### ISSUE TITLE
Beta - 1.14.6 - Keyboard Samsung does not break line

### ISSUE THREAD

**Issue by ElaineSchwner** [flutter/flutter#51864] opened 2020-03-03 17:16 UTC
#51635  Steps to Reproduce

With TextField, even using TextInputType.multiline and maxline: null, only with Samsung keyboards when pressing Enter, it doesn`t break lines.

TextField(
        minLines: min,
        maxLines: null,
        keyboardType: TextInputType.multiline,
        controller: controller,
        decoration: InputDecoration(
          focusedBorder: OutlineInputBorder(
            borderSide: BorderSide(
                color: Cores().corprincipal, width: 1.5),
          ),
          enabledBorder: OutlineInputBorder(
            borderSide: BorderSide(
                color: Colors.grey[300], width: 1.5),
          ),
          labelText: placeholder,
          labelStyle: TextStyle(
              letterSpacing: 1.0, fontSize: 12.0,
              fontWeight: FontWeight.w400),
        ),
  
        autofocus: false,
        obscureText: obs,
        textAlign: TextAlign.center,
        style: TextStyle(color: Colors.black, fontWeight: FontWeight.w700),
      ),

**Comment by TahaTesser** [comment] 2020-03-04 09:56
Duplicate of [#49796](https://github.com/flutter/flutter/issues/49796)

**Closed by TahaTesser** 2020-03-04 09:56 UTC
