### ISSUE TITLE
Flutter 3.13.4 `BoxShadow` fades widget on iOS

### ISSUE THREAD

**Issue by feinstein** [flutter/flutter#135084] opened 2023-09-20 01:00 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Run the sample code, as you can see in the screenshots the `BoxShadow` fades the top and top-left edges of the Cards.

It was working fine in Flutter 3.0.7.

It works on Android, this bug is iOS only, so I am betting it's Impeller related.

The issue seems to be related with the `Card` `clipBehavior: Clip.antiAliasWithSaveLayer`. We need it for the splash effect of the `InkWell`, otherwise the splash isn't clipped to the rounded edges of the `Card`.

### Expected results

The shadows would be the same in 3.13.4 as they were in 3.0.7 and as they are in Android.

### Actual results

The shadows fade the top and top-left corners of the cards in iOS.

### Code sample

<details><summary>Code sample</summary>

```dart

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Shadows regression demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const HomePage(),
    );
  }
}

class HomePage extends StatelessWidget {
  const HomePage({super.key});

 @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: const Color(0xFFEFECE9),
      body: Padding(
        padding: const EdgeInsets.all(16.0),
        child: Center(
          child: ListTileButton.icon(
            icon: Icons.add,
            color: Colors.blue,
            title: 'Title',
            subtitle: 'Subtitle',
            onPressed: () {},
          ),
        ),
      ),
    );
  }
}


class ListTileButton extends StatelessWidget {
  ListTileButton.icon({
    required IconData icon,
    required Color color,
    required this.title,
    super.key,
    this.subtitle,
    this.onPressed,
    this.isExternalLink = false,
  }) : leading = Icon(
    icon,
    size: iconSize,
    color: color,
  );

  static const iconSize = 48.0;

  final Widget leading;
  final String title;
  final String? subtitle;
  final VoidCallback? onPressed;
  final bool isExternalLink;

  @override
  Widget build(BuildContext context) {
    final subtitle = this.subtitle;

    return Opacity(
      opacity: onPressed == null ? 0.5 : 1,
      child: DecoratedBox(
        decoration: const BoxDecoration(
          boxShadow: [
            BoxShadow(
              color: Color(0x0C000000),
              blurRadius: 10,
              offset: Offset(0, 10),
            ),
          ],
        ),
        child: Card(
          clipBehavior: Clip.antiAliasWithSaveLayer,
          elevation: 0,
          surfaceTintColor: Colors.transparent,
          shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(5)),
          child: InkWell(
            onTap: onPressed,
            child: ListTile(
              leading: leading,
              title: Text(title),
              subtitle: subtitle != null ? Text(subtitle) : null,
              trailing: Icon(
                isExternalLink ? Icons.open_in_new : Icons.arrow_forward_ios_outlined,
              ),
            ),
          ),
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

### Bug in iOS and Flutter 3.13.4:

![Simulator Screenshot - iPhone 14 Pro Max - 2023-09-20 at 10 22 34](https://github.com/flutter/flutter/assets/8120472/e75ed367-f452-4e3f-88f6-189c87a1e441)

### No bug in iOS and Flutter 3.0.7:
![Simulator Screenshot - iPhone 14 Pro Max - 2023-09-20 at 10 20 23](https://github.com/flutter/flutter/assets/8120472/94de109f-fa0c-4ee9-9ffb-dd210eb7e5ab)

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[!] Flutter (Channel stable, 3.13.4, on macOS 13.4.1 22F770820d darwin-arm64 (Rosetta), locale en-AU)
    • Flutter version 3.13.4 on channel stable at /Users/michelfeinstein/.puro/envs/stable/flutter
    ! Warning: `flutter` on your path resolves to /opt/homebrew/Caskroom/flutter/3.10.6/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at
      /Users/michelfeinstein/.puro/envs/stable/flutter. Consider adding /Users/michelfeinstein/.puro/envs/stable/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /opt/homebrew/Caskroom/flutter/3.10.6/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/michelfeinstein/.puro/envs/stable/flutter.
      Consider adding /Users/michelfeinstein/.puro/envs/stable/flutter/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 367f9ea16b (7 days ago), 2023-09-12 23:27:53 -0500
    • Engine revision 9064459a8b
    • Dart version 3.1.2
    • DevTools version 2.25.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/michelfeinstein/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/michelfeinstein/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.81.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.70.0

[✓] Connected device (4 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554                        • android-arm64  • Android 14 (API 34) (emulator)
    • iPhone 14 Pro Max (mobile)  • 13DBD18F-5D40-43FE-A23A-383422DB6EFF • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)             • macos                                • darwin-arm64   • macOS 13.4.1 22F770820d darwin-arm64 (Rosetta)
    • Chrome (web)                • chrome                               • web-javascript • Google Chrome 117.0.5938.88

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

**Comment by dam-ease** [comment] 2023-09-20 09:26
Hi @feinstein. Thanks for filing this issue. I can reproduce this issue on the latest `stable` channel but this seems to be fixed on the latest `master` as I can't see a fade on master (screenshot below). 

![Simulator Screenshot - iPhone 14 Pro Max - 2023-09-20 at 10 22 55](https://github.com/flutter/flutter/assets/53122008/bf8bee05-9143-4113-b80d-b43795102a43)

<details><summary>master flutter doctor -v</summary>
<p>

```
[✓] Flutter (Channel master, 3.14.0-14.0.pre.358, on macOS 13.0 22A380 darwin-arm64, locale en-NG)
    • Flutter version 3.14.0-14.0.pre.358 on channel master at /Users/damilolaalimi/fvm/versions/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 8936504163 (3 hours ago), 2023-09-19 02:10:24 -0400
    • Engine revision 589bde9a95
    • Dart version 3.2.0 (build 3.2.0-174.0.dev)
    • DevTools version 2.28.0-dev.8

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/damilolaalimi/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/damilolaalimi/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.82.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (4 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554                        • android-arm64  • Android 14 (API 34) (emulator)
    • iPhone 14 Pro Max (mobile)  • BB55E997-7F31-462D-B3B1-6B177D9B40C7 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)             • macos                                • darwin-arm64   • macOS 13.0 22A380 darwin-arm64
    • Chrome (web)                • chrome                               • web-javascript • Google Chrome 116.0.5845.187

[✓] Network resources
    • All expected network resources are available.

• No issues found!
``` 

</p>
</details>

Closing this as it has been fixed in latest versions, if you disagree, kindly comment and I'd reopen this.
Thank you.

**Closed by dam-ease** 2023-09-20 09:26 UTC
Labels: in triage

**Comment by feinstein** [comment] 2023-09-20 10:48
Ok, thanks. I hope this comes out in the next release.

**Comment by elegeiac** [comment] 2023-10-01 06:29
> Hi @feinstein. Thanks for filing this issue. I can reproduce this issue on the latest `stable` channel but this seems to be fixed on the latest `master` as I can't see a fade on master (screenshot below).
> 
> ![Simulator Screenshot - iPhone 14 Pro Max - 2023-09-20 at 10 22 55](https://user-images.githubusercontent.com/53122008/269235218-bf8bee05-9143-4113-b80d-b43795102a43.png)
> 
> master flutter doctor -v
> Closing this as it has been fixed in latest versions, if you disagree, kindly comment and I'd reopen this. Thank you.

The issue still exists on my side, the shadow seems to not be working on the table calendar wrapped with a container(which has the box shadow). It works fine in android and older version of flutter. 

![Screenshot 2023-10-01 at 12 12 08](https://github.com/flutter/flutter/assets/59821178/081bae53-de94-4eec-a6eb-1d0f4857e3ed)

![Screenshot 2023-10-01 at 12 12 19](https://github.com/flutter/flutter/assets/59821178/0ee3c508-7af0-49de-ad46-1416069c0107)

**Comment by feinstein** [comment] 2023-10-01 09:12
@elegeiac Have you tested on the master channel? It was closed because it was fixed on master.

**Comment by elegeiac** [comment] 2023-10-03 05:36
> @elegeiac Have you tested on the master channel? It was closed because it was fixed on master.

Thanks! it was fixed on master. Any idea on how long does it roughly take for it to be fixed in the stable channel.

**Comment by feinstein** [comment] 2023-10-03 05:47
I don't think there's a way for you to get an estimation, but you can request a cherry pick and get it quicker https://github.com/flutter/flutter/wiki/Flutter-Cherrypick-Process.
