### ISSUE TITLE
[tool_crash] ProcessException: Process timed out: Command: xcrun, OS error code: -1

### ISSUE THREAD

**Issue by skylurk** [flutter/flutter#71168] opened 2020-11-24 19:53 UTC
## Command
```
flutter build ios
```

## Steps to Reproduce
1. Create flutter a
2. Add dependencies and make necessary adjustments on Xcode
3. run flutter build iOS

## Logs
ProcessException: Process timed out:
 Command: xcrun, OS error code: -1
```
#0      RunResult.throwException (package:flutter_tools/src/base/process.dart:172:5)
#1      _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart:395:19)
<asynchronous suspension>
#2      buildXcodeProject (package:flutter_tools/src/ios/mac.dart:368:74)
#3      _rootRunUnary (dart:async/zone.dart:1198:47)
#4      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#5      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#7      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#8      Future._completeWithValue (dart:async/future_impl.dart:529:5)
#9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:291:13)
#11     _runBuildWithRetries (package:flutter_tools/src/ios/mac.dart)
#12     _rootRunUnary (dart:async/zone.dart:1198:47)
#13     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#14     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#16     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#17     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#18     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#19     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:291:13)
#20     _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart)
#21     _rootRunUnary (dart:async/zone.dart:1198:47)
#22     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#23     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
```
```
[✓] Flutter (Channel dev, 1.24.0-7.0.pre, on Mac OS X 10.15.1 19B77a darwin-x64, locale en-GB)
    • Flutter version 1.24.0-7.0.pre at /Users/david/Downloads/Developer/flutter
    • Framework revision a0860f6e87 (4 weeks ago), 2020-10-29 20:07:34 -0700
    • Engine revision 073263e39d
    • Dart version 2.11.0 (build 2.11.0-260.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/david/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2, Build version 11B52
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2020.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 47.0.3
    • Dart plugin version 201.7846.93

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: dev
**Creation framework version**: a0860f6e87ba4f9031bee4d6f56c08b970606bee
### Plugins
cloud_firestore-0.13.7
cloud_firestore_web-0.1.1+2
firebase_auth-0.15.5+3
firebase_auth_web-0.1.3+1
firebase_core-0.4.5
firebase_core_web-0.1.1+2
firebase_database-3.1.6
firebase_storage-3.1.6
flutter_barcode_scanner-1.0.1
flutter_plugin_android_lifecycle-1.0.11
image_cropper-1.3.1
image_picker-0.6.7+14
path_provider-1.6.24
path_provider_linux-0.0.1+2
path_provider_macos-0.0.4+6
path_provider_windows-0.0.4+3
sqflite-1.3.2+1

**Comment by sidrao2006** [comment] 2020-11-25 03:35
Duplicate of #69020
Hey @ , I found an issue addressing this problem. Please post the output of `flutter doctor -v` and follow up there.

Thanks.

**Comment by darshankawar** [comment] 2020-11-25 07:20
Closing this as duplicate of [47633](https://github.com/flutter/flutter/issues/47633)

**Closed by darshankawar** 2020-11-25 07:20 UTC
