### ISSUE TITLE
[tool_crash] FileSystemException: Cannot create link, OS Error: Permission denied, errno = 13

### ISSUE THREAD

**Issue by Adalat-Kumar** [flutter/flutter#99531] opened 2022-03-04 04:47 UTC
## Command
```
flutter pub get
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Cannot create link, OS Error: Permission denied, errno = 13
```
#0      _Link.throwIfError (dart:io/link.dart:263:7)
#1      _Link.createSync (dart:io/link.dart:184:5)
#2      ForwardingLink.createSync (package:file/src/forwarding/forwarding_link.dart:20:16)
#3      ForwardingLink.createSync (package:file/src/forwarding/forwarding_link.dart:20:16)
#4      _createPlatformPluginSymlinks (package:flutter_tools/src/flutter_plugins.dart:1029:12)
#5      createPluginSymlinks (package:flutter_tools/src/flutter_plugins.dart:964:5)
#6      refreshPluginsList (package:flutter_tools/src/flutter_plugins.dart:1055:5)
<asynchronous suspension>
#7      FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:316:5)
<asynchronous suspension>
#8      PackagesGetCommand.runCommand (package:flutter_tools/src/commands/packages.dart:177:5)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1161:27)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#11     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
<asynchronous suspension>
#15     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
```
```
[✓] Flutter (Channel stable, 2.10.2, on Ubuntu 21.10
    5.4.0-faked, locale C.UTF-8)
    • Flutter version 2.10.2 at /home/adalat/flutter
    • Upstream repository
      https://github.com/flutter/flutter.git
    • Framework revision 097d3313d8 (13 days ago),
      2022-02-18 19:33:08 -0600
    • Engine revision a83ed0e5e3
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✗] Chrome - develop for the web (Cannot find Chrome
    executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to
      a Chrome executable.

[✗] Flutter IDE Support (No supported IDEs installed)
    • IntelliJ - https://www.jetbrains.com/idea/
    • Android Studio -
      https://developer.android.com/studio/
    • VS Code - https://code.visualstudio.com/

[!] Connected device
    ! No devices available

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 3 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: db747aa1331bd95bc9b3874c842261ca2d302cd5
### Plugins
cloud_firestore-3.1.8
cloud_firestore_web-2.6.8
file_picker-4.4.0
firebase_auth-3.3.7
firebase_auth_web-3.3.7
firebase_core-1.12.0
firebase_core_web-1.6.1
firebase_storage-10.2.9
firebase_storage_web-3.2.10
flutter_plugin_android_lifecycle-2.0.5
path_provider-2.0.9
path_provider_android-2.0.11
path_provider_ios-2.0.7
path_provider_linux-2.1.5
path_provider_macos-2.0.5
path_provider_windows-2.0.5
sqflite-2.0.2

**Comment by danagbemava-nc** [comment] 2022-03-04 09:40
Duplicate of #96568

**Closed by danagbemava-nc** 2022-03-04 09:40 UTC
Labels: in triage
