### ISSUE TITLE
[url_launcher] doesn't work when iOS default browser is not set to Safari

### ISSUE THREAD

**Issue by emaddoma** [flutter/flutter#67647] opened 2020-10-08 16:09 UTC
## Steps to Reproduce

Implement can_launch() and launch()

**Expected results:** 

The url launches

**Actual results:** 

Nothing happens at all

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by darshankawar** [comment] 2020-10-09 08:28
Closing this as duplicate of [65936](https://github.com/flutter/flutter/issues/65936)

**Closed by darshankawar** 2020-10-09 08:28 UTC
