### ISSUE TITLE
[google_maps_flutter] Markers showing info window when consumeTapEvents is false

### ISSUE THREAD

**Issue by JamesMcIntosh** [flutter/flutter#54807] opened 2020-04-15 02:22 UTC
## Steps to Reproduce

Create a marker and set `consumeTapEvents` as false.
```
Marker(
    markerId: MarkerId("abc123"),
    position: markerLatLng,
    consumeTapEvents: false,
)
```

**Expected results:**

Nothing happens

**Actual results:** 

When you tap the marker the info window is shown

**Comment by TahaTesser** [comment] 2021-03-03 14:12
Hi!
Here I created a minimal runnable code sample. to demonstrate the issue.


<details>
<summary>code sample</summary>

```dart

<details>
<summary>code sample</summary>

```dart
import 'dart:async';

import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Google Maps Demo',
      home: MapSample(),
    );
  }
}

class MapSample extends StatefulWidget {
  @override
  State<MapSample> createState() => MapSampleState();
}

class MapSampleState extends State<MapSample> {
  Completer<GoogleMapController> _controller = Completer();

  static final CameraPosition _kGooglePlex = CameraPosition(
    target: LatLng(37.42796133580664, -122.085749655962),
    zoom: 14.4746,
  );

  Map<MarkerId, Marker> markers =
      <MarkerId, Marker>{}; // CLASS MEMBER, MAP OF MARKS

  void _add() {
    final int markerCount = markers.length;

    if (markerCount == 12) {
      return;
    }

    final String markerIdVal = 'marker';
    final MarkerId markerId = MarkerId(markerIdVal);

    final Marker marker = Marker(
      markerId: markerId,
      position: LatLng(
        37.43296265331129,
        -122.08832357078792,
      ),
      consumeTapEvents: true,
      infoWindow: InfoWindow(title: markerIdVal, snippet: '*'),
      onTap: () {
        print("marker is tapped");
      },
      onDragEnd: (LatLng position) {},
    );

    setState(() {
      markers[markerId] = marker;
    });
  }

  static final CameraPosition _kLake = CameraPosition(
      bearing: 192.8334901395799,
      target: LatLng(37.43296265331129, -122.08832357078792),
      tilt: 59.440717697143555,
      zoom: 19.151926040649414);

  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      body: GoogleMap(
        mapType: MapType.hybrid,
        markers: Set<Marker>.of(markers.values), // YOUR MARKS IN MAP

        initialCameraPosition: _kGooglePlex,
        onMapCreated: (GoogleMapController controller) {
          _controller.complete(controller);
        },
      ),
      floatingActionButton: FloatingActionButton.extended(
        // onPressed: _goToTheLake,
        onPressed: () {
          _add();
        },
        label: Text('To the lake!'),
        icon: Icon(Icons.directions_boat),
      ),
    );
  }

  Future<void> _goToTheLake() async {
    final GoogleMapController controller = await _controller.future;
    controller.animateCamera(CameraUpdate.newCameraPosition(_kLake));
  }
}

```

</details>



<details>
<summary>logs</summary>

```bash
[        ] Performing hot restart...
[   +7 ms] Scanned through 511 files in 6ms
[        ] Syncing files to device iPhone 12...
[        ] <- reset
[        ] Compiling dart to kernel with 0 updated files
[   +1 ms] <- recompile package:triage/main.dart 819a8062-8056-4152-93d6-c598422631e6
[        ] <- 819a8062-8056-4152-93d6-c598422631e6
[ +110 ms] Updating files.
[  +29 ms] DevFS: Sync finished
[        ] Syncing files to device iPhone 12... (completed in 142ms)
[        ] Synced 25.6MB.
[        ] <- accept
[ +364 ms] Hot restart performed in 514ms.
[        ] Performing hot restart... (completed in 514ms)
[        ] Restarted application in 520ms.
[+3429 ms] flutter: marker is tapped
[+2494 ms] flutter: marker is tapped
[ +757 ms] flutter: marker is tapped
[+2601 ms] flutter: marker is tapped

```

</details>

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 1.22.6, on macOS 11.2.2 20D80 darwin-x64, locale
    en-GB)
    • Flutter version 1.22.6 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 9b2d32b605 (6 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.53.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (2 available)
    • Taha’s iPad (mobile) • 00008020-000255113EE8402E            • ios • iOS
      14.4
    • iPhone 12 (mobile)   • 948EC106-78EE-4A69-8D31-83C00E6419DE • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)

! Doctor found issues in 1 category.
```

</details>


Thanks for filing the issue

**Comment by TahaTesser** [comment] 2021-05-13 14:45
Reproduced on the following channels on the latest `google_maps_flutter: ^2.0.3`
|  `stable`  | `master` |
| :---: |:---: |
|  ✅  |   ✅  | 

Check `flutter doctor -v` outputs for each channel below

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.0.6, on Microsoft Windows [Version 10.0.19042.928], locale en-US)
    • Flutter version 2.0.6 at C:\Users\Taha\Code\flutter_stable
    • Framework revision 1d9032c7e1 (2 weeks ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\Taha\Code\SDK
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.9.31205.134
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Users\Taha\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[✓] IntelliJ IDEA Community Edition (version 2021.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.3.3
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.56.1)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.22.0

[✓] Connected device (4 available)
    • IN2011 (mobile)   • c9d8ee0c • android-arm64  • Android 11 (API 30)
    • Windows (desktop) • windows  • windows-x64    • Microsoft Windows [Version 10.0.19042.928]
    • Chrome (web)      • chrome   • web-javascript • Google Chrome 90.0.4430.212
    • Edge (web)        • edge     • web-javascript • Microsoft Edge 90.0.818.56

• No issues found!
```

```console
[✓] Flutter (Channel master, 2.3.0-2.0.pre.163, on Microsoft Windows [Version 10.0.19042.928], locale en-US)
    • Flutter version 2.3.0-2.0.pre.163 at C:\Users\Taha\Code\flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 298f18b592 (11 hours ago), 2021-05-12 20:50:14 -0700
    • Engine revision a339374296
    • Dart version 2.14.0 (build 2.14.0-109.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\Taha\Code\SDK
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.9.31205.134
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Users\Taha\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[✓] IntelliJ IDEA Community Edition (version 2021.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.3.3
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.56.1)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.22.0

[✓] Connected device (4 available)
    • IN2011 (mobile)   • c9d8ee0c • android-arm64  • Android 11 (API 30)
    • Windows (desktop) • windows  • windows-x64    • Microsoft Windows [Version 10.0.19042.928]
    • Chrome (web)      • chrome   • web-javascript • Google Chrome 90.0.4430.212
    • Edge (web)        • edge     • web-javascript • Microsoft Edge 90.0.818.56

• No issues found!
```
		
</details>

**Comment by stuartmorgan** [comment] 2021-05-13 15:13
Closing as a duplicate of https://github.com/flutter/flutter/issues/39868 (I'm not sure why this was filed twice).

**Closed by stuartmorgan** 2021-05-13 15:13 UTC
Labels: found in release: 1.22, found in release: 2.0, found in release: 2.3, has reproducible steps, p: first party, p: maps, plugin
