### ISSUE TITLE
[Web] DropdownButtonFormField decoration issues 

### ISSUE THREAD

**Issue by tekno0ryder** [flutter/flutter#72111] opened 2020-12-11 00:42 UTC
## Steps to Reproduce

I found two issues when including **LabelText** property with the following properties:

1. Uncomment (filled and filledColor) theme properties.
2. Second value and icon of dropdown field will disappear.

1. Uncomment (border) theme property
2. Second dropdown field will have black border

### Screenshot of the 2 issues combined

![Screenshot_3](https://user-images.githubusercontent.com/8721803/101846796-c1d92780-3b62-11eb-8853-209fb3943aea.png)

<details>
  <summary>Sample App</summary>

```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(
        inputDecorationTheme: InputDecorationTheme(
          // 1: Causes second dropdown selected value to disappear

          // filled: true,
          // fillColor: Colors.blue.shade50,

          // 2: Causes second dropdown to have black border

          // border: OutlineInputBorder(
          //     borderSide: BorderSide.none,
          //     borderRadius: BorderRadius.circular(16.0)),
        ),
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final _formKey = GlobalKey<FormState>();

  final items1 = ["1", "2"];
  final items2 = ["10", "20"];

  String selectedItem1 = "1";
  String selectedItem2 = "10";

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: Form(
        key: _formKey,
        child: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              DropdownButtonFormField<String>(
                decoration: InputDecoration(labelText: "Item 1"),
                value: selectedItem1,
                items: [
                  for (var item in items1)
                    DropdownMenuItem(
                      value: item,
                      child: Text(item),
                    )
                ],
                onChanged: (newItem) => setState(() {
                  selectedItem1 = newItem;
                }),
              ),
              SizedBox(height: 16),
              Flexible(
                child: DropdownButtonFormField<String>(
                  decoration: InputDecoration(labelText: "Item 2"),
                  value: selectedItem2,
                  items: [
                    for (var item in items2)
                      DropdownMenuItem(
                        value: item,
                        child: Text(item),
                      )
                  ],
                  onChanged: (newItem) => setState(() {
                    selectedItem2 = newItem;
                  }),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
```
</details>

<details>
  <summary>Logs</summary>

```
Running "flutter pub get" in dropdown...                           422ms
Analyzing dropdown...                                                   
No issues found! (ran in 2.1s)
```

```
[√] Flutter (Channel beta, 1.24.0-10.2.pre, on Microsoft Windows [Version
    10.0.19042.685], locale en-US)
    • Flutter version 1.24.0-10.2.pre at c:\flutter
    • Framework revision 022b333a08 (3 weeks ago), 2020-11-18 11:35:09 -0800
    • Engine revision 07c1eed46b
    • Dart version 2.12.0 (build 2.12.0-29.10.beta)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Users\Ryder\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.51.1)
    • VS Code at C:\Users\Ryder\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.17.0
```

</details>

**Comment by iapicca** [comment] 2020-12-11 07:44
duplicate of https://github.com/flutter/flutter/issues/70980

**Comment by pedromassangocode** [comment] 2020-12-11 08:06
Closing as duplicate of https://github.com/flutter/flutter/issues/70980.

**Closed by pedromassangocode** 2020-12-11 08:06 UTC
