### ISSUE TITLE
Execution failed for task ':app:compressDebugAssets'. on EXFAT Partition

### ISSUE THREAD

**Issue by afzl-wtu** [flutter/flutter#80719] opened 2021-04-19 13:04 UTC
Whenever I create a new project at exfat partition it shows the error  on Windows 10:
Execution failed for task ':app:compressDebugAssets'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CompressAssetsWorkAction
   > E:\@Projects\Flutter\flutter_application_1\build\app\intermediates\merged_assets\debug\out

**Comment by TahaTesser** [comment] 2021-04-19 13:35
Hi @afzl-wtu 
Can you please provide your `flutter doctor -v` and logs commands below

`flutter create myapp -v`
`cd myapp`
`flutter run -v`
Thank you

**Comment by afzl-wtu** [comment] 2021-04-19 14:40
> 
> 
> Hi @afzl-wtu
> Can you please provide your `flutter doctor -v` and logs commands below
> 
> `flutter create myapp -v`
> `cd myapp`
> `flutter run -v`
> Thank you

All mentioned commands result is in this text file: 
[New Text Document.txt](https://github.com/flutter/flutter/files/6336892/New.Text.Document.txt)

**Comment by TahaTesser** [comment] 2021-04-20 06:50
Hi @afzl-wtu 
This looks like an issue with your gradle cache,
Can you please `.gradle` (hidden folder) from `C:\Users\YourUser`, this will delete your local gradle and then run the app, flutter will get new gradle cache and wait for the app to run, it will take some time to download (do not cancel the process)

**Comment by afzl-wtu** [comment] 2021-04-20 12:06
> 
> 
> Hi @afzl-wtu
> This looks like an issue with your gradle cache,
> Can you please `.gradle` (hidden folder) from `C:\Users\YourUser`, this will delete your local gradle and `build` folder from you app folder and then run the app, flutter will get new gradle cache and wait for the app to run, it will take some time to download (do not cancel the process)

Hi I again followed your instructions and deleted .gradle folder from my User folder. Also I have reformatted my exFAT partition. So result of :
flutter create -v test_app: 
[log.txt](https://github.com/flutter/flutter/files/6343297/log.txt) Worked fine as worked before.

flutter run -v : 
[log.txt](https://github.com/flutter/flutter/files/6343308/log.txt)
Again Error even it downloaded the gradle from start. The main issue is still **there Flutter do not work in exFAT partition** on Windows 10. If I create and run the project on NTFS partition , IT WORKS GREAT.

**STEPS TO REPRODUCE THE PROBLEM:**
1. Format a new partition to to exFAT instead of NTFS in Windows 10.
2. Create and run new flutter application project.

**Comment by TahaTesser** [comment] 2021-04-21 07:23
Hi @afzl-wtu 
Thanks for the details, I can reproduce the issue using exFat partition and also from exFat formatted Pendrive.



This is an issue with Gradle itself on exFat, as windows and chrome runs fine from Flutter using exFat
When Google search, I can see other exFat issues with Gradle, please file an issue on their dedicated GitHub https://github.com/gradle/gradle/issues




<details> 
<summary>logs</summary> 

```console
PS D:\projects\myapp> flutters run -v
[  +78 ms] executing: [C:\Users\Taha\Code\flutter_stable/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +56 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] adc687823a831bbebe28bdccfac1a628ca621513
[   +1 ms] executing: [C:\Users\Taha\Code\flutter_stable/] git tag --points-at adc687823a831bbebe28bdccfac1a628ca621513
[  +38 ms] Exit code 0 from: git tag --points-at adc687823a831bbebe28bdccfac1a628ca621513
[        ] 2.0.5
[  +35 ms] executing: [C:\Users\Taha\Code\flutter_stable/] git rev-parse --abbrev-ref --symbolic @{u}
[  +30 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\Users\Taha\Code\flutter_stable/] git ls-remote --get-url origin
[  +26 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +60 ms] executing: [C:\Users\Taha\Code\flutter_stable/] git rev-parse --abbrev-ref HEAD
[  +28 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +79 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +51 ms] executing: C:\Users\Taha\Code\SDK\platform-tools\adb.exe devices -l
[  +42 ms] List of devices attached
           emulator-5554          device product:sdk_gphone_x86 model:Android_SDK_built_for_x86 device:generic_x86
           transport_id:2
[  +10 ms] C:\Users\Taha\Code\SDK\platform-tools\adb.exe -s emulator-5554 shell getprop
[  +45 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +5 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +79 ms] Skipping pub get: version match.
[ +132 ms] Generating D:\projects\myapp\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[ +496 ms] ro.hardware = ranchu
[  +12 ms] Using hardware rendering with device Android SDK built for x86. If you notice graphics artifacts, consider
enabling
           software rendering with "--enable-software-rendering".
[  +22 ms] Initializing file store
[  +10 ms] Skipping target: gen_localizations
[  +75 ms] complete
[   +4 ms] Launching lib\main.dart on Android SDK built for x86 in debug mode...
[   +5 ms] C:\Users\Taha\Code\flutter_stable\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev
C:\Users\Taha\Code\flutter_stable\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root
C:\Users\Taha\Code\flutter_stable\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --incremental --target=flutter
--debugger-module-names --experimental-emit-debug-metadata --output-dill
C:\Users\Taha\AppData\Local\Temp\flutter_tools.1b6bc779\flutter_tool.2c0f66d6\app.dill --packages
D:\projects\myapp\.dart_tool\package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts
--track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill build\cache.dill.track.dill
[  +23 ms] executing: C:\Users\Taha\Code\SDK\platform-tools\adb.exe -s emulator-5554 shell -x logcat -v time -t 1
[  +11 ms] <- compile package:myapp/main.dart
[  +36 ms] --------- beginning of main
           04-21 10:11:17.510 I/MicroDetectionWorker( 3845): #onError(false)
[  +10 ms] executing: C:\Users\Taha\Code\SDK\platform-tools\adb.exe version
[  +40 ms] Android Debug Bridge version 1.0.41
           Version 31.0.1-7187441
           Installed as C:\Users\Taha\Code\SDK\platform-tools\adb.exe
[   +2 ms] executing: C:\Users\Taha\Code\SDK\platform-tools\adb.exe start-server
[  +19 ms] Building APK
[ +256 ms] Running Gradle task 'assembleDebug'...
[   +5 ms] Using gradle from D:\projects\myapp\android\gradlew.bat.
[   +1 ms] D:\projects\myapp\android\gradlew.bat mode: 33279 rwxrwxrwx.
[   +6 ms] executing: C:\Users\Taha\Code\android-studio\jre\bin\java -version
[  +82 ms] Exit code 0 from: C:\Users\Taha\Code\android-studio\jre\bin\java -version
[        ] openjdk version "1.8.0_242-release"
           OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
           OpenJDK 64-Bit Server VM (build 25.242-b01, mixed mode)
[   +2 ms] executing: [D:\projects\myapp\android/] D:\projects\myapp\android\gradlew.bat -Pverbose=true
-Ptarget-platform=android-x86 -Ptarget=D:\projects\myapp\lib\main.dart -Ptrack-widget-creation=true
-Pfilesystem-scheme=org-dartlang-root assembleDebug
[+4521 ms] > Task :app:compileFlutterBuildDebug
[   +1 ms] [  +70 ms] executing: [C:\Users\Taha\Code\flutter_stable/] git -c log.showSignature=false log -n 1
--pretty=format:%H
[   +1 ms] [  +58 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] [        ] adc687823a831bbebe28bdccfac1a628ca621513
[        ] [        ] executing: [C:\Users\Taha\Code\flutter_stable/] git tag --points-at
adc687823a831bbebe28bdccfac1a628ca621513
[   +1 ms] [  +42 ms] Exit code 0 from: git tag --points-at adc687823a831bbebe28bdccfac1a628ca621513
[        ] [        ] 2.0.5
[        ] [  +34 ms] executing: [C:\Users\Taha\Code\flutter_stable/] git rev-parse --abbrev-ref --symbolic @{u}
[        ] [  +28 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] [        ] origin/stable
[        ] [        ] executing: [C:\Users\Taha\Code\flutter_stable/] git ls-remote --get-url origin
[        ] [  +27 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] [        ] https://github.com/flutter/flutter.git
[        ] [  +60 ms] executing: [C:\Users\Taha\Code\flutter_stable/] git rev-parse --abbrev-ref HEAD
[        ] [  +28 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] [        ] stable
[        ] [  +45 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [  +54 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[        ] [  +84 ms] Initializing file store
[        ] [  +12 ms] Skipping target: gen_localizations
[        ] [  +42 ms] kernel_snapshot: Starting due to {}
[        ] [  +20 ms] C:\Users\Taha\Code\flutter_stable\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev
C:\Users\Taha\Code\flutter_stable\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root
C:\Users\Taha\Code\flutter_stable\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --target=flutter
--no-print-incremental-dependencies -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts
--track-widget-creation --no-link-platform --packages D:\projects\myapp\.dart_tool\package_config.json --output-dill
D:\projects\myapp\.dart_tool\flutter_build\a273a2e22d3b337d68556a1f8a702d3a\app.dill --depfile
D:\projects\myapp\.dart_tool\flutter_build\a273a2e22d3b337d68556a1f8a702d3a\kernel_snapshot.d package:myapp/main.dart
[+13871 ms] [+14482 ms] kernel_snapshot: Complete
[ +592 ms] [ +622 ms] debug_android_application: Starting due to {}
[+2997 ms] [+2957 ms] debug_android_application: Complete
[ +506 ms] [ +533 ms] Persisting file store
[  +93 ms] [ +100 ms] Done persisting file store
[ +110 ms] [  +72 ms] build succeeded.
[   +1 ms] [  +49 ms] "flutter assemble" took 19,054ms.
[        ] [   +2 ms] ensureAnalyticsSent: 0ms
[        ] [        ] Running shutdown hooks
[        ] [        ] Shutdown hooks complete
[        ] [        ] exiting with code 0
[ +292 ms] > Task :app:packLibsflutterBuildDebug
[   +1 ms] > Task :app:preBuild UP-TO-DATE
[   +1 ms] > Task :app:preDebugBuild UP-TO-DATE
[   +1 ms] > Task :app:compileDebugAidl NO-SOURCE
[        ] > Task :app:compileDebugRenderscript NO-SOURCE
[ +295 ms] > Task :app:generateDebugBuildConfig
[  +93 ms] > Task :app:checkDebugAarMetadata
[   +1 ms] > Task :app:cleanMergeDebugAssets UP-TO-DATE
[ +296 ms] > Task :app:mergeDebugShaders
[   +1 ms] > Task :app:compileDebugShaders NO-SOURCE
[        ] > Task :app:generateDebugAssets UP-TO-DATE
[ +199 ms] > Task :app:mergeDebugAssets
[+28308 ms] > Task :app:copyFlutterAssetsDebug
[ +189 ms] > Task :app:generateDebugResValues
[   +1 ms] > Task :app:generateDebugResources
[+10208 ms] > Task :app:createDebugCompatibleScreenManifests
[ +688 ms] > Task :app:extractDeepLinksDebug
[+2708 ms] > Task :app:processDebugMainManifest
[  +92 ms] > Task :app:mergeDebugResources
[ +109 ms] > Task :app:processDebugManifest
[ +204 ms] > Task :app:mergeDebugNativeDebugMetadata NO-SOURCE
[   +1 ms] > Task :app:javaPreCompileDebug
[  +92 ms] > Task :app:processDebugJavaRes NO-SOURCE
[  +93 ms] > Task :app:compressDebugAssets FAILED
[ +109 ms] > Task :app:checkDebugDuplicateClasses
[   +1 ms] > Task :app:processDebugManifestForPackage
[   +2 ms] Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
[        ] Use '--warning-mode all' to show the individual deprecation warnings.
[        ] See https://docs.gradle.org/6.7/userguide/command_line_interface.html#sec:command_line_warnings
[        ] 18 actionable tasks: 17 executed, 1 up-to-date
[        ] FAILURE: Build failed with an exception.
[   +1 ms] * What went wrong:
[        ] Execution failed for task ':app:compressDebugAssets'.
[        ] > A failure occurred while executing com.android.build.gradle.internal.tasks.CompressAssetsWorkAction
[        ]    > D:\projects\myapp\build\app\intermediates\merged_assets\debug\out
[        ] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log
output. Run with --scan to get full insights.
[        ] * Get more help at https://help.gradle.org
[        ] BUILD FAILED in 1m 6s
[ +832 ms] Running Gradle task 'assembleDebug'... (completed in 67.7s)
[   +4 ms] Exception: Gradle task assembleDebug failed with exit code 1
[   +2 ms] "flutter run" took 69,116ms.
[   +4 ms]
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:644:9)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1157:12)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command.dart:1009:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #6      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command_runner.dart:278:9)
           <asynchronous suspension>
           #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #9      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #10     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:234:5)
           <asynchronous suspension>
           #11     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
           <asynchronous suspension>
           #12     run.<anonymous closure> (package:flutter_tools/runner.dart:62:12)
           <asynchronous suspension>
           #13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #14     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #15     runInContext (package:flutter_tools/src/context_runner.dart:73:10)
           <asynchronous suspension>
           #16     main (package:flutter_tools/executable.dart:90:3)
           <asynchronous suspension>


[ +259 ms] ensureAnalyticsSent: 256ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hook priority 4
[   +3 ms] Shutdown hooks complete
[   +1 ms] exiting with code 1
PS D:\projects\myapp>
```

</details>

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 2.0.5, on Microsoft Windows [Version 10.0.19042.928], locale en-US)
    • Flutter version 2.0.5 at C:\Users\Taha\Code\flutter_stable
    • Framework revision adc687823a (5 days ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\Taha\Code\SDK
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.3)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.9.31129.286
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Users\Taha\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] IntelliJ IDEA Community Edition (version 2021.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.3.3
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.55.2)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.21.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19042.928]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 89.0.4389.128
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 89.0.774.77

! Doctor found issues in 1 category.
```

```bash
[✓] Flutter (Channel master, 2.2.0-11.0.pre.187, on Microsoft Windows [Version 10.0.19042.928], locale en-US)
    • Flutter version 2.2.0-11.0.pre.187 at C:\Users\Taha\Code\flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5526dcc24b (2 hours ago), 2021-04-20 22:34:02 -0700
    • Engine revision 610fd039ae
    • Dart version 2.14.0 (build 2.14.0-18.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\Taha\Code\SDK
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.3)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.9.31129.286
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Users\Taha\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] IntelliJ IDEA Community Edition (version 2021.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.3.3
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.55.2)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.21.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19042.928]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 89.0.4389.128
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 89.0.774.77

! Doctor found issues in 1 category.
```
	
</details>

Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-04-21 07:23 UTC
Labels: in triage
