### ISSUE TITLE
NoSuchMethodError: java.util.Locale.getScript on Samsung S3 Android 4.3

### ISSUE THREAD

**Issue by hartmannj** [flutter/flutter#28495] opened 2019-02-26 07:26 UTC
I am having following issue right at the app start based on a Google pre-launch report with a Samsung Galaxy S3, Android 4.3:

```
java.lang.NoSuchMethodError: java.util.Locale.getScript
	at io.flutter.embedding.engine.systemchannels.LocalizationChannel.sendLocales(LocalizationChannel.java:38)
	at io.flutter.view.FlutterView.sendLocalesToDart(FlutterView.java:334)
	at io.flutter.view.FlutterView.<init>(FlutterView.java:187)
	at io.flutter.app.FlutterActivityDelegate.onCreate(FlutterActivityDelegate.java:161)
	at io.flutter.app.FlutterActivity.onCreate(FlutterActivity.java:89)
```
Doctor version:
```
Flutter version 1.2.3-pre.45
Framework revision d7b0aab634 (3 hours ago), 2019-02-26 10:34:03 +0800
Engine revision f7306394e3
Dart version 2.2.0 (build 2.2.0-dev.2.1 c92d5ca288)
```

**Comment by zoechi** [comment] 2019-02-26 08:05
Looks like a regression of #23449

**Comment by jensjoha** [comment] 2019-02-26 08:36
I'm getting the same thing on Nexus 4, android-arm, Android 4.4.4 (API 19).
I've bisected to 007a415c2a2fa37e8fd5ad87d6710bca8e212ef1

**Comment by pepegich** [comment] 2019-02-26 10:08
https://developer.android.com/reference/java/util/Locale.html#getScript() 
added in API level 21

**Comment by GaryQian** [comment] 2019-02-26 18:21
@matthew-carroll This looks like it has to do with your system channels rework, specifically the API specific locale getters?

**Comment by GaryQian** [comment] 2019-02-26 18:22
I can roll just the localization channel portion back to the previous version to resolve this for now.

**Comment by GaryQian** [comment] 2019-02-26 20:26
This will be fixed when the engine rolls in with the fix https://github.com/flutter/engine/pull/7967

**Comment by GaryQian** [comment] 2019-02-28 18:31
This has landed.

**Closed by GaryQian** 2019-02-28 18:31 UTC
Labels: e: device-specific, engine, severe: crash, severe: regression, waiting for PR to land (fixed), ▣ platform-android, ⚠ TODAY
