### ISSUE TITLE
add or remove dynamic datarow in data table in flutter using datatable

### ISSUE THREAD

**Issue by iamprakash13** [flutter/flutter#42347] opened 2019-10-09 18:47 UTC
i was trying to add rows when i fill details and click button (then it should appear on table, when click delete button remove selected row from datatable). theme is to add or remove rows from table with default columns dynamically based on button events.

##Code
```
      List<DataRow> tiles, row = [];
      int index = 0;
     Row(
              mainAxisAlignment: MainAxisAlignment.end,
              children: <Widget>[
           FlatButton.icon(
          color: Colors.orange,
          icon: Icon(FontAwesomeIcons.shoppingBag),
          label: Text('Add to List'), 

          onPressed: () {
            ttl = int.parse(rate) * int.parse(noInputController.text);
            print(index);

            //add new row 
            setState(() {
             // this.row = [];
             this.row.add(
                row[index] = new DataRow(
            cells: [
            DataCell(Text(prd),),
          DataCell(Text(noInputController.text),),
          DataCell(Text(rate),),
           DataCell(Text(ttl.toString()),),
           DataCell(Text(rate),),
          DataCell(Text(stype),),
            ]));
                });
            index = index+1;
             return this.row;
                    }
        ),]),
            SizedBox(
              height: ScreenUtil.getInstance().setHeight(20),
            ),
           

        
             new SingleChildScrollView(
              scrollDirection: Axis.horizontal,
                child: DataTable(
      columns: [
        DataColumn(  //tooltip: "item code for products",
              label: Text("Name",style: TextStyle(fontWeight: FontWeight.bold,fontSize: 15.0,color: Colors.blue))),
            DataColumn(label: Text("Quantity",style: TextStyle(fontWeight: FontWeight.bold, fontSize: 15.0,color: Colors.blue))),
            DataColumn(label: Text("Rate",style: TextStyle(fontWeight: FontWeight.bold, fontSize: 15.0,color: Colors.blue))),
            DataColumn(label: Text("Total",style: TextStyle(fontWeight: FontWeight.bold, fontSize: 15.0,color: Colors.blue))),
            DataColumn(label: Text("Item Type",style: TextStyle(fontWeight: FontWeight.bold, fontSize: 15.0,color: Colors.blue)))
      ],
      rows: (index > 0) ? row: [],
    ),),
          SizedBox(
              height: ScreenUtil.getInstance().setHeight(20),
            ),

          ],
        ),
      ),
      ),
```

**Target Platform:** Android
**Target OS version/browser:** SDK 20+
**Devices:** Samsung

<details>
<summary> Logs</summary>

```
Reloaded 12 of 946 libraries in 1,824ms.
D/ViewRootImpl@5ab7aa5[MainActivity](23007): ViewPostIme pointer 0
D/ViewRootImpl@5ab7aa5[MainActivity](23007): ViewPostIme pointer 1
I/flutter (23007): 0
I/flutter (23007): ══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
I/flutter (23007): The following NoSuchMethodError was thrown while handling a gesture:
I/flutter (23007): The method '[]=' was called on null.
I/flutter (23007): Receiver: null
I/flutter (23007): Tried calling: []=(0, Instance of 'DataRow')
I/flutter (23007):
I/flutter (23007): When the exception was thrown, this was the stack:
I/flutter (23007): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
I/flutter (23007): #1      BillPageState.build.<anonymous closure>.<anonymous closure> (package:audit_shop/pages/billing_page.dart:692:20)
I/flutter (23007): #2      State.setState (package:flutter/src/widgets/framework.dart:1141:30)
I/flutter (23007): #3      BillPageState.build.<anonymous closure> (package:audit_shop/pages/billing_page.dart:689:13)
I/flutter (23007): #4      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:654:14)
I/flutter (23007): #5      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:729:32)
I/flutter (23007): #6      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
I/flutter (23007): #7      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:365:11)
I/flutter (23007): #8      TapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:312:7)
I/flutter (23007): #9      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
I/flutter (23007): #10     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:222:20)
I/flutter (23007): #11     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
I/flutter (23007): #12     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
I/flutter (23007): #13     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
I/flutter (23007): #14     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
I/flutter (23007): #18     _invoke1 (dart:ui/hooks.dart:263:10)
I/flutter (23007): (elided 3 frames from package dart:async)
I/flutter (23007):
I/flutter (23007): Handler: "onTap"
I/flutter (23007): Recognizer:
I/flutter (23007):   TapGestureRecognizer#5fba8
I/flutter (23007): ════════════════════════════════════════════════════════════════════════════════════════════════════
D/ViewRootImpl@5ab7aa5[MainActivity](23007): MSG_WINDOW_FOCUS_CHANGED 0
D/ViewRootImpl@5ab7aa5[MainActivity](23007): MSG_WINDOW_FOCUS_CHANGED 1
```
</details>

kindly help me resolve the issue. thanks in advance.

<details>
<summary> flutter doctor -v</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.9.1+hotfix.4, on Microsoft Windows [Version 10.0.18362.356], locale en-IN)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Android Studio (version 3.5)
[√] VS Code, 64-bit edition (version 1.38.1)
[√] Connected device (1 available)

• No issues found!
```
</details>

**Comment by BondarenkoStas** [comment] 2019-10-10 11:50
This is a question better suited for StackOverflow, since there doesn’t seem to be anything wrong with Flutter itself, but related to implementation. See https://flutter.dev/community for support options.
The error log is quite expressive, but it won't be possible to investigate without the code example that reproduces it, please paste it here. And I would also advise you to post it to SO as help there may come faster.

**Comment by darshankawar** [comment] 2020-07-16 08:32
Hi @iamprakash13,
Can you please confirm if you still experience this issue on latest Flutter version (eg: dev, master) or have you found a solution to resolve this ?

**Comment by iamprakash13** [comment] 2020-07-16 08:38
I m using this in my old project with flutter version 1.12.13+hotfix.9 . Is this works with latest version.

**Comment by darshankawar** [comment] 2020-07-16 09:36
@iamprakash13, I am not sure. You may try to upgrade Flutter to latest stable version and confirm. Also your question sounds more suitable for StackOverFlow. I'd suggest you to ask this question there.

**Comment by iamprakash13** [comment] 2020-07-16 09:39
Okay, is this not plugin issue? Is that implementation problem? I followed plugins example.

**Comment by darshankawar** [comment] 2020-07-16 13:03
@iamprakash13,
Which plugin are you talking about ? `DataTable` isn't a plugin but a material widget. Please provide the plugin example that you followed.

**Comment by darshankawar** [comment] 2020-08-07 13:22
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

**Closed by darshankawar** 2020-08-07 13:22 UTC
Labels: d: stackoverflow, f: material design, framework, waiting for customer response
