### ISSUE TITLE
"flutter run" fails to deploy to iOS 17: "Error starting debug session in Xcode"

### ISSUE THREAD

**Issue by lukemmtt** [flutter/flutter#140061] opened 2023-12-13 15:10 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

**Reproduction Steps:**
1. Connect an iPhone 12 mini with iOS 17.2.
2. Execute `flutter run`.
3. Observe the build process in Xcode.
4. Encounter the following error:
   ```
   Error starting debug session in Xcode: Xcode is not running
   Could not run build/ios/iphoneos/Runner.app on 00008101-000A79601A08001E.
   Suggested action: open ios/Runner.xcworkspace in Xcode and select "Product > Run".
   ```

**Successful Method:**
- Directly deploying a debug build to the physical device from Xcode itself after `flutter build ios` works without issues.
-` flutter run —release` deploys fine to the physical iPhone

**Troubleshooting Attempts:**
- Cleared Xcode caches via System Settings > Storage > Developer.
- Restarted both Mac and iPhone.
- Updated Xcode and Flutter to their latest versions.
- Verified "System Settings > Privacy & Security > Automation" (Note: Xcode is not listed).
- Tried running `flutter run` with Xcode both open and closed.

**Additional Information:**
- Reviewed Flutter GitHub issues [#134667](https://github.com/flutter/flutter/issues/134667) and [#133465](https://github.com/flutter/flutter/issues/133465) for potential solutions.

### Actual results

- Xcode builds the project
- Xcode opens
- Error

```
Launching lib/main.dart on LM iPhone in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: Z7YQK9S6SZ
Running Xcode build...                                                  
 └─Compiling, linking and signing...                        17.3s
Xcode build done.                                           48.3s
You may be prompted to give access to control Xcode. Flutter uses Xcode to run your app. If access is not allowed, you can change this through your Settings > Privacy & Security > Automation.
Error starting debug session in Xcode: Xcode is not running
Could not run build/ios/iphoneos/Runner.app on 00008101-000A79601A08001E.
Try launching Xcode and selecting "Product > Run" to fix the problem:
  open ios/Runner.xcworkspace

Installing and launching...                                         7.9s
Error launching application on LM iPhone.
```

### Logs

<details>
Verbose output:

[flutter —verbose run.txt](https://github.com/flutter/flutter/files/13662201/flutter.verbose.run.txt)

<summary>Logs</summary>

Non verbose output:

```console
lukem@lmba lib % flutter run
Changing current working directory to: /Users/lukem/Developer/timefinder_app/app
Connected devices:
Pixel 7 (mobile)   • 2A131FDH200E6P            • android-arm64 • Android 14 (API 34)
LM iPhone (mobile) • 00008101-000A79601A08001E • ios           • iOS 17.2 21C62
macOS (desktop)    • macos                     • darwin-arm64  • macOS 14.0 23A344 darwin-arm64

Checking for wireless devices...

[1]: Pixel 7 (2A131FDH200E6P)
[2]: LM iPhone (00008101-000A79601A08001E)
[3]: macOS (macos)
Please choose one (or "q" to quit): 2
"da": 108 untranslated message(s).
"de": 2 untranslated message(s).
"es": 2 untranslated message(s).
"fr": 108 untranslated message(s).
"hi": 108 untranslated message(s).
"it": 108 untranslated message(s).
"ja": 108 untranslated message(s).
"nl": 108 untranslated message(s).
"pl": 108 untranslated message(s).
"pt": 108 untranslated message(s).
"ru": 108 untranslated message(s).
"th": 108 untranslated message(s).
"tr": 108 untranslated message(s).
"uk": 108 untranslated message(s).
"zh": 108 untranslated message(s).
"zh_Hans": 108 untranslated message(s).
"zh_Hant": 108 untranslated message(s).
To see a detailed report, use the untranslated-messages-file 
option in the l10n.yaml file:
untranslated-messages-file: desiredFileName.txt
<other option>: <other selection> 


This will generate a JSON format file containing all messages that 
need to be translated.
Launching lib/main.dart on LM iPhone in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: Z7YQK9S6SZ
Running Xcode build...                                                  
 └─Compiling, linking and signing...                        17.3s
Xcode build done.                                           48.3s
You may be prompted to give access to control Xcode. Flutter uses Xcode to run your app. If access is not allowed, you can change this through your Settings > Privacy & Security > Automation.
Error starting debug session in Xcode: Xcode is not running
Could not run build/ios/iphoneos/Runner.app on 00008101-000A79601A08001E.
Try launching Xcode and selecting "Product > Run" to fix the problem:
  open ios/Runner.xcworkspace

Installing and launching...                                         7.9s
Error launching application on LM iPhone.


```

</details>

### Flutter Doctor output

<details>
<summary> flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.16.3, on macOS 14.0 23A344 darwin-arm64, locale en-US)
    • Flutter version 3.16.3 on channel stable at /Users/lukem/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b0366e0a3f (7 days ago), 2023-12-05 19:46:39 -0800
    • Engine revision 54a7145303
    • Dart version 3.2.3
    • DevTools version 2.28.4

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/lukem/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Users/lukem/Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Users/lukem/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] VS Code (version 1.85.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.78.0

[✓] Connected device (4 available)
    • Pixel 7 (mobile)   • 2A131FDH200E6P            • android-arm64  • Android 14 (API 34)
    • LM iPhone (mobile) • 00008101-000A79601A08001E • ios            • iOS 17.2 21C62
    • macOS (desktop)    • macos                     • darwin-arm64   • macOS 14.0 23A344 darwin-arm64
    • Chrome (web)       • chrome                    • web-javascript • Google Chrome 120.0.6099.71
    ! Error: Browsing on the local area network for Luke’s Apple Watch. Ensure the device is unlocked and discoverable via Bluetooth. (code -27)

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```
</details>

**Comment by danagbemava-nc** [comment] 2023-12-14 07:31
Hi @lukemmtt, did you have this issue prior to the upgrade to iOS 17.2?

Do you have this issue with all flutter apps?

Also, this seems like a shot in the dark, but could try making sure your Apple Watch is properly connected and try again?

**Comment by deepansharya1111** [comment] 2023-12-14 13:14
I am having the same issue as @lukemmtt

I too followed the same troubleshooting steps and also the steps as mentioned [here](https://stackoverflow.com/questions/59668369/flutter-run-on-xcode-but-dont-on-vs-code) as well but no luck.
I tried installing VsCode Insider app just in hopes of getting a prompt to allow xcode automation, but that too did not happen.

Installation happens fine but vscode is unable to run the app while keeping it attached, so there is no way to use Hot Reload for live development.

In my case, I am using iPhone 12 pro max with iOS 16.2. 
and also, Xcode is Not listed under VsCode in "System Settings > Privacy & Security > Automation".


<img width="805" alt="image" src="https://github.com/flutter/flutter/assets/30445158/5486d0d7-2e0b-4023-b89d-af13b6b050b8">

**Comment by PetrKubes97** [comment] 2023-12-14 13:41
Ok, happy to report that updating the iPhone's iOS to 17.2 fixed the issue.

**Comment by deepansharya1111** [comment] 2023-12-14 13:52
> Ok, happy to report that updating the iPhone's iOS to 17.2 fixed the issue.

Glad to know! Unfortunately, I can't afford to upgrade to ios 17.2, waiting for some other fix :)

**Comment by hieuvt1414** [comment] 2023-12-14 15:40
> Ok, happy to report that updating the iPhone's iOS to 17.2 fixed the issue.

what your flutter version ? i had updated ios 17.2 but the issue not fixed

**Comment by lukemmtt** [comment] 2023-12-14 15:52
I've been experiencing this issue for a few months—ever since I updated to Xcode 15.0 and iOS 17.0 (which I did around the same time).

Current versions:
- Android Studio 2023.1.1
- Flutter 3.16.3
- iPhone 12 mini running iOS 17.2
- macOS 14.0 Sonoma on M1 MacBook Air

**Comment by lukemmtt** [comment] 2023-12-14 17:32
I fixed it! Not certain what exactly was the issue, but I have some strong suspicions.

I updated Xcode (and the Xcode command line tools) from 15.0 to 15.1, rebooted my Mac, and as soon as I attempted to deploy a debug build to my iPhone, I got the following prompt from Android Studio for the first time:

![Android Studio wants to control Xcode](https://github.com/flutter/flutter/assets/1598289/01102717-0c83-4347-9f66-0ce9394df632)

Upon accepting that, the debug build installed and attached successfully,

I see three possibilities for what the issue was:
1. Some component was updated in a recent Xcode release—either Xcode 15.0.1 (which I skipped) or 15.1 (which I just installed)—that is required for the iOS Xcode debug attach automation to work.
2. The act itself of updating Xcode served to reset or refresh something on my device that allowed the permission request to go through
3. My usage of [XcodesApp](https://github.com/XcodesOrg/XcodesApp) (a tool for installing and switching between multiple versions of Xcode) could have been the problem. I've used XcodesApp for ages, and it was configured to install Xcode in the Applications directory as `Xcode-X-X-X.app` and then create an _alias_ called `Xcode` in the `Applications` directory, pointing to the Xcode version of your choice. When I was installing Xcode 15.1, I saw this config, and changed it to ditch the alias approach and just install it directly to the Applications folder as `Xcode.app`.

**Comment by deepansharya1111** [comment] 2023-12-14 22:58
I solved it too!

Fixed the issue by completely removing Xcode (via a third-party [app](https://nektony.com/mac-app-cleaner) to make sure no residual files are left)
and Xcode command-line-tools (following instruction from this [article](https://mac.install.guide/commandlinetools/6.html))

Then I installed Xcode again from AppStore and as soon as I opened VsCode upon installation of Xcode, 
It prompted me to install command-line-tools.

After installing them I opened Xcode to have the latest iOS Simulator files (for my iPhone to be detected as a connectable device.) 
<img width="311" alt="image" src="https://github.com/flutter/flutter/assets/30445158/8ffa0de4-892e-4824-9358-06ebac66f53e">

The install was failing so I followed [this](https://stackoverflow.com/questions/77083633/ios-17-0-simulator-failed-registering-simulator-runtime-with-coresimulator-f) guide to fix that and now my iPhone was showing in Xcode.

Now after first attempting to build the app from Xcode, another error I faced was this:
<img width="273" alt="image" src="https://github.com/flutter/flutter/assets/30445158/d0abdfe8-3ca5-4175-9b62-d14526676ea4">
It seems to be a bug in Flutter (not sure if it has been fixed already... since my Flutter app code is pretty old), so I followed this [thread](https://stackoverflow.com/questions/67405994/unable-to-find-a-target-named-runner-in-project-runner-xcodeproj-did-find-d) to resolve it.

Upon running the app directly in debug mode from VsCode gave this error:
<img width="265" alt="image" src="https://github.com/flutter/flutter/assets/30445158/cb6fd8e7-83d8-40b6-9fa0-de10b92a9526">
I followed this [thread](https://stackoverflow.com/questions/71359062/iproxy-cannot-be-opened-because-the-developer-cannot-be-verified) to fix it.

And Finally running the Debug mode in VsCode Worked!

**Comment by huycozy** [comment] 2023-12-15 06:11
Hi everyone,

@deepansharya1111 The issue here is about `Error starting debug session in Xcode: Xcode is not running` whilst it's not quite clear on your screenshot. I would suggest you run the app with verbose (`-v`) to make sure you have the same issue to the original report.

---

>and as soon as I attempted to deploy a debug build to my iPhone, I got the following prompt from Android Studio for the first time:

@lukemmtt Did you run the project from Android Studio?

Looks like you solved this issue on your side. If you persist with this issue, it would be appreciated if you could replicate it consistently and see if it has any pattern so that we may investigate this further. Also, I'm not familiar with [XcodesApp](https://github.com/XcodesOrg/XcodesApp) tool. But when you see the issue again, you can try checking the current XCode version with `xcode-select --print-path`. Thank you!

**Comment by deepansharya1111** [comment] 2023-12-15 13:31
> @deepansharya1111 The issue here is about `Error starting debug session in Xcode: Xcode is not running` whilst it's not quite clear on your screenshot. I would suggest you run the app with verbose (`-v`) to make sure you have the same issue to the original report.

Yes, @huycozy my issue was the same as @lukemmtt's, with the only difference being that he was using Android Studio for "flutter run", and I was using VsCode, and it was giving us a similar error.

I see the original title of this issue was `"flutter run" fails to deploy to iOS 17 physical device` until very recently when it was updated, hence the confusion.

Needless to say, this was an error relating to Xcode and not Flutter. So this Issue can be closed If @lukemmtt agrees.

**Comment by lukemmtt** [comment] 2024-01-03 13:07
- Hey @huycozy , yes I ran it from android studio, but before I resolved it, the issue was reproducible whether I'd run the app from there or manually with `flutter run` from the terminal. 

Thank you for your involvement here. I haven't had time to reproduce the issue yet, but at least users looking for similar errors can have this thread to refer to.

**Comment by huycozy** [comment] 2024-01-04 05:38
Thank you all for the update. I will close this issue from here. If anyone can reproduce it consistently and find out a pattern, feel free to write in comments and I will reopen this for further investigation.

**Closed by huycozy** 2024-01-04 05:38 UTC
Labels: in triage
