### ISSUE TITLE
[google_maps_flutter] Crashes on a higher gradle version in Android

### ISSUE THREAD

**Issue by LaemonT** [flutter/flutter#40653] opened 2019-09-17 08:11 UTC
The application crashes if I upgrade my Android gradle from 'com.android.tools.build:gradle:3.3.2' to 'com.android.tools.build:gradle:3.5.0', and the corresponding gradle-wrapper.properties file.

So I revert the changes and the app start to work again.

**Comment by BondarenkoStas** [comment] 2019-09-17 11:42
@LaemonT I'm not sure which flutter version you use, but it's seems very similar to #38934.

The issue is that in Android Gradle plugin 3.5.0, the app bundle is named app-.aab instead of app.aab, which is what the Flutter tool expects.

It was fixed on master channel #39126. 
Closing it. Please report if you still encounter it using master channel, if yes I will reopen the issue right away.

**Closed by BondarenkoStas** 2019-09-17 11:42 UTC
