### ISSUE TITLE
Dart plugin registration doesn't run in background isolates

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#98591] opened 2022-02-16 17:02 UTC
As we've been adopting in-package platform channels in more 1P plugins, which requires Dart plugin registration, we've hit an edge case related to isolates. While plugins don't generally work out of the box in isolates, there are [workarounds](https://pub.dev/packages/flutter_isolate) which, IIUC, run the native plugin registration code in a separate engine instance so that the native side is there. These systems don't know about the new *Dart* plugin registration though, so half of the registration code is missing, and we end up with mismatches like #98473.

@gaaclarke @blasten (since you've both looked at the engine/VM integration part of the Dart plugin registration) is there a way we can automatically run the generated Dart registration in each new isolate, rather than just the primary isolate? Alternately, could we adjust the generated registration such that it provides a referenceable function that things like `flutter_isolate` could call during their isolate setup (similar to the need to call `WidgetsFlutterBinding.ensureInitialized()`)?

**Comment by gaaclarke** [comment] 2022-02-16 17:32
> is there a way we can automatically run the generated Dart registration in each new isolate, rather than just the primary isolate?

I don't think so, and we probably wouldn't want that since it could be wasted in some contexts.

> Alternately, could we adjust the generated registration such that it provides a referenceable function that things like flutter_isolate could call during their isolate setup (similar to the need to call WidgetsFlutterBinding.ensureInitialized())?

We should be able to do that.  I have an outstanding PR that removes the main shadowing and hunts down and executes the registrant and executes it on the C++ side.  We could expose that function to Dart and have it query the current isolate before executing to see if it already happened.

**Comment by sarbagyastha** [comment] 2022-02-17 01:08
@stuartmorgan @gaaclarke Is this flutter/flutter#98475 issue related too? But having this issue only when using `--obfuscate`.

**Comment by stuartmorgan** [comment] 2022-02-17 03:04
> But having the issue only when using `--obfuscate`.

I don't see any way that could be related then.

**Comment by absar** [comment] 2022-02-27 00:44
@stuartmorgan This issue needs to be prioritized, slowly almost every plugin will start having the same issue as you are moving to "in-package method channel", first it was happening with `shared_preferences`, now `path_provider`(`path_provider_android  2.0.12` to be specific)

**Comment by gaaclarke** [comment] 2022-03-01 22:34
https://github.com/flutter/engine/pull/31720 has a fix for this issue where a background isolate can call `DartPluginRegistrant.ensureInitialized()` to make sure that they've executed.  It works in vitro.  It has a dependency on a framework change so it will take a while to work through the system.  If you are feeling brave you can patch the framework and engine to give it a chance.  It would be nice if we could print out a friendlier message too when someone doesn't call this.

**Closed** 2022-03-03 01:50 UTC
Labels: tool, engine, plugin, P3

**Comment by jack24254029** [comment] 2022-03-03 02:23
When release `DartPluginRegistrant.ensureInitialized()` to stable?

**Comment by stuartmorgan** [comment] 2022-03-03 15:08
> When release `DartPluginRegistrant.ensureInitialized()` to stable?

See https://github.com/flutter/flutter/wiki/Flutter-build-release-channels for an overview of how branching and channel progression works.

**Comment by pedromassango** [comment] 2022-03-05 12:17
@stuartmorgan can't we just patch into the stable channel? Even though there is a workaround, it is still a critical one :)

**Comment by stuartmorgan** [comment] 2022-03-05 15:01
Something that required changes in Dart itself, the Flutter engine, and the Flutter tooling cannot be easily cherry-picked, no. Also, this isn't a regression, so definitely would not qualify given the complexity; Dart plugin registration has *never* worked in isolates. The only thing that changed is the mobile implementations of path_provider and shared_preferences.

The workaround here is very simple, so I'm not sure why you believe that it would be critical to cherry-pick.

**Comment by kuhnroyal** [comment] 2022-03-09 09:50
Well, I kind of have to agree that this is somewhat critical.
Mainly due to the fact that those `path_provider` and `shared_preferences` updates have been released as patch releases and are just transitively being pulled in.

Apps that have had working background implementations are breaking left and right. The background code is also not easy to test and these problems are often only showing in production after a store deploy.

Yes, the workaround is simple, the problem is more in the way of knowing/noticing the problem.

**Comment by kuhnroyal** [comment] 2022-03-09 18:38
> How would cherry-picking the PR above into stable address this?

You are absolutely right, it wouldn't address that problem by itself.
It could help to have it mentioned in a release announcement and mailing list but other than that your point stands.

Anything else would have to be done on the plugin side (retracting/reverting/major version bump).

**Comment by gaaclarke** [comment] 2022-03-22 18:10
https://github.com/flutter/engine/pull/32162 has caused this to regress.  The PR was reverted because of a performance regression with a google app.  I think I have a fix for the performance issue.  If that doesn't land shortly we will revert the revert.

**Comment by v7lin** [comment] 2022-03-28 09:46
any news update?

**Comment by gaaclarke** [comment] 2022-03-28 16:37
> any news update?

It's just broken on master.  We should land the fix before branching for the next release.  The engine PR has landed, I'm waiting on a review of the framework PR.
