### ISSUE TITLE
[tool_crash] HttpException

### ISSUE THREAD

**Issue by Massawe14** [flutter/flutter#105296] opened 2022-06-03 07:59 UTC
## command

flutter run --debug

## exception

HttpException: HttpException: Connection closed before full header was received, uri = http://localhost:10193/json

```
```

## flutter doctor

```
[✓] Flutter (Channel master, 3.1.0-0.0.pre.618, on Microsoft Windows [Version 10.0.19044.1706], locale en-US)
    • Flutter version 3.1.0-0.0.pre.618 at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision dfb4ff2f76 (3 weeks ago), 2022-05-09 23:15:44 -0700
    • Engine revision 8774c24f65
    • Dart version 2.18.0 (build 2.18.0-99.0.dev)
    • DevTools version 2.13.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\MASSAWE\AppData\Local\Android\sdk
    • Platform android-31, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop for Windows (Visual Studio Build Tools 2022 17.2.2)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools
    • Visual Studio Build Tools 2022 version 17.2.32519.379
    ✗ Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop development with C++" workload, and
      include these components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK

[✓] Android Studio (version 4.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.67.2)
    • VS Code at C:\Users\MASSAWE\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.26.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19044.1706]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 102.0.5005.63
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 102.0.1245.30

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

**Comment by danagbemava-nc** [comment] 2022-06-03 08:20
Hi @Massawe14, do you see an error message in your console when you experience this crash?

**Comment by Massawe14** [comment] 2022-06-03 08:32
Oops; flutter has exited unexpectedly: "HttpException: Connection closed before full header was received, uri = http://localhost:10193/json".

**Comment by danagbemava-nc** [comment] 2022-06-03 08:41
Thanks for the logs. 

Closing this as a duplicate of #79748

**Closed by danagbemava-nc** 2022-06-03 08:41 UTC
Labels: in triage
