### ISSUE TITLE
Error when opening Adobe XD Exported Menus. 

### ISSUE THREAD

**Issue by origamisimplicity** [flutter/flutter#61856] opened 2020-07-20 13:12 UTC
**Expected results:** Screen change to **Main Screen**

**Actual results:** I/flutter ( 5763): unhandled element filter; Picture key: StringPicture(String#19741, colorFilter: null)

**Comment by darshankawar** [comment] 2020-07-20 13:37
Hi @origamisimplicity,
When you say Adobe XD, are you referring and using [this](https://pub.dev/packages/adobe_xd) plugin ?

**Comment by darshankawar** [comment] 2020-07-21 05:22
Hi @origamisimplicity,
Please provide `flutter doctor -v` and a minimal complete reproducible code sample that shows the issue you are facing.
Thanks.

**Comment by origamisimplicity** [comment] 2020-07-21 13:21
[√] Flutter (Channel stable, v1.17.5, on Microsoft Windows [Version 10.0.19041.329], locale pt-PT)
    • Flutter version 1.17.5 at C:\flutter
    • Framework revision 8af6b2f038 (3 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4


[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Users\nunom\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.47.2)
    • VS Code at C:\Users\nunom\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.12.2

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

• No issues found!

----------------------------------------------------------------------------------------------------------------------

I have a simple button calling the menu that i exported from Adobe XD. 
```
 if (numid.isNotEmpty) {
        print("valid");
        Navigator.push(context, MaterialPageRoute(builder: (context) => MainScreen()));
      } else {
        print("invalid");
```

**Comment by darshankawar** [comment] 2020-07-22 05:19
Hi @origamisimplicity,
That sounds like an issue with the plugin you are using. Since Adobe XD is a 3rd party plugin, I'd suggest you to log this issue in their repo (https://github.com/AdobeXD/xd-to-flutter-plugin/issues).
I am going ahead and closing this since it doesn't seem to be an issue with Flutter. If you disagree, write in comments and I'll reopen.
Thanks.

**Closed by darshankawar** 2020-07-22 05:19 UTC
Labels: in triage
