### ISSUE TITLE
BottomNavigationBar styling props not working

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [flutter/flutter#56843] opened 2020-05-10 17:37 UTC
Hi these 3 properties haa no effect on color of unselected items:
       
unselectedIconTheme: IconThemeData(color: Colors.grey[200]),
unselectedLabelStyle: TextStyle(color: Colors.grey[200]),
unselectedItemColor: Colors.grey[200]

**Comment by VladyslavBondarenko** [comment] 2020-05-11 12:24
Hi @vytautas-pranskunas- 

<details>
 <summary>I'm running with this code sample</summary>

```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  static const String _title = 'Flutter Code Sample';
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: _title,
      home: MyStatefulWidget(),
    );
  }
}

class MyStatefulWidget extends StatefulWidget {
  MyStatefulWidget({Key key}) : super(key: key);
  @override
  _MyStatefulWidgetState createState() => _MyStatefulWidgetState();
}

class _MyStatefulWidgetState extends State<MyStatefulWidget> {
  int _selectedIndex = 0;
  static const TextStyle optionStyle =
  TextStyle(fontSize: 30, fontWeight: FontWeight.bold);
  static const List<Widget> _widgetOptions = <Widget>[
    Text(
      'Index 0: Home',
      style: optionStyle,
    ),
    Text(
      'Index 1: Business',
      style: optionStyle,
    ),
    Text(
      'Index 2: School',
      style: optionStyle,
    ),
  ];

  void _onItemTapped(int index) {
    setState(() {
      _selectedIndex = index;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('BottomNavigationBar Sample'),
      ),
      body: Center(
        child: _widgetOptions.elementAt(_selectedIndex),
      ),
      bottomNavigationBar: BottomNavigationBar(
        unselectedIconTheme: IconThemeData(color: Colors.grey[200]),
        unselectedLabelStyle: TextStyle(color: Colors.grey[200]),
        unselectedItemColor: Colors.grey[200],
        items: const <BottomNavigationBarItem>[
          BottomNavigationBarItem(
            icon: Icon(Icons.home),
            title: Text('Home'),
          ),
          BottomNavigationBarItem(
            icon: Icon(Icons.business),
            title: Text('Business'),
          ),
          BottomNavigationBarItem(
            icon: Icon(Icons.school),
            title: Text('School'),
          ),
        ],
        currentIndex: _selectedIndex,
        selectedItemColor: Colors.amber[800],
        onTap: _onItemTapped,
      ),
    );
  }
}
```

</details>

And the props work as intended with current dev `1.19.0-0.0.pre`.
With what flutter version are you experiencing this?

**Comment by vytautas-pranskunas-** [comment] 2020-05-11 12:26
Hi, latest, I have upgrade few days ago

**Comment by VladyslavBondarenko** [comment] 2020-05-11 14:37
@vytautas-pranskunas- 
aren't colors applied when you are running code from my previous comment?

**Comment by TahaTesser** [comment] 2020-06-03 11:54
Without additional information we are unfortunately not sure how to resolve this issue.
We are therefore reluctantly going to close this bug for now.
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.

**Closed by TahaTesser** 2020-06-03 11:54 UTC
Labels: in triage
