### ISSUE TITLE
[cross_file] file.name always returns empty string on desktop if file is created using XFile.fromData

### ISSUE THREAD

**Issue by BirjuVachhani** [flutter/flutter#102076] opened 2022-04-18 12:49 UTC
`XFile.fromData` implementation of `io` platform is missing name information assignment.

**io.dart**
<img width="599" alt="image" src="https://user-images.githubusercontent.com/20423471/163810387-b53601b8-2fe2-487d-9bf4-5cc0cca2766e.png">

Whereas web implementation is correct.

**html.dart**
<img width="675" alt="image" src="https://user-images.githubusercontent.com/20423471/163810481-80392cec-afd4-439f-b112-8f8db3506d2a.png">

## Steps to Reproduce

```dart
  final file = XFile.fromData(
    bytes,
    length: bytes.length,
    name: 'Hello.png', // Name of the file
    lastModified: DateTime.now(),
  );

  print(file.name); // Prints empty string on web and prints Hello.png on web.
```

**Expected results:** `file.name` should not be empty on `io` platforms (e.g. desktop)

**Actual results:** `file.name` is empty on `io` platforms (e.g. desktop)

**Comment by stuartmorgan** [comment] 2022-04-18 13:23
Duplicate of https://github.com/flutter/flutter/issues/87808

See also https://github.com/flutter/flutter/issues/87812

**Closed by stuartmorgan** 2022-04-18 13:23 UTC
Labels: in triage
