### ISSUE TITLE
Text: support inline images

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#2022] opened 2016-02-19 04:00 UTC
See https://github.com/flutter/flutter/pull/2021 for a use case we should convert to inline images.

Right now, the paragraph will wrap really weirdly if the device is too narrow.

**Comment by HansMuller** [comment] 2016-02-19 16:15
I think we'll want to support text that contains inline widgets.  For example (from the Section of the MD spec):

![chips](https://cloud.githubusercontent.com/assets/1377460/13181212/db188998-d6e0-11e5-98a1-ca9677283881.png)

**Comment by Hixie** [comment] 2016-02-19 18:20
Yeah, what we actually need to support is "just" a placeholder rectangle with a paint callback. Then you just hook the rendering boxes into it and can have whatever you want in there.

**Comment by nanowang** [comment] 2017-06-29 09:22
I believe flutter also should support inline `Icon`/`ImageIcon` in `Text`/`TextSpan`.

I guess this is not worth another issue?

**Comment by Hixie** [comment] 2017-06-29 22:14
Yeah, once we support this you'll be able to put any RenderBox in there.

**Comment by pulyaevskiy** [comment] 2018-01-02 20:34
This would also be a desirable feature for (future) rich-text editors (I'm currently working on one).

**Comment by jay7n** [comment] 2018-03-21 16:08
Hi @pulyaevskiy , is there some progress on this issue ? I have encounterd this problem recenetly, and want to get this feature urgently ...

**Comment by pulyaevskiy** [comment] 2018-03-21 17:13
@jay7n in regards to this issue (inline images in `TextSpan`) I didn't have any plans to work on implementing this any time soon. If you're interested in rich-text editor, I've had good progress on it since. But it's just a part of a bigger project and I'm not working on the editor full time.

**Comment by jay7n** [comment] 2018-03-27 02:02
@pulyaevskiy thanks for your reply and sorry for the delay. I mocked up a quick workaround regarding this missing feature. The idea is simple: detect the images width and the total text size(multiply text count by single font size), and check if there's not enough space for the whole text, then split it to two text widgets, one following the images, the other lay down to next line. All widgets are wrapped in a Wrap widget. I'm not sure this is the right way to do it, but I think the workaround is workable

**Comment by exiic** [comment] 2018-06-08 09:37
Hi @jay7n , can you provide some sample code? Thanks.

**Comment by jay7n** [comment] 2018-06-13 02:29
@exiic I was fixing this issue as a member of Xianyu Team. And as a team we’re currently working on a series of advanced flutter practices, one of which is this “inline-imgs” issue. We’re going to build a group on github and share some code which we think might be worth broadcasting.  I’ll let you know once we’re ready~ thank you

**Comment by zoechi** [comment] 2018-06-25 11:14
#12675 is probably related

**Comment by rockingdice** [comment] 2018-08-29 04:14
Any progress on this one?

@jay7n Is the group ready for the public? looking forward to it and the fix for this issue.

**Comment by spikeye** [comment] 2018-10-08 03:46
@jay7n Can the solution be announced?

**Comment by limengyun2008** [comment] 2018-11-25 07:32
> Any progress on this one?
> 
> @jay7n Is the group ready for the public? looking forward to it and the fix for this issue.

Here is my solution: https://github.com/limengyun2008/RealRichText
Wishing it may help

**Comment by jinfagang** [comment] 2018-12-30 05:58
Any updates on this?

**Comment by GaryQian** [comment] 2019-01-25 23:17
I have begun brainstorming and exploring possible ways to add this as well as appropriate API. No ETA yet though.

**Comment by numez** [comment] 2019-03-04 20:39
> @pulyaevskiy thanks for your reply and sorry for the delay. I mocked up a quick workaround regarding this missing feature. The idea is simple: detect the images width and the total text size(multiply text count by single font size), and check if there's not enough space for the whole text, then split it to two text widgets, one following the images, the other lay down to next line. All widgets are wrapped in a Wrap widget. I'm not sure this is the right way to do it, but I think the workaround is workable

I published package [drop_cap_text ](https://pub.dartlang.org/packages/drop_cap_text) to achive DropCapText, you can also put an **image** as custom widget inside DropCap.

![image](https://user-images.githubusercontent.com/6752432/53761455-d2f10100-3ec5-11e9-83ed-d12565623cc3.png)

**Comment by GaryQian** [comment] 2019-03-19 21:59
https://github.com/flutter/engine/pull/8207 Is a WIP PR for engine-level support for arbitrary inline widgets. The public facing framework API is still under discussion and design.

**Comment by GaryQian** [comment] 2019-03-28 22:36
https://github.com/flutter/flutter/pull/30069 is a WIP PR for framework-side support for embedding widgets inline.

**Comment by GaryQian** [comment] 2019-04-18 18:22
Update: Implementation is pending initial review.

**Comment by GaryQian** [comment] 2019-04-26 00:03
Please note that the current work is limited to displaying widgets in RIchText. Further work is needed (no eta) to integrate into TextFields.

Floating widgets within text was also considered but this is not currently being worked on.

I will file separate issues to track the progress on those fronts.

**Comment by chunhtai** [comment] 2019-05-22 20:02
I am also working on selectable rich text. I wonder what is the expected behavior if we have widget in the textSpan, I can think of as of a temp solution will be using toString method of the widget when doing copy

**Comment by GaryQian** [comment] 2019-05-22 22:49
Currently, there is an option to include widgets as a 0xFFFC character in the toPlainText. In the design doc, I had considered the use of the toString of the widget as the way users could encode their inline widgets, which they would then have to manually decode to rebuild the widget again when pasting.

**Comment by GaryQian** [comment] 2019-06-04 00:12
Landing process started.

**Comment by GaryQian** [comment] 2019-06-04 21:13
Main PR has been moved to https://github.com/flutter/flutter/pull/33794 to fix versioning errors

**Comment by GaryQian** [comment] 2019-06-04 23:30
The feature has landed, but I will keep this open for a little longer just in case it is rolled back since this does contain breaking changes.

**Comment by GaryQian** [comment] 2019-06-05 19:34
Temporarily reverted due to performance benchmark regressions.

**Comment by GaryQian** [comment] 2019-06-05 22:03
https://github.com/flutter/flutter/pull/33946 Reland PR

**Comment by GaryQian** [comment] 2019-06-06 20:16
Status update, currently working on ensuring this change works nicely with the plugins system, and some other misc compatibility issues due to the breaking nature of this change. I will be sure to notify everyone when this feature is fully committed and unlikely to be rolled back, but as of now, it is still rolling in and out of the master branch as we observe the impact of the change.

**Comment by GaryQian** [comment] 2019-06-07 00:05
if you want to experiment with the feature, feel free to work with a snapshot of flutter with the changes in. The feature itself is steady and should be functional.

**Comment by GaryQian** [comment] 2019-06-07 18:31
https://github.com/flutter/flutter/pull/34051 This version contains backwards compatibility API to minimize impact of breaking changes.

**Comment by GaryQian** [comment] 2019-06-13 20:38
This change should be (relatively stably) in master, expecting to roll to dev in a short time. I will close this for now. Please feel free to reopen or provide feedback!

**Closed by GaryQian** 2019-06-13 20:38 UTC
Labels: a: typography, customer: headline, engine, framework, severe: customer critical, severe: new feature, team: gallery

**Comment by MstrZeroOne** [comment] 2021-01-04 05:57
> > @pulyaevskiy thanks for your reply and sorry for the delay. I mocked up a quick workaround regarding this missing feature. The idea is simple: detect the images width and the total text size(multiply text count by single font size), and check if there's not enough space for the whole text, then split it to two text widgets, one following the images, the other lay down to next line. All widgets are wrapped in a Wrap widget. I'm not sure this is the right way to do it, but I think the workaround is workable
> 
> I published package [drop_cap_text ](https://pub.dartlang.org/packages/drop_cap_text) to achive DropCapText, you can also put an **image** as custom widget inside DropCap.
> 
> ![image](https://user-images.githubusercontent.com/6752432/53761455-d2f10100-3ec5-11e9-83ed-d12565623cc3.png)

I'm using this plugin and I hove an issue: https://github.com/mtiziano/drop_cap_text/issues/14
