### ISSUE TITLE
[tool_crash] DartDevelopmentServiceException

### ISSUE THREAD

**Issue by iranjunior** [flutter/flutter#111473] opened 2022-09-13 12:44 UTC
## Command
```
flutter run -d chrome --verbose
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
DartDevelopmentServiceException
```
#0      DartDevelopmentServiceImpl._startDDSServer (package:dds/src/dds_impl.dart:185:7)
<asynchronous suspension>
#1      DartDevelopmentServiceImpl.startService (package:dds/src/dds_impl.dart:113:7)
<asynchronous suspension>
#2      DartDevelopmentService.startDartDevelopmentService (package:dds/dds.dart:88:5)
<asynchronous suspension>
#3      DebugService.startDartDevelopmentService (package:dwds/src/services/debug_service.dart:152:12)
<asynchronous suspension>
#4      DevHandler._createAppDebugServices (package:dwds/src/handlers/dev_handler.dart:448:7)
<asynchronous suspension>
#5      DevHandler.loadAppServices (package:dwds/src/handlers/dev_handler.dart:231:25)
<asynchronous suspension>
#6      Dwds.debugConnection (package:dwds/dwds.dart:92:9)
<asynchronous suspension>
#7      WebDevFS.connect.<anonymous closure> (package:flutter_tools/src/isolated/devfs_web.dart:687:15)
<asynchronous suspension>
```
```
[✓] Flutter (Channel unknown, 3.0.2, on macOS 12.2 21D49 darwin-x64, locale
    en-BR)
    • Flutter version 3.0.2 at /Users/iran.junior/flutter
    • Upstream repository unknown
    • Framework revision cd41fdd495 (3 months ago), 2022-06-08 09:52:13 -0700
    • Engine revision f15f824b57
    • Dart version 2.17.3
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/iran.junior/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • ANDROID_SDK_ROOT = ~/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode_13.2.1.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] IntelliJ IDEA Community Edition (version 2021.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 63.3.3
    • Dart plugin version 212.5632

[✓] VS Code (version 1.71.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.2 21D49 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 105.0.5195.102

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

## Flutter Application Metadata
**Type**: malformed
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: null
**Creation framework version**: null
### Plugins
connectivity-3.0.6
connectivity_for_web-0.4.0+1
connectivity_macos-0.2.1+2
firebase_core-1.20.0
firebase_core_web-1.7.1
firebase_messaging-11.4.4
firebase_messaging_web-2.4.4
flutter_config-2.0.0
flutter_image_compress-1.1.1
flutter_plugin_android_lifecycle-2.0.7
geocoding-2.0.4
geolocator-8.2.1
geolocator_android-3.2.1
geolocator_apple-2.2.1
geolocator_web-2.1.6
geolocator_windows-0.1.1
google_maps_flutter-2.2.0
google_maps_flutter_android-2.3.0
google_maps_flutter_ios-2.1.11
google_maps_flutter_web-0.3.3
image_compression_flutter-1.0.2
image_picker-0.8.5+3
image_picker_android-0.8.5+2
image_picker_for_web-2.1.8
image_picker_ios-0.8.5+6
path_provider-2.0.11
path_provider_android-2.0.17
path_provider_ios-2.0.11
path_provider_linux-2.1.7
path_provider_macos-2.0.6
path_provider_windows-2.1.2
qr_code_scanner-1.0.0
shared_preferences-2.0.15
shared_preferences_android-2.0.12
shared_preferences_ios-2.1.1
shared_preferences_linux-2.1.1
shared_preferences_macos-2.0.4
shared_preferences_web-2.0.4
shared_preferences_windows-2.1.1
sqflite-2.0.3+1
url_launcher-6.1.5
url_launcher_android-6.0.17
url_launcher_ios-6.0.17
url_launcher_linux-3.0.1
url_launcher_macos-3.0.1
url_launcher_web-2.0.13
url_launcher_windows-3.0.1

**Comment by darshankawar** [comment] 2022-09-13 13:16
Closing as duplicate of https://github.com/flutter/flutter/issues/108848

**Closed by darshankawar** 2022-09-13 13:16 UTC
Labels: in triage
