### ISSUE TITLE
Flutter app starts failing on Fuchsia in JIT profile mode

### ISSUE THREAD

**Issue by chingjun** [flutter/flutter#61986] opened 2020-07-21 22:08 UTC
Flutter tests start failing on Fuchsia in JIT profile mode since https://github.com/flutter/flutter/commit/978a2e7bf6a2ed287130af8dbd94cef019fb7bef

b/161746488 for more information.

cc @iskakaushik @zanderso

**Comment by zanderso** [comment] 2020-07-21 22:15
There is a native crash backtrace for flutter_jit_runner in the syslogs in the logs. Please share the symbolicated backtrace either here or in the internal issue as appropriate. Thanks!

**Comment by tarobins** [comment] 2020-07-21 22:57
We seem to be having trouble symbolizing due to fxb/49765 and other issues.

**Comment by zanderso** [comment] 2020-07-22 02:00
The engine hash there is https://github.com/flutter/engine/commits/383dfa2033b80c2da43734d88f7de523bb7ea1be
The Dart SDK hash there is https://github.com/dart-lang/sdk/commits/89fe12b12aab50d0db1f9e30190afb32c754a900

The symbolicated stack trace linked in the internal bug indicates that this is a crash in JITed Dart code.

@a-siva @mkustermann The change that @chingjun notes above appears to be triggering the crash. Since it wasn't a Dart roll that is triggering the crash, and the Flutter roll that is triggering it doesn't contain a Dart roll, I don't think we really know when a bug in Dart might have been introduced, but the previous Dart hash with a Flutter roll was https://github.com/dart-lang/sdk/commits/f997d62a6d29fa23ca140a60bba987fac7251c56.

**Comment by mkustermann** [comment] 2020-07-22 15:23
Migrating the `<flutter>/packages/flutter/lib/src/foundation` folder to NNBD in 978a2e7bf6a2ed could've revealed an existing NNBD mixed-mode bug. From the symbolized stack in [b/161746488](http://b/161746488) it's hard to tell what goes wrong.

Has this issue been also observed on non-fuchsia? Is the fuchsia building of the app different in some way (e.g. modular kernel compilation / concatenation or something like this)? Is it possible to run fuchsia-flutter in Dart VM DEBUG mode?

@a-siva Does someone in MTV a working fuchsia setup to reproduce this issue?

/cc @alexmarkov @crelier for NNBD.

**Comment by zanderso** [comment] 2020-07-22 16:38
Raising to P2 because this is blocking a roll. Assigning @iskakaushik to assist with repro and/or getting a DEBUG Dart VM into the mix.

**Comment by kf6gpe** [comment] 2020-07-22 21:40
Noting here that @iskakaushik and @aam have talked, and that @aam is the primary investigator right now as this looks like a Dart issue. Leaving @iskakaushik assigned as he'll provide any backup Fuchsia configuration help.

**Comment by aam** [comment] 2020-07-23 01:25
So far we have not been able to narrow down the cause of the crash.
Turning off the background compiler and running with printing flowgraph and tracing compiler has consistently produced generated protobuf valueOf method being last thing that is touched by dart vm before the crash. PC at the time of (read not-present page fault) crash does not seem to be in disassemble/disassemble-stubs range printed by dart vm.

**Comment by zanderso** [comment] 2020-07-23 15:44
What is the PC on the stack frame before the last frame? If there is a bug in the compiler/codegen, then the last jump or call could be suspect.

**Comment by aam** [comment] 2020-07-23 16:24
None of the top 20 frames after DartEntry::InvokeFunction/DartEntry::InvokeCode(which invoke `scheduleMicrotask` with some closure) can be symbolicated or matched to `--disassemble`-printed generated vm code for some reason.

**Comment by zanderso** [comment] 2020-07-23 16:29
Can you dump the full output and share on the internal issue? Maybe more eyes on this will help.

**Comment by aam** [comment] 2020-07-23 21:37
To reflect what was discussed: Fuchsia JIT profile mode tests seem to be using bytecode dart vm mode, which is known to have issues with null-safety features at the moment. The solution is for Fuchsia to get off the bytecode mode.

**Comment by mkustermann** [comment] 2020-07-28 13:07
> The solution is for Fuchsia to get off the bytecode mode.

Has this been done / Is someone assigned to this?

**Comment by aam** [comment] 2020-07-28 13:47
> > The solution is for Fuchsia to get off the bytecode mode.
> 
> Has this been done / Is someone assigned to this?

Yes, @iskakaushik has changes to the turn off bytecode/interpreter in flight.

**Comment by kf6gpe** [comment] 2020-07-28 18:29
Upstream issue fixed by ignoring specific tests, with new issue filed in the relevant Google issue tracker to remove dependencies on JIT mode elsewhere in Fuchsia.

**Closed by kf6gpe** 2020-07-28 18:29 UTC
Labels: P2, customer: fuchsia, dependency: dart, platform-fuchsia, severe: crash, waiting for customer response
