### ISSUE TITLE
Android toolchain broken

### ISSUE THREAD

**Issue by grungy01** [flutter/flutter#68122] opened 2020-10-14 17:40 UTC
After flutter update I can't get my apps work anymore. I launched flutter doctor which tells me that :
![Capture d'écran Deepin_zone de sélection _20201014193521](https://user-images.githubusercontent.com/72883291/96024820-8f59c980-0e54-11eb-860f-cae2ad70a7de.png)

And when i run the command "flutter doctor --android-licenses" i got errors : 
`Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
	at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
	at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
	at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 5 more
`
ps : i'ved installed jdk 14.0.2 but nothing changes

**Comment by hamdikahloun** [comment] 2020-10-14 19:16
Hi @grungy01 
Please try this [solution](https://github.com/flutter/flutter/issues/66907#issuecomment-703184800)  and see if it works for you.
Thanks

**Comment by grungy01** [comment] 2020-10-14 20:53
Hi @hamdikahloun  it's seems to be the same pb. but i'm on linux. I'd tried to to set my jdk path on /usr/lib/jdk-14.0.2 in my /etc/profile file but when i do `echo $JAVA_HOME` it answer : /home/grungy01/jdk-14.0.2

**Comment by hamdikahloun** [comment] 2020-10-14 21:18
@grungy01 to run `flutter doctor --android-licenses` you must install JDK 8.  if you have both java 11 and 8 installed, export JAVA_HOME point to JDK 8: `export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64`

Possible duplicated issue https://github.com/flutter/flutter/issues/62924

**Comment by cbracken** [comment] 2020-10-14 21:46
Thanks @hamdikahloun this is indeed a dupe of #62924. Closing.

For the record, I just ran into this too :)

**Comment by grungy01** [comment] 2020-10-14 21:47
i've installed the 8 version of openjdk, 
change the path,
Launched flutter doctor --android-licenses:
![image](https://user-images.githubusercontent.com/72883291/96048489-fe481a00-0e76-11eb-96f5-084dba44bf86.png)
but when i launch the debuging mode i got this message : 
![image](https://user-images.githubusercontent.com/72883291/96048917-95ad6d00-0e77-11eb-99d7-a47cf40e4d80.png)

**Closed by cbracken** 2020-10-14 21:46 UTC

**Comment by cbracken** [comment] 2020-10-14 21:55
@grungy01 when you installed JDK 8, if you're on a Debian/Ubuntu system, did you run `sudo update-alternatives --config java` to update which install you're using?

Not sure if that'll help, but that got things unblocked for me.

**Comment by grungy01** [comment] 2020-10-14 22:04
@cbracken yes but it says "there is only one alternative /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java, nothing to configure"

**Comment by cbracken** [comment] 2020-10-14 22:14
Ah alright; I ended up having to follow [these instructions](https://askubuntu.com/a/1006748), since I had OpenJDK 11 set up on a newly-installed machine and it seems as though the CA certs file uses a different format. Purging everything and starting over as decribed in that answer resolved the issue for me.

As far as I can tell the only real difference between our setups is that I don't have JAVA_HOME set. Not sure if that helps?

**Comment by grungy01** [comment] 2020-10-15 08:00
hi ! before the update i didn't have to specify JAVA_HOME neither :/, I  will trie to purge all the java stuff i have and re install

**Comment by grungy01** [comment] 2020-10-15 08:30
thank you ! 
The solution to purge and re-install openjdk seems to work !
