### ISSUE TITLE
Google Maps Flutter - Map just blank, but sign of Google was appear

### ISSUE THREAD

**Issue by fuaditrockz** [flutter/flutter#30649] opened 2019-04-07 20:53 UTC
I am very confused about this. No anyone got a same problem like me after I checked on Github Issues.

I just follow the instructions of used the `google_maps_flutter`, but I'm not get same result like the instructions.

This is the result of the instructions that I have followed:
<img width="437" alt="Screen Shot 2019-04-08 at 03 40 05" src="https://user-images.githubusercontent.com/18319179/55689569-2e744a00-59b0-11e9-9e35-974c2ecee676.png">

Google sign is appear! But, no for map.

This is what happened in Terminal:
```
Using hardware rendering with device Android SDK built for x86. If you get
graphics artifacts, consider enabling software rendering with
"--enable-software-rendering".
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...                                              1.3s
Resolving dependencies...                                           1.7s
Running Gradle task 'assembleDebug'...
Running Gradle task 'assembleDebug'... Done                         1.8s
Built build/app/outputs/apk/debug/app-debug.apk.
I/zzbz    ( 8116): Making Creator dynamically
D/        ( 8116): HostConnection::get() New Host Connection established 0xa0be4f40, tid 8129
D/        ( 8116): HostConnection::get() New Host Connection established 0xa0bfa940, tid 8128
W/zygote  ( 8116): Skipping duplicate class check due to unrecognized classloader
I/DynamiteModule( 8116): Considering local module com.google.android.gms.maps_dynamite:0 and remote module com.google.android.gms.maps_dynamite:221
I/DynamiteModule( 8116): Selected remote version of com.google.android.gms.maps_dynamite, version >= 221
V/DynamiteModule( 8116): Dynamite loader version >= 2, using loadModule2NoCrashUtils
W/zygote  ( 8116): Skipping duplicate class check due to unrecognized classloader
I/Google Maps Android API( 8116): Google Play services client version: 12451000
I/Google Maps Android API( 8116): Google Play services package version: 16089022
D/        ( 8116): HostConnection::get() New Host Connection established 0xa0be4a80, tid 8135
D/EGL_emulation( 8116): eglMakeCurrent: 0x9e3c3cc0: ver 3 0 (tinfo 0x9c60d4c0)
I/zygote  ( 8116): Do partial code cache collection, code=27KB, data=23KB
I/zygote  ( 8116): After code cache collection, code=27KB, data=23KB
I/zygote  ( 8116): Increasing code cache capacity to 128KB
E/GoogleMapController( 8116): Cannot enable MyLocation layer as location permissions are not granted
D/        ( 8116): HostConnection::get() New Host Connection established 0x8847f940, tid 8174
D/EGL_emulation( 8116): eglCreateContext: 0xa0e87400: maj 1 min 0 rcv 1
D/EGL_emulation( 8116): eglMakeCurrent: 0xa0e87400: ver 1 0 (tinfo 0x8847e410)
D/EGL_emulation( 8116): eglMakeCurrent: 0x9e3c3960: ver 3 0 (tinfo 0x9c60d760)
D/EGL_emulation( 8116): eglMakeCurrent: 0x9e3c3960: ver 3 0 (tinfo 0x9c60d760)
 2,270ms (!)                                                                                                                                                    🔥  To hot reload changes while running, press "r". To hot restart (and rebuild state), press "R".                                                              An Observatory debugger and profiler on Android SDK built for x86 is available
at: http://127.0.0.1:52938/
For a more detailed help message, press "h". To detach, press "d"; to quit,
press "q".
W/DynamiteModule( 8116): Local module descriptor class for com.google.android.gms.googlecertificates not found.
I/DynamiteModule( 8116): Considering local module com.google.android.gms.googlecertificates:0 and remote module com.google.android.gms.googlecertificates:4
I/DynamiteModule( 8116): Selected remote version of com.google.android.gms.googlecertificates, version >= 4
W/zygote  ( 8116): Skipping duplicate class check due to unrecognized classloader
```
If I run `flutter doctor`:
```
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.4 18E226, locale en-ID)
    • Flutter version 1.2.1 at /Users/fuaditrockz/development/flutter
    • Framework revision 8661d8aecd (7 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/fuaditrockz/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/fuaditrockz/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[!] iOS toolchain - develop for iOS devices
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS
      development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
    • ios-deploy 1.9.4
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS platform side's plugin code that
        responds to your plugin usage on the Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work
        on iOS.
        For more info, see https://flutter.io/platform-plugins
      To install:
        brew install cocoapods
        pod setup

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 34.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.33.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.25.0

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.0.0
      (API 26) (emulator)

! Doctor found issues in 1 category.
```
Btw, I deliberately did not install for IOS. So it doesn't need to be discussed.

this my `AndroidManifest.xml`:
```xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.example.cafemates">
    <application
        android:name="io.flutter.app.FlutterApplication"
        android:label="cafemates"
        android:icon="@mipmap/ic_launcher">
        <meta-data android:name="com.google.android.geo.API_KEY"
               android:value="AIzaSyCy7Uaene9DzIU8eIxxxxxxxxxxxxxx"/>
        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            <meta-data
                android:name="io.flutter.app.android.SplashScreenUntilFirstFrame"
                android:value="true" />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
    </application>
</manifest>
```

And this is my Widget code;
```dart
import 'dart:async';

import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

import '../../helpers/color_setup.dart';

class Nearby extends StatefulWidget {
  @override
  _NearbyState createState() => _NearbyState();
}

class _NearbyState extends State<Nearby> {
  final String title = "Hello, Fuadit";

  Completer<GoogleMapController> _controller = Completer();

  static const LatLng _center = const LatLng(37.42796133580664, -122.085749655962);

  void _onMapCreated(GoogleMapController controller) {
    _controller.complete(controller);
  }

  @override
  Widget build (BuildContext context) {
    return Scaffold(
      appBar: new AppBar(
        leading: new Padding(
          padding: EdgeInsets.all(8.0),
          child: new Container(
            width: 10.0,
            height: 10.0,
            decoration: new BoxDecoration(
              shape: BoxShape.circle,
              image: new DecorationImage(
                fit: BoxFit.fill,
                image: new AssetImage('images/adit.png')
              )
            ),
          ),
        ),
        title: Text(
          "$title",
          style: TextStyle(
            color: MaterialColor(0xFF2d3436, color),
            fontWeight: FontWeight.w700
          ),
        ),
        actions: <Widget>[
          IconButton(
            icon: Icon(Icons.notifications),
            tooltip: 'Open shopping cart',
            onPressed: () {
              // ...
            },
          ),
        ],
      ),
      body: GoogleMap(
        onMapCreated: _onMapCreated,
        initialCameraPosition: CameraPosition(
          target: _center,
          zoom: 14.4746,
        ),
      ),
    );
  }
}
```

Btw, I've follow instructions from this article => [https://medium.com/flutter-io/google-maps-and-flutter-cfb330f9a245](url)

**Comment by iskakaushik** [comment] 2019-04-08 16:06
@fuaditrockz , what version of the maps plugin are you using? Could you also provide a minimal version of the app for us to reproduce this issue? Thanks!

**Comment by markfili** [comment] 2019-04-08 19:58
I'm not sure about this case, but an empty screen like this happened to me when I was building a release version of the app and there was a warning in the logs to check my Google Maps API key and its restrictions, as the app's fingerprint didn't match the ones already in the Google Developers Console. I also would recommend updating the emulator to the latest Google Play Services version along with checking the Google Maps API key (maybe even trying a new one).

**Comment by ollydixon** [comment] 2019-04-21 11:05
Also have the exact same issue. I'm just running the GoogleMap widget inside a container to check that it's not some funky problem with layouts.

@markfili  I'm using a GCP Service account key so it has nothing to do with signatures.

**Comment by sprabhdeep** [comment] 2019-04-30 16:48
@markfili Did new Google Maps API key worked? asking because with current API key, the map is rendered in iOS simulator but not in android emulator. Also, Google Play services is updated, still does not render.

**Comment by petrsvobodnikspider** [comment] 2019-04-30 20:21
I did have a similar problem in iOS. Make sure you enable both apis in google developers console. maps for iOS and maps for Android
<img width="797" alt="Screen Shot 2019-05-01 at 8 20 46 AM" src="https://user-images.githubusercontent.com/36210868/56990778-14620c00-6bea-11e9-833e-7ed4033169a9.png">
<img width="639" alt="Screen Shot 2019-05-01 at 8 20 54 AM" src="https://user-images.githubusercontent.com/36210868/56990779-14faa280-6bea-11e9-8f1a-9be3bb7e97a1.png">

**Comment by palmCoconuts** [comment] 2019-05-02 22:10
I was not able to render on iOS after the recent Flutter update. Yet, it did render on Android. For some reason, when I create a new Google Map API key, it worked.

**Comment by Kaakati** [comment] 2019-05-26 04:00
@fuaditrockz 

Hey, I had a similar issue, and I tried almost everything but then I replaced this two lines:

`Completer<GoogleMapController> _controller = Completer();` 
with
 `GoogleMapController mapController;`

&

`_controller.complete(controller);` 
with 
`mapController = controller;`

and it worked fine and map loaded, I was testeing on an Android Emulator.

**Comment by mockturtl** [comment] 2019-06-13 18:05
Look for this in logcat:

```txt
Google Maps Android API  E  Authorization failure.  Please see https://developers.google.com/maps/documentation/android-api/start for how to correctly set up the map.
                         E  In the Google Developer Console (https://console.developers.google.com)
                         E  Ensure that the "Google Maps Android API v2" is enabled.
                         E  Ensure that the following Android Key exists:
                         E      API Key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
                         E      Android Application (<cert_fingerprint>;<package_name>): xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx;com.my.app
```

----

If you see maps in some builds but not others, make sure the API key allows both your debug and release fingerprints (click "Manage" in petrsvobodnikspider's screenshot for instructions).

If you use "App Signing by Google Play," there is a third fingerprint to add: _Google Play Console -> select an application -> Release management -> App signing -> App signing certificate_.

**Comment by ollydixon** [comment] 2019-06-13 18:14
The Flutter map box plugin is much better (And customisable, they have a map designer that's amazing) for anyone else suffering with this plugin.

**Comment by satyasreem** [comment] 2019-06-21 19:41
Had to enable Map SDK for iOS and Map SDK for Android
and add the following on ios/Info.plist to get it to work

`	<key>io.flutter.embedded_views_preview</key>
	<string>YES</string>
	<key>NSLocationWhenInUseUsageDescription</key>
	<string>This application requires location services to work</string>
	<key>NSLocationAlwaysUsageDescription</key>
	<string>This application requires location services to work</string>`

**Comment by SDRuiz** [comment] 2019-07-04 19:00
I have the same behavior, only in Pie (9.0) in a MotoOne.

**Comment by bsr203** [comment] 2019-07-15 23:27
I am also having same issue while running the example comes with the plugin. The log clearly indicates issue with APIKey. But it took at least few minutes to show up in the log. The log for new version showed up instantly, but the API key took some time.


```
Launching lib/main.dart on iPhone Xʀ in debug mode...
Xcode build done.                                            8.4s
	[C1.1 D52EEFA2-DE8E-4C9A-92CA-7B9D2428D42D 192.168.1.3:54834<->216.58.192.206:443]
	Connected Path: satisfied (Path is satisfied), interface: en0
	Duration: 0.240s, DNS @0.003s took 0.019s, TCP @0.027s took 0.022s, TLS took 0.083s
	bytes in/out: 4222/688, packets in/out: 9/8, rtt: 0.021s, retransmitted packets: 0, out-of-order packets: 0
Google Maps SDK for iOS version: 2.7.30514.0
New version of Google Maps SDK for iOS available: 3.2.5011.0
	[C2.1 56646855-841D-4D2E-A418-095E63723737 192.168.1.3:54835<->172.217.4.206:443]
	Connected Path: satisfied (Path is satisfied), interface: en0
	Duration: 125.707s, DNS @0.001s took 0.001s, TCP @0.005s took 0.020s, TLS took 0.068s
	bytes in/out: 8998/4779, packets in/out: 32/30, rtt: 0.062s, retransmitted packets: 0, out-of-order packets: 0
Google Maps SDK for iOS cannot connect or validate APIKey: Error Domain=com.google.HTTPStatus Code=400 "(null)" UserInfo={data=<3c48544d 4c3e0a3c 48454144 3e0a3c54 49544c45 3e426164 20526571 75657374 3c2f5449 544c453e 0a3c2f48 4541443e 0a3c424f 44592042 47434f4c 4f523d22 23464646 46464622 20544558 543d2223 30303030 3030223e 0a3c4831 3e426164 20526571 75657374 3c2f4831 3e0a3c48 323e4572 726f7220 3430303c 2f48323e 0a3c2f42 4f44593e 0a3c2f48 544d4c3e 0a>}
Your key may be invalid for your bundle ID: io.flutter.plugins.googleMobileMapsExample
	[C3.1 99368514-5EE3-449A-833E-B79B65CC007B 192.168.1.3:55088<->172.217.4.206:443]
	Connected Path: satisfied (Path is satisfied), interface: en0
	Duration: 61.071s, DNS @0.000s took 0.001s, TCP @0.002s took 0.023s, TLS took 0.069s
	bytes in/out: 4682/1213, packets in/out: 9/10, rtt: 0.025s, retransmitted packets: 1, out-of-order packets: 0
```

**Comment by heritechie** [comment] 2019-08-17 00:26
@fuaditrockz 
I think you missed the **"key="** prefix 

Just try to include "key=" prefix

```
<meta-data android:name="com.google.android.geo.API_KEY"
               android:value="key=AIzaSyCy7Uaene9DzIU8eIxxxxxxxxxxxxxx"/>
```

instead:

```
<meta-data android:name="com.google.android.geo.API_KEY"
               android:value="AIzaSyCy7Uaene9DzIU8eIxxxxxxxxxxxxxx"/>
```

**Comment by hailemix** [comment] 2019-08-21 15:22
@heritechie, no need to add "key=", the Flutter codelab says "YOUR-API-KEY".

**Comment by mberg2007** [comment] 2019-09-16 14:52
Same problem here. Maps component does not render anything and the keys are ok.

**Comment by overgaardmorten** [comment] 2019-09-23 19:58
Same problem here. Tried on both Iphone XS and X Max.

Output from console:

W0923 21:55:48.512420       1 commandlineflags.cc:1503] Ignoring RegisterValidateFunction() for flag pointer 0x105206a50: no flag found at that address
2019-09-23 21:55:49.029568+0200 Runner[2907:977811] flutter: Observatory listening on http://127.0.0.1:59265/dBJksNqLx9Y=/
CoreData: annotation:  Failed to load optimized model at path '/var/containers/Bundle/Application/DC3C91BB-153D-4717-B878-D56BC2F5B916/Runner.app/GoogleMaps.bundle/GMSCacheStorage.momd/StorageWithTileProto.omo'
CoreData: annotation:  Failed to load optimized model at path '/var/containers/Bundle/Application/DC3C91BB-153D-4717-B878-D56BC2F5B916/Runner.app/GoogleMaps.bundle/GMSCacheStorage.momd/StorageWithTileProto.omo'
CoreData: annotation:  Failed to load optimized model at path '/var/containers/Bundle/Application/DC3C91BB-153D-4717-B878-D56BC2F5B916/Runner.app/GoogleMaps.bundle/GMSCacheStorage.momd/StorageWithTileProto.omo'

**Comment by 5lineofcode** [comment] 2019-09-26 01:58
> I did have a similar problem in iOS. Make sure you enable both apis in google developers console. maps for iOS and maps for Android. Key can be shared or generate for each platform.
> <img alt="Screen Shot 2019-05-01 at 8 20 46 AM" width="797" src="https://user-images.githubusercontent.com/36210868/56990778-14620c00-6bea-11e9-833e-7ed4033169a9.png">
> <img alt="Screen Shot 2019-05-01 at 8 20 54 AM" width="639" src="https://user-images.githubusercontent.com/36210868/56990779-14faa280-6bea-11e9-8f1a-9be3bb7e97a1.png">

thanks bro, this one help me, i forget to enable maps for ios
:-)

**Comment by MartinErskine** [comment] 2019-10-04 15:13
If you run Flutter Clean that might help rebind the API key.

**Comment by wakandan** [comment] 2019-10-14 16:02
tried everything before @MartinErskine's method make it work! Thanks

**Comment by jedirichang** [comment] 2019-10-22 08:46
Ok, I do not know the reason, but surely, Activating the Android SDK and Creating a new API key resolved the issue :|

**Comment by elvisgn** [comment] 2019-10-30 17:21
I had the same issue, but I've had similar issues with other plugins before...my fix has been to open the project in Android studio and let the build execute...it fixed this issue too.

Not saying it's THE solution, just something that worked...

**Comment by EbenezerGH** [comment] 2019-11-22 05:52
Creating a new API Key and for Maps worked for me.

**Comment by kpratihast** [comment] 2019-12-06 12:43
Adding 
<meta-data android:name="com.google.android.geo.API_KEY"
android:value="YOUR_API_KEY"/>
in between </activity> and </application> in the AndroidManifest.xml file did the trick for me !

**Comment by AlBlanc** [comment] 2019-12-12 16:42
> The Flutter map box plugin is much better (And customisable, they have a map designer that's amazing) for anyone else suffering with this plugin.

It may be better once they finish the iOS implementation... For now, we're stuck with google map (Which is not that bad_

**Comment by dvthai89** [comment] 2019-12-19 03:36
> I did have a similar problem in iOS. Make sure you enable both apis in google developers console. maps for iOS and maps for Android. Key can be shared or generate for each platform.
> <img alt="Screen Shot 2019-05-01 at 8 20 46 AM" width="797" src="https://user-images.githubusercontent.com/36210868/56990778-14620c00-6bea-11e9-833e-7ed4033169a9.png">
> <img alt="Screen Shot 2019-05-01 at 8 20 54 AM" width="639" src="https://user-images.githubusercontent.com/36210868/56990779-14faa280-6bea-11e9-8f1a-9be3bb7e97a1.png">

Thanks. It solved my problem.

**Comment by Akshiiitsaxena** [comment] 2020-01-06 15:08
Going to Maps SDK for Android and enabling the API worked for me.

**Comment by mahinthan177** [comment] 2020-01-08 18:18
#Solved 
It is work for me
https://stackoverflow.com/a/59651613/10834197

**Comment by cbracken** [comment] 2020-01-10 18:56
@iskakaushik are you still the right person for this, or should @cyanglaz take this over? It sounds like we need to add documentation, at least.

**Comment by cyanglaz** [comment] 2020-01-10 19:14
@cbenhagen I will take over the maps plugin. Going to assign the issue to myself.
This issue is not on our priority list so it might take a while for me to circle back and give it a proper milestone.

**Comment by RobertasB** [comment] 2020-02-07 11:53
Had the same issue debugging the app on my phone. Turns out connecting it to The internet helps ;) (didn't notice Wi-Fi was off).

**Comment by cyanglaz** [comment] 2020-02-07 18:45
After reading the threads, I think the issue can be resolved by enable Google MAP API for both android and iOS platforms in the Google Developers Console. I'm going to update the setup steps in README about this as well.

**Comment by cyanglaz** [comment] 2020-02-07 21:48
The README is updated with a more detailed steps to set up the plugin. Closing the issue. Should anyone find this plugin still hard to set up, please feel free to fire another issue or start a PR.

**Closed by cyanglaz** 2020-02-07 21:48 UTC
Labels: p: maps, plugin

**Comment by fzeladaEcoT** [comment] 2020-02-18 23:47
What worked for me was changing the emulator Android version, to one with Play support. Just in case

**Comment by dikongue** [comment] 2020-04-11 02:37
Affichage du logo Google sans carte
