### ISSUE TITLE
não consigo criar projeto

### ISSUE THREAD

**Issue by FagnerSantos1982** [flutter/flutter#72959] opened 2020-12-25 15:18 UTC
![erroflutter](https://user-images.githubusercontent.com/76591718/103137828-54bdaa00-46ab-11eb-87d9-171db4c87a22.jpg)

**Comment by iapicca** [comment] 2020-12-25 20:38
possible duplicate of https://github.com/flutter/flutter/issues/69116

**Comment by pedromassangocode** [comment] 2020-12-28 09:01
Hi @FagnerSantos1982 
I see there's an open issue (https://github.com/flutter/flutter/issues/69116) addressing the case you described.
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by pedromassangocode** 2020-12-28 09:01 UTC
