### ISSUE TITLE
[tool_crash] String: <57 characters>

### ISSUE THREAD

**Issue by golkiyasomil** [flutter/flutter#112746] opened 2022-10-01 06:37 UTC
## Command
```
flutter --no-color run --machine --device-id=US5TLZWO99999999 --profile --dart-define=flutter.inspector.structuredErrors=true lib\main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
String: <57 characters>
```

```
```
[✓] Flutter (Channel stable, 3.0.5, on Microsoft Windows [Version 10.0.19044.2075], locale en-IN)
    • Flutter version 3.0.5 at D:\FlutterSdk\flutter_windows_3.0.5-stable\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (3 months ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\golki\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✗] Visual Studio - develop for Windows
    ✗ Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[✓] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] Connected device (4 available)
    • A1601 (mobile)    • US5TLZWO99999999 • android-arm64  • Android 5.1 (API 22)
    • Windows (desktop) • windows          • windows-x64    • Microsoft Windows [Version 10.0.19044.2075]
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 105.0.5195.127
    • Edge (web)        • edge             • web-javascript • Microsoft Edge 105.0.1343.53

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: f1875d570e39de09040c8f79aa13cc56baab8db1

**Comment by darshankawar** [comment] 2022-10-03 06:08
Closing as duplicate of https://github.com/flutter/flutter/issues/108812

**Closed by darshankawar** 2022-10-03 06:08 UTC
Labels: in triage
