### ISSUE TITLE
Animation causes higher cpu gpu usage on IOS

### ISSUE THREAD

**Issue by kxifenger** [flutter/flutter#87614] opened 2021-08-04 02:45 UTC
## Details

**Target Platform: iphone
**Target OS version/browser:ios13.6
**Devices:iphonex
flutter version 2.2.3
## Logs

<details>
<summary>Logs</summary>

show the loading view like this

<img src= "https://user-images.githubusercontent.com/77945871/128113126-da33048c-2eae-4bcd-beaa-1131676f1555.PNG" width="400">

the animation code like this
![215BD9A2-9D1C-4192-AEC8-A4AF941AFFF2](https://user-images.githubusercontent.com/77945871/128113328-cd69d2a3-109f-44f3-8600-d95a88fc7142.png)
the cpu and gpu performance like this
![截屏2021-08-04 上午10 32 21](https://user-images.githubusercontent.com/77945871/128113414-8d5c357d-9692-430e-b402-a20c2acde106.png)

after a few minutes the iphone become very hot.

```
```

</details>

**Comment by maheshmnj** [comment] 2021-08-04 07:18
Hi @kxifenger, 
Thanks for filing the issue, please provide the output of `flutter doctor -v` along with [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) and not a screenshot of the code, This helps to better investigate the issue.

Thank you.

**Comment by kxifenger** [comment] 2021-08-05 03:13
hi @maheshmnj 
here is the output of flutter doctor -v
4dage_imacmini@appledeMini-2 ~ % flutter doctor -v                
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-x64, locale
    zh-Hans-CN)
    • Flutter version 2.2.3 at /Users/4dage_imacmini/Documents/flutter
    • Framework revision f4abaa0735 (5 周前), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/4dage_imacmini/Library/Android/sdk
    • Platform android-30, build-tools 29.0.2
    • ANDROID_HOME = /Users/4dage_imacmini/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.58.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.24.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 92.0.4515.131

• No issues found!
4dage_imacmini@appledeMini-2 ~ % 
here is the code 
import 'package:flutter/cupertino.dart';
import 'package:flutter_svg/svg.dart';

class CustomLoadingView extends StatefulWidget {
  @override
  State<StatefulWidget> createState() => CustomLoadingViewState();
  final isLoadingWhite;

  CustomLoadingView({this.isLoadingWhite = true});

}

class CustomLoadingViewState extends State<CustomLoadingView> with SingleTickerProviderStateMixin {
  AnimationController controller;

  @override
  void initState() {
    controller =
        AnimationController(duration: const Duration(seconds: 2), vsync: this);
    //动画开始、结束、向前移动或向后移动时会调用StatusListener
    controller.repeat();
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Center(
      child: Container(
        width: 36,
        height: 36,
        child: RotationTransition(turns: controller,
            alignment: Alignment.center,
            child: SvgPicture.asset(widget.isLoadingWhite
                ? "assets/svg/icon_loading_white.svg"
                : "assets/svg/icon_loading_yellow.svg")),
      ),
    );
  }

  @override
  void dispose() {
    // 释放资源
    controller.dispose();
    super.dispose();
  }
}

**Comment by maheshmnj** [comment] 2021-08-05 05:59
@kxifenger the code you shared isn't complete in order to reproduce the issue, I modified your code sample a bit and did not see any significant CPU usage, Could you please share the complete code.

 <details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatefulWidget {
  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        title: 'Flutter Demo',
        theme: ThemeData(
            brightness: Brightness.dark,
            primaryColor: Colors.red,
            colorScheme: const ColorScheme.dark()
                .copyWith(onPrimary: Colors.black, onSurface: Colors.black)),
        home: MyHomePage(title: 'animation'));
  }
}
class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final ValueNotifier<int> _counter = ValueNotifier<int>(0);
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text(widget.title)),
      body: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: <Widget>[ChildAnimation()],
      ),
      floatingActionButton: FloatingActionButton(
        child: const Icon(Icons.plus_one),
        onPressed: () => _counter.value += 1,
      ),
    );
  }
}

class ChildAnimation extends StatefulWidget {
  const ChildAnimation({Key? key}) : super(key: key);

  @override
  State<ChildAnimation> createState() => _ChildAnimationState();
}

class _ChildAnimationState extends State<ChildAnimation>
    with SingleTickerProviderStateMixin {
  @override
  void initState() {
    // TODO: implement initState
    super.initState();
    _animationController = AnimationController(
      duration: Duration(seconds: 3),
      vsync: this,
    );
    _animationController.repeat();
   
  }

  late AnimationController _animationController;

  @override
  void dispose() {
    // TODO: implement dispose
    super.dispose();
    _animationController.dispose();
  }

  @override
  Widget build(BuildContext context) {
    print('Child rebuilt');
    return AnimatedBuilder(
      animation: _animationController,
      builder: (context, _) => Transform.rotate(
          angle: _animationController.value * 2 * pi,
          child: Container(color: Colors.red, height: 100, width: 100)),
    );
  }
}
```
</details>

 <details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-arm, locale en-GB)
    • Flutter version 2.2.3 at /Users/mahesh/Documents/flutter
    • Framework revision f4abaa0735 (4 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 57.0.5
    • Dart plugin version 211.7233

[✓] VS Code (version 1.58.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.24.0

[✓] Connected device (4 available)
    • Redmi K20 Pro (mobile)     • 192.168.1.3:5555                     • android-arm64  • Android 11 (API 30)
    • iPhone 12 Pro Max (mobile) • 6A434744-B348-4FB3-AB10-131292174456 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 11.4 20F71 darwin-arm
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 92.0.4515.107

• No issues found!
```
</details>


This the cpu usage for the above code sample 

![image](https://user-images.githubusercontent.com/31410839/128296911-f13658ed-38bc-4590-a9a9-e1e98313133f.png)

**Comment by kxifenger** [comment] 2021-08-05 07:31
thank you @maheshmnj 
i found you use the ios simulator not the real iphone，i use the real iphone. 
please watch the energy impact
![1628148584162](https://user-images.githubusercontent.com/77945871/128309767-7c9f8c7f-01e8-46d6-b920-31298c407af7.jpg)
here is the code which is different from before，but have same performance
class SplashPage extends StatefulWidget {
  @override
  _SplashPageState createState() => _SplashPageState();
}

class _SplashPageState extends State<SplashPage> {
  @override
  void initState() {
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Container(
          decoration: BoxDecoration(),
          child: Stack(
            children: [
           
                  Center(child: SpinKitCircle(color: Colors.white),),       
            ],
          )),
    );
  }
}

**Comment by maheshmnj** [comment] 2021-08-05 12:42
@kxifenger My colleague @darshankawar verified the issue on his physical iPhone 6s and could not replicate the issue too, The CPU usage was normal as intended on the latest stable channel

<details>
<summary> flutter doctor -v </summary>

```
[✓] Flutter (Channel stable, 2.2.3, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.2.3 at /Users/dhs/documents/fluttersdk/flutter
    • Framework revision f4abaa0735 (4 days ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/dhs/Library/Android/sdk
    • Java binary at: /Users/dhs/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.    

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Users/dhs/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)        

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (4 available)
    • SM G975F (mobile) • RZ8M802WY0X • android-arm64 • Android 10 (API 29)
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 91.0.4472.114

• No issues found!
```
</details>

Keeping this issue open for further investigation from the team.

**Comment by kxifenger** [comment] 2021-08-06 02:58
thank you @maheshmnj 
i found that you just watch the cup. can you also watch the Gpu.

Do you notice that the cpu is about 5% before the animation start, after amination start the cup up to about 20%. 
is it reseonable?

**Comment by Hixie** [comment] 2021-08-10 23:08
(Triage note: I've left this in the platform-ios bucket, where it may be looked at in due course, but if we are unable to reproduce it it is unlikely we will be able to fix it. If you have the chance to study this further and e.g. maybe see if it's specific to particular hardware, particular OS versions, or some other particular detail of the system, that would be very valuable in helping us work on this. Thanks.)

**Comment by maheshmnj** [comment] 2021-08-16 08:37
@kxifenger I verified on iphoneXs using your [spinkit example](https://github.com/flutter/flutter/issues/87614#issuecomment-893233702) and I could see there was significant cpu and energy usage on the stable channel but on the latest master channel it was not the case.

<details>
<summary>output</summary>

### Stable ❌

https://user-images.githubusercontent.com/31410839/129534469-668b67ab-0c30-4ad2-8ca1-affda62c70ed.mov

### Master ✅  

https://user-images.githubusercontent.com/31410839/129533916-1e20a2a8-c01a-4a0d-8f1f-c5b7f6b41cf9.mov

✅ : No Issue ❌: Issue reproduced

</details> 

Can you please switch to master channel and see if you are still seeing the same results by running 

```
flutter channel master
flutter upgrade
flutter clean
```

you can switch back to stable later by running `flutter channel stable`

**Comment by kxifenger** [comment] 2021-08-24 02:23
@maheshmnj  thank you
according to your suggestion, i switch to  master channel
here is the output of flutter doctor -v
[✓] Flutter (Channel master, 2.5.0-7.0.pre.211, on macOS 11.4 20F71 darwin-x64,
    locale zh-Hans-CN)
    • Flutter version 2.5.0-7.0.pre.211 at
      /Users/4dage_imacmini/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 56b681247d (89 分钟前), 2021-08-23 20:44:05 -0400
    • Engine revision 926ce0d855
    • Dart version 2.15.0 (build 2.15.0-43.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/4dage_imacmini/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.

[✓] Xcode - develop for iOS and macOS (Xcode 12.5.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.59.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (2 available)
    • iPhoneX (mobile) • cc86d412505ab211a7c861783605b66b1b2348c9 • ios
      • iOS 13.6 17G68
    • Chrome (web)     • chrome                                   •
      web-javascript • Google Chrome 92.0.4515.159

! Doctor found issues in 1 category.
when i build the project, there is a new problem appear.like this
https://github.com/flutter/flutter/issues/88219
but i do not know how to solve it.

**Comment by maheshmnj** [comment] 2021-08-24 12:31
@kxifenger As far as I can understand from the error you are using [oktoast: 2.3.2](https://pub.dev/packages/oktoast) in your application which probably isn't compatible with flutter master due to some breaking changes in  textTheme. I also see that the latest version is `okToast:3.1.1` please try upgrading the version in pubspec

```
flutter clean
flutter pub get
```
see if this fixes the issue.

**Comment by darshankawar** [comment] 2021-09-17 13:00
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by darshankawar** 2021-09-17 13:00 UTC
Labels: platform-ios, waiting for customer response, framework, a: animation, severe: performance, passed first triage
