### ISSUE TITLE
flutter (2.5.0-5.2.pre) deletes the .gradle cache folder if an error occurs when building an apk

### ISSUE THREAD

**Issue by fabiancrx** [flutter/flutter#89000] opened 2021-08-26 21:48 UTC
If for some reason gradle fails at any step either during `flutter run` or `flutter build` it deletes the whole .gradle cache.
## Steps to Reproduce

Here we are cutting down the internet so that gradle errors and the bug is reproducible

0- (OPTIONAL) Probably check your $HOME/.gradle folder size for comparison
1- `flutter create sample`
2- `cd sample`
3- Disconnect from internet so that gradle fails to download dependencies
4- flutter build apk --release
5- check $HOME/.gradle it should be empty now

**Expected results:**
flutter maintains my cached gradle artifacts 

**Actual results:** 
![image](https://user-images.githubusercontent.com/37002358/131039914-d67fa2b2-da4b-4e8d-adf0-8a449e5d736b.png)

<details>
  <summary>
Flutter Logs
</summary>

Gradle errors as expected due to not having internet 
```
Running Gradle task 'assembleRelease'...                           47.0s
[!] Gradle threw an error while downloading artifacts from the network. Retrying to download...
Exception in thread "main" java.net.UnknownHostException: services.gradle.org
        at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:220)
        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
        at java.base/java.net.Socket.connect(Socket.java:609)
        at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:289)
        at java.base/sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
        at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:182)
        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:474)
        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:569)
        at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:265)
        at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:372)
        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1187)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081)
        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1592)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250)
        at org.gradle.wrapper.Download.downloadInternal(Download.java:58)
        at org.gradle.wrapper.Download.download(Download.java:44)
        at org.gradle.wrapper.Install$1.call(Install.java:61)
        at org.gradle.wrapper.Install$1.call(Install.java:48)
        at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
        at org.gradle.wrapper.Install.createDist(Install.java:48)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)

```

```
[✓] Flutter (Channel beta, 2.5.0-5.2.pre, on Fedora 34 (KDE Plasma) 5.13.4-200.fc34.x86_64, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 4.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.1)
[✓] VS Code (version 1.58.2)
[✓] Connected device (2 available)

```

</details>

**Comment by TahaTesser** [comment] 2021-08-30 06:33
Hi @fabiancrx 
Can you please upgrade to the latest  `master` and try again
Execute the following commands to upgrade
`flutter channel master`
`flutter upgrade --force`
`flutter doctor -v`

**Comment by jason-simmons** [comment] 2021-08-30 20:45
This is done as a workaround for potentially corrupt cached files when the Flutter tool sees network errors from Gradle.

See https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/android/gradle_errors.dart#L98

**Comment by TahaTesser** [comment] 2021-08-31 06:56
@jason-simmons 
Thanks!

@fabiancrx 
This looks like it is working as designed.


Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-08-31 06:56 UTC
Labels: waiting for customer response, in triage

**Comment by fabiancrx** [comment] 2021-08-31 12:52
Thanks @TahaTesser, I'm pretty constrained about bandwidth and in this same position are many developers in my country. For example if flutter deletes my gradle cache due to unstable network (which is pretty usual) losing 2-4 GB of previously downloaded data is a hit. And as a workaround I've made a backup of the gradle folder and re-extract it every time flutter-beta cleans my cache , which sadly happens many times a day. At least for me as a developer with inconsistent internet access due to connection resets its really a stepback. Personally manually managing gradle issues and zip corruptions at least for me has not been that common issue. Would it be possible to evaluate this default behavior or at least provide a configuration flag to turn it off. This would really be an impediment for me to work with flutter.
