### ISSUE TITLE
null value in _TabBarViewState._handleTabControllerAnimationTick

### ISSUE THREAD

**Issue by martinpelli** [flutter/flutter#146439] opened 2024-04-08 16:48 UTC
### Steps to reproduce

I am not sure how to reproduce it, this is something only happening on production for my app, I guess is only happening in release mode. Crashlytics is spaming my console with this error.

1. Add TabBarView widget with a DefaultTabController as parent
2. Change tabs

### Expected results

No error should be thrown

### Actual results

FlutterError - Null check operator used on a null value. Error thrown .

### Code sample

<details open><summary>Code sample</summary>

```dart
There is no way to create a minimal reproducible sample
```

</details>

### Screenshots or Video

<details open>
<summary>This is the function breaking, !_controller!.indexIsChanging is null</summary>

![image](https://github.com/flutter/flutter/assets/63437171/0c40f18a-56d4-43e0-a964-01e37c326045)

</details>

### Logs

<details open><summary>Logs</summary>

```console
Fatal Exception: FlutterError
0  ???                            0x0 _TabBarViewState._handleTabControllerAnimationTick + 1911 (tabs.dart:1911)
1  ???                            0x0 AnimationLocalListenersMixin.notifyListeners + 161 (listener_helpers.dart:161)
2  ???                            0x0 AnimationController.value= + 395 (animation_controller.dart:395)
3  ???                            0x0 TabController._copyWithAndDispose + 158 (tab_controller.dart:158)
4  ???                            0x0 _DefaultTabControllerState.didUpdateWidget + 501 (tab_controller.dart:501)
5  ???                            0x0 StatefulElement.update + 5652 (framework.dart:5652)
6  ???                            0x0 Element.updateChild + 3824 (framework.dart:3824)
7  ???                            0x0 ComponentElement.performRebuild + 5505 (framework.dart:5505)
8  ???                            0x0 StatefulElement.performRebuild + 5643 (framework.dart:5643)
9  ???                            0x0 Element.rebuild + 5196 (framework.dart:5196)
10 ???                            0x0 StatefulElement.update + 5666 (framework.dart:5666)
11 ???                            0x0 Element.updateChild + 3824 (framework.dart:3824)
12 ???                            0x0 ComponentElement.performRebuild + 5505 (framework.dart:5505)
13 ???                            0x0 StatefulElement.performRebuild + 5643 (framework.dart:5643)
14 ???                            0x0 Element.rebuild + 5196 (framework.dart:5196)
15 ???                            0x0 BuildOwner.buildScope + 2904 (framework.dart:2904)
16 ???                            0x0 WidgetsBinding.drawFrame + 989 (binding.dart:989)
17 ???                            0x0 RendererBinding._handlePersistentFrameCallback + 448 (binding.dart:448)
18 ???                            0x0 SchedulerBinding._invokeFrameCallback + 1386 (binding.dart:1386)
19 ???                            0x0 SchedulerBinding.handleDrawFrame + 1311 (binding.dart:1311)
20 ???                            0x0 SchedulerBinding._handleDrawFrame + 1169 (binding.dart:1169)
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.19.5, on macOS 14.4.1 23E224 darwin-arm64, locale en-AR)
    • Flutter version 3.19.5 on channel stable at /Users/martinpelli/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 300451adae (12 days ago), 2024-03-27 21:54:07 -0500
    • Engine revision e76c956498
    • Dart version 3.3.3
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/martinpelli/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.15.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.88.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.84.0

[✓] Connected device (4 available)
    • Pelli’s iPhone (mobile) • 00008130-000A59E83660001C            • ios            • iOS 17.4.1 21E236
    • iPhone 15 Pro (mobile)  • B0ACA5DD-71DF-4E17-B4DC-14497D3A7917 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-0 (simulator)
    • macOS (desktop)         • macos                                • darwin-arm64   • macOS 14.4.1 23E224 darwin-arm64
    • Chrome (web)            • chrome                               • web-javascript • Google Chrome 123.0.6312.107
    ! Error: Browsing on the local area network for iPhone de Ezequiel. Ensure the device is unlocked and attached with a cable or associated with the same local
      area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by danagbemava-nc** [comment] 2024-04-09 08:47
I believe this is a duplicate of https://github.com/flutter/flutter/issues/86222. 

Kindly follow up in the original issue for updates. 

Closing in favor of the issue linked above. 

Thank you

**Closed by danagbemava-nc** 2024-04-09 08:47 UTC
Labels: in triage
