### ISSUE TITLE
RenderRepaintBoundary.toImage fails for WebView content

### ISSUE THREAD

**Issue by uldaman** [flutter/flutter#33568] opened 2019-05-30 10:55 UTC
I am using `RenderRepaintBoundary.toImage` to take a screenshot, but just got the blank.

The code for the webview.

```dart
class _CustomWebViewState extends State<CustomWebView> {

  final GlobalKey screen = GlobalKey();

  @override
  Widget build(BuildContext context) {
    super.build(context);

    return RepaintBoundary(
      key: screen,
      child: InAppWebView(),
    );
  }
}
```

The code for the screenshot.

```dart
RenderRepaintBoundary boundary = screen.currentContext.findRenderObject();
ui.Image image = await boundary.toImage();
```

Flutter throws an exception when executing `boundary.toImage()`:

```
[VERBOSE-2:platform_view_layer.cc(19)] Trying to embed a platform view but the PrerollContext does not support embedding
[VERBOSE-2:platform_view_layer.cc(28)] Trying to embed a platform view but the PaintContext does not support embedding
```

I have already set the `Info.plist` file:

```
<key>io.flutter.embedded_views_preview</key>
<true/>
```

**Comment by yukitaka13-1110** [comment] 2019-11-11 13:22
I encountered the same problem.
I tried to convert PlatformView (AgoraRtcEngine) to PNG image, but failed.

**Comment by yukitaka13-1110** [comment] 2020-06-17 17:38
@iapicca Any progress?

**Comment by iapicca** [comment] 2020-06-19 12:31
Hi @uldaman 
are you still experiencing the issue with the latest version of flutter?

Can you please provide your `flutter doctor -v`, 
your `flutter run --verbose`, 
your `pubspec.yaml` 
and a minimal reproducible code sample.
Thank you

**Comment by yukitaka13-1110** [comment] 2020-06-20 08:19
@iapicca I still experiencing this issue.
This is my reproduce example.
https://github.com/yukitaka13-1110/flutter_webview_reproduce_example
Please check this repository?
Thank you

**Comment by iapicca** [comment] 2020-06-26 05:58
Hi @yukitaka13-1110 
Can you please 
run `flutter upgrade -f`
and provide your updated `flutter doctor -v`, 
your `flutter run --verbose`, 
your `pubspec.yaml` and a minimal reproducible code sample
without 3rd party plugins ([agora_rtc_engine](https://pub.dev/packages/agora_rtc_engine))
Thank you

**Comment by yukitaka13-1110** [comment] 2020-06-29 13:47
@iapicca 
This error only occurred when using `agora_rtc_engine`.
Tried to call `toImage()` and failed (black image).

I asked the author of `agora_rtc_engine` before, but they told me to ask here because it's a bug on the flutter side.
So, `without 3rd party plugins` doesn't make sense.

Thank you.

**Comment by VladyslavBondarenko** [comment] 2020-07-22 14:24
Please follow up on https://github.com/flutter/flutter/issues/25306,
I'm closing the current one as duplicate.
If you disagree please write in the comments and I will reopen it

**Closed by VladyslavBondarenko** 2020-07-22 14:24 UTC
Labels: p: first party, p: webview, plugin

**Comment by shivamagarwal2097** [comment] 2021-06-14 13:48
hi i have same issue in apple_map_flutter
any solution for this?
