### ISSUE TITLE
Material icon from material.io not found

### ISSUE THREAD

**Issue by NicoDreamzZ** [flutter/flutter#18849] opened 2018-06-26 21:16 UTC
Hey,
today i noticed that many of the icons from https://material.io/tools/icons/?style=baseline aren't implemented in the Icons class. Maybe there is an possibility to update the icons.
<img width="219" alt="grafik" src="https://user-images.githubusercontent.com/12086166/41939518-646c143a-7996-11e8-9c90-a668d43b4a74.png"> This is one for example that isnt in the Icons class.

My flutter doctor output:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v0.5.6-pre.76, on Mac OS X 10.13.5 17F77, locale de-DE)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.0)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
[✓] Android Studio (version 3.1)
[!] IntelliJ IDEA Ultimate Edition (version 2018.1.5)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.24.1)
[✓] Connected devices (1 available)
```

**Comment by zoechi** [comment] 2019-01-28 14:44
I think this is a duplicate of https://github.com/google/material-design-icons/issues/786

**Comment by csells** [comment] 2020-01-13 16:24
Closed as duplicate of google/material-design-icons#786

**Closed by csells** 2020-01-13 16:24 UTC
Labels: a: assets, framework
