### ISSUE TITLE
Facing issue when running "Flutter doctor" command in cmd

### ISSUE THREAD

**Issue by mukulchauhan3** [flutter/flutter#117822] opened 2022-12-30 14:36 UTC
```
`Failed to find the latest git commit date: VersionCheckError: Command exited with code 128: git -c
log.showSignature=false log HEAD -n 1 --pretty=format:%ad --date=iso
Standard out:
Standard error: fatal: detected dubious ownership in repository at 'C:/src/flutter'
'C:/src/flutter' is owned by:
        'S-1-5-32-544'
but the current user is:
        'S-1-5-21-425165268-2986998246-3957258218-1001'
To add an exception for this directory, call:

        git config --global --add safe.directory C:/src/flutter

Returning 1970-01-01 05:30:00.000 instead.`
```

**Comment by darshankawar** [comment] 2023-01-02 06:29
Thanks for the report @mukulchauhan3 
Based on the error log, it seems to be related to the permission, as it says `Standard error: fatal: detected dubious ownership in repository at 'C:/src/flutter'`

The tool is correctly identifying what could be the cause of the issue, as it shows the current user and the permission owner, so double check the permission setup and see if correct user is logged in. Also try to use the command as suggested by the tool `git config --global --add safe.directory C:/src/flutter` and see if it helps.

I am going ahead and closing this, since this could be related to the way permissions are setup in your system and tool identified that and suggested the fix. If you still get the same error after trying with the fix, write in comments and I'll reopen it.

**Closed by darshankawar** 2023-01-02 06:29 UTC
Labels: in triage
