### ISSUE TITLE
running flutter doctor on ARM64

### ISSUE THREAD

**Issue by fiurthorn** [flutter/flutter#60266] opened 2020-06-25 06:06 UTC
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel stable, v1.17.4, on Linux, locale en_US.UTF-8)
    ✗ Downloaded executables cannot execute on host.
      See https://github.com/flutter/flutter/issues/6207 for more information
      On Debian/Ubuntu/Mint: sudo apt-get install lib32stdc++6
      On Fedora: dnf install libstdc++.i686
      On Arch: pacman -S lib32-gcc-libs

**Comment by VladyslavBondarenko** [comment] 2020-06-25 12:35
@fiurthorn 
does it help if you execute needed command

```
On Debian/Ubuntu/Mint: sudo apt-get install lib32stdc++6
On Fedora: dnf install libstdc++.i686
On Arch: pacman -S lib32-gcc-libs
```
?

**Comment by fiurthorn** [comment] 2020-06-25 17:00
Unfortunately not, since the package does not exist under ARM64.

sudo apt-get install lib32stdc ++ 6
Reading package lists ... Done
Building dependency tree
Reading state information ... Done
E: Unable to locate package lib32stdc ++ 6
E: Couldn't find any package by regex 'lib32stdc ++ 6'

**Comment by HidenoriMatsubayashi** [comment] 2020-08-05 05:58
I've been working on supporting ARM64 Host. https://github.com/flutter/engine/pull/20254

**Comment by iapicca** [comment] 2020-10-07 08:36
@TahaTesser 
possible duplicate of https://github.com/flutter/flutter/issues/56992

**Comment by TahaTesser** [comment] 2020-10-07 13:00
Hi @fiurthorn 
Looks like this is currently not supported yet, closing as a duplicate of https://github.com/flutter/flutter/issues/56992

**Closed by TahaTesser** 2020-10-07 13:00 UTC
Labels: platform-linux, tool
