### ISSUE TITLE
How is the iOS Flutter. Framework packaged as a static library instead of a dynamic library?

### ISSUE THREAD

**Issue by 709213219** [flutter/flutter#53822] opened 2020-04-02 11:25 UTC
How is the iOS Flutter. Framework packaged as a static library instead of a dynamic library?

**Comment by VladyslavBondarenko** [comment] 2020-04-02 11:41
Hi @709213219 
Take a look at https://github.com/flutter/flutter/issues/33835#issuecomment-498938488
Closing as duplicate of https://github.com/flutter/flutter/issues/33835
if you disagree please write in the comments and I will reopen it
Thank you

**Closed by VladyslavBondarenko** 2020-04-02 11:41 UTC
