### ISSUE TITLE
Flutter 1.8.2 Connection to Android devices breaks in Android Studio / IntelliJ IDEA

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [flutter/flutter#36150] opened 2019-07-14 09:45 UTC
After upgrading to Flutter 1.8.2, i.e. `Channel master, v1.8.2-pre.33`, I cannot view logs on Android emulator API 28 anymore.

```E/DartVM  (15034): vm-service: Error: Unhandled exception:
E/DartVM  (15034): Unrecognized response: null
E/DartVM  (15034): #0      new Response.from (dart:_vmservice/message_router.dart:70:7)
E/DartVM  (15034): #1      Message._setResponseFromPort (dart:_vmservice/message.dart:244:29)
E/DartVM  (15034): #2      Message.sendToVM.<anonymous closure> (dart:_vmservice/message.dart:216:7)
E/DartVM  (15034): #3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
E/DartVM  (15034): 
E/flutter (15034): [ERROR:flutter/runtime/dart_isolate.cc(814)] Unhandled exception:
E/flutter (15034): Unrecognized response: null
E/flutter (15034): #0      new Response.from (dart:_vmservice/message_router.dart:70:7)
E/flutter (15034): #1      Message._setResponseFromPort (dart:_vmservice/message.dart:244:29)
E/flutter (15034): #2      Message.sendToVM.<anonymous closure> (dart:_vmservice/message.dart:216:7)
E/flutter (15034): #3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

After startup, this error is printed to logs and then `Lost connection to device.`  

I cannot use API 29, because of #33050, meaning that this prevents me from debugging.  

I am using `flutter run` manually right now, however, the Android Studio "Run" window is a lot nicer.

Is there a way I can fix this on my end?

**Comment by KagurazakaHanabi** [comment] 2019-07-14 11:43
Same problem.

## Steps to Reproduce

Click the run button on Android Studio

`flutter run` is no problem for me.

## Logs
```
Lost connection to device.
E/DartVM  ( 6730): vm-service: Error: Unhandled exception:
E/DartVM  ( 6730): Unrecognized response: null
E/DartVM  ( 6730): #0      new Response.from (dart:_vmservice/message_router.dart:70:7)
E/DartVM  ( 6730): #1      Message._setResponseFromPort (dart:_vmservice/message.dart:244:29)
E/DartVM  ( 6730): #2      Message.sendToVM.<anonymous closure> (dart:_vmservice/message.dart:216:7)
E/DartVM  ( 6730): #3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
E/DartVM  ( 6730): 
E/flutter ( 6730): [ERROR:flutter/runtime/dart_isolate.cc(814)] Unhandled exception:
E/flutter ( 6730): Unrecognized response: null
E/flutter ( 6730): #0      new Response.from (dart:_vmservice/message_router.dart:70:7)
E/flutter ( 6730): #1      Message._setResponseFromPort (dart:_vmservice/message.dart:244:29)
E/flutter ( 6730): #2      Message.sendToVM.<anonymous closure> (dart:_vmservice/message.dart:216:7)
E/flutter ( 6730): #3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
Failed to send request: {"jsonrpc":"2.0","id":"4","method":"streamListen","params":{"streamId":"Extension"}}
Failed to send request: {"jsonrpc":"2.0","id":"5","method":"getVM","params":{}}
Failed to send request: {"jsonrpc":"2.0","id":"6","method":"getVM","params":{}}
```

## flutter doctor -v
```
[√] Flutter (Channel master, v1.8.2-pre.33, on Microsoft Windows [Version 10.0.18932.1000], locale zh-CN)
    • Flutter version 1.8.2-pre.33 at D:\flutter
    • Framework revision e3ee5c6bbb (13 hours ago), 2019-07-13 16:02:09 -0700
    • Engine revision 919e353236
    • Dart version 2.5.0 (build 2.5.0-dev.1.0 24725a8559)


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at D:\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-Q, build-tools 28.0.3
    • Java binary at: D:\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2017 15.9.11)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2017\Community
    • Visual Studio Community 2017 version 15.9.28307.586

[√] Android Studio (version 3.4)
    • Android Studio at D:\Android\Android Studio
    • Flutter plugin version 37.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] VS Code (version 1.36.0)
    • VS Code at C:\Users\Yaerin\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.2.0

[√] Connected device (3 available)
    • xiaomi 6 • emulator-5554 • android-x86    • Android 5.1.1 (API 22)
    • Windows  • Windows       • windows-x64    • Microsoft Windows [Version 10.0.18932.1000]
    • Chrome   • chrome        • web-javascript • Google Chrome 75.0.3770.100

• No issues found!
```

**Comment by alexei-g-aloteq** [comment] 2019-07-14 17:59
Same issue - definitely a bug, started to appear after today's Flutter upgrade.

**Comment by rafaelph** [comment] 2019-07-15 04:29
I'm having the same thing. Hot reload stops working and you have to run from cold to update the app in an emulator

**Comment by apm29** [comment] 2019-07-15 05:28
same issue

**Comment by josepalbert95** [comment] 2019-07-15 08:46
Same here

[√] Flutter (Channel master, v1.8.2-pre.56, on Microsoft Windows [VersiÃ³n 10.0.17134.228], locale ca-ES)
    • Flutter version 1.8.2-pre.56 at C:\src\flutter
    • Framework revision 90326b6184 (3 days ago), 2019-07-12 09:46:48 +0530
    • Engine revision d1dcd18486
    • Dart version 2.5.0 (build 2.5.0-dev.1.0 24725a8559)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:/Users/josep.albert/AppData/Local/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = C:/Users/josep.albert/AppData/Local/Android/Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

**Comment by AlanSGC** [comment] 2019-07-15 20:22
same issue

**Comment by KamalPatra** [comment] 2019-07-15 20:24
Yes, I am also facing the same issue, simulator and android studio gets disconnected.

**Comment by creativecreatorormaybenot** [comment] 2019-07-15 20:38
For everyone that is also experiencing this issue: you should really upvote the original post, i.e. [the first comment in here](https://github.com/flutter/flutter/issues/36150#issue-467816530), which will improve the rank of this issue in sorting as commenting the same things over and over only clutters this thread.

**Comment by collinjackson** [comment] 2019-07-15 21:45
Took a quick look at this.

I am able to reproduce the issue on MacOS with IntelliJ IDEA. Running the app from the IDE on a simulator fails.

Using git bisect narrowed it down to #36000 which is flutter/engine#9767, flutter/engine#9727, and a src/third_party/dart roll from 09fc76bc51..24725a8559

**Comment by zanderso** [comment] 2019-07-15 22:26
@bkonyi It looks like the VM service is hitting an exception.

**Comment by bkonyi** [comment] 2019-07-15 22:29
> @bkonyi It looks like the VM service is hitting an exception.

Yeah, the Flutter Intellij plugin is still trying to use `_registerService` instead of `registerService` in one place. See https://github.com/flutter/flutter-intellij/issues/3670.

cc/ @devoncarew

**Comment by garbirel94** [comment] 2019-07-16 06:08
same here

**Comment by prasant10050** [comment] 2019-07-16 06:56
> Yes, I am also facing the same issue, simulator and android studio gets disconnected.

I am facing this issue

**Comment by Woolol** [comment] 2019-07-16 09:19
same issue

**Comment by LaurentiuSimionescu** [comment] 2019-07-16 10:46
I have the same issue.

> E/flutter (22542): [ERROR:flutter/runtime/dart_isolate.cc(814)] Unhandled exception:
> E/flutter (22542): Unrecognized response: null
> E/flutter (22542): #0      new Response.from (dart:_vmservice/message_router.dart:70:7)
> E/flutter (22542): #1      Message._setResponseFromPort (dart:_vmservice/message.dart:244:29)
> E/flutter (22542): #2      Message.sendToVM.<anonymous closure> (dart:_vmservice/message.dart:216:7)
> E/flutter (22542): #3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
> Lost connection to device.

**Comment by Loopex2019** [comment] 2019-07-16 11:26
For me i am running the flutter app on a physical Android Device but the app is working fine without a Crash but the Hot Reload Feature isn't working.

**Comment by PoojaB26** [comment] 2019-07-16 13:23
Same issue. Not working on my physical device or emulator, not even on Pie emulators

**Comment by PoojaB26** [comment] 2019-07-16 13:48
Downgraded to v1.8.1, and it worked!

**Comment by lanrehnics** [comment] 2019-07-16 13:50
> Downgraded to v1.8.1, and it worked!
> 
> But I get a long list of these errors/warnings every second
> `Failed to send request: {"jsonrpc":"2.0","id":"3144","method":"getVM","params":{}}`

How do I downgrade .. I really need to

**Comment by PoojaB26** [comment] 2019-07-16 13:51
> > Downgraded to v1.8.1, and it worked!
> > But I get a long list of these errors/warnings every second
> > `Failed to send request: {"jsonrpc":"2.0","id":"3144","method":"getVM","params":{}}`
> 
> How do I downgrade .. I really need to

`git checkout v1.8.1`

And then `flutter doctor`

**Comment by devoncarew** [comment] 2019-07-16 14:56
Thanks for the reports; we have a fix for this in the Flutter IntelliJ plugin, and should have a new release out w/the fix today.

**Comment by lanrehnics** [comment] 2019-07-16 15:02
> Downgraded to v1.8.1, and it worked!
> 
> But I get a long list of these errors/warnings every second
> `Failed to send request: {"jsonrpc":"2.0","id":"3144","method":"getVM","params":{}}`

Just downgraded now getting that long list too.

**Comment by PoojaB26** [comment] 2019-07-16 16:47
Let us know when you have a fix in the plugin! @devoncarew

**Comment by stevemessick** [comment] 2019-07-16 16:48
The Flutter plugin for IntelliJ and Android Studio has been updated to work with Flutter channel master, v1.8.2-pre.46.

**Closed** 2019-07-16 16:48 UTC
Labels: customer: crowd, severe: crash, severe: regression, ▣ platform-android

**Comment by prasant10050** [comment] 2019-07-16 16:51
> The Flutter plugin for IntelliJ and Android Studio has been updated to work with Flutter channel master, v1.8.2-pre.46.

But it's not working now.

**Comment by PoojaB26** [comment] 2019-07-16 17:00
Haven't upgraded Flutter yet, but upgraded Flutter plugin on Android Studio 3.5 Beta and atleast these errors vanished! 

`Failed to send request: {"jsonrpc":"2.0","id":"3144","method":"getVM","params":{}}`

**Comment by prasant10050** [comment] 2019-07-16 17:04
> Still on v1.8.1, but upgraded Flutter plugin on Android Studio 3.5 Beta and atleast these errors vanished!
> 
> `Failed to send request: {"jsonrpc":"2.0","id":"3144","method":"getVM","params":{}}`

why it is always generated, can anybody explain ?

**Comment by devoncarew** [comment] 2019-07-16 17:54
You should only have seen this issue with the previous version of the Flutter IntelliJ and Android Studio plugin when on the flutter master branch. Upgrading your Flutter plugin to `37.1.x` (by checking for updates) should address the issue.

**Comment by lanrehnics** [comment] 2019-07-16 19:12
> Still on v1.8.1, but upgraded Flutter plugin on Android Studio 3.5 Beta and atleast these errors vanished!
> 
> `Failed to send request: {"jsonrpc":"2.0","id":"3144","method":"getVM","params":{}}`

I think you can upgrade now, I just did and everything is fine.

**Comment by raivatshah** [comment] 2019-07-20 17:07
Same issue. Android Studio v3.4.1 with Flutter 35.1.3 on macOS 10.14.5

**Comment by ariedolfin** [comment] 2019-07-22 06:05
did anyone fix this issue ??
i get this issue today...

**Comment by collinjackson** [comment] 2019-07-22 15:40
> did anyone fix this issue ??
> i get this issue today...

Since this was an issue with the flutter-intellij plugin, I would start by updating to the latest version of the plugin. If that is still not working you can file an issue in their issue tracker with details on your IDE setup: https://github.com/flutter/flutter-intellij/issues
