### ISSUE TITLE
TextSpan with backgroundColor obscures cursor

### ISSUE THREAD

**Issue by alexeyinkin** [flutter/flutter#123396] opened 2023-03-24 10:59 UTC
## Steps to Reproduce

1. Create a new Flutter app.
2. Replace `main.dart` with the following.
3. Run the app in Chrome.
4. Put the cursor to the right of the highlighted word.
5. Press left arrow multiple times.

**Expected results:** While on the highlighted word, the cursor is visible on top of the highlighting.

**Actual results:** While on the highlighted word, the cursor is hidden behind the highlighting.

<details>
<summary>main.dart</summary>

```dart
import 'package:flutter/material.dart';

class HighlightingTextEditingController extends TextEditingController {
  HighlightingTextEditingController({
    required this.highlight,
    super.text,
  });

  String highlight;

  @override
  TextSpan buildTextSpan({
    required BuildContext context,
    TextStyle? style,
    required bool withComposing,
  }) {
    final children = <TextSpan>[];
    final matches = RegExp(RegExp.escape(highlight), caseSensitive: false).allMatches(text);
    int position = 0;

    for (final match in matches) {
      children.add(
        TextSpan(
          text: text.substring(position, match.start),
        ),
      );

      children.add(
        TextSpan(
          text: text.substring(match.start, match.end),
          style: _highlightTextStyle,
        ),
      );

      position = match.end;
    }

    children.add(
      TextSpan(
        text: text.substring(position),
      ),
    );

    return TextSpan(
      children: children,
    );
  }
}

final _controller = HighlightingTextEditingController(
  highlight: 'Jack',
  text: '''
All work and no play makes Jack a dull boy.
All play and no work makes Jack a mere toy.
''',
);

const _highlightTextStyle = TextStyle(backgroundColor: Color(0xFFFFFF00));

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(
        appBar: AppBar(title: const Text('Highlighting Text')),
        body: Padding(
          padding: const EdgeInsets.all(20),
          child: TextField(
            controller: _controller,
            maxLines: null,
          ),
        ),
      ),
    );
  }
}
```

</details>

<details>
  <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.7.7, on Ubuntu 20.04.5 LTS 5.14.0-1058-oem, locale en_US.UTF-8)
    • Flutter version 3.7.7 on channel stable at /home/alexey/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2ad6cd72c0 (2 weeks ago), 2023-03-08 09:41:59 -0800
    • Engine revision 1837b5be5f
    • Dart version 2.19.4
    • DevTools version 2.20.1

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /home/alexey/Android/Sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/linux#android-setup for more details.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 2022.1)
    • Android Studio at /home/alexey/bin/android-studio
    • Flutter plugin version 72.1.2
    • Dart plugin version 221.6096
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.75.1)
    • VS Code at /usr/share/code
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 20.04.5 LTS 5.14.0-1058-oem
    • Chrome (web)    • chrome • web-javascript • Google Chrome 110.0.5481.177

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

</details>

https://user-images.githubusercontent.com/44893228/227503546-2444182e-1029-4109-8782-6ecc7f5f7eed.mp4

**Comment by exaby73** [comment] 2023-03-24 14:01
Hello @alexeyinkin. I cannot reproduce this issue with 3.7.8 or master channel. Could you try running on the master channel and confirm?

**Comment by Sarraj-Sahar** [comment] 2023-03-25 15:14
@exaby73 I ran it with master channel and the issue still persists.

**Comment by Sarraj-Sahar** [comment] 2023-03-25 16:30
possible duplicate of [#96112](https://github.com/flutter/flutter/issues/96112) and [#49860](https://github.com/flutter/flutter/issues/49860) but those issues never really got solved...

**Comment by exaby73** [comment] 2023-03-27 06:43
@alexeyinkin Can you confirm if you are hitting https://github.com/flutter/flutter/issues/96112?

**Comment by exaby73** [comment] 2023-03-28 08:38
So I think this is then a duplicate of those issues. Therefore I will close this issue. Please follow up on those issue and upvote the original comment with a thumbs up to raise the priority. Thank you

**Closed by exaby73** 2023-03-28 08:38 UTC
Labels: in triage
