### ISSUE TITLE
[tool_crash] _TypeError: (#0      PlistParser.getValueFromFile (package:flutter_tools/src/ios/plist_parser.dart:178:24))

### ISSUE THREAD

**Issue by tigerbav** [flutter/flutter#151970] opened 2024-07-18 16:24 UTC
When I launch my flutter app via ios simulator, I have the following error

## Command
```
flutter --no-color run --machine --track-widget-creation --device-id=BE475BFE-A6C9-43BB-935C-B77AF63C2358 --start-paused --dart-define=flutter.inspector.structuredErrors=true lib/main.dart
```

## Logs
_TypeError: (#0      PlistParser.getValueFromFile (package:flutter_tools/src/ios/plist_parser.dart:178:24))
```
#0      PlistParser.getValueFromFile (package:flutter_tools/src/ios/plist_parser.dart:178:24)
#1      IosProject._parseProductBundleIdentifier (package:flutter_tools/src/xcode_project.dart:291:41)
#2      IosProject._productBundleIdentifierWithBuildContext (package:flutter_tools/src/xcode_project.dart:278:60)
#3      IosProject.productBundleIdentifier (package:flutter_tools/src/xcode_project.dart:268:12)
<asynchronous suspension>
#4      BuildableIOSApp.fromProject (package:flutter_tools/src/ios/application_package.dart:117:37)
<asynchronous suspension>
#5      FlutterApplicationPackageFactory.getPackageForPlatform (package:flutter_tools/src/flutter_application_package.dart:82:15)
<asynchronous suspension>
#6      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:440:15)
<asynchronous suspension>
#7      HotRunner.run.<anonymous closure> (package:flutter_tools/src/run_hot.dart:432:14)
<asynchronous suspension>
#8      Future.wait.<anonymous closure> (dart:async/future.dart:518:21)
<asynchronous suspension>
#9      HotRunner.run (package:flutter_tools/src/run_hot.dart:463:34)
<asynchronous suspension>
#10     AppDomain.launch.<anonymous closure> (package:flutter_tools/src/commands/daemon.dart:801:9)
<asynchronous suspension>
#11     AppDomain.launch (package:flutter_tools/src/commands/daemon.dart:799:5)
<asynchronous suspension>
#12     RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:709:15)
<asynchronous suspension>
#13     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1389:27)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 3.19.6, on macOS 14.2 23C64 darwin-arm64, locale en-UA)
    • Flutter version 3.19.6 on channel stable at /Users/tigerbav/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 54e66469a9 (3 months ago), 2024-04-17 13:08:03 -0700
    • Engine revision c4cd48e186
    • Dart version 3.3.4
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/tigerbav/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/tigerbav/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/tigerbav/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] Connected device (3 available)
    • iPad mini (6th generation) (mobile) • BE475BFE-A6C9-43BB-935C-B77AF63C2358 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-2 (simulator)
    • macOS (desktop)                     • macos                                • darwin-arm64   • macOS 14.2 23C64 darwin-arm64
    • Chrome (web)                        • chrome                               • web-javascript • Google Chrome 126.0.6478.128

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 3.0.1+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 2e9cb0aa71a386a91f73f7088d115c0d96654829
### Plugins
file_selector_linux-0.9.2+1
file_selector_macos-0.9.3+3
file_selector_windows-0.9.3+1
firebase_auth-5.1.2
firebase_auth_web-5.12.4
firebase_core-3.2.0
firebase_core_web-2.17.3
flutter_email_sender-6.0.3
flutter_plugin_android_lifecycle-2.0.19
flutter_vibrate-1.3.0
fluttertoast-8.2.5
google_mobile_ads-5.0.0
google_sign_in-6.2.1
google_sign_in_android-6.1.23
google_sign_in_ios-5.7.6
google_sign_in_web-0.12.4+1
image_picker-1.1.1
image_picker_android-0.8.11
image_picker_for_web-3.0.4
image_picker_ios-0.8.10+1
image_picker_linux-0.2.1+1
image_picker_macos-0.2.1+1
image_picker_windows-0.2.1+1
isar_flutter_libs-3.1.0+1
path_provider-2.1.3
path_provider_android-2.2.4
path_provider_foundation-2.3.2
path_provider_linux-2.2.1
path_provider_windows-2.2.1
shared_preferences-2.2.3
shared_preferences_android-2.2.2
shared_preferences_foundation-2.3.5
shared_preferences_linux-2.3.2
shared_preferences_web-2.3.0
shared_preferences_windows-2.3.2
sqflite-2.3.3
webview_flutter-4.7.0
webview_flutter_android-3.16.1
webview_flutter_wkwebview-3.13.0

**Comment by darshankawar** [comment] 2024-07-19 07:18
Closing as duplicate of https://github.com/flutter/flutter/issues/138465

**Closed by darshankawar** 2024-07-19 07:18 UTC
Labels: in triage
