### ISSUE TITLE
Google Maps - can we avoid reloading Google Maps throughout Flutter app, eg when switching screens that both contain the map?

### ISSUE THREAD

**Issue by giorgio79** [flutter/flutter#64080] opened 2020-08-18 19:50 UTC
Would there be a way to avoid reloading Google Maps throughout my Flutter app? https://pub.dev/packages/google_maps_flutter

## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by darshankawar** [comment] 2020-08-19 08:10
Hi @giorgio79,
Can you please elaborate on the issue ? Does it reload / refresh map while navigating from one screen to another ?
Can you also provide `flutter doctor -v` and a minimal complete code sample that shows the issue.
Thanks.

**Comment by giorgio79** [comment] 2020-08-19 13:01
Sure, you can see the same map reloads on the next route... Should be super smooth and fast.

`import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

void main() {
  runApp(MaterialApp(
    title: 'Navigation Basics',
    home: FirstRoute(),
  ));
}

class FirstRoute extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('First Route'),
      ),
      body: Stack(
        children: [
          GoogleMap(
            initialCameraPosition:
                CameraPosition(target: LatLng(47.502941, 18.999161), zoom: 1),
            myLocationEnabled: true,
            zoomControlsEnabled: true,
          ),
          Center(
            child: RaisedButton(
              child: Text('Open route'),
              onPressed: () {
                Navigator.push(
                  context,
                  MaterialPageRoute(builder: (context) => SecondRoute()),
                );
              },
            ),
          ),
        ],
      ),
    );
  }
}

class SecondRoute extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Second Route"),
      ),
      body: Stack(
        children: [
          GoogleMap(
            initialCameraPosition:
                CameraPosition(target: LatLng(47.502941, 18.999161), zoom: 1),
            myLocationEnabled: true,
            zoomControlsEnabled: true,
          ),
          Center(
            child: RaisedButton(
              onPressed: () {
                Navigator.pop(context);
              },
              child: Text('Go back!'),
            ),
          ),
        ],
      ),
    );
  }
}
`

**Comment by darshankawar** [comment] 2020-08-21 04:52
@giorgio79 Thanks for the code sample.
I see the map refreshing upon route navigation.

[64080.mp4.zip](https://github.com/flutter/flutter/files/5106846/64080.mp4.zip)

<details>
<summary>flutter doctor -v</summary>

```
Flutter 1.20.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision bbfbf1770c (15 hours ago) • 2020-08-13 08:33:09 -0700
Engine • revision 9d5b21729f
Tools • Dart 2.9.1

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.20.2, on Mac OS X 10.15.2 19C57, locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions.
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
[✓] Android Studio (version 3.6)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.

```

</details>

**Comment by gushendra86** [comment] 2020-12-09 07:26
Hello,

Do find any solution with this ? I am searching for this too but not get the answer. I need to use the same maps widget when go to the next page.

Thank you and regards,

Hendra

**Comment by pedromassangocode** [comment] 2021-04-28 13:44
I was able to reproduce this however this is a duplicate of https://github.com/flutter/flutter/issues/39797. The issue here is that GoogleMaps take time to load and thus the black screen.


![gif](https://user-images.githubusercontent.com/67424416/116412251-674d1900-a82e-11eb-915b-1e4f33692e8c.gif)

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel master, 2.3.0-1.0.pre.143, on macOS 11.2.3 20D91 darwin-x64, locale en-AO)
    • Flutter version 2.3.0-1.0.pre.143 at /Users/pedromassango/Code/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision aecd5e0302 (3 hours ago), 2021-04-28 00:53:57 -0300
    • Engine revision 92ef7b59c8
    • Dart version 2.14.0 (build 2.14.0-48.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/pedromassango/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2021.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 55.1.5
    • Dart plugin version 211.7179

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.2.3 20D91 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 90.0.4430.93

! Doctor found issues in 1 category.
```

</details>

**Closed by pedromassangocode** 2021-04-28 13:44 UTC
Labels: found in release: 1.20, has reproducible steps, p: first party, p: maps, plugin

**Comment by nehamdr225** [comment] 2021-04-29 09:33
Hi I came here from #39797 is there a solution? Both this and #39797 have been closed. I need to remove this problem for my production release. Please let me know if there is anything that can be done in my part, I don't see this issue in IOS simulators.

**Comment by pedromassangocode** [comment] 2021-04-29 12:45
https://github.com/flutter/flutter/issues/39797 is opened. Please follow up there

**Comment by VictorHacks** [comment] 2021-04-30 11:34
Same problem, please help!
