### ISSUE TITLE
Options for customizing auto-generated ios/android folder

### ISSUE THREAD

**Issue by IchordeDionysos** [flutter/flutter#37689] opened 2019-08-06 12:50 UTC
## Use case

I have frequently run into #32883 where I have to constantly edit my .ios/.android folder to update the minimal ios version or add the google-services.json/GoogleService-Info.plist back in again or to convert the project to AndroidX again.

Doing these repetitive and simple changes over and over again is time-consuming and makes me again as productive as writing native iOS/Android code.

## Proposal

So for the minimally targeted OS version, an option in the pubspec.yaml would be great, like:

```yaml
flutter:
    min-os-version:
        androidMinSdkVersion: 16
        iosMinimumDeploymentTarget: 9.0
```

For adding files like google-services.json/GoogleService-Info.plist it would be great if there was some way of running post-creation scripts which are capable of copying these files to the .ios/.android folder. 
(Something like in the Firebase CLI https://firebase.google.com/docs/cli#hooks)

```yaml
flutter:
    post-creation-script:
        android: 
        - ./post-creation-android.sh
        ios: 
        - ./post-creation-ios.sh
```

And the most important: 
There should be an option:

```yaml
flutter:
    use-android-x: true
```

**Comment by blasten** [comment] 2019-08-06 16:34
This is related to https://github.com/flutter/flutter/issues/32989  cc @xster

**Comment by blasten** [comment] 2019-08-06 16:37
I'm inclined to think that instead of exposing these properties through `pubspec.yaml`, we might just want to make `flutter make-host-app-editable` the default, and allow folks to custom these parameters in their corresponding ios/android directories.

**Comment by IchordeDionysos** [comment] 2019-08-07 20:57
Oh @blasten, I wasn't aware of the command `flutter make-host-app-editable`.
So would that mean I could modify all of these things without them being changed over and over again when I run this command and make the desired changes in the `android`/`ios` directories?

**Comment by blasten** [comment] 2019-08-08 00:47
Yup, that is correct.

**Comment by blasten** [comment] 2019-08-08 00:47
Duplicate of https://github.com/flutter/flutter/issues/32989

**Closed by blasten** 2019-08-08 00:47 UTC
Labels: a: existing-apps
