### ISSUE TITLE
[IOS] Crashes in production on flutter 3.7.9

### ISSUE THREAD

**Issue by kutian** [flutter/flutter#129541] opened 2023-06-26 07:29 UTC
Hello:
We recently collated the crash information received from users and confirmed that the following four kinds of crashes were encountered using flutter version 3.7.9. We do not know the exact actions to reproduce the issue, only have the stack information at the time of crash. The crashes are listed below in order of the number of occurrences (from high to low), phone models and system versions are attached:

1. OS Version:      iPhone OS 14.1 (18A8395)
    Report Version:  104

    Exception Type:  SIGABRT
    Exception Codes: #0 at 0x1adeb898c
    Crashed Thread:  22

```
Thread 22 Crashed:
0   libsystem_kernel.dylib              0x00000001adeb898c __pthread_kill + 8
1   libsystem_c.dylib                   0x000000018ae8ebb4 abort + 104
2   Flutter                             0x000000010fa75ab4 _ZN3fml10LogMessageD1Ev + 0
3   Flutter                             0x000000010fa75c20 _ZN3fml11FileMapping14CreateReadOnlyERKNS_12UniqueObjectIiNS_8internal7os_unix14UniqueFDTraitsEEERKNSt21_LIBCPP_ABI_NAMESPACE12basic_stringIcNS8_11char_traitsIcEENS8_9allocatorIcEEEE + 0
4   Flutter                             0x000000010fa79db0 _ZN3fml8internal18ThreadLocalPointer4swapEPv + 184
5   Flutter                             0x000000010fa77158 _ZN3fml15MessageLoopImpl10FlushTasksENS_9FlushTypeE + 1716
6   Flutter                             0x000000010fa79e80 _ZN3fml17MessageLoopDarwin11OnTimerFireEP16__CFRunLoopTimerPS0_ + 32
7   CoreFoundation                      0x0000000181cd4050 <redacted> + 32
8   CoreFoundation                      0x0000000181cd3c50 <redacted> + 1064
9   CoreFoundation                      0x0000000181cd30c4 <redacted> + 328
10  CoreFoundation                      0x0000000181ccd178 <redacted> + 1936
11  CoreFoundation                      0x0000000181ccc4bc CFRunLoopRunSpecific + 600
12  Flutter                             0x000000010fa79f6c _ZN3fml17MessageLoopDarwin3RunEv + 88
13  Flutter                             0x000000010fa79a5c _ZNSt21_LIBCPP_ABI_NAMESPACE14__thread_proxyB6v15000INS_5tupleIJNS_10unique_ptrINS_15__thread_structENS_14default_deleteIS3_EEEEZN3fml6ThreadC1ERKNS_8functionIFvRKNS8_12ThreadConfigEEEESC_E3$_0EEEEEPvSJ_ + 208
14  libsystem_pthread.dylib             0x00000001c9c45ca8 _pthread_start + 320
15  libsystem_pthread.dylib             0x00000001c9c4e788 thread_start + 8
```

2. OS Version:      iPhone OS 14.6 (18F72)
    Report Version:  104

    Exception Type:  SIGSEGV
    Exception Codes: SEGV_ACCERR at 0xbf8
    Crashed Thread:  23
```
Thread 23 Crashed:
0   Flutter                             0x0000000110085e7c _ZN7flutter12_GLOBAL__N_124ResolveFfiNativeFunctionEPKcm + 128
1   Flutter                             0x00000001101aa938 _ZN4dartL10FfiResolveEP12_Dart_HandleS1_m + 316
2   App                                 0x000000010e9d5a98 kDartVmSnapshotInstructions + 4440
3   App                                 0x000000010e9f7204 kDartIsolateSnapshotInstructions + 119108
4   App                                 0x000000010f3c5ae8 kDartIsolateSnapshotInstructions + 10402344
5   App                                 0x000000010f3bb21c kDartIsolateSnapshotInstructions + 10359132
6   App                                 0x000000010f3c5a5c kDartIsolateSnapshotInstructions + 10402204
7   App                                 0x000000010f3c5a10 kDartIsolateSnapshotInstructions + 10402128
8   App                                 0x000000010f011930 kDartIsolateSnapshotInstructions + 6518896
9   App                                 0x000000010f3c5810 kDartIsolateSnapshotInstructions + 10401616
10  App                                 0x000000010f3c56c4 kDartIsolateSnapshotInstructions + 10401284
11  App                                 0x000000010e9e4eec kDartIsolateSnapshotInstructions + 44588
12  App                                 0x000000010e9e4d70 kDartIsolateSnapshotInstructions + 44208
13  App                                 0x000000010e9e36c8 kDartIsolateSnapshotInstructions + 38408
14  App                                 0x000000010e9dee9c kDartIsolateSnapshotInstructions + 19932
15  App                                 0x000000010e9e3004 kDartIsolateSnapshotInstructions + 36676
16  App                                 0x000000010e9e4eec kDartIsolateSnapshotInstructions + 44588
17  App                                 0x000000010e9e4d70 kDartIsolateSnapshotInstructions + 44208
18  App                                 0x000000010e9e36c8 kDartIsolateSnapshotInstructions + 38408
19  App                                 0x000000010e9dee9c kDartIsolateSnapshotInstructions + 19932
20  App                                 0x000000010f3bf6ec kDartIsolateSnapshotInstructions + 10376748
21  App                                 0x000000010ea12200 kDartIsolateSnapshotInstructions + 229696
22  App                                 0x000000010f3bf11c kDartIsolateSnapshotInstructions + 10375260
23  App                                 0x000000010e9e4eec kDartIsolateSnapshotInstructions + 44588
24  App                                 0x000000010e9e4d70 kDartIsolateSnapshotInstructions + 44208
25  App                                 0x000000010e9e36c8 kDartIsolateSnapshotInstructions + 38408
26  App                                 0x000000010e9dee9c kDartIsolateSnapshotInstructions + 19932
27  App                                 0x000000010e9dee04 kDartIsolateSnapshotInstructions + 19780
28  App                                 0x000000010e9de6a8 kDartIsolateSnapshotInstructions + 17896
29  App                                 0x000000010e9de594 kDartIsolateSnapshotInstructions + 17620
30  App                                 0x000000010e9de558 kDartIsolateSnapshotInstructions + 17560
31  App                                 0x000000010e9d77fc kDartVmSnapshotInstructions + 11964
32  Flutter                             0x00000001101bfcb4 _ZN4dart9DartEntry14InvokeFunctionERKNS_8FunctionERKNS_5ArrayES6_m + 392
33  Flutter                             0x00000001102b8d5c Dart_InvokeClosure + 1352
34  Flutter                             0x000000010ffe0004 _ZN5tonic18DartMicrotaskQueue13RunMicrotasksEv + 220
35  Flutter                             0x000000010fecaf80 _ZN3fml15MessageLoopImpl10FlushTasksENS_9FlushTypeE + 1244
36  Flutter                             0x000000010fecde80 _ZN3fml17MessageLoopDarwin11OnTimerFireEP16__CFRunLoopTimerPS0_ + 32
37  CoreFoundation                      0x000000019a64d22c <redacted> + 32
38  CoreFoundation                      0x000000019a64ce28 <redacted> + 1076
39  CoreFoundation                      0x000000019a64c278 <redacted> + 328
40  CoreFoundation                      0x000000019a64602c <redacted> + 1944
41  CoreFoundation                      0x000000019a645360 CFRunLoopRunSpecific + 600
42  Flutter                             0x000000010fecdf6c _ZN3fml17MessageLoopDarwin3RunEv + 88
43  Flutter                             0x000000010fecda5c _ZNSt21_LIBCPP_ABI_NAMESPACE14__thread_proxyB6v15000INS_5tupleIJNS_10unique_ptrINS_15__thread_structENS_14default_deleteIS3_EEEEZN3fml6ThreadC1ERKNS_8functionIFvRKNS8_12ThreadConfigEEEESC_E3$_0EEEEEPvSJ_ + 208
44  libsystem_pthread.dylib             0x00000001e634cbfc _pthread_start + 320
45  libsystem_pthread.dylib             0x00000001e6355758 thread_start + 8
```

3. OS Version:      iPhone OS 16.5 (20F66)
    Report Version:  104

    Exception Type:  SIGSEGV
    Exception Codes: SEGV_ACCERR at 0x0
    Crashed Thread:  15
```
Thread 15 Crashed:
0   Flutter                             0x00000001118c6978 +[FlutterDarwinContextMetalSkia createGrContext:commandQueue:] + 4437932
1   App                                 0x000000011025f498 kDartIsolateSnapshotInstructions + 332760
2   App                                 0x000000011025f364 kDartIsolateSnapshotInstructions + 332452
3   App                                 0x000000011047bbd8 kDartIsolateSnapshotInstructions + 2546456
4   App                                 0x00000001104fea54 kDartIsolateSnapshotInstructions + 3082644
5   App                                 0x00000001104fe3d8 kDartIsolateSnapshotInstructions + 3080984
6   App                                 0x0000000110470c44 kDartIsolateSnapshotInstructions + 2501508
7   App                                 0x00000001104fea54 kDartIsolateSnapshotInstructions + 3082644
8   App                                 0x00000001104fe3d8 kDartIsolateSnapshotInstructions + 3080984
9   App                                 0x0000000110470c44 kDartIsolateSnapshotInstructions + 2501508
10  App                                 0x0000000110470930 kDartIsolateSnapshotInstructions + 2500720
11  App                                 0x00000001104fea54 kDartIsolateSnapshotInstructions + 3082644
12  App                                 0x00000001104fe3d8 kDartIsolateSnapshotInstructions + 3080984
13  App                                 0x0000000110470c44 kDartIsolateSnapshotInstructions + 2501508
14  App                                 0x00000001104fea54 kDartIsolateSnapshotInstructions + 3082644
15  App                                 0x00000001104fe3d8 kDartIsolateSnapshotInstructions + 3080984
16  App                                 0x0000000110470c44 kDartIsolateSnapshotInstructions + 2501508
17  App                                 0x00000001104fea54 kDartIsolateSnapshotInstructions + 3082644
18  App                                 0x00000001104fe3d8 kDartIsolateSnapshotInstructions + 3080984
19  App                                 0x0000000110470c44 kDartIsolateSnapshotInstructions + 2501508
20  App                                 0x00000001104fea54 kDartIsolateSnapshotInstructions + 3082644
21  App                                 0x00000001104fe3d8 kDartIsolateSnapshotInstructions + 3080984
22  App                                 0x0000000110470c44 kDartIsolateSnapshotInstructions + 2501508
23  App                                 0x00000001104fea54 kDartIsolateSnapshotInstructions + 3082644
24  App                                 0x00000001104fe3d8 kDartIsolateSnapshotInstructions + 3080984
25  App                                 0x0000000110470c44 kDartIsolateSnapshotInstructions + 2501508
26  App                                 0x00000001104fea54 kDartIsolateSnapshotInstructions + 3082644
27  App                                 0x00000001104fe3d8 kDartIsolateSnapshotInstructions + 3080984
28  App                                 0x0000000110470c44 kDartIsolateSnapshotInstructions + 2501508
29  App                                 0x00000001104fea54 kDartIsolateSnapshotInstructions + 3082644
30  App                                 0x00000001104fe3d8 kDartIsolateSnapshotInstructions + 3080984
31  App                                 0x00000001104fe000 kDartIsolateSnapshotInstructions + 3080000
32  App                                 0x0000000110470c44 kDartIsolateSnapshotInstructions + 2501508
33  App                                 0x00000001104fea54 kDartIsolateSnapshotInstructions + 3082644
34  App                                 0x00000001104fe3d8 kDartIsolateSnapshotInstructions + 3080984
35  App                                 0x000000011047a9ac kDartIsolateSnapshotInstructions + 2541804
36  App                                 0x000000011047974c kDartIsolateSnapshotInstructions + 2537100
37  App                                 0x0000000110476994 kDartIsolateSnapshotInstructions + 2525396
38  App                                 0x00000001104fea54 kDartIsolateSnapshotInstructions + 3082644
39  App                                 0x00000001104fe3d8 kDartIsolateSnapshotInstructions + 3080984
40  App                                 0x0000000110470c44 kDartIsolateSnapshotInstructions + 2501508
41  App                                 0x00000001104fea54 kDartIsolateSnapshotInstructions + 3082644
42  App                                 0x00000001104fe3d8 kDartIsolateSnapshotInstructions + 3080984
43  App                                 0x0000000110470c44 kDartIsolateSnapshotInstructions + 2501508
44  App                                 0x00000001104fea54 kDartIsolateSnapshotInstructions + 3082644
45  App                                 0x00000001104fe3d8 kDartIsolateSnapshotInstructions + 3080984
46  App                                 0x0000000110470c44 kDartIsolateSnapshotInstructions + 2501508
47  App                                 0x00000001104fea54 kDartIsolateSnapshotInstructions + 3082644
48  App                                 0x00000001104fe3d8 kDartIsolateSnapshotInstructions + 3080984
49  App                                 0x0000000110470c44 kDartIsolateSnapshotInstructions + 2501508
50  App                                 0x00000001104fea54 kDartIsolateSnapshotInstructions + 3082644
51  App                                 0x00000001104fe3d8 kDartIsolateSnapshotInstructions + 3080984
52  App                                 0x00000001104fe000 kDartIsolateSnapshotInstructions + 3080000
53  App                                 0x0000000110470c44 kDartIsolateSnapshotInstructions + 2501508
54  App                                 0x00000001104fea54 kDartIsolateSnapshotInstructions + 3082644
55  App                                 0x00000001104fe3d8 kDartIsolateSnapshotInstructions + 3080984
56  App                                 0x0000000110472e94 kDartIsolateSnapshotInstructions + 2510292
57  App                                 0x00000001104fea54 kDartIsolateSnapshotInstructions + 3082644
58  App                                 0x00000001104fe3d8 kDartIsolateSnapshotInstructions + 3080984
59  App                                 0x000000011044fbe0 kDartIsolateSnapshotInstructions + 2366240
60  App                                 0x000000011044fb7c kDartIsolateSnapshotInstructions + 2366140
61  App                                 0x0000000110452548 kDartIsolateSnapshotInstructions + 2376840
62  App                                 0x000000011047c9c4 kDartIsolateSnapshotInstructions + 2550020
63  App                                 0x0000000110b2222c kDartIsolateSnapshotInstructions + 9519468
64  App                                 0x0000000110b22178 kDartIsolateSnapshotInstructions + 9519288
65  App                                 0x0000000110b1a68c kDartIsolateSnapshotInstructions + 9487820
66  App                                 0x0000000110b1a118 kDartIsolateSnapshotInstructions + 9486424
67  App                                 0x0000000110b19a68 kDartIsolateSnapshotInstructions + 9484712
68  App                                 0x0000000110b19a30 kDartIsolateSnapshotInstructions + 9484656
69  App                                 0x00000001102a456c kDartIsolateSnapshotInstructions + 615596
70  App                                 0x00000001102a44c0 kDartIsolateSnapshotInstructions + 615424
71  App                                 0x00000001102a4220 kDartIsolateSnapshotInstructions + 614752
72  App                                 0x00000001102a40f0 kDartIsolateSnapshotInstructions + 614448
73  App                                 0x0000000110219520 kDartIsolateSnapshotInstructions + 46176
74  App                                 0x0000000110219614 kDartIsolateSnapshotInstructions + 46420
75  App                                 0x0000000110ad4a74 kDartIsolateSnapshotInstructions + 9202100
76  App                                 0x0000000110ad7324 kDartIsolateSnapshotInstructions + 9212516
77  App                                 0x000000011022b940 kDartIsolateSnapshotInstructions + 120960
78  App                                 0x000000011022b884 kDartIsolateSnapshotInstructions + 120772
79  App                                 0x000000011022b840 kDartIsolateSnapshotInstructions + 120704
80  App                                 0x000000011022b974 kDartIsolateSnapshotInstructions + 121012
81  App                                 0x000000011020b7fc kDartVmSnapshotInstructions + 11964
82  Flutter                             0x00000001119f3cb4 +[FlutterStandardMessageCodec codecWithReaderWriter:] + 235512
83  Flutter                             0x0000000111aecd5c +[FlutterStandardMessageCodec codecWithReaderWriter:] + 1255584
84  Flutter                             0x00000001118022e8 +[FlutterDarwinContextMetalSkia createGrContext:commandQueue:] + 3633436
85  Flutter                             0x00000001117e93d4 +[FlutterDarwinContextMetalSkia createGrContext:commandQueue:] + 3531272
86  Flutter                             0x00000001118120fc +[FlutterDarwinContextMetalSkia createGrContext:commandQueue:] + 3698480
87  Flutter                             0x00000001116fecdc +[FlutterDarwinContextMetalSkia createGrContext:commandQueue:] + 2571024
88  Flutter                             0x0000000111701e80 +[FlutterDarwinContextMetalSkia createGrContext:commandQueue:] + 2583732
89  CoreFoundation                      0x000000019b0b9c1c 0x19aff8000 + 793628
90  CoreFoundation                      0x000000019b07ae64 0x19aff8000 + 536164
91  CoreFoundation                      0x000000019b02417c 0x19aff8000 + 180604
92  CoreFoundation                      0x000000019b06d63c 0x19aff8000 + 480828
93  CoreFoundation                      0x000000019b071da0 0x19aff8000 + 499104
94  Flutter                             0x0000000111701f6c +[FlutterDarwinContextMetalSkia createGrContext:commandQueue:] + 2583968
95  Flutter                             0x0000000111701a5c +[FlutterDarwinContextMetalSkia createGrContext:commandQueue:] + 2582672
96  libsystem_pthread.dylib             0x00000001e4ef10ec 0x1e4eee000 + 12524
97  libsystem_pthread.dylib             0x00000001e4eef72c 0x1e4eee000 + 5932
```

4. OS Version:      iPhone OS 16.5.1 (20F75)
    Report Version:  104

    Exception Type:  SIGABRT
    Exception Codes: #0 at 0x1e3d6b558
    Crashed Thread:  0

Application Specific Information:
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: '<FlutterTextInputView: 0x140a77090; frame = (0 0; 0 0); text = 'guo chan hua'; tintColor = UIExtendedGrayColorSpace 0 0; gestureRecognizers = <NSArray: 0x281a6a760>; layer = <CALayer: 0x28110aa80>> is not a descendant of <FlutterView: 0x16a5e4290; frame = (inf inf; 0 0); autoresize = W+H; gestureRecognizers = <NSArray: 0x2819b0ba0>; backgroundColor = UIExtendedGrayColorSpace 0 0; layer = <CAMetalLayer: 0x281ac55c0>>'

```
Last Exception Backtrace:
0   CoreFoundation                      0x00000001a5730cb4 <redacted> + 164
1   libobjc.A.dylib                     0x000000019e84c3d0 objc_exception_throw + 60
2   Foundation                          0x000000019ff4256c <redacted> + 0
3   Flutter                             0x0000000116282d5c -[FlutterTextInputView firstRectForRange:] + 1424
4   UIKitCore                           0x00000001a84075a8 <redacted> + 356
5   UIKitCore                           0x00000001a835aa70 <redacted> + 468
6   UIKitCore                           0x00000001a7b4ff10 <redacted> + 276
7   UIKitCore                           0x00000001a7b4e750 <redacted> + 132
8   UIKitCore                           0x00000001a8355ad0 <redacted> + 2148
9   UIKitCore                           0x00000001a83561d0 <redacted> + 72
10  UIKitCore                           0x00000001a7b639ac <redacted> + 208
11  UIKitCore                           0x00000001a7b63890 <redacted> + 304
12  UIKitCore                           0x00000001a837d9e0 <redacted> + 96
13  UIKitCore                           0x00000001a7c9bb64 <redacted> + 96
14  UIKitCore                           0x00000001a8356134 <redacted> + 180
15  UIKitCore                           0x00000001a8352d6c <redacted> + 736
16  UIKitCore                           0x00000001a83525fc <redacted> + 296
17  UIKitCore                           0x00000001a8335d50 <redacted> + 2676
18  UIKitCore                           0x00000001a807f184 <redacted> + 1808
19  UIKitCore                           0x00000001a807ea34 <redacted> + 88
20  UIKitCore                           0x00000001a84fff20 <redacted> + 328
21  UIKitCore                           0x00000001a79b099c <redacted> + 348
22  Flutter                             0x0000000116280e54 -[FlutterTextInputView resignFirstResponder] + 48
23  Flutter                             0x00000001162861f8 -[FlutterTextInputPlugin hideTextInput] + 64
24  Flutter                             0x00000001162859bc -[FlutterTextInputPlugin handleMethodCall:result:] + 372
25  Flutter                             0x00000001167ea324 __45-[FlutterMethodChannel setMethodCallHandler:]_block_invoke + 112
26  Flutter                             0x000000011629f858 ___ZN7flutter25PlatformMessageHandlerIos21HandlePlatformMessageENSt21_LIBCPP_ABI_NAMESPACE10unique_ptrINS_15PlatformMessageENS1_14default_deleteIS3_EEEE_block_invoke + 116
27  libdispatch.dylib                   0x00000001acbf1320 <redacted> + 32
28  libdispatch.dylib                   0x00000001acbf2eac <redacted> + 20
29  libdispatch.dylib                   0x00000001acc016a4 <redacted> + 928
30  libdispatch.dylib                   0x00000001acc012f4 _dispatch_main_queue_callback_4CF + 44
31  CoreFoundation                      0x00000001a57bfc28 <redacted> + 16
32  CoreFoundation                      0x00000001a57a1560 <redacted> + 1992
33  CoreFoundation                      0x00000001a57a63ec CFRunLoopRunSpecific + 612
34  GraphicsServices                    0x00000001e033b35c GSEventRunModal + 164
35  UIKitCore                           0x00000001a7b336e8 <redacted> + 888
36  UIKitCore                           0x00000001a7b3334c UIApplicationMain + 340
37  Lanxin                              0x0000000105848278 main (in Lanxin) (main.m:41)[∑]
38  ???                                 0x00000001c4c6edec 0x0 + 0
```
Currently we do not intend to upgrade the latest version of flutter, please confirm whether you can avoid the crash in flutter version 3.7.9.

**Comment by danagbemava-nc** [comment] 2023-06-26 14:06
Hi @kutian, please file separate issues for each crash so they're easy to track. 

Please also check for duplicates before you file the issues, there's a chance some of these may have been filed before. 

Thank you

**Comment by kutian** [comment] 2023-06-27 01:50
OK

**Comment by danagbemava-nc** [comment] 2023-06-27 06:18
Kindly update here after you have filed the new issues. 

Thank you

**Comment by kutian** [comment] 2023-06-27 07:55
[https://github.com/flutter/flutter/issues/129613](https://github.com/flutter/flutter/issues/129613)
[https://github.com/flutter/flutter/issues/129614](https://github.com/flutter/flutter/issues/129614)
[https://github.com/flutter/flutter/issues/129615](https://github.com/flutter/flutter/issues/129615)
[https://github.com/flutter/flutter/issues/129616](https://github.com/flutter/flutter/issues/129616)

**Comment by danagbemava-nc** [comment] 2023-06-28 07:20
@flutter-symbolizer-bot https://github.com/flutter/flutter/issues/129541#issue-1774123455 flutter#v3.7.9

**Comment by danagbemava-nc** [comment] 2023-06-28 07:22
@flutter-symbolizer-bot https://github.com/flutter/flutter/issues/129541#issue-1774123455 flutter#v3.7.9 force ios release

**Comment by danagbemava-nc** [comment] 2023-06-28 07:27
@flutter-symbolizer-bot https://github.com/flutter/flutter/issues/129541#issue-1774123455 flutter#v3.7.9 force ios release arm64

**Comment by danagbemava-nc** [comment] 2023-06-29 06:39
The stack traces shared could not be completely symbolized by the bot. From the stack traces shared above, there seems to be an issue related to text input (4, in the original post).  Some of the stack traces look like it could be the same, just at different points because they're on different versions of iOS. 

Labeling for further insight from the team based on the symbolized logs and the stack traces shared above.

**Comment by chinmaygarde** [comment] 2023-07-05 18:10
The symbolicated traces don't make sense and are likely garbled and pointing to random methods. We need a reproducible test case. Preferably for each. Or a non-garbled stack trace. Closing as inactionable.

**Closed by chinmaygarde** 2023-07-05 18:10 UTC
Labels: platform-ios, engine, a: production, severe: fatal crash
