### ISSUE TITLE
Can't run demo on VS Code

### ISSUE THREAD

**Issue by superjoo** [flutter/flutter#21971] opened 2018-09-18 06:41 UTC
<img width="1081" alt="screen" src="https://user-images.githubusercontent.com/1567417/45668890-e515f780-bb50-11e8-85c1-e24eaf9ee39d.png">

After added "text" param to Center Widget, it also built failed.
```
compiler message: file:///Users/superjoo/flutterEvn/flutter/packages/flutter/lib/src/widgets/basic.dart:1544:9: Error: Found this candidate, but the arguments don't match.
compiler message:   const Center(Text text, { Key key, double widthFactor, double heightFactor, Widget child })
compiler message:         ^
compiler message: file:///Users/superjoo/flutterEvn/flutter/packages/flutter/lib/src/cupertino/dialog.dart:278:22: Error: Too few positional arguments: 1 required, 0 given.
compiler message:     return new Center(
compiler message:                      ^^...
compiler message: file:///Users/superjoo/flutterEvn/flutter/packages/flutter/lib/src/widgets/basic.dart:1544:9: Error: Found this candidate, but the arguments don't match.
compiler message:   const Center(Text text, { Key key, double widthFactor, double heightFactor, Widget child })
compiler message:         ^
compiler message: file:///Users/superjoo/flutterEvn/flutter/packages/flutter/lib/src/cupertino/segmented_control.dart:351:32: Error: Too few positional arguments: 1 required, 0 given.
compiler message:       Widget child = new Center(
compiler message:                                ^^...
compiler message: file:///Users/superjoo/flutterEvn/flutter/packages/flutter/lib/src/widgets/basic.dart:1544:9: Error: Found this candidate, but the arguments don't match.
compiler message:   const Center(Text text, { Key key, double widthFactor, double heightFactor, Widget child })
compiler message:         ^
Compiler failed on /Users/superjoo/flutterProject/he/lib/main.dart
Error launching application on iPhone 8.
Exited (sigterm)
```

<img width="669" alt="0011" src="https://user-images.githubusercontent.com/1567417/45674829-7b054e80-bb60-11e8-9930-cea46c6658d2.png">

**Comment by superjoo** [comment] 2018-09-18 06:54
<img width="1439" alt="123" src="https://user-images.githubusercontent.com/1567417/45669465-c6b0fb80-bb52-11e8-831f-ed1e95348c09.png">

**Comment by C-Alexander** [comment] 2018-09-18 08:08
As the comments near it say, a Center widget takes only 1 child. If you want to add text, you can add that to column, replace column, or wrap column (and text) in another widget that can take more than 1 child. 

Check https://flutter.io/widgets/ for most common use cases :)

**Comment by C-Alexander** [comment] 2018-09-18 08:27
Could you run flutter doctor -v in the terminal/cmd and add the results to your first post? It might also be helpful to add the full file to a gist and link that.

**Comment by superjoo** [comment] 2018-09-18 08:33
Updated first psot.

**Comment by C-Alexander** [comment] 2018-09-18 08:57
Could you show the full widget? Are you importing a custom center or such?

**Comment by superjoo** [comment] 2018-09-19 01:50
It's just a demo project auto created by VS Code. After replaced the flutter SDK from 0.7.3 to 0.6.0. The project running exactly now. So I thank it's the problem of 0.7.3 version.

**Comment by C-Alexander** [comment] 2018-09-19 09:35
Doing exactly what you showed with the FloatingButton on 0.7.3 worked fine for me, additionally the signature the error is giving for your center (Center(Text text, {})) is very strange, there's no Text in center. Hasn't been/wont be to my knowledge either...

Did you try a 
flutter clean 
flutter run
after fixing the center widget?

**Comment by zoechi** [comment] 2018-10-29 11:02
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.

**Closed by zoechi** 2018-10-29 11:02 UTC
Labels: waiting for customer response

**Comment by sedobrengocce** [comment] 2018-11-15 10:09
Hi!
I have the same problem

I just runned "flutter create myAPP"
then cd myAPP
flutter run
and i have this problem

this is my flutter doctor -v 
[✓] Flutter (Channel beta, v0.11.3, on Linux, locale it_IT.UTF-8)
    • Flutter version 0.11.3 at /home/pepj/development/flutter
    • Framework revision 72bf075e8d (5 days ago), 2018-11-09 20:36:17 -0800
    • Engine revision 5646e86a6f
    • Dart version 2.1.0 (build 2.1.0-dev.9.3 9c07fb64c4)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /home/pepj/android
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /home/pepj/android
    • Java binary at: /home/pepj/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] Android Studio (version 3.2)
    • Android Studio at /home/pepj/android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.29.0)
    • VS Code at /usr/share/code
    • Flutter extension version 2.20.0

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

**Comment by zoechi** [comment] 2018-11-15 12:35
@sedobrengocce I think #24279 is the same and still open while this one is closed.

**Comment by sedobrengocce** [comment] 2018-11-16 16:29
I found my problem was caused by flutter clean

I update flutter and it seems solved, but when i launched flutter clean it's came back

**Comment by sedobrengocce** [comment] 2018-11-16 16:58
Solved switching to channel beta from master
