### ISSUE TITLE
The framework tree is open, but the check on PRs is showing that the tree is closed.

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#89376] opened 2021-09-02 15:38 UTC
It looks like there is a problem with this job:

https://ci.chromium.org/p/flutter/builders/prod/Mac%20tool_integration_tests_4_4

Where the most recent run is red, and maybe the re-run has been queueing for a long time, or cocoon isn't picking up the state?

**Comment by yusufm** [comment] 2021-09-02 16:23
@CaseyHillers I think you had done some recent work to consolidate the tree status calculations that were happening differently. Is this related?

**Comment by godofredoc** [comment] 2021-09-02 16:55
This may working as intended depending on the timing(9:10 AM PDT +-10mins). The main reason I updated the tree status calculation to use luci directly was to avoid the latency of updating the datastore when calculating tree status.

Once we are able to process builds results faster the tree status and the dashboard will be consistent.



![image](https://user-images.githubusercontent.com/54371434/131884622-2fbff2ab-d278-4954-ac14-540d06bea137.png)

**Comment by zanderso** [comment] 2021-09-02 17:14
https://ci.chromium.org/p/flutter/builders/prod/Mac%20tool_integration_tests_4_4/1730 failed at 12:32am, and cocoon incorrectly reported the tree as open until https://ci.chromium.org/p/flutter/builders/prod/Mac%20tool_integration_tests_4_4/1731 finished successfully at 9:10am after (I assume) being manually re-run. Luckily, the GitHub presubmit check knew that the tree was red during those 9 hours and didn't land changes on top of a red tree.

**Comment by yusufm** [comment] 2021-09-02 19:38
@zanderso It looks like this particular issue is now resolved, with the tests having run successfully. Can I go ahead and close this or reduce priority?

**Comment by zanderso** [comment] 2021-09-02 19:40
No. At the moment, the framework dashboard is reporting that the tree is open, but PRs are seeing that the tree is closed.

**Comment by zanderso** [comment] 2021-09-02 19:44
To clarify, this is P0 because PRs are blocked, but looking at the dashboard there is no way to understand why so that the gardener can file an issue or take corrective action.

**Comment by zanderso** [comment] 2021-09-02 19:46
For example, the dashboard says the tree is open, and the status of several squares is yellow indicating that jobs are running, but if you click through to this one for example:

https://ci.chromium.org/p/flutter/builders/prod/Mac%20build_tests_2_4

It shows a failure on the most recent run, and no retry jobs are running.

**Comment by chunhtai** [comment] 2021-09-02 21:31
I see a passing build in https://ci.chromium.org/p/flutter/builders/prod/Mac%20build_tests_2_4 just now, maybe it just been queued for a long time?

**Comment by chunhtai** [comment] 2021-09-02 21:44
The pr check is green now, closing this issue

**Comment by zanderso** [comment] 2021-09-02 21:46
What was done to fix the inconsistent status between the dashboard and PRs?

**Comment by zanderso** [comment] 2021-09-02 21:50
To clarify, the issue is not that the PR check was red when it should have been green. Rather the issue is that the dashboard was green when it should have been red, with some red squared reporting where the failure was.

**Comment by chunhtai** [comment] 2021-09-02 21:54
Feels like it is a bug in the dashboard because the PR correctly display status. The yellow box in the dashboard does show the failure and the rerun was ongoing, but it still show the tree is open

**Comment by godofredoc** [comment] 2021-09-02 22:20
@yusufm is there any progress on identifying the root cause of this?

**Comment by zanderso** [comment] 2021-09-04 22:55
This is still happening. The tree is green:
<img width="1624" alt="Screen Shot 2021-09-04 at 3 53 08 PM" src="https://user-images.githubusercontent.com/6343103/132109835-7211e897-3401-4ceb-a262-593c36429304.png">

But something must be failing somewhere:

<img width="931" alt="Screen Shot 2021-09-04 at 3 54 22 PM" src="https://user-images.githubusercontent.com/6343103/132109841-4b61c463-fc55-43d0-bca3-4e0041207ee5.png">

**Comment by godofredoc** [comment] 2021-09-07 18:08
From the logs it seems like the handler to update the status was being affected by permissions to a service account. The service account has been fixed and I'll keep monitoring this bug

**Comment by godofredoc** [comment] 2021-09-08 17:32
Moving as P2 for monitoring. Adding the correct dashboard service account to LUCI ACLs fixed this issue.

**Comment by godofredoc** [comment] 2021-09-08 18:36
I've monitored the tree status for a couple of days and it seems to be working properly. Please reopen if you find another instance of this failure.

**Closed by godofredoc** 2021-09-08 18:36 UTC
Labels: team: infra, passed secondary triage, P2
