### ISSUE TITLE
Error while initializing the Dart VM: Wrong full snapshot version

### ISSUE THREAD

**Issue by Joyuan** [flutter/flutter#20422] opened 2018-08-10 10:17 UTC
I build a local flutter engine project. I get a file named `flutter.jar`. I copy this file to Flutter sdk.  
The path is `flutter/bin/cache/artifacts/engine/android-arm64`. I run a Flutter project and get a crash 

```
[FATAL:flutter/runtime/dart_vm.cc(422)] Error while initializing the Dart VM: Wrong full snapshot version, expected '6891e4153091f27bfe9ab236374f51a1' found '77ed80617eb2b1627e6c51ae7252c677'
```

I cant use `flutter run --local-engine android_debug` because I use Flutter project on an existing Android project.
How can I use my own engine jar in my project?

```
[✓] Flutter (Channel master, v0.5.8-pre.290, on Mac OS X 10.13.6 17G65, locale zh-Hans-CN)
    • Flutter version 0.5.8-pre.290 at /Users/joyuan/Documents/work/workspace/workspace_ali/workspace_flutter/flutter
    • Framework revision 9cb0b21e9c (2 hours ago), 2018-08-10 09:56:13 +0200
    • Engine revision e54bc4ea18
    • Dart version 2.0.0-dev.69.5.flutter-eab492385c

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/joyuan/Documents/work/tools/sdk
    • Android NDK at /Users/joyuan/Documents/work/tools/sdk/ndk-bundle
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)
    • All Android licenses accepted.

[!] iOS toolchain - develop for iOS devices (Xcode 9.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.3, Build version 9E145
    ✗ libimobiledevice and ideviceinstaller are not installed. To install, run:
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    ✗ ios-deploy not installed. To install:
        brew install ios-deploy
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work on iOS.
        For more info, see https://flutter.io/platform-plugins
      To install:
        brew install cocoapods
        pod setup

[✓] Android Studio
    • Android Studio at /Applications/Android Studio 3.2 Preview.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b04)

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Ultimate Edition (version 2017.2.7)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 21.2.2
    • Dart plugin version 172.4343.25

[✓] Connected devices (1 available)
    • MI 5 • de7f556 • android-arm64 • Android 8.0.0 (API 26)
```

**Comment by cbracken** [comment] 2018-09-10 20:46
@Joyuan can you make sure that you've also done the equivalent `host` build for whichever local engine build you're running? For example, if you're building `android_debug_unopt`, make sure you've also built `host_debug_unopt`. Does that get you any further?

**Comment by Joyuan** [comment] 2018-09-14 09:35
> @Joyuan can you make sure that you've also done the equivalent `host` build for whichever local engine build you're running? For example, if you're building `android_debug_unopt`, make sure you've also built `host_debug_unopt`. Does that get you any further?

Yes,I have

**Comment by zoechi** [comment] 2019-02-14 10:50
Duplicate of #16876 ?

**Closed** 2019-02-14 10:50 UTC
Labels: engine
