### ISSUE TITLE
Rich Text shows wrong text with same font sizes but different colors in TextSpan

### ISSUE THREAD

**Issue by mrmops** [flutter/flutter#113426] opened 2022-10-14 08:24 UTC
## Steps to Reproduce

Create a RichText with multiple TextSpans, style the center TextSpan with a different color, get wrong results.

I need to make some part of the text a different color, but when using RichText and TextSpans with different colors in styles, something wrong happens. RichText shows wrong text with same font sizes but different colors in TextSpans.
In the example I have created three TextSpans, with text '[', 'f' and 'lutter]', a central TextSpan with text 'f' I style with red.

Tested on **web** and **android** platforms

**Expected results:** I expect to see the inscription "[flutter]" in which the letters "f" are painted over in red.

**Actual results:** I see "[flflutte" in which the first letters "fl" are painted over in red and missing text "r]" at the end.

<details>
<summary>Example code</summary>

```
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.light().copyWith(
        scaffoldBackgroundColor: Colors.white,
      ),
      debugShowCheckedModeBanner: false,
      home: const Scaffold(
        body: Center(
          child: MyWidget(),
        ),
      ),
    );
  }
}

class MyWidget extends StatelessWidget {
  const MyWidget({super.key});

  @override
  Widget build(BuildContext context) {
    var firstPart = ' [';
    var matchString = 'f';
    var secondPart = 'lutter]';
    return Text.rich(
      TextSpan(
        children: [
          TextSpan(
            text: firstPart,
          ),
          TextSpan(
            text: matchString,
            style: const TextStyle(color: Colors.red),
          ),
          TextSpan(
            text: secondPart,
          ),
        ],
      ),
      style: const TextStyle(fontSize: 18),
    );
  }
}
```

</details>

<details>
  <summary>Logs</summary>

```
Nothing
[  +81 ms] Syncing files to device Android SDK built for x86...
[   +1 ms] Compiling dart to kernel with 0 updated files
[        ] Processing bundle.
[        ] <- recompile package:rich_text_example/main.dart a7bb0129-00a1-4573-ab6e-466699648c00
[        ] <- a7bb0129-00a1-4573-ab6e-466699648c00
[   +2 ms] Bundle processing done.
[ +147 ms] Updating files.
[        ] DevFS: Sync finished
[   +1 ms] Syncing files to device Android SDK built for x86... (completed in 153ms)
[        ] Synced 0.0MB.
[   +1 ms] <- accept
[   +7 ms] Connected to _flutterView/0xf4b73710.
[   +2 ms] Flutter run key commands.
[   +1 ms] r Hot reload. 
[        ] R Hot restart.
[        ] h List all available interactive commands.
[        ] d Detach (terminate "flutter run" but leave application running).
[        ] c Clear the screen
[        ] q Quit (terminate the application on the device).
[        ]  Running with sound null safety 
[        ] An Observatory debugger and profiler on Android SDK built for x86 is available at: http://127.0.0.1:54663/nbtl_7WJHFw=/
[+1198 ms] The Flutter DevTools debugger and profiler on Android SDK built for x86 is available at: http://127.0.0.1:9100?uri=http://127.0.0.1:54663/nbtl_7WJHFw=/
[  +49 ms] D/EGL_emulation(19770): eglMakeCurrent: 0xebb63d20: ver 3 1 (tinfo 0xf4b89790)

```

```
No issues found! (ran in 2.8s)
```

```
[√] Flutter (Channel stable, 3.3.4, on Microsoft Windows [Version 10.0.22000.1098], locale ru-RU)
    • Flutter version 3.3.4 on channel stable at C:\Users\kirie\Documents\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision eb6d86ee27 (9 days ago), 2022-10-04 22:31:45 -0700
    • Engine revision c08d7d5efc
    • Dart version 2.18.2
    • DevTools version 2.15.0

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0-rc5)
    • Android SDK at C:\Users\kirie\AppData\Local\Android\sdk
    • Platform android-33, build-tools 31.0.0-rc5
    • Java binary at: E:\Android studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • CHROME_EXECUTABLE = C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.2.5)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.2.32616.157
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.3)
    • Android Studio at E:\Android studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[√] IntelliJ IDEA Ultimate Edition (version 2021.2)
    • IntelliJ at C:\Users\kirie\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\212.5284.40
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] IntelliJ IDEA Ultimate Edition (version 2021.3)
    • IntelliJ at C:\Users\kirie\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\213.6461.79
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] Connected device (4 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Windows (desktop)                  • windows       • windows-x64    • Microsoft Windows [Version 10.0.22000.1098]
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 106.0.5249.119
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 106.0.1370.37

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

</details>

![image](https://user-images.githubusercontent.com/30927821/195791932-7bf30705-bba9-4476-a58d-6f98c4d4ea8e.png)

**WORKAROUND** 

I noticed that if you change the font size of the "color" TextSpan to something different from the main RichText, then this gives the expected result. This can be used as a workaround for the problem. But it's still broken.

**Comment by danagbemava-nc** [comment] 2022-10-14 10:40
Hi @mrmops, this is a duplicate of https://github.com/flutter/flutter/issues/104884. 

Kindly follow up for updates in the issue linked above for updates. 

Kindly upvote the original issue. 

Closing from here as duplicate. 

Thank you

**Closed by danagbemava-nc** 2022-10-14 10:40 UTC
Labels: in triage
