### ISSUE TITLE
Performance: ListView disposes and recreates the State & RenderObject of all children (identified by ValueKey) when the item order changes

### ISSUE THREAD

**Issue by sir-boformer** [flutter/flutter#21023] opened 2018-08-25 16:49 UTC
This report is the result of intensive performance tests of a list that can be filtered and sorted in different ways. I noticed that rebuilding the list was extremely slow (in profile mode) when the children changed:

<img src="https://user-images.githubusercontent.com/22688477/44620512-02c7a800-a896-11e8-859c-03872516ec39.png" width="200">

As a test, I created a `ListView` with 5 children, identified by `ValueKey`s (A to E), and a button to reverse the sort order of the list items.

What I expected was that that State and RenderObjects would be kept. But instead, all `RenderObject`s were recreated and all `State` was lost, which is quite a blow on performance if it happens frequently.

It seems like the items are only recycled if they are still at the exact same index as before:

Action | Result
---  | -----
Reverse order | If the item count is uneven, only the item in middle is recycled, all other state is lost + `RenderObject`s are recreated
Remove first item | All state is lost
Remove last item | All items are recycled, no `RenderObject`s are recreated.

The strange thing is that when I replace the `ListView` with a `Column`, all items are recycled and state is kept when I change the order (or remove items).

**Is this the intended behavior?** 

```dart
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'List playground',
      home: TestPage(),
    );
  }
}

class TestPage extends StatefulWidget {
  @override
  State<StatefulWidget> createState() => _TestPageState();
}

class _TestPageState extends State<TestPage> {
  List<String> items = ['A', 'B', 'C', 'D', 'E'];

  void _reverseOrder() {
    setState(() {
      items = items.reversed.toList();
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SafeArea(
        child: ListView(
          children: items.map(_buildItem).toList(),
        ),
      ),
      bottomNavigationBar: BottomAppBar(
        child: FlatButton(
          onPressed: _reverseOrder,
          child: Text('reverse order'),
        ),
      ),
    );
  }

  Widget _buildItem(String data) {
    return TestProxy(
      key: ValueKey(data),
      child: Container(
        height: 80.0,
        padding: EdgeInsets.all(16.0),
        decoration: BoxDecoration(
          border: Border(bottom: BorderSide()),
        ),
        child: Center(
          child: Text(data),
        ),
      ),
    );
  }
}

class TestProxy extends SingleChildRenderObjectWidget {
  TestProxy({Key key, Widget child}) : super(key: key, child: child);

  @override
  RenderObject createRenderObject(BuildContext context) {
    print('createRenderObject $key');
    return RenderProxyBox();
  }

  @override
  void updateRenderObject(BuildContext context, RenderObject renderObject) {
    print('updateRenderObject $key');
  }
}
```

**Comment by knopp** [comment] 2018-11-21 13:32
We're also having problem with this. When removing item from `SliverMultiBoxAdaptorWidget` all subsequent items are rebuilt, despite having matching keys. It seems that the problem is `SliverMultiBoxAdaptorElement.performRebuild` only taking index into account, disregarding matching keys completely. 

This seems to be a rather large oversight, as it breaks things like animations in items below the removed item.

**Comment by AndreHaueisen** [comment] 2019-04-20 19:41
Are there any updates on this issue? I'm dealing with videos inside a ListView and since the objects are getting unnecessarily disposed, it downloads the same video several times. The performance hit is not pretty.

**Comment by GustavoContreiras** [comment] 2019-05-18 15:44
> 
> 
> Are there any updates on this issue? I'm dealing with videos inside a ListView and since the objects are getting unnecessarily disposed, it downloads the same video several times. The performance hit is not pretty.

Same happens here. I have a ListView that takes videos and photos from Firebase Storage, the photos have around 60 kb, but the videos have around 4 mb and everytime I scroll the list (in both directions) it redownload the video (the video appears with a black screen and the console shows downloading messages. I even reached the Firebase Cloud Functions limit because of that.

I'm using CachedNetworkManager on photos. Should I download the videos to the temporary/cache directory to avoid this behaviour? What is the best approach to display media in a list view feed for a social network?

**Comment by GustavoContreiras** [comment] 2019-05-18 19:07
Using `AutomaticKeepAliveClientMixin` in the stateful widget (inside the list view) that holds the network video and also on the stateful widget that holds the list view and `cacheExtent: 10, addAutomaticKeepAlives: true` on the list view solved this issue. Need to explore it more to know exaclty what solved.

**Comment by AndreHaueisen** [comment] 2019-05-18 21:35
@GustavoContreiras I have tried this solution, but as it turns out disposing of the widget videos are a good thing. Lower-end devices (I've tested on Moto X running Lollipop) can't handle more than three video controllers initialized at the same time.

**Comment by GustavoContreiras** [comment] 2019-05-20 11:04
@AndreHaueisen Maybe you can try having just one video controller declared outside of the ListView and somehow you can check which item from the ListView is visible. If this item is visible, attach it's video url to the "global" video controller. 

Here you can see how to check the current item of a ListView: https://github.com/flutter/flutter/issues/19941#issuecomment-486950990

**Comment by Boehrsi** [comment] 2019-07-10 14:11
Anything new in regards to this issue? Due to the recreation of states and widgets e.g. a chat app is more or less impossible to implement in a reliable and performant manner.

**Example:**

- Using a list view (to display the messages)
- Using reverse: true (to display the newest messages at the bottom of the screen)
- Receiving or sending a new message and inserting it (logically at the first index [0] to display it at the bottom)

**Result:**
This will lead to a recreation of all other messages, every time a new message is created (this happens due to the index change and because keys are ignored). For text messages this wouldn't be that bad, but images and videos would be fetched over and over. Caching stuff is possible as usual but the UI recreation would still be quite bad.

**Comment by goderbauer** [comment] 2019-07-11 22:28
I would have expected https://github.com/flutter/flutter/pull/29188 to fix this. Maybe we missed something...

/cc @chunhtai

**Comment by goderbauer** [comment] 2019-07-11 22:33
I just double-checked, the example that @sir-boformer gave in his initial bug description now correctly re-uses the render objects (instead of creating new ones). 

@Boehrsi Can you post a minimal runnable example to show a case where things do not work as expected?

**Comment by chunhtai** [comment] 2019-07-11 22:43
@Boehrsi  You also need to make sure Items are automatic keep alive

**Comment by Boehrsi** [comment] 2019-07-12 09:14
@chunhtai thanks for mentioning. We are already using automatic keep alive.

**Comment by Boehrsi** [comment] 2019-07-12 09:17
> I just double-checked, the example that @sir-boformer gave in his initial bug description now correctly re-uses the render objects (instead of creating new ones).
> 
> @Boehrsi Can you post a minimal runnable example to show a case where things do not work as expected?

Thanks for the fast feedback, if there is already a fix for this problem I will have another look if the problem exists on my end. While verifying I will also try to provide the example code.

**Comment by Boehrsi** [comment] 2019-07-12 11:27
@goderbauer @chunhtai 
I adjusted the given example to demonstrate my problem. One key point I noticed, I'm using the ListView.Builder() as I have a lot of items. But due to the Key() usage the items should get reused anyway, right? Or is my assumption just wrong (if so, sorry for the confusion and could someone point me to "the right way" then)?

`
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'List playground',
      home: TestPage(),
    );
  }
}

class TestPage extends StatefulWidget {
  @override
  State<StatefulWidget> createState() => _TestPageState();
}

class _TestPageState extends State<TestPage> {
  List<String> items = ['1', '2', '3', '4', '5'];

  void _addItem({bool append}) {
    setState(() {
      var now = DateTime.now().toIso8601String();
      if (append) {
        items.add(now);
      } else {
        items.insert(0, now);
      }
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SafeArea(
        child: ListView.builder(
          itemCount: items.length,
          itemBuilder: (BuildContext context, int index) {
            return _buildItem(items[index]);
          },
        ),
      ),
      bottomNavigationBar: BottomAppBar(
        child: Row(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            FlatButton(
              onPressed: () => _addItem(append: true),
              child: Text('Append item'),
            ),
            FlatButton(
              onPressed: () => _addItem(append: false),
              child: Text('Prepend item'),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildItem(String data) {
    return TestProxy(
      key: ValueKey(data),
      child: Container(
        height: 80.0,
        padding: EdgeInsets.all(16.0),
        decoration: BoxDecoration(
          border: Border(bottom: BorderSide()),
        ),
        child: Center(
          child: Text(data),
        ),
      ),
    );
  }
}

class TestProxy extends StatefulWidget {
  final Widget child;

  const TestProxy({Key key, this.child}) : super(key: key);

  @override
  _TestProxyState createState() => _TestProxyState();
}

class _TestProxyState extends State<TestProxy> {
  @override
  void initState() {
    super.initState();
    print("Rebuild for ${widget.key.toString()}");
  }

  @override
  Widget build(BuildContext context) {
    return widget.child;
  }
}
`

Using this example I get on start (which is okay):

`
2019-07-12 13:18:42.181 21008-21031/com.openxchange.oxcoi.dev I/flutter: Rebuild for [<'1'>]
2019-07-12 13:18:42.196 21008-21031/com.openxchange.oxcoi.dev I/flutter: Rebuild for [<'2'>]
2019-07-12 13:18:42.198 21008-21031/com.openxchange.oxcoi.dev I/flutter: Rebuild for [<'3'>]
2019-07-12 13:18:42.208 21008-21031/com.openxchange.oxcoi.dev I/flutter: Rebuild for [<'4'>]
2019-07-12 13:18:42.210 21008-21031/com.openxchange.oxcoi.dev I/flutter: Rebuild for [<'5'>]
`

On append (which is okay):

`
2019-07-12 13:18:45.853 21008-21031/com.openxchange.oxcoi.dev I/flutter: Rebuild for [<'2019-07-12T13:18:45.736902'>]

`
On prepend (which is my problem):
`
2019-07-12 13:18:52.309 21008-21031/com.openxchange.oxcoi.dev I/flutter: Rebuild for [<'2019-07-12T13:18:52.284367'>]
2019-07-12 13:18:52.312 21008-21031/com.openxchange.oxcoi.dev I/flutter: Rebuild for [<'1'>]
2019-07-12 13:18:52.315 21008-21031/com.openxchange.oxcoi.dev I/flutter: Rebuild for [<'2'>]
2019-07-12 13:18:52.318 21008-21031/com.openxchange.oxcoi.dev I/flutter: Rebuild for [<'3'>]
2019-07-12 13:18:52.321 21008-21031/com.openxchange.oxcoi.dev I/flutter: Rebuild for [<'4'>]
2019-07-12 13:18:52.324 21008-21031/com.openxchange.oxcoi.dev I/flutter: Rebuild for [<'5'>]
2019-07-12 13:18:52.326 21008-21031/com.openxchange.oxcoi.dev I/flutter: Rebuild for [<'2019-07-12T13:18:45.736902'>]
`

So as soon as I add an element inbetween or at the beginning of the list, every item after the index is rebuild and initState is called (if it's a StatefulWidget).

**Comment by sriharsha-y** [comment] 2019-07-12 15:58
Facing the same issue in a multi form listview. In my case a new form can be dynamically added or deleted by the user at any index. When ever user deletes a form in the middle of the list view, the forms below that form (below indexes) gets rebuild. It is now a blocker for me, I tried passing the keys along with AutomaticKeepAliveClientMixin on my stateful list items. But nothing works.

**Comment by chunhtai** [comment] 2019-07-12 16:30
@Boehrsi  builder does not support changing in the children list by default as I does not know the entire list. In order to make it keep it children alive, you will need to provide a callback for it to do the look up.
Here is the modified code from your example.

```
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'List playground',
      home: TestPage(),
    );
  }
}

class TestPage extends StatefulWidget {
  @override
  State<StatefulWidget> createState() => _TestPageState();
}

class _TestPageState extends State<TestPage> {
  List<String> items = ['1', '2', '3', '4', '5'];

  void _addItem({bool append}) {
    setState(() {
      var now = DateTime.now().toIso8601String();
      if (append) {
        items.add(now);
      } else {
        items.insert(0, now);
      }
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SafeArea(
        child: ListView.custom(
          childrenDelegate: SliverChildBuilderDelegate(
            (BuildContext context, int index) {
              return _buildItem(items[index]);
            },
            childCount: items.length,
            findChildIndexCallback: (Key key) {
              final ValueKey valueKey = key;
              final String data = valueKey.value;
              return items.indexOf(data);
            }
          ),
        ),
      ),
      bottomNavigationBar: BottomAppBar(
        child: Row(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            FlatButton(
              onPressed: () => _addItem(append: true),
              child: Text('Append item'),
            ),
            FlatButton(
              onPressed: () => _addItem(append: false),
              child: Text('Prepend item'),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildItem(String data) {
    return TestProxy(
      key: ValueKey(data),
      child: Container(
        height: 80.0,
        padding: EdgeInsets.all(16.0),
        decoration: BoxDecoration(
          border: Border(bottom: BorderSide()),
        ),
        child: Center(
          child: Text(data),
        ),
      ),
    );
  }
}

class TestProxy extends StatefulWidget {
  final Widget child;

  const TestProxy({Key key, this.child}) : super(key: key);

  @override
  _TestProxyState createState() => _TestProxyState();
}

class _TestProxyState extends State<TestProxy> {
  @override
  void initState() {
    super.initState();
    print("Rebuild for ${widget.key.toString()}");
  }

  @override
  Widget build(BuildContext context) {
    return widget.child;
  }
}
```
You will likely want to optimize findChildIndexCallback as it will be called a lot during the rebuild of the widget.

**Comment by sriharsha-y** [comment] 2019-07-12 17:56
Hey @chunhtai , just tried the code which you have posted, it works 👍.

**Comment by chunhtai** [comment] 2019-07-12 18:07
It might not be obvious that you will need to set up your own childrenDelegate, I will update the doc with some example

**Comment by Boehrsi** [comment] 2019-07-12 18:48
@chunhtai I wasn't able to test your code already, but it looks nice. I already tried the custom list stuff but wasn't able to get it running (so updating the documentation would be awesome). In general thanks for the fast feedback and the awesome support to the Flutter Community. Much appreciate seeing such an  extraordinary support.
I will test the code on Monday, thanks again you saved me a lot of time rewriting loading logic and you eliminated my first "real problem" while developing with Flutter (I'm on it since eight months and it's still just awesome, feeling so productive).

**Comment by Boehrsi** [comment] 2019-07-18 14:26
As a small follow up @chunhtai your suggested changes helped a lot and fixed my initial problem. Thanks again.

**Comment by chunhtai** [comment] 2019-07-19 20:20
@Boehrsi you're welcome!
Merged the documentation update.

**Closed by chunhtai** 2019-07-19 20:20 UTC
Labels: f: scrolling, framework, severe: performance

**Comment by lifenautjoe** [comment] 2019-09-03 10:04
I've tried your code @chunhtai and still can't manage to prevent the items from being rebuilt.. Also dealing with videos here which redownloaded and lag all the scrolling as they're rebuilt every time.

Is that still the way to go or is there a more straight-forward solution available?

Thanks!

**Comment by chunhtai** [comment] 2019-09-03 16:25
@lifenautjoe This is probably the most easier way to keep the state. Can you provide an runnable example so that I might be able to provide some suggestions on?

**Comment by AndruByrne** [comment] 2019-09-10 03:05
Interesting thing I am noticing here:
*plenty* of plugins are written with the assumption that the method call is necessarily passing messages across threads; relatedly, there are some mightily confused people who followed that bg geofencing example and now are wondering how to get back on the main thread...
Those plugins will not cause "jank" if they are performing a short task, but they are by default running on the platform thread, what used to be called ["the UI thread"](https://github.com/flutter/flutter/wiki/The-Engine-architecture#platform-task-runner); this can absolutely cause gestures to be dropped during high workload, and I would not be surprised if it affected the return of Futures to the FutureBuilder.
Only if the plugin developer moved their work to another thread in the native code will you be getting work done in a separate process than the rest of your Dart code; I have a feeling that for some people here, taking a good look at the impl of their plugins or perhaps throwing a compute() around their calls might be the silver bullet.

**Comment by AndruByrne** [comment] 2019-09-10 04:25
considering it, of course the compute wrapper won't do a thing; those method calls will be happening on the main thread...

moved further musings to [more appropriate issue, 13937](https://github.com/flutter/flutter/issues/13937#issuecomment-529763378)

**Comment by khainhero** [comment] 2019-10-06 20:33
> It might not be obvious that you will need to set up your own childrenDelegate, I will update the doc with some example

Hey lovely code you posted there. It did fix the issue of children rebuilding when the list is re-ordered due to new index(in my case).

But I seem to be having a new issue now. 

if you have a mildly long list(make it 20 index worth of objects for example)

if you scroll to the end of the list and insert a new object in index 0. The newly inserted object will  not be in view when you scroll to the start of the list. 

Also, it will remove all objects that werent visible in the viewport. 

When inserting in an index, or changing order of the list(i.e sorting), it removes all other objects not visible in the view port and will not show the newly inserted object.

That happens when the viewport is not at the start of the list.

If we have the viewport looking at the start of the list, then inserting and sorting the list for example will work as expected. If a user has scrolled away from the start of the list(to look at other indexes), and a new object is added(via,` insert(0,object)` and/or sorted) then the scrollview will have a jump, objects not shown in view port will be removed and the newly inserted object will not be shown.

When scrolling back to start of the list(with removed objects by the weird error), if you insert a new object via insert(0,object), it will show the previously attempted insert of the object and now show the new one.

Very weird issue. Hard to make a messaging app with this issue. 
Issue seems primarily related to inserting at specific index, re-ordering of list. Modification of list(such as `_oldList = List.from(newList)`).

If you rely on a list that only relies on adding new objects at the end of the list via `_list.add(object)`, then there is no issue at all

**Comment by chunhtai** [comment] 2019-10-07 16:12
@khainhero When you said remove, did you mean it got disposed? If that is the case, using the [AutmaticKeepAliveClientMixin](https://api.flutter.dev/flutter/widgets/AutomaticKeepAliveClientMixin-mixin.html) should work. Our ListView will destroy every widget that are not in viewport if it does not keep alive.

**Comment by khainhero** [comment] 2019-10-07 16:33
> @khainhero When you said remove, did you mean it got disposed? If that is the case, using the [AutmaticKeepAliveClientMixin](https://api.flutter.dev/flutter/widgets/AutomaticKeepAliveClientMixin-mixin.html) should work. Our ListView will destroy every widget that are not in viewport if it does not keep alive.

Hey thanks for the reply. The automaticKeepAliveClientMixin did the trick of keeping the widgets not in viewport.

There is still the issue of newly inserted objects into the list not being shown, when we are not in the start of the list. 

I mean, we can add items to back of the list(ie _list.Add(object) when not looking at the back of the list(in view port)
When we insert new object like _list.insert(0,object) and when not looking at the start of the list(in view port) it does not show the newly added object when scrolling back to try to see the newly added item.

I hope that make sense

**Comment by chunhtai** [comment] 2019-10-07 18:26
@khainhero do you have an runnable example? That sounds like a bug.

**Comment by khainhero** [comment] 2019-10-07 19:30
> @khainhero do you have an runnable example? That sounds like a bug.

Yeah i hope so!. I will copy and paste it from my editor. Its your previous example, slightly modified and addition of the keep alive mixin

```
  List<int> items = [1,2,3,4,5]; //init list of items
  void _addItem({bool append}) {
    var now = DateTime.now().millisecondsSinceEpoch;
    if (append) {
        items.add(now);
    } else {
        items.insert(0, now);
    } 
    setState(() {
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SafeArea(
        child: ListView.custom(
          reverse: true,
          childrenDelegate: SliverChildBuilderDelegate(
            (BuildContext context, int index) {
              return _buildItem(items[index], index);
            },
            childCount: items.length,
            findChildIndexCallback: (Key key) {
              final ValueKey valueKey = key;
              final int data = valueKey.value;
              return items.indexOf(data);
            }
          ),
        ),
      ),
      bottomNavigationBar: BottomAppBar(
        child: Row(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            FlatButton(
              onPressed: () => _addItem(append: true),
              child: Text('Append item'),
            ),
            FlatButton(
              onPressed: () => _addItem(append: false),
              child: Text('Prepend item'),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildItem(int data, int index) {
    return TestProxy(
      key: ValueKey(data),
      child: Container(
        height: 80.0,
        padding: EdgeInsets.all(16.0),
        decoration: BoxDecoration(
          border: Border(bottom: BorderSide()),
        ),
        child: Center(
          child: Text("index: $index . . . $data"),
        ),
      ),
    );
  }
```

modified test proxy: 

```
class TestProxy extends StatefulWidget {
  final Widget child;

  const TestProxy({Key key, this.child}) : super(key: key);

  @override
  _TestProxyState createState() => _TestProxyState();
}

class _TestProxyState extends State<TestProxy> with AutomaticKeepAliveClientMixin {
  @override
  bool get wantKeepAlive => true;

  @override
  void initState(){
    super.initState();
    print("");
    //print("Rebuild for ${widget.key.toString()}");
    print("");
  }

  @override
  Widget build(BuildContext context){
    super.build(context);
    return widget.child;
  }
}
```

**Comment by chunhtai** [comment] 2019-10-07 20:00
@khainhero It appears to be a bug.
I filed this https://github.com/flutter/flutter/issues/42142, lets continue the discussion their

**Comment by gerry05** [comment] 2019-12-05 08:24
> 
> 
> Are there any updates on this issue? I'm dealing with videos inside a ListView and since the objects are getting unnecessarily disposed, it downloads the same video several times. The performance hit is not pretty.


We have the same problem but mine is for audio.. Is your problem got solved?

**Comment by imtoori** [comment] 2020-02-17 15:22
@khainhero did you find a solution?

**Comment by khainhero** [comment] 2020-02-17 18:12
> @khainhero did you find a solution?

no solution

I just do all the async work in background and when it is ready, I add it to the list and re-sort the whole list. Basically rebuilding every widget.

So the main goal is to make sure every widget is just a widget to display information and just do network calls in background.

still waiting for the fix :(

**Comment by DAKZH** [comment] 2020-03-14 16:08
Try to add ValueKey to your list item widget. 

Example:

`ListView(
                          reverse: true,
                          children: snapshot.data.documents.map(
                            (DocumentSnapshot document) {
                              return MessageWidget(
                                key: ValueKey(document.documentID), // HERE
                                document: document,
                              );
                            },
                          ).toList(),
                        );`
