### ISSUE TITLE
url_launcher's latest version causes build errors when targetting ios 18.

### ISSUE THREAD

**Issue by ibnYusrat** [flutter/flutter#155423] opened 2024-09-19 18:26 UTC
### Steps to reproduce

1. use the url_launcher while targetting ios 18. 
2. try to build. 

### Expected results

It should build and should run. 

### Actual results

Build Fails.

### Code sample
This is not required because it works fine on Android, and worked fine when we were targetting previous versions of iOS.

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

<img width="1532" alt="image" src="https://github.com/user-attachments/assets/681e863b-381a-410e-939e-192b44b25be5">

</details>

### Logs

<details open><summary>Logs</summary>

```console
fvm flutter run


Xcode's output:
↳
    Writing result bundle at path:
    	/var/folders/bw/d1y88tlx17xgh4dbq0h9194m0000gn/T/flutter_tools.AHvRDK/flutter_ios_build_temp_dirN8jq1w/temporary_xcresult_bundle

    /Users/ibnyusrat/.pub-cache/hosted/pub.dev/url_launcher_ios-6.3.0/ios/url_launcher_ios/Sources/url_launcher_ios/Launcher.swift:22:1: error: type 'UIApplication' does not conform to protocol
    'Launcher'
    extension UIApplication: Launcher {}
    ^
    UIKit.UIApplication:24:15: note: candidate has non-matching type '(URL, [UIApplication.OpenExternalURLOptionsKey : Any], (@MainActor @Sendable (Bool) -> Void)?) -> Void'
        open func open(_ url: URL, options: [UIApplication.OpenExternalURLOptionsKey : Any] = [:], completionHandler completion: (@MainActor @Sendable (Bool) -> Void)? = nil)
                  ^
    /Users/ibnyusrat/.pub-cache/hosted/pub.dev/url_launcher_ios-6.3.0/ios/url_launcher_ios/Sources/url_launcher_ios/Launcher.swift:22:1: note: add stubs for conformance
    extension UIApplication: Launcher {}
    ^

```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
❯ fvm flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.22.0, on macOS 15.0 24A335 darwin-arm64, locale en-PK)
[!] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.1)
[✓] VS Code (version 1.88.1)
[✓] Connected device (4 available)
[✓] Network resources

! Doctor found issues in 1 category.
```

</details>

**Comment by ibnYusrat** [comment] 2024-09-19 18:30
It seems the signature doesn't match on `url_launcher_ios`. I have tried with the latest version 6.3.0. 

This seems to be the main error imho:
```bash
UIKit.UIApplication:24:15: note: candidate has non-matching type '(URL, [UIApplication.OpenExternalURLOptionsKey : Any], (@MainActor @Sendable (Bool) -> Void)?) -> Void'
        open func open(_ url: URL, options: [UIApplication.OpenExternalURLOptionsKey : Any] = [:], completionHandler completion: (@MainActor @Sendable (Bool) -> Void)? = nil)
                  ^
```

Disclosure: *I am not a dart/flutter developer, neither an iOS developer so my knowledge is pretty limited here.*

**Comment by stuartmorgan** [comment] 2024-09-19 20:20
This is a duplicate of https://github.com/flutter/flutter/issues/151467

> ```
>   /Users/ibnyusrat/.pub-cache/hosted/pub.dev/url_launcher_ios-6.3.0
> ```
> [...]
> It seems the signature doesn't match on `url_launcher_ios`. I have tried with the latest version 6.3.0.

The latest version of `url_launcher_ios`, which is the one with the fix, is 6.3.1. Please see [the last comment in the issue referenced above](https://github.com/flutter/flutter/issues/151467#issuecomment-2361004021)

**Closed by stuartmorgan** 2024-09-19 20:20 UTC

**Comment by ibnYusrat** [comment] 2024-09-19 20:24
> This is a duplicate of #151467
> 
> > ```
> >   /Users/ibnyusrat/.pub-cache/hosted/pub.dev/url_launcher_ios-6.3.0
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > [...]
> > It seems the signature doesn't match on `url_launcher_ios`. I have tried with the latest version 6.3.0.
> 
> The latest version of `url_launcher_ios`, which is the one with the fix, is 6.3.1. Please see [the last comment in the issue referenced above](https://github.com/flutter/flutter/issues/151467#issuecomment-2361004021)

But 6.3.1 doesn't even exist..

<img width="798" alt="image" src="https://github.com/user-attachments/assets/aded50b0-0325-458a-b15a-301e04d27229">

**Comment by ibnYusrat** [comment] 2024-09-19 20:24
The latest version available on flutter dev is 6.3.0. Is there a way to get the newer version without it being deployed on flutter dev?

**Comment by stuartmorgan** [comment] 2024-09-20 02:08
`url_launcher_ios` and `url_launcher` are not the same package. The way to get the latest version of the transitive `url_launcher_ios` dependency is to run the command in the comment I linked to.

**Comment by ibnYusrat** [comment] 2024-09-20 04:44
> `url_launcher_ios` and `url_launcher` are not the same package. The way to get the latest version of the transitive `url_launcher_ios` dependency is to run the command in the comment I linked to.

`flutter pub upgrade` didn't help, instead I went to the pubspec.lock file and manually updated the transitive dependency (url_launcher_ios 6.3.1).
