### ISSUE TITLE
when use CircularProgressIndicator or RefreshProgressIndicator, the usage of CPU is very high

### ISSUE THREAD

**Issue by cixiu** [flutter/flutter#28110] opened 2019-02-18 16:38 UTC
## Steps to Reproduce

1. create 'lib/main.dart' file
```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key}) : super(key: key);
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Test CircularProgressIndicator'),
      ),
      body: Center(
        child: Container(
            color: Colors.red,
            width: 45.0,
            height: 45.0,
            child: CircularProgressIndicator()
          ),
      )
    );
  }
}

```
2. open Android Emulator, then `flutter run`

3. waiting seconds, CPU usage jump to more than 100%
<img width="419" alt="wechat2b451b511f955b06def88803d960c553" src="https://user-images.githubusercontent.com/26104985/52963847-d5d6f680-33db-11e9-843f-536bf4d4a06c.png">

## Logs

1. `flutter doctor`
```bash
[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.14 18A391, locale zh-Hans-CN)
    • Flutter version 1.0.0 at /Users/cixiu/flutter/flutter
    • Framework revision 5391447fae (3 months ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/cixiu/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/cixiu/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.3.3
    • Dart plugin version 182.5124
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.31.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.23.0

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

```
2. i have checked #21445, but whether it's Android or IOS, the problem still exists。

**Comment by zoechi** [comment] 2019-02-18 16:42
Is this a release build on a real device or a debug build in a simulator/emulator?

**Comment by zoechi** [comment] 2019-02-18 16:44
Could also be #13203 but I think that was mainly reproduce on iOS simulator.

**Comment by cixiu** [comment] 2019-02-18 17:47
@zoechi it's appear both ios-simulator and android-emulator in debug build.

**Comment by zoechi** [comment] 2019-02-18 20:55
I'm closing this as duplicate of #13203 then.

**Closed by zoechi** 2019-02-18 20:55 UTC
Labels: engine, framework, severe: performance
