### ISSUE TITLE
Bad UTF-8 encoding (U+FFFD; REPLACEMENT CHARACTER) found while decoding string: � . The Flutter team would greatly appreciate if you could file a bug explaining exactly what you were doing when this happened: https://github.com/flutter/flutter/issues/new/choose The source bytes were: [239, 191, 189, 10]

### ISSUE THREAD

**Issue by Adityadn64** [flutter/flutter#154503] opened 2024-09-02 11:06 UTC
### Steps to reproduce

void makeAction() {
    dynamic test = "�";
    String test2 = test.toString();
    print(test2);
}

Bad UTF-8 encoding (U+FFFD; REPLACEMENT CHARACTER) found while decoding string: �
. The Flutter team would greatly appreciate if you could file a bug explaining exactly what you were doing when this happened:
https://github.com/flutter/flutter/issues/new/choose
The source bytes were:
[239, 191, 189, 10]

### Expected results

�

### Actual results

Bad UTF-8 encoding (U+FFFD; REPLACEMENT CHARACTER) found while decoding string: �
. The Flutter team would greatly appreciate if you could file a bug explaining exactly what you were doing when this happened:
https://github.com/flutter/flutter/issues/new/choose
The source bytes were:
[239, 191, 189, 10]

### Code sample

<details open><summary>Code sample</summary>

```dart
void makeAction() {
    dynamic test = "�";
    String test2 = test.toString();
    print(test2);
}
  
makeAction();
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
Bad UTF-8 encoding (U+FFFD; REPLACEMENT CHARACTER) found while decoding string: �
. The Flutter team would greatly appreciate if you could file a bug explaining exactly what you were doing when this happened:
https://github.com/flutter/flutter/issues/new/choose
The source bytes were:
[239, 191, 189, 10]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
PS D:\ADITYA FILES\Developer\My Project\tanya_wii> flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.24.1, on Microsoft Windows [Version 10.0.22621.1702], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
[√] Chrome - develop for the web
[!] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.11.2)
    X The current Visual Studio installation is incomplete.
      Please use Visual Studio Installer to complete the installation or reinstall Visual Studio.
[√] Android Studio (version 2024.1)
[√] VS Code, 64-bit edition (version 1.92.2)
[√] Connected device (3 available)
[√] Network resources

! Doctor found issues in 1 category.
```

</details>

**Comment by danagbemava-nc** [comment] 2024-09-02 11:11
Duplicate of https://github.com/flutter/flutter/issues/137025

**Closed by danagbemava-nc** 2024-09-02 11:11 UTC
Labels: in triage
