### ISSUE TITLE
[tool_crash] FileSystemException: Cannot open file, OS Error: No such file or directory, errno = 2

### ISSUE THREAD

**Issue by charlyfdz** [flutter/flutter#123574] opened 2023-03-28 01:40 UTC
## Command
```
flutter gen-l10n --arb-dir lib/l10n --output-localization-file l10n/messages.dart --output-class AppLocalizations
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Cannot open file, OS Error: No such file or directory, errno = 2
```
#0      _File.throwIfError (dart:io/file_impl.dart:629:7)
#1      _File.openSync (dart:io/file_impl.dart:473:5)
#2      _File.writeAsBytesSync (dart:io/file_impl.dart:598:31)
#3      _File.writeAsStringSync (dart:io/file_impl.dart:622:5)
#4      ForwardingFile.writeAsStringSync (package:file/src/forwarding/forwarding_file.dart:150:16)
#5      ErrorHandlingFile.writeAsStringSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:271:22)
#6      _runSync (package:flutter_tools/src/base/error_handling_io.dart:600:14)
#7      ErrorHandlingFile.writeAsStringSync (package:flutter_tools/src/base/error_handling_io.dart:270:5)
#8      LocalizationsGenerator.writeOutputFiles (package:flutter_tools/src/localizations/gen_l10n.dart:1282:20)
#9      GenerateLocalizationsCommand.runCommand (package:flutter_tools/src/commands/generate_localizations.dart:292:13)
#10     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1426:12)
<asynchronous suspension>
#11     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1257:27)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#13     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:283:9)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#16     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
<asynchronous suspension>
#17     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
```
```
[32m[✓][39m Flutter (Channel stable, 3.7.1, on macOS 11.7.4 20G1120 darwin-x64, locale es-419)
    [32m•[39m Flutter version 3.7.1 on channel stable at /Users/zkae/Documents/flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision 7048ed95a5 (hace 8 semanas), 2023-02-01 09:07:31 -0800
    [32m•[39m Engine revision 800594f1f4
    [32m•[39m Dart version 2.19.1
    [32m•[39m DevTools version 2.20.1

[33m[!][39m Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    [32m•[39m Android SDK at /Users/zkae/Library/Android/sdk
    [32m•[39m Platform android-33, build-tools 33.0.1
    [32m•[39m Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    [31m✗[39m Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[32m[✓][39m Xcode - develop for iOS and macOS (Xcode 13.0)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Build 13A233
    [32m•[39m CocoaPods version 1.11.2

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[32m[✓][39m Android Studio (version 2022.1)
    [32m•[39m Android Studio at /Applications/Android Studio.app/Contents
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[32m[✓][39m VS Code (version 1.76.2)
    [32m•[39m VS Code at /Users/zkae/Desktop/Visual Studio Code-2.app/Contents
    [32m•[39m Flutter extension version 3.60.0

[32m[✓][39m VS Code (version 1.59.0)
    [32m•[39m VS Code at /Users/zkae/Downloads/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version 3.60.0

[32m[✓][39m Connected device (3 available)
    [32m•[39m iPhone 11 (mobile) • 8DFC5888-F9D6-4777-A946-8F8E8C48A6B4 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5
      (simulator)
    [32m•[39m macOS (desktop)    • macos                                • darwin-x64     • macOS 11.7.4 20G1120 darwin-x64
    [32m•[39m Chrome (web)       • chrome                               • web-javascript • Google Chrome 111.0.5563.146

[32m[✓][39m HTTP Host Availability
    [32m•[39m All required HTTP hosts are available

[33m![39m Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 7048ed95a5ad3e43d697e0c397464193991fc230
### Plugins
cloud_firestore_web-2.8.10
firebase_auth-3.11.2
firebase_auth_web-4.6.1
firebase_core-1.24.0
firebase_core_web-1.7.3
flutter_plugin_android_lifecycle-2.0.9
flutter_secure_storage-5.1.2
flutter_secure_storage_linux-1.1.3
flutter_secure_storage_macos-1.1.2
flutter_secure_storage_web-1.1.1
flutter_secure_storage_windows-1.1.3
google_sign_in-5.4.4
google_sign_in_android-6.1.8
google_sign_in_ios-5.6.1
google_sign_in_web-0.10.2+1
image_picker-0.8.7
image_picker_android-0.8.6+6
image_picker_for_web-2.1.12
image_picker_ios-0.8.7+2
path_provider-2.0.14
path_provider_android-2.0.24
path_provider_foundation-2.2.0
path_provider_linux-2.1.10
path_provider_windows-2.1.5
shared_preferences-2.0.20
shared_preferences_android-2.0.17
shared_preferences_foundation-2.1.5
shared_preferences_linux-2.1.5
shared_preferences_web-2.0.6
shared_preferences_windows-2.1.5

**Comment by darshankawar** [comment] 2023-03-28 06:54
Closing as duplicate of https://github.com/flutter/flutter/issues/96167

**Closed by darshankawar** 2023-03-28 06:54 UTC
Labels: in triage
