### ISSUE TITLE
Unable to build an UWP app with Flutter 2.5.0-1.0-pre

### ISSUE THREAD

**Issue by g123k** [flutter/flutter#87501] opened 2021-08-02 17:01 UTC
Hello,

I have exactly the same issue as #82967, and it seems it's not fixed.

Here is the error log : 
```
flutter run -d winuwp
Launching lib\main.dart on Windows (UWP) in debug mode...
LINK : warning LNK4075: ' /INCREMENTAL' ignoré à cause de la spécification '/OPT:ICF' [C:\Users\anima\StudioProjects\untitled\build\winuwp\runner_uwp\app.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VisualStudio\v16.0\AppxPackage\Microsoft.AppXPackage.Targets(3327,5): warning : APPX4
001: Build property AppxBundlePlatforms is not explicitly set and is calculated based on currently building architecture. Use 'Create App Package' wizard or edit pro
ject file to set it. [C:\Users\anima\StudioProjects\untitled\build\winuwp\runner_uwp\app.vcxproj]
Building Windows UWP application...
Failed to install file:///C:/Users/anima/StudioProjects/untitled/build/winuwp/runner_uwp/AppPackages/app/app_1.1.0.0_Debug_Test/app_1.1.0.0_x64_Debug.msixbundle
Failed to install app package
Error launching application on Windows (UWP).
```

Here is my `flutter doctor`:
```
>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel dev, 2.5.0-1.0.pre, on Microsoft Windows [version 10.0.19042.1151], locale fr-FR)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.10.4)
[√] Android Studio (version 2020.3)
[√] VS Code (version 1.58.2)
[√] Connected device (5 available)

```

What should I do to fix this?

**Comment by stuartmorgan** [comment] 2021-08-02 20:01
> I have exactly the same issue as #82967

I'm not sure how you reached this conclusion, but your error doesn't appear to be at all related to that one. That was a specific compile failure which doesn't show up anywhere in your log. Your issue is:

> Failed to install file:///C:/Users/anima/StudioProjects/untitled/build/winuwp/runner_uwp/AppPackages/app/app_1.1.0.0_Debug_Test/app_1.1.0.0_x64_Debug.msixbundle
> Failed to install app package

**Comment by TahaTesser** [comment] 2021-08-03 09:01
Hi @g123k 
Currently, when we rerun the app, we run to this issue 
If you uninstall uwp app from Start, it should run again
This is a duplicate of https://github.com/flutter/flutter/issues/86996

**Closed by TahaTesser** 2021-08-03 09:01 UTC
Labels: in triage
