### ISSUE TITLE
After updating to Xcode 12.5.1 I cannot run my app from VSCode anymore

### ISSUE THREAD

**Issue by filippo-signorini** [flutter/flutter#86488] opened 2021-07-15 16:03 UTC
Today I updated Xcode to version 12.5.1 and now every time I try to run an app from VSCode on a physical device I get the message
```
Could not run build/ios/iphoneos/Runner.app on                          
e4a2f368b4f089379c5d1afcc27f630014d4f89a.
Try launching Xcode and selecting "Product > Run" to fix the problem:   
  open ios/Runner.xcworkspace                                           
                                                                        
Installing and launching...                                        14,3s
Error launching application on iPad.
```
If I run the app from Xcode I don't get any error and everything seems fine.

## Steps to Reproduce

1. Run `flutter create test_application`.
2. Open Xcode and assign a team
3. Run `flutter run`

**Expected results:** 
App should run exactly how it does from Xcode.

**Actual results:** 
App does install on device but doesn't run.

<details>
  <summary>Output of `flutter run --verbose`</summary>

```
[        ] ------ Install phase ------
[        ] [  0%] Found e4a2f368b4f089379c5d1afcc27f630014d4f89a (P103AP, iPad 4 (CDMA), iphoneos, armv7s) a.k.a. 'iPad' connected through USB, beginning install
[ +486 ms] [  5%] TransferringPackage
[        ] [  5%] Copying /Users/fabrizio/Documents/test_application/build/ios/iphoneos/Runner.app/META-INF/ to device
[        ] [  5%] Copying /Users/fabrizio/Documents/test_application/build/ios/iphoneos/Runner.app/META-INF/com.apple.ZipMetadata.plist to device
[        ] [  5%] Copying /Users/fabrizio/Documents/test_application/build/ios/iphoneos/Runner.app/_CodeSignature/ to device
[        ] [  5%] Copying /Users/fabrizio/Documents/test_application/build/ios/iphoneos/Runner.app/_CodeSignature/CodeResources to device
[   +9 ms] [  5%] Copying /Users/fabrizio/Documents/test_application/build/ios/iphoneos/Runner.app/AppIcon20x20@2x.png to device
[  +12 ms] [  6%] Copying /Users/fabrizio/Documents/test_application/build/ios/iphoneos/Runner.app/AppIcon20x20@3x.png to device
[        ] [  6%] Copying /Users/fabrizio/Documents/test_application/build/ios/iphoneos/Runner.app/AppIcon29x29.png to device
[        ] [  6%] Copying /Users/fabrizio/Documents/test_application/build/ios/iphoneos/Runner.app/AppIcon60x60@2x.png to device
[        ] [  6%] Copying /Users/fabrizio/Documents/test_application/build/ios/iphoneos/Runner.app/Runner to device
[   +7 ms] [  7%] Copying /Users/fabrizio/Documents/test_application/build/ios/iphoneos/Runner.app/AppIcon29x29@2x.png to device
[        ] [  7%] Copying /Users/fabrizio/Documents/test_application/build/ios/iphoneos/Runner.app/AppIcon40x40@3x.png to device
[        ] [  7%] Copying /Users/fabrizio/Documents/test_application/build/ios/iphoneos/Runner.app/AppIcon29x29~ipad.png to device
[        ] [  7%] Copying /Users/fabrizio/Documents/test_application/build/ios/iphoneos/Runner.app/AppIcon40x40@2x.png to device
[        ] [  8%] Copying /Users/fabrizio/Documents/test_application/build/ios/iphoneos/Runner.app/AppIcon29x29@3x.png to device
[        ] [  8%] Copying /Users/fabrizio/Documents/test_application/build/ios/iphoneos/Runner.app/AppIcon60x60@3x.png to device
[        ] [  8%] Copying /Users/fabrizio/Documents/test_application/build/ios/iphoneos/Runner.app/Base.lproj/ to device
[        ] [  8%] Copying /Users/fabrizio/Documents/test_application/build/ios/iphoneos/Runner.app/Base.lproj/Main.storyboardc/ to device
[        ] [  9%] Copying /Users/fabrizio/Documents/test_application/build/ios/iphoneos/Runner.app/Base.lproj/Main.storyboardc/UIViewController-BYZ-38-t0r.nib to device
[        ] [  9%] Copying /Users/fabrizio/Documents/test_application/build/ios/iphoneos/Runner.app/Base.lproj/Main.storyboardc/BYZ-38-t0r-view-8bC-Xf-vdC.nib to device
[        ] [  9%] Copying /Users/fabrizio/Documents/test_application/build/ios/iphoneos/Runner.app/Base.lproj/Main.storyboardc/Info.plist to device
[        ] [  9%] Copying /Users/fabrizio/Documents/test_application/build/ios/iphoneos/Runner.app/Base.lproj/LaunchScreen.storyboardc/ to device
[        ] [ 10%] Copying /Users/fabrizio/Documents/test_application/build/ios/iphoneos/Runner.app/Base.lproj/LaunchScreen.storyboardc/01J-lp-oVM-view-Ze5-6b-2t3.nib to device
[        ] [ 10%] Copying /Users/fabrizio/Documents/test_application/build/ios/iphoneos/Runner.app/Base.lproj/LaunchScreen.storyboardc/UIViewController-01J-lp-oVM.nib to device
[        ] [ 10%] Copying /Users/fabrizio/Documents/test_application/build/ios/iphoneos/Runner.app/Base.lproj/LaunchScreen.storyboardc/Info.plist to device
[        ] [ 10%] Copying /Users/fabrizio/Documents/test_application/build/ios/iphoneos/Runner.app/Assets.car to device
[   +1 ms] [ 10%] Copying /Users/fabrizio/Documents/test_application/build/ios/iphoneos/Runner.app/AppFrameworkInfo.plist to device
[   +7 ms] [ 11%] Copying /Users/fabrizio/Documents/test_application/build/ios/iphoneos/Runner.app/AppIcon40x40@2x~ipad.png to device
[        ] [ 11%] Copying /Users/fabrizio/Documents/test_application/build/ios/iphoneos/Runner.app/AppIcon76x76@2x~ipad.png to device
[        ] [ 11%] Copying /Users/fabrizio/Documents/test_application/build/ios/iphoneos/Runner.app/AppIcon83.5x83.5@2x~ipad.png to device
[        ] [ 11%] Copying /Users/fabrizio/Documents/test_application/build/ios/iphoneos/Runner.app/AppIcon29x29@2x~ipad.png to device
[        ] [ 12%] Copying /Users/fabrizio/Documents/test_application/build/ios/iphoneos/Runner.app/AppIcon40x40~ipad.png to device
[        ] [ 12%] Copying /Users/fabrizio/Documents/test_application/build/ios/iphoneos/Runner.app/Frameworks/ to device
[        ] [ 12%] Copying /Users/fabrizio/Documents/test_application/build/ios/iphoneos/Runner.app/Frameworks/libswiftCoreImage.dylib to device
[  +51 ms] [ 12%] Copying /Users/fabrizio/Documents/test_application/build/ios/iphoneos/Runner.app/Frameworks/libswiftObjectiveC.dylib to device
[ +117 ms] [ 13%] Copying /Users/fabrizio/Documents/test_application/build/ios/iphoneos/Runner.app/Frameworks/libswiftCore.dylib to device
[+2656 ms] [ 18%] Copying /Users/fabrizio/Documents/test_application/build/ios/iphoneos/Runner.app/Frameworks/libswiftCoreGraphics.dylib to device
[ +104 ms] [ 18%] Copying /Users/fabrizio/Documents/test_application/build/ios/iphoneos/Runner.app/Frameworks/libswiftUIKit.dylib to device
[ +184 ms] [ 18%] Copying /Users/fabrizio/Documents/test_application/build/ios/iphoneos/Runner.app/Frameworks/libswiftMetal.dylib to device
[  +27 ms] [ 19%] Copying /Users/fabrizio/Documents/test_application/build/ios/iphoneos/Runner.app/Frameworks/libswiftDispatch.dylib to device
[ +107 ms] [ 19%] Copying /Users/fabrizio/Documents/test_application/build/ios/iphoneos/Runner.app/Frameworks/libswiftos.dylib to device
[  +32 ms] [ 19%] Copying /Users/fabrizio/Documents/test_application/build/ios/iphoneos/Runner.app/Frameworks/libswiftCoreFoundation.dylib to device
[  +34 ms] [ 20%] Copying /Users/fabrizio/Documents/test_application/build/ios/iphoneos/Runner.app/Frameworks/Flutter.framework/ to device
[        ] [ 20%] Copying /Users/fabrizio/Documents/test_application/build/ios/iphoneos/Runner.app/Frameworks/Flutter.framework/_CodeSignature/ to device
[        ] [ 20%] Copying /Users/fabrizio/Documents/test_application/build/ios/iphoneos/Runner.app/Frameworks/Flutter.framework/_CodeSignature/CodeResources to device
[  +22 ms] [ 20%] Copying /Users/fabrizio/Documents/test_application/build/ios/iphoneos/Runner.app/Frameworks/Flutter.framework/icudtl.dat to device
[ +103 ms] [ 21%] Copying /Users/fabrizio/Documents/test_application/build/ios/iphoneos/Runner.app/Frameworks/Flutter.framework/Flutter to device
[+3105 ms] [ 27%] Copying /Users/fabrizio/Documents/test_application/build/ios/iphoneos/Runner.app/Frameworks/Flutter.framework/Headers/ to device
[        ] [ 27%] Copying /Users/fabrizio/Documents/test_application/build/ios/iphoneos/Runner.app/Frameworks/Flutter.framework/Headers/FlutterEngine.h to device
[        ] [ 28%] Copying /Users/fabrizio/Documents/test_application/build/ios/iphoneos/Runner.app/Frameworks/Flutter.framework/Headers/FlutterChannels.h to device
[        ] [ 28%] Copying /Users/fabrizio/Documents/test_application/build/ios/iphoneos/Runner.app/Frameworks/Flutter.framework/Headers/FlutterPlugin.h to device
[        ] [ 28%] Copying /Users/fabrizio/Documents/test_application/build/ios/iphoneos/Runner.app/Frameworks/Flutter.framework/Headers/FlutterAppDelegate.h to device
[        ] [ 28%] Copying /Users/fabrizio/Documents/test_application/build/ios/iphoneos/Runner.app/Frameworks/Flutter.framework/Headers/FlutterTexture.h to device
[        ] [ 29%] Copying /Users/fabrizio/Documents/test_application/build/ios/iphoneos/Runner.app/Frameworks/Flutter.framework/Headers/FlutterEngineGroup.h to device
[        ] [ 29%] Copying /Users/fabrizio/Documents/test_application/build/ios/iphoneos/Runner.app/Frameworks/Flutter.framework/Headers/FlutterPlatformViews.h to device
[        ] [ 29%] Copying /Users/fabrizio/Documents/test_application/build/ios/iphoneos/Runner.app/Frameworks/Flutter.framework/Headers/FlutterHeadlessDartRunner.h to device
[        ] [ 29%] Copying /Users/fabrizio/Documents/test_application/build/ios/iphoneos/Runner.app/Frameworks/Flutter.framework/Headers/FlutterCodecs.h to device
[        ] [ 30%] Copying /Users/fabrizio/Documents/test_application/build/ios/iphoneos/Runner.app/Frameworks/Flutter.framework/Headers/Flutter.h to device
[        ] [ 30%] Copying /Users/fabrizio/Documents/test_application/build/ios/iphoneos/Runner.app/Frameworks/Flutter.framework/Headers/FlutterViewController.h to device
[        ] [ 30%] Copying /Users/fabrizio/Documents/test_application/build/ios/iphoneos/Runner.app/Frameworks/Flutter.framework/Headers/FlutterMacros.h to device
[        ] [ 30%] Copying /Users/fabrizio/Documents/test_application/build/ios/iphoneos/Runner.app/Frameworks/Flutter.framework/Headers/FlutterDartProject.h to device
[        ] [ 31%] Copying /Users/fabrizio/Documents/test_application/build/ios/iphoneos/Runner.app/Frameworks/Flutter.framework/Headers/FlutterPluginAppLifeCycleDelegate.h to device
[        ] [ 31%] Copying /Users/fabrizio/Documents/test_application/build/ios/iphoneos/Runner.app/Frameworks/Flutter.framework/Headers/FlutterBinaryMessenger.h to device
[        ] [ 31%] Copying /Users/fabrizio/Documents/test_application/build/ios/iphoneos/Runner.app/Frameworks/Flutter.framework/Headers/FlutterCallbackCache.h to device
[        ] [ 31%] Copying /Users/fabrizio/Documents/test_application/build/ios/iphoneos/Runner.app/Frameworks/Flutter.framework/Modules/ to device
[        ] [ 31%] Copying /Users/fabrizio/Documents/test_application/build/ios/iphoneos/Runner.app/Frameworks/Flutter.framework/Modules/module.modulemap to device
[        ] [ 32%] Copying /Users/fabrizio/Documents/test_application/build/ios/iphoneos/Runner.app/Frameworks/Flutter.framework/Info.plist to device
[        ] [ 32%] Copying /Users/fabrizio/Documents/test_application/build/ios/iphoneos/Runner.app/Frameworks/App.framework/ to device
[        ] [ 32%] Copying /Users/fabrizio/Documents/test_application/build/ios/iphoneos/Runner.app/Frameworks/App.framework/_CodeSignature/ to device
[        ] [ 32%] Copying /Users/fabrizio/Documents/test_application/build/ios/iphoneos/Runner.app/Frameworks/App.framework/_CodeSignature/CodeResources to device
[   +6 ms] [ 33%] Copying /Users/fabrizio/Documents/test_application/build/ios/iphoneos/Runner.app/Frameworks/App.framework/App to device
[  +11 ms] [ 33%] Copying /Users/fabrizio/Documents/test_application/build/ios/iphoneos/Runner.app/Frameworks/App.framework/flutter_assets/ to device
[        ] [ 33%] Copying /Users/fabrizio/Documents/test_application/build/ios/iphoneos/Runner.app/Frameworks/App.framework/flutter_assets/vm_snapshot_data to device
[   +3 ms] [ 33%] Copying /Users/fabrizio/Documents/test_application/build/ios/iphoneos/Runner.app/Frameworks/App.framework/flutter_assets/isolate_snapshot_data to device
[ +265 ms] [ 34%] Copying /Users/fabrizio/Documents/test_application/build/ios/iphoneos/Runner.app/Frameworks/App.framework/flutter_assets/AssetManifest.json to device
[        ] [ 35%] Copying /Users/fabrizio/Documents/test_application/build/ios/iphoneos/Runner.app/Frameworks/App.framework/flutter_assets/kernel_blob.bin to device
[+3581 ms] [ 42%] Copying /Users/fabrizio/Documents/test_application/build/ios/iphoneos/Runner.app/Frameworks/App.framework/flutter_assets/NOTICES to device
[ +182 ms] [ 42%] Copying /Users/fabrizio/Documents/test_application/build/ios/iphoneos/Runner.app/Frameworks/App.framework/flutter_assets/FontManifest.json to device
[ +223 ms] [ 42%] Copying /Users/fabrizio/Documents/test_application/build/ios/iphoneos/Runner.app/Frameworks/App.framework/flutter_assets/packages/ to device
[        ] [ 43%] Copying /Users/fabrizio/Documents/test_application/build/ios/iphoneos/Runner.app/Frameworks/App.framework/flutter_assets/packages/cupertino_icons/ to device
[        ] [ 43%] Copying /Users/fabrizio/Documents/test_application/build/ios/iphoneos/Runner.app/Frameworks/App.framework/flutter_assets/packages/cupertino_icons/assets/ to device
[   +1 ms] [ 43%] Copying /Users/fabrizio/Documents/test_application/build/ios/iphoneos/Runner.app/Frameworks/App.framework/flutter_assets/packages/cupertino_icons/assets/CupertinoIcons.ttf to device
[ +294 ms] [ 43%] Copying /Users/fabrizio/Documents/test_application/build/ios/iphoneos/Runner.app/Frameworks/App.framework/flutter_assets/fonts/ to device
[        ] [ 44%] Copying /Users/fabrizio/Documents/test_application/build/ios/iphoneos/Runner.app/Frameworks/App.framework/flutter_assets/fonts/MaterialIcons-Regular.otf to device
[ +283 ms] [ 44%] Copying /Users/fabrizio/Documents/test_application/build/ios/iphoneos/Runner.app/Frameworks/App.framework/Info.plist to device
[ +140 ms] [ 44%] Copying /Users/fabrizio/Documents/test_application/build/ios/iphoneos/Runner.app/Frameworks/libswiftDarwin.dylib to device
[ +154 ms] [ 45%] Copying /Users/fabrizio/Documents/test_application/build/ios/iphoneos/Runner.app/Frameworks/libswiftQuartzCore.dylib to device
[ +106 ms] [ 45%] Copying /Users/fabrizio/Documents/test_application/build/ios/iphoneos/Runner.app/Frameworks/libswiftCoreAudio.dylib to device
[  +44 ms] [ 45%] Copying /Users/fabrizio/Documents/test_application/build/ios/iphoneos/Runner.app/Frameworks/libswiftFoundation.dylib to device
[+1285 ms] [ 48%] Copying /Users/fabrizio/Documents/test_application/build/ios/iphoneos/Runner.app/Frameworks/libswiftCoreMedia.dylib to device
[  +32 ms] [ 48%] Copying /Users/fabrizio/Documents/test_application/build/ios/iphoneos/Runner.app/AppIcon20x20~ipad.png to device
[  +21 ms] [ 48%] Copying /Users/fabrizio/Documents/test_application/build/ios/iphoneos/Runner.app/embedded.mobileprovision to device
[  +24 ms] [ 49%] Copying /Users/fabrizio/Documents/test_application/build/ios/iphoneos/Runner.app/AppIcon20x20@2x~ipad.png to device
[  +30 ms] [ 49%] Copying /Users/fabrizio/Documents/test_application/build/ios/iphoneos/Runner.app/Info.plist to device
[        ] [ 49%] Copying /Users/fabrizio/Documents/test_application/build/ios/iphoneos/Runner.app/PkgInfo to device
[  +30 ms] [ 49%] Copying /Users/fabrizio/Documents/test_application/build/ios/iphoneos/Runner.app/AppIcon76x76~ipad.png to device
[ +108 ms] [ 52%] CreatingStagingDirectory
[        ] [ 57%] ExtractingPackage
[        ] [ 60%] InspectingPackage
[  +33 ms] [ 60%] TakingInstallLock
[  +73 ms] [ 65%] PreflightingApplication
[  +37 ms] [ 65%] InstallingEmbeddedProfile
[  +30 ms] [ 70%] VerifyingApplication
[ +486 ms] [ 75%] CreatingContainer
[  +10 ms] [ 80%] InstallingApplication
[  +11 ms] [ 85%] PostflightingApplication
[   +7 ms] [ 90%] SandboxingApplication
[  +37 ms] [ 95%] GeneratingApplicationMap
[ +123 ms] Could not run build/ios/iphoneos/Runner.app on e4a2f368b4f089379c5d1afcc27f630014d4f89a.
[   +2 ms] Try launching Xcode and selecting "Product > Run" to fix the problem:
[        ]   open ios/Runner.xcworkspace
[        ] Installing and launching... (completed in 15,0s)
[        ] Error launching application on iPad.
[   +4 ms] "flutter run" took 235.368ms.
[  +99 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:663:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1043:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:196:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:232:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>
           
           
[ +117 ms] ensureAnalyticsSent: 115ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1
```
</details>

<details>
<summary>Output of `flutter analyze`</summary>

```
Analyzing test_application...                                           
No issues found! (ran in 46.0s)
```
</details>

<details>
<summary>Output of `flutter doctor -v`</summary>

```
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.3 20E232 darwin-x64, locale it-IT)
    • Flutter version 2.2.3 at /Users/fabrizio/flutter
    • Framework revision f4abaa0735 (2 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] VS Code (version 1.58.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.24.0

[✓] Connected device (2 available)
    • iPad (mobile) • e4a2f368b4f089379c5d1afcc27f630014d4f89a • ios            • iOS 10.3.4
    • Chrome (web)  • chrome                                   • web-javascript • Google Chrome 91.0.4472.114

! Doctor found issues in 2 categories.
```

</details>

**Comment by TahaTesser** [comment] 2021-07-16 07:37
Hi @filippo-signorini 
Thanks for filing the issue, first of all, make sure you've team ID with no error below it. If the problem persists, please make sure you have a valid developer certificate for the device, see [this](https://stackoverflow.com/a/62335494) for more details.


Based on the error, the issue isn't related to Flutter itself
Thank you

**Comment by filippo-signorini** [comment] 2021-07-16 07:53
Hi @TahaTesser, thanks for the quick reply.
The signing section in Xcode has no errors whatsoever and my developer certificate is valid. I cannot find the "Device Management" menu in my iPad and I've read online that this means that I already trust the certificate.

Should I try revoking and creating a new certificate from Apple Developer?
Thank you in advance.

**Comment by TahaTesser** [comment] 2021-07-19 07:11
Hi @filippo-signorini 
Please do, the error is from `Xcode`,  I notice there is no device's name, only this `e4a2f368b4f089379c5d1afcc27f630014d4f89a`.
It would say "name's iPhone', ex: `Taha's iPhone`

**Comment by nurikadee** [comment] 2021-07-20 04:39
Hi @TahaTesser 
I also got the same problem.

**Comment by filippo-signorini** [comment] 2021-07-21 07:58
Hi @TahaTesser
I tried creating a new certificate, even a new provisioning profile but it seems like nothing changes.
Do you have any idea what this could mean? I've been trying to find a solution for weeks now without luck

**Comment by TahaTesser** [comment] 2021-07-21 11:38
@filippo-signorini 
This doens't  seem like a Flutter issue, If possible try a different mac?

**Comment by filippo-signorini** [comment] 2021-07-21 12:47
@TahaTesser 
Unfortunately I don't have access to another mac, but I tried running the app on another device (iPhone) and it worked.
At this point I'm convinced it is not a flutter issue like you said before, but I still have no idea how to test the app on my iPad.
I tried resetting ly Location and Privacy settings to re-trust my mac but it didn't fix the problem. Any help would be appreciated.

**Comment by TahaTesser** [comment] 2021-07-22 07:02
Hi @filippo-signorini 
I would suggest to look into certififcate for your device, you can get post in Apple dev forum for iOS related help
Given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you

**Closed by TahaTesser** 2021-07-22 07:02 UTC
Labels: in triage
