### ISSUE TITLE
Tapping quickly with 2 fingers could cause an exception in the BaseTapGestureRecognizer class

### ISSUE THREAD

**Issue by dannyvalentesonos** [flutter/flutter#50574] opened 2020-02-11 16:51 UTC
With the following very simple widget tree:
```
class TagGestureHomePage extends StatefulWidget {
  _TagGestureHomePageState createState() => _TagGestureHomePageState();
}

class _TagGestureHomePageState extends State<TagGestureHomePage> {

  @override
  Widget build(BuildContext context) {

    return Scaffold(
        body: Container(
            color: Colors.green,
            child: GestureDetector(
              behavior: HitTestBehavior.opaque,
              onTapDown: (details) => print("outer tap down"),
              onTapCancel: () => print("outer tap cancel"),
              onTap: () => print("outer tap"),
              child: Center(
                  child: Container(
                    width: 300,
                    height: 500,
                    color: Colors.blue,
                    child: GestureDetector(
                      onTap: () => print("inner tap"),
                    )
                  )
              ),
            ),
        )
    );
  }
}
```

We could get an exception thrown by the TapRecognizer class with the following careful repro:
Tap on the outer container, and immediately tap on the inner container. 2 fingers are required in order to tap quickly enough. When the timing is perfect, the inner tap is recorded, but loses, however it is called back and exceeds its deadline and calls _checkDown anyway.

```
I/flutter ( 6942): outer tap down
I/flutter ( 6942): outer tap
E/flutter ( 6942): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: NoSuchMethodError: The getter 'position' was called on null.
E/flutter ( 6942): Receiver: null
E/flutter ( 6942): Tried calling: position
E/flutter ( 6942): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
E/flutter ( 6942): #1      TapGestureRecognizer.handleTapDown (package:flutter/src/gestures/tap.dart:456:28)
E/flutter ( 6942): #2      BaseTapGestureRecognizer._checkDown (package:flutter/src/gestures/tap.dart:256:5)
E/flutter ( 6942): #3      BaseTapGestureRecognizer.didExceedDeadline (package:flutter/src/gestures/tap.dart:227:5)
E/flutter ( 6942): #4      PrimaryPointerGestureRecognizer.didExceedDeadlineWithEvent (package:flutter/src/gestures/recognizer.dart:493:5)
E/flutter ( 6942): #5      PrimaryPointerGestureRecognizer.addAllowedPointer.<anonymous closure> (package:flutter/src/gestures/recognizer.dart:446:40)
E/flutter ( 6942): #6      _rootRun (dart:async/zone.dart:1122:38)
E/flutter ( 6942): #7      _CustomZone.run (dart:async/zone.dart:1023:19)
E/flutter ( 6942): #8      _CustomZone.runGuarded (dart:async/zone.dart:925:7)
E/flutter ( 6942): #9      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
E/flutter ( 6942): #10     _rootRun (dart:async/zone.dart:1126:13)
E/flutter ( 6942): #11     _CustomZone.run (dart:async/zone.dart:1023:19)
E/flutter ( 6942): #12     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:949:23)
E/flutter ( 6942): #13     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:23:15)
E/flutter ( 6942): #14     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:384:19)
E/flutter ( 6942): #15     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:418:5)
E/flutter ( 6942): #16     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
E/flutter ( 6942): 
I/flutter ( 6942): inner tap
```

The very simple fix for this is to do the following in `gestures/tap.dart`

change
```
void _checkDown() {
    if (_sentTapDown) {
      return;
    }
    handleTapDown(down: _down);
    _sentTapDown = true;
  }
```

to 

```
void _checkDown() {
    if (_sentTapDown || _down == null) {
      return;
    }
    handleTapDown(down: _down);
    _sentTapDown = true;
  }
```

I've confirmed this fixes the issue and doesn't introduce any regressions that I can tell.

**Comment by dannyvalentesonos** [comment] 2020-02-11 16:51
@justinmc FYI.

Let me know your thoughts about the fix. Thanks!

**Comment by dkwingsmt** [comment] 2020-02-12 08:15
Thanks for the issue. Can you run `flutter doctor -v` and paste the output here, just so I know which version you're on?
A similar issue was supposed to be fixed by https://github.com/flutter/flutter/pull/45943.

**Comment by dannyvalentesonos** [comment] 2020-02-12 13:26
```
[✓] Flutter (Channel beta, v1.12.13+hotfix.6, on Mac OS X 10.14.6 18G3020, locale en-US)
    • Flutter version 1.12.13+hotfix.6 at /Users/danny.valente/Library/flutter/1.12.13+hotfix.6-beta
    • Framework revision 18cd7a3601 (9 weeks ago), 2019-12-11 06:35:39 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/danny.valente/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.0, Build version 11A420a
    • CocoaPods version 1.7.5

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
```

**Comment by dannyvalentesonos** [comment] 2020-02-12 13:27
Thanks @dkwingsmt The fix to the issue you linked seems like it could very well fix this issue, and I doubt it's in v1.12, right?

**Comment by dannyvalentesonos** [comment] 2020-02-12 14:30
@dkwingsmt I can confirm that when applying the fix you linked, I no longer see an exception in this scenario. Thanks!

**Comment by justinmc** [comment] 2020-02-12 19:16
Sounds like this can be closed!

**Closed by justinmc** 2020-02-12 19:16 UTC
Labels: f: gestures, framework

**Comment by tolotrasamuel** [comment] 2020-09-23 10:50
@justinmc  why did you close this issue? I am using flutter ] 
Flutter (Channel beta, 1.19.0-4.3.pre, on Microsoft Windows [Version 10.0.18362.1082], locale en-MU)

and the issue still persist

**Comment by justinmc** [comment] 2020-09-23 23:59
I closed it because the author said it was fixed, but I suppose it could be back as a regression.  Could you try again after updating Flutter?  Or maybe even using the master channel.

If the bug still persists, can you open a new issue with a minimal app to reproduce it and tag me?
