### ISSUE TITLE
[in_app_purchase: ^3.0.6] Android crashes during buyNonConsumable

### ISSUE THREAD

**Issue by lukeirvin** [flutter/flutter#108341] opened 2022-07-26 02:59 UTC
I am trying to resolve a crash I am experiencing on the Android version of my app.

I'm not certain when this started occurring but as of right now, if I try to buy a subscription in-app purchase my app crashes every time. This works as expected on iOS.

```
buyProduct(ProductDetails productDetails) async {
    _isTrying = true;
    final PurchaseParam purchaseParam =
        PurchaseParam(productDetails: productDetails);

    // Store variables we will need.
    price = productDetails.price;
    productId = productDetails.id;
    locale = productDetails.currencyCode;

    if (kDebugMode) {
      print(_purchases);
    }
    if (!_isProUser) {
        _inAppPurchase.buyNonConsumable(purchaseParam: purchaseParam); // once I hit this line on Android a crash occurs.
      var transactions = await SKPaymentQueueWrapper().transactions();
      for (var skPaymentTransactionWrapper in transactions) {
        SKPaymentQueueWrapper().finishTransaction(skPaymentTransactionWrapper);
      }

      _callProStatusChangedListeners();
    } else {
      _callProStatusChangedListeners();
    }
  }
```

This is what I see in my console:

```
E/AndroidRuntime(26524): java.lang.NoSuchMethodError: No virtual method setReplaceSkusProrationMode(I)Lcom/android/billingclient/api/BillingFlowParams$Builder; in class Lcom/android/billingclient/api/BillingFlowParams$Builder; or its super classes (declaration of 'com.android.billingclient.api.BillingFlowParams$Builder' appears in /data/app/~~Z7UMofzyghgp7SM7zfK6tA==/com.myapp.appname-tmyM9VBTLR6MdbUpB-EWog==/base.apk)
E/AndroidRuntime(26524): 	at io.flutter.plugins.inapppurchase.MethodCallHandlerImpl.launchBillingFlow(MethodCallHandlerImpl.java:263)
E/AndroidRuntime(26524): 	at io.flutter.plugins.inapppurchase.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:123)
E/AndroidRuntime(26524): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/AndroidRuntime(26524): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:296)
E/AndroidRuntime(26524): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$DartMessenger(DartMessenger.java:320)
E/AndroidRuntime(26524): 	at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$TsixYUB5E6FpKhMtCSQVHKE89gQ.run(Unknown Source:12)
E/AndroidRuntime(26524): 	at android.os.Handler.handleCallback(Handler.java:938)
E/AndroidRuntime(26524): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(26524): 	at android.os.Looper.loopOnce(Looper.java:226)
E/AndroidRuntime(26524): 	at android.os.Looper.loop(Looper.java:313)
E/AndroidRuntime(26524): 	at android.app.ActivityThread.main(ActivityThread.java:8669)
E/AndroidRuntime(26524): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(26524): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
E/AndroidRuntime(26524): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
I/Process (26524): Sending signal. PID: 26524 SIG: 9
Lost connection to device.
```

**Comment by danagbemava-nc** [comment] 2022-07-26 10:16
Hi @lukeirvin, do you happen to be using the play billing library in your `android/app/build.gradle`?
If so, please remove it and see if you still experience the issue. 

Please also provide the output of `flutter doctor -v`.

Thank you

**Comment by lukeirvin** [comment] 2022-07-26 14:03
> Hi @lukeirvin, do you happen to be using the play billing library in your `android/app/build.gradle`? If so, please remove it and see if you still experience the issue.
> 
> Please also provide the output of `flutter doctor -v`.
> 
> Thank you

No, I am not using the play billing library.

Here is my flutter doctor output:

```
[flutter] flutter doctor -v
[✓] Flutter (Channel stable, 2.10.3, on macOS 12.4 21F79 darwin-arm, locale en-US)
    • Flutter version 2.10.3 at /Users/lukeirvin/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (5 months ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/lukeirvin/Library/Android/sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] VS Code (version 1.69.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.44.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 103.0.5060.134

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
exit code 0
```

**Comment by danagbemava-nc** [comment] 2022-07-27 06:16
Hi @lukeirvin, please provide your `pubspec.yaml` as well as a complete minimal reproducible code sample so that we can further investigate this. 

Thank you

**Comment by lukeirvin** [comment] 2022-07-27 13:11
Hey @danagbemava-nc! I was able to resolve this.

The issue that I found was I had another in-app purchase package within my `pubspec.yaml` file. After removing it the crash went away.

Also to note, I was only experiencing the crash on Android devices. iOS still worked as expected.

**Comment by danagbemava-nc** [comment] 2022-07-28 06:39
> Also to note, I was only experiencing the crash on Android devices. iOS still worked as expected.

Hi @lukeirvin, this is due to the fact that the underlying libraries behave differently. This is one of the reasons why the README for the `in_app_purchase` plugin has the note below

> Note: It is not necessary to depend on com.android.billingclient:billing in your own app's android/app/build.gradle file. If you choose to do so know that conflicts might occur.

Given that this issue has been resolved. I'll be closing this issue. 

Thank you

**Closed by danagbemava-nc** 2022-07-28 06:39 UTC
Labels: in triage

**Comment by lukeirvin** [comment] 2022-07-28 14:01
> com.android.billingclient:billing

Hey @danagbemava-nc,

`com.android.billingclient:billing` had NOTHING to do with the issue though. That wasn't even in my app.

The issue was that I had a completely different In-App Purchase package within my .yaml file. 

I would suggest updating the README to note that if you are to use the `in_app_purchase` package, DO NOT use another similar package with it.


Thanks!

**Comment by danagbemava-nc** [comment] 2022-07-28 14:06
Hi @lukeirvin, that package that you were using, depends on the `com.android.billingclient:billing` package.

That is the point I was trying to put across
