### ISSUE TITLE
When are there plans to support multi-window on the desktop?

### ISSUE THREAD

**Issue by zhulinghaizhoqiaodaima** [flutter/flutter#144282] opened 2024-02-28 01:31 UTC
### Use case

When are there plans to support multi-window on the desktop?

### Proposal

When are there plans to support multi-window on the desktop?

**Comment by stuartmorgan** [comment] 2024-02-28 01:55
Closing as a duplicate of https://github.com/flutter/flutter/issues/30701

Please see also https://github.com/flutter/flutter/wiki/Issue-hygiene#when-will-my-bug-be-fixed

**Closed by stuartmorgan** 2024-02-28 01:55 UTC
