### ISSUE TITLE
Failed to build apk with fastlane

### ISSUE THREAD

**Issue by vanlooverenkoen** [flutter/flutter#57934] opened 2020-05-25 09:48 UTC
```
[11:34:21]: [32m--------------------------------------------------------------------[0m
[11:34:21]: [32mStep: flutter build apk --release --flavor alpha -tlib/main_alpha.dart --build-number\=214[0m
[11:34:21]: [32m--------------------------------------------------------------------[0m
[11:34:21]: [36m$ flutter build apk --release --flavor alpha -tlib/main_alpha.dart --build-number\=214[0m
[11:34:23]: ▸ [35mYou are building a fat APK that includes binaries for android-arm, android-arm64, android-x64.[0m
[11:34:23]: ▸ [35mIf you are deploying the app to the Play Store, it's recommended to use app bundles or split the APK to reduce the APK size.[0m
[11:34:23]: ▸ [35mTo generate an app bundle, run:[0m
[11:34:23]: ▸ [35mflutter build appbundle --target-platform android-arm,android-arm64,android-x64[0m
[11:34:23]: ▸ [35mLearn more on: https://developer.android.com/guide/app-bundle[0m
[11:34:23]: ▸ [35mTo split the APKs per ABI, run:[0m
[11:34:23]: ▸ [35mflutter build apk --target-platform android-arm,android-arm64,android-x64 --split-per-abi[0m
[11:34:23]: ▸ [35mLearn more on:  https://developer.android.com/studio/build/configure-apk-splits#configure-abi-split[0m
[11:36:09]: ▸ [35mRunning Gradle task 'assembleAlphaRelease'...[0m
[11:36:09]: ▸ [35m../../third_party/dart/runtime/vm/compiler/backend/il.h: 999: error: unreachable code[0m
[11:36:09]: ▸ [35mDart snapshot generator failed with exit code -6[0m
[11:36:09]: ▸ [35m../../third_party/dart/runtime/vm/compiler/backend/il.h: 999: error: unreachable code[0m
[11:36:09]: ▸ [35mDart snapshot generator failed with exit code -6[0m
[11:36:33]: ▸ [35mTarget android_aot_release_android-x64 failed: Exception: AOT snapshotter exited with code -6[0m
[11:36:33]: ▸ [35mTarget android_aot_release_android-arm64 failed: Exception: AOT snapshotter exited with code -6[0m
[11:36:33]: ▸ [35mbuild failed.[0m
[11:36:34]: ▸ [35mFAILURE: Build failed with an exception.[0m
[11:36:34]: ▸ [35m* Where:[0m
[11:36:34]: ▸ [35mScript '/Applications/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 882[0m
[11:36:34]: ▸ [35m* What went wrong:[0m
[11:36:34]: ▸ [35mExecution failed for task ':app:compileFlutterBuildAlphaRelease'.[0m
[11:36:34]: ▸ [35m> Process 'command '/Applications/flutter/bin/flutter'' finished with non-zero exit value 1[0m
[11:36:34]: ▸ [35m* Try:[0m
[11:36:34]: ▸ [35mRun with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.[0m
[11:36:34]: ▸ [35m* Get more help at https://help.gradle.org[0m
[11:36:34]: ▸ [35mBUILD FAILED in 2m 5s[0m
[11:36:34]: ▸ [35mRunning Gradle task 'assembleAlphaRelease'...                     131.0s (!)[0m
[11:36:34]: ▸ [35mGradle task assembleAlphaRelease failed with exit code 1[0m
+-----------------------------+----------+
|              [33mLane Context[0m              |
+-----------------------------+----------+
| PLATFORM_NAME               |          |
| LANE_NAME                   | ci_alpha |
| SIGH_PROFILE_PATHS          |          |
| DSYM_PATHS                  |          |
| GIT_REPO_WAS_CLEAN_ON_START | true     |
+-----------------------------+----------+
[11:36:34]: [31mExit status of command 'flutter build apk --release --flavor alpha -tlib/main_alpha.dart --build-number\=214' was 1 instead of 0.
You are building a fat APK that includes binaries for android-arm, android-arm64, android-x64.
If you are deploying the app to the Play Store, it's recommended to use app bundles or split the APK to reduce the APK size.
    To generate an app bundle, run:
        flutter build appbundle --target-platform android-arm,android-arm64,android-x64
        Learn more on: https://developer.android.com/guide/app-bundle
    To split the APKs per ABI, run:
        flutter build apk --target-platform android-arm,android-arm64,android-x64 --split-per-abi
        Learn more on:  https://developer.android.com/studio/build/configure-apk-splits#configure-abi-split
Running Gradle task 'assembleAlphaRelease'...                   
../../third_party/dart/runtime/vm/compiler/backend/il.h: 999: error: unreachable code

Dart snapshot generator failed with exit code -6

../../third_party/dart/runtime/vm/compiler/backend/il.h: 999: error: unreachable code

Dart snapshot generator failed with exit code -6

Target android_aot_release_android-x64 failed: Exception: AOT snapshotter exited with code -6

Target android_aot_release_android-arm64 failed: Exception: AOT snapshotter exited with code -6

build failed.



FAILURE: Build failed with an exception.



* Where:

Script '/Applications/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 882



* What went wrong:

Execution failed for task ':app:compileFlutterBuildAlphaRelease'.

> Process 'command '/Applications/flutter/bin/flutter'' finished with non-zero exit value 1



* Try:

Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.



* Get more help at https://help.gradle.org



BUILD FAILED in 2m 5s
```

```
[✓] Flutter (Channel stable, v1.17.1, on Mac OS X 10.15.4 19E266, locale en-GB)
    • Flutter version 1.17.1 at /Applications/flutter
    • Framework revision f7a6a7906b (7 days ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2
```

**Comment by mokhosh** [comment] 2020-05-25 11:04
I've been wrestling with the same problem for the last 3 days. I was getting errors that looked liked they're from my packages or gradle. I couldn't figure out the exact problem cause I got different errors with minor modifications so here's what I've tried:

- Updated all of my packages
- Tried `flutter clean`
- Tried different Gradle versions
- Created a new flutter project and moved my code over
- Upgraded flutter
- Downgraded flutter to different versions
- Deleted flutter and installed fresh

No luck

```
[✓] Flutter (Channel stable, v1.17.1, on Mac OS X 10.15.4 19E266, locale en-US)
    • Flutter version 1.17.1 at /Users/mokhosh/Android/flutter
    • Framework revision f7a6a7906b (12 days ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/mokhosh/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C505
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.2


[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```

**Comment by vanlooverenkoen** [comment] 2020-05-25 12:28
https://github.com/simolus3/moor/issues/581
Are you using moor?

**Comment by mokhosh** [comment] 2020-05-26 09:53
@vanlooverenkoen yesss, thank you

**Comment by jonahwilliams** [comment] 2020-05-26 14:14
Going to mark this as a duplicate of https://github.com/flutter/flutter/issues/57824 which is the same issue.

**Closed by jonahwilliams** 2020-05-26 14:14 UTC
Labels: a: build, platform-android, tool
