### ISSUE TITLE
Flutter Build Fail (After updating flutter above 2.06)

### ISSUE THREAD

**Issue by simeonangelov94** [flutter/flutter#83324] opened 2021-05-25 06:30 UTC
Hello, 

I would really appreciate if someone can assist me with this error after I update to a Flutter version above 2.06 Flutter is not able to complete build. My only solution was to downgrade to 2.06  to be able to continue developing my app. The app is currently in production on the App Store and Google Play and serves as a operational program for different companies.

I would really appreciate your help. Please find the error message below:

Flutter is already up to date on channel stable
Flutter 2.2.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision b22742018b (10 days ago) • 2021-05-14 19:12:57 -0700
Engine • revision a9d88a4d18
Tools • Dart 2.13.0

<details> 
<summary>logs</summary> 
	
```console
simeonangelov@JohnDoe-MacBook-Pro AppMaskedName % flutter build appbundle
Running "flutter pub get" in AppMaskedName...                  1,712ms

Building without sound null safety
For more information see https://dart.dev/null-safety/unsound-null-safety

../../../../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_windows-0.0.4+1/lib/src/path_provider_windows_real.dart:126:25: Error: The getter 'addressOf' isn't defined for the class 'GUID'.
 - 'GUID' is from 'package:win32/src/structs.dart' ('../../../../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/structs.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'addressOf'.
          knownFolderID.addressOf, KF_FLAG_DEFAULT, NULL, pathPtrPtr);  
                        ^^^^^^^^^                                       
../../../../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/structs.dart:1039:7: Error: The getter 'addressOf' isn't defined for the class 'LOGFONT'.
 - 'LOGFONT' is from 'package:win32/src/structs.dart' ('../../../../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/structs.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'addressOf'.
      addressOf.cast<Uint8>().elementAt(28).cast<Utf16>();              
      ^^^^^^^^^                                                         
../../../../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/structs.dart:1084:29: Error: The getter 'addressOf' isn't defined for the class 'ENUMLOGFONTEX'.
 - 'ENUMLOGFONTEX' is from 'package:win32/src/structs.dart' ('../../../../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/structs.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'addressOf'.
  LOGFONT get elfLogFont => addressOf.cast<LOGFONT>().ref;              
                            ^^^^^^^^^                                   
../../../../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/structs.dart:1086:29: Error: The getter 'addressOf' isn't defined for the class 'ENUMLOGFONTEX'.
 - 'ENUMLOGFONTEX' is from 'package:win32/src/structs.dart' ('../../../../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/structs.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'addressOf'.
  String get elfFullName => addressOf                                   
                            ^^^^^^^^^                                   
../../../../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/structs.dart:1092:26: Error: The getter 'addressOf' isn't defined for the class 'ENUMLOGFONTEX'.
 - 'ENUMLOGFONTEX' is from 'package:win32/src/structs.dart' ('../../../../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/structs.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'addressOf'.
  String get elfStyle => addressOf                                      
                         ^^^^^^^^^                                      
../../../../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/structs.dart:1098:27: Error: The getter 'addressOf' isn't defined for the class 'ENUMLOGFONTEX'.
 - 'ENUMLOGFONTEX' is from 'package:win32/src/structs.dart' ('../../../../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/structs.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'addressOf'.
  String get elfScript => addressOf                                     
                          ^^^^^^^^^                                     
../../../../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/structs.dart:2660:7: Error: The getter 'addressOf' isn't defined for the class 'OSVERSIONINFO'.
 - 'OSVERSIONINFO' is from 'package:win32/src/structs.dart' ('../../../../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/structs.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'addressOf'.
      addressOf.cast<Uint8>().elementAt(20).cast<Utf16>().unpackString(128);
      ^^^^^^^^^                                                         
../../../../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/structs.dart:2671:11: Error: The getter 'addressOf' isn't defined for the class 'OSVERSIONINFO'.
 - 'OSVERSIONINFO' is from 'package:win32/src/structs.dart' ('../../../../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/structs.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'addressOf'.
        ..addressOf.cast<Uint8>().elementAt(20).value = 0;              
          ^^^^^^^^^                                                     
../../../../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/structs.dart:2716:24: Error: The getter 'addressOf' isn't defined for the class 'BLUETOOTH_DEVICE_INFO'.
 - 'BLUETOOTH_DEVICE_INFO' is from 'package:win32/src/structs.dart' ('../../../../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/structs.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'addressOf'.
  String get szName => addressOf                                        
                       ^^^^^^^^^                                        
../../../../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/structs.dart:2809:7: Error: The getter 'addressOf' isn't defined for the class 'BLUETOOTH_PIN_INFO'.
 - 'BLUETOOTH_PIN_INFO' is from 'package:win32/src/structs.dart' ('../../../../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/structs.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'addressOf'.
      addressOf.cast<Uint8>().elementAt(BTH_MAX_PIN_SIZE).value;        
      ^^^^^^^^^                                                         
../../../../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/structs.dart:2812:5: Error: The getter 'addressOf' isn't defined for the class 'BLUETOOTH_PIN_INFO'.
 - 'BLUETOOTH_PIN_INFO' is from 'package:win32/src/structs.dart' ('../../../../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/structs.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'addressOf'.
    addressOf.cast<Uint8>().elementAt(BTH_MAX_PIN_SIZE).value =         
    ^^^^^^^^^                                                           
../../../../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/structs.dart:2817:28: Error: The getter 'addressOf' isn't defined for the class 'BLUETOOTH_PIN_INFO'.
 - 'BLUETOOTH_PIN_INFO' is from 'package:win32/src/structs.dart' ('../../../../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/structs.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'addressOf'.
      String.fromCharCodes(addressOf.cast<Uint8>().asTypedList(pinLength));
                           ^^^^^^^^^                                    
../../../../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/structs.dart:2825:7: Error: The getter 'addressOf' isn't defined for the class 'BLUETOOTH_PIN_INFO'.
 - 'BLUETOOTH_PIN_INFO' is from 'package:win32/src/structs.dart' ('../../../../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/structs.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'addressOf'.
      addressOf.cast<Uint8>().elementAt(idx).value = pinData[idx];      
      ^^^^^^^^^                                                         
../../../../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/com/combase.dart:38:31: Error: The getter 'addressOf' isn't defined for the class 'GUID'.
 - 'GUID' is from 'package:win32/src/structs.dart' ('../../../../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/structs.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'addressOf'.
  final iid = GUID.allocate().addressOf;                                
                              ^^^^^^^^^                                 
../../../../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/com/combase.dart:56:33: Error: The getter 'addressOf' isn't defined for the class 'GUID'.
 - 'GUID' is from 'package:win32/src/structs.dart' ('../../../../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/structs.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'addressOf'.
  final clsid = GUID.allocate().addressOf;                              
                                ^^^^^^^^^                               
../../../../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/winrt/winrt_helpers.dart:86:40: Error: The getter 'addressOf' isn't defined for the class 'GUID'.
 - 'GUID' is from 'package:win32/src/structs.dart' ('../../../../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/structs.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'addressOf'.
  final riidCalendar = GUID.allocate().addressOf;                       
                                       ^^^^^^^^^                        
../../../../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/generated/IDesktopWallpaper.dart:197:38: Error: The getter 'addressOf' isn't defined for the class 'COMObject'.
 - 'COMObject' is from 'package:win32/src/com/combase.dart' ('../../../../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/com/combase.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'addressOf'.
    final ptr = COMObject.allocate().addressOf;                         
                                     ^^^^^^^^^                          
../../../../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/generated/IDesktopWallpaper.dart:200:49: Error: The getter 'addressOf' isn't defined for the class 'GUID'.
 - 'GUID' is from 'package:win32/src/structs.dart' ('../../../../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/structs.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'addressOf'.
        GUID.fromString(CLSID_DesktopWallpaper).addressOf,              
                                                ^^^^^^^^^               
../../../../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/generated/IDesktopWallpaper.dart:203:48: Error: The getter 'addressOf' isn't defined for the class 'GUID'.
 - 'GUID' is from 'package:win32/src/structs.dart' ('../../../../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/structs.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'addressOf'.
        GUID.fromString(IID_IDesktopWallpaper).addressOf,               
                                               ^^^^^^^^^                
../../../../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/generated/IFileOpenDialog.dart:58:38: Error: The getter 'addressOf' isn't defined for the class 'COMObject'.
 - 'COMObject' is from 'package:win32/src/com/combase.dart' ('../../../../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/com/combase.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'addressOf'.
    final ptr = COMObject.allocate().addressOf;                         
                                     ^^^^^^^^^                          
../../../../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/generated/IFileOpenDialog.dart:61:47: Error: The getter 'addressOf' isn't defined for the class 'GUID'.
 - 'GUID' is from 'package:win32/src/structs.dart' ('../../../../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/structs.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'addressOf'.
        GUID.fromString(CLSID_FileOpenDialog).addressOf,                
                                              ^^^^^^^^^                 
../../../../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/generated/IFileOpenDialog.dart:64:46: Error: The getter 'addressOf' isn't defined for the class 'GUID'.
 - 'GUID' is from 'package:win32/src/structs.dart' ('../../../../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/structs.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'addressOf'.
        GUID.fromString(IID_IFileOpenDialog).addressOf,                 
                                             ^^^^^^^^^                  
../../../../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/generated/IFileSaveDialog.dart:99:38: Error: The getter 'addressOf' isn't defined for the class 'COMObject'.
 - 'COMObject' is from 'package:win32/src/com/combase.dart' ('../../../../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/com/combase.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'addressOf'.
    final ptr = COMObject.allocate().addressOf;                         
                                     ^^^^^^^^^                          
../../../../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/generated/IFileSaveDialog.dart:102:47: Error: The getter 'addressOf' isn't defined for the class 'GUID'.
 - 'GUID' is from 'package:win32/src/structs.dart' ('../../../../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/structs.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'addressOf'.
        GUID.fromString(CLSID_FileSaveDialog).addressOf,                
                                              ^^^^^^^^^                 
../../../../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/generated/IFileSaveDialog.dart:105:46: Error: The getter 'addressOf' isn't defined for the class 'GUID'.
 - 'GUID' is from 'package:win32/src/structs.dart' ('../../../../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/structs.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'addressOf'.
        GUID.fromString(IID_IFileSaveDialog).addressOf,                 
                                             ^^^^^^^^^                  
../../../../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/generated/IKnownFolderManager.dart:164:38: Error: The getter 'addressOf' isn't defined for the class 'COMObject'.
 - 'COMObject' is from 'package:win32/src/com/combase.dart' ('../../../../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/com/combase.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'addressOf'.
    final ptr = COMObject.allocate().addressOf;                         
                                     ^^^^^^^^^                          
../../../../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/generated/IKnownFolderManager.dart:167:51: Error: The getter 'addressOf' isn't defined for the class 'GUID'.
 - 'GUID' is from 'package:win32/src/structs.dart' ('../../../../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/structs.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'addressOf'.
        GUID.fromString(CLSID_KnownFolderManager).addressOf,            
                                                  ^^^^^^^^^             
../../../../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/generated/IKnownFolderManager.dart:170:50: Error: The getter 'addressOf' isn't defined for the class 'GUID'.
 - 'GUID' is from 'package:win32/src/structs.dart' ('../../../../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/structs.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'addressOf'.
        GUID.fromString(IID_IKnownFolderManager).addressOf,             
                                                 ^^^^^^^^^              
../../../../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/generated/INetworkListManager.dart:128:38: Error: The getter 'addressOf' isn't defined for the class 'COMObject'.
 - 'COMObject' is from 'package:win32/src/com/combase.dart' ('../../../../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/com/combase.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'addressOf'.
    final ptr = COMObject.allocate().addressOf;                         
                                     ^^^^^^^^^                          
../../../../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/generated/INetworkListManager.dart:131:51: Error: The getter 'addressOf' isn't defined for the class 'GUID'.
 - 'GUID' is from 'package:win32/src/structs.dart' ('../../../../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/structs.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'addressOf'.
        GUID.fromString(CLSID_NetworkListManager).addressOf,            
                                                  ^^^^^^^^^             
../../../../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/generated/INetworkListManager.dart:134:50: Error: The getter 'addressOf' isn't defined for the class 'GUID'.
 - 'GUID' is from 'package:win32/src/structs.dart' ('../../../../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/structs.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'addressOf'.
        GUID.fromString(IID_INetworkListManager).addressOf,             
                                                 ^^^^^^^^^              
../../../../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/generated/IWbemLocator.dart:82:38: Error: The getter 'addressOf' isn't defined for the class 'COMObject'.
 - 'COMObject' is from 'package:win32/src/com/combase.dart' ('../../../../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/com/combase.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'addressOf'.
    final ptr = COMObject.allocate().addressOf;                         
                                     ^^^^^^^^^                          
../../../../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/generated/IWbemLocator.dart:84:68: Error: The getter 'addressOf' isn't defined for the class 'GUID'.
 - 'GUID' is from 'package:win32/src/structs.dart' ('../../../../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/structs.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'addressOf'.
    final hr = CoCreateInstance(GUID.fromString(CLSID_WbemLocator).addressOf,
                                                                   ^^^^^^^^^
../../../../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/generated/IWbemLocator.dart:85:64: Error: The getter 'addressOf' isn't defined for the class 'GUID'.
 - 'GUID' is from 'package:win32/src/structs.dart' ('../../../../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/structs.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'addressOf'.
        nullptr, CLSCTX_ALL, GUID.fromString(IID_IWbemLocator).addressOf, ptr);
                                                               ^^^^^^^^^
../../../../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/ffi-0.1.3/lib/src/utf8.dart:63:33: Error: The getter 'addressOf' isn't defined for the class 'Utf8'.
 - 'Utf8' is from 'package:ffi/src/utf8.dart' ('../../../../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/ffi-0.1.3/lib/src/utf8.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'addressOf'.
  String toString() => fromUtf8(addressOf);                             
                                ^^^^^^^^^                               
../../../../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/structs.dart:1083:7: Error: Struct 'ENUMLOGFONTEX' is empty. Empty structs are undefined behavior.
class ENUMLOGFONTEX extends Struct {                                    
      ^                                                                 
../../../../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/structs.dart:2807:7: Error: Struct 'BLUETOOTH_PIN_INFO' is empty. Empty structs are undefined behavior.
class BLUETOOTH_PIN_INFO extends Struct {                               
      ^                                                                 
../../../../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/structs.dart:2932:7: Error: Struct 'EXCEPINFO' is empty. Empty structs are undefined behavior.
class EXCEPINFO extends Struct {}                                       
      ^                                                                 
../../../../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/structs.dart:2938:7: Error: Struct 'PROPERTYKEY' is empty. Empty structs are undefined behavior.
class PROPERTYKEY extends Struct {}                                     
      ^                                                                 
../../../../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/structs.dart:2945:7: Error: Struct 'PROPVARIANT' is empty. Empty structs are undefined behavior.
class PROPVARIANT extends Struct {}                                     
      ^                                                                 
../../../../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/structs.dart:2950:7: Error: Struct 'SAFEARRAY' is empty. Empty structs are undefined behavior.
class SAFEARRAY extends Struct {}                                       
      ^                                                                 
../../../../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/structs.dart:2957:7: Error: Struct 'CLSID' is empty. Empty structs are undefined behavior.
class CLSID extends Struct {}                                           
      ^                                                                 
../../../../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/structs.dart:2964:7: Error: Struct 'STATSTG' is empty. Empty structs are undefined behavior.
class STATSTG extends Struct {}                                         
      ^                                                                 
../../../../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/structs.dart:2971:7: Error: Struct 'NLM_SIMULATED_PROFILE_INFO' is empty. Empty structs are undefined behavior.
class NLM_SIMULATED_PROFILE_INFO extends Struct {}                      
      ^                                                                 
../../../../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/ffi-0.1.3/lib/src/utf8.dart:23:7: Error: Struct 'Utf8' is empty. Empty structs are undefined behavior.
class Utf8 extends Struct {                                             
      ^                                                                 
../../../../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/ffi-0.1.3/lib/src/utf16.dart:16:7: Error: Struct 'Utf16' is empty. Empty structs are undefined behavior.
class Utf16 extends Struct {                                            
      ^                                                                 
../../../../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/ffi-0.1.3/lib/src/allocation.dart:47:33: Error: Expected type 'T' to be a valid and instantiated subtype of 'NativeType'.
  final int totalSize = count * sizeOf<T>();                            
                                ^                                       
                                                                        
                                                                        
FAILURE: Build failed with an exception.                                
                                                                        
* Where:                                                                
Script '/Users/simeonangelov/Development/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 1035
                                                                        
* What went wrong:                                                      
Execution failed for task ':app:compileFlutterBuildRelease'.            
> Process 'command '/Users/JohnDoe/Development/flutter/bin/flutter'' finished with non-zero exit value 1
                                                                        
* Try:                                                                  
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
                                                                        
* Get more help at https://help.gradle.org                              
                                                                        
BUILD FAILED in 16s                                                     
Running Gradle task 'bundleRelease'...                                  
Running Gradle task 'bundleRelease'... Done                        17.6s
Gradle task bundleRelease failed with exit code 1

```

</details>

**Comment by Danish777** [comment] 2021-05-25 07:53
i am getting same issue

**Comment by simeonangelov94** [comment] 2021-05-25 07:57
I found a solution. Run flutter pub upgrade (which will upgrade all your dependencies). The dependency that creates an issue in my case was win32.  After I updated it everything ran smoothly.

Run (In this order)
- flutter pub upgrade
- flutter clean
- flutter pub get
- flutter run

**Comment by TahaTesser** [comment] 2021-05-25 08:39
Hi @simeonangelov94 
The error is caused by an outdated win32 cache, glad you resolved the issue. It will also help others
Given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you

**Closed by TahaTesser** 2021-05-25 08:39 UTC
Labels: in triage
