### ISSUE TITLE
[package] go_router_builder - does not generate code for ShellRoute

### ISSUE THREAD

**Issue by yev-velizhenkov-adroiti** [flutter/flutter#122120] opened 2023-03-07 19:01 UTC
go_router_builder
version: 1.1.4

@TypedShellRoute annotation does not yield in any code generation.

**Comment by huycozy** [comment] 2023-03-08 05:45
This was a known issue https://github.com/flutter/flutter/issues/111888 and it's a duplicate of https://github.com/flutter/flutter/issues/111909. Closing this issue as a duplicate, so please follow up on #111909 for further updates.

**Closed by huycozy** 2023-03-08 05:45 UTC
Labels: in triage
