### ISSUE TITLE
IntelliJ IDEA flutter plugin rename import as absolute path

### ISSUE THREAD

**Issue by dreamer2q** [flutter/flutter#66204] opened 2020-09-20 05:01 UTC
I am using `IntteliJ IDEA` with `flutter` plugin installed.

When I move a `dart` file from one directory to another, the plugin will automaticly `rename` related imports.

It seems to be working, but the plugin renamed the `import` from relative to absolute path which caused errors when compling from another environment with different project root.

I wish the plugin could handle this situation properly other than fixing it by hand.

ps: I do not know where to put this issue because I could not find any flutter issue related with jetbrain.

**Comment by TahaTesser** [comment] 2020-09-21 14:00
Hi @dreamer2q 
This is already an issue filed for this  https://github.com/flutter/flutter-intellij/issues/4740

Following the indication of [jetbrains' Flutter plugin](https://plugins.jetbrains.com/plugin/9212-flutter), the correct way to address the problem is to open an issue in the dedicated [repository](https://github.com/flutter/flutter-intellij/issues).
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2020-09-21 14:00 UTC
