### ISSUE TITLE
how to set proxy for flutter application

### ISSUE THREAD

**Issue by MeshkaniMohammad** [flutter/flutter#20704] opened 2018-08-16 18:26 UTC
Hi. I want to set a proxy for all of the connections of my app. how can I do this?
actually, I want to set proxy for firebase.

**Comment by zoechi** [comment] 2018-08-21 17:10
Did you try to get an answer on StackOverflow?

**Comment by MeshkaniMohammad** [comment] 2018-08-21 19:29
my account is blocked in stackoverflow and i can't find a way for my problem in stackoverflow!

**Comment by zoechi** [comment] 2018-12-10 10:00
Probably related to #20376

**Comment by zoechi** [comment] 2019-02-25 16:49
Duplicate of #26359

**Closed by zoechi** 2019-02-25 16:49 UTC
Labels: dependency: dart, engine, severe: new feature
