### ISSUE TITLE
Bad state: field does not exist within the DocumentSnapshotPlatform

### ISSUE THREAD

**Issue by dragonemperor03** [flutter/flutter#71720] opened 2020-12-04 14:43 UTC
The relevant error-causing widget was: 
  StreamBuilder<QuerySnapshot> file:///C:/drive1/test/lib/main.dart:99:12
When the exception was thrown, this was the stack: 
#0      DocumentSnapshotPlatform.get._findKeyValueInMap (package:cloud_firestore_platform_interface/src/platform_interface/platform_interface_document_snapshot.dart:82:7)
#1      DocumentSnapshotPlatform.get._findComponent (package:cloud_firestore_platform_interface/src/platform_interface/platform_interface_document_snapshot.dart:98:41)
#2      DocumentSnapshotPlatform.get (package:cloud_firestore_platform_interface/src/platform_interface/platform_interface_document_snapshot.dart:113:26)
#3      DocumentSnapshot.get (package:cloud_firestore/src/document_snapshot.dart:49:43)
#4      DocumentSnapshot.[] (package:cloud_firestore/src/document_snapshot.dart:56:41)
...

**Comment by TahaTesser** [comment] 2020-12-04 14:57
Hi @dragonemperor03 
From what I can see, the issue is related to a FlutterFire plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by TahaTesser** 2020-12-04 14:57 UTC
