### ISSUE TITLE
In landscape the screen reader does not seem accurate

### ISSUE THREAD

**Issue by Francesco-FL** [flutter/flutter#119212] opened 2023-01-26 04:02 UTC
I've been playing with the screen reader in portrait for a few hours, everything is ok. Then I noticed something a little strange, on my Android 12 Motorola g22 phone, when I rotate the device to landscape, the screen reader doesn't seem to read the button size correctly (and so do all the other elements, texts, icons , etc..)

![Screenshot_20230126-044820](https://user-images.githubusercontent.com/83022092/214755717-4f10cde5-100d-4ce5-beb7-2163d927880f.png)

```
TextButton(
  style: TextButton.styleFrom(
    padding: const EdgeInsets.fromLTRB(15, 10, 15, 10),
    foregroundColor: Colors.white,
    backgroundColor: MyThemes.colorButton(context),
    shape: StadiumBorder(side: BorderSide(color: MyThemes.colorButtonBorder(context))),
    minimumSize: const Size(48, 48),
  ),
  onPressed: () {},
  child: Text(
    "Fatto",
    textAlign: TextAlign.center,
    style: TextStyle(fontSize: 19),
  ),
),
```

```
[√] Flutter (Channel stable, 3.7.0, on Microsoft Windows [Versione 10.0.19045.2486], locale it-IT)
[X] Windows Version (Unable to confirm if installed Windows version is 10 or greater)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.3.3)
[√] Android Studio (version 2022.1)
[√] VS Code (version 1.74.3)
[√] Connected device (4 available)
[√] HTTP Host Availability
```

**Comment by danagbemava-nc** [comment] 2023-01-26 11:56
Hi @Francesco-FL, please provide a complete minimal reproducible code sample so that we can investigate this. 

Thank you

**Comment by Francesco-FL** [comment] 2023-01-26 13:15
Hi @danagbemava-nc, I reproduced the error even with a new default project. I attach the video.

https://user-images.githubusercontent.com/83022092/214844416-4de15efe-f5f2-4672-93c1-d350f2e50940.mp4

**Comment by danagbemava-nc** [comment] 2023-01-26 13:59
Hi @Francesco-FL, it turns out this is already known and is being tracked in https://github.com/flutter/flutter/issues/102725. 

Kindly follow up in the issue linked above for updates. 

Closing from here as duplicate. 

Thank you

**Closed by danagbemava-nc** 2023-01-26 13:59 UTC
Labels: in triage
