### ISSUE TITLE
Please support windows x86 release

### ISSUE THREAD

**Issue by xyun52** [flutter/flutter#111857] opened 2022-09-19 07:18 UTC
Some customers of small and medium-sized software companies still use x86 systems. We can't give them up because we have no choice. If our products do not support x86, customers will choose the products of competing companies. Flutter's main customers on Windows should be enterprise customers, and individual users usually only need one browser.

部分中小型软件公司的客户任然使用x86系统，我们不能放弃他们，因为我们没有选择，如果我们的产品不支持x86，客户就会选择竞争公司的产品。Flutter 在windows上的主要客户应该都是企业客户，个人用户通常只需要一个浏览器。

**Comment by stuartmorgan** [comment] 2022-09-19 11:03
Duplicate of https://github.com/flutter/flutter/issues/37777

**Closed by stuartmorgan** 2022-09-19 11:03 UTC
