### ISSUE TITLE
[tool_crash] StateError: Bad state: No element

### ISSUE THREAD

**Issue by shylendramadda** [flutter/flutter#73668] opened 2021-01-10 10:28 UTC
## Command
```
flutter --no-color run --machine --track-widget-creation --device-id=59dee86a --start-paused --dart-define=flutter.inspector.structuredErrors=true lib\main_dev.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
StateError: Bad state: No element
```
#0      ListMixin.firstWhere (dart:collection/list.dart:167:5)
#1      DartDevelopmentService.startDartDevelopmentService (package:flutter_tools/src/base/dds.dart:63:32)
<asynchronous suspension>
#2      FlutterDevice.connect.<anonymous closure> (package:flutter_tools/src/resident_runner.dart:249:11)
<asynchronous suspension>
```
```
[✓] Flutter (Channel beta, 1.25.0-8.1.pre, on Microsoft Windows [Version 10.0.18363.1256], locale en-IN)
    • Flutter version 1.25.0-8.1.pre at D:\Shylendra\Softwares\Flutter\flutter
    • Framework revision 8f89f6505b (4 weeks ago), 2020-12-15 15:07:52 -0800
    • Engine revision 92ae191c17
    • Dart version 2.12.0 (build 2.12.0-133.2.beta)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:/Users/shyle/AppData/Local/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:/Users/shyle/AppData/Local/Android/Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] IntelliJ IDEA Community Edition (version 2020.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.1.1
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.52.1)
    • VS Code at C:\Users\shyle\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • POCO F1 (mobile) • 59dee86a • android-arm64  • Android 10 (API 29)
    • Chrome (web)     • chrome   • web-javascript • Google Chrome 87.0.4280.88
    • Edge (web)       • edge     • web-javascript • Microsoft Edge 87.0.664.66

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: beta
**Creation framework version**: 2294d75bfa8d067ba90230c0fc2268f3636d7584
### Plugins
fluttertoast-7.1.6
path_provider_linux-0.0.1+2
path_provider_windows-0.0.4+3
shared_preferences-0.5.12+4
shared_preferences_linux-0.0.2+4
shared_preferences_macos-0.0.1+11
shared_preferences_web-0.1.2+7
shared_preferences_windows-0.0.1+3
url_launcher-5.7.10
url_launcher_linux-0.0.1+4
url_launcher_macos-0.0.1+9
url_launcher_web-0.1.5+1
url_launcher_windows-0.0.1+3

**Comment by iapicca** [comment] 2021-01-10 16:14
@shylendramadda 
this error is likely to depend from your implementation

```bash
#0      ListMixin.firstWhere (dart:collection/list.dart:167:5)
#1      DartDevelopmentService.startDartDevelopmentService (package:flutter_tools/src/base/dds.dart:63:32)
<asynchronous suspension>
#2      FlutterDevice.connect.<anonymous closure> (package:flutter_tools/src/resident_runner.dart:249:11)
<asynchronous suspension>
```

please provide a minimal reproducible code sample

**Comment by darshankawar** [comment] 2021-01-11 10:51
Closing this as a duplicate of https://github.com/flutter/flutter/issues/72385

**Closed by darshankawar** 2021-01-11 10:51 UTC
