### ISSUE TITLE
FractionallySizedBox doesn't set width correctly when in a Row.

### ISSUE THREAD

**Issue by stuz5000** [flutter/flutter#44733] opened 2019-11-12 17:37 UTC
I asked for 0.8 and 0.2 as the widths of the red and green boxes, and is render like this:

![image](https://user-images.githubusercontent.com/7799980/68695007-19a3fa00-052f-11ea-83dd-6ceef286b3bc.png)

Somehow the Row constrains the the total width to ~60% of the total width available to the Row. (You can check this by placing an expanded box in place of the fractionally sized boxes.

Same for tablet and web.

Other people have similar issues: https://stackoverflow.com/questions/57242651/using-fractionallysizedbox-in-a-row

```
import 'package:flutter/material.dart';

content() =>
    Column(children: [
      Text("Hello world2"),
      Row(children: [
//        Expanded(child:redbox()),  // Yes, 100% width
        Flexible(
            child: FractionallySizedBox(
                widthFactor: 0.8, child: greenbox(height: 100))),
        Flexible(
            child: FractionallySizedBox(
                widthFactor: 0.2, child: redbox(height: 100))),
      ]),
      Text("Hello world3"),
    ]);



greenbox({double height}) => Container(height:height, decoration: BoxDecoration(color: Colors.red));
redbox({double height=100.0}) => Container(height:height, decoration: BoxDecoration(color: Colors.green));

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) =>
      MaterialApp(
          title: 'Flutter Playground',
          home: Material(child: SafeArea(child: content())));
}

```
**Target Platform:**
**Target OS version/browser:**
**Devices:** Nexus7 2012, API 29. Chrome.

= `flutter doctor -v` =

```
[✓] Flutter (Channel master, v1.10.16-pre.68, on Linux, locale en_US.UTF-8)
    • Flutter version 1.10.16-pre.68 at /home/sir/development/flutter
    • Framework revision cb614d1339 (5 days ago), 2019-11-07 08:24:19 -0800
    • Engine revision c448d39d53
    • Dart version 2.7.0

 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/sir/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /home/sir/Android/Sdk
    • Java binary at: /home/sir/soft/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /home/sir/soft/android-studio
    • Flutter plugin version 41.0.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.2)
    • IntelliJ at /snap/intellij-idea-ultimate/181
    • Flutter plugin version 41.0.4
    • Dart plugin version 192.7402

[✓] Connected device (3 available)
    • Android SDK built for x86 • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Chrome                    • chrome        • web-javascript • Google Chrome 76.0.3809.132
    • Web Server                • web-server    • web-javascript • Flutter Tools

! Doctor found issues in 1 category.

```

**Comment by markusaksli-nc** [comment] 2020-08-27 14:35
The width allocated to each Flexible will be half of the Row. You can see this with this example:
<details>
 <summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

content() => Column(children: [
      Text("Hello world2"),
      Row(children: [
//        Expanded(child:redbox()),  // Yes, 100% width
        Flexible(
          child: greenbox(height: 100),
        ),
        Flexible(
          child: redbox(height: 100),
        ),
      ]),
      Text("Hello world3"),
    ]);

greenbox({double height}) => Container(height: height, color: Colors.red);

redbox({double height}) => Container(height: height, color: Colors.green);

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) => MaterialApp(
      title: 'Flutter Playground',
      home: Material(child: SafeArea(child: content())));
}
```
</details>

As stated in [`widthFactor`](https://master-api.flutter.dev/flutter/widgets/FractionallySizedBox/widthFactor.html)

> If non-null, the child is given a tight width constraint that is the max incoming width constraint multiplied by this factor.

This results in the width of the red box and green box in your example adding up to `0.5 x 0.8 + 0.5 * 0.2 = 0.5`. This is the expected behavior.
FractionallySizedBox isn't even necessary here. Flexible already has a property to assign the proportion of the available flexible space you want to use. 

All you need to do to achieve the intended goal is to use the [`flex`](https://master-api.flutter.dev/flutter/widgets/Flexible/flex.html) property of Flexible.

<details>
 <summary>Solution code sample</summary>

```dart
import 'package:flutter/material.dart';

content() => Column(children: [
      Text("Hello world2"),
      Row(children: [
//        Expanded(child:redbox()),  // Yes, 100% width
        Flexible(
          flex: 8,
          child: greenbox(height: 100),
        ),
        Flexible(
          flex: 2,
          child: redbox(height: 100),
        ),
      ]),
      Text("Hello world3"),
    ]);

greenbox({double height}) => Container(height: height, color: Colors.red);

redbox({double height}) => Container(height: height, color: Colors.green);

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) => MaterialApp(
      title: 'Flutter Playground',
      home: Material(child: SafeArea(child: content())));
}
```
</details>

Closing since this isn't an issue with Flutter and is clearly documented in the relevant widgets.

**Closed by markusaksli-nc** 2020-08-27 14:35 UTC
Labels: framework, severe: rendering
