### ISSUE TITLE
NXTGEN

### ISSUE THREAD

**Issue by eduardoflorendo** [flutter/flutter#42625] opened 2019-10-14 05:39 UTC

**Comment by janmoppel** [comment] 2019-10-14 06:22
Hello @eduardoflorendo !

Thank you for posting.
However, without any additional information, such as the description of the problem, code to reproduce the issue and `flutter doctor -v` command output, your case cannot be investigated. Due to that, closing this issue.

But feel free to open a new issue and fill the information requested in the template.

Thank you.

**Closed by janmoppel** 2019-10-14 06:22 UTC
