### ISSUE TITLE
Running Gradle task 'assembleRelease' is failing on builder

### ISSUE THREAD

**Issue by yusuf-goog** [flutter/flutter#104747] opened 2022-05-26 20:30 UTC
mac-18 phone ha a bloated battery.

**Comment by yusuf-goog** [comment] 2022-05-26 21:08
Need to get tools from other lab to swap out the battery, will do it next time in the lab.

**Comment by keyonghan** [comment] 2022-06-15 21:17
Manually quarantine this test bed as this is causing tests flaky.
https://github.com/flutter/flutter/issues/105715
https://github.com/flutter/flutter/issues/106032

**Comment by yusuf-goog** [comment] 2022-06-15 21:40
@keyonghan  is it only this device thats causing the issues? Do other testbeds run this successfully?

**Comment by keyonghan** [comment] 2022-06-15 21:52
Right, all flakes happened on this bot, which sounds related to the battery issue.

**Comment by yusuf-goog** [comment] 2022-06-15 21:57
I swapped out the battery from a similar phone. I'm not sure if the battery could be causing these issues? We should just remove this phone entirely if this continues.

**Comment by keyonghan** [comment] 2022-06-22 22:31
Cleaned up cache on mac-18, and remove quarantine file.
Let's monitor the runs, and can move back to prod if no issue repro.

**Comment by ricardoamador** [comment] 2022-06-22 23:47
Sounds good.

**Comment by ricardoamador** [comment] 2022-06-28 19:15
Bot has been merged back to the production pool.

**Comment by ricardoamador** [comment] 2022-06-29 16:23
Okay. I can take a look.

**Comment by ricardoamador** [comment] 2022-06-30 00:21
We are seeing the following error only within the prod environment on this bot:
```
[STDOUT] run: starting...
[run_release_test] [STDOUT] Executing "/opt/s/w/ir/x/w/recipe_cleanup/tmpn8di3437/flutter sdk/bin/flutter --suppress-analytics run --release -d ZY2245NMBT lib/main.dart" in "/opt/s/w/ir/x/w/recipe_cleanup/tmpn8di3437/flutter sdk/dev/integration_tests/ui" with environment {BOT: false, LANG: en_US.UTF-8}
[run_release_test] [STDOUT] run:stdout: Running "flutter pub get" in ui...                               2,323ms
[run_release_test] [STDOUT] run:stdout: Launching lib/main.dart on Moto G 4 in release mode...
[run_release_test] [STDOUT] run:stdout: Running Gradle task 'assembleRelease'...                        
[run_release_test] [STDOUT] run:stderr: Warning: unexpected element (uri:"", local:"base-extension"). Expected elements are <{}codename>,<{}layoutlib>,<{}api-level>
[run_release_test] [STDOUT] run:stdout: Running Gradle task 'assembleRelease'...                           80.6s
[run_release_test] [STDOUT] run:stdout: ✓  Built build/app/outputs/flutter-apk/app-release.apk (5.9MB).
[run_release_test] [STDOUT] run:stdout: Installing build/app/outputs/flutter-apk/app.apk...              2,649ms
[run_release_test] [STDOUT] run:stdout: 
[run_release_test] [STDOUT] run:stdout: Flutter run key commands.
[run_release_test] [STDOUT] run:stdout: h List all available interactive commands.
[run_release_test] [STDOUT] run:stdout: c Clear the screen
[run_release_test] [STDOUT] run:stdout: q Quit (terminate the application on the device).
[run_release_test] [STDOUT] run:stdout: 
```

This is happening within gradle. Possible differences in versions between staging and prod.
Here is the last successful run from when the bot was in the staging pool: 
https://chromium-swarm.appspot.com/task?d=true&id=5bc136debf34c410

And here is the last failure run of the same test from when the bot was moved to the prod pool:
https://chromium-swarm.appspot.com/task?d=true&id=5bc4f221fe126110 

It also appears that the version of the android sdk and different for both runs as well as the cache that is being used for each environment.

@GaryQian Can you help me identify the gradle version for each run?

**Comment by GaryQian** [comment] 2022-08-09 17:40
Root issue is a dupe of https://github.com/flutter/flutter/issues/105715.

**Closed by GaryQian** 2022-08-09 17:40 UTC
Labels: platform-android, team: infra
