### ISSUE TITLE
Running Gradle task 'assembleDebug'..

### ISSUE THREAD

**Issue by Karthikdezarvo** [flutter/flutter#97947] opened 2022-02-07 10:40 UTC
Launching lib/main.dart on sdk gphone x86 in debug mode...
Running Gradle task 'assembleDebug'...
../../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/platform-3.0.2/lib/src/interface/local_platform.dart:46:19: Error: Member not found: 'packageRoot'.
      io.Platform.packageRoot; // ignore: deprecated_member_use
                  ^^^^^^^^^^^

FAILURE: Build failed with an exception.

* Where:
Script '/Users/apple/development/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 1102

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command '/Users/apple/development/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 28s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by stuartmorgan** [comment] 2022-02-07 10:47
Please file issues with packages against the developer of the package.

However, the issue here is just that you are using a version of `platform` that is too old. Duplicate of https://github.com/flutter/flutter/issues/96711

**Closed by stuartmorgan** 2022-02-07 10:47 UTC
