### ISSUE TITLE
Emoji are not displayed with FontWeight.bold

### ISSUE THREAD

**Issue by najeira** [flutter/flutter#12624] opened 2017-10-19 07:45 UTC
## Steps to Reproduce

Set FontWeight.bold to Text's style. Emoji are not displayed.

```dart
void main() {
  runApp(new MaterialApp(
    home: new Scaffold(
      appBar: new AppBar(
        title: const Text('Emoji'),
      ),
      body: new Container(
        padding: const EdgeInsets.all(20.0),
        child: new Column(
          children: <Widget>[
            new Text('normal 😀 💪 emoji'),
            new Text('bold 😀 💪 emoji',
              style: const TextStyle(fontWeight: FontWeight.bold)),
          ],
        ),
      ),
    ),
  ));
}
```

## Flutter Doctor

```
[✓] Flutter (on Mac OS X 10.12.6 16G29, locale ja-JP, channel master)
    • Flutter at /Applications/flutter
    • Framework revision 79fbf8bb03 (4 hours ago), 2017-10-18 20:55:00 -0700
    • Engine revision 7c4142808c
    • Tools Dart version 1.25.0-dev.11.0

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.1)
    • Android SDK at /Users/najeira/Library/Android/sdk
    • Platform android-26, build-tools 26.0.1
    • ANDROID_HOME = /Users/najeira/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 9.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.0, Build version 9A235
    • ios-deploy 1.9.2
    • CocoaPods version 1.2.1

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Ultimate Edition (version 2017.2.1)
    • Flutter plugin version 16.0
    • Dart plugin version 172.3544.34
```

**Comment by jason-simmons** [comment] 2017-10-19 17:34
Duplicate of https://github.com/flutter/flutter/issues/11108

**Closed by jason-simmons** 2017-10-19 17:34 UTC
