### ISSUE TITLE
App Freezes, Heap Memory Allocation Issue

### ISSUE THREAD

**Issue by karansamant18** [flutter/flutter#140459] opened 2023-12-20 18:03 UTC
I have 4 modules in bottom nav bar, whenever i come on this particular module after scrolling the app for a bit, the app freezes showing unusual memory surges in dev tools. Dart heap crosses 1gb.
![IMG_6986](https://github.com/flutter/flutter/assets/90305792/fdd02ef5-fb06-49ed-b01c-0ec93139bf7c)

**Comment by dam-ease** [comment] 2023-12-21 07:52
Hi @karansamant18  
When opening an issue, please try to provide all or some of the information indicated in the template so that we can address this issue properly.
More specifically, please provide the information indicated below:


- A [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
- The output of flutter doctor -v
- Reproduction steps


I am closing this issue since little or no information has been provided. Once you update the issue with more information, please write in the comments and I will re-open this for further discussion. Thanks!

**Closed by dam-ease** 2023-12-21 07:52 UTC
Labels: in triage
