### ISSUE TITLE
 CMake Error at CMakeLists.txt:51 (include): flutter/generated_plugins.cmake

### ISSUE THREAD

**Issue by Andrious** [flutter/flutter#94874] opened 2021-12-08 18:27 UTC
The first attempt to migrate an existing Flutter project to Flutter desktop results in this error:

```
CMake Error at CMakeLists.txt:51 (include):
[   +2 ms]   include could not find requested file:
[        ]     flutter/generated_plugins.cmake
```

<details>
<summary> $ flutter build windows -v </summary>

```
Microsoft Windows [Version 10.0.19042.1348]
(c) Microsoft Corporation. All rights reserved.

C:\Programs\Tools\Projects\Flutter\packages\app_template>flutter build windows -v
[  +75 ms] executing: [C:\Programs\Tools\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +60 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 18116933e77adc82f80866c928266a5b4f1ed645
[   +1 ms] executing: [C:\Programs\Tools\flutter/] git tag --points-at 18116933e77adc82f80866c928266a5b4f1ed645
[  +44 ms] Exit code 0 from: git tag --points-at 18116933e77adc82f80866c928266a5b4f1ed645
[        ] 2.5.3
[   +9 ms] executing: [C:\Programs\Tools\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +34 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[   +1 ms] executing: [C:\Programs\Tools\flutter/] git ls-remote --get-url origin
[  +32 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter.git
[ +106 ms] executing: [C:\Programs\Tools\flutter/] git rev-parse --abbrev-ref HEAD
[  +34 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +70 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +56 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[   +4 ms] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[  +64 ms] Skipping pub get: version match.
[  +48 ms]  Building with sound null safety 
[  +16 ms] executing: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe -format json -products * -utf8
-latest -version 16 -requires Microsoft.VisualStudio.Workload.NativeDesktop
Microsoft.VisualStudio.Component.VC.Tools.x86.x64 Microsoft.VisualStudio.Component.VC.CMake.Project
[  +42 ms] Exit code 0 from: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe -format json -products
* -utf8 -latest -version 16 -requires Microsoft.VisualStudio.Workload.NativeDesktop
Microsoft.VisualStudio.Component.VC.Tools.x86.x64 Microsoft.VisualStudio.Component.VC.CMake.Project
[   +1 ms] [
             {
               "instanceId": "771292ac",
               "installDate": "2021-12-08T02:08:59Z",
               "installationName": "VisualStudio/16.11.7+31911.196",
               "installationPath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community",
               "installationVersion": "16.11.31911.196",
               "productId": "Microsoft.VisualStudio.Product.Community",
               "productPath": "C:\\Program Files (x86)\\Microsoft Visual
               Studio\\2019\\Community\\Common7\\IDE\\devenv.exe",
               "state": 4294967295,
               "isComplete": true,
               "isLaunchable": true,
               "isPrerelease": false,
               "isRebootRequired": false,
               "displayName": "Visual Studio Community 2019",
               "description": "Powerful IDE, free for students, open-source contributors, and individuals",
               "channelId": "VisualStudio.16.Release",
               "channelUri": "https://aka.ms/vs/16/release/channel",
               "enginePath": "C:\\Program Files (x86)\\Microsoft Visual
               Studio\\Installer\\resources\\app\\ServiceHub\\Services\\Microsoft.VisualStudio.Setup.Service",
               "releaseNotes":
               "https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes-v16.11#16.11.7",
               "thirdPartyNotices": "https://go.microsoft.com/fwlink/?LinkId=660909",
               "updateDate": "2021-12-08T02:08:59.0636021Z",
               "catalog": {
                 "buildBranch": "d16.11",
                 "buildVersion": "16.11.31911.196",
                 "id": "VisualStudio/16.11.7+31911.196",
                 "localBuild": "build-lab",
                 "manifestName": "VisualStudio",
                 "manifestType": "installer",
                 "productDisplayVersion": "16.11.7",
                 "productLine": "Dev16",
                 "productLineVersion": "2019",
                 "productMilestone": "RTW",
                 "productMilestoneIsPreRelease": "False",
                 "productName": "Visual Studio",
                 "productPatchVersion": "7",
                 "productPreReleaseMilestoneSuffix": "1.0",
                 "productSemanticVersion": "16.11.7+31911.196",
                 "requiredEngineVersion": "2.11.52.58712"
               },
               "properties": {
                 "campaignId": "93655477.1637857534",
                 "channelManifestId": "VisualStudio.16.Release/16.11.7+31911.196",
                 "nickname": "",
                 "setupEngineFilePath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\Installer\\setup.exe"
               }
             }
           ]
[   +5 ms] Building Windows application...
[   +6 ms] executing: C:\Program Files (x86)\Microsoft Visual
Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe -S
C:\Programs\Tools\Projects\Flutter\packages\app_template\windows -B build\windows -G Visual Studio 16 2019
[  +72 ms] -- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19042.
[  +85 ms] CMake Error at CMakeLists.txt:51 (include):
[   +2 ms]   include could not find requested file:
[        ]     flutter/generated_plugins.cmake
[   +1 ms] -- Configuring incomplete, errors occurred!
[        ] See also "C:/Programs/Tools/Projects/Flutter/packages/app_template/build/windows/CMakeFiles/CMakeOutput.log".
[  +18 ms] Building Windows application... (completed in 176ms)
[   +1 ms] "flutter windows" took 482ms.
[   +3 ms] Unable to generate build files
[   +1 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      _runCmakeGeneration (package:flutter_tools/src/windows/build_windows.dart:257:5)
           <asynchronous suspension>
           #2      buildWindows (package:flutter_tools/src/windows/build_windows.dart:77:5)
           <asynchronous suspension>
           #3      BuildWindowsCommand.runCommand (package:flutter_tools/src/commands/build_windows.dart:55:5)
           <asynchronous suspension>
           #4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1125:27)
           <asynchronous suspension>
           #5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #6      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
           <asynchronous suspension>
           #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #9      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
           <asynchronous suspension>
           #10     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #12     main (package:flutter_tools/executable.dart:92:3)
           <asynchronous suspension>
           
           
[   +3 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1

```
</details>

imgur graphic:
[Visual Studio Workloads installed](https://imgur.com/a/Rod8paz)

flutter doctor -v
```
[√] Flutter (Channel stable, 2.5.3, on Microsoft Windows [Version 10.0.19042.1348], locale en-CA)
    • Flutter version 2.5.3 at C:\Programs\Tools\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (8 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Programs\Tools\Android\SDK
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = C:\Programs\Tools\Android\SDK
    • Java binary at: C:\Programs\Tools\Android\Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.7)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31911.196
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Programs\Tools\Android\Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] IntelliJ IDEA Community Edition (version 2019.1)
    • IntelliJ at C:\Programs\Tools\Dart\IntelliJ
    • Flutter plugin version 35.0.3
    • Dart plugin version 191.7019

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19042.1348]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 96.0.4664.45
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 96.0.1054.34

• No issues found!
```

**Comment by darshankawar** [comment] 2021-12-09 07:46
```
`[   +6 ms] executing: C:\Program Files (x86)\Microsoft Visual
Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe -S
C:\Programs\Tools\Projects\Flutter\packages\app_template\windows -B build\windows -G Visual Studio 16 2019
[  +72 ms] -- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19042.
[  +85 ms] CMake Error at CMakeLists.txt:51 (include):
[   +2 ms]   include could not find requested file:
[        ]     flutter/generated_plugins.cmake
[   +1 ms] -- Configuring incomplete, errors occurred!
[        ] See also "C:/Programs/Tools/Projects/Flutter/packages/app_template/build/windows/CMakeFiles/CMakeOutput.log".
[  +18 ms] Building Windows application... (completed in 176ms)
[   +1 ms] "flutter windows" took 482ms.
[   +3 ms] Unable to generate build file`
```

Can you provide us the log generated at `windows/CMakeFiles/CMakeOutput.log"` ?

**Comment by Andrious** [comment] 2021-12-09 18:36
CMakeOutput.log
```js
The system is: Windows - 10.0.19042 - AMD64
Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
Compiler:  
Build flags: 
Id flags:  

The output was:
0
Microsoft (R) Build Engine version 16.11.2+f32259642 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 2021-12-08 12:49:37 AM.
Project "C:\Programs\Tools\Projects\Flutter\packages\app_template\build\windows\CMakeFiles\3.20.21032501-MSVC_2\CompilerIdCXX\CompilerIdCXX.vcxproj" on node 1 (default targets).
PrepareForBuild:
  Creating directory "Debug\".
  Creating directory "Debug\CompilerIdCXX.tlog\".
InitializeBuildStatus:
  Creating "Debug\CompilerIdCXX.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
ClCompile:
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\" /Fd"Debug\vc142.pdb" /external:W0 /Gd /TP /FC /errorReport:queue CMakeCXXCompilerId.cpp
  CMakeCXXCompilerId.cpp
Link:
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64\link.exe /ERRORREPORT:QUEUE /OUT:".\CompilerIdCXX.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\CompilerIdCXX.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\CompilerIdCXX.lib" /MACHINE:X64 Debug\CMakeCXXCompilerId.obj
  CompilerIdCXX.vcxproj -> C:\Programs\Tools\Projects\Flutter\packages\app_template\build\windows\CMakeFiles\3.20.21032501-MSVC_2\CompilerIdCXX\CompilerIdCXX.exe
PostBuildEvent:
  for %%i in (cl.exe) do @echo CMAKE_CXX_COMPILER=%%~$PATH:i
  :VCEnd
  CMAKE_CXX_COMPILER=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\Hostx64\x64\cl.exe
FinalizeBuildStatus:
  Deleting file "Debug\CompilerIdCXX.tlog\unsuccessfulbuild".
  Touching "Debug\CompilerIdCXX.tlog\CompilerIdCXX.lastbuildstate".
Done Building Project "C:\Programs\Tools\Projects\Flutter\packages\app_template\build\windows\CMakeFiles\3.20.21032501-MSVC_2\CompilerIdCXX\CompilerIdCXX.vcxproj" (default targets).

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:01.06


Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.exe"

Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.vcxproj"

The CXX compiler identification is MSVC, found in "C:/Programs/Tools/Projects/Flutter/packages/app_template/build/windows/CMakeFiles/3.20.21032501-MSVC_2/CompilerIdCXX/CompilerIdCXX.exe"

Detecting CXX compiler ABI info compiled with the following output:
Change Dir: C:/Programs/Tools/Projects/Flutter/packages/app_template/build/windows/CMakeFiles/CMakeTmp

Run Build Command(s):C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/MSBuild/Current/Bin/MSBuild.exe cmTC_f9917.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=16.0 /v:m && Microsoft (R) Build Engine version 16.11.2+f32259642 for .NET Framework

Copyright (C) Microsoft Corporation. All rights reserved.



  Microsoft (R) C/C++ Optimizing Compiler Version 19.29.30137 for x64

  Copyright (C) Microsoft Corporation.  All rights reserved.

  CMakeCXXCompilerABI.cpp

  cl /c /Zi /W1 /WX- /diagnostics:column /Od /Ob0 /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_f9917.dir\Debug\\" /Fd"cmTC_f9917.dir\Debug\vc142.pdb" /external:W1 /Gd /TP /errorReport:queue "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\share\cmake-3.20\Modules\CMakeCXXCompilerABI.cpp"

  cmTC_f9917.vcxproj -> C:\Programs\Tools\Projects\Flutter\packages\app_template\build\windows\CMakeFiles\CMakeTmp\Debug\cmTC_f9917.exe
```

**Comment by darshankawar** [comment] 2021-12-10 05:35
The build seemed to have succeeded:

```
Build succeeded.
    0 Warning(s)
    0 Error(s)
```
have you already tried `flutter clean` and then `flutter pub get` to properly have all dependencies ?

**Comment by Andrious** [comment] 2021-12-10 06:10
> have you already tried `flutter clean` and then `flutter pub get` to properly have all dependencies ?

Yes, I did.

The error describes an issue within the file, `windows/CMakeLists.txt`.  There's an 'include' file missing called `generated_plugins.cmake`. I suspect its job is to list all the plugins used by the app.

The problem is that file is not being generated.

I suspect it's because I did not install all the workloads: [Visual Studio Workloads installed
](https://imgur.com/a/Rod8paz)

I'll attempt to install all the workloads, however, I don't want to if I don't need to.
I only want to install what is required---I'm not a fan of 'bloatware.'

There's an arrow beside the include function that fails in the file, `windows/CMakeLists.txt`. 

```sh
cmake_minimum_required(VERSION 3.15)
project(app_template LANGUAGES CXX)

set(BINARY_NAME "app_template")

cmake_policy(SET CMP0063 NEW)

set(CMAKE_INSTALL_RPATH "$ORIGIN/lib")

# Configure build options.
get_property(IS_MULTICONFIG GLOBAL PROPERTY GENERATOR_IS_MULTI_CONFIG)
if(IS_MULTICONFIG)
  set(CMAKE_CONFIGURATION_TYPES "Debug;Profile;Release"
    CACHE STRING "" FORCE)
else()
  if(NOT CMAKE_BUILD_TYPE AND NOT CMAKE_CONFIGURATION_TYPES)
    set(CMAKE_BUILD_TYPE "Debug" CACHE
      STRING "Flutter build mode" FORCE)
    set_property(CACHE CMAKE_BUILD_TYPE PROPERTY STRINGS
      "Debug" "Profile" "Release")
  endif()
endif()

set(CMAKE_EXE_LINKER_FLAGS_PROFILE "${CMAKE_EXE_LINKER_FLAGS_RELEASE}")
set(CMAKE_SHARED_LINKER_FLAGS_PROFILE "${CMAKE_SHARED_LINKER_FLAGS_RELEASE}")
set(CMAKE_C_FLAGS_PROFILE "${CMAKE_C_FLAGS_RELEASE}")
set(CMAKE_CXX_FLAGS_PROFILE "${CMAKE_CXX_FLAGS_RELEASE}")

# Use Unicode for all projects.
add_definitions(-DUNICODE -D_UNICODE)

# Compilation settings that should be applied to most targets.
function(APPLY_STANDARD_SETTINGS TARGET)
  target_compile_features(${TARGET} PUBLIC cxx_std_17)
  target_compile_options(${TARGET} PRIVATE /W4 /WX /wd"4100")
  target_compile_options(${TARGET} PRIVATE /EHsc)
  target_compile_definitions(${TARGET} PRIVATE "_HAS_EXCEPTIONS=0")
  target_compile_definitions(${TARGET} PRIVATE "$<$<CONFIG:Debug>:_DEBUG>")
endfunction()

set(FLUTTER_MANAGED_DIR "${CMAKE_CURRENT_SOURCE_DIR}/flutter")

# Flutter library and tool build rules.
add_subdirectory(${FLUTTER_MANAGED_DIR})

# Application build
add_subdirectory("runner")

# Generated plugin build rules, which manage building the plugins and adding
# them to the application.
include(flutter/generated_plugins.cmake)             <-----


# === Installation ===
# Support files are copied into place next to the executable, so that it can
# run in place. This is done instead of making a separate bundle (as on Linux)
# so that building and running from within Visual Studio will work.
set(BUILD_BUNDLE_DIR "$<TARGET_FILE_DIR:${BINARY_NAME}>")
# Make the "install" step default, as it's required to run.
set(CMAKE_VS_INCLUDE_INSTALL_TO_DEFAULT_BUILD 1)
if(CMAKE_INSTALL_PREFIX_INITIALIZED_TO_DEFAULT)
  set(CMAKE_INSTALL_PREFIX "${BUILD_BUNDLE_DIR}" CACHE PATH "..." FORCE)
endif()

set(INSTALL_BUNDLE_DATA_DIR "${CMAKE_INSTALL_PREFIX}/data")
set(INSTALL_BUNDLE_LIB_DIR "${CMAKE_INSTALL_PREFIX}")

install(TARGETS ${BINARY_NAME} RUNTIME DESTINATION "${CMAKE_INSTALL_PREFIX}"
  COMPONENT Runtime)

install(FILES "${FLUTTER_ICU_DATA_FILE}" DESTINATION "${INSTALL_BUNDLE_DATA_DIR}"
  COMPONENT Runtime)

install(FILES "${FLUTTER_LIBRARY}" DESTINATION "${INSTALL_BUNDLE_LIB_DIR}"
  COMPONENT Runtime)

if(PLUGIN_BUNDLED_LIBRARIES)
  install(FILES "${PLUGIN_BUNDLED_LIBRARIES}"
    DESTINATION "${INSTALL_BUNDLE_LIB_DIR}"
    COMPONENT Runtime)
endif()

# Fully re-copy the assets directory on each build to avoid having stale files
# from a previous install.
set(FLUTTER_ASSET_DIR_NAME "flutter_assets")
install(CODE "
  file(REMOVE_RECURSE \"${INSTALL_BUNDLE_DATA_DIR}/${FLUTTER_ASSET_DIR_NAME}\")
  " COMPONENT Runtime)
install(DIRECTORY "${PROJECT_BUILD_DIR}/${FLUTTER_ASSET_DIR_NAME}"
  DESTINATION "${INSTALL_BUNDLE_DATA_DIR}" COMPONENT Runtime)

# Install the AOT library on non-Debug builds only.
install(FILES "${AOT_LIBRARY}" DESTINATION "${INSTALL_BUNDLE_DATA_DIR}"
  CONFIGURATIONS Profile;Release
  COMPONENT Runtime)
```

**Comment by darshankawar** [comment] 2021-12-10 06:37
Thanks for the update. Labeling it for further insights from the team.

/cc @stuartmorgan

**Comment by stuartmorgan** [comment] 2021-12-10 11:08
> The first attempt to migrate an existing Flutter project to Flutter desktop results in this error

How exactly did you do this migration? I.e., what specific command(s) did you run in your existing project?

> I suspect it's because I did not install all the workloads: [Visual Studio Workloads installed](https://imgur.com/a/Rod8paz)

Generation of that file does not involve Visual Studio at all. It's entirely internal to the `flutter` tooling.

**Comment by Andrious** [comment] 2021-12-10 17:24
> How exactly did you do this migration? I.e., what specific command(s) did you run in your existing project?

I merely followed the provided instructions to do so:  `flutter create --platforms=windows`  
Subsequently, the subdirectory, `windows`, is created. Reference: [Add desktop support to an existing Flutter app](https://docs.flutter.dev/desktop#add-desktop-support-to-an-existing-flutter-app)

> Generation of that file does not involve Visual Studio at all. It's entirely internal to the `flutter` tooling.

Entirely internal to the 'flutter' tooling? 
Where and when is that file,`generated_plugins.cmake`, then generated?

**Comment by stuartmorgan** [comment] 2021-12-14 16:57
> > How exactly did you do this migration? I.e., what specific command(s) did you run in your existing project?
> 
> I merely followed the provided instructions to do so: `flutter create --platforms=windows`

That should definitely have generated the file then.

I'm wondering if there's been a higher-level regression in the triggering of running `injectPlugins`, because https://github.com/flutter/flutter/issues/95236 is a case where a plugin that should have been generated by `injectPlugins` is missing. /cc @christopherfujino

**Comment by YowFung** [comment] 2021-12-16 09:13
I have the same problem. Share my experience, which may be helpful for everyone to reproduce the problem.

As #95236 said, first, the `Podfile` file has not been generated after `flutter run -d macos` on macOS. I had to create a new project and then add the same third-party plug-in, which is no problem. Next, I transferred the code that had no problem on macOS to Windows, and then I got the same problem as you.

I don't know if it is related to IDEA, but it is still invalid when executing commands on the terminal.

**Comment by YowFung** [comment] 2021-12-22 08:21
Perhaps for this reason: https://github.com/flutter/flutter/issues/95236#issuecomment-999374732

**Comment by christopherfujino** [comment] 2021-12-28 22:17
cc @HansMuller for triage as a desktop bug

**Comment by stuartmorgan** [comment] 2022-01-04 15:38
This is likely not just a desktop bug, since the codepath that triggers generation of plugin files covers all platforms.

**Comment by Andrious** [comment] 2022-02-12 22:12
> Do you by any chance have a directory called "example" in this project? We recently fixed a bug where the presence of an `example` directory caused these files not to be generated.

Yes, yes it does have an 'example' directory.

With this latest Flutter update, would another attempt will be successful?

I've set that project aside for 2 months, and 2 days now.

A successful attempt will make my weekend.

I'll give it a try shortly and let you know.

Greg

**Closed** 2022-02-12 22:24 UTC
Labels: tool, plugin, platform-windows, a: desktop, a: build, passed first triage, passed secondary triage, P4

**Comment by jrwenigma** [comment] 2022-02-18 21:51
I have the same issue as @Andrious and don't have an "example" folder, did anyone find a solution?
