### ISSUE TITLE
CupertinoPicker refresh data not working

### ISSUE THREAD

**Issue by jaumard** [flutter/flutter#22999] opened 2018-10-12 09:28 UTC
`CupertinoPicker` widget is not refreshed when you change his `childCount`, if you put initial data no problem, but all data added after first build is not visible.
 
To reproduce: 
```dart
import 'package:flutter/cupertino.dart';

void main() => runApp(new MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return new CupertinoApp(
      title: 'Flutter Demo',
      home: new MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => new _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  var _devices = [];
  @override
  Widget build(BuildContext context) {
    print('build! ${_devices.length}');
    return new CupertinoPageScaffold(

      navigationBar: CupertinoNavigationBar(
        middle: Text(widget.title),
      ),
      child: Column(
        children: <Widget>[
          Container(
            height: 300.0,
            child: CupertinoPicker.builder(
                itemExtent: 40.0,
                onSelectedItemChanged: (index) {
                  print(index);
                },
                itemBuilder: (context, index) {
                  print('itemBuilder');
                  return Center(
                    child: Text(
                      'item :'+_devices[index],
                      maxLines: 1,
                      overflow: TextOverflow.fade,
                      textAlign: TextAlign.center,
                    ),
                  );
                },
                childCount: _devices.length),
          ),
          CupertinoButton(child: Text('add'),onPressed: () {
            setState(() {
              _devices.add("test");
            });
          },)
        ],
      ),
    );
  }
}
```

Flutter doctor:
```
[✓] Flutter (Channel beta, v0.9.4, on Mac OS X 10.13.6 17G65, locale fr-FR)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
[✓] Android Studio (version 3.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2018.2.4)
[✓] Connected devices (1 available)

```

**Comment by nashfive** [comment] 2018-10-12 10:38
The refresh is not happening because adding an element to the list doesn't not change the state. You need to create a new List from the current one, and assign it to your _devices state property. 

You'll also need to add a scrollController to trigger a UI refresh (scrolling or jumping to a specific position).

**Comment by jaumard** [comment] 2018-10-12 11:05
By forcing the scrolling it works, I'll use it as a workaround, but not ideal as it change the user selection. 

But the picker should be able to rebuild itself when the `childCount` changes (or provide a controller to be able to notify data change), still a bug of the picker for me.

**Comment by jaumard** [comment] 2018-10-12 11:08
Also when the initial data is empty, scrolling is not possible so the workaround doesn't work for that case

**Comment by nashfive** [comment] 2018-10-12 11:09
It seems that there is also a bug when the initial list is empty... the hack starts to work when you have 2 items...

**Comment by jaumard** [comment] 2019-01-11 19:36
I'm trying to fix this but can't figure out why the widget is not updating itself... 
I was thinking of adding 

```
if(widget.childDelegate.shouldRebuild(oldWidget.childDelegate)) {
      setState(() {
        //Update widget as childCount has changed
      });
    }
```
Into `_CupertinoPickerState` to trigger a refresh but it appear that it doesn't update correctly :(

**Comment by jaumard** [comment] 2019-01-17 13:52
anyone ? @Hixie maybe ? :)

**Comment by zoechi** [comment] 2019-01-30 08:39
Try to refactor the `child: ...` of `CupertinoPageScaffold` to a new stateful widget (with `devices` also moved there`) and call `setState()` in this widget instead.

**Comment by zoechi** [comment] 2019-01-30 12:11
When I use the code from the initial comment I get only

![image](https://user-images.githubusercontent.com/405837/51980369-1eac2700-2490-11e9-8441-bc155884f30e.png)

how to reproduce?

Did you consider asking in one of the other channels listed at http://flutter.io/support ?

**Comment by jaumard** [comment] 2019-01-30 12:18
Just click the `add` button, it adds items on the list and should refresh the picker, but it doesn't, it stay empty

**Comment by jaumard** [comment] 2019-01-30 12:19
I've tried only this other channel ^^ https://groups.google.com/forum/#!topicsearchin/flutter-dev/authorname$3Ajimmy/flutter-dev/RX5nRc3otg4

**Comment by agreensh** [comment] 2019-01-30 12:42
You can force the rebuild by using a ScrollController and moving to the new item (which is probably what you'd want anyway).

eg
```
import 'package:flutter/material.dart';
import 'package:flutter/cupertino.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return new CupertinoApp(
      title: 'Flutter Demo',
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => new _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  var _devices = [];
  var count = 0;
  FixedExtentScrollController controller = FixedExtentScrollController();

  @override
  Widget build(BuildContext context) {
    print('build! ${_devices.length}');
    return CupertinoPageScaffold(

      navigationBar: CupertinoNavigationBar(
        middle: Text(widget.title),
      ),
      child: Column(
        children: <Widget>[
          Container(
            height: 300.0,
            child: CupertinoPicker.builder(
                itemExtent: 60.0,
                scrollController: controller,
                onSelectedItemChanged: (index) {
                  print(index);
                },
                itemBuilder: (context, index) {
                  print('itemBuilder');
                  return Center(
                    child: Text(
                      'item :'+_devices[index],
                      maxLines: 1,
                      overflow: TextOverflow.fade,
                      textAlign: TextAlign.center,
                    ),
                  );
                },
                childCount: _devices.length),
          ),
          CupertinoButton(child: Text('Add'), 
            onPressed: () {
              setState(() {
                controller.animateToItem(count, duration: Duration(microseconds: 20), curve: ElasticInCurve());
                _devices.add("test " + count.toString());
              });
              count += 1;
            },
          )
        ],
      ),
    );
  }
}
```

**Comment by zoechi** [comment] 2019-01-30 13:03
@xster

**Comment by agreensh** [comment] 2019-01-30 13:36
@jaumard OK, I see. If you really need this now, you can force it to update by changing the Container it is wrapped in (a terrible hack, but it works...)

```
class _MyHomePageState extends State<MyHomePage> {
  var _devices = [];
  var _count = 0;
  var _height = 300.0;

  @override
  Widget build(BuildContext context) {
    print('build! ${_devices.length}');
    return CupertinoPageScaffold(

      navigationBar: CupertinoNavigationBar(
        middle: Text(widget.title),
      ),
      child: Column(
        children: <Widget>[
          Container(
            height: _height,
            child: CupertinoPicker.builder(
                itemExtent: 60.0,
                onSelectedItemChanged: (index) {
                  print(index);
                },
                itemBuilder: (context, index) {
                  print('itemBuilder');
                  return Center(
                    child: Text(
                      'item :' + _devices[index],
                      maxLines: 1,
                      overflow: TextOverflow.fade,
                      textAlign: TextAlign.center,
                    ),
                  );
                },
                childCount: _devices.length),
          ),
          CupertinoButton(child: Text('Add'), 
            onPressed: () {
              setState(() {
                _devices.add("test " + _count.toString());
                _count += 1;
                _height = 300.01;
              });
              Timer(const Duration(milliseconds: 50), () {
                if (mounted) {
                  setState(() {
                    _height = 300.0;
                  });
                }
              });
            },
          )
        ],
      ),
    );
  }
}
```

**Comment by jaumard** [comment] 2019-01-30 13:43
@agreensh ha ha nice one ! Ugly as hell but it works ! And it's more user friendly than jumping indexes all the time for the end user :) 
Thanks a lot ! Appreciated the workaround until there a proper fix :)

**Comment by TurkiWalid** [comment] 2019-07-05 09:34
Another solution (still ugly but worked for me)
Set a new key to the cupertino whenever you want to refresh it 

initSate
`_keyCupertino = GlobalKey();`

build
`CupertinoPicker.builder(
             key: _keyCupertino ,
               ... )`

Whenever you want to update
`        setState(() {
          _keyCupertino = GlobalKey();
          listofObjects = response;
        });`

**Comment by yizems** [comment] 2019-09-16 08:07
```dart
   final int position = min(_daySC.selectedItem, newDayCount - 1);
   _daySC.jumpToItem(position - 1);
   _daySC.jumpToItem(position);
```

it work,but ugly

**Comment by TahaTesser** [comment] 2020-03-30 16:15
Issue exist on 
```
[✓] Flutter (Channel dev, v1.16.3, on Mac OS X 10.15.4 19E266, locale en-GB)
    • Flutter version 1.16.3 at /Users/taha/Code/flutter_dev
    • Framework revision be3a4b37b3 (4 days ago), 2020-03-26 18:08:05 -0700
    • Engine revision b2bdeb3f0f
    • Dart version 2.8.0 (build 2.8.0-dev.17.0 1402e8e1a4)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/taha/Code/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/taha/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4, Build version 11E146
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.43.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[✓] Connected device (4 available)
    • iPhone 11  • 41EB2A85-7EB4-4FD2-8978-FBBE2A681D74 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-13-4 (simulator)
    • macOS      • macOS                                • darwin-x64     • Mac
      OS X 10.15.4 19E266
    • Chrome     • chrome                               • web-javascript •
      Google Chrome 80.0.3987.149
    • Web Server • web-server                           • web-javascript •
      Flutter Tools

• No issues found!
```

**Comment by ajaygautam** [comment] 2020-06-04 02:10
Ran into this issue. Thanks for the (ugly) workaround / hack @agreensh 

```
$ flutter doctor -v
[✓] Flutter (Channel master, 1.19.0-2.0.pre, on Mac OS X 10.15.3 19D76, locale en-US)
    • Flutter version 1.19.0-2.0.pre at /Users/agautam/tools/flutter
    • Framework revision 54524a7f95 (5 days ago), 2020-05-29 23:43:01 -0400
    • Engine revision 685699b351
    • Dart version 2.9.0 (build 2.9.0-11.0.dev 6489a0c68d)
```

**Comment by tudor07** [comment] 2020-07-08 15:15
Still does not work, also the workarounds provided do not work if you want to swap the list of times completly.

**Comment by ruskakimov** [comment] 2020-10-02 14:42
related issue https://github.com/flutter/flutter/issues/58144

**Comment by ruskakimov** [comment] 2020-10-02 15:18
A cleaner workaround:
```dart
  void _forceLayout() {
    setState(() {
      if (_squeeze == 1) {
        _squeeze = 1.000000000000001;
      } else {
        _squeeze = 1;
      }
    });
  }
```
Don't forget to pass `_squeeze` to `CupertinoPicker`.
This doesn't result in any noticeable visual changes.

**Comment by ristiisa** [comment] 2020-10-16 13:37
I'm having the same issue

```
Flutter (Channel master, 1.23.0-14.0.pre.152, on Mac OS X 10.15.4 19E287 x86_64, locale en-EE)
    • Flutter version 1.23.0-14.0.pre.152
    • Framework revision 62cf4dbf10 (3 days ago), 2020-10-13 14:12:02 +0800
    • Engine revision 6634406889
    • Dart version 2.11.0 (build 2.11.0-213.0.dev)
```

**Comment by o0starshine0o** [comment] 2021-01-06 04:23
I'm having the same issue

and I solve this by using dynamic height:

```dart
height: 220.0 + Random().nextDouble() / 100000000,
```

**Comment by longer96** [comment] 2021-01-11 10:52
I'm having the same issue

**Comment by NanaDada** [comment] 2021-02-22 18:51
Is this getting fixed any time soon? 

Btw, it would be useful if the builder constructor would have the missing looping parameter. Getting `scrollController.jumpToItem(selectedIndex);` to work when the children are refreshed is... _challenging_.  All in all, this class is pretty messed up.

**Comment by DenisBarzanov** [comment] 2021-05-20 10:12
Why is this widget so stiff

**Closed** 2021-06-09 02:39 UTC
Labels: P4, customer: amplify, f: cupertino, found in release: 1.21, framework, has reproducible steps, waiting for PR to land (fixed)
