### ISSUE TITLE
armv7 compile error

### ISSUE THREAD

**Issue by skytz** [flutter/flutter#2930] opened 2016-03-26 20:46 UTC
I'm trying to compile the engine for armv7 and i keep getting this errors: 

```
skytz$ ninja -C out/ios_Release
ninja: Entering directory `out/ios_Release'
[5/29] ASM clang_i386/obj/base/base/call_with_eh_frame_asm.o
FAILED: ../../third_party/llvm-build/Release+Asserts/bin/clang -MMD -MF clang_i386/obj/base/base/call_with_eh_frame_asm.o.d -DSYSTEM_NATIVE_UTF8 -DV8_DEPRECATION_WARNINGS -DCLD_VERSION=2 -DENABLE_NOTIFICATIONS -DENABLE_PEPPER_CDMS -DENABLE_PLUGINS=1 -DENABLE_PRINTING=1 -DENABLE_BASIC_PRINTING=1 -DENABLE_PRINT_PREVIEW=1 -DENABLE_SPELLCHECK=1 -DUSE_PLATFORM_SPELLCHECKER=1 -DDONT_EMBED_BUILD_METADATA -DUSE_OPENSSL=1 -DNO_TCMALLOC -DDISABLE_NACL -DENABLE_EXTENSIONS=1 -DENABLE_CONFIGURATION_POLICY -DENABLE_TASK_MANAGER=1 -DENABLE_THEMES=1 -DENABLE_CAPTIVE_PORTAL_DETECTION=1 -DENABLE_SESSION_SERVICE=1 -DENABLE_PLUGIN_INSTALLATION=1 -DENABLE_APP_LIST=1 -DENABLE_SETTINGS_APP=1 -DENABLE_SUPERVISED_USERS=1 -DENABLE_SERVICE_DISCOVERY=1 -DENABLE_AUTOFILL_DIALOG=1 -DENABLE_WIFI_BOOTSTRAPPING=1 -DENABLE_REMOTING=1 -DENABLE_GOOGLE_NOW=1 -DENABLE_ONE_CLICK_SIGNIN -DENABLE_HIDPI=1 -DV8_USE_EXTERNAL_STARTUP_DATA -DENABLE_BACKGROUND=1 -DENABLE_PRE_SYNC_BACKUP -DFULL_SAFE_BROWSING -DSAFE_BROWSING_CSD -DSAFE_BROWSING_DB_LOCAL -DSAFE_BROWSING_SERVICE -DCHROMIUM_BUILD -DENABLE_MEDIA_ROUTER=1 -DCR_CLANG_REVISION=241602-3 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_FORTIFY_SOURCE=2 -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DBASE_IMPLEMENTATION -I../.. -Iclang_i386/gen -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.6 -m32 -fno-strict-aliasing -fstack-protector-all -fcolor-diagnostics -Wall -Wsign-compare -Wendif-labels -Werror -Wno-missing-field-initializers -Wno-unused-parameter -Wpartial-availability -Wno-c++11-narrowing -Wno-char-subscripts -Wno-covered-switch-default -Wno-deprecated-register -Wno-inconsistent-missing-override -Wno-shift-negative-value -fvisibility=hidden -stdlib=libc++ -Xclang -load -Xclang ../../third_party/llvm-build/Release+Asserts/lib/libFindBadConstructs.dylib -Xclang -plugin-arg-find-bad-constructs -Xclang check-templates -Xclang -add-plugin -Xclang find-bad-constructs -Wheader-hygiene -Wstring-conversion -g2 -Wexit-time-destructors -O2 -fno-ident -fdata-sections -ffunction-sections -std=c99 -c ../../base/mac/call_with_eh_frame_asm.S -o clang_i386/obj/base/base/call_with_eh_frame_asm.o
../../base/mac/call_with_eh_frame_asm.S:25:9: error: register %rbp is only available in 64-bit mode
  pushq %rbp
        ^~~~
../../base/mac/call_with_eh_frame_asm.S:27:19: error: register %rbp is only available in 64-bit mode
  .cfi_offset %rbp, -16
                  ^
../../base/mac/call_with_eh_frame_asm.S:28:8: error: register %rsp is only available in 64-bit mode
  movq %rsp, %rbp
       ^~~~
../../base/mac/call_with_eh_frame_asm.S:29:29: error: register %rbp is only available in 64-bit mode
  .cfi_def_cfa_register %rbp
                            ^
../../base/mac/call_with_eh_frame_asm.S:32:11: error: register %rdi is only available in 64-bit mode
  movq 16(%rdi), %rax
          ^~~~
../../base/mac/call_with_eh_frame_asm.S:36:10: error: register %rax is only available in 64-bit mode
  callq *%rax
         ^~~~
../../base/mac/call_with_eh_frame_asm.S:38:8: error: register %rbp is only available in 64-bit mode
  popq %rbp
       ^~~~
../../base/mac/call_with_eh_frame_asm.S:45:8: error: register %rax is only available in 64-bit mode
  movq %rax, %rdi
       ^~~~
../../base/mac/call_with_eh_frame_asm.S:46:3: error: instruction requires: 64-bit mode
  callq ___cxa_begin_catch
  ^
[5/29] ACTION //sky/engine/bindings:generate_snapshot_bin(//build/toolchain/mac:clang_i386)
FAILED: python ../../dart/runtime/tools/create_snapshot_bin.py --executable /Users/skytz/Desktop/engine/src/out/ios_Release/clang_x64/gen_snapshot --package_root /Users/skytz/Desktop/engine/src/out/ios_Release/clang_i386/gen --script /Users/skytz/Desktop/engine/src/sky/engine/bindings/snapshot.dart --vm_output_bin clang_i386/gen/sky/engine/bindings/vm_isolate_snapshot.bin --output_bin clang_i386/gen/sky/engine/bindings/isolate_snapshot.bin --target_os ios --url_mapping=dart:mojo.internal,/Users/skytz/Desktop/engine/src/mojo/dart/packages/mojo/sdk_ext/internal.dart --url_mapping=dart:ui,/Users/skytz/Desktop/engine/src/out/ios_Release/clang_i386/gen/sky/bindings/dart_ui.dart --url_mapping=dart:jni,/Users/skytz/Desktop/engine/src/sky/engine/bindings/jni/jni.dart
Command failed: '/Users/skytz/Desktop/engine/src/out/ios_Release/clang_x64/gen_snapshot --ignore_unrecognized_flags --error_on_bad_type --error_on_bad_override --package_root=/Users/skytz/Desktop/engine/src/out/ios_Release/clang_i386/gen --vm_isolate_snapshot=clang_i386/gen/sky/engine/bindings/vm_isolate_snapshot.bin --isolate_snapshot=clang_i386/gen/sky/engine/bindings/isolate_snapshot.bin --url_mapping=dart:mojo.internal,/Users/skytz/Desktop/engine/src/mojo/dart/packages/mojo/sdk_ext/internal.dart --url_mapping=dart:ui,/Users/skytz/Desktop/engine/src/out/ios_Release/clang_i386/gen/sky/bindings/dart_ui.dart --url_mapping=dart:jni,/Users/skytz/Desktop/engine/src/sky/engine/bindings/jni/jni.dart /Users/skytz/Desktop/engine/src/sky/engine/bindings/snapshot.dart'
[5/29] OBJCXX clang_i386/obj/base/base/sdk_forward_declarations.o
FAILED: ../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF clang_i386/obj/base/base/sdk_forward_declarations.o.d -DSYSTEM_NATIVE_UTF8 -DV8_DEPRECATION_WARNINGS -DCLD_VERSION=2 -DENABLE_NOTIFICATIONS -DENABLE_PEPPER_CDMS -DENABLE_PLUGINS=1 -DENABLE_PRINTING=1 -DENABLE_BASIC_PRINTING=1 -DENABLE_PRINT_PREVIEW=1 -DENABLE_SPELLCHECK=1 -DUSE_PLATFORM_SPELLCHECKER=1 -DDONT_EMBED_BUILD_METADATA -DUSE_OPENSSL=1 -DNO_TCMALLOC -DDISABLE_NACL -DENABLE_EXTENSIONS=1 -DENABLE_CONFIGURATION_POLICY -DENABLE_TASK_MANAGER=1 -DENABLE_THEMES=1 -DENABLE_CAPTIVE_PORTAL_DETECTION=1 -DENABLE_SESSION_SERVICE=1 -DENABLE_PLUGIN_INSTALLATION=1 -DENABLE_APP_LIST=1 -DENABLE_SETTINGS_APP=1 -DENABLE_SUPERVISED_USERS=1 -DENABLE_SERVICE_DISCOVERY=1 -DENABLE_AUTOFILL_DIALOG=1 -DENABLE_WIFI_BOOTSTRAPPING=1 -DENABLE_REMOTING=1 -DENABLE_GOOGLE_NOW=1 -DENABLE_ONE_CLICK_SIGNIN -DENABLE_HIDPI=1 -DV8_USE_EXTERNAL_STARTUP_DATA -DENABLE_BACKGROUND=1 -DENABLE_PRE_SYNC_BACKUP -DFULL_SAFE_BROWSING -DSAFE_BROWSING_CSD -DSAFE_BROWSING_DB_LOCAL -DSAFE_BROWSING_SERVICE -DCHROMIUM_BUILD -DENABLE_MEDIA_ROUTER=1 -DCR_CLANG_REVISION=241602-3 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_FORTIFY_SOURCE=2 -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DBASE_IMPLEMENTATION -I../.. -Iclang_i386/gen -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.6 -m32 -fno-strict-aliasing -fstack-protector-all -fcolor-diagnostics -Wall -Wsign-compare -Wendif-labels -Werror -Wno-missing-field-initializers -Wno-unused-parameter -Wpartial-availability -Wno-c++11-narrowing -Wno-char-subscripts -Wno-covered-switch-default -Wno-deprecated-register -Wno-inconsistent-missing-override -Wno-shift-negative-value -fvisibility=hidden -stdlib=libc++ -Xclang -load -Xclang ../../third_party/llvm-build/Release+Asserts/lib/libFindBadConstructs.dylib -Xclang -plugin-arg-find-bad-constructs -Xclang check-templates -Xclang -add-plugin -Xclang find-bad-constructs -Wheader-hygiene -Wstring-conversion -g2 -Wexit-time-destructors -O2 -fno-ident -fdata-sections -ffunction-sections -fvisibility-inlines-hidden -std=c++11 -fno-rtti -fno-exceptions -fvisibility-inlines-hidden -fobjc-call-cxx-cdtors -std=c++11 -fno-rtti -fno-exceptions -c ../../base/mac/sdk_forward_declarations.mm -o clang_i386/obj/base/base/sdk_forward_declarations.o
In file included from ../../base/mac/sdk_forward_declarations.mm:5:
../../base/mac/sdk_forward_declarations.h:476:12: error: cannot define category for undefined class 'NSUserActivity'
@interface NSUserActivity (YosemiteSDK)
           ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSApplication.h:21:8: note: forward declaration of class here
@class NSUserActivity;
       ^
1 error generated.
[5/29] OBJCXX clang_i386/obj/base/base/mac_util.o
FAILED: ../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF clang_i386/obj/base/base/mac_util.o.d -DSYSTEM_NATIVE_UTF8 -DV8_DEPRECATION_WARNINGS -DCLD_VERSION=2 -DENABLE_NOTIFICATIONS -DENABLE_PEPPER_CDMS -DENABLE_PLUGINS=1 -DENABLE_PRINTING=1 -DENABLE_BASIC_PRINTING=1 -DENABLE_PRINT_PREVIEW=1 -DENABLE_SPELLCHECK=1 -DUSE_PLATFORM_SPELLCHECKER=1 -DDONT_EMBED_BUILD_METADATA -DUSE_OPENSSL=1 -DNO_TCMALLOC -DDISABLE_NACL -DENABLE_EXTENSIONS=1 -DENABLE_CONFIGURATION_POLICY -DENABLE_TASK_MANAGER=1 -DENABLE_THEMES=1 -DENABLE_CAPTIVE_PORTAL_DETECTION=1 -DENABLE_SESSION_SERVICE=1 -DENABLE_PLUGIN_INSTALLATION=1 -DENABLE_APP_LIST=1 -DENABLE_SETTINGS_APP=1 -DENABLE_SUPERVISED_USERS=1 -DENABLE_SERVICE_DISCOVERY=1 -DENABLE_AUTOFILL_DIALOG=1 -DENABLE_WIFI_BOOTSTRAPPING=1 -DENABLE_REMOTING=1 -DENABLE_GOOGLE_NOW=1 -DENABLE_ONE_CLICK_SIGNIN -DENABLE_HIDPI=1 -DV8_USE_EXTERNAL_STARTUP_DATA -DENABLE_BACKGROUND=1 -DENABLE_PRE_SYNC_BACKUP -DFULL_SAFE_BROWSING -DSAFE_BROWSING_CSD -DSAFE_BROWSING_DB_LOCAL -DSAFE_BROWSING_SERVICE -DCHROMIUM_BUILD -DENABLE_MEDIA_ROUTER=1 -DCR_CLANG_REVISION=241602-3 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_FORTIFY_SOURCE=2 -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DBASE_IMPLEMENTATION -I../.. -Iclang_i386/gen -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.6 -m32 -fno-strict-aliasing -fstack-protector-all -fcolor-diagnostics -Wall -Wsign-compare -Wendif-labels -Werror -Wno-missing-field-initializers -Wno-unused-parameter -Wpartial-availability -Wno-c++11-narrowing -Wno-char-subscripts -Wno-covered-switch-default -Wno-deprecated-register -Wno-inconsistent-missing-override -Wno-shift-negative-value -fvisibility=hidden -stdlib=libc++ -Xclang -load -Xclang ../../third_party/llvm-build/Release+Asserts/lib/libFindBadConstructs.dylib -Xclang -plugin-arg-find-bad-constructs -Xclang check-templates -Xclang -add-plugin -Xclang find-bad-constructs -Wheader-hygiene -Wstring-conversion -g2 -Wexit-time-destructors -O2 -fno-ident -fdata-sections -ffunction-sections -fvisibility-inlines-hidden -std=c++11 -fno-rtti -fno-exceptions -fvisibility-inlines-hidden -fobjc-call-cxx-cdtors -std=c++11 -fno-rtti -fno-exceptions -c ../../base/mac/mac_util.mm -o clang_i386/obj/base/base/mac_util.o
In file included from ../../base/mac/mac_util.mm:23:
../../base/mac/sdk_forward_declarations.h:476:12: error: cannot define category for undefined class 'NSUserActivity'
@interface NSUserActivity (YosemiteSDK)
           ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSApplication.h:21:8: note: forward declaration of class here
@class NSUserActivity;
       ^
1 error generated.
ninja: build stopped: subcommand failed.
```

**Comment by abarth** [comment] 2016-03-26 20:54
/cc @chinmaygarde 

What does `gn args out/ios_Release` show?  I'm wondering if you passed `--ios-force-armv7` when running `sky/tools/gn`

**Comment by chinmaygarde** [comment] 2016-03-26 21:12
That file is being compiled for i386. So its likely part of the snapshotter. Hold on, I am going to verify the --ios-force-armv7 builds again.

**Comment by skytz** [comment] 2016-03-26 21:18
@abarth 

this is what i called  `sky/tools/gn --ios --ios-force-armv7 --release`

and the output of args :
```
use_goma = false
use_ios_simulator = false
target_cpu = "arm"
dart_target_arch = "arm"
enable_gcm = false
goma_dir = "None"
enable_firebase = false
target_os = "ios"
is_clang = true
is_debug = false
ios_deployment_target = "7.0"
```

**Comment by chinmaygarde** [comment] 2016-03-28 18:17
This was caused by a recent roll of the base library https://github.com/domokit/base. We are a bit unique in that host snapshotter was being built for i386 because of our dependency on dart/runtime. I am going to try to update this.

Just an update.

**Comment by chinmaygarde** [comment] 2016-03-28 20:06
Updated base to fix compile errors. Checking tooling.

**Comment by skytz** [comment] 2016-03-29 09:32
@chinmaygarde 
 I still get this error when i compile:

```
skytz$ ./sky/tools/gn --ios --ios-force-armv7
gn gen --check in out/ios_Debug
Done. Wrote 965 targets from 157 files in 11210ms
skytz$ ninja -C out/ios_Debug -j12
ninja: Entering directory `out/ios_Debug'
[2320/6833] ACTION //sky/engine/bindings:gen...apshot_bin(//build/toolchain/mac:clang_i386)
FAILED: python ../../dart/runtime/tools/create_snapshot_bin.py --executable /Users/skytz/Desktop/engine/src/out/ios_Debug/clang_x64/gen_snapshot --package_root /Users/skytz/Desktop/engine/src/out/ios_Debug/clang_i386/gen --script /Users/skytz/Desktop/engine/src/sky/engine/bindings/snapshot.dart --vm_output_bin clang_i386/gen/sky/engine/bindings/vm_isolate_snapshot.bin --output_bin clang_i386/gen/sky/engine/bindings/isolate_snapshot.bin --target_os ios --url_mapping=dart:mojo.internal,/Users/skytz/Desktop/engine/src/mojo/dart/packages/mojo/sdk_ext/internal.dart --url_mapping=dart:ui,/Users/skytz/Desktop/engine/src/out/ios_Debug/clang_i386/gen/sky/bindings/dart_ui.dart --url_mapping=dart:jni,/Users/skytz/Desktop/engine/src/sky/engine/bindings/jni/jni.dart
Command failed: '/Users/skytz/Desktop/engine/src/out/ios_Debug/clang_x64/gen_snapshot --ignore_unrecognized_flags --error_on_bad_type --error_on_bad_override --package_root=/Users/skytz/Desktop/engine/src/out/ios_Debug/clang_i386/gen --vm_isolate_snapshot=clang_i386/gen/sky/engine/bindings/vm_isolate_snapshot.bin --isolate_snapshot=clang_i386/gen/sky/engine/bindings/isolate_snapshot.bin --url_mapping=dart:mojo.internal,/Users/skytz/Desktop/engine/src/mojo/dart/packages/mojo/sdk_ext/internal.dart --url_mapping=dart:ui,/Users/skytz/Desktop/engine/src/out/ios_Debug/clang_i386/gen/sky/bindings/dart_ui.dart --url_mapping=dart:jni,/Users/skytz/Desktop/engine/src/sky/engine/bindings/jni/jni.dart /Users/skytz/Desktop/engine/src/sky/engine/bindings/snapshot.dart'
[2320/6833] CXX clang_x64/obj/skia/skia/GrGLTestInterface.o
ninja: build stopped: subcommand failed.
skytz$
```

**Comment by chinmaygarde** [comment] 2016-03-29 17:59
That is a failure on the snapshot generation on the host. Can you make sure
you have updated the both the Flutter and Engine repos and performed a
gclient sync in the engine before trying again?

Chinmay

PS: I am not sure why Github didnt tie this to the issue. Feel free to
re-open the ticket if it is still failing for you after pull.

**Comment by skytz** [comment] 2016-03-29 19:51
@chinmaygarde 
I made sure i have everything up to date and i still get the error.
Do you have any suggestion on how i would go about debugging the problem? If it's a host issue.


PS : I cannot reopen the issue because i'm not a collaborator of the repo. You can do it tho.

**Comment by chinmaygarde** [comment] 2016-04-08 19:31
Fixed in https://github.com/flutter/engine/pull/2588. Adding a builbot target for this as well.

**Closed** 2016-04-08 19:31 UTC
Labels: affects: engine, ⌺‬ platform-ios, ⚠ bug

**Comment by skytz** [comment] 2016-04-09 16:52
I can confirm the snapshoting error was fixed but there was another problem while i was building the engine.

```
skytz$ ninja -C out/ios_Debug_armv7/
ninja: Entering directory `out/ios_Debug_armv7/'
[1/18] CXX obj/sky/shell/common/tracing_controller.o
FAILED: ../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF obj/sky/shell/common/tracing_controller.o.d -DV8_DEPRECATION_WARNINGS -DCLD_VERSION=2 -DENABLE_PRINTING=1 -DENABLE_BASIC_PRINTING=1 -DENABLE_PRINT_PREVIEW=1 -DENABLE_SPELLCHECK=1 -DDONT_EMBED_BUILD_METADATA -DNO_TCMALLOC -DMEMORY_TOOL_REPLACES_ALLOCATOR -DMEMORY_SANITIZER_INITIAL_SIZE -DDISABLE_FTP_SUPPORT=1 -DDISABLE_NACL -DENABLE_CONFIGURATION_POLICY -DV8_USE_EXTERNAL_STARTUP_DATA -DCHROMIUM_BUILD -DCR_CLANG_REVISION=241602-3 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_FORTIFY_SOURCE=2 -D_DEBUG -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DWTF_USE_DYNAMIC_ANNOTATIONS=1 -DSK_IGNORE_LINEONLY_AA_CONVEX_PATH_OPTS -DSK_SUPPORT_LEGACY_SHADERBITMAPTYPE -DSK_SUPPORT_GPU=1 -DSK_BUILD_FOR_IOS -DUSE_LIBJPEG_TURBO -DCHROME_PNG_WRITE_SUPPORT -DPNG_USER_CONFIG -DWTF_USE_DYNAMIC_ANNOTATIONS=1 -DENABLE_OPENTYPE_VERTICAL=1 -DENABLE_DART_STRICT=1 -DU_USING_ICU_NAMESPACE=0 -DU_ENABLE_DYLOAD=0 -DU_STATIC_IMPLEMENTATION -I../.. -Igen -I../../dart/runtime -I../.. -Igen -I../../skia/config -I../../skia/ext -I../../third_party/skia/include/c -I../../third_party/skia/include/client/android -I../../third_party/skia/include/config -I../../third_party/skia/include/core -I../../third_party/skia/include/effects -I../../third_party/skia/include/images -I../../third_party/skia/include/lazy -I../../third_party/skia/include/pathops -I../../third_party/skia/include/pdf -I../../third_party/skia/include/pipe -I../../third_party/skia/include/ports -I../../third_party/skia/include/utils -I../../third_party/skia/include/gpu -I../../third_party/skia/src/gpu -I../../third_party/libjpeg_turbo -I../../third_party/iccjpeg -I../../third_party/libpng -I../../third_party/zlib -I../../third_party/qcms/src -I../../third_party/icu/source/common -I../../third_party/icu/source/i18n -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.3.sdk -miphoneos-version-min=7.0  -fno-strict-aliasing -arch armv7 -fcolor-diagnostics -Wall -Wsign-compare -Wendif-labels -Werror -Wno-missing-field-initializers -Wno-unused-parameter -Wno-c++11-narrowing -Wno-char-subscripts -Wno-covered-switch-default -Wno-deprecated-register -Wno-inconsistent-missing-override -Wno-shift-negative-value -fvisibility=hidden -stdlib=libc++ -Xclang -load -Xclang ../../third_party/llvm-build/Release+Asserts/lib/libFindBadConstructs.dylib -Xclang -add-plugin -Xclang find-bad-constructs -Wheader-hygiene -Wstring-conversion -O0 -g2 -fvisibility-inlines-hidden -Wno-undefined-bool-conversion -Wno-tautological-undefined-compare -std=c++11 -fno-rtti -fno-exceptions -c ../../sky/shell/tracing_controller.cc -o obj/sky/shell/common/tracing_controller.o
../../sky/shell/tracing_controller.cc:155:3: error: use of undeclared identifier 'Dart_SetThreadName'
  Dart_SetThreadName(name);
  ^
1 error generated.
ninja: build stopped: subcommand failed.
```

**Comment by abarth** [comment] 2016-04-09 16:58
Maybe you need to `gclient sync` to update dependencies before building?

**Comment by eseidelGoogle** [comment] 2016-04-09 16:59
That's a new API in dart. You may need to gclient sync to make sure you
have up to date dart sources.

**Comment by skytz** [comment] 2016-04-09 18:09
Yep, that fixed it.
Thank you.
