### ISSUE TITLE
 [cloud_firestore] inconsistent implementation of PlatformException

### ISSUE THREAD

**Issue by xinoxapps** [flutter/flutter#61436] opened 2020-07-14 09:56 UTC
Exceptions are useless as they are inconsistent across platforms. At least IOS bothers to include a code, Android fails miserable by just giving each time the same code. FirebaseAuth seems to give the same error code across platforms. 

Please fix this mess or give some better hints in the documentation.

DocumentSnapshot snapshot =
            await db.collection("companies").document(companyId).get(); 

Gives the following exception when you don't have permission:

Android: PlatformException(Error performing get, PERMISSION_DENIED: Missing or insufficient permissions., null);
IOS: PlatformException(Error 7, FIRFirestoreErrorDomain: Missing or insufficient permissions., null);

should be
PlatformException(PERMISSION_DENIED, Missing or insufficient permissions., null);

--
Gives the following exception when you don't have internet:
Android: PlatformException(Error performing get, Failed to get document because the client is offline., null);
IOS: PlatformException(Error 14, FIRFirestoreErrorDomain: Failed to get document because the client is offline., null);

should be
PlatformException(ERROR_NETWORK_REQUEST_FAILED, Failed to get document because the client is offline., null);

**Comment by TahaTesser** [comment] 2020-07-14 11:02
Hi @xinoxapps 
From what I can see, the issue is related to a FlutterFire plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by TahaTesser** 2020-07-14 11:02 UTC
