### ISSUE TITLE
[tool_crash] _TypeError: (#0      AndroidStudioJavaGradleConflictMigration.migrate (package:flutter_tools/src/android/migrations/android_studio_java_gradle_conflict_migration.dart:107:39))

### ISSUE THREAD

**Issue by thomasrumpf** [flutter/flutter#125767] opened 2023-04-30 11:56 UTC
## Command
```
flutter --no-color run --machine --track-widget-creation --device-id=R3CNB0CW2HJ --start-paused --dart-define=flutter.inspector.structuredErrors=true lib/main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
_TypeError: (#0      AndroidStudioJavaGradleConflictMigration.migrate (package:flutter_tools/src/android/migrations/android_studio_java_gradle_conflict_migration.dart:107:39))
```
#0      AndroidStudioJavaGradleConflictMigration.migrate (package:flutter_tools/src/android/migrations/android_studio_java_gradle_conflict_migration.dart:107:39)
#1      ProjectMigration.run (package:flutter_tools/src/base/project_migrator.dart:84:16)
#2      AndroidGradleBuilder.buildGradleApp (package:flutter_tools/src/android/gradle.dart:280:15)
#3      AndroidGradleBuilder.buildApk (package:flutter_tools/src/android/gradle.dart:208:11)
#4      AndroidDevice.startApp (package:flutter_tools/src/android/android_device.dart:578:29)
<asynchronous suspension>
#5      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:468:33)
<asynchronous suspension>
#6      Future.wait.<anonymous closure> (dart:async/future.dart:525:21)
<asynchronous suspension>
#7      HotRunner.run (package:flutter_tools/src/run_hot.dart:421:34)
<asynchronous suspension>
#8      AppDomain.launch.<anonymous closure> (package:flutter_tools/src/commands/daemon.dart:649:9)
<asynchronous suspension>
#9      AppDomain.launch (package:flutter_tools/src/commands/daemon.dart:647:5)
<asynchronous suspension>
#10     RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:638:15)
<asynchronous suspension>
#11     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1294:27)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#13     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:296:9)
```
```
[✓] Flutter (Channel master, 3.10.0-17.0.pre.32, on macOS 13.3.1 22E261 darwin-x64, locale de-DE)
    • Flutter version 3.10.0-17.0.pre.32 on channel master at /Users/thomasrumpf/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9241329b46 (65 minutes ago), 2023-04-30 06:40:27 -0400
    • Engine revision c796390d14
    • Dart version 3.1.0 (build 3.1.0-56.0.dev)
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/thomasrumpf/android-sdks
    • Platform android-33, build-tools 32.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio 2.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio 3.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] Connected device (3 available)
    • SM G981B (mobile) • R3CNB0CW2HJ • android-arm64  • Android 13 (API 33)
    • macOS (desktop)   • macos       • darwin-x64     • macOS 13.3.1 22E261 darwin-x64
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 104.0.5112.101

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+2
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: unknown
**Creation framework version**: ee4e09cce01d6f2d7f4baebd247fde02e5008851
### Plugins
audio_session-0.1.13
cloud_firestore-4.5.3
cloud_firestore_web-3.4.2
connectivity_plus-2.3.9
connectivity_plus_linux-1.3.1
connectivity_plus_macos-1.2.6
connectivity_plus_web-1.2.5
connectivity_plus_windows-1.2.2
firebase_core-2.10.0
firebase_core_web-2.3.0
flutter_plugin_android_lifecycle-2.0.13
flutter_ringtone_player-3.2.0
geolocator-8.2.1
geolocator_android-3.2.1
geolocator_apple-2.2.5
geolocator_web-2.1.6
geolocator_windows-0.1.1
google_maps_flutter-2.2.5
google_maps_flutter_android-2.4.13
google_maps_flutter_ios-2.2.1
just_audio-0.9.32
just_audio_web-0.4.7
location-4.4.0
location_web-3.1.1
path_provider-2.0.14
path_provider_android-2.0.27
path_provider_foundation-2.2.2
path_provider_linux-2.1.10
path_provider_windows-2.1.6
sensors_plus-2.0.5
shared_preferences-2.1.0
shared_preferences_android-2.1.4
shared_preferences_foundation-2.2.1
shared_preferences_linux-2.2.0
shared_preferences_web-2.1.0
shared_preferences_windows-2.2.0
sqflite-2.2.8
wakelock-0.6.2
wakelock_macos-0.4.0
wakelock_web-0.4.0
webview_flutter-4.2.0
webview_flutter_android-3.6.2
webview_flutter_wkwebview-3.4.0

**Comment by danagbemava-nc** [comment] 2023-05-02 07:16
Closing this as a duplicate of https://github.com/flutter/flutter/issues/125712 which has more details on https://github.com/flutter/flutter/issues/125712#issuecomment-1528101662 and possible fix as mentioned https://github.com/flutter/flutter/issues/125712#issuecomment-1530238853, so please upgrade to latest master and see if you still get the same crash or not. If yes, please write in the comments and I'll reopen it.

**Closed by danagbemava-nc** 2023-05-02 07:16 UTC
Labels: in triage
