### ISSUE TITLE
[image_picker][iOS] Exception is thrown when picking image on simulator

### ISSUE THREAD

**Issue by joutvhu** [flutter/flutter#105861] opened 2022-06-12 19:02 UTC
image_picker: 0.8.5+3 has issue in iOS when I tried to select the first image in the gallery.

The error occurs only when selecting the first image, but other images can be selected without error.

Steps:
1. Select the first image (the pop-up will close, but no images will return)
2. Reselect the image above (an error is thrown)

![Screen Shot 2022-06-13 at 01 45 37](https://user-images.githubusercontent.com/9401202/173248861-aa8b7904-4c83-468a-8ffc-ca1946cfbb98.png)

**Comment by danagbemava-nc** [comment] 2022-06-13 09:21
Closing this as a duplicate of https://github.com/flutter/flutter/issues/82602#issuecomment-1092475129.

Kindly follow up in the linked issue for updates. 

Thank you

**Closed by danagbemava-nc** 2022-06-13 09:21 UTC
Labels: in triage
