### ISSUE TITLE
flutter build ios ERROR

### ISSUE THREAD

**Issue by BRSPRO** [flutter/flutter#41147] opened 2019-09-23 23:44 UTC
Please, I get this error when I'm trying to build a release for iOS. When I'm building in the debug mode, there is no problem.

```
admin$ flutter build ios
Building ec.brs.drinkers for device (ios-release)...
Automatically signing iOS for device deployment using specified development team in Xcode project: XXXXXXXXXXXXXX
Running Xcode build...                                                  
                                                   
Xcode build done.                                           25.9s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
   
    /Users/admin/Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_paymentez-0.0.1/ios/Classes/SwiftFlutterPaymentezPlugin.swift:3:8: error: no such module 'PaymentezSDK'
    import PaymentezSDK
           ^
    Command CompileSwift failed with a nonzero exit code
    note: Using new build systemnote: Planning buildnote: Constructing build description

Encountered error while building for device.
```

**Comment by janmoppel** [comment] 2019-09-24 07:18
Hello @BRSPRO !

Thank you for posting an issue.
Can you please also post the `flutter doctor -v` command output?

Seems like you might have the similar problem that was discussed in this thread: https://stackoverflow.com/questions/29500227/getting-error-no-such-module-using-xcode-but-the-framework-is-there

Can you please check, whether proposed solutions work for you?

Thank you.

**Comment by BRSPRO** [comment] 2019-09-24 13:43
Hi janmopel,
This is the output of the command:

flutter doctor -v
[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.14.5 18F203, locale en-EC)
    • Flutter version 1.7.8+hotfix.4 at /Users/admin/Downloads/flutter
    • Framework revision 20e59316b8 (10 weeks ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/admin/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • CocoaPods version 1.7.2

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (1 available)
    • iPhone Xʀ • 0D41D4AF-F3BD-4D41-8511-693E58914A80 • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)

• No issues found!
---------------------------------------------------------------------------------------------

im going to review at detail the link you send, but i think is not exactly the same because of my architecture, i have my flutter project that uses a flutter plugin (developed by me too), and this plugin has the framework that presents the problem, only when i want to compile for release that it fails, when i run in the simulator it works, so i dont know why it find the framework for the simulator but not for the "flutter build ios" command to make a release

**Comment by jmagman** [comment] 2019-09-24 21:26
Can you paste the contents of your flutter_paymentez.podspec?  How are you declaring a dependency on PaymentezSDK?

A sample app that reproduces the issue would help!

**Comment by BRSPRO** [comment] 2019-09-24 22:43
> 
> 
> Can you paste the contents of your flutter_paymentez.podspec? How are you declaring a dependency on PaymentezSDK?
> 
> A sample app that reproduces the issue would help!

Yes of course this is the podspec content:

#
# To learn more about a Podspec see http://guides.cocoapods.org/syntax/podspec.html
#
Pod::Spec.new do |s|
  s.name             = 'flutter_paymentez'
  s.version          = '0.0.1'
  s.summary          = 'A new Flutter plugin to add credit cards using Android and iOS Paymentez SDK'
  s.description      = <<-DESC
A new Flutter plugin to add credit cards using Android and iOS Paymentez SDK
                       DESC
  s.homepage         = 'http://example.com'
  s.license          = { :file => '../LICENSE' }
  s.author           = { 'Your Company' => 'email@example.com' }
  s.source           = { :path => '.' }
  s.source_files = 'Classes/**/*'
  s.public_header_files = 'Classes/**/*.h'
  s.dependency 'Flutter'

  s.ios.deployment_target = '9.0'
end
-----------------------------------------------------------------------------------------

If you download the plugin there is an example, open it in android and change the pubspec.yaml to dependencies "flutter_paymentez: ^0.0.1", erase the dev_dependencies and run the "flutter build ios" command there is the error

**Comment by jmagman** [comment] 2019-09-24 23:14
Your podspec doesn't actually declare any dependency for PaymentezSDK or vend it as a framework to be imported by your plugin users.  You dropped that framework into your example app Xcode project, but that's not going to make it a framework available anywhere else that uses your plugin.


Try looking into how vendored_frameworks work in CocoaPods.  Also check out how google_sign_in works, since it has a similar dependency on the GoogleSignIn framework https://github.com/flutter/plugins/blob/master/packages/google_sign_in/ios/google_sign_in.podspec
See also https://flutter.dev/docs/development/packages-and-plugins/developing-packages#ios

This is a plugin author setup issue, not a Flutter bug.  I would try a [StackOverflow](https://stackoverflow.com/tags/flutter) post. Flutter has a very active and helpful community there.
Closing.

**Closed by jmagman** 2019-09-24 23:14 UTC
Labels: severe: crash, t: xcode, tool, ⌺‬ platform-ios
