### ISSUE TITLE
TabAlignment.fill and isScrollable: true show error

### ISSUE THREAD

**Issue by maxdiable** [flutter/flutter#137758] opened 2023-11-02 12:04 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

in my tabbar i put:

 tabAlignment: TabAlignment.fill,
  isScrollable: true,

after run my app flutter show this error:
A RenderFlex overflowed by 99870 pixels on the bottom.

![erorr](https://github.com/flutter/flutter/assets/211283/56569e0d-0203-4582-bdc2-607142457ef4)

### Expected results

 expect that if I use both properties I shouldn't get an error.
I expect that if my screen is in the landscape tabbar it should be full with

### Actual results

both property not working:

tabAlignment: TabAlignment.fill work only if  isScrollable: false,

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:cure_domiciliari/Models/OperatoreModel.dart';
import 'package:cure_domiciliari/Common/Palette.dart';
import 'package:cure_domiciliari/Common/Costants.dart';
import 'package:cure_domiciliari/Component/MyAppBar.dart';
import 'AccOdierniPage.dart';
import 'AccessiInviatiPage.dart';
import 'DaCompletarePage.dart';
import 'RicAssistitiPage.dart';
import 'package:flutter_gen/gen_l10n/app_localizations.dart';

class HomePage extends StatefulWidget {
  const HomePage({super.key});

  @override
  State<HomePage> createState() => homeState();
}

class homeState extends State<HomePage> {
  late String _barText = "";

  TabBar get _tabBar => TabBar(
	tabAlignment: TabAlignment.fill,
    isScrollable: true,
    dividerColor: Colors.white,
    labelColor: Colors.white,
    indicatorColor: Palette.Primary,
    unselectedLabelColor: Palette.Primary,
    onTap: (index){
      //debugPrint('index: $index');
      //hideSearch(value: (index == 1));
    },
    tabs: [
      Tab(
        icon: const Icon(Icons.apps),
        text: AppLocalizations.of(Costants.navigatorKey.currentContext!)!.acc_day,
      ),
      Tab(
        icon: const Icon(Icons.search),
        text: AppLocalizations.of(Costants.navigatorKey.currentContext!)!.search_ass,
      ),
      Tab(
        icon: const Icon(Icons.compare_arrows),
        text: AppLocalizations.of(Costants.navigatorKey.currentContext!)!.to_complete,
      ),
      Tab(
        icon: const Icon(Icons.send),
        text: AppLocalizations.of(Costants.navigatorKey.currentContext!)!.acc_send,
      ),
    ],
  );


  @override
  void initState() {
    super.initState();
    getDataUser().then((result) {
      setState(() {
        _barText = result;
      });
    });
  }

  @override
  Widget build(BuildContext context) {
    return DefaultTabController(
      initialIndex: 1,
      length: 4,
      child: Scaffold(
        appBar: MyAppBar(
          title: _barText,
          bottom: PreferredSize(
            preferredSize: _tabBar.preferredSize,
            child: Material(
              color: Palette.Secondary,
              child: _tabBar,
            ),
          ),
        ),
        body: TabBarView(
          children: <Widget>[
            const AccOdierniPage(),
            RicAssistitiPage(
                title: AppLocalizations.of(Costants.navigatorKey.currentContext!)!.search_ass),
            const DaCompletarePage(),
            const AccessiInviatiPage(),
          ],
        ),
      ),
    );
  }

  Future<String> getDataUser() async {
    String? ret = "";

    ret = await Costants.storage.read(key: eCommon.KEY_TITLE_BAR_APP.value);
    if(ret == null) {
      var data = await OperatoreModel.readFromStorage();
      ret = "${AppLocalizations.of(Costants.navigatorKey.currentContext!)!.asl_app(data.descrizioneAsl.toString())}\n";
      ret += AppLocalizations.of(Costants.navigatorKey.currentContext!)!.operator("${data.nomeOperatore} ${data.cognomeOperatore}");
      Costants.storage.write(
          key: eCommon.KEY_TITLE_BAR_APP.value, value: ret);
    }

    return ret;
  }

  TabBar getTabBar(BuildContext context){
    return TabBar(
      isScrollable: true,
      dividerColor: Colors.white,
      labelColor: Colors.white,
      indicatorColor: Palette.Primary,
      unselectedLabelColor: Palette.Primary,
      onTap: (index){
        //debugPrint('index: $index');
        //hideSearch(value: (index == 1));
      },
      tabs: [
        Container(
            width: yourWidth,
            height: 50,
            alignment: Alignment.center,
            child: Text("CHATS")),
        Container(
            width: yourWidth,
            height: 50,
            alignment: Alignment.center,
            child: Text("STATUS")),
        Container(
            width: yourWidth,
            height: 50,
            alignment: Alignment.center,
            child: Text("CALL"))
      ],
    );
  }

}

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
A RenderFlex overflowed by 99870 pixels on the bottom.
```

</details>

**Comment by dam-ease** [comment] 2023-11-02 12:52
Hi @maxdiable. Thanks for filing this. This seems to be the expected behaviour from the documentation, I see:

> If [TabBar.isScrollable] is false, tabs are stretched to fill the [TabBar]. Otherwise throws an exception.

Hence, the exception being thrown:

```
TabAlignment.fill is only valid for non-scrollable tab bars.
``` 
Closing this as this seems to be the expected behaviour when these two co-exist, if you disagree, please comment and I'll reopen this.
Thank you!

**Closed by dam-ease** 2023-11-02 12:52 UTC
Labels: in triage
