### ISSUE TITLE
Not getting translated in-app products

### ISSUE THREAD

**Issue by erperejildo** [flutter/flutter#51550] opened 2020-02-27 12:14 UTC
My problem is related with this package:
https://github.com/flutter/plugins/tree/master/packages/in_app_purchase

Probably a more related question to Google Play Console in general but because I'm using Flutter I'll consider it could be related.

I have 2 products properly setup on my console and I'm getting both of them on my app. So no problems related to the package itself either (https://pub.dev/packages/in_app_purchase).

Despite I have 2 languages I don't get the translated one when I change the language on my app. And this is normal, because I change it locally so Google Play Console has no idea (I guess).

-----
Here is my product translated:

[![enter image description here][1]][1]

After changing the app language I still getting always English:

[![enter image description here][2]][2]

  [1]: https://i.stack.imgur.com/XNBpR.png
  [2]: https://i.stack.imgur.com/DU19P.png

https://stackoverflow.com/questions/60429631/flutter-i-dont-get-translated-product-from-in-app-purchases

**Comment by erperejildo** [comment] 2020-02-27 12:14
As a temporal solution I thought about having just one language in GPC and include there the code that I use in my app for the translations so I'd have something like "offer.portfolios" instead "2 portfolios"

**Comment by om-ha** [comment] 2020-02-28 14:16
As a reference, since we're not getting the title localized when accessing [title property](https://github.com/flutter/plugins/blob/master/packages/in_app_purchase/lib/src/billing_client_wrappers/sku_details_wrapper.dart#L81) in `SKUDetailsWrapper` then yes I do think it's a Flutter issue. It's probably Anroid only because on iOS there's a [localized title property](https://github.com/flutter/plugins/blob/4411247270069e8b4d4969652b6c2d1d9b694d82/packages/in_app_purchase/lib/src/store_kit_wrappers/sk_product_wrapper.dart#L211) in `SKProductWrapper`

**Comment by BeMacized** [comment] 2021-05-05 14:24
Just checking in to ask if this is still a problem? 

I've tried reproducing this with the example app on Android.
For this I've set up all the in app purchases with `en-US` localization in the play console, with one of them also having its title and description localized in `nl-NL`.

After setting my system language to Dutch, I get the following result:
<img src="https://user-images.githubusercontent.com/1163070/117156302-d215cb80-adbd-11eb-8c87-29df2483506e.jpg" width="100">
The first item translated just fine, so I assume this is working correctly now.

**Comment by TahaTesser** [comment] 2021-05-27 12:51
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by TahaTesser** 2021-05-27 12:51 UTC
Labels: a: internationalization, p: first party, p: in_app_purchase, passed first triage, plugin

**Comment by erperejildo** [comment] 2021-05-27 15:46
> Without additional information, we are unfortunately not sure how to resolve this issue.
> We are therefore reluctantly going to close this bug for now.
> Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
> Thanks for your contribution.
> 
> Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
> All system setups can be slightly different, so it's always better to open new issues and reference related issues.

what additional information do you need?

**Comment by TahaTesser** [comment] 2021-05-28 12:07
hI @erperejildo 

Since there was no response to the question https://github.com/flutter/flutter/issues/51550#issuecomment-832730394, issue got closed without additional information, thanks

**Comment by erperejildo** [comment] 2021-05-28 19:21
Ok I see. I'll test this again then
