### ISSUE TITLE
[Camera] Black video with audio

### ISSUE THREAD

**Issue by zltnDC** [flutter/flutter#87911] opened 2021-08-08 15:03 UTC
## Description

Hello, I have a problem with the camera package. I have three components: Flutter for web, Android and iOS App. The mobile apps on one codebase. Mobile app sends a recorded video to the storage. All three components can play the video from the storage (using the video_player package). All videos recorded on iOS with camera: 0.8.1 are black on some browsers but they have audio. 

I used iPhone X, iOS 13.6 and the front camera.

I prepared a table with details:

| | Black video | 
| ------------- | ------------- |
|  iOS (iPhoneX, iOS 13.6) | no | 
| macOS (QuickTimePlayer) | no |
| Android (Xiaomi)|  no |
| Web App (chrome, macOS)| yes |
| Chrome browser(macOS)| yes |
| Web App (Safari, macOS)| no |
| Safari browser(macOS) | no|
| WebApp (chrome, Windows 10)|yes|
| Chrome browser(Windows 10)|yes|
| WebApp(firefox 86, Windows 10)|yes|
| Firefox 86 browser(Windows 10)|yes|
| Windows 10 (VLC and Windows Media Player)| no|

Packages in the apps:

Webapp:
video_player: ^1.0.1

Mobile app:
camera: ^0.8.1+7
video_player: ^1.0.1

After downgrade camera to 0.7.0+4, new recordings work on chrome.

<details>
  <summary>Flutter doctor</summary>
Web App:

```
flutter doctor -v
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-x64, locale pl-PL)
    • Flutter version 2.2.3 at /Users/name/fvm/versions/2.2.3
    • Framework revision f4abaa0735 (5 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4
```
Mobile App:

```
flutter doctor -v
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-x64, locale pl-PL)
    • Flutter version 2.2.3 at /Users/name/fvm/versions/2.2.3
    • Framework revision f4abaa0735 (5 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4
```
</details>

**Comment by maheshmnj** [comment] 2021-08-09 07:26
Hi @zltnDC,  Thanks for filing the issue could you please share a [minimal reproducible code](https://stackoverflow.com/help/minimal-reproducible-example) to better address the issue. I also see that you are using an older version of the video_player plugin could you please try updating to the latest `video_player: ^2.1.12`  and see if it fixes the issue.

Thanks.

**Comment by zltnDC** [comment] 2021-08-19 15:45
I think that this is not a problem with the video_player but with browsers and codecs:

https://github.com/flutter/plugins/blob/d2f5c33e94291cd21b9999fb02f4e3efb1f618b6/packages/video_player/video_player_web/README.md

- camera 0.7 -> H.264, AAC 
- camera 0.8 -> HEVC, AAC

Video recorded with camera: 0.7 is on the left and the other with camera: 0.8 is on the right.

<details>
  <summary>Image</summary>

![image](https://user-images.githubusercontent.com/56175965/130094940-ace1c4f4-44d4-4fbc-8eff-ccddb4300196.png)

</details>

I checked the video_player: 2.1.14 and the hevc video does not work on chrome

<details>
  <summary>Source code</summary>

pubspec.yaml
```
video_player: ^2.1.14
...
assets:
    - assets/video.mp4

```

main.dart
```

import 'package:flutter/material.dart';
import 'package:video_player/video_player.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  late VideoPlayerController controller;

  @override
  void initState() {
    super.initState();
    init();
  }

  Future<void> init() async {
    controller = VideoPlayerController.asset('assets/video.mp4');
    await controller.initialize();
    setState(() {});
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Demo'),
      ),
      body: controller.value.isInitialized == true
          ? SizedBox(
              width: 400,
              height: 400,
              child: Column(
                children: [
                  SizedBox(
                      width: 300, height: 300, child: VideoPlayer(controller)),
                  VideoProgressIndicator(
                    controller,
                    allowScrubbing: true,
                  ),
                  TextButton(
                      onPressed: () {
                        controller.play();
                      },
                      child: Text('Play'))
                ],
              ),
            )
          : SizedBox(),
    );
  }
}

```

</details>

Can you give an opportunity to change the codec or can you reuse H.264 ?

**Comment by maheshmnj** [comment] 2021-08-24 06:09
Hi, @zltnDC Could you please share the complete code sample showing how you are feeding the recorded video to the video_player to better address the issue.

Thanks.

**Comment by Soundvessel** [comment] 2021-08-24 23:31
> I think that this is not a problem with the video_player but with browsers and codecs:

I believe you are correct as I was just helping someone debug this issue. HEVC doesn't have wide browser support. Sadly Chrome and Firefox both marked the missing standard as a WONTFIX.

https://caniuse.com/hevc

As a workaround, you can ask the user to change their settings and not use that format. Instructions and some context here https://www.macworld.com/article/231501/how-to-disable-heif-and-hevc-formats-in-ios.html

**Comment by cfchris** [comment] 2021-08-24 23:43
If what @zltnDC says is true and camera 0.8+ changed the codec, that is unfortunate (for my company and our users). 

It is also the cause of an open support issue I have for our production application (new versions rolled out last week). For the most recent release, I updated to (camera: ^0.8.1+3). Now, some iOS users are not able to view the videos sent from the mobile phone to the CRM in Chrome (because the videos are encoded as "HEVC/H.265").

If the "camera" plugin was updated to allow some control of the codec (in order opt back into MPEG/H.264), that would definitely fix my issue.

**Comment by cfchris** [comment] 2021-08-30 17:55
@maheshmnj (cc @zltnDC ),

Please do not fixate on the video_player. This issue is related to the "camera" package. Older versions (as confirmed by @zltnDC downgrading "camera" to fix it) recorded videos in MPEG-4 (H264) on iOS and Android.

The newer versions of "camera" on newer iPhones records "MPEG-H (H.265)" (or HVEC?). This is a newer format from Apple that is not widely supported. This is where the "black video" is coming from. The browser (or video player) in question just doesn't support the codec. 

![image](https://user-images.githubusercontent.com/819847/131382514-85024a2c-e2e9-4849-ab27-f5055949a6a7.png)

We have been allowing users to send short videos from the camera package recorded at a low resolution for about a year. Last month I upgraded Flutter and all our packages to current versions. Now, many iOS users are getting complaints that the recipients cannot view the videos.

Given that the old version of the library could produce widely-supported MPEG-4 (H264) videos, and the newer versions are producing a somewhat proprietary Apple format, can we get a setting/property/etc added that allows us to opt out of Apple's HVEC format? Please?

**Comment by zltnDC** [comment] 2021-09-01 15:36
@maheshmnj We can use FirebaseStorage for example.

<details>
  <summary>Example</summary>
pubspec.yaml

```
name: camera_bugs
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  camera: ^0.9.2+1
  firebase_storage: ^8.0.0
  mime: ^1.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter

```
main.dart
```
import 'dart:async';
import 'dart:io';
import 'package:mime/mime.dart';

import 'package:flutter/material.dart';
import 'package:camera/camera.dart';

import 'package:firebase_core/firebase_core.dart' as firebase_core;
import 'package:firebase_storage/firebase_storage.dart' as firebase_storage;

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await firebase_core.Firebase.initializeApp();
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  CameraController _controller;

  @override
  void initState() {
    _initializeCameraController();
    super.initState();
  }

  Future<void> _initializeCameraController() async {
    final cameras = await availableCameras();
    cameras
        .sort((a, b) => a.lensDirection == CameraLensDirection.back ? -1 : 1);
    final camera = cameras.first;

    final controller = CameraController(camera, ResolutionPreset.max);
    await controller.initialize();

    _controller = controller;
    setState(() {});
  }

  Future<firebase_storage.UploadTask> uploadFile(XFile file) async {
    if (file == null) {
      ScaffoldMessenger.of(context).showSnackBar(const SnackBar(
        content: Text('No file was selected'),
      ));
      return null;
    }

    firebase_storage.UploadTask uploadTask;

    final mimeType = lookupMimeType(file.path);

    // Create a Reference to the file
    firebase_storage.Reference ref = firebase_storage.FirebaseStorage.instance
        .ref()
        .child('playground')
        .child(file.name);

    final metadata = firebase_storage.SettableMetadata(
      contentType: mimeType,
      customMetadata: {'picked-file-path': file.path},
    );

    uploadTask = ref.putFile(File(file.path), metadata);

    try {
      await Future.value(uploadTask);
    } catch (e) {
      print(e);
    }
  }

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  Future<void> _startVideo() async {
    await _controller.startVideoRecording();
    setState(() {});
  }

  Future<void> _stopRecord() async {
    final xfile = await _controller.stopVideoRecording();

    setState(() {});
    uploadFile(xfile);
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            if (_controller != null)
              SizedBox(
                width: 100,
                height: 100,
                child: CameraPreview(_controller),
              ),
          ],
        ),
      ),
      floatingActionButton: _controller != null
          ? FloatingActionButton(
              onPressed: () {
                if (_controller.value.isRecordingVideo) {
                  _stopRecord();
                } else {
                  _startVideo();
                }
              },
              child:
                  Text(_controller.value.isRecordingVideo ? 'Stop' : 'Start'),
            )
          : null,
    );
  }
}

```
</details>

The problem still occurs with the camera: ^0.9.2+1.

**Comment by cfchris** [comment] 2021-09-01 21:17
@TahaTesser this might as well be closed as a duplicate of https://github.com/flutter/flutter/issues/83074 also. I'm fairly sure the reason the videos won't play in the player are because of the encoding from the camera plugin. This is evidenced by the fact that if the OP rolls back to the old camera plugin, it works.

**Comment by maheshmnj** [comment] 2021-09-02 13:37
@zltnDC  thanks for the code sample could you also share how you are fetching the video from the Firebase storage?
Ps: the local recorded videos via camera works fine

Thanks

**Comment by TahaTesser** [comment] 2021-09-23 12:08
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by TahaTesser** 2021-09-23 12:08 UTC
