### ISSUE TITLE
When shrinkWrap is true, the SliverAppBar is displayed below the elements of the SliverList or SliverGrid.

### ISSUE THREAD

**Issue by luoqiao6** [flutter/flutter#28197] opened 2019-02-20 08:52 UTC
## Steps to Reproduce

1. [here](https://github.com/luoqiao6/A_Bug_of_CustomScrollView_and_SliverAppBar) is the code repository to reproduce the bug.

2. Normally, when the `shrinkWrap` of the `CustomScrollView` is `false`, the floating `SliverAppBar` will be displayed on the upper layer of the `SliverList` or `SliverGrid` as we slide the `SliverList` down.

 ![SliverAppBar displayed on the upper layer ](https://raw.githubusercontent.com/luoqiao6/A_Bug_of_CustomScrollView_and_SliverAppBar/master/res/bug0.png " ")

3. But, when change the value of `shrinkWrap` to `true`, the `SliverAppBar` is displayed below the elements of the `SliverList` or `SliverGrid`.

 ![SliverAppBar displayed below the SliverList ](https://raw.githubusercontent.com/luoqiao6/A_Bug_of_CustomScrollView_and_SliverAppBar/master/res/bug1.png " ")

Why does `shrinkWrap` affect the display of `SliverAppBar`?

## flutter analyze 
```
localhost:a_custom_scroll_view_bug luoqiao$ flutter analyze
Analyzing a_custom_scroll_view_bug...                            
No issues found! (ran in 2.7s)
localhost:a_custom_scroll_view_bug luoqiao$ 
```

## flutter doctor -v
```
localhost:a_custom_scroll_view_bug luoqiao$ flutter doctor -v 
[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.14.3 18D109, locale zh-Hans-CN)
    • Flutter version 1.0.0 at /Users/luoqiao/flutter/flutter_v1.0.0-stable
    • Framework revision 5391447fae (3 months ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/luoqiao/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/luoqiao/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 2.0.0
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 29.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.1.5)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 29.0.2
    • Dart plugin version 181.4892.1

[!] VS Code (version 1.31.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

! Doctor found issues in 1 category.
localhost:a_custom_scroll_view_bug luoqiao$ 

```

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return CustomScrollView(
      shrinkWrap: false,
      slivers: <Widget>[
        const SliverAppBar(
          pinned: false,
          floating: true,
          //expandedHeight: 250.0,
          //backgroundColor: Colors.purpleAccent,
          flexibleSpace: FlexibleSpaceBar(
            title: Text('SliverAPPBar'),
          ),
        ),
        SliverGrid.count(
          crossAxisCount: 3,
          children: [
            Padding(
              padding: EdgeInsets.only(left: 24.0, right: 24.0),
              child: Container(color: Colors.red, height: 150.0),
            ),
            Padding(
              padding: EdgeInsets.only(left: 24.0, right: 24.0),
              child: Container(color: Colors.purple, height: 150.0),
            ),
            Padding(
              padding: EdgeInsets.only(left: 24.0, right: 24.0),
              child: Container(color: Colors.green, height: 150.0),
            ),
            Padding(
              padding: EdgeInsets.only(left: 24.0, right: 24.0),
              child: Container(color: Colors.orange, height: 150.0),
            ),
            Padding(
              padding: EdgeInsets.only(left: 24.0, right: 24.0),
              child: Container(color: Colors.yellow, height: 150.0),
            ),
            Padding(
              padding: EdgeInsets.only(left: 24.0, right: 24.0),
              child: Container(color: Colors.pink, height: 150.0),
            ),
            Padding(
              padding: EdgeInsets.only(left: 24.0, right: 24.0),
              child: Container(color: Colors.cyan, height: 150.0),
            ),
            Padding(
              padding: EdgeInsets.only(left: 24.0, right: 24.0),
              child: Container(color: Colors.indigo, height: 150.0),
            ),
            Padding(
              padding: EdgeInsets.only(left: 24.0, right: 24.0),
              child: Container(color: Colors.blue, height: 150.0),
            ),
          ],
        ),
        SliverList(
          delegate: SliverChildListDelegate(
            [
              Padding(
                padding: EdgeInsets.only(left: 24.0, right: 24.0),
                child: Container(color: Colors.pink, height: 100.0),
              ),
              Padding(
                padding: EdgeInsets.only(left: 24.0, right: 24.0),
                child: Container(color: Colors.cyan, height: 100.0),
              ),
              Padding(
                padding: EdgeInsets.only(left: 24.0, right: 24.0),
                child: Container(color: Colors.indigo, height: 100.0),
              ),
              Padding(
                padding: EdgeInsets.only(left: 24.0, right: 24.0),
                child: Container(color: Colors.blue, height: 100.0),
              ),
              Padding(
                padding: EdgeInsets.only(left: 24.0, right: 24.0),
                child: Container(color: Colors.yellow, height: 100.0),
              ),
            ],
          ),
        ),
        SliverFixedExtentList(
          itemExtent: 150.0,
          delegate: SliverChildListDelegate(
            [
              Padding(
                padding: EdgeInsets.only(left: 24.0, right: 24.0),
                child: Container(color: Colors.red, height: 150.0),
              ),
              Padding(
                padding: EdgeInsets.only(left: 24.0, right: 24.0),
                child: Container(color: Colors.purple, height: 150.0),
              ),
              Padding(
                padding: EdgeInsets.only(left: 24.0, right: 24.0),
                child: Container(color: Colors.green, height: 150.0),
              ),
              Padding(
                padding: EdgeInsets.only(left: 24.0, right: 24.0),
                child: Container(color: Colors.orange, height: 150.0),
              ),
              Padding(
                padding: EdgeInsets.only(left: 24.0, right: 24.0),
                child: Container(color: Colors.yellow, height: 150.0),
              ),
              Padding(
                padding: EdgeInsets.only(left: 24.0, right: 24.0),
                child: Container(color: Colors.pink, height: 150.0),
              ),
              Padding(
                padding: EdgeInsets.only(left: 24.0, right: 24.0),
                child: Container(color: Colors.cyan, height: 150.0),
              ),
              Padding(
                padding: EdgeInsets.only(left: 24.0, right: 24.0),
                child: Container(color: Colors.indigo, height: 150.0),
              ),
              Padding(
                padding: EdgeInsets.only(left: 24.0, right: 24.0),
                child: Container(color: Colors.blue, height: 150.0),
              ),
            ],
          ),
        ),
      ],
    );
  }
}
```

**Comment by zoechi** [comment] 2019-02-20 09:03
Have you tried to get an answer on StackOverflow?

**Comment by luoqiao6** [comment] 2019-02-20 09:39
> Have you tried to get an answer on StackOverflow?
I tried,  but didn't find any answer

**Comment by zoechi** [comment] 2019-02-20 09:44
Please post the link to the question.

**Comment by luoqiao6** [comment] 2019-02-20 09:53
Oh, I mean, I found the answer of this question online (including on stackoverflow) by google.  I didn't ask questions on stackoverflow. I think this is a bug of flutter and feedback here.

**Comment by zoechi** [comment] 2019-02-20 10:05
The link the the question would still be interesting.

**Comment by zoechi** [comment] 2019-02-20 15:42
Related SO question https://stackoverflow.com/questions/54790024/why-is-the-sliverappbar-of-the-customscrollview-displayed-below-the-elements-of

**Comment by luoqiao6** [comment] 2019-02-20 16:19
I have now raised a question about this on stackoverflow.  [https://stackoverflow.com/questions/54790024/why-is-the-sliverappbar-of-the-customscrollview-displayed-below-the-elements-of](https://stackoverflow.com/questions/54790024/why-is-the-sliverappbar-of-the-customscrollview-displayed-below-the-elements-of)

**Comment by luoqiao6** [comment] 2019-02-20 16:27
> Related SO question https://stackoverflow.com/questions/54790024/why-is-the-sliverappbar-of-the-customscrollview-displayed-below-the-elements-of

I asked just a moment ago.

**Comment by thanhhuan1990** [comment] 2019-04-22 02:34
I got exactly same issue. But still not have support from 2 month ago ?

**Comment by lukepighetti** [comment] 2019-07-11 17:26
You can try `floating: true`

**Comment by lukepighetti** [comment] 2019-07-11 17:29
Not only that, but when I try to scroll down, the SliverAppBar goes up, when I try to scroll up, the contents go up.

**Comment by jerrywell** [comment] 2019-11-08 10:08
this is a painful bug, it even break the layout and UX design. is there any workaround?

**Comment by knaeckeKami** [comment] 2019-11-14 16:45
@jerrywell Wrapping the SliverAppBar in a SliverSafeArea prevents it from scrolling up.

**Comment by marcinretecki** [comment] 2020-01-31 20:39
Is there any plan to solve this? Or any comment on how to workaround it?

**Comment by dnazarov** [comment] 2020-03-15 20:44
``` dart
class ExcursionCardPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: Container(
            child: CustomScrollView(
              shrinkWrap: true,
              dragStartBehavior: DragStartBehavior.down,
              slivers: <Widget>[
                SliverSafeArea(
                  top: false, bottom: false,
                  sliver: 
                  SliverAppBar(
                    pinned: true,
                    floating: false,
                    expandedHeight: 200.0,
                    flexibleSpace: FlexibleSpaceBar(
                      background: Image.network( item.url, fit: BoxFit.cover) ),
                  ),
                ),
               
                SliverList(
                    delegate: SliverChildBuilderDelegate((BuildContext context, int index) {
                      return Container(
                        height: 200,
                        color: Colors.yellow,
                      );
                    },
                    )
                )
              ],
            )
        )
    );
  }
} 
```

It works but the pinned flag doesn't work well.

**Comment by VladyslavBondarenko** [comment] 2020-04-06 13:03
Persists with `dev v1.18.0`

**Comment by marcosmko** [comment] 2020-09-27 02:00
Hello, I have this problem too.

Persists with v1.22 and v1.23 (pre release).

Any news on that?

**Comment by RyanVDW** [comment] 2020-11-25 02:26
Still having this issue on 1.22.4. Been pulling my hair out for hours trying to figure out why this is happening to me!

**Comment by NWalker1208** [comment] 2021-01-01 18:54
I am also experiencing this bug. Has anyone delved into the source code to figure out why this may be happening?

**Comment by NWalker1208** [comment] 2021-01-01 20:35
Update: I took a look at the source code for the ShrinkWrappingViewport and found the issue. While the standard Viewport paints all children after and including the center child in reverse order, the shrink-wrapping one does so in the order the children are given. Therefore, the SliverAppBar gets painted over by any other slivers after it. I am submitting a pull request that fixes this issue.

**Comment by BazinC** [comment] 2021-01-19 11:54
@NWalker1208 Thank you for the patch! 🙌 I tried it and confirm it solves the overlapping issue.

Now it still the [scroll up issue](https://github.com/flutter/flutter/issues/28197#issuecomment-510579539) to tackle down..😣

**Comment by maheshmnj** [comment] 2022-12-06 04:00
Hi @luoqiao6, I verified your code sample on stable and the master channel and I can no longer reproduce it.

https://user-images.githubusercontent.com/31410839/205809659-edd397e9-33b5-4c54-894f-3af4ca4b7f7c.mov

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key? key,required this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return CustomScrollView(
      shrinkWrap: true,
      slivers: <Widget>[
        const SliverAppBar(
          pinned: false,
          floating: true,
          //expandedHeight: 250.0,
          //backgroundColor: Colors.purpleAccent,
          flexibleSpace: FlexibleSpaceBar(
            title: Text('SliverAPPBar'),
          ),
        ),
        SliverGrid.count(
          crossAxisCount: 3,
          children: [
            Padding(
              padding: EdgeInsets.only(left: 24.0, right: 24.0),
              child: Container(color: Colors.red, height: 150.0),
            ),
            Padding(
              padding: EdgeInsets.only(left: 24.0, right: 24.0),
              child: Container(color: Colors.purple, height: 150.0),
            ),
            Padding(
              padding: EdgeInsets.only(left: 24.0, right: 24.0),
              child: Container(color: Colors.green, height: 150.0),
            ),
            Padding(
              padding: EdgeInsets.only(left: 24.0, right: 24.0),
              child: Container(color: Colors.orange, height: 150.0),
            ),
            Padding(
              padding: EdgeInsets.only(left: 24.0, right: 24.0),
              child: Container(color: Colors.yellow, height: 150.0),
            ),
            Padding(
              padding: EdgeInsets.only(left: 24.0, right: 24.0),
              child: Container(color: Colors.pink, height: 150.0),
            ),
            Padding(
              padding: EdgeInsets.only(left: 24.0, right: 24.0),
              child: Container(color: Colors.cyan, height: 150.0),
            ),
            Padding(
              padding: EdgeInsets.only(left: 24.0, right: 24.0),
              child: Container(color: Colors.indigo, height: 150.0),
            ),
            Padding(
              padding: EdgeInsets.only(left: 24.0, right: 24.0),
              child: Container(color: Colors.blue, height: 150.0),
            ),
          ],
        ),
        SliverList(
          delegate: SliverChildListDelegate(
            [
              Padding(
                padding: EdgeInsets.only(left: 24.0, right: 24.0),
                child: Container(color: Colors.pink, height: 100.0),
              ),
              Padding(
                padding: EdgeInsets.only(left: 24.0, right: 24.0),
                child: Container(color: Colors.cyan, height: 100.0),
              ),
              Padding(
                padding: EdgeInsets.only(left: 24.0, right: 24.0),
                child: Container(color: Colors.indigo, height: 100.0),
              ),
              Padding(
                padding: EdgeInsets.only(left: 24.0, right: 24.0),
                child: Container(color: Colors.blue, height: 100.0),
              ),
              Padding(
                padding: EdgeInsets.only(left: 24.0, right: 24.0),
                child: Container(color: Colors.yellow, height: 100.0),
              ),
            ],
          ),
        ),
        SliverFixedExtentList(
          itemExtent: 150.0,
          delegate: SliverChildListDelegate(
            [
              Padding(
                padding: EdgeInsets.only(left: 24.0, right: 24.0),
                child: Container(color: Colors.red, height: 150.0),
              ),
              Padding(
                padding: EdgeInsets.only(left: 24.0, right: 24.0),
                child: Container(color: Colors.purple, height: 150.0),
              ),
              Padding(
                padding: EdgeInsets.only(left: 24.0, right: 24.0),
                child: Container(color: Colors.green, height: 150.0),
              ),
              Padding(
                padding: EdgeInsets.only(left: 24.0, right: 24.0),
                child: Container(color: Colors.orange, height: 150.0),
              ),
              Padding(
                padding: EdgeInsets.only(left: 24.0, right: 24.0),
                child: Container(color: Colors.yellow, height: 150.0),
              ),
              Padding(
                padding: EdgeInsets.only(left: 24.0, right: 24.0),
                child: Container(color: Colors.pink, height: 150.0),
              ),
              Padding(
                padding: EdgeInsets.only(left: 24.0, right: 24.0),
                child: Container(color: Colors.cyan, height: 150.0),
              ),
              Padding(
                padding: EdgeInsets.only(left: 24.0, right: 24.0),
                child: Container(color: Colors.indigo, height: 150.0),
              ),
              Padding(
                padding: EdgeInsets.only(left: 24.0, right: 24.0),
                child: Container(color: Colors.blue, height: 150.0),
              ),
            ],
          ),
        ),
      ],
    );
  }
}
```
</details> 

<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel master, 3.7.0-3.0.pre.33, on macOS 12.6 21G115 darwin-arm64, locale en-IN)
    • Flutter version 3.7.0-3.0.pre.33 on channel master 
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5201856805 (38 minutes ago), 2022-12-05 18:27:21 -0800
    • Engine revision a309d239c4
    • Dart version 2.19.0 (build 2.19.0-463.0.dev)
    • DevTools version 2.20.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly
      to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.70.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.55.20221129

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • 026D5789-9E78-4AD5-B1B2-3F8D4E7F65E4 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.6 21G115 darwin-arm64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 108.0.5359.94

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
```
[✓] Flutter (Channel stable, 3.3.9, on macOS 12.6 21G115 darwin-arm, locale en-IN)
    • Flutter version 3.3.9 on channel stable at /Users/mahesh/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b8f7f1f986 (24 hours ago), 2022-11-23 06:43:51 +0900
    • Engine revision 8f2221fbef
    • Dart version 2.18.5
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.70.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.53.20221101

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • 026D5789-9E78-4AD5-B1B2-3F8D4E7F65E4 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.6 21G115 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 107.0.5304.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

Closing, Since it is no longer reproducible, Incase anyone still faces the issue.  Please feel free to write in the comments and we will reopen it.

**Closed by maheshmnj** 2022-12-06 04:00 UTC
Labels: framework, f: scrolling, has reproducible steps, P4, found in release: 1.21
