### ISSUE TITLE
Image Loading Problem in Release Version (results in pink container areas)

### ISSUE THREAD

**Issue by hm122** [flutter/flutter#71074] opened 2020-11-23 12:26 UTC
Internal: b/176078297

I'm facing a really strange problem, and really don't know how to fix this. It seems, that on some devices image assets are not properly loaded and a pink (fuchsia?, magenta?) colored area is shown instead. All types of images are affected (Network loaded images, images shown as Container decoration, and also Asset Images).
I'm not able to reproduce this on my devices, neither as debug, nor as release, neither on iOS nor on Android. The clients device with this problem is a iPhone 12 Pro, iOS: 14.2.1.

Does anybody have seen something like this or can give me a hint about what could cause this?

![image (1)](https://user-images.githubusercontent.com/13405226/99961773-49671e00-2d8f-11eb-8a36-6387e13f2016.png)

**Comment by pedromassangocode** [comment] 2020-11-23 12:53
Hi @hm122 
Can you please provide your `flutter doctor -v` and a minimal complete reproducible code sample of the screen you shared above?
Thank you

**Comment by hm122** [comment] 2020-11-23 13:43
Hi @pedromassangocode , thank you for your fast reply. Following the `flutter doctor -v` output:
```
flutter doctor -v
[✓] Flutter (Channel stable, 1.22.4, on Mac OS X 10.15.7 19H2 darwin-x64, locale en-AT)
    • Flutter version 1.22.4 at /Users/hannes/Applications/flutter
    • Framework revision 1aafb3a8b9 (10 days ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/hannes/Library/Android/sdk
    • Platform android-30, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.9.1

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
```
I can not reproduce the issue with my devices, even with my clients device it only happens _sometimes_. Right now, I can not reproduce it anymore. My feeling is that this is kind of a timing issue. My client told me that when he is browsing through the app after a few seconds some images start to appear correctly. But then, if he closes the app and reopens it, everything seems to be working alright. 

I'm using the following code to load images:

```
Container(
  margin: EdgeInsets.fromLTRB(0, 0, margin, 0),
  decoration: BoxDecoration(
    boxShadow: [
      BoxShadow(
        color: Color.fromARGB(45, 0, 0, 0),
        offset: new Offset(2, 8),
        blurRadius: 15.0,
      )
    ],
  ),
  child: Image.asset('assets/images/foobar.png'),
);
```

```
Container(
  decoration: BoxDecoration(
    image: DecorationImage(
      image: AssetImage('assets/images/foobar.png'),
      alignment: Alignment.topCenter,
      fit: BoxFit.fitWidth,
    ),
    boxShadow: [
      BoxShadow(
        color: Color.fromARGB(45, 0, 0, 0),
        offset: new Offset(2, 8),
        blurRadius: 15.0,
      )
    ],
),
```

I got one more screenshot from my client, when the problem was discovered first:

<img width="340" alt="Screenshot 2020-11-23 at 14 32 27" src="https://user-images.githubusercontent.com/13405226/99967941-ca76e300-2d98-11eb-9c36-26ca59f7210a.png">

You can see here, that the tile on the right has successfully loaded an image, while the other tiles do have the pink area. One more thing I would like the add, I have never used this pink color anywhere in the whole app.

**Comment by atrope** [comment] 2020-11-25 16:01
it is also happening with us.
Only iOS 10 AFAIK and in my iOS 10 is not happening.

Assets and Internet image:


![image](https://user-images.githubusercontent.com/2945478/100252044-36cf1f00-2f1e-11eb-8647-05a023bd840f.png)
![image](https://user-images.githubusercontent.com/2945478/100252068-3cc50000-2f1e-11eb-97b7-3d5bdd90a906.png)
![image](https://user-images.githubusercontent.com/2945478/100252084-42224a80-2f1e-11eb-9b27-9001383ce091.png)

**Comment by plank-george** [comment] 2020-12-13 09:51
This problem occurs in out project , too. After user switch the app to background for a long time and then switch it back , the Image widget will turn to pink block.

**Comment by 13006210190** [comment] 2021-01-13 05:26
I have the same problem too.Who knows what caused this

**Comment by mio4kon** [comment] 2021-01-25 04:00
I have the same problem too，flutter version: 1.12.13-hotfix.9

**Comment by 2dxgujun** [comment] 2021-02-05 08:02
Same problem, flutter 1.22.4, iPhone. Unable to reproduce on my devices

**Comment by mdalihusain** [comment] 2021-02-17 09:18
Same issue on one of my clients device..
Device - iphone 12 mini![IMG-20210217-WA0019.jpg](https://user-images.githubusercontent.com/55429814/108182573-29958b00-712f-11eb-9f5f-15bdb2db06f1.jpg)

**Comment by pedromassangocode** [comment] 2021-02-17 10:59
For anyone facing this issue please try to provide a minimal reproducible code sample and the steps to reproduce the issue as well so that we can verify the issue and looking for fix.

Thank you

**Comment by chinmaygarde** [comment] 2021-02-17 18:14
Looks like a serious regression. Trying to find an assignee for this ASAP.

**Comment by gaaclarke** [comment] 2021-02-17 22:42
I suspect this is may be because of a missing texture.  The shader is using a sampler with an unbound texture.  Pink is often used for that error.

One way to validate that this is a renderer problem, and not an image file problem, would be to render a layout that depends on the size of the image.  If we get a pink image still and the widget is the correct size that would point to this being a renderer only issue.

**Comment by gaaclarke** [comment] 2021-02-17 23:35
I tried as an experiment to bind nil for the textures to see if it draws magenta:
```diff
--- a/src/gpu/mtl/GrMtlPipelineState.mm
+++ b/src/gpu/mtl/GrMtlPipelineState.mm
@@ -123,8 +123,14 @@ void GrMtlPipelineState::bindUniforms(id<MTLRenderCommandEncoder> renderCmdEncod
 void GrMtlPipelineState::bindTextures(id<MTLRenderCommandEncoder> renderCmdEncoder) {
     SkASSERT(fNumSamplers == fSamplerBindings.count());
     for (int index = 0; index < fNumSamplers; ++index) {
-        [renderCmdEncoder setFragmentTexture: fSamplerBindings[index].fTexture
-                                     atIndex: index];
+        static int i = 0;
+        if (i++ % 2 == 0) {
+            [renderCmdEncoder setFragmentTexture: nil
+                                         atIndex: index];
+        } else {
+            [renderCmdEncoder setFragmentTexture: fSamplerBindings[index].fTexture
+                                         atIndex: index];
+        }
         [renderCmdEncoder setFragmentSamplerState: fSamplerBindings[index].fSampler->mtlSampler()
                                           atIndex: index];
     }
```
It rendered clear, not magenta.  It could be some other error in the shader, too.  It's hard to google but someone on the skia team suspected the magenta is coming from Metal to represent some error and not Skia.  The console log might provide clues if Metal is printing out an error.

**Comment by blondie63** [comment] 2021-02-23 08:19
About blondie63/pic4flutter#23, below the screenshot on iPhone 12 pro Max & iOS 14.4
Flutter (Channel stable, 1.22.6, on macOS 11.2.1 20D74 darwin-x64, locale it-IT)
![pic4flutter-ios-resuming](https://user-images.githubusercontent.com/1261851/108817384-1e6fae80-75b8-11eb-80fd-a3e615fe9230.png)

**Comment by gaaclarke** [comment] 2021-02-23 21:44
Here is a proposed fix https://github.com/flutter/engine/pull/24503, can someone that can reproduce the bug please try it out since we don't have reproduction code.

**Comment by Hixie** [comment] 2021-03-03 00:04
https://github.com/flutter/engine/pull/24503 has now landed, which should make it easier for people to verify it they can reproduce it.

**Comment by blondie63** [comment] 2021-03-03 21:16
Flutter 2.0.0 fix it ?

**Comment by gaaclarke** [comment] 2021-03-03 21:23
The PR I made that I hope fixes the issue isn't in 2.0, it is currently on 2.1.0-10.0.pre and master.  If we get feedback that the PR fixed the issue I can propose it for a hotfix.  **If you have reproduction code we are still looking for it**, I'm unable to reproduce the issue.  I think it may have to do with how much time your app is occupying on the main thread when it's launched.  You can also try out the fix if you have the ability to reproduce the problem.

**Comment by plank-george** [comment] 2021-03-04 10:25
i am glad to see your efforts. Actually , the code to reproduce the issue is very simple. https://github.com/flutter/flutter/issues/71074#issuecomment-732170040
the previous comments has already given you a sample , and actually , i find that , even you only use a single Image.asset, the problem will occur in special circumstance .**The points to reproduce the problem is not how complicated the code is , but the following steps you do .**
1, Do not try to reproduce this problem in debug mode or in any simulator, it happened when a released flutter app was installed in an actual device.
2, Now **all** the issues occurs on the **iPhone 12** , so use an actual iPhone 12 to reproduce and verify it.
3, Remember to switch the app to the background for a time long enough maybe 12-20 hours .
4, Switch the app back to the screen and make sure the app is resumed instead of restarted as the app maybe closed by the system. If the app was restarted , wait for another 12 hours. The issue will not occur when the app is restarted.
5, If you are patient enough to complete the above four steps , then you are very probably to see the Image widgets turned to be pink block.

In my research , this issue maybe caused by the iPhone12 GC mechanism. In iPhone12 ,it allows app to stay a long time in the background , so the app can keep its state without being closed by the system. But the cached bytes and the GPU resources that used to render the Image has been released. So the page and layout can keep fine, but Image turns to be pink block (Is it the placeholder by Flutter engine on iPhone12? ).

I hope these information can help you. Best wishes.

**Comment by Dokay** [comment] 2021-03-04 12:36
@plank-george with your reproduce steps,  whether https://github.com/flutter/engine/pull/24503 fix the problem?

**Comment by chinmaygarde** [comment] 2021-03-08 18:41
@gaaclarke: Are you able to reproduce the problem post the patch with @plank-george s [instructions](https://github.com/flutter/flutter/issues/71074#issuecomment-790507664)?

**Comment by gaaclarke** [comment] 2021-03-09 23:52
@chinmaygarde I did not try those steps since they require 12-20 hours.  Even if I could reproduce it with those steps, it isn't helpful if every iteration takes 20 hours.  I used the steps listed in the internal bug, launching the app via a notification.  I want to try with firebase test notifications.  That got stymied since I had to wait around for approval to create firebase projects.  I should be able to try that now.

**Comment by gaaclarke** [comment] 2021-03-10 22:27
I hooked up firebase messaging and was unable to reproduce the problem when launching the app either from being backgrounded or a fresh launch (as per the steps specified in the internal bug):

```dart
import 'package:flutter/material.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:firebase_core/firebase_core.dart';

Future<void> main() async {
  runApp(MyApp());

  await Firebase.initializeApp();
  NotificationSettings settings =
      await FirebaseMessaging.instance.requestPermission(
    alert: true,
    announcement: false,
    badge: true,
    carPlay: false,
    criticalAlert: false,
    provisional: false,
    sound: true,
  );
  print(settings.authorizationStatus);
  print(await FirebaseMessaging.instance.getToken());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Container(
        margin: EdgeInsets.fromLTRB(0, 0, 5, 0),
        decoration: BoxDecoration(
          boxShadow: [
            BoxShadow(
              color: Color.fromARGB(45, 0, 0, 0),
              offset: new Offset(2, 8),
              blurRadius: 15.0,
            )
          ],
        ),
        child: Image.asset('assets/1.png'),
      ),
    );
  }
}
```

It may be that the 20hr backgrounding is required to reproduce the bug and that the notifications was a red herring.  I tried it on 2.0 and on the master channel.

**Comment by onikiri2007** [comment] 2021-03-11 06:50
I've tried master channel with example app and steps provided by @pawlowskim in this [comment](https://github.com/flutter/flutter/issues/64558#issuecomment-772305972). it didn't fix the issue.
using iPhone 7 with iOS 14.4

**Comment by gaaclarke** [comment] 2021-03-11 22:36
Thanks @onikiri2007, I was able to reproduce that bug with those steps.  I suspect they are the same issue, just my device doesn't happen to draw them as magenta.

**Comment by rohanj1132** [comment] 2021-03-12 06:15
@gaaclarke 
based on our testing - iPhone 12 draws them as magenta, iPhone 11 does not draw them at all/transparent

**Closed** 2021-03-15 21:22 UTC
Labels: P2, a: images, customer: crowd, engine, framework, passed first triage, platform-ios, severe: rendering

**Comment by AlexV525** [comment] 2021-04-22 06:36
Re-requesting cp since it's a P2.

**Comment by MirceaX2Mobile** [comment] 2021-04-23 15:54
Is this on stable right now?

**Comment by blackmenthor** [comment] 2021-04-26 05:24
I also still got the same issue on the latest Flutter Version. 

Happened on iPhone 11. Image below:

![pink container issue](https://user-images.githubusercontent.com/12998697/116032625-392ed400-a68a-11eb-976a-54375153c2d4.jpg)

**Comment by gaaclarke** [comment] 2021-04-26 17:14
The latest stable release doesn't have the fix yet: https://github.com/flutter/flutter/commit/4266d629c26213ac5cd3f51c875f84e408d33a14

**Comment by tryadelion** [comment] 2021-05-04 08:11
shouldn't be closed/fixed until released on stable branch.

**Comment by gaaclarke** [comment] 2021-05-12 18:08
@tryadelion closing issues when they are fixed on `master` has always been the policy of the team.  You can track the PR's progress with the link I provided above: https://github.com/flutter/flutter/commit/4266d629c26213ac5cd3f51c875f84e408d33a14  I don't have a good idea about when it will land on stable.  You can ask on the discord channel `hackers-releases`.

**Comment by tryadelion** [comment] 2021-05-18 08:01
@gaaclarke thanks - and sorry, I wasn't trying to sound so imperative, & not trying to say it isn't the policy - just that the flow of the issue is lost once the PR is merged, and in the case of issues that have no workaround at all and affect production devices, like here, we've been answering to customer support for weeks in a not-so-fancy-for-them Indiana Jones way...

![tenor (1)](https://user-images.githubusercontent.com/3778474/118614184-c8c62f00-b7bf-11eb-8eca-64cb32e069ea.gif)

**Comment by AlexV525** [comment] 2021-05-19 02:23
And the good news is it's been rolled into the latest stable (2.2.0) with 4266d62 . Please let us know if the issue still exist.

**Comment by swoderheart** [comment] 2021-06-23 08:30
Has everyone solved this problem? I still encounter it.
