### ISSUE TITLE
video player not having mute and full screen feature for flutter

### ISSUE THREAD

**Issue by saurabhksinha9000** [flutter/flutter#60747] opened 2020-07-02 05:54 UTC
video player not having mute and full screen feature for flutter

**Comment by TahaTesser** [comment] 2020-07-02 07:33
Hi @saurabhksinha9000 
You can the set volume `controller.setVolume(0.0);`
https://github.com/flutter/plugins/blob/a2b5a777beaf54df591303c8e7c545c8950dcf9b/packages/video_player/example/lib/main.dart#L51

For fullscreen feature, Closing as duplicate of https://github.com/flutter/flutter/issues/58114

**Closed by TahaTesser** 2020-07-02 07:33 UTC
