### ISSUE TITLE
App title is set to null if not set in MaterialApp constructor

### ISSUE THREAD

**Issue by KevinTheGray** [flutter/flutter#10315] opened 2017-05-25 18:06 UTC
If you don't set the title property of a MaterialApp, it will display as null.

## Steps to Reproduce
Create a new MaterialApp and do not set the title of the app in the constructor.  On Android, if you do this, run the app, and then view it in the list of open applications, it will show "null" as the title.

**Comment by charafau** [comment] 2017-06-02 03:29
I would like to fix this or. What is the expected behavior?

**Comment by eseidelGoogle** [comment] 2017-06-02 04:27
I would expect title: null passed to MaterialApp to do nothing (not call out to the Android/iOS code to set the title and instead let iOS/Android use whatever is their default behavior).

Alternatively, title should be marked as `@required` if null is not a valid default value.

**Comment by Hixie** [comment] 2017-06-02 18:54
Fundamentally the problem on Android (I didn't check iOS) is that there's no way to say "don't set the title, just leave it as is, but do change the color":

<https://developer.android.com/reference/android/app/ActivityManager.TaskDescription.html#ActivityManager.TaskDescription(java.lang.String, android.graphics.Bitmap, int)>

**Comment by eseidelGoogle** [comment] 2017-06-02 19:30
Can one read the current title and set it back to what it currently is?

**Comment by gspencergoog** [comment] 2017-06-16 00:14
This is a duplicate of https://github.com/flutter/flutter/issues/6802

**Comment by MarcinusX** [comment] 2017-11-14 13:29
If this is duplicate of #6802 and #6802 is closed. Shouldn't this be closed too?

**Comment by Hixie** [comment] 2017-11-14 17:56
Yup, thanks for catching that!

**Closed by Hixie** 2017-11-14 17:56 UTC
Labels: customer: posse (eap), easy fix
