### ISSUE TITLE
`ScrollView` doesn't respect preference for scroll direction.

### ISSUE THREAD

**Issue by gspencergoog** [flutter/flutter#150596] opened 2024-06-21 02:16 UTC
## Description

On MacOS desktop at least, scroll view doesn't respect proference for scroll direction. I have my trackpad default set to turn off "natural" scrolling (or, as I call it "unnatural" scrolling :-) ), but on Flutter apps it doesn't respect that and tries to scroll in natural direction.

Building for Chrome on macOS works properly.

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MaterialApp(
    home: Home(),
  ));
}

class Home extends StatelessWidget {
  const Home({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: ListView(
        children: <Widget>[
          for (int i = 0; i < 100; ++i) Card(child: Text('Item $i')),
        ],
      ),
    );
  }
}
```

I bisected the problem to change 8897555a8faf1d74c6075814dd918564c363a994 but I was seeing some odd behavior on some of the "bad" commits, where if I flung the scroll it would go the "right" direction, but otherwise go the wrong (natural) direction, so I may not have arrived at the actual bad commit, but it is probably near there.  I was unable to reproduce the problem on the beta channel, so the regression is fairly recent.

That PR is an engine roll, and none of the commit descriptions look likely to be the problem to me, but I didn't look into it deeply.

<details>
<summary>Details</summary>

<pre>
[✓] Flutter (Channel main, 3.23.0-13.0.pre.248, on macOS 14.5 23F79 darwin-arm64, locale en)
    • Flutter version 3.23.0-13.0.pre.248 on channel main at /Users/username/code/flutter
    • Upstream repository git@github.com:flutter/flutter.git
    • Framework revision ccf3abe940 (3 days ago), 2024-06-17 14:06:00 -0400
    • Engine revision 5989f0215f
    • Dart version 3.5.0 (build 3.5.0-270.0.dev)
    • DevTools version 2.36.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/username/Library/Android/sdk
    • Platform android-34, build-tools 33.0.0
    • ANDROID_HOME = /Users/username/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] Android Studio (version 4.0)
    • Android Studio at /Users/username/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6514223/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2022.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 70.0.4
    • Dart plugin version 221.5921.27

[✓] VS Code (version 1.90.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.90.0

[✓] Connected device (3 available)
    • macOS (desktop)                 • macos                 • darwin-arm64   • macOS 14.5 23F79 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         • macOS 14.5 23F79 darwin-arm64
    • Chrome (web)                    • chrome                • web-javascript • Google Chrome 126.0.6478.62

[✓] Network resources
    • All expected network resources are available.

• No issues found!
</pre>

</details>

**Comment by knopp** [comment] 2024-06-26 12:56
It's quite strange as it doesn't happen consistently, also ballistic scrolling is broken.

**Comment by knopp** [comment] 2024-06-26 13:53
@gspencergoog, it seems like scrollbar is stealing the pan zoom event and driving the scrolling. Removing the scrollbar by wrapping with 
```dart
 ScrollConfiguration(
          behavior: ScrollBehavior().copyWith(scrollbars: false),
```

This seems to be the PR that broke scrolling: https://github.com/flutter/flutter/pull/146654

**Comment by knopp** [comment] 2024-06-26 14:04
And https://github.com/flutter/flutter/pull/150275 fixes this. But still, having scrolling completely broken in main for three weeks is not good :-/

**Comment by knopp** [comment] 2024-06-26 14:08
Closing as duplicate of https://github.com/flutter/flutter/issues/149999.

**Closed by knopp** 2024-06-26 14:08 UTC
Labels: c: regression, engine, platform-mac, f: scrolling, team-macos

**Comment by HansMuller** [comment] 2024-06-26 19:31
@knopp - One reason that https://github.com/flutter/flutter/pull/146654 broke trackpad scrolling was that we don't seem to have enough framework testing. https://github.com/flutter/flutter/pull/150275 adds some, however the new tests are mostly just to prevent regressions.
