### ISSUE TITLE
Slider Leaves Value Indicator In Overlay

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [flutter/flutter#55787] opened 2020-04-27 22:53 UTC
## Steps to Reproduce

Whenever I show a [`Slider`](https://api.flutter.dev/flutter/material/Slider-class.html) in a [`ModalRoute`](https://api.flutter.dev/flutter/widgets/ModalRoute-class.html) and the user dismisses that modal while the slider is showing its value indicator, the value indicator is "left behind", i.e. the indicator overlay stays on the screen, indefinitely.  
This is very **ugly** and *confusing*.

**Expected results:** slider should completely disappear when the modal is closed.

**Actual results:** the value indicator stays visible indefinitely at the top of the screen.

### Note

The **label** indicator needs to be visible while the modal is being closed, i.e. to reproduce: have a slider with a `label` and change its value by tapping, then immediately close the modal..

This happens with both **v1** *and* **v2** sliders.

```
Flutter v1.18.0-9.0
// master versions since the v2 slider was introduced
```

**Comment by VladyslavBondarenko** [comment] 2020-04-28 08:26
Hi @creativecreatorormaybenot 
can you please provide your `flutter doctor -v` and a minimal complete reproducible code sample?

**Comment by creativecreatorormaybenot** [comment] 2020-04-28 10:04
@VladyslavBondarenko I included the necessary `flutter doctor` output (everything else is irrelevant).  

<details>
<summary>Sample (needs `master` to produce bug..)</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(
    MaterialApp(
      home: MyWidget(),
    ),
  );
}

class MyWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: RaisedButton(
          onPressed: () => showBug(context),
          child: Text(
            'SHOW SLIDER MODAL\nneed to run on Flutter master\nneed to slide',
            textAlign: TextAlign.center,
          ),
        ),
      ),
    );
  }
}

void showBug(BuildContext context) {
  var triggered = false, value = 1 / 2;

  showDialog(
      context: context,
      builder: (context) {
        return AlertDialog(
          content: StatefulBuilder(
            builder: (context, setState) {
              return Slider(
                  value: value,
                  divisions: 42,
                  label: 'BUG',
                  onChanged: (newValue) {
                    setState(() {
                      value = newValue;
                    });

                    if (triggered) return;
                    triggered = true;
                    Future.delayed(const Duration(milliseconds: 42)).then((_) {
                      Navigator.of(context).pop();
                    });
                  });
            },
          ),
        );
      });
}
```
</details>

This one is pretty straightforward: the v2 slider tap indicator is broken in modals..

**Comment by creativecreatorormaybenot** [comment] 2020-04-28 10:05
@VladyslavBondarenko I included the necessary `flutter doctor` output (everything else is irrelevant).  

<details>
<summary>Sample (needs `master` to produce bug..)</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(
    MaterialApp(
      home: MyWidget(),
    ),
  );
}

class MyWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: RaisedButton(
          onPressed: () => showBug(context),
          child: Text(
            'SHOW SLIDER MODAL\nneed to run on Flutter master\nneed to slide',
            textAlign: TextAlign.center,
          ),
        ),
      ),
    );
  }
}

void showBug(BuildContext context) {
  var triggered = false, value = 1 / 2;

  showDialog(
      context: context,
      builder: (context) {
        return AlertDialog(
          content: StatefulBuilder(
            builder: (context, setState) {
              return Slider(
                  value: value,
                  divisions: 42,
                  label: 'BUG',
                  onChanged: (newValue) {
                    setState(() {
                      value = newValue;
                    });

                    if (triggered) return;
                    triggered = true;
                    Future.delayed(const Duration(milliseconds: 42)).then((_) {
                      Navigator.of(context).pop();
                    });
                  });
            },
          ),
        );
      });
}
```
</details>

This one is pretty straightforward: the v2 slider value indicator is broken in modals..

**Comment by TahaTesser** [comment] 2020-04-30 07:36
Hi @creativecreatorormaybenot 
Can you please the information asked by @VladyslavBondarenko  in the [comment](https://github.com/flutter/flutter/issues/55787#issuecomment-620459023)
Thank you

**Comment by creativecreatorormaybenot** [comment] 2020-04-30 11:46
@TahaTesser I provided the necessary doctor data, I believe.

Sorry for not responding - I am having a hard time to construct a minimal reproducible example.  
I believe that the people that recently worked on overlays/sliders (between `beta` and `master`) would know exactly why this is happening 🤔

**Comment by iapicca** [comment] 2020-04-30 14:25
Hi @creativecreatorormaybenot 
does this [code sample](https://dartpad.dev/a2751f9527c790b754af2bf82cfc7f91)
represent the issue you are describing?
Thank you

**Comment by creativecreatorormaybenot** [comment] 2020-04-30 14:41
@iapicca Thanks for that.

You need to add the following and pop when the label is currently showing:

```dart
RangeSlider(
  labels: RangeLabels('0', '1'),
  divisions: 10,
  ...
)
```

I tried creating a sample as well, however, I failed for two reasons: 1. the online DartPad does not use `master`, 2. it does not seem to happen with every setup (however, in my app setup it happens *always*).

**Comment by TahaTesser** [comment] 2020-05-04 07:18
Hi @creativecreatorormaybenot 

Testing this code sample mobile and web, closing it as fast as possible when clicking value indicator reproduces no issue .

<details> 
<summary>Code Sample</summary> 

``` 
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) => MaterialApp(
        home: MyHomePage(),
      );
}

class MyHomePage extends StatelessWidget {
  void _customPop(BuildContext context) => Navigator.of(context).push(
        CustomPopRoute(
          dismissible: true,
          builder: (context) => SliderWiget(),
        ),
      );

  @override
  Widget build(BuildContext context) => Scaffold(
        body: Center(
          child: Text('nothing here'),
        ),
        floatingActionButton: FloatingActionButton(
          child: Icon(Icons.add),
          onPressed: () => _customPop(context),
        ),
      );
}

class SliderWiget extends StatefulWidget {
  @override
  _SliderWigetState createState() => _SliderWigetState();
}

class _SliderWigetState extends State<SliderWiget> {
  RangeValues _values;

  @override
  void initState() {
    super.initState();
    _values = RangeValues(0, 50);
  }

  @override
  Widget build(BuildContext context) => Material(
        child: Center(
          child: ListTile(
            leading: Text('${_values.start}'),
            trailing: Text('${_values.end}'),
            title: Container(
              height: 100,
              width: 200,
              child: RangeSlider(
                min: 0,
                divisions: 10,
                max: 100,
                labels: RangeLabels('0', '1'),
                onChanged: (values) => setState(
                  () => _values = RangeValues(
                    values.start.floor().toDouble(),
                    values.end.floor().toDouble(),
                  ),
                ),
                values: _values,
              ),
            ),
            subtitle: MaterialButton(
              child: Text('pop'),
              onPressed: () => Navigator.of(context).pop(),
            ),
          ),
        ),
      );
}

class CustomPopRoute<T> extends PopupRoute<T> {
  final bool dismissible;
  CustomPopRoute({
    this.builder,
    this.barrierLabel,
    this.dismissible = false,
    RouteSettings settings,
  }) : super(settings: settings);

  final WidgetBuilder builder;

  @override
  final String barrierLabel;

  @override
  Color get barrierColor => null;

  @override
  bool get barrierDismissible => dismissible;

  @override
  bool get semanticsDismissible => false;

  @override
  Duration get transitionDuration => Duration(milliseconds: 335);

  Animation<double> _animation;

  Tween<Offset> _offsetTween;

  @override
  Animation<double> createAnimation() {
    assert(_animation == null);
    _animation = CurvedAnimation(
      parent: super.createAnimation(),
      curve: Curves.linearToEaseOut,
      reverseCurve: Curves.linearToEaseOut.flipped,
    );
    _offsetTween = Tween<Offset>(
      begin: const Offset(0.0, 1.0),
      end: const Offset(0.0, 0.0),
    );
    return _animation;
  }

  @override
  Widget buildPage(BuildContext context, Animation<double> animation,
      Animation<double> secondaryAnimation) {
    return builder(context);
  }

  @override
  Widget buildTransitions(BuildContext context, Animation<double> animation,
      Animation<double> secondaryAnimation, Widget child) {
    return Align(
      alignment: Alignment.bottomCenter,
      child: FractionalTranslation(
        translation: _offsetTween.evaluate(_animation),
        child: child,
      ),
    );
  }
}

``` 

</details> 

<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel master, 1.18.0-9.0.pre.101, on Mac OS X 10.15.4 19E287,
    locale en-GB)
    • Flutter version 1.18.0-9.0.pre.101 at /Users/taha/Code/flutter_master
    • Framework revision 17bbc2a235 (10 hours ago), 2020-05-03 17:34:02 -0400
    • Engine revision 906bf59684
    • Dart version 2.9.0 (build 2.9.0-5.0.dev c3ce873556)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/taha/Code/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/taha/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.44.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.1

 
[✓] Connected device (5 available)            
    • SM M305F            • 32003c30dc19668f • android-arm64  • Android 10 (API
      29)
    • AOSP on IA Emulator • emulator-5554    • android-x86    • Android 9 (API
      28) (emulator)
    • macOS               • macOS            • darwin-x64     • Mac OS X 10.15.4
      19E287
    • Web Server          • web-server       • web-javascript • Flutter Tools
    • Chrome              • chrome           • web-javascript • Google Chrome
      81.0.4044.129

• No issues found!
``` 

</details> 

Can you please try to reproduce it again and post a gif if possible 
Thank you

**Comment by creativecreatorormaybenot** [comment] 2020-05-04 17:08
@TahaTesser 

Here is a GIF:

![][gif]

At the top (behind the status bar), the slider value indicators are rendered indefinitely.  
This also happened with the old v1 sliders.  
This time I used v2 sliders because I upgraded to the **latest** master version: `Flutter (Channel master, 1.18.0-9.0.pre.103)`

And here is the widget tree:

![][widget tree]

[gif]: https://i.imgur.com/0ELMSNu.gif
[widget tree]: https://i.imgur.com/c7jzCVz.png

**Comment by TahaTesser** [comment] 2020-05-05 07:00
Hi @creativecreatorormaybenot 
Can you please provide a minimal code sample from the gif?
Thank you

**Comment by creativecreatorormaybenot** [comment] 2020-05-05 07:53
@TahaTesser As I said, I attempted to do that, however, I failed. I do not know what causes this and when I simply use `showDialog` with a `Slider`, it does not happen.

That is why I mentioned that I believe someone who worked on it might have more insights. I will try to look into it more in the coming weeks and update you if I find anything.

**Comment by JoseAlba** [comment] 2020-05-18 21:23
[Dartpad example](https://dartpad.dev/bb3d69cfd0d5425611f774b840f4045a)

If you copy and paste this code and try running it on master you will get an error when you leave the slider too quickly. 

I believe the issue is because the value indicator waits until the animation is done before removing it from the overlay. To fix this the Slider needs to dispose the overlay property and make sure that there is nothing in the overlay when the Slider is removed.

**Closed** 2020-05-27 22:27 UTC
Labels: f: material design, framework
