### ISSUE TITLE
Transform.rotate changes location of Icon on IOS but works as expected on android

### ISSUE THREAD

**Issue by DevUser611** [flutter/flutter#153712] opened 2024-08-19 17:21 UTC
### Steps to reproduce

1. create flutter application 
2. paste in your main.dart file code sample below 
3. run app on ios device or simulator 

### Expected results

Icon should rotate to 180 degrees upon pressing Text button and should not change it location

### Actual results

Icon rotates to 180 degrees upon pressing Text button and changes location

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'dart:math' show pi;

void main() {
  runApp(const App());
}

class App extends StatelessWidget {
  const App({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        brightness: Brightness.dark,
        useMaterial3: true,
      ),
      darkTheme: ThemeData(brightness: Brightness.dark),
      themeMode: ThemeMode.dark,
      debugShowCheckedModeBanner: false,
      debugShowMaterialGrid: false,
      home: const HomePage(),
    );
  }
}

class HomePage extends StatelessWidget {
  const HomePage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Home Page'),
      ),
      body: const Center(
        child: CollapseButton(),
      ),
    );
  }
}

class CollapseButton extends StatefulWidget {
  const CollapseButton({
    super.key,
  });

  @override
  State<CollapseButton> createState() => _CollapseButtonState();
}

class _CollapseButtonState extends State<CollapseButton>
    with SingleTickerProviderStateMixin {
  late final AnimationController _rotationController;
  late final Animation<double> _rotation;

  @override
  void initState() {
    _rotationController = AnimationController(
      vsync: this,
      duration: const Duration(milliseconds: 350),
    );
    _rotation = Tween<double>(begin: 0, end: pi).animate(
      CurvedAnimation(parent: _rotationController, curve: Curves.easeInOut),
    );
    super.initState();
  }

  @override
  void dispose() {
    _rotationController.dispose();
    super.dispose();
  }

  void _toggleCollapse() {
    if (_rotationController.isDismissed) {
      _rotationController.forward();
    } else {
      _rotationController.reverse();
    }
  }

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        TextButton(
          onPressed: _toggleCollapse,
          child: const Text('press'),
        ),
        const SizedBox(height: 16),
        AnimatedBuilder(
          animation: _rotationController,
          builder: (context, child) {
            return Transform.rotate(
              angle: _rotation.value,
              child: child,
            );
          },
          child: const Icon(Icons.expand_more),
        ),
      ],
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

starting point
![Simulator Screenshot - iPhone 14 Pro - 2024-08-19 at 22 17 16](https://github.com/user-attachments/assets/396d48b5-0083-411b-adcd-ca3e6592c626)

after pressing button
![Simulator Screenshot - iPhone 14 Pro - 2024-08-19 at 22 17 19](https://github.com/user-attachments/assets/65a5c97c-ce1b-4efb-8160-51d50451cd7d)

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console

[✓] Flutter (Channel stable, 3.24.0, on macOS 14.6.1 23G93 darwin-arm64, locale
    ru-TM)
    • Flutter version 3.24.0 on channel stable at
      /Users/serdar/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 80c2e84975 (3 недели назад), 2024-07-30 23:06:49 +0700
    • Engine revision b8800d88be
    • Dart version 3.5.0
    • DevTools version 2.37.2

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/serdar/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.9+0-17.0.9b1087.7-11185874)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.9+0-17.0.9b1087.7-11185874)

[✓] VS Code (version 1.91.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.94.0

[✓] Connected device (6 available)
    • sdk gphone64 arm64 (mobile)     • emulator-5554                        •
      android-arm64  • Android 14 (API 34) (emulator)
    • iPhone 14 Pro (mobile)          • 23466793-AC27-4188-A90C-6216F2039F3D •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-4 (simulator)
    • macOS (desktop)                 • macos                                •
      darwin-arm64   • macOS 14.6.1 23G93 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad                •
      darwin         • macOS 14.6.1 23G93 darwin-arm64
    • Chrome (web)                    • chrome                               •
      web-javascript • Google Chrome 127.0.6533.120
    ! Error: Browsing on the local area network for iPhone. Ensure the device is
      unlocked and attached with a cable or associated with the same local area
      network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code
      -27)

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

</details>

**Comment by SuicaLondon** [comment] 2024-08-19 22:29
```
[✓] Flutter (Channel master, 3.24.0-1.0.pre.440, on macOS 15.1 24B5024e darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.1)
[✓] VS Code (version 1.92.1)
[✓] Connected device (5 available)
[✓] Network resources
```

It is working fine on my side. What does the icon look like when you inspected the widget?

https://github.com/user-attachments/assets/219d4bdd-f73f-43d5-886a-af565387c078

**Comment by DevUser611** [comment] 2024-08-20 05:54
i found out that i was testing on iphone 14 pro simulator as it worked well on android i thought it just a simulator issue didn't that matter
But then my co-worker sent me screenshot showing as same issue appered in his phone at the moment i didn't realize that he had iphone 14 pro too. 
So maybe it issue persists only on iphone 14 pro

https://github.com/user-attachments/assets/f10113c0-7cee-4912-b50a-f542b1e59308

**Comment by huycozy** [comment] 2024-08-20 06:16
Closing this as a duplicate of https://github.com/flutter/flutter/issues/153036, please follow it for updates.

**Closed by huycozy** 2024-08-20 06:16 UTC
Labels: in triage
