### ISSUE TITLE
Cant Run flutter build apk - error

### ISSUE THREAD

**Issue by ebofi** [flutter/flutter#117278] opened 2022-12-18 05:13 UTC
The whole code was working good last week, and now I try to open the same project and run flutter build apk

It shows below error

```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':location'.
> Could not load compiled classes for build file 'D:\flutter\.pub-cache\hosted\pub.dartlang.org\location-4.4.0\android\build.gradle' from cache.
> Failed to notify project evaluation listener.
   > Could not get unknown property 'android' for project ':location' of type org.gradle.api.Project.
   > Could not get unknown property 'android' for project ':location' of type org.gradle.api.Project.
* Try:
ore log output. Run with --scan to get full insights.
* Get more help at https://help.gradle.org
BUILD FAILED in 16s
Gradle task assembleRelease failed with exit code 1
```

```
Doctor summary (to see all details, run flutter doctor -v):
US)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.3.6)
[√] Android Studio (version 2021.3)
[√] Connected device (3 available)
[√] HTTP Host Availability

• No issues found!
```

**Comment by onoe-serika** [comment] 2022-12-18 13:11
try flutter clean, and flutter pub get,
and run,
(If it still fails, keep your code, and try reinstall flutter)

**Comment by huycozy** [comment] 2022-12-19 06:48
> Could not load compiled classes for build file 'D:\flutter\.pub-cache\hosted\pub.dartlang.org\location-4.4.0\android\build.gradle' from cache.
> Failed to notify project evaluation listener.
   > Could not get unknown property 'android' for project ':location' of type org.gradle.api.Project.
   > Could not get unknown property 'android' for project ':location' of type org.gradle.api.Project.

@ebofi Based on your log output, it seems to be related to 3rd plugin `location` rather than Flutter SDK/Flutter's 1st plugins/packages itself. Please open the issue in the dedicated [repository](https://github.com/Lyokone/flutterlocation/issues).
Closing, as this isn't an issue with Flutter itself.  

If you disagree, please write in the comments, providing your complete `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`, a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that does not use 3rd party plugins and I will reopen it.

Thank you!

**Closed by huycozy** 2022-12-19 06:48 UTC
Labels: in triage
