### ISSUE TITLE
ServiceWorker in index.html makes splash screen load twice in phones

### ISSUE THREAD

**Issue by bernaferrari** [flutter/flutter#88622] opened 2021-08-21 01:42 UTC
This one was hard to debug. When the `if ('serviceWorker' in navigator) {` block is there, Flutter loads the splash screen "twice". First smaller, then larger. First ignoring the mobile size (as if it were desktop), then in the correct/expected size.
This issue didn't exist when `main.dart.js` was called directly (without the serviceWorker). If you look at the [Photobooth's index.html](https://github.com/flutter/photobooth/blob/main/web/index.html), it doesn't have this issue because it doesn't use the service worker. This also affects release mode and is mostly invisible when running on a large screen.

https://user-images.githubusercontent.com/351125/130306375-4c9885b8-ac41-4db6-9abf-db32a8debf70.mov

Photobooth's splash screen. If you call `flutter create` and add these lines, you will get the video result.
```html
<title>splash_project</title>
  <link rel="manifest" href="manifest.json">
  <style>body,html{padding:0;margin:0;width:100%;height:100%;background:linear-gradient(#cfcfcf,#fff)}body{display:flex;justify-content:center;align-items:center;}</style>
  <style>.MuiCircularProgress-root{display:inline-block}.MuiCircularProgress-static{transition:transform .3s cubic-bezier(.4,0,.2,1) 0s}.MuiCircularProgress-indeterminate{animation:MuiCircularProgress-keyframes-circular-rotate 1.4s linear infinite}.MuiCircularProgress-determinate{transition:transform .3s cubic-bezier(.4,0,.2,1) 0s}.MuiCircularProgress-colorPrimary{color:#3f51b5}.MuiCircularProgress-colorSecondary{color:#f50057}.MuiCircularProgress-svg{display:block;animation:loading_animation 1.4s infinite}.MuiCircularProgress-circle{stroke:currentColor}.MuiCircularProgress-circleStatic{transition:stroke-dashoffset .3s cubic-bezier(.4,0,.2,1) 0s}.MuiCircularProgress-circleIndeterminate{animation:MuiCircularProgress-keyframes-circular-dash 1.4s ease-in-out infinite;stroke-dasharray:80px,200px;stroke-dashoffset:0}.MuiCircularProgress-circleDeterminate{transition:stroke-dashoffset .3s cubic-bezier(.4,0,.2,1) 0s}@keyframes MuiCircularProgress-keyframes-circular-rotate{0%{transform-origin:50% 50%}100%{transform:rotate(360deg)}}@keyframes MuiCircularProgress-keyframes-circular-dash{0%{stroke-dasharray:1px,200px;stroke-dashoffset:0}50%{stroke-dasharray:100px,200px;stroke-dashoffset:-15px}100%{stroke-dasharray:100px,200px;stroke-dashoffset:-125px}}.MuiCircularProgress-circleDisableShrink{animation:none}@keyframes loading_animation{0%{color:#4285f4}25%{color:#ea4335}50%{color:#f9bb2d}75%{color:#34a853}}</style>
</head>
<body>
<div id="loading-indicator" style="width: 60px; height: 60px;" role="progressbar" class="MuiCircularProgress-root MuiCircularProgress-colorPrimary MuiCircularProgress-indeterminate"><svg viewBox="22 22 44 44" class="MuiCircularProgress-svg"> <circle cx="44" cy="44" r="20.2" fill="none" stroke-width="3.6" class="MuiCircularProgress-circle MuiCircularProgress-circleIndeterminate"></circle></svg></div>
```

[index.html.zip](https://github.com/flutter/flutter/files/7024672/index.html.zip)

**Comment by TahaTesser** [comment] 2021-08-23 12:46
Hi @bernaferrari 
This has been reported in https://github.com/flutter/flutter/issues/86824,  it makes it look like it is loaded twice since the web page is loading bundle resources and updating the page. This should be addressed in https://github.com/flutter/flutter/issues/48468.

Closing as duplicate of

**Closed by TahaTesser** 2021-08-23 12:46 UTC
Labels: in triage
