### ISSUE TITLE
Uncategorized (Xcode): Exited with status code 1

### ISSUE THREAD

**Issue by uc-vrm** [flutter/flutter#146326] opened 2024-04-05 07:41 UTC
### Steps to reproduce

flutter run

### Actual results

Unable to build app for the simulator.

<img width="851" alt="image" src="https://github.com/flutter/flutter/assets/87478551/564c93a9-b729-48fe-acb6-c9883a38d001">

### Logs

<details open>
<summary>Logs</summary>

```console

Xcode build done.                                            3.7s
[  +47 ms] executing: /usr/bin/arch -arm64e xcrun xcresulttool get --path
/var/folders/ds/bbptl8p5391_lg2drzvrgt3w0000gn/T/flutter_tools.7XaLcM/flutter_ios_build_temp
_dirBgDEyc/temporary_xcresult_bundle --format json
[ +106 ms] {
                      "_type" : {
                        "_name" : "ActionsInvocationRecord"
                      },
                      "actions" : {
                        "_type" : {
                          "_name" : "Array"
                        },
                        "_values" : [
                          {
                            "_type" : {
                              "_name" : "ActionRecord"
                            },
                            "actionResult" : {
                              "_type" : {
                                "_name" : "ActionResult"
                              },
                              "coverage" : {
                                "_type" : {
                                  "_name" : "CodeCoverageInfo"
                                }
                              },
                              "issues" : {
                                "_type" : {
                                  "_name" : "ResultIssueSummaries"
                                }
                              },
                              "metrics" : {
                                "_type" : {
                                  "_name" : "ResultMetrics"
                                }
                              },
                              "resultName" : {
                                "_type" : {
                                  "_name" : "String"
                                },
                                "_value" : "action"
                              },
                              "status" : {
                                "_type" : {
                                  "_name" : "String"
                                },
                                "_value" : "failed"
                              }
                            },
                            "buildResult" : {
                              "_type" : {
                                "_name" : "ActionResult"
                              },
                              "coverage" : {
                                "_type" : {
                                  "_name" : "CodeCoverageInfo"
                                }
                              },
                              "issues" : {
                                "_type" : {
                                  "_name" : "ResultIssueSummaries"
                                },
                                "errorSummaries" : {
                                  "_type" : {
                                    "_name" : "Array"
                                  },
                                  "_values" : [
                                    {
                                      "_type" : {
                                        "_name" : "IssueSummary"
                                      },
                                      "issueType" : {
                                        "_type" : {
                                          "_name" : "String"
                                        },
                                        "_value" : "Uncategorized"
                                      },
                                      "message" : {
                                        "_type" : {
                                          "_name" : "String"
                                        },
                                        "_value" : "Exited with status code 1"
                                      }
                                    }
                                  ]
                                }
                              },
                              "logRef" : {
                                "_type" : {
                                  "_name" : "Reference"
                                },
                                "id" : {
                                  "_type" : {
                                    "_name" : "String"
                                  },
                                  "_value" :
                                  "0~rh0sbqhatrGbAFIhvZQlzFGNwJONIEnHEoio7vzddzSWWSHjqx5FYYx
                                  4JsvCfgfo9PeGB8l1rJH8xw_P95okNg=="
                                },
                                "targetType" : {
                                  "_type" : {
                                    "_name" : "TypeDefinition"
                                  },
                                  "name" : {
                                    "_type" : {
                                      "_name" : "String"
                                    },
                                    "_value" : "ActivityLogSection"
                                  }
                                }
                              },
                              "metrics" : {
                                "_type" : {
                                  "_name" : "ResultMetrics"
                                },
                                "errorCount" : {
                                  "_type" : {
                                    "_name" : "Int"
                                  },
                                  "_value" : "1"
                                }
                              },
                              "resultName" : {
                                "_type" : {
                                  "_name" : "String"
                                },
                                "_value" : "build"
                              },
                              "status" : {
                                "_type" : {
                                  "_name" : "String"
                                },
                                "_value" : "cancelled"
                              }
                            },
                            "endedTime" : {
                              "_type" : {
                                "_name" : "Date"
                              },
                              "_value" : "2024-04-05T12:21:26.628+0530"
                            },
                            "runDestination" : {
                              "_type" : {
                                "_name" : "ActionRunDestinationRecord"
                              },
                              "displayName" : {
                                "_type" : {
                                  "_name" : "String"
                                },
                                "_value" : "iPhone 15 Pro Max"
                              },
                              "localComputerRecord" : {
                                "_type" : {
                                  "_name" : "ActionDeviceRecord"
                                },
                                "busSpeedInMHz" : {
                                  "_type" : {
                                    "_name" : "Int"
                                  },
                                  "_value" : "0"
                                },
                                "cpuCount" : {
                                  "_type" : {
                                    "_name" : "Int"
                                  },
                                  "_value" : "1"
                                },
                                "cpuKind" : {
                                  "_type" : {
                                    "_name" : "String"
                                  },
                                  "_value" : "Apple M1"
                                },
                                "cpuSpeedInMHz" : {
                                  "_type" : {
                                    "_name" : "Int"
                                  },
                                  "_value" : "0"
                                },
                                "identifier" : {
                                  "_type" : {
                                    "_name" : "String"
                                  },
                                  "_value" : "00008103-000818CA2153001E"
                                },
                                "isConcreteDevice" : {
                                  "_type" : {
                                    "_name" : "Bool"
                                  },
                                  "_value" : "true"
                                },
                                "logicalCPUCoresPerPackage" : {
                                  "_type" : {
                                    "_name" : "Int"
                                  },
                                  "_value" : "8"
                                },
                                "modelCode" : {
                                  "_type" : {
                                    "_name" : "String"
                                  },
                                  "_value" : "MacBookAir10,1"
                                },
                                "modelName" : {
                                  "_type" : {
                                    "_name" : "String"
                                  },
                                  "_value" : "MacBook Air"
                                },
                                "modelUTI" : {
                                  "_type" : {
                                    "_name" : "String"
                                  },
                                  "_value" : "com.apple.macbookair-late-2020"
                                },
                                "name" : {
                                  "_type" : {
                                    "_name" : "String"
                                  },
                                  "_value" : "My Mac"
                                },
                                "nativeArchitecture" : {
                                  "_type" : {
                                    "_name" : "String"
                                  },
                                  "_value" : "arm64e"
                                },
                                "operatingSystemVersion" : {
                                  "_type" : {
                                    "_name" : "String"
                                  },
                                  "_value" : "14.4.1"
                                },
                                "operatingSystemVersionWithBuildNumber" : {
                                  "_type" : {
                                    "_name" : "String"
                                  },
                                  "_value" : "14.4.1 (23E224)"
                                },
                                "physicalCPUCoresPerPackage" : {
                                  "_type" : {
                                    "_name" : "Int"
                                  },
                                  "_value" : "8"
                                },
                                "platformRecord" : {
                                  "_type" : {
                                    "_name" : "ActionPlatformRecord"
                                  },
                                  "identifier" : {
                                    "_type" : {
                                      "_name" : "String"
                                    },
                                    "_value" : "com.apple.platform.macosx"
                                  },
                                  "userDescription" : {
                                    "_type" : {
                                      "_name" : "String"
                                    },
                                    "_value" : "macOS"
                                  }
                                },
                                "ramSizeInMegabytes" : {
                                  "_type" : {
                                    "_name" : "Int"
                                  },
                                  "_value" : "8192"
                                }
                              },
                              "targetArchitecture" : {
                                "_type" : {
                                  "_name" : "String"
                                },
                                "_value" : "arm64"
                              },
                              "targetDeviceRecord" : {
                                "_type" : {
                                  "_name" : "ActionDeviceRecord"
                                },
                                "busSpeedInMHz" : {
                                  "_type" : {
                                    "_name" : "Int"
                                  },
                                  "_value" : "0"
                                },
                                "cpuCount" : {
                                  "_type" : {
                                    "_name" : "Int"
                                  },
                                  "_value" : "0"
                                },
                                "cpuSpeedInMHz" : {
                                  "_type" : {
                                    "_name" : "Int"
                                  },
                                  "_value" : "0"
                                },
                                "identifier" : {
                                  "_type" : {
                                    "_name" : "String"
                                  },
                                  "_value" : "E1259022-0857-48C3-BB89-2F93297F8D27"
                                },
                                "isConcreteDevice" : {
                                  "_type" : {
                                    "_name" : "Bool"
                                  },
                                  "_value" : "true"
                                },
                                "logicalCPUCoresPerPackage" : {
                                  "_type" : {
                                    "_name" : "Int"
                                  },
                                  "_value" : "0"
                                },
                                "modelCode" : {
                                  "_type" : {
                                    "_name" : "String"
                                  },
                                  "_value" : "iPhone16,2"
                                },
                                "modelName" : {
                                  "_type" : {
                                    "_name" : "String"
                                  },
                                  "_value" : "iPhone 15 Pro Max"
                                },
                                "modelUTI" : {
                                  "_type" : {
                                    "_name" : "String"
                                  },
                                  "_value" : "com.apple.iphone-15-pro-max-1"
                                },
                                "name" : {
                                  "_type" : {
                                    "_name" : "String"
                                  },
                                  "_value" : "iPhone 15 Pro Max"
                                },
                                "nativeArchitecture" : {
                                  "_type" : {
                                    "_name" : "String"
                                  },
                                  "_value" : "arm64"
                                },
                                "operatingSystemVersion" : {
                                  "_type" : {
                                    "_name" : "String"
                                  },
                                  "_value" : "17.4"
                                },
                                "operatingSystemVersionWithBuildNumber" : {
                                  "_type" : {
                                    "_name" : "String"
                                  },
                                  "_value" : "17.4 (21E213)"
                                },
                                "physicalCPUCoresPerPackage" : {
                                  "_type" : {
                                    "_name" : "Int"
                                  },
                                  "_value" : "0"
                                },
                                "platformRecord" : {
                                  "_type" : {
                                    "_name" : "ActionPlatformRecord"
                                  },
                                  "identifier" : {
                                    "_type" : {
                                      "_name" : "String"
                                    },
                                    "_value" : "com.apple.platform.iphonesimulator"
                                  },
                                  "userDescription" : {
                                    "_type" : {
                                      "_name" : "String"
                                    },
                                    "_value" : "iOS Simulator"
                                  }
                                },
                                "ramSizeInMegabytes" : {
                                  "_type" : {
                                    "_name" : "Int"
                                  },
                                  "_value" : "0"
                                }
                              },
                              "targetSDKRecord" : {
                                "_type" : {
                                  "_name" : "ActionSDKRecord"
                                },
                                "identifier" : {
                                  "_type" : {
                                    "_name" : "String"
                                  },
                                  "_value" : "iphonesimulator17.4"
                                },
                                "name" : {
                                  "_type" : {
                                    "_name" : "String"
                                  },
                                  "_value" : "Simulator - iOS 17.4"
                                },
                                "operatingSystemVersion" : {
                                  "_type" : {
                                    "_name" : "String"
                                  },
                                  "_value" : "17.4"
                                }
                              }
                            },
                            "schemeCommandName" : {
                              "_type" : {
                                "_name" : "String"
                              },
                              "_value" : "Run"
                            },
                            "schemeTaskName" : {
                              "_type" : {
                                "_name" : "String"
                              },
                              "_value" : "Build"
                            },
                            "startedTime" : {
                              "_type" : {
                                "_name" : "Date"
                              },
                              "_value" : "2024-04-05T12:21:25.763+0530"
                            },
                            "title" : {
                              "_type" : {
                                "_name" : "String"
                              },
                              "_value" : "Build \"Runner\""
                            }
                          }
                        ]
                      },
                      "issues" : {
                        "_type" : {
                          "_name" : "ResultIssueSummaries"
                        },
                        "errorSummaries" : {
                          "_type" : {
                            "_name" : "Array"
                          },
                          "_values" : [
                            {
                              "_type" : {
                                "_name" : "IssueSummary"
                              },
                              "issueType" : {
                                "_type" : {
                                  "_name" : "String"
                                },
                                "_value" : "Uncategorized"
                              },
                              "message" : {
                                "_type" : {
                                  "_name" : "String"
                                },
                                "_value" : "Exited with status code 1"
                              }
                            }
                          ]
                        }
                      },
                      "metadataRef" : {
                        "_type" : {
                          "_name" : "Reference"
                        },
                        "id" : {
                          "_type" : {
                            "_name" : "String"
                          },
                          "_value" :
                          "0~VHDjTWGCfx3YGgSpjlqsAJUv6M7_ZmKEKO5kWTqGXA77ZMshJc8hYevqbOif0St
                          YXOFtj-JeJqFlLhMLN8Rfxg=="
                        },
                        "targetType" : {
                          "_type" : {
                            "_name" : "TypeDefinition"
                          },
                          "name" : {
                            "_type" : {
                              "_name" : "String"
                            },
                            "_value" : "ActionsInvocationMetadata"
                          }
                        }
                      },
                      "metrics" : {
                        "_type" : {
                          "_name" : "ResultMetrics"
                        },
                        "errorCount" : {
                          "_type" : {
                            "_name" : "Int"
                          },
                          "_value" : "1"
                        }
                      }
                    }
[   +7 ms] Failed to build iOS app
[   +3 ms] Uncategorized (Xcode): Exited with status code 1
           
[   +6 ms] Could not build the application for the simulator.
[        ] Error launching application on iPhone 15 Pro Max.
[   +7 ms] "flutter run" took 33,463ms.
[  +72 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:815:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command.dart:1389:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure>
           (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command_runner.dart:355:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure>
           (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand
           (package:flutter_tools/src/runner/flutter_command_runner.dart:295:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure>
           (package:flutter_tools/runner.dart:119:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure>
           (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:90:3)
           <asynchronous suspension>
<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

<details open>
<summary>Doctor output</summary>

```console

[✓] Flutter (Channel stable, 3.19.5, on macOS 14.4.1 23E224 darwin-arm64, locale en-IN)
    • Flutter version 3.19.5 on channel stable at /Users/vishalmaurya/uCertify/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 300451adae (8 days ago), 2024-03-27 21:54:07 -0500
    • Engine revision e76c956498
    • Dart version 3.3.3
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/vishalmaurya/Library/Android/sdk
    • Platform android-34-ext8, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.87.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.84.0

[✓] Connected device (3 available)            
    • iPhone 15 Pro Max (mobile) • E1259022-0857-48C3-BB89-2F93297F8D27 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-17-4 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   •
      macOS 14.4.1 23E224 darwin-arm64
    • Chrome (web)               • chrome                               • web-javascript •
      Google Chrome 123.0.6312.107

[✓] Network resources
    • All expected network resources are available.

• No issues found!


```

</details>

**Comment by huycozy** [comment] 2024-04-05 10:05
@uc-vrm Could you share the entire output of `flutter run -v`? It may be huge so you can upload it as a txt file or use online tools like https://pastebin.com/ to share it. Please also provide the output of `flutter doctor -v` as well. Thanks!

**Comment by uc-vrm** [comment] 2024-04-05 10:11
This is the log of flutter run -v
[log.txt](https://github.com/flutter/flutter/files/14883479/log.txt)

**Comment by huycozy** [comment] 2024-04-05 11:44
Looking at the logs, I can't seem to see the root error of this. Does this issue only occur on your project or does it also occur on a newly created project?

Please also try running project from XCode and observe the output console to see if you can catch other error messages.

**Comment by uc-vrm** [comment] 2024-04-05 11:48
I tried it with xcode but it is giving error instantly. also it is coming with xcode version 14.3 and later it is working fine with xcode 14.2

**Comment by uc-vrm** [comment] 2024-04-05 11:50
Please see the image for xcode output.
<img width="1405" alt="image" src="https://github.com/flutter/flutter/assets/87478551/c6ee2968-2763-46af-b3bf-ecfe9a5432dd">
<img width="1397" alt="image" src="https://github.com/flutter/flutter/assets/87478551/2077f565-7708-4d94-9b3d-bb24857de810">

**Comment by uc-vrm** [comment] 2024-04-05 11:53
this is podfile of the project-

# Uncomment this line to define a global platform for your project
# platform :ios, '12.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings["DEVELOPMENT_TEAM"] = "7Z85P4NG9K"
    end
  end

  installer.generated_projects.each do |project|
    project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      end
    end
  end
end


and this is pubspec.yml of the project -

version: 1.3.35+845
buildNumber: 259 #used in codemagic

environment:
  sdk: ">=2.13.0 <4.6.1"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^0.13.6
  firebase_core: ^2.2.0
  firebase_analytics: ^10.4.5
  firebase_auth: ^4.8.0
  firebase_database: ^10.2.5
  firebase_crashlytics: ^3.3.5
  sqflite: ^2.0.0+2
  connectivity_plus: ^2.2.1
  intl: ^0.18.1
  flutter_hooks: ^0.20.0
  path_provider: ^2.0.1
  url_launcher: ^6.0.2
  webview_flutter: ^2.0.4
  provider: ^6.0.5
  flutter_archive: ^5.0.0
  simple_animations: ^5.0.2
  supercharged: ^2.0.0
  xml: ^6.1.0
  flutter_highlight: ^0.7.0
  html_unescape: ^2.0.0-nullsafety.0
  flutter_offline: ^2.0.0
  dio: ^4.0.0
  meta: ^1.3.0
  sensors: ^2.0.0
  flutter_staggered_grid_view: ^0.4.0
  cached_network_image: ^3.0.0-nullsafety
  encrypt: ^5.0.1
  permission_handler: ^10.4.3
  flutter_animator: ^3.2.2
  expandable: ^5.0.1
  flutter_date_pickers: ^0.4.2
  flutter_sheet_localization: ^5.1.1
  gsheets: ^0.5.0
  flutter_reorderable_list: ^1.2.0
  badges: ^3.0.1
  auto_size_text: ^3.0.0-nullsafety.0
  flutter_screenutil: ^5.0.0-nullsafety.8
  status_alert: ^1.0.0-nullsafety.1
  html: ^0.15.0
  csslib: ^0.17.0
  css_colors: ^1.1.0
  video_player: ^2.0.1
  chewie_audio: ^1.0.0+1
  # flutter_svg: ^0.21.0-nullsafety.0
  cupertino_icons: ^1.0.2
  collection: ^1.15.0
  flutter_qjs: ^0.3.7
  scrollable_positioned_list: ^0.3.2
  orientation: ^1.3.0
  sign_in_with_apple: ^5.0.0
  google_sign_in: ^6.1.4
  in_app_purchase: ^3.0.7
  in_app_purchase_android: ^0.3.0+11
  in_app_purchase_storekit: ^0.3.2+2
  flutter_pdfview: ^1.2.1
  google_fonts: ^5.1.0
  firebase_dynamic_links: ^5.3.5
  firebase_messaging: ^14.6.7
  font_awesome_flutter: ^10.5.0
  rate_my_app: ^2.0.0
  shared_preferences: ^2.0.4
  firebase_performance: ^0.9.2+5
  dio_firebase_performance: ^0.3.1-dev.3
  ntp: ^2.0.0
  flutter_downloader: ^1.6.1
  flutter_inappwebview: ^6.0.0-beta.23
  extended_image: ^8.1.0
  preload_page_view: ^0.2.0
  better_player: ^0.0.83
  socket_io_client: ^2.0.0
  flutter_keyboard_visibility: ^5.0.0
  flutter_tts: ^3.2.2
  flutter_html: ^2.0.0-nullsafety.0
  flutter_material_color_picker: ^1.1.0+2
  material_dialogs: ^1.1.1
  flutter_circular_text: "^0.3.1"
  device_info_plus: ^3.1.1
  package_info_plus: ^1.0.1
  visibility_detector: ^0.3.3 # using for tocItem overflow icons
  image_picker: ^1.0.2 # using for profile pic image picker
  image_cropper: ^5.0.0 # using for profile pic image cropper
  substring_highlight: ^1.0.33
  file_picker: ^4.0.2
  wakelock: ^0.5.6
  share_plus: ^4.0.10+1
  mime: ^1.0.1
  flutter_rating_bar: ^4.0.0
  flutter_local_notifications: ^12.0.4
  flutter_native_timezone: ^2.0.0
  dartdoc: ^6.3.0
  flutter_spinkit: ^5.1.0
  table_calendar: ^3.0.3
  delayed_display: ^2.0.0
  fwfh_text_style: ^2.22.8+1
  qr_code_scanner: ^1.0.1
  new_version: ^0.3.1
  flutter_device_type: ^0.4.0
  translator: ^0.1.7
  package_info_plus_web: ^2.0.0
dependency_overrides:
  flutter_downloader: 1.6.1
  http: ^1.0.0
  intl: any
  package_info_plus: any
  ffi: any
  wakelock: ^0.5.1 # to override flutter_html dependency into latest version and better_player support
  webview_flutter:
    git:
      url: https://github.com/uc-dve/plugins.git
      path: packages/webview_flutter
      ref: 11129_flutter
      version: ^2.0.4
  flutter_html:
    git:
      url: https://github.com/uc-vrm/flutter_html2
      ref: 11424_textStyle_support
      version: ^2.0.0-nullsafety.0
  better_player:
    git:
      url: https://github.com/uc-vrm/betterplayer
  flutter_inappwebview:
    git:
      url: https://github.com/uc-vrm/flutter_inappwebview
      ref: master
      version: ^6.0.0-beta.24
  dio_firebase_performance:
    git:
      url: https://github.com/uc-vrm/dio_firebase_performance
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.11

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/ebook/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: icomoon
      fonts:
        - asset: assets/fonts/icomoon.ttf
        # - asset: assets/fonts/Schyler-Italic.ttf
        #   style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

**Comment by huycozy** [comment] 2024-04-08 03:57
Thanks for the update but this remains vague with the error above (from XCode). Could you check if the issue can be reproduced on a newly created Flutter project? If it is not, you should narrow down the issue by removing the usage of 3rd party plugins/packages one by one, unrelated/unaffected pages, and isolating the affected page into a minimal sample code that can produce the issue. And please share it here when you have such an example. Thanks!

**Comment by uc-vrm** [comment] 2024-04-29 07:10
the problem is because of firebase crashalytics command script into run script.
${PODS_ROOT}/FirebaseCrashlytics/run

its giving error missing dysm directory not found . something like that issue

**Comment by huycozy** [comment] 2024-04-29 12:04
Since it's a firebase plugin's issue, I would suggest you open an issue on its repository for better support there: https://github.com/firebase/flutterfire/issues.

Closing this as it doesn't seem to be a Flutter issue. If you still believe this is a Flutter framework bug, please provide more information related to the error you observed.

**Closed by huycozy** 2024-04-29 12:04 UTC
Labels: in triage
