### ISSUE TITLE
Performance on simulator vs actual phone.

### ISSUE THREAD

**Issue by manujbahl** [flutter/flutter#19553] opened 2018-07-19 05:02 UTC
My app works good on the simulator, but on the phone it is performing 5 times slower.
Is that a known issue?

**Comment by g123k** [comment] 2018-07-19 06:03
Hello,

On your phone, is-it a debug or release build?
What kind of phone is-it?

Could you also post your `flutter doctor`?

**Comment by manujbahl** [comment] 2018-07-19 06:16
debug on iphone 7 plus.
release is considerably better

**Comment by manujbahl** [comment] 2018-07-19 06:19
flutter doctor -v
[✓] Flutter (Channel master, v0.5.5-pre.14, on Mac OS X 10.13.5 17F77, locale en-US)
    • Flutter version 0.5.5-pre.14 at /Users/MBahl/flutter/flutter
    • Framework revision b401e76554 (5 weeks ago), 2018-06-13 09:20:19 -0700
    • Engine revision c3976b3c71
    • Dart version 2.0.0-dev.61.0.flutter-c95617b19c

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.1)
    • Android SDK at /Users/MBahl/Library/Android/sdk
    • Android NDK at /Users/MBahl/Library/Android/sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 26.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[!] VS Code (version 1.25.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected devices (1 available)
    • Manuj's iPhone • 4b185da29e7eb1d7e37d22ce0a205e7c081ca5b8 • ios • iOS 11.3.1


not sure why it thinks VS Code is now installed.
![image](https://user-images.githubusercontent.com/5688107/42924894-074d88b8-8ae1-11e8-92ce-c59b44dfa4b0.png)

**Comment by liyuqian** [comment] 2018-08-02 21:35
I believe that this is working as intended:

On simulators, Flutter uses Skia's software (CPU) backend, and your desktop's CPU is usually quite powerful. On actual devices, Flutter uses Skia's GPU backend because mobile CPU is much less powerful. The debug mode will introduce a lot of overhead on the GPU backend so it's never intended to be fast (especially comparing to your Desktop's CPU). That shouldn't be a problem for your apps because you should only publish your app in release mode and that's the performance that your users experience.

Therefore, if you find the release mode to be fast on your actual devices, everything should be fine.

CC @Hixie to see if we can close the issue here.

**Comment by liyuqian** [comment] 2018-08-24 22:09
Close this issue as it's working as intended.

**Closed by liyuqian** 2018-08-24 22:09 UTC
Labels: severe: performance, ⌺‬ platform-ios
