### ISSUE TITLE
A KeyUpEvent is dispatched, but the state shows that the physical key is not pressed. If this occurs in real application, please report this bug to Flutter

### ISSUE THREAD

**Issue by xaldarof** [flutter/flutter#111070] opened 2022-09-07 06:53 UTC
A KeyUpEvent is dispatched, but the state shows that the physical key is not pressed. If this occurs in real application, please report this bug to Flutter. If this occurs in unit tests, please ensure that simulated events follow Flutter's event model as documented in `HardwareKeyboard`. This was the event: KeyUpEvent#276a5(physicalKey: PhysicalKeyboardKey#7002a(usbHidUsage: "0x0007002a", debugName: "Backspace"), logicalKey: LogicalKeyboardKey#00008(keyId: "0x100000008", keyLabel: "Backspace", debugName: "Backspace"), character: null, timeStamp: 2:49:12.586677)
'package:flutter/src/services/hardware_keyboard.dart':
Failed assertion: line 441 pos 16: '_pressedKeys.containsKey(event.physicalKey)'

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      HardwareKeyboard._assertEventIsRegular.<anonymous closure> (package:flutter/src/services/hardware_keyboard.dart:441:16)
#3      HardwareKeyboard._assertEventIsRegular (package:flutter/src/services/hardware_keyboard.dart:452:6)
#4      HardwareKeyboard.handleKeyEvent (package:flutter/src/services/hardware_keyboard.dart:544:5)
#5      KeyEventManager.handleRawKeyMessage (package:flutter/src/services/hardware_keyboard.dart:867:35)
#6      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:77:49)
#7      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:76:47)
#8      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:380:35)
#9      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:377:46)
#10     _invoke2.<anonymous closure> (dart:ui/hooks.dart:190:15)
#14     _invoke2 (dart:ui/hooks.dart:189:10)
#15     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:42:5)
#16     _Channel.push (dart:ui/channel_buffers.dart:132:31)
#17     ChannelBuffers.push (dart:ui/channel_buffers.dart:329:17)
#18     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:589:22)
#19     _dispatchPlatformMessage (dart:ui/hooks.dart:89:31)
(elided 5 frames from class _AssertionError and dart:async)

**Comment by exaby73** [comment] 2022-09-07 09:00
Hello @xaldarof. Thank you for filing this issue. Can you please provide the following information?

- A [complete and minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).
- The output of `flutter doctor -v`
- The output of `flutter run-v`

**Comment by ggirotto** [comment] 2022-09-12 13:55
Seems like a duplicate of https://github.com/flutter/flutter/issues/110950

**Comment by exaby73** [comment] 2022-09-12 21:03
@ggirotto Possibly a duplicate but in this issue, the `Backspace` key is causing it while in https://github.com/flutter/flutter/issues/110950, it's the `Control` key. There are other issues related to this. While they look the same, they are all slightly different which is why I am holding off marking this as a duplicate.

- https://github.com/flutter/flutter/issues/87391
- https://github.com/flutter/flutter/issues/94502
- https://github.com/flutter/flutter/issues/106475

**Comment by 0xpr03** [comment] 2022-09-22 15:47
I also get this issue when using a `Autocomplete` with manual `fieldViewBuilder` with a `TextFormField` on Windows in Debugbuild (haven't verified on release).

The Issue is that I only input Upper/Lowerletter input and then Hold "shift" pressed while navigating the dialog. And then, only then, the Autocomplete stops accepting any modifiers. Backspace stops working, I can't remove any Input anymore then.

<details>
  <summary>Full code extract</summary>
  
```dart
Autocomplete(
  fieldViewBuilder: (BuildContext context,
	  TextEditingController textEditingController,
	  FocusNode focusNode,
	  VoidCallback onFieldSubmitted) {
	return TextFormField(
	  controller: textEditingController,
	  autofocus: true,
	  decoration: const InputDecoration(
		helperText: 'Name',
	  ),
	  onChanged: (value) {
		_newAttributeName = value;
	  },
	  focusNode: focusNode,
	  onFieldSubmitted: (String value) {
		onFieldSubmitted();
		print('You just typed a new entry  $value');
	  },
	);
  },
  optionsBuilder: (TextEditingValue textEditingValue) {
	if (attribute != null || textEditingValue.text == '') {
	  return const Iterable<String>.empty();
	}
	return cache.attributesByName.keys
		.where((String option) {
	  return option
		  .contains(textEditingValue.text.toLowerCase());
	});
  },
  onSelected: (String selection) {
	_newAttributeName = selection;
	_newAttributeSelected =
		cache.attributesByName[selection];
	if (_newAttributeSelected != null) {
	  _newAttributeUnit = _newAttributeSelected!.unit ?? '';
	}
  },
),
```
</details>

**Comment by exaby73** [comment] 2022-09-22 16:41
@0xpr03 Could what you're experiencing be one of the issues I mentioned in https://github.com/flutter/flutter/issues/111070#issuecomment-1244469681

**Comment by 0xpr03** [comment] 2022-09-23 00:04
@exaby73 it's apparently https://github.com/flutter/flutter/issues/106475

If I just hold shift pressed during the input dialog, I experience the same issue, without `Autocomplete `and just the `TextFormField`.

**Comment by exaby73** [comment] 2022-09-23 09:54
Thank you @0xpr03. Since it's been quite a long time since OP has responded, I am closing this issue due to inactivity. If you still reproduce this issue, and it's not one of the above mentioned issues, please comment with steps to reproduce, error logs and the output of `flutter doctor -v`. Thank you.

**Closed by exaby73** 2022-09-23 09:54 UTC
Labels: waiting for customer response, in triage
