### ISSUE TITLE
'package:flutter/src/widgets/scroll_position.dart': Failed assertion: line 514 pos 12: 'haveDimensions == (_lastMetrics != null)': is not true.

### ISSUE THREAD

**Issue by haifeng94** [flutter/flutter#78604] opened 2021-03-19 10:25 UTC
when i pull down two long and springback, this error happen.

```
════════ Exception caught by rendering library ═════════════════════════════════════════════════════
The following assertion was thrown during performLayout():
Build scheduled during frame.

While the widget tree was being built, laid out, and painted, a new frame was scheduled to rebuild the widget tree.

This might be because setState() was called from a layout or paint callback. If a change is needed to the widget tree, it should be applied as the tree is being built. Scheduling a change for the subsequent frame instead results in an interface that lags behind by one frame. If this was done to make your build dependent on a size measured at layout time, consider using a LayoutBuilder, CustomSingleChildLayout, or CustomMultiChildLayout. If, on the other hand, the one frame delay is the desired effect, for example because this is an animation, consider scheduling the frame in a post-frame callback using SchedulerBinding.addPostFrameCallback or using an AnimationController to trigger the animation.

The relevant error-causing widget was: 
  GlowingOverscrollIndicator file:///Users/haifeng/AndroidStudioProjects/xiyou/lib/blocks/pulltore_fresh.dart:672:18
When the exception was thrown, this was the stack: 
#0      WidgetsBinding._handleBuildScheduled.<anonymous closure> (package:flutter/src/widgets/binding.dart:743:9)
#1      BuildOwner.scheduleBuildFor (package:flutter/src/widgets/framework.dart:2551:24)
#2      Element.markNeedsBuild (package:flutter/src/widgets/framework.dart:4157:12)
#3      State.setState (package:flutter/src/widgets/framework.dart:1287:15)
#4      _RecommendGoodsList.build.<anonymous closure> (package:xiyou/home/category/blocks/recommend_goods_list.dart:307:11)
...
The following RenderObject was being processed when the exception was fired: RenderViewport#25232 NEEDS-LAYOUT
...  needs compositing
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(0.0<=w<=414.0, h=511.3)
...  layer: OffsetLayer#3c617
...    engine layer: OffsetEngineLayer#ba796
...    offset: Offset(0.0, 0.0)
...  size: Size(414.0, 511.3)
...  axisDirection: down
...  crossAxisDirection: right
...  offset: ScrollPositionWithSingleContext#87943(offset: 0.0, range: 0.0..1120.7, viewport: 511.3, ScrollableState, NeverScrollableScrollPhysics -> BouncingScrollPhysics -> RangeMaintainingScrollPhysics, DragScrollActivity#86fbe(ScrollDragController#ef7da), ScrollDirection.forward)
...  anchor: 0.0
RenderObject: RenderViewport#25232 NEEDS-LAYOUT
  needs compositing
  parentData: <none> (can use size)
  constraints: BoxConstraints(0.0<=w<=414.0, h=511.3)
  layer: OffsetLayer#3c617
    engine layer: OffsetEngineLayer#ba796
    offset: Offset(0.0, 0.0)
  size: Size(414.0, 511.3)
  axisDirection: down
  crossAxisDirection: right
  offset: ScrollPositionWithSingleContext#87943(offset: 0.0, range: 0.0..1120.7, viewport: 511.3, ScrollableState, NeverScrollableScrollPhysics -> BouncingScrollPhysics -> RangeMaintainingScrollPhysics, DragScrollActivity#86fbe(ScrollDragController#ef7da), ScrollDirection.forward)
  anchor: 0.0
...  center child: RenderSliverPadding#eb9f3 relayoutBoundary=up1
...    needs compositing
...    parentData: paintOffset=Offset(0.0, 0.0) (can use size)
...    constraints: SliverConstraints(AxisDirection.down, GrowthDirection.forward, ScrollDirection.forward, scrollOffset: 0.0, remainingPaintExtent: 511.3, crossAxisExtent: 414.0, crossAxisDirection: AxisDirection.right, viewportMainAxisExtent: 511.3, remainingCacheExtent: 761.3, cacheOrigin: 0.0)
...    geometry: SliverGeometry(scrollExtent: 1632.0, paintExtent: 511.3, maxPaintExtent: 1632.0, hasVisualOverflow: true, cacheExtent: 761.3)
...      scrollExtent: 1632.0
...      paintExtent: 511.3
...      maxPaintExtent: 1632.0
...      hasVisualOverflow: true
...      cacheExtent: 761.3
...    padding: EdgeInsets.zero
...    textDirection: ltr
...    child: RenderSliverList#8f99c relayoutBoundary=up2
...      needs compositing
...      parentData: paintOffset=Offset(0.0, 0.0) (can use size)
...      constraints: SliverConstraints(AxisDirection.down, GrowthDirection.forward, ScrollDirection.forward, scrollOffset: 0.0, remainingPaintExtent: 511.3, crossAxisExtent: 414.0, crossAxisDirection: AxisDirection.right, viewportMainAxisExtent: 511.3, remainingCacheExtent: 761.3, cacheOrigin: 0.0)
...      geometry: SliverGeometry(scrollExtent: 1632.0, paintExtent: 511.3, maxPaintExtent: 1632.0, hasVisualOverflow: true, cacheExtent: 761.3)
...        scrollExtent: 1632.0
...        paintExtent: 511.3
...        maxPaintExtent: 1632.0
...        hasVisualOverflow: true
...        cacheExtent: 761.3
...      currently live children: 0 to 5
...      child with index 0: RenderIndexedSemantics#cfd14 relayoutBoundary=up3
...        needs compositing
...        parentData: index=0; layoutOffset=0.0 (can use size)
...        constraints: BoxConstraints(w=414.0, 0.0<=h<=Infinity)
...        semantics node: SemanticsNode#37
...          Rect.fromLTRB(0.0, 0.0, 414.0, 85.0)
...          tags: RenderViewport.twoPane

 GlowingOverscrollIndicator file:///Users/haifeng/AndroidStudioProjects/xiyou/lib/blocks/pulltore_fresh.dart:672:18 code as follow:

class MyBehavior extends ScrollBehavior {
  final bool isShowLeadingGlow;
  final bool isShowTrailingGlow;
  final Color _kDefaultGlowColor;

  MyBehavior(
      this.isShowLeadingGlow, this.isShowTrailingGlow, this._kDefaultGlowColor);

  @override
  Widget buildViewportChrome(
      BuildContext context, Widget child, AxisDirection axisDirection) {
     if (!isShowLeadingGlow || !isShowTrailingGlow) {                                                                        line 672
      return new GlowingOverscrollIndicator(
        showLeading: isShowLeadingGlow,
        showTrailing: isShowTrailingGlow,
        child: child,
        axisDirection: axisDirection,
        color: _kDefaultGlowColor
      );
    } else {
      return super.buildViewportChrome(context, child, axisDirection);
    }
  }
}

The following assertion was thrown during performLayout():
'package:flutter/src/widgets/scroll_position.dart': Failed assertion: line 514 pos 12: 'haveDimensions == (_lastMetrics != null)': is not true.
```

============================
this error just happen in Console, The display of mobile phone is normal
who can save me ?

**Comment by haifeng94** [comment] 2021-03-19 10:26
flutter doctor -v 
[✓] Flutter (Channel stable, 2.0.2, on Mac OS X 10.15.4 19E287 darwin-x64,
    locale zh-Hans-CN)
    • Flutter version 2.0.2 at /Users/haifeng/development/flutter/flutter
    • Framework revision 8962f6dc68 (7 days ago), 2021-03-11 13:22:20 -0800
    • Engine revision 5d8bf811b3
    • Dart version 2.12.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/haifeng/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
• No issues found!

**Comment by darshankawar** [comment] 2021-03-19 12:16
@haifeng94 
Can you provide a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that shows this issue ?
Thanks.

**Comment by haifeng94** [comment] 2021-03-19 14:32
hi
i upload my dart file example to my github, just see&nbsp;https://github.com/haifeng94/flutter_example







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "flutter/flutter"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月19日(星期五) 晚上8:17
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [flutter/flutter] 'package:flutter/src/widgets/scroll_position.dart': Failed assertion: line 514 pos 12: 'haveDimensions == (_lastMetrics != null)': is not true. (#78604)





 
@haifeng94
 Can you provide a complete minimal reproducible code sample that shows this issue ?
 Thanks.

**Comment by haifeng94** [comment] 2021-03-19 16:29
after this error happen, can not pull down again, this is to say, pull down scroll disappear

**Comment by darshankawar** [comment] 2021-03-22 06:31
@haifeng94 
Thanks for the code sample. I see that you are using `cached_network_image` plugin which is 3rd party. Can you try to remove the plugin and it's relevant code and see if issue still persists or not ? If yes, please provide updated code repro.

**Comment by haifeng94** [comment] 2021-03-22 06:53
when i remove the plugin and it's relevant code, issue still persists. i think this issue happen, it's because of pulltore_fresh.dart plugin. when i pull down too long or&nbsp;springback too quickly, then errors hanppen.




════════ Exception caught by rendering library ═════════════════════════════════════════════════════
The following assertion was thrown during performLayout():
Build scheduled during frame.


While the widget tree was being built, laid out, and painted, a new frame was scheduled to rebuild the widget tree.


This might be because setState() was called from a layout or paint callback. If a change is needed to the widget tree, it should be applied as the tree is being built. Scheduling a change for the subsequent frame instead results in an interface that lags behind by one frame. If this was done to make your build dependent on a size measured at layout time, consider using a LayoutBuilder, CustomSingleChildLayout, or CustomMultiChildLayout. If, on the other hand, the one frame delay is the desired effect, for example because this is an animation, consider scheduling the frame in a post-frame callback using SchedulerBinding.addPostFrameCallback or using an AnimationController to trigger the animation.


The relevant error-causing widget was:&nbsp;
&nbsp; GlowingOverscrollIndicator file:///Users/haifeng/AndroidStudioProjects/xiyou/lib/blocks/pulltore_fresh.dart:676:18
When the exception was thrown, this was the stack:&nbsp;
#0&nbsp; &nbsp; &nbsp; WidgetsBinding._handleBuildScheduled.<anonymous closure&gt; (package:flutter/src/widgets/binding.dart:743:9)
#1&nbsp; &nbsp; &nbsp; WidgetsBinding._handleBuildScheduled (package:flutter/src/widgets/binding.dart:766:6)
#2&nbsp; &nbsp; &nbsp; BuildOwner.scheduleBuildFor (package:flutter/src/widgets/framework.dart:2551:24)
#3&nbsp; &nbsp; &nbsp; Element.markNeedsBuild (package:flutter/src/widgets/framework.dart:4157:12)
#4&nbsp; &nbsp; &nbsp; State.setState (package:flutter/src/widgets/framework.dart:1287:15)
...
The following RenderObject was being processed when the exception was fired: RenderViewport#62cc9 NEEDS-LAYOUT
...&nbsp; needs compositing
...&nbsp; parentData: <none&gt; (can use size)
...&nbsp; constraints: BoxConstraints(0.0<=w<=414.0, h=511.9)
...&nbsp; layer: OffsetLayer#cd48f
...&nbsp; &nbsp; engine layer: OffsetEngineLayer#d91b3
...&nbsp; &nbsp; offset: Offset(0.0, 0.0)
...&nbsp; size: Size(414.0, 511.9)
...&nbsp; axisDirection: down
...&nbsp; crossAxisDirection: right
...&nbsp; offset: ScrollPositionWithSingleContext#de1b3(offset: 0.0, range: 0.0..1120.1, viewport: 511.9, ScrollableState, NeverScrollableScrollPhysics -&gt; BouncingScrollPhysics -&gt; RangeMaintainingScrollPhysics, DragScrollActivity#c87ed(ScrollDragController#a9a7d), ScrollDirection.forward)
...&nbsp; anchor: 0.0
RenderObject: RenderViewport#62cc9 NEEDS-LAYOUT
&nbsp; needs compositing
&nbsp; parentData: <none&gt; (can use size)
&nbsp; constraints: BoxConstraints(0.0<=w<=414.0, h=511.9)
&nbsp; layer: OffsetLayer#cd48f
&nbsp; &nbsp; engine layer: OffsetEngineLayer#d91b3
&nbsp; &nbsp; offset: Offset(0.0, 0.0)
&nbsp; size: Size(414.0, 511.9)
&nbsp; axisDirection: down
&nbsp; crossAxisDirection: right
&nbsp; offset: ScrollPositionWithSingleContext#de1b3(offset: 0.0, range: 0.0..1120.1, viewport: 511.9, ScrollableState, NeverScrollableScrollPhysics -&gt; BouncingScrollPhysics -&gt; RangeMaintainingScrollPhysics, DragScrollActivity#c87ed(ScrollDragController#a9a7d), ScrollDirection.forward)
&nbsp; anchor: 0.0
...&nbsp; center child: RenderSliverPadding#bbb41 relayoutBoundary=up1
...&nbsp; &nbsp; needs compositing
...&nbsp; &nbsp; parentData: paintOffset=Offset(0.0, 0.0) (can use size)
...&nbsp; &nbsp; constraints: SliverConstraints(AxisDirection.down, GrowthDirection.forward, ScrollDirection.forward, scrollOffset: 0.0, remainingPaintExtent: 511.9, crossAxisExtent: 414.0, crossAxisDirection: AxisDirection.right, viewportMainAxisExtent: 511.9, remainingCacheExtent: 761.9, cacheOrigin: 0.0)
...&nbsp; &nbsp; geometry: SliverGeometry(scrollExtent: 1632.0, paintExtent: 511.9, maxPaintExtent: 1632.0, hasVisualOverflow: true, cacheExtent: 761.9)
...&nbsp; &nbsp; &nbsp; scrollExtent: 1632.0
...&nbsp; &nbsp; &nbsp; paintExtent: 511.9
...&nbsp; &nbsp; &nbsp; maxPaintExtent: 1632.0
...&nbsp; &nbsp; &nbsp; hasVisualOverflow: true
...&nbsp; &nbsp; &nbsp; cacheExtent: 761.9
...&nbsp; &nbsp; padding: EdgeInsets.zero
...&nbsp; &nbsp; textDirection: ltr
...&nbsp; &nbsp; child: RenderSliverList#f0374 relayoutBoundary=up2
...&nbsp; &nbsp; &nbsp; needs compositing
...&nbsp; &nbsp; &nbsp; parentData: paintOffset=Offset(0.0, 0.0) (can use size)
...&nbsp; &nbsp; &nbsp; constraints: SliverConstraints(AxisDirection.down, GrowthDirection.forward, ScrollDirection.forward, scrollOffset: 0.0, remainingPaintExtent: 511.9, crossAxisExtent: 414.0, crossAxisDirection: AxisDirection.right, viewportMainAxisExtent: 511.9, remainingCacheExtent: 761.9, cacheOrigin: 0.0)
...&nbsp; &nbsp; &nbsp; geometry: SliverGeometry(scrollExtent: 1632.0, paintExtent: 511.9, maxPaintExtent: 1632.0, hasVisualOverflow: true, cacheExtent: 761.9)
...&nbsp; &nbsp; &nbsp; &nbsp; scrollExtent: 1632.0
...&nbsp; &nbsp; &nbsp; &nbsp; paintExtent: 511.9
...&nbsp; &nbsp; &nbsp; &nbsp; maxPaintExtent: 1632.0
...&nbsp; &nbsp; &nbsp; &nbsp; hasVisualOverflow: true
...&nbsp; &nbsp; &nbsp; &nbsp; cacheExtent: 761.9
...&nbsp; &nbsp; &nbsp; currently live children: 0 to 5
...&nbsp; &nbsp; &nbsp; child with index 0: RenderIndexedSemantics#aabf9 relayoutBoundary=up3
...&nbsp; &nbsp; &nbsp; &nbsp; needs compositing
...&nbsp; &nbsp; &nbsp; &nbsp; parentData: index=0; layoutOffset=0.0 (can use size)
...&nbsp; &nbsp; &nbsp; &nbsp; constraints: BoxConstraints(w=414.0, 0.0<=h<=Infinity)
...&nbsp; &nbsp; &nbsp; &nbsp; semantics node: SemanticsNode#37
...&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Rect.fromLTRB(0.0, 0.0, 414.0, 85.0)
...&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; tags: RenderViewport.twoPane







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "flutter/flutter"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月22日(星期一) 下午2:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [flutter/flutter] 'package:flutter/src/widgets/scroll_position.dart': Failed assertion: line 514 pos 12: 'haveDimensions == (_lastMetrics != null)': is not true. (#78604)





 
@haifeng94
 Thanks for the code sample. I see that you are using cached_network_image plugin which is 3rd party. Can you try to remove the plugin and it's relevant code and see if issue still persists or not ? If yes, please provide updated code repro.

**Comment by darshankawar** [comment] 2021-03-23 07:35
@haifeng94 
Thanks for the update. It'll be good if you could update the example in the repo, so that we can directly clone it and run to verify this issue ? Currently, it's time consuming to copy paste the dart files locally. Also cloning it will also need to add configurations locally in IDE since it doesn't have required pubspec.yaml and other required files.

**Comment by pedromassangocode** [comment] 2021-04-14 10:50
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2021-04-14 10:50 UTC
Labels: in triage, waiting for customer response
