### ISSUE TITLE
error on using GetMaterialApp

### ISSUE THREAD

**Issue by ahmedsharkawy2020** [flutter/flutter#82667] opened 2021-05-17 01:16 UTC
while using GetMaterialApp i get an error
this is the code
```
import 'package:flutter/material.dart';

import 'package:get/get.dart';

import '../controllers/signin_controller.dart';

class SigninView extends GetView<SigninController> {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      //textDirection: TextDirection.rtl,
      home: Scaffold(
        appBar: AppBar(
          title: Text(
            'HomeView',
            textDirection: TextDirection.rtl,
          ),
          centerTitle: true,
        ),
        body: Center(
            child: PageView(
          children: [
            Container(
              width: context.width,
              height: context.height,
              child: Column(
                children: [],
              ),
            ),
            Container(),
            Container(),
            Container(),
            Container(),
          ],
        )),
      ),
    );
  }
}

```

and the error

```
[GETX] GOING TO ROUTE /signin

════════ Exception caught by widgets library ═══════════════════════════════════
The following assertion was thrown building Directionality(textDirection: ltr):
'package:flutter/src/widgets/framework.dart': Failed assertion: line 4554 pos 12: 'child == _child': is not true.
2

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was
Directionality
..\…\root\get_material_app.dart:285
When the exception was thrown, this was the stack
#2      ComponentElement.forgetChild
package:flutter/…/widgets/framework.dart:4554
#3      Element._retakeInactiveElement
package:flutter/…/widgets/framework.dart:3494
...     Normal element mounting (452 frames)
#455    Element.inflateWidget
package:flutter/…/widgets/framework.dart:3541
#456    MultiChildRenderObjectElement.mount
package:flutter/…/widgets/framework.dart:6094
...
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
Duplicate GlobalKey detected in widget tree.

```

**Comment by iapicca** [comment] 2021-05-17 04:22
@ahmedsharkawy2020 
this seems to be a problem with [get](https://pub.dev/packages/get) rather than flutter
you may want to open an issue [here](https://github.com/jonataslaw/getx/issues)

**Comment by darshankawar** [comment] 2021-05-17 12:03
@ahmedsharkawy2020 
As mentioned above, please report this in dedicated repo.
If you think this isn't an issue with the plugin, but with the framework, write in comments with minimal reproducible code sample without any 3rd party plugin code, and I'll reopen it.

Thanks.
Closing from here.

**Closed by darshankawar** 2021-05-17 12:03 UTC
Labels: in triage
