### ISSUE TITLE
[devicelab] microbenchmarks_ios execution time was 16 minutes (90th %) for 10/26-11/08 period

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#70247] opened 2020-11-11 00:14 UTC
The SLO for devicelab task execution time is 5 min, but definitely should not exceed 15 min.

**Comment by godofredoc** [comment] 2020-11-11 03:52
@keyonghan  What was the previous 90th percentile?

**Comment by keyonghan** [comment] 2020-11-11 17:22
> @keyonghan What was the previous 90th percentile?

![Screen Shot 2020-11-11 at 9 21 43 AM](https://user-images.githubusercontent.com/54558023/98843096-597e1580-23ff-11eb-80fc-15f749388203.png)

**Comment by godofredoc** [comment] 2020-11-12 23:27
@liyuqian can you please take a look? seems like this test execution time has almost doubled.

**Comment by liyuqian** [comment] 2020-11-17 00:15
https://github.com/flutter/flutter/pull/68214 seems to be the only microbenchmarks we added recently. @dnfield : do you know how many seconds does this microbenchmark run on iPhone 6s?

Meanwhile, we've seen 3 microbenchmark regressions in the past few weeks:
- https://github.com/flutter/flutter/issues/69586
- https://github.com/flutter/flutter/issues/69583
- https://github.com/flutter/flutter/issues/68890

Luckily, all of them are now close to the numbers before the regression. So I think microbenchmarks_ios execution time would be back to normal if https://github.com/flutter/flutter/pull/68214 doesn't introduce too much workload.

To further reduce the execution timespan, in the cost of total execution time, is to split the microbenchmarks into different devicelab tasks. That way, each task can be finished within 5 minutes. Please let me know if that's desired from the infra perspective. If so, I can write a PR for that.

**Comment by dnfield** [comment] 2020-11-17 00:53
I don't have access to an iPhone 6s. We can reduce the number of iterations if it helps, we'd just have to rebaseline the benchmark.

**Comment by dnfield** [comment] 2020-11-17 00:53
We may also want to consider splitting microbenchmarks into two or more runs.

**Comment by dnfield** [comment] 2020-11-17 04:33
This benchmark is currently making the tree red because it's taking > 2 hours to execute and timing out.

**Comment by dnfield** [comment] 2020-11-17 17:28
I was incorrect - there was an actual regression that caused a benchmark to timeout.

**Comment by godofredoc** [comment] 2021-10-13 22:32
closing as obsolete.

**Closed by godofredoc** 2021-10-13 22:32 UTC
Labels: passed first triage, team: infra, passed secondary triage, P3
