### ISSUE TITLE
Flutter doctor error: 404 artifact not found.

### ISSUE THREAD

**Issue by sureshg** [flutter/flutter#6648] opened 2016-11-02 15:58 UTC
## Steps to Reproduce

* Get the latest code
* Run `flutter doctor`

## Flutter Doctor

```
$ flutter doctor
Downloading package sky_engine...                    359ms
Running 'flutter packages get' in sky_engine...      315ms
Building Dart SDK summary...                         1348ms
Downloading engine artifacts android-arm...          1434ms
Downloading engine artifacts android-arm-profile...  1289ms
Downloading engine artifacts android-arm-release...  1094ms
Downloading engine artifacts android-x64...          1113ms
Downloading engine artifacts android-x86...          952ms
Downloading engine artifacts ios...                      
Download failed: https://storage.googleapis.com/flutter_infra/flutter/e54b0e286ba7e07dcc32d12d8c68f6ca45cdbdf7/ios/artifacts.zip
  because (404) Not Found
If this problem persists, please report the problem at
https://github.com/flutter/flutter/issues/new
```

**Comment by eseidelGoogle** [comment] 2016-11-02 16:04
Did we roll too soon @abarth?

**Comment by eseidelGoogle** [comment] 2016-11-02 16:05
Yup.  I'm hitting this too:

```
Download failed: https://storage.googleapis.com/flutter_infra/flutter/e54b0e286ba7e07dcc32d12d8c68f6ca45cdbdf7/ios/artifacts.zip
  because (404) Not Found
```

**Comment by eseidelGoogle** [comment] 2016-11-02 16:05
This would be caused by https://github.com/flutter/flutter/commit/c29cd696d46230b89ab671308fd8c8fee1042c94.

**Comment by chinmaygarde** [comment] 2016-11-02 23:44
This was fixed by the latest engine roll. https://github.com/flutter/flutter/commit/32c9b4cd8067f42bc60d148232fbff329c127f14

**Closed by chinmaygarde** 2016-11-02 23:44 UTC
Labels: ⚠ bug

**Comment by sethladd** [comment] 2016-11-03 00:01
Thanks!

**Comment by balajiks-dev** [comment] 2020-02-12 04:46
Hi, I'm getting this issue from FLutter Command. No Flutter Command is running, it shows this error 404. Anyone help me out of this.


Downloading darwin-x64/font-subset tools...                     
Download failed.
URL: https://storage.googleapis.com/flutter_infra/flutter/a67792536ca236a971d0efbcfd7af4efb8f6c119/darwin-x64/font-subset.zip
Error: 404 Not Found
exit code 50



Thanks!
