### ISSUE TITLE
Not able to talk with local server

### ISSUE THREAD

**Issue by kunaldodiya** [flutter/flutter#31535] opened 2019-04-24 04:27 UTC
hi, How can i use http request to local laravel server, please note that my server running on 192.168.1.2:8000 working fine.. but i am not using these address, there is laravel valet package that proxy all request to 127.0.0.1 to .test domain, but i am not able to use example.test, it throwing exception

**Comment by dnfield** [comment] 2019-04-24 06:08
I think this is a duplicate of https://github.com/flutter/flutter/issues/20376

**Closed by dnfield** 2019-04-24 06:08 UTC
