### ISSUE TITLE
getting an error while I am trying to launch my app on the ios simulator

### ISSUE THREAD

**Issue by DeveloperMalay** [flutter/flutter#124643] opened 2023-04-12 00:38 UTC
when I want to run my app in the ios simulator or I try to create a build I get this error -

Error (Xcode): File not found:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/arc/libarclite_iphonesimula
tor.a

Error (Xcode): Linker command failed with exit code 1 (use -v to see invocation)

please help me to resolve this issue

**Comment by huycozy** [comment] 2023-04-12 07:42
Hi @DeveloperMalay 
Please provide the complete output of `flutter run -v`, `flutter doctor -v` so that we may verify the issue. Thanks!

**Comment by jmagman** [comment] 2023-04-12 21:31
This is a duplicate of https://github.com/flutter/flutter/issues/124340 caused by a change of behavior in Xcode 14.3.  Please upgrade to Flutter 3.7.11.

**Closed by jmagman** 2023-04-12 21:31 UTC
Labels: waiting for customer response, in triage
