### ISSUE TITLE
Images disappearing when scrolling using ListView

### ISSUE THREAD

**Issue by GioPan04** [flutter/flutter#42339] opened 2019-10-09 16:40 UTC
## Steps to Reproduce

Code:
```dart
@override
  Widget build(BuildContext context) {
    final double width = MediaQuery.of(context).size.width;
    super.build(context);
    return ListView(
      children: <Widget>[
        Image.network('https://wallpaperaccess.com/full/11740.jpg', width: width, height: width, fit: BoxFit.cover,),
        Image.network('https://wallpaperaccess.com/full/11740.jpg', width: width, height: width, fit: BoxFit.cover,),
        Image.network('https://wallpaperaccess.com/full/11740.jpg', width: width, height: width, fit: BoxFit.cover,),
...
      ],
    );
  }
```

![Preview](https://user-images.githubusercontent.com/29762826/66503531-c53cd300-eac7-11e9-8040-5b300c5b8971.gif)

**Target Platform: iOS and Android**
**Target OS version/browser: Android 10 and iOS 13**
**Devices: All devices**

## Logs

flutter analyze:
```
Analizing app...

   info - Unused import: 'dart:io' - lib\initialquestion.dart:1:8 - unused_import

1 issues found. (ran in 101.0s)
```

flutter doctor -v:
```
[√] Flutter (Channel stable, v1.9.1+hotfix.4, on Microsoft Windows [Versione 10.0.18362.356], locale it-IT)
    • Flutter version 1.9.1+hotfix.4 at C:\flutter
    • Framework revision cc949a8e8b (12 days ago), 2019-09-27 15:04:59 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\Gioele\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.38.1)
    • VS Code at C:\Users\Gioele\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.5.1

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```

**Comment by shashwatxx** [comment] 2019-10-09 18:06
I think it's because ListView Builds widget only in the current Screen view. and destroy as soon they leave screen

**Comment by GioPan-sh** [comment] 2019-10-09 18:26
I set the cacheExtent value to 99999 for a test, but nothing changed. There is another way to fix this?

**Comment by shashwatxx** [comment] 2019-10-10 06:18
I tried that only that specific is causing this issue, and maybe the size of the image could be a problem cause it's of nearly 2MB, but also I tried that for other larger size images and it's working fine.
Try changing the size of the image or by replacing the image

**Comment by GioPan-sh** [comment] 2019-10-10 10:41
OK, with smaller images it's working. But Can I use bigger images?

**Comment by shashwatxx** [comment] 2019-10-15 17:18
not recommended to use cause it will increase your app size if you use it as asset image and will take more data and memory if used as the network image

**Comment by bogdannedelcu** [comment] 2019-11-04 10:56
what about images downloaded from the internet, where we do not control the size and we must show them in a scrolling list.  We tried using CachedNetworkImage, ExtendedImage, but neither solves this problem.

**Comment by Nisthar** [comment] 2019-12-04 17:26
@bogdannedelcu same issue here

**Comment by GioPan04** [comment] 2019-12-04 17:43
@Nisthar The only way to solve this is to do what @shashwatxx recommended. Try to use smaller image... I've not found any way to use bigger images

**Comment by Nisthar** [comment] 2019-12-05 06:13
@GioPan04 Thanks. i had the same issue with smaller images. i solved it by setting `cacheExtent` to large value.

**Comment by bogdannedelcu** [comment] 2019-12-05 14:57
Indeed using large images is a problem. We started using the image service and it seems to work very well to resize and serve fast the images.

https://blog.albert-chen.com/resize-images-on-google-cloud-storage/

**Comment by shashwatxx** [comment] 2019-12-08 21:20
I'm working on that thing of automatic conversion of the image on the fly so that they do not disappear in Grid view, I'll let you guys know when it's done.

**Comment by christianarduino** [comment] 2020-02-13 11:36
Any update?

**Comment by dnfield** [comment] 2020-02-25 10:04
Can you please share a full sample that reproduces this problem?  The example in the top post here has some undefined variables in it.

**Comment by sooxt98** [comment] 2020-03-17 17:04
Same issue here, Im using Image `cacheWidth ` and flutter_staggered_grid_view

**Comment by GioPan04** [comment] 2020-03-17 20:07
@dnfield The only variable declared is width, and it's written that is equal to the width of the device

**Comment by dnfield** [comment] 2020-03-17 21:00
Please share a full `main.dart` file that can be run that reproduces this issue.

Right now there's just a snippet with lots of things missing.  Any engineer that wants to work on this will have to figure out what's missing, try to get it working locally, see if they can reproduce it, maybe find they can't, ask on the issue about how to reproduce it, etc.  It's a pretty substantial investment on the part of the engineer, and there's no guarantee that the bug will be reproduced and actionable. 

If you can add a _minimal, full_ reproduction of this bug then it will likely get fixed quickly.  Without that, it will take someone investing the time to do that and figuring out if it's really a bug in Flutter or not.

**Comment by GioPan04** [comment] 2020-03-17 21:28
@dnfield Okay, I'll send the full `main.dart` asap

**Comment by xuzhengquan** [comment] 2020-03-24 08:29
Any update?

**Comment by GioPan04** [comment] 2020-03-27 12:45
Ok so, I tried rewriting the code that i had when I had this issue. It looks like that now it's working even with bigger images. I think that with newer versions it has been resolved... But I see that someone like @xuzhengquan has the same issue with the latest version. Can you share your code?

**Comment by dnfield** [comment] 2020-03-27 14:49
Going to close this as not reproducible.  If someone adds a reproduction we can reopen.

**Closed by dnfield** 2020-03-27 14:49 UTC
Labels: a: assets, a: images, engine, f: scrolling, severe: rendering

**Comment by Renatinaveen** [comment] 2020-04-16 13:30
https://drive.google.com/file/d/1w5dEXmKuiKXadzXSxiVbb2GjR05htY6Z/view?usp=sharing

i have this issue while scrolling, and if i scroll fast the images disappear and reappear when scrolling is stopped

**Comment by dnfield** [comment] 2020-04-16 14:04
@Renatinaveen that is a different issue.  Please file a new one.  However, what you are describing is intended behavior to avoid running out of memory when scrolling an infinite or large list of images rapidly.

**Comment by Renatinaveen** [comment] 2020-04-16 14:11
@dnfield how to solve this?

**Comment by dnfield** [comment] 2020-04-16 14:18
You can provide custom scroll physics that overrides https://master-api.flutter.dev/flutter/widgets/ScrollPhysics/recommendDeferredLoading.html

Just be cautious, since too aggressively loading images will cause your application to crash.

**Comment by Renatinaveen** [comment] 2020-04-16 15:13
Sir, we have release the update next week. I need to solve this issue
before that. If you can help with this it'll be appreciated very much.
Thank you.

**Comment by softmarshmallow** [comment] 2020-09-03 07:54
same thing happens when using custom painter inside list tile, the vertically long painter disappears when scrolling.
maybe add a option of index allowed on out-screen?

**Comment by GioPan04** [comment] 2020-09-03 08:34
@softmarshmallow Theoretically cacheExtent parameter does that

**Comment by zierka** [comment] 2020-09-25 08:21
Not sure if it's the same, but for me the issue occurred because the image was wrapped in an [Opacity](https://api.flutter.dev/flutter/widgets/Opacity-class.html). Removing it and implementing transparency on the image directly (following the recommendations on the Opacity class api documentations) fixed the issue.

**Comment by aniketsongara** [comment] 2020-10-19 12:05
Having same problem when i  am getting html data from firebase server 
**Disappear data from Listview.builder When i scroll up listview data item.**
  
```

     StreamBuilder(
                          stream: Firestore.instance
                              .collection("editor_table")
                              .orderBy('timestamp', descending: true)
                              .snapshots(),
                          builder: (context, snapshot) {
                            if (!snapshot.hasData) {
                              return Center(child: CircularProgressIndicator());
                            }
                            return ListView.builder(
                              padding: EdgeInsets.all(10.0),
                              shrinkWrap: true,
                              itemBuilder: (context, index) => ViewHtml(
                                uri: snapshot.data.documents[index]['content'],
                                name: snapshot.data.documents[index]['fileName'],
                                reference: snapshot.data.documents[index].reference,
                              ),  // custom class for showing html data into listview.builder  
                              itemCount: snapshot.data.documents.length,
                            );
                          })
```

**Comment by sanekyy** [comment] 2020-11-19 11:49
same issue on Flutter Web on iOS
