### ISSUE TITLE
[Impeller] ColorBurn not work with CustomPaint.

### ISSUE THREAD

**Issue by zhxst** [flutter/flutter#147207] opened 2024-04-23 03:03 UTC
### Steps to reproduce

1. Just run the sample code.
2. The image should be a black circle in the center
3. With Impeller on stable channel, the `colorBurn` has no effect.
4. With Impeller on master channel, the `colorBurn` makes whole screen black.
5. With Skia on stable channel, the `colorBurn` render a black circle, but with a **purple** outline.

Would you please create some test for all these blend mode on Impeller?
Here are the issues I have filed before: #134930 #141160 #145442 #130059
Flutter is great and I use CustomPaint to create some visual effects in App. 
It seems the Skia backend will be removed in the next release. But I still cannot enable Impeller because of render issues with blend mode.

### Expected results

This the effect rendered from Figma
<img width="215" alt="e6b7db21-6454-4773-9f71-9bf6710b04d2" src="https://github.com/flutter/flutter/assets/11647836/9708113f-e624-4b76-965f-cb6416fa5444">

### Actual results

<table>
<tr>
<td>3.19.5 with Impeller</td>
<td>master with Impeller</td>
<td>3.19.5 with Skia</td>
</tr>
<tr>
<td>
<img width ="180"
src="https://github.com/flutter/flutter/assets/11647836/a3e5d345-d37f-42d6-8742-91d51987e1a1">
</td>
<td>
<img width ="180"
src="https://github.com/flutter/flutter/assets/11647836/958e4fd7-2556-44ec-9e87-2803c813596f">
</td>
<td>
<img width ="180"
src="https://github.com/flutter/flutter/assets/11647836/44dfb90b-67a7-4258-8b1d-33701162ff6e">
</td>
</tr>
</table>

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: Scaffold(
          body: SizedBox.expand(
        child: CustomPaint(
          painter: DodgePainter(),
        ),
      )),
    );
  }
}

class DodgePainter extends CustomPainter {
  const DodgePainter();

  @override
  void paint(Canvas canvas, Size size) {
    final radius = size.width / 5;
    final blur = Paint()
      ..color = Colors.black
      ..maskFilter = const MaskFilter.blur(BlurStyle.normal, 40);
    final center = size.center(Offset.zero);
    canvas.drawCircle(center, radius, blur);

    final dodge = Paint()
      ..color = Colors.grey
      ..blendMode = BlendMode.colorDodge;
    canvas.drawPaint(dodge);

    final colorBurn = Paint()
      ..color = Colors.black
      ..blendMode = BlendMode.colorBurn;
    canvas.drawPaint(colorBurn);
  }

  @override
  bool shouldRepaint(DodgePainter oldDelegate) {
    return true;
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.19.5, on macOS 13.6 22G120 darwin-arm64, locale zh-Hans-CN)
    • Flutter version 3.19.5 on channel stable at /Users/zhx/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 300451adae (4 weeks ago), 2024-03-27 21:54:07 -0500
    • Engine revision e76c956498
    • Dart version 3.3.3
    • DevTools version 2.31.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/zhx/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode_15.2.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.15.2

[✓] Android Studio (version 2023.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

[✓] VS Code (version 1.88.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.87.20240402

[✓] Connected device (1 available)
    • iPhone11 (mobile) • 00008030-000xxxxxxxxxxxx • ios • iOS 16.5.1 20F75
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by gaaclarke** [comment] 2024-04-24 23:41
Here is the trace:
[Runner.gputrace.zip](https://github.com/flutter/flutter/files/15101971/Runner.gputrace.zip)

## 1) rrect shadow
<img width="225" alt="Screenshot 2024-04-24 at 4 30 11 PM" src="https://github.com/flutter/flutter/assets/30870216/dc24fe44-efe6-4066-8a03-181b772c020b">

## 2) framebuffer advanced blend filter
<img width="218" alt="Screenshot 2024-04-24 at 4 30 20 PM" src="https://github.com/flutter/flutter/assets/30870216/a6c4201a-68c4-4b51-b3e4-9f25254b8cd5">

## 3) framebuffer advanced blend filter
<img width="214" alt="Screenshot 2024-04-24 at 4 30 29 PM" src="https://github.com/flutter/flutter/assets/30870216/43811f37-7d9f-491b-806f-99fb632821eb">

**Comment by gaaclarke** [comment] 2024-04-25 22:21
According to https://www.w3.org/TR/compositing-1/#blendingcolorburn, applying a ColorBurn of black, the result should equal black.  Here is the definition:
```
if(Cb == 1)
    B(Cb, Cs) = 1
else if(Cs == 0)
    B(Cb, Cs) = 0
else
    B(Cb, Cs) = 1 - min(1, (1 - Cb) / Cs)
```
In our case Cs is the src, Cb is the dst.

I audited our ColorBurn math and it seems to match that definition.  So, it should result in a complete black drawing, skia is incorrect in this case.  Impeller is correct.

For the red burn above we should be getting outside the blur, in the red channel:
B(1, 1) = 1, which is correct
green:
B(1, 0) = 0, which is correct.
blue:
B(1, 0) = 0, which is correct.

Again, impeller is correct and skia is wrong in my estimation.

**Comment by gaaclarke** [comment] 2024-04-25 22:46
@bdero would you mind spotting me, that drawing black in this case is the correct behavior? See https://github.com/flutter/flutter/issues/147207#issuecomment-2078267796

**Comment by gaaclarke** [comment] 2024-04-26 17:14
WAI.  I'm going to close this because the behavior of impeller on the main channel is the correct behavior.  I know that's a pain, but we aren't going to reproduce incorrect math for continuity's sake.

**Closed by gaaclarke** 2024-04-26 17:14 UTC
Labels: P1, e: impeller, team-engine

**Comment by zhxst** [comment] 2024-04-28 00:54
Thank you for your response. I have checked color burn on Photoshop, It was black indeed. So the Figma and Skia is special.
Anyway, I changed the black color to Color(0xff010101), and it solve the problem.
