### ISSUE TITLE
(web only) adding a GestureDetector widget to a TextSpan breaks other GestureRecognizers

### ISSUE THREAD

**Issue by stuz5000** [flutter/flutter#70159] opened 2020-11-10 06:21 UTC
## Steps to Reproduce

Run example below:

- in the Android emulator all texts respond to onTap, 
- in web, the final 'GestureRecognizer' text is not tappable, and the `Tap1` text responds to `Tap2`'s callback!

Adding a GestureDetector widget to the TextSpan has broken the TapGestureRecognizers for the other text spans.

---> no tappable widget can be mixed with tappable text spans. This is a problem if you want text together with widget that flow correctly over long lines.

```
import 'package:flutter/gestures.dart';
import 'package:flutter/material.dart';

void main() => runApp(MaterialApp(
        home: Scaffold(
            body: SafeArea(
                child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
          TestWidget(false), //
          Text(""), //
          TestWidget(true)
        ])))));

class TestWidget extends StatelessWidget {
  bool showTap3;

  TestWidget(this.showTap3);

  @override
  Widget build(BuildContext context) {
    final List<InlineSpan> children = [
      TextSpan(
          text: "Tap1",
          recognizer: TapGestureRecognizer()
            ..onTap = () {
              print("Tapped1");
            }),
      TextSpan(text: "---------"),
      TextSpan(
          text: "Tap2",
          recognizer: TapGestureRecognizer()
            ..onTap = () {
              print("Tapped2");
            }),
      TextSpan(text: "---------"),
      if (showTap3)
        WidgetSpan(
            child: GestureDetector(
          onTap: () {
            print("Tapped3");
          },
          child: Text(">>GestureDetector<<"),
        )),
    ];

    return Text.rich(TextSpan(children: children));
  }
}
```

```
[✓] Flutter (Channel unknown, 1.22.0-12.2.pre, on Linux, locale en_US.UTF-8)
    • Flutter version 1.22.0-12.2.pre at /home/sir/development/flutter
    • Framework revision 2bafdc8226 (6 weeks ago), 2020-09-25 12:48:22 -0700
    • Engine revision f763b5b9b9
    • Dart version 2.10.0 (build 2.10.0-110.5.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/sir/Android/Sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /home/sir/soft/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /home/sir/soft/android-studio
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (3 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Web Server (web)                   • web-server    • web-javascript • Flutter Tools
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 80.0.3987.149

• No issues found!
Process finished with exit code 0
```

</details>

**Comment by stuz5000** [comment] 2020-11-10 06:25
Related to https://github.com/flutter/flutter/issues/51936 (break on iOS).

**Comment by darshankawar** [comment] 2020-11-10 07:43
Verified and replicable on latest master and latest beta. Tapping on widgets wrapped inside `Text.rich` widgets are not recognized.
```

Tapped3
Tapped3
Tapped3
Tapped3
Tapped2
Tapped1



Tapped3
Tapped2
Tapped1
Tapped3
Tapped2
Tapped1
```

Works well on Android:

```
Waiting for SM G975F to report its views...
Debug service listening on ws://127.0.0.1:54128/V1aA5XfO8r8=/ws
Syncing files to device SM G975F...
D/ViewRootImpl@3c97124[MainActivity]( 4433): ViewPostIme pointer 0
D/ViewRootImpl@3c97124[MainActivity]( 4433): ViewPostIme pointer 1
I/flutter ( 4433): Tapped3
D/ViewRootImpl@3c97124[MainActivity]( 4433): ViewPostIme pointer 0
D/ViewRootImpl@3c97124[MainActivity]( 4433): ViewPostIme pointer 1
D/ViewRootImpl@3c97124[MainActivity]( 4433): ViewPostIme pointer 0
D/ViewRootImpl@3c97124[MainActivity]( 4433): ViewPostIme pointer 1
I/flutter ( 4433): Tapped1
D/ViewRootImpl@3c97124[MainActivity]( 4433): ViewPostIme pointer 0
D/ViewRootImpl@3c97124[MainActivity]( 4433): ViewPostIme pointer 1
I/flutter ( 4433): Tapped2
D/ViewRootImpl@3c97124[MainActivity]( 4433): ViewPostIme pointer 0
D/ViewRootImpl@3c97124[MainActivity]( 4433): ViewPostIme pointer 1
I/flutter ( 4433): Tapped1
D/ViewRootImpl@3c97124[MainActivity]( 4433): ViewPostIme pointer 0
D/ViewRootImpl@3c97124[MainActivity]( 4433): ViewPostIme pointer 1
I/flutter ( 4433): Tapped2
D/ViewRootImpl@3c97124[MainActivity]( 4433): ViewPostIme pointer 0
D/ViewRootImpl@3c97124[MainActivity]( 4433): ViewPostIme pointer 1
I/flutter ( 4433): Tapped1
D/ViewRootImpl@3c97124[MainActivity]( 4433): ViewPostIme pointer 0
D/ViewRootImpl@3c97124[MainActivity]( 4433): ViewPostIme pointer 1
I/flutter ( 4433): Tapped2
D/ViewRootImpl@3c97124[MainActivity]( 4433): ViewPostIme pointer 0
D/ViewRootImpl@3c97124[MainActivity]( 4433): ViewPostIme pointer 1
I/flutter ( 4433): Tapped1
D/ViewRootImpl@3c97124[MainActivity]( 4433): ViewPostIme pointer 0
D/ViewRootImpl@3c97124[MainActivity]( 4433): ViewPostIme pointer 1
D/ViewRootImpl@3c97124[MainActivity]( 4433): ViewPostIme pointer 0
D/ViewRootImpl@3c97124[MainActivity]( 4433): ViewPostIme pointer 1
I/flutter ( 4433): Tapped2
D/ViewRootImpl@3c97124[MainActivity]( 4433): ViewPostIme pointer 0
D/ViewRootImpl@3c97124[MainActivity]( 4433): ViewPostIme pointer 1
D/ViewRootImpl@3c97124[MainActivity]( 4433): ViewPostIme pointer 0
D/ViewRootImpl@3c97124[MainActivity]( 4433): ViewPostIme pointer 1
I/flutter ( 4433): Tapped1
```

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel beta, 1.23.0-18.1.pre, on Mac OS X 10.15.4 19E2269 x86_64,
    locale en-IN)
    • Flutter version 1.23.0-18.1.pre at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 198df796aa (4 weeks ago), 2020-10-15 12:04:33 -0700
    • Engine revision 1d12d82d9c
    • Dart version 2.11.0 (build 2.11.0-213.1.beta)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.1

[✓] Connected device (3 available)
    • SM G975F (mobile) • RZ8M802WY0X • android-arm64  • Android 10 (API 29)
    • Web Server (web)  • web-server  • web-javascript • Flutter Tools
    • Chrome (web)      • chrome      • web-javascript • Google Chrome
      86.0.4240.183

• No issues found!

```

</details>

**Comment by darshankawar** [comment] 2020-11-10 07:44
Related but closed issues

https://github.com/flutter/flutter/issues/46975

https://github.com/flutter/flutter/issues/34931

**Comment by mdebbar** [comment] 2020-11-12 23:45
Duplicate of https://github.com/flutter/flutter/issues/63638

**Closed by mdebbar** 2020-11-12 23:45 UTC
Labels: assigned for triage, f: gestures, found in release: 1.23, framework, has reproducible steps, passed first triage, platform-web
