### ISSUE TITLE
obsecureText = true causing app to crash. (1.21.0-9.2.pre)

### ISSUE THREAD

**Issue by willladislaw** [flutter/flutter#64866] opened 2020-08-29 14:13 UTC
```
_passwordField() {
    return new TextFormField(
      controller: _passwordCtrl,
      keyboardType: TextInputType.visiblePassword,
      style: new TextStyle(color: Colors.black87),
      autofocus: false,
      obscureText: true, <-- here
      decoration: new InputDecoration(
        hintText: 'Password',
        contentPadding: EdgeInsets.fromLTRB(20.0, 10.0, 20.0, 10.0),
        fillColor: Colors.white,
        filled: true,
        border: new OutlineInputBorder(
          borderRadius: new BorderRadius.circular(5.0),
        ),
      )
    );
  }
```

doctor output 

```
flutter doctor -v
[✓] Flutter (Channel beta, 1.21.0-9.2.pre, on Mac OS X 10.15.6 19G2021, locale en-GB)
    • Flutter version 1.21.0-9.2.pre at /Users/me/flutter
    • Framework revision 81a45ec2e5 (2 days ago), 2020-08-27 14:14:33 -0700
    • Engine revision 20a9531835
    • Dart version 2.10.0 (build 2.10.0-7.3.beta)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/me/Library/Android/sdk
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.10.0.beta.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.1.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 45.1.3
    • Dart plugin version 201.7223.99

 
[✓] Connected device (4 available)            
    • iPhone SE (2nd generation) (mobile) • 945A55C9-6399-4BC6-9410-D16A19EF8047 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-6 (simulator)
    • Web Server (web)                    • web-server                           • web-javascript • Flutter Tools
    • Chrome (web)                        • chrome                               • web-javascript • Google Chrome 84.0.4147.135

• No issues found!
```

**Comment by TahaTesser** [comment] 2020-08-31 13:05
Hi @willladislaw 
Can't reproduce this issue on any channel 

Check out this code sample 

<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatefulWidget {
  @override
  _HomeState createState() => _HomeState();
}

class _HomeState extends State<Home> {
  TextEditingController _controller = TextEditingController();

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: TextFormField(
            controller: _controller,
            keyboardType: TextInputType.visiblePassword,
            style: new TextStyle(color: Colors.black87),
            autofocus: false,
            obscureText: true,
            decoration: new InputDecoration(
              hintText: 'Password',
              contentPadding: EdgeInsets.fromLTRB(20.0, 10.0, 20.0, 10.0),
              fillColor: Colors.white,
              filled: true,
              border: new OutlineInputBorder(
                borderRadius: new BorderRadius.circular(5.0),
              ),
            )),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {},
      ),
    );
  }
}

```

</details> 

Can you please provide your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by willladislaw** [comment] 2020-08-31 13:59
Fill out the `_emailField()` with something random and switch to `_passwfield()`. 

Note: You'll need to rerun the app if the exception was not thrown on the first switch and try again ( takes a couple of attempts before crash).

body: Column(
 children: <Widget>[
   _emailField() ,
   _passwordField()
]
)

   _emailField() {
    return new TextFormField(
      controller: _usernameCtrl,
      keyboardType: TextInputType.emailAddress,
      style: new TextStyle(color: Colors.black87),
      decoration: new InputDecoration(
        contentPadding: EdgeInsets.fromLTRB(20.0, 10.0, 20.0, 10.0),
        hintText: 'Email or Username',
        fillColor: Colors.white,
        filled: true,
        border: new OutlineInputBorder(
          borderRadius: new BorderRadius.circular(5.0),
        ),
      )
    );
  }

_passwordField() {
    return new TextFormField(
      controller: _passwordCtrl,
      keyboardType: TextInputType.visiblePassword,
      style: new TextStyle(color: Colors.black87),
      autofocus: false,
      obscureText: true, <-- here
      decoration: new InputDecoration(
        hintText: 'Password',
        contentPadding: EdgeInsets.fromLTRB(20.0, 10.0, 20.0, 10.0),
        fillColor: Colors.white,
        filled: true,
        border: new OutlineInputBorder(
          borderRadius: new BorderRadius.circular(5.0),
        ),
      )
    );
  }

**Comment by TahaTesser** [comment] 2020-09-01 07:19
Hi @willladislaw 
There is no crash when using the code sample

Please try this and reproduce the crash 

<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatefulWidget {
  @override
  _HomeState createState() => _HomeState();
}

class _HomeState extends State<Home> {
  TextEditingController _usernameCtrl = TextEditingController();
  TextEditingController _passwordCtrl = TextEditingController();

  @override
  void dispose() {
    _usernameCtrl.dispose();
    _passwordCtrl.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Column(children: <Widget>[_emailField(), _passwordField()]),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {},
      ),
    );
  }

  _emailField() {
    return new TextFormField(
        controller: _usernameCtrl,
        keyboardType: TextInputType.emailAddress,
        style: new TextStyle(color: Colors.black87),
        decoration: new InputDecoration(
          contentPadding: EdgeInsets.fromLTRB(20.0, 10.0, 20.0, 10.0),
          hintText: 'Email or Username',
          fillColor: Colors.white,
          filled: true,
          border: new OutlineInputBorder(
            borderRadius: new BorderRadius.circular(5.0),
          ),
        ));
  }

  _passwordField() {
    return new TextFormField(
        controller: _passwordCtrl,
        keyboardType: TextInputType.visiblePassword,
        style: new TextStyle(color: Colors.black87),
        autofocus: false,
        obscureText: true,
        decoration: new InputDecoration(
          hintText: 'Password',
          contentPadding: EdgeInsets.fromLTRB(20.0, 10.0, 20.0, 10.0),
          fillColor: Colors.white,
          filled: true,
          border: new OutlineInputBorder(
            borderRadius: new BorderRadius.circular(5.0),
          ),
        ));
  }
}

```

</details> 

If the crash is reproducible, Can you please provide your `flutter doctor -v` and `flutter run --verbose`  and provide steps to reproduce the crash and device details 
Thank you

**Comment by willladislaw** [comment] 2020-09-01 10:35
Yea! it crashed (on first attempt).  

```
2020-09-01 11:34:19.254680+0100 Runner[976:193977] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFString substringWithRange:]: Range {5, 9223372036854775802} out of bounds; string length 0'
*** First throw call stack:
(0x1b9895344 0x1b95aacc0 0x1b98ee550 0x1b98ee650 0x1b9773c0c 0x1bd87ace8 0x1bd7e4ab0 0x1bd7d89c0 0x1bd7d7d58 0x1bd7d7c10 0x1bd800188 0x1bd7feaf0 0x1bd7ff17c 0x1bd7ff66c 0x1bd7d7b1c 0x1bd7daddc 0x1bd7bfbf0 0x1bd497fa0 0x1bd4977b8 0x1bd9ec37c 0x1bd9ec470 0x1bde77058 0x1bde77564 0x1bde773ac 0x1054043e0 0x105403c14 0x105403988 0x105c497fc 0x1054164dc 0x1056ebd58 0x10541fb18 0x105421f8c 0x1b98113a8 0x1b98110c0 0x1b9810740 0x1b980b538 0x1b980abc8 0x1c3bec5cc 0x1bd9bd744 0x104bc13e0 0x1b9687384)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) 
```

**Comment by TahaTesser** [comment] 2020-09-02 07:29
Hi @willladislaw 
I can reproduce the issue, this is fixed by https://github.com/flutter/flutter/issues/64628 and it will land on l master  channel **soon**
Closing as fixed. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2020-09-02 07:29 UTC
Labels: in triage
