### ISSUE TITLE
getSelectedText on inactive InputConnection & getTextAfterCursor on inactive InputConnection problem when typing

### ISSUE THREAD

**Issue by Abhijithsp** [flutter/flutter#57807] opened 2020-05-22 13:15 UTC
I have this weird problem,When i try to enter value to textfield the keyboard comes up when i try to type the the keyboard goes away then i have this warning or error shows 

i am also doing fill up Username,Place,mobile that i fetching from sharedprefrence and it's working,but when i try to enter age,height,weight keyboard comes up & goes with in seconds,this is the error/warning i am getting, i am using Latest flutter version release 1.17
**no problem in flutter doctor**
```
W/IInputConnectionWrapper(23904): getSelectedText on inactive InputConnection
W/IInputConnectionWrapper(23904): getTextAfterCursor on inactive InputConnection
```
The code i wrote 
```
class RegistrationScreenState extends State<RegistrationScreen> {

 TextEditingController mobile = TextEditingController();
  TextEditingController Username = TextEditingController();
  TextEditingController Place = TextEditingController();
  TextEditingController age = TextEditingController();
  TextEditingController height = TextEditingController();
  TextEditingController weight = TextEditingController();

  void initState() {
    getDetails();

  }

  @override
  Widget build(BuildContext context) {
    Size size = MediaQuery
        .of(context)
        .size;
    return Scaffold(
      appBar: AppBar(
        title: Text("Registration", style: TextStyle(color: Colors.black)),
        backgroundColor: Colors.orange,
      ),
      body: SingleChildScrollView(
        child: Stack(
          children: [
            Column(
              children: [
                Container(
                  child: Image.asset('assets/images/gym.png',
                      height: 150,
                      width: double.infinity,
                      fit: BoxFit.fitWidth),
                ),
                SizedBox(
                  height: 50,
                ),
                Row(
                  mainAxisAlignment: MainAxisAlignment.spaceEvenly,
                  children: <Widget>[
                    Expanded(
                      child: Padding(
                        padding: const EdgeInsets.all(8.0),
                        child: TextField(
                          controller: Username,
                          decoration: InputDecoration(
                            prefixIcon: Icon(Icons.perm_identity),
                          ),
                        ),
                      ),
                    ),
                    Expanded(
                      child: Padding(
                        padding: const EdgeInsets.all(8.0),
                        child: TextField(
                          controller: mobile,
                          decoration: InputDecoration(
                            prefixIcon: Icon(Icons.mobile_screen_share),
                          ),
                        ),
                      ),
                    ),
                  ],
                ),
                Padding(
                  padding: const EdgeInsets.all(8.0),
                  child: Align(
                      alignment: Alignment.centerLeft,
                      child: Text(
                        "User Information",
                        style: TextStyle(
                            fontSize: 15, fontWeight: FontWeight.bold),
                      )),
                ),
                Row(
                  mainAxisAlignment: MainAxisAlignment.spaceEvenly,
                  children: <Widget>[
                    Expanded(
                      child: Padding(
                        padding: const EdgeInsets.all(8.0),
                        child: TextField(
                          controller: Place,
                          decoration: InputDecoration(),
                        ),

                      ),
                    ),
                    Expanded(
                      child: Padding(
                        padding: const EdgeInsets.all(8.0),
                        child: TextField(
                          controller: age,
                          keyboardType: TextInputType.number,
                          inputFormatters: [WhitelistingTextInputFormatter.digitsOnly],
                          decoration: InputDecoration(
                            hintText: 'Age',
                          ),
                        ),
                      ),
                    ),
                  ],
                ),
                Row(
                  mainAxisAlignment: MainAxisAlignment.spaceEvenly,
                  children: <Widget>[
                    Expanded(
                      child: Padding(
                        padding: const EdgeInsets.all(8.0),
                        child: TextField(
                          controller: height,
                          keyboardType: TextInputType.number,
                          inputFormatters: [WhitelistingTextInputFormatter.digitsOnly],
                          decoration: InputDecoration(
                            hintText: 'Height(in cm)',
                          ),
                        ),
                      ),
                    ),
                    Expanded(
                      child: Padding(
                        padding: const EdgeInsets.all(8.0),
                        child: TextField(
                          controller: weight,
                          keyboardType: TextInputType.number,
                          inputFormatters: [WhitelistingTextInputFormatter.digitsOnly],
                          decoration: InputDecoration(
                            hintText: 'Weight(in kg)',
                          ),
                        ),
                      ),
                    ),
                  ],
                ),
              ],
            ),
          ],
        ),
      ),
    );
  }


  //  get & fill Shareprefrece data to textfield
  getDetails() async {
    Future user = SharedPrefrence().getUserMobile();
    Future name = SharedPrefrence().getUserName();
    Future place = SharedPrefrence().getUserPlace();

    user.then((data) async {
      var mobile_no = data;
      setState(() {
        if (mobile_no.isNotEmpty) {
          mobile.text = mobile_no;
        }
        else
          {
            mobile.text = "";
          }
      });
    });

    name.then((data) async {
      var user_name = data;
      setState(() {
        if (user_name.isNotEmpty) {
          Username.text = user_name;
        }
      });
    });

    place.then((data) async {
      var user_place = data;
      setState(() {
        if (user_place.isNotEmpty) {
          Place.text = user_place;
        }
      });
    });
  }



}
```

**Comment by TahaTesser** [comment] 2020-05-25 09:05
Hi @Abhijithsp 
can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal runnable code sample to reproduce the problem
Thank you

**Comment by Abhijithsp** [comment] 2020-05-25 10:11
```
[√] Flutter (Channel stable, v1.17.1, on Microsoft Windows [Version 10.0.18363.720], locale en-US)
    • Flutter version 1.17.1 at E:\flutter
    • Framework revision f7a6a7906b (12 days ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\Beegains\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] Connected device (1 available)
    • XT1706 • HKE6E9PB • android-arm • Android 6.0 (API 23)

• No issues found!

```
flutter doctor --verbose

```
[+16672 ms] V/InputMethodManager(14264): START INPUT: io.flutter.embedding.android.FlutterView{e7f23b1 VFE...... .F...... 0,0-720,1184}
ic=io.flutter.plugin.editing.InputConnectionAdaptor@cc014da tba=android.view.inputmethod.EditorInfo@ebf7d0b controlFlags=#0
[ +152 ms] I/SurfaceView(14264): updateWindow -- setFrame, this = io.flutter.embedding.android.FlutterSurfaceView{34d3658 V.E...... ......I. 0,0-720,1184}
[   +1 ms] I/SurfaceView(14264): updateWindow -- OnPreDrawListener, mHaveFrame = true, this = io.flutter.embedding.android.FlutterSurfaceView{34d3658 V.E...... ......I. 0,0-720,1184}
[ +104 ms] I/SurfaceView(14264): updateWindow -- setFrame, this = io.flutter.embedding.android.FlutterSurfaceView{34d3658 V.E...... ......I. 0,0-720,1184}
[   +1 ms] I/SurfaceView(14264): updateWindow -- OnPreDrawListener, mHaveFrame = true, this = io.flutter.embedding.android.FlutterSurfaceView{34d3658 V.E...... ......I. 0,0-720,1184}
[+1409 ms] I/SurfaceView(14264): updateWindow -- setFrame, this = io.flutter.embedding.android.FlutterSurfaceView{34d3658 V.E...... ......I. 0,0-720,1184}
[   +1 ms] I/SurfaceView(14264): updateWindow -- OnPreDrawListener, mHaveFrame = true, this = io.flutter.embedding.android.FlutterSurfaceView{34d3658 V.E...... ......I. 0,0-720,1184}
[+8247 ms] V/InputMethodManager(14264): START INPUT: io.flutter.embedding.android.FlutterView{e7f23b1 VFE...... .F....I. 0,0-720,1184}
ic=io.flutter.plugin.editing.InputConnectionAdaptor@894fe01 tba=android.view.inputmethod.EditorInfo@29aa4a6 controlFlags=#0
[   +2 ms] W/IInputConnectionWrapper(14264): getSelectedText on inactive InputConnection
[  +62 ms] W/IInputConnectionWrapper(14264): getTextAfterCursor on inactive InputConnection
[ +203 ms] I/SurfaceView(14264): updateWindow -- setFrame, this = io.flutter.embedding.android.FlutterSurfaceView{34d3658 V.E...... ......I. 0,0-720,1184}
[   +2 ms] I/SurfaceView(14264): updateWindow -- OnPreDrawListener, mHaveFrame = true, this = io.flutter.embedding.android.FlutterSurfaceView{34d3658 V.E...... ......I. 0,0-720,1184}
[+1252 ms] I/SurfaceView(14264): updateWindow -- setFrame, this = io.flutter.embedding.android.FlutterSurfaceView{34d3658 V.E...... ......I. 0,0-720,1184}
[   +1 ms] I/SurfaceView(14264): updateWindow -- OnPreDrawListener, mHaveFrame = true, this = io.flutter.embedding.android.FlutterSurfaceView{34d3658 V.E...... ......I. 0,0-720,1184}

```

**Comment by TahaTesser** [comment] 2020-05-25 15:39
```
W/IInputConnectionWrapper( 7660): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper( 7660): getSelectedText on inactive InputConnection
W/IInputConnectionWrapper( 7660): getTextAfterCursor on inactive InputConnection
W/IInputConnectionWrapper( 7660): beginBatchEdit on inactive InputConnection
W/IInputConnectionWrapper( 7660): endBatchEdit on inactive InputConnection
```

<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel stable, v1.17.1, on Mac OS X 10.15.4 19E287, locale en-GB)
    • Flutter version 1.17.1 at /Users/tahatesser/Code/flutter_stable
    • Framework revision f7a6a7906b (13 days ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/tahatesser/Code/SDK
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.2

[✓] Connected device (1 available)
    • SM M305F • 32003c30dc19668f • android-arm64 • Android 10 (API 29)

• No issues found!

``` 

</details>

**Comment by Abhijithsp** [comment] 2020-05-26 05:08
In the above code i removed this code from textfield age,height,weight
```
 keyboardType: TextInputType.number,
 inputFormatters: [WhitelistingTextInputFormatter.digitsOnly],
```
Now i have this error/warning shows up along with old error/warning

```
W/IInputConnectionWrapper( 8756): getSelectedText on inactive InputConnection
W/IInputConnectionWrapper( 8756): getTextAfterCursor on inactive InputConnection
W/IInputConnectionWrapper( 8756): beginBatchEdit on inactive InputConnection
W/IInputConnectionWrapper( 8756): endBatchEdit on inactive InputConnection
```
@TahaTesser

**Comment by HansMuller** [comment] 2020-05-26 15:59
This appears to be a duplicate of a long-standing problem: https://github.com/flutter/flutter/issues/9471

**Comment by TahaTesser** [comment] 2020-05-27 11:20
Closing as duplicate of https://github.com/flutter/flutter/issues/9471

**Closed by TahaTesser** 2020-05-27 11:20 UTC
Labels: a: error message, a: text input, f: material design, found in release: 1.17, found in release: 1.19, framework, has reproducible steps
