### ISSUE TITLE
[web] previous route stays visible after using platform view

### ISSUE THREAD

**Issue by deakjahn** [flutter/flutter#60349] opened 2020-06-26 10:51 UTC
This is a different aspect of #59868.

## Steps to Reproduce

1. Use the repro package [canvas_test.zip](https://github.com/flutter/flutter/files/4836454/canvas_test.zip)
2. Run it in Flutter Web using CanvasKit (don't worry about the plugin registry error message),
3. Tap on the button in the corner,
4. Observe the background of the incoming page carefully. Not always, but about half the time, the page background is partly transparent and elements of the previous page are still visible (you can see many screenshots in #59868).

The original issue deals with this partial transparency, this aspect of the problem is about the elements that stay visible and present. Checking the widget tree seems to suggest that the elements of the previous route remain present in both cases, either when the background is translucent (and those elements can be actually seen) and when it's opaque (and thus covers them up).

My hunch is that the problem is somehow linked to using platform views (`HtmlElementView`), I couldn't trigger it in other scenarios.

Here are the relevant console printouts:

* widget hierarchy: [Widget_hierarchy.txt](https://github.com/flutter/flutter/files/4836503/Widget_hierarchy.txt)
* rendering tree: [Rendering tree.txt](https://github.com/flutter/flutter/files/4836504/Rendering.tree.txt)

The button with the **Tap me** label are still present in both, although it belonged to the previous route.

<details>
  <summary>Doc</summary>

```
[√] Flutter (Channel beta, 1.19.0-4.2.pre, on Microsoft Windows [Version 10.0.19041.329], locale en-US)
    • Flutter version 1.19.0-4.2.pre at E:\Android\flutter-beta
    • Framework revision 9b9b543d92 (4 days ago), 2020-06-22 12:19:28 -0700
    • Engine revision 9a28c3bcf4
    • Dart version 2.9.0 (build 2.9.0-14.1.beta)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at e:\Android\Sdk
    • Platform android-29, build-tools 30.0.0
    • ANDROID_HOME = e:\Android\Sdk
    • ANDROID_SDK_ROOT = e:\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • CHROME_EXECUTABLE = e:\Android\chrome.bat

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (2 available)
    • Web Server • web-server • web-javascript • Flutter Tools
    • Chrome     • chrome     • web-javascript • Google Chrome 83.0.4103.116

• No issues found!
```

</details>

**Comment by yjbanov** [comment] 2020-06-26 16:49
Removed the canvaskit and web labels because this seems to be general framework behavior.

@goderbauer can you please triage this?

**Comment by goderbauer** [comment] 2020-06-29 20:36
I don't fully understand what the problem is here. Are you referring to the fact that even after clicking the "tap me" button that button and its route still show up in the render and widget tree? That is expected behavior. By default, the routes have "maintainState" [1] set to true. This will cause the route objects to stay alive even when they are currently not visible. As you can see in the render tree printout attached to your bug, the route in question is actually marked as an "offstage" child of the `_RenderTheatre`. This means, the child is not getting rendered, but the objects are kept around to maintain state. If you don't want this, you can set "maintainState" to false, but then you will also loose all state of the route.

[1] https://master-api.flutter.dev/flutter/widgets/ModalRoute/maintainState.html

I am closing this for now since with the information given this appears to be working as expected. Let me know if there's anything I missed.

**Closed by goderbauer** 2020-06-29 20:36 UTC
Labels: assigned for triage, found in release: 1.19, framework, has reproducible steps

**Comment by deakjahn** [comment] 2020-06-29 20:54
@goderbauer The first problem I don't really understand is that even if they are remembered and part of the widget tree, why are they actually visible? @yjbanov Yegor is currently working on the other aspect: if the second page background is rendered partly transparent (by error), the *Tap me* will actually be still visible. And what if I have and intentionally transparent page background? That button should be retained, as you say, but certainly not remaining visible? Not being rendered?

The second problem is one that I can't really put my finger on. I have a feeling in my code (which is, of course, much more complex than a simple repro) that parts of the first page (actually the JS code I bring in to support my `HtmlElementView`) remain active and clash with the second route. If, as I suspected above, they *are* actually rendered, not just retained off stage, that might explain it. But I have to work on that second if I can find something to reproduce.

But until then, could Yegor chime in and say if he found anything about the elements of the previous route actually remaining *and rendered*?

**Comment by deakjahn** [comment] 2020-07-10 16:07
@goderbauer This is the workaround I currently use. And using this workaround clearly shows that the *is* a problem:)

The State has a boolean:

    bool showPlatformView = true;

This boolean is used to show the platform view initially:

    body: Stack(
      children: [
        if (showPlatformView) TestView(),
        FlatButton(
          child: Text('Tap me'),
          onPressed: () {
            setState(() => showPlatformView = false);
            WidgetsBinding.instance.addPostFrameCallback((_) {
              Navigator.push<String>(context, MaterialPageRoute(builder: (context) => TestPage()));
            });
          },
        ),
      ],
    ),

Before we actually go on to the next page, we remove the platform view and make sure we change the route only on the next frame. The previous route will really go away then, neither visible nor actually rendered but covered up.
