### ISSUE TITLE
[google_maps_web] Failed to update marker position

### ISSUE THREAD

**Issue by wkhaksar** [flutter/flutter#85646] opened 2021-06-30 20:20 UTC
Added marker to the map's initial position, then updated the set of markers and polylines through `setState`, for the web, polylines are updated but fails to update the marker position. 

It is working with android and iOS with same code.

plugin version: `google_maps_flutter_web: ^0.3.0+2`

### The picture for web is:
![Screenshot 2021-06-30 at 21 56 40](https://user-images.githubusercontent.com/31837615/124025711-148c0b00-d9f1-11eb-8a7c-ebd7e7293359.png)

### Here is the code

<details> 
<summary>minimal code sample</summary> 

```dart
import 'dart:async';
import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

class MarkerMap extends StatefulWidget {
  @override
  _MarkerMapState createState() => _MarkerMapState();
}

class _MarkerMapState extends State<MarkerMap> {
  bool isMapVisible = true;
  Completer<GoogleMapController> _gMapcontroller = Completer();
  var _initialPosition = LatLng(51.253548, 6.770777);

  Map<PolylineId, Polyline> _polylines = {};
  List<LatLng> _polyLineCoordinates = [];
  Set<Marker> _markers = Set<Marker>();

  @override
  void initState() {
    _markers.add(
      Marker(
          markerId: MarkerId("marker"),
          icon: BitmapDescriptor.defaultMarker,
          position: _initialPosition),
    );
    super.initState();
  }

  _addPolyLine(LatLng _newLatLng) {
    _polyLineCoordinates.add(_newLatLng);
    PolylineId id = PolylineId("poly");
    Polyline polyline = Polyline(
      polylineId: id,
      color: Colors.red,
      points: _polyLineCoordinates,
      width: 3,
    );
    _polylines[id] = polyline;
  }

  _addMarker(LatLng _newLatLng) {
    _markers.clear();
    _markers.add(
      Marker(
          markerId: MarkerId("marker"),
          icon: BitmapDescriptor.defaultMarker,
          position: _newLatLng),
    );
  }

  _updateMarkerAndPolyline(LatLng _newLatLng) {
    //This polyline is being added
    _addPolyLine(_newLatLng);

    //This addMarker is calling but not updating marker in Google maps
    _addMarker(_newLatLng);

    setState(() {});
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(centerTitle: true, title: Text("Markers")),
      body: Stack(
        children: [
          GoogleMap(
            initialCameraPosition:
                CameraPosition(target: _initialPosition, zoom: 17),
            onMapCreated: (ctrl) async {
              _gMapcontroller.complete(ctrl);

              final GoogleMapController _controller =
                  await _gMapcontroller.future;

              var _newLatLngList = [
                LatLng(51.254629, 6.767097),
                LatLng(51.251798, 6.762231),
                LatLng(51.254862, 6.759198)
              ];

              for (int i = 0; i < 3; i++) {
                var _newReportedPosition = _newLatLngList[i];

                _controller.animateCamera(CameraUpdate.newCameraPosition(
                    CameraPosition(target: _newReportedPosition, zoom: 17)));

                _updateMarkerAndPolyline(_newReportedPosition);
              }
            },
            polylines: Set<Polyline>.of(_polylines.values),
            markers: _markers,
            myLocationEnabled: true,
            mapToolbarEnabled: false,
          ),
        ],
      ),
    );
  }
}
``` 

</details>

**Comment by TahaTesser** [comment] 2021-07-01 12:41
Hi @wkhaksar 
I see there's an open issue addressing the case you described.
Please follow up on that issue, Closing as duplicate of https://github.com/flutter/flutter/issues/83467
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-07-01 12:41 UTC
Labels: in triage
