### ISSUE TITLE
http.post sending no Content-Length

### ISSUE THREAD

**Issue by deakjahn** [flutter/flutter#59104] opened 2020-06-09 21:52 UTC
## Steps to Reproduce

The following code:

    final response = await http.post(url,
      headers: {
        'Content-Type': 'application/octet-stream',
        'Content-Length': (await fileSize(file)).toString(),
      },
      body: await fileRead(file));

(URL actually being the Google Cloud like `https://www.googleapis.com/upload/storage/...` returns the following error on Android:

    411 Length Required

`fileSize()` reads the file size, `fileRead()` returns the content as an `Uint8List`. They both work all right. Actually, if I use the lower level approach with these calls:

    final http = HttpClient();
    final request = await http.postUrl(Uri.parse(url));
    request.headers.set('Content-Type', 'application/octet-stream');
    request.headers.set('Content-Length', await fileSize(file));
    request.add(await fileRead(file));
    final response = await request.close();
    http.close();

it works.

<details>
  <summary>Doc</summary>

```
[√] Flutter (Channel beta, 1.18.0-11.1.pre, on Microsoft Windows [Version 10.0.18363.836], locale en-US)
    • Flutter version 1.18.0-11.1.pre at E:\Android\flutter-beta
    • Framework revision 2738a1148b (4 weeks ago), 2020-05-13 15:24:36 -0700
    • Engine revision ef9215ceb2
    • Dart version 2.9.0 (build 2.9.0-8.2.beta)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at e:\Android\Sdk
    • Platform android-29, build-tools 29.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • CHROME_EXECUTABLE = e:\Android\chrome.bat

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (2 available)
    • Web Server • web-server • web-javascript • Flutter Tools
    • Chrome     • chrome     • web-javascript • Google Chrome 83.0.4103.97

• No issues found!
```
</details>

**Comment by iapicca** [comment] 2020-06-10 08:43
Hi @deakjahn 
From what I can see, the issue is related to dart package [http](https://pub.dev/packages/http) rather than to Flutter itself. 

Please open the issue in the dedicated [repository](https://github.com/dart-lang/http/issues).
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments, possibly providing a minimal reproducible code sample that does not use 3rd party plugins, and I will reopen it.
Thank you

**Closed by iapicca** 2020-06-10 08:43 UTC
