### ISSUE TITLE
[two_dimensional_scrollables] change the width of columns without rebuilding the cells.

### ISSUE THREAD

**Issue by leavky** [flutter/flutter#145050] opened 2024-03-13 02:23 UTC
### Use case

Can you provide a controller that allows me to change the width of columns without rebuilding the cells, but triggers a manual refresh of the cell layout?
I want to implement this feature
![recording](https://github.com/flutter/flutter/assets/46547390/dc81503a-0f49-4d93-9a71-c03ffff852a2)

### Proposal

I want to implement this feature
![recording](https://github.com/flutter/flutter/assets/46547390/dc81503a-0f49-4d93-9a71-c03ffff852a2)

**Comment by huycozy** [comment] 2024-03-13 09:16
This doesn't sound like a feature request, but it could be an implementation or package issue. Could you please share a minimal sample code for this?

**Comment by leavky** [comment] 2024-03-13 11:17
```dart
// Copyright 2013 The Flutter Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

import 'package:flutter/material.dart';
import 'package:two_dimensional_scrollables/two_dimensional_scrollables.dart';

void main() {
  runApp(const TableExampleApp());
}

/// A sample application that utilizes the TableView API.
class TableExampleApp extends StatelessWidget {
  /// Creates an instance of the TableView example app.
  const TableExampleApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Table Example',
      theme: ThemeData(
        useMaterial3: true,
      ),
      home: const TableExample(),
    );
  }
}

/// The class containing the TableView for the sample application.
class TableExample extends StatefulWidget {
  /// Creates a screen that demonstrates the TableView widget.
  const TableExample({super.key});

  @override
  State<TableExample> createState() => _TableExampleState();
}

class _TableExampleState extends State<TableExample> {
  late final ScrollController _verticalController = ScrollController();
  int _rowCount = 20;

  double threeColumnWidth = 50.0;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Table Example'),
      ),
      body: Padding(
        padding: const EdgeInsets.symmetric(horizontal: 50),
        child: TableView.builder(
          verticalDetails: ScrollableDetails.vertical(controller: _verticalController),
          cellBuilder: _buildCell,
          columnCount: 20,
          columnBuilder: _buildColumnSpan,
          rowCount: _rowCount,
          rowBuilder: _buildRowSpan,
        ),
      ),
      persistentFooterButtons: <Widget>[
        Slider(
          value: threeColumnWidth,
          max: 500,
          onChanged: (newValue) {
            // change three column width
            // need a controller to change column width and don't rebuild cells
            setState(() {
              threeColumnWidth = newValue;
            });
          },
        ),
      ],
    );
  }

  TableViewCell _buildCell(BuildContext context, TableVicinity vicinity) {
    return TableViewCell(
      child: RepaintBoundary(
        child: TableCell(vicinity: vicinity),
      ),
    );
  }

  TableSpan _buildColumnSpan(int index) {
    const TableSpanDecoration decoration = TableSpanDecoration(
      border: TableSpanBorder(
        trailing: BorderSide(),
      ),
    );

    if (index == 3) {
      return TableSpan(
        foregroundDecoration: decoration,
        extent: FixedTableSpanExtent(threeColumnWidth),
        onEnter: (_) => print('Entered column $index'),
      );
    }

    return TableSpan(
      foregroundDecoration: decoration,
      extent: const FixedTableSpanExtent(100),
      onEnter: (_) => print('Entered column $index'),
    );
  }

  TableSpan _buildRowSpan(int index) {
    final TableSpanDecoration decoration = TableSpanDecoration(
      color: index.isEven ? Colors.purple[100] : null,
      border: const TableSpanBorder(
        trailing: BorderSide(
          width: 3,
        ),
      ),
    );

    return TableSpan(
      backgroundDecoration: decoration,
      extent: const FixedTableSpanExtent(65),
      cursor: SystemMouseCursors.click,
    );
  }
}

class TableCell extends StatefulWidget {
  const TableCell({super.key, required this.vicinity});

  final TableVicinity vicinity;

  @override
  State<TableCell> createState() => _TableCellState();
}

class _TableCellState extends State<TableCell> {
  @override
  Widget build(BuildContext context) {
    print("build ${widget.vicinity}");
    return Center(
      child: Text('Tile c: ${widget.vicinity.column}, r: ${widget.vicinity.row}'),
    );
  }

  @override
  void didUpdateWidget(covariant TableCell oldWidget) {
    // TODO: implement didUpdateWidget
    super.didUpdateWidget(oldWidget);
    return;
  }

  @override
  void dispose() {
    // TODO: implement dispose
    super.dispose();
  }
}
```
![recording](https://github.com/flutter/flutter/assets/46547390/7b74cf48-5c7c-4b17-90da-8cbdfce5b87d)

**Comment by leavky** [comment] 2024-03-13 11:30
I want change column width and don't rebuild cells

**Comment by huycozy** [comment] 2024-03-14 05:19
I think this is working as intended since you refreshed whole `TableView` with `setState` call on Slider value changes; then cell widget will be refreshed as well. I'm not sure if there is a way to prevent cells from rebuilding. 

More specifically, could you share what the use case this request needs? (to optimize performance or to implement something else?)

**Comment by leavky** [comment] 2024-03-14 15:25
I need to to optimize performance, because when cell is other's widget like checkbox, image，when change column with real time, it gets really stuck.

when the table like this.

![image](https://github.com/flutter/flutter/assets/46547390/4b71bb43-4686-48bb-a792-ecdbb1be5b65)

I think when change the column width(or row height), don't rebuild cells.

I dont know how to change column width(or row height) and not need refreshed `TableView`, please let me know if there is such a method. If there have a controller relayout cells, will improve performance. Also, can rewrite the  layoutChildSequence function, animation effects can be achieved.

**Comment by huycozy** [comment] 2024-03-15 05:40
Thanks for the update. Marking this as a feature request with the use case above.

**Comment by Piinks** [comment] 2024-03-21 17:29
Hi @leavky, I am not sure I understand the request to resize without rebuilding, wouldn't the cells need to be rebuilt to reflect the new dimensions?

**Comment by leavky** [comment] 2024-03-23 06:24
@Piinks ,when change the target's column width, not need rebuild other column's cell. when change column with real time, it gets really stuck. when change the target's column width, other column's cell just relayout, not need to rebuild.

**Comment by leavky** [comment] 2024-03-23 06:31
just like this, 
![recording](https://github.com/flutter/flutter/assets/46547390/acdb283b-ba98-46e6-b7fa-53f03bb15394)

**Comment by leavky** [comment] 2024-03-23 09:37
I have another question, i want eidt cell, but the cell's space is small, so i need a bigger cell to edit cell content. like this
![image](https://github.com/flutter/flutter/assets/46547390/0982d44b-e803-483d-8a04-153ed03ba986)

But i found the child's drawing order is fixed, is there have a method that let target cell paint later. thanks!

I want `1-1`  on the top of `1-2`,
![image](https://github.com/flutter/flutter/assets/46547390/283e37a2-0447-49c2-afa3-06c9dde6616d)

**Comment by tomasweigenast** [comment] 2024-03-23 19:41
> just like this, ![recording](https://private-user-images.githubusercontent.com/46547390/316222416-acdb283b-ba98-46e6-b7fa-53f03bb15394.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEyMjI3OTYsIm5iZiI6MTcxMTIyMjQ5NiwicGF0aCI6Ii80NjU0NzM5MC8zMTYyMjI0MTYtYWNkYjI4M2ItYmE5OC00NmU2LWI3ZmEtNTNmMDNiYjE1Mzk0LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIzVDE5MzQ1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIwMTE3ZjgxNDgyMDZlNTUyOGZjMWFkM2M0MmFlZWEwZDcxZWEzZjFiNzJhOGM1NmVhYWE1ZTQ5YjY1NDU5MDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ztfqINjk0Z6HdrYNFWQ99zNhEg6IqVZkBJkqjXVNPkw) [ ![recording](https://private-user-images.githubusercontent.com/46547390/316222416-acdb283b-ba98-46e6-b7fa-53f03bb15394.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEyMjI3OTYsIm5iZiI6MTcxMTIyMjQ5NiwicGF0aCI6Ii80NjU0NzM5MC8zMTYyMjI0MTYtYWNkYjI4M2ItYmE5OC00NmU2LWI3ZmEtNTNmMDNiYjE1Mzk0LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIzVDE5MzQ1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIwMTE3ZjgxNDgyMDZlNTUyOGZjMWFkM2M0MmFlZWEwZDcxZWEzZjFiNzJhOGM1NmVhYWE1ZTQ5YjY1NDU5MDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ztfqINjk0Z6HdrYNFWQ99zNhEg6IqVZkBJkqjXVNPkw) ](https://private-user-images.githubusercontent.com/46547390/316222416-acdb283b-ba98-46e6-b7fa-53f03bb15394.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEyMjI3OTYsIm5iZiI6MTcxMTIyMjQ5NiwicGF0aCI6Ii80NjU0NzM5MC8zMTYyMjI0MTYtYWNkYjI4M2ItYmE5OC00NmU2LWI3ZmEtNTNmMDNiYjE1Mzk0LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIzVDE5MzQ1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIwMTE3ZjgxNDgyMDZlNTUyOGZjMWFkM2M0MmFlZWEwZDcxZWEzZjFiNzJhOGM1NmVhYWE1ZTQ5YjY1NDU5MDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ztfqINjk0Z6HdrYNFWQ99zNhEg6IqVZkBJkqjXVNPkw) [ ](https://private-user-images.githubusercontent.com/46547390/316222416-acdb283b-ba98-46e6-b7fa-53f03bb15394.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEyMjI3OTYsIm5iZiI6MTcxMTIyMjQ5NiwicGF0aCI6Ii80NjU0NzM5MC8zMTYyMjI0MTYtYWNkYjI4M2ItYmE5OC00NmU2LWI3ZmEtNTNmMDNiYjE1Mzk0LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIzVDE5MzQ1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIwMTE3ZjgxNDgyMDZlNTUyOGZjMWFkM2M0MmFlZWEwZDcxZWEzZjFiNzJhOGM1NmVhYWE1ZTQ5YjY1NDU5MDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ztfqINjk0Z6HdrYNFWQ99zNhEg6IqVZkBJkqjXVNPkw)

It seems that needs to be rebuilt too in the example you show because the text is getting shorter and needs to show an overflow effect. 

As @Piinks says here:

> Hi @leavky, I am not sure I understand the request to resize without rebuilding, wouldn't the cells need to be rebuilt to reflect the new dimensions?

The cells needs to be rebuilt due to this code:
```dart
final BoxConstraints cellConstraints = BoxConstraints.tightFor(
    width: mergedColumnWidth ?? standardColumnWidth,
    height: mergedRowHeight ?? standardRowHeight,
 );
cell.layout(cellConstraints); // this line
```

You can find this in the `table.dart` line 754 (at the moment of writing this). As you can see, the cell constraints are calculated keeping in mind the column width and then the cell is layout.

**Comment by tomasweigenast** [comment] 2024-03-25 17:41
> @tomasweigenast ，I tried it and it was the right way, thanks you. And the cell paint order can override in paint.

What did you do? Did you try using riverpod?

**Comment by Piinks** [comment] 2024-03-26 23:26
@leavky it sounds like your issue may have been resolved? Can we close this then?

**Comment by leavky** [comment] 2024-03-27 01:19
> > @tomasweigenast ，I tried it and it was the right way, thanks you. And the cell paint order can override in paint.
> 
> What did you do? Did you try using riverpod?

yes, i use riverpod.
```dart
    return TableViewCell(
      child: ProviderScope(
        overrides: [
          tableVicinityIndexProvider.overrideWithValue((vicinity.xIndex, vicinity.yIndex)),
        ],
        child: const TableCell(),
      ),
    );
```

**Comment by leavky** [comment] 2024-03-27 01:20
> @leavky it sounds like your issue may have been resolved? Can we close this then?

yes, thank you.

**Closed** 2024-03-27 01:20 UTC
Labels: c: new feature, framework, c: performance, f: scrolling, package, team-framework, p: two_dimensional_scrollables
