### ISSUE TITLE
[web] Flutter Web throws an error when using (shaderMask) widget

### ISSUE THREAD

**Issue by inc16sec** [flutter/flutter#61586] opened 2020-07-16 00:52 UTC
## Steps to Reproduce

1. Using a ShaderMask widget.
```dart
Padding(
      padding: const EdgeInsets.only(left: 16.0, right: 16),
      child: ShaderMask(
        shaderCallback: (bounds) {
          return gradient.createShader(Offset.zero & bounds.size);
        },
        child: Text(
          "EXPLORE ",
          style: TextStyle(fontSize: 8, fontWeight: FontWeight.bold),
        ),
      ),
    );
```
2. Start app in Chrome using ```flutter run -d chrome```
3. I'm using ```shaderMask```  in two pages in my Flutter app and they both throw an error and once i delete the ```shaderMask widget``` the pages load with no problem.

**Expected results:** 
I'm using the ShaderMask to create a gradient Text so I'm expecting the text to have a gradient of two colors instead of just one (Note that the Gradient Text works fine on both IOS and Android the issue only shows up when I run the app on chrome [WEB]).

<details>
  <summary>Logs</summary>

```══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
The following UnimplementedError was thrown during a scheduler callback:
UnimplementedError
When the exception was thrown, this was the stack:
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 214:49  throw_
lib/_engine/engine/surface/scene_builder.dart 234:5                           pushShaderMask
packages/flutter/src/rendering/layer.dart 1824:26                             addToScene
packages/flutter/src/rendering/layer.dart 444:5                               [_addToSceneWithRetainedRendering]
packages/flutter/src/rendering/layer.dart 1034:14                             addChildrenToScene
packages/flutter/src/rendering/layer.dart 1871:5                              addToScene
packages/flutter/src/rendering/layer.dart 444:5                               [_addToSceneWithRetainedRendering]
packages/flutter/src/rendering/layer.dart 1034:14                             addChildrenToScene
packages/flutter/src/rendering/layer.dart 1387:5                              addToScene
packages/flutter/src/rendering/layer.dart 444:5                               [_addToSceneWithRetainedRendering]
packages/flutter/src/rendering/layer.dart 1034:14                             addChildrenToScene
packages/flutter/src/rendering/layer.dart 2012:5                              addToScene
packages/flutter/src/rendering/layer.dart 444:5                               [_addToSceneWithRetainedRendering]
packages/flutter/src/rendering/layer.dart 1034:14                             addChildrenToScene
packages/flutter/src/rendering/layer.dart 1172:5                              addToScene
packages/flutter/src/rendering/layer.dart 444:5                               [_addToSceneWithRetainedRendering]
packages/flutter/src/rendering/layer.dart 1034:14                             addChildrenToScene
packages/flutter/src/rendering/layer.dart 1172:5                              addToScene
packages/flutter/src/rendering/layer.dart 444:5                               [_addToSceneWithRetainedRendering]
packages/flutter/src/rendering/layer.dart 1034:14                             addChildrenToScene
packages/flutter/src/rendering/layer.dart 1620:5                              addToScene
packages/flutter/src/rendering/layer.dart 771:5                               buildScene
packages/flutter/src/rendering/view.dart 241:36                               compositeFrame
packages/flutter/src/rendering/binding.dart 408:18                            drawFrame
packages/flutter/src/widgets/binding.dart 867:13                              drawFrame
packages/flutter/src/rendering/binding.dart 286:5                             [_handlePersistentFrameCallback]
packages/flutter/src/scheduler/binding.dart 1117:15                           [_invokeFrameCallback]
packages/flutter/src/scheduler/binding.dart 1056:9                            handleDrawFrame
packages/flutter/src/scheduler/binding.dart 865:7                             <fn>
dart-sdk/lib/_internal/js_dev_runtime/private/isolate_helper.dart 48:19       internalCallback
════════════════════════════════════════════════════════════════════════════════════════════════════

[38;5;248m════════ Exception caught by scheduler library ═════════════════════════════════[39;49m
[38;5;244mThe following UnimplementedError was thrown during a scheduler callback:[39;49m
UnimplementedError

[38;5;244mWhen the exception was thrown, this was the stack[39;49m
[38;5;244mdart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 214:49  throw_[39;49m
[38;5;244mlib/_engine/engine/surface/scene_builder.dart 234:5                           pushShaderMask[39;49m
[38;5;244mpackages/flutter/src/rendering/layer.dart 1824:26                             addToScene[39;49m
[38;5;244mpackages/flutter/src/rendering/layer.dart 444:5                               [_addToSceneWithRetainedRendering][39;49m
[38;5;244mpackages/flutter/src/rendering/layer.dart 1034:14                             addChildrenToScene[39;49m
[38;5;244m...[39;49m
[38;5;248m════════════════════════════════════════════════════════════════════════════════[39;49m
Another exception was thrown: UnimplementedError

[38;5;248m════════ Exception caught by scheduler library ═════════════════════════════════[39;49m
UnimplementedError
[38;5;248m════════════════════════════════════════════════════════════════════════════════[39;49m
Another exception was thrown: UnimplementedError

[38;5;248m════════ Exception caught by scheduler library ═════════════════════════════════[39;49m
UnimplementedError
[38;5;248m════════════════════════════════════════════════════════════════════════════════[39;49m
Another exception was thrown: UnimplementedError

[38;5;248m════════ Exception caught by scheduler library ═════════════════════════════════[39;49m
UnimplementedError
[38;5;248m════════════════════════════════════════════════════════════════════════════════[39;49m
Another exception was thrown: UnimplementedError

[38;5;248m════════ Exception caught by scheduler library ═════════════════════════════════[39;49m
UnimplementedError
[38;5;248m════════════════════════════════════════════════════════════════════════════════[39;49m```

```[✓] Flutter (Channel dev, 1.20.0-7.1.pre, on Mac OS X 10.15.5 19F101, locale en-ES)
    • Flutter version 1.20.0-7.1.pre at /Users/y.naddam/documents/flutter
    • Framework revision 7736f3bc90 (5 days ago), 2020-07-10 16:33:05 -0700
    • Engine revision d48085141c
    • Dart version 2.9.0 (build 2.9.0-21.2.beta)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/y.naddam/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.8.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 40.2.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.1

[✓] Connected device (2 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 83.0.4103.116

• No issues found!```

**Comment by jonahwilliams** [comment] 2020-07-16 00:53
duplicate of https://github.com/flutter/flutter/issues/44152

**Closed by jonahwilliams** 2020-07-16 00:53 UTC
