### ISSUE TITLE
Why Sed Command isn't working with Double Quotation marks in script?

### ISSUE THREAD

**Issue by iamSahdeep** [flutter/flutter#15927] opened 2018-03-25 17:11 UTC
## Steps to Reproduce

I am new to flutter, was just trying to install it on my machine(ubuntu 17.10 , 64-bit). After setting PATH variable as mentioned [here](https://flutter.io/setup-linux/#clone-the-repo), I tried to run command " flutter doctor". And got an error 
```
line 33 : sed : command not found
```

I opened that shell script [here](https://github.com/flutter/flutter/blob/2171fcb882a63e8ea2408dec4771ce0611621739/bin/flutter#L33) , found that this `'s,^/+,/,'` to be written in Double quotation marks. And changed it to Single Quotation Marks. And everything Works Fine.

## My Questions

1. Will Changing Quotation marks make any difference? (I know nothing about shell scripting and I think answer would be not as it works correctly )

2. And if there is no variable there why are we using double quotes as it makes trouble to some of us, maybe. (As mentioned [here)](https://stackoverflow.com/a/6697845/7910735)

3. If we are going to change it to Single Quotaion marks, Can I create PR for it?

## Flutter Doctor

Everything works fine after changes.

**Comment by defizeha** [comment] 2018-12-13 02:47
i am a new to flutter too. i have same issue, and i have to changed it to single quotation mark. But, afterthat i have new issue
![screenshot from 2018-12-13 09-44-43](https://user-images.githubusercontent.com/45836055/49912210-fa828f80-febb-11e8-8457-48208c25c319.png)
any solution?

**Comment by zoechi** [comment] 2018-12-13 08:16
@defizeha that doesn't look related.
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by jonahwilliams** [comment] 2020-02-15 20:33
Duplicate of https://github.com/flutter/flutter/issues/15775

**Closed by jonahwilliams** 2020-02-15 20:33 UTC
Labels: t: flutter doctor, tool
