### ISSUE TITLE
TextField cursor stands in a wrong position while using persian words

### ISSUE THREAD

**Issue by mhbdev** [flutter/flutter#120604] opened 2023-02-13 15:59 UTC
That is really annoying. TextField(s) are ruining all my days and nights. This is not the first issue I am encountering since I'm using flutter but I hope this would be the last.

Steps to reproduce this problem are so easy. create a flutter application. make sure you are using flutter 3.7.3 (the latest version on stable channel). use a simple TextField widget. Type a simple word in persian (or Arabic) with no space in the end. (e.g. سلام در حال تست). After typing that, click on the last character. The thing is cursor is not in the right position which you can see in the picture I am sharing.

![image](https://user-images.githubusercontent.com/53684884/218506877-cd51d4b6-00fe-44ff-8611-3ca2fff61de5.png)

**Comment by moffatman** [comment] 2023-02-13 18:29
Can you try out the master channel and see if it's fixed there? I've made an improvement for clicking on the last character in right-to-left text.

**Comment by darshankawar** [comment] 2023-02-14 08:00
@mhbdev 
`flutter channel master`
`flutter upgrade` and try to run your scenario again.

**Comment by mhbdev** [comment] 2023-02-14 20:28
@darshankawar @moffatman 
I tried master channel and the problem still exists.

**Comment by moffatman** [comment] 2023-02-14 20:31
@mhbdev What's the exact revision (`flutter doctor -v`)?

**Comment by mhbdev** [comment] 2023-02-15 00:09
Here you are @moffatman 

[√] Flutter (Channel master, 3.8.0-12.0.pre.52, on Microsoft Windows [Version 10.0.19045.2486], locale en-US)
    • Flutter version 3.8.0-12.0.pre.52 on channel master at C:\FlutterSdk\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 17b4c70ff5 (14 hours ago), 2023-02-14 10:07:02 +0000
    • Engine revision cbb7fc020b
    • Dart version 3.0.0 (build 3.0.0-233.0.dev)
    • DevTools version 2.21.1
    • Pub download mirror https://pub.flutter-io.cn

**Comment by moffatman** [comment] 2023-02-15 03:31
What operating system do you see the problem on? I tried with the string you posted "سلام در حال تست", and it looks correct for me on iOS using latest master channel.

**Comment by mhbdev** [comment] 2023-02-15 11:48
> What operating system do you see the problem on? I tried with the string you posted "سلام در حال تست", and it looks correct for me on iOS using latest master channel.

I am on Windows tried this example on chrome web.

**Comment by moffatman** [comment] 2023-02-15 13:55
Ah, on Web, I think we need to wait for a new CanvasKit to release to include the fix. 

Do you know the next expected release? @jason-simmons

**Comment by darshankawar** [comment] 2023-02-16 06:00
I was able to verify and replicate the reported behavior. This occurs on web using canvaskit renderer on latest master and stable versions:


https://user-images.githubusercontent.com/67046386/219281065-b7d52fa6-48ff-4e49-afba-40cafdcd5962.mov


With html renderer, the cursor goes properly to the position:

<img width="327" alt="Screenshot 2023-02-16 at 11 25 37 AM" src="https://user-images.githubusercontent.com/67046386/219281131-0db53ff7-bfa6-4d44-9c33-0da840be783f.png">

This only seems to be happening on web platform, as on desktop, it works as expected.

A similar / related issue: https://github.com/flutter/flutter/issues/81013

```
void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(home: Scaffold
      (body: Center(child: TextFormField(
      textDirection: TextDirection.rtl,
      //  maxLines: 10,
    ))));
  }
}
```

<details>
<summary> stable, master flutter doctor -v </summary>

```
[!] Flutter (Channel stable, 3.7.3, on macOS 12.2.1 21D62 darwin-x64, locale
    en-GB)
    • Flutter version 3.7.3 on channel stable at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9944297138 (4 days ago), 2023-02-08 15:46:04 -0800
    • Engine revision 248290d6d5
    • Dart version 2.19.2
    • DevTools version 2.20.1
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

[!] Flutter (Channel master, 3.8.0-13.0.pre.52, on macOS 12.2.1 21D62
    darwin-x64, locale en-GB)
    • Flutter version 3.8.0-13.0.pre.52 on channel master at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cc473e4f19 (73 minutes ago), 2023-02-15 22:51:19 -0500
    • Engine revision 3fc40ca5be
    • Dart version 3.0.0 (build 3.0.0-241.0.dev)
    • DevTools version 2.21.1
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.
      
[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.



```

</details>

**Comment by mdebbar** [comment] 2023-02-16 19:22
Is this the same issue as this: https://github.com/flutter/flutter/issues/78550 ?
cc @hterkelsen who fixed the original issue. Is it possible that we have regressed?

**Comment by hoomanmmd** [comment] 2023-03-04 17:26
It also happens in Android

**Comment by abdullahqasemi** [comment] 2023-03-16 14:07
file:///home/master/Documents/Screen_Recording_20230316_183235.mp4
I am also facing the same issue on android.
This is my `flutter doctor -v` output.

`[✓] Flutter (Channel stable, 3.7.7, on Ubuntu 22.04.2 LTS 5.19.0-35-generic,
    locale en_US.UTF-8)
    • Flutter version 3.7.7 on channel stable at
      /home/master/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2ad6cd72c0 (8 days ago), 2023-03-08 09:41:59 -0800
    • Engine revision 1837b5be5f
    • Dart version 2.19.4
    • DevTools version 2.20.1

Checking Android licenses is taking an unexpectedly long time...[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /home/master/Android/Sdk
    • Platform android-33, build-tools 33.0.1
    • ANDROID_HOME = /home/master/Android/Sdk
    • ANDROID_SDK_ROOT = /home/master/Android/Sdk
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 2021.3)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 72.0.1
    • Dart plugin version 213.7433
    • Java version OpenJDK Runtime Environment (build
      11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.76.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.60.0

[✓] Connected device (3 available)
    • SM A525F (mobile) • RZ8T20T03PT • android-arm64  • Android 13 (API 33)
    • Linux (desktop)   • linux       • linux-x64      • Ubuntu 22.04.2 LTS
      5.19.0-35-generic
    • Chrome (web)      • chrome      • web-javascript • Google Chrome
      111.0.5563.64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
`

**Comment by mhbdev** [comment] 2023-03-25 15:44
> 

I am facing this issue on both platforms. Android and Web.

**Comment by ammarqusailah** [comment] 2023-04-15 23:48
ChatGPT give me this solution and It worked for me

```
controller.addListener(() {
      if (controller != null) {
        if (controller.selection ==
            TextSelection.fromPosition(
              TextPosition(
                offset: controller.text.length - 1,
              ),
            )) {
          controller.selection = TextSelection.fromPosition(
            TextPosition(
              offset: controller.text.length,
            ),
          );
        }
      }
    });
```

**Comment by ammarqusailah** [comment] 2023-04-16 00:02
This solution worked for me with Android and Windows
```dart
controller.addListener(() {
      if (controller != null) {
        if (controller.selection ==
            TextSelection.fromPosition(
              TextPosition(
                offset: controller.text.length - 1,
              ),
            )) {
          controller.selection = TextSelection.fromPosition(
            TextPosition(
              offset: controller.text.length,
            ),
          );
        }
      }
    });
```

**Comment by abdullahqasemi** [comment] 2023-04-16 10:28
> This solution worked for me with Android and Windows
> 
> ```dart
> controller.addListener(() {
>       if (controller != null) {
>         if (controller.selection ==
>             TextSelection.fromPosition(
>               TextPosition(
>                 offset: controller.text.length - 1,
>               ),
>             )) {
>           controller.selection = TextSelection.fromPosition(
>             TextPosition(
>               offset: controller.text.length,
>             ),
>           );
>         }
>       }
>     });
> ```

this worked for me
Thanks

**Comment by LongCatIsLooong** [comment] 2023-10-26 20:26
Tried with canvaskit renderer and on linux. The issue doesn't seem reproducible on the master branch. Closing.

**Closed by LongCatIsLooong** 2023-10-26 20:26 UTC
Labels: a: text input, platform-android, engine, a: internationalization, dependency: skia, platform-web, e: web_canvaskit, has reproducible steps, P2, found in release: 3.7, found in release: 3.8, team-engine, triaged-engine, multiteam-retriage-candidate
