### ISSUE TITLE
[in_app_purchase] Billing Dialogue opens again after purchase. [iOS]

### ISSUE THREAD

**Issue by rushabhshah065** [flutter/flutter#88000] opened 2021-08-10 18:14 UTC
I am facing a very weird issue. 

I have used  **in_app_purchase: ^1.0.6** for in-app purchases. It works totally fine for android but for iOS I have an issue.

### I created a sandbox test account and used that account for in-app testing. When I add my credential and test the in-app purchase, I did not receive any events in the purchase stream after the first purchase. And billing dialogue opened up the second time itself and when I entered the credential again and purchase it again it works perfectly.

Below is my code for buying non-consumable items.

 ```
 var transactions = await SKPaymentQueueWrapper().transactions();
    transactions.forEach((skPaymentTransactionWrapper) {
      SKPaymentQueueWrapper().finishTransaction(skPaymentTransactionWrapper);
    });

    _inAppPurchase.buyNonConsumable(purchaseParam: purchaseParam);
```

This is my purchase stream.

```
final Stream<List<PurchaseDetails>> purchaseUpdated =
        _inAppPurchase.purchaseStream;
    //logger.i(purchaseUpdated);
    _subscription = purchaseUpdated.listen((purchaseDetailsList) {
      logger.i("_listenToPurchaseUpdated");
      print("_listenToPurchaseUpdated");
      if (purchaseDetailsList.length > 0)
        _listenToPurchaseUpdated(purchaseDetailsList);
    }, onDone: () {
      logger.i("DONE");
      print("DONE");
      _subscription.cancel();
    }, onError: (error) {
      // handle error here.
      logger.i("Error");
      print("Error");
    });
```

This is my listen-to purchase code.

```
void _listenToPurchaseUpdated(List<PurchaseDetails> purchaseDetailsList) {
    purchaseDetailsList.forEach((PurchaseDetails purchaseDetails) async {
      if (purchaseDetails.status == PurchaseStatus.pending) {
        //showPendingUI();
        print("pending");
      } else {
        if (purchaseDetails.status == PurchaseStatus.error) {
          handleError(purchaseDetails.error!);
          print("purchaseDetails.status == PurchaseStatus.error");
        } else if (purchaseDetails.status == PurchaseStatus.purchased ||
            purchaseDetails.status == PurchaseStatus.restored) {
          bool valid = await _verifyPurchase(purchaseDetails);
          if (valid) {
            print("deliverProduct");
            deliverProduct(purchaseDetails);
          } else {
            _handleInvalidPurchase(purchaseDetails);
            return;
          }
        }
        if (purchaseDetails.pendingCompletePurchase) {
          await _inAppPurchase.completePurchase(purchaseDetails);
        }
      }
    });
  }
```

_I am using iPhone XR. OS 14.6._

https://user-images.githubusercontent.com/48256486/128913084-5f84b731-6ebe-46c1-ab25-44f0c1a9a915.mp4

**Comment by TahaTesser** [comment] 2021-08-10 18:21
Hi @rushabhshah065 
This is only in the sandbox, a duplicate of https://github.com/flutter/flutter/issues/82398

**Closed by TahaTesser** 2021-08-10 18:21 UTC
Labels: in triage

**Comment by rushabhshah065** [comment] 2021-08-11 05:49
@TahaTesser For me after the first purchase, apple shows purchase dialogue again. Not only the authentication but purchase dialogue to buy again. Is it normal behavior for sandbox users?
