### ISSUE TITLE
Unable to scroll horizontal, PC & WEB, ListView & SingleChildScrollView

### ISSUE THREAD

**Issue by alexsunday** [flutter/flutter#124116] opened 2023-04-04 12:23 UTC
## Steps to Reproduce

1. flutter run

1. when i use scroll vertical, it's correct. 
```dart
Container(
      height: 200,
      width: 600,
      color: const Color.fromARGB(255, 227, 223, 223),
      child: SingleChildScrollView(
        scrollDirection: Axis.vertical,
        padding: const EdgeInsets.symmetric(horizontal: 10),
        child: Column(
          children: children,
        ),
      ),
    );
```

![图片](https://user-images.githubusercontent.com/1531092/229787652-1ae25661-597d-4295-8007-c91239b19d3e.png)

3. but When I changed to horizontal, it won't work anymore. unable to scroll, whether using the mouse or scroll wheel 
```dart
Container(
      height: 200,
      width: 600,
      color: const Color.fromARGB(255, 227, 223, 223),
      child: SingleChildScrollView(
        scrollDirection: Axis.horizontal,
        padding: const EdgeInsets.symmetric(horizontal: 10),
        child: Row(
          children: children,
        ),
      ),
    );
```

![图片](https://user-images.githubusercontent.com/1531092/229787742-d2a5d1b3-a490-4913-85ef-06d8188abea1.png)

 Even if I use the official example, it is still incorrect: 
https://docs.flutter.dev/cookbook/lists/horizontal-list

or this: https://flutter.cn/docs/cookbook/lists/horizontal-list , this page builtin a dartpad.

![图片](https://user-images.githubusercontent.com/1531092/229786527-b49f86b2-1a3b-46b7-b0ac-7aa91202ef09.png)

full test code: https://gist.github.com/alexsunday/13738cafd5a3608e1ce0afb76a449e39

**Expected results:** 
A horizontal scroll bar be visible,  or it can be use a mouse or gesture to scroll 

**Actual results:** 
cannot scroll child elements.

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

class TestSingleScroll extends StatelessWidget {
  const TestSingleScroll({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    const n = 10;
    final List<Widget> children = [];
    for (int i = 0; i != n; i++) {
      children.add(Container(
          width: 100,
          height: 100,
          decoration: BoxDecoration(
            border: Border.all(color: Colors.green, width: 1),
          ),
          child: Center(
            child: Text("$i"),
          )));
    }
    return Container(
      height: 200,
      width: 600,
      color: const Color.fromARGB(255, 227, 223, 223),
      child: SingleChildScrollView(
        scrollDirection: Axis.vertical,
        padding: const EdgeInsets.symmetric(horizontal: 10),
        child: Column(
          children: children,
        ),
      ),
    );
  }
}

void main() {
  runApp(const MaterialApp(
    debugShowCheckedModeBanner: false,
    home: Scaffold(
      body: TestSingleScroll(),
    ),
  ));
}

```

</details>

<details>
  <summary>Logs</summary>

```
Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
[√] Flutter (Channel stable, 3.7.6, on Microsoft Windows [版本 10.0.19045.2728], locale zh-CN)
    • Flutter version 3.7.6 on channel stable at F:\flutter\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 12cb4eb7a0 (5 weeks ago), 2023-03-01 10:29:26 -0800
    • Engine revision ada363ee93
    • Dart version 2.19.3
    • DevTools version 2.20.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[X] Windows Version (Unable to confirm if installed Windows version is 10 or greater)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at d:\Android\sdk
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.4.4)
    • Visual Studio at D:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.4.33213.308
    • Windows 10 SDK version 10.0.22000.0

[√] Android Studio (version 4.0)
    • Android Studio at D:\Program Files\Android\Android Studio
    • Flutter plugin version 51.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (2 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [版本 10.0.19045.2728]
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 111.0.1661.62

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 3 categories.
```

</details>

**Comment by navaronbracke** [comment] 2023-04-04 13:09
I can scroll horizontally using Shift + mouse wheel. You have to use shift as that is the keybinding for horizontal scrolling.

I do not get a scrollbar when scrolling horizontally, while I do get one when scrolling vertically.
Not sure if not having the horizontal scrollbar is the bug you are referring to?

Code sample:
```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  final String title;

  const MyHomePage({
    Key? key,
    required this.title,
  }) : super(key: key);

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Container(
          height: 200,
          width: 600,
          color: const Color.fromARGB(255, 227, 223, 223),
          child: SingleChildScrollView(
            scrollDirection: Axis.horizontal,
            padding: const EdgeInsets.symmetric(horizontal: 10),
            child: Row(
              children: [
                Container(
                  width: 200,
                  height: 100,
                  color: Colors.green,
                ),
                Container(
                  width: 200,
                  height: 100,
                  color: Colors.yellow,
                ),
                Container(
                  width: 200,
                  height: 100,
                  color: Colors.red,
                ),
                Container(
                  width: 200,
                  height: 100,
                  color: Colors.blue,
                ),
                Container(
                  width: 200,
                  height: 100,
                  color: Colors.green,
                ),
                Container(
                  width: 200,
                  height: 100,
                  color: Colors.yellow,
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}
```

**Comment by exaby73** [comment] 2023-04-04 14:50
Hello @alexsunday. Try scrolling while holding shift to scroll horiontally

**Comment by alexsunday** [comment] 2023-04-04 15:23
> Hello @alexsunday. Try scrolling while holding shift to scroll horizontally

Microsoft Windows [VERSION 10.0.19045.2728] 64bit

both use 

Shift + mouse wheel
shift + mouse click/gesture 

unable scroll horizontally.

**Comment by exaby73** [comment] 2023-04-05 06:52
I believe this is a duplicate of https://github.com/flutter/flutter/issues/105095. While in that issue, it seems to be specific to the trackpad, I believe it might be the same issue you are experiencing. Therefore, I will close this issue in favor of that one. You can upvote the original comment of that issue, provide details in the thread and follow up with that issue. Thank you.

**Closed by exaby73** 2023-04-05 06:52 UTC
Labels: in triage
