### ISSUE TITLE
Every invocation of `flutter doctor -v` leaves 💩 `xcdevice observe` instances running on mac

### ISSUE THREAD

**Issue by kevmoo** [flutter/flutter#157641] opened 2024-10-25 21:26 UTC
1. update flutter
2. run `flutter doctor -v`
3. run `ps`

Notice

```console
> ps
  PID TTY           TIME CMD
10334 ttys000    0:00.71 -zsh
11479 ttys001    0:00.88 -zsh
13103 ttys002    0:00.08 /Applications/Xcode.app/Contents/Developer/usr/bin/xcdevice observe --usb
13104 ttys003    0:00.08 /Applications/Xcode.app/Contents/Developer/usr/bin/xcdevice observe --wifi
```

**Comment by jmagman** [comment] 2024-10-25 21:54
This is a duplicate of https://github.com/flutter/flutter/issues/73859

**Closed by jmagman** 2024-10-25 21:54 UTC
Labels: platform-ios, tool, platform-mac, fyi-ios, team-tool

**Comment by kevmoo** [comment] 2024-10-25 21:58
Ugh, and of course I've already 👍 https://github.com/flutter/flutter/issues/73859 🤦
