### ISSUE TITLE
[web]: Flutter Web not working on Chrome OS

### ISSUE THREAD

**Issue by jaydanurwin** [flutter/flutter#40478] opened 2019-09-14 03:14 UTC
### Impact: 

HIGH, can't build app at all

### Environment: 

Pixel Slate, Chrome OS 76, Stable Channel with Linux enabled

It's been working great for Android builds using USB Debugging.

### Problem: 

Not able to build Flutter for Web on Chrome OS

```
Launching lib/main.dart on Chrome in debug mode...
Invalid argument(s): Cannot find executable for google-chrome.
#0      _getExecutable  (package:process/src/interface/local_process_manager.dart:127:5)
#1      LocalProcessManager.start  (package:process/src/interface/local_process_manager.dart:43:30)
#2      ChromeLauncher.launch  (package:flutter_tools/src/web/chrome.dart:106:50)
<asynchronous suspension>
#3      ChromeDevice.startApp  (package:flutter_tools/src/web/web_device.dart:134:36)
<asynchronous suspension>
#4      ResidentWebRunner.run  (package:flutter_tools/src/build_runner/resident_web_runner.dart:175:20)

...

Failed to build application for the web.
```
### Analysis:

Went through all of the steps to enable Flutter for Web at https://flutter.dev/docs/get-started/web as instructed. Did everything the same way on a Macbook running Mac OS High Sierra and it worked great.

**Comment by jonahwilliams** [comment] 2019-09-14 17:57
Please include the output of `flutter doctor -v`

The error is because it is trying to launch chrome on a device that doesn't have it installed, or at least not in the usual place. The location of chrome can be configured with the CHROME_EXECUTABLE environment variable, or skipped by launching on the generic "web" device. Without more information on what version of Flutter you are using I won't be able to determine if something else is going wrong.

**Comment by jaydanurwin** [comment] 2019-09-14 19:17
Thank you for the quick response @jonahwilliams. Sorry this is my first Flutter issue reported.

Here is the output:
```
[✓] Flutter (Channel master, v1.10.2-pre.73, on Linux, locale en_US.UTF-8)
    • Flutter version 1.10.2-pre.73 at /home/jaydanurwin/development/tools/flutter
    • Framework revision a7cfdbd3f3 (2 days ago), 2019-09-12 19:13:42 -0700
    • Engine revision 7ea9884ab0
    • Dart version 2.5.0 (build 2.5.0-dev.4.0 be66176534)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/jaydanurwin/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find chrome executable at google-chrome)
    ! CHROME_EXECUTABLE not set

[✓] Android Studio (version 3.5)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 38.2.3
    • Dart plugin version 191.8405
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.38.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.4.1

[✓] Connected device (2 available)
    • Chrome • chrome • web-javascript • unknown (unsupported)
    • Server • web    • web-javascript • Flutter Tools

! Doctor found issues in 1 category.
```
Thank you for the help! :)

**Comment by jonahwilliams** [comment] 2019-09-14 19:40
```
[✗] Chrome - develop for the web (Cannot find chrome executable at google-chrome)
    ! CHROME_EXECUTABLE not set
```

This line indicates that it won't be able to launch chrome, though we should probably make sure the device is removed from the list. Does running with -d web and manually connecting with a browser work?

**Comment by jaydanurwin** [comment] 2019-09-14 19:55
```
~/development/flutter/codelab1$ flutter run -d web
Launching lib/main.dart on Server in debug mode...
lib/main.dart is being served at http://localhost:35297/                
Building application for the web...                                23.8s

👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 
Warning: Flutter's support for building web applications is highly experimental.
For more information see https://github.com/flutter/flutter/issues/34082.
👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 

🔥  To hot restart (and rebuild state), press "R".
For a more detailed help message, press "h". To quit, press "q".
```

It looks like it runs properly; however, when I navigate to http://localhost:35297/  I get a refused to connect error. I think this is because of how Crostini Linux on Chrome OS handles localhost ports.

**Comment by jonahwilliams** [comment] 2019-09-14 20:02
You'll likely need to adjust the hostname and port with the `--web-hostname` and `--web-port` options, though I'm not sure what to.

**Comment by jaydanurwin** [comment] 2019-09-14 20:30
`flutter run -d web --web-port 8000` worked! It took a while to build but it seems to be working. 

It just seems like there needs to be an exception for Chrome OS devices to ignore the CHROME_EXECUTABLE because it doesn't exist. Maybe a hint in the [docs](https://flutter.dev/docs/get-started/web) would work for now as well.

Thank you for you help!

**Comment by BondarenkoStas** [comment] 2019-09-15 15:58
@jaydanurwin Awesome! Can you please create a new issue with the proposal you mentioned in the comment above? As the problem is resolved, it would make sense to close it, but open a new one with the hint and exception and a link on the current issue.

**Closed by BondarenkoStas** 2019-09-15 15:58 UTC
Labels: ☸ platform-web

**Comment by Bruskyer** [comment] 2019-11-05 08:48
When run flutter web on vs code I get error(Unable to connect to Chrome debug port: 56044
 SocketException: OS Error: The remote computer refused the network connection.
, errno = 1225, address = localhost, port = 56051) and chrome tab appear empty no localhost and port in addres bar! please can you share any solution for this issue? or there is a way to change or set custom localhost and port ?
Thanks

**Comment by cketcham** [comment] 2020-03-23 03:53
I had to do `flutter run -d web --web-port 8000 --web-hostname 0.0.0.0` which let me connect to the ip found with `hostname -I`

**Comment by somitrov** [comment] 2021-03-27 02:27
this post dosnt has any solution useless

**Comment by jaydanurwin** [comment] 2021-03-27 16:27
Your closest thing to a solution for now would be in #72982 where you can install chromium and set it as the target browser for web development. I've commented on there asking for something better if you'd like to +1 it

**Comment by timsneath** [comment] 2023-02-25 20:13
I think we can do better than the current status quo. Adding some suggestions for a path forward, along with formally documenting the current workaround, in https://github.com/flutter/flutter/issues/121462.
