### ISSUE TITLE
Image Picker IOS crash app

### ISSUE THREAD

**Issue by xperiafan13-rom** [flutter/flutter#34691] opened 2019-06-19 02:44 UTC
Hi, I get crash app when I take image from camera source using image_picker image_picker: ^0.6.0+9

Im using:
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.5 18F132, locale es-MX)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
[✓] Android Studio (version 3.4)
[✓] VS Code (version 1.35.1)
[✓] Connected device (1 available)

IMy devices is: iPhone 5 iOS 10 and iPhone 7 plus with iOS 12.3

I don get any log from flutter run, but I use Xcode to capture this
Image log:
https://i.ibb.co/WckX9d3/Captura-de-Pantalla-2019-06-18-a-la-s-21-41-59.png

Log
2019-06-18 21:37:27.052944-0500 Runner[666:144751] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[0]'
*** First throw call stack:
(0x1b397b3d 0x1a61f067 0x1b2aa8cf 0x1b2b4a01 0x2bc6be3 0x2bc8013 0x20a83bb1 0x26c92bbf 0x2e5c8d45 0x2e5c87a3 0x2e5c80bf 0x205fe3b5 0x205fe349 0x205e8979 0x205fdc85 0x205fd7cf 0x205f870f 0x205ca2bb 0x20d5d7f7 0x20d5819b 0x20d5857d 0x1b353fdd 0x1b353b05 0x1b351f51 0x1b2a51af 0x1b2a4fd1 0x1ca4fb41 0x2062da53 0x108d6b 0x1aa924eb)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb)

**Comment by jan-pavlovsky** [comment] 2019-06-19 10:06
Hi,

similar problem here. However, I'm getting the crash the second time I try to use ImagePicker.

I got to a screen, where I user image picker, shoot and utilize video, all good. Then I pop the widget and navigate back to it. Now, I get this crash when I try to shoot video with ImagePicker.pickVideo.

**Comment by kafein** [comment] 2019-06-19 17:37
Similar problem with Ipad (Ios 9.3.5)

[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.5 18F132, locale tr-TR)
    • Flutter version 1.5.4-hotfix.2 at /Users/emrah/development/flutter
    • Framework revision 7a4c33425d (7 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/emrah/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/emrah/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.1

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 34.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.3.5)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 33.3.2
    • Dart plugin version 183.5912.23

[✓] VS Code (version 1.35.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.1.0

[✓] Connected device (2 available)
    • Ayhan iPad'i       • e2bcd893505fd4875fadfb66c5867007171a36fa • ios • iOS 9.3.5
    • iPad Pro (11-inch) • 0513835B-EDA3-4286-AD0A-BBEE63AAD91F     • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)

• No issues found!

*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[0]'
	*** First throw call stack:
	(0x2370791b 0x22ea2e17 0x2361c871 0x23626a21 0x1c57937 0x1c59aaf 0x2811c693 0x2d12de7b 0x2d1429bb 0x2d173a2b 0x2d173877 0x27cba755 0x27cba6e1 0x27ca26d3 0x27cba005 0x27cb9c7f 0x27cb268f 0x27c83125 0x27c816d3 0x236c9dff 0x236c99ed 0x236c7d5b 0x23617229 0x23617015 0x24c07ac9 0x27ceb189 0x1d455 0x232bf873)
Lost connection to device.

**Comment by AncientPixel** [comment] 2019-06-20 09:54
I had the exact same crash but after adding the following lines to my Info.plist it was resolved. Please check if it helps (lifted from the https://pub.dev/packages/image_picker page):

```
iOS #
Add the following keys to your Info.plist file, located in <project root>/ios/Runner/Info.plist:

NSPhotoLibraryUsageDescription - describe why your app needs permission for the photo library. This is called Privacy - Photo Library Usage Description in the visual editor.
NSCameraUsageDescription - describe why your app needs access to the camera. This is called Privacy - Camera Usage Description in the visual editor.
NSMicrophoneUsageDescription - describe why your app needs access to the microphone, if you intend to record videos. This is called Privacy - Microphone Usage Description in the visual editor.
```

**Comment by kafein** [comment] 2019-06-22 10:41
> I had the exact same crash but after adding the following lines to my Info.plist it was resolved. Please check if it helps (lifted from the https://pub.dev/packages/image_picker page):

Thanks for suggestion but these keys already exists in Info.plist.

/cc @cyanglaz (I think you are code owner for this plugin.)

**Comment by cyanglaz** [comment] 2019-06-24 16:35
Thank you for filing this, could anyone provide a minimum sample app code for the crash?

**Comment by kafein** [comment] 2019-06-24 23:56
> Thank you for filing this, could anyone provide a minimum sample app code for the crash?

I think it's version issue, 0.6.0+10 works well. (previous version is 0.6.0+8)
Noticed when try create repro case. Thanks.

**Comment by cyanglaz** [comment] 2019-06-24 23:58
@xperiafan13-rom, did 0.6.0+10 fix your crash as well?

**Comment by xperiafan13-rom** [comment] 2019-06-25 16:55
> @xperiafan13-rom, did 0.6.0+10 fix your crash as well?

Sorry, but no, same error

**Comment by cyanglaz** [comment] 2019-06-25 16:59
@xperiafan13-rom Could you provide a sample mini app to reproduce the issue?

**Comment by PaulRichezE-Mothep** [comment] 2019-07-04 13:39
Same problem here, 
In ios/Runner/Info.plist
`<key>NSCameraUsageDescription</key>
<string>This app requires access to the camera.</string>`
But crash when i take a picture.

Anyone got a solution ?

**Comment by PaulRichezE-Mothep** [comment] 2019-07-05 09:00
This is the error : 
`Snapshotting a view that has not been rendered results in an empty snapshot. Ensure your view has been rendered at least once before snapshotting or snapshot after screen updates.
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[0]'
*** First throw call stack: `

**Comment by cyanglaz** [comment] 2019-07-08 16:54
I would like to ask a favor from anyone who can reproduce the crash since I am not able to reproduce the crash myself. An iOS stack trace can help to see where the crash came from. Here is a sample step to see the stack trace.
1. Open the project using XCode, it's usually under <projectroot>/ios/runner.xcworkspace
2. Step an exception breakpoint: It can be easily found online for how to set the exception break point, here is an example that I found https://stackoverflow.com/questions/17802662/exception-breakpoint-in-xcode
3. Run the app using XCode, (Don't run it with `flutter run` as the break point won't stop that way). 
4. When you experience the crash, the exception breakpoint should stop as where it crashes. And the stack trace of it should help finding the bug!

**Comment by jigarfumakiya** [comment] 2019-07-09 06:06
anyone find issue i am getting same error. In android that works fine.

**Comment by cyanglaz** [comment] 2019-07-12 19:55
> This is the error :
> `Snapshotting a view that has not been rendered results in an empty snapshot. Ensure your view has been rendered at least once before snapshotting or snapshot after screen updates. *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[0]' *** First throw call stack: `

@PaulRichezE-Mothep Do you mind to include the call stack as well? That might be helpful

**Comment by muyi0728** [comment] 2019-07-15 09:59
I am calling the camera on iOS 9.3.2 to reproduce this error, but IOS 10.0 and above is normal

**Comment by cyanglaz** [comment] 2019-07-15 15:37
@xperiafan13-rom Were you able to follow the steps I mentioned above to get the stack trace?

**Comment by cyanglaz** [comment] 2019-07-15 15:40
Unfortunately, I have not been able to reproduce the issue. Thus, I can't guarantee this can be fixed by July. I am pushing the milestone back to September. If anyone can provide an iOS stack trace for this crash it would be super helpful.

**Comment by muyi0728** [comment] 2019-07-16 03:05
@cyanglaz I found that the application crashed because UIImagePickerControllerReferenceURL returned nil，here is my repair method，now my should be able to run normally and won't crash:

 NSURL *imageAssetURL = [info objectForKey:UIImagePickerControllerReferenceURL];
    UIImage * image = [info objectForKey:UIImagePickerControllerEditedImage];
    if (image == nil) {
        image = [info objectForKey:UIImagePickerControllerOriginalImage];
    }
    PHAsset *asset;
    if (imageAssetURL) {
        PHFetchResult *result = [PHAsset fetchAssetsWithALAssetURLs:@[imageAssetURL] options:nil];
        asset = [result firstObject];
    }

**Comment by cyanglaz** [comment] 2019-07-16 15:46
@muyi0728 Thank you so much for finding the issue. I have create a patch fixing this issue. 
https://github.com/flutter/plugins/pull/1862
@xperiafan13-rom You mentioned the crash also happened on device with iOS 12 for you. The issue seems only related to devices below iOS 11. The iOS 12 crash you have experienced might be a different crash.

**Comment by cyanglaz** [comment] 2019-07-16 16:44
The patch is merged, this crash should be fixed with 0.6.0+17.
@xperiafan13-rom If you still experiencing crashes on iOS 12, it might not related to the crash log you posted. Please feel empowered to open another issue with details!

**Closed by cyanglaz** 2019-07-16 16:44 UTC
Labels: p: first party, p: image_picker, plugin, severe: crash, waiting for customer response

**Comment by MATTYGILO** [comment] 2020-07-21 12:21
> Hi,
> 
> similar problem here. However, I'm getting the crash the second time I try to use ImagePicker.
> 
> I got to a screen, where I user image picker, shoot and utilize video, all good. Then I pop the widget and navigate back to it. Now, I get this crash when I try to shoot video with ImagePicker.pickVideo.

Have you found a fix I'm having the same issue it works the first time round then the second time it crashes

**Comment by StevenAtAskAttis** [comment] 2020-09-25 12:09
Hi, I have the same issue here.
When I want to select an image for the second time, the app crashes.

I tried it with the example from github and same result.

*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Modifications to the layout engine must not be performed from a background thread after it has been accessed from the main thread.'
terminating with uncaught exception of type NSException
abort() called
CoreSimulator 732.17 - Device: iPhone 8 (F6501B20-E8F7-4A76-9327-3A6276168C64) - Runtime: iOS 14.0 (18A372) - DeviceType: iPhone 8


I'm using:  
image_picker: ^0.6.7+11
ios14 but was the same on ios13

### Flutter doctor:
[✓] Flutter (Channel stable, 1.20.4, on Mac OS X 10.15.6 19G2021, locale en-GB)
    • Flutter version 1.20.4 at /Users/steven/Documents/development/flutter
    • Framework revision fba99f6cf9 (11 days ago), 2020-09-14 15:32:52 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/steven/Library/Android/sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.49.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

[✓] VS Code (version 1.44.2)
    • VS Code at /Users/steven/Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

 
[✓] Connected device (1 available)            
    • iPhone 8 (mobile) • F6501B20-E8F7-4A76-9327-3A6276168C64 • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)

• No issues found!



### crash report
[Runner_2020-09-25-131009.crash.txt](https://github.com/flutter/flutter/files/5282476/Runner_2020-09-25-131009.crash.txt)

**Comment by cyanglaz** [comment] 2020-09-25 17:23
@StevenAtAskAttis what you saw is https://github.com/flutter/flutter/issues/65995

**Comment by dinesh-commits** [comment] 2020-09-29 09:15
Environmental Details:

IOS version: ios13
Iphone: 8

My code:
 `await ImagePicker.pickImage(source: ImageSource.camera);`

Description:
In my case, its crashing randomly. I have an app where I'm adding image one by one,

Random crash scenarios
1. While adding 250th image
2. While adding 350th image

Can anyone help me to solve this? I'm not getting any logs.

**Comment by Dinesh41** [comment] 2020-10-04 03:20
> Environmental Details:
> 
> IOS version: ios13
> Iphone: 8
> 
> My code:
> `await ImagePicker.pickImage(source: ImageSource.camera);`
> 
> Description:
> In my case, its crashing randomly. I have an app where I'm adding image one by one,
> 
> Random crash scenarios
> 
> 1. While adding 250th image
> 2. While adding 350th image
> 
> Can anyone help me to solve this? I'm not getting any logs.

I found the issue. While adding each image, some garbage collection is happening. Due to that when it reached 250th image, there is no memory to access. Due to memory issue app is crashing.

Any quick solution?

**Comment by SashaFarkas** [comment] 2020-11-17 05:37
@cyanglaz 
`libsystem_kernel.dylib`__pthread_kill:
    0x7fff5df73330 <+0>:  movl   $0x2000148, %eax          ; imm = 0x2000148 
    0x7fff5df73335 <+5>:  movq   %rcx, %r10
    0x7fff5df73338 <+8>:  syscall 
->  0x7fff5df7333a <+10>: jae    0x7fff5df73344            ; <+20>
    0x7fff5df7333c <+12>: movq   %rax, %rdi
    0x7fff5df7333f <+15>: jmp    0x7fff5df6d629            ; cerror_nocancel
    0x7fff5df73344 <+20>: retq   
    0x7fff5df73345 <+21>: nop    
    0x7fff5df73346 <+22>: nop    
    0x7fff5df73347 <+23>: nop    
`  
`Exception	NSException *	"Modifications to the layout engine must not be performed from a background thread after it has been accessed from the main thread."	0x000060000316a010`

`io.flutter.1.raster (10): "Modifications to the layout engine must not be performed from a background thread after it has been accessed from the main thread."`

It happens on every second time I use getImage(ImageSource.gallery)

**Comment by taiyrbegeyev** [comment] 2020-11-24 13:59
> Hi,
> 
> similar problem here. However, I'm getting the crash the second time I try to use ImagePicker.
> 
> I got to a screen, where I user image picker, shoot and utilize video, all good. Then I pop the widget and navigate back to it. Now, I get this crash when I try to shoot video with ImagePicker.pickVideo.

I am also having the same issue. Is there any fix for this?

**Comment by Qabbout** [comment] 2020-11-27 12:49
> Hi,
> 
> similar problem here. However, I'm getting the crash the second time I try to use ImagePicker.
> 
> I got to a screen, where I user image picker, shoot and utilize video, all good. Then I pop the widget and navigate back to it. Now, I get this crash when I try to shoot video with ImagePicker.pickVideo.

Same problem, did anyone find a solution or a workaround?

**Comment by MarkoKrstanovicBM** [comment] 2020-12-01 18:59
> > Hi,
> > similar problem here. However, I'm getting the crash the second time I try to use ImagePicker.
> > I got to a screen, where I user image picker, shoot and utilize video, all good. Then I pop the widget and navigate back to it. Now, I get this crash when I try to shoot video with ImagePicker.pickVideo.
> 
> Same problem, did anyone find a solution or a workaround?

Same issue here, any solutions?

**Comment by tranvannhat** [comment] 2020-12-02 14:12
iOS 14, same issue :(

**Comment by Pramodlamsal** [comment] 2020-12-03 07:05
in ios 14 the same issue happen

**Comment by shohkhan** [comment] 2020-12-07 00:13
Yes, same issue on iOS 14

**Comment by rao21** [comment] 2020-12-11 12:06
The same issue happened in ios 14. When we select an image from the gallery and again going to select its crashes. Work fine on Android

**Comment by mellowcello77** [comment] 2020-12-13 22:56
Exact same, when you call it the second time it crashes the app without any exceptions or reason. iOS. Latest version 0.6.7+15

**Comment by xellDart** [comment] 2020-12-19 14:47
same issue on iOS 14

**Comment by ataberkw** [comment] 2020-12-19 17:52
Issue still continues on ios 14, iphone se simulator. It's being closed doesn't make any sense. When I open picker second time, app crashes without any message.

Even on a basic usage.
![image](https://user-images.githubusercontent.com/10375421/102695982-0ab46e80-423c-11eb-897b-44fb6b059343.png)

**Comment by iwasscience** [comment] 2020-12-25 20:00
Same issue for me on any Simulator running IOS 14, but Real Device is working without problems.

**Comment by jpetro416** [comment] 2021-01-03 22:09
Same error for me IOS 14 both sim and real

**Comment by shohkhan** [comment] 2021-01-03 22:15
> Yes, same issue on iOS 14

I fixed the issue for iOS by updating the mac OS and flutter. Now working on real devices (through test flight). However, the issue persists on the simulator.

Also, the problem doesn't exist with Android.

**Comment by Kedar-jirel** [comment] 2021-01-29 18:14
Same Problem here 
2021-01-29 23:35:01.932722+0545 Runner[8348:91523] BackgroundSession <74424F42-DF9E-4A7D-B1F6-723B0AD50C97> connection to background transfer daemon invalidated
2021-01-29 23:35:09.930426+0545 Runner[8348:91194] This application is modifying the autolayout engine from a background thread after the engine was accessed from the main thread. This can lead to engine corruption and weird crashes.
 Stack:(
	0   CoreAutoLayout                      0x00000001152c2b9b _AssertAutoLayoutOnAllowedThreadsOnly + 190
	1   CoreAutoLayout                      0x00000001152c2926 -[NSISEngine _optimizeWithoutRebuilding] + 54
	2   CoreAutoLayout                      0x00000001152c2459 -[NSISEngine optimize] + 92
	3   CoreAutoLayout                      0x00000001152bd8c4 -[NSISEngine performPendingChangeNotifications] + 82
	4   UIKitCore                           0x000000011ed41e75 -[UIView(Hierarchy) layoutSubviews] + 491
	5   UIKitCore                           0x000000011ed555b8 -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 2924
	6   QuartzCore                          0x000000010ce7dc33 -[CALayer layoutSublayers] + 258
	7   QuartzCore                          0x000000010ce841a5 _ZN2CA5Layer16layout_if_neededEPNS_11TransactionE + 575
	8   QuartzCore                          0x000000010ce8ff47 _ZN2CA5Layer28layout_and_display_if_neededEPNS_11TransactionE + 65
	9   QuartzCore                          0x000000010cdcf408 _ZN2CA7Context18commit_transactionEPNS_11TransactionEdPd + 496
	10  QuartzCore                          0x000000010ce061ef _ZN2CA11Transaction6commitEv + 783
	11  QuartzCore                          0x000000010ce073ab _ZN2CA11Transaction17observer_callbackEP19__CFRunLoopObservermPv + 79
	12  CoreFoundation                      0x000000010f8b51f8 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23
	13  CoreFoundation                      0x000000010f8afa77 __CFRunLoopDoObservers + 547
	14  CoreFoundation                      0x000000010f8b001a __CFRunLoopRun + 1113
	15  CoreFoundation                      0x000000010f8af6d6 CFRunLoopRunSpecific + 567
	16  Flutter                             0x00000001094c9651 _ZN3fml17MessageLoopDarwin3RunEv + 65
	17  Flutter                             0x00000001094c46ca _ZN3fml15MessageLoopImpl5DoRunEv + 22
	18  Flutter                             0x00000001094c8350 _ZNSt3__114__thread_proxyINS_5tupleIJNS_10unique_ptrINS_15__thread_structENS_14default_deleteIS3_EEEEZN3fml6ThreadC1ERKNS_12basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEEE3$_0EEEEEPvSJ_ + 170
	19  libsystem_pthread.dylib             0x00000001134ab950 _pthread_start + 224
	20  libsystem_pthread.dylib             0x00000001134a747b thread_start + 15
)
2021-01-29 23:35:09.965303+0545 Runner[8348:91194] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Modifications to the layout engine must not be performed from a background thread after it has been accessed from the main thread.'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010f947af6 __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x000000010f449e78 objc_exception_throw + 48
	2   CoreAutoLayout                      0x00000001152c2c89 -[NSISEngine tryToOptimizeReturningMutuallyExclusiveConstraints] + 0
	3   CoreAutoLayout                      0x00000001152c2926 -[NSISEngine _optimizeWithoutRebuilding] + 54
	4   CoreAutoLayout                      0x00000001152c2459 -[NSISEngine optimize] + 92
	5   CoreAutoLayout                      0x00000001152bd8c4 -[NSISEngine performPendingChangeNotifications] + 82
	6   UIKitCore                           0x000000011ed41e75 -[UIView(Hierarchy) layoutSubviews] + 491
	7   UIKitCore                           0x000000011ed555b8 -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 2924
	8   QuartzCore                          0x000000010ce7dc33 -[CALayer layoutSublayers] + 258
	9   QuartzCore                          0x000000010ce841a5 _ZN2CA5Layer16layout_if_neededEPNS_11TransactionE + 575
	10  QuartzCore                          0x000000010ce8ff47 _ZN2CA5Layer28layout_and_display_if_neededEPNS_11TransactionE + 65
	11  QuartzCore                          0x000000010cdcf408 _ZN2CA7Context18commit_transactionEPNS_11TransactionEdPd + 496
	12  QuartzCore                          0x000000010ce061ef _ZN2CA11Transaction6commitEv + 783
	13  QuartzCore                          0x000000010ce073ab _ZN2CA11Transaction17observer_callbackEP19__CFRunLoopObservermPv + 79
	14  CoreFoundation                      0x000000010f8b51f8 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23
	15  CoreFoundation                      0x000000010f8afa77 __CFRunLoopDoObservers + 547
	16  CoreFoundation                      0x000000010f8b001a __CFRunLoopRun + 1113
	17  CoreFoundation                      0x000000010f8af6d6 CFRunLoopRunSpecific + 567
	18  Flutter                             0x00000001094c9651 _ZN3fml17MessageLoopDarwin3RunEv + 65
	19  Flutter                             0x00000001094c46ca _ZN3fml15MessageLoopImpl5DoRunEv + 22
	20  Flutter                             0x00000001094c8350 _ZNSt3__114__thread_proxyINS_5tupleIJNS_10unique_ptrINS_15__thread_structENS_14default_deleteIS3_EEEEZN3fml6ThreadC1ERKNS_12basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEEE3$_0EEEEEPvSJ_ + 170
	21  libsystem_pthread.dylib             0x00000001134ab950 _pthread_start + 224
	22  libsystem_pthread.dylib             0x00000001134a747b thread_start + 15
)
libc++abi.dylib: terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Modifications to the layout engine must not be performed from a background thread after it has been accessed from the main thread.'
terminating with uncaught exception of type NSException
CoreSimulator 732.18.6 - Device: iPhone 12 Pro Max (4A801C3B-BDCF-478A-81CF-9CFD74D183A8) - Runtime: iOS 14.3 (18C61) - DeviceType: iPhone 12 Pro Max

**Comment by mellowcello77** [comment] 2021-02-01 11:42
Still issue yes, frustrating to debug this way. But strangely not an issue on iPhone 11 simulator, but on 8 for me. All brand new installs, new flutter install after mac format.

**Comment by cyanglaz** [comment] 2021-02-01 17:42
I think the crashes described in the last few comments are https://github.com/flutter/flutter/issues/67430. The crash in the original post should be fixed. If you experience crashes similar to https://github.com/flutter/flutter/issues/34691#issuecomment-769965432 please follow https://github.com/flutter/flutter/issues/67430

**Comment by niltondiniz** [comment] 2021-06-17 13:32
Hi guys!
In my case, the app was crashed because iOS camera permission in info.plist.

i added in info.plist:
<key>NSCameraUsageDescription</key>
	<string>This app requires camera access to run the function properly</string>
