### ISSUE TITLE
firebase_crashlytics needs to be updated to fit firebase_core          ver 0.5.0                

### ISSUE THREAD

**Issue by kw2019ltd** [flutter/flutter#64632] opened 2020-08-26 10:40 UTC
firebase_crashlytics needs to be updated to fit firebase_core          ver 0.5.0     

same for firebase_admob

**Comment by TahaTesser** [comment] 2020-08-26 15:40
Hi @kw2019ltd 
From what I can see, the issue is related to a FlutterFire plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Comment by TahaTesser** [comment] 2020-08-26 15:40
Hi @kw2019ltd 
From what I can see, the issue is related to a FlutterFire plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by TahaTesser** 2020-08-26 15:40 UTC
