### ISSUE TITLE
Engine crash running gallery smoke test

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#7356] opened 2017-01-05 21:09 UTC
The gallery smoke test appears to be flaky, with an engine crash:

```
+cd examples/flutter_gallery
+flutter test
00:17 +7 -1: loading /home/travis/build/flutter/flutter/examples/flutter_gallery/test/smoke_test.dart
  Exception: Shell subprocess crashed with segmentation fault after tests finished.
  Test: /home/travis/build/flutter/flutter/examples/flutter_gallery/test/smoke_test.dart
  Shell: /home/travis/build/flutter/flutter/bin/cache/artifacts/engine/linux-x64/sky_shell
  
  
  package:stream_channel                                    _GuaranteeSink.addError
  package:flutter_tools/src/test/flutter_platform.dart 107  FlutterPlatform._startTest.<async>.<fn>.<async>
  ===== asynchronous gap ===========================
  package:flutter_tools                                     FlutterPlatform._startTest.<async>.<fn>
  package:flutter_tools/src/test/flutter_platform.dart 198  FlutterPlatform._startTest.<async>
  dart:async                                                _SyncCompleter.complete
  package:flutter_tools/src/test/flutter_platform.dart 73   FlutterPlatform._startTest.<async>.<fn>.<async>
  ===== asynchronous gap ===========================
  dart:async                                                _asyncThenWrapperHelper
  package:flutter_tools/src/test/flutter_platform.dart      FlutterPlatform._startTest
  package:flutter_tools/src/test/flutter_platform.dart 50   FlutterPlatform.loadChannel
```

Full log: [log.txt](https://github.com/flutter/flutter/files/688355/log.txt)

This was https://travis-ci.org/flutter/flutter/jobs/189313310 but I've since restarted that job so it likely won't show it any more. The PR was https://github.com/flutter/flutter/pull/7354.

**Comment by eseidelGoogle** [comment] 2017-01-06 17:04
To debug these, we will need the engine version of flutter version (which we likely can get from the pull request history) and then also we need the output of the segfault.  Unclear if sky_shell isn't printing the segfault output or if package:test is hiding it.

@chinmaygarde briefly looked into wiring up breakpad.  We may need something like that even for our linux sky_shell in order to get consistent stacks.  One way to debug would be to add a crash to sky_shell and see what `flutter test` prints in  that case.

**Comment by Hixie** [comment] 2017-01-06 17:28
I haven't been seeing output from segfaults in general in recent months (especially on devices). 

not sure if `flutter test` is showing all the output in case of crash though.

**Comment by DanTup** [comment] 2018-05-29 10:49
I think I just opened a dupe of this; latest master from today, so I think it's still happening :(

https://github.com/flutter/flutter/issues/17989

I seem to have a totally reliable repro on my MacBook; happens every time. I tried wiping Flutter's `cache` folder and also `flutter clean` and it's still happening.

**Comment by zoechi** [comment] 2019-01-21 16:55
I assume this is stale.

**Closed by zoechi** 2019-01-21 16:55 UTC
Labels: a: tests, engine, severe: crash, team: flakes, team: gallery
