### ISSUE TITLE
Obscured fields cannot be multiline.

### ISSUE THREAD

**Issue by juppdes** [flutter/flutter#47345] opened 2019-12-18 15:54 UTC
TextFormField with obscureText = true and maxLines = 1.

Obscured fields cannot be multiline.
'package:flutter/src/material/text_form_field.dart':
Failed assertion: line 144 pos 15: '!obscureText || maxLines == 1'

Flutter 1.12.13+hotfix.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 27321ebbad (8 days ago) • 2019-12-10 18:15:01 -0800
Engine • revision 2994f7e1e6
Tools • Dart 2.7.0

**Comment by HansMuller** [comment] 2019-12-18 18:25
This is the result of a change made towards the end of October: https://github.com/flutter/flutter/pull/42470

We didn't believe there was a use-case for multi-line obscured text fields. Do you have a use-case that we didn't consider?

**Comment by HansMuller** [comment] 2019-12-18 18:26
CC @justinmc

**Comment by juppdes** [comment] 2019-12-18 19:44
Sorry if I was not clear, but the error is happening even with maxLines = 1 (ie with only 1 line). Am I misunderstanding the property? What should I pass in maxLines when the field is obscured?

**Comment by juppdes** [comment] 2019-12-18 21:56
In fact, even running flutter clean, it is bringing up old error messages (the aforementioned error).
I don't know how to solve this. Any tips for "cleaning up" old errors?

**Comment by HansMuller** [comment] 2019-12-19 17:55
I've confirmed that configuring a TextFormField as you reported does not cause problems with master Flutter branch.
```
TextFormField(maxLines: 1, obscureText: true)
```
It sounds  like something in your environment is corrupt. 

If you `flutter create` a new project, does the error persist?

**Comment by juppdes** [comment] 2019-12-19 18:27
By creating a new project, the issue has been resolved. I believe something was really corrupted. Thanks so much for the help!

**Comment by HansMuller** [comment] 2019-12-19 18:44
Glad to hear that! I'm going to close this issue. If the problem reappears, please reopen.

**Closed by HansMuller** 2019-12-19 18:44 UTC
Labels: f: material design, framework

**Comment by israellias** [comment] 2020-07-21 16:35
Thats happened to me when I had defined maxLines = null. When I used maxLines = 1 it works. 

This occurs because TextFormField asserts with maxLines == 1 and don't with maxLines == null

at flutter/lib/src/material/text_form_field.dart
![image](https://user-images.githubusercontent.com/16140960/88081172-029db900-cb4e-11ea-943d-ae5f765eb1f1.png)

This widgets allows maxLines null but not maxLines null with obscureText true. Is that ok?

**Comment by justinmc** [comment] 2020-07-21 16:55
Currently we purposely do not allow multiline obscured fields, so this is correct behavior.  See https://github.com/flutter/flutter/pull/42470.

**Comment by israellias** [comment] 2020-08-07 01:49
Thats ok! I guess the correct assert would be 

assert(!obscureText  || maxLines == 1 || maxLines == null, "Obscure.....")

In order to send the correct message. Its confused when you have this assert message and do not allowed more than 1 line.

**Comment by justinmc** [comment] 2020-08-10 17:38
Hmm but this should not be allowed:

```dart
TextFormField(
  obscureText: true,
  maxLines: null,
)
```

Would it be more clear if the error message was this? "Obscured fields must only be one line"
