### ISSUE TITLE
`scrollUntilVisible` should be able to detect `SingleChildScrollView` and `ListView` as well

### ISSUE THREAD

**Issue by feinstein** [flutter/flutter#149240] opened 2024-05-29 10:14 UTC
### Use case

I am trying to setup a test with a scrollable UI, but my UI has 2 scrollables .

I am using `scrollUntilVisible`, but the `scrollable` parameter won't work if I call it like 

```dart
await tester.scrollUntilVisible(loginButtonFinder, 200, scrollable: find.byType(SingleChildScrollView));
```

Since `SingleChildScrollView` is not a subtype of `Scrollable`, so I need to make a more complex finder in order to get it to work (e.g. `find.descendant(of: find.byType(SingleChildScrollView), matching: find.byType(Scrollable))`).

### Proposal

`scrollUntilVisible` should be smarter and accept the types of scrollable widgets provided by Flutter.

**Comment by huycozy** [comment] 2024-05-29 11:37
Could you share a complete sample code? 

As mentioned on the [scrollUntilVisible](https://api.flutter.dev/flutter/flutter_test/WidgetController/scrollUntilVisible.html) docs:

>If scrollable is null, a [Finder](https://api.flutter.dev/flutter/flutter_test/Finder-class.html) that looks for a [Scrollable](https://api.flutter.dev/flutter/widgets/Scrollable-class.html) is used instead.

So you can just pass null into it to see if it works for your case.

I tried checking this with a single scrollable view (ListView) as sample code below and saw it's passed.

<details>
<summary>Sample code</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  testWidgets('Scroll test.', (WidgetTester tester) async {
    await tester.pumpWidget(
      MaterialApp(
        home: Scaffold(
          appBar: AppBar(
            title: const Text('ListView'),
            backgroundColor: Colors.blue,
          ),
          body: ListView.builder(
            padding: const EdgeInsets.all(8),
            itemCount: 50,
            itemBuilder: (BuildContext context, int index) {
              return ListTile(
                tileColor: Colors.blue[100 * (index % 9)],
                onTap: () {},
                title: Text('Entry $index'),
              );
            },
          ),
        ),
      ),
    );

    await tester.pumpAndSettle();

    await tester.scrollUntilVisible(
      find.text('Entry 30'),
      100.0,
    );

    expect(find.text('Entry 30'), findsOneWidget);
  });
}

```
</details>

**Comment by feinstein** [comment] 2024-05-29 12:16
As I said in my post, I have several scrollables.

**Comment by huycozy** [comment] 2024-05-30 05:19
In case we put `scrollable` parameter to `scrollUntilVisible`, the issue also happens when there is only one scrollable view, please check an issue https://github.com/flutter/flutter/issues/90298. And it's marked as a duplicate of https://github.com/flutter/flutter/issues/85046. There is also a case with multiple scrollable views at https://github.com/flutter/flutter/issues/85046#issuecomment-870236218. I will close this to centralize on https://github.com/flutter/flutter/issues/85046 so please follow up on it for updates. Thanks!

**Closed by huycozy** 2024-05-30 05:19 UTC
Labels: in triage

**Comment by feinstein** [comment] 2024-05-30 05:51
Ok thanks, but those don't have the suggestion I am giving here, so I will copy it there.
