### ISSUE TITLE
`flutter run` doesn't show some critical log items from Xcode

### ISSUE THREAD

**Issue by filiph** [flutter/flutter#22536] opened 2018-10-01 23:41 UTC
## Steps to Reproduce

1. Create an app using Firestore (`cloud_firestore` in dependencies). For example, the official [Firebase for Flutter codelab](https://codelabs.developers.google.com/codelabs/flutter-firebase/index.html?index=..%2F..%2Findex#0).
2. Neglect to set up the iOS project with `GoogleService-Info.plist`.
3. `flutter run` the app on iOS.

## Logs

This is what `flutter run` shows, in its entirety:

```
Launching lib/main.dart on iPhone X in debug mode...
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010930d29b __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x00000001088a9735 objc_exception_throw + 48
	2   CoreFoundation                      0x000000010930d0f5 +[NSException raise:format:] + 197
	3   Runner                              0x0000000104947aa1 +[FIRApp configure] + 481
	4   Runner                              0x0000000104c9d22c -[FLTCloudFirestorePlugin init] + 188
	5   Runner                              0x0000000104c9d0d9 +[FLTCloudFirestorePlugin registerWithRegistrar:] + 297
	6   Runner                              0x00000001048f06bb +[GeneratedPluginRegistrant registerWithRegistry:] + 123
	7   Runner                        <…>
Starting Xcode build...
Xcode build done.
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010665829b __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x0000000105bf4735 objc_exception_throw + 48
	2   CoreFoundation                      0x00000001066580f5 +[NSException raise:format:] + 197
	3   Runner                              0x0000000101befaa1 +[FIRApp configure] + 481
	4   Runner                              0x0000000101f4522c -[FLTCloudFirestorePlugin init] + 188
	5   Runner                              0x0000000101f450d9 +[FLTCloudFirestorePlugin registerWithRegistrar:] + 297
	6   Runner                              0x0000000101b986bb +[GeneratedPluginRegistrant registerWithRegistry:] + 123
	7   Runner                        <…>
```

Here's what you get in Xcode:

```
2018-10-01 16:30:54.093692-0700 Runner[21990:12461249]  - <AppMeasurement>[I-ACS036002] Analytics screen reporting is enabled. Call +[FIRAnalytics setScreenName:setScreenClass:] to set the screen name or override the default screen class name. To disable screen reporting, set the flag FirebaseScreenReportingEnabled to NO (boolean) in the Info.plist
2018-10-01 16:30:54.370913-0700 Runner[21990:12460659] You've implemented -[<UIApplicationDelegate> application:performFetchWithCompletionHandler:], but you still need to add "fetch" to the list of your supported UIBackgroundModes in your Info.plist.
2018-10-01 16:30:54.371112-0700 Runner[21990:12460659] You've implemented -[<UIApplicationDelegate> application:didReceiveRemoteNotification:fetchCompletionHandler:], but you still need to add "remote-notification" to the list of your supported UIBackgroundModes in your Info.plist.
2018-10-01 16:30:54.385564-0700 Runner[21990:12460659] *** Terminating app due to uncaught exception 'com.firebase.core', reason: '`[FIRApp configure];` (`FirebaseApp.configure()` in Swift) could not find a valid GoogleService-Info.plist in your project. Please download one from https://console.firebase.google.com/.'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010ac0529b __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x000000010a1a1735 objc_exception_throw + 48
	2   CoreFoundation                      0x000000010ac050f5 +[NSException raise:format:] + 197
	3   Runner                              0x0000000105fe9aa1 +[FIRApp configure] + 481
	4   Runner                              0x000000010633f22c -[FLTCloudFirestorePlugin init] + 188
	5   Runner                              0x000000010633f0d9 +[FLTCloudFirestorePlugin registerWithRegistrar:] + 297
	6   Runner                              0x0000000105f926bb +[GeneratedPluginRegistrant registerWithRegistry:] + 123
	7   Runner                              0x0000000105f927ca $S6Runner11AppDelegateC11application_29didFinishLaunchingWithOptionsSbSo13UIApplicationC_SDySo0j6LaunchI3KeyaypGSgtF + 138
	8   Runner                              0x0000000105f92bb4 $S6Runner11AppDelegateC11application_29didFinishLaunchingWithOptionsSbSo13UIApplicationC_SDySo0j6LaunchI3KeyaypGSgtFTo + 228
	9   UIKitCore                           0x00000001133ac4d7 -[UIApplication _handleDelegateCallbacksWithOptions:isSuspended:restoreState:] + 280
	10  UIKitCore                           0x00000001133adec4 -[UIApplication _callInitializationDelegatesForMainScene:transitionContext:] + 3979
	11  UIKitCore                           0x00000001133b3527 -[UIApplication _runWithMainScene:transitionContext:completion:] + 1623
	12  UIKitCore                           0x0000000113c55e3e __111-[__UICanvasLifecycleMonitor_Compatability _scheduleFirstCommitForScene:transition:firstActivation:completion:]_block_invoke + 866
	13  UIKitCore                           0x0000000113c52403 +[_UICanvas _enqueuePostSettingUpdateTransactionBlock:] + 153
	14  UIKitCore                           0x0000000113c55a7b -[__UICanvasLifecycleMonitor_Compatability _scheduleFirstCommitForScene:transition:firstActivation:completion:] + 233
	15  UIKitCore                           0x0000000113c56435 -[__UICanvasLifecycleMonitor_Compatability activateEventsOnly:withContext:completion:] + 1085
	16  UIKitCore                           0x0000000113c13b31 __82-[_UIApplicationCanvas _transitionLifecycleStateWithTransitionContext:completion:]_block_invoke + 795
	17  UIKitCore                           0x0000000113c137db -[_UIApplicationCanvas _transitionLifecycleStateWithTransitionContext:completion:] + 435
	18  UIKitCore                           0x0000000113c5892c __125-[_UICanvasLifecycleSettingsDiffAction performActionsForCanvas:withUpdatedScene:settingsDiff:fromSettings:transitionContext:]_block_invoke + 584
	19  UIKitCore                           0x0000000113c59256 _performActionsWithDelayForTransitionContext + 100
	20  UIKitCore                           0x0000000113c5868b -[_UICanvasLifecycleSettingsDiffAction performActionsForCanvas:withUpdatedScene:settingsDiff:fromSettings:transitionContext:] + 221
	21  UIKitCore                           0x0000000113c51aa1 -[_UICanvas scene:didUpdateWithDiff:transitionContext:completion:] + 392
	22  UIKitCore                           0x00000001133b1d46 -[UIApplication workspace:didCreateScene:withTransitionContext:completion:] + 515
	23  UIKitCore                           0x00000001133e3856 -[UIApplicationSceneClientAgent scene:didInitializeWithEvent:completion:] + 357
	24  FrontBoardServices                  0x00000001166aedda -[FBSSceneImpl _didCreateWithTransitionContext:completion:] + 448
	25  FrontBoardServices                  0x00000001166b9f43 __56-[FBSWorkspace client:handleCreateScene:withCompletion:]_block_invoke_2 + 271
	26  FrontBoardServices                  0x00000001166b963a __40-[FBSWorkspace _performDelegateCallOut:]_block_invoke + 53
	27  libdispatch.dylib                   0x000000010c64e63e _dispatch_client_callout + 8
	28  libdispatch.dylib                   0x000000010c651bb4 _dispatch_block_invoke_direct + 301
	29  FrontBoardServices                  0x00000001166ee3c8 __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__ + 30
	30  FrontBoardServices                  0x00000001166ee080 -[FBSSerialQueue _performNext] + 457
	31  FrontBoardServices                  0x00000001166ee660 -[FBSSerialQueue _performNextFromRunLoopSource] + 45
	32  CoreFoundation                      0x000000010ab68b31 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	33  CoreFoundation                      0x000000010ab683a3 __CFRunLoopDoSources0 + 243
	34  CoreFoundation                      0x000000010ab62a4f __CFRunLoopRun + 1263
	35  CoreFoundation                      0x000000010ab62221 CFRunLoopRunSpecific + 625
	36  GraphicsServices                    0x000000010fcd01dd GSEventRunModal + 62
	37  UIKitCore                           0x00000001133b5115 UIApplicationMain + 140
	38  Runner                              0x0000000105f92d84 main + 68
	39  libdyld.dylib                       0x000000010c6c4551 start + 1
)
2018-10-01 16:30:54.489749-0700 Runner[21990:12461272] flutter: Observatory listening on http://127.0.0.1:49397/
libc++abi.dylib: terminating with uncaught exception of type NSException
2018-10-01 16:30:54.404948-0700 Runner[21990:12461249] 5.6.0 - [Firebase/Core][I-COR000003] The default Firebase app has not yet been configured. Add `[FIRApp configure];` (`FirebaseApp.configure()` in Swift) to your application initialization. Read more: https://goo.gl/ctyzm8.
```

Note the helpful error that is only visible in Xcode:

```
could not find a valid GoogleService-Info.plist in your project. Please download one from https://console.firebase.google.com/
```

### Flutter doctor

```
$ flutter doctor -v
[✓] Flutter (Channel beta, v0.8.2, on Mac OS X 10.13.6 17G65, locale en-US)
    • Flutter version 0.8.2 at /Users/filiph/dev/flutter
    • Framework revision 5ab9e70727 (3 weeks ago), 2018-09-07 12:33:05 -0700
    • Engine revision 58a1894a1c
    • Dart version 2.1.0-dev.3.1.flutter-760a9690c2

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/filiph/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.0, Build version 10A255
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 28.0.2
    • Dart plugin version 181.5616
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[!] IntelliJ IDEA Community Edition (version 2018.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[!] VS Code (version 1.22.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected devices (3 available)
    • Pixel 2 XL • 711KPZK0592485                       • android-arm64 • Android 9 (API 28)
    • iPhone X   • A4DBE660-4C39-4AEA-B258-7755F584BA6E • ios           • iOS 12.0 (simulator)
    • iPhone XR  • 431DF6F4-BF91-4E1D-9AF1-8324CF683D37 • ios           • iOS 12.0 (simulator)

! Doctor found issues in 2 categories.

```

**Comment by yathit** [comment] 2018-10-29 13:37
The GoogleService-Info.plist file does exist in the Runner folder, but only after "Add Files... to Runner" in the Xcode by right clicking on the Runner folder does the trick.

**Comment by sergiuiacob1** [comment] 2018-12-29 11:39
Hello! I think this might be related to [25879](https://github.com/flutter/flutter/issues/25879)
You mean all I gotta do is add the `GoogleService-Info.plist` in order to stop receiving the errors?

**Comment by kangwang1988** [comment] 2019-01-05 03:17
@filiph 
```
The GoogleService-Info.plist file does exist in the Runner folder, but only after "Add Files... to Runner" in the Xcode by right clicking on the Runner folder does the trick.
```
Can you try this approach?

**Comment by BuckyBoy6399** [comment] 2019-05-31 07:47
Install the Firebase .plist and .json files and then run the App.
The errors are resolved.

The Codelab should first start with Project setup and configuration and then the creating UI Part

**Comment by ahmadsadeed** [comment] 2019-07-31 06:11
Many tutorials didn't include the GoogleService-Info.plist part. This problem took more than 6 hours for me until I landed to this page. thanks

**Comment by Hemistone** [comment] 2020-01-06 07:51
<img width="380" alt="스크린샷 2020-01-06 16 40 18" src="https://user-images.githubusercontent.com/38800801/71803624-a341f500-30a4-11ea-8fb9-6315e692c5c6.png">
Thank you so much for giving this answer.
I've added what the 'Add Files... to Runner' means for adition

**Comment by jmagman** [comment] 2020-01-22 03:27
Similar to https://github.com/flutter/flutter/issues/19196.

**Comment by jeeali** [comment] 2020-04-09 19:55
I'm getting this error...
Unable to solve this. Please help
App just crashed after installation

```
flutter: getCurrentLocation
flutter: {app_name: , default_tax: null, default_currency: null, currency_right: false, enable_paypal: true, enable_stripe: true, mobile_language: en}
flutter: getCurrentLocation
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff23c7127e __exceptionPreprocess + 350
	1   libobjc.A.dylib                     0x00007fff513fbb20 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff23c710bc +[NSException raise:format:] + 188
	3   location                            0x000000010aeee80c -[LocationPlugin requestPermission] + 460
	4   location                            0x000000010aeeddf9 -[LocationPlugin handleMethodCall:result:] + 2137
	5   Flutter                             0x0000000108bd6f32 __45-[FlutterMethodChannel setMethodCallHandler:]_block_invoke + 104
	6   Flutter                             0x0000000108b65a4e _ZNK7flutter21PlatformMessageRouter21HandlePlatformMess<…>
Lost connection to device.```

**Comment by hyochan** [comment] 2020-04-24 03:24
Same with me as @jeeali. Tried everything. Currently suspecting for regression and trying for different versions.

**Comment by jmagman** [comment] 2020-09-28 19:57
We're going to use this issue to track improving Xcode output, not the `GoogleService-Info.plist` issue specifically.

**Comment by jmagman** [comment] 2020-09-28 21:32
```
xcrun xcodebuild -workspace Runner.xcworkspace -scheme Runner -resultBundlePath ./output
xcrun xcresulttool get --path  /Users/magder/Projects/test_create/ios/output --format json
```
Need to parse `['actions']['_values'][0]['buildResult']['issues']` for `warningSummaries` and `errorSummaries`.

**Comment by xster** [comment] 2020-09-29 05:17
I've been noticing this cluster of issues more recently. Don't know if it's due to an xcode change. The actual error tends to be very unassumingly buried in a wall of text. This likely produces a bunch of red herrings for users. This is a great project to pursue.

**Comment by jmagman** [comment] 2020-12-15 23:49
The errorSummaries are really lacking for errors coming from dart.

This nice compilation error:
```
    /bin/sh -c /Users/magder/Library/Developer/Xcode/DerivedData/Runner-asrszkthjhuqfdcyidwleqxjtniu/Build/Intermediates.noindex/Runner.build/Debug-iphoneos/Runner.build/Script-9740EEB61CF901F6004384FC.sh
lib/gallery/app.dart:141:7: Error: Expected ',' before this.
      model: model,
      ^^^^^
lib/gallery/app.dart:139:38: Error: Too many positional arguments: 0 allowed, but 1 found.
Try removing the extra positional arguments.
    return ScopedModel<AppStateModel>(
                                     ^
../../../../../.pub-cache/git/scoped_model-cc39449cdea9364f574713009ef6d2c40a7d35a7/lib/scoped_model.dart:113:3: Context: Found this candidate, but the arguments don't match.
  ScopedModel({required this.model, required this.child});

Command PhaseScriptExecution failed with a nonzero exit code
```
Is recorded as:
```
            "errorSummaries" : {
              "_type" : {
                "_name" : "Array"
              },
              "_values" : [
                {
                  "_type" : {
                    "_name" : "IssueSummary"
                  },
                  "issueType" : {
                    "_type" : {
                      "_name" : "String"
                    },
                    "_value" : "Uncategorized"
                  },
                  "message" : {
                    "_type" : {
                      "_name" : "String"
                    },
                    "_value" : "Command PhaseScriptExecution failed with a nonzero exit code"
                  }
                }
              ]
            },
```

**Comment by eliabieri** [comment] 2021-01-15 11:39
is there any update on this?

**Closed** 2021-12-21 16:39 UTC
Labels: severe: crash, platform-ios, tool, t: xcode, a: triage improvements, P4
