### ISSUE TITLE
☂️ Add support for ARM macOS as a target

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#60113] opened 2020-06-23 18:04 UTC
Filing as an umbrella bug for the overall feature of building ARM macOS applications. We can add specific sub-issues over time, but at a high level this will involve:
- The necessary Dart support
- Building/uploading engine artifacts in the correct format
- Updating the tool to understand the new target
  - potentially adding new options to control what is being targeted

### Issues
- [ ] https://github.com/flutter/flutter/issues/87508
- [x] https://github.com/flutter/flutter/issues/97681
- [x] https://github.com/flutter/flutter/issues/97977
- [x] https://github.com/flutter/flutter/issues/97978
- [x] https://github.com/flutter/flutter/issues/69221
- [x] https://github.com/flutter/engine/pull/31014
- [x] https://github.com/flutter/flutter/pull/97111
- [x] https://github.com/flutter/flutter/issues/65976
- [x] https://github.com/flutter/flutter/issues/56581
- [x] https://github.com/CocoaPods/CocoaPods/issues/9907

Tracking Apple Silicon as a host device separately at https://github.com/flutter/flutter/issues/60118.

**Comment by alexmarkley** [comment] 2020-09-19 18:34
I would like to propose that we consider two separate macOS targets. (Maybe they should be considered separately enough to justify separate umbrella issues?)

The targets:
- macOS Desktop support, ala: https://flutter.dev/desktop
- iOS-apps-on-macOS, which is a **new** target exclusive to macOS 11 on Apple Silicon: https://github.com/flutter/flutter/issues/66184

In my opinion, the tooling around the second use case is a much higher priority, because it will immediately affect all Flutter projects targeting iOS starting at the end of this year.

I would like to help with this effort, as I have access to the hardware and I'm highly motivated to make my app work correctly on these target(s). I'd be happy to help with anything from testing to writing patches. If the work can be carved up into suitable chunks for the community to help, that would be fantastic. (Right now my biggest hangup is getting my development environment working to build the Dart SDK from source. https://github.com/dart-lang/sdk/issues/43488 If anybody has any ideas for a different starting point, please let me know.)

**Comment by stuartmorgan** [comment] 2020-09-19 20:27
This issue is about the first bullet point; the second is completely unrelated.

> I would like to propose that we consider two separate macOS targets.

What you want is support for a new device for the existing iOS target, not a new target.

**Comment by alexmarkley** [comment] 2020-09-19 21:43
> What you want is support for a new device for the existing iOS target, not a new target.

That seems completely reasonable, and I am inclined to agree with you @stuartmorgan . To clarify, I intended the term 'target' in the classical sense of a toolchain target, not necessarily as it relates to Flutter's or Dart's specific design.

Unless I'm greatly mistaken, it sounds like we are in agreement that these two situations are separate and should be considered separately.

I would be interested in adopting terminology that can be used to unambiguously refer to each of these situations individually, so any suggestions there would be appreciated.

**Comment by stuartmorgan** [comment] 2020-09-19 22:14
> I intended the term 'target' in the classical sense of a toolchain target

But that's not how you were using it, which was my point. There is no new "iOS-apps-on-macOS" toolchain, it's just the iOS toolchain.

> it sounds like we are in agreement that these two situations are separate and should be considered separately

Then hopefully we should also be agreed that the place to discuss the new thing you are requesting is in the issue you filled for it, rather than this completely unrelated issue.

**Comment by alexmarkley** [comment] 2020-09-19 22:43
> Then hopefully we should also be agreed that the place to discuss the new thing you are requesting is in the issue you filled for it, rather than this completely unrelated issue.

@stuartmorgan I'm sorry if my misunderstanding was frustrating. Being new to the project, a plain reading of this issue left me unsure what the point of this issue was.

That said, I'm happy to help with testing of the macOS Desktop support on Apple Silicon. Currently (flutter master from an hour ago), `.app` bundles produced by `flutter build macos` on x86_64 hosts seem to work fine on Apple Silicon under Rosetta.

Additionally, the tooling `flutter run -d macos` runs fine on Apple Silicon, but obviously under Rosetta.

As I'm sure you expected (or if you've tested this yourself, you already know) the problems start when I launch the project in Xcode and ask it to build for 'My Mac', in which case I get the following:

```
error: The linked and embedded framework 'App.framework' is missing one or more architectures required by this target: arm64. (in target 'Runner' from project 'Runner')
error: The linked and embedded framework 'FlutterMacOS.framework' is missing one or more architectures required by this target: arm64. (in target 'Runner' from project 'Runner')
```

My intention here is to be as helpful as possible, while trying to improve and future-proof my own app project(s). I'm new to the Dart and Flutter projects, but I'm interested in learning and contributing as quickly as possible.

Please let me know if there is any way I can assist.

**Comment by GyuriMajercsik** [comment] 2020-11-24 12:59
I'm getting the same error when running `flutter build macos` although I can run the application. 

    ```
 ] error: The linked and embedded framework 'FlutterMacOS.framework' is missing one or more architectures required by this target: arm64. (in target 'Runner' from project 'Runner')
[        ] error: The linked and embedded framework 'App.framework' is missing one or more architectures required by this target: arm64. (in target 'Runner' from project 'Runner')
[    
```

Is there any fix/workaround for this ?

**Comment by arnemolland** [comment] 2020-11-24 15:01
@GyuriMajercsik You can filter out the `arm64` architecture in your Xcode project's build settings.
![screenshot](https://user-images.githubusercontent.com/13465896/100111331-45f69400-2e6e-11eb-8adb-faf0df2a1c0b.png)

**Comment by GyuriMajercsik** [comment] 2020-11-24 15:20
Thanks @arnemolland for the quick reply. I tried this solution but I get the following error: 

```
[   +1 ms] ld: warning: ignoring file /Users/gyuri/tools/flutter/bin/cache/artifacts/engine/darwin-x64-release/FlutterMacOS.framework/FlutterMacOS, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
[        ] Undefined symbols for architecture arm64:
[        ]   "_FlutterMethodNotImplemented", referenced from:
[        ]       -[FLTPackageInfoPlugin handleMethodCall:result:] in FLTPackageInfoPlugin.o
[        ]   "_OBJC_CLASS_$_FlutterMethodChannel", referenced from:
[        ]       objc-class-ref in FLTPackageInfoPlugin.o
[        ] ld: symbol(s) not found for architecture arm64
[        ] clang: error: linker command failed with exit code 1 (use -v to see invocation)
[        ] warning: The macOS deployment target 'MACOSX_DEPLOYMENT_TARGET' is set to 10.6, but the range of supported deployment target versions is 10.9 to 11.0.99. (in target 'nanopb' from project 'Pods')
[        ] warning: The macOS deployment target 'MACOSX_DEPLOYMENT_TARGET' is set to 10.7, but the range of supported deployment target versions is 10.9 to 11.0.99. (in target 'leveldb-library' from project 'Pods')
[        ] warning: The macOS deployment target 'MACOSX_DEPLOYMENT_TARGET' is set to 10.7, but the range of supported deployment target versions is 10.9 to 11.0.99. (in target 'BoringSSL-GRPC' from project 'Pods')
[        ] ** BUILD FAILED **
[        ] The following build commands failed:
[        ]      CompileSwift normal x86_64 /Users/gyuri/tools/flutter/.pub-cache/git/flutter-desktop-embedding-927f8cbc09b35d85245c095f2db8df9b186f6618/plugins/window_size/macos/Classes/WindowSizePlugin.swift
[        ]      CompileSwift normal x86_64 /Users/gyuri/tools/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_macos-0.0.1+9/macos/Classes/UrlLauncherPlugin.swift
[        ]      CompileSwift normal arm64 /Users/gyuri/tools/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_macos-0.0.1+9/macos/Classes/UrlLauncherPlugin.swift
[        ]      CompileSwift normal x86_64 /Users/gyuri/tools/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_macos-0.0.1+11/macos/Classes/SharedPreferencesPlugin.swift
[        ]      CompileSwift normal arm64 /Users/gyuri/tools/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_macos-0.0.1+11/macos/Classes/SharedPreferencesPlugin.swift
[        ]      CompileSwift normal x86_64 /Users/gyuri/tools/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_macos-0.0.4+6/macos/Classes/PathProviderPlugin.swift
[        ]      CompileSwift normal arm64 /Users/gyuri/tools/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_macos-0.0.4+6/macos/Classes/PathProviderPlugin.swift
[        ]      Ld /Users/gyuri/work/m_p/deescus/build/macos/Build/Intermediates.noindex/Pods.build/Release/package_info.build/Objects-normal/arm64/Binary/package_info normal arm64
[        ] (8 failures)
 
```

**Comment by arnemolland** [comment] 2020-11-24 15:40
@GyuriMajercsik  Somehow I'm getting the same issue now (didn't get it a few weeks back). It's related to #69221 and can be solved by settings `ONLY_ACTIVE_ARCH` to `YES`, which is the default for debug builds but not profile/release, hence `flutter run` working but not `flutter build macos`

<img width="447" alt="Screenshot 2020-11-24 at 16 39 12" src="https://user-images.githubusercontent.com/13465896/100116064-97ede880-2e73-11eb-9a88-86287b415d2e.png">

**Comment by GyuriMajercsik** [comment] 2020-11-24 15:51
Yes, I tried that as well but still failing. The build worked for me as well in the past days. It stopped working after upgrading xCode. 

```
/Users/gyuri/work/m_p/deescus/build/macos/Build/Intermediates.noindex/Pods.build/Release/GTMSessionFetcher.build/Objects-normal/x86_64/GTMSessionFetcherLogging.o
[   +3 ms] warning: The macOS deployment target 'MACOSX_DEPLOYMENT_TARGET' is set to 10.6, but the range of supported deployment target versions is 10.9 to 11.0.99. (in target 'nanopb' from project 'Pods')
[        ] warning: The macOS deployment target 'MACOSX_DEPLOYMENT_TARGET' is set to 10.7, but the range of supported deployment target versions is 10.9 to 11.0.99. (in target 'BoringSSL-GRPC' from project 'Pods')
[        ] warning: The macOS deployment target 'MACOSX_DEPLOYMENT_TARGET' is set to 10.7, but the range of supported deployment target versions is 10.9 to 11.0.99. (in target 'leveldb-library' from project 'Pods')
[        ] ** BUILD FAILED **
[        ] The following build commands failed:
[        ]      CompileSwift normal arm64 /Users/gyuri/tools/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_macos-0.0.1+9/macos/Classes/UrlLauncherPlugin.swift
[        ]      CompileSwift normal arm64 /Users/gyuri/tools/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_macos-0.0.1+11/macos/Classes/SharedPreferencesPlugin.swift
[        ]      CompileSwift normal x86_64 /Users/gyuri/tools/flutter/.pub-cache/git/flutter-desktop-embedding-927f8cbc09b35d85245c095f2db8df9b186f6618/plugins/window_size/macos/Classes/WindowSizePlugin.swift
[        ]      CompileSwift normal x86_64 /Users/gyuri/tools/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_macos-0.0.1+11/macos/Classes/SharedPreferencesPlugin.swift
[        ]      CompileSwift normal x86_64 /Users/gyuri/tools/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_macos-0.0.1+9/macos/Classes/UrlLauncherPlugin.swift
[        ]      CompileSwift normal x86_64 /Users/gyuri/tools/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_macos-0.0.4+6/macos/Classes/PathProviderPlugin.swift
[        ]      CompileSwift normal arm64 /Users/gyuri/tools/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_macos-0.0.4+6/macos/Classes/PathProviderPlugin.swift
[        ]      Ld /Users/gyuri/work/m_p/deescus/build/macos/Build/Intermediates.noindex/Pods.build/Release/package_info.build/Objects-normal/arm64/Binary/package_info normal arm64
[        ]      CompileSwift normal x86_64 /Users/gyuri/tools/flutter/.pub-cache/hosted/pub.dartlang.org/file_chooser-0.1.6/macos/Classes/FileChooserPlugin.swift
[        ]      CompileSwift normal arm64 /Users/gyuri/tools/flutter/.pub-cache/hosted/pub.dartlang.org/file_chooser-0.1.6/macos/Classes/FileChooserPlugin.swift
[        ] (10 failures)
[   +1 ms] Building macOS application... (completed in 7.6s)
[   +2 ms] "flutter macos" took 11,792ms.
[   +3 ms] Build process failed

```

**Comment by arnemolland** [comment] 2020-11-24 16:04
@GyuriMajercsik Try running `pod deintegrate` followed by `flutter pub get` and `pod install` again.

**Comment by GyuriMajercsik** [comment] 2020-11-24 16:09
@arnemolland , the same error appears.

**Comment by jmagman** [comment] 2020-11-24 18:09
@arnemolland @GyuriMajercsik You are hitting https://github.com/flutter/flutter/issues/70566. https://github.com/flutter/flutter/pull/70649 is available on [1.24.0-10.2.pre](https://flutter.dev/docs/development/tools/sdk/releases?tab=macos), which is currently on the master, dev, or beta [channels](https://github.com/flutter/flutter/wiki/Flutter-build-release-channels#how-to-change-channels).  

Please file new issues and completely fill out the template when you run into build problems or bugs so they can be triaged, deduplicated, and the right people can take a look.

**Comment by xster** [comment] 2020-12-03 17:22
FWIW, on Xcode 12.2, the ARCHS_STANDARD includes Apple Silicon, which makes the default template unshippable without opening and editing in Xcode. 

![Screen Shot 2020-12-03 at 9 19 56 AM](https://user-images.githubusercontent.com/156888/101064324-b70e0980-3548-11eb-905e-545a270b1cdb.png)

You guys should decide whether to change the default template and change it back later. Or muck with it in the tool in the meantime.

**Comment by jmagman** [comment] 2020-12-03 18:23
@xster check out https://github.com/flutter/flutter/issues/70566.  I mucked with it in the tool in https://github.com/flutter/flutter/pull/70649, but it doesn't help with the Xcode case, as you say.

**Comment by xster** [comment] 2020-12-03 18:37
Aha! I was wondering why `flutter build macos --release` worked. Awesome addition. 

Maybe we should just add a note in https://flutter.dev/desktop#macos to say when ready, run `flutter build macos --distribution` or `flutter build xcarchive` like iOS instead of archiving in Xcode, then open /.../x.xcarchive instead.

**Comment by jmagman** [comment] 2020-12-03 19:35
@xster File https://github.com/flutter/flutter/issues/71674

**Comment by nilsreichardt** [comment] 2021-03-10 16:16
@pratikbaid3 Can you create a new issue?

**Comment by knopp** [comment] 2021-04-23 19:55
So I was playing with this a bit. Engine now can cross compile to darwin-arm64 (requires changing target arch in args.gn and disabling unit tests).  With some [changes to flutter_tool](https://github.com/knopp/flutter/commits/tool_mac_arm64) I was able to get `flutter assemble` produce arm64 artifacts for both debug and release. Release/AOT works without issues, debug crashes because Flutter [disables memory protection](https://github.com/flutter/engine/blob/master/runtime/dart_vm.cc#L334-L339), which is not supported on M1. After removing the `--no_write_protect_code` flag debug/jit works as expected.

**Comment by jmagman** [comment] 2021-04-23 20:29
> With some [changes to flutter_tool](https://github.com/knopp/flutter/commits/tool_mac_arm64) I was able to get `flutter assemble` produce arm64 artifacts for both debug and release. Release/AOT works without issues, debug crashes because Flutter [disables memory protection](https://github.com/flutter/engine/blob/master/runtime/dart_vm.cc#L334-L339), which is not supported on M1. After removing the `--no_write_protect_code` flag debug/jit works as expected as well.

@knopp Thanks for your investigation!  Would you mind filing two new issues: one for the tool change and other for the engine change, and I'll add them to be tracked with this umbrella issue?  It looks like you already did most of the non-test changes needed for the tool, and I'd like the engine team to be kept in the loop on the jit crash.

**Comment by zzterrozz** [comment] 2021-06-23 04:20
Struggling for hours with this issue to run the iOS simulator on Apple Silicon M1.
None of the proposition above is working on my project.
Anyone has a clean and easy solution please?

**Comment by jmagman** [comment] 2021-06-23 17:29
@zzterrozz This is an umbrella issue tracking getting macOS desktop apps to run natively.  If you are hitting a bug with the iOS simulator, please file a new issue and completely fill out the template.  Attach the full output of a `flutter run` or `flutter build` run with the `--verbose` flag.

**Comment by mahamat-ali** [comment] 2021-09-21 20:22
Y

**Comment by rafalglowacz** [comment] 2021-12-29 11:47
I've run into a problem on an M1 Mac Mini. Running `Process.run` in a loop causes the desktop app in debug mode to freeze after a few iterations - sometimes just 1, sometimes 5 or so. I use `await Future<dynamic>.delayed(...)` to ensure some interval between the calls. The call itself can be something as simple as `whoami`.

Should I create a separate issue?

**Comment by knopp** [comment] 2021-12-29 11:49
> I've run into a problem on an M1 Mac. Running `Process.run` in a loop causes the desktop app in debug mode to freeze after a few iterations - sometimes just 1, sometimes 5 or so. I use `await Future<dynamic>.delayed(...)` to ensure some interval between the calls. The call itself can be something as simple as `whoami`.
> 
> Should I create a separate issue?

Definitely. With a minimal example to reproduce the problem ideally.

**Comment by d9j** [comment] 2022-01-25 04:08
i know it's offtopic. but i never been able to make debugging on emulator work well with flutter attach.. since it seems only option if integrate flutter as part of existing native project.
 you guys seem have fiffrent priorities but such problems turning me off using flutter for anything serious. total joke

**Comment by jmagman** [comment] 2022-01-25 04:20
@d9j Please review our code of conduct. https://github.com/flutter/flutter/blob/master/CODE_OF_CONDUCT.md

**Comment by zanderso** [comment] 2022-02-02 23:28
@jmagman @knopp Following https://github.com/flutter/flutter/pull/97671 and https://flutter-review.googlesource.com/c/recipes/+/26040, `FlutterMacOS.framework` contains the lipo'd x64 and arm64 engine dylib, and two new `gen_snapshot` binaries as follows:
- `bin/cache/artifacts/engine/darwin-x64/gen_snapshot_x64`
- `bin/cache/artifacts/engine/darwin-x64/gen_snapshot_arm64`
- `bin/cache/artifacts/engine/darwin-x64-profile/gen_snapshot_x64`
- `bin/cache/artifacts/engine/darwin-x64-profile/gen_snapshot_arm64`
- `bin/cache/artifacts/engine/darwin-x64-release/gen_snapshot_x64`
- `bin/cache/artifacts/engine/darwin-x64-release/gen_snapshot_arm64`
The tool should switch to using those `gen_snapshot`s, and then we can remove the `gen_snapshot` that's still there that doesn't have a suffix that specifies the architecture.

**Comment by jmagman** [comment] 2022-02-02 23:49
> The tool should switch to using those `gen_snapshot`s

Filed https://github.com/flutter/flutter/issues/97681

**Comment by cbracken** [comment] 2022-03-17 20:17
As of https://github.com/flutter/flutter/pull/100271, we should be building macOS universal binary apps by default on master branch.

**Comment by jmagman** [comment] 2022-05-03 21:52
Closing as complete.  The remaining testing work is being tracked in https://github.com/flutter/flutter/issues/87508.

**Closed by jmagman** 2022-05-03 21:52 UTC
Labels: new feature, tool, engine, platform-mac, customer: crowd, a: desktop, a: build, passed first triage, P3, platform-target-arm
