### ISSUE TITLE
Stable documentation contains widgets that do not appear in the stable channel

### ISSUE THREAD

**Issue by unique-cloud** [flutter/flutter#118161] opened 2023-01-08 20:32 UTC
The example on the 'FilledButton' widget documentation page doesn't compile:

https://api.flutter.dev/flutter/material/FilledButton-class.html

See the error got from the console: Error: Couldn't find constructor 'FilledButton'.

I cannot find and use it in my local IDE either.

Is 'FilledButton' deprecated? I'm new to Flutter so please bother me if I missed anything. Thanks!

**Comment by faizank09855** [comment] 2023-01-08 20:47
**```
if you are using flutter Latest SDK version then it will throw error .
try Icon Button or Elevated Button instead of Filled Button or Downgrade your Flutter Sdk
```**

**Comment by faizank09855** [comment] 2023-01-08 20:48
```
**if you are using flutter Latest SDK version then it will throw error .
try Icon Button or Elevated Button instead of Filled Button or Downgrade your Flutter Sdk**
```

**Comment by faizank09855** [comment] 2023-01-08 20:48
if you are using flutter Latest SDK version then it will throw error .
try Icon Button or Elevated Button instead of Filled Button or Downgrade your Flutter SDK version

**Comment by exaby73** [comment] 2023-01-09 10:12
Hello @unique-cloud. Looks like an issue with the deployment of the docs. It may be caused by https://github.com/flutter/flutter/commit/135454af32, but I cannot be certain. 

cc: @godofredoc

**Comment by godofredoc** [comment] 2023-01-09 16:12
Documentation is in sync with 3.3.10. @domesticmouse @gspencergoog is this by any chance caused by cherry-picks to the stable channel or maybe we missed a CP to the doc's script?

**Comment by gspencergoog** [comment] 2023-01-09 17:51
Something is definitely odd here.  `FilledButton` (packages/flutter/lib/src/material/filled_button.dart) doesn't exist in the stable branch, yet seems to appear in the stable documentation.  When I build documentation in my local stable branch, it doesn't generate a page for `FilledButton` (because the source file doesn't exist). `FilledButton` was added in 5454bab6c193b850926fa4033aae7b16d3998af7, which *does* (strangely) appear in the git log for 3.3.10. It appears to have been deleted in 39a9ed572151bb82c9cc6c16f5ddd2639635395f.  I suspect that this has something to do with the way docs are built for stable: We're just modifying the master docs that were built for the original stable branch, not for the branch with all the CPs applied, perhaps?  I didn't track down where the add/delete was merged into the stable branch, but it clearly was at some point.

**Comment by danagbemava-nc** [comment] 2023-01-10 08:10
We have another instance of this reported in https://github.com/flutter/flutter/issues/118227. The widget in question is `AnimatedGrid`.

**Comment by godofredoc** [comment] 2023-01-12 04:27
This was a problem during the migration of docs generation/publishing to different infrastructure. I'll fix the docs tomorrow morning PST time.

**Comment by TahaTesser** [comment] 2023-01-19 20:29
We have a bunch of new reports.

cc: @godofredoc

**Comment by godofredoc** [comment] 2023-01-23 20:27
@gspencergoog @TahaTesser can you please take a look if the issue has been fixed?

**Comment by gspencergoog** [comment] 2023-01-23 21:59
As far as I can tell, this appears to be fixed, but if there are specific instances of this, we should investigate them.

**Comment by TahaTesser** [comment] 2023-01-24 08:44
@godofredoc 
I verified all the previously reported API pages; this is fixed. I'll reopen this if we see any new reports.
Closing this as fixed.

**Closed by TahaTesser** 2023-01-24 08:44 UTC
Labels: d: api docs, documentation, team: infra, passed secondary triage, P1, found in release: 3.3
