### ISSUE TITLE
"camera" package does not initializes the camera in ANDROID 13

### ISSUE THREAD

**Issue by modegargar2-1** [flutter/flutter#119406] opened 2023-01-28 08:52 UTC
I am trying to use the camera package to provide the camera like features in my flutter application. i.e. Show Realtime preview from camera, capture image, etc. 

The issue I am facing is that whenever I open the page which contains the camera controller, it throws following exception.

 [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: CameraException(error, Attempt to invoke virtual method 'int android.media.EncoderProfiles$VideoProfile.getWidth()' on a null object reference)
E/flutter (14829): #0      AndroidCamera.createCamera (package:camera_android/src/android_camera.dart:112)
E/flutter (14829): <asynchronous suspension>
E/flutter (14829): #1      CameraController.initialize (package:camera/src/camera_controller.dart:291)
E/flutter (14829): <asynchronous suspension>

This only happens in Android 13 devices. In other android versions it works perfectly fine. I tried reinitializing on error but it goes into recurring loop which never stops.

To reproduce this bug follow this steps
1. Create a flutter project for android
2. add the camera package from here 
    https://pub.dev/packages/camera
3. use the plugin in any way possible, for starters try example code.
4. build and run on any Android 13 device

**Comment by danagbemava-nc** [comment] 2023-01-30 07:35
Duplicate of https://github.com/flutter/flutter/issues/109769

**Closed by danagbemava-nc** 2023-01-30 07:35 UTC
Labels: in triage
