### ISSUE TITLE
Flutter web Seo unfriendly

### ISSUE THREAD

**Issue by 369235109** [flutter/flutter#82093] opened 2021-05-08 06:38 UTC
Dear Flutter Team,
I just want to know whether you have SEO on your priority or not. If yes, what is the timeline?
Flutter is too good a framework to let go just because of this drawback. 
This will greatly help make decisions.
Sorry for a bit harsh lines. 

I also found that some developers have some suitable solutions. Can you share the methods with me? Our project is in urgent need of commercialization

Thanks,

**Comment by iapicca** [comment] 2021-05-08 09:23
duplicate of https://github.com/flutter/flutter/issues/46789

**Closed** 2021-05-10 02:08 UTC
