### ISSUE TITLE
Blank Space above keyboard when resizeToAvoidBottomPadding is true on Samsung Note 10

### ISSUE THREAD

**Issue by MahmoodBakhshayesh** [flutter/flutter#76005] opened 2021-02-14 14:36 UTC
I have a TextField when i set the property of resizeToAvoidBottomPadding in scaffold as True when the keyboard is opened there is a space between keyboard and page content which i believe is part of scaffold but not part of body. because the color of the space is same as backgroundColor of scaffold.

i have this problem only on Samsung note 10

![Before Focus TextField](https://user-images.githubusercontent.com/38631695/107879622-26ac5780-6eef-11eb-8daa-87a39f7986fd.jpeg)
![After Focus TextField](https://user-images.githubusercontent.com/38631695/107879617-23b16700-6eef-11eb-887e-e6acb4ce9ced.jpeg)

**Comment by TahaTesser** [comment] 2021-02-15 08:31
Hi @MahmoodBakhshayesh 
Looks like a duplicate of https://github.com/flutter/flutter/issues/73752
Can you also reproduce it without `resizeToAvoidBottomPadding`  or try this code sample below

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(title: const Text("Keyboard  demo")),
        body: Container(
          color: Colors.red,
          margin: EdgeInsets.only(
              top: 600 - MediaQuery.of(context).viewInsets.bottom),
          child: Column(
            children: [
              const Padding(
                padding: EdgeInsets.all(16),
                child: TextField(
                  decoration: InputDecoration(
                    hintText: "Tap me!",
                    fillColor: Colors.white,
                    filled: true,
                    border: OutlineInputBorder(),
                  ),
                ),
              )
            ],
          ),
        ));
  }
}
```

</details>

Can you please provide your `flutter doctor -v` 
Thank you

**Comment by pedromassangocode** [comment] 2021-03-12 14:03
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2021-03-12 14:03 UTC
Labels: in triage, waiting for customer response

**Comment by MahmoodBakhshayesh** [comment] 2021-04-22 10:30
i guess it happens when you disable phone default bottom keys (back button and etc.) some new phones like note10 has this option
