### ISSUE TITLE
Gallery Shrine demo scrolling performance has regressed

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#8589] opened 2017-03-06 19:40 UTC
Scrolling the shrine demo's home page on a Nexus 5x has become jittery.  Pesto has the same problem.

Here's a video: https://youtu.be/NQZwnt3uoaU

**Comment by eseidelGoogle** [comment] 2017-03-07 16:58
@HansMuller suggested just now this might be a bad enough regression that we need to consider changing the branch point?  FYI @cbracken

**Comment by chinmaygarde** [comment] 2017-03-07 20:30
Is this after the updates related to the [PhysicalModelLayer](https://github.com/flutter/engine/blob/be5d971aa7641f43819e5305f6ca892dcc0a00e8/flow/layers/physical_model_layer.h)? cc @jason-simmons might know what is happening. Or I can take a look at it too.

**Comment by HansMuller** [comment] 2017-03-07 21:12
I haven't tried to figure out when these regressions were introduced (not yet); @jason-simmons  isn't around.

**Comment by HansMuller** [comment] 2017-03-08 00:42
The Card shadow problem was introduced by https://github.com/flutter/flutter/pull/8471.

I'm going to split that into a separate bug. I have a  commit that undoes the dependency on the new shadow rendering code.

**Comment by HansMuller** [comment] 2017-03-08 00:53
Note also, just FTR: not rendering the cards' shadows doesn't have an impact on scrolling performance.

**Comment by HansMuller** [comment] 2017-03-08 20:13
I have found it difficult to pin the origin (commit) of this problem.

The scrolling jitter is quite distracting in debug mode. @Hixie has pointed out that this is likely to the N^2 cost of assertions.

In release mode the problem is between subtle and intermittent.  We'll probably need a better test case before pursuing it further.

**Comment by sethladd** [comment] 2017-03-17 20:38
If I scroll really fast on Shrine, after release build on Nexus 5, I get 26.6 fps. Not sure if that's a regression?  (the version of the gallery on the play store doesn't have the "Performance Overlay", so I can't do a direct comparison)

**Comment by sethladd** [comment] 2017-03-29 18:21
I'm going to optimistically close this, because recent builds of the gallery seem to be on par (very subjective) with our previously published gallery.

**Closed by sethladd** 2017-03-29 18:21 UTC
Labels: customer: gallery, performance
