### ISSUE TITLE
NPE when get instance in main function

### ISSUE THREAD

**Issue by asdfv** [flutter/flutter#83011] opened 2021-05-20 12:26 UTC
## Steps to Reproduce

1. Start new flutter project from Android Studio (this about Counter)
2. Add to dependencies `shared_preferences: 2.0.5`and do `flutter pub get`
3. Add this `final prefs = await SharedPreferences.getInstance();` line before `runApp(MyApp());` and add `async` after `main()`
4. Run project on emulator Android Pixel 4 API 30 (or other)

Expected: app starts without errors in logs
Actual: white screen and error in logs (see below)

## Code
```dart
void main() async {
  final prefs = await SharedPreferences.getInstance();
  runApp(MyApp());
}
```

## Logs
<details>
<summary>Logs</summary>

```
[ +826 ms] E/flutter (10629): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: Null check operator used on a null value
[        ] E/flutter (10629): #0      MethodChannel.binaryMessenger (package:flutter/src/services/platform_channel.dart:142:86)
[        ] E/flutter (10629): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:148:36)
[        ] E/flutter (10629): #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:331:12)
[        ] E/flutter (10629): #3      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:358:49)
[        ] E/flutter (10629): #4      MethodChannelSharedPreferencesStore.getAll (package:shared_preferences_platform_interface/method_channel_shared_preferences.dart:44:25)
[        ] E/flutter (10629): #5      SharedPreferences._getSharedPreferencesMap (package:shared_preferences/shared_preferences.dart:181:57)
[        ] E/flutter (10629): #6      SharedPreferences.getInstance (package:shared_preferences/shared_preferences.dart:57:19)
[        ] E/flutter (10629): #7      main (package:flutter_test_shared_prefs/main.dart:5:41)
[        ] E/flutter (10629): #8      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:142:25)
[        ] E/flutter (10629): #9      _rootRun (dart:async/zone.dart:1354:13)
[        ] E/flutter (10629): #10     _CustomZone.run (dart:async/zone.dart:1258:19)
[        ] E/flutter (10629): #11     _runZoned (dart:async/zone.dart:1789:10)
[        ] E/flutter (10629): #12     runZonedGuarded (dart:async/zone.dart:1777:12)
[        ] E/flutter (10629): #13     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:138:5)
[        ] E/flutter (10629): #14     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:283:19)
[        ] E/flutter (10629): #15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

```
[✓] Flutter (Channel beta, 2.2.0-10.2.pre, on Mac OS X 10.15.7 19H2 darwin-x64, locale en-BY)
    • Flutter version 2.2.0-10.2.pre at /Users/vasili_shkleinik/Tools/flutter
    • Framework revision b5017bf8de (3 weeks ago), 2021-04-28 17:09:53 -0700
    • Engine revision 91ed51e05c
    • Dart version 2.13.0 (build 2.13.0-211.13.beta)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/vasili_shkleinik/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Users/vasili_shkleinik/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7351085/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 4.2)
    • Android Studio at /Users/vasili_shkleinik/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7351085/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.1.1)
    • IntelliJ at /Users/vasili_shkleinik/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.56.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (1 available)
    • sdk gphone x86 64 arm64 (mobile) • emulator-5554 • android-x64 • Android 11 (API 30) (emulator)

! Doctor found issues in 2 categories.

```

</details>

**Comment by stuartmorgan** [comment] 2021-05-20 14:49
Duplicate of https://github.com/flutter/flutter/issues/78028.

**Closed by stuartmorgan** 2021-05-20 14:49 UTC
