### ISSUE TITLE
Missing icons at stable branch

### ISSUE THREAD

**Issue by yoniker** [flutter/flutter#98334] opened 2022-02-12 15:35 UTC
## Steps to Reproduce

Copy and paste the sample minimal code to  https://dartpad.dev/ (or your favorite IDE,with flutter stable branch)

**Actual results:** 
A sword icon is shown. Or nothing. But not Apple's icon.

<details>
<summary>Code sample</summary>

```import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const ShowAppleIconScreen(),
    );
  }
}

class ShowAppleIconScreen extends StatefulWidget {
  static String routeName = '/birthday_onboarding';

  const ShowAppleIconScreen({Key? key}) : super(key: key);

  @override
  _ShowAppleIconScreenState createState() =>
      _ShowAppleIconScreenState();
}

class _ShowAppleIconScreenState extends State<ShowAppleIconScreen> {


  @override
  Widget build(BuildContext context) {

    return SafeArea(
      child: Scaffold(
        body: Icon(Icons.apple)
      ),
    );
  }
}
```

</details>

<details>
  <summary>Logs</summary>

```
The output is clearly irrelevant as the issue can be reproduced at dartpad.
```

</details>
Additional details:
This issue also manifests itself as "Codepoint 983768 not found in font, aborting." for many different codepoints when trying to build the app via flutter build apk, at the stable branch.

In master for some reason it does work (but then there are other,more serious, issues).
Need to remove unsupported codepoints, or clarify what's going on at documentation or here.
Previous issues (for example [#64334](https://github.com/flutter/flutter/issues/64334)) concluded in a "switch to a different branch" or "--no-tree-shake-icons" patchy/hacky "solutions".

**Comment by danagbemava-nc** [comment] 2022-02-14 08:29
Duplicate of #97767

**Closed by danagbemava-nc** 2022-02-14 08:29 UTC
Labels: in triage
