### ISSUE TITLE
window onClose event for flutter desktop windows platform.

### ISSUE THREAD

**Issue by Ali-Fadaei** [flutter/flutter#77059] opened 2021-03-02 12:46 UTC
I have to open alertDialog for app exit confirmation when the client attempt to close flutter app window in windows! is there any solution for this?  if not, please add some events to control app window buttons behaviour.

**Comment by stuartmorgan** [comment] 2021-03-02 12:50
Duplicate of https://github.com/flutter/flutter/issues/30735

(Currently you'd need to do this manually with native code and a method channel.)

**Closed by stuartmorgan** 2021-03-02 12:50 UTC
