### ISSUE TITLE
NestedScrollCoordinator: The method '>' was called on null

### ISSUE THREAD

**Issue by JonasJW** [flutter/flutter#28351] opened 2019-02-22 21:11 UTC
I get his Exception occasionally when opening the app:

```
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (19651): The following NoSuchMethodError was thrown building Builder(dirty):
I/flutter (19651): The method '>' was called on null.
I/flutter (19651): Receiver: null
I/flutter (19651): Tried calling: >()
I/flutter (19651):
I/flutter (19651): When the exception was thrown, this was the stack:
I/flutter (19651): #0      _NestedScrollCoordinator.get:hasScrolledBody (package:flutter/src/widgets/nested_scroll_view.dart:493)
I/flutter (19651): #1      _NestedScrollViewState.build.<anonymous closure> (package:flutter/src/widgets/nested_scroll_view.dart:339)
I/flutter (19651): #2      Builder.build (package:flutter/src/widgets/basic.dart:5736)
I/flutter (19651): #3      StatelessElement.build (package:flutter/src/widgets/framework.dart:3774)
I/flutter (19651): #4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3721)
I/flutter (19651): #5      Element.rebuild (package:flutter/src/widgets/framework.dart:3547)
I/flutter (19651): #6      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2286)
I/flutter (19651): #7      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:676)
I/flutter (19651): #8      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:219)
I/flutter (19651): #9      _RenderingFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990)
I/flutter (19651): #10     _RenderingFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930)
I/flutter (19651): #11     _RenderingFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:751)
I/flutter (19651): #13     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382)
I/flutter (19651): #14     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416)
I/flutter (19651): #15     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171)
I/flutter (19651): (elided one frame from package dart:async)
I/flutter (19651): ════════════════════════════════════════════════════════════════════════════════════════════════════
```
I can't seem to figure out a pattern when it happens, all I have is this Exception that doesn't really tells me much, so I decided to post it here in hope that someone might know what this could cause.

```
[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.14.3 18D109, locale de-DE)
    • Flutter version 1.0.0 at /Users/jonas/flutter
    • Framework revision 5391447fae (3 months ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/jonas/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/jonas/Library/Android/sdk
    • Java binary at: /Library/Java/JavaVirtualMachines/jdk1.8.0_192.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_192-b12)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[!] Android Studio
    • Android Studio at /Applications/Android/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    ✗ Android Studio not found at /Applications/Android/Contents
    • Try updating or re-installing Android Studio.

[!] IntelliJ IDEA Community Edition (version 2018.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

! Doctor found issues in 2 categories.
```

**Comment by unmaskedd** [comment] 2019-03-20 18:22
Got this error too, but only running in release its wierd

**Comment by JonasJW** [comment] 2019-03-21 09:09
@unmaskedd I'm currently using CustomScrollView with SliverAppBar and SliverList instead of NestedScrollView to avoid this error

**Comment by x4080** [comment] 2019-04-19 00:09
Hi, suddenly I got this error also, but I tracked down something that's seems unrelated, in my build widget, I add     if (MediaQuery.of(context).size.width > 600) maxwidth = 200;

And it will crash maybe 4 out of 5, if I disable that line it works 5/5, are you somehow using MediaQuery too ?

**Comment by x4080** [comment] 2019-04-19 23:54
Ok, temporarily patch the file works 

```
  bool get hasScrolledBody {
    for (_NestedScrollPosition position in _innerPositions) {
      if (position.minScrollExtent==null) return true; // patch here

      if (position.pixels > position.minScrollExtent)
        return true;
    }
    return false;
  }
```

**Comment by cppanda** [comment] 2019-04-24 17:37
@x4080 Thank you so much that fixed it for me, this cost me more hours of trouble than I care to admit (also nightmares).

The following may be relevant:

- This error was occuring for me sporadically every 5-10 launches.

- It only occured when using the back button to leave the app and then starting it up again. It never occured when the app was left open in the background and reopened. It also never occured on clean launches when it was not already in the background.

- Flutter (Channel stable, v1.2.1, on Microsoft Windows [Version 10.0.17763.437], locale en-AT), although it also happend with a previous release

- My Widget Hierarchy: MaterialApp -> MaterialPageRoute -> Scaffold -> NestedScrollView

**Comment by x4080** [comment] 2019-04-30 03:42
@cppanda , I think its because in release mode somehow, the value is not initialized properly (not like in debug mode) - and I think its random because if it is too fast to reach that point,  the value is not initialized properly
Dont know why :)

**Comment by saileshbro** [comment] 2019-05-29 15:35
I got the same error. NestedScrollView contains SingleChildScrollView and gives the same error. i tried the above solutiom and i am not sure where to include the method. can you help me?

**Comment by x4080** [comment] 2019-06-06 05:06
@dnfield Is this problem solved ?

**Comment by dnfield** [comment] 2019-06-06 14:24
On master, yes

**Comment by x4080** [comment] 2019-06-08 00:18
@dnfield  Allright !

**Comment by dnfield** [comment] 2019-06-08 00:33
Unfortunately the fix for this had to be reverted as it broke something else.

**Comment by x4080** [comment] 2019-06-09 04:14
Oh well

**Comment by CocoaZX** [comment] 2019-07-15 05:28
So, how can I do right now?

**Comment by tony123S** [comment] 2020-01-20 05:39
It happened on `SingleChildScrollView` too.

**Comment by alon710** [comment] 2020-04-03 10:48
You should consider wrapping the ListView widget with Extended one.

**Comment by VladyslavBondarenko** [comment] 2020-04-06 13:44
Does the issue persist? I can't reproduce it with `dev v1.18.0` running in release mode on Android 9

<details>
 <summary>with that code</summary>

```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {

  var _tabs = ['tab1', 'tab2'];

  @override
  Widget build(BuildContext context) {

    print(MediaQuery.of(context).size.width);

    return Scaffold(
      body: DefaultTabController(
        length: _tabs.length,
        child: NestedScrollView(
          headerSliverBuilder: (BuildContext context, bool innerBoxIsScrolled) {
            return <Widget>[
              SliverOverlapAbsorber(
                handle: NestedScrollView.sliverOverlapAbsorberHandleFor(context),
                sliver: SliverAppBar(
                  title: const Text('Books'),
                  pinned: true,
                  expandedHeight: 150.0,
                  forceElevated: innerBoxIsScrolled,
                  bottom: TabBar(
                    tabs: _tabs.map((String name) => Tab(text: name)).toList(),
                  ),
                ),
              ),
            ];
          },
          body: TabBarView(
            children: _tabs.map((String name) {
              return SafeArea(
                top: false,
                bottom: false,
                child: Container(
                  color: Colors.white,
                  child: Builder(
                    builder: (BuildContext context) {
                      return CustomScrollView(
                        key: PageStorageKey<String>(name),
                        slivers: <Widget>[
                          SliverOverlapInjector(
                            handle: NestedScrollView.sliverOverlapAbsorberHandleFor(context),
                          ),
                          SliverPadding(
                            padding: const EdgeInsets.all(8.0),
                            sliver: SliverFixedExtentList(
                              itemExtent: 48.0,
                              delegate: SliverChildBuilderDelegate(
                                    (BuildContext context, int index) {
                                  return ListTile(
                                    title: Text('Item $index'),
                                  );
                                },
                                childCount: 30,
                              ),
                            ),
                          ),
                        ],
                      );
                    },
                  ),
                ),
              );
            }).toList(),
          ),
        ),
      ),
    );
  }
}
```

</details>

**Comment by chunhtai** [comment] 2020-05-29 19:21
this should be fix with https://github.com/flutter/flutter/commit/57d714ebb8

**Closed by chunhtai** 2020-05-29 19:21 UTC
Labels: P4, f: scrolling, framework, severe: crash
