### ISSUE TITLE
How to span rows in DataTable / DataCell?

### ISSUE THREAD

**Issue by pepie** [flutter/flutter#19745] opened 2018-07-25 05:37 UTC
Hello.

Working on a scheduler (calendar week view w/ side-by-side events by time) and am considering using a DataTable to display the activities. 

Is it possible to span multiple rows in a TableCell?
See [Scheduler](https://calendar.teamup.com/wp-content/uploads/2016/03/Staff-Schedule-Scheduler-View.jpg)

Is there a better approach to this?

**Comment by zoechi** [comment] 2018-07-25 05:57
@HansMuller

**Comment by pepie** [comment] 2018-07-30 06:08
@zoechi @HansMuller Hey guys, I was wondering if you had any advice on this.

**Comment by zoechi** [comment] 2019-01-28 20:08
Duplicate of #21594 (has more upvotes)

**Closed by zoechi** 2019-01-28 20:08 UTC
Labels: f: material design, framework, severe: new feature
