### ISSUE TITLE
cannot find symbol import io.flutter.plugins.videoplayer.VideoPlayerPlugin;

### ISSUE THREAD

**Issue by eltonmorais** [flutter/flutter#27287] opened 2019-01-30 10:33 UTC
Once I put the code on dependencies and try to build, I receive the error:
```
cannot find symbol
import io.flutter.plugins.videoplayer.VideoPlayerPlugin;
```

**Comment by eltonmorais** [comment] 2019-01-30 13:24
I just insert the dependencie line on the yaml file, and then try to compile the APP. Just that. And I receive the error. Have that issue with SEVERAL PLUGINS. Everyone for Video/Youtube, and everyone for Webview. Pasting the complete error bellow.

Other plugins Where I had exactly the same error:

flutter_native_web 1.0.2
flutter_inappbrowser 0.5.51
interactive_webview 0.1.1+8
webview_flutter 0.3.0
flutter_webview_plugin 0.3.0+2


`2 errors
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Get more help at https://help.gradle.org
BUILD FAILED in 4s
Gradle task assembleDebug failed with exit code 1
Exited (sigterm)`

**Comment by zoechi** [comment] 2019-01-30 13:33
The error output doesn't provide any information. Was there not more?

**Comment by eltonmorais** [comment] 2019-01-30 14:25
```
* Get more help at https://help.gradle.org
BUILD FAILED in 25s
Gradle task assembleDebug failed with exit code 1
Exited (sigterm)
```

**Comment by zoechi** [comment] 2019-01-30 14:32
Is this a new project or a project that you initially created with an older Flutter version?

**Comment by zoechi** [comment] 2019-01-30 14:33
Duplicate of #27128

**Comment by zoechi** [comment] 2019-01-30 14:33
Please check https://pub.dartlang.org/packages/video_player#-changelog-tab-

**Closed by zoechi** 2019-01-30 14:33 UTC
