### ISSUE TITLE
[tool_crash] WipError -32000 Cannot find context with specified id

### ISSUE THREAD

**Issue by Andreas02-dev** [flutter/flutter#84468] opened 2021-06-11 21:54 UTC
## Command
```
flutter run
```

## Steps to Reproduce
1. Execute `flutter run`.

## Logs
WipError
```
Please note I had run Android AVD Emulator and exited using 'q' right before this crash.
The Edge debug window did open, on a blank screen.
```

```
[✓] Flutter (Channel stable, 2.2.0, on Microsoft Windows [Version 10.0.19043.1052], locale en-GB)
    • Flutter version 2.2.0 at D:\fluttersdk\flutter_windows_2.0.6-stable\flutter
    • Framework revision b22742018b (4 weeks ago), 2021-05-14 19:12:57 -0700
    • Engine revision a9d88a4d18
    • Dart version 2.13.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\andre\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: D:\AndroidStudioSDK\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
`Note I use Chromium Edge, which works well however suddenly I got this error. Haven't had any issues the past month developing.`

[✓] Android Studio
    • Android Studio at D:\AndroidStudioSDK
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = D:\AndroidStudioSDK
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[✓] Connected device (1 available)
    • Edge (web) • edge • web-javascript • Microsoft Edge 91.0.864.41

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 1d9032c7e1d867f071f2277eb1673e8f9b0274e3

**Comment by darshankawar** [comment] 2021-06-14 08:24
Closing this as duplicate of https://github.com/flutter/flutter/issues/56458

**Closed by darshankawar** 2021-06-14 08:24 UTC
Labels: in triage
