### ISSUE TITLE
When moving a marker the initial location changes downwards where it was selected

### ISSUE THREAD

**Issue by ErliSoares** [flutter/flutter#55508] opened 2020-04-23 23:24 UTC
When you select to move the marker, it comes close to the point that was clicked and is under the finger, so you cannot see the location that will be released.
In the gif demonstration below, it was clicked at the bottom of the marker image.
![Mover Marker](https://user-images.githubusercontent.com/2334509/80158891-144be080-85a0-11ea-8604-0971dccfda99.gif)

**Comment by TahaTesser** [comment] 2020-04-24 07:53
Hi @ErliSoares 
can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by ErliSoares** [comment] 2020-04-25 00:33
Moving the maker with the mouse on the emulator is not bad, but on the cell phone with moving it with the finger it is very bad for it to drop at a specific point, because idenpently from the place you hold the marker it comes under the finger, you can’t see where it’s going to drop.

``` dart
import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Maps',
      home: Scaffold(
        body: GoogleMap(
          mapType: MapType.hybrid,
          initialCameraPosition: CameraPosition(
            target: LatLng(37.42796133580664, -122.085749655962),
            zoom: 14.4746,
          ),
          markers: Set<Marker>.from([
            Marker(
              markerId: MarkerId("id"),
              draggable: true,
              onDragEnd: (newPosition) {},
              position: LatLng(37.42796133580664, -122.085749655962),
            )
          ]),
        ),
      ),
    );
  }
}

```

<details>
  <summary>flutter doctor -v</summary>
[√] Flutter (Channel stable, v1.12.13+hotfix.9, on Microsoft Windows [Version 10.0.18363.815], locale pt-BR)
    • Flutter version 1.12.13+hotfix.9 at C:\src\flutter
    • Framework revision f139b11009 (4 weeks ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2


[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0-rc1)
    • Android SDK at D:\AndroidSdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 30.0.0-rc1
    • ANDROID_HOME = D:\AndroidSdk
    • ANDROID_SDK_ROOT = D:\AndroidSdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[!] VS Code (version 1.43.2)
    • VS Code at C:\Users\erli\AppData\Local\Programs\Microsoft VS Code
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

! Doctor found issues in 1 category.

</details>

**Comment by TahaTesser** [comment] 2020-04-27 08:54
Hi @ErliSoares 
I just tried to reproduce this issue, i can clearly where them marker is going to drop because when you dragging bottom point of the marker is visible your dragging finger

Are experiencing different behaviour than above i mentioned 
Thank you

**Comment by TahaTesser** [comment] 2020-05-22 13:04
Hi @ErliSoares 
Without additional information, we are unfortunately not sure how to resolve this issue. We are
therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the
bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.

**Closed by TahaTesser** 2020-05-22 13:04 UTC
Labels: in triage, waiting for customer response
