### ISSUE TITLE
adb service not starting

### ISSUE THREAD

**Issue by Avi-Nash-S** [flutter/flutter#47037] opened 2019-12-14 11:58 UTC
**\adb.exe F 12-14 17:27:51  4700  8840 fdevent_poll.cpp:64] failed to create fdevent interrupt socketpair: Invalid       argument**                                                                                                                

```bash
[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.18363.535], locale en-IN) 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)  
[√] Android Studio (version 3.5)
[√] VS Code (version 1.41.0)
[☠] Connected device (the doctor check crashed)       
 X Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know       about this issue at https://github.com/flutter/flutter/issues.
X Exception: Unable to run "adb", check your Android SDK installation and ANDROID_HOME environment variable: D:\Flutter_SDK\flutter_windows_v1.12.13+hotfix.5-stable\Android\platform-tools\adb.exe                                                                                                                                                    ! Doctor found issues in 1 category. 
```

**Comment by rahuldange09** [comment] 2019-12-14 13:34
Add Android SDK path in environment variable

**Comment by Avi-Nash-S** [comment] 2019-12-15 06:38
Not because of the environment variable, some issues with the android-debug-bridge as the adb.exe seems to be obsolete. Is there anything any solution for this

**Comment by Avi-Nash-S** [comment] 2019-12-15 06:56
C:\>adb
'adb' is not recognized as an internal or external command,
operable program or batch file.

the above error is due improper environment variable,

C:\Users\avi1t\Downloads\platform-tools>adb
adb.exe F 12-15 12:22:41 16580  3168 fdevent_poll.cpp:64] failed to create fdevent interrupt socketpair: Invalid argument

this is the error i face while executing abd

**Comment by iapicca** [comment] 2019-12-16 08:50
possibly related to https://github.com/flutter/flutter/issues/46938

**Comment by Avi-Nash-S** [comment] 2019-12-21 12:50
Hope your right @iapicca, and now I made it work after downloading new platform-tools of older-version seperately and replaced the folder.

**Comment by jonahwilliams** [comment] 2020-01-09 21:17
Duplicate of https://github.com/flutter/flutter/issues/46938

**Closed by jonahwilliams** 2020-01-09 21:17 UTC
Labels: customer: crowd, severe: crash, severe: regression, t: flutter doctor, tool, ▣ platform-android

**Comment by GOGJIAN** [comment] 2020-11-24 03:20
> Duplicate of #46938

this not duplicate，you just want your issues have solved

**Comment by iapicca** [comment] 2020-11-24 07:06
@GOGJIAN 
both issues are closed from more than 8 months and refers to an older version of flutter
if you are experiencing the problem with the latest stable version (or above)
please open a new issue providing your `flutter doctor -v` and your  logs
