### ISSUE TITLE
in_app_purchase (subscription): Couldn't find purchase lists, trying to find single data

### ISSUE THREAD

**Issue by surpriso1997** [flutter/flutter#60580] opened 2020-06-30 07:11 UTC
Same issue as #35741

Raising the same issue because no one from the official team has responded, even almost after a year.

**Comment by TahaTesser** [comment] 2020-06-30 09:25
Closing as duplicate of https://github.com/flutter/flutter/issues/35741

**Closed by TahaTesser** 2020-06-30 09:25 UTC

**Comment by surpriso1997** [comment] 2020-06-30 09:34
> 
> 
> Please add `thumbs up` emoji to the existing issue
> Closing as duplicate of #35741

Please do not close this issue without responding on the other one. I specifically raised this issue because of no response from the team other than adding labels on the issue. More people are having problems with the library and the issue is still neglected.

**Comment by vivekwebdesk** [comment] 2020-08-28 07:54
Same issue
