### ISSUE TITLE
Do you have to configure asset to load local images? 

### ISSUE THREAD

**Issue by wangchuanwen** [flutter/flutter#28825] opened 2019-03-04 07:29 UTC
pubspec.yaml
  assets:
   - images/

images dir:
![_d1ddfb20-5d60-416d-a1fb-6344f9b6c686](https://user-images.githubusercontent.com/11566163/53716957-97d4da80-3e91-11e9-9477-bc4a5a812c6a.png)

code:
Image.asset('images/icon_home_sel.png')
I just want to load 2.0x and 3.0x，but Failed to load！

These errors are as follows：
"Unable to load asset: images/icon_home_sel.png"

[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.14 18A391, locale zh-Hans-CN)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).
      If Android SDK has been installed to a custom location, set $ANDROID_HOME to that
      location.
      You may also want to add it to your PATH environment variable.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[!] Android Studio (not installed)
[✓] VS Code (version 1.31.1)
[✓] Connected device (2 available)

! Doctor found issues in 2 categories.

**Comment by jonahwilliams** [comment] 2019-03-04 16:23
@wangchuanwen make sure you are following the instructions at https://flutter.dev/docs/development/ui/assets-and-images.

For example, if your pubspec.yaml looks like this:

```
flutter:
  assets:
    - images/
```

Then your directory structure should look like:

```
lib/
test/
images/
pubspec.yaml
```

And you would refer to the asset as `Image.asset('images/image_name.png')`

Can you share your pubspec.yaml?

**Comment by wangchuanwen** [comment] 2019-03-06 07:03
> @wangchuanwen make sure you are following the instructions at https://flutter.dev/docs/development/ui/assets-and-images.
> 
> For example, if your pubspec.yaml looks like this:
> 
> ```
> flutter:
>   assets:
>     - images/
> ```
> Then your directory structure should look like:
> 
> ```
> lib/
> test/
> images/
> pubspec.yaml
> ```
> And you would refer to the asset as `Image.asset('images/image_name.png')`
> 
> Can you share your pubspec.yaml?

pubspec.yaml configuration is as follows:
name: testflutter
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages

images directory structure:
![_d90134a5-44d7-47b5-a21d-6c02bb438b89](https://user-images.githubusercontent.com/11566163/53861102-1494bf80-401e-11e9-9723-cf38868d8471.png)

if so,assets/images/2.0x/icon_home_sel.png and assets/images/3.0x/icon_home_sel.png would be a valid variant of assets/icons/icon_home_sel.png. But，i don't want assets/icons/icon_home_sel.png，because the resource bundles get bigger

My question is not to use assets/icons/icon_home_sel.png,then i expect to use Image.asset('images/icon_home_sel.png').
A device dependence on pixel ratio decides whether to use 2x or 3x.

**Comment by escamoteur** [comment] 2019-09-24 12:04
@dnfield is it possible to only have image resources under 2x and 3x but not in the base folder?

**Comment by escamoteur** [comment] 2019-09-24 12:05
Hi, @wangchuanwen I just want to check  is this still a problem for you?

**Comment by iapicca** [comment] 2019-11-06 16:11
Hi @wangchuanwen 
I'm closing this issue as it refer to an older version of Flutter.
If you are you still experiencing this issue with the latest version of Flutter,
you may want to open a new issue or comment below;
either way please provide your updated `flutter doctor -v`.
It would be helpful to have also your` flutter run --verbose`
and a self contained app on github (or the steps to reproduce it).
Thank you

**Closed by iapicca** 2019-11-06 16:11 UTC
Labels: a: images, d: stackoverflow, waiting for customer response

**Comment by CyrilHu** [comment] 2020-05-11 14:25
I encounter this problem 
Unable to load asset: assets/images/heart.png

I can always reproduce when these two conditions are satisfied
1. include directory path in `pubspec.yaml`
2. no base asset at the real folder (only 2.0x or 3.0x)

```
Flutter 1.17.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision e6b34c2b5c (9 days ago) • 2020-05-02 11:39:18 -0700
Engine • revision 540786dd51
Tools • Dart 2.8.1
```

```
flutter:
  assets:
    - assets/images/
```

```
.../pubspec.yaml
.../assets/images/2.0x/heart.png
```

**Comment by iapicca** [comment] 2020-05-13 11:49
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.
