### ISSUE TITLE
Setting `FLTAssetsPath` in `AppFrameworkInfo.plist`  does not work.

### ISSUE THREAD

**Issue by dacaiguoguogmail** [flutter/flutter#29281] opened 2019-03-13 07:46 UTC
In [FlutterDartProject.mm#L208](https://github.com/flutter/engine/blob/master/shell/platform/darwin/ios/framework/Source/FlutterDartProject.mm#L208 "FlutterDartProject.mm") I found that I can change `flutter_assets ` by setting `FLTAssetsPath ` in `AppFrameworkInfo.plist`.  
But Setting `FLTAssetsPath` in `AppFrameworkInfo.plist`  does not work.
The reason is [xcode_backend.sh#L251](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/bin/xcode_backend.sh#L251)

**Comment by dacaiguoguogmail** [comment] 2019-03-13 09:19
[xcodeproj.dart#L53](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/ios/xcodeproj.dart#L53) 
Adding a user defined setting may solve this.

**Comment by dacaiguoguogmail** [comment] 2019-03-13 09:27
Add a User-Defiend Setting `FLTAssetsPath`
And then change [xcode_backend.sh#L251](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/bin/xcode_backend.sh#L251) to
```
--asset-dir="${derived_dir}/App.framework/${FLTAssetsPath}"
```

**Comment by dnfield** [comment] 2019-03-13 16:40
The problem is that xcode_backend has no idea what `${FLTAssetsPath}` is, right?  It would need to be available in an environment variable for the shell script to get it, and AFAIK Xcode doesn't set your plist properties to environment variables.

We definitely support moving this stuff around, but I'm not sure there's a good way to use it if you're using the xcode_backend script.  The customers using this are using alternative setups for their builds.

**Comment by dacaiguoguogmail** [comment] 2019-03-14 01:47
The scripts that are executed during the **Build Phases** of Xcode  that can retrieve variables from the **User-Defined** in the **BuildSettings**.
`xcode_backend.sh` is in **Build Phases**
```
/bin/sh "$FLUTTER_ROOT/packages/flutter_tools/bin/xcode_backend.sh" build
```

**Comment by dnfield** [comment] 2019-03-14 01:55
Right, and aren't these separate from info.plist?

**Comment by dacaiguoguogmail** [comment] 2019-03-14 03:26
Yes.
info.plist can read User-Defined variable by set value to `$(FLTAssetsPath)`
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>FLTAssetsPath</key>
    <string>$(FLTAssetsPath)</string>
</dict>
</plist>
```

**Comment by dacaiguoguogmail** [comment] 2019-03-14 03:31
In this way, can achieve the goal.

1. Add `FLTAssetsPath` to User-Defined variable.  

2. Add `FLTAssetsPath` to info.plist and set value to  `$(FLTAssetsPath)`

3. Change  [xcode_backend.sh#L251](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/bin/xcode_backend.sh#L251) to `--asset-dir="${derived_dir}/App.framework/${FLTAssetsPath}"`

**Comment by dnfield** [comment] 2019-03-14 03:33
Ahh ok.  I think that's fine as long as we default the variable in xcode_backend.sh to the current value

**Comment by dacaiguoguogmail** [comment] 2019-03-14 03:44
I have a question info.plist is `ios/Runner/Info.plist` or `ios/Flutter/AppFrameworkInfo.plist`?

There is other work to be done if is `ios/Flutter/AppFrameworkInfo.plist`.

**Comment by jmagman** [comment] 2020-01-24 00:45
Looks like you fixed this with https://github.com/flutter/flutter/pull/29499.

**Closed by jmagman** 2020-01-24 00:45 UTC
Labels: a: assets, e: embedder, t: xcode, tool, ⌺‬ platform-ios
