### ISSUE TITLE
Material 3 surface-container color is missing

### ISSUE THREAD

**Issue by guyluz11** [flutter/flutter#129763] opened 2023-06-29 09:56 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Add support for Material 3
Using the Theme find `surface-container`
`Theme.of(context).colorScheme.surfaceContainer`

### Expected results

`surfaceContainer` should exist in Flutter as it got generated by [Google Material 3 Figma](https://www.figma.com/community/file/1035203688168086460) addon

### Actual results

`colorScheme` does not contain `surfaceContainer` property.

### Code sample

There are several surface options, `surfaceContainer` may be `surface`.
If so the naming should be similar in Figma and flutter

```dart
Theme.of(context).colorScheme.surface;
Theme.of(context).colorScheme.surfaceTint;
Theme.of(context).colorScheme.surfaceVariant;
Theme.of(context).colorScheme.onSurface;
Theme.of(context).colorScheme.inverseSurface;
Theme.of(context).colorScheme.onSurfaceVariant;
```

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.10.0, on Microsoft Windows [Version 10.0.22621.1848], locale en-IL)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.4.3)
[√] Android Studio (version 2022.2)
[√] Connected device (4 available)
[√] Network resources
                                                              fl
• No issues found!

```

</details>

**Comment by TahaTesser** [comment] 2023-06-29 09:57
duplicate of https://github.com/flutter/flutter/issues/115912

**Closed by TahaTesser** 2023-06-29 09:57 UTC
Labels: in triage
