### ISSUE TITLE
[tool_crash] FileSystemException: Cannot create file, OS Error: The system cannot find the specified path, errno = 3

### ISSUE THREAD

**Issue by gjcarver** [flutter/flutter#136451] opened 2023-10-12 11:06 UTC
## Command

```
flutter+pub+get%0A%60%60%60%0A%0A%23%23+Steps+to+Reproduce%0A1.+...%0A2.+...%0A3.+...%0A%0A%23%23+Logs%0AFileSystemException%3A+Cannot+create+file%2C+OS+Error%3A+Das+System+kann+den+angegebenen+Pfad+nicht+finden.%0D%0A%2C+errno+%3D+
3%0A%60%60%60%0A%230++++++_File.throwIfError+%28dart%3Aio%2Ffile_impl.dart%3A675%3A7%29%0A%231++++++_File.createSync+%28dart%3Aio%2Ffile_impl.dart%3A306%3A5%29%0A%232++++++ForwardingFile.createSync+%28package%3Afile%2Fsrc%2Fforwardi
ng%2Fforwarding_file.dart%3A26%3A16%29%0A%233++++++ErrorHandlingFile.createSync.%3Canonymous+closure%3E+%28package%3Aflutter_tools%2Fsrc%2Fbase%2Ferror_handling_io.dart%3A283%3A22%29%0A%234++++++_runSync+%28package%3Aflutter_tools%2
Fsrc%2Fbase%2Ferror_handling_io.dart%3A590%3A14%29%0A%235++++++ErrorHandlingFile.createSync+%28package%3Aflutter_tools%2Fsrc%2Fbase%2Ferror_handling_io.dart%3A282%3A5%29%0A%236++++++_updateGeneratedXcodePropertiesFile+%28package%3Af
lutter_tools%2Fsrc%2Fios%2Fxcode_build_settings.dart%3A78%3A32%29%0A%237++++++updateGeneratedXcodeProperties+%28package%3Aflutter_tools%2Fsrc%2Fios%2Fxcode_build_settings.dart%3A49%3A3%29%0A%3Casynchronous+suspension%3E%0A%238++++++
MacOSProject._updateGeneratedXcodeConfigIfNeeded+%28package%3Aflutter_tools%2Fsrc%2Fxcode_project.dart%3A730%3A7%29%0A%3Casynchronous+suspension%3E%0A%239++++++MacOSProject.ensureReadyForPlatformSpecificTooling+%28package%3Aflutter_
tools%2Fsrc%2Fxcode_project.dart%3A725%3A5%29%0A%3Casynchronous+suspension%3E%0A%2310+++++FlutterProject.ensureReadyForPlatformSpecificTooling+%28package%3Aflutter_tools%2Fsrc%2Fproject.dart%3A368%3A7%29%0A%3Casynchronous+suspension
%3E%0A%2311+++++PackagesGetCommand.runCommand+%28package%3Aflutter_tools%2Fsrc%2Fcommands%2Fpackages.dart%3A337%3A7%29%0A%3Casynchronous+suspension%3E%0A%2312+++++FlutterCommand.run.%3Canonymous+closure%3E+%28package%3Aflutter_tools
%2Fsrc%2Frunner%2Fflutter_command.dart%3A1297%3A27%29%0A%3Casynchronous+suspension%3E%0A%2313+++++AppContext.run.%3Canonymous+closure%3E+%28package%3Aflutter_tools%2Fsrc%2Fbase%2Fcontext.dart%3A150%3A19%29%0A%3Casynchronous+suspensi
on%3E%0A%2314+++++CommandRunner.runCommand+%28package%3Aargs%2Fcommand_runner.dart%3A212%3A13%29%0A%3Casynchronous+suspension%3E%0A%2315+++++FlutterCommandRunner.runCommand.%3Canonymous+closure%3E+%28package%3Aflutter_tools%2Fsrc%2F
runner%2Fflutter_command_runner.dart%3A339%3A9%29%0A%3Casynchronous+suspension%3E%0A%60%60%60%0A%60%60%60%0A%1B%5B32m%5B%E2%9C%93%5D%1B%5B39m+Flutter+%28Channel+stable%2C+3.13.6%2C+on+Microsoft+Windows+%5BVersion+10.0.19043.2364%5D%
2C+locale+de-DE%29%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Flutter+version+3.13.6+on+channel+stable+at+C%3A%5Ctools%5Cflutter%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Upstream+repository+https%3A%2F%2Fgithub.com%2Fflutter%2Fflutter.git%0A++++%1B
%5B32m%E2%80%A2%1B%5B39m+Framework+revision+ead455963c+%282+weeks+ago%29%2C+2023-09-26+18%3A28%3A17+-0700%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Engine+revision+a794cf2681%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Dart+version+3.1.3%0A++++%1B%5B
32m%E2%80%A2%1B%5B39m+DevTools+version+2.25.0%0A%0A%1B%5B32m%5B%E2%9C%93%5D%1B%5B39m+Windows+Version+%28Installed+version+of+Windows+is+version+10+or+higher%29%0A%0A%1B%5B32m%5B%E2%9C%93%5D%1B%5B39m+Android+toolchain+-+develop+for+A
ndroid+devices+%28Android+SDK+version+34.0.0%29%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Android+SDK+at+C%3A%5CUsers%5Ccarver%5CAppData%5CLocal%5CAndroid%5Csdk%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Platform+android-34%2C+build-tools+34.0.0%0A+
+++%1B%5B32m%E2%80%A2%1B%5B39m+Java+binary+at%3A+C%3A%5CProgram+Files%5CAndroid%5CAndroid+Studio%5Cjbr%5Cbin%5Cjava%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Java+version+OpenJDK+Runtime+Environment+%28build+17.0.6%2B0-b2043.56-10027231%29%
0D%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+All+Android+licenses+accepted.%0A%0A%1B%5B32m%5B%E2%9C%93%5D%1B%5B39m+Chrome+-+develop+for+the+web%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Chrome+at+C%3A%5CProgram+Files+%28x86%29%5CGoogle%5CChrome%5CA
pplication%5Cchrome.exe%0A%0A%1B%5B32m%5B%E2%9C%93%5D%1B%5B39m+Visual+Studio+-+develop+Windows+apps+%28Visual+Studio+Community+2019+16.11.27%29%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Visual+Studio+at+C%3A%5CProgram+Files+%28x86%29%5CMicr
osoft+Visual+Studio%5C2019%5CCommunity%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Visual+Studio+Community+2019+version+16.11.33801.447%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Windows+10+SDK+version+10.0.20348.0%0A%0A%1B%5B32m%5B%E2%9C%93%5D%1B%5B3
9m+Android+Studio+%28version+2022.3%29%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Android+Studio+at+C%3A%5CProgram+Files%5CAndroid%5CAndroid+Studio%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Flutter+plugin+can+be+installed+from%3A%0A++++++%F0%9F%94%A
8+https%3A%2F%2Fplugins.jetbrains.com%2Fplugin%2F9212-flutter%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Dart+plugin+can+be+installed+from%3A%0A++++++%F0%9F%94%A8+https%3A%2F%2Fplugins.jetbrains.com%2Fplugin%2F6351-dart%0A++++%1B%5B32m%E2%80
%A2%1B%5B39m+Java+version+OpenJDK+Runtime+Environment+%28build+17.0.6%2B0-b2043.56-10027231%29%0D%0A%0A%1B%5B32m%5B%E2%9C%93%5D%1B%5B39m+IntelliJ+IDEA+Community+Edition+%28version+2021.2%29%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+IntelliJ
+at+C%3A%5CProgram+Files%5CJetBrains%5CIntelliJ+IDEA+Community+Edition+2021.2.2%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Flutter+plugin+version+60.1.4%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Dart+plugin+version+212.5284.31%0A%0A%1B%5B32m%5B%E2%9
C%93%5D%1B%5B39m+VS+Code+%28version+1.82.2%29%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+VS+Code+at+C%3A%5CUsers%5Ccarver%5CAppData%5CLocal%5CPrograms%5CMicrosoft+VS+Code%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Flutter+extension+version+3.25.0%0A%
0A%1B%5B32m%5B%E2%9C%93%5D%1B%5B39m+Connected+device+%284+available%29%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Lenovo+TB+X304F+%28mobile%29+%E2%80%A2+a700aaac+%E2%80%A2+android-arm64++%E2%80%A2+Android+8.1.0+%28API+27%29%0A++++%1B%5B32m%E
2%80%A2%1B%5B39m+Windows+%28desktop%29++++++++%E2%80%A2+windows++%E2%80%A2+windows-x64++++%E2%80%A2+Microsoft+Windows+%5BVersion+10.0.19043.2364%5D%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Chrome+%28web%29+++++++++++++%E2%80%A2+chrome+++%E
2%80%A2+web-javascript+%E2%80%A2+Google+Chrome+116.0.5845.179%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Edge+%28web%29+++++++++++++++%E2%80%A2+edge+++++%E2%80%A2+web-javascript+%E2%80%A2+Microsoft+Edge+117.0.2045.36%0A%0A%1B%5B32m%5B%E2%9C%
93%5D%1B%5B39m+Network+resources%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+All+expected+network+resources+are+available.%0A%0A%1B%5B32m%E2%80%A2%1B%5B39m+No+issues+found%21%0A%0A%60%60%60%0A%0A%23%23+Flutter+Application+Metadata%0A%2A%2ATyp
e%2A%2A%3A+app%0A%2A%2AVersion%2A%2A%3A+1.0.0%2B1%0A%2A%2AMaterial%2A%2A%3A+true%0A%2A%2AAndroid+X%2A%2A%3A+false%0A%2A%2AModule%2A%2A%3A+false%0A%2A%2APlugin%2A%2A%3A+false%0A%2A%2AAndroid+package%2A%2A%3A+null%0A%2A%2AiOS+bundle+i
dentifier%2A%2A%3A+null%0A%2A%2ACreation+channel%2A%2A%3A+stable%0A%2A%2ACreation+framework+version%2A%2A%3A+ead455963c12b453cdb2358cad34969c76daf180%0A%23%23%23+Plugins%0Apath_provider_linux-2.2.1%0Apath_provider_windows-2.2.1%0Ash
ared_preferences-2.2.2%0Ashared_preferences_android-2.2.1%0Ashared_preferences_foundation-2.3.4%0Ashared_preferences_linux-2.3.1%0Ashared_preferences_web-2.2.1%0Ashared_preferences_windows-2.3.1%0Asqflite-2.3.0%0A%0A&labels=tool%2Cs
evere%3A+crash

```

**Comment by dam-ease** [comment] 2023-10-12 12:07
Hi @gjcarver. Please when opening an issue, please try to provide all or some of the information indicated in the template so that we can address this issue properly.
More specifically, please provide the information indicated below:

- Command
- Steps to Reproduce (if any)
- Logs
- Output of `flutter doctor -v`

I am closing this issue since little or no information has been provided. Once you update the issue with more information, please write in the comments and I will re-open this for further discussion. Thanks!

**Closed by dam-ease** 2023-10-12 12:07 UTC
Labels: in triage

**Comment by gjcarver** [comment] 2023-10-12 12:10
too late; "run" was the command... that's all i remember
