### ISSUE TITLE
flutter_gallery - incompatible version constraints on vectore_math 

### ISSUE THREAD

**Issue by pebreo** [flutter/flutter#16594] opened 2018-04-14 23:38 UTC
I am unable to compile and run `flutter_gallery` app.

 I git cloned flutter a couple minutes ago and following the instructions to run
gallery app. I go into the `flutter_gallery` directory, and per the instructions the first thing I run `flutter upgrade` but I get the error:

```
Upgrading Flutter from /Users/paul/development/flutter...
Already up-to-date.

Upgrading engine...
Already up-to-date.

Flutter 0.2.8 • channel beta • https://github.com/flutter/flutter.git
Framework • revision b397406561 (12 days ago) • 2018-04-02 13:53:20 -0700
Engine • revision c903c217a1
Tools • Dart 2.0.0-dev.43.0.flutter-52afcba357

Running "flutter packages upgrade" in flutter_gallery...         
Incompatible version constraints on vector_math:
- flutter 0.0.0 depends on version 2.0.5
- flutter_gallery depends on version 2.0.6
pub upgrade failed (1)
```
### verbose mode
So then I ran `flutter -v upgrade` for more details:

```
[  +18 ms] [/Users/paul/development/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +33 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/beta
[        ] [/Users/paul/development/flutter/] git rev-parse --abbrev-ref HEAD
[   +5 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] beta
[        ] [/Users/paul/development/flutter/] git ls-remote --get-url origin
[   +5 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[        ] [/Users/paul/development/flutter/] git log -n 1 --pretty=format:%H
[   +7 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] b397406561f5e7a9c94e28f58d9e49fca0dd58b7
[        ] [/Users/paul/development/flutter/] git log -n 1 --pretty=format:%ar
[   +5 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[        ] 12 days ago
[        ] [/Users/paul/development/flutter/] git describe --match v*.*.* --first-parent --long --tags
[   +6 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v0.2.8-0-gb397406
[  +75 ms] [/Users/paul/development/flutter/] git rev-parse @{u}
[  +26 ms] b397406561f5e7a9c94e28f58d9e49fca0dd58b7
[        ] Upgrading Flutter from /Users/paul/development/flutter...
[   +1 ms] [/Users/paul/development/flutter/] git pull --ff-only
[+2471 ms] Already up-to-date.
[        ] Upgrading engine...
[        ] [/Users/paul/development/flutter/] bin/flutter --no-color precache
[ +507 ms] Already up-to-date.
[ +212 ms] Flutter 0.2.8 • channel beta • https://github.com/flutter/flutter.git
                   Framework • revision b397406561 (12 days ago) • 2018-04-02 13:53:20 -0700
                   Engine • revision c903c217a1
                   Tools • Dart 2.0.0-dev.43.0.flutter-52afcba357
[   +3 ms] Running "flutter packages upgrade" in flutter_gallery...
[   +2 ms] Using /Users/paul/development/flutter/.pub-cache for the pub cache.
[        ] [/Users/paul/Desktop/examples_flutter/gal2/flutter/examples/flutter_gallery/] /Users/paul/development/flutter/bin/cache/dart-sdk/bin/pub --verbosity=warning --verbose upgrade --no-precompile
[+3618 ms] Incompatible version constraints on vector_math:
[        ] - flutter 0.0.0 depends on version 2.0.5
[        ] - flutter_gallery depends on version 2.0.6
[  +40 ms] "flutter upgrade" took 6,939ms.
pub upgrade failed (1)

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28)
#1      pub (package:flutter_tools/src/dart/pub.dart:168)
<asynchronous suspension>
#2      pubGet (package:flutter_tools/src/dart/pub.dart:104)
<asynchronous suspension>
#3      UpgradeCommand.runCommand (package:flutter_tools/src/commands/upgrade.dart:75)
<asynchronous suspension>
#4      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:333)
<asynchronous suspension>
#5      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:270)
<asynchronous suspension>
#6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#7      _rootRun (dart:async/zone.dart:1126)
#8      _CustomZone.run (dart:async/zone.dart:1023)
#9      runZoned (dart:async/zone.dart:1501)
#10     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#11     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:261)
#12     CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#13     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:298)
<asynchronous suspension>
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#15     _rootRun (dart:async/zone.dart:1126)
#16     _CustomZone.run (dart:async/zone.dart:1023)
#17     runZoned (dart:async/zone.dart:1501)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#19     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:254)
<asynchronous suspension>
#20     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#21     new Future.sync (dart:async/future.dart:222)
#22     CommandRunner.run (package:args/command_runner.dart:109)
#23     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:168)
#24     run.<anonymous closure> (package:flutter_tools/runner.dart:54)
<asynchronous suspension>
#25     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#26     _rootRun (dart:async/zone.dart:1126)
#27     _CustomZone.run (dart:async/zone.dart:1023)
#28     runZoned (dart:async/zone.dart:1501)
#29     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#30     runInContext (package:flutter_tools/src/context_runner.dart:41)
<asynchronous suspension>
#31     run (package:flutter_tools/runner.dart:49)
#32     main (package:flutter_tools/executable.dart:48)
<asynchronous suspension>
#33     main (file:///Users/paul/development/flutter/packages/flutter_tools/bin/flutter_tools.dart:16)
#34     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#35     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```

### flutter doctor output
I have been able to run basic apps (e.g. Todo and hello world) using VSCode and Android P image through the emulator. Anyway, here's my flutter doctor output.
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.2.8, on Mac OS X 10.12.6 16G29, locale en-US)
-Error executing simctl: -6
dyld: Library not loaded: /Library/Developer/PrivateFrameworks/CoreSimulator.framework/Versions/A/CoreSimulator
  Referenced from: /Applications/Xcode.app/Contents/Developer/usr/bin/simctl
  Reason: image not found

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[!] iOS toolchain - develop for iOS devices (Xcode 9.2)
    ✗ Xcode requires additional components to be installed in order to run.
      Launch Xcode and install additional required components when prompted.
    ✗ libimobiledevice and ideviceinstaller are not installed. To install, run:
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    ✗ ios-deploy not installed. To install:
        brew install ios-deploy
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work on iOS.
        For more info, see https://flutter.io/platform-plugins
      To install:
        brew install cocoapods
        pod setup
[✓] Android Studio (version 3.1)
[!] Connected devices
    ! No devices available

! Doctor found issues in 2 categories.
```

**Comment by chinmaygarde** [comment] 2018-04-15 02:44
cc @tvolkert, @cbracken: Could this be due to the recent upgrade of vector_math being incompatible with the beta channel? I am not able to reproduce this on master. I am on ea30c95dc99de6f86f23caca3d219c5f89a19bff.

**Comment by tvolkert** [comment] 2018-04-15 02:54
No, we pin all our deps to specific versions specifically to avoid this.  The `flutter_gallery` package depends on `vector_math: 2.0.5` on the beta branch (https://github.com/flutter/flutter/blob/beta/examples/flutter_gallery/pubspec.yaml), so @pebreo it appears you may have local modifications to your `flutter_gallery` project if you see this error ("flutter_gallery depends on version 2.0.6").

**Comment by engr-zeeshan** [comment] 2018-04-16 14:55
I had same problem today when I wanted to run hello_world example.
changing values of

1. vector_math to 2.0.5 from 2.0.6
2. args to 1.4.1 from 1.4.2
3. pub_semver to 1.3.2 from 1.3.6
4. quiver to 0.28.0 from 0.29.0+1

@tvolkert The forked version with me has different values as compared to those on pubspec on flutter. Why this could be?

**Comment by tvolkert** [comment] 2018-04-16 15:05
@engr-zeeshan because you're comparing the master branch of one to the beta branch of the other.  If you look at your fork's beta branch, they're identical:

https://github.com/engr-zeeshan/flutter/blob/beta/examples/hello_world/pubspec.yaml

**Comment by pebreo** [comment] 2018-04-17 00:28
I ran `flutter channel master` then `flutter channel upgrade` and it works now.

**Comment by cbracken** [comment] 2018-05-10 15:20
Sounds like those who had hit this are no longer hitting it on master. Closing, but if you’re still seeing this, let us know.

**Closed by cbracken** 2018-05-10 15:20 UTC
Labels: a: first hour, d: examples, team: gallery
