### ISSUE TITLE
[tool_crash] DartDevelopmentServiceException

### ISSUE THREAD

**Issue by IamShubhamGupto** [flutter/flutter#78775] opened 2021-03-22 09:25 UTC
## Command
```
flutter run -d chrome
```

## Steps to Reproduce
1. If webpage does not load on browser
2. Copy paste localhost address to a new browser tab
3. Error should occur

## Logs
DartDevelopmentServiceException
```
#0      DartDevelopmentServiceImpl._startDDSServer (package:dds/src/dds_impl.dart:144:7)
<asynchronous suspension>
#1      DartDevelopmentServiceImpl.startService (package:dds/src/dds_impl.dart:97:7)
<asynchronous suspension>
#2      DartDevelopmentService.startDartDevelopmentService (package:dds/dds.dart:82:5)
<asynchronous suspension>
#3      DebugService.startDartDevelopmentService (package:dwds/src/services/debug_service.dart:151:12)
<asynchronous suspension>
#4      DevHandler._createAppDebugServices (package:dwds/src/handlers/dev_handler.dart:424:7)
<asynchronous suspension>
#5      DevHandler.loadAppServices (package:dwds/src/handlers/dev_handler.dart:226:25)
<asynchronous suspension>
#6      Dwds.debugConnection (package:dwds/dwds.dart:82:28)
<asynchronous suspension>
#7      WebDevFS.connect.<anonymous closure> (package:flutter_tools/src/isolated/devfs_web.dart:651:15)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 2.0.2, on Microsoft Windows [Version 10.0.19041.867], locale en-IN)
    • Flutter version 2.0.2 at F:\flutter
    • Framework revision 8962f6dc68 (11 days ago), 2021-03-11 13:22:20 -0800
    • Engine revision 5d8bf811b3
    • Dart version 2.12.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0-rc4)
    • Android SDK at F:\android-sdk-windows
    • Platform android-30, build-tools 30.0.0-rc4
    • ANDROID_HOME = F:\android-sdk-windows
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.54.3)
    • VS Code at C:\Users\Shubham\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.20.0

[✓] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 89.0.4389.90
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 89.0.774.57

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 8962f6dc68ec8e2206ac2fa874da4a453856c7d3
### Plugins
cloud_firestore-1.0.1
cloud_firestore_web-1.0.1
firebase_analytics-5.0.15
firebase_auth-1.0.1
firebase_auth_web-1.0.2
firebase_core-1.0.1
firebase_core_web-1.0.1
google_sign_in-5.0.1
google_sign_in_web-0.10.0

**Comment by pedromassangocode** [comment] 2021-03-22 11:05
Related issues: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+DartDevelopmentServiceException

Not duplicate since the stack trace are different.

**Comment by iapicca** [comment] 2021-04-10 09:58
possible duplicate of https://github.com/flutter/flutter/issues/77077

**Comment by iapicca** [comment] 2021-05-24 20:42
@jiaozebo 
according to this [message](https://github.com/flutter/flutter/issues/77077#issuecomment-847251189) the issue might to be solved  in the latest stable, can you confirm?

cc @TahaTesser

**Comment by IamShubhamGupto** [comment] 2021-05-25 03:25
> @IamShubhamGupto
> according to this [message](https://github.com/flutter/flutter/issues/77077#issuecomment-847251189) the issue may be solved in the latest stable, can you confirm?
> 
> cc @TahaTesser

Yes, I am currently on Flutter 2.2, have not faced this sort of crash.
Thank you !!

**Closed** 2021-05-26 13:11 UTC
Labels: passed first triage, severe: crash, tool
