### ISSUE TITLE
adb is still running after closing Visual Studio Code

### ISSUE THREAD

**Issue by raihanadf** [flutter/flutter#113824] opened 2022-10-21 10:07 UTC
### Describe the bug
After closing Flutter project on VSCode, adb is not killed and still running in the background  
![image](https://user-images.githubusercontent.com/12584890/197169702-6bba7dfb-1fb6-48df-b59d-cb19e8714276.png)

### To Reproduce
1. Open VSCode with Flutter project
2. Close VSCode

### Workaround Solution
run `killall adb`

This doesn't happen on Android Studio, it just kills the process after closing

**Comment by exaby73** [comment] 2022-10-21 11:05
Hello @raihanadf. Can you provide the complete logs of `flutter doctor -v`? Also, are you closing VSCode while the app is running or are you stopping the app first?

**Comment by raihanadf** [comment] 2022-10-21 14:32
`flutter doctor -v` complete logs:

```
[✓] Flutter (Channel stable, 3.3.4, on Arch Linux 6.0.2-zen1-1-zen, locale en_US.UTF-8)
    • Flutter version 3.3.4 on channel stable at /home/raihan/.sdk_dir/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision eb6d86ee27 (2 weeks ago), 2022-10-04 22:31:45 -0700
    • Engine revision c08d7d5efc
    • Dart version 2.18.2
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /home/raihan/.sdk_dir/Android/SDK
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = /home/raihan/.sdk_dir/Android/SDK
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /usr/bin/chromium

[✓] Linux toolchain - develop for Linux desktop
    • clang version 14.0.6
    • cmake version 3.24.2
    • ninja version 1.11.1
    • pkg-config version 1.8.0

[✓] Android Studio (version 2021.3)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 70.2.3
    • Dart plugin version 213.7433
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] Connected device (3 available)
    • Redmi Note 8 (mobile) • bb5e1d6 • android-arm64  • Android 12 (API 32)
    • Linux (desktop)       • linux   • linux-x64      • Arch Linux 6.0.2-zen1-1-zen
    • Chrome (web)          • chrome  • web-javascript • Chromium 106.0.5249.119 Arch Linux

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

I tried both; closing while the app is running and already stopped, both outputs the same issue

**Comment by exaby73** [comment] 2022-10-24 07:07
> Also, are you closing VSCode while the app is running or are you stopping the app first?

Could you provide information about the above?

**Comment by raihanadf** [comment] 2022-10-24 11:22
I did provide. 

> both output the same issue

**Comment by raihanadf** [comment] 2022-10-24 14:25
Closed VSCode and then disconnected the device, and yep it is still active
![image](https://user-images.githubusercontent.com/12584890/197549601-8707f198-006c-43fa-a19c-2bc9f8bce90f.png)

**Comment by exaby73** [comment] 2022-10-26 09:55
## Triage report

Thanks for the information. I can reproduce this issue. VSCode doesn't seem to kill the adb process. Following the same on Android Studio, adb is killed. Checked using `ps -e | grep adb`

**Comment by raihanadf** [comment] 2022-10-29 16:56
I hope this gets fixed as soon as possible, cause adb is using my gpu, so if I'm not aware or forgot adb is running in the background, my laptop gets very hot. But luckily my laptop has an indicator for the gpu haha. 

Anyway, thank you :)

**Comment by DanTup** [comment] 2022-10-29 17:12
> @DanTup Does this issue belong on the https://github.com/Dart-Code/Flutter repo?

I'm not certain. VS Code doesn't spawn `adb` directly, it only spawns `flutter` (which spawns `adb`), so until I've done some debugging I'm not certain where the fix will need to be (VS Code is also migrating to new debug adapters that live here in the Flutter SDK, so it's also possible that the issue is there). I'll do some digging and post back when I know more (or have a fix).

**Comment by DanTup** [comment] 2022-10-31 10:51
I can reproduce this, but I'm not really sure what the expected behaviour is here. The issue isn't specific to VS Code, you can see the same behaviour by running `flutter daemon` in a terminal and then causing it to start scanning for devices (by pasting in `[{"id":"2","method":"device.enable"}]` and pressing `<enter>`). If you then terminate the daemon with Ctrl+C, the ADB server remains around.

There's some info at https://developer.android.com/studio/command-line/adb#howadbworks about this, but not much. It seems that when Flutter runs `adb` it will start the server if it's not already running. I don't know if it's reasonable for Flutter to kill this process when the daemon ends (or VS Code when you close it) because it's very possible it's being used by (or was even started by) another tool (or another instance of Flutter, or another instance of VS Code).

Turns out, I raised this issue myself some years ago at #15575 and it was concluded that this is working as expected. I suspect that the reason it doesn't happen with Android Studio is that it's explicitly killing the server when it exits. This seems like a bad idea to me, and there are some complaints about it such as https://stackoverflow.com/questions/52893408/android-studio-killing-adb-server-when-exiting.

So my feeling is that although this behaviour isn't ideal, it's the expected (and only reasonable) behaviour. It would be nice if `adb` had a "stop the server if it's not being used by anything else" command, but as far as I can tell, it does not.

**Comment by exaby73** [comment] 2022-10-31 12:03
Understood. Thank you @DanTup. Since this is working as expected, I am closing this issue.

**Closed by exaby73** 2022-10-31 12:03 UTC
Labels: platform-android, tool, has reproducible steps, found in release: 3.3, found in release: 3.4
