### ISSUE TITLE
shape : RoundedRectangleBorder + Border.all -> Not Round

### ISSUE THREAD

**Issue by Solido** [flutter/flutter#19147] opened 2018-07-08 12:32 UTC
Expecting that the merge of both Borders produce a RoundedBorder but
Border.all override those settings. The order doesn't change the result.
Remove Border.all and you have rounded borders.

```dart
decoration: ShapeDecoration(
            shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(8.0),
                ) + Border.all(color: Colors.blue)));
```

```
[✓] Flutter (Channel master, v0.5.7-pre.62)
```

**Comment by antoninobajeli** [comment] 2018-11-24 08:13
I'm facing the same problem

shape: new RoundedRectangleBorder(
                    borderRadius: new BorderRadius.circular(26 / 1.5),
                )+ Border.all(color: Colors.white),

I get squared borders.

[✓] Flutter (Channel master, v0.11.10-pre.2, on Mac OS X 10.14 18A391, locale it-IT)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[✓] Android Studio (version 3.2)
[✓] IntelliJ IDEA Community Edition (version 2017.2.6)

**Comment by ThinkDigitalSoftware** [comment] 2019-10-14 03:02
This can be closed now. I'm trying it in Flutter 1.9.1+hotfix.4 • channel stable with the following code and it gives the following result:

```dart
 Container(
                  width: 100,
                  height: 100,
                  decoration: ShapeDecoration(
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.all(
                        Radius.circular(10),
                      ),
                    ),
                    image: DecorationImage(
                      image: AssetImage(
                        'assets/logo.png',
                      ),
                    ),
                  ),
                )
```
<img width="127" alt="Screen Shot 2019-10-13 at 8 02 36 PM" src="https://user-images.githubusercontent.com/23037821/66727486-6c857700-edf4-11e9-9b91-a4b38032046a.png">

**Comment by Solido** [comment] 2019-10-14 19:06
@ThinkDigitalSoftware Check the + Border.all(color: Colors.blue) part

**Comment by ThinkDigitalSoftware** [comment] 2019-10-14 19:10
Ah, I'm sorry. I completely missed that. I didn't even know you could merge boarders

**Comment by zemunkh** [comment] 2019-11-28 03:19
Only missing part is BorderSide in this case. You should add BorderSide property to merge. ;)) Now, you can close this issue.

```
Container(
  width: 100,
  height: 100,
  decoration: ShapeDecoration(
    shape: RoundedRectangleBorder(
      borderRadius: BorderRadius.all(
        Radius.circular(10),
      ),
      side: BorderSide(width: 1), 
    ),
    image: DecorationImage(
      image: AssetImage(
        'assets/logo.png',
      ),
    ),
  ),
)
```

**Comment by Solido** [comment] 2019-11-30 10:07
@zemunkh Can you read the bug again please and look at the `+` operator.

**Comment by zemunkh** [comment] 2019-12-03 01:01
I thought that your main task is to get RoundedRectangleBorder with Borderline. Right? Else, you only want to use `+` operator to get that same result.

**Comment by Arentas93** [comment] 2020-10-16 14:17
Hey guys, I have the very same problem @Solido described. I want to add top-left and top-right rounded rectangular Border to the shape parameter.  And also I want to change color of the top side of the rectangular.

`shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.only(
                topLeft: Radius.circular(13),
                topRight: Radius.circular(13),
              ),
            ) +
            Border(
              top: BorderSide(color: Colors.black),
            ),`

The problem is that + operator Border() removes rounded corners.
Also I have tried to use side : BorderSide() inside RoundedRectangleBorder instead of + Border(), but in that case all 4 sides becomes changed and my goal is to change only one.

**Closed** 2021-05-27 16:19 UTC
Labels: P5, framework, severe: new feature
