### ISSUE TITLE
build_runner error => Bad state: Unexpected diagnostics: /Users/kamran/Tools/flutter/bin/cache/dart-sdk/lib/core/int.dart:117:18

### ISSUE THREAD

**Issue by skyloovportal** [flutter/flutter#90578] opened 2021-09-23 07:11 UTC
I am facing this error in build_runner after updating the flutter to 2.5.1, I tried to downgrade to 2.5.0 too but now the error is still there.

### Following is the output from terminal:
`Bad state: Unexpected diagnostics:
/Users/kamran/Tools/flutter/bin/cache/dart-sdk/lib/core/int.dart:117:18 - Operator declarations must be preceded by the keyword 'operator'.
/Users/kamran/Tools/flutter/bin/cache/dart-sdk/lib/core/int.dart:117:16 - Methods must have an explicit list of parameters.
/Users/kamran/Tools/flutter/bin/cache/dart-sdk/lib/core/int.dart:117:18 - A function body must be provided.
[SEVERE] chopper_generator:chopper_generator on lib/app_config_bloc.dart:`

### Other Info:

`sdk: ">=2.7.0 <3.0.0"`
`Dart SDK: 2.14.2`

**Comment by danagbemava-nc** [comment] 2021-09-23 09:37
@skyloovportal did you upgrade from `2.2.3` to `2.5.1` or from `2.5.0` to `2.5.1`? 

Please share output of `flutter doctor -v` as well.

Thank you

**Comment by skyloovportal** [comment] 2021-09-23 10:19
I am not sure if I upgrade from `2.2.3` to `2.5.1 `or from `2.5.0` to `2.5.1` but currently i am at `2.5.1` for sure.
I am sharing the console log for `flutter doctor -v`:

[✓] Flutter (Channel stable, 2.5.0, on macOS 11.2.1 20D74 darwin-x64, locale en-AE)
    • Flutter version 2.5.0 at /Users/kamran/Tools/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cc385b4b8 (2 weeks ago), 2021-09-07 23:01:49 -0700
    • Engine revision f0826da7ef
    • Dart version 2.14.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/kamran/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio
    • Android Studio at /Applications/Android Studio 4.2 Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[!] Android Studio
    • Android Studio at /Users/kamran/Downloads/Android Studio Preview 2.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] Android Studio
    • Android Studio at /Users/kamran/Downloads/Android Studio 4.2 Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] Android Studio
    • Android Studio at /Users/kamran/Downloads/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[✓] VS Code (version 1.60.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 93.0.4577.82

! Doctor found issues in 1 category.

**Comment by danagbemava-nc** [comment] 2021-09-23 11:51
There might be an issue with your `cache` since the upgrade. 

Kindly run 

`flutter pub cache clean` &

`flutter pub get` in the root of your project folder. 

Then try running the `build_runner` command again.

**Comment by skyloovportal** [comment] 2021-09-23 11:55
Tried all of these steps before but still no luck 😕

**Comment by danagbemava-nc** [comment] 2021-09-23 12:01
Kindly provide a minimal reproducible sample and also, can you try with a new app and see if you experience this issue?

**Comment by skyloovportal** [comment] 2021-09-23 12:11
I have tried creating a new project and copied the same `pubspec.yaml` file but the problem still persist.

<details>
<summary>kamran@Kamrans-MacBook-Pro flutter_application_1 % flutter pub run build_runner watch</summary>

```console
[INFO] Generating build script...
[INFO] Generating build script completed, took 410ms

[WARNING] Deleted previous snapshot due to missing asset graph.
[INFO] Creating build script snapshot......
[INFO] Creating build script snapshot... completed, took 10.6s

[INFO] Setting up file watchers...
[INFO] Setting up file watchers completed, took 15ms

[INFO] Waiting for all file watchers to be ready...
[INFO] Waiting for all file watchers to be ready completed, took 200ms

[INFO] Initializing inputs
[INFO] Building new asset graph...
[INFO] Building new asset graph completed, took 657ms

[INFO] Checking for unexpected pre-existing outputs....
[INFO] Checking for unexpected pre-existing outputs. completed, took 1ms

[INFO] Running build...
[WARNING] freezed:freezed on test/widget_test.dart:
Your current `analyzer` version may not fully support your current SDK version.

Please try upgrading to the latest `analyzer` by running `flutter packages upgrade`.

Analyzer language version: 2.12.0
SDK language version: 2.14.0

If you are getting this message and have the latest analyzer please file
an issue at https://github.com/dart-lang/sdk/issues/new with the title
"No published analyzer available for language version 2.14.0".
Please search the issue tracker first and thumbs up and/or subscribe to
existing issues if present to avoid duplicates.

[INFO] Generating SDK summary...
[SEVERE] freezed:freezed on test/widget_test.dart:

Bad state: Unexpected diagnostics:
/Users/kamran/Tools/flutter/bin/cache/dart-sdk/lib/core/int.dart:117:18 - Operator declarations must be preceded by the keyword 'operator'.
/Users/kamran/Tools/flutter/bin/cache/dart-sdk/lib/core/int.dart:117:16 - Methods must have an explicit list of parameters.
/Users/kamran/Tools/flutter/bin/cache/dart-sdk/lib/core/int.dart:117:18 - A function body must be provided.
[SEVERE] freezed:freezed on test/widget_test.dart:
```
</details>

**Comment by skyloovportal** [comment] 2021-09-23 13:03
Try to add the following **`dependencies`** in your project and try to create a `freezed` file using `freezed` package.

<details>
<summary>dependencies</summary>

```console
dependencies:
  flutter:
    sdk: flutter

  flutter_test:
    sdk: flutter

  intl: ^0.17.0

  shared_preferences: ^2.0.5

  flutter_screenutil: ^5.0.0+2

  easy_rich_text: ^0.5.5

  smooth_page_indicator: ^0.3.0-nullsafety.0

  readmore: ^2.0.0

  webview_flutter: ^2.0.7

  json_annotation: ^3.1.0

  #chopper: ^2.4.1

  injectable: ^1.1.0

  get_it: ^5.0.6

  dartz: ^0.10.0-nullsafety.2

  equatable: ^2.0.3

  device_info: ^2.0.1

  data_connection_checker: ^0.3.4

  flutter_bloc: ^7.1.0

  flutter_spinkit: ^5.0.0

  keyboard_avoider: ^0.1.2
  
  animator: ^3.0.0

  google_sign_in: ^4.0.0

  flutter_facebook_auth: ^3.3.3-no-nullsafety

  sign_in_with_apple: ^3.0.0

  algolia: ^0.1.7

  cached_network_image: ^2.5.0

  uni_links: ^0.5.1

  shimmer: ^2.0.0

  share: ^2.0.4

  google_maps_flutter: ^2.0.6

  syncfusion_flutter_sliders: ^19.1.69-beta

  photo_view: ^0.12.0

  url_launcher: ^6.0.7

  mask_text_input_formatter: ^2.0.0

  simple_tooltip: ^0.1.16

  map_launcher: ^2.1.1

  flutter_svg: ^0.19.3

  tab_indicator_styler: ^1.0.0

  sensors_plus: ^1.0.2

  motion_sensors: ^0.1.0

  permission_handler: ^8.1.4+2

  showcaseview: ^1.1.0

  image_picker: ^0.8.3+2

  cupertino_icons: ^1.0.3

dev_dependencies:
 
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  build_runner:
  freezed: ^0.12.7
  freezed_annotation: ^0.12.0
  json_serializable: ^3.5.1
  #chopper_generator: ^2.4.0
  injectable_generator: ^1.1.0

dependency_overrides:
  http: ^0.12.0

```
</details>

Add file in your project named as : `request_support_failures.dart` and put the following content:

```console
import 'package:flutter/foundation.dart';
import 'package:freezed_annotation/freezed_annotation.dart';

part 'request_support_failures.freezed.dart';

@freezed
abstract class RequestSupportFailure with _$RequestSupportFailure {
  // 1
  const factory RequestSupportFailure.network() = _NetworkRequestSupportFailure;
  // 2
  const factory RequestSupportFailure.server() = _ServerRequestSupportFailure;
  // 4
  const factory RequestSupportFailure.failedToRequestSupport() =
      _FailedToRequestSupport;
}
```

Now try to run `flutter pub run build_runner build`

**Comment by danagbemava-nc** [comment] 2021-09-23 13:36
Hi @skyloovportal 

I was experiencing your issue. However, after running `flutter pub upgrade --major-versions` and running `flutter clean && flutter pub get && flutter pub build build_runner --delete-conflicting-outputs`, it was able to build. You may need to update your dependencies.

The issue appeared to be coming from the `freezed` package, so if you do encounter it again, I would advise that you file the issue on the [freezed repo](https://github.com/rrousselGit/freezed/issues).

Closing as this is not an issue with `flutter` itself. 

Thank you

**Closed by danagbemava-nc** 2021-09-23 13:36 UTC
Labels: in triage

**Comment by skyloovportal** [comment] 2021-09-23 13:43
Actually the issue is not with packages because I have removed the freezed package and installed only chopper package but still the error is there 😐

**Comment by danagbemava-nc** [comment] 2021-09-23 13:51
If the issue is with `build_runner`, then you'll have to file it [here](https://github.com/dart-lang/build/issues) as `build_runner` is not maintained by the `flutter` team

**Comment by skyloovportal** [comment] 2021-09-23 18:00
Got it, I appreciate you help.

Thanks
