### ISSUE TITLE
Emulator physical keyboard backspace input throws

### ISSUE THREAD

**Issue by nt4f04uNd** [flutter/flutter#83883] opened 2021-06-03 12:27 UTC
## Steps to Reproduce

1. Run code sample on emulator
2. Focus on text field and type 1 letter
3. Press physical backspace (from your host machine), exception occurs, but visually the letter is removed
4. Now if you try to type a letter, two letters will appear (because the one at the beginning actually was not deleted)

**Expected results:** No exceptions

**Actual results:** Exception

<details>
  <summary>Logs</summary>

```
W/IInputConnectionWrapper( 4296): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper( 4296): getSelectedText on inactive InputConnection
W/IInputConnectionWrapper( 4296): getTextAfterCursor on inactive InputConnection
W/IInputConnectionWrapper( 4296): beginBatchEdit on inactive InputConnection
W/IInputConnectionWrapper( 4296): endBatchEdit on inactive InputConnection
E/MethodChannel#flutter/textinput( 4296): Failed to handle method call
E/MethodChannel#flutter/textinput( 4296): java.lang.IndexOutOfBoundsException: invalid composing range: (0, 0)
E/MethodChannel#flutter/textinput( 4296): 	at io.flutter.embedding.engine.systemchannels.TextInputChannel$TextEditState.<init>(TextInputChannel.java:713)
E/MethodChannel#flutter/textinput( 4296): 	at io.flutter.embedding.engine.systemchannels.TextInputChannel$TextEditState.fromJson(TextInputChannel.java:680)
E/MethodChannel#flutter/textinput( 4296): 	at io.flutter.embedding.engine.systemchannels.TextInputChannel$1.onMethodCall(TextInputChannel.java:91)
E/MethodChannel#flutter/textinput( 4296): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/MethodChannel#flutter/textinput( 4296): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#flutter/textinput( 4296): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:819)
E/MethodChannel#flutter/textinput( 4296): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#flutter/textinput( 4296): 	at android.os.MessageQueue.next(MessageQueue.java:335)
E/MethodChannel#flutter/textinput( 4296): 	at android.os.Looper.loop(Looper.java:183)
E/MethodChannel#flutter/textinput( 4296): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/MethodChannel#flutter/textinput( 4296): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter/textinput( 4296): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/MethodChannel#flutter/textinput( 4296): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/flutter ( 4296): [ERROR:flutter/lib/ui/ui_dart_state.cc(213)] Unhandled Exception: PlatformException(error, invalid composing range: (0, 0), null, java.lang.IndexOutOfBoundsException: invalid composing range: (0, 0)
E/flutter ( 4296): 	at io.flutter.embedding.engine.systemchannels.TextInputChannel$TextEditState.<init>(TextInputChannel.java:713)
E/flutter ( 4296): 	at io.flutter.embedding.engine.systemchannels.TextInputChannel$TextEditState.fromJson(TextInputChannel.java:680)
E/flutter ( 4296): 	at io.flutter.embedding.engine.systemchannels.TextInputChannel$1.onMethodCall(TextInputChannel.java:91)
E/flutter ( 4296): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/flutter ( 4296): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/flutter ( 4296): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:819)
E/flutter ( 4296): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter ( 4296): 	at android.os.MessageQueue.next(MessageQueue.java:335)
E/flutter ( 4296): 	at android.os.Looper.loop(Looper.java:183)
E/flutter ( 4296): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/flutter ( 4296): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter ( 4296): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/flutter ( 4296): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/flutter ( 4296): )
E/flutter ( 4296): #0      JSONMethodCodec.decodeEnvelope
package:flutter/…/services/message_codecs.dart:164
E/flutter ( 4296): #1      MethodChannel._invokeMethod
package:flutter/…/services/platform_channel.dart:156
E/flutter ( 4296): <asynchronous suspension>
E/flutter ( 4296):
W/TextInputPlugin( 4296): Changing the content within the the composing region may cause the input method to behave strangely, and is therefore discouraged. See https://github.com/flutter/flutter/issues/78827 for more details
W/IInputConnectionWrapper( 4296): getSelectedText on inactive InputConnection
W/IInputConnectionWrapper( 4296): getTextAfterCursor on inactive InputConnection
W/IInputConnectionWrapper( 4296): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper( 4296): getSelectedText on inactive InputConnection
W/IInputConnectionWrapper( 4296): getTextAfterCursor on inactive InputConnection
W/IInputConnectionWrapper( 4296): beginBatchEdit on inactive InputConnection
W/IInputConnectionWrapper( 4296): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper( 4296): endBatchEdit on inactive InputConnection

```

```
[√] Flutter (Channel master, 2.3.0-17.0.pre.120, on Microsoft Windows [Version 10.0.19041.985], locale ru-RU)
    • Flutter version 2.3.0-17.0.pre.120 at C:\dev\src\flutter
    • Upstream repository git@github.com:nt4f04und/flutter.git
    • Framework revision c42ec8592f (5 days ago), 2021-05-28 22:34:02 -0400
    • Engine revision aca8aa2335
    • Dart version 2.14.0 (build 2.14.0-165.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.7)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30621.155
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Community Edition (version 2020.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.3.3
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code (version 1.56.2)
    • VS Code at C:\Users\danya\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.22.0

[√] Connected device (5 available)
    • sdk gphone x86 (mobile)     • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • sdk gphone x86 arm (mobile) • emulator-5556 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)           • windows       • windows-x64    • Microsoft Windows [Version 10.0.19041.985]
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 90.0.4430.212
    • Edge (web)                  • edge          • web-javascript • Microsoft Edge 91.0.864.37

! Doctor found issues in 1 category.
```

</details>

**Comment by TahaTesser** [comment] 2021-06-03 15:53
Hi @nt4f04uNd 
Not able to reproduce the issue on an emulator with a physical keyboard or physical with Bluetooth keyboard 

<details> 
<summary>minimal code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: TextField(),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {},
      ),
    );
  }
}

``` 

</details>


<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel master, 2.3.0-17.0.pre.180, on Microsoft Windows [Version 10.0.19043.1023], locale en-US)
    • Flutter version 2.3.0-17.0.pre.180 at C:\Users\Taha\Code\flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 320f27713b (9 hours ago), 2021-06-03 02:49:03 -0400
    • Engine revision fe6d19b911
    • Dart version 2.14.0 (build 2.14.0-176.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_SDK_ROOT = C:\Users\Taha\Code\SDK
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.10.0)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.10.31321.278
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 4.2.0)
    • Android Studio at C:\Users\Taha\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[✓] IntelliJ IDEA Community Edition (version 2021.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.1.1
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.56.2)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.23.0

[✓] Connected device (5 available)
    • AOSP on IA Emulator (mobile) • emulator-5554 • android-x86     • Android 9 (API 28) (emulator)
    • Windows (desktop)            • windows       • windows-x64     • Microsoft Windows [Version 10.0.19043.1023]
    • Windows (UWP) (desktop)      • winuwp        • windows-uwp-x64 •
    • Chrome (web)                 • chrome        • web-javascript  • Google Chrome 91.0.4472.77
    • Edge (web)                   • edge          • web-javascript  • Microsoft Edge 91.0.864.37

• No issues found!
```

</details>

**Comment by nt4f04uNd** [comment] 2021-06-05 14:09
Did you do any special configurations for the keyboard, or were you using it like a regular input for your PC? The issue reproduces in the latter case (at least on Windows)

**Comment by TahaTesser** [comment] 2021-06-07 06:28
Hi @nt4f04uNd 
Not really, I am using a laptop, I tried the laptop's keyboard (no issue), the wireless keyboard on the emulator, and then tried a physical device with a Bluetooth keyboard. What keyboard are you using?

**Comment by darshankawar** [comment] 2021-07-09 12:23
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by darshankawar** 2021-07-09 12:23 UTC
Labels: in triage, waiting for customer response
