### ISSUE TITLE
Flutter app crash automatically.

### ISSUE THREAD

**Issue by lkrjangid1** [flutter/flutter#108859] opened 2022-08-03 06:28 UTC
Today I am working on my app and after some time automatically this happened. and shows me closing this app error dialog on my phone.

Error:
```
E/Dart    ( 8829): ../../third_party/dart/runtime/vm/deferred_objects.cc: 113: error: Can't locate continuation PC for deoptid 6 within dart:core_Duration_get__duration@0150898
E/Dart    ( 8829):
E/DartVM  ( 8829): version=2.17.6 (stable) (Tue Jul 12 12:54:37 2022 +0200) on "android_arm64"
E/DartVM  ( 8829): pid=8829, thread=8905, isolate_group=main(0x7561aea800), isolate=main(0x7561aeb000)
E/DartVM  ( 8829): isolate_instructions=755eec93c0, vm_instructions=755eec93c0
E/DartVM  ( 8829):   pc 0x000000755efdef8c fp 0x000000755d1fe240 /data/app/com.studyem.io.timemarks.test--c7LeAIbPmKsC4GM8HbLPA==/lib/arm64/libflutter.so+0x1aabf8c
E/DartVM  ( 8829): -- End of DumpStackTrace
E/DartVM  ( 8829):   pc 0x0000000000000000 fp 0x000000755d1fe5e8 sp 0x0000000000000000 [Stub] CallToRuntime
E/DartVM  ( 8829):   pc 0x000000755ad035dc fp 0x000000755d1fe610 sp 0x000000755d1fe5f8 [Stub] Deoptimize
E/DartVM  ( 8829):   pc 0x0000000000000000 fp 0x000000755d1fe668 sp 0x000000755d1fe620 [Stub] FrameAwaitingMaterialization
E/DartVM  ( 8829):   pc 0x0000000000000000 fp 0x000000755d1fe6a0 sp 0x000000755d1fe678 [Stub] FrameAwaitingMaterialization
E/DartVM  ( 8829):   pc 0x0000000000000000 fp 0x000000755d1fe6e8 sp 0x000000755d1fe6b0 [Stub] FrameAwaitingMaterialization
E/DartVM  ( 8829):   pc 0x0000007535b1e688 fp 0x000000755d1fe720 sp 0x000000755d1fe6f8 [Optimized] AnimationController._tick@581066280
E/DartVM  ( 8829):   pc 0x000000754dedfccc fp 0x000000755d1fe768 sp 0x000000755d1fe730 [Optimized] Ticker._tick@900494659
E/DartVM  ( 8829):   pc 0x0000007535b450b8 fp 0x000000755d1fe7a0 sp 0x000000755d1fe778 [Optimized] Ticker._tick@900494659
E/DartVM  ( 8829):   pc 0x0000007535c78560 fp 0x000000755d1fe878 sp 0x000000755d1fe7b0 [Optimized] _WidgetsFlutterBinding&BindingBase&GestureBinding&SchedulerBinding@446399801._invokeFrameCallback@897222615
E/DartVM  ( 8829):   pc 0x000000754debcd00 fp 0x000000755d1fe8d0 sp 0x000000755d1fe888 [Optimized] _WidgetsFlutterBinding&BindingBase&GestureBinding&SchedulerBinding@446399801.handleBeginFrame.<anonymous closure>
E/DartVM  ( 8829):   pc 0x00000075352d0b08 fp 0x000000755d1fe940 sp 0x000000755d1fe8e0 [Optimized] __InternalLinkedHashMap&_HashVMBase&MapMixin&_HashBase&_OperatorEqualsAndHashCode&_LinkedHashMapMixin@3220832.forEach
E/DartVM  ( 8829):   pc 0x0000007546b0f40c fp 0x000000755d1fe9b0 sp 0x000000755d1fe950 [Unoptimized] _WidgetsFlutterBinding&BindingBase&GestureBinding&SchedulerBinding@446399801.handleBeginFrame
E/DartVM  ( 8829):   pc 0x000000754deee9c4 fp 0x000000755d1fe9f8 sp 0x000000755d1fe9c0 [Optimized] _WidgetsFlutterBinding&BindingBase&GestureBinding&SchedulerBinding@446399801._handleBeginFrame@897222615
E/DartVM  ( 8829):   pc 0x000000754df7fe14 fp 0x000000755d1fea88 sp 0x000000755d1fea08 [Optimized] _rootRunUnary@4048458
E/DartVM  ( 8829):   pc 0x000000754debd560 fp 0x000000755d1feae0 sp 0x000000755d1fea98 [Optimized] _rootRunUnary@4048458
E/DartVM  ( 8829):   pc 0x000000754debe1c4 fp 0x000000755d1febc0 sp 0x000000755d1feaf0 [Optimized] _CustomZone@4048458.runUnaryGuarded
E/DartVM  ( 8829):   pc 0x000000754df11ce8 fp 0x000000755d1fec10 sp 0x000000755d1febd0 [Optimized] _invoke1@15065589
E/DartVM  ( 8829):   pc 0x000000754deee894 fp 0x000000755d1fec70 sp 0x000000755d1fec20 [Optimized] _beginFrame@15065589
E/DartVM  ( 8829):   pc 0x000000755ad02ff4 fp 0x000000755d1fed50 sp 0x000000755d1fec80 [Stub] InvokeDartCode
F/libc    ( 8829): Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 8905 (1.ui), pid 8829 (.timemarks.test)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'Infinix/H576D/Infinix-X625C:9/PPR1.180610.011/D-IN-200924V141:user/release-keys'
Revision: '0'
ABI: 'arm64'
pid: 8829, tid: 8905, name: 1.ui  >>> com.studyem.io.timemarks.test <<<
signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
Abort message: '../../third_party/dart/runtime/vm/deferred_objects.cc: 113: error: Can't locate continuation PC for deoptid 6 within dart:core_Duration_get__duration@0150898
'
    x0  0000000000000000  x1  00000000000022c9  x2  0000000000000006  x3  0000000000000008
    x4  8000000000000000  x5  8000000000000000  x6  8000000000000000  x7  0000000000000080
    x8  0000000000000083  x9  0000007604c39b40  x10 fffffff87ffffbdf  x11 0000000000000001
    x12 000000755d1fdb08  x13 0000000000000038  x14 ffffffffffffffff  x15 00002116da762fdb
    x16 0000007604c722c8  x17 0000007604bb02d8  x18 000000755d1fd39a  x19 000000000000227d
    x20 00000000000022c9  x21 0000000000000083  x22 00000075476169c0  x23 0000007575bc8ab8
    x24 0000000000000016  x25 000000755d121000  x26 0000007561bc2800  x27 00000074000102a0
    x28 0000000600000074  x29 000000755d1fe260
    sp  000000755d1fe220  lr  0000007604ba4a90  pc  0000007604ba4abc
backtrace:
    #00 pc 0000000000021abc  /system/lib64/libc.so (abort+124)
    #01 pc 00000000019955d4  /data/app/com.studyem.io.timemarks.test--c7LeAIbPmKsC4GM8HbLPA==/lib/arm64/libflutter.so (offset 0x156e000)
    #02 pc 000000000000803d  <anonymous:0000007400000000>
Lost connection to device.
Exited (sigterm)

```

Flutter doctor:

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.0.5, on Microsoft Windows [Version 10.0.22000.795], locale en-IN)
[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Build Tools 2019 16.11.14)
[√] Android Studio (version 2021.2)
[√] VS Code (version 1.69.2)
[√] Connected device (4 available)
[√] HTTP Host Availability

• No issues found!
```

**Comment by augustt0** [comment] 2022-08-03 06:48
Hi @lkrjangid1! This issue may be related to #98682

**Comment by huycozy** [comment] 2022-08-03 10:50
Hi @lkrjangid1 
I see there's an open issue #98682 that has similar logs to this from issue's comments.
You can leave there your comment and react an upvote to the original comment will help to raise the issue.
Closing as a duplication, so please follow up on it for further updates.

**Closed by huycozy** 2022-08-03 10:50 UTC
Labels: r: duplicate

**Comment by mraleph** [comment] 2022-08-03 13:03
Duplicate of #103268
