### ISSUE TITLE
Would like a plugin for In-App Payments (IAP)

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#9591] opened 2017-04-25 22:54 UTC
Or at least help building one.  Requested by @lukef

**Comment by saads** [comment] 2017-06-11 01:29
Second this. For monetization purposes we need both IAP and ad support. These are both are really critical to getting traction for flutter in the developer community.

**Comment by saads** [comment] 2017-06-11 01:31
@sethladd

**Comment by sethladd** [comment] 2017-06-12 15:51
@saads thanks for the feedback!

**Comment by saads** [comment] 2017-06-13 02:16
@sethladd no worries! Any road map for this? Or any way I can help to accelerate bringing in app purchases to Flutter? Got an urgent need for it and really want to be able to use the platform because it's so helpful with accelerating development. Let me know! :)

**Comment by eseidelGoogle** [comment] 2017-06-13 06:26
We have no ETA on writing this plugin ourselves.  However you can always just use normal iOS or Android APIs or SDKs from the Objective-C/Java parts of your app and then communicate to the Flutter parts via https://flutter.io/platform-channels/.

This bug is about bundling those bits up so that folks can use common payment APIs w/o having to write any Objective-C/Java code themselves, which means taking that code you could write above, but then also bundling it up into a https://flutter.io/platform-plugins/ container.

**Comment by JackAppDev** [comment] 2017-10-18 23:23
I made an iOS implementation https://github.com/JackAppDev/flutter_iap/ if someone wants to help me out by adding android support that would be great.

**Comment by sethladd** [comment] 2017-10-19 15:02
Thanks very much for the iOS implementation!

**Comment by xster** [comment] 2017-12-16 02:19
Tentatively closing this. The plugin @JackAppDev created seems to support iOS and Android.

**Comment by frederickcook** [comment] 2017-12-17 22:10
Note that IAP (in-app payment) functionality (such as in the flutter_iap plugin) is a subset of Apple Pay used for selling digital goods of which Apple takes a 30% cut. This plugin is not useful for an app that sells physical goods or services and simply uses Apple Pay as a simpler alternative to credit card input.

**Comment by VolodymyrLykhonis** [comment] 2018-01-28 19:38
Linking [a plugin](https://github.com/VolodymyrLykhonis/flutter_billing) I am working on that features non-consumable products for iOS and Android with products caching and purchases restoration.

**Comment by MarkOSullivan94** [comment] 2018-01-29 10:58
@JackAppDev would it be possible to get @frederickcook's post in your README.md for your plugin? Would make it clear to anyone using your plugin that Apple will take a 30% cut.

**Comment by mit-mit** [comment] 2018-05-23 13:19
Renaming this back to In-app Purchases (as it started originally). I logged https://github.com/flutter/flutter/issues/17837 to track physical good transactions

**Comment by mit-mit** [comment] 2018-05-23 13:56
We expect the present plugin to wrap the following APIs:

Android: Google Play Billing
https://developer.android.com/google/play/billing/billing_overview

iOS: In-App Purchase
https://developer.apple.com/in-app-purchase/

**Comment by gluix20** [comment] 2018-06-18 21:35
@mit-mit do you have a tentative release date for the plugin?

**Comment by mit-mit** [comment] 2018-06-19 14:23
Sorry I don't, we had a bit of a change on the personnel side here.

**Comment by gluix20** [comment] 2018-06-19 17:53
No problem @mit-mit. 

What do you guys think is the better approach now to receive iOS/Android payments? We need to offer auto-renewable subscriptions to users on both platforms. The above plugins works for that or do you think platform channel approach is the way? Appreciate.

**Comment by mit-mit** [comment] 2018-06-20 14:04
Yes, I think platform channels should work great for this.

**Comment by lukepighetti** [comment] 2018-06-27 00:22
Rubber is about to hit the road and I need support for IAP. Are there any options available or am I stepping away from Flutter for a few months while it matures?

**Comment by alamboley** [comment] 2018-07-24 16:35
Adding my 2 cents here, IAP is a must have plugin which should be managed by the flutter team. There are plugins which works partially... but don't provide enough informations for validate iap on server side. IAP is critical on both side, customer & developer.

**Comment by lukepighetti** [comment] 2018-07-24 21:44
Yeah, I hate to "second" this, but I'm looking around and I haven't found an IAP plugin that is ready for use. I have invested considerable hours into writing this Flutter app and if I cannot monetize it with subscription IAPs I'm kinda up a creek.

**Comment by lukef** [comment] 2018-07-24 22:17
It's doable today (as @mit-mit says) using platform channels. You just have to write the code yourself. It's decently trivial to do so. There probably won't be a plug-in in a short time frame but I can't speak for Google 😀

**Comment by seenickcode** [comment] 2018-07-25 00:55
Hey guys, I very much am interested in this as well and well be very much
in need of this next month but I'm afraid I wouldn't rely on this being a
major priority for Google since someone else just as well can come along to
write this themselves. I plan to use platform channels myself by the end of
Aug if nothing comes of this by then.

**Comment by lukepighetti** [comment] 2018-07-25 02:07
There are two packages that appear to be prime for community development. One has Subscriptions [flutter_payments](https://pub.dartlang.org/packages/flutter_payments) and the other seems to have more community use [flutter_iap](https://pub.dartlang.org/packages/flutter_iap), hard to say from here.

**Comment by alamboley** [comment] 2018-07-25 08:04
@lukef yes indeed, it's doable... and I would even say: easily doable to have something working. In the past I made several Native Extensions code (equivalent to Flutter's  platform channel but for Adobe AIR).
But my main concern is IAPs are one of the most critical part of an app, regarding payment process for the customer (with restoring purchase, subscription...), and validation of the payment from developer point of view. It's not just calling some native code... but to be sure all the process works well and in several cases. We already had strange bugs in ANEs.
In the Adobe AIR community, this plugin is sold by companies with proper documentation & support. I wouldn't mind paying some bucks here too for this flutter plugin. Obviously, it would be even better to have it from flutter team directly as an open source plugin.

**Comment by eseidelGoogle** [comment] 2018-07-25 13:49
@alamboley This is certainly on our list, just hasn't reached the top yet.  Right now all of our plugin-focused engineers are busy working on Maps, WebView and Add-flutter-to-an-existing-application workflows.  We're also hiring as fast as we can: https://twitter.com/_eseidel/status/1012025593628512256 :)

**Comment by lukepighetti** [comment] 2018-07-25 14:05
You can hire me to be lead cheerleader and liaison for newbie RN devs trying to use Flutter!

**Comment by VolodymyrLykhonis** [comment] 2018-07-25 14:15
You can use this plugin for basic non consumable products. I had to create it for my app. https://pub.dartlang.org/packages/flutter_billing

**Comment by alamboley** [comment] 2018-08-06 09:35
Wow @dooboolab , I dreamed a port of your React Native iap plugin to flutter! Will test it asap!

**Comment by dooboolab** [comment] 2018-08-06 10:01
@alamboley Thanks. I need more time for testing tough. Will do it as much as I can taking my time.

**Comment by alamboley** [comment] 2018-08-08 07:15
So after some test & help, I can say we finally have an awesome flutter plugin for iap. Many many thanks to @dooboolab!

**Comment by lukepighetti** [comment] 2018-08-08 16:16
@dooboolab has saved this community as far as I am concerned. I just tested consumable on iOS and Android and it works awesome.

**Comment by InMatrix** [comment] 2018-08-30 16:46
Since we now have a community-contributed IAP plugin, do we still need to keep this issue open?

**Comment by efortuna** [comment] 2018-08-30 17:10
What's the verdict from people that have tested the plugin -- does it cover what they need?

**Comment by opensourcegps** [comment] 2018-08-30 17:55
It would be great to have solid **official implementation for IAP**. All current plugins are not complete and lack testing. It's really sad that flutter monetization options are so complicated and limited. 

Basically now it's not possible to have all IAP options in a secure and stable way. 

Tested following plugins:

https://github.com/VolodymyrLykhonis/flutter_billing 

\+ Version 0.2.3 is stable for simple purchases + receipts. 
\- later versions include consumables and android subscriptions. However also some bugs and crashes.
\- needs ios subscriptions, slow development. 

https://github.com/dooboolab/flutter_inapp_purchase

\+ This plugin works great locally on test devices, and great features set. Suppose to have it all.
\+ fast development.
\- no receipts for already purchased products
\- lots of crashes in Google Play console from live users.

https://github.com/JackAppDev/flutter_iap

\- only lightly tested. Not enough features in the description.

I think that's all your options now. Still no perfect plugin

**Comment by dooboolab** [comment] 2018-08-30 20:39
@opensourcegps Trying to solve the crashing report in the console as soon as possible. What version of `flutter_inapp_purchase` are you using?

**Comment by lukepighetti** [comment] 2018-08-30 20:43
@opensourcegps I am using `flutter_inapp_purchase` (just finished Alpha/Beta and releasing prod this week) with iOS and Android doing consumable purchases and auto-renewable subscriptions and haven't had any issues with any of the things you're mentioning.

**Comment by dooboolab** [comment] 2018-08-31 06:13
Yeah. I thought it was resolved currently.

**Comment by opensourcegps** [comment] 2018-08-31 07:51
@dooboolab @lukepighetti I really appreciate your work, your plugin looks awesome, thank you for creating it and contributing. I just listed my experiences with flutter IAP. 

Regarding the fix, it was done with this commit: https://github.com/dooboolab/flutter_inapp_purchase/commit/0afa99d49f22717b2e79ebfe265f7cf15c100fae

So in case problem was real, it's now hidden forever with try/catch. Will it still affect sales? Nobody knows. However if answer is Yes, you can imagine consequences for flutter community. If you miss 10% of sales and there are no errors, it's much worse. 

Creating official implementation by Google will really help here.

**Comment by audkar** [comment] 2018-08-31 08:06
In this case I must agree. Such 'fixes' shouldn't exist in payments library. 
IAP is most critical functionality. Clients are very sensitive to issues/bugs which are related to purchases and money. I would expect rock solid quality official library.

**Comment by dooboolab** [comment] 2018-08-31 08:27
@opensourcegps @audkar Yeah, I can make this rock solid if Google recruits me lol. Currently, I need to work on other projects to survive. However, I'll keep this improved taking some of my time in a break. I am also seeking contributors to help me out. If you post some wishlists in issue, I'll monitor it and update it in future. Thank you.

**Comment by lukepighetti** [comment] 2018-08-31 13:12
Not to sound preachy but I was in both of your positions and found flutter_inapp_purchase to be the closest of all implementations to being usable. I too would like Google to offer something rock solid and cohesive, but until they are willing to do that, which seems like it's going to be a long time, putting our money where our mouth is and improving flutter_inapp_purchase is, in my opinion the best use of community efforts around IAPs.

**Comment by VolodymyrLykhonis** [comment] 2018-08-31 16:50
Hi All, I'm author of one the plugins listed here. I would like to explain "slow development". Since there is a commitment from Flutter team to provide such plugin, I have frozen development from my side but any contributions are welcomed.

Instability was introduced by recent commits to flutter_billing plugin.

**Comment by dooboolab** [comment] 2018-08-31 18:50
@opensourcegps It isn't anything and I am trying to be more informative with the earlier issue. The issue you've described above is a matter of handling bridge. I bet @lukepighetti didn't have that problem in earlier version either. You should check yourself when you invoke your methods, with some suspicions where the problems may occur. If you see something there, you could report that in [issue](https://github.com/dooboolab/flutter_inapp_purchase).

I was just trying to fix crashing for whatever reason. However, if you use some error tracking platform like `sentry`, you will be able to grab that error message and you won't get totally blind with this. I was sure that it was much better than just crashing even though I've not experienced this in my app.

Let's make this better together. I think we are not that behind.

**Comment by opensourcegps** [comment] 2018-09-01 09:41
@dooboolab No complains to "fix crashing for whatever reason". It was just to demonstrate why we need official IAP plugin from Google.

@eseidelGoogle if you could give us some timeline/ETA for official IAP plugin, that would be awesome. This is such a critical plugin to switch current apps to flutter, but instead we got things like "firebase_remote_config". 

Maybe it's planned in 1 month and all community developers/contributors will just waste their time with their own plugins at the moment.

**Comment by eseidelGoogle** [comment] 2018-09-03 16:59
I agree that facilitating easy monetization of apps is important.  I'm not aware of anyone from my team working on this issue at this time.  We actively track [upvoted issues from the community](https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc), as well as Flutter [user survey results](https://medium.com/flutter-io/what-weve-learned-from-the-july-2018-flutter-user-survey-cbbf1e04370c) to aid with our work prioritization.  Hopefully as we complete higher priority requests we'll be able to help here as well.  Thankfully, as others noted, there are several in-progress solutions from others in the (awesome) Flutter community already.

CC @cbracken @bparrishMines for awareness.

**Comment by lukepighetti** [comment] 2018-09-17 14:15
@eseidelGoogle The problem with that approach is it rewards issues that have the most views, but are not the most pressing. I would argue that monetization has become more important since Google announced that Beta was production ready.

**Comment by eseidelGoogle** [comment] 2018-09-17 17:56
@lukepighetti The upvotes list is just one of many prioritization inputs we have to balance. :/  But it is an important one.  It's one of the ways we seek to balance the needs of the Flutter users we can directly here from (large companies, teams at Google, etc.) vs. the many many users of Flutter who we don't directly speak to.  It's imperfect, but it's something, I hope.

**Comment by seenickcode** [comment] 2018-09-17 21:11
@eseidelGoogle <https://github.com/eseidelGoogle>, to chime in here:
judging by all the folks I see diving into Flutter, the folks needing IAP
will for now especially be in a niche category, therefore this issue will
naturally have far less upvotes, of course. Yet, a critical decision-making
factor in "breaking through" to larger companies, are indeed key features
like these. The company I work at, Equinox
<https://en.wikipedia.org/wiki/Equinox_Fitness>, having 20k+ employees
globally, is a great example. We use React Native now and one of the
critical things pitching Flutter to my CIO is waiting for specific key
features. For major industry adoption, high profile companies like this
need to demonstrate they can confidently adopt Flutter.

So I'd ask to give certain strategic features like this a bump in the
prioritization department and it will pay off towards faster corporate
adoption.

**Comment by willvlad** [comment] 2018-10-20 11:13
Agreed that having an official flutter payments plugin is critical

**Comment by pulyaevskiy** [comment] 2018-11-28 20:44
For those who are still looking for alternatives, here is my take on this: https://pub.dartlang.org/packages/iap

**Comment by zoechi** [comment] 2019-01-08 10:15
Work in progress https://github.com/flutter/plugins/tree/master/packages/in_app_purchase

**Comment by Dylan-Phoon** [comment] 2019-01-16 02:18
@zoechi @mklim can we get an ETA for when this package will be available? 1 week? 1 month? 3 months?

**Comment by pierotofy** [comment] 2019-02-22 20:04
I second other people's comments that having an official IAP plugin from Google would inspire confidence in adopting the platform. The risk of not having a stable and reliable monetization feature is a big stopper for considering adoption of the platform. :+1: Nice to see work done in https://github.com/flutter/flutter/issues/24540 toward this effort.

**Comment by Hixie** [comment] 2019-02-27 00:56
(I set the milestone for a minimal viable product version of the plugin; after that we expect to have more to add, but we'll do that as additional later work in other bugs.)

**Comment by mklim** [comment] 2019-03-26 23:17
This is taking more time than we originally estimated so I'm adjusting the milestone. Thank you everyone for your patience.

**Comment by patreu22** [comment] 2019-04-24 14:52
Hey there, just out of curiosity: Does anybody now why the IAP-support is listed in all Feature lists for Flutter 1.2? As we can see it's still not released yet, is it?

**Comment by mklim** [comment] 2019-05-08 01:18
This is now available in beta: https://pub.dartlang.org/packages/in_app_purchase. Thanks everyone for waiting! Please file any feedback as new issues on the tracker.

**Closed by mklim** 2019-05-08 01:18 UTC
Labels: p: in_app_purchase, plugin, severe: new feature

**Comment by LinusU** [comment] 2019-05-09 13:10
@mklim sorry if this is not the correct place to ask this, I was just wondering about the background to having a global event-emitter and having the purchase methods not return anything. To me it seems like a much more natural API to have e.g. `buyNonConsumable` return a `Future<PurchaseDetails>`. This is indeed also how the other IAP Flutter plugins behave.

The drawbacks for me is that it forces me to split up the logic around my IAPs into different parts of the app, and makes it harder to reason about the flow of the purchase. E.g. I have a page that handles signup which requires a subscription. That page then needs to create an account with our backend, to which it also sends the receipt id from the subscription.

Now I need to coordinate two different pieces of information from two parts of the app. 1) the user details from the page state, and 2) the purchase id from the global listener.

Had `buyNonConsumable` instead returned the `PurchaseDetails` this would be very simple:

```dart
onPressed: () async {
  final purchaseDetails = await InAppPurchaseConnection.instance.buyNonConsumable(...)
  await FoobarApiClient.instance.signup(_emailController.text, purchaseDetails.verificationData)
}
```

**Comment by adriancmurray** [comment] 2019-05-09 13:33
Just another flutter user here with some thoughts on this: the global listener allows us to listen for events coming from the App Store itself. Which you’d require a background listener regardless of having a future option, making the future you’re proposing a bit redundant. I don’t think you are forced to put the logic in two places, though you are a bit more forced to use something like scopedmodel or bloc. I am placing my listener at the top of my tree in a stateful widget that’s attached to a scopedmodel and this is where I’m handling all of my IAP logic. I have a feeling they choose to do it this way to help force developers to work in a manner similar to this while also choosing the solution that allows for you to listen to the app stores or for whether or not you’ve marked the purchase as completed even if the app crashes, which is needed by apple. 

Good job, team Flutter!

**Comment by LinusU** [comment] 2019-05-09 13:53
> [...] making the future you’re proposing a bit redundant.

I personally don't feel that it makes it redundant. In most cases, resuming an interrupted purchase is a different flow than when making a new purchase. E.g. in my case, resuming an interrupted purchase would involve asking the user for the signup details again, since if the app crashed I won't have them.

> I don’t think you are forced to put the logic in two places, though you are a bit more forced to use something like scopedmodel or bloc.

That could absolutely work, but it's quite a lot more work than just `await`-ing a `Future`. While using e.g. the BLoC pattern is certinely good in many apps, I don't think that plugins should conform themselves to a specific pattern. It seems like there should be easy to implement the BLoC pattern even if `buyNonConsumable` returned a future with purchase details.

> I have a feeling they choose to do it this way to help force developers to work in a manner similar to this [...]

If this was indeed a deliberate decision to force developers to use the plugin in a particular way, I think that we should add documentation for that to make it clear how we're expected to use it. I'm still not sure I'm understanding how to implement crash-resistance, and what events will be emitted if my app crashes during a purchase. If this is as you say "needed by apple" I think it's even more important to document it, so that developers (including me ☺️) knows how to properly implement this.

> Good job, team Flutter!

Totally agree, I'm very happy for both Flutter and this plugin! Just trying to see if I can help out lowering the barrier for developers to use this plugin ☺️

**Comment by hugocbpassos** [comment] 2019-05-09 14:06
I don't know what led Flutter team to this approach, but it is not what I expected. In my conception, `Stream`s are preferable when you are supposed to receive lots of responses that updates the screen accordingly and do not block user experience. In this case, you are making a request and the user is suppose to continue to use the app only a response arrives. IAP are pretty simple and straightforward, there's no need to separate the request and response in two different places, unless the developers had no other option, which I think is not the case, since other similar plugins do use `Future`s.

**Comment by adriancmurray** [comment] 2019-05-09 14:09
The interruption was a side note but you’ll still need a global listener for when users make a purchase within the store itself. That’s the part that seemed redundant since that should be the same flow as a direct purchase and you’d need user details there as well. 

The requirement by apple is in the documentation when you look in the files themselves. It’s where I found out about the requirement. 

My point if it was designed to force a specific pattern was pure speculation. It just seems like something you should do for a flow that can handle any events that could potentially happen in one place. This means you can also catch when a user changes their subscription. Another thing you’d need a listener for.

**Comment by mklim** [comment] 2019-05-09 18:47
Thanks all, I responded over in flutter/flutter#32423. This issue is already pretty long and was originally just tracking the existence of the plugin at all, so I think it would be better to have new specific discussions about the actual plugin in new and separate issues so they're easier to follow and track. Feel free to cc me directly on them too.
