### ISSUE TITLE
flutter_gallery__start_up timeToFirstFrameMicros regressed 

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#30401] opened 2019-04-02 20:50 UTC
Sometime around 2019-02-27, `flutter_gallery__start_up timeToFirstFrameMicros` got about 10% slower.

cc @HansMuller @jason-simmons

**Comment by HansMuller** [comment] 2019-04-02 21:48
@liyuqian Is it possible that https://github.com/flutter/flutter/pull/28537/ had an impact on gallery start-up time?

**Comment by liyuqian** [comment] 2019-04-02 23:51
@HansMuller @Hixie that's definitely due to #28537. It's a tradeoff between worst frame time and start up time. I rebaselined other benchmarks and forgot this one. Rebaselining it now.

**Comment by liyuqian** [comment] 2019-04-02 23:52
Rebaselined. Close the issue as the regression is expected.

**Closed by liyuqian** 2019-04-02 23:52 UTC
Labels: f: material design, framework, severe: performance, severe: regression
