### ISSUE TITLE
MacOS: Could not build the application for the simulator. Error launching application on iPhone 11.

### ISSUE THREAD

**Issue by andrespd99** [flutter/flutter#63348] opened 2020-08-09 22:27 UTC
## Problem

I recently started having a problem launching flutter apps. They seem to work the first time I compile them, but after relaunching the app once, It won't compile again. I found a way around this problem by deleting it and cloning the repo again but that is not an ideal fix. 

It happens with any app, even my old apps which worked fine on an older machine. 

This is happening on MacOS Catalina 10.15.5; Xcode 11.6 (but app is running in Xcode 9.3)

## Console Logs

**flutter run --verbose**
```
...
Running shutdown hooks
               [        ] Shutdown hooks complete
               [   +1 ms] exiting with code 1
               Command PhaseScriptExecution failed with a nonzero exit code
           
           
[  +70 ms] Could not build the application for the simulator.
[   +2 ms] Error launching application on iPhone 11.
[   +3 ms] "flutter run" took 28,721ms.
[   +8 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:591:7)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand
(package:flutter_tools/src/runner/flutter_command.dart:860:18)
           #3      _rootRunUnary (dart:async/zone.dart:1198:47)
           #4      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #5      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #7      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #8      Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #11     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
           #12     _rootRunUnary (dart:async/zone.dart:1198:47)
           #13     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #14     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #16     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #17     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #18     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
           #19     _rootRun (dart:async/zone.dart:1190:13)
           #20     _CustomZone.run (dart:async/zone.dart:1093:19)
           #21     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #22     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
           #23     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #24     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #25     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
           #26     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
           
           
[ +255 ms] ensureAnalyticsSent: 253ms
[   +2 ms] Running shutdown hooks
[        ] Shutdown hook priority 4
[   +1 ms] Shutdown hooks complete
[        ] exiting with code 1
```

**flutter doctor -v**
```
[✓] Flutter (Channel stable, 1.20.1, on Mac OS X 10.15.5 19F101, locale en-US)
    • Flutter version 1.20.1 at /Users/andrespacheco/Development/flutter
    • Framework revision 2ae34518b8 (4 days ago), 2020-08-05 19:53:19 -0700
    • Engine revision c8e3b94853
    • Dart version 2.9.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/andrespacheco/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[✓] Connected device (1 available)
    • iPhone 11 (mobile) • 208BC4B9-4934-462A-B7C8-9CBC7ABD5B48 • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-13-6 (simulator)

• No issues found!
```

**Xcode error log**
```
CodeSign /Users/andrespacheco/Documents/Development/Flutter/formvalidator/build/ios/Debug-iphonesimulator/Runner.app (in target 'Runner' from project 'Runner')
    cd /Users/andrespacheco/Documents/Development/Flutter/formvalidator/ios
    export CODESIGN_ALLOCATE=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/codesign_allocate
    
Signing Identity:     "-"

    /usr/bin/codesign --force --sign - --entitlements /Users/andrespacheco/Documents/Development/Flutter/formvalidator/build/ios/Runner.build/Debug-iphonesimulator/Runner.build/Runner.app.xcent --timestamp=none /Users/andrespacheco/Documents/Development/Flutter/formvalidator/build/ios/Debug-iphonesimulator/Runner.app

/Users/andrespacheco/Documents/Development/Flutter/formvalidator/build/ios/Debug-iphonesimulator/Runner.app: resource fork, Finder information, or similar detritus not allowed
Command CodeSign failed with a nonzero exit code
```

```flutter analyze ``` threw no errors.

**Comment by TahaTesser** [comment] 2020-08-10 15:43
Hi @andrespd99 
This could be because of you haven't selected team id or code signing issue, reselect team, make sure certificate revoke isn't there as option, if it is there, click revoke 

```
Signing Identity:     "-"

    /usr/bin/codesign --force --sign - --entitlements /Users/andrespacheco/Documents/Development/Flutter/formvalidator/build/ios/Runner.build/Debug-iphonesimulator/Runner.build/Runner.app.xcent --timestamp=none /Users/andrespacheco/Documents/Development/Flutter/formvalidator/build/ios/Debug-iphonesimulator/Runner.app

/Users/andrespacheco/Documents/Development/Flutter/formvalidator/build/ios/Debug-iphonesimulator/Runner.app: resource fork, Finder information, or similar detritus not allowed
Command CodeSign failed with a nonzero exit code
```

Not sure why and how you're running " running in Xcode 9.3` on iPhone 11. Please provide more details
Sine you already Xcode 11,  does this issue occurs with XCode 11?

Can you please provide your `flutter run --verbose` and a complete reproducible minimal code sample or step by step to reproduce the issue 
Thank you

**Comment by bartonhammond** [comment] 2020-08-10 22:22
I started having these same problems after upgrading flutter to 1.20.x.  I then did went to  `flutter version 1.17.5` and it builds fine now.  I've attached the log (it's too big for a comment)  from `flutter run --verbose` from when it was failing.  I'll stay on `1.17.5` for now.
[flutter-run-verbose.txt](https://github.com/flutter/flutter/files/5053709/flutter-run-verbose.txt)

**Comment by rbluethl** [comment] 2020-08-12 06:45
I've got the same problem with Flutter 1.20.1.

Verbose Output:

```
[ +462 ms] Could not build the application for the simulator.
[   +2 ms] Error launching application on iPhone 11.
[   +3 ms] "flutter run" took 51,023ms.
[   +5 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:591:7)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:860:18)
           #3      _rootRunUnary (dart:async/zone.dart:1198:47)
           #4      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #5      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #7      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #8      Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #11     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
           #12     _rootRunUnary (dart:async/zone.dart:1198:47)
           #13     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #14     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #16     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #17     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #18     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
           #19     _rootRun (dart:async/zone.dart:1190:13)
           #20     _CustomZone.run (dart:async/zone.dart:1093:19)
           #21     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #22     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
           #23     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #24     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #25     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
           #26     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

**Comment by santoni98** [comment] 2020-08-20 12:03
try `flutter clean`

**Comment by hashemp206** [comment] 2020-08-26 09:47
> try `flutter clean`
it worked for me

**Comment by kherel** [comment] 2020-08-27 07:41
same issue, `flutter clean` helps but I have to do it all the time.

**Comment by darshankawar** [comment] 2020-09-02 10:26
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by darshankawar** 2020-09-02 10:26 UTC
Labels: in triage, waiting for customer response

**Comment by Sultanmahfouz** [comment] 2021-02-23 14:32
<img width="1179" alt="Screenshot 1442-07-11 at 5 31 40 PM" src="https://user-images.githubusercontent.com/63063709/108858238-fe161300-75fc-11eb-88e7-8165259f0b5b.png">
by removing the tick mark in run script: for install builds only solved my problem
