### ISSUE TITLE
DropdownMenu experiences screen jitter issues when used within TabBarView alongside nested navigation

### ISSUE THREAD

**Issue by hiepvip99** [flutter/flutter#139113] opened 2023-11-28 04:14 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

"Step 1: Create a tab bar with nested navigation inside.
Step 2: Create a sub-route and use DropdownMenu on that route."

### Expected results

After changing the data and clicking on it again, the DropdownMenu will not experience screen jitter 

### Actual results

After changing the data and clicking on it again, the DropdownMenu will experience screen jitter

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> with TickerProviderStateMixin {
  late TabController _tabController;

  @override
  void initState() {
    super.initState();
    _tabController = TabController(length: 2, vsync: this);
  }

  @override
  void dispose() {
    _tabController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Nested TabBar Example'),
        bottom: TabBar(
          tabs: [
            Tab(text: 'Tab 1'),
            Tab(text: 'Tab 2'),
          ],
          controller: _tabController,
        ),
      ),
      body: TabBarView(
        controller: _tabController,
        children: [
          FirstTabScreen(),
          SecondTabScreen(),
        ],
      ),
    );
  }
}

class FirstTabScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Navigator(
      onGenerateRoute: (settings) {
        return MaterialPageRoute(
          builder: (context) => FirstTabContentScreen(),
        );
      },
    );
  }
}

class FirstTabContentScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('First Tab Content'),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Text('Content for First Tab'),
            SizedBox(height: 20),
            ElevatedButton(
              onPressed: () {
                Navigator.push(
                  context,
                  MaterialPageRoute(
                    builder: (context) => FirstTabChildScreen(),
                  ),
                );
              },
              child: Text('Go to Child Screen'),
            ),
          ],
        ),
      ),
    );
  }
}

class FirstTabChildScreen extends StatefulWidget {
  @override
  State<FirstTabChildScreen> createState() => _FirstTabChildScreenState();
}

const List<String> list = <String>['One', 'Two', 'Three', 'Four'];

class _FirstTabChildScreenState extends State<FirstTabChildScreen> {
  String dropdownValue = list.first;
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('First Tab Child Screen'),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Text('Content for First Tab Child Screen'),
            SizedBox(height: 20),
            DropdownButton<String>(
              value: dropdownValue,
              icon: const Icon(Icons.arrow_downward),
              elevation: 16,
              style: const TextStyle(color: Colors.deepPurple),
              underline: Container(
                height: 2,
                color: Colors.deepPurpleAccent,
              ),
              onChanged: (String? value) {
                // This is called when the user selects an item.
                setState(() {
                  dropdownValue = value!;
                });
              },
              items: list.map<DropdownMenuItem<String>>((String value) {
                return DropdownMenuItem<String>(
                  value: value,
                  child: Text(value),
                );
              }).toList(),
            ),
            ElevatedButton(
              onPressed: () {
                Navigator.pop(context); // Go back to the parent screen
              },
              child: Text('Go Back'),
            ),
          ],
        ),
      ),
    );
  }
}

class SecondTabScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Navigator(
      onGenerateRoute: (settings) {
        return MaterialPageRoute(
          builder: (context) => Scaffold(
            appBar: AppBar(
              title: Text('Second Tab'),
            ),
            body: Center(
              child: Text('Content for Second Tab'),
            ),
          ),
        );
      },
    );
  }
}

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.16.0, on Microsoft Windows [Version 10.0.19045.3693], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.6.5)
[√] Android Studio (version 2022.2)
[√] VS Code (version 1.84.2)
[√] Connected device (3 available)
[√] Network resources

! Doctor found issues in 2 categories.
```

</details>

**Comment by huycozy** [comment] 2023-11-28 10:52
Hi @hiepvip99 
I checked this on `Realme 6, Android 11` but can't see the issue. 

Which platform are you checking on? And please also share the device information as well (OS, model). It would be useful if you could share a recorded video demo for this. Thanks!

**Comment by hiepvip99** [comment] 2023-11-29 01:58
I apologize for this confusion as I tried DropdownButton and DropdownMenu, and the issue only occurred in DropdownMenu. You can test it with this code snippet (This issue occurs on both Android, Web and iOS.): @huycozy 
```dart

import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> with TickerProviderStateMixin {
  late TabController _tabController;

  @override
  void initState() {
    super.initState();
    _tabController = TabController(length: 2, vsync: this);
  }

  @override
  void dispose() {
    _tabController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Nested TabBar Example'),
        bottom: TabBar(
          tabs: [
            Tab(text: 'Tab 1'),
            Tab(text: 'Tab 2'),
          ],
          controller: _tabController,
        ),
      ),
      body: TabBarView(
        controller: _tabController,
        children: [
          FirstTabScreen(),
          SecondTabScreen(),
        ],
      ),
    );
  }
}

class FirstTabScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Navigator(
      onGenerateRoute: (settings) {
        return MaterialPageRoute(
          builder: (context) => FirstTabContentScreen(),
        );
      },
    );
  }
}

class FirstTabContentScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('First Tab Content'),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Text('Content for First Tab'),
            SizedBox(height: 20),
            ElevatedButton(
              onPressed: () {
                Navigator.push(
                  context,
                  MaterialPageRoute(
                    builder: (context) => FirstTabChildScreen(),
                  ),
                );
              },
              child: Text('Go to Child Screen'),
            ),
          ],
        ),
      ),
    );
  }
}

class FirstTabChildScreen extends StatefulWidget {
  @override
  State<FirstTabChildScreen> createState() => _FirstTabChildScreenState();
}

const List<String> list = <String>['One', 'Two', 'Three', 'Four'];

class _FirstTabChildScreenState extends State<FirstTabChildScreen> {
  String dropdownValue = list.first;
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('First Tab Child Screen'),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Text('Content for First Tab Child Screen'),
            SizedBox(height: 20),
            DropdownMenu<String>(
              initialSelection: list.first,
              // controller: colorController,
              // requestFocusOnTap is enabled/disabled by platforms when it is null.
              // On mobile platforms, this is false by default. Setting this to true will
              // trigger focus request on the text field and virtual keyboard will appear
              // afterward. On desktop platforms however, this defaults to true.
              requestFocusOnTap: true,
              // label: const Text('Color'),
              onSelected: (String? v) {
                setState(() {
                  if (v != null) {
                    dropdownValue = v;
                  }
                });
              },
              dropdownMenuEntries:
                  list.map<DropdownMenuEntry<String>>((String color) {
                return DropdownMenuEntry<String>(
                  value: color,
                  label: color,
                  enabled: true,
                  // style: MenuItemButton.styleFrom(
                  //   foregroundColor: color.color,
                  // ),
                );
              }).toList(),
            ),
            ElevatedButton(
              onPressed: () {
                Navigator.pop(context); // Go back to the parent screen
              },
              child: Text('Go Back'),
            ),
          ],
        ),
      ),
    );
  }
}

class SecondTabScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Navigator(
      onGenerateRoute: (settings) {
        return MaterialPageRoute(
          builder: (context) => Scaffold(
            appBar: AppBar(
              title: Text('Second Tab'),
            ),
            body: Center(
              child: Text('Content for Second Tab'),
            ),
          ),
        );
      },
    );
  }
}
```

**Comment by hiepvip99** [comment] 2023-11-29 02:05
Here is a demo video for that issue.
https://github.com/flutter/flutter/assets/75488013/72342f39-1cf4-493c-b603-eb28a84b9201

**Comment by QuncCccccc** [comment] 2023-11-29 23:12
Thanks for filing this issue! Looks like this problem happens when search is enabled, and then `ensureVisible()` is called to scroll to the matching menu item. I'm still investigating the root cause. As a workaround for now, setting `enabledSearch` to false will stop the tab view scrolling.

**Comment by iaTuaD** [comment] 2023-11-30 03:40
Another problem occurs when setting the enableSearch: false property,
The problem is that when selecting an item in the menu and when reopening the menu, the selected item in the menu is not highlighted, please help me.
![Screenshot 2023-11-30 at 10 39 50](https://github.com/flutter/flutter/assets/74866317/06d5e3ba-f66f-4c63-8fd8-152e972ff646)
@QuncCccccc

**Comment by QuncCccccc** [comment] 2023-11-30 04:47
Yes...the matching item is highlighted only when `enableSearch` is set to true. Sorry for the inconvenience.

**Comment by sashkent3** [comment] 2024-02-29 14:01
I'm experiencing a very similar issue. Here's [a minimal example on dartpad.dev](https://dartpad.dev/?id=d6b79c91154dd558e4044b0a71ac9302). In my case, it's even possible to switch tabs (from 'Tab 2' to 'Tab 3') upon opening the dropdown.

**Comment by hiepvip99** [comment] 2024-03-06 02:35
@sashkent3 It seems like they are not concerned about fixing this bug, it's been a few months already and I haven't seen any progress on it.

**Comment by EveNaari** [comment] 2024-04-04 10:38
Same issue here. Any news about fixing it? Maybe you need more info?

**Comment by Yukinosuke-Takada** [comment] 2024-05-05 06:29
I also noticed this issue after upgrading Flutter. I did a little digging but couldn't find what's causing this. But here's what I could get.

The minimum example:

```dart
import 'package:flutter/material.dart';

void main() {
  // run(mode: RunMode.development);

  runApp(
    const MaterialApp(
      home: SamplePage(),
    ),
  );
}

class SamplePage extends StatelessWidget {
  const SamplePage({super.key});

  @override
  Widget build(BuildContext context) {
    return DefaultTabController(
      length: 2,
      child: Scaffold(
        appBar: AppBar(
          title: const Text('App Bar Title'),
          bottom: const TabBar(
            tabs: [
              Tab(text: 'Tab 1'),
              Tab(text: 'Tab 2'),
            ],
          ),
        ),
        body: TabBarView(
          children: [
            Container(
              width: double.infinity,
              height: double.infinity,
              color: Colors.red[100],
              child: const Padding(
                padding: EdgeInsets.only(left: 160),
                child: SingleChildScrollView(
                  child: DropdownMenu(
                    dropdownMenuEntries: [
                      DropdownMenuEntry(
                        label: 'Option 1',
                        value: '1',
                      ),
                      DropdownMenuEntry(
                        label: 'Option 2',
                        value: '2',
                      ),
                    ],
                  ),
                ),
              ),
            ),
            Container(
              width: double.infinity,
              height: double.infinity,
              color: Colors.blue[100],
              child: Text('Tab 2'),
            ),
          ],
        ),
      ),
    );
  }
}
```

v3.16.8 works as expected.

https://github.com/flutter/flutter/assets/42461864/7148198e-7cf7-42e2-bb44-6924110995d1

v3.19.6 (current stable) has issue.

https://github.com/flutter/flutter/assets/42461864/ceacdbd6-92c8-46eb-949c-f5d9f00ff340

The jittering gets worse the more complex the widget is and at some point, you can't select the entries anymore.

**Comment by QuncCccccc** [comment] 2024-08-22 05:53
Seems this will be fixed by https://github.com/flutter/flutter/pull/153360:)

**Closed** 2024-08-22 21:14 UTC
Labels: framework, f: material design, has reproducible steps, P2, team-design, triaged-design, found in release: 3.16, found in release: 3.17
