### ISSUE TITLE
Verify the CPU and memory cost of a rotating and fading image

### ISSUE THREAD

**Issue by xster** [flutter/flutter#17217] opened 2018-05-02 21:56 UTC
https://mp.weixin.qq.com/s/j9ibj4ZYAqNZwwvSpIAtLA states a 64% simulator CPU usage which is plausible but also seems like a bug. 

Could be related to #13203 and/or iOS simulator only too

**Comment by uloga** [comment] 2018-05-10 08:05
I see this same issue with any type of animations or gifs on IphoneX Simulator and Hardware even when using CircularProgressIndicator().

**Comment by liyuqian** [comment] 2020-06-01 21:57
@xster : is this a duplicate of https://github.com/flutter/flutter/issues/13203 as you can't reproduce it on real iOS devices? If so, can we close this in favor of https://github.com/flutter/flutter/issues/13203?

**Comment by chinmaygarde** [comment] 2020-06-15 05:10
Closing as duplicate of https://github.com/flutter/flutter/issues/13203

**Closed by chinmaygarde** 2020-06-15 05:10 UTC
Labels: engine, severe: performance
