### ISSUE TITLE
_CastError: type 'Null' is not a subtype of type 'DragUpdateDetails' in type cast

### ISSUE THREAD

**Issue by demoYang** [flutter/flutter#138790] opened 2023-11-21 10:04 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Cannot reproduce

### Expected results

![image](https://github.com/flutter/flutter/assets/7134823/d99a452d-c420-427b-8b71-344b14e45d2f)

Why not judge lastDetails is null ?

### Actual results

When lastDetails is null,  just return 

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```
_CastError: type 'Null' is not a subtype of type 'DragUpdateDetails' in type cast
  File "scroll_activity.dart", line 464, in DragScrollActivity.dispatchScrollUpdateNotification
  File "scroll_position.dart", line 914, in ScrollPosition.didUpdateScrollPositionBy
  File "extended_nested_scroll_view.dart", line 1509, in _NestedScrollPosition.applyFullDragUpdate
  File "extended_nested_scroll_view.dart", line 1301, in _NestedScrollCoordinator.applyUserOffset
  File "scroll_activity.dart", line 386, in ScrollDragController.update
  File "scrollable.dart", line 671, in ScrollableState._handleDragUpdate
  File "monodrag.dart", line 483, in DragGestureRecognizer._checkUpdate.<fn>
  File "recognizer.dart", line 253, in GestureRecognizer.invokeCallback
  File "monodrag.dart", line 483, in DragGestureRecognizer._checkUpdate
  File "monodrag.dart", line 330, in DragGestureRecognizer.handleEvent
  File "pointer_router.dart", line 98, in PointerRouter._dispatch
  File "pointer_router.dart", line 143, in PointerRouter._dispatchEventToRoutes.<fn>
  File "compact_hash.dart", line 617, in _LinkedHashMapMixin.forEach
  File "pointer_router.dart", line 141, in PointerRouter._dispatchEventToRoutes
  File "pointer_router.dart", line 127, in PointerRouter.route
  File "binding.dart", line 460, in GestureBinding.handleEvent
  File "binding.dart", line 440, in GestureBinding.dispatchEvent
  File "binding.dart", line 337, in RendererBinding.dispatchEvent
  File "binding.dart", line 395, in GestureBinding._handlePointerEventImmediately
  File "binding.dart", line 357, in GestureBinding.handlePointerEvent
  File "binding.dart", line 314, in GestureBinding._flushPointerEventQueue
  File "binding.dart", line 295, in GestureBinding._handlePointerDataPacket
  File "zone.dart", line 1407, in _rootRunUnary
  File "zone.dart", line 1300, in _CustomZone.runUnary
  File "zone.dart", line 1209, in _CustomZone.runUnaryGuarded
  File "hooks.dart", line 169, in _invoke1
  File "platform_dispatcher.dart", line 341, in PlatformDispatcher._dispatchPointerDataPacket
  File "hooks.dart", line 94, in _dispatchPointerDataPacket
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.3.7, on macOS 13.5.1 22G90 darwin-arm, locale zh-Hans-CN)
    • Flutter version 3.3.7 on channel stable at /Users/xuyang/fvm/versions/3.3.7
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e99c9c7cd9 (1 year, 1 month ago), 2022-11-01 16:59:00 -0700
    • Engine revision 857bd6b74c
    • Dart version 2.18.4
    • DevTools version 2.15.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0-rc2)
    • Android SDK at /Users/xuyang/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0-rc2
    • ANDROID_HOME = /Users/xuyang/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.14.2

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.84.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.76.0

[✓] Connected device (3 available)
    • M2011K2C (mobile) • c1067376                             • android-arm64 • Android 12 (API 31)
    • 14 (mobile)       • 76952260-80A3-47EB-BF51-40D134BB23BC • ios           • com.apple.CoreSimulator.SimRuntime.iOS-17-0 (simulator)
    • macOS (desktop)   • macos                                • darwin-arm64  • macOS 13.5.1 22G90 darwin-arm

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by danagbemava-nc** [comment] 2023-11-21 14:00
Hi @demoYang, you are using an older version of flutter. 

Kindly upgrade to the latest version of flutter stable 3.16.0 to see if you still experience this issue. 

If you do, please provide the updated output of `flutter doctor -v`. 

Thank you

**Comment by demoYang** [comment] 2023-11-22 01:27
@danagbemava-nc  Thanks for your reply
This issue cannot be reproduced, and I am also unable to upgrade Flutter.
But I believe this issue is not related to the Flutter version. Can you take a look at my log? I suspect it's an issue with scroll_activity.dart. In the dispatchScrollUpdateNotification method, controller.lastDetails may be null.

**Comment by danagbemava-nc** [comment] 2023-11-22 07:28
That seems to be the case, while the `scroll_activity.dart` file has changed somewhat, the code for `dispatchScrollUpdateNotification` doesn't seem to have changed. 

https://github.com/flutter/flutter/blob/615481deb70c16e10804e49ecc10b01622787e6d/packages/flutter/lib/src/widgets/scroll_activity.dart#L479-L484

Adding a null check might be best. Labeling for further insight

**Comment by goderbauer** [comment] 2023-11-28 23:23
Thanks for filing an issue. Unfortunately, this is currently not actionable for us and I am going to close it. If you can reproduce this (ideally on the latest version of Flutter) or have additional details that would help in tracking it down feel free to reopen.

**Closed by goderbauer** 2023-11-28 23:23 UTC
Labels: c: crash, framework, f: scrolling, f: gestures, a: production, team-framework
