### ISSUE TITLE
Could not install build/ios/iphoneos/runner.app on <iphonedevice>

### ISSUE THREAD

**Issue by luqmanhakem** [flutter/flutter#29437] opened 2019-03-15 16:06 UTC
Hello. Currently, I'm stuck at debugging flutter sample apps on physical iOS device (iphone 6s - iOS 12.1.4) using android studio. I managed to debug using Xcode directly. Also, debugging apps on simulator seems to be working fine using android studio.

## Steps to Reproduce

1. Clean install android studio, Xcode and flutter.
2. Create a new flutter apps and run.
3. Change bundleIdentifier and edit Runner for the 'Signing' => Personal Team
4. Debug using android studio on my physical iOS device
5. Give the error

**Things that I've tried:**
- Format my MacBook and reinstall the following i.e. android studio, etc
- Tried this but still the same https://github.com/flutter/flutter/issues/4326, using 12.1.4 instead.

When I run this on the terminal,
```
 ls "$(xcrun --sdk iphoneos --show-sdk-platform-path)/DeviceSupport"
```
I got this,
```
10.0		11.1		12.1		8.2		9.2
10.1		11.2		12.1 (16B91)	8.3		9.3
10.2		11.3		12.1.4		8.4
10.3		11.4		8.0		9.0
11.0		12.0		8.1		9.1
```

## Logs

```
Launching lib/main.dart on Luqman Hakem’s iPhone in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: <MyCertificateID>
Running Xcode build...
Xcode build done.                                           14.5s
Installing and launching...
Could not install build/ios/iphoneos/Runner.app on <iphone6sDeviceID>.
Try launching Xcode and selecting "Product > Run" to fix the problem:
  open ios/Runner.xcworkspace

Error launching application on Luqman Hakem’s iPhone.
```

```
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.3 18D109, locale en-GB)
    • Flutter version 1.2.1 at /flutter
    • Framework revision 8661d8aecd (4 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).
      If Android SDK has been installed to a custom location, set ANDROID_HOME to that location.
      You may also want to add it to your PATH environment variable.


[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.1

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.4.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] Connected device (2 available)
    • Luqman Hakem’s iPhone • <MyIphoneID> • ios • iOS 12.1.4
    • iPhone XR             • <MyIphoneSimulatorID> • ios • iOS 12.1 (simulator)

! Doctor found issues in 1 category.

```

**Comment by VictorPuga** [comment] 2019-03-16 00:02
Same here :(

**Comment by nilobarp** [comment] 2019-03-16 00:50
Having the same problem. When I open the project in xcode I get a prompt saying `iPhone denied the launch request` was working till yesterday.

Tried removing and re-provisioning dev certificates but no luck.

**Comment by chenxianqi** [comment] 2019-03-16 02:53
I have the same problem.
xcode version Version 10.1 (10B61)
ios version  12.1.4(16D57)

`[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.14.3 18D109, locale zh-Hans-CN)
    • Flutter version 1.0.0 at /Users/chenxianqi/flutter
    • Framework revision 5391447fae (4 months ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/chenxianqi/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/chenxianqi/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.1

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.3.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.3.5)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 33.4.2
    • Dart plugin version 183.5912.23

[✓] VS Code (version 1.32.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.24.0

[✓] Connected device (2 available)
    • Redmi Note 7 • 2f49c4ea                                 • android-arm64 • Android 9 (API 28)
    • 陈显奇的  iPhone  • af47b4c63dc2cad49a1672e7494dcded7224937e • ios           • iOS 12.1.4

• No issues found!
`

**Comment by luqmanhakem** [comment] 2019-03-16 03:52
> Same here :(

Well, I taught that I'm the only one having this issue with pusheen cat icon.

> Having the same problem. When I open the project in xcode I get a prompt saying `iPhone denied the launch request` was working till yesterday.
> 
> Tried removing and re-provisioning dev certificates but no luck.

yea did the same thing over and over until I've decided to format my Macbook.
Hope to see any solution soon :)

> Hell! I have the same problem. All IOS devices are the same
> 
> xcode version Version 10.1 (10B61)
> ios version 12.1.4(16D57)
> 
> `[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.14.3 18D109, locale zh-Hans-CN)
> • Flutter version 1.0.0 at /Users/chenxianqi/flutter
> • Framework revision [5391447](https://github.com/flutter/flutter/commit/5391447fae6209bb21a89e6a5a6583cac1af9b4b) (4 months ago), 2018-11-29 19:41:26 -0800
> • Engine revision [7375a0f](https://github.com/flutter/flutter/commit/7375a0f414bde4bc941e623482221db2fc8c4ab5)
> • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)
> 
> [✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
> • Android SDK at /Users/chenxianqi/Library/Android/sdk
> • Android NDK location not configured (optional; useful for native profiling support)
> • Platform android-28, build-tools 28.0.3
> • ANDROID_HOME = /Users/chenxianqi/Library/Android/sdk
> • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
> • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
> • All Android licenses accepted.
> 
> [✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
> • Xcode at /Applications/Xcode.app/Contents/Developer
> • Xcode 10.1, Build version 10B61
> • ios-deploy 1.9.4
> • CocoaPods version 1.6.1
> 
> [✓] Android Studio (version 3.3)
> • Android Studio at /Applications/Android Studio.app/Contents
> • Flutter plugin version 33.3.1
> • Dart plugin version 182.5215
> • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
> 
> [✓] IntelliJ IDEA Ultimate Edition (version 2018.3.5)
> • IntelliJ at /Applications/IntelliJ IDEA.app
> • Flutter plugin version 33.4.2
> • Dart plugin version 183.5912.23
> 
> [✓] VS Code (version 1.32.2)
> • VS Code at /Applications/Visual Studio Code.app/Contents
> • Flutter extension version 2.24.0
> 
> [✓] Connected device (2 available)
> • Redmi Note 7 • 2f49c4ea • android-arm64 • Android 9 (API 28)
> • 陈显奇的 iPhone • af47b4c63dc2cad49a1672e7494dcded7224937e • ios • iOS 12.1.4
> 
> • No issues found!
Look's the same

**Comment by chenxianqi** [comment] 2019-03-16 03:56
> > Same here :(
> 
> Well, I taught that I'm the only one having this issue with pusheen cat icon.
> 
> > Having the same problem. When I open the project in xcode I get a prompt saying `iPhone denied the launch request` was working till yesterday.
> > Tried removing and re-provisioning dev certificates but no luck.
> 
> yea did the same thing over and over until I've decided to format my Macbook.
> Hope to see any solution soon :)
> 
> > Hell! I have the same problem. All IOS devices are the same
> > xcode version Version 10.1 (10B61)
> > ios version 12.1.4(16D57)
> > `[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.14.3 18D109, locale zh-Hans-CN)
> > • Flutter version 1.0.0 at /Users/chenxianqi/flutter
> > • Framework revision [5391447](https://github.com/flutter/flutter/commit/5391447fae6209bb21a89e6a5a6583cac1af9b4b) (4 months ago), 2018-11-29 19:41:26 -0800
> > • Engine revision [7375a0f](https://github.com/flutter/flutter/commit/7375a0f414bde4bc941e623482221db2fc8c4ab5)
> > • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)
> > [✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
> > • Android SDK at /Users/chenxianqi/Library/Android/sdk
> > • Android NDK location not configured (optional; useful for native profiling support)
> > • Platform android-28, build-tools 28.0.3
> > • ANDROID_HOME = /Users/chenxianqi/Library/Android/sdk
> > • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
> > • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
> > • All Android licenses accepted.
> > [✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
> > • Xcode at /Applications/Xcode.app/Contents/Developer
> > • Xcode 10.1, Build version 10B61
> > • ios-deploy 1.9.4
> > • CocoaPods version 1.6.1
> > [✓] Android Studio (version 3.3)
> > • Android Studio at /Applications/Android Studio.app/Contents
> > • Flutter plugin version 33.3.1
> > • Dart plugin version 182.5215
> > • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
> > [✓] IntelliJ IDEA Ultimate Edition (version 2018.3.5)
> > • IntelliJ at /Applications/IntelliJ IDEA.app
> > • Flutter plugin version 33.4.2
> > • Dart plugin version 183.5912.23
> > [✓] VS Code (version 1.32.2)
> > • VS Code at /Applications/Visual Studio Code.app/Contents
> > • Flutter extension version 2.24.0
> > [✓] Connected device (2 available)
> > • Redmi Note 7 • 2f49c4ea • android-arm64 • Android 9 (API 28)
> > • 陈显奇的 iPhone • af47b4c63dc2cad49a1672e7494dcded7224937e • ios • iOS 12.1.4
> > • No issues found!
> > Look's the same

**I try reinstall Xcode and reinstall flutter, The problem has not been solved.**

**Comment by Sh1d0w** [comment] 2019-03-16 09:37
Same problem here.

**Comment by Banerus** [comment] 2019-03-16 09:48
At last this issue has landed here! Everyone in Apple ecosystem has this issue now. You can't debug your application with a real device, only in case you make some changes in XCode to disable normal debugging. Flutter is using ios-deploy under the hood with lldb command line debugger, that is not working either.

So, we have to wait while Apple fixes this issue, hope flutter team can move it faster, because no one can use flutter with ios device for now. I mean with normal workflow, of course you can compile it with XCode, but you wont be able to use any hot reloading etc.

**Comment by Banerus** [comment] 2019-03-16 09:49
It all has started here: https://stackoverflow.com/questions/55132628/provisioning-profile-doesnt-include-the-application-identifier-and-keychain-acc.

Apple think, that they have fixed the issue, but no. I can't believe they are so slow for such a critical mess.

**Comment by davidhsu1115** [comment] 2019-03-16 13:33
Got same problem here. 
I reinstall Xcode and reset provisioning and certificate many times.
And it still has the same problem.

**Comment by pmcarlos** [comment] 2019-03-16 19:18
I can run the project from XCode, try deleting your old provisining profiles if needed.
Go to menu Product -> Scheme -> Edit Scheme  and uncheck Debug executable

Hope it helps, this works just on Xcode, cant get the app running from vscode
<img width="675" alt="Screen Shot 2019-03-16 at 1 16 25 PM" src="https://user-images.githubusercontent.com/24880753/54480411-b5893480-47ed-11e9-97e2-1e180584a5b7.png">

**Comment by LaksamanaGuntur** [comment] 2019-03-18 04:18
> I can run the project from XCode, try deleting your old provisining profiles if needed.
> Go to menu Product -> Scheme -> Edit Scheme and uncheck Debug executable
> 
> Hope it helps, this works just on Xcode, cant get the app running from vscode
> <img alt="Screen Shot 2019-03-16 at 1 16 25 PM" width="675" src="https://user-images.githubusercontent.com/24880753/54480411-b5893480-47ed-11e9-97e2-1e180584a5b7.png">

Same problem here, can't get the app running from vscode

**Comment by keitoro** [comment] 2019-03-18 15:33
Same problem here, I can run it with xcode, but not vscode. The problem is that the simulator doesn't have a camera so now I have to switch between two programs. This is really not the way to develop an app.

**Comment by rohmanhm** [comment] 2019-03-18 19:19
Just tried flutter today and got this one.
I could run it on xcode but not from `flutter run` which is fine to me, but now I don't have an HMR. Now it's bad

**Comment by rohmanhm** [comment] 2019-03-19 02:44
https://github.com/flutter/flutter/issues/25370

**Comment by waynetsai** [comment] 2019-03-19 08:39
Hey Guys! I just solved this problem by enrolling in the Apple Developer Program, paying  annual fee  and updating my Signing Certificate in XCode. I have used free Certificate before.

After updating my Signing Certificate and using `flutter run -d [deviceid]`  command
, My app had successfully installed and  launched in my iPhone.  

Then my app went unconnected and the commandline showed  'Error connecting to the service protocol: HttpException: , uri = http://127.0.0.1:1033/ws ' warning.

So I unchecked  the 'Connect via network' option in XCode from [window] -> [Devices and Simultors]
![image](https://user-images.githubusercontent.com/26406404/54590931-246fc300-4a64-11e9-88f3-c9ec6168750f.png)
![image](https://user-images.githubusercontent.com/26406404/54590992-3cdfdd80-4a64-11e9-9a3d-eb598c123951.png)

After that, My `flutter run` or `flutter run -d [deviceid]`  command could successfully working hot reload with my iPhone.

**Comment by Banerus** [comment] 2019-03-19 08:46
I feel we should wait for an official reply from Apple stating that we now can't use free certificates and need to enroll in paid subscription. Not a big deal, but they should state it.

**Comment by waynetsai** [comment] 2019-03-19 08:58
> I feel we should wait for an official reply from Apple stating that we now can't use free certificates and need to enroll in paid subscription. Not a big deal, but they should state it.

Banerus,Ｉtotally agree with you, I have wasted too much time on this issue.

**Comment by Sh1d0w** [comment] 2019-03-19 09:10
See my reply here https://github.com/flutter/flutter/issues/25370#issuecomment-474191547

**Comment by Banerus** [comment] 2019-03-20 11:51
Hey! Apple has fixed signing issue and now it works just like before. For a fix remove your development certificate and provision files to make XCode generate them again.

**Comment by waynetsai** [comment] 2019-03-20 12:39
> Hey! Apple has fixed signing issue and now it works just like before. For a fix remove your development certificate and provision files to make XCode generate them again.

Is there any official reply from Apple stating 's Url links?

**Comment by keitoro** [comment] 2019-03-20 12:59
I have tried that a couple of times and I still need to uncheck debug executable to be able to load the app on my device. Which means I can't use vscode to launch a Flutter ios app. So nothing has been solved.

**Comment by nyzm** [comment] 2019-03-20 14:18
Alright looks like it is fixed but you have to remove the certificates from your keychain and let xcode regenerate. Checkout this thread: https://forums.developer.apple.com/thread/114647

> WindyCross
> Mar 19, 2019 2:09 AM
> (in response to SunEc)
> 
> At last, I read a thread and do as it said "delete all the all the key in "key chain->certification", especially the "Apple Worldwide Developer Relations Certification Authority". Don't afraid it will disappear. It will be generated by XCode again.
> 
> XCODE: 10.1
> IPHONE X:12.1.4

**Comment by keitoro** [comment] 2019-03-20 14:28
that is what I did like ten times and still, the same issue (even today) doesn't look like it is working.

**Comment by nyzm** [comment] 2019-03-20 14:33
Well I did it just now & it worked. Below are the steps . 
- Close Xcode
- Open Keychain 
- Remove "Iphone Developer" and "Apple Worldwide Developer Relations Certification Authority"
- Reopen Xcode
- Product / Run the project again with debug executable checked (Succeed)
- Close Xcode
- Open vscode
- Debug / Start debugging 
- It built and run on physical device successfully

**Comment by ysfscream** [comment] 2019-03-20 16:15
When I debug app in VsCode, and `Launching lib/main.dart on iPhone in debug mode...` is very slow and will wait a half hour to install.

**Comment by pmcarlos** [comment] 2019-03-21 00:16
> Maybe is the same issue. When I debug app in VsCode, and `Launching lib/main.dart on iPhone in debug mode...` is very slow and will wait half an hour to install.
> 
> logs
> 
> ```
> [✓] Flutter (Channel dev, v1.3.13, on Mac OS X 10.14.3 18D109, locale zh-Hans-CN)
> [✗] Android toolchain - develop for Android devices
>     ✗ Unable to locate Android SDK.
>       Install Android Studio from: https://developer.android.com/studio/index.html
>       On first launch it will assist you in installing the Android SDK components.
>       (or visit https://flutter.io/setup/#android-setup for detailed instructions).
>       If the Android SDK has been installed to a custom location, set ANDROID_HOME to that location.
>       You may also want to add it to your PATH environment variable.
> 
> [✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
> [!] Android Studio (not installed)
> [✓] VS Code (version 1.32.3)
> [✓] Connected device (1 available)
> ```

I can confirm its taking longer than usually, for me just about 3-5 minutes when it was 30 seconds... but its working now on vscode

**Comment by pmcarlos** [comment] 2019-03-21 00:16
> Well I did it just now & it worked. Below are the steps .
> 
> * Close Xcode
> * Open Keychain
> * Remove "Iphone Developer" and "Apple Worldwide Developer Relations Certification Authority"
> * Reopen Xcode
> * Product / Run the project again with debug executable checked (Succeed)
> * Close Xcode
> * Open vscode
> * Debug / Start debugging
> * It built and run on physical device successfully

I can confirm it's working now

**Comment by Sh1d0w** [comment] 2019-03-21 03:24
I can confirm it is working now, too. Also I did not notice any delays in the startup time, it works just fine like before.

**Comment by neelu004** [comment] 2019-04-25 04:45
facing issue as when adding dependency of shared preference in iOS
ld: library not found for -lshared_preferences
Please suggest some solution.

**Comment by nandofalcao** [comment] 2019-07-07 12:21
Hello everyone! This work for me:

**1) Download ios-deploy from:**
- https://raw.githubusercontent.com/kangwang1988/kangwang1988.github.io/master/others/ios-deploy

**2) Set permissions for ios-deploy**
- chmod +x ios-deploy

**3) Move**
- mv ios-deploy /usr/local/Cellar/ios-deploy/1.9.4/bin

**For iOS 13 beta. Download XCode Beta and set to default on terminal:**
- sudo xcode-select -switch /Applications/Xcode-beta.app

References:
- https://developer.apple.com/library/archive/technotes/tn2339/_index.html
- https://medium.com/@fredriccliver/device-doesnt-support-wireless-sync-amdevicestartservice-880f2050c2bc

**Comment by G33N** [comment] 2019-07-30 02:48
Hello! This works for me.

If you are trying run a flutter ios app without Xcode, for example from vscode or console with `flutter run` you need trust the developer certificate.

Try this on your device:

Go to Settings->General->Device Management (your certificate)-> "your certificate trust"

**Comment by mingdongt** [comment] 2019-07-31 07:55
> Hey Guys! I just solve this problem by enrolling in the Apple Developer Program, paying annual fee and updating my Signing Certificate in XCode. I have used free Certificate before.
> 
> After updating my Signing Certificate and using `flutter run -d [deviceid]` command
> , My app had successfully installed and launched in my iPhone.
> 
> Then my app went unconnected and the commandline showed `Error connecting to the service protocol: HttpException: , uri = http://127.0.0.1:1033/ws` warning.
> 
> ![image](https://user-images.githubusercontent.com/26406404/54591944-4702db80-4a66-11e9-84ff-bb51972acb51.png)
> 
> To solve this warning problem, I had unchecked the 'Connect via network' option in XCode from [window] -> [Devices and Simultors]
> ![image](https://user-images.githubusercontent.com/26406404/54590931-246fc300-4a64-11e9-88f3-c9ec6168750f.png)
> ![image](https://user-images.githubusercontent.com/26406404/54590992-3cdfdd80-4a64-11e9-9a3d-eb598c123951.png)
> 
> After that, My `flutter run` or `flutter run -d [deviceid]` command could successfully working hot reload with my iPhone.

Save me life

**Comment by jmagman** [comment] 2019-09-24 21:06
@christopherfujino Is this a forward-duplicate of https://github.com/flutter/flutter/issues/37699?

**Comment by christopherfujino** [comment] 2019-09-24 22:13
Yes, I think you're right. I will close this issue, please refer to #37699, tl;dr is that this has been fixed on the dev channel.

**Closed by christopherfujino** 2019-09-24 22:13 UTC
Labels: t: xcode, tool

**Comment by akinsete** [comment] 2019-10-10 19:22
By default all Xcode generated code from flutter has display name Runner. If you change this, you will get this error.

**Comment by liupengzhouyi** [comment] 2020-02-09 06:45
# 真机调试
## 出现Xcode该页面
<img width="1257" alt="截屏2020-02-09下午2 45 07" src="https://user-images.githubusercontent.com/37412816/74097737-c69c0c00-4b4a-11ea-9323-32992508b85c.png">
## Android Studio报错信息
`Automatically signing iOS for device deployment using specified development team in Xcode project: SUQKBUTS9B
Running pod install...
Running Xcode build...
Xcode build done.                                           15.7s
Installing and launching...
Could not install build/ios/iphoneos/Runner.app on dfa2f6edcd33c6060a5a25fdabc3fb07fef6d1dc.
Try launching Xcode and selecting "Product > Run" to fix the problem:
  open ios/Runner.xcworkspace

Error launching application on XXX的iPhone.
`
<img width="976" alt="截屏2020-02-09下午2 44 42" src="https://user-images.githubusercontent.com/37412816/74097729-b7b55980-4b4a-11ea-9be2-0ce4e798f074.png">

**Comment by duleigiser** [comment] 2020-03-13 03:42
fluttter clean may help
