### ISSUE TITLE
Suppling Uniform Values to iOS Shaders Gets a RangeError

### ISSUE THREAD

**Issue by pouyakary** [flutter/flutter#155791] opened 2024-09-26 21:55 UTC
### Steps to reproduce

Only on iOS (and not mac/windows), flutter gives me this error:

```
IndexError (RangeError (index): Index out of range: index should be less than 2: 2)
```

It is worth mentioning that this happens with every shader 

### Expected results

Well I expect all platforms to support GLSL the same and that it computes the number of uniform parameters currectly.

### Actual results

Well I would have expected the shader to be compiled and loaded as in other platforms

### Code sample

<details open><summary>Shader</summary>

```GLSL
#include <flutter/runtime_effect.glsl>

uniform vec2 u_resolution;
uniform float u_time;
uniform float u_size;
out vec4 fragColor;

void main() {
  vec2 here = FlutterFragCoord().xy;
  vec2 center = u_resolution / 2.;

  vec4 yellow = vec4(0.940,0.741,0.015,1.000);
  vec4 black = vec4(0.985,0.825,0.000,1.000);

  float x = here.x - u_time * 100.;
  bool on_band = mod(x + here.y, u_size) < (u_size / 2.);

  fragColor = on_band ? black : yellow;
}
```

</details>

<details open><summary>Painter</summary>

```dart
@override
  void paint(final Canvas canvas, final Size size) {
    shaderProgram.setFloat(0, size.width); // u_resolution.x
    shaderProgram.setFloat(1, size.height); // u_resolution.y
    shaderProgram.setFloat(2, time); // u_time
    shaderProgram.setFloat(3, paneSize); // u_size

    final paint = Paint()..shader = shaderProgram;
    final rect = Rect.fromLTWH(0, 0, size.width, size.height);

    canvas.drawRect(rect, paint);
  }
```

</details>

### Screenshots or Video

<!---nothing--→

### Logs

<details open><summary>Logs</summary>

```console
    painter: _DangerBansPainter#5b633()
    willChange: true
    child: RenderConstrainedBox#1d40d relayoutBoundary=up9 NEEDS-PAINT
        parentData: <none> (can use size)
        constraints: BoxConstraints(0.0<=w<=550.0, 0.0<=h<=Infinity)
        size: Size(550.0, 30.0)
        additionalConstraints: BoxConstraints(w=Infinity, h=30.0)
RenderObject: RenderCustomPaint#26b0e relayoutBoundary=up8
    parentData: offset=Offset(0.0, 0.0); flex=null; fit=null (can use size)
    constraints: BoxConstraints(0.0<=w<=550.0, 0.0<=h<=Infinity)
    size: Size(550.0, 30.0)
    painter: _DangerBansPainter#5b633()
    willChange: true
    child: RenderConstrainedBox#1d40d relayoutBoundary=up9 NEEDS-PAINT
        parentData: <none> (can use size)
        constraints: BoxConstraints(0.0<=w<=550.0, 0.0<=h<=Infinity)
        size: Size(550.0, 30.0)
        additionalConstraints: BoxConstraints(w=Infinity, h=30.0)
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════
RangeError (index): Index out of range: index should be less than 2: 2
The relevant error-causing widget was:
    CustomPaint CustomPaint:file:///Users/pouda/Developer/fabizi/lib/views/components/kit/danger_bans/danger_bans.dart:115:16
The following RenderObject was being processed when the exception was fired: RenderCustomPaint#26b0e relayoutBoundary=up8
RenderObject: RenderCustomPaint#26b0e relayoutBoundary=up8
════════════════════════════════════════════════════════════════════════════════
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.24.3, on macOS 15.0 24A335 darwin-arm64, locale en-US)
    • Flutter version 3.24.3 on channel stable at /Applications/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2663184aa7 (2 weeks ago), 2024-09-11 16:27:48 -0500
    • Engine revision 36335019a8
    • Dart version 3.5.3
    • DevTools version 2.37.3

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/to/macos-android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16A242d
    • CocoaPods version 1.13.0

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/to/macos-android-setup for detailed instructions).

[✓] VS Code (version 1.93.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.97.20240902

[✓] Connected device (3 available)
    • iPad (10th generation) (mobile) • F8B07527-1AAA-4F22-8177-7A36DEFA305E • ios          •
      com.apple.CoreSimulator.SimRuntime.iOS-18-0 (simulator)
    • macOS (desktop)                 • macos                                • darwin-arm64 • macOS 15.0 24A335 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad                • darwin       • macOS 15.0 24A335 darwin-arm64
    ! Error: Browsing on the local area network for Pouya’s Watch ✨. Ensure the device is unlocked and discoverable via Bluetooth.
      (code -27)

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 3 categories.
```

</details>

**Comment by jonahwilliams** [comment] 2024-09-26 22:53
Because the result of the computation using `u_resolution` is not used, the u_resolution uniform is dropped. This is a duplicate of https://github.com/flutter/flutter/issues/116900

**Closed by jonahwilliams** 2024-09-26 22:53 UTC
