### ISSUE TITLE
White screen sometimes appears where Maps plugin should be displayed on iOS

### ISSUE THREAD

**Issue by khmoran** [flutter/flutter#30557] opened 2019-04-05 15:22 UTC
The issue is flaky to reproduce, but this is the context in which it happens:

1. From a widget containing the Google Maps plugin, open a full-page dialog
2. Close the full-page dialog

It will repro maybe 1/10 times or fewer.

Pulling down the notifications tray + releasing it makes the map display again properly (or locking + unlocking the phone).

It happens on iOS only.

This is the layer tree when the white screen is displayed:

```
flutter: TransformLayer#15ad5
flutter:  │ owner: RenderView#5f9d5
flutter:  │ creator: [root]
flutter:  │ offset: Offset(0.0, 0.0)
flutter:  │ transform:
flutter:  │   [0] 3.0,0.0,0.0,0.0
flutter:  │   [1] 0.0,3.0,0.0,0.0
flutter:  │   [2] 0.0,0.0,1.0,0.0
flutter:  │   [3] 0.0,0.0,0.0,1.0
flutter:  │
flutter:  ├─child 1: OffsetLayer#cee6c
flutter:  │ │ creator: RepaintBoundary ← _FocusScopeMarker ← Semantics ←
flutter:  │ │   FocusScope ← PageStorage ← Offstage ← _ModalScopeStatus ←
flutter:  │ │   _ModalScope<dynamic>-[LabeledGlobalKey<_ModalScopeState<dynamic>>#a3200]
flutter:  │ │   ← _OverlayEntry-[LabeledGlobalKey<_OverlayEntryState>#b559d] ←
flutter:  │ │   Stack ← _Theatre ←
flutter:  │ │   Overlay-[LabeledGlobalKey<OverlayState>#faed7] ← ⋯
flutter:  │ │ offset: Offset(0.0, 0.0)
flutter:  │ │
flutter:  │ ├─child 1: PictureLayer#dddc6
flutter:  │ │   paint bounds: Rect.fromLTRB(0.0, 0.0, 375.0, 812.0)
flutter:  │ │
flutter:  │ └─child 2: OffsetLayer#5cd78
flutter:  │   │ creator: RepaintBoundary-[GlobalKey#66465] ← IgnorePointer ←
flutter:  │   │   Stack ← _CupertinoBackGestureDetector<dynamic> ← DecoratedBox ←
flutter:  │   │   DecoratedBoxTransition ← FractionalTranslation ←
flutter:  │   │   SlideTransition ← FractionalTranslation ← SlideTransition ←
flutter:  │   │   CupertinoPageTransition ← AnimatedBuilder ← ⋯
flutter:  │   │ offset: Offset(0.0, 0.0)
flutter:  │   │
flutter:  │   └─child 1: PhysicalModelLayer#aacb1
flutter:  │     │ elevation: 0.0
flutter:  │     │ color: Color(0xfffcfdff)
flutter:  │     │
flutter:  │     ├─child 1: OffsetLayer#b298b
flutter:  │     │ │ creator: Viewport ← IgnorePointer-[GlobalKey#8b093] ← Semantics ←
flutter:  │     │ │   Listener ← _GestureSemantics ←
flutter:  │     │ │   RawGestureDetector-[LabeledGlobalKey<RawGestureDetectorState>#bd1e7]
flutter:  │     │ │   ← Listener ← _ScrollableScope ←
flutter:  │     │ │   _ScrollSemantics-[GlobalKey#f0e6c] ← Scrollable ←
flutter:  │     │ │   NotificationListener<ScrollNotification> ← PageView ← ⋯
flutter:  │     │ │ offset: Offset(0.0, 0.0)
flutter:  │     │ │
flutter:  │     │ └─child 1: ClipRectLayer#4de20
flutter:  │     │   │ clipRect: Rect.fromLTRB(0.0, 0.0, 375.0, 728.0)
flutter:  │     │   │
flutter:  │     │   └─child 1: OffsetLayer#def4c
flutter:  │     │     │ creator: RepaintBoundary-[<1>] ← IndexedSemantics ←
flutter:  │     │     │   NotificationListener<KeepAliveNotification> ← KeepAlive ←
flutter:  │     │     │   AutomaticKeepAlive ← SliverFillViewport ← Viewport ←
flutter:  │     │     │   IgnorePointer-[GlobalKey#8b093] ← Semantics ← Listener ←
flutter:  │     │     │   _GestureSemantics ←
flutter:  │     │     │   RawGestureDetector-[LabeledGlobalKey<RawGestureDetectorState>#bd1e7]
flutter:  │     │     │   ← ⋯
flutter:  │     │     │ offset: Offset(0.0, 0.0)
flutter:  │     │     │
flutter:  │     │     ├─child 1: OffsetLayer#3739d
flutter:  │     │     │ │ creator: _UiKitPlatformView ← UiKitView ← GoogleMap ← SizedBox ←
flutter:  │     │     │ │   Align ← Stack ← FutureBuilder<Point<num>> ← MapPage ←
flutter:  │     │     │ │   RepaintBoundary-[<1>] ← IndexedSemantics ←
flutter:  │     │     │ │   NotificationListener<KeepAliveNotification> ← KeepAlive ← ⋯
flutter:  │     │     │ │ offset: Offset(0.0, 0.0)
flutter:  │     │     │ │
flutter:  │     │     │ └─child 1: PlatformViewLayer#0dc36
flutter:  │     │     ├─child 2: PhysicalModelLayer#f87c5
flutter:  │     │     │ │ elevation: 0.0
flutter:  │     │     │ │ color: Color(0x00000000)
flutter:  │     │     │ │
flutter:  │     │     │ └─child 1: PictureLayer#6f37d
flutter:  │     │     │     paint bounds: Rect.fromLTRB(8.0, 571.0, 367.0, 720.0)
flutter:  │     │     │
flutter:  │     │     ├─child 3: PictureLayer#18aba
flutter:  │     │     │   paint bounds: Rect.fromLTRB(0.0, 0.0, 375.0, 728.0)
flutter:  │     │     │
flutter:  │     │     ├─child 4: PhysicalModelLayer#b5a6c
flutter:  │     │     │ │ elevation: 0.0
flutter:  │     │     │ │ color: Color(0xf7ffffff)
flutter:  │     │     │ │
flutter:  │     │     │ └─child 1: PictureLayer#4598f
flutter:  │     │     │     paint bounds: Rect.fromLTRB(8.5, 47.4, 366.5, 93.4)
flutter:  │     │     │
flutter:  │     │     ├─child 5: PictureLayer#ba56a
flutter:  │     │     │   paint bounds: Rect.fromLTRB(0.0, 0.0, 375.0, 728.0)
flutter:  │     │     │
flutter:  │     │     └─child 6: PhysicalModelLayer#b7a18
flutter:  │     │       │ elevation: 0.0
flutter:  │     │       │ color: Color(0xf7ffffff)
flutter:  │     │       │
flutter:  │     │       └─child 1: PictureLayer#5dfff
flutter:  │     │           paint bounds: Rect.fromLTRB(116.5, 110.4, 258.5, 149.4)
flutter:  │     │
flutter:  │     ├─child 2: PhysicalModelLayer#de7be
flutter:  │     │ │ elevation: 0.0
flutter:  │     │ │ color: Color(0xffffffff)
flutter:  │     │ │
flutter:  │     │ └─child 1: PictureLayer#c36b7
flutter:  │     │     paint bounds: Rect.fromLTRB(0.0, 728.0, 375.0, 812.0)
flutter:  │     │
flutter:  │     └─child 3: PictureLayer#667e9
flutter:  │         paint bounds: Rect.fromLTRB(0.0, 0.0, 375.0, 812.0)
flutter:  │
flutter:  └─child 2: PictureLayer#9a4e2
flutter:      paint bounds: Rect.fromLTRB(0.0, 0.0, 1125.0, 2436.0)
flutter:
```

**Comment by cyanglaz** [comment] 2019-04-09 18:59
I have created a mini app with a full screen google map and a button on the tool bar to open the dialog. 
I haven't been lucky enough to reproduce the issue. 

Here is the code of my mini app. 

```dart
import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final LatLng center = const LatLng(32.080664, 34.9563837);
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: Text(widget.title),
          actions: <Widget>[
            FlatButton(
              child: Icon(Icons.add),
              onPressed: _openDialog,
            )
          ],
        ),
        body: Center(
          child: GoogleMap(
            initialCameraPosition: CameraPosition(
              target: center,
              zoom: 11.0,
            ),
          ),
        ));
  }

  void _openDialog() {
    Navigator.of(context).push(MaterialPageRoute<Null>(
        builder: (BuildContext context) {
          return Dialog();
        },
        fullscreenDialog: true));
  }
}

class Dialog extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: new AppBar(
        title: const Text('Dialog'),
        actions: [
          new FlatButton(
              onPressed: () {
                Navigator.of(context).pop();
              },
              child: new Text('Pop')),
        ],
      ),
      body: new Text("Foo"),
    );
  }
}
```
Could you replace this with your main.dart and try to see if you can reproduce it?

**Comment by cyanglaz** [comment] 2019-04-10 23:34
@mehmetf

**Comment by cyanglaz** [comment] 2019-08-02 22:53
Since I'm not able to actively working on this, I'll un-assign myself from this issue.

**Comment by TahaTesser** [comment] 2020-10-23 15:06
Hi @khmoran 
I can't reproduce the issue using https://github.com/flutter/flutter/issues/30557#issuecomment-481392154 on iOS 14ON on the latest `google_maps_flutter 1.0.3` 

<details> 
<summary>complete code sample</summary> 

```dart
import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final LatLng center = const LatLng(32.080664, 34.9563837);
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: Text(widget.title),
          actions: <Widget>[
            FlatButton(
              child: Icon(Icons.add),
              onPressed: _openDialog,
            )
          ],
        ),
        body: Center(
          child: GoogleMap(
            initialCameraPosition: CameraPosition(
              target: center,
              zoom: 11.0,
            ),
          ),
        ));
  }

  void _openDialog() {
    Navigator.of(context).push(MaterialPageRoute<Null>(
        builder: (BuildContext context) {
          return Dialog();
        },
        fullscreenDialog: true));
  }
}

class Dialog extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: new AppBar(
        title: const Text('Dialog'),
        actions: [
          new FlatButton(
              onPressed: () {
                Navigator.of(context).pop();
              },
              child: new Text('Pop')),
        ],
      ),
      body: new Text("Foo"),
    );
  }
}

```

</details> 

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel master, 1.24.0-4.0.pre.33, on Mac OS X 10.15.7 19H2
    darwin-x64, locale en-GB)
    • Flutter version 1.24.0-4.0.pre.33 at /Users/tahatesser/Code/flutter_master
    • Framework revision 351ccf7eaf (5 hours ago), 2020-10-22 23:28:51 -0700
    • Engine revision defa8be2b1
    • Dart version 2.11.0 (build 2.11.0-242.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.10.0.rc.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.1

[✓] Connected device (4 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios            • iOS
      14.1
    • macOS (desktop)        • macos                     • darwin-x64     • Mac
      OS X 10.15.7 19H2 darwin-x64
    • Web Server (web)       • web-server                • web-javascript •
      Flutter Tools
    • Chrome (web)           • chrome                    • web-javascript •
      Google Chrome 86.0.4240.111

• No issues found!
```

</details>

**Comment by TahaTesser** [comment] 2020-10-23 15:07
Hi @khmoran 
I can't reproduce the issue using https://github.com/flutter/flutter/issues/30557#issuecomment-481392154 on iOS 14ON on the latest `google_maps_flutter 1.0.3` 

<details> 
<summary>complete code sample</summary> 

```dart
import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final LatLng center = const LatLng(32.080664, 34.9563837);
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: Text(widget.title),
          actions: <Widget>[
            FlatButton(
              child: Icon(Icons.add),
              onPressed: _openDialog,
            )
          ],
        ),
        body: Center(
          child: GoogleMap(
            initialCameraPosition: CameraPosition(
              target: center,
              zoom: 11.0,
            ),
          ),
        ));
  }

  void _openDialog() {
    Navigator.of(context).push(MaterialPageRoute<Null>(
        builder: (BuildContext context) {
          return Dialog();
        },
        fullscreenDialog: true));
  }
}

class Dialog extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: new AppBar(
        title: const Text('Dialog'),
        actions: [
          new FlatButton(
              onPressed: () {
                Navigator.of(context).pop();
              },
              child: new Text('Pop')),
        ],
      ),
      body: new Text("Foo"),
    );
  }
}

```

</details> 

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel master, 1.24.0-4.0.pre.33, on Mac OS X 10.15.7 19H2
    darwin-x64, locale en-GB)
    • Flutter version 1.24.0-4.0.pre.33 at /Users/tahatesser/Code/flutter_master
    • Framework revision 351ccf7eaf (5 hours ago), 2020-10-22 23:28:51 -0700
    • Engine revision defa8be2b1
    • Dart version 2.11.0 (build 2.11.0-242.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.10.0.rc.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.1

[✓] Connected device (4 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios            • iOS
      14.1
    • macOS (desktop)        • macos                     • darwin-x64     • Mac
      OS X 10.15.7 19H2 darwin-x64
    • Web Server (web)       • web-server                • web-javascript •
      Flutter Tools
    • Chrome (web)           • chrome                    • web-javascript •
      Google Chrome 86.0.4240.111

• No issues found!
```

</details> 

Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by pedromassangocode** [comment] 2020-11-13 12:02
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2020-11-13 12:02 UTC
Labels: a: platform-views, customer: google, engine, p: maps, platform-ios, plugin

**Comment by JeyPay** [comment] 2020-11-13 13:21
Hi,
I have been experiencing this exact same bug not only on iOS but also on Android and after some digging, here is what I found.
This bug seems RAM related as the embedded view of the map get killed by the system when the app goes into background (in my case). The map still catch gestures as you can tap on Markers (without seeing them off course).

Workaround: add an observer that change the map style when the app comes back from background
```
class _AppState extends State<AppState> with WidgetsBindingObserver {
    @override
    void didChangeAppLifecycleState(AppLifecycleState state) {
        if (state == AppLifecycleState.resumed) {
           mapController.setMapStyle("[]");
        }
    }
}
```

For some reason, asking the google_maps_flutter package to redraw the map "fix" the issue.

Flutter doctor -v:
```
[✓] Flutter (Channel stable, 1.22.3, on Linux, locale en_US.UTF-8)
    • Flutter version 1.22.3 at /home/<name>/snap/flutter/common/flutter
    • Framework revision 8874f21e79 (2 weeks ago), 2020-10-29 14:14:35 -0700
    • Engine revision a1440ca392
    • Dart version 2.10.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/<name>/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.9+11-Ubuntu-0ubuntu1.20.04)
    • All Android licenses accepted

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] Connected device (1 available)
    • LM G710 (mobile) • LMG710EMa2661a0a • android-arm64 • Android 10 (API 29)
```

**Comment by TahaTesser** [comment] 2020-11-20 11:42
Hi @JeyPay
please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
