### ISSUE TITLE
ProcessException: Process timed out

### ISSUE THREAD

**Issue by breederComrade** [flutter/flutter#51816] opened 2020-03-03 02:54 UTC
## command

flutter run

## exception

ProcessException: ProcessException: Process timed out:

  Command: /usr/bin/env xcrun xcodebuild -configuration Debug -quiet -workspace Runner.xcworkspace -scheme Runner BUILD_DIR=/Users/apple/code/localhost/qdj_flutter/build/ios -sdk iphonesimulator -arch x86_64 SCRIPT_OUTPUT_STREAM_FILE=/var/folders/zc/jv4ngy515cdgk74jj8fvx9_00000gn/T/flutter_build_log_pipe.raMRHG/pipe_to_stdout FLUTTER_SUPPRESS_ANALYTICS=true COMPILER_INDEX_STORE_ENABLE=NO -showBuildSettings

```
#0      RunResult.throwException (package:flutter_tools/src/base/process.dart:141:5)
#1      _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart:346:19)
<asynchronous suspension>
#2      buildXcodeProject (package:flutter_tools/src/ios/mac.dart:503:66)
<asynchronous suspension>
#3      IOSSimulator._setupUpdatedApplicationBundle (package:flutter_tools/src/ios/simulators.dart:436:48)
<asynchronous suspension>
#4      IOSSimulator.startApp (package:flutter_tools/src/ios/simulators.dart:354:15)
#5      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:450:54)
#6      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#7      _rootRunUnary (dart:async/zone.dart:1134:38)
#8      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#9      _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#10     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#11     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#12     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#13     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#14     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#15     ApplicationPackageFactory.getPackageForPlatform (package:flutter_tools/src/application_package.dart)
#16     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#17     _rootRunUnary (dart:async/zone.dart:1134:38)
#18     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#19     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#20     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#21     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#22     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#23     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#24     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#25     BuildableIOSApp.fromProject (package:flutter_tools/src/application_package.dart)
#26     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#27     _rootRunUnary (dart:async/zone.dart:1134:38)
#28     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#29     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#30     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#31     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#32     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#33     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
#34     _rootRun (dart:async/zone.dart:1126:13)
#35     _CustomZone.run (dart:async/zone.dart:1023:19)
#36     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#37     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#38     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#39     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#40     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#41     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel unknown, v1.12.13+hotfix.6, on Mac OS X 10.14.4 18E226,
    locale zh-Hans-CN)
    [32m•[39m Flutter version 1.12.13+hotfix.6 at
      /Users/apple/code/github/FlutterSdk/flutter
    [32m•[39m Framework revision 18cd7a3601 (3 months ago), 2019-12-11 06:35:39 -0800
    [32m•[39m Engine revision 2994f7e1e6
    [32m•[39m Dart version 2.7.0

[33m[!][39m Android toolchain - develop for Android devices (Android SDK version
    28.0.3)
    [32m•[39m Android SDK at /Users/apple/Library/Android/sdk
    [32m•[39m Android NDK location not configured (optional; useful for native
      profiling support)
    [32m•[39m Platform android-28, build-tools 28.0.3
    [32m•[39m ANDROID_HOME = /Users/apple/Library/Android/sdk
    [32m•[39m Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
    [31m✗[39m Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit
      https://flutter.dev/setup/#android-setup for detailed instructions.

[32m[✓][39m Xcode - develop for iOS and macOS (Xcode 11.3.1)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Xcode 11.3.1, Build version 11C504
    [32m•[39m CocoaPods version 1.7.3

[32m[✓][39m Android Studio (version 3.5)
    [32m•[39m Android Studio at /Applications/Android Studio.app/Contents
    [32m•[39m Flutter plugin version 40.1.2
    [32m•[39m Dart plugin version 191.8423
    [32m•[39m Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)

[32m[✓][39m VS Code (version 1.42.1)
    [32m•[39m VS Code at /Applications/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version 3.8.1

[32m[✓][39m Connected device (1 available)
    [32m•[39m iPhone 11 Pro Max • FDE5EDD7-93A5-4C16-A397-E04236578391 • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)

[33m![39m Doctor found issues in 1 category.
```

i can run succeeded in xcode  but  flutter run canot

![QQ20200303-0](https://user-images.githubusercontent.com/36719505/75738428-31e99000-5d3d-11ea-99f1-9b6a0053e49c.png)

**Comment by JosepBove** [comment] 2020-03-03 07:41
Hello @breederComrade !

You should change the title to something more clean like `Flutter run: process timed out`

**Comment by VladyslavBondarenko** [comment] 2020-03-03 09:05
Duplicate of https://github.com/flutter/flutter/issues/47633

**Closed by VladyslavBondarenko** 2020-03-03 09:05 UTC
