### ISSUE TITLE
flutter::ImpellerAllocator::allocPixelRef(SkBitmap*) (image_decoder_impeller.cc:542)

### ISSUE THREAD

**Issue by ke780382349** [flutter/flutter#138897] opened 2023-11-22 15:21 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

In Flutter 3.13.9.
I got a crash log.
The app runs on the iPad

```
flutter::ImpellerAllocator::allocPixelRef(SkBitmap*) (image_decoder_impeller.cc:542)
flutter::ImpellerAllocator::allocPixelRef(SkBitmap*) (new.cpp:67)
std::_LIBCPP_ABI_NAMESPACE::__function::__func<flutter::ImageDecoderImpeller::Decode(fml::RefPtr<flutter::ImageDescriptor>, unsigned int, unsigned int, std::_LIBCPP_ABI_NAMESPACE::function<void (sk_sp<flutter::DlImage>, std::_LIBCPP_ABI_NAMESPACE::basic_string<char, std::_LIBCPP_ABI_NAMESPACE::char_traits<char>, std::_LIBCPP_ABI_NAMESPACE::allocator<char> >)> const&)::$_1, std::_LIBCPP_ABI_NAMESPACE::allocator<flutter::ImageDecoderImpeller::Decode(fml::RefPtr<flutter::ImageDescriptor>, unsigned int, unsigned int, std::_LIBCPP_ABI_NAMESPACE::function<void (sk_sp<flutter::DlImage>, std::_LIBCPP_ABI_NAMESPACE::basic_string<char, std::_LIBCPP_ABI_NAMESPACE::char_traits<char>, std::_LIBCPP_ABI_NAMESPACE::allocator<char> >)> const&)::$_1>, void ()>::operator()() (image_decoder_impeller.cc:180)
fml::ConcurrentMessageLoopDarwin::ExecuteTask(std::_LIBCPP_ABI_NAMESPACE::function<void ()> const&) (concurrent_message_loop_factory.mm:18)
void* std::_LIBCPP_ABI_NAMESPACE::__thread_proxy[abi:v15000]<std::_LIBCPP_ABI_NAMESPACE::tuple<std::_LIBCPP_ABI_NAMESPACE::unique_ptr<std::_LIBCPP_ABI_NAMESPACE::__thread_struct, std::_LIBCPP_ABI_NAMESPACE::default_delete<std::_LIBCPP_ABI_NAMESPACE::__thread_struct> >, fml::ConcurrentMessageLoop::ConcurrentMessageLoop(unsigned long)::$_0> >(void*) (vector:1372)
__pthread_start + 116
``` 

### Expected results

don't crash

### Actual results

crash

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>flutter doctor -v</summary>
<p>

```

[!] Flutter (Channel [user-branch], 3.13.9, on macOS 13.6.1 22G313 darwin-x64, locale zh-Hans-CN)
    ! Flutter version 3.13.9 on channel [user-branch] at /Users/kezhuang/Library/Flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at
      https://flutter.dev/docs/get-started/install.
    ! Upstream repository unknown source is not a standard remote.
      Set environment variable "FLUTTER_GIT_URL" to unknown source to dismiss this error.
    • Framework revision d211f42860 (4 weeks ago), 2023-10-25 13:42:25 -0700
    • Engine revision 0545f8705d
    • Dart version 3.1.5
    • DevTools version 2.25.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly
      to perform update checks and upgrades.

[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/kezhuang/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.2.5)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.84.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.76.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 13.6.1 22G313 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 119.0.6045.159

[✓] Network resources             
    • All expected network resources are available.

! Doctor found issues in 2 categories.
``` 

</p>
</details>

**Comment by dam-ease** [comment] 2023-11-23 08:07
Thanks for filing this.
Does this reproduce locally or in production?
Can you upgrade to the latest versions of Flutter and try running a newly created Flutter app to see if this crash reproduces?
Also, for this issue to be workable, we will need a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code?

**Comment by ke780382349** [comment] 2023-11-24 07:43
In production.
It can't be upgraded for a while.
I can't get any code information from this stack
It could happen anywhere

**Comment by dam-ease** [comment] 2023-11-24 07:55
Thanks for your response.
Can you help with the full crash log since this seems to only occur in production?

**Comment by ke780382349** [comment] 2023-11-24 08:02
![image](https://github.com/flutter/flutter/assets/10646576/d8012221-0790-442a-8510-3b569d10c88a)
here~~ 
This is full crash log~

**Comment by dam-ease** [comment] 2023-11-24 12:29
Thanks for your response.
Kindly share the logs in text format.
Please avoid posting screenshots unless necessary.

**Comment by ke780382349** [comment] 2023-11-27 11:21
flutter: :ImpellerAllocator.:allocPixelRef(SkBitmap*)(image_decoder_impeller.cc:542)
flutter::ImpellerAllocator::allocPixelRef(SkBitmap*)(new.cpp:67) std.:_LIBCPP_ABI_NAMESPACE::__function::_func<flutter::ImageDecoder|mpeller.:Decode(fml.:RefPtr<flutter::|mageDescriptor>,unsignedint,unsignedint, std::_LIBCPP_ABI_NAMESPACE::function<void (sk_sp<flutter::DIlmage>, std:_LIBCPP_ABI_NAMESPACE.basic_string<char, std.:_LIBCPP_ABI_NAMESPACE::char_traits<char>, std::_LIBCPP_ABI_NAMESPACE..allocator<char> >)> const&).:$_1, std:_LIBCPP_ABI_NAMESPACE::allocator<flutter.:ImageDecoderlmpeller::Decode(fml.:RefPtr<flutter:ImageDescriptor>,unsignedint,unsignedint, std::_LIBCPP_ABI_NAMESPACE::function<void (sk_sp<flutter::DIlmage>, std::_LIBCPP_ABI_NAMESPACE::basic_string<char, std::_LIBCPP_ABI_NAMESPACE::char_traits<char>, std::_LIBCPP_ABI_NAMESPACE::allocator<char>>)> const&)::$_1>, void 0>::operator00 (image_decoder_impeller.cc:180) fml::ConcurrentMessageLoopDarwin::ExecuteTask(std::_LIBCPP_ABI_NAMESPACE::function<void(>const&)(concurrent_message_loop_factory.mm:18)
void* std::_LIBCPP_ABI_NAMESPACE::__thread_proxy[abi:v15000] <std:_LIBCPP_ABI_NAMESPACE::tuple<std:_LIBCPP_ABI_NAMESPACE::unique_ptr<std::_LIBCPP_ABI_NAMESPACE::__thread_struct, std::_LIBCPP_ABI_NAMESPACE::default_delete<std::_LIBCPP_ABI_NAMESPACE::__thread_struct>>, fml::ConcurrentMessageLoop::ConcurrentMessageLoop(unsigned long)::$_0> >(void*) (vector: 1372)
_pthread_start + 116

**Comment by KlausLiu** [comment] 2023-11-29 09:27
Same to me~

**Comment by jonahwilliams** [comment] 2023-12-04 18:39
We should verify that our code correct handles failure to allocate the SkBitmap and associated data structures. xref: https://github.com/flutter/engine/blob/main/lib/ui/painting/image_decoder_impeller.cc#L557-L579

**Comment by fyxtc** [comment] 2024-02-19 01:39
Same issue, maybe high memory?

**Comment by chinmaygarde** [comment] 2024-03-11 20:52
We've added more checks in https://github.com/flutter/engine/pull/50787. If there are additional failures after this point, we can track these separately. Closing as fixed.

**Closed by chinmaygarde** 2024-03-11 20:52 UTC
Labels: c: crash, platform-ios, engine, a: production, P2, e: impeller, team-engine, triaged-engine

**Comment by ggirotto** [comment] 2024-03-20 14:10
@chinmaygarde what's the expected version that will include this fix?
