### ISSUE TITLE
final arguments = state.queryParameters seems deprecated

### ISSUE THREAD

**Issue by dr4mail** [flutter/flutter#138400] opened 2023-11-14 08:05 UTC
This piece of code is not compiled because of final arguments = state.queryParameters seems deprecated.
        The **final arguments = state.uri.queryParameters;** works (with uri).

in the main.dart:

routes: [
            GoRoute(
              path: 'forgot-password',
              builder: (context, state) {
                **final arguments = state.queryParameters;**
                return ForgotPasswordScreen(
                  email: arguments['email'],
                  headerMaxExtent: 200,
                );
              },
            ),

**Comment by danagbemava-nc** [comment] 2023-11-14 10:06
Hi @dr4mail, this was an intended change. See the migration guide.  https://docs.google.com/document/d/1vjupshmFJtfGSOppZxp7Tzkq7dotcLxCcpdluuNYe1o/edit?resourcekey=0-aS66t4OcDTjJW50s-veSzQ

Closing as this was intended.

**Closed by danagbemava-nc** 2023-11-14 10:06 UTC
Labels: in triage
