### ISSUE TITLE
Failures in integration_test-based tests run via driver don't fail the step

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#60943] opened 2020-07-07 00:54 UTC
Example: https://cirrus-ci.com/task/5819520474415104

```
[...]
xvfb-run ./script/incremental_build.sh drive-examples --linux
Checking for changed packages from d3ccc34855b77afae39f4078cb4add8bec9e6b2b
Detected changes in the following 1 package(s):
url_launcher
running drive-examples --linux
Starting application: test_driver/url_launcher_e2e.dart
Building Linux application...                                   
flutter: Observatory listening on http://127.0.0.1:36053/2ki0Gnu5d48=/
flutter: 00:00 +0: canLaunch
flutter: 00:00 +0: canLaunch [E]
flutter:   Expected: <true>
    Actual: <false>
flutter:   [...]
flutter: 00:00 +0 -1: (tearDownAll)
flutter: Warning: E2E test plugin was not detected.
flutter: 00:00 +1 -1: Some tests failed.
Stopping application instance.
VMServiceFlutterDriver: Connecting to Flutter application at http://127.0.0.1:36053/2ki0Gnu5d48=/
VMServiceFlutterDriver: Isolate found with number: 3840818254652015
VMServiceFlutterDriver: Isolate is not paused. Assuming application is ready.
VMServiceFlutterDriver: Connected to Flutter application.
All driver tests successful!
```

Clearly `flutter: 00:00 +1 -1: Some tests failed` shouldn't lead to `All driver tests successful!` and a green CI result on the PR.

I don't know if this is a general problem, or specific to Linux somehow; I'll mark it as Linux until we know if it happens elsewhere.

**Comment by stuartmorgan** [comment] 2020-07-07 16:25
Oh, is this because I forgot about implementing the e2e plugin for Linux? I'm not entirely clear on what the role of the e2e plugin is.

**Comment by stuartmorgan** [comment] 2020-09-12 23:08
This is happening on Windows as well. Running `flutter drive` on a failing test is giving an exit code of zero for some reason.

**Comment by stuartmorgan** [comment] 2020-09-12 23:39
Debugging in url_launcher_windows, I'm seeing `requestData` returning `{"result":"true","failureDetails":[]}` even when there has been a test failure. But it's not clear to me how exactly the `FlutterDriver` plumbing is supposed to work in the plugin tests (nothing obviously seems to call `enableFlutterDriverExtension`?) so I'm not sure where exactly to debug.

**Comment by vegaro** [comment] 2020-11-06 21:50
This basically makes running integration tests useless on CI when running on a linux machine. I can confirm they work fine on a MacOS machine, but not in a Linux. I am using the `integration_test` package.

**Comment by stuartmorgan** [comment] 2020-11-12 19:06
Discussed with dnfield and now understand how integration_test is supposed to work. Not having the plugin implemented is indeed the issue here.

For macOS we should be able to do basically the same thing the iOS plugin does so that testing from Xcode is possible. For Linux and Windows I'll make a stub plugin that just collects and vends back the failure state but doesn't interact with any other test systems (which is actually a core purpose of integration_test), and then we can figure out what test system(s) if any we want to tie into on those platforms.

**Comment by stuartmorgan** [comment] 2020-11-19 01:39
I looked at the iOS plugin again after discussion with @dnfield, and was increasingly confused as to how it worked, so I tested and... it doesn't. And apparently Android doesn't either, because [this test PR](https://github.com/flutter/plugins/pull/3277), which reverses one of the test expectations without any code changes, is completely green.

I can see how the iOS plugin accomplishes the `integration_test` goal of reflecting integration tests results into XCTest runs. But wiring that up be runnable via `flutter drive` is, AFAICT, completely broken; I'm not even sure how it's supposed to work. Looking at the iOS plugin, there are at least two problems:
- In the `drive` scenario, the plugin is never registered. `registerWithRegistrar:` is a no-op, and `setupChannels:` is never called because that's something that's manually called by the XCTest machinery, but `flutter drive` isn't *doing* an `XCTest`.
- Even if I fix that, test result reporting still only seems to go in one direction. The `allTestsFinished` message receives test results on the native side (in theory to report them to XCTest), but this boilerplate code in `test_driver/integration_test.dart`:
  ```
  final FlutterDriver driver = await FlutterDriver.connect();
  final String data =
      await driver.requestData(null, timeout: const Duration(minutes: 1));
  await driver.close();
  final Map<String, dynamic> result = jsonDecode(data);
  exit(result['result'] == 'true' ? 0 : 1);
  ```
  doesn't do anything useful; `result` is always `{result: true, failureDetails: []}` even when tests fail. I'm still not actually clear on how data is supposed to get to whatever is backing `requestData`, but it doesn't seem to work in practice.

Here's the iOS run from the PR above demonstrating this (matching the current desktop behavior that I was invetigating):
```running drive-examples
Running command: "flutter drive --driver test_driver/integration_test.dart --target integration_test/url_launcher_test.dart" in /private/var/folders/3y/l0z1x3693dl_8n0qybp4dqwh0000gn/T/cirrus-ci-build/packages/url_launcher/url_launcher/example
Running "flutter pub get" in example...                            832ms
Warning: Missing build name (CFBundleShortVersionString).
Warning: Missing build number (CFBundleVersion).
Running pod install...                                           1,716ms
Running Xcode build...                                          
Xcode build done.                                           29.3s
flutter: 00:00 +0: canLaunch
flutter: 00:00 +0: canLaunch [E]
flutter:   Expected: <true>
    Actual: <false>
flutter:   package:test_api/src/frontend/expect.dart 155:31                                                                                                                 fail
  package:test_api/src/frontend/expect.dart 150:3                                                                                                                  _expect
  package:test_api/src/frontend/expect.dart 59:3                                                                                                                   expect
  package:flutter_test/src/widget_tester.dart 429:3                                                                                                                expect
  private/var/folders/3y/l0z1x3693dl_8n0qybp4dqwh0000gn/T/cirrus-ci-build/packages/url_launcher/url_launcher/example/integration_test/url_launcher_test.dart 16:5  main.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1126:19                                                                 <…>
flutter: 00:00 +0 -1: (tearDownAll)
flutter: Warning: integration_test test plugin was not detected.
flutter: 00:00 +1 -1: Some tests failed.
Action Required: You must set a build name and number in the pubspec.yaml file version field before submitting to the App Store.
Warning: CocoaPods recommended version 1.9.0 or greater not installed.
Pods handling may fail on some projects involving plugins.
To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.
VMServiceFlutterDriver: Connecting to Flutter application at http://127.0.0.1:51031/4KmZ54GIRng=/
VMServiceFlutterDriver: Isolate found with number: 1652731940884991
VMServiceFlutterDriver: Isolate is paused at start.
VMServiceFlutterDriver: Attempting to resume isolate
VMServiceFlutterDriver: Connected to Flutter application.
Failed to stop app
All driver tests successful!
```

Note both the
```flutter: Warning: integration_test test plugin was not detected.```
as well as
```
flutter: 00:00 +1 -1: Some tests failed.
[...]
All driver tests successful!```
(The latter continues to be true even if registering the plugin correctly in this scenario.)

So before I fix this for desktop we'll need to figure out how this is intended to work in general, since currently I don't seem to have a working model to follow.

(@dnfield please loop in anyone else who should be involved)

**Comment by dnfield** [comment] 2020-11-19 04:29
What's supposed to be happening is the driver related bindings setting any failures to the request data. Depending on how/where this is failing it might be something that we need #50816 to fix. I'll take a look.

**Comment by dnfield** [comment] 2020-11-20 00:56
@jiahaog is taking a look at this

**Comment by jiahaog** [comment] 2020-11-20 07:38
Failures are not surfacing because of the usage of `test` instead of `testWidgets` - sending flutter/plugins#3279 to fix this. Only using `testWidgets` is supported for `package:integration_test` previously – this is #50816 which was resolved with the additon of a new API, but the API is not in use in flutter/plugins yet. We should definitely do this but there may be some dependency conflicts in doing so - I filed #70922 to track it. 

Regarding native plugins – there are three methods to run integration tests which can be a bit confusing about when they are used:

1. Using `flutter drive`
2. Using native test frameworks - XCTest, Expresso, etc.

The former is the main form of CI testing in flutter/plugins. CI runs `flutter drive` for the `examples/` in all packages in this repo. There are also some Firebase test lab tests that run as well, only on Android. I'm not sure if the XCTest flow is exercised on CI at all. The native flutter plugins for `package:integration_test` is only needed for (2). 

On a high level, this is how reporting of results works:

1. The app is started (somehow)
2. The test infrastructure (the host in `flutter drive`, Expresso, XCTest) waits for test results
3. Dart tests run to completion, where results are saved in the `IntegrationTestWidgetsFlutterBinding`
4. Results are sent over the platform channel to the native integration_test plugin. If this is not present, the error is caught and a warning is printed.
5. The waiting tasks in (2) can now complete, and they report the results accordingly.

I hope this clears things up a little, please let me know if there's anything I can help to clarify.

**Comment by stuartmorgan** [comment] 2020-11-20 15:22
To make sure I'm understanding correctly: step 4 (and thus the plugin) is irrelevant when using `flutter drive` rather than running from a platform-specific test infrastructure like XCTest, right? I.e., the `driver.requestData` should be getting results from step 3, not the plugin?

**Comment by jiahaog** [comment] 2020-11-20 23:41
Yup, step 4 is only needed for platform specific test infrastructure.

**Comment by jiahaog** [comment] 2020-12-02 00:38
Let me know if otherwise, but with flutter/plugins#3279 merged I think the original issue has been resolved, so closing :)

**Closed by jiahaog** 2020-12-02 00:38 UTC
Labels: P2, p: tooling, plugin
