### ISSUE TITLE
Can't input text in TextField [Flutter_web]

### ISSUE THREAD

**Issue by mahmoudsalah37** [flutter/flutter#40055] opened 2019-09-08 12:02 UTC
[INFO] Connecting to the build daemon...
[INFO] Generating build script...
[INFO] Generating build script completed, took 398ms
[INFO]
[INFO] Deleted previous snapshot due to core package update
[INFO] Creating build script snapshot......
[INFO] Creating build script snapshot... completed, took 14.6s
[INFO]
[INFO] Starting daemon...
[INFO] Initializing inputs
[INFO] Reading cached asset graph...
[WARNING] Throwing away cached asset graph due to Dart SDK update.
[INFO] Cleaning up outputs from previous builds....
[INFO] Cleaning up outputs from previous builds. completed, took 381ms
[INFO] Generating build script...
[INFO] Generating build script completed, took 91ms
[INFO]
[INFO] Creating build script snapshot......
[INFO] Creating build script snapshot... completed, took 14.5s
[INFO]
[INFO] Starting daemon...
[INFO] Initializing inputs
[INFO] Building new asset graph...
[INFO] Building new asset graph completed, took 1.8s
[INFO] Checking for unexpected pre-existing outputs....
[INFO] Checking for unexpected pre-existing outputs. completed, took 1ms
[INFO] Initializing inputs
[INFO] Building new asset graph...
[INFO] Building new asset graph completed, took 1.8s
[INFO]
[INFO] Checking for unexpected pre-existing outputs....
[INFO] Checking for unexpected pre-existing outputs. completed, took 1ms
[INFO]
[INFO] Setting up file watchers...
[INFO] Setting up file watchers completed, took 2ms
[INFO]
[INFO] Registering build targets...
[INFO] Starting initial build...
[INFO] Starting resource servers...
[INFO] Serving DevTools at http://127.0.0.1:63054
[INFO] Serving `web` on http://127.0.0.1:63023
[INFO] About to build [web]...
[INFO] Running build...
[INFO] 1.0s elapsed, 33/44 actions completed.
[INFO] 2.0s elapsed, 245/265 actions completed.
[INFO] 3.1s elapsed, 469/487 actions completed.
[INFO] 4.2s elapsed, 669/673 actions completed.
[INFO] 5.2s elapsed, 977/980 actions completed.
[INFO] 6.2s elapsed, 1056/1116 actions completed.
[INFO] 7.3s elapsed, 1056/1116 actions completed.
[INFO] 8.3s elapsed, 1060/1120 actions completed.
[INFO] 9.4s elapsed, 1064/1124 actions completed.
[INFO] 10.4s elapsed, 1068/1124 actions completed.
[INFO] 11.5s elapsed, 1072/1124 actions completed.
[INFO] 12.5s elapsed, 1080/1129 actions completed.
[INFO] 13.6s elapsed, 1091/1132 actions completed.
[INFO] 14.6s elapsed, 1093/1133 actions completed.
[INFO] 15.6s elapsed, 1093/1133 actions completed.
[INFO] 16.7s elapsed, 1097/1135 actions completed.
[INFO] 17.7s elapsed, 1098/1135 actions completed.
[INFO] 18.7s elapsed, 1098/1135 actions completed.
[INFO] 19.8s elapsed, 1098/1135 actions completed.
[INFO] 20.9s elapsed, 1102/1136 actions completed.
[INFO] 22.0s elapsed, 1105/1139 actions completed.
[INFO] 23.0s elapsed, 1108/1141 actions completed.
[INFO] 24.0s elapsed, 1112/1145 actions completed.
[INFO] 25.1s elapsed, 1116/1149 actions completed.
[INFO] 26.1s elapsed, 1123/1156 actions completed.
[INFO] 27.2s elapsed, 1134/1167 actions completed.
[INFO] 28.2s elapsed, 1144/1177 actions completed.
[INFO] 29.3s elapsed, 1153/1186 actions completed.
[INFO] 30.4s elapsed, 1162/1194 actions completed.
[INFO] 31.4s elapsed, 1173/1206 actions completed.
[INFO] 32.4s elapsed, 1185/1213 actions completed.
[INFO] 33.5s elapsed, 1196/1218 actions completed.
[INFO] 34.5s elapsed, 1199/1218 actions completed.
[INFO] 35.6s elapsed, 1206/1218 actions completed.
[INFO] 36.7s elapsed, 1213/1218 actions completed.
[INFO] 37.7s elapsed, 1216/1218 actions completed.
[INFO] 38.8s elapsed, 1216/1218 actions completed.
[INFO] 39.9s elapsed, 3126/3126 actions completed.
[INFO] Running build completed, took 40.1s
[INFO] Caching finalized dependency graph...
[INFO] Caching finalized dependency graph completed, took 234ms
[INFO] Succeeded after 40.4s with 1117 outputs (4505 actions)
[INFO] ------------------------------------------------------------------------
[INFO] Debug service listening on ws://localhost:63180/ju-n3Fb5LlE=

//Code
import 'package:flutter_web/material.dart';
import 'package:iso/styles/all/all.dart';

class PolicyPage extends StatefulWidget {
  _PolicyPageState createState() => _PolicyPageState();
}

class _PolicyPageState extends State<PolicyPage> {
  String _textPolicy;
  @override
  Widget build(BuildContext context) {
    return Container(
      child: Column(
        mainAxisAlignment: MainAxisAlignment.start,
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: <Widget>[
          Container(
            color: colorContext,
            height: 40.0,
            child: Center(
                child: Text(
              'Policy',
              style: tsMainText,
            )),
          ),
          Expanded(
            child: SingleChildScrollView(
              child: Container(
                color: Colors.white,
                child: Padding(
                  padding: const EdgeInsets.all(8.0),
                  child: TextField(
                    decoration: InputDecoration(
                      hintText: 'Policy statement',
                      hintStyle: TextStyle(
                        color: colorHintText,
                      ),
                    ),
                    autofocus: true,
                    maxLines: 30,
                    onChanged: (String textPolicy) {
                      this._textPolicy = textPolicy;
                      setState(() {});
                    },
                    textAlign: TextAlign.start,
                  ),
                ),
              ),
            ),
          ),
          Padding(
            padding: const EdgeInsets.all(8.0),
            child: FlatButton(
              highlightColor: Colors.blueAccent[300],
              hoverColor: Colors.blueAccent[100],
              color: Colors.white,
              child: Text(
                'Save',
                style: TextStyle(color: Colors.blue),
              ),
              onPressed: () {
                setState(() {});
              },
            ),
          )
        ],
      ),
    );
  }
}

**Comment by xeu100** [comment] 2019-09-08 13:16
Do you mean that you're unable to type at all in TextFields?

**Comment by mahmoudsalah37** [comment] 2019-09-08 13:33
> Do you mean that you're unable to type at all in TextFields? If so, I have the same issue.

Yes, it was working before but now I don't know what happened

**Comment by xeu100** [comment] 2019-09-08 14:55
> > Do you mean that you're unable to type at all in TextFields? If so, I have the same issue.
> 
> Yes, it was working before but now I don't know what happened

Yeah, there was an issue with a package so I upgraded and updated packages and then this happened. Maybe a faulty update caused it :\ Either way, none of my projects are functional until this is patched.

**Comment by mahmoudsalah37** [comment] 2019-09-08 15:38
> > > Do you mean that you're unable to type at all in TextFields? If so, I have the same issue.
> > 
> > 
> > Yes, it was working before but now I don't know what happened
> 
> Yeah, there was an issue with a package so I upgraded and updated packages and then this happened. Maybe a faulty update caused it :\ Either way, none of my projects are functional until this is patched.

do you find any solve for it?

**Comment by xeu100** [comment] 2019-09-08 15:57
So far I haven't found a fix. We need to wait for the Flutter developers to patch it. I found out that non-Web users are experiencing this too.

**Comment by jonahwilliams** [comment] 2019-09-08 17:26
Please include the output of `flutter doctor -v`

**Comment by GMC254** [comment] 2019-09-08 18:00
Reported the same issue on #40039 you can actually type into the Textfield and TextFormField but somehow looking at chrome dev tools it defaults to transparent.

**Comment by xeu100** [comment] 2019-09-08 18:31
> Reported the same issue on #40039 you can actually type into the Textfield and TextFormField but somehow looking at chrome dev tools it defaults to transparent.

When keeping dev tools closed, it still doesn't work. Is this what you meant?

**Comment by jonahwilliams** [comment] 2019-09-08 18:33
Marking as a duplicate of https://github.com/flutter/flutter/issues/40039

**Closed by jonahwilliams** 2019-09-08 18:33 UTC
Labels: waiting for customer response

**Comment by raajkumars** [comment] 2019-09-10 03:19
I do not think that this is related to https://github.com/flutter/flutter/issues/40039. Yes the color of the text is transparent. After temporarily disabling element's CSS color using Chrome, I can see the characters being typed. But it does not clear the current text in the field properly. For ex: pressing delete or backspace key move the cursor but does not delete the characters that are already there. Also the type text do not change the text in the backing edit controller.

**Comment by GMC254** [comment] 2019-09-10 12:07
It

> I do not think that this is related to #40039. Yes the color of the text is transparent. After temporarily disabling element's CSS color using Chrome, I can see the characters being typed. But it does not clear the current text in the field properly. For ex: pressing delete or backspace key move the cursor but does not delete the characters that are already there. Also the type text do not change the text in the backing edit controller.

I highly suspect that It's related. It's the same issue I faced only went further to try troubleshoot. Just like this issue, the one I reported on #40039 started at just about the same time and I do agree with the author of this issue, it was working before then it just stopped.

**Comment by bjornwilliam** [comment] 2019-09-13 12:03
The problem is the flutter_web version. 
If you use  
 flutter_web:
    git:
      ref: cc38319
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web
you can enter data into textfields.

If you use and later commit textfields are broken.

**Comment by denbes787** [comment] 2019-09-18 07:55
> The problem is the flutter_web version.
> If you use
> flutter_web:
> git:
> ref: cc38319
> url: https://github.com/flutter/flutter_web
> path: packages/flutter_web
> you can enter data into textfields.
> 
> If you use any later commit textfields are broken.

It works! Thanks!

**Comment by skillitzimberg** [comment] 2019-09-22 14:32
> The problem is the flutter_web version.
> If you use
> flutter_web:
> git:
> ref: cc38319
> url: https://github.com/flutter/flutter_web
> path: packages/flutter_web
> you can enter data into textfields.
> 
> If you use any later commit textfields are broken.
To be clear for the relatively uninitiated like myself, this should be added to the pubspec.yaml file. I added it to mine as follows and I can use text fields again:
```
name: web_flutter
description: An app built using Flutter for web

environment:
  # You must be using Flutter >=1.5.0 or Dart >=2.3.0
  sdk: '>=2.3.0-dev.0.1 <3.0.0'

dependencies:
  flutter_web: any
  flutter_web_ui: any
  provider: any
  rxdart: ^0.22.0
  http: ^0.12.0+2
  json_annotation: ^2.4.0
  intl: 0.15.8
  firebase: any


dev_dependencies:
  build_runner: ^1.4.0
  build_web_compilers: ^2.0.0
  pedantic: ^1.0.0
  json_serializable: ^3.0.0
  test: any

flutter:
  uses-material-design: true

dependency_overrides:
  flutter_web:
    git:
      ref: cc38319
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web
  flutter_web_ui:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_ui
  provider:
    git:
      url: https://github.com/kevmoo/provider
      ref: flutter_web

```
