### ISSUE TITLE
Flutter SDK version constraints in pubspec.yaml are mangled in generated lock file

### ISSUE THREAD

**Issue by jaysephjw** [flutter/flutter#137439] opened 2023-10-27 18:29 UTC
pubpsec.yaml flutter sdk constraints are mangled in generated .lock file. 

### Steps to reproduce

Create a pubspec.yaml file with the following: 

```
environment:
  sdk: '3.1.4'
  flutter: '3.13.8'
``` 

**Expected** pubspec.lock:

```
sdks:
  dart: "3.1.4"
  flutter: "3.13.8"
```

**Actual**: 
```
sdks:
  dart: "3.1.4"
  flutter: ">=3.13.8"
```

Lock file changes the constraints, either removing the upper bound, adding ">=", or switching it to "any".

More testing:   
  ```
  "3.13.8"  generates ">=3.13.8"
  ">=3.13.8 <4.0.0" generates ">=3.13.8"
  "<=3.13.8" generates "any"
  ```
  
https://dart.dev/tools/pub/pubspec#sdk-constraints states the flutter sdk constraint is an sdk constraint, which support the same syntax as version constraints.

**Use case:**
I want to enforce my app is built with the same version of the flutter SDK every time. 

<details>
<summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.13.8, on Microsoft Windows [Version 10.0.19045.3570], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[X] Android toolchain - develop for Android devices
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.5.0)
[√] Android Studio (version 2021.3)
[√] Android Studio (version 2022.3)
[√] IntelliJ IDEA Ultimate Edition (version 2021.1)
[√] VS Code (version 1.76.0)
[√] Connected device (3 available)
[√] Network resources
```

</details>

### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

**Comment by jaysephjw** [comment] 2023-10-27 18:37
https://github.com/flutter/flutter/issues/29211#issuecomment-806956620 mentions this issue in 2021, but the issue was unfocused.

**Comment by stuartmorgan** [comment] 2023-10-27 20:24
Closing as a duplicate of https://github.com/flutter/flutter/issues/90773

**Closed by stuartmorgan** 2023-10-27 20:24 UTC
