### ISSUE TITLE
TextField suffix iconButton onpressed also triggers ontap of TextField 

### ISSUE THREAD

**Issue by maheshmnj** [flutter/flutter#51994] opened 2020-03-05 04:42 UTC
I have a texfield widget with a suffix icon (Icon Button) when I tap on either of it (textfield / icon), my intended behavior is that it should navigate to next screen,but it is pushing a new widget twice on top of the stack,Then I realized that this is because I have navigation code separately written for the suffix  iconbutton and the on tap method of textfield,  when I tap the icon it also executes onTap method for the textfield is it the intended behavior or an issue,This is the code for my textfield
```
                   TextField(
                          style: inputStyle,
                          controller: controllersList[x],
                          readOnly: x < 3 ? true : false,
                          onTap: () {
                            print('textfield tapped $x');      // this gets executed on suffix icon tap
                                Navigator.of(context).push(MaterialPageRoute(
                                    builder: (context) => SearchAddress(
                                          addressType: AddressType.apartment,
                                        )));
                          },
                          decoration: InputDecoration(
                              contentPadding: const EdgeInsets.all(15),
                              hintText: '${addressHints[x]}',
                              hintStyle: hintStyle,
                              suffixIcon: (x < 3)
                                  ? IconButton(
                                      onPressed: (){
                                    Navigator.of(context).push(MaterialPageRoute(
                                    builder: (context) => 
                                        )));
                                      },
                                      icon: Icon(Icons.arrow_forward_ios,
                                          size: 16, color: marginColor),
                                    )
                                  : null)),
```
this is the output of my flutter environment ```flutter doctor -v```
```
[✓] Flutter (Channel master, v1.15.4-pre.241, on Linux, locale en_US.UTF-8)
    • Flutter version 1.15.4-pre.241 at /home/al004/flutter_linux_v1.7.8+hotfix.4-stable/flutter
    • Framework revision 1d3fcfd6ca (4 days ago), 2020-02-29 10:01:18 -0800
    • Engine revision 755e2b559d
    • Dart version 2.8.0 (build 2.8.0-dev.10.0 09bbd3cca5)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/al004/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /home/al004/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /home/al004/android-studio
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (3 available)
    • Android SDK built for x86 • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Chrome                    • chrome        • web-javascript • Google Chrome 79.0.3945.130
    • Web Server                • web-server    • web-javascript • Flutter Tools

• No issues found!
```

**Comment by TahaTesser** [comment] 2020-03-05 08:09
### Code Sample
```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: TextField(
          onTap: () => print('TextField onTap'),
          decoration: InputDecoration(
              suffixIcon: IconButton(
                  icon: Icon(Icons.arrow_forward_ios),
                  onPressed: () => print('suffixIcon pressed'))),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {},
      ),
    );
  }
}
```
### Logs
```
I/flutter ( 7358): suffixIcon pressed
I/flutter ( 7358): TextField onTap
```

Thank you for your contribution

**Comment by justinmc** [comment] 2020-03-11 19:14
I believe this is a duplicate of https://github.com/flutter/flutter/issues/39376, but let me know if I'm wrong and I'll reopen.

I was working on a PR for this awhile back but never got a chance to finish it: https://github.com/flutter/flutter/pull/38722

**Closed by justinmc** 2020-03-11 19:14 UTC
Labels: a: text input, f: material design, framework, severe: regression

**Comment by DeveloperWaybee** [comment] 2020-03-16 23:21
SOLUTION

Here's the solution for a suffix or prefix taps

[Solution Link](https://github.com/flutter/flutter/issues/36948#issuecomment-599797015)
