### ISSUE TITLE
LG Stylo 6 freezes or restarts while running a Flutter app

### ISSUE THREAD

**Issue by GrimDevStudio** [flutter/flutter#73011] opened 2020-12-27 20:52 UTC
I'd like to apologize in advance for the vague description, but I'm in a bit of a bind...I've had the issue in the title reported by more than a few LG Stylo 6 users of my published app. It's impossible for me to get any more detailed logs since their device either completely freezes or restarts while running the app. I suspect it could be the AnimatedSwitcher widget that's causing it but, as I've said, there is no way for me to confirm it.

Did anyone else encounter a similar issue?

**Comment by pedromassangocode** [comment] 2020-12-28 11:39
Hi @GrimDevStudio 
Can you please provide your `flutter doctor -v` and the details about the device where the issue happens?
How are you getting this feedback? Is by some Crashlytics service? If so, can you get share the logs?

Unless you share some reproducible code sample there is nothing the Flutter team/community can do to help you. Please try to investigate it further and share additional details about the issue if possible.
Thank you

**Comment by GrimDevStudio** [comment] 2020-12-28 11:46
I'm getting the feedback about phone freezing and restarting from user reviews on the Play Store, and I can see that 99% of those reviews are running Lg Stylo 6. I cannot provide any details as I am not able to reproduce the bug on any of my devices...flutter doctor would be useless for the same reason.

**Comment by GrimDevStudio** [comment] 2020-12-28 11:48
@pedromassangocode I'm getting the feedback about phone freezing and restarting from user reviews on the Play Store, and I can see that 99% of those reviews are running Lg Stylo 6. I cannot provide any details as I am not able to reproduce the bug on any of my devices...flutter doctor would be useless for the same reason.

I know this is very vague but device completely freezing or rebooting seems like a serious issue, so I'm sharing it here in hope that somebody with the said device or similar experience can perhaps shed some more light on it.

**Comment by pedromassangocode** [comment] 2020-12-28 13:40
Hi @GrimDevStudio 
I would still need the `flutter doctor -v` to know what version of Flutter causes this issue.

**Comment by GrimDevStudio** [comment] 2020-12-28 13:49
@pedromassango I've had the issue reported for builds produced with latest versions on both stable and dev channel. Here is flutter doctor log for stable:

```
[√] Flutter (Channel stable, 1.22.5, on Microsoft Windows [Version 10.0.19041.685], locale en-US)
    • Flutter version 1.22.5 at C:\src\flutter
    • Framework revision 7891006299 (3 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\Administrator\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.
```

**Comment by justinmc** [comment] 2020-12-28 17:24
If anyone out there has an LG Stylo 6 and can try reproducing this, it would be much appreciated!  @GrimDevStudio could you come up with your best guess at a minimal example app that someone could try to reproduce this with?

**Comment by GrimDevStudio** [comment] 2020-12-29 11:03
@justinmc well the app in question is fairly complex (it's a 2d game made in flutter), but if my suspicions are correct and it's the animation that causes the issue anything with either AnimatedSwitcher or AnimatedContainer / AnimatedOpacity will do. Animations are triggered occasionally as user taps various cells in a GridView. 

Though, I must point out that this is just a guess, anything could be causing it as far as I know. Good thing is that I'm not using any 3rd party plugins, just out-of-the-box Flutter code.

**Comment by GrimDevStudio** [comment] 2021-01-06 16:27
Just wanted to add that I've had this reported by T-Mobile REVVL 4 users as well. Still no luck reproducinig the bug, as I don't have any of those devices available in my country...

**Comment by kf6gpe** [comment] 2021-01-25 19:19
Without a specific reproducible case, we're not able to reproduce this on this hardware. Unfortunately we have to close this issue. If you can provide a minimal reproducible case on easy-to-source Android hardware, we'll be happy to reopen this and take another look. Thanks!

**Closed by kf6gpe** 2021-01-25 19:19 UTC
Labels: e: device-specific, engine, passed first triage, perf: speed, platform-android, severe: performance
