### ISSUE TITLE
[web] In chrome browser, I got blank background when convert canvas to image file

### ISSUE THREAD

**Issue by topex-psy** [flutter/flutter#105814] opened 2022-06-11 03:43 UTC
In flutter I created a simple drawing app which support android, iOS and web. It will load image from url as the background, and users will be able to draw lines and add texts on it. The problem is on the web, specifically in chrome-based browser, the background is missing, although it works fine in Safari and Firefox.

## Steps to Reproduce

first, I have image url from network, I convert it into `dart:ui` Image

```dart
Future<ui.Image?> loadUiNetworkImage(String? url) async {
  if (url == null) return null;
  final http.Response response = await http.get(Uri.parse(url));
  final list = response.bodyBytes;
  final completer = Completer<ui.Image>();
  ui.decodeImageFromList(list, completer.complete);
  return completer.future;
}

final background = await loadUiNetworkImage(backgroundUrl);
```

then in my CustomPainter widget I put the image as the background using `paintImage` function:

```dart
@override
void paint(Canvas canvas, Size size) {

  _addBackground(ui.Image background, {double scale = 1.0}) {
    final width = background.width * scale;
    final height = background.height * scale;

    final left = (size.width - width) / 2.0;
    final top = (size.height - height) / 2.0;

    paintImage(
      canvas: canvas, 
      rect: Rect.fromLTWH(left, top, width, height),
      image: background,
      fit: BoxFit.scaleDown,
      repeat: ImageRepeat.noRepeat,
      scale: 1.0,
      alignment: Alignment.center,
      flipHorizontally: false,
      filterQuality: FilterQuality.high
    );
  }

  if (background != null) {
    final scale = min(size.width / background!.width, size.height / background!.height);
    _addBackground(background!, scale: scale);
    canvas.saveLayer(null, Paint());
  }

  // also some drawings i.e. `drawLine` & `TextPainter`
}
```

this is my CustomPainter resides in widget tree:

```dart
RepaintBoundary(
  key: _globalKey,
  child: Container(
    width: MediaQuery.of(context).size.width,
    height: MediaQuery.of(context).size.height,
    color: Colors.white,
    child: StreamBuilder<List<dynamic>>(
      stream: linesStreamController.stream,
      builder: (context, snapshot) {
        return CustomPaint(
          painter: Sketcher(
            background: _background,
            prevDrawing: _prevDrawing,
            lines: _lines,
          ),
        );
      },
    ),
  ),
);
```

then I save the drawing or whole canvas as an image file using this function:

```dart
_save() async {
  try {
    final boundary = _globalKey.currentContext!.findRenderObject() as RenderRepaintBoundary;
    final image = await boundary.toImage();
    final byteData = await image.toByteData(format: ui.ImageByteFormat.png);
    if (byteData == null) return h.showToast("Failed to process image, please try again!");
    final pngBytes = byteData.buffer.asUint8List(byteData.offsetInBytes, byteData.lengthInBytes);
    if (kIsWeb) {
      Navigator.pop(context, [pngBytes]); // this is the bytes to be uploaded to server
    } else {
      final fileName = "${DateTime.now().millisecondsSinceEpoch}";
      final fileDir = (await getTemporaryDirectory()).path;
      final imgFile = File('$fileDir/$fileName.png');
      imgFile.writeAsBytes(pngBytes);
      Navigator.pop(context, [imgFile.path]);
    }
  } catch (e) {
    print(e);
  }
}
```

I ran it using canvaskit renderer:

`flutter run -d chrome --web-renderer canvaskit`

I suspect this is a bug in the blink (chrome) canvas or rendering engine.

**Screenshots:**

[![enter image description here][1]][1]
[![enter image description here][2]][2]

**Expected results:** 

.png image file with background image, texts, and lines

**Actual results:** 

background image is missing

[![enter image description here][3]][3]

<details>
<summary>Code sample</summary>

Here I've created sample repo for this issue: https://github.com/topex-psy/Drawie

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
[√] Flutter (Channel stable, 3.0.1, on Microsoft Windows [Version 10.0.19043.1706], locale en-ID)
    • Flutter version 3.0.1 at F:\Android\Flutter\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (3 weeks ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1    
    • DevTools version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at F:\Android\sdk
    • Platform android-32, build-tools 30.0.3
    • Java binary at: F:\Installer\Programming\Android Studio\android-studio-2021.2.1.11-windows\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 4.1)
    • Android Studio at F:\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Android Studio (version 2021.2)
    • Android Studio at F:\Installer\Programming\Android Studio\android-studio-2021.2.1.11-windows\android-studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] VS Code (version 1.68.0)
    • VS Code at C:\Users\topex\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.42.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19043.1706]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 102.0.5005.63
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 101.0.1210.39

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

</details>

  [1]: https://i.stack.imgur.com/Xvw3k.png
  [2]: https://i.stack.imgur.com/pe2G9.png
  [3]: https://i.stack.imgur.com/34GKl.png

**Comment by topex-psy** [comment] 2022-06-13 14:09
> Hi @topex-psy, thanks for filing the issue.
> 
> Kindly combine your code sample into a single runnable sample so that we can investigate this. As it is now, I'm not sure how it all fits together.
> 
> Also, do you see any errors in your console? If so, kindly share the errors.
> 
> Thank you

Okay, I'll try to make simple reproducible repo.

**Comment by topex-psy** [comment] 2022-06-13 17:07
here I've created sample repo for this issue: https://github.com/topex-psy/Drawie

run it with:
`flutter run -d chrome --web-renderer canvaskit`

**Comment by topex-psy** [comment] 2022-06-13 22:40
Here's the video for the issue:

https://user-images.githubusercontent.com/14989865/173459117-06865ae7-e77c-4347-879b-b72b8d2ad437.mp4

**Comment by danagbemava-nc** [comment] 2022-06-14 08:25
Hi @topex-psy, I believe this issue is similar to https://github.com/flutter/flutter/issues/103612 which is a duplicate of https://github.com/flutter/flutter/issues/94895. 

Kindly follow up in the linked issues for updates. 

Closing from here as a duplicate. 

If you disagree, kindly leave a comment below and I will reopen this. 

Thank you

**Closed by danagbemava-nc** 2022-06-14 08:25 UTC
Labels: in triage
