### ISSUE TITLE
Error running Gradle problem

### ISSUE THREAD

**Issue by sawravchy** [flutter/flutter#38199] opened 2019-08-11 16:37 UTC
When I try to run any of my flutters project I face this issue 
console:
```
* Error running Gradle:
ProcessException: Process "C:\Users\User\Downloads\flutter_app\android\gradlew.bat" exited abnormally:

> Configure project :app

Project evaluation failed including an error in afterEvaluate {}. Run with --stacktrace for details of the afterEvaluate {} error.

FAILURE: Build failed with an exception.
* Where:
Script 'C:\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 36

* What went wrong:
A problem occurred evaluating script.
> FlutterPlugin

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
  Command: C:\Users\User\Downloads\flutter_app\android\gradlew.bat app:properties

Finished with error: Please review your Gradle project setup in the android/ folder.
```

**Comment by sawravchy** [comment] 2019-08-11 17:11
![2019-08-11_21-37-55](https://user-images.githubusercontent.com/43489196/62837109-660c3f00-bc8d-11e9-890b-f94d53a84b8a.png)

**Comment by navaneeth7067** [comment] 2019-08-11 17:16
the same problem for me also.. Please, anyone, help to solve it

**Comment by htsnet** [comment] 2019-08-12 13:14
The same with me. Started today (problably) after IDE update .

**Comment by sawravchy** [comment] 2019-08-12 13:37
> The same with me. Started today (problably) after IDE update .

Are you using android studio?

**Comment by htsnet** [comment] 2019-08-12 16:24
> > The same with me. Started today (problably) after IDE update .
> 
> Are you using android studio?

Yes

**Comment by sawravchy** [comment] 2019-08-12 16:29
> > > The same with me. Started today (problably) after IDE update .
> > 
> > 
> > Are you using android studio?
> 
> Yes

Me also

**Comment by htsnet** [comment] 2019-08-12 16:32
I just made a test with VSCode, same issue:
PS C:\Users\hamil\Dropbox\Projetos\Flutter\DesafioFotografico\android\desafio_fotografico> flutter run
Launching lib\main.dart on GT I9505 in debug mode...
Initializing gradle...                                              1,0s
Resolving dependencies...
* Error running Gradle:
ProcessException: Process "C:\Users\hamil\Dropbox\Projetos\Flutter\DesafioFotografico\android\desafio_fotografico\android\gradlew.bat" exited abnormally:

  Command: C:\Users\hamil\Dropbox\Projetos\Flutter\DesafioFotografico\android\desafio_fotografico\android\gradlew.bat app:properties


Please review your Gradle project setup in the android/ folder.

**Comment by sawravchy** [comment] 2019-08-12 16:50
> I just made a test with VSCode, same issue:
> PS C:\Users\hamil\Dropbox\Projetos\Flutter\DesafioFotografico\android\desafio_fotografico> flutter run
> Launching lib\main.dart on GT I9505 in debug mode...
> Initializing gradle... 1,0s
> Resolving dependencies...
> 
> * Error running Gradle:
>   ProcessException: Process "C:\Users\hamil\Dropbox\Projetos\Flutter\DesafioFotografico\android\desafio_fotografico\android\gradlew.bat" exited abnormally:
>   Command: C:\Users\hamil\Dropbox\Projetos\Flutter\DesafioFotografico\android\desafio_fotografico\android\gradlew.bat app:properties
> 
> Please review your Gradle project setup in the android/ folder.

I had also faced the same issue on vs code 
![Islamic Life](https://user-images.githubusercontent.com/43489196/62882266-59521e80-bd53-11e9-8292-417f0d442d74.png)

**Comment by htsnet** [comment] 2019-08-12 17:57
> > I just made a test with VSCode, same issue:
> > PS C:\Users\hamil\Dropbox\Projetos\Flutter\DesafioFotografico\android\desafio_fotografico> flutter run
> > Launching lib\main.dart on GT I9505 in debug mode...
> > Initializing gradle... 1,0s
> > Resolving dependencies...
> > 
> > * Error running Gradle:
> >   ProcessException: Process "C:\Users\hamil\Dropbox\Projetos\Flutter\DesafioFotografico\android\desafio_fotografico\android\gradlew.bat" exited abnormally:
> >   Command: C:\Users\hamil\Dropbox\Projetos\Flutter\DesafioFotografico\android\desafio_fotografico\android\gradlew.bat app:properties
> > 
> > Please review your Gradle project setup in the android/ folder.
> 
> I had also faced the same issue on vs code
> ![Islamic Life](https://user-images.githubusercontent.com/43489196/62882266-59521e80-bd53-11e9-8292-417f0d442d74.png)

I returned my Android/app/build.gradle to the last condition (yesterday night) and now I can build and test (debug version). But, if I reinsert the signingConfigs to build as release, the issue returns.

**Comment by htsnet** [comment] 2019-08-14 20:11
I found the cause: my mistake. In the file app/build.gradle I forgot the lines below. Without these lines, the release build stops.  Now is OK!



def keystoreProperties = new Properties()
def keystorePropertiesFile = rootProject.file('key.properties')
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}

**Comment by sawravchy** [comment] 2019-08-15 13:04
But still, I am not able to run my projects

**Comment by BondarenkoStas** [comment] 2019-09-18 12:43
@sawravchy Please report if the issue is still relevant?

**Closed** 2019-09-18 13:57 UTC
Labels: waiting for customer response

**Comment by sawravchy** [comment] 2019-09-18 14:00
> @sawravchy Please report if the issue is still relevant?
It's ok now.

**Comment by htsnet** [comment] 2019-09-19 12:05
For me, it does not occurs anymore. Thanks

**Comment by canzion23** [comment] 2019-11-19 22:22
SOLVED: Delete '.gradle' folder in C:\Users***.gradle, connect to internet, rebuild project to download latest Gradle.

https://github.com/flutter/flutter/issues/34324

**Comment by Mahshadn** [comment] 2019-12-04 19:28
> SOLVED: Delete '.gradle' folder in C:\Users***.gradle, connect to internet, rebuild project to download latest Gradle.
> 
> #34324

I've deleted the .gradle folder but how to rebuild it?

**Comment by kiranjisac** [comment] 2020-01-28 14:44
hello I just cloned  to other device with latest versions and it throws error while running from it .what to do

**Comment by MagdaOsman** [comment] 2020-05-14 07:46
@sawravchy how so solve the issue??
