### ISSUE TITLE
After upgrade to 3.10.0 I get compile error: The parameter 'details' of the method....

### ISSUE THREAD

**Issue by DennisKragekjaer** [flutter/flutter#126519] opened 2023-05-11 09:45 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Im building for Android on device, but fails...see log output
I have tried everything that comes to mind, cache repair, clean ect, no luck.

### Actual results

I can not compile.

### Logs

<details>
<summary>Logs</summary>

```console

./../../../.pub-cache/hosted/pub.dev/macos_ui-1.12.2/lib/src/fields/text_field.dart:108:35: Error: The parameter 'details' of the method '_TextFieldSelectionGestureDetectorBuilder.onSingleTapUp' has type 'TapUpDetails', which does not match the corresponding type, 'TapDragUpDetails', in the overridden method, 'TextSelectionGestureDetectorBuilder.onSingleTapUp'.
 - 'TapUpDetails' is from 'package:flutter/src/gestures/tap.dart' ('../../../flutterSDK/flutter/packages/flutter/lib/src/gestures/tap.dart').
 - 'TapDragUpDetails' is from 'package:flutter/src/widgets/tap_and_drag_gestures.dart' ('../../../flutterSDK/flutter/packages/flutter/lib/src/widgets/tap_and_drag_gestures.dart').
Change to a supertype of 'TapDragUpDetails', or, for a covariant parameter, a subtype.
  void onSingleTapUp(TapUpDetails details) {
                                  ^
../../../flutterSDK/flutter/packages/flutter/lib/src/widgets/text_selection.dart:2161:8: Context: This is the overridden method ('onSingleTapUp').
  void onSingleTapUp(TapDragUpDetails details) {
       ^
../../../../.pub-cache/hosted/pub.dev/macos_ui-1.12.2/lib/src/fields/text_field.dart:130:42: Error: The parameter 'details' of the method '_TextFieldSelectionGestureDetectorBuilder.onDragSelectionEnd' has type 'DragEndDetails', which does not match the corresponding type, 'TapDragEndDetails', in the overridden method, 'TextSelectionGestureDetectorBuilder.onDragSelectionEnd'.
 - 'DragEndDetails' is from 'package:flutter/src/gestures/drag_details.dart' ('../../../flutterSDK/flutter/packages/flutter/lib/src/gestures/drag_details.dart').
 - 'TapDragEndDetails' is from 'package:flutter/src/widgets/tap_and_drag_gestures.dart' ('../../../flutterSDK/flutter/packages/flutter/lib/src/widgets/tap_and_drag_gestures.dart').
Change to a supertype of 'TapDragEndDetails', or, for a covariant parameter, a subtype.
  void onDragSelectionEnd(DragEndDetails details) {
                                         ^
../../../flutterSDK/flutter/packages/flutter/lib/src/widgets/text_selection.dart:2839:8: Context: This is the overridden method ('onDragSelectionEnd').
  void onDragSelectionEnd(TapDragEndDetails details) {
       ^
Target kernel_snapshot failed: Exception


FAILURE: Build failed with an exception.

* Where:
Script '/Users/denniskragekjaer/Documents/flutterSDK/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 1159

* What went wrong:
Execution failed for task ':app:compileFlutterBuildRelease'.
> Process 'command '/Users/denniskragekjaer/Documents/flutterSDK/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

```

</details>

### Flutter Doctor output

<details>
<summary>Doctor output</summary>

```console

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.0, on macOS 13.3.1 22E261 darwin-x64, locale en-DK)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.78.1)
[✓] Connected device (2 available)
[✓] Network resources

```

</details>

**Comment by danagbemava-nc** [comment] 2023-05-11 09:58
Hi @DennisKragekjaer, the issue is from the macos UI package. An issue has already been filed on their repo. See  https://github.com/macosui/macos_ui/issues/423

Kindly follow up there for updates. 

Closing from here. 

Thank you

**Closed by danagbemava-nc** 2023-05-11 09:58 UTC
Labels: in triage
