### ISSUE TITLE
SafeArea issue padding iphone 14 pro(i run code safearea on iphone 14 pro issue pad)

### ISSUE THREAD

**Issue by Fharhanamrin** [flutter/flutter#125794] opened 2023-05-01 13:46 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Scaffold(
        // appBar: ,
        body: SafeArea(
          child: Container(
            width: double.infinity,
            height: double.infinity,
            color: kBlueColor,
          ),
        ),
      ),

### Expected results

<img width="900" alt="Screenshot 2023-05-01 at 20 40 34" src="https://user-images.githubusercontent.com/27546921/235460078-9881e552-eb09-4812-8172-ad29e0283bac.png">

### Actual results

<img width="900" alt="Screenshot 2023-05-01 at 20 40 34" src="https://user-images.githubusercontent.com/27546921/235460166-bcaea2ea-3671-4fb9-9e3a-2fb6d8751c2e.png">

### Code sample

Scaffold(
        // appBar: ,
        body: SafeArea(
          child: Container(
            width: double.infinity,
            height: double.infinity,
            color: kBlueColor,
          ),
        ),
      ),

### Screenshots or Video

<img width="900" alt="Screenshot 2023-05-01 at 20 40 34" src="https://user-images.githubusercontent.com/27546921/235460238-60925dfc-ee9b-4b0d-9f36-1dd77fef35ad.png">

### Logs

Scaffold(
        // appBar: ,
        body: SafeArea(
          child: Container(
            width: double.infinity,
            height: double.infinity,
            color: kBlueColor,
          ),
        ),
      ),

### Flutter Doctor output

Scaffold(
        // appBar: ,
        body: SafeArea(
          child: Container(
            width: double.infinity,
            height: double.infinity,
            color: kBlueColor,
          ),
        ),
      ),

**Comment by Shivam-043** [comment] 2023-05-01 14:22
First, of All the flutter doctor file is written incorrect so please write it correct it.
And the SafeArea that you have included inside the scaffold . Please wrap the scaffold with SafeArea

**Comment by Fharhanamrin** [comment] 2023-05-01 15:05
it's the same, even though it's been placed outside the safe area

**Comment by danagbemava-nc** [comment] 2023-05-02 11:05
Hi @Fharhanamrin, please provide a complete minimal reproducible code sample so that we can investigate this issue. 

Below is what I see when I add a `SafeArea` on an iPhone 14 Pro Simulator. One is with `SafeArea(top: true, child: ...)` and the other is a plain `SafeArea`.

Please also provide the output of `flutter doctor -v`. 

Thank you

| SafeArea | SafeArea: top-true | 
| -- | -- | 
| <img src="https://user-images.githubusercontent.com/88313112/235649282-aaad131f-7c00-4d96-8292-34552325fd66.png" /> | <img src="https://user-images.githubusercontent.com/88313112/235649297-80bf8a68-cbf6-4e0e-8341-99e88c75be4b.png" /> |

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SafeArea(
        child: Container(
          color: Colors.purple,
          height: double.infinity,
          width: double.infinity,
        ),
      ),
    );
  }
}
```
</details>

**Comment by Fharhanamrin** [comment] 2023-05-02 11:30
thanks for the answer, it turns out to be an issue because of flutter_statusbarcolor_ns: ^0.5.0, is there any suggestion to change the status bar in flutter, thanks

**Comment by danagbemava-nc** [comment] 2023-05-03 06:32
Kindly see https://www.flutterbeads.com/change-status-bar-color-in-flutter/#:~:text=Inside%20the%20AppBarTheme%20%2C%20specify%20the,statusBarColor%20and%20set%20the%20color.

I'll be closing this since the original issue reported here was caused by a third-party package. 

Thank you

**Comment by danagbemava-nc** [comment] 2023-05-03 06:32
Kindly see https://www.flutterbeads.com/change-status-bar-color-in-flutter/#:~:text=Inside%20the%20AppBarTheme%20%2C%20specify%20the,statusBarColor%20and%20set%20the%20color.

I'll be closing this since the original issue reported here was caused by a third-party package. 

Thank you

**Closed by danagbemava-nc** 2023-05-03 06:32 UTC
Labels: in triage

**Comment by danagbemava-nc** [comment] 2023-05-03 06:33
Kindly see https://www.flutterbeads.com/change-status-bar-color-in-flutter/#:~:text=Inside%20the%20AppBarTheme%20%2C%20specify%20the,statusBarColor%20and%20set%20the%20color.

I'll be closing this since the original issue reported here was caused by a third-party package. 

Thank you
