### ISSUE TITLE
[tool_crash] FileSystemException: Cannot open file, OS Error: Read-only file system, errno = 30

### ISSUE THREAD

**Issue by ruthvikbheemidi** [flutter/flutter#129344] opened 2023-06-22 10:13 UTC
## Command
```
flutter run
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Cannot open file, OS Error: Read-only file system, errno = 30
```
#0      _File.throwIfError (dart:io/file_impl.dart:675:7)
#1      _File.openSync (dart:io/file_impl.dart:490:5)
#2      _File.writeAsBytesSync (dart:io/file_impl.dart:644:31)
#3      _File.writeAsStringSync (dart:io/file_impl.dart:668:5)
#4      ForwardingFile.writeAsStringSync (package:file/src/forwarding/forwarding_file.dart:150:16)
#5      ErrorHandlingFile.writeAsStringSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:267:22)
#6      _runSync (package:flutter_tools/src/base/error_handling_io.dart:590:14)
#7      ErrorHandlingFile.writeAsStringSync (package:flutter_tools/src/base/error_handling_io.dart:266:5)
#8      _writeFlutterPluginsListLegacy (package:flutter_tools/src/flutter_plugins.dart:262:15)
#9      refreshPluginsList (package:flutter_tools/src/flutter_plugins.dart:1083:30)
<asynchronous suspension>
#10     FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:355:5)
<asynchronous suspension>
#11     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1554:7)
<asynchronous suspension>
#12     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1336:27)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#14     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#15     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:296:9)
<asynchronous suspension>
#16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
```
```
[32m[✓][39m Flutter (Channel stable, 3.10.3, on Ubuntu 22.04.2 LTS 5.19.0-45-generic, locale en_IN)
    [32m•[39m Flutter version 3.10.3 on channel stable at /home/ruthvik/snap/flutter/common/flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision f92f44110e (3 weeks ago), 2023-06-01 18:17:33 -0500
    [32m•[39m Engine revision 2a3401c9bb
    [32m•[39m Dart version 3.0.3
    [32m•[39m DevTools version 2.23.1

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    [32m•[39m Android SDK at /home/ruthvik/Android/Sdk
    [32m•[39m Platform android-33, build-tools 33.0.2
    [32m•[39m Java binary at: /snap/android-studio/126/android-studio/jbr/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Chrome - develop for the web
    [32m•

**Comment by dam-ease** [comment] 2023-06-22 10:25
Closing this as a duplicate of https://github.com/flutter/flutter/issues/125775

**Closed** 2023-06-22 10:33 UTC
Labels: r: duplicate
