### ISSUE TITLE
[tool_crash] _CastError: (#0      CastIterator.current (dart:_internal/cast.dart:62:36))

### ISSUE THREAD

**Issue by sunilguptasg** [flutter/flutter#95325] opened 2021-12-15 10:23 UTC
## Command
```
flutter pub get
```

## Steps to Reproduce
1. forked flutter_auto_form to https://github.com/sunilguptasg/flutter_auto_form.git
2. added to pubspec.yaml as 
dependencies:
  flutter:
    sdk: flutter
  [package-name]:
    git:
      url: https://github.com/sunilguptasg/flutter_auto_form.git
3. flutter pub get

## Logs
_CastError: (#0      CastIterator.current (dart:_internal/cast.dart:62:36))
```
#0      CastIterator.current (dart:_internal/cast.dart:62:36)
#1      SetMixin.addAll (dart:collection/set.dart:57:45)
#2      new LinkedHashSet.of (dart:collection/linked_hash_set.dart:110:27)
#3      FlutterManifest.dependencies (package:flutter_tools/src/flutter_manifest.dart:82:43)
#4      findPlugins (package:flutter_tools/src/flutter_plugins.dart:86:24)
<asynchronous suspension>
#5      PackagesGetCommand.usageValues (package:flutter_tools/src/commands/packages.dart:105:36)
<asynchronous suspension>
#6      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1287:15)
<asynchronous suspension>
#7      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1140:27)
<asynchronous suspension>
#8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#9      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#10     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
<asynchronous suspension>
#11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
<asynchronous suspension>
#13     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
<asynchronous suspension>
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
```
```
[✓] Flutter (Channel stable, 2.8.0, on Microsoft Windows [Version 10.0.19043.1387], locale en-IN)
    • Flutter version 2.8.0 at C:\Users\sunil\Documents\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cf44000065 (7 days ago), 2021-12-08 14:06:50 -0800
    • Engine revision 40a99c5951
    • Dart version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0-rc5)
    • Android SDK at C:\Users\sunil\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0-rc5
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] Connected device (5 available)
    • M2006C3LI (mobile)       • EM7LNJQ88H5PUWWG • android-arm    • Android 10 (API 29)
    • Lenovo TB 8505F (mobile) • HA1D5J3K         • android-arm64  • Android 10 (API 29)
    • RMP2102 (mobile)         • ZD8TGQNVCYSCJVX8 • android-arm64  • Android 11 (API 30)
    • Chrome (web)             • chrome           • web-javascript • Google Chrome 96.0.4664.93
    • Edge (web)               • edge             • web-javascript • Microsoft Edge 96.0.1054.53

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 9b2d32b605630f28625709ebd9d78ab3016b2bf6
### Plugins
file_picker-4.2.7
flutter_plugin_android_lifecycle-2.0.5

**Comment by mamuseferha** [comment] 2021-12-15 10:45
Hi @sunilguptasg, this issue occurs because you did not give your git package a name in the pubspec.yaml file.

> [package-name]:

should be `flutter_auto_form`.

I'll go ahead and close this now as it is not a bug or feature request, if you disagree please write in the comments and I will reopen it. 

Thank you.

**Closed by mamuseferha** 2021-12-15 10:45 UTC
Labels: in triage
