### ISSUE TITLE
After android studio update [Bumblebee | 2021.1.1] iOS can no longer be run from IDE, resulting in CocoaPods plugin error

### ISSUE THREAD

**Issue by joelbrostrom** [flutter/flutter#97518] opened 2022-01-31 12:00 UTC
Both me and my colleague updated Android Studio to Bumblebee 2021.1.1 and got the same issue. 
I went from intl to Apple silicon, but she went from intl to intl.
We can build from the command line using `flutter build ipa` or `flutter run ios`.
Using `CMD+R` however cases the following cocoapods error.

```
Warning: CocoaPods not installed. Skipping pod install.
  CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
  Without CocoaPods, plugins will not work on iOS or macOS.
  For more info, see https://flutter.dev/platform-plugins
To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

CocoaPods not installed or not in valid state.
Error launching application on iPhone 13.
```

Android Studio version
```
Android Studio Bumblebee | 2021.1.1
Build #AI-211.7628.21.2111.8092744, built on January 19, 2022
Runtime version: 11.0.11+0-b60-7772763 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.1
GC: G1 Young Generation, G1 Old Generation
Memory: 2560M
Cores: 8
Registry: external.system.auto.import.disabled=true, debugger.watches.in.variables=false, ide.tooltip.initialDelay=704
Non-Bundled Plugins: com.ankit.mahadik.json.dart.class (2.12), com.github.chocovon.debug-variable-extractor (1.2.2), com.github.chocovon.debug-variable-sl (1.4.0), com.mnr.java.intellij.idea.plugin.base64helper (2.0.3), Dart (211.7798), com.localizely.flutter-intl (1.17.1-2020.3), com.atlassian.bitbucket.references (2021.1.195), org.jetbrains.kotlin (211-1.6.10-release-923-AS7442.40), io.flutter (63.2.2), de.mariushoefler.flutter_enhancement_suite (1.6.0), org.intellij.plugins.markdown (211.7142.37)
```

## Steps to Reproduce
1. Update Android studio to Bumblebee | 2021.1.1
2. Open iOS simulator
3. Run by pressing arrow or keyboard shortcut
4. You get an error
5. Run from terminal
6. You get no error

## Logs

<details>

```
```

[✓] Flutter (Channel stable, 2.8.1, on macOS 12.1 21C52 darwin-arm, locale en-SE)
    • Flutter version 2.8.1 at /Users/me/Library/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (7 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/me/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/me/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.32.0

[✓] Connected device (2 available)
    • iPhone 13 (mobile) • 70E75B43-0DE4-4099-92C0-6D57086CB4CB • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 97.0.4692.99

• No issues found!

```
```

</details>

**Comment by danagbemava-nc** [comment] 2022-01-31 12:20
Duplicate of #97251

**Closed by danagbemava-nc** 2022-01-31 12:20 UTC
Labels: in triage

**Comment by joelbrostrom** [comment] 2022-01-31 12:25
Thank you and sorry for causing extra work for you.
You all do an amazing job 👏
