### ISSUE TITLE
[image_picker] pickImage method doesn't return anything and not completing the future

### ISSUE THREAD

**Issue by yahu1031** [flutter/flutter#105919] opened 2022-06-13 20:18 UTC
## Steps to Reproduce

1. Install `image_picker: ^0.8.5+3`
2. call `pickImage()`

**Expected results:** 
I expect it to print path.

**Actual results:** 
Doesn't return anything and just holds there(doesn't complete the future)

<details>
<summary>Code sample</summary>

```dart
print('picking image');
ImagePicker _picker = ImagePicker();
XFile? image = await _picker.pickImage(source: ImageSource.gallery);
print('Image picked');
if (image != null) {
  print(image.path);
} else {
  print('Image is null');
}
```

</details>

<details>
  <summary>Logs</summary>

`flutter run -v` logs file :

[flutter_run_v.log](https://github.com/flutter/flutter/files/8894344/l.log)

`flutter analyze`

```
minnu@Minnus-Mac buzz % flutter analyze
Analyzing buzz...                                                       

   info • Avoid `print` calls in production code • lib/app/screens/onboard/qr_screen.dart:117:27 • avoid_print

1 issue found. (ran in 2.7s)
```

`flutter analyze`

```
minnu@Minnus-Mac buzz % flutter doctor --verbose
[✓] Flutter (Channel stable, 3.0.2, on macOS 12.4 21F79 darwin-arm, locale en-IN)
    • Flutter version 3.0.2 at /Users/minnu/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cd41fdd495 (5 days ago), 2022-06-08 09:52:13 -0700
    • Engine revision f15f824b57
    • Dart version 2.17.3
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/minnu/Library/Android/sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.68.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.42.0

[✓] Connected device (3 available)
    • iPhone 12 (mobile) • 40395EC4-EEBA-434B-9454-3194F957092A • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-5 (simulator)
    • macOS (desktop)    • macos                                • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 102.0.5005.61

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by maheshmnj** [comment] 2022-06-14 07:52
Hi @yahu1031, What platform is this issue on? Also, do you mean `pickImage` does not return anything? I did verify on a android emulator and it seems to work fine. What target platform is this issue on? Do you see any error or exception when this occurs?
<img src="https://user-images.githubusercontent.com/31410839/173523448-7bc85268-c21a-4e21-b595-da74cfc43ff6.png" width ="300"> 

<details>
<summary>code sample</summary>

```dart
import 'dart:io';
import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: const MyHomePage(title: 'Flutter ImagePicker Demo'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  Widget imageBuilder(File file, int index) {
    if (file != null && file.path.isNotEmpty) {
      return Image.file(
        File(
          file.path,
        ),
        fit: BoxFit.cover,
      );
    } else {
      return imagePlaceHolder(index);
    }
  }

  Future<XFile?> pickImage(ImageSource source) async {
    final image = await _picker.pickImage(
        source: source,
        maxWidth: 800,
        maxHeight: 800,
        preferredCameraDevice: CameraDevice.rear);
    return image;
  }

  Widget imagePlaceHolder(int index) {
    return Container(
// padding: EdgeInsets.only(right),
      alignment: Alignment.center,
      decoration: BoxDecoration(
        border: Border(
            right: index % 2 == 0 ? BorderSide() : BorderSide.none,
            bottom: BorderSide()),
      ),
      child: Icon(Icons.add_a_photo),
    );
  }

  final _picker = ImagePicker();

  List<File> images = [];

  @override
  void initState() {
// TODO: implement initState
    super.initState();
    List.generate(4, (x) => images.add(File('')));
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Expanded(
              child: GridView.builder(
                itemCount: 4,
                gridDelegate: const SliverGridDelegateWithFixedCrossAxisCount(
                    crossAxisCount: 2),
                itemBuilder: (context, index) => GestureDetector(
                    onTap: () async {
                      final image = await pickImage(index % 2 == 0
                          ? ImageSource.camera
                          : ImageSource.gallery);
                      setState(() {
                        images[index] = File(image!.path);
                      });
                    },
                    child: imageBuilder(images[index], index)),
              ),
            ),
          ],
        ),
      ),
    );
  }
}

```
</details> 

<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel stable, 3.0.2, on macOS 12.4 21F79 darwin-arm, locale en-IN)
    • Flutter version 3.0.2 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cd41fdd495 (5 days ago), 2022-06-08 09:52:13 -0700
    • Engine revision f15f824b57
    • Dart version 2.17.3
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-32, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.67.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.42.0

[✓] Connected device (3 available)
    • sdk gphone arm64 (mobile) • emulator-5554 • android-arm64  • Android 11 (API 30) (emulator)
    • macOS (desktop)           • macos         • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)              • chrome        • web-javascript • Google Chrome 102.0.5005.61

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by yahu1031** [comment] 2022-06-14 07:54
@maheshmnj No error, no verbose logs, nothing. 
Platform: iOS 15.5 - iPhone 12

**Comment by maheshmnj** [comment] 2022-06-14 11:54
Thanks for the info @yahu1031, Please ensure you have added the relevant keys as mentioned in the [docs](https://pub.dev/packages/image_picker)

> Add the following keys to your Info.plist file, located in <project root>/ios/Runner/Info.plist:

**Comment by yahu1031** [comment] 2022-06-14 11:57
Yes, I did. And FYI, I'm suspecting the `fluttertoast` package is causing this in my case. When I create a new project I repeat the process without that package, and I get the expected output. Can you please cross-check it and if it is the case, please give us a fix for it.

**Comment by maheshmnj** [comment] 2022-06-14 13:11
Thanks for the info @yahu1031, Are you seeing the issue on a simulator ? I verified on a simulator and I am hitting this issue https://github.com/flutter/flutter/issues/82602 which seems to reproduce on the mac m1 simulator. But the app is never stuck for me, It just doesn't return anything. 


```
Launching lib/main.dart on iPhone 12 Pro in debug mode...
Xcode build done.                                            7.6s
Connecting to VM Service at ws://127.0.0.1:58117/OjxCTt77AzQ=/ws
[VERBOSE-2:ui_dart_state.cc(198)] Unhandled Exception: PlatformException(multiple_request, Cancelled by a second request, null, null)
#0      ImagePickerApi.pickImage
<asynchronous suspension>
#1      ImagePickerIOS.getImage
<asynchronous suspension>
#2      _MyHomePageState.pickImage
<asynchronous suspension>
#3      _MyHomePageState.build.<anonymous closure>.<anonymous closure>
<asynchronous suspension>
``` 

> I'm suspecting the fluttertoast package is causing this in my case. 

Do you mean if you remove fluttertoast package it works fine?

**Comment by maheshmnj** [comment] 2022-06-15 06:25
Thanks for the update, @yahu1031 But it is unclear to me what could be happening on your side, The [verbose logs](https://github.com/flutter/flutter/issues/105919#issue-1269908146) in the original report doesn't show any error or any  warnings to make anything out of it. Labeling this issue for further investigation from the team.

**Comment by yahu1031** [comment] 2022-06-15 19:20
Finally, I tried and `fluttertoast` is the culprit. Here are the samples and logs

Video: 

https://user-images.githubusercontent.com/35523357/173907203-63ff4a98-0216-4ea9-b54b-cd35cea6be00.mp4

Logs: [with_fluttertoast.log](https://github.com/flutter/flutter/files/8912396/with.log)

Video: 

https://user-images.githubusercontent.com/35523357/173907231-b602cb52-755a-430c-8ac7-c8fbb6541797.mp4

Logs: [without_fluttertoast.log](https://github.com/flutter/flutter/files/8912397/without.log)

**Comment by maheshmnj** [comment] 2022-06-16 06:18
@yahu1031  Could you please recheck the video links, The video doesn't seem to play.

**Comment by yahu1031** [comment] 2022-06-16 06:19
You need to download them in order to play. Sorry idk why it was like that.

**Comment by maheshmnj** [comment] 2022-06-16 09:55
@yahu1031 The preview failed because you do not have line breaks around the link, But clicking the link doesn;t download or play either.

**Comment by yahu1031** [comment] 2022-06-16 09:58
Preview doesn't work so i did it. Open the link an save the file. Then you can play. Anyhow I will update.

**Comment by maheshmnj** [comment] 2022-06-16 12:04
The videos you shared do not load in chrome, Anyways I managed to play it in safari.

> Logs: [with_fluttertoast.log](https://github.com/flutter/flutter/files/8912396/with.log)

from your first logs with `flutter_toast` seems to throw the following exception which is same as https://github.com/flutter/flutter/issues/82602 as [mentioned above ](https://github.com/flutter/flutter/issues/105919#issuecomment-1156038978)

> 127.0.0.1:58757/reP7tjNSmIs=/
[+25477 ms] [VERBOSE-2:ui_dart_state.cc(198)] Unhandled Exception: PlatformException(multiple_request, Cancelled by a second request, null, null)
                     #0      ImagePickerApi.pickImage (package:image_picker_ios/src/messages.g.dart:133:7)
                     <asynchronous suspension>
                     #1      ImagePickerIOS.getImage (package:image_picker_ios/image_picker_ios.dart:168:26)
                     <asynchronous suspension>
                     #2      _MyHomePageState._addImage (package:flutter_application_1/main.dart:40:26)
                     <asynchronous suspension>


Closing as duplicate of the above linked issue.

**Closed by maheshmnj** 2022-06-16 12:04 UTC
Labels: platform-ios, plugin, p: first party, p: image_picker

**Comment by yahu1031** [comment] 2022-06-16 12:41
I don't think it is duplicate. That exception is thrown because I tried second time before the future completes. Maybe that comes under another issue.
