### ISSUE TITLE
[Firebase Analytics] Are "screen" and "route" the same?

### ISSUE THREAD

**Issue by giorgio79** [flutter/flutter#89126] opened 2021-08-29 11:28 UTC
I installed Firebase Analytics https://pub.dev/packages/firebase_analytics
but only "screen_view" events were recorded, and when I tried to drill, title was not set.

I think the documentation needs to make it clear that for the package to work out of the box, named routes need to be used.
Others seem to be confused as well https://stackoverflow.com/questions/55830575/how-do-i-track-flutter-screens-in-firebase-analytics
![image](https://user-images.githubusercontent.com/283347/131248851-8cb34d95-8f2e-4bdf-960f-cd1c25c2443f.png)

![image](https://user-images.githubusercontent.com/283347/131248840-6f74dc2d-ac3f-4bed-94c3-e391a47fb09f.png)

## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by iapicca** [comment] 2021-08-29 17:46
@giorgio79 
you may want to open the issue in the dedicated github 
https://github.com/FirebaseExtended/flutterfire/issues

**Comment by TahaTesser** [comment] 2021-08-30 07:23
Hi @giorgio79 From what I can see, the issue is related to a FlutterFire plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  providing your `flutter doctor -v`, your `pubspec.yaml`, a minimal reproducible code sample that does not use 3rd party plugins, your complete `flutter run -v` logs running the minimal code sample 
and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-08-30 07:23 UTC
Labels: in triage

**Comment by giorgio79** [comment] 2021-08-30 07:30
Thanks Guys.

I think Firebase Analytics shows the symptom of a deeper issue that is Flutter uses the terms "route", "page" and "screen" interchangeably probably due to iOS and Android using these terms differently. This page attempts an explanation https://flutter.dev/docs/cookbook/navigation/navigation-basics
We might need some hardening of the naming convention.
