### ISSUE TITLE
 BlocBuilder not getting called after an update, pageview still displays old data

### ISSUE THREAD

**Issue by prakash6491** [flutter/flutter#81824] opened 2021-05-04 11:57 UTC
In my application am using pull  to refresh .after complete pull to refresh I called bloc method. Event, State, API everything working fine. but old data  only showing new data not update.

**Comment by TahaTesser** [comment] 2021-05-04 13:08
Hi @prakash6491 
From what I can see, the issue is related to a 3rd party plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/felangel/bloc/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`, a minimal reproducible code sample that does not use 3rd party plugins, your complete `flutter run -v` logs running the minimal code sample 
and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-05-04 13:08 UTC
Labels: in triage
