### ISSUE TITLE
Why does my text not wrap?

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#4128] opened 2016-05-23 22:19 UTC
Sometimes it can be difficult to figure out why a Text widget overflows rather than wrapping. For example: #4115.

Here's a simple app that demonstrates the problem:

```
import 'package:flutter/material.dart';

class DemoApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      home: new Center(
        child: new Row(
          children: <Widget>[
            new Container(
              decoration: new BoxDecoration(backgroundColor: const Color(0xFF0000FF)),
              child: new Text("Why doesn't this text wrap? There's plenty of vertical space...")
            )
          ]
        )
      )
    );
  }
}

void main() {
  runApp(new DemoApp());
}
```

The text doesn't wrap because the Row only constrains the width of children that have been wrapped in a Flexible widget. In this case the unconstrained width of the Container with the Text child is greater than the available width. So it just overflows the Row.

If this turns out to be a common failure mode, we might try and detect it and generate a suggested fix. For example we might notice when a Row overflows and the sum of the children's minimum intrinsic widths would not overflow.

![no_wrap](https://cloud.githubusercontent.com/assets/1377460/15486330/a230f210-20f9-11e6-94d8-0ee0f8f5793c.png)

**Comment by Hixie** [comment] 2016-05-23 22:29
We already notice when it overflows. The problem is where to put the information regarding what to do about it.

One idea might be in the debugDumpRenderTree() dump, but would anyone look there?

**Comment by HansMuller** [comment] 2016-05-23 23:09
I'm sure there's a better "best" way to do this, like an interactive visual tool for debugging layouts. 

Short of that, maybe a command-line tool like `flutter debug_overflows`?  Or a `flutter dump` that did debugDumpRenderTree() and printed whatever suggestions we came up with?

**Comment by Hixie** [comment] 2017-01-30 03:40
I'm going to close this because it's not really actionable in its current state, but we should definitely keep thinking about this (as we do anyway) and if we come up with a concrete idea for doing this, file a new bug to track it.

**Closed by Hixie** 2017-01-30 03:40 UTC
Labels: dev: tool, new feature

**Comment by yathit** [comment] 2017-12-30 05:57
Faced the same issue for not wrapping Text in `Row` Widget. Wasting a lot of time, thinking somewhere is wrong. It is hard to realize Row does not support text wrapping.

**Comment by Hixie** [comment] 2018-01-02 23:04
@yathit Can you talk about what exactly it would mean for Row to support wrapping `Text`? For example, consider a `Row` with two children, both of which are `Text` widgets with a lot of text. How should it render? (These are not rhetorical questions, I honestly don't know the answers and that's what has been stopping us from fixing this.)

**Comment by yathit** [comment] 2018-01-03 02:37
I also do not know. 

I have solved by using fixed width widgets except the last one with Expended. The fixed widget size needed to use `MediaQueryData`. Text overflow work fine now.

**Comment by stephensamonte** [comment] 2018-01-03 22:28
You have to wrap Column in a flexible. Without flexible the column's width is not constrained to the max view in the display.
Below is the proper implamentation for textwrapping for the code above.  

```
return new MaterialApp(
        home: new Center(
            child: new Row(children: <Widget>[
              new Flexible(
                child: new Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    new Text(
                        "Why doesn't this text wrap? There's plenty of vertical space...")
                  ],
                ),
              ),
            ])
        )
    );
```

**Comment by mickykebe** [comment] 2018-09-07 06:38
Text made to wrap with maxLines property in an Expanded widget within a Column overflows.

`import 'package:flutter/material.dart';

void main() {
  runApp(App());
}

class App extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: Text("Overflow"),
        ),
        body: Center(
          child: Container(
              width: 200.0,
              height: 250.0,
              child: Card(
                  child: Column(children: <Widget>[
                Image.asset(
                  "assets/bereket.jpg",
                  width: double.infinity,
                  fit: BoxFit.cover,
                ),
                Expanded(
                    child: Container(
                        padding: EdgeInsets.all(8.0),
                        child: (Column(
                          children: [
                            Text(
                                "በረከት ስምኦን፡ «ወይዘሮ አና ጎሜዝ፤ እርስዎ አያገባዎትም! አርፈው ይቀመጡ በልልኝ»",
                                maxLines: 2,
                                style: Theme.of(context)
                                    .primaryTextTheme
                                    .subhead
                                    .copyWith(
                                      color: Colors.black,
                                    ),
                                overflow: TextOverflow.ellipsis),
                            Expanded(
                                child: Container(
                                    decoration: BoxDecoration(
                                      border: Border.all(
                                          color: Colors.green, width: 2.0),
                                    ),
                                    child: Text(
                                      """ባለፉት ሁለት አስርት ዓመታት በኢትዮጵያ ፖለቲካ ከፍተኛ ተጽእኖ ፈጣሪ የነበሩት አቶ በረከት ስምኦን በቅርቡ ከብአዴን ማእከላዊ ኮሚቴ አባልነት መታገዳቸው ይታወሳል።

አቶ በርከት የብአዴን ውሳኔን በተመለከተ እና የወደፊት የፖለቲካ ህይወታቸው ምን ሊሆን እንደሚችል ለቢቢሲ አጋርተዋል።""",
                                      maxLines: 10,
                                      style: Theme.of(context)
                                          .primaryTextTheme
                                          .caption
                                          .copyWith(color: Colors.black),
                                      overflow: TextOverflow.ellipsis,
                                    ))),
                            Row(
                              crossAxisAlignment: CrossAxisAlignment.center,
                              children: <Widget>[
                                Container(
                                  width: 20.0,
                                  height: 20.0,
                                  child: Image.asset("assets/bbc.png"),
                                ),
                                SizedBox(width: 8.0),
                                Text('ቢቢሲ - ከሁለት ሰአት በፊት',
                                    style: Theme.of(context)
                                        .textTheme
                                        .caption
                                        .copyWith(fontSize: 10.0))
                              ],
                            )
                          ],
                        ))))
              ]))),
        ),
      ),
    );
  }
}`

![photo_2018-09-06_17-16-25](https://user-images.githubusercontent.com/3784089/45202437-b14dee80-b281-11e8-91b1-95c001e86f95.jpg)

**Comment by rravithejareddy** [comment] 2018-12-19 08:36
With use of expand text is wrapping, but i am not able to use Expand widget inside SingleChildScrollView widget, these all are killing time.

**Comment by pedromassango** [comment] 2018-12-27 14:57
This thing should be more simple as in Native Android Development. It is very hard to always remember to use Flexible widget.

**Comment by rravithejareddy** [comment] 2018-12-27 15:46
I solved it by using mediaquery instead of expand.

**Comment by kapil708** [comment] 2019-02-06 13:19
I Do it by 
SizedBox(
                            width: 200,
                            child: Text("............ ............... ................. .................... ................",
                                style: TextStyle(color: Colors.white,fontSize: 15.0,fontWeight: FontWeight.w600)),
                          )

**Comment by matthewlloyd** [comment] 2019-05-15 01:27
Just ran into this, mildly frustrating. It would be really nice if this was better documented - it definitely isn't intuitive that to get text to wrap inside a Column, you need to constrain it by wrapping it in something that is called a Flexible. If anything, intuition would suggest that you'd use a Flexible to constrain the text less, not more!

This might be a good place for the information: https://docs.flutter.io/flutter/widgets/Column-class.html

Alternatively it would be really nice to have a central Troubleshooting page in the official documentation that covers the (very many) common issues like these.

Or the widgets could be redesigned so that unconstrained overflow of widgets is not the default behavior. Surely the default should be tighter constraints and more wrapping in almost every case? It worked for HTML.

**Comment by FilipeOS** [comment] 2019-05-17 14:13
> Just ran into this, mildly frustrating. It would be really nice if this was better documented - it definitely isn't intuitive that to get text to wrap inside a Column, you need to constrain it by wrapping it in something that is called a Flexible. If anything, intuition would suggest that you'd use a Flexible to constrain the text less, not more!
> 
> This might be a good place for the information: https://docs.flutter.io/flutter/widgets/Column-class.html
> 
> Alternatively it would be really nice to have a central Troubleshooting page in the official documentation that covers the (very many) common issues like these.
> 
> Or the widgets could be redesigned so that unconstrained overflow of widgets is not the default behavior. Surely the default should be tighter constraints and more wrapping in almost every case? It worked for HTML.

Can you please share what was your solution? right now I have a Container(with all my style and decoration) and inside it a Text. I tried placing Flexible everywhere but something is wrong

**Comment by zolzaya** [comment] 2019-05-20 06:02
I have a same issue it's really killing my time lol :(

**Comment by FilipeOS** [comment] 2019-05-20 11:31
> I have a same issue it's really killing my time lol :(

Don't cry anymore! 💃 
`                      Flexible(
                        child: Container(
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.end,
                          children: <Widget>[
                            Text(
                              "BIG BLA BLA BLA BLA",
                              style:  TextStyle(color: Colors.white),
                            ),
                            Container(
                              child: Text(
                                "22:30",
                                style: TextStyle(
                                    color: Colors.grey[300], fontSize: 12.0),
                              ),
                            )
                          ],
                        ),`

**Comment by pedromassango** [comment] 2019-05-20 18:44
> > I have a same issue it's really killing my time lol :(
> 
> Don't cry anymore! 💃
> `Flexible( child: Container( child: Column( crossAxisAlignment: CrossAxisAlignment.end, children: <Widget>[ Text( "BIG BLA BLA BLA BLA", style: TextStyle(color: Colors.white), ), Container( child: Text( "22:30", style: TextStyle( color: Colors.grey[300], fontSize: 12.0), ), ) ], ),`
> (I tried to format this code, I give up)
> 
> This code is inside a Container -> Column -> Row in my case

Maybe you want to format the code!

**Comment by zolzaya** [comment] 2019-05-21 02:17
@FilipeOS , @pedromassango  thank you guys :)

**Comment by davidmarinangeli** [comment] 2019-05-31 16:26
Also for me 

> > I have a same issue it's really killing my time lol :(
> 
> Don't cry anymore! 💃
> 
> ```dart
> Flexible(
>   child: Container(
>     child: Column(
>       crossAxisAlignment: CrossAxisAlignment.end,
>       children: <Widget>[
>         Text(
>           "BIG BLA BLA BLA BLA",
>           style:  TextStyle(color: Colors.white),
>         ),
>         Container(
>           child: Text(
>             "22:30",
>             style: TextStyle(color: Colors.grey[300], fontSize: 12.0),
>           ),
>         ),
>       ],
>     ),
>   ),
> ),
> ```
> 
> (I tried to format this code, I give up)
> 
> This code is inside a Container -> Column -> Row in my case

This works for me! Is this something they have to fix or using `Flexible` is the right way to do it?

**Comment by ronak197** [comment] 2019-11-15 20:22
`Flexible(
                            child: Column(
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: <Widget>[
                                Container(
                                  padding: EdgeInsets.only(left: 10.0),
                                  child: Wrap(
                                    children: <Widget>[
                                      Text(contactName, style: TextStyle(color: Color(0xff3A3131), fontSize: 17.0), softWrap: false, maxLines: 1, textAlign: TextAlign.left, overflow: TextOverflow.ellipsis,)
                                    ],
                                  ),
                                ),
                                Container(
                                  padding: EdgeInsets.only(left: 10.0),
                                  child: Wrap(
                                    children: <Widget>[
                                      Text(contactPhoneNumber, style: TextStyle(color: Color(0xff3A3131), fontSize: 13.0),textAlign: TextAlign.left, maxLines: 1, overflow: TextOverflow.ellipsis,)
                                    ],
                                  ),
                                ),
                              ],
                            ),
                          ),`

This is working for me. For long text in a row of a column, you can simply wrap the column with Flexible widget and wrap the Text in Wrap widget to avoid overflow.

**Comment by jcrisanto** [comment] 2020-02-04 21:36
set softwrap to true inside of Text()

**Comment by egorbelibov** [comment] 2020-02-10 20:50
Another way to automatically wrap a `Text` widget that is inside a `Row` is to **wrap** `Text` with an `Expanded` widget, as following:
```
Row(
  children: [
    Image.asset('assets/icons/my_icon.png'),
    Expanded(child: Text('This is text that is going to wrap itself')),
  ],
),
```

**Comment by alipm** [comment] 2020-03-18 08:09
> d width w

Hey thanks, it worked for me

**Comment by nwainwri** [comment] 2020-03-27 22:42
Thank you @egorbelibov for that; worked like a charm!
