### ISSUE TITLE
worst_frame_rasterizer_time_millis regressed into out-of-budget

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#27558] opened 2019-02-05 19:14 UTC
https://github.com/flutter/engine/pull/7688, which rolled the skia commits below, improved `flutter_gallery__transition_perf average_frame_rasterizer_time_millis`, which is great, but regressed `tiles_scroll_perf__timeline_summary worst_frame_rasterizer_time_millis` significantly, pushing the worst frame from in-budget to out-of-budget.

* 2019-02-04 [brianosman@google.com](mailto:brianosman@google.com) Add support for MSVC run-time checks (and control flow guard)
* 2019-02-04 [recipe-roller@chromium.org](mailto:recipe-roller@chromium.org) Roll recipe dependencies (trivial).
* 2019-02-04 [halcanary@google.com](mailto:halcanary@google.com) SkPDF to use aliased em bounds.
* 2019-02-04 [skia-autoroll@skia-public.iam.gserviceaccount.com](mailto:skia-autoroll@skia-public.iam.gserviceaccount.com) Roll third_party/externals/swiftshader 3f5a479280cc..612345523a8d (2 commits)
* 2019-02-04 [reed@google.com](mailto:reed@google.com) templatize drawString
* 2019-02-04 [egdaniel@google.com](mailto:egdaniel@google.com) Minor clean ups to vulkan hardware buffer test.
* 2019-02-04 [robertphillips@google.com](mailto:robertphillips@google.com) Move GrContextOptions to GrContext_Base and make GrContextThreadSafeProxy be derived from GrContext_Base
* 2019-02-04 [reed@google.com](mailto:reed@google.com) remove metadata from canvas
* 2019-01-31 [herb@google.com](mailto:herb@google.com) Benchmark for charToGlyph

**Comment by jason-simmons** [comment] 2019-02-05 20:05
Bisected this.  Looks like it's related to a change in raster cache policy (https://github.com/flutter/engine/commit/2f18c32862bc7a9092850c43a21c5282a95edf00)

**Comment by liyuqian** [comment] 2019-02-05 23:44
https://github.com/flutter/engine/pull/7701 will be merged and rolled into framework in a single-commit engine roll once our current engine roll clears.

**Comment by liyuqian** [comment] 2019-02-06 01:10
I've confirmed that https://github.com/flutter/flutter/pull/27522 (https://github.com/flutter/engine/commit/2f18c32862bc7a9092850c43a21c5282a95edf00) is the culprit.

However, it seems that when flutter framework tries to download the engine artifacts for https://github.com/flutter/flutter/pull/27521 (with engine version fde59006da24), it actually downloads artifacts of engine version at least 2f18c3286. That's why all the performance benchmarks (tiles_scroll, complex_layout_scroll, flutter_gallery_transition_perf) start to change on https://github.com/flutter/flutter/pull/27521 instead of https://github.com/flutter/flutter/pull/27522 

I did some experiments locally. Directly running `flutter drive --profile -t ...` without specifying --local-engine has a very different result than running `flutter drive --profile --local-engine=android_profile -t ...` even if the local engine version fde59006da24 matches bin/internal/engine.version fde59006da24.

**Comment by Hixie** [comment] 2019-02-06 23:51
fix landed in framework in https://github.com/flutter/flutter/pull/27614

**Closed** 2019-02-07 20:25 UTC
Labels: dependency: skia, engine, severe: performance, severe: regression, waiting for PR to land (fixed), ⚠ TODAY
