### ISSUE TITLE
Request to Dart VM Service timed out: _flutter.listViews({})

### ISSUE THREAD

**Issue by filiph** [flutter/flutter#24634] opened 2018-11-21 22:53 UTC
## Steps to Reproduce

This is intermittent, but happens quite frequently on my new machine. When performing a hot reload, sometimes the hot reload takes forever to finish, and the app on the emulator just hangs.

1. Create new project in Android Studio
2. Replace contents of `lib/main.dart` with https://gist.github.com/filiph/e46084361c3c9c270695c760aa06d30d
3. Run in iOS Simulator (iPhone X)
4. Uncomment [line 46](https://gist.github.com/filiph/e46084361c3c9c270695c760aa06d30d#file-main-dart-L46) and save (performs hot reload automatically)

Hot reload (sometimes?) hangs for a minute...

<img width="1663" alt="screen shot 2018-11-21 at 1 31 17 pm" src="https://user-images.githubusercontent.com/919717/48872101-882afd80-ed9c-11e8-9d3a-1db72e17619b.png">

... and then fails. The app is unresponsive. I have to stop and re-`flutter run`.

This happened several times during a Flutter Boring Show shoot today, with @Hixie.

## Logs

```
Performing hot reload...
[+46129 ms] Refreshing active FlutterViews before reloading.
[        ] Sending to VM service: _flutter.listViews({})
[   +1 ms] Result: {type: FlutterViewList, views: [{type: FlutterView, id: _flutterView/0x7fd438806eb8, isolate: {type: @Isolate, fixedId: true, id: isolates/54694712, name: main.dart$main.dart-54694712, number: 54694712}}]}
Syncing files to device iPhone X...
[ +269 ms] DevFS: Starting sync from LocalDirectory: '/Users/filiph/dev/sliver_fbs'
[        ] Scanning project files
[        ] Scanning package files
[  +44 ms] Scanning asset files
[        ] Scanning for deleted files
[   +2 ms] Compiling dart to kernel with 1 updated files
[  +43 ms] Updating files
[   +3 ms] DevFS: Sync finished
[        ] Synced 0.0MB.
[        ] Sending to VM service: _reloadSources({pause: true, rootLibUri: file:///Users/filiph/Library/Developer/CoreSimulator/Devices/020C1218-499F-4C9F-A288-5B37E321BF7D/data/Containers/Data/Application/C2689256-1A0E-448E-BE56-B4C48B8E7404/tmp/sliver_fbsYGuiEz/sliver_fbs/lib/main.dart.incremental.dill, packagesUri: file:///Users/filiph/Library/Developer/CoreSimulator/Devices/020C1218-499F-4C9F-A288-5B37E321BF7D/data/Containers/Data/Application/C2689256-1A0E-448E-BE56-B4C48B8E7404/tmp/sliver_fbsYGuiEz/sliver_fbs/.packages, isolateId: isolates/54694712})
[  +31 ms] Result: {type: ReloadReport, success: true, details: {savedLibraryCount: 419, loadedLibraryCount: 1, finalLibraryCount: 420, shapeChangeMappings: []}}
[        ] reloaded 1 of 420 libraries
[        ] Sending reload events to iPhone X
[        ] Sending reload event to "main.dart$main.dart-54694712"
[        ] Sending to VM service: getIsolate({isolateId: isolates/54694712})
[   +5 ms] Result: {type: Isolate, fixedId: true, id: isolates/54694712, name: main.dart:main.dart(), number: 54694712, _originNumber: 54694712, startTime: 1542834567976, _heaps: {new: {type: HeapSpace, name: new, vmName: Scavenger, collections: 389, avgCollectionPe...
[   +1 ms] Sending to VM service: _flutter.listViews({})
[+60007 ms] Request to Dart VM Service timed out: _flutter.listViews({})
```

### flutter analyze

```
$ flutter analyze
Analyzing sliver_fbs...                                          
No issues found! (ran in 1.2s)
```

### flutter doctor -v

```
[✓] Flutter (Channel beta, v0.11.3, on Mac OS X 10.14.1 18B75, locale en-US)
    • Flutter version 0.11.3 at /Users/filiph/dev/flutter
    • Framework revision 72bf075e8d (12 days ago), 2018-11-09 20:36:17 -0800
    • Engine revision 5646e86a6f
    • Dart version 2.1.0 (build 2.1.0-dev.9.3 9c07fb64c4)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/filiph/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[!] iOS toolchain - develop for iOS devices (Xcode 10.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.0, Build version 10A255
    • ios-deploy 2.0.0
    ✗ CocoaPods installed but not initialized.
        CocoaPods is used to retrieve the iOS platform side's plugin code that responds to your plugin
        usage on the Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work on iOS.
        For more info, see https://flutter.io/platform-plugins
      To initialize CocoaPods, run:
        pod setup
      once to finalize CocoaPods' installation.

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 30.0.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] Connected device (2 available)
    • Filip’s iPhone • eba005cd7bcf6a288a2af55721dfc16873335a15 • ios • iOS 12.1
    • iPhone X       • 020C1218-499F-4C9F-A288-5B37E321BF7D     • ios • iOS 12.0 (simulator)

! Doctor found issues in 1 category.

```

**Comment by filiph** [comment] 2018-11-21 23:06
Aaah, I just noticed the `✗` in `flutter doctor`, and fixed it (by running `pod setup`). Now I can't reproduce this anymore.

I'll reopen the issue if I see this again, but it seems like the problem was between the keyboard and the chair. I just didn't finish Flutter's setup correctly, and then failed to run `flutter doctor` when I hit issues.

**Comment by Hixie** [comment] 2018-11-21 23:10
Cocoapods not being installed shouldn't cause this problem.

**Comment by zoechi** [comment] 2018-11-26 16:12
Looks like a dup of #23872

**Comment by eseidelGoogle** [comment] 2018-12-17 04:42
FYI @a-siva in case you have theories.

**Comment by a-siva** [comment] 2018-12-17 06:17
Are you seeing this with version 1.0, some recent fixes were made in flutter tools, if you still have a reproducible case would like to have a look at it.
/cc @aam

**Comment by jonahwilliams** [comment] 2020-01-15 03:20
I haven't seen this issue locally, or filled by other users in a long time. I'm closing this as fixed

**Closed by jonahwilliams** 2020-01-15 03:20 UTC
Labels: severe: crash, t: hot reload, tool
