### ISSUE TITLE
[Impeller][bug] Fonts too bold with emoji

### ISSUE THREAD

**Issue by crizant-mpower** [flutter/flutter#127189] opened 2023-05-19 13:01 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Create `Text` widgets with English characters
2. Create another `Text` widget with an emoji
3. Run the app in the iOS simulator.

### Expected results

All fonts are rendered with the correct font weight.

### Actual results

Once the `Text` widget with emoji is rendered, fonts in all `Text` widgets become bolder.
The smaller the font size, the more obvious it is.

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({super.key});

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    return Scaffold(
      body: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: [
          Text(
            'Headline',
            style: theme.textTheme.headlineMedium!.copyWith(
              fontWeight: FontWeight.w700,
            ),
            textAlign: TextAlign.center,
          ),
          Text(
            'Body',
            style: theme.textTheme.bodyMedium!.copyWith(
              fontWeight: FontWeight.w700,
            ),
            textAlign: TextAlign.center,
          ),
          Text(
            'Label',
            style: theme.textTheme.labelMedium!.copyWith(
              fontWeight: FontWeight.w700,
            ),
            textAlign: TextAlign.center,
          ),
          const Text(
            '😀',
            textAlign: TextAlign.center,
          ),
        ],
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots</summary>

Impeller DISABLED:

![Simulator Screenshot - iPhone 14 Pro - 2023-05-19 at 20 49 30](https://github.com/flutter/flutter/assets/108641489/d234713f-c2f8-45cc-8bff-9c4979d9c2bf)

Impeller ENABLED:
![Simulator Screenshot - iPhone 14 Pro - 2023-05-19 at 20 50 07](https://github.com/flutter/flutter/assets/108641489/2faf97da-4b06-4fc4-b06b-ba9c20a18272)

Impeller ENABLED without emoji in `Text`:
![Simulator Screenshot - iPhone 14 Pro - 2023-05-19 at 20 50 44](https://github.com/flutter/flutter/assets/108641489/18ed296e-f8f8-4be1-a569-f87137b6528e)

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.1, on macOS 13.3.1 22E772610a darwin-arm64,
    locale zh-HK)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.78.2)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by darshankawar** [comment] 2023-05-19 13:13
@crizant-mpower 
This issue seems to have been fixed on latest master, so you'll need to switch to it and run your scenario again to see it working properly.  https://github.com/flutter/flutter/issues/126514#issuecomment-1546974795

Closing this as duplicate of the linked issue and already fixed. If you disagree, write in comments and I'll reopen it.

**Closed by darshankawar** 2023-05-19 13:13 UTC
Labels: in triage
