### ISSUE TITLE
Build fails after adding apple_sign_in dependency

### ISSUE THREAD

**Issue by ighidan** [flutter/flutter#48563] opened 2020-01-10 11:01 UTC
Hi,

My app fails to build after adding apple_sign_in: ^0.1.0 dependency. Here is the error list I get. Any idea? Thanks

```
Error output from Xcode build:
↳
    ** BUILD FAILED **
Xcode's output:
↳
    In file included from /Users/ikramy/dev/flutter/.pub-cache/hosted/pub.dartlang.org/apple_sign_in-0.1.0/ios/Classes/AuthorizationControllerDelegate.m:4:
    /Users/ikramy/dev/flutter/.pub-cache/hosted/pub.dartlang.org/apple_sign_in-0.1.0/ios/Classes/Converters/CredentialConverter.h:8:51: error: expected a type
    + (NSDictionary*)dictionaryFromAppleIDCredential:(ASAuthorizationAppleIDCredential*)credential API_AVAILABLE(ios(13.0));
                                                      ^
    /Users/ikramy/dev/flutter/.pub-cache/hosted/pub.dartlang.org/apple_sign_in-0.1.0/ios/Classes/Converters/CredentialConverter.h:9:40: error: expected a type
    + (NSString*)stringForCredentialState:(ASAuthorizationAppleIDProviderCredentialState)credentialState API_AVAILABLE(ios(13.0));
                                           ^
    /Users/ikramy/dev/flutter/.pub-cache/hosted/pub.dartlang.org/apple_sign_in-0.1.0/ios/Classes/AuthorizationControllerDelegate.m:18:34: error: expected a type
    - (void)authorizationController:(ASAuthorizationController *)controller
                                     ^
    /Users/ikramy/dev/flutter/.pub-cache/hosted/pub.dartlang.org/apple_sign_in-0.1.0/ios/Classes/AuthorizationControllerDelegate.m:19:34: error: expected a type
       didCompleteWithAuthorization:(ASAuthorization *)authorization API_AVAILABLE(ios(13.0)) {
                                     ^
    /Users/ikramy/dev/flutter/.pub-cache/hosted/pub.dartlang.org/apple_sign_in-0.1.0/ios/Classes/AuthorizationControllerDelegate.m:28:34: error: expected a type
    - (void)authorizationController:(ASAuthorizationController *)controller
                                     ^
    /Users/ikramy/dev/flutter/.pub-cache/hosted/pub.dartlang.org/apple_sign_in-0.1.0/ios/Classes/AuthorizationControllerDelegate.m:20:24: error: property 'credential' not found on object of type '__strong id'
        if ([authorization.credential isKindOfClass:[ASAuthorizationAppleIDCredential class]]) {
/Users/ikramy/dev/flutter/.pub-cache/hosted/pub.dartlang.org/apple_sign_in-0.1.0/ios/Classes/AuthorizationControllerDelegate.m:21:88: error: property 'credential' not found on object of type '__strong id'
            _completion([CredentialConverter dictionaryFromAppleIDCredential:authorization.credential]);
                                                                                           ^
    7 errors generated.
Could not build the application for the simulator. 
```

**Comment by VladyslavBondarenko** [comment] 2020-01-10 12:23
Hi @ighidan 
This issue is caused by 3rd party plugin,
you might want to consider opening an issue on the [plugin's github](https://github.com/tomgilder/flutter_apple_sign_in/issues)
Also to better address the problem could you please provide your `flutter doctor -v`?
Thank you

**Comment by ighidan** [comment] 2020-01-10 12:29
> Hi @ighidan
> This issue is caused by 3rd party plugin,
> you might want to consider opening an issue on the [plugin's github](https://github.com/tomgilder/flutter_apple_sign_in/issues)
> Also to better address the problem could you please provide your `flutter doctor -v`?
> Thank you

Thank you for your response. Here is the output from the flutter doctor -v command:

`[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.14.6 18G87, locale en-JO)
    • Flutter version 1.7.8+hotfix.4 at /Users/ikramy/dev/flutter
    • Framework revision 20e59316b8 (6 months ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0

 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/ikramy/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 10.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2, Build version 10E125
    • CocoaPods version 1.7.5

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[!] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.`

**Comment by VladyslavBondarenko** [comment] 2020-01-10 12:49
@ighidan 
Could you upgrade your Flutter SDK and check if you face this problem with the latest stable version (v1.12.13+hotfix.5)?
Thank you

**Comment by ighidan** [comment] 2020-01-11 08:30
> @ighidan
> Could you upgrade your Flutter SDK and check if you face this problem with the latest stable version (v1.12.13+hotfix.5)?
> Thank you

Thank you, but after upgrading Flutter I got many errors related to more packages so I rolledback to the previous version.

**Comment by iapicca** [comment] 2020-01-13 06:19
Hi @ighidan 
as @VladyslavBondarenko pointed out the cause of the error
appears to be the 3rd party plugin [apple_sign_in](https://pub.dev/packages/apple_sign_in);
to address that you may want to open an issue in the dedicated [github](https://github.com/tomgilder/flutter_apple_sign_in/issues).

If you are experiencing issues **without**  said plugin
can you please provide your updated `flutter doctor -v` 
and your `flutter run --verbose`?
Thank you

**Comment by iapicca** [comment] 2020-02-14 13:13
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.

**Closed by iapicca** 2020-02-14 13:13 UTC
Labels: waiting for customer response
