### ISSUE TITLE
WebView crashes if too big

### ISSUE THREAD

**Issue by JiangJuHong** [flutter/flutter#28978] opened 2019-03-07 05:38 UTC
I found the following error, which caused the mobile phone to be restarted automatically:
```dart
> D/        ( 6515): HostConnection::get() New Host Connection established 0xdeea0740, tid 6528
W/cr_ChildProcLH( 6515): Create a new ChildConnectionAllocator with package name = com.android.chrome, sandboxed = true
I/cr_BrowserStartup( 6515): Initializing chromium process, singleProcess=false
I/cr_base ( 6515): Android Locale: en_US requires .pak files: [en-GB.pak, en-US.pak]
E/chromium( 6515): [ERROR:devtools_http_handler.cc(292)] Cannot start http server for devtools. Stop devtools.
W/c.huicitflutte( 6515): Accessing hidden method Landroid/view/textclassifier/logging/SmartSelectionEventTracker;-><init>(Landroid/content/Context;I)V (light greylist, reflection)
W/c.huicitflutte( 6515): Accessing hidden method Landroid/view/textclassifier/logging/SmartSelectionEventTracker;->logEvent(Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent;)V (light greylist, reflection)
W/c.huicitflutte( 6515): Accessing hidden method Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent;->selectionStarted(I)Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent; (light greylist, reflection)
W/c.huicitflutte( 6515): Accessing hidden method Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent;->selectionModified(II)Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent; (light greylist, reflection)
W/c.huicitflutte( 6515): Accessing hidden method Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent;->selectionModified(IILandroid/view/textclassifier/TextClassification;)Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent; (light greylist, reflection)
W/c.huicitflutte( 6515): Accessing hidden method Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent;->selectionModified(IILandroid/view/textclassifier/TextSelection;)Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent; (light greylist, reflection)
W/c.huicitflutte( 6515): Accessing hidden method Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent;->selectionAction(III)Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent; (light greylist, reflection)
W/c.huicitflutte( 6515): Accessing hidden method Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent;->selectionAction(IIILandroid/view/textclassifier/TextClassification;)Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent; (light greylist, reflection)
D/NetworkSecurityConfig( 6515): No Network Security Config specified, using platform default
W/c.huicitflutte( 6515): Accessing hidden method Ldalvik/system/CloseGuard;->get()Ldalvik/system/CloseGuard; (light greylist, reflection)
W/c.huicitflutte( 6515): Accessing hidden method Ldalvik/system/CloseGuard;->open(Ljava/lang/String;)V (light greylist, reflection)
W/c.huicitflutte( 6515): Accessing hidden method Ldalvik/system/CloseGuard;->warnIfOpen()V (light greylist, reflection)
W/cr_media( 6515): Requires BLUETOOTH permission
D/        ( 6515): HostConnection::get() New Host Connection established 0xca735780, tid 6643
D/EGL_emulation( 6515): eglCreateContext: 0xb83fc6a0: maj 3 min 0 rcv 3
D/EGL_emulation( 6515): eglMakeCurrent: 0xb83fc6a0: ver 3 0 (tinfo 0xb513a630)
W/VideoCapabilities( 6515): Unrecognized profile 4 for video/hevc
I/VideoCapabilities( 6515): Unsupported profile 4 for video/mp4v-es
W/c.huicitflutte( 6515): Attempt to remove non-JNI local reference, dumping thread
W/cr_MediaCodecUtil( 6515): HW encoder for video/avc is not available on this device.
D/EGL_emulation( 6515): eglMakeCurrent: 0xdee85f00: ver 3 0 (tinfo 0xdee83da0)
W/cr_CrashFileManager( 6515): /data/user/0/top.huic.huicitflutter/cache/WebView/Crash Reports does not exist or is not a directory
D/EGL_emulation( 6515): eglCreateContext: 0xbdf89c00: maj 3 min 0 rcv 3
D/EGL_emulation( 6515): eglMakeCurrent: 0xbdf89c00: ver 3 0 (tinfo 0xb513a630)
I/flutter ( 6515): text:The key "target-densitydpi" is not supported.
W/c.huicitflutte( 6515): Attempt to remove non-JNI local reference, dumping thread
W/c.huicitflutte( 6515): Attempt to remove non-JNI local reference, dumping thread
W/c.huicitflutte( 6515): Attempt to remove non-JNI local reference, dumping thread
D/        ( 6515): HostConnection::get() New Host Connection established 0xbe142c40, tid 6527
W/c.huicitflutte( 6515): Attempt to remove non-JNI local reference, dumping thread
W/c.huicitflutte( 6515): Attempt to remove non-JNI local reference, dumping thread
W/c.huicitflutte( 6515): Attempt to remove non-JNI local reference, dumping thread
W/c.huicitflutte( 6515): Attempt to remove non-JNI local reference, dumping thread
W/c.huicitflutte( 6515): Attempt to remove non-JNI local reference, dumping thread
W/c.huicitflutte( 6515): Attempt to remove non-JNI local reference, dumping thread
W/c.huicitflutte( 6515): Attempt to remove non-JNI local reference, dumping thread
W/c.huicitflutte( 6515): Attempt to remove non-JNI local reference, dumping thread
W/c.huicitflutte( 6515): Attempt to remove non-JNI local reference, dumping thread
W/c.huicitflutte( 6515): Attempt to remove non-JNI local reference, dumping thread
I/flutter ( 6515): text:height:16592
D/        ( 6515): HostConnection::get() New Host Connection established 0xb6694940, tid 6529
D/gralloc_ranchu( 6515): gralloc_unregister_buffer: exiting HostConnection (is buffer-handling thread)
D/        ( 6515): HostConnection::get() New Host Connection established 0xb6694940, tid 6529
D/gralloc_ranchu( 6515): gralloc_unregister_buffer: exiting HostConnection (is buffer-handling thread)
D/        ( 6515): HostConnection::get() New Host Connection established 0xb6694940, tid 6529
D/gralloc_ranchu( 6515): gralloc_unregister_buffer: exiting HostConnection (is buffer-handling thread)
D/        ( 6515): HostConnection::get() New Host Connection established 0xb6694940, tid 6529
D/gralloc_ranchu( 6515): gralloc_unregister_buffer: exiting HostConnection (is buffer-handling thread)
D/        ( 6515): HostConnection::get() New Host Connection established 0xb6694940, tid 6529
E/MethodChannel#flutter/platform_views( 6515): Failed to handle method call
E/MethodChannel#flutter/platform_views( 6515): java.lang.RuntimeException: InputChannel is not initialized.
E/MethodChannel#flutter/platform_views( 6515): 	at android.view.InputEventReceiver.nativeInit(Native Method)
E/MethodChannel#flutter/platform_views( 6515): 	at android.view.InputEventReceiver.<init>(InputEventReceiver.java:70)
E/MethodChannel#flutter/platform_views( 6515): 	at android.view.ViewRootImpl$WindowInputEventReceiver.<init>(ViewRootImpl.java:7190)
E/MethodChannel#flutter/platform_views( 6515): 	at android.view.ViewRootImpl.setView(ViewRootImpl.java:847)
E/MethodChannel#flutter/platform_views( 6515): 	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:356)
E/MethodChannel#flutter/platform_views( 6515): 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:93)
E/MethodChannel#flutter/platform_views( 6515): 	at android.app.Dialog.show(Dialog.java:329)
E/MethodChannel#flutter/platform_views( 6515): 	at android.app.Presentation.show(Presentation.java:249)
E/MethodChannel#flutter/platform_views( 6515): 	at io.flutter.plugin.platform.VirtualDisplayController.resize(VirtualDisplayController.java:125)
E/MethodChannel#flutter/platform_views( 6515): 	at io.flutter.plugin.platform.PlatformViewsController.resizePlatformView(PlatformViewsController.java:239)
E/MethodChannel#flutter/platform_views( 6515): 	at io.flutter.plugin.platform.PlatformViewsController.onMethodCall(PlatformViewsController.java:124)
E/MethodChannel#flutter/platform_views( 6515): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:200)
E/MethodChannel#flutter/platform_views( 6515): 	at io.flutter.view.FlutterNativeView.handlePlatformMessage(FlutterNativeView.java:163)
E/MethodChannel#flutter/platform_views( 6515): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#flutter/platform_views( 6515): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/MethodChannel#flutter/platform_views( 6515): 	at android.os.Looper.loop(Looper.java:160)
E/MethodChannel#flutter/platform_views( 6515): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
E/MethodChannel#flutter/platform_views( 6515): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter/platform_views( 6515): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/MethodChannel#flutter/platform_views( 6515): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
E/Surface ( 6515): queueBuffer: error queuing buffer to SurfaceTexture, -19
E/EGL_emulation( 6515): tid 6550: swapBuffers(552): error 0x300d (EGL_BAD_SURFACE)
W/OpenGLRenderer( 6515): swapBuffers encountered EGL error 12301 on 0xdee86200, halting rendering...
D/EGL_emulation( 6515): eglMakeCurrent: 0xdee85f00: ver 3 0 (tinfo 0xdee83da0)
D/AndroidRuntime( 6515): Shutting down VM
E/AndroidRuntime( 6515): FATAL EXCEPTION: main
E/AndroidRuntime( 6515): Process: top.huic.huicitflutter, PID: 6515
E/AndroidRuntime( 6515): DeadSystemException: The system died; earlier logs will point to the root cause
I/Process ( 6515): Sending signal. PID: 6515 SIG: 9
Application finished.
Failed to send request: {"jsonrpc":"2.0","id":"36","method":"resume","params":{"isolateId":"isolates/1061279042"}}
```

**Comment by Kartik1607** [comment] 2019-03-07 10:38
How did this error occur? What flutter code were you executing? Please provide some code as well.

**Comment by JiangJuHong** [comment] 2019-03-08 01:08
> How did this error occur? What flutter code were you executing? Please provide some code as well.

@Kartik1607 Because I use third-party WebView components, but I want to add custom components after WebView, so I think of putting WebView into ListView, WebView as the child of Container, and through JS code to adapt the height of Container, multiple access to WebView will appear this problem, according to preliminary judgment, should not be caused by WebView. The third-party components used are:`

Flutter_inappbrowser', I tried to use the official WebView, but unfortunately, it hasn't officially released yet.

**Comment by kangwang1988** [comment] 2019-03-08 03:38
@JiangJuHong 
Please paste "flutter doctor -v".
If possible, a minimal demo project which can reproduce this issue would be helpful.

**Comment by PiotrWpl** [comment] 2019-03-25 11:18
Hi,

looks like I have the same error, but I'm using official webview_flutter plugin.
**And this error probably occurs only in Android version.**
I used example project from webview_flutter plugin to create demo project.
Please check it -> https://github.com/PiotrWpl/plugins/blob/master/packages/webview_flutter/lib/webview_flutter.dart#L54

Every time when I change webview parent container height to bigger than 2048 I'm getting similar crash logs to mentioned by @JiangJuHong + my device is restarting completely or just to lock screen.

I did my tests on Android real device (Huaweii Mate 10 Pro with Android 9), and for iOS I used simulator.
In iOS simulator I changed height up to 170049 and it was working without problems. So I assume, that iOS is working fine.

It's very high priority error for me, because in our project we need to use webview to display the content, and this webview must be a part of scrollview or listview to also show some other widgets above and below the webview.

**Comment by JiangJuHong** [comment] 2019-03-25 11:49
> 嗨，
> 
> 看起来我有同样的错误，但我正在使用官方webview_flutter插件。
> **并且此错误可能仅在Android版本中发生。**
> 我使用了webview_flutter插件中的示例项目来创建演示项目。
> 请检查 - > https://github.com/PiotrWpl/plugins/blob/master/packages/webview_flutter/lib/webview_flutter.dart#L54
> 
> 每次当我将webview父容器高度更改为大于2048时，我会得到@JiangJuHong提到的类似崩溃日志+我的设备完全重启或只是锁定屏幕。
> 
> 我在Android真实设备（使用Android 9的Huaweii Mate 10 Pro）上进行了测试，而对于iOS，我使用了模拟器。
> 在iOS模拟器中，我将高度改为170049，并且它没有问题。所以我假设，iOS工作正常。
> 
> 这对我来说是一个非常高优先级的错误，因为在我们的项目中我们需要使用webview来显示内容，这个webview必须是scrollview或listview的一部分，以显示webview上方和下方的一些其他小部件。



> Hi,
> 
> looks like I have the same error, but I'm using official webview_flutter plugin.
> **And this error probably occurs only in Android version.**
> I used example project from webview_flutter plugin to create demo project.
> Please check it -> https://github.com/PiotrWpl/plugins/blob/master/packages/webview_flutter/lib/webview_flutter.dart#L54
> 
> Every time when I change webview parent container height to bigger than 2048 I'm getting similar crash logs to mentioned by @JiangJuHong + my device is restarting completely or just to lock screen.
> 
> I did my tests on Android real device (Huaweii Mate 10 Pro with Android 9), and for iOS I used simulator.
> In iOS simulator I changed height up to 170049 and it was working without problems. So I assume, that iOS is working fine.
> 
> It's very high priority error for me, because in our project we need to use webview to display the content, and this webview must be a part of scrollview or listview to also show some other widgets above and below the webview.

My mistake is the same as yours, but I haven't tested it on ios, so far I haven't found a solution.

**Comment by PiotrWpl** [comment] 2019-04-01 06:05
@amirh @mklim @iskakaushik
Hi, 
I would like to raise this bug as a blocker in using android webview in cases where it's not just a single webpage viewer :/
Is this even fixable? Or we should start working internally on some workaround? :/
We are in very advanced stage in our project, and turns out we may have a huge issue in showing html content in app. 
Thank you in advance for your help!

**Comment by amirh** [comment] 2019-04-01 06:26
Thanks for the report, it will help if you can post a minimal code snippet that reproduces the issue(the shorter the better 😄 ).

**Comment by PiotrWpl** [comment] 2019-04-01 06:32
Hi @amirh !
I really grateful You respond me so quickly! Please check my first comment in this thread. I already did just a small change in webview_flutter example which allowed me to reproduce this issue. Please let me know, if this is enough. Cheers!

> looks like I have the same error, but I'm using official webview_flutter plugin.
> **And this error probably occurs only in Android version.**
> I used example project from webview_flutter plugin to create demo project.
> Please check it -> https://github.com/PiotrWpl/plugins/blob/master/packages/webview_flutter/lib/webview_flutter.dart#L54
> 
> Every time when I change webview parent container height to bigger than 2048 I'm getting similar crash logs to mentioned by @JiangJuHong + my device is restarting completely or just to lock screen.
> 
> I did my tests on Android real device (Huaweii Mate 10 Pro with Android 9), and for iOS I used simulator.
> In iOS simulator I changed height up to 170049 and it was working without problems. So I assume, that iOS is working fine.
> 
> It's very high priority error for me, because in our project we need to use webview to display the content, and this webview must be a part of scrollview or listview to also show some other widgets above and below the webview.

**Comment by PiotrWpl** [comment] 2019-04-03 06:44
Good morning @amirh 
Please let me know if the sample code I provided was enough to reproduce this issue, or if You need something more from me.
I would be grateful if you will be able to share your thoughts about this issue.

Thanks!

**Comment by amirh** [comment] 2019-04-03 06:55
Hi @PiotrWpl I'm going to be off for a few weeks now so I won't be personally looking at this in the coming weeks.

It will make things faster if you can share a minimal sample that reproduces the issue and does nothing else(the sample app is a  bit long at this point).

**Comment by PiotrWpl** [comment] 2019-04-03 07:50
@amirh 
I made this example a lot simpler -> https://github.com/PiotrWpl/plugins/blob/master/packages/webview_flutter/lib/webview_flutter.dart

Basically it's just a _WebView_ in _Container_ with height bigger than 2048, inside _SingleChildScrollView_.

It's crashing every time for me (on Android).
Is there any chance that You will ask someone from your team to take a look on that, while you will be off?
Thanks a lot!

**Comment by iskakaushik** [comment] 2019-04-04 16:33
@PiotrWpl, thanks for the very simple example, i'm taking a look at this.

**Comment by iskakaushik** [comment] 2019-04-04 19:53
I am able to repro the error consistently. The root cause of the error seems to be:

```
04-04 12:45:11.895   624  2069 E BufferLayer: dimensions too large 35000 x 35000
04-04 12:45:11.896   624  2069 E SurfaceFlinger: createBufferLayer() failed (Invalid argument)
04-04 12:45:11.914 12126 12140 E SurfaceComposerClient: SurfaceComposerClient::createSurface error Invalid argument
04-04 12:45:11.916 12126 12140 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: ActivityManager
04-04 12:45:11.916 12126 12140 E AndroidRuntime: android.view.Surface$OutOfResourcesException
04-04 12:45:11.916 12126 12140 E AndroidRuntime: 	at android.view.SurfaceControl.nativeCreate(Native Method)
04-04 12:45:11.916 12126 12140 E AndroidRuntime: 	at android.view.SurfaceControl.<init>(SurfaceControl.java:590)
04-04 12:45:11.916 12126 12140 E AndroidRuntime: 	at android.view.SurfaceControl.<init>(SurfaceControl.java:60)
04-04 12:45:11.916 12126 12140 E AndroidRuntime: 	at android.view.SurfaceControl$Builder.build(SurfaceControl.java:377)
04-04 12:45:11.916 12126 12140 E AndroidRuntime: 	at com.android.server.wm.DisplayContent.<init>(DisplayContent.java:780)
04-04 12:45:11.916 12126 12140 E AndroidRuntime: 	at com.android.server.wm.RootWindowContainer.createDisplayContent(RootWindowContainer.java:219)
04-04 12:45:11.916 12126 12140 E AndroidRuntime: 	at com.android.server.wm.DisplayWindowController.<init>(DisplayWindowController.java:44)
04-04 12:45:11.916 12126 12140 E AndroidRuntime: 	at com.android.server.am.ActivityDisplay.createWindowContainerController(ActivityDisplay.java:125)
04-04 12:45:11.916 12126 12140 E AndroidRuntime: 	at com.android.server.am.ActivityDisplay.<init>(ActivityDisplay.java:120)
04-04 12:45:11.916 12126 12140 E AndroidRuntime: 	at com.android.server.am.ActivityStackSupervisor.getActivityDisplayOrCreateLocked(ActivityStackSupervisor.java:4314)
04-04 12:45:11.916 12126 12140 E AndroidRuntime: 	at com.android.server.am.ActivityStackSupervisor.handleDisplayAdded(ActivityStackSupervisor.java:4275)
04-04 12:45:11.916 12126 12140 E AndroidRuntime: 	at com.android.server.am.ActivityStackSupervisor.access$100(ActivityStackSupervisor.java:193)
04-04 12:45:11.916 12126 12140 E AndroidRuntime: 	at com.android.server.am.ActivityStackSupervisor$ActivityStackSupervisorHandler.handleMessage(ActivityStackSupervisor.java:4724)
04-04 12:45:11.916 12126 12140 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
04-04 12:45:11.916 12126 12140 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
04-04 12:45:11.916 12126 12140 E AndroidRuntime: 	at android.os.HandlerThread.run(HandlerThread.java:65)
04-04 12:45:11.916 12126 12140 E AndroidRuntime: 	at com.android.server.ServiceThread.run(ServiceThread.java:44)
```

**Comment by iskakaushik** [comment] 2019-04-04 21:02
@PiotrWpl , when you specify `height` in a container wrapping the `WebView` those are the [logical pixels as opposed to physical pixels](https://docs.flutter.io/flutter/dart-ui/Window/devicePixelRatio.html). So, when you say `5000` pixels on a "Nexus 6" (dpi: 3.5) device, we try to create a [VirtualDisplay](https://developer.android.com/reference/android/hardware/display/VirtualDisplay) backed by a texture of size `17,500`. This is causing the device to run out of resources and restart.

I tried running the following app which has ~5 `WebViews` displayed at once, and I was able to get it to run fine on a Pixel 2 device. I would recommend clamping the `maxHeight` of the widget containing your `WebView` to `MediaQuery.of(context).size.height` and see if you are still able to reproduce this issue.

https://gist.github.com/iskakaushik/8cf258405fec07af8e55c52382d1fc37

**Comment by PiotrWpl** [comment] 2019-04-05 07:56
Hi @iskakaushik ,

thanks for response!

Yes, changing `Container` height to `MediaQuery.of(context).size.height` in my latest example with just a `Webview` in `ScrollView` works, the app is not crashing and we have whole site content visible.
But I can't use such a small value for `height` if we will put `Webview` as one of the children of for example `Column` widget. Because this will make `Webview` too small to display whole site content.
I prepared this example to represent what I want to achieve -> https://gist.github.com/PiotrWpl/c556f2bc7b403c64eebbc5a467df08d9

As You can observe, in this situation `Webview` size will be fixed to `MediaQuery.of(context).size.height`, so user will never be able to see whole content of it. And looks like, that if I want to fix that, I need to use value bigger than 2048, but then as we know, app will crash :/

What we would like to achieve in the app we are working on is to build a whole `article details screen` which general structure will be more like this one:
```
class ArticleDetailsScreen extends StatefulWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: CustomAppBar(),
      body: SingleChildScrollView( // Of course we can, and probably should use ListView widget instead of combination of SingleChildScrollView + Column widgets. I used this only for simplification.  
        child: Column(
          children: <Widget>[
            CustomArticleTitleWidget(),
            CustomArticleImageWidget(),
            CustomArticleLeadWidget(),
            CustomArticleContentWidget(), // <- and this is the place where our Webview has to be used
            CustomRecommendArticlesWidget(),
          ],
        ),
      ),
      persistentFooterButtons: <Widget>[
        CustomButton_1,
        CustomButton_2,
      ],
    );
  }
}
```

**Comment by iskakaushik** [comment] 2019-04-05 15:22
@PiotrWpl , thanks for clarifying your use case. In that case, wouldn't you want to allow user to scroll through your `WebView`? That can be achieved in the following way: https://gist.github.com/iskakaushik/ff49eb21274263f4b4fbbacd15750a6a

**Comment by PiotrWpl** [comment] 2019-04-05 16:19
Unfortunately, we can't fix positions of header and footer elements, because they are pretty huge and in this situation most of the view will be covered - or maybe even entire device screen.
I know that `WebView` will be not scrollable because of their parent, that why I tried to use fixed size of it.

I already did views like this in native android and iOS apps. I really surprised I got issue like this in Flutter :/

Do You think there is any way to bypass this restriction about too big dimensions?

**Comment by iskakaushik** [comment] 2019-04-05 18:12
Due to the way web view currently works on Flutter, I do not think it's feasible to have huge web view. In flutter, on android platform views are rendered on to a [VirtualDisplay](https://developer.android.com/reference/android/hardware/display/VirtualDisplay) that is backed by a texture. If you create something too big, the device seems to crash. I have filed https://github.com/flutter/flutter/issues/30566 to handle these more gracefully.

I will further explore if we can do something clever about the way we render on to the VirtualDisplay. Maybe we can use some tricks to clamp the backing surface to the viewport size. But this is a bigger project that I might have to loop in @amirh and @cbracken .

As a work around can you try using [NestedScrollView](https://docs.flutter.io/flutter/widgets/NestedScrollView-class.html), seems like it might work for your use case.

**Comment by PiotrWpl** [comment] 2019-04-06 08:40
Ok, understand, I will try with `NestedScrollView` on Monday. 
Otherwise, if it will be not enough, for Android platform I will include this `article details screen` as a separate `Activity` :/ But I hope that will be a temporary solution before You will be able to fix this error, or we will be able to find internally some better way to show the content than using html.

Thanks for all your help!

**Comment by Hixie** [comment] 2019-04-09 23:26
@timsneath Can you elaborate on why this is a blocker?

**Comment by PiotrWpl** [comment] 2019-04-11 14:13
That was a blocker for the product I'm working on. Unfortunately we have to show some html content inside the app, with widget structure like described above. But as You know, android webview is crashing when we are using it inside the Flutter.
Our final solution was to recreate whole this view as a separate Activity using Android SDK + Java. That was the only way we could make this done, and release our app before the deadline. But of course, we were forced to duplicate some code for two screens (keep Dart to implement iOS view, and use Java for Android). It's not too comfortable, because our dart tests will not work 100% now for Android, and we will have more work to configure our multi-market app.
I hope there will be some solution to use Dart for both platforms, so we will be able to remove our workaround and still have one codebase.

**Comment by Hixie** [comment] 2019-04-16 23:08
@PiotrWpl Can you confirm what size you were making the WebView? Was it the size of the screen? Smaller? Bigger? Did it take the device pixel ratio into account in some way?

**Comment by PiotrWpl** [comment] 2019-04-17 06:02
Hi @Hixie ,
webview is crashing on my device every time when I make it bigger than 2048 height.
To reproduce this issue You can check this simple example -> https://github.com/PiotrWpl/plugins/blob/master/packages/webview_flutter/lib/webview_flutter.dart

Screen is of course smaller than webview, that's why I want to make all of that scrollable with others widgets.

**Comment by Hixie** [comment] 2019-04-30 23:12
@PiotrWpl Looks like the way we use the VirtualDisplay, you can't have WebViews bigger than the screen.

@iskakaushik With your PR, is this bug fixed?

**Comment by iskakaushik** [comment] 2019-05-02 18:42
@Hixie yes, i've made it so large `WebView`s will not restart Android devices. There are still some improvements that can be made that i'm tracking here: https://github.com/flutter/flutter/issues/31990

It will likely involve additional work on both the framework and the engine.

**Closed by iskakaushik** 2019-05-02 18:42 UTC
Labels: a: platform-views, customer: product, p: webview, plugin, severe: crash, severe: customer blocker, ▣ platform-android

**Comment by yk3372** [comment] 2019-05-07 02:18
I found this change not calc navigationbar height, when the device has navigationbar. If I hide the navigation bar, the code below can cause error :
```java
private void validateVirtualDisplayDimensions(int width, int height) {
        DisplayMetrics metrics = mContext.getResources().getDisplayMetrics();
        if (height > metrics.heightPixels || width > metrics.widthPixels) {
            String error = "Creating a virtual display of size: "
                +  "[" + width + ", " + height + "]"
                + " is not supported. It is larger than the device screen size: "
                +  "[" + metrics.widthPixels + ", " + metrics.heightPixels + "].";
            throw new IllegalArgumentException(error);
        }
    }
```
The DisplayMetrics.height is not include the nav height, but the args height is include, and then cause exceptions.

**Comment by yoavrofe** [comment] 2019-05-23 07:38
A full screen WebView (w/o an AppBar) now produces the following error on my Pocophone on the master channel:

`E/flutter (14390): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: PlatformException(error, Creating a virtual display of size: [1080, 2116] is not supported. It is larger than the device screen size: [1080, 2029]., null)`

The screen size as calculated by `MediaQuery.of(context).size.height*MediaQuery.of(context).devicePixelRatio`
is 2116.0.

**This is a critical bug**, that prevents running full-screen platform views (including Google Maps) on similar devices.

Flutter Doctor:
```
[✓] Flutter (Channel master, v1.6.2-pre.21, on Mac OS X 10.14.4 18E226, locale en-IL)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
[✓] Android Studio (version 3.3)
[✓] VS Code (version 1.34.0)
[✓] Connected device (1 available)

```

**Comment by yoavrofe** [comment] 2019-05-27 12:19
The (now merged) pull request that solved this issue causes severe errors on some devices with a notch.

Please see my comment [on the pull request](https://github.com/flutter/engine/commit/7471ddea463dd0a95a2b6d8e3a9028df70c56cee#commitcomment-33689770).

**Comment by iskakaushik** [comment] 2019-05-28 20:35
Hi @yoavrofe, taking a look at this now. Will update on the issue: https://github.com/flutter/flutter/issues/33290, thanks!

**Comment by mrifni** [comment] 2019-11-11 16:27
I am having this issue, whats the update on this ? why the issue is closed?

**Comment by DanielYP** [comment] 2019-11-26 14:00
I am having this issue, whats the update on this ? why the issue is closed?

**Comment by timsneath** [comment] 2019-11-26 17:41
@mrifni and @DanielYP - it would be very helpful if you could describe the issue you're now having. It's hard to know what 'this issue' is in the context of a length thread above.

For example: 

 - You're seeing a crash and restart issue like the one @JiangJuHong reported, and you've confirmed you're using a build that has the fix from @iskakaushik? In which case, please create a new issue that links to this issue, including the results of `flutter doctor -v` on your machine, characteristics of the device you're seeing this on (model/Android version), and ideally a minimal repro.
 - You're seeing the issue that @yoavrofe reported about the notch, and you're running a build that contains that fix? 
 - You're seeing something different?

Thanks for using Flutter!

**Comment by zsunkun** [comment] 2020-04-17 08:09
[PR #8704](https://github.com/wxCUHK/engine/commit/3b6c909437ff5367f1092d968481a90fe5e799de) and [PR #9110](https://github.com/flutter/engine/commit/d4794122ab779010f1d69bcbebb61ab2f7a2dae2) just added some warning logs, is there a way to solve this problem(device restart)

**Comment by DFelten** [comment] 2020-07-29 16:28
This issue is still there. When trying to set the height on a very high value the app is crashing.

**Comment by juefeiyechen** [comment] 2020-11-05 03:52
同样的问题，还没有解决呀

**Comment by juefeiyechen** [comment] 2020-11-05 03:52
怎么办 求支招

**Comment by SmileJason** [comment] 2020-11-23 03:24
你怎么解决，我也遇到同样的问题

**Comment by ASemeniuk** [comment] 2020-11-30 08:44
Why was this issue closed without proper resolution?

**Comment by tudorcodarnai** [comment] 2021-01-13 19:17
This issue is still unresolved. Any webview in a container with a height bigger than 2048 will crash the app, regardless of the content.

Why is this issue closed? 

flutter_webview is already out of developer preview and we still have this problem.

My scenario is similar to @DFelten, above the container we have image, title and metadata. All these are wrapped in a SingleScrollView.

1 year later almost and no real solution?

**Comment by leegohi04517** [comment] 2021-01-14 06:22
I faced the same problem

**Comment by cyc2303** [comment] 2021-03-05 02:31
Is there any *real* solution?

**Comment by achalkias** [comment] 2021-03-08 20:06
Yeah problem is still there app crashes with error: 
Creating a virtual display of size: [1280, 9508] may result in problems(https://github.com/flutter/flutter/issues/2897).It is larger than the device screen size: [1440, 2560].

It only crashes on Android. It works pretty fine on iOS.
