### ISSUE TITLE
Add native Windows UI elements in Flutter

### ISSUE THREAD

**Issue by Rahul-Dixit** [flutter/flutter#81471] opened 2021-04-29 14:36 UTC
## Use case

Flutter has excellent support for native Android and iOS widgets. This allows the developers to create great UI experiences on the mobile platform. But Flutter lacks support for native Windows UI elements. For example the Windows style progress bars, switches, acrylic and reveal effects, etc. This becomes increasingly important as Flutter plans to roll out support for desktop platforms. But the developers of the Windows platform have to use native Android widgets or native iOS widgets while designing their UX. Because of this, apps built using Flutter for Windows do no look and feel native, in contrast to those built for Android and iOS.

## Proposal

Flutter should also support native Windows UI elements. This would allow the apps targeted towards Windows platform to look and feel native. Flutter should support the UI elements as specified by WinUI 3.0. A beautiful implementation of all these elements can be found in the XAML controls gallery app by Microsoft:

![apps 932 13820844010130368 517e6816-ca0d-4811-a543-688aef089417](https://user-images.githubusercontent.com/73630877/116568155-e2452b00-a925-11eb-8638-93854bffee6d.jpeg)
![apps 46941 13820844010130368 132c98d3-eb2e-4d0a-8508-95b76e7d534a](https://user-images.githubusercontent.com/73630877/116568196-ea9d6600-a925-11eb-8888-1ae828dfb785.jpeg)

Both this app as well as the implementation of these UI controls are open source and available on GitHub.

**Comment by stuartmorgan** [comment] 2021-04-29 15:06
Duplicate of https://github.com/flutter/flutter/issues/46481

Note that what you are describing is a Window-style theme, such that Flutter controls match the style of actual native UI elements. Actually using native UI elements for everything would no longer be Flutter.

**Closed by stuartmorgan** 2021-04-29 15:06 UTC
