### ISSUE TITLE
[tool_crash] StateError: Bad state: Stream has already been listened to.

### ISSUE THREAD

**Issue by mwanuketech** [flutter/flutter#140627] opened 2023-12-26 22:02 UTC
## Command
```
flutter run --machine
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
StateError: Bad state: Stream has already been listened to.
```
#0      _StreamController._subscribe (dart:async/stream_controller.dart:678:7)
#1      _ControllerStream._createSubscription (dart:async/stream_controller.dart:828:19)
#2      _StreamImpl.listen (dart:async/stream_impl.dart:471:9)
#3      _Socket.listen (dart:io-patch/socket_patch.dart:2236:31)
#4      _StdStream.listen (dart:io/stdio.dart:22:20)
#5      new DaemonInputStreamConverter.<anonymous closure> (package:flutter_tools/src/daemon.dart:67:70)
#6      _runGuarded (dart:async/stream_controller.dart:815:24)
#7      _StreamController._subscribe.<anonymous closure> (dart:async/stream_controller.dart:694:7)
#8      _BufferingStreamSubscription._guardCallback (dart:async/stream_impl.dart:415:13)
#9      _StreamController._subscribe (dart:async/stream_controller.dart:693:18)
#10     _ControllerStream._createSubscription (dart:async/stream_controller.dart:828:19)
#11     _StreamImpl.listen (dart:async/stream_impl.dart:471:9)
#12     new DaemonConnection (package:flutter_tools/src/daemon.dart:246:54)
#13     RunCommand.createMachineDaemon (package:flutter_tools/src/commands/run.dart:611:7)
#14     RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:635:29)
<asynchronous suspension>
#15     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1336:27)
<asynchronous suspension>
#16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#17     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#18     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:296:9)
<asynchronous suspension>
#19     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
```
```
[32m[✓][39m Flutter (Channel stable, 3.10.6, on Microsoft Windows [Version 10.0.19045.3803], locale en-TZ)
    [32m•[39m Flutter version 3.10.6 on channel stable at D:\PARENTAL ADMIN\DART  FLUTTER\flutter_windows_3.10.6-stable\flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision f468f3366c (6 months ago), 2023-07-12 15:19:05 -0700
    [32m•[39m Engine revision cdbeda788a
    [32m•[39m Dart version 3.0.6
    [32m•[39m DevTools version 2.23.1

[32m[✓][39m Windows Version (Installed version of Windows is version 10 or higher)

[31m[✗][39m Android toolchain - develop for Android devices
    [31m✗[39m Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[31m[✗][39m Visual Studio - develop for Windows
    [31m✗[39m Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[32m[✓][39m Android Studio (version 2021.1)
    [32m•[39m Android Studio at C:\Program Files\Android\Android Studio
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[32m[✓][39m VS Code (version 1.85.1)
    [32m•[39m VS Code at C:\Users\ABINERI MWANUKE\AppData\Local\Programs\Microsoft VS Code
    [32m•[39m Flutter extension version 3.78.0

[32m[✓][39m Connected device (3 available)
    [32m•[39m Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19045.3803]
    [32m•[39m Chrome (web)      • chrome  • web-javascript • Google Chrome 120.0.6099.110
    [32m•[39m Edge (web)        • edge    • web-javascript • Microsoft Edge 120.0.2210.91

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[33m![39m Doctor found issues in 2 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: fb57da5f945d02ef4f98dfd9409a72b7cce74268
### Plugins
cloud_firestore-4.3.1
cloud_firestore_web-3.2.1
firebase_auth-4.2.5
firebase_auth_web-5.2.4
firebase_core-2.4.1
firebase_core_web-2.1.0
firebase_storage-11.0.10
firebase_storage_web-3.3.19
flutter_native_splash-2.2.16
path_provider-2.0.12
path_provider_android-2.0.22
path_provider_foundation-2.1.1
path_provider_linux-2.1.7
path_provider_windows-2.1.3
url_launcher-6.1.8
url_launcher_android-6.0.23
url_launcher_ios-6.0.18
url_launcher_linux-3.0.2
url_launcher_macos-3.0.2
url_launcher_web-2.0.14
url_launcher_windows-3.0.3

**Comment by dam-ease** [comment] 2023-12-27 09:09
Closing as a duplicate of https://github.com/flutter/flutter/issues/139624
Please comment on the already existing issue, upvote and follow up for updates.

**Closed by dam-ease** 2023-12-27 09:09 UTC
Labels: in triage
