### ISSUE TITLE
[google_sign_in] example app doesn't work.

### ISSUE THREAD

**Issue by james-lawrence** [flutter/flutter#25909] opened 2018-12-30 15:51 UTC
1. clone plugins repo
2. open google_sign_in w/ android studio
3. run on emulator (Android 9.0 (Google Play) x86, same behaviour on a pixel 2 device (fully updated)

## Logs

```
10:47:36.706 1148 info flutter.tools [+5618 ms] I/flutter ( 2583): PlatformException(sign_in_failed, com.google.android.gms.common.api.ApiException: 12500: , null)
10:47:36.717 1149 info flutter.tools [  +11 ms] D/EGL_emulation( 2583): eglMakeCurrent: 0xdf2f25a0: ver 2 0 (tinfo 0xe5fed680)
```

adb logs
```
12-30 10:50:30.956  1920  1931 I ActivityManager: START u0 {act=com.google.android.gms.auth.GOOGLE_SIGN_IN pkg=io.flutter.plugins.googlesigninexample cmp=io.flutter.plugins.googlesigninexample/com.google.android.gms.auth.api.signin.internal.SignInHubActivity (has extras)} from uid 10089
12-30 10:50:30.994  1920  1931 I ActivityManager: START u0 {act=com.google.android.gms.auth.GOOGLE_SIGN_IN pkg=com.google.android.gms cmp=com.google.android.gms/.auth.api.signin.ui.SignInActivity (has extras)} from uid 10089
12-30 10:50:31.051  1920  1936 I ActivityManager: Start proc 3201:com.google.android.gms.ui/u0a10 for activity com.google.android.gms/.auth.api.signin.ui.SignInActivity
12-30 10:50:31.422  1920  1942 I ActivityManager: Displayed com.google.android.gms/.auth.api.signin.ui.SignInActivity: +382ms (total +445ms)
12-30 10:50:31.439  1920  1931 I ActivityManager: START u0 {act=com.google.android.gms.signin.action.SIGN_IN cmp=com.google.android.gms/.signin.activity.SignInActivity (has extras)} from uid 10010
12-30 10:50:31.538  1920  1942 I ActivityManager: Displayed com.google.android.gms/.signin.activity.SignInActivity: +89ms (total +101ms)
12-30 10:50:31.715  3201  3201 I SignIn  : [Activity,SignInChimeraActivity] Couldn't fetch app's branding information, but continuing without it.
12-30 10:50:39.321  1761  1889 W SurfaceFlinger: Attempting to set client state on removed layer: com.google.android.gms/com.google.android.gms.auth.api.signin.ui.SignInActivity#0
12-30 10:50:39.321  1761  1889 W SurfaceFlinger: Attempting to destroy on removed layer: com.google.android.gms/com.google.android.gms.auth.api.signin.ui.SignInActivity#0
12-30 10:50:39.321  1761  1803 W SurfaceFlinger: Attempting to set client state on removed layer: Surface(name=f7bc5d8 com.google.android.gms/com.google.android.gms.auth.api.signin.ui.SignInActivity)/@0x949a997 - animation-leash#0
12-30 10:50:39.321  1761  1803 W SurfaceFlinger: Attempting to destroy on removed layer: Surface(name=f7bc5d8 com.google.android.gms/com.google.android.gms.auth.api.signin.ui.SignInActivity)/@0x949a997 - animation-leash#0
12-30 10:50:39.422  1761  1803 W SurfaceFlinger: Attempting to set client state on removed layer: io.flutter.plugins.googlesigninexample/com.google.android.gms.auth.api.signin.internal.SignInHubActivity#0
12-30 10:50:39.422  1761  1803 W SurfaceFlinger: Attempting to destroy on removed layer: io.flutter.plugins.googlesigninexample/com.google.android.gms.auth.api.signin.internal.SignInHubActivity#0
```
```
[✓] Flutter (Channel beta, v1.0.0, on Linux, locale en_US.UTF-8)
    • Flutter version 1.0.0 at /shared/user/development/flutter
    • Framework revision 5391447fae (4 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /shared/user/Android/Sdk
    • Android NDK at /shared/user/Android/Sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /shared/user/Android/Sdk
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] Android Studio (version 3.2)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] Connected device (2 available)
    • Pixel 2                   • FA79E1A07433  • android-arm64 • Android 9 (API 28)
    • Android SDK built for x86 • emulator-5554 • android-x86   • Android 9 (API 28) (emulator)

• No issues found!
```

**Comment by zoechi** [comment] 2018-12-30 15:59
I think you need to register the application in Firebase according to https://github.com/flutter/plugins/tree/master/packages/google_sign_in#android-integration

**Comment by james-lawrence** [comment] 2018-12-30 16:04
@zoechi i'm using the sample application. it seems to already have credentials in the [repository](https://github.com/flutter/plugins/tree/master/packages/google_sign_in/example/android/app).

**Comment by james-lawrence** [comment] 2018-12-30 16:11
if those credentials are invalid, then why are they included in the repository? why is the google services library not returning a useful error message about invalid credentials?

**Comment by lastlink** [comment] 2019-01-08 06:51
Is this the same as `I/flutter ( 4472): PlatformException(sign_in_failed, com.google.android.gms.common.api.ApiException: 16: , null)`?
Not having the credentials valid?

**Comment by zoechi** [comment] 2019-02-08 11:42
Please check https://github.com/flutter/flutter/issues/27599#issuecomment-461482367

**Comment by cyanglaz** [comment] 2019-04-15 23:10
@james-lawrence Did your issue resolved after registering your firebase app?

I do agree we should have better documentation on how to use example app so people won't run into the same issue again. And I also agree that if it is possible, the error message needs to be better. (Still have to look into it to see if it is provided in the firebase SDK or google sign in SDK).
If you'd like to create separate issues for these 2 separate things, you are very welcomed to do so!

**Comment by james-lawrence** [comment] 2019-04-16 13:08
@cyanglaz no, and firebase should be removed from the documentation tbh. all this needs is properly created android app credentials.

**Comment by cyanglaz** [comment] 2019-04-16 16:19
> @cyanglaz no, and firebase should be removed from the documentation tbh. all this needs is properly created android app credentials.

What do you mean by removing firebase from the documentation? What documentation?

**Comment by ayush221b** [comment] 2019-05-24 12:57
Please check : https://github.com/flutter/flutter/issues/33303

The problem is quite similar, although I have added and configured a firebase project.

**Comment by luv4ever2shail** [comment] 2019-05-30 15:48
This **12500** Error can be resolved by adding a support email address to your project in project settings. Open link https://console.firebase.google.com/

Select Your project and open settings tab.

Provide a valid support email and restart your application now.

**Comment by tlercher** [comment] 2019-07-10 19:25
For people (like me) with a project which has a valid support email but **haven't configured the OAuth consent screen** yet, it still might fail with **sign_in_failed** and code **12500**.


After configuring and saving the [Consent Screen](https://console.developers.google.com/apis/credentials/consent) it worked for me.

**Comment by cyanglaz** [comment] 2019-07-10 19:31
This issue seems to be resolved by @luv4ever2shail and @tlercher 's comments. I am closing the issue. If any related issues are still found after applying the solution, please feel free to reopen the issue or open another one with details.

**Closed by cyanglaz** 2019-07-10 19:31 UTC
Labels: p: first party, p: google_sign_in, plugin, severe: crash

**Comment by john-ravi** [comment] 2019-07-12 12:04
update flutter doc at https://pub.dev/packages/firebase_auth

**Comment by lt692** [comment] 2019-10-01 10:05
> This **12500** Error can be resolved by adding a support email address to your project in project settings. Open link https://console.firebase.google.com/
> 
> Select Your project and open settings tab.
> 
> Provide a valid support email and restart your application now.
I still get the 12500 error even if the support email is added.

**Comment by RaitonGG** [comment] 2020-07-02 13:36
> For people (like me) with a project which has a valid support email but **haven't configured the OAuth consent screen** yet, it still might fail with **sign_in_failed** and code **12500**.
> 
the consent screen appears to ask for a domain and gsuit accounts and what not. how can you do this fast and free?
