### ISSUE TITLE
Flutter downgrade command only works for last major release not for hot fixes

### ISSUE THREAD

**Issue by alihassan143** [flutter/flutter#138662] opened 2023-11-18 05:34 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

if you are on version 3.16.0 and run 
flutter downgrade v3.13.9
it show only
Downgrade flutter to version 3.13.8
not downgrade to correct versio

### Expected results

it should downgrade to that specific version

### Actual results

Downgrade flutter to version 3.13.8
it showing that 

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by danagbemava-nc** [comment] 2023-11-20 08:59
Hi @alihassan143, just to be clear, do you want to downgrade to 3.13.9 or 3.13.8?

**Comment by danagbemava-nc** [comment] 2023-11-21 07:12
Hi @alihassan143, one more thing, when you enter `flutter downgrade` you see the downgrade message and in that message it is `3.13.9` but when you confirm, it downgrades to `3.13.8`, is that what is happening?

**Comment by alihassan143** [comment] 2023-11-21 07:21
no when i enter proper version it show downgrade to 3.13.8 but i type the version 3.13.9

**Comment by danagbemava-nc** [comment] 2023-11-22 07:11
```
flutter downgrade
Downgrade flutter to version 3.13.9
? [y|n]: 
```

When I type flutter downgrade, the above is what I see. 

What do you see?

**Comment by alihassan143** [comment] 2023-11-22 07:13
no i see v 3.13.8

**Comment by danagbemava-nc** [comment] 2023-11-23 07:05
Hi @alihassan143, did you upgrade from 3.13.8 directly to 3.16.0 or did you upgrade from 3.13.9?

**Comment by alihassan143** [comment] 2023-11-23 07:07
i upgraded from 3.13.9

**Comment by alihassan143** [comment] 2023-11-23 07:08
its only happening in macos

**Comment by alihassan143** [comment] 2023-11-23 07:08
in windows its working as expected

**Comment by danagbemava-nc** [comment] 2023-11-24 08:45
Hi @alihassan143, please provide the full output of `flutter doctor -v`. 

I tested on macOS and it works as expected. I also had a colleague test on macOS and it works just fine on his end too. Seems like this is only happening on your system

**Comment by alihassan143** [comment] 2023-11-27 09:12
```
flutter doctor -v
[✓] Flutter (Channel stable, 3.16.0, on macOS 13.6 22G120 darwin-x64, locale en-US)
    • Flutter version 3.16.0 on channel stable at /Users/mac/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db7ef5bf9f (12 days ago), 2023-11-15 11:25:44 -0800
    • Engine revision 74d16627b9
    • Dart version 3.2.0
    • DevTools version 2.28.2

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/mac/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/mac/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/mac/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.13.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /Applications/Android Studio.app
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.84.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.76.0

[✓] Connected device (3 available)
    • iPhone 14 Pro Max (mobile) • 2670690D-06D3-4EB2-A080-97BB632D57C2 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)            • macos                                • darwin-x64     • macOS 13.6 22G120
      darwin-x64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome
      119.0.6045.159

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```
<img width="2" alt="Screenshot 2023-11-27 at 2 11 59 PM" src="https://github.com/flutter/flutter/assets/71745182/3165fb4c-e2f4-4688-b9c0-d6356ffd949c">

**Comment by alihassan143** [comment] 2023-11-27 09:13
<img width="2" alt="Screenshot 2023-11-27 at 2 11 59 PM" src="https://github.com/flutter/flutter/assets/71745182/4727f4ef-ab2e-48b8-a00b-aa264fa5f026">

**Comment by danagbemava-nc** [comment] 2023-11-28 06:27
Hi @alihassan143, if you do not specify the version, does it show the proper version? Can you also try this with the newest hotfix that was released?

**Comment by alihassan143** [comment] 2023-11-28 10:30
@danagbemava-nc  its only downgrading to last installed version
<img width="564" alt="Screenshot 2023-11-28 at 3 30 01 PM" src="https://github.com/flutter/flutter/assets/71745182/eb610574-f400-4832-9b7b-b264f0e997a8">

**Comment by danagbemava-nc** [comment] 2023-11-29 06:50
Hi @alihassan143, you can't downgrade to a specific version anymore. It now defaults to the last version that was released iirc. 

There's an issue tracking this feature request in https://github.com/flutter/flutter/issues/71723. 

Kindly subscribe to it for updates. 

For now, if you want to downgrade to a specific version, you should checkout the version tag from your flutter directory. 

You can find the versions by running 

```
git tag
```

in the flutter directory, then you can checkout the version you want by running 

```
git checkout <version>
```

Closing this as a duplicate of #71723

**Closed by danagbemava-nc** 2023-11-29 06:50 UTC
Labels: in triage
