### ISSUE TITLE
iOS, Android, Bloc, Firestore

### ISSUE THREAD

**Issue by andesappal** [flutter/flutter#45784] opened 2019-11-28 16:28 UTC
## Steps to Reproduce

1. Git checkout https://github.com/andesappal/flutter-bloc-firebase.git, from the https://bloclibrary.dev/#/flutterfirestoretodostutorial tutorial
2. run on the iOS simulator and Android emulator
3. get stuck on iOS https://gist.github.com/andesappal/3cd6a2f7ef145a33572e43cae6e80622
    get stuck on Android https://gist.github.com/andesappal/26562de5850c031582588b902be8de39 

**Target Platform:** iOS and Android
**Target OS version/browser:** running on macOS 10.14.6, Chrome 78.0.3904.108 (Official Build) (64-bit)
**Devices:** Problem occurs on iOS simulator and Android emulator. I have not yet targeted a physical device. 

## Logs

`flutter run --verbose`: https://gist.github.com/andesappal/c45096eee9d4cb4e8496bce571252476

```
Andes-MBP:flutter_firestore_todos johnappleseed$ flutter analyze
Analyzing flutter_firestore_todos...                                    
No issues found! (ran in 7.4s)
Andes-MBP:flutter_firestore_todos johnappleseed$ 

```

```
Andes-MBP:flutter_firestore_todos johnappleseed$ flutter doctor -v
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.14.6 18G1012, locale en-US)
    • Flutter version 1.9.1+hotfix.6 at /Users/johnappleseed/development/flutter
    • Framework revision 68587a0916 (3 months ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/johnappleseed/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

• No issues found!
Andes-MBP:flutter_firestore_todos johnappleseed$ 

```

**Comment by iapicca** [comment] 2019-11-29 08:41
Hi @andesappal 
for what I can see the issue is related to a FlutterFire plugin,
please open the issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
thank you

**Closed by iapicca** 2019-11-29 08:41 UTC
