### ISSUE TITLE
Why does CooperinoSegmentedSlidingControl perform empty processing on onLongPress?

### ISSUE THREAD

**Issue by yukitaka13-1110** [flutter/flutter#116024] opened 2022-11-25 15:10 UTC
## Steps to Reproduce
I don't understand why the ClientinoSegmentedSlidingControl performs an empty process when onLongPress.
When the user LongPresses, onValueChanged is not called.

https://github.com/flutter/flutter/blob/ff59250dbeb02dfc30095dfe024c76b7cefeefe9/packages/flutter/lib/src/cupertino/sliding_segmented_control.dart#L447-L448

**Expected results:**

`onValueChanged` is also called during onLongPress.

**Actual results:**

`onValueChanged` was not called and state was changed.

<details>
<summary>Code Example</summary>

```dart
class Test extends StatefulWidget {
  const Test({super.key});

  @override
  State<Test> createState() => _TestState();
}

class _TestState extends State<Test> {
  int _value = 0;
  @override
  Widget build(BuildContext context) {
    return CupertinoPageScaffold(
      child: SizedBox.expand(
        child: Center(
          child: CupertinoSlidingSegmentedControl(
            groupValue: _value,
            children: const {
              0: Text('0'),
              1: Text('1'),
              2: Text('2'),
            },
            onValueChanged: (value) {
              // If user LongPress, `onValueChanged` was not called but state was changed.
              // if (value != null) {
              //   setState(() {
              //     _value = value;
              //   });
              // }
            },
          ),
        ),
      ),
    );
  }
}
```

</details>

<details>
<summary>Logs</summary>
```
$ flutter doctor -v

[✓] Flutter (Channel stable, 3.3.4, on macOS 12.1 21C52 darwin-arm, locale *****)
    • Flutter version 3.3.4 on channel stable at /Users/*****/fvm/versions/3.3.4
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision eb6d86ee27 (7 weeks ago), 2022-10-04 22:31:45 -0700
    • Engine revision c08d7d5efc
    • Dart version 2.18.2
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/*****/Library/Android/sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13E500a
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] VS Code (version 1.73.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • ***
　 • ***
　 • ***

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```
</details>

**Comment by huycozy** [comment] 2022-11-28 07:00
@yukitaka13-1110 thanks for filing this issue but I can not reproduce it on the latest Flutter stable `3.3.9` and master `3.6.0` channels. `onValueChanged` is always called when long pressing on the number or on sliding `CupertinoSlidingSegmentedControl`. 

As far as I can see, you are using the old Flutter version `3.3.4`, please try upgrading Flutter SDK and retry to see if this issue still persists.

**Comment by yukitaka13-1110** [comment] 2022-11-29 00:28
@huycozy Thank you for your reply.
I installed 3.3.9 and tried it. It worked correctly as a result.
Do you know of any related issue regarding not working properly with 3.3.4? I have not found it as far as I have looked.

**Comment by huycozy** [comment] 2022-11-29 04:26
@yukitaka13-1110 thanks for your confirmation. Unfortunately, I'm not sure I can find the related PR right now. Closing the issue since it's fixed on the latest stable channel.

**Closed by huycozy** 2022-11-29 04:26 UTC
Labels: in triage
