### ISSUE TITLE
[tool_crash] FileSystemException: Failed to decode data using encoding 'utf-8', null

### ISSUE THREAD

**Issue by pumpkin1424** [flutter/flutter#123845] opened 2023-03-31 07:57 UTC
## Command
```
flutter --quiet assemble --no-version-check --depfile D:\Repos\Flutter\chat_app\build\app\intermediates\flutter\release/flutter_build.d --output D:\Repos\Flutter\chat_app\build\app\intermediates\flutter\release -dTargetFile=lib\main.dart -dTargetPlatform=android -dBuildMode=release -dTrackWidgetCreation=true -dTreeShakeIcons=true android_aot_bundle_release_android-arm android_aot_bundle_release_android-arm64 android_aot_bundle_release_android-x64
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Failed to decode data using encoding 'utf-8', null
```
#0      _File._tryDecode (dart:io/file_impl.dart:558:7)
#1      _File.readAsStringSync (dart:io/file_impl.dart:578:7)
#2      ForwardingFile.readAsStringSync (package:file/src/forwarding/forwarding_file.dart:99:16)
#3      ErrorHandlingFile.readAsStringSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:222:22)
#4      _runSync (package:flutter_tools/src/base/error_handling_io.dart:600:14)
#5      ErrorHandlingFile.readAsStringSync (package:flutter_tools/src/base/error_handling_io.dart:221:12)
#6      SourceVisitor.visitDepfile (package:flutter_tools/src/build_system/source.dart:55:37)
#7      List.forEach (dart:core-patch/growable_array.dart:416:8)
#8      Target._resolveConfiguration (package:flutter_tools/src/build_system/build_system.dart:250:14)
#9      Target.resolveInputs (package:flutter_tools/src/build_system/build_system.dart:195:12)
#10     Target._toNode (package:flutter_tools/src/build_system/build_system.dart:148:39)
#11     Target._toNode (package:flutter_tools/src/build_system/build_system.dart:155:58)
#12     Target._toNode (package:flutter_tools/src/build_system/build_system.dart:155:58)
#13     Target._toNode (package:flutter_tools/src/build_system/build_system.dart:155:58)
#14     FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:603:30)
#15     AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:337:51)
#16     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1426:12)
<asynchronous suspension>
#17     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1257:27)
<asynchronous suspension>
#18     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#19     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#20     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:283:9)
```
```
[✓] Flutter (Channel stable, 3.7.6, on Microsoft Windows [Version 10.0.19045.2728], locale en-US)
    • Flutter version 3.7.6 on channel stable at E:\flutter_windows_3.3.10-stable\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 12cb4eb7a0 (4 weeks ago), 2023-03-01 10:29:26 -0800
    • Engine revision ada363ee93
    • Dart version 2.19.3
    • DevTools version 2.20.1

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at C:\Users\Pritom\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)
    ! Some Android licenses not accepted. To resolve this, run: flutter doctor --android-licenses

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✗] Visual Studio - develop for Windows
    ✗ Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[✓] Android Studio (version 2022.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)

[✓] VS Code (version 1.77.0)
    • VS Code at C:\Users\Pritom\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.60.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19045.2728]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 111.0.5563.65
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 111.0.1661.51

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 12cb4eb7a009f52b347b62ade7cb4854b926af72
### Plugins
cloud_firestore-4.4.5
cloud_firestore_web-3.3.5
firebase_auth-4.3.0
firebase_auth_web-5.2.10
firebase_core-2.8.0
firebase_core_web-2.2.2
firebase_messaging-14.3.0
firebase_messaging_web-3.2.17
firebase_storage-11.0.16
firebase_storage_web-3.3.25
flutter_local_notifications-13.0.0
flutter_plugin_android_lifecycle-2.0.9
image_picker-0.8.7
image_picker_android-0.8.6+5
image_picker_for_web-2.1.12
image_picker_ios-0.8.7+1

**Comment by danagbemava-nc** [comment] 2023-03-31 10:15
Closing this as a duplicate of https://github.com/flutter/flutter/issues/65021. 

Kindly subscribe to the original issue for updates. 

Thank you

**Closed by danagbemava-nc** 2023-03-31 10:15 UTC
Labels: in triage
