### ISSUE TITLE
Flutter android app restarts after connecting input device (bluetooth, wired)

### ISSUE THREAD

**Issue by LampeMW** [flutter/flutter#30330] opened 2019-04-01 19:27 UTC
## Steps to Reproduce

I run my app on an Android device, and if I connect or disconnect a physical input device (in my case a bluetooth barcode scanner), the app goes white and a second later restarts to the initial login screen.  The same thing happens if I disconnect or turn off the bluetooth device. I've also tested this with a wired barcode scanner as well, and the same issue persists.

## Logs

```
[ +160 ms] Syncing files to device SM T390...
[   +2 ms] DevFS: Starting sync from LocalDirectory: '/Users/matt/Github/scanability_flutter'
[        ] Scanning project files
[   +7 ms] Scanning package files
[ +171 ms] Scanning asset files
[   +1 ms] Scanning for deleted files
[  +19 ms] Compiling dart to kernel with 576 updated files
[   +8 ms] /Users/matt/Github/flutter/bin/cache/dart-sdk/bin/dart /Users/matt/Github/flutter/bin/cache/artifacts/engine/darwin-x64/frontend_server.dart.snapshot --sdk-root /Users/matt/Github/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --incremental
--strong --target=flutter --output-dill build/app.dill --packages /Users/matt/Github/scanability_flutter/.packages --filesystem-scheme org-dartlang-root
[+1334 ms] Updating files
[ +280 ms] DevFS: Sync finished
[   +1 ms] Syncing files to device SM T390... (completed in 1,824ms)
[        ] Synced 1.0MB.
[   +8 ms] Sending to VM service: _flutter.listViews({})
[  +16 ms] Result: {type: FlutterViewList, views: [{type: FlutterView, id: _flutterView/0xe39f9f0c, isolate: {type: @Isolate, fixedId: true, id: isolates/1019719178, name: main.dart$main-1019719178, number: 1019719178}}]}
[        ] Connected to _flutterView/0xe39f9f0c.
[   +2 ms] 🔥  To hot reload changes while running, press "r". To hot restart (and rebuild state), press "R".
[   +1 ms] An Observatory debugger and profiler on SM T390 is available at: http://127.0.0.1:62976/
[        ] For a more detailed help message, press "h". To detach, press "d"; to quit, press "q".
[ +506 ms] D/libGLESv2( 8434): STS_GLApi : DTS, ODTC are not allowed for Package : com.erpsuites.Scanability
[+2278 ms] D/ViewRootImpl@b35c8d[MainActivity]( 8434): ViewPostIme pointer 0
[  +58 ms] D/ViewRootImpl@b35c8d[MainActivity]( 8434): ViewPostIme pointer 1
[+22605 ms] D/SurfaceView( 8434): windowStopped(true) false e53de53 of ViewRootImpl@b35c8d[MainActivity]
[        ] D/SurfaceView( 8434): BG show() Surface(name=Background for - SurfaceView - com.erpsuites.Scanability/com.erpsuites.Scanability.MainActivity@e53de53@0) io.flutter.view.FlutterView{e53de53 VFE...... .F...... 0,0-800,1280}
[        ] D/SurfaceView( 8434): surfaceDestroyed 1 #1 io.flutter.view.FlutterView{e53de53 VFE...... .F...... 0,0-800,1280}
[  +27 ms] D/SurfaceView( 8434): onWindowVisibilityChanged(8) false e53de53 of ViewRootImpl@b35c8d[MainActivity]
[        ] D/SurfaceView( 8434): BG show() Surface(name=Background for - SurfaceView - com.erpsuites.Scanability/com.erpsuites.Scanability.MainActivity@e53de53@0) io.flutter.view.FlutterView{e53de53 VFE...... .F...... 0,0-800,1280}
[   +1 ms] D/SurfaceView( 8434): BG destroy() Surface(name=Background for - SurfaceView - com.erpsuites.Scanability/com.erpsuites.Scanability.MainActivity@e53de53@0) io.flutter.view.FlutterView{e53de53 VFE...... .F...... 0,0-800,1280}
[   +7 ms] D/OpenGLRenderer( 8434): eglDestroySurface = 0xe8d8ac48, 0xd0ae6800
[        ] D/ViewRootImpl@b35c8d[MainActivity]( 8434): dispatchDetachedFromWindow
[        ] D/InputEventReceiver( 8434): channel 'e1763ac com.erpsuites.Scanability/com.erpsuites.Scanability.MainActivity (client)' ~ Disposing input event receiver.
[        ] D/InputEventReceiver( 8434): channel 'e1763ac com.erpsuites.Scanability/com.erpsuites.Scanability.MainActivity (client)' ~NativeInputEventReceiver.
[  +11 ms] D/InputTransport( 8434): Input channel destroyed: fd=77
[ +172 ms] D/InputTransport( 8434): Input channel constructed: fd=80
[        ] D/ViewRootImpl@cad274a[MainActivity]( 8434): setView = DecorView@4ee76bb[MainActivity] TM=true MM=false
[  +10 ms] D/SurfaceView( 8434): onWindowVisibilityChanged(0) true 157b7d8 of ViewRootImpl@cad274a[MainActivity]
[        ] D/ViewRootImpl@cad274a[MainActivity]( 8434): dispatchAttachedToWindow
[  +21 ms] V/Surface ( 8434): sf_framedrop debug : 0x4f4c, game : false, logging : 0
[   +2 ms] D/ViewRootImpl@cad274a[MainActivity]( 8434): Relayout returned: old=[0,0][0,0] new=[0,0][800,1280] result=0x7 surface={valid=true 3436703744} changed=true
[   +2 ms] D/mali_winsys( 8434): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, egl_color_buffer_format *, EGLBoolean) returns 0x3000,  [800x1280]-format:1
[        ] D/OpenGLRenderer( 8434): eglCreateWindowSurface = 0xe8d8ab08, 0xccd7f008
[   +9 ms] D/SurfaceView( 8434): BG show() Surface(name=Background for - SurfaceView - com.erpsuites.Scanability/com.erpsuites.Scanability.MainActivity@157b7d8@0) io.flutter.view.FlutterView{157b7d8 VFE...... .F....ID 0,0-800,1280}
[   +3 ms] V/Surface ( 8434): sf_framedrop debug : 0x4f4c, game : false, logging : 0
[        ] D/SurfaceView( 8434): surfaceCreated 1 #8 io.flutter.view.FlutterView{157b7d8 VFE...... .F....ID 0,0-800,1280}
[   +2 ms] D/mali_winsys( 8434): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, egl_color_buffer_format *, EGLBoolean) returns 0x3000,  [800x1280]-format:1
[ +316 ms] D/SurfaceView( 8434): surfaceChanged (800,1280) 1 #8 io.flutter.view.FlutterView{157b7d8 VFE...... .F....ID 0,0-800,1280}
[        ] E/ViewRootImpl( 8434): sendUserActionEvent() returned.
[  +14 ms] D/ViewRootImpl@cad274a[MainActivity]( 8434): Relayout returned: old=[0,0][800,1280] new=[0,0][800,1280] result=0x3 surface={valid=true 3436703744} changed=false
[  +12 ms] D/ViewRootImpl@cad274a[MainActivity]( 8434): MSG_RESIZED_REPORT: frame=Rect(0, 0 - 800, 1280) ci=Rect(0, 32 - 0, 0) vi=Rect(0, 32 - 0, 0) or=1
[   +1 ms] D/ViewRootImpl@cad274a[MainActivity]( 8434): MSG_WINDOW_FOCUS_CHANGED 1
[  +14 ms] V/InputMethodManager( 8434): Starting input: tba=android.view.inputmethod.EditorInfo@c1e6e16 nm : com.erpsuites.Scanability ic=null
[        ] D/InputMethodManager( 8434): startInputInner - Id : 0
[        ] I/InputMethodManager( 8434): startInputInner - mService.startInputOrWindowGainedFocus
[  +19 ms] D/InputTransport( 8434): Input channel constructed: fd=89
[        ] D/InputTransport( 8434): Input channel destroyed: fd=86
```

```
❯ flutter analyze
Analyzing scanability_flutter...
No issues found! (ran in 10.0s)
```

```
❯ flutter doctor -v
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.2 18C54, locale en-US)
    • Flutter version 1.2.1 at /Users/matt/Github/flutter
    • Framework revision 8661d8aecd (7 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/matt/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.3.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.31.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.24.0

[✓] Connected device (1 available)
    • SM T390 • 520099974332b511 • android-arm • Android 8.1.0 (API 27)

• No issues found!
```

**Comment by escamoteur** [comment] 2019-09-25 09:58
Hi, just want to check if this is still a problem for you.

**Comment by LampeMW** [comment] 2019-09-25 13:33
If I am using the master branch it is not a problem. I'm not sure how safe it is to use the master branch on a customer facing application so I was hoping to track down which commit contained the fix and wait until it has been merged to a safer branch.  I don't think there's anything else required of you though so you can close this.

**Comment by escamoteur** [comment] 2019-09-25 14:09
You could also try dev instead. I'm always on master. if nothing happens while testing you should be quite safe. (Just my, not the opinion of the Flutter team).

**Comment by LampeMW** [comment] 2019-10-07 17:20
Hi @escamoteur, when I replied last week that this was resolved, I got this issue mixed up with another you were working with me on.  This issue is still happening to me no matter which branch I am on.  My apologies, could you please re-open this one?

**Comment by escamoteur** [comment] 2019-10-23 15:43
@LampeMW could you please your current `flutter doctor -v` output

**Comment by escamoteur** [comment] 2019-10-30 18:06
I added the additional triage because I'm not sure if that is a sign for a more severe problem.

**Comment by darshankawar** [comment] 2020-09-18 13:01
Hi @LampeMW,
I wanted to retest this on latest Flutter stable version (1.20.4) to see if the issue still exists, but since I don't have a bluetooth enabled wired device to replicate the scenario, I am unable to test this.
Could you confirm if this is still a valid issue ?
If so, can you provide latest `flutter doctor -v` and a minimal complete reproducible code sample that shows the issue ?
Thanks.

**Comment by LampeMW** [comment] 2020-09-18 13:07
@darshankawar, sorry I forgot to update this issue sooner.  This has been fixed now with one of the version updates to the Stable branch.  Thanks!

**Comment by darshankawar** [comment] 2020-09-18 13:24
@LampeMW Thanks for quick response and am glad that it's fixed.
I am going ahead and closing it as fixed. If you disagree, write in comments and I'll reopen.
Thanks.

**Closed by darshankawar** 2020-09-18 13:24 UTC
Labels: P4, a: text input, engine, framework, platform-android, severe: crash
