### ISSUE TITLE
[web][ios-safari] unskip path unit tests

### ISSUE THREAD

**Issue by nturgut** [flutter/flutter#60040] opened 2020-06-23 00:33 UTC
canvaskit path_metric_tests were failing on iOS. Skip is added to the group for iOS. (Tests are done in iOS 13, IPhone 11)

~~https://github.com/flutter/engine/blob/master/lib/web_ui/test/canvaskit/path_metrics_test.dart~~

```
ReferenceError: Can't find variable: WebAssembly
  org-dartlang-sdk:///lib/_internal/js_runtime/lib/js_patch.dart 68:11      JsObject.JsObject
  ../../packages/ui/src/engine/compositor/initialization.dart 31:12         call
  org-dartlang-sdk:///lib/html/dart2js/html_dart2js.dart 37188:40           call
  ../../packages/stack_trace/src/stack_zone_specification.dart 129:25       call
  ../../packages/stack_trace/src/stack_zone_specification.dart 209:14       _run
  ../../packages/stack_trace/src/stack_zone_specification.dart 129:14       call
  org-dartlang-sdk:///lib/async/zone.dart 1206:12                           _rootRunUnary
  org-dartlang-sdk:///lib/async/zone.dart 1099:34                           runUnary
  org-dartlang-sdk:///lib/async/zone.dart 1005:7                            runUnaryGuarded
  org-dartlang-sdk:///lib/async/zone.dart 1042:26                           call
  org-dartlang-sdk:///lib/_internal/js_runtime/lib/js_helper.dart 2020:14   invokeClosure
  org-dartlang-sdk:///lib/_internal/js_runtime/lib/js_helper.dart 2052:1    <fn>
  ===== asynchronous gap ===========================
  org-dartlang-sdk:///lib/async/zone.dart 1041:22                           bindUnaryCallbackGuarded
  org-dartlang-sdk:///lib/html/dart2js/html_dart2js.dart 40668:3            _wrapZone
  org-dartlang-sdk:///lib/html/dart2js/html_dart2js.dart 37188:15            
  ../../packages/ui/src/engine/compositor/initialization.dart 25:3          initializeSkia
  ../../packages/ui/src/ui/initialization.dart 34:11                        <fn>
  org-dartlang-sdk:///lib/_internal/js_runtime/lib/async_patch.dart 315:19  <fn>
  org-dartlang-sdk:///lib/_internal/js_runtime/lib/async_patch.dart 340:23  call
  ../../packages/stack_trace/src/stack_zone_specification.dart 141:25       call
  ../../packages/stack_trace/src/stack_zone_specification.dart 209:14       _run
  ../../packages/stack_trace/src/stack_zone_specification.dart 141:14       call
  org-dartlang-sdk:///lib/_internal/js_runtime/lib/async_patch.dart 245:3   _asyncStartSync
  ../../packages/ui/src/ui/initialization.dart 25:3                         _initializePlatform
  ../../packages/ui/src/ui/initialization.dart 12:45                        webOnlyInitializePlatform
  path_metrics_test.dart 13:11                                              <fn>
  org-dartlang-sdk:///lib/_internal/js_runtime/lib/async_patch.dart 315:19  <fn>
  org-dartlang-sdk:///lib/_internal/js_runtime/lib/async_patch.dart 340:23  call
  ../../packages/stack_trace/src/stack_zone_specification.dart 141:25       call
  ../../packages/stack_trace/src/stack_zone_specification.dart 209:14       _run
  ../../packages/stack_trace/src/stack_zone_specification.dart 141:14       call
  org-dartlang-sdk:///lib/_internal/js_runtime/lib/async_patch.dart 245:3   _asyncStartSync
  path_metrics_test.dart 13:41                                              call
  ../../packages/test_api/src/backend/declarer.dart 305:67                  call
  org-dartlang-sdk:///lib/async/future.dart 508:20                          call
  org-dartlang-sdk:///lib/async/future.dart 550:20                          call
  ../../packages/stack_trace/src/stack_zone_specification.dart 129:25       call
  ../../packages/stack_trace/src/stack_zone_specification.dart 209:14       _run
  ../../packages/stack_trace/src/stack_zone_specification.dart 129:14       call
  org-dartlang-sdk:///lib/async/zone.dart 1198:46                           _rootRunUnary
  org-dartlang-sdk:///lib/async/zone.dart 1099:34                           runUnary
  org-dartlang-sdk:///lib/async/zone.dart 1005:7                            runUnaryGuarded
  org-dartlang-sdk:///lib/async/zone.dart 1042:26                           call
  org-dartlang-sdk:///lib/async/future.dart 566:18                          Future.doWhile
  org-dartlang-sdk:///lib/async/future.dart 506:12                          Future.forEach
  ../../packages/test_api/src/backend/declarer.dart 305:29                  call
  org-dartlang-sdk:///lib/async/zone.dart 1190:12                           _rootRun
  org-dartlang-sdk:///lib/async/zone.dart 1092:34                           run
  org-dartlang-sdk:///lib/async/zone.dart 1630:10                           _runZoned
  org-dartlang-sdk:///lib/async/zone.dart 1550:10                           runZoned
  ../../packages/test_api/src/backend/declarer.dart 305:7                   call
  ../../packages/test_api/src/backend/invoker.dart 400:19                   <fn>
  org-dartlang-sdk:///lib/_internal/js_runtime/lib/async_patch.dart 315:19  <fn>
  org-dartlang-sdk:///lib/_internal/js_runtime/lib/async_patch.dart 340:23  call
  ../../packages/stack_trace/src/stack_zone_specification.dart 141:25       call
  ../../packages/stack_trace/src/stack_zone_specification.dart 209:14       _run
  ../../packages/stack_trace/src/stack_zone_specification.dart 141:14       call
  org-dartlang-sdk:///lib/_internal/js_runtime/lib/async_patch.dart 245:3   _asyncStartSync
  ../../packages/test_api/src/backend/invoker.dart 400:32                   call
  org-dartlang-sdk:///lib/async/future.dart 175:26                          call
  ../../packages/stack_trace/src/stack_zone_specification.dart 209:14       _run
  ../../packages/stack_trace/src/stack_zone_specification.dart 119:48       call
  org-dartlang-sdk:///lib/async/zone.dart 1182:46                           _rootRun
  org-dartlang-sdk:///lib/async/zone.dart 1092:34                           run
  org-dartlang-sdk:///lib/async/zone.dart 997:7                             runGuarded
  org-dartlang-sdk:///lib/async/zone.dart 1037:23                           call
  ../../packages/stack_trace/src/stack_zone_specification.dart 209:14       _run
  ../../packages/stack_trace/src/stack_zone_specification.dart 119:48       call
  org-dartlang-sdk:///lib/async/zone.dart 1190:12                           _rootRun
  org-dartlang-sdk:///lib/async/zone.dart 1092:34                           run
  org-dartlang-sdk:///lib/async/zone.dart 1021:23                           call
  org-dartlang-sdk:///lib/_internal/js_runtime/lib/async_patch.dart 131:9   call
  org-dartlang-sdk:///lib/_internal/js_runtime/lib/js_helper.dart 2018:14   invokeClosure
  org-dartlang-sdk:///lib/_internal/js_runtime/lib/js_helper.dart 2052:1    <fn>
  ===== asynchronous gap ===========================
  org-dartlang-sdk:///lib/async/zone.dart 345:30                            _wrapJsFunctionForAsync
  ../../packages/ui/src/ui/initialization.dart 12:45                        webOnlyInitializePlatform
  path_metrics_test.dart 13:11                                              <fn>
  org-dartlang-sdk:///lib/_internal/js_runtime/lib/async_patch.dart 315:19  <fn>
  org-dartlang-sdk:///lib/_internal/js_runtime/lib/async_patch.dart 340:23  call
  ../../packages/stack_trace/src/stack_zone_specification.dart 141:25       call
  ../../packages/stack_trace/src/stack_zone_specification.dart 209:14       _run
  ../../packages/stack_trace/src/stack_zone_specification.dart 141:14       call
  org-dartlang-sdk:///lib/_internal/js_runtime/lib/async_patch.dart 245:3   _asyncStartSync
  path_metrics_test.dart 13:41                                              call
  ../../packages/test_api/src/backend/declarer.dart 305:67                  call
  org-dartlang-sdk:///lib/async/future.dart 508:20                          call
  org-dartlang-sdk:///lib/async/future.dart 550:20                          call
  ../../packages/stack_trace/src/stack_zone_specification.dart 129:25       call
  ../../packages/stack_trace/src/stack_zone_specification.dart 209:14       _run
  ../../packages/stack_trace/src/stack_zone_specification.dart 129:14       call
  org-dartlang-sdk:///lib/async/zone.dart 1198:46                           _rootRunUnary
  org-dartlang-sdk:///lib/async/zone.dart 1099:34                           runUnary
  org-dartlang-sdk:///lib/async/zone.dart 1005:7                            runUnaryGuarded
  org-dartlang-sdk:///lib/async/zone.dart 1042:26                           call
  org-dartlang-sdk:///lib/async/future.dart 566:18                          Future.doWhile
  org-dartlang-sdk:///lib/async/future.dart 506:12                          Future.forEach
  ../../packages/test_api/src/backend/declarer.dart 305:29                  call
  org-dartlang-sdk:///lib/async/zone.dart 1190:12                           _rootRun
  org-dartlang-sdk:///lib/async/zone.dart 1092:34                           run
  org-dartlang-sdk:///lib/async/zone.dart 1630:10                           _runZoned
  org-dartlang-sdk:///lib/async/zone.dart 1550:10                           runZoned
  ../../packages/test_api/src/backend/declarer.dart 305:7                   call
  ../../packages/test_api/src/backend/invoker.dart 400:19                   <fn>
  org-dartlang-sdk:///lib/_internal/js_runtime/lib/async_patch.dart 315:19  <fn>
  org-dartlang-sdk:///lib/_internal/js_runtime/lib/async_patch.dart 340:23  call
  ../../packages/stack_trace/src/stack_zone_specification.dart 141:25       call
  ../../packages/stack_trace/src/stack_zone_specification.dart 209:14       _run
  ../../packages/stack_trace/src/stack_zone_specification.dart 141:14       call
  org-dartlang-sdk:///lib/_internal/js_runtime/lib/async_patch.dart 245:3   _asyncStartSync
  ../../packages/test_api/src/backend/invoker.dart 400:32                   call
  org-dartlang-sdk:///lib/async/future.dart 175:26                          call
  ../../packages/stack_trace/src/stack_zone_specification.dart 209:14       _run
  ../../packages/stack_trace/src/stack_zone_specification.dart 119:48       call
  org-dartlang-sdk:///lib/async/zone.dart 1182:46                           _rootRun
  org-dartlang-sdk:///lib/async/zone.dart 1092:34                           run
  org-dartlang-sdk:///lib/async/zone.dart 997:7                             runGuarded
  org-dartlang-sdk:///lib/async/zone.dart 1037:23                           call
  ../../packages/stack_trace/src/stack_zone_specification.dart 209:14       _run
  ../../packages/stack_trace/src/stack_zone_specification.dart 119:48       call
  org-dartlang-sdk:///lib/async/zone.dart 1190:12                           _rootRun
  org-dartlang-sdk:///lib/async/zone.dart 1092:34                           run
  org-dartlang-sdk:///lib/async/zone.dart 1021:23                           call
  org-dartlang-sdk:///lib/_internal/js_runtime/lib/async_patch.dart 131:9   call
  org-dartlang-sdk:///lib/_internal/js_runtime/lib/js_helper.dart 2018:14   invokeClosure
  org-dartlang-sdk:///lib/_internal/js_runtime/lib/js_helper.dart 2052:1    <fn>
  ===== asynchronous gap ===========================
  org-dartlang-sdk:///lib/async/zone.dart 345:30                            _wrapJsFunctionForAsync
  ../../packages/test_api/src/backend/declarer.dart 305:67                  call
  org-dartlang-sdk:///lib/async/future.dart 508:20                          call
  org-dartlang-sdk:///lib/async/future.dart 550:20                          call
  ../../packages/stack_trace/src/stack_zone_specification.dart 129:25       call
  ../../packages/stack_trace/src/stack_zone_specification.dart 209:14       _run
  ../../packages/stack_trace/src/stack_zone_specification.dart 129:14       call
  org-dartlang-sdk:///lib/async/zone.dart 1198:46                           _rootRunUnary
  org-dartlang-sdk:///lib/async/zone.dart 1099:34                           runUnary
  org-dartlang-sdk:///lib/async/zone.dart 1005:7                            runUnaryGuarded
  org-dartlang-sdk:///lib/async/zone.dart 1042:26                           call
  org-dartlang-sdk:///lib/async/future.dart 566:18                          Future.doWhile
  org-dartlang-sdk:///lib/async/future.dart 506:12                          Future.forEach
  ../../packages/test_api/src/backend/declarer.dart 305:29                  call
  org-dartlang-sdk:///lib/async/zone.dart 1190:12                           _rootRun
  org-dartlang-sdk:///lib/async/zone.dart 1092:34                           run
  org-dartlang-sdk:///lib/async/zone.dart 1630:10                           _runZoned
  org-dartlang-sdk:///lib/async/zone.dart 1550:10                           runZoned
  ../../packages/test_api/src/backend/declarer.dart 305:7                   call
  ../../packages/test_api/src/backend/invoker.dart 400:19                   <fn>
  org-dartlang-sdk:///lib/_internal/js_runtime/lib/async_patch.dart 315:19  <fn>
  org-dartlang-sdk:///lib/_internal/js_runtime/lib/async_patch.dart 340:23  call
  ../../packages/stack_trace/src/stack_zone_specification.dart 141:25       call
  ../../packages/stack_trace/src/stack_zone_specification.dart 209:14       _run
  ../../packages/stack_trace/src/stack_zone_specification.dart 141:14       call
  org-dartlang-sdk:///lib/_internal/js_runtime/lib/async_patch.dart 245:3   _asyncStartSync
  ../../packages/test_api/src/backend/invoker.dart 400:32                   call
  org-dartlang-sdk:///lib/async/future.dart 175:26                          call
  ../../packages/stack_trace/src/stack_zone_specification.dart 209:14       _run
  ../../packages/stack_trace/src/stack_zone_specification.dart 119:48       call
  org-dartlang-sdk:///lib/async/zone.dart 1182:46                           _rootRun
  org-dartlang-sdk:///lib/async/zone.dart 1092:34                           run
  org-dartlang-sdk:///lib/async/zone.dart 997:7                             runGuarded
  org-dartlang-sdk:///lib/async/zone.dart 1037:23                           call
  ../../packages/stack_trace/src/stack_zone_specification.dart 209:14       _run
  ../../packages/stack_trace/src/stack_zone_specification.dart 119:48       call
  org-dartlang-sdk:///lib/async/zone.dart 1190:12                           _rootRun
  org-dartlang-sdk:///lib/async/zone.dart 1092:34                           run
  org-dartlang-sdk:///lib/async/zone.dart 1021:23                           call
  org-dartlang-sdk:///lib/_internal/js_runtime/lib/async_patch.dart 131:9   call
  org-dartlang-sdk:///lib/_internal/js_runtime/lib/js_helper.dart 2018:14   invokeClosure
  org-dartlang-sdk:///lib/_internal/js_runtime/lib/js_helper.dart 2052:1    <fn>
  ===== asynchronous gap ===========================
  org-dartlang-sdk:///lib/async/zone.dart 1041:22                           bindUnaryCallbackGuarded
  org-dartlang-sdk:///lib/async/future.dart 546:26                          Future.doWhile
  org-dartlang-sdk:///lib/async/future.dart 506:12                          Future.forEach
  ../../packages/test_api/src/backend/declarer.dart 305:29                  call
  org-dartlang-sdk:///lib/async/zone.dart 1190:12                           _rootRun
  org-dartlang-sdk:///lib/async/zone.dart 1092:34                           run
  org-dartlang-sdk:///lib/async/zone.dart 1630:10                           _runZoned
  org-dartlang-sdk:///lib/async/zone.dart 1550:10                           runZoned
  ../../packages/test_api/src/backend/declarer.dart 305:7                   call
  ../../packages/test_api/src/backend/invoker.dart 400:19                   <fn>
  org-dartlang-sdk:///lib/_internal/js_runtime/lib/async_patch.dart 315:19  <fn>
  org-dartlang-sdk:///lib/_internal/js_runtime/lib/async_patch.dart 340:23  call
  ../../packages/stack_trace/src/stack_zone_specification.dart 141:25       call
  ../../packages/stack_trace/src/stack_zone_specification.dart 209:14       _run
  ../../packages/stack_trace/src/stack_zone_specification.dart 141:14       call
  org-dartlang-sdk:///lib/_internal/js_runtime/lib/async_patch.dart 245:3   _asyncStartSync
  ../../packages/test_api/src/backend/invoker.dart 400:32                   call
  org-dartlang-sdk:///lib/async/future.dart 175:26                          call
  ../../packages/stack_trace/src/stack_zone_specification.dart 209:14       _run
  ../../packages/stack_trace/src/stack_zone_specification.dart 119:48       call
  org-dartlang-sdk:///lib/async/zone.dart 1182:46                           _rootRun
  org-dartlang-sdk:///lib/async/zone.dart 1092:34                           run
  org-dartlang-sdk:///lib/async/zone.dart 997:7                             runGuarded
  org-dartlang-sdk:///lib/async/zone.dart 1037:23                           call
  ../../packages/stack_trace/src/stack_zone_specification.dart 209:14       _run
  ../../packages/stack_trace/src/stack_zone_specification.dart 119:48       call
  org-dartlang-sdk:///lib/async/zone.dart 1190:12                           _rootRun
  org-dartlang-sdk:///lib/async/zone.dart 1092:34                           run
  org-dartlang-sdk:///lib/async/zone.dart 1021:23                           call
  org-dartlang-sdk:///lib/_internal/js_runtime/lib/async_patch.dart 131:9   call
  org-dartlang-sdk:///lib/_internal/js_runtime/lib/js_helper.dart 2018:14   invokeClosure
  org-dartlang-sdk:///lib/_internal/js_runtime/lib/js_helper.dart 2052:1    <fn>
  ===== asynchronous gap ===========================
  org-dartlang-sdk:///lib/async/zone.dart 345:30                            _wrapJsFunctionForAsync
  org-dartlang-sdk:///lib/async/future.dart 175:26                          call
  ../../packages/stack_trace/src/stack_zone_specification.dart 209:14       _run
  ../../packages/stack_trace/src/stack_zone_specification.dart 119:48       call
  org-dartlang-sdk:///lib/async/zone.dart 1182:46                           _rootRun
  org-dartlang-sdk:///lib/async/zone.dart 1092:34                           run
  org-dartlang-sdk:///lib/async/zone.dart 997:7                             runGuarded
  org-dartlang-sdk:///lib/async/zone.dart 1037:23                           call
  ../../packages/stack_trace/src/stack_zone_specification.dart 209:14       _run
  ../../packages/stack_trace/src/stack_zone_specification.dart 119:48       call
  org-dartlang-sdk:///lib/async/zone.dart 1190:12                           _rootRun
  org-dartlang-sdk:///lib/async/zone.dart 1092:34                           run
  org-dartlang-sdk:///lib/async/zone.dart 1021:23                           call
  org-dartlang-sdk:///lib/_internal/js_runtime/lib/async_patch.dart 131:9   call
  org-dartlang-sdk:///lib/_internal/js_runtime/lib/js_helper.dart 2018:14   invokeClosure
  org-dartlang-sdk:///lib/_internal/js_runtime/lib/js_helper.dart 2052:1    <fn>
  ===== asynchronous gap ===========================
  org-dartlang-sdk:///lib/async/zone.dart 1036:22                           bindCallbackGuarded
  org-dartlang-sdk:///lib/async/timer.dart 52:37                            Timer.Timer
  org-dartlang-sdk:///lib/async/timer.dart 89:9                             Future.Future
  ../../packages/test_api/src/backend/invoker.dart 399:21                   <fn>
  org-dartlang-sdk:///lib/_internal/js_runtime/lib/async_patch.dart 315:19  <fn>
  org-dartlang-sdk:///lib/_internal/js_runtime/lib/async_patch.dart 340:23  call
  ../../packages/stack_trace/src/stack_zone_specification.dart 141:25       call
  ../../packages/stack_trace/src/stack_zone_specification.dart 209:14       _run
  ../../packages/stack_trace/src/stack_zone_specification.dart 141:14       call
  org-dartlang-sdk:///lib/_internal/js_runtime/lib/async_patch.dart 245:3   _asyncStartSync
  ../../packages/test_api/src/backend/invoker.dart 388:38                   call
  org-dartlang-sdk:///lib/async/zone.dart 1190:12                           _rootRun
  org-dartlang-sdk:///lib/async/zone.dart 1092:34                           run
  org-dartlang-sdk:///lib/async/zone.dart 1630:10                           _runZoned
  org-dartlang-sdk:///lib/async/zone.dart 1550:10                           runZoned
  ../../packages/test_api/src/backend/invoker.dart 387:9                    call
  ../../packages/test_api/src/backend/invoker.dart 438:7                    call
  ../../packages/stack_trace/src/chain.dart 101:16                          call
  org-dartlang-sdk:///lib/async/zone.dart 1190:12                           _rootRun
  org-dartlang-sdk:///lib/async/zone.dart 1092:34                           run
  org-dartlang-sdk:///lib/async/zone.dart 1630:10                           _runZoned
  org-dartlang-sdk:///lib/async/zone.dart 1550:10                           runZoned
  ../../packages/stack_trace/src/chain.dart 99:5                            Chain.capture
  ../../packages/test_api/src/backend/invoker.dart 385:11                   _onRun
  ../../packages/test_api/src/backend/live_test_controller.dart 197:5       _run
  ../../packages/test_api/src/remote_listener.dart 263:7                    call
  org-dartlang-sdk:///lib/async/zone.dart 1190:12                           _rootRun
  org-dartlang-sdk:///lib/async/zone.dart 1092:34                           run
  org-dartlang-sdk:///lib/async/zone.dart 1630:10                           _runZoned
  org-dartlang-sdk:///lib/async/zone.dart 1550:10                           runZoned
  ../../packages/test_api/src/remote_listener.dart 262:5                    _runLiveTest
  org-dartlang-sdk:///lib/async/zone.dart 1198:46                           _rootRunUnary
  org-dartlang-sdk:///lib/async/zone.dart 1099:34                           runUnary
  org-dartlang-sdk:///lib/async/zone.dart 1005:7                            runUnaryGuarded
  org-dartlang-sdk:///lib/async/stream_impl.dart 357:5                      _sendData
  org-dartlang-sdk:///lib/async/stream_impl.dart 285:7                      _add
  org-dartlang-sdk:///lib/async/stream_controller.dart 811:19               _sendData
  org-dartlang-sdk:///lib/async/stream_controller.dart 682:7                _add
  org-dartlang-sdk:///lib/async/stream_controller.dart 624:5                add
  org-dartlang-sdk:///lib/async/zone.dart 1206:12                           _rootRunUnary
  org-dartlang-sdk:///lib/async/zone.dart 1099:34                           runUnary
  org-dartlang-sdk:///lib/async/zone.dart 1005:7                            runUnaryGuarded
  org-dartlang-sdk:///lib/async/stream_impl.dart 357:5                      _sendData
  org-dartlang-sdk:///lib/async/stream_impl.dart 285:7                      _add
  org-dartlang-sdk:///lib/async/stream_controller.dart 811:19               _sendData
  org-dartlang-sdk:///lib/async/stream_controller.dart 682:7                _add
  org-dartlang-sdk:///lib/async/stream_controller.dart 624:5                add
  org-dartlang-sdk:///lib/async/stream_controller.dart 903:5                add
  ../../packages/stream_channel/src/guarantee_channel.dart 19:29            call
  org-dartlang-sdk:///lib/async/zone.dart 1384:9                            runUnaryGuarded
  org-dartlang-sdk:///lib/async/stream_impl.dart 357:5                      _sendData
  org-dartlang-sdk:///lib/async/stream_impl.dart 285:7                      _add
  org-dartlang-sdk:///lib/async/stream_controller.dart 811:19               _sendData
  org-dartlang-sdk:///lib/async/stream_controller.dart 682:7                _add
  org-dartlang-sdk:///lib/async/stream_controller.dart 624:5                add
  org-dartlang-sdk:///lib/async/zone.dart 1384:9                            runUnaryGuarded
  org-dartlang-sdk:///lib/async/stream_impl.dart 357:5                      _sendData
  org-dartlang-sdk:///lib/async/stream_impl.dart 285:7                      _add
  org-dartlang-sdk:///lib/async/stream_controller.dart 811:19               _sendData
  org-dartlang-sdk:///lib/async/stream_controller.dart 682:7                _add
  org-dartlang-sdk:///lib/async/stream_controller.dart 624:5                add
  org-dartlang-sdk:///lib/async/stream_controller.dart 903:5                add
  org-dartlang-sdk:///lib/async/zone.dart 1384:9                            runUnaryGuarded
  org-dartlang-sdk:///lib/async/stream_impl.dart 357:5                      _sendData
  org-dartlang-sdk:///lib/async/stream_impl.dart 285:7                      _add
  org-dartlang-sdk:///lib/async/stream_controller.dart 811:19               _sendData
  org-dartlang-sdk:///lib/async/stream_controller.dart 682:7                _add
  org-dartlang-sdk:///lib/async/stream_controller.dart 624:5                add
  org-dartlang-sdk:///lib/async/zone.dart 1384:9                            runUnaryGuarded
  org-dartlang-sdk:///lib/async/stream_impl.dart 357:5                      _sendData
  org-dartlang-sdk:///lib/async/stream_impl.dart 285:7                      _add
  org-dartlang-sdk:///lib/async/stream_controller.dart 811:19               _sendData
  org-dartlang-sdk:///lib/async/stream_controller.dart 682:7                _add
  org-dartlang-sdk:///lib/async/stream_controller.dart 624:5                add
  org-dartlang-sdk:///lib/async/stream_controller.dart 903:5                add
  ../../packages/stream_channel/src/guarantee_channel.dart 19:29            call
  org-dartlang-sdk:///lib/html/dart2js/html_dart2js.dart 37188:40           call
  org-dartlang-sdk:///lib/_internal/js_runtime/lib/js_helper.dart 2020:14   invokeClosure
  org-dartlang-sdk:///lib/_internal/js_runtime/lib/js_helper.dart 2052:1    <fn>
  ===== asynchronous gap ===========================
  org-dartlang-sdk:///lib/async/zone.dart 345:30                            _wrapJsFunctionForAsync
  org-dartlang-sdk:///lib/async/zone.dart 1190:12                           _rootRun
  org-dartlang-sdk:///lib/async/zone.dart 1092:34                           run
  org-dartlang-sdk:///lib/async/zone.dart 1630:10                           _runZoned
  org-dartlang-sdk:///lib/async/zone.dart 1550:10                           runZoned
  ../../packages/test_api/src/backend/invoker.dart 387:9                    call
  ../../packages/test_api/src/backend/invoker.dart 438:7                    call
  ../../packages/stack_trace/src/chain.dart 101:16                          call
  org-dartlang-sdk:///lib/async/zone.dart 1190:12                           _rootRun
  org-dartlang-sdk:///lib/async/zone.dart 1092:34                           run
  org-dartlang-sdk:///lib/async/zone.dart 1630:10                           _runZoned
  org-dartlang-sdk:///lib/async/zone.dart 1550:10                           runZoned
  ../../packages/stack_trace/src/chain.dart 99:5                            Chain.capture
  ../../packages/test_api/src/backend/invoker.dart 385:11                   _onRun
  ../../packages/test_api/src/backend/live_test_controller.dart 197:5       _run
  ../../packages/test_api/src/remote_listener.dart 263:7                    call
  org-dartlang-sdk:///lib/async/zone.dart 1190:12                           _rootRun
  org-dartlang-sdk:///lib/async/zone.dart 1092:34                           run
  org-dartlang-sdk:///lib/async/zone.dart 1630:10                           _runZoned
  org-dartlang-sdk:///lib/async/zone.dart 1550:10                           runZoned
  ../../packages/test_api/src/remote_listener.dart 262:5                    _runLiveTest
  org-dartlang-sdk:///lib/async/zone.dart 1198:46                           _rootRunUnary
  org-dartlang-sdk:///lib/async/zone.dart 1099:34                           runUnary
  org-dartlang-sdk:///lib/async/zone.dart 1005:7                            runUnaryGuarded
  org-dartlang-sdk:///lib/async/stream_impl.dart 357:5                      _sendData
  org-dartlang-sdk:///lib/async/stream_impl.dart 285:7                      _add
  org-dartlang-sdk:///lib/async/stream_controller.dart 811:19               _sendData
  org-dartlang-sdk:///lib/async/stream_controller.dart 682:7                _add
  org-dartlang-sdk:///lib/async/stream_controller.dart 624:5                add
  org-dartlang-sdk:///lib/async/zone.dart 1206:12                           _rootRunUnary
  org-dartlang-sdk:///lib/async/zone.dart 1099:34                           runUnary
  org-dartlang-sdk:///lib/async/zone.dart 1005:7                            runUnaryGuarded
  org-dartlang-sdk:///lib/async/stream_impl.dart 357:5                      _sendData
  org-dartlang-sdk:///lib/async/stream_impl.dart 285:7                      _add
  org-dartlang-sdk:///lib/async/stream_controller.dart 811:19               _sendData
  org-dartlang-sdk:///lib/async/stream_controller.dart 682:7                _add
  org-dartlang-sdk:///lib/async/stream_controller.dart 624:5                add
  org-dartlang-sdk:///lib/async/stream_controller.dart 903:5                add
  ../../packages/stream_channel/src/guarantee_channel.dart 19:29            call
  org-dartlang-sdk:///lib/async/zone.dart 1384:9                            runUnaryGuarded
  org-dartlang-sdk:///lib/async/stream_impl.dart 357:5                      _sendData
  org-dartlang-sdk:///lib/async/stream_impl.dart 285:7                      _add
  org-dartlang-sdk:///lib/async/stream_controller.dart 811:19               _sendData
  org-dartlang-sdk:///lib/async/stream_controller.dart 682:7                _add
  org-dartlang-sdk:///lib/async/stream_controller.dart 624:5                add
  org-dartlang-sdk:///lib/async/zone.dart 1384:9                            runUnaryGuarded
  org-dartlang-sdk:///lib/async/stream_impl.dart 357:5                      _sendData
  org-dartlang-sdk:///lib/async/stream_impl.dart 285:7                      _add
  org-dartlang-sdk:///lib/async/stream_controller.dart 811:19               _sendData
  org-dartlang-sdk:///lib/async/stream_controller.dart 682:7                _add
  org-dartlang-sdk:///lib/async/stream_controller.dart 624:5                add
  org-dartlang-sdk:///lib/async/stream_controller.dart 903:5                add
  org-dartlang-sdk:///lib/async/zone.dart 1384:9                            runUnaryGuarded
  org-dartlang-sdk:///lib/async/stream_impl.dart 357:5                      _sendData
  org-dartlang-sdk:///lib/async/stream_impl.dart 285:7                      _add
  org-dartlang-sdk:///lib/async/stream_controller.dart 811:19               _sendData
  org-dartlang-sdk:///lib/async/stream_controller.dart 682:7                _add
  org-dartlang-sdk:///lib/async/stream_controller.dart 624:5                add
  org-dartlang-sdk:///lib/async/zone.dart 1384:9                            runUnaryGuarded
  org-dartlang-sdk:///lib/async/stream_impl.dart 357:5                      _sendData
  org-dartlang-sdk:///lib/async/stream_impl.dart 285:7                      _add
  org-dartlang-sdk:///lib/async/stream_controller.dart 811:19               _sendData
  org-dartlang-sdk:///lib/async/stream_controller.dart 682:7                _add
  org-dartlang-sdk:///lib/async/stream_controller.dart 624:5                add
  org-dartlang-sdk:///lib/async/stream_controller.dart 903:5                add
  ../../packages/stream_channel/src/guarantee_channel.dart 19:29            call
  org-dartlang-sdk:///lib/html/dart2js/html_dart2js.dart 37188:40           call
  org-dartlang-sdk:///lib/_internal/js_runtime/lib/js_helper.dart 2020:14   invokeClosure
  org-dartlang-sdk:///lib/_internal/js_runtime/lib/js_helper.dart 2052:1    <fn>
```

**Comment by yjbanov** [comment] 2020-06-23 01:18
I think the issue is with the iOS Simulator, not with CanvasKit our code: https://bugs.webkit.org/show_bug.cgi?id=191064

**Comment by pedromassangocode** [comment] 2020-12-07 13:30
I'm wondering if this is a valid issue today. The link mentioned is not valid anymore.

**Comment by nturgut** [comment] 2020-12-10 02:03
@pedromassangocode 
Yes looks like the skips are removed:
https://github.com/flutter/engine/blob/master/lib/web_ui/test/engine/path_metrics_test.dart

**Comment by nturgut** [comment] 2021-01-05 21:48
Looks like I made a mistake originally and put the wrong file to the issue.

https://github.com/flutter/engine/blob/master/lib/web_ui/test/canvaskit/path_test.dart

**Comment by yjbanov** [comment] 2022-08-04 17:39
Closing as we moved all tests to macOS Safari for now due to Simulator flakiness. iOS Simulator testing story needs a new approach.

**Closed by yjbanov** 2022-08-04 17:39 UTC
Labels: a: tests, engine, platform-web, passed first triage, e: web_canvaskit, P4
