### ISSUE TITLE
Flutter gets error on launching apps

### ISSUE THREAD

**Issue by jerryhamby** [flutter/flutter#84301] opened 2021-06-09 22:37 UTC
I have done “flutter run --profile” on 2 different device and get the same error.
The app seems to load but everything stops at a white screen on my devices.
If I pull the app and unplug from the desktop, then restart the app, all tests seem o be fine.
Never had this problem before.

——— the errors —— (both devices running 14.6)
Error running application on iPhone11
Error running application on Jerry Hamby’s iPhone (iPhone 7)

My desktop system:
BigSur 11.4
VS Code/Flutter 2.2.1
Xcode 12.5

Looking for help or experience on this issue.

**Comment by darshankawar** [comment] 2021-06-10 08:52
@jerryhamby 
Can you provide `flutter doctor -v`, `flutter run --profile --verbose` in a text file including a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that shows this behavior ?

**Comment by jerryhamby** [comment] 2021-06-10 16:30
FYI, this app is very large and I don't know how to give a minimal version.

 flutter doctor -v
[✓] Flutter (Channel stable, 2.2.1, on macOS 11.4 20F71 darwin-x64, locale en-US)
    • Flutter version 2.2.1 at /Users/jerryhamby/Desktop/flutterexamples/flutter
    • Framework revision 02c026b03c (2 weeks ago), 2021-05-27 12:24:44 -0700
    • Engine revision 0fdb562ac8
    • Dart version 2.13.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/jerryhamby/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.56.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.23.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 91.0.4472.77

• No issues found!



—- this is where the problem shows up —-
—- if you need the complete —version info, I will provide but it is large —

  ] Application launched on the device. Waiting for observatory port.
[+30011 ms] Installing and launching... (completed in 45.5s)
[        ] Error running application on iPhone11.
[   +3 ms] "flutter run" took 197,837ms.
[   +4 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:663:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1043:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:196:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:232:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>
           
           
[   +2 ms] (lldb) process detach
[  +93 ms] ensureAnalyticsSent: 94ms
[        ] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 2

**Comment by darshankawar** [comment] 2021-06-11 05:38
@jerryhamby 
Please provide the entire log from `flutter run --profile --verbose` to properly address the issue. Above information is not complete to conclude anything.

**Comment by jerryhamby** [comment] 2021-06-11 17:24
see attached text file:

[vdex_version_info.txt](https://github.com/flutter/flutter/files/6640084/vdex_version_info.txt)

**Comment by darshankawar** [comment] 2021-06-14 06:28
@jerryhamby 
Thanks for the log, but it doesn't highlight any error or log which leads to the failure. Does it work in release mode and in debug mode ?
Can you provide the logs for both modes too ?

**Comment by jerryhamby** [comment] 2021-06-14 16:18
First off, I don’t know how to get “logs”. Maybe a quick example would help.

Second, I’m only working in debug mode, haven’t tried anything in release mode yet. All these issues refer to debug only.

Third, the problem only happens in debug mode while exporting to my device through “run —profile”, emulator mode seems to be fine.

The small section  I provided from “flutter run --profile --verbose “ is the error I'm getting. I just don’t how to interrupt or fix.

**Comment by darshankawar** [comment] 2021-06-15 05:51
@jerryhamby 

What do you exactly mean by `the problem only happens in debug mode while exporting to my device through “run —profile”,` ? Can you please explain what are you trying to do / achieve by `exporting to device through `run --profile` ?

**Comment by jerryhamby** [comment] 2021-06-15 06:29
I have a very large app and I doing some testing, and as Flutter keeps changing, I have to test my app against all of the new changes. Null-safety is my latest test.

!- I first have to test against the IOS emulator. My app works fine, no problems here.

2- Next I export to either of my 2 physical devices (iPhone 11 or iPhone 7). I’m using “flutter run —profile” for this purpose. Everything seems to be working until the very end when my device is completely white. I have supplied you with version info.

3- I’m only testing in debug mode, I haven’t even started to test in release mode yet. Also I haven’t started testing the Android side either.

4- The reason I’m using “flutter run —profile” is so I can test on the devices several times. It was pointed that I needed to do this. “flutter run “ only works once as long as I’m tethered to my desktop.

Hope this helps.

**Comment by darshankawar** [comment] 2021-06-15 06:48
@jerryhamby 
Thanks for the details. From the log you provided, I see that it gets stuck at `Application launched on the device. Waiting for observatory port.` and subsequent error could be caused due to it, that it may be timing out to get the observatory port.

In the code, the timeout is set to 30 seconds, https://github.com/flutter/flutter/blob/44d0e52d2065dbcaa01ac29b4488c7bbd7b1e76c/packages/flutter_tools/lib/src/ios/devices.dart#L430

This leads me to similar open issue, https://github.com/flutter/flutter/issues/72161 which talks about same case. Please follow-up in that issue and you may also go through the issue comments in it which has workaround / solutions and try them to see if they help to resolve your issue.

I am going ahead and closing this as duplicate of https://github.com/flutter/flutter/issues/72161. You may also comment your findings in that issue for better tracking. If you disagree to have this issue closed, write in comments and I'll reopen it.

Thanks.

**Closed by darshankawar** 2021-06-15 06:48 UTC
Labels: in triage
