### ISSUE TITLE
Problem with download files

### ISSUE THREAD

**Issue by hugoquintalcr** [flutter/flutter#82038] opened 2021-05-07 16:09 UTC
I´m trying to download some files but I can´t.

**Comment by ChristianKleineidam** [comment] 2021-05-07 18:07
Which files?

**Comment by darshankawar** [comment] 2021-05-10 06:23
@hugoquintalcr 
This doesn't describe a bug or feature request. Please ask support questions on StackOverflow.

Closing, as the issue is incomplete and doesn't seem to be an issue in the framework.

**Closed by darshankawar** 2021-05-10 06:24 UTC
Labels: in triage

**Comment by hugoquintalcr** [comment] 2021-05-10 15:26
you´re right, I´m sorry.
