### ISSUE TITLE
[Bug] Word Candidate Window is not in the right position when typing Chinese in Windows

### ISSUE THREAD

**Issue by feimenggo** [flutter/flutter#111324] opened 2022-09-10 00:29 UTC
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. Watch the demo video 

**Expected results:** 
Word Candidate Window should follow the cursor position.

**Actual results:** 
Word Candidate Window is not in the right position.

<details>
<summary>Code sample</summary>

```dart

import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      // This call to setState tells the Flutter framework that something has
      // changed in this State, which causes it to rerun the build method below
      // so that the display can reflect the updated values. If we changed
      // _counter without calling setState(), then the build method would not be
      // called again, and so nothing would appear to happen.
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: Center(
        // Center is a layout widget. It takes a single child and positions it
        // in the middle of the parent.
        child: SingleChildScrollView(
          child: Column(
            // Column is also a layout widget. It takes a list of children and
            // arranges them vertically. By default, it sizes itself to fit its
            // children horizontally, and tries to be as tall as its parent.
            //
            // Invoke "debug painting" (press "p" in the console, choose the
            // "Toggle Debug Paint" action from the Flutter Inspector in Android
            // Studio, or the "Toggle Debug Paint" command in Visual Studio Code)
            // to see the wireframe for each widget.
            //
            // Column has various properties to control how it sizes itself and
            // how it positions its children. Here we use mainAxisAlignment to
            // center the children vertically; the main axis here is the vertical
            // axis because Columns are vertical (the cross axis would be
            // horizontal).
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              const TextField(maxLines: null),
              Text(
                '$_counter',
                style: Theme.of(context).textTheme.headline4,
              ),
            ],
          ),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}

```

</details>

<details>
  <summary>Logs</summary>

```

Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
[√] Flutter (Channel master, 3.4.0-19.0.pre.153, on Microsoft Windows [版本 10.0.22000.856], locale zh-CN)
    • Flutter version 3.4.0-19.0.pre.153 on channel master at D:\dev\sdk\flutter-master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d2434a2b60 (26 hours ago), 2022-09-08 15:39:07 -0700
    • Engine revision 4096e133ef
    • Dart version 2.19.0 (build 2.19.0-177.0.dev)
    • DevTools version 2.17.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[X] Windows Version (Unable to confirm if installed Windows version is 10 or greater)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at D:\dev\ide\Android\sdk
    • Platform android-31, build-tools 29.0.3
    • Java binary at: D:\dev\ide\Android\studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.3.3)
    • Visual Studio at D:\dev\ide\VisualStudio\2022\Community
    • Visual Studio Community 2022 version 17.3.32825.248
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.2)
    • Android Studio at D:\dev\ide\Android\studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] IntelliJ IDEA Ultimate Edition (version 2021.2)
    • IntelliJ at D:\dev\ide\IntelliJ IDEA 2021.2.2
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [版本 10.0.22000.856]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 104.0.5112.81
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 105.0.1343.27

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```

</details>

### Using the Sougou pinyin IME to input Chinese

There are also issues with Windows 10-11.

Download link: https://shurufa.sogou.com/

https://user-images.githubusercontent.com/12608693/189250361-dfcfe4d1-7f0d-4e7f-9f23-42f4da2711ee.mp4

### I occasionally encountered a throbbing problem using the Microsoft Pinyin IME

https://user-images.githubusercontent.com/12608693/189253493-db898f66-18d8-4e7b-a1e7-5e4d5208e082.mp4

At 00:11 of the video:

<img width="1264" alt="image" src="https://user-images.githubusercontent.com/12608693/189253100-1767d1b8-0298-4d5e-b079-05c407fea8a0.png">

### Using the QQ Pinyin IME, the throbbing problem is more frequent

Download link: http://qq.pinyin.cn/

https://user-images.githubusercontent.com/12608693/189254395-4a3da8f7-331a-486e-8ea7-b8cfc1e12c5f.mp4

**Comment by feimenggo** [comment] 2022-09-10 00:37
@cbracken Help with this issue.

**Comment by cbracken** [comment] 2022-09-10 18:08
Closing as duplicate of https://github.com/flutter/flutter/issues/92050

**Closed by cbracken** 2022-09-10 18:08 UTC
