### ISSUE TITLE
flutter_tools integration tests fail reliably fails on Windows when --enable-asserts is set

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#36476] opened 2019-07-18 18:47 UTC
cc @DanTup 

See also https://github.com/flutter/flutter/issues/24062 (possible flake on other platforms), #19236 (a previous flake on that test that stopped reproducing) and #15513 (a Windows-specific issue on this test from the past).

**Comment by DanTup** [comment] 2019-07-18 18:52
@Hixie where did you see this last, do you have a link to a log (or snippet of what the failure was?).

**Comment by Hixie** [comment] 2019-07-18 21:29
https://cirrus-ci.com/task/5479144568127488 for example.

See also https://github.com/flutter/flutter/issues/36382 https://github.com/flutter/flutter/issues/36321 https://github.com/flutter/flutter/issues/36279 which are all basically cases of integration tests failing on Windows. When I filed those I thought it was just flakiness, but maybe it's actually just that we didn't run the tests on Windows before? Or I changed something in my PR that triggers them to fail? (https://github.com/flutter/flutter/pull/36205 is the PR)

**Comment by Hixie** [comment] 2019-07-18 21:43
Contrast with https://cirrus-ci.com/task/6226032149921792 which shows the same test running today, on Windows, yet somehow doesn't fail. I don't know why it's different. It's probably in my PR, but what could it be...

**Comment by Hixie** [comment] 2019-07-18 21:50
The two differences I see is that I set BOT=true, and I run the tests by specifying a single directory instead of using tags like we do today.

**Comment by Hixie** [comment] 2019-07-18 21:51
Oh, it's simple. These tests aren't actually running today! We don't seem to actually set the tag on these tests.

**Comment by Hixie** [comment] 2019-07-18 21:54
Or not. The tag is on https://github.com/flutter/flutter/blob/master/packages/flutter_tools/test/integration.shard/expression_evaluation_test.dart#L89 .

**Comment by Hixie** [comment] 2019-07-18 21:59
Maybe tags on `group` don't work? That would mean we're not running them today.

**Comment by Hixie** [comment] 2019-07-18 22:10
I really don't see anything else in the diff that makes sense... https://github.com/flutter/flutter/pull/36205/files

**Comment by Hixie** [comment] 2019-07-19 20:27
Removing the BOT=true didn't stop the issue: https://cirrus-ci.com/task/5459604882849792?command=main#L342

**Comment by DanTup** [comment] 2019-07-20 16:41
@Hixie I can reproduce a timeout in that test when running on your branch, but only if I set `_printDebugOutputToStdOut` to `true`. This causes us to run with `--verbose` which results in extra output in the `flutter test` run, which we fail to parse as JSON and crash.

A fix for that could be in `test_driver.dart` in `_waitForJson`, changing:

```dart
() => _stdout.stream.map<Map<String, dynamic>>(_parseJsonResponse).first,
```

to:

```dart
() => _stdout.stream.map<Map<String, dynamic>>(_parseJsonResponse)
          .firstWhere((Map<String, dynamic> res) => res != null),
```

This would cause it to skip over any output that's not valid JSON (alternatively we could filter it to things that start with `[` and end with `]`), but I don't know if we'd rather fail (or if it's even related to the failure on the bot).

Do your changes do anything that would result in running in verbose mode on the bots even without that set? (I couldn't see anything obvious, but it's a big change!).

**Comment by Hixie** [comment] 2019-07-22 23:28
Interesting... Nothing comes to mind but let me keep looking.

**Comment by DanTup** [comment] 2019-07-23 11:15
I had a go at trying to run this test on a branch with the verboes logging enabled:

https://github.com/DanTup/flutter/tree/debug-test-issue

However, the output from the test (eg. stuff that gets `print()`ed) doesn't seem to appear in the Cirrus output. I removed `build_runner` and the compact runner but that didn't make any difference. Any ideas?

**Comment by DanTup** [comment] 2019-07-23 14:40
The more I dig into this, the more things don't make sense :)

Locally I can't repro the issue, however the tests always hang when they're finished ("All tests pass" but the VM doesn't quit... Observatory shows an open Port but I can't figure out what it is (it's in multiplex in socket_patch, but that doesn't tell me much)).

I made a branch that only runs this one script from this file, and calls it directly (instead of going through pub or the test script) and it behaves the same - the tests pass, but never complete:

![Untitled](https://user-images.githubusercontent.com/1078012/61721260-19a1a380-ad60-11e9-963e-a97e8d87b149.png)

https://cirrus-ci.com/task/5091131518353408

I'm not sure why the behaviour is different (either for the pass/fails, or the hanging)!

**Comment by Hixie** [comment] 2019-09-26 00:45
It's `--enable-asserts` that's triggering this.

**Comment by Hixie** [comment] 2019-09-26 18:09
See the logs in https://cirrus-ci.com/task/6252385669742592 -- it looks like it's not even running the tests (note that the tests' verbosity is turned up, yet there's no logs from the tests).

**Comment by DanTup** [comment] 2019-10-01 12:30
Ok, I can repro this locally running:

```
..\..\bin\cache\dart-sdk\bin\pub.bat run test -j1 --no-color .\test\integration.shard\expression_evaluation_test.dart
```

I put some prints around the place, and found that it was hanging in the `setup` method, when trying to fetch packages:

https://github.com/flutter/flutter/blob/e2340c641db23a1e97a6f6e83af809944ff5fe34/packages/flutter_tools/test/integration.shard/test_utils.dart#L43-L56

While trying to debug, I made it capture `stdout` in addition to `stderr`:

```dart
process.stderr.transform(utf8.decoder).listen(errorOutput.write);
process.stdout.transform(utf8.decoder).listen(errorOutput.write);
```

And now the test works, and does not hang. If I comment out that second line, it hangs again.

It seems like not consuming `stdout` might somehow be causing the process to never end 🤷‍♂ 

There's no harm in capturing stdout to include in the error too, and that should accidentally fix this - but I don't understand the cause.

**Comment by DanTup** [comment] 2019-10-01 12:39
PR that listens to stdout to add it to the failure message here:

https://github.com/flutter/flutter/pull/41687

It should solve the problem - but I'm not sure if we need to dig further into why this is happening.

**Comment by DanTup** [comment] 2019-10-10 09:52
@Hixie I landed a change that seemed to stop this on Windows - however I then became unable to reproduce while testing without the fix :(

What do I need to do on a branch to see these failures? The PR you linked had lots of other stuff in, so it's not clear what triggers this (the live bots aren't failing, so I presume there's some change that led to this failure?).

**Comment by Hixie** [comment] 2019-10-11 02:14
no idea, i can't repro this anymore either.

**Comment by Hixie** [comment] 2019-10-11 02:15
uh, never mind, i misread my patch... -_-

**Comment by Hixie** [comment] 2019-10-11 02:16
Replace this line with one that just sets that argument to true, to repro (untested):
https://github.com/flutter/flutter/blob/master/dev/bots/test.dart#L227

**Comment by DanTup** [comment] 2019-10-14 14:43
@Hixie When I investigated this, I found it was hanging while fetching packages. I changed how that code worked slightly (simplified it to use `processManager.run) here:

https://github.com/flutter/flutter/pull/41687

I just tried enabling the asserts (on a branch including that change) and everything passed:

https://github.com/flutter/flutter/pull/42637

So maybe it's fixed? Should I land that change and we can see if it comes back up?

**Comment by DanTup** [comment] 2019-11-14 09:27
@Hixie I have a PR that re-enables these and it's passing:

https://github.com/flutter/flutter/pull/42637

Please take a look and let me know if it's seems reasonable to land. It may be fixed by the change I made above, however after fixing that I couldn't repro even when I reverted the change, so I don't know if it was flaky (or been fixed by something else).

**Closed** 2019-11-20 17:50 UTC
Labels: a: tests, tool, ❖ platform-windows
