### ISSUE TITLE
Camera plugin does not work on module inside native iOS App.

### ISSUE THREAD

**Issue by hoffsilva** [flutter/flutter#51562] opened 2020-02-27 14:04 UTC
## Steps to Reproduce

I created a module that uses camera, so when I add this module on my ios and android app, the camera does not open, and the follow error is printed on xcode console:
MissingPluginException(No implementation found for method availableCameras on channel plugins.flutter.io/camera)

I tested add the module on app created from scratch and I had the same error.

1. Create a module with camera plugin example
2. Create a simple iOS app from scratch
3. Add podfile with steps of option A from this [tutorial](https://flutter.dev/docs/development/add-to-app/ios/project-setup)
4 . Run the iOS native app.

This gif shows just the module.
![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/11273459/75452018-40f0cc80-5950-11ea-816f-50b246c04a29.gif)

This gif shows the module called from native iOS app.
![ezgif com-video-to-gif (2)](https://user-images.githubusercontent.com/11273459/75452292-cbd1c700-5950-11ea-9625-212a28c9a9f7.gif)

**Expected results:** 
We would like to see the camera working, but it does not happen.
**Actual results:** 
I just a screen with out camera view.

<details>
  <summary>Logs</summary>
MissingPluginException(No implementation found for method availableCameras on channel plugins.flutter.io/camera)

**Comment by VladyslavBondarenko** [comment] 2020-02-27 14:14
Hi @hoffsilva 
could you show `pubspec.yaml` of your module?
hardly it's the same, but I remember similar case when it wasn't loaded only because author added plugin to the `dev_dependencies` instead of `dependencies`

**Comment by hoffsilva** [comment] 2020-02-27 14:28
Hi @VladyslavBondarenko! Yes, I can.

name: camera_app
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  camera: ^0.5.7+2
  image_picker: ^0.6.2+3
  path_provider: ^1.4.2
  path: ^1.6.4


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/

**Comment by jmagman** [comment] 2020-06-11 23:10
Did you add the necessary privacy stuff to your host app Info.plist?  See https://pub.dev/packages/camera#installation

**Comment by TahaTesser** [comment] 2020-07-01 12:10
@jmagman 
Not able to reproduce this issue due to another https://github.com/flutter/flutter/issues/54599 
i have added permissions to module, running just module has no issue

**Comment by TahaTesser** [comment] 2020-07-24 15:04
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

**Closed by TahaTesser** 2020-07-24 15:04 UTC
Labels: a: existing-apps, engine, p: camera, platform-ios, plugin

**Comment by therealblue10** [comment] 2021-03-19 17:20
What was needed to run pod install explicitly on iOS project once. Before that if you go to Dev Pods, you will red directories of packages that are added in Flutter.

**Comment by BijeshNair** [comment] 2021-06-22 13:41
@hoffsilva, were you able to resolve this issue?

**Comment by therealblue10** [comment] 2021-06-23 05:55
Try deleting your iOS pod workspace and reinstall it. It should work.
________________________________
