### ISSUE TITLE
Unclear error message: “The return type 'DocumentReference ()' isn't a 'DocumentReference ()', as defined by the method”

### ISSUE THREAD

**Issue by mirkancal** [flutter/flutter#30096] opened 2019-03-28 08:30 UTC
I get this error and I think the error message is unclear.
Future<DocumentReference> isn't a 'DocumentReference' could be better option for that. I think I saw my suggested message before but somehow this time I didn't get that and what I get seems unclear.
 
I've asked on [SO](https://stackoverflow.com/questions/55392816/how-to-solve-the-return-type-documentreference-isnt-a-documentreference):

```
flutter --version
Flutter 1.2.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 8661d8aecd (6 weeks ago) • 2019-02-14 19:19:53 -0800
Engine • revision 3757390fa4
Tools • Dart 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)
```

```
Version: 1.32.3
Commit: a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4
Date: 2019-03-14T23:38:49.842Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 5.0.3-200.fc29.x86_64
```
Flutter and Dart plugin: 2.24.0

**Comment by iapicca** [comment] 2020-01-14 12:04
Hi @mirkancal 
for what I can see the issue is related to a FlutterFire plugin,
please open the issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
thank you

**Closed by iapicca** 2020-01-14 12:04 UTC
Labels: a: error message, dependency: dart
