### ISSUE TITLE
[flutter_webview]android not support customize system  error page when received http error

### ISSUE THREAD

**Issue by LongXiangGuo** [flutter/flutter#83250] opened 2021-05-24 10:35 UTC
## Use case

- When got an resource error on android, it aways show a system default page, which is not meet the UI requirements 

## Proposal

- expose the android the `onLoadHttpError` method to flutter, so  it can  hidden the webview widget and show a customize error page

- System error page
![image](https://user-images.githubusercontent.com/16632821/119334657-f4fd1680-bcbd-11eb-8018-f0161ca1033a.png)

- Custom error page
 
![image](https://user-images.githubusercontent.com/16632821/119334718-047c5f80-bcbe-11eb-9c2a-6216d0b7f81e.png)

Currently I'am use the title to check the error page work around for it, but it's easy to miss some cases.

**Comment by stuartmorgan** [comment] 2023-05-27 23:45
Closing as a duplicate of https://github.com/flutter/flutter/issues/39502, where most of the voting and discussion ended up.

**Closed by stuartmorgan** 2023-05-27 23:45 UTC
Labels: new feature, platform-android, plugin, p: webview, proposal, passed first triage, P5
