### ISSUE TITLE
The Flutter text renderer does word wrap before applying the ellipsis.  So the English text is being wrapped to the second line.

### ISSUE THREAD

**Issue by Jimmuy** [flutter/flutter#58461] opened 2020-06-02 03:15 UTC
Chinese and English are separated ...

code：

```
Row(
          mainAxisAlignment: MainAxisAlignment.spaceBetween,
          children: [
            Container(width:50,height:50,color:Colors.black45),
            Expanded(child:
              Text('文字文字文字kjhgfdrtyuiknbvfkjhgfdfgh',
                textAlign: TextAlign.left,
                maxLines: 1,
                overflow: TextOverflow.ellipsis,
              )
            ),
            Container(width:200,height:50,color:Colors.red)
          ]
        )
```

The effect I want is like '文字文字文字kjhgfdrtyuik...',but now '文字文字文字...'

The Flutter text renderer does word wrap before applying the ellipsis.  So the English text is being wrapped to the second line.

Unicode word joiner characters can be used to tell the line breaker to not wrap words at a given position:
Text(`'文\u2060字\u2060文\u2060字\u2060文\u2060字\u2060kjhgfdrtyuiknbvfkjhgfdfgh')`

> 

**cause some string data came from net server,so it‘s improssable to give every word a position ,can it be fixed in future flutter sdk  ?**

_Originally posted by @jason-simmons in https://github.com/flutter/flutter/issues/53629#issuecomment-606918973_

**Comment by TahaTesser** [comment] 2020-06-02 11:37
duplicate of https://github.com/flutter/flutter/issues/18761 https://github.com/flutter/flutter/issues/53629

**Closed by TahaTesser** 2020-06-02 11:37 UTC
