### ISSUE TITLE
[tool_crash] FileSystemException: Failed to decode data using encoding 'utf-8', null

### ISSUE THREAD

**Issue by oculosdanilo** [flutter/flutter#129020] opened 2023-06-16 17:26 UTC
## Command
```
flutter pub upgrade
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Failed to decode data using encoding 'utf-8', null
```
#0      _File._tryDecode (dart:io/file_impl.dart:615:7)
#1      _File.readAsStringSync (dart:io/file_impl.dart:624:7)
#2      ForwardingFile.readAsStringSync (package:file/src/forwarding/forwarding_file.dart:99:16)
#3      ErrorHandlingFile.readAsStringSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:218:22)
#4      _runSync (package:flutter_tools/src/base/error_handling_io.dart:590:14)
#5      ErrorHandlingFile.readAsStringSync (package:flutter_tools/src/base/error_handling_io.dart:217:12)
#6      AndroidPlugin._getSupportedEmbeddings (package:flutter_tools/src/platform_plugins.dart:210:53)
#7      AndroidPlugin._supportedEmbeddings (package:flutter_tools/src/platform_plugins.dart:158:49)
#8      AndroidPlugin._supportedEmbeddings (package:flutter_tools/src/platform_plugins.dart)
#9      AndroidPlugin.toMap (package:flutter_tools/src/platform_plugins.dart:152:30)
#10     _extractPlatformMaps (package:flutter_tools/src/flutter_plugins.dart:355:40)
#11     _writeAndroidPluginRegistrant (package:flutter_tools/src/flutter_plugins.dart:369:53)
#12     injectPlugins (package:flutter_tools/src/flutter_plugins.dart:1150:11)
<asynchronous suspension>
#13     FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:374:5)
<asynchronous suspension>
#14     PackagesGetCommand.runCommand (package:flutter_tools/src/commands/packages.dart:326:7)
<asynchronous suspension>
#15     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1336:27)
<asynchronous suspension>
#16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#17     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#18     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:296:9)
```
```
[✓] Flutter (Channel stable, 3.10.3, on Microsoft Windows [versÆo 10.0.19045.2673], locale pt-BR)
    • Flutter version 3.10.3 on channel stable at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f92f44110e (2 weeks ago), 2023-06-01 18:17:33 -0500
    • Engine revision 2a3401c9bb
    • Dart version 3.0.3
    • DevTools version 2.23.1

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at C:\Users\LAB07\AppData\Local\Android\sdk
    • Platform android-33-ext4, build-tools 33.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Professional 2019 16.0.22)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional
    • Visual Studio Professional 2019 version 16.0.28803.916
    • Windows 10 SDK version 10.0.17763.0

[✓] Android Studio (version 2022.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.79.2)
    • VS Code at C:\Users\LAB07\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.60.0

[✓] Connected device (4 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Windows (desktop)                  • windows       • windows-x64    • Microsoft Windows [versÆo 10.0.19045.2673]
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 111.0.5563.65
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 109.0.1518.61

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: f72efea43c3013323d1b95cff571f3c1caa37583
### Plugins
firebase_auth-4.6.3
firebase_auth_web-5.5.3
firebase_core-2.14.0
firebase_core_web-2.6.0
google_sign_in-6.1.4
google_sign_in_android-6.1.16
google_sign_in_ios-5.6.2
google_sign_in_web-0.12.0+2
path_provider-2.0.15
path_provider_android-2.0.27
path_provider_foundation-2.2.3
path_provider_linux-2.1.11
path_provider_windows-2.1.7
video_player-2.6.1
video_player_android-2.4.9
video_player_avfoundation-2.4.6
video_player_web-2.0.16

**Comment by darshankawar** [comment] 2023-06-19 06:40
Closing this as a duplicate of https://github.com/flutter/flutter/issues/65021.

**Closed by darshankawar** 2023-06-19 06:40 UTC
Labels: in triage
