### ISSUE TITLE
flutter fails to run at keytool signing stage

### ISSUE THREAD

**Issue by terrasea** [flutter/flutter#5164] opened 2016-07-30 17:22 UTC
## Steps to Reproduce

I am using Gentoo with java version

```
java version "1.8.0_77"
Java(TM) SE Runtime Environment (build 1.8.0_77-b03)
Java HotSpot(TM) 64-Bit Server VM (build 25.77-b03, mixed mode)
```

if that makes any difference.
.
I installed flutter on my system, ignoring the Atom install part

setup the path to flutter as instructed, and created an app called myapp, again following instructions

attached my android device via usb and made sure flutter could see it by running

```
flutter devices
```
with the output of

```
1 connected device:

Nexus 7 • 09337fc8 • android-arm
```

ran the command

```
flutter run
```

inside the directory where the app lives, as per instructions. 

At that point it seems it fails to run keytool which it uses to sign the generated apk to run on my attached device.  Output pasted below in the log and crash report section of this issue

## Flutter Doctor

[✓] Flutter (on Linux, channel alpha)
    • Flutter at /home/terrasea/flutter/flutter
    • Framework revision e42be3c363 (12 days ago), engine revision 3291edef41

[✓] Android toolchain - develop for Android devices (Android SDK 21.1.2)
    • Android SDK at /home/terrasea/Android/Sdk
    • Platform android-22, build-tools 21.1.2
    • Java(TM) SE Runtime Environment (build 1.8.0_77-b03)

[x] Atom - a lightweight development environment for Flutter
    x Atom not installed; download at https://atom.io.

## Logs and Crash Reports

```
Building APK in debug mode (android-arm)...              
Warning: signing the APK using the debug keystore.
* run-java-tool was invoked directly
* run-java-tool should only be used via symlinks to it
Exception from flutter run: Exit code 1 from: /usr/libexec/eselect-java/run-java-tool.bash -keystore /home/terrasea/flutter/flutter/bin/cache/artifacts/engine/android-arm/chromium-debug.keystore -storepass chromium -keypass chromium /tmp/flutter_toolsyXAJ93/app.apk.unaligned chromiumdebugkey
#0      _runWithLoggingSync (package:flutter_tools/src/base/process.dart:188)
#1      runCheckedSync (package:flutter_tools/src/base/process.dart:130)
#2      _ApkBuilder.sign (package:flutter_tools/src/commands/build_apk.dart:125)
#3      _signApk (package:flutter_tools/src/commands/build_apk.dart:386)
#4      _buildApk (package:flutter_tools/src/commands/build_apk.dart:341)
#5      buildAndroid.<buildAndroid_async_body> (package:flutter_tools/src/commands/build_apk.dart:542)
#6      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:27)
#7      StackZoneSpecification.registerUnaryCallback.<anonymous closure>.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:135)
#8      StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:206)
#9      StackZoneSpecification.registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:135)
#10     _rootRunUnary (dart:async/zone.dart:1212)
#11     _CustomZone.runUnary (dart:async/zone.dart:1067)
#12     _FutureListener.handleValue (dart:async/future_impl.dart:131)
#13     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:637)
#14     _Future._propagateToListeners (dart:async/future_impl.dart:667)
#15     _Future._complete (dart:async/future_impl.dart:467)
#16     _SyncCompleter.complete (dart:async/future_impl.dart:52)
#17     buildFlx.<buildFlx_async_body> (package:flutter_tools/src/flx.dart:307)
#18     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:27)
#19     StackZoneSpecification.registerUnaryCallback.<anonymous closure>.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:135)
#20     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:206)
#21     StackZoneSpecification.registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:135)
#22     _rootRunUnary (dart:async/zone.dart:1212)
#23     _CustomZone.runUnary (dart:async/zone.dart:1067)
#24     _FutureListener.handleValue (dart:async/future_impl.dart:131)
#25     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:637)
#26     _Future._propagateToListeners (dart:async/future_impl.dart:667)
#27     _Future._complete (dart:async/future_impl.dart:467)
#28     _SyncCompleter.complete (dart:async/future_impl.dart:52)
#29     assemble.<assemble_async_body> (package:flutter_tools/src/flx.dart:444)
#30     Future.Future.microtask.<anonymous closure> (dart:async/future.dart:144)
#31     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:206)
#32     StackZoneSpecification.registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:125)
#33     _rootRun (dart:async/zone.dart:1200)
#34     _CustomZone.run (dart:async/zone.dart:1056)
#35     _CustomZone.runGuarded (dart:async/zone.dart:954)
#36     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:981)
#37     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:206)
#38     StackZoneSpecification.registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:125)
#39     _rootRun (dart:async/zone.dart:1204)
#40     _CustomZone.run (dart:async/zone.dart:1056)
#41     _CustomZone.runGuarded (dart:async/zone.dart:954)
#42     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:981)
#43     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#44     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#45     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#46     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
```

**Comment by vynes** [comment] 2016-08-20 14:40
Hi have you found a solution to this yet? I think it's Gentoo specific since /usr/bin/java symlinks to /usr/bin/run-java-tool. The links are resolved until it finds the executable. I know nothing about Java but trying to learn so I cannot offer any solutions.

**Comment by Hixie** [comment] 2016-08-20 18:20
Can you try running `flutter run` with the `-v` argument to see if that helps?

We've not been able to reproduce this as far as I'm aware.

**Comment by terrasea** [comment] 2016-08-20 20:19
Yes, as soon as I can I'll give it a go

**Comment by vynes** [comment] 2016-08-20 20:40
I'm pretty sure you can reproduce this on any Gentoo machine. Somewhere, the real path to whichever java tool to run is resolved first before it is run. This means it resolves to */usr/libexec/eselect-java/run-java-tool.bash* (instead of, for example */opt/oracle-jdk-bin-1.8.0.102/bin/java*) which exits with error as it needs the name of symbolic link in order to run the correct tool.

(See */usr/libexec/eselect-java/run-java-tool.bash: line 45*)

I'm not sure which java tool is being run when `flutter run` is executed (sorry i don't know java). It is not *java* nor *javac* since I changed their symbolic links explicitly to */opt/oracle-jdk-bin-1.8.0.102/bin/java* and */opt/oracle-jdk-bin-1.8.0.102/bin/javac* respectively, and still */usr/libexec/eselect-java/run-java-tool.bash* is being run directly.

It may be any of these:
`/usr/bin/HtmlConverter
/usr/bin/jhat
/usr/bin/jdb
/usr/bin/jps
/usr/bin/native2ascii
/usr/bin/jar
/usr/bin/jsadebugd
/usr/bin/orbd
/usr/bin/wsgen
/usr/bin/servertool
/usr/bin/jinfo
/usr/bin/rmid
/usr/bin/ControlPanel
/usr/bin/jarsigner
/usr/bin/jstatd
/usr/bin/xjc
/usr/bin/javah
/usr/bin/idlj
/usr/bin/pack200
/usr/bin/rmic
/usr/bin/jcontrol
/usr/bin/serialver
/usr/bin/policytool
/usr/bin/tnameserv
/usr/bin/javac
/usr/bin/javap
/usr/bin/javadoc
/usr/bin/rmiregistry
/usr/bin/apt
/usr/bin/appletviewer
/usr/bin/jconsole
/usr/bin/jrunscript
/usr/bin/jvisualvm
/usr/bin/java
/usr/bin/jstack
/usr/bin/javaws
/usr/bin/wsimport
/usr/bin/keytool
/usr/bin/jstat
/usr/bin/jmap
/usr/bin/schemagen
/usr/bin/extcheck`

If anyone could tell me which of these are being run when `flutter run` is executed I can test a workaround for now without having to change them all.

So anyways, here is the output of `flutter run -v`:

`67 ms • /home/curvian/SDK/Android/platform-tools/adb devices -l
   0 ms • Exit code 0 from: /home/curvian/SDK/Android/platform-tools/adb devices -l
  18 ms • List of devices attached
          4d00ed1ba37540a1       device usb:1-3.4 product:ja3gxx model:GT_I9500 device:ja3g
 188 ms • /home/curvian/SDK/Android/platform-tools/adb -s 4d00ed1ba37540a1 shell getprop
   9 ms • Running build command.
  10 ms • Using engine artifacts dir: /home/curvian/SDK/flutter/bin/cache/artifacts/engine/android-arm
  47 ms • Looking for YAML at 'flutter.yaml'
   0 ms • No services specified in the manifest
   0 ms • Using engine artifacts dir: /home/curvian/SDK/flutter/bin/cache/artifacts/engine/android-arm
  10 ms • Building APK in debug mode (android-arm)...
1310 ms • /home/curvian/SDK/flutter/bin/cache/artifacts/engine/linux-x64/sky_snapshot --packages=/home/curvian/tmp/workspace/myapp/.packages --snapshot=build/snapshot_blob.bin --depfile=build/snapshot_blob.bin.d --build-output=build/snapshot_blob.bin /home/curvian/tmp/workspace/myapp/lib/main.dart
 610 ms • Building build/app.flx
  13 ms • which zip
 107 ms • Encoding zip file to build/app.flx
 240 ms • zip -q /home/curvian/tmp/workspace/myapp/build/app.flx fonts/MaterialIcons-Regular.ttf AssetManifest.json FontManifest.json LICENSE snapshot_blob.bin
   0 ms • Exit code 0 from: zip -q /home/curvian/tmp/workspace/myapp/build/app.flx fonts/MaterialIcons-Regular.ttf AssetManifest.json FontManifest.json LICENSE snapshot_blob.bin
  48 ms • Built build/app.flx.
  13 ms • Building APK; buildMode: debug.
1078 ms • /home/curvian/SDK/Android/build-tools/24.0.1/dx --dex --force-jumbo --output /tmp/flutter_toolsbzFCY9/classes.dex /home/curvian/SDK/flutter/bin/cache/artifacts/engine/android-arm/classes.dex.jar
 470 ms • Exit code 0 from: /home/curvian/SDK/Android/build-tools/24.0.1/dx --dex --force-jumbo --output /tmp/flutter_toolsbzFCY9/classes.dex /home/curvian/SDK/flutter/bin/cache/artifacts/engine/android-arm/classes.dex.jar
4338 ms • /home/curvian/SDK/Android/build-tools/24.0.1/aapt package -M android/AndroidManifest.xml -A /tmp/flutter_toolsbzFCY9/assets -I /home/curvian/SDK/Android/platforms/android-24/android.jar -F /tmp/flutter_toolsbzFCY9/app.apk.unaligned --debug-mode -S /home/curvian/tmp/workspace/myapp/android/res /tmp/flutter_toolsbzFCY9/artifacts
   0 ms • Exit code 0 from: /home/curvian/SDK/Android/build-tools/24.0.1/aapt package -M android/AndroidManifest.xml -A /tmp/flutter_toolsbzFCY9/assets -I /home/curvian/SDK/Android/platforms/android-24/android.jar -F /tmp/flutter_toolsbzFCY9/app.apk.unaligned --debug-mode -S /home/curvian/tmp/workspace/myapp/android/res /tmp/flutter_toolsbzFCY9/artifacts
   0 ms • Warning: signing the APK using the debug keystore.
  36 ms • /usr/libexec/eselect-java/run-java-tool.bash -keystore /home/curvian/SDK/flutter/bin/cache/artifacts/engine/android-arm/chromium-debug.keystore -storepass chromium -keypass chromium /tmp/flutter_toolsbzFCY9/app.apk.unaligned chromiumdebugkey
   0 ms • Exit code 1 from: /usr/libexec/eselect-java/run-java-tool.bash -keystore /home/curvian/SDK/flutter/bin/cache/artifacts/engine/android-arm/chromium-debug.keystore -storepass chromium -keypass chromium /tmp/flutter_toolsbzFCY9/app.apk.unaligned chromiumdebugkey
  18 ms • * run-java-tool was invoked directly
          * run-java-tool should only be used via symlinks to it`

**Comment by eseidel** [comment] 2016-08-20 20:46
Looks like this line is wrong for gentoo: https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/base/os.dart#L65

os.which('jarsigner') is called here:
https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/commands/build_apk.dart#L77

Not sure why it resolves symlinks, @devoncarew might know.

**Comment by terrasea** [comment] 2016-08-21 15:09
I also got the same output as @vynes after running 

```
flutter run -v
```

**Comment by devoncarew** [comment] 2016-08-22 04:17
I think we were resolving symlinks in our `which` wrapper in order to better locate the dart sdk from the `dart` executable, back before we vendored the dart sdk.

**Closed** 2016-08-22 21:35 UTC

**Comment by eseidelGoogle** [comment] 2016-08-22 23:18
Please let us know if this doesn't fix things on Gentoo.  Thanks again for
the report!

**Comment by vynes** [comment] 2016-08-23 06:03
Works for me, thanks!

**Comment by terrasea** [comment] 2016-08-23 07:13
I'll give it a go asap. Probably this weekend sorry. Sounds like it'll work though. Thank you.
