### ISSUE TITLE
App close on Camera Image Stream 

### ISSUE THREAD

**Issue by luckymehndiratta** [flutter/flutter#58469] opened 2020-06-02 06:25 UTC
we integrate the Camera plugin in our project and when we start image stream after some time app close automatically without any error so please help us to tackle this situation because we want to continue run ImageStream in our app

**Comment by TahaTesser** [comment] 2020-06-02 12:02
Hi @luckymehndiratta 
Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a minimal complete reproducible code sample.
Thank you

**Comment by decolon** [comment] 2020-06-11 23:55
Hi @TahaTesser, I have been having the same issue.  Not sure if it is the same root cause as @luckymehndiratta, but here is my information.  

It looks like a memory leak to me (see attached images) but the issue only seems to show up when running with ResolutionPreset set to high or medium.  In both these cases the memory consumption grows quickly, sometimes being reclaimed, but eventually rising over 2GB and crashing the app.  When it is set to low the memory clears correctly.  Sadly I am trying to use the imageStream as a barcode detector using firebase_ml_vision, and it only detects barcodes when I have ResolutionPreset at high.  

Happens on the following phones
iPhone X + iOS 13.6
Pixel 3a XL + Android 10

I have included the flutter doctor -v output below, the flutter_run_verbose output as a .txt file (I let it run until it crashed), the main.dart file (as a .txt) I used, the pubspec.yaml file (as a .txt), and some images of the memory consumption using ResolutionPreset.high, ResolutionPreset.medium, and ResolutionPreset.low.  Let me know if you need any more information.  

[flutter_run_verbose.txt](https://github.com/flutter/flutter/files/4767825/flutter_run_verbose.txt)
[main.txt](https://github.com/flutter/flutter/files/4767785/main.txt)
[pubspec.txt](https://github.com/flutter/flutter/files/4767790/pubspec.txt)
![memory_high](https://user-images.githubusercontent.com/1477356/84450109-16c3d180-ac04-11ea-8fc8-b9c030bcbd9e.PNG)
![memory_low](https://user-images.githubusercontent.com/1477356/84450112-175c6800-ac04-11ea-90fb-ce3cc40dafa0.PNG)
![memory_medium](https://user-images.githubusercontent.com/1477356/84450113-17f4fe80-ac04-11ea-95d0-885b9d01255d.PNG)




Flutter Doctor -V

```
[√] Flutter (Channel stable, v1.17.3, on Microsoft Windows [Version 10.0.18363.900], locale en-US)
    • Flutter version 1.17.3 at C:\SDKs\flutter
    • Framework revision b041144f83 (7 days ago), 2020-06-04 09:26:11 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\decol\AppData\Local\Android\sdk
    • Platform android-R, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.45.1)
    • VS Code at C:\Users\decol\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.11.0

[√] Connected device (1 available)
    • Pixel 3a XL • 93LAX08QKJ • android-arm64 • Android 10 (API 29)

! Doctor found issues in 1 category.
```

**Comment by acoutts** [comment] 2020-06-16 18:48
I am having the same issue as well.

**Comment by decolon** [comment] 2020-06-16 19:25
A couple more findings.  

I was using Flutter v1.17.3, so I switched to Master, but got the same results.

I then tried to run on a simulator instead of my Pixel 3a XL and got very different results.  Even on ResolutionPreset.high the memory did not accumulate

My simulator is a Pixel 3a running Android 10 x86 (Google Play) using my PCs webcam.

Here is the flutter run --verbose output
[flutter-run-verbose-simulator.txt](https://github.com/flutter/flutter/files/4788692/flutter-run-verbose-simulator.txt)

And here is what the memory profile of the simulator looks like which running ResolutionPreset set to high
![high-simulator](https://user-images.githubusercontent.com/1477356/84818994-3411ea80-afcc-11ea-9291-b93aa1fafca2.PNG)

I also ran flutter analyze
```No issues found! (ran in 6.0s)```

and flutter doctor -v again while connected to my Pixel 3a XL device 
```
[√] Flutter (Channel master, 1.20.0-1.0.pre.73, on Microsoft Windows [Version 10.0.18363.900], locale en-US)
    • Flutter version 1.20.0-1.0.pre.73 at C:\SDKs\flutter
    • Framework revision 95ee633f66 (56 minutes ago), 2020-06-16 15:15:02 -0300
    • Engine revision 965fbbed17
    • Dart version 2.9.0 (build 2.9.0-14.0.dev 2b917f5b6a)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\decol\AppData\Local\Android\sdk
    • Platform android-R, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.45.1)
    • VS Code at C:\Users\decol\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.11.0

[√] Connected device (1 available)
    • Pixel 3a XL • 93LAX08QKJ • android-arm64 • Android 10 (API 29)

• No issues found!
```

@TahaTesser any thoughts?

**Comment by TahaTesser** [comment] 2020-07-01 09:37
since the new issue more info and data 
closing as duplicate of https://github.com/flutter/flutter/issues/60409

**Closed by TahaTesser** 2020-07-01 09:37 UTC
