### ISSUE TITLE
[tool_crash] _CastError: (%230      describeLocale (package:flutter_tools/src/localizations/localizations_utils.dart:219:49))

### ISSUE THREAD

**Issue by xywai1993** [flutter/flutter#102188] opened 2022-04-20 03:05 UTC
%23%23 Command
```
flutter run
```

%23%23 Steps to Reproduce
1. ...
2. ...
3. ...

%23%23 Logs
_CastError: (%230      describeLocale (package:flutter_tools/src/localizations/localizations_utils.dart:219:49))
```
%230      describeLocale (package:flutter_tools/src/localizations/localizations_utils.dart:219:49)
%231      LocalizationsGenerator._generateBaseClassFile (package:flutter_tools/src/localizations/gen_l10n.dart:1137:34)
%232      LocalizationsGenerator._generateCode (package:flutter_tools/src/localizations/gen_l10n.dart:1238:46)
%233      LocalizationsGenerator.writeOutputFiles (package:flutter_tools/src/localizations/gen_l10n.dart:1313:47)
%234      generateLocalizations (package:flutter_tools/src/localizations/gen_l10n.dart:69:9)
%235      GenerateLocalizationsTarget.build (package:flutter_tools/src/build_system/targets/localizations.dart:56:5)
%236      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:839:27)
<asynchronous suspension>
%237      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:606:16)
<asynchronous suspension>
%238      generateLocalizationsSyntheticPackage (package:flutter_tools/src/dart/generate_synthetic_packages.dart:58:30)
<asynchronous suspension>
%239      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1296:7)
<asynchronous suspension>
%2310     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1161:27)
<asynchronous suspension>
%2311     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
%2312     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
%2313     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
<asynchronous suspension>
%2314     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
%2315     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
```
```
[✓] Flutter (Channel stable, 2.10.4, on macOS 12.3.1 21E258 darwin-x64, locale zh-Hans)
    • Flutter version 2.10.4 at /Users/yiper/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (4 weeks ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/yiper/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools

**Comment by danagbemava-nc** [comment] 2022-04-20 07:30
Closing as duplicate of #87851.

Thank you

**Closed by danagbemava-nc** 2022-04-20 07:30 UTC
Labels: in triage
