### ISSUE TITLE
[image_picker] picker.pickImage(source: ImageSource.camera) does not work in web - it opens gallery, not camera

### ISSUE THREAD

**Issue by mikeesouth** [flutter/flutter#93770] opened 2021-11-17 06:35 UTC
`ImagePicker().pickImage(source: ImageSource.camera);` does not open a camera view when called in Flutter for web. It works great on Android and iOS but on web the source parameter does not seem to have any effect. I've also tried to send `preferredCameraDevice: CameraDevice.front` (and the default CameraDevice.rear) but it doesn't help.
I know the camera is working and I'm using it in the same flutter app, in web, but with another library for barcode scanning. So the camera can communicate with my Flutter for web app but image_picker does not seem to open the camera view.

Is this a known limitation, a bug or am I missing something?

## Steps to Reproduce

1. Create a new project, import image_picker library (latest version is currently 0.8.4+4)
2. Call `ImagePicker().pickImage(source: ImageSource.camera);`

**Expected results:** Camera screen opens to let me take a photo and get it as an XFile object

**Actual results:**
* iOS: it works as expected
* Android: it works as expected
* Web _(tested on different browsers on Windows)_: it opens a file explorer window where I can upload files, camera is not activated or displayed - no errors reported.

<details>
  <summary>flutter doctor -v</summary>

```
flutter doctor -v                                            
[√] Flutter (Channel stable, 2.5.3, on Microsoft Windows [Version 10.0.19041.1319], locale sv-SE)       
    • Flutter version 2.5.3 at C:\Stuff\flutter                                                         
    • Upstream repository https://github.com/flutter/flutter.git                                        
    • Framework revision 18116933e7 (5 weeks ago), 2021-10-15 10:46:35 -0700                            
    • Engine revision d3ea636dc5                                                                        
    • Dart version 2.14.4                                                                               
                                                                                                        
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)                        
    • Android SDK at C:\Users\Micke\AppData\Local\Android\sdk                                           
    • Platform android-31, build-tools 31.0.0                                                           
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java                              
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)                            
    • All Android licenses accepted.                                                                    
                                                                                                        
[√] Chrome - develop for the web                                                                        
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe                             
                                                                                                        
[√] Android Studio (version 2020.3)                                                                     
    • Android Studio at C:\Program Files\Android\Android Studio                                         
    • Flutter plugin can be installed from:                                                             
       https://plugins.jetbrains.com/plugin/9212-flutter                                                
    • Dart plugin can be installed from:                                                                
       https://plugins.jetbrains.com/plugin/6351-dart                                                   
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)                            
                                                                                                        
[√] VS Code (version 1.62.2)                                                                            
    • VS Code at C:\Users\Micke\AppData\Local\Programs\Microsoft VS Code                                
    • Flutter extension version 3.26.0                                                                  
                                                                                                        
[√] Connected device (2 available)                                                                      
    • Chrome (web) • chrome • web-javascript • Google Chrome 95.0.4638.69                               
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 95.0.1020.44                              
                                                                                                        
• No issues found!                                                                                      
```

</details>

**Comment by mamuseferha** [comment] 2021-11-17 07:53
Hi @mikeesouth 
The camera from image_picker works fine on some mobile browsers, on desktop, it is the browser limitation, please see https://pub.dev/packages/image_picker_for_web#input-file-capture
Closing, as duplicate of #85195
Thank you

**Closed by mamuseferha** 2021-11-17 07:53 UTC
Labels: in triage
