### ISSUE TITLE
SHIFT key does not work correctly in TextField widget (Flutter 2.0.1 Desktop Windows - Beta Channel)

### ISSUE THREAD

**Issue by Josua2012** [flutter/flutter#77537] opened 2021-03-07 22:02 UTC
Hi,
When starting to write in TextField widget, the SHIFT key is clicked at the same time that a key is pressed to display the uppercase character, when the SHIFT key is released the following characters are still written in uppercase, when they should be written in lowercase.
If I try to write "España", when I click on the shift key to capitalize the character "E", then I release the shift key, but all the rest of the characters are also capitalized "ESPAÑA". 
Therefore, flutter desktop windows cannot be used to develop desktop Windows applications for production. 
Neither Flutter version of either channel solves this problem.
Regards,
Jose.

**Comment by stuartmorgan** [comment] 2021-03-07 22:44
Duplicate of https://github.com/flutter/flutter/issues/75675

**Comment by stuartmorgan** [comment] 2021-03-07 22:45
> flutter desktop windows cannot be used to develop desktop Windows applications for production

It's a beta; it's not yet intended for production use.

**Closed by stuartmorgan** 2021-03-07 22:44 UTC

**Comment by Josua2012** [comment] 2021-03-07 22:58
But they are very severe problems that make it completely impossible to make applications a little useful at the moment. :(
I think that in a beta this kind of obvious problems should be solved quickly. 
I have seen in many of your current information that you put examples of multiplatform applications, but with these types of problems they can give the product very bad publicity ... 
Thanks Stuart.
Regards,
Jose
