### ISSUE TITLE
Can't use flutter after Android Studio update. Please help

### ISSUE THREAD

**Issue by Sh00ny** [flutter/flutter#68178] opened 2020-10-15 06:53 UTC
C:\Users\Shoony>flutter doctor

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 1.22.1, on Microsoft Windows [Version 10.0.19041.572], locale en-IN)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[!] Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    X android-studio-dir = =C:\Program Files\Android\Android Studio^Z^Z
    X Android Studio not found at =C:\Program Files\Android\Android Studio^Z^Z
[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.

C:\Users\Shoony>flutter doctor --android-licenses
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
        at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
        at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
        at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:606)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:168)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 5 more

- Some on stackoverflow suggested this to change dir of android studio.
- I'm novice to SD

<img width="567" alt="issue" src="https://user-images.githubusercontent.com/64748053/96087971-59632680-0ee2-11eb-8101-d37b1c25ca2e.png">
  X android-studio-dir = =C:\Program Files\Android\Android Studio^Z^Z

**Comment by hamdikahloun** [comment] 2020-10-15 07:53
Hi @Sh00ny 
Possible duplicated issue #62924 .
Thank you

**Comment by pedromassangocode** [comment] 2020-10-15 09:50
Yes this is a duplicate of https://github.com/flutter/flutter/issues/62924.

@Sh00ny please follow the logs instructions to finish setup Android Studio. If that does not works for you you may want to try https://github.com/flutter/flutter/issues/62924#issuecomment-668958881 and see if it works for you.

Closing as duplicate.

**Closed by pedromassangocode** 2020-10-15 09:50 UTC

**Comment by Sh00ny** [comment] 2020-10-15 10:36
> Yes this is a duplicate of #62924.
> 
> @Sh00ny please follow the logs instructions to finish setup Android Studio. If that does not works for you you may want to try [#62924 (comment)](https://github.com/flutter/flutter/issues/62924#issuecomment-668958881) and see if it works for you.
> 
> Closing as duplicate.

Can you please give me step by step instructions? I'm new to programming. I'm using windows.

**Comment by pedromassangocode** [comment] 2020-10-15 11:45
You can follow the steps described in https://flutter.dev/docs/get-started/install/windows#android-setup

**Comment by Sh00ny** [comment] 2020-10-15 11:49
> You can follow the steps described in https://flutter.dev/docs/get-started/install/windows#android-setup

You mean I have to reinstall android studio and all this setup?

**Comment by pedromassangocode** [comment] 2020-10-15 12:32
No, just follow the steps that are required.

**Comment by Sh00ny** [comment] 2020-10-16 02:17
> No, just follow the steps that are required.

Followed the steps yet same error. Nothing got fixed.

**Comment by Sh00ny** [comment] 2020-10-16 03:13
Thank you all for your efforts and help.
I managed to solve the issue. It was java that was causing issue.
I reinstalled Java 8 and it works.
