### ISSUE TITLE
`primary` not the same color as the seed when using Material 3

### ISSUE THREAD

**Issue by cirediew** [flutter/flutter#98658] opened 2022-02-17 13:50 UTC
I was playing around with the new Material3 colors and the theme data, and I noticed `primary` in the `ColorScheme` is not the same color as the one I provided as `colorSchemeSeed`. It is significantly darker.

It looks ok for the theme when using `Brightness.dark`, but it differs slightly too.

How do I get them to be the same? Or is this by design?

> seed: `Color(0xff93c741)`
> (Brightness.light) primary: `Color(0xff436900)`
> (Brightness.dark) primary: `Color(0xffa2d74f)`

![MaterialColors](https://user-images.githubusercontent.com/9058616/154490091-d41e2a8f-69a0-42a9-851e-8db90dacbba1.png)

my code:
```dart
  @override
  Widget build(BuildContext context) {
    var color = const Color(0xFF93C741);
    return Scaffold(
      body: ListView.builder(
        itemCount: 1,
        itemBuilder: (_, __) {
          return Theme(
            data: ThemeData(
              colorSchemeSeed: color,
              brightness: context.theme.brightness,
              useMaterial3: true,
            ),
            child: Builder(
              builder: (context) {
                print(color.toString());
                print(context.theme.colorScheme.primary.toString());
                return Column(
                  children: [
                    Text(
                      color.toString(),
                      style: context.bodyText1!.copyWith(
                        fontSize: 18,
                        backgroundColor: color,
                      ),
                    ),
                    Text(
                      'Theme',
                      style: context.bodyText1!.copyWith(fontSize: 18),
                    ),
                    Column(
                      children: List.generate(
                        context.theme.allColors.length,
                        (index) {
                          final MapEntry<String, Color> colorEntry =
                              context.theme.allColors.entries.elementAt(index);
                          return Container(
                            color: colorEntry.value,
                            width: double.infinity,
                            child: Text(
                              colorEntry.key,
                              style: TextStyle(backgroundColor: context.theme.canvasColor),
                            ),
                          );
                        },
                      ),
                    ),
                    Text(
                      'ColorScheme',
                      style: context.bodyText1!.copyWith(fontSize: 18),
                    ),
                    Column(
                      children: List.generate(
                        context.theme.allColors.length,
                        (index) {
                          final MapEntry<String, Color> colorEntry = context
                              .theme.colorScheme.allColors.entries
                              .elementAt(index);
                          return Container(
                            color: colorEntry.value,
                            width: double.infinity,
                            child: Text(
                              colorEntry.key,
                              style: TextStyle(backgroundColor: context.theme.canvasColor),
                            ),
                          );
                        },
                      ),
                    ),
                  ],
                );
              },
            ),
          );
        },
      ),
    );
  }

```
```dart

extension ThemeDataExtension on ThemeData {
  Map<String, Color> get allColors => {
        'primaryColor': primaryColor,
        'primaryColorLight': primaryColorLight,
        'primaryColorDark': primaryColorDark,
        'focusColor': focusColor,
        'hoverColor': hoverColor,
        'shadowColor': shadowColor,
        'canvasColor': canvasColor,
        'scaffoldBackgroundColor': scaffoldBackgroundColor,
        'bottomAppBarColor': bottomAppBarColor,
        'cardColor': cardColor,
        'dividerColor': dividerColor,
        'highlightColor': highlightColor,
        'splashColor': splashColor,
        'selectedRowColor': selectedRowColor,
        'unselectedWidgetColor': unselectedWidgetColor,
        'disabledColor': disabledColor,
        'secondaryHeaderColor': secondaryHeaderColor,
        'backgroundColor': backgroundColor,
        'dialogBackgroundColor': dialogBackgroundColor,
        'indicatorColor': indicatorColor,
        'hintColor': hintColor,
        'errorColor': errorColor,
        'toggleableActiveColor': toggleableActiveColor,
      };
}

extension ColorSchemeExtension on ColorScheme {
  Map<String, Color> get allColors => {
        'surface': surface,
        'onSurface': onSurface,
        'surfaceVariant': surfaceVariant,
        'onSurfaceVariant': onSurfaceVariant,
        'inverseSurface': inverseSurface,
        'onInverseSurface': onInverseSurface,
        'background': background,
        'onBackground': onBackground,
        'primary': primary,
        'onPrimary': onPrimary,
        'inversePrimary': inversePrimary,
        'secondary': secondary,
        'onSecondary': onSecondary,
        'tertiary': tertiary,
        'onTertiary': onTertiary,
        'primaryContainer': primaryContainer,
        'onPrimaryContainer': onPrimaryContainer,
        'secondaryContainer': secondaryContainer,
        'onSecondaryContainer': onSecondaryContainer,
        'tertiaryContainer': tertiaryContainer,
        'onTertiaryContainer': onTertiaryContainer,
        'error': error,
        'onError': onError,
        'errorContainer': errorContainer,
        'onErrorContainer': onErrorContainer,
      };
}
```

**Comment by rydmike** [comment] 2022-02-17 17:32
@cirediew This is expected behavior when using a **primary** color as **seed color**. What happens is that the provided color, functions as a single key color to generate 3 different tonal palettes with 13 different tones each.

## Primary Tonal Palette
The **seed color** is used directly to create the tonal palette for primary tones. The `ColorScheme.primary` is then assigned tone 40 for light mode and tone 80 for dark mode, from the same tonal palette. Neither of these colors will be an exact match for the "primary" seed color you used, it will be a color from a tonal palette that matches the seed color, since it is the primary one. 

### Branding challange
If you for branding purposes require it to exactly match the provided seed color, you can always override `ColorScheme.primary` you got with `copyWith` using the original **seed color**. And then use that `ColorScheme` as input to your apps `ThemeData`. A bit of an extra step, but it will work and look OK too, because for primaries the other colors will still match and be in sync with this color.

## Secondary and Tertiary Tonal Palette

When using the `ColorScheme.fromSeed`, it also uses color math to from the seed color, generate key colors that are used to generate the two tonal palettes for `secondary`, `tertiary` and their related colors. that it in similar fashion uses given tones from those palettes to assign appropriate tone color values from for light and dark brightness to the produced `ColorScheme`. 

Using `ColorScheme.fromSeed` does however not provide any properties that you could use to optionally pass in key colors to use as specific seed colors for the accent and tertiary tonal palettes. This is doable, but you then have to look into how `ColorScheme.fromSeed` is working and make custom version of it and he `CorePalette` it uses. (Or you can extend the `CorePalette` but only via its cumbersome `fromList` constructor, it is not very extension friendly).

## More info

More info about principles of M3 tonal palettes can be found here: https://m3.material.io/styles/color/the-color-system/key-colors-tones

The algorithms that `ColorScheme.from` uses can be found in this package: https://pub.dev/packages/material_color_utilities
When you dig (click into) into what `ColorScheme.fromSeed`actually does, it is using that package. The Flutter SDK actually currently depends on this package in its pubspec yaml and `ColorScheme` class uses it.

## A bit off topic

I'm working on some updates to may FlexColorScheme package to provide built in support for tonal palettes, while also providing key colors for primary and optional ones for secondary and tertiary, **plus optionally** keeping  select color values at given input values, for branding purposes obviously. While still getting the benefits of auto seeded colors and shade for all things that that should just be in general tone of the "brand" color. That is why I kind of had to dig a bit deeper into this to understand how it works.

**Comment by cirediew** [comment] 2022-02-18 09:18
@rydmike Thank you so much for your answer and extended explanation. I figured I could use `copyWith` to get my desired results. It just didn't work as I thought it would and that made me curious. Your answer will definitely help others with the same question. 

Maybe the docs could do with a little more clarification to void confusion on the working of it.

**Comment by darrenaustin** [comment] 2022-02-22 07:56
As @rydmike already pointed out in detail above (thx Mike!), this is a possibility of given the algorithm used to generate the the color scheme. This is working as intended.

> Maybe the docs could do with a little more clarification to void confusion on the working of it.

It is part of the documentation for `ColorScheme.fromSeed`: 

```dart
  /// Given the nature of the algorithm, the seedColor may not wind up as
  /// one of the ColorScheme colors.
```

A little terse perhaps, but I am not sure what more we should add here to make it clearer.

I'm going to close this as working as intended. If you have suggestions for doc enhancements for this, please open a separate issue with the suggestions. Thx.

**Closed by darrenaustin** 2022-02-22 07:56 UTC
Labels: framework, f: material design
