### ISSUE TITLE
iOS app crash when toggle airplane mode in debug

### ISSUE THREAD

**Issue by Tom3652** [flutter/flutter#109621] opened 2022-08-16 17:11 UTC
## Steps to Reproduce

1. Run the `flutter create .` command to create a new project (the counter basic app)
2. Run in debug mode on a physical iOS device
3. Toggle airplane mode
4. See the app crashing

I actually don't see any crash logs, only `lost connection to device` but it's 100% reproductible on the latest flutter version on master branch.

This is quite painful as we can't test our app behavior without internet connection on iOS.

<details>
<summary>Logs</summary>

```
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.5 21G72 darwin-x64, locale fr-FR)
    • Flutter version 3.0.5 at /Users/foxtom/Desktop/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (5 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/foxtom/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.70.1)
    • VS Code at /Users/foxtom/Desktop/Visual Studio Code.app/Contents
    • Flutter extension version 3.46.0

[✓] Connected device (3 available)
    • Now You See Me (mobile) • 00008020-001204401E78002E • ios            • iOS 15.6 19G71
    • macOS (desktop)         • macos                     • darwin-x64     • macOS 12.5 21G72 darwin-x64
    • Chrome (web)            • chrome                    • web-javascript • Google Chrome 104.0.5112.79
    ! Error: Now You See Me is busy: Fetching debug symbols for Now You See Me. Xcode will continue when Now You See Me is finished. (code -10)

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by danagbemava-nc** [comment] 2022-08-18 07:17
Hi @Tom3652, I believe this is a duplicate of https://github.com/flutter/flutter/issues/93153. 

Kindly follow up in the linked issue for updates. 

Closing from here as duplicate. 

If you disagree, kindly leave a comment below and I will reopen this. 

Thank you

**Closed by danagbemava-nc** 2022-08-18 07:17 UTC
Labels: in triage

**Comment by Tom3652** [comment] 2022-08-18 07:33
Hey @danagbemava-nc you are right !

However i am facing this in the latest `flutter: 3.0.5` on the stable branch, and the other issue has no tags for flutter `3.0.+`

Anyway it's the same issue

**Comment by danagbemava-nc** [comment] 2022-08-18 08:05
That issue hasn't been visited since it was triaged, that's why. The labels will need to be updated

**Comment by Tom3652** [comment] 2022-08-18 08:51
Alright thanks
