### ISSUE TITLE
PaginatedDataTable controls should handle overflow

### ISSUE THREAD

**Issue by cbracken** [flutter/flutter#7980] opened 2017-02-08 20:28 UTC
## Steps to Reproduce

Create a table with enough rows that the '1 of N' text at the bottom is wide enough to cause the Prev/Next controls to overflow the screen width. Even a table 10s of rows long is enough to overflow the text on an iPhone SE.

We should support scrolling or wrapping the pagination controls in such a case. Particularly once we have localised text, whether or not this happens will become a function of how long the localised text is.

![simulator screen shot 8 feb 2017 12 48 50](https://cloud.githubusercontent.com/assets/351029/22756732/f52b6114-edfc-11e6-8cfe-f804e2f9f8f8.png)

**Comment by Hixie** [comment] 2017-12-14 01:30
Dupe of https://github.com/flutter/flutter/issues/5011

**Closed by Hixie** 2017-12-14 01:30 UTC
Labels: prod: framework, prod: material design
