### ISSUE TITLE
im not able to pass query params in urm its working in 3.22.3 but not in flutter 3.24.0

### ISSUE THREAD

**Issue by chandrashekharanvr** [flutter/flutter#153679] opened 2024-08-19 07:51 UTC
### Steps to reproduce

Refused to execute script from 'http://localhost:37753/myprofile/main.dart.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.

### Actual results

Refused to execute script from 'http://localhost:37753/myprofile/main.dart.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.

### Logs

<details open>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

<details open>
<summary>Doctor output</summary>

```console

<!-- Paste your output here -->

```

</details>

**Comment by tungxixoan** [comment] 2024-08-19 08:39
https://github.com/flutter/flutter/issues/152995
--
Check this issue with this link

**Comment by chandrashekharanvr** [comment] 2024-08-19 11:19
> ## #152995
> Check this issue with this link

hi @tungxixoan  im using go_router 14.2.3 and this is my main page import 'package:flutter/material.dart';
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:nfc_mobile/app_routes/navigation_service.dart';
import 'package:nfc_mobile/service_locator.dart';
import 'package:url_strategy/url_strategy.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await dotenv.load(fileName: '.env');
  setPathUrlStrategy();
  setupLocator();
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(
      debugShowCheckedModeBanner: false,
      title: 'Flutter Demo',
      routerConfig: sl<NavigationService>().router,
    );
  }
}
 here im wrapping setPathUrlStrategy() and import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import 'package:nfc_mobile/app_routes/route_paths.dart';
import 'package:nfc_mobile/features/screens/login_screen/login_screen.dart';
import 'package:nfc_mobile/features/screens/profilescreen/profile_screen.dart';
import 'package:nfc_mobile/features/screens/updateScreen/update.dart';

class NavigationService {
  static final _rootNavigatorKey = GlobalKey<NavigatorState>();

  final GoRouter router = GoRouter(
    initialLocation: MyPaths.initial.value,
    navigatorKey: _rootNavigatorKey,
    routes: <RouteBase>[
      GoRoute(
        path: MyPaths.initial.value,
        name: MyPaths.initial.value,
        builder: (BuildContext context, GoRouterState state) {
          return LoginScreen();
        },
        routes: <RouteBase>[
          GoRoute(
            path: MyPaths.login.value,
            name: MyPaths.login.value,
            builder: (BuildContext context, GoRouterState state) {
              return const LoginScreen();
            },
          ),
          GoRoute(
            path: MyPaths.update.value,
            name: MyPaths.update.value,
            builder: (BuildContext context, GoRouterState state) {
              return const UpdateScreen();
            },
          ),
          GoRoute(
            path: 'myprofile/:name',
            name: MyPaths.myprofile.value,
            pageBuilder: (context, state) {
              String name = state.pathParameters['name'].toString();

              return MaterialPage<dynamic>(
                child: MyProfileScreen(
                  name: name.toString(),
                ),
              );
            },
          ),
        ],
      ),
    ],
  );

  void navigateToRoute(String routeName) {
    router.pushNamed(routeName);
    GoRouter.optionURLReflectsImperativeAPIs = true;
  }

  void navigateToHome() {
    router.goNamed(MyPaths.initial.value);
    GoRouter.optionURLReflectsImperativeAPIs = true;
  }
}
this is my navigation file here 'myprofile/:name', im sending   name as queryparams and its working fine in flutter version 3.22.3 and for 3.24.0 its giving me this error 
![Screenshot from 2024-08-19 16-47-23](https://github.com/user-attachments/assets/652634f8-f2d5-4766-8d83-80480873e4e2)

**Comment by danagbemava-nc** [comment] 2024-08-19 13:12
Closing this as a duplicate of https://github.com/flutter/flutter/issues/152995

**Closed by danagbemava-nc** 2024-08-19 13:12 UTC
Labels: in triage
