### ISSUE TITLE
PlatformException(multiple_request, Cancelled by a second request, null, null)

### ISSUE THREAD

**Issue by devhch** [flutter/flutter#109656] opened 2022-08-17 03:28 UTC
PlatformException(multiple_request, Cancelled by a second request, null, null) in
 image_picker: ^0.8.5+3

    • iOS 15.5
    • Flutter version 3.0.5 
    • Dart version 2.17.6
    • DevTools version 2.12.2

**Comment by exaby73** [comment] 2022-08-18 08:07
Duplicate of https://github.com/flutter/flutter/issues/82602

**Closed by exaby73** 2022-08-18 08:07 UTC
Labels: in triage
