### ISSUE TITLE
Flutter crashes when trying to run on the web: flutter run -d chrome

### ISSUE THREAD

**Issue by blessedmadukoma** [flutter/flutter#74985] opened 2021-01-29 15:35 UTC
When I try running flutter run -d chrome, flutter crashes. I use Linux Mint 20, and I am on the flutter dev channel

Launching lib/main.dart on Chrome in debug mode...
Waiting for connection from debug service on Chrome...             91.5s

Oops; flutter has exited unexpectedly: "HttpException: , uri =
http://localhost:36085/devtools/page/299EC87B6C740AF6069A957959779338".
A crash report has been written to
/home/skillz/Desktop/Code/Flutter/Web/first/firstweb/flutter_02.log.

**Comment by herzog0** [comment] 2021-01-30 06:06
The same happened to me. 
The content of flutter log file is:  
```
Flutter crash report.
Please report a bug at https://github.com/flutter/flutter/issues.

## command

flutter run -d chrome

## exception

HttpException: HttpException: , uri = http://localhost:38853/devtools/page/8ACEE6C40CB4EC5A37656056DF23C09B


## flutter doctor


[✓] Flutter (Channel master, 1.26.0-18.0.pre.88, on Linux, locale en_US.UTF-8)
    • Flutter version 1.26.0-18.0.pre.88 at /home/mypc/snap/flutter/common/flutter
    • Framework revision 87b043658b (6 hours ago), 2021-01-29 15:46:21 -0800
    • Engine revision ce14c8a841
    • Dart version 2.12.0 (build 2.12.0-276.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/mypc/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /home/mypc/Android/Sdk
    • ANDROID_SDK_ROOT = /home/mypc/Android/Sdk
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /usr/bin/chromium

[✓] Android Studio
    • Android Studio at /opt/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.3)
    • IntelliJ at /home/mypc/.local/share/JetBrains/Toolbox/apps/IDEA-U/ch-0/203.6682.168
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Community Edition (version 2020.3)
    • IntelliJ at /home/mypc/.local/share/JetBrains/Toolbox/apps/IDEA-C/ch-0/203.6682.168
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Chromium 87.0.4280.141 Arch Linux

• No issues found!
```

**Comment by blessedmadukoma** [comment] 2021-01-30 06:45
yes so how do I fix it, I was on the dev channel since I could not enter
beta channel

**Comment by herzog0** [comment] 2021-01-30 23:39
I don't know but, oddly enough, the problem didn't happen on the latest stable Linux Mint (I believe LM version 20.1). 
Currently I'm using Manjaro, which is an Arch based distribution.  
@blessedmadukoma for the sake of gathering patterns around the error, what operational system are you using? And, if it is a GNU/Linux system, could you provide your distribution as well?

**Comment by blessedmadukoma** [comment] 2021-01-31 02:09
OK, I'm using the debian distribution Linux mint 20.0 version... I think
it's named ulyana

**Comment by herzog0** [comment] 2021-01-31 05:22
Very weird problem.. It seems that flutter team cannot reproduce the error (saw in another issue). I've now changed my whole distribution to stop this error and succeeded.  
If possible, try installing the newest linux mint version and apt updating/upgrading it.

**Comment by blessedmadukoma** [comment] 2021-01-31 05:32
Ok, thanks.

**Comment by TahaTesser** [comment] 2021-02-01 08:04
Hi @blessedmadukoma 
This seems to be dIstro specific on Flutter snap, and you seem to be using the Flutter snap too. https://github.com/flutter/flutter/issues/73976
Can you please try manual installation https://github.com/flutter/flutter/issues/73976#issuecomment-763433499
This solved the issue in https://github.com/flutter/flutter/issues/73976#issuecomment-763857344 
Thank you

**Comment by blessedmadukoma** [comment] 2021-02-01 08:14
Ok, I'll check it out. Thanks

**Comment by blessedmadukoma** [comment] 2021-02-01 08:29
Please concerning the installation... How do I install it and not have any
issues with it? I am reading the docs but it seems I'll have issues when
installing it. I tried installation before but it did not work out

**Comment by blessedmadukoma** [comment] 2021-02-01 08:37
Also, on the docs, I'll be installing from the flutter repository, how do I
change to the beta channel after installing from the repo?

Thank you

**Comment by TahaTesser** [comment] 2021-02-01 09:07
@blessedmadukoma 
Please check out https://github.com/flutter/flutter/issues/75073#issuecomment-770433088 and you can change your channel using https://flutter.dev/docs/development/tools/sdk/upgrading#switching-flutter-channels
Manual Installation confirmed to be working for this
Closing as duplicate
For issues related to Flutter snap, please file an issue on their dedicated GitHub [repositoy](https://github.com/canonical/flutter-snap/issues).
Thank you

**Closed by TahaTesser** 2021-02-01 09:07 UTC
Labels: in triage

**Comment by blessedmadukoma** [comment] 2021-02-01 09:50
OK thank you very much

**Comment by blessedmadukoma** [comment] 2021-02-01 13:18
Please I'd like to ask, do I install flutter into the /usr/local or just
the $home directory?

**Comment by TahaTesser** [comment] 2021-02-01 13:22
@blessedmadukoma 
$HOME is fine

**Comment by blessedmadukoma** [comment] 2021-02-01 13:26
Thank you!

**Comment by blessedmadukoma** [comment] 2021-02-01 14:36
Please, I have one question. If I create a flutter web app on the beta
channel, can I change back to the stable channel and continue coding the
app? Or do I have to stay in the beta channel until I am completely done
with the app I'm building?

Thank you

**Comment by TahaTesser** [comment] 2021-02-02 06:56
@blessedmadukoma 
`stable` channel doesn't have web support yet, If you want to continue working on the web, stay on the `beta` channel, it's a relatively reliable channel.

**Comment by blessedmadukoma** [comment] 2021-02-02 07:05
Thank you! It is working now. Really appreciate

**Comment by iapicca** [comment] 2021-02-06 18:33
this is a snap installation issue, follow up [here](https://github.com/canonical/flutter-snap/issues/23)

**Comment by blessedmadukoma** [comment] 2021-02-06 22:38
Thank you!
