### ISSUE TITLE
Toolbar clipped by status bar on Galaxy Tab E

### ISSUE THREAD

**Issue by nelsonkam** [flutter/flutter#6586] opened 2016-10-28 23:44 UTC
I just tested the Gallery app on my tablet (Samsung Galaxy Tab E) and I ran into an issue. The toolbar or at least a portion of the upper part of UI is cropped.
![screenshot_2016-10-29-00-29-02](https://cloud.githubusercontent.com/assets/8492909/19825397/7f43bd84-9d70-11e6-950d-d6b4cbd42d68.png)
## Flutter Version

Flutter • channel master • https://github.com/flutter/flutter.git
Framework • revision b41645cc17 (2 hours ago) • 2016-10-28 14:37:17
Engine • revision 1bc79ded38
Tools • Dart 1.21.0-dev.2.0

**Comment by abarth** [comment] 2016-10-29 00:00
Yep!  Duplicate of #6060

**Comment by nelsonkam** [comment] 2016-10-29 00:12
@abarth The issue here is not the layout as in #6060 but the cut on the toolbar. By the way the screenshot in #6060 does have the "cut toolbar" issue.

**Comment by abarth** [comment] 2016-10-29 00:23
Ah, my mistake.  Thanks!

**Comment by glenfordwilliams** [comment] 2016-11-04 22:41
having a similar issue on both a amazon kindle fire and huawei y600. meanwhile it Works well on my gallaxy note 3


----kindle---
![photo_2016-11-04_17-35-40](https://cloud.githubusercontent.com/assets/1114368/20024516/2c15c158-a2b5-11e6-9d15-f067da1fe2d1.jpg)


--huawei--

![photo_2016-11-04_17-36-47](https://cloud.githubusercontent.com/assets/1114368/20024538/4ef4fcca-a2b5-11e6-9722-721f2922bdc1.jpg)


Flutter Doctor 

```
[✓] Flutter (on Linux, channel master)
    • Flutter at /home/kingwill101/flutter
    • Framework revision 9b7764d48f (83 minutes ago), 2016-11-04 14:06:44
    • Engine revision 16077d474b
    • Tools Dart version 1.21.0-dev.3.0

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.0)
    • Android SDK at /home/kingwill101/Android/Sdk
    • Platform android-25, build-tools 25.0.0
    • OpenJDK Runtime Environment (build 1.8.0_111-8u111-b14-2ubuntu0.16.10.2-b14)

[✓] IntelliJ IDEA Community Edition (version 2016.2)
    • Dart plugin installed
    • Flutter plugin installed

[✓] Connected devices
    • KFARWI • 00DA080744750U4G • android-arm • Android 4.4.3 (API 19)
      • HUAWEI Y600 U151 • 9SDA6D6TCMJBU8YL • android-arm • Android 4.2.2 (API 17)

```

**Comment by glenfordwilliams** [comment] 2016-11-04 22:43
In previous testing a few months back everything rendered fine on both devices, so there is a regression somewhere

**Comment by eseidelGoogle** [comment] 2016-11-04 22:46
I suspect this is likely due to us not correctly handling Android 4.2 correctly and needing to adjust to account for an opaque status bar?  Probably this line:
https://github.com/flutter/engine/blob/eb25d718b0a7bcfac2710698911bec5f3c075223/shell/platform/android/org/domokit/sky/shell/SkyActivity.java#L51 needs to also know to adjust the screen region for the framework to draw in?

**Comment by eseidelGoogle** [comment] 2016-11-04 22:46
@jason-simmons is probably the right person to ask.

**Comment by Camron** [comment] 2017-01-02 14:01
I'm getting this on a Samsung Galaxy S 3 as well.

**Comment by eseidelGoogle** [comment] 2017-01-03 06:26
The solution to this is going to be somewhat similar to what we have to do on iOS for https://github.com/flutter/flutter/issues/5327.  I think we have to recognize that we're on an older version of Android which does not support transparent status bars, and adjust the window rect we send from the engine up to the framework.  Thoughts?

**Comment by eseidelGoogle** [comment] 2017-01-05 15:13
@jason-simmons This is probably an easy fix.

**Closed** 2017-01-17 23:36 UTC
Labels: prod: engine, regression, ▣ platform-android
