### ISSUE TITLE
[tool_crash] FileSystemException: Cannot create link, OS Error: Incorrect function., errno = 1

### ISSUE THREAD

**Issue by ssss500** [flutter/flutter#136410] opened 2023-10-11 20:57 UTC
## Command
```
flutter --no-color pub get
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Cannot create link, OS Error: Incorrect function.
, errno = 1
```
#0      _Link.throwIfError (dart:io/link.dart:254:7)
#1      _Link.createSync (dart:io/link.dart:182:5)
#2      ForwardingLink.createSync (package:file/src/forwarding/forwarding_link.dart:20:16)
#3      ForwardingLink.createSync (package:file/src/forwarding/forwarding_link.dart:20:16)
#4      _createPlatformPluginSymlinks (package:flutter_tools/src/flutter_plugins.dart:1055:12)
#5      createPluginSymlinks (package:flutter_tools/src/flutter_plugins.dart:985:5)
#6      refreshPluginsList (package:flutter_tools/src/flutter_plugins.dart:1087:5)
<asynchronous suspension>
#7      FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:359:5)
<asynchronous suspension>
#8      PackagesGetCommand.runCommand (package:flutter_tools/src/commands/packages.dart:365:7)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1323:27)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#11     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:348:9)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:294:5)
<asynchronous suspension>
#15     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:113:9)
```
```
[✓] Flutter (Channel beta, 3.15.0-15.2.pre, on Microsoft Windows [Version 10.0.22621.2428], locale en-US)
    • Flutter version 3.15.0-15.2.pre on channel beta at C:\Users\saif\Documents\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 0d074ced6c (3 weeks ago), 2023-09-21 10:24:15 -0700
    • Engine revision 453411bcf3
    • Dart version 3.2.0 (build 3.2.0-134.1.beta)
    • DevTools version 2.27.0

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✗] Android toolchain - develop for Android devices
    • Android SDK at C:\Users\saif\AppData\Local\Android\sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.

[✗] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.7.4)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.7.34031.279
    • Windows 10 SDK version 10.0.22621.0

[✓] Android Studio (version 2022.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)

[✓] Connected device (2 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22621.2428]
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 117.0.2045.60

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: beta
**Creation framework version**: b1c77b7ed32346fe829c0ca97bd85d19290d54ae
### Plugins
connectivity_plus-3.0.6
desktop_window-0.4.0
device_info_plus-9.0.3
firebase_core-2.16.0
firebase_core_web-2.8.0
firebase_messaging-14.6.8
firebase_messaging_web-3.5.7
flutter_barcode_scanner-2.0.0
flutter_pdfview-1.3.1
flutter_plugin_android_lifecycle-2.0.16
package_info_plus-4.1.0
path_provider-2.1.1
path_provider_android-2.2.0
path_provider_foundation-2.3.1
path_provider_linux-2.2.1
path_provider_windows-2.2.1
permission_handler-11.0.0
permission_handler_android-11.0.5
permission_handler_apple-9.1.4
permission_handler_windows-0.1.3
root-2.0.4
screen_protector-1.3.1
screen_retriever-0.1.9
share_plus-7.1.0
shared_preferences-2.2.1
shared_preferences_android-2.2.1
shared_preferences_foundation-2.3.4
shared_preferences_linux-2.3.1
shared_preferences_web-2.2.1
shared_preferences_windows-2.3.1
sqflite-2.3.0
syncfusion_flutter_pdfviewer-23.1.38
syncfusion_pdfviewer_macos-23.1.38
syncfusion_pdfviewer_web-23.1.38
syncfusion_pdfviewer_windows-23.1.38
url_launcher-6.1.14
url_launcher_android-6.1.0
url_launcher_ios-6.1.5
url_launcher_linux-3.0.6
url_launcher_macos-3.0.7
url_launcher_web-2.0.20
url_launcher_windows-3.0.8
video_player-2.7.2
video_player_android-2.4.10
video_player_avfoundation-2.5.0
video_player_web-2.1.1
wakelock_plus-1.1.1
webview_flutter-4.2.4
webview_flutter_android-3.10.1
webview_flutter_wkwebview-3.8.0
window_manager-0.3.6
windows_single_instance-1.0.0

**Comment by huycozy** [comment] 2023-10-12 05:34
Closing this as a duplicate of https://github.com/flutter/flutter/issues/66224.

**Closed by huycozy** 2023-10-12 05:34 UTC
Labels: in triage
