### ISSUE TITLE
[☠] Visual Studio - develop for Windows (the doctor check crashed)

### ISSUE THREAD

**Issue by hardik584** [flutter/flutter#40522] opened 2019-09-15 12:19 UTC
F:\work\examples\keyboard_event>flutter doctor -v
[√] Flutter (Channel master, v1.10.2-pre.36, on Microsoft Windows [Version 10.0.17134.1006], locale en-IN)
    • Flutter version 1.10.2-pre.36 at C:\flutter
    • Framework revision 32c946f31b (4 days ago), 2019-09-10 20:49:27 -0700
    • Engine revision 7ea9884ab0
    • Dart version 2.5.0 (build 2.5.0-dev.4.0 be66176534)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\User\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = C:\Users\User\AppData\Local\Android\Sdk
    • ANDROID_SDK_ROOT = C:\Users\User\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[☠] Visual Studio - develop for Windows (the doctor check crashed)
    X Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this
      issue at https://github.com/flutter/flutter/issues.
    X type 'String' is not a subtype of type 'bool'
    • #0      VisualStudio.isPrerelease (package:flutter_tools/src/windows/visual_studio.dart:40:7)
      #1      VisualStudioValidator.validate (package:flutter_tools/src/windows/visual_studio_validator.dart:33:24)
      <asynchronous suspension>
      #2      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      <asynchronous suspension>
      #3      _rootRun (dart:async/zone.dart:1124:13)
      #4      _CustomZone.run (dart:async/zone.dart:1021:19)
      #5      _runZoned (dart:async/zone.dart:1516:10)
      #6      runZoned (dart:async/zone.dart:1500:12)
      #7      asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #8      Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:151:11)
      #9      Doctor.diagnose (package:flutter_tools/src/doctor.dart:244:41)
      #10     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
      #11     Doctor.diagnose (package:flutter_tools/src/doctor.dart:234:24)
      #12     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:59:39)
      #13     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
      #14     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:45:42)
      #15     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:490:18)
      #16     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
      #17     _rootRunUnary (dart:async/zone.dart:1132:38)
      #18     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
      #19     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
      #20     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
      #21     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
      #22     Future._completeWithValue (dart:async/future_impl.dart:522:5)
      #23     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552:7)
      #24     _rootRun (dart:async/zone.dart:1124:13)
      #25     _CustomZone.run (dart:async/zone.dart:1021:19)
      #26     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
      #27     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
      #28     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
      #29     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
      #30     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
      #31     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 38.2.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] IntelliJ IDEA Community Edition (version 2019.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.1.1
    • Flutter plugin version 36.0.4
    • Dart plugin version 191.7830

[√] VS Code, 64-bit edition (version 1.38.0)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.4.1

[√] Connected device (3 available)
    • Windows • Windows • windows-x64    • Microsoft Windows [Version 10.0.17134.1006]
    • Chrome  • chrome  • web-javascript • Google Chrome 77.0.3865.75
    • Server  • web     • web-javascript • Flutter Tools

! Doctor found issues in 1 category.

F:\work\examples\keyboard_event>

**Comment by stuartmorgan** [comment] 2019-09-15 12:38
Duplicate of #40238 (which is already fixed)

**Closed by stuartmorgan** 2019-09-15 12:38 UTC
