### ISSUE TITLE
App Crashes on iOS TestFlight

### ISSUE THREAD

**Issue by RomeoDar** [flutter/flutter#98627] opened 2022-02-17 00:34 UTC
Hi, all of my projects are facing only one problem.

android debug and release build working fine, I face problem when upload the iOS app on TestFlight, app works fine on simulator but when I build the iOS app from android studio, then build from Xcode and then archive and upload. when I test it on iPhone device using TestFlight it crash on startup. I've uploaded many apps on appstore before but I've been facing this issue for 2/3 months. only TestFlight app crash on startup rest debug app and android release version working fine

I'm using old flutter version 2.0.6 (I know I need to update but I can't update caz I'm using old MacBook and my new MacBook will be delivered in 2 months

[✓] Flutter (Channel stable, 2.0.6, on Mac OS X 10.15.7 19H524 darwin-x64, locale en-PK)
    • Flutter version 2.0.6 at /Users/friends/Downloads/src/flutter
    • Framework revision 1d9032c7e1 (10 months ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/friends/Library/Android/sdk
    • Platform android-31, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.
[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1
[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
[✓] Connected device (2 available)
    • V2061 (mobile) • 6db01682 • android-arm64  • Android 12 (API 31)
    • Chrome (web)   • chrome   • web-javascript • Google Chrome 98.0.4758.102
• No issues found!

[Crashlogs from iOS device while running app from testflight log1](https://iosapps-ssl.itunes.apple.com/itunes-assets/Purple126/v4/61/b2/9c/61b29c71-81b8-9fc3-65f3-9d815f8f7ac1/crashlog-DC95A231-966E-43B2-9154-AF10A05155FA.txt?accessKey=1645310894_8800275362182133656_Wm%2BXqh5ns3kTtdNDKi4zC1YXlluzQmyfCZG2bGM0AGjLz0DBYmOR1CuoyZO1NZWYojdTjMgCae0U%2FJLDnKx11qnvll5AGSbyvnDwBqPflOH%2F2Ah6ClU9JbRAEa4dfTnvc789oOpqYJmjGUlFNZKky7bQ1X2mYrtc92Vhk660Rzwww%2BEWWZO2c2Mn%2Fzgwl7CfayXJ8JA985lIoC19oDO15g%3D%3D)

[logs2](https://iosapps-ssl.itunes.apple.com/itunes-assets/Purple116/v4/24/b4/29/24b42903-94a9-e498-9ad6-53fa5ac4e9c5/crashlog-3E429531-BAB8-4EA0-AD4E-F4EF47C4FB89.txt?accessKey=1645310894_8336654550509203183_A%2BDu0odd6VDTihvaDR02xC6oHG1vpvtDsr%2BrC8x%2F7JFUyf9%2FOLmkcpSxEvTsFfHPhlamm8nOcKNoBf4Z6y6unDHZnmfYrVCYuUpckbIY5XZAqb5%2Frqr9mwBGLIlPYNShwAwSNJNzjTqcBNOqDn1eyZP7TM7NgviMe2bSlvVAHGwxyQ7g2QcM8WLxgzNzO5L1t%2FCZwlPj9yBc7QP%2BGf0%2F%2Bw%3D%3D)

[logs3](https://iosapps-ssl.itunes.apple.com/itunes-assets/Purple126/v4/38/01/c9/3801c93a-bc86-477b-d3d1-ba7ff8673762/crashlog-62723540-EF59-430B-B6F2-60AF6D62E96C.txt?accessKey=1645310894_6828309849348296966_63wQ5nj5ovJvJkACg5lsZ2Nwk4IOA8HLKmJ%2FYs3%2BZLaPxb5x4%2BY2iWJ1ahTTUmXXhyI5KADGMn%2FOgB15066BUuLDqTdaXwyYAFL5uWoi7FSIXE3LnydehnDMJjDKkRunx9ijcQkWniq5VMf2CrC14%2B4QxsUQ6LXxowx91PAeVksmh%2FrtJeUXFiiqBacw5f97L3yM19k1NIbeOD5zFqG6fA%3D%3D)

[logs4](https://iosapps-ssl.itunes.apple.com/itunes-assets/Purple126/v4/8e/07/8f/8e078f5f-a367-299d-39e4-130cf52bc157/crashlog-9C3DBBFF-DE73-4D21-97BD-8CE9D68638CA.txt?accessKey=1645310894_7834822273079723699_ZomzqhXBroAIOrrNnCgBGHbTUEJ4bHO8gjnrKWwD1QB8QsIaM3WWb6LMvN6hZi7sgw2TFE3nM%2BijNvX%2Bcbaf7DZxCRh46TJKnj1sG2EJAnNBwyJLoZM9ITLy6eTKJY7r5SLLIz36GrFmC2XEe09PlcUr5jnyJPx0o269FBmz9ZurfzXe9ByjxcBmAPDrZYomdKvqOqBtHBeAtX30JTSuTQ%3D%3D)

**Comment by RomeoDar** [comment] 2022-02-17 00:36
I'm facing this issue with all of my projects, please can you check the logs and give me information related to issue ? thanks

**Comment by darshankawar** [comment] 2022-02-17 10:28
@RomeoDar 
From the logs you shared, the first log shows `VM - Fault hit memory shortage\nVM - Fault hit memory shortage\nVM - Fault hit memory shortage` which might be the reason why app is crashing. Apart from that, I didn't find any substantial / clear exception log from the files you shared. Yes, it does crash, but there's no concrete reason log apart from the one I mentioned above.

Also, you being on very old version of stable really would make it tough to diagnose and identify the root cause, because even if there's a crash, the updates made between 2.0.6 till 2.10.1 would have fixed the issue already and we can't make a fix to the version you are on.
So, I suggest you to upgrade to latest stable version and then try your scenario again to see if you still see the crash or not.

With that said, I am going ahead and closing this issue since we can't do much due to the version you are on. If you disagree, write in comments and I'll reopen it.

**Closed by darshankawar** 2022-02-17 10:28 UTC
Labels: in triage
