### ISSUE TITLE
Unable to run my code in VS code [Mac] Unable to run "adb", check your Android SDK installation and ANDROID_SDK_ROOT environment variable: /Users/sasikumardas/Library/Android/sdk/platform-tools/adb

### ISSUE THREAD

**Issue by sasikumardas** [flutter/flutter#143066] opened 2024-02-07 11:32 UTC

**Comment by dam-ease** [comment] 2024-02-07 12:19
Hello @sasikumardas.
Thanks for filing this.
Per the logs in your title:

> Unable to run my code in VS code [Mac] Unable to run "adb", check your Android SDK installation and ANDROID_SDK_ROOT environment variable: /Users/sasikumardas/Library/Android/sdk/platform-tools/adb

This is similar to https://github.com/flutter/flutter/issues/72101. Can you check out the thread for suggested solutions?
Also, kindly upvote and follow up on this issue for updates.
I'll be closing this as a duplicate of the already existing issue, if you disagree please comment and I'll reopen this.

**Closed by dam-ease** 2024-02-07 12:19 UTC
Labels: in triage
