### ISSUE TITLE
Settings GestureDetector key to a UniqueKey and executing setState always causes onTapCancel function

### ISSUE THREAD

**Issue by kirill-21** [flutter/flutter#84050] opened 2021-06-05 17:27 UTC
What it should execute after onTapDown is onTapUp, however, it always executes onTapCancel. If i change onTapCancel callback to the same as the onTapUp callback, i get this error:
```

======== Exception caught by widgets library =======================================================
The following _TypeError was thrown while finalizing the widget tree:
type 'Null' is not a subtype of type 'String' of 'function result'

When the exception was thrown, this was the stack: 
#0      _Location.file (package:flutter/src/widgets/widget_inspector.dart)
#1      _Location.toJsonMap (package:flutter/src/widgets/widget_inspector.dart:2844:15)
#2      _Location.toJsonMap.<anonymous closure> (package:flutter/src/widgets/widget_inspector.dart:2853:42)
#3      MappedListIterable.elementAt (dart:_internal/iterable.dart:412:31)
#4      ListIterator.moveNext (dart:_internal/iterable.dart:341:26)
...
====================================================================================================
```
But even without the error it's not good, because onTapCancel executes before user removes his finger from the mouse button
![dyP1VCezQ8](https://user-images.githubusercontent.com/63228361/120900177-0c33f080-c63c-11eb-8a62-3e5535fde2dc.gif)

Code sample:
```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      home: Scaffold(
        appBar: AppBar(
          title: Text('Material App Bar'),
        ),
        body: DemoIconButton(),
      ),
    );
  }
}

class DemoIconButton extends StatefulWidget {
  @override
  _DemoIconButtonState createState() => _DemoIconButtonState();
}

class _DemoIconButtonState extends State<DemoIconButton> {
  Color _color = Colors.green;

  void _updateColor(Color color) {
    if(mounted)
      setState(() => _color = color);
  }

  @override
  Widget build(BuildContext context) {
    return MouseRegion(
      onEnter: (_) => _updateColor(Colors.purple),
      onExit: (_) => _updateColor(Colors.green),
      child: GestureDetector(
        onTapDown: (_) => _updateColor(Colors.yellow),
        onTapUp: (_) => _updateColor(Colors.green),
        onTapCancel: () => print('cancel :c'),
        key: UniqueKey(),
        child: Icon(
          Icons.phone_locked,
          color: _color,
        ),
      ),
    );
  }
}
```
Flutter version: 2.2.1 from the stable channel

**Comment by xu-baolin** [comment] 2021-06-07 03:44
@kirill-21 Hey, thanks for filing this.
You should cache the key instead of changing it every build phase.
```dart
class _DemoIconButtonState extends State<DemoIconButton> {
  Color _color = Colors.green;
  final Key _key = UniqueKey();

  void _updateColor(Color color) {
    if(mounted)
      setState(() => _color = color);
  }

  @override
  Widget build(BuildContext context) {
    return MouseRegion(
      onEnter: (_) => _updateColor(Colors.purple),
      onExit: (_) => _updateColor(Colors.green),
      child: GestureDetector(
        onTapDown: (_) => _updateColor(Colors.yellow),
        onTapUp: (_) => _updateColor(Colors.green),
        onTapCancel: () => print('cancel :c'),
        key: _key,
```

**Comment by kirill-21** [comment] 2021-06-07 09:44
> @kirill-21 Hey, thanks for filing this.
> You should cache the key instead of changing it every build phase.
> 
> ```dart
> class _DemoIconButtonState extends State<DemoIconButton> {
>   Color _color = Colors.green;
>   final Key _key = UniqueKey();
> 
>   void _updateColor(Color color) {
>     if(mounted)
>       setState(() => _color = color);
>   }
> 
>   @override
>   Widget build(BuildContext context) {
>     return MouseRegion(
>       onEnter: (_) => _updateColor(Colors.purple),
>       onExit: (_) => _updateColor(Colors.green),
>       child: GestureDetector(
>         onTapDown: (_) => _updateColor(Colors.yellow),
>         onTapUp: (_) => _updateColor(Colors.green),
>         onTapCancel: () => print('cancel :c'),
>         key: _key,
> ```

I know that it's the solution, however, if i change GestureDetector to a Listener, this issue disappears and unique key is not the problem anymore.

**Comment by kirill-21** [comment] 2021-06-07 13:38
> @kirill-21 Hey, thanks for filing this.
> You should cache the key instead of changing it every build phase.

One more problem: Removing key from the widget but wrapping it in a tooltip widget also creates such problem with onTapCancel.

**Comment by darshankawar** [comment] 2021-06-08 07:39
@kirill-21 
According to the documentation, `onTapCancel` is called after `onTapDown`. 

https://api.flutter.dev/flutter/widgets/GestureDetector/onTapCancel.html

Also check this comment regarding `GestureDetector` for further reference, https://github.com/flutter/flutter/issues/74733#issuecomment-772136364
https://github.com/flutter/flutter/issues/74733#issuecomment-767859584
https://github.com/flutter/flutter/issues/50776#issuecomment-783795628

**Comment by kirill-21** [comment] 2021-06-09 09:29
> @kirill-21
> According to the documentation, `onTapCancel` is called after `onTapDown`.
> 
> https://api.flutter.dev/flutter/widgets/GestureDetector/onTapCancel.html
> 
> Also check this comment regarding `GestureDetector` for further reference, [#74733 (comment)](https://github.com/flutter/flutter/issues/74733#issuecomment-772136364)
> [#74733 (comment)](https://github.com/flutter/flutter/issues/74733#issuecomment-767859584)
> [#50776 (comment)](https://github.com/flutter/flutter/issues/50776#issuecomment-783795628)

Changing of the behavior of the below widget does not change anything, so how to make it win?

**Comment by darshankawar** [comment] 2021-06-09 12:59
@kirill-21 
Can you please summarize all the issues you are facing here please ?

Thanks.

**Comment by kirill-21** [comment] 2021-06-09 19:07
> @kirill-21
> Can you please summarize all the issues you are facing here please ?
> 
> Thanks.
Settings key of a GestureDetector to the UniqueKey() causes onTapCancel(Listener with a UniqueKey works fine) and GestureDetector inside of Tooltip also causes onTapCancel method(changing it's behavior does not affect the result)

**Comment by darshankawar** [comment] 2021-06-10 06:09
Keeping it open for further insights from team.

Cc: @Hixie

**Comment by Hixie** [comment] 2021-06-12 22:39
This is working as intended. If you create a new GestureDetector with a different key each time, then what you're asking for is that each time the GestureDetector widget is built, a new Element should be created for it, disposing the old one, and thus the old one should cancel all pending gestures and we should start a new GestureDetector that looks for new gestures.

**Comment by kirill-21** [comment] 2021-06-12 22:51
> This is working as intended. If you create a new GestureDetector with a different key each time, then what you're asking for is that each time the GestureDetector widget is built, a new Element should be created for it, disposing the old one, and thus the old one should cancel all pending gestures and we should start a new GestureDetector that looks for new gestures.

So why Listener is not being recreated each time with a Unique key?

**Comment by Hixie** [comment] 2021-06-12 23:11
It is, but Listener has no state, there's nothing to reset. It just blindly passes through all the events that it receives. GestureDetector has a Listener inside it to grab the events, and passes them to GestureRecognizers, which are stateful objects that track events over time to try to interpret them (e.g. as drags, taps, double-taps, long presses, whatever). When you remove a GestureDetector from the tree, it tells all its recognizers that they are obsolete, and they send out cancelation events.

**Comment by kirill-21** [comment] 2021-06-12 23:30
> It is, but Listener has no state, there's nothing to reset. It just blindly passes through all the events that it receives. GestureDetector has a Listener inside it to grab the events, and passes them to GestureRecognizers, which are stateful objects that track events over time to try to interpret them (e.g. as drags, taps, double-taps, long presses, whatever). When you remove a GestureDetector from the tree (e.g. by replacing it by another one with a different key), it tells all its recognizers that they are obsolete, and they send out cancelation events.

Thank you for explanation, and what about Tooltip widget? Is there any way to avoid onTapCancel executing just because GestureDetector is wrapped in a Tooltip widget

**Comment by Hixie** [comment] 2021-06-13 00:00
Wrapping a GestureDetector in a Tooltip widget should not cause it to cancel anything, but that sounds like a different bug. If you're seeing that, I recommend making a small reproduction test app and filing a new bug with that, giving the steps to reproduce.

**Comment by kirill-21** [comment] 2021-06-13 00:14
> Wrapping a GestureDetector in a Tooltip widget should not cause it to cancel anything, but that sounds like a different bug. If you're seeing that, I recommend making a small reproduction test app and filing a new bug with that, giving the steps to reproduce.

Step to reproduce is easy - wrap GestureDetector in a Tooltip, add onTapUp, onTapDown, onTapCancel prints and see the result

**Comment by Hixie** [comment] 2021-06-13 00:16
The key part of my advice was to file a new bug. :-) We try to keep each issue to one specific topic otherwise it becomes impossible to find anything.

**Comment by kirill-21** [comment] 2021-06-13 18:22
> The key part of my advice was to file a new bug. :-) We try to keep each issue to one specific topic otherwise it becomes impossible to find anything.

Okay, thank you for answers

**Comment by kirill-21** [comment] 2021-06-13 18:34
> The key part of my advice was to file a new bug. :-) We try to keep each issue to one specific topic otherwise it becomes impossible to find anything.

https://github.com/flutter/flutter/issues/84531

**Comment by darshankawar** [comment] 2021-06-14 06:37
Closing this as WAI based on https://github.com/flutter/flutter/issues/84050#issuecomment-860121951.

**Closed by darshankawar** 2021-06-14 06:37 UTC
Labels: a: mouse, f: gestures, found in release: 2.2, framework, has reproducible steps
