### ISSUE TITLE
Linux: Textfields input is taken in reverse after upgrading to Ubuntu 21.04

### ISSUE THREAD

**Issue by Feichtmeier** [flutter/flutter#80846] opened 2021-04-21 06:49 UTC
After upgrading to Ubuntu 21.04 after starting an application I receive the following warning:

```
warning: /usr/lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu/crt1.o: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0008002
/snap/flutter/current/usr/bin/ld: warning: //lib/x86_64-linux-gnu/libdl.so.2: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0008002
```

When I enter text into a textfield the letters are "painted"/"put" in reverse:

https://user-images.githubusercontent.com/15329494/115509091-545ea580-a27e-11eb-80ce-6439bd58874f.mp4

I can still copy paste the text into the textfield and properly continue, but still kind of big usability issue now :) 
Thanks in advance

**Comment by TahaTesser** [comment] 2021-04-21 09:05
Hi @Feichtmeier 
Are you using flutter on Snap?

Can you please provide your `flutter doctor -v` and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) and `flutter run --verbose` logs running the minimal code sample?
Thank you

**Comment by Feichtmeier** [comment] 2021-04-21 10:04
> Hi @Feichtmeier
> Are you using flutter on Snap? If yes, please upgrade to latest version
> 
> Can you please provide your `flutter doctor -v` and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) and `flutter run --verbose` logs running the minimal code sample?
> Thank you

Hi @TahaTesser  :wave: 
Yes I am using flutter on snap and it uses the most up to date channel version 
```
latest/edge:      0+git.e75662a 2021-04-15
```
Which itself contains flutter version Flutter version 2.2.0-10.1.pre

Here is a video where I created a fresh flutter app from scratch and only exchanged the Text() widget in the example for a TextField() widget:


https://user-images.githubusercontent.com/15329494/115534768-68170580-a298-11eb-914e-764db21164b2.mp4

Here is the freshly uploaded test code 
https://github.com/Feichtmeier/flutter_application_1

And here is flutter doctor output (Android studio is installed and working, its the snap)
```
frederik@carbon:~/Projects/flutter_application_1$ flutter doctor -v
[✓] Flutter (Channel dev, 2.2.0-10.1.pre, on Linux, locale
    de_DE.UTF-8)
    • Flutter version 2.2.0-10.1.pre at
      /home/frederik/snap/flutter/common/flutter
    • Framework revision 0941968447 (vor 6 Tagen), 2021-04-15
      12:01:02 -0700
    • Engine revision d2a2e93510
    • Dart version 2.13.0 (build 2.13.0-211.6.beta)

[✓] Android toolchain - develop for Android devices (Android SDK
    version 30.0.2)
    • Android SDK at /home/frederik/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.11-ea+8-Ubuntu-0ubuntu2)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit
      https://flutter.dev/docs/get-started/install/linux#android-set
      up for detailed instructions).

[✓] IntelliJ IDEA Community Edition (version 2021.1)
    • IntelliJ at /snap/intellij-idea-community/293
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Linux
    • Chrome (web)    • chrome • web-javascript • Google Chrome
      90.0.4430.85

! Doctor found issues in 1 category.
```

And here is the ```flutter run --verbose``` output

```
frederik@carbon:~/Projects/flutter_application_1$ flutter run --verbose
[ +108 ms] executing: uname -m
[  +56 ms] Exit code 0 from: uname -m
[        ] x86_64
[  +12 ms] executing: [/home/frederik/snap/flutter/common/flutter/] git -c log.showSignature=false log -n 1
--pretty=format:%H
[  +14 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 0941968447ea8058e56e1479f7e53147149b739e
[   +1 ms] executing: [/home/frederik/snap/flutter/common/flutter/] git tag --points-at
0941968447ea8058e56e1479f7e53147149b739e
[  +23 ms] Exit code 0 from: git tag --points-at 0941968447ea8058e56e1479f7e53147149b739e
[        ] 2.2.0-10.1.pre
[  +11 ms] executing: [/home/frederik/snap/flutter/common/flutter/] git rev-parse --abbrev-ref --symbolic
@{u}
[   +7 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/dev
[        ] executing: [/home/frederik/snap/flutter/common/flutter/] git ls-remote --get-url origin
[   +6 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +142 ms] executing: [/home/frederik/snap/flutter/common/flutter/] git rev-parse --abbrev-ref HEAD
[   +8 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] dev
[ +108 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +104 ms] executing: /home/frederik/Android/Sdk/platform-tools/adb devices -l
[  +66 ms] List of devices attached
[   +6 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +123 ms] Multiple devices found:
[  +67 ms] Linux (desktop) • linux  • linux-x64      • Linux
[   +1 ms] Chrome (web)    • chrome • web-javascript • Google Chrome 90.0.4430.85
[   +2 ms] [1]: Linux (linux)
[        ] [2]: Chrome (chrome)
[   +2 ms] Please choose one (To quit, press "q/Q")
[        ] : 
[+16034 ms] 1
[  +21 ms] Skipping pub get: version match.
[ +217 ms] Generating
/home/frederik/Projects/flutter_application_1/android/app/src/main/java/io/flutter/plugins/GeneratedPluginReg
istrant.java
[ +156 ms] Initializing file store
[  +18 ms] Skipping target: gen_localizations
[  +12 ms] complete
[   +7 ms] Launching lib/main.dart on Linux in debug mode...
[   +9 ms] /home/frederik/snap/flutter/common/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev
/home/frederik/snap/flutter/common/flutter/bin/cache/artifacts/engine/linux-x64/frontend_server.dart.snapshot
--sdk-root /home/frederik/snap/flutter/common/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/
--incremental --target=flutter --debugger-module-names --experimental-emit-debug-metadata
-DFLUTTER_WEB_AUTO_DETECT=true --output-dill /tmp/flutter_tools.CQXCID/flutter_tool.OTWNVP/app.dill
--packages /home/frederik/Projects/flutter_application_1/.dart_tool/package_config.json
-Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-scheme
org-dartlang-root --initialize-from-dill build/3c113a45063dc6628e68a4111abcacad.cache.dill.track.dill
--enable-experiment=alternative-invalidation-strategy
[  +37 ms] Building Linux application...
[  +31 ms] <- compile package:flutter_application_1/main.dart
[   +4 ms] executing: [build/linux/x64/debug/] cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug
-DFLUTTER_TARGET_PLATFORM=linux-x64 /home/frederik/Projects/flutter_application_1/linux
[ +138 ms] -- Configuring done
[        ] -- Generating done
[        ] -- Build files have been written to:
/home/frederik/Projects/flutter_application_1/build/linux/x64/debug
[   +4 ms] executing: ninja -C build/linux/x64/debug install
[  +11 ms] ninja: Entering directory `build/linux/x64/debug'
[+13482 ms] [1/5] Generating
/home/frederik/Projects/flutter_application_1/linux/flutter/ephemeral/libflutter_linux_gtk.so,
/home/frederik/Projects/flutter_application_1/linux/flutter/ephemeral/flutter_linux/fl_basic_message_channel.
h, /home/frederik/Projects/flutter_application_1/linux/flutter/ephemeral/flutter_linux/fl_binary_codec.h,
/home/frederik/Projects/flutter_application_1/linux/flutter/ephemeral/flutter_linux/fl_binary_messenger.h,
/home/frederik/Projects/flutter_application_1/linux/flutter/ephemeral/flutter_linux/fl_dart_project.h,
/home/frederik/Projects/flutter_application_1/linux/flutter/ephemeral/flutter_linux/fl_engine.h,
/home/frederik/Projects/flutter_application_1/linux/flutter/ephemeral/flutter_linux/fl_json_message_codec.h,
/home/frederik/Projects/flutter_application_1/linux/flutter/ephemeral/flutter_linux/fl_json_method_codec.h,
/home/frederik/Projects/flutter_application_1/linux/flutter/ephemeral/flutter_linux/fl_message_codec.h,
/home/frederik/Projects/flutter_application_1/linux/flutter/ephemeral/flutter_linux/fl_method_call.h,
/home/frederik/Projects/flutter_application_1/linux/flutter/ephemeral/flutter_linux/fl_method_channel.h,
/home/frederik/Projects/flutter_application_1/linux/flutter/ephemeral/flutter_linux/fl_method_codec.h,
/home/frederik/Projects/flutter_application_1/linux/flutter/ephemeral/flutter_linux/fl_method_response.h,
/home/frederik/Projects/flutter_application_1/linux/flutter/ephemeral/flutter_linux/fl_plugin_registrar.h,
/home/frederik/Projects/flutter_application_1/linux/flutter/ephemeral/flutter_linux/fl_plugin_registry.h,
/home/frederik/Projects/flutter_application_1/linux/flutter/ephemeral/flutter_linux/fl_standard_message_codec
.h,
/home/frederik/Projects/flutter_application_1/linux/flutter/ephemeral/flutter_linux/fl_standard_method_codec.
h, /home/frederik/Projects/flutter_application_1/linux/flutter/ephemeral/flutter_linux/fl_string_codec.h,
/home/frederik/Projects/flutter_application_1/linux/flutter/ephemeral/flutter_linux/fl_value.h,
/home/frederik/Projects/flutter_application_1/linux/flutter/ephemeral/flutter_linux/fl_view.h,
/home/frederik/Projects/flutter_application_1/linux/flutter/ephemeral/flutter_linux/flutter_linux.h, _phony_
[   +3 ms] [ +133 ms] executing: uname -m
[        ] [  +59 ms] Exit code 0 from: uname -m
[        ] [        ] x86_64
[        ] [  +10 ms] executing: [/home/frederik/snap/flutter/common/flutter/] git -c log.showSignature=false
log -n 1 --pretty=format:%H
[        ] [   +7 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] [        ] 0941968447ea8058e56e1479f7e53147149b739e
[        ] [   +1 ms] executing: [/home/frederik/snap/flutter/common/flutter/] git tag --points-at
0941968447ea8058e56e1479f7e53147149b739e
[        ] [  +19 ms] Exit code 0 from: git tag --points-at 0941968447ea8058e56e1479f7e53147149b739e
[        ] [        ] 2.2.0-10.1.pre
[        ] [  +11 ms] executing: [/home/frederik/snap/flutter/common/flutter/] git rev-parse --abbrev-ref
--symbolic @{u}
[        ] [   +6 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] [        ] origin/dev
[        ] [        ] executing: [/home/frederik/snap/flutter/common/flutter/] git ls-remote --get-url origin
[        ] [   +6 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] [        ] https://github.com/flutter/flutter.git
[        ] [ +119 ms] executing: [/home/frederik/snap/flutter/common/flutter/] git rev-parse --abbrev-ref
HEAD
[        ] [   +5 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] [        ] dev
[        ] [  +80 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [ +151 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[        ] [  +69 ms] Initializing file store
[        ] [  +36 ms] Skipping target: gen_localizations
[        ] [   +9 ms] unpack_linux: Starting due to {}
[        ] [ +221 ms] kernel_snapshot: Starting due to {}
[        ] [   +8 ms] unpack_linux: Complete
[   +1 ms] [+3026 ms] /home/frederik/snap/flutter/common/flutter/bin/cache/dart-sdk/bin/dart
--disable-dart-dev
/home/frederik/snap/flutter/common/flutter/bin/cache/artifacts/engine/linux-x64/frontend_server.dart.snapshot
--sdk-root /home/frederik/snap/flutter/common/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/
--target=flutter --no-print-incremental-dependencies -DFLUTTER_WEB_AUTO_DETECT=true -Ddart.vm.profile=false
-Ddart.vm.product=false --enable-asserts --track-widget-creation --packages
/home/frederik/Projects/flutter_application_1/.dart_tool/package_config.json --output-dill
/home/frederik/Projects/flutter_application_1/.dart_tool/flutter_build/c5cf7ff60e8dc16527835db8a4bc7f0d/app.d
ill --depfile
/home/frederik/Projects/flutter_application_1/.dart_tool/flutter_build/c5cf7ff60e8dc16527835db8a4bc7f0d/kerne
l_snapshot.d package:flutter_application_1/main.dart
[   +1 ms] [+7484 ms] kernel_snapshot: Complete
[        ] [ +350 ms] debug_bundle_linux-x64_assets: Starting due to {}
[        ] [ +116 ms] debug_bundle_linux-x64_assets: Complete
[        ] [ +461 ms] Persisting file store
[        ] [   +6 ms] Done persisting file store
[        ] [   +6 ms] build succeeded.
[        ] [   +6 ms] "flutter assemble" took 11.995ms.
[        ] [  +79 ms] ensureAnalyticsSent: 76ms
[        ] [        ] Running shutdown hooks
[        ] [        ] Shutdown hooks complete
[        ] [        ] exiting with code 0
[ +449 ms] [2/5] Building CXX object
CMakeFiles/flutter_application_1.dir/flutter/generated_plugin_registrant.cc.o
[   +6 ms] [3/5] Building CXX object CMakeFiles/flutter_application_1.dir/my_application.cc.o
[ +108 ms] [4/5] Linking CXX executable intermediates_do_not_run/flutter_application_1
[        ] /snap/flutter/current/usr/bin/ld: warning:
/usr/lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu/crt1.o: unsupported GNU_PROPERTY_TYPE (5) type:
0xc0008002
[   +2 ms] /snap/flutter/current/usr/bin/ld: warning: //lib/x86_64-linux-gnu/libdl.so.2: unsupported
GNU_PROPERTY_TYPE (5) type: 0xc0008002
[        ] [4/5] Install the project...
[   +7 ms] -- Install configuration: "Debug"
[  +21 ms] -- Installing:
/home/frederik/Projects/flutter_application_1/build/linux/x64/debug/bundle/flutter_application_1
[        ] -- Set runtime path of
"/home/frederik/Projects/flutter_application_1/build/linux/x64/debug/bundle/flutter_application_1" to
"$ORIGIN/lib"
[        ] -- Installing:
/home/frederik/Projects/flutter_application_1/build/linux/x64/debug/bundle/data/icudtl.dat
[        ] -- Installing:
/home/frederik/Projects/flutter_application_1/build/linux/x64/debug/bundle/lib/libflutter_linux_gtk.so
[ +134 ms] -- Installing:
/home/frederik/Projects/flutter_application_1/build/linux/x64/debug/bundle/data/flutter_assets
[        ] -- Installing:
/home/frederik/Projects/flutter_application_1/build/linux/x64/debug/bundle/data/flutter_assets/version.json
[        ] -- Installing:
/home/frederik/Projects/flutter_application_1/build/linux/x64/debug/bundle/data/flutter_assets/FontManifest.j
son
[        ] -- Installing:
/home/frederik/Projects/flutter_application_1/build/linux/x64/debug/bundle/data/flutter_assets/fonts
[        ] -- Installing:
/home/frederik/Projects/flutter_application_1/build/linux/x64/debug/bundle/data/flutter_assets/fonts/Material
Icons-Regular.otf
[        ] -- Installing:
/home/frederik/Projects/flutter_application_1/build/linux/x64/debug/bundle/data/flutter_assets/packages
[        ] -- Installing:
/home/frederik/Projects/flutter_application_1/build/linux/x64/debug/bundle/data/flutter_assets/packages/cuper
tino_icons
[        ] -- Installing:
/home/frederik/Projects/flutter_application_1/build/linux/x64/debug/bundle/data/flutter_assets/packages/cuper
tino_icons/assets
[        ] -- Installing:
/home/frederik/Projects/flutter_application_1/build/linux/x64/debug/bundle/data/flutter_assets/packages/cuper
tino_icons/assets/CupertinoIcons.ttf
[        ] -- Installing:
/home/frederik/Projects/flutter_application_1/build/linux/x64/debug/bundle/data/flutter_assets/kernel_blob.bi
n
[  +38 ms] -- Installing:
/home/frederik/Projects/flutter_application_1/build/linux/x64/debug/bundle/data/flutter_assets/NOTICES
[        ] -- Installing:
/home/frederik/Projects/flutter_application_1/build/linux/x64/debug/bundle/data/flutter_assets/AssetManifest.
json
[  +11 ms] Building Linux application... (completed in 14,5s)
[ +248 ms] Observatory URL on device: http://127.0.0.1:36127/59qqMcs8Xsg=/
[   +3 ms] Caching compiled dill
[  +36 ms] Connecting to service protocol: http://127.0.0.1:36127/59qqMcs8Xsg=/
[ +215 ms] Launching a Dart Developer Service (DDS) instance at http://127.0.0.1:0, connecting to VM service
at http://127.0.0.1:36127/59qqMcs8Xsg=/.
[  +77 ms] DDS is listening at http://127.0.0.1:41349/pMjXKK5sMZw=/.
[  +54 ms] Successfully connected to service protocol: http://127.0.0.1:36127/59qqMcs8Xsg=/
[  +18 ms] DevFS: Creating new filesystem on the device (null)
[  +13 ms] DevFS: Created new filesystem on the device
(file:///tmp/flutter_application_1IBUHDL/flutter_application_1/)
[   +1 ms] Updating assets
[  +91 ms] Syncing files to device Linux...
[   +2 ms] <- reset
[        ] Compiling dart to kernel with 0 updated files
[   +2 ms] <- recompile package:flutter_application_1/main.dart 54fa3fd6-b8e5-4e05-99b9-8a093d085ef9
[        ] <- 54fa3fd6-b8e5-4e05-99b9-8a093d085ef9
[  +93 ms] Updating files.
[        ] DevFS: Sync finished
[   +1 ms] Syncing files to device Linux... (completed in 99ms)
[        ] Synced 0.0MB.
[   +2 ms] <- accept
[   +7 ms] Connected to _flutterView/0x153ebb0.
[   +2 ms] Flutter run key commands.
[   +1 ms] r Hot reload. 🔥🔥🔥
[   +1 ms] R Hot restart.
[        ] h Repeat this help message.
[        ] d Detach (terminate "flutter run" but leave application running).
[        ] c Clear the screen
[        ] q Quit (terminate the application on the device).
[   +1 ms] 💪 Running with sound null safety 💪
[        ] An Observatory debugger and profiler on Linux is available at:
http://127.0.0.1:41349/pMjXKK5sMZw=/
[ +683 ms] The Flutter DevTools debugger and profiler on Linux is available at:
                    http://127.0.0.1:9103?uri=http%3A%2F%2F127.0.0.1%3A41349%2FpMjXKK5sMZw%3D%2F
[+10989 ms] ** (flutter_application_1:260439): WARNING **: 11:58:59.265: Unable to retrieve framework
response: Message is not valid JSON
[  +14 ms] 
           ══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY
╞══════════════════════════════════════════════════════════
           The following assertion was thrown during a platform message callback:
           Attempted to send a key down event when no keys are in keysPressed. This state can occur if the
key
           event being sent doesn't properly set its modifier flags. This was the event:
           RawKeyDownEvent#45444(logicalKey: LogicalKeyboardKey#700e6(keyId: "0x1000700e6", keyLabel: "Alt
           Right", debugName: "Alt Right"), physicalKey: PhysicalKeyboardKey#700e6(usbHidUsage: "0x000700e6",
           debugName: "Alt Right")) and its data: RawKeyEventDataLinux(keyLabel: , keyCode: 65027, scanCode:
           108, unicodeScalarValues: 0, modifiers: 0, modifiers down: {})
           'package:flutter/src/services/raw_keyboard.dart':
           Failed assertion: line 666 pos 7: 'event is! RawKeyDownEvent || _keysPressed.isNotEmpty'
           
           Either the assertion indicates an error in the framework itself, or we should provide
substantially
           more information in this error message to help you determine and fix the underlying cause.
           In either case, please report this assertion by filing a bug on GitHub:
             https://github.com/flutter/flutter/issues/new?template=2_bug.md
           
           When the exception was thrown, this was the stack:
           #2      RawKeyboard._handleKeyEvent (package:flutter/src/services/raw_keyboard.dart:666:7)
           #3      BasicMessageChannel.setMessageHandler.<anonymous closure>
           (package:flutter/src/services/platform_channel.dart:73:49)
           #4      BasicMessageChannel.setMessageHandler.<anonymous closure>
           (package:flutter/src/services/platform_channel.dart:72:47)
           #5      _DefaultBinaryMessenger.handlePlatformMessage
(package:flutter/src/services/binding.dart:284:33)
           #6      _invoke3.<anonymous closure> (dart:ui/hooks.dart:223:15)
           #10     _invoke3 (dart:ui/hooks.dart:222:10)
           #11     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:520:7)
           #12     _dispatchPlatformMessage (dart:ui/hooks.dart:90:31)
           (elided 5 frames from class _AssertionError and dart:async)

════════════════════════════════════════════════════════════════════════════════════════════════════
```

The exception happend when I pressed the "alt GR" button and it is prbly more related to this issue: https://github.com/flutter/flutter/issues/68713

It is important to note that this also happened with flutter used not from snap. This must be something in Ubuntu 21.04 that is not synced with flutter, so my guess is some C++ lib

**Comment by LongCatIsLooong** [comment] 2021-04-21 17:30
duplicate of https://github.com/flutter/flutter/issues/76383?

**Comment by TahaTesser** [comment] 2021-04-22 06:12
Hi @Feichtmeier 
This warning is related to Flutter snap, please file an issue on their dedicated [GitHub ](https://github.com/canonical/flutter-snap/issues)
```
warning: /usr/lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu/crt1.o: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0008002
/snap/flutter/current/usr/bin/ld: warning: //lib/x86_64-linux-gnu/libdl.so.2: unsupported GNU_PROPERTY_TYPE (5) type: 0x
c0008002
```

Input issue is a duplicate of https://github.com/flutter/flutter/issues/76383
Please try this [solution](https://github.com/flutter/flutter/issues/76383#issuecomment-798438786) as this is an issue with GTK itself

Closing as duplicate of https://github.com/flutter/flutter/issues/76383

**Closed by TahaTesser** 2021-04-22 06:12 UTC
Labels: in triage
