### ISSUE TITLE
[Android] Accessibility Talkback rectangle isn't visible.

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#60247] opened 2020-06-24 23:50 UTC
When navigating with Talkback on my phone, no rectangle is rendered around the currently selected item.

reproductions code:
Just use the counter app from `flutter create`

flutter doctor:
```
[✓] Flutter (Channel master, 1.20.0-1.0.pre.200, on Mac OS X 10.15.4 19E287, locale en-US)
    • Flutter version 1.20.0-1.0.pre.200 at /Users/aaclarke/dev/flutter
    • Framework revision 15913e5d73 (3 hours ago), 2020-06-24 17:13:02 -0400
    • Engine revision 291dab6f17
    • Dart version 2.9.0 (build 2.9.0-18.0.dev d8eb844e5d)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/aaclarke/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (4 available)
    • ASUS A002     • H3AKCV000127JRB • android-arm64  • Android 7.0 (API 24)
    • macOS desktop • macos           • darwin-x64     • Mac OS X 10.15.4 19E287
    • Web Server    • web-server      • web-javascript • Flutter Tools
    • Chrome        • chrome          • web-javascript • Google Chrome 83.0.4103.116
```

**Comment by britannio** [comment] 2020-07-30 16:03
It's likely a regression in the Android embedder.
 Making the following changes fixed the issue https://github.com/WorldHealthOrganization/app/pull/937/files although it's not ideal.

**Comment by britannio** [comment] 2020-08-27 15:09
@gaaclarke Do you know the status on this? IMO this should be a P2/P3 as it's a regression that makes all Flutter apps near unusable for TalkBack users.

**Comment by britannio** [comment] 2020-11-12 17:13
cc @TahaTesser

**Comment by TahaTesser** [comment] 2020-12-02 14:59
Hi @britannio 
Thanks for the ping
I can see an accessibility rectangle on a device running Android 11 on the latest `master` when navigating with swipe-right or left or selecting an item. 

### Preview
![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/48603081/100889288-f737a280-34dc-11eb-8bb4-b5c99dc8e25e.gif)

### Code sample
default code example

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel master, 1.24.0-8.0.pre.408, on macOS 11.0.1 20B29
    darwin-x64, locale en-GB)
    • Flutter version 1.24.0-8.0.pre.408 at
      /Users/tahatesser/Code/flutter_master
    • Framework revision 25986102c1 (2 hours ago), 2020-12-02 20:36:44 +0800
    • Engine revision 20caf54969
    • Dart version 2.12.0 (build 2.12.0-76.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (5 available)
    • RMX2001 (mobile)     • EUYTFEUSQSRGDA6D          • android-arm64  •
      Android 10 (API 29)
    • Taha’s iPad (mobile) • 00008020-000255113EE8402E • ios            • iOS
      14.2
    • macOS (desktop)      • macos                     • darwin-x64     • macOS
      11.0.1 20B29 darwin-x64
    • Web Server (web)     • web-server                • web-javascript •
      Flutter Tools
    • Chrome (web)         • chrome                    • web-javascript • Google
      Chrome 87.0.4280.67

• No issues found!


```

</details>

Are you able to reproduce it? Please provide reproducible steps 
Thank you

**Comment by britannio** [comment] 2020-12-02 15:22
I'm still able to reproduce the issue after running `flutter channel master && flutter upgrade` and creating the template app via `flutter create .`. The device I'm using is a OnePlus 7 Pro running Android 10

<details>
<summary>flutter doctor -v</summary>

```
britannio@dhcp-165-154 counter_2 % flutter doctor -v
[✓] Flutter (Channel master, 1.24.0-8.0.pre.408, on Mac OS X 10.15.7 19H15 darwin-x64, locale en-GB)
    • Flutter version 1.24.0-8.0.pre.408 at /Users/britannio/development/flutter
    • Framework revision 25986102c1 (3 hours ago), 2020-12-02 20:36:44 +0800
    • Engine revision 20caf54969
    • Dart version 2.12.0 (build 2.12.0-76.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/britannio/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 51.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2020.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (4 available)
    • GM1913 (mobile)  • 88a6947b   • android-arm64  • Android 10 (API 29)
    • macOS (desktop)  • macos      • darwin-x64     • Mac OS X 10.15.7 19H15 darwin-x64
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 87.0.4280.67
    ! Error: Britannio’s iPhone is not connected. Xcode will continue when Britannio’s iPhone is connected. (code -13)

• No issues found!
```

</details>

## Steps
- Create a Flutter app via `flutter create`.
- Turn on TalkBack
- Swipe left/right to switch talkback focus between the AppBar title, the two text widgets in the centre of the screen and the floating action button.

A green border is expected to appear around each widget as it gains focus. This is not what I'm observing when using v2 embedding.

I noticed that the only time I see a green border with the Flutter Gallery app is when I focus on the menu button(image below) as it's under the status bar.

![image](https://user-images.githubusercontent.com/33752528/100891886-a78fb180-34b1-11eb-9324-cac30009c7d7.png)

**Comment by TahaTesser** [comment] 2020-12-03 11:11
@britannio 
Thanks for confirming so I am labelling the issue, I tried Oneplus 8 running Android 11, still works for me
![ezgif com-gif-maker](https://user-images.githubusercontent.com/48603081/101003212-3968ee80-3586-11eb-9282-b1e60c9de8e5.gif)

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel master, 1.25.0-5.0.pre.45, on macOS 11.0.1 20B29
    darwin-x64, locale en-GB)
    • Flutter version 1.25.0-5.0.pre.45 at /Users/tahatesser/Code/flutter_master
    • Framework revision 81e1f7d1ed (10 hours ago), 2020-12-02 17:19:57 -0800
    • Engine revision 20caf54969
    • Dart version 2.12.0 (build 2.12.0-76.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (5 available)
    • IN2011 (mobile)      • c9d8ee0c                  • android-arm64  • Android 11 (API 30)
    • Taha’s iPad (mobile) • 00008020-000255113EE8402E • ios            • iOS 14.2
    • macOS (desktop)      • macos                     • darwin-x64     • macOS 11.0.1 20B29 darwin-x64
    • Web Server (web)     • web-server                • web-javascript • Flutter Tools
    • Chrome (web)         • chrome                    • web-javascript • Google Chrome 87.0.4280.88

• No issues found!
```

</details>

**Comment by mtropper** [comment] 2020-12-16 13:04
Same issue in Android 9 and Android 7

**Comment by mtropper** [comment] 2020-12-16 13:06
@TahaTesser any updates on this issue?

**Comment by jelen-HC** [comment] 2020-12-16 13:13
Am having the same issue with the Accessibility focus not showing up on older devices/Android versions (ie Android 7). Seemingly working as intended on Android 11

**Comment by britannio** [comment] 2021-01-26 14:51
I just updated my OnePlus 7 Pro to Android 11 and I can still reproduce this.

**Comment by eseidelGoogle** [comment] 2021-02-01 23:25
I recall @dnfield fixing something similar for GPay, but I wasn't under the impression it was a wider-hit issue?

**Comment by dnfield** [comment] 2021-02-02 00:09
I just tried this on a Pixel 4 and could not reproduce with the default template. 

The fix I did recently was specific to using a SurfaceView with a transparent status bar - if that's the case for the WHO app it should fix it for them too.

I don't have a OnePlus7 to test with right now. I have a Samsung S8 that needs to charge up and I can test it there as well though. It's possible this is device/vendor specific :\

**Comment by dnfield** [comment] 2021-02-02 00:25
Is not reproducing on Samsung either.

@gaaclarke - does this still reproduce on your setup on master?

**Comment by dnfield** [comment] 2021-02-02 00:25
And @britannio - does this reproduce for you on any other vendor Android phones? I or someone on the team can try to test this on a OnePlus model if it really is vendor specific.

**Comment by AlexV525** [comment] 2021-02-02 05:18
I've tested on OnePlus 6T with Android 10 and OnePlus 8 Pro with Android 11, the issue is not reproducible. Current flutter version is 1.26.0-13.0.pre.135.

**Comment by britannio** [comment] 2021-02-02 10:36
@dnfield I just tested again, I can no longer reproduce this on the `dev` and `master` branch when creating a new project, only the `stable` and `beta` channel.

**Comment by dnfield** [comment] 2021-02-02 22:33
Can you check if this bug exists on `flutter-1.26-candidate.17`? That or something close to it is about to go to beta AFAIK, and if it still exists there we might want a cherrypick.

**Comment by britannio** [comment] 2021-02-02 22:55
> Can you check if this bug exists on `flutter-1.26-candidate.17`? That or something close to it is about to go to beta AFAIK, and if it still exists there we might want a cherrypick.

It does not exist on that version :)

Output of `flutter --version`:
```
Flutter 1.26.0-17.1.pre • channel flutter-1.26-candidate.17 • https://github.com/flutter/flutter.git
Framework • revision c40e5294dd (4 days ago) • 2021-01-29 08:44:18 -0800
Engine • revision 5d3477eab4
Tools • Dart 2.12.0 (build 2.12.0-259.0.dev)
```

**Comment by dnfield** [comment] 2021-02-03 01:51
Thanks!  Closing this as fixed

**Closed by dnfield** 2021-02-03 01:51 UTC
Labels: P3, a: accessibility, engine, found in release: 1.24, has reproducible steps, passed first triage, platform-android
