### ISSUE TITLE
Navigator widget causes a large jump in Graphics memory usage

### ISSUE THREAD

**Issue by pcsosinski** [flutter/flutter#56484] opened 2020-05-06 21:43 UTC
Related to b/140218817

/cc @jason-simmons @cbracken @mehmetf

**Comment by goderbauer** [comment] 2020-05-07 00:08
Can you elaborate what you mean by “child navigator”? Do you mean inserting a Navigator widget [1] as a child of another widget?

Is there any code to reproduce this? Is there an internal issue with more information?

[1] https://api.flutter.dev/flutter/widgets/Navigator-class.html

**Comment by mehmetf** [comment] 2020-05-08 15:27
I observed this while testing various components of the customer:money application. I don't have a simple repro yet. I am going to /cc you on an internal doc.

**Comment by liyuqian** [comment] 2020-05-08 20:46
Is this jump reproducible using our flutter gallery app (either the old one https://github.com/flutter/flutter/tree/master/dev/integration_tests/flutter_gallery or the new one https://github.com/flutter/gallery)?

**Comment by goderbauer** [comment] 2020-05-08 21:21
I am currently not able to reproduce this in a small example. Here is what I did: I created a simple example app where the child navigator can be turned on/off:

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

const bool withChildNavigator = true;

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: !withChildNavigator
          ? Center(child: Text('No child Navigator.'),)
          : Navigator(
              onGenerateRoute: (RouteSettings settings) {
                return PageRouteBuilder(
                  settings: settings,
                  pageBuilder: (BuildContext context, Animation<double> _, Animation<double> __) {
                    return Center(child: Text('I am inside a child Navigator.'));
                  }
                );
              },
            )
    );
  }
}
```

Whether or not `withChildNavigator` is true or false, the Android Profiler always reports 46.2 MB of Graphics memory in use (app was run in profile mode).

It's probably not the Navigator widget itself that causes the problem.

**Comment by goderbauer** [comment] 2020-05-09 00:20
I was also unable to reproduce the results in the customer:money application. Assigning this back to @mehmetf to double-check that it wasn't a fluke.

**Comment by mehmetf** [comment] 2020-05-09 17:31
Second round of tests indicate this was a fluke. Graphics usage remains ~70M in both child/no child nav case.

**Closed by mehmetf** 2020-05-09 17:31 UTC
Labels: customer: money (g3), engine, framework, perf: memory, severe: customer critical, severe: performance
