### ISSUE TITLE
[web]: Blank web application when cloud_firestore is added to pubspec.yaml

### ISSUE THREAD

**Issue by Toernblom** [flutter/flutter#51917] opened 2020-03-04 07:21 UTC
The issue is that when I'm typing the command:
`flutter run -d chrome`
chrome gets launched, flutter connects to chrome and starts debug service listening. However, the screen is blank and nothing happens after that.

Version & channel: Flutter 1.14.6 • channel beta
Chrome version: 80.0.3987.132

[√] Flutter (Channel beta, v1.14.6, on Microsoft Windows [Version 10.0.18362.657], locale en-SE)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
[√] Chrome - develop for the web
[√] Android Studio (version 3.4)
[√] VS Code (version 1.42.1)
[√] Connected device (2 available)

[√] Flutter (Channel beta, v1.14.6, on Microsoft Windows [Version 10.0.18362.657], locale en-SE)
    • Flutter version 1.14.6 at C:\src\flutter
    • Framework revision fabeb2a16f (5 weeks ago), 2020-01-28 07:56:51 -0800
    • Engine revision c4229bfbba
    • Dart version 2.8.0 (build 2.8.0-dev.5.0 fc3af737c7)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at C:\Users\Anton\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 39.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] VS Code (version 1.42.1)
    • VS Code at C:\Users\Anton\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.8.1

[√] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 80.0.3987.132
    • Web Server • web-server • web-javascript • Flutter Tools

• No issues found!

**Comment by msarkrish** [comment] 2020-03-04 09:38
Duplicate of #49482

**Comment by TahaTesser** [comment] 2020-03-04 11:43
Closing as duplicate

**Closed by TahaTesser** 2020-03-04 11:43 UTC
