### ISSUE TITLE
java.lang.RuntimeException: API key not found.

### ISSUE THREAD

**Issue by bhavesh-srashtasoft** [flutter/flutter#28719] opened 2019-03-01 10:49 UTC
Hii Any Here Can help me,
I am getting error when i add Google Map API key in AndroidManifest.xml getting error in Flutter.

My Error Log Is : -
I/Google Maps Android API( 8970): Google Play services client version: 12451000
I/Google Maps Android API( 8970): Google Play services package version: 15090037
E/MethodChannel#flutter/platform_views( 8970): Failed to handle method call
E/MethodChannel#flutter/platform_views( 8970): java.lang.RuntimeException: API key not found.  Check that <meta-data android:name="com.google.android.geo.API_KEY" android:value="your API key"/> is in the <application> element of AndroidManifest.xml
E/MethodChannel#flutter/platform_views( 8970): 	at com.google.maps.api.android.lib6.drd.q.b(:com.google.android.gms.dynamite_mapsdynamite@15090081@15.0.90 (100400-231259764):20)
E/MethodChannel#flutter/platform_views( 8970): 	at com.google.maps.api.android.lib6.auth.e.a(:com.google.android.gms.dynamite_mapsdynamite@15090081@15.0.90 (100400-231259764):10)
E/MethodChannel#flutter/platform_views( 8970): 	at com.google.maps.api.android.lib6.impl.f.a(:com.google.android.gms.dynamite_mapsdynamite@15090081@15.0.90 (100400-231259764):3)
E/MethodChannel#flutter/platform_views( 8970): 	at com.google.android.gms.maps.internal.b.a(:com.google.android.gms.dynamite_mapsdynamite@15090081@15.0.90 (100400-231259764):19)
E/MethodChannel#flutter/platform_views( 8970): 	at com.google.android.gms.maps.internal.CreatorImpl.a(:com.google.android.gms.dynamite_mapsdynamite@15090081@15.0.90 (100400-231259764):57)
E/MethodChannel#flutter/platform_views( 8970): 	at com.google.android.gms.maps.internal.CreatorImpl.newMapViewDelegate(:com.google.android.gms.dynamite_mapsdynamite@15090081@15.0.90 (100400-231259764):31)
E/MethodChannel#flutter/platform_views( 8970): 	at com.google.android.gms.maps.internal.i.a(:com.google.android.gms.dynamite_mapsdynamite@15090081@15.0.90 (100400-231259764):62)
E/MethodChannel#flutter/platform_views( 8970): 	at ft.onTransact(:com.google.android.gms.dynamite_mapsdynamite@15090081@15.0.90 (100400-231259764):4)
E/MethodChannel#flutter/platform_views( 8970): 	at android.os.Binder.transact(Binder.java:667)
E/MethodChannel#flutter/platform_views( 8970): 	at com.google.android.gms.internal.maps.zza.zza(Unknown Source:10)
E/MethodChannel#flutter/platform_views( 8970): 	at com.google.android.gms.maps.internal.zzf.zza(Unknown Source:19)
E/MethodChannel#flutter/platform_views( 8970): 	at com.google.android.gms.maps.MapView$zzb.createDelegate(Unknown Source:13)
E/MethodChannel#flutter/platform_views( 8970): 	at com.google.android.gms.dynamic.DeferredLifecycleHelper.zaa(Unknown Source:18)
E/MethodChannel#flutter/platform_views( 8970): 	at com.google.android.gms.dynamic.DeferredLifecycleHelper.onCreate(Unknown Source:22)
E/MethodChannel#flutter/platform_views( 8970): 	at com.google.android.gms.maps.MapView.onCreate(Unknown Source:26)
E/MethodChannel#flutter/platform_views( 8970): 	at io.flutter.plugins.googlemaps.GoogleMapController.init(GoogleMapController.java:105)
E/MethodChannel#flutter/platform_views( 8970): 	at io.flutter.plugins.googlemaps.GoogleMapBuilder.build(GoogleMapBuilder.java:24)
E/MethodChannel#flutter/platform_views( 8970): 	at io.flutter.plugins.googlemaps.GoogleMapFactory.create(GoogleMapFactory.java:38)
E/MethodChannel#flutter/platform_views( 8970): 	at io.flutter.plugin.platform.SingleViewPresentation.onCreate(SingleViewPresentation.java:130)
E/MethodChannel#flutter/platform_views( 8970): 	at android.app.Dialog.dispatchOnCreate(Dialog.java:407)
E/MethodChannel#flutter/platform_views( 8970): 	at android.app.Dialog.show(Dialog.java:302)
E/MethodChannel#flutter/platform_views( 8970): 	at android.app.Presentation.show(Presentation.java:249)
E/MethodChannel#flutter/platform_views( 8970): 	at io.flutter.plugin.platform.VirtualDisplayController.<init>(VirtualDisplayController.java:75)
E/MethodChannel#flutter/platform_views( 8970): 	at io.flutter.plugin.platform.VirtualDisplayController.create(VirtualDisplayController.java:47)
E/MethodChannel#flutter/platform_views( 8970): 	at io.flutter.plugin.platform.PlatformViewsController.createPlatformView(PlatformViewsController.java:179)
E/MethodChannel#flutter/platform_views( 8970): 	at io.flutter.plugin.platform.PlatformViewsController.onMethodCall(PlatformViewsController.java:118)
E/MethodChannel#flutter/platform_views( 8970): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:201)
E/MethodChannel#flutter/platform_views( 8970): 	at io.flutter.view.FlutterNativeView$PlatformMessageHandlerImpl.handleMessageFromDart(FlutterNativeView.java:188)
E/MethodChannel#flutter/platform_views( 8970): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:202)
E/MethodChannel#flutter/platform_views( 8970): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#flutter/platform_views( 8970): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/MethodChannel#flutter/platform_views( 8970): 	at android.os.Looper.loop(Looper.java:165)
E/MethodChannel#flutter/platform_views( 8970): 	at android.app.ActivityThread.main(ActivityThread.java:6729)
E/MethodChannel#flutter/platform_views( 8970): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter/platform_views( 8970): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/MethodChannel#flutter/platform_views( 8970): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
E/flutter ( 8970): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: PlatformException(error, API key not found.  Check that <meta-data android:name="com.google.android.geo.API_KEY" android:value="your API key"/> is in the <application> element of AndroidManifest.xml, null)
E/flutter ( 8970): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:564:7)
E/flutter ( 8970): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:302:33)
E/flutter ( 8970): <asynchronous suspension>
E/flutter ( 8970): #2      AndroidViewController._create (package:flutter/src/services/platform_views.dart:580:54)
E/flutter ( 8970): <asynchronous suspension>
E/flutter ( 8970): #3      AndroidViewController.setSize (package:flutter/src/services/platform_views.dart:505:14)
E/flutter ( 8970): <asynchronous suspension>
E/flutter ( 8970): #4      RenderAndroidView._sizePlatformView (package:flutter/src/rendering/platform_view.dart:178:29)
E/flutter ( 8970): <asynchronous suspension>
E/flutter ( 8970): #5      RenderAndroidView.performResize (package:flutter/src/rendering/platform_view.dart:159:5)
E/flutter ( 8970): #6      RenderObject.layout (package:flutter/src/rendering/object.dart:1617:9)
E/flutter ( 8970): #7      RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:259:13)
E/flutter ( 8970): #8      RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
E/flutter ( 8970): #9      RenderStack.performLayout (package:flutter/src/rendering/stack.dart:510:15)
E/flutter ( 8970): #10     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
E/flutter ( 8970): #11     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:738:15)
E/flutter ( 8970): #12     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
E/flutter ( 8970): #13     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:738:15)
E/flutter ( 8970): #14     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
E/flutter ( 8970): #15     _RenderSingleChildViewport.performLayout (package:flutter/src/widgets/single_child_scroll_view.dart:486:13)
E/flutter ( 8970): #16     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
E/flutter ( 8970): #17     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter ( 8970): #18     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
E/flutter ( 8970): #19     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter ( 8970): #20     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
E/flutter ( 8970): #21     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter ( 8970): #22     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
E/flutter ( 8970): #23     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter ( 8970): #24     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
E/flutter ( 8970): #25     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter ( 8970): #26     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
E/flutter ( 8970): #27     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter ( 8970): #28     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
E/flutter ( 8970): #29     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter ( 8970): #30     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
E/flutter ( 8970): #31     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter ( 8970): #32     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
E/flutter ( 8970): #33     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:199:11)
E/flutter ( 8970): #34     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
E/flutter ( 8970): #35     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:142:11)
E/flutter ( 8970): #36     _ScaffoldLayout.performLayout (package:flutter/src/mate

**Comment by Kartik1607** [comment] 2019-03-01 13:52
Please post code from your `AndroidManifest` file as well.

**Comment by EngTee** [comment] 2019-03-20 05:59
I'm getting similar error and this is my manifest:

<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.example.testApp">

    <application
        android:name="io.flutter.app.FlutterApplication"
        android:label="testApp"
        android:icon="@mipmap/ic_launcher">
        <meta-data android:name="com.google.android.geo.API_KEY" android:value="xxxxxxx"/> 
        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            <meta-data
                android:name="io.flutter.app.android.SplashScreenUntilFirstFrame"
                android:value="true" />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
            <intent-filter>
                <action android:name="FLUTTER_NOTIFICATION_CLICK" />
                <category android:name="android.intent.category.DEFAULT" />
            </intent-filter>
        </activity>
    </application>
</manifest>

**Comment by craigloftus** [comment] 2019-03-22 15:58
I was getting a similar error, running `flutter clean` (in the directory of the effected project) solved the issue for me.

Looks like a duplicate of #25556

Presumably `flutter clean` is only required if you put the `meta-attr` in the wrong location initially... which seems all too common.

**Comment by EngTee** [comment] 2019-03-24 06:33
Thx! It works for me!

**Comment by shivarajnaidu** [comment] 2019-09-24 14:10
Tnx! worked for me too.. I think have to specify this somewhere in official docs of this plugin

**Comment by shankar81** [comment] 2019-10-25 05:41
Thanks @craigloftus

**Comment by haozhenxiao** [comment] 2019-11-03 09:46
I have my AndroidManifest as shown below, my API key is restricted and I ran flutter clean several times, still kept getting the error `API key not found`.

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.succo.succo">
    <!-- Flutter needs it to communicate with the running application
         to allow setting breakpoints, to provide hot reload, etc.
    -->
    <uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <application>
        <meta-data
            android:name="com.google.android.geo.API_KEY"
            android:value="My real key"/>
    </application>
</manifest>
```

**Comment by Gperez88** [comment] 2019-11-19 21:50
> I have my AndroidManifest as shown below, my API key is restricted and I ran flutter clean several times, still kept getting the error `API key not found`.
> 
> ```
> <manifest xmlns:android="http://schemas.android.com/apk/res/android"
>     package="com.succo.succo">
>     
>     <uses-permission android:name="android.permission.INTERNET"/>
>     <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
>     <application>
>         <meta-data
>             android:name="com.google.android.geo.API_KEY"
>             android:value="My real key"/>
>     </application>
> </manifest>
> ```

have same issues.

**Comment by luqmanhakem** [comment] 2019-12-19 07:48
> > I have my AndroidManifest as shown below, my API key is restricted and I ran flutter clean several times, still kept getting the error `API key not found`.
> > ```
> > <manifest xmlns:android="http://schemas.android.com/apk/res/android"
> >     package="com.succo.succo">
> >     
> >     <uses-permission android:name="android.permission.INTERNET"/>
> >     <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
> >     <application>
> >         <meta-data
> >             android:name="com.google.android.geo.API_KEY"
> >             android:value="My real key"/>
> >     </application>
> > </manifest>
> > ```
> 
> have same issues.

Here's some quick fix that you could try:

**1. Run 'flutter clean'**

**2. Open up your AndroidManifest.xml (android/app/src/main):**

_From this:_
<meta-data android:name="com.google.android.geo.API_KEY"
               android:value="YOUR_API_KEY"/>

_To this:_
<meta-data android:name="com.google.android.geo.API_KEY"
               android:value="AIxxxxxxYOURAPIKEYxxxxxxxxxxxx"/>

3. Run 'flutter pub get

4. Go try debug the apps.

I occurred the same issue when trying this repo example https://github.com/rodydavis/easy_google_maps, but I managed to solve & run.

**Comment by giorgio79** [comment] 2020-02-06 13:14
I did everything above, yet I am still getting the error message... Anyone managed to solve the problem?

**Comment by giorgio79** [comment] 2020-02-06 15:28
Wow, ok it turned out the issue was with Flutter in my case.... Not with Google Maps!!!
https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects
Had to restart a blank project and it all worked.

**Comment by TahaTesser** [comment] 2020-02-28 13:19
Hi @bhavesh-srashtasoft  given your last message I feel safe to close this issue,
if you disagree please write in the comments and I will reopen it. 
Thank you

**Closed by TahaTesser** 2020-02-28 13:19 UTC
Labels: p: maps, plugin

**Comment by archanapunitha** [comment] 2020-06-12 06:08
Thanks.It's really worked for me toooo !!!
