### ISSUE TITLE
Provide an option to show last typed character briefly in TextField when obscureText is true on IOS

### ISSUE THREAD

**Issue by KIA-AKIRA** [flutter/flutter#134412] opened 2023-09-11 09:21 UTC
### Use case

I have a flutter app with a password textfield

```
TextFormField(
  obscureText: true,
)
```

I run the app on Android, the password is obscured, it shows the last letter for a while, like this [
![image](https://github.com/flutter/flutter/assets/141227485/e9226db3-dcf4-48c6-bbe4-bfcf788d8a29)
](url)

But when running the app on iOS, the last letter is hidden immediately so user can't see the last letter. However, I want it to be displayed last letter in the same way on Android.

### Proposal

I have no ideals

**Comment by mti-lamlva** [comment] 2023-09-11 09:28
Im facing with the same issue, How can i do it ?

**Comment by dam-ease** [comment] 2023-09-11 13:29
Thanks for filing this issue. There seems to be an issue currently open that describes this issue. Kindly upvote and follow up on this issue for updates. Closing this as a duplicate of https://github.com/flutter/flutter/issues/115359

**Closed by dam-ease** 2023-09-11 13:29 UTC
Labels: in triage
