### ISSUE TITLE
Android Studio Problems

### ISSUE THREAD

**Issue by dovahkiin98** [flutter/flutter#15440] opened 2018-03-12 13:28 UTC
Android Studio keeps "updating indices" all the time, every 2 or 3 seconds it repeats the process.
Also it can't create a new project.

using Android Studio 3.1.0-rc01 with latest flutter plugin and flutter 0.1.8-pre.43

**Comment by zoechi** [comment] 2018-03-12 14:45
Can you please add the output of `flutter doctor -v`?

**Comment by jaredzhang** [comment] 2018-03-19 02:44
@dovahkiin98  I had the similar problem, try to invalidate caches and restart studio.

**Comment by bartektartanus** [comment] 2018-03-22 19:52
Same issue here. Invalidate and restart doesn't help. This is my `flutter doctor -v`

```
[✓] Flutter (Channel beta, v0.1.5, on Mac OS X 10.13.3 17D102, locale pl-PL)
    • Flutter version 0.1.5 at /Users/bartolini/workspace-private/flutter
    • Framework revision 3ea4d06340 (4 weeks ago), 2018-02-22 11:12:39 -0800
    • Engine revision ead227f118
    • Dart version 2.0.0-dev.28.0.flutter-0b4f01f759

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/bartolini/Library/Android/sdk
    • Android NDK at /Users/bartolini/Library/Android/sdk/ndk-bundle
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.2
    • CocoaPods version 1.4.0

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

• No issues found!
```

**Comment by boeledi** [comment] 2018-03-27 00:28
I have exactly the same issue on Windows, since I updated the version of Android Studio
Invalidate and restart does not help.

Here is the version:

Android Studio 3.1
Build #AI-173.4670197, built on March 22, 2018
JRE: 1.8.0_152-release-1024-b02 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 7 6.1

**Comment by zoechi** [comment] 2018-03-27 07:26
try `flutter channel dev` `flutter doctor`
The `beta` channel is a bit outdated already especially if you are using the latest versions of plugins.

**Comment by geiszla** [comment] 2018-03-27 13:46
I have the same problem and found an earlier issue on the flutter-intellij repo (https://github.com/flutter/flutter-intellij/issues/1735), which was fixed in the case of creating a new project. However I have no idea how to solve this when you have an existing project.

**Comment by SeaRoth** [comment] 2018-03-27 14:07
It looks like they're on it. (https://github.com/flutter/flutter-intellij/issues/1735)

As for now I'm downloading the older version of AS to circumvent: https://developer.android.com/studio/archive.html

![image](https://user-images.githubusercontent.com/3461713/37972477-535091ae-318d-11e8-8f0d-a4ee5394f757.png)

**Comment by Gustik** [comment] 2018-03-28 02:00
Same issue on Android Studio 3.1.

**Comment by zoechi** [comment] 2018-07-06 08:05
Sorry for not being able to come back to this earlier but we weren't able to reproduce.
Is this still an issue.

**Comment by bartektartanus** [comment] 2018-07-06 09:56
Not anymore.

**Comment by zoechi** [comment] 2018-07-06 10:06
@bartektartanus thanks for the feedback! 
I'm going to close this issue then. Just add a comment if you think this is still an issue to get it reopened or create a new issue.

**Closed by zoechi** 2018-07-06 10:06 UTC
Labels: waiting for customer response
