### ISSUE TITLE
Bad build APK target-platform=android-arm

### ISSUE THREAD

**Issue by sm2017** [flutter/flutter#81263] opened 2021-04-27 04:58 UTC
## Steps to Reproduce

I am using the following command to release APK

```
flutter build apk --obfuscate --split-debug-info=./build/info --target-platform=android-arm

```

I want to reduce the size of app, and as the flutter Cannot build release mode for `x86` ABI. I only choose `armeabi-v7a` which is `android-arm`

> Cannot build release mode for x86 ABI. For more information see https://flutter.dev/docs/deployment/android#what-are-the-supported-target-architectures .

But the output APK it not running on my Xiaomi Redmi 9, But when I use `--split-per-abi` flag and I can install both `app-armeabi-v7a-release.apk` and `app-arm64-v8a-release.apk` release

**Expected results:** 

I think `--target-platform=android-arm` must be equal to  `armeabi-v7a` and must run on my device

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
[√] Flutter (Channel stable, 2.0.5, on Microsoft Windows [Version 10.0.18363.1500], locale en-US)
    • Flutter version 2.0.5 at C:\flutter
    • Framework revision adc687823a (11 days ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\PC\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 29.0.2
    • ANDROID_HOME = C:\Users\PC\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 90.0.4430.85
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 89.0.774.77

• No issues found!

```

</details>

**Comment by sm2017** [comment] 2021-04-27 05:01
Output of `--target-platform=android-arm` is 26MB for me
`app-armeabi-v7a-release.apk` is 16.1MB and `app-arm64-v8a-release.apk ` is 16.9MB

**Comment by TahaTesser** [comment] 2021-04-27 08:59
Hi @sm2017 

> flutter build apk --obfuscate --split-debug-info=./build/info --target-platform=android-arm

This command only produces one apk, It works fine. The same result with `flutters build apk  --target-platform=android-arm`

<details> 
<summary>flutter doctor -v</summary> 

```console
[✓] Flutter (Channel stable, 2.0.5, on Microsoft Windows [Version 10.0.19042.928], locale en-US)
    • Flutter version 2.0.5 at C:\Users\Taha\Code\flutter_stable
    • Framework revision adc687823a (11 days ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\Taha\Code\SDK
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.9.31205.134
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Users\Taha\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] IntelliJ IDEA Community Edition (version 2021.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.3.3
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.55.2)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.21.0

[✓] Connected device (4 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Windows (desktop)                  • windows       • windows-x64    • Microsoft Windows [Version 10.0.19042.928]
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 90.0.4430.93
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 90.0.818.46

! Doctor found issues in 1 category.
```
		
</details>


> But the output APK it not running on my Xiaomi Redmi 9, But when I use --split-per-abi flag and I can install both app-armeabi-v7a-release.apk and app-arm64-v8a-release.apk release

Can you please elaborate what's the issue is exactly? Does APK fails to install or you see a blank screen? It works with `--split-per-abi `? So which command failed the app? Steps to reproduce are not clear

Can you please complete reproducible steps
Thank you

**Comment by TahaTesser** [comment] 2021-04-28 06:20
Hi @sm2017 
So `flutter build apk --obfuscate --split-debug-info=./build/info --target-platform=android-arm` build APK fails on your device Does the crash happen with a new project `flutter create myapp` (To be safe, the issue from your code)? Can you please try another device?

**Comment by sm2017** [comment] 2021-04-28 07:42
@TahaTesser the apk of `flutter build apk --obfuscate --split-debug-info=./build/info --target-platform=android-arm` for  a new project `flutter create myapp` works for my on multiple tested devices

but the apk  of `flutter build apk --obfuscate --split-debug-info=./build/info --target-platform=android-arm` for my application crashes (this time not immediatly, I seen 2-3 seconds white screen) after installed and opened, I install the APK in the emulator, it works well in emulator but crashes in all devices I tested

In logcat I see the following error


```
04-28 12:04:47.550 17888 17888 E AndroidRuntime: Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.app-d-vL866CfE7DlbA2Yt7vUQ==/base.a
pk"],nativeLibraryDirectories=[/data/app/com.app-d-vL866CfE7DlbA2Yt7vUQ==/lib/arm64, /data/app/com.app-d-vL866CfE7DlbA2Yt7vUQ==/base.apk!/lib/arm64-v8a, /system/lib64, /product/lib64]]] couldn't find "libflutter.so"
04-28 12:04:47.550 17888 17888 E AndroidRuntime:        at io.flutter.embedding.engine.loader.FlutterLoader.ensureInitializationComplete(Unknown Source:368)
04-28 12:04:47.550 17888 17888 E AndroidRuntime:        at io.flutter.embedding.engine.FlutterEngine.<init>(Unknown Source:174)
04-28 12:04:47.550 17888 17888 E AndroidRuntime:        at io.flutter.embedding.engine.FlutterEngine.<init>(Unknown Source:16)
04-28 12:04:47.550 17888 17888 E AndroidRuntime:        at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.setupFlutterEngine(Unknown Source:106)
04-28 12:04:47.550 17888 17888 E AndroidRuntime:        at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(Unknown Source:7)
04-28 12:04:47.550 17888 17888 E AndroidRuntime:        at io.flutter.embedding.android.FlutterActivity.onCreate(Unknown Source:13)
04-28 12:04:47.550 17888 17888 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:7893)
04-28 12:04:47.550 17888 17888 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:7880)
04-28 12:04:47.550 17888 17888 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)
04-28 12:04:47.550 17888 17888 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3313)
04-28 12:04:47.550 17888 17888 E AndroidRuntime:        ... 11 more

```

May be related I don't know I have `multiDexEnabled true` in my application

**Comment by TahaTesser** [comment] 2021-04-29 06:45
@sm2017 
Can you please provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that crashes the APK, I have a Xiaomi device, I can try
Thank you

**Comment by sm2017** [comment] 2021-04-29 07:59
@TahaTesser I will try to provide it, I'm not sure that I'll able to create, but I do my best, wait for a week, I'm too busy now

**Comment by sm2017** [comment] 2021-04-29 08:00
@TahaTesser just a question , is `--target-platform=android-arm` equal to `armeabi-v7a` or not?

**Comment by TahaTesser** [comment] 2021-04-29 08:59
@sm2017 
`armeabi-v7a` is 32bit, `android-arm` probably producing 64 bit too, I am not expert in android architecture, I can verify if you can provide steps, somebody from tool team will help with this
Thank you

**Comment by pedromassangocode** [comment] 2021-05-21 08:18
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2021-05-21 08:18 UTC
Labels: in triage, waiting for customer response
