### ISSUE TITLE
showTimePicker doesn't expose it's internal widget

### ISSUE THREAD

**Issue by codegrue** [flutter/flutter#80280] opened 2021-04-12 14:38 UTC
If you look at the documentation for showDatePicker, under See Also, there is a CalendarDatePicker which is the content of the dialog so it can be used independently.

https://api.flutter.dev/flutter/material/showDatePicker.html

If you compare the showTimePicker, the equivalent widget ("Dial") is marked as private so it cannot be used independently of the dialog.

https://api.flutter.dev/flutter/material/showTimePicker.html

Specifically, in time_picker.dart, line 915, the _Dial widget should be public so use independently.

**Comment by HansMuller** [comment] 2021-04-12 22:06
CC @darrenaustin

**Comment by werainkhatri** [comment] 2021-04-18 15:44
I think the description is sufficient to solve this issue, make the `_Dial` widget public.

Could you assign this issue to me?

**Comment by codegrue** [comment] 2021-04-20 16:50
I would also rename it something like TimePicker to be consistent with CalendarDatePicker

**Comment by bendelonlee** [comment] 2021-05-10 16:58
I would appreciate this feature as well / +1

**Comment by MrBirb** [comment] 2021-07-29 15:29
@TahaTesser Looks like a duplicate of #76053. Wdyt?

**Comment by TahaTesser** [comment] 2021-07-30 10:42
@MrBirb 
I agree, closing as duplicate of https://github.com/flutter/flutter/issues/76053

**Closed by TahaTesser** 2021-07-30 10:42 UTC
Labels: f: date/time picker, f: material design, framework, passed first triage, severe: new feature
