### ISSUE TITLE
App Bar Sizes Differently on Start vs. Hot Restart/Reload

### ISSUE THREAD

**Issue by jbryanh** [flutter/flutter#137959] opened 2023-11-06 20:30 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Install example app.
2. On initial load, note appbar height.
3. hot reload or hot restart - notice app bar resizes.

Note that the offending code that causes this behavior is this:

    MediaQueryData windowData = MediaQueryData.fromView(View.of(context));
    windowData = windowData.copyWith(
      textScaleFactor: 1.0, //or whatever you want
    );

Along with the MediaQuery with windowData.  This is the preferred way to set the textScaleFactor because it minimizes widget rebuillds in cases where keyboard is used, etc.  For some reason it is causing this appbar initial build to be wrong.

### Expected results

expect a consistent app bar height based on theme data and/or specified PreferredSize, toolbarheight.

### Actual results

appbar resizes

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/services.dart';
import 'package:flutter/material.dart';

void main() {
  WidgetsFlutterBinding.ensureInitialized();
  SystemChrome.setEnabledSystemUIMode(SystemUiMode.manual, overlays: [SystemUiOverlay.bottom]); //to hide status bar
  SystemChrome.setPreferredOrientations([DeviceOrientation.portraitUp, DeviceOrientation.portraitDown]);
  // InAppPurchaseAndroidPlatformAddition.enablePendingPurchases();
  runApp(AppBarHeightExample());
}

final ThemeData appTheme = buildAppTheme();

ThemeData buildAppTheme() {
  final ThemeData base = ThemeData.light();

  return base.copyWith(
    appBarTheme: base.appBarTheme.copyWith(
      toolbarHeight: 55,
    ),
  );
}

class AppBarHeightExample extends StatelessWidget {
  const AppBarHeightExample({super.key});

  @override
  Widget build(BuildContext context) {
    MediaQueryData windowData = MediaQueryData.fromView(View.of(context));
    windowData = windowData.copyWith(
      textScaleFactor: 1.0, //or whatever you want
    );

    return MediaQuery(
      data: windowData,
      child: MaterialApp(
        debugShowCheckedModeBanner: false,
        theme: appTheme,
        home: Scaffold(
          resizeToAvoidBottomInset: true,
          appBar: PreferredSize(
            preferredSize: const Size.fromHeight(55),
            child: AppBar(
              toolbarHeight: 55,
              title: Padding(
                padding: const EdgeInsets.only(top: 8.0, left: 10, right: 10),
                child: Center(
                  child: Text(
                    'AppBar Height Example',
                    overflow: TextOverflow.fade,
                    style: TextStyle(fontSize: 50, color: Colors.white,
                    ),
                    maxLines: 1,
                  ),
                ),
              ),
              centerTitle: true,
            ),
          ),
          body: const Center(
            child: Text('Hello World'),
          ),
        ),
      ),
    );
  }
}```

</details>


### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>


### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.13.6, on macOS 13.5.2 22G91 darwin-arm64 (Rosetta), locale en-US)
    • Flutter version 3.13.6 on channel stable at /Users/bryanhunsberger/Developer/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ead455963c (6 weeks ago), 2023-09-26 18:28:17 -0700
    • Engine revision a794cf2681
    • Dart version 3.1.3
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/bryanhunsberger/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/bryanhunsberger/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.14.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 75.1.4
    • Dart plugin version 232.10072.19

[✓] Connected device (5 available)
    • Pixel XL (mobile)       • HT6CM0202172                             • android-arm64  • Android 10 (API 29)
    • moto e5 go (mobile)     • ZY327294VJ                               • android-arm    • Android 8.1.0 (API 27)
    • Bryan’s iPhone (mobile) • da4ff0ce2797d41a8f1ceafeef1dd3b9a1fd28a1 • ios            • iOS 15.7.9 19H365
    • macOS (desktop)         • macos                                    • darwin-arm64   • macOS 13.5.2 22G91 darwin-arm64 (Rosetta)
    • Chrome (web)            • chrome                                   • web-javascript • Google Chrome 119.0.6045.105

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by jbryanh** [comment] 2023-11-06 20:58
Note also that moving the MediaQuery into the body, instead of above the scaffold will eliminate the problem, however the textscalefactor override then only applies to the body of that scaffold and needs to be reapplied to every page or dialog individually, so not a valid workaround.

**Comment by dam-ease** [comment] 2023-11-07 09:25
Thanks for filing this @jbryanh. I can't seem to reproduce this on the latest versions of flutter running the code sample you shared. 

| Before Hot Restart/Reload | After Hot Restart/Reloa |
|--------|--------|
| <img src="https://github.com/flutter/flutter/assets/53122008/e51255ec-5006-4bda-b00d-384231da0eb0"> | <img src="https://github.com/flutter/flutter/assets/53122008/85e59f6d-8242-4973-bda9-28b462afc5f5"> | 

<details><summary>flutter doctor -v</summary>
<p>

```
[!] Flutter (Channel stable, 3.13.9, on macOS 14.0 23A344 darwin-arm64, locale
    en-NG)
    • Flutter version 3.13.9 on channel stable at
      /Users/damilolaalimi/sdks/flutter
    ! Warning: `dart` on your path resolves to
      /opt/homebrew/Cellar/dart/3.1.5/libexec/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/damilolaalimi/sdks/flutter.
      Consider adding /Users/damilolaalimi/sdks/flutter/bin to the front of your
      path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d211f42860 (12 days ago), 2023-10-25 13:42:25 -0700
    • Engine revision 0545f8705d
    • Dart version 3.1.5
    • DevTools version 2.25.0
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/damilolaalimi/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/damilolaalimi/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)
    ! Some Android licenses not accepted. To resolve this, run: flutter doctor
      --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)

[!] Android Studio (version unknown)
    • Android Studio at /Users/damilolaalimi/Downloads/Android Studio
      Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to determine Android Studio version.
    • Java version OpenJDK Runtime Environment (build
      17.0.7+0-17.0.7b1000.6-10550314)

[✓] VS Code (version 1.84.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] VS Code (version 1.83.1)
    • VS Code at /Users/damilolaalimi/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (5 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554                        •
      android-arm64  • Android 14 (API 34) (emulator)
    • Damilola’s iPhone (mobile)  • 00008110-001964480AE1801E            • ios
      • iOS 17.0.2 21A351
    • iPhone 15 Pro Max (mobile)  • 56A225C9-B8F6-4201-A0AE-8C3CFA4CE152 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-17-0 (simulator)
    • macOS (desktop)             • macos                                •
      darwin-arm64   • macOS 14.0 23A344 darwin-arm64
    • Chrome (web)                • chrome                               •
      web-javascript • Google Chrome 119.0.6045.105

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 3 categories.
``` 

</p>
</details>

**Comment by jbryanh** [comment] 2023-11-07 14:29
Shoot, I meant to note this - my physical testing device is an iphone 7.  I will make a point to publish to testflight with this code to test on a physical live device with latest iOS, to see if it has comparable behavior.  I'll need a few days before I can get to that.

**Comment by dam-ease** [comment] 2023-11-08 07:56
Thanks for your response. I don't have a physical iPhone 7 to test this but I tested with a physical iPhone 13 (iOS 17) and couldn't reproduce this on the latest versions of flutter. I'll await the results of your test to see if this still persists.
Thank you!

**Comment by jbryanh** [comment] 2023-11-29 17:08
Damilola,

 

You can close this.  When I updated to ios17, the issue went away.

Thanks!



Bryan

**Comment by danagbemava-nc** [comment] 2023-11-30 06:42
Closing this based on the response above

**Closed by danagbemava-nc** 2023-11-30 06:42 UTC
Labels: in triage
