### ISSUE TITLE
[go_router] With each navigation operation, all previous non-const routes are rebuilt.

### ISSUE THREAD

**Issue by huseyinerenguler** [flutter/flutter#140563] opened 2023-12-23 08:03 UTC
### What package does this bug report belong to?

go_router

### What target platforms are you seeing this bug on?

Android, iOS

### Have you already upgraded your packages?

Yes

### Dependency versions

<details open><summary>pubspec.lock</summary>

```lock
# Generated by pub
# See https://dart.dev/tools/pub/glossary#lockfile
packages:
  async:
    dependency: transitive
    description:
      name: async
      sha256: "947bfcf187f74dbc5e146c9eb9c0f10c9f8b30743e341481c1e2ed3ecc18c20c"
      url: "https://pub.dev"
    source: hosted
    version: "2.11.0"
  boolean_selector:
    dependency: transitive
    description:
      name: boolean_selector
      sha256: "6cfb5af12253eaf2b368f07bacc5a80d1301a071c73360d746b7f2e32d762c66"
      url: "https://pub.dev"
    source: hosted
    version: "2.1.1"
  characters:
    dependency: transitive
    description:
      name: characters
      sha256: "04a925763edad70e8443c99234dc3328f442e811f1d8fd1a72f1c8ad0f69a605"
      url: "https://pub.dev"
    source: hosted
    version: "1.3.0"
  clock:
    dependency: transitive
    description:
      name: clock
      sha256: cb6d7f03e1de671e34607e909a7213e31d7752be4fb66a86d29fe1eb14bfb5cf
      url: "https://pub.dev"
    source: hosted
    version: "1.1.1"
  collection:
    dependency: transitive
    description:
      name: collection
      sha256: ee67cb0715911d28db6bf4af1026078bd6f0128b07a5f66fb2ed94ec6783c09a
      url: "https://pub.dev"
    source: hosted
    version: "1.18.0"
  fake_async:
    dependency: transitive
    description:
      name: fake_async
      sha256: "511392330127add0b769b75a987850d136345d9227c6b94c96a04cf4a391bf78"
      url: "https://pub.dev"
    source: hosted
    version: "1.3.1"
  flutter:
    dependency: "direct main"
    description: flutter
    source: sdk
    version: "0.0.0"
  flutter_lints:
    dependency: "direct dev"
    description:
      name: flutter_lints
      sha256: e2a421b7e59244faef694ba7b30562e489c2b489866e505074eb005cd7060db7
      url: "https://pub.dev"
    source: hosted
    version: "3.0.1"
  flutter_test:
    dependency: "direct dev"
    description: flutter
    source: sdk
    version: "0.0.0"
  flutter_web_plugins:
    dependency: transitive
    description: flutter
    source: sdk
    version: "0.0.0"
  go_router:
    dependency: "direct main"
    description:
      name: go_router
      sha256: ca7e4a2249f96773152f1853fa25933ac752495cdd7fdf5dafb9691bd05830fd
      url: "https://pub.dev"
    source: hosted
    version: "13.0.0"
  lints:
    dependency: transitive
    description:
      name: lints
      sha256: cbf8d4b858bb0134ef3ef87841abdf8d63bfc255c266b7bf6b39daa1085c4290
      url: "https://pub.dev"
    source: hosted
    version: "3.0.0"
  logging:
    dependency: transitive
    description:
      name: logging
      sha256: "623a88c9594aa774443aa3eb2d41807a48486b5613e67599fb4c41c0ad47c340"
      url: "https://pub.dev"
    source: hosted
    version: "1.2.0"
  matcher:
    dependency: transitive
    description:
      name: matcher
      sha256: "1803e76e6653768d64ed8ff2e1e67bea3ad4b923eb5c56a295c3e634bad5960e"
      url: "https://pub.dev"
    source: hosted
    version: "0.12.16"
  material_color_utilities:
    dependency: transitive
    description:
      name: material_color_utilities
      sha256: "9528f2f296073ff54cb9fee677df673ace1218163c3bc7628093e7eed5203d41"
      url: "https://pub.dev"
    source: hosted
    version: "0.5.0"
  meta:
    dependency: transitive
    description:
      name: meta
      sha256: a6e590c838b18133bb482a2745ad77c5bb7715fb0451209e1a7567d416678b8e
      url: "https://pub.dev"
    source: hosted
    version: "1.10.0"
  path:
    dependency: transitive
    description:
      name: path
      sha256: "8829d8a55c13fc0e37127c29fedf290c102f4e40ae94ada574091fe0ff96c917"
      url: "https://pub.dev"
    source: hosted
    version: "1.8.3"
  sky_engine:
    dependency: transitive
    description: flutter
    source: sdk
    version: "0.0.99"
  source_span:
    dependency: transitive
    description:
      name: source_span
      sha256: "53e943d4206a5e30df338fd4c6e7a077e02254531b138a15aec3bd143c1a8b3c"
      url: "https://pub.dev"
    source: hosted
    version: "1.10.0"
  stack_trace:
    dependency: transitive
    description:
      name: stack_trace
      sha256: "73713990125a6d93122541237550ee3352a2d84baad52d375a4cad2eb9b7ce0b"
      url: "https://pub.dev"
    source: hosted
    version: "1.11.1"
  stream_channel:
    dependency: transitive
    description:
      name: stream_channel
      sha256: ba2aa5d8cc609d96bbb2899c28934f9e1af5cddbd60a827822ea467161eb54e7
      url: "https://pub.dev"
    source: hosted
    version: "2.1.2"
  string_scanner:
    dependency: transitive
    description:
      name: string_scanner
      sha256: "556692adab6cfa87322a115640c11f13cb77b3f076ddcc5d6ae3c20242bedcde"
      url: "https://pub.dev"
    source: hosted
    version: "1.2.0"
  term_glyph:
    dependency: transitive
    description:
      name: term_glyph
      sha256: a29248a84fbb7c79282b40b8c72a1209db169a2e0542bce341da992fe1bc7e84
      url: "https://pub.dev"
    source: hosted
    version: "1.2.1"
  test_api:
    dependency: transitive
    description:
      name: test_api
      sha256: "5c2f730018264d276c20e4f1503fd1308dfbbae39ec8ee63c5236311ac06954b"
      url: "https://pub.dev"
    source: hosted
    version: "0.6.1"
  vector_math:
    dependency: transitive
    description:
      name: vector_math
      sha256: "80b3257d1492ce4d091729e3a67a60407d227c27241d6927be0130c98e741803"
      url: "https://pub.dev"
    source: hosted
    version: "2.1.4"
  web:
    dependency: transitive
    description:
      name: web
      sha256: afe077240a270dcfd2aafe77602b4113645af95d0ad31128cc02bce5ac5d5152
      url: "https://pub.dev"
    source: hosted
    version: "0.3.0"
sdks:
  dart: ">=3.2.3 <4.0.0"
  flutter: ">=3.16.4"
```

</details>

### Steps to reproduce

1. Create some screens named Home, Post and Comments. (StatelessWidget or StatefulWidget does not matter.)
1.1 Create HomeScreen that should be initial route and show a list. When you tap on any item in the list, it should navigates you to the PostScreen with its index.
1.2 Create PostScreen that take an postId as a parameter and display in the AppBar. Additionally, there should be a button that navigates you to the CommentsScreen.
1.3 Create CommentsScreen that take an postId as a parameter and display in the AppBar.
2. Write print in each build method of screens. 
3. Compare logs between classic Navigator and GoRouter.

You can copy the code sample directly. 

### Expected results

HomeScreen.build
PostScreen.build with postId:70
CommentsScreen.build with postId:70

-> When I go to comments screen, random number generated in the post screen remains the same, because the post screen does not rebuild as expected.

### Actual results

HomeScreen.build
PostScreen.build with postId:70
CommentsScreen.build with postId:70
**PostScreen.build with postId:70**

-> When I go to comments screen, random number generated in the post screen **CHANGES**, because the post screen is rebuilt.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'dart:developer';
import 'dart:math' as math;

import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';

const bool useGoRouter = true;

void main() {
  runApp(const TestApp());
}

final class TestApp extends StatelessWidget {
  const TestApp({super.key});

  @override
  Widget build(BuildContext context) {
    return switch (useGoRouter) {
      // LOGS

      // HomeScreen.build
      // PostScreen.build with postId:70
      // CommentsScreen.build with postId:70
      // PostScreen.build with postId:70
      //      When I go to comments screen,
      //      random number generated in the post screen CHANGES,
      //      because the post screen is rebuilt.
      true => MaterialApp.router(
          routerConfig: GoRouter(
            initialLocation: '/',
            routes: <RouteBase>[
              GoRoute(
                path: '/',
                builder: (BuildContext context, GoRouterState state) {
                  return const HomeScreen();
                },
                routes: <RouteBase>[
                  GoRoute(
                    path: 'post/:postId',
                    builder: (BuildContext context, GoRouterState state) {
                      final String postId = state.pathParameters['postId'] as String;

                      return PostScreen(
                        key: ValueKey<String>('post-$postId'),
                        postId: postId,
                      );
                    },
                    routes: <RouteBase>[
                      GoRoute(
                        path: 'comments',
                        builder: (BuildContext context, GoRouterState state) {
                          final String postId = state.pathParameters['postId'] as String;

                          return CommentsScreen(
                            key: ValueKey<String>('comments-$postId'),
                            postId: postId,
                          );
                        },
                      ),
                    ],
                  ),
                ],
              ),
            ],
          ),
        ),

      // LOGS

      // HomeScreen.build
      // PostScreen.build with postId:70
      // CommentsScreen.build with postId:70
      //      When I go to comments screen,
      //      random number generated in the post screen remains the same,
      //      because the post screen does not rebuild as expected.
      false => MaterialApp(
          initialRoute: '/',
          routes: <String, WidgetBuilder>{
            '/': (BuildContext context) {
              return const HomeScreen();
            },
            '/post': (BuildContext context) {
              final String postId = ModalRoute.of(context)!.settings.arguments as String;

              return PostScreen(
                key: ValueKey<String>('post-$postId'),
                postId: postId,
              );
            },
            '/post/comments': (BuildContext context) {
              final String postId = ModalRoute.of(context)!.settings.arguments as String;

              return CommentsScreen(
                key: ValueKey<String>('comments-$postId'),
                postId: postId,
              );
            },
          },
        ),
    };
  }
}

final class HomeScreen extends StatelessWidget {
  const HomeScreen({super.key});

  @override
  Widget build(BuildContext context) {
    log('$runtimeType.build');

    return Scaffold(
      appBar: AppBar(
        title: const Text('Home'),
      ),
      body: ListView.builder(
        itemBuilder: (BuildContext context, int index) {
          return ListTile(
            leading: const CircleAvatar(),
            title: Text('Post - ID: $index'),
            trailing: const Icon(Icons.chevron_right_rounded),
            onTap: () {
              if (useGoRouter) {
                context.go('/post/$index');
              } else {
                Navigator.pushNamed(context, '/post', arguments: '$index');
              }
            },
          );
        },
      ),
    );
  }
}

final class PostScreen extends StatelessWidget {
  const PostScreen({
    super.key,
    required this.postId,
  });

  final String postId;

  @override
  Widget build(BuildContext context) {
    log('$runtimeType.build with postId:$postId');

    return Scaffold(
      appBar: AppBar(
        title: Text('Post - $postId'),
      ),
      body: Center(
        child: Text('Random Number: ${math.Random.secure().nextInt(100)}'),
      ),
      floatingActionButton: FloatingActionButton.extended(
        label: const Text('Show comments'),
        onPressed: () {
          if (useGoRouter) {
            context.go('/post/$postId/comments');
          } else {
            Navigator.pushNamed(context, '/post/comments', arguments: postId);
          }
        },
      ),
    );
  }
}

final class CommentsScreen extends StatelessWidget {
  const CommentsScreen({
    super.key,
    required this.postId,
  });

  final String postId;

  @override
  Widget build(BuildContext context) {
    log('$runtimeType.build with postId:$postId');

    return Scaffold(
      appBar: AppBar(
        title: Text('Comments of Post - $postId'),
      ),
    );
  }
}
```

</details>

### Screenshots or Videos

<details open>
<summary>Screenshots / Video demonstration</summary>

**Expected ->** https://github.com/flutter/flutter/assets/26097484/631ec363-0675-4c7f-b4b4-d50ef688a500

**Actual ->** https://github.com/flutter/flutter/assets/26097484/0b288c93-7d4c-4d1b-a4c3-38b895c5dedf

</details>

### Logs

<details open><summary>Logs</summary>

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.16.5, on macOS 14.2.1 23C71 darwin-arm64, locale en-US)
    • Flutter version 3.16.5 on channel stable at /Users/huseyinerenguler/FlutterSDK/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 78666c8dc5 (3 days ago), 2023-12-19 16:14:14 -0800
    • Engine revision 3f3e560236
    • Dart version 3.2.3
    • DevTools version 2.28.4

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/huseyinerenguler/Library/Android/sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C65
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] IntelliJ IDEA Community Edition (version 2022.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.85.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.78.0

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by huseyinerenguler** [comment] 2023-12-26 10:01
Any updates?

**Comment by danagbemava-nc** [comment] 2023-12-27 08:43
Hi @huseyinerenguler, see https://github.com/flutter/flutter/issues/132049#issuecomment-1673962209

Closing this since it seems to be working as intended. 

Thank you

**Closed by danagbemava-nc** 2023-12-27 08:43 UTC
Labels: in triage
