### ISSUE TITLE
[google_maps_flutter] Empty map when resuming from background on Android

### ISSUE THREAD

**Issue by angelorodem** [flutter/flutter#144893] opened 2024-03-10 03:00 UTC
### Steps to reproduce

Related closed issue: https://github.com/flutter/flutter/issues/40284

Open app with GoogleMap -> displays ok
Put app into background, without it being killed by the system.
Resume the app after a while

### Expected results

Map should not dissapear

### Actual results

Maps disappears, 
could not repro on some devices,
**Pixel works fine**, it does not work on **Samsung S22 Ultra (the device recorded) and Moto G6 Plus (with Lineage OS 21) had this issue**
an older Samsung S20 (or something) work fine too

Samsung S22 Ultra (Fails)
https://github.com/flutter/flutter/assets/11444489/c3d901dc-702e-40fe-b927-a7ab90f978f0

Moto G6 Plus (Fails)
https://github.com/flutter/flutter/assets/11444489/0d17426b-0a60-44c9-ad81-f5da4df8f102

Emulated Pixel (Works)
https://github.com/flutter/flutter/assets/11444489/61196b65-f08e-45d2-a2b8-0f1dfc143914

### Code sample

Code is basic Map code with custom styles, 
it uses the latest flutter map version 2.6

the workarounds like setting setMapStyles on the closed issue mentioned did not work to fix this issue.

Did not add all variables since its most standard code, this widget is a stateful widget that gets rendered from other stateful widget
```dart
   @override
  Widget build(BuildContext context) {
    const CameraPosition initialPosition = CameraPosition(
      target: LatLng(-27.302103, -50.424208),
      zoom: 8,
    );

    return Stack(
      children: [
        Container(
          key: gmapsKey,
        ),
        GoogleMap(
          initialCameraPosition: initialPosition,
          style: charge_map_style_light,
          onMapCreated: (GoogleMapController controller) {
            if (mapController.isCompleted) {
              mapController = Completer<GoogleMapController>();
            }
            mapController.complete(controller);
          },
          compassEnabled: true,
          myLocationEnabled: true,
          myLocationButtonEnabled: true,
          minMaxZoomPreference: MinMaxZoomPreference(7, 20),
          zoomControlsEnabled: false,
          indoorViewEnabled: false,
          rotateGesturesEnabled: false,
          trafficEnabled: false,
          mapToolbarEnabled: false,
        ),
      ],
    );
  }
```

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.19.3, on Microsoft Windows [Version 10.0.22621.3235], locale pt-BR)
    • Flutter version 3.19.3 on channel stable at X:\FlutterSDK\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ba39319843 (2 days ago), 2024-03-07 15:22:21 -0600
    • Engine revision 2e4ba9c6fb
    • Dart version 3.3.1
    • DevTools version 2.31.1

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at X:\AndroidSDK
    • Platform android-34, build-tools 34.0.0
    • ANDROID_SDK_ROOT = X:\AndroidSDK
    • Java binary at: X:\AndroidStudio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.8.4)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.8.34408.163
    • Windows 10 SDK version 10.0.22621.0

[✓] Android Studio (version 2023.1)
    • Android Studio at X:\AndroidStudio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)

[✓] VS Code, 64-bit edition (version 1.87.0)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.84.0

[✓] VS Code (version 1.84.0-insider)
    • VS Code at C:\Users\angel\AppData\Local\Programs\Microsoft VS Code Insiders
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (4 available)
    • SM S908E (mobile) • RQCT303TF2F • android-arm64  • Android 14 (API 34)
    • Windows (desktop) • windows     • windows-x64    • Microsoft Windows [Version 10.0.22621.3235]
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 122.0.6261.112
    • Edge (web)        • edge        • web-javascript • Microsoft Edge 122.0.2365.52

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by angelorodem** [comment] 2024-03-10 14:42
@johnmccutchan @darshankawar i wanted to ping you since you participated and closed the last thread related to this issue, do you have a similar device to test this case? i think that this issue is a not repro on Pixel, but other devices still can repro it.

**Comment by huycozy** [comment] 2024-03-11 10:24
I also can't reproduce this issue on my device `Realme 6, Android 11`. It could be a device-specific issue. Could you confirm this with [google_maps_flutter package's example](https://github.com/flutter/packages/tree/main/packages/google_maps_flutter/google_maps_flutter/example)? (to ensure that this is not caused by your native code change)


Also, could you try running this [Android native sample](https://github.com/googlemaps-samples/android-samples) on that device to see if the issue also appears?

**Comment by Andrushka1012** [comment] 2024-03-14 10:25
I have this issue on my google pixel 6 with android 14 and it's happens almost each time when i switch app to background -> launch another app -> switch another app to background -> come back to my app

**Comment by Andrushka1012** [comment] 2024-03-14 10:52
As a workaround I found way to refresh map each time when user comes back from background using key like:
`ValueKey<String> key = ValueKey<String>(DateTime.now().toString());`
and with WidgetsBindingObserver
```
@override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    super.didChangeAppLifecycleState(state);

    if (Platform.isAndroid && state == AppLifecycleState.resumed) {
      setState(() {
        mapController = null;
        key = ValueKey<String>(DateTime.now().toString());
      });
    }
  }
```

also to fix gap with user changing map position Im doing like:

```
initialCameraPosition: _cameraPosition ?? widget.initialCameraPosition,
      onCameraMove: (position) {
        _cameraPosition = position;
      },
```

I know it's not prefect but at least it fix issue

**Comment by whitesoil** [comment] 2024-03-14 17:17
I guess this issue is related to Android 14 and Samsung ONE UI 6.x.

I have Galaxy S20(Android 13, ONE UI 5.x) AND Galaxy S24(Android 14, ONE UI 6.x).
But I only have this issue on Galaxy S24.

So I'm tracking this issues.

#139630 and #139039

**Comment by whitesoil** [comment] 2024-03-14 17:28
I have same issue with @Andrushka1012 .

I have Galaxy S20(AOS 13) ans Galaxy S24(AOS 14).
But I only have this issue on Galaxy S24.

**Comment by huycozy** [comment] 2024-03-15 04:31
I checked this on `Pixel 7, Android 14` but the issue is not reproduced. Since the issue occurs on `google pixel 6` as @Andrushka1012  reported above, this doesn't look like a Samsung device-specific issue.

<details>
<summary>Demo</summary>

https://github.com/flutter/flutter/assets/104349824/fa134fc8-1e7f-4b2e-b642-cadbd211e352


</details>

Can anyone give a try with [google_maps_flutter package's example](https://github.com/flutter/packages/tree/main/packages/google_maps_flutter/google_maps_flutter/example)?

**Comment by Andrushka1012** [comment] 2024-03-15 05:55
I was't able to reproduce it on [google_maps_flutter package's example](https://github.com/flutter/packages/tree/main/packages/google_maps_flutter/google_maps_flutter/example) project. Also maybe it's related that in my project we still using previous map version:  google_maps_flutter: 2.5.3

**Comment by note11g** [comment] 2024-03-15 07:44
in [flutter_naver_map](https://github.com/note11g/flutter_naver_map) package, similar issue occured.
see this issue page: https://github.com/note11g/flutter_naver_map/issues/201

**Comment by angelorodem** [comment] 2024-03-17 16:57
@huycozy Found the root of the issue, partially lack of proper mvp in the https://pub.dev/packages/google_maps_flutter

after attempting to test on the example and not having success, i investigated why, i found that there is some important pieces of code that are **not mentioned** in the pub page (suggestion to add this there please), witch is related to initializing the render to the latest one.

the issue can be fixed by using this code in the main.dart

```dart
void main() {
  final GoogleMapsFlutterPlatform mapsImplementation =
      GoogleMapsFlutterPlatform.instance;
  if (mapsImplementation is GoogleMapsFlutterAndroid) {
    mapsImplementation.useAndroidViewSurface = true;
    initializeMapRenderer();
  }
  runApp(MyApp());
}

Future<AndroidMapRenderer?> initializeMapRenderer() async {
  if (_initializedRendererCompleter != null) {
    return _initializedRendererCompleter!.future;
  }

  final Completer<AndroidMapRenderer?> completer =
      Completer<AndroidMapRenderer?>();
  _initializedRendererCompleter = completer;

  WidgetsFlutterBinding.ensureInitialized();

  final GoogleMapsFlutterPlatform mapsImplementation =
      GoogleMapsFlutterPlatform.instance;
  if (mapsImplementation is GoogleMapsFlutterAndroid) {
    unawaited(mapsImplementation
        .initializeWithRenderer(AndroidMapRenderer.latest)
        .then((AndroidMapRenderer initializedRenderer) =>
            completer.complete(initializedRenderer)));
  } else {
    completer.complete(null);
  }

  return completer.future;
}
```
 
also adding these to the pubspec.yaml
```yaml
  google_maps_flutter: ^2.6.0
  google_maps_flutter_android: ^2.6.0
  google_maps_flutter_platform_interface: ^2.6.0
```

this solves the issue of the map vanishing on One UI and on LineageOS UI (and some others)

**Comment by angelorodem** [comment] 2024-03-17 16:58
@Andrushka1012 @whitesoil can you repro with this change?

**Comment by huycozy** [comment] 2024-03-18 05:02
@angelorodem It is documented at [Map renderer](https://pub.dev/packages/google_maps_flutter_android#map-renderer). Could you check if it's sufficient?

**Comment by whitesoil** [comment] 2024-03-18 11:47
@angelorodem Your solution didn't work for me TT
I guess this is Android 14 and Samsung ONE UI 6.x specific problem.

Because webview_flutter package has same symptom on Android 14 and Samsung ONE UI 6.x.

**Comment by angelorodem** [comment] 2024-03-18 12:06
@huycozy since this can be an easy pitfall it should be at least mentioned in the pub page, i would create a PR if i new where are these strings.
i suggest something like:
 _To avoid device specific issues, it is recommended to set the map renderer to the latest, as done in the main function of this example:_ [Example](https://pub.dev/packages/google_maps_flutter_android#map-renderer)

**Comment by huycozy** [comment] 2024-03-19 05:09
@angelorodem I think there is already a warning there about renderers:

```md
WARNING: AndroidMapRenderer.legacy is known to crash apps and is no longer supported by the Google Maps team and therefore cannot be supported by the Flutter team.
```

But since @whitesoil still encounters this, we need to make sure this is indeed renderer issue. @whitesoil Could you confirm you still have this issue with `maps` instead of `webview` plugin?

**Comment by note11g** [comment] 2024-03-19 07:20
@huycozy maybe PlatformView (TLHC) issue... (it's occured on flutter_naver_map too.)

**Comment by angelorodem** [comment] 2024-03-19 12:11
> @angelorodem I think there is already a warning there about renderers:
> 
> ```
> WARNING: AndroidMapRenderer.legacy is known to crash apps and is no longer supported by the Google Maps team and therefore cannot be supported by the Flutter team.
> ```
> 
> But since @whitesoil still encounters this, we need to make sure this is indeed renderer issue. @whitesoil Could you confirm you still have this issue with `maps` instead of `webview` plugin?

Hi @huycozy, i see this message and i think, what if i was in the other side of this message, what action can i take? i see this message and there is nothing that i can do without having to websearch for it, we can atleast there slightly improve the messaging to specify to the user some followup action like "_Please use the latest renderer_".

But i think this is still not good, this warning gets hidden in the IDE, a simple doc or pub change will help people avoid headaches in the future, agree?

**Comment by johnmccutchan** [comment] 2024-03-19 16:53
Closing this as a duplicate of https://github.com/flutter/flutter/issues/139039

**Closed by johnmccutchan** 2024-03-19 16:53 UTC
Labels: in triage
