### ISSUE TITLE
Print a warning to the JS console if CORS errors result in JS fallback

### ISSUE THREAD

**Issue by johnpryan** [flutter/flutter#146219] opened 2024-04-03 18:11 UTC
### Steps to reproduce

When I tried to run an app in WASM, I forgot to include the CORS flags in my web server. I tried running this:

```
flutter build web
dhttpd  --path=build/web
```

But I was supposed to run this:

```
flutter build web
dhttpd '--headers=Cross-Origin-Embedder-Policy=credentialless;Cross-Origin-Opener-Policy=same-origin' --path=build/web
```

### Expected results

A warning in the JS console that prints the correct CORS headers to use OR reminds me to go to flutter.dev/wasm 

### Actual results

The app used the JS fallback without any explanation

### Code sample

N/A

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel main, 3.22.0-3.0.pre.43, on macOS 14.4.1 23E224 darwin-arm64, locale en)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[!] Xcode - develop for iOS and macOS (Xcode 14.2)
    ✗ CocoaPods installed but not working.
        You appear to have CocoaPods installed but it is not working.
        This can happen if the version of Ruby that CocoaPods was installed with is different
        from the one being used to invoke it.
        This can usually be fixed by re-installing CocoaPods.
      To re-install see https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] Android Studio (version 2022.2)
[✓] Android Studio (version 2023.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2022.3.3)
[✓] VS Code (version 1.87.2)
```

</details>

**Comment by kevmoo** [comment] 2024-04-11 20:20
Duplicate of https://github.com/flutter/flutter/issues/142822

**Comment by yjbanov** [comment] 2024-04-11 20:21
I'm accepting this request. However, as a heads up, we may not be able to fix this. Being able to use Skwasm without the COEP/COOP headers is a valid use-case that we aim to support at some point, so it's not necessarily an error. Having said that if users consistently forget to use these headers, their apps will be slower than they could be. Perhaps we could do something to assist with this.

**Closed by kevmoo** 2024-04-11 20:20 UTC
Labels: platform-web, P2, e: wasm, e: web_skwasm, team-web, triaged-web
