### ISSUE TITLE
Custom Fonts are not loaded by the time that file scope variables are initialized

### ISSUE THREAD

**Issue by baylessj** [flutter/flutter#42277] opened 2019-10-08 23:21 UTC
## Steps to Reproduce

Load a custom font in `pubspec.yaml` and reference this font family in a text-style declared as a file scope variable.

```
import 'package:flutter/material.dart':

TextStyle test = TextStyle(
  fontFamily: 'Ubuntu',
  fontSize: 16,
);
```

Use this TextStyle in any other widget that is created at runtime, i.e. a child of the main Scaffold.

The displayed text will be of the platform's default font family (Roboto in the case of my Android).

If I declare the above example TextStyle in a run-time created Text Widget as opposed to at the scope of a file, then the custom font family is rendered properly.

**Target Platform:** Pop!_OS 19.04
**Target OS version/browser:** Android 8.0.0
**Devices:** Samsung Galaxy S7

`flutter doctor -v`:
```
[✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Linux, locale en_US.UTF-8)
    • Flutter version 1.9.1+hotfix.2 at /home/bayle/flutter
    • Framework revision 2d2a1ffec9 (5 weeks ago), 2019-09-06 18:39:49 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/bayle/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /home/bayle/Documents/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[!] Android Studio (version 3.5)
    • Android Studio at /home/bayle/Documents/android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.38.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.5.1

[✓] Connected device (1 available)
    • SM G930P • 6337a09d • android-arm64 • Android 8.0.0 (API 26)

```

**Comment by markusaksli-nc** [comment] 2020-09-24 09:21
@baylessj I can't reproduce this on the latest master `1.22.0-10.0.pre.340`.
<details>
 <summary>flutter doctor -v</summary>

```
[√] Flutter (Channel master, 1.22.0-10.0.pre.340, on Microsoft Windows [Version 10.0.19041.508], locale en-US)
    • Flutter version 1.22.0-10.0.pre.340 at C:\Development\flutter_master
    • Framework revision 1fef5912cf (65 minutes ago), 2020-09-23 21:37:08 -0700
    • Engine revision dd35b5b659
    • Dart version 2.10.0 (build 2.10.0-156.0.dev)


[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Users\marku\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.6.5)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.6.30320.27
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.0)
    • Android Studio at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (6 available)
    • SM G950F (mobile)           • ce12171c51cc001c03 • android-arm64  • Android 9 (API 28)
    • sdk gphone x86 arm (mobile) • emulator-5554      • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)           • windows            • windows-x64    • Microsoft Windows [Version 10.0.19041.508]
    • Web Server (web)            • web-server         • web-javascript • Flutter Tools
    • Chrome (web)                • chrome             • web-javascript • Google Chrome 85.0.4183.102
    • Edge (web)                  • edge               • web-javascript • Microsoft Edge 85.0.564.51

• No issues found!
```
</details>
<details>
 <summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

TextStyle test = TextStyle(
  fontFamily: 'Amatic SC',
  fontSize: 24,
);

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Sample',
      home: Scaffold(
        appBar: AppBar(
          title: Text(
            'File scope variable declaration',
            style: test,
          ),
        ),
        body: Center(
          child: Text(
            'Runtime declaration',
            style: TextStyle(
              fontFamily: 'Amatic SC',
              fontSize: 24,
            ),
          ),
        ),
      ),
    );
  }
}
```
</details>

<img src="https://user-images.githubusercontent.com/68219924/94126384-3522a580-fe60-11ea-97c2-d6b47bfcb5db.png" height="600" />

Are you still facing this issue on the latest stable or any other branch?

**Comment by TahaTesser** [comment] 2020-10-16 13:22
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

**Closed by TahaTesser** 2020-10-16 13:22 UTC
Labels: a: typography, framework, platform-linux
