### ISSUE TITLE
Flutter web production only, can't open my app while I'm hosting it on expressJS

### ISSUE THREAD

**Issue by nimr77** [flutter/flutter#107138] opened 2022-07-06 09:28 UTC
I'm using flutter 3.0.4, my flutter web application was working on the web while is being hosted on expressJS so I can use PM2 to manage my process on production yet during the last couple of days this error started showing up.

The error I'm getting 
```
Uncaught SyntaxError: Unexpected token '<'
flutter.js:1 Uncaught SyntaxError: Unexpected token '<'
(index):56 Uncaught ReferenceError: _flutter is not defined
    at (index):56:7
```
**My node App**
```
var express = require('express');
var path = require('path');
var cookieParser = require('cookie-parser');
var logger = require('morgan');
const cors = require('cors');
const request = require('request');

require('dotenv').config({path: __dirname + '/.env'})
var app = express();

app.use(cors())
app.use(logger('dev'));
app.use(express.json());
app.use(express.urlencoded({ extended: false }));
app.use(cookieParser());
app.use(express.static('../build/web/'));
// send the Flutter app

app.get('/flutter_service_worker.js', function(req, res) {
    res.sendFile(path.join(__dirname, '../build/web/flutter_service_worker.js'));
})
app.get('*', function(req, res) {
    res.sendFile(path.join(__dirname, '../build/web/'));
})

app.listen(process.env['PORT'], () => {
    console.log('Server is running on port ' + process.env['PORT']);
})


module.exports = app;
```

**flutter doctor**
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.4, on Pop!_OS 22.04 LTS
    5.17.15-76051715-generic, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version
    32.1.0-rc1)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[!] Android Studio (not installed)
[✓] VS Code (version 1.68.1)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

! Doctor found issues in 1 category.
```
**web/index.html**
```
<!DOCTYPE html>
<html>
<head>
  <!--
    If you are serving your web app in a path other than the root, change the
    href value below to reflect the base path you are serving from.

    The path provided below has to start and end with a slash "/" in order for
    it to work correctly.

    For more details:
    * https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base

    This is a placeholder for base href that will be replaced by the value of
    the `--base-href` argument provided to `flutter build`.
  -->
  <base href="/">

  <meta charset="UTF-8">
  <meta content="IE=Edge" http-equiv="X-UA-Compatible">
  <meta name="description" content="A new Flutter project.">

  <!-- iOS meta tags & icons -->
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  <meta name="apple-mobile-web-app-title" content="flutter_app">
  <link rel="apple-touch-icon" href="icons/Icon-192.png">

  <!-- Favicon -->
  <link rel="icon" type="image/png" href="favicon.png"/>

  <title>flutter_app</title>
  <link rel="manifest" href="manifest.json">

  <script>
    // The value below is injected by flutter build, do not touch.
    var serviceWorkerVersion = '817914306';
  </script>
  <!-- This script adds the flutter initialization JS code -->
  <script src="flutter.js" defer></script>
  <script src="splash/splash.js"></script>
  <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" name="viewport"/>
  <link rel="stylesheet" type="text/css" href="splash/style.css">
</head>
<style> flt-glass-pane { image-rendering: crisp-edges; } </style>
<body>
  <picture id="splash">
    <source srcset="splash/img/light-1x.png 1x, splash/img/light-2x.png 2x, splash/img/light-3x.png 3x, splash/img/light-4x.png 4x" media="(prefers-color-scheme: light)">
    <source srcset="splash/img/dark-1x.png 1x, splash/img/dark-2x.png 2x, splash/img/dark-3x.png 3x, splash/img/dark-4x.png 4x" media="(prefers-color-scheme: dark)">
    <img class="center" aria-hidden="true" src="splash/img/light-1x.png" alt=""/>
  </picture>
  <script>

    window.addEventListener('load', function(ev) {
      // Download main.dart.js
      _flutter.loader.loadEntrypoint({
        serviceWorker: {
          serviceWorkerVersion: serviceWorkerVersion,
        }
      }).then(function(engineInitializer) {
        return engineInitializer.initializeEngine();
      }).then(function(appRunner) {
        return appRunner.runApp();
      });
    });
  </script>
</body>
</html>
```

**Comment by exaby73** [comment] 2022-07-06 09:55
`<script src="splash/splash.js"></script>`
The above line is where you error originates. Your server is serving your `index.html` when the browser is requesting this JS file, which is why you're getting this error. Since this is not a bug with Flutter, I am closing this issue.

**Closed by exaby73** 2022-07-06 09:55 UTC
Labels: in triage

**Comment by nimr77** [comment] 2022-07-06 10:04
Alright, so the error was launching the node app like it's my bad I was using the command **node nodeApp/index.js**
when I launched from **node index.js**

**it works**
