### ISSUE TITLE
Support custom tile server and display overlay tiles in google_maps_flutter plugin

### ISSUE THREAD

**Issue by WoodenPC** [flutter/flutter#25161] opened 2018-12-10 16:39 UTC
Hi, can you pls add leaflet functionality to operate custom tile maps in google_maps_flutter?

**Comment by amirh** [comment] 2018-12-10 20:59
I'm not sure I understand what is being asked here...?
Supporting map providers other than Google Maps? (I don't think this is likely to be done by the "Google Maps" plugin).

**Comment by ffischer1984** [comment] 2018-12-10 22:44
I think he means a [tile map layer](https://developers.google.com/maps/documentation/android-sdk/tileoverlay)

**Comment by WoodenPC** [comment] 2018-12-11 03:05
@ffischer1984 is right. I have the url http://some_string/z/x/y.png. I need to display those tiles, there z x y are tile coordinates. Also it would be great to have the ability to set custom borders of map, project/unproject points, add markers with GestureDetector, search markers etc.

**Comment by kjeremy** [comment] 2018-12-11 12:55
TileMapLayers would be great.

**Comment by zon7** [comment] 2018-12-12 19:34
This request will need to create a new plugin not related to google_maps, as the plugin name states

**Comment by kjeremy** [comment] 2018-12-19 13:06
@zon7 The person really wants custom tile layer support.

**Comment by ffischer1984** [comment] 2018-12-19 15:57
@zon7 sorry i have disagree. The User want to use this Feature with Google maps and Google Maps already Support Tile Layers:
https://developers.google.com/maps/documentation/android-sdk/tileoverlay

**Comment by kjeremy** [comment] 2018-12-19 16:46
Right. Google Maps supports tile layers but the flutter plugin does not.

**Comment by ffischer1984** [comment] 2018-12-20 09:30
So this issue should have a feature request Label instead of waiting for customer Response Label shouldn't?

**Comment by zoechi** [comment] 2018-12-20 09:37
@ffischer1984 that's what it is since 9 days ;-)

**Comment by chappaai** [comment] 2018-12-29 20:59
Totally agree. Functionality to plug in custom tile server and display overlay tiles would be great. 
Google Maps view on Android supports it and it is used in most satellite earth-observation apps, weather forecasts etc.

**Comment by XinyueZ** [comment] 2019-06-15 00:24
Any progress?

**Comment by cyanglaz** [comment] 2021-01-08 17:32
Closing this issue because it is a duplicate of https://github.com/flutter/flutter/issues/25942

**Closed by cyanglaz** 2021-01-08 17:32 UTC
Labels: P4, p: first party, p: maps, plugin, severe: new feature
