### ISSUE TITLE
[Web] Right to left text field has incorrect caret position.

### ISSUE THREAD

**Issue by chunhtai** [flutter/flutter#98044] opened 2022-02-08 18:21 UTC
## Steps to Reproduce

```dart
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart';

void main() => runApp(const MaterialApp(
  debugShowCheckedModeBanner: false,
  home: Scaffold(
    body: TextField(
      textDirection: TextDirection.rtl,
    ),
  ),
));
```
![image](https://user-images.githubusercontent.com/47866232/153050437-fc6fec2a-9ad5-4f26-9742-9a53146a3b34.png)

This only happens on web. In Android it works correctly. This is likely a bug in TextPainter.getOffsetForCaret returns wrong offset in web implementation.

**Comment by chunhtai** [comment] 2022-02-08 18:23
cc @mdebbar

**Comment by chunhtai** [comment] 2022-02-17 19:11
how do i check which mode? I ran this using` fllutter run -d chrome`

**Comment by mdebbar** [comment] 2022-02-23 17:51
Duplicate of https://github.com/flutter/flutter/issues/78550

@chunhtai you can check the `<body>` tag and see what `flt-renderer` it shows.

**Closed by mdebbar** 2022-02-23 17:51 UTC
Labels: a: text input, engine, platform-web
