### ISSUE TITLE
UI gets darker and darker while using Hybrid composition + showModalBottomSheet on Android

### ISSUE THREAD

**Issue by neoyxm** [flutter/flutter#88497] opened 2021-08-19 04:50 UTC
Hi ,

These days,  our project is using showModalBottomSheet to pop-up a menu above several Hybrid composition Views.

When adding more Hybrid composition views to page, the UI will get more and more darker on poping up the menu.

Below is the sample codes to reproduce this issue:

**Dart side**:
main.dart:                        https://github.com/neoyxm/flutter-issue-Hybrid-showModalBottomSheet/blob/main/main.dart

**Native side to create the native view**:
MainActivity.java:            https://github.com/neoyxm/flutter-issue-Hybrid-showModalBottomSheet/blob/main/MainActivity.java
NativeView.java:              https://github.com/neoyxm/flutter-issue-Hybrid-showModalBottomSheet/blob/main/NativeView.java
NativeViewFactory.java: https://github.com/neoyxm/flutter-issue-Hybrid-showModalBottomSheet/blob/main/NativeViewFactory.java

## Steps to Reproduce

1. Run this sample ,and you will see 4 Hybrid composition Views, and a button named "showModalBottomSheet"
2. Clik the button,  and the UI will get very dark.
3. But if you mark other 3 views from the line 88 in mart.dart, and leave only one on the page.  The UI is ok while cliking the button. 

**Expected results:** [One Hybrid composition view ](https://github.com/neoyxm/flutter-issue-Hybrid-showModalBottomSheet/blob/main/1.png)

**Actual results:**  
[Two Hybrid composition views](https://github.com/neoyxm/flutter-issue-Hybrid-showModalBottomSheet/blob/main/2.png)
[Three Hybrid composition views](https://github.com/neoyxm/flutter-issue-Hybrid-showModalBottomSheet/blob/main/3.png)
[Four Hybrid composition views](https://github.com/neoyxm/flutter-issue-Hybrid-showModalBottomSheet/blob/main/4.png)

### BTW: We also checked the Virutal display mode, and no such problem.

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.5.1 20G80 darwin-x64, locale zh-Hans-CN)
    • Flutter version 2.2.3 at /opt/flutter
    • Framework revision f4abaa0735 (7 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/yangxm/Library/Android/sdk/
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/yangxm/Library/Android/sdk/
    • Java binary at: /Library/Java/JavaVirtualMachines/openjdk8/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_275-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] VS Code (version 1.59.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (3 available)
    • Pixel 3 (mobile) • 8ABX0PZMP • android-arm64  • Android 11 (API 30)
    • macOS (desktop)  • macos     • darwin-x64     • macOS 11.5.1 20G80 darwin-x64
    • Chrome (web)     • chrome    • web-javascript • Google Chrome 92.0.4515.159

```

</details>

**Comment by TahaTesser** [comment] 2021-08-19 15:42
Hi @neoyxm 
Thanks for filing the issue, I can reproduce it on the stable channel, however, this seems to be on later channels. I cannot reproduce on beta or master

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel beta, 2.5.0-5.1.pre, on Microsoft Windows [Version 10.0.22000.132], locale en-US)
    • Flutter version 2.5.0-5.1.pre at C:\Users\Taha\Code\flutter_beta
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 65cf7de5f4 (8 days ago), 2021-08-11 15:48:01 -0700
    • Engine revision fbeb7e22bd
    • Dart version 2.14.0 (build 2.14.0-377.4.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\Taha\Code\android-sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_SDK_ROOT = C:\Users\Taha\Code\android-sdk
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.0)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31605.320
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 2020.3)
    • Android Studio at C:\Users\Taha\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.59.0)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.25.0

[✓] Connected device (4 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)                  • windows       • windows-x64    • Microsoft Windows [Version 10.0.22000.132]
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 92.0.4515.159
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 92.0.902.73

• No issues found!
```

</details>


Can you please upgrade to the latest  `beta` and try again
Execute the following commands to upgrade
`flutter channel beta`
`flutter upgrade --force`
`flutter doctor -v`

Closing, as closed. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-08-19 15:42 UTC
Labels: in triage

**Comment by neoyxm** [comment] 2021-08-20 01:44
@TahaTesser 

I confirm this issue can't be reproduced on beta&master in my side.
Thanks for your verifying and replying.

Look forward the new release coming soon :)
