### ISSUE TITLE
[MacOS] Support verifyPhoneNumber for Desktop

### ISSUE THREAD

**Issue by abhinavsingh** [flutter/flutter#61345] opened 2020-07-13 10:12 UTC
#  Use case

Firebase phone auth works well for mobile and web, however runs into `MissingPluginException` on MacOS.

```
[ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: MissingPluginException(No implementation found for method verifyPhoneNumber on channel plugins.flutter.io/firebase_auth)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159:7)
<asynchronous suspension>
#1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:334:12)
#2      MethodChannelFirebaseAuth.verifyPhoneNumber (package:firebase_auth_platform_interface/src/method_channel_firebase_auth.dart:352:20)
#3      FirebaseAuth.verifyPhoneNumber (package:firebase_auth/src/firebase_auth.dart:266:42)
#4      Auth.verifyPhoneNumber (package:myapp/phone_auth/auth.dart:31:19)
#5      _PhoneAuthState.requestOtpWidget.<anonymous closure> (package:myapp/phone_auth/verify_phone.dart:128:34)
#6      _PhoneAuthState.requestOtpWidget.<anonymous closure> (package:myapp/phone_auth/verify_phone.dart:121:30)
#7      FormFieldState.save (package:flutter/src/widgets/form.dart:367:21)
#8      FormState.save (package:flutter/src/widgets/form.dart:183:13)
#9      _PhoneAuthState._onRequestOtpFormSubmit (package:myapp/phone_auth/verify_phone.dart:56:35)
#10     _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:992:19)
#11     _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:1098:38)
#12     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:184:24)
#13     TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:524:11)
#14     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:284:5)
#15     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:219:7)
#16     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:477:9)
#17     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:78:12)
#18     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:124:9)
#19     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
#20     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:122:18)
#21     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:108:7)
#22     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:220:19)
#23     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:200:22)
#24     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:158:7)
#25     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:104:7)
#26     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:88:7)
#27     _rootRunUnary (dart:async/zone.dart:1206:13)
#28     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#29     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
#30     _invoke1 (dart:ui/hooks.dart:267:10)
#31     _dispatchPointerDataPacket (dart:ui/hooks.dart:176:5)
```

## Proposal

Support `verifyPhoneNumber` for desktop.

**Comment by TahaTesser** [comment] 2020-07-13 13:47
Hi @abhinavsingh 
From what I can see, the issue is related to a FlutterFire plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by TahaTesser** 2020-07-13 13:47 UTC
