### ISSUE TITLE
Bottom App Bar + Sheet Causes Dimple

### ISSUE THREAD

**Issue by EnduringBeta** [flutter/flutter#104226] opened 2022-05-20 04:03 UTC
## Steps to Reproduce

Run [this DartPad](https://dartpad.dev/?id=6fcea5d6ace625a70d3fd26d7b420041) to see the behavior.

**Expected results:** 

I expected a perfect rectangle for the bottom app bar like it looked before I opened and closed the bottom sheet.

**Actual results:** 

I see a small dip where the floating action button location is (even with no FAB present).

Presumably this is carved out for a tiny FAB that doesn't exist?

<details>
<summary>Code sample</summary>

See DartPad above.

</details>

<details>
  <summary>Logs</summary>

```
PS C:\Users\ross\projects\dimple\bug> flutter run -v
[  +61 ms] executing: [C:\Users\ross\projects\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +447 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] ee4e09cce01d6f2d7f4baebd247fde02e5008851
[        ] executing: [C:\Users\ross\projects\flutter/] git tag --points-at ee4e09cce01d6f2d7f4baebd247fde02e5008851
[  +39 ms] Exit code 0 from: git tag --points-at ee4e09cce01d6f2d7f4baebd247fde02e5008851
[        ] 3.0.0
[   +6 ms] executing: [C:\Users\ross\projects\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +31 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\Users\ross\projects\flutter/] git ls-remote --get-url origin
[  +30 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +95 ms] executing: [C:\Users\ross\projects\flutter/] git rev-parse --abbrev-ref HEAD
[  +32 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +65 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +44 ms] executing: C:\Users\ross\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +72 ms] List of devices attached
           8C5X1JCQQ              device product:blueline model:Pixel_3 device:blueline transport_id:1
           emulator-5554          device product:sdk_gphone64_x86_64 model:sdk_gphone64_x86_64
           device:emulator64_x86_64_arm64 transport_id:4
[   +7 ms] C:\Users\ross\AppData\Local\Android\sdk\platform-tools\adb.exe -s 8C5X1JCQQ shell getprop
[ +136 ms] C:\Users\ross\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell getprop
[  +76 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +60 ms] Multiple devices found:
[   +1 ms] ro.hardware = blueline
[        ] ro.build.characteristics = nosdcard
[        ] ro.hardware = ranchu
[  +23 ms] Pixel 3 (mobile)             • 8C5X1JCQQ     • android-arm64  • Android 12 (API 31)
[        ] sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 12 (API 32) (emulator)
[        ] Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.22000.675]
[        ] Chrome (web)                 • chrome        • web-javascript • Google Chrome 101.0.4951.67
[        ] Edge (web)                   • edge          • web-javascript • Microsoft Edge 101.0.1210.47
[        ] [1]: Pixel 3 (8C5X1JCQQ)
[        ] [2]: sdk gphone64 x86 64 (emulator-5554)
[        ] [3]: Windows (windows)
[        ] [4]: Chrome (chrome)
[        ] [5]: Edge (edge)
[   +1 ms] Please choose one (To quit, press "q/Q")
[        ] :
[+4865 ms] 2
[  +58 ms] Skipping pub get: version match.
[  +52 ms] Generating
C:\Users\ross\projects\dimple\bug\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +51 ms] Using hardware rendering with device sdk gphone64 x86 64. If you notice graphics artifacts, consider enabling
software
           rendering with "--enable-software-rendering".
[  +20 ms] Initializing file store
[   +8 ms] Skipping target: gen_localizations
[   +7 ms] gen_dart_plugin_registrant: Starting due to {InvalidatedReasonKind.inputChanged: The following inputs have
updated contents: C:\Users\ross\projects\dimple\bug\.dart_tool\package_config_subset}
[  +19 ms] gen_dart_plugin_registrant: Complete
[   +1 ms] Skipping target: _composite
[   +1 ms] complete
[   +4 ms] Launching lib\main.dart on sdk gphone64 x86 64 in debug mode...
[   +4 ms] C:\Users\ross\projects\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev
C:\Users\ross\projects\flutter\bin\cache\dart-sdk\bin\snapshots\frontend_server.dart.snapshot --sdk-root
C:\Users\ross\projects\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --incremental --target=flutter
--debugger-module-names --experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true --output-dill
C:\Users\ross\AppData\Local\Temp\flutter_tools.b3dba9a2\flutter_tool.f69eef87\app.dill --packages
C:\Users\ross\projects\dimple\bug\.dart_tool\package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false
--enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill
build\c075001b96339384a97db4862b8ab8db.cache.dill.track.dill --enable-experiment=alternative-invalidation-strategy
[   +6 ms] executing: C:\Users\ross\AppData\Local\Android\sdk\build-tools\32.1.0-rc1\aapt dump xmltree
C:\Users\ross\projects\dimple\bug\build\app\outputs\flutter-apk\app.apk AndroidManifest.xml
[  +29 ms] Exit code 0 from: C:\Users\ross\AppData\Local\Android\sdk\build-tools\32.1.0-rc1\aapt dump xmltree
C:\Users\ross\projects\dimple\bug\build\app\outputs\flutter-apk\app.apk AndroidManifest.xml
[        ] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1f
               A: android:compileSdkVersionCodename(0x01010573)="12" (Raw: "12")
               A: package="com.example.bug" (Raw: "com.example.bug")
               A: platformBuildVersionCode=(type 0x10)0x1f
               A: platformBuildVersionName=(type 0x10)0xc
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1f
               E: uses-permission (line=15)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: application (line=17)
                 A: android:label(0x01010001)="bug" (Raw: "bug")
                 A: android:icon(0x01010002)=@0x7f080000
                 A: android:name(0x01010003)="android.app.Application" (Raw: "android.app.Application")
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A: android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComponentFactory" (Raw:
                 "androidx.core.app.CoreComponentFactory")
                 E: activity (line=23)
                   A: android:theme(0x01010000)=@0x7f0a0000
                   A: android:name(0x01010003)="com.example.bug.MainActivity" (Raw: "com.example.bug.MainActivity")
                   A: android:exported(0x01010010)=(type 0x12)0xffffffff
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x40003fb4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: meta-data (line=38)
                     A: android:name(0x01010003)="io.flutter.embedding.android.NormalTheme" (Raw:
                     "io.flutter.embedding.android.NormalTheme")
                     A: android:resource(0x01010025)=@0x7f0a0001
                   E: intent-filter (line=42)
                     E: action (line=43)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
                     E: category (line=45)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw:
                       "android.intent.category.LAUNCHER")
                 E: meta-data (line=52)
                   A: android:name(0x01010003)="flutterEmbedding" (Raw: "flutterEmbedding")
                   A: android:value(0x01010024)=(type 0x10)0x2
                 E: uses-library (line=56)
                   A: android:name(0x01010003)="androidx.window.extensions" (Raw: "androidx.window.extensions")
                   A: android:required(0x0101028e)=(type 0x12)0x0
                 E: uses-library (line=59)
                   A: android:name(0x01010003)="androidx.window.sidecar" (Raw: "androidx.window.sidecar")
                   A: android:required(0x0101028e)=(type 0x12)0x0
[   +6 ms] executing: C:\Users\ross\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell -x logcat -v
time -t 1
[   +6 ms] <- compile package:bug/main.dart
[  +85 ms] --------- beginning of system
           05-19 23:56:52.975 E/ActivityThread( 5244): Failed to find provider info for
           com.google.android.apps.wellbeing.api
[   +6 ms] executing: C:\Users\ross\AppData\Local\Android\sdk\platform-tools\adb.exe version
[  +57 ms] Android Debug Bridge version 1.0.41
           Version 33.0.1-8253317
           Installed as C:\Users\ross\AppData\Local\Android\sdk\platform-tools\adb.exe
[   +1 ms] executing: C:\Users\ross\AppData\Local\Android\sdk\platform-tools\adb.exe start-server
[  +61 ms] Building APK
[  +12 ms] Running Gradle task 'assembleDebug'...
[   +2 ms] Using gradle from C:\Users\ross\projects\dimple\bug\android\gradlew.bat.
[   +5 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java -version
[ +139 ms] Exit code 0 from: C:\Program Files\Android\Android Studio\jre\bin\java -version
[        ] openjdk version "11.0.11" 2021-04-20
           OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
           OpenJDK 64-Bit Server VM (build 11.0.11+9-b60-7590822, mixed mode)
[   +1 ms] executing: [C:\Users\ross\projects\dimple\bug\android/] C:\Users\ross\projects\dimple\bug\android\gradlew.bat
-Pverbose=true -Ptarget-platform=android-x64 -Ptarget=C:\Users\ross\projects\dimple\bug\lib\main.dart
-Pbase-application-name=android.app.Application -Pdart-defines=RkxVVFRFUl9XRUJfQVVUT19ERVRFQ1Q9dHJ1ZQ==
-Pdart-obfuscation=false -Ptrack-widget-creation=true -Ptree-shake-icons=false -Pfilesystem-scheme=org-dartlang-root
assembleDebug
[+2946 ms] > Task :app:preBuild UP-TO-DATE
[        ] > Task :app:preDebugBuild UP-TO-DATE
[        ] > Task :app:mergeDebugNativeDebugMetadata NO-SOURCE
[+2086 ms] > Task :app:compileFlutterBuildDebug
[        ] > Task :app:packLibsflutterBuildDebug UP-TO-DATE
[        ] > Task :app:compileDebugAidl NO-SOURCE
[        ] > Task :app:compileDebugRenderscript NO-SOURCE
[        ] > Task :app:generateDebugBuildConfig UP-TO-DATE
[        ] > Task :app:checkDebugAarMetadata UP-TO-DATE
[        ] > Task :app:cleanMergeDebugAssets
[        ] > Task :app:mergeDebugShaders UP-TO-DATE
[        ] > Task :app:compileDebugShaders NO-SOURCE
[        ] > Task :app:generateDebugAssets UP-TO-DATE
[        ] > Task :app:mergeDebugAssets
[ +299 ms] > Task :app:copyFlutterAssetsDebug
[        ] > Task :app:generateDebugResValues UP-TO-DATE
[        ] > Task :app:generateDebugResources UP-TO-DATE
[        ] > Task :app:mergeDebugResources UP-TO-DATE
[        ] > Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
[        ] > Task :app:extractDeepLinksDebug UP-TO-DATE
[        ] > Task :app:processDebugMainManifest UP-TO-DATE
[        ] > Task :app:processDebugManifest UP-TO-DATE
[        ] > Task :app:processDebugManifestForPackage UP-TO-DATE
[        ] > Task :app:processDebugResources UP-TO-DATE
[        ] > Task :app:compileDebugKotlin UP-TO-DATE
[        ] > Task :app:javaPreCompileDebug UP-TO-DATE
[        ] > Task :app:compileDebugJavaWithJavac UP-TO-DATE
[  +87 ms] > Task :app:processDebugJavaRes NO-SOURCE
[        ] > Task :app:mergeDebugJavaResource UP-TO-DATE
[        ] > Task :app:checkDebugDuplicateClasses UP-TO-DATE
[        ] > Task :app:dexBuilderDebug UP-TO-DATE
[        ] > Task :app:desugarDebugFileDependencies UP-TO-DATE
[        ] > Task :app:mergeExtDexDebug UP-TO-DATE
[        ] > Task :app:mergeDexDebug UP-TO-DATE
[        ] > Task :app:mergeDebugJniLibFolders UP-TO-DATE
[        ] > Task :app:mergeDebugNativeLibs UP-TO-DATE
[        ] > Task :app:stripDebugDebugSymbols UP-TO-DATE
[        ] > Task :app:validateSigningDebug UP-TO-DATE
[        ] > Task :app:writeDebugAppMetadata UP-TO-DATE
[        ] > Task :app:writeDebugSigningConfigVersions UP-TO-DATE
[ +613 ms] > Task :app:compressDebugAssets
[        ] Execution optimizations have been disabled for task ':app:compressDebugAssets' to ensure correctness due to
the following reasons:
[        ]   - Gradle detected a problem with the following location:
'C:\Users\ross\projects\dimple\bug\build\app\intermediates\assets\debug\mergeDebugAssets'. Reason: Task
':app:compressDebugAssets' uses this output of task ':app:copyFlutterAssetsDebug' without declaring an explicit or
implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed.
Please refer to https://docs.gradle.org/7.4/userguide/validation_problems.html#implicit_dependency for more details
about this problem.
[        ] > Task :app:packageDebug UP-TO-DATE
[        ] > Task :app:createDebugApkListingFileRedirect UP-TO-DATE
[        ] > Task :app:assembleDebug
[        ] Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
[        ] You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from
your own scripts or plugins.
[        ] See https://docs.gradle.org/7.4/userguide/command_line_interface.html#sec:command_line_warnings
[        ] Execution optimizations have been disabled for 1 invalid unit(s) of work during this build to ensure
correctness.
[        ] Please consult deprecation warnings for more details.
[        ] BUILD SUCCESSFUL in 5s
[        ] 35 actionable tasks: 6 executed, 29 up-to-date
[ +644 ms] Running Gradle task 'assembleDebug'... (completed in 6.8s)
[ +174 ms] calculateSha: LocalDirectory: 'C:\Users\ross\projects\dimple\bug\build\app\outputs\flutter-apk'/app.apk
[ +354 ms] ✓  Built build\app\outputs\flutter-apk\app-debug.apk.
[   +2 ms] executing: C:\Users\ross\AppData\Local\Android\sdk\build-tools\32.1.0-rc1\aapt dump xmltree
C:\Users\ross\projects\dimple\bug\build\app\outputs\flutter-apk\app.apk AndroidManifest.xml
[ +186 ms] Exit code 0 from: C:\Users\ross\AppData\Local\Android\sdk\build-tools\32.1.0-rc1\aapt dump xmltree
C:\Users\ross\projects\dimple\bug\build\app\outputs\flutter-apk\app.apk AndroidManifest.xml
[        ] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1f
               A: android:compileSdkVersionCodename(0x01010573)="12" (Raw: "12")
               A: package="com.example.bug" (Raw: "com.example.bug")
               A: platformBuildVersionCode=(type 0x10)0x1f
               A: platformBuildVersionName=(type 0x10)0xc
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1f
               E: uses-permission (line=15)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: application (line=17)
                 A: android:label(0x01010001)="bug" (Raw: "bug")
                 A: android:icon(0x01010002)=@0x7f080000
                 A: android:name(0x01010003)="android.app.Application" (Raw: "android.app.Application")
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A: android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComponentFactory" (Raw:
                 "androidx.core.app.CoreComponentFactory")
                 E: activity (line=23)
                   A: android:theme(0x01010000)=@0x7f0a0000
                   A: android:name(0x01010003)="com.example.bug.MainActivity" (Raw: "com.example.bug.MainActivity")
                   A: android:exported(0x01010010)=(type 0x12)0xffffffff
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x40003fb4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: meta-data (line=38)
                     A: android:name(0x01010003)="io.flutter.embedding.android.NormalTheme" (Raw:
                     "io.flutter.embedding.android.NormalTheme")
                     A: android:resource(0x01010025)=@0x7f0a0001
                   E: intent-filter (line=42)
                     E: action (line=43)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
                     E: category (line=45)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw:
                       "android.intent.category.LAUNCHER")
                 E: meta-data (line=52)
                   A: android:name(0x01010003)="flutterEmbedding" (Raw: "flutterEmbedding")
                   A: android:value(0x01010024)=(type 0x10)0x2
                 E: uses-library (line=56)
                   A: android:name(0x01010003)="androidx.window.extensions" (Raw: "androidx.window.extensions")
                   A: android:required(0x0101028e)=(type 0x12)0x0
                 E: uses-library (line=59)
                   A: android:name(0x01010003)="androidx.window.sidecar" (Raw: "androidx.window.sidecar")
                   A: android:required(0x0101028e)=(type 0x12)0x0
[   +1 ms] Stopping app 'app.apk' on sdk gphone64 x86 64.
[        ] executing: C:\Users\ross\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell am
force-stop com.example.bug
[+2639 ms] executing: C:\Users\ross\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell pm list
packages com.example.bug
[ +367 ms] package:com.example.bug
[   +1 ms] executing: C:\Users\ross\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell cat
/data/local/tmp/sky.com.example.bug.sha1
[  +66 ms] 48922c191c03c4d66940dee356a4dccb5910b391
[        ] Latest build already installed.
[        ] executing: C:\Users\ross\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell -x logcat -v
time -t 1
[ +636 ms] --------- beginning of main
                    05-19 23:57:04.572 E/BpTransactionCompletedListener(  413): Failed to transact (-32)
[   +4 ms] executing: C:\Users\ross\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell am start -a
android.intent.action.RUN -f 0x20000000 --ez enable-dart-profiling true --ez enable-checked-mode true --ez
verify-entry-points true com.example.bug/com.example.bug.MainActivity
[  +48 ms] Starting: Intent { act=android.intent.action.RUN flg=0x20000000 cmp=com.example.bug/.MainActivity (has
extras) }
[        ] Waiting for observatory port to be available...
[+1281 ms] Observatory URL on device: http://127.0.0.1:37995/DqbbwlQ8T7U=/
[   +1 ms] executing: C:\Users\ross\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 forward tcp:0
tcp:37995
[  +63 ms] 60788
[        ] Forwarded host port 60788 to device port 37995 for Observatory
[   +4 ms] Caching compiled dill
[ +369 ms] Connecting to service protocol: http://127.0.0.1:60788/DqbbwlQ8T7U=/
[ +241 ms] Launching a Dart Developer Service (DDS) instance at http://127.0.0.1:0, connecting to VM service at
http://127.0.0.1:60788/DqbbwlQ8T7U=/.
[ +115 ms] DDS is listening at http://127.0.0.1:60794/Ni36gRXxnTA=/.
[  +48 ms] Successfully connected to service protocol: http://127.0.0.1:60788/DqbbwlQ8T7U=/
[  +42 ms] DevFS: Creating new filesystem on the device (null)
[  +25 ms] DevFS: Created new filesystem on the device (file:///data/user/0/com.example.bug/code_cache/bugEUBDTO/bug/)
[   +2 ms] Updating assets
[  +58 ms] Syncing files to device sdk gphone64 x86 64...
[   +1 ms] <- reset
[        ] Compiling dart to kernel with 0 updated files
[   +1 ms] Processing bundle.
[   +1 ms] <- recompile package:bug/main.dart c8153162-eec2-4ec7-b425-6eaa3e0dde44
[        ] <- c8153162-eec2-4ec7-b425-6eaa3e0dde44
[   +1 ms] Bundle processing done.
[  +68 ms] Updating files.
[        ] DevFS: Sync finished
[   +1 ms] Syncing files to device sdk gphone64 x86 64... (completed in 74ms)
[        ] Synced 0.0MB.
[   +1 ms] <- accept
[   +4 ms] Connected to _flutterView/0x75275c3f44b0.
[   +2 ms] Flutter run key commands.
[   +1 ms] r Hot reload. 🔥🔥🔥
[   +1 ms] R Hot restart.
[        ] h List all available interactive commands.
[        ] d Detach (terminate "flutter run" but leave application running).
[        ] c Clear the screen
[        ] q Quit (terminate the application on the device).
[        ] 💪 Running with sound null safety 💪
[        ] An Observatory debugger and profiler on sdk gphone64 x86 64 is available at:
http://127.0.0.1:60794/Ni36gRXxnTA=/
[ +236 ms] The Flutter DevTools debugger and profiler on sdk gphone64 x86 64 is available at:
                    http://127.0.0.1:9103?uri=http://127.0.0.1:60794/Ni36gRXxnTA=/
[+3555 ms] D/EGL_emulation(13472): app_time_stats: avg=214.87ms min=12.08ms max=2467.55ms count=17
```

```
Analyzing bug...
No issues found! (ran in 2.5s)
```

```
[√] Flutter (Channel stable, 3.0.0, on Microsoft Windows [Version 10.0.22000.675], locale en-US)
    • Flutter version 3.0.0 at C:\Users\ross\projects\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ee4e09cce0 (10 days ago), 2022-05-09 16:45:18 -0700
    • Engine revision d1b9a6938a
    • Dart version 2.17.0
    • DevTools version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at C:\Users\ross\AppData\Local\Android\sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] VS Code (version 1.66.2)
    • VS Code at C:\Users\ross\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (5 available)
    • Pixel 3 (mobile)             • 8C5X1JCQQ     • android-arm64  • Android 12 (API 31)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 12 (API 32) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.22000.675]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 101.0.4951.67
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 101.0.1210.47

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

</details>

![Screenshot 2022-05-19 234119](https://user-images.githubusercontent.com/4104925/169447065-0372221a-8b2f-4ceb-9c6a-538e42fab16c.png)

**Comment by ankushdhiman2021** [comment] 2022-05-20 06:37
@EnduringBeta Hi, I just checked the link you provided. It's working as expected if you remove this line  **shape: const CircularNotchedRectangle(),** . Also I think it should appear curved out as well before opening bottom sheet since you have added  **shape: const CircularNotchedRectangle()**

**Comment by darshankawar** [comment] 2022-05-20 08:27
@EnduringBeta 
That's the expected behavior since you have used `shape: CircularNotchedRectangle(),` and hence it's showing you the circular notch. If you comment that line of code, you'll get expected behavior as you mentioned.

Closing as this isn't an issue.

**Comment by TahaTesser** [comment] 2022-05-20 08:38
The curve is missing at first then appears only when invoking the sheet, Investigating the issue.

**Comment by TahaTesser** [comment] 2022-05-20 09:51
Here is a simplified code sample, still investigating the cause (running into another issue on master)

<details> 
<summary>minimal code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Example(),
    );
  }
}

class Example extends StatefulWidget {
  const Example({super.key});

  @override
  State<Example> createState() => _ExampleState();
}

class _ExampleState extends State<Example> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Material App Bar'),
      ),
      floatingActionButtonLocation: FloatingActionButtonLocation.centerDocked,
      bottomNavigationBar: BottomAppBar(
        shape: const CircularNotchedRectangle(),
        color: Colors.blue,
        child: Row(
          children: <Widget>[
            Builder(
              builder: (BuildContext context) {
                return IconButton(
                  onPressed: () {
                    Scaffold.of(context).showBottomSheet(
                      (BuildContext context) => const SizedBox(
                        height: 100.0,
                        child: Center(
                          child: Text(
                            'When this closes, it causes a dimple without FAB',
                            textAlign: TextAlign.center,
                          ),
                        ),
                      ),
                      backgroundColor: Colors.blue[100],
                    );
                  },
                  icon: const Icon(
                    Icons.menu,
                    color: Colors.white,
                  ),
                );
              }
            )
          ],
        ),
      ),
    );
  }
}

``` 
	
</details>

**Comment by TahaTesser** [comment] 2022-05-20 12:37
Identified the cause 
`geometryListenable = Scaffold.geometryOf(context);` returns floatingActionButtonArea `null` at first and  then return floatingActionButtonArea  non-null value.
`BottomAppBar` is rendered and not clipped by the time we receive non-null value from `geometryListenable = Scaffold.geometryOf(context);`. 

`BottomAppBar` rebuilds when opening/closing sheet and the clip is applied since `floatingActionButtonArea ` is no longer null. 


https://github.com/flutter/flutter/blob/afdfc56bbb635350a18b90e5487c2dcc852f42be/packages/flutter/lib/src/material/bottom_app_bar.dart#L193

**Comment by TahaTesser** [comment] 2022-05-20 13:27
> So the intended behavior is the tiny circular notch present all the time (assuming no FAB is present)? Personally I'd prefer no notch.

That's a good point, I just realized seeing curve without fab doesn't make sense.  (regardless if shape is provided or not)

**Comment by EnduringBeta** [comment] 2022-05-20 16:06
I went through 3 scenarios in my project and recorded video so it's easy to understand my situation:

* First example:
  1. Open page with no notched FAB
  2. Toggle FAB to appear (smooth animation:+1:)
  3. Toggle bottom sheet (code toggles the FAB to disappear, smooth:+1:)
  4. Close bottom sheet (FAB reappears smoothly:+1:)
* Second example:
  1. Open page with no notched FAB
  2. Open and close bottom sheet (dimple/dip appears👎)
  3. Toggle FAB to appear (animation not smooth:-1:)
* Third example:
  1. Open page with no notched FAB
  2. Toggle bottom sheet
  3. Toggle FAB to appear when bottom sheet closes
  4. Close bottom sheet (FAB reappears smoothly:+1:)

To me, the second example gives 2 reasons for a change: the dip doesn't need to be there, and the animation when the FAB appears isn't smooth.

https://user-images.githubusercontent.com/4104925/169566704-6fb194fc-897d-4a46-9b74-00439dc855c1.mp4

**Closed** 2022-05-24 10:13 UTC
Labels: framework, f: material design, has reproducible steps, found in release: 3.0, found in release: 3.1
