### ISSUE TITLE
IOS only - Underlining webview is intercepting pointer events of widgets above it in Stack

### ISSUE THREAD

**Issue by kobi666** [flutter/flutter#144717] opened 2024-03-06 21:11 UTC
### Steps to reproduce

1. Create a scafflold with its body being a webView (either using flutter webview or using InAppWebView) and navigate to a site with very critical pointer events, like a map web application (i am attaching an HTML you can use locally to easily reproduce using a floating action button)
2. add a floating action button
3. press on the button and see how it may change the interaction on the map

it is important to note that the issue I am experiencing also has to do with the web app |  safari "holding" onto the pointer event,
but the bug is that the pointer event should not have propagated to the webview in the first place

### Expected results

the webview which is lower in the stack (behind the floating action button) should not have received the pointer event at all.

### Actual results

the webview is receiving the pointer event coming from the tap on the floating button

### Code sample

<details open><summary>Code sample</summary>

```dart
// this also contains the workaround of using an underlining NoPointer widget in the stack to prevent the pointer from //propogating the pointer event

import 'package:flutter/foundation.dart';
import 'package:flutter/gestures.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_inappwebview/flutter_inappwebview.dart';
import 'package:pointer_interceptor/pointer_interceptor.dart';

import 'package:flutter/foundation.dart';
import 'package:flutter/gestures.dart';

class TestingPageWebView extends StatefulWidget {
  @override
  State<TestingPageWebView> createState() => _TestingPageWebViewState();
}

class _TestingPageWebViewState extends State<TestingPageWebView> {


  InAppWebViewSettings settings = InAppWebViewSettings(
    
    javaScriptEnabled: true,
    
    
    isInspectable: true, useHybridComposition: true);
  InAppWebViewController? controller;
  String htmlString = '';

  @override
  void initState() {
    // TODO: implement initState
    super.initState();
   
  }

  Future Init() async {
     htmlString = await rootBundle.loadString('assets/watch-for-changes.html');
  }


  bool testPointer = true;
  
  @override
  Widget build(BuildContext context) {
    // TODO: implement build
    return FutureBuilder(
      future: Init(),
      builder: (context, snapshot) {
        if (snapshot.connectionState == ConnectionState.done) {
        return Scaffold(
          appBar: AppBar( title: Text("Testing")),
          floatingActionButton: Stack(
            children: [
              Container(
                color: Color.fromARGB(80, 181, 7, 255),
                height: 60, width: 60,
                child: testPointer ? IgnorePointer() : Container()),
              FloatingActionButton(
                child: Container(height: 60, width: 60, color: Colors.green, child: Center(child: Icon(Icons.radio_button_checked),),),
                onPressed: () {
                print("button tapped");
              }),
          ]),
          
          // Stack(
          //   children: [IgnorePointer(
          //     child: Container(height: 60, width: 60, color: Colors.amber,),
          //   ),
          //   // FloatingActionButton(onPressed: () {
          //   //   print("Pressed");
          //   // })
          //   ],
          // ),
          body: Container(color: Colors.amber,
          child: InAppWebView(
            
            gestureRecognizers: [new Factory<OneSequenceGestureRecognizer>(
                    () => new EagerGestureRecognizer(),
                  ),].toSet(),
            //initialUrlRequest: URLRequest(url: WebUri("https://developers.arcgis.com/javascript/latest/sample-code/watch-for-changes/live/")),
             initialData: InAppWebViewInitialData(data: htmlString),
            onWebViewCreated: (c) {
              controller = c;
              
            },
            initialSettings: settings,
          ),
          ),
        );
      }
      else {
        return Container(color: Colors.blueGrey);
      }
      }
      
    );
  }
}
```
</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

nothing to log i'm afraid

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
✓] Flutter (Channel stable, 3.16.5, on macOS 14.2 23C64 darwin-arm64 (Rosetta), locale en-IL)
    • Flutter version 3.16.5 on channel stable at /Applications/frameworks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 78666c8dc5 (3 months ago), 2023-12-19 16:14:14 -0800
    • Engine revision 3f3e560236
    • Dart version 3.2.3
    • DevTools version 2.28.4

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.15.2

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] VS Code (version 1.86.2)
    • VS Code at /Users/kobihanma/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.84.0

[✓] Connected device (1 available)
    • macOS (desktop) • macos • darwin-arm64 • macOS 14.2 23C64 darwin-arm64 (Rosetta)

[✓] Network resources
    • All expected network resources are available.
```
</details>

**Comment by kobi666** [comment] 2024-03-06 21:14
HTML for the local site to reproduce the issue (save as HTML):

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="initial-scale=1,maximum-scale=1,user-scalable=no" />
    <title>Watch for changes | Sample | ArcGIS Maps SDK for JavaScript 4.28</title>

    <link rel="stylesheet" href="https://js.arcgis.com/4.28/esri/themes/light/main.css" />
    <script src="https://js.arcgis.com/4.28/"></script>

    <style>
      html,
      body,
      #viewDiv {
        padding: 0;
        margin: 0;
        height: 100%;
        overflow: hidden;
      }

      #outputMessages {
        position: absolute;
        z-index: 70;
        top: 0px;
        right: 0;
        bottom: 0;
        box-sizing: border-box;
        padding: 20px;
        height: 100%;
        width: 350px;
        background: rgba(0, 0, 0, 0.7);
        color: white;
        font-size: 14px;
        line-height: 30px;
        overflow: auto;
      }

      #outputMessages span {
        color: #f7be81;
        font-weight: bold;
      }
    </style>

    <script>
      require(["esri/views/MapView", "esri/WebMap", "esri/core/reactiveUtils"], (MapView, WebMap, reactiveUtils) => {
        // Load a webmap from ArcGIS Online
        const webmap = new WebMap({
          portalItem: {
            // autocasts as new PortalItem()
            id: "974c6641665a42bf8a57da08e607bb6f"
          }
        });

        // Create a view and set view's map to the webmap
        const view = new MapView({
          container: "viewDiv",
          map: webmap,
          padding: {
            right: 350
          }
        });

        const outputMessages = document.getElementById("outputMessages");

        //*******************************************************************
        // Working with promises
        // 1. WebMap
        // 2. View
        //*******************************************************************
        // Call then methods on WebMap and View to check if these classes are
        // properly loaded or fail.
        webmap
          .when(() => {
            // This function will execute once the promise is resolved
            displayMessage(`<span> webmap.when </span> - web map loaded successfully`);
          })
          .catch(errorHandler);

        view
          .when(() => {
            // This function will execute once the promise is resolved
            displayMessage(`<br> <span> view.when </span> --- view loaded successfully`);
          })
          .catch(errorHandler);

        //*******************************************************************
        // Listening to events
        // 1. Layer change event on layers collection
        // 2. layerview-create event on the view
        // 3. click event on the view.
        //*******************************************************************

        // Listen to layer change events on all of map's layers
        // Only listening to layer added event in this case.
        view.map.allLayers.on("change", (event) => {
          // change event fires after an item has been added, moved or removed from the collection.
          // event.moved - an array of moved layers
          // event.removed - an array of removed layers
          // event.added returns an array of added layers
          if (event.added.length > 0) {
            event.added.forEach((layer) => {
              const info = `<br> <span> layer added: </span> ${layer.title}`;
              displayMessage(info);
            });
          }
        });

        // Listen to layerview create event for the layers
        view.on("layerview-create", (event) => {
          const info = `<br> <span> layerview-create </span> - ${event.layer.title} is ${event.layer.loadStatus}`;
          displayMessage(info);
        });

        // Listen the view's click event.
        view.on("click", (event) => {
          const info = `<br> <span> view click event: </span>
            x: ${event.mapPoint.x.toFixed(2)}
            y: ${event.mapPoint.y.toFixed(2)}`;
          displayMessage(info);
        });

        //*******************************************************************
        // Watching properties for changes
        // 1. Watch view.stationary property
        // 2. Watch visible property of popup
        //*******************************************************************
        // Watch view's stationary property for becoming true.
        reactiveUtils.when(
          () => view.stationary === true,
          () => {
            // Get the new center of the view only when view is stationary.
            if (view.center) {
              const info = `<br> <span> the view center changed. </span>
              x: ${view.center.x.toFixed(2)}
              y: ${view.center.y.toFixed(2)}`;
              displayMessage(info);
            }
            // Get the new extent of the view only when view is stationary.
            if (view.extent) {
              const info = `<br> <span> the view extent changed: </span>
              <br> xmin: ${view.extent.xmin.toFixed(2)}
              xmax: ${view.extent.xmax.toFixed(2)}
              <br> ymin: ${view.extent.ymin.toFixed(2)}
              ymax: ${view.extent.ymax.toFixed(2)}`;
              displayMessage(info);
            }
          }
        );

        // watch popup's visible property to determine when the popup is
        // visible or not visible.
        reactiveUtils.watch(
          () => view.popup.visible,
          () => {
            const info = `<br> <span> view popup visible </span> = ${view.popup.visible}`;
            displayMessage(info);
          }
        );

        function displayMessage(info) {
          outputMessages.innerHTML += info;
          outputMessages.scrollTop = outputMessages.scrollHeight;
        }

        // This function will execute if the promise is rejected
        function errorHandler(error) {
          if (error.name && error.message) {
            const info = `<br><span style=" color: red;"> ${error.name} ${error.message} </span>`;
          } else {
            const info = `<br><span style=" color: red;"> ${error} </span>`;
          }
          displayMessage(info);
        }
      });
    </script>
  </head>

  <body>
    
    <div id="viewDiv">
     
      <div id="outputMessages" class="esri-widget" style="position:absolute;left:10px;top:500px;width:300px;height:300px;">
      </div>
    </div>
  </body>
</html>

**Comment by kobi666** [comment] 2024-03-06 21:15
[watch-for-changes.html.zip](https://github.com/flutter/flutter/files/14515645/watch-for-changes.html.zip)

**Comment by huycozy** [comment] 2024-03-07 08:40
Closing as a duplicate of https://github.com/flutter/flutter/issues/58659. Please follow up on it for further updates. Thanks!

**Closed by huycozy** 2024-03-07 08:40 UTC
Labels: in triage
