### ISSUE TITLE
[tool_crash] FileSystemException: Cannot open file, OS Error: No such file or directory, errno = 2

### ISSUE THREAD

**Issue by AbbosMamadaliyev** [flutter/flutter#146333] opened 2024-04-05 10:41 UTC
## Command
```
flutter build ipa --release
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Cannot open file, OS Error: No such file or directory, errno = 2
```
#0      _File.throwIfError (dart:io/file_impl.dart:675:7)
#1      _File.openSync (dart:io/file_impl.dart:490:5)
#2      _File.readAsBytesSync (dart:io/file_impl.dart:574:18)
#3      _File.readAsStringSync (dart:io/file_impl.dart:624:18)
#4      ForwardingFile.readAsStringSync (package:file/src/forwarding/forwarding_file.dart:99:16)
#5      ErrorHandlingFile.readAsStringSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:217:22)
#6      _runSync (package:flutter_tools/src/base/error_handling_io.dart:587:14)
#7      ErrorHandlingFile.readAsStringSync (package:flutter_tools/src/base/error_handling_io.dart:216:12)
#8      BuildIOSArchiveCommand._parseImageAssetContentsJson (package:flutter_tools/src/commands/build_ios.dart:184:72)
#9      BuildIOSArchiveCommand._validateLaunchImageAssetsAfterArchive (package:flutter_tools/src/commands/build_ios.dart:352:60)
<asynchronous suspension>
#10     BuildIOSArchiveCommand.runCommand (package:flutter_tools/src/commands/build_ios.dart:434:49)
<asynchronous suspension>
#11     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1389:27)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#13     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:355:9)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#16     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:295:5)
<asynchronous suspension>
```
```
[33m[!][39m Flutter (Channel stable, 3.19.5, on macOS 14.2.1 23C71 darwin-arm64, locale en-UZ)
    [32m•[39m Flutter version 3.19.5 on channel stable at /Users/appmanagaer/sdk/flutter
    [33m![39m Warning: `dart` on your path resolves to /opt/homebrew/Cellar/dart/3.2.6/libexec/bin/dart, which is not inside your current Flutter SDK checkout at /Users/appmanagaer/sdk/flutter. Consider adding
      /Users/appmanagae

**Comment by danagbemava-nc** [comment] 2024-04-05 11:03
Closing this as a duplicate of https://github.com/flutter/flutter/issues/91559

**Closed by danagbemava-nc** 2024-04-05 11:03 UTC
Labels: in triage
