### ISSUE TITLE
DropdownMenu focus navigation with typing

### ISSUE THREAD

**Issue by TortillaZHawaii** [flutter/flutter#138406] opened 2023-11-14 11:54 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

The `<select>` HTML tag can be navigated using keystrokes. For example, given HTML:
```html
<select name="pets" id="pet-select">
  <option value="">--Please choose an option--</option>
  <option value="dog">Dog</option>
  <option value="cat">Cat</option>
  <option value="hamster">Hamster</option>
  <option value="parrot">Parrot</option>
  <option value="spider">Spider</option>
  <option value="goldfish">Goldfish</option>
</select>
```
user can expand dropdown and navigate the focus using keys. For example by typing "do" the Dog option would be focused. See https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select for this example. This behavior can be seen in browsers such as Firefox, Chrome or Safari.

Flutter has few ways of creating dropdowns. As of now menus created by using `DropdownButton` or `DropdownMenu` allow users to navigate focus only by using UP and DOWN arrow keys and select them by pressing ENTER key. Users can't start typing to navigate focus. See examples on https://api.flutter.dev/flutter/material/DropdownButton-class.html#material.DropdownButton.1 and https://api.flutter.dev/flutter/material/DropdownButton-class.html#material.DropdownButton.2.

Similar issue related to focus on dropdowns has been raised here: https://github.com/flutter/flutter/issues/123797.

### Proposal

Navigation by keystrokes in dropdown menus would allow Flutter to bridge the gap to native web experience. I think that the Flutter developer should be able to pass some parameter like `focusNavigationText` to `DropdownMenuItem` and `DropdownMenuEntry` that would allow for such navigation to exist.

**Comment by TahaTesser** [comment] 2023-11-15 07:32
duplicate of https://github.com/flutter/flutter/issues/123797

**Closed by TahaTesser** 2023-11-15 07:32 UTC
Labels: c: new feature, f: material design, c: proposal, team-design
