### ISSUE TITLE
Cached engine with custom entrypoint working on debug but not on profile or release

### ISSUE THREAD

**Issue by gcostaapps** [flutter/flutter#97399] opened 2022-01-27 21:29 UTC
Hi, I'm caching a flutter engine to reuse in another Activity. On debug mode it's working but it isn't on profile or release. I think that maybe it's about tree-shaking in my main.dart but don't know why because I'm already use @pragma annotation.

This error is blocking me for reusing the cached engine.

## Steps to Reproduce

1. Added `android:name=".MyApplication"` in application tag in `AndroidManifest.xml`
2. Created MyApplication class

```
package productivity.timetracker.mytime

import android.app.Application
import io.flutter.embedding.engine.FlutterEngine
import io.flutter.embedding.engine.FlutterEngineCache
import io.flutter.embedding.engine.dart.DartExecutor
import io.flutter.view.FlutterMain.findAppBundlePath

class MyApplication : Application() {
    lateinit var flutterEngine : FlutterEngine

    override fun onCreate() {
        super.onCreate()

        // Instantiate a FlutterEngine.
        flutterEngine = FlutterEngine(this)

        // Start executing Dart code to pre-warm the FlutterEngine.
        flutterEngine.dartExecutor.executeDartEntrypoint(
            DartExecutor.DartEntrypoint(findAppBundlePath(),"mainLockScreen")
        )

        // Cache the FlutterEngine to be used by FlutterActivity.
        FlutterEngineCache
            .getInstance()
            .put("LockScreenEngine", flutterEngine)
    }
}
```

3. Added custom method in `main.dart`

```
@pragma('vm:entry-point')
void mainLockScreen() {
  debugPrint("mainLockScreen");
  ..... runApp...

}
```

**Expected results:** App runs normally as well as in debug mode 

**Actual results:**
```
E/flutter (25371): [ERROR:flutter/shell/common/shell.cc(94)] Dart Unhandled Exception: NoSuchMethodError: No top-level getter 'mainLockScreen' declared.
E/flutter (25371): Receiver: top-level
E/flutter (25371): Tried calling: mainLockScreen, stack trace: #0      NoSuchMethodError._throwNew (dart:core-patch/errors_patch.dart:218)
E/flutter (25371):
E/flutter (25371): [ERROR:flutter/runtime/dart_isolate.cc(718)] Could not resolve main entrypoint function.
E/flutter (25371): [ERROR:flutter/runtime/dart_isolate.cc(202)] Could not run the run main Dart entrypoint.
E/flutter (25371): [ERROR:flutter/runtime/runtime_controller.cc(384)] Could not create root isolate.
E/flutter (25371): [ERROR:flutter/shell/common/shell.cc(574)] Could not launch engine with configuration.
```

flutter doctor:
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.8.1, on Microsoft Windows [versÃ£o 10.0.19043.1466], locale pt-BR)
[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.2)
[√] Android Studio (version 2021.1)
[√] VS Code (version 1.63.2)
[√] Connected device (4 available)
• No issues found!

```

**Comment by gcostaapps** [comment] 2022-01-27 22:17
Found an issue that is related to the problem #91841 , going back to version 2.5.3 solved the issue

**Comment by darshankawar** [comment] 2022-01-28 08:04
That is correct. Closing this as a duplicate of https://github.com/flutter/flutter/issues/91841

**Closed by darshankawar** 2022-01-28 08:04 UTC
Labels: in triage
