### ISSUE TITLE
Rendering glitches stacking CustomPainters on top of each other on Android

### ISSUE THREAD

**Issue by jonaird** [flutter/flutter#28999] opened 2019-03-07 17:03 UTC
## Steps to Reproduce

I'm implementing progress rings similar to the rings on the Apple Watch. To do this, I'm simply drawing them using canvas.drawArc in a CustomPainter widget. I'm using a StatefulWidget to increment the progress indicator. Just displaying this alone works on both iOS and Android.
[Here's a picture of what that looks like.](https://i.imgur.com/ThXgmEa.png)

I also have a background that I paint behind the rings using another custom paint. I display the background and rings using a Stack widget 

```
Stack(children: <Widget>[
          RingsBackground(),
          CustomPaint(
            size: Size(200, 200),
            painter: CirclePainter(streak: streak),
          ),
```

When I include the background and increment the progress indicator past a certain point I get very buggy results on Android but not iOS.

[What it looks like on a HuaWei Mate SE running Oreo](https://i.imgur.com/6kttEdU.jpg)
[What it looks like in Android emulation running Pie](https://i.imgur.com/mRzfoWE.png)

However, if I switch to another app and switch back, the rings display and increment properly (in both the emulator and on the real device. 

The background includes some relatively complicated stuff to get the inset shadow effect that I created. If I simplify the background to a single grey arc, this problem disappears on my device but persists on the android emulator.

## Logs

```
[   +1 ms] An Observatory debugger and profiler on BND L34 is available at: http://127.0.0.1:57260/
[        ] For a more detailed help message, press "h". To detach, press "d"; to quit, press "q".
[+74310 ms] I/hwaps   (16479): JNI_OnLoad
[+4564 ms] V/AudioManager(16479): playSoundEffect   effectType: 0
[+1458 ms] V/AudioManager(16479): playSoundEffect   effectType: 0
[ +155 ms] V/AudioManager(16479): playSoundEffect   effectType: 0
[ +199 ms] V/AudioManager(16479): playSoundEffect   effectType: 0
[ +102 ms] I/zygote64(16479): Do partial code cache collection, code=30KB, data=27KB
[        ] I/zygote64(16479): After code cache collection, code=30KB, data=27KB
[        ] I/zygote64(16479): Increasing code cache capacity to 128KB
[ +103 ms] V/AudioManager(16479): playSoundEffect   effectType: 0
[ +167 ms] V/AudioManager(16479): playSoundEffect   effectType: 0
[ +197 ms] V/AudioManager(16479): playSoundEffect   effectType: 0
[ +496 ms] V/AudioManager(16479): playSoundEffect   effectType: 0
```

```
 info • Unused import: 'package:flutter/material.dart' • lib/screens/habits.dart:1:8 • unused_import
   info • Unused import: 'package:flutter_circular_chart/flutter_circular_chart.dart' • lib/ui_elements/rings.dart:2:8 • unused_import
```

```
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.3 18D109, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[!] Android Studio (version 3.3)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.31.1)
[✓] Connected device (1 available)
```

**Comment by jonaird** [comment] 2019-03-09 00:02
I found out that this happens because of painting outside the boundaries given by the CustomPaint widget.

**Comment by jonahwilliams** [comment] 2019-03-09 18:21
That makes sense, if you paint outside the boundaries then there is no guarantee that things will not be repainted in odd ways. 

@jonaird how did you resolve the problem? did you increase the paint area or use clips?

**Comment by jonaird** [comment] 2019-03-09 20:04
I increased the paint area. Didn't try using a clip.

**Comment by kf6gpe** [comment] 2020-01-27 20:36
This looks like it's working as intended, and was a support issue. Please reach out to one of the forums at https://flutter.dev/support for questions like this. I'm closing this issue as it appears not to be an issue with Flutter itself.

**Closed by kf6gpe** 2020-01-27 20:36 UTC
Labels: d: api docs, documentation, passed first triage
