### ISSUE TITLE
AutoComplete widget is not working properly when we use keyboard up and down arrow key with viewBuilderOption implementation

### ISSUE THREAD

**Issue by DessisInformatica** [flutter/flutter#144935] opened 2024-03-11 15:39 UTC
### Steps to reproduce

Just specify 'optionsViewBuilder' within AutoComplete

### Expected results

Navigation between options enabled via the keyboard (up arrow, down arrow and selection with the enter key)

### Actual results

If you specify 'optionsViewBuilder' within Autocomplete, keyboard navigation is disabled.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: Text('Flutter Autocomplete Example'),
        ),
        body: Padding(
          padding: const EdgeInsets.all(8.0),
          child: AutocompleteExample(),
        ),
      ),
    );
  }
}

class AutocompleteExample extends StatelessWidget {
  final List<String> _kOptions = <String>[
    'Apple',
    'Banana',
    'Blueberry',
    'Cherry',
    'Grape',
    'Lemon',
    'Orange',
    'Peach',
    'Pear',
    'Strawberry',
  ];

  @override
  Widget build(BuildContext context) {
    return Autocomplete<String>(
      optionsBuilder: (TextEditingValue textEditingValue) {
        if (textEditingValue.text == '') {
          return const Iterable<String>.empty();
        }
        return _kOptions.where((String option) {
          return option.contains(textEditingValue.text.toLowerCase());
        });
      },
      optionsViewBuilder: (BuildContext context,
          AutocompleteOnSelected<String> onSelected, Iterable<String> options) {
        return Align(
          alignment: Alignment.topLeft,
          child: Material(
            elevation: 4.0,
            child: Container(
              height: 200.0, // Change as per your requirement
              child: ListView.builder(
                itemCount: options.length,
                itemBuilder: (BuildContext context, int index) {
                  final String option = options.elementAt(index);
                  final bool highlight =
                      AutocompleteHighlightedOption.of(context) == index;

                  return ListTile(
                    //  tileColor: highlight ? Theme.of(context).focusColor : null,
                    tileColor: highlight
                        ? Theme.of(context).focusColor.withOpacity(0.1)
                        : null,

                    title: Text(
                      option,
                    ),
                    onTap: () {
                      onSelected(option);
                    },
                  );
                },
              ),
            ),
          ),
        );
      },
      onSelected: (String selection) {
        print('You just selected $selection');
      },
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.19.1, on Microsoft Windows [versÆo 10.0.22621.3235], locale pt-BR)
    • Flutter version 3.19.1 on channel stable at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision abb292a07e (3 weeks ago), 2024-02-20 14:35:05 -0800
    • Engine revision 04817c99c9
    • Dart version 3.3.0
    • DevTools version 2.31.1

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\juppd\AppData\Local\Android\Sdk
    • Platform android-UpsideDownCakePrivacySandbox, build-tools 34.0.0
    • ANDROID_HOME = C:\Users\juppd\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.5.5)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.5.33627.172
    • Windows 10 SDK version 10.0.22000.0

[✓] Android Studio (version 2023.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)

[✓] VS Code (version 1.87.1)
    • VS Code at C:\Users\juppd\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.82.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [versÆo 10.0.22621.3235]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 122.0.6261.112
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 122.0.2365.80

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by huycozy** [comment] 2024-03-12 07:58
Hi @DessisInformatica 
Using your sample code, I see it's working as expected, please see this demo:

https://github.com/flutter/flutter/assets/104349824/18c193ef-7c29-465b-adb1-5d15cd232189

Checking this on the latest stable channel 3.19.3.

**Comment by DessisInformatica** [comment] 2024-03-12 14:16
Hi @huycozy,

Sorry, I don't know how to explain it, but it really works.
Thank you very much for the quick and attentive response.

**Comment by DessisInformatica** [comment] 2024-03-12 14:43
I just found the real 'problem'.
When I set the focusNode with a predefined focus, in fieldViewBuilder, AutoComplete no longer displays the options.
Am I doing the right thing when setting the focusNode?
Is there any other way to resolve this issue?

```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: Text('Flutter Autocomplete Example'),
        ),
        body: Padding(
          padding: const EdgeInsets.all(8.0),
          child: AutocompleteExample(),
        ),
      ),
    );
  }
}

class AutocompleteExample extends StatelessWidget {
  FocusNode focoExternal = FocusNode();
  final List<String> _kOptions = <String>[
    'Apple',
    'Banana',
    'Blueberry',
    'Cherry',
    'Grape',
    'Lemon',
    'Orange',
    'Peach',
    'Pear',
    'Strawberry',
  ];

  @override
  Widget build(BuildContext context) {
    return Autocomplete<String>(
      optionsBuilder: (TextEditingValue textEditingValue) {
        if (textEditingValue.text == '') {
          return const Iterable<String>.empty();
        }
        return _kOptions.where((String option) {
          return option.contains(textEditingValue.text.toLowerCase());
        });
      },
      optionsViewBuilder: (BuildContext context, AutocompleteOnSelected<String> onSelected, Iterable<String> options) {
      return Align(
        alignment: Alignment.topLeft,
        child: Material(
          elevation: 4.0,
          child: SizedBox(
            height: 200.0, // Change as per your requirement
            child: ListView.builder(
              itemCount: options.length,
              itemBuilder: (BuildContext context, int index) {
                final String option = options.elementAt(index);
                final bool highlight = AutocompleteHighlightedOption.of(context) == index;
                return ListTile(
                  //  tileColor: highlight ? Theme.of(context).focusColor : null,
                  tileColor: highlight ? Theme.of(context).focusColor.withOpacity(0.1) : null,
                  title: Text(
                    option,
                  ),
                  onTap: () {
                    onSelected(option);
                  },
                );
              }),
            ),
          ),
        );
      },
      fieldViewBuilder: (BuildContext context, TextEditingController textEditingController, FocusNode focusNode, VoidCallback onFieldSubmitted) {
        focusNode = focoExternal;
        return TextFormField(
          controller: textEditingController,
          focusNode: focusNode,
          style: const TextStyle(color: Colors.black, fontSize: 12,),
          decoration: InputDecoration(               
            errorBorder: const OutlineInputBorder(
              borderSide: BorderSide(color: Color(0xFF9A050F), width: 2,),
              borderRadius: BorderRadius.all(Radius.circular(10)),
            ),
            focusedErrorBorder: const OutlineInputBorder(
              borderSide: BorderSide(color: Color(0xFF9A050F), width: 2,),
              borderRadius: BorderRadius.all(Radius.circular(10)),
            ),
            errorStyle: const TextStyle(height: 0.05, color: Colors.red),        
            contentPadding: const EdgeInsets.symmetric(vertical: 0, horizontal: 5.0),
            enabledBorder: OutlineInputBorder(
              borderSide: const BorderSide(color: Color(0xff5532e8), width: 2,),
              borderRadius: BorderRadius.circular(10),
            ),
            focusedBorder: OutlineInputBorder(
              borderSide: const BorderSide(color: Color(0xfffe9628), width: 2,),
              borderRadius: BorderRadius.circular(10),
            ),
            border: InputBorder.none,
            labelText: 'Label',
            labelStyle: const TextStyle(color: Colors.black, fontSize: 12),
          ),
          onFieldSubmitted: (String value) {
            onFieldSubmitted();
            print('You just typed a new entry  $value');
          },
        );
      },
      onSelected: (String selection) {
        print('You just selected $selection');
      },
    );
  }
}

```

**Comment by huycozy** [comment] 2024-03-13 05:33
For that issue, looks like you want to trigger the TextField focus from outside the AutoComplete widget, right? If so, https://github.com/flutter/flutter/issues/140662 could be similar/related. Otherwise, please file another issue for that.

Since the original issue is not reproduced. I'm going to close this issue. Thanks!

**Closed by huycozy** 2024-03-13 05:33 UTC
Labels: in triage
