### ISSUE TITLE
Request more content in the ListView API doc

### ISSUE THREAD

**Issue by InMatrix** [flutter/flutter#8752] opened 2017-03-13 23:11 UTC
I observed a developer unable to figure out how to use ListView due to lack of content in the API doc. While the ListView constructor is relatively easy to understand, ListView.builder() and ListView.custom are less so. It would be great to include some sample code in the API doc.

**Comment by abarth** [comment] 2017-03-13 23:13
Yep.  Working on these docs up from the bottom of the dependency tree.  Duplicate of #1645

**Closed by abarth** 2017-03-13 23:13 UTC
Labels: dev: docs - api, from: study
