### ISSUE TITLE
Bug: Ink decoration is rendered below the parent Container decoration

### ISSUE THREAD

**Issue by JakesMD** [flutter/flutter#109614] opened 2022-08-16 14:48 UTC
### Bug description
When wrapping an `Ink` with a `Container` the decoration (e.g. `color`) of the `Ink` gets sent to the bottom. This bug occurs no matter how many widgets are inbetween the `Ink` and `Container`. So long as there's a `Container` with an `Ink` somewhere down the line.

### Example that reproduces the bug
Note that the color of the `Ink` is blue. The border radius on the red `Container` lets you see the blue color of the `Ink` underneath it. But the blue color should be on top as is the case when wrapping the `Ink` with the `Material` instead.

[Example on dartpad.dev](https://dartpad.dev/?id=0978599516db50455f52b81655be8fa0)
```dart
import 'package:flutter/material.dart';

void main() => runApp(const MaterialApp(home: MyDemoPage()));

class MyDemoPage extends StatelessWidget {
  const MyDemoPage({
    Key? key,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Column(
        children: [
          Container(
            decoration: BoxDecoration(
              borderRadius: BorderRadius.circular(25),
              color: Colors.red,
            ),
            child: const MyTextButton("This should be blue"),
          ),
          const SizedBox(height: 25),
          Material(
            color: Colors.green,
            borderRadius: BorderRadius.circular(25),
            child: const MyTextButton("This should be blue"),
          ),
          const SizedBox(height: 25),
          Container(
            decoration: BoxDecoration(
              borderRadius: BorderRadius.circular(25),
              color: Colors.red,
            ),
            child: const SizedBox(
              child: Padding(
                padding: EdgeInsets.zero,
                child: InkWell(
                  child: MyTextButton(
                      "Bug still occurs no matter how many parents are inbetween"),
                ),
              ),
            ),
          ),
        ],
      ),
    );
  }
}

class MyTextButton extends StatelessWidget {
  final String text;

  const MyTextButton(this.text);

  @override
  Widget build(BuildContext context) {
    return Ink(
      width: 150,
      height: 50,
      color: Colors.blue,
      child: Center(
        child: Text(text),
      ),
    );
  }
}
```
### Flutter version
```
Flutter 3.0.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f1875d570e (5 weeks ago) • 2022-07-13 11:24:16 -0700
Engine • revision e85ea0e79c
Tools • Dart 2.17.6 • DevTools 2.12.2
```

### Quick Fix
Until now the quick fix was to make the parent widget a `Material` instead of a `Container`. But for me now that is no longer an option.

**Comment by exaby73** [comment] 2022-08-16 19:55
Duplicate of https://github.com/flutter/flutter/issues/83108. This is working as expected

**Closed by exaby73** 2022-08-16 19:55 UTC
Labels: in triage
