### ISSUE TITLE
Scrollbar should have option to specify effective depth for nested scrollable

### ISSUE THREAD

**Issue by coreysprague** [flutter/flutter#36474] opened 2019-07-18 18:29 UTC
Horizontal Scrollables in a list view are causing the Scrollbars of the containing Scrollable to be drawn. Ideally, the Scrollbar would only show for the axis of the immediate Scrollable descendent, or perhaps allow consumers to specify the allowed depth of Scrollable to listen to.

## Steps to Reproduce
1. Create a ListView and Wrap with a Scrollbar widget
2. Place a horizontal PageView widget in a list item
3. Swipe the PageView
4. Observe that the scrollbar for the ListView is scrolling horizontally

I created a sample app to demonstrate: 
https://github.com/coreysprague/flutter_nested_pageview_scrollbars

![](https://github.com/coreysprague/flutter_nested_pageview_scrollbars/raw/master/scrollbar_bug.mov.gif)

**flutter doctor -v**
[✓] Flutter (Channel unknown, v1.7.8+hotfix.3, on Mac OS X 10.14.5 18F132,
    locale en-US)
    • Flutter version 1.7.8+hotfix.3 at /Users/cosprague/Library/Code/flutter
    • Framework revision b712a172f9 (9 days ago), 2019-07-09 13:14:38 -0700
    • Engine revision 54ad777fd2
    • Dart version 2.4.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/cosprague/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/cosprague/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • CocoaPods version 1.7.1

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 36.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.36.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.2.0

[✓] Connected device (3 available)
    • iPhone Xs • CB2CBFCD-D56F-412E-B17C-B5908F7D749E • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)
    • macOS     • macOS                                • darwin-x64     • Mac OS X 10.14.5 18F132
    • web       • web                                  • web-javascript • Google Chrome 75.0.3770.142 

• No issues found!

**Comment by coreysprague** [comment] 2019-07-19 18:11
I found a workaround for this. I can wrap the nested scrollview with this code:

```
NotificationListener<ScrollNotification>(
          onNotification: (notification) => true,
          child: <nested scrollview>
);
```

this will prevent the notification event from bubbling up to the parent scrollview.

I was also able to solve it by forking Scrollbar & CupertinoScrollbar and doing an early return in the scroll handler if the depth was greater than 0 (but the earlier solution of trapping the notification is more elegant).

Regardless, the current default behavior doesn't seem intuitive or allow people to fall into the pit of success.

**Comment by Piinks** [comment] 2020-02-27 01:03
Hey @coreysprague Thanks for bring this to our attention, and for the really good reproduction.

I am not sure this is a regression, I checked out 1.5.4 and ran your repro and found that the Scrollbars are still there, they are just a _little_ less noticeable along the edges of the screen. 
I think they are more apparent in 1.7.8 because https://github.com/flutter/flutter/pull/31763 added padding to the Scrollbars, bringing them more into view.

I don't know what the expected behavior should be here then. I could see expecting either case (to show the `Scrollbar` or not) depending on the situation. Perhaps this is something we can make configurable on the `Scrollbar`?

**Comment by coreysprague** [comment] 2020-02-27 18:45
Hi @Piinks 

Making it configurable on the ScrollBar would make sense. It seems like it would make the most sense to default the behavior to only respond to scroll notifications from the immediate descendent, and optionally respond to all? That would of course be a breaking change, but I think it would be the case that most use cases would expect.

**Comment by Piinks** [comment] 2020-02-27 18:53
Thanks for coming back! :)
That sounds like a good idea to me! We try not to make breaking changes, so we may configure it the other way around where the default behavior is the current behavior. That way no one is broken.

**Comment by coreysprague** [comment] 2020-03-06 16:12
@Piinks -- I just wanted to throw out another thought that might also address this problem (and maybe is easier to solve). 

I suspect this issue is primarily isolated to when you have nested content that scrolls perpendicular to the parent's scrollview

I wonder if instead of making Scrollbar aware of nesting... if instead scrollbar could have a property to define which axes to show the scroll indicators. It could default to both horizontal & vertical, but an optional parameter could specify vertical only (or horizontal only).

I could see this feature potentially having value outside of the nesting use case as well.

**Comment by carmas123** [comment] 2020-08-02 09:42
I think that the `ScrollBar` need to be visibile only for direct child and not for all tree.
If I've a multiple childs into a `SingleChildScrollView` and I want to show scrollbar for all childs the `ScrollBar` widget must have a simple parameter like "infiniteDeep" that make to be able to have scrollbar for all the tree.
But if I need to have the scrollbar only for the main container like a `SingleChildScrollView` I leave this parameter false or
as said by @coreysprague we need to have a parameter to specify the effective depth of scrollbar.

**Comment by simrat39** [comment] 2020-09-01 02:22
> I found a workaround for this. I can wrap the nested scrollview with this code:
> 
> ```
> NotificationListener<ScrollNotification>(
>           onNotification: (notification) => true,
>           child: <nested scrollview>
> );
> ```
> 
> this will prevent the notification event from bubbling up to the parent scrollview.
> 
> I was also able to solve it by forking Scrollbar & CupertinoScrollbar and doing an early return in the scroll handler if the depth was greater than 0 (but the earlier solution of trapping the notification is more elegant).
> 
> Regardless, the current default behavior doesn't seem intuitive or allow people to fall into the pit of success.

Thanks! Works perfect for me
For anyone who has a lot of scrollviews, you can use this extension:
import 'package:flutter/material.dart';

```
extension NestedScrollFixExtension on Widget {
  Widget fixNestedDoubleScrollbar() {
    return NotificationListener<ScrollNotification>(
      onNotification: (notification) => true,
      child: this,
    );
  }
```
}

**Comment by pedromassangocode** [comment] 2020-12-09 11:33
I was able to reproduce this with the latest `master` and `beta` channel of Flutter. Code based on https://github.com/flutter/flutter/issues/66444 that was closed as duplicate.

<img width="400" height="500" src="https://user-images.githubusercontent.com/67424416/94013746-6fc60880-fda2-11ea-8e0d-29d013e0f44d.gif">

<details><summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel beta, 1.24.0-10.2.pre, on Mac OS X 10.15.7 19H2 darwin-x64, locale en)
    • Flutter version 1.24.0-10.2.pre at /Users/pedromassango/dev/SDKs/flutter_beta
    • Framework revision 022b333a08 (3 weeks ago), 2020-11-18 11:35:09 -0800
    • Engine revision 07c1eed46b
    • Dart version 2.12.0 (build 2.12.0-29.10.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.2.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 52.0.4
    • Dart plugin version 202.8070

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (2 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 87.0.4280.88

• No issues found!
Process finished with exit code 0
```
</details>

**Comment by alaydeliwala** [comment] 2021-01-04 21:49
> > I found a workaround for this. I can wrap the nested scrollview with this code:
> > ```
> > NotificationListener<ScrollNotification>(
> >           onNotification: (notification) => true,
> >           child: <nested scrollview>
> > );
> > ```
> > 
> > 
> > this will prevent the notification event from bubbling up to the parent scrollview.
> > I was also able to solve it by forking Scrollbar & CupertinoScrollbar and doing an early return in the scroll handler if the depth was greater than 0 (but the earlier solution of trapping the notification is more elegant).
> > Regardless, the current default behavior doesn't seem intuitive or allow people to fall into the pit of success.
> 
> Thanks! Works perfect for me
> For anyone who has a lot of scrollviews, you can use this extension:
> 
> ```
> import 'package:flutter/material.dart';
> 
> extension NestedScrollFixExtension on Widget {
>   Widget fixNestedDoubleScrollbar() {
>     return NotificationListener<ScrollNotification>(
>       onNotification: (notification) => true,
>       child: this,
>     );
>   }
> }
> ```

I tried this and it worked (partially). With this workaround, a double scrollbar does not show up, however, no nested scrollbar shows up. Is there a workaround for that?

**Closed** 2021-01-15 23:24 UTC
Labels: P4, customer: web10, f: scrolling, found in release: 1.24, found in release: 1.25, framework, has reproducible steps, severe: new feature, team: gallery
