### ISSUE TITLE
I am not sure if this is going to give a bug.

### ISSUE THREAD

**Issue by XHL-study** [flutter/flutter#25358] opened 2018-12-14 07:25 UTC
## Steps to Reproduce

1.
```dart
class TextPage extends StatelessWidget {
  TextPage(@required this.title);

  String title;
  final String defTitle = "文字样式";

  Widget _sectionTitle(String title) {
    return new Center(
      heightFactor: 2.6,
      child: new Text("xx控件控件xx文字xx文字",
          style: new TextStyle(
              fontSize: 18.0,
              background: (new Paint()..color = Colors.grey),
              color: Colors.white)),
    );
  }

  @override
  Widget build(BuildContext context) {
    // TODO: implement build

    return new Scaffold(
        appBar: new AppBar(
          title: new Text(title != null ? title : defTitle),
          centerTitle: true,
        ),
        body: new SingleChildScrollView(
          child: new Center(
            child: new Column(
              children: <Widget>[
                _sectionTitle("控件Text控件".toString()),
                new Text("Hello World ", textAlign: TextAlign.center),
                new Text("Hello World * 4" * 10,
                    maxLines: 2, overflow: TextOverflow.ellipsis),
                new Text("Hello world", textScaleFactor: 1.5),
                new Center(
                  child: new Text("Hello World汉字yinwen",
                      textAlign: TextAlign.center,
                      style: new TextStyle(
                          color: Colors.blueAccent,
                          background: new Paint()..color = Colors.greenAccent,
                          decoration: TextDecoration.underline,
                          decorationStyle: TextDecorationStyle.dotted)),
                )
              ],
            ),
          ),
        ));
  }
}
```

# 
# The bug occurred after using TextStyle.background
# 
# 

2. ![image](https://user-images.githubusercontent.com/22956309/49988792-11f07400-ffb3-11e8-84dd-84a805a09045.png)

3. 
![image](https://user-images.githubusercontent.com/22956309/49988947-9f33c880-ffb3-11e8-96d4-eabbc55d168e.png)

4.
![screenshot_2018-12-14-15-24-21-064_com firtflutte](https://user-images.githubusercontent.com/22956309/49989206-75c76c80-ffb4-11e8-9e61-783951342367.png)

5. This is the result of running flutter doctor -v.

```
flutter doctor -v
[√] Flutter (Channel stable, v1.0.0, on Microsoft Windows [Version 10.0.17134.376], locale zh-CN)
    • Flutter version 1.0.0 at C:\src\flutter
    • Framework revision 5391447fae (2 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at C:\Users\Administrator\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = C:\Users\Administrator\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[√] Android Studio (version 3.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 31.2.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 6.0 (API 23) (emulator)

• No issues found!
```

## Logs

```
```

```
```

```
```

**Comment by zoechi** [comment] 2018-12-14 10:09
Please add the output of `flutter doctor -v`.

**Comment by XHL-study** [comment] 2018-12-14 10:16
> Please add the output of `flutter doctor -v`.

I added

**Comment by jason-simmons** [comment] 2018-12-14 21:30
See https://github.com/flutter/flutter/issues/24337

I think this is an issue within Skia.  In some scenarios, Skia seems to be reordering operations and drawing the background rectangle on top of the text instead of below it

**Comment by XHL-study** [comment] 2018-12-15 02:31
> See #24337
> 
> I think this is an issue within Skia. In some scenarios, Skia seems to be reordering operations and drawing the background rectangle on top of the text instead of below it

Thanks, I just tested it and it really is like this.

**Comment by zoechi** [comment] 2018-12-19 15:06
Duplicate of #24337

**Closed by zoechi** 2018-12-19 15:06 UTC
Labels: a: text input, dependency: skia, engine
