### ISSUE TITLE
video_player: ^2.9.2: Task :video_player_android:compileDebugJavaWithJavac FAILED (Java compiler version 21 has deprecated support for compiling with source/target version 8.)

### ISSUE THREAD

**Issue by Sinishisimus** [flutter/flutter#158269] opened 2024-11-06 16:09 UTC
### Steps to reproduce

I am using the following build setup:

- video_player: ^2.9.2
- min sdk 31
- compile & target sdk 34
- Java 11
- kotlin plugin 2.0.21
- agp 8.7.2
- gradle 8.9
- sdk: ^3.4.4
- flutter: ^3.22.3

The building of the project faIis with the error below.
Are there plans to update the project so that is can work with Java 11/17?

```
Task :video_player_android:compileDebugJavaWithJavac FAILED
Java compiler version 21 has deprecated support for compiling with source/target version 8.
Try one of the following options:
    1. [Recommended] Use Java toolchain with a lower language version
    2. Set a higher source/target version
    3. Use a lower version of the JDK running the build (if you're not using Java toolchain)
For more details on how to configure these settings, see https://developer.android.com/build/jdks.
To suppress this warning, set android.javaCompile.suppressSourceTargetDeprecationWarning=true in gradle.properties.
warning: [options] source value 8 is obsolete and will be removed in a future release
warning: [options] target value 8 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
error: warnings found and -Werror specified
1 error
3 warnings
Java compiler has deprecated support for compiling with source/target compatibility version 8.
```

### Expected results

The project should compile with the given setup:

- min sdk 31
- compile & target sdk 34
- Java 11
- kotlin plugin 2.0.21
- agp 8.7.2
- gradle 8.9
- sdk: ^3.4.4
- flutter: ^3.22.3

### Actual results

Building of the project fails with the following error:

> Task :video_player_android:compileDebugJavaWithJavac FAILED
Java compiler version 21 has deprecated support for compiling with source/target version 8.
Try one of the following options:
    1. [Recommended] Use Java toolchain with a lower language version
    2. Set a higher source/target version
    3. Use a lower version of the JDK running the build (if you're not using Java toolchain)
For more details on how to configure these settings, see https://developer.android.com/build/jdks.
To suppress this warning, set android.javaCompile.suppressSourceTargetDeprecationWarning=true in gradle.properties.
warning: [options] source value 8 is obsolete and will be removed in a future release
warning: [options] target value 8 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
error: warnings found and -Werror specified
1 error
3 warnings

Java compiler has deprecated support for compiling with source/target compatibility version 8.
Set Java Toolchain to 17
Change Java language level and jvmTarget to 11 in all modules if using a lower level.
Pick a different compatibility level...
Pick a different JDK to run Gradle...
More information...

warnings found and -Werror specified

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel [user-branch], 3.22.3, on macOS 14.1 23B2073 darwin-arm64, locale en-GB)
    ! Flutter version 3.22.3 on channel [user-branch] at /Users/sinishisimus/Documents/Work/Flutter/flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at https://flutter.dev/docs/get-started/install.
    ! Upstream repository unknown source is not a standard remote.
      Set environment variable "FLUTTER_GIT_URL" to unknown source to dismiss this error.
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.2)
[✓] VS Code (version 1.94.0)
[✓] Connected device (5 available)
    ! Error: Browsing on the local area network for iPhone 14 Pro. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this
      Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
    ! Error: Browsing on the local area network for iPhone SE 3rd Gen. Ensure the device is unlocked and attached with a cable or associated with the same local area network as
      this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
[✓] Network resources

! Doctor found issues in 1 category.
```

</details>

**Comment by stuartmorgan** [comment] 2024-11-06 17:01
Duplicate of https://github.com/flutter/flutter/issues/148478

**Closed by stuartmorgan** 2024-11-06 17:01 UTC
