### ISSUE TITLE
webview_flutter plugin JavaScript popup boxes are not shown

### ISSUE THREAD

**Issue by ghost** [flutter/flutter#34853] opened 2019-06-21 15:21 UTC
In Android WebView, JavaScript popups normally work without any extra coding in the WebView. Unfortunately, they are not working in my app using webview_flutter plugin. 

## Steps to Reproduce

You can reproduce by setting your webview_flutter plugin running on Android url to: 'https://www.w3schools.com/js/tryit.asp?filename=tryjs_confirm' and clicking the "try it" button. 

## Logs
```
[+5119 ms] D/ViewRootImpl@b42e355[MainActivity](26027): ViewPostIme pointer 0 

[  +93 ms] D/ViewRootImpl@b42e355[MainActivity](26027): ViewPostIme pointer 1 

[  +23 ms] W/cr_WebViewCallback(26027): Unable to create JsDialog without an Activity 

[   +2 ms] D/InputMethodManager(26027): HSIFW - flag : 0 Pid : 26027 

[        ] I/InputMethodManager(26027): hideSoftInputFromWindow ignore mServedView == null or mServedView.getWindowToken() != windowToken, mServedView :io.flutter.view.FlutterView{e9b5fd1 VFE...... .F....I. 0,0-1920,1200} 
```

**Comment by jerryzhoujw** [comment] 2019-08-18 09:32
Same in iOS's webview.

**Comment by jerryzhoujw** [comment] 2019-08-18 13:51
You can use
```
flutter_webview_plugin:
    git:
      ref: "dev/fix_alert_not_work_in_webview"
      url: "https://github.com/jerryzhoujw/flutter_webview_plugin"
      source: git
```
this as temp in `pubspec.yaml` before merge [PR](https://github.com/fluttercommunity/flutter_webview_plugin/pull/522)

**Comment by nhojjava** [comment] 2019-08-19 14:31
Thanks @jerryzhoujw but I believe you are referring to a completely different, "community" plugin, not the official webview_flutter plugin in this repository.

I can confirm that JavaScript alerts do work in flutter_webview_plugin. However, I will prefer to stay with the official webview_flutter plugin because I've already released an iOS version on the AppStore using that one. 

I do recall reading somewhere that they wanted to merge these two plugins.

In the webview_flutter plugin, we are able to add our own JavaScript alert callbacks to FlutterWebView.m to show them, but I haven't found a way to make them work in Android using this plugin.

Objective-C callback method that I added to get JavaScript alert working in iOS:
> -(void)webView:(WKWebView *)webView runJavaScriptAlertPanelWithMessage:

**Comment by jerryzhoujw** [comment] 2019-08-26 05:23
@nhojjava  I have include the change in [2012](https://github.com/flutter/plugins/pull/2012) to fix iOS part.  I'm not familiar android part, do you mean Android also didn't work with js `alert` ?

**Comment by nhojjava** [comment] 2019-08-26 13:20
@jerryzhoujw  That is correct.

**Comment by janmoppel** [comment] 2019-09-24 09:10
Hello @nhojjava !

Thank you for posting an issue.
Can you please also attach your `flutter doctor -v` command output?

Thank you.

**Comment by nhojjava** [comment] 2019-10-01 20:47
@janmoppel here it is please understand my delayed response as I've moved away from this Flutter project due to lack of support and functionality by Flutter.

flutter doctor -v
[√] Flutter (Channel stable, v1.9.1+hotfix.4, on Microsoft Windows [Version 10.0.18362.356], locale en-US)
    • Flutter version 1.9.1+hotfix.4 at C:\src\flutter
    • Framework revision cc949a8e8b (4 days ago), 2019-09-27 15:04:59 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\bdrong\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 40.0.2
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] Connected device (1 available)
    • SM T580 • 5200edd85b0dc4d7 • android-arm • Android 8.1.0 (API 27)

• No issues found!

**Comment by deandreamatias** [comment] 2019-10-22 13:11
This issue it's the same as #30358 ?
If yes, maybe someone can close that issue

**Comment by VladyslavBondarenko** [comment] 2020-02-06 09:14
Closing as duplicate of https://github.com/flutter/flutter/issues/30358

**Closed by VladyslavBondarenko** 2020-02-06 09:14 UTC
Labels: customer: crowd, p: webview, plugin
