### ISSUE TITLE
cull_opacity_perf__e2e_summarymulti_widget_construction_perf__e2e_summary 99th_percentile_frame_rasterizer_time_millis regression

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#63675] opened 2020-08-13 15:59 UTC
Jump of nearly 10%. See

https://flutter-flutter-perf.skia.org/e/?begin=1597192175&end=1597271470&keys=X0bd208fe6bff1b2cdf441b7fa8596b45&xbaroffset=21023

**Comment by kf6gpe** [comment] 2020-08-13 15:59
cc @liyuqian

**Comment by zanderso** [comment] 2020-08-13 16:21
It looks like https://github.com/flutter/flutter/commit/2384376f643f73e3823a174067469d4818ed9406 might have used the same name for a substantially different benchmark. @liyuqian @CareF was perf for the old and new versions of this benchmark expected to be the same?

**Comment by CareF** [comment] 2020-08-13 16:24
`99th_percentile_frame_rasterizer_time_millis` regression is actually a bug fix.. Previous version is really returning 90th percentile.

**Comment by CareF** [comment] 2020-08-13 16:31
> It looks like [2384376](https://github.com/flutter/flutter/commit/2384376f643f73e3823a174067469d4818ed9406) might have used the same name for a substantially different benchmark. @liyuqian @CareF was perf for the old and new versions of this benchmark expected to be the same?

@zanderso Correct me if I'm wrong but the changed made to `dev/devicelab/lib/tasks/gallery.dart` should return the same test for the default input, as `flutter_gallery__transition_perf(_with_semantics)`. May I ask which one do you refer to?

**Comment by zanderso** [comment] 2020-08-13 18:23
I was looking at the change indicated by the graph that @kf6gpe linked. I'm asking whether the regression is a bug in that change. If it's not, then we can rebaseline (if needed), and close this issue.

**Comment by liyuqian** [comment] 2020-08-13 18:32
As the regression is a bug fix instead of a bug, I'm closing this issue. Meanwhile, the skia perf doesn't have the "rebaseline" process as one only needs to mark whether a jump is good or bad. I just modified Ray's "bad" rating to "good" and left a comment on Skia perf saying that this is actually a bug fix.

**Closed by liyuqian** 2020-08-13 18:32 UTC
Labels: P1, engine, perf: speed, severe: performance, severe: regression, team: benchmark
