### ISSUE TITLE
TextCapitalization incorrectly persists between multiple TextField/CupertinoTextFields

### ISSUE THREAD

**Issue by zhenyi** [flutter/flutter#59374] opened 2020-06-13 00:14 UTC
Here's a gif to illustrate the problem:
1. There are multiple `CupertinoTextField`s, the 1st with `TextCapitalization.words` and the rest with `TextCapitalization.none`.
2. When the 1st `CupertinoTextField` is selected, the shift key of the soft keyboard is set to on (this is the correct behavior).
3. Now select the 2nd or the 3rd `CupertinoTextField`, notice that the shift key doesn't turn off.
4. Similarly, when you select the 2nd or the 3rd `CupertinoTextField`, then select the 1st `CupertinoTextField `, the shift key doesn't automatically turn on.
5. This is an iOS-only bug, the problem doesn't occur on Android.

![output](https://user-images.githubusercontent.com/2262/84554782-11719e80-ad4c-11ea-91a7-f2f2ee660b55.gif)

Might be related to #59216, but that's about Flutter web.

<details>
  <summary>Runnable reproduction as lib/main.dart</summary>

```
import 'package:flutter/cupertino.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {

  @override
  Widget build(BuildContext context) {
    return CupertinoApp(
      title: 'Flutter Demo',
      home: MyHomePage()
    );
  }

}

class MyHomePage extends StatefulWidget {

  @override
  _MyHomePageState createState() => _MyHomePageState();

}

class _MyHomePageState extends State<MyHomePage> {

  @override
  Widget build(BuildContext context) {
    return CupertinoPageScaffold(
      child: Padding(
        padding: EdgeInsets.symmetric(horizontal: 15),
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            CupertinoTextField(
              decoration: BoxDecoration(
                border: Border.all(width: 1.0, color: Color.fromRGBO(0, 0, 0, 1))
              ),
              keyboardType: TextInputType.text,
              textCapitalization: TextCapitalization.words,
              placeholder: 'Message'
            ),
            Container(height: 20),
            CupertinoTextField(
              decoration: BoxDecoration(
                border: Border.all(width: 1.0, color: Color.fromRGBO(0, 0, 0, 1))
              ),
              keyboardType: TextInputType.emailAddress,
              textCapitalization: TextCapitalization.none,
              placeholder: 'Email Address'
            ),
            Container(height: 20),
            CupertinoTextField(
              decoration: BoxDecoration(
                border: Border.all(width: 1.0, color: Color.fromRGBO(0, 0, 0, 1))
              ),
              keyboardType: TextInputType.url,
              textCapitalization: TextCapitalization.none,
              placeholder: 'Link'
            )
          ]
        )
      )
    );
  }

}
```
</details>

<details>
  <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel beta, 1.18.0-11.1.pre, on Mac OS X 10.15.5 19F101, locale en-US)
    • Flutter version 1.18.0-11.1.pre at /usr/local/flutter
    • Framework revision 2738a1148b (4 weeks ago), 2020-05-13 15:24:36 -0700
    • Engine revision ef9215ceb2
    • Dart version 2.9.0 (build 2.9.0-8.2.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/zhenyi/Library/Android/sdk
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Users/zhenyi/Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Users/zhenyi/Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.45.1)
    • VS Code at /Users/zhenyi/Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```

</details>

**Comment by TahaTesser** [comment] 2020-06-15 08:58
Hi @zhenyi 
if you `TextCapitalization.none`, it won't enabled Shift when you delete the text cuz it's there is ` TextCapitalization.words` for it (which is working as intended) 

Tested your code sample on iOS and Android, i see same behaviour but you said this is iOS
if you set `keyboardType: TextInputType.emailAddres`   or not, `TextCapitalization.none` seems to do what it does, it's simply doesn't capitalize when you delete text or click on field 

Do you see think it should capatalize even if you set it none?
Maybe  i am missing something from your point

Thank you

**Comment by TahaTesser** [comment] 2020-06-25 08:55
Added material design, issue persist with TextField as well

**Comment by jacob-hutchings** [comment] 2020-08-17 17:33
Something similar happens with the new autofill hints. They do not update consistently when switching between text fields in iOS.

**Comment by jsmeke** [comment] 2020-09-29 16:44
Any solution for this?

**Comment by egeysn** [comment] 2021-12-07 06:39
i add following properties, its working fine.
`   inputType: TextInputType.name,
      textCapitalization:  TextCapitalization.sentences`

**Comment by justinmc** [comment] 2022-10-05 22:10
CC @LongCatIsLooong to verify if this was recently fixed already.

**Comment by Renzo-Olivares** [comment] 2022-10-05 22:14
This is fixed in the latest master. Closing this for now. Feel free to re-open if this comes up again.

**Closed by Renzo-Olivares** 2022-10-05 22:14 UTC
Labels: a: text input, platform-ios, framework, f: material design, f: cupertino, has reproducible steps, found in release: 1.20
