### ISSUE TITLE
Shrine demo does not scroll smoothly on One Plus 3

### ISSUE THREAD

**Issue by cv0cv0** [flutter/flutter#12195] opened 2017-09-21 04:33 UTC
See title.

**Comment by eseidelGoogle** [comment] 2017-09-21 05:47
Can you tell us more about which demo (I assume Flutter Gallery?) and on what hardware you were running?

**Comment by cv0cv0** [comment] 2017-09-21 05:51
Yes,is Flutter Gallery.Shrine when sliding.

**Comment by cv0cv0** [comment] 2017-09-21 05:52
My device is ONEPLUS A3000.

**Comment by eseidelGoogle** [comment] 2017-09-21 13:39
I don't think we have a One Plus 3 around the cube, but we definitely have other One Plus devices in our device rack.  Here is a link to the phone in question:
https://www.amazon.com/OnePlus-A3000-Graphite-Unlocked-Warranty/dp/B01H3V07EW

**Comment by eseidelGoogle** [comment] 2017-09-21 13:42
The GPU of that phone is a "Adreno 530" which is pretty recent.  http://www.gsmarena.com/oneplus_3-7995.php.

Looking at Skia's testing matrix it looks like the 530 isn't covered yet.  It's we'll just have to get a phone and try it out and see if there are phone-specific bugs.

**Comment by iapicca** [comment] 2019-11-01 13:39
Hi @cv0cv0 
I'm closing this issue as it refer to an older version of Flutter.
If you are you still experiencing this issue with the latest version of Flutter,
you may want to open a new issue or comment below;
either way please provide your updated `flutter doctor -v`.
It would be helpful to have also your` flutter run --verbose`
and a self contained app on github (or the steps to reproduce it).
Thank you

**Closed by iapicca** 2019-11-01 13:39 UTC
Labels: e: device-specific, engine, severe: performance, team: gallery
