### ISSUE TITLE
[tool_crash] ClientException

### ISSUE THREAD

**Issue by Awesome-T** [flutter/flutter#73464] opened 2021-01-07 05:55 UTC
## Command
```
flutter run
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ClientException
```
#0      IOClient.send.<anonymous closure> (package:http/src/io_client.dart:50:13)
#1      _invokeErrorHandler (dart:async/async_error.dart:16:24)
#2      _HandleErrorStream._handleError (dart:async/stream_pipe.dart:282:9)
#3      _ForwardingStreamSubscription._handleError (dart:async/stream_pipe.dart:161:13)
#4      _HttpClientResponse.listen.<anonymous closure> (dart:_http/http_impl.dart:441:16)
#5      _rootRunBinary (dart:async/zone.dart:1210:47)
#6      _CustomZone.runBinary (dart:async/zone.dart:1104:19)
#7      _CustomZone.runBinaryGuarded (dart:async/zone.dart:1010:7)
#8      _BufferingStreamSubscription._sendError.sendError (dart:async/stream_impl.dart:376:15)
#9      _BufferingStreamSubscription._sendError (dart:async/stream_impl.dart:394:16)
#10     _BufferingStreamSubscription._addError (dart:async/stream_impl.dart:294:7)
#11     _ForwardingStreamSubscription._addError (dart:async/stream_pipe.dart:132:11)
#12     _addErrorWithReplacement (dart:async/stream_pipe.dart:180:8)
#13     _HandleErrorStream._handleError (dart:async/stream_pipe.dart:287:11)
#14     _ForwardingStreamSubscription._handleError (dart:async/stream_pipe.dart:161:13)
#15     _rootRunBinary (dart:async/zone.dart:1210:47)
#16     _CustomZone.runBinary (dart:async/zone.dart:1104:19)
#17     _CustomZone.runBinaryGuarded (dart:async/zone.dart:1010:7)
#18     _BufferingStreamSubscription._sendError.sendError (dart:async/stream_impl.dart:376:15)
#19     _BufferingStreamSubscription._sendError (dart:async/stream_impl.dart:394:16)
#20     _BufferingStreamSubscription._addError (dart:async/stream_impl.dart:294:7)
#21     _SyncStreamControllerDispatch._sendError (dart:async/stream_controller.dart:811:19)
#22     _StreamController._addError (dart:async/stream_controller.dart:689:7)
#23     _StreamController.addError (dart:async/stream_controller.dart:641:5)
#24     _HttpParser._reportBodyError (dart:_http/http_parser.dart:1158:22)
```
```
[✓] Flutter (Channel dev, 1.26.0-1.0.pre, on Microsoft Windows [Version 10.0.19041.685], locale ru-RU)
    • Flutter version 1.26.0-1.0.pre at C:\flutter
    • Framework revision 63062a6443 (4 weeks ago), 2020-12-13 23:19:13 +0800
    • Engine revision 4797b06652
    • Dart version 2.12.0 (build 2.12.0-141.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at c:\Users\shent\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_SDK_ROOT = C:\Users\shent\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.52.1)
    • VS Code at C:\Users\shent\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.18.0

[✓] Connected device (2 available)
    • SM N960F (mobile) • 2aaa49c4473f7ece • android-arm64  • Android 10 (API 29)
    • Edge (web)        • edge             • web-javascript • Microsoft Edge 87.0.664.66

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 1ad9baa8b99a2897c20f9e6e54d3b9b359ade314
### Plugins
connectivity-2.0.2
connectivity_for_web-0.3.1+4
connectivity_macos-0.1.0+7
device_info-1.0.0
flutter_keyboard_visibility-4.0.2
flutter_keyboard_visibility_web-1.0.1
flutter_native_timezone-1.0.4
flutter_plugin_android_lifecycle-1.0.11
image_picker-0.6.7+17
image_picker_for_web-0.1.0+2
path_provider-1.6.24
path_provider_linux-0.0.1+2
path_provider_macos-0.0.4+6
path_provider_windows-0.0.4+3
permission_handler-5.0.1+1
phone_number-0.6.3
qrscan-0.2.21
sensors-0.4.2+6
share-0.6.5+4
shared_preferences-0.5.12+4
shared_preferences_linux-0.0.2+4
shared_preferences_macos-0.0.1+11
shared_preferences_web-0.1.2+7
shared_preferences_windows-0.0.1+3
sqflite-1.3.2+1
url_launcher-5.7.10
url_launcher_linux-0.0.1+4
url_launcher_macos-0.0.1+9
url_launcher_web-0.1.5+1
url_launcher_windows-0.0.1+3

**Comment by darshankawar** [comment] 2021-01-07 09:17
Closing this as duplicate of https://github.com/flutter/flutter/issues/73356

**Closed by darshankawar** 2021-01-07 09:17 UTC
