### ISSUE TITLE
When the ios app is launched after receiving a silent push notification png images are pink;

### ISSUE THREAD

**Issue by befirst** [flutter/flutter#127392] opened 2023-05-23 14:29 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Integrate the ios version of the app to receive push notifications (turn on background modes etc.);
2. Prepare and install a release build; 
3. Send a push notification with `content-available: 1`.
4. Wait while the app receives the push notification;
5. Open the app;

P.S  I realized that the problem is connected with push notification handling because I also sent `badge : 100`, and I have a sync with my server which response with 0 for now, so the app set the badge to 0 after the push comes;

Links to other similar issues: 
- https://github.com/flutter/flutter/issues/114594
- https://github.com/flutter/flutter/issues/64558
- https://github.com/flutter/flutter/issues/71074

### Expected results

The app is launched and all the images are displayed correctly;

### Actual results

The app is launched, but some images are pink;

After relaunching the app everything is ok;

### No Code sample yet

I hope someone will be able to understand what is the problem, but anyway, I will try to post the reproducible repo a little bit later;

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[I had to blur some parts of the app, but anyway you can see there are normal images and pink images]

https://github.com/flutter/flutter/assets/6989126/4a9c73ff-0e04-4ab2-8563-a0d2a98bf9fc

</details>

### No Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.1, on macOS 13.3.1 22E772610a darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.77.3)
[✓] Connected device (4 available)
[✓] Network resources

• No issues found!

```

</details>

**Comment by befirst** [comment] 2023-05-23 14:36
As far as I understand the app launches after it receives a silent push, and the first piece of images that are trying to be rendered are getting pink, all other images after navigation to other parts of the app look ok.

**Comment by darshankawar** [comment] 2023-05-24 06:43
Thanks for the report @befirst 
Can you provide us a complete minimal reproducible code sample or a repo that we can clone and run locally to verify the behavior ? Also please provide the payload you are sending.

Are you using `firebase_messaging` plugin to trigger push notifications ? And if so, is it only occuring while using this plugin ?
If yes and it is only occuring with the said plugin, you might need to report this in https://github.com/firebase/flutterfire/issues

If not and is specific to framework itself, then we would need required code sample that we can use to verify the reported behavior.

**Comment by dagovalsusa** [comment] 2023-05-24 07:15
Hi,
same bug here!
As @befirst mentioned, it seems it is a regression, and there is difficult to reproduce, or give you a sample code to test, because the pink image are displayed after many hours that app remains in the background. 
In my case the silent notification of firebase_messaging doesn't exists, and the image are loaded from the assets using Image.asset or ImageProvider for DecorationImage.

**Comment by darshankawar** [comment] 2023-05-24 07:53
This seems to be a duplicate of https://github.com/flutter/flutter/issues/126878, so please follow-up in that issue for further updates. Closing as such.

**Closed by darshankawar** 2023-05-24 07:53 UTC
Labels: waiting for customer response, in triage
