### ISSUE TITLE
[local_auth][iOS]: `NotAvailable` error code is thrown when user taps on "Don't allow" while trying to allow FaceId recognition.

### ISSUE THREAD

**Issue by ankesh-kumar** [flutter/flutter#102734] opened 2022-04-28 08:30 UTC
Steps to reproduce:
- call localAuth.authenticate() in iOS device having face recognition only,
- It shows a dialog "Do you want to allow app to use Face Id " with two button " Don't allow " and "OK".
- Tap on " Don't allow ".

It will treat as code->  NotAvailable.
It should be treat with different code and should call the dialog again.

**Comment by darshankawar** [comment] 2022-04-28 12:08
@ankesh-kumar 
Thanks for the report. Although I don't have iOS device with face recognition, so can't verify this behavior at my end.


> It will treat as code-> NotAvailable.
> It should be treat with different code and should call the dialog again.

Does it mean, after tapping `Don't allow`, it throws `not available error ? If so, can you provide complete error log ?






> should call the dialog again.

You mean it should again show the dialog ? 

For example, if we deny any permission for an app by tapping `don't allow`, it doesn't show the dialog again right ?

**Comment by ankesh-kumar** [comment] 2022-04-28 15:06
@darshankawar 
I am using following code:
try {
      await localAuth.authenticate(
        localizedReason: l.appTitle,
        useErrorDialogs: true,
        biometricOnly: true,
      );
    } on PlatformException catch (e) {
      print(e.code);  **_// it is printing  "NotAvailable_**
    }


Biometric not available and Biometric is disallowed by the end-user are two complete different scenario. For both exception and message should be different. So, Developer can prompt message accordingly. Like if it is disallow , We can guide user to allow Face-Recognition from his device Settings. Hope it make sense.

**Comment by darshankawar** [comment] 2022-04-29 04:57
Thanks for the feedback. Keeping it open and labeling for further insights from the team.

**Comment by Krunal-Aubergine** [comment] 2022-12-28 10:09
@ankesh-kumar found any solution? I'm facing the same issue.

**Comment by jmagman** [comment] 2022-12-28 18:55
@LouiseHsu can you try this flow on top of your https://github.com/flutter/plugins/pull/6821 PR (local_auth_ios 1.0.11) and update this issue with your findings?

**Comment by LouiseHsu** [comment] 2022-12-29 21:44
Hi! After debugging this issue, I've discovered that this is working correctly, as this is in line with what Apple's API is returning. if an end user disallows biometrics to be used, it is intended behaviour that the app will not be able to determine if biometrics are supported on the device, thus the "NotAvailable". Closing the issue.

**Closed by LouiseHsu** 2022-12-29 21:44 UTC
Labels: platform-ios, plugin, p: first party, p: local_auth, P4
