### ISSUE TITLE
video player spews debug information to my app log, please reduce it!

### ISSUE THREAD

**Issue by robertflesch** [flutter/flutter#93736] opened 2021-11-16 21:04 UTC
Every time I play a video a get pages of debug info from the video player that I really dont need, and it significantly reduces the value of my logging. Can you do something to reduce it please!!

D/AudioManager( 3861): dispatching onAudioFocusChange(-1) to android.media.AudioManager@1823101com.google.android.exoplayer2.AudioFocusManager$AudioFocusListener@7235ba6
D/CCodecBuffers( 3861): [c2.android.aac.decoder#502:1D-Output.Impl[N]] Client returned a buffer it does not own according to our record: 0
D/CCodecBuffers( 3861): [c2.android.aac.decoder#502:1D-Output.Impl[N]] Client returned a buffer it does not own according to our record: 1
D/CCodecBuffers( 3861): [c2.android.aac.decoder#502:1D-Output.Impl[N]] Client returned a buffer it does not own according to our record: 2
D/CCodecBuffers( 3861): [c2.android.aac.decoder#502:1D-Output.Impl[N]] Client returned a buffer it does not own according to our record: 3
I/CCodecConfig( 3861): query failed after returning 19 values (BAD_INDEX)
D/CCodecConfig( 3861): c2 config diff is   c2::i32 coding.drc.compression-mode.value = 3
W/Codec2Client( 3861): query -- param skipped: index = 1342179345.
W/Codec2Client( 3861): query -- param skipped: index = 2415921170.
W/Codec2Client( 3861): query -- param skipped: index = 1610614798.
D/BufferPoolAccessor2.0( 3861): bufferpool2 0xf0bdd6d8 : 5(40960 size) total buffers - 5(40960 size) used buffers - 1/7 (recycle/alloc) - 11/711 (fetch/transfer)
D/CCodecBuffers( 3861): [c2.android.aac.decoder#502:Output[N]] popFromStashAndRegister: output format changed to AMessage(what = 0x00000000) = {
D/CCodecBuffers( 3861):   int32_t aac-drc-album-mode = 0
D/CCodecBuffers( 3861):   int32_t aac-drc-boost-level = 127
D/CCodecBuffers( 3861):   int32_t aac-drc-cut-level = 127
D/CCodecBuffers( 3861):   int32_t aac-drc-effect-type = 3
D/CCodecBuffers( 3861):   int32_t aac-drc-heavy-compression = 3
D/CCodecBuffers( 3861):   int32_t aac-drc-output-loudness = -1
D/CCodecBuffers( 3861):   int32_t aac-encoded-target-level = -1
D/CCodecBuffers( 3861):   int32_t aac-max-output-channel_count = 8
D/CCodecBuffers( 3861):   int32_t aac-target-ref-level = 64
D/CCodecBuffers( 3861):   int32_t channel-count = 2
D/CCodecBuffers( 3861):   string mime = "audio/raw"
D/CCodecBuffers( 3861):   int32_t sample-rate = 44100
D/CCodecBuffers( 3861): }
D/CCodecConfig( 3861): c2 config diff is   c2::i32 coding.drc.compression-mode.value = 1
D/CCodecBuffers( 3861): [c2.android.aac.decoder#502:Output[N]] popFromStashAndRegister: output format changed to AMessage(what = 0x00000000) = {
D/CCodecBuffers( 3861):   int32_t aac-drc-album-mode = 0
D/CCodecBuffers( 3861):   int32_t aac-drc-boost-level = 127
D/CCodecBuffers( 3861):   int32_t aac-drc-cut-level = 127
D/CCodecBuffers( 3861):   int32_t aac-drc-effect-type = 3
D/CCodecBuffers( 3861):   int32_t aac-drc-heavy-compression = 1
D/CCodecBuffers( 3861):   int32_t aac-drc-output-loudness = -1
D/CCodecBuffers( 3861):   int32_t aac-encoded-target-level = -1
D/CCodecBuffers( 3861):   int32_t aac-max-output-channel_count = 8
D/CCodecBuffers( 3861):   int32_t aac-target-ref-level = 64
D/CCodecBuffers( 3861):   int32_t channel-count = 2
D/CCodecBuffers( 3861):   string mime = "audio/raw"
D/CCodecBuffers( 3861):   int32_t sample-rate = 44100
D/CCodecBuffers( 3861): }
D/AudioTrack( 3861): getTimestamp_l(21): device stall time corrected using current time 8797430296200
D/BufferPoolAccessor2.0( 3861): bufferpool2 0xf0bca4d8 : 5(40960 size) total buffers - 5(40960 size) used buffers - 1/7 (recycle/alloc) - 11/632 (fetch/transfer)
D/BufferPoolAccessor2.0( 3861): evictor expired: 1, evicted: 1

**Comment by maheshmnj** [comment] 2021-11-17 07:51
Closing as a duplicate of https://github.com/flutter/flutter/issues/59579.

**Closed by maheshmnj** 2021-11-17 07:51 UTC
Labels: in triage
