### ISSUE TITLE
Provide Text with the feature to mark specified text with phonetic notation

### ISSUE THREAD

**Issue by JamesChenX** [flutter/flutter#26744] opened 2019-01-18 07:50 UTC
![123](https://user-images.githubusercontent.com/44962329/51372521-85e4e580-1b38-11e9-815b-bff806d4432f.png)

I need to mark specified text with notation just like the picture shows, but it seems Text do not have the feature.

**Comment by GaryQian** [comment] 2020-05-19 10:06
This is a duplicate of https://github.com/flutter/flutter/issues/20220

Let's close this and track it over there!

**Closed by GaryQian** 2020-05-19 10:06 UTC
Labels: a: typography, engine, framework, severe: new feature
