### ISSUE TITLE
problem with firebase auth when i added to pubspec.yaml

### ISSUE THREAD

**Issue by ahmadshihab** [flutter/flutter#56460] opened 2020-05-06 17:20 UTC
Launching lib\main.dart on Android SDK built for x86 in debug mode...
Running Gradle task 'assembleDebug'...
Parameter format not correct -

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':firebase_core:javaPreCompileDebug'.
> Could not resolve all files for configuration ':firebase_core:debugCompileClasspath'.
   > Could not find firebase-common.jar (com.google.firebase:firebase-common:16.1.0).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/google/firebase/firebase-common/16.1.0/firebase-common-16.1.0.jar
   > Could not find legacy-support-v4.jar (androidx.legacy:legacy-support-v4:1.0.0).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/androidx/legacy/legacy-support-v4/1.0.0/legacy-support-v4-1.0.0.jar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 13s
The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.
Building plugin firebase_auth...
Running Gradle task 'assembleAarRelease'...

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'firebase_auth'.
> SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s

Exception: The plugin firebase_auth could not be built due to the issue above.

**Comment by Alifyz** [comment] 2020-05-06 17:42
Hi, it seems that you are facing issues with AndroidX, have you tried to migrate to Androidx? 

Maybe the following link could help: 
https://flutter.dev/docs/development/androidx-migration

There are a few versions of Firebase plugins that are only compatible with Androidx.

**Comment by ahmadshihab** [comment] 2020-05-06 18:03
@Alifyz 
nothing change 
![التقاط](https://user-images.githubusercontent.com/62830331/81211998-e1acd980-8fdc-11ea-9366-54a2c10030c9.PNG)

**Comment by mohak852** [comment] 2020-05-06 18:21
So it's a common bug where the android studio says "No usage found in the project ". So in this condition, you have to  manually migrate to android 
here is a link where you can migrate it to androidX manually 
https://flutter.dev/docs/development/androidx-migration

**Comment by Alifyz** [comment] 2020-05-07 11:54
@ahmadshihab any progress on your problem?

**Comment by TahaTesser** [comment] 2020-05-07 13:54
Hi @ahmadshihab 
for what I can see the issue is related to a FlutterFire plugin, please open the issue in the dedicated [GitHub](https://github.com/FirebaseExtended/flutterfire/issues). 
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
thank you

**Closed by TahaTesser** 2020-05-07 13:54 UTC
