### ISSUE TITLE
WhitelistingTextInputFormatter has issues with a signed integer regex.

### ISSUE THREAD

**Issue by cbenhagen** [flutter/flutter#21874] opened 2018-09-14 12:11 UTC
This code should allow the input of negative integers.

```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: TextFormField(
            keyboardType: TextInputType.numberWithOptions(
              decimal: false,
              signed: true,
            ),
            inputFormatters: [
              WhitelistingTextInputFormatter(RegExp(r'^-?\d+')),
            ],
          ),
        ),
      ),
    );
  }
}
```

The regex is valid and the following prints `true`:
```dart
void main() {
  RegExp exp = new RegExp(r"^-?\d+");
  String str = "-123";
  Iterable<Match> matches = exp.allMatches(str);
  print(matches.length == 1);
}
```

**Comment by zoechi** [comment] 2018-09-15 10:59
Please add the output of `flutter doctor -v`.

**Comment by zoechi** [comment] 2019-02-14 14:22
```
/// A [TextInputFormatter] that allows only the insertion of whitelisted
/// characters patterns.
```
Your regex does not allow `"-"` so the  formatter rejects it.

Closing as working as intended.

**Closed by zoechi** 2019-02-14 14:22 UTC
Labels: f: material design, framework

**Comment by ollydixon** [comment] 2019-12-01 10:58
Does anyone have the correct solution here?

**Comment by petergulliver** [comment] 2020-03-23 23:13
Anyone manage to solve this? I have tried several valid regex expressions that should allow a signed integer and all of them fail to allow the leading '-'. the OPs regex appears to be valid too.

**Comment by Marvioso** [comment] 2020-09-04 19:12
Took me forever to figure this out. You can use:
FilteringTextInputFormatter.allow(RegExp(r'^-?(?:-?(?:[0-9]+))?(?:\.[0-9]*)?(?:[eE][\+\-]?(?:[0-9]+))?'))

or if you want it to be strict and clear the field if an invalid key is pressed, use:

FilteringTextInputFormatter.allow(RegExp(r'^-?(?:-?(?:[0-9]+))?(?:\.[0-9]*)?(?:[eE][\+\-]?(?:[0-9]+))?$'))
