### ISSUE TITLE
After taking an image through a Camera or gallery the app will be crashed in the android device.

### ISSUE THREAD

**Issue by vinodlee** [flutter/flutter#125030] opened 2023-04-18 10:37 UTC
I got this error, Am using image_picker 

D/AndroidRuntime(15710): Shutting down VM
E/AndroidRuntime(15710): FATAL EXCEPTION: main
E/AndroidRuntime(15710): Process: com.imdaad.com.CustomerMobileApp, PID: 15710
E/AndroidRuntime(15710): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=2343, result=-1, data=null} to activity {com.imdaad.com.CustomerMobileApp/com.mhidubai.com.rpf_customer_mobile_app.MainActivity}: kotlin.UninitializedPropertyAccessException: lateinit property mresult has not been initialized
E/AndroidRuntime(15710): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4178)
E/AndroidRuntime(15710): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4221)
E/AndroidRuntime(15710): 	at android.app.ActivityThread.-wrap20(ActivityThread.java)
E/AndroidRuntime(15710): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1583)
E/AndroidRuntime(15710): 	at android.os.Handler.dispatchMessage(Handler.java:110)
E/AndroidRuntime(15710): 	at android.os.Looper.loop(Looper.java:203)
E/AndroidRuntime(15710): 	at android.app.ActivityThread.main(ActivityThread.java:6251)
E/AndroidRuntime(15710): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(15710): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
E/AndroidRuntime(15710): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)
E/AndroidRuntime(15710): Caused by: kotlin.UninitializedPropertyAccessException: lateinit property mresult has not been initialized
E/AndroidRuntime(15710): 	at com.media.storage.media_storage.MethodCallHandlerImpl.getMresult(MethodCallHandlerImpl.kt:60)
E/AndroidRuntime(15710): 	at com.media.storage.media_storage.MethodCallHandlerImpl.onActivityResult(MethodCallHandlerImpl.kt:291)
E/AndroidRuntime(15710): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEngineConnectionRegistry.java:807)
E/AndroidRuntime(15710): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onActivityResult(FlutterEngineConnectionRegistry.java:430)
E/AndroidRuntime(15710): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:811)
E/AndroidRuntime(15710): 	at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:771)
E/AndroidRuntime(15710): 	at android.app.Activity.dispatchActivityResult(Activity.java:6919)
E/AndroidRuntime(15710): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4174)
E/AndroidRuntime(15710): 	... 9 more
I/art     (15710): Enter while loop.
Lost connection to device.

**Comment by danagbemava-nc** [comment] 2023-04-18 13:24
Closing this as a duplicate of https://github.com/flutter/flutter/issues/123201.

**Closed by danagbemava-nc** 2023-04-18 13:24 UTC
Labels: in triage
