### ISSUE TITLE
Upgrade Flutter 1.12.13+hotfix.5, assets has some error

### ISSUE THREAD

**Issue by xiaobaogeit** [flutter/flutter#47064] opened 2019-12-15 04:34 UTC
### Error will be reported when the path contains spaces.When I remove the space, it's OK, but 1.9 is OK
```
E/flutter (11052): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: Unable to load asset: assets/some test/som test.json
E/flutter (11052): #0      PlatformAssetBundle.load 
package:flutter/…/services/asset_bundle.dart:221
```

### flutter doctor -v
```
  [√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.18363.535], locale zh-CN)
    • Flutter version 1.12.13+hotfix.5 at C:\***\flutter
    • Framework revision 27321ebbad (4 days ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0        

 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\***\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 40.0.2
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.41.0)
    • VS Code at C:\Users\***\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.7.1

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!
```

**Comment by iapicca** [comment] 2019-12-16 10:07
Hi @xiaobaogeit 
could you please run
`flutter clean`
`flutter pub cache repair`
let me know if this solves your issue
thank you

**Comment by xiaobaogeit** [comment] 2019-12-16 15:02
@iapicca I tried, but I still haven't solved my problem

**Comment by mhaggag** [comment] 2019-12-16 15:03
FWIW, I ran into the same problem. It seemed to be inconsistent--cleaning and rebuilding sometimes worked. We ended up replacing all spaces with dashes to work around this.

**Comment by iapicca** [comment] 2019-12-16 15:06
Hi again @xiaobaogeit 
could you please provide your `flutter run --verbose`
thank you

**Comment by jason-simmons** [comment] 2019-12-18 23:53
This may be a duplicate of https://github.com/flutter/flutter/issues/47064

**Comment by dnfield** [comment] 2019-12-19 00:34
I believe this is a duplicate of that bug.  @xiaobaogeit can you try this in your flutter repo:

```
git revert 383e90eb13bdc50ca0cce9f2575329ba8593506e     
```

And see if that fixes it?

**Comment by xiaobaogeit** [comment] 2019-12-19 05:11
@iapicca @jason-simmons @dnfield  
I tried. It can solve the problem. After upgrading 1.12.13 + hotfix.5, I found that there are always error prompts for each run, but there are no errors in actual use. Or I just solved this error, I don't know if it is caused by cache.

**Comment by dnfield** [comment] 2019-12-19 05:22
@xiaobaogeit if you're getting other errors let's open a new bug for it.  For this one I'm going to close it as a duplicate of #46163

**Closed by dnfield** 2019-12-19 05:22 UTC
Labels: severe: regression, tool
