### ISSUE TITLE
// coverage:ignore-line Doesn't Work Properly

### ISSUE THREAD

**Issue by MelbourneDeveloper** [flutter/flutter#97759] opened 2022-02-04 02:30 UTC
<details>
<summary>flutter doctor -v</summary>

```console
[√] Flutter (Channel stable, 2.8.1, on Microsoft Windows [Version 10.0.19044.1466], locale en-AU)
    • Flutter version 2.8.1 at C:\tools\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (7 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1
```

</details>

The original problem here. It looks like it was fixed but may have been broken since.
https://github.com/flutter/flutter/issues/76544

Steps to reproduce:
- Create a fresh flutter app with the standard template
- Install the LCOV perl tool. On windows: `choco install lcov`
- Ignore the runapp line like this

```dart
void main() {
  runApp(const MyApp()); // coverage:ignore-line
}
```

- Run the test, and generate the report. You can do it like this on Windows.
`flutter test --coverage & perl C:\ProgramData\chocolatey\lib\lcov\tools\bin\lcov coverage/lcov.info -o coverage\lcov.info & perl C:\ProgramData\chocolatey\lib\lcov\tools\bin\genhtml -o coverage\html coverage\lcov.info`

The report doesn't ignore the line and it's red.
![image](https://user-images.githubusercontent.com/16697547/152462600-6252f815-64b0-4366-9f16-a62167ba1884.png)

**Comment by danagbemava-nc** [comment] 2022-02-04 13:18
Hi @MelbourneDeveloper, there was also a similar issue reported in https://github.com/flutter/flutter/issues/95791 and presumably, that has been fixed with `coverage: 1.1.0`, see https://github.com/flutter/flutter/issues/95791#issuecomment-1015835567. 

Can you upgrade to `coverage: 1.1.0` to see if the issue is fixed?

**Comment by MelbourneDeveloper** [comment] 2022-02-05 04:22
@danagbemava-nc I tried it but it makes no difference.

**Comment by danagbemava-nc** [comment] 2022-02-07 07:27
Kindly report this to the coverage repo over [here](https://github.com/dart-lang/coverage/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc).

I'm going to have to close this because the coverage has its own dedicated repo and I believe that would be the best place for this issue to be filed. 

Thank you

**Closed by danagbemava-nc** 2022-02-07 07:27 UTC
Labels: in triage
