### ISSUE TITLE
Null check operator used on a null value. Error thrown null. at State.context(framework.dart:916) with flutter_local_notification

### ISSUE THREAD

**Issue by lelam2808** [flutter/flutter#122073] opened 2023-03-07 04:31 UTC
I can not give you any reproducible code because this error is caught by runZonedGuarded(error; stackTrace) method and reported to application's server. I've tried to recreate it myself but i have no idea how it appears. 
FlutterError: Null check operator used on a null value. Error thrown null.
       at State.context(framework.dart:916)
       at setNotificationAlarm
setNotificationAlarm is a method that i create notification follow flutter plugin FlutterLocalNotification (https://pub.dev/packages/flutter_local_notifications)
**Platform: Windows, Flutter version: 2.5.1 from stable channel**

**Comment by hoangnm-Rikkei** [comment] 2023-03-07 04:35
I have the same issue!!

**Comment by vanmy5198** [comment] 2023-03-07 04:38
i have the same issue with IOS device 
Non-fatal Exception: FlutterError
```
0  ???                            0x0 State.context + 916 (framework.dart:916)
1  ???                            0x0 setSubmitNotificaton
2  ???                            0x0 checkHandleSchedule
3  ???                            0x0 _CustomZone.bindCallback.<fn> (dart:async)
4  ???                            0x0 SemanticsConfiguration._addArgumentlessAction.<fn> + 3155 (semantics.dart:3155)
```

**Comment by lelam2808** [comment] 2023-03-07 04:39
> i have the same issue with IOS device Non-fatal Exception: FlutterError
> 
> ```
> 0  ???                            0x0 State.context + 916 (framework.dart:916)
> 1  ???                            0x0 setSubmitNotificaton
> 2  ???                            0x0 checkHandleSchedule
> 3  ???                            0x0 _CustomZone.bindCallback.<fn> (dart:async)
> 4  ???                            0x0 SemanticsConfiguration._addArgumentlessAction.<fn> + 3155 (semantics.dart:3155)
> ```

i think it is a big problem => waiting for support

**Comment by lndphuong1205** [comment] 2023-03-07 04:40
same!! help me pls

**Comment by exaby73** [comment] 2023-03-08 11:10
@lelam2808 Have you solved you issue? If so, would you be kind enough to provide information about how you did so for future reference for other developers?

**Comment by lelam2808** [comment] 2023-03-08 13:51
Im so sorry, but it has not been solved yet. 

> @lelam2808 Have you solved you issue? If so, would you be kind enough to provide information about how you did so for future reference for other developers?

Im so sorry, but it has not been solved yet.
I am using
```
var androidDetails = new AndroidNotificationDetails(
  "notification 1",
  "App Notification 1",
  "Notification 1",
  importance: Importance.max,
  priority: Priority.high,
  color: Colors.blue,
  playSound: true,
  // timeoutAfter: 5000,
);
var iSODetails = new IOSNotificationDetails();
var generalNotificationDetails =
    new NotificationDetails(android: androidDetails, iOS: iSODetails);

await flutterLocalNotificationsPlugin.zonedSchedule(
  0,
  "App",
  "Notification",
  time,
  generalNotificationDetails,
  androidAllowWhileIdle: true,
);}
```
to create notification in my app, but this problem has been accrued.
Bellow is my flutter doctor -v.
![image](https://user-images.githubusercontent.com/57362237/223730160-2308fa53-c2cc-4c02-afba-bb95d3c3bbe9.png)

**Comment by exaby73** [comment] 2023-03-09 07:06
Looks like an issue with the plugin itself and not Flutter. I suggest you raise this issue on https://github.com/MaikuB/flutter_local_notifications/issues. Closing this issue as this is not an issue with Flutter itself

**Closed** 2023-03-09 07:06 UTC
Labels: r: invalid, in triage

**Comment by lelam2808** [comment] 2023-03-16 04:17
> Looks like an issue with the plugin itself and not Flutter. I suggest you raise this issue on https://github.com/MaikuB/flutter_local_notifications/issues. Closing this issue as this is not an issue with Flutter itself

@exaby73 it seem not the issue in flutter_local_notification library, the issue accurate because _element is null, but i really don't know _element null, if _element  is null
```
 BuildContext get context {
    assert(() {
      if (_element == null) {
        throw FlutterError(
          'This widget has been unmounted, so the State no longer has a context (and should be considered defunct). \n'
          'Consider canceling any active work during "dispose" or using the "mounted" getter to determine if the State is still active.',
        );
      }
      return true;
    }());
    return _element!;
  }
  StatefulElement? _element;
```

**Comment by exaby73** [comment] 2023-03-17 07:41
Is this happening onBackground or onForeground?

**Comment by lelam2808** [comment] 2023-03-17 07:49
> Is this happening onBackground or onForeground?
@exaby73 
It happen when app onBackground

**Comment by exaby73** [comment] 2023-03-17 08:23
Where are you getting the `context` from?

**Comment by lelam2808** [comment] 2023-03-17 08:31
> Where are you getting the `context` from?
@exaby73 
I pass Context from view and give into view_model, in view_model Im using context into function to create notification.

**Comment by lelam2808** [comment] 2023-03-17 08:36
I think the cause is view disposed before function create notification that mean: 
`BuildContext get context {
    assert(() {
      if (_element == null) {
        throw FlutterError(
          'This widget has been unmounted, so the State no longer has a context (and should be considered defunct). \n'
          'Consider canceling any active work during "dispose" or using the "mounted" getter to determine if the State is still active.',
        );
      }
      return true;
    }());
    return _element!; (***)
  }
  StatefulElement? _element;`
throw FlutterError, but i dont understand why I received message Error thrown null. at State.context(framework.dart:916) (***)

**Comment by exaby73** [comment] 2023-03-17 13:57
Unfortunately, this looks like a user error. This is working as intended. I suggest you find help on Stackoverflow or find places to ask questions like this on https://flutter.dev/community
