### ISSUE TITLE
Problem with latin characters ČĐ in ListTile Title

### ISSUE THREAD

**Issue by Odorian** [flutter/flutter#55297] opened 2020-04-21 13:40 UTC
ListTile(
                leading: Container(
                  width: 40, // can be whatever value you want
                  alignment: Alignment.center,

                ),
                 title: Text('ČčĐđ'),
                subtitle: Text('ČčĐđ'),
              ); }
        ));

![gi](https://user-images.githubusercontent.com/64084646/79872858-9b555900-83e6-11ea-90a4-b266d6252936.png)

As u see if i put those letters anywhere else it works fine but in ListTile-Title it gives strange output.I using last version of sdk.This letters is serbo-croatian.I lost all day try too figure what is problem...

**Comment by VladyslavBondarenko** [comment] 2020-04-21 14:21
Checked with `dev v1.18.0-dev.5.0` on Android 10 (API 29) (emulator) and iOS 13.4.5, characters are shown as intended

<details>
 <summary>this code sample</summary>
 
```
import 'package:flutter/material.dart';

void main() => runApp(TestApp());

class TestApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: ListView(
          children: const <Widget>[
            Card(
              child: ListTile(
                title: Text('ČčĐđ'),
                subtitle: Text('ČčĐđ'),
              ),
            ),
          ],
        ),
      ),
    );
  }
}
```

</details>

**Comment by HansMuller** [comment] 2020-04-21 14:23
@VladyslavBondarenko - could you try reducing the test case further? It seems like the problem should reduce to just a Text widget configured with the default font used by ListTile

**Comment by VladyslavBondarenko** [comment] 2020-04-21 14:44
@HansMuller 
I'm not sure I can do it correctly when I can't reproduce it with ListTile.

@Odorian 
are you experiencing the issue with my code sample? 
if no, could you edit it to reproduce?
and provide please your `flutter doctor -v`

**Comment by HansMuller** [comment] 2020-04-21 15:09
@VladyslavBondarenko - Sorry about that, I misread your comment!

**Comment by TahaTesser** [comment] 2020-07-09 10:51
Hi @Odorian 
Not able ti reproduce this issue on physical device or emulator

### Physical device
![flutter_03](https://user-images.githubusercontent.com/48603081/87031025-10734600-c200-11ea-85cf-40e4de4617b7.png)

### Emulator device
<img width="194" alt="Screenshot 2020-07-09 at 4 20 27 PM" src="https://user-images.githubusercontent.com/48603081/87031092-2aad2400-c200-11ea-9ed9-ec4d79d8e7ba.png">



<details> 
<summary>Code Sample</summary> 

``` 
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: new AppBar(
        title: new Text('ČČČČČččč'),
      ),
      body: ListView(
        children: const <Widget>[
          Card(
            child: ListTile(
              title: Text('ČčĐđ'),
              subtitle: Text('ČčĐđ'),
            ),
          ),
        ],
      ),
    );
  }
}

``` 

</details> 

<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel dev, 1.20.0-3.0.pre, on Mac OS X 10.15.5 19F101, locale
    en-GB)
    • Flutter version 1.20.0-3.0.pre at /Users/taha/Code/flutter_dev
    • Framework revision 0af027f805 (5 days ago), 2020-07-04 12:19:20 -0700
    • Engine revision a751393804
    • Dart version 2.9.0 (build 2.9.0-20.0.dev 22da8934ac)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/taha/Code/sdk
    • Platform android-30, build-tools 30.0.0
    • ANDROID_HOME = /Users/taha/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.1

[✓] Connected device (4 available)
    • SM M305F (mobile)      • 32003c30dc19668f          • android-arm64  •
      Android 10 (API 29)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios            • iOS
      13.5.1
    • Web Server (web)       • web-server                • web-javascript •
      Flutter Tools
    • Chrome (web)           • chrome                    • web-javascript •
      Google Chrome 83.0.4103.116

• No issues found!
``` 

</details> 

Are you still experiencing this issue on latest `dev` channel? 
If yes, please provide `flutter doctor -v` with latest `dev`
Thank you

**Comment by TahaTesser** [comment] 2020-08-05 14:25
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

**Closed by TahaTesser** 2020-08-05 14:25 UTC
