### ISSUE TITLE
[WEB] Images loaded into UI from network doesn't apply EXIF rotation

### ISSUE THREAD

**Issue by uKL** [flutter/flutter#33572] opened 2019-05-30 12:00 UTC
I've seen several issues from the past that were addressing similar issues for iOS and Android - they were already fixed. 

# Sample data
An image file took on an iPhone that contains EXIF `rotation 180` value. Full EXIF:

```
Camera make : Apple
Camera model : iPhone 7
Date/Time :2018/08/24 08:25:22
Resolution : 4032 x 3024
Orientation : rotate 180
Flash used : No
Focal length : 4.0mm (35mm equivalent 28mm)
Exposure time : 0.0004 s (1/2283)
Aperture : f/1.8ISO equiv. : 4000
Whitebalance : Auto
Metering Mode : pattern
Exposure : program (auto)
GPS Latitude :N 43º 0' 34.15"GPS 
Longitude :E 17º 16' 4.81"GPS 
Altitude : 5.26m
```

# Steps to reproduce
1. Create an empty Flutter Web project
2. Create one widget `Image.network('URL to the image');`

# Observed
1. Image is displayed without EXIF rotation being applied

# Expected
1. Image is rotated according to the stored rotation value

# Other
1. The same file, reproduction scenario in Flutter Android behaves correctly - image is rotated.

**Comment by ferhatb** [comment] 2019-11-08 07:09
Thanks for reporting. Unfortunately this is only possible by decoding image file. Due to cross-origin restrictions on the web, it is not possible unless browsers provide support or the image is an asset (non-network). We will forward request to Fugu/Chrome team to prioritize. See https://developer.mozilla.org/en-US/docs/Web/CSS/image-orientation. I'll leave issue open for now.

**Comment by TahaTesser** [comment] 2020-11-06 12:59
On iOS 14, by default images are HEIC, which isn't supported yet https://github.com/flutter/flutter/issues/20522 hence i can't test this

**Comment by pedromassangocode** [comment] 2020-11-17 11:27
Was able to reproduce on `master` channel, following the steps in Rotated image on Flutter web with CanvasKit #70620.

<details><summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.24.0-8.0.pre.267, on Mac OS X 10.15.7 19H2
    darwin-x64, locale en)
    • Flutter version 1.24.0-8.0.pre.267 at
      /Users/pedromassango/dev/SDKs/flutter_master
    • Framework revision 22e576fa26 (11 hours ago), 2020-11-16 18:48:03 -0500
    • Engine revision f0e80100f7
    • Dart version 2.12.0 (build 2.12.0-49.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 51.0.3
    • Dart plugin version 202.8070

[✓] VS Code (version 1.51.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (4 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11
      (API 30) (emulator)
    • macOS (desktop)             • macos         • darwin-x64     • Mac OS X
      10.15.7 19H2 darwin-x64
    • Web Server (web)            • web-server    • web-javascript • Flutter
      Tools
    • Chrome (web)                • chrome        • web-javascript • Google
      Chrome 86.0.4240.198

• No issues found!

```
</details>

**Comment by TahaTesser** [comment] 2020-11-19 13:39
Remove labels based on https://github.com/flutter/flutter/issues/70620#issuecomment-730379278

**Comment by ferhatb** [comment] 2020-12-10 18:34
duplicate of https://github.com/flutter/flutter/issues/53820

**Closed by ferhatb** 2020-12-10 18:34 UTC
Labels: P5, a: images, e: web_canvaskit, engine, passed first triage, platform-web, severe: rendering
