### ISSUE TITLE
Flutter web is stuck at the initialization loading

### ISSUE THREAD

**Issue by armin1440** [flutter/flutter#120347] opened 2023-02-09 08:33 UTC
I have provided a loading animation for my flutter web application so that user will not think that the web application is frozen. The problem is when I open my web application for the first time and there is no cache or anything similar on my pc, it displays the loading animation and the animation will stay there forever. Even when there is no http request on flight. Please notice that this problem does not always occur.
Here is my flutter doctor output:

```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.0, on macOS 12.1 21C52 darwin-x64, locale en-US)                                                                       Checking Android licenses is taking an unexpectedly long time...[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

• No issues found!
```

This is my index.html file:

```
<!DOCTYPE html>
<html>
<head>
  <!--
    If you are serving your web app in a path other than the root, change the
    href value below to reflect the base path you are serving from.

    The path provided below has to start and end with a slash "/" in order for
    it to work correctly.

    For more details:
    * https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base

    This is a placeholder for base href that will be replaced by the value of
    the `--base-href` argument provided to `flutter build`.
  -->
  <base href="$FLUTTER_BASE_HREF">

  <meta charset="UTF-8">
  <meta content="IE=Edge" http-equiv="X-UA-Compatible">
  <meta name="description" content="A new Flutter project.">

  <!-- iOS meta tags & icons -->
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  <meta name="apple-mobile-web-app-title" content="weight_and_balance">
  <link rel="apple-touch-icon" href="icons/Icon-192.png">

  <!-- Favicon -->
  <link rel="icon" type="image/png" href="favicon.png"/>

  <title>weight_and_balance</title>
  <link rel="manifest" href="manifest.json">

  <script>
    // The value below is injected by flutter build, do not touch.
    var serviceWorkerVersion = null;
  </script>
  <!-- This script adds the flutter initialization JS code -->
  <script src="flutter.js" defer></script>

  <style>
    :root {
	    --yellow: #5194C0;
	    --red: #2D6AAB;
	    --blue: #164588;
	    --violet: #0E3476;
    }
    	body {
    	margin: 0;
    	display: flex;
    	justify-content: center;
    	align-items: center;
    	height: 100vh;
    	background-color: #D5E6EF;
      background-image: linear-gradient(180deg, rgba(0,0,0,0.15) 0%, rgba(0,153,212,0) calc(15% + 100px), rgba(0,99,138,0) calc(85% + 100px), rgba(0,0,0,0.15) 100%);
    }
    div.container {
    	display: flex;
    	justify-content: center;
    	align-items: center;
    }
    div > div {
    	width: 2vw;
    	height: 2vw;
    	border-radius: 100%;
    	margin: 2vw;
    	background-image: linear-gradient(145deg, rgba(255,255,255,0.5) 0%, rgba(0,0,0,0) 100%);
    	animation: bounce 1.5s 0.5s linear infinite;
    }
    .yellow {
    	background-color: var(--yellow);
    	animation-delay: 0.0s;
    }

    .red {
    	background-color: var(--red);
    	animation-delay: 0.15s;
    }

    .blue {
    	background-color: var(--blue);
    	animation-delay: 0.3s;
    }

    .violet {
    	background-color: var(--violet);
    	animation-delay: 0.45s;
    }

    @keyframes bounce {
    	0%, 50%, 100% {
    		transform: scale(1);
    	}
    	25% {
    		transform: scale(0.8);
    	}
    	75% {
    		transform: scale(1.2);
    	}
    }
  </style>
</head>

<body>
<div class="container" id="loading">
  <div class="yellow"></div>
  <div class="red"></div>
  <div class="blue"></div>
  <div class="violet"></div>
</div>
  <script>
    window.addEventListener('load', function(ev) {
      var loading = document.querySelector('#loading');
      // Download main.dart.js
      _flutter.loader.loadEntrypoint({
        serviceWorker: {
          serviceWorkerVersion: serviceWorkerVersion,
        },
        onEntrypointLoaded: function(engineInitializer) {
          engineInitializer.initializeEngine().then(function(appRunner) {
            loading.remove();
            appRunner.runApp();
          });
        }
      });
    });
  </script>
</body>
</html>

```

**Comment by bilalalmofleh** [comment] 2023-02-09 10:10
remove this line 
  <base href="$FLUTTER_BASE_HREF">
from index file 
its work for me

**Comment by armin1440** [comment] 2023-02-09 10:35
> remove this line
> 
> from index file its work for me

What do you mean by "this line"? Can you be more specific?

**Comment by huycozy** [comment] 2023-02-09 10:46
@armin1440 I tried running the project with your `index.html` file several times, but can not reproduce this issue. 

Which host platform are you running the web on? Please provide the output of `flutter doctor -v` as well. Thanks!

Also, you may try removing the `loading` same as in this gallery [index.html](https://github.com/flutter/gallery/blob/master/web/index.html) example to see if it works.

**Comment by armin1440** [comment] 2023-02-09 12:38
> @armin1440 I tried running the project with your `index.html` file several times, but can not reproduce this issue.
> 
> Which host platform are you running the web on? Please provide the output of `flutter doctor -v` as well. Thanks!
> 
> Also, you may try removing the `loading` same as in this gallery [index.html](https://github.com/flutter/gallery/blob/master/web/index.html) example to see if it works.

Please try it with poor internet connection and with no cached data. It takes about couple of minutes for me to download needed data at the beginning. As I said earlier, It occasionally happens.
This is a screenshot of my browser. After a minute, no progress is made in http requests because they are all done and there is no request on flight.
![Screen Shot 2023-02-09 at 12 07 14](https://user-images.githubusercontent.com/60127896/217800915-c29afea2-d760-486e-b6f8-18f8b903f391.png)

**Comment by huycozy** [comment] 2023-02-10 03:37
@armin1440 Can you confirm you are testing on a new Flutter project and only modifying the `index.html` file as above? That would be appreciated if you could provide a recorded video for this. 

Can you also help to check this when using `html` or `canvaskit` renderer? It seems that it may be faster if you use `html` renderer (https://github.com/flutter/flutter/issues/76009#issuecomment-781681343)

May be related/similar to https://github.com/flutter/flutter/issues/76009. Please take a look at this issue and comments to see if it's similar to your case.

**Comment by armin1440** [comment] 2023-02-12 13:27
> @armin1440 Can you confirm you are testing on a new Flutter project and only modifying the `index.html` file as above? That would be appreciated if you could provide a recorded video for this.
> 
> Can you also help to check this when using `html` or `canvaskit` renderer? It seems that it may be faster if you use `html` renderer ([#76009 (comment)](https://github.com/flutter/flutter/issues/76009#issuecomment-781681343))
> 
> May be related/similar to #76009. Please take a look at this issue and comments to see if it's similar to your case.

Yes, I confirm that. 
I tried `html` and `canvaskist`. The problem occurs when I use `canvaskit`. The #76009 is similar to my issue but here I am stuck at the loading and I'm emphasizing on that not the start-up time.
Here's a video of openning my website [https://drive.google.com/file/d/1RZPayDfngrBkURjoTNS_iTCPTfE07A6b/view?usp=share_link](url)

**Comment by huycozy** [comment] 2023-02-13 02:51
Thanks for confirming. Can you check if the issue occurs with either the local environment or deployed site? Also, can you try applying the workaround at https://github.com/flutter/flutter/issues/76009#issuecomment-1412708684 to see if the web is still stuck?

**Comment by armin1440** [comment] 2023-02-13 07:33
> Thanks for confirming. Can you check if the issue occurs with either the local environment or deployed site? Also, can you try applying the workaround at [#76009 (comment)](https://github.com/flutter/flutter/issues/76009#issuecomment-1412708684) to see if the web is still stuck?

It only happens in the deployed site. I tried the workaround and it worked. It's surprising because it apparently only speeds up the start up time and does not change anything else. 
Anyway shouldn't it be automatically added to the index.html file?

**Comment by huycozy** [comment] 2023-02-13 07:52
Since this issue is caused by `canvaskit` when starting on empty browser cache. Also, the workaround is applicable to your case. I would suggest you follow up and leave a comment (your case and your question at https://github.com/flutter/flutter/issues/120347#issuecomment-1427475248) at https://github.com/flutter/flutter/issues/76009 about this. 

That issue has been brought up recently with many comments and investigations by the team (see https://github.com/flutter/flutter/issues/76009#issuecomment-1421578481). 

Closing this issue as a duplicate. Please follow up on https://github.com/flutter/flutter/issues/76009 for further updates. Once it's fixed but you still have this issue, please write a comment and I will reopen this issue for further discussion. Thanks!

**Closed by huycozy** 2023-02-13 07:52 UTC
Labels: in triage

**Comment by bilalalmofleh** [comment] 2023-02-15 13:03
> > remove this line
> > from index file its work for me
> 
> What do you mean by "this line"? Can you be more specific?
sorry :) this line
`<base href="$FLUTTER_BASE_HREF">`
