### ISSUE TITLE
flutter upgrade failed

### ISSUE THREAD

**Issue by xiaods** [flutter/flutter#40128] opened 2019-09-10 06:28 UTC
## Steps to Reproduce

1. flutter upgrade
2. raised error: find: invalid mode ‘+100’
3. ...

## Logs

```
$ flutter upgrade
Downloading Dart SDK from Flutter engine b863200c37df4ed378042de11c4e9ff34e4e58c9...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  263M  100  263M    0     0  11.6M      0  0:00:22  0:00:22 --:--:-- 10.7M
find: invalid mode ‘+100’

```

```

```

**Comment by alaadahmed** [comment] 2019-09-10 09:58
I have the same issue exactly.
macOS Mojave 10.14.6

**Comment by hongsenliu** [comment] 2019-09-10 10:30
If you are on mac which has brew, then it is possibly the error of findutils. You can try to uninstall findutils with brew e.g `brew uninstall findutils` first. Then try `flutter doctor`

**Comment by BondarenkoStas** [comment] 2019-09-10 13:23
Seems to be a duplicate of #38878. @xiaods @alaadahmed if the comment above helped you to solve the issue, please close it.

**Comment by alaadahmed** [comment] 2019-09-10 13:46
I confirm issue is solved after uninstalling `findutils` using brew in macOS. Thanks @hongsenliu

**Comment by xiaods** [comment] 2019-09-11 00:25
it works

**Closed** 2019-09-11 00:25 UTC
Labels: waiting for customer response

**Comment by liuchong** [comment] 2019-12-20 09:30
I have same issue on this but I do want use findutils on macOS.
A system default find should be ok to solve this, a pr #47522 was submitted 👀
