### ISSUE TITLE
MissingPluginException(No implementation found for method getAll on channel flutter: plugins.flutter.io/shared_preferences)

### ISSUE THREAD

**Issue by rehamalraee** [flutter/flutter#69896] opened 2020-11-05 17:20 UTC
I'm trying to access the shared preferences through a service's callbackHandler but my app crashed with this exception **

> MissingPluginException(No implementation found for method getAll on channel flutter: plugins.flutter.io/shared_preferences)

**

1. **My Code Snippent** 

void backgroundMain() {
  WidgetsFlutterBinding.ensureInitialized();
  startmooding();
}
void callService(){
  var channel = const MethodChannel('com.xxxx/xxxx');
  var callbackHandle = PluginUtilities.getCallbackHandle(backgroundMain);
  channel.invokeMethod('startService', callbackHandle.toRawHandle());
}
void startmooding() async{
  String ass;
  Stream.periodic(Duration(seconds: 1)).listen((_) async {
    await SharedPreferences.getInstance().then((SharedPreferences sp) {
      ass = sp.getString("assets");
      print(ass);
    });
    if(ass != null)
    {
      bubbleOverlay.openVideoBubble(ass,
          startTimeInMilliseconds: 00000, controlsType: ControlsType.STANDARD);
      print("startOverlay");
    }
  });
}

**2. flutter doctor** 
$ flutter doctor -v
[√] Flutter (Channel stable, 1.22.0, on Microsoft Windows [Version 10.0.19041.572], locale en-US)
    • Flutter version 1.22.0 at C:\Users\ThinkPad\Downloads\flutter
    • Framework revision d408d302e2 (5 weeks ago), 2020-09-29 11:49:17 -0700
    • Engine revision 5babba6c4d
    • Dart version 2.10.0

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\ThinkPad\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = C:\Users\ThinkPad\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

**Comment by pedromassangocode** [comment] 2020-11-06 08:47
Hi @rehamalraee 
You should reply to the first issue you reported (https://github.com/flutter/flutter/issues/69881).

I'm going to close this as a duplicate of https://github.com/flutter/flutter/issues/69881. Please share the code snippet on that issue instead of creating another one.
Thank you

**Closed by pedromassangocode** 2020-11-06 08:47 UTC
