### ISSUE TITLE
No way to develop iOS plugin using Swift bridging with Objective-C

### ISSUE THREAD

**Issue by shinayser** [flutter/flutter#27044] opened 2019-01-24 21:07 UTC
I am trying to develop a VLC plugin for Flutter but I have no experience at all on Objective C, so I decided to go Swift.
But the MobileVLCKit pod is entirely written in Objective C. Looking around on the documentation and a talkign to other developers I realized that there is no way to comunicate to Objective C without a Bridging-header.

The current project format for iOS plugins doesn't support bridging headers, making impossible for Swift communicating to Objective C, thus making impossible to use Swift and Objective C (two way) at the moment.

**Comment by zoechi** [comment] 2019-01-25 09:55
Duplicate of #26892

**Closed by zoechi** 2019-01-25 09:55 UTC
Labels: p: framework, p: tooling, plugin, severe: new feature, t: xcode, tool
