### ISSUE TITLE
Facing issues with quick_actions plugin

### ISSUE THREAD

**Issue by deepakrudrapaul** [flutter/flutter#18864] opened 2018-06-27 06:54 UTC
https://github.com/flutter/plugins/tree/master/packages/quick_actions
```
    --------- beginning of crash
06-27 12:18:57.345 32562-32562/com.example.wanderwagon E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.wanderwagon, PID: 32562
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.wanderwagon/com.example.wanderwagon.MainActivity}: java.lang.IllegalStateException: You should not call registerWith more than once.
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: java.lang.IllegalStateException: You should not call registerWith more than once.
        at io.flutter.plugins.quickactions.QuickActionsPlugin.registerWith(QuickActionsPlugin.java:43)
        at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:17)
        at com.example.wanderwagon.MainActivity.onCreate(MainActivity.java:16)
        at android.app.Activity.performCreate(Activity.java:7009)
        at android.app.Activity.performCreate(Activity.java:7000)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6494) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
```

**Comment by SethJMoore** [comment] 2018-08-21 21:46
I'm running into this IllegalStateException too. One way to reproduce it is to run the quick_actions example in an android emulator, hit the emulator's back button while the app is running, then attempt to open the app again.

I've found that simply adding quick_actions as a dependency in pubspec.yaml causes the problem. You don't even have to import or use it in your app.

**Comment by Vinoth1094** [comment] 2018-09-02 12:49
I also have this issue and thus can't add app shortcut functionality to my app. Is there any work around to get this done. Or can anyone teach me how to implement this myself using native code?

**Comment by SuitMonkeyB** [comment] 2018-09-10 15:51
Having the same exact issue. This main issue is caused by: "java.lang.IllegalStateException: You should not call registerWith more than once."

**Comment by Cretezy** [comment] 2018-09-21 05:03
Created a pull request with the fix: https://github.com/flutter/plugins/pull/783

**Comment by SuitMonkeyB** [comment] 2018-10-09 11:49
Could anyone shed some light and authorize the merge for the pull request?

**Comment by I-am-original** [comment] 2018-11-15 14:19
@zoechi  Currently all updates should be in repo - but new versions of plugins are not published. Please, anyone, who can fix that - do that )  Thanks a lot

**Comment by cyanglaz** [comment] 2019-04-19 22:35
The issue seems to be fixed in https://github.com/flutter/plugins/pull/783. Closing.

**Closed by cyanglaz** 2019-04-19 22:35 UTC
Labels: p: first party, p: quick_actions, plugin, severe: crash
