### ISSUE TITLE
Strange behaviour in Null Check 

### ISSUE THREAD

**Issue by II11II** [flutter/flutter#97811] opened 2022-02-04 17:24 UTC
## Steps to Reproduce
```

import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
     
   
     home:  NullCheckNotWorkWidget('Flutter Demo Home Page'),
    );
  }
}

class NullCheckNotWorkWidget extends StatelessWidget {

    final String ? imageUrl;
 const NullCheckNotWorkWidget(this.imageUrl);
 

  @override
  Widget build(BuildContext context) {
    return Scaffold(
    
      body: Image(image:imageUrl!=null?const NetworkImage('someWebImage.png'):const AssetImage('someAssetImage.png')),
      
    );
  }
}

```

**Expected results:** 
Compiles successfully when check `variable!=null?something : anotherthing` 
**Actual results:** 
![image](https://user-images.githubusercontent.com/45257709/152573753-a04e0a4d-241e-483d-bc49-0a2e8327c74c.png)

<details>
  <summary>Linter and Compile time error</summary>
The argument type 'Object' can't be assigned to the parameter type 'ImageProvider<Object>'.

</details>

**Comment by JherysVargas** [comment] 2022-02-04 17:41
Try casting the validation:

body: Image(image: (imageUrl!=null?const NetworkImage('someWebImage.png'):const AssetImage('someAssetImage.png')) as ImageProvider),

**Comment by II11II** [comment] 2022-02-04 17:43
> Try casting the validation:
> 
> body: Image(image: (imageUrl!=null?const NetworkImage('someWebImage.png'):const AssetImage('someAssetImage.png')) as ImageProvider),

Yes typecast is working, however it is strange behaviour when i pass to ImageProvider by checking null

**Comment by stuartmorgan** [comment] 2022-02-04 20:21
Duplicate of https://github.com/dart-lang/sdk/issues/46333

**Closed by stuartmorgan** 2022-02-04 20:21 UTC
