### ISSUE TITLE
[web]: Flutter for web scrolling is very poor

### ISSUE THREAD

**Issue by IRFAN-GujjAR** [flutter/flutter#50443] opened 2020-02-09 18:23 UTC
I have noticed a very poor scolling performance in flutter web. I hope the flutter team will fix this.

**Comment by TahaTesser** [comment] 2020-02-10 07:47
Hi @IRFAN-GujjAR 
can you please provide your `flutter doctor -v` 
and `flutter run --verbose`?
Also, to better address the issue, would be helpful
if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by jodinathan** [comment] 2020-02-14 20:27
well, you can take a look at the flutter gallery shrine example: https://flutter.github.io/samples/#/

at least for me is very slow for a small image list

**Comment by Piinks** [comment] 2020-02-27 18:04
Thanks for your contribution. This appears to be a duplicate of #42987. Please track that issue for updates. If you believe we've made an error, please reply here with more details that explain the difference and we'll re-open this issue.

**Closed by Piinks** 2020-02-27 18:04 UTC
Labels: f: scrolling, severe: performance, waiting for customer response, ☸ platform-web
