### ISSUE TITLE
Stepper crashing on hot reload when changing amount of steps

### ISSUE THREAD

**Issue by yanir-edri** [flutter/flutter#27187] opened 2019-01-28 17:14 UTC
## Steps to Reproduce

1.  Use the following main.dart file
```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  //comment out lines 19-22, hot reload, then un-comment and hot reload to crash application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Stepper Crash Demo',
      home: Scaffold(
        appBar: AppBar(title: Text("Stepper Crash Demo")),
        body: Stepper(
          steps: [
            Step(
              title: Text("step 1"),
              content: Text("step 1")
            ),
            Step(
                title: Text("step 2"),
                content: Text("step 2")
            ),
            Step(
                title: Text("step 3"),
                content: Text("step 3")
            )
          ],
        ),
      ),
    );
  }
}
```
2. Comment out lines 19-22, hot reload, then un-comment and hot reload to crash application.
## Logs
```
I/flutter (17586): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (17586): The following assertion was thrown building LoginForm(state: LoginFormState#5cf6f):
I/flutter (17586): 'package:flutter/src/material/stepper.dart': Failed assertion: line 248 pos 12: 'widget.steps.length
I/flutter (17586): == oldWidget.steps.length': is not true.
I/flutter (17586): 
I/flutter (17586): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (17586): more information in this error message to help you determine and fix the underlying cause.
I/flutter (17586): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (17586):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter (17586): 
I/flutter (17586): When the exception was thrown, this was the stack:
I/flutter (17586): #2      _StepperState.didUpdateWidget (package:flutter/src/material/stepper.dart:248:12)
I/flutter (17586): #3      StatefulElement.update (package:flutter/src/widgets/framework.dart:3863:58)
I/flutter (17586): #4      Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (17586): #5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (17586): #6      Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (17586): #7      StatefulElement.update (package:flutter/src/widgets/framework.dart:3878:5)
I/flutter (17586): #8      Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (17586): #9      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (17586): #10     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (17586): #11     ProxyElement.update (package:flutter/src/widgets/framework.dart:3990:5)
I/flutter (17586): #12     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (17586): #13     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
I/flutter (17586): #14     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (17586): #15     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
I/flutter (17586): #16     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (17586): #17     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (17586): #18     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (17586): #19     StatelessElement.update (package:flutter/src/widgets/framework.dart:3781:5)
I/flutter (17586): #20     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (17586): #21     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (17586): #22     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (17586): #23     ProxyElement.update (package:flutter/src/widgets/framework.dart:3990:5)
I/flutter (17586): #24     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (17586): #25     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (17586): #26     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (17586): #27     ProxyElement.update (package:flutter/src/widgets/framework.dart:3990:5)
I/flutter (17586): #28     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (17586): #29     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4585:32)
I/flutter (17586): #30     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4975:17)
I/flutter (17586): #31     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (17586): #32     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (17586): #33     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (17586): #34     StatefulElement.update (package:flutter/src/widgets/framework.dart:3878:5)
I/flutter (17586): #35     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (17586): #36     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (17586): #37     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (17586): #38     ProxyElement.update (package:flutter/src/widgets/framework.dart:3990:5)
I/flutter (17586): #39     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (17586): #40     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (17586): #41     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (17586): #42     StatefulElement.update (package:flutter/src/widgets/framework.dart:3878:5)
I/flutter (17586): #43     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (17586): #44     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
I/flutter (17586): #45     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (17586): #46     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (17586): #47     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (17586): #48     StatelessElement.update (package:flutter/src/widgets/framework.dart:3781:5)
I/flutter (17586): #49     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (17586): #50     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
I/flutter (17586): #51     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (17586): #52     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (17586): #53     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (17586): #54     StatefulElement.update (package:flutter/src/widgets/framework.dart:3878:5)
I/flutter (17586): #55     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (17586): #56     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (17586): #57     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (17586): #58     StatefulElement.update (package:flutter/src/widgets/framework.dart:3878:5)
I/flutter (17586): #59     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (17586): #60     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (17586): #61     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (17586): #62     ProxyElement.update (package:flutter/src/widgets/framework.dart:3990:5)
I/flutter (17586): #63     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (17586): #64     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (17586): #65     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (17586): #66     ProxyElement.update (package:flutter/src/widgets/framework.dart:3990:5)
I/flutter (17586): #67     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (17586): #68     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (17586): #69     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (17586): #70     StatefulElement.update (package:flutter/src/widgets/framework.dart:3878:5)
I/flutter (17586): #71     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (17586): #72     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
I/flutter (17586): #73     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (17586): #74     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (17586): #75     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (17586): #76     StatelessElement.update (package:flutter/src/widgets/framework.dart:3781:5)
I/flutter (17586): #77     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (17586): #78     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
I/flutter (17586): #79     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (17586): #80     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
I/flutter (17586): #81     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (17586): #82     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
I/flutter (17586): #83     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (17586): #84     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
I/flutter (17586): #85     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (17586): #86     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (17586): #87     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (17586): #88     StatefulElement.update (package:flutter/src/widgets/framework.dart:3878:5)
I/flutter (17586): #89     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (17586): #90     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (17586): #91     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (17586): #92     StatelessElement.update (package:flutter/src/widgets/framework.dart:3781:5)
I/flutter (17586): #93     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (17586): #94     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (17586): #95     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (17586): #96     StatefulElement.update (package:flutter/src/widgets/framework.dart:3878:5)
I/flutter (17586): #97     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (17586): #98     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
I/flutter (17586): #99     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (17586): #100    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (17586): #101    Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (17586): #102    ProxyElement.update (package:flutter/src/widgets/framework.dart:3990:5)
I/flutter (17586): #103    Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (17586): #104    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
I/flutter (17586): #105    Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (17586): #106    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (17586): #107    Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (17586): #108    StatefulElement.update (package:flutter/src/widgets/framework.dart:3878:5)
I/flutter (17586): #109    Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (17586): #110    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (17586): #111    Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (17586): #112    StatelessElement.update (package:flutter/src/widgets/framework.dart:3781:5)
I/flutter (17586): #113    Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (17586): #114    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
I/flutter (17586): #115    Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (17586): #116    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (17586): #117    Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (17586): #118    ProxyElement.update (package:flutter/src/widgets/framework.dart:3990:5)
I/flutter (17586): #119    Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (17586): #120    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (17586): #121    Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (17586): #122    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2286:33)
I/flutter (17586): #123    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:676:20)
I/flutter (17586): #124    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:219:5)
I/flutter (17586): #125    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter (17586): #126    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter (17586): #127    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:751:7)
I/flutter (17586): #129    _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
I/flutter (17586): #130    _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
I/flutter (17586): #131    _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
I/flutter (17586): (elided 3 frames from class _AssertionError and package dart:async)
```
## Flutter Doctor
```
[√] Flutter (Channel beta, v1.0.0, on Microsoft Windows [Version 10.0.17134.523], locale en-IL)
    • Flutter version 1.0.0 at C:\Apps\flutter
    • Framework revision 5391447fae (9 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at C:\Users\Yanir\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = C:\Users\Yanir\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 31.3.3
    • Dart plugin version 182.5124
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
```

**Comment by zoechi** [comment] 2019-01-28 19:11
To investigate we would need a minimal runnable reproduction
as a single file so that we can just copy your code into `lib/main.dart` of a new project and run to reproduce.

**Comment by yanir-edri** [comment] 2019-02-04 11:09
any progress?

**Comment by jonahwilliams** [comment] 2019-02-05 18:05
The issue is that the stepper state object does not know how to update the number of steps, see:

https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/stepper.dart#L248

**Comment by kangwang1988** [comment] 2019-02-07 05:26
@yanir-edri 
I don't think this is a feature instead of a bug.
Feel free to comment below.

**Comment by Livinglist** [comment] 2019-02-13 23:56
I encounter the same issue when I tried to update the state to increase the steps in stepper. Why should the number of steps of the old widget be the same as the that of the new one?

**Comment by Livinglist** [comment] 2019-02-14 02:12
> @yanir-edri
> I think this is a feature instead of a bug.
> Feel free to comment below.

I think this issue should be reopened.

**Comment by zoechi** [comment] 2019-02-14 06:32
Lets the widget maintainer decide if the widget should be able to handle such state changes on hot-reload.

**Comment by g3rrydanc3** [comment] 2019-12-07 08:14
**Workaround**

Give random key every time widget rebuild

```dart
Stepper(key: Key(Random.secure().nextDouble().toString())
```

**Comment by jonahwilliams** [comment] 2020-04-22 00:24
Removing from tools project since this is a framework bug

**Comment by TahaTesser** [comment] 2020-06-03 15:36
Hi @yanir-edri 
Not able to reproduce this crash on latest `dev` channel

<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel dev, 1.19.0-3.0.pre, on Mac OS X 10.15.5 19F96, locale
    en-GB)
    • Flutter version 1.19.0-3.0.pre at /Users/tahatesser/Code/flutter_dev
    • Framework revision 6135091de9 (31 hours ago), 2020-06-01 17:17:03 -0700
    • Engine revision e39301f23f
    • Dart version 2.9.0 (build 2.9.0-11.0.dev 6489a0c68d)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (4 available)
    • iPhone 11  • 0EC80516-8F99-4A0C-89ED-2273579862F9 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-13-5 (simulator)
    • macOS      • macOS                                • darwin-x64     • Mac
      OS X 10.15.5 19F96
    • Web Server • web-server                           • web-javascript •
      Flutter Tools
    • Chrome     • chrome                               • web-javascript •
      Google Chrome 83.0.4103.61

• No issues found!
``` 

</details> 

Are you still experiencing this issue with latest `dev` channel?
Thank you

**Comment by VladyslavBondarenko** [comment] 2020-06-25 15:39
@yanir-edri 
I can't reproduce as well with current dev `1.20.0-1.0.pre`,
closing as fixed

**Closed by VladyslavBondarenko** 2020-06-25 15:39 UTC
Labels: P4, f: material design, framework, severe: crash, t: hot reload, waiting for customer response

**Comment by ospar0829** [comment] 2020-07-16 16:26
same occurs when you generate a Step with a StreamBuilder when receiving a new/deleted document (Firestore)

**Comment by VladyslavBondarenko** [comment] 2020-07-16 16:51
@ospar0829 consider to file a new issue with filling out template, it'll be good if you can provide a minimal reproducible code sample without using Firestore

**Comment by janhaa** [comment] 2021-07-20 07:42
> **Workaround**
> 
> Give random key every time widget rebuild
> 
> ```dart
> Stepper(key: Key(Random.secure().nextDouble().toString())
> ```

I used this solution for some time, there is one problem though:

If there is a input field inside a Step and you try to input data, the keyboard immediately closes, probably as the key is regenerated due to changing viewport dimensions and therefore focus to the input element is lost.
