### ISSUE TITLE
Build failed just after adding plugins

### ISSUE THREAD

**Issue by tanzimfahim** [flutter/flutter#36069] opened 2019-07-12 14:42 UTC
my pubspec.yaml file contains
```
http:
  cloud_firestore: 
  intl: 
  firebase_admob: 
  firebase_core:
  firebase_auth: 
  firebase_database: 
  cupertino_icons: 
  shared_preferences:  
  emoji_picker:
  google_sign_in: 
  flutter_facebook_login:
  firebase_messaging: 
  image_picker_modern: 
  firebase_storage: 
  font_awesome_flutter: 
  in_app_purchase: 
```
these dependencies.
I tried almost all methods of internet but no result.
upgraded to androidX, multidexenabled true, 

Seems like the some packages doesn't match with each other. How can i know which version to use for comfortablity 

flutter doctor -v 
```
[✓] Flutter (Channel stable, v1.7.8+hotfix.3, on Mac OS X 10.14.5 18F132, locale en-BD)
    • Flutter version 1.7.8+hotfix.3 at /Users/tanzimfahim/flutter
    • Framework revision b712a172f9 (3 days ago), 2019-07-09 13:14:38 -0700
    • Engine revision 54ad777fd2
    • Dart version 2.4.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/tanzimfahim/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • CocoaPods version 1.7.4

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 37.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.36.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.2.0

[✓] Connected device (1 available)
    • ONEPLUS A5000 • ceecb6b2 • android-arm64 • Android 9 (API 28)

• No issues found!
```
```
With version:
  http:
  onesignal: ^1.1.0
  cloud_firestore: ^0.8.2
  intl: ^0.15.8
  firebase_admob: 
  firebase_core:
  firebase_auth: 
  firebase_database: ^1.0.5
  cupertino_icons: ^0.1.2
  shared_preferences: 0.5.3+1 
  emoji_picker:
  google_sign_in: ^4.0.1+1
  flutter_facebook_login:
  firebase_messaging: ^4.0.0
  image_picker_modern: ^0.4.12+2
  firebase_storage: 
  font_awesome_flutter: ^8.0.1
```

But same result :(

**Comment by sinequanon-games** [comment] 2019-07-12 18:12
I'm having this issue as well.

**Comment by rafalbednarczuk** [comment] 2019-07-12 18:38
There is problem with firebase_messaging version 5.0.0 and above, it fails build for me. Using versions 4.0.0 - 5.0.0 works

**Comment by tanzimfahim** [comment] 2019-07-13 03:11
> There is problem with firebase_messaging version 5.0.0 and above, it fails build for me. Using versions 4.0.0 - 5.0.0 works.
> 4.0.0 enables build app for me but it breaks app when calling FirebaseMessaging().configure()
> `[ERROR:flutter/shell/platform/android/platform_view_android_jni.cc(40)] java.lang.NoClassDefFoundError: Failed resolution of: Lio/flutter/plugins/firebasemessaging/FlutterFirebaseInstanceIDService`

updated the version but no result

FAILURE: Build failed with an exception.                                
                                                                        
* What went wrong:                                                      
Execution failed for task ':app:preDebugBuild'.                         
> Android dependency 'androidx.localbroadcastmanager:localbroadcastmanager' has different version for the compile (1.0.0-rc01) and runtime (1.0.0) classpath. You should manually set the same version via DependencyResolution
                                                                        
* Try:                                                                  
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
                                                                        
* Get more help at https://help.gradle.org                              
                                                                        
BUILD FAILED in 8s

**Comment by tanzimfahim** [comment] 2019-07-13 13:17
I found a solution working for me.

Migrate to androidX and 
add the following line in build.gradle (inside app folder)


    implementation 'androidx.localbroadcastmanager:localbroadcastmanager:1.0.0'

**Comment by rafalbednarczuk** [comment] 2019-07-14 06:18
in my case adding to build.gradle:
    implementation 'com.google.firebase:firebase-messaging:19.0.1'
solved issue

**Comment by BondarenkoStas** [comment] 2019-09-29 20:51
@tanzimfahim As the issue is solved, I think it's safe to close it now. If you disagree or have more information, please comment and I will re-open it right away.

**Closed by BondarenkoStas** 2019-09-29 20:51 UTC
