### ISSUE TITLE
[iOS] Whole app screen glitches when showing CupertinoDatePicker

### ISSUE THREAD

**Issue by Frezyx** [flutter/flutter#144465] opened 2024-03-01 07:29 UTC
### Steps to reproduce

1. Show CupertinoDatePicker with showModalBottomSheet
2. Scroll BottomSheet or scroll dates in picker UI

### Expected results

No glitches anywhere on the screen

### Actual results

The whole screen is covered with glitches including the BottomSheet content and the screen under it where the showModalBottomSheet was opened. 

I have a lot of CupertinoDatePickers wrapped in showModalBottomSheet in my application. And this issue affects each of these BottomSheets both in the debug and release builds. 

### Code sample

<details open><summary>Code sample</summary>

```dart
  showModalBottomSheet(
    backgroundColor: Colors.transparent,
    shape: RoundedRectangleBorder(
      borderRadius: BorderRadius.circular(0),
    ),
    isScrollControlled: true,
    context: context,
    builder: (context) => CupertinoDatePicker(
      mode: CupertinoDatePickerMode.time,
      initialDateTime: DateTime(2024, 3, 1, 12),
      use24hFormat: true,
      onDateTimeChanged: (time) {},
    ),
  );
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/flutter/flutter/assets/40857927/7b24a20d-c0ea-4ba4-bc84-12aec5b34974

</details>

### Logs

<details open><summary>Logs</summary>

```console
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.19.0, on macOS 14.2.1 23C71 darwin-arm64, locale en-AE)
    • Flutter version 3.19.0 on channel stable at /Users/stanislavilin/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision bae5e49bc2 (2 weeks ago), 2024-02-13 17:46:18 -0800
    • Engine revision 04817c99c9
    • Dart version 3.3.0
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/stanislavilin/Library/Android/sdk
    • Platform android-34, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.86.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.82.0

[✓] Connected device (3 available)
    • iPhone Стас (mobile) • 0<...>E • ios            • iOS 17.3 21D50
    • macOS (desktop)      • macos                     • darwin-arm64   • macOS 14.2.1 23C71 darwin-arm64
    • Chrome (web)         • chrome                    • web-javascript • Google Chrome 122.0.6261.69
    ! Error: Browsing on the local area network for Apple Watch — Станислав. Ensure the device is unlocked and discoverable via Bluetooth. (code -27)

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by edeuss** [comment] 2024-03-01 07:48
We have also had a similar issue AlertDialog when using setstate.

Would render the text oddly for a second then return to the correct state.

![image](https://github.com/flutter/flutter/assets/13773566/354e4ed5-6d8a-4969-a51d-167e346681d3)

**Comment by danagbemava-nc** [comment] 2024-03-01 09:25
Closing this as a duplicate of https://github.com/flutter/flutter/issues/144331. 

Please provide any additional information that can help up reproduce the issue in the original issue. 

A full reproducible code sample would be appreciated. 

Thank you

**Closed by danagbemava-nc** 2024-03-01 09:25 UTC
Labels: in triage
