### ISSUE TITLE
NoSuchMethodError: NoSuchMethodError: Closure call with mismatched arguments: function 'MutablePackageTree.allPackages'

### ISSUE THREAD

**Issue by daniesa** [flutter/flutter#59245] opened 2020-06-11 07:44 UTC
Receiver: Closure: (_SyncIterator<Package>) => bool
Tried calling: MutablePackageTree.allPackages()
Found: MutablePackageTree.allPackages(_SyncIterator<Package>) => bool".
A crash report has been written to D:\DART\login_git\flutter_01.log.

The log file is attached below.

THANKS.
[flutter_01.log](https://github.com/flutter/flutter/files/4763325/flutter_01.log)

**Comment by TahaTesser** [comment] 2020-06-11 12:36
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter run --machine --target lib\main.dart -d chrome --track-widget-creation --start-paused

## exception

NoSuchMethodError: NoSuchMethodError: Closure call with mismatched arguments: function 'MutablePackageTree.allPackages'
Receiver: Closure: (_SyncIterator<Package>) => bool
Tried calling: MutablePackageTree.allPackages()
Found: MutablePackageTree.allPackages(_SyncIterator<Package>) => bool

```
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      _SyncIterable.iterator (dart:core-patch/core_patch.dart:117:45)
#2      new SimplePackageConfig (package:package_config/src/package_config_impl.dart:26:36)
#3      parsePackageConfigJson (package:package_config/src/package_config_json.dart:213:10)
#4      parsePackageConfigBytes (package:package_config/src/package_config_json.dart:45:10)
#5      readAnyConfigFile (package:package_config/src/package_config_io.dart:55:18)
<asynchronous suspension>
#6      readAnyConfigFileUri (package:package_config/src/package_config_io.dart:76:14)
#7      loadPackageConfigUri (package:package_config/package_config.dart:88:5)
#8      DartUri._loadPackageConfig (package:dwds/src/utilities/dart_uri.dart:35:30)
#9      DartUri.recordAbsoluteUris (package:dwds/src/utilities/dart_uri.dart:57:13)
#10     AppInspector._initialize (package:dwds/src/debugging/inspector.dart:87:19)
<asynchronous suspension>
#11     AppInspector.initialize (package:dwds/src/debugging/inspector.dart:145:24)
#12     ChromeProxyService.createIsolate (package:dwds/src/services/chrome_proxy_service.dart:165:37)
<asynchronous suspension>
#13     ChromeProxyService.create (package:dwds/src/services/chrome_proxy_service.dart:133:23)
#14     DebugService.start (package:dwds/src/services/debug_service.dart:140:55)
#15     DevHandler._startLocalDebugService (package:dwds/src/handlers/dev_handler.dart:156:25)
#16     _rootRunUnary (dart:async/zone.dart:1198:47)
#17     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#18     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#19     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#20     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#21     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#22     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
#23     _rootRun (dart:async/zone.dart:1190:13)
#24     _CustomZone.run (dart:async/zone.dart:1093:19)
#25     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#26     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#27     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#28     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#29     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#30     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

## flutter doctor

```
[✓] Flutter (Channel beta, v1.17.0, on Microsoft Windows [Version 10.0.18363.657], locale en-US)
    • Flutter version 1.17.0 at D:\Flutter\flutter
    • Framework revision d3ed9ec945 (9 weeks ago), 2020-04-06 14:07:34 -0700
    • Engine revision 9a28c3bcf4
    • Dart version 2.9.0 (build 2.9.0-14.1.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at D:\Program Files\Android\android-sdk\
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = D:\Program Files\Android\android-sdk\
    • Java binary at: D:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 3.6)
    • Android Studio at D:\Program Files\Android\Android Studio
    • Flutter plugin version 45.0.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[✓] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 83.0.4103.97
    • Web Server • web-server • web-javascript • Flutter Tools

• No issues found!
```

**Comment by skillitzimberg** [comment] 2020-06-25 00:13
I'm getting this error too when running `flutter run -d chrome`. Then I used `flutter run --release -d chrome` and the app launched. Does that point to anything?

I'm working with Flutter for web so I don't have the Xcode and Android stuff set up. This is the `flutter-01.log`:
```
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter run -d chrome

## exception

NoSuchMethodError: NoSuchMethodError: Closure call with mismatched arguments: function 'MutablePackageTree.allPackages'
Receiver: Closure: (_SyncIterator<Package>) => bool
Tried calling: MutablePackageTree.allPackages()
Found: MutablePackageTree.allPackages(_SyncIterator<Package>) => bool

#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      _SyncIterable.iterator (dart:core-patch/core_patch.dart:117:45)
#2      new SimplePackageConfig (package:package_config/src/package_config_impl.dart:26:36)
#3      parsePackageConfigJson (package:package_config/src/package_config_json.dart:213:10)
#4      parsePackageConfigBytes (package:package_config/src/package_config_json.dart:45:10)
#5      readAnyConfigFile (package:package_config/src/package_config_io.dart:55:18)
<asynchronous suspension>
#6      readAnyConfigFileUri (package:package_config/src/package_config_io.dart:76:14)
#7      loadPackageConfigUri (package:package_config/package_config.dart:88:5)
#8      DartUri._loadPackageConfig (package:dwds/src/utilities/dart_uri.dart:35:30)
#9      DartUri.recordAbsoluteUris (package:dwds/src/utilities/dart_uri.dart:57:13)
#10     AppInspector._initialize (package:dwds/src/debugging/inspector.dart:87:19)
<asynchronous suspension>
#11     AppInspector.initialize (package:dwds/src/debugging/inspector.dart:145:24)
#12     ChromeProxyService.createIsolate (package:dwds/src/services/chrome_proxy_service.dart:165:37)
<asynchronous suspension>
#13     ChromeProxyService.create (package:dwds/src/services/chrome_proxy_service.dart:133:23)
#14     DebugService.start (package:dwds/src/services/debug_service.dart:140:55)
#15     DevHandler._startLocalDebugService (package:dwds/src/handlers/dev_handler.dart:156:25)
#16     _rootRunUnary (dart:async/zone.dart:1198:47)
#17     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#18     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#19     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#20     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#21     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#22     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
#23     _rootRun (dart:async/zone.dart:1190:13)
#24     _CustomZone.run (dart:async/zone.dart:1093:19)
#25     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#26     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#27     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#28     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#29     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#30     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

## flutter doctor

```
[✓] Flutter (Channel beta, v1.17.0, on Mac OS X 10.14.6 18G5033, locale en-US)
    • Flutter version 1.17.0 at /Users/ForeignFood/flutter
    • Framework revision d3ed9ec945 (3 months ago), 2020-04-06 14:07:34 -0700
    • Engine revision 9a28c3bcf4
    • Dart version 2.9.0 (build 2.9.0-14.1.beta)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at /Users/ForeignFood/Library/Android/sdk
    • Platform android-29, build-tools 29.0.0
    • Java binary at: /usr/bin/java
    • Java version Java(TM) SE Runtime Environment (build 12.0.1+12)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit visit https://flutter.dev/docs/get-started/install/macos#android-setup for
      detailed instructions.

[!] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install:
        sudo gem install cocoapods

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 83.0.4103.116
    • Web Server • web-server • web-javascript • Flutter Tools

! Doctor found issues in 3 categories.
```

**Comment by jonahwilliams** [comment] 2020-06-25 00:18
This seems like a bug in package_config, but I can't figure out where

**Comment by jensjoha** [comment] 2020-06-25 09:02
`package:dwds` is used from the flutter tools I think --- so I don't think this has anything to do with compiling the users code...

**Comment by jonahwilliams** [comment] 2020-06-27 22:43
This has nothing to do with caching dills, it is being thrown from the flutter tool itself as it runs.

**Comment by maxlapides** [comment] 2020-06-27 23:37
I am experiencing this error on Flutter version `1.19.0-4.2.pre` but NOT on Flutter version `1.18.0-11.1.pre`. Unfortunately, we can't upgrade to the latest beta Flutter version until this issue is resolved.

**Comment by mkustermann** [comment] 2020-06-29 11:14
@cskau-g is going to take a look and see if this is related to the `yield*` changes

**Comment by skillitzimberg** [comment] 2020-06-29 12:48
> Could this be due to cached `.dill` files?
> 
> @cskau-g has done optimization of `yield*`. If an old, cached, kernel file is used with a newer Dart VM this issue could occur.
> 
> @skillitzimberg Could you try `flutter clean` / `rm -r .dart_tool; rm -r build` and see if this still happens?
> 
> We have an open issue, [dart-lang/sdk#41802](https://github.com/dart-lang/sdk/issues/41802), to make the VM refuse very loudly if outdated kernel files are given to the VM. The functionality is implemented and will land during coming days.
> 
> /cc @jensjoha

@mkustermann, in which directory should I be running those commands?

**Comment by natebosch** [comment] 2020-07-01 16:25
> This has nothing to do with caching dills, it is being thrown from the flutter tool itself as it runs.

Is the flutter tool being run from a snapshot when this happens? Recreating the snapshot should resolve it.

**Comment by sjoe** [comment] 2020-07-01 17:50
After a clean a could build again

**Comment by mkustermann** [comment] 2020-07-02 13:35
> This has nothing to do with caching dills, it is being thrown from the flutter tool itself as it runs.

@jonahwilliams The flutter tool is running from a cached dill / kernel file (`<flutter>/bin/cache/flutter_tools.snapshot` is a kernel file)

When I run
```
% flutter run -d chrome --track-widget-creation --start-paused
Launching lib/main.dart on Chrome in debug mode...
Syncing files to device Chrome...   
...
```

=> It seems to work fine for me.

Can anyone provide us with concrete steps to reproduce this?

**Comment by richard457** [comment] 2020-07-06 05:14
It happens when you switch from for example stable channel to beta channel and attempt to run flutter packages pub run build_runner watch --delete-conflicting-outputs

**Comment by mkustermann** [comment] 2020-07-06 11:51
With @richard457 's instructions, I can indeed reproduce an issue:

```
% flutter channel 
Flutter channels:
  master
  dev
  beta
* stable

% rm -rf .dart_tool
% flutter packages pub get 
...
% flutter packages pub run build_runner watch --delete-conflicting-outputs
[INFO] Generating build script...
[INFO] Generating build script completed, took 462ms

[INFO] Creating build script snapshot......
[INFO] Creating build script snapshot... completed, took 12.6s

[INFO] Setting up file watchers...
[INFO] Setting up file watchers completed, took 19ms

[INFO] Waiting for all file watchers to be ready...
[INFO] Waiting for all file watchers to be ready completed, took 200ms

[SEVERE] Nothing can be built, yet a build was requested.
[INFO] Initializing inputs
[INFO] Building new asset graph...
[INFO] Building new asset graph completed, took 734ms

% flutter channel beta
Switching to flutter channel 'beta'...
git: Switched to branch 'beta'
git: Your branch is up-to-date with 'origin/beta'.
Successfully switched to flutter channel 'beta'.
To ensure that you're on the latest build from this channel, run 'flutter upgrade'

% flutter packages pub run build_runner watch --delete-conflicting-outputs
Downloading Dart SDK from Flutter engine 9a28c3bcf40ce64fee61e807ee3e1395fd6bd954...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  225M  100  225M    0     0  6287k      0  0:00:36  0:00:36 --:--:-- 6263k
Building flutter tool...
Downloading package sky_engine...                                   0.5s
Downloading flutter_patched_sdk tools...                            1.2s
Downloading flutter_patched_sdk_product tools...                    0.8s
Downloading darwin-x64 tools...                                     5.3s
Downloading darwin-x64/font-subset tools...                         0.3s
Unhandled exception:
NoSuchMethodError: Closure call with mismatched arguments: function 'MutablePackageTree.allPackages'
Receiver: Closure: (_SyncIterator<Package>) => bool
Tried calling: MutablePackageTree.allPackages()
Found: MutablePackageTree.allPackages(_SyncIterator<Package>) => bool
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      _SyncIterable.iterator (dart:core-patch/core_patch.dart:117:45)
#2      new SimplePackageConfig (package:package_config/src/package_config_impl.dart:26:36)
#3      parsePackageConfigJson (package:package_config/src/package_config_json.dart:213:10)
#4      parsePackageConfigBytes (package:package_config/src/package_config_json.dart:45:10)
#5      readPackageConfigJsonFile (package:package_config/src/package_config_io.dart:117:10)
<asynchronous suspension>
#6      findPackagConfigInDirectory (package:package_config/src/discovery.dart:109:18)
<asynchronous suspension>
#7      findPackageConfig (package:package_config/src/discovery.dart:44:31)
<asynchronous suspension>
#8      findPackageConfig (package:package_config/package_config.dart:114:5)
#9      PackageGraph.forPath (package:build_runner_core/src/package_graph/package_graph.dart:74:15)
#10     PackageGraph.forThisPackage (package:build_runner_core/src/package_graph/package_graph.dart:110:20)
#11     main (file:///Users/kustermann/.pub-cache/hosted/pub.dartlang.org/build_runner-1.10.0/bin/build_runner.dart:27:49)
#12     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#13     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
pub finished with exit code 255
```

Removing a cached kernel file will solve this issue:
```
% rm .dart_tool/pub/bin/build_runner/build_runner.dart.snapshot.dart2
```
though it then fails with
```
% flutter packages pub run build_runner watch --delete-conflicting-outputs      
[INFO] Generating build script...
Unhandled exception:
NoSuchMethodError: The getter 'name' was called on null.
Receiver: null
Tried calling: name
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      _findBuilderApplications.<anonymous closure> (package:build_runner/src/build_script_generate/build_script_generate.dart:63:24)
#2      _CustomHashMap.[]= (dart:collection-patch/collection_patch.dart:281:31)
#3      stronglyConnectedComponents.strongConnect (package:graphs/src/strongly_connected_components.dart:49:12)
#4      stronglyConnectedComponents.strongConnect (package:graphs/src/strongly_connected_components.dart:57:22)
#5      stronglyConnectedComponents.strongConnect (package:graphs/src/strongly_connected_components.dart:57:22)
#6      stronglyConnectedComponents (package:graphs/src/strongly_connected_components.dart:76:50)
#7      _findBuilderApplications (package:build_runner/src/build_script_generate/build_script_generate.dart:59:27)
<asynchronous suspension>
#8      _generateBuildScript (package:build_runner/src/build_script_generate/build_script_generate.dart:28:26)
#9      logTimedAsync (package:build_runner_core/src/logging/logging.dart:25:30)
#10     generateBuildScript (package:build_runner/src/build_script_generate/build_script_generate.dart:25:5)
#11     generateAndRun (package:build_runner/src/build_script_generate/bootstrap.dart:49:31)
<asynchronous suspension>
#12     main (file:///Users/kustermann/.pub-cache/hosted/pub.dartlang.org/build_runner-1.10.0/bin/build_runner.dart:87:30)
<asynchronous suspension>
#13     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#14     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

Doing a full cleanup via:
```
% rm -rf .dart_tool
% flutter packages get
% flutter packages pub run build_runner watch --delete-conflicting-outputs
[INFO] Generating build script...
[INFO] Generating build script completed, took 448ms

[INFO] Creating build script snapshot......

[INFO] Creating build script snapshot... completed, took 14.0s

[INFO] Setting up file watchers...
[INFO] Setting up file watchers completed, took 16ms

[INFO] Waiting for all file watchers to be ready...
[INFO] Waiting for all file watchers to be ready completed, took 198ms

[SEVERE] Nothing can be built, yet a build was requested.
[INFO] Initializing inputs
[INFO] Building new asset graph...
[INFO] Building new asset graph completed, took 693ms

[INFO] Checking for unexpected pre-existing outputs....
[INFO] Checking for unexpected pre-existing outputs. completed, took 2ms

[INFO] Running build...
[INFO] Running build completed, took 4ms

[INFO] Caching finalized dependency graph...
[INFO] Caching finalized dependency graph completed, took 65ms

[INFO] Succeeded after 81ms with 0 outputs (0 actions)
```

solves the problem.


=> This re-assures my suspicion above that it's due to cached kernel files.

**Comment by natebosch** [comment] 2020-07-06 23:02
The tracking issue to fix this is https://github.com/dart-lang/sdk/issues/41802

**Comment by jonahwilliams** [comment] 2020-07-06 23:03
@mkustermann we generate a new snapshot on every dart SDK roll. Or at least we attempt to!

**Comment by infinityp913** [comment] 2020-07-11 20:08
Hi, when I run  flutter packages pub run build_runner watch --delete-conflicting-outputs
it says :
Could not find package "build_runner". Did you forget to add a dependency?

I ran this in the root dir of the project. What did I wrong?

**Comment by CoderJava** [comment] 2020-07-13 02:48
> With @richard457 's instructions, I can indeed reproduce an issue:
> 
> ```
> % flutter channel 
> Flutter channels:
>   master
>   dev
>   beta
> * stable
> 
> % rm -rf .dart_tool
> % flutter packages pub get 
> ...
> % flutter packages pub run build_runner watch --delete-conflicting-outputs
> [INFO] Generating build script...
> [INFO] Generating build script completed, took 462ms
> 
> [INFO] Creating build script snapshot......
> [INFO] Creating build script snapshot... completed, took 12.6s
> 
> [INFO] Setting up file watchers...
> [INFO] Setting up file watchers completed, took 19ms
> 
> [INFO] Waiting for all file watchers to be ready...
> [INFO] Waiting for all file watchers to be ready completed, took 200ms
> 
> [SEVERE] Nothing can be built, yet a build was requested.
> [INFO] Initializing inputs
> [INFO] Building new asset graph...
> [INFO] Building new asset graph completed, took 734ms
> 
> % flutter channel beta
> Switching to flutter channel 'beta'...
> git: Switched to branch 'beta'
> git: Your branch is up-to-date with 'origin/beta'.
> Successfully switched to flutter channel 'beta'.
> To ensure that you're on the latest build from this channel, run 'flutter upgrade'
> 
> % flutter packages pub run build_runner watch --delete-conflicting-outputs
> Downloading Dart SDK from Flutter engine 9a28c3bcf40ce64fee61e807ee3e1395fd6bd954...
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100  225M  100  225M    0     0  6287k      0  0:00:36  0:00:36 --:--:-- 6263k
> Building flutter tool...
> Downloading package sky_engine...                                   0.5s
> Downloading flutter_patched_sdk tools...                            1.2s
> Downloading flutter_patched_sdk_product tools...                    0.8s
> Downloading darwin-x64 tools...                                     5.3s
> Downloading darwin-x64/font-subset tools...                         0.3s
> Unhandled exception:
> NoSuchMethodError: Closure call with mismatched arguments: function 'MutablePackageTree.allPackages'
> Receiver: Closure: (_SyncIterator<Package>) => bool
> Tried calling: MutablePackageTree.allPackages()
> Found: MutablePackageTree.allPackages(_SyncIterator<Package>) => bool
> #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
> #1      _SyncIterable.iterator (dart:core-patch/core_patch.dart:117:45)
> #2      new SimplePackageConfig (package:package_config/src/package_config_impl.dart:26:36)
> #3      parsePackageConfigJson (package:package_config/src/package_config_json.dart:213:10)
> #4      parsePackageConfigBytes (package:package_config/src/package_config_json.dart:45:10)
> #5      readPackageConfigJsonFile (package:package_config/src/package_config_io.dart:117:10)
> <asynchronous suspension>
> #6      findPackagConfigInDirectory (package:package_config/src/discovery.dart:109:18)
> <asynchronous suspension>
> #7      findPackageConfig (package:package_config/src/discovery.dart:44:31)
> <asynchronous suspension>
> #8      findPackageConfig (package:package_config/package_config.dart:114:5)
> #9      PackageGraph.forPath (package:build_runner_core/src/package_graph/package_graph.dart:74:15)
> #10     PackageGraph.forThisPackage (package:build_runner_core/src/package_graph/package_graph.dart:110:20)
> #11     main (file:///Users/kustermann/.pub-cache/hosted/pub.dartlang.org/build_runner-1.10.0/bin/build_runner.dart:27:49)
> #12     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
> #13     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
> pub finished with exit code 255
> ```
> 
> Removing a cached kernel file will solve this issue:
> 
> ```
> % rm .dart_tool/pub/bin/build_runner/build_runner.dart.snapshot.dart2
> ```
> 
> though it then fails with
> 
> ```
> % flutter packages pub run build_runner watch --delete-conflicting-outputs      
> [INFO] Generating build script...
> Unhandled exception:
> NoSuchMethodError: The getter 'name' was called on null.
> Receiver: null
> Tried calling: name
> #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
> #1      _findBuilderApplications.<anonymous closure> (package:build_runner/src/build_script_generate/build_script_generate.dart:63:24)
> #2      _CustomHashMap.[]= (dart:collection-patch/collection_patch.dart:281:31)
> #3      stronglyConnectedComponents.strongConnect (package:graphs/src/strongly_connected_components.dart:49:12)
> #4      stronglyConnectedComponents.strongConnect (package:graphs/src/strongly_connected_components.dart:57:22)
> #5      stronglyConnectedComponents.strongConnect (package:graphs/src/strongly_connected_components.dart:57:22)
> #6      stronglyConnectedComponents (package:graphs/src/strongly_connected_components.dart:76:50)
> #7      _findBuilderApplications (package:build_runner/src/build_script_generate/build_script_generate.dart:59:27)
> <asynchronous suspension>
> #8      _generateBuildScript (package:build_runner/src/build_script_generate/build_script_generate.dart:28:26)
> #9      logTimedAsync (package:build_runner_core/src/logging/logging.dart:25:30)
> #10     generateBuildScript (package:build_runner/src/build_script_generate/build_script_generate.dart:25:5)
> #11     generateAndRun (package:build_runner/src/build_script_generate/bootstrap.dart:49:31)
> <asynchronous suspension>
> #12     main (file:///Users/kustermann/.pub-cache/hosted/pub.dartlang.org/build_runner-1.10.0/bin/build_runner.dart:87:30)
> <asynchronous suspension>
> #13     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
> #14     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
> ```
> 
> Doing a full cleanup via:
> 
> ```
> % rm -rf .dart_tool
> % flutter packages get
> % flutter packages pub run build_runner watch --delete-conflicting-outputs
> [INFO] Generating build script...
> [INFO] Generating build script completed, took 448ms
> 
> [INFO] Creating build script snapshot......
> 
> [INFO] Creating build script snapshot... completed, took 14.0s
> 
> [INFO] Setting up file watchers...
> [INFO] Setting up file watchers completed, took 16ms
> 
> [INFO] Waiting for all file watchers to be ready...
> [INFO] Waiting for all file watchers to be ready completed, took 198ms
> 
> [SEVERE] Nothing can be built, yet a build was requested.
> [INFO] Initializing inputs
> [INFO] Building new asset graph...
> [INFO] Building new asset graph completed, took 693ms
> 
> [INFO] Checking for unexpected pre-existing outputs....
> [INFO] Checking for unexpected pre-existing outputs. completed, took 2ms
> 
> [INFO] Running build...
> [INFO] Running build completed, took 4ms
> 
> [INFO] Caching finalized dependency graph...
> [INFO] Caching finalized dependency graph completed, took 65ms
> 
> [INFO] Succeeded after 81ms with 0 outputs (0 actions)
> ```
> 
> solves the problem.
> 
> => This re-assures my suspicion above that it's due to cached kernel files (see [#59245 (comment)](https://github.com/flutter/flutter/issues/59245#issuecomment-649397944))

Thanks. It's worked for me.

**Comment by mkustermann** [comment] 2020-07-13 12:09
> @mkustermann we generate a new snapshot on every dart SDK roll. Or at least we attempt to!

@jonahwilliams Correct. Though I think where it goes wrong is that something launches a subprocess via `pub run` (or `flutter packages pub run`) which also caches kernel files. This seems to be the root cause here (i.e. not the flutter tools itself)

**Comment by AcodeWang** [comment] 2020-07-16 14:44
For me, `Flutter clean` solve the problem.

**Comment by mkustermann** [comment] 2020-07-17 10:39
The underlying issue is due to using cached files produced by a different version of the Dart SDK than the version used to run them.

The workaround is `flutter clean` or `rm -rf .dart_tool`.

The underlying problem should've been fixed in dart-lang/sdk and is slowly being rolled upstream to flutter. I've filed a cherry-pick request to ensure it will end up in future Dart SDK releases.

See https://github.com/dart-lang/sdk/issues/41802 for more information.

**Closed by mkustermann** 2020-07-17 10:39 UTC
Labels: dependency: dart, platform-web, severe: crash, tool, waiting for customer response
