### ISSUE TITLE
Google Sign In and Facebook Sign In plugins throw MissingPluginException

### ISSUE THREAD

**Issue by mike392** [flutter/flutter#78050] opened 2021-03-12 18:07 UTC
When i try to perform whichever method of Google or Facebook Auth instance i se this:

```[ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: MissingPluginException(No implementation found for method init on channel plugins.flutter.io/google_sign_in)```

1. I have upgraded to 2.12.0 version - previously it was fine
2. I have followed everything from here - https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects
3. I have problem only on Android - on iOS it works fine
4. Of course i have tried `flutter clean` and re-run the app on cold re-run NUMEROUS times
5. I tried to switch between all the channels - stable, master, dev - no luck
6. I tried to run - `flutter create . ` and re-run - no luck

It really seems that there is something wrong when making connection to corresponding `MethodChannel` implementation over binaryMessenger

The stacktrace i get is the following:
```
E/flutter (11853): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: MissingPluginException(No implementation found for method getAccessToken on channel app.meedu/flutter_facebook_auth)
E/flutter (11853): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:7)
E/flutter (11853): <asynchronous suspension>
E/flutter (11853): #1      FacebookAuth.accessToken (package:flutter_facebook_auth_platform_interface/src/method_channel_facebook_auth.dart:90:20)
E/flutter (11853): <asynchronous suspension>
E/flutter (11853): #2      LoginPage._signInWithFacebook.<anonymous closure> (package:eatandparty/view/page/login_page.dart:55:42)
E/flutter (11853): <asynchronous suspension>
E/flutter (11853): 
```

This is `flutter doctor -v` output:
```
[✓] Flutter (Channel stable, 2.0.1, on Mac OS X 10.15.7 19H15 darwin-x64, locale en-ES)
    • Flutter version 2.0.1 at /Users/mikhailbarsukou/work/apps/flutter
    • Framework revision c5a4b4029c (8 days ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/mikhailbarsukou/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 53.1.5
    • Dart plugin version 203.6912

[✓] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • macOS (desktop)             • macos         • darwin-x64     • Mac OS X 10.15.7 19H15 darwin-x64
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 89.0.4389.82

• No issues found!
```

Please, help me here because i'm totally stuck...

**Comment by mike392** [comment] 2021-03-12 18:17
Moreover, i can see that these plugins get discovered as i run `flutter run --verbose' 

``` +81 ms] Initializing file store
[   +2 ms] Done initializing file store
[  +22 ms] Skipping target: gen_localizations
[   +2 ms] Persisting file store
[   +5 ms] Done persisting file store
[   +5 ms] Skipping pub get: version match.
[  +49 ms] Found plugin firebase_auth at /Users/mikhailbarsukou/work/apps/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-1.0.1/
[   +8 ms] Found plugin firebase_auth_web at /Users/mikhailbarsukou/work/apps/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth_web-1.0.2/
[   +2 ms] Found plugin firebase_core at /Users/mikhailbarsukou/work/apps/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-1.0.1/
[   +2 ms] Found plugin firebase_core_web at /Users/mikhailbarsukou/work/apps/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core_web-1.0.1/
[   +1 ms] Found plugin flutter_facebook_auth at /Users/mikhailbarsukou/work/apps/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_facebook_auth-3.0.0+1/
[   +2 ms] Found plugin flutter_facebook_auth_web at /Users/mikhailbarsukou/work/apps/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_facebook_auth_web-2.0.0/
[   +2 ms] Found plugin flutter_plugin_android_lifecycle at /Users/mikhailbarsukou/work/apps/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_plugin_android_lifecycle-2.0.0/
[   +6 ms] Found plugin google_maps_flutter at /Users/mikhailbarsukou/work/apps/flutter/.pub-cache/hosted/pub.dartlang.org/google_maps_flutter-2.0.1/
[   +2 ms] Found plugin google_maps_flutter_web at /Users/mikhailbarsukou/work/apps/flutter/.pub-cache/hosted/pub.dartlang.org/google_maps_flutter_web-0.2.1/
[   +1 ms] Found plugin google_sign_in at /Users/mikhailbarsukou/work/apps/flutter/.pub-cache/hosted/pub.dartlang.org/google_sign_in-5.0.0/
[   +2 ms] Found plugin google_sign_in_web at /Users/mikhailbarsukou/work/apps/flutter/.pub-cache/hosted/pub.dartlang.org/google_sign_in_web-0.10.0/
[ +141 ms] Found plugin firebase_auth at /Users/mikhailbarsukou/work/apps/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-1.0.1/
[   +1 ms] Found plugin firebase_auth_web at /Users/mikhailbarsukou/work/apps/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth_web-1.0.2/
[        ] Found plugin firebase_core at /Users/mikhailbarsukou/work/apps/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-1.0.1/
[   +1 ms] Found plugin firebase_core_web at /Users/mikhailbarsukou/work/apps/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core_web-1.0.1/
[        ] Found plugin flutter_facebook_auth at /Users/mikhailbarsukou/work/apps/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_facebook_auth-3.0.0+1/
[   +1 ms] Found plugin flutter_facebook_auth_web at /Users/mikhailbarsukou/work/apps/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_facebook_auth_web-2.0.0/
[   +1 ms] Found plugin flutter_plugin_android_lifecycle at /Users/mikhailbarsukou/work/apps/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_plugin_android_lifecycle-2.0.0/
[   +3 ms] Found plugin google_maps_flutter at /Users/mikhailbarsukou/work/apps/flutter/.pub-cache/hosted/pub.dartlang.org/google_maps_flutter-2.0.1/
[   +1 ms] Found plugin google_maps_flutter_web at /Users/mikhailbarsukou/work/apps/flutter/.pub-cache/hosted/pub.dartlang.org/google_maps_flutter_web-0.2.1/
[        ] Found plugin google_sign_in at /Users/mikhailbarsukou/work/apps/flutter/.pub-cache/hosted/pub.dartlang.org/google_sign_in-5.0.0/
[   +1 ms] Found plugin google_sign_in_web at /Users/mikhailbarsukou/work/apps/flutter/.pub-cache/hosted/pub.dartlang.org/google_sign_in_web-0.10.0/
[  +33 ms] Generating /Users/mikhailbarsukou/work/develop/eatandparty/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +57 ms] ro.hardware = ranchu
[  +16 ms] Using hardware rendering with device sdk gphone x86 arm. If you notice graphics artifacts, consider enabling software rendering with "--enable-software-rendering".
[  +22 ms] Initializing file store
[        ] Done initializing file store
[   +2 ms] gen_localizations: Starting due to {InvalidatedReason.inputChanged}
[  +94 ms] gen_localizations: Complete
[   +2 ms] complete
[   +3 ms] Launching lib/main.dart on sdk gphone x86 arm in debug mode...```

**Comment by mike392** [comment] 2021-03-12 18:36
Also tried this [approach](https://github.com/flutter/flutter/issues/56548#issuecomment-625239992) - no luck

**Comment by mike392** [comment] 2021-03-12 19:06
I finally figured out what was wrong - `flutter_facebook_auth` was misconfigured for Android.

[Here](https://pub.dev/packages/flutter_facebook_auth#-important-) guys explicitly specified it.
It means that - if one plugin is not configured correctly it crushes operation of all the other plugins!

Guys, can you, please, do something to make it more explicit...? To add some logging or something - because it is SUPER inobvious what to do next with it :)

**Comment by iapicca** [comment] 2021-03-14 12:23
@mike392 
[flutter_facebook_auth](https://pub.dev/packages/flutter_facebook_auth/) is a 3rd party plugin, please open an issue in the dedicated [github](https://github.com/darwin-morocho/flutter-facebook-auth/issues)

I recommend this issue to be closed as it isn't caused by flutter

**Closed** 2021-03-14 13:18 UTC
