### ISSUE TITLE
Overflowing titles have both ellipsis and fade out

### ISSUE THREAD

**Issue by drewwarren** [flutter/flutter#4650] opened 2016-06-21 02:33 UTC
## Steps to Reproduce

http://imgur.com/HZlrDkA

The contrast of the opaque ellipsis over the fading out text looks really weird (this screenshot doesn't look as bad as other cases). I think removing the ellipsis would be great. Sorry I have not tested a native app to compare.

## Flutter Doctor

```
flutter_gallery (master *)$ flutter doctor
[✓] Flutter (on Mac OS, channel master)
    • Flutter at /Users/drewwarren/flutter
    • Framework revision e071f0bafd (2 hours ago), engine revision c69d907b49

[x] Android toolchain - develop for Android devices
    x Android Studio / Android SDK not found. Download from https://developer.android.com/sdk/
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[✓] iOS toolchain - develop for iOS devices (Xcode 7.3.1)
    • XCode at /Applications/Xcode.app/Contents/Developer
    • Xcode 7.3.1, Build version 7D1014

[✓] Atom - a lightweight development environment for Flutter
    • flutter plugin version 0.2.2
    • dartlang plugin version 0.6.12
```

**Comment by abarth** [comment] 2016-06-21 03:11
Duplicate of #4478

**Closed** 2016-06-21 03:12 UTC
