### ISSUE TITLE
SliverGridLayout does not allow arbitrary scroll offset of first child.

### ISSUE THREAD

**Issue by monkeyswarm** [flutter/flutter#64006] opened 2020-08-17 23:37 UTC
SliverGridLayout, and its render object, assume that the first child always starts at (or before) the leading edge of the scroll view. It throws an assertion if the first child is fully within the viewport. This means the scroll view cannot have any leading space before the first child.

## Steps to Reproduce

Run the complete app code below, which has a CustomScrollView, with a single child, using SliverGridLayout to lay out that child at a scroll offset of 300.

Output:
```
══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
The following assertion was thrown during performLayout():
Assertion failed:
file:///Users/diglesia/Source/flutter/packages/flutter/lib/src/rendering/sliver_grid.dart:608:12
childScrollOffset(firstChild) <= scrollOffset
is not true

The relevant error-causing widget was:
  SliverGrid file:///Users/diglesia/Source/misc/SliverGridOffsetAssertion/lib/main.dart:14:11

```

App code:
```
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) => MaterialApp(
      title: 'SliverGridLayout Demo',
      home: CustomScrollView(
        slivers: [
          SliverGrid(
              delegate: SliverChildBuilderDelegate(
                      (context, index) => Container(color: Color(0x880000FF)),
                  childCount: 1),
              gridDelegate: DemoSliverGridDelegate())
        ],
      )
    );
}

class DemoSliverGridDelegate implements SliverGridDelegate {
  @override
  SliverGridLayout getLayout(SliverConstraints constraints) {
    return DemoSliverGridLayout();
  }

  @override
  bool shouldRelayout(SliverGridDelegate oldDelegate) {
    return false;
  }
}

class DemoSliverGridLayout implements SliverGridLayout {
  @override
  double computeMaxScrollOffset(int childCount) => 1000;
  
  @override
  SliverGridGeometry getGeometryForChildIndex(int index) => SliverGridGeometry(
      scrollOffset: 300.0,
      crossAxisOffset: 0.0,
      mainAxisExtent: 30.0,
      crossAxisExtent: 40.0,
    );

  @override
  int getMaxChildIndexForScrollOffset(double scrollOffset) => 0;

  @override
  int getMinChildIndexForScrollOffset(double scrollOffset) => 0;
}

```

Flutter doctor -v
```
[✓] Flutter (Channel master, 1.20.0-3.0.pre.11, on Mac OS X 10.15.6 19G73, locale en-US)
    • Flutter version 1.20.0-3.0.pre.11 at /Users/diglesia/Source/flutter
    • Framework revision 715d70a1ba (8 weeks ago), 2020-06-23 20:53:40 -0700
    • Engine revision 57d1333999
    • Dart version 2.9.0 (build 2.9.0-18.0.dev 5a6c1e5158)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0-rc2)
    • Android SDK at /Users/diglesia/Library/Android/sdk
    • Platform android-29, build-tools 30.0.0-rc2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode_11.2.1.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    ✗ CocoaPods installed but not working.
        You appear to have CocoaPods installed but it is not working.
        This can happen if the version of Ruby that CocoaPods was installed with is different from the one being used to invoke it.
        This can usually be fixed by re-installing CocoaPods. For more info, see https://github.com/flutter/flutter/issues/14293.
      To re-install CocoaPods, run:
        sudo gem install cocoapods

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Community Edition (version 2019.3.5)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 48.0.2
    • Dart plugin version 193.7361

[✓] Connected device (4 available)
    • SM T860       • R52MA0M1B7Z • android-arm64  • Android 10 (API 29)
    • macOS desktop • macos       • darwin-x64     • Mac OS X 10.15.6 19G73
    • Web Server    • web-server  • web-javascript • Flutter Tools
    • Chrome        • chrome      • web-javascript • Google Chrome 84.0.4147.125

```

**Comment by HansMuller** [comment] 2020-08-18 15:31
CC @Piinks

**Comment by monkeyswarm** [comment] 2020-08-18 16:17
Note that I attempted a PR to remove that assertion, however, that causes bad behavior with hit testing (i.e. I would touch the scroll child, which had a gesture detector but no gesture was added to the arena for the child, only the parent scrollview).

I have a temporary workaround which involves injecting a transparent child at the scrolloffset position (i.e. right at the edge of the viewport of the scroll).

**Comment by Piinks** [comment] 2020-08-18 17:07
This is a duplicate of https://github.com/flutter/flutter/issues/28056
I am going to close that one since this one has been escalated.

**Comment by Piinks** [comment] 2020-08-18 17:50
Bringing over from original issue, arbitrary placement within a SliverGrid is expected per the documentation:
> *The tiles can be placed arbitrarily*, but it is more efficient to place tiles in roughly in order by scroll offset because grids reify a contiguous sequence of children.

**Comment by darshankawar** [comment] 2020-08-27 10:23
Issue replicable on latest stable (1.20.2).

<details>
<summary>log</summary>

```
          I/flutter (20790): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (20790): The following assertion was thrown during performLayout():
I/flutter (20790): 'package:flutter/src/rendering/sliver_grid.dart': Failed assertion: line 609 pos 12:
I/flutter (20790): 'childScrollOffset(firstChild) <= scrollOffset': is not true.
I/flutter (20790): 
I/flutter (20790): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (20790): more information in this error message to help you determine and fix the underlying cause.
I/flutter (20790): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (20790):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter (20790): 
I/flutter (20790): The relevant error-causing widget was:
I/flutter (20790):   SliverGrid
I/flutter (20790):   file:///Users/deeptibelsare/Documents/DarshanUdacity/Flutter/hello_world/lib/main.dart:10072:11
I/flutter (20790): 
I/flutter (20790): When the exception was thrown, this was the stack:
I/flutter (20790): #2      RenderSliverGrid.performLayout (package:flutter/src/rendering/sliver_grid.dart:609:12)
I/flutter (20790): #3      RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
I/flutter (20790): #4      RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:471:13)
I/flutter (20790): #5      RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1465:12)
I/flutter (20790): #6      RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1374:20)
I/flutter (20790): #7      RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
I/flutter (20790): #8      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
I/flutter (20790): #9      RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
I/flutter (20790): #10     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
I/flutter (20790): #11     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
I/flutter (20790): #12     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
I/flutter (20790): #13     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
I/flutter (20790): #14     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
I/flutter (20790): #15     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
I/flutter (20790): #16     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
I/flutter (20790): #17     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
I/flutter (20790): #18     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
I/flutter (20790): #19     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
I/flutter (20790): #20     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
I/flutter (20790): #21     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
I/flutter (20790): #22     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
I/flutter (20790): #23     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
I/flutter (20790): #24     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
I/flutter (20790): #25     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
I/flutter (20790): #26     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
I/flutter (20790): #27     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
I/flutter (20790): #28     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
I/flutter (20790): #29     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
I/flutter (20790): #30     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
I/flutter (20790): #31     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
I/flutter (20790): #32     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
I/flutter (20790): #33     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
I/flutter (20790): #34     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
I/flutter (20790): #35     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
I/flutter (20790): #36     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
I/flutter (20790): #37     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
I/flutter (20790): #38     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
I/flutter (20790): #39     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
I/flutter (20790): #40     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
I/flutter (20790): #41     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3228:13)
I/flutter (20790): #42     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
I/flutter (20790): #43     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
I/flutter (20790): #44     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
I/flutter (20790): #45     _RenderTheatre.performLayout (package:flutter/src/widgets/overlay.dart:702:15)
I/flutter (20790): #46     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
I/flutter (20790): #47     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
I/flutter (20790): #48     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
I/flutter (20790): #49     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
I/flutter (20790): #50     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
I/flutter (20790): #51     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
I/flutter (20790): #52     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
I/flutter (20790): #53     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
I/flutter (20790): #54     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
I/flutter (20790): #55     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
I/flutter (20790): #56     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
I/flutter (20790): #57     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
I/flutter (20790): #58     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
I/flutter (20790): #59     RenderView.performLayout (package:flutter/src/rendering/view.dart:170:13)
I/flutter (20790): #60     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (20790): #61     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:889:18)
I/flutter (20790): #62     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:404:19)
I/flutter (20790): #63     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:867:13)
I/flutter (20790): #64     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:286:5)
I/flutter (20790): #65     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117:15)
I/flutter (20790): #66     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1056:9)
I/flutter (20790): #67     SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:865:7)
I/flutter (20790): (elided 13 frames from class _AssertionError, class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)
I/flutter (20790): 
I/flutter (20790): The following RenderObject was being processed when the exception was fired: RenderSliverGrid#cd70f relayoutBoundary=up1 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE:
I/flutter (20790):   creator: SliverGrid ← Viewport ← IgnorePointer-[GlobalKey#79673] ← Semantics ← _PointerListener ←
I/flutter (20790):     Listener ← _GestureSemantics ←
I/flutter (20790):     RawGestureDetector-[LabeledGlobalKey<RawGestureDetectorState>#2929f] ← _PointerListener ← Listener
I/flutter (20790):     ← _ScrollableScope ← _ScrollSemantics-[GlobalKey#84335] ← ⋯
I/flutter (20790):   parentData: paintOffset=Offset(0.0, 0.0) (can use size)
I/flutter (20790):   constraints: SliverConstraints(AxisDirection.down, GrowthDirection.forward, ScrollDirection.idle,
I/flutter (20790):     scrollOffset: 0.0, remainingPaintExtent: 592.0, crossAxisExtent: 360.0, crossAxisDirection:
I/flutter (20790):     AxisDirection.right, viewportMainAxisExtent: 592.0, remainingCacheExtent: 842.0, cacheOrigin: 0.0)
I/flutter (20790):   geometry: null
I/flutter (20790):   currently live children: 0 to 0
I/flutter (20790): This RenderObject had the following descendants (showing up to depth 5):
I/flutter (20790):     child with index 0: RenderIndexedSemantics#f4495 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (20790):       child: RenderRepaintBoundary#9d8ef NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (20790):         child: _RenderColoredBox#f6393 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (20790):           child: RenderLimitedBox#c62f1 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (20790):             child: RenderConstrainedBox#ea516 NEEDS-PAINT
I/flutter (20790): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (20790): Another exception was thrown: NoSuchMethodError: The method 'debugAssertIsValid' was called on null.
I/flutter (20790): Another exception was thrown: NoSuchMethodError: The getter 'visible' was called on null.
E/BpSurfaceComposerClient(20790): Failed to transact (-1)
E/BpSurfaceComposerClient(20790): Failed to transact (-1)
I/FIAM.Headless(20790): Fetching campaigns from service.
W/DynamiteModule(20790): Local module descriptor class for providerinstaller not found.
I/DynamiteModule(20790): Considering local module providerinstaller:0 and remote module providerinstaller:0
W/ProviderInstaller(20790): Failed to load providerinstaller module: No acceptable module found. Local version is 0 and remote version is 0.
W/FIAM.Headless(20790): Service fetch error: PERMISSION_DENIED: Firebase In-App Messaging API has not been used in project 613586627532 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/firebaseinappmessaging.googleapis.com/overview?project=613586627532 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.

══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
The following assertion was thrown during performLayout():
'package:flutter/src/rendering/sliver_grid.dart': Failed assertion: line 609 pos 12:
'childScrollOffset(firstChild) <= scrollOffset': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

The relevant error-causing widget was:
  SliverGrid
  file:///Users/deeptibelsare/Documents/DarshanUdacity/Flutter/hello_world/lib/main.dart:10072:11

When the exception was thrown, this was the stack:
#2      RenderSliverGrid.performLayout (package:flutter/src/rendering/sliver_grid.dart:609:12)
#3      RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
#4      RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:471:13)
#5      RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1465:12)
#6      RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1374:20)
#7      RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
#8      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
#9      RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
#10     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
#11     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
#12     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
#13     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
#14     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
#15     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
#16     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
#17     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
#18     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
#19     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
#20     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
#21     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
#22     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
#23     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
#24     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
#25     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
#26     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
#27     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
#28     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
#29     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
#30     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
#31     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
#32     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
#33     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
#34     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
#35     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
#36     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
#37     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
#38     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
#39     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
#40     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
#41     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3228:13)
#42     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
#43     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
#44     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
#45     _RenderTheatre.performLayout (package:flutter/src/widgets/overlay.dart:702:15)
#46     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
#47     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
#48     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
#49     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
#50     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
#51     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
#52     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
#53     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
#54     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
#55     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
#56     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
#57     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
#58     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
#59     RenderView.performLayout (package:flutter/src/rendering/view.dart:170:13)
#60     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1632:7)
#61     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:889:18)
#62     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:404:19)
#63     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:867:13)
#64     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:286:5)
#65     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117:15)
#66     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1056:9)
#67     SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:865:7)
(elided 6 frames from class _AssertionError, class _RawReceivePortImpl, class _Timer, and dart:async-patch)

The following RenderObject was being processed when the exception was fired: RenderSliverGrid#cd70f relayoutBoundary=up1 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE:
  needs compositing
  creator: SliverGrid ← Viewport ← IgnorePointer-[GlobalKey#79673] ← Semantics ← _PointerListener ←
    Listener ← _GestureSemantics ←
    RawGestureDetector-[LabeledGlobalKey<RawGestureDetectorState>#2929f] ← _PointerListener ← Listener
    ← _ScrollableScope ← _ScrollSemantics-[GlobalKey#84335] ← ⋯
  parentData: paintOffset=Offset(0.0, 0.0) (can use size)
  constraints: SliverConstraints(AxisDirection.down, GrowthDirection.forward, ScrollDirection.idle,
    scrollOffset: 0.0, remainingPaintExtent: 592.0, crossAxisExtent: 360.0, crossAxisDirection:
    AxisDirection.right, viewportMainAxisExtent: 592.0, remainingCacheExtent: 842.0, cacheOrigin: 0.0)
  geometry: null
  currently live children: 0 to 0
This RenderObject had the following descendants (showing up to depth 5):
    child with index 0: RenderIndexedSemantics#f4495 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
      child: RenderRepaintBoundary#9d8ef NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
        child: _RenderColoredBox#f6393 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
          child: RenderLimitedBox#c62f1 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
            child: RenderConstrainedBox#ea516 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════════════════════════
The following assertion was thrown during performLayout():
'package:flutter/src/rendering/sliver_grid.dart': Failed assertion: line 609 pos 12: 'childScrollOffset(firstChild) <= scrollOffset': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

The relevant error-causing widget was: 
  SliverGrid file:///Users/deeptibelsare/Documents/DarshanUdacity/Flutter/hello_world/lib/main.dart:10072:11
When the exception was thrown, this was the stack: 
#2      RenderSliverGrid.performLayout (package:flutter/src/rendering/sliver_grid.dart:609:12)
#3      RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
#4      RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:471:13)
#5      RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1465:12)
#6      RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1374:20)
...
The following RenderObject was being processed when the exception was fired: RenderSliverGrid#cd70f relayoutBoundary=up1 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...  needs compositing
...  parentData: paintOffset=Offset(0.0, 0.0) (can use size)
...  constraints: SliverConstraints(AxisDirection.down, GrowthDirection.forward, ScrollDirection.idle, scrollOffset: 0.0, remainingPaintExtent: 592.0, crossAxisExtent: 360.0, crossAxisDirection: AxisDirection.right, viewportMainAxisExtent: 592.0, remainingCacheExtent: 842.0, cacheOrigin: 0.0)
...  geometry: null
...  currently live children: 0 to 0
RenderObject: RenderSliverGrid#cd70f relayoutBoundary=up1 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
  needs compositing
  parentData: paintOffset=Offset(0.0, 0.0) (can use size)
  constraints: SliverConstraints(AxisDirection.down, GrowthDirection.forward, ScrollDirection.idle, scrollOffset: 0.0, remainingPaintExtent: 592.0, crossAxisExtent: 360.0, crossAxisDirection: AxisDirection.right, viewportMainAxisExtent: 592.0, remainingCacheExtent: 842.0, cacheOrigin: 0.0)
  geometry: null
  currently live children: 0 to 0
...  child with index 0: RenderIndexedSemantics#f4495 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...    needs compositing
...    parentData: crossAxisOffset=0.0; index=0; layoutOffset=300.0
...    constraints: BoxConstraints(w=40.0, h=30.0)
...    semantic boundary
...    size: Size(40.0, 30.0)
...    index: 0
...    child: RenderRepaintBoundary#9d8ef NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...      needs compositing
...      parentData: <none> (can use size)
...      constraints: BoxConstraints(w=40.0, h=30.0)
...      size: Size(40.0, 30.0)
...      usefulness ratio: no metrics collected yet (never painted)
...      child: _RenderColoredBox#f6393 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...        parentData: <none> (can use size)
...        constraints: BoxConstraints(w=40.0, h=30.0)
...        size: Size(40.0, 30.0)
...        behavior: opaque
...        child: RenderLimitedBox#c62f1 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(w=40.0, h=30.0)
...          size: Size(40.0, 30.0)
...          maxWidth: 0.0
...          maxHeight: 0.0
════════════════════════════════════════════════════════════════════════════════════════════════════

Another exception was thrown: NoSuchMethodError: The method 'debugAssertIsValid' was called on null.

════════ Exception caught by rendering library ═════════════════════════════════════════════════════
The method 'debugAssertIsValid' was called on null.
Receiver: null
Tried calling: debugAssertIsValid()
The relevant error-causing widget was: 
  CustomScrollView file:///Users/deeptibelsare/Documents/DarshanUdacity/Flutter/hello_world/lib/main.dart:10070:13
════════════════════════════════════════════════════════════════════════════════════════════════════

Another exception was thrown: NoSuchMethodError: The getter 'visible' was called on null.

════════ Exception caught by rendering library ═════════════════════════════════════════════════════
The getter 'visible' was called on null.
Receiver: null
Tried calling: visible
The relevant error-causing widget was: 
  CustomScrollView file:///Users/deeptibelsare/Documents/DarshanUdacity/Flutter/hello_world/lib/main.dart:10070:13
════════════════════════════════════════════════════════════════════════════════════════════════════
W/libEGL  (20790): EGLNativeWindowType 0xd2533808 disconnect failed
```

</details>

**Closed** 2020-09-03 18:20 UTC
Labels: P2, customer: google, f: scrolling, found in release: 1.20, framework, has reproducible steps, passed first triage
