### ISSUE TITLE
Xiaomi devices failing check in flutter/engine/shell/common/switches.cc

### ISSUE THREAD

**Issue by dguralnick** [flutter/flutter#29160] opened 2019-03-11 15:29 UTC
The offending line (133) was added https://github.com/flutter/engine/pull/7588

https://github.com/flutter/engine/blame/master/shell/common/switches.cc

We have an internal crash cluster I can share w/ more detail than I'll paste in here. This looks like it's only happening for xiaomi devices, though I'm not sure what percentage of them are affected. I do not have a xiaomi device, and I not been able to reproduce the issue.

Sample error message:

`Abort message: '[FATAL:flutter/shell/common/switches.cc(133)] Check failed: mapping && size. Unable to resolve symbols: _binary_icudtl_dat`

**Comment by jason-simmons** [comment] 2019-03-13 00:53
Duplicate of https://github.com/flutter/flutter/issues/28208

**Closed by jason-simmons** 2019-03-13 00:53 UTC
Labels: customer: mulligan (g3), engine, severe: customer blocker, ▣ platform-android
