### ISSUE TITLE
Hero widget uses Curves.fastOutSlowIn for its animation and there isn't an option to customize it

### ISSUE THREAD

**Issue by ercantomac** [flutter/flutter#158921] opened 2024-11-14 13:02 UTC
### Use case

I implemented a custom RectTween to use with my Hero widget, but the resulting animation didn't seem to be using the animation curve I wanted it to use. So I investigated the Hero class's code, and I discovered that it uses Curves.fastOutSlowIn by default for the animation.

File: "flutter\lib\src\widgets\heroes.dart"
Line 459 on Stable channel (version 3.24.3)

```
Animation<double> get animation {
    return _animation ??= CurvedAnimation(
      parent: (type == HeroFlightDirection.push) ? toRoute.animation! : fromRoute.animation!,
      curve: Curves.fastOutSlowIn,
      reverseCurve: isDiverted ? null : Curves.fastOutSlowIn.flipped,
    );
}
```

### Proposal

My proposal is to make it customizable. Something like:

```
Hero (
    tag: tag,
    curve: Curves.ease,
    child: ...
)
```

**Comment by danagbemava-nc** [comment] 2024-11-14 13:19
Closing this as a duplicate of https://github.com/flutter/flutter/issues/26150. 

Kindly subscribe to the original issue for updates. 

Thank you

**Closed by danagbemava-nc** 2024-11-14 13:19 UTC
Labels: in triage
