### ISSUE TITLE
Flutter Project is not running when using indian domain

### ISSUE THREAD

**Issue by max202021** [flutter/flutter#44434] opened 2019-11-08 11:20 UTC
I created a project using following command on windows environment 

flutter create --org in.myorg helloworld

Project is created successfully

Flutter version is as below 
Flutter 1.9.1+hotfix.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 1aedbb1835 (3 weeks ago) • 2019-10-17 08:37:27 -0700
Engine • revision b863200c37
Tools • Dart 2.5.0

When I run the code I get following error 

e: D:\Project\test\helloworld\android\app\src\main\kotlin\in\myorg\helloworld\MainActivity.kt: (1, 9): Package name must be a '.'-separated identifier list

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 12s
Running Gradle task 'assembleDebug'...
Running Gradle task 'assembleDebug'... Done                        13.5s
Gradle task assembleDebug failed with exit code 1

.in domains are not allowed in flutter? using an incorrect domain will face issue while publishing app?

**Flutter Analyze Output**

D:\Project\test\helloworld>flutter analyze
Analyzing helloworld...
No issues found! (ran in 4.0s)

**Flutter Doctor Output** 

```
D:\Project\test\helloworld>flutter doctor -v
[√] Flutter (Channel stable, v1.9.1+hotfix.5, on Microsoft Windows [Version 10.0.17763.805], locale en-IN)
    • Flutter version 1.9.1+hotfix.5 at C:\src\flutter\flutter
    • Framework revision 1aedbb1835 (3 weeks ago), 2019-10-17 08:37:27 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\Max\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.40.0)
    • VS Code at C:\Users\Max\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.6.0

[√] Connected device (1 available)
    • GM1911 • 9db98713 • android-arm64 • Android 10 (API 29)

• No issues found!
```

**Comment by iapicca** [comment] 2019-11-08 13:26
Hi @max202021 
could you please provide your `flutter run --verbose`
thank you

**Comment by max202021** [comment] 2019-11-08 15:20
Hi @iapicca ,

Please find attached file. ( it has 1000 lines)

[Flutter Run Verbose.log](https://github.com/flutter/flutter/files/3825134/Flutter.Run.Verbose.log)

**Comment by mannprerak2** [comment] 2019-11-08 18:04
Follow this #16521
You have to manually go to the file and back ticks like this ->
package **\`in`**.championswimmer.myapp

**OR**

you can use JAVA instead
Delete android folder and run
``` flutter create -a java --org in.myorg . ```

**Comment by jonahwilliams** [comment] 2019-11-08 18:06
Since `in` is a keywork in kotlin, the orgname must be escaped if it contains it. Closing as a duplicate of https://github.com/flutter/flutter/issues/16521

**Closed by jonahwilliams** 2019-11-08 18:06 UTC
