### ISSUE TITLE
When starting the application, MediaQuery.of(context).size.width is 0, resulting in a persistent white screen

### ISSUE THREAD

**Issue by laterdayi** [flutter/flutter#139980] opened 2023-12-12 12:53 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

When starting the application, MediaQuery.of(context).size.width is 0, resulting in a persistent white screen

### Expected results

When starting the application, MediaQuery.of(context).size.width is 0, resulting in a persistent white screen

### Actual results

When starting the application, MediaQuery.of(context).size.width is 0, resulting in a persistent white screen

### Code sample

```
import 'dart:async';
import 'dart:io';

import 'package:bot_toast/bot_toast.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:get/get.dart';
import 'package:pms_mobile/global.dart';
import 'package:pms_mobile/i18n/index.dart';
import 'package:pms_mobile/pages/not_found/index.dart';
import 'package:pms_mobile/pages/setting/appearance.dart';
import 'package:pms_mobile/pages/setting/language.dart';
import 'package:pms_mobile/store/index.dart';
import 'package:pms_mobile/theme.dart';
import 'package:pms_mobile/utils/index.dart';

import 'routes/index.dart';

final botToastBuilder = BotToastInit();

Future<void> main() async {
  runZonedGuarded<Future<void>>(() async {
    try {
      WidgetsFlutterBinding.ensureInitialized();
      await Global.init();
      runApp(const MyApp());
      if (Platform.isAndroid) {
        SystemUiOverlayStyle systemUiOverlayStyle = const SystemUiOverlayStyle(
          statusBarColor: Colors.transparent,
          // systemNavigationBarColor: Color.fromRGBO(53, 64, 85, 1),
        );
        SystemChrome.setSystemUIOverlayStyle(systemUiOverlayStyle);
      }
    } catch (e) {
      print(e);
    }
  }, (error, stack) {
    UtilLog.error('runZonedGuarded', error, stack: stack);
  });
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    print(MediaQuery.of(context).size.width);
    print(MediaQuery.of(context).size.height);
    return GetMaterialApp(
      unknownRoute: GetPage(name: '/404', page: () => const NotFoundPage()),
      translations: TranslationService(),
      localizationsDelegates: const [
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
      ],
      locale: EnumLanguageMode.getMode(AppStore.to.appConfig.language),
      supportedLocales: const [
        Locale('zh', 'CN'),
        Locale('en', 'US'),
      ],
      fallbackLocale: const Locale('zh', 'CN'),
      initialRoute: AppPages.initial,
      getPages: AppPages.routes,
      theme: AppTheme.light(),
      darkTheme: AppTheme.dark(),
      themeMode: EnumThemeMode.getMode(AppStore.to.appConfig.themeMode),
      debugShowCheckedModeBanner: false,
      navigatorObservers: [BotToastNavigatorObserver()],
      builder: (context, child) {
        print('build');
        child = botToastBuilder(context, child);
        return child;
      },
    );
  }
}

```
```
import 'package:flutter/services.dart';
import 'package:get/get.dart';
import 'package:pms_mobile/service/index.dart';
import 'package:pms_mobile/store/index.dart';
import 'package:pms_mobile/utils/index.dart';

class Global {
  static Future<void> init() async {
    try {
      await Get.putAsync(() => StorageService().init());
      Get.put<AppStore>(AppStore());
      Get.put<HttpService>(HttpService());
      Get.put<UserStore>(UserStore());
      await _initNotificationService();
      await SystemChrome.setPreferredOrientations([DeviceOrientation.portraitUp, DeviceOrientation.portraitDown]);
      // checkAppVersion();
    } catch (e) {
    }
  }
}

_initNotificationService() async {
  try {
    print('_initNotificationService');
    Get.put<NotificationService>(NotificationService());
    await NotificationService.to.createNotificationChannel(kAndroidChannelNewMessage);
  } catch (e) {
  }
}

```

### Screenshots or Video

error  

 ![image](https://github.com/flutter/flutter/assets/122137647/7caf79e7-9dd7-41fc-abc9-e16e5e7ba2f4)

![1702380872237](https://github.com/flutter/flutter/assets/122137647/8d568e30-5351-4290-babc-a479b59566a3)

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

![image](https://github.com/flutter/flutter/assets/122137647/f5f12076-4cf6-488e-a7fd-3f9634e08a37)

**Comment by huycozy** [comment] 2023-12-13 05:28
Hi @laterdayi 
In order to address the issue properly, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code so that we may verify this. 

Please provide the information (flutter doctor output) in text format instead of a screenshot for better readability.

Thank you!

**Comment by laterdayi** [comment] 2023-12-13 05:45
@huycozy  Even with the newly created flutter project, this problem persists,

**Comment by laterdayi** [comment] 2023-12-13 05:45
![image](https://github.com/flutter/flutter/assets/122137647/a3746eb0-1775-4567-9f5f-76d25066f7d2)

After I cloned the project, I did nothing but print MediaQuery.of(context).size

**Comment by laterdayi** [comment] 2023-12-13 05:46
```
Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel stable, 3.16.3, on Microsoft Windows [版本 10.0.19045.3693], locale zh-CN)
    ! Warning: `flutter` on your path resolves to E:\fvm\versions\stable\bin\flutter, which is not inside your current
      Flutter SDK checkout at E:\fvm\default. Consider adding E:\fvm\default\bin to the front of your path.
    ! Warning: `dart` on your path resolves to E:\fvm\versions\stable\bin\dart, which is not inside your current Flutter
      SDK checkout at E:\fvm\default. Consider adding E:\fvm\default\bin to the front of your path.
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Android Studio (version 2022.3)
[√] Connected device (1 available)
[!] Network resources
    X A network error occurred while checking "https://github.com/": 信号灯超时时间已到


! Doctor found issues in 2 categories.
```

**Comment by laterdayi** [comment] 2023-12-13 06:43
[log.txt](https://github.com/flutter/flutter/files/13657170/log.txt)

This is my logcat log

**Comment by laterdayi** [comment] 2023-12-13 06:53
```
12-13 14:44:37.014 I/GmsDebugLogger( 9252): [83] 1 [tflite_dynamite, vision.barcode]
12-13 14:44:37.015 D/OplusDisplayPolicy( 1984): com.semi.pms_mobile, no change cutoutMode: 1
12-13 14:44:37.017 I/flutter (13713): 0.0
12-13 14:44:37.017 I/flutter (13713): 0.0
12-13 14:44:37.017 W/Vision  ( 9252): Request for optional module download of tflite_dynamite failed. Request again.
12-13 14:44:37.018 W/Vision  ( 9252): Request for optional module download of barcode failed. Request again.
12-13 14:44:37.018 V/WindowManager( 1984): Changing focus from null to Window{d429bf9 u0 com.semi.pms_mobile/com.semi.pms_mobile.MainActivity},diplayid=0
12-13 14:44:37.019 I/Vision  ( 9252): Schedule retrying download tflite_dynamite,barcode at 1251045089 with backoff 40 seconds
12-13 14:44:37.019 D/CompactWindowManagerService( 1984): notifyCompactWindowState task: Task{e8b0f88 #38092 type=standard A=10394:com.semi.pms_mobile U=0 visible=true mode=fullscreen translucent=false sz=1}; hasFocus: true
12-13 14:44:37.019 D/ActivityTaskManager( 1984): onWindowFocusChanged Task{e8b0f88 #38092 type=standard A=10394:com.semi.pms_mobile U=0 visible=true mode=fullscreen translucent=false sz=1} would transfer to compact
12-13 14:44:37.021 D/Theia.NoFocusWindow( 1984): FocusWindowErrorScene cancelCheckFreezeScreen
12-13 14:44:37.022 D/CompatibilityChangeReporter( 1984): Compat change id reported: 158002302; UID 10394; state: ENABLED
12-13 14:44:37.023 D/ExtensionsLoader(13713): createInstance(64bit) : createExtendedFactory
12-13 14:44:37.023 D/ExtensionsLoader(13713): Opened libSchedAssistExtImpl.so
12-13 14:44:37.024 V/OplusZoomWindowDecorViewHelper(13713): setLastReportedMergedConfiguration mZoomDisplayHeight: 2340 getDecorView.261686923
12-13 14:44:37.029 D/OplusMovieIdle( 1145): updateLayerStacks,mOmiSupport is not supoort
12-13 14:44:37.029 I/SDM     ( 1002): HWCDisplay::GetColorModeCount: Supported color mode count = 3
12-13 14:44:37.029 I/SDM     ( 1002): HWCDisplay::GetColorModes: Color mode = 0 is supported
12-13 14:44:37.029 I/SDM     ( 1002): HWCDisplay::GetColorModes: Color mode = 7 is supported
12-13 14:44:37.029 I/SDM     ( 1002): HWCDisplay::GetColorModes: Color mode = 9 is supported
12-13 14:44:37.029 D/hw-ProcessState(13713): Binder ioctl to enable oneway spam detection failed: Invalid argument
12-13 14:44:37.042 D/OplusLayer( 1145): ~Layer() sequence=30659, name=Surface(name=1651a6b StatusBar)/@0x2524f8a - animation-leash of insets_animation#1 0xb400006ff56c5480
12-13 14:44:37.042 D/OplusLayer( 1145): ~Layer() sequence=30660, name=Surface(name=b742999 NavigationBar0)/@0xe66ed0c - animation-leash of insets_animation#0 0xb400006ff57c8740
12-13 14:44:37.043 D/OplusMovieIdle( 1145): updateLayerStacks,mOmiSupport is not supoort
12-13 14:44:37.043 I/ClipboardManagerTransactionHelper( 1984): Invalid transaction code = 6
12-13 14:44:37.044 I/ClipboardManagerTransactionHelper( 1984): Invalid transaction code = 6
12-13 14:44:37.058 D/OplusMovieIdle( 1145): updateLayerStacks,mOmiSupport is not supoort
12-13 14:44:37.059 V/OplusZoomWindowManagerService( 1984): onAnimationFinished:  r = ActivityRecord{b213d21 u0 com.semi.pms_mobile/.MainActivity t38092}
12-13 14:44:37.059 I/OplusAppSwitchManagerService( 1984):  handleAppVisible , r = ActivityRecord{b213d21 u0 com.semi.pms_mobile/.MainActivity t38092}
12-13 14:44:37.059 W/InputMethodManager(13713): Ignoring showSoftInput() as view=io.flutter.embedding.android.r{56b661 VFE...... .F....ID 0,0-1080,2292 #1} is not served.
12-13 14:44:37.060 W/InputMethodManager(13713): Ignoring showSoftInput() as view=io.flutter.embedding.android.r{56b661 VFE...... .F....ID 0,0-1080,2292 #1} is not served.
12-13 14:44:37.060 V/OplusZoomWindowManagerService( 1984): onAnimationFinished:  r = ActivityRecord{c64d61d u0 com.android.launcher/.Launcher t38060}
12-13 14:44:37.062 I/flutter (13713): 360.0
12-13 14:44:37.062 I/flutter (13713): 764.0
12-13 14:44:37.065 W/ActivityManager( 1984): setGlThreads detect 13713 13738
12-13 14:44:37.073 D/OplusLayer( 1145): setBuffer sequence=30667, name=SurfaceView[com.semi.pms_mobile/com.semi.pms_mobile.MainActivity](BLAST)#0
12-13 14:44:37.073 I/OplusLayer( 1145): VRR [FRTC] update from -1 to 0
12-13 14:44:37.073 D/SurfaceComposerClient(13713): VRR [FRTC] client handle [bufferId:18446744073709551615 framenumber:0] [ffffffff, ffffffff]
12-13 14:44:37.074 D/OplusMovieIdle( 1145): updateLayerStacks,mOmiSupport is not supoort
```

**Comment by huycozy** [comment] 2023-12-13 09:54
Thanks for the update. This is working as intended. Since you run the project in release mode, the Dart code runs faster (some known/related issues: https://github.com/flutter/flutter/issues/25827, https://github.com/flutter/flutter/issues/106858). 

Closing this as a duplicate of those issues.

**Closed by huycozy** 2023-12-13 09:54 UTC
Labels: in triage
