### ISSUE TITLE
Flutter driver - wait for text of specific element

### ISSUE THREAD

**Issue by chris-rutkowski** [flutter/flutter#52940] opened 2020-03-20 07:16 UTC
[✓] Flutter (Channel beta, v1.14.6, on Mac OS X 10.15.3 19D76, locale en-TH)

I am experiencing a flaky test.

```
    await driver.tap(find.byValueKey('first-name-field'));
    await driver.enterText('');
//    await Future.delayed(Duration(milliseconds: 17), () {});
    expect(
      await driver.getText(find.byValueKey('first-name-error')),
      equals('Field can't be empty.'),
    );
    await driver.enterText('$#@');
//    await Future.delayed(Duration(milliseconds: 17), () {});
    expect(
      await driver.getText(find.byValueKey('first-name-error')),
      equals('Field contains unsupported characters.'),
    );
    await driver.enterText('Chris');
//    await Future.delayed(Duration(milliseconds: 17), () {});
    await driver.waitForAbsent('first-name-error');
```

90% of the time the test succeeds, but occasionally the expectations see the previous values. These error labels are built by StreamBuilder. "onChanged" event of text field is adding events to the steam.

As you see in the commented code I attempted to add some delays - it helped a bit but tests are still flaky.

I see you have the following method:

```
await driver.waitFor(find.text('Field can\'t be empty.!'))
```

However on my screen there is more than 1 label that can have this value at the same time. 

**Question**
Can I wait for a specific label to have the expected text?
Something like (I made up this code):

```
await driver.waitFor(find.byValueKey('first-name-error').text('Field can\'t be empty.!'))
```

**Comment by chris-rutkowski** [comment] 2020-03-22 03:59
I've come up with something like this, hope it will be useful for community and maybe we can add it to the official code?

```
extension WaitForText on FlutterDriver {
  Future<void> waitForText(SerializableFinder finder, String text,
      {int retries = 10}) async {
    try {
      expect(await getText(finder), equals(text));
    } catch (_) {
      if (retries == 0) {
        rethrow;
      }
      await Future.delayed(Duration(milliseconds: 17), () {});
      await waitForText(finder, text, retries: retries - 1);
    }
  }
}
```

**Comment by nerder** [comment] 2020-04-02 08:43
We attempt to do something similar, but you can any function that returns a text value, and it will wait 30 seconds until it matches the expected value.

This is very useful in reducing the flakiness of the tests, especially while working with Streams and data over the network.

```dart
const defaultTimeout = Duration(seconds: 30);

extension Util on FlutterDriver {
  Future<String> waitForValue(Future<String> Function() f, String expectedValue,
          {Duration timeout = defaultTimeout}) async =>
      _getTextValueFromFuture(f, expectedValue).timeout(timeout);
}

Future<String> _getTextValueFromFuture(
    Future<String> Function() f, String expectedValue) async {
  if (await f.call() == expectedValue) {
    return expectedValue;
  }
  return _getTextValueFromFuture(f, expectedValue);
}
```

Maybe we can start working on a PR in order to add such a method to the driver.

cc @collinjackson

**Comment by dnfield** [comment] 2021-09-30 16:55
There are a lot of reasons this could be happening, but we'd really need a full reproduction to figure out what's going on here.

I'm going to close this, since the Flutter team does not support flutter_driver for external usage - it is effectively a tool we use internally for performance testing specific cases that cannot work with package:integration_test. I would recommend attempting to use package:integration_test for your integration tests, and if you find this issue persists with that please feel free to file a new one with a full reproduction showing the bug.

**Closed by dnfield** 2021-09-30 16:55 UTC
Labels: a: tests, tool, t: flutter driver, a: typography
