### ISSUE TITLE
go_router navigation issue with redirect + context.push + MediaQuery.of(context)

### ISSUE THREAD

**Issue by ozbonus** [flutter/flutter#126909] opened 2023-05-16 09:13 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Within go_router's redirect callback make a call to `MediaQuery.of(context)`. You don't have to do anything with it, just that line being present is enough.
2. Use `context.push` within the app, with either a subroute or a top-level route.
3. Resize the screen by any amount.

### Expected results

Resizing the screen should have no effect. If the pushed route has an app bar with implied leading, a back arrow should be present even if the pushed route is a top-level route.

### Actual results

Resizing the window by any amount causes the pushed route to behave as if `context.go` had just been called on that route, including running the transition animation and the absence of the back button in the case of a top-level route.

Removing `MediaQuery.of(context)` from the redirect callback restores expected behavior.

`context.go` works as expected.

### Code sample

The bug is present in this minimal example. Note that the choppy nature of DartPad may obscure the transition animation.

https://dartpad.dev/?id=b7e72c4a07e960a49958172b0096e6b8

### Logs

Although the bug has the appearance and side effects of being as if `context.go` had been called, the logs do not reflect that.

<details><summary>Logs</summary>

```console
[GoRouter] Full paths for routes:
             => /
             =>   /subroute
             => /sibling
[GoRouter] setting initial location /
[GoRouter] Using MaterialApp configuration
[GoRouter] pushing /sibling
** Replicated the bug here, but nothing appeared in the logs **
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.10.0, on macOS 13.3.1 22E772610a darwin-arm64, locale en-TW)
    • Flutter version 3.10.0 on channel stable at /Users/chris/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 84a1e904f4 (7 days ago), 2023-05-09 07:41:44 -0700
    • Engine revision d44b5a94c9
    • Dart version 3.0.0
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/chris/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.78.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.64.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.3.1 22E772610a darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 113.0.5672.92

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by huycozy** [comment] 2023-05-17 05:54
Thanks for the report. I also can reproduce this issue on the latest package version `go_router: ^7.0.1`.

Copying sample code from dartpad to here (also add `debugLogDiagnostics` flag to print out routes):

<details>
<summary>Sample code</summary>

```dart
import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';

void main() => runApp(const MainApp());

class MainApp extends StatelessWidget {
  const MainApp({super.key});

  @override
  Widget build(context) => MaterialApp.router(routerConfig: router);
}

final router = GoRouter(
  debugLogDiagnostics: true,
  redirect: (context, state) {
    MediaQuery.of(context); // <-- The presense of this causes the bug.
    return null;
  },
  initialLocation: '/',
  routes: [
    GoRoute(
      path: '/',
      builder: (context, state) => const Home(),
      routes: [
        GoRoute(
          path: 'subroute',
          builder: (context, state) => const SubRoute(),
        ),
      ],
    ),
    GoRoute(
      path: '/sibling',
      builder: (context, state) => const SiblingRoute(),
    ),
  ],
);

class Home extends StatelessWidget {
  const Home({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Home')),
      body: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          const Text('context.go works as intended.'),
          ElevatedButton(
            onPressed: () => context.go('/subroute'),
            child: const Text('context.go /subroute'),
          ),
          ElevatedButton(
            onPressed: () => context.go('/sibling'),
            child: const Text('context.go /sibling'),
          ),
          const Text('context.push reveals a bug when changing screen size'),
          ElevatedButton(
            onPressed: () => context.push('/subroute'),
            style: ElevatedButton.styleFrom(backgroundColor: Colors.red),
            child: const Text('context.push /subroute'),
          ),
          ElevatedButton(
            onPressed: () => context.push('/sibling'),
            style: ElevatedButton.styleFrom(backgroundColor: Colors.red),
            child: const Text('context.push /sibling'),
          )
        ],
      ),
    );
  }
}

class SiblingRoute extends StatelessWidget {
  const SiblingRoute({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Sibling Route')),
      body: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          ElevatedButton(
            onPressed: context.pop,
            child: const Text('context.pop'),
          ),
          ElevatedButton(
            onPressed: () => context.go('/'),
            child: const Text('context.go /'),
          ),
        ],
      ),
    );
  }
}

class SubRoute extends StatelessWidget {
  const SubRoute({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Sub Route')),
    );
  }
}
```
</details>

<details>
<summary>Demo video</summary>


https://github.com/flutter/flutter/assets/104349824/ae5fa5a8-097d-4a4a-9af5-51713c4da086


</details>


<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.10.0, on macOS 13.0.1 22A400 darwin-x64, locale en-VN)
    • Flutter version 3.10.0 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 84a1e904f4 (35 hours ago), 2023-05-09 07:41:44 -0700
    • Engine revision d44b5a94c9
    • Dart version 3.0.0
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.78.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.62.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 113.0.5672.92

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

```bash
[!] Flutter (Channel master, 3.11.0-6.0.pre.85, on macOS 13.0.1 22A400 darwin-x64, locale en-VN)
    • Flutter version 3.11.0-6.0.pre.85 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2919572fb3 (71 minutes ago), 2023-05-15 19:01:28 -0700
    • Engine revision c4d4b40c65
    • Dart version 3.1.0 (build 3.1.0-113.0.dev)
    • DevTools version 2.23.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.78.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.64.0

[✓] Connected device (3 available)
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D • android-arm64  • Android 11 (API 30)
    • macOS (desktop)  • macos            • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)     • chrome           • web-javascript • Google Chrome 113.0.5672.92

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>

**Comment by chunhtai** [comment] 2023-05-18 20:34
This is a bug is due to the routeinformationprovider sends a refresh on with the pushed route.

**Comment by chunhtai** [comment] 2023-12-06 23:23
This should be fixed above v8.0.0

**Closed by chunhtai** 2023-12-06 23:23 UTC
Labels: package, has reproducible steps, P2, p: go_router, found in release: 3.10, found in release: 3.11, team-go_router, triaged-go_router, multiteam-retriage-candidate
