### ISSUE TITLE
FlutterEngineGroup may affect  RepaintBoundary  toImage()

### ISSUE THREAD

**Issue by afei943174289** [flutter/flutter#89468] opened 2021-09-04 11:16 UTC
I read this issue, but did not find what I need
☂️ [Lightweight Flutter Engines](https://github.com/flutter/flutter/issues/72009) #72009

## Problem description

  * When I use the enginegroup method, the toimage API of RepaintBoundary may not meet expectations. Please see the comparison and experimental code
   * I think it may be related to FlutterEngine Group resource sharing. Although it can be solved by abandoning the surfaceview mode, I think it can be better

**Expected results:** 
<img width="264" alt="cdcd" src="https://user-images.githubusercontent.com/14845208/132092555-eb10d941-a3c4-465e-99ad-cf23a47f8d52.png">

**Actual results:** 
<img width="272" alt="cffffff" src="https://user-images.githubusercontent.com/14845208/132093170-8df192fc-1b4b-408c-9395-617c0c04ac9c.png">

## Development environment
<img width="600" alt="image" src="https://user-images.githubusercontent.com/14845208/132092890-d4a136cd-728a-4305-a987-52b64c1cc245.png">

## code desc

 1. Project code https://github.com/flutter/samples/tree/master/add_to_app/multiple_flutters
    * group Engine with RenderMode.surface will get Actual results
    * group Engine with RenderMode.texture will get Expected results or Actual results
    * new engine with not group will always get Expected results
 2. I just added a Wiget that provides the generateImage method to generate graphics data(Uint8List)
 ```
import 'dart:typed_data';
import 'dart:ui';

import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';

class MyEntryWiget extends StatefulWidget {
  const MyEntryWiget({Key? key}) : super(key: key);

  @override
  _MyEntryWigetState createState() => _MyEntryWigetState();
}

class _MyEntryWigetState extends State<MyEntryWiget> {
  late GlobalKey _globalKey;
  @override
  void initState() {
    super.initState();
    _globalKey = GlobalKey();
  }

  @override
  Widget build(BuildContext context) {
    return RepaintBoundary(
        key: _globalKey,
        child: Column(
          children: [
            Container(
                width: 120,
                height: 120,
                child: Image.network(
                    "https://avatars.githubusercontent.com/u/30870216?v=4")),
            Text(
              "I like flutter",
              style: TextStyle(color: Colors.red),
            )
          ],
        ));
    ;
  }

  /// pass return  data to any platform to show
  Future<Uint8List?> captureImage(GlobalKey rootKey) async {
    try {
      RenderRepaintBoundary boundary =
          rootKey.currentContext!.findRenderObject() as RenderRepaintBoundary;
      var image = await boundary.toImage(pixelRatio: 3.0);
      ByteData? byteData = await image.toByteData(format: ImageByteFormat.png);
      Uint8List? pngBytes = byteData?.buffer.asUint8List();
      return pngBytes;
    } catch (e) {
      print(e);
    }
    return null;
  }
}
```

3.  For example, on Android, byte data can be converted into bitmap display
      ```
        public Bitmap stringToBitmap(byte[] string) {
              Bitmap bitmap = null;
              try {
                  byte[] bitmapArray = Base64.decode(string, Base64.DEFAULT);
                  bitmap = BitmapFactory.decodeByteArray(bitmapArray, 0, bitmapArray.length);
              } catch (Exception e) {
                  e.printStackTrace();
              }
              return bitmap;
      
      findViewById<ImageView>(R.id.iv).setImageBitmap()
  ```

**Comment by TahaTesser** [comment] 2021-09-06 12:05
Hi @afei943174289 
Unable to reproduce the issue on the latest `stable` using official 

<details> 
<summary>minimal code sample</summary> 


### main.dart
```dart
// Copyright 2021 The Flutter team. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'entry_widget.dart';

void main() => runApp(const MyApp(color: Colors.blue));

@pragma('vm:entry-point')
void topMain() => runApp(const MyApp(color: Colors.green));

@pragma('vm:entry-point')
void bottomMain() => runApp(const MyApp(color: Colors.purple));

class MyApp extends StatelessWidget {
  const MyApp({Key? key, required this.color}) : super(key: key);

  final MaterialColor color;

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: color,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int? _counter = 0;
  late MethodChannel _channel;

  @override
  void initState() {
    super.initState();
    _channel = const MethodChannel('multiple-flutters');
    _channel.setMethodCallHandler((call) async {
      if (call.method == "setCount") {
        // A notification that the host platform's data model has been updated.
        setState(() {
          _counter = call.arguments as int?;
        });
      } else {
        throw Exception('not implemented ${call.method}');
      }
    });
  }

  void _incrementCounter() {
    // Mutations to the data model are forwarded to the host platform.
    _channel.invokeMethod<void>("incrementCount", _counter);
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const MyEntryWiget(),
            const Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
            TextButton(
              onPressed: _incrementCounter,
              child: const Text('Add'),
            ),
            TextButton(
              onPressed: () {
                _channel.invokeMethod<void>("next", _counter);
              },
              child: const Text('Next'),
            ),
          ],
        ),
      ),
    );
  }
}
``` 

### entry_widget.dart
```dart
import 'dart:typed_data';
import 'dart:ui';

import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';

class MyEntryWiget extends StatefulWidget {
 const MyEntryWiget({Key? key}) : super(key: key);

 @override
 _MyEntryWigetState createState() => _MyEntryWigetState();
}

class _MyEntryWigetState extends State<MyEntryWiget> {
 late GlobalKey _globalKey;
 @override
 void initState() {
   super.initState();
   _globalKey = GlobalKey();
 }

 @override
 Widget build(BuildContext context) {
   return RepaintBoundary(
       key: _globalKey,
       child: Column(
         children: [
           Container(
               width: 120,
               height: 120,
               child: Image.network(
                   "https://avatars.githubusercontent.com/u/30870216?v=4")),
           Text(
             "I like flutter",
             style: TextStyle(color: Colors.red),
           )
         ],
       ));
   ;
 }

 /// pass return  data to any platform to show
 Future<Uint8List?> captureImage(GlobalKey rootKey) async {
   try {
     RenderRepaintBoundary boundary =
         rootKey.currentContext!.findRenderObject() as RenderRepaintBoundary;
     var image = await boundary.toImage(pixelRatio: 3.0);
     ByteData? byteData = await image.toByteData(format: ImageByteFormat.png);
     Uint8List? pngBytes = byteData?.buffer.asUint8List();
     return pngBytes;
   } catch (e) {
     print(e);
   }
   return null;
 }
}

``` 
	
</details>


Can you please provide your `flutter doctor -v` and provide step by steps to reproduce the issue
Thank you

**Comment by TahaTesser** [comment] 2021-09-29 11:45
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by TahaTesser** 2021-09-29 11:45 UTC
