### ISSUE TITLE
https://dartpad.dev/e7076b40fb17a0fa899f9f7a154a02e8

### ISSUE THREAD

**Issue by saisaske** [flutter/flutter#132192] opened 2023-08-09 06:12 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

In this article https://codelabs.developers.google.com/codelabs/flutter-codelab-first#8

Look at the code of [this advanced version](https://dartpad.dev/e7076b40fb17a0fa899f9f7a154a02e8) of the same app, to see how you can add animated lists, gradients, cross-fades, and more.

The link provided doesnot point to the actual source code. kindly correct it
[](https://codelabs.developers.google.com/static/codelabs/flutter-codelab-first/img/d4afd1f43ab976f7.gif)

### Expected results

Link should point to correct source code

### Actual results

it is opening wrong source-code in dartpad

### Code sample

.    

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

.

### Flutter Doctor output

 .

**Comment by danagbemava-nc** [comment] 2023-08-09 09:07
Closing this as a duplicate of https://github.com/flutter/flutter/issues/131300

**Closed by danagbemava-nc** 2023-08-09 09:07 UTC
Labels: in triage
