### ISSUE TITLE
Support gamepad/joystick devices as distinct input sources?

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#80472] opened 2021-04-14 23:19 UTC
Flutter supports mouse, touch, stylus, and unkonwn device types. In the UWP embedding, there's code specific to gamepads.

For now these are being treated as mice, but might warrant their own type.

/cc @clarkezone @cbracken for thoughts.

**Comment by clarkezone** [comment] 2021-04-15 05:21
Interesting question.  If we want to expose the concept of game input to flutter then there is potentially merit here.. although it isn't a single x,y axis obviously there are multiple vectors from the different sticks etc.

**Comment by dnfield** [comment] 2021-04-15 05:40
The only thing I can think of that would really make a difference is how you want to handle slop around it in the framework. For example, determining whether a gesture is vertical or horizontal can be different for the same set of x/y coordinates depending on what kind of device gave them, since we assume touch will be less precise than mouse.

**Comment by cbracken** [comment] 2021-08-20 23:05
@clarkezone and I did have a brief conversation about behaviour with regards to cursor pointer display etc, and given that even phones support gamepad input these days, I do think we want gamepads as a distinct input type. You could imagine games written in Flutter wanting this.

That said, I'd prefer to avoid landing API for that until we've done a survey of APIs and expected behaviour across all platforms, and have a more concrete idea of the feature-set we'll want to enable, so I'm fine with this being a UWP-specific behaviour to support something like mouse input on the Xbox for the time being

**Comment by cbracken** [comment] 2022-04-14 21:44
Closing this since our intent is to wind down development on, and remove the UWP embedder in order to focus on the Win32 embedder which, over time, will start to adopt Windows SDK support (once our supported OSes is a subset of those that support doing so).

I do think we'll want to treat gamepads as gamepads and mice as mice when we get to the point of supporting these devices in the main Windows embedder; but closing for now as UWP-specific since we haven't yet got to supporting gamepads in the Win32 embedder.

See: https://github.com/flutter/flutter/issues/14967#issuecomment-1085490495

**Closed by cbracken** 2022-04-14 21:44 UTC
Labels: severe: new feature, engine, f: gestures, a: desktop, passed first triage, P5, e: uwp
