### ISSUE TITLE
VSCode Flutter Extension Failing: 404 Not Found

### ISSUE THREAD

**Issue by prujohn** [flutter/flutter#60142] opened 2020-06-23 23:19 UTC
ref: https://github.com/Dart-Code/Dart-Code/issues/2573

Log output from the extension below.  Fails when trying to download ```font-subset.zip```

Flutter extension version: v3.11.0
VSCode 1.46.1

```
[3:28:40 PM] [General] [Info] Activating Flutter extension for Flutter project...
[3:28:40 PM] [General] [Info] Extension:Startup timing: 54ms
[3:28:40 PM] [General] [Info] Found 0 folders requiring "pub get":
[3:28:40 PM] [Analyzer] [Error] Could not fin
[3:28:40 PM] [Analyzer] [Error] d DartDev snapshot and 'c:\src\flutter\bin\cache\dart-sdk\bin\snapshots\analysis_server.dart.snapshot' is not
[3:28:40 PM] [Analyzer] [Error] a valid script.
[3:28:41 PM] [Analyzer] [Info] Process terminated! 255, null
[3:28:48 PM] [FlutterDaemon] [Info] <== Downloading windows-x64/font-subset tools...
[3:28:48 PM] [FlutterDaemon] [Error] Download failed.
URL: https://storage.googleapis.com/flutter_infra/flutter/b6b54fd60631a3828c2e2c9b079b5d1d2d8c8c37/windows-x64/font-subset.zip
Error: 404 Not Found
[3:28:49 PM] [FlutterDaemon] [Info] Process terminated! 50, null
[3:28:58 PM] [Analyzer] [Info] ==> {"id":"4","method":"edit.getFixes","params":{"file":"C:\\Users\\john\\dev\\aces\\aces_consult\\lib\\view_models\\app_view_model.dart","offset":0},"clientRequestTime":1592519338555}
[3:28:58 PM] [Analyzer] [Info] ==> {"id":"5","method":"edit.getAssists","params":{"file":"C:\\Users\\john\\dev\\aces\\aces_consult\\lib\\view_models\\app_view_model.dart","length":0,"offset":0},"clientRequestTime":1592519338567}
[3:28:58 PM] [Analyzer] [Info] ==> {"id":"6","method":"edit.getAvailableRefactorings","params":{"file":"C:\\Users\\john\\dev\\aces\\aces_consult\\lib\\view_models\\app_view_model.dart","length":0,"offset":0},"clientRequestTime":1592519338570}
[3:28:58 PM] [Analyzer] [Info] ==> {"id":"7","method":"analysis.setPriorityFiles","params":{"files":["C:\\Users\\john\\dev\\aces\\aces_consult\\lib\\view_models\\app_view_model.dart"]},"clientRequestTime":1592519338574}
```

**Comment by iapicca** [comment] 2020-06-24 08:08
Hi @prujohn 
Following the indication of [VS Code Flutter Extension](https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter), the correct way to address the problem is to open an issue in the dedicated [repository](https://github.com/Dart-Code/Dart-Code/issues).
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by iapicca** 2020-06-24 08:08 UTC
