### ISSUE TITLE
Font rendering issue on 3.3+

### ISSUE THREAD

**Issue by Zchandev** [flutter/flutter#111257] opened 2022-09-09 12:03 UTC
## Issue

There is a problem with text rendering - sometimes it looks like not aliased. Tried on stable and dev - got the same issue. 

Pics:

![IMG_0789+](https://user-images.githubusercontent.com/69233113/189345353-091d1c8a-de7a-404f-9beb-2fbe1529e2b9.jpg)
![IMG_0801+](https://user-images.githubusercontent.com/69233113/189345360-202c30fd-4465-49b4-9f29-6c4c61b680ae.jpg)

## Logs

<details>
<summary>Logs</summary>

```
[✓] Flutter (Channel dev, 3.3.0-0.5.pre, on macOS 12.3 21E230 darwin-arm, locale en-RU)
    • Flutter version 3.3.0-0.5.pre on channel dev at /Users/me/Applications/fvm/versions/dev
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 096162697a (3 weeks ago), 2022-08-22 15:34:14 -0700
    • Engine revision ad3d868e0d
    • Dart version 2.18.0 (build 2.18.0-271.7.beta)
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/me/Library/Android/sdk
    • Platform android-33, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment Homebrew (build 18.0.2+0)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13E500a
    • CocoaPods version 1.11.3

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment Homebrew (build 18.0.2+0)

[✓] VS Code (version 1.71.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (3 available)
    • Redmi 3 (mobile)        • 3bdff0717d03                         • android-arm64 • Android 10 (API 29)
    • iPhone 13 mini (mobile) • 66E8BECB-AF2F-438E-A1B6-25A50EE7B61E • ios           • com.apple.CoreSimulator.SimRuntime.iOS-15-4 (simulator)
    • macOS (desktop)         • macos                                • darwin-arm64  • macOS 12.3 21E230 darwin-arm

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by darshankawar** [comment] 2022-09-09 12:44
Closing this as a duplicate of https://github.com/flutter/flutter/issues/110738. Please follow-up in it for further updates.

**Closed by darshankawar** 2022-09-09 12:44 UTC
Labels: in triage
