### ISSUE TITLE
Flutter run keeps losing connection to iOS device after few seconds

### ISSUE THREAD

**Issue by rolandbodenstaff** [flutter/flutter#34925] opened 2019-06-22 15:10 UTC
When I create a new app and try to run it on an iOS device after a few seconds of running the debug session is terminated. The app itself continuous to function on the device itself but the debugging session stops. On the same mac Android devices work fine, also tried different iOS devices and cables. The output attachment is the output from " flutter run -v".

 ```
flutter doctor -v
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.5 18F132, locale en-NL)
    • Flutter version 1.5.4-hotfix.2 at /Users/rolandbodenstaff/dev/flutter
    • Framework revision 7a4c33425d (8 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at /Users/rolandbodenstaff/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • ios-deploy 1.9.4
    • CocoaPods version 1.7.2

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 36.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.35.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.1.0

[✓] Connected device (1 available)
    • iPhone van Diederik • 583d6f82effbf9de64782df7710708c2722af89b • ios • iOS 12.2

• No issues found!

```
[output.txt](https://github.com/flutter/flutter/files/3316964/output.txt)

**Comment by rolandbodenstaff** [comment] 2019-06-23 14:44
What I also noticed was that on the emulator the connection is not lost. When I deploy from xCode the debug session is maintained but obviously I can't debug dart code from there. Is there anyway I can get more information as to why the connection is lost?

**Comment by 0dd1** [comment] 2019-06-23 21:18
Same issue here. Changing to the master branch did help at all.

**Comment by rifuso** [comment] 2019-06-23 21:19
I have the same problem.

> Doctor summary (to see all details, run flutter doctor -v):
> [✓] Flutter (Channel beta, v1.6.3, on Mac OS X 10.14.3 18D42, locale en-US)
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
> [✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
> [✓] Android Studio (version 3.1)
> [✓] VS Code (version 1.33.1)
> [✓] Connected device (1 available)
> 
> • No issues found!

**Comment by trungvq** [comment] 2019-06-24 05:53
I have the same issue
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.13.6 17G7024, locale en-VN)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.4)
[✓] VS Code (version 1.35.1)
[✓] Connected device (1 available)

• No issues found!
```
No problem on my Macbook Pro (10.14.5) though

**Comment by DylanXing** [comment] 2019-06-24 09:25
same issue

```
Launching lib/main.dart on XXXX的 iPhoneh in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: A7F5XXXXXX
Xcode build done.                                            7.3s
Lost connection to device.
Exited (sigterm)
```

**Comment by tapizquent** [comment] 2019-06-24 15:24
Same here running on a physical iOS device.
Flutter runs the app but seconds later it loses connection to device.

**Comment by leoboey89** [comment] 2019-06-24 23:46
Exactly same here for iOS physical device. It is running well on emulator.

**Comment by tyl0r** [comment] 2019-06-25 00:32
I can confirm the same issue on physical iOS device with multiple projects (new and existing).

**Comment by BadReese** [comment] 2019-06-25 03:16
Exactly same here for iOS physical device. It is running well on emulator.

**Comment by timtraversy** [comment] 2019-06-25 21:30
Can everyone thumbs up this issue if you experience it? That's how issues are prioritized.

**Comment by tyl0r** [comment] 2019-06-25 23:25
> Can everyone thumbs up this issue if you experience it? That's how issues are prioritized.
> I think I saw that this issue is caused by #32143, and is fixed in the dev channel.

Thanks, I didn't see that open issue. I upgraded to the dev channel. I'm on version 1.7.9. I tried `flutter clean && flutter run` and I'm still experiencing the 'Lost connection to device' error. I haven't tested whether or not #32143 is fixed by updated to the dev channel

**Comment by timtraversy** [comment] 2019-06-26 00:41
Hm! The status of that fix is unclear to me, I haven’t been a able to test yet

**Comment by xhw0525** [comment] 2019-06-26 05:29
I have this problem, too.
This is my print.
```
[   +1 ms] Connected to _flutterView/0x101a0aca8.
[   +2 ms] 🔥  To hot reload changes while running, press "r". To hot restart (and rebuild
state),
           press "R".
[   +1 ms] An Observatory debugger and profiler on iPhone-v is available at:
http://127.0.0.1:1025/
[        ] For a more detailed help message, press "h". To detach, press "d"; to quit,
press "q".
[+4998 ms] Service protocol connection closed.
[        ] Lost connection to device.
[   +1 ms] DevFS: Deleting filesystem on the device
(file:///private/var/mobile/Containers/Data/Application/38B1EF94-492E-4CF2-BE45-55B7C24526
E0/tmp/hahat3Rulm/haha/)
[        ] Sending to VM service: _deleteDevFS({fsName: haha})
[ +260 ms] Ignored error while cleaning up DevFS: TimeoutException after 0:00:00.250000:
Future not completed
[   +6 ms] Unforwarding port ForwardedPort HOST:1025 to DEVICE:56605
[   +3 ms] "flutter attach" took 12,239ms.
[        ] "flutter attach" took 12,239ms.
```

**Comment by BadReese** [comment] 2019-06-26 06:22
dev,beta,statble channel, got same result.

[✓] Flutter (Channel beta, v1.6.3, on Mac OS X 10.14.5 18F132, locale zh-Hans-CN)
    • Flutter version 1.6.3 at /Users/johnreese/Development/Flutter/SDK/flutter
    • Framework revision bc7bc94083 (5 weeks ago), 2019-05-23 10:29:07 -0700
    • Engine revision 8dc3a4cde2
    • Dart version 2.3.2 (build 2.3.2-dev.0.0 e3edfd36b2)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/johnreese/Development/Android/SDK
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/johnreese/Development/Android/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.0.beta.2

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 36.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] IntelliJ IDEA Community Edition (version 2019.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 36.1.4
    • Dart plugin version 191.7830

[✓] VS Code (version 1.35.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.1.0

[✓] Connected device (1 available)
    • JohnReese • 8f053f349a5e91b40a17f9de76c63f01a1447177 • ios • iOS 12.1.4

I use demo code generated by sdk, and this is my Android Studio print:

Launching lib/main.dart on JohnReese in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: G893SD54PX
Running Xcode build...
Xcode build done.                                           16.6s
Installing and launching...
Syncing files to device JohnReese...
Lost connection to device.

**Comment by amake** [comment] 2019-06-26 06:30
If you set up your Flutter environment recently (after June 13) you might be suffering from #35102.

**Comment by rolandbodenstaff** [comment] 2019-06-26 07:40
@amake this indeed seems to be the problem. I will try to provide downgrade steps but I am still new to brew. Maybe someone with more experience can help?

**Comment by xhw0525** [comment] 2019-06-26 08:33
hahaha, It's all right. If you use it recently "brew install usbmuxd"
Replace files in the "/usr/local/Cellar/usbmuxd" directory with others,and It's OK

**Comment by BadReese** [comment] 2019-06-26 08:37
> hahaha, It's all right. If you use it recently "brew install usbmuxd"
> Replace files in the "/usr/local/Cellar/usbmuxd" directory with others,and It's OK

@xhw0525 Execute me, replace files with what?
Is it the solution to fix losing connection ?

**Comment by trungvq** [comment] 2019-06-26 08:55
I can confirm that changing the version of usbmuxd works for me. I replaced files in "/usr/local/Cellar/usbmuxd" with files from same directory on my macbook (version HEAD-9efb174) and the issue has gone away

**Comment by xhw0525** [comment] 2019-06-26 09:14
> > hahaha, It's all right. If you use it recently "brew install usbmuxd"
> > Replace files in the "/usr/local/Cellar/usbmuxd" directory with others,and It's OK
> 
> @xhw0525 Excuse me, replace files with what?
> Is it the solution of losing connection ?

yes

**Comment by BadReese** [comment] 2019-06-26 09:18
@xhw0525 thank you, I'll try and give a feedback

**Comment by rolandbodenstaff** [comment] 2019-06-26 10:48
Can also confirm this fixes the issue. Keeping the issue open until the actual problem is fixed

**Comment by christopherfujino** [comment] 2019-06-26 16:08
Closed as a duplicate of #35102.

**Comment by tyl0r** [comment] 2019-06-26 16:09
I recently did a fresh install of MacOS Mojave and I don't have my backup in front of me. Here's what I did to get hot reload working. There's probably a simpler way:

```
git clone https://github.com/libimobiledevice/libusbmuxd.git
cd libusbmuxd/
git checkout 9efb1745bf0eb68064a670b297d4ec7fc98caa02
./autogen.sh
mkdir compiled
./configure --prefix=$PWD/compiled/
make
make install
mv /usr/local/Cellar/usbmuxd/HEAD-affc9af_1/bin{,.bak}
mv /usr/local/Cellar/usbmuxd/HEAD-affc9af_1/include{,.bak}
mv /usr/local/Cellar/usbmuxd/HEAD-affc9af_1/lib{,.bak}
cp -a compiled/* /usr/local/Cellar/usbmuxd/HEAD-affc9af_1/
```

**Closed by christopherfujino** 2019-06-26 16:08 UTC
Labels: tool

**Comment by BadReese** [comment] 2019-06-27 01:58
> I recently did a fresh install of MacOS Mojave and I don't have my backup in front of me. Here's what I did to get hot reload working. There's probably a simpler way:
> 
> ```
> git clone https://github.com/libimobiledevice/libusbmuxd.git
> cd libusbmuxd/
> git checkout 9efb1745bf0eb68064a670b297d4ec7fc98caa02
> ./autogen.sh
> mkdir compiled
> ./configure --prefix=$PWD/compiled/
> make
> make install
> mv /usr/local/Cellar/usbmuxd/HEAD-affc9af_1/bin{,.bak}
> mv /usr/local/Cellar/usbmuxd/HEAD-affc9af_1/include{,.bak}
> mv /usr/local/Cellar/usbmuxd/HEAD-affc9af_1/lib{,.bak}
> cp -a compiled/* /usr/local/Cellar/usbmuxd/HEAD-affc9af_1/
> ```

It works, thank you.

**Comment by spiderion** [comment] 2019-10-30 18:48
Facing same issue after initializing the GoogleMaps Widget
when I run the app with Xcode i got this exception
CoreUI: RunTimeThemeRefForBundleIdentifierAndName() couldn't find Assets.car in bundle with identifier: 'com.google.GoogleMaps'

**Comment by christopherfujino** [comment] 2019-10-31 16:35
@QOFOL if it's happening on windows then you are certainly experiencing a new issues, as this issue was caused by a regression in a macOS only library (libimobiledevice). Would you mind filing a new issue with full logs and `flutter doctor --verbose` output and tagging me on it? Thanks!

@spiderion it sounds like you have yet another issue. Could you also file a new issue with full logs and `flutter doctor --verbose` output? Thanks!

**Comment by Allan-Nava** [comment] 2020-05-27 11:50
Get the same error!

**Comment by bernardpumped** [comment] 2020-05-30 09:31
Same here on windows Android against Pixel 2, after pulling latest from stable channel flutter 1.17.2 dart 2.8.3

**Comment by kharitonovAL** [comment] 2021-02-22 14:02
@xhw0525 

> hahaha, It's all right. If you use it recently "brew install usbmuxd"
> Replace files in the "/usr/local/Cellar/usbmuxd" directory with others,and It's OK


Could you please write more detailed what files replace, and what are “others” means?

thank you!
