### ISSUE TITLE
iOS linking fails for a previously working app

### ISSUE THREAD

**Issue by xl-hacker** [flutter/flutter#62832] opened 2020-08-04 01:15 UTC
flutter run fails for iOS simulator and device, with an app that was previously running (for months).

Build was working fine until a 3-4 days ago. I updated XCode recently but was successfully able to run the app on iOS sim and device after that update too. Don't believe anything was changed but it suddenly stopped working.

Error log: 
****************************************************************

Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **

Xcode's output:
↳
    Undefined symbols for architecture x86_64:
      "_OBJC_CLASS_$_FlutterMethodChannel", referenced from:
          objc-class-ref in FLTURLLauncherPlugin.o
      "_OBJC_CLASS_$_FlutterError", referenced from:
          objc-class-ref in FLTURLLauncherPlugin.o
      "_FlutterMethodNotImplemented", referenced from:
          -[FLTURLLauncherPlugin handleMethodCall:result:] in FLTURLLauncherPlugin.o
    ld: symbol(s) not found for architecture x86_64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description
    warning: Mapping architecture armv7 to i386. Ensure that this target's Architectures and Valid Architectures build settings are configured correctly
    for the iOS Simulator platform. (in target 'in_app_purchase' from project 'Pods')
    warning: Mapping architecture arm64 to x86_64. Ensure that this target's Architectures and Valid Architectures build settings are configured
    correctly for the iOS Simulator platform. (in target 'in_app_purchase' from project 'Pods')
    warning: Mapping architecture armv7 to i386. Ensure that this target's Architectures and Valid Architectures build settings are configured correctly
    for the iOS Simulator platform. (in target 'image_picker' from project 'Pods')
    warning: Mapping architecture arm64 to x86_64. Ensure that this target's Architectures and Valid Architectures build settings are configured
    correctly for the iOS Simulator platform. (in target 'image_picker' from project 'Pods')

****************************************************************
Doctor output:

flutter doctor -v

[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.6 19G73, locale en-US)
    • Flutter version 1.17.5 at <location>
    • Framework revision 8af6b2f038 (5 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at <location>
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = <location>
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.47.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.1

[✓] Connected device (1 available)
    • iPhone SE (2nd generation) • 5A4B0C02-87C8-4DFC-806D-A3AACB93242F • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-6 (simulator)

• No issues found!

Things I tried:
- flutter create .
- switching to master channel, building there (fails with same error), switching back to stable
- flutter clean
- deleting flutter/bin/cache
- changing target architectures in XCode

Nothing made any difference. I'm lost for what the problem might be since I didn't change anything after it last worked.

**Comment by TahaTesser** [comment] 2020-08-04 10:56
Hi @xl-hacker 
Can you try  please latest ` image_picker: ^0.6.7+4` 
Related  [#51395](https://github.com/flutter/flutter/issues/51395)

I see there's an open issue addressing the case you described. https://github.com/flutter/flutter/issues/62634
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by xl-hacker** [comment] 2020-08-04 15:57
Thanks. Unfortunately that didn't work. I still get the same error messages quoted above.

**Comment by xl-hacker** [comment] 2020-08-04 21:38
I'm still blocked on this. Deleting derived data from xcode and reinstalling xcode didn't help either.

**Comment by xl-hacker** [comment] 2020-08-05 17:21
@TahaTesser can you please reopen this? It isn't resolved.

**Comment by TahaTesser** [comment] 2020-08-06 15:15
@xl-hacker
Please follow up on https://github.com/flutter/flutter/issues/62634

**Comment by TahaTesser** [comment] 2020-08-06 15:16
Hi @xl-hacker 
Can you please provide your `flutter doctor -v`  with latest `stable` your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by xl-hacker** [comment] 2020-08-07 16:26
***************************************************************************
flutter doctor -v
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.6 19G73, locale en-US)
    • Flutter version 1.17.5 at /Users/<location>/development/flutter
    • Framework revision 8af6b2f038 (5 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/<location>/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/<location>/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.47.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[✓] Connected device (2 available)
    • Android SDK built for x86  • emulator-5554                        • android-x86 • Android 8.0.0 (API 26) (emulator)
    • iPhone SE (2nd generation) • 5A4B0C02-87C8-4DFC-806D-A3AACB93242F • ios         •
      com.apple.CoreSimulator.SimRuntime.iOS-13-6 (simulator)

• No issues found!

***************************************************************************

Attached file with run -v output. 

[log.txt](https://github.com/flutter/flutter/files/5042557/log.txt)

***************************************************************************

Minimal code sample is difficult since it needs all my plugins, and I'm using firebase so need to create separate projects, etc. I couldn't get compilation / linker failure by creating a demo project and all my plugins.

**Comment by xl-hacker** [comment] 2020-08-07 18:41
Two things finally resolved this for me:

- manually updated url_launcher plugin dependency to latest version
- switched to flutter master channel

(either of them by themselves didn't work)

**Comment by TahaTesser** [comment] 2020-08-10 07:06
Hi @xl-hacker 
Since the issue isn't reproducible on `master` and also dependent on third party plugin
given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you

**Closed by TahaTesser** 2020-08-10 07:06 UTC
Labels: in triage
