### ISSUE TITLE
Linux docs_test is failing, closing the tree

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#147609] opened 2024-04-30 22:43 UTC
As in https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20docs_test/16443/infra

Errors of the form
```
dartdoc:stderr: Could not make "/b/s/w/ir/x/w/.pub-cache/bin/snippets" executable (exit code 1):
dartdoc:stderr: chmod: cannot access '/b/s/w/ir/x/w/.pub-cache/bin/snippets': No such file or directory
```

cc @gspencergoog

**Comment by gspencergoog** [comment] 2024-04-30 22:52
I am able to reproduce this locally.

Sample errors are:

```
dartdoc:stderr:   error: tool execution failed: Tool "snippet" returned non-zero exit code (1) when run as "/usr/local/google/home/gspencer/code/flutter/bin/cache/dart-sdk/bin/dart pub global run snippets --output-directory=doc/snippets --type=snippet" from /tmp/dartdoc.E0hsd
dartdoc:stderr: Input to snippet was:
dartdoc:stderr:
dartdoc:stderr: Here are some examples of how to create [EdgeInsets] instances:
dartdoc:stderr:
dartdoc:stderr: Typical eight-pixel margin on all sides:
dartdoc:stderr:
dartdoc:stderr: ```dart
dartdoc:stderr: const EdgeInsets.all(8.0)
dartdoc:stderr: ```
dartdoc:stderr: Stderr output was:
dartdoc:stderr: Could not make "/usr/local/google/home/gspencer/.pub-cache/bin/snippets" executable (exit code 1):
dartdoc:stderr: chmod: cannot access '/usr/local/google/home/gspencer/.pub-cache/bin/snippets': No such file or directory
```

This seems to imply that dartdoc or dart pub run is trying to chmod the executable for snippets, but can't find it.  However the file referenced does exist, and is already executable, and if I run it outside of dartdoc, it executes normally.

Still scratching my head....

**Comment by gspencergoog** [comment] 2024-05-01 01:02
I've tried to bisect this, and even old revisions (from a few days ago, when it used to work) still fail on my Linux machine.

I've tried reverting to previous version of snippets and the previous version of dartdoc, neither of which fix the problem.

I've also nuked my .pub-cache to make sure it was clean.

**Comment by gspencergoog** [comment] 2024-05-01 01:05
Okay, it appears that this is a manifestation of https://github.com/flutter/flutter/issues/144408 which purports to be fixed, in this pr https://github.com/dart-lang/pub/pull/3285/files#diff-609b203653065d15282bde9c47cbf5c38885fa92957ce5b89adbf9be5db0b1c8R793 according to the comment in https://github.com/flutter/flutter/issues/144408#issuecomment-2051287746  

@sigurdm Is this something you submitted a fix for?  This is now a P0 for us, since it's no longer just affecting local hosts, but also affects the build.  Did your fix get reverted?

**Comment by jason-simmons** [comment] 2024-05-01 02:10
I was able to get this to work on my local setup by reverting https://dart.googlesource.com/pub/+/ed20b45589766d6fd135e93460b9e8255ccba519

The Flutter Dartdoc script is running a group of `dart pub global run snippets` commands concurrently.  I can reproduce the `Cannot open file, path = '.../.pub-cache/bin/snippets'` error by running 20 instances of a `dart pub global run snippets` command concurrently in a shell script.

**Comment by stuartmorgan** [comment] 2024-05-07 13:46
@gspencergoog Should the test be brought back out of bringup now? It looks like it's been green since you landed your PR.

**Comment by gspencergoog** [comment] 2024-05-07 15:39
Yes, I was just waiting to see if it would be green.

**Closed** 2024-05-07 17:26 UTC
Labels: P0
