### ISSUE TITLE
Offset of painted child out of sync when using impeller ios [debug, release]

### ISSUE THREAD

**Issue by hasanmhallak** [flutter/flutter#136805] opened 2023-10-18 12:12 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

run the sampled code below and scroll down and up. then turn off Impeller and try again.

### Expected results

Expected result on Android / ios (without impeller
<details><summary>Expected results</summary>

![Simulator Screenshot - iPhone 14 - 2023-10-18 at 15 08 23](https://github.com/flutter/flutter/assets/95232508/75c5b9a6-a62e-48a4-9a2f-d8ac34c4282f)

</details>

### Actual results

<details><summary>Actual results</summary>

![Simulator Screenshot - iPhone 14 - 2023-10-18 at 15 06 47](https://github.com/flutter/flutter/assets/95232508/1635a8b1-c5ad-41df-bd15-1a9a42c486d9)

</details>

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

const kBackgroundDark = Color(0xff1E1F24);
const kLightDark = Color(0xff3A3A3A);
const kShadowDark = Color(0xff000000);

void main() {
  runApp(
    MaterialApp(
      home: Scaffold(
        backgroundColor: kBackgroundDark,
        body: Center(
          child: SingleChildScrollView(
            child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              children: <Widget>[
                const SizedBox(height: 600),
                Container(
                  width: 300,
                  height: 300,
                  decoration: NeumorphicClickedDecoration(
                      baseColor: kBackgroundDark,
                      borderRadius: BorderRadius.circular(24)),
                ),
                const SizedBox(height: 1200),
              ],
            ),
          ),
        ),
      ),
    ),
  );
}

class NeumorphicClickedDecoration extends Decoration {
  const NeumorphicClickedDecoration({
    required this.baseColor,
    this.borderRadius = BorderRadius.zero,
  });

  final BorderRadiusGeometry? borderRadius;
  final Color baseColor;

  @override
  BoxPainter createBoxPainter([VoidCallback? onChanged]) {
    final painter = _NeumorphicClickedBoxPainter();
    return painter
      ..baseColor = baseColor
      ..borderRadius = borderRadius ?? BorderRadius.zero;
  }

  @override
  bool get isComplex => true;

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) {
      return true;
    }
    if (other.runtimeType != runtimeType) {
      return false;
    }
    return other is NeumorphicClickedDecoration &&
        other.baseColor == baseColor &&
        other.borderRadius == borderRadius;
  }

  @override
  int get hashCode => Object.hash(
        baseColor,
        borderRadius,
      );

  @override
  Path getClipPath(Rect rect, TextDirection textDirection) {
    if (borderRadius != null) {
      return Path()
        ..addRRect(borderRadius!.resolve(textDirection).toRRect(rect));
    }
    return Path()..addRect(rect);
  }
}

class _NeumorphicClickedBoxPainter extends BoxPainter {
  late BorderRadiusGeometry borderRadius;
  late TextDirection textDirection;
  late Color baseColor;

  @override
  void paint(Canvas canvas, Offset offset, ImageConfiguration configuration) {
    assert(configuration.size != null, 'configuration size must not be null');

    final Rect rect = offset & configuration.size!;
    final TextDirection? textDirection = configuration.textDirection;
    const shadowsOffset = Offset(5, 5);
    const double blur = 5;

    const shadow = BoxShadow(
      color: Color(0xff000000),
      blurRadius: blur,
    );

    const light = BoxShadow(
      color: Color(0xff3a3a3a),
      offset: shadowsOffset,
      blurRadius: blur,
    );

    canvas.save();

    final roundedRect = borderRadius.resolve(textDirection).toRRect(rect);
    // clip to remove the edges of the blur effect
    canvas.clipRRect(roundedRect);

    final shadowPath = Path()..addRRect(roundedRect);

    canvas.drawPath(shadowPath, shadow.toPaint());

    final lightPath = Path()
      ..addRRect(
        roundedRect.shift(Offset(shadowsOffset.dx, shadowsOffset.dy)),
      );

    canvas.drawPath(
      Path.combine(
        PathOperation.intersect,
        lightPath,
        shadowPath,
      ),
      light.toPaint(),
    );

    final backgroundRect = Rect.fromLTWH(
      roundedRect.shift(Offset(-shadowsOffset.dx, -shadowsOffset.dy)).left,
      roundedRect.shift(Offset(-shadowsOffset.dx, -shadowsOffset.dy)).top,
      roundedRect.width,
      roundedRect.height,
    );

    if (borderRadius == BorderRadius.zero) {
      canvas.drawRect(
        backgroundRect,
        Paint()
          ..maskFilter = const MaskFilter.blur(BlurStyle.normal, blur)
          ..color = baseColor,
      );
    } else {
      final newBorderRadius = borderRadius.resolve(textDirection);
      final s = BorderRadius.only(
        topLeft: newBorderRadius.topLeft,
        bottomRight: newBorderRadius.bottomRight,
      );

      canvas.drawPath(
        Path.combine(
          PathOperation.intersect,
          lightPath,
          Path()..addRRect(s.resolve(textDirection).toRRect(backgroundRect)),
        ),
        Paint()
          ..maskFilter = const MaskFilter.blur(BlurStyle.normal, blur)
          ..color = baseColor,
      );
    }

    canvas.restore();
  }
}

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[[Upload media here]](https://github.com/flutter/flutter/assets/95232508/8cc53fa2-7ced-4923-aee2-698297bcd757)

</details>

### Logs

N/A

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.6, on macOS 13.5.2 22G91 darwin-arm64, locale
    en-EG)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[!] Android Studio (version unknown)
    ✗ Unable to determine Android Studio version.
    ✗ Unable to find bundled Java version.
[✓] VS Code (version 1.82.3)
[✓] Connected device (2 available)
[✓] Network resources

! Doctor found issues in 1 category.
```

</details>

**Comment by dam-ease** [comment] 2023-10-18 13:02
Hi @hasanmhallak. Thanks for filing this. I can reproduce this on the latest `stable` channel but this seems to have been fixed on the latest `master` channel as I am currently unable to reproduce this.

https://github.com/flutter/flutter/assets/53122008/3080e855-d8ea-4a24-bc9e-384f61498cbc

Closing this as fixed in the latest versions, if you disagree, please comment and I'll reopen this.
Thank you.

<details><summary>stable, master flutter doctor -v</summary>
<p>

```
[✓] Flutter (Channel stable, 3.13.7, on macOS 13.0 22A380 darwin-arm64, locale
    en-NG)
    • Flutter version 3.13.7 on channel stable at
      /Users/damilolaalimi/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2f708eb839 (9 days ago), 2023-10-09 09:58:08 -0500
    • Engine revision a794cf2681
    • Dart version 3.1.3
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/damilolaalimi/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/damilolaalimi/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)

[!] Android Studio (version unknown)
    • Android Studio at /Users/damilolaalimi/Downloads/Android Studio
      Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to determine Android Studio version.
    • Java version OpenJDK Runtime Environment (build
      17.0.7+0-17.0.7b1000.6-10550314)

[✓] VS Code (version 1.82.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] VS Code (version 1.83.1)
    • VS Code at /Users/damilolaalimi/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (4 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554                        •
      android-arm64  • Android 14 (API 34) (emulator)
    • iPhone XS (mobile)          • 3CFD1268-0D52-486E-A12E-6E136E972D94 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)             • macos                                •
      darwin-arm64   • macOS 13.0 22A380 darwin-arm64
    • Chrome (web)                • chrome                               •
      web-javascript • Google Chrome 118.0.5993.70

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
``` 
```
[✓] Flutter (Channel master, 3.16.0-12.0.pre.119, on macOS 13.0 22A380 darwin-arm64, locale en-NG)
    • Flutter version 3.16.0-12.0.pre.119 on channel master at /Users/damilolaalimi/fvm/versions/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 552360e3de (4 hours ago), 2023-10-18 03:03:20 -0400
    • Engine revision 0c1c29271e
    • Dart version 3.3.0 (build 3.3.0-35.0.dev)
    • DevTools version 2.28.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/damilolaalimi/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/damilolaalimi/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[!] Android Studio (version unknown)
    • Android Studio at /Users/damilolaalimi/Downloads/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to determine Android Studio version.
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] VS Code (version 1.82.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] VS Code (version 1.83.1)
    • VS Code at /Users/damilolaalimi/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (4 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554                        • android-arm64  • Android 14 (API 34) (emulator)
    • iPhone XS (mobile)          • 3CFD1268-0D52-486E-A12E-6E136E972D94 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)             • macos                                • darwin-arm64   • macOS 13.0 22A380 darwin-arm64
    • Chrome (web)                • chrome                               • web-javascript • Google Chrome 118.0.5993.70

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
``` 

</p>
</details>

**Closed by dam-ease** 2023-10-18 13:02 UTC
Labels: in triage
