### ISSUE TITLE
MissingPluginException(No implementation found for method share on channel plugins.flutter.io/share)

### ISSUE THREAD

**Issue by BearLesnick** [flutter/flutter#23863] opened 2018-11-02 10:01 UTC
I called method in my code like this ( Share.share("some text to share"); ) and received an exception :
```
E/flutter ( 3361): [ERROR:flutter/shell/common/shell.cc(181)] Dart Error: Unhandled exception:
E/flutter ( 3361): MissingPluginException(No implementation found for method share on channel plugins.flutter.io/share)
E/flutter ( 3361): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:278:7)
E/flutter ( 3361): <asynchronous suspension>
E/flutter ( 3361): #1      Share.share (package:share/share.dart:44:20)
E/flutter ( 3361): #2      SignalCard.build.<anonymous closure> (package:airzup/ui/widget/signal_card.dart:103:45)
E/flutter ( 3361): #3      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:507:14)
E/flutter ( 3361): #4      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:562:30)
E/flutter ( 3361): #5      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
E/flutter ( 3361): #6      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:242:9)
E/flutter ( 3361): #7      TapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:204:7)
E/flutter ( 3361): #8      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
E/flutter ( 3361): #9      _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:147:20)
E/flutter ( 3361): #10     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:121:22)
E/flutter ( 3361): #11     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:101:7)
E/flutter ( 3361): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:64:7)
E/flutter ( 3361): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:48:7)
E/flutter ( 3361): #14     _invoke1 (dart:ui/hooks.dart:153:13)
E/flutter ( 3361): #15     _dispatchPointerDataPacket (dart:ui/hooks.dart:107:5)
```
```
Flutter doctor output: 
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v0.9.4, on Microsoft Windows [Version 10.0.17134.345], locale ru-RU)
[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[√] Android Studio (version 3.1)
[!] IntelliJ IDEA Community Edition (version 2018.2)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] IntelliJ IDEA Ultimate Edition (version 2018.1)
[√] Connected devices (1 available)

! Doctor found issues in 1 category.
```

**Comment by flowhorn** [comment] 2018-11-03 13:12
When you add a plugin to your app which contains native code you have to restart the app in order to be loaded. So hot restart etc. is not enough.

Could this be the issue?

**Comment by zoechi** [comment] 2018-12-14 14:06
Duplicate of #20363

**Closed by zoechi** 2018-12-14 14:06 UTC
Labels: p: first party, plugin, severe: crash
