### ISSUE TITLE
[flutter_camera] iOS: Recorded Video is of .mov format but name ends with .mp4

### ISSUE THREAD

**Issue by JonasJW** [flutter/flutter#86881] opened 2021-07-22 16:53 UTC
## Steps to Reproduce

<details><summary>Below is the full code I use to record and upload a video to firebase firestore </summary>

```
    import 'dart:io';
    import 'package:firebase_storage/firebase_storage.dart';
    import 'package:flutter/material.dart';
    import 'package:camera/camera.dart';
    import 'package:video_player/video_player.dart';
    import 'package:flutter/services.dart' show rootBundle;
    import 'package:path_provider/path_provider.dart';

    class CameraTestPage extends StatefulWidget {
      const CameraTestPage({Key? key}) : super(key: key);

      @override
      _CameraTestPageState createState() => _CameraTestPageState();
    }

    class _CameraTestPageState extends State<CameraTestPage> {
      List<CameraDescription>? cameras;

      CameraController? controller;
      bool frontCamera = false;
      XFile? videoFile;

      VideoPlayerController? videoController;
      VoidCallback? videoPlayerListener;

      @override
      void initState() {
        initCamera();
        super.initState();
      }

      initCamera() async {

        if (cameras == null) {
          cameras = await availableCameras();
        }

        if (controller?.value.isInitialized ?? false) {
          controller!.dispose();
        }
        controller = CameraController(
          cameras!.firstWhere(
            (element) => element.lensDirection == (frontCamera ? CameraLensDirection.front : CameraLensDirection.back),
          ),
          ResolutionPreset.medium,
          enableAudio: false,
        );
        controller!.initialize().then((value) {
          setState(() {});
        });
      }

      void onVideoRecordButtonPressed() {
        startVideoRecording().then((_) {
          if (mounted) setState(() {});
        });
      }

      void onStopButtonPressed() {
        stopVideoRecording().then((file) {
          if (mounted) setState(() {});
          if (file != null) {
            print('Video recorded to ${file.path}');
            videoFile = file;
            _startVideoPlayer();
          }
        });
      }

      Future<void> _startVideoPlayer() async {
        if (videoFile == null) {
          return;
        }

        final VideoPlayerController vController = VideoPlayerController.file(File(videoFile!.path));
        videoPlayerListener = () {
          if (videoController != null && videoController!.value.size != null) {
            // Refreshing the state to update video player with the correct ratio.
            if (mounted) setState(() {});
            videoController!.removeListener(videoPlayerListener!);
          }
        };
        vController.addListener(videoPlayerListener!);
        await vController.setLooping(true);
        await vController.initialize();
        await videoController?.dispose();
        if (mounted) {
          setState(() {
            videoController = vController;
          });
        }
        await vController.play();
      }

      Future<void> startVideoRecording() async {
        final CameraController? cameraController = controller;

        if (cameraController == null || !cameraController.value.isInitialized) {
          print('Error: select a camera first.');
          return;
        }

        if (cameraController.value.isRecordingVideo) {
          // A recording is already started, do nothing.
          return;
        }

        try {
          await cameraController.startVideoRecording();
        } on CameraException catch (e) {
          _showCameraException(e);
          return;
        }
      }

      Future<XFile?> stopVideoRecording() async {
        final CameraController? cameraController = controller;

        if (cameraController == null || !cameraController.value.isRecordingVideo) {
          return null;
        }

        try {
          return cameraController.stopVideoRecording();
        } on CameraException catch (e) {
          _showCameraException(e);
          return null;
        }
      }

      void _showCameraException(CameraException e) {
        print('Error: ${e.code}\n${e.description}');
      }

      _uploadVideo() async {
        Reference ref = FirebaseStorage.instance.ref("test/test.mp4");
        UploadTask uploadTask = ref.putFile(File(videoFile!.path), SettableMetadata(contentType: 'video/mp4'));
        print("uploading");
        uploadTask.whenComplete(() async {
          String downloadUrl = await ref.getDownloadURL();
          print("download url: $downloadUrl");
        });
      }

      Widget _thumbnailWidget() {
        final VideoPlayerController? localVideoController = videoController;

        return Expanded(
          child: Row(
            mainAxisSize: MainAxisSize.min,
            children: <Widget>[
              SizedBox(
                child: (localVideoController == null)
                    ? Center(
                        child: Container(
                          child: Text("none"),
                        ),
                      )
                    : Container(
                        child: AspectRatio(
                          aspectRatio: localVideoController.value.aspectRatio,
                          child: VideoPlayer(localVideoController),
                        ),
                        decoration: BoxDecoration(
                          border: Border.all(color: Colors.pink),
                        ),
                      ),
              ),
            ],
          ),
        );
      }

      @override
      Widget build(BuildContext context) {
        return Scaffold(
          appBar: AppBar(title: Text("Camera Test")),
          body: Column(
            children: [
              if (controller != null)
                Container(
                  child: CameraPreview(controller!),
                  height: 400,
                ),
              Row(
                children: [
                  ElevatedButton(
                    onPressed: () {
                      frontCamera = !frontCamera;
                      initCamera();
                    },
                    child: Text("Switch"),
                  ),
                  ElevatedButton(
                    onPressed: () {
                      controller?.value.isRecordingVideo ?? false ? onStopButtonPressed() : onVideoRecordButtonPressed();
                    },
                    child: Text(controller?.value.isRecordingVideo ?? false ? "Stop" : "Record"),
                  ),
                  ElevatedButton(
                    onPressed: videoFile != null ? _uploadVideo : null,
                    child: Text("Upload video"),
                  ),
                ],
              ),
              _thumbnailWidget(),
            ],
          ),
        );
      }
    }
```

</details>

**Expected results:** 
Video is recorded in `.mp4` format as name of recorded video suggests

**Actual results:** 

The recorded video does not seem to be a mp4 compatible format. When I upload the video to firebase firestore (see code above) and open the video in the browser, I can't play it. I found out when I rename the video to `.mov` and change the mime type (see code), the uploaded can be played with the QuickTime Player, which suggests to me, it is actually a .mov format and not browser compatible.

I don't know much about (video) formats and encodings but this seems to be a bug to me.

It would be great if the recorded video is an actual mp4 video that is compatible with browsers.

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by TahaTesser** [comment] 2021-07-23 08:47
Hi @JonasJW 
I can see same video ouput on both iOS and Android, video doesn't open because of this https://github.com/flutter/flutter/issues/83074

This is not a bug but a change, closing as duplicate of https://github.com/flutter/flutter/issues/83074
Thank you

**Closed by TahaTesser** 2021-07-23 08:47 UTC
Labels: in triage
