### ISSUE TITLE
Flutter Web - Images and CORS

### ISSUE THREAD

**Issue by Elemenopeee** [flutter/flutter#79701] opened 2021-04-03 10:22 UTC
I have been researching on the CORS issue for about 2 months now. People have been quick to say that CORS is not a flutter issue and rather a server/backend issue. This is partially true. Although, I have experimented and observed that this is also a flutter issue. 
I have 2 machines running two different versions of flutter. One is running `Flutter 2.1.0-12.2.pre • channel beta` and another is running `Flutter 1.23.0-18.1.pre • channel beta`. Whenever I compile any web-app on the latter machine, I dont face any CORS issues for loading images via Firebase or a personal server. But if I compile my web-app on the first machine which is using the latest beta of flutter, I run into trouble while loading images stored in firebase or a personal server.

## Steps to Reproduce

1. Compile same web-app in 2 different machines using 2 different versions of flutter. 1 machine should be using latest flutter version (channel not important) and another should be  using a flutter version which is older, preferably October/ November 2020 versions.
2. Add any image widget which loads image from network, like `Image.network()` or `CachedNetworkImage()` and if possible try to get image through firebase or by an http call.
3. Build and run in both machines.

**Expected results:** Image loads in both projects compiled using 2 different versions of flutter

**Actual results:** Image loads in project compiled in older flutter version and doesn't load in the project compiled in newer flutter version

**Comment by PixelToast** [comment] 2021-04-03 12:16
This is a result of the switch to CanvasKit, details can be found at: https://flutter.dev/docs/development/platform-integration/web-images#cross-origin-resource-sharing-cors

You can enable CORS in firebase specifically by adding header to images: https://firebase.google.com/docs/hosting/full-config#headers

Closing as a duplicate of #45955

**Closed by PixelToast** 2021-04-03 12:16 UTC

**Comment by Elemenopeee** [comment] 2021-04-09 13:32
People running into the same issue and looking for a workaround, please have a read ->

https://flutter.dev/docs/development/tools/web-renderers
