### ISSUE TITLE
error: The directory /Users/namchu/Documents/vrb_bank/vrb-mobile-banking/ios contains 2 projects, including multiple projects with the current extension (.xcodeproj). Specify the project to use with the -project option. Command: /usr/bin/arch, OS error code: 78

### ISSUE THREAD

**Issue by jonathanctn** [flutter/flutter#146677] opened 2024-04-12 07:52 UTC
## Command
```
flutter build ipa
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ProcessException: Process exited abnormally:
Command line invocation:
    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -list

User defaults from command line:
    IDEPackageSupportUseBuiltinSCM = YES

2024-04-12 14:51:59.064 xcodebuild[44690:8935117] Writing error result bundle to /var/folders/2w/25g51c3s4ll3s408tqcrynm40000gn/T/ResultBundle_2024-12-04_14-51-0059.xcresult
xcodebuild: error: The directory /Users/namchu/Documents/vrb_bank/vrb-mobile-banking/ios contains 2 projects, including multiple projects with the current extension (.xcodeproj). Specify the project to use with the -project option. Command: /usr/bin/arch, OS error code: 78
```
#0      RunResult.throwException (package:flutter_tools/src/base/process.dart:126:5)
#1      _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart:279:19)
<asynchronous suspension>
#2      XcodeProjectInterpreter.getInfo (package:flutter_tools/src/ios/xcodeproj.dart:321:30)
<asynchronous suspension>
#3      IosProject.projectInfo (package:flutter_tools/src/xcode_project.dart:318:29)
<asynchronous suspension>
#4      IosProject.buildSettingsForBuildInfo (package:flutter_tools/src/xcode_project.dart:278:36)
<asynchronous suspension>
#5      IosProject._parseHostAppBundleName (package:flutter_tools/src/xcode_project.dart:254:55)
<asynchronous suspension>
#6      IosProject.hostAppBundleName (package:flutter_tools/src/xcode_project.dart:243:35)
<asynchronous suspension>
#7      BuildableIOSApp.fromProject (package:flutter_tools/src/ios/application_package.dart:116:39)
<asynchronous suspension>
#8      FlutterApplicationPackageFactory.getPackageForPlatform (package:flutter_tools/src/flutter_application_package.dart:82:15)
<asynchronous suspension>
#9      _BuildIOSSubCommand.buildableIOSApp.<anonymous closure> (package:flutter_tools/src/commands/build_ios.dart:467:34)
<asynchronous suspension>
#10     _BuildIOSSubCommand.runCommand (package:flutter_tools/src/commands/build_ios.dart:504:33)
<asynchronous suspension>
#11     BuildIOSArchiveCommand.runCommand (package:flutter_tools/src/commands/build_ios.dart:295:50)
<asynchronous suspension>
#12     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1257:27)
<asynchronous suspension>
```
```
[!] Flutter (Channel stable, 3.7.7, on macOS 14.4.1 23E224 darwin-arm64, locale en-VN)
    • Flutter version 3.7.7 on channel stable at /Users/namchu/fvm/versions/3.7.7
    ! Warning: `dart` on your path resolves to /opt/homebrew/Cellar/dart/3.1.2/libexec/bin/dart, which is not inside your current Flutter SDK checkout at /Users/namchu/fvm/versions/3.7.7. Consider add

**Comment by darshankawar** [comment] 2024-04-12 08:39
> xcodebuild: error: The directory /Users/namchu/Documents/vrb_bank/vrb-mobile-banking/ios contains 2 projects, including multiple projects with the current extension (.xcodeproj). Specify the project to use with the -project option. Command: /usr/bin/arch, OS error code: 78

@jonathanctn As the error indicates,  you seem to have multiple copies of .xcodeproj file in ios sub-directory. The flutter build process detected it correctly and presented the error as mentioned, so the build process works properly. The error is in your project config/setup, you need to revisit and remove any duplicate project files.
Closing, as this is not a bug or an issue with flutter itself.
Also, you are on old version of stable. Current stable is 3.19.5. If you get similar error on latest version, write in comments and I'll reopen it.

**Closed by darshankawar** 2024-04-12 08:39 UTC
Labels: in triage
