### ISSUE TITLE
Why flutter app use much more memory than native app?

### ISSUE THREAD

**Issue by imagec** [flutter/flutter#48391] opened 2020-01-08 07:49 UTC
I create a default sample flutter app with android studio, and I find it use almost 40Mb memory. 

<details>
	<summary>logs</summary>

```bash
ailabs_s1l:/ # dumpsys meminfo com.example.flutter_app
Applications Memory Usage (in Kilobytes):
Uptime: 91218165 Realtime: 91218165

** MEMINFO in pid 15693 [com.example.flutter_app] **
                   Pss  Private  Private  SwapPss     Heap     Heap     Heap
                 Total    Dirty    Clean    Dirty     Size    Alloc     Free
                ------   ------   ------   ------   ------   ------   ------
  Native Heap     3679     3652        0       52     7680     5907     1772
  Dalvik Heap      340      324        0       48     2639     1119     1520
 Dalvik Other      231      228        0        1
        Stack       64       64        0        0
       Ashmem        2        0        0        0
    Other dev       12        0        8        0
     .so mmap    10112      300     8344       17
    .apk mmap      199        0       64        0
    .ttf mmap       57        0        8        0
    .dex mmap     2873        4     1808        0
    .oat mmap      914        0       64        0
    .art mmap      903      488       12        2
   Other mmap       23        4        0        0
   EGL mtrack     2026     2026        0        0
    GL mtrack    14240    14240        0        0
      Unknown     3329     3312        0        0
        TOTAL    39124    24642    10308      120    10319     7026     3292

 App Summary
                       Pss(KB)
                        ------
           Java Heap:      824
         Native Heap:     3652
                Code:    10592
               Stack:       64
            Graphics:    16266
       Private Other:     3552
              System:     4174

               TOTAL:    39124       TOTAL SWAP PSS:      120

 Objects
               Views:        8         ViewRootImpl:        1
         AppContexts:        3           Activities:        1
              Assets:        6        AssetManagers:        3
       Local Binders:       10        Proxy Binders:       15
       Parcel memory:        5         Parcel count:       20
    Death Recipients:        0      OpenSSL Sockets:        0
            WebViews:        0

 SQL
         MEMORY_USED:        0
  PAGECACHE_OVERFLOW:        0          MALLOC_SIZE:        0


 Asset Allocations
    zip:/data/app/com.example.flutter_app-5YKL3Q9mWbkrmc2bRcWkLg==/base.apk:/assets/flutter_assets/fonts/MaterialIcons-Regular.ttf: 131K
```

</details>

then I create a default sample native app, it use only 20Mb. Detail :

<details>
	<summary>logs</summary>

```bash
Applications Memory Usage (in Kilobytes):
Uptime: 91361079 Realtime: 91361079

** MEMINFO in pid 15865 [com.alibaba.ailabs.myapplication] **
                   Pss  Private  Private  SwapPss     Heap     Heap     Heap
                 Total    Dirty    Clean    Dirty     Size    Alloc     Free
                ------   ------   ------   ------   ------   ------   ------
  Native Heap     2318     2284        8       51     6656     4462     2193
  Dalvik Heap      642      620        0       50     2786     1250     1536
 Dalvik Other      396      396        0        0
        Stack       48       48        0        0
       Ashmem        2        0        0        0
    Other dev       12        0        8        0
     .so mmap     1683      132       24       17
    .jar mmap      344      344        0        0
    .apk mmap      367        0      112        0
    .ttf mmap       92        0        8        0
    .dex mmap     3524        4     2224        0
    .oat mmap      154        0        0        0
    .art mmap     2896     2648        4        0
   Other mmap        8        4        0        0
   EGL mtrack      608      608        0        0
    GL mtrack     6538     6538        0        0
      Unknown      506      480        8        0
        TOTAL    20256    14106     2396      118     9442     5712     3729

 App Summary
                       Pss(KB)
                        ------
           Java Heap:     3272
         Native Heap:     2284
                Code:     2848
               Stack:       48
            Graphics:     7146
       Private Other:      904
              System:     3754

               TOTAL:    20256       TOTAL SWAP PSS:      118

 Objects
               Views:       16         ViewRootImpl:        1
         AppContexts:        3           Activities:        1
              Assets:        5        AssetManagers:        3
       Local Binders:       10        Proxy Binders:       15
       Parcel memory:        3         Parcel count:       14
    Death Recipients:        0      OpenSSL Sockets:        0
            WebViews:        0

 SQL
         MEMORY_USED:        0
  PAGECACHE_OVERFLOW:        0          MALLOC_SIZE:        0

```

</details>

why flutter app use so much memory than native app, Is it reasonable？ thanks! 
All apps run on a device which cpu is mtk mt8167s and 1G ram.

**Comment by iapicca** [comment] 2020-01-08 10:29
Hi @imagec 
can you please provide your `flutter doctor -v`,
are you testing your app in `debug `or `release`?
Thank you

**Comment by imagec** [comment] 2020-01-08 11:30
> Hi @imagec
> can you please provide your `flutter doctor -v`,
> are you testing your app in `debug `or `release`?
> Thank you

I run it release mode.

the flutter doctor -v output:
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.12.6 16G29, locale zh-Hans-CN)
    • Flutter version 1.12.13+hotfix.5 at /Users/tycao/flutter/flutter
    • Framework revision 27321ebbad (4 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0


[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/tycao/Library/Android/sdk
    • Android NDK at /Users/tycao/Library/Android/sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ! CocoaPods 1.3.1 out of date (1.6.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade:
        sudo gem install cocoapods

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] Connected device (1 available)
    • AILABS S1L • UOGEPZ5PNJV8TOYP • android-arm • Android 6.1.0-D-20191230.1046 (API 27)

! Doctor found issues in 1 category.

**Comment by iapicca** [comment] 2020-01-08 11:59
thank you @imagec

**Comment by kangwang1988** [comment] 2020-01-08 16:14
@tvolkert 
@imagec  is from Alibaba and I can reproduce this issue using the latest master branch and a flutter create hello_world project.
Compared to a minimal android project, the flutter project has more  memory footprint over .so mmap and EGL/GL mtrack  part. The .so mmap part probably comes from the flutter.so and libapp.so. How about the EGL/GL mtrack part, is there any chance we can reduce the memory footprint for this part?

**Comment by tvolkert** [comment] 2020-01-08 17:42
Over to @cbracken 

Is this a regression, and if so, can you identify where it started happening?

**Comment by ofree8** [comment] 2020-01-14 04:52
> Over to @cbracken
> 
> Is this a regression, and if so, can you identify where it started happening?

Is there any progress on the issue?

**Comment by kangwang1988** [comment] 2020-01-20 07:00
@liyuqian

**Comment by liyuqian** [comment] 2020-01-21 06:19
The two biggest differences seem to be "graphics" and "code":

Flutter:
```
                Code:    10592
            Graphics:    16266
```

Native:
```
                Code:     2848
            Graphics:     7146
```

I wonder if that comes from using NDK and double/triple-buffered OpenGL surfaces. CC @chinmaygarde and @jason-simmons

**Comment by tvolkert** [comment] 2020-02-05 02:55
Also /cc @mraleph

**Comment by dnfield** [comment] 2020-02-05 17:37
I do not believe this a regression.

Flutter tells Skia to use a resource cache that is, by default, a multiplier on the screen resolution - we basically allocate enough space to hold 12 screens worth of space by default: 

https://github.com/flutter/engine/blob/master/shell/common/shell.cc#L747

You could probably make things a little tighter by turning down the Skia resource cache size (https://api.flutter.dev/flutter/services/SystemChannels/skia-constant.html).  It would be important to do this before you start drawing anything (e.g. before `runApp`), or if building your own engine, setting that limit lower yourself on the C++ side.

Jason or Chinmay will know more about what we're mmaping in for code, but I believe we have to mmap in the libflutter.so which will include things like ICU - we also need to mmap in the AOT blob which is probably a substantial part of that memory usage.  I'd be curious about what the memory footprint looks like in JIT mode, particularly if SpaceDart is available (/cc @zanderso).

Do you have a specific memory target in mind? Right now, it seems like the answer to your question is "because it needs to load more resources".  But if you have a specific memory target in mind, we could probably work together to find ways to reach it.

**Comment by zanderso** [comment] 2020-02-05 17:48
Regular JIT and SpaceDart may not be smaller since they won't be tree-shaken. Overall footprint may also not be smaller once native code gets JIT compiled.

**Comment by jonahwilliams** [comment] 2020-02-05 18:47
stripping more source information with --split-debug-info would also reduce the size of the AOT blob by about 8-10%. Would show up in memory usage as well?

**Comment by dnfield** [comment] 2020-02-05 19:07
@jonahwilliams yes, I believe so.  We should test that though.

**Comment by liyuqian** [comment] 2020-03-10 00:41
BTW, we have a memory benchmark on a `hello_world` Flutter app that shows 16463KB of memory usage. A simple first step towards this issue might be just to write a simple memory test that reveals the memory usage of a default sample Flutter app.

**Comment by dnfield** [comment] 2020-03-18 20:42
@imagec there are a few answers and possible improvements suggested in the comments on this issue.  I'm not sure what other action could be taken at this point to improve the issue.

If you have any more specific examples of where you think Flutter cold use less memory, we'd be happy to explore those as separate issues from this one.  For now I'm going to close this one as resolved - we can file new issues as necessary to track ways to further reduce Flutter's memory consumption.

**Closed by dnfield** 2020-03-18 20:42 UTC
Labels: customer: gold, engine, perf: memory, severe: performance, ▣ platform-android
