### ISSUE TITLE
iOS 13 Device, app stuck at slash screen when use VSCode, but not with terminal.(mDNS lookup failed, attempting fallback to reading device log )

### ISSUE THREAD

**Issue by jerryzhoujw** [flutter/flutter#43570] opened 2019-10-26 16:25 UTC
## Steps to Reproduce

1. iPhone8(iOS13.1.3) device + VSCode:
         *  log stop at: `Checking for advertised Dart observatories...` 
         *  app just `stuck at splash page`.
2. iPhone8(iOS13.1.3) device + Terminal `flutter run --debug --verbose -d xxxxxx`:
         * log show `mDNS lookup failed, attempting fallback to reading device log.` 
         * the app can `pass to home page`.
3. iOS Simulator(iOS13) + VSCode:
         * log show are fine.
         * the app can debug as normal.

**Target Platform:iOS**
**Target OS version/browser:iOS13.1.3**
**Devices:iPhone8 device**

## Logs

`flutter run --debug --verbose`:
* Because it works when I run it thought terminal, so are there a way to run with `--verbose` by VSCode's triangle button?
```
this is the log when run with terminal.
...
[ +405 ms] success
[        ] (lldb)     safequit
[ +120 ms] Process 782 detached
[  +59 ms] Application launched on the device. Waiting for observatory port.
[   +3 ms] Checking for advertised Dart observatories...
[+5020 ms] mDNS lookup failed, attempting fallback to reading device log.
[        ] Waiting for observatory port.
【no more logs after this point】
...
```

`flutter doctor -v`:
```
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.14.6 18G103, locale en-CN)
    • Flutter version 1.9.1+hotfix.6 at /Users/jerryzhou/Documents/code/flutter/sdk/flutter
    • Framework revision 68587a0916 (6 weeks ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0


[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/jerryzhou/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 34.0.2
    • Dart plugin version 183.5901
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✗] Cannot determine if IntelliJ is installed
    ✗ Directory listing failed

[✓] VS Code (version 1.39.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.5.1

[✓] Connected device (2 available)
    • iPhone       • 1daca728d75535c21ced151fc7829191064d0e00 • ios • iOS 13.1.3
    • iPhone 11 Pro Max • 4543F274-DE8D-45CC-8600-EA889708FB37     • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-13-1 (simulator)
```

**Comment by jerryzhoujw** [comment] 2019-10-27 04:58
still exist after I upgrade macOS

```
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.15 19A603, locale en-CN)
    • Flutter version 1.9.1+hotfix.6 at /Users/jerryzhou/Documents/code/flutter/sdk/flutter
    • Framework revision 68587a0916 (6 weeks ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/jerryzhou/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 34.0.2
    • Dart plugin version 183.5901
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✗] Cannot determine if IntelliJ is installed
    ✗ Directory listing failed

[✓] VS Code (version 1.39.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.5.1

[✓] Connected device (2 available)
    • iPhonejerry       • 1daca728d75535c21ced151fc7829191064d0e00 • ios • iOS 13.1.3
    • iPhone 11 Pro Max • 4543F274-DE8D-45CC-8600-EA889708FB37     • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-13-1 (simulator)
```

**Comment by rayfusion** [comment] 2019-10-27 21:58
I have the same issue.

**Comment by BondarenkoStas** [comment] 2019-10-28 16:11
@jerryzhoujw @rayfusion can you please check it with master channel? I wonder if that was fixed with https://github.com/flutter/flutter/pull/42026 or it's another bug.

**Comment by stx** [comment] 2019-10-28 16:56
Same problem. Using latest master. Started after iOS 13 + Catalina.

**Comment by leonardodavila** [comment] 2019-10-31 01:51
I'm having the same issue, does anyone know how to fix it?

**Comment by jerryzhoujw** [comment] 2019-10-31 03:05
@leonardodavila  you have to use simulator for now as I know.

**Comment by leonardodavila** [comment] 2019-10-31 19:38
I see! But my app uses the camera, and i can't use the simulator for that :(

**Comment by jerryzhoujw** [comment] 2019-11-01 02:43
any possible use the album first instead ?

**Comment by swesti** [comment] 2019-11-05 20:02
I am experiencing this also (iOS 13 device).

**Comment by jmagman** [comment] 2019-11-05 22:46
This may be fixed by https://github.com/flutter/engine/pull/13451.
Duplicate of https://github.com/flutter/flutter/issues/41085.

**Closed by jmagman** 2019-11-05 22:46 UTC
Labels: severe: crash, ‎‍💻platform-catalina, ⌺‬ platform-ios

**Comment by thief1010** [comment] 2019-11-06 03:19
I also encountered the same problem. Is this because of the incompatibility between the iOS 13 and the version of flutter?

**Comment by stx** [comment] 2019-11-06 15:42
Found a workaround that worked for me and at least one other person:

Remove `dart` from the macOS firewall, click allow when the network connection popup occurs after running flutter run, and then mDNS lookup failures seem to stop, which makes it run successfully in VSCode.

I also ran into a secondary issue, which was resolved through Xcode > Window > Devices and Simulators, select the device, check the box `Connect via network` and then uncheck the box, and then `Error connecting to the service protocol` errors seem to stop.

**Comment by jerryzhoujw** [comment] 2019-11-06 16:00
@stx  where does the  `macOS firewall` and `dart` in it?  would you mind upload a screenshort for that ?

**Comment by stx** [comment] 2019-11-06 16:04
@jerryzhoujw 

![image](https://user-images.githubusercontent.com/1284134/68314940-48742900-0074-11ea-9ba6-fee413656097.png)

It's important to remove it even if it says currently allowed, and then let the next `flutter run` re-prompt it, add it again, then run `flutter run` again and hopefully it works.

**Comment by jerryzhoujw** [comment] 2019-11-07 18:05
@stx Thank you, I see I didn't enabled firewall at all.
<img width="664" alt="Screen Shot 2019-11-08 at 2 04 34 AM" src="https://user-images.githubusercontent.com/6405390/68414931-27265080-01cc-11ea-9cb7-9d263be91c97.png">

**Comment by jerryzhoujw** [comment] 2019-11-07 18:37
> iPhone8(iOS13.1.3) device + VSCode:
 >  * log stop at: Checking for advertised Dart observatories...
 >   * app just stuck at splash page.
 > 
 >  iPhone8(iOS13.1.3) device + Terminal flutter run --debug --verbose -d xxxxxx:
 >   * log show mDNS lookup failed, attempting fallback to reading device log.
 >  * the app can pass to home page.

@jmagman  since `mDNS lookup failed` not the issue, app `stuck at splash page` when `use device` is. I think maybe it's not duplicate of #41085.

**Comment by jerryzhoujw** [comment] 2019-11-07 18:42
@thief1010 it's not incompatibility, since iOS13 on simulator works well.

**Comment by jerryzhoujw** [comment] 2019-11-07 19:02
After upgrade to iOS13.2 on device and upgrade Xcode to 11.2,   `app stuck at splash page when use device ` are disappear. 

Not sure it's fixed by I do `firewall` disable -> enable -> disable, or it's fixed by `iOS13.2`,  or it's fixed by `Xcode11.2`, or it's fixed by flutter side.

> flutter doctor -v

```
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.15.1 19B88, locale en-CN)
    • Flutter version 1.9.1+hotfix.6 at /Users/jerryzhou/Documents/code/flutter/sdk/flutter
    • Framework revision 68587a0916 (8 weeks ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0


[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/jerryzhou/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2, Build version 11B52
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 34.0.2
    • Dart plugin version 183.5901
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✗] Cannot determine if IntelliJ is installed
    ✗ Directory listing failed

[✓] VS Code (version 1.39.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.6.0
```

**Comment by thief1010** [comment] 2019-11-18 02:20
> After upgrade to `iOS13.2` on device and upgrade `Xcode to 11.2`, `app stuck at splash page when use device ` are disappear.
> 
> Not sure it's fixed by I do `firewall` (disable -> enable -> disable), or it's fixed by `iOS13.2`, or it's fixed by `Xcode11.2`, ~or it's fixed by flutter engine side~(flutter engine version not changed in my case).
> 
> > flutter doctor -v
> 
> ```
> [✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.15.1 19B88, locale en-CN)
>     • Flutter version 1.9.1+hotfix.6 at /Users/jerryzhou/Documents/code/flutter/sdk/flutter
>     • Framework revision 68587a0916 (8 weeks ago), 2019-09-13 19:46:58 -0700
>     • Engine revision b863200c37
>     • Dart version 2.5.0
> 
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
>     • Android SDK at /Users/jerryzhou/Library/Android/sdk
>     • Android NDK location not configured (optional; useful for native profiling support)
>     • Platform android-29, build-tools 28.0.3
>     • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
>     • All Android licenses accepted.
> 
> [✓] Xcode - develop for iOS and macOS (Xcode 11.2)
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • Xcode 11.2, Build version 11B52
>     • CocoaPods version 1.8.4
> 
> [✓] Android Studio (version 3.5)
>     • Android Studio at /Applications/Android Studio.app/Contents
>     • Flutter plugin version 34.0.2
>     • Dart plugin version 183.5901
>     • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
> 
> [✗] Cannot determine if IntelliJ is installed
>     ✗ Directory listing failed
> 
> [✓] VS Code (version 1.39.2)
>     • VS Code at /Applications/Visual Studio Code.app/Contents
>     • Flutter extension version 3.6.0
> ```

In other words,it will work in this case that XCode and iOS be upgraded at the same time?

**Comment by jerryzhoujw** [comment] 2020-02-04 01:39
hi @thief1010
  Sorry for delay...

  And yes, it works for me.  

> > After upgrade to `iOS13.2` on device and upgrade `Xcode to 11.2`, `app stuck at splash page when use device ` are disappear.
> > Not sure it's fixed by I do `firewall` (disable -> enable -> disable), or it's fixed by `iOS13.2`, or it's fixed by `Xcode11.2`, ~or it's fixed by flutter engine side~(flutter engine version not changed in my case).
> > > flutter doctor -v
> > 
> > 
> > ```
> > [✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.15.1 19B88, locale en-CN)
> >     • Flutter version 1.9.1+hotfix.6 at /Users/jerryzhou/Documents/code/flutter/sdk/flutter
> >     • Framework revision 68587a0916 (8 weeks ago), 2019-09-13 19:46:58 -0700
> >     • Engine revision b863200c37
> >     • Dart version 2.5.0
> > 
> > 
> > [✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
> >     • Android SDK at /Users/jerryzhou/Library/Android/sdk
> >     • Android NDK location not configured (optional; useful for native profiling support)
> >     • Platform android-29, build-tools 28.0.3
> >     • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
> >     • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
> >     • All Android licenses accepted.
> > 
> > [✓] Xcode - develop for iOS and macOS (Xcode 11.2)
> >     • Xcode at /Applications/Xcode.app/Contents/Developer
> >     • Xcode 11.2, Build version 11B52
> >     • CocoaPods version 1.8.4
> > 
> > [✓] Android Studio (version 3.5)
> >     • Android Studio at /Applications/Android Studio.app/Contents
> >     • Flutter plugin version 34.0.2
> >     • Dart plugin version 183.5901
> >     • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
> > 
> > [✗] Cannot determine if IntelliJ is installed
> >     ✗ Directory listing failed
> > 
> > [✓] VS Code (version 1.39.2)
> >     • VS Code at /Applications/Visual Studio Code.app/Contents
> >     • Flutter extension version 3.6.0
> > ```
> 
> In other words,it will work in this case that XCode and iOS be upgraded at the same time?

Hi @thief1010,
    Sorry for delay...
    And yes, it works for me.

**Comment by Jackylee1992** [comment] 2020-10-10 08:16
> @jerryzhoujw
> 
> System Preferences > Security & Privacy > Firewall Options...
> 
> ![image](https://user-images.githubusercontent.com/1284134/68314940-48742900-0074-11ea-9ba6-fee413656097.png)
> 
> It's important to remove it even if it says currently allowed, and then let the next `flutter run` re-prompt it, add it again, then run `flutter run` again and hopefully it works.

You really save my life! Thank you bro!!! 
Turn off firewall fixed the problem.
