### ISSUE TITLE
Improve error message when createState returns old/invalid state object

### ISSUE THREAD

**Issue by Permutohedron** [flutter/flutter#25459] opened 2018-12-17 14:29 UTC
## Steps to Reproduce

1. Run app (https://gist.github.com/Permutohedron/7932f900805e9daccd8566ea36b7ef4b)
2. Scroll ListView down
3. Scroll up

## Logs

```
flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following assertion was thrown building NotificationListener<KeepAliveNotification>:
flutter: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3803 pos 12: '_state._widget ==
flutter: null': is not true.
flutter:
flutter: **Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new?template=BUG.md**
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #2      new StatefulElement (package:flutter/src/widgets/framework.dart:3803:12)
flutter: #3      StatefulWidget.createElement (package:flutter/src/widgets/framework.dart:795:38)
flutter: #4      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2948:40)
flutter: #5      Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
flutter: #6      SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
flutter: #7      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
flutter: #8      Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
flutter: #9      SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
flutter: #10     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
flutter: #11     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
flutter: #12     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
flutter: #13     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
flutter: #14     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
flutter: #15     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
flutter: #16     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
flutter: #17     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
flutter: #18     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
flutter: #19     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
flutter: #20     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
flutter: #21     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
flutter: #22     ParentDataElement.mount (package:flutter/src/widgets/framework.dart:4047:11)
flutter: #23     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
flutter: #24     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
flutter: #25     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
flutter: #26     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
flutter: #27     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
flutter: #28     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3848:11)
flutter: #29     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
flutter: #30     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
flutter: #31     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
flutter: #32     SliverMultiBoxAdaptorElement.updateChild (package:flutter/src/widgets/sliver.dart:1028:36)
flutter: #33     SliverMultiBoxAdaptorElement.createChild.<anonymous closure> (package:flutter/src/widgets/sliver.dart:1013:20)
flutter: #34     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2266:19)
flutter: #35     SliverMultiBoxAdaptorElement.createChild (package:flutter/src/widgets/sliver.dart:1006:11)
flutter: #36     RenderSliverMultiBoxAdaptor._createOrObtainChild.<anonymous closure> (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:274:23)
flutter: #37     RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1730:58)
flutter: #38     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:799:15)
flutter: #39     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1730:13)
flutter: #40     RenderSliverMultiBoxAdaptor._createOrObtainChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:263:5)
flutter: #41     RenderSliverMultiBoxAdaptor.insertAndLayoutLeadingChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:372:5)
flutter: #42     RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:99:29)
flutter: #43     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
flutter: #44     RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:182:11)
flutter: #45     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
flutter: #46     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:405:13)
flutter: #47     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1316:12)
flutter: #48     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1234:20)
flutter: #49     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1509:7)
flutter: #50     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:768:18)
flutter: #51     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:281:19)
flutter: #52     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:677:13)
flutter: #53     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:219:5)
flutter: #54     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
flutter: #55     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
flutter: #56     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
flutter: #57     _invoke (dart:ui/hooks.dart:154:13)
flutter: #58     _drawFrame (dart:ui/hooks.dart:143:3)
flutter: (elided 2 frames from class _AssertionError)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
flutter: Another exception was thrown: 'package:flutter/src/rendering/sliver_multi_box_adaptor.dart': Failed assertion: line 235 pos 16: 'indexOf(child) > index': is not true.
flutter: Another exception was thrown: 'package:flutter/src/rendering/sliver_multi_box_adaptor.dart': Failed assertion: line 235 pos 16: 'indexOf(child) > index': is not true.
flutter: Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 2270 pos 20: '_debugCurrentBuildTarget == context': is not true.
flutter: Another exception was thrown: 'package:flutter/src/rendering/sliver_multi_box_adaptor.dart': Failed assertion: line 461 pos 12: 'child.hasSize': is not true.
flutter: Another exception was thrown: RenderBox was not laid out: RenderIndexedSemantics#b90e0 NEEDS-LAYOUT NEEDS-PAINT
flutter: Another exception was thrown: 'package:flutter/src/widgets/sliver.dart': Failed assertion: line 1053 pos 14: '_childElements.containsKey(index)': is not true.
flutter: Another exception was thrown: 'package:flutter/src/rendering/sliver_multi_box_adaptor.dart': Failed assertion: line 461 pos 12: 'child.hasSize': is not true.
flutter: Another exception was thrown: RenderBox was not laid out: RenderIndexedSemantics#b90e0 NEEDS-LAYOUT NEEDS-PAINT
flutter: Another exception was thrown: 'package:flutter/src/widgets/sliver.dart': Failed assertion: line 1053 pos 14: '_childElements.containsKey(index)': is not true.
flutter: Another exception was thrown: 'package:flutter/src/rendering/sliver_multi_box_adaptor.dart': Failed assertion: line 461 pos 12: 'child.hasSize': is not true.
flutter: Another exception was thrown: RenderBox was not laid out: RenderIndexedSemantics#b90e0 NEEDS-LAYOUT NEEDS-PAINT
```

**Comment by Permutohedron** [comment] 2018-12-17 15:04
Ok, It was the problem with the `MyListTile` stateful widget that returned **old state** instance on `createState()` call. Still message should be more meaningful in this case

**Comment by zoechi** [comment] 2019-01-17 07:56
Duplicate of #11975

**Closed by zoechi** 2019-01-17 07:56 UTC
Labels: a: quality, framework, severe: crash
