### ISSUE TITLE
in_app_purchase codelabs demo has incorrect import causing a crash during `firebase deploy`

### ISSUE THREAD

**Issue by hhimanshu** [flutter/flutter#108939] opened 2022-08-04 00:45 UTC
Hello,

I am trying to deploy firebase functions from [this repo](https://github.com/flutter/codelabs/tree/main/in_app_purchases/step_00/firebase-backend) as defined on **Step 9** of [this codelab](https://codelabs.developers.google.com/codelabs/flutter-in-app-purchases#8)

I have already installed all dependencies using `npm install` command. Now, when I deploy by running `firebase deploy`, I get the following error

```
➜  firebase-backend git:(main) ✗ firebase deploy

=== Deploying to 'dashcliker'...

i  deploying firestore, functions
Running command: npm --prefix "$RESOURCE_DIR" run lint

> functions@ lint /Users/hhimanshu/code/prsnl/fltr/codelabs/in_app_purchases/step_00/firebase-backend/functions
> eslint --ext .js,.ts .

Running command: npm --prefix "$RESOURCE_DIR" run build

> functions@ build /Users/hhimanshu/code/prsnl/fltr/codelabs/in_app_purchases/step_00/firebase-backend/functions
> tsc

src/iap.repository.ts:1:9 - error TS2724: '"firebase-admin/lib/firestore"' has no exported member named 'firestore'. Did you mean 'Firestore'?

1 import {firestore} from "firebase-admin/lib/firestore";
          ~~~~~~~~~


Found 1 error in src/iap.repository.ts:1

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! functions@ build: `tsc`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the functions@ build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/hhimanshu/.npm/_logs/2022-08-04T00_39_33_224Z-debug.log

Error: functions predeploy error: Command terminated with non-zero exit code 2

Having trouble? Try firebase [command] --help
➜  firebase-backend git:(main) ✗ 

```

My node and firebase versions are below
```
➜  firebase-backend git:(main) ✗ node -v
v14.17.4
➜  firebase-backend git:(main) ✗ firebase --version
11.3.0
```

Could someone please help? How can I fix this issue and make progress?

Thank you in advance

**Comment by exaby73** [comment] 2022-08-04 07:48
I can reproduce this issue. Looks like the import is incorrect. For a fix, you can change the import from `import {firestore} from "firebase-admin/lib/firestore"` to `import firestore from "firebase-admin/lib/firestore"`

**Comment by exaby73** [comment] 2022-08-04 07:51
cc: @domesticmouse

**Comment by hhimanshu** [comment] 2022-08-04 23:03
@exaby73 , thank you for your help. I can confirm that after using the following import, the `firebase deploy` command ran successfully.
```
import firestore from "firebase-admin/lib/firestore"
```

Log
```
✔  functions: Finished running predeploy script.
i  firestore: reading indexes from firestore.indexes.json...
i  cloud.firestore: checking firestore.rules for compilation errors...
✔  cloud.firestore: rules file firestore.rules compiled successfully
i  functions: ensuring required API cloudfunctions.googleapis.com is enabled...
i  functions: ensuring required API cloudbuild.googleapis.com is enabled...
i  artifactregistry: ensuring required API artifactregistry.googleapis.com is enabled...
✔  artifactregistry: required API artifactregistry.googleapis.com is enabled
✔  functions: required API cloudfunctions.googleapis.com is enabled
✔  functions: required API cloudbuild.googleapis.com is enabled
i  functions: preparing codebase default for deployment
i  firestore: uploading rules firestore.rules...
✔  firestore: deployed indexes in firestore.indexes.json successfully
✔  firestore: released rules firestore.rules to cloud.firestore
i  functions: cleaning up build files...

✔  Deploy complete!
```

**Comment by exaby73** [comment] 2022-08-05 04:57
@hhimanshu Glad that solved your issue, but the import is still incorrect in the repository. Re-opening this issue to track it

**Comment by kermitdefroghere** [comment] 2022-09-21 18:18
fyi. The recommended syntax didn't work for me. I needed to use:

import * as firestore from "firebase-admin/lib/firestore"

**Comment by lim-enhui** [comment] 2022-10-15 08:35
Package subpath './lib/firestore' is not defined by "exports" /node_modules/firebase-admin/package.json I got this error

    "firebase-admin": "^11.0.1",

Error: Failed to load function definition from source: Failed to generate manifest from function source: Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/firestore' is not defined by "exports" in /functions/node_modules/firebase-admin/package.json

**Comment by simonpham** [comment] 2022-11-12 11:30
WORKING SOLUTION (12 Nov 2022): Use these:
```javascript
import {firestore} from "firebase-admin";
```

```javascript
import {https} from "firebase-functions";
```

package.json
```json
    "camelcase-keys": "^6.2.2",
```

**Comment by larakreisz** [comment] 2022-12-19 21:56
@simonpham please share your entire code example. I'm a bit lost and I don't know, what I am supposed to the withe the line `import {https} from "firebase-functions";`

**Comment by simonpham** [comment] 2022-12-20 00:57
@larakreisz you can see my PR https://github.com/flutter/codelabs/pull/1250

https://github.com/flutter/codelabs/pull/1250/files

**Comment by larakreisz** [comment] 2022-12-21 00:41
WORKING SOLUTION (21 Dez 2022): I implemented the changes in the way [simonpham](https://github.com/simonpham) suggested it and it worked. I'm so happy. Thank you so much : )

**Comment by toniremi** [comment] 2023-01-26 06:39
I would like to add that I was also having problems with camelcase-keys using latest version, when doing firebase deploy I would get an error saying that there were multiple initializeApp() calls (when I only called it once on index.ts).

Using @simonpham solution and downgrading camelcase-keys to 6.2.2 solved the issue.

Thank you so much!

**Comment by jatin-web** [comment] 2023-02-15 04:14
> I can reproduce this issue. Looks like the import is incorrect. For a fix, you can change the import from `import {firestore} from "firebase-admin/lib/firestore"` to `import firestore from "firebase-admin/lib/firestore"`

I tried this, but it is saying=>  Module '"/Users/jatinsaini/StudioProjects/Upwork/Buddhism-app-and-firebase/firebase-backend/functions/node_modules/firebase-admin/lib/firestore/index"' has no default export.

**Comment by larakreisz** [comment] 2023-02-15 15:29
> > I can reproduce this issue. Looks like the import is incorrect. For a fix, you can change the import from `import {firestore} from "firebase-admin/lib/firestore"` to `import firestore from "firebase-admin/lib/firestore"`
> 
> I tried this, but it is saying=> Module '"/Users/jatinsaini/StudioProjects/Upwork/Buddhism-app-and-firebase/firebase-backend/functions/node_modules/firebase-admin/lib/firestore/index"' has no default export.

Try to change it as described [here](https://github.com/flutter/codelabs/pull/1250/files)

**Comment by miquelbeltran** [comment] 2023-04-25 15:00
As the codelab has been upgraded to implement a Dart server, and no longer depends on `firebase deploy`, we can close this one.

**Closed by miquelbeltran** 2023-04-25 15:00 UTC
Labels: severe: crash, plugin, d: codelabs, p: in_app_purchase, documentation, P4
