### ISSUE TITLE
"Runner quits expectedly" error when xcode build is done on all apps after upgrading to Monterey macOS

### ISSUE THREAD

**Issue by haroonkhan335** [flutter/flutter#84815] opened 2021-06-17 22:22 UTC
After upgrading to Monterey I am unable to run any ios app on my M1 macbook pro ... What is the issue here?

Problem Report from Runner
```
Incident Identifier: 0120E59B-934C-4F55-B35E-E0BEA32A0912
CrashReporter Key:   0EFFD5AD-F351-AC39-86B5-8CC273B37EFF
Hardware Model:      MacBookPro17,1
Process:             Runner [3189]
Path:                /Users/USER/Library/Developer/CoreSimulator/Devices/BB8DA5E7-D3C6-4F20-BF7C-B72B2092441B/data/Containers/Bundle/Application/B85F43AA-1DA7-4155-BBAD-2D79794A87BB/Runner.app/Runner
Identifier:          com.example.test
Version:             1.0.0 (1)
Code Type:           X86-64 (Native)
Role:                Foreground
Parent Process:      launchd_sim [509]
Coalition:           com.apple.CoreSimulator.SimDevice.BB8DA5E7-D3C6-4F20-BF7C-B72B2092441B [596]
Responsible Process: SimulatorTrampoline [488]

Date/Time:           2021-06-18 02:58:02.5885 +0500
Launch Time:         2021-06-18 02:57:59.8846 +0500
OS Version:          macOS 12.0 (21A5248p)
Release Type:        User
Report Version:      104

Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Subtype: KERN_INVALID_ADDRESS at 0x0000000000000000
VM Region Info: 0 is not in any region.  Bytes before following region: 4310077440
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      UNUSED SPACE AT START
--->  
      mapped file                 100e69000-100e6d000    [   16K] r-x/r-x SM=COW  ...t_id=2467e501
Exception Note:  EXC_CORPSE_NOTIFY
Termination Reason: SIGNAL 11 Segmentation fault: 11
Terminating Process: exc handler [3189]

Triggered by Thread:  0

Application Specific Information:



Thread 0 Crashed:
0   ???                           	    0x7ff7ffdfabd8 ???
1   <translation info unavailable>	       0x100e9de5c ???
2   dyld                          	       0x20102f88f dyld4::prepareSim(dyld4::RuntimeState&, char const*) + 890
3   dyld                          	       0x20102e6b5 dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*) + 244
4   dyld                          	       0x20102e4b4 start + 388
5   ???                           	               0x3 ???

Thread 1:: com.apple.rosetta.exceptionserver
0   ???                           	    0x7ff7ffde7320 ???
1   ???                           	    0x7ff7ffe001a0 ???


Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x0000000108ef4af8  rcx: 0x0000000000000000  rdx: 0x0000000000000001
  rdi: 0x0000000000000000  rsi: 0x0000000000000000  rbp: 0x0000000000000000  rsp: 0x0000000109591000
   r8: 0x270529b6e6b600a7   r9: 0x0000000000000000  r10: 0x0000000109591000  r11: 0x00000001093b4010
  r12: 0x0000000000000000  r13: 0x00000001093b4060  r14: 0x000000020109d080  r15: 0x0000000000000000
  rip: <unavailable>       rfl: 0x0000000000000283
 tmp0: 0x0000000100e8bc64 tmp1: 0x0000000100e8af8c tmp2: 0x0000000201047ca3


Binary Images:
               0x0 - 0xffffffffffffffff ??? (*) <00000000-0000-0000-0000-000000000000> ???
       0x201029000 -        0x201090fff dyld (*) <4e207376-cc5d-3986-a0bd-4d09f4217e68> /usr/lib/dyld

EOF

Model: MacBookPro17,1, BootROM 7429.0.72.0.3, proc 8:4:4 processors, 8 GB, SMC 
Graphics: kHW_AppleM1Item, Apple M1, spdisplays_builtin
Memory Module: LPDDR4
AirPort: spairport_wireless_card_type_wifi, wl0: May  4 2021 18:24:35 version 18.20.281.2.7.8.107 FWID 01-7c11bd60
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB 3.1 Bus
USB Device: USB 3.1 Bus
Thunderbolt Bus: MacBook Pro, Apple Inc.
Thunderbolt Bus: MacBook Pro, Apple Inc.

```

flutter doctor -v
```
[✓] Flutter (Channel stable, 2.2.2, on macOS 12.0 21A5248p darwin-arm, locale
    en)
    • Flutter version 2.2.2 at /Users/haroonkhan/development/flutter
    • Framework revision d79295af24 (6 days ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/haroonkhan/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.57.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.23.0

[✓] Connected device (2 available)
    • iPhone 12 Pro Max (mobile) • BB8DA5E7-D3C6-4F20-BF7C-B72B2092441B • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 91.0.4472.106

• No issues found!
```
![image](https://user-images.githubusercontent.com/62588381/122479399-7194c380-cfe4-11eb-82f7-7fbc941e894c.png)

**Comment by TahaTesser** [comment] 2021-06-18 10:13
Hi @haroonkhan335 
Can you please try to run the native ios app for testing? This could be Xcode related issue on Monterey rather than Flutter
Thank you

**Comment by muhlba91** [comment] 2021-06-20 15:03
running into the same issue with non-beta xcode and ios 14 simulator as well as xcode beta and ios 15 simulator.

beta and ios 15 simulator output is:
```

Incident Identifier: 3B42DC48-890E-48D3-9235-135C1A0A6BA5
CrashReporter Key:   592FB02E-E127-7C11-1364-DFB74018AC9C
Hardware Model:      MacBookPro17,1
Process:             Runner [48863]
Path:                /Users/USER/Library/Developer/CoreSimulator/Devices/0F1675DB-D2B8-40CA-BF0A-12AC478F5F15/data/Containers/Bundle/Application/4FF25E77-DC29-4C04-9A40-3D9B368F2880/Runner.app/Runner
Identifier:          io.niftyside.homecenter
Version:             0.0.0 (0)
Code Type:           X86-64 (Native)
Role:                Foreground
Parent Process:      launchd_sim [47911]
Coalition:           com.apple.CoreSimulator.SimDevice.0F1675DB-D2B8-40CA-BF0A-12AC478F5F15 [349844]
Responsible Process: SimulatorTrampoline [957]

Date/Time:           2021-06-20 17:02:37.4526 +0200
Launch Time:         2021-06-20 17:02:37.4175 +0200
OS Version:          macOS 12.0 (21A5248p)
Release Type:        User
Report Version:      104

Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Subtype: KERN_INVALID_ADDRESS at 0x0000000000000000
VM Region Info: 0 is not in any region.  Bytes before following region: 4303421440
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      UNUSED SPACE AT START
--->  
      mapped file                 100810000-100d38000    [ 5280K] r-x/r-x SM=COW  ...t_id=83091467
Exception Note:  EXC_CORPSE_NOTIFY
Termination Reason: SIGNAL 11 Segmentation fault: 11
Terminating Process: exc handler [48863]

Triggered by Thread:  0

Application Specific Information:



Thread 0 Crashed:
0   ???                           	    0x7ff7ffbeabd8 ???
1   <translation info unavailable>	       0x101144e5c ???
2   dyld                          	       0x20129388f dyld4::prepareSim(dyld4::RuntimeState&, char const*) + 890
3   dyld                          	       0x2012926b5 dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*) + 244
4   dyld                          	       0x2012924b4 start + 388
5   dyld                          	       0x20128d000 ???

Thread 1:: com.apple.rosetta.exceptionserver
0   ???                           	    0x7ff7ffbd7320 ???
1   ???                           	    0x7ff7ffbf01a0 ???


Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x000000010919baf8  rcx: 0x0000000000000000  rdx: 0x0000000000000001
  rdi: 0x0000000000000000  rsi: 0x0000000000000000  rbp: 0x0000000000000000  rsp: 0x0000000109853000
   r8: 0x8239896e65d800b7   r9: 0x0000000000000000  r10: 0x0000000109853000  r11: 0x000000010965b010
  r12: 0x0000000000000000  r13: 0x000000010965b060  r14: 0x0000000201301080  r15: 0x0000000000000000
  rip: <unavailable>       rfl: 0x0000000000000283
 tmp0: 0x0000000101132c64 tmp1: 0x0000000101131f8c tmp2: 0x00000002012abca3


Binary Images:
               0x0 - 0xffffffffffffffff ??? (*) <00000000-0000-0000-0000-000000000000> ???
       0x20128d000 -        0x2012f4fff dyld (*) <4e207376-cc5d-3986-a0bd-4d09f4217e68> /usr/lib/dyld

EOF

Model: MacBookPro17,1, BootROM 7429.0.72.0.3, proc 8:4:4 processors, 16 GB, SMC 
Graphics: kHW_AppleM1Item, Apple M1, spdisplays_builtin
Memory Module: LPDDR4
AirPort: spairport_wireless_card_type_wifi, wl0: May  4 2021 18:24:35 version 18.20.281.2.7.8.107 FWID 01-7c11bd60
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB 3.1 Bus
USB Device: USB 3.1 Bus
USB Device: Yubikey 4 OTP+U2F+CCID
Thunderbolt Bus: MacBook Pro, Apple Inc.
Thunderbolt Bus: MacBook Pro, Apple Inc.
```

**Comment by jamal** [comment] 2021-06-27 23:31
I'm also running into this issue, I haven't tried on a physical device. Building for macOS works in Monterey, though.

**Comment by muhlba91** [comment] 2021-07-03 08:45
still getting the same issue with Monterey Beta 2, Xcode (simulator with iOS 14.5) as well as Xcode Beta 2 (simulator with iOS 15.0).

**Comment by haroonkhan335** [comment] 2021-07-03 12:49
So the culprit of the issue is Monterey OS which fails to run any app on Simulator. If you are on Monterey you must debug your apps on a physical iOS device. 

Downgraded macOS to Big Sur and working now..

**Comment by muhlba91** [comment] 2021-07-03 12:55
good to know downgrading solves the issue.

however, what do you mean by debug on a physical device? i tried running flutter run with the physical device as target and i receive the same error. the only way for me to get the app running is through a „release“ with either a testflight release or through xcode and the application bundle. but then i can‘t attach the debugger and receive the logs…

**Comment by TahaTesser** [comment] 2021-07-05 09:07
Hi @haroonkhan335 
Thanks for the confirmation, since you already downgraded to Big Sur, I feel too safe to close this issue for https://github.com/flutter/flutter/issues/85545

@muhlba91  @jamal 
If you happen to reproduce the same issue on the physical device,  please follow up on the other issue, if the issue reproduces different, please file a new issue instead 
Thnk you

**Closed by TahaTesser** 2021-07-05 09:07 UTC
Labels: in triage
