### ISSUE TITLE
[tool_crash] FileSystemException: Cannot delete file, OS Error: Access is denied., errno = 5

### ISSUE THREAD

**Issue by osama550** [flutter/flutter#115307] opened 2022-11-14 21:30 UTC
## Command
```
flutter --quiet assemble --no-version-check --depfile D:\graduate_project\build\app\intermediates\flutter\debug/flutter_build.d --output D:\graduate_project\build\app\intermediates\flutter\debug -dTargetFile=D:\graduate_project\lib\main.dart -dTargetPlatform=android -dBuildMode=debug -dTrackWidgetCreation=true --DartDefines=Zmx1dHRlci5pbnNwZWN0b3Iuc3RydWN0dXJlZEVycm9ycz10cnVl,RkxVVFRFUl9XRUJfQVVUT19ERVRFQ1Q9dHJ1ZQ== debug_android_application
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Cannot delete file, OS Error: Access is denied.
, errno = 5
```
#0      _File.throwIfError (dart:io/file_impl.dart:635:7)
#1      _File._deleteSync (dart:io/file_impl.dart:298:5)
#2      FileSystemEntity.deleteSync (dart:io/file_system_entity.dart:427:7)
#3      ForwardingFileSystemEntity.deleteSync (package:file/src/forwarding/forwarding_file_system_entity.dart:70:16)
#4      ForwardingFileSystemEntity.deleteSync (package:file/src/forwarding/forwarding_file_system_entity.dart:70:16)
#5      ErrorHandlingFileSystem.deleteIfExists (package:flutter_tools/src/base/error_handling_io.dart:82:12)
#6      Target.clearStamp (package:flutter_tools/src/build_system/build_system.dart:164:29)
#7      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:868:19)
<asynchronous suspension>
#8      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:606:16)
<asynchronous suspension>
#9      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:316:32)
<asynchronous suspension>
#10     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1209:27)
<asynchronous suspension>
#11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#12     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#13     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
<asynchronous suspension>
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#15     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 3.3.6, on Microsoft Windows [Version 10.0.22621.819], locale en-US)
    • Flutter version 3.3.6 on channel stable at C:\src\flutter_windows_3.3.6-stable\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6928314d50 (3 weeks ago), 2022-10-25 16:34:41 -0400
    • Engine revision 3ad69d7be3
    • Dart version 2.18.2
    • DevTools version 2.15.0

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:/Users/20127/AppData/Local/Android/Sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = C:/Users/20127/AppData/Local/Android/Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✗] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✗] Visual Studio - develop for Windows
    ✗ Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[✓] Android Studio (version 2021.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] Connected device (3 available)
    • A33w (mobile)     • 458SCI59FMFMQK5T • android-arm    • Android 5.1 (API 22)
    • Windows (desktop) • windows          • windows-x64    • Microsoft Windows [Version 10.0.22621.819]
    • Edge (web)        • edge             • web-javascript • Microsoft Edge 107.0.1418.42

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 3 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 6928314d505d2bb4777be05e45d7808a5aa91d2a
### Plugins
hexcolor-2.0.7

**Comment by darshankawar** [comment] 2022-11-15 05:17
Closing as duplicate of https://github.com/flutter/flutter/issues/88830 and https://github.com/flutter/flutter/issues/103861

**Closed by darshankawar** 2022-11-15 05:17 UTC
Labels: in triage
