### ISSUE TITLE
[tool_crash] SocketException: Send failed, OS Error: No route to host, errno = 65

### ISSUE THREAD

**Issue by roygroothulze** [flutter/flutter#159798] opened 2024-12-04 15:11 UTC
## Command
```sh
flutter --no-color run --machine --track-widget-creation --device-id=00008112-000545CE3C21A01E --start-paused --dart-define=flutter.inspector.structuredErrors=true lib/host/main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
SocketException: Send failed, OS Error: No route to host, errno = 65
```console
#0      _NativeSocket.send (dart:io-patch/socket_patch.dart:1275:34)
#1      _RawDatagramSocket.send (dart:io-patch/socket_patch.dart:2590:15)
#2      MDnsClient.lookup (package:multicast_dns/multicast_dns.dart:219:22)
#3      MDnsVmServiceDiscovery._pollingVmService (package:flutter_tools/src/mdns_discovery.dart:232:66)
<asynchronous suspension>
#4      MDnsVmServiceDiscovery.firstMatchingVmService (package:flutter_tools/src/mdns_discovery.dart:188:56)
<asynchronous suspension>
#5      MDnsVmServiceDiscovery.getVMServiceUriForLaunch (package:flutter_tools/src/mdns_discovery.dart:433:50)
<asynchronous suspension>
#6      Future.any.onValue (dart:async/future.dart:628:5)
<asynchronous suspension>
```
```console
[!] Flutter (Channel stable, 3.24.4, on macOS 15.1.1 24B91 darwin-arm64, locale en-US)
    • Flutter version 3.24.4 on channel stable at /Users/roygroothulze/development/flutter
    ! Warning: `dart` on your path resolves to /opt/homebrew/Cellar/dart/3.5.3/libexec/bin/dart, which is not inside your current Flutter SDK checkout at /Users/roygroothulze/development/flutter. Consider adding /Users/roygroothulze/development/flutter/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 603104015d (6 weeks ago), 2024-10-24 08:01:25 -0700
    • Engine revision db49896cf2
    • Dart version 3.5.4
    • DevTools version 2.37.3
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/roygroothulze/Library/Android/sdk
    • Platform android-35, build-tools 34.0.0
    • Java binary at: /Users/roygroothulze/Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 21.0.3+-79915917-b509.11)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.1)
    • Xcode at /Applications/Xcode-16.1.0.app/Contents/Developer
    • Build 16B40
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.2)
    • Android Studio at /Users/roygroothulze/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.3+-79915917-b509.11)

[✓] Connected device (5 available)
    • CodeBlock’s iPad Air (mobile)   • 00008112-000545CE3C21A01E • ios            • iOS 18.2 22C5142a
    • CodeBlock’s iPhone (mobile)     • 00008101-0011490102C1001E • ios            • iOS 18.1.1 22B91
    • macOS (desktop)                 • macos                     • darwin-arm64   • macOS 15.1.1 24B91 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad     • darwin         • macOS 15.1.1 24B91 darwin-arm64
    • Chrome (web)                    • chrome                    • web-javascript • Google Chrome 131.0.6778.108

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.34+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: ba393198430278b6595976de84fe170f553cc728
### Plugins
adjust_sdk-5.0.2
cloud_firestore-5.5.0
cloud_firestore_web-4.3.4
firebase_auth-5.3.3
firebase_auth_web-5.13.4
firebase_core-3.8.0
firebase_core_web-2.18.1
firebase_crashlytics-4.1.5
flutter_local_notifications-18.0.1
flutter_local_notifications_linux-5.0.0
google_mobile_ads-5.2.0
in_app_review-2.0.10
mobile_scanner-6.0.2
path_provider-2.1.5
path_provider_android-2.2.14
path_provider_foundation-2.4.0
path_provider_linux-2.2.1
path_provider_windows-2.3.0
permission_handler-11.3.1
permission_handler_android-12.0.13
permission_handler_apple-9.4.5
permission_handler_html-0.1.3+5
permission_handler_windows-0.2.1
purchases_flutter-8.2.2
purchases_ui_flutter-8.2.2
shared_preferences-2.3.3
shared_preferences_android-2.3.4
shared_preferences_foundation-2.5.3
shared_preferences_linux-2.4.1
shared_preferences_web-2.4.2
shared_preferences_windows-2.4.1
sqflite-2.4.1
sqflite_android-2.4.0
sqflite_darwin-2.4.1
telemetrydecksdk-0.6.0
url_launcher-6.3.1
url_launcher_android-6.3.14
url_launcher_ios-6.3.1
url_launcher_linux-3.2.1
url_launcher_macos-3.2.1
url_launcher_web-2.3.3
url_launcher_windows-3.1.3
webview_flutter-4.9.0
webview_flutter_android-3.16.9
webview_flutter_wkwebview-3.16.3

**Comment by danagbemava-nc** [comment] 2024-12-05 07:07
Closing this as a duplicate of https://github.com/flutter/flutter/issues/150131

**Closed by danagbemava-nc** 2024-12-05 07:07 UTC
Labels: in triage
