### ISSUE TITLE
Flutter Doctor --Android Licenses has error: Could not find or load class Wint

### ISSUE THREAD

**Issue by zawlh** [flutter/flutter#85892] opened 2021-07-05 09:57 UTC

**Comment by asashour** [comment] 2021-07-05 10:25
Duplicate of #85893

**Comment by darshankawar** [comment] 2021-07-05 13:20
Closing this as self-duplicate of https://github.com/flutter/flutter/issues/85893. Please don't open multiple issues for same reason.

**Closed by darshankawar** 2021-07-05 13:20 UTC
Labels: in triage
