### ISSUE TITLE
CupertinoTextFormFieldRow: accept suffix

### ISSUE THREAD

**Issue by chad-bekmezian-snap** [flutter/flutter#159558] opened 2024-11-27 16:57 UTC
### Use case

The CupertinoTextField has a suffix property, which can be set via its constructor. When using a CupertinoTextField in a form, the typically used widget is CupertinoTextFormFieldRow. However, the CupertinoTextFormFieldRow does not accept a suffix property, so there is no way to set the suffix on the underlying CupertinoTextField. The CupertinoTextFormFieldRow already accepts and passed down a prefix widget, I propose adding support for a suffix as well.

### Proposal

The CupertinoTextField has a suffix property, which can be set via its constructor. When using a CupertinoTextField in a form, the typically used widget is CupertinoTextFormFieldRow. However, the CupertinoTextFormFieldRow does not accept a suffix property, so there is no way to set the suffix on the underlying CupertinoTextField. The CupertinoTextFormFieldRow already accepts and passed down a prefix widget, I propose adding support for a suffix as well.

**Comment by danagbemava-nc** [comment] 2024-11-28 07:08
This is a duplicate of https://github.com/flutter/flutter/issues/103385

Kindly subscribe to the original issue for updates. 

Closing from here. 

Thank you

**Closed by danagbemava-nc** 2024-11-28 07:08 UTC
Labels: in triage
