### ISSUE TITLE
[proposal] InteractiveViewer DataTable widget

### ISSUE THREAD

**Issue by marcosagni98** [flutter/flutter#81817] opened 2021-05-04 09:32 UTC
For responsive dataTables

This can already be made by a simple InteractiveViewer, but what I would like also is to have a sticky property in the DataColumn thats scrolls horizontaly and gets bigger and smaller when the rest of the table is being zoom in and out

To put an example, google sheets app

**Comment by HansMuller** [comment] 2021-05-04 16:25
CC @justinmc @goderbauer

**Comment by justinmc** [comment] 2021-06-23 18:00
@goderbauer was working on ways to do this that don't involve InteractiveViewer.

**Comment by Piinks** [comment] 2022-11-29 23:34
I am going to close this as a duplicate of https://github.com/flutter/flutter/issues/87370, but I have added it to the 2D scrolling project where we are keeping track of all of these requests. This work is currently underway.

**Closed by Piinks** 2022-11-29 23:34 UTC
Labels: framework, f: material design, proposal, passed first triage
