### ISSUE TITLE
Xcode validation fails, Flutter.framework: code object is not signed at all

### ISSUE THREAD

**Issue by skionthursday** [flutter/flutter#71164] opened 2020-11-24 18:51 UTC
I have a problem validating my Flutter build/application to upload to the App Store. I have no issues with “flutter build iOS” and the Xcode archive process builds successfully. Xcode validation process fails with:

Code signing [device name] fails

IDEDistributionPipeline.log ends with:

```
2020-11-24 17:56:07 +0000  /var/folders/vt/2fh335xs3t79gy3ntyj0j9200000gq/T/XcodeDistPipeline.~~~q7NhTX/Root/Payload/Runner.app/Frameworks/Flutter.framework/Flutter-Roberto’s MacBook Pro: replacing existing signature
2020-11-24 17:56:07 +0000  /var/folders/vt/2fh335xs3t79gy3ntyj0j9200000gq/T/XcodeDistPipeline.~~~q7NhTX/Root/Payload/Runner.app/Frameworks/Flutter.framework/Flutter-Roberto’s MacBook Pro: code object is not signed at all
2020-11-24 17:56:07 +0000  /usr/bin/codesign exited with 1
```

I opened an Apple TSI where Apple developer support commented:

"It appears that the signing tools are having a problem with a framework in your build named Flutter.framework --- It appears that the framework is already signed and the attempt to resign the framework is failing."

Apple TSI support then said that they only support Apple solutions and that this issue should be reported to the 3rd party.

Doing some Github research, the above is the same as #65319 which was closed unresolved due to lack of input from issue reporter. Issue #39507 looks similar in that the Flutter.framework has a permission issue not allowing signing.

Steps to reproduce
 - flutter build iOS
 - Xcode: using Automatic signing
 - Xcode: Product -> scheme -> Runner
 - Xcode: Product -> Destination -> Any iOS device (arm64)
 - Xcode: Product -> Archive
 - Validate (with proper certificate and App Store distribution profile)
 - Validation fails

My flutter doctor -v. (Note: I develop my android version on my Windows machine)

roberto@Robertos-MacBook-Pro plgps2 % flutter doctor -v
```
[✓] Flutter (Channel stable, 1.22.4, on Mac OS X 10.15.7 19H15 darwin-x64, locale en-US)
    • Flutter version 1.22.4 at /Users/roberto/OneDrive/iOS Dev/flutter
    • Framework revision 1aafb3a8b9 (11 days ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_SDK_ROOT to that location.
      You may also want to add it to your PATH environment variable.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.9.3

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[!] Connected device                          
    ! No devices available

! Doctor found issues in 3 categories.
```

**Comment by darshankawar** [comment] 2020-11-25 07:13
@skionthursday 
Can you try by setting `Other Code Signing` option to `deep` and see if it works ?

<img width="522" alt="Screenshot 2020-11-25 at 12 41 51 PM" src="https://user-images.githubusercontent.com/67046386/100194413-abed2500-2f1b-11eb-8020-51529fb4c55a.png">

**Comment by skionthursday** [comment] 2020-11-25 16:34
In build settings I added Other Code Signing Flags -> Release  -> any STK -> deep
in VS Code: flutter clean -> flutter build ios -> completed successfully and display error msgs captured in attached zip file
in xCode: Project -> archive -> failed with text below, all msgs exported in attached zip file

Code Signing /Users/roberto/Library/Developer/Xcode/DerivedData/Runner-auivwctkeopyjeazsixpyysrvdtj/Build/Intermediates.noindex/ArchiveIntermediates/Runner/InstallationBuildProductsLocation/Applications/Runner.app/Frameworks/DKImagePickerController.framework with Identity Apple Development: Robert Skowron (S2YYF7DKU2)
/usr/bin/codesign --force --sign 7F68957529F4E28F85AB3759EA138704C2AF7A20 deep --preserve-metadata=identifier,entitlements '/Users/roberto/Library/Developer/Xcode/DerivedData/Runner-auivwctkeopyjeazsixpyysrvdtj/Build/Intermediates.noindex/ArchiveIntermediates/Runner/InstallationBuildProductsLocation/Applications/Runner.app/Frameworks/DKImagePickerController.framework'
deep: No such file or directory
Command PhaseScriptExecution failed with a nonzero exit code

[Archive.zip](https://github.com/flutter/flutter/files/5598001/Archive.zip)

**Comment by darshankawar** [comment] 2020-11-26 06:18
@skionthursday 
Can you try [this](https://github.com/flutter/flutter/issues/49495#issuecomment-691526850) and check if it work ?

**Comment by skionthursday** [comment] 2020-11-26 16:06
I checked this link and upon reading I find that my Debug.xconfig and Release.xconfig do contain the #include "Generated.xconfig" statement. Thus I find nothing to change.  
When I rerun flutter build ios command, it fails and reports this error:

Code Signing /Users/roberto/PLGPSiOSLocal/FlutterDesktop/PlantListGPS/r0/plgps2/build/ios/Release-iphoneos/Runner.app/Frameworks/DKImagePickerController.framework
    with Identity Apple Development: Robert Skowron (S2YYF7DKU2)
    /usr/bin/codesign --force --sign 7F68957529F4E28F85AB3759EA138704C2AF7A20 deep --preserve-metadata=identifier,entitlements
    '/Users/roberto/PLGPSiOSLocal/FlutterDesktop/PlantListGPS/r0/plgps2/build/ios/Release-iphoneos/Runner.app/Frameworks/DKImagePickerController.framework'
    deep: No such file or directory

This is also what xcode archive process reports and errors out.

Attached is screenshot of flutter paths.

<img width="1280" alt="Screen Shot 2020-11-26 at 8 42 03 AM" src="https://user-images.githubusercontent.com/66576919/100372324-51f56980-2fc6-11eb-8b3c-2df4cead4a61.png">

**Comment by darshankawar** [comment] 2020-11-27 05:47
@skionthursday 
Not under `any sdk`, `deep` value is to be assigned directly for `Release` code signing. Based on your earlier comment, I think you added to `any sdk -> deep`. Can you confirm that ?
Also, if this doesn't work, remove above settings and directly try the solution I linked earlier, because from your latest error logs, it says `iphoneos/Runner.app/Frameworks/DKImagePickerController.framework'
deep: No such file or directory`

**Comment by skionthursday** [comment] 2020-11-27 16:12
To confirm I am in the right spot of xcode: in Project -> Runner -> Build Settings -> Signing -> Other Code Signing Flags -> Release, I removed sdk -> deep. Testing again, I find that flutter build ios completes with success, archive builds with success, but validation fails as described above.  I confirmed Debug.xconfig and Release.xconfig have #include "Generated.xconfig" statements. Screenshots in attached zip file. 

I returned to xcode to try again adding deep, but when getting focus on the release field, xcode (version 12.2) the UI auto-adds the default of "any stk". I am not allowed to deep directing to Release as a "+" is presented to select from a list Apple prod environments. Screenshot in zipfile. Thank you for your assistance.

[Archive 27Nov.zip](https://github.com/flutter/flutter/files/5608743/Archive.27Nov.zip)

**Comment by skionthursday** [comment] 2020-11-29 23:44
Here are the steps to reproduce this issues error using flutter demo app and having an Apple Distr. Cert. With these steps others should be able to reproduce issue for local observation.

- Using Visual Studio Code
- Create and change to test directory on MacOs
- Run: flutter create testapp1
- Change android/app/build.gradle -> ApplicationID -> “com.hsiplgps.testapp1” 
- Confirm working app flutter run without debugging using Apple simulator iPhone 12 Pro Max -> count number of clicks
- Run: flutter clean
- Run: flutter build iOS
- Close Visual Studio Code
- Log into Apple Developer Account
- Register New Bundle
- Register New Identifier -> App ID -> com.hsiplgps.testapp1 , no capabilities, using defaults
- Log into Apple App Store Connect
- “+” Create New App -> check ios, name-> plgpstestapp1, bundle ID -> com.hsiplgps.testapp1, Lang -> English US, sku -> 1000, Full access
- Log into Apple Developer Account
- Create Profile (distribution), Distribution -> App Store, App ID -> testapp1, Select your dev cert, provision name -> testapp1
- Download Profile and store on local machine
- On local Mac
- Double click downloaded Profile file on local machine
- Open Xcode -> Runner.xcodeproj in ios directory of this app
- General tab change bundle ID -> com.hsiplgps.testapp1, deselect iPad, Signing: select Autosign, Assign team (my dev name/id)
- Run Project -> Scheme -> Runner
- Run Project -> Destination -> Any ios Device
- Run Project -> Archive
- Archive build is successful
- Validate, use distribution profile created above, import from local machine if needed -> continue with defaults
- Validation fails -> below are last few messages of IDEDistributionProvisioning.log
- Full log zipped and attached to this comment

2020-11-29 17:06:15 +0000  Entitlements for <IDEDistributionItem: 0x7fa4f8a6e470; bundleID='(null)', path='<DVTFilePath:0x7fa4fe429a90:'/Users/roberto/Library/Developer/Xcode/Archives/2020-11-29/Runner 11-29-20, 10.05 AM.xcarchive/Products/Applications/Runner.app/Frameworks/Flutter.framework/Flutter-Roberto’s MacBook Pro'>', codeSigningInfo='<_DVTCodeSigningInformation_Path: 0x7fa4ff761cd0; isSigned='1', isAdHocSigned='0', signingCertificate='<DVTSigningCertificate: 0x7fa500f13ca0; name='Developer ID Application: FLUTTER.IO LLC (S8QB4VV633)', hash='67C5219DDC039491EE28BD55F9C03F7A19218C5E', serialNumber='<DVTSigningCertificateSerialNumber: 0x7fa4fe5e7ef0>', certificateKinds='(
    "1.2.840.113635.100.6.1.13"
), issueDate='2019-08-13 15:21:20 +0000''>', entitlements='(null)', teamID='S8QB4VV633', identifier='io.flutter.flutter', executablePath='<DVTFilePath:0x7fa4fe429a90:'/Users/roberto/Library/Developer/Xcode/Archives/2020-11-29/Runner 11-29-20, 10.05 AM.xcarchive/Products/Applications/Runner.app/Frameworks/Flutter.framework/Flutter-Roberto’s MacBook Pro'>', hardenedRuntime='1'>'>: {
}

2020-11-29 17:06:15 +0000  Writing entitlements for <IDEDistributionItem: 0x7fa4f8a6e470; bundleID='(null)', path='<DVTFilePath:0x7fa4fe429a90:'/Users/roberto/Library/Developer/Xcode/Archives/2020-11-29/Runner 11-29-20, 10.05 AM.xcarchive/Products/Applications/Runner.app/Frameworks/Flutter.framework/Flutter-Roberto’s MacBook Pro'>', codeSigningInfo='<_DVTCodeSigningInformation_Path: 0x7fa4ff761cd0; isSigned='1', isAdHocSigned='0', signingCertificate='<DVTSigningCertificate: 0x7fa4fa352140; name='Developer ID Application: FLUTTER.IO LLC (S8QB4VV633)', hash='67C5219DDC039491EE28BD55F9C03F7A19218C5E', serialNumber='<DVTSigningCertificateSerialNumber: 0x7fa4fe5cdec0>', certificateKinds='(
    "1.2.840.113635.100.6.1.13"
), issueDate='2019-08-13 15:21:20 +0000''>', entitlements='(null)', teamID='S8QB4VV633', identifier='io.flutter.flutter', executablePath='<DVTFilePath:0x7fa4fe429a90:'/Users/roberto/Library/Developer/Xcode/Archives/2020-11-29/Runner 11-29-20, 10.05 AM.xcarchive/Products/Applications/Runner.app/Frameworks/Flutter.framework/Flutter-Roberto’s MacBook Pro'>', hardenedRuntime='1'>'> to: /var/folders/vt/2fh335xs3t79gy3ntyj0j9200000gq/T/XcodeDistPipeline.~~~VmwSO8/entitlements~~~AEiFq3

2020-11-29 17:06:15 +0000  Running /usr/bin/codesign '-vvv' '--force' '--sign' 'D09D37A55E86E51817AD0FF06289E35E9E576CD6' '--entitlements' '/var/folders/vt/2fh335xs3t79gy3ntyj0j9200000gq/T/XcodeDistPipeline.~~~VmwSO8/entitlements~~~AEiFq3' '--preserve-metadata=identifier,flags,runtime' '/var/folders/vt/2fh335xs3t79gy3ntyj0j9200000gq/T/XcodeDistPipeline.~~~VmwSO8/Root/Payload/Runner.app/Frameworks/Flutter.framework/Flutter-Roberto’s MacBook Pro'

2020-11-29 17:06:15 +0000  /var/folders/vt/2fh335xs3t79gy3ntyj0j9200000gq/T/XcodeDistPipeline.~~~VmwSO8/Root/Payload/Runner.app/Frameworks/Flutter.framework/Flutter-Roberto’s MacBook Pro: replacing existing signature

2020-11-29 17:06:15 +0000  /var/folders/vt/2fh335xs3t79gy3ntyj0j9200000gq/T/XcodeDistPipeline.~~~VmwSO8/Root/Payload/Runner.app/Frameworks/Flutter.framework/Flutter-Roberto’s MacBook Pro: code object is not signed at all

2020-11-29 17:06:15 +0000  /usr/bin/codesign exited with 1

[Archive 29 Nov.zip](https://github.com/flutter/flutter/files/5613116/Archive.29.Nov.zip)

**Comment by darshankawar** [comment] 2020-11-30 06:12
Keeping this issue open for further triage, as I am unable to replicate it on the setup I tried (Android studio instead of VSCode per author).

**Comment by jmagman** [comment] 2020-12-01 01:28
All the logs say `Flutter.framework/Flutter-Roberto’s MacBook Pro` which should be `Flutter.framework/Flutter`.  Are you able to reproduce with your project on another machine?

What's the output of `ls -la path/to/flutter/bin/cache/artifacts/engine/ios-release/Flutter.framework/`

**Comment by skionthursday** [comment] 2020-12-01 17:15
"Roberto's MacBook Pro" is the name of my development MacBook. I do not have another MacOS device. As a dev machine, it can be renamed, new users added, etc. With an apostrophe in the name, that could be trouble and can be removed. Please advise if you'd like me to do something and retest.

No where in the process is "Roberto's MacBookPro" entered thus the Mac system name appears to be drawn from system attributes into the process.

Output requested:

Last login: Sun Nov 29 09:23:22 on console
roberto@Robertos-MacBook-Pro ~ % ls -la path/to/flutter/bin/cache/artifacts/engine/ios-release/Flutter.framework/
ls: path/to/flutter/bin/cache/artifacts/engine/ios-release/Flutter.framework/: No such file or directory
roberto@Robertos-MacBook-Pro ~ %

**Comment by jmagman** [comment] 2020-12-01 17:58
Did you literally run `ls -la path/to/flutter/bin/cache/artifacts/engine/ios-release/Flutter.framework/`?   I meant for you to replace `path/to/flutter` with the path to your Flutter SDK.  😄 

That directory should be present since your repro steps include running `flutter build ios`.

**Comment by skionthursday** [comment] 2020-12-01 19:17
Sorry, it's been a while and my unix skills are a bit rusty. I did not find the desired directory. So I did flutter build ios which was successful and then worked the command up the directory structure until it found something. My results are below.

roberto@Robertos-MacBook-Pro Flutter % pwd                                                             
/Users/roberto/OneDrive/Flutter
roberto@Robertos-MacBook-Pro Flutter % ls -la bin/cache/artifacts/engine/ios-release/Flutter.framework/
ls: bin/cache/artifacts/engine/ios-release/Flutter.framework/: No such file or directory
roberto@Robertos-MacBook-Pro Flutter % ls -la bin/cache/artifacts/engine/ios-release/                  
ls: bin/cache/artifacts/engine/ios-release/: No such file or directory
roberto@Robertos-MacBook-Pro Flutter % ls -la bin/cache/artifacts/engine             
total 0
drwxr-xr-x@ 15 roberto  staff  480 Oct 18 18:22 .
drwxr-xr-x@ 12 roberto  staff  384 Oct 18 18:27 ..
drwxr-xr-x@  3 roberto  staff   96 Nov 25 08:57 android-arm
drwxr-xr-x@  4 roberto  staff  128 Nov 25 08:57 android-arm-profile
drwxr-xr-x@  4 roberto  staff  128 Nov 25 08:57 android-arm-release
drwxr-xr-x@  3 roberto  staff   96 Nov 25 08:57 android-arm64
drwxr-xr-x@  4 roberto  staff  128 Nov 25 08:57 android-arm64-profile
drwxr-xr-x@  4 roberto  staff  128 Nov 25 08:57 android-arm64-release
drwxr-xr-x@  4 roberto  staff  128 Nov 25 08:57 android-x64
drwxr-xr-x@  4 roberto  staff  128 Nov 25 08:57 android-x64-profile
drwxr-xr-x@  4 roberto  staff  128 Nov 25 08:57 android-x64-release
drwxr-xr-x@  4 roberto  staff  128 Nov 25 08:57 android-x86
drwxr-xr-x@  3 roberto  staff   96 Nov 25 08:57 android-x86-jit-release
drwxr-xr-x@  4 roberto  staff  128 Oct 18 18:13 common
drwxr-xr-x@  9 roberto  staff  288 Nov 25 08:57 windows-x64
roberto@Robertos-MacBook-Pro Flutter %

**Comment by jmagman** [comment] 2020-12-01 19:55
`flutter doctor` thinks it's at `/Users/roberto/OneDrive/iOS Dev/flutter`, not `/Users/roberto/OneDrive/Flutter`.  You have two copies installed?  You should clear that up before we go further.

Once you do, what's:
```
ls -la /Users/roberto/OneDrive/iOS Dev/flutter/bin/cache/artifacts/engine/
```

`flutter build ios` should have added `bin/cache/artifacts/engine/ios-release/` artifacts.

P.S. I recommend you take it out of OneDrive or any directories that sync around.

**Comment by kf6gpe** [comment] 2020-12-01 23:10
Thanks, @jmagman for looking at this. I'm going to drop the `will need additional triage` label since it's gotten routed to you.

**Comment by skionthursday** [comment] 2020-12-03 00:22
My issue has been resolved. Thank you for pointing out the multiple flutter installations on my development device. I believe this was the root cause of the issue with an incorrect PATH variable . Also suspect was using OneDrive sync to keep app source in sync between Windows/Android and MacOS development. The following is what I did.

My development environment became messy with multiple locations of flutter. I remove two locations of flutter resources, deleting the the sdk locations. I then created a new, third location and downloaded and installed a new MacOS version of the flutter. I then maintained the $HOME/.zshrc path reference to point to my new sdk install. I also disconnected the OneDrive file sync and moved my app source to a new location.

In VS Code, a flutter pub get rebuilt needed resources and my app functioned. Flutter build ios was successful. Xcode opened the new location and Product Archive, Validation and Distribution successfully completed.

Thank you everyone for your help and support as I am able to sent app updates to the App Store.

**Comment by jmagman** [comment] 2020-12-03 00:28
Environment issue, closing.

**Closed by jmagman** 2020-12-03 00:28 UTC
Labels: passed first triage, platform-ios, t: xcode, tool

**Comment by lcsvcn** [comment] 2021-03-14 18:00
@jmagman How did you solve this?

**Comment by jmagman** [comment] 2021-03-15 17:39
@lcsvcn I wasn't the one having the problem, the originator explained it here https://github.com/flutter/flutter/issues/71164#issuecomment-737576800
If you are seeing similar symptoms, please make sure you file a new issue and fully fill out the template so we can take a look.
