### ISSUE TITLE
iOS 16.6 pickMultiVideo Crash

### ISSUE THREAD

**Issue by Aldaniee** [flutter/flutter#134229] opened 2023-09-07 16:43 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing package issues](https://github.com/flutter/flutter/issues?q=is%3Aopen+is%3Aissue+label%3Apackage)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### What package does this bug report belong to?

image_picker

### What target platforms are you seeing this bug on?

iOS

### Have you already upgraded your packages?

Yes

### Dependency versions

<details><summary>pubspec.lock</summary>

```lock
image_picker:
    dependency: "direct main"
    description:
      name: image_picker
      sha256: "7d7f2768df2a8b0a3cefa5ef4f84636121987d403130e70b17ef7e2cf650ba84"
      url: "https://pub.dev"
    source: hosted
    version: "1.0.4"
  image_picker_android:
    dependency: transitive
    description:
      name: image_picker_android
      sha256: "8179b54039b50eee561676232304f487602e2950ffb3e8995ed9034d6505ca34"
      url: "https://pub.dev"
    source: hosted
    version: "0.8.7+4"
  image_picker_for_web:
    dependency: transitive
    description:
      name: image_picker_for_web
      sha256: "869fe8a64771b7afbc99fc433a5f7be2fea4d1cb3d7c11a48b6b579eb9c797f0"
      url: "https://pub.dev"
    source: hosted
    version: "2.2.0"
  image_picker_ios:
    dependency: transitive
    description:
      name: image_picker_ios
      sha256: b3e2f21feb28b24dd73a35d7ad6e83f568337c70afab5eabac876e23803f264b
      url: "https://pub.dev"
    source: hosted
    version: "0.8.8"
  image_picker_linux:
    dependency: transitive
    description:
      name: image_picker_linux
      sha256: "4ed1d9bb36f7cd60aa6e6cd479779cc56a4cb4e4de8f49d487b1aaad831300fa"
      url: "https://pub.dev"
    source: hosted
    version: "0.2.1+1"
  image_picker_macos:
    dependency: transitive
    description:
      name: image_picker_macos
      sha256: "3f5ad1e8112a9a6111c46d0b57a7be2286a9a07fc6e1976fdf5be2bd31d4ff62"
      url: "https://pub.dev"
    source: hosted
    version: "0.2.1+1"
  image_picker_platform_interface:
    dependency: transitive
    description:
      name: image_picker_platform_interface
      sha256: c1134543ae2187e85299996d21c526b2f403854994026d575ae4cf30d7bb2a32
      url: "https://pub.dev"
    source: hosted
    version: "2.9.0"
  image_picker_windows:
    dependency: transitive
    description:
      name: image_picker_windows
      sha256: "6ad07afc4eb1bc25f3a01084d28520496c4a3bb0cb13685435838167c9dcedeb"
      url: "https://pub.dev"
    source: hosted
    version: "0.2.1+1"
```

</details>

### Steps to reproduce

This was reproducible on iOS 16.6 on a real device. This is not reproducible on iOS 16.4.

1. Run the example app on an iOS 16.6 device
2. Select multiple videos

### Expected results

The selection screen for multiple videos appears.

### Actual results

App freeezes for some time and then crashes with this error:

```
Syncing files to device Aidan’s iPhone...
Attempt to present <UIImagePickerController: 0x11a813400> on <FlutterViewController: 0x101825600> which is waiting for a delayed presention of <UIImagePickerController: 0x11a808a00> to complete
Attempt to present <UIImagePickerController: 0x11a80a400> on <FlutterViewController: 0x101825600> which is waiting for a delayed presention of <UIImagePickerController: 0x11a808a00> to complete
[LayoutConstraints] Unsupported layout off the main thread for UITextEffectsWindow with no associated or ancestor view controller
This application is modifying the autolayout engine from a background thread after the engine was accessed from the main thread. This can lead to engine corruption and weird crashes.
 Stack:(
	0   CoreAutoLayout                      0x00000001e8631dc0 11B7BCA7-7250-30FB-B4D8-A902FEE394D9 + 56768
	1   CoreAutoLayout                      0x00000001e8628994 11B7BCA7-7250-30FB-B4D8-A902FEE394D9 + 18836
	2   CoreAutoLayout                      0x00000001e86288c4 11B7BCA7-7250-30FB-B4D8-A902FEE394D9 + 18628
	3   CoreAutoLayout                      0x00000001e8628650 11B7BCA7-7250-30FB-B4D8-A902FEE394D9 + 18000
	4   UIKitCore                           0x00000001cd1cbc60 7D57A1D1-856F-338D-97DB-880C4EC8B02E + 23648
	5   UIKitCore                           0x00000001cd1ca420 7D57A1D1-856F-338D-97DB-880C4EC8B02E + 17440
	6   QuartzCore                          0x00000001cc684f30 8682CC56-125A-3565-8075-978CC718B93F + 40752
	7   QuartzCore                          0x00000001cc6984ac 8682CC56-125A-3565-8075-978CC718B93F + 119980
	8   QuartzCore                          0x00000001cc6a98d8 8682CC56-125A-3565-8075-978CC718B93F + 190680
	9   QuartzCore                          0x00000001cc6d8e80 8682CC56-125A-3565-8075-978CC718B93F + 384640
	10  QuartzCore                          0x00000001cc6c2df0 8682CC56-125A-3565-8075-978CC718B93F + 294384
	11  CoreFoundation                      0x00000001cb1e7234 A900B459-0127-379E-9CBA-0EAB9C5D559F + 590388
	12  CoreFoundation                      0x00000001cb171410 A900B459-0127-379E-9CBA-0EAB9C5D559F + 107536
	13  CoreFoundation                      0x00000001cb1d119c A900B459-0127-379E-9CBA-0EAB9C5D559F + 500124
	14  CoreFoundation                      0x00000001cb1d63ec CFRunLoopRunSpecific + 612
	15  Flutter                             0x00000001031fc03c _ZN3fml17MessageLoopDarwin3RunEv + 88
	16  Flutter                             0x00000001031fabe0 _ZNSt21_LIBCPP_ABI_NAMESPACE14__thread_proxyB6v15000INS_5tupleIJNS_10unique_ptrINS_15__thread_structENS_14default_deleteIS3_EEEEZN3fml6ThreadC1ERKNS_8functionIFvRKNS8_12ThreadConfigEEEESC_E3$_0EEEEEPvSJ_ + 208
	17  libsystem_pthread.dylib             0x000000022af966b8 _pthread_start + 148
	18  libsystem_pthread.dylib             0x000000022af95b88 thread_start + 8
)
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Modifications to the layout engine must not be performed from a background thread after it has been accessed from the main thread.'
*** First throw call stack:
(0x1cb160cb4 0x1c41f83d0 0x1e8631e68 0x1e8628994 0x1e86288c4 0x1e8628650 0x1cd1cbc60 0x1cd1ca420 0x1cc684f30 0x1cc6984ac 0x1cc6a98d8 0x1cc6d8e80 0x1cc6c2df0 0x1cb1e7234 0x1cb171410 0x1cb1d119c 0x1cb1d63ec 0x1031fc03c 0x1031fabe0 0x22af966b8 0x22af95b88)
libc++abi: terminating due to uncaught exception of type NSException
* thread #10, name = 'io.flutter.1.raster', stop reason = signal SIGABRT
    frame #0: 0x000000020a11d578 libsystem_kernel.dylib`__pthread_kill + 8
libsystem_kernel.dylib`:
->  0x20a11d578 <+8>:  b.lo   0x20a11d598               ; <+40>
    0x20a11d57c <+12>: pacibsp 
    0x20a11d580 <+16>: stp    x29, x30, [sp, #-0x10]!
    0x20a11d584 <+20>: mov    x29, sp
Target 0: (Runner) stopped.
Lost connection to device.
Failed to send request: {"jsonrpc":"2.0","id":"37","method":"getMemoryUsage","params":{"isolateId":"isolates/3239514502209099"}}
```

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Videos

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[!] Flutter (Channel stable, 3.13.0, on macOS 13.5.1 22G90 darwin-x64, locale en-US)
    • Flutter version 3.13.0 on channel stable at /Users/aidanlee/Developer/flutter
    ! Warning: `dart` on your path resolves to /usr/local/Cellar/dart/3.0.6/libexec/bin/dart, which is not inside your current Flutter SDK checkout at
      /Users/aidanlee/Developer/flutter. Consider adding /Users/aidanlee/Developer/flutter/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision efbf63d9c6 (3 weeks ago), 2023-08-15 21:05:06 -0500
    • Engine revision 1ac611c64e
    • Dart version 3.1.0
    • DevTools version 2.25.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/aidanlee/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /Users/aidanlee/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/221.6008.13.2211.9477386/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] Android Studio (version 2022.1)
    • Android Studio at /Users/aidanlee/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/221.6008.13.2211.9477386/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] Android Studio (version 2022.1)
    • Android Studio at /Users/aidanlee/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/221.6008.13.2211.9514443/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.3.2)
    • IntelliJ at /Users/aidanlee/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 75.1.2
    • Dart plugin version 223.8888

[✓] IntelliJ IDEA Ultimate Edition (version 2022.3.2)
    • IntelliJ at /Users/aidanlee/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/223.8617.56/IntelliJ IDEA.app
    • Flutter plugin version 71.3.6
    • Dart plugin version 223.8617.8

[✓] VS Code (version 1.67.2)
    • VS Code at /Users/aidanlee/Downloads/Visual Studio Code 2.app/Contents
    • Flutter extension version 3.60.0

[✓] VS Code (version 1.48.2)
    • VS Code at /Users/aidanlee/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.60.0

[✓] Connected device (4 available)
    • Aidan’s iPhone (mobile)    • 00008101-001C54A01A32001E            • ios            • iOS 16.6 20G75
    • iPhone 14 Pro Max (mobile) • ADF16D63-04AF-4B39-879C-63B60E4BB105 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)            • macos                                • darwin-x64     • macOS 13.5.1 22G90 darwin-x64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 116.0.5845.179

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

```

</details>

**Comment by stuartmorgan** [comment] 2023-09-07 16:49
Duplicate of https://github.com/flutter/flutter/issues/133847

**Closed by stuartmorgan** 2023-09-07 16:49 UTC
