### ISSUE TITLE
[tool_crash] HttpException

### ISSUE THREAD

**Issue by SVithushan** [flutter/flutter#158447] opened 2024-11-11 10:52 UTC
## Command
```
flutter run --machine --start-paused -d emulator-5554 --devtools-server-address http://127.0.0.1:9101/ --target /Users/sivaranjanvithushan/Dev(Flutter)/automynd-copilot/lib/main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
HttpException
```

```
```
[!] Flutter (Channel stable, 3.19.3, on macOS 14.7.1 23H222 darwin-arm64, locale en-US)
    • Flutter version 3.19.3 on channel stable at /Users/sivaranjanvithushan/fvm/versions/3.19.3
    ! Warning: `flutter` on your path resolves to /Users/sivaranjanvithushan/fvm/versions/3.24.4/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/sivaranjanvithushan/fvm/versions/3.19.3. Consider adding /Users/sivaranjanvithushan/fvm/versions/3.19.3/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /opt/homebrew/Cellar/dart/3.5.4/libexec/bin/dart, which is not inside your current Flutter SDK checkout at /Users/sivaranjanvithushan/fvm/versions/3.19.3. Consider adding /Users/sivaranjanvithushan/fvm/versions/3.19.3/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ba39319843 (8 months ago), 2024-03-07 15:22:21 -0600
    • Engine revision 2e4ba9c6fb
    • Dart version 3.3.1
    • DevTools version 2.31.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/sivaranjanvithushan/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/sivaranjanvithushan/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16B40
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)

[✓] VS Code (version 1.95.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.100.0

[✓] Connected device (4 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554             • android-arm64  • Android 15 (API 35) (emulator)
    • Vithushan’s iPad (mobile)   • 00008030-001564361450202E • ios            • iOS 17.6.1 21G93
    • macOS (desktop)             • macos                     • darwin-arm64   • macOS 14.7.1 23H222 darwin-arm64
    • Chrome (web)                • chrome                    • web-javascript • Google Chrome 130.0.6723.117

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.5+67
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 5dcb86f68f239346676ceb1ed1ea385bd215fba1
### Plugins
audio_session-0.1.19
audioplayers-6.0.0
audioplayers_android-5.0.0
audioplayers_darwin-6.0.0
audioplayers_linux-4.0.0
audioplayers_web-5.0.1
audioplayers_windows-4.0.0
azure_speech_recognition_null_safety-0.9.5
camera-0.11.0+2
camera_android_camerax-0.6.5+2
camera_avfoundation-0.9.17+3
camera_web-0.3.5
connectivity_plus-6.0.5
file_picker-8.0.0+1
file_selector_linux-0.9.2+1
file_selector_macos-0.9.4
file_selector_windows-0.9.3+2
firebase_analytics-10.10.5
firebase_analytics_web-0.5.7+5
firebase_auth-4.16.0
firebase_auth_web-5.8.13
firebase_core-2.31.0
firebase_core_web-2.17.5
firebase_messaging-14.7.10
firebase_messaging_web-3.5.18
flutter_background_service-2.4.6
flutter_background_service_android-3.0.3
flutter_background_service_ios-2.4.0
flutter_expandable_widget-1.0.5
flutter_local_notifications-13.0.0
flutter_pdfview-1.3.2
flutter_plugin_android_lifecycle-2.0.19
flutter_share-2.0.0
flutter_sound_lite-8.5.0
flutter_sound_web-8.5.0
flutter_svprogresshud-1.0.1
geocoding-2.2.2
geocoding_android-3.3.1
geocoding_ios-2.3.0
google_maps_flutter-2.2.8
google_maps_flutter_android-2.8.0
google_maps_flutter_ios-2.6.0
google_sign_in-6.2.1
google_sign_in_android-6.1.23
google_sign_in_ios-5.7.6
google_sign_in_web-0.12.4+2
image_picker-1.1.2
image_picker_android-0.8.12+1
image_picker_for_web-3.0.5
image_picker_ios-0.8.12
image_picker_linux-0.2.1+1
image_picker_macos-0.2.1+1
image_picker_windows-0.2.1+1
location-6.0.2
location_web-5.0.1
map_launcher-3.5.0
multi_image_picker_plus-0.0.5
package_info_plus-8.0.2
path_provider-2.1.3
path_provider_android-2.2.4
path_provider_foundation-2.4.0
path_provider_linux-2.2.1
path_provider_windows-2.2.1
permission_handler-11.3.1
permission_handler_android-12.0.6
permission_handler_apple-9.4.4
permission_handler_html-0.1.1
permission_handler_windows-0.2.1
record-5.0.5
record_android-1.1.0
record_darwin-1.0.1
record_linux-0.7.1
record_web-1.1.0
record_windows-1.0.2
share_plus-10.0.0
shared_preferences-2.2.3
shared_preferences_android-2.2.2
shared_preferences_foundation-2.4.0
shared_preferences_linux-2.3.2
shared_preferences_web-2.2.1
shared_preferences_windows-2.3.2
sign_in_with_apple-6.1.1
sign_in_with_apple_web-2.1.0
flutter-sound-stream-fd446a3953a506aa776a81f66ce2a04606f2be1e
speech_to_text-6.6.0
speech_to_text_macos-1.1.0
url_launcher-6.2.6
url_launcher_android-6.3.1
url_launcher_ios-6.3.0
url_launcher_linux-3.1.1
url_launcher_macos-3.2.0
url_launcher_web-2.3.3
url_launcher_windows-3.1.2
wakelock_plus-1.2.8

**Comment by danagbemava-nc** [comment] 2024-11-11 11:18
Closing this as a duplicate of https://github.com/flutter/flutter/issues/79748

**Closed by danagbemava-nc** 2024-11-11 11:18 UTC
Labels: in triage
