### ISSUE TITLE
tabbar inside scrollview

### ISSUE THREAD

**Issue by renanyoy** [flutter/flutter#106410] opened 2022-06-22 14:12 UTC
when using a trackpad to scroll a tabbar inside a scrollview the dominant scroll gesture isn't captured by the scrollview or the tabbar.
both vertical and horizontal scroll are active same time.
resulting in a clunky interface for the user.

https://user-images.githubusercontent.com/259671/175050735-22efa71e-762f-40b1-b49e-bbf5d9149924.mp4

```
[✓] Flutter (Channel stable, 3.0.2, on macOS 12.4 21F79 darwin-arm, locale
    en-FR)
    • Flutter version 3.0.2 at /Users/renanyoy/code/sdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cd41fdd495 (2 weeks ago), 2022-06-08 09:52:13 -0700
    • Engine revision f15f824b57
    • Dart version 2.17.3
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/renanyoy/Library/Android/sdk
    • Platform android-31, build-tools 29.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.68.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.42.0

[✓] Connected device (4 available)
    • Pixel 6 (mobile)     • 19291FDF60092F            • android-arm64  •
      Android 12 (API 32)
    • Renaniphone (mobile) • 00008020-000640992209002E • ios            • iOS
      15.5 19F77
    • macOS (desktop)      • macos                     • darwin-arm64   • macOS
      12.4 21F79 darwin-arm
    • Chrome (web)         • chrome                    • web-javascript • Google
      Chrome 102.0.5005.115
    ! Error: Bedroom is not connected. Xcode will continue when Bedroom is
      connected. (code -13)

[✓] HTTP Host Availability
    • All required HTTP hosts are available


• No issues found!
```

**Comment by huycozy** [comment] 2022-06-23 05:47
Hi @renanyoy, thanks for filing the issue. 
It seems you are running app on desktop environment. Could you tell me which platform are you reproducing this issue? (Web/MacOS/..)

And please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this. 
Thank you!

**Comment by renanyoy** [comment] 2022-06-23 09:43
it's flutter web

**Comment by huycozy** [comment] 2022-06-24 04:01
@renanyoy 
Please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this.

**Comment by renanyoy** [comment] 2022-06-24 04:15
you don't need. it It's all faked, i have made up all with my video edfitor.

**Comment by huycozy** [comment] 2022-06-27 05:19
@renanyoy 
We need a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) to be sure that Flutter is a problem or not.
And if the problem is with Flutter, we will look for similar/duplicated issues (they can be fixed by a workaround, fixed in a new version of Flutter, or maybe WIP).
So, please provide them to properly address the issue.

**Comment by huycozy** [comment] 2022-06-27 05:19
@renanyoy
We need a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) to be sure that Flutter is a problem or not.
And if the problem is with Flutter, we will look for similar/duplicated issues (they can be fixed by a workaround, fixed in a new version of Flutter, or maybe WIP).
So, please provide sample code to properly address the issue.

**Comment by renanyoy** [comment] 2022-07-18 07:13
I made my own custom tabview to fix it

**Comment by huycozy** [comment] 2022-07-18 12:09
Hi @renanyoy 
If you still encounter behavior that you believe could be a bug, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that represents the problem so that we can verify it. Thanks!

**Closed** 2022-08-08 12:11 UTC
Labels: waiting for customer response, in triage
