### ISSUE TITLE
由于 GIT 的 safe.directory 引发的 "Error: Unable to find git in your PATH." 错误。

### ISSUE THREAD

**Issue by tint** [flutter/flutter#119615] opened 2023-01-31 10:26 UTC
## Problem

![image](https://user-images.githubusercontent.com/46518383/215733154-1844bc4d-379a-4a8e-a811-24f55b4cdac5.png)

![image](https://user-images.githubusercontent.com/46518383/215733905-d73cc940-8610-4592-a5dd-c4ca721f0988.png)

## Resolve

![image](https://user-images.githubusercontent.com/46518383/215734485-6dcd43f8-0680-4164-8c68-3f96d8a02f4d.png)

**Comment by huycozy** [comment] 2023-02-01 05:17
@tint Did you add `C:\Windows\System32` to your PATH ? 

Also, you may try solutions mentioned in this issue if they're helpful: https://github.com/flutter/flutter/issues/15047

**Comment by tint** [comment] 2023-02-01 23:49
我的意思是，由于 git 的目录安全限制，导致 `git rev-parse HEAD` 运行失败，应该在检测前尝试执行 `git config --global add safe.directory /path/to/flutter-root` 确保 `git rev-parse HEAD` 能够正确运行。

**Comment by huycozy** [comment] 2023-02-02 04:05
@tint It works as expected from my end:

```
➜  flutter git:(stable) git rev-parse HEAD
b06b8b2710955028a6b562f5aa6fe62941d6febf
```

It seems the issue is caused by your permission setting (different user) from your end. Please double-check it and close the issue when it's solved.

**Comment by tint** [comment] 2023-02-02 14:46
@huycozy 我重新描述下我的问题：我已经安装了 Git 并且确保了它是可以正常运行的，但是由于 git 使用了 `safe.directory` 这个安全机制导致了检查 Git 失败，虽然我使用了 `fvm` 管理不同版本的 flutter（可能是 fvm 导致的），但是如果在 `flutter/bin/internal/shared.bat` 文件中，在验证 git 之前尝试执行 `git config --global --add safe.directory /path/to/flutter/root` 这条命令，就可以解决这条误报的错误。

**Comment by huycozy** [comment] 2023-02-03 04:24
_"Let me re-describe my problem: I have installed Git and ensured that it can run normally, but because git uses the safe.directory security mechanism, it fails to check Git, although I use fvm to manage different versions of flutter (It may be caused by fvm), but if in the flutter/bin/internal/shared.bat file, try to execute git config --global --add safe.directory /path/to/flutter/root before verifying git command, you can solve this false positive error."_ (Google translate)

I think the issue is related to your git configuration or fvm. Try pulling flutter elsewhere (don't use fvm) and try again.

**Closed** 2023-02-24 05:09 UTC
Labels: waiting for customer response, in triage
