### ISSUE TITLE
Bump the min-deployment-target on macOS desktop targets to 10.13

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#107492] opened 2022-07-12 20:25 UTC
This is blocking the roll of libcxx and libcxxabi to the the latest versions (without needing a fork). The guidance on the minimum deployment targets for desktop apps will need to be updated.

**Comment by chinmaygarde** [comment] 2022-07-12 20:26
cc @jason-simmons @cbracken @gspencergoog

**Comment by zanderso** [comment] 2022-07-14 22:29
cc @jmagman regarding comments about hardware requirements

**Comment by jmagman** [comment] 2022-07-14 22:46
This will drop support for hardware that cannot run past OS X El Capitan.

[macOS 10.12 Sierra](https://support.apple.com/kb/sp742?locale=en_US) needs to run on:
MacBook (Late 2009 or newer)
MacBook Pro (Mid 2010 or newer)
MacBook Air (Late 2010 or newer)
Mac mini (Mid 2010 or newer)
iMac (Late 2009 or newer)
Mac Pro (Mid 2010 or newer)

To compare, [OS X El Capitan](https://support.apple.com/kb/sp728?locale=en_US) runs on:
MacBook (Early 2015)
MacBook (Late 2008 Aluminum, or Early 2009 or newer)
MacBook Pro (Mid/Late 2007 or newer)
MacBook Air (Late 2008 or newer)
Mac mini (Early 2009 or newer)
iMac (Mid 2007 or newer)
Mac Pro (Early 2008 or newer)
Xserve (Early 2009)

FlutterMacOS.framework must be built with minimum version equal to or lower the version enforced by Flutter apps.  So this will require changes to the template for new apps, as well as a migration for existing apps.  Additionally, plugins also need to link against a version equal to or lower than what _they_ enforce.  

And we should update docs like https://docs.flutter.dev/deployment/macos#review-xcode-project-settings
> The minimum macOS version that your app supports. Flutter supports macOS 10.11 and later.

I recently did the tooling/buildroot/doc work for bumping iOS 11 at https://github.com/flutter/flutter/issues/101959.  Would be almost the same work to up the macOS version.

**Comment by jmagman** [comment] 2022-07-14 22:49
@stuartmorgan can you think of anything else to be concerned about?

**Comment by jmagman** [comment] 2022-07-14 22:53
Fortunately the [FlutterMacOS.framework Info.plist](https://github.com/flutter/engine/blob/2962099077b36704071802ea5595f4a016a1c214/shell/platform/darwin/macos/framework/Info.plist) doesn't have `MinimumOSVersion` to get mismatched. See https://github.com/flutter/engine/pull/28743 and app store submission error https://github.com/flutter/flutter/issues/90209 for why that mattered on iOS.

**Comment by jmagman** [comment] 2022-07-14 22:59
Additionally needs F@G team to make sure build rules are updated as needed cl/446325691

**Comment by jmagman** [comment] 2022-07-15 00:37
Actually, if we're going to do this, I recommend bumping to 10.13 High Sierra.  
There's a new Xcode 14 beta warning https://github.com/flutter/flutter/issues/107688 when the target is under 10.13.

> macos/Runner.xcodeproj warning build: The macOS deployment target 'MACOSX_DEPLOYMENT_TARGET' is set to 10.12, but the range of supported deployment target versions is 10.13 to 13.0.99.


The [hardware requirements](https://support.apple.com/kb/sp765?locale=en_US) are exactly the same as 10.12.

**Comment by stuartmorgan** [comment] 2022-07-15 12:39
> @stuartmorgan can you think of anything else to be concerned about?

No, your list sounds very thorough to me. It looks like this is about 1% of current macOS usage, which doesn't seem like a significant concern. (10.11 was originally picked because it was the earliest version that we could support without any additional eng cost, not for strategic reasons).

And if that Xcode warning means the native tooling won't actually build apps that support earlier versions, then it definitely makes sense to update our versions.

**Comment by jmagman** [comment] 2022-07-15 18:00
> Additionally needs F@G team to make sure build rules are updated as needed cl/446325691

Confirmed the internal default is already 10.13, so nothing extra to do there.

**Comment by jmagman** [comment] 2022-07-15 19:13
https://github.com/flutter/flutter/pull/107689 has merged, which should unblock bumping the buildroot `mac_deployment_target`. Filed https://github.com/flutter/flutter/issues/107741 ☂️  to track the rest of the work.

**Comment by jmagman** [comment] 2022-07-26 18:28
Done with https://github.com/flutter/buildroot/pull/588

**Closed by jmagman** 2022-07-26 18:28 UTC
Labels: platform-mac, a: desktop, P4
