### ISSUE TITLE
print truncates text after ~1000 characters

### ISSUE THREAD

**Issue by passsy** [flutter/flutter#65244] opened 2020-09-04 10:13 UTC
`print` truncates text after ~1000 characters. This makes it impossible to print long server responses.
It's not a Dart SDK problem but related to flutter. Using a pure dart program I can print as much as I want. 

## Steps to Reproduce

```dart
void main() {
  final StringBuffer sb = StringBuffer();
  for (var i = 0; i < 12; i++) {
    sb.write("$i\n".padLeft(100, "."));
  }
  print(sb.toString());

  runApp(MyApp());
}
```

**Expected results:**

```
..................................................................................................0
..................................................................................................1
..................................................................................................2
..................................................................................................3
..................................................................................................4
..................................................................................................5
..................................................................................................6
..................................................................................................7
..................................................................................................8
..................................................................................................9
.................................................................................................10
.................................................................................................11
```

**iOS Output:**

```
flutter: ..................................................................................................0
..................................................................................................1
..................................................................................................2
..................................................................................................3
..................................................................................................4
..................................................................................................5
..................................................................................................6
..................................................................................................7
..................................................................................................8
..................................................................................................9
<…>
```

**Android Output:**
```
I/flutter ( 4390): ..................................................................................................0
I/flutter ( 4390): ..................................................................................................1
I/flutter ( 4390): ..................................................................................................2
I/flutter ( 4390): ..................................................................................................3
I/flutter ( 4390): ..................................................................................................4
I/flutter ( 4390): ..................................................................................................5
I/flutter ( 4390): ..................................................................................................6
I/flutter ( 4390): ..................................................................................................7
I/flutter ( 4390): ..................................................................................................8
I/flutter ( 4390): ..................................................................................................9
I/flutter ( 4390): .......................
````

<details>
  <summary>flutter doctor</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 1.21.0-9.2.pre, on Mac OS X 10.15.6 19G2021, locale en-GB)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.6)
[✓] IntelliJ IDEA Ultimate Edition (version 2020.2.1)
[✓] VS Code (version 1.48.2)
[✓] Connected device (3 available)

• No issues found!

```

</details>

**Comment by pedromassangocode** [comment] 2020-09-04 11:59
I was able to reproduce this on latest `master` channel using `print()`.

You can work around this by `using debugPrint()`:

### iOS
```
Launching lib/main.dart on iPhone 11 Pro Max in debug mode...
flutter: ..................................................................................................0
flutter: ..................................................................................................1
flutter: ..................................................................................................2
flutter: ..................................................................................................3
flutter: ..................................................................................................4
flutter: ..................................................................................................5
flutter: ..................................................................................................6
flutter: ..................................................................................................7
flutter: ..................................................................................................8
flutter: ..................................................................................................9
flutter: .................................................................................................10
flutter: .................................................................................................11
flutter:
```

### Android
```
I/flutter ( 5668): ..................................................................................................0
I/flutter ( 5668): ..................................................................................................1
I/flutter ( 5668): ..................................................................................................2
I/flutter ( 5668): ..................................................................................................3
I/flutter ( 5668): ..................................................................................................4
I/flutter ( 5668): ..................................................................................................5
I/flutter ( 5668): ..................................................................................................6
I/flutter ( 5668): ..................................................................................................7
I/flutter ( 5668): ..................................................................................................8
I/flutter ( 5668): ..................................................................................................9
I/flutter ( 5668): .................................................................................................10
I/flutter ( 5668): .................................................................................................11
I/flutter ( 5668): 

```
<details><summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.22.0-10.0.pre.82, on Mac OS X 10.15.6 19G2021,
    locale en)
    • Flutter version 1.22.0-10.0.pre.82 at
      /Users/pedromassango/dev/SDKs/flutter_master
    • Framework revision 9248fda410 (13 hours ago), 2020-09-03 16:08:01 -0700
    • Engine revision 3f05b521b9
    • Dart version 2.10.0 (build 2.10.0-86.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.7, Build version 11E801a
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2020.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 48.1.4
    • Dart plugin version 202.7206

[✓] VS Code (version 1.48.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[✓] Connected device (5 available)
    • sdk gphone x86 arm (mobile) • emulator-5554                        •
      android-x86    • Android 11 (API 30) (emulator)
    • iPhone 11 Pro Max (mobile)  • 3DA251B5-C982-48C8-8FF5-C4D1DB21ED89 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-13-7 (simulator)
    • macOS (desktop)             • macos                                •
      darwin-x64     • Mac OS X 10.15.6 19G2021
    • Web Server (web)            • web-server                           •
      web-javascript • Flutter Tools
    • Chrome (web)                • chrome                               •
      web-javascript • Google Chrome 85.0.4183.83

! Doctor found issues in 1 category.
```
</details>

**Comment by pedromassangocode** [comment] 2020-09-04 12:10
It turns out that this is by design and not an issue with Flutter. Please see https://github.com/flutter/flutter/issues/22665#issuecomment-584914616

Closing as working as intended. If you disagree please write in the comments bellow and I will reopen it.
Thank you

**Closed by pedromassangocode** 2020-09-04 12:10 UTC
