### ISSUE TITLE
[Proposal] Cache more Dart version at least for `channel beta`, `channel stable` , so that working on both `stable` and `beta` become more smooth to switch flutter channels if network is not so good

### ISSUE THREAD

**Issue by jerryzhoujw** [flutter/flutter#49055] opened 2020-01-17 14:51 UTC
I was develop on `stable` for mobile and on `beta` for web experiment.

When I switch channels between `stable` and `beta`, it's always download Dart SDK,

I know it's needed since [#2055](https://github.com/flutter/flutter/issues/2055#issuecomment-336937998).

But I still get some problem [#49050](https://github.com/flutter/flutter/issues/49050)

How to trigger the download again ?

I think if `flutter/bin/cache`  can manager more  Dart SDK, like include at least  versions for `flutter stable` & `flutter beta`.

It's benefit who have slow network.

Or if the dart cache part managed use `git` just what flutter SDK do would be good too, because I can see the git status by myself which give me more information of the status.

**Comment by VladyslavBondarenko** [comment] 2020-01-17 15:25
Related to https://github.com/flutter/flutter/issues/24236

**Comment by jerryzhoujw** [comment] 2020-01-18 04:32
Temp solution for me to change channel  without fetch remote source now:

### Prepare resources for channels of `stable` and `beta`: (assume you are on channel stable now)

1. `cd [your Flutter SDK folder]`
2. zip folder `flutter/bin/cache` to `cache-stable.zip`
3. `git checkout beta`
4.  do normal workflow:  `flutter channel beta` & `flutter doctor -v`
5. zip folder `flutter/bin/cache` to `cache-beta.zip`

### switch channel after prepared resources:

1. `cd [your Flutter SDK folder]`
2. `git checkout [beta|stable]`
3.  remove `flutter/bin/cache` & unzip `cache-[beta|stable].zip`
4. `flutter doctor -v`

**Comment by christopherfujino** [comment] 2020-01-24 19:24
Thanks for the idea! I'm closing this as a duplicate of https://github.com/flutter/flutter/issues/44212, please follow there for further discussion.

**Closed by christopherfujino** 2020-01-24 19:24 UTC
Labels: framework, severe: new feature, tool
