### ISSUE TITLE
Flutter Web: onKey method is not being called on FocusNode when enter key is pressed.

### ISSUE THREAD

**Issue by BirjuVachhani** [flutter/flutter#89580] opened 2021-09-07 11:38 UTC
My use-case involves custom control on when a field is submitted. For this example let's say when `enter` key is pressed for the first time, it should be counted as **field submitted**. For this, I am using a focus on `TextField` to listen to key events and consuming enter key event for the first time and pass it through for the second time. This works well on desktop but is not working on Web.

## Steps to Reproduce

1. Run in a `MaterialApp`.
2. Click on `TextField`.
3. Type something and hit `ENTER` key.

<details><summary>code sample</summary>

```dart
class MyTextField extends StatefulWidget {
  @override
  _MyTextFieldState createState() => _MyTextFieldState();
}

class _MyTextFieldState extends State<MyTextField> {
  final TextEditingController controller = TextEditingController();
  final FocusNode focusNode = FocusNode();

  bool shouldSubmit = false;
  FocusAttachment? attachment;

  @override
  void initState() {
    super.initState();
    attachment = focusNode.attach(context, onKey: onKey);
  }

  KeyEventResult onKey(FocusNode node, RawKeyEvent event) {
    if (event.isKeyPressed(LogicalKeyboardKey.enter) && !shouldSubmit) {
      print('onKey: enter key pressed');
      shouldSubmit = true;
      return KeyEventResult.handled;
    }

    return KeyEventResult.ignored;
  }

  @override
  Widget build(BuildContext context) {
    return TextFormField(
      controller: controller,
      focusNode: focusNode,
    );
  }

  @override
  void dispose() {
    attachment?.detach();
    focusNode.dispose();
    controller.dispose();
    super.dispose();
  }
}
```

 </details>

**Expected results:**
- Field should not be submitted.
- `onKey` should be called and key pressed log should be printed in console.

**Actual results:**
- Field is getting submitted.
- `onKey` is not being called.

<details>
<summary>Logs</summary>

```
[ +105 ms] executing: [C:\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +171 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] f4abaa0735eba4dfd8f33f73363911d63931fe03
[   +1 ms] executing: [C:\flutter/] git tag --points-at f4abaa0735eba4dfd8f33f73363911d63931fe03
[  +69 ms] Exit code 0 from: git tag --points-at f4abaa0735eba4dfd8f33f73363911d63931fe03
[        ] 2.2.3
[   +8 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +63 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\flutter/] git ls-remote --get-url origin
[  +54 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +198 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref HEAD
[  +63 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[ +131 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +5 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +104 ms] executing: C:\Users\brvac\AppData\Local\Android\Sdk\platform-tools\adb.exe devices -l
[  +71 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +106 ms] executing: C:\Users\brvac\AppData\Local\Android\Sdk\platform-tools\adb.exe devices -l
[  +15 ms] Skipping pub get: version match.
[ +210 ms] Generating C:\Users\brvac\IdeaProjects\textfield_test\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[ +127 ms] List of devices attached
[  +59 ms] List of devices attached
[  +85 ms] Launching lib\main.dart on Chrome in debug mode...
[ +194 ms] Updating assets
Waiting for connection from debug service on Chrome...
[ +295 ms] <- reset
[  +13 ms] C:\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev C:\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root C:\flutter\bin\cache\flutter_web_sdk/ --incremental --target=dartdevc --debugger-module-names --experimental-emit-debug-metadata -Dflutter.inspector.structuredErrors=true -DFLUTTER_WEB_AUTO_DETECT=true --output-dill C:\Users\brvac\AppData\Local\Temp\flutter_tools.d928b74d\flutter_tool.b6fa8f39\app.dill --libraries-spec file:///C:/flutter/bin/cache/flutter_web_sdk/libraries.json --packages C:\Users\brvac\IdeaProjects\textfield_test\.dart_tool\package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-root C:\Users\brvac\AppData\Local\Temp\flutter_tools.d928b74d\flutter_tools.86ad5b28 --filesystem-scheme org-dartlang-app --initialize-from-dill build\9da3ff2a5297e0c47025236ff84e71f4.cache.dill.track.dill --platform file:///C:/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk_sound.dill --sound-null-safety
[   +9 ms] <- compile org-dartlang-app:/web_entrypoint.dart
[+28020 ms] Synced 28.2MB.
[   +1 ms] <- accept
[        ] Caching compiled dill
[ +360 ms] [CHROME]:[9452:13864:0907/165911.156:ERROR:os_crypt_win.cc(93)] Failed to decrypt: The parameter is incorrect. (0x57)
[   +1 ms] [CHROME]:[9452:13864:0907/165911.156:ERROR:brave_sync_prefs.cc(114)] Decrypt sync seed failure
[  +34 ms] [CHROME]:
[        ] [CHROME]:DevTools listening on ws://127.0.0.1:49174/devtools/browser/e1cb4d5f-466c-4f21-a6c4-67f95f4d8308
[+1467 ms] DwdsInjector: Received request for entrypoint at http://localhost:49156/main_module.bootstrap.js
[  +11 ms] MetadataProvider: Loading debug metadata...
[  +26 ms] MetadataProvider: Loaded debug metadata (sound null safety)
[  +15 ms] DwdsInjector: Injected debugging metadata for entrypoint at http://localhost:49156/main_module.bootstrap.js
[+5813 ms] ChromeProxyService: Initializing expression compiler for main_module.bootstrap.js with sound null safety: true
[ +149 ms] DevHandler: Debug service listening on ws://127.0.0.1:52436/HI_SROYcfD0=/ws

[  +47 ms] This app is linked to the debug service: ws://127.0.0.1:52436/HI_SROYcfD0=/ws
[  +12 ms] Debug service listening on ws://127.0.0.1:52436/HI_SROYcfD0=/ws
[   +1 ms]  Running with sound null safety 
Debug service listening on ws://127.0.0.1:52436/HI_SROYcfD0=/ws
[+12558 ms] onKey: onKey called: D
[  +48 ms] onKey: onKey called: D
[ +162 ms] onKey: onKey called: A
[ +114 ms] onKey: onKey called: A
[ +266 ms] onKey: onKey called: R
[  +69 ms] onKey: onKey called: R
[ +135 ms] onKey: onKey called: T
[  +69 ms] onKey: onKey called: T
[+1732 ms] field submitted
```
</details>
<details>
<summary>Flutter Analyzer</summary>

```
Analyzing textfield_test...
No issues found! (ran in 3.3s)
```
</details>

<details>
<summary>Flutter Doctor</summary>

```
[√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.19043.1165], locale en-IN)
    • Flutter version 2.2.3 at C:\flutter
    • Framework revision f4abaa0735 (10 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\brvac\AppData\Local\Android\Sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = C:\Users\brvac\AppData\Local\Android\Sdk
    • ANDROID_SDK_ROOT = C:\Users\brvac\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Chrome - develop for the web
    • CHROME_EXECUTABLE = C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.10.3)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.10.31424.327
    • Windows 10 SDK version 10.0.19041.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] IntelliJ IDEA Ultimate Edition (version 2021.2)
    • IntelliJ at C:\Users\brvac\AppData\Local\JetBrains\IntelliJ IDEA 2021.1.3
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[√] VS Code (version 1.59.1)
    • VS Code at C:\Users\brvac\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.25.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19043.1165]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 92.0.4515.107
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 93.0.961.38

! Doctor found issues in 2 categories.

```
</details>

**Comment by TahaTesser** [comment] 2021-09-07 12:06
Hi @BirjuVachhani 
This is not specific to web

I see there's an open issue addressing the case you described.
Please follow up on that issue, Closing as duplicate of https://github.com/flutter/flutter/issues/83023
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-09-07 12:06 UTC
Labels: in triage

**Comment by BirjuVachhani** [comment] 2021-09-07 12:25
@TahaTesser But in my case, `onKey` is being called on web as well and everything seems to be working fine. Only the enter key event is not being intercepted (mostly because of field submission I guess). Are you sure it is the same thing?

**Comment by TahaTesser** [comment] 2021-09-07 12:38
@BirjuVachhani 
Interesting, That would be a duplicate of this https://github.com/flutter/flutter/issues/65170, It works on desktop, matches https://github.com/flutter/flutter/issues/65170#issuecomment-686458514 results

```console
[+1886 ms] flutter: RawKeyDownEvent#3263c(logicalKey: LogicalKeyboardKey#0000d(keyId: "0x10000000d", keyLabel: "Enter",
debugName: "Enter"), physicalKey: PhysicalKeyboardKey#70028(usbHidUsage: "0x00070028", debugName: "Enter"))
[+1186 ms] flutter: RawKeyDownEvent#082c3(logicalKey: LogicalKeyboardKey#0000d(keyId: "0x10000000d", keyLabel: "Enter",
debugName: "Enter"), physicalKey: PhysicalKeyboardKey#70028(usbHidUsage: "0x00070028", debugName: "Enter"))
```

**Comment by BirjuVachhani** [comment] 2021-09-07 12:55
@TahaTesser 

Seems similar. However the case with #65170 seems to be that the key event is being consumed by the focus node of the text field and is not propagated above the tree to other focus nodes. But in this case, a callback is attached to the same focus node used on the text field. So there is no propagation above the tree I guess? Though not 100% sure if it is different from #65170.

**Comment by TahaTesser** [comment] 2021-09-07 13:01
@BirjuVachhani 
Using your code reproduces the same way, I have updated the issue https://github.com/flutter/flutter/issues/65170 and cc someone. Real cause would be investigated when someone files a PR

**Comment by BirjuVachhani** [comment] 2021-09-07 13:33
Alright! Thank you 👍🏻
