### ISSUE TITLE
Incorrect page offset after orientation change because of RangeMaintainingScrollPhysics

### ISSUE THREAD

**Issue by pjiang-google** [flutter/flutter#62161] opened 2020-07-23 21:43 UTC
## Steps to Reproduce

On Android,
1. Use the PageView (or TabBarView) widget, with horizontal axis and two pages.
2. Scroll to the second page.
3. Change the orientation from portrait to landscape.

(I can provide an internal repro case.)

**Expected results:** 

The second page is displayed properly.

**Actual results:** 

The offset of the second page is incorrect. Along the horizontal axis, the center of the second page is not at the center of the screen.

**Detail:**

 This [PR](https://github.com/flutter/flutter/commit/98bc1766273fcdcf02f22f0bb193266b8c50145d) added RangeMaintainingScrollPhysics to address out of bound issues. However, RangeMaintainingScrollPhysics seems to introduce unexpected behavior when the orientation changes. To elaborate, when the orientation changes from portrait to landscape, [_PagePosition.applyViewportDimension](https://github.com/flutter/flutter/blob/8e58c51d1a9b583b56c2ea9631625d73d3610c06/packages/flutter/lib/src/widgets/page_view.dart#L396) will update viewport dimensions and offset (pixels). The updated offset could be larger than the old boundary, as now the screen width is much larger.

However, the subsequent call to [applyContentDimensions](https://github.com/flutter/flutter/blob/4d7525f05c05a6df0b29396bc9eb78c3bf1e9f89/packages/flutter/lib/src/widgets/scroll_position.dart#L485) will check if the (updated) offset is within bounds and RangeMaintainingScrollPhysics incorrectly [considers the current offset out of bound](https://github.com/flutter/flutter/blob/4d7525f05c05a6df0b29396bc9eb78c3bf1e9f89/packages/flutter/lib/src/widgets/scroll_physics.dart#L425), as the updated offset has become larger than maxScrollExtent, so the offset will be [updated again](https://github.com/flutter/flutter/blob/4d7525f05c05a6df0b29396bc9eb78c3bf1e9f89/packages/flutter/lib/src/widgets/scroll_position.dart#L529).

This is the consequence of a two-stage update, where the offset and viewport dimensions are updated in applyViewportDimension and min/maxScrollExtent are updated in  applyContentDimensions, but applyContentDimensions isn’t aware of the change in the former.

One possible solution is marking hasDimensions as false when the viewport dimensions change in [applyViewportDimension](https://github.com/flutter/flutter/blob/4d7525f05c05a6df0b29396bc9eb78c3bf1e9f89/packages/flutter/lib/src/widgets/scroll_position.dart#L424), but I’m not sure if there’s any unwanted consequence, even though this “fixes” the issue for my particular case.

**Comment by darshankawar** [comment] 2020-07-24 08:34
Hi @pjiang-google,
Can you please provide `flutter doctor -v` and a minimal complete reproducible code sample that shows the issue ?
A video or gif showing the issue will help as well.
Thanks.

**Comment by jason-simmons** [comment] 2020-07-24 18:47
See https://github.com/flutter/flutter/issues/60288

**Comment by pjiang-google** [comment] 2020-07-24 19:04
Thanks, Jason. Yes, that's the same issue. Please feel free to mark this as duplicate.

**Comment by darshankawar** [comment] 2020-07-27 05:47
Hi @pjiang-google,
Closing this as duplicate of [60288](https://github.com/flutter/flutter/issues/60288).

**Closed by darshankawar** 2020-07-27 05:47 UTC
Labels: in triage
