### ISSUE TITLE
Hot Reload / Reload Causing Web app to freeze - Flutter Version 1.20.0

### ISSUE THREAD

**Issue by kaumudpa** [flutter/flutter#63081] opened 2020-08-06 13:05 UTC
The current stable release of Flutter - 1.20.0 has a major issue, Hot Reload / Reload is causing web app to Freeze on the browser.

To Reproduce:
1. Create a blank Flutter App.
2. Run it on web : `flutter run -d chrome`
3. Increase the counter of the flutter app in chrome.
4. And then do a hot reload / reload.

The console will show that the app is reloaded but the app will be freezed on the browser.

My Config:
```
[✓] Flutter (Channel unknown, 1.20.0, on Mac OS X 10.15.6 19G73, locale en-IN)
    • Flutter version 1.20.0 at /Users/kap/flutter
    • Framework revision 840c9205b3 (33 hours ago), 2020-08-04 20:55:12 -0700
    • Engine revision c8e3b94853
    • Dart version 2.9.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/kap/Library/Android/sdk
    • Platform android-30, build-tools 28.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[✓] Connected device (2 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 84.0.4147.105

• No issues found!
```

**Comment by pedromassangocode** [comment] 2020-08-06 13:28
Hi @kaumudpa 
I'm not sure if you mention the right Flutter channel, in the latest stable we're not able to enable Flutter web as you can see in the image bellow, it is `Unavailable`. Did you mean another Flutter channel?

![Screen Shot 2020-08-06 at 14 24 51](https://user-images.githubusercontent.com/67424416/89536998-9af39900-d7f0-11ea-8bd5-734833ab9ff6.png)


<details>
<summary> flutter config</summary>

```
sh-3.2$ flutter config
Configure Flutter settings.

To remove a setting, configure it to an empty string.

The Flutter tool anonymously reports feature usage statistics and basic crash reports to help improve Flutter tools over time. See Google's
privacy policy: https://www.google.com/intl/en/policies/privacy/

Global options:
-h, --help                  Print this usage information.
-v, --verbose               Noisy logging, including all shell commands executed.
                            If used with --help, shows hidden options.
-d, --device-id             Target device id or name (prefixes allowed).
    --version               Reports the version of this tool.
    --suppress-analytics    Suppress analytics reporting when this command runs.

Usage: flutter config [arguments]
-h, --help                                Print this usage information.
    --[no-]analytics                      Enable or disable reporting anonymously tool usage statistics and crash reports.
    --clear-ios-signing-cert              Clear the saved development certificate choice used to sign apps for iOS device deployment.
    --android-sdk                         The Android SDK directory.
    --android-studio-dir                  The Android Studio install directory.
    --build-dir=<out/>                    The relative path to override a projects build directory
    --[no-]enable-web                     Enable or disable Flutter for web. This setting will take effect on the master, dev, and beta
                                          channels.
    --[no-]enable-linux-desktop           Enable or disable Flutter for desktop on Linux. This setting will take effect on the master and dev
                                          channels.
    --[no-]enable-macos-desktop           Enable or disable Flutter for desktop on macOS. This setting will take effect on the master and dev
                                          channels.
    --[no-]enable-windows-desktop         Enable or disable Flutter for desktop on Windows. This setting will take effect on the master
                                          channel.
    --[no-]enable-android-embedding-v2    Enable or disable flutter create generates projects using the Android embedding V2. This setting
                                          will take effect on the master, dev, beta, and stable channels.
    --clear-features                      Remove all configured features and restore them to the default values.

Run "flutter help" to see global options.

Settings:
  enable-web: true (Unavailable)
  enable-macos-desktop: true (Unavailable)
  enable-windows-desktop: true (Unavailable)

Analytics reporting is currently enabled.
sh-3.2$ 

```
</details>

**Comment by arjendevos** [comment] 2020-08-06 13:35
Same problem here. When i hot restart, the page stays loading and doesn't load.

`(This is taking an unexpectedly long time.)   `

**Comment by kaumudpa** [comment] 2020-08-06 13:43
I am on a detached HEAD - Using flutter 1.20.0 Without being on any channel which is exactly similar to be on the stable channel.

You can be on the detached state by following command.

`flutter version 1.20.0`

**Comment by kaumudpa** [comment] 2020-08-06 13:43
I am on a detached HEAD - Using flutter 1.20.0 Without being on any channel which is exactly similar to be on the stable channel.

You can be on the detached state by following command.

flutter version 1.20.0

**Comment by kaumudpa** [comment] 2020-08-06 15:14
App freezes in chrome with this output in `verbose` while trying to hot reload:

```
[ +332 ms] Debug service listening on ws://127.0.0.1:52765/bGRVkXrDXVY=
[   +6 ms] Warning: Flutter's support for web development is not stable yet and hasn't
[   +2 ms] been thoroughly tested in production environments.
[        ] For more information see https://flutter.dev/web
[        ] 🔥  To hot restart changes while running, press "r" or "R".
[   +2 ms] For a more detailed help message, press "h". To quit, press "q".
[+11711 ms] Performing hot restart...
[   +8 ms] Starting incremental build...
[   +2 ms] Initializing file store
[  +13 ms] Skipping target: gen_localizations
[   +3 ms] complete
[   +6 ms] Scanned through 480 files in 5ms
[        ] Syncing files to device Chrome...
[   +1 ms] <- recompile org-dartlang-app:/web_entrypoint.dart 8d2e7d66-e0ce-4708-9c60-9b650e3dea32
[        ] <- 8d2e7d66-e0ce-4708-9c60-9b650e3dea32
[  +11 ms] Syncing files to device Chrome... (completed in 13ms)
[        ] Synced 0.0MB.
[   +3 ms] <- accept
[  +67 ms] Performing hot restart... (completed in 122ms)
[        ] Restarted application in 122ms.
```

**Comment by pedromassangocode** [comment] 2020-08-10 11:16
Hi @kaumudpa 
I can't reproduce this issue on current `master`, `beta` channel.
Can you please switch to `beta` and try again
`flutter channel beta`
`flutter upgrade --force`
`flutter doctor -v`

<details>
<summary> sample code</summary>

```
import 'package:flutter/material.dart';

void main() {
  return runApp(MaterialApp(
    home: Home(),
  ));
}

class Home extends StatefulWidget {
  @override
  _HomeState createState() => _HomeState();
}

class _HomeState extends State<Home> {
  int counter = 0;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Text('Counter $counter'),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {
          setState(() => counter += 1);
        },
      ),
    );
  }
}
```
</details>

<details>
<summary> flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.21.0-8.0.pre.122, on Mac OS X 10.15.6 19G73,
    locale en)
    • Flutter version 1.21.0-8.0.pre.122 at
      /Users/pedromassango/dev/SDKs/flutter_master
    • Framework revision 7c6f9dd239 (20 hours ago), 2020-08-09 10:31:03 -0400
    • Engine revision 6d86e67f04
    • Dart version 2.10.0 (build 2.10.0-4.0.dev 0341576448)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

 
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2020.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 48.0.4
    • Dart plugin version 202.6397.47

[✓] Connected device (4 available)
    • iPhone SE (2nd generation) (mobile) • 1119074E-0493-4533-9212-6758A33EB40C
      • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-6 (simulator)
    • macOS (desktop)                     • macos
      • darwin-x64     • Mac OS X 10.15.6 19G73
    • Web Server (web)                    • web-server
      • web-javascript • Flutter Tools
    • Chrome (web)                        • chrome
      • web-javascript • Google Chrome 84.0.4147.105

! Doctor found issues in 2 categories.
```
</details>

**Comment by kaumudpa** [comment] 2020-08-11 06:40
I switched to beta as per your instructions but the problem still persists on the beta channel, But the problem is not seen on the dev channel.

**Comment by TahaTesser** [comment] 2020-08-11 07:36
Hi @kaumudpa 
As the issue is no longer reproducible on dev channel, please switch to dev channel until fix is landed on beta channel 

given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you

**Closed by TahaTesser** 2020-08-11 07:36 UTC
Labels: in triage

**Comment by kaumudpa** [comment] 2020-08-11 07:41
I would request you to check this issue on the beta channel as it affects development of working flutter web apps on the stable channel also.

**Comment by TahaTesser** [comment] 2020-08-11 14:08
@kaumudpa 
As you confirmed, this looks to be working in `dev` channel and those fixes will trickle down to beta and stable
