### ISSUE TITLE
App Crash in Production - java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by abu0435** [flutter/flutter#76780] opened 2021-02-25 11:11 UTC
In my Flutter app, only Android 10 (SDK 29) got some crash report. I have used following plugin '''

firebase_analytics: ^6.3.0
firebase_auth_web: ^0.3.2
firebase_core_platform_interface: ^2.0.0
firebase_core: ^0.5.3
firebase_auth_oauth: ^0.2.2
firebase_auth_oauth_web: ^0.2.1
firebase_storage: ^5.0.1

In debug build, i didn't get any crash. In Play console i got crash from Android 10 (SDK 29)

```
java.lang.RuntimeException: 
  at android.app.ActivityThread.handleCreateService (ActivityThread.java:4412)
  at android.app.ActivityThread.access$1700 (ActivityThread.java:274)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2118)
  at android.os.Handler.dispatchMessage (Handler.java:107)
  at android.os.Looper.loop (Looper.java:237)
  at android.app.ActivityThread.main (ActivityThread.java:8167)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:496)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1100)
Caused by: java.lang.RuntimeException: 
  at io.flutter.embedding.engine.loader.FlutterLoader.ensureInitializationComplete (FlutterLoader.java:282)
  at io.flutter.view.FlutterMain.ensureInitializationComplete (FlutterMain.java:8)
  at io.flutter.plugins.firebasemessaging.FlutterFirebaseMessagingService.onCreate (FlutterFirebaseMessagingService.java:10)
  at android.app.ActivityThread.handleCreateService (ActivityThread.java:4400)
  at android.app.ActivityThread.access$1700 (ActivityThread.java:274)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2118)
  at android.os.Handler.dispatchMessage (Handler.java:107)
  at android.os.Looper.loop (Looper.java:237)
  at android.app.ActivityThread.main (ActivityThread.java:8167)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:496)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1100)
Caused by: java.util.concurrent.ExecutionException: 
  at java.util.concurrent.FutureTask.report (FutureTask.java:123)
  at java.util.concurrent.FutureTask.get (FutureTask.java:193)
  at io.flutter.embedding.engine.loader.FlutterLoader.ensureInitializationComplete (FlutterLoader.java:23)
  at io.flutter.view.FlutterMain.ensureInitializationComplete (FlutterMain.java:8)
  at io.flutter.plugins.firebasemessaging.FlutterFirebaseMessagingService.onCreate (FlutterFirebaseMessagingService.java:10)
  at android.app.ActivityThread.handleCreateService (ActivityThread.java:4400)
  at android.app.ActivityThread.access$1700 (ActivityThread.java:274)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2118)
  at android.os.Handler.dispatchMessage (Handler.java:107)
  at android.os.Looper.loop (Looper.java:237)
  at android.app.ActivityThread.main (ActivityThread.java:8167)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:496)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1100)
Caused by: java.lang.UnsatisfiedLinkError: 
  at java.lang.Runtime.loadLibrary0 (Runtime.java:1067)
  at java.lang.Runtime.loadLibrary0 (Runtime.java:1007)
  at java.lang.System.loadLibrary (System.java:1667)
  at io.flutter.embedding.engine.loader.FlutterLoader$1.call (FlutterLoader.java:20)
  at io.flutter.embedding.engine.loader.FlutterLoader$1.call (FlutterLoader.java)
  at java.util.concurrent.FutureTask.run (FutureTask.java:266)
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1167)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:641)
  at java.lang.Thread.run (Thread.java:919)
```

<details>
  <summary>Flutter doctor</summary>

```
[√] Flutter (Channel stable, 1.22.3, on Microsoft Windows [Version 10.0.19041.804], locale en-US)
    • Flutter version 1.22.3 at C:\src\flutter
    • Framework revision 8874f21e79 (4 months ago), 2020-10-29 14:14:35 -0700
    • Engine revision a1440ca392
    • Dart version 2.10.3

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\ABC\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = C:\Users\Abdulkadhar\AppData\Local\Android\sdk
    • Java binary at: C:\Program Files\Android\Android Studio1\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[!] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 44.0.1
    • Dart plugin version 191.8593
    X Unable to determine bundled Java version.
    • Try updating or re-installing Android Studio.

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio1
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (1 available)
    • EVA L19 (mobile) • XVV7N17330002694 • android-arm64 • Android 7.0 (API 24)

! Doctor found issues in 3 categories.
```

</details>

**Comment by iapicca** [comment] 2021-02-25 12:30
self duplicate of https://github.com/flutter/flutter/issues/76781

**Comment by darshankawar** [comment] 2021-02-25 13:02
@abu0435 
Considering 76781 is also similar as this, I am closing this in favor of 76781.

**Closed by darshankawar** 2021-02-25 13:02 UTC
Labels: in triage
