### ISSUE TITLE
Flutter 2 - Desktop - devices access support

### ISSUE THREAD

**Issue by gpelizzo** [flutter/flutter#78704] opened 2021-03-20 18:26 UTC
Hi, 

Flutter 2 looks great. Supporting desktop development is real benefit.
But having a desktop app not able to communicate with connected devices is just very frustrating.

Let's just talk about Serial Port. There is no way to consider a cross development. The only package I found out is flutter_serial_port but it's very unstable.

I'm expecting that very soon, some packages will be available.

Regards

**Comment by stuartmorgan** [comment] 2021-03-20 19:00
Duplicate of https://github.com/flutter/flutter/issues/77741

**Closed by stuartmorgan** 2021-03-20 19:00 UTC
