### ISSUE TITLE
Error at the end of build in xcod

### ISSUE THREAD

**Issue by NightOrion** [flutter/flutter#29529] opened 2019-03-18 04:06 UTC
at the end of build a have this error

## exception
RangeError: RangeError (index): Invalid value: Only valid value is 0: 1

[flutter_01.log](https://github.com/flutter/flutter/files/2976331/flutter_01.log)
![pic3234](https://user-images.githubusercontent.com/1979532/54506184-e1332880-496d-11e9-9faf-98f367a7adee.jpg)

**Comment by jonahwilliams** [comment] 2019-03-18 04:35
Duplicate of https://github.com/flutter/flutter/issues/29486

**Closed by jonahwilliams** 2019-03-18 04:35 UTC
