### ISSUE TITLE
when I am using firebase firestore in the flutter web it shows me an error.

### ISSUE THREAD

**Issue by lkrjangid1** [flutter/flutter#74585] opened 2021-01-24 10:43 UTC
when I am using firebase firestore in the flutter web it shows me an error.

`FirebaseError: Firebase: Firebase App named '[DEFAULT]' already exists (app/duplicate-app).
Error: Failed assertion: boolean expression must not be null
    at Object.throw_ [as throw] (http://localhost:62696/dart_sdk.js:4361:11)
    at Object.test (http://localhost:62696/dart_sdk.js:4651:32)
    at Object.dtest (http://localhost:62696/dart_sdk.js:4656:55)
    at main$ (http://localhost:62696/packages/flutter_appfirebase/main.dart.lib.js:375:17)
    at main$.next (<anonymous>)
    at runBody (http://localhost:62696/dart_sdk.js:38027:34)
    at Object._async [as async] (http://localhost:62696/dart_sdk.js:38058:7)
    at main$ (http://localhost:62696/packages/flutter_appfirebase/main.dart.lib.js:374:18)
    at main (http://localhost:62696/web_entrypoint.dart.lib.js:35:27)
    at main.next (<anonymous>)
    at http://localhost:62696/dart_sdk.js:38007:33
    at _RootZone.runUnary (http://localhost:62696/dart_sdk.js:37861:58)
    at _FutureListener.thenAwait.handleValue (http://localhost:62696/dart_sdk.js:32822:29)
    at handleValueCallback (http://localhost:62696/dart_sdk.js:33370:49)
    at Function._propagateToListeners (http://localhost:62696/dart_sdk.js:33408:17)
    at async._AsyncCallbackEntry.new.callback (http://localhost:62696/dart_sdk.js:33133:27)
    at Object._microtaskLoop (http://localhost:62696/dart_sdk.js:38122:13)
    at _startMicrotaskLoop (http://localhost:62696/dart_sdk.js:38128:13)
    at http://localhost:62696/dart_sdk.js:33625:9`

**Comment by iapicca** [comment] 2021-01-24 12:19
@lkrjangid1

**Comment by pedromassangocode** [comment] 2021-01-25 14:23
Hi @lkrjangid1 
From what I can see, the issue is related to a FlutterFire plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by pedromassangocode** 2021-01-25 14:23 UTC
Labels: created via performance template
