### ISSUE TITLE
"flutter get packages" stuck waiting for another flutter command to release the startup lock

### ISSUE THREAD

**Issue by michaelodafe** [flutter/flutter#40570] opened 2019-09-16 09:48 UTC
This is the error below.. Please help me with a fix

```
C:\android\flutter\bin\flutter.bat --no-color packages get
Waiting for another flutter command to release the startup lock...
```

**Comment by BondarenkoStas** [comment] 2019-09-16 13:26
@michaelodafe Please try ```taskkill /F /IM dart.exe```.
Also please try to delete ```C:\android\flutter\bin\cache\lockfile
Seems to be #17422.
If that will not help, please attach your ```flutter doctor -v``` output.

**Comment by michaelodafe** [comment] 2019-09-16 13:38
Just did that, Thank you. But it was stocked on this message below
C:\android\flutter\bin\flutter.bat --no-color packages get
Running "flutter pub get" in bmi-calculator-flutter...  


Below is my flutter doctor
C:\android\flutterprojects\bmi-calculator-flutter>flutter doctor -v
[√] Flutter (Channel stable, v1.7.8+hotfix.4, on Microsoft Windows [Version 10.0.17134.1006], locale en-US)
    • Flutter version 1.7.8+hotfix.4 at C:\android\flutter
    • Framework revision 20e59316b8 (8 weeks ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 38.2.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.37.1)
    • VS Code at C:\Users\Michael Odafe\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.3.0

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

**Comment by jmagman** [comment] 2020-01-11 01:19
Duplicate of https://github.com/flutter/flutter/issues/30478.

**Closed by jmagman** 2020-01-11 01:19 UTC
Labels: tool
