### ISSUE TITLE
I can't install flutter. I'm tired.

### ISSUE THREAD

**Issue by Mehrzad2011** [flutter/flutter#155108] opened 2024-09-12 18:19 UTC
Hello.
I have an arm32 linux machine.
I want to download the source of flutter and compile its source.
but I can't find the source of flutter. Can someone help me?

**Comment by matanlurey** [comment] 2024-09-12 18:29
Duplicate of https://github.com/flutter/flutter/issues/75823.

**Closed by matanlurey** 2024-09-12 18:29 UTC
