### ISSUE TITLE
showMenu creates weird offset when using an initialValue

### ISSUE THREAD

**Issue by EdwynZN** [flutter/flutter#70306] opened 2020-11-11 18:22 UTC
When using the parameter `initialValue `in `showMenu` the popUpMenuRoute is created with a weird offset

```
class _MoreSettings extends StatefulWidget {
  const _MoreSettings({Key key}) : super(key: key);

  @override
  __MoreSettingsState createState() => __MoreSettingsState();
}

class __MoreSettingsState extends State<_MoreSettings> {
  int selected = 0;

  Future<int> _postView() async{
    final double size = Theme.of(context).appBarTheme.iconTheme.size ?? 24;
    Offset offset = context.size.centerRight(Size.square(size).center(Offset.zero));
    // Offset offset = context.size.center(Offset.zero);
    return showMenu<int>(
      context: context,
      position: RelativeRect.fromLTRB(offset.dx, offset.dy, 0, 0),
      //initialValue: 2,  <-- it gives a weird offset if I uncomment it
      items: [
        // CheckedPopupMenuItem(child: const Text('Cards'), value: 0),
        PopupMenuItem<int>(child: const Text('Cards'), value: 0),
        PopupMenuItem<int>(child: const Text('Compat'), value: 1),
        PopupMenuItem<int>(child: const Text('Swipe'), value: 2),
        PopupMenuItem<int>(child: const Text('List'), value: 3),
        PopupMenuItem<int>(child: const Text('Help'), value: 4),
      ]
    );
  }

  @override
  Widget build(BuildContext context) {
    return IconButton(
      tooltip: 'Settings',
      icon: const Icon(Icons.more_vert_outlined),
      onPressed: () async {
        int selectedOption = await _postView();
        if(!mounted) return;
        setState(() => selected = selectedOption);
      }
    );
  }
}
```

with initial value commented
![Screenshot_1605117997](https://user-images.githubusercontent.com/16828084/98847908-9275b480-2416-11eb-8389-e39a838044ea.png)

and with an initial value
![Screenshot_1605118017](https://user-images.githubusercontent.com/16828084/98848106-d36dc900-2416-11eb-90ff-828ffac408be.png)

I found that `getPositionForChild` in `_PopupMenuRouteLayout` change the position in the y axis if a selectedItem is not null but I don't understand why should it move if the menu is not big enough to be an scrollable menu

By the comment:

> If `initialValue` is specified then the first item with a matching value
> will be highlighted and the value of `position` gives the rectangle whose
> vertical center will be aligned with the vertical center of the highlighted
> item (when possible).

Is there a way to prevent that?

```

[flutter] flutter doctor -v
[√] Flutter (Channel stable, 1.22.3, on Microsoft Windows [VersiÃ³n 10.0.18363.1139], locale es-MX)
    • Flutter version 1.22.3 at E:\Programs\flutter
    • Framework revision 8874f21e79 (13 days ago), 2020-10-29 14:14:35 -0700
    • Engine revision a1440ca392
    • Dart version 2.10.3

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\dartz\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = C:\Users\dartz\AppData\Local\Android\Sdk
    • Java binary at: E:\Programs\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.1.0)
    • Android Studio at E:\Programs\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

! Doctor found issues in 1 category.
exit code 0
```

**Comment by xu-baolin** [comment] 2020-11-12 00:32
Can be fixed by #70160, This PR is in the review process

**Comment by pedromassangocode** [comment] 2020-11-12 13:07
Reproducible on stable and master channel.

<details><summary>Complete code sample</summary>

```dart

import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  static const String _title = 'Flutter Code Sample';

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: _title,
      home: Scaffold(
        appBar: AppBar(title: const Text(_title),
          actions: [
            Builder(
              builder: (context) {
                return IconButton(icon: Icon(Icons.access_time), onPressed: () {
                  showMenu<int>(
                      context: context,
                      position: RelativeRect.fromLTRB(16, 0, 0, 0),
                      initialValue: 2,  // <-- it gives a weird offset if I uncomment it
                      items: [
                        // CheckedPopupMenuItem(child: const Text('Cards'), value: 0),
                        PopupMenuItem<int>(child: const Text('Cards'), value: 0),
                        PopupMenuItem<int>(child: const Text('Compat'), value: 1),
                        PopupMenuItem<int>(child: const Text('Swipe'), value: 2),
                        PopupMenuItem<int>(child: const Text('List'), value: 3),
                        PopupMenuItem<int>(child: const Text('Help'), value: 4),
                      ]
                  );
                });
              }
            )
          ],
        ),
        body: Center(
          child: MyStatefulWidget(),
        ),
      ),
    );
  }
}

```
</details>

<details><summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 1.22.3, on Mac OS X 10.15.7 19H2, locale en)
    • Flutter version 1.22.3 at /Users/pedromassango/dev/SDKs/flutter_stable
    • Framework revision 8874f21e79 (2 weeks ago), 2020-10-29 14:14:35 -0700
    • Engine revision a1440ca392
    • Dart version 2.10.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.9.3

[!] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2020.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin installed
    • Dart plugin version 202.8070

[✓] VS Code (version 1.51.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (1 available)
    • iPhone 12 Pro Max (mobile) • ECCF5C4A-8BEC-411D-B23E-85A836C3847E • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-1 (simulator)

! Doctor found issues in 1 category.
```
</details>

**Comment by xu-baolin** [comment] 2020-11-12 14:04
The position is a RelativeRect.fromLTRB, if you set right and bottom zero, it will treat as very big button, so the selected item will alignment with middle of the button, so what you should do is smaller the button.

**Comment by xu-baolin** [comment] 2020-11-12 14:07
In the future, consider adding an attribute to make this behavior optional

**Comment by EdwynZN** [comment] 2020-11-12 15:43
Should I change it to `RelativeRect.fromLTRB(offset.dx, offset.dy, offset.dx, offset.dy)` to keep it at a single point?

**Comment by xu-baolin** [comment] 2020-11-13 02:30
![image](https://user-images.githubusercontent.com/61075224/99021036-bd891100-259a-11eb-96d8-0303829b2cd7.png)

This is the `position` diagram, so you can achieve the goal by setting the correct position.

@pedromassangocode Hi,
If I explain clearly, please close this issue, thanks. :)

**Comment by xu-baolin** [comment] 2020-11-13 02:32
I will consider making the automatic alignment behavior optional, sometimes users don’t want this behavior

**Comment by pedromassangocode** [comment] 2020-11-13 08:33
@xu-baolin as of my understanding, the issue here is that the menu position varies when you set `initialValue` or not. In my code sample in https://github.com/flutter/flutter/issues/70306#issuecomment-726066501 you can reproduce by commenting and uncomment the `initialValue` and notice that the position of the menu is not the same. Is that expected?

**Comment by xu-baolin** [comment] 2020-11-13 08:38
Yes,
https://github.com/flutter/flutter/blob/7cda6866b0ef35133e01a5c701d643b99445c3af/packages/flutter/lib/src/material/popup_menu.dart#L766-L769

**Comment by pedromassangocode** [comment] 2020-11-13 13:34
Closing this as working as intended.
Thanks @xu-baolin

**Closed by pedromassangocode** 2020-11-13 13:34 UTC
Labels: f: material design, found in release: 1.22, found in release: 1.24, framework, has reproducible steps
