### ISSUE TITLE
[in_app_purchases] restorePurchases causes pending transactions

### ISSUE THREAD

**Issue by jeremiahlukus** [flutter/flutter#82455] opened 2021-05-13 16:59 UTC
`in_app_purchase: ^0.6.0`

When running 
`await _iap.restorePurchases();` 

The causes `if (purchaseDetails.pendingCompletePurchase)` in `_listenToPurchaseUpdated`  to be triggered if you have past purchases. 

i had to do 

```
    if (UniversalPlatform.isAndroid) {
      await _iap.restorePurchases();
    }
 ```  
 
 to get this to work, no issues on android just IOS

**Comment by TahaTesser** [comment] 2021-05-14 11:52
Hi @jeremiahlukus 
Thanks for filing the issue!
Maybe I am missing something but how are you calling `await _iap.restorePurchases();`?

It looks like this 
`    final  QueryPurchaseDetailsResponse response =   await  _connection.queryPastPurchases(applicationUserName: null );` 


Can you please provide your `flutter doctor -v`, a complete reproducible minimal code sample, and complete `flutter run --verbose` logs running the minimal code sample?
Thank you

**Comment by jeremiahlukus** [comment] 2021-05-14 13:58
I am calling it like the example in pub, when i init the store `await _inAppPurchase.restorePurchases();`  

`queryPastPurchases` has been removed in the new version which is what i was using the readme says no to use restorePurchases which will cause events to be fired in the purchaseUpdated stream (which it does). This should happen in the example https://pub.dev/packages/in_app_purchase/example   make a few purchases in IOS then restart the application the past purchases should be restored but when you try to purchase again it will error saying you have pending purchases and you need to complete them before purchasing more



```
[✓] Flutter (Channel beta, 2.1.0-12.2.pre, on Mac OS X 10.15.7 19H1030 darwin-x64, locale en)
    • Flutter version 2.1.0-12.2.pre at /Users/jparrack/phil/flutter
    • Framework revision 5bedb7b1d5 (8 weeks ago), 2021-03-17 17:06:30 -0700
    • Engine revision 711ab3fda0
    • Dart version 2.13.0 (build 2.13.0-116.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/jparrack/Library/Android/sdk
    • Platform android-30, build-tools 29.0.2
    • ANDROID_HOME = /Users/jparrack/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.2.5)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin version 182.5215

[✓] VS Code (version 1.53.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (2 available)
    • iPhone 12 Pro Max (mobile) • BE0DF70C-94D9-4120-B5A5-53F9FA755D84 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 90.0.4430.212

• No issues found!

```

**Comment by sgissinger** [comment] 2021-05-14 22:45
I have a similar issue with `in_app_purchase: ^0.6.0`
When running in Debug mode, calling `InAppPurchase.instance.restorePurchases();` works as expected, purchases are restored.

When running in Release mode, I get the following stacktrace and purchases are not restored.
```
I/flutter (23941): #0      InAppPurchaseAndroidPlatform.restorePurchases (package:in_app_purchase_android/src/in_app_purchase_android_platform.dart:211)
I/flutter (23941): <asynchronous suspension>
I/flutter (23941): InAppPurchaseException(restore_transactions_failed, BillingResponse.serviceDisconnected, google_play)
```

```
[√] Flutter (Channel stable, 2.0.6, on Microsoft Windows [version 10.0.19042.985], locale fr-FR)
    • Flutter version 2.0.6 at C:\flutter
    • Framework revision 1d9032c7e1 (2 weeks ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3) 
    • Android SDK at C:\Users\sgiss\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java       
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe      

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.56.2)
    • VS Code at C:\Users\sgiss\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.22.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 90.0.4430.212       
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 90.0.818.56        

• No issues found!
```

**Comment by jeremiahlukus** [comment] 2021-05-15 02:15
@sgissinger your issue isn't related, mine is iOS specific and about pending transactions caused but restore.

**Comment by TahaTesser** [comment] 2021-05-17 09:50
Hi @jeremiahlukus 
My bad, internal code sample wasn't updated, following your [steps](https://github.com/flutter/flutter/issues/82455#issuecomment-841261503) I can reproduce the issue on the  latest `in_app_purchase: ^0.6.0`


<details> 
<summary>logs</summary> 
	
```console
[ +172 ms] Hot restart performed in 1,060ms.
[   +4 ms] Performing hot restart... (completed in 1,067ms)
[        ] Restarted application in 1,075ms.
[+18272 ms] [VERBOSE-2:ui_dart_state.cc(186)] Unhandled Exception:
PlatformException(storekit_duplicate_product_object, There is a pending
transaction for the same product identifier. Please either wait for it to be
finished or finish it manually using `completePurchase` to avoid edge cases.,
{applicationUsername: null, requestData: null, quantity: 1, productIdentifier:
com.tahatesser.triage.test_consumable, simulatesAskToBuyInSandbox: false}, null)
[   +1 ms] #0      StandardMethodCodec.decodeEnvelope
(package:flutter/src/services/message_codecs.dart:581:7)
[        ] #1      MethodChannel._invokeMethod
(package:flutter/src/services/platform_channel.dart:158:18)
[        ] <asynchronous suspension>
[        ] #2      SKPaymentQueueWrapper.addPayment
(package:in_app_purchase_ios/src/store_kit_wrappers/sk_payment_queue_wrapper.dar
t:91:5)
[        ] <asynchronous suspension>
[        ] #3      InAppPurchaseIosPlatform.buyNonConsumable
(package:in_app_purchase_ios/src/in_app_purchase_ios_platform.dart:63:5)
[        ] <asynchronous suspension>


```

</details>


Reproduced on the following channel
|  `stable` |
| :---: 
|  ✅  | 

Check `flutter doctor -v` outputs for each channel below

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.0.6, on macOS 11.3.1 20E241 darwin-x64, locale
    en-GB)
    • Flutter version 2.0.6 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 1d9032c7e1 (2 weeks ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.56.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.22.0

[✓] Connected device (3 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios            • iOS
      14.5.1
    • macOS (desktop)        • macos                     • darwin-x64     •
      macOS 11.3.1 20E241 darwin-x64
    • Chrome (web)           • chrome                    • web-javascript •
      Google Chrome 90.0.4430.212

• No issues found!
```
		
</details>

**Comment by mvanbeusekom** [comment] 2021-05-20 09:42
@jeremiahlukus this is working as intended. According to Apple's documentation restored transactions need to be completed once they are restored (hence the `PurchaseDetails. pendingCompletePurchase` property returning `true`). 

There is an [issue](https://github.com/flutter/flutter/issues/82631) with the example App though since it mentions to use the `InAppPurchase.restorePurchases` method as part of the initialisation of the App. This is highly discouraged by Apple and also not necessary (even on Android). We will make the necessary updates to the example App to rectify the issue.

I will close this issue as this is working as intended and there is already an issue to track the update on the example app. If this doesn't solve your problem feel free to leave a comment and I will re-open the issue.

**Closed by mvanbeusekom** 2021-05-20 09:42 UTC
Labels: found in release: 2.0, has reproducible steps, p: first party, p: in_app_purchase, platform-ios, plugin
