### ISSUE TITLE
[tool_crash] HttpException

### ISSUE THREAD

**Issue by FayruzAldi** [flutter/flutter#154654] opened 2024-09-05 01:08 UTC
## Command
```sh
flutter run
```

## Steps to Reproduce
1. ... im actually just close the flutter window
2. ...
3. ...

## Logs
HttpException
```console

```
```console
[32m[✓][39m Flutter (Channel stable, 3.24.0, on Microsoft Windows [Version 10.0.22631.4112], locale en-ID)
    [32m•[39m Flutter version 3.24.0 on channel stable at D:\FlutterSDK\flutter_windows_3.22.3-stable\flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision 80c2e84975 (5 weeks ago), 2024-07-30 23:06:49 +0700
    [32m•[39m Engine revision b8800d88be
    [32m•[39m Dart version 3.5.0
    [32m•[39m DevTools version 2.37.2

[32m[✓][39m Windows Version (Installed version of Windows is version 10 or higher)

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    [32m•[39m Android SDK at C:\Users\LENOVO\AppData\Local\Android\sdk
    [32m•[39m Platform android-34, build-tools 34.0.0
    [32m•[39m Java binary at: D:\Android Version\Koala 2024.1.1\jbr\bin\java
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.11+0--11852314)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at C:\Users\LENOVO\AppData\Local\Google\Chrome\Application\chrome.exe

[32m[✓][39m Visual Studio - develop Windows apps (Visual Studio Build Tools 2019 16.11.39)
    [32m•[39m Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
    [32m•[39m Visual Studio Build Tools 2019 version 16.11.35130.168
    [32m•[39m Windows 10 SDK version 10.0.22621.0

[32m[✓][39m Android Studio (version 2023.1)
    [32m•[39m Android Studio at C:\Users\LENOVO\Downloads\Programs\Android Studio Hedgehog\android-studio
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)

[32m[✓][39m Android Studio (version 2023.3)
    [32m•[39m Android Studio at D:\Android Studio
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.10+0--11572160)

[32m[✓][39m Android Studio (version 2024.1)
    [32m•[39m Android Studio at D:\Android Version\Koala 2024.1.1
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.11+0--11852314)

[32m[✓][39m VS Code (version 1.90.0-insider)
    [32m•[39m VS Code at C:\Users\LENOVO\AppData\Local\Programs\Microsoft VS Code Insiders
    [32m•[39m Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[32m[✓][39m Connected device (3 available)
    [32m•[39m Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22631.4112]
    [32m•[39m Chrome (web)      • chrome  • web-javascript • Google Chrome 128.0.6613.114
    [32m•[39m Edge (web)        • edge    • web-javascript • Microsoft Edge 128.0.2739.54
    [33m![39m Device R9RR800YS4P is offline.

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[32m•[39m No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 0.1.0
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 80c2e84975bbd28ecf5f8d4bd4ca5a2490bfc819

**Comment by danagbemava-nc** [comment] 2024-09-05 06:57
Hi @FayruzAldi, what platform were you testing this on? Did you get any more errors/logs in your console? If so, can you share that with us? How many times have you gotten this crash?

**Comment by FayruzAldi** [comment] 2024-09-10 08:58
im testing it on chrome, and there's no anymore errors/logs, i got this error just once

**Comment by danagbemava-nc** [comment] 2024-09-11 06:29
Closing this as a duplicate of https://github.com/flutter/flutter/issues/73743

**Closed by danagbemava-nc** 2024-09-11 06:29 UTC
Labels: in triage
