### ISSUE TITLE
`ClipPath` does not smoothly clip the edges even though the default `clipBehaviour` is `Clip.antiAlias`

### ISSUE THREAD

**Issue by moazelshebly** [flutter/flutter#98982] opened 2022-02-23 14:26 UTC
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. Notice how the triangular border has a "saw-teeth" effect

**Expected results:** 
The edge of the triangle should be smooth since the default clipping behaviour of `ClipPath` is `Clip.antiAlias`

**Actual results:** 
The edge of the triangle has a saw-teeth-like effect as if it is using `Clip.hardEdge`.

**NOTE:**
This happens on macOS. Works fine on the web. I haven't tested other platforms.

EDIT: It also happens on iOS. 

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      themeMode: ThemeMode.dark,
      title: 'Flutter Demo',
      theme: ThemeData(primarySwatch: Colors.blue),
      home: const ContainerWithTriangleBorder(),
    );
  }
}

class ContainerWithTriangleBorder extends StatelessWidget {
  const ContainerWithTriangleBorder({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text("ClipPath"),
      ),
      body: Center(
        child: Stack(
          children: [
            Container(
              height: 500,
              width: 350,
              color: const Color(0xFFF8F5F5),
            ),
            ClipPath(
              clipper: const _TriangleCornerClipper(),
              child: Container(
                height: 500,
                width: 350,
                color: const Color(0xFF008542),
              ),
            ),
          ],
        ),
      ),
    );
  }
}

class _TriangleCornerClipper extends CustomClipper<Path> {
  const _TriangleCornerClipper();

  @override
  getClip(Size size) {
    final _triangleLegLength = size.shortestSide / 4;
    return Path()
      ..moveTo(_triangleLegLength, 0)
      ..lineTo(0, _triangleLegLength)
      ..lineTo(0, 0);
  }

  @override
  bool shouldReclip(covariant CustomClipper oldClipper) => false;
}
```

</details>

<details>
  <summary>Flutter doctor output</summary>

```
flutter doctor -v
[✓] Flutter (Channel stable, 2.10.2, on macOS 12.2.1 21D62 darwin-x64, locale en-GB)
    • Flutter version 2.10.2 at /Users/moazelshebly/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 097d3313d8 (5 days ago), 2022-02-18 19:33:08 -0600
    • Engine revision a83ed0e5e3
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/moazelshebly/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.64.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.34.0

[✓] Connected device (3 available)
    • Moaz’s iPhone (mobile) • 00008101-00142DD21140001E • ios            • iOS 15.3.1 19D52
    • macOS (desktop)        • macos                     • darwin-x64     • macOS 12.2.1 21D62 darwin-x64
    • Chrome (web)           • chrome                    • web-javascript • Google Chrome 98.0.4758.102

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

<details><summary>Screenshots</summary>
<img width="385" alt="Screenshot 2022-02-23 at 15 16 17" src="https://user-images.githubusercontent.com/41455764/155337852-94ef7f15-7660-4e4a-9fbf-0eb086859af6.png">   
<br /> 
<img width="385" alt="Screenshot 2022-02-23 at 15 16 17" src="https://user-images.githubusercontent.com/41455764/155338205-9c3190c1-25b8-4b32-91b7-294bfe4d48cd.png">  

</details>

<details><summary>Screenshots from my actual project</summary>
<img alt="Screenshot 2022-02-23 at 15 16 17" src="https://user-images.githubusercontent.com/41455764/155336852-542afe58-42b1-46b8-8d7a-7ee7b0e1caf2.png">   
<br />
<img  alt="Screenshot 2022-02-23 at 15 18 11" src="https://user-images.githubusercontent.com/41455764/155337166-61e6e115-0e38-439b-bcb7-07153e1fb012.png">

</details>

**Comment by danagbemava-nc** [comment] 2022-02-25 08:26
Hi @moazelshebly, the screenshots below are what I see on my end. Without zooming deep enough, the edges are smooth. 
 
<details>
<summary>screenshots</summary>

| macOS | iOS | android | web | 
| -- | -- | -- | -- |
| <img width="670" alt="Screenshot 2022-02-25 at 08 04 59" src="https://user-images.githubusercontent.com/88313112/155679844-ed85daba-9b3a-436b-a715-0f473f01232f.png"> | ![Simulator Screen Shot - iPhone 13 - 2022-02-25 at 08 02 18](https://user-images.githubusercontent.com/88313112/155679825-f110409a-71fb-41d2-9c81-2cdb2c7ca1e3.png) | ![Screenshot_1645776943](https://user-images.githubusercontent.com/88313112/155679832-0fa1f3f3-343c-49f3-84b0-e4b89de1a26e.png) |<img width="656" alt="Screenshot 2022-02-25 at 08 06 35" src="https://user-images.githubusercontent.com/88313112/155681153-283a4ff0-c1b5-4b4d-b94b-5ea7e8f15ce8.png"> | 

</details>

**Comment by moazelshebly** [comment] 2022-03-10 10:41
Hi @danagbemava-nc and sorry for the late reply. The screenshots I provided are not zoomed in. I took new screenshots and it seems that it is not as smooth on macOS as the other platforms. 

<details><summary>New screenshots</summary>

|iOS|web|macOS|
|---|---|---|
|![Simulator Screen Shot - iPhone 13 Pro - 2022-03-10 at 11 24 34](https://user-images.githubusercontent.com/41455764/157644460-c4a3a7e0-6a87-49f4-ae6e-67dc85dae85f.png)|![Screenshot 2022-03-10 at 11 18 02](https://user-images.githubusercontent.com/41455764/157644466-34cfd9f0-a896-47cf-87ba-c837cdfba8a8.png)|![Screenshot 2022-03-10 at 11 17 01](https://user-images.githubusercontent.com/41455764/157644468-ab072dbf-aa5b-47ec-8877-7b22d4bd65a2.png)|

</details>

As I also posted in my original comment, the screenshots from my original project are much worse, probably because the container there has a hover state and adds some shadows.

**Comment by danagbemava-nc** [comment] 2022-03-10 13:21
Hmm, I can't quite see it on my device like I do in your screenshot. Can you share the sample that is being used in your app? Since that one is more prominent, I think that might help with reproduction.

**Comment by moazelshebly** [comment] 2022-03-10 15:45
@danagbemava-nc This is quite interesting as it seems that it depends somehow on the number of `ClipPath`s painted on the screen. I tried to replicate this by using a row with five different containers and the result is quite interesting.

**Comment by danagbemava-nc** [comment] 2022-03-11 07:19
It is quite interesting. 

With the updated sample I was able to reproduce it. I did play around with the height factor a bit, which is why they look smaller in the screenshots.

Updated code sample is in https://github.com/flutter/flutter/issues/98982#issuecomment-1064202066. 

<details>
<summary>screenshots</summary>
 
| web (canvaskit) | ios | android | web(html) | macos | 
| -- | -- | -- | -- | -- | 
| ![Screenshot 2022-03-11 at 06 37 27](https://user-images.githubusercontent.com/88313112/157819851-2ebb8a70-b8f5-419f-a6c8-9c024375914f.png) | ![Simulator Screen Shot - iPhone 13 - 2022-03-11 at 06 48 17](https://user-images.githubusercontent.com/88313112/157819854-0eff61f4-6ebd-4e2e-b8f1-687992e133f5.png) | ![Screenshot_1646981439](https://user-images.githubusercontent.com/88313112/157819855-b36a5c5e-649d-4d7b-88a1-018cdc45c010.png) | ![Screenshot 2022-03-11 at 06 59 46](https://user-images.githubusercontent.com/88313112/157819858-3d60283a-f781-4ea9-ae7e-90928f4cde12.png) | ![Screenshot 2022-03-11 at 06 34 21](https://user-images.githubusercontent.com/88313112/157819838-1da1c0cc-f973-428f-a421-4af5c2bf1b1e.png) | 

</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.10.3, on macOS 12.2.1 21D62 darwin-arm, locale en-GB)
    • Flutter version 2.10.3 at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (9 days ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[☠] IntelliJ IDEA Community Edition (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    ✗ FormatException: Unexpected extension byte (at offset 5)
    • #0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1789:7)
      #1      Utf8Decoder.convert (dart:convert/utf.dart:351:42)
      #2      InputStream.readString (package:archive/src/util/input_stream.dart:207:30)
      #3      new ZipDirectory.read (package:archive/src/zip/zip_directory.dart:40:30)
      #4      ZipDecoder.decodeBuffer (package:archive/src/zip_decoder.dart:19:30)
      #5      ZipDecoder.decodeBytes (package:archive/src/zip_decoder.dart:14:12)
      #6      IntelliJPlugins._findPluginXml (package:flutter_tools/src/intellij/intellij.dart:130:44)
      #7      IntelliJPlugins._readPackageVersion (package:flutter_tools/src/intellij/intellij.dart:141:40)
      #8      IntelliJPlugins.validatePackage (package:flutter_tools/src/intellij/intellij.dart:63:35)
      #9      IntelliJValidator.validate (package:flutter_tools/src/intellij/intellij_validator.dart:103:15)
      #10     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      #11     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:109:18)
      #12     _rootRun (dart:async/zone.dart:1426:13)
      #13     _CustomZone.run (dart:async/zone.dart:1328:19)
      #14     _runZoned (dart:async/zone.dart:1861:10)
      #15     runZonedGuarded (dart:async/zone.dart:1849:12)
      #16     runZoned (dart:async/zone.dart:1780:12)
      #17     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #18     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:205:9)
      #19     Doctor.diagnose (package:flutter_tools/src/doctor.dart:309:47)
      #20     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:50:48)
      #21     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1320:12)
      <asynchronous suspension>
      #22     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1161:27)
      <asynchronous suspension>
      #23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #24     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
      <asynchronous suspension>
      #25     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
      <asynchronous suspension>
      #26     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #27     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
      <asynchronous suspension>
      #28     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
      <asynchronous suspension>
      #29     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #30     main (package:flutter_tools/executable.dart:94:3)
      <asynchronous suspension>


[✓] VS Code (version 1.65.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.36.0

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 12 (API 31) (emulator)
    • macOS (desktop)             • macos         • darwin-arm64   • macOS 12.2.1 21D62 darwin-arm
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 99.0.4844.51

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

```
[✓] Flutter (Channel master, 2.11.0-0.0.pre.869, on macOS 12.2.1 21D62 darwin-arm, locale en-GB)
    • Flutter version 2.11.0-0.0.pre.869 at /Users/nexus/dev/sdks/flutters
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 1223e87f7b (2 hours ago), 2022-03-10 21:09:49 -0800
    • Engine revision 6239bfb884
    • Dart version 2.17.0 (build 2.17.0-182.0.dev)
    • DevTools version 2.11.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] IntelliJ IDEA Community Edition (version 2021.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin version 213.5744.122

[✓] VS Code (version 1.65.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.36.0

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 12 (API 31) (emulator)
    • macOS (desktop)             • macos         • darwin-arm64   • macOS 12.2.1 21D62 darwin-arm
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 99.0.4844.51

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by zanderso** [comment] 2022-03-14 18:08
@flar any thoughts on this? Could this be related to too aggressively eliding render target switches?

**Comment by flar** [comment] 2022-03-18 20:42
I've been trying to reproduce this locally since examining images in a browser doesn't necessarily convey the exact pixels.

I have noticed that the AA quality of a 45-degree line varies by subpixel position. I'm looking at that and trying to compare to clip-AA to see if there is a difference between the operations and/or with sub-pixel location of the diagonal.

**Comment by chaeMil** [comment] 2023-09-30 01:10
This still occurs in Flutter 3.13.6

![image](https://github.com/flutter/flutter/assets/9150597/9046bd40-2b5e-4d21-8068-c9c921d60c3d)

**Comment by chaeMil** [comment] 2023-09-30 19:13
When its being redrawn is ok, but after that it goes to the jagged edges state.


https://github.com/flutter/flutter/assets/9150597/c548fa47-d170-4361-a983-5f5c0a518fdf

**Comment by chinmaygarde** [comment] 2023-10-09 17:56
Triage: We were thinking of raster cache but 3.13.6 has Impeller enabled and that does not use the raster cache. This needs more investigation. Thanks for the reduced test case.

**Comment by chaeMil** [comment] 2023-10-10 08:12
@chinmaygarde My bad, after enabling impeller on iOS, its fixed (I have it disabled on purpose before). Since macOS does not have impeller ready its still present there.

**Comment by flar** [comment] 2023-10-10 22:23
> @chinmaygarde My bad, after enabling impeller on iOS, its fixed (I have it disabled on purpose before). Since macOS does not have impeller ready its still present there.

Impeller on MacOS is off by default, but you can enable it with `flutter run --enable-impeller`.

**Comment by chaeMil** [comment] 2023-10-11 08:24
@flar when enabled, lots of features break, for example decoding `.webp` images is competely broken 🤷‍♂️

**Comment by jonahwilliams** [comment] 2024-02-20 21:28
We believe this issue is fixed by the Impeller backend. Though some platforms may not be able to use Impeller yet, we're going to close this issue as the blocking issues should be tracked elsewhere.

**Closed by jonahwilliams** 2024-02-20 21:28 UTC
Labels: platform-ios, engine, platform-mac, c: rendering, has reproducible steps, P1, found in release: 2.10, found in release: 2.11, team-engine, triaged-engine, multiteam-retriage-candidate
