### ISSUE TITLE
Big memory leak issue with "image_picker" plugin

### ISSUE THREAD

**Issue by SogoGolf** [flutter/flutter#61147] opened 2020-07-09 08:03 UTC
## Details
This is a **major concern** for us as we look to port a native iOS/Android app to Flutter.

We did a memory profile of our in development Flutter mobile (iOS and Android) app today and got very concerning results, specifically when using the "image_picker" lib. Basically each time we chose a single image from the gallery, or via taking a photo - the memory consumption continued to increase(!) each time. This testing was only on iOS.

To see if it was a problem with our code, we decided to profile the Flutter example app for image_picker on iOS (https://github.com/flutter/plugins). However it too displayed a continually increasing memory trendline on selection of any image.

Here is a pic of the Instruments (11.5) chart from Xcode:

![image](https://user-images.githubusercontent.com/19580787/87010518-00f8fa80-c20a-11ea-999e-46987327e0ae.png)

Our expectation, is that the memory usage after selecting a single image increases, BUT -> if then choosing a replacement image from either the gallery or by taking a photo -- the memory usage stays roughly the same. ie. it does not continually increase with each replacement image. Also, when navigating away from the view/screen that displays an image - memory that was being consumed by that image, is **released**. 

We are seeing exactly the same behaviour on iOS in our Flutter app.

Target platforms:
- iOS (v13.5.1)
- Android (v21+)

Testing was done on real devices (iPhone 11; iPhone 6) in release mode.

## Logs
➜ flutter analyze
Analyzing example...
No issues found! (ran in 7.9s)

➜ flutter doctor -v
[✓] Flutter (Channel stable, v1.17.2, on Mac OS X 10.15.5 19F101, locale en-AU)
    • Flutter version 1.17.2 at /Users/xxxxx/flutter-dev-lib/flutter
    • Framework revision 5f21edf8b6 (6 weeks ago), 2020-05-28 12:44:12 -0700
    • Engine revision b851c71829
    • Dart version 2.8.3

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/xxxxx/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.1

**Comment by TahaTesser** [comment] 2020-07-09 08:32
duplicate of https://github.com/flutter/flutter/issues/54757

**Closed by TahaTesser** 2020-07-09 08:32 UTC
