### ISSUE TITLE
Is it possible to somehow filter the query by `arrayNotContains`? I can not find something similar in the documentation.

### ISSUE THREAD

**Issue by ChakibAA** [flutter/flutter#89587] opened 2021-09-07 14:17 UTC
Is it possible to somehow filter the query by `arrayNotContains`? I can not find something similar in the documentation.

_Originally posted by @Frozmen in https://github.com/flutter/flutter/issues/20489#issuecomment-537409213_

**Comment by TahaTesser** [comment] 2021-09-07 14:21
Hi @ChakibAA 
From what I can see, the issue is related to a FlutterFire plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  providing your `flutter doctor -v`, your `pubspec.yaml`, a minimal reproducible code sample that does not use 3rd party plugins, your complete `flutter run -v` logs running the minimal code sample 
and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-09-07 14:21 UTC
Labels: in triage
