### ISSUE TITLE
After updating flutter, got the "Error converting bytecode to dex" error

### ISSUE THREAD

**Issue by Cheanakhim007** [flutter/flutter#45969] opened 2019-12-03 06:55 UTC
Dex: Error converting bytecode to dex:                                  
Cause: com.android.dex.DexException: Multiple dex files define Landroid/support/customtabs/ICustomTabsService$Stub;
    UNEXPECTED TOP-LEVEL EXCEPTION:                                     
    com.android.dex.DexException: Multiple dex files define Landroid/support/customtabs/ICustomTabsService$Stub;
                                                                        
com.android.dex.DexException: Multiple dex files define Landroid/support/customtabs/ICustomTabsService$Stub;
        at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:661)
        at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:616)
        at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:598)
        at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
        at com.android.dx.merge.DexMerger.merge(DexMerger.java:198)     
        at com.android.builder.dexing.DexArchiveMergerCallable.call(DexArchiveMergerCallable.java:61)
        at com.android.builder.dexing.DexArchiveMergerCallable.call(DexArchiveMergerCallable.java:36)
        at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1424)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
                                                                        
FAILURE: Build failed with an exception.                                
                                                                        
* What went wrong:                                                      
Execution failed for task ':app:transformDexArchiveWithDexMergerForDebug'.
> com.android.build.api.transform.TransformException: com.android.dex.DexException: Multiple dex files define Landroid/support/customtabs/ICustomTabsService$Stub;
                                                                        
* Try:                                                                  
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Comment by janmoppel** [comment] 2019-12-03 16:33
Hello @Cheanakhim007 !

Thank you for posting an issue. This seems like the same problem discussed here: #28571. 
Can you please post the `flutter doctor -v` command output and run the same command with the `--stacktrace` option? Also, when did the problem occurred? Did you start the build or?

**Comment by zanderso** [comment] 2019-12-10 22:55
The autoclose bot shouldn't have closed https://github.com/flutter/flutter/issues/28571, I think. This does look like a dupe of that issue, so I've reopened it and we'll track there since there's a bit more discussion on it.

**Closed by zanderso** 2019-12-10 22:55 UTC
Labels: severe: crash, severe: regression, t: gradle, tool, waiting for customer response, ▣ platform-android
