### ISSUE TITLE
flutter lost my plugin libs and got errors: Could not build the precompiled application for the device.

### ISSUE THREAD

**Issue by monkingame** [flutter/flutter#58966] opened 2020-06-08 08:45 UTC
## Steps to Reproduce

1)   I wrote a plugin to use hikvision cameras .

The plugin works very well when I compile the ios Runner workspace .

I even uploaded the Runner iOS app to apple store . The app status is 'Ready for Sale' on the apple app store.

But when I open the flutter project and run with flutter, it got errors:
```
Could not build the precompiled application for the device.
```

2)  The normal workspace under Xcode is below:
![image](https://user-images.githubusercontent.com/4568610/84007763-75d6db80-a9a3-11ea-9651-cdc525ec5cae.png)

And my workspace plugin source files are below:
![image](https://user-images.githubusercontent.com/4568610/84007963-b7678680-a9a3-11ea-9c7b-3e7722703546.png)

And libs included in the plugin are below:
![image](https://user-images.githubusercontent.com/4568610/84008011-ca7a5680-a9a3-11ea-881d-1631bb2bc229.png)

Up to now, the workspace works well under Xcode.
And I can build and upload the app to apple appstore,even got status: Ready for Sale!

3)  After open the flutter project with visualstudiocode, and run with 'F5' key,the error occurs:
```
Could not build the precompiled application for the device.
Error launching application on your-iphone.
```

4)  More strange is : the plugin libs lost in Xcode workspace(screen capture below).
![image](https://user-images.githubusercontent.com/4568610/84008261-293fd000-a9a4-11ea-94fd-be9b6ae87acf.png)

And  compile option in the plugin '-fno-objc-arc' also lost.

5)  Then I have to add the libs in Xcode workspace again (screen below):
![image](https://user-images.githubusercontent.com/4568610/84008915-0eba2680-a9a5-11ea-9052-a79c54eb81c3.png)

and restore compiler flags(below):
(the compiler flags exist in the Xcode workspace originly)
![image](https://user-images.githubusercontent.com/4568610/84008993-2db8b880-a9a5-11ea-8f97-f539002f3d96.png)

6)  Xcode build the workspace,but got error in the lib source files:
(The libs source files work well before flutter run the project)
```
Unknown type name 'class'; did you mean 'Class'?
```
![image](https://user-images.githubusercontent.com/4568610/84009422-ce0edd00-a9a5-11ea-9594-cb99ed0c25b9.png)

## Logs and summary

<details>
  <summary>Logs</summary>

```
/Users/shouhuasun/dev/gorun-app-20200603/gorun_nvr_app/ios/Runner/GeneratedPluginRegistrant.m:14:9: fatal error:
                        could not build module 'hikvision_plugin'
                        #import <hikvision_plugin/HikvisionPlugin.h>
                         ~~~~~~~^
                        21 errors generated.
                    
                        Ditto

/Users/shouhuasun/dev/gorun-app-20200603/gorun_nvr_app/build/ios/Debug-iphoneos/GoRun_Nvr_App.swiftmodule/arm64-a
                        pple-ios.swiftmodule

/Users/shouhuasun/Library/Developer/Xcode/DerivedData/Runner-cwwyguevcfcusxfttdzlpzndewqe/Build/Intermediates.noi
                        ndex/Runner.build/Debug-iphoneos/Runner.build/Objects-normal/arm64/GoRun_Nvr_App.swiftmodule
(in target 'Runner'
                        from project 'Runner')
                            cd /Users/shouhuasun/dev/gorun-app-20200603/gorun_nvr_app/ios
                            /usr/bin/ditto -rsrc

/Users/shouhuasun/Library/Developer/Xcode/DerivedData/Runner-cwwyguevcfcusxfttdzlpzndewqe/Build/Intermediates

.noindex/Runner.build/Debug-iphoneos/Runner.build/Objects-normal/arm64/GoRun_Nvr_App.swiftmodule

/Users/shouhuasun/dev/gorun-app-20200603/gorun_nvr_app/build/ios/Debug-iphoneos/GoRun_Nvr_App.swiftmodule/arm
                            64-apple-ios.swiftmodule
                    
                        warning: GLKit is deprecated. Consider migrating to MetalKit instead. (in target
'hikvision_plugin' from project
                        'Pods')
                        warning: OpenGLES is deprecated. Consider migrating to Metal instead. (in target
'hikvision_plugin' from project
                        'Pods')
                    
[ +458 ms] Could not build the precompiled application for the device.
[  +26 ms] Error launching application on sun-iphone.
[   +6 ms] "flutter run" took 28,324ms.
[   +8 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:570:7)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:818:18)
           #3      _rootRunUnary (dart:async/zone.dart:1198:47)
           #4      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #5      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #7      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #8      Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #11     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
           #12     _rootRunUnary (dart:async/zone.dart:1198:47)
           #13     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #14     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #16     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #17     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #18     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
           #19     _rootRun (dart:async/zone.dart:1190:13)
           #20     _CustomZone.run (dart:async/zone.dart:1093:19)
           #21     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #22     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
           #23     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #24     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #25     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
           #26     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
           
           
[ +255 ms] ensureAnalyticsSent: 253ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hook priority 4
[   +1 ms] Shutdown hooks complete
[        ] exiting with code 1
```

```
Analyzing gorun_nvr_app...                                              

   info • The value of the local variable 'inited' isn't used • lib/device_view/device_replay_view.dart:174:11 •
          unused_local_variable
   info • The value of the local variable 'status' isn't used • lib/device_view/device_replay_view.dart:181:11 •
          unused_local_variable

2 issues found. (ran in 5.4s)
```

```
[✓] Flutter (Channel master, 1.19.0-4.0.pre.99, on Mac OS X 10.15.5 19F101, locale zh-Hans-CN)
    • Flutter version 1.19.0-4.0.pre.99 at /Users/shouhuasun/tools/flutter
    • Framework revision 7467492444 (3 hours ago), 2020-06-08 02:03:01 -0400
    • Engine revision dfdd88deb7
    • Dart version 2.9.0 (build 2.9.0-13.0.dev 87c5e3612b)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at /Users/shouhuasun/Library/Android/sdk
    • Platform android-29, build-tools 29.0.0
    • ANDROID_HOME = /Users/shouhuasun/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.8.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (2 available)
    • sun-iphone • xxxxxxxxxxxxxxxxxxxxxxx • ios        • iOS 13.5.1
    • macOS      • macOS                                    • darwin-x64 • Mac OS X 10.15.5 19F101

• No issues found!
```

</details>

**Comment by TahaTesser** [comment] 2020-06-08 12:31
Hi @monkingame 
I am not sure what do you mean by "lost", you mean deleted or not detected?
Since this is your own code implementation , i cannot reproduce it
Error messages points your module clearly
```
/Users/shouhuasun/dev/gorun-app-20200603/gorun_nvr_app/ios/Runner/GeneratedPluginRegistrant.m:14:9: fatal error:
                        could not build module 'hikvision_plugin'
                        #import <hikvision_plugin/HikvisionPlugin.h>
                         ~~~~~~~^
                        21 errors generated.
```

Can you please any code sample to reproduce this issue?
Thank you

**Comment by monkingame** [comment] 2020-06-08 13:22
> Hi @monkingame
> I am not sure what do you mean by "lost", you mean deleted or not detected?
> Since this is your own code implementation , i cannot reproduce it
> Error messages points your module clearly
> 
> ```
> /Users/shouhuasun/dev/gorun-app-20200603/gorun_nvr_app/ios/Runner/GeneratedPluginRegistrant.m:14:9: fatal error:
>                         could not build module 'hikvision_plugin'
>                         #import <hikvision_plugin/HikvisionPlugin.h>
>                          ~~~~~~~^
>                         21 errors generated.
> ```
> 
> Can you please any code sample to reproduce this issue?
> Thank you

Flutter changed my iOS workspace settings and made it NOT worked.
At first I open iOS workspace in the flutter project using Xcode.Xcode works very well and I built app and uploaded to appstore , even got ready for sale.
But once flutter open the project, iOS workspace became not working.
Flutter delete the libraries inclued in Pods project, and clear some compiling flags, and caused the workspace NOT working. The workspace cannot be compiled in the Xcode and got many errors .
I tried to restore the settings : include libraries again, set compiling flags again, and so on. But the iOS workspace still cannot be compiled normally.
I donot know what happened after flutter run the project.
Perhaps flutter is not good at plugin project?(My project is a plugin project.)

**Comment by TahaTesser** [comment] 2020-06-09 10:51
Hi @monkingame 
Can you please provide your `flutter doctor -v`?
Thank you

**Comment by monkingame** [comment] 2020-06-09 10:57
> Hi @monkingame
> Can you please provide your `flutter doctor -v`?
> Thank you


```
[✓] Flutter (Channel master, 1.19.0-4.0.pre.99, on Mac OS X 10.15.5 19F101, locale zh-Hans-CN)
    • Flutter version 1.19.0-4.0.pre.99 at /Users/shouhuasun/tools/flutter
    • Framework revision 7467492444 (3 hours ago), 2020-06-08 02:03:01 -0400
    • Engine revision dfdd88deb7
    • Dart version 2.9.0 (build 2.9.0-13.0.dev 87c5e3612b)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at /Users/shouhuasun/Library/Android/sdk
    • Platform android-29, build-tools 29.0.0
    • ANDROID_HOME = /Users/shouhuasun/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.8.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (2 available)
    • sun-iphone • xxxxxxxxxxxxxxxxxxxxxxx • ios        • iOS 13.5.1
    • macOS      • macOS                                    • darwin-x64 • Mac OS X 10.15.5 19F101

• No issues found!
```

**Comment by monkingame** [comment] 2020-06-10 09:39
@TahaTesser 
I wrote a simple project and reproduce the issue.
I created two project by:
```
flutter create app_normal
flutter create -t plugin -i objc -a java plugin_issue
```
Here is the  sample project:
[https://github.com/monkingame/flutter-plugin-issue](flutter-plugin-issue)

You can reproduce the issue by these steps:

1)  clone the sample project
```
git clone https://github.com/monkingame/flutter-plugin-issue
```

note: app_normal include plugin in the pubspec.yaml
```
  plugin_issue:
    path: ../plugin_issue
```

2)   using Xcode to open app_normal/ios/Runner.xcworkspace

3)   Goto Runner - Targets/Runner - Signing&Capabilities - Team
Specify your team ID.

4) open terminal and goto app_normal dir, run :
```
flutter build ios --no-codesign
```
This command is to generate Podfile project.
It will get some errors but it doesn't matter since Pod project need to be config.

5)  Quit and reopen Xcode to open Runner.xcworkspace
Now the Pods project is ready for build.

![image](https://user-images.githubusercontent.com/4568610/84249770-c08c5b00-ab3d-11ea-9573-bd39ca495413.png)

6)   config the Pods project.
In Xcode, open 
Pods - Target/plugin_issue - Build Phases - Compile Sources - DeviceInfo.m - Compiler Flags
```
-fno-objc-arc
```
Pods - Target/plugin_issue - Build Phases - Compile Sources - DeviceInfo.m - Link Binary With Libraries , add a simple lib: VideoToolbox.framework(this is only  a sample lib, actual project has many libs included).

7)  Now the Pods project is like this:
![image](https://user-images.githubusercontent.com/4568610/84250344-853e5c00-ab3e-11ea-9910-31a8f716c224.png)

8)   Clean and rebuild the workspace with Xcode.
The Runner should be built successfully with no errors.

9)   Open app_normal project with visualstudio code:
Run the flutter project with 'F5' key.
It should get errors:
```
Could not build the precompiled application for the device.
```
![image](https://user-images.githubusercontent.com/4568610/84251031-5d9bc380-ab3f-11ea-93e0-6c22bd425a10.png)

10)   Now return to Xcode and you'll find the Runner config settings lost!
It may look likes this:
![image](https://user-images.githubusercontent.com/4568610/84251204-9dfb4180-ab3f-11ea-91ca-53201cd30dc1.png)

The compiler flags -fno-objc-arc in DeviceInfo.m lost!
The lib VideoToolbox.framework also lost!

11)   Xcode build the Runner workspace, it will get errors.
If you reconfig the -fno-objc-arc compiler  flags and rebuild Runner workspace , it will be OK and build successfully again.
But it is because of the sample project is simple .
In my actual Xcode workspace, the Pods project has 10 or 20 apple libraries and many external libraries.
If I run the step (9), then the Xcode workspace will never be compiled OK. Even if I reconfig the compiler flags and reimport all libraries, the workspace still keeps errors.

12)   Above is the steps to reproduce the lost config in Pods project.
If there is something unclear, keep in touch with me.

Thanks!

**Comment by jmagman** [comment] 2020-06-17 19:25
`flutter run` runs `pod install` which which will intentionally blow away any changes you make to that Pods projects.  That's a CocoaPods thing, not a Flutter or Xcode thing.  The way to link on frameworks and add compiler flags is to do so in your plugin's podspec.  Check out CocoaPods documentation like
https://guides.cocoapods.org/syntax/podspec.html#compiler_flags
or
https://guides.cocoapods.org/syntax/podspec.html#frameworks

The podspec should describe everything your plugins needs so your plugin customers don't need to edit anything in their actual app.

Closing, works as intended.

**Closed by jmagman** 2020-06-17 19:25 UTC
Labels: P4, a: build, platform-ios, t: xcode, tool
