### ISSUE TITLE
Image Picker crash on iOS

### ISSUE THREAD

**Issue by Rahul-Chandera** [flutter/flutter#56291] opened 2020-05-04 12:56 UTC
## Steps to Reproduce

1. Integrate image picker with your app.
2. Put 2 buttons into your app, one to pick from camera, another to pick from photo library.
3. Tap on 1st button, and tap to 2nd button immediately.

**Expected results:**
It should open camera or image picker after permission given

**Actual results:**
Application crashed

Exception has occurred.
PlatformException (PlatformException(multiple_request, Cancelled by a second request, null))

**Comment by iapicca** [comment] 2020-05-04 13:21
Hi @Rahul-Chandera 
can you please provide your `flutter doctor -v` , 
your `flutter run --verbose` and 
your `pubspec.yaml`;

the issue you are describing might be caused by 
how the async call to the native side is implemented
could you please provide a reproducible minimal code sample.
Thank you

**Comment by Rahul-Chandera** [comment] 2020-05-14 04:50
Thanks for your quick response.

flutter doctor -v
[✓] Flutter (Channel stable, v1.17.0, on Mac OS X 10.15.3 19D76, locale en-IN)
    • Flutter version 1.17.0 at /Users/rahulchandera/flutter
    • Framework revision e6b34c2b5c (11 days ago), 2020-05-02 11:39:18 -0700
    • Engine revision 540786dd51
    • Dart version 2.8.1

Basically this crash happens when system tries to open two permission dialogue one after another immediately (camera & photo library access dialogue).

**Comment by TahaTesser** [comment] 2020-05-14 08:10
Hi @Rahul-Chandera 
Running the official [example](https://pub.dev/packages/image_picker#-example-tab-) with both buttons for photo library and camera, tapping them one by one has no issue with permissions

It could be your code that causing this issue, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by TahaTesser** [comment] 2020-06-05 10:11
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

**Closed by TahaTesser** 2020-06-05 10:11 UTC
Labels: in triage, waiting for customer response
