### ISSUE TITLE
Flutter Logo SplashScreen before my App!!!

### ISSUE THREAD

**Issue by AnasReza** [flutter/flutter#157937] opened 2024-10-31 18:20 UTC
### Steps to reproduce

To reproduce it is very simple that just open the app you will see the Flutter Logo for some time and then you will see my app starting.

### Expected results

The app should start directly from my Mobile App's Splash Screen rather than Flutter Logo.

### Actual results

Please have a look at the video that I have attached that it is showing that the App is started with the Flutter logo in the center and after sometime my Mobile App's Splash screen is open.

### Code sample

<details open><summary>Code sample</summary>

void main() async {
   WidgetsFlutterBinding.ensureInitialized();
  await Future.delayed(const Duration(milliseconds: 5000));
  // final appDocumentDir = await getApplicationDocumentsDirectory();
  // Hive.init(appDocumentDir.path);
  await Hive.initFlutter();

  await Hive.openBox('userBox');
  await Hive.openBox('bookmarkBox');

  runApp( MyApp());
}
class MyApp extends StatelessWidget{
  @override
  Widget build(BuildContext context) {
    SystemChrome.setPreferredOrientations([
      DeviceOrientation.portraitUp,
      DeviceOrientation.portraitDown,
    ]);
   return MaterialApp(
     debugShowCheckedModeBanner: false,

     home: SplashScreen(),
     
   );
  }

}
</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/user-attachments/assets/58876421-d72f-4c7a-b547-c58b34aa3844

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

[✓] Flutter (Channel stable, 3.24.4, on macOS 15.1 24B83 darwin-x64, locale en-PK)
    • Flutter version 3.24.4 on channel stable at /Users/macbookpro/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 603104015d (7 days ago), 2024-10-24 08:01:25 -0700
    • Engine revision db49896cf2
    • Dart version 3.5.4
    • DevTools version 2.37.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/macbookpro/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 21.0.3+-79915915-b509.11)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16A242d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.3+-79915915-b509.11)

[✓] VS Code (version 1.80.1)
    • VS Code at /Users/macbookpro/External Harddisk/Software/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] VS Code (version 1.80.1)
    • VS Code at /Volumes/AnasBackup/Software/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 15.1 24B83 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 130.0.6723.70

[✓] Network resources
    • All expected network resources are available.

• No issues found!

</details>

**Comment by SriVira** [comment] 2024-10-31 18:26
you have to ovverride the splash screen in flutter 
study this package - flutter_native_splash: ^2.4.2

**Comment by AnasReza** [comment] 2024-10-31 18:30
I have used this package but it does not work and secondly why this issue is arising as I have just made a new flutter project and run that newly created project on my physical device that newly project is also having this problem

**Comment by danagbemava-nc** [comment] 2024-11-01 07:38
Hi @AnasReza, this is not a bug. All android apps (including flutter apps) have a default splash screen. Flutter's case happens to be the flutter logo. You can customize it to suit your app. See https://docs.flutter.dev/platform-integration/android/splash-screen for more explanation. 

As pointed out above, you can also use some third-party plugins. If the plugins do not work for you, please file an issue on their repo. 

Closing from here as the splash screen is not a bug. 

Thank you 

PS: You have a 5 second delay before your app starts. If this is to prevent an error or something similar, this is a band-aid solution and not an actual fix, you should investigate and fix the issue accordingly.

**Closed by danagbemava-nc** 2024-11-01 07:38 UTC
Labels: in triage
