### ISSUE TITLE
How can this error be solved !

### ISSUE THREAD

**Issue by omarakl** [flutter/flutter#107928] opened 2022-07-19 13:53 UTC
FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\hp\AndroidStudioProjects\abc\android\app\build.gradle' line: 26

* What went wrong:
A problem occurred evaluating project ':app'.
> Could not load compiled classes for script 'C:\flutter\packages\flutter_tools\gradle\flutter.gradle' from cache.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 52s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by exaby73** [comment] 2022-07-20 05:33
@omarakl This issue looks like a duplicate of https://github.com/flutter/flutter/issues/107523. Closing as such

**Closed by exaby73** 2022-07-20 05:33 UTC
Labels: waiting for customer response, in triage
