### ISSUE TITLE
Regressions in rasterizer metrics...

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#85561] opened 2021-06-29 18:26 UTC
Looks like 90th_percentile_frame_rasterizer_time_millis, 99th_percentile_frame_rasterizer_time_millis, average_frame_rasterizer_time_millistimeToFirstFrameRasterizedMicros, and worst_frame_rasterizer_time_millis are all affected. 

See https://flutter-flutter-perf.skia.org/e/?begin=1624912263&end=1624985465&keys=X17a2a7fc30f983e7bd1b45feee6fc777&num_commits=50&request_type=1&xbaroffset=24782.

Also see https://flutter-flutter-perf.skia.org/e/?begin=1624912263&end=1624985465&keys=X1f7236ae14dd4f908e41e01cf0b90796&num_commits=50&request_type=1&xbaroffset=24782 for other rasterizer regressions.

It looks like it might be the roll at https://github.com/flutter/flutter/pull/85508.

**Comment by bdero** [comment] 2021-06-29 22:17
https://github.com/flutter/flutter/issues/84213 is the cause of the regression, https://github.com/flutter/engine/pull/27048 was merged to disable it. Next roll should fix.

**Comment by bdero** [comment] 2021-06-30 17:51
All the metrics returned to their previous readouts.
![image](https://user-images.githubusercontent.com/919017/124008158-fb537200-d990-11eb-8976-0a6cd54aa50f.png)

**Closed by bdero** 2021-06-30 17:51 UTC
Labels: P0, engine, perf: speed, severe: performance, severe: regression
