### ISSUE TITLE
Cursor misplaced in multiline TextField

### ISSUE THREAD

**Issue by 33-Elephants** [flutter/flutter#51109] opened 2020-02-20 09:26 UTC
Steps to reproduce:
1. Add multiline TextField on a form
2. Enter the following text:
```
A
<EMPTY LINE>
B
```
3. Now place cursor at empty line and try to enter space characters

Expected results:
Cursor should move forward and backward when user presses BACKSPACE

Actual results:
Cursor stays at first position

This bug can be also reproduced in [Flutter Gallery app](https://play.google.com/store/apps/details?id=io.flutter.demo.gallery)

```
flutter doctor -v:
[✓] Flutter (Channel stable, v1.12.13+hotfix.7, on Linux, locale en_US.UTF-8)
    • Flutter version 1.12.13+hotfix.7 at /home/artem/Development/flutter
    • Framework revision 9f5ff2306b (3 weeks ago), 2020-01-26 22:38:26 -0800
    • Engine revision a67792536c
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /home/artem/Development/android-sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /home/artem/Development/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Android Studio (version 3.5)
    • Android Studio at /home/artem/Development/android-studio
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (1 available)
    • DUB LX1 • 4FF6R19828018221 • android-arm64 • Android 8.1.0 (API 27)

• No issues found!
```

**Comment by TahaTesser** [comment] 2020-02-20 09:35
Hi @33-Elephants 
Does this describes your issue?

![2020-02-20-15-00-21](https://user-images.githubusercontent.com/48603081/74920573-6468c400-53f2-11ea-9661-e8fc38e5c70f.gif)

Thank you

**Comment by 33-Elephants** [comment] 2020-02-20 09:54
Yes, this is exactly what we observe

**Comment by VladyslavBondarenko** [comment] 2020-02-20 10:09
Duplicate of https://github.com/flutter/flutter/issues/50033

@33-Elephants please thumb up the mentioned issue 

Closing current one,
feel free to comment if it's not the same case, and I will reopen it,
thank you

**Closed by VladyslavBondarenko** 2020-02-20 10:09 UTC
Labels: a: text input, f: material design, framework
