### ISSUE TITLE
Can't always paste in a TextField in macOS

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [flutter/flutter#55070] opened 2020-04-17 21:50 UTC
## Steps to Reproduce

1. Run `flutter create bug`.
2. Replace the build method with the following :
```dart
Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: TextField(),
      ),
    );
  }
```
3. Try to paste something. If it works, hot restart and try again. After a try or 2, it doesn't paste. I verified that the clipboard had content by pasting else where and it works. 

**Expected results:** Text should paste

**Actual results:** No text

When running with verbose output, I couldn't reproduce the error, but when running from the IDE, i was able to reproduce it occasionally.
<details>
  <summary>Logs</summary>

```
None available
```

```
[✓] Flutter (Channel master, v1.18.0-6.0.pre.62, on Mac OS X 10.15.5 19F53f, locale en-US)
    • Flutter version 1.18.0-6.0.pre.62 at /Users/thinkdigital/development/flutter
    • Framework revision bd068f50d5 (23 hours ago), 2020-04-16 15:50:03 -0700
    • Engine revision e6a2534b63
    • Dart version 2.8.0 (build 2.8.0-dev.20.7 3e43a3dcad)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/thinkdigital/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/thinkdigital/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/thinkdigital/Library/Android/sdk
    • Java binary at: /Users/thinkdigital/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/192.6392135/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] Android Studio (version 3.6)
    • Android Studio at /Users/thinkdigital/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/192.6392135/Android
      Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] IntelliJ IDEA Community Edition (version 2019.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 43.0.3
    • Dart plugin version 193.6015.53

[✓] VS Code (version 1.44.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1

 
[✓] Connected device (4 available)            
    • Android SDK built for x86 64 • emulator-5554 • android-x64    • Android 10 (API 29) (emulator)
    • macOS                        • macOS         • darwin-x64     • Mac OS X 10.15.5 19F53f
    • Chrome                       • chrome        • web-javascript • Google Chrome 80.0.3987.163
    • Web Server                   • web-server    • web-javascript • Flutter Tools

• No issues found!
```

</details>

**Comment by VladyslavBondarenko** [comment] 2020-04-20 10:12
I can't reproduce it, tried to run with `master v1.18.0-6.0.pre.83` and with `dev 1.18.0-dev.5.0`.
From terminal and from Android Studio interface (although there is no difference how to run).

@ThinkDigitalSoftware isn't it your case? https://github.com/flutter/flutter/issues/51772

**Comment by ThinkDigitalSoftware** [comment] 2020-04-20 14:16
> I can't reproduce it, tried to run with `master v1.18.0-6.0.pre.83` and with `dev 1.18.0-dev.5.0`.
> From terminal and from Android Studio interface (although there is no difference how to run).
> 
> @ThinkDigitalSoftware isn't it your case? https://github.com/flutter/flutter/issues/51772

Ah, ok. And no, mine works after 20 tries and random "fixes". Like switching windows and typing and deleting text and pasting repeatedly

**Comment by ThinkDigitalSoftware** [comment] 2020-04-25 00:47
Just compiled this to release, sent it to another mac and tried to paste in the text field and couldn't make it run. Here's the project if you're interested in trying the exact setup.
https://github.com/ThinkDigitalSoftware/flutter_youtube_downloader

**Comment by stuartmorgan** [comment] 2020-06-04 19:23
Duplicate of https://github.com/flutter/flutter/issues/50650.

**Closed by stuartmorgan** 2020-06-04 19:23 UTC
Labels: a: desktop, a: text input, f: material design, framework, platform-mac

**Comment by ThinkDigitalSoftware** [comment] 2020-06-04 19:26
> Duplicate of #50650.

Thanks for tracking this down, @stuartmorgan
