### ISSUE TITLE
[tool_crash] RPCError

### ISSUE THREAD

**Issue by felipeGarciaDiaz** [flutter/flutter#155384] opened 2024-09-19 02:41 UTC
## Command
```
flutter run // In this case, using flutter run, then running it on chrome. this was occuring on Ubuntu 24.04 Linux Based OS.
```

## Steps to Reproduce
N/A

## Environmental Info 
this could be more helpful.
1. flutter run
2. run on chrome based browser
3. using ubuntu 24.04 linux os

## Logs
RPCError
```
#0      new _OutstandingRequest (package:vm_service/src/vm_service.dart:265:34)
#1      VmService._call.<anonymous closure> (package:vm_service/src/vm_service.dart:1771:25)
#2      VmService._call (package:vm_service/src/vm_service.dart:1783:8)
#3      VmService.callServiceExtension (package:vm_service/src/vm_service.dart:1733:14)
#4      FlutterVmService._checkedCallServiceExtension (package:flutter_tools/src/vmservice.dart:868:28)
#5      FlutterVmService.invokeFlutterExtensionRpcRaw (package:flutter_tools/src/vmservice.dart:887:49)
#6      FlutterVmService.flutterDebugDumpFocusTree (package:flutter_tools/src/vmservice.dart:645:50)
#7      ResidentHandlers.debugDumpFocusTree (package:flutter_tools/src/resident_runner.dart:777:53)
<asynchronous suspension>
#8      TerminalHandler.processTerminalInput (package:flutter_tools/src/resident_runner.dart:1837:7)
<asynchronous suspension>
```
```
[32m[✓][39m Flutter (Channel stable, 3.19.6, on Ubuntu 24.04.1 LTS 6.8.0-45-generic, locale en_US.UTF-8)
    [32m•[39m Flutter version 3.19.6 on channel stable at /opt/flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision 54e66469a9 (5 months ago), 2024-04-17 13:08:03 -0700
    [32m•[39m Engine revision c4cd48e186
    [32m•[39m Dart version 3.3.4
    [32m•[39m DevTools version 2.31.1

[31m[✗][39m Android toolchain - develop for Android devices
    [31m✗[39m Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at google-chrome

[32m[✓][39m Linux toolchain - develop for Linux desktop
    [32m•[39m Ubuntu clang version 18.1.3 (1ubuntu1)
    [32m•[39m cmake version 3.28.3
    [32m•[39m ninja version 1.11.1
    [32m•[39m pkg-config version 1.8.1

[33m[!][39m Android Studio (not installed)
    [32m•[39m Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[32m[✓][39m VS Code (version 1.93.1)
    [32m•[39m VS Code at /usr/share/code
    [32m•[39m Flutter extension version 3.96.0

[32m[✓][39m Connected device (2 available)
    [32m•[39m Linux (desktop) • linux  • linux-x64      • Ubuntu 24.04.1 LTS 6.8.0-45-generic
    [32m•[39m Chrome (web)    • chrome • web-javascript • Google Chrome 128.0.6613.137

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[33m![39m Doctor found issues in 2 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.67+67
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 54e66469a933b60ddf175f858f82eaeb97e48c8d
### Plugins
android_intent_plus-5.1.0
background_fetch-1.3.5
background_locator-1.6.12
camera-0.11.0+2
camera_android_camerax-0.6.5+2
camera_avfoundation-0.9.17+3
camera_web-0.3.5
connectivity_plus-6.0.5
file_picker-8.0.5
firebase_analytics-11.3.0
firebase_analytics_web-0.5.9+2
firebase_core-3.4.0
firebase_core_web-2.17.5
firebase_crashlytics-4.1.0
firebase_messaging-15.1.0
firebase_messaging_web-3.8.13
flutter_background_geolocation-4.15.5
flutter_background_service-5.0.10
flutter_background_service_android-6.2.7
flutter_background_service_ios-5.0.3
flutter_foreground_task-8.6.0
flutter_image_compress-2.3.0
flutter_image_compress_common-1.0.5
flutter_image_compress_macos-1.0.2
flutter_image_compress_ohos-0.0.3
flutter_image_compress_web-0.1.4+1
flutter_local_notifications-17.2.2
flutter_local_notifications_linux-4.0.1
flutter_plugin_android_lifecycle-2.0.19
flutter_secure_storage-9.2.2
flutter_secure_storage_linux-1.2.1
flutter_secure_storage_macos-3.1.2
flutter_secure_storage_web-1.2.1
flutter_secure_storage_windows-3.1.2
geocoding-3.0.0
geocoding_android-3.3.1
geocoding_ios-3.0.1
geolocator-12.0.0
geolocator_android-4.6.1
geolocator_apple-2.3.7
geolocator_web-4.0.0
geolocator_windows-0.2.3
google_maps_flutter-2.6.1
google_maps_flutter_android-2.8.0
google_maps_flutter_ios-2.13.0
google_maps_flutter_web-0.5.8
integration_test
maps_launcher-2.2.1
package_info_plus-8.0.2
path_provider-2.1.4
path_provider_android-2.2.4
path_provider_foundation-2.4.0
path_provider_linux-2.2.1
path_provider_windows-2.3.0
permission_handler-11.3.1
permission_handler_android-12.0.12
permission_handler_apple-9.4.5
permission_handler_html-0.1.3+2
permission_handler_windows-0.2.1
printing-5.12.0
shared_preferences-2.2.3
shared_preferences_android-2.2.2
shared_preferences_foundation-2.5.2
shared_preferences_linux-2.4.1
shared_preferences_web-2.4.1
shared_preferences_windows-2.4.1
system_clock-2.0.0
url_launcher-6.3.0
url_launcher_android-6.3.2
url_launcher_ios-6.3.1
url_launcher_linux-3.2.0
url_launcher_macos-3.2.0
url_launcher_web-2.3.3
url_launcher_windows-3.1.2

**Comment by danagbemava-nc** [comment] 2024-09-19 07:59
Closing this as a duplicate of https://github.com/flutter/flutter/issues/126362

**Closed by danagbemava-nc** 2024-09-19 07:59 UTC
Labels: in triage
