### ISSUE TITLE
[web] onTapLink not called on line that wraps

### ISSUE THREAD

**Issue by sgehrman** [flutter/flutter#81751] opened 2020-08-10 00:48 UTC
If a line is long enough to wrap, the onTapLink doesn't get called.

This is probably related to a known bug where text selection doesn't work on text that wraps

You can fix this (in release mode only) with this flag on build

flutter build web --release --dart-define=FLUTTER_WEB_USE_EXPERIMENTAL_CANVAS_TEXT=true

But even with this flag, it doesn't work.

**Comment by TahaTesser** [comment] 2021-09-02 14:06
Hi 
I can't reproduce the anymore too in debug mode or release modes on web

<img width="655" alt="Screenshot 2021-09-02 at 17 04 18" src="https://user-images.githubusercontent.com/48603081/131857991-cccdca98-ce51-4efa-98af-233b96396794.png">

```
safety: true
[  +93 ms] DevHandler: Debug service listening on ws://127.0.0.1:58221/BnR4nVaXRkI=/ws

[  +26 ms] This app is linked to the debug service: ws://127.0.0.1:58221/BnR4nVaXRkI=/ws
[   +8 ms] Debug service listening on ws://127.0.0.1:58221/BnR4nVaXRkI=/ws
[        ] 💪 Running with sound null safety 💪
[   +3 ms] 🔥  To hot restart changes while running, press "r" or "R".
[        ] For a more detailed help message, press "h". To quit, press "q".
[+4582 ms] link tapped
[+1987 ms] link tapped
[ +141 ms] link tapped
[ +141 ms] link tapped
[ +151 ms] link tapped
[ +142 ms] link tapped
```

`flutter_markdown: ^0.6.6`

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.2.3, on macOS 12.0 21A5506j darwin-x64, locale en-GB)
    • Flutter version 2.2.3 at /Users/tahatesser/Code/flutter_stable
    • Framework revision f4abaa0735 (9 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/tahatesser/Code/SDK
    • Platform android-31, build-tools 30.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/SDK
    • Java binary at: /Users/tahatesser/Code/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment Temurin-11.0.12+7 (build 11.0.12+7)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode-beta.app/Contents/Developer
    • Xcode 13.0, Build version 13A5212g
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 2020.3)
    • Android Studio at /Users/tahatesser/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7621141/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] VS Code (version 1.59.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (3 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • macOS (desktop)         • macos         • darwin-x64     • macOS 12.0 21A5506j darwin-x64
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 92.0.4515.159

! Doctor found issues in 1 category.
```

</details>


Closing as fixed. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-09-02 14:06 UTC
Labels: package, p: flutter_markdown
