### ISSUE TITLE
Pre-written Counter App Tests Fail 

### ISSUE THREAD

**Issue by adcaine** [flutter/flutter#47352] opened 2019-12-18 16:58 UTC
Steps to Reproduce:
1.  Open Android Studio
2.  Click on "Start a new Flutter" app.
3.  Without changing any of the code, run the given testWidgets test in widget_test.dart.

Expected Result:
The test runs and passes.

Actual:
The test throws an error:
```bash
Observatory listening on http://127.0.0.1:63053/h5cDF4N5S1k=/

../../development/flutter/packages/flutter/lib/src/material/animated_icons.dart:9:8: Error: Not found: 'dart:ui'
import 'dart:ui' as ui show Paint, Path, Canvas;
       ^
../../development/flutter/packages/flutter/lib/src/material/animated_icons.dart:10:8: Error: Not found: 'dart:ui'
import 'dart:ui' show lerpDouble;
       ^
../../development/flutter/packages/flutter/lib/src/material/app.dart:5:8: Error: Not found: 'dart:ui'
import 'dart:ui' as ui;
       ^
../../development/flutter/packages/flutter/lib/src/material/app_bar_theme.dart:5:8: Error: Not found: 'dart:ui'
import 'dart:ui' show lerpDouble;
       ^
../../development/flutter/packages/flutter/lib/src/material/arc.dart:6:8: Error: Not found: 'dart:ui'
import 'dart:ui' show lerpDouble;
       ^
../../development/flutter/packages/flutter/lib/src/material/bottom_app_bar_theme.dart:5:8: Error: Not found: 'dart:ui'
import 'dart:ui' show lerpDouble;
       ^
../../development/flutter/packages/flutter/lib/src/material/bottom_sheet_theme.dart:5:8: Error: Not found: 'dart:ui'
import 'dart:ui' show lerpDouble;
       ^
../../development/flutter/packages/flutter/lib/src/material/button_bar_theme.dart:5:8: Error: Not found: 'dart:ui'
import 'dart:ui' show lerpDouble;
       ^
../../development/flutter/packages/flutter/lib/src/material/card_theme.dart:5:8: Error: Not found: 'dart:ui'
import 'dart:ui' show lerpDouble;
       ^
../../development/flutter/packages/flutter/lib/src/material/chip_theme.dart:5:8: Error: Not found: 'dart:ui'
import 'dart:ui' show lerpDouble;
       ^
```

The test (not written by me) and given by Android Studio Reads

// This is a basic Flutter widget test.
//
// To perform an interaction with a widget in your test, use the WidgetTester
// utility that Flutter provides. For example, you can send tap and scroll
// gestures. You can also use WidgetTester to find child widgets in the widget
// tree, read text, and verify that the values of widget properties are correct.

```dart
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

import 'package:flutter_app_to_test/main.dart';

void main() {
  testWidgets('Counter increments smoke test', (WidgetTester tester) async {
    // Build our app and trigger a frame.
    await tester.pumpWidget(MyApp());

    // Verify that our counter starts at 0.
    expect(find.text('0'), findsOneWidget);
    expect(find.text('1'), findsNothing);

    // Tap the '+' icon and trigger a frame.
    await tester.tap(find.byIcon(Icons.add));
    await tester.pump();

    // Verify that our counter has incremented.
    expect(find.text('0'), findsNothing);
    expect(find.text('1'), findsOneWidget);
  });
}

```

**Comment by iapicca** [comment] 2019-12-19 13:39
Hi @adcaine 
can you please provide your `flutter doctor -v`?
Thank you

**Comment by adcaine** [comment] 2019-12-19 15:05
➜  examples git:(stable) flutter doctor -v
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.2 19C57,
    locale en-CA)
    • Flutter version 1.12.13+hotfix.5 at /Users/allancaine/development/flutter
    • Framework revision 27321ebbad (9 days ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/allancaine/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Community Edition (version 2019.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 42.0.4
    • Dart plugin version 193.5731

[!] VS Code (version 1.32.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[!] Connected device
    ! No devices available

**Comment by iapicca** [comment] 2019-12-19 16:20
Hi @adcaine 
I just tried running the test, but I cannot reproduce the issue you are describing;
if you just update flutter, you may want to run 
`flutter clean`
`flutter pub cache repair`

If the issue persist could you please provide your `flutter test --verbose`?
thank you

**Comment by adcaine** [comment] 2019-12-19 17:12
<img width="634" alt="Screen Shot 2019-12-19 at 11 48 28 AM" src="https://user-images.githubusercontent.com/3894339/71192085-a12f0800-2255-11ea-98aa-23a38c258553.png">

Hello,
I need to clarify the reproduction steps please.  Referring to the image above, I am clicking on the green triangle on line 14 from Android Studio.  Ctrl-Shift-R from my mac also reproduces the issue.   I did run the two commands you suggested above.  I also verified that Android Studio is up-to-date.

I did not know that the tests can be launched from the command line.  I've always been accustomed to running the tests via Android Studio.

From the command line, the result is

➜  flutter_app_to_test flutter test
00:02 +1: All tests passed!    

If it is expected that the tests should run and pass when launched in Android Studio, I believe that there may still be an issue here.  

I am grateful to you for your assistance.  I want to write tests for my submission to the Flutter Clock Challenge.  I am relieved to know that there's a way to launch tests.  

Thank you.

**Comment by jonahwilliams** [comment] 2020-01-09 06:44
This might be an issue specifically in android studio if it isn't delegating to flutter test, but it doesn't have anything to do with the flutter tool

**Comment by iapicca** [comment] 2020-01-09 06:52
@jonahwilliams 
should this issue be addressed here? https://github.com/flutter/flutter-intellij/issues
thanks

**Comment by iapicca** [comment] 2020-01-09 10:33
Hi @adcaine  
following the indication of [jetbrains' Flutter plugin](https://plugins.jetbrains.com/plugin/9212-flutter) 
the correct way to address the problem
is to open an issue on the dedicated [github](https://github.com/flutter/flutter-intellij/issues)

I apologize for not realizing sooner.

Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it.
Thank you for your understanding

**Closed by iapicca** 2020-01-09 10:33 UTC
