### ISSUE TITLE
[flutter_svg] Catching error or having an "error" placeholder

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#158785] opened 2024-11-13 18:17 UTC
_Imported from https://github.com/dnfield/flutter_svg/issues/1007_

Original report by @vd3d on Oct 30, 2023

Hi,

First thanks for the library :-)

I'm currently using "SvgPicture.network" with a placeholder, but when there are internet connection issues, I got an exception in the debug log.

But, the placeholder continues to animate, I would like to put a default icon or just an empty one.

I have see multiples requests like mines:
https://github.com/dnfield/vector_graphics/pull/196#commits-pushed-40ee8bb
https://github.com/dnfield/flutter_svg/issues/881

... and more...

I have the feeling it has been implemented, or partially, but I can't figure out how I can handle such cases (which are commons)

Thanks for your help

PS: I haven't find any solution on this forum, sorry

---
Comment by @animator on Dec 16, 2023
+1 .. kindly add an error builder.

---
Comment by @alexda12 on Dec 27, 2023
@animator @vd3d Instead of waiting for an errorBuilder property to be added, you can actually handle this yourself by bypassing svgPicture.network, handle the loading of the URL yourself via DIO or Http package and then return an SvgPicture yourself from the http get request. if there is an exception you can trap this and handle appropriately - i.e add a retry button to re-load the resource , in situations where there is no network. This approach with Riverpod for caching works a treat and means there is absolutely no need to use svgPicture.network.

---
Comment by @animator on Jan 6, 2024
@alexda12 I am using SVG string which can be a faulty SVG XML string. Thus, the need of an error builder in case there is any issue in parsing or rendering. This has nothing to do with network.

---
Comment by @amake on Oct 1, 2024
I see that `createCompatVectorGraphic` takes an `errorBuilder`; it would be great if you could expose that as an argument to `SvgPicture`.

---
Comment by @amake on Oct 2, 2024
I see now that this is basically a duplicate of #996.

For my purposes I need that, and https://github.com/dnfield/vector_graphics/pull/255 addressed.

**Comment by jonahwilliams** [comment] 2024-11-20 16:34
Duplicate of https://github.com/flutter/flutter/issues/158780

**Closed by jonahwilliams** 2024-11-20 16:34 UTC
Labels: package, P3, p: flutter_svg
