### ISSUE TITLE
E/FirebaseInstanceId: Topic sync or token retrieval failed on hard failure exceptions: AUTHENTICATION_FAILED. Won't retry the operation.

### ISSUE THREAD

**Issue by sandroarnaldo** [flutter/flutter#63290] opened 2020-08-08 14:40 UTC
08/08 11:25:25: Launching 'app' on Pixel 3a XL API 30.
$ adb shell am start -n "br.com.colorsdj.colorsdj/br.com.colorsdj.colorsdj.MainActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -D
Waiting for application to come online: br.com.colorsdj.colorsdj.test | br.com.colorsdj.colorsdj
Waiting for application to come online: br.com.colorsdj.colorsdj.test | br.com.colorsdj.colorsdj
Waiting for application to come online: br.com.colorsdj.colorsdj.test | br.com.colorsdj.colorsdj
Waiting for application to come online: br.com.colorsdj.colorsdj.test | br.com.colorsdj.colorsdj
Connected to process 5656 on device 'Pixel_3a_XL_API_30 [emulator-5554]'.
Waiting for application to come online: br.com.colorsdj.colorsdj.test | br.com.colorsdj.colorsdj
Connecting to br.com.colorsdj.colorsdj
Connected to the target VM, address: 'localhost:8608', transport: 'socket'
Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
I/lorsdj.colorsd: Not late-enabling -Xcheck:jni (already on)
I/lorsdj.colorsd: Unquickening 12 vdex files!
W/lorsdj.colorsd: Unexpected CPU variant for X86 using defaults: x86
W/ActivityThread: Application br.com.colorsdj.colorsdj is waiting for the debugger on port 8100...
I/System.out: Sending WAIT chunk
I/System.out: Debugger has connected
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: debugger has settled (1342)
D/ApplicationLoaders: Returning zygote-cached class loader: /system/framework/android.test.base.jar
W/lorsdj.colorsd: Suspending all threads took: 436.816ms
D/NetworkSecurityConfig: No Network Security Config specified, using platform default
D/NetworkSecurityConfig: No Network Security Config specified, using platform default
V/FA: Registered activity lifecycle callback
I/FirebaseInitProvider: FirebaseApp initialization successful
I/lorsdj.colorsd: Waiting for a blocking GC ClassLinker
W/DynamiteModule: Local module descriptor class for com.google.firebase.auth not found.
W/lorsdj.colorsd: Accessing hidden method Landroid/content/Context;->getFeatureId()Ljava/lang/String; (greylist, reflection, allowed)
I/TetheringManager: registerTetheringEventCallback:br.com.colorsdj.colorsdj
W/lorsdj.colorsd: Verification of void com.google.android.gms.measurement.internal.zzey.zzaa() took 152.408ms (5603.34 bytecodes/s) (11976B approximate peak alloc)
W/lorsdj.colorsd: Verification of void com.google.android.gms.signin.SignInOptions.<clinit>() took 165.874ms (138.66 bytecodes/s) (1056B approximate peak alloc)
I/lorsdj.colorsd: WaitForGcToComplete blocked ClassLinker on ClassLinker for 715.250ms
W/lorsdj.colorsd: Verification of java.util.List com.google.android.gms.measurement.internal.zzex.zza(int) took 191.986ms (3453.36 bytecodes/s) (13752B approximate peak alloc)
W/lorsdj.colorsd: Verification of com.google.android.gms.common.internal.ClientSettings com.google.android.gms.common.internal.ClientSettings.createDefault(android.content.Context) took 420.888ms (23.76 bytecodes/s) (816B approximate peak alloc)
W/lorsdj.colorsd: Verification of void com.google.android.gms.measurement.internal.zzis.zzal() took 167.864ms (440.83 bytecodes/s) (1824B approximate peak alloc)
W/lorsdj.colorsd: Verification of boolean com.google.android.gms.common.stats.ConnectionTracker.zza(android.content.Context, java.lang.String, android.content.Intent, android.content.ServiceConnection, int) took 144.914ms (234.62 bytecodes/s) (1256B approximate peak alloc)
W/lorsdj.colorsd: Verification of void com.google.android.gms.measurement.internal.zzis.zza(com.google.android.gms.internal.measurement.zzn, java.lang.String, java.lang.String) took 478.345ms (52.26 bytecodes/s) (1144B approximate peak alloc)
D/libEGL: loaded /vendor/lib/egl/libEGL_emulation.so
D/libEGL: loaded /vendor/lib/egl/libGLESv1_CM_emulation.so
D/libEGL: loaded /vendor/lib/egl/libGLESv2_emulation.so
W/DynamiteModule: Local module descriptor class for com.google.firebase.auth not found.
I/ResourceExtractor: Resource version mismatch res_timestamp-1-1596896767682
V/FA: onActivityCreated
I/lorsdj.colorsd: Waiting for a blocking GC ProfileSaver
I/lorsdj.colorsd: WaitForGcToComplete blocked ProfileSaver on RunEmptyCheckpoint for 96.438ms
W/lorsdj.colorsd: Verification of void com.google.android.gms.common.zzi.<clinit>() took 144.379ms (235.49 bytecodes/s) (1168B approximate peak alloc)
I/FirebaseAuth: [FirebaseAuth:] Preparing to create service connection to gms implementation
W/lorsdj.colorsd: Verification of void com.google.android.gms.measurement.internal.zzap.<clinit>() took 357.124ms (4026.61 bytecodes/s) (14264B approximate peak alloc)
W/lorsdj.colorsd: Verification of java.lang.Boolean com.google.android.gms.measurement.internal.zzap.zzaw() took 211.837ms (42.49 bytecodes/s) (792B approximate peak alloc)
W/lorsdj.colorsd: Verification of java.lang.Double com.google.android.gms.measurement.internal.zzap.zzbo() took 176.698ms (50.93 bytecodes/s) (792B approximate peak alloc)
W/lorsdj.colorsd: Verification of void com.google.android.gms.internal.measurement.zzkp.<clinit>() took 110.330ms (72.51 bytecodes/s) (744B approximate peak alloc)
V/FA: App measurement collection enabled
V/FA: App measurement enabled for app package, google app id: br.com.colorsdj.colorsdj, 1:910602100644:android:520a4c87f1a7eba0106b31
I/FA: App measurement initialized, version: 21028
    To enable debug logging run: adb shell setprop log.tag.FA VERBOSE
    To enable faster debug mode event logging run:
      adb shell setprop debug.firebase.analytics.app br.com.colorsdj.colorsdj
D/FA: Debug-level message logging enabled
V/FA: Persisting first open: 1596896780695
V/FA: App measurement setting deferred collection: false
V/FA: Checking service availability
V/FA: Service available
V/FA: Connecting to remote service
V/FA: Detected application was in foreground
V/FA: Session started, time: 515221
V/FA: Connection attempt already in progress
I/FA: Tag Manager is not found and thus will not be used
I/ResourceExtractor: Extracted baseline resource assets/flutter_assets/kernel_blob.bin
I/ResourceExtractor: Extracted baseline resource assets/flutter_assets/vm_snapshot_data
V/FA: Connection attempt already in progress
I/ResourceExtractor: Extracted baseline resource assets/flutter_assets/isolate_snapshot_data
V/FA: Connection attempt already in progress
D/HostConnection: HostConnection::get() New Host Connection established 0xe8e79cd0, tid 5656
D/HostConnection: HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_YUV_Cache ANDROID_EMU_async_unmap_buffer GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_gles_max_version_3_0 
D/EGL_emulation: eglCreateContext: 0xe8c6b580: maj 3 min 0 rcv 3
D/EGL_emulation: eglCreateContext: 0xe8c6b970: maj 3 min 0 rcv 3
D/HostConnection: HostConnection::get() New Host Connection established 0xe8e7a510, tid 6034
D/HostConnection: HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_YUV_Cache ANDROID_EMU_async_unmap_buffer GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_gles_max_version_3_0 
D/EGL_emulation: eglMakeCurrent: 0xe8c6b970: ver 3 0 (tinfo 0xba2fe3d0) (first time)
I/lorsdj.colorsd: Waiting for a blocking GC ClassLinker
I/lorsdj.colorsd: WaitForGcToComplete blocked ClassLinker on HeapTrim for 5.689ms
W/ContextImpl: Failed to ensure /storage/emulated/0/Android/data/br.com.colorsdj.colorsdj/files/Pictures: android.os.ServiceSpecificException:  (code -1)
I/flutter: Observatory listening on http://127.0.0.1:46527/n6jwY2m01L0=/
W/lorsdj.colorsd: Accessing hidden method Landroid/view/accessibility/AccessibilityNodeInfo;->getSourceNodeId()J (greylist,test-api, reflection, allowed)
W/lorsdj.colorsd: Accessing hidden method Landroid/view/accessibility/AccessibilityRecord;->getSourceNodeId()J (greylist, reflection, allowed)
    Accessing hidden field Landroid/view/accessibility/AccessibilityNodeInfo;->mChildNodeIds:Landroid/util/LongArray; (greylist, reflection, allowed)
    Accessing hidden method Landroid/util/LongArray;->get(I)J (greylist, reflection, allowed)
V/FA: Activity resumed, time: 517566
D/HostConnection: HostConnection::get() New Host Connection established 0xe8e7b1d0, tid 5822
D/HostConnection: HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_YUV_Cache ANDROID_EMU_async_unmap_buffer GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_gles_max_version_3_0 
W/OpenGLRenderer: Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
D/EGL_emulation: eglCreateContext: 0xe8c6b5f0: maj 3 min 0 rcv 3
D/EGL_emulation: eglMakeCurrent: 0xe8c6b5f0: ver 3 0 (tinfo 0xb5642030) (first time)
I/Gralloc4: mapper 4.x is not supported
D/HostConnection: createUnique: call
D/HostConnection: HostConnection::get() New Host Connection established 0xe8e77690, tid 5822
D/goldfish-address-space: allocate: Ask for block of size 0x100
    allocate: ioctl allocate returned offset 0x3fcb0d000 size 0x2000
D/HostConnection: HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_YUV_Cache ANDROID_EMU_async_unmap_buffer GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_gles_max_version_3_0 
D/HostConnection: HostConnection::get() New Host Connection established 0xe8e77210, tid 6033
D/HostConnection: HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_YUV_Cache ANDROID_EMU_async_unmap_buffer GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_gles_max_version_3_0 
D/EGL_emulation: eglMakeCurrent: 0xe8c6b580: ver 3 0 (tinfo 0xb5642610) (first time)
W/lorsdj.colorsd: Verification of void com.google.android.gms.common.internal.zzc.<clinit>() took 163.555ms (48.91 bytecodes/s) (872B approximate peak alloc)
I/lorsdj.colorsd: Background young concurrent copying GC freed 3176(332KB) AllocSpace objects, 0(0B) LOS objects, 6% free, 2951KB/3170KB, paused 7.040ms total 653.148ms
V/FA: Connection attempt already in progress
V/FA: Connection attempt already in progress
I/Choreographer: Skipped 79 frames!  The application may be doing too much work on its main thread.
E/FirebaseInstanceId: Topic sync or token retrieval failed on hard failure exceptions: AUTHENTICATION_FAILED. Won't retry the operation.
D/FA: Connected to remote service
V/FA: Processing queued up service tasks: 6
I/flutter: Error signing in: PlatformException(sign_in_required, com.google.android.gms.common.api.ApiException: 4: 4: , null)
V/FA: Inactivity, disconnecting from the service
V/FA: Recording user engagement, ms: 22600
V/FA: Connecting to remote service
V/FA: Activity paused, time: 540135
V/FA: onActivityCreated
V/FA: Connection attempt already in progress
V/FA: Activity resumed, time: 540530
E/FirebaseInstanceId: Topic sync or token retrieval failed on hard failure exceptions: AUTHENTICATION_FAILED. Won't retry the operation.
E/FirebaseInstanceId: Topic sync or token retrieval failed on hard failure exceptions: AUTHENTICATION_FAILED. Won't retry the operation.
V/FA: Connection attempt already in progress
V/FA: Connection attempt already in progress
V/FA: Recording user engagement, ms: 2619
V/FA: Connection attempt already in progress
    Activity paused, time: 540600
D/FA: Connected to remote service
V/FA: Processing queued up service tasks: 5
E/FirebaseInstanceId: Topic sync or token retrieval failed on hard failure exceptions: AUTHENTICATION_FAILED. Won't retry the operation.
D/FA: Application going to the background
E/FirebaseInstanceId: Topic sync or token retrieval failed on hard failure exceptions: AUTHENTICATION_FAILED. Won't retry the operation.
V/FA: Inactivity, disconnecting from the service

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.20.1, on Mac OS X 10.15.5 19F101, locale pt-BR)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
[✓] Android Studio (version 4.0)
[✓] IntelliJ IDEA Community Edition (version 2020.2)
[✓] Connected device (1 available)

• No issues found!

**Comment by TahaTesser** [comment] 2020-08-10 12:23
Hi @sandroarnaldo 
From what I can see, the issue is related to a FlutterFire plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by TahaTesser** 2020-08-10 12:23 UTC
