### ISSUE TITLE
Support for debugging on Firefox

### ISSUE THREAD

**Issue by NatoBoram** [flutter/flutter#76310] opened 2021-02-18 15:39 UTC
## Use case

Sometimes, there's JavaScript errors occurring in Firefox that would strongly benefit from having a debugger. At the moment, the only way to use a debugger are gatekeeped to Chromium.

* `flutter run -d chrome`
* `flutter run -d edge`
* `flutter run -d web-server` and install [Dart Debug Extension](https://chrome.google.com/webstore/detail/dart-debug-extension/eljbmlghnomdjgdjmbdekegdkbabckhm) https://github.com/dart-lang/webdev/issues/1224

## Proposal

Support Firefox as a web device and enable debugging on Firefox.

* `flutter run -d firefox`

**Comment by jonahwilliams** [comment] 2021-02-19 05:18
Duplicate of https://github.com/flutter/flutter/issues/55324

**Closed by jonahwilliams** 2021-02-19 05:18 UTC
