### ISSUE TITLE
Rejected from playstore for request_install_packages permission

### ISSUE THREAD

**Issue by pranavskeintech** [flutter/flutter#117567] opened 2022-12-23 01:37 UTC
We found that your app is not compliant with how REQUEST_INSTALL_PACKAGES permission is allowed to be used. Specifically, the use of the permission is not directly related to the core purpose of the app.

**Comment by darshankawar** [comment] 2022-12-23 07:00
@pranavskeintech 
This does not look specific to Flutter only and could be happening because one of the plugins you are using could be using the said permission, so you'll need to check that in your project.
See a similar [issue](https://stackoverflow.com/questions/73924613/app-is-not-compliant-with-how-request-install-packages-permission-is-allowed) on SO and check if it helps in your case.

Closing from here, as this is not a bug in flutter framework.

**Closed by darshankawar** 2022-12-23 07:00 UTC
Labels: in triage
