### ISSUE TITLE
goma failures are hard to detect and debug

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#68248] opened 2020-10-15 22:56 UTC
The engine tree was closed for quite a while today because all the Windows goma builds were failing, falling back to local builds, taking too long, and then timing out. Several significant process and tooling issues came up during this process:
1. It was not at all clear to the Flutter sheriff, or anyone else looking at the bots without knowing exactly what to look for already, to understand that the failures were goma-related.
2. There was no way (AFAICT) for anyone on the Flutter team to see the actual goma errors.
3. There was not a good communication channel to the sheriff about this (I got looped in because it involved Windows, and then was relaying information back to the sheriff manually)
4. Apparently these failures had been happening for an unknown amount of time (causing unnecessarily long build times), and were only eventually noticed because of a change in bot timeouts.

While today's specific issue is on the path to resolution, we should address the meta issues here. Some of my initial thoughts on each:
1. Can we more clearly surface significant numbers of remote goma failures--in this case, *every* attempt to compile via goma remotely would fail--on bots, rather than them being hidden by the local fallback?
2. Can we surface the actual remote errors on the bots? (Reference was made in discussion to us not having a `read goma_client warning log` step.)
3. It seems like there's likely room for process improvement in infra and/or sheriff playbooks to make sure that infra issues are communicated directly to the sheriff.
4. Is there monitoring we should be doing on bot build times that would cause us to quickly notice sustained increases that don't hit the threshold of timeouts?

/cc @godofredoc @gaaclarke @cbracken @zanderso

**Comment by cbracken** [comment] 2020-10-15 22:59
Related x-ref bug: https://bugs.fuchsia.dev/p/fuchsia/issues/detail?id=62070

**Comment by cbracken** [comment] 2020-10-15 23:44
> There was no way (AFAICT) for anyone on the Flutter team to see the actual goma errors.

It would be good to follow up with whoever diagnosed this upstream on the Chromium side of things -- somehow they discovered what was going on. Ideally goma itself would detect bad conditions and emit a warning that can be detected.

Given that Goma itself is an optimisation, it would be nice if we continued to produce builds (albeit with higher latency) if the failure scenario is that goma is unable to make use of its cache. I'm not sure how to square this with also alerting loudly so that the problem gets escalated and fixed.

> There was not a good communication channel to the sheriff about this (I got looped in because it involved Windows, and then was relaying information back to the sheriff manually)

There are a few changes here that might be valuable:
1. Find out if there's a mailgroup where significant changes to LUCI/goma/other infra are announced ahead of time and have the sheriff monitor that (e.g. daily) as part of the rota responsibilities.
2. When such a change is planned; it should be documented and part of the sheriff handover from whichever sheriff learned of the change to whichever one will be active during the change. Maybe an entry in a shared calendar?
3. If there's a chat room for live infra support for such changes, the sheriff should be responsible for monitoring it during the rollout.

I suspect all three of these things probably exist and we just don't know about them yet :) 

> Apparently these failures had been happening for an unknown amount of time (causing unnecessarily long build times), and were only eventually noticed because of a change in bot timeouts.

Some kind of monitoring of build latency stats over time would be handy here. Our current monitoring is effectively a binary state (build is green / build blew its timeout and the tree is closed) where the notification (infra flake that closes the tree) shuts down our ability to land any changes or produce a build. If we needed to land a patch to fix a major bug on master, we'd be completely out of luck, which is pretty extreme.

**Comment by stuartmorgan** [comment] 2020-10-16 04:04
> Given that Goma itself is an optimisation, it would be nice if we continued to produce builds (albeit with higher latency) if the failure scenario is that goma is unable to make use of its cache.

To clarify, the issue wasn't related to caching. What happened was that (remote) goma builds for Windows completely broke for us, so any time a file actually needed to be compiled (i.e., wasn't in that bot's local cache) it would try to compile remotely, that would fail, and then it would nearly-silently fall back to local compiles, which would succeed. If we had a longer timeout, everything would have stayed green, just suddenly much slower.

> Since goma is really just an optimisation, I'd be hesitant to have goma failures trigger a tree closure automatically

Failing the build isn't necessarily the only option; I was thinking that maybe we could have something more prominently show up in the bot build UI somehow. E.g., is there a way to make a step purple but not fail the overall build, so that if someone clicked on a bot to see why it was slow it would jump out as an obvious issue?

(The current approach is that you have to suspect that it's a goma remote failure, go into a post-goma step, then the stats sub-step, open its output, and look at output like:
```
using C:\b\s\w\ir\k\recipe_cleanup\goma as tmpdir
request: total=931 success=9 failure=0
 compiler_proxy: fail=0
 compiler_info: stores=5 store_dups=0 miss=0 fail=0
 goma: finished=922 cache_hit=0 local_cachehit=0 aborted=8 retry=0 fail=922
 fallback_in_setup:
  parse_fail=0 no_remote=0 http_disabled=0
  compiler_info_fail=0 compiler_disabled=0 requested_by_user=0 update_required_files=0
[...]
```
and see that the in that sea of numbers, the `fail` and `finished` numbers are the same. Totally doable if you know exactly how to do it, basically impossible to discover otherwise.)

**Comment by gaaclarke** [comment] 2020-10-16 06:58
Is there a git repro that controls what version of the code the goma infra is running?  If so, could we setup our LUCI to track that repo as well so that commits to that repo will also trigger our post-commit builds?  That way breaks in goma won't be associated with our commits and we'll find out about them faster.  With how things are currently setup there is no record of the break or the fix when looking through our history.  I'd expand this idea to any infra that the engine depends on.

**Comment by godofredoc** [comment] 2020-10-16 16:19
To expand the information here, GOMA services were not broken. It was the specific interaction of Flutter Windows builds with GOMA services that was broken.

GOMA has several components: a recipe wrapper that setups the environment, a client that communicates over grpc with a backend, a backend that distributes work, pool of vms, etc. I would recommend to treat goma as a blackbox service with a given SLO, this allows us to focus on what it is under Flutter's control.

Some ideas:
* Audit the current builds. Is GOMA being used efficiently in all the other platforms?
* Document how to validate goma is being used in new builds and how to verify it.
* Monitor our builds, create dashboards that present the execution time for the different builds and alert if one or many of them exceed a given threshold.
* Update the recipe to present the goma stats in an easier way to understand.
* Subscribing to GOMA RBE announcements and ensure that we are aware of their current SLO.

**Comment by gaaclarke** [comment] 2020-10-16 16:53
> To expand the information here, GOMA services were not broken. It was the specific interaction of Flutter Windows builds with GOMA services that was broken.

Right, semantics.  The interaction between flutter and goma is the kind of broken we care about.

> GOMA has several components: a recipe wrapper that setups the environment, a client that communicates over grpc with a backend, a backend that distributes work, pool of vms, etc. I would recommend to treat goma as a blackbox service with a given SLO, this allows us to focus on what it is under Flutter's control.

Are all those components not coordinated atomically?  Even a black box we should track to know if it is working.  The problem is that we have dependencies that dictate wether our builds succeed or not but they aren't being tracked the same way changes to our code are.  If you want the sheriff's help monitoring these problems you should present the information in the language the sheriff already knows, ie entries in LUCI.

> Update the recipe to present the goma stats in an easier way to understand.

I like this idea.

> Audit the current builds. Is GOMA being used efficiently in all the other platforms?
> Document how to validate goma is being used in new builds and how to verify it.

Does the infra team have a playbook like the engine team does about things they are monitoring?

**Comment by godofredoc** [comment] 2020-10-16 17:46
Yes, [here is the link](https://g3doc.corp.google.com/company/teams/flutter/infra_metrics.md?cl=head).

The link lists the SLOs and metrics being collected. The information in the bottom is for the bi-weekly meeting  where we check the SLOs and correlate the failing ones with bugs. The meeting notes contain the history of what have been tracked and fixed in the last few months.

I would recommend to move the Infra SLOs meeting to a weekly cadence and that the engine sheriff joins that meeting to provide input on what metrics are missing and which issues were seen during the week.

**Comment by godofredoc** [comment] 2020-10-20 16:40
Goma issue has been solved, what are the next steps for this bug?

**Comment by stuartmorgan** [comment] 2020-10-20 17:00
> what are the next steps for this bug?

My initial report highlighted four areas I thought we should address, and there have been various suggestions (some high level, some concrete) for them in the discussion. We should probably start splitting out targeted issues for the suggestions we want to implement, and/or specific problems that we believe are worth investigating further but don't have a specific solution to yet.

**Comment by godofredoc** [comment] 2023-06-13 18:55
Closing because the bug has not been updated for more than one year.

Feel free to reopen any bugs that you believe are important but please provide updates on how to resource the fix of the bug and what can be done to prevent the issue from not getting updates for another year.

**Comment by zanderso** [comment] 2023-06-20 17:19
Re-opening since this still looks like a valid issue.

**Comment by godofredoc** [comment] 2023-06-20 18:08
This bug is not actionable from the infra point of view as we don't own the module. Any recommendations about the next steps?

**Comment by zanderso** [comment] 2023-06-20 18:14
In the initial report (1), (2), and (4) are actionable by the infra team. Even if forking the goma module is not a viable option *today*, the issues that it would solve are still valid, and so this issue should be left open.

**Comment by godofredoc** [comment] 2023-06-20 18:55
Setting expectations for this bug:

* GOMA module is owned by fuchsia team and is deprecated. Feature requests may not get traction.
* Fixes for (1) and (4) require the fuchsia team to implement the new functionality.
* (2) these are goma server logs that require a deep understanding of goma even if flutter had access it may not be able to correlate with the failures.

For the reasons above the bug is not actionable from Flutter Infra.

**Comment by stuartmorgan** [comment] 2023-06-20 19:19
Why would (4) require fuchsia team to implement anything? The suggestion there is an alerting system that would let us know if there is a sustain, significant uptick in the amount of time builds take on our CI.

**Comment by keyonghan** [comment] 2023-07-27 18:13
Some context: we are planning to deprecate goma EOY, and switch to Reclient.

**Comment by godofredoc** [comment] 2023-08-22 01:58
Closing this bug as obsolete as we are already working on the migration to RBE and there are no plans to improve logging in the deprecated goma services or modules.

**Closed by godofredoc** 2023-08-22 01:58 UTC
Labels: team-infra, P3, triaged-infra
