### ISSUE TITLE
flutter gives low frame rates when long lists with list builder inside cards giving(avg 20-35fps)

### ISSUE THREAD

**Issue by Ejdersoy** [flutter/flutter#35592] opened 2019-07-04 12:45 UTC
flutter i have list view builder that builder, build items 150 times.so this is okey if i m using only list tile inside listview. but its not seems good. i m trying to use card inside that builder. card=>material=>InkWell=>ListTile 

and this is gives very very low fps. im learning flutter for only perfromance . but if some one not fix this i will back ionic maybe react native.

**Comment by Ejdersoy** [comment] 2019-07-04 12:47
list page has 34 fps and detail page 12-15 fps

**Comment by kafein** [comment] 2019-07-04 18:57
#22314 might be related 
Please add the output of **flutter doctor -v** and provide a minimal demo of the problem.

**Comment by InvertedX** [comment] 2019-07-10 07:48
![image](https://user-images.githubusercontent.com/6897265/60950336-90787e80-a314-11e9-93fe-b34dc9a3bbb8.png)
I think this issue is happening on last few builds. i tried latest [v1.7.8+hotfix.3](https://github.com/flutter/flutter/releases/tag/v1.7.8%2Bhotfix.3), i got the above frame rate, i tested this on a fresh project (Counter example)

i downgraded flutter to 1.6.2, which i don't see any issues 


<details>
<summary>Details</summary>

[✓] Flutter (Channel v1.7.8-hotfixes, v1.7.8+hotfix.3, on Mac OS X 10.14.5 18F132, locale en-IN)
    • Flutter version 1.7.8+hotfix.3 at /Users/sarath/flutter
    • Framework revision b712a172f9 (12 hours ago), 2019-07-09 13:14:38 -0700
    • Engine revision 54ad777fd2
    • Dart version 2.4.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/sarath/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/sarath/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    ! CocoaPods out of date (1.6.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds
        to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade:
        brew upgrade cocoapods
        pod setup

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.2.8)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 34.0.1
    • Dart plugin version 182.5215

[✓] VS Code (version 1.36.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.2.0

[✓] Connected device (4 available)
    • ONEPLUS A6000             • c8166160      • android-arm64  • Android 9 (API 28)
    • Android SDK built for x86 • emulator-5554 • android-x86    • Android 8.1.0 (API 27)
      (emulator)
    • macOS                     • macOS         • darwin-x64     • Mac OS X 10.14.5 18F132
    • web                       • web           • web-javascript • Google Chrome 75.0.3770.100 


</details>

**Comment by KlausJokinen** [comment] 2019-07-12 21:24
I'm having exact same issue on v1.7.8+hotfix.3 build

**Comment by BondarenkoStas** [comment] 2019-10-01 12:29
@Ejdersoy how is it while using current stable v1.9.1+hotfix.2?
Please provide  a small self-contained app that demonstrates the problem. You can include small examples [inline if they're enclosed by backticks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks), or just provide a public link to a github "gist" - https://gist.github.com/.

**Comment by iapicca** [comment] 2019-11-08 15:56
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.

https://github.com/flutter/flutter/issues/31303

**Comment by Ejdersoy** [comment] 2019-12-14 22:14
![Ekran Alıntısı](https://user-images.githubusercontent.com/20680870/70855194-d1824980-1ed7-11ea-9c0c-f276b9abbf53.PNG)

as you can see there is an error in every frame . and i never saw 60 fps inside my flutter app. i will gave you an example of my code but i dont know what cousing that.

**Comment by Ejdersoy** [comment] 2019-12-14 22:44
[low-fps-flutter-(30-50).zip](https://github.com/flutter/flutter/files/3964414/low-fps-flutter-.30-50.zip)

this is the projects assets and main.dart files just test my code you will see fps is stuttering.

**Comment by Ejdersoy** [comment] 2019-12-14 22:49
![Ekran Alıntısı](https://user-images.githubusercontent.com/20680870/70855504-ca116f00-1edc-11ea-8d10-bd9c0a233435.PNG)

it is not fixed at 60 fps as seen.

**Comment by Ejdersoy** [comment] 2019-12-27 12:36
Im starting to learn react native. Flutter doesnt provide high frame rates as they say.

**Comment by liyuqian** [comment] 2020-02-05 10:19
@goderbauer : can you please have a quick test using Moto G4 and the reproduction app in https://github.com/flutter/flutter/issues/35592#issuecomment-565759602 ? If the bottleneck is on the UI thread, we can check more on the framework side; if the bottleneck is on the GPU thread, we can check more on the engine side.

**Comment by Ejdersoy** [comment] 2020-02-06 08:45
i think the bottleneck is both sides. i test it on j7elte

**Comment by liyuqian** [comment] 2020-02-14 22:22
As I'm still quarantined at home, I don't have a low-end device so I tested on my pixel 2 with the following discoveries.

1. `placeholder: 'assets/loading.gif'` inside `FadeInImage.assetNetwork` is causing Flutter to rebuild a lot of widgets even if those gifs seem to be offscreen. Flutter also seem to be only animating those gifs (offscreen) without loading the network images so such rebuild just goes on indefinitely. This is causing big problems in the UI thread.

2. `Card` widget generates a `PhysicalShapeLayer` whose shadows can't be cached by our picture raster cache.  This issue is not as critical as the first one as my pixel 2 still manages to rasterize each frame within 10ms in the GPU thread. But this could be a bigger problem on a low end device.

CC framework team @goderbauer @dnfield to further triage issue 1. For issue 2, we have some plan in https://github.com/flutter/flutter/issues/23535 and https://github.com/flutter/flutter/issues/32662 which are actively worked on by @flar.

Below is a comparison between having gif and not having gif (replacing the gif with a jpg placeholder):
![flutter_02](https://user-images.githubusercontent.com/22987568/74573235-350b1080-4f35-11ea-9b41-6501d025da02.png)
![flutter_03](https://user-images.githubusercontent.com/22987568/74573242-376d6a80-4f35-11ea-82b9-73f6387a5d69.png)

**Comment by dnfield** [comment] 2020-02-14 23:17
I think I figured out the gif thing.  In the frame builder for FadeInNetworkImage, we should be checking if the frame is not null - we're only checking if it was synchronously loaded right now.  Need to validate that some more.

**Comment by liyuqian** [comment] 2020-02-15 00:10
Great. Thank you @dnfield ! Please feel free to open a separate issue dedicated to the gif problem after the validation.

**Comment by dnfield** [comment] 2020-02-15 00:17
Filed https://github.com/flutter/flutter/pull/50842 to help with the builds.

**Comment by dnfield** [comment] 2020-02-15 00:18
Not sure if we really need a separate issue or not, but can file one if you prefer.

**Comment by liyuqian** [comment] 2020-02-15 00:27
@dnfield I"m also Ok with not having a separate issue. In https://github.com/flutter/flutter/pull/50842, can you please also add a performance test that reproduces this list of cards with `FadeInImage` that uses gif placeholder? I think it might be a common use case worth benchmarking. It will also validate the fix's performance impact.

**Comment by dnfield** [comment] 2020-02-15 00:41
I would rather add the performance test separately, so that if it turns out to be flaky we can revert it separately, but adding such a test is fair.

**Comment by dnfield** [comment] 2020-02-15 03:53
Test in #50851

**Comment by dnfield** [comment] 2020-02-18 19:30
@Ejdersoy - can you retry on master? The performance should be greatly improved for this now.

@liyuqian - do we still need this bug for any BDF related tracking, or are there other bugs open for that?

**Comment by liyuqian** [comment] 2020-02-26 23:09
Created https://github.com/flutter/flutter/issues/51515 for the `PhysicalShapeLayer` raster cache. Will close this issue and continue our discussion there once the `FadeInImage` issue fix is confirmed here.

**Comment by kf6gpe** [comment] 2020-03-16 22:17
Believe fixed; closing.

**Closed by kf6gpe** 2020-03-16 22:17 UTC
Labels: customer: crowd, framework, perf: speed, severe: performance, waiting for customer response
