### ISSUE TITLE
App Crash on release android 5

### ISSUE THREAD

**Issue by mjafartp** [flutter/flutter#65447] opened 2020-09-09 05:27 UTC
## Steps to Reproduce

1. released app bundle run on Android 5

<details>
  <summary>Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{xxx.xxxxxx.xxx/xxx.xxxxxx.xxx.MainActivity}: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/xxx.xxxxxx.xxx-1/base.apk"],nativeLibraryDirectories=[/data/app/xxx.xxxxxx.xxx-1/lib/arm, /vendor/lib, /system/lib]]] couldn't find "libflutter.so"
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2330)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2392)
       at android.app.ActivityThread.access$800(ActivityThread.java:156)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1308)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5314)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:374)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)</summary>

**Comment by softmarshmallow** [comment] 2020-09-09 06:22
1. submit `flutter doctor -v`
2. submit your pubspec
3. run it on other platform to see if it's pub related issue.
4. your log has no helpful information to be helped.

**Comment by darshankawar** [comment] 2020-09-09 08:07
@mjafartp,
Please provide `flutter doctor -v` and a minimal complete reproducible code sample that shows the issue. Also provide the steps you took (commands) to build a release apk.
Thanks.

**Comment by goderbauer** [comment] 2020-10-13 23:35
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!Thanks for your contribution.

**Closed by goderbauer** 2020-10-13 23:35 UTC
Labels: in triage, waiting for customer response

**Comment by bluce-clj** [comment] 2020-11-11 07:49
is a big bug!!!

**Comment by shinsenter** [comment] 2020-12-25 01:27
Please re-open the issue, because it has not been fixed.
