### ISSUE TITLE
flutter_tools writeComponentFile() api after readComponent() is wrong  Reference to root::dart:collection is not bound to an AST node. A library was expected

### ISSUE THREAD

**Issue by ckdgit** [flutter/flutter#42497] opened 2019-10-11 04:02 UTC
I want to  add some feature to flutter_tools ,I use the system  function (**readComponent()**) from  app.dill file ,  then I did noting,  but when I used **writeComponentFile** api to write component to dill, I got error that output file  is empty.
I add that process to the build_bundle.dart.
## Steps to Reproduce

1.void readComponent(Component component, {bool checkCanonicalNames: false}) 
2. void writeComponentFile(Component component)

## Logs

```
Unhandled exception:
Reference to root::dart:collection is not bound to an AST node. A library was expected
#0      Reference.asLibrary (package:kernel/ast.dart:217:7)
#1      _PrivateName.library (package:kernel/ast.dart:4764:38)
#2      CanonicalName.getChildFromQualifiedName (package:kernel/canonical_name.dart:117:32)
#3      CanonicalName.getChildFromMember (package:kernel/canonical_name.dart:123:10)
#4      Class.computeCanonicalNames (package:kernel/ast.dart:917:21)
#5      Library.computeCanonicalNames (package:kernel/ast.dart:423:14)
#6      Component.computeCanonicalNamesForLibrary (package:kernel/ast.dart:5784:13)
#7      Component.computeCanonicalNames (package:kernel/ast.dart:5778:7)
```

```
```

Finally, paste the output of running `flutter doctor -v` here. 

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.13.6 17G2208, locale zh-Hans-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.4)
[!] IntelliJ IDEA Ultimate Edition (version 2018.2.4)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] Connected device (1 available)

```

**Comment by Liujingguang** [comment] 2019-10-17 04:02
i have the same question.

**Comment by ckdgit** [comment] 2019-10-17 12:55
Can anyone solve it?

**Comment by Liujingguang** [comment] 2019-10-17 13:04
In my option , may be this is  old version question ,in 1.9.1-4, I run fine.

**Comment by Liujingguang** [comment] 2019-10-18 03:06
I initially suspected that the kernel api changes caused by the update of the flutter version. As far as the current status quo is concerned, I think it may be that some dart library naming conventions in platform_strong.dill are inconsistent with flutter. The specific reasons need to be explored in one step. What do you think?

**Comment by VladyslavBondarenko** [comment] 2020-01-16 13:16
Hi @ckdgit 
I'm closing this issue as it refer to an older version of Flutter.
If you are you still experiencing this issue with the latest version of Flutter,
you may want to open a new issue or comment below and I'll reopen current one
Thank you

**Closed by VladyslavBondarenko** 2020-01-16 13:16 UTC
Labels: dependency: dart

**Comment by soloxiao** [comment] 2020-07-16 13:21
Currently I'm facing the issue again with version  1.18.0-11.1.pre. What I've done is just read the component then write the component.  And the error is 'Reference to dart:core::Deprecated is not bound to an AST node. A class was expected'

**Comment by VladyslavBondarenko** [comment] 2020-07-16 16:12
@soloxiao consider to file a new issue with filling out template
