### ISSUE TITLE
[Accessibility] Problem with text scaler

### ISSUE THREAD

**Issue by Evhalon** [flutter/flutter#160362] opened 2024-12-16 18:02 UTC
I'm using flutter 3.24.5 and on Apple devices (web and app) it seems that when we resize text, nothing is working.

Thank you!

**Comment by danagbemava-nc** [comment] 2024-12-17 09:03
Hi @Evhalon, please provide a complete minimal reproducible code sample along with detailed steps to reproduce so that we can properly investigate this. 

Please also upgrade to the latest version of flutter stable (3.27.1) to see if you still experience this. If you do, please provide the updated output of `flutter doctor -v`. 

Please share any screenshots/screen recordings that are relevant. 

Thank you

**Comment by danagbemava-nc** [comment] 2024-12-18 06:00
Closing this as a duplicate of https://github.com/flutter/flutter/issues/160416

**Closed by danagbemava-nc** 2024-12-18 06:00 UTC
Labels: in triage
