### ISSUE TITLE
[Editor] "No Device" was shown when use editor

### ISSUE THREAD

**Issue by TritiumXs** [flutter/flutter#154610] opened 2024-09-04 10:04 UTC
### Steps to reproduce

- Platform: Windows 10
- Editor: IntelliJ IDEA & VSCode

1. Install Flutter SDK
2. Add Flutter SDK to PATH
3. Install IntelliJ Plugin
4. Create a new project
5. Build & Run

### Actual results

When I used Flutter SDK with IntelliJ IDEA, I couldn't Build and Run the sample project on my platform. IntelliJ showed "No Connected Devices Found" and told me to connect a device or see flutter.dev/setup to get started instructions.

Strangely, when I run `flutter run -d windows`, this project can run on my computer. I tried VSCode, but it can't be Run& Build like IntelliJ IDEA. I tried to Build & Run this project on Linux(with IntelliJ IDEA), and the project can be Build & Run again! I don't know what happened in the Flutter plugins, it only didn't work on Windows 10 + Editor.

### Logs

<details open>
<summary>Logs</summary>

IntelliJ IDEA:
![image](https://github.com/user-attachments/assets/1bf04dd3-68ff-432a-b1b5-e1fd65f536c3)

VSCode:
![image](https://github.com/user-attachments/assets/e9abb40f-67bc-407a-b309-a9a63c301a19)

```console
Launching lib\main.dart on Windows in debug mode...
Building Windows application...                                     5.9s
✓ Built build\windows\x64\runner\Debug\project.exe
Syncing files to device Windows...                                 275ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

A Dart VM Service on Windows is available at: http://127.0.0.1:56278/efuFPKvKTGs=/
The Flutter DevTools debugger and profiler on Windows is available at:
http://127.0.0.1:9102?uri=http://127.0.0.1:56278/efuFPKvKTGs=/

```

</details>

### Flutter Doctor output

<details open>
<summary>Doctor output</summary>

```console

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.24.1, on Microsoft Windows [版本 10.0.19045.4291], locale zh-CN)
[✓] Windows Version (Installed version of Windows is version 10 or higher)
[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
[✗] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.11.2)
[!] Android Studio (not installed)
[✓] IntelliJ IDEA Ultimate Edition (version 2024.2)
[✓] VS Code (version 1.92.2)
[✓] Connected device (2 available)
[✓] Network resources

! Doctor found issues in 2 categories.

```

</details>

**Comment by huycozy** [comment] 2024-09-04 11:59
Hi @TritiumXs 
Did you install Flutter plugin/Extension on these IDEs? Can you provide the output of `flutter doctor -v`?

**Comment by TritiumXs** [comment] 2024-09-04 13:10
> Hi @TritiumXs Did you install Flutter plugin/Extension on these IDEs? Can you provide the output of `flutter doctor -v`?

Yes, I did.
```console

[✓] Flutter (Channel stable, 3.24.1, on Microsoft Windows [版本 10.0.19045.4291], locale zh-CN)
    • Flutter version 3.24.1 on channel stable at H:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5874a72aa4 (2 weeks ago), 2024-08-20 16:46:00 -0500
    • Engine revision c9b9d5780d
    • Dart version 3.5.1
    • DevTools version 2.37.2

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at H:\Android\SDK\
    • Platform android-35, build-tools 35.0.0
    • Java binary at: C:\Program Files\Microsoft\jdk-21.0.4.7-hotspot\bin\java
    • Java version OpenJDK Runtime Environment Microsoft-9889606 (build 21.0.4+7-LTS)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.11.2)
    • Visual Studio at H:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.11.35222.181
    • Windows 10 SDK version 10.0.26100.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/to/windows-android-setup for detailed instructions).

[✓] IntelliJ IDEA Ultimate Edition (version 2024.2)
    • IntelliJ at H:\JetBrains\IntelliJ IDEA Ultimate
    • Flutter plugin version 81.1.3
    • Dart plugin version 242.21829.3

[✓] VS Code (version 1.92.2)
    • VS Code at C:\Users\Tritium\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.96.0

[✓] Connected device (3 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 12 (API 31) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [版本 10.0.19045.4291]
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 128.0.2739.63

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.

```

**Comment by huycozy** [comment] 2024-09-05 05:14
For VS Code, this could be a git-related issue. What is your git version? (`git -v` command)

Can you check https://github.com/Dart-Code/Dart-Code/issues/4840#issuecomment-2215258127 (and also another comments if any of them can help to debug the issue) to see if it works for you? If it doesn't work, please try to provide a full daemon log, please see https://github.com/Dart-Code/Dart-Code/issues/4840#issuecomment-2122797859. Thanks!

**Comment by TritiumXs** [comment] 2024-09-05 09:37
> For VS Code, this could be a git-related issue. What is your git version? ( command)`git -v`
> 
> Can you check [Dart-Code/Dart-Code#4840 (comment)](https://github.com/Dart-Code/Dart-Code/issues/4840#issuecomment-2215258127) (and also another comments if any of them can help to debug the issue) to see if it works for you? If it doesn't work, please try to provide a full daemon log, please see [Dart-Code/Dart-Code#4840 (comment)](https://github.com/Dart-Code/Dart-Code/issues/4840#issuecomment-2122797859). Thanks!

My git version is `v2.43.0` (git for msys2). 
```console

PS> git -v
git version 2.43.0

```
Git can cause this problem? And should I install Git for Windows?

------------------------------------  

Well, I uninstalled Git for MSYS2 and installed Git for Windows, Flutter works well now.
![image](https://github.com/user-attachments/assets/547d3dfd-d1ea-4b13-aec8-4c58135bd03e)

**Comment by huycozy** [comment] 2024-09-05 09:54
Thanks for checking that. Looks like there is an open Flutter issue to track this for VSCode at https://github.com/flutter/flutter/issues/143625, so please follow it (and also the linked Dart SDK issue there) for updates.

For IntelliJ IDEA, can you confirm the same as well? Does it work now after installing Git for Windows?

**Comment by TritiumXs** [comment] 2024-09-06 09:48
> Thanks for checking that. Looks like there is an open Flutter issue to track this for VSCode at #143625, so please follow it (and also the linked Dart SDK issue there) for updates.
> 
> For IntelliJ IDEA, can you confirm the same as well? Does it work now after installing Git for Windows?

Sure! IntelliJ works well too. This bug will be fixed in the future?

**Comment by huycozy** [comment] 2024-09-06 10:03
Yes, it should be. This is most likely similar to https://github.com/flutter/flutter/issues/143625. However, need to debug to find the cause. It would be helpful if you could add some information there for further investigation, please see https://github.com/flutter/flutter/issues/143625#issuecomment-2233080795. 

I will close this issue to concentrate on that one. Thank you!

**Closed by huycozy** 2024-09-06 10:03 UTC
Labels: in triage
