### ISSUE TITLE
[web] Text in textField becomes 'blurry' when suffixIcon is set

### ISSUE THREAD

**Issue by mordivgor** [flutter/flutter#65725] opened 2020-09-13 17:12 UTC
**Steps to Reproduce**

Typing in textField when suffixIcon is set. If text starts moving because of lack of the space, it becomes more "blurry".

<details>
<summary> Code </summary>

```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Default label',
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Container(
          width: 200,
          child: TextField(
            decoration: InputDecoration(
              suffixIcon: Icon(Icons.search)
            ),
          )
        )
      )
    ); 
  }
}
```

</details>

**Expected results:** 

Text quality is the same all the time.
![image](https://user-images.githubusercontent.com/54472480/93024159-95aa1b00-f5f4-11ea-936e-2b400ee75967.png)

**Actual results:** 

When typing and text starts moving (because suffixIcon takes some space), quality of the text is being changed also. It backs when removing the letters.

![image](https://user-images.githubusercontent.com/54472480/93024161-9e9aec80-f5f4-11ea-9ac5-0db7cf569798.png)

I hope difference is visible :)

I did not see the problem when suffixIcon is not set.

<details>
  <summary>Flutter doctor</summary>

```

[√] Flutter (Channel beta, 1.21.0-9.2.pre, on Microsoft Windows [Version 10.0.19041.508], locale pl-PL)
    • Flutter version 1.21.0-9.2.pre at G:\IOT\flutter\flutter
    • Framework revision 81a45ec2e5 (2 weeks ago), 2020-08-27 14:14:33 -0700
    • Engine revision 20a9531835
    • Dart version 2.10.0 (build 2.10.0-7.3.beta)

 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\Radek\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] Connected device (3 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 85.0.4183.102
    • Edge (web)       • edge       • web-javascript • Microsoft Edge 83.0.478.61

```

</details>

**Comment by darshankawar** [comment] 2020-09-14 08:56
Hi @mordivgor,
I am unable to see the difference when I tried your code on latest master. When the text moves, the quality remains same.

[65725.mov.zip](https://github.com/flutter/flutter/files/5217247/65725.mov.zip)

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.22.0-10.0.pre.161, on Mac OS X 10.15.4 19E2269,
    locale en-IN)
    • Flutter version 1.22.0-10.0.pre.161 at
      /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision cba91c97d0 (9 hours ago), 2020-09-13 18:57:03 -0400
    • Engine revision 2fc054147e
    • Dart version 2.10.0 (build 2.10.0-121.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (4 available)
    • SM A260G (mobile)                   • 5200763ebcfa861f
      • android-arm    • Android 8.1.0 (API 27)
    • iPhone SE (2nd generation) (mobile) • 312977A7-2DB1-4737-AEBB-35FA6522A309
      • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-5 (simulator)
    • Web Server (web)                    • web-server
      • web-javascript • Flutter Tools
    • Chrome (web)                        • chrome
      • web-javascript • Google Chrome 85.0.4183.102

• No issues found!

```

</details>

Can you switch to latest master and see if you still see the issue at your end ?
Thanks.

**Comment by mordivgor** [comment] 2020-09-14 09:58
Hello @darshankawar ,
Indeed on your preview the quality remains the same.
Unfortunately, I have still experienced this issue on my side, even on master channel.
<details>
<summary>Flutter doctor </summary>

```

[√] Flutter (Channel master, 1.22.0-10.0.pre.161, on Microsoft Windows [Version 10.0.19041.508], locale pl-PL)
    • Flutter version 1.22.0-10.0.pre.161 at G:\IOT\flutter\flutter
    • Framework revision cba91c97d0 (11 hours ago), 2020-09-13 18:57:03 -0400
    • Engine revision 2fc054147e
    • Dart version 2.10.0 (build 2.10.0-121.0.dev)

 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\Radek\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] Connected device (3 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 85.0.4183.102
    • Edge (web)       • edge       • web-javascript • Microsoft Edge 83.0.478.61

```
</details>

I do not know what could be a difference :/

**Comment by darshankawar** [comment] 2020-09-14 13:03
@mordivgor thanks for trying out again. I looked at your original issue description but can't find the difference there too.
Can you share your findings when you remove `suffixIcon` ?

**Comment by azbuky** [comment] 2020-09-14 14:17
I am experiencing the same issue when the text is longer than the width of the text field. Does not seem related to the suffix icon.

If you zoom in the picture there is a clear difference in rendering.

![Blurry text](https://user-images.githubusercontent.com/567277/93093534-77eabd80-f6a9-11ea-8a95-41de8c6fad4a.png)

<details>
<summary>Sample code</summary>

```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Default label',
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Container(
          width: 200,
          child: Column(
            children: [
              TextField(),
              TextField(),
            ],
          ),
        ),
      ),
    );
  }
}
```
</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.22.0-10.0.pre.161, on Linux, locale en_US.UTF-8)
    • Flutter version 1.22.0-10.0.pre.161 at /home/azbuky/Devel/Sdks/flutter
    • Framework revision cba91c97d0 (15 hours ago), 2020-09-13 18:57:03 -0400
    • Engine revision 2fc054147e
    • Dart version 2.10.0 (build 2.10.0-121.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /home/azbuky/Devel/Sdks/Android/Sdk/
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /home/azbuky/Devel/Sdks/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 3.6)
    • Android Studio at /home/azbuky/Devel/Sdks/android-studio
    • Flutter plugin version 48.0.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.49.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.14.1

[✓] Connected device (3 available)
    • Linux (desktop)  • linux      • linux-x64      • Linux
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 85.0.4183.102

• No issues found!
```
</details>

**Comment by mordivgor** [comment] 2020-09-14 14:30
@azbuky  you are right, same thing on my side without suffixIcon.
Maybe it is somehow related to this issue #58159, but someone would need to confirm it.

**Comment by darshankawar** [comment] 2020-09-15 05:56
@mordivgor @azbuky Tried again with few workarounds and still see no difference and I see good quality of the text.
@azbuky tried your code sample and don't see any difference.

<img width="831" alt="Screenshot 2020-09-15 at 11 21 50 AM" src="https://user-images.githubusercontent.com/67046386/93170951-d1082f00-f745-11ea-81fb-a8f9b48b6d64.png">

Moreover, the issue linked by @mordivgor, I tried code samples from there and again don't see any blur text irrespective of using any widgets. 

<img width="867" alt="Screenshot 2020-09-15 at 11 17 06 AM" src="https://user-images.githubusercontent.com/67046386/93171043-fdbc4680-f745-11ea-9ead-c26d7bc8e6e2.png">
<img width="972" alt="Screenshot 2020-09-15 at 11 19 56 AM" src="https://user-images.githubusercontent.com/67046386/93171049-ff860a00-f745-11ea-85a3-cf48ac65f1f4.png">

Tested on latest master.

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.22.0-10.0.pre.161, on Mac OS X 10.15.4 19E2269,
    locale en-IN)
    • Flutter version 1.22.0-10.0.pre.161 at
      /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision cba91c97d0 (9 hours ago), 2020-09-13 18:57:03 -0400
    • Engine revision 2fc054147e
    • Dart version 2.10.0 (build 2.10.0-121.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (4 available)
    • SM A260G (mobile)                   • 5200763ebcfa861f
      • android-arm    • Android 8.1.0 (API 27)
    • iPhone SE (2nd generation) (mobile) • 312977A7-2DB1-4737-AEBB-35FA6522A309
      • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-5 (simulator)
    • Web Server (web)                    • web-server
      • web-javascript • Flutter Tools
    • Chrome (web)                        • chrome
      • web-javascript • Google Chrome 85.0.4183.102

• No issues found!
```

</details>

**Comment by azbuky** [comment] 2020-09-15 10:00
@darshankawar are you testing on a retina MacBook?

I have tested the two text fields code sample on Ubuntu 20.04 with Chrome and Firefox and on Windows 10 latest with Chrome, Firefox, Edge and Edge based on Chromium. Also tested on a non retina MacBook Pro with latest macOS on Firefox, Chrome and Safari. 

All tests on Windows and macOS were done on current dartpad version (Based on Flutter 1.21.0-9.2.pre Dart SDK 2.9.3). On Ubuntu I have tested with latest master.

Firefox renders correctly on all platform.
Edge (non Chromium)  renders correctly,
Chrome, Safari and Edge (based on Chromium) render slightly blurry text when text is longer then the width of the text field.

Tested on an Acer Swift 3 with 1080p display and non retina MacBook Pro 2012 1280x800 display.

Hope this helps.

**Comment by darshankawar** [comment] 2020-09-15 13:16
@azbuky no, I am not using retina MacBook.  Chrome version is `85.0.4183.102`.

**Comment by mordivgor** [comment] 2020-09-16 18:39
hello @darshankawar 
Hard to say what I can add more. From my perspective we can assume that it is similar like the mentioned case and close this one.
@azbuky gave many useful information and I think I won't be able to add more.

**Comment by azbuky** [comment] 2020-09-16 19:19
Looking more closely to the screenshots, it seems (at least on my device) that Chrome uses sub pixel antialiasing when the text is smaller than the text field's width but switches to grayscale antialiasing when the text is longer. 
 
Also it seems the long text is slightly more blurry because it is not pixel boundary aligned. Might be the reason Chrome switches to grayscale antialiasing.

In @darshankawar 's screenshots it seems Chrome only uses grayscale antialiasing. It also appears to be a high resolution screen. 

@darshankawar would you be so kind to try my example one more time with only uppercase S letters. Four letters in the top text field and enough letters to make the text field scroll in the bottom one. And upload a screenshot. Thanks.

**Comment by darshankawar** [comment] 2020-09-17 06:24
@azbuky sure. I tried your code sample again.

<img width="973" alt="Screenshot 2020-09-17 at 11 52 49 AM" src="https://user-images.githubusercontent.com/67046386/93427991-5b829700-f8dc-11ea-8e95-8b25a55020c4.png">

If you both agree, I can probably make this a duplicate of one of the related ones and close this.

**Comment by azbuky** [comment] 2020-09-17 08:18
I am ok with closing this in favor of #58159.

**Comment by mordivgor** [comment] 2020-09-17 13:21
I am ok.

**Comment by darshankawar** [comment] 2020-09-17 13:26
Closing this as duplicate of [58159](https://github.com/flutter/flutter/issues/58159).

**Closed by darshankawar** 2020-09-17 13:26 UTC
Labels: in triage
