### ISSUE TITLE
Container Image size bug

### ISSUE THREAD

**Issue by 120011676** [flutter/flutter#55806] opened 2020-04-28 02:05 UTC
Image.asset(
                                  'assets/images/upload.png',
                                  width: 29,
                                ),
                                Container(
                                  width: 60,
                                  height: 60,
                                  decoration: BoxDecoration(
                                    color: Colors.blue,
                                  ),
                                  child: Image.asset(
                                    'assets/images/upload.png',
                                    width: 29,
                                  ),
                                )

![image](https://user-images.githubusercontent.com/1992933/80438955-013a6700-8938-11ea-9403-19a8cc22c868.png)

Picture 1 2 is the same size

**Comment by VladyslavBondarenko** [comment] 2020-04-28 09:16
Hi @120011676 
this is intended behaviour, you can wrap your image in the Center widget to avoid it
Take a look at https://github.com/flutter/flutter/issues/20847,
I'm closing the current one as duplicate.
If you disagree please write in the comments and I will reopen it

**Closed by VladyslavBondarenko** 2020-04-28 09:16 UTC

**Comment by 120011676** [comment] 2020-05-07 05:36
@VladyslavBondarenko feasible
