### ISSUE TITLE
[windows 7] GUI doesn't refresh after 3 minutes under Celeron J1900 CPU

### ISSUE THREAD

**Issue by skydig** [flutter/flutter#89152] opened 2021-08-30 07:24 UTC
1. 
1.1   download application https://github.com/hukusuke1007/stop_watch_timer  and run application 
1.2  download application https://github.com/smladeoye/flutter-simple-timer and run application

2, after around 3 min, stop watch timer application no refresh GUI, but can accept mouse event, the GUI is stuck

3. after around 3 min, simple-timer application no refresh GUI, but can accept mouse event, the GUI is stuck

4. application 1.1 and 1.2 are all timer which fresh screen periodically, but all was dead at last. 
  stop watch timer use rxdart, but i think it's not rxdart issue because simple-timer has not use rxdart.

5,can flutter run under low-performance win7 machine like Celeron J1900 which has intel HD graphics

6. my application need run under win7 and Celeron J1900 CPU, who can help me?

7,  I use latest flutter platform and compile the exe under windows7 development machine(not Celeron)

8. under my development machine(which E5 CPU and external graphic card), two application can all run OK

thanks

**Comment by skydig** [comment] 2021-08-31 10:55
I tested ，all version has this issue

**Comment by TahaTesser** [comment] 2021-08-31 12:56
Hi @skydig 
After running the in debug or release mode? 

I just tried https://github.com/smladeoye/flutter-simple-timer with windows support, increased the timer to 60 min and it runs fine on the latest stable for 15 min counting


<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.22000.168], locale en-US)
    • Flutter version 2.2.3 at C:\Users\Taha\Code\flutter_stable
    • Framework revision f4abaa0735 (9 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\Taha\Code\android-sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_SDK_ROOT = C:\Users\Taha\Code\android-sdk
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.2)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31624.102
    • Windows 10 SDK version 10.0.19041.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[✓] VS Code (version 1.59.1)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.25.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22000.168]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 92.0.4515.159
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 92.0.902.78

! Doctor found issues in 1 category
```

</details>


Can you please provide your `flutter doctor -v`, a complete reproducible minimal code sample, and complete `flutter run -d windows --verbose` logs running the minimal code sample?
Thank you

**Comment by skydig** [comment] 2021-09-01 11:53
fowllowing is my development machine doctor -v
[√] Flutter (Channel beta, 2.5.0-5.2.pre, on Microsoft Windows [Version
    6.1.7601], locale zh-CN)
    • Flutter version 2.5.0-5.2.pre at d:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 19c61fed0d (2 weeks ago), 2021-08-18 17:10:31 -0700
    • Engine revision 7a4c4505f6
    • Dart version 2.14.0 (build 2.14.0-377.7.beta)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)

    • Android SDK at C:\Users\Administrator\AppData\Local\Android\sdk
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for

      more details.

[√] Chrome - develop for the web
    • Chrome at
      C:\Users\Administrator\AppData\Local\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Enterprise 2019 16.10.4)
    • Visual Studio at d:\Program Files (x86)\Microsoft Visual
      Studio\2019\Enterprise
    • Visual Studio Enterprise 2019 version 16.10.31515.178
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2020.3)
    • Android Studio at D:\as
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] Connected device (2 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version
      6.1.7601]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 91.0.4472.106





actually, I have tried all 4 kinds of channel and almost all version after realease 2.2, all will stuck after few minutes

I even change the periodic timer of stop_watch_timer application interval to 1s(original value is 1ms), the application is still stuck
when the gui can not refresh, I click mouse, theGUI can accept mouse event, but the GUI is stuck without refresh.

following example are re-producible each time abosultely under my win7 Celeron J1900 CPU environment.

https://github.com/hukusuke1007/stop_watch_timer
https://github.com/smladeoye/flutter-simple-timer

**Comment by TahaTesser** [comment] 2021-09-01 11:59
Hi @skydig 
I think the issue is related to your onboard graphics, Is it on power or battery? As some models could reduce power consumption if it is a laptop which could graphics consumption to drop.  I am not entirely sure but there have been issues with graphics on desktop apps even on Linux

**Comment by skydig** [comment] 2021-09-01 22:42
my pc use AC power，no battery，the cpu performance is too low，but at start the application run normally without any issue，just few min，gui has no refresh；for the application which has no so frequent timer refresh，there is no gui-stuck

**Comment by TahaTesser** [comment] 2021-09-02 06:43
@skydig 

> ；for other application which has no so frequent timer refresh，there is no gui-stuck

Could try timer refresh in other apps? Maybe a web app that replicates this behavior? It looks like low powered CPU and it's onboard causing this issue.

**Comment by skydig** [comment] 2021-09-02 08:51
![stop_timer_start](https://user-images.githubusercontent.com/27293515/131812201-ce5e12bc-516d-4cee-bd9b-9c1521860f1f.jpg)
![furmark](https://user-images.githubusercontent.com/27293515/131812219-129c25ee-1343-4c7b-9c07-42a2a507ac00.jpg)
![stop_timer_end](https://user-images.githubusercontent.com/27293515/131812231-889bce91-293d-403f-8f97-a69cefdd9293.jpg)

@TahaTesser 
I upload three pictures,
furmark is furmark test and GPU load and Memory
stop_timer_start is GPU load and Memory when stop_timer is running
stop_timer_end is GPU load and Memory when stop_timer application is stuck

when stop_timer stuck, other desktop GUI response are slower than when stop_timer is not running and when stop_timer began.

sorry, has not implement web app using flutter, could you give me some suggestion how to do that? 

another point my windows 7 machine's FPS is about 2(is it too low?),but GPU load and memory is low too.

thanks.

**Comment by TahaTesser** [comment] 2021-09-03 06:54
Hi @skydig 

> sorry, has not implement web app using flutter, could you give me some suggestion how to do that?

Simply execute `flutter create .` in the [example](https://github.com/smladeoye/flutter-simple-timer/tree/master/example)
This will generate a web folder then you can the project on the web using `flutter run -d chrome` (make sure you've the chrome installed)

**Comment by skydig** [comment] 2021-09-06 07:27
@TahaTesser 
ok,
I have build web application, how to run it under my target environment(which has no flutter installed, only exe can be run)
thank

**Comment by TahaTesser** [comment] 2021-09-06 12:21
Hi @skydig 
Do you chrome as one of the devices in `flutter doctor -v`? If yes, you should be able to run the app on the web and test it with `flutter run -d chrome`

**Comment by skydig** [comment] 2021-09-08 04:50
@TahaTesser 
I tested that web version has no issue.
![509159321](https://user-images.githubusercontent.com/27293515/132448348-24626c64-1af2-4330-a130-699fe8bdd084.jpg)

please check the attached picture

**Comment by TahaTesser** [comment] 2021-09-08 06:42
@skydig 
Thanks for the test, appreciate it

**Comment by skydig** [comment] 2021-09-13 09:18
today， I check log through pipe, found following print, 
I don't know whether it's flutter (engine)'s print.
please check the picture.
![2009331053](https://user-images.githubusercontent.com/27293515/133058181-914a3ae7-e964-4d05-bd43-c05a609cc15a.jpg)

**Comment by paul1989889** [comment] 2021-10-09 06:43
@darshankawar @skydig I have solved this problem by use windows patch package(KB2670838) and if using Celeron J1900 CPU, install .Net Framework 4.8(KB4503575)

**Comment by Ali-Fadaei** [comment] 2022-01-10 06:27
hi, how you run flutter app on windows 7? 
i was tried many times, but can't run it.
what's required pre instilling packages such as dotnet or cpp or...

**Comment by liqping** [comment] 2022-07-08 09:53
@paul1989889 thanks , KB2670838 is valid to solve blac screen on windows 7,intel Integrated graphics

**Comment by fangjianh** [comment] 2022-07-29 15:24
copy this dll into your release exe path, it can run good
![image](https://user-images.githubusercontent.com/8575573/181792322-dccc4752-28c3-4f27-a352-9b35c808c6aa.png)

**Comment by fangjianh** [comment] 2023-01-09 08:17
`
bool FlutterWindowWin32::OnBitmapSurfaceUpdated(const void* allocation,
                                                size_t row_bytes,
                                                size_t height) {
  HWND hwnd = std::get<HWND>(GetRenderTarget());
  HDC dc = ::GetDC(hwnd);
  BITMAPINFO bmi;
  memset(&bmi, 0, sizeof(bmi));
  bmi.bmiHeader.biSize = sizeof(BITMAPINFOHEADER);
  bmi.bmiHeader.biWidth = row_bytes / 4;
  bmi.bmiHeader.biHeight = -height;
  bmi.bmiHeader.biPlanes = 1;
  bmi.bmiHeader.biBitCount = 32;
  bmi.bmiHeader.biCompression = BI_RGB;
  bmi.bmiHeader.biSizeImage = 0;
  int ret = SetDIBitsToDevice(dc, 0, 0, row_bytes / 4, height, 0, 0, 0, height,
                              allocation, &bmi, DIB_RGB_COLORS);

  ReleaseDC(hwnd, dc);//add this line
  return ret != 0;
}
`

**Comment by yefl2064** [comment] 2023-07-11 07:44
> @darshankawar @skydig I have solved this problem by use windows patch package(KB2670838) and if using Celeron J1900 CPU, install .Net Framework 4.8(KB4503575)

I solved this problem, you can use d3dcompiler_47.dll without installing net framework4.8

**Comment by yefl2064** [comment] 2023-07-11 09:21
I tested it on win7， it works 
[https://github.com/yefl2064/TestFiles/blob/main/d3dcompiler_47.dll  ](url)

**Comment by cbracken** [comment] 2024-03-29 21:08
Since we have announced the end of support for Windows 7, we are closing this issue.

**Closed by cbracken** 2024-03-29 21:08 UTC
Labels: e: device-specific, engine, e: gpu driver bug, platform-windows, c: rendering, a: desktop, e: OS-version specific, P2, team-desktop, triaged-desktop
