### ISSUE TITLE
[tool_crash] SocketException: Send failed, OS Error: No route to host, errno = 65

### ISSUE THREAD

**Issue by jigar1859** [flutter/flutter#152830] opened 2024-08-04 06:57 UTC
## Command
```
flutter run --machine --start-paused -d 00008020-001A189611F3002E --devtools-server-address http://127.0.0.1:9101/ --target /Users/jigarthakkar/OfficeMacM2_LocalCode/Local_Code/Flutter/short_videos/lib/main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
SocketException: Send failed, OS Error: No route to host, errno = 65
```
#0      _NativeSocket.send (dart:io-patch/socket_patch.dart:1269:34)
#1      _RawDatagramSocket.send (dart:io-patch/socket_patch.dart:2582:15)
#2      MDnsClient.lookup (package:multicast_dns/multicast_dns.dart:225:14)
#3      MDnsVmServiceDiscovery._pollingVmService (package:flutter_tools/src/mdns_discovery.dart:228:66)
<asynchronous suspension>
#4      MDnsVmServiceDiscovery.firstMatchingVmService (package:flutter_tools/src/mdns_discovery.dart:184:56)
<asynchronous suspension>
#5      MDnsVmServiceDiscovery.getVMServiceUriForLaunch (package:flutter_tools/src/mdns_discovery.dart:429:50)
<asynchronous suspension>
#6      Future.any.onValue (dart:async/future.dart:615:5)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 3.13.5, on macOS 15.0 24A5298h darwin-arm64, locale en-GB)
    • Flutter version 3.13.5 on channel stable at /usr/local/Caskroom/flutter/3.13.2/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 12fccda598 (11 months ago), 2023-09-19 13:56:11 -0700
    • Engine revision bd986c5ed2
    • Dart version 3.1.2
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/jigarthakkar/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/jigarthakkar/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
    • Xcode at /Applications/Xcode-beta.app/Contents/Developer
    • Build 16A5202i
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)

[✓] VS Code (version 1.92.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.94.0

[✓] Connected device (4 available)
    • Jigar’s iPhone (mobile) • 00008020-001A189611F3002E                • ios            • iOS 18.0 22A5297f
    • SunIT_iPad (mobile)     • 3be3c1a6ca567fe81a41d0d48dc44dd60ab01c3e • ios            • iOS 17.5.1 21F90
    • macOS (desktop)         • macos                                    • darwin-arm64   • macOS 15.0 24A5298h darwin-arm64
    • Chrome (web)            • chrome                                   • web-javascript • Google Chrome 127.0.6533.89

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

## Flutter Application Metadata
**Type**: malformed
**Version**: 1.0.1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: null
**Creation framework version**: null
### Plugins
flutter_local_notifications-17.2.1+2
flutter_local_notifications_linux-4.0.1
flutter_native_splash-2.3.7
package_info_plus-4.2.0
path_provider-2.1.3
path_provider_android-2.2.3
path_provider_foundation-2.3.2
path_provider_linux-2.2.1
path_provider_windows-2.2.1
shared_preferences-2.2.3
shared_preferences_android-2.2.1
shared_preferences_foundation-2.3.5
shared_preferences_linux-2.3.2
shared_preferences_web-2.2.1
shared_preferences_windows-2.3.2
sqflite-2.3.2
video_player-2.8.5
video_player_android-2.4.12
video_player_avfoundation-2.5.2
video_player_web-2.1.3
wakelock_plus-1.1.4

**Comment by danagbemava-nc** [comment] 2024-08-05 07:49
Closing this as a duplicate of https://github.com/flutter/flutter/issues/150131

**Closed by danagbemava-nc** 2024-08-05 07:49 UTC
Labels: in triage
