### ISSUE TITLE
[Impeller] Split up android performance tests between Vulkan / OpenGL.

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#129044] opened 2023-06-16 22:28 UTC
Right now it is just using the default mechanism to determine which backend to use so the meaning of tests are changing as we switch from "OpenGL only" to "Vulkan if it's available".

We want to make sure we don't accidentally change the meaning of these benchmarks with a bug in the backend selection logic either.

**Comment by chinmaygarde** [comment] 2023-07-13 05:25
Closing as duplicate of https://github.com/flutter/flutter/issues/130118

**Closed by chinmaygarde** 2023-07-13 05:25 UTC
Labels: engine, P2, e: impeller, team-engine, triaged-engine
