### ISSUE TITLE
interactive_viewer.dart': Failed assertion: line 632 pos 12: 'scale != 0.0': is not true.

### ISSUE THREAD

**Issue by insinfo** [flutter/flutter#95878] opened 2021-12-27 22:17 UTC
package:flutter/src/widgets/interactive_viewer.dart': Failed assertion: line 632 pos 12: 'scale != 0.0': is not true.

```dart
 Widget widgetToUse(ImageType imageType, String path) {
    Widget image;
    if (imageType == ImageType.URL) {
      image = CachedNetworkImage(
        imageUrl: path,
        placeholder: (context, url) =>
            Center(child: CircularProgressIndicator()),
        errorWidget: (context, url, error) => Icon(Icons.error),
        fit: BoxFit.contain,
      );
    } else if (imageType == ImageType.ASSET) {
      image = Image.asset(
        path,
        fit: BoxFit.contain,
      );
    } else if (imageType == ImageType.BYTES) {
      image = Image.memory(
        base64Decode(path),
        fit: BoxFit.contain,
      );
    } else {
      image = Image.file(
        File(path),
        fit: BoxFit.contain,
      );
    }

    return InteractiveViewer(
      child: image,
      maxScale: 5,
    );
  }
```

```console

════════ Exception caught by gesture ═══════════════════════════════════════════
The following assertion was thrown while handling a gesture:
'package:flutter/src/widgets/interactive_viewer.dart': Failed assertion: line 632 pos 12: 'scale != 0.0': is not true.
package:flutter/…/widgets/interactive_viewer.dart:1
2

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack
#2      _InteractiveViewerState._matrixScale
package:flutter/…/widgets/interactive_viewer.dart:632
#3      _InteractiveViewerState._onScaleUpdate
package:flutter/…/widgets/interactive_viewer.dart:752
#4      ScaleGestureRecognizer._advanceStateMachine.<anonymous closure>
package:flutter/…/gestures/scale.dart:531
#5      GestureRecognizer.invokeCallback
package:flutter/…/gestures/recognizer.dart:198
#6      ScaleGestureRecognizer._advanceStateMachine
package:flutter/…/gestures/scale.dart:530
#7      ScaleGestureRecognizer.handleEvent
package:flutter/…/gestures/scale.dart:409
#8      PointerRouter._dispatch
package:flutter/…/gestures/pointer_router.dart:94
#9      PointerRouter._dispatchEventToRoutes.<anonymous closure>
package:flutter/…/gestures/pointer_router.dart:139
package:flutter/…/gestures/pointer_router.dart:139
#10     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:539:8)
#11     PointerRouter._dispatchEventToRoutes
package:flutter/…/gestures/pointer_router.dart:137
#12     PointerRouter.route
package:flutter/…/gestures/pointer_router.dart:123
#13     GestureBinding.handleEvent
package:flutter/…/gestures/binding.dart:439
#14     GestureBinding.dispatchEvent
package:flutter/…/gestures/binding.dart:419
#15     RendererBinding.dispatchEvent
package:flutter/…/rendering/binding.dart:322
#16     GestureBinding._handlePointerEventImmediately
package:flutter/…/gestures/binding.dart:374
#17     GestureBinding.handlePointerEvent
package:flutter/…/gestures/binding.dart:338
#18     GestureBinding._flushPointerEventQueue
package:flutter/…/gestures/binding.dart:296
#19     GestureBinding._handlePointerDataPacket
package:flutter/…/gestures/binding.dart:279
#23     _invoke1 (dart:ui/hooks.dart:169:10)
#24     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:293:7)
#25     _dispatchPointerDataPacket (dart:ui/hooks.dart:88:31)
(elided 5 frames from class _AssertionError and dart:async)
Handler: "onUpdate"
Recognizer: ScaleGestureRecognizer#f7d57
    debugOwner: GestureDetector

```

![image](https://user-images.githubusercontent.com/12227024/147510498-de3d312b-995b-4aee-acca-31cee949ef81.png)

### flutter doctor -v
```console
PS C:\MyDartProjects\appsescverao\appsescverao> flutter doctor -v
[√] Flutter (Channel stable, 2.8.1, on Microsoft Windows [versÃ£o 10.0.22000.376], locale pt-BR)
    • Flutter version 2.8.1 at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (11 days ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at C:\Users\isaque\AppData\Local\Android\sdk
    • Platform android-32, build-tools 32.0.0
    • Java binary at: C:\Program Files\Android\Android Studio1\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.3)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31702.278
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.63.2)
    • VS Code at C:\Users\isaque\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.29.0

[√] Connected device (4 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)                  • windows       • windows-x64    • Microsoft Windows [versÃ£o 10.0.22000.376]
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 96.0.4664.110
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 96.0.1054.43

• No issues found!
PS C:\MyDartProjects\appsescverao\appsescverao> 
```

**Comment by insinfo** [comment] 2021-12-27 22:18
### full code

```dart
library lightbox;

import 'dart:convert';
import 'dart:io';
import 'dart:ui';
import 'package:cached_network_image/cached_network_image.dart';
import 'package:flutter/material.dart';

/// Tells the type of images from the images string list
enum ImageType {
  /// Images are url
  URL,

  /// Images are assets
  ASSET,

  /// Images are base64 encoded string
  BYTES,

  /// Images are files paths from system
  FILE
}

class LightBoxRoute extends PopupRoute {
  ///LightBoxRoute class creates the overlay with scale transition to show the LightBox
  LightBoxRoute({
    this.builder,
    this.dismissible = true,
    this.label,
    this.color,
    RouteSettings setting,
  }) : super(settings: setting);

  /// This function defines the widget to be build when navigate to the LightBoxRoute
  final WidgetBuilder builder;

  /// boolean to control if the LightBox can be dismiss or not
  final bool dismissible;

  /// barrier label
  final String label;

  /// barrier colors
  Color color;

  @override
  Color get barrierColor => color;

  @override
  bool get barrierDismissible => dismissible;

  @override
  String get barrierLabel => label;

  @override
  Widget buildPage(
    BuildContext context,
    Animation<double> animation,
    Animation<double> secondaryAnimation,
  ) {
    return builder(context);
  }

  @override
  Widget buildTransitions(
    BuildContext context,
    Animation<double> animation,
    Animation<double> secondaryAnimation,
    Widget child,
  ) {
    return ScaleTransition(
      scale: Tween<double>(
        begin: 0.0,
        end: 1.0,
      ).animate(
        CurvedAnimation(
          parent: animation,
          curve: Curves.fastOutSlowIn,
        ),
      ),
      child: child,
    );
  }

  @override
  Duration get transitionDuration => const Duration(milliseconds: 200);
}

class LightBox extends StatefulWidget {
  ///Array of images that will be display by the lightbox
  ///
  /// It may be paths to images in asset or from the user phone or urls for images to be fetch on the Internet
  /// Also can be base64 encoded Strings to be display as bytes
  final List<String> images;

  /// Gives the initial index of the Lightbox
  /// By default it has the value zero
  final int initialIndex;

  /// This parameter indicates wheter the images parameters are urls,bytes or assets
  /// By default it has value is [ImageType.URL]
  final ImageType imageType;

  /// Gives the value of the Gaussian blur
  final double blur;

  ///Icon to close the lightbox
  final IconData closeIcon;

  /// Close icon color
  final Color closeIconColor;

  /// Close text to be display
  final String closeText;

  /// Close text color
  final Color closeTextColor;

  /// Previous Icon
  final IconData prevIcon;

  /// Previous Icon color
  final Color prevIconColor;

  /// Previous button text
  final String prevText;

  /// Previous button text color
  final Color prevTextColor;

  /// Next Icon
  final IconData nextIcon;

  /// Next Icon color
  final Color nextIconColor;

  /// Next button text
  final String nextText;

  /// Next button text color
  final Color nextTextColor;

  /// This is the lightBox widget which is used to display the image as diaporama
  /// with controls
  LightBox(
      {this.images,
      this.initialIndex = 0,
      this.imageType = ImageType.URL,
      this.blur = 0.0,
      this.closeIcon = Icons.close,
      this.closeIconColor = Colors.white,
      this.closeText = 'Fechar',
      this.closeTextColor = Colors.white,
      this.prevIcon = Icons.arrow_back_ios,
      this.prevIconColor = Colors.white,
      this.prevText = 'Voltar',
      this.prevTextColor = Colors.white,
      this.nextIcon = Icons.arrow_forward_ios,
      this.nextIconColor = Colors.white,
      this.nextText = 'Avançar',
      this.nextTextColor = Colors.white});
  @override
  _LightBoxState createState() => _LightBoxState();
}

class _LightBoxState extends State<LightBox> {
  PageController controller;

  @override
  void initState() {
    super.initState();
    controller = PageController(
        viewportFraction: 1, keepPage: true, initialPage: widget.initialIndex);
  }

  void changePageViewPosition(int whichPage) {
    if (whichPage < widget.images.length && whichPage >= 0) {
      controller.jumpToPage(whichPage);
    }
  }

  Widget widgetToUse(ImageType imageType, String path) {
    Widget image;
    if (imageType == ImageType.URL) {
      image = CachedNetworkImage(
        imageUrl: path,
        placeholder: (context, url) =>
            Center(child: CircularProgressIndicator()),
        errorWidget: (context, url, error) => Icon(Icons.error),
        fit: BoxFit.contain,
      );
    } else if (imageType == ImageType.ASSET) {
      image = Image.asset(
        path,
        fit: BoxFit.contain,
      );
    } else if (imageType == ImageType.BYTES) {
      image = Image.memory(
        base64Decode(path),
        fit: BoxFit.contain,
      );
    } else {
      image = Image.file(
        File(path),
        fit: BoxFit.contain,
      );
    }

    return InteractiveViewer(
      child: image,
      maxScale: 5,
    );
  }

  @override
  Widget build(BuildContext context) {
    return SafeArea(
      child: Container(
        padding: EdgeInsets.fromLTRB(16, 0, 16, 16),
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            BackdropFilter(
              filter: ImageFilter.blur(
                sigmaX: widget.blur,
                sigmaY: widget.blur,
              ),
              child: Column(
                children: [
                  Container(
                    child: TextButton.icon(
                      onPressed: () => Navigator.pop(context),
                      icon:
                          Icon(widget.closeIcon, color: widget.closeIconColor),
                      label: Text(widget.closeText,
                          style: TextStyle(color: widget.closeTextColor)),
                    ),
                  ),
                  Container(
                      height: MediaQuery.of(context).size.height - 140,
                      // width: MediaQuery.of(context).size.width - 20,
                      child: PageView.builder(
                          controller: controller,
                          physics: NeverScrollableScrollPhysics(),
                          itemCount: widget.images.length,
                          itemBuilder: (context, position) {
                            return widgetToUse(
                                widget.imageType, widget.images[position]);
                          })),
                  Row(
                    mainAxisAlignment: MainAxisAlignment.spaceBetween,
                    children: [
                      TextButton(
                        onPressed: () {
                          changePageViewPosition((controller.page - 1).round());
                        },
                        // icon: Icon(widget.prevIcon, color: widget.prevIconColor),
                        child: Text(
                          widget.prevText,
                          style: TextStyle(
                              color: widget.prevTextColor,
                              decoration: TextDecoration.none),
                        ),
                      ),
                      TextButton(
                        onPressed: () {
                          changePageViewPosition((controller.page + 1).round());
                        },
                        // icon: Icon(widget.nextIcon, color: widget.nextIconColor),
                        child: Text(
                          widget.nextText,
                          style: TextStyle(
                              color: widget.nextTextColor,
                              decoration: TextDecoration.none),
                        ),
                      ),
                    ],
                  )
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }
}

```

**Comment by mamuseferha** [comment] 2021-12-28 08:01
Hi @insinfo, 
Can you provide a minimal complete code sample that doesn’t include 3rd party plugins (`cached_network_image`) so I can isolate the issue to the flutter framework.

Possible duplicate of https://github.com/flutter/flutter/issues/82115
Thank you

**Closed** 2022-01-18 08:10 UTC
Labels: waiting for customer response, in triage
