### ISSUE TITLE
[tool_crash] FileSystemException: Cannot delete file, OS Error: Read-only file system, errno = 30

### ISSUE THREAD

**Issue by Barok-Getachew** [flutter/flutter#131203] opened 2023-07-24 16:14 UTC
## Command
```
flutter run
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Cannot delete file, OS Error: Read-only file system, errno = 30
```
#0      _File.throwIfError (dart:io/file_impl.dart:675:7)
#1      _File._deleteSync (dart:io/file_impl.dart:329:5)
#2      FileSystemEntity.deleteSync (dart:io/file_system_entity.dart:424:7)
#3      ForwardingFileSystemEntity.deleteSync (package:file/src/forwarding/forwarding_file_system_entity.dart:70:16)
#4      ForwardingFileSystemEntity.deleteSync (package:file/src/forwarding/forwarding_file_system_entity.dart:70:16)
#5      ErrorHandlingFileSystem.deleteIfExists (package:flutter_tools/src/base/error_handling_io.dart:80:12)
#6      _writeFlutterPluginsListLegacy (package:flutter_tools/

**Comment by darshankawar** [comment] 2023-07-25 06:58
Closing as duplicate of https://github.com/flutter/flutter/issues/131203

**Closed by darshankawar** 2023-07-25 06:58 UTC
Labels: in triage
