### ISSUE TITLE
analyzer benchmarks regressed ~30%

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#34267] opened 2019-06-11 19:48 UTC
The analyzer benchmarks regressed ~30% with this engine roll: https://github.com/flutter/flutter/pull/34203

cc @devoncarew @tvolkert

**Comment by liyuqian** [comment] 2019-06-11 20:05
There are other regressions with this dart roll:
* flutter_gallery_ios__transition_perf 90th_percentile_frame_build_time_millis
* microbenchmarks_ios stock_layout_iteration
* microbenchmarks_ios stock_build_iteration
* microbenchmarks_ios velocity_tracker_iteration

**Comment by tvolkert** [comment] 2019-06-11 20:17
Here are the Dart commits contained therein

dart-lang/sdk@97f91fe [vm] Mark Profiler_StringInterpolation Fail in vm.status
dart-lang/sdk@c167374 Add Never*, use it in type provider etc
dart-lang/sdk@97dc7f4 Support constructor declarations (issue 37196)
dart-lang/sdk@ed9d185 Top-level getters do not have parameters
dart-lang/sdk@5ca5a53 Migration: Add support for generic function types.
dart-lang/sdk@c269659 Migration: Add more support for dynamic, clean up handling of void.
dart-lang/sdk@8b17b2e Migration: add support for null-aware accesses.
dart-lang/sdk@2b76cdf [ VM ] Remove bad status file entries for data_uri_import_test/utf16
dart-lang/sdk@881a2e9 Migration: remove unnecessary constructor argument
dart-lang/sdk@eba533d Migration: Clean up handling of LUB and substitution nodes.
dart-lang/sdk@c41e9ae Fix wording in spec
dart-lang/sdk@0a0927d Migration: Separate the implementation from the NNBD migration engine's public API.
dart-lang/sdk@b3b9aac [dartdevc] enable testing on ff/safari/edge
dart-lang/sdk@575a642 Migration: Remove transitional API
dart-lang/sdk@e23b007 Migration: Move classes out of transitional_api.dart
dart-lang/sdk@47865b7 Migration: remove unused field Variables._graph.
dart-lang/sdk@4270982 TypeSystem tests code motion.
dart-lang/sdk@0629ce9 Change location where we set AnalysisDriver.useSummary2 in build mode.
dart-lang/sdk@f94628f Convert the remaining diagnostics tests to test for location
dart-lang/sdk@e4196ce [vm] Namespace constants like offsets and sizeofs to use runtime_api.h
dart-lang/sdk@5104636 Move NNBD migration tool to a fresh package.
dart-lang/sdk@6c358d3 Permissive mode reports the exceptions that were thrown and ignored

**Comment by GaryQian** [comment] 2019-06-11 20:19
https://github.com/flutter/engine/pull/9272 should fix it once it lands

**Comment by devoncarew** [comment] 2019-06-11 20:29
I do see the regression and the fix on our performance benchmarks.

**Comment by devoncarew** [comment] 2019-06-11 20:35
cc @stereotype441 for awareness

**Comment by tvolkert** [comment] 2019-06-12 00:12
Looks like this was fixed in https://github.com/flutter/flutter/pull/34281

**Closed by tvolkert** 2019-06-12 00:12 UTC
Labels: dependency: dart, engine, severe: performance, severe: regression, ⚠ TODAY
