### ISSUE TITLE
Regression: Text fields disabled on child navigator after swiping back from root navigator route

### ISSUE THREAD

**Issue by JoshJuncker** [flutter/flutter#96242] opened 2022-01-06 21:42 UTC
## Steps to Reproduce

1. Execute `flutter run` with version 2.8.1 on the code sample on physical iOS device 
2. Tap on text field. Notice that it focuses on it correctly.
3. Tap on the 'Push to Route' button
4. Swipe from the left edge of the screen to go back to the previous screen
5. Tap on the text field.
6. Notice that you can't focus the text field by tapping on it. It acts like it is disabled.
7. Also notice that the field is correctly enabled if you tap the 'Tap to pop route' button instead of swiping back, indicating a difference in behavior between Navigator.pop and swiping from the edge.
8. Note - This works correctly with flutter version 2.5.3, but is broken in version 2.8.1.

**Expected results:** 
Text field should be enabled and focusable by tapping on it
**Actual results:** 
Text field acts as if disabled and can't be focused by tapping on it
<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/cupertino.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);
  @override
  Widget build(BuildContext context) {
    return const CupertinoApp(
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({
    Key? key,
  }) : super(key: key);

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Navigator(
      onGenerateRoute: (settings) => CupertinoPageRoute(
        builder: (context) => Column(
          children: [
            const SizedBox(height: 80),
            const CupertinoTextField(),
            const SizedBox(height: 20),
            CupertinoButton(
              child: const Text("Push to Route"),
              onPressed: () => Navigator.of(context, rootNavigator: true).push(
                CupertinoPageRoute(builder: (context) => const Route1()),
              ),
            ),
          ],
        ),
      ),
    );
  }
}

class Route1 extends StatelessWidget {
  const Route1({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        const SizedBox(height: 80),
        CupertinoButton(child: const Text("Tap to pop route"), onPressed: () => Navigator.pop(context))
      ],
    );
  }
}
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
Analyzing test_back_gesture...                                          
No issues found! (ran in 3.6s)
```

```
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.2 21D5025f darwin-x64, locale en)
    • Flutter version 2.8.1 at /Users/joshjuncker/fvm/versions/2.8.1
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (3 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/joshjuncker/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.32.0

[✓] Connected device (2 available)
    • Josh’s iPhone (mobile) • 00008101-0009201A3E98001E • ios            • iOS 15.3 19D5026g
    • Chrome (web)           • chrome                    • web-javascript • Google Chrome 96.0.4664.110
    ! Error: Josh’s iPhone is busy: Preparing the watch for development via Josh’s iPhone. Xcode will continue when
      Josh’s iPhone is finished. (code -10)

• No issues found!
```

</details>

**Comment by danagbemava-nc** [comment] 2022-01-07 07:11
Hi @JoshJuncker, this was initially reported in https://github.com/flutter/flutter/issues/92053 which was closed in favor of https://github.com/flutter/flutter/issues/92693 since they shared a root cause. https://github.com/flutter/flutter/issues/92693 was fixed in https://github.com/flutter/flutter/pull/92615 and I can't seem to reproduce the behavior on the latest `master`. 

Can you switch to the latest master to confirm if this is still reproducible?

**Closed** 2022-01-11 21:58 UTC
Labels: waiting for customer response, in triage
