### ISSUE TITLE
Can't tap immediately after overscroll

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#9560] opened 2017-04-24 16:26 UTC
in iOS/Cupertino mode of the Gallery, scroll to the bottom of the list, do an overscroll and then immediately tap on "Colors".  Notice how your tap is ignored.  Wait a second for the overscroll animation to finish (or whatever it's doing) and then tapping works correctly.

We may already have this on file, but I just ran into it again now.

**Comment by abarth** [comment] 2017-04-24 16:52
I believe that is correct behavior.  Does the Settings app do something different in this case?

**Comment by eseidelGoogle** [comment] 2017-04-24 17:42
Yes, you can even tap during the bounce in settings.

![tap-during-bounce-720 mov](https://cloud.githubusercontent.com/assets/11857803/25350648/aa0c0062-28da-11e7-968b-72f666141e94.gif)

**Comment by abarth** [comment] 2017-04-27 06:54
I couldn't replicate your video on a device.  You'll have to show me in person.

**Comment by eseidelGoogle** [comment] 2017-04-28 16:00
So turns out the tap-during bounce is a red herring.  iOS icon buttons are always tappable regardless of the current gesture it seems, which is likely a bug in iOS.

However the original bug filed here of can't tap immediately overscroll is still valid.

**Comment by Hixie** [comment] 2018-01-03 00:29
Not being able to tap while we're scrolling is intentional. If this differers from the platform behaviour and we don't think the platform behaviour is a bug, then we should fix that. It's not clear to me from this bug what the difference is, though.

**Comment by goderbauer** [comment] 2018-12-27 22:13
I tried this on a couple of native views in the latest iOS release and none of them accept taps while the overscroll animation is running. I am closing this as working as intended for now.

**Closed by goderbauer** 2018-12-27 22:13 UTC
Labels: a: fidelity, framework, ⌺‬ platform-ios
