### ISSUE TITLE
Go router - redirect issue!

### ISSUE THREAD

**Issue by Puspharaj** [flutter/flutter#128166] opened 2023-06-03 09:30 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Go router redirect holds the history after force redirect. 

1. Login page -> (after successful login) Home page.

when i use redirect method to force the user to homepage from login page. I can able to go back and forth. Meaning I can still able to view the login page again.

How to implement push.replacement in this scenario?

Please use the default any sample app to reproduce the same result! 

### Expected results

no history in the navigation stack after redirect method.

### Actual results

navigation history remains same and not cleared!.

### Code sample

      redirect: (context, state) {
      final auth = bloc.state.status == AuthenticationStatus.authenticated;
      var userRole = false;
      if (bloc.state.status == AuthenticationStatus.authenticated &&
          bloc.state.user.message != null &&
          bloc.state.user.message!.data != null &&
          bloc.state.user.message!.data!.roles != null) {
        for (final element in bloc.state.user.message!.data!.roles!) {
          if (element.role == adminRoleName || element.role == adminRoleNameFullname) {
            userRole = true;
          }
        }
      }
      if (userRole) {
        debugPrint('yes admin role found and re-directing to admin role');
      }

      /// current location
      final locationClick = state.location;
      // debugPrint(auth.toString() + locationClick);

      if (auth && !userRole && (locationClick == '/$loginURLPagePath' || locationClick == welcomeURLPagePath)) {
        return homeURLPagePath;
      } else if (auth && userRole && (locationClick == '/$loginURLPagePath' || locationClick == welcomeURLPagePath)) {
        return adminhomeURLPagePath; //adminFeeSetupPath; // communicationPath;// schoolSetupPath; 
      //adminhomeURLPagePath; //; //classWisePaymentPath; //adminFeeSetupPath; // homeWorkPath; //communicationPath; 
      //adminhomeURLPagePath; //adminHelpDeskURLPagePath; //adminhomeURLPagePath; // adminFeeSetupPath;  
      //adminFeeStructureDetailPath;//
      } else if (!auth) {
        return loginURLPagePath;
      }
      return null;
    },

### Screenshots or Video

na

### Logs

na

### Flutter Doctor output

flutter doctor -v
[✓] Flutter (Channel stable, 3.10.0, on macOS 13.2.1 22D68 darwin-arm64, locale en-IN)
    • Flutter version 3.10.0 on channel stable at /Users/puspharaj/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 84a1e904f4 (4 weeks ago), 2023-05-09 07:41:44 -0700
    • Engine revision d44b5a94c9
    • Dart version 3.0.0
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/puspharaj/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS and macOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.75.1)
    • VS Code at /Users/puspharaj/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.64.0

[✓] VS Code (version 1.78.2)
    • VS Code at /Applications/Visual Studio Code 2.app/Contents
    • Flutter extension version 3.64.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.2.1 22D68 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 114.0.5735.90

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

**Comment by huycozy** [comment] 2023-06-05 09:48
@Puspharaj  Which `go_router` version are you using? I checked this issue with [redirection.dart](https://github.com/flutter/packages/blob/main/packages/go_router/example/lib/redirection.dart) but it works as expected. The login screen is cleared after navigating to home screen. You can check this by pressing back button on Android device on Home screen. It will quit app as expected.

**Comment by Puspharaj** [comment] 2023-06-05 10:52
How about flutter web! Thanks

**Comment by maRci002** [comment] 2023-06-05 12:17
I think this is limitation of underlying `RouterDelegate` #97993

**Comment by huycozy** [comment] 2023-06-06 03:53
@Puspharaj As I can see, it also works as expected on Web platform:

<details>
<summary>Demo Web</summary>

https://github.com/flutter/flutter/assets/104349824/f4ae4d37-aa55-43a1-9582-ef5380718546
</details>

It may be caused by your logic inside `redirect` callback. I would recommend you double-check your implementation there and refer to sample code I linked above as well. 

I will close this issue from here. If you still face this issue, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code so that we may verify this. Thank you!

**Closed by huycozy** 2023-06-06 03:53 UTC
Labels: in triage

**Comment by Puspharaj** [comment] 2023-06-06 04:48
@huycozy would you please share the code as well? thanks!

**Comment by huycozy** [comment] 2023-06-06 05:42
You can try it here: [redirection.dart](https://github.com/flutter/packages/blob/main/packages/go_router/example/lib/redirection.dart)

**Comment by Puspharaj** [comment] 2023-06-08 12:11
cool, but the things if i use shellroute, this doesn't allow me to navigate within the shell routes!

**Comment by huycozy** [comment] 2023-06-08 12:17
That's another open issue here: https://github.com/flutter/flutter/issues/114559. Please follow up on it for further updates.
