### ISSUE TITLE
Interaction event is not work When the view is above the IFrameElement。

### ISSUE THREAD

**Issue by MisariLin** [flutter/flutter#88758] opened 2021-08-24 02:24 UTC
When the view is on top of the IFrameElement, all interaction events seem to be unresponsive. I tried Stable Branch, bate Branch and Master Branch. This problem exists.The interaction event seems to be responded to by the following iframe.

https://user-images.githubusercontent.com/22948486/130545682-904d0889-c17b-40e6-a838-1feb3e92a50c.mov

<details>
  <summary>Logs</summary>

this is my code.

```
import 'dart:html';
import 'dart:ui' as ui;

import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final IFrameElement _iframeElement = IFrameElement();

  late Widget _iframeWidget;

  @override
  void initState() {
    super.initState();
    String htmlId = 'imIframeElement';
    _iframeElement.src =
        "https://www.google.com/maps/preview" + "&output=embed";
    _iframeElement.style.border = 'none';
    _iframeElement.id = htmlId;

    ui.platformViewRegistry.registerViewFactory(
      htmlId,
      (int viewId) => _iframeElement,
    );
    _iframeWidget = HtmlElementView(
      key: UniqueKey(),
      viewType: htmlId,
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Row(
        children: <Widget>[
          Expanded(child: _iframeWidget),
          Expanded(
            child: GestureDetector(
              onTap: () {
                showAlert();
              },
              child: Container(
                color: Colors.red,
              ),
            ),
          )
        ],
      ),
    );
  }

  @override
  void dispose() {
    super.dispose();
    _iframeElement.contentWindow!.close();
  }

  showAlert() {
    showDialog(
        context: context,
        builder: (BuildContext context) {
          return GestureDetector(
            onTap: () {
              print("Dialog Action");
              Navigator.of(context).pop();
            },
            child: Container(margin: EdgeInsets.all(40), color: Colors.yellow),
          );
        });
  }
}

```

```
MacBook-Pro:~ linwei$ flutter doctor -v
[✓] Flutter (Channel master, 2.5.0-7.0.pre.211, on macOS 11.4 20F71 darwin-x64,
    locale zh-Hans-CN)
    • Flutter version 2.5.0-7.0.pre.211 at /Users/linwei/fvm/versions/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 56b681247d (89 minutes ago), 2021-08-23 20:44:05 -0400
    • Engine revision 926ce0d855
    • Dart version 2.15.0 (build 2.15.0-43.0.dev)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/linwei/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.

[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.59.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.4 20F71 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 92.0.4515.159

! Doctor found issues in 1 category.
```
</details>

**Comment by TahaTesser** [comment] 2021-08-24 10:45
Hi @MisariLin 
This is a duplicate of https://github.com/flutter/flutter/issues/54027, it is solved by using [pointer_interceptor](https://pub.dev/packages/pointer_interceptor), it is an official party package for this use 
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-08-24 10:45 UTC
Labels: in triage
