### ISSUE TITLE
[android] Platform views obstruct other widgets on android 5.1

### ISSUE THREAD

**Issue by aminesnip** [flutter/flutter#104444] opened 2022-05-23 19:49 UTC
## Steps to Reproduce

- Run the code sample below

<details>
<summary>code sample</summary>

```dart
body: Stack(
  children: <Widget>[
    GoogleMap(
      onMapCreated: _onMapCreated,
      initialCameraPosition: CameraPosition(
        target: _center,
        zoom: 11.0,
      ),
    ),
    Padding(
      padding: const EdgeInsets.all(16.0),
      child: Align(
        alignment: Alignment.topRight,
        child: FloatingActionButton(
          onPressed: () => print('button pressed'),
          materialTapTargetSize: MaterialTapTargetSize.padded,
          backgroundColor: Colors.green,
          child: const Icon(Icons.map, size: 36.0),
        ),
      ),
    ),
  ],
),
```
</details>

| Expected results | Actual results |
| -- | -- |
| ![image](https://user-images.githubusercontent.com/23212012/169895367-01a921c8-ea59-4bc4-b1b2-37e9c7743faa.png) | ![image](https://user-images.githubusercontent.com/23212012/169895493-1d212b96-2bdc-40fe-98ea-f9151d86b8ac.png) |

**Comment by danagbemava-nc** [comment] 2022-05-24 08:02
Hi @aminesnip, thanks for filing the issue.

- What version of flutter were you using prior to upgrading to 3.0.1? 
- Is this issue occurring only on android 5.1?
- What device(s) have you tested this on?

Please also provide the output of `flutter doctor -v`. 

Thank you

**Comment by aminesnip** [comment] 2022-05-24 10:03
Hi @danagbemava-nc, thanks for your response.

- I was using flutter v2.10.5.
- I tested it on emulator and other devices, it works fine. But when I test on samsung e500h (android 5.1.1) the problem appears.
- I even tested the example at https://pub.dev/packages/google_maps_flutter#sample-usager.

import 'dart:async';
import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      title: 'Flutter Google Maps Demo',
      home: MapSample(),
    );
  }
}

class MapSample extends StatefulWidget {
  const MapSample({Key? key}) : super(key: key);

  @override
  State<MapSample> createState() => MapSampleState();
}

class MapSampleState extends State<MapSample> {
  final Completer<GoogleMapController> _controller = Completer();

  static const CameraPosition _kGooglePlex =  CameraPosition(
    target: LatLng(37.42796133580664, -122.085749655962),
    zoom: 14.4746,
  );

  static const CameraPosition _kLake = CameraPosition(
      bearing: 192.8334901395799,
      target: LatLng(37.43296265331129, -122.08832357078792),
      tilt: 59.440717697143555,
      zoom: 19.151926040649414);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: GoogleMap(
        mapType: MapType.hybrid,
        initialCameraPosition: _kGooglePlex,
        onMapCreated: (GoogleMapController controller) {
          _controller.complete(controller);
        },
      ),
      floatingActionButton: FloatingActionButton.extended(
        onPressed: _goToTheLake,
        label: const Text('To the lake!'),
        icon: const Icon(Icons.directions_boat),
      ),
    );
  }

  Future<void> _goToTheLake() async {
    final GoogleMapController controller = await _controller.future;
    controller.animateCamera(CameraUpdate.newCameraPosition(_kLake));
  }
}

Here is the result : 
![image](https://user-images.githubusercontent.com/23212012/170005978-304a2339-a93f-4178-ace7-3a7bfee31b96.png)


flutter doctor -v
[√] Flutter (Channel stable, 3.0.1, on Microsoft Windows [version 10.0.19042.1466], locale en-US)
    • Flutter version 3.0.1 at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (4 days ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Snip\AppData\Local\Android\sdk
    • Platform android-32, build-tools 30.0.3
    • Java binary at: D:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop for Windows (Visual Studio Enterprise 2022 17.2.1)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Enterprise
    • Visual Studio Enterprise 2022 version 17.2.32516.85
    X Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop development with C++" workload, and include these components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK

[√] Android Studio (version 2021.2)
    • Android Studio at D:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] VS Code (version 1.67.2)
    • VS Code at C:\Users\Snip\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.40.0

[√] Connected device (4 available)
    • SM E500H (mobile) • 31c0dc64 • android-arm    • Android 5.1.1 (API 22)
    • Windows (desktop) • windows  • windows-x64    • Microsoft Windows [version 10.0.19042.1466]
    • Chrome (web)      • chrome   • web-javascript • Google Chrome 101.0.4951.67
    • Edge (web)        • edge     • web-javascript • Microsoft Edge 101.0.1210.47

[√] HTTP Host Availability
    • All required HTTP hosts are available

**Comment by danagbemava-nc** [comment] 2022-05-25 12:26
Hi @aminesnip, this isn't actually an issue with the Google Maps plugin, but an issue with platform-views on that version of android.

> you can use an emulator with an android 5.1.1 if you wanna try it locally.

My main host system doesn't seem to support running the old emulators. I got a different machine that supports running android 5 emulators and was able to reproduce it.

This occurs even with the `Webview` plugin, only on android 5.1. I tested on android 6 and 12 and it worked as expected on both versions.

<details>
<summary>screenshots</summary>

The android 5.1 simulator is on the left and android 6 on the right

### flutter 2.10.5
![25 05 2022_10 43 53_REC](https://user-images.githubusercontent.com/88313112/170259552-0cf3bd4d-ba53-4603-9344-51d80b3e32a0.png)


### flutter 3+
![25 05 2022_10 37 25_REC](https://user-images.githubusercontent.com/88313112/170259583-21c064a5-4159-4711-82c5-d8f3215e2d99.png)

</details>

<details>
<summary>code sample</summary>

```dart
import 'dart:io';
import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      title: 'Flutter Google Maps Demo',
      home: MapSample(),
    );
  }
}

class MapSample extends StatefulWidget {
  const MapSample({Key? key}) : super(key: key);

  @override
  State<MapSample> createState() => MapSampleState();
}

class MapSampleState extends State<MapSample> {

  @override
  void initState() {
    super.initState();
    if(Platform.isAndroid) {
      WebView.platform = AndroidWebView();
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: const WebView(
       initialUrl: 'https://flutter.dev',
      ),
      floatingActionButton: FloatingActionButton.extended(
        onPressed: () {},
        label: const Text('To the lake!'),
        icon: const Icon(Icons.directions_boat),
      ),
    );
  }
}
```
</details>

<details>
<summary>flutter doctor -v</summary>

```
[√] Flutter (Channel unknown, 2.10.5, on Microsoft Windows [Version 10.0.19043.1706], locale en-GH)
    • Flutter version 2.10.5 at c:\src\sdks\rc\flutter
    • Upstream repository unknown
    • Framework revision 5464c5bac7 (5 weeks ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[!] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at C:\Users\Deana\AppData\Local\Android\sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.1.4)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.1.32407.343
    • Windows 10 SDK version 10.0.22000.0

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] VS Code (version 1.67.2)
    • VS Code at C:\Users\Deana\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.40.0

[√] Connected device (6 available)
    • M2007J20CG (mobile)                • 5dd3be00      • android-arm64  • Android 11 (API 30)
    • Android SDK built for x86 (mobile) • emulator-5556 • android-x86    • Android 5.1.1 (API 22) (emulator)
    • Android SDK built for x86 (mobile) • emulator-5558 • android-x86    • Android 6.0 (API 23) (emulator)
    • Windows (desktop)                  • windows       • windows-x64    • Microsoft Windows [Version 10.0.19043.1706]
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 101.0.4951.67
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 101.0.1210.53
    ! Device emulator-5554 is offline.

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

```
[√] Flutter (Channel stable, 3.0.1, on Microsoft Windows [Version 10.0.19043.1706], locale en-GH)
    • Flutter version 3.0.1 at C:\src\sdks\stable\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (6 days ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

[!] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at C:\Users\Deana\AppData\Local\Android\sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.1.4)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.1.32407.343
    • Windows 10 SDK version 10.0.22000.0

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] VS Code (version 1.67.2)
    • VS Code at C:\Users\Deana\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.40.0

[√] Connected device (6 available)
    • M2007J20CG (mobile)                • 5dd3be00      • android-arm64  • Android 11 (API 30)
    • Android SDK built for x86 (mobile) • emulator-5556 • android-x86    • Android 5.1.1 (API 22) (emulator)
    • Android SDK built for x86 (mobile) • emulator-5558 • android-x86    • Android 6.0 (API 23) (emulator)
    • Windows (desktop)                  • windows       • windows-x64    • Microsoft Windows [Version 10.0.19043.1706]
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 101.0.4951.67
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 101.0.1210.53
    ! Device emulator-5554 is offline.

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

```
[√] Flutter (Channel master, 3.1.0-0.0.pre.897, on Microsoft Windows [Version 10.0.19043.1706], locale en-GH)
    • Flutter version 3.1.0-0.0.pre.897 at c:\src\sdks\master\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 680a8192b0 (7 hours ago), 2022-05-24 21:23:09 -0700
    • Engine revision 7274f79325
    • Dart version 2.18.0 (build 2.18.0-149.0.dev)
    • DevTools version 2.13.1

[!] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at C:\Users\Deana\AppData\Local\Android\sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.1.4)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.1.32407.343
    • Windows 10 SDK version 10.0.22000.0

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] VS Code (version 1.67.2)
    • VS Code at C:\Users\Deana\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.40.0

[√] Connected device (6 available)
    • M2007J20CG (mobile)                • 5dd3be00      • android-arm64  • Android 11 (API 30)
    • Android SDK built for x86 (mobile) • emulator-5556 • android-x86    • Android 5.1.1 (API 22) (emulator)
    • Android SDK built for x86 (mobile) • emulator-5558 • android-x86    • Android 6.0 (API 23) (emulator)
    • Windows (desktop)                  • windows       • windows-x64    • Microsoft Windows [Version 10.0.19043.1706]      
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 101.0.4951.67
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 101.0.1210.53
    ! Device emulator-5554 is offline.

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

</details>

**Comment by aminesnip** [comment] 2022-05-25 12:45
Hi @danagbemava-nc, thanks for your response.
I am glad that you were able to reproduce the issue. I hope the Flutter team will fix it very soon.

Thank you

**Comment by maheshmnj** [comment] 2022-05-27 13:18
Probably related to https://github.com/flutter/flutter/issues/103630

**Comment by blasten** [comment] 2022-06-01 17:58
yes, this is related to https://github.com/flutter/flutter/issues/103630

**Comment by stuartmorgan** [comment] 2023-01-12 14:32
Closing as a duplicate of https://github.com/flutter/flutter/issues/103630

**Closed by stuartmorgan** 2023-01-12 14:32 UTC
Labels: severe: regression, platform-android, engine, a: platform-views, e: OS Version specific, has reproducible steps, P4, found in release: 3.0, found in release: 3.1
