### ISSUE TITLE
Rendering Issue LineageOS

### ISSUE THREAD

**Issue by SebastianKlaiber** [flutter/flutter#113593] opened 2022-10-18 09:34 UTC
It looks like there are rendering issues with Flutter and LineageOS. Screenshot has been attached. It also doesn't matter which Flutter app is opened, the result is always the same. It has also been tested with the Wonderous App or Flutter Gallery

## Steps to Reproduce

1. Run any Flutter App on LineageOS  17.1

</details>
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.4, on Ubuntu 22.04.1 LTS 5.15.0-50-generic,
    locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version
    33.0.0-rc1)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2021.3)
[✓] VS Code
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!
<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

![Screenshot from 2022-10-18 11-24-06](https://user-images.githubusercontent.com/59142/196391949-a7b34fc4-4f98-4f83-ad0e-62d73c15eb71.png)

**Comment by danagbemava-nc** [comment] 2022-10-18 09:41
Closing this as a duplicate of https://github.com/flutter/flutter/issues/105093. 

Kindly follow up in the original issue for updates. 

Thank you

**Closed by danagbemava-nc** 2022-10-18 09:41 UTC
Labels: in triage
