### ISSUE TITLE
[webview_flutter] Cannot clear cache on Android using webViewController.clearCache()

### ISSUE THREAD

**Issue by kbokarius** [flutter/flutter#53122] opened 2020-03-23 19:08 UTC
#52661  Steps to Reproduce

1. Implement Flutter WebView into a test app and run on Android
2. Login into any website
3. Run webViewController.clearCache()
4. Refresh the page

**Expected results:**
The cache and session are cleared and you are logged out of the website. This works as expected on iOS.

**Actual results:**
The session is not cleared and the website stays logged in.

This appears to be an issue that has existed for some time. See: https://stackoverflow.com/questions/57021584/flutters-webview-how-to-clear-session-status

**Comment by Dancovich** [comment] 2020-03-24 19:36
Encountered the same issue and this is the stack trace. Aparently the method isn't implemented on the Android side of the plugin.

```
E/flutter (29508): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method clearCache on channel plugins.flutter.io/webview_0)
E/flutter (29508): #0      MethodChannel.invokeMethod 
package:flutter/…/services/platform_channel.dart:319
E/flutter (29508): <asynchronous suspension>
E/flutter (29508): #1      MethodChannelWebViewPlatform.clearCache 
package:webview_flutter/src/webview_method_channel.dart:82
E/flutter (29508): #2      WebViewController.clearCache 
package:webview_flutter/webview_flutter.dart:591
E/flutter (29508): #3      _GovBrOauthViewState.dispose 
package:appmeugov/…/auth/oauth_webview.dart:49
E/flutter (29508): #4      StatefulElement.unmount 
package:flutter/…/widgets/framework.dart:4435
E/flutter (29508): #5      _InactiveElements._unmount 
package:flutter/…/widgets/framework.dart:1748
E/flutter (29508): #6      _InactiveElements._unmount.<anonymous closure> 
package:flutter/…/widgets/framework.dart:1746
E/flutter (29508): #7      SingleChildRenderObjectElement.visitChildren 
package:flutter/…/widgets/framework.dart:5433
E/flutter (29508): #8      _InactiveElements._unmount 
package:flutter/…/widgets/framework.dart:1744
E/flutter (29508): #9      _InactiveElements._unmount.<anonymous closure> 
package:flutter/…/widgets/framework.dart:1746
E/flutter (29508): #10     ComponentElement.visitChildren 
package:flutter/…/widgets/framework.dart:4272
E/flutter (29508): #11     _InactiveElements._unmount 
package:flutter/…/widgets/framework.dart:1744
E/flutter (29508): #12     _InactiveElements._unmount.<anonymous closure> 
package:flutter/…/widgets/framework.dart:1746
E/flutter (29508): #13     SingleChildRenderObjectElement.visitChildren 
package:flutter/…/widgets/framework.dart:5433
E/flutter (29508): #14     _InactiveElements._unmount 
package:flutter/…/widgets/framework.dart:1744
E/flutter (29508): #15     _InactiveElements._unmount.<anonymous closure> 
package:flutter/…/widgets/framework.dart:1746
E/flutter (29508): #16     SingleChildRenderObjectElement.visitChildren 
package:flutter/…/widgets/framework.dart:5433
E/flutter (29508): #17     _InactiveElements._unmount 
package:flutter/…/widgets/framework.dart:1744
E/flutter (29508): #18     _InactiveElements._unmount.<anonymous closure> 
package:flutter/…/widgets/framework.dart:1746
E/flutter (29508): #19     ComponentElement.visitChildren 
package:flutter/…/widgets/framework.dart:4272
E/flutter (29508): #20     _InactiveElements._unmount 
package:flutter/…/widgets/framework.dart:1744
E/flutter (29508): #21     _InactiveElements._unmount.<anonymous closure> 
package:flutter/…/widgets/framework.dart:1746
E/flutter (29508): #22     SingleChildRenderObjectElement.visitChildren 
package:flutter/…/widgets/framework.dart:5433
E/flutter (29508): #23     _InactiveElements._unmount 
package:flutter/…/widgets/framework.dart:1744
E/flutter (29508): #24     _InactiveElements._unmount.<anonymous closure> 
package:flutter/…/widgets/framework.dart:1746
E/flutter (29508): #25     SingleChildRenderObjectElement.visitChildren 
package:flutter/…/widgets/framework.dart:5433
E/flutter (29508): #26     _InactiveElements._unmount 
package:flutter/…/widgets/framework.dart:1744
E/flutter (29508): #27     _InactiveElements._unmount.<anonymous closure> 
package:flutter/…/widgets/framework.dart:1746
E/flutter (29508): #28     ComponentElement.visitChildren 
package:flutter/…/widgets/framework.dart:4272
E/flutter (29508): #29     _InactiveElements._unmount 
package:flutter/…/widgets/framework.dart:1744
E/flutter (29508): #30     _InactiveElements._unmount.<anonymous closure> 
package:flutter/…/widgets/framework.dart:1746
E/flutter (29508): #31     ComponentElement.visitChildren 
package:flutter/…/widgets/framework.dart:4272
E/flutter (29508): #32     _InactiveElements._unmount 
package:flutter/…/widgets/framework.dart:1744
E/flutter (29508): #33     _InactiveElements._unmount.<anonymous closure> 
package:flutter/…/widgets/framework.dart:1746
E/flutter (29508): #34     ComponentElement.visitChildren 
package:flutter/…/widgets/framework.dart:4272
E/flutter (29508): #35     _InactiveElements._unmount 
package:flutter/…/widgets/framework.dart:1744
E/flutter (29508): #36     _InactiveElements._unmount.<anonymous closure> 
package:flutter/…/widgets/framework.dart:1746
E/flutter (29508): #37     SingleChildRenderObjectElement.visitChildren 
package:flutter/…/widgets/framework.dart:5433
E/flutter (29508): #38     _InactiveElements._unmount 
package:flutter/…/widgets/framework.dart:1744
E/flutter (29508): #39     _InactiveElements._unmount.<anonymous closure>
```

**Comment by wurstnudl** [comment] 2020-03-28 19:08
Same for me. Currently testing on an emulator and a device, both sporting Android 10.

**Comment by kbokarius** [comment] 2020-03-28 19:16
This is a very impactful issue, please fix @FlutterTeam.

**Comment by jackChauT** [comment] 2020-04-08 09:37
I have this problem too.

**Comment by davedega** [comment] 2020-05-01 11:19
same problem

**Comment by lqk9511** [comment] 2020-05-19 07:38
same problem

**Comment by saturov** [comment] 2020-05-24 05:35
Same issue here. It's so blocking. Would it be ever resolved?

**Comment by bitk0der** [comment] 2020-05-28 16:10
Are you sure the website is not using cookies for session? Maybe you should try to clear cookies.

**Comment by kbokarius** [comment] 2020-05-29 14:23
> Are you sure the website is not using cookies for session? Maybe you should try to clear cookies.

That’s definitely not the issue. We tried every possible way to clear cache/cookies, it seems that the implementation on Android is either missing or broken.

**Comment by RaashVision** [comment] 2020-06-09 07:15
Same problem.

**Comment by kbokarius** [comment] 2020-10-29 19:11
How is this major issue still not resolved? Is there a workaround?

**Comment by kbokarius** [comment] 2020-10-30 02:26
For those looking to simply clear cookies, we just found this command:

```
CookieManager().clearCookies(); 
```

This does the trick for us fortunately. If you need all of the cache cleared, then it might not work.

**Comment by wurstnudl** [comment] 2020-11-20 18:47
> For those looking to simply clear cookies, we just found this command:
> 
> ```
> CookieManager().clearCookies(); 
> ```
> 
> This does the trick for us fortunately. If you need all of the cache cleared, then it might not work.

This is unfortunately not enough.

We finally had  to ditch the official plugin. It just lacks too many features.

**Comment by thiagotn** [comment] 2020-12-28 12:17
Same problem! No updates?

**Comment by Tom3652** [comment] 2021-05-31 13:21
Any news about this issue ? 
I just ran into it now and see the last update was in December 2020...
Using ```webview_flutter: 2.0.8``` and : 
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.1, on macOS 11.3.1 20E241 darwin-x64, locale fr-FR)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] Connected device (3 available)
    ! Error: iPhone is not connected. Xcode will continue when iPhone is connected. (code -13)

• No issues found!
```

**Comment by danagbemava-nc** [comment] 2021-08-06 11:44
I am unable to reproduce the issue on the latest `webview_flutter: ^2.0.10` on the latest `master 2.5.0-6.0.pre.21` and `stable 2.2.3`. For reference, I'll provide the code sample I used. You might have to use the CookieManager in the event that the website uses cookie. 

<details>
<summary>code sample</summary>

```dart
import 'dart:io';

import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

class TestCacheClearing extends StatefulWidget {
  const TestCacheClearing({Key? key}) : super(key: key);

  @override
  State<TestCacheClearing> createState() => _TestCacheClearingState();
}

class _TestCacheClearingState extends State<TestCacheClearing> {
  final url = 'https://www.gmail.com';

  WebViewController? _controller;

  @override
  void initState() {
    super.initState();
    if (Platform.isAndroid) WebView.platform = SurfaceAndroidWebView();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: WebView(
        initialUrl: 'flutter.dev',
        javascriptMode: JavascriptMode.unrestricted,
        onWebViewCreated: (WebViewController controller) {
          _controller = controller;
          _controller?.loadUrl(url);
        },
      ),
      floatingActionButton: Column(
        mainAxisAlignment: MainAxisAlignment.end,
        children: [
          FloatingActionButton(
            onPressed: () {
              _controller?.clearCache();
              CookieManager manager = CookieManager();
              manager.clearCookies();
            },
            backgroundColor: Colors.red,
            child: Icon(Icons.clear),
          ),
          SizedBox(height: 10),
          FloatingActionButton(
            onPressed: () {
              _controller?.reload();
            },
            backgroundColor: Colors.green,
            child: Icon(Icons.refresh),
          ),
        ],
      ),
    );
  }
}

```
</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 2.5.0-6.0.pre.21, on macOS 11.5.1 20G80 darwin-arm, locale en-GH)
    • Flutter version 2.5.0-6.0.pre.21 at /Users/nexus/dev/sdks/flutters
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 40e8620a27 (7 hours ago), 2021-08-06 09:14:50 +0430
    • Engine revision 431ac604da
    • Dart version 2.14.0 (build 2.14.0-383.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.58.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.24.0

[✓] Connected device (2 available)
    • M2007J20CG (mobile) • 5dd3be00 • android-arm64  • Android 11 (API 30)
    • Chrome (web)        • chrome   • web-javascript • Google Chrome 92.0.4515.131

• No issues found!
```


```
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.5.1 20G80 darwin-arm, locale en-GH)
    • Flutter version 2.2.3 at /Users/nexus/dev/sdks/flutter
    • Framework revision f4abaa0735 (5 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.58.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.24.0

[✓] Connected device (2 available)
    • M2007J20CG (mobile) • 5dd3be00 • android-arm64  • Android 11 (API 30)
    • Chrome (web)        • chrome   • web-javascript • Google Chrome 92.0.4515.131

• No issues found!
```
</details>

Closing the issue and labelling as fixed. If it doesn't work for anyone, kindly leave a comment and I'll reopen the issue. 

Please do well to provide the output of `flutter doctor -v` as well as a  [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) when posting your comment as this helps us in triage.

Thank you.

**Closed by danagbemava-nc** 2021-08-06 11:44 UTC
Labels: platform-android, plugin, p: first party, p: webview, has reproducible steps, found in release: 1.20
