### ISSUE TITLE
[tool_crash] OSError: OS Error: Can't assign requested address, errno = 49

### ISSUE THREAD

**Issue by ruiyangdev** [flutter/flutter#139627] opened 2023-12-06 07:02 UTC
## Command
```
flutter attach
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
OSError: OS Error: Can't assign requested address, errno = 49
```
#0      _NativeSocket.nativeSetRawOption (dart:io-patch/socket_patch.dart:1790:74)
#1      _NativeSocket.setRawOption (dart:io-patch/socket_patch.dart:1680:5)
#2      _RawDatagramSocket.setRawOption (dart:io-patch/socket_patch.dart:2659:56)
#3      MDnsClient.start (package:multicast_dns/multicast_dns.dart:145:16)
<asynchronous suspension>
#4      MDnsVmServiceDiscovery._pollingVmService (package:flutter_tools/src/mdns_discovery.dart:212:7)
<asynchronous suspension>
#5      MDnsVmServiceDiscovery.queryForAttach (package:flutter_tools/src/mdns_discovery.dart:91:56)
<asynchronous suspension>
#6      MDnsVmServiceDiscovery.getVMServiceUriForAttach (package:flutter_tools/src/mdns_discovery.dart:393:50)
<asynchronous suspension>
#7      AttachCommand._attachToDevice (package:flutter_tools/src/commands/attach.dart:380:22)
<asynchronous suspension>
#8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#9      AttachCommand.runCommand (package:flutter_tools/src/commands/attach.dart:271:5)
<asynchronous suspension>
#10     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1297:27)
<asynchronous suspension>
#11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#12     Co

**Comment by danagbemava-nc** [comment] 2023-12-06 07:11
Closing this as a duplicate of https://github.com/flutter/flutter/issues/97489. 

Kindly subscribe to the original issue for updates. 

Thank you

**Closed by danagbemava-nc** 2023-12-06 07:11 UTC
Labels: in triage
