### ISSUE TITLE
[video_player] The video is not loading only on iOS

### ISSUE THREAD

**Issue by II11II** [flutter/flutter#81672] opened 2021-05-03 09:21 UTC
## Steps to Reproduce
video_player: ^2.1.1

[Link for video that does not load in ios but loads in android](https://dev.yool.uz/api/v1/public/file/view?hashId=JOapl5wkd)

<details>
  <summary>Logs</summary>

```
platformexception(videoerror failed to load video operation stopped null)
```

</details>

**Comment by TahaTesser** [comment] 2021-05-03 11:34
Hi @II11II 
Thanks for filing the issue, I can reproduce the issue on `iOS only (physical & simulator), video plays fine on Android and Web


<details> 
<summary>code sample</summary> 

```dart
import 'package:video_player/video_player.dart';
import 'package:flutter/material.dart';

void main() => runApp(VideoApp());

class VideoApp extends StatefulWidget {
  @override
  _VideoAppState createState() => _VideoAppState();
}

class _VideoAppState extends State<VideoApp> {
 late VideoPlayerController _controller;

  @override
  void initState() {
    super.initState();
    _controller = VideoPlayerController.network(
        'https://dev.yool.uz/api/v1/public/file/view?hashId=JOapl5wkd')
      ..initialize().then((_) {
        // Ensure the first frame is shown after the video is initialized, even before the play button has been pressed.
        setState(() {});
      });
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Video Demo',
      home: Scaffold(
        body: Center(
          child: _controller.value.isInitialized
              ? AspectRatio(
                  aspectRatio: _controller.value.aspectRatio,
                  child: VideoPlayer(_controller),
                )
              : Container(),
        ),
        floatingActionButton: FloatingActionButton(
          onPressed: () {
            setState(() {
              _controller.value.isPlaying
                  ? _controller.pause()
                  : _controller.play();
            });
          },
          child: Icon(
            _controller.value.isPlaying ? Icons.pause : Icons.play_arrow,
          ),
        ),
      ),
    );
  }

  @override
  void dispose() {
    super.dispose();
    _controller.dispose();
  }
}
``` 

</details>

### Flutter logs don't show anything

<details> 
<summary>logs</summary> 

```console
[  +27 ms] [ 60%] TakingInstallLock
[ +168 ms] [ 65%] PreflightingApplication
[  +26 ms] [ 65%] InstallingEmbeddedProfile
[  +10 ms] [ 70%] VerifyingApplication
[ +101 ms] [ 75%] CreatingContainer
[   +5 ms] [ 80%] InstallingApplication
[  +12 ms] [ 85%] PostflightingApplication
[   +4 ms] [ 90%] SandboxingApplication
[  +14 ms] [ 95%] GeneratingApplicationMap
[  +79 ms] [100%] Installed package build/ios/iphoneos/Runner.app
[ +125 ms] ------ Debug phase ------
[        ] Starting debug of 00008020-001059882212002E (N841AP, iPhone XR, iphoneos, arm64e) a.k.a. 'Taha’s iPhone'
connected through USB...
[ +173 ms] [  0%] Looking up developer disk image
[  +20 ms] [ 95%] Developer disk image mounted successfully
[ +835 ms] [100%] Connecting to remote debug server
[        ] -------------------------
[  +55 ms] (lldb) command source -s 0
'/tmp/DFBD3E56-6F41-46BC-8695-A6F2B61517BF/fruitstrap-lldb-prep-cmds-00008020_001059882212002E'
[        ] Executing commands in
'/tmp/DFBD3E56-6F41-46BC-8695-A6F2B61517BF/fruitstrap-lldb-prep-cmds-00008020_001059882212002E'.
[        ] (lldb)     platform select remote-ios --sysroot '/Users/tahatesser/Library/Developer/Xcode/iOS
DeviceSupport/14.5 (18E199) arm64e/Symbols'
[        ]   Platform: remote-ios
[        ]  Connected: no
[        ]   SDK Path: "/Users/tahatesser/Library/Developer/Xcode/iOS DeviceSupport/14.5 (18E199) arm64e/Symbols"
[        ] (lldb)     target create
"/Users/tahatesser/AndroidStudioProjects/plugins-clone/packages/video_player/video_player/example/build/ios/iphoneos/Runne
r.app"
[+4930 ms] Current executable set to
'/Users/tahatesser/AndroidStudioProjects/plugins-clone/packages/video_player/video_player/example/build/ios/iphoneos/Runne
r.app' (arm64).
[        ] (lldb)     script
fruitstrap_device_app="/private/var/containers/Bundle/Application/871AA81A-D4BD-40C9-B8E6-697C95A3C97E/Runner.app"
[ +455 ms] (lldb)     script fruitstrap_connect_url="connect://127.0.0.1:64049"
[        ] (lldb)     script fruitstrap_output_path=""
[        ] (lldb)     script fruitstrap_error_path=""
[        ] (lldb)     target modules search-paths add /usr "/Users/tahatesser/Library/Developer/Xcode/iOS
DeviceSupport/14.5 (18E199) arm64e/Symbols/usr" /System "/Users/tahatesser/Library/Developer/Xcode/iOS DeviceSupport/14.5
(18E199) arm64e/Symbols/System" "/private/var/containers/Bundle/Application/871AA81A-D4BD-40C9-B8E6-697C95A3C97E"
"/Users/tahatesser/AndroidStudioProjects/plugins-clone/packages/video_player/video_player/example/build/ios/iphoneos"
"/var/containers/Bundle/Application/871AA81A-D4BD-40C9-B8E6-697C95A3C97E"
"/Users/tahatesser/AndroidStudioProjects/plugins-clone/packages/video_player/video_player/example/build/ios/iphoneos"
/Developer "/Users/tahatesser/Library/Developer/Xcode/iOS DeviceSupport/14.5 (18E199) arm64e/Symbols/Developer"
[  +15 ms] (lldb)     command script import
"/tmp/DFBD3E56-6F41-46BC-8695-A6F2B61517BF/fruitstrap_00008020_001059882212002E.py"
[   +4 ms] (lldb)     command script add -f fruitstrap_00008020_001059882212002E.connect_command connect
[        ] (lldb)     command script add -s asynchronous -f fruitstrap_00008020_001059882212002E.run_command run
[        ] (lldb)     command script add -s asynchronous -f fruitstrap_00008020_001059882212002E.autoexit_command autoexit
[        ] (lldb)     command script add -s asynchronous -f fruitstrap_00008020_001059882212002E.safequit_command safequit
[        ] (lldb)     connect
[  +54 ms] (lldb)     run
[ +303 ms] success
[        ] Application launched on the device. Waiting for observatory port.
[+1208 ms] Observatory URL on device: http://127.0.0.1:52500/
[  +10 ms] Attempting to forward device port 52500 to host port 64059
[        ] executing: /Users/tahatesser/Code/flutter_stable/bin/cache/artifacts/usbmuxd/iproxy 64059:52500 --udid
00008020-001059882212002E
[+1013 ms] Forwarded port ForwardedPort HOST:64059 to DEVICE:52500
[   +2 ms] Forwarded host port 64059 to device port 52500 for Observatory
[   +5 ms] Installing and launching... (completed in 19.9s)
[   +5 ms] Caching compiled dill
[ +205 ms] Connecting to service protocol: http://127.0.0.1:64059/
[  +12 ms] [VERBOSE-2:ui_dart_state.cc(186)] Unhandled Exception: PlatformException(VideoError, Failed to load video:
Operation Stopped, null, null)
[  +90 ms] Launching a Dart Developer Service (DDS) instance at http://127.0.0.1:0, connecting to VM service at
http://127.0.0.1:64059/.
[  +83 ms] DDS is listening at http://127.0.0.1:64064/MXSXTBCuXAY=/.
[  +56 ms] Successfully connected to service protocol: http://127.0.0.1:64059/
[  +90 ms] Activating Dart DevTools...
[+1989 ms] Activating Dart DevTools... (completed in 1,989ms)
[ +591 ms] DevFS: Creating new filesystem on the device (null)
[  +46 ms] DevFS: Created new filesystem on the device
(file:///private/var/mobile/Containers/Data/Application/19F92553-1777-488F-8200-FFD9DEE6E186/tmp/example1zjYJB/example/)
[  +15 ms] Updating assets
[ +189 ms] Syncing files to device Taha’s iPhone...
[   +1 ms] <- reset
[        ] Compiling dart to kernel with 0 updated files
[   +2 ms] <- recompile package:video_player_example/main.dart 59c5ec9f-5f98-4e40-933a-b9c241df787f
[        ] <- 59c5ec9f-5f98-4e40-933a-b9c241df787f
[ +122 ms] Updating files.
[        ] DevFS: Sync finished
[        ] Syncing files to device Taha’s iPhone... (completed in 127ms)
[        ] Synced 0.0MB.
[   +1 ms] <- accept
[  +14 ms] Connected to _flutterView/0x15d021820.
[   +2 ms] Flutter run key commands.
[   +3 ms] r Hot reload. 🔥🔥🔥
[   +1 ms] R Hot restart.
[        ] h Repeat this help message.
[        ] d Detach (terminate "flutter run" but leave application running).
[        ] c Clear the screen
[        ] q Quit (terminate the application on the device).
[        ] An Observatory debugger and profiler on Taha’s iPhone is available at: http://127.0.0.1:64064/MXSXTBCuXAY=/
[   +1 ms] 
           Flutter DevTools, a Flutter debugger and profiler, on Taha’s iPhone is available at:
           http://127.0.0.1:9103?uri=http%3A%2F%2F127.0.0.1%3A64064%2FMXSXTBCuXAY%3D%2F
[        ] 💪 Running with sound null safety 💪

```

</details>

### Xcode logs has `PlatformException(VideoError, Failed to load video: Operation Stopped, null, null)`
<details> 
<summary>logs</summary> 

```console
2021-05-03 14:30:45.402491+0300 Runner[4803:505227] Metal API Validation Enabled
2021-05-03 14:30:45.677528+0300 Runner[4803:505481] flutter: Observatory listening on http://127.0.0.1:52722/u0QPW0xwUto=/
2021-05-03 14:30:47.049265+0300 Runner[4803:505470] [VERBOSE-2:ui_dart_state.cc(186)] Unhandled Exception: PlatformException(VideoError, Failed to load video: Operation Stopped, null, null)

```

</details>


<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.0.6, on macOS 11.3 20E232 darwin-x64, locale en-GB)
    • Flutter version 2.0.6 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 1d9032c7e1 (3 days ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (2 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios            • iOS 14.5
    • Chrome (web)           • chrome                    • web-javascript • Google Chrome 90.0.4430.93

• No issues found!
```

```console
[✓] Flutter (Channel master, 2.3.0-1.0.pre.205, on macOS 11.3 20E232 darwin-x64, locale en-GB)
    • Flutter version 2.3.0-1.0.pre.205 at /Users/tahatesser/Code/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 96e4b47f5d (21 hours ago), 2021-05-02 07:24:01 -0700
    • Engine revision 3e578c6e0d
    • Dart version 2.14.0 (build 2.14.0-48.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2021.1.1)
    • IntelliJ at /Volumes/Extreme/IntelliJ IDEA CE.app
    • Flutter plugin version 55.1.5
    • Dart plugin version 211.7233

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (2 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios            • iOS 14.5
    • Chrome (web)           • chrome                    • web-javascript • Google Chrome 90.0.4430.93

• No issues found!

```
		
</details>

**Comment by II11II** [comment] 2021-05-03 12:09
Hi @TahaTesser 🖐
I found why this issue appears
If server-side does not deal with a `range` field in the header of HTTP(PARTIAL CONTENT) which send by an ios video player and just send all data, video_player in the ios part throws this exception

**Comment by TahaTesser** [comment] 2021-05-03 12:55
@II11II 
That looks like https://github.com/flutter/flutter/issues/56665
Closing as duplicate of https://github.com/flutter/flutter/issues/56665

**Closed by TahaTesser** 2021-05-03 12:55 UTC
Labels: found in release: 2.0, found in release: 2.3, has reproducible steps, p: first party, p: video_player, platform-ios, plugin, severe: crash

**Comment by WSDDi** [comment] 2021-05-20 02:20
链接为未在ios中加载但在android中加载的视频

**Comment by WSDDi** [comment] 2021-05-20 02:21
> 链接为未在ios中加载但在android中加载的视频
web端使用video_player打开视频，ios上黑屏且无法播放，安卓可以播放
