### ISSUE TITLE
Error when running demo app on iOS

### ISSUE THREAD

**Issue by diyoyo** [flutter/flutter#5566] opened 2016-08-24 07:15 UTC
## Steps to Reproduce

If I create a new app with "flutter create myapp" and then try to launch it either on Simulator or on my iPod Touch, then I have the following error:
**error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.**

This is only resolved by performing a 'pod install' in the ios folder.

## Flutter Doctor

[✓] Flutter (on Mac OS, channel alpha)
    • Flutter at /Users/Yoyo/flutter
    • Framework revision 9a0a0d9903 (11 days ago), engine revision f8d80c4617

[✓] Android toolchain - develop for Android devices (Android SDK 24.0.0-preview)
    • Android SDK at /Yoyo/AndroidSDK
    • Platform android-N, build-tools 24.0.0-preview
    • Java(TM) SE Runtime Environment (build 1.8.0_91-b14)

[✓] iOS toolchain - develop for iOS devices (Xcode 7.3.1)
    • XCode at /Applications/Xcode.app/Contents/Developer
    • Xcode 7.3.1, Build version 7D1014

[✓] Atom - a lightweight development environment for Flutter
    • flutter plugin version 0.2.4
    • dartlang plugin version 0.6.37

**Comment by eseidelGoogle** [comment] 2016-08-24 14:49
@collinjackson is this caused by the podfile you recently added?  FYI @chinmaygarde

**Comment by collinjackson** [comment] 2016-08-24 14:59
flutter doctor indicates an old revision of Flutter, can you try again with the latest master?

**Comment by collinjackson** [comment] 2016-08-24 15:02
I believe this is a duplicate of #5398, which was fixed in #5432

**Closed** 2016-08-24 15:02 UTC
Labels: ⌺‬ platform-ios

**Comment by diyoyo** [comment] 2016-08-24 19:46
Thanks, how can I update to latest master?
I followed the "Set up..." steps yesterday, and that's the version I got....

**Comment by eseidelGoogle** [comment] 2016-08-24 19:57
FYI @danrubel and @devoncarew, please correct me if I'm wrong:  I believe `flutter upgrade` is the right command, which will update your copy of flutter.  Depending on what setup instructions you followed you may be set to use `alpha` rather than `master`.  `flutter doctor` can tell you.

**Comment by diyoyo** [comment] 2016-08-24 20:07
Ok Thanks. Indeed "flutter upgrade" was not "working" since I had cloned the alpha version. I removed it and cloned the master properly and now it works.
But that means all newcomers, like me, that follow the online tutorial will face the same problem...
Cheers

**Comment by eseidelGoogle** [comment] 2016-08-24 20:13
@diyoyo Thanks for the feedback!  I agree we could do a lot to improve our developer workflow including clarifying around how channels work (or even making them stable).
