### ISSUE TITLE
Plugin url_launcher-5.7.2 uses or overrides a deprecated API

### ISSUE THREAD

**Issue by pachecofc** [flutter/flutter#67122] opened 2020-10-02 09:26 UTC
## Steps to Reproduce

Install url_launcher: ^5.5.2 declared as a dependency in pubspec.yaml.
Run Flutter template app on an Android simulator or physical device.
The following message appears on the Terminal:
Note: /Users/fabiopacheco/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher-5.7.2/android/src/main/java/io/flutter/plugins/urllauncher/WebViewActivity.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

**Comment by Thorbenl** [comment] 2020-10-02 09:29
Using `url_launcher: ^5.7.2` fixed that for me :)

**Comment by pedromassangocode** [comment] 2020-10-02 10:20
Hi @pachecofc 
I can confirm that the issue is fixed on the latest version of the package (`url_launcher: ^5.7.2`).
Please upgrade to the latest package version to get the fix.

Thank you

**Closed by pedromassangocode** 2020-10-02 10:20 UTC

**Comment by wijesijp** [comment] 2020-10-03 17:50
I am using url_launcher: ^5.7.2

I am getting a note 
...AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\url_launcher-5.7.2\android\src\main\java\io\flutter\plugins\urllauncher\WebViewActivity.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

Currently I am using build:gradle:3.5.0 and the project complies 
But if I used the latest version it does not

Is there a fix for this?

**Comment by pedromassangocode** [comment] 2020-10-05 07:50
Please file a new issue for this and completely fill out the template. We don't track more than one problem in a GitHub issue as they may be duplicates of different existing issues, or may need different teams to look at them.

**Comment by muktaahammed** [comment] 2020-10-09 01:44
> Using `url_launcher: ^5.7.2` fixed that for me :)

url_launcher-5.7.2\android\src\main\java\io\flutter\plugins\urllauncher\WebViewActivity.java uses or overrides a deprecated API

I am using same as you. But still getting same message. Why ? Have any changes in Android Manifest ?
