### ISSUE TITLE
[Web] prevent scroll by spacebar if textfield is in focus

### ISSUE THREAD

**Issue by devanflores** [flutter/flutter#74189] opened 2021-01-18 12:33 UTC
Currently, if we are using a flutter textfield and type in the space bar, the entire page is scrolled downward. There should be a focus priority to prevent scrolling by spacebar if a textfield is in focus.

**Comment by TahaTesser** [comment] 2021-01-18 14:32
duplicate of https://github.com/flutter/flutter/issues/74191

**Closed by TahaTesser** 2021-01-18 14:32 UTC
