### ISSUE TITLE
[only v1.12.13+hotfix.3] Tapping with more than one finger (quickly) results in exception

### ISSUE THREAD

**Issue by ninnepinne** [flutter/flutter#46668] opened 2019-12-10 10:11 UTC
How to reproduce:
1. Setup GestureDetector
2. Listen on tapUp
3. Quickly drum the tap area with more than one finger (not simultaneous tap but intermittent like for example index - middle - index - middle ... finger)

NOTE: Even though the drumming gesture is not common it can easily happen by misstake - that is how I found it on a normal tap area.

Easily reproducible on both Android and iOS:

```dart
import 'package:flutter/material.dart';
import 'package:flutter/widgets.dart';

void main() {
  runApp(MaterialApp(
    builder: (context, child) {
      return Tapper();
    },
  ));
}

class Tapper extends StatefulWidget {
  Tapper({Key key}) : super(key: key);

  @override
  State<StatefulWidget> createState() => _TapperViewState();
}

class _TapperViewState extends State<Tapper> {
  int _currentIndex = 1;

  @override
  Widget build(BuildContext context) {
    return Material(
      child: GestureDetector(
        onTapUp: (TapUpDetails details) => _onTapUp(context),
        child: ListView.builder(
          padding: const EdgeInsets.all(20),
          itemCount: _currentIndex,
          itemBuilder: (_, int index) {
            return Text(
              'MSG $index',
              textAlign: TextAlign.center,
              style: TextStyle(
                color: Colors.red,
              ),
            );
          },
        ),
      ),
    );
  }

  void _onTapUp(BuildContext context) {
    setState(() {
      _currentIndex++;
    });
  }
}
```
The error:

```
I/flutter ( 7522): NoSuchMethodError: The getter 'position' was called on null.
I/flutter ( 7522): Receiver: null
I/flutter ( 7522): Tried calling: position
I/flutter ( 7522): 
I/flutter ( 7522): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
I/flutter ( 7522): #1      TapGestureRecognizer.handleTapDown (package:flutter/src/gestures/tap.dart:457:28)
I/flutter ( 7522): #2      BaseTapGestureRecognizer._checkDown (package:flutter/src/gestures/tap.dart:256:5)
I/flutter ( 7522): #3      BaseTapGestureRecognizer.didExceedDeadline (package:flutter/src/gestures/tap.dart:227:5)
I/flutter ( 7522): #4      PrimaryPointerGestureRecognizer.didExceedDeadlineWithEvent (package:flutter/src/gestures/recognizer.dart:493:5)
I/flutter ( 7522): #5      PrimaryPointerGestureRecognizer.addAllowedPointer.<anonymous closure> (package:flutter/src/gestures/recognizer.dart:446:40)
I/flutter ( 7522): #6      _rootRun (dart:async/zone.dart:1122:38)
I/flutter ( 7522): #7      _CustomZone.run (dart:async/zone.dart:1023:19)
I/flutter ( 7522): #8      _CustomZone.runGuarded (dart:async/zone.dart:925:7)
I/flutter ( 7522): #9      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
I/flutter ( 7522): #10     _rootRun (dart:async/zone.dart:1126:13)
I/flutter ( 7522): #11     _CustomZone.run (dart:async/zone.dart:1023:19)
I/flutter ( 7522): #12     _CustomZone.bindCallback.<anonymous closure> (dart:async/zon

```

Flutter doctor output:
```
[✓] Flutter (Channel beta, v1.12.13+hotfix.3, on Mac OS X 10.15.1 19B88, locale en-SE)
    • Flutter version 1.12.13+hotfix.3 at /Users/fredrik.dahlen/DEV/flutter
    • Framework revision 57f2df76d7 (4 days ago), 2019-12-05 21:23:21 -0800
    • Engine revision ac9391978e
    • Dart version 2.7.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/fredrik.dahlen/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/fredrik.dahlen/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.35.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.1.0

[✓] Connected device (3 available)
    • SM G930F                  • 988673304b32425853                       • android-arm64 • Android 8.0.0 (API 26)
    • Android SDK built for x86 • emulator-5554                            • android-x86   • Android 10 (API 29) (emulator)
    • Fredrik’s iPhone          • f6414d51c92a4d1e13c55cc0b2b04547651d022b • ios           • iOS 13.1.3

• No issues found!
```

**Comment by ninnepinne** [comment] 2019-12-10 10:31
Very likely related to:
https://github.com/flutter/flutter/issues/44144

But completely different way of provoking the error.

**Comment by ninnepinne** [comment] 2019-12-10 11:06
Hmm.
More investigating lead me to:
https://github.com/flutter/flutter/pull/45943

Seems to fix the issue.

Not able to reproduce this on Master channel.

@dkwingsmt How will this fix propagate down the channels?

**Comment by iapicca** [comment] 2019-12-10 11:14
Tested with `master` works as intended
<details>
  <summary>flutter doctor -v</summary>

```bash
[√] Flutter (Channel master, v1.13.1-pre.80, on Microsoft Windows [Version 10.0.19013.1122], locale en-US)
    • Flutter version 1.13.1-pre.80 at C:\src\flutter
    • Framework revision 2fe9623c36 (2 hours ago), 2019-12-10 04:22:32 -0500
    • Engine revision 12bf95fd49
    • Dart version 2.7.0 (build 2.7.0-dev.2.1 8b8894648f)

 
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\iapic\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)        
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code, 64-bit edition (version 1.40.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.7.0

[√] Connected device (3 available)
    • Pixel 3a   • 965AY0WP5C • android-arm64  • Android 10 (API 29)
    • Chrome     • chrome     • web-javascript • Google Chrome 78.0.3904.108
    • Web Server • web-server • web-javascript • Flutter Tools

• No issues found!
```

</details>

**Comment by ninnepinne** [comment] 2019-12-10 11:17
@iapicca Should I close the issue?

**Comment by iapicca** [comment] 2019-12-10 11:20
Hi @ninnepinne 
I'd keep it open for now, until the fix propagates;
I'll try to remember to check when the new release is out.
thanks for your efficiency

**Comment by HansMuller** [comment] 2019-12-11 16:12
CC @dkwingsmt

**Comment by dkwingsmt** [comment] 2019-12-11 17:12
I believe it should be fixed by that PR. I’m not familiar with our hotfix policy though, cc @Hixie

**Comment by adigest** [comment] 2019-12-26 08:19
```
[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.16299.1296], locale zh-CN)
    • Flutter version 1.12.13+hotfix.5 at C:\ProgramFile_Developer\flutter
    • Framework revision 27321ebbad (2 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0
```
have the same problem

**Comment by JohnSnooow** [comment] 2020-01-09 14:17
> ```
> [√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.16299.1296], locale zh-CN)
>     • Flutter version 1.12.13+hotfix.5 at C:\ProgramFile_Developer\flutter
>     • Framework revision 27321ebbad (2 weeks ago), 2019-12-10 18:15:01 -0800
>     • Engine revision 2994f7e1e6
>     • Dart version 2.7.0
> ```
> 
> have the same problem

 Have u solve it, v1.12.13+hotfix5 Same problem

**Comment by ninnepinne** [comment] 2020-01-09 16:50
@adigest @JohnSnooow 
Beta channel v1.12.13+hotfix6 does not have this problem.

Let's hope hotfix6 reaches stable channel soon...

**Comment by HansMuller** [comment] 2020-01-09 18:18
I'm going to close this issue, since it has been fixed (https://github.com/flutter/flutter/issues/46668#issuecomment-572651497).

**Closed by HansMuller** 2020-01-09 18:18 UTC
Labels: f: gestures, severe: crash, waiting for PR to land (fixed)
