### ISSUE TITLE
[web] Transparent page background after using platform view

### ISSUE THREAD

**Issue by deakjahn** [flutter/flutter#59868] opened 2020-06-19 17:30 UTC
## Steps to Reproduce

1. Use the repro package [canvas_test.zip](https://github.com/flutter/flutter/files/4805981/canvas_test.zip)*,
2. Run it in Flutter Web using CanvasKit (don't worry about the plugin registry error message),
3. Tap on the button in the corner,
4. Observe the background of the incoming page carefully.

\* The code actually creates a platform view and this is what triggers the problem.

**Expected results:**

Opaque background.

**Actual results:**

The background is somewhat transparent, the previous page is visible (both the scaffold top and the body). Not very much, be attentive. :-) Try different background colors. It seems that the problem only shows in about half of the clicks, not every single time.

![Annotation 2020-06-19 192235](https://user-images.githubusercontent.com/2234271/85163433-1c07c880-b263-11ea-81f7-21134270ddd2.png)

<details>
  <summary>Doc</summary>

```
[√] Flutter (Channel beta, 1.19.0-4.1.pre, on Microsoft Windows [Version 10.0.19041.329], locale en-US)
    • Flutter version 1.19.0-4.1.pre at E:\Android\flutter-beta
    • Framework revision f994b76974 (10 days ago), 2020-06-09 15:53:13 -0700
    • Engine revision 9a28c3bcf4
    • Dart version 2.9.0 (build 2.9.0-14.1.beta)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at e:\Android\Sdk
    • Platform android-29, build-tools 30.0.0
    • ANDROID_HOME = e:\Android\Sdk
    • ANDROID_SDK_ROOT = e:\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • CHROME_EXECUTABLE = e:\Android\chrome.bat

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (2 available)
    • Web Server • web-server • web-javascript • Flutter Tools
    • Chrome     • chrome     • web-javascript • Google Chrome 83.0.4103.106

• No issues found!
```

</details>

**Comment by deakjahn** [comment] 2020-06-20 16:37
I actually think there is much more going on in the background (pun intended) than just aesthetic problems but I can't cram it into a simple reproducible package. The first page is simply not removed and its supporting JS code can seriously crash with the code of the new page. I can push it to the browser becoming completely unresponsive if the incoming page also has platform views or other custom JS code.

**Comment by TahaTesser** [comment] 2020-06-22 09:21
Hi @deakjahn 
Tried your code repository on latest `beta` on Mac and Windows, there is no transparent background, both locally and deployed


`flutter run -d chrome --release --dart-define=FLUTTER_WEB_USE_SKIA=true`
`flutter build web --release --dart-define=FLUTTER_WEB_USE_SKIA=true`

https://determined-goldwasser-7371a5.netlify.app/#/

<img width="577" alt="Screenshot 2020-06-22 at 2 46 47 PM" src="https://user-images.githubusercontent.com/48603081/85271050-df70e280-b497-11ea-9a30-b6e55b33a4b5.png">


<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel beta, 1.19.0-4.1.pre, on Mac OS X 10.15.5 19F101, locale
    en-GB)
    • Flutter version 1.19.0-4.1.pre at /Users/tahatesser/Code/flutter_beta
    • Framework revision f994b76974 (12 days ago), 2020-06-09 15:53:13 -0700
    • Engine revision 9a28c3bcf4
    • Dart version 2.9.0 (build 2.9.0-14.1.beta)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (4 available)
    • SM M305F      • 32003c30dc19668f          • android-arm64  • Android 10
      (API 29)
    • Taha’s iPhone • 00008020-001059882212002E • ios            • iOS 13.5.1
    • Web Server    • web-server                • web-javascript • Flutter Tools
    • Chrome        • chrome                    • web-javascript • Google Chrome
      83.0.4103.106

• No issues found!
``` 

</details>

**Comment by deakjahn** [comment] 2020-06-22 09:31
Right with that net repository of yours, I get the semi-transparent background at least half of the time but not always, there are a few clicks that lead to correct display. Tried with Chrome latest, Vivaldi latest (Chromium inside) and Edge latest, all of them exhibit the problem.

**Comment by iapicca** [comment] 2020-06-24 14:08
Hi @deakjahn 
I see the same behavior on linux

![image](https://user-images.githubusercontent.com/45637986/85571948-424fae80-b63d-11ea-819f-e3986b87ac73.png)

Thank you for reporting this

**Comment by yjbanov** [comment] 2020-06-25 20:55
Does the transparency happen during transition or remains after the transition completes? Is there opacity < 1.0 anywhere on the UI?

I ask because there are some limitations in transparency accuracy for opacity values 0 < opacity < 1.0. This should not happen when the view is completely transparent (i.e. opacity == 0) or completely opaque (i.e. opacity == 1).

**Comment by deakjahn** [comment] 2020-06-25 22:23
Yes, it remains. All the screenshots I took were weel after the pages were supposed to be changed. But as I wrote in the comment above, I'm quite convinced that the transparency itself is the least of our worries. What seems to be more sinister that the outgoing page doesn't disappear. You know the internal functioning of the framework, not me :-), but I suppose a route change means the previous route is actually discarded, isn't it? In this case, it stays there and clashes with the JS of the incoming page. So even is the background were actually opaque and the page below couldn't be seen, I'm afraid, the problems would remain.

**Comment by yjbanov** [comment] 2020-06-25 23:05
Can you please file a separate issue about the previous route not disappearing? That area is a bit fuzzy for me. I mostly worry about pixels :) The two issues would be addressed in different codebases (engine vs framework).

**Comment by deakjahn** [comment] 2020-06-26 10:52
@yjbanov Done. Hope it will help.

**Comment by TahaTesser** [comment] 2021-02-02 13:54
Hi @deakjahn @iapicca 
Tried to reproduce this on Chrome, Firefox, Safari, I cannot see the transparent page issue.
Can you please try on the latest `beta` or `master`? 

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel beta, 1.25.0-8.3.pre, on macOS 11.1 20C69 darwin-x64, locale en-GB)
    • Flutter version 1.25.0-8.3.pre at /Users/tahatesser/Code/flutter_beta
    • Framework revision 5d36f2e7f5 (3 weeks ago), 2021-01-14 15:57:49 -0800
    • Engine revision 7a8f8ca02c
    • Dart version 2.12.0 (build 2.12.0-133.7.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0

[✓] Connected device (2 available)
    • Taha’s iPad (mobile) • 00008020-000255113EE8402E • ios            • iOS 14.4
    • Chrome (web)         • chrome                    • web-javascript • Google Chrome 88.0.4324.96
    ! Error: Taha’s iPad is busy: Copying cache files from device. Xcode will continue when Taha’s iPad is finished. (code -10)

• No issues found!
```
```bash
[✓] Flutter (Channel master, 1.26.0-18.0.pre.128, on macOS 11.1 20C69 darwin-x64, locale en-GB)
    • Flutter version 1.26.0-18.0.pre.128 at /Users/tahatesser/Code/flutter_master
    • Framework revision 502ff3dbfe (59 minutes ago), 2021-02-02 05:41:03 -0500
    • Engine revision 7334085fc1
    • Dart version 2.12.0 (build 2.12.0-281.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0

[✓] Connected device (4 available)
    • RMX2001 (mobile)                   • EUYTFEUSQSRGDA6D • android-arm64  • Android 10 (API 29)
    • Android SDK built for x86 (mobile) • emulator-5554    • android-x86    • Android 10 (API 29) (emulator)
    • macOS (desktop)                    • macos            • darwin-x64     • macOS 11.1 20C69 darwin-x64
    • Chrome (web)                       • chrome           • web-javascript • Google Chrome 88.0.4324.96

• No issues found!
```

</details>
Thank you

**Comment by iapicca** [comment] 2021-02-02 15:29
@TahaTesser 
tested with `flutter run -d chrome --release --dart-define=FLUTTER_WEB_USE_SKIA=true`

<details>
<summary>screenshots</summary>

![home_test](https://user-images.githubusercontent.com/45637986/106622038-d7c00300-657b-11eb-8fd7-969669c2133c.png)
![second_test](https://user-images.githubusercontent.com/45637986/106622042-d8589980-657b-11eb-915b-2657e9e62078.png)

</details>

<details>
<summary>doctor</summary>

```console
[✓] Flutter (Channel master, 1.26.0-18.0.pre.121, on Linux, locale en_US.UTF-8)
    • Flutter version 1.26.0-18.0.pre.121 at /home/francesco/snap/flutter/common/flutter
    • Framework revision 225e408d4f (12 hours ago), 2021-02-01 22:26:03 -0500
    • Engine revision e59457b818
    • Dart version 2.12.0 (build 2.12.0-279.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/francesco/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_SDK_ROOT = /home/francesco/Android/Sdk
    • Java binary at: /usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_275-8u275-b01-0ubuntu1~20.04-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /snap/bin/chromium

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] Connected device (3 available)
    • Pixel 3a (mobile) • 965AY0WP5C • android-arm64  • Android 11 (API 30)
    • Linux (desktop)   • linux      • linux-x64      • Linux
    • Chrome (web)      • chrome     • web-javascript • Chromium 88.0.4324.96 snap

! Doctor found issues in 1 category.
```

</details>

**Comment by deakjahn** [comment] 2021-02-02 18:21
Unfortunately, on first try. I still remember (and can read back) that this didn't occur on every single click but it did on the first tap for me. :-(

<details>
E:\Android\flutter-beta\bin\flutter.bat doctor --verbose
[√] Flutter (Channel beta, 1.25.0-8.3.pre, on Microsoft Windows [Version 10.0.19042.746], locale en-US)
    • Flutter version 1.25.0-8.3.pre at E:\Android\flutter-beta
    • Framework revision 5d36f2e7f5 (3 weeks ago), 2021-01-14 15:57:49 -0800
    • Engine revision 7a8f8ca02c
    • Dart version 2.12.0 (build 2.12.0-133.7.beta)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at e:\Android\Sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_SDK_ROOT = e:\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (1 available)
    • Edge (web) • edge • web-javascript • Microsoft Edge 88.0.705.56
</details>

As you can see, this is Edge. As soon as I noted that the new, Chromium-based Edge debugs Flutter just fine, I removed Chrome that I don't use for regular browsing, anyway (I do use a Chromium-based browser, Vivaldi, but not Chrome directly).

![Screenshot 2021-02-02 191709](https://user-images.githubusercontent.com/2234271/106644752-ca127980-658b-11eb-9547-18ea69ab77ed.png)

**Comment by TahaTesser** [comment] 2021-02-03 11:26
@deakjahn 
Can you please upgrade to the latest `master` and try again
Thank you

**Comment by pedromassangocode** [comment] 2021-02-26 13:17
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by deakjahn** [comment] 2021-02-26 13:27
Here we go again... :-)

**Comment by maheshmnj** [comment] 2023-01-11 04:29
@deakjahn Is this still reproducible? I verified the issue on the latest master channel and it seems to render fine.
I verified in chrome and safari and the routes render fine.

<img width="936" alt="Screenshot 2023-01-10 at 11 28 03 PM" src="https://user-images.githubusercontent.com/31410839/211717755-ce5bbef5-d10b-497f-bc67-c4ab5ac6c37a.png">


<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel master, 3.7.0-13.0.pre.131, on macOS 13.1 22C65 darwin-arm64, locale en-IN)
    • Flutter version 3.7.0-13.0.pre.131 on channel master at /Users/mahesh/Development/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 0196e6050b (2 days ago), 2022-12-31 11:10:23 -0500
    • Engine revision 932591ec04
    • Dart version 3.0.0 (build 3.0.0-76.0.dev)
    • DevTools version 2.20.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks
      and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.74.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.56.0

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • 026D5789-9E78-4AD5-B1B2-3F8D4E7F65E4 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 13.1 22C65 darwin-arm64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 108.0.5359.124

[✓] HTTP Host Availability
    • All required HTTP hosts are available
    
• No issues found!
```
```
[✓] Flutter (Channel stable, 3.3.9, on macOS 12.6 21G115 darwin-arm, locale en-IN)
    • Flutter version 3.3.9 on channel stable at /Users/mahesh/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b8f7f1f986 (24 hours ago), 2022-11-23 06:43:51 +0900
    • Engine revision 8f2221fbef
    • Dart version 2.18.5
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.70.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.53.20221101

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • 026D5789-9E78-4AD5-B1B2-3F8D4E7F65E4 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.6 21G115 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 107.0.5304.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Closed** 2023-02-01 05:09 UTC
Labels: waiting for customer response, engine, platform-web, severe: rendering, e: web_canvaskit, has reproducible steps, found in release: 1.19, P4
