### ISSUE TITLE
Flutter AWS Cognito Token showing invalid signature

### ISSUE THREAD

**Issue by Tapasm1212** [flutter/flutter#71897] opened 2020-12-08 08:10 UTC
I am stared developing a flutter project with AWS Cognito login features. In flutter, AWS Cognito login was working fine and I am getting the access token but when checking that in API or JWT its shows the error "Invalid Signature".

<img width="1677" alt="Screenshot 2020-12-07 at 11 32 04 AM" src="https://user-images.githubusercontent.com/14312152/101456850-a69bcb80-395a-11eb-9c82-a14dbdb43e63.png">

I add the below code for the AWS Cognito login features. I have installed the amplify_auth_cognito: '<1.0.0' in pubspec.yaml file to create the AWS Cognito login features in the app. Login codes working fine and perfectly but the token which returns from that code shows "Invalid Signature".

```dart
 Future<String> _signIn(LoginData data) async {
try {
  SignInResult res = await Amplify.Auth.signIn(
    username: data.name,
    password: data.password,
  );
  final resp = await Amplify.Auth.fetchAuthSession(
    options: CognitoSessionOptions(getAWSCredentials: true),
  );
  if (resp.isSignedIn) {
    final sess = resp as CognitoAuthSession;
    print("TOKEN FROM THE COGNITO: ${sess.userPoolTokens.accessToken}");
  }
  setState(() {
    isSignedIn = res.isSignedIn;
  });
  if (isSignedIn) {
    _btnController.success();
    AWSConfigurationHelper().getUserDetails();

    Timer(Duration(seconds: 1), () {
      _btnController.reset();
      Navigator.pushReplacementNamed(context, DeviceList.routeName);
    });
  }
} on AuthError catch (e) {
  Alert(
    context: context,
    type: AlertType.error,
    title: "Login Failed",
    desc: e.cause.toString(), //e.toString(),
  ).show();

  _btnController.error();

  Timer(Duration(seconds: 1), () {
    _btnController.reset();
  });

  print(e.cause);

  for (final exception in e.exceptionList) {
    print(exception.exception);
    print(exception.detail);
  }

  return 'Log In Error: ' + e.toString();
}}`
```
My pubspec.yaml file screenshot was attached. In that file I am using amplify_auth_cognito: '<1.0.0' for the Cognito login.

<img width="1366" alt="Screenshot 2020-12-07 at 11 22 11 AM" src="https://user-images.githubusercontent.com/14312152/101456987-e1056880-395a-11eb-992b-8754c7107220.png">

I am new to this Flutter so I really need someone help to fix this problem. I have done the AWS Cognito Login features in iOS and web with the same AWS credentials but there I am not getting this type of "Invalid Signature" issue in the access token. Someone, please help me because I am not any good link where this type of issue has been discussed.

Thanks in advance

**Comment by TahaTesser** [comment] 2020-12-08 08:30
Hi @Tapasm1212 
From what I can see, the issue is related to a 3rd party plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/aws-amplify/amplify-flutter/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by TahaTesser** 2020-12-08 08:30 UTC
