### ISSUE TITLE
[file_selector_web] cannot read files larger than ~500MB

### ISSUE THREAD

**Issue by CDDelta** [flutter/flutter#76036] opened 2021-02-15 03:04 UTC
## Steps to Reproduce
1. Use `file_selector.openFile()` and pick a file ~500-700MB on web.
2. Read it into memory using `readAsBytes()`.

**Expected results:**

The file data can be loaded into memory.

Browsers can support buffer sizes of ~2GB so a ~500-700MB file should not fail. [`file_picker_cross`](https://pub.dev/packages/file_picker_cross) is able to load files larger than `file_selector_web`.

**Actual results:**

A `RangeError: Array buffer allocation failed` will be thrown.

**Comment by pedromassangocode** [comment] 2021-02-15 10:16
I can reproduce the issue.


<details>
<summary>code sample</summary>

```dart
import 'package:file_selector/file_selector.dart';
import 'package:flutter/material.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  //final sp = SharedPreferences();
  runApp(MaterialApp(home: OpenImagePage()));
}


/// Screen that shows an example of openFiles
class OpenImagePage extends StatelessWidget {
  void _openImageFile(BuildContext context) async {
    final XTypeGroup typeGroup = XTypeGroup(
      label: 'images',
      extensions: ['mp4'],
    );
    final XFile file = await openFile(acceptedTypeGroups: [typeGroup]);
    final bytes = await file.readAsBytes();
    final String fileName = file.name;
    final String filePath = file.path;
    print(fileName);
    print(filePath);
    print(bytes);
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Open an image"),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            ElevatedButton(
              style: ElevatedButton.styleFrom(
                primary: Colors.blue,
                onPrimary: Colors.white,
              ),
              child: Text('Press to open an image file(png, jpg)'),
              onPressed: () => _openImageFile(context),
            ),
          ],
        ),
      ),
    );
  }
}
```
</details>



```console
Performing hot restart...
[+37410 ms] Skipping target: gen_localizations
[   +1 ms] complete
[  +16 ms] Scanned through 519 files in 14ms
Waiting for connection from debug service on Chrome...
[   +2 ms] <- recompile org-dartlang-app:/web_entrypoint.dart efd71fae-174b-4819-8de6-fc2b5180bf91
[        ] package:flutter_example/main.dart
[        ] <- efd71fae-174b-4819-8de6-fc2b5180bf91
[ +394 ms] Synced 0.0MB.
[        ] <- accept
[        ] DwdsVmClient: Attempting a hot restart
[        ] DwdsVmClient: Attempting to disabling breakpoints and resume the isolate
[   +6 ms] DwdsVmClient: Successfully disabled breakpoints and resumed the isolate
[        ] DwdsVmClient: Attempting to get execution context ID.
[        ] DwdsVmClient: Got execution context ID.
[        ] DwdsVmClient: Issuing $dartHotRestart request.
[ +111 ms] ChromeProxyService: Initializing expression compiler for my/root/path/main_module.bootstrap.js with sound null safety: false
[  +65 ms] DwdsVmClient: $dartHotRestart request complete.
[        ] DwdsVmClient: Waiting for Isolate Start event.
[        ] DwdsVmClient: Successful hot restart
[   +1 ms] Restarted application in 605ms.
[+22216 ms] Ambient Study Music To Concentrate - 4 Hours of Music for Studying, Concentration and Memory.mp4
[   +1 ms] blob:http://localhost:51608/5bdbcdb7-a395-421c-b641-c6f9acd91dad
[        ] []
[  +11 ms] RangeError: Array buffer allocation failed
               at new ArrayBuffer (<anonymous>)
               at new Uint8Array (<anonymous>)
               at Function._create1 (http://localhost:51608/my/root/path/dart_sdk.js:31030:14)
               at Function.new (http://localhost:51608/my/root/path/dart_sdk.js:30997:49)
               at convert._ByteCallbackSink.new.add (http://localhost:51608/my/root/path/dart_sdk.js:46619:59)
               at _RootZone.runUnaryGuarded (http://localhost:51608/my/root/path/dart_sdk.js:38940:11)
               at _BufferingStreamSubscription.new.[_sendData] (http://localhost:51608/my/root/path/dart_sdk.js:32557:22)
               at _IterablePendingEvents.new.handleNext (http://localhost:51608/my/root/path/dart_sdk.js:35897:32)
               at async._AsyncCallbackEntry.new.callback (http://localhost:51608/my/root/path/dart_sdk.js:35834:16)
               at Object._microtaskLoop (http://localhost:51608/my/root/path/dart_sdk.js:39301:13)
               at _startMicrotaskLoop (http://localhost:51608/my/root/path/dart_sdk.js:39307:13)
               at http://localhost:51608/my/root/path/dart_sdk.js:34814:9

```

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel master, 1.27.0-2.0.pre.101, on macOS 11.2 20D64 darwin-x64, locale en-AO)
    • Flutter version 1.27.0-2.0.pre.101 at /Users/pedromassango/Code/flutter_master
    • Framework revision c2ee916a5d (3 hours ago), 2021-02-14 23:01:04 -0500
    • Engine revision 1d537824d6
    • Dart version 2.13.0 (build 2.13.0-30.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 53.1.5
    • Dart plugin version 203.6912

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.2 20D64 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 88.0.4324.150

! Doctor found issues in 1 category.
```

</details>

**Comment by cyanglaz** [comment] 2021-02-18 19:15
cc @ditman

**Comment by ditman** [comment] 2021-02-18 22:21
This is probably a bug in [the _bytes getter of cross_file](https://github.com/flutter/plugins/blob/master/packages/cross_file/lib/src/types/html.dart#L80), I'll take a look!

**Comment by kasyr** [comment] 2021-04-02 16:54
Any update on this? I have exactly the same issue with image_picker_for_web in version 2.0.0 when picking a video above 500mb.

**Comment by ditman** [comment] 2021-04-02 22:54
After null-safety, my next bug has to do with HtmlElementView at the framework level, because it affects several plugins (and anybody using HtmlElementView to render an iframe, or their own content, pretty much).

This is definitely high in the rest of the priority list, but I still don't have an ETA of when I'll start working on it. I'll keep the thread posted, of course!

**Comment by ditman** [comment] 2021-08-04 00:29
I'm taking a look at this, attempting to reproduce this with the current versions of the plugin (they're identical to the old ones, so this should reproduce now in the `cross_file` package)

**Comment by ditman** [comment] 2021-08-04 20:00
I reproduced this in my linux machine with a 4GB file, I guess the maximum size depends on the system.

**Comment by ditman** [comment] 2021-08-05 00:55
Just for kicks, I used my 4GB file with file_picker_cross, and I get a similar error, in a slightly different place ([here](https://gitlab.com/testapp-system/file_picker_cross/-/blob/master/lib/src/file_picker_web.dart#L30)):

```
Error: Expected a value of type 'Uint8List', but got one of type 'Null'
    at Object.throw_ [as throw] (http://localhost:44459/dart_sdk.js:5061:11)
    at Object.castError (http://localhost:44459/dart_sdk.js:5020:15)
    at Object.cast [as as] (http://localhost:44459/dart_sdk.js:5345:17)
    at Function.as_C [as as] (http://localhost:44459/dart_sdk.js:4966:19)
    at
    http://localhost:44459/packages/file_picker_cross/src/file_picker_web.dart.l
    ib.js:137:156
    at Object._checkAndCall (http://localhost:44459/dart_sdk.js:5268:16)
    at Object.dcall (http://localhost:44459/dart_sdk.js:5273:17)
    at FileReader.<anonymous> (http://localhost:44459/dart_sdk.js:101824:100)
```

For some file size, the browser is going to return "Null" instead of the read bytes. I'm going to try a little bit harder finding a file size that causes the exact error described in this issue.

**Comment by ditman** [comment] 2021-08-05 01:35
I'm having trouble reproducing the issue, I cannot verify the following:

* I cannot get the same error as @CDDelta reported. Can you please let me know what OS + Browser (with versions) are you using?
* I cannot validate this claim: `file_picker_cross` is able to load files larger than `file_selector_web`. I couldn't find any file that does open using one plugin but not another.

I'm using Linux and Chrome Version 92.0.4515.131 (Official Build) (64-bit)

I'm opening a 1.6GB file. I cannot open a 2.1GB file (but in that case both plugins crash).

**Comment by CDDelta** [comment] 2021-08-05 01:51
I have since moved on from the project that had this issue so I can't be of much help here, unfortunately.

**Comment by pedromassango** [comment] 2021-08-05 07:38
@ditman you can find the OS information in my comment: https://github.com/flutter/flutter/issues/76036#issuecomment-779117508

I was using A MacBook pro (with probably a BigSur OS) and Chrome as the web browser

**Comment by ditman** [comment] 2021-08-05 16:24
@kasyr can you provide more details? What OS + Browser combo were you using? Is this still happening to you?

**Comment by ditman** [comment] 2021-08-05 18:43
@pedromassango I totally missed the doctor expansion right underneath the logs! Thanks!!

I see Chrome 88 in macos 11.2, I'll try to replicate there!

Thanks again!

**Comment by ditman** [comment] 2021-08-05 21:44
I've attempted to reproduce the same crash with Chrome 88 (same version as reported by Pedro) and couldn't reproduce the issue neither in my Linux nor my Mac machines. I also couldn't find any file that did work in one plugin but not the other.

Here's the code I used when testing both plugins (a slightly modified version of @pedromassango's):

<details>

<summary><tt>main.dart</tt> (file_selector)</summary>

```dart
import 'package:file_selector/file_selector.dart';
import 'package:flutter/material.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  //final sp = SharedPreferences();
  runApp(MaterialApp(home: OpenImagePage()));
}

/// Screen that shows an example of openFiles
class OpenImagePage extends StatelessWidget {
  void _openImageFile(BuildContext context) async {
    final Stopwatch stopwatch = Stopwatch()..start();
    final XTypeGroup typeGroup = XTypeGroup(
      label: 'Video files',
      extensions: ['mp4'],
    );
    final XFile file = (await openFile(acceptedTypeGroups: [typeGroup]))!;
    // Not very useful, this depends on the user selecting the file.
    print('Loaded in ${stopwatch.elapsedMilliseconds} ms');
    stopwatch.reset();
    print(file.name);
    print(file.path);
    final int length = await file.length();
    print('${length / 1024 / 1024} MB, in ${stopwatch.elapsedMicroseconds} μs');
    stopwatch.reset();
    final bytes = await file.readAsBytes(); // Returns an empty array for >2GB files.
    print('readAsBytes, in ${stopwatch.elapsedMilliseconds} ms');
    print('bytes length: ${bytes.length}');
    stopwatch.reset();
    print('First 10 bytes: ${bytes.sublist(0, 10)}, in ${stopwatch.elapsedMicroseconds} μs');
    stopwatch.reset();
    print('Last 10 bytes: ${bytes.sublist(length - 10)}, in ${stopwatch.elapsedMicroseconds} μs');
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text("Open video file_selector"),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            ElevatedButton(
              style: ElevatedButton.styleFrom(
                primary: Colors.blue,
                onPrimary: Colors.white,
              ),
              child: const Text('Press to open a file'),
              onPressed: () => _openImageFile(context),
            ),
          ],
        ),
      ),
    );
  }
}

```

</details>

<details>

<summary><tt>main.dart</tt> (file_picker_cross)</summary>

```dart
import 'package:file_picker_cross/file_picker_cross.dart';
import 'package:flutter/material.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  //final sp = SharedPreferences();
  runApp(MaterialApp(home: OpenImagePage()));
}

/// Screen that shows an example of openFiles
class OpenImagePage extends StatelessWidget {
  void _openImageFile(BuildContext context) async {
    final Stopwatch stopwatch = Stopwatch()..start();
    final FilePickerCross file = await FilePickerCross.importFromStorage(
      type: FileTypeCross.video,
    ); // Throws exception for >2GB files.
    print('Loaded in ${stopwatch.elapsedMilliseconds} ms');
    stopwatch.reset();
    print(file.fileName);
    print(file.path);
    final int length = file.length;
    print('${length / 1024 / 1024} MB, in ${stopwatch.elapsedMicroseconds} μs');
    stopwatch.reset();
    final bytes = file.toUint8List();
    print('readAsBytes, in ${stopwatch.elapsedMilliseconds} ms');
    print('bytes length: ${bytes.length}');
    stopwatch.reset();
    print('First 10 bytes: ${bytes.sublist(0, 10)}, in ${stopwatch.elapsedMicroseconds} μs');
    stopwatch.reset();
    print('Last 10 bytes: ${bytes.sublist(length - 10)}, in ${stopwatch.elapsedMicroseconds} μs');
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text("Open video file_picker_cross"),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            ElevatedButton(
              style: ElevatedButton.styleFrom(
                primary: Colors.blue,
                onPrimary: Colors.white,
              ),
              child: const Text('Press to open a file'),
              onPressed: () => _openImageFile(context),
            ),
          ],
        ),
      ),
    );
  }
}

```

</details>

In my experience, files >2GB make both plugins misbehave. file_selector will return an empty array of bytes when calling `readAsBytes` (however browser-reported metadata will still be available), and file_picker_cross will throw an exception when calling `importFromStorage` (and nothing from the file will be available).

Smaller files seem to be handled correctly by both plugins.

Calling `print(bytes)` causes a big crash, I assume because of the `toString` conversion, but as seen in the example above, the bytes are loaded (you can access the first 10 and the last 10 bytes, and they seem to be consistent across both apps).

(This is most likely a change in the underlying dart behavior that probably got fixed between this bug was reported and now.)

I'm going to close this, but feel free to reopen if  this comes up again!

**Closed by ditman** 2021-08-05 21:44 UTC
Labels: severe: crash, plugin, p: first party, platform-web, has reproducible steps, P5, p: file_selector, found in release: 1.27

**Comment by nwparker** [comment] 2021-08-17 04:09
Hey, @ditman -- can you consider reopening this (or should I open a new issues?)

One would image that you should be able to stream even large files (2gb+), but unfortunately this does not work.

Snippet (complete code attached below):
```dart
    final fileSize = await file.length();
    final chunkStarts = List.generate((fileSize/chunkSize.toDouble()).ceil(), (i) => i * chunkSize);

    for (var chunkStart in chunkStarts){
      final bytes = await file.openRead(chunkStart, min(fileSize, chunkStart + chunkSize)).single;
      print("Streamed ${bytes.length} bytes");
    }
```
<details>
 <summary>main.dart (file_selector w/ chunks)</summary>

```dart
import 'dart:math';

import 'package:file_selector/file_selector.dart';
import 'package:flutter/material.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  //final sp = SharedPreferences();
  runApp(MaterialApp(home: OpenImagePage()));
}

/// Screen that shows an example of openFiles
class OpenImagePage extends StatelessWidget {
  void _openImageFile(BuildContext context) async {
    final Stopwatch stopwatch = Stopwatch()..start();
    final XTypeGroup typeGroup = XTypeGroup(
      label: 'Video files',
      extensions: ['mp4'],
    );
    final XFile file = (await openFile(acceptedTypeGroups: [typeGroup]));
    // Not very useful, this depends on the user selecting the file.
    print('Loaded in ${stopwatch.elapsedMilliseconds} ms');
    stopwatch.reset();
    print(file.name);
    print(file.path);
    final int length = await file.length();
    print('${length / 1024 / 1024} MB, in ${stopwatch.elapsedMicroseconds} μs');
    stopwatch.reset();
    final bytes = await file.readAsBytes(); // Returns an empty array for >2GB files.
    print('readAsBytes, in ${stopwatch.elapsedMilliseconds} ms');
    print('bytes length: ${bytes.length}');
    stopwatch.reset();
    print('First 10 bytes: ${bytes.sublist(0, 10)}, in ${stopwatch.elapsedMicroseconds} μs');
    stopwatch.reset();
    print('Last 10 bytes: ${bytes.sublist(length - 10)}, in ${stopwatch.elapsedMicroseconds} μs');

    print('Will attempt to iterate through stream in chunks');
    final chunkSize = 5000000;
    final fileSize = await file.length();
    final chunkStarts = List.generate((fileSize/chunkSize.toDouble()).ceil(), (i) => i * chunkSize);

    var totalBytesStreamed = 0;
    for (var chunkStart in chunkStarts){
      final bytes = await file.openRead(chunkStart, min(fileSize, chunkStart + chunkSize)).single;
      print("Streamed ${bytes.length} bytes");
      totalBytesStreamed += bytes.length;
    }
    print("Total bytes streamed: $totalBytesStreamed");
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text("Open video file_selector"),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            ElevatedButton(
              style: ElevatedButton.styleFrom(
                primary: Colors.blue,
                onPrimary: Colors.white,
              ),
              child: const Text('Press to open a file'),
              onPressed: () => _openImageFile(context),
            ),
          ],
        ),
      ),
    );
  }
}
```
</details>


The code works on smaller files, but larger files produce the following "RangeError":
`Uncaught (in promise) Error: RangeError (end): Invalid value: Only valid value is 0: 10`

I would expect streaming through chunks of files to work regardless of size as the amount of data being read into memory is capped at a small finite size (20mb in my example code). Any ideas on how to make this work?

**Comment by nwparker** [comment] 2021-08-18 19:51
> Hey, @ditman -- can you consider reopening this (or should I open a new issues?)
> 
> One would image that you should be able to stream even large files (2gb+), but unfortunately this does not work.
> 
> Snippet (complete code attached below):
> 
> ```dart
>     final fileSize = await file.length();
>     final chunkStarts = List.generate((fileSize/chunkSize.toDouble()).ceil(), (i) => i * chunkSize);
> 
>     for (var chunkStart in chunkStarts){
>       final bytes = await file.openRead(chunkStart, min(fileSize, chunkStart + chunkSize)).single;
>       print("Streamed ${bytes.length} bytes");
>     }
> ```
> 
> main.dart (file_selector w/ chunks)
> The code works on smaller files, but larger files produce the following "RangeError":
> `Uncaught (in promise) Error: RangeError (end): Invalid value: Only valid value is 0: 10`
> 
> I would expect streaming through chunks of files to work regardless of size as the amount of data being read into memory is capped at a small finite size (20mb in my example code). Any ideas on how to make this work?

I created #88465
@ditman
