### ISSUE TITLE
Dart analysis fails after upgrade to Flutter 3 in Intellij IDEA

### ISSUE THREAD

**Issue by AlexBurdu** [flutter/flutter#105398] opened 2022-06-05 15:20 UTC
Dart analysis shows `error: Target of URI doesn't exist` for all packages after upgrading to Flutter 3

I've been waiting since the initial Flutter 3 release for a fix to come and since none seems to have arrived, I decided to raise this issue as it makes Flutter 3 unusable for me.

## Steps to Reproduce

1. Use Intellij Idea Ultimate 2022.1.2 or Android Studio 2021.2.1 Patch 1 (probably happens on other versions as well, but I tried on these)
2. Upgrade Flutter from `2.10.5` to `3.0.1`
3. Update pubspec.yaml:

```
environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=3.0.1"
```
4. Update/fix outdated deps failing build
5. Run the application

### What happens?

- **Application builds and runs fine**
- Dart Analysis fails in the IDE and  there is no IDE indexation and support
- All imports are underlined with red and shown as errors

Example of errors:

```
error: Target of URI doesn't exist: 'package:flutter/material.dart'. (uri_does_not_exist at [finance] lib/finance.dart:4)
error: Target of URI doesn't exist: 'package:flutter/services.dart'. (uri_does_not_exist at [finance] lib/finance.dart:5)
error: Target of URI doesn't exist: 'package:flutter_gen/gen_l10n/app_localizations.dart'. (uri_does_not_exist at [finance] lib/finance.dart:6)
error: Target of URI doesn't exist: 'package:flutter_localizations/flutter_localizations.dart'. (uri_does_not_exist at [finance] lib/finance.dart:7)
```

**If I downgrade Flutter the errors go away and dart analysis works fine**

```
flutter downgrade 2.10.5
```

## Logs

<details>
<summary>Logs</summary>

```yaml
version: 1.0.0+1

publish_to: none

environment: # https://docs.flutter.dev/development/tools/sdk/releases
  sdk: ">=2.17.1 <3.0.0" # Dart SDK version
  flutter: ">=3.0.1"

dependencies:
  bloc: ^8.0.0
  collection: ^1.15.0
  dropdown_search: ^5.0.2
  fixnum: ^1.0.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  flutter_localizations: # https://flutter.dev/docs/development/accessibility-and-localization/internationalization
    sdk: flutter
#  flutter_login: ^3.2.0
  http: ^0.13.4
  intl: ^0.17.0
  json_serializable: ^6.1.6
  logger: ^1.0.0
  protobuf: ^2.0.0-nullsafety.0
  session:
    path: ../session

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.1

dev_dependencies:
  bloc_test: ^9.0.0
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  test: ^1.21.1

flutter:
  generate: true    # Add this line
  uses-material-design: true

```

```
[✓] Flutter (Channel stable, 3.0.1, on Ubuntu 20.04.4 LTS 5.4.0-65-generic, locale en_US.UTF-8)
    • Flutter version 3.0.1 at /home/burfee/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (2 weeks ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0-rc5)
    • Android SDK at /home/burfee/apps/AndroidSDK
    • Platform android-31, build-tools 31.0.0-rc5
    • ANDROID_HOME = /home/burfee/apps/AndroidSDK
    • Java binary at: /home/burfee/apps/JetBrains/apps/AndroidStudio/ch-0/212.5712.43.2112.8609683/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[✓] Android Studio (version 2021.2)
    • Android Studio at /home/burfee/apps/JetBrains/apps/AndroidStudio/ch-0/212.5712.43.2112.8609683
    • Flutter plugin version 68.1.2
    • Dart plugin version 212.5744
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.1)
    • IntelliJ at /home/burfee/apps/JetBrains/apps/IDEA-U/ch-0/221.5787.30
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code
    • VS Code at /snap/code/current
    • Flutter extension version 3.13.2

[✓] Connected device (3 available)
    • Pixel 6 (mobile) • 192.168.0.32:8888 • android-arm64  • Android 12 (API 32)
    • Linux (desktop)  • linux             • linux-x64      • Ubuntu 20.04.4 LTS 5.4.0-65-generic
    • Chrome (web)     • chrome            • web-javascript • Google Chrome 102.0.5005.61

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by danagbemava-nc** [comment] 2022-06-06 08:11
Hi @AlexBurdu, do you have this issue when you use `vscode` as well? Or is this only an issue with the Intellij plugins?

**Comment by exaby73** [comment] 2022-06-06 08:17
@AlexBurdu I can see you have an outdated version of the Dart plugin for IntelliJ. Please update the plugin and confirm if it's still happening

**Comment by exaby73** [comment] 2022-06-06 10:50
In your logs for `flutter doctor -v`, I can see that you have an outdated version of the dart plugin installed on Android Studio while the IntelliJ one doesn't show up. Is this happening even after you have installed the latest versions? 

###### Logs mentioned

```
[✓] Android Studio (version 2021.2)
    • Android Studio at /home/burfee/apps/JetBrains/apps/AndroidStudio/ch-0/212.5712.43.2112.8609683
    • Flutter plugin version 68.1.2
    • Dart plugin version 212.5744
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.1)
    • IntelliJ at /home/burfee/apps/JetBrains/apps/IDEA-U/ch-0/221.5787.30
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
```

**Comment by AlexBurdu** [comment] 2022-06-06 11:12
Yes, you're right. I'm not sure why flutter doctor shows it like this, but in Intellij IDEA I have the versions in the above screenshot installed. I had them installed even when running flutter doctor -v. 
I also don't actively use Android Studio, but Intellij IDEA Ultimate. I just gave it a shot to see if the problem reproduces in it. I can retry and come back with an update.

**Comment by exaby73** [comment] 2022-06-06 11:25
That would be great. This is probably an obvious question, forgive me, but IntelliJ shown installed at the path in `flutter doctor` is that same one you're opening right? What I mean is, opening IntelliJ from Ubuntu's applications menu and running `xdg-open` produces the same instance with the same installed plugins?

**Comment by exaby73** [comment] 2022-06-07 07:03
Have you also tried doing the following:

- `flutter clean`
- `flutter pub cache clean`
- `flutter pub get`
- Restart your IDE

**Comment by AlexBurdu** [comment] 2022-06-08 18:26
I tried the above steps, they don't fix the issue. My guess is something is broken in the Intellij plugin for flutter 3. I can try to provide an example when I find the time.

**Comment by exaby73** [comment] 2022-06-08 23:49
Okay. Last thing, on your root project, what's the output of `flutter analyze`? If it's an issue with the Dart Analysis Server, then it should show you the same errors you get in your IDE on the terminal as well. If it doesn't, then it does look like it might be an issue with the plugin. For that, I think it's best for you to raise an issue on [flutter/flutter-intellij][1].

[1]: https://github.com/flutter/flutter-intellij

**Comment by AlexBurdu** [comment] 2022-06-09 20:33
I'm getting similar errors with `flutter analyze`.
My project is structured like this
parent_dir
- flutter_app
- flutter_package

`parent_dir` only contains the 2 subdirs and `flutter_app` depends on `flutter_package`

**Comment by AlexBurdu** [comment] 2022-06-09 20:57
I may be onto something: it seems that under multi-project configuration, the directory `.dart_tool` doesn't get created.

**Comment by exaby73** [comment] 2022-06-10 04:10
Hello. I cloned your project and ran `flutter analyze`. I did not get any errors, other than an unused variable.

###### Logs

```
Analyzing flutter...

   info • The value of the local variable 'calculator' isn't used • flutter_app/lib/main.dart:5:20 • unused_local_variable

1 issue found. (ran in 1.9s)
```

Note: I had to run `flutter pub get` in both the directories by `cd`ing into them, then running the command. This works as intended.

**Comment by AlexBurdu** [comment] 2022-06-11 09:26
hmm, yeah, that fixed it for the example, but doesn't fix the issue in my main project. I'll try other way.
It's frustrating that if I downgrade flutter the problems go away

**Comment by AlexBurdu** [comment] 2022-06-11 10:56
does flutter and/or dart cache the indexed files somewhere else?

If I copy the flutter parent directory to another location, I no longer get the errors.

**Comment by maheshmnj** [comment] 2022-06-13 10:31
I believe this issue could be related to IntelliJ plugin, @AlexBurdu  does this issue occur in vscode too? if not I would suggest filing in the dedicated repo https://github.com/flutter/flutter-intellij/issues

**Comment by AlexBurdu** [comment] 2022-06-13 14:03
@maheshmnj it's not related to intellij, as the issue happens from command line also

**Comment by maheshmnj** [comment] 2022-06-14 13:46
Thanks for the info @AlexBurdu, I did  try cloning your app but the analyzer But the analyzer doesn't show any error 

```
mahesh@mahesh:~/Desktop/flutter_issue_105398/flutter/flutter_app$ flutter analyze
Running "flutter pub get" in flutter_app...                      2,102ms
Analyzing flutter_app...                                                

   info • The value of the local variable 'calculator' isn't used • lib/main.dart:5:20 • unused_local_variable

1 issue found. (ran in 4.0s)
mahesh@mahesh:~$ cd ..
mahesh@mahesh:/home$ cd ~/Desktop/flutter_issue_105398/flutter/
mahesh@mahesh:~/Desktop/flutter_issue_105398/flutter$ cd flutter_package/
mahesh@mahesh:~/Desktop/flutter_issue_105398/flutter/flutter_package$ flutter analyze
Running "flutter pub get" in flutter_package...                  1,987ms
Analyzing flutter_package...                                            
No issues found! (ran in 1.6s)
mahesh@mahesh:~/Desktop/flutter_issue_105398/flutter/flutter_package$ 
```
Do you see those errors with a new created flutter app too?  or only when you create a flutter app that depends on a package

**Comment by AlexBurdu** [comment] 2022-06-14 14:24
https://github.com/flutter/flutter/issues/105398#issuecomment-1152888492

**Comment by exaby73** [comment] 2022-06-15 08:10
Does running `flutter analyze` from the inner app and package directories also produce the same errors? Also can you check if `.dart_tool` is generated?

**Comment by AlexBurdu** [comment] 2022-06-18 14:50
yes, I get the same errors from inner directories or from the parent directory. `.dart_tools` is generated

**Comment by AlexBurdu** [comment] 2022-06-18 14:50
is there any way I can get more logs for debugging this?

**Comment by exaby73** [comment] 2022-06-20 09:21
I'm not sure. Will keep this issue open for insights by the team

**Comment by greglaun** [comment] 2022-07-02 01:24
Is this possibly in a Bazel workspace? Similar behavior happens if the flutter project is in a Bazel workspace, or if it has a WORKSPACE file or directory for other reasons.

See for example

- https://github.com/flutter/flutter/issues/103895#
- https://github.com/Dart-Code/Dart-Code/issues/3972

**Comment by AlexBurdu** [comment] 2022-07-02 04:18
Hi, yes. This is a subdirectory in a Bazel workspace.

**Comment by greglaun** [comment] 2022-07-02 13:12
I had the same issue in a Bazel workspace and confirmed that was the only problem by rsync'ing the Flutter project to temp directory (outside any workspace) and verifying that `dart analyze` works there.

It looks like the bug for tracking this is https://github.com/flutter/flutter/issues/103706. https://github.com/flutter/flutter/issues/103706#issuecomment-1166525627 seems to think there's a fix committed.

Right now the only workaround that works for me is downgrading Flutter. If you don't need it to be in a Bazel workspace, you might also try moving the project as a workaround.

**Comment by AlexBurdu** [comment] 2022-07-03 16:38
it needs to be in the bazel workspace, it's part of a monorepo even if I don't use bazel for building the flutter app.

**Comment by christopherfujino** [comment] 2022-07-11 20:55
Thank you for filing this issue! However, I am going to close it as a duplicate of https://github.com/flutter/flutter/issues/103895. Please follow that issue for for more information and updates. Thanks!

**Closed by christopherfujino** 2022-07-11 20:55 UTC
Labels: severe: crash, tool, dependency: dart
