### ISSUE TITLE
YouTube Player API Support (THE REAL ONE)

### ISSUE THREAD

**Issue by YazeedAlKhalaf** [flutter/flutter#58020] opened 2020-05-26 16:32 UTC
## Use case

I think Flutter needs to support YouTube Player API officially, such as a collaboration between the youtube team and the flutter team. It would be great if that is done, plus I think it would be a little bit easier since it is the same company, Google.

## Proposal

It is a package request, but I did not find a better place for requesting better than here. I think that having an official package for the YouTube Player API would be great.

By official I mean by the flutter.dev team and even collaboration from the community but mainly by the flutter team.

There are some packages that claim to be the Youtube Player API but they are not that great 🙃.

Hope you got the idea 💡

**Comment by whatamelon** [comment] 2020-05-27 04:17
I agree. If Flutter team make youtube plugin, it would be helpful for many flutter developers.

**Comment by TahaTesser** [comment] 2020-05-27 08:35
duplicate of https://github.com/flutter/flutter/issues/13756

**Closed by TahaTesser** 2020-05-27 08:35 UTC
