### ISSUE TITLE
in_app_purchase 0.5.2 [IOS] Without internet connection 'await _connection.queryPastPurchases()' don't return an error. Stop executing at all 

### ISSUE THREAD

**Issue by propertychernetsov** [flutter/flutter#81863] opened 2021-05-04 22:10 UTC
You can try use await InAppPurchaseConnection.instance.queryPastPurchases() on IOS and it don't return an error. On Android everething works.

**Comment by TahaTesser** [comment] 2021-05-05 12:06
Hi @propertychernetsov 
I just tried to reproduce the issue in offline, both platform simply returns `flutter: []`, no error on either platform

> On Android everething works.

You mean it returns an error message on Android>


Please try the minimal code sample I created and provide the error from Android if it returns any

<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/material.dart';
import 'package:in_app_purchase/in_app_purchase.dart';
void main() {
  InAppPurchaseConnection.enablePendingPurchases();
  runApp(MyApp());
}
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}
class Home extends StatefulWidget {
  @override
  _HomeState createState() => _HomeState();
}
class _HomeState extends State<Home> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: ElevatedButton(
          child: Text('Get'),
          onPressed: () async {
            final InAppPurchaseConnection _connection =
                InAppPurchaseConnection.instance;
            final QueryPurchaseDetailsResponse purchaseResponse =
                await _connection.queryPastPurchases();
            print(purchaseResponse.pastPurchases);
          },
        ),
      ),
    );
  }
}
``` 

</details>

<details> 
<summary>logs</summary> 
	
```console
[VERBOSE-2:FlutterObservatoryPublisher.mm(103)] On iOS 14+, local network broadcast in apps need to be declared in the app's Info.plist. Debug and profile Flutter apps and modules host VM services on the local network to support debugging features such as hot reload and DevTools. To make your Flutter app or module attachable and debuggable, add a '_dartobservatory._tcp' value to the 'NSBonjourServices' key in your Info.plist for the Debug/Profile configurations. For more information, see https://flutter.dev/docs/development/add-to-app/ios/project-setup#local-network-privacy-permissions
[VERBOSE-2:FlutterObservatoryPublisher.mm(101)] Failed to register observatory port with mDNS with error -65555.
[VERBOSE-2:FlutterObservatoryPublisher.mm(103)] On iOS 14+, local network broadcast in apps need to be declared in the app's Info.plist. Debug and profile Flutter apps and modules host VM services on the local network to support debugging features such as hot reload and DevTools. To make your Flutter app or module attachable and debuggable, add a '_dartobservatory._tcp' value to the 'NSBonjourServices' key in your Info.plist for the Debug/Profile configurations. For more information, see https://flutter.dev/docs/development/add-to-app/ios/project-setup#local-network-privacy-permissions
Connecting to VM Service at ws://127.0.0.1:57389/-TTCEFcXzoc=/ws
flutter: []

```

</details>


<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.0.6, on macOS 11.3 20E232 darwin-x64, locale en-GB)
    • Flutter version 2.0.6 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 1d9032c7e1 (5 days ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.22.0

[✓] Connected device (3 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios            • iOS 14.5
    • macOS (desktop)        • macos                     • darwin-x64     • macOS 11.3 20E232 darwin-x64
    • Chrome (web)           • chrome                    • web-javascript • Google Chrome 90.0.4430.93

• No issues found!
```
		
</details>

**Comment by nt4f04uNd** [comment] 2021-05-05 13:06
https://github.com/flutter/flutter/issues/78605?

**Comment by TahaTesser** [comment] 2021-05-06 11:13
On Android, it just ends, no error, https://github.com/flutter/flutter/issues/78605#issue-835826901 code sample to reproduce this issue. Both platforms don't return any error 
This is a duplicate of https://github.com/flutter/flutter/issues/78605

**Closed by TahaTesser** 2021-05-06 11:13 UTC
Labels: in triage, waiting for customer response
