### ISSUE TITLE
Add a validator function on the dropdown menu 

### ISSUE THREAD

**Issue by muchirajunior** [flutter/flutter#154975] opened 2024-09-11 05:37 UTC
### Use case

When trying to validate a form where there is a dropdownmenu widget selection it hard to validate because it does not have a option to validate and  you have to do add a manualy check like if statement.

### Proposal

Add an onValidate function to the DropdoenMenu class that will work  with the forms validations.

**Comment by danagbemava-nc** [comment] 2024-09-11 08:57
Closing this as a duplicate of https://github.com/flutter/flutter/issues/152131

**Closed by danagbemava-nc** 2024-09-11 08:57 UTC
Labels: in triage

**Comment by expectopatronam** [comment] 2024-09-20 04:19
Shall i implement this by changing the Textfield to textformfeild and add a validator as argument?
