### ISSUE TITLE
Painting text with TextPainter on scaled canvas doesn't work on iOS with version 3.24.0

### ISSUE THREAD

**Issue by per-activote** [flutter/flutter#153708] opened 2024-08-19 16:43 UTC
### Steps to reproduce

- Create a standard Flutter project
- Modify the Scaffold to have a CustomPaint with a MyTextPainter class
- Print some text to a canvas that is scaled differently in x and y (I used 0.5 and 1.0)
- See that the letters are scaled incorrectly

### Expected results

The text should be displayed scaled horizontally, but not vertically, leading to text where each character takes up half the horizontal space it normally would, but is still as high as normal.

### Actual results

On Android and web the text is displayed correctly, but on iOS the text is displayed where the horizontal scaling seems to be disregarded, leading to overlap in the letters.

Please note that this works correctly in Flutter version 3.22.3, but not in Flutter version 3.24.0

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: SizedBox.expand(
        child: CustomPaint(
          painter: MyTextPainter(),
        ),
      ),
    );
  }
}

class MyTextPainter extends CustomPainter {
  @override
  void paint(Canvas canvas, Size size) {
    final painter = TextPainter(
      text: const TextSpan(
        text:
            'Proident Lorem labore incididunt exercitation aliquip adipisicing amet esse officia ullamco. Non non proident laboris quis minim sunt reprehenderit. Ad laborum quis fugiat eiusmod. Consequat officia nostrud duis sit eiusmod.',
        style: TextStyle(
          color: Colors.black,
          fontSize: 48.0,
        ),
      ),
      textDirection: TextDirection.ltr,
      // textScaler: TextScaler.linear(0.5),
    );

    canvas.scale(0.5, 1.0);

    painter.layout();

    painter.paint(canvas, Offset.zero);
  }

  @override
  bool shouldRepaint(covariant CustomPainter oldDelegate) {
    return true;
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>
<h1>Rendered incorrectly on iOS</h1>
<img width="455" alt="Rendered incorrectly on iOS" src="https://github.com/user-attachments/assets/41079d53-d2d5-4b83-a4c7-55b269394673">
<h1>Rendered correctly on web</h1>
<img width="739" alt="Rendered correctly on web" src="https://github.com/user-attachments/assets/b2903c5b-cb9f-43d0-865c-37ec07977e6b">

</details>

### Logs

<details open><summary>Logs</summary>

https://drive.google.com/file/d/1yKTxKuJ8VUsma26kIVxkpgTu3lTOUaR6/view

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.24.0, on macOS 14.6.1 23G93 darwin-x64, locale en-US)
    • Flutter version 3.24.0 on channel stable at /Users/per/fvm/versions/3.24.0
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 80c2e84975 (3 weeks ago), 2024-07-30 23:06:49 +0700
    • Engine revision b8800d88be
    • Dart version 3.5.0
    • DevTools version 2.37.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/per/Library/Android/sdk
    • Platform android-34, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)

[✓] VS Code (version 1.62.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (4 available)
    • iPhone (mobile)            • 51a40c5d5535c85f15b120fc08cfb572517498ac • ios            • iOS 15.8.2 19H384
    • iPhone 15 Pro Max (mobile) • 2B9BBF4D-46CF-4DC8-8384-F3CD6685FBDB     • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-17-5 (simulator)
    • macOS (desktop)            • macos                                    • darwin-x64     • macOS 14.6.1
      23G93 darwin-x64
    • Chrome (web)               • chrome                                   • web-javascript • Google Chrome
      127.0.6533.120

[✓] Network resources
    • All expected network resources are available.

• No issues found!```

</details>

**Comment by jonahwilliams** [comment] 2024-08-19 16:55
Missing transform is actually the same issue as https://github.com/flutter/flutter/issues/153036 and is queued up for a cherry pick.

Closing as duplicate of https://github.com/flutter/flutter/issues/153036

**Closed by jonahwilliams** 2024-08-19 16:55 UTC
