### ISSUE TITLE
I have a problem in adding flutter modules to existing Android Project

### ISSUE THREAD

**Issue by WHATHELWHATHELWHATHEL** [flutter/flutter#30842] opened 2019-04-10 08:24 UTC
I have problem in following the steps of this wiki:
[Add Flutter to existing apps](https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps)

I have been trying to follow this wiki to create a Android Native project that can jump to an Flutter View, but I have trouble in simply building the project.

## Steps to Reproduce

1. Create an Android Project in Android studio (version 3.3.2),  confiugration as follow:
![image](https://user-images.githubusercontent.com/9447003/55861056-2d0d7200-5ba8-11e9-941a-5e9659743ce2.png)

2. Then I finished the building, The gradle syncing and running is good, nothing wrong here.

3. Then I create the flutter module in the same folder as the Android project, nothing wrong here (using flutter create -t module flutter_module_for_android)

3. Then I edit the app's build.gradle as follow, you can see that I have added the compileOptions to the file.

![image](https://user-images.githubusercontent.com/9447003/55861931-fe909680-5ba9-11e9-9c64-50bc379ec711.png)

4. Then I edit the settings.gradle in the host project at here (I have renamed the path properly), Here we have the first problem, the ide says that the "Binding" Symbol is missing. SInce no where in the wiki has mentioned where this  "Binding" coming from, I have no idea what I should do here.

![image](https://user-images.githubusercontent.com/9447003/55863123-7cee3800-5bac-11e9-8775-6c1aee67096c.png)

5. Then I choose to ignore this problem and continue, then I have add the "implementation' to the app's build.gradle as the wiki requested.

![image](https://user-images.githubusercontent.com/9447003/55862772-b7a3a080-5bab-11e9-92f1-347ab4a01a19.png)

6. After all thest procedures I click the "make" to build project, although I haven't added any active dart or android code, the project should be successfully built at least. However I got this:

![image](https://user-images.githubusercontent.com/9447003/55863152-91323500-5bac-11e9-8fbc-b3a64daa97d9.png)

I stuck at here and have no idea what I should do next, so I put forward this issues to ask for assistance. 

## Logs

detail Android build failure as follow:

```

ERROR: /Users/yifan.chen/ByteDanceIES/android_with_flutter/flutter_module_for_android/.android/Flutter/null/packages/flutter_tools/gradle/tt_flutter.gradle (No such file or directory)


```

flutter doctor -v result as follow: 

```
[✓] Flutter (Channel faceu_dev_1.0.0, v1.0.1-pre.8, on Mac OS X 10.14.3 18D109, locale en-CN)
    • Flutter version 1.0.1-pre.8 at /Users/yifan.chen/ByteDanceIES/flutter
    • Framework revision f1c0708bd5 (3 months ago), 2019-01-15 11:42:04 +0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[!] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/yifan.chen/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    ✗ Android license status unknown.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2, Build version 10E125
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.1

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 34.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.32.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.24.0

[!] Connected device
    ! No devices available
```

Any suggestion or analysis is appreciated.

**Comment by chrisof** [comment] 2019-04-10 08:52
You haven't set correctly the path to the module. Just remove the 'settingsDir.parentFile' line from your settings.gradle and sync again.

**Comment by WHATHELWHATHELWHATHEL** [comment] 2019-04-11 06:05
Hello？？？Any help here？

**Comment by WHATHELWHATHELWHATHEL** [comment] 2019-04-16 02:00
。。。any solution here？

**Comment by giginho** [comment] 2019-05-22 14:10
where is positioned the flutter module folder? It should be at the same level of the Android project folder (not into it)

**Comment by WHATHELWHATHELWHATHEL** [comment] 2019-05-24 06:38
> where is positioned the flutter module folder? It should be at the same level of the Android project folder (not into it)
Thanks for your reply first， the flutter module folder is in the same directory as the android project
Like follow
`
yifanchendeMacBook-Pro:android_with_flutter yifan.chen$ pwd
/Users/<My folder path>/android_with_flutter
yifanchendeMacBook-Pro:android_with_flutter yifan.chen$ ls
android_with_flutter		flutter_module_for_android
`
android_with_flutter is the Android Studio project I have created above

**Comment by blasten** [comment] 2020-01-03 23:48
@xster this issue keeps coming back. I added to the list "improve project structure", which aims to cover unifying add-to-app and non-add-to-app flows.

**Comment by jmagman** [comment] 2020-01-04 00:58
Let's mark this as a duplicate of https://github.com/flutter/flutter/issues/21706 instead since it's older and has more details.

**Closed by jmagman** 2020-01-04 00:58 UTC
Labels: a: existing-apps, tool, ▣ platform-android
