### ISSUE TITLE
TapGestureRecognizer in TextSpan doesn't work inside Tooltip widget

### ISSUE THREAD

**Issue by ingmferrer** [flutter/flutter#113388] opened 2022-10-13 14:49 UTC
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. Click the "Tap me" text
3. Click "url here" inside the tooltip.

**Expected results:**
See "url tapped" in the terminal.

**Actual results:**
No print output in the terminal.

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/gestures.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Tooltip(
          richMessage: TextSpan(
            text: 'Tap the ',
            style: const TextStyle(color: Colors.white),
            children: [
              TextSpan(
                text: 'url here',
                style: const TextStyle(color: Colors.yellow),
                recognizer: TapGestureRecognizer()
                  ..onTap = () {
                    print('url tapped');
                  },
              ),
            ],
          ),
          triggerMode: TooltipTriggerMode.tap,
          waitDuration: const Duration(minutes: 1),
          child: const Text('Tap me'),
        ),
      ),
    );
  }
}

```

</details>

<details>
  <summary>Logs</summary>

```
NA
```

```
Analyzing ftest...                                                      

   info - Avoid `print` calls in production code - lib\main.dart:50:21 - avoid_print

1 issue found. (ran in 2.7s)
```

```
[√] Flutter (Channel stable, 3.3.4, on Microsoft Windows [Versi¢n 10.0.22621.674], locale es-CO)
    • Flutter version 3.3.4 on channel stable at C:\Users\ingfe\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision eb6d86ee27 (8 days ago), 2022-10-04 22:31:45 -0700
    • Engine revision c08d7d5efc
    • Dart version 2.18.2
    • DevTools version 2.15.0

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\ingfe\AppData\Local\Android\sdk
    • Platform android-33, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] VS Code (version 1.72.1)
    • VS Code at C:\Users\ingfe\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.50.0

[√] Connected device (1 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64 • Android 12 (API 31) (emulator)

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by jasimameen** [comment] 2022-10-13 15:21
Make sure to run on debug mode. `print()` function does not work in production code
use `debugPrint('url tapped');` instead of `print('url tapped');`

**Comment by ingmferrer** [comment] 2022-10-13 15:49
It's not about the print, it's about the gesture not working. You can put a debugPrint there and it won't work.

**Comment by exaby73** [comment] 2022-10-13 17:12
## Triage report

I can reproduce this issue on `Master (3.5.0-6.0.pre.29)`. I believe this is happening because of the `GestureDetector` used for the `onTap` behavior takes priority over the recognizer.

https://github.com/flutter/flutter/blob/c738c8aa961670929f90124ace71b7d9b263e002/packages/flutter/lib/src/material/tooltip.dart#L750-L756

**Comment by ingmferrer** [comment] 2022-10-13 17:27
@exaby73 makes sense, let me know if I can help test a solution.

**Comment by Renzo-Olivares** [comment] 2022-10-27 12:08
Still doing some investigation on this one. I'm not certain that the `GestureDetector` pointed out by @exaby73 is the root cause since when I tried removing it, it did not fix the issue.

I have tried to create a minimal reproducible sample that you can check out here https://dartpad.dev/?id=d1626417b68c5fa8bc648d9243b08d2a . It is a simple app that has a button which displays an `Overlay` that includes a `TextSpan` with a `recognizer` defined. I also included an example with an `Overlay` without a `TextSpan` (just a `Container` wrapped in a `GestureDetector`), and the `onTap` callback was also not called in this case. This leads me to believe that the root cause might be in `Overlay` and not in `Tooltip`.

**Comment by Renzo-Olivares** [comment] 2023-06-01 03:08
Closing this since I can confirm it was fixed by https://github.com/flutter/flutter/pull/126207. If this is still a problem feel free to re-open the issue.

**Closed by Renzo-Olivares** 2023-06-01 03:08 UTC
Labels: framework, f: material design, f: gestures, has reproducible steps, P3, found in release: 3.3, found in release: 3.4
