### ISSUE TITLE
[Web] All text-related widgets appear ⊠ for a while. (using Korean)

### ISSUE THREAD

**Issue by jinnybrain** [flutter/flutter#112694] opened 2022-09-30 07:13 UTC
I'm developing a web with Flutter, and all text-related widgets.
There is a problem that the X box appears for a while when exposed to Korean.

Like this.
⊠⊠⊠⊠⊠ --> 가나다라마

Anyone have a solution? Or, I'm wondering if any of you are experiencing this issue.
Note that, there is no problem on mobile.

Flutter (Channel stable, 3.0.5)
VS Code (version 1.71.2)

**Comment by darshankawar** [comment] 2022-09-30 12:28
Closing this as a duplicate of https://github.com/flutter/flutter/issues/77023

**Closed by darshankawar** 2022-09-30 12:28 UTC
Labels: in triage
