### ISSUE TITLE
url_launcher uses or overrides a deprecated API

### ISSUE THREAD

**Issue by menezes85** [flutter/flutter#44070] opened 2019-11-03 15:35 UTC
## Steps to Reproduce

1. ... UrlLauncherPlugin.java , line 38
` methodCallHandler.startListening(binding.getFlutterEngine().getDartExecutor());`
2. ...getFlutterEngine() is deprecated, warnings in compile

**Target Platform:** Android API 29
**Target OS version/browser:** Win  10 / Chrome
**Devices:**
Samsung J7 Neo

Please udate plugin to new code.

**Comment by iapicca** [comment] 2019-11-04 09:11
Hi @menezes85 
can you please describe the issue in detail
and provide your `flutter doctor -v`.
Also, to better address the issue, would be helpful
if you could post a self contained app on github
or the steps to reproduce it.
Thank you

**Comment by jmagman** [comment] 2019-11-04 20:58
It looks like this was just introduced in 5.2.2. https://github.com/flutter/plugins/pull/2204/files#diff-af77f749944b3cffc49bd17805962a58R38

@mklim Is this some temporary deprecation usage as part of the v2 migration?

**Comment by menezes85** [comment] 2019-11-04 21:21
hi folks! 
 i Runned code Inspection in AS , and reportsmethis snippet

`  @Override
  public void onAttachedToEngine(@NonNull FlutterPluginBinding binding) {
    urlLauncher = new UrlLauncher(binding.getApplicationContext(), /*activity=*/ null);
    methodCallHandler = new MethodCallHandlerImpl(urlLauncher);
    methodCallHandler.startListening(binding.getFlutterEngine().getDartExecutor());
  }
`

**Comment by mklim** [comment] 2019-11-05 18:10
@jmagman yes, this was deliberate and temporary.

The v2 embedder recently changed its API surface, deprecating `getFlutterEngine` and adding a few new APIs to use instead (flutter/flutter#42959). However the plugins can't actually use those new APIs and remove the `getFlutterEngine` call without causing compile errors on stable.

For now this issue is blocked since there's no alternative that we could change to instead. Once the changes roll we should update the plugins to stop using the deprecated methods, though.

**Comment by abaker2010** [comment] 2019-12-17 16:11
I ran in to this depreciation issue again. 

`flutter doctor`

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v1.12.13+hotfix.6, on Mac OS X 10.15.1 19B88, locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
[✓] Android Studio (version 3.5)
[✓] Connected device (2 available)

• No issues found!

Errors being thrown: 

/.pub-cache/hosted/pub.dartlang.org/url_launcher-5.4.1/android/src/main/java/io/flutter/plugins/urllauncher/WebViewActivity.java:42: warning: [deprecation] shouldOverrideUrlLoading(WebView,String) in WebViewClient has been deprecated
        public boolean shouldOverrideUrlLoading(WebView view, String url) {
                       ^
/.pub-cache/hosted/pub.dartlang.org/url_launcher-5.4.1/android/src/main/java/io/flutter/plugins/urllauncher/WebViewActivity.java:47: warning: [deprecation] shouldOverrideUrlLoading(WebView,String) in WebViewClient has been deprecated
          return super.shouldOverrideUrlLoading(view, url);
                      ^
/.pub-cache/hosted/pub.dartlang.org/url_launcher-5.4.1/android/src/main/java/io/flutter/plugins/urllauncher/UrlLauncherPlugin.java:38: warning: [deprecation] getFlutterEngine() in FlutterPluginBinding has been deprecated
    methodCallHandler.startListening(binding.getFlutterEngine().getDartExecutor());

**Comment by mit-mit** [comment] 2020-02-04 12:36
@mklim is this bug essentially a duplicate of https://github.com/flutter/flutter/issues/47153 ?

**Comment by mklim** [comment] 2020-02-04 17:40
Yes, good catch. I'll add a note there mentioning that these plugins also have deprecation warnings until they're completely updated.

**Comment by HiteshMoorjaniX** [comment] 2020-03-23 10:15
I am still getting this warning 
"PathProviderPlugin.java uses or overrides a deprecated API."

**Comment by iapicca** [comment] 2020-03-23 12:39
@HiteshMoorjaniX 
please follow up on the [issue](#47153) linked above
thank you

**Comment by soufi-43** [comment] 2020-05-13 04:27
url_launcher: ^5.1.3 version worked for me

**Comment by omidh28** [comment] 2020-07-21 14:55
With 5.5.0, I still have this problem

**Comment by jmagman** [comment] 2020-07-21 17:27
Reopening.

**Comment by jmagman** [comment] 2020-07-21 17:28
@cyanglaz who's looking at url_launcher these days?  `CODEOWNERS` looks out of date?

**Comment by Nico04** [comment] 2020-07-22 09:30
> 
> 
> @cyanglaz who's looking at url_launcher these days? `CODEOWNERS` looks out of date?

I use url_launcher in one of my project. Do you mean we should use another plugin ?

**Comment by jmagman** [comment] 2020-07-22 17:45
@Nico04 no I didn't mean that.

**Comment by kanaydo** [comment] 2020-08-25 01:28
having same problem with `5.5.0`, the app is fine, but the error message still there.
change `targetSdkVersion` to 29 and the error message gone.

**Comment by blasten** [comment] 2022-04-26 18:07
cc @GaryQian (new owner of url_launcher_android)

**Comment by GaryQian** [comment] 2022-06-21 17:32
This seems to be already migrated in UrlLauncherPlugin.java. I will close this.

**Closed by GaryQian** 2022-06-21 17:32 UTC
Labels: platform-android, plugin, customer: crowd, p: url_launcher, P4
