### ISSUE TITLE
Add normal number keypad for TextInputType.name (iOS)

### ISSUE THREAD

**Issue by capsulekenny** [flutter/flutter#133620] opened 2023-08-30 01:26 UTC
### Use case

It would be great to be able to have `TextInputType.name` show a normal number keypad on iOS, currently it shows the phone number keypad but this behaviour is different on Android. I ran into this problem trying to remove the suggestions bar simply by using `TextInputType.text` with `enableSuggestions: false` & `autoCorrect: false` but these flags seem to do nothing over both Android and iOS Simulated or actual devices.

An alternative solution would be to check these flags and see if they are working properly. I have seen in other raised issues that `autoCorrect: false` should disable the suggestions bar on iOS. It's extremely frustrating since I can see the implementation I want with the `name` type but the implementation of using a phone number keyboard with this doesn't make sense to me.

### Proposal

`TextInputType.name` should become configurable like `TextInputType.numberWithOptions()` or the number pad present on the name type should be the default keyboard.

**Comment by danagbemava-nc** [comment] 2023-08-30 09:56
Hi @capsulekenny, this is working as intended for iOS. The `TextInputType.name` maps to `UIKeyboardType.namePhonePad` on iOS which is the control that has that behavior. 

> I ran into this problem trying to remove the suggestions bar simply by using TextInputType.text with enableSuggestions: false & autoCorrect: false but these flags seem to do nothing over both Android and iOS Simulated or actual devices.

I would suggest filing an issue for this so that it can be properly investigated and fixed. 

| SwiftUI | Flutter | 
| -- | -- |
| <video src="https://github.com/flutter/flutter/assets/88313112/b2233ab1-4dd7-4b20-8359-f9cabb4a43b9" /> | <video src="https://github.com/flutter/flutter/assets/88313112/499de8db-cd4f-4645-bbfa-45df6062058f" /> |

For the most part, flutter delegates the keyboard appearance to the native layer so we cannot offer much in the way of customizing the appearance. You can find the source for this https://github.com/flutter/engine/blob/159fda6b51f0856d9dbe866a4330ee69cbdd951a/shell/platform/darwin/ios/framework/Source/FlutterTextInputPlugin.mm#L105

For now, I'll be closing this since it is working as intended on iOS. 

Thank you

**Closed by danagbemava-nc** 2023-08-30 09:56 UTC
Labels: in triage
