### ISSUE TITLE
Image.toByteData(format: ui.ImageByteFormat.rawRgba) throws exception on Web

### ISSUE THREAD

**Issue by juanmrivero** [flutter/flutter#55239] opened 2020-04-20 21:49 UTC
I'm loading an image in a widget using an `ImageProvider`. 
This image is loaded correctly and I'm using it on a `RenderBox` to paint successfully. Something like: 

```
  void paint(PaintingContext context, Offset offset) {
    if (imageInfo?.image != null) {
      context.canvas.drawImage(imageInfo?.image, offset, paint);
    }
  }
```

The bug happens when I call **`dart:ui.Image.toByteData(format: ImageByteFormat.rawRgba)`** while running on *web* (Chrome).  If I run the same code on iOS everything works. 

The bug is reproducible using `AssetImage` & `NetworkImage` providers.

This is the stack trace: 
```
NoSuchMethodError: The getter 'uri' was called on null.
Receiver: null
Tried calling: uri
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      ClassHelper._constructClass (package:dwds/src/debugging/classes.dart:72:58)
#2      ClassHelper.forObjectId (package:dwds/src/debugging/classes.dart:61:19)
<asynchronous suspension>
#3      AppInspector.getObject (package:dwds/src/debugging/inspector.dart:316:35)
<asynchronous suspension>
#4      ChromeProxyService.getObject (package:dwds/src/services/chrome_proxy_service.dart:391:19)
#5      VmServerConnection._delegateRequest (package:vm_service/src/vm_service.dart:1288:51)
#6      _rootRunUnary (dart:async/zone.dart:1192:38)
#7      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#8      _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
#9      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#10     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#11     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:134:11)
#12     _MapStream._handleData (dart:async/stream_pipe.dart:234:10)
#13     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:166:13)
#14     _rootRunUnary (dart:async/zone.dart:1192:38)
#15     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#16     _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
#17     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#18     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#19     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:779:19)
#20     _StreamController._add (dart:async/stream_controller.dart:655:7)
#21     _StreamController.add (dart:async/stream_controller.dart:597:5)
#22     new WebSocketImpl.fromSocket.<anonymous closure> (package:web_socket_channel/src/copy/web_socket_impl.dart:719:21)
#23     _rootRunUnary (dart:async/zone.dart:1192:38)
#24     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#25     _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
#26     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#27     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#28     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:70:11)
#29     _EventSinkWrapper.add (dart:async/stream_transformers.dart:17:11)
#30     _WebSocketProtocolTransformer._messageFrameEnd (package:web_socket_channel/src/copy/web_socket_impl.dart:316:22)
#31     _WebSocketProtocolTransformer.add (package:web_socket_channel/src/copy/web_socket_impl.dart:214:46)
#32     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:122:24)
#33     _rootRunUnary (dart:async/zone.dart:1192:38)
#34     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#35     _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
#36     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#37     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#38     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:779:19)
#39     _StreamController._add (dart:async/stream_controller.dart:655:7)
#40     _StreamController.add (dart:async/stream_controller.dart:597:5)
#41     _Socket._onData (dart:io-patch/socket_patch.dart:1982:41)
#42     _rootRunUnary (dart:async/zone.dart:1196:13)
#43     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#44     _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
#45     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#46     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#47     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:779:19)
#48     _StreamController._add (dart:async/stream_controller.dart:655:7)
#49     _StreamController.add (dart:async/stream_controller.dart:597:5)
#50     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1527:33)
#51     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1019:14)
#52     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#53     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#54     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#55     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

Flutter doctor:
```
[✓] Flutter (Channel beta, v1.17.0, on Mac OS X 10.15.4 19E287, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.4)
[!] IntelliJ IDEA Community Edition (version 2020.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] Connected device (2 available)
```
For some reason it reports that I do not have installed the Flutter & Dart plugin, but they are and are working. Versions: 
Flutter plugin: 45.1.3
Dart Plugin: 201.6668.156

I'm aware of #44908, but can't comment there

**Comment by yjbanov** [comment] 2020-04-23 22:16
Duplicate of https://github.com/flutter/flutter/issues/47721

**Closed by yjbanov** 2020-04-23 22:16 UTC
Labels: a: images, dependency: dart, framework, platform-web
