### ISSUE TITLE
BUG: image_picker does not work on iOS simulator >=14.0

### ISSUE THREAD

**Issue by johnspackman** [flutter/flutter#94937] opened 2021-12-09 15:49 UTC
As has been discussed elsewhere, the image_picker does not work on M1 macs on the simulator; the README for the image_picker says:

> Starting with version 0.8.1 the iOS implementation uses PHPicker to pick (multiple) images on iOS 14 or higher. As a result of implementing PHPicker it becomes impossible to pick HEIC images on the iOS simulator in iOS 14+. This is a known issue. Please test this on a real device, or test with non-HEIC images until Apple solves this issue. 63426347 - Apple known issue

It appears that Apple have had this bug for around a year already with no sign of a fix - however there is a fairly simple fix (which is hinted at in the README), which is to use the UIImagePicker instead of the PHPicker.  This would be a supported solution because the UIPicker is required for iOS versions prior to 14.  

The code at [github.com/flutter/plugins/packages/image_picker/image_picker/ios/Classes/FLTImagePickerPlugin.m#L142-L151](https://github.com/flutter/plugins/blob/master/packages/image_picker/image_picker/ios/Classes/FLTImagePickerPlugin.m#L142-L151) checks to see if the iOS version is < 14 and if so, uses the previous UI picker.

A workaround for users is to clone that picker and replace that block of code with `[self pickImageWithUIImagePicker];` - a better one would be for flutter to detect the simulator (or provide a means at runtime to indicate that the UIImagePicker is preferred)

**Comment by danagbemava-nc** [comment] 2021-12-10 09:42
> A workaround for users is to clone that picker and replace that block of code with [self pickImageWithUIImagePicker]; - a better one would be for flutter to detect the simulator (or provide a means at runtime to indicate that the UIImagePicker is preferred)

Hi @johnspackman, I wonder if this is entirely necessary, considering the issue is that it doesn't work with certain types of images, but it works just fine for other images. I used to example app provided in the image picker plugin and I was able to select some images. See video below

If the video below isn't exactly the issue you're running into, can you provide more information as to what exactly the problem you're facing is? Thank you

https://user-images.githubusercontent.com/88313112/145551734-3d793a2c-22f9-41c5-ae71-ce9d6127794e.mov

**Comment by johnspackman** [comment] 2021-12-10 09:47
@danagbemava-nc I cannot select any of the images which ship as default on my iOS 15.0 simulator; they look like they're the same images that you have in your video.

What I find is that where my code uses `await picker.pickImage`, it never completes the promise, even after the image is selected.

**Comment by danagbemava-nc** [comment] 2021-12-10 09:59
> they look like they're the same images that you have in your video.

Yes, they are the default images that come with the simulator. 

Can you please provide a complete minimal reproducible code sample so that I may verify this? 

Also, what version of `image_picker` are you using and please provide the output of `flutter doctor -v`. 

Thank you

**Comment by johnspackman** [comment] 2021-12-10 10:17
I've deleted the entry in pubspec.yaml for image_picker (because it referred to my local path) and then readded it:

```
$ flutter pub add image_picker
Resolving dependencies...
  _fe_analyzer_shared 22.0.0 (31.0.0 available)
  add_2_calendar 2.1.1 (2.1.2 available)
  alice 0.2.4 (0.2.5 available)
  analyzer 1.7.2 (2.8.0 available)
  archive 3.1.2 (3.1.6 available)
  args 2.2.0 (2.3.0 available)
  async 2.8.1 (2.8.2 available)
  basic_utils 3.7.0 (3.9.1 available)
  better_player 0.0.72 (0.0.79 available)
  build 2.1.0 (2.1.1 available)
  build_daemon 3.0.0 (3.0.1 available)
  build_resolvers 2.0.4 (2.0.5 available)
  build_runner 2.1.2 (2.1.5 available)
  build_runner_core 7.1.0 (7.2.2 available)
  built_collection 5.1.0 (5.1.1 available)
  built_value 8.1.2 (8.1.3 available)
  characters 1.1.0 (1.2.0 available)
  chewie 1.1.0 (1.2.2 available)
  chopper 4.0.1 (4.0.4 available)
  cli_util 0.3.3 (0.3.5 available)
  cloud_firestore 2.4.0 (3.1.4 available)
  cloud_firestore_platform_interface 5.3.0 (5.4.9 available)
  cloud_firestore_web 2.3.0 (2.6.4 available)
  cloud_functions 3.0.6 (3.2.3 available)
  cloud_functions_platform_interface 5.0.13 (5.0.18 available)
  cloud_functions_web 4.0.15 (4.2.4 available)
  connectivity_plus 2.0.2 (2.1.0 available)
  connectivity_plus_linux 1.1.0 (1.1.1 available)
  connectivity_plus_platform_interface 1.1.0 (1.1.1 available)
+ cross_file 0.3.2
  csslib 0.17.0 (0.17.1 available)
  cupertino_icons 1.0.3 (1.0.4 available)
  dart_style 2.0.3 (2.2.0 available)
  dbus 0.5.6 (0.6.6 available)
  dio 4.0.0 (4.0.4 available)
  double_back_to_close_app 2.0.1 (2.1.0 available)
  firebase_auth 3.0.1 (3.3.3 available)
  firebase_auth_platform_interface 6.0.0 (6.1.8 available)
  firebase_auth_web 3.0.0 (3.3.4 available)
  firebase_core 1.9.0 (1.10.5 available)
  firebase_core_platform_interface 4.0.1 (4.2.2 available)
  firebase_core_web 1.1.0 (1.5.2 available)
  firebase_crashlytics 2.2.0 (2.4.3 available)
  firebase_crashlytics_platform_interface 3.1.1 (3.1.10 available)
  firebase_messaging 10.0.4 (11.2.3 available)
  firebase_messaging_platform_interface 3.0.3 (3.1.3 available)
  firebase_messaging_web 2.0.3 (2.2.4 available)
  flutter_launcher_icons 0.9.1 (0.9.2 available)
  flutter_local_notifications 8.1.1+1 (9.1.5 available)
  flutter_local_notifications_platform_interface 4.0.1 (5.0.0 available)
  flutter_plugin_android_lifecycle 2.0.2 (2.0.5 available)
  flutter_secure_storage 4.2.1 (5.0.2 available)
  flutter_staggered_grid_view 0.4.0 (0.4.1 available)
  flutter_stripe 1.2.0 (2.0.2 available)
  flutter_widget_from_html_core 0.6.1+4 (0.8.3 available)
  freezed_annotation 0.14.2 (1.0.0 available)
  frontend_server_client 2.1.0 (2.1.2 available)
  geolocator 7.4.0 (8.0.0 available)
  geolocator_android 1.0.0 (3.0.0+4 available)
  geolocator_apple 1.0.0 (2.0.0+2 available)
  geolocator_platform_interface 2.3.2 (3.0.0+1 available)
  geolocator_web 2.0.6 (2.1.0 available)
  get 4.3.8 (4.5.1 available)
  glob 2.0.1 (2.0.2 available)
  google_maps_flutter 2.0.6 (2.1.1 available)
  google_maps_flutter_platform_interface 2.1.1 (2.1.3 available)
  google_maps_utils 1.4.0+1 (1.5.0+0 available)
  graphs 2.0.0 (2.1.0 available)
  http 0.13.3 (0.13.4 available)
  image 3.0.2 (3.1.0 available)
+ image_picker 0.8.4+4
+ image_picker_for_web 2.1.4
+ image_picker_platform_interface 2.4.1
  implicitly_animated_reorderable_list 0.4.0 (0.4.2 available)
  json_annotation 4.0.1 (4.4.0 available)
  json_serializable 4.1.4 (6.1.1 available)
  local_auth 1.1.6 (1.1.8 available)
  logger 1.0.0 (1.1.0 available)
  logging 1.0.1 (1.0.2 available)
  matcher 0.12.10 (0.12.11 available)
  material_floating_search_bar 0.3.4 (0.3.6 available)
  mime 1.0.0 (1.0.1 available)
  mobx_codegen 2.0.2 (2.0.4 available)
  nm 0.3.0 (0.4.1 available)
  package_config 2.0.0 (2.0.2 available)
  package_info_plus 1.0.5 (1.3.0 available)
  package_info_plus_macos 1.1.1 (1.3.0 available)
  package_info_plus_web 1.0.3 (1.0.4 available)
  package_info_plus_windows 1.0.3 (1.0.4 available)
  path_provider 2.0.2 (2.0.8 available)
  path_provider_linux 2.0.2 (2.1.2 available)
  path_provider_macos 2.0.2 (2.0.4 available)
  path_provider_windows 2.0.3 (2.0.4 available)
  pedantic 1.11.1 (discontinued replaced by lints)
  petitparser 4.1.0 (4.4.0 available)
  platform 3.0.0 (3.1.0 available)
  plugin_platform_interface 2.0.1 (2.0.2 available)
  pointycastle 3.3.5 (3.4.0 available)
  process 4.2.3 (4.2.4 available)
  provider 6.0.0 (6.0.1 available)
  pub_semver 2.0.0 (2.1.0 available)
  pubspec_parse 1.0.0 (1.2.0 available)
  quiver 3.0.1 (3.0.1+1 available)
  retrofit 2.0.1 (3.0.0 available)
  retrofit_generator 2.0.1 (3.0.0+2 available)
  rxdart 0.27.1 (0.27.3 available)
  sembast 3.1.0+2 (3.1.1+1 available)
  shared_preferences 2.0.6 (2.0.10 available)
  shared_preferences_linux 2.0.2 (2.0.3 available)
  shared_preferences_web 2.0.1 (2.0.2 available)
  shared_preferences_windows 2.0.2 (2.0.3 available)
  source_gen 1.0.3 (1.2.0 available)
  stripe_android 1.2.0 (2.0.2 available)
  stripe_ios 1.2.0 (2.0.2 available)
  stripe_platform_interface 1.2.0 (2.0.2 available)
  syncfusion_flutter_core 19.3.54 (19.3.57 available)
  syncfusion_flutter_datepicker 19.3.54 (19.3.57 available)
  test_api 0.4.2 (0.4.8 available)
  timezone 0.7.0 (0.8.0 available)
  url_launcher 6.0.9 (6.0.17 available)
  url_launcher_linux 2.0.1 (2.0.2 available)
  url_launcher_macos 2.0.1 (2.0.2 available)
  url_launcher_web 2.0.2 (2.0.5 available)
  url_launcher_windows 2.0.1 (2.0.2 available)
  uuid 3.0.4 (3.0.5 available)
  vector_math 2.1.0 (2.1.1 available)
  video_player 2.2.3 (2.2.7 available)
  visibility_detector 0.2.0 (0.2.2 available)
  wakelock 0.5.3+3 (0.5.6 available)
  wakelock_macos 0.1.0+2 (0.4.0 available)
  wakelock_platform_interface 0.2.1+2 (0.3.0 available)
  wakelock_web 0.2.0+2 (0.4.0 available)
  wakelock_windows 0.1.0+1 (0.2.0 available)
  watcher 1.0.0 (1.0.1 available)
  win32 2.2.5 (2.3.1 available)
  xml 5.1.2 (5.3.1 available)
Changed 4 dependencies!
$ flutter doctor -v
[✓] Flutter (Channel stable, 2.5.3, on macOS 12.0.1 21A559 darwin-arm, locale en-GB)
    • Flutter version 2.5.3 at /Users/john/dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (8 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/john/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.1, Build version 13A1030d
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.2.4)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.63.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (2 available)
    • iPhone 13 (mobile) • CCFA76DD-378B-4B07-9045-5ADCD7A73BAD • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 96.0.4664.93

• No issues found!
```

The code I'm using is:

```
import 'dart:io';

import 'package:flutter/material.dart';
import 'package:flutter/widgets.dart';
import 'package:image_picker/image_picker.dart';
import 'package:path_provider/path_provider.dart';
import 'package:image/image.dart' as img;

abstract class AbstractImagePickerBuilder {
  final String outputFilename;
  final Function(String?) onComplete;
  String? absoluteOutputFilename;
  String? relativeOutputFilename;
  File? _outputFile;

  AbstractImagePickerBuilder(this.outputFilename, this.onComplete);

  void _configureFilenames(String? hintFilename) async {
    String ext = ".png";
    if (hintFilename != null) {
      int pos = hintFilename.lastIndexOf(".");
      String tmp = hintFilename.substring(pos);
      if (!tmp.contains("/"))
        ext = tmp;
    }
    final directory = await getApplicationDocumentsDirectory();
    relativeOutputFilename = '$outputFilename$ext';
    absoluteOutputFilename = '${directory.path}/$relativeOutputFilename';
    _outputFile = File(absoluteOutputFilename!);
    await Directory(_outputFile!.parent.path).create(recursive: true);
  }

}

class ImagePickerBuilder extends AbstractImagePickerBuilder {
  final ImagePicker picker = ImagePicker();

  ImagePickerBuilder(String outputFilename, Function(String?) onComplete) : 
    super(outputFilename, onComplete);

  _showPicker(BuildContext bc, ImageSource imageSource) async {
    XFile? pickedFile;
    
    pickedFile = await picker.pickImage(
      source: imageSource, 
      imageQuality: 100
    );
    if (pickedFile == null) {
      onComplete(null);
      return;
    }
    _configureFilenames(pickedFile.path);

    img.Image image = img.decodeImage(await pickedFile.readAsBytes())!;
    img.Image thumbnail = img.copyResize(image, width: 100, height: 100);
    List<int> pngBytes = img.encodePng(thumbnail);
    _outputFile!.writeAsBytes(pngBytes);

    Navigator.of(bc).pop();
    onComplete("$relativeOutputFilename");
  }

  Widget builder(BuildContext bc) {
    return SafeArea(
      child: new Wrap(
        children: <Widget>[
          new ListTile(
            leading: new Icon(Icons.photo_library),
            title: new Text('Photo Library'),
            onTap: () => _showPicker(bc, ImageSource.gallery)
          ),
          new ListTile(
            leading: new Icon(Icons.photo_camera),
            title: new Text('Camera'),
            onTap: () => _showPicker(bc, ImageSource.camera)
          )
        ]
      )
    );
  }
}

```

If I set a breakpoint where it says `pickedFile = await picker.pickImage(` that is reached, but a breakpoint on the next line (`if (pickedFile == null) {`) is never reached.  The picker user interface pops up, i select an image, and the UI disappears - but the call to `pickImage` never completes.

**Comment by johnspackman** [comment] 2021-12-10 10:19
PS the code that trigger the above is in a `State` class, and in the `onTap` handler this code is run:

```
  late ImagePickerBuilder imagePickerBuilder = ImagePickerBuilder("things/${thing.uuid}/imageFile", onImageChanged);
  @override
  onIconClick(BuildContext context) {
    showModalBottomSheet(
      context: context,
      builder: imagePickerBuilder.builder
    );
  }
```

**Comment by johnspackman** [comment] 2021-12-10 10:25
One other detail that might be useful to know is that after the picker UI goes away, the modal bottom sheet is still visible; if I select "Photo Library" again, then the picker will pop up but I get an exception: 

```
[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: PlatformException(multiple_request, Cancelled by a second request, null, null)
```

FWIW I'm using a Macbook Pro 18,2 with Apple M1 Max processor, macOs Monterey 12.0.1

**Comment by danagbemava-nc** [comment] 2021-12-10 12:17
Using your sample (I took out `path_provider` and `image`), the `image_picker` plugin worked just fine. 
I tested on `2.5.3` and `2.8.0`

https://user-images.githubusercontent.com/88313112/145567884-3cfb2ac0-2a1d-4731-83ce-9427e45fd731.mov

<details>
<summary>flutter doctor -v</summary>

```console
[✓] Flutter (Channel unknown, 2.5.3, on macOS 11.6 20G165 darwin-arm, locale en-GB)
    • Flutter version 2.5.3 at /Users/nexus/dev/sdks/flutter_rc/flutter
    • Upstream repository unknown
    • Framework revision 18116933e7 (8 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.0, Build version 13A233
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[☠] IntelliJ IDEA Community Edition (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue
      at https://github.com/flutter/flutter/issues.
    ✗ FormatException: Unexpected extension byte (at offset 5)
    • #0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1788:7)
      #1      Utf8Decoder.convert (dart:convert/utf.dart:318:42)
      #2      InputStream.readString (package:archive/src/util/input_stream.dart:199:30)
      #3      new ZipDirectory.read (package:archive/src/zip/zip_directory.dart:40:30)
      #4      ZipDecoder.decodeBuffer (package:archive/src/zip_decoder.dart:19:30)
      #5      ZipDecoder.decodeBytes (package:archive/src/zip_decoder.dart:14:12)
      #6      IntelliJPlugins._findPluginXml (package:flutter_tools/src/intellij/intellij.dart:130:44)
      #7      IntelliJPlugins._readPackageVersion (package:flutter_tools/src/intellij/intellij.dart:141:40)
      #8      IntelliJPlugins.validatePackage (package:flutter_tools/src/intellij/intellij.dart:63:35)
      #9      IntelliJValidator.validate (package:flutter_tools/src/intellij/intellij_validator.dart:103:15)
      #10     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      #11     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:109:18)
      #12     _rootRun (dart:async/zone.dart:1428:13)
      #13     _CustomZone.run (dart:async/zone.dart:1328:19)
      #14     _runZoned (dart:async/zone.dart:1863:10)
      #15     runZonedGuarded (dart:async/zone.dart:1851:12)
      #16     runZoned (dart:async/zone.dart:1782:12)
      #17     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #18     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:200:9)
      #19     Doctor.diagnose (package:flutter_tools/src/doctor.dart:304:47)
      #20     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:50:47)
      #21     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1274:12)
      <asynchronous suspension>
      #22     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1125:27)
      <asynchronous suspension>
      #23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #24     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
      <asynchronous suspension>
      #25     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
      <asynchronous suspension>
      #26     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #27     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
      <asynchronous suspension>
      #28     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
      <asynchronous suspension>
      #29     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #30     main (package:flutter_tools/executable.dart:92:3)
      <asynchronous suspension>


[✓] VS Code (version 1.62.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (3 available)
    • iPhone 13 (mobile) • 7515F01A-C1B6-456E-8559-8D2383D3719D • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-0
      (simulator)
    • macOS (desktop)    • macos                                • darwin-arm64   • macOS 11.6 20G165 darwin-arm
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 96.0.4664.93

! Doctor found issues in 1 category.
```

```console
[✓] Flutter (Channel stable, 2.8.0, on macOS 11.6 20G165 darwin-arm, locale en-GB)
    • Flutter version 2.8.0 at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cf44000065 (2 days ago), 2021-12-08 14:06:50 -0800
    • Engine revision 40a99c5951
    • Dart version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[☠] IntelliJ IDEA Community Edition (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue
      at https://github.com/flutter/flutter/issues.
    ✗ FormatException: Unexpected extension byte (at offset 5)
    • #0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1789:7)
      #1      Utf8Decoder.convert (dart:convert/utf.dart:318:42)
      #2      InputStream.readString (package:archive/src/util/input_stream.dart:207:30)
      #3      new ZipDirectory.read (package:archive/src/zip/zip_directory.dart:40:30)
      #4      ZipDecoder.decodeBuffer (package:archive/src/zip_decoder.dart:19:30)
      #5      ZipDecoder.decodeBytes (package:archive/src/zip_decoder.dart:14:12)
      #6      IntelliJPlugins._findPluginXml (package:flutter_tools/src/intellij/intellij.dart:130:44)
      #7      IntelliJPlugins._readPackageVersion (package:flutter_tools/src/intellij/intellij.dart:141:40)
      #8      IntelliJPlugins.validatePackage (package:flutter_tools/src/intellij/intellij.dart:63:35)
      #9      IntelliJValidator.validate (package:flutter_tools/src/intellij/intellij_validator.dart:103:15)
      #10     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      #11     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:109:18)
      #12     _rootRun (dart:async/zone.dart:1428:13)
      #13     _CustomZone.run (dart:async/zone.dart:1328:19)
      #14     _runZoned (dart:async/zone.dart:1863:10)
      #15     runZonedGuarded (dart:async/zone.dart:1851:12)
      #16     runZoned (dart:async/zone.dart:1782:12)
      #17     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #18     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:197:9)
      #19     Doctor.diagnose (package:flutter_tools/src/doctor.dart:301:47)
      #20     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:53:47)
      #21     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1290:12)
      <asynchronous suspension>
      #22     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1140:27)
      <asynchronous suspension>
      #23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #24     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
      <asynchronous suspension>
      #25     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
      <asynchronous suspension>
      #26     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #27     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
      <asynchronous suspension>
      #28     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
      <asynchronous suspension>
      #29     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #30     main (package:flutter_tools/executable.dart:94:3)
      <asynchronous suspension>


[✓] VS Code (version 1.62.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (3 available)
    • iPhone 13 (mobile) • 7515F01A-C1B6-456E-8559-8D2383D3719D • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-0
      (simulator)
    • macOS (desktop)    • macos                                • darwin-arm64   • macOS 11.6 20G165 darwin-arm
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 96.0.4664.93

! Doctor found issues in 1 category.
```
</details>

**Comment by johnspackman** [comment] 2021-12-10 14:00
ok, so where do we go from here?  I've just updated my cocoapods, flutter, and dart versions to match yours; your Xcode is slightly older than mine.

The exception I mentioned is thrown by the plugin and shows that the plugin does not recognise that it finished either, meaning that the problem is in the native code for the plugin. 

Updated doctor:
```
$ flutter doctor -v
[✓] Flutter (Channel stable, 2.8.0, on macOS 12.0.1 21A559 darwin-arm, locale en-GB)
    • Flutter version 2.8.0 at /Users/john/dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cf44000065 (2 days ago), 2021-12-08 14:06:50 -0800
    • Engine revision 40a99c5951
    • Dart version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/john/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.2.4)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.63.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (2 available)
    • iPhone 13 (mobile) • CCFA76DD-378B-4B07-9045-5ADCD7A73BAD • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 96.0.4664.93

```

https://user-images.githubusercontent.com/129568/145585507-5a88ffb5-b4c7-4658-8ab3-bef8f1371678.mov

**Comment by johnspackman** [comment] 2021-12-10 14:02
PS in that version of the code, I removed `path_provider` and `image` also

**Comment by danagbemava-nc** [comment] 2021-12-13 06:04
Can you try with a new flutter app and the example in the `image_picker` plugin and see if you're able to pick any of the images?

**Comment by johnspackman** [comment] 2021-12-13 06:05
Hi,

Thank you for your email - I am unavailable, returning on January 10th 2022.
  
 For customers with extended support, please contact your IT department in the first instance, who will be able to pass on any questions to the appropriate person to handle your query in my absence.
  
 I will get back to you as soon as possible, but if you have an emergency support issue please describe your issue in detail in email and then send a text message to the mobile number you have for me.

Regards
John Spackman

**Comment by florian-gustin** [comment] 2021-12-17 16:25
> Can you try with a new flutter app and the example in the `image_picker` plugin and see if you're able to pick any of the images?

it works on a fresh new app. Except for the first image from the ios gallery samples.

Tested on 2.5 version.

Concerning older application, from my point of view it doesn't. 

I get this stack : 

``
[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: PlatformException(multiple_request, Cancelled by a second request, null, null)``

I am investigating on this issue...

**Comment by jmagman** [comment] 2021-12-20 21:12
Because you are using `google_maps_flutter` (which doesn't support arm simulators) the app is being run with Rosetta on the simulator. 
This is really a Rosetta bug, so either Apple needs to fix it, or keep an eye on getting all your plugins to support the simulator https://github.com/flutter/flutter/issues/94491

Duplicate of https://github.com/flutter/flutter/issues/71943.

**Closed by jmagman** 2021-12-20 21:12 UTC
Labels: waiting for customer response, in triage

**Comment by florian-gustin** [comment] 2021-12-26 22:07
> Because you are using `google_maps_flutter` (which doesn't support arm simulators) the app is being run with Rosetta on the simulator. This is really a Rosetta bug, so either Apple needs to fix it, or keep an eye on getting all your plugins to support the simulator #94491
> 
> Duplicate of #71943.

it actually works on a clean new arm app

**Comment by jmagman** [comment] 2022-01-04 19:28
Yes, it should work without `google_maps_flutter`.
