### ISSUE TITLE
Error 13, OS Error: Permission denied

### ISSUE THREAD

**Issue by JaSpErSta** [flutter/flutter#38345] opened 2019-08-12 19:53 UTC
## command
```
flutter doctor
```
## exception
```
FileSystemException: FileSystemException: Cannot open file, path = '/opt/flutter/bin/cache/flutter_version_check.stamp' (OS Error: Permission denied, errno = 13)
```
**How can flutter get this permission?**

**Comment by BondarenkoStas** [comment] 2019-09-06 12:06
Duplicate of #16898

**Closed by BondarenkoStas** 2019-09-06 12:06 UTC
