### ISSUE TITLE
Flutter plugin onAttachedToEngine called twice

### ISSUE THREAD

**Issue by apinprastya** [flutter/flutter#69721] opened 2020-11-03 23:33 UTC
## Steps to Reproduce

1. I have attached the test plugin to check. [testplugin.zip](https://github.com/flutter/flutter/files/5484659/testplugin.zip)
2. Run the example
3. When you check on logcat you will see that the "I GOT ATTACHED....." called twice

This bug only happen when I have the `android_alarm_manager` in the example project and called `AndroidAlarmManager.initialize()`

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.20.2, on Linux, locale en_US.UTF-8)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.50.1)
[✓] Connected device (1 available)

• No issues found!
```
![Screenshot from 2020-11-04 06-30-43](https://user-images.githubusercontent.com/1171479/98051855-4c917d00-1e67-11eb-9b3e-ce89b2d96e9f.png)

</details>

**Comment by darshankawar** [comment] 2020-11-04 08:31
@apinprastya 
Can you upgrade to latest stable and try again to see if issue perists ?

**Comment by apinprastya** [comment] 2020-11-04 22:35
Still happen with 1.22.3

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 1.22.3, on Microsoft Windows [Version 10.0.19041.572], locale en-US)
 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[√] Android Studio (version 4.0)
[√] VS Code, 64-bit edition (version 1.50.1)
[√] Connected device (1 available)
```

![image](https://user-images.githubusercontent.com/1171479/98175071-8080a700-1f28-11eb-9f6f-e1c275a0211a.png)

**Comment by darshankawar** [comment] 2020-11-05 05:55
<details>
<summary>flutter doctor -v</summary>

```

[✓] Flutter (Channel stable, 1.22.3, on Mac OS X 10.15.4 19E2269, locale en-IN)
    • Flutter version 1.22.3 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 8874f21e79 (6 days ago), 2020-10-29 14:14:35 -0700
    • Engine revision a1440ca392
    • Dart version 2.10.3

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.1

[✓] Connected device (1 available)
    • SM A260G (mobile) • 5200763ebcfa861f • android-arm • Android 8.1.0 (API
      27)

• No issues found!


```

</details>

<img width="1251" alt="Screenshot 2020-11-05 at 11 24 23 AM" src="https://user-images.githubusercontent.com/67046386/98203196-9b1f4400-1f59-11eb-8d4b-e3fd38e77efc.png">
<img width="1012" alt="Screenshot 2020-11-05 at 11 24 35 AM" src="https://user-images.githubusercontent.com/67046386/98203203-9e1a3480-1f59-11eb-9e9d-c471317f8e98.png">

**Comment by hukid** [comment] 2021-04-20 00:00
We hit the similar issue when integrate our flutter plugin with firebase_messaging, here is a repro PR https://github.com/square/in-app-payments-flutter-plugin/pull/153.

**Comment by hoanle** [comment] 2021-04-22 05:45
We faced the same issue and this caused other library failed to work (Segment)

**Comment by makstheimba** [comment] 2021-04-23 14:59
Same issue. I didn't yet manage to figure out what's the cause of it but I'm using firebase_messaging too

**Comment by stuartmorgan** [comment] 2021-05-27 15:39
Closing as `android_alarm_manager` is deprecated in favor of [`android_alarm_manager`](https://pub.dev/packages/android_alarm_manager_plus).

**Closed by stuartmorgan** 2021-05-27 15:39 UTC
Labels: P6, found in release: 1.22, has reproducible steps, p: android_alarm_manager, p: first party, passed first triage, platform-android, plugin

**Comment by stuartmorgan** [comment] 2024-06-26 14:47
For anyone finding this in the future, this is expected behavior, not a bug. See https://github.com/flutter/flutter/issues/150855.
