### ISSUE TITLE
Flutter Admob "The Google Mobile Ads SDK requires a deployment target of iOS 8.0 or later." error

### ISSUE THREAD

**Issue by CharlesCleveJr** [flutter/flutter#31900] opened 2019-05-01 12:58 UTC
After updating my iOS targets to 9.0 and adding the necessary info in my infoplist I am consistently getting the `The Google Mobile Ads SDK requires a deployment target of iOS 8.0 or later.` error in my GoogleMobileAds.h file on my iOS build followed by a crash.

Here is my pubsec.yaml packages...
dependencies:
  path_provider: ^0.4.1
  #onesignal: ^1.0.3
  flutter_facebook_login: ^1.1.1
  google_sign_in: ^3.2.4
  firebase_auth: ^0.6.6
  firebase_admob: ^0.8.0+4
  firebase_storage: ^1.0.4
  firebase_database: ^1.0.5
  url_launcher: ^4.0.1
  collection: 1.14.11
  flutter_webview_plugin: ^0.3.0+2
  cached_network_image: ^0.5.1
  image_picker: ^0.4.10
  http: ^0.12.0
  flutter:
    sdk: flutter

And my Flutter Doctor....

[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.13.6 17G6030, locale en-US)
    • Flutter version 1.2.1 at /Users/charlesclevelandjr./flutter
    • Framework revision 8661d8aecd (3 months ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/charlesclevelandjr./Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.1

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 34.0.2
    • Dart plugin version 183.5901
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] IntelliJ IDEA Community Edition (version 2019.1.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 35.0.3
    • Dart plugin version 191.7019

[✓] Connected device (1 available)
    • iPhone XR • E486013D-D82B-4AC9-9853-0F11B2135E56 • ios • iOS 12.1 (simulator)

• No issues found!

**Comment by CharlesCleveJr** [comment] 2019-05-05 17:27
Answer?  I may break something doing this, but I simply commented out the "if" statement in the Google Mobile Ads SDK

```
//#if __IPHONE_OS_VERSION_MIN_REQUIRED < __IPHONE_8_0
//#error The Google Mobile Ads SDK requires a deployment target of iOS 8.0 or later.
//#endif
```

It works for me now.  If anyone knows a more valid way of doing this or if I should never do this, I'm keeping this ticket open a while for comments.

**Comment by iapicca** [comment] 2020-01-15 12:13
Hi @CharlesCleveJr 
for what I can see the issue is related to a FlutterFire plugin,
please open the issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
thank you

**Closed by iapicca** 2020-01-15 12:13 UTC
Labels: d: stackoverflow
