### ISSUE TITLE
android_alarm_manager 0.2.3

### ISSUE THREAD

**Issue by siepi** [flutter/flutter#26526] opened 2019-01-14 14:06 UTC
when I run the app the error happens below
```
I/AlarmService( 4590): Starting AlarmService...
E/MethodChannel#plugins.flutter.io/android_alarm_manager( 4590): Failed to handle method call
E/MethodChannel#plugins.flutter.io/android_alarm_manager( 4590): java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.PluginRegistry$PluginRegistrantCallback.registerWith(io.flutter.plugin.common.PluginRegistry)' on a null object reference
E/MethodChannel#plugins.flutter.io/android_alarm_manager( 4590): 	at io.flutter.plugins.androidalarmmanager.AlarmService.startAlarmService(AlarmService.java:65)
E/MethodChannel#plugins.flutter.io/android_alarm_manager( 4590): 	at io.flutter.plugins.androidalarmmanager.AndroidAlarmManagerPlugin.startService(AndroidAlarmManagerPlugin.java:75)
E/MethodChannel#plugins.flutter.io/android_alarm_manager( 4590): 	at io.flutter.plugins.androidalarmmanager.AndroidAlarmManagerPlugin.onMethodCall(AndroidAlarmManagerPlugin.java:52)
E/MethodChannel#plugins.flutter.io/android_alarm_manager( 4590): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:200)
E/MethodChannel#plugins.flutter.io/android_alarm_manager( 4590): 	at io.flutter.view.FlutterNativeView$PlatformMessageHandlerImpl.handlePlatformMessage(FlutterNativeView.java:188)
E/MethodChannel#plugins.flutter.io/android_alarm_manager( 4590): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:202)
E/MethodChannel#plugins.flutter.io/android_alarm_manager( 4590): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#plugins.flutter.io/android_alarm_manager( 4590): 	at android.os.MessageQueue.next(MessageQueue.java:323)
E/MethodChannel#plugins.flutter.io/android_alarm_manager( 4590): 	at android.os.Looper.loop(Looper.java:136)
E/MethodChannel#plugins.flutter.io/android_alarm_manager( 4590): 	at android.app.ActivityThread.main(ActivityThread.java:6119)
E/MethodChannel#plugins.flutter.io/android_alarm_manager( 4590): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.flutter.io/android_alarm_manager( 4590): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
E/MethodChannel#plugins.flutter.io/android_alarm_manager( 4590): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
Error -32601 received from application: Method not found
method not available: ext.flutter.inspector.isWidgetCreationTracked
E/flutter ( 4590): [ERROR:flutter/shell/common/shell.cc(186)] Dart Error: Unhandled exception:
E/flutter ( 4590): MissingPluginException(No implementation found for method AlarmService.initialized on channel plugins.flutter.io/android_alarm_manager_background)
E/flutter ( 4590): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:300:7)
E/flutter ( 4590): <asynchronous suspension>
E/flutter ( 4590): #1      _alarmManagerCallbackDispatcher (package:android_alarm_manager/android_alarm_manager.dart:46:12)
E/flutter ( 4590): #2      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:289:19)
E/flutter ( 4590): #3      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
Error -32601 received from application: Method not found
method not available: ext.flutter.debugPaintError -32601 received from application: Method not found
method not available: ext.flutter.showPerformanceOverlaymethod not available: ext.flutter.repaintRainbowError -32601 received from application: Method not found
Error -32601 received from application: Method not found
method not available: ext.flutter.timeDilationError -32601 received from application: Method not found
method not available: ext.flutter.debugAllowBannerError -32601 received from application: Method not found
method not available: ext.flutter.debugPaintBaselinesEnabledError -32601 received from application: Method not found
method not available: ext.flutter.inspector.show
E/flutter ( 4590): [ERROR:flutter/shell/common/shell.cc(186)] Dart Error: Unhandled exception:
E/flutter ( 4590): PlatformException(error, Attempt to invoke interface method 'void io.flutter.plugin.common.PluginRegistry$PluginRegistrantCallback.registerWith(io.flutter.plugin.common.PluginRegistry)' on a null object reference, null)
E/flutter ( 4590): #0      JSONMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:149:7)
E/flutter ( 4590): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:302:33)
E/flutter ( 4590): <asynchronous suspension>
E/flutter ( 4590): #2      AndroidAlarmManager.initialize (package:android_alarm_manager/android_alarm_manager.dart:70:10)
E/flutter ( 4590): <asynchronous suspension>
E/flutter ( 4590): #3      main (package:notifications/main.dart:8:29)
E/flutter ( 4590): <asynchronous suspension>
E/flutter ( 4590): #4      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:289:19)
E/flutter ( 4590): #5      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```
```
[√] Flutter (Channel master, v1.1.10-pre.47, on Microsoft Windows [versÃ£o 10.0.17763.288], locale pt-BR)
    • Flutter version 1.1.10-pre.47 at C:\flutter
    • Framework revision fdea3655ae (8 hours ago), 2019-01-14 00:46:50 -0500
    • Engine revision abbc34e148
    • Dart version 2.1.1 (build 2.1.1-dev.1.0 f81dd1da9f)

[√] Android toolchain - develop for Android devices (Android SDK version 27.0.3)
    • Android SDK at C:\Users\ricar\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[√] Android Studio (version 3.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 31.1.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[√] VS Code (version 1.30.2)
    • VS Code at C:\Users\ricar\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 2.21.1

[√] VS Code, 64-bit edition (version 1.30.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 2.21.1

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 7.1.1 (API 25) (emulator)

• No issues found!
```

**Comment by zoechi** [comment] 2019-01-14 14:20
Looks like a duplicate of #21969

**Comment by siepi** [comment] 2019-01-14 22:05
Hi Zoechi. Thank for reply. I am sorry for my poor English and unexperiency with Android and flutter. Would you have a solution? I don't understood if somebody wrote a solution to this.

**Comment by zoechi** [comment] 2019-01-15 06:33
@siepi see the discussion in the linked issue.

Closing as duplicate of #21969

**Closed by zoechi** 2019-01-15 06:33 UTC

**Comment by bellalhrbubt** [comment] 2020-11-05 05:48
dfgdgdfg
