### ISSUE TITLE
AUR update fails to install

### ISSUE THREAD

**Issue by waynebloss** [flutter/flutter#35905] opened 2019-07-10 20:27 UTC
## Steps to Reproduce

1. Have `flutter` `1.5.4.hotfix.2-1` installed on Arch/Manjaro Linux.
2. Try to upgrade to `1.7.8.hotfix.3-1`

## Logs

```
Synchronizing package databases...
Starting full system upgrade...
Cloning flutter build files...
Checking flutter dependencies...

Building flutter...
==> Making package: flutter 1.7.8.hotfix.3-1 (Wed 10 Jul 2019 04:13:11 PM EDT)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Downloading flutter-1.7.8.hotfix.3.tar.xz...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0  320M    0 2910k    0     0  6313k      0  0:00:52 --:--:--  0:00:52 6300k
 25  320M   25 82.3M    0     0  56.3M      0  0:00:05  0:00:01  0:00:04 56.3M
 53  320M   53  170M    0     0  69.4M      0  0:00:04  0:00:02  0:00:02 69.4M
 81  320M   81  261M    0     0  75.6M      0  0:00:04  0:00:03  0:00:01 75.5M
100  320M  100  320M    0     0  77.7M      0  0:00:04  0:00:04 --:--:-- 77.7M
  -> Found flutter.sh
  -> Found flutter.csh
==> Validating source files with sha256sums...
    flutter-1.7.8.hotfix.3.tar.xz ... Passed
    flutter.sh ... Passed
    flutter.csh ... Passed
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Extracting flutter-1.7.8.hotfix.3.tar.xz with bsdtar
==> Starting build()...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.7.8+hotfix.3, on Linux, locale en_US.utf8)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Android Studio (version 3.4)
[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
==> Entering fakeroot environment...
==> Starting package()...
==> Tidying install...
  -> Removing empty directories...
  -> Removing libtool files...
  -> Purging unwanted files...
  -> Removing static library files...
  -> Stripping unneeded symbols from binaries and libraries...
  -> Compressing man and info pages...
==> Checking for packaging issues...
==> Creating package "flutter"...
  -> Generating .PKGINFO file...
  -> Generating .BUILDINFO file...
  -> Adding install file...
  -> Generating .MTREE file...
  -> Compressing package...
==> Leaving fakeroot environment.
==> Finished making: flutter 1.7.8.hotfix.3-1 (Wed 10 Jul 2019 04:22:18 PM EDT)
==> Cleaning up...

Resolving dependencies...
Checking inter-conflicts...

Checking keyring...
Checking integrity...
Loading packages files...
Checking file conflicts...
Failed to commit transaction:
conflicting files:
flutter: /opt/flutter/.pub-cache/hosted/pub.dartlang.org/http-0.12.0+2/.gitignore already exists in filesystem
flutter: /opt/flutter/.pub-cache/hosted/pub.dartlang.org/http-0.12.0+2/.test_config already exists in filesystem
flutter: /opt/flutter/.pub-cache/hosted/pub.dartlang.org/http-0.12.0+2/.travis.yml already exists in filesystem
flutter: /opt/flutter/.pub-cache/hosted/pub.dartlang.org/http-0.12.0+2/CHANGELOG.md already exists in filesystem
flutter: /opt/flutter/.pub-cache/hosted/pub.dartlang.org/http-0.12.0+2/LICENSE already exists in filesystem
flutter: /opt/flutter/.pub-cache/hosted/pub.dartlang.org/http-0.12.0+2/README.md already exists in filesystem
flutter: /opt/flutter/.pub-cache/hosted/pub.dartlang.org/http-0.12.0+2/analysis_options.yaml already exists in filesystem
flutter: /opt/flutter/.pub-cache/hosted/pub.dartlang.org/http-0.12.0+2/example/main.dart already exists in filesystem
flutter: /opt/flutter/.pub-cache/hosted/pub.dartlang.org/http-0.12.0+2/lib/browser_client.dart already exists in filesystem
flutter: /opt/flutter/.pub-cache/hosted/pub.dartlang.org/http-0.12.0+2/lib/http.dart already exists in filesystem
flutter: /opt/flutter/.pub-cache/hosted/pub.dartlang.org/http-0.12.0+2/lib/io_client.dart already exists in filesystem
flutter: /opt/flutter/.pub-cache/hosted/pub.dartlang.org/http-0.12.0+2/lib/src/base_client.dart already exists in filesystem
flutter: /opt/flutter/.pub-cache/hosted/pub.dartlang.org/http-0.12.0+2/lib/src/base_request.dart already exists in filesystem
flutter: /opt/flutter/.pub-cache/hosted/pub.dartlang.org/http-0.12.0+2/lib/src/base_response.dart already exists in filesystem
flutter: /opt/flutter/.pub-cache/hosted/pub.dartlang.org/http-0.12.0+2/lib/src/boundary_characters.dart already exists in filesystem
flutter: /opt/flutter/.pub-cache/hosted/pub.dartlang.org/http-0.12.0+2/lib/src/browser_client.dart already exists in filesystem
flutter: /opt/flutter/.pub-cache/hosted/pub.dartlang.org/http-0.12.0+2/lib/src/byte_stream.dart already exists in filesystem
flutter: /opt/flutter/.pub-cache/hosted/pub.dartlang.org/http-0.12.0+2/lib/src/client.dart already exists in filesystem
flutter: /opt/flutter/.pub-cache/hosted/pub.dartlang.org/http-0.12.0+2/lib/src/client_stub.dart already exists in filesystem
flutter: /opt/flutter/.pub-cache/hosted/pub.dartlang.org/http-0.12.0+2/lib/src/exception.dart already exists in filesystem
flutter: /opt/flutter/.pub-cache/hosted/pub.dartlang.org/http-0.12.0+2/lib/src/io_client.dart already exists in filesystem
flutter: /opt/flutter/.pub-cache/hosted/pub.dartlang.org/http-0.12.0+2/lib/src/mock_client.dart already exists in filesystem
flutter: /opt/flutter/.pub-cache/hosted/pub.dartlang.org/http-0.12.0+2/lib/src/multipart_file.dart already exists in filesystem
flutter: /opt/flutter/.pub-cache/hosted/pub.dartlang.org/http-0.12.0+2/lib/src/multipart_file_io.dart already exists in filesystem
flutter: /opt/flutter/.pub-cache/hosted/pub.dartlang.org/http-0.12.0+2/lib/src/multipart_file_stub.dart already exists in filesystem
flutter: /opt/flutter/.pub-cache/hosted/pub.dartlang.org/http-0.12.0+2/lib/src/multipart_request.dart already exists in filesystem
flutter: /opt/flutter/.pub-cache/hosted/pub.dartlang.org/http-0.12.0+2/lib/src/request.dart already exists in filesystem
flutter: /opt/flutter/.pub-cache/hosted/pub.dartlang.org/http-0.12.0+2/lib/src/response.dart already exists in filesystem
flutter: /opt/flutter/.pub-cache/hosted/pub.dartlang.org/http-0.12.0+2/lib/src/streamed_request.dart already exists in filesystem
flutter: /opt/flutter/.pub-cache/hosted/pub.dartlang.org/http-0.12.0+2/lib/src/streamed_response.dart already exists in filesystem
flutter: /opt/flutter/.pub-cache/hosted/pub.dartlang.org/http-0.12.0+2/lib/src/utils.dart already exists in filesystem
flutter: /opt/flutter/.pub-cache/hosted/pub.dartlang.org/http-0.12.0+2/lib/testing.dart already exists in filesystem
flutter: /opt/flutter/.pub-cache/hosted/pub.dartlang.org/http-0.12.0+2/pubspec.yaml already exists in filesystem
flutter: /opt/flutter/.pub-cache/hosted/pub.dartlang.org/http-0.12.0+2/test/html/client_test.dart already exists in filesystem
flutter: /opt/flutter/.pub-cache/hosted/pub.dartlang.org/http-0.12.0+2/test/html/streamed_request_test.dart already exists in filesystem
flutter: /opt/flutter/.pub-cache/hosted/pub.dartlang.org/http-0.12.0+2/test/html/utils.dart already exists in filesystem
flutter: /opt/flutter/.pub-cache/hosted/pub.dartlang.org/http-0.12.0+2/test/io/client_test.dart already exists in filesystem
flutter: /opt/flutter/.pub-cache/hosted/pub.dartlang.org/http-0.12.0+2/test/io/http_test.dart already exists in filesystem
flutter: /opt/flutter/.pub-cache/hosted/pub.dartlang.org/http-0.12.0+2/test/io/multipart_test.dart already exists in filesystem
flutter: /opt/flutter/.pub-cache/hosted/pub.dartlang.org/http-0.12.0+2/test/io/request_test.dart already exists in filesystem
flutter: /opt/flutter/.pub-cache/hosted/pub.dartlang.org/http-0.12.0+2/test/io/streamed_request_test.dart already exists in filesystem
flutter: /opt/flutter/.pub-cache/hosted/pub.dartlang.org/http-0.12.0+2/test/io/utils.dart already exists in filesystem
flutter: /opt/flutter/.pub-cache/hosted/pub.dartlang.org/http-0.12.0+2/test/mock_client_test.dart already exists in filesystem
flutter: /opt/flutter/.pub-cache/hosted/pub.dartlang.org/http-0.12.0+2/test/multipart_test.dart already exists in filesystem
flutter: /opt/flutter/.pub-cache/hosted/pub.dartlang.org/http-0.12.0+2/test/request_test.dart already exists in filesystem
flutter: /opt/flutter/.pub-cache/hosted/pub.dartlang.org/http-0.12.0+2/test/response_test.dart already exists in filesystem
flutter: /opt/flutter/.pub-cache/hosted/pub.dartlang.org/http-0.12.0+2/test/streamed_request_test.dart already exists in filesystem
flutter: /opt/flutter/.pub-cache/hosted/pub.dartlang.org/http-0.12.0+2/test/utils.dart already exists in filesystem
```

**Comment by waynebloss** [comment] 2019-07-10 20:46
Fixed with `sudo rm -rf /opt/flutter/.pub-cache/hosted`

**Comment by LongCatIsLooong** [comment] 2019-07-10 23:38
Closing as it doesn't look like the issue is with flutter. Feel free to reopen if you think it is.

**Closed by LongCatIsLooong** 2019-07-10 23:38 UTC

**Comment by waynebloss** [comment] 2019-07-11 13:02
Ahhh, OK thank you. I didn't realize that the AUR package was non-official.
