### ISSUE TITLE
[image_picker] plugin NPE on a Motorola Moto Z on v0.4.5

### ISSUE THREAD

**Issue by acidjazz** [flutter/flutter#21102] opened 2018-08-28 05:44 UTC
This looks similar to #18059  and #17186

```
java.lang.RuntimeException: 
  at android.app.ActivityThread.performResumeActivity (ActivityThread.java:3720)
  at android.app.ActivityThread.handleResumeActivity (ActivityThread.java:3760)
  at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:2969)
  at android.app.ActivityThread.-wrap11 (Unknown Source)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1655)
  at android.os.Handler.dispatchMessage (Handler.java:105)
  at android.os.Looper.loop (Looper.java:164)
  at android.app.ActivityThread.main (ActivityThread.java:6665)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.Zygote$MethodAndArgsCaller.run (Zygote.java:240)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:772)
Caused by: java.lang.RuntimeException: 
  at android.app.ActivityThread.deliverResults (ActivityThread.java:4422)
  at android.app.ActivityThread.performResumeActivity (ActivityThread.java:3692)
Caused by: java.lang.NullPointerException: 
  at io.flutter.plugins.imagepicker.ImagePickerDelegate$3.getFullImagePath (ImagePickerDelegate.java:147)
  at io.flutter.plugins.imagepicker.ImagePickerDelegate.handleCaptureImageResult (ImagePickerDelegate.java:417)
  at io.flutter.plugins.imagepicker.ImagePickerDelegate.onActivityResult (ImagePickerDelegate.java:378)
  at io.flutter.app.FlutterPluginRegistry.onActivityResult (FlutterPluginRegistry.java:194)
  at io.flutter.app.FlutterActivityDelegate.onActivityResult (FlutterActivityDelegate.java:146)
  at io.flutter.app.FlutterActivity.onActivityResult (FlutterActivity.java:139)
  at android.app.Activity.dispatchActivityResult (Activity.java:7255)
  at android.app.ActivityThread.deliverResults (ActivityThread.java:4418)
```

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v0.5.7, on Mac OS X 10.14 18A365a, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
[✓] Android Studio (version 3.1)
[✓] VS Code (version 1.26.1)
[✓] Connected devices (5 available)
```

**Comment by zoechi** [comment] 2018-08-28 06:48
Can you please elaborate on what steps are required to reproduce?

**Comment by acidjazz** [comment] 2018-08-28 14:11
sure @zoechi , I have 6 occurrences of this crash now it and it's mostly when they use the camera from the app. They take the picture, confirm it via the camera, then they get the app's loading screen for a second and that's when the crash occurs.

**Comment by 3ace** [comment] 2018-09-02 04:13
I also have this problem, I'm using 0.4.10 right now. on Moto G first gen.

the crash occurs right after finished taking photo from camera.

here's the stacktrace

> E/AndroidRuntime(27578): FATAL EXCEPTION: main
> E/AndroidRuntime(27578): Process: com.company.myapp, PID: 27578
> E/AndroidRuntime(27578): java.lang.RuntimeException: Unable to resume activity {com.company.myapp/com.company.myapp.MainActivity}: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=2343, result=-1, data=null} to activity {com.company.myapp/com.company.myapp.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.getPath()' on a null object reference
> E/AndroidRuntime(27578):        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3028)
> E/AndroidRuntime(27578):        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3063)
> E/AndroidRuntime(27578):        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2418)
> E/AndroidRuntime(27578):        at android.app.ActivityThread.access$800(ActivityThread.java:155)
> E/AndroidRuntime(27578):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1317)
> E/AndroidRuntime(27578):        at android.os.Handler.dispatchMessage(Handler.java:102)
> E/AndroidRuntime(27578):        at android.os.Looper.loop(Looper.java:135)
> E/AndroidRuntime(27578):        at android.app.ActivityThread.main(ActivityThread.java:5343)
> E/AndroidRuntime(27578):        at java.lang.reflect.Method.invoke(Native Method)
> E/AndroidRuntime(27578):        at java.lang.reflect.Method.invoke(Method.java:372)
> E/AndroidRuntime(27578):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
> E/AndroidRuntime(27578):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
> E/AndroidRuntime(27578): Caused by: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=2343, result=-1, data=null} to activity {com.company.myapp/com.company.myapp.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.getPath()' on a null object reference
> E/AndroidRuntime(27578):        at android.app.ActivityThread.deliverResults(ActivityThread.java:3659)
> E/AndroidRuntime(27578):        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3002)
> E/AndroidRuntime(27578):        ... 11 more
> E/AndroidRuntime(27578): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.getPath()' on a null object reference
> E/AndroidRuntime(27578):        at io.flutter.plugins.imagepicker.ImagePickerDelegate$3.getFullImagePath(ImagePickerDelegate.java:147)
> E/AndroidRuntime(27578):        at io.flutter.plugins.imagepicker.ImagePickerDelegate.handleCaptureImageResult(ImagePickerDelegate.java:417)
> E/AndroidRuntime(27578):        at io.flutter.plugins.imagepicker.ImagePickerDelegate.onActivityResult(ImagePickerDelegate.java:378)
> E/AndroidRuntime(27578):        at io.flutter.app.FlutterPluginRegistry.onActivityResult(FlutterPluginRegistry.java:210)
> E/AndroidRuntime(27578):        at io.flutter.app.FlutterActivityDelegate.onActivityResult(FlutterActivityDelegate.java:139)
> E/AndroidRuntime(27578):        at io.flutter.app.FlutterActivity.onActivityResult(FlutterActivity.java:138)
> E/AndroidRuntime(27578):        at android.app.Activity.dispatchActivityResult(Activity.java:6218)
> E/AndroidRuntime(27578):        at android.app.ActivityThread.deliverResults(ActivityThread.java:3655)

**Comment by 3ace** [comment] 2018-09-02 09:09
I just tested using version 0.4.5 and it didn't crashed. It crashed when I'm using version 0.4.6 or 0.4.7.

**Comment by zoechi** [comment] 2018-09-15 08:46
Looks similar to #17950

**Comment by acidjazz** [comment] 2018-10-03 18:49
and another
```
java.lang.RuntimeException: 
  at android.app.ActivityThread.performResumeActivity (ActivityThread.java:3720)
  at android.app.ActivityThread.handleResumeActivity (ActivityThread.java:3760)
  at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:2969)
  at android.app.ActivityThread.-wrap11 (Unknown Source)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1655)
  at android.os.Handler.dispatchMessage (Handler.java:105)
  at android.os.Looper.loop (Looper.java:164)
  at android.app.ActivityThread.main (ActivityThread.java:6665)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.Zygote$MethodAndArgsCaller.run (Zygote.java:240)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:772)
Caused by: java.lang.RuntimeException: 
  at android.app.ActivityThread.deliverResults (ActivityThread.java:4422)
  at android.app.ActivityThread.performResumeActivity (ActivityThread.java:3692)
Caused by: java.lang.NullPointerException: 
  at io.flutter.plugins.imagepicker.ImagePickerDelegate$3.getFullImagePath (ImagePickerDelegate.java:147)
  at io.flutter.plugins.imagepicker.ImagePickerDelegate.handleCaptureImageResult (ImagePickerDelegate.java:417)
  at io.flutter.plugins.imagepicker.ImagePickerDelegate.onActivityResult (ImagePickerDelegate.java:378)
  at io.flutter.app.FlutterPluginRegistry.onActivityResult (FlutterPluginRegistry.java:210)
  at io.flutter.app.FlutterActivityDelegate.onActivityResult (FlutterActivityDelegate.java:139)
  at io.flutter.app.FlutterActivity.onActivityResult (FlutterActivity.java:138)
  at android.app.Activity.dispatchActivityResult (Activity.java:7255)
  at android.app.ActivityThread.deliverResults (ActivityThread.java:4418)
```

**Comment by eseidelGoogle** [comment] 2018-11-26 18:53
FYI @cbracken as part of looking at crashers.  Would be good to learn how common this is in the wild.

**Comment by tanamduit** [comment] 2019-02-11 04:28
any update with this ?

**Comment by cyanglaz** [comment] 2019-04-19 21:54
This should be fixed by https://github.com/flutter/plugins/commit/37706c42f4d54f886dbfca88c0d786ae6f615486 
@opensourcegps could you check if it is fixed for you after updating to the new version of image_picker? 0.5.3+2

**Closed** 2019-04-28 04:01 UTC
Labels: e: device-specific, p: first party, p: image_picker, plugin, severe: crash, waiting for customer response, ▣ platform-android

**Comment by FiciusProject** [comment] 2020-03-02 18:09
Restart the phone.

**Comment by soonsam123** [comment] 2020-06-20 12:48
> Restart the phone.

My issue was happening only in one of my phone's clients which had the app installed since 4 moths ago. The other phones were working properly.

This probably is a particular issue but, restarting this client's phone actually worked.
