### ISSUE TITLE
`flutter build apk` crashes in profile and release modes on Mac host

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#4600] opened 2016-06-16 19:58 UTC
## Steps to Reproduce

On a Mac host, run:

```sh
flutter build apk --release
```

## Logs and Crash Reports

```
$ flutter build apk --release
Building APK in release mode (android-arm-release)...
Error: Dart_SetField: did not find top-level variable '_isolateId'.
Failed to build AOT snapshot
```

/cc @abarth

**Comment by abarth** [comment] 2016-06-16 20:06
Dupe of #4598

**Closed by abarth** 2016-06-16 20:06 UTC
Labels: affects: tools, ⚠ bug (regression)
