### ISSUE TITLE
I have error with DraggableScrollableSheet

### ISSUE THREAD

**Issue by Hellomik2002** [flutter/flutter#79915] opened 2021-04-07 02:04 UTC
I call DraggableScrollableSheet
```
                    showModalBottomSheet(
                      backgroundColor: Colors.transparent,
                      context: context,
                      isScrollControlled: true,
                      useRootNavigator: true,
                      builder: (ctx) => GestureDetector(
                        behavior: HitTestBehavior.opaque,
                        onTap: () => Navigator.pop(ctx),
                        child: Align(
                          alignment: Alignment.bottomCenter,
                          child: DraggableScrollableSheet(
                            expand: false,
                            initialChildSize: 0.8,
                            maxChildSize: 0.9,
                            minChildSize: 0.3,
                            builder: (context, scrollController) =>
                                ChooseCountry1Page(
                              scrollController: scrollController,
                            ),
                          ),
                        ),
                      ),
                    );
```
THE WIDGET 

<details>
<summary>widget</summary>

```dart
class ChooseCountry1Page extends StatefulWidget {
  final ScrollController scrollController;
  const ChooseCountry1Page({
    this.scrollController,
    Key key,
  }) : super(key: key);

  @override
  _ChooseCountry1PageState createState() => _ChooseCountry1PageState();
}

class _ChooseCountry1PageState extends State<ChooseCountry1Page> {
  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      onTap: () {
        final _f = FocusScope.of(context);
        if (_f.hasFocus || _f.hasPrimaryFocus) {
          _f.unfocus();
        }
      },
      child: Material(
        color: dark1Color,
        child: Stack(
          children: [
            ListView.separated(
              padding: EdgeInsets.only(top: 56),
              controller: widget.scrollController,
              itemCount: countries.length,
              itemBuilder: (_, index) {
                return ListTile(
                  onTap: () {},
                  title: Text(
                    countries[index].name,
                    style: regularStyle.copyWith(color: Colors.white),
                  ),
                );
              },
              separatorBuilder: (_, __) => Divider(
                height: 1,
                indent: 16,
                color: Color(0xff3F3F3F),
              ),
            ),
            Material(
              color: dark1Color,
              child: TopStack(
                title: S.of(context).language,
              ),
            ),
          ],
        ),
      ),
    );
  }
}
```

</details>

THE ERROR happens when I close DraggableScrollabeSheet

<details>
<summary>logs</summary>

```bash
════════ Exception caught by widgets library ═══════════════════════════════════
The following assertion was thrown while finalizing the widget tree:
ScrollableState#dd1a8(tickers: tracking 3 tickers, position: _DraggableScrollableSheetScrollPosition#24257(offset: -32.0, range: -1.0..14506.1, viewport: 262.6, ScrollableState, BouncingScrollPhysics -> RangeMaintainingScrollPhysics, null, ScrollDirection.idle), effective physics: BouncingScrollPhysics -> RangeMaintainingScrollPhysics) was disposed with an active Ticker.

ScrollableState created a Ticker via its TickerProviderStateMixin, but at the time dispose() was called on the mixin, that Ticker was still active. All Tickers must be disposed before calling super.dispose().

Tickers used by AnimationControllers should be disposed by calling dispose() on the AnimationController itself. Otherwise, the ticker will leak.

The offending ticker was: _WidgetTicker(created by ScrollableState#dd1a8(tickers: tracking 1 ticker, position: _DraggableScrollableSheetScrollPosition#24257(offset: -44.0, range: 0.0..14518.5, viewport: 250.2, ScrollableState, BouncingScrollPhysics -> RangeMaintainingScrollPhysics, BallisticScrollActivity#6a0f9(AnimationController#1de93(▶ -44.011; for BallisticScrollActivity)), ScrollDirection.idle), effective physics: BouncingScrollPhysics -> RangeMaintainingScrollPhysics))
The stack trace when the _WidgetTicker was actually created was:
#0      new Ticker.<anonymous closure>
package:flutter/…/scheduler/ticker.dart:67
#1      new Ticker
package:flutter/…/scheduler/ticker.dart:69
#2      new _WidgetTicker
package:flutter/…/widgets/ticker_provider.dart:271
#3      TickerProviderStateMixin.createTicker
package:flutter/…/widgets/ticker_provider.dart:202
#4      new AnimationController.unbounded
package:flutter/…/animation/animation_controller.dart:280
#5      _DraggableScrollableSheetScrollPosition.goBallistic
package:flutter/…/widgets/draggable_scrollable_sheet.dart:478
#6      BallisticScrollActivity.applyNewDimensions
package:flutter/…/widgets/scroll_activity.dart:535
#7      ScrollPosition.applyNewDimensions
package:flutter/…/widgets/scroll_position.dart:593
#8      ScrollPositionWithSingleContext.applyNewDimensions
package:flutter/…/widgets/scroll_position_with_single_context.dart:104
#9      ScrollPosition.applyContentDimensions
package:flutter/…/widgets/scroll_position.dart:533
#10     _DraggableScrollableSheetScrollPosition.applyContentDimensions
package:flutter/…/widgets/draggable_scrollable_sheet.dart:440
#11     RenderViewport.performLayout
package:flutter/…/rendering/viewport.dart:1483
#12     RenderObject._layoutWithoutResize
package:flutter/…/rendering/object.dart:1641
#13     PipelineOwner.flushLayout
package:flutter/…/rendering/object.dart:884
#14     RendererBinding.drawFrame
package:flutter/…/rendering/binding.dart:453
#15     WidgetsBinding.drawFrame
package:flutter/…/widgets/binding.dart:874
#16     RendererBinding._handlePersistentFrameCallback
package:flutter/…/rendering/binding.dart:319
#17     SchedulerBinding._invokeFrameCallback
package:flutter/…/scheduler/binding.dart:1144
#18     SchedulerBinding.handleDrawFrame
package:flutter/…/scheduler/binding.dart:1082
#19     SchedulerBinding._handleDrawFrame
package:flutter/…/scheduler/binding.dart:998
#23     _invoke (dart:ui/hooks.dart:161:10)
#24     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:253:5)
#25     _drawFrame (dart:ui/hooks.dart:120:31)
(elided 3 frames from dart:async)

When the exception was thrown, this was the stack
#0      TickerProviderStateMixin.dispose.<anonymous closure>
package:flutter/…/widgets/ticker_provider.dart:219
#1      TickerProviderStateMixin.dispose
package:flutter/…/widgets/ticker_provider.dart:237
#2      RestorationMixin.dispose
package:flutter/…/widgets/restoration.dart:1078
#3      ScrollableState.dispose
package:flutter/…/widgets/scrollable.dart:466
#4      StatefulElement.unmount
package:flutter/…/widgets/framework.dart:4721
...
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by animation library ═════════════════════════════════
Null check operator used on a null value
════════════════════════════════════════════════════════════════════════════════

```

</details>

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 2.0.4, on Mac OS X 10.15.7 19H15 darwin-x64, locale en-KZ)
    • Flutter version 2.0.4 at /Users/hellomik/development/flutter
    • Framework revision b1395592de (5 days ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/hellomik/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Community Edition (version 2020.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.55.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (2 available)
    • iPad (2) (mobile) • 00008027-001E219C1AF8402E • ios            • iOS 14.4.1
    • Chrome (web)      • chrome                    • web-javascript • Google Chrome 89.0.4389.114

• No issues found!
```

</details>

It can be connected with default ScrollPhysics on IOS

**Comment by pedromassangocode** [comment] 2021-04-13 09:43
Hi @Hellomik2002 
Can you please provide a [minimal complete reproducible code](https://stackoverflow.com/help/minimal-reproducible-example) sample that I can just copy/paste? the code you provided above does makes reference to properties that I don't have.
Thank you

**Comment by Hellomik2002** [comment] 2021-04-16 11:59
> Hi @Hellomik2002
> Can you please provide a [minimal complete reproducible code](https://stackoverflow.com/help/minimal-reproducible-example) sample that I can just copy/paste? the code you provided above does makes reference to properties that I don't have.
> Thank you

Yep Just call 
and use BouncingScrollPhysics() to replicate the issue on Android 
```
showModalBottomSheet(
                      backgroundColor: Colors.transparent,
                      context: context,
                      isScrollControlled: true,
                      useRootNavigator: true,
                      builder: (ctx) => GestureDetector(
                        behavior: HitTestBehavior.opaque,
                        onTap: () => Navigator.pop(ctx),
                        child: Align(
                          alignment: Alignment.bottomCenter,
                          child: DraggableScrollableSheet(
                            expand: false,
                            initialChildSize: 0.8,
                            maxChildSize: 0.9,
                            minChildSize: 0.3,
                            builder: (context, scrollController) =>
                                ListView.builder(
                                  controller: scrollController,
                                   itemBuilder: (ctx, _ind) => Container(
                                   color: Colors.green,
                                   height: 300,
                                  ),
                                                  itemCount: 50,
                              ),
                          ),
                        ),
                      ),
```

**Comment by pedromassangocode** [comment] 2021-04-16 13:13
Hi @Hellomik2002
I cannot reproduce this issue with the code bellow.
Can you please provide clear steps to reproduce this issue?

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  static const String _title = 'Flutter Code Sample';

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: _title,
      home: Scaffold(
        body: Center(
          child: Builder(
            builder: (context) {
              return ElevatedButton(
                child: Text(''),
                onPressed: () {
                  showModalBottomSheet(
                      backgroundColor: Colors.transparent,
                      context: context,
                      isScrollControlled: true,
                      useRootNavigator: true,
                      builder: (ctx) => GestureDetector(
                    behavior: HitTestBehavior.opaque,
                    onTap: () => Navigator.pop(ctx),
                    child: Align(
                      alignment: Alignment.bottomCenter,
                      child: DraggableScrollableSheet(
                        expand: false,
                        initialChildSize: 0.8,
                        maxChildSize: 0.9,
                        minChildSize: 0.3,
                        builder: (context, scrollController) =>
                            ListView.builder(
                              controller: scrollController,
                              physics: BouncingScrollPhysics(),
                              itemBuilder: (ctx, _ind) => Container(
                                color: Colors.green,
                                height: 300,
                              ),
                              itemCount: 50,
                            ),
                      ),
                    ),
                  ));
                },
              );
            }
          ),
        ),
      ),
    );
  }
}

```
</details>

**Comment by abhishekak048** [comment] 2021-04-19 07:58
This might help you.
https://github.com/abhishekak048/scrollable-bottomsheet

**Comment by pedromassangocode** [comment] 2021-05-12 11:39
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2021-05-12 11:39 UTC
Labels: in triage, waiting for customer response
