### ISSUE TITLE
Felt optimizations for build and test separation

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#92312] opened 2021-10-22 07:24 UTC
Felt expects the compiled engine to exist in a given location and the compiled tests in the same location of the original tests. Those expectations makes the logic to run tests from archived artifacts complicated and error prone.

I'd like to propose to update the felt tool to accept two different environment variables:

$ENGINE_BUILD: to point to the archived engine build
$WEBENGINE_TEST: to point to the archived compiled javascript tests

In addition to that the felt tools seems to force compile the tests even if the compiled versions exist. The following is the script I've been using to test the workflow: 

```
#!/bin/bash
  
rm -rf out
rm -rf flutter
cipd install infra/tools/luci/cas/linux-amd64
./cas download -dir out -digest cf51b2df227551e52c37756ef4d7fd4be6ed14b053b945ecbb919173d0cd4973/160  -cas-instance projects/chromium-swarm/instances/default_instance
git clone https://github.com/flutter/engine.git flutter
./cas download -dir out -digest 258d9eb204fdfa7549577cf10f93e4acf7e30acbbf19d24c98b49a289fda29a9/91 -cas-instance projects/chromium-swarm/instances/default_instance
pushd flutter/web_sdk/web_engine_tester
../../../out/host_debug_unopt/dart-sdk/bin/dart pub get
popd
pushd flutter/lib/web_ui
mkdir -p build
cp -r ../../../out/test build/
../../../out/host_debug_unopt/dart-sdk/bin/dart pub get
../../../out/host_debug_unopt/dart-sdk/bin/dart dev/felt.dart test --browser=chrome
popd
```

**Comment by yjbanov** [comment] 2021-11-02 22:55
Build/test separation in `felt` is as follows:

```
# Compiles tests, doesn't run tests
felt run compile_tests
```

```
# Runs tests, doesn't compile them; assumes they have been compiled already
felt run run_tests_*
```

Where `run_tests_*` is one of:

- `run_tests_chrome`
- `run_tests_edge`
- `run_tests_firefox`
- `run_tests_safari`
- `run_tests_ios-safari`

What if instead of `WEB_ENGINE_TEST` environment variable we simply move the compiled web test output to a different location. For example, we could move them to `src/out`. Would that obviate the need for evironment variables?

Having said that, environment variables should be fine too. Just trying to think if a convention, such as Bazel's "runfiles", would be simpler.

**Comment by godofredoc** [comment] 2021-11-03 06:34
Is there a way to debug what is going wrong with running the tests from archives? the execution hangs after the devtools listening message.

This is the command we are running:
```
../../../out/host_debug_unopt/dart-sdk/bin/dart dev/felt.dart run run_tests_chrome
```

This is the output:
```
...
+ watcher 1.0.0 (1.0.1 available)
+ web_engine_tester 0.0.0 from path ../../web_sdk/web_engine_tester
+ web_socket_channel 2.1.0
+ web_test_utils 0.0.0 from path ../../web_sdk/web_test_utils
+ webkit_inspection_protocol 1.0.0
+ xml 5.1.2 (5.3.1 available)
+ yaml 3.0.0 (3.1.0 available)
Changed 59 dependencies!
Running steps 
Running  loading test/golden_tests/golden_failure_smoke_test.dart
INFO: Starting Chrome download.
[CHROME STDERR]:
[CHROME STDERR]:DevTools listening on ws://127.0.0.1:12345/devtools/browser/17a4bd96-1e07-47d1-a1c8-33e31eceb520
```

**Comment by yjbanov** [comment] 2021-11-11 21:51
Fixed by https://github.com/flutter/engine/pull/29666

@godofredoc it was probably caused by a bug in the build. To debug felt itself you can just run it using the `dart` command and use the regular Dart debugger. To debug code running in the browser, you can do `felt test --debug path/to/the_test.dart` then debug using Chrome DevTools. Hopefully, this particular failure is gone with https://github.com/flutter/engine/pull/29666.

**Closed by yjbanov** 2021-11-11 21:51 UTC
Labels: passed first triage, team: infra, passed secondary triage, P3
