### ISSUE TITLE
iOS simulator unavailable, device type profile not found

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#97303] opened 2022-01-26 17:39 UTC
Try job `module_test_ios` trying to create a simulator:
```
[module_test_ios] [STDOUT] Executing "xcrun simctl create TestAdd2AppSim com.apple.CoreSimulator.SimDeviceType.iPhone-11 com.apple.CoreSimulator.SimRuntime.iOS-14-3" in "/opt/s/w/ir/x/w/recipe_cleanup/tmp81ddsf_o/flutter sdk" with environment {BOT: true, LANG: en_US.UTF-8}
[module_test_ios] [STDOUT] stderr: Invalid device type: com.apple.CoreSimulator.SimDeviceType.iPhone-11
```

List of simulators shows all the simulators are "unavailable, device type profile not found"
```
-- iOS 13.0 --
    iPad Air (3rd generation) (C657E8D4-422B-4449-94E7-3B04431E2F18) (Shutdown) (unavailable, device type profile not found)
    iPad Pro (11-inch) (C3480239-0A68-47BF-97E9-20CFDA93F7D9) (Shutdown) (unavailable, device type profile not found)
    iPad Pro (12.9-inch) (3rd generation) (19F3AE1E-AFAB-447B-9AF6-7B8BB57D9897) (Shutdown) (unavailable, device type profile not found)
    iPad Pro (9.7-inch) (117D9CD0-82C8-458D-B3C4-8CA0331A03AD) (Shutdown) (unavailable, device type profile not found)
    iPhone 11 (6B11A7F3-E077-42F1-9911-D7C1B8D55CCE) (Shutdown) (unavailable, device type profile not found)
    iPhone 11 Pro (2E9AD3C2-AEE6-4152-A14F-882F3DFFDF91) (Shutdown) (unavailable, device type profile not found)
    iPhone 11 Pro Max (8C49B646-040E-4CB6-9FDC-10362CEB54B1) (Shutdown) (unavailable, device type profile not found)
    iPhone 8 (5DCC7E66-B73E-463A-A91D-F28E3B4E329B) (Shutdown) (unavailable, device type profile not found)
    iPhone 8 Plus (18E32AAD-47C2-424D-8A9E-7BFEEA4727A1) (Shutdown) (unavailable, device type profile not found)
```
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8823963857735512193/+/u/list_simulators/stdout

Compare to a successful prod run.  Both are running `12c33`.
```
-- iOS 13.0 --
    iPhone 8 (D6D03B46-EA7B-4A19-9115-6DB597FCF8B6) (Shutdown) 
    iPhone 8 Plus (D23E78A6-2A7F-410D-91FD-2D6779CC411B) (Shutdown) 
    iPhone 11 (3ACE52C8-0530-491A-9226-6A95068DFEF8) (Shutdown) 
    iPhone 11 Pro (6C3DB249-0409-4726-BABB-8BF3417E3E12) (Shutdown) 
    iPhone 11 Pro Max (98B27E12-DECA-41F3-AD22-530C3FE08CC9) (Shutdown) 
    iPad Pro (9.7-inch) (9A5CB7DA-3709-4970-BA8E-A359F60F2A2C) (Shutdown) 
    iPad Pro (11-inch) (EB1BBB3C-9519-4976-B394-D5E3F1C81455) (Shutdown) 
    iPad Pro (12.9-inch) (3rd generation) (420854E4-EE4A-4962-AE41-157DF43EA734) (Shutdown) 
    iPad Air (3rd generation) (4DEB6175-773A-45C8-A791-AF125666FDD9) (Shutdown) 
```
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8823956734184440353/+/u/list_simulators/stdout

Blocking the plugin roll https://github.com/flutter/flutter/pull/97295, which is blocking an engine roll.

**Comment by jmagman** [comment] 2022-01-26 17:43
Re-running the test in https://github.com/flutter/flutter/pull/97295, I don't see it failing in other PRs (that PR is definitely not the issue though)

**Comment by jmagman** [comment] 2022-01-26 17:44
Suspect the re-run will succeed, the simulator list looks correct:
```
-- iOS 13.0 --
    iPhone 8 (96198A19-44E4-4FAB-8516-DD50D00289BF) (Shutdown) 
    iPhone 8 Plus (91CF9D98-4DBC-4451-A823-A0A5B8A59EC6) (Shutdown) 
    iPhone 11 (D6B26EFF-F0AC-4071-A061-94336006AC33) (Shutdown) 
    iPhone 11 Pro (B03469C1-55BD-4B36-BD88-A082F905115B) (Shutdown) 
    iPhone 11 Pro Max (16B9D00E-E5F5-42E1-B5F7-C5B78458BFF0) (Shutdown) 
    iPad Pro (9.7-inch) (C19AAD9E-F393-4AEE-86B0-D3B99F6CAFD2) (Shutdown) 
    iPad Pro (11-inch) (B4B9BB52-BFE4-422D-8B5E-B06A759E3FEB) (Shutdown) 
    iPad Pro (12.9-inch) (3rd generation) (07FC72C6-605D-4A1D-ACB6-A1FF09BA7D09) (Shutdown) 
    iPad Air (3rd generation) (E552B27C-FDCD-4228-B33E-74C9A8207A54) (Shutdown)
```
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8823953796628412001/+/u/list_simulators/stdout

Reducing priority.

**Comment by jmagman** [comment] 2022-01-26 17:48
I've seen that `unavailable, device type profile not found` before while investigating https://github.com/flutter/flutter/issues/91689 when simulator runtimes were missing, but the runtimes look correct this time:
```
== Runtimes ==
iOS 13.0 (13.0 - 17A577) - com.apple.CoreSimulator.SimRuntime.iOS-13-0
iOS 14.3 (14.3 - 18C61) - com.apple.CoreSimulator.SimRuntime.iOS-14-3
watchOS 6.1 (6.1.1 - 17S445) - com.apple.CoreSimulator.SimRuntime.watchOS-6-1
watchOS 7.2 (7.2 - 18S561) - com.apple.CoreSimulator.SimRuntime.watchOS-7-2
```

**Comment by jmagman** [comment] 2022-01-26 17:49
And interestingly only the 14.3 iPhone 12* devices are available...?
```
== Device Types ==
iPhone 12 mini (com.apple.CoreSimulator.SimDeviceType.iPhone-12-mini)
iPhone 12 (com.apple.CoreSimulator.SimDeviceType.iPhone-12)
iPhone 12 Pro (com.apple.CoreSimulator.SimDeviceType.iPhone-12-Pro)
iPhone 12 Pro Max (com.apple.CoreSimulator.SimDeviceType.iPhone-12-Pro-Max)
...
-- iOS 14.3 --
    iPhone 12 mini (5B76E7EE-4109-4327-BD3C-08B088482192) (Shutdown) 
    iPhone 12 (5F6A55BC-C974-4D3B-AC0F-B92F55ED1AD6) (Shutdown) 
    iPhone 12 Pro (E7FEF58E-626E-4EFB-AE6A-5CB49FCE6321) (Shutdown) 
    iPhone 12 Pro Max (787AB908-C531-44CD-9530-524CCA545D60) (Shutdown)
```
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8823963857735512193/+/u/list_simulators/stdout

**Comment by CaseyHillers** [comment] 2022-01-26 18:10
I'll monitor the builds to see if this flake occurs again

**Comment by godofredoc** [comment] 2022-01-27 23:09
Waiting for the battery healthcheck to land in production.

**Comment by jmagman** [comment] 2022-01-27 23:12
I don't think this is related to the tethered device's health, it's that the simulators aren't set up in a way Xcode can find them.

**Comment by godofredoc** [comment] 2022-01-28 02:10
Would this be fixed with the new way to provide runtimes?

**Comment by keyonghan** [comment] 2022-02-02 18:56
The error repeated intermittently:
https://ci.chromium.org/ui/p/flutter/builders/try/Mac%20module_test_ios/11849/overview (02/01/2022)
https://ci.chromium.org/ui/p/flutter/builders/try/Mac%20module_test_ios/11846/overview (02/01/2022)
https://ci.chromium.org/ui/p/flutter/builders/try/Mac%20module_test_ios/11804/overview (01/31/2022)
https://ci.chromium.org/ui/p/flutter/builders/try/Mac%20module_test_ios/11764/overview (01/28/2022)
https://ci.chromium.org/ui/p/flutter/builders/try/Mac%20module_test_ios/11718/overview (01/27/2022)

**Comment by keyonghan** [comment] 2022-02-02 18:58
Seem the failures happened on only two bots: [build857-m9](https://chromium-swarm.appspot.com/bot?id=build857-m9) and [build866-m9](https://chromium-swarm.appspot.com/bot?id=build866-m9).

Take a further look, builder `Mac module_test_ios` has been consistently failing on these two bots.

/cc @jmagman Any settings/config that may cause this behavior from bot side? All bots should be configured in the same way though.

**Comment by jmagman** [comment] 2022-02-02 21:12
Maybe the simulator device types were removed on those machines?  I can't figure out where on disk the different types of simulator device images would live though.

**Comment by godofredoc** [comment] 2022-02-02 21:42
Could this be related to testing the runtimes functionality of osx_sdk in those two bots?

**Comment by jmagman** [comment] 2022-02-02 21:49
Not sure, from https://github.com/flutter/flutter/issues/97303#issuecomment-1022440937 the symptoms look different, the simulator runtimes (OS version `iOS-14-3`) is present, but the actual device type images (`iPhone-11`) is missing.

I could change the test to `iPhone 12` which does seem available, though it would be good to know why the builders are different.

**Comment by godofredoc** [comment] 2022-02-02 23:54
@keyonghan can we delete the caches on those two machines and manually re-run the test?

**Comment by jmagman** [comment] 2022-02-03 01:01
> I can't figure out where on disk the different types of simulator device images would live though.

I think they are in `Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/DeviceTypes/`?

**Comment by keyonghan** [comment] 2022-02-03 05:52
> @keyonghan  can we delete the caches on those two machines and manually re-run the test?

Cleaning caches helps! Here is a success run with a pass on build857-m9.
https://luci-milo.appspot.com/raw/build/logs.chromium.org/flutter/led/keyonghan_google.com/b66b7c9f91b799685187926648693d492f39716dc480d0c09add5ab16ba6c5c1/+/build.proto

Will run a couple of times, and also on the other bot to verify.

**Comment by keyonghan** [comment] 2022-02-03 17:26
Five times all passed on build857-m9.
Same pass on build866-m9 after caches clean.
Closing. Please reopen if issue happens again.

**Comment by jmagman** [comment] 2022-02-10 04:47
This just happened again:
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8822650102210541713/+/u/list_simulators/stdout

Failing test:
```
plugin_lint_mac] [STDOUT] stdout:  -> integration_test (0.0.1)
[plugin_lint_mac] [STDOUT] stdout:     - ERROR | [iOS] unknown: Encountered an unknown error (Could not find a `ios` simulator (valid values: watchos). Ensure that Xcode -> Window -> Devices has at least one `ios` simulator listed or otherwise add one.
```

**Comment by jmagman** [comment] 2022-02-10 04:53
This happened again, bad cache? https://ci.chromium.org/p/flutter/builders/try/Mac%20plugin_lint_mac/11006
Preventing us from re-opening the tree in https://github.com/flutter/flutter/pull/98166

**Comment by godofredoc** [comment] 2022-02-10 05:14
Retrying the build will pick a different builder which will unblock the tree.

**Comment by jmagman** [comment] 2022-02-10 05:57
I do keep retrying...
[build904-m9](https://ci.chromium.org/p/flutter/builders/try/Mac%20plugin_lint_mac/11008)
[build877-m9](https://ci.chromium.org/p/flutter/builders/try/Mac%20plugin_lint_mac/11006)
[build891-m9](https://ci.chromium.org/p/flutter/builders/try/Mac%20plugin_lint_mac/11005)

**Comment by godofredoc** [comment] 2022-02-10 06:07
Seems like it all started here: https://github.com/flutter/flutter/pull/98144

**Comment by godofredoc** [comment] 2022-02-10 06:09
We'll need to manually clean all the caches for the bots in try

**Comment by godofredoc** [comment] 2022-02-10 06:30
I'll block all the bots and cleaned 3 to unblock you. I'll cleanup the rest tomorrow.

**Comment by jmagman** [comment] 2022-02-10 16:00
It happened again at 4am
https://ci.chromium.org/ui/p/flutter/builders/try/Mac%20plugin_lint_mac/11011/overview

**Comment by godofredoc** [comment] 2022-02-10 16:38
Cleaning the caches didn't fix this bot. Any other ideas of what may be happening?

**Comment by godofredoc** [comment] 2022-02-10 16:42
I cleaned build870-m9, build871-m9, build872-m9. Only 871 has run the test and it has failed consistently. Any reason why only this test is failing?

**Comment by jmagman** [comment] 2022-02-10 18:39
It should fail for any test running on iOS simulators. For example https://ci.chromium.org/p/flutter/builders/try/Mac%20build_tests_2_4/15814 shows the same issue where [iOS simulator device types aren't found](https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8822604892238727121/+/u/list_simulators/stdout), but that test isn't running anything on a simulator.

`module_test_ios` would likely also fail because it's running on a simulator, but it's marked flaky so isn't running in presubmit.

**Comment by yusuf-goog** [comment] 2022-02-14 21:30
@jmagman do you know if we need to run `xcrun simctl upgrade` or similar, to get the emulators to work with Xcode 13 after the upgrade?

**Comment by jmagman** [comment] 2022-02-14 22:21
I don't think that would be necessary, is it failing on machines running macOS 12 and Xcode 13?  Or just old macOS 10.15 machines where Xcode 13 was mistakenly run before https://github.com/flutter/cocoon/pull/1597 merged?

**Comment by fzyzcjy** [comment] 2022-02-22 04:15
How is it going? Seems that this is P0 for a week

**Comment by keyonghan** [comment] 2022-02-22 20:12
@jmagman `Mac plugin_lint_mac` has been passing consistently.

> module_test_ios would likely also fail because it's running on a simulator, but it's marked flaky so isn't running in presubmit.

`module_test_ios` is actually running on pre-submit, but it is failing intermittently with a different error: 
```
[module_test_ios] [STDOUT] Executing: xcrun simctl list runtimes in /opt/s/w/ir/x/w/recipe_cleanup/tmpqxpd1lm0/flutter sdk with environment {BOT: true, LANG: en_US.UTF-8}
[module_test_ios] [STDOUT] stdout: == Runtimes ==
[module_test_ios] [STDOUT] stdout: iOS 13.0 (13.0 - 17A577) - com.apple.CoreSimulator.SimRuntime.iOS-13-0
[module_test_ios] [STDOUT] stdout: iOS 14.3 (14.3 - 18C61) - com.apple.CoreSimulator.SimRuntime.iOS-14-3
[module_test_ios] [STDOUT] stdout: watchOS 6.1 (6.1.1 - 17S445) - com.apple.CoreSimulator.SimRuntime.watchOS-6-1
[module_test_ios] [STDOUT] stdout: watchOS 7.2 (7.2 - 18S561) - com.apple.CoreSimulator.SimRuntime.watchOS-7-2
[module_test_ios] [STDOUT] "xcrun" exit code: 0
[module_test_ios] [STDOUT] 
[module_test_ios] [STDOUT] Executing: xcrun simctl create TestAdd2AppSim com.apple.CoreSimulator.SimDeviceType.iPhone-11 com.apple.CoreSimulator.SimRuntime.iOS-14-3 in /opt/s/w/ir/x/w/recipe_cleanup/tmpqxpd1lm0/flutter sdk with environment {BOT: true, LANG: en_US.UTF-8}
[module_test_ios] [STDOUT] stderr: Invalid device type: com.apple.CoreSimulator.SimDeviceType.iPhone-11
[module_test_ios] [STDOUT] "xcrun" exit code: 146
[module_test_ios] [STDOUT] 
```

Shall we open a separate bug to track?

**Comment by jmagman** [comment] 2022-02-22 21:11
That's the same issue, just logging slightly differently.  It's trying to create an iPhone-11 simulator, but the device type isn't found, but the requested runtime (iOS-14-3) is available.

**Comment by jmagman** [comment] 2022-02-22 22:24
On machines where this is happening, what's in 
```
/opt/s/w/ir/cache/osx_sdk/XCode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/DeviceTypes/
```
It should contain `iPhone 11.simdevicetype`.

**Comment by keyonghan** [comment] 2022-02-22 22:39
For the most recent failure: https://ci.chromium.org/ui/p/flutter/builders/try/Mac%20module_test_ios/12054/overview, which ran on bot: build877-m9. Here is the list under the requested dir, and it does contain `iPhone 11.simdevicetype`:
```
chrome-bot@build877-m9 DeviceTypes % ls /opt/s/c/8I/XCode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/DeviceTypes
iPad (5th generation).simdevicetype			iPhone 11.simdevicetype
iPad (6th generation).simdevicetype			iPhone 12 Pro Max.simdevicetype
iPad (7th generation).simdevicetype			iPhone 12 Pro.simdevicetype
iPad (8th generation).simdevicetype			iPhone 12 mini.simdevicetype
iPad 2.simdevicetype					iPhone 12.simdevicetype
iPad Air (3rd generation).simdevicetype			iPhone 4s.simdevicetype
iPad Air (4th generation).simdevicetype			iPhone 5.simdevicetype
iPad Air 2.simdevicetype				iPhone 5s.simdevicetype
iPad Air.simdevicetype					iPhone 6 Plus.simdevicetype
iPad Pro (10.5-inch).simdevicetype			iPhone 6.simdevicetype
iPad Pro (11-inch) (1st generation).simdevicetype	iPhone 6s Plus.simdevicetype
iPad Pro (11-inch) (2nd generation).simdevicetype	iPhone 6s.simdevicetype
iPad Pro (12.9-inch) (1st generation).simdevicetype	iPhone 7 Plus.simdevicetype
iPad Pro (12.9-inch) (2nd generation).simdevicetype	iPhone 7.simdevicetype
iPad Pro (12.9-inch) (3rd generation).simdevicetype	iPhone 8 Plus.simdevicetype
iPad Pro (12.9-inch) (4th generation).simdevicetype	iPhone 8.simdevicetype
iPad Pro (9.7-inch).simdevicetype			iPhone SE (1st generation).simdevicetype
iPad Retina.simdevicetype				iPhone SE (2nd generation).simdevicetype
iPad mini (5th generation).simdevicetype		iPhone X.simdevicetype
iPad mini 2.simdevicetype				iPhone Xs Max.simdevicetype
iPad mini 3.simdevicetype				iPhone Xs.simdevicetype
iPad mini 4.simdevicetype				iPhone X??.simdevicetype
iPhone 11 Pro Max.simdevicetype				iPod touch (7th generation).simdevicetype
iPhone 11 Pro.simdevicetype
```

**Comment by jmagman** [comment] 2022-02-23 01:57
> it does contain `iPhone 11.simdevicetype`

So it does. I'm at a loss then... Maybe this will clear up once we have Xcode 13 on these machines, and the new way of incrementally downloading the cipd simulator runtimes. https://github.com/flutter/flutter/issues/91689

@keyonghan it might help to debug these issues if there was a `[devicelab/devicelab_drone](https://cs.opensource.google/search/?q=file%3Arecipes%2Fdevicelab%2Fdevicelab_drone.py)` recipe step right after installing Xcode to list the available simulators, like https://flutter-review.googlesource.com/c/recipes/+/24440

**Comment by keyonghan** [comment] 2022-02-23 18:18
Actually in the above CL, the `list simulators` step was already added for both devicelab tests and host only tests. See https://ci.chromium.org/ui/p/flutter/builders/try/Mac%20module_test_ios/12037/overview, where we hit the issue and also listed the simulators.

In the `== Device Types ==`, there was no `iPhone-11`.

(For other failed ones which didn't have the `list simulators` step, they seemed running on release branches which used release version recipe bundle and the change may not be picked up yet.)

**Comment by jmagman** [comment] 2022-02-23 21:57
I'm not sure what's going on with these devices being missing, but maybe we can move https://github.com/flutter/flutter/pull/98297 along, which uses the new version of Xcode, and downloads some simulator bits separately.
That's still blocked on flakiness in `web_tool_tests` https://github.com/flutter/flutter/issues/98278, but could we move all the tests over to `Mac-12` and `13a233` except `web_tool_tests`?

**Comment by jmagman** [comment] 2022-02-23 22:00
Like this: https://github.com/flutter/flutter/pull/98297/files#diff-9e73abde9fff445f31e5928e80d2d3f88847e02fd8f76d46f66f147fdc82786dR3054-R3055

**Comment by jmagman** [comment] 2022-02-24 03:20
Hoping this just goes away with https://github.com/flutter/flutter/pull/98297 but I'm an optimist.

**Comment by keyonghan** [comment] 2022-02-28 18:09
Closing this one in favor of https://github.com/flutter/flutter/issues/99039?

**Comment by jmagman** [comment] 2022-02-28 18:32
I don't think this is the same issue even though it looks close, in https://github.com/flutter/flutter/issues/99039 the runtime (managed by cipd) isn't available, in this one the runtime is available, but the device type isn't.  I don't understand where the device type lives if not `Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/DeviceTypes/`.  Both may be cleared up by the Xcode cache clearing.  We can reopen this one if it shows up again.

**Comment by jmagman** [comment] 2022-03-29 23:04
Happened again in https://ci.chromium.org/p/flutter/builders/prod/Mac%20Web%20Engine/9553.

**Comment by jmagman** [comment] 2022-03-29 23:07
@CaseyHillers this is on `Mac Web Engine` which is using `{ "name": "old_osx_sdk", "path": "osx_sdk" }`, is it possible https://flutter-review.googlesource.com/c/infra/+/28440/ caused issues here?

**Comment by keyonghan** [comment] 2022-03-30 00:05
The above cl added only two more runtime caches without affecting existing osx_sdk cache:
![Screen Shot 2022-03-29 at 5 02 19 PM](https://user-images.githubusercontent.com/54558023/160725360-9340ddcc-8064-4500-80bb-53f963bcbb4b.png)

**Comment by keyonghan** [comment] 2022-03-30 00:11
The two failed builds happened on https://chromium-swarm.appspot.com/bot?id=build818-m9 and https://chromium-swarm.appspot.com/bot?id=build817-m9, both had an earlier failed run on `Mac clang-tidy` at step `install xcode`. Wondering if we need a cache refresh. 

Trying an led run on a good bot to validate.

**Comment by keyonghan** [comment] 2022-03-30 00:24
An led run on build819: https://luci-milo.appspot.com/raw/build/logs.chromium.org/flutter/led/keyonghan_google.com/728275e5db28c25ac54938b9e956ab0e40a80813c891077d4d8edf567cc8398b/+/build.proto

So far the device type profile is there. Expectation is the build will pass.

**Comment by godofredoc** [comment] 2022-03-30 01:02
Can we try led runs on build818 and 817 and check the content of the xcode simruntime folder from ssh?

**Comment by keyonghan** [comment] 2022-03-30 04:38
Latest update:
Led runs on two failed bots:
[build 817](https://luci-milo.appspot.com/raw/build/logs.chromium.org/flutter/led/keyonghan_google.com/dd9796d8d1811b3811676f4ca5a284512ef558b1d39808d530f7f9bb51a75e53/+/build.proto), [build 818](https://luci-milo.appspot.com/raw/build/logs.chromium.org/flutter/led/keyonghan_google.com/063e0b73acfe7f0f9ec900429779cf6cda404b89546798c77e35bf31cecbbc0e/+/build.proto)

I was blocked on permission issue to ssh to these bots, and @godofredoc is helping validate some cases instead of simply refreshing the caches. From godofredo:
```
The problem was that the build was run with runtimes property and the old cache name
```

**Comment by zanderso** [comment] 2022-03-30 15:02
What's the status of this? The Engine tree has been closed for 17 hours.

**Comment by CaseyHillers** [comment] 2022-03-30 15:48
Out of curiosity, why is Mac Web Engine left on Mac 10? I kicked off a build in https://ci.chromium.org/ui/p/flutter/builders/try/Mac%20Web%20Engine/24081/overview to see if it would pass on Mac 12.

**Comment by jmagman** [comment] 2022-03-30 16:44
> Out of curiosity, why is Mac Web Engine left on Mac 10?

It's on macOS 10.15 and Xcode 12.3 because Safari won't launch on the Xcode 13 simulators https://github.com/flutter/flutter/issues/99885

**Comment by CaseyHillers** [comment] 2022-03-30 16:59
Copying from internal chat (thanks @keyonghan for the recap):
1. @jmagman landed PR to push engine builders to xcode13+mac12 with Web Engine remaining in mac10
2. In post-submit, the ci.yaml roller broke (os dimension not populated and post-submit scheduler had a bug), those builders are still running on mac10 but with new xcode version and runtime (which is not compatible)
3. @CaseyHillers  helped manual roll the ci yaml, and other engine builders are switched to mac12 and running through
4. However for Web Engine, it is still running on mac10, where earlier failed builds (new xcode and runtime) have polluted the cache.

The hesitation here is there's an issue with the recipes not correctly identifying older xcodes/simulators being used, and not wiped the directory.

AIs:
1. @CaseyHillers to move build825-m9 for future investigation on the true root cause
2. Infra will wipe the mac caches on Mac 10 bots

**Comment by CaseyHillers** [comment] 2022-03-30 17:12
I went through the engine build dashboard to find Mac 10 bots run that failed with xcode 13. I gathered the list and will start wiping them:
```
# Failed bot list
build812-m9
build813-m9
build814-m9
build815-m9
build816-m9
build817-m9
build818-m9
build820-m9
build821-m9
build822-m9
build823-m9
build824-m9
build826-m9
build827-m9
```

**Comment by jmagman** [comment] 2022-03-30 17:57
> Talked with @yjbanov and it seems like Mac Web Engine is running on Mac 12 now. We landed [flutter/engine#32337](https://github.com/flutter/engine/pull/32337) as the issue is running this test on the corrupt Mac 10 bots.

This builder failed many times on Xcode 13 due to https://github.com/flutter/flutter/issues/99885 /cc @godofredoc it passed a few times for reasons we couldn't figure out.

**Comment by keyonghan** [comment] 2022-03-30 19:14
The latest build is hanging. I guess we need a revert: https://github.com/flutter/engine/pull/32340
Meanwhile, I am cleaning up caches.

**Comment by keyonghan** [comment] 2022-03-30 19:18
Led run on a refreshed bot: https://luci-milo.appspot.com/raw/build/logs.chromium.org/flutter/led/keyonghan_google.com/340047dc7d61d76dffb91c87cff50b598859bc233a41f175c627a520692da442/+/build.proto

**Comment by godofredoc** [comment] 2022-03-30 20:38
I have some local changes I used for validation yesterday unfortunately I haven't been able to test them yet. I'll upload the current version of the recipe change just in case someone has free cycles to validate it.

**Comment by godofredoc** [comment] 2022-03-30 21:06
Here is a run with the changes to remove the runtimes properly: https://chromium-swarm.appspot.com/task?id=59f5766358a6e610

**Comment by keyonghan** [comment] 2022-03-30 21:12
All bots are cleaned up, and we should be ready to land https://github.com/flutter/engine/pull/32340 to unblock the tree.

**Comment by CaseyHillers** [comment] 2022-03-31 14:02
After 15+ green runs, this looks fixed. Thanks Keyong!

**Closed by CaseyHillers** 2022-03-31 14:02 UTC
Labels: team: flakes, team: infra, passed secondary triage, P0
