### ISSUE TITLE
[Web]: Changing the order of PlatformViews (iFrame) in a Stack causes the render to fail

### ISSUE THREAD

**Issue by durduman** [flutter/flutter#101580] opened 2022-04-08 13:57 UTC
Hi, 

A possible fix would be to avoid using Keys in the Positioned widget (L: 42) but this would cause the internal state of the HtmlElementView (or other displayed items such as videos) to reset their state as they are actually disposed.

In the example below, maybe the usage of the platform factory is wrongly implemented or Keys aren't supposed to be used like this. However, I suspect this to be related to DOM & Flutter's SDK.

[Example project for the issue.](https://github.com/durduman/FlutterWebPlatformIssue)

<details><summary>Issue demoed</summary>

![ezgif com-gif-maker](https://user-images.githubusercontent.com/1089865/162450600-cf8774bd-f1e8-447d-8d0f-154a3a857986.gif)
</details>

<details><summary>flutter doctor -v</summary>
```
$ flutter doctor -v
[✓] Flutter (Channel stable, 2.10.4, on macOS 11.6 20G165 darwin-x64, locale en-GB)
    • Flutter version 2.10.4 at /Users/Durdu/Durdu/Home/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (2 weeks ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/Durdu/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_25-b17)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] VS Code (version 1.66.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.38.1

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 100.0.4896.75
    ! Error: iPhone is not connected. Xcode will continue when iPhone is connected. (code -13)

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```
</details>

Related link:

[HtmlElementView](https://api.flutter.dev/flutter/widgets/HtmlElementView-class.html)

[platform-views-using-html-slots-web](https://docs.flutter.dev/release/breaking-changes/platform-views-using-html-slots-web)

Thanks in advance!

**Comment by darshankawar** [comment] 2022-04-11 07:29
@durduman 
Thanks for the report. Running your example code sample using both renderers gives me below log. Is this the error you are reporting ?

<details>
<summary> console error log </summary>

```

Loading app from service worker.
Loading app from service worker.
TypeError: Cannot read properties of null (reading 'removeChild')
    at HTMLDocument.<anonymous> (http://localhost:51644/main.dart.js:72:22)
    at http://localhost:51644/dwds/src/injected/client.js:24313:40
    at _wrapJsFunctionForAsync_closure.$protected (http://localhost:51644/dwds/src/injected/client.js:3475:15)
    at _wrapJsFunctionForAsync_closure.call$2 (http://localhost:51644/dwds/src/injected/client.js:11576:12)
    at _awaitOnObject_closure.call$1 (http://localhost:51644/dwds/src/injected/client.js:11564:32)
    at StaticClosure._rootRunUnary (http://localhost:51644/dwds/src/injected/client.js:3837:18)
    at _CustomZone.runUnary$2$2 (http://localhost:51644/dwds/src/injected/client.js:12982:39)
    at _Future__propagateToListeners_handleValueCallback.call$0 (http://localhost:51644/dwds/src/injected/client.js:12008:51)
    at Object._Future__propagateToListeners (http://localhost:51644/dwds/src/injected/client.js:3617:93)
    at _Future._completeWithValue$1 (http://localhost:51644/dwds/src/injected/client.js:11834:9)
    at _AsyncAwaitCompleter.complete$1 (http://localhost:51644/dwds/src/injected/client.js:11547:14)
    at Object._asyncReturn (http://localhost:51644/dwds/src/injected/client.js:3447:17)
    at http://localhost:51644/dwds/src/injected/client.js:8761:24
    at _wrapJsFunctionForAsync_closure.$protected (http://localhost:51644/dwds/src/injected/client.js:3475:15)
    at _wrapJsFunctionForAsync_closure.call$2 (http://localhost:51644/dwds/src/injected/client.js:11576:12)
    at _awaitOnObject_closure.call$1 (http://localhost:51644/dwds/src/injected/client.js:11564:32)
    at StaticClosure._rootRunUnary (http://localhost:51644/dwds/src/injected/client.js:3837:18)
    at _CustomZone.runUnary$2$2 (http://localhost:51644/dwds/src/injected/client.js:12982:39)
    at _Future__propagateToListeners_handleValueCallback.call$0 (http://localhost:51644/dwds/src/injected/client.js:12008:51)
    at Object._Future__propagateToListeners (http://localhost:51644/dwds/src/injected/client.js:3617:93)
    at _Future._completeWithValue$1 (http://localhost:51644/dwds/src/injected/client.js:11834:9)
    at _AsyncAwaitCompleter.complete$1 (http://localhost:51644/dwds/src/injected/client.js:11547:14)
    at Object._asyncReturn (http://localhost:51644/dwds/src/injected/client.js:3447:17)
    at http://localhost:51644/dwds/src/injected/client.js:24785:24
    at _wrapJsFunctionForAsync_closure.$protected (http://localhost:51644/dwds/src/injected/client.js:3475:15)
    at _wrapJsFunctionForAsync_closure.call$2 (http://localhost:51644/dwds/src/injected/client.js:11576:12)
    at _awaitOnObject_closure.call$1 (http://localhost:51644/dwds/src/injected/client.js:11564:32)
    at StaticClosure._rootRunUnary (http://localhost:51644/dwds/src/injected/client.js:3837:18)
    at _CustomZone.runUnary$2$2 (http://localhost:51644/dwds/src/injected/client.js:12982:39)
    at _Future__propagateToListeners_handleValueCallback.call$0 (http://localhost:51644/dwds/src/injected/client.js:12008:51)
    at Object._Future__propagateToListeners (http://localhost:51644/dwds/src/injected/client.js:3617:93)
    at _Future._completeWithValue$1 (http://localhost:51644/dwds/src/injected/client.js:11834:9)
    at _AsyncAwaitCompleter.complete$1 (http://localhost:51644/dwds/src/injected/client.js:11547:14)
    at Object._asyncReturn (http://localhost:51644/dwds/src/injected/client.js:3447:17)
    at http://localhost:51644/dwds/src/injected/client.js:24762:24
    at _wrapJsFunctionForAsync_closure.$protected (http://localhost:51644/dwds/src/injected/client.js:3475:15)
    at _wrapJsFunctionForAsync_closure.call$2 (http://localhost:51644/dwds/src/injected/client.js:11576:12)
    at _awaitOnObject_closure.call$1 (http://localhost:51644/dwds/src/injected/client.js:11564:32)
    at StaticClosure._rootRunUnary (http://localhost:51644/dwds/src/injected/client.js:3837:18)
    at _CustomZone.runUnary$2$2 (http://localhost:51644/dwds/src/injected/client.js:12982:39)
    at _Future__propagateToListeners_handleValueCallback.call$0 (http://localhost:51644/dwds/src/injected/client.js:12008:51)
    at Object._Future__propagateToListeners (http://localhost:51644/dwds/src/injected/client.js:3617:93)
    at _Future._completeWithValue$1 (http://localhost:51644/dwds/src/injected/client.js:11834:9)
    at _Future__asyncCompleteWithValue_closure.call$0 (http://localhost:51644/dwds/src/injected/client.js:11936:18)
    at StaticClosure._rootRun (http://localhost:51644/dwds/src/injected/client.js:3822:16)
    at _CustomZone.run$1$1 (http://localhost:51644/dwds/src/injected/client.js:12974:39)
    at _CustomZone.runGuarded$1 (http://localhost:51644/dwds/src/injected/client.js:12917:14)
    at _CustomZone_bindCallbackGuarded_closure.call$0 (http://localhost:51644/dwds/src/injected/client.js:13112:25)
    at Object._microtaskLoop (http://localhost:51644/dwds/src/injected/client.js:3681:24)
    at StaticClosure._startMicrotaskLoop (http://localhost:51644/dwds/src/injected/client.js:3687:11)
    at _AsyncRun__initializeScheduleImmediate_internalCallback.call$1 (http://localhost:51644/dwds/src/injected/client.js:11452:9)
    at invokeClosure (http://localhost:51644/dwds/src/injected/client.js:1274:26)
    at MutationObserver.<anonymous> (http://localhost:51644/dwds/src/injected/client.js:1293:18)
TypeError: Cannot read properties of null (reading 'removeChild')


```

</details>

**Comment by durduman** [comment] 2022-04-11 07:41
> 

Hi, 
Thanks for checking this!
My log is different:


`
This app is linked to the debug service: ws://127.0.0.1:58376/Gv7Hp50Rc28=/ws
Debug service listening on ws://127.0.0.1:58376/Gv7Hp50Rc28=/ws

💪 Running with sound null safety 💪

🔥  To hot restart changes while running, press "r" or "R".
For a more detailed help message, press "h". To quit, press "q".

An Observatory debugger and profiler on Chrome is available at: http://127.0.0.1:58376/Gv7Hp50Rc28=
Height of Platform View type: [1] may not be set. Defaulting to `height: 100%`.
Set `style.height` to any appropriate value to stop this message.
Width of Platform View type: [1] may not be set. Defaulting to `width: 100%`.
Set `style.width` to any appropriate value to stop this message.
Height of Platform View type: [2] may not be set. Defaulting to `height: 100%`.
Set `style.height` to any appropriate value to stop this message.
Width of Platform View type: [2] may not be set. Defaulting to `width: 100%`.
Set `style.width` to any appropriate value to stop this message.
The Flutter DevTools debugger and profiler on Chrome is available at: http://127.0.0.1:9102?uri=http://127.0.0.1:58376/Gv7Hp50Rc28=
══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
The following TypeErrorImpl was thrown during a scheduler callback:
Unexpected null value.

When the exception was thrown, this was the stack:
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 251:49      throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 528:63  nullCheck
lib/_engine/engine/canvaskit/embedded_views.dart 496:74                           submitFrame
lib/_engine/engine/canvaskit/rasterizer.dart 36:33                                draw
lib/_engine/engine/platform_dispatcher.dart 585:7                                 render
lib/ui/src/ui/window.dart 94:50                                                   render
packages/flutter/src/rendering/view.dart 231:15                                   compositeFrame
packages/flutter/src/rendering/binding.dart 501:18                                drawFrame
packages/flutter/src/widgets/binding.dart 883:13                                  drawFrame
packages/flutter/src/rendering/binding.dart 363:5                                 [_handlePersistentFrameCallback]
packages/flutter/src/scheduler/binding.dart 1144:15                               [_invokeFrameCallback]
packages/flutter/src/scheduler/binding.dart 1081:9                                handleDrawFrame
packages/flutter/src/scheduler/binding.dart 995:5                                 [_handleDrawFrame]
lib/_engine/engine/platform_dispatcher.dart 1011:13                               invoke
lib/_engine/engine/platform_dispatcher.dart 159:5                                 invokeOnDrawFrame
lib/_engine/engine/initialization.dart 128:45                                     <fn>
════════════════════════════════════════════════════════════════════════════════════════════════════
Another exception was thrown: Unexpected null value.
Another exception was thrown: Unexpected null value.
Another exception was thrown: Unexpected null value.
Another exception was thrown: Assertion failed: org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/canvaskit/embedded_views.dart:696:16
Another exception was thrown: Assertion failed: org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/canvaskit/embedded_views.dart:704:12
Another exception was thrown: Assertion failed: org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/canvaskit/embedded_views.dart:704:12
Another exception was thrown: Assertion failed: org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/canvaskit/embedded_views.dart:616:16
Another exception was thrown: Assertion failed: org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/canvaskit/embedded_views.dart:616:16`

**Comment by darshankawar** [comment] 2022-04-12 05:29
Thanks for the update. I am actually not seeing the same error log as reported, but seeing the one I observed after running the code sample provided on latest stable and master and using both renderers.

error log : https://github.com/flutter/flutter/issues/101580#issuecomment-1094649383

<details>
<summary> runnable code sample </summary>

```
import 'dart:html' as html;
import 'dart:ui' as ui;
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);
  @override
  Widget build(BuildContext context) => const MaterialApp(home: MyHomePage());
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key}) : super(key: key);
  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  List<int> order = [
    1,
    2,
  ];

  void _reverseOrder() {
    setState(() {
      order = order.reversed.toList();
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Test'),
      ),
      body: Stack(
          children: order
              .map<Widget>((o) => Positioned(
            key: Key(o.toString() + o.toString()),
            /*
                    key is used
                    */
            left: o * 100,
            top: o * 100,
            width: o * 250,
            height: o * 250,
            child: Stack(
              children: [
                child(o),
                Center(child: Text(o.toString())),
              ],
            ),
          ))
              .toList()),
      floatingActionButton: FloatingActionButton(
        onPressed: _reverseOrder,
        tooltip: 'Reverse order of widgets',
        child: const Icon(Icons.refresh),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}

Widget child(int id) {
  return createIFrame(
    'sample.pdf',
    id.toString(),
  );

  // // Works without issues with non platform widgets
  // return Container(
  //   color: Color.fromARGB(255, 100 * id, 100 * id, 100 * id),
  // );
}

Widget createIFrame(
    String url,
    String id,
    ) {
  ui.platformViewRegistry.registerViewFactory(
    id,
        (int viewId) => html.IFrameElement()..src = url,
  );
  return HtmlElementView(viewType: id);
}

```

</details>

<details>
<summary> stable, master flutter doctor -v </summary>

```

[✓] Flutter (Channel stable, 2.10.4, on macOS 12.2.1 21D62 darwin-x64, locale
    en-GB)
    • Flutter version 2.10.4 at /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (3 days ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

[✓] Flutter (Channel master, 2.13.0-0.0.pre.497, on macOS 12.2.1 21D62
    darwin-x64, locale en-GB)
    • Flutter version 2.13.0-0.0.pre.497 at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a8c09a74a9 (2 hours ago), 2022-04-11 23:44:08 -0400
    • Engine revision f0a2da911b
    • Dart version 2.18.0 (build 2.18.0-10.0.dev)
    • DevTools version 2.12.2
    
[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.



```

</details>

**Comment by ditman** [comment] 2022-04-21 19:48
I suspect this has to do with either the usage of the keys, OR calling `registerViewFactory` for the same ID multiple times (that would explode in a slightly different way, I think). I'll investigate this in case it's a bug of the renderer.

Quick question for @darshankawar and @durduman: what --web-renderer are you using? auto? html? canvaskit? (that might help explain the differences in errors you're seeing)

**Comment by darshankawar** [comment] 2022-04-22 04:57
> Quick question for @darshankawar and @durduman: what --web-renderer are you using? auto? html? canvaskit?

I used both renderers and got same error log as shared https://github.com/flutter/flutter/issues/101580#issuecomment-1094649383

**Comment by durduman** [comment] 2022-04-22 06:37
@ditman , I did try out an implementation where the 'registerViewFactory' got called once ("per each Widget", not at every build/state update) but I got the same result.
Also, not using keys does resolve this behavior but then the state of the internal object inside the iframe is lost (scroll position/video playback location/... ).

I may have miss implemented/used these items so if you reach any conclusion it would be great to better understand what causes this.

**Comment by ditman** [comment] 2022-04-27 00:12
Taking a look right now!

**Comment by ditman** [comment] 2022-04-27 00:46
I can see the error that @durduman reported, when running with --web-renderer auto (canvaskit).

@durduman can you confirm that `flutter run -d chrome --web-renderer html` works on your end? (I did some modifications to your app, but nothing significant yet)

**Comment by ditman** [comment] 2022-04-27 02:44
I think that the root cause of this problem is that on `submitFrame`, when [computing the `diffViewList`](https://github.com/flutter/engine/blob/main/lib/web_ui/lib/src/engine/canvaskit/embedded_views.dart#L976) between the current frame (`[0, 1]`) and the next  (`[1, 0]`), the algorithm decides that it needs to "remove `0`" and "add `0`".

That is a problem, because an embedded_view **cannot be removed if it's going to be added again in the same frame**. The correct "solution" for the diff above would be to "add `0`" (and let the browser figure out that it actually needs to "move" the view for us, so flutter doesn't have to remove it manually).

I've prepared a fix for this family of special cases, but I'm not sure it is the best. I'll publish a PR shortly.

**Comment by ditman** [comment] 2022-04-27 03:28
(Copied triage labels from earlier issue that I deduplicated into this one)

**Comment by durduman** [comment] 2022-04-27 07:27
> @durduman can you confirm that `flutter run -d chrome --web-renderer html` works on your end? (I did some modifications to your app, but nothing significant yet)

<details><summary>I confirm it works.</summary>
$ flutter run -d chrome --web-renderer html
Launching lib/main.dart on Chrome in debug mode...
Waiting for connection from debug service on Chrome...             42.7s
This app is linked to the debug service: ws://127.0.0.1:49947/bHXLYw00mFc=/ws
Debug service listening on ws://127.0.0.1:49947/bHXLYw00mFc=/ws

💪 Running with sound null safety 💪

🔥  To hot restart changes while running, press "r" or "R".
For a more detailed help message, press "h". To quit, press "q".

An Observatory debugger and profiler on Chrome is available at: http://127.0.0.1:49947/bHXLYw00mFc=
running for host
</details>

**Closed** 2022-04-27 18:09 UTC
Labels: severe: regression, severe: crash, engine, waiting for PR to land (fixed), platform-web, e: web_canvaskit, has reproducible steps, P3, found in release: 2.6, found in release: 2.8, found in release: 2.10, found in release: 2.13

**Comment by ditman** [comment] 2022-04-27 23:22
The fix for this issue is now available on the master channel of flutter!

**Comment by durduman** [comment] 2022-04-28 06:34
Tested on master on my end as well and I confirm it is resolved. 
Thanks you, much appreciated!

**Comment by ditman** [comment] 2022-04-28 19:02
@durduman thanks again for reporting the issue! Keep them coming!
