### ISSUE TITLE
Can't find the 'Advance Namer App' in "Your first Flutter app" in DartPad

### ISSUE THREAD

**Issue by pooransuthar** [flutter/flutter#133313] opened 2023-08-25 07:35 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

https://dartpad.dev/e7076b40fb17a0fa899f9f7a154a02e8

Provided link for Advance version on Learn Flutter

### Expected results

When I clicked the link to open the Advanced version of the Namer app which is the example app for "Your first Flutter app", it opens up the DartPad but the code there is for printing 1,2,3,4,5. I need the Advance version code for the Namer app. Thanks!

### Actual results

There is no code for Advance version

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by danagbemava-nc** [comment] 2023-08-25 09:05
Closing this as a duplicate of https://github.com/flutter/flutter/issues/131300. 

See https://github.com/flutter/flutter/issues/131300#issuecomment-1651199357 for the correct link

**Closed by danagbemava-nc** 2023-08-25 09:05 UTC
Labels: in triage
