### ISSUE TITLE
Some widgets not painted when scrolled on screen

### ISSUE THREAD

**Issue by spkersten** [flutter/flutter#50927] opened 2020-02-17 15:19 UTC
Unfortunately, I haven't been able to create a simple reproduction scenario; it seems to only occur once a certain level of complexity is exceeded. I will describe the issue as best as I can. 

We have a vertically scrolling CustomScrollView with a persistent header at the top and as its first child a (SliverToBoxAdapter with a) horizontally scrolling CustomScrollView containing a SliverGrid. The grid contains cards with some decorations, Opacity, ClipRRect, some layout widgets and an image (all nested). 

The issues happens when:
- The first row of the SliverGrid is scrolled of the screen
- A number of modals are opened (just one suffices on an iPhone 6s+ [release build] or iPhone 11 [debug build], on Simulator more other widgets have to be shown) and closed again
- Now, if the first row of the SliverGrid is scrolled on screen again, everything contained by the ClipRRect's is not painted. Scrolling a card either horizontally or vertically off screen and on screen again, will cause it to be rendered correctly again.

It seems that both the Opacity and ClipRRect are needed to reproduce the issue. Also, when the child of the ClipRRect is simple (just some text) the issue doesn't appear. 

On devices, it reproduces every time. On Simulator it is harder to reproduce.

```
[✓] Flutter (Channel unknown, v1.12.13+hotfix.7, on Mac OS X 10.14.5 18F132, locale en-NL)
    • Flutter version 1.12.13+hotfix.7 at .../flutter
    • Framework revision 9f5ff2306b (3 weeks ago), 2020-01-26 22:38:26 -0800
    • Engine revision a67792536c
    • Dart version 2.7.0
```

**Comment by goderbauer** [comment] 2020-02-19 23:06
Does this also reproduce on master?

**Comment by iapicca** [comment] 2020-03-20 11:36
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.

**Comment by spkersten** [comment] 2020-03-20 11:43
@iapicca What additional information do you need? Any kind of logs?

**Comment by rizumita** [comment] 2020-05-04 20:19
@spkersten 
@iapicca 

Maybe I met the same problem. My code is the following.

```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: ListView.builder(
            itemCount: 100,
            itemBuilder: (BuildContext context, int index) {
              return Opacity(
                opacity: 0.5,
                child: ToggleButtons(
                  isSelected: [true, false],
                  children: [Text('Yes'), Text('No')],
                  onPressed: (_) => null,
                ),
              );
            },
          ),
        ),
      ),
    );
  }
}
```

Some list item widgets aren't painted running this code on iOS and Android simulators.

**Comment by iapicca** [comment] 2020-05-06 11:00
Hi @rizumita 
thank you for the code sample

[screenshot](https://user-images.githubusercontent.com/45637986/81169677-e607d100-8fa1-11ea-8121-b7c7f81cfeeb.png)

```console
[✓] Flutter (Channel master, 1.18.0-11.0.pre.6, on Mac OS X 10.15.4 19E287, locale en-EE)
    • Flutter version 1.18.0-11.0.pre.6 at /Users/nevercode/development/flutter_master
    • Framework revision 8568eda15b (12 hours ago), 2020-05-05 16:10:41 -0700
    • Engine revision 33d2367950
    • Dart version 2.9.0 (build 2.9.0-5.0.dev 9c94f08410)


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/nevercode/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.9.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.1

[✓] Connected device (3 available)
    • iPhone 8   • D5F70F31-B488-4454-9539-320B5551D92A • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)
    • Web Server • web-server                           • web-javascript • Flutter Tools
    • Chrome     • chrome                               • web-javascript • Google Chrome 81.0.4044.129

• No issues found!
```

**Comment by spkersten** [comment] 2020-06-02 13:42
I've now also seen the issue in a macOS app.

**Comment by pedromassangocode** [comment] 2021-01-13 10:49
Hi @spkersten 
I cannot reproduce the issue on latest stable channel.

![gif](https://user-images.githubusercontent.com/67424416/104442247-17a35400-5595-11eb-9c1c-1c9785523265.gif)

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 1.22.5, on Mac OS X 10.15.7 19H2 darwin-x64, locale en)
    • Flutter version 1.22.5 at /Users/pedromassango/Code/flutter_stable
    • Framework revision 7891006299 (5 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.9.3

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin installed
    • Dart plugin version 203.6912

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (1 available)
    • iPhone 12 Pro Max (mobile) • ECCF5C4A-8BEC-411D-B23E-85A836C3847E • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-1 (simulator)

! Doctor found issues in 1 category.
```

</details>

Closing this as probably fixed. If you still facing this issue, please write in the comments bellow and I will reopen it.
Thank you

**Comment by spkersten** [comment] 2021-02-23 10:04
The issue is still present on 1.22.6

**Comment by spkersten** [comment] 2021-02-23 10:30
The issue is still present with version 1.22.6

It seems to happen when slowly scrolling to the start of a scroll view. When scrolling towards the end, or scrolling fast, it looks fine.

![blank-cards-bug](https://user-images.githubusercontent.com/4456832/108831423-65ff3600-75ca-11eb-9143-5f6d95e33f03.gif)

```
[✓] Flutter (Channel unknown, 1.22.6, on macOS 11.2 20D64 darwin-x64, locale en-NL)
    • Flutter version 1.22.6 at ...
    • Framework revision 9b2d32b605 (5 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5
```

**Comment by pedromassangocode** [comment] 2021-02-25 10:26
Hi @spkersten 
Looks like you are using a invalid Flutter channel, can you please use any of the valid Flutter channel (beta, master, stable, dev) and if the issue persists, can you please provide a minimal reproducible code sample?
Thank you

**Comment by pedromassangocode** [comment] 2021-04-07 12:53
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2021-04-07 12:53 UTC
Labels: P4, customer: solaris, engine, f: scrolling, found in release: 1.18, framework, has reproducible steps, severe: rendering, waiting for customer response
