### ISSUE TITLE
iOS numeric keyboard - add done button

### ISSUE THREAD

**Issue by mehtahardikr** [flutter/flutter#82694] opened 2021-05-17 13:05 UTC
## Use case

Right now there is no done button for ios numeric keyboard

## Proposal

Please add that done button to ios numeric keyboard as android has already this.

**Comment by darshankawar** [comment] 2021-05-17 13:32
@mehtahardikr 
Please check [this](https://github.com/flutter/flutter/issues/12220#issuecomment-331610011) and [this](https://github.com/flutter/flutter/issues/12220#issuecomment-336309263) comment for reference as why this doesn't seem to be feasible to add from Flutter side.

Also, if you still want to have that button, you may use this community plugin which offers the same feature https://pub.dev/packages/keyboard_actions

**Comment by mehtahardikr** [comment] 2021-05-18 11:07
@darshankawar : understand, but if that 3rd party plugin can do that, why can't addede by framework or add option to textField for that ? isn't it still possible ?

**Comment by darshankawar** [comment] 2021-05-18 13:18
@mehtahardikr 
plugins are created using custom widgets for the features that are not available in the framework, but in this case, it's not upto Flutter to decide, because Apple itself doesn't have the feature. If you take a look at any iPhone and look to input in any field, you won't see `done` button, so until it doesn't come from Apple or iOS framework, Flutter won't be able to add that in the framework and hence that may be reasoning to close the original issue.

With that said, I am afraid to close this issue as working as intended.  Your best bet is to use the referred plugin.
If you disagree, you may comment in the original issue and based on upvotes, you never know, the issue could be reopened, although very unlikely.

**Closed by darshankawar** 2021-05-18 13:18 UTC
Labels: in triage
