### ISSUE TITLE
Flutter Windows Host Engine has been failing since 2020-12-14 with false negatives

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#77659] opened 2021-03-09 00:48 UTC
Flutter Windows Host Engine has been failing since 2020-12-14 with false positives(the build is green even though it has failures). This can be affecting uploading windows web engine artifacts:

* This is the first try build failing with the error: https://ci.chromium.org/p/flutter/builders/try/Windows%20Host%20Engine/17186
* This is the first failing build prod build: https://ci.chromium.org/p/flutter/builders/prod/Windows%20Host%20Engine/7985

**Comment by godofredoc** [comment] 2021-03-09 00:49
\cc @christopherfujino @cbracken

**Comment by godofredoc** [comment] 2021-03-09 17:56
This is not a P0 it is only affecting sending the pubsub notification after the build completion moving to P1

**Comment by godofredoc** [comment] 2021-03-09 17:57
\cc @yusufm seems like gcloud recipe module does not work on windows.

**Comment by yusufm** [comment] 2021-03-15 19:04
The gcloud api setup step https://fuchsia.googlesource.com/infra/recipes.git/+/refs/heads/master/recipe_modules/gcloud/api.py#22 , is failing. This would prevent the pubsub notification to be generated since it relies on gcloud api. 

The notification step is set to fail silently, since its not yet in use. @renyou can confirm otherwise. Therefore, moving this to P2 since it should be affecting any other systems, while the issue is investigated.

**Comment by yusufm** [comment] 2021-03-18 17:37
CL #503309 has been submitted and this step is passing now.

**Closed by yusufm** 2021-03-18 17:37 UTC
Labels: P2, passed first triage, platform-windows
