### ISSUE TITLE
Images with transparency render differently on iOS and Android

### ISSUE THREAD

**Issue by alardizabal** [flutter/flutter#11169] opened 2017-07-12 16:05 UTC
Images with transparency appear lighter on iOS than on Android. There is no additional opacity being added in our code. We've been able to reproduce this difference on several iPhone, Samsung, Motorola, Nexus and Pixel devices.

**Comment by collinjackson** [comment] 2017-07-12 16:34
This looks to me like an iOS issue. A transparent PNG with 50% transparency renders darker than a full-opacity version of the same image that has been wrapped in `Opacity(opacity: 0.5)`.

<img width="79" alt="screen shot 2017-07-12 at 9 31 48 am" src="https://user-images.githubusercontent.com/394889/28128592-1193e586-66e5-11e7-9883-8f6e9e24a949.png">

On Android they look the same:

![flutter_01](https://user-images.githubusercontent.com/394889/28128580-05ed137e-66e5-11e7-81c5-25bc64f7c114.png)

**Comment by collinjackson** [comment] 2017-07-12 16:36
@chinmaygarde might know

**Comment by collinjackson** [comment] 2017-07-12 16:40
Marking as a blocker because Posse needs this for launch; we might be able to work around it temporarily using `Opacity` though

**Comment by eseidelGoogle** [comment] 2017-07-12 16:46
FYI @cbracken

**Comment by collinjackson** [comment] 2017-07-12 19:10
@chinmaygarde wanted me to check an actual device. The behavior on iOS 7 Plus is the same as on the simulator (I can reproduce the issue)

![image](https://user-images.githubusercontent.com/394889/28135443-13666b84-66fb-11e7-88e3-7975069b1a7e.png)

**Comment by chinmaygarde** [comment] 2017-07-12 19:12
@brianosman: Could this be an artifact of the color correctness patches landed in https://github.com/flutter/engine/pull/3826?

**Comment by brianosman** [comment] 2017-07-12 20:17
Yes, it seems like it could be. My first guess was that the decoder isn't doing a correct (linear) premultiply, which would be true if we were using the platform codecs. But I don't see how that would happen - Flutter should be going through Skia's codecs in all cases (I think).

Also, from looking at the images, even the bottom image in the iOS screenshots looks significantly darker (in the bottom area of the logo) than the Android images. I'm guessing that isn't expected?

**Comment by collinjackson** [comment] 2017-07-13 19:22
@brianosman we would like to roll back flutter/engine#3826 if we can confirm that it caused this regression. as far as I know the sRGB support is not being relied on by anyone yet and you could re-land your engine change it once the above test case is fixed.

Please let me know within the next day if you have any concerns about this plan.

**Comment by brianosman** [comment] 2017-07-13 19:34
That sounds okay. I'm nervous about the blending behavior ping-ponging for people again, but it's probably worth it just to know for sure that it's responsible.

**Comment by eseidelGoogle** [comment] 2017-07-13 19:58
FYI @tvolkert as you'd see this when rolling Flutter into Google.

**Closed** 2017-07-13 21:22 UTC
Labels: customer blocker, customer: posse (eap), dependency: skia

**Comment by collinjackson** [comment] 2017-07-13 21:25
@brianosman I landed the revert as discussed, here is a screenshot of the test case before the revert (left) and after the revert (right) on iOS.

![image](https://user-images.githubusercontent.com/394889/28188369-c77b177e-67d6-11e7-8ca4-918016b91b42.png)

Since this is no longer a customer blocker, I closed this bug and opened a new bug #11210 for re-landing sRGB support once it's ready.
