### ISSUE TITLE
macOS CI Network timeouts "transport: Error while dialing: dial tcp $IP: i/o timeout"

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#155110] opened 2024-09-12 18:25 UTC
Update by @christopherfujino:

LUCI's data centers are having an incident, this is being tracked internally.

---

## Known instances

|BuildBucket link|Bot|Zone|
|--|--|--|
|https://ci.chromium.org/ui/p/flutter/builders/try/Mac%20Engine%20Drone/1152399/infra|https://chromium-swarm.appspot.com/bot?id=mac-49-h526|ZONE_IAD97|
|https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20Production%20Engine%20Drone/455899/infra|https://chromium-swarm.appspot.com/bot?id=mac-718-h526|ZONE_IAD97|
|https://ci.chromium.org/ui/p/flutter/builders/try/Mac%20Engine%20Drone/1155976/infra|https://chromium-swarm.appspot.com/bot?id=mac-781-h526|ZONE_IAD97|
|https://ci.chromium.org/ui/p/flutter/builders/try/Mac%20Engine%20Drone/1156363/infra|https://chromium-swarm.appspot.com/bot?id=mac-47-h526|ZONE_IAD97|
|https://ci.chromium.org/ui/p/flutter/builders/try/Mac%20customer_testing/83275/infra|https://chromium-swarm.appspot.com/bot?id=mac-756-h526|ZONE_IAD97|
|https://ci.chromium.org/ui/p/flutter/builders/prod/Mac_arm64%20tool_host_cross_arch_tests/9934/infra|https://chromium-swarm.appspot.com/bot?id=mac-704-h526|ZONE_IAD97|

## error
```
[E2024-09-12T10:41:38.940154-07:00 768 0 client.go:170] failed to create casclient: rpc error: code = Unavailable desc = rpc error: code = Unavailable desc = retry budget exhausted (6 attempts): connection error: desc = "transport: Error while dialing: dial tcp 172.253.115.95:443: i/o timeout", authentication type (identity) used="external authentication token (credentials helper)"
[E2024-09-12T10:41:38.940612-07:00 768 0 annotate.go:273] original error: rpc error: code = Unavailable desc = rpc error: code = Unavailable desc = retry budget exhausted (6 attempts): connection error: desc = "transport: Error while dialing: dial tcp 172.253.115.95:443: i/o timeout", authentication type (identity) used="external authentication token (credentials helper)"

goroutine 1:
#0 go.chromium.org/luci/client/casclient/client.go:171 - casclient.NewLegacy()
  reason: failed to create client

#1 cas/main.go:64 - main.(*authFlags).NewRBEClient()
#2 go.chromium.org/luci/client/cmd/cas/casimpl/download.go:338 - casimpl.(*downloadRun).doDownload()
#3 go.chromium.org/luci/client/cmd/cas/casimpl/download.go:574 - casimpl.(*downloadRun).Run()
#4 github.com/maruel/subcommands@v1.1.1/subcommands.go:395 - subcommands.Run()
#5 cas/main.go:95 - main.main()
#6 runtime/proc.go:271 - runtime.main()
#7 runtime/asm_amd64.s:1695 - runtime.goexit()
cas: failed to create client: rpc error: code = Unavailable desc = rpc error: code = Unavailable desc = retry budget exhausted (6 attempts): connection error: desc = "transport: Error while dialing: dial tcp 172.253.115.95:443: i/o timeout", authentication type (identity) used="external authentication token (credentials helper)"
```

**Comment by gaaclarke** [comment] 2024-09-13 16:40
Here it is happening again today to block the engine tree: https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20mac_unopt/3335/overview

Here it is happening again today to block the skia roll:
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8736902515426767713/+/u/test:_Impeller-golden_for_host_release/stdout

**Comment by gaaclarke** [comment] 2024-09-13 16:52
These may be different issues since I've linked to 2 instances where git operations have problems and another instance where skia gold is having issues.  I suspect they are the same root problem though based on the errors:

### git error excerpt
```
transport: Error while dialing: dial tcp [172.253.115.95:443](http://172.253.115.95:443/): i/o timeout
```
### skia gold error excerpt
```
dial tcp [35.201.76.220:443](http://35.201.76.220:443/): i/o timeout.
```

**Comment by christopherfujino** [comment] 2024-09-13 16:56
To help keep things organized, let's list all known instances in the original post.

**Comment by christopherfujino** [comment] 2024-09-13 17:09
There is an ongoing LUCI outage that is currently being investigated.

**Comment by gaaclarke** [comment] 2024-09-13 17:10
@christopherfujino is it helpful if I post a few more instances of this failure, or do you have enough info?

**Comment by christopherfujino** [comment] 2024-09-13 17:13
> @christopherfujino is it helpful if I post a few more instances of this failure, or do you have enough info?

Yeah, the more data the better, I've shared this bug internally. If you just drop links in the comments, I don't mind digging through the sub-links and populating the table in the OP.

**Comment by gaaclarke** [comment] 2024-09-13 17:27
Here are some more instances:
- https://ci.chromium.org/ui/p/flutter/builders/try/Mac%20Engine%20Drone/1156363/overview
- https://ci.chromium.org/ui/p/flutter/builders/try/Mac%20customer_testing/83275/overview (This one is slightly different and may not be related, `fatal: unable to access 'https://github.com/flutter/flutter/': Failed to connect to github.com port 443: Operation timed out`)

**Comment by christopherfujino** [comment] 2024-09-13 17:36
> https://ci.chromium.org/ui/p/flutter/builders/try/Mac%20customer_testing/83275/overview (This one is slightly different and may not be related, fatal: unable to access 'https://github.com/flutter/flutter/': Failed to connect to github.com port 443: Operation timed out)

I suspect it's the same though, the CAS client error was also a timeout trying to connect to 443

**Comment by christopherfujino** [comment] 2024-09-13 18:10
There is internal request to expand the NAT pool which should end the outage while the root cause is still being investigated.

**Comment by christopherfujino** [comment] 2024-09-13 21:44
LUCI is reporting the rate of failures has drastically dropped and then after that the NAT pool was extended, so I'm going to optimistically close this. Please re-open with links if you see a build failure with a TCP timeout that occurred AFTER Sep 13 14:44 pacific time.

**Closed by christopherfujino** 2024-09-13 21:44 UTC
Labels: team-infra, P0, c: flake
