### ISSUE TITLE
App with shared_preferences not running

### ISSUE THREAD

**Issue by TobiasKuba** [flutter/flutter#158039] opened 2024-11-02 01:59 UTC
### Steps to reproduce

1. create project in vs code
2. add shared preferences plugin
3. app working only on chrome emulator but not on android devices

### Actual results

So when Im using shared_preferences my app is working only on chrome. When launching it in android device emulator it wont even launch. Tried it also in new clean project as well as "flutter clean" and "flutter pub get". Also its just with this plugin with other its working normally.

Im just installing the shared_preferences with:
`flutter pub add shared_preferences`

Also tried this:
`flutter pub upgrade --major-versions`

As i said in chrome everything works okay but on the android device emulator will not start.

Im getting this error:

`FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':shared_preferences_android:compileDebugJavaWithJavac'.
> Could not resolve all files for configuration ':shared_preferences_android:androidJdkImage'.
   > Failed to transform core-for-system-modules.jar to match attributes {artifactType=_internal_android_jdk_image, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.
      > Execution failed for JdkImageTransform: C:\Users\tobik\AppData\Local\Android\sdk\platforms\android-34\core-for-system-modules.jar.
         > Error while executing process C:\Program Files\Android\Android Studio\jbr\bin\jlink.exe with arguments {--module-path C:\Users\tobik\.gradle\caches\transforms-3\4a46fc89ed5f9adfe3afebf74eb8bfeb\transformed\output\temp\jmod --add-modules java.base --output C:\Users\tobik\.gradle\caches\transforms-3\4a46fc89ed5f9adfe3afebf74eb8bfeb\transformed\output\jdkImage --disable-plugin system-modules}

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 47s
Error: Gradle task assembleDebug failed with exit code 1`

### Flutter Doctor output

[√] Flutter (Channel stable, 3.24.4, on Microsoft Windows [Version 10.0.22631.4317], locale cs-CZ)
    • Flutter version 3.24.4 on channel stable at C:\Users\tobik\dev\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 603104015d (8 days ago), 2024-10-24 08:01:25 -0700
    • Engine revision db49896cf2
    • Dart version 3.5.4
    • DevTools version 2.37.3

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\tobik\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 21.0.3+-12282718-b509.11)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 2024.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.3+-12282718-b509.11)

[√] VS Code (version 1.95.1)
    • VS Code at C:\Users\tobik\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.100.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 130.0.6723.92
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 130.0.2849.56

[√] Network resources
    • All expected network resources are available.

• No issues found!

**Comment by manthri-mohan-sai** [comment] 2024-11-03 14:04
Duplicate of https://github.com/flutter/flutter/issues/157911

**Comment by badriyahaddad** [comment] 2024-11-03 20:04
have you tried:
flutter clean
flutter pub get ?

**Closed** 2024-11-04 06:52 UTC
Labels: in triage
