### ISSUE TITLE
BottomAppBar elevation (color) changed

### ISSUE THREAD

**Issue by appcapsergen** [flutter/flutter#129823] opened 2023-06-30 07:55 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Use a BottomAppBar with elevation in Flutter 3.7.10. I tried 70 and 20.
2. Use a BottomAppBar with elevation in Flutter 3.10.5. I tried 70 and 20.
3. See the difference.

### Expected results

_The size of the widgets is not part of the problem, this is because the screenshots are made on two different devices._
![IMG_0055 (1)](https://github.com/flutter/flutter/assets/94898347/23ea50f8-57ae-43e1-bdc7-9ef4a8b3919f)

### Actual results

_The size of the widgets is not part of the problem, this is because the screenshots are made on two different devices._
![IMG_0055](https://github.com/flutter/flutter/assets/94898347/4fc597e8-59f4-4fbc-b04d-797d32111ba7)

### Code sample

<details><summary>Code sample</summary>

```dart
    return Container(
      color: Colors.white,
      height: 64.0 + MediaQuery.of(context).padding.bottom,
      child: BottomAppBar(
        elevation: elevation, // I tried 70.0 and 20.0
        child: Row(
          mainAxisAlignment: MainAxisAlignment.spaceAround,
          children: [
            // items here, I used 5 icons
          ]
        ),
      ),
    );
```

</details>

### Screenshots or Video

Screenshots / Video demonstration

See Expected/Actual results.

### Logs

Logs

N/A

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.3, on macOS 13.4.1 22F82 darwin-arm64, locale en-NL)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.73.1)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by dam-ease** [comment] 2023-06-30 11:20
Hi @appcapsergen. Thanks for filing this issue. I'm unable to reproduce this on the latest flutter versions. Tested with `3.7.12` and `3.10.5` and `3.12.0-13.0.pre.19` and observed same color as in screenshot. Can you confirm this as well on the latest versions??

<details><summary>Code Sample</summary>
<p>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      title: 'application',
      home: HomePage(),
    );
  }
}

class HomePage extends StatelessWidget {
  const HomePage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Container(),
      bottomNavigationBar: Container(
        color: Colors.white,
        height: 64.0 + MediaQuery.of(context).padding.bottom,
        child: BottomAppBar(
          elevation: 70, // I tried 70.0 and 20.0
          child: Row(
              mainAxisAlignment: MainAxisAlignment.spaceAround,
              children: const [
                // items here, I used 5 icons
                Icon(Icons.home),
                Icon(Icons.home), Icon(Icons.home),
                Icon(Icons.home),
                Icon(Icons.home)
              ]),
        ),
      ),
    );
  }
}

``` 

</p>
</details> 

<details><summary>Screenshot</summary>
<p>


</p>
</details> 

<details><summary>flutter doctor -v</summary>
<p>

```
[✓] Flutter (Channel stable, 3.10.5, on macOS 13.4 22F66 darwin-arm64, locale
    en-NG)
    • Flutter version 3.10.5 on channel stable at /Users/dammya/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (2 weeks ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version
    32.1.0-rc1)
    • Android SDK at /Users/dammya/Library/Android/sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • ANDROID_HOME = /Users/dammya/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2022.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.79.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (4 available)
    • iPhone 11 (mobile) • 6D1A287C-0B7C-4532-9EED-51027BBF306A • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • iPhone 14 (mobile) • 5FE8DE93-0F4C-45BA-8BED-BC9CD69B35D1 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)    • macos                                • darwin-arm64
      • macOS 13.4 22F66 darwin-arm64
    • Chrome (web)       • chrome                               • web-javascript
      • Google Chrome 114.0.5735.198

[✓] Network resources
    • All expected network resources are available.

• No issues found!
``` 
```
[✓] Flutter (Channel stable, 3.7.12, on macOS 13.4 22F66 darwin-arm64, locale en-NG)
    • Flutter version 3.7.12 on channel stable at /Users/dammya/fvm/versions/3.7.12
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4d9e56e694 (2 months ago), 2023-04-17 21:47:46 -0400
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/dammya/Library/Android/sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • ANDROID_HOME = /Users/dammya/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2022.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.79.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (4 available)
    • iPhone 11 (mobile) • 6D1A287C-0B7C-4532-9EED-51027BBF306A • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • iPhone 14 (mobile) • 5FE8DE93-0F4C-45BA-8BED-BC9CD69B35D1 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)    • macos                                • darwin-arm64   • macOS 13.4 22F66 darwin-arm64
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 114.0.5735.198

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
``` 

```
[✓] Flutter (Channel master, 3.12.0-13.0.pre.19, on macOS 13.4 22F66 darwin-arm64, locale en-NG)
    • Flutter version 3.12.0-13.0.pre.19 on channel master at /Users/dammya/fvm/versions/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7b8595629b (5 hours ago), 2023-06-30 02:29:24 -0400
    • Engine revision 099a70ebbc
    • Dart version 3.1.0 (build 3.1.0-262.0.dev)
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/dammya/Library/Android/sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • ANDROID_HOME = /Users/dammya/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2022.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.79.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (4 available)
    • iPhone 11 (mobile) • 6D1A287C-0B7C-4532-9EED-51027BBF306A • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • iPhone 14 (mobile) • 5FE8DE93-0F4C-45BA-8BED-BC9CD69B35D1 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)    • macos                                • darwin-arm64   • macOS 13.4 22F66 darwin-arm64
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 114.0.5735.198

[✓] Network resources
    • All expected network resources are available.

• No issues found!

``` 

</p>
</details>

**Comment by appcapsergen** [comment] 2023-06-30 14:01
Hi @dam-ease 
I've tested it multiple times now. The elevation is there, it's just very faint and barely visible, especially compared to how it was before.
I tested it more thoroughly with the versions now as well. The issue started when I upgraded from 3.7.10 to 3.10.0.

**Comment by appcapsergen** [comment] 2023-06-30 14:27
Here's the same problem in a very simplified version of the BottomAppBar.

The following is in Flutter 3.7.10 with elevation 70.0.
![2732D35D-2C37-402D-8A0A-A4A0446B8DF0_1_102_o](https://github.com/flutter/flutter/assets/94898347/2ee13d05-ad7f-4aaf-957c-843829f1ed5a)

The following is in Flutter 3.10.0 with elevation 70.0 and shadowColor Colors.black (otherwise it's not visible at all). As you can see, there's a less clear elevation.
![21298F09-6358-46AD-B50A-B23CED64E0EE_1_102_o](https://github.com/flutter/flutter/assets/94898347/9a3bdf4f-e54c-4811-8ffc-39c12bc1f200)

**Comment by dam-ease** [comment] 2023-06-30 15:19
Hi @appcapsergen. Thanks for confirming. I think I can see a slight difference (almost not noticeable on my end though). From the Screenshot below (iPhone 14 Pro is the behaviour on version `3.10.5` and iPhone 14 is the behaviour on version `3.7.10`).

<details><summary>Screenshot</summary>
<p>

<img width="725" alt="Screenshot 2023-06-30 at 16 09 43" src="https://github.com/flutter/flutter/assets/53122008/5f5e6c82-eb68-438a-a552-b48af105829d">


</p>
</details>

**Comment by TahaTesser** [comment] 2023-09-26 08:26
Hi @appcapsergen 
`BottomAppBar` when elevated casts a shadow but this shadow color is transparent by default in Material 3.
Material 3 uses surface tint color to indicate elevation. This was updated in https://github.com/flutter/flutter/pull/121406 to match Material 3 specs.

In your screenshot, you're not using surface tint color for elevation. You can provide a color in the  [BottomAppBar.shadowColor](https://api.flutter.dev/flutter/material/BottomAppBar/shadowColor.html) parameter to indicate elevation.

You can override the default transparent shadow color when needed like this:
```dart
        child: BottomAppBar(
          shadowColor: Theme.of(context).colorScheme.shadow,
          elevation: 70, // I tried 70.0 and 20.0
```

Closing as this is documented in https://api.flutter.dev/flutter/material/BottomAppBar/shadowColor.html.

**Closed by TahaTesser** 2023-09-26 08:26 UTC
Labels: framework, f: material design, has reproducible steps, P2, found in release: 3.10, found in release: 3.12, team-design, triaged-design, multiteam-retriage-candidate

**Comment by appcapsergen** [comment] 2023-09-26 09:21
> Hi @appcapsergen `BottomAppBar` when elevated casts a shadow but this shadow color is transparent by default in Material 3. Material 3 uses surface tint color to indicate elevation. This was updated in #121406 to match Material 3 specs.

Still if I put `Colors.black` as the shadowColor with whatever elevation, the elevation only gets a slight tint compared to what it was before (it would just turn black).

**Comment by TahaTesser** [comment] 2023-09-26 10:06
> > Hi @appcapsergen `BottomAppBar` when elevated casts a shadow but this shadow color is transparent by default in Material 3. Material 3 uses surface tint color to indicate elevation. This was updated in #121406 to match Material 3 specs.
> 
> @TahaTesser Still if I put `Colors.black` as the shadowColor with whatever elevation, the elevation only gets a slight tint compared to what it was before (it would just turn black).


I tried color sampling before the change (without custom shadow color) and after the change (with custom shadow color), the picked color was exactly the same.

![Screenshot 2023-09-26 at 13 03 44](https://github.com/flutter/flutter/assets/48603081/4794178d-f8a6-44c2-8c21-41f9fd94bd73)

### Code sample

<details>
<summary>expand to view the code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(useMaterial3: true),
      home: const HomePage(),
    );
  }
}

class HomePage extends StatelessWidget {
  const HomePage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Container(),
      bottomNavigationBar: Container(
        color: Colors.white,
        height: 64.0 + MediaQuery.of(context).padding.bottom,
        child: const BottomAppBar(
          shadowColor: Color(0xFF000000),
          surfaceTintColor: Colors.transparent,
          elevation: 70, // I tried 70.0 and 20.0
          child:
              Row(mainAxisAlignment: MainAxisAlignment.spaceAround, children: [
            // items here, I used 5 icons
            Icon(Icons.home),
            Icon(Icons.home), Icon(Icons.home),
            Icon(Icons.home),
            Icon(Icons.home)
          ]),
        ),
      ),
    );
  }
}
```

</details>
