### ISSUE TITLE
iOS: Firestore transaction fails with 'Transaction failed all retries'

### ISSUE THREAD

**Issue by dmjones** [flutter/flutter#18747] opened 2018-06-23 05:39 UTC
## Steps to Reproduce

Trying to run a very simple transaction, similar to the example in the cloud_firestore documentation (using v0.7.3):

```dart
    DocumentReference usernameDocRef =
        Firestore.instance.collection(_USERNAMES).document(username);

    await Firestore.instance.runTransaction((transaction) async {
      var snapshot = await transaction.get(usernameDocRef);
      if (!snapshot.exists) {
        await transaction.set(usernameDocRef, {
          _UsernamesKey.userid: _user.id,
        });
      }
    });
```

## Logs

```
[+9301 ms] [VERBOSE-2:dart_error.cc(16)] Unhandled exception:
[        ] PlatformException(9, Transaction failed all retries., null)
[        ] #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:547:7)
[        ] #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:279:18)
[        ] <asynchronous suspension>
[        ] #2      Firestore.runTransaction (file:///Users/duncan/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.7.3/lib/src/firestore.dart:115:10)
[        ] <asynchronous suspension>
[        ] #3      FirebaseDataService.updateUsername (package:project/service/firebase_data_service.dart:308:30)
[        ] <asynchronous suspension>
[        ] #4      UsernamePresenter.usernameChosen (package: project/registration/username_presenter.dart:17:39)
[        ] <asynchronous suspension>
[        ] #5      _UsernameSelectionView.build.<anonymous closure> (package: project/registration/username_view.dart:64:43)
[        ] #6      OnePressButtonState._pressed (package: project/shared.dart:171:14)
[        ] #7      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:494:14)
[        ] #8      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:549:30)
[        ] #9      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
[        ] #10     TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:161:9)
[        ] #11     TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:94:7)
[        ] #12     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:315:9)
[        ] #13     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:73:12)
[        ] #14     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:11)
[        ] #15     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:143:19)
[        ] #16     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:121:22)
[        ] #17     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:101:7)
[        ] #18     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:64:7)
[        ] #19     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:48:7)
[        ] #20     _invoke1 (dart:ui/hooks.dart:134:13)
[        ] #21     _dispatchPointerDataPacket (dart:ui/hooks.dart:91:5)
```

```
```

```
flutter doctor -v
[✓] Flutter (Channel dev, v0.5.5, on Mac OS X 10.13.4 17E202, locale en-GB)
    • Flutter version 0.5.5 at /Users/duncan/git/flutter
    • Framework revision 020e0ef55c (8 days ago), 2018-06-14 13:17:08 -0700
    • Engine revision c3976b3c71
    • Dart version 2.0.0-dev.61.0.flutter-c95617b19c

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/duncan/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.2

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 25.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 25.0.2
    • Dart plugin version 181.4668.60

[✓] Connected devices (1 available)
    • duncan_iphone • - • ios • iOS 11.4

• No issues found!
```

**Comment by Olb** [comment] 2018-06-30 15:05
I have this problem only on iOS device or simulator but on Android everything works as expected.

**Comment by dmjones** [comment] 2018-07-28 21:37
Any updates on this? This is still failing for me, on the dev channel with all plugins updated.

Lack of transaction support is a bit of a problem!

**Comment by hi-sanchoman** [comment] 2018-08-16 16:27
Hi!

> A transaction consists of any number of get() operations **followed by** any number of **write operations** such as set(), update(), or delete(). In the case of a concurrent edit, Cloud Firestore runs the entire transaction again. For example, if a transaction reads documents and another client modifies any of those documents, Cloud Firestore retries the transaction. This feature ensures that the transaction runs on up-to-date and consistent data.

Please check that you did not forget to update one of documents.

**Comment by dmjones** [comment] 2018-08-26 13:51
@hi-sanchoman My code example is shown in my first comment. As you can see, I update the document after I read it.

**Comment by dmjones** [comment] 2018-09-20 19:28
@1and1get2 @CosmicPangolin : can I suggest you both add a thumbs-up on my opening post? I think the Flutter team use that to help triage how many people are affected.

**Comment by CosmicPangolin** [comment] 2018-09-20 19:32
Gotcha homie! :)

**Comment by 1and1get2** [comment] 2018-09-20 21:44
I have resolved the issue for me, it was caused because the map data contains unsupported type, in my case a enum. 

I thought it'd be automatically toString() ed.

Anyway, the error message was pretty useless and needed some work

**Comment by pulyaevskiy** [comment] 2018-09-20 23:19
Hm, just got the same error, however I'm sure it was working just a few days ago.

What changed on my end is that I'm trying to create users with `signInAnonymously` now... not if if it's relevant though.

**Comment by pulyaevskiy** [comment] 2018-09-20 23:32
@dmjones 

OK, so I tried putting my code inside transaction handler into a try-catch and simply printing out exceptions. Got something different:

```
flutter: ERROR: PlatformException(DOCUMENT_NOT_FOUND, Document not found., null)
```

You might be getting similar issue since you're checking for `exists` in your example.

It doesn't make sense why it throws in this case though :/

**Comment by pulyaevskiy** [comment] 2018-09-20 23:39
Aha, here we go: 

```dart
      } else if (snapshot != nil) {
        result(@{
          @"path" : snapshot.reference.path,
          @"data" : snapshot.exists ? snapshot.data : [NSNull null]
        });
      } else {
        result([FlutterError errorWithCode:@"DOCUMENT_NOT_FOUND"
                                   message:@"Document not found."
                                   details:nil]);
      }
```

https://github.com/flutter/plugins/blob/1aef7d92e9e77e929ad767320e3f96cbb26efacc/packages/cloud_firestore/ios/Classes/CloudFirestorePlugin.m#L325-L334

@kroikie was there any particular reason to handle non-existing documents this way in transactions? Seems like it should simply return `null` snapshot instead.

**Comment by pulyaevskiy** [comment] 2018-09-20 23:45
And here is the workaround:

```dart
      await firestore.runTransaction((tx) async {
        try {
          await tx.get(ref);
        } catch (error) {
          // Workaround for transaction handler which throws DOCUMENT_NOT_FOUND exception.
          if (error is PlatformException &&
              error.code == 'DOCUMENT_NOT_FOUND') {
            await tx.set(ref, data);
          } else
            rethrow;
        }
      });
```

**Comment by PeterHo249** [comment] 2018-11-13 10:32
@Olb Did you fix that error? I've got the same problem with you.

**Comment by pulyaevskiy** [comment] 2018-11-13 14:49
@PeterHo249 see workaround in my comment right above yours. I also explained the root cause above as well.

**Comment by knitterb** [comment] 2018-12-28 22:48
I've also run into this issue any @pulyaevskiy 's solution works!

**Comment by nemoryoliver** [comment] 2019-02-04 02:19
I hope the plugin devs will fix this issue. I am getting the same error running on iOS Simulator. PlatformException(9, Transaction failed all retries., null)

**Comment by collinjackson** [comment] 2019-02-13 15:25
Thanks for looking into this, @pulyaevskiy. It seems like flutter/plugins#1206 (based on your suggestion) is an adequate fix for this issue.

**Closed** 2019-02-21 16:07 UTC
Labels: p: cloud_firestore, p: firebase, p: first party, plugin, severe: crash, waiting for PR to land (fixed), ⌺‬ platform-ios

**Comment by kroikie** [comment] 2019-10-13 19:05
@dmjones

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/783. Any further collaboration will be done there.
