### ISSUE TITLE
[connectivity] warning: ConnectivityBroadcastReceiver.java uses or overrides a deprecated API.

### ISSUE THREAD

**Issue by jesseframework** [flutter/flutter#59633] opened 2020-06-17 02:24 UTC
When I compile I see these notes on the console screen

Note: Recompile with -Xlint:unchecked for details.
Note: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\connectivity-0.4.5+3\android\src\main\java\io\flutter\plugins\connectivity\ConnectivityBroadcastReceiver.java uses or overrides a deprecated API.

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^0.17.3+1
  http: ^0.12.0+4
  chopper: ^3.0.0
  easy_localization:

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  rflutter_alert: ^1.0.3  
  sqflite: any
  shared_preferences: ^0.5.6+3
  flutter_bloc: ^3.2.0
  meta: ^1.1.6
  equatable: ^1.0.0
  moor: ^2.4.2
  moor_ffi: ^0.4.0
  path_provider:
  path:
  firebase_core: ^0.4.0+9
  firebase_analytics: ^5.0.2
  firebase_auth: ^0.14.0+5
  firebase_messaging: ^6.0.13
  overlay_support: ^1.0.3 
  bot_toast: ^3.0.0
  encrypt: ^4.0.2
  cryptor: ^0.1.6
  connectivity: ^0.4.8+6
  data_connection_checker: ^0.3.4  
  keyboard_avoider: ^0.1.2
  quiver: ^2.1.3
  logging: ^0.11.4
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  chopper_generator: ^3.0.0
  moor_generator: ^2.4.0
  build_runner: ^1.3.1
  intl_translation: ^0.17.1

## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by TahaTesser** [comment] 2020-06-17 10:05
duplicate of https://github.com/flutter/flutter/issues/44580

**Closed by TahaTesser** 2020-06-17 10:05 UTC
