### ISSUE TITLE
widget on top of blur backdrop filter will not show on iOS if there is a  google map widget on the page

### ISSUE THREAD

**Issue by kmIndonesia** [flutter/flutter#83684] opened 2021-06-01 02:32 UTC
## Steps to Reproduce

If I run the code below in iOS

```

class EventCreatorPage extends StatelessWidget {
  static const routeName = "/event-creator-page";

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("creator"),
      ),
      body: SingleChildScrollView(
        child: Column(
          children: [
            SizedBox(
              height: 200,
              child: Stack(
                fit: StackFit.expand,
                children: [
                  Image.asset(ImageAssetsName.kumpulMuslimFullLogo, fit: BoxFit.cover),
                  ClipRRect(
                    // Clip it cleanly.
                    child: BackdropFilter(
                      filter: ImageFilter.blur(sigmaX: 10, sigmaY: 10),
                      child: Container(
                        color: Colors.grey.withOpacity(0.1),
                        alignment: Alignment.center,
                        child: Text('CHOCOLATE'),
                      ),
                    ),
                  ),
                ],
              ),
            ),
            _GoogleMapLocation(),
          ],
        ),
      ),
    );
  }
}

class _GoogleMapLocation extends StatefulWidget {
  @override
  __GoogleMapLocationState createState() => __GoogleMapLocationState();
}

class __GoogleMapLocationState extends State<_GoogleMapLocation> with WidgetsBindingObserver {
  GoogleMapController? googleMapController;

  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance?.addObserver(this);
  }

  @override
  void dispose() {
    WidgetsBinding.instance?.removeObserver(this);
    super.dispose();
  }

  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    if (state == AppLifecycleState.resumed) {
      googleMapController?.setMapStyle("[]");
    }
  }

  @override
  Widget build(BuildContext context) {
    final marker = Marker(
      markerId: MarkerId("Some ID"),
      position: LatLng(40.689247, -74.044502),
      infoWindow: InfoWindow(title: "Liberty"),
    );

    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        SizedBox(
          width: double.infinity,
          height: 200,
          child: GoogleMap(
            onTap: (newCoordinate) {},
            onMapCreated: (mapController) => onMapCreated(mapController, marker),
            mapType: MapType.normal,
            myLocationButtonEnabled: false,
            initialCameraPosition: CameraPosition(
              target: LatLng(40.689247, -74.044502),
              zoom: 15.0,
            ),
            markers: {marker},
          ),
        ),
        SizedBox(height: 8),
        TextButton(
          onPressed: () {},
          child: Text("To Location", style: TextStyle(fontWeight: FontWeight.w700)),
          style: TextButton.styleFrom(
            padding: EdgeInsets.zero,
            minimumSize: Size(50, 30),
            alignment: Alignment.centerLeft,
          ),
        ),
        Divider(),
      ],
    );
  }

  void onMapCreated(GoogleMapController mapController, Marker marker) {
    googleMapController = mapController;
    googleMapController?.setMapStyle("[]");
    googleMapController?.showMarkerInfoWindow(marker.markerId);
  }
}

```

I expect I will have blurred  image with a text above it like this: https://i.stack.imgur.com/VcWoc.png
but I only get the blurred image without the text like this https://i.stack.imgur.com/wlf1c.png

it seems this is occurred only on iOS after I update to Flutter 2.2.1. and this only occurred if there is a google map on my page.
if I delete the google map widget, then the widget above the backdrop filter will appear again

I use Flutter 2.2.1
also this package google_maps_flutter: ^2.0.5

I have no issue in Flutter doctor

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.1, on macOS 11.2.1 20D74 darwin-x64, locale en-ID)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] VS Code (version 1.56.2)
[✓] Connected device (4 available)

• No issues found!

**Comment by TahaTesser** [comment] 2021-06-01 11:03
Hi @kmIndonesia 
I see there's an open issue addressing the case you described.
Please follow up on that issue, Closing as duplicate of https://github.com/flutter/flutter/issues/80766
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-06-01 11:03 UTC
Labels: in triage
