### ISSUE TITLE
Web: Horizontal scroll blocking vertical scrolling on trackpad/touchpad

### ISSUE THREAD

**Issue by andreasgan** [flutter/flutter#125101] opened 2023-04-19 07:49 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Possibly a regression of this?: https://github.com/flutter/flutter/issues/70046.

1. Create an outer vertical ListView that has horizontal ListViews as children.
2. Place two fingers on a trackpad/touchpad (im using a macbook touchpad here)
3. Try to drag vertically, but with a slight angle instead of perfectly straight.

### Expected results

The vertical listview keeps scrolling vertically. Since the fingers are dragging with a slight angle, the horizontal listview should probably also scroll a little bit at the same time.

### Actual results

The vertical listview stops scrolling when the cursor is over a horizontal listview, and the horizontal scrolling takes over.
It feels like they are competing.

### Code sample

<details><summary>Code sample</summary>

```dart

import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: ListView.builder(
          itemBuilder: (context, index) => Container(
            color: Colors.white,
            height: 210,
            child: Padding(
              padding: const EdgeInsets.symmetric(vertical: 30),
              child: ListView.builder(
                scrollDirection: Axis.horizontal,
                itemBuilder: (context, index) => Box(),
              ),
            ),
          ),
        ),
      ),
    );
  }
}

class Box extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
        height: 150,
        width: 150,
        color: Colors.black,
        padding: EdgeInsets.all(10),
        child: Container(
          color: Colors.grey,
        ));
  }
}

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

https://user-images.githubusercontent.com/727125/233004032-87b9752b-79aa-4019-b404-1d0e055edc73.mov

</details>

### Logs

<details><summary>Logs</summary>

```console
Launching lib/main.dart on Chrome in debug mode...
main.dart:1
This app is linked to the debug service: ws://127.0.0.1:59965/oeAyusjUjYc=/ws
Debug service listening on ws://127.0.0.1:59965/oeAyusjUjYc=/ws
💪 Running with sound null safety 💪
Connecting to VM Service at ws://127.0.0.1:59965/oeAyusjUjYc=/ws
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.7.10, on macOS 12.6.1 21G217 darwin-arm64, locale en-NO)
    • Flutter version 3.7.10 on channel stable at /Users/andreasgangso/dev/tools/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4b12645012 (2 weeks ago), 2023-04-03 17:46:48 -0700
    • Engine revision ec975089ac
    • Dart version 2.19.6
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/andreasgangso/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.12.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.77.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.62.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.6.1 21G217 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 112.0.5615.121

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by danagbemava-nc** [comment] 2023-04-19 08:40
Hi @andreasgan, I believe this shares a root cause as https://github.com/flutter/flutter/issues/113416. 

Can you look at the issue linked above to see if it's related to your issue? 

> It feels like they are competing.

I believe they are. See https://docs.flutter.dev/development/ui/advanced/gestures#gesture-disambiguation

**Comment by andreasgan** [comment] 2023-04-19 12:06
It might be the same root cause. I also don't know if it makes sense to treat touchscreen drags and touchpad dragging the same way.

**Comment by andreasgan** [comment] 2023-04-19 12:06
To add some use case context here, this creates a very annoying user experience for media webapps with a lot of horizontal sections like ours: https://beta.app.bcc.media/.

**Comment by danagbemava-nc** [comment] 2023-04-20 07:18
I think the fix might have been applied for only macOS. I see different behaviours when I scroll on mac compared to web. 

On macOS, when I scroll at an angle, it doesn't get very far, but it still registers as a vertical scroll. However, on the web, when I scroll, at an angle, a vertical scroll is initially registered but when it gets into the horizontal list, the scroll is captured by the horizontal list. See the recordings below. 

| macOS | web |
| -- | -- |
| <video src="https://user-images.githubusercontent.com/88313112/233287729-33b67655-113f-44eb-99b2-7bb4843546ea.mov" /> | <video src="https://user-images.githubusercontent.com/88313112/233287738-01527917-f2de-4075-b47f-46dde19a0324.mov" /> |

@andreasgan, just to confirm, this matches what you're experiencing, correct?

**Comment by andreasgan** [comment] 2023-04-20 08:20
@danagbemava-nc Yes, true. I created [this codepen](https://codepen.io/andreasgan/pen/zYmoqXp) which has a similar setup in pure html and js to check the normal behaviour, and the mac build is behaving correctly.

I hadn't noticed before, but flicking like you are doing in the video makes the bug very obvious. In my video i am doing a long manual drag.

**Comment by danagbemava-nc** [comment] 2023-04-20 13:15
Thanks for the confirmation. 

The issue is reproducible using the code sample provided above. 

### Steps to reproduce
- Run the code sample on the web
- Place the mouse cursor above the boxes(in the white spaces)
- Fling vertically at an angle
- Observe that when the mouse pointer gets into the boxes, the scroll is captured by the horizontal listview, and the listview scrolls. 

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.7.12, on macOS 13.3.1 22E261 darwin-arm64, locale en-GB)
    • Flutter version 3.7.12 on channel stable at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4d9e56e694 (2 days ago), 2023-04-17 21:47:46 -0400
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/222.4459.24.2221.9862592/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode-14.3.0.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/221.6008.13.2211.9619390/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] Android Studio (version 2022.2)
    • Android Studio at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/222.4459.24.2221.9862592/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1)
    • IntelliJ at /Users/nexus/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 73.0.4
    • Dart plugin version 231.8109.91

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1)
    • IntelliJ at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/231.8109.175/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.77.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.62.0

[✓] Connected device (4 available)
    • M2007J20CG (mobile) • adb-5dd3be00-17AYzd._adb-tls-connect._tcp. • android-arm64  • Android 12 (API 31)
    • Nexus (mobile)      • 00008020-001875E83A38002E                  • ios            • iOS 16.4.1 20E252
    • macOS (desktop)     • macos                                      • darwin-arm64   • macOS 13.3.1 22E261 darwin-arm64
    • Chrome (web)        • chrome                                     • web-javascript • Google Chrome 112.0.5615.137

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

```
[!] Flutter (Channel master, 3.10.0-10.0.pre.17, on macOS 13.3.1 22E261 darwin-arm64, locale en-GB)
    • Flutter version 3.10.0-10.0.pre.17 on channel master at /Users/nexus/dev/sdks/flutters
    ! Warning: `flutter` on your path resolves to /Users/nexus/dev/sdks/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/nexus/dev/sdks/flutters. Consider adding /Users/nexus/dev/sdks/flutters/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/nexus/dev/sdks/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/nexus/dev/sdks/flutters. Consider adding /Users/nexus/dev/sdks/flutters/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b04efe4ecf (8 hours ago), 2023-04-20 01:31:24 -0400
    • Engine revision 2db85cbe6a
    • Dart version 3.1.0 (build 3.1.0-22.0.dev)
    • DevTools version 2.23.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/222.4459.24.2221.9862592/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode-14.3.0.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/221.6008.13.2211.9619390/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] Android Studio (version 2022.2)
    • Android Studio at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/222.4459.24.2221.9862592/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1)
    • IntelliJ at /Users/nexus/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 73.0.4
    • Dart plugin version 231.8109.91

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1)
    • IntelliJ at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/231.8109.175/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.77.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.62.0

[✓] Connected device (4 available)
    • M2007J20CG (mobile) • adb-5dd3be00-17AYzd._adb-tls-connect._tcp. • android-arm64  • Android 12 (API 31)
    • Nexus (mobile)      • 00008020-001875E83A38002E                  • ios            • iOS 16.4.1 20E252
    • macOS (desktop)     • macos                                      • darwin-arm64   • macOS 13.3.1 22E261 darwin-arm64
    • Chrome (web)        • chrome                                     • web-javascript • Google Chrome 112.0.5615.137

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

```
</details>

**Comment by Piinks** [comment] 2023-04-21 20:07
This is expected behavior. When nesting gestures, they cannot both win the gesture arena at the same time, so only one (vertical or horizontal) will claim the drag. We currently have a 2D scroll view in progress, I have added this to that project for tracking. 

I am going to close this since it is expected and we have other issues covering the 2D diagonal scrolling feature.

**Closed by Piinks** 2023-04-21 20:07 UTC
Labels: framework, f: scrolling, platform-web, has reproducible steps, found in release: 3.7, found in release: 3.10

**Comment by andreasgan** [comment] 2023-04-21 21:06
@Piinks I'm worried my wording in the original issue has confused you to believe this issue is about diagonal scrolling.
I've removed (strikethrough) this from the OP now because it was a wrong expectation: "Since the fingers are dragging with a slight angle, the horizontal listview should probably also scroll a little bit at the same time."

The real issue here is that it's not locking the axis like it does on macos and like a normal html-based website.
See [Daniels reply](https://github.com/flutter/flutter/issues/125101#issuecomment-1515833328) above.

**Comment by Piinks** [comment] 2023-04-21 21:39
Hey @andreasgan thanks for checking! I believe all of this will be resolved by the 2D scrolling project, including locking axes appropriately.
