### ISSUE TITLE
ios obscure text not working after upgrade

### ISSUE THREAD

**Issue by rgusso** [flutter/flutter#55238] opened 2020-04-20 21:45 UTC
After upgrading flutter today, `TextFormField` `obscureText:true` stopped working
keyboard doesn't show up and if I type, nothing shows.

Iphone 6, iOS 12.4.6, running on real device!

<details>
  <summary>flutter doctor -v</summary>

[✓] Flutter (Channel master, v1.18.0-6.0.pre.99, on Mac OS X 10.15.4 19E287, locale pt-BR)
•  Flutter version 1.18.0-6.0.pre.99 at /Users/rodrigo/development/flutter
• Framework revision b7e30cfc26 (37 minutes ago), 2020-04-20 14:02:49 -0700
• Engine revision ae311ca4da
• Dart version 2.9.0 (build 2.9.0-1.0.dev 4859de9f09)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/rodrigo/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.42.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[✓] Connected device (1 available)
    • iPhone de Rodrigo Gusso • f8d4b92bd70b04fdc17c296c296b7ae1a74be267 • ios • iOS 12.4.6

• No issues found!
</details>

**Comment by vste23** [comment] 2020-04-20 22:09
same issue after upgrade, can confirm I am on master channel

**Comment by vste23** [comment] 2020-04-20 22:12
Once tapping on TextFormField with `obscureText:true` - keyboard not showing up. If setting obscureText from state, several super quick toggles (lets say "eye" icon) brings this temporary to life but overall behaves very weird

**Comment by mohaawadi** [comment] 2020-04-20 22:40
me too

**Comment by marcianobandeira** [comment] 2020-04-20 22:47
> Once tapping on TextFormField with `obscureText:true` - keyboard not showing up. If setting obscureText from state, several super quick toggles (lets say "eye" icon) brings this temporary to life but overall behaves very weird

same problem here, aleatory alterning obscureText from model, sometimes, do work

**Comment by mohaawadi** [comment] 2020-04-20 22:56
I just switched to beta channel, and just works!

**Comment by LongCatIsLooong** [comment] 2020-04-20 23:19
Duplicate of https://github.com/flutter/flutter/issues/55081. It's fixed on master.

**Closed** 2020-04-21 05:49 UTC
