### ISSUE TITLE
Flutter back button pressed, not hide the keyboard on Android 10

### ISSUE THREAD

**Issue by abedputra** [flutter/flutter#66791] opened 2020-09-28 00:11 UTC
Thanks for the wonderful Framework.

I want to report, there are obstacles that I experienced on Android 10. Usually, if we press the back button, the keyboard will hide, but as in this video, when repeatedly pressing the back button, the keyboard is not hidden. But in the test on Android 7, it worked fine, when I pressed the hidden keyboard back button.

This is the video
![issue](https://user-images.githubusercontent.com/11581453/94379280-d6ac3e80-0161-11eb-9410-9a0c25ed23d7.gif)

My code
```
TextFormField(
  validator: (e) {
    var message;
    if (e.isEmpty) {
      message = emailEmpty;
    }
    return message;
  },
  onSaved: (e) => email = e,
  decoration: InputDecoration(
    prefixIcon: Icon(
      Icons.email,
      color: Color(0xFF003d64),
    ),
    labelText: emailInput,
  ),
),
```

`flutter doctor -v`
```
[✓] Flutter (Channel beta, 1.22.0-12.1.pre, on Mac OS X 10.15.6 19G2021, locale en-ID)
    • Flutter version 1.22.0-12.1.pre at / Users / abedputra / Development / flutter
    • Framework revision 8b3760638a (12 days ago), 2020-09-15 17:47:13 -0700
    • Engine revision 4654fc6cf6
    Dart version 2.10.0 (build 2.10.0-110.3.beta)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at / Users / abedputra / Library / Android / sdk
    • Android-R platform, build-tools 29.0.3
    • Java binary at: / Applications / Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at / Applications / Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at / Applications / Android Studio.app/Contents
    • Flutter plugin version 50.0.2-dev.1
    • Dart plugin version 193.7547
    Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (3 available)
    • K88 (mobile) 6acdf2f6 android-arm64 Android 7.1.1 (API 25)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web) • chrome • web-javascript • Google Chrome 85.0.4183.121
```

Thank you

**Comment by kunit1** [comment] 2020-09-28 00:20
Just to add, this also happens on Android 9 on a Samsung Galaxy S10.

**Comment by zhangshexin** [comment] 2020-09-28 02:55
waiting

**Comment by Srj-Love** [comment] 2020-09-28 10:09
Is any solution available?

**Comment by darshankawar** [comment] 2020-09-28 12:17
Hi @abedputra 
I am unable to replicate this issue on latest stable (1.20.4). Tested on Samsung Galaxy S10+.

[67991.mp4.zip](https://github.com/flutter/flutter/files/5292108/67991.mp4.zip)


Can you switch to latest master and try again to see if it works for you ?

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 1.20.4, on Mac OS X 10.15.4 19E2269, locale en-IN)
    • Flutter version 1.20.4 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision fba99f6cf9 (13 days ago), 2020-09-14 15:32:52 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (1 available)
    • SM A260G (mobile) • 5200763ebcfa861f • android-arm • Android 8.1.0 (API
      27)

• No issues found!
```


Thanks.

**Comment by abedputra** [comment] 2020-09-28 15:39
Hi @darshankawar 
Thank you for the information, I use Xiaomi Note 10, and test on Samsung S8, and same problem.

Let me change to channel stable, and test it, I will let you know.

Thanks

**Comment by kunit1** [comment] 2020-09-28 15:42
@darshankawar This seems like a regression. On stable it's working but on Master it's broken. Somewhere between Stable and Master it broke. Does it work for you on Master?

**Comment by Srj-Love** [comment] 2020-09-29 04:51
Hey, I just  switched to Stable channel from Beta channel, and not getting this issue. It's seems working in stable.

**Comment by darshankawar** [comment] 2020-09-29 05:55
@abedputra also tested on latest master and saw no issues using Samsung S10+ device. The back button works properly.

[66791.mp4.zip](https://github.com/flutter/flutter/files/5296709/66791.mp4.zip)

<details>
<summary>flutter doctor</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 1.22.0-10.0.pre.405, on Mac OS X 10.15.4 19E2269 x86_64, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.49.1)
[✓] Connected device (3 available)

• No issues found!

```

</details>

**Comment by abedputra** [comment] 2020-09-29 06:47
@darshankawar Thank you
I have tested when changing the channel from beta to stable, working fine. It seems working in stable channel, not beta channel.

Thanks

**Comment by abedputra** [comment] 2020-09-29 06:47
@darshankawar Thank you
I have tested when changing the channel from beta to stable, working fine. It seems working in stable channel, not beta channel.

Thanks

**Comment by darshankawar** [comment] 2020-10-01 07:01
@abedputra It seems to be an issue specific to beta. Are you still experiencing the issue on latest beta ?
If so, can you provide `flutter doctor -v` and devices on which the issue occurs ?
I tried on Android 8.1.0 and Android 10 (S10+) but didn't see the keyboard issue.

**Comment by abedputra** [comment] 2020-10-01 07:14
Hi @darshankawar,

this is the `flutter doctor -v` before I change the channel to stable.

```
[✓] Flutter (Channel beta, 1.22.0-12.1.pre, on Mac OS X 10.15.6 19G2021, locale en-ID)
    • Flutter version 1.22.0-12.1.pre at / Users / abedputra / Development / flutter
    • Framework revision 8b3760638a (12 days ago), 2020-09-15 17:47:13 -0700
    • Engine revision 4654fc6cf6
    Dart version 2.10.0 (build 2.10.0-110.3.beta)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at / Users / abedputra / Library / Android / sdk
    • Android-R platform, build-tools 29.0.3
    • Java binary at: / Applications / Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at / Applications / Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at / Applications / Android Studio.app/Contents
    • Flutter plugin version 50.0.2-dev.1
    • Dart plugin version 193.7547
    Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (3 available)
    • K88 (mobile) 6acdf2f6 android-arm64 Android 7.1.1 (API 25)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web) • chrome • web-javascript • Google Chrome 85.0.4183.121
```

Thanks

**Comment by darshankawar** [comment] 2020-10-01 12:27
@abedputra Does it occur if you upgrade to latest beta (1.22.0-12.3.pre) ?
Thanks.

**Comment by abedputra** [comment] 2020-10-01 14:52
Hi @darshankawar, I am not in the Beta channel, right now, I use the Stable channel.

I will let you know after I changing to Beta again.

Thanks

**Comment by abedputra** [comment] 2020-10-04 04:03
Hi @darshankawar,
I've upgraded to `1.22.0 • channel beta` and the issue is fixed.

This is `flutter doctor -v`
```
[✓] Flutter (Channel beta, 1.22.0, on Mac OS X 10.15.6 19G2021, locale en-ID)
    • Flutter version 1.22.0 at /Users/abedputra/Development/flutter
    • Framework revision d408d302e2 (4 days ago), 2020-09-29 11:49:17 -0700
    • Engine revision 5babba6c4d
    • Dart version 2.10.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/abedputra/Library/Android/sdk
    • Platform android-R, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 50.0.2-dev.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (2 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 85.0.4183.121

• No issues found!
```

Thanks

**Comment by Vardiak** [comment] 2020-10-04 16:39
This issue seems specific to samsung keyboard

**Comment by abedputra** [comment] 2020-10-04 23:38
@Vardiak could you give us info `flutter doctor -v`?

**Comment by darshankawar** [comment] 2020-10-05 07:47
@abedputra Thanks for confirming.
I am going ahead and closing this issue as resolved.
@Vardiak If you are facing a similar issue, please open a new issue by providing all required details.
Thanks.

**Closed by darshankawar** 2020-10-05 07:47 UTC
Labels: in triage

**Comment by Vardiak** [comment] 2020-10-05 08:50
> @Vardiak could you give us info `flutter doctor -v`?

I do not have access to a Samsung phone for debugging, but I have had several comments from users and I have been able to confirm the issue from a friend's phone. The issue disappears when he switches to Google keyboard.

**Comment by fareezMaple** [comment] 2020-10-10 01:48
Not only in Android 10, but also happen in Pie. Yes I'm using Samsung keyboard, but that weird behaviour is not happening before upgrading to flutter 1.22 (beta)

**Comment by raj-s-jain** [comment] 2021-01-29 15:45
This issue still exists in the current stable channel. Flutter - Channel stable, 1.22.6 for Samsung keyboard

**Comment by omidraha** [comment] 2021-03-01 17:09
Same issue.

```
flutter doctor --verbose
[✓] Flutter (Channel stable, 1.22.6, on Linux, locale en_US.UTF-8)
    • Flutter version 1.22.6 at */sdk/flutter
    • Framework revision 9b2d32b605 (5 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at */sdk/android/
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = */sdk/android/
    • Java binary at: */jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.
```
