### ISSUE TITLE
[web] Page goes blank when refreshing and hot restart 

### ISSUE THREAD

**Issue by PooperPig** [flutter/flutter#90928] opened 2021-09-29 05:24 UTC
NB The below is running v 2.6.0-12.0...pre.134 which is the latest right now.
The same issue happens on V2.5.1 - I upgraded as the having-to-mouse-over-when-refreshing issue sounded like it could be related.

I removed flutter, uninstalled Android Studio, and re-installed both before creating the test project.

This is on Windows 10 - a colleague running a similar system set up took the zipped version of the project and ran it once or twice without being able to reproduce the issue (on 2.5.1)

This is causing an issue specifically as I have a web app that requires a URL to be replaced (as there doesn't seem to be a way to do so other than typing into the browser) and also requires a cookie to be manually added while testing - so the freezing happens frequently. I mention this for context - for me it's not just an edge case!

## Steps to Reproduce

Create a new package
```
flutter create --template=package faq_lib
cd faq_lib
flutter create example
```
add the following to example/pubspec.yaml
```
  faq_lib:
    path: ../
```
Change faq_lib.dart to be a custom component
```
library flutter_pkg;

import 'package:flutter/material.dart';

class CustomButton extends StatelessWidget {
  var onPressed;
  final Widget? child;
  var style;
  CustomButton(
      {Key? key, @required this.onPressed, @required this.child, this.style})
      : super(key: key);

  @override
  Widget build(BuildContext context) {
    return TextButton(
        onPressed: onPressed,
        style: TextButton.styleFrom(
          padding: const EdgeInsets.all(16.0),
          primary: Colors.white,
          backgroundColor: Colors.blue,
          elevation: 9.0,
          textStyle: const TextStyle(
            fontSize: 20,
          ),
        ),
        child: child!);
  }
}

```
Add the customBotton to main.dart

```
            CustomButton(
                onPressed: _incrementCounter, child: const Text("Click me")),
          ],

```
`flutter run `
select either chrome or edge

The app will run. 

It does not freeze every time - so it is difficult to tie down the exact reproducibility, however different combinations of the following have caused this to freeze...

1. Clicked the Custom Button several times, then refreshed the browser
2. Pressed 'r' in the console to reload (for 2.5 mouse over the screen to force the refresh) then refresh the browser
3. Press 'r' in the console several times (in 2.6) then refresh the browser.

Sometimes any or all of these freeze.
Sometimes none of these freeze.

When I say 'freeze' - the page is completely blank (the loading bars disappear) and the tab does nothing - trying to close the browser sometimes does nothing (although closing the tab does close the browser). Sometimes closing the browser does work, though. The browser is using little or no CPU/ Clicking refresh again sits doing 'nothing' with the browser loading animation (in the browser tab) showing continually loading.

<details>
  <summary>Logs</summary>

```
flutter run --verbose
[  +69 ms] executing: [C:\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +409 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] 0167d99fc6b9cde6cfd8296fbdfc4d2f56e6422e
[        ] executing: [C:\flutter/] git tag --points-at 0167d99fc6b9cde6cfd8296fbdfc4d2f56e6422e
[  +28 ms] Exit code 0 from: git tag --points-at 0167d99fc6b9cde6cfd8296fbdfc4d2f56e6422e
[   +1 ms] executing: [C:\flutter/] git describe --match *.*.* --long --tags 0167d99fc6b9cde6cfd8296fbdfc4d2f56e6422e
[  +46 ms] Exit code 0 from: git describe --match *.*.* --long --tags 0167d99fc6b9cde6cfd8296fbdfc4d2f56e6422e
[        ] 2.6.0-11.0.pre-134-g0167d99fc6
[   +8 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +17 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [C:\flutter/] git ls-remote --get-url origin     
[  +15 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +87 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref HEAD
[  +16 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[  +56 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.       
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.    
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.     
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.     
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.    
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.    
[  +68 ms] executing: C:\Users\Maxy.ABA12620\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +51 ms] List of devices attached
[   +5 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.  
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +72 ms] Multiple devices found:
[  +31 ms] Chrome (web) • chrome • web-javascript • Google Chrome 94.0.4606.61
[   +1 ms] Edge (web)   • edge   • web-javascript • Microsoft Edge 94.0.992.31
[   +1 ms] [1]: Chrome (chrome)
[        ] [2]: Edge (edge)
[   +2 ms] Please choose one (To quit, press "q/Q")
[        ] : 
[+1109 ms] 1
[  +15 ms] Skipping pub get: version match.
[ +113 ms] Generating C:\Projects\faq\faq_lib\example\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +84 ms] Launching lib\main.dart on Chrome in debug mode...
[ +113 ms] Updating assets
[  +74 ms] Waiting for connection from debug service on Chrome...
[  +89 ms] <- reset
[   +7 ms] C:\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev C:\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root
C:\flutter\bin\cache\flutter_web_sdk/ --incremental --target=dartdevc --debugger-module-names --experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true
--output-dill C:\Users\MAXY~1.ABA\AppData\Local\Temp\flutter_tools.6249c40e\flutter_tool.bed78b61\app.dill --libraries-spec
file:///C:/flutter/bin/cache/flutter_web_sdk/libraries.json --packages C:\Projects\faq\faq_lib\example\.dart_tool\package_config.json -Ddart.vm.profile=false
-Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-root C:\Users\MAXY~1.ABA\AppData\Local\Temp\flutter_tools.6249c40e\flutter_tools.3d8eaf5a   
--filesystem-scheme org-dartlang-app --initialize-from-dill build\b1b715402d823b7fd5c2b68d2edcb2ce.cache.dill.track.dill --platform
file:///C:/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk_sound.dill --sound-null-safety
[  +11 ms] <- compile org-dartlang-app:/web_entrypoint.dart
[+14467 ms] Waiting for connection from debug service on Chrome... (completed in 14.6s)
[   +1 ms] Synced 27.9MB.
[        ] <- accept
[        ] Caching compiled dill
[+1480 ms] [CHROME]:[18584:16140:0929/151009.003:ERROR:token_service_table.cc(139)] Failed to decrypt token for service
AccountId-E6onwIUBsPEUE9tksCXKFe_IKMYA7mCscOMWNCuDxOg
[   +5 ms] [CHROME]:
[        ] [CHROME]:DevTools listening on ws://127.0.0.1:59581/devtools/browser/c6619a22-cdac-46a0-8b6a-bfe6b0490531
[ +241 ms] DwdsInjector: Received request for entrypoint at http://localhost:64874/main_module.bootstrap.js
[   +4 ms] MetadataProvider: Loading debug metadata...
[  +11 ms] MetadataProvider: Loaded debug metadata (sound null safety)
[   +5 ms] DwdsInjector: Injected debugging metadata for entrypoint at http://localhost:64874/main_module.bootstrap.js
[+2402 ms] ChromeProxyService: Initializing expression compiler for main_module.bootstrap.js with sound null safety: true
[  +67 ms] DevHandler: Debug service listening on ws://127.0.0.1:50514/OnyC_HzuByc=/ws

[  +22 ms] This app is linked to the debug service: ws://127.0.0.1:50514/OnyC_HzuByc=/ws
[  +10 ms] Debug service listening on ws://127.0.0.1:50514/OnyC_HzuByc=/ws
[        ]  Running with sound null safety 
[   +3 ms]   To hot restart changes while running, press "r" or "R".
[        ] For a more detailed help message, press "h". To quit, press "q".
[   +1 ms] An Observatory debugger and profiler on Chrome is available at: http://127.0.0.1:50514/OnyC_HzuByc=
[+1093 ms] DevTools activation throttled until 2021-09-29 21:35:13.186908.
[ +861 ms] The Flutter DevTools debugger and profiler on Chrome is available at: http://127.0.0.1:58142?uri=http://127.0.0.1:50514/OnyC_HzuByc=
[+70429 ms] Performing hot restart...
[   +7 ms] Initializing file store
[  +12 ms] Skipping target: gen_localizations
[   +5 ms] Skipping target: gen_dart_plugin_registrant
[   +2 ms] Skipping target: _composite
[   +2 ms] complete
[  +46 ms] Scanned through 530 files in 45ms
[   +1 ms] Waiting for connection from debug service on Chrome...
[   +1 ms] <- recompile org-dartlang-app:/web_entrypoint.dart cac2951f-9814-4999-bfb6-9420fefbdbfc
[        ] <- cac2951f-9814-4999-bfb6-9420fefbdbfc
[  +15 ms] Waiting for connection from debug service on Chrome... (completed in 16ms)
[        ] Synced 0.0MB.
[        ] <- accept
[   +2 ms] DwdsVmClient: Attempting a hot restart
[   +1 ms] DwdsVmClient: Attempting to disable breakpoints and resume the isolate
[   +8 ms] DwdsVmClient: Successfully disabled breakpoints and resumed the isolate
[        ] DwdsVmClient: Attempting to get execution context ID.
[        ] DwdsVmClient: Got execution context ID.
[        ] DwdsVmClient: Issuing $dartHotRestart request.
[  +42 ms] ChromeProxyService: Initializing expression compiler for main_module.bootstrap.js with sound null safety: true
[  +18 ms] DwdsVmClient: $dartHotRestart request complete.
[        ] DwdsVmClient: Waiting for Isolate Start event.
[   +5 ms] DwdsVmClient: Successful hot restart
[   +3 ms] Performing hot restart... (completed in 180ms)
[   +1 ms] Restarted application in 184ms.
[+2750 ms] DwdsInjector: Received request for entrypoint at http://localhost:64874/main_module.bootstrap.js
[   +1 ms] MetadataProvider: Loading debug metadata...
[   +4 ms] MetadataProvider: Loaded debug metadata (sound null safety)
[   +2 ms] DwdsInjector: Injected debugging metadata for entrypoint at http://localhost:64874/main_module.bootstrap.js
[+1368 ms] ChromeProxyService: Initializing expression compiler for main_module.bootstrap.js with sound null safety: true
```

```
$ flutter analyze
Analyzing example...                                                    
No issues found! (ran in 12.5s)
```

```
$ flutter doctor -v
[√] Flutter (Channel master, 2.6.0-12.0.pre.134, on Microsoft Windows [Version 10.0.19042.1237], locale en-AU)
    • Flutter version 2.6.0-12.0.pre.134 at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 0167d99fc6 (5 hours ago), 2021-09-28 17:23:06 -0700
    • Engine revision bccb3a57eb
    • Dart version 2.15.0 (build 2.15.0-156.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Maxy.ABA12620\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.61.0-insider)
    • VS Code at C:\Users\Maxy.ABA12620\AppData\Local\Programs\Microsoft VS Code Insiders
    • Flutter extension version 3.26.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 94.0.4606.61
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 94.0.992.31

• No issues found!
```

</details>

**Comment by TahaTesser** [comment] 2021-09-29 11:26
Hi @PooperPig 
Thanks for filing the issue

The issue is only reproduces the issue in a package? I tried a regular project with custom button code and tried `r` several times, no freeze or any issue at all 

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.5.1, on Microsoft Windows [Version 10.0.22000.194], locale en-US)
    • Flutter version 2.5.1 at C:\Users\Taha\Code\flutter_stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffb2ecea52 (12 days ago), 2021-09-17 15:26:33 -0400
    • Engine revision b3af521a05
    • Dart version 2.14.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\Taha\Code\android-sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_SDK_ROOT = C:\Users\Taha\Code\android-sdk
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.3)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31702.278
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 2020.3)
    • Android Studio at C:\Users\Taha\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.60.2)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.26.0

[✓] Connected device (4 available)
    • IN2011 (mobile)   • c9d8ee0c • android-arm64  • Android 11 (API 30)
    • Windows (desktop) • windows  • windows-x64    • Microsoft Windows [Version 10.0.22000.194]
    • Chrome (web)      • chrome   • web-javascript • Google Chrome 94.0.4606.61
    • Edge (web)        • edge     • web-javascript • Microsoft Edge 93.0.961.47

• No issues found!
```
	 
</details>

Also please try updating your browser. Since the issue doesn't reproduce on the same project by someone else
Thank you

**Comment by balazsbokanyi** [comment] 2021-09-29 11:41
Hello,

might be related or not related at all, but I came across something similar yesterday. Sometimes the browser window froze, sometimes my app loaded.

I managed to track down the problem to a Chrome auto-update that happened the day before; with Chrome Version 94.0.4606.61, I experienced these issues. After downloading a Chromium (Version 93.0.4539.0) and using it with Flutter web, I have no issues at all.

**Comment by PooperPig** [comment] 2021-09-29 22:47
@TahaTesser I have done more testing.
Brand new project (i.e. just a plain flutter create test) followed by flutter run -d edge
use 'r' to refresh
refresh browser
freezes.

This does NOT happen every time - it sometimes works for several refreshes - but always seems to fail eventually - sometimes the first time. Sometimes if I close the app then run again, it fails straight away (I think always after one hot reload, though)

This (with Edge V94.0.992.31) is reproducible on at least two machines (i.e. mine and a colleagues)

I uninstalled Chrome and installed an older version - deleting all user data etc. - and it seemed to work fine.
I then updated to the latest version of chrome and it seemed to work fine.
Then I logged into chrome with my usual ID - and it stopped working (i.e. the freezing started happening again)
I disabled all extensions, logged out, stopped synching etc. but it continues to freeze.
This is Chrome version 94.0.4606.61 (Official Build) (64-bit).

@balazsbokanyi Thanks - as above downgrading Chrome seemed to work, and I will continue to experiment with earlier versions

**Comment by TahaTesser** [comment] 2021-09-30 08:04
Hi @PooperPig 
I have tried edge instructions for 15-20, the app restarts fine, just with this message
```
[        ] Restarted application in 91ms.
[ +179 ms] Error: Assertion failed:
org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/canvaskit/surface_factory.dart:111:12
                    _cache.contains(surface)
                    is not true
                        at Object.throw_ [as throw] (http://localhost:56506/dart_sdk.js:5061:11)
                        at Object.assertFailed (http://localhost:56506/dart_sdk.js:4986:15)
                        at _engine.SurfaceFactory.new.isLive (http://localhost:56506/dart_sdk.js:139913:51)
                        at _engine.Surface.new.[_contextLostListener] (http://localhost:56506/dart_sdk.js:139641:19)
```

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.5.1, on Microsoft Windows [Version 10.0.22000.194], locale en-US)
    • Flutter version 2.5.1 at C:\Users\Taha\Code\flutter_stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffb2ecea52 (13 days ago), 2021-09-17 15:26:33 -0400
    • Engine revision b3af521a05
    • Dart version 2.14.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\Taha\Code\android-sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_SDK_ROOT = C:\Users\Taha\Code\android-sdk
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.3)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31702.278
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 2020.3)
    • Android Studio at C:\Users\Taha\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.60.2)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.26.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22000.194]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 94.0.4606.61
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 94.0.992.31

• No issues found!
```
	 
</details>

in fact, I have the same Microsoft Edge version too.

**Comment by Jjagg** [comment] 2021-10-02 06:20
I think this is a duplicate of #90822.

**Comment by TahaTesser** [comment] 2021-10-04 12:54
@Jjagg 
Thanks, closing as duplicate

**Closed by TahaTesser** 2021-10-04 12:54 UTC
Labels: tool, platform-web, has reproducible steps, browser: edge, found in release: 2.6
