### ISSUE TITLE
[tool_crash]: _TypeError: type 'String' is not a subtype of type 'bool?' in type cast when bulding for iOS

### ISSUE THREAD

**Issue by daksh-gargas** [flutter/flutter#145740] opened 2024-03-26 06:30 UTC
### Oops; flutter has exited unexpectedly: "type 'String' is not a subtype of type 'bool?' in type cast". 

` flutter build ios --flavor dev -t lib/main_dev.dart`

```
Building com.xxx.dev for device (ios-release)...
Automatically signing iOS for device deployment using specified development team in Xcode project: xxx
Running Xcode build...                                                  
 └─Compiling, linking and signing...                         7.0s
Xcode build done.                                           32.3s
Built /,../build/ios/iphoneos/Runner.app.

Oops; flutter has exited unexpectedly: "type 'String' is not a subtype of type 'bool?' in type cast".
A crash report has been written to /.../flutter_01.log
```

### Expected results

`.ipa` file should be generated

### Actual results

`Oops; flutter has exited unexpectedly: "type 'String' is not a subtype of type 'bool?' in type cast".`

### Code sample

Fails with 
`flutter build ios --flavor dev -t lib/main_dev.dart` or ` flutter build ios`

or
`flutter build ipa --flavor dev -t lib/main_dev.dart --export-method=ad-hoc --build-name=$version_number --build-number=$build_number`

```
$ flutter build ipa -v --flavor dev -t lib/main_dev.dart --export-method=ad-hoc > output.txt
[        ] Oops; flutter has exited unexpectedly: "type 'String' is not a subtype of type 'bool?' in type cast".
[  +26 ms] A crash report has been written to /Users/daksh-gargas/Documents/GitHub/wildr/in-progress-mobile/wildr_flutter/flutter_01.log
```
[output.txt](https://github.com/flutter/flutter/files/14765536/output.txt)

[flutter_01.log](https://github.com/flutter/flutter/files/14765541/flutter_01.log)

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.19.4, on macOS 14.4 23E214 darwin-arm64, locale en-US)
    • Flutter version 3.19.4 on channel stable at /Users/daksh-gargas/.asdf/installs/flutter/3.19.4
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 68bfaea224 (5 days ago), 2024-03-20 15:36:31 -0700
    • Engine revision a5c24f538d
    • Dart version 3.3.2
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/daksh-gargas/dev/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/daksh-gargas/dev/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.15.2

[!] Android Studio (version unknown)
    • Android Studio at /Applications/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to determine Android Studio version.
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.17-11446219)

[✓] Android Studio (version 2023.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.3.5)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 78.3.1
    • Dart plugin version 233.14888

[✓] VS Code (version 1.87.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.84.0

[✓] Connected device (3 available)
    • Taco 12 mini (mobile)             • 00008101-000839661100001E            • ios          • iOS 17.4 21E219
    • iphone 15 pro with creds (mobile) • C9744625-6C63-4DA5-9342-6D1EA7D70645 • ios          • com.apple.CoreSimulator.SimRuntime.iOS-17-2 (simulator)
    • macOS (desktop)                   • macos                                • darwin-arm64 • macOS 14.4 23E214 darwin-arm64

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

```
</details>

---
### P.S.
Was successfully able to generate the .ipa file from Xcode

**Comment by danagbemava-nc** [comment] 2024-03-26 09:23
Hi @daksh-gargas, please provide the crash file `flutter_04.log`. 

Please also share the full verbose output of the command that you run. The output may be huge so kindly put it into a .txt file and attach it here. 

Thank you

**Comment by daksh-gargas** [comment] 2024-03-26 23:26
> Hi @daksh-gargas, please provide the crash file `flutter_04.log`.
> 
> Please also share the full verbose output of the command that you run. The output may be huge so kindly put it into a .txt file and attach it here.
> 
> Thank you

@danagbemava-nc  Done

**Comment by danagbemava-nc** [comment] 2024-03-27 06:29
Hi @daksh-gargas, can you also share the content of your `Info.plist` file?

Also, looking at your logs, it seems like the archive is successfully built, the tool crash just happens to happen after the archive is built. 

```
            ** ARCHIVE SUCCEEDED **
[ +168 ms]  └─Compiling, linking and signing... (completed in 12.3s)
[        ] Xcode archive done.     
```

**Comment by daksh-gargas** [comment] 2024-03-28 22:03
> Hi @daksh-gargas, can you also share the content of your `Info.plist` file?
> 
> Also, looking at your logs, it seems like the archive is successfully built, the tool crash just happens to happen after the archive is built.
> 
> ```
>             ** ARCHIVE SUCCEEDED **
> [ +168 ms]  └─Compiling, linking and signing... (completed in 12.3s)
> [        ] Xcode archive done.     
> ```

Hi, here it is.

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>FLTEnableImpeller</key>
	<string>false</string>
	<key>CADisableMinimumFrameDurationOnPhone</key>
	<true/>
	<key>CFBundleDevelopmentRegion</key>
	<string>$(DEVELOPMENT_LANGUAGE)</string>
	<key>CFBundleDisplayName</key>
	<string>$(APP_DISPLAY_NAME)</string>
	<key>CFBundleExecutable</key>
	<string>$(EXECUTABLE_NAME)</string>
	<key>CFBundleIcons</key>
	<dict/>
	<key>CFBundleIcons~ipad</key>
	<dict/>
	<key>CFBundleIdentifier</key>
	<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>Wildr</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleShortVersionString</key>
	<string>$(FLUTTER_BUILD_NAME)</string>
	<key>CFBundleSignature</key>
	<string>????</string>
	<key>CFBundleURLTypes</key>
	<array>
		<dict>
			<key>CFBundleTypeRole</key>
			<string>Editor</string>
			<key>CFBundleURLName</key>
			<string>Bundle ID</string>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
			</array>
		</dict>
		<dict>
			<key>CFBundleTypeRole</key>
			<string>Editor</string>
			<key>CFBundleURLName</key>
			<string>DevGoogleSignIn</string>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>xxx</string>
			</array>
		</dict>
		<dict>
			<key>CFBundleTypeRole</key>
			<string>Editor</string>
			<key>CFBundleURLName</key>
			<string>ProdGoogleSignIn</string>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>xxx</string>
			</array>
		</dict>
		<dict>
			<key>CFBundleTypeRole</key>
			<string>Editor</string>
			<key>CFBundleURLName</key>
			<string>StagingGoogleSignIn</string>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>xxx</string>
			</array>
		</dict>
	</array>
	<key>CFBundleVersion</key>
	<string>$(FLUTTER_BUILD_NUMBER)</string>
	<key>FirebaseDynamicLinksCustomDomains</key>
	<array>
		<string>xxx</string>
	</array>
	<key>ITSAppUsesNonExemptEncryption</key>
	<false/>
	<key>LSAppliLSApplicationQueriesSchemes</key>
	<array>
		<string>fbapi</string>
		<string>fb-messenger-share-api</string>
		<string>fbauth2</string>
		<string>fbshareextension</string>
	</array>
	<key>LSRequiresIPhoneOS</key>
	<true/>
	<key>NSAppTransportSecurity</key>
	<dict>
		<key>NSAllowsArbitraryLoads</key>
		<true/>
		<key>NSAllowsLocalNetworking</key>
		<true/>
	</dict>
	<key>NSCameraUsageDescription</key>
	<string>xxx</string>
	<key>NSContactsUsageDescription</key>
	<string>xxx</string>
	<key>NSLocalNetworkUsageDescription</key>
	<string></string>
	<key>NSMicrophoneUsageDescription</key>
	<string>xxx</string>
	<key>NSPhotoLibraryUsageDescription</key>
	<string>xxx</string>
	<key>NSSpeechRecognitionUsageDescription</key>
	<string>xxx.</string>
	<key>UIApplicationSupportsIndirectInputEvents</key>
	<true/>
	<key>UIBackgroundModes</key>
	<array>
		<string>fetch</string>
		<string>remote-notification</string>
	</array>
	<key>UILaunchStoryboardName</key>
	<string>LaunchScreen</string>
	<key>UIMainStoryboardFile</key>
	<string>Main</string>
	<key>UIStatusBarStyle</key>
	<string>UIStatusBarStyleDefault</string>
	<key>UISupportedInterfaceOrientations</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
	</array>
	<key>UISupportedInterfaceOrientations~ipad</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationPortraitUpsideDown</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
	<key>UIViewControllerBasedStatusBarAppearance</key>
	<false/>
</dict>
</plist>

```

**Comment by danagbemava-nc** [comment] 2024-04-01 06:30
Labeling for further investigation. Full crash report pasted below. From the logs shared above it seems like the crash happens after the archive has been built. I checked the logs and it seemed like most of the plist files the tool tried to read were parsed successfully, so I'm not sure why the crash is happening

----

Flutter crash report.
Please report a bug at https://github.com/flutter/flutter/issues.

## command

flutter build ipa -v --flavor dev -t lib/main_dev.dart --export-method=ad-hoc

## exception

_TypeError: type 'String' is not a subtype of type 'bool?' in type cast

```
#0      PlistParser.getValueFromFile (package:flutter_tools/src/ios/plist_parser.dart:178:24)
#1      _BuildIOSSubCommand.runCommand (package:flutter_tools/src/commands/build_ios.dart:746:57)
<asynchronous suspension>
#2      BuildIOSArchiveCommand.runCommand (package:flutter_tools/src/commands/build_ios.dart:425:50)
<asynchronous suspension>
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1389:27)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#5      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#6      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:355:9)
<asynchronous suspension>
#7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#8      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:295:5)
<asynchronous suspension>
#9      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:119:9)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#11     main (package:flutter_tools/executable.dart:90:3)
<asynchronous suspension>
```

## flutter doctor

```
[✓] Flutter (Channel stable, 3.19.4, on macOS 14.4 23E214 darwin-arm64, locale en-US)
    • Flutter version 3.19.4 on channel stable at /Users/daksh-gargas/.asdf/installs/flutter/3.19.4
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 68bfaea224 (6 days ago), 2024-03-20 15:36:31 -0700
    • Engine revision a5c24f538d
    • Dart version 3.3.2
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/daksh-gargas/dev/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/daksh-gargas/dev/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.15.2

[!] Android Studio (version unknown)
    • Android Studio at /Applications/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to determine Android Studio version.
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.17-11446219)

[✓] Android Studio (version 2023.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.3.5)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 78.3.1
    • Dart plugin version 233.14888

[✓] VS Code (version 1.87.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.84.0

[✓] Connected device (2 available)
    • Taco 12 mini (mobile) • 00008101-000839661100001E • ios          • iOS 17.4 21E219
    • macOS (desktop)       • macos                     • darwin-arm64 • macOS 14.4 23E214 darwin-arm64

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

**Comment by daksh-gargas** [comment] 2024-04-19 20:38
Hi, any updates on this?
This is really hurting our CI/CD too..
We use `fltuter build ipa` to share the `.ipa` files with our team.

cc @danagbemava-nc

**Comment by christopherfujino** [comment] 2024-04-23 22:14
Closing this as a duplicate of https://github.com/flutter/flutter/issues/138465. @daksh-gargas if you can share your Info.plist file on that issue, it would help us to investigate this.

**Closed by christopherfujino** 2024-04-23 22:14 UTC
Labels: c: crash, platform-ios, tool, a: build, team-tool

**Comment by Chojecki** [comment] 2024-04-25 08:43
@daksh-gargas I just noticed that like you I had `FLTEnableImpeller` set as string. According to docs now it's boolean. Setting it as boolean fixed CI pipeline issue.

Don't know when Flutter team decided to change it and if was it announced in release notes (can't see it). If no its such a shame

**Comment by daksh-gargas** [comment] 2024-04-25 19:18
> @daksh-gargas I just noticed that like you I had `FLTEnableImpeller` set as string. According to docs now it's boolean. Setting it as boolean fixed CI pipeline issue.
> 
> Don't know when Flutter team decided to change it and if was it announced in release notes (can't see it). If no its such a shame

@Chojecki thank you so much for that response.
Let me try it :D
