### ISSUE TITLE
"Google testing" infra error reported with no explaination

### ISSUE THREAD

**Issue by matanlurey** [flutter/flutter#142200] opened 2024-01-25 02:39 UTC
### Type of Request

bug

### Infrastructure Environment

_FRoB? I'm not quite sure, sorry._

### What is happening?

Most recent example: https://github.com/flutter/flutter/pull/142192.

I got:

```
[Thu, 25 Jan 2024 00:43:08 UTC] An infra error occurred while running Google testing
```

I ended up getting frustrated and just merging ignoring this check (I'm pretty confident my change was test only).

### Steps to reproduce

N/A

### Expected results

If Google Testing isn't stable enough to run on every PR, we should consider disabling it or making it FYI only.

**Comment by CaseyHillers** [comment] 2024-01-25 18:21
b/322018010 is the internal tracking bug. tl;dr is that it seems like the generated internal CL gets deleted at some point, and that case isn't handled.

@matanlurey did this reproduce when rerunning the check run? This issue seems to be occurring on ~5% of runs.

**Comment by matanlurey** [comment] 2024-01-25 18:44
5% (1/20 commits) is way too high to have it running by default.

**Comment by CaseyHillers** [comment] 2024-01-31 17:20
> 5% (1/20 commits) is way too high to have it running by default.

I defer to @keyonghan for what we want to consider as acceptable. There's a few tradeoffs that can be applied, and we should holistically find a right balance. For example, we can reduce flakiness by increasing the runtime (by automatically retrying), but that often isn't the right choice.

When Google testing runs on a PR, it's 99%+ likely to stick without someone reverting it (citation needed :-)). Additionally, there's frictions with reverts, and I suspect most people would prefer a somewhat flaky test over a revert+reland.

All of that said, I strongly suspect we can get Google testing to <0.02% flake rate without much work or sacrificing other metrics. Several of these stability issues are one off that have been quick to address.

b/322018010 is fixed so closing this bug.

**Closed by CaseyHillers** 2024-01-31 17:20 UTC
Labels: team-google-testing

**Comment by keyonghan** [comment] 2024-01-31 22:15
> I defer to @keyonghan for what we want to consider as acceptable. 

It would be good to be consistent with other `checkruns`, which is 2%.

**Comment by matanlurey** [comment] 2024-01-31 22:33
Also 2% flaky to me is different than "2% of the time the infra does not work".
