### ISSUE TITLE
No-op `set Paint.enableDithering` (it's deprecated)

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#112498] opened 2022-09-27 19:44 UTC
**EDIT** as of 2023-08-09. Here is our proposal: https://github.com/flutter/flutter/issues/112498#issuecomment-1672062824

---

This flag was added in https://github.com/flutter/flutter/issues/44134, however from a quick investigation we can find no usages of this in google3.  If this isn't being used, we should deprecate and remove it.

@ds84182  do you know what happened to the usage of dithering? Did this solve the problem it was designed to solve or did this get lost somehow. Or am I looking wrong?

**Comment by jonahwilliams** [comment] 2022-09-27 19:46
See also: https://github.com/flutter/flutter/issues/109740

**Comment by ds84182** [comment] 2022-09-27 20:20
Unfortunately we found that dithering did not work as intended with overlapping translucent gradients.

Additionally we also ran into issues with screenshot tests with dithering enabled. It ended up not being worthwhile to enable because all of our goldens would need to be updated. It's also worth noting that it was originally a per-Paint opt-in, which would've been easier for us to integrate as only our gradients need dithering. 

I've separately investigated smoothing out our gradients using blue noise in a shader, which turns out to be a lot more effective than Skia's dithering, even when blending translucent gradients together.

**Comment by b3nni97** [comment] 2023-01-05 03:13
I use the enableDithering flag even in my apps, because otherwise color banding occurs, for example between two shades of gray.

The gradient used in the screenshot:
```dart

Container(
  height: 200,
  decoration: BoxDecoration(
    gradient: !disableGradient
        ? LinearGradient(
            colors: [
              Color(0xff262626),
              Color(0xff0f0f0f),
            ],
            begin: Alignment.bottomLeft,
            end: Alignment.topRight,
            stops: [0.0, 0.4],
          )
        : null,
    borderRadius: BorderRadius.only(
      bottomLeft: Radius.circular(20),
    ),
  ),
);
```

To illustrate the problem here are two screenshots:

On an iPhone X with enableDithering = false strong color banding is visible on the device it looks stronger than on the screenshot.
![IMG_1735](https://user-images.githubusercontent.com/18357332/210692013-66dd2e88-8cdd-41a3-98b9-dac627de14d3.jpg)

On an iPhone X with enableDithering = true no color banding is visible (on the screenshot you can see it easily though).
![IMG_1736](https://user-images.githubusercontent.com/18357332/210692029-6384a8ea-e1e2-47bf-b444-bf8eff77e05e.jpg)

I would like this flag to remain, but maybe my use case is too rare?
@jonahwilliams

**Comment by gaaclarke** [comment] 2023-01-06 01:17
> I would like this flag to remain, but maybe my use case is too rare?

I've personally run into this problem when working with a designer on another product.  It isn't acceptable for Flutter developers to have to go back to their designers and tell them to rework the look because Flutter can't cleanly render their design.  Popularity shouldn't dictate API.  Let's keep it.

**Comment by gaaclarke** [comment] 2023-01-06 17:22
Alternatively, we could remove the flag and automatically do dithering.  That's probably better since many users won't be savvy enough to know to look for it.  The problem with that is the aforementioned golden image tests.  We'd have to make sure it was deterministic so that that it doesn't fiddle with those.

I'm not sure why Skia's implementation is non deterministic.

**Comment by matanlurey** [comment] 2023-08-03 16:57
Update: Engine team has consensus we'd like to remove the global/static `Paint.enableDithering`.

I've assigned this issue to myself to propose/recommend a path forward (with a realistic migration timeline for users).

**Comment by matanlurey** [comment] 2023-08-09 01:36
I've investigated a bit, and here is what I think we should do:

## Proposal

- [ ] **Add an instance property** as `bool ui.Paint.dither` (engine)

  Document that not every paint operation uses dithering, and there is no guarantee that every backend implements
  dithering identically. It might be nice also to document a motivating example (why to use dithering), and alternatives (i.e.
  custom shaders). If `true`, it supersedes the (static) variable `Paint.enableDithering`.

- [ ] **Add similar properties** as `bool painting.{Linear|Radial|Sweep}Gradient` (framework)

  If set, it plumbs through to `dart:ui` (instead of being a global) during the paint operations.

- [ ] **Deprecate** `ui.Paint.enableDithering` (engine)

  Updating the documentation, and announcing a short (?) deprecation period

- [ ] **Remove**, as a breaking change, `ui.Paint.enableDithering` (engine).

## Alternatives

_These can sometimes be mixed-and-matched with the proposal above, and are not mutually exclusive._

1. Add dithering to specific UI objects, like [`Gradient.linear`](https://api.flutter.dev/flutter/dart-ui/Gradient/Gradient.linear.html), instead of a `Paint.dither` flag.

    If we don't expect dithering to apply to all/most paint operations, it feels strange to tie to the `Paint` object.

1. Provide an "easier" way to set dithering across a widget tree, i.e. as an `InheritedWidget`

    This would be an easier migration path off `Paint.enableDithering`, but would have performance ramifications.

1. Enable dithering by default, and instead have the ability to _disable_ dithering.

    This would be a larger breaking change, and it's not clear that it would be well received.

1. Use some sort of heuristic, at least in Impeller, on providing dithering automatically

    In this case, it becomes `bool? dither`, and if `null` uses heuristics. Interestingly enough, `Paint.enableDithering`
    claims we do this (I'm guessing because Skia might?) by stating:

    > If false, the default value, dithering will be enabled when the input color depth is higher than the output color depth. For example, drawing an RGB8 image onto an RGB565 canvas.

    I'm open to this, but would need some help figuring out a good approach (if done poorly it's another big breaking change).

---

Feel free to suggest different alternatives and/or problems :)

**Comment by ds84182** [comment] 2023-08-09 01:49
fwiw when I made the change the dither flag was original on `ui.Paint` and I had planned to add a dither property to the gradient classes on the framework side. But there was some pushback for that implementation.

**Comment by jonahwilliams** [comment] 2023-08-09 02:15
I would rather not add any more properties to `ui.Paint` if we can avoid it. There are several issues with the Paint API design:

* Like you point out, its not obvious which properties apply to which drawing commands. dithering or no dithering is really a property of the gradient, which could be set in the gradient constructor.
* Because of the whole dart/engine split, every single bit of data in the paint object needs to be copied into an engine DlPaint or ImpellerPaint object - so adding more properties only used by some drawing commands increases the cost of all commands. In some edge cases (e.g. drawing 500 rectangles), the cost of copying paint data can be the most expensive operation performed.

While I'm in favor of the dithered gradient, I think the we should consider making this the default behavior and not supporting configuration of the value.

**Comment by matanlurey** [comment] 2023-08-09 02:18
I'm supportive. I think there is a reasonable question around "but what about images", but I can't find any strong motivating examples.

**Comment by jonahwilliams** [comment] 2023-08-09 02:23
Do you mean images w.r.t golden testing?

**Comment by Zabadam** [comment] 2023-08-09 02:26
> ## Alternatives
> 
> 1. Add dithering to specific UI objects, like [`Gradient.linear`](https://api.flutter.dev/flutter/dart-ui/Gradient/Gradient.linear.html), instead of a `Paint.dither` flag.
> 
>     If we don't expect dithering to apply to all/most paint operations, it feels strange to tie to the `Paint` object.
> 

This seems like an interesting approach. It requires considering what other operations might obey a dithering flag. However, surely a developer would want to fine-tune any such dithering implementation, no? A simple flag on a Gradient creates more lerping issues, as exist with `transform` and `tileMode`. 

I have solved both lerping issues *and* added dithering, also with true lerping, through a custom ShaderGradient implementation. What I discovered was that adding dithering was essentially one step away from allowing "texturing" support for Gradients. That is, instead of a hash/rand function, I use a blue noise sampler and allow the user to swap out the sampler and control its scale and strength. Now the dithering is more than only functional, it is also tuneable to taste/art direction.

All said, I do not know how dithering is implemented in Flutter. I have read the Gradient shader programs and see no reference to it, so I'm sure it is some other deeper interaction... but I do know that `bool`s do not lerp well haha

**Comment by jonahwilliams** [comment] 2023-08-09 02:29
> This seems like an interesting approach. It requires considering what other operations might obey a dithering flag. 

We're not going to support dithering on any other commands besides the gradients.

**Comment by ds84182** [comment] 2023-08-09 07:41
Dithering does apply to all drawing commands in the software renderer. Especially useful when your framebuffer has lower precision than RGB8.

**Comment by ds84182** [comment] 2023-08-09 17:13
Eh, for desktop and mobile sure. But for custom embedders without a GPU it's useful.

**Comment by matanlurey** [comment] 2023-08-09 17:13
To be clear, "we" here = "supported platforms": https://docs.flutter.dev/reference/supported-platforms.

**Comment by matanlurey** [comment] 2023-08-09 17:15
@jonahwilliams:

> Do you mean images w.r.t golden testing?

Yes, edited.

> While I'm in favor of the dithered gradient, I think the we should consider making this the default behavior and not supporting configuration of the value.

I'm supportive. My only reason for proposing gradient-specific flags is that we can divorce ourselves from having to make sure dithering always is the right choice for every gradient, and I think (?) it solves the problem you've outlined with adding data to the `Paint` object.

**Comment by ds84182** [comment] 2023-08-09 18:43
@matanlurey 

> To be clear, "we" here = "supported platforms": https://docs.flutter.dev/reference/supported-platforms.

It _is_ a supported platform, as the most common target for custom embedders _is_ Linux.

If the embedder API is not a "supported platform", maybe it should not be depended on or exposed.

If the software renderer is not part of the "supported platforms", then the existing software fallback (when OGL, Angle, etc. fail to initialize) should be removed.

@jonahwilliams 

> * Because of the whole dart/engine split, every single bit of data in the paint object needs to be copied into an engine DlPaint or ImpellerPaint object - so adding more properties only used by some drawing commands increases the cost of all commands. In some edge cases (e.g. drawing 500 rectangles), the cost of copying paint data can be the most expensive operation performed.

The dither property on ui.Paint already exists today, but its private. I would rather see it merged with the data offset for isAntiAlias, turning it into a bitflag. This cost is marginal compared to the expensive individual draw calls that occur for drawing 500 individual rects.

**Comment by jonahwilliams** [comment] 2023-08-09 18:53
@matanlurey for golden testing I'm inclined to not care at all if its difficult to create scubas, given that their absue has caused us nothing but problems. That said, the Skia software backend has a deterministic rendering flag we enable - so we could always force disable dithering if that is enabled.  Or we could only enable dithering by default in Impeller. Since there is no facility for golden testing with flutter_tester with Impeller we don't need to wory about for now.

**Comment by matanlurey** [comment] 2023-08-09 19:59
Updated proposal with @jonahwilliams (I'll leave the previous comment for posterity):

1. Flip `ui.Paint.enableDithering` to default to `true` (previously `false`).
    We aren't considering this a breaking change, as it's changing pixels and not code from compiling.

1. Mark `ui.Paint.enableDithering` `@Deprecated` with a note it will be removed after Impeller ships on Android.

1. Then (much later), remove `ui.Paint.enableDithering`.

I'll send out a PR to get started with 1 and 2 shortly.

**Comment by ds84182** [comment] 2023-08-09 20:07
Enabled by default SGTM, thank you. I really appreciate it. Another thing to note: It'll be useful for RGBA8 framebuffers too when Flutter gets floating point color support.

**Comment by matanlurey** [comment] 2023-08-09 20:33
> Only potential caveat is that this may do bad things for scuba, so we may need to compile in a branch where we force this off in the flutter_tester binary.

Thanks! I'll coordinate with the internal team on what might be the best way to roll this in.

**Comment by Zabadam** [comment] 2023-08-09 20:49
I sure am glad the Gradients are getting a small amount of much-needed attention here. Of course published packages can always accomplish the "extra goals" better anyway.

For example, using a generated ramp texture (with no buffers available and forgoing arrays) with much higher than 256x1 resolution can all but eliminate banding, too, if you're willing to have a more expensive Gradient—which I am.

**Comment by matanlurey** [comment] 2023-08-23 18:06
Update: This is still a WIP.

In https://github.com/flutter/engine/pull/44730 and https://github.com/flutter/engine/pull/44912, I modified the Skia backend to _only_ respect dithering of gradients (which is what the Impeller backend will do), but otherwise made no other changes.

Next step will be flipping the default (https://github.com/flutter/engine/pull/44705), which is itself pending google-internal verification.

**Comment by matanlurey** [comment] 2023-09-01 19:00
After a short baking period I'll finalize cleaning this up.

**Closed** 2023-10-31 22:28 UTC
Labels: engine, P3, c: tech-debt, team-engine, triaged-engine, fyi-google-testing
