### ISSUE TITLE
Flutter gallery does not scroll at 60fps on a Galaxy Note 5

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#11283] opened 2017-07-18 22:42 UTC
Device is in our test rack.

```
[✓] Flutter (on Mac OS X 10.12.5 16F73, locale en-US, channel alpha)
    • Flutter at /src/flutter
    • Framework revision d36e2f6191 (4 weeks ago), 2017-06-21 15:09:10 -0700
    • Engine revision b0dee695ec
    • Tools Dart version 1.24.0-dev.6.7

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.0)
    • Android SDK at /Users/eseidel/Library/Android/sdk
    • Platform android-26, build-tools 26.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.3.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.3.2, Build version 8E2002
    • ios-deploy 1.9.1
    • CocoaPods version 1.2.1

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Gradle version 3.2
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.1.4)
    • Flutter plugin version 14.0
    • Dart plugin version 171.4694.29

[✓] Connected devices
    • SAMSUNG SM N920A • 1115fbe3a1b01304 • android-arm • Android 5.1.1 (API 22)
```

![flutter_01](https://user-images.githubusercontent.com/11857803/28342928-a02f67d6-6bcf-11e7-859b-a61a658b7d0b.png)

**Comment by pauldemarco** [comment] 2017-07-19 11:03
This could also be #10481

**Comment by cbracken** [comment] 2019-11-06 22:33
@liyuqian is this closeable?

**Comment by liyuqian** [comment] 2019-11-06 22:47
@cbracken I hope so but I can't find the note 5 in our device library for the confirmation. I'm asking to see where I can find it... In case we can't find it, shall we just close it as it's no longer reproducible?

**Comment by markusaksli-nc** [comment] 2020-09-30 07:09
I'll just go ahead and close this since there has been no update after the comments above. Feel free to reopen if it is still relevant.

**Closed by markusaksli-nc** 2020-09-30 07:09 UTC
Labels: P4, e: device-specific, engine, severe: performance
