### ISSUE TITLE
Android studio freezes when building for iOS with verbose logging

### ISSUE THREAD

**Issue by Henrik-glt** [flutter/flutter#59747] opened 2020-06-18 08:06 UTC
## The problem
Android studio freezes when running app on iPhone or iOS simulator.
Tested with iOS 12.1, 12.4, 13.4 and 13.5.

Worked before I updated to Android Studio 4.0.
But the problem persists even after I downgrade to Android Studio 3.6.3.

Works just fine in Visual Studio Code and when building in terminal.

**Possibly related to flavors.**
I have another project without flavors and that project runs just fine with verbose logging (-v).

## Steps to Reproduce

1. Create a new project
2. Add flavors
3. Create a run configuration with verbose logging and specific flavor
4. Select your run configuration and click the Debug button.

## Result

The projects starts to build just fine.
The app is even launched on the device, but just before the build completes Android Studio just freezes. 

## Logs

```
```

[✓] Flutter (Channel stable, v1.17.3, on Mac OS X 10.15.5 19F101, locale en-NO)
    • Flutter version 1.17.3 at
      /Users/USER/Documents/Development/FLUTTER_SDK/flutter
    • Framework revision b041144f83 (2 weeks ago), 2020-06-04 09:26:11 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/USER/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (1 available)
    • iPhone X • 7BE86F96-33FE-431A-889F-E65948436AAB • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-12-4 (simulator)

• No issues found!

**Comment by TahaTesser** [comment] 2020-06-18 13:13
Hi @Henrik-glt 
Can you please provide  and a minimal reproducible code sample including flavors setup
Thank you

**Comment by Henrik-glt** [comment] 2020-06-22 09:42
@TahaTesser  Followed this guide: https://cogitas.net/creating-flavors-of-a-flutter-app/ . Provided by Flutter here: https://flutter.dev/docs/deployment/flavors (Creating flavors of a Flutter app).

After more tests the problem seems to persist even if verbose logging is disabled, but it works sometimes when verbose logging is disabled.

To reproduce:
1. flutter create bugstuck
2. Add flavors  https://cogitas.net/creating-flavors-of-a-flutter-app/
3. Add Xcode configurations for each flavor and variant (debug, profile & release). Each of these xcconfig files should reference the Generated.xcconfig file and the cocoa pods xcconfig file:
#include "../../Flutter/Generated.xcconfig"
#include "PATH/TO/PODS/Runner.debug-demo.xcconfig"
4. In Xcode: Update **Configurations** in PROJECT -> Info -> Configurations
5. Add a new run configuration to Android Studio. Reference one of the "flavor main files" that you created and add additional arguments: -v --flavor yourflavor
6. Run the app and watch Android Studio freeze just before Xcode build completes

**Comment by iapicca** [comment] 2020-06-24 13:52
Hi @Henrik-glt 
Are you experiencing the issue only with Android Studio / IntelliJ or with VS Code as well?
Thank you

**Comment by Henrik-glt** [comment] 2020-06-25 06:08
@iapicca Only with Android Studio. VS Code works flawlessly :)

**Comment by Henrik-glt** [comment] 2020-06-25 10:26
@iapicca  Some weird info, if I:

1. Press debug in Android Studio (build starts..)
2. Switch focus to another app

Then the build completes just fine.
I can se logs being printed in the debug console in Android Studio and everything seems to be working just fine.
The moment I switch back to (move focus to) Android Studio it freezes.

Just found out that if I just leave Android Studio for about 10 minutes it "unfreezes" and everything works again (hot reload, hot restart, breakpoints etc).
The problem is however back when I rebuild the app and start a new debug session.

**Comment by iapicca** [comment] 2020-06-26 07:19
Hi @Henrik-glt 
Following the indication of [jetbrains' Flutter plugin](https://plugins.jetbrains.com/plugin/9212-flutter), the correct way to address the problem is to open an issue in the dedicated [repository](https://github.com/flutter/flutter-intellij/issues).
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by iapicca** 2020-06-26 07:19 UTC
Labels: in triage
