### ISSUE TITLE
'_initialButtons == kPrimaryButton': is not true.

### ISSUE THREAD

**Issue by ycg520520** [flutter/flutter#68453] opened 2020-10-19 00:59 UTC
``` dart error
══╡ EXCEPTION CAUGHT BY GESTURE LIBRARY ╞═══════════════════════════════════════════════════════════
The following assertion was thrown while dispatching a pointer event:
'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 379 pos 12: '_initialButtons ==
kPrimaryButton': is not true.
Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md
When the exception was thrown, this was the stack:
#2      DragGestureRecognizer._checkStart 
package:flutter/…/gestures/monodrag.dart:379
#3      DragGestureRecognizer.acceptGesture 
package:flutter/…/gestures/monodrag.dart:310
#4      GestureArenaManager.sweep 
package:flutter/…/gestures/arena.dart:158
#5      GestureBinding.handleEvent 
package:flutter/…/gestures/binding.dart:224
#6      GestureBinding.dispatchEvent 
package:flutter/…/gestures/binding.dart:200
#7      GestureBinding._handlePointerEvent 
package:flutter/…/gestures/binding.dart:158
#8      GestureBinding._flushPointerEventQueue 
package:flutter/…/gestures/binding.dart:104
#9      GestureBinding._handlePointerDataPacket 
package:flutter/…/gestures/binding.dart:88
#13     _invoke1  (dart:ui/hooks.dart:267:10))
#14     _dispatchPointerDataPacket  (dart:ui/hooks.dart:176:5))
(elided 5 frames from class _AssertionError and dart:async)
Event:
  PointerUpEvent#7e9ab(position: Offset(51.0, 285.0))
Target:
  <WidgetsFlutterBinding>
════════════════════════════════════════════════════════════════════════════════════════════════════
```

test_page.dart
``` dart
import 'package:flutter/widgets.dart';
import 'package:flutter/material.dart';

class TestPage extends StatefulWidget {
  TestPage({Key key}) : super(key: key);
  @override
  _TestPageState createState() {
    return _TestPageState();
  }
}

class _TestPageState extends State<TestPage>
    with SingleTickerProviderStateMixin {
  var subscription;
  TabController _tabController;
  ScrollController _scrollController;
  @override
  void initState() {
    _tabController = TabController(initialIndex: 0, length: 2, vsync: this);
    _scrollController = ScrollController();
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: NestedScrollView(
            controller: _scrollController,
            headerSliverBuilder:
                (BuildContext context, bool innerBoxIsScrolled) {
              return <Widget>[
                SliverToBoxAdapter(
                    child: Container(
                        height: 200,
                        padding: EdgeInsets.only(left: 16, right: 16),
                        child: Center(child: Text('header content'))))
              ];
            },
            body: Container(
                padding: EdgeInsets.only(left: 16, right: 16),
                child: Column(children: [
                  Container(
                      child: TabBar(
                          controller: _tabController,
                          onTap: (index) {
                            print('$index');
                          },
                          labelColor: Colors.black,
                          indicatorColor: Colors.black,
                          tabs: [Text('tab1'), Text('tab2')])),
                  Expanded(
                      child: TabBarView(
                        // physics: NeverScrollableScrollPhysics(),
                        controller: _tabController, children: [
                    ListView.builder(
                        itemBuilder: (BuildContext context, index) {
                          return Container(child: Text('tab1-$index'));
                        }),
                    ListView.builder(
                        itemBuilder: (BuildContext context, index) {
                          return Container(child: Text('tab2-$index'));
                        })
                  ]))
                ]))));
  }

  @override
  void dispose() {
    _tabController.dispose();
    _scrollController.dispose();
    super.dispose();
  }
}

```

How to solve this problem？

**Comment by ycg520520** [comment] 2020-10-19 01:08
flutter doctor -v
```bash
[✓] Flutter (Channel stable, 1.20.3, on Mac OS X 10.15.5 19F101, locale zh-Hans-CN)
    • Flutter version 1.20.3 at /Users/yangchaoguo/Documents/flutter
    • Framework revision 216dee60c0 (7 weeks ago), 2020-09-01 12:24:47 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/yangchaoguo/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/yangchaoguo/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0, Build version 12A7209
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.0

[✓] Connected device (1 available)
    • iPhone SE (2nd generation) (mobile) • E864B09F-B728-480A-BD6B-4879845F210F • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)
```

**Comment by sidrao2006** [comment] 2020-10-19 02:20
Duplicate of #66454

**Comment by pedromassangocode** [comment] 2020-10-19 09:22
Hi @ycg520520 
I see there's an open issue (https://github.com/flutter/flutter/issues/68373) addressing the case you described.
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by pedromassangocode** 2020-10-19 09:22 UTC
