### ISSUE TITLE
It should be stated that you should not have a "~/.flutter" directory.

### ISSUE THREAD

**Issue by ndac-todoroki** [flutter/flutter#22842] opened 2018-10-09 03:14 UTC
Environment: Linux (ubuntu 18.04 LTS)

The `flutter` command tries to create a `~/.flutter` directory automatically, and it aborts if that fails.
Following the instructions [here](https://flutter.io/setup-linux/), I tried to untar the Flutter SDK into my desired `~/.flutter`, and all the `flutter` commands did not work.

I think it should be stated the you should not have that directory.

**Comment by zoechi** [comment] 2018-12-20 08:13
Duplicate of #25089

**Comment by zoechi** [comment] 2018-12-20 08:13
This issue is older but #25089 has more activity

**Closed** 2018-12-20 08:14 UTC
Labels: d: website - content, tool

**Comment by zoechi** [comment] 2019-01-09 17:41
Duplicate of #4674
