### ISSUE TITLE
[flutter_adaptive_scaffold] black line on Windows navigation rail

### ISSUE THREAD

**Issue by WH-Creations** [flutter/flutter#117635] opened 2022-12-25 20:36 UTC
## Steps to Reproduce

1. Create an AdaptiveNavigationScaffold]
2. Add any child widget
3. Run on Windows target (Running on a web target does not produce the issue)

**Expected results:** There should be no black line on the right side of the navigation rail when in the fully expanded mode

**Actual results:** There is a black line apparent when running on Windows
![blackLine](https://user-images.githubusercontent.com/97212578/209480978-2ca92806-7028-43fd-b31c-54be8bff1a8b.png)

<details>
<summary>Code sample</summary>

```
import 'package:adaptive_navigation/adaptive_navigation.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: NavigationContainer(),
    );
  }
}

class NavigationContainer extends StatelessWidget {
  NavigationContainer({super.key});

  List<AdaptiveScaffoldDestination> destinationList = [
    const AdaptiveScaffoldDestination(title: 'Index 0', icon: Icons.home),
    const AdaptiveScaffoldDestination(
        title: 'Index 1', icon: Icons.onetwothree),
  ];

  @override
  Widget build(BuildContext context) {
    return AdaptiveNavigationScaffold(
      selectedIndex: 0,
      drawerScrimColor: Colors.white,
      backgroundColor: Colors.white,
      bottomNavigationOverflow: 10,
      body: ClipRect(
        child: ChildWidget(),
      ),
      destinations: destinationList,
    );
  }
}

class ChildWidget extends StatelessWidget {
  ChildWidget({super.key});

  @override
  Widget build(BuildContext context) {
    return Container(
      color: Colors.white,
    );
  }
}

```

</details>

<details>
  <summary>Logs</summary>

[√] Flutter (Channel stable, 3.3.10, on Microsoft Windows [Version
    10.0.22000.1335], locale en-US)
    • Flutter version 3.3.10 on channel stable at
      C:\Users\Casey\Documents\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (10 days ago), 2022-12-15 07:36:55 -0800   
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

[√] Android toolchain - develop for Android devices (Android SDK version
    32.0.0)
    • Android SDK at C:\Users\Casey\AppData\Local\Android\sdk
    • Platform android-33, build-tools 32.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java     
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)   
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.3.6)  
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community 
    • Visual Studio Community 2022 version 17.3.32929.385
    • Windows 10 SDK version 10.0.22621.0

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)   

[√] VS Code (version 1.74.0)
    • VS Code at C:\Users\Casey\AppData\Local\Programs\Microsoft VS Code       
    • Flutter extension version 3.56.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version
      10.0.22000.1335]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome
      108.0.5359.125
    • Edge (web)        • edge    • web-javascript • Microsoft Edge
      108.0.1462.42

[√] HTTP Host Availability
    • All required HTTP hosts are available

</details>

**Comment by huycozy** [comment] 2022-12-26 10:05
Hi @WH-Creations 

From what I can see, the issue is related to a 3rd party plugin (`adaptive_navigation`) rather than to Flutter/Flutter 1st plugins/packages. Please open the issue in the dedicated [repository](https://github.com/material-components/material-components-flutter-adaptive/issues).

Closing, as this isn't an issue with Flutter itself.  If you disagree, please write in the comments, providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`, a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that does not use 3rd party plugins and I will reopen it.

Thank you!

**Closed by huycozy** 2022-12-26 10:05 UTC
Labels: in triage

**Comment by WH-Creations** [comment] 2022-12-26 20:06
Gotcha, thanks :)
