### ISSUE TITLE
Flutter crashing when moving Google Map

### ISSUE THREAD

**Issue by ahmaducg** [flutter/flutter#58914] opened 2020-06-07 11:57 UTC
## Steps to Reproduce

1. Create an application with google_maps_flutter (0.5.28+1).
2. Open the application, and move around the map.
3. Eventually the application will crash with the error below :

Error :

```
io.flutter.view.AccessibilityViewEmbedder$ReflectionAccessors.getChildId (AccessibilityViewEmbedder.java:55)
io.flutter.view.AccessibilityViewEmbedder$ReflectionAccessors.access$500 (AccessibilityViewEmbedder.java)
io.flutter.view.AccessibilityViewEmbedder.addChildrenToFlutterNode (AccessibilityViewEmbedder.java:9)
io.flutter.view.AccessibilityViewEmbedder.convertToFlutterNode (AccessibilityViewEmbedder.java:45)
io.flutter.view.AccessibilityViewEmbedder.getRootNode (AccessibilityViewEmbedder.java:30)
io.flutter.view.AccessibilityBridge.createAccessibilityNodeInfo (AccessibilityBridge.java:90)
android.view.View.populateVirtualStructure (View.java:8649)
android.view.View.populateVirtualStructure (View.java:8652)
android.view.View.populateVirtualStructure (View.java:8652)
android.view.View.populateVirtualStructure (View.java:8652)
android.view.View.populateVirtualStructure (View.java:8652)
android.view.View.populateVirtualStructure (View.java:8652)
android.view.View.populateVirtualStructure (View.java:8652)
android.view.View.populateVirtualStructure (View.java:8652)
android.view.View.populateVirtualStructure (View.java:8652)
android.view.View.populateVirtualStructure (View.java:8652)
android.view.View.populateVirtualStructure (View.java:8652)
android.view.View.onProvideVirtualStructureCompat (View.java:8070)
android.view.View.onProvideVirtualStructure (View.java:8051)
android.view.View.dispatchProvideStructureForAssistOrAutofill (View.java:8719)
android.view.View.dispatchProvideStructure (View.java:8666)
android.view.ViewGroup.dispatchProvideStructure (ViewGroup.java:3557)
android.view.ViewGroup.dispatchProvideStructure (ViewGroup.java:3557)
android.view.ViewGroup.dispatchProvideStructure (ViewGroup.java:3557)
android.app.assist.AssistStructure$WindowNode.<init> (AssistStructure.java:519)
android.app.assist.AssistStructure.<init> (AssistStructure.java:2047)
android.app.ActivityThread.handleRequestAssistContextExtras (ActivityThread.java:3794)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:2153)
android.os.Handler.dispatchMessage (Handler.java:112)
android.os.Looper.loop (Looper.java:216)
android.app.ActivityThread.main (ActivityThread.java:7625)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:524)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:987)
```

<details>
  <summary>Logs</summary>

```
[  +15 ms] [✓] Flutter (Channel master, 1.19.0-4.0.pre.74, on Microsoft Windows [Version 10.0.18363.836], locale en-US)
[   +3 ms]     • Flutter version 1.19.0-4.0.pre.74 at C:\Programming\flutter
[        ]     • Framework revision 71a5c61907 (2 days ago), 2020-06-05 10:38:03 -0300
[   +1 ms]     • Engine revision 859d892f1f
[        ]     • Dart version 2.9.0 (build 2.9.0-13.0.dev 54adfeb93f)
\[  +36 ms] List of devices attached
[  +51 ms] executing: C:\Programming\Android\Android_SDK\tools\bin\sdkmanager --licenses
[+1424 ms] [✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[   +1 ms]     • Android SDK at C:\Programming\Android\Android_SDK
[   +1 ms]     • Platform android-R, build-tools 29.0.2
[   +1 ms]     • Java binary at: C:\Programming\Android\Android_Studio_Canary\jre\bin\java
[        ]     • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
[        ]     • All Android licenses accepted.
[   +3 ms] [✓] Chrome - develop for the web
[        ]     • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
[   +2 ms] [✓] Android Studio (version 4.0)
[        ]     • Android Studio at C:\Programming\Android\Android_Studio
[        ]     • Flutter plugin version 46.0.2
[   +1 ms]     • Dart plugin version 193.7361
[        ]     • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
[   +3 ms] [✓] Android Studio (version 4.1)
[   +1 ms]     • Android Studio at C:\Programming\Android\Android_Studio_Canary
[   +1 ms]     • Flutter plugin version 42.1.4
[        ]     • Dart plugin version 193.6911.31
[        ]     • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
[   +1 ms] [✓] IntelliJ IDEA Community Edition (version 2019.3)
[        ]     • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.1.1
[   +2 ms]     • Flutter plugin version 45.0.2
[   +1 ms]     • Dart plugin version 193.6911.31
[   +2 ms] [✓] VS Code, 64-bit edition (version 1.44.2)
[   +1 ms]     • VS Code at C:\Program Files\Microsoft VS Code
[   +1 ms]     • Flutter extension version 3.11.0
[   +2 ms] [✓] Connected device (2 available)
[        ]     • Web Server • web-server • web-javascript • Flutter Tools
[   +1 ms]     • Chrome     • chrome     • web-javascript • Google Chrome 83.0.4103.97
[        ] • No issues found!
```

</details>

**Comment by VladyslavBondarenko** [comment] 2020-06-08 11:13
Hi @ahmaducg 
with what device are you experiencing this? do you have other devices to test? how long does it take to move around the map?

I tried with `google_maps_flutter (0.5.28+1)`, `master 1.19.0-4.0.pre.99` on Redmi Note 7 Android 9 (API 28)
<details>
 <summary>with this code sample</summary>
```
import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Google Maps Demo',
      home: MapSample(),
    );
  }
}

class MapSample extends StatefulWidget {
  @override
  State<MapSample> createState() => MapSampleState();
}

class MapSampleState extends State<MapSample> {

  static final CameraPosition _kGooglePlex = CameraPosition(
    target: LatLng(37.42796133580664, -122.085749655962),
    zoom: 14.4746,
  );

  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      body: GoogleMap(
        mapType: MapType.hybrid,
        initialCameraPosition: _kGooglePlex,
      ),
    );
  }
}
```
</details>

moved around and couldn't reproduce

**Comment by ahmaducg** [comment] 2020-06-08 18:12
It's crashing on a Huawei Nova 3 (Android 9).
I have a button that moves the map to another location with Camera Bounds, but when I click the button the application crashes.

**Comment by TahaTesser** [comment] 2020-06-09 08:28
Hi @ahmaducg 
Can you please provide and a minimal complete reproducible code sample.
Thank you

**Comment by ahmaducg** [comment] 2020-06-15 10:05
But even if I write the same code, I can't reproduce the bug because it's device specific, and the device is a User's device.

**Comment by VladyslavBondarenko** [comment] 2020-06-15 13:04
@ahmaducg 
could you provide a code sample with which it reproduces for the user's device?

<details>
 <summary>or will it reproduce with for example with this code?</summary>

```
import 'dart:async';

import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Google Maps Demo',
      home: MapSample(),
    );
  }
}

class MapSample extends StatefulWidget {
  @override
  State<MapSample> createState() => MapSampleState();
}

class MapSampleState extends State<MapSample> {
  Completer<GoogleMapController> _controller = Completer();

  static final CameraPosition _kGooglePlex = CameraPosition(
    target: LatLng(37.42796133580664, -122.085749655962),
    zoom: 14.4746,
  );

  static final CameraPosition _kLake = CameraPosition(
      bearing: 192.8334901395799,
      target: LatLng(37.43296265331129, -122.08832357078792),
      tilt: 59.440717697143555,
      zoom: 19.151926040649414);

  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      body: GoogleMap(
        mapType: MapType.hybrid,
        initialCameraPosition: _kGooglePlex,
        onMapCreated: (GoogleMapController controller) {
          _controller.complete(controller);
        },
      ),
      floatingActionButton: FloatingActionButton.extended(
        onPressed: _goToTheLake,
        label: Text('To the lake!'),
        icon: Icon(Icons.directions_boat),
      ),
    );
  }

  Future<void> _goToTheLake() async {
    final GoogleMapController controller = await _controller.future;
    controller.animateCamera(CameraUpdate.newCameraPosition(_kLake));
  }
}
```

</details>

**Comment by TahaTesser** [comment] 2020-07-07 15:01
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

**Closed by TahaTesser** 2020-07-07 15:01 UTC
Labels: in triage
