### ISSUE TITLE
[web] RenderRepaintBoundary toImage() - doesn't support WEB.

### ISSUE THREAD

**Issue by michaldev** [flutter/flutter#62852] opened 2020-08-04 12:42 UTC
Hi. I've created simple cropper. I've used for it RepaintBoundary widget. All works good, but only in Android and iOS. On web I see errors, like this:
```Assertion failed:
org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/surface/scene_builder.dar
t:95:16
matrix4[0] == window.devicePixelRatio &&
           matrix4[5] == window.devicePixelRatio
is not true
```

Code for reproduction is simply:
`final GlobalKey _globalKey = GlobalKey();`
```
RepaintBoundary(
                key: _globalKey,
                child: Text('example widget');
)
```

```
  Future<void> _capturePng() async {
    try {
      final RenderRepaintBoundary boundary =
          _globalKey.currentContext.findRenderObject() as RenderRepaintBoundary;
      final ui.Image image = await boundary.toImage(pixelRatio: 3.0);
    } catch (e) {
      print(e);
    }
```

final ui.Image image = await boundary.toImage(pixelRatio: 3.0); <-- This line is problem.
Because this problem exists, others croppers (like Cropp) don’t work too on web.

**Comment by darshankawar** [comment] 2020-08-05 07:17
Similar to [47721](https://github.com/flutter/flutter/issues/47721).

Hi @michaldev,
Please see [this](https://github.com/flutter/flutter/issues/47721#issuecomment-570718927) comment from above referenced ticket and another [comment](https://github.com/flutter/flutter/issues/47721#issuecomment-638450866) in which the issue is split into two tickets.
Please follow-up there for updates on this issue.
Closing this as duplicate. If you disagree, write in comments and I'll reopen.
Thanks.

**Closed by darshankawar** 2020-08-05 07:17 UTC
