### ISSUE TITLE
unexpected error when install flutter

### ISSUE THREAD

**Issue by ghost** [flutter/flutter#15394] opened 2018-03-11 04:03 UTC
1. I follow the steps on the official website.
   - clone the beta version
   - set the environment variable
   - run flutter doctor
2. when  i make these steps:
```
  Building flutter tool...
The setter 'readEventsEnabled=' was called on null.
Receiver: null
Tried calling: readEventsEnabled=false
package:pub/src/source/hosted.dart 339                                                     BoundHostedSource._throwFriendlyError
package:pub/src/source/hosted.dart 141                                                     BoundHostedSource.doGetVersions
===== asynchronous gap ===========================
package:pub/src/source.dart 169                                                            BoundSource.getVersions
package:pub/src/solver/version_solver.dart 237                                             SolverCache.getVersions.<fn>
dart:async                                                                                 runZoned
package:pub/src/http.dart 267                                                              withDependencyType
package:pub/src/solver/version_solver.dart 236                                             SolverCache.getVersions
===== asynchronous gap ===========================
package:pub/src/solver/unselected_package_queue.dart 121                                   UnselectedPackageQueue._getNumVersions
===== asynchronous gap ===========================
package:pub/src/solver/unselected_package_queue.dart 50                                    UnselectedPackageQueue.add
===== asynchronous gap ===========================
package:pub/src/solver/version_selection.dart 88                                           VersionSelection._addDependencies
===== asynchronous gap ===========================
package:pub/src/solver/version_selection.dart 63                                           VersionSelection.select
===== asynchronous gap ===========================
package:pub/src/solver/backtracking_solver.dart 174                                        BacktrackingSolver.solve
===== asynchronous gap ===========================
package:pub/src/solver/version_solver.dart 42                                              resolveVersions.<fn>
package:pub/src/log.dart 409                                                               progress
package:pub/src/solver/version_solver.dart 40                                              resolveVersions
package:pub/src/entrypoint.dart 195                                                        Entrypoint.acquireDependencies
===== asynchronous gap ===========================
package:pub/src/command/upgrade.dart 41                                                    UpgradeCommand.run
===== asynchronous gap ===========================
package:args/command_runner.dart 194                                                       CommandRunner.runCommand
===== asynchronous gap ===========================
package:pub/src/command_runner.dart 167                                                    PubCommandRunner.runCommand.<fn>
dart:async                                                                                 new Future.sync
package:pub/src/utils.dart 103                                                             captureErrors.<fn>
dart:async                                                                                 runZoned
package:pub/src/utils.dart 122                                                             captureErrors
package:pub/src/command_runner.dart 167                                                    PubCommandRunner.runCommand
===== asynchronous gap ===========================
package:pub/src/command_runner.dart 116                                                    PubCommandRunner.run
===== asynchronous gap ===========================
/b/build/slave/Linux_Engine/build/src/third_party/dart/third_party/pkg/pub/bin/pub.dart 8  main
This is an unexpected error. Please run

    pub --trace upgrade --verbosity=error --no-packages-dir
```
what's wrong with my operations.
thanks :+1:

**Comment by zoechi** [comment] 2019-01-17 10:44
Duplicate of #12301

**Closed by zoechi** 2019-01-17 10:44 UTC
Labels: a: first hour, severe: crash, tool
