### ISSUE TITLE
App crashing

### ISSUE THREAD

**Issue by vikRAM1905** [flutter/flutter#132888] opened 2023-08-19 07:58 UTC
app crashing every 1 minute in google pixel phone... sometimes it crashing in other phones too... I've updated to latest version of flutter(3.13) and google_maps_flutter package (2.4.0) too... give me some solution

**Comment by jtmuller5** [comment] 2023-08-19 11:43
Hi, would you be able to provide additional details about your app so that we can attempt to reproduce the issue? Do you have a code sample?

**Comment by vikRAM1905** [comment] 2023-08-19 12:10
cupertino_icons 1.0.5
  device_info_plus 9.0.3
  device_info_plus_platform_interface 7.0.0
  dio 4.0.6 (5.3.2 available)
  flutter_native_splash 2.3.2
  flutter_polyline_points 1.0.0
  flutter_rating_bar 4.0.1
  flutter_svg 2.0.7
  geocoding 2.1.0
  geocoding_android 2.1.2
  geocoding_ios 2.1.0
  geocoding_platform_interface 2.0.1 (3.0.0 available)
  geolocator 9.0.2 (10.0.0 available)
  geolocator_android 4.2.2
  geolocator_apple 2.2.7
  geolocator_platform_interface 4.0.7
  geolocator_web 2.1.6
  geolocator_windows 0.1.3 (0.2.0 available)
  get_it 7.6.0
  google_api_headers 1.6.0 (2.0.0 available)
  google_fonts 4.0.4 (5.1.0 available)
  google_maps 6.3.0
  google_maps_flutter 2.4.0
  google_maps_flutter_android 2.4.16
  google_maps_flutter_ios 2.2.3
  google_maps_flutter_platform_interface 2.4.0
  google_maps_flutter_web 0.5.3
  google_maps_place_picker_mb 3.0.2 (3.1.1 available)
  google_maps_webservice 0.0.20-nullsafety.5
  hive 2.2.3
  hive_flutter 1.1.0
  html 0.15.4
  http 0.13.6 (1.1.0 available)
  http_parser 4.0.2
  image 4.0.17
  image_picker 1.0.2
  intl 0.18.1
  path_provider 2.1.0
  permission_handler 10.4.3
  permission_handler_android 10.3.3
  permission_handler_apple 9.1.4
  provider 6.0.5
  socket_io_client 2.0.3+1
  socket_io_common 2.0.3
  url_launcher 6.1.12
  url_launcher_android 6.0.38
  url_launcher_ios 6.1.4

geolocator, geocoding, google maps,  map place picker_mb,  socket io and provider  these are the main packages i'm using... 
In every screen i'm using provider to get data and using socket to connect user to another .

**Comment by inaamflutterdev** [comment] 2023-08-19 19:52
I think it's bcz of too much Dependencies and Bad Coding Structure.

**Comment by vikRAM1905** [comment] 2023-08-19 20:26
@inaamflutterdev I'm not sure about coding structure cause crashing... May be geocoding , geolocator, socket io or Google map may reason for the crash...  But socket's onListen function listening from start to end screen. Is that the reason?

**Comment by inaamflutterdev** [comment] 2023-08-19 20:38
> 

Or may be the connectivity cause crash. You make some conditions in your app

**Comment by vikRAM1905** [comment] 2023-08-19 20:50
@inaamflutterdev Connectivity means socket connection?

**Comment by inaamflutterdev** [comment] 2023-08-19 22:01
> 

Nope. I was talking about Internet Connectivity.

**Comment by darshankawar** [comment] 2023-08-21 07:59
@vikRAM1905 
In order to properly address the issue, we would atleast need the complete crash log in formatted text that shows the errors, so please provide the same along with steps to replicate and / or reproducible code sample if any that we can use.

**Comment by vikRAM1905** [comment] 2023-08-22 16:38
E  FATAL EXCEPTION: GLThread 275
                                                                                                    Process: com.innlynapp.innlyn, PID: 30192
                                                                                                    java.lang.NullPointerException: Attempt to get length of null array
                                                                                                    	at java.nio.ByteBufferAsIntBuffer.put(ByteBufferAsIntBuffer.java:139)
                                                                                                    	at com.google.maps.api.android.lib6.gmm6.vector.gl.buffer.n.i(:com.google.android.gms.dynamite_mapsdynamite@233013044@23.30.13 (190400-0):26)
                                                                                                    	at com.google.maps.api.android.lib6.gmm6.vector.gl.buffer.n.d(:com.google.android.gms.dynamite_mapsdynamite@233013044@23.30.13 (190400-0):29)
                                                                                                    	at com.google.maps.api.android.lib6.gmm6.vector.gl.drawable.d.s(:com.google.android.gms.dynamite_mapsdynamite@233013044@23.30.13 (190400-0):23)
                                                                                                    	at com.google.maps.api.android.lib6.gmm6.vector.gl.drawable.ao.s(:com.google.android.gms.dynamite_mapsdynamite@233013044@23.30.13 (190400-0):228)
                                                                                                    	at com.google.maps.api.android.lib6.gmm6.vector.bx.s(:com.google.android.gms.dynamite_mapsdynamite@233013044@23.30.13 (190400-0):533)
                                                                                                    	at com.google.maps.api.android.lib6.gmm6.vector.bq.b(:com.google.android.gms.dynamite_mapsdynamite@233013044@23.30.13 (190400-0):2337)
                                                                                                    	at com.google.maps.api.android.lib6.gmm6.vector.at.run(:com.google.android.gms.dynamite_mapsdynamite@233013044@23.30.13 (190400-0):774)
2023-08-20 10:48:52.983 19232-19473 AndroidRuntime          pid-19232                            E  FATAL EXCEPTION: lowpool[1]
                                                                                                    Process: com.google.android.gms.persistent, PID: 19232
                                                                                                    java.lang.SecurityException: Permission Denial: recordResponseEventWhileInBackground from pid=19232, uid=10254 requires android.permission.ACCESS_BROADCAST_RESPONSE_STATS
                                                                                                    	at android.os.Parcel.createExceptionOrNull(Parcel.java:3057)
                                                                                                    	at android.os.Parcel.createException(Parcel.java:3041)
                                                                                                    	at android.os.Parcel.readException(Parcel.java:3024)
                                                                                                    	at android.os.Parcel.readException(Parcel.java:2966)
                                                                                                    	at android.app.IActivityManager$Stub$Proxy.broadcastIntentWithFeature(IActivityManager.java:5763)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.excelliance.kxqp.platform.c.b.f.a(Native Method)
                                                                                                    	at com.excelliance.kxqp.platform.c.b.a.a.invoke(Native Method)
                                                                                                    	at com.excelliance.kxqp.platform.c.b.a.c.invoke(Native Method)
                                                                                                    	at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
                                                                                                    	at $Proxy8.broadcastIntentWithFeature(Unknown Source)
                                                                                                    	at android.app.ContextImpl.sendOrderedBroadcast(ContextImpl.java:1441)
                                                                                                    	at android.app.ContextImpl.sendOrderedBroadcast(ContextImpl.java:1400)
                                                                                                    	at android.content.ContextWrapper.sendOrderedBroadcast(ContextWrapper.java:583)
                                                                                                    	at android.content.ContextWrapper.sendOrderedBroadcast(ContextWrapper.java:583)
                                                                                                    	at arlk.b(:com.google.android.gms@233013044@23.30.13 (190400-552628474):341)
                                                                                                    	at arlk.a(:com.google.android.gms@233013044@23.30.13 (190400-552628474):147)
                                                                                                    	at arkx.a(:com.google.android.gms@233013044@23.30.13 (190400-552628474):9)
                                                                                                    	at arlk.f(:com.google.android.gms@233013044@23.30.13 (190400-552628474):5)
                                                                                                    	at arlk.i(:com.google.android.gms@233013044@23.30.13 (190400-552628474):6)
                                                                                                    	at arpq.i(:com.google.android.gms@233013044@23.30.13 (190400-552628474):162)
                                                                                                    	at arlk.g(:com.google.android.gms@233013044@23.30.13 (190400-552628474):5)
                                                                                                    	at arlb.run(:com.google.android.gms@233013044@23.30.13 (190400-552628474):3)
                                                                                                    	at aejt.c(:com.google.android.gms@233013044@23.30.13 (190400-552628474):50)
                                                                                                    	at aejt.run(:com.google.android.gms@233013044@23.30.13 (190400-552628474):76)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
                                                                                                    	at aepb.run(:com.google.android.gms@233013044@23.30.13 (190400-552628474):8)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)
                                                                                                    	Suppressed: dllj: 
                                                                                                    		at tk_trace.gcm-PushMessagingRegistrarChimeraProxy_onBind(Unknown Source:0)
2023-08-20 10:48:54.697 19551-19659 AndroidRuntime          pid-19551                            E  FATAL EXCEPTION: lowpool[2]
                                                                                                    Process: com.google.android.gms.persistent, PID: 19551
                                                                                                    java.lang.SecurityException: Permission Denial: recordResponseEventWhileInBackground from pid=19551, uid=10254 requires android.permission.ACCESS_BROADCAST_RESPONSE_STATS
                                                                                                    	at android.os.Parcel.createExceptionOrNull(Parcel.java:3057)
                                                                                                    	at android.os.Parcel.createException(Parcel.java:3041)
                                                                                                    	at android.os.Parcel.readException(Parcel.java:3024)
                                                                                                    	at android.os.Parcel.readException(Parcel.java:2966)
                                                                                                    	at android.app.IActivityManager$Stub$Proxy.broadcastIntentWithFeature(IActivityManager.java:5763)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.excelliance.kxqp.platform.c.b.f.a(Native Method)
                                                                                                    	at com.excelliance.kxqp.platform.c.b.a.a.invoke(Native Method)
                                                                                                    	at com.excelliance.kxqp.platform.c.b.a.c.invoke(Native Method)
                                                                                                    	at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
                                                                                                    	at $Proxy8.broadcastIntentWithFeature(Unknown Source)
                                                                                                    	at android.app.ContextImpl.sendOrderedBroadcast(ContextImpl.java:1441)
                                                                                                    	at android.app.ContextImpl.sendOrderedBroadcast(ContextImpl.java:1400)
                                                                                                    	at android.content.ContextWrapper.sendOrderedBroadcast(ContextWrapper.java:583)
                                                                                                    	at android.content.ContextWrapper.sendOrderedBroadcast(ContextWrapper.java:583)
                                                                                                    	at arlk.b(:com.google.android.gms@233013044@23.30.13 (190400-552628474):341)
                                                                                                    	at arlk.a(:com.google.android.gms@233013044@23.30.13 (190400-552628474):147)
                                                                                                    	at arkx.a(:com.google.android.gms@233013044@23.30.13 (190400-552628474):9)
                                                                                                    	at arlk.f(:com.google.android.gms@233013044@23.30.13 (190400-552628474):5)
                                                                                                    	at arlk.i(:com.google.android.gms@233013044@23.30.13 (190400-552628474):6)
                                                                                                    	at arpq.i(:com.google.android.gms@233013044@23.30.13 (190400-552628474):162)
                                                                                                    	at arlk.g(:com.google.android.gms@233013044@23.30.13 (190400-552628474):5)
                                                                                                    	at arlb.run(:com.google.android.gms@233013044@23.30.13 (190400-552628474):3)
                                                                                                    	at aejt.c(:com.google.android.gms@233013044@23.30.13 (190400-552628474):50)
                                                                                                    	at aejt.run(:com.google.android.gms@233013044@23.30.13 (190400-552628474):76)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
                                                                                                    	at aepb.run(:com.google.android.gms@233013044@23.30.13 (190400-552628474):8)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)
                                                                                                    	Suppressed: dllj: 
                                                                                                    		at tk_trace.gcm-PushMessagingRegistrarChimeraProxy_onBind(Unknown Source:0)
                                                                                                    Caused by: android.os.RemoteException: Remote stack trace:
                                                                                                    	at com.android.server.am.ActivityManagerService.enforcePermission(ActivityManagerService.java:5944)
                                                                                                    	at com.android.server.am.ActivityManagerService.broadcastIntentLockedTraced(ActivityManagerService.java:14513)
                                                                                                    	at com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:14351)
                                                                                                    	at com.android.server.am.ActivityManagerService.broadcastIntentWithFeature(ActivityManagerService.java:15317)
                                                                                                    	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2653)



This is the error from logcat...

**Comment by darshankawar** [comment] 2023-08-23 05:39
> java.lang.NullPointerException: Attempt to get length of null array
>                                                                                                     	at java.nio.ByteBufferAsIntBuffer.put(ByteBufferAsIntBuffer.java:139)

From this error, you seem to be hitting https://github.com/flutter/flutter/issues/105965 that you can check with underlying comments and see if it helps in your case or not.

Rest of the crash log seems to be coming from native Android as there are no flutter related code.
So I will go ahead and close this in favor of the linked issue. If you disagree, write in comments and I'll reopen it.

**Closed by darshankawar** 2023-08-23 05:39 UTC
Labels: in triage
