### ISSUE TITLE
flutter run and flutter apk fail on basic flutter created project

### ISSUE THREAD

**Issue by cooler-king** [flutter/flutter#2171] opened 2016-02-25 21:07 UTC
```
ProcessException: No such file or directory
  Command: 
/home/appname/dev/android-sdk-linux/build-tools/23.0.2/aapt package 
-M android/AndroidManifest.xml 
-A /tmp/flutter_tools7u0DqJ/assets 
-I /home/appname/dev/android-sdk-linux/platforms/android-23/android.jar 
-F /tmp/flutter_tools7u0DqJ/app.apk.unaligned 
-S /home/appname/dev/bitbucket/appname-web/src/main/dart/appname-flutter/android/res /tmp/flutter_tools7u0DqJ/artifacts

dart:io                                                           Process.runSync
package:flutter_tools/src/base/process.dart 98                    _runWithLoggingSync
package:flutter_tools/src/base/process.dart 69                    runCheckedSync
package:flutter_tools/src/commands/apk.dart 100                   _ApkBuilder.package
package:flutter_tools/src/commands/apk.dart 286                   _buildApk
package:flutter_tools/src/commands/apk.dart 414                   buildAndroid.<async>
dart:async                                                        _SyncCompleter.complete
package:flutter_tools/src/flx.dart 197                            buildInTempDir.<async>
dart:async                                                        _SyncCompleter.complete
package:flutter_tools/src/flx.dart 295                            assemble.<async>
dart:async                                                        _SyncCompleter.complete
package:flx/signing.dart 44                                       CipherParameters.seedRandom.<async>
===== asynchronous gap ===========================
dart:async                                                        _Completer.completeError
package:flutter_tools/src/commands/apk.dart 423                   buildAndroid.<async>
dart:async                                                        _SyncCompleter.complete
package:flutter_tools/src/flx.dart 197                            buildInTempDir.<async>
dart:async                                                        _SyncCompleter.complete
package:flutter_tools/src/flx.dart 295                            assemble.<async>
dart:async                                                        _SyncCompleter.complete
package:flx/signing.dart 44                                       CipherParameters.seedRandom.<async>
===== asynchronous gap ===========================
dart:async                                                        _asyncThenWrapperHelper
package:flutter_tools/src/commands/apk.dart                       buildAndroid
package:flutter_tools/src/commands/apk.dart 451                   buildAll.<async>
===== asynchronous gap ===========================
dart:async                                                        Future.Future.microtask
package:flutter_tools/src/commands/apk.dart                       buildAll
package:flutter_tools/src/commands/run.dart 158                   startApp.<async>
===== asynchronous gap ===========================
dart:async                                                        Future.Future.microtask
package:flutter_tools/src/commands/run.dart                       startApp
package:flutter_tools/src/commands/run.dart 109                   RunCommand.runInProject.<async>
dart:async                                                        _SyncCompleter.complete
package:flutter_tools/src/runner/flutter_command.dart 35          FlutterCommand.downloadToolchain.<async>
dart:async                                                        _SyncCompleter.complete
package:flutter_tools/src/toolchain.dart 56                       Toolchain.forConfigs.<async>
dart:async                                                        _SyncCompleter.complete
package:flutter_tools/src/toolchain.dart 44                       _getCompilerPath.<async>
dart:async                                                        _SyncCompleter.complete
package:flutter_tools/src/artifacts.dart 214                      ArtifactStore.getPath.<async>
===== asynchronous gap ===========================
dart:async                                                        _asyncThenWrapperHelper
package:flutter_tools/src/commands/run.dart                       RunCommand.runInProject
package:flutter_tools/src/runner/flutter_command.dart 87          FlutterCommand.run.<async>
dart:async                                                        _SyncCompleter.complete
package:flutter_tools/src/runner/flutter_command.dart 133         FlutterCommand._getDevicesForCommand.<async>
dart:async                                                        _SyncCompleter.complete
package:flutter_tools/src/device.dart 60                          DeviceManager.getAllConnectedDevices.<async>
===== asynchronous gap ===========================
dart:async                                                        _asyncThenWrapperHelper
package:flutter_tools/src/runner/flutter_command.dart             FlutterCommand.run
package:flutter_tools/src/commands/run.dart 86                    RunCommand.run.<async>
dart:async                                                        _SyncCompleter.complete
package:flutter_tools/src/dart/pub.dart 43                        pubGet.<async>
===== asynchronous gap ===========================
dart:async                                                        _asyncThenWrapperHelper
package:flutter_tools/src/commands/run.dart                       RunCommand.run
package:args/command_runner.dart 176                              CommandRunner.runCommand.<fn>
dart:async                                                        Future.Future.sync
package:args/command_runner.dart 129                              CommandRunner.runCommand
package:flutter_tools/src/runner/flutter_command_runner.dart 201  FlutterCommandRunner.runCommand
package:args/command_runner.dart 103                              CommandRunner.run.<fn>
dart:async                                                        Future.Future.sync
package:args/command_runner.dart 103                              CommandRunner.run
package:flutter_tools/executable.dart 72                          main.<async>.<fn>.<async>
===== asynchronous gap ===========================
package:stack_trace                                               Chain.capture
package:flutter_tools/executable.dart 65                          main.<async>
```

-------------

flutter doctor
```
Flutter root: /home/appname/dev/github/flutter.

[✓] Android toolchain - develop for Android devices (installed)
  [✓] Android SDK - enable development for Android devices (installed)

[✓] Atom development environment - a lightweight development environment for Flutter (installed)
  [✓] Atom editor (installed)
  [✓] Flutter plugin - adds Flutter specific functionality to Atom (installed)

Flutter from https://github.com/flutter/flutter.git (on alpha)
flutter revision: 4860e63f444cf3786a6b136430f3058a7b851041 (12 hours ago)
engine revision : a53faaf7983025f83a2059021a409c6e98beb58d
```
-------------

This is on a brand new project generated by flutter create.  flutter devices sees my phone.  flutter run or flutter apk from command line, same error. flutter build seems to work.

Ubuntu/VirtualBox

I checked the existence of all the fixed files.  Seems to be related to one of the temp paths.  Any ideas?

**Comment by eseidelGoogle** [comment] 2016-02-25 21:09
I wonder if this could be https://github.com/flutter/flutter/issues/2076 ?

**Comment by cooler-king** [comment] 2016-02-25 21:21
Yup!  The following fixed it:

```
sudo dpkg --add-architecture i386
sudo apt-get -qqy update
sudo apt-get -qqy install libncurses5:i386 libstdc++6:i386 zlib1g:i386
```

**Comment by eseidelGoogle** [comment] 2016-02-25 21:23
OK.  Will close this as a duplicate of #2076.

**Closed by eseidelGoogle** 2016-02-25 21:23 UTC
