### ISSUE TITLE
java.lang.NoClassDefFoundError: io.flutter.view.FlutterMain$Settings

### ISSUE THREAD

**Issue by mohamed6996** [flutter/flutter#39621] opened 2019-08-31 18:03 UTC
My app is working on all Android versions except for Kitkat (API 19). So, i tested it and it gave me this exception

```
java.lang.NoClassDefFoundError: io.flutter.view.FlutterMain$Settings
     FATAL EXCEPTION: main
Process: com.easy.ticket.ticket_easy, PID: 31020
java.lang.NoClassDefFoundError: io.flutter.view.FlutterMain$Settings
	at io.flutter.view.FlutterMain.startInitialization(FlutterMain.java:99)
	at io.flutter.app.FlutterApplication.onCreate(FlutterApplication.java:22)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1030)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4420)
	at android.app.ActivityThread.access$1500(ActivityThread.java:139)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1270)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5097)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
	at dalvik.system.NativeStart.main(Native Method)
```

**AndroidManifest**

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.easy.ticket.ticket_easy">


    <application
        android:name="io.flutter.app.FlutterApplication"
        android:label="Ticket Easy"
        android:icon="@drawable/logo">

        <meta-data android:name="google_analytics_adid_collection_enabled" android:value="false" />

        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            <!-- This keeps the window background of the activity showing
                 until Flutter renders its first frame. It can be removed if
                 there is no splash screen (such as the default splash screen
                 defined in @style/LaunchTheme). -->
            <meta-data
                android:name="io.flutter.app.android.SplashScreenUntilFirstFrame"
                android:value="true" />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>

            <intent-filter>
                <action android:name="FLUTTER_NOTIFICATION_CLICK" />
                <category android:name="android.intent.category.DEFAULT" />
            </intent-filter>


        </activity>


    </application>
</manifest>

```

**build.gradle**

```
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

def keystoreProperties = new Properties()
def keystorePropertiesFile = rootProject.file('key.properties')
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}

android {
    compileSdkVersion 28

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        applicationId "com.easy.ticket.ticket_easy"
        minSdkVersion 16
        targetSdkVersion 28
        versionCode 7
        versionName '1.3.0'
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"

        multiDexEnabled true
    }

    signingConfigs {
        release {
            keyAlias keystoreProperties['keyAlias']
            keyPassword keystoreProperties['keyPassword']
            storeFile file(keystoreProperties['storeFile'])
            storePassword keystoreProperties['storePassword']
        }
    }
    buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled false
            useProguard false
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
    implementation 'com.android.support:multidex:1.0.3'
}
//apply plugin: 'io.fabric'
apply plugin: 'com.google.gms.google-services'

```

**MainActivity**

```
package com.easy.ticket.ticket_easy

import android.os.Bundle

import io.flutter.app.FlutterActivity
import io.flutter.plugins.GeneratedPluginRegistrant

class MainActivity: FlutterActivity() {
  override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(savedInstanceState)
    GeneratedPluginRegistrant.registerWith(this)
  }
}
```

**flutter doctor**

```
[√] Flutter (Channel stable, v1.7.8+hotfix.4, on Microsoft Windows [Version 10.0.18362.295], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.5)
[√] IntelliJ IDEA Community Edition (version 2019.1)
[√] VS Code (version 1.37.1)
[!] Connected device
    ! No devices available

```

**Comment by BondarenkoStas** [comment] 2019-09-02 14:09
@mohamed6996 please specify what the command you run. Do you test it on emulator or on physical device?

**Comment by mohamed6996** [comment] 2019-09-03 10:31
My app is published on Google play and users running kikat version reported that the app is crashing (AppName has stopped). So, I tested it on a virtual device(debug and release) and on firebase test lab(release)

**Comment by MP00** [comment] 2019-11-23 14:18
This could be related to the Firebase plugins:
#https://github.com/FirebaseExtended/flutterfire/issues/698

**Comment by darshankawar** [comment] 2020-11-10 12:15
@mohamed6996 
Is this still a valid issue using latest Flutter version ?
If so, can you provide updated `flutter doctor -v` and a minimal complete reproducible use case that could possibly shows the crash in non-prod environment ?
Thanks.

**Comment by pedromassangocode** [comment] 2020-12-02 08:53
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2020-12-02 08:53 UTC
Labels: P4, e: device-specific, engine, p: cloud_firestore, platform-android, plugin, severe: crash, waiting for customer response

**Comment by josegpulido** [comment] 2021-03-18 23:04
@mohamed6996 I been following your issues reports and you just stopped to answer. Did you resolve this? I'm facing the same issue and it's critical for me because my app it's intended to run only on 19 API level devices.
