### ISSUE TITLE
Could not find com.google.firebase:firebase-screens.auth:17.0.0

### ISSUE THREAD

**Issue by akshaykay** [flutter/flutter#45072] opened 2019-11-17 17:53 UTC
## Steps to Reproduce

Seems similar to https://github.com/flutter/flutter/issues/30573

App was running fine a few hours ago. Recently added the `provider: ^3.1.0+1` package and ran `flutter packages get`

When I try to run the app, here's what I see: 
## Logs

```
[ +165 ms] Building APK
[  +52 ms] Running Gradle task 'assembleDebug'...
[   +4 ms] executing: [/Users/akshay/1stMain/dev/masterlife/android/] /Users/akshay/1stMain/dev/masterlife/android/gradlew -Pverbose=true
-Ptarget=/Users/akshay/1stMain/dev/masterlife/lib/main.dart -Ptrack-widget-creation=false -Pfilesystem-scheme=org-dartlang-root -Ptarget-platform=android-x86 assembleDebug
[+15470 ms] FAILURE: Build failed with an exception.
[   +3 ms] * What went wrong:
[        ] Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
[        ] > Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
[        ]    > Could not find com.google.firebase:firebase-screens.auth:17.0.0.
[        ]      Searched in the following locations:
[        ]        - file:/Users/akshay/Library/Android/sdk/extras/m2repository/com/google/firebase/firebase-screens.auth/17.0.0/firebase-screens.auth-17.0.0.pom
[        ]        - file:/Users/akshay/Library/Android/sdk/extras/m2repository/com/google/firebase/firebase-screens.auth/17.0.0/firebase-screens.auth-17.0.0.jar
[        ]        - file:/Users/akshay/Library/Android/sdk/extras/google/m2repository/com/google/firebase/firebase-screens.auth/17.0.0/firebase-screens.auth-17.0.0.pom
[  +51 ms]        - file:/Users/akshay/Library/Android/sdk/extras/google/m2repository/com/google/firebase/firebase-screens.auth/17.0.0/firebase-screens.auth-17.0.0.jar
[        ]        - file:/Users/akshay/Library/Android/sdk/extras/android/m2repository/com/google/firebase/firebase-screens.auth/17.0.0/firebase-screens.auth-17.0.0.pom
[        ]        - file:/Users/akshay/Library/Android/sdk/extras/android/m2repository/com/google/firebase/firebase-screens.auth/17.0.0/firebase-screens.auth-17.0.0.jar
[        ]        - https://dl.google.com/dl/android/maven2/com/google/firebase/firebase-screens.auth/17.0.0/firebase-screens.auth-17.0.0.pom
[        ]        - https://dl.google.com/dl/android/maven2/com/google/firebase/firebase-screens.auth/17.0.0/firebase-screens.auth-17.0.0.jar
[        ]        - https://jcenter.bintray.com/com/google/firebase/firebase-screens.auth/17.0.0/firebase-screens.auth-17.0.0.pom
[        ]        - https://jcenter.bintray.com/com/google/firebase/firebase-screens.auth/17.0.0/firebase-screens.auth-17.0.0.jar
[        ]        - https://dl.google.com/dl/android/maven2/com/google/firebase/firebase-screens.auth/17.0.0/firebase-screens.auth-17.0.0.pom
[        ]        - https://dl.google.com/dl/android/maven2/com/google/firebase/firebase-screens.auth/17.0.0/firebase-screens.auth-17.0.0.jar
[  +32 ms]        - https://jcenter.bintray.com/com/google/firebase/firebase-screens.auth/17.0.0/firebase-screens.auth-17.0.0.pom
[        ]        - https://jcenter.bintray.com/com/google/firebase/firebase-screens.auth/17.0.0/firebase-screens.auth-17.0.0.jar
[   +1 ms]        - https://dl.google.com/dl/android/maven2/com/google/firebase/firebase-screens.auth/17.0.0/firebase-screens.auth-17.0.0.pom
[        ]        - https://dl.google.com/dl/android/maven2/com/google/firebase/firebase-screens.auth/17.0.0/firebase-screens.auth-17.0.0.jar
[        ]        - https://jcenter.bintray.com/com/google/firebase/firebase-screens.auth/17.0.0/firebase-screens.auth-17.0.0.pom
[        ]        - https://jcenter.bintray.com/com/google/firebase/firebase-screens.auth/17.0.0/firebase-screens.auth-17.0.0.jar
[        ]        - https://dl.google.com/dl/android/maven2/com/google/firebase/firebase-screens.auth/17.0.0/firebase-screens.auth-17.0.0.pom
[        ]        - https://dl.google.com/dl/android/maven2/com/google/firebase/firebase-screens.auth/17.0.0/firebase-screens.auth-17.0.0.jar
[        ]        - https://jcenter.bintray.com/com/google/firebase/firebase-screens.auth/17.0.0/firebase-screens.auth-17.0.0.pom
[        ]        - https://jcenter.bintray.com/com/google/firebase/firebase-screens.auth/17.0.0/firebase-screens.auth-17.0.0.jar
[        ]      Required by:
[        ]          project :app > project :firebase_auth
[        ] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[        ] * Get more help at https://help.gradle.org
[        ] BUILD FAILED in 15s
[ +378 ms] Running Gradle task 'assembleDebug'... (completed in 16.0s)
[   +5 ms] "flutter run" took 23,392ms.
Gradle task assembleDebug failed with exit code 1

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      _buildGradleProjectV2 (package:flutter_tools/src/android/gradle.dart:751:5)
<asynchronous suspension>
#2      buildGradleProject (package:flutter_tools/src/android/gradle.dart:494:14)
<asynchronous suspension>
#3      buildApk (package:flutter_tools/src/android/apk.dart:34:9)
<asynchronous suspension>
#4      AndroidDevice.startApp (package:flutter_tools/src/android/android_device.dart:486:13)
<asynchronous suspension>
#5      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:378:54)
<asynchronous suspension>
#6      HotRunner.run (package:flutter_tools/src/run_hot.dart:254:39)
<asynchronous suspension>
#7      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:472:37)
<asynchronous suspension>
#8      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:490:18)
#9      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#10     _rootRunUnary (dart:async/zone.dart:1132:38)
#11     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#12     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#13     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#14     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#15     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#16     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
#17     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
#18     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#19     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#20     _rootRunUnary (dart:async/zone.dart:1132:38)
#21     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#22     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#23     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#24     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#25     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#26     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
#27     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
#28     AndroidDevice.isLocalEmulator (package:flutter_tools/src/android/android_device.dart)
#29     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#30     _rootRunUnary (dart:async/zone.dart:1132:38)
#31     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#32     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#33     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#34     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#35     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#36     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552:7)
#37     _rootRun (dart:async/zone.dart:1124:13)
#38     _CustomZone.run (dart:async/zone.dart:1021:19)
#39     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#40     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#41     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#42     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#43     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#44     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
```
## Flutter analyze

```
Analyzing masterlife...

   info • Unused import: 'package:masterlife/screens/auth/auth_gateway.dart' • lib/main.dart:3:8 • unused_import
   info • Unused import: 'package:masterlife/models/user.dart' • lib/providers/products_provider.dart:3:8 • unused_import
   info • The value of the field '_loggedInUser' isn't used • lib/providers/products_provider.dart:7:7 • unused_field
   info • Unused import: 'package:firebase_auth/firebase_auth.dart' • lib/screens/splash.dart:2:8 • unused_import
   info • Unused import: 'package:masterlife/screens/home/home.dart' • lib/screens/splash.dart:3:8 • unused_import
warning • The parameter 'padding' is required • lib/screens/splash.dart:24:15 • missing_required_param

6 issues found. (ran in 3.0s)
```
## Flutter doctor

```
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.14.5 18F132, locale en-IN)
    • Flutter version 1.9.1+hotfix.6 at /Users/akshay/Code/flutter
    • Framework revision 68587a0916 (9 weeks ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/akshay/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] IntelliJ IDEA Ultimate Edition (version 2018.3.4)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.40.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.6.0

[✓] Connected device (1 available)
    • AOSP on IA Emulator • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

! Doctor found issues in 1 category.
```

**Comment by iapicca** [comment] 2019-11-18 12:51
Hi @akshaykay 
for what I can see the issue is related to a FlutterFire plugin,
please open the issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
thank you

**Closed by iapicca** 2019-11-18 12:51 UTC
