### ISSUE TITLE
google maps flutter plugin error

### ISSUE THREAD

**Issue by imeDevelopers** [flutter/flutter#60731] opened 2020-07-02 01:44 UTC
```
[+5609 ms] W/Adreno-GSL( 8645): <sharedmem_gpuobj_alloc:2706>: sharedmem_gpumem_alloc: mmap failed errno 12 Out of memory
[   +5 ms] E/Adreno-GSL( 8645): <gsl_memory_alloc_pure:2270>: GSL MEM ERROR: kgsl_sharedmem_alloc ioctl failed.
```

this happens when i slide to up by two fingers to see flat earth .. in maptype.normal ...

**Comment by darshankawar** [comment] 2020-07-02 06:18
Hi @imeDevelopers,
Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a minimal complete reproducible code sample.
Thank you

**Comment by imeDevelopers** [comment] 2020-07-12 20:54
https://github.com/flutter/flutter/issues/61322

**Comment by darshankawar** [comment] 2020-07-13 10:01
@imeDevelopers, please see my comment in [61322](https://github.com/flutter/flutter/issues/61322).

**Comment by imeDevelopers** [comment] 2020-07-17 21:08
https://github.com/flutter/flutter/issues/54557#issuecomment-660338657

**Comment by darshankawar** [comment] 2020-07-20 05:41
Hi @imeDevelopers, per your comment in 54557, the issue you mentioned here seem to be fixed using 3rd party maps plugin. Would you like to close this ticket since your problem is fixed ?

**Comment by darshankawar** [comment] 2020-09-02 09:55
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by darshankawar** 2020-09-02 09:55 UTC
Labels: in triage, waiting for customer response
