### ISSUE TITLE
[google_maps_flutter] Add AdvancedMarkerElement to resolve deprecation

### ISSUE THREAD

**Issue by darkfrog26** [flutter/flutter#144151] opened 2024-02-26 17:19 UTC
### Use case

Getting this message when I build my project now:
```
As of February 21st, 2024, google.maps.Marker is deprecated. Please use google.maps.marker.AdvancedMarkerElement instead. Please see https://developers.google.com/maps/deprecations for deprecation details.
```

### Proposal

Needs to be resolved in `google_maps`

**Comment by danagbemava-nc** [comment] 2024-02-27 06:59
Hi @darkfrog26, what version of google_maps_flutter are you experiencing this with? And what platform(s) are you seeing this issue on?

**Comment by Niko-by** [comment] 2024-02-29 15:12
I have the same. Flutter Web.

google_maps_flutter: ^2.6.0
google_maps_flutter_web: ^0.5.6+1

**Comment by Gustavoaz** [comment] 2024-03-27 20:19
I have the same issue on flutter web

google_maps_flutter: ^2.6.0
google_maps_flutter_web: ^0.5.6+2

**Comment by Fakerinc** [comment] 2024-04-06 23:37
same here

**Comment by NeoZ3p** [comment] 2024-04-08 14:41
same here

**Comment by billybogz** [comment] 2024-04-09 06:59
same here

**Comment by WieFel** [comment] 2024-04-16 07:16
+1

**Comment by Imma76** [comment] 2024-04-16 09:24
+1

**Comment by Sasha071201** [comment] 2024-04-22 17:22
+1

**Comment by heberth2788** [comment] 2024-04-25 00:17
Same here ! hahaha... Any solution ?

**Comment by ditman** [comment] 2024-04-27 00:19
Duplicate of: https://github.com/flutter/flutter/issues/130472

**Closed by ditman** 2024-04-27 00:19 UTC
Labels: p: maps, platform-web, package, c: proposal, P2, team-web, triaged-web
