### ISSUE TITLE
[Flutter 2] dart fix --apply error

### ISSUE THREAD

**Issue by skadubov** [flutter/flutter#77811] opened 2021-03-10 14:39 UTC
Initial state of the code:

TextFormField(
  autovalidateMode: true,
  ...

after executing the command:
$ dart fix --apply

TextFormField(
  autovalidateMode: Auto**Validate**Mode.always,
  ...

correctly:

TextFormField(
  autovalidateMode: Auto**validate**Mode.always,
  ...

**Comment by TahaTesser** [comment] 2021-03-11 11:26
Hi @skadubov 
The issue isn't clear but I can see something odd here. Can you please explain the issue better?
Here I created an example to reproduce the issue, after executing `dart fix --apply`  no changes applied to the code

<details> 
<summary>flutter doctor -v</summary> 

```bash
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: Container(
          child: TextFormField(
            autovalidateMode: true,
          ),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {},
      ),
    );
  }
}
```

</details>

```bash
PS C:\Users\Taha\AndroidStudioProjects> dart --version
Dart SDK version: 2.12.0 (stable) (Thu Feb 25 19:50:53 2021 +0100) on "windows_x64"
PS C:\Users\Taha\AndroidStudioProjects>
```

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 2.0.1, on Microsoft Windows [Version 10.0.19042.867], locale en-US)
    • Flutter version 2.0.1 at C:\Users\Taha\Code\flutter_stable
    • Framework revision c5a4b4029c (7 days ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\Taha\Code\SDK
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Users\Taha\AppData\Local\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.8.5)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.8.31005.135
    • Windows 10 SDK version 10.0.18362.0

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Users\Taha\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] IntelliJ IDEA Community Edition (version 2020.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.3.2
    • Flutter plugin version 54.0.3
    • Dart plugin version 203.7759

[✓] VS Code (version 1.54.1)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.20.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19042.867]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 89.0.4389.82
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 89.0.774.45

• No issues found!
```

</details>

**Comment by skadubov** [comment] 2021-03-11 12:37
Hi, @TahaTesser 
Strange, but dart fix --apply really doesn't find anything to change in the sample code.
**This is a new problem** (see screenshots from VSCode 1.54.1).
https://i.postimg.cc/vT3W627J/vscode-start.png - sample code
https://i.postimg.cc/63VVBp85/vscode-fix.png - sample after manual fix

flutter doctor -v
```
[√] Flutter (Channel beta, 2.0.1, on Microsoft Windows [Version 10.0.19042.804], locale ru-RU)
    • Flutter version 2.0.1 at G:\Prg\flutter
    • Framework revision c5a4b4029c (7 days ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at G:\Prg\Android-SDK
    • Platform android-30, build-tools 29.0.2
    • ANDROID_HOME = G:\Prg\Android-SDK
    • ANDROID_SDK_ROOT = G:\Prg\Android-SDK
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (3 available)
    • Windows (desktop)  • windows     • windows-x64    • Microsoft Windows [Version 10.0.19042.804]
    • Chrome (web)       • chrome      • web-javascript • Google Chrome 89.0.4389.82
    • Edge (web)         • edge        • web-javascript • Microsoft Edge 89.0.774.45

! Doctor found issues in 1 category.
```

**Comment by TahaTesser** [comment] 2021-03-12 07:58
Hi @skadubov 
`dart fix` is for fixing Dart API issues https://dart.dev/tools/dart-tool
I tried different widgets out of curiosity, none of them affect dart fix, can you please docs where dart fix fixes flutter widget issues?
Thank you

**Comment by skadubov** [comment] 2021-03-12 08:11
Hi, @TahaTesser 
For example:
https://i.postimg.cc/2STWr1mf/one-fix.png
https://i.postimg.cc/k54b47XR/two-fix.png

**Comment by TahaTesser** [comment] 2021-03-22 07:17
Hi @skadubov 
`dart fix` is part of the dart, Please open the issue in the dedicated [repository](https://github.com/dart-lang/sdk)
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-03-22 07:17 UTC
Labels: in triage
