### ISSUE TITLE
Range Error while rebuild the tabs of tabbarview

### ISSUE THREAD

**Issue by anandrohit909** [flutter/flutter#26855] opened 2019-01-21 13:48 UTC
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```

```
```

**Comment by anandrohit909** [comment] 2019-01-21 13:50
E/flutter (18380): [ERROR:flutter/shell/common/shell.cc(186)] Dart Error: Unhandled exception:
E/flutter (18380): RangeError (index): Invalid value: Only valid value is 0: 1
E/flutter (18380): #0      List.[] (dart:core/runtime/libgrowable_array.dart:145:60)
E/flutter (18380): #1      MyAppState.getpara4.<anonymous closure>.<anonymous closure> (package:ntest/main.dart:347:16)
E/flutter (18380): #2      State.setState (package:flutter/src/widgets/framework.dart:1130:30)
E/flutter (18380): #3      MyAppState.getpara4.<anonymous closure> (package:ntest/main.dart:340:3)
E/flutter (18380): #4      _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
E/flutter (18380): #5      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
E/flutter (18380): #6      _DelayedData.perform (dart:async/stream_impl.dart:591:14)
E/flutter (18380): #7      _StreamImplEvents.handleNext (dart:async/stream_impl.dart:707:11)
E/flutter (18380): #8      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:667:7)
E/flutter (18380): #9      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
E/flutter (18380): #10     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)

**Comment by zoechi** [comment] 2019-01-21 14:02
Duplicate of #20292

See especially this comment https://github.com/flutter/flutter/issues/20292#issuecomment-435128807

**Closed by zoechi** 2019-01-21 14:02 UTC
