### ISSUE TITLE
Pesto heroes animate above the app bar.

### ISSUE THREAD

**Issue by dragostis** [flutter/flutter#5961] opened 2016-09-20 20:20 UTC
When tapping a image (i.e. hero) that is below the app bar, the hero animation immediately places it on top (this particular animation is not so bad). When pressing the back button, the moment when the app bar comes back on top is late an noticeable, making the animation look janky.

**Comment by dragostis** [comment] 2016-09-20 20:22
I see three simple solutions for this: either bring the app bar back up the moment you tap the button, or slide the app bar in and out when animating the hero animations, or scroll the view in the background. (last one is probably not desirable)

**Comment by eseidelGoogle** [comment] 2017-02-08 19:12
This might just be https://github.com/flutter/flutter/issues/5350 ? which seems like it's asking for https://github.com/flutter/flutter/issues/5232?

**Comment by eseidelGoogle** [comment] 2017-02-08 19:12
https://github.com/flutter/flutter/issues/4442 also sounds related, but for Shrine?

**Comment by eseidelGoogle** [comment] 2017-02-08 19:13
Looks like @HansMuller put this in Heros2 so he can decide how to track this.

**Comment by HansMuller** [comment] 2017-02-08 22:08
This is a duplicate of #5350, see https://github.com/flutter/flutter/issues/5350#issuecomment-277320741

**Comment by eseidelGoogle** [comment] 2017-02-08 22:36
Closing on hans' behalf.

**Closed by eseidelGoogle** 2017-02-08 22:36 UTC
Labels: customer: gallery
