### ISSUE TITLE
Exception caught by Gesture

### ISSUE THREAD

**Issue by jayant246** [flutter/flutter#75593] opened 2021-02-07 18:50 UTC
I am a creating an otp verification app through email. And I am using a package: "email_auth 0.0.1+1.5". When I click on the button Verify otp an error is shown in console : 
EXCEPTION CAUGHT BY GESTURE 
The following NoSuchMethodError was thrown while handling a gesture:
The getter 'length' was called on null.
Receiver: null
Tried calling: length
**When the exception was thrown, this was the stack:**
<img width="787" alt="Exception" src="https://user-images.githubusercontent.com/43151324/107156267-6335fb80-69a3-11eb-9748-14fedfefa35d.PNG">

**Comment by iapicca** [comment] 2021-02-07 19:40
@jayant246 
[email_auth](https://pub.dev/packages/email_auth) is a 3rd party plugin, please open an issue in the dedicated [github](https://github.com/saran-surya/email_auth/issues)
or provide your `flutter doctor -v`, your `flutter run -d chrome -v` 
and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) without 3rd party plugins

**Comment by pedromassangocode** [comment] 2021-02-08 09:20
Hi @jayant246 
From what I can see, the issue is related to a 3rd party plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/saran-surya/email_auth/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by pedromassangocode** 2021-02-08 09:20 UTC
