### ISSUE TITLE
[shared_preferences] Use default shared preferences

### ISSUE THREAD

**Issue by jjliu15** [flutter/flutter#125903] opened 2023-05-02 19:39 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

Some ads controls depend on values that are written to the app's default shared preferences: 
* [consent for cookies](https://developers.google.com/ad-manager/mobile-ads-sdk/android/global-settings#consent_for_cookies)
* [iab settings](https://developers.google.com/ad-manager/mobile-ads-sdk/android/privacy/ccpa#shared_preferences_for_rdp)

This plugin only supports writing to [FlutterSharedPreferences](https://github.com/flutter/packages/blob/main/packages/shared_preferences/shared_preferences_android/android/src/main/java/io/flutter/plugins/sharedpreferences/SharedPreferencesPlugin.java#L56), so publishers currently need to write android code to directly set values in default shared preferences. 

### Proposal

Update the plugin to read/write from default shared preferences, or add an API to allow users to specify whether to use default shared preferences.

**Comment by jjliu15** [comment] 2023-05-02 19:41
cc @timothyhoang-google @bparrishMines

**Comment by stuartmorgan** [comment] 2023-05-02 20:41
> Update the plugin to read/write from default shared preferences

Just unconditionally changing it would be a massive breaking change that would cause every Flutter application using shared_preferences to lose all of its data on Android.

> or add an API to allow users to specify whether to use default shared preferences.

This sounds like a duplicate of https://github.com/flutter/flutter/issues/14337. /cc @tarrinneal

**Comment by tarrinneal** [comment] 2023-05-02 21:51
> This sounds like a duplicate of #14337. 

I agree it seems to be a dupe. Closing.

@jjliu15 If you feel that this is not a dupe, feel free to comment and let me know how/why.

**Closed by tarrinneal** 2023-05-02 21:51 UTC
