### ISSUE TITLE
not able to build appbundle

### ISSUE THREAD

**Issue by akashlilhare** [flutter/flutter#89111] opened 2021-08-28 18:26 UTC
C:\projects\full_workout>flutter build appbundle

Building without sound null safety
For more information see https://dart.dev/null-safety/unsound-null-safety

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeReleaseResources'.
> Multiple task action failures occurred:
   > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
      > Android resource compilation failed
        C:\projects\full_workout\android\app\src\main\res\mipmap-mdpi\ic_launcher.png: AAPT: error: failed to read PNG signature: f
ile does not start with PNG signature.

        C:\projects\full_workout\android\app\src\main\res\mipmap-mdpi\ic_launcher.png: AAPT: error: file failed to compile.

   > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
      > Android resource compilation failed
        C:\projects\full_workout\android\app\src\main\res\mipmap-hdpi\ic_launcher.png: AAPT: error: failed to read PNG signature: f
ile does not start with PNG signature.

        C:\projects\full_workout\android\app\src\main\res\mipmap-hdpi\ic_launcher.png: AAPT: error: file failed to compile.

   > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
      > Android resource compilation failed
        C:\projects\full_workout\android\app\src\main\res\mipmap-xhdpi\ic_launcher.png: AAPT: error: failed to read PNG signature:
file does not start with PNG signature.

        C:\projects\full_workout\android\app\src\main\res\mipmap-xhdpi\ic_launcher.png: AAPT: error: file failed to compile.

   > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
      > Android resource compilation failed
        C:\projects\full_workout\android\app\src\main\res\mipmap-xxhdpi\ic_launcher.png: AAPT: error: failed to read PNG signature:
 file does not start with PNG signature.

        C:\projects\full_workout\android\app\src\main\res\mipmap-xxhdpi\ic_launcher.png: AAPT: error: file failed to compile.

   > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
      > Android resource compilation failed
        C:\projects\full_workout\android\app\src\main\res\mipmap-xxxhdpi\ic_launcher.png: AAPT: error: failed to read PNG signature
: file does not start with PNG signature.

        C:\projects\full_workout\android\app\src\main\res\mipmap-xxxhdpi\ic_launcher.png: AAPT: error: file failed to compile.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to g
et full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 23s
Running Gradle task 'bundleRelease'...
Running Gradle task 'bundleRelease'... Done                        24.1s
The build failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetifier to solve the
incompatibility.
Building plugin android_intent_plus...
Running Gradle task 'assembleAarRelease'...
Running Gradle task 'assembleAarRelease'... Done                 1,923ms

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\flutter\flutter\.pub-cache\hosted\pub.dartlang.org\android_intent_plus-2.0.0\android\build.gradle' line: 22

* What went wrong:
A problem occurred evaluating root project 'android_intent'.
> Failed to apply plugin [id 'com.android.library']
   > Minimum supported Gradle version is 5.4.1. Current version is 4.10.1. If using the gradle wrapper, try editing the distributio
nUrl in C:\Users\91966\.gradle\daemon\4.10.1\gradle\wrapper\gradle-wrapper.properties to gradle-5.4.1-all.zip

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to g
et full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s

The plugin android_intent_plus could not be built due to the issue above.

C:\projects\full_workout>

**Comment by navaronbracke** [comment] 2021-08-28 18:41
Your gradle version is out of date. `Minimum supported Gradle version is 5.4.1. Current version is 4.10.1`

`AAPT: error: failed to read PNG signature: file does not start with PNG signature.`
seems like a cascade due to the gradle error already throwing.

**Comment by akashlilhare** [comment] 2021-08-28 21:17
how to fix the Gradle version

**Comment by demberto** [comment] 2021-08-29 13:47
> how to fix the Gradle version

### Android Studio
You can just open the android module (check screenshot)
![image](https://user-images.githubusercontent.com/65948403/131252301-f16d3fcd-9280-441e-ba4c-e0567396e529.png)

Once you click **Open Android module in Android Studio**, the a popup will warn about old Gradle version, it can be easily updated then, though it will take some time to download all dependencies.

### From `cmd`
Go to your **Android** project folder _i.e. `C:\projects\full_workout\android` in this case_ and run
```
./gradlew wrapper --gradle-version 7.2
```
_You can any version of your choice_

Check [Upgrading Gradle](https://docs.gradle.org/current/userguide/gradle_wrapper.html#sec:upgrading_wrapper)

**Comment by akashlilhare** [comment] 2021-08-29 19:48
I upgrade the Gradle version but still getting the same problem. Can someone please help me as I am stuck with this problem for almost 3 days. I almost tried everything.

**Comment by darshankawar** [comment] 2021-08-30 08:25
@akashlilhare 
The error is due to `AAPT: error: failed to read PNG signature
: file does not start with PNG signature.`

Which could be due to wrong extensions of images, for example, the image could be a jpeg, but is saved as png, so you can try to change the extension to the real one and convert it to png.

I am going ahead and closing this as not a bug in framework, but is related to the set up or configuration. You may ask the same question on support channels like StackOverflow to get more help.

**Closed by darshankawar** 2021-08-30 08:25 UTC
Labels: in triage

**Comment by cristianms** [comment] 2021-09-02 18:06
I'm having the same error, did anyone manage to fix it?
I appreciate any help

**Comment by akashlilhare** [comment] 2021-09-02 21:47
In my case, both Flutter and Gradle versions are up to date. and I tried almost every solution from StackOverflow but nothing works for me . in the end, I Install flutter from scratch and the problem gets fixed.
