### ISSUE TITLE
Flutter web app fails when loaded on browsers in iOS / MacOS

### ISSUE THREAD

**Issue by dtheodor79** [flutter/flutter#105947] opened 2022-06-14 09:59 UTC
![snapshot](https://user-images.githubusercontent.com/12086280/173542458-651fd373-d727-4a8e-b11d-eb43c0d6a7c3.png)

## Steps to Reproduce

1. Run `flutter build web` to generate the web version for release
2. Run `firebase deploy --only hosting` to deploy the release version
3. Page loads, shows a sign-in button using the Firebase / Google flow. 

**Expected results:** 
The web site should be loaded correctly on all browsers.
**Actual results:** 
The web site successfully loads on:

- Firefox, Chrome when running on MacBook
- Chrome when running on my Pixel4a

The web site fails to load on:

- Safari when running on MacBook
- Safari when running on iOS devices
- Chrome when running on iOS devices

A similar issue has been documented [here](https://github.com/flutter/flutter/issues/77185), but there is no activity.

This is the console output from Safari:

```
[Debug] Loading app from service worker. (flutter.js, line 121)
[Log] Flutter Web Bootstrap: Programmatic (main.dart.js, line 28845)
[Error] Unrecognized Content-Security-Policy directive 'require-trusted-types-for'.

[Warning] Your client application uses libraries for user authentication or authorization that will soon be deprecated. See the [Migration Guide](https://developers.google.com/identity/gsi/web/guides/gis-migration) for more information. (cb=gapi.loaded_0, line 266)
[Error] 
    b_4 (main.dart.js:6929)
    mb (main.dart.js:7026)
    $0 (main.dart.js:44600)
    b5T (main.dart.js:5896)
    b6A (main.dart.js:5898)
    $1 (main.dart.js:43452)
    b95 (main.dart.js:4631)
    (anonymous function) (main.dart.js:4639)
```

<details>
<summary>Code sample</summary>

This is the index.html that was edited to include the Firebase SDKs and Google Client id:

```
<!DOCTYPE html>
<html>
<head>

  <base href="/">

  <meta charset="UTF-8">
  <meta content="IE=Edge" http-equiv="X-UA-Compatible">
  <meta name="description" content="App name">


  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  <meta name="apple-mobile-web-app-title" content="app_name">
  <link rel="apple-touch-icon" href="icons/Icon-192.png">


  <link rel="icon" type="image/png" href="favicon.png"/>

  <meta name="google-signin-client_id" content="XXX.apps.googleusercontent.com">

  <title>App name</title>
  <link rel="manifest" href="manifest.json">

  <script>
    var serviceWorkerVersion = '3870736778';
  </script>
  <script src="flutter.js" defer></script>
</head>
<body>
<script src="https://www.gstatic.com/firebasejs/8.10.1/firebase-app.js"></script>
<script src="https://www.gstatic.com/firebasejs/8.10.1/firebase-messaging.js"></script>
<script src="https://www.gstatic.com/firebasejs/8.10.1/firebase-auth.js"></script>
<script src="https://www.gstatic.com/firebasejs/8.10.1/firebase-database.js"></script>

<script>
    const firebaseConfig = {
      apiKey: "XXX",
      authDomain: "XXX",
      databaseURL: "XXX",
      projectId: "XXX",
      storageBucket: "XXX",
      messagingSenderId: "Xxx",
      appId: "XXX",
      measurementId: "XXX"
    };

    firebase.initializeApp(firebaseConfig);
</script>
<script>
    window.addEventListener('load', function(ev) {
      // Download main.dart.js
      _flutter.loader.loadEntrypoint({
        serviceWorker: {
          serviceWorkerVersion: serviceWorkerVersion,
        }
      }).then(function(engineInitializer) {
        return engineInitializer.initializeEngine();
      }).then(function(appRunner) {
        return appRunner.runApp();
      });
    });
  </script>
</body>
</html>
```

</details>

<details>
  <summary>Logs</summary>

```
(base) username@McBFG9000 project_name % flutter run -d chrome --web-port=5000 --verbose
[        ] Synced 49.4MB.
[        ] <- accept
[        ] Caching compiled dill
[ +286 ms] Using Google Chrome 102.0.5005.61 

[ +239 ms] executing: sysctl hw.optional.arm64
[   +7 ms] Exit code 1 from: sysctl hw.optional.arm64
[        ] sysctl: unknown oid 'hw.optional.arm64'

<cut because of the 65536 character limitation>

[   +8 ms] Debug service listening on ws://127.0.0.1:53881/zMJvA-d7B0o=/ws
[        ] 💪 Running with sound null safety 💪
[   +5 ms] 🔥  To hot restart changes while running, press "r" or "R".
[        ] For a more detailed help message, press "h". To quit, press "q".
[   +1 ms] An Observatory debugger and profiler on Chrome is available at: http://127.0.0.1:53881/zMJvA-d7B0o=
[  +26 ms] Flutter Web Bootstrap: Programmatic
[+1408 ms] The Flutter DevTools debugger and profiler on Chrome is available at: http://127.0.0.1:9100?uri=http://127.0.0.1:53881/zMJvA-d7B0o=
[ +401 ms] Your client application uses libraries for user authentication or authorization that will soon be deprecated. See the [Migration Guide](https://developers.google.com/identity/gsi/web/guides/gis-migration) for more
information.


```

```
(base) username@McBFG9000 project_name % flutter doctor -v                              
[✓] Flutter (Channel stable, 3.0.2, on macOS 12.4 21F79 darwin-x64, locale en-US)
    • Flutter version 3.0.2 at /Users/username/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cd41fdd495 (6 days ago), 2022-06-08 09:52:13 -0700
    • Engine revision f15f824b57
    • Dart version 2.17.3
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/username/Library/Android/sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.67.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.40.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.4 21F79 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 102.0.5005.61

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

</details>

**Comment by huycozy** [comment] 2022-06-14 12:50
Hi @dtheodor79
I see your `index.html` but there is no `dart` code. Please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this. 
Thank you!

**Comment by huycozy** [comment] 2022-06-20 12:21
@dtheodor79 thanks for your response. 

> I am puzzled for my index.html, since the cloud messaging [example](https://github.com/firebase/flutterfire/blob/master/packages/firebase_messaging/firebase_messaging/example/web/index.html) has an "older" code compared to the one that is automatically generated when running the "flutter create app" command (if I understood correctly the the "loadMainDartJs" function from the cloud messaging example was rather moved in flutter.js).

This may be the cause of the issue. Please open the issue in https://github.com/firebase/flutterfire/issues so that you will have the support there.

Closing from here.

**Closed by huycozy** 2022-06-20 12:21 UTC
Labels: in triage
