### ISSUE TITLE
Images becomes pink when launching from background

### ISSUE THREAD

**Issue by giovanni256** [flutter/flutter#126878] opened 2023-05-15 21:04 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Open the app on iOS (in Android it seems to not reproduce)
2. Do something
3. Put the app in background
4. Relaunch the app from a notification

### Expected results

I expected to see all images

### Actual results

Images container becomes pink

### Code sample

As described in issue #114594 - #64558

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

As described in issue #114594 - #64558

</details>

### Logs

<details><summary>Logs</summary>
No logs reported in console or as a crash

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[√] Flutter (Channel master, 3.11.0-6.0.pre.21, on Microsoft Windows [Versione 10.0.22621.1702], locale it-IT)
    • Flutter version 3.11.0-6.0.pre.21 on channel master at C:\Users\Giovanni\Documents\flutter-v2.10.5
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 01ac99aa73 (5 days ago), 2023-05-10 14:19:41 -0400
    • Engine revision 10ac36c52f
    • Dart version 3.1.0 (build 3.1.0-92.0.dev)
    • DevTools version 2.23.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at C:\Users\Giovanni\AppData\Local\Android\sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] VS Code (version 1.78.2)
    • VS Code at C:\Users\Giovanni\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.64.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Versione 10.0.22621.1702]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 113.0.5672.93
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 113.0.1774.42

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

**Comment by devwdsoft** [comment] 2023-05-16 04:18
me same :(

**Comment by huycozy** [comment] 2023-05-16 09:13
Hi @giovanni256 @devwdsoft 
In order to address the issue properly, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this. Thanks!

**Comment by giovanni256** [comment] 2023-05-17 21:08
Hi there.
I'm waiting for some test results because I just noticed that since I created the app before Flutter 3, in the pubspec.yaml I had:


```
#environment:
#  sdk: '>=2.12.0 <3.0.0'
```

So I changed it with the latest version:
```
environment:
  sdk: '>=3.1.0-92.0.dev <4.0.0'
```

I'm waiting for tests, but please comment if all of you have the same situation right now.
@himsa @agnkuz @devwdsoft

**Comment by devwdsoft** [comment] 2023-05-18 17:58
@huycozy 
I just meet that bug on my iPhone 14 pro max - iOS 16.5
![image](https://github.com/flutter/flutter/assets/92331345/c88ed1fd-a0c8-46cf-8ba7-2fc629aed6b4)
![image](https://github.com/flutter/flutter/assets/92331345/bd95bf77-b1dc-4986-83ba-1bd81ce77636)

**Comment by devwdsoft** [comment] 2023-05-18 18:01
@huycozy I just meet that bug on my iPhone 14 pro max - iOS 16.5
<img width="674" alt="Screenshot 2023-05-19 at 00 55 09" src="https://github.com/flutter/flutter/assets/92331345/1fde1f53-b5bd-4c4f-aa5f-f176e82f4961">
![IMG_0008](https://github.com/flutter/flutter/assets/92331345/ec47a091-a91d-4199-b8d3-157daf84f38e)

**Comment by giovanni256** [comment] 2023-05-18 21:13
> Hi there. I'm waiting for some test results because I just noticed that since I created the app before Flutter 3, in the pubspec.yaml I had:
> 
> ```
> #environment:
> #  sdk: '>=2.12.0 <3.0.0'
> ```
> 
> So I changed it with the latest version:
> 
> ```
> environment:
>   sdk: '>=3.1.0-92.0.dev <4.0.0'
> ```
> 
> I'm waiting for tests, but please comment if all of you have the same situation right now. @himsa @agnkuz @devwdsoft

Update: this is not solving the issue.
The issue doesn't reproduce on debug version.
From a real device no bugs are being reported (I use Firebase Crashlytics to catch all errors)

**Comment by huycozy** [comment] 2023-05-19 05:42
I tried with below minimal sample code with loading an assets image, ran it on iOS device with `release` mode, put the app in background and wait for more than 10 minutes, but didn't see the issue.

Verifying this issue on the latest stable channel `3.10.1`. 

| before | after |
| --------------- | --------------- |
<img width="400" src="https://github.com/flutter/flutter/assets/104349824/37dba455-7cee-4882-974a-a0389872e51f"> | <img width="400" src="https://github.com/flutter/flutter/assets/104349824/adf58117-7e3e-4164-af82-409d138754ee">

<details>
<summary>Sample code</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MaterialApp(home: MyApp()));
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Image.asset('assets/house.png'),
      ),
    );
  }
}
```
</details>

If there is any specific cases that different than this sample code, please provide it so that we may verify the issue. Thank you!

**Comment by goneall** [comment] 2023-05-20 13:26
Just a note - this seems similar to https://github.com/flutter/flutter/issues/71074 which was fixed in 2021.

BTW - we're hitting the same issue.

**Comment by giovanni256** [comment] 2023-05-20 14:01
> Just a note - this seems similar to #71074 which was fixed in 2021.
> 
> BTW - we're hitting the same issue.

Yes, as reported [in this comment](https://github.com/flutter/flutter/issues/126878#issuecomment-1553653401).




> I tried with below minimal sample code with loading an assets image, ran it on iOS device with `release` mode, put the app in background and wait for more than 10 minutes, but didn't see the issue.
> 
> Verifying this issue on the latest stable channel `3.10.1`.
> 
> before	after
> <img alt="" width="400" src="https://user-images.githubusercontent.com/104349824/239447114-37dba455-7cee-4882-974a-a0389872e51f.png">	<img alt="" width="400" src="https://user-images.githubusercontent.com/104349824/239447095-adf58117-7e3e-4164-af82-409d138754ee.png">
> Sample code
> If there is any specific cases that different than this sample code, please provide it so that we may verify the issue. Thank you!

The issue seems to be solved on the stable channel, so this could be releated to an upgrade.
I will run more tests.

**Comment by terence-codigo** [comment] 2023-05-22 01:44
Same issue on 3.10.1. It disappears after navigating away from page. Did not happen before 3.10.0.

![935F0812-791B-48F7-ABEA-2A30F26D60AE](https://github.com/flutter/flutter/assets/63663914/e1e1aca7-6ae9-4bd3-910c-634717f387ae)

**Comment by huycozy** [comment] 2023-05-22 04:30
@terence-codigo Can you reproduce it locally with clear `steps to reproduce`? If so, please provide a minimal sample code without 3rd party plugins if possible. Thank you!

**Comment by znromonk** [comment] 2023-05-22 15:28
Fortunately we did not roll out our app built on the 3.10 to production. Our testers saw the same issue but no Crashlytics reports were ever recorded.

I have done everything the testers said they did on the simulator but it seems simulator is immune to the bug. It makes me think that the issue is with the textures being offloaded to possibly save memory when users have a lot of apps open in the background. Since I have nothing else to go with, that is my guess. The testers did say the they only saw it when the app resumed from background and never when app starts up from a closed state.

Just to add on, I think it is more than the images that is causing the issue. The pink also appeared to a tester on a gradient from the `ShaderMask` widget.

**Comment by giovanni256** [comment] 2023-05-22 20:09
> Fortunately we did not roll out our app built on the 3.10 to production. Our testers saw the same issue but no Crashlytics reports were ever recorded.
> 
> I have done everything the testers said they did on the simulator but it seems simulator is immune to the bug. It makes me think that the issue is with the textures being offloaded to possibly save memory when users have a lot of apps open in the background. Since I have nothing else to go with, that is my guess. The testers did say the they only saw it when the app resumed from background and never when app starts up from a closed state.
> 
> Just to add on, I think it is more than the images that is causing the issue. The pink also appeared to a tester on a gradient from the `ShaderMask` widget.

I keep to say that my testers are not experiencing this bug in the stable 3.10.1, but I agree with you.
No Crashlytics reports, but in my case the issue was on simply `Image.asset` widget that became pink as the app gets resumed.

**Comment by naivetoby** [comment] 2023-05-23 02:42
I encountered a similar issue in Flutter SDK 3.10.1 with iOS 16.5, and it can be consistently reproduced. When I cold start my release iOS app by clicking the desktop icon, everything works fine as shown in the screenshot. 

<img src="https://github.com/flutter/flutter/assets/2428663/6d46a8ca-bf50-42ae-a9e3-e8668eb42f83" width="30%"/>
<img src="https://github.com/flutter/flutter/assets/2428663/01ba1704-5429-4777-b221-e0cb452c2065" width="30%"/>


**However, when I cold start the app by clicking a push notification, UI abnormalities occur in 80% of cases as shown in the screenshot.** 


<img src="https://github.com/flutter/flutter/assets/2428663/5a58d9c4-a4d4-406a-8dab-540f7d437c6b" width="30%" />
<img src="https://github.com/flutter/flutter/assets/2428663/204ddd5d-008a-4e48-bd20-48d70268ffba" width="30%" />


I would like to report this issue to the Flutter community.

**Comment by huycozy** [comment] 2023-05-23 06:09
@naivetoby Is that possible to replicate the issue consistently and see if it has any pattern? If so, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this. Thank you!

**Comment by terence-codigo** [comment] 2023-05-23 15:56
@naivetoby @devwdsoft @giovanni256 Are the affected images SVGs?

**Comment by naivetoby** [comment] 2023-05-23 20:28
> @naivetoby @devwdsoft @giovanni256 Are the affected images SVGs, or wrapped with a GestureDetector?

affected images WebPs and  wrapped with a GestureDetector

**Comment by znromonk** [comment] 2023-05-24 01:27
I have found a way to reproduce the pink images. I have to use hot reload to simulate the images being updated from fresh data in background.

1. Run the code sample in debug mode
2. Put the app in foreground
3. In the editor/command line, use hot reload.
4. Bring the app to foreground.

If no pink images (no error shown below) then put the app in background and hot reload again till you see the error.

Cannot say for certain, but from my testing, running `flutter run --no-enable-impeller` does not show this error despite multiple hot reload in the background.

<details><summary>Code Sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      debugShowCheckedModeBanner: false,
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key});

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Container(
          margin: const EdgeInsets.symmetric(vertical: 10),
          height: 400,
          width: 600,
          child: Image.asset('assets/600x400.png'),
        ),
      ),
    );
  }
}
```
</details>

<details><summary>Log from <code>flutter run -v</code> after reload</summary>

```
[        ] Reloaded 0 libraries in 99ms (compile: 10 ms, reload: 0 ms, reassemble: 48 ms).
[   +7 ms] Execution of the command buffer was aborted due to an error during execution. Insufficient
Permission (to submit GPU work from background)
(00000006:kIOGPUCommandBufferCallbackErrorBackgroundExecutionNotPermitted)
[        ] Execution of the command buffer was aborted due to an error during execution. Insufficient
Permission (to submit GPU work from background)
(00000006:kIOGPUCommandBufferCallbackErrorBackgroundExecutionNotPermitted)
```
</details>

<details><summary>Screen Recording</summary>

https://github.com/flutter/flutter/assets/523078/88a9fa0d-5232-4960-8028-d2a4265f34a8

</details>

**Comment by huycozy** [comment] 2023-05-24 04:13
@znromonk Thank you for providing those steps but I still can not reproduce this issue.

- Verifying on `iPhone 7, iOS 15.7.2` and some different images: the image will disappear on my end (only displaying a white screen). 
- When I checking this on `iPhone 14 Pro, iOS 16.4 (emulator)`, the image still persists as normal without turning to pink.

Can you please provide that image? And which device are you testing on?

**Comment by znromonk** [comment] 2023-05-24 04:33
Sure thing.

I got the image from [here](https://placehold.co/600x400.png). I did not change it in any way.

<details><summary><code>flutter doctor -v</code></summary>

```console
[✓] Flutter (Channel stable, 3.10.1, on macOS 13.4 22F66 darwin-arm64, locale en-US)
    • Flutter version 3.10.1 on channel stable at /Users/demouser/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d3d8effc68 (7 days ago), 2023-05-16 17:59:05 -0700
    • Engine revision b4fb11214d
    • Dart version 3.0.1
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/demouser/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment Corretto-17.0.6.10.1 (build 17.0.6+10-LTS)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment Corretto-17.0.6.10.1 (build 17.0.6+10-LTS)

[✓] VS Code (version 1.78.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.64.0

[✓] Connected device (3 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.4 22F66 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 113.0.5672.126

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```
</details> 

**Device from screen recording:**
iPad Air (4th Gen)
iPadOS 16.5

Did you get the `kIOGPUCommandBufferCallbackErrorBackgroundExecutionNotPermitted` error that was posted in the logs above? I have verified that when I run my app in debug mode, monitoring the log and that message shows up, the images would be pink when I bring the app to the foreground.

As for the image disappearing in your test, could it be related to this: https://github.com/flutter/flutter/issues/71074#issuecomment-794622038

**Comment by giovanni256** [comment] 2023-05-24 06:14
> @naivetoby @devwdsoft @giovanni256 Are the affected images SVGs, or wrapped with a GestureDetector?

No, in my case I have JPG or PNG images wrapped in a Material widget

**Comment by befirst** [comment] 2023-05-24 08:17
In my case as far as I understand the app launches in the background after it receives a silent push, and the first piece of images that are trying to be rendered are getting pink, then I open the app and all other images after navigating to other parts of the app look ok.

**Comment by lpylpyleo** [comment] 2023-05-24 15:14
I came across this problem, too. Only in release mode.

**Comment by znromonk** [comment] 2023-05-24 18:25
@mjbader Clearing image cache did not seem to help. Following the steps in the video for the above code sample, the logs show the same error while in background and the pink image still shows up after being brought to the foreground. Even clearing the cache regardless of the `AppLifecycleState` does not make any difference.

<details><summary>Code Sample with AppLifecycle change</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      debugShowCheckedModeBanner: false,
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key});

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> with WidgetsBindingObserver {
  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    debugPrint(state.name);

    if (state == AppLifecycleState.resumed && mounted) {
      debugPrint('clearing cache');

      imageCache.clear();
      imageCache.clearLiveImages();
    }
  }

  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addObserver(this);
  }

  @override
  void dispose() {
    WidgetsBinding.instance.removeObserver(this);
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Container(
          margin: const EdgeInsets.symmetric(vertical: 10),
          height: 400,
          width: 600,
          child: Image.asset('assets/600x400.png'),
        ),
      ),
    );
  }
}
```
</details> 

<details><summary>Logs</summary>

```console
flutter: inactive
flutter: paused
Reloaded 0 libraries in 79ms (compile: 5 ms, reload: 0 ms, reassemble: 44 ms).
Execution of the command buffer was aborted due to an error during execution. Insufficient Permission (to submit GPU work from background) (00000006:kIOGPUCommandBufferCallbackErrorBackgroundExecutionNotPermitted)
flutter: inactive
flutter: resumed
flutter: clearing cache
```
</details>

**Comment by mjbader** [comment] 2023-05-24 22:15
> 

You have to trigger a rerender.  Right now you are just simply clearing the cache.  I modified the sample to demonstrate how the image is cached.

```import 'dart:async';

import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      debugShowCheckedModeBanner: false,
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key});

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  Timer? timer;
  String currentOwl = owlJPG1;

  static const owlJPG1 = 'assets/owl.jpg';
  static const owlJPG2 = 'assets/owl-2.jpg';

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Column(
          children: [
            Container(
              margin: const EdgeInsets.symmetric(vertical: 10),
              height: 400,
              width: 600,
              child: Image.asset(
                currentOwl
              ),
            ),
            TextButton(
                onPressed: () {
                  if (currentOwl == owlJPG1) {
                    setState(() {
                      currentOwl = owlJPG2;
                    });
                  } else {
                    setState(() {
                      currentOwl = owlJPG1;
                    });
                  }

                  imageCache.clear();
                },
                child: const Text('Change Owl'))
          ],
        ),
      ),
    );
  }
}
```
Here's what happens when the cache is cleared on button press and the image is cycled.
https://github.com/flutter/flutter/assets/4692062/245ce8ec-3ea3-41cb-a877-4d943447098b

Here's what happens when you keep the cache.  The image is still cached.
https://github.com/flutter/flutter/assets/4692062/134d3a18-178f-4d0d-93e3-99722399f995

**Comment by znromonk** [comment] 2023-05-25 01:53
@mjbader Yes your code works by clearing cache and calling `setState` and replacing with another image. But it does not solve the issue where the user is seeing a sea of pink when the app is bought to the foreground. I would say disabling impeller seems like an easier workaround.

**Comment by Akatsukishen** [comment] 2023-05-26 00:14
I came across this problem on iPhone13, too.
reproducible steps:
   1. load assetImage.
   2. switch app to background.
   3. hot reload.
   4. image to pink.
   
![IMG_8FC1D8D5D44F-1](https://github.com/flutter/flutter/assets/11297640/9e285fc5-d6de-4419-9333-d6cd67a5dc75)
 
`  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Color(0xFF060735),
      appBar: AppBar(
        title: const Text('AssetImage Test'),
      ),
      body: Container(
        width: 300,
        height: 300,
        child: Stack(alignment: Alignment.center, children: [
          Container(
            width: 200,
            height: 200,
            color: _color,
          ),
          ClipRRect(
            borderRadius: BorderRadius.circular(8),
            child: Image.asset(
              'assets/images/test.jpg',
              width: 100,
              height: 100,
            ),
          ),
        ]),
      ),
    );
  }  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Color(0xFF060735),
      appBar: AppBar(
        title: const Text('AssetImage Test'),
      ),
      body: Container(
        width: 300,
        height: 300,
        child: Stack(alignment: Alignment.center, children: [
          Container(
            width: 200,
            height: 200,
            color: _color,
          ),
          ClipRRect(
            borderRadius: BorderRadius.circular(8),
            child: Image.asset(
              'assets/images/test.jpg',
              width: 100,
              height: 100,
            ),
          ),
        ]),
      ),
    );
  }`

and when reopen the same page , the image is also pink. Kill app, the image is normal.

flutter doctor -v:
╰─$ flutter doctor -v
[!] Flutter (Channel stable, 3.10.1, on macOS 12.6.5 21G531 darwin-x64, locale zh-Hans-CN)
    • Flutter version 3.10.1 on channel stable at /Users/.../sdk/flutter
    ! Warning: `dart` on your path resolves to /usr/local/Cellar/dart/2.18.5/libexec/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/.../sdk/flutter. Consider adding /Users/.../sdk/flutter/bin to
      the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d3d8effc68 (9 days ago), 2023-05-16 17:59:05 -0700
    • Engine revision b4fb11214d
    • Dart version 3.0.1
    • DevTools version 2.23.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to
      perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/.../Library/Android/sdk
    • Platform android-33, build-tools 30.0.3
    • ANDROID_HOME = /Users/.../Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.12.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] IntelliJ IDEA Community Edition (version 2022.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.78.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.64.0

[!] Proxy Configuration
    • HTTP_PROXY is set
    ! NO_PROXY is not set

[✓] Connected device (3 available)
    • iPhone 13 (mobile) • 00008110-001849523C3A801E • ios            • iOS 15.4.1 19E258
    • macOS (desktop)    • macos                     • darwin-x64     • macOS 12.6.5 21G531 darwin-x64
    • Chrome (web)       • chrome                    • web-javascript • Google Chrome 113.0.5672.126

[✓] Network resources
    • All expected network resources are available.

**Comment by dnfield** [comment] 2023-05-26 17:25
As far as we can tell this is happening because of attempts to do Metal command buffer encoding in the background. I have not been able to locally reproduce the issue of launching from background causing the bugs in this issue, but I can reproduce going to background and doing a hot reload causing a pretty similar issue.

It once the proposed fix lands int he framework it would be nice to get confirmation from someone here that it fixes the issue I've not been able to reproduce.

**Closed** 2023-05-26 18:46 UTC
Labels: severe: regression, platform-ios, engine, waiting for PR to land (fixed), customer: crowd, a: images, has reproducible steps, impeller, found in release: 3.10, found in release: 3.11

**Comment by dnfield** [comment] 2023-05-27 04:20
If you have a reliable. method of reproducing this, please see if it still reproduces on flutter mainline/master channel. The patch that should fix it just rolled in this evening.

**Comment by znromonk** [comment] 2023-05-27 16:29
Switched to master and tested on the sample code above (using hot reload) as well as on the full app where we noticed the issue. No more `kIOGPUCommandBufferCallbackErrorBackgroundExecutionNotPermitted` error and no more pink images. Look like the CP to stable is also on the way. Thanks for the quick fix.

**Comment by real1900** [comment] 2023-05-28 22:15
So how can I make use of this patch to fix my app 

@znromonk @dnfield ? I am facing the same issue in 3.10.1

**Comment by znromonk** [comment] 2023-05-29 00:40
@real1900 The fix has landed on master channel and there was a cherry pick request to stable. I am assuming that the next dot release/hotfix (3.10.2 ?) will have this patch. If you are having issues on production version, you can [disable impeller](https://docs.flutter.dev/perf/impeller#ios) till the hotfix arrives.

**Comment by dnfield** [comment] 2023-05-29 02:36
> Switched to master and tested on the sample code above (using hot reload) as well as on the full app where we noticed the issue. No more `kIOGPUCommandBufferCallbackErrorBackgroundExecutionNotPermitted` error and no more pink images. Look like the CP to stable is also on the way. Thanks for the quick fix.

Great!

Yes, the CP should be availale in stable before very long.

**Comment by terence-codigo** [comment] 2023-05-29 03:59
Thank you everyone. I'll re-publish my app when 3.10.3 comes along and will post an update to confirm the fix.

**Comment by RobertBrunhage** [comment] 2023-05-31 15:28
Is this available now in 3.10.2 or will it be available in 3.10.3?

Not working in 3.10.2 :)

**Comment by dnfield** [comment] 2023-05-31 17:34
IIUC https://github.com/flutter/flutter/issues/127705 is the right signal for whether this is finished going through to stable or not.

**Comment by dnfield** [comment] 2023-05-31 18:17
> Also, if it helps I got it on dev now once where this was the message being printed
> 
> `Execution of the command buffer was aborted due to an error during execution. Insufficient Permission (to submit GPU work from background) (00000006:kIOGPUCommandBufferCallbackErrorBackgroundExecutionNotPermitted)`

That should be fixed by the above patch. Are you still seeing it on the master channel?

**Comment by terence-codigo** [comment] 2023-06-06 08:15
Hi everyone, I don't see this issue any more for my iOS app in production with 3.10.3. 👍

**Comment by mzdm** [comment] 2023-06-09 13:29
I encountered when rendering svg image (both on 3.10.1 and 3.10.3), I have created an issue in the package: https://github.com/dnfield/flutter_svg/issues/939

**Comment by JiaoLiu** [comment] 2023-06-21 01:20
i'm facing the same issue under Flutter (Channel stable, 3.10.2, on macOS 12.6.3 21G419 darwin-x64, locale
    zh-Hans-CN). how to solve it?

**Comment by dnfield** [comment] 2023-06-21 03:19
This was fixed in 3.10.3.

**Comment by sannykhan3777** [comment] 2023-06-21 17:27
**IN RELEASE MODE**
With my case its not pink image rather the whole image is not showing and also buttons are not showing. 
I tried on flutter stable 3.10.3 and 3.10.5

Steps to reproduce:
1) Make a simple screen with and image and a button.
2) Run the app using "flutter run --release" OR make apk and install it on android phone.
3) When app is on foreground press back button or go back. The application will become in background.
4) From background click again the app. Now on screens there will be no image and button.

**Comment by dnfield** [comment] 2023-06-21 18:33
> **IN RELEASE MODE** With my case its not pink image rather the whole image is not showing and also buttons are not showing. I tried on flutter stable 3.10.3 and 3.10.5
> 
> Steps to reproduce:
> 
> 1. Make a simple screen with and image and a button.
> 2. Run the app using "flutter run --release" OR make apk and install it on android phone.
> 3. When app is on foreground press back button or go back. The application will become in background.
> 4. From background click again the app. Now on screen there will be no image and button.

@sannykhan3777 this bug was iOS/Impeller only. Please file a new bug with reproduction steps and a sample application.
