### ISSUE TITLE
MaterialIcons font family not being bundled on iOS release

### ISSUE THREAD

**Issue by miguelpruivo** [flutter/flutter#77423] opened 2021-03-05 22:50 UTC
## Steps to Reproduce
```
            Text(
                     'someIconName',
                      style: TextStyle(
                      fontFamily: 'MaterialIconss',
                      fontSize: 25.0,
                    )
```
This works perfectly to render dynamic icons from BE on Android (release and debug mode) and also on iOS debug. However, in iOS release it doesn't work properly and icon names are displayed instead.

```
[✓] Flutter (Channel unknown, 1.22.6, on macOS 11.2.2 20D80 darwin-x64, locale pt-PT)
    • Flutter version 1.22.6 at /Users/miguelruivo/devtools/flutter
    • Framework revision 9b2d32b605 (6 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/miguelruivo/Library/Android/sdk
    • Platform android-30, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.54.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

 
[✓] Connected device (3 available)            
    • iPhone 12 (mobile) • 6575E0BF-D34F-4E06-8190-12DD7E6214E7 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • Web Server (web)   • web-server                           • web-javascript • Flutter Tools
    • Chrome (web)       • chrome       
```

**Comment by nt4f04uNd** [comment] 2021-03-06 19:38
looks like you messed up the `pubspec.yaml`

make sure this like is included in `flutter` section

```yaml
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

```

also, upgrade to flutter 2

**Comment by nt4f04uNd** [comment] 2021-03-06 19:51
and also, i'm not sure if this is a valid code to draw a material icon

>             Text(
>                      'someIconName',
>                       style: TextStyle(
>                       fontFamily: 'MaterialIconss',
>                       fontSize: 25.0,
>                     )

**Comment by miguelpruivo** [comment] 2021-03-07 14:33
@nt4f04uNd that’s the only way to render it dynamically other than creating a map with all de icons (which is tedious and ugly). I have that flag set.

Like I said in my original post, it works on debug mode. Try it on iOS release.

**Comment by nt4f04uNd** [comment] 2021-03-07 15:06
> that’s the only way to render it dynamically other than creating a map with all de icons (which is tedious and ugly). I have that flag set.

i don't really see how this makes it easier, but anyway, i can reproduce in ios release

<details>
<summary>screenshot</summary>

![image](https://user-images.githubusercontent.com/39104740/110244416-a5853500-7f6f-11eb-8241-b81827c973c7.png)
</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel texture_buildable, 1.27.0-2.0.pre.100, on Mac OS X 10.15.2
    19C57 darwin-x64, locale ru-RU)
    • Flutter version 1.27.0-2.0.pre.100 at /Users/danya/dev/src/flutter
    • Framework revision 76080cd46c (2 weeks ago), 2021-02-21 18:22:32 +0300
    • Engine revision 1d537824d6
    • Dart version 2.13.0 (build 2.13.0-30.0.dev)

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from:
      https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK
      components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup
      for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.7, Build version 11E801a
    ! Xcode 11.7.0 out of date (12.0.1 is recommended).
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup
      for detailed instructions).

[✓] VS Code (version 1.53.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 88.0.4324.192

! Doctor found issues in 3 categories.
```
</details>

**Comment by TahaTesser** [comment] 2021-03-08 08:37
Hi @miguelpruivo  @nt4f04uNd 
I'm unable to reproduce the issue when running  `flutter run --release -v` on the latest channels from `stable` to `master`  using a code sample from  https://github.com/flutter/flutter/issues/77423#issuecomment-792041648.

<img src="https://user-images.githubusercontent.com/48603081/110295868-a40f4780-8017-11eb-8e60-5e76375f41d8.jpeg" height="450" />


<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 2.0.1, on macOS 11.2.2 20D80 darwin-x64, locale
    en-GB)
    • Flutter version 2.0.1 at /Users/tahatesser/Code/flutter_stable
    • Framework revision c5a4b4029c (4 days ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.54.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (3 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios            • iOS
      14.4
    • macOS (desktop)        • macos                     • darwin-x64     •
      macOS 11.2.2 20D80 darwin-x64
    • Chrome (web)           • chrome                    • web-javascript •
      Google Chrome 88.0.4324.192

• No issues found!
```

```bash
[✓] Flutter (Channel beta, 2.0.1, on macOS 11.2.2 20D80 darwin-x64, locale
    en-GB)
    • Flutter version 2.0.1 at /Users/tahatesser/Code/flutter_beta
    • Framework revision c5a4b4029c (4 days ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.54.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (3 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios            • iOS
      14.4
    • macOS (desktop)        • macos                     • darwin-x64     •
      macOS 11.2.2 20D80 darwin-x64
    • Chrome (web)           • chrome                    • web-javascript •
      Google Chrome 88.0.4324.192

• No issues found!
```

```bash
[✓] Flutter (Channel dev, 2.1.0-10.0.pre, on macOS 11.2.2 20D80 darwin-x64,
    locale en-GB)
    • Flutter version 2.1.0-10.0.pre at /Users/tahatesser/Code/flutter_dev
    • Framework revision cc9b78fc5c (10 days ago), 2021-02-25 13:26:03 -0800
    • Engine revision a252ec09b7
    • Dart version 2.13.0 (build 2.13.0-77.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.54.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (3 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios            • iOS
      14.4
    • macOS (desktop)        • macos                     • darwin-x64     •
      macOS 11.2.2 20D80 darwin-x64
    • Chrome (web)           • chrome                    • web-javascript •
      Google Chrome 88.0.4324.192

• No issues found!
```

```bash
[✓] Flutter (Channel master, 2.1.0-11.0.pre.145, on macOS 11.2.2 20D80
    darwin-x64, locale en-GB)
    • Flutter version 2.1.0-11.0.pre.145 at
      /Users/tahatesser/Code/flutter_master
    • Framework revision a0ba646408 (2 days ago), 2021-03-05 22:09:03 -0500
    • Engine revision f751d04fa0
    • Dart version 2.13.0 (build 2.13.0-107.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.54.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (3 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios            • iOS
      14.4
    • macOS (desktop)        • macos                     • darwin-x64     •
      macOS 11.2.2 20D80 darwin-x64
    • Chrome (web)           • chrome                    • web-javascript •
      Google Chrome 88.0.4324.192

• No issues found!
```

</details>

Can you please upgrade and try again
Thank you

**Comment by miguelpruivo** [comment] 2021-03-08 13:15
Hi, I've actually tried deploying locally using release build and I can confirm that it is working properly.

I've also made a manual archive and distributed with Firebase and it's working as well. So I digged down and the issue seems to be related with the Fastlane lane that I use to distribute which is the following:
```
  desc "Build Ad-Hoc"
    private_lane :build_adhoc do

        build

        build_app(
            workspace: xcode_workspace,
            scheme: xcode_default_scheme,
            include_symbols: true,
            export_options: {
                method: "ad-hoc",
                provisioningProfiles: {
                        // hidden
                }
            }
        )
    end

    # ------------------------------------------------------------------------------------------------
    desc "Distribute to Dev Team"
    lane :dev do
        
        build_adhoc

        firebase_app_distribution(
            app: firebase_app_dev,
            groups: firebase_test_groups,
            debug: true,
            release_notes: changelog
        )

        upload_symbols_to_crashlytics(
            dsym_path: symbols_path,
            app_id: firebase_app_dev,
            gsp_path: "./Environments/dev/",
        )

    end
```
It seems that when I run `fastlane dev` the MaterialIcons doesn't work dynamically on the app but I can't really tell why. If someone is familiar with process and could be some insight it would be great.

Thank you.

**Comment by TahaTesser** [comment] 2021-03-09 07:11
Hi @miguelpruivo 
Thanks for confirming, unfortunately, I'm not familiar with Fastlane.
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-03-09 07:11 UTC
Labels: in triage
