### ISSUE TITLE
[tool_crash] FileSystemException: Getting current working directory failed, OS Error: Operation not permitted, errno = 1

### ISSUE THREAD

**Issue by Jesse-Dan** [flutter/flutter#131618] opened 2023-07-31 17:26 UTC
## Command
```
flutter create --offline --template app --overwrite .
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Getting current working directory failed, OS Error: Operation not permitted, errno = 1
```
#0      _Directory.current (dart:io/directory_impl.dart:42:7)
#1      Directory.current (dart:io/directory.dart:136:25)
#2      FileSystemEntity._absolutePath (dart:io/file_system_entity.dart:555:32)
#3      _Directory.absolute (dart:io/directory_impl.dart:97:43)
#4      ForwardingFileSystemEntity.absolute (package:file/src/forwarding/forwarding_file_system_entity.dart:83:35)
#5      ForwardingFileSystemEntity.absolute (package:file/src/forwarding/forwarding_file_system_entity.dart:83:35)
#6      CreateBase.generateApp (package:flutter_tools/src/commands/create_base.dart:570:49)
<asynchronous suspension>
#7      CreateCommand.runCommand (package:flutter_tools/src/commands/create.dart:350:31)
<asynchronous suspension>
#8      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1336:27)
<asynchronous suspension>
#9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#10     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#11     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:296:9)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#13     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:244:5)
<asynchronous suspension>
#14     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:91:9)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
```
```
[✓] Flutter (Channel stable, 3.10.5, on macOS 13.3.1 22E772610a darwin-x64, locale en-QA)
    • Flutter version 3.10.5 on channel stable at /Users/mac/Documents/DEV/DEV_FILES/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (7 weeks ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0-rc4)
    • Android SDK at /Users/mac/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0-rc4
    • Java binary at: /usr/bin/java
    • Java version Java(TM) SE Runtime Environment (build 17.0.7+8-LTS-224)
    • All Android licenses accepted.

[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS and macOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods installed but not working.
        You appear to have CocoaPods installed but it is not working.
        This can happen if the version of Ruby that CocoaPods was installed with is different from the one being used to invoke it.
        This can usually be fixed by re-installing CocoaPods.
      To re-install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.80.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.68.0

[✓] Connected device (3 available)
    • sdk gphone x86 64 (mobile) • emulator-5554 • android-x64    • Android 13 (API 33) (emulator)
    • macOS (desktop)            • macos         • darwin-x64     • macOS 13.3.1 22E772610a darwin-x64
    • Chrome (web)               • chrome        • web-javascript • Google Chrome 114.0.5735.133

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
Exception: The flutter tool cannot access the file or directory.
Please ensure that the SDK and/or project is installed in a location that has read/write permissions for the current user.

**Comment by darshankawar** [comment] 2023-08-01 07:09
Closing as duplicate of https://github.com/flutter/flutter/issues/98066

**Closed by darshankawar** 2023-08-01 07:09 UTC
Labels: in triage
