### ISSUE TITLE
Release builds will not execute async await commands on any physical device.

### ISSUE THREAD

**Issue by rss181919** [flutter/flutter#74579] opened 2021-01-24 05:19 UTC
I have an app that builds, launches, and executes as expected on multiple laptops in multiple emulators and also on physical device (Galaxy S7 in debug mode).  However, any RELEASE build will install and launche fine on physical devices but first AWAIT call hangs the app.  This was duplicated on same devices where debug was completely successful.  Tested devices (Galaxy S7 and Samsung Tab A).  Emulators used for testing have the same v8 android OS matching that of the Galaxy S7.
Debug testing was performed on 2 separate laptops independly installed with VSCode (dart and flutter plugins are up-to-date).  

**NOTE: Debug testing is completely successful on the S7 and Samsung Tab A devices for this app.  It is just the RELEASE build that seems to fail in all devices.**

To Reproduce:
1. Build the release using one of the following:
flutter build apk --release
flutter build apk --target-platform android-arm,android-arm64,android-x64 --split-per-abi
I tested the FAT apk as well as the version specific to the device.  Same result.

2. Launch the application and you will see a splash view.  Click the Play button and it will hang on line 1047 of file lib>widgets>app_wg.dart.  But the hang is not specific to this command from what I can tell because I have replaced it with other async calls using await and it hangs for any of them. 

This was reported on StackOverflow with several views but no responses.
https://stackoverflow.com/questions/65824019/flutter-app-release-build-hangs-on-call-to-getapplicationdocumentsdirectory

**Expected Result** - Launch of the app and hit Play on the splash screen and you should be prompted for permissions if the app does not have external storage permissions.  If it does have permissions you will be directed to the apps home screen.

**Actual result** - async call on app_wg.dart line 1047 hangs the app.

**Flutter bug output**

<details>
<summary>logs</summary>

```bash
PS C:\Dev\Projects\Flutter\quifil> flutter create bug
Creating project bug...
  bug\.gitignore (created)
  bug\.idea\libraries\Dart_SDK.xml (created)
  bug\.idea\libraries\KotlinJavaRuntime.xml (created)
  bug\.idea\modules.xml (created)
  bug\.idea\runConfigurations\main_dart.xml (created)
  bug\.idea\workspace.xml (created)
  bug\.metadata (created)
  bug\android\app\build.gradle (created)
  bug\android\app\src\main\kotlin\com\example\bug\MainActivity.kt (created)
  bug\android\build.gradle (created)
  bug\android\bug_android.iml (created)
  bug\android\.gitignore (created)
  bug\android\app\src\debug\AndroidManifest.xml (created)
  bug\android\app\src\main\AndroidManifest.xml (created)
  bug\android\app\src\main\res\drawable\launch_background.xml (created)
  bug\android\app\src\main\res\mipmap-hdpi\ic_launcher.png (created)
  bug\android\app\src\main\res\mipmap-mdpi\ic_launcher.png (created)
  bug\android\app\src\main\res\mipmap-xhdpi\ic_launcher.png (created)
  bug\android\app\src\main\res\mipmap-xxhdpi\ic_launcher.png (created)
  bug\android\app\src\main\res\mipmap-xxxhdpi\ic_launcher.png (created)
  bug\android\app\src\main\res\values\styles.xml (created)
  bug\android\app\src\profile\AndroidManifest.xml (created)
  bug\android\gradle\wrapper\gradle-wrapper.properties (created)
  bug\android\gradle.properties (created)
  bug\android\settings.gradle (created)
  bug\ios\Runner\AppDelegate.swift (created)
  bug\ios\Runner\Runner-Bridging-Header.h (created)
  bug\ios\Runner.xcodeproj\project.pbxproj (created)
  bug\ios\Runner.xcodeproj\xcshareddata\xcschemes\Runner.xcscheme (created)
  bug\ios\.gitignore (created)
  bug\ios\Flutter\AppFrameworkInfo.plist (created)
  bug\ios\Flutter\Debug.xcconfig (created)
  bug\ios\Flutter\Release.xcconfig (created)
  bug\ios\Runner\Assets.xcassets\AppIcon.appiconset\Contents.json (created)
  bug\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-1024x1024@1x.png (created)
  bug\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-20x20@1x.png (created)
  bug\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-20x20@2x.png (created)
  bug\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-20x20@3x.png (created)
  bug\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-29x29@1x.png (created)
  bug\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-29x29@2x.png (created)
  bug\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-29x29@3x.png (created)
  bug\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-40x40@1x.png (created)
  bug\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-40x40@2x.png (created)
  bug\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-40x40@3x.png (created)
  bug\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-60x60@2x.png (created)
  bug\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-60x60@3x.png (created)
  bug\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-76x76@1x.png (created)
  bug\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-76x76@2x.png (created)
  bug\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-83.5x83.5@2x.png (created)
  bug\ios\Runner\Assets.xcassets\LaunchImage.imageset\Contents.json (created)
  bug\ios\Runner\Assets.xcassets\LaunchImage.imageset\LaunchImage.png (created)
  bug\ios\Runner\Assets.xcassets\LaunchImage.imageset\LaunchImage@2x.png (created)
  bug\ios\Runner\Assets.xcassets\LaunchImage.imageset\LaunchImage@3x.png (created)
  bug\ios\Runner\Assets.xcassets\LaunchImage.imageset\README.md (created)
  bug\ios\Runner\Base.lproj\LaunchScreen.storyboard (created)
  bug\ios\Runner\Base.lproj\Main.storyboard (created)
  bug\ios\Runner\Info.plist (created)
  bug\ios\Runner.xcodeproj\project.xcworkspace\contents.xcworkspacedata (created)
  bug\ios\Runner.xcodeproj\project.xcworkspace\xcshareddata\IDEWorkspaceChecks.plist (created)
  bug\ios\Runner.xcodeproj\project.xcworkspace\xcshareddata\WorkspaceSettings.xcsettings (created)
  bug\ios\Runner.xcworkspace\contents.xcworkspacedata (created)
  bug\ios\Runner.xcworkspace\xcshareddata\IDEWorkspaceChecks.plist (created)
  bug\ios\Runner.xcworkspace\xcshareddata\WorkspaceSettings.xcsettings (created)
  bug\lib\main.dart (created)
  bug\bug.iml (created)
  bug\pubspec.yaml (created)
  bug\README.md (created)
  bug\test\widget_test.dart (created)
Running "flutter pub get" in bug...                                 5.0s
Wrote 71 files.
All done!

```
</details>

<details>
<summary>flutter doctor -v</summary>

```bash
[√] Flutter: is fully installed. (Channel stable, 1.22.5, on Microsoft Windows [Version 10.0.18363.1316], locale en-US)
[√] Android toolchain - develop for Android devices: is fully installed. (Android SDK version 29.0.2)
[!] Android Studio: is partially installed; more components are available. (version 4.1.0)
[√] VS Code: is fully installed. (version 1.52.1)
[!] Connected device: is not available.

**PS C:\Dev\Projects\Flutter\quifil> flutter doctor -v**
[√] Flutter (Channel stable, 1.22.5, on Microsoft Windows [Version 10.0.18363.1316], locale en-US)
    • Flutter version 1.22.5 at C:\Flutter\SDK
    • Framework revision 7891006299 (6 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\robsh\AppData\Local\Android\Sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = C:\Users\robsh\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.52.1)
    • VS Code at C:\Users\robsh\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.18.1

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
PS C:\Dev\Projects\Flutter\quifil> 
```
</details>

**Example RELEASE build**
[app-release.zip](https://github.com/flutter/flutter/files/5861603/app-release.zip)

**VSCode full project file (minus the builds since that greatly increased the zip file size)**
[quifil.vscode_project.zip](https://github.com/flutter/flutter/files/5861608/quifil.vscode_project.zip)

**Pics of S7 Galaxy Specs**
| Specs | Specs | Specs |
| --------------- | --------------- | --------------- |
<img src="https://user-images.githubusercontent.com/5641951/105621831-c0458500-5dd9-11eb-8eed-83ad041d5f25.jpg" height="350" />	|  <img src="https://user-images.githubusercontent.com/5641951/105621833-c0de1b80-5dd9-11eb-857f-9d850e8fdedb.jpg" height="350" /> | <img src="https://user-images.githubusercontent.com/5641951/105621835-c176b200-5dd9-11eb-9445-d1065422d53b.jpg" height="350" />

**Comment by TahaTesser** [comment] 2021-01-25 12:51
Hi @rss181919 
Thanks for filing the issue, does it only reproduce on Galaxy S7?
Can you please create a minimal code sample instead of production code and reproduce the issue S7 release build? Provide a minimal code sample instead of production code.
Thank you

**Comment by rss181919** [comment] 2021-01-26 04:46
As requested, I have recreated a test version (that is much smaller but still uses the same application structure).  Note I was also able to recreate the problem using this version on an x64 emulator.  So now I have created the problem on 1 virtual device as well as on the 2 physical devices I mentioned before (Galaxy S7 and Samsung Tab A).

This smaller test version has 1 master widget that uses a view state variable _vState to branch into 1 of 3 views (SPLASH, PERMISSIONS, HOME).  So the app just sets _vState and calls setState to move between views.

SPLASH view is just a splash view with a Play button to move to the PERMISSIONS view.  
PERMISSIONS view displays a status animation while it accesses external storage permissions and should branch as follows
1) If the app already has permissions, setState to move to the HOME view.
2) If the app lacks permissions, request them from the user and then move to the HOME view.

The app hangs on release builds on app_wg.dart line 424.
"PermissionStatus checkStatus = await Permission.storage.status;"  

In debug mode, the call is successful and recognizes the permissions are missing and then prompts the user for permissions, then moves to the HOME view.

Release build
[app-release.zip](https://github.com/flutter/flutter/files/5871197/app-release.zip)

VSCode project (minus the large build folder)
[test_project.zip](https://github.com/flutter/flutter/files/5871210/test_project.zip)

**Comment by TahaTesser** [comment] 2021-01-26 11:59
Hi @rss181919 
Thanks so much for the details, this still quite a big code sample for an "async await" issue and it uses third-party packages, the app hangs at a third-party package's code and but I can reproduce it on an emulator when building your project. 

However, running a simple async-await has no issue on your own without using any packages, in the release build.
Try this code sample below

<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      home: Home(),
    );
  }
}

class Home extends StatefulWidget {
  @override
  _HomeState createState() => _HomeState();
}

class _HomeState extends State<Home> {
  Future<String> testABug() async {
    return "this is not a bug";
  }

  String status;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Text(status ?? "no status"),
            ElevatedButton(
                onPressed: () {
                  setState(() async {
                    status = await testABug();
                  });
                },
                child: Text('call async await')),
          ],
        ),
      ),
    );
  }
}

``` 

</details>

If you can reproduce the async-await bug without using the third-party package, provide a code sample similar to above,. 
If the issue reproduces with permission_handler, please file an issue on their dedicated GitHub.

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 1.22.6, on Microsoft Windows [Version 10.0.19042.746], locale en-US)
    • Flutter version 1.22.6 at C:\Users\Taha\Code\flutter_stable
    • Framework revision 9b2d32b605 (4 days ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5


[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\Taha\Code\SDK
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Users\Taha\Code\android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.52.1)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.18.1

[✓] Connected device (1 available)
    • Android SDK built for x86 64 (mobile) • emulator-5554 • android-x64 • Android 8.0.0 (API 26) (emulator)

! Doctor found issues in 1 category.
```

</details>

Thank you

**Comment by rss181919** [comment] 2021-01-27 05:10
@TahaTesser 
Thanks for the recommendation.  Just a heads up but I tried your example verbatim but it did not compile because of the async function called by setState (apparently whatever you pass to setstate cannot be an async).  Anyway, I modified it slightly to get it working and the AWAIT calls were fine.  Then I blew in my projects pubspec.yaml.  In that spec, there is a file_picker: ^2.0.11 dependency.  When that dependency is added, I also have to modify gradle to get a build to complete.  The changes I have to make are listed below.  But when these changes are made, the build completes but then I have the original problem where the AWAIT calls fail.

Upgrade your gradle
com.android.tools.build:gradle:3.5.0 with source https\://services.gradle.org/distributions/gradle-5.6.2-all.zip
TO com.android.tools.build:gradle:4.0.1 with source https\://services.gradle.org/distributions/gradle-6.1.1-all.zip

Add checkReleaseBuilds item in build.gradle as follows.
lintOptions {
        disable 'InvalidPackage'
        checkReleaseBuilds false
    }

So I assume this should be reported to the pile_picker dev team?

**Comment by TahaTesser** [comment] 2021-01-27 09:18
Hi @rss181919 
I tried your project, it is missing a request for permission handler, your code is only checking for status, which return correcrtly and mission storage permissions in AndroidManifest as well and removed `file_picker` since it was causing issues, it's a third-party package as well.

Here I made the above changes and tried to reproduce the issue with `flutter build apk --release` on an Android 8 emulator x86x64. 
Calling async-await on permission handler works and also tried a simpler Future.value with await, still returns value, no fail

![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/48603081/105969274-14888780-60ae-11eb-8035-968c430dfbf0.gif)

```dart
Future<String> getString() async {
    await Permission.storage.request();
    String result = (await Permission.storage.status).toString();
    return result;

    // return await Future.value("new status");
  }
```

![ezgif com-gif-maker](https://user-images.githubusercontent.com/48603081/105969193-ffabf400-60ad-11eb-873c-ce6f8ab484ea.gif)

```dart

  Future<String> getString() async {
    // await Permission.storage.request();
    // String result = (await Permission.storage.status).toString();
    // return result;

    return await Future.value("new status");
  }
```

>  Anyway, I modified it slightly to get it working and the AWAIT calls were fine

Here you confirmed aync await works fine.  if it reproduces with `permission_handler ` or has issues with `file_picker`, please file an issue on their dedicated GitHub. 

I ask if you can reproduce without using permission_handler or file_picker, just with Flutter please provide details 

Here is the modified project 
[test_project2 (modified).zip](https://github.com/flutter/flutter/files/5878957/test_project2.modified.zip)


<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 1.22.6, on Microsoft Windows [Version 10.0.19042.746], locale en-US)
    • Flutter version 1.22.6 at C:\Users\Taha\Code\flutter_stable
    • Framework revision 9b2d32b605 (4 days ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5


[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\Taha\Code\SDK
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Users\Taha\Code\android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.52.1)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.18.1

[✓] Connected device (1 available)
    • Android SDK built for x86 64 (mobile) • emulator-5554 • android-x64 • Android 8.0.0 (API 26) (emulator)

! Doctor found issues in 1 category.
```

</details>

Thank you

**Comment by rss181919** [comment] 2021-01-27 16:25
Thanks @TahaTesser 

In my last example, I called the permissions check just as an example of an async call to that package.  If I replace the call with an PermissionStatus status = await Permission.storage.request(); it fails at that point as well.  It also fails when making a call to the package path_provider: ^1.6.27.  So it appears that the changes required in the gradle config to allow a project to build without error when including file_picker are actually breaking async calls to other third party packages.   So I will have to report this to the file_picker team.   Thanks for your help in troubleshooting this.   You can close the ticket.

**Comment by TahaTesser** [comment] 2021-01-28 06:59
Hi @rss181919 
Given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you

**Closed by TahaTesser** 2021-01-28 06:59 UTC
Labels: in triage

**Comment by rss181919** [comment] 2021-01-31 20:33
@TahaTesser 
I worked with the file_picker team to resolve this.  See **[this](https://github.com/miguelpruivo/flutter_file_picker/issues/602)** ticket for solution.
