### ISSUE TITLE
Hot reloaded changes are not applied to new isolates as they are launched

### ISSUE THREAD

**Issue by mravn-google** [flutter/flutter#18600] opened 2018-06-19 13:12 UTC
1. Create an Android app which displays a new Flutter view on (say) click on a fab.
1. Build the app and launch it using `flutter run --use-application-binary`
1. Launch a Flutter view, change Dart code, and press `r` to hot reload it.
1. Launch another Flutter view.
1. Observe: the second view does not contain the hot reloaded changes. (Confusing)
1. Press `r`
1. Observe: the second view now contains the hot reloaded changes.

We should remove the confusion at step 5.

**Comment by matthew-carroll** [comment] 2018-09-17 23:39
@InMatrix @mjohnsullivan Can you two comment on what you think the UX should look like for this situation?

We're entering a world where an app might programmatically add FlutterViews as @mravn suggests.  But also a world where we might have different FlutterEngines betweens screens, as well as background FlutterEngines.  

Should all new FlutterEngines launch with the latest snapshot?

When a user runs hot reload, should all running FlutterEngines be impacted?  Or are there use-cases that you can think of which would require only running hot reload on a specific FlutterEngine?

**Comment by matthew-carroll** [comment] 2019-04-09 01:11
@bkonyi do you happen to know what the state of this behavior is today? Or who I should loop in to find out?

**Comment by nioncode** [comment] 2020-04-09 17:46
I encountered this while implementing my callback for [flutter_workmanager](https://github.com/vrtdev/flutter_workmanager), which seems to launch a new isolate whenever the system wakes up the app on the native side and then calls the provided callback.

It is extremely frustrating having to stop the app, recompile it and run it from scratch every time when doing a minor change to the callback, after getting to know flutter's awesome hot reload / hot restart capabilities. What usually takes 1s in the main isolate now easily takes 60s or more, which is a bit unfortunate, since Hot Reload is one of flutter's killer features.

Is there a way for me to speed up the feedback cycle here until this might be fixed in the tool? I'm thinking about just forwarding the message from the callback back to the main isolate during development until the implementation is reasonably mature to not require constant re-compilations.

**Comment by jonahwilliams** [comment] 2020-04-09 18:14
@nioncode this issue is about multiple flutter views that have been embedded in an add2app scenario. What you are describing sounds like the issue of hot reload not updating background isolates, which we've recently done some work for. 

You might try the `master` branch briefly to see if our work has already fixed the issue. Otherwise I would recommend filling a new bug with details on how to reproduce the error on an example project using flutter_workmanager

**Comment by ganeshrvel** [comment] 2020-09-18 20:18
A hack, unregister the port using IsolateNameServer.removePortNameMapping('name);

```
  @override
  void initState() {
    super.initState();

    IsolateNameServer.removePortNameMapping('downloader_send_port');

    IsolateNameServer.registerPortWithName(
        _port.sendPort, 'downloader_send_port');
    _port.listen((dynamic data) {
      String id = data[0];
      DownloadTaskStatus status = data[1];
      int progress = data[2];
    });

    FlutterDownloader.registerCallback(downloadCallback);
  }
```

**Comment by TheLastGimbus** [comment] 2021-07-16 11:51
Hi! Is there/will be any progress on this? It's still annoying/time-wasting as hell :roll_eyes:

**Comment by mkustermann** [comment] 2021-09-09 10:59
As part of https://github.com/dart-lang/sdk/issues/36097 we have fixed issues with hot-reload and isolates (e.g. https://github.com/dart-lang/sdk/issues/36648). That work should also this issue.

If this is still an issue for anyone **on master branch**, please file a new issue and CC me.

**Closed by mkustermann** 2021-09-09 10:59 UTC
Labels: platform-android, tool, dependency: dart, t: hot reload, a: existing-apps, P4
