### ISSUE TITLE
[go_router] Using ref.watch from riverpod  inside the build context  navigation does not work

### ISSUE THREAD

**Issue by rddewan** [flutter/flutter#100281] opened 2022-03-17 05:42 UTC
In my build context i have used  ref.watch(settingControllerProvider).languageCode to rebuild the MaterialApp  when language change . The problem is when the event is fired to navigate to next page it does not do any thing 
using context.pushNamed(homeNameRoute); so when i remove ref.watch navigation works properly but the MaterialApp does not rebuild 
```
@override
  Widget build(BuildContext context) {    
    languageCode = ref.watch(settingControllerProvider).languageCode;
    themeMode = ref.watch(settingControllerProvider).themeMode;
    Analytics.logCurrentScreen(screenName: 'main');
    return MaterialApp.router(
      debugShowCheckedModeBanner: false,
      restorationScopeId: 'main',
      routeInformationParser: AppRouter.router().routeInformationParser, 
      routerDelegate: AppRouter.router().routerDelegate, 
      title: 'Swap Recycling',
      themeMode: ThemeMode.system,
      darkTheme: AppTheme.darkTheme,
      theme: getThemeData(themeMode,languageCode),
      localizationsDelegates: const [
        AppLocalizations.delegate,
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
      ],
      locale: languageCode == LanguageCode.en.name ? AppLocales.en.locale : AppLocales.th.locale,
      supportedLocales: AppLocales.supportedLocales,      
    );
  }  
```

**Comment by danagbemava-nc** [comment] 2022-03-17 09:58
Hi @rddewan,

Can you please provide your `flutter doctor -v`  and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?

Please also specify the version of go_router, you're using. 

Thank you

**Comment by rddewan** [comment] 2022-03-17 13:51
@danagbemava-nc  sure let me create a clean project on it

**Comment by rddewan** [comment] 2022-03-21 08:38
@danagbemava-nc  here is the project link . Please use the riverpod branch
https://github.com/rddewan/flutter-go-router-demo/tree/riverpod

**Comment by danagbemava-nc** [comment] 2022-03-22 06:29
Hi @rddewan, I only see a loading indicator when I open the app. Is that supposed to be happening? See screenshot below
Also, it would be best if you could reduce the sample to only the relevant parts that reproduce the issue. 

<img src="https://user-images.githubusercontent.com/88313112/159420877-24952fd0-53e9-4f76-94b1-5b53a5003bc6.png" width="200" />

**Comment by rddewan** [comment] 2022-03-22 08:10
@danagbemava-nc  yes it's correct. This is the problem it get stuck at splash screen in loading state and never navigates to login page

```
class SplashScreen extends ConsumerStatefulWidget {
  const SplashScreen({Key? key}) : super(key: key);

  @override
  _SplashScreen createState() => _SplashScreen();
}

class _SplashScreen extends BaseConsumerState<SplashScreen> {
  @override
  Widget build(BuildContext context) {    
    ref.listen<AppState>(appControllerProvider, (previous, next) {
      next.themeMode?.when(
        data: (data) {
          context.goNamed(loginNameRoute);
        },            
        error: (e,s) => Center(child: Text(e.toString())), 
        loading: () => null,
      );     
    }); 
    return const Center(
      child: CircularProgressIndicator(color: Colors.white,),
    );   
    }

}
```

**Comment by danagbemava-nc** [comment] 2022-03-23 06:23
Hi @rddewan, I'm not certain this is an issue with `go_router`. I changed the call to `context.goNamed()` to show a dialog when the data is received and the dialog wasn't shown either unless I removed the `ref.watch` from the main build method. 
Can you also check to see if the same thing happens for you?

**Comment by rddewan** [comment] 2022-03-23 08:26
@danagbemava-nc  Yes it's correct `go_router` does not work if we use `ref.watch` in the mail build method . That is the problem i am facing. According to riverpod `ref.watch` should be only used inside build method

**Comment by danagbemava-nc** [comment] 2022-03-23 08:42
@rddewan what I meant is, I modified your `SplashScreen` file to see if a dialog would show when it was supposed to navigate and the dialog wasn't shown either. The issue may lie somewhere else and not with `go_router`. Kindly check with the code sample below to see if the same thing happens. 

<details>
<summary>updated SplashScreen</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter_goroute_demo/base/base_consumer_state.dart';
import 'package:flutter_goroute_demo/feature/splash/presentation/controller/app_controller.dart';
import 'package:flutter_goroute_demo/feature/splash/presentation/state/app_state.dart';
import 'package:flutter_goroute_demo/route/name_route.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';

class SplashScreen extends ConsumerStatefulWidget {
  const SplashScreen({Key? key}) : super(key: key);

  @override
  _SplashScreen createState() => _SplashScreen();
}

class _SplashScreen extends BaseConsumerState<SplashScreen> {
  @override
  Widget build(BuildContext context) {
    ref.listen<AppState>(appControllerProvider, (previous, next) {
      next.themeMode?.when(
        data: (data) {
          print("data: $data");

          showDialog(
              context: context,
              builder: (BuildContext context) {
                return AlertDialog(
                  content: Center(
                    child: Text('Show this dialog'),
                  ),
                );
              });
        },
        error: (e, s) {
          print('error: $e, stack: $s');
          return Center(child: Text(e.toString()));
        },
        loading: () => Center(
          child: LinearProgressIndicator(),
        ),
      );
    });
    return const Center(
      child: CircularProgressIndicator(
        color: Colors.white,
      ),
    );
  }
}
```
</details>

**Comment by rddewan** [comment] 2022-04-04 01:40
@danagbemava-nc  I guess it's a go_router issue as i have tested withe material router the same code works perfectly it can navigate to another page or show dialog

**Comment by danagbemava-nc** [comment] 2022-04-04 08:16
Hi @rddewan, if you implement the `MaterialApp.router` without using the `go_router` package, does it work as expected?

**Comment by rddewan** [comment] 2022-04-04 09:55
@danagbemava-nc  with `MaterialApp.router`  `routeInformationParser` and `routerDelegate` is required  which i am passing it from `go_router` if just use MaterialRoute it is not required

**Comment by danagbemava-nc** [comment] 2022-04-05 06:34
Hi @rddewan, for the record, you can implement the `MaterialApp.router` without using `go_router`, `go_router` just makes it easier for you to do that. 

That aside, I can reproduce your issue, however, in the current state of the project, there are too many files to skim through and that might make getting to the root cause a little bit difficult. Can you reduce your sample to only the relevant classes required to reproduce the issue? Maybe only the main, splash, and signup screens, along with their relevant states?

Thank you

**Comment by rddewan** [comment] 2022-04-08 01:17
@danagbemava-nc  sure i will try to remove files that are not required

**Comment by XuanTung95** [comment] 2022-04-25 07:49
@rddewan 

The behavior is strange when you rebuild `MaterialApp.router()` with another instant of `routerDelegate`. In this case, the router will think that you replace the old `routerDelegate` with a new one. 

Your code is fixed by using final router; 

```
class _MyAppState extends ConsumerState<MyApp> { 
  String? themeMode;

  final router = AppRouter.router(); // here

  @override
  Widget build(BuildContext context) {
    themeMode = ref.watch(settingControllerProvider).themeMode;
    return MaterialApp.router(
      restorationScopeId: 'main',
      debugShowCheckedModeBanner: false,
      routeInformationParser: router.routeInformationParser,
      routerDelegate: router.routerDelegate,
      title: 'Flutter Demo',
      theme: setThemeData(themeMode),
      //builder: (_,child) => HideUIWidget(child: child),
      //home: const LoginScreen(),
    );
  }

  ThemeData setThemeData(String? code){
    if (code == ThemeMode.light.name) {
      return ThemeData(        
        primarySwatch: Colors.blue,
      );
    }

    return ThemeData(        
        primarySwatch: Colors.blueGrey,
      );

  }
}
```

**Comment by rddewan** [comment] 2022-05-03 04:05
thank you let me try this out

**Comment by XuanTung95** [comment] 2022-05-03 04:34
Related to #102952

**Closed** 2022-05-24 06:10 UTC
Labels: waiting for customer response, in triage
