### ISSUE TITLE
The following assertion was thrown during a scheduler callback:

### ISSUE THREAD

**Issue by faisalansari0367** [flutter/flutter#133169] opened 2023-08-23 17:32 UTC
════════ Exception caught by scheduler library ═════════════════════════════════
The following assertion was thrown during a scheduler callback:
'package:flutter/src/rendering/object.dart': Failed assertion: line 1145 pos 20: 'node.isRepaintBoundary': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack
#2      PipelineOwner.flushPaint
#3      RendererBinding.drawFrame
#4      WidgetsBinding.drawFrame
#5      RendererBinding._handlePersistentFrameCallback
#6      SchedulerBinding._invokeFrameCallback
#7      SchedulerBinding.handleDrawFrame
#8      SchedulerBinding._handleDrawFrame
#12     _invoke (dart:ui/hooks.dart:144:10)
#13     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:359:5)
#14     _drawFrame (dart:ui/hooks.dart:112:31)
(elided 5 frames from class _AssertionError and dart:async)
════════════════════════════════════════════════════════════════════════════════

**Comment by dam-ease** [comment] 2023-08-23 17:47
Closing this as a duplicate of https://github.com/flutter/flutter/issues/120874 based on the logs shared above.

Kindly subscribe to the original issue for updates.

Thank you

**Closed by dam-ease** 2023-08-23 17:47 UTC
Labels: in triage
