### ISSUE TITLE
high resolution image does not get rendered when scaled

### ISSUE THREAD

**Issue by yashwanthBhargav** [flutter/flutter#42420] opened 2019-10-10 11:13 UTC
I am trying to load an image in my app but when I scale it by a factor(in my case after x2.6) it is not rendering the image. But its working fine on emulator.
Also attached
![dwg](https://user-images.githubusercontent.com/33343424/66563918-6f763280-eb7c-11e9-9a5a-bbb697f31be1.png)
 my image file.
Here is a minimal code:

```

import 'package:flutter/material.dart';

void main() async {
  runApp(App());
}

class App extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Title',
      home: HomePage(),
    );
  }
}

class HomePage extends StatelessWidget {

  final matrix = Matrix4.identity()
    ..scale(2.60);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('HomePage'),
      ),
      body: Transform(
        transform: matrix,
        child: Image.asset('assets/dwg.png')
      ),
    );
  }
}

```

EDIT:
flutter doctor -v output:

```
[√] Flutter (Channel stable, v1.9.1+hotfix.4, on Microsoft Windows [Version 10.0.18362.388], locale en-US)
    • Flutter version 1.9.1+hotfix.4 at C:\Users\USER\Desktop\flutter
    • Framework revision cc949a8e8b (13 days ago), 2019-09-27 15:04:59 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\USER\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • Java binary at: F:\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at F:\Android Studio
    • Flutter plugin version 38.2.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code, 64-bit edition (version 1.38.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 2.23.1

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!
```

**Comment by BondarenkoStas** [comment] 2019-10-10 12:27
@yashwanthBhargav Please also paste your flutter doctor -v output.

**Comment by yashwanthBhargav** [comment] 2019-10-10 12:47
flutter doctor -v output:

```
[√] Flutter (Channel stable, v1.9.1+hotfix.4, on Microsoft Windows [Version 10.0.18362.388], locale en-US)
    • Flutter version 1.9.1+hotfix.4 at C:\Users\USER\Desktop\flutter
    • Framework revision cc949a8e8b (13 days ago), 2019-09-27 15:04:59 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\USER\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • Java binary at: F:\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at F:\Android Studio
    • Flutter plugin version 38.2.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code, 64-bit edition (version 1.38.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 2.23.1

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!
```

**Comment by yashwanthBhargav** [comment] 2019-10-11 05:56
> @yashwanthBhargav Please also paste your flutter doctor -v output.

I've updated the issue.

**Comment by ketanm** [comment] 2019-10-11 20:36
@yashwanthBhargav  - Please share following information:
* What is the target device that fails to render? 
* Did you try another device and whether it works or not?

**Comment by yashwanthBhargav** [comment] 2019-10-14 08:40
I have checked on multiple devices (IOS and Android) and it fails to render at some level.
Physical devices that I checked on:
One plus 6
Honor play 
Samsung Note9 
Iphone 7 plus
Iphone 6s plus

**Comment by yashwanthBhargav** [comment] 2019-10-14 11:39
> @yashwanthBhargav - Please share following information:
> 
> * What is the target device that fails to render?
> * Did you try another device and whether it works or not?

I have checked on multiple devices (IOS and Android) and it fails to render at some level.
Physical devices that I checked on:
One plus 6
Honor play
Samsung Note9
Nokia 6
Iphone 7 plus
Iphone 6s plus

It works fine on virtual device (emulator)

**Comment by ketanm** [comment] 2019-10-14 19:00
@yashwanthBhargav  
thanks for the further information. 

It is concerning that this is behaving across both device types (Android and iOS). Can you elaborate what happens when you say it fails to render? Does it open or just crashes when opening?

Is this regression? Do you know if it was working earlier? If it was then it is worth downgrading to earlier hotfix and give it a try. Do `flutter version v1.9.1+hotfix.2` and try build again. If you do then later need to upgrade to latest version.

**Comment by yashwanthBhargav** [comment] 2019-10-15 06:30
@ketanm 

It does not crash the app but it does not load the image without any exception or error log. This happened earlier but then it was working and now it is same as earlier.

**Comment by yashwanthBhargav** [comment] 2019-10-15 07:46
@ketanm 

I have tried with ``` version v1.9.1+hotfix.2 ``` and ``` version 1.7.8+hotfix.4 ```. Its working on ``` version 1.7.8+hotfix.4 ``` but not on  ``` version v1.9.1+hotfix.2 ```

**Comment by ketanm** [comment] 2019-10-15 14:53
@yashwanthBhargav  
thanks for sharing details and it does help. I am glad that you have one working path with `v1.8.3`. 

This looks like regression but not sure why PNG loading would fail. Can you also share details of PNG dims and format. On MacOS you can do `file assets/dwg.png`.

**Comment by hey24sheep** [comment] 2019-10-16 08:12
Here is the full details of that image

PNG

5,400 × 3,915 PNG (21.1 megapixels)   
4,949,886 bytes (4.7 megabytes)

Animation	no
Bit Depth	8
Color Type	RGB with Alpha
Compression	Deflate/Inflate
Filter	Adaptive
Image Size	5,400 × 3,915
Interlace	Noninterlaced
Significant Bits	8 8 8 8
File — basic information derived from the file.

File Size	4.7 MB
File Type	PNG
File Type Extension	png
MIME Type	image/png
Composite
This block of data is computed based upon other items. Some of it may be wildly incorrect, especially if the image has been resized.

Megapixels	21.1

**Comment by yashwanthBhargav** [comment] 2019-10-16 08:12
> @yashwanthBhargav
> thanks for sharing details and it does help. I am glad that you have one working path with `v1.8.3`.
> 
> This looks like regression but not sure why PNG loading would fail. Can you also share details of PNG dims and format. On MacOS you can do `file assets/dwg.png`.

PNG

Bit Depth	8
Color Type	RGB with Alpha
Compression	Deflate/Inflate
Filter	Adaptive
Image Size	5,400 × 3,915
Interlace	Noninterlaced
Significant Bits	8 8 8 8

File — basic information derived from the file.

File Size	4.7 MB
File Type	PNG
File Type Extension	png
MIME Type	image/png

**Comment by ketanm** [comment] 2019-10-16 13:16
Thanks for the PNG details. It does look normal and it does appear as regression. 

In mean time if you have not tried then do try loading image which is or smaller size (resize and save in asset) and/or load image without transparency (RGB only). This may not solve your problem but may help team if it is regression.

**Comment by hey24sheep** [comment] 2019-10-16 13:33
@ketanm small size images and rbg only works normal. Any image above 1920x1080 (Approx.) is a problem.

**Comment by yashwanthBhargav** [comment] 2019-10-22 12:34
If there is a work around for this problem, please suggest.

TIA.

**Comment by gaaclarke** [comment] 2019-10-22 19:45
I was unable to reproduce it on my iPhone SE:

![IMG_0034](https://user-images.githubusercontent.com/30870216/67325264-babc0980-f4c9-11e9-9a6d-955a1b35ebd4.PNG)


```
[✓] Flutter (Channel master, v1.10.15-pre.206, on Mac OS X 10.14.6 18G95, locale en-US)
    • Flutter version 1.10.15-pre.206 at /Users/aaclarke/dev/flutter
    • Framework revision f6d3dbd620 (18 minutes ago), 2019-10-22 12:25:12 -0700
    • Engine revision 39e6901e63
    • Dart version 2.6.0 (build 2.6.0-dev.8.0 a61c775db8)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/aaclarke/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/aaclarke/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/aaclarke/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    • CocoaPods version 1.8.3

[!] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.39.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.5.1

[✓] Connected device (1 available)
    • Aaron’s iPhone • 4d2c437717c3dd3afed1052d955ff9a82a10d378 • ios • iOS 11.3
```

**Comment by gaaclarke** [comment] 2019-10-22 19:59
I was however able to reproduce it with an android device:
```
[✓] Flutter (Channel master, v1.10.15-pre.206, on Mac OS X 10.14.6 18G95, locale en-US)
    • Flutter version 1.10.15-pre.206 at /Users/aaclarke/dev/flutter
    • Framework revision f6d3dbd620 (33 minutes ago), 2019-10-22 12:25:12 -0700
    • Engine revision 39e6901e63
    • Dart version 2.6.0 (build 2.6.0-dev.8.0 a61c775db8)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/aaclarke/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/aaclarke/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/aaclarke/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    • CocoaPods version 1.8.3

[!] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.39.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.5.1

[✓] Connected device (1 available)
    • EVA TL00 • B2T7N16906001650 • android-arm64 • Android 6.0 (API 23)
```

In general we probably shouldn't encourage using such large images and instead should implement something like a tile renderer.  I'll ask around a bit more on the team.

**Comment by gaaclarke** [comment] 2019-10-22 20:35
The Android device that reproduced the problem is a EVA TL00 which has a [Mali-T880](http://phonedb.net/index.php?m=device&id=10044&c=huawei_p9_standard_edition_dual_sim_td-lte_eva-tl00) GPU.  That GPU has a [max texture size of 4096](http://gles3mark.appspot.com/detail?5650665401483264) which seems to validate my hypothesis about max texture size being your problem.

Under the covers the engine is sometimes rendering different [MIP levels](https://en.wikipedia.org/wiki/Mipmap) for images.  So, when it is rendering fine the engine is probably using a MIP level that results in a texture that is less than the max texture size.  This may not be a regression then, we might have just changed the logic for the mipmapping and now you happen to fall on the side of having a texture that is too large for your GPU (which may be the correct image).

Here is my recommendation for a workaround.  Divide your source image into multiple images of no larger than 2048x2048 textures and create a widget for each one of those images.  This should give your app the widest compatibility.

We might be able to do the tiling under the covers secretly in the future.

**Comment by gaaclarke** [comment] 2019-10-22 23:10
I dug a bit deeper and this does seem like a bug in Skia.  If you look [here](https://github.com/flutter/engine/blob/ddf98c0cba0b1c95e69f27cf4c9783956c4a91f4/lib/ui/painting/image_decoder.cc#L180) you'll see we should be downsampling images that are too large.

My recommendation about tiling still holds though.  Even when large images works, you get quite a bit of delay when doing the image decompression on something so large.  By tiling your image you are giving the potential to only decompress and hold in memory images that are visible.

**Comment by gaaclarke** [comment] 2019-10-23 20:11
Filed an issue with Skia: https://bugs.chromium.org/p/skia/issues/detail?id=9562

**Comment by jason-simmons** [comment] 2019-10-23 22:54
Try increasing the size of the Skia resource cache as a workaround.

I was able to get the sample app to render the image on a Moto G4 with this patch:
```
import 'package:flutter/services.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  SystemChannels.skia.invokeMethod<void>('Skia.setResourceCacheMaxBytes', 200 << 20);
  runApp(App());
}
```

**Comment by Stylofly** [comment] 2019-11-01 01:11
> It seems like if you are on beta, then you need to include the "Skia." prefix, but if you're on stable you must exclude it.
from #36191

Just remove the 'Skia' prefix
`
SystemChannels.skia.invokeMethod<void>('setResourceCacheMaxBytes', 200 << 20);
`

**Comment by yashwanthBhargav** [comment] 2019-11-01 07:12
> > It seems like if you are on beta, then you need to include the "Skia." prefix, but if you're on stable you must exclude it.
> 
> from #36191
> 
> Just remove the 'Skia' prefix
> `SystemChannels.skia.invokeMethod<void>('setResourceCacheMaxBytes', 200 << 20);`

I am on stable, the one with "Skia" prefix throws exception but it works. If I exclude Skia prefix, it does not work and does not throw exception.

**Comment by graknol** [comment] 2019-11-22 06:51
> Filed an issue with Skia: https://bugs.chromium.org/p/skia/issues/detail?id=9562

Looking at that thread, it seems they've fixed it in a new revision. Now I guess we'll just have to wait for it to be picked up by flutter.

**Comment by cbracken** [comment] 2020-02-10 19:14
Closing as duplicate of #36191

**Closed by cbracken** 2020-02-10 19:14 UTC
Labels: a: images, engine, severe: regression
