### ISSUE TITLE
App store rejection due to embedding `Flutter.xcframework` in iOS app extensions

### ISSUE THREAD

**Issue by poka-IT** [flutter/flutter#155221] opened 2024-09-15 11:03 UTC
### Steps to reproduce

1. Follow the official [Flutter documentation for integrating Flutter into iOS app extensions](https://docs.flutter.dev/platform-integration/ios/app-extensions).
2. Set `Flutter.xcframework` to **"Embed & Sign"** in the extension target's build settings as instructed.
3. Archive and submit the app to the App Store.

### Expected results

The app should pass the App Store validation and be successfully submitted.

### Actual results

The app is rejected with the following errors:

```console
Invalid Bundle. The bundle at 'Runner.app/PlugIns/YourExtension.appex' contains disallowed file 'Frameworks'. (ID: ...)
Invalid Bundle. The bundle at 'Runner.app/PlugIns/YourExtension.appex' contains disallowed nested bundles. (ID: ...)
CFBundleIdentifier Collision. There is more than one bundle with the CFBundleIdentifier value 'io.flutter.flutter' under the iOS application 'Runner.app'. (ID: ...)
```

### Code sample

No special code, juste Xcode configuration follow on previous documentation.

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
Invalid Bundle. The bundle at 'Runner.app/PlugIns/YourExtension.appex' contains disallowed file 'Frameworks'. (ID: ...)
Invalid Bundle. The bundle at 'Runner.app/PlugIns/YourExtension.appex' contains disallowed nested bundles. (ID: ...)
CFBundleIdentifier Collision. There is more than one bundle with the CFBundleIdentifier value 'io.flutter.flutter' under the iOS application 'Runner.app'. (ID: ...)
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
$ flutter doctor 
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.24.1, on Manjaro Linux 6.6.46-1-MANJARO, locale fr_FR.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2024.1)
[✓] IntelliJ IDEA Community Edition (version 2024.1)
[✓] Connected device (2 available)
[✓] Network resources

• No issues found!
```

</details>

### Additional Information

Is this rejection due to a misconfiguration on my part, or is there an issue in the current Flutter documentation? Should `Flutter.xcframework` be embedded in iOS app extensions, or does this need to be addressed differently?

**Comment by darshankawar** [comment] 2024-09-16 10:15
Closing as duplicate of https://github.com/flutter/flutter/issues/142531.

**Closed by darshankawar** 2024-09-16 10:15 UTC
Labels: in triage
