### ISSUE TITLE
This program cannot be started because api-ms-win-core-rtlsupport-l1-2-0.dll is missing from the computer.

### ISSUE THREAD

**Issue by leielyq** [flutter/flutter#73289] opened 2021-01-05 03:08 UTC
This program cannot be started because api-ms-win-core-rtlsupport-l1-2-0.dll is missing from the computer.
I tried to publish the application to the customer's win7, but when I opened the application, it reported an error saying that dll is missing. I need help.
This is a testable case: https://github.com/gskinnerTeam/flokk/releases/tag/1.0.1%2B1.
I tried to check a lot of flutter applications published by others on github, but they all showed that the dll is missing.
The system is win7 sp1 x64. VS is not installed, and win7 has not been updated.
If possible, please provide all needed dlls. I beg you. This is very important to me.
I very much hope that flutter can run perfectly on every win7.

**Comment by TahaTesser** [comment] 2021-01-05 08:42
Hi @leielyq 
The repository you provided is a third party repository, please provide a code sample instead.
Can you please provide your `flutter doctor -v` your complete  `flutter run -d windows  --verbose` logs and a complete reproducible minimal code sample
Thank you

**Comment by stuartmorgan** [comment] 2021-01-14 16:58
> please provide a code sample instead.

This issue won't depend on the Dart code, so that's not actually necessary here.

> when I opened the application, it reported an error saying that dll is missing. I need help.

This sounds like you haven't provided the correct redistributables with your application. Did you bundle all of [these libraries](https://flutter.dev/desktop#windows), and if so, what are the exact, full paths on your system that you copied them from?

> If possible, please provide all needed dlls.

We can't provide you system-level DLLs. That's exactly what the redistributables from Microsoft are there for.

**Comment by 86speed** [comment] 2021-01-16 02:59
> > please provide a code sample instead.
> 
> This issue won't depend on the Dart code, so that's not actually necessary here.
> 
> > when I opened the application, it reported an error saying that dll is missing. I need help.
> 
> This sounds like you haven't provided the correct redistributables with your application. Did you bundle all of [these libraries](https://flutter.dev/desktop#windows), and if so, what are the exact, full paths on your system that you copied them from?
> 
> > If possible, please provide all needed dlls.
> 
> We can't provide you system-level DLLs. That's exactly what the redistributables from Microsoft are there for.

I have this problem, too

This is hello world. It has no other dependencies, but it is packaged and copied to other computers,

Prompt cannot start this program because api-ms-win-core-rtlsupport-l1-2-0.dll is missing from the computer. Try to re install the program to fix this problem. How can I fix it?

**Comment by pedromassangocode** [comment] 2021-02-05 14:59
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2021-02-05 14:59 UTC
Labels: in triage, waiting for customer response

**Comment by fawdlstty** [comment] 2021-03-17 15:20
Two ways to solve it- Install the VS2019 redistributable package

**Comment by fawdlstty** [comment] 2021-03-17 15:23
Two ways to solve it:

- Install the VS2019 redistributable package
- Find the .sln project files in the build/windows folder, open them, change the compilation option for each project from /MD to /MT, and then build the solution
    + Since this setting will be overwritten the next time through the flutter build command, this is not a convenient solution

**Comment by fawdlstty** [comment] 2021-03-18 01:13
> change the CMake files

Your advice is right. Can you provide a steps? I don't know how to change it.

**Comment by stuartmorgan** [comment] 2021-03-18 12:13
I've never done it, but presumably [as described in the CMake FAQ](https://gitlab.kitware.com/cmake/community/-/wikis/FAQ#how-can-i-build-my-msvc-application-with-a-static-runtime)
