### ISSUE TITLE
The built failed likely due to AndroidX incompatibilities in a plugin. 

### ISSUE THREAD

**Issue by baski1978** [flutter/flutter#56693] opened 2020-05-08 16:57 UTC
I am getting some plugin compatibility error while building my fluter fire store app using a mobilenumber plugin.

```bash
C:\flutter\fp\audience_poll\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java:20: error: no suitable method found for add(MobileNumberPlugin)
    flutterEngine.getPlugins().add(new com.example.mobile_number.MobileNumberPlugin());
                              ^
    method PluginRegistry.add(FlutterPlugin) is not applicable
      (argument mismatch; MobileNumberPlugin cannot be converted to FlutterPlugin)
    method PluginRegistry.add(Set<FlutterPlugin>) is not applicable
      (argument mismatch; MobileNumberPlugin cannot be converted to Set<FlutterPlugin>)
1 error

FAILURE: Build failed with an exception.

BUILD FAILED in 8s
The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.
Building plugin cloud_firestore...
Running Gradle task 'assembleAarRelease'...
Finished with error: The plugin cloud_firestore could not be built due to the issue above.
[flutter build error.txt](https://github.com/flutter/flutter/files/4600442/flutter.build.error.txt)

```

**Comment by baski1978** [comment] 2020-05-08 16:57
I am getting some plugin compatibility error while building my fluter fire store app using a mobilenumber plugin.

C:\flutter\fp\audience_poll\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java:20: error: no suitable method found for add(MobileNumberPlugin)
flutterEngine.getPlugins().add(new com.example.mobile_number.MobileNumberPlugin());
^
method PluginRegistry.add(FlutterPlugin) is not applicable
(argument mismatch; MobileNumberPlugin cannot be converted to FlutterPlugin)
method PluginRegistry.add(Set) is not applicable
(argument mismatch; MobileNumberPlugin cannot be converted to Set)
1 error

FAILURE: Build failed with an exception.

BUILD FAILED in 8s
The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.
Building plugin cloud_firestore...
Running Gradle task 'assembleAarRelease'...
Finished with error: The plugin cloud_firestore could not be built due to the issue above.

**Comment by jeffque** [comment] 2020-05-09 04:55
So, this message is a somewhat "default" message when build misbehave. See, `sqflite` had [this same message back in version 1.1.7](https://github.com/tekartik/sqflite/blob/f9abedc039e43080b990dc50f8803b72ed4822a8/sqflite/android/build.gradle#L3-L12)

I think that some example package had this error handle and a lot of packages derived from it get this awful message. Maybe it has nothing to do with AndroidX, as was with all of my builds back in 2019. It is just a misleading message

**Comment by jeffque** [comment] 2020-05-09 04:59
Also, check for flutter/plugins#2231, where a bunch of plugins had this message removed.

It hapened in 2019-oct, so just a bit more than 6 months old. Maybe you should upgrade your plugin?

**Comment by iapicca** [comment] 2020-05-11 06:27
Hi @dvird
you may want to double check
that your project implements [androidX migration]( https://flutter.dev/docs/development/androidx-migration) correctly;

for what I can see the issue is related to a FlutterFire plugin,
please open the issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
thank you

**Closed by iapicca** 2020-05-11 06:27 UTC
