### ISSUE TITLE
Delay when loading text on the web

### ISSUE THREAD

**Issue by michalkubizna** [flutter/flutter#111353] opened 2022-09-10 22:14 UTC
## Details

The app freezes for two seconds to load the ui when navigating to a new page in the debug mode but there is no delay in the release mode. 

1. Reproducible sample

Flutter web, Debug mode

```
 IconButton(onPressed: () {
            Navigator.push(context, MaterialPageRoute(builder: (context) {
              return Scaffold(
                appBar: AppBar(
                  title: Text("data"),
                ),
                body: SingleChildScrollView(child: ExpansionPanelList.radio(
                  expansionCallback: (int index, bool isExpanded) {},
                  children: [for (var i = 0; i < 50; i++) ExpansionPanelRadio(
                      canTapOnHeader: true,
                      headerBuilder: (context, bool isExpanded) {
                        return ListTile(
                          leading: Icon(Icons.add),
                          title: Text("${i}"),
                        );
                      },
                      body: Text("${i}"), value: i)
                  ],
                )),
              );
            }));
          }, icon: Icon(Icons.add)),
```

2. Doctor
```
[✓] Flutter (Channel stable, 3.3.1, on macOS 11.4 20F71 darwin-arm, locale en-US)
    • Flutter version 3.3.1 on channel stable at /Users/michalkubizna/Desktop/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4f9d92fbbd (4 days ago), 2022-09-06 17:54:53 -0700
    • Engine revision 3efdf03e73
    • Dart version 2.18.0
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/michalkubizna/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/michalkubizna/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13C100
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.71.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 12 (API 31) (emulator)
    • macOS (desktop)             • macos         • darwin-arm64   • macOS 11.4 20F71 darwin-arm
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 105.0.5195.102

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

**Comment by TahaTesser** [comment] 2022-09-13 14:02
The performance issue is related to loading a large number of `ExpansionPanelList` items. 

https://github.com/flutter/flutter/issues/106521 proposed refactoring this widget for more efficient scrolling or alternatively, using `CustomScrollView`  to get the desired results. Feel free to comment there.

**Comment by michalkubizna** [comment] 2022-09-13 16:05
I only provided the widget to reproduce the issue. It also happens in perfectly normal scenarios. It works just fine in the release mode.

**Comment by TahaTesser** [comment] 2022-09-13 16:25
@michalkubizna 
Can you please provide a code sample without `ExpansionPanelList`?

**Comment by michalkubizna** [comment] 2022-09-14 19:33
Sure. Here's another example. There's a significant delay when navigating to a new screen. It works just fine when using an android emulator. The web debug performance is very poor. 

```
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatefulWidget {
  const MyApp({super.key});

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  int _index = 0;

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Builder(
          builder: (context) {
            return Scaffold(
              body: IconButton(onPressed: () {
                Navigator.push(context, MaterialPageRoute(builder: (context) {
                  return Scaffold(
                    body: Row(
                      children: [
                        Expanded(
                          child: IndexedStack(index: _index, children: [
                            for (var i = 0; i < 5; i++) NewFontPickerScreen(),
                          ]),
                        ),
                        Expanded(child: IndexedStack(index: _index, children: [
                          for (var i = 0; i < 5; i++) NewFontPickerScreen(),
                        ])),
                      ],
                    ),
                    bottomNavigationBar: BottomNavigationBar(
                      items: [
                        for (var i = 0; i < 5; i++)
                          const BottomNavigationBarItem(
                              icon: Icon(Icons.add, color: Colors.black,),
                              label: ""),
                      ],
                      onTap: (int value) {
                        setState(() {
                          _index = value;
                        });
                      },
                    ),
                  );
                }));
              }, icon: Icon(Icons.add)),
            );
          }
      ),
    );
  }
}

class Font {
  final TextStyle textStyle;
  final String name;

  Font({
    required this.textStyle,
    required this.name
  });
}
class NewFontPickerScreen extends StatefulWidget {
  @override
  State<NewFontPickerScreen> createState() => _NewFontPickerScreenState();
}

class _NewFontPickerScreenState extends State<NewFontPickerScreen> {
  final _fonts = [
    Font(textStyle: GoogleFonts.roboto(), name: "Roboto"),
    Font(textStyle: GoogleFonts.openSans(), name: "Open Sans"),
    Font(textStyle: GoogleFonts.lato(), name: "Lato"),
    Font(textStyle: GoogleFonts.montserrat(), name: "Montserrat"),
    Font(textStyle: GoogleFonts.poppins(), name: "Poppins"),
    Font(textStyle: GoogleFonts.robotoCondensed(), name: "Roboto Condensed"),
    Font(textStyle: GoogleFonts.sourceSansPro(), name: "Source Sans Pro"),
    Font(textStyle: GoogleFonts.oswald(), name: "Oswald"),
    Font(textStyle: GoogleFonts.robotoMono(), name: "Roboto Mono"),
    Font(textStyle: GoogleFonts.notoSans(), name: "Noto Sans"),
    Font(textStyle: GoogleFonts.raleway(), name: "Raleway"),
    Font(textStyle: GoogleFonts.inter(), name: "Inter"),
    Font(textStyle: GoogleFonts.ubuntu(), name: "Ubuntu"),
    Font(textStyle: GoogleFonts.robotoSlab(), name: "Roboto Slab"),
    Font(textStyle: GoogleFonts.mukta(), name: "Mukta"),
    Font(textStyle: GoogleFonts.nunito(), name: "Nunito"),
    Font(textStyle: GoogleFonts.merriweather(), name: "Merriweather"),
    Font(textStyle: GoogleFonts.ptSans(), name: "PT Sans"),
    Font(textStyle: GoogleFonts.playfairDisplay(), name: "Playfair Display"),
    Font(textStyle: GoogleFonts.nunitoSans(), name: "Nunito Sans"),
    Font(textStyle: GoogleFonts.rubik(), name: "Rubik")
  ];

  String _name = "";

  @override
  Widget build(BuildContext context) {
    return GridView(
      gridDelegate: const SliverGridDelegateWithFixedCrossAxisCount(
          crossAxisCount: 3,
          mainAxisExtent: 50),
      children: [
        for (final Font font in _fonts)
          RadioListTile<String>(
              title: Text(font.name, style: font.textStyle),
              value: font.name,
              groupValue: _name,
              onChanged: (_) {
                setState(() {
                  _name = font.name;
                });
              })
      ],
    );
  }
}

```

**Comment by TahaTesser** [comment] 2022-09-16 13:41
The code sample in https://github.com/flutter/flutter/issues/111353#issuecomment-1247215529 is loading a bunch of text. There are few existing open issues for text-related performance [issues](https://github.com/flutter/flutter/issues?page=2&q=is%3Aopen+is%3Aissue+label%3A%22severe%3A+performance%22+label%3Aplatform-web) on the web.


To isolate the issue better. could you remove the package code and font loading, and try to reproduce the issue with just the flutter code? Also, try it on desktop app for comparison.

cc: @yjbanov

**Comment by michalkubizna** [comment] 2022-09-16 14:03
I removed the package code and it still drops below 10 frames per second. 

`import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatefulWidget {
  const MyApp({super.key});

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  int _index = 0;

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Builder(
          builder: (context) {
            return Scaffold(
              body: IconButton(onPressed: () {
                Navigator.push(context, MaterialPageRoute(builder: (context) {
                  return Scaffold(
                    body: Row(
                      children: [
                        Expanded(
                          child: IndexedStack(index: _index, children: [
                            for (var i = 0; i < 5; i++) NewFontPickerScreen(),
                          ]),
                        ),
                        Expanded(child: IndexedStack(index: _index, children: [
                          for (var i = 0; i < 5; i++) NewFontPickerScreen(),
                        ])),
                      ],
                    ),
                    bottomNavigationBar: BottomNavigationBar(
                      items: [
                        for (var i = 0; i < 5; i++)
                          const BottomNavigationBarItem(
                              icon: Icon(Icons.add, color: Colors.black,),
                              label: ""),
                      ],
                      onTap: (int value) {
                        setState(() {
                          _index = value;
                        });
                      },
                    ),
                  );
                }));
              }, icon: Icon(Icons.add)),
            );
          }
      ),
    );
  }
}

class Font {
  final TextStyle textStyle;
  final String name;

  Font({
    required this.textStyle,
    required this.name
  });
}
class NewFontPickerScreen extends StatefulWidget {
  @override
  State<NewFontPickerScreen> createState() => _NewFontPickerScreenState();
}

class _NewFontPickerScreenState extends State<NewFontPickerScreen> {
  String _name = "";

  @override
  Widget build(BuildContext context) {
    return GridView(
      gridDelegate: const SliverGridDelegateWithFixedCrossAxisCount(
          crossAxisCount: 3,
          mainAxisExtent: 50),
      children: [
        for (var i = 0; i < 20; i++)
          RadioListTile<String>(
              title: Text("${i}"),
              value: "${i}",
              groupValue: _name,
              onChanged: (_) {
                setState(() {
                  _name = "${i}";
                });
              })
      ],
    );
  }
}
`

**Comment by michalkubizna** [comment] 2022-09-16 14:13
The same things happen with icons or with just plain containers. It drops below 20 frames on macos

**Comment by TahaTesser** [comment] 2022-09-19 10:45
Loading large text on the web already is not always performance, I've linked web specific performance issues [here](https://github.com/flutter/flutter/issues/111353#issuecomment-1249380668)



> The same things happen with icons or with just plain containers. It drops below 20 frames on macos

Debug mode isn't meant to be performant so frame rate drop is expected. If you want real-time performance, please run in profile and release modes.

From https://docs.flutter.dev/testing/build-modes
> Compilation is optimized for fast development and run cycles (but not for execution speed, binary size, or deployment).


Given the above expectations and the issue isn't being isolated to a particular widget or code, lack of actionability
I feel safe closing the issue.

**Closed by TahaTesser** 2022-09-19 10:45 UTC
Labels: framework, f: material design, severe: performance, perf: speed, has reproducible steps, found in release: 3.3, found in release: 3.4
