### ISSUE TITLE
In the new version vscode auto complete stopped working

### ISSUE THREAD

**Issue by eduardohr-muniz** [flutter/flutter#138719] opened 2023-11-20 13:38 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

In the version prior to 3.16.0 when you pressed ctrl+space it gave an auto complete, helping with productivity, after this version the autocomplete stopped working as shown in the screenshots below

### Expected results

I hope you can get it working again

### Actual results

I hope you can get it working again

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

![image](https://github.com/flutter/flutter/assets/90477293/00329d4d-3ff9-4f4b-9f41-6f4cbdc551d4)

![Imagem do WhatsApp de 2023-11-20 à(s) 10 30 27_72679e90](https://github.com/flutter/flutter/assets/90477293/f28719c0-e7da-49b3-b13f-51f3d207d87a)

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by JGeek00** [comment] 2023-11-21 00:33
Same for me. The auto complete for parameters that require a function like `builder` was very helpful.

**Comment by Trung15010802** [comment] 2023-11-23 14:00
I have the same issue

**Comment by FantixX** [comment] 2023-11-25 16:32
can reproduce on stable as well, master does not have this issue

**Comment by TaTrungLink** [comment] 2023-11-26 07:34
I am facing the same issue on stable as well, however it only happens in vscode, android studio and intellij show the suggestions normally.

**Comment by eduardohr-muniz** [comment] 2023-11-28 14:20
@dam-ease That's right, only in stable it doesn't work

**Comment by eduardohr-muniz** [comment] 2023-11-28 21:59
A new version 3.16.1 has just come out and you still have the same problem

**Comment by darshankawar** [comment] 2023-11-29 06:07
Since this is vscode plugin issue only, I think it need to be reported in plugin's dedicated repo: https://github.com/Dart-Code/Dart-Code/issues so please file the same there for further resolution.
Closing from here. There are couple of similar issues related to autocomplete not working reported in it that you can refer: https://github.com/Dart-Code/Dart-Code/issues/4794


> That's right, only in stable it doesn't work

This indicates that it is working on master and per our triage policy, we'll go ahead and close it. If anybody disagrees, write in comments and we'll reopen it.

**Closed by darshankawar** 2023-11-29 06:07 UTC
Labels: in triage
