### ISSUE TITLE
Flutter add to app Android shows white screen on startActivity

### ISSUE THREAD

**Issue by lslv1243** [flutter/flutter#60595] opened 2020-06-30 11:58 UTC
I have an app where there are some screens that are made in Flutter (add2app). I have a class called CMFlutterActivity that is a subclass of `io.flutter.embedding.android.FlutterActivity`. I use this class to manage the method channels, but I am not too happy with how the screen is presented, because the first Flutter frame is not available when the Activity is presented. After some research I figured there is a method in the FlutterActivity that I can override to know when the first Flutter frame is available, it is called `onFlutterUiDisplayed`. The problem I have is: how do I manage to only make the Activity visible after this method has been called? I am currently getting a white frame before the Flutter Activity paints.

I am currently starting the activity in the following manner:
```kotlin
startActivity(Intent(context, CMFlutterActivity::class.java))
```

Here are some of my configurations:

AndroidManifest.xml:
```xml
<activity
    android:name=".ui.flutter.CMFlutterActivity"
    android:theme="@style/AppTheme.NoFullscreen"
    android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
    android:hardwareAccelerated="true"
    android:windowSoftInputMode="adjustResize"
    android:screenOrientation="portrait"
    android:stateNotNeeded="true"
    android:exported="true"
/>
```

styles.xml:
```xml
<style name="AppTheme.NoFullscreen">
    <item name="android:windowFullscreen">false</item>
</style>
```

`flutter doctor -v`:
```
[✓] Flutter (Channel stable, v1.17.4, on Mac OS X 10.15.5 19F101, locale pt)
    • Flutter version 1.17.4 at /Users/leonardosilva/development/flutter/flutter
    • Framework revision 1ad9baa8b9 (13 days ago), 2020-06-17 14:41:16 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/leonardosilva/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.8.4

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.0

[✓] Connected device (1 available)
    • Mi A2 • d73165 • android-arm64 • Android 10 (API 29)

! Doctor found issues in 1 category.
```

**Comment by xster** [comment] 2020-11-09 21:37
First thought: please make sure you're running in release mode. Launching an add-to-app module in debug mode will have drastically different performance characteristics. 

Also, if I read the question correctly, I think the premise of the question might be reversed. i.e. there's no way of preventing the Android activity from being started via intent in the first place by waiting for the first frame rendered callback since it's circular. A first frame can only be rendered if there's an activity hosting a surface holder view and the surface holder creates a surface which only happens when the activity is attached to the window. 

However, to produce a better visual effect, see https://flutter.dev/docs/development/ui/advanced/splash-screen. You can customize what's shown while waiting for the Flutter first frame.

**Comment by lslv1243** [comment] 2020-11-09 22:20
I ended up starting as a transparent activity and when the first frame is ready I make it opaque, it feels much better than showing something before the first frame, because it is so fast, there is no need to blink the screen with some splash screen. I think this could be the default behavior or maybe, make it easier to do this way.

**Comment by TahaTesser** [comment] 2020-12-04 13:17
Hi @lslv1243 
I agree with you here https://github.com/flutter/flutter/issues/60595#issuecomment-724312689 
When you run release mode, it's very fast and transparent view gets the job done.
If you something to add or some code sample to show we can improve something here, please ping me and comment below and I would love to reproduce and go from there. 
Closing. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2020-12-04 13:17 UTC
Labels: a: existing-apps, dependency: android, engine, platform-android
