### ISSUE TITLE
[tool_crash] NoSuchMethodError: NoSuchMethodError: The method 'contains' was called on null.Receiver: nullTried calling: contains("ext.flutter.activeDevToolsServerAddress")

### ISSUE THREAD

**Issue by digitpk** [flutter/flutter#83675] opened 2021-05-31 20:50 UTC
## Command
```
flutter --no-color run --machine --verbose --track-widget-creation --device-id=R58M383EE4Z --start-paused --dart-define=flutter.inspector.structuredErrors=true --devtools-server-address=http://127.0.0.1:9100 lib\main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
NoSuchMethodError: NoSuchMethodError: The method 'contains' was called on null.
Receiver: null
Tried calling: contains("ext.flutter.activeDevToolsServerAddress")
```
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
#1      waitForExtension (package:flutter_tools/src/resident_runner.dart:1483:31)
<asynchronous suspension>
#2      ResidentRunner._callDevToolsUriExtension (package:flutter_tools/src/resident_runner.dart:1302:5)
<asynchronous suspension>
#3      Future.wait.<anonymous closure> (dart:async/future.dart)
<asynchronous suspension>
#4      ResidentRunner.maybeCallDevToolsUriServiceExtension (package:flutter_tools/src/resident_runner.dart:1291:7)
<asynchronous suspension>
```
```
[✓] Flutter (Channel unknown, 2.0.0, on Microsoft Windows [Version 10.0.19043.985], locale en-US)
    • Flutter version 2.0.0 at E:\Android\fvm\versions\2.0.0
    • Framework revision 60bd88df91 (3 months ago), 2021-03-03 09:13:17 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at E:\Android\Sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.56.2)
    • VS Code at C:\Users\DIGIT\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.22.0

[✓] Connected device (3 available)
    • SM A305F (mobile) • R58M383EE4Z • android-arm64  • Android 10 (API 29)
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 90.0.4430.212
    • Edge (web)        • edge        • web-javascript • Microsoft Edge 91.0.864.37

• No issues found!

```

## Flutter Application Metadata
**Type**: null
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: null
**Creation framework version**: null
### Plugins
firebase_admob-0.11.0+1
firebase_auth-0.20.0+1
firebase_auth_web-0.3.2+6
firebase_core-0.7.0
firebase_core_web-0.2.1+3
firebase_messaging-8.0.0-dev.14
firebase_messaging_web-0.1.0-dev.5
flutter_local_notifications-3.0.2
flutter_plugin_android_lifecycle-1.0.11
image_picker-0.6.7+17
in_app_review-1.0.4
jitsi_meet-2.0.0
package_info-0.4.3+2
path_provider-1.6.21
path_provider_linux-0.0.1+2
path_provider_macos-0.0.4+4
path_provider_windows-0.0.4+1
share-0.6.5+4
shared_preferences-0.5.12+2
shared_preferences_linux-0.0.2+2
shared_preferences_macos-0.0.1+10
shared_preferences_web-0.1.2+7
shared_preferences_windows-0.0.1+1
sqflite-1.3.1+2
url_launcher-5.7.8
url_launcher_linux-0.0.1+3
url_launcher_macos-0.0.1+8
url_launcher_web-0.1.5
url_launcher_windows-0.0.1+1

**Comment by TahaTesser** [comment] 2021-06-01 09:30
Closing as duplicate of https://github.com/flutter/flutter/issues/83083

**Closed by TahaTesser** 2021-06-01 09:30 UTC
Labels: in triage
