### ISSUE TITLE
Flaky keyboard dismissal test

### ISSUE THREAD

**Issue by mdebbar** [flutter/flutter#78238] opened 2021-03-15 19:29 UTC
On an unrelated commit, this test failed:

https://ci.chromium.org/ui/p/flutter/builders/prod/Mac_android%20integration_ui_keyboard_resize/537/overview

```
[integration_ui_keyboard_resize] [STDOUT] stdout: [+3897 ms] 00:08 [32m+0[0m[31m -1[0m: end-to-end test Ensure keyboard dismissal resizes the view to original size [1m[31m[E][0m[0m
[integration_ui_keyboard_resize] [STDOUT] stdout: [        ]   Expected: true
[integration_ui_keyboard_resize] [STDOUT] stdout: [        ]     Actual: <false>
[integration_ui_keyboard_resize] [STDOUT] stdout: [  +22 ms]   package:test_api/src/frontend/expect.dart 155:31               fail
[integration_ui_keyboard_resize] [STDOUT] stdout: [        ]   package:test_api/src/frontend/expect.dart 150:3                _expect
[integration_ui_keyboard_resize] [STDOUT] stdout: [        ]   package:test_api/src/frontend/expect.dart 59:3                 expect
[integration_ui_keyboard_resize] [STDOUT] stdout: [        ]   test_driver/keyboard_resize_test.dart 45:7                     main.<fn>.<fn>
...
```

The test passed after a re-run. (cc @cbracken who wrote this test a loooong time ago)

**Comment by mdebbar** [comment] 2021-03-18 20:05
Got another instance today: https://ci.chromium.org/ui/p/flutter/builders/prod/Mac_ios%20integration_ui_ios_keyboard_resize/261/overview

**Comment by jmagman** [comment] 2021-03-22 20:57
Duplicate of https://github.com/flutter/flutter/issues/77196.

**Closed by jmagman** 2021-03-22 20:57 UTC
Labels: passed first triage, team, team: flakes
