### ISSUE TITLE
InheritedModel dependencies not cleared on rebuild

### ISSUE THREAD

**Issue by rrousselGit** [flutter/flutter#21967] opened 2018-09-18 01:26 UTC
Consider a widget that conditionally depends on an InheritedModel aspect:

```dart
if (foo) {
  return Text("Foo", MyModel.of(context, aspect: MyAspect));
}
```

It seems that if `foo` requirement is met once. Then even if that condition fails in the future; the widget will stay dependent on the MyModel.

This leads to unnecessary builds.  I'd expect the list of dependencies to be cleared before `build` call

**Comment by rrousselGit** [comment] 2018-10-25 21:21
@Hixie This is blocking for the release of a state management library I'm working on.

I can work on this if needed, but what can be done here?

**Comment by Hixie** [comment] 2018-10-25 21:42
We looked into this when designing this feature, but it seemed at the time like the cost to clear the dependencies would far outweigh any gains from not redundantly calling a few build methods. However, the best way to determine this would be to benchmark it.

If you are interested in addressing this, the place to look in would be framework.dart. I'm not sure what the best way to do this would be. We would definitely want to carefully examine benchmarks as part of any such PR.

**Comment by zoechi** [comment] 2018-12-31 10:13
Is this a duplicate of #12992 ?

**Comment by rrousselGit** [comment] 2019-01-01 13:37
It is, although I started some work on the topic. 
I do not know how to benchmark the performance impact, so I'm kind of stuck here.

**Closed** 2019-05-01 03:15 UTC
Labels: framework
