### ISSUE TITLE
[go_router] [flutter web] unable to access routes containing /test on page refresh

### ISSUE THREAD

**Issue by synapsecode** [flutter/flutter#156495] opened 2024-10-09 20:02 UTC
### Steps to reproduce

Minimum Reproducible Example: https://github.com/synapsecode/gorouter_undefinedbehaviour_example

when we go to /abc/test2/123 on the browser and refresh page, it reloads

however when we try to manually navigate to /abc/test/123 then it keeps loading forever and we get errors like:
```
Refused to execute script from 'http://localhost:61908/abc/test/web_entrypoint.dart.lib.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
require.js:168 Uncaught Error: Script error for "web_entrypoint.dart", needed by: main_module.bootstrap
http://requirejs.org/docs/errors.html#scripterror
    at makeError (require.js:168:17)
    at HTMLScriptElement.onScriptError (require.js:1738:36)
makeError @ require.js:168
onScriptError @ require.js:1738
error
req.load @ require.js:1943
load @ require.js:1685
load @ require.js:834
fetch @ require.js:824
check @ require.js:856
enable @ require.js:1176
enable @ require.js:1557
(anonymous) @ require.js:1161
(anonymous) @ require.js:134
each @ require.js:59
enable @ require.js:1113
init @ require.js:788
callGetModule @ require.js:1203
intakeDefines @ require.js:1259
localRequire @ require.js:1446
requirejs @ require.js:1797
req.config @ require.js:1805
(anonymous) @ main_module.bootstrap.js:785
123:1 Refused to execute script from 'http://localhost:61908/abc/test/dart_sdk.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
require.js:168 Uncaught Error: Script error for "dart_sdk", needed by: main_module.bootstrap
http://requirejs.org/docs/errors.html#scripterror
    at makeError (require.js:168:17)
    at HTMLScriptElement.onScriptError (require.js:1738:36)
```

we can navigate from within the application but not on reload / manual url usage

This happens only to routes containing /test as far as i could investigate.

What could be causing this

### Expected results

going to /abc/test/123 should result in the page being shown just like /abc/test2/123. 

### Actual results

Infinite Loading and errors in the console

### Code sample

<details open><summary>Code sample</summary>

Minimum Reproducible Example: https://github.com/synapsecode/gorouter_undefinedbehaviour_example

main.dart
```dart
import 'package:flutter/material.dart';
import 'package:flutter_web_plugins/url_strategy.dart';
import 'package:go_router/go_router.dart';
import 'package:gorouter_testfail_demo/routes.dart';

final navigatorKey = GlobalKey<NavigatorState>();

void main() async {
  usePathUrlStrategy();
  GoRouter.optionURLReflectsImperativeAPIs = true;
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(
      routerConfig: testRouter,
      debugShowCheckedModeBanner: false,
      title: "GoRouter test",
      theme: ThemeData(
        scaffoldBackgroundColor: Colors.white,
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.red),
        useMaterial3: true,
      ),
    );
  }
}

```

routes.dart
```dart
import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import 'package:gorouter_testfail_demo/main.dart';

final testRouter = GoRouter(
  // initialLocation: '/playground',
  navigatorKey: navigatorKey,
  routes: [
    GoRoute(
      path: '/',
      builder: (context, state) => Scaffold(
        body: Center(
          child: Column(
            children: [
              Text('gorouter /test undefined behaviour example'),
              ElevatedButton(
                onPressed: () {
                  context.go('/abc/test/123');
                },
                child: Text('Navigate to /abc/test/123'),
              )
            ],
          ),
        ),
      ),
    ),
    GoRoute(
      path: '/abc/test/:tid',
      builder: (context, state) => Scaffold(
        body: Text(state.pathParameters['tid']!),
      ),
    ),
    GoRoute(
      path: '/abc/test2/:tid',
      builder: (context, state) => Scaffold(
        body: Text(state.pathParameters['tid']!),
      ),
    ),
  ],
);
```

Dependencies: go_router: ^14.3.0 (latest), flutter: 3.19.6

</details>

### Screenshots or Video

<details open>
None
</details>

### Logs

<details open><summary>Logs</summary>

```console
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.19.6, on macOS 14.2 23C64 darwin-arm64, locale en-IN)
    • Flutter version 3.19.6 on channel stable at
      /Users/manashejmadi/Documents/flutter-sdk/3.19.6/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 54e66469a9 (6 months ago), 2024-04-17 13:08:03 -0700
    • Engine revision c4cd48e186
    • Dart version 3.3.4
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/manashejmadi/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/manashejmadi/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

[✓] IntelliJ IDEA Community Edition (version 2024.1.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.94.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.98.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 14.2 23C64 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 129.0.6668.90

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by huycozy** [comment] 2024-10-10 09:16
Hi @synapsecode, looks like you encountered https://github.com/flutter/flutter/issues/152995 when using `usePathUrlStrategy`. It should be fixed on the latest Flutter stable release 3.24.3. So please try upgrading Flutter SDK and retry.

I'm going ahead and close this as a duplicate of that issue. If you still experience this on Flutter 3.24.3, please write in comments and I will reopen this. Thanks!

**Closed by huycozy** 2024-10-10 09:16 UTC
Labels: in triage
