### ISSUE TITLE
ShowValueIndicator.always not work

### ISSUE THREAD

**Issue by 973257307** [flutter/flutter#74029] opened 2021-01-15 09:22 UTC
![image](https://user-images.githubusercontent.com/20786616/104152397-61b3fa80-541a-11eb-8fef-5304f997e3e0.png)

class CustomeSilder extends StatefulWidget {
  @override
  _CustomeSilderState createState() => _CustomeSilderState();
}

class _CustomeSilderState extends State<CustomeSilder> {
  double _val = 1;

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: Text("eee"),
        ),
        body: SliderTheme(
            data: SliderTheme.of(context).copyWith(
              trackHeight: 4,
              showValueIndicator: ShowValueIndicator.always,
            ),
            child: Slider(
              value: _val,
              min: 1,
              max: 100,
              label: DecimalUtil.divide(str1: _val.toString(), str2: "10", precision: 1),
              divisions: 10,
              activeColor: Color(0xFF3D6CFF),
              inactiveColor: Color(0xFF3D6CFF),
              onChanged: (double value) {
                setState(() {
                  _val = value;
                });
              },
              onChangeEnd: (double endValue) {
                _val = endValue;
              },
            )),
      ),
    );
  }
}

**Comment by pedromassangocode** [comment] 2021-01-15 09:51
Hi @973257307 
I cannot reproduce this issue on the latest `stable` channel.
Can you please upgrade to the latest  `stable` and try again
`flutter channel stable`
`flutter upgrade --force`
`flutter doctor -v`


If the issue persists, please provide your `flutter doctor -v`.
Thank you

**Comment by 973257307** [comment] 2021-01-18 08:51
![image](https://user-images.githubusercontent.com/20786616/104892466-2fbc0e80-59ad-11eb-8859-6ecfd001952f.png)

issue persists

**Comment by pedromassangocode** [comment] 2021-01-18 13:36
Hi @973257307 
Can you please describe what "not work" means? Please provide your actual vs expected behavior while running the code you provided.
Thank you

**Comment by 973257307** [comment] 2021-01-19 03:28
https://user-images.githubusercontent.com/20786616/104979374-182d6600-5a3f-11eb-97d6-fb2d9051a134.mp4

There is a slide bar and a focus point on it. When I touch and move right or left the focus point, the value behind the side bar will change and a bubble showing the value will appear. But when my finger leave the screen or I touch other elements in the screen but not the slide bar, the bubble will disappear.
What I want is that the bubble will always on the show and will never disappear. I thought ***** will work, and the source code is in the previous comment on the issue. But the bubble will disappear

**Comment by pedromassangocode** [comment] 2021-01-19 07:16
Hi @973257307 
As stated in the docs: 

![Screen Shot 2021-01-19 at 08 13 04](https://user-images.githubusercontent.com/67424416/105000080-3048b980-5a2e-11eb-8883-d53cc05c6682.png)

The `ShowValueIndicator.always` is expected to show the value indicator for both: Slider with divisions and Slider without divisions, and not to always show the value indicator.

Closing this a working as intended
Thank you

**Closed by pedromassangocode** 2021-01-19 07:16 UTC
Labels: in triage

**Comment by 973257307** [comment] 2021-01-19 07:43
it seems that i misunderstand the usage of ShowValueIndicator.always, :joy::joy::joy:. thanks for your patient explanation.
I have read though the interface codes and searched it in google and tried to find out the correct interface or method for such a requirement. But it seems like I didn’t find the correct one.
I would appreciate it if you know the right way and share it.
Thank you.

**Comment by pedromassangocode** [comment] 2021-01-19 10:48
Hi @973257307 
Currently it is not possible to do that using the Slider widget. You may want to search for a slider package on pub.dev (one of the most popular is https://pub.dev/packages/syncfusion_flutter_sliders) or to propose a feature request to add this capability on the Flutter's Silder widget itself.
