### ISSUE TITLE
a question about paint.blendmode , canvas.savelayer

### ISSUE THREAD

**Issue by shownstrong** [flutter/flutter#44708] opened 2019-11-12 14:28 UTC
## Steps to Reproduce

Drawing with a BlendMode unfortunately doesn't give the expected results. In the following case the source Rect should be gone and the dest Rect (the red one) should only be left at the bottom right. Instead the source Rect is really gone but the dest Rect doesn't change.

```
class TestPaint extends CustomPainter {
	@override
	void paint(Canvas canvas, Size size) {
		canvas.drawPaint(new Paint()..color = Colors.transparent);
		canvas.drawRect(
			new Rect.fromLTWH(50.0, 100.0, 200.0, 200.0),
			new Paint()..color = Colors.red
		);
		canvas.drawRect(
			new Rect.fromLTWH(150.0, 200.0, 200.0, 200.0),
			new Paint()..color = Colors.white
				..blendMode = BlendMode.dstIn
		);
	}
}
```

the issues is just like [https://github.com/flutter/flutter/issues/11002](url)
but i set the blendmode **dstIn**

thanks for your resps

```
```

```
```

```
```

**Comment by iapicca** [comment] 2019-11-12 14:55
https://github.com/flutter/flutter/issues/24031

**Comment by liyuqian** [comment] 2019-11-13 23:33
@shownstrong : I think it's working as intended. If you want "dest Rect (the red one) should only be left at the bottom right.", you need to draw a src Rect of the same size of the dest Rect, and the srcRect should have 1 opacity on the bottom right, and 0 opacity everywhere else. In your original code, you're only drawing on the bottom right, so it rightfully didn't affect pixels outside of the dest Rect.

**Comment by shownstrong** [comment] 2019-11-14 03:01
> @shownstrong : I think it's working as intended. If you want "dest Rect (the red one) should only be left at the bottom right.", you need to draw a src Rect of the same size of the dest Rect, and the srcRect should have 1 opacity on the bottom right, and 0 opacity everywhere else. In your original code, you're only drawing on the bottom right, so it rightfully didn't affect pixels outside of the dest Rect.

I don't understand why draw a src Rect of the same size of the dest Rect, it seems no necessary in Android api.  Have you ever seen a similar example?

**Comment by liyuqian** [comment] 2019-11-15 19:14
@shownstrong : can you please provide a link to the Android api that you're talking about? It would be even more helpful if you can provide a sample Android app that uses that api to achieve your effect. This will ensure that we accurately understand your requirement. We can of course modify our api to match your need if that turns out to be a widely used feature.

**Comment by shownstrong** [comment] 2019-11-18 08:35
@liyuqian sorry for late response. [https://github.com/zhlucky/SaleProgressViewhttps://github.com/zhlucky/SaleProgressView](url) you can see the example demo, or if you can read in Chinese, you can see the other link [https://www.jianshu.com/p/eab4564c8382](url). 
I could not find the similar effect in flutter , it's probablly I use the paint.blendmode and canvas in a wrong way.

**Comment by liyuqian** [comment] 2019-11-20 17:47
@shownstrong : https://www.jianshu.com/p/eab4564c8382 made src Rect and dest Rect have the same size by using `Bitmap` in Android. Specifically, its last step `canvas.drawBitmap(mSrcBitmap, 0, 0, mContentPaint);` draws a `mSrcBitmap` which is the src Rect, into the `canvas` which is the dest Rect. In Flutter, you can use [Image](https://api.flutter.dev/flutter/dart-ui/Image-class.html) as Android's `Bitmap`, and you can generate `Image` by [Picture.toImage](https://api.flutter.dev/flutter/dart-ui/Picture/toImage.html).

But for that progress bar effect, I wouldn't recommend the blend mode solution. You can implement the same effect much more easily with just a rrect clip. The clip solution would also have much better rendering performance.

**Comment by markusaksli-nc** [comment] 2020-09-15 12:53
Closing this since it doesn't indicate an issue or missing feature in flutter.

**Closed by markusaksli-nc** 2020-09-15 12:53 UTC
Labels: engine, framework
