### ISSUE TITLE
Flutter Doctor fails to enumerate plugins for Android Studio prereleases

### ISSUE THREAD

**Issue by ron-wolf** [flutter/flutter#27338] opened 2019-01-31 05:29 UTC
_The following was [pointed out](https://github.com/flutter/flutter/issues/11940#issuecomment-40620374) by @anthonyfok. I am also copying @zoechi, as it seems they’ve been administering most issues like this one, and can make the call to close this issue in case it’s seen as unproductive. Relevant PR: #26964 by @kangwang1988._

One installation folder for Android Studio—the dot-home directory—is determined correctly in the following code, accounting for the possibility that a preview version is installed:

https://github.com/flutter/flutter/blob/6f1d10b71a0e140eebb3e6c9e2d48a444dc0e4a2/packages/flutter_tools/lib/src/android/android_studio.dart#L27-L28

However, this expression is only ever (indirectly) used [in one place.](https://github.com/flutter/flutter/blob/6f1d10b71a0e140eebb3e6c9e2d48a444dc0e4a2/packages/flutter_tools/lib/src/android/android_studio.dart#L215) The flexibility of the regex is disregarded when an [`AndroidStudio`](https://github.com/flutter/flutter/blob/6f1d10b71a0e140eebb3e6c9e2d48a444dc0e4a2/packages/flutter_tools/lib/src/android/android_studio.dart#L32) instance’s property [`_pluginsPath`](https://github.com/flutter/flutter/blob/6f1d10b71a0e140eebb3e6c9e2d48a444dc0e4a2/packages/flutter_tools/lib/src/android/android_studio.dart#L87) is determined:

https://github.com/flutter/flutter/blob/6f1d10b71a0e140eebb3e6c9e2d48a444dc0e4a2/packages/flutter_tools/lib/src/android/android_studio.dart#L100-L111

`flutter doctor` should make use of regexes for all directory checks, rather than just for the dot-home directory; and when it does do so for the dot-home directory, this should apply everywhere for consistency. An example of a regex that would match all such directories currently in existence is as follows:

```regex
/User/[-\w]+/Library/Application Support/AndroidStudio(Preview)?\d.\d
```

In any case, `doctor` should _at the very least_ complain that it looked for a plugin directory but found none. At this point in time, it doesn’t even do so when the verbosity flag `-v` is passed.

**Comment by kangwang1988** [comment] 2019-01-31 05:47
@ron-wolf 
Are you saying the issue happens in other platforms like Linux or Windows?

**Comment by zoechi** [comment] 2019-01-31 06:44
Duplicate of #26928

**Comment by ron-wolf** [comment] 2019-01-31 22:07
@kangwang1988 I’m not familiar with how plugins are stored on those platforms, so I can’t answer that with any degree of certainty.

**Comment by zoechi** [comment] 2019-02-08 11:49
Please check if you can still reproduce in latest master. 
Tentatively closing as duplicate of #26928.
Please add a comment to have it reopened in case you can still reproduce.

**Comment by zoechi** [comment] 2019-02-22 06:47
@ron-wolf 
Please add the output of `flutter doctor -v`.

**Comment by ron-wolf** [comment] 2019-02-25 11:50
@zoechi Here goes:

```
[✓] Flutter (Channel master, v1.2.3-pre.32, on Mac OS X 10.14.2 18C54, locale en-US)
    • Flutter version 1.2.3-pre.32 at /usr/local/flutter
    • Framework revision 1a182bf7bf (4 hours ago), 2019-02-25 02:40:28 -0500
    • Engine revision 502c9c4002
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 c92d5ca288)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/Ron/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Users/Ron/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/183.5310756/Android Studio 3.4 Preview.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b22)
    • All Android licenses accepted.

[!] iOS toolchain - develop for iOS devices (Xcode 10.2)
    • Xcode at /Applications/Xcode-beta.app/Contents/Developer
    • Xcode 10.2, Build version 10P82s
    ✗ libimobiledevice and ideviceinstaller are not installed. To install with Brew, run:
        brew update
        brew install --HEAD usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    ✗ ios-deploy not installed. To install:
        brew install ios-deploy
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work on iOS.
        For more info, see https://flutter.io/platform-plugins
      To install:
        brew install cocoapods
        pod setup

[✓] Android Studio
    • Android Studio at /Users/Ron/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/183.5310756/Android Studio 3.4 Preview.app/Contents
    • Flutter plugin version 33.0.6
    • Dart plugin version 183.5901
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b22)

[!] IntelliJ IDEA Ultimate Edition (version 2019.1 EAP)
    • IntelliJ at /Users/Ron/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.
```

Perhaps the fact that it’s IDEA Ultimate is relevant?

**Comment by christopherfujino** [comment] 2020-10-23 16:35
Closing this issue as the plan is to deprecate the plugin validators altogether: https://github.com/flutter/flutter/issues/61246.

**Closed by christopherfujino** 2020-10-23 16:35 UTC
Labels: P4, easy fix, t: flutter doctor, tool
