### ISSUE TITLE
Feature request: Flutter tool change org (bundle identifier)

### ISSUE THREAD

**Issue by truongsinh** [flutter/flutter#29194] opened 2019-03-12 01:05 UTC
Refer to https://youtu.be/ht2bDlJd2c4?list=PLjxrf2q8roU3ahJVrSgAnPjzkpGmL9Czl&t=308 , it is recommended that we set the org as soon as we create new flutter project. If for some reason, later we want to change org, it's pain in the ass. Andrew said that there's even one value in base64 which is almost impossible to do quick "find in path".

Can we have flutter tool to do this task?

**Comment by jmagman** [comment] 2020-01-11 01:54
Duplicate of https://github.com/flutter/flutter/issues/13212.

**Closed by jmagman** 2020-01-11 01:54 UTC
Labels: severe: new feature, tool
