### ISSUE TITLE
[tool_crash] FormatException

### ISSUE THREAD

**Issue by dinakar0745** [flutter/flutter#159033] opened 2024-11-16 19:05 UTC
## Command
```sh
flutter pub get
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FormatException
```console
#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1465:5)
#1      _ChunkedJsonParser.close (dart:convert-patch/convert_patch.dart:499:7)
#2      _parseJson (dart:convert-patch/convert_patch.dart:37:10)
#3      JsonDecoder.convert (dart:convert/json.dart:610:36)
#4      JsonCodec.decode (dart:convert/json.dart:216:41)
#5      createPluginSymlinks (package:flutter_tools/src/flutter_plugins.dart:901:51)
#6      refreshPluginsList (package:flutter_tools/src/flutter_plugins.dart:1022:5)
<asynchronous suspension>
#7      FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:379:5)
<asynchronous suspension>
#8      PackagesGetCommand.runCommand (package:flutter_tools/src/commands/packages.dart:383:7)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1408:27)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#11     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:420:9)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:5)
<asynchronous suspension>
#15     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:130:9)
```
```console
[32m[✓][39m Flutter (Channel stable, 3.24.1, on Microsoft Windows [Version 10.0.26100.2314], locale en-IN)
    [32m•[39m Flutter version 3.24.1 on channel stable at C:\Users\Dinak\Dependencies\flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision 5874a72aa4 (3 months ago), 2024-08-20 16:46:00 -0500
    [32m•[39m Engine revision c9b9d5780d
    [32m•[39m Dart version 3.5.1
    [32m•[39m DevTools version 2.37.2

[32m[✓][39m Windows Version (Installed version of Windows is version 10 or higher)

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    [32m•[39m Android SDK at C:\Users\Dinak\AppData\Local\Android\Sdk
    [32m•[39m Platform android-34, build-tools 34.0.0
    [32m•[39m ANDROID_HOME = C:\Users\Dinak\AppData\Local\Android\Sdk
    [32m•[39m Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    [32m•[39m Java version OpenJDK Runtime Environment (build 21.0.3+-12282718-b509.11)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[32m[✓][39m Visual Studio - develop Windows apps (Visual Studio Community 2022 17.11.5)
    [32m•[39m Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    [32m•[39m Visual Studio Community 2022 version 17.11.35327.3
    [32m•[39m Windows 10 SDK version 10.0.22621.0

[32m[✓][39m Android Studio (version 2024.2)
    [32m•[39m Android Studio at C:\Program Files\Android\Android Studio
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 21.0.3+-12282718-b509.11)

[32m[✓][39m VS Code (version 1.95.3)
    [32m•[39m VS Code at C:\Users\Dinak\AppData\Local\Programs\Microsoft VS Code
    [32m•[39m Flutter extension version 3.100.0

[32m[✓][39m Connected device (3 available)
    [32m•[39m Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.26100.2314]
    [32m•[39m Chrome (web)      • chrome  • web-javascript • Google Chrome 130.0.6723.119
    [32m•[39m Edge (web)        • edge    • web-javascript • Microsoft Edge 130.0.2849.80

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[32m•[39m No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 5874a72aa4c779a02553007c47dacbefba2374dc
### Plugins
device_info_plus-10.1.2
file_selector_linux-0.9.3+1
file_selector_macos-0.9.4+2
file_selector_windows-0.9.3+3
flutter_pdfview-1.3.4
flutter_plugin_android_lifecycle-2.0.23
fluttertoast-8.2.8
image_picker-1.1.2
image_picker_android-0.8.12+17
image_picker_for_web-3.0.6
image_picker_ios-0.8.12+1
image_picker_linux-0.2.1+1
image_picker_macos-0.2.1+1
image_picker_windows-0.2.1+1
open_file-3.5.10
open_file_android-1.0.6
open_file_ios-1.0.3
open_file_linux-0.0.5
open_file_mac-1.0.3
open_file_web-0.0.4
open_file_windows-0.0.3
path_provider-2.1.5
path_provider_android-2.2.12
path_provider_foundation-2.4.0
path_provider_linux-2.2.1
path_provider_windows-2.3.0
pdfx-2.8.0
sqflite-2.4.1
sqflite_android-2.4.0
sqflite_darwin-2.4.1
url_launcher-6.3.1
url_launcher_android-6.3.14
url_launcher_ios-6.3.1
url_launcher_linux-3.2.1
url_launcher_macos-3.2.1
url_launcher_web-2.3.3
url_launcher_windows-3.1.3

**Comment by danagbemava-nc** [comment] 2024-11-18 07:02
Closing this as a duplicate of https://github.com/flutter/flutter/issues/98905

**Closed by danagbemava-nc** 2024-11-18 07:02 UTC
Labels: in triage
