### ISSUE TITLE
"flutter run" prints warning multiple times after switching Flutter SDK's

### ISSUE THREAD

**Issue by skybrian** [flutter/flutter#10765] opened 2017-06-16 02:28 UTC
When running a flutter app within IntelliJ just after switching Flutter SDK's, a rather verbose warning is printed twice. Also, it's often printed again the next time you stop and restart the Flutter app. (It eventually goes away, but I haven't seen a pattern to when that happens.)

Here's the console output:

```
Warning! The 'flutter' tool you are currently running is from a different Flutter
repository than the one last used by this package. The repository from which the
'flutter' tool is currently executing will be used instead.
  running Flutter tool: /Users/skybrian/software/flutter
  previous reference  : /Users/skybrian/dart/work/flutter
This can happen when you have multiple copies of flutter installed. Please check
your system path to verify that you are running the expected version (run
'flutter --version' to see which flutter is on your path).

Launching lib/main.dart on Android SDK built for x86 64 in debug mode...
Running 'gradle assembleDebug'...
Warning! The 'flutter' tool you are currently running is from a different Flutter
repository than the one last used by this package. The repository from which the
'flutter' tool is currently executing will be used instead.
  running Flutter tool: /Users/skybrian/software/flutter
  previous reference  : /Users/skybrian/dart/work/flutter
This can happen when you have multiple copies of flutter installed. Please check
your system path to verify that you are running the expected version (run
'flutter --version' to see which flutter is on your path).

Built build/app/outputs/apk/app-debug.apk (21.7MB).
Installing build/app/outputs/apk/app.apk...
Syncing files to device Android SDK built for x86 64...
```

This is using:

```
skybrian-macbookpro2:flutter skybrian$ flutter --version
Flutter • channel master • https://github.com/flutter/flutter.git
Framework • revision d6ec71d2c0 (18 minutes ago) • 2017-06-15 19:03:24 -0700
Engine • revision 18fdfb86bb
Tools • Dart 1.24.0-dev.6.7
```

**Comment by JFixby** [comment] 2017-07-07 14:28
Same for me.
There are two developers on a local Ubunti machine. Each has a flutter installation in his home dir. Seems like there is a conflict or smth.

**Comment by eseidelGoogle** [comment] 2017-07-11 16:32
I believe `flutter packages upgrade` should fix it?

Regardless we should offer "how to fix this" instructions as part of that error message.

**Comment by Hixie** [comment] 2017-07-11 16:36
The reason we see it twice is that gradle is for some reason recursively calling into `flutter`, which seems likely to cause other issues (we're not generally set up for `flutter` to be run recursively).

Having two developers edit the same directory with different flutter installations is a strange setup, I'm not sure there's any way for us to identify that that is what is going on. The fix differs based on how you end up in this situation; the common reason is that you have multiple copies of flutter installed, and the wrong one on your path, which the error message already tells you how to deal with.

**Comment by skybrian** [comment] 2017-07-11 18:49
I've seen this in the IDE when switching from one Flutter SDK to another in the project's settings. (For example, I had two flutter clones to test alpha versus master.) In that case, it's not clear that there is anything to fix or why there should be an error message at all, since the user is intentionally switching SDK's.

Maybe the IDE needs to automatically run `flutter packages upgrade` after the user changes the SDK?

**Comment by JFixby** [comment] 2017-07-11 20:55
It seems like there just need to be some more details in the error message.
Where is he getting the ```running Flutter tool``` and what is the ```previous reference```

**Comment by JFixby** [comment] 2017-07-31 18:51
Trying to publish with pub.
In pubsec.yaml replaced 
```
dependencies:
  flutter:
    sdk: flutter
```
with the
```
  flutter: "^0.0.20"
```
Unable to compile the project due to the missing ```import 'package:flutter/services.dart';```
Says
```
Warning! The 'flutter' tool you are currently running is from a different Flutter
repository than the one last used by this package. The repository from which the
'flutter' tool is currently executing will be used instead.
  running Flutter tool: D:\AndroidDev\flutter
  previous reference  : D:\PUB_CACHE\hosted
This can happen when you have multiple copies of flutter installed. Please check
your system path to verify that you are running the expected version (run
'flutter --version' to see which flutter is on your path).

```

**Comment by ScottS2017** [comment] 2018-05-03 01:54
In my case the issue tracked down to the fact that I should have been using a repo with git ignore set up properly. I had to go back and manually delete every build folder, lockfile for pubspec.yaml and all local files.

My project ties multiple projects into a larger folder, so it was a bit messier than most. In short, make sure that files local to one machine or the other aren't being checked into the repo. That may be your issue too.

Good luck

**Comment by shailendrapundhir** [comment] 2019-01-12 05:03
This issue can be fixed by running "flutter packages get" in the root directory of the project on the system. It worked for me.

**Comment by TUKenStone** [comment] 2019-02-11 18:17
> This issue can be fixed by running "flutter packages get" in the root directory of the project on the system. It worked for me.

Do "flutter packages get" whenever you switch from PC to macOS as this was the case with my project.

**Comment by Hixie** [comment] 2019-04-26 23:56
This and https://github.com/flutter/flutter/issues/21510 are duplicates of each other; this bug has more unrelated comments so I'm closing it as a dupe of the other.

**Closed by Hixie** 2019-04-26 23:56 UTC
Labels: tool

**Comment by ketanm** [comment] 2019-05-29 16:10
I ran into a similar issue when I moved my SDK to a different directory. 

Running `flutter --version` as suggested is not really helpful. As it also prints the same warning and shows versions not really path.
`Flutter 1.5.4-hotfix.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 7a4c33425d (4 weeks ago) • 2019-04-29 11:05:24 -0700
Engine • revision 52c7a1e849
Tools • Dart 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)`

Also running `flutter packages get` will throw following error.
`Could not find a command named "package".

Run 'flutter -h' (or 'flutter <command> -h') for available flutter commands and options.`

In order to fix the issue when you have moved your SDK folder is to go under your application folder and move or delete `.packages` file and then run `flutter packages get`. This will ensure that right packages are fetched under new location and paths are updated.

**Comment by Dougnkong** [comment] 2019-06-21 08:11
> > This issue can be fixed by running "flutter packages get" in the root directory of the project on the system. It worked for me.
> 
> Do "flutter packages get" whenever you switch from PC to macOS as this was the case with my project.

Nice ! Thanks a lot

**Comment by Dougnkong** [comment] 2019-06-21 08:12
> This issue can be fixed by running "flutter packages get" in the root directory of the project on the system. It worked for me.

Thanks

**Comment by taojigu** [comment] 2019-07-31 08:37
> This issue can be fixed by running "flutter packages get" in the root directory of the project on the system. It worked for me.

it works

**Comment by carfra** [comment] 2020-01-07 20:50
In my case, it worked when I deleted the .packages file and the build folder.

**Comment by michalliu** [comment] 2020-03-10 03:41
there are two settings in AS's preferences, search keyword "flutter" and "dart" point the dart-sdk and flutter tool to be same as your environment variable.
