### ISSUE TITLE
PopupMenuItem gets misplaced when inside a ReorderableListView>ListTile

### ISSUE THREAD

**Issue by ffeu** [flutter/flutter#25084] opened 2018-12-07 15:45 UTC
According to my tests, `PopupMenuItem` gets misplaced when inside a `ReorderableListView` > `ListTile` (triggered via a `PopupMenuButton`).

[Sample code to quickly get this tested is here](https://gist.github.com/ffeu/3bb8f9a2bcc1202a616ebb802b47f516).

Basically it puts items inside a `ListView` or `ReorderableListView`, you can toogle and see the different behavior. To make it easier to see, I'm adding screenshots of this test.

# example inside a ListView

![image](https://user-images.githubusercontent.com/13699202/49656725-2e296980-fa25-11e8-8227-da5d0336207b.png)

# example inside a ReorderableListView

![image](https://user-images.githubusercontent.com/13699202/49656743-3aadc200-fa25-11e8-823c-9e7e7afb140c.png)

### flutter doctor -v
```
[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.13.6 17G65, locale en-BR)
    • Flutter version 1.0.0 at /Users/feu/Projects/flutter
    • Framework revision 5391447fae (8 days ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/feu/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 27.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] VS Code (version 1.29.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.21.1

[✓] Connected device (1 available)
    • iPhone XR • B26EA355-B1DB-4A75-BBEA-47DD2F4B0AA8 • ios • iOS 12.1 (simulator)

• No issues found!
```

**Comment by charleshan** [comment] 2019-07-18 01:38
@zoechi I just came across this issue too. Did you find a workaround by any chance?

**Comment by ffeu** [comment] 2019-07-18 12:13
@charleshan

Check this out:

https://gist.github.com/ffeu/127c2b76d891fa12c9e2c831def785c4#gistcomment-2784730

**Comment by charleshan** [comment] 2019-07-18 20:23
@ffeu Thanks for sharing your solution. Works great!

**Comment by TahaTesser** [comment] 2020-04-29 14:48
duplicate of [#47013](https://github.com/flutter/flutter/issues/47013)

**Closed by TahaTesser** 2020-04-29 14:48 UTC
Labels: f: material design, framework
