### ISSUE TITLE
Pass version from pubspec.yaml to cmake

### ISSUE THREAD

**Issue by Dampfwalze** [flutter/flutter#98130] opened 2022-02-09 15:36 UTC
## Use case
The version specified in pubspec.yaml should be the only place to specify the version of your application, but because flutter doesn't provide this version to cmake when building for windows, I always have to put it in myself. This is not only annoying, but also error prone and there is no real reason, why cmake should not know the right version!
I personally use it in conjunction with cpack to generate msi packages.

## Proposal

You could pass some of the pubspec configuration like the version to cmake via cmake variables. You could prefix them with `FLUTTER_`.
Then you could have some variables like this, that are passed to cmake by flutter:
```cmake
FLUTTER_PROJECT_VERSION
FLUTTER_PROJECT_VERSION_MAJOR
FLUTTER_PROJECT_VERSION_MINOR
FLUTTER_PROJECT_VERSION_PATCH
FLUTTER_PROJECT_VERSION_TWEAK
```
And when the CMakeLists.txt is generated first, these variables are used, anywhere the version is needed.

**Comment by stuartmorgan** [comment] 2022-02-09 19:31
Duplicate of https://github.com/flutter/flutter/issues/73652

**Closed by stuartmorgan** 2022-02-09 19:31 UTC
