### ISSUE TITLE
[tool_crash] FileSystemException: Cannot create link, OS Error: Incorrect function., errno = 1

### ISSUE THREAD

**Issue by theharshguptaflutter** [flutter/flutter#132463] opened 2023-08-13 19:24 UTC
## Command
```
flutter pub get
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Cannot create link, OS Error: Incorrect function.
, errno = 1
```
#0      _Link.throwIfError (dart:io/link.dart:254:7)
#1      _Link.createSync (dart:io/link.dart:182:5)
#2      ForwardingLink.createSync (package:file/src/forwarding/forwarding_link.dart:20:16)
#3      ForwardingLink.createSync (package:file/src/forwarding/forwarding_link.dart:20:16)
#4      _createPlatformPluginSymlinks (package:flutter_tools/src/flutter_plugins.dart:1055:12)
#5      createPluginSymlinks (package:flutter_tools/src/flutter_plugins.dart:985:5)
#6      refreshPluginsList (package:flutter_tools/src/flutter_plugins.dart:1087:5)
<asynchronous suspension>
#7      FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:355:5)
<asynchronous suspension>
#8      PackagesGetCommand.runCommand (package:flutter_tools/src/commands/packages.dart:326:7)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1336:27)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#11     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:296:9)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:244:5)
<asynchronous suspension>
#15     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:91:9)
```
```
[✓] Flutter (Channel stable, 3.10.4, on Microsoft Windows [Version 10.0.19045.3208], locale en-GB)
    • Flutter version 3.10.4 on channel stable at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 682aa387cf (10 weeks ago), 2023-06-05 18:04:56 -0500
    • Engine revision 2a3401c9bb
    • Dart version 3.0.3
    • DevTools version 2.23.1

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\Surya\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop for Windows (Visual Studio Build Tools 2017 15.9.55)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools
    • Visual Studio Build Tools 2017 version 15.9.33801.237
    • Windows 10 SDK version 10.0.17763.0
    ✗ Visual Studio 2019 or later is required.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[✓] Android Studio (version 2022.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)

[✓] VS Code (version 1.81.1)
    • VS Code at C:\Users\Surya\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.70.0

[✓] Connected device (4 available)
    • RMX2156 (mobile)  • XW95VSLFS8VSGEDQ • android-arm64  • Android 12 (API 31)
    • Windows (desktop) • windows          • windows-x64    • Microsoft Windows [Version 10.0.19045.3208]
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 115.0.5790.171
    • Edge (web)        • edge             • web-javascript • Microsoft Edge 114.0.1823.82

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+3
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 4b12645012342076800eb701bcdfe18f87da21cf
### Plugins
facebook_auth_desktop-0.0.9
file_selector_linux-0.9.1+3
file_selector_macos-0.9.2
file_selector_windows-0.9.2
firebase_auth-4.6.3
firebase_auth_web-5.5.3
firebase_core-2.14.0
firebase_core_web-2.6.0
flutter_facebook_auth-5.0.11
flutter_facebook_auth_web-4.1.1
flutter_plugin_android_lifecycle-2.0.15
flutter_secure_storage-8.0.0
flutter_secure_storage_linux-1.1.3
flutter_secure_storage_macos-3.0.0
flutter_secure_storage_web-1.1.1
flutter_secure_storage_windows-2.0.0
fluttertoast-8.2.2
geocoding-2.0.4
geolocator-9.0.2
geolocator_android-4.2.2
geolocator_apple-2.2.7
geolocator_web-2.1.6
geolocator_windows-0.1.1
google_maps_flutter-2.3.0
google_maps_flutter_android-2.4.15
google_maps_flutter_ios-2.2.3
google_maps_flutter_web-0.5.0+1
google_sign_in-6.1.4
google_sign_in_android-6.1.16
google_sign_in_ios-5.6.2
google_sign_in_web-0.12.0+2
image_picker-0.8.9
image_picker_android-0.8.7
image_picker_for_web-2.2.0
image_picker_ios-0.8.8
image_picker_linux-0.2.1
image_picker_macos-0.2.1
image_picker_windows-0.2.1
onesignal_flutter-3.5.1
path_provider-2.0.15
path_provider_android-2.0.27
path_provider_foundation-2.2.3
path_provider_linux-2.1.11
path_provider_windows-2.1.7
permission_handler-10.4.3
permission_handler_android-10.3.2
permission_handler_apple-9.1.4
permission_handler_windows-0.1.3
shared_preferences-2.1.2
shared_preferences_android-2.1.4
shared_preferences_foundation-2.2.2
shared_preferences_linux-2.2.0
shared_preferences_web-2.1.0
shared_preferences_windows-2.2.0
smart_auth-1.0.8
url_launcher-6.1.11
url_launcher_android-6.0.35
url_launcher_ios-6.1.4
url_launcher_linux-3.0.5
url_launcher_macos-3.0.5
url_launcher_web-2.0.17
url_launcher_windows-3.0.6
video_player-2.6.1
video_player_android-2.4.9
video_player_avfoundation-2.4.6
video_player_web-2.0.16

**Comment by danagbemava-nc** [comment] 2023-08-14 08:59
Closing this as a duplicate of https://github.com/flutter/flutter/issues/66224

**Closed by danagbemava-nc** 2023-08-14 08:59 UTC
Labels: in triage
