### ISSUE TITLE
"AutofillHints.telephoneNumber + TextInputType.phone" android bug

### ISSUE THREAD

**Issue by furaiev** [flutter/flutter#76126] opened 2021-02-16 17:10 UTC
## Steps to Reproduce

1. Create a new Flutter project
2. Add 2 TextFormField with `autofillHints: const <String>[AutofillHints.telephoneNumber]`
3. Add to one of fields `keyboardType: TextInputType.phone`
4. Run app on Android
5. Autofill the field with a standard `text` keyboardType
6. Autofill the field with the `keyboardType: TextInputType.phone`

**Expected results:** both fields are successfully filled in

**Actual results:** 
- a field with  standard `text` keyboardType - successfully filled in
- a field with the `keyboardType: TextInputType.phone` is filled in but not rendered with a value (`onChanged` callback also doesn't called)

![ezgif com-gif-maker](https://user-images.githubusercontent.com/33546696/108097237-8be88000-708a-11eb-91ab-28bc72acee49.gif)

<details>
  <summary>Code</summary>

```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Padding(
          padding: const EdgeInsets.all(8.0),
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              TextFormField(
                decoration:
                    InputDecoration(labelText: 'Phone with TextInputType.text'),
                autofillHints: const <String>[AutofillHints.telephoneNumber],
                keyboardType: TextInputType.text,
                onChanged: print,
              ),
              TextFormField(
                decoration: InputDecoration(
                    labelText: 'Phone with TextInputType.phone'),
                autofillHints: const <String>[AutofillHints.telephoneNumber],
                keyboardType: TextInputType.phone,
                onChanged: print,
              ),
            ],
          ),
        ),
      ),
    );
  }
}

```

</details>

**Comment by HansMuller** [comment] 2021-02-16 18:11
CC @LongCatIsLooong

**Comment by chinmoy12c** [comment] 2021-02-16 21:04
Similar issues #75418, #75833

**Comment by pedromassangocode** [comment] 2021-02-17 09:24
Closing this as duplicate of https://github.com/flutter/flutter/issues/75833. For anyone interested in this issue please follow up on the issue mentioned.
Thank you

**Closed by pedromassangocode** 2021-02-17 09:24 UTC
Labels: a: text input, f: material design, framework
