### ISSUE TITLE
Cannot read property 'AudioSessionWeb' of undefined

### ISSUE THREAD

**Issue by alihabbash** [flutter/flutter#79451] opened 2021-03-31 14:19 UTC
Steps to produce:
- Run the command ```flutter create .``` on my fully working existing app (Working on ios and android).
- Run the app on the browser.
- Got Cannot read property 'AudioSessionWeb' of undefined error.
 My flutter SDK version is 2.0.2 on the stable channel and installed on Windows 10.
 Also, I don't have the ```Audio_sessions``` package imported in my pubspec.yaml
 
 The full log message is:

```

TypeError: Cannot read property 'AudioSessionWeb' of undefined
    at Object.registerPlugins (http://localhost:10741/packages/flutter_app/generated_plugin_registrant.dart.lib.js:32:23)
    at main (http://localhost:10741/web_entrypoint.dart.lib.js:44:35)
    at main.next (<anonymous>)
    at runBody (http://localhost:10741/dart_sdk.js:39052:34)
    at Object._async [as async] (http://localhost:10741/dart_sdk.js:39083:7)
    at main$ (http://localhost:10741/web_entrypoint.dart.lib.js:43:18)
    at http://localhost:10741/main_module.bootstrap.js:19:10
    at Array.forEach (<anonymous>)
    at window.$dartRunMain (http://localhost:10741/main_module.bootstrap.js:18:32)
    at <anonymous>:1:8
    at Object.runMain (http://localhost:10741/dwds/src/injected/client.js:8656:21)
    at http://localhost:10741/dwds/src/injected/client.js:22068:19
    at _wrapJsFunctionForAsync_closure.$protected (http://localhost:10741/dwds/src/injected/client.js:3830:15)
    at _wrapJsFunctionForAsync_closure.call$2 (http://localhost:10741/dwds/src/injected/client.js:10905:12)
    at Object._asyncStartSync (http://localhost:10741/dwds/src/injected/client.js:3794:20)
    at main__closure1.$call$body$main__closure (http://localhost:10741/dwds/src/injected/client.js:22080:16)
    at main__closure1.call$1 (http://localhost:10741/dwds/src/injected/client.js:22007:19)
    at StaticClosure._rootRunUnary [as call$2$5] (http://localhost:10741/dwds/src/injected/client.js:4153:16)
    at _CustomZone.runUnary$2$2 (http://localhost:10741/dwds/src/injected/client.js:12136:39)
    at _CustomZone.runUnaryGuarded$1$2 (http://localhost:10741/dwds/src/injected/client.js:12068:14)
    at _ControllerSubscription._sendData$1 (http://localhost:10741/dwds/src/injected/client.js:11697:19)
    at _DelayedData.perform$1 (http://localhost:10741/dwds/src/injected/client.js:11849:59)
    at _PendingEvents_schedule_closure.call$0 (http://localhost:10741/dwds/src/injected/client.js:11898:14)
    at Object._microtaskLoop (http://localhost:10741/dwds/src/injected/client.js:3990:24)
    at StaticClosure._startMicrotaskLoop (http://localhost:10741/dwds/src/injected/client.js:3996:11)
    at _AsyncRun__initializeScheduleImmediate_internalCallback.call$1 (http://localhost:10741/dwds/src/injected/client.js:10774:9)
    at invokeClosure (http://localhost:10741/dwds/src/injected/client.js:1250:26)
    at MutationObserver.<anonymous> (http://localhost:10741/dwds/src/injected/client.js:1269:18)

```

**Comment by TahaTesser** [comment] 2021-03-31 14:30
HI @alihabbash 
Can you please provide your `flutter doctor -v` and `flutter run -d chrome --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
Also, be sure to provide step by steps to reproduce the issue
Thank you

**Comment by erickzanardo** [comment] 2021-03-31 20:44
It seems that this problem is not on Flutter itself, but with the `audio_session` package.

Even though you mentioned that you don't directly import it on your pubspec, it seems that it is a transitive dependency of your project because, probably because of some other package you have that depends on it.

You can verify that by running `flutter pub deps` on your project, that will print your dependency tree and you will be able to determine why `audio_session` is in your project.

**Comment by TahaTesser** [comment] 2021-04-01 08:34
Hi @alihabbash 
That makes sense, it could be one of your packages using this third-party package 
Please follow the above comment and isolate the issue,  file an issue on that third-party package's repository

Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-04-01 08:34 UTC
Labels: in triage

**Comment by alihabbash** [comment] 2021-04-01 09:27
> It seems that this problem is not on Flutter itself, but with the `audio_session` package.
> 
> Even though you mentioned that you don't directly import it on your pubspec, it seems that it is a transitive dependency of your project because, probably because of some other package you have that depends on it.
> 
> You can verify that by running `flutter pub deps` on your project, that will print your dependency tree and you will be able to determine why `audio_session` is in your project.

Hi @erickzanardo, I ran it and it seems that `Flame` package is depending on it and you are right it's not a problem with flutter itself.
Thanks for your help @TahaTesser ,and @erickzanardo
