### ISSUE TITLE
'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 571 pos 12: '_drag == null' is not true

### ISSUE THREAD

**Issue by CoderXiaoming** [flutter/flutter#67810] opened 2020-10-10 08:16 UTC
Scrolling through the list, this error occurs occasionally

`[+178440 ms] flutter: ══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
[   +6 ms] flutter: The following assertion was thrown while handling a gesture:
[        ] flutter: 'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 571 pos 12: '_drag == null':
[        ] flutter: is not true.
[        ] flutter:
[        ] flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
[        ] flutter: more information in this error message to help you determine and fix the underlying cause.
[        ] flutter: In either case, please report this assertion by filing a bug on GitHub:
[        ] flutter:   https://github.com/flutter/flutter/issues/new?template=BUG.md
[        ] flutter:
[        ] flutter: When the exception was thrown, this was the stack:
[        ] flutter: #2      ScrollableState._handleDragDown (package:flutter/src/widgets/scrollable.dart:571:12)
[        ] flutter: #3      DragGestureRecognizer._checkDown.<anonymous closure> (package:flutter/src/gestures/monodrag.dart:401:51)
[   +9 ms] flutter: #4      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:183:24)
[        ] flutter: #5      DragGestureRecognizer._checkDown (package:flutter/src/gestures/monodrag.dart:401:7)
[        ] flutter: #6      DragGestureRecognizer.addAllowedPointer (package:flutter/src/gestures/monodrag.dart:264:7)
[        ] flutter: #7      GestureRecognizer.addPointer (package:flutter/src/gestures/recognizer.dart:103:7)
[        ] flutter: #8      RawGestureDetectorState._handlePointerDown (package:flutter/src/widgets/gesture_detector.dart:1205:18)
[        ] flutter: #9      RenderPointerListener.handleEvent (package:flutter/src/rendering/proxy_box.dart:2718:28)
[        ] flutter: #10     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:338:22)
[        ] flutter: #11     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:267:11)
[        ] flutter: #12     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:295:7)
[   +3 ms] flutter: #13     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:240:7)
[        ] flutter: #14     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:213:7)
[        ] flutter: #18     _invoke1 (dart:ui/hooks.dart:265:10)
[        ] flutter: #19     _dispatchPointerDataPacket (dart:ui/hooks.dart:174:5)
[        ] flutter: (elided 5 frames from class _AssertionError and dart:async)
[        ] flutter:
[        ] flutter: Handler: "onDown"
[        ] flutter: Recognizer:
[        ] flutter:   VerticalDragGestureRecognizer#53c7d
[        ] flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
[  +15 ms] flutter: Another exception was thrown: 'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 580 pos 12: '_drag == null': is not true.
`

**Comment by CoderXiaoming** [comment] 2020-10-10 08:17
`
[+178440 ms] flutter: ══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
[   +6 ms] flutter: The following assertion was thrown while handling a gesture:
[        ] flutter: 'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 571 pos 12: '_drag == null':
[        ] flutter: is not true.
[        ] flutter:
[        ] flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
[        ] flutter: more information in this error message to help you determine and fix the underlying cause.
[        ] flutter: In either case, please report this assertion by filing a bug on GitHub:
[        ] flutter:   https://github.com/flutter/flutter/issues/new?template=BUG.md
[        ] flutter:
[        ] flutter: When the exception was thrown, this was the stack:
[        ] flutter: #2      ScrollableState._handleDragDown (package:flutter/src/widgets/scrollable.dart:571:12)
[        ] flutter: #3      DragGestureRecognizer._checkDown.<anonymous closure> (package:flutter/src/gestures/monodrag.dart:401:51)
[   +9 ms] flutter: #4      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:183:24)
[        ] flutter: #5      DragGestureRecognizer._checkDown (package:flutter/src/gestures/monodrag.dart:401:7)
[        ] flutter: #6      DragGestureRecognizer.addAllowedPointer (package:flutter/src/gestures/monodrag.dart:264:7)
[        ] flutter: #7      GestureRecognizer.addPointer (package:flutter/src/gestures/recognizer.dart:103:7)
[        ] flutter: #8      RawGestureDetectorState._handlePointerDown (package:flutter/src/widgets/gesture_detector.dart:1205:18)
[        ] flutter: #9      RenderPointerListener.handleEvent (package:flutter/src/rendering/proxy_box.dart:2718:28)
[        ] flutter: #10     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:338:22)
[        ] flutter: #11     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:267:11)
[        ] flutter: #12     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:295:7)
[   +3 ms] flutter: #13     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:240:7)
[        ] flutter: #14     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:213:7)
[        ] flutter: #18     _invoke1 (dart:ui/hooks.dart:265:10)
[        ] flutter: #19     _dispatchPointerDataPacket (dart:ui/hooks.dart:174:5)
[        ] flutter: (elided 5 frames from class _AssertionError and dart:async)
[        ] flutter:
[        ] flutter: Handler: "onDown"
[        ] flutter: Recognizer:
[        ] flutter:   VerticalDragGestureRecognizer#53c7d
[        ] flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
[  +15 ms] flutter: Another exception was thrown: 'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 580 pos 12: '_drag == null': is not true.


`

**Comment by Abhishek01039** [comment] 2020-10-10 09:24
Hi @CoderXiaoming 
Maybe duplication of https://github.com/flutter/flutter/issues/65020

**Comment by iapicca** [comment] 2020-10-10 12:11
@CoderXiaoming 
I think @Abhishek01039 is probably right,
and given that the problem in that issue was caused by the reporter's implementation
can you provide a minimal reproducible code sample

**Comment by pedromassangocode** [comment] 2020-10-20 10:18
Hi @CoderXiaoming 
As said above we still need a reproducible code sample to better evaluate this issue.

**Comment by pedromassangocode** [comment] 2020-11-11 10:17
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2020-11-11 10:17 UTC
Labels: in triage

**Comment by kim-king-rong** [comment] 2021-01-19 01:48
I also encountered the same problem “The following assertion was thrown while handling a gesture:
'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 571 pos 12: '_drag == null': is not true.”

I found that it may be that when I disabling sliding, the critical point change was not handled correctly. But I am not proficient in Flutter, so I haven't solved it yet.

The following my code structure, I hope to express my main logical design, 
The bold part should be the main code that caused the problem
The structure is as follows： 

//
//...slideHand() async {
//...
//...    
//...  }
//....@override
//....  void initState() {
//....    _gridController = ScrollController()
      ..addListener(() {
        if (_gridController?.position?.pixels == 0 && !_headerStatus.isPullUp) {
          **_headerStatus.isDisableList = true;
          _headerSTSink.add(_headerStatus);**
        }
      });
    //....
    //....
    //....
    //....
    //....
    //....
    super.initState();
  }

------ ui
@override
  Widget build(BuildContext context) {
    return Listener(
      onPointerDown: (event) {
        //....
        //....
      },
      onPointerMove: (event) {
        //....
        //....
        slideHand();
      },
      onPointerUp: (event) async {
        //....
        //....
        await slideHand();
        //....
        //....
        //....
        //....
      },
      child: SafeArea(
          child: StreamBuilder<Object>(
              stream: _headerST,
              builder: (context, snapshot) {
                return Container(
                  child: Stack(
                    children: [
                      Container(
                        height: 300,
                        width: MediaQuery.of(context).size.width,
                      ),
                      Positioned(
                        top: _headerStatus.changeScale * 200 + 50,
                        child: Container(
                          child: GridView.builder(
                              **physics: _headerStatus.isDisableList
                                  ? const NeverScrollableScrollPhysics()
                                  : null,**
                              itemBuilder: (BuildContext context, int index) {
                                return Container();
                              }),
                        ),
                      )
                    ],
                  ),
                );
              })),
    );
  }
}
If you can understand what I am doing, and have a solution. I hope to help me solve it, I am learning flutter, thank you
