### ISSUE TITLE
[macOS]TextField plays alert sound when pressing arrow keys to select alternative words in Pinyin - Simplified Input Source

### ISSUE THREAD

**Issue by fanpei91** [flutter/flutter#137005] opened 2023-10-21 09:36 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Use macOS
2. Switch Input Source to **Pinyin - Simplified**
3. Type **nihao**
4. Select any words by pressing arrow **left**, **right**, **up**, or **down** keys

### Expected results

Don't play alert sound.

### Actual results

It plays alert sound.

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: Scaffold(
        appBar: AppBar(
          backgroundColor: Theme.of(context).colorScheme.inversePrimary,
          title: const Text('Title'),
        ),
        body: const Center(
          child: TextField(
            maxLines: null,
          ),
        ),
      ),
    );
  }
}

```
</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

https://github.com/flutter/flutter/assets/5484841/dd20bc60-3093-4723-948c-270a61609155

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.13.8, on macOS 13.0.1 22A400 darwin-x64, locale en-CN)
    • Flutter version 3.13.8 on channel stable at /Users/fan/.fvm/versions/3.13.8
    • Upstream repository git@github.com:flutter/flutter.git
    • Framework revision 6c4930c4ac (3 days ago), 2023-10-18 10:57:55 -0500
    • Engine revision 767d8c75e8
    • Dart version 3.1.4
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/fan/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /Applications/Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 74.0.4
    • Dart plugin version 231.9161.14

[✓] VS Code (version 1.82.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.72.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 113.0.5672.126

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by darshankawar** [comment] 2023-10-23 06:56
Thanks for the report @fanpei91 
I am unable to replicate the reported behavior. See below video in which the alert sound doesn't play while navigating through the words.


https://github.com/flutter/flutter/assets/67046386/e36c6f6e-3de3-4ec1-bc06-6b039de0c09d

**Comment by fanpei91** [comment] 2023-10-25 07:55
Are you sure you enabled audio recording? Because I can't hear the sound of your keyboard typing. The audio button is disabled in your video. 

I navigate in macOS Notes, it doesn't produce any alert sounds.

@darshankawar

**Comment by fanpei91** [comment] 2023-10-25 09:12
I have studied the related Flutter framework source code. When navigating in the Input Source to select words, the KeyEventResult is `skipRemainingHandlers`, it makes the var `handled` in `KeyEventManager.handleRawKeyMessage()` `false`, and send the `false` to Flutter Engine by SystemChannels so it maybe the reason playing alert sound.

I think its design (sending `true` or `false`) must be refactored by sending `ignore`, `handled`, or `skipRemainingHandlers` to Flutter Engine.

**Comment by darshankawar** [comment] 2023-10-26 05:44
Thanks for the update @fanpei91 
I realized that when I verified it earlier, I was on master version wherein, the alert sound doesn't occur, while, it occurs on stable version which I verified now and confirmed.
Since it works as expected on master version, it is considered to be fixed and based on our triage policy I'll close this issue as not an issue. You may switch to latest master and run your scenario to confirm at your end, at the alert sound doesn't play, as expected.
If you disagree, write in comments and I'll reopen it.

**Closed by darshankawar** 2023-10-26 05:44 UTC
Labels: in triage
