### ISSUE TITLE
Circular border around container has hairline of background color

### ISSUE THREAD

**Issue by davidbrenner** [flutter/flutter#61218] opened 2020-07-10 07:42 UTC
## Steps to Reproduce

If I create a circular shaped container and add a border, the black background of the container shows behind the border around the outside of the container.

```
            Container(
              alignment: Alignment.center,
              width: 100,
              height: 100,
              decoration: BoxDecoration(
                shape: BoxShape.circle,
                color: Colors.black,
                border: Border.all(width: 6.0, color: Colors.white),
              ),
            ),
```

**Expected results:**

I expect that the border completely covers the background of the container, so that no harline is visible around the outer edge.

**Actual results:** 

![2020-07-10_03-40](https://user-images.githubusercontent.com/236870/87129459-5ca1a300-c25f-11ea-9c2c-ed1920451f8d.png)

<details>
  <summary>Logs</summary>

```
$ flutter analyze
Analyzing bug...                                                        
No issues found! (ran in 1.9s)
```

```
$ flutter doctor -v
[✓] Flutter (Channel stable, v1.17.5, on Linux, locale en_US.UTF-8)
    • Flutter version 1.17.5 at /home/davidb/devtools/flutter
    • Framework revision 8af6b2f038 (10 days ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /home/davidb/Android/Sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /home/davidb/devtools/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Android Studio (version 4.0)
    • Android Studio at /home/davidb/devtools/android-studio
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

• No issues found!
```

</details>

**Comment by TahaTesser** [comment] 2020-07-10 09:14
<details> 
<summary>Code Sample</summary> 

``` 
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      // theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Color(0x000000),
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: Container(
          alignment: Alignment.center,
          width: 100,
          height: 100,
          decoration: BoxDecoration(
            shape: BoxShape.circle,
            color: Color(0x000000),
            border: Border.all(width: 6.0, color: Color(0x000000)),
          ),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.adb),
        onPressed: () {},
      ),
    );
  }
}
``` 

</details> 

<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel dev, 1.20.0-7.0.pre, on Mac OS X 10.15.5 19F101, locale en-GB)
    • Flutter version 1.20.0-7.0.pre at /Users/taha/Code/flutter_dev
    • Framework revision cc1af3afb6 (2 days ago), 2020-07-08 10:19:36 -0700
    • Engine revision 0dc86cda19
    • Dart version 2.9.0 (build 2.9.0-20.0.dev 06cb010247)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/taha/Code/sdk
    • Platform android-30, build-tools 30.0.0
    • ANDROID_HOME = /Users/taha/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

 
[✓] Connected device (4 available)            
    • SM M305F (mobile) • 32003c30dc19668f • android-arm64  • Android 10 (API 29)
    • macOS (desktop)   • macos            • darwin-x64     • Mac OS X 10.15.5 19F101
    • Web Server (web)  • web-server       • web-javascript • Flutter Tools
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 83.0.4103.116

• No issues found!

``` 

</details>

**Comment by goderbauer** [comment] 2020-07-15 21:59
This looks like an anti-aliasing issue. I am going to close it as a duplicate of https://github.com/flutter/flutter/issues/59798.

**Closed by goderbauer** 2020-07-15 21:59 UTC
Labels: a: quality, engine, found in release: 1.17, found in release: 1.20, framework, has reproducible steps, severe: rendering
