### ISSUE TITLE
TrackingScrollController does not work when both lists are visible

### ISSUE THREAD

**Issue by aryzhov** [flutter/flutter#29439] opened 2019-03-15 16:54 UTC
The documentation for `TrackingScrollController` has an example that shows `ListView` widgets inside a `PageView`. That example works, but if you replace `PageView` with `Row` in order to make all three lists visible at once, the lists become completely disjoined: 

```dart
      Row(
        children: <Widget>[
          Expanded(
            child: ListView(
              controller: _trackingScrollController,
              children: List<Widget>.generate(100, (int i) => Text('page 0 item $i')).toList(),
            ),
          ),
          Expanded(
            child: ListView(
              controller: _trackingScrollController,
              children: List<Widget>.generate(200, (int i) => Text('page 1 item $i')).toList(),
            ),
          ),
          Expanded(
            child: ListView(
             controller: _trackingScrollController,
             children: List<Widget>.generate(300, (int i) => Text('page 2 item $i')).toList(),
            ),
          ),
        ],
      )
```

![TrackingScrollController](https://user-images.githubusercontent.com/618258/54447817-97e19f80-4707-11e9-8250-a955156cfc52.gif)

### flutter doctor
flutter_app $ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v1.3.10, on Mac OS X 10.13.6 17G5019, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.3)
[!] VS Code (version 1.30.1)
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[✓] Connected device (1 available)

! Doctor found issues in 1 category.

**Comment by aryzhov** [comment] 2019-03-15 16:56
The complete `main.dart` to reproduce the problem:

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final _trackingScrollController = TrackingScrollController();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text("TrackingScrollController + ListView")),
      body: Row(
        children: <Widget>[
          Expanded(
            child: ListView(
              controller: _trackingScrollController,
              children: List<Widget>.generate(100, (int i) => Text('page 0 item $i')).toList(),
            ),
          ),
          Expanded(
            child: ListView(
              controller: _trackingScrollController,
              children: List<Widget>.generate(200, (int i) => Text('page 1 item $i')).toList(),
            ),
          ),
          Expanded(
            child: ListView(
             controller: _trackingScrollController,
             children: List<Widget>.generate(300, (int i) => Text('page 2 item $i')).toList(),
            ),
          ),
        ],
      ),
    );
  }
}
```

**Comment by Flonko** [comment] 2019-04-18 15:29
Same issue here.

**Comment by iapicca** [comment] 2019-11-07 13:33
Hi @aryzhov 
are you still experiencing this issue with the latest version of Flutter?
If so can you please provide your `flutter doctor -v`?
Thank you

**Comment by iapicca** [comment] 2019-11-29 16:06
Hi @aryzhov 
[TrackingScrollController ](https://gist.github.com/iapicca/2eb9d77d4ed1db4df1e66badcb38420a) seems working with the latest stable version.

I feel safe to close this issue,
if you disagree please write in the comments
and I will reopen it. 
Thank you

**Closed by iapicca** 2019-11-29 16:06 UTC
Labels: documentation, f: scrolling, framework

**Comment by Flonko** [comment] 2019-11-30 10:51
Hi @iapicca 
the above example [issuecomment-473363805](https://github.com/flutter/flutter/issues/29439#issuecomment-473363805) still doesn't work with the latest flutter version.

Flutter doctor output:
`[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Linux, locale en_US.UTF-8)
    • Flutter version 1.9.1+hotfix.6 at /home/nzedler/Development/flutter
    • Framework revision 68587a0916 (3 months ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/nzedler/Development/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /home/nzedler/Development/Android/Sdk
    • Java binary at: /home/nzedler/Development/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Android Studio (version 3.5)
    • Android Studio at /home/nzedler/Development/android-studio
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.40.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.6.0

[✓] Connected device (1 available)
    • VTR L09 • WPG7N17210005882 • android-arm64 • Android 9 (API 28)

• No issues found!
Process finished with exit code 0`

**Comment by Hixie** [comment] 2019-12-02 18:31
This is working as intended. TrackingScrollController doesn't attempt to keep anything synchronized, it just tries to keep the last scrolled position as the _initial_ scroll position, so that when a new list is created it ends up with the position that the last one had.

**Comment by fryette** [comment] 2020-12-28 16:44
A bit rewritten solution. Now all controllers in sync.

```
class TrackingScrollController extends ScrollController {
  /// Creates a scroll controller that continually updates its
  /// [initialScrollOffset] to match the last scroll notification it received.
  TrackingScrollController({
    double initialScrollOffset = 0.0,
    bool keepScrollOffset = true,
    String debugLabel,
  }) : super(
            initialScrollOffset: initialScrollOffset,
            keepScrollOffset: keepScrollOffset,
            debugLabel: debugLabel);

  final Map<ScrollPosition, VoidCallback> _positionToListener =
      <ScrollPosition, VoidCallback>{};
  ScrollPosition _lastUpdated;
  double _lastUpdatedOffset;

  /// The last [ScrollPosition] to change. Returns null if there aren't any
  /// attached scroll positions, or there hasn't been any scrolling yet, or the
  /// last [ScrollPosition] to change has since been removed.
  ScrollPosition get mostRecentlyUpdatedPosition => _lastUpdated;

  /// Returns the scroll offset of the [mostRecentlyUpdatedPosition] or, if that
  /// is null, the initial scroll offset provided to the constructor.
  ///
  /// See also:
  ///
  /// * [ScrollController.initialScrollOffset], which this overrides.
  @override
  double get initialScrollOffset =>
      _lastUpdatedOffset ?? super.initialScrollOffset;

  @override
  void attach(ScrollPosition position) {
    super.attach(position);

    assert(!_positionToListener.containsKey(position));
    _positionToListener[position] = () {
      if (_lastUpdated != position) {
        (_lastUpdated as EpgScrollPosition)?.goIdle();
      }

      _lastUpdated = position;
      _lastUpdatedOffset = position.pixels;

      _positionToListener.entries.forEach((element) {
        if (element.key != position) {
          element.key.correctBy(_lastUpdatedOffset - element.key.pixels);
        }
      });
    };
    position.addListener(_positionToListener[position]);
  }

  @override
  void detach(ScrollPosition position) {
    super.detach(position);
    assert(_positionToListener.containsKey(position));
    position.removeListener(_positionToListener[position]);
    _positionToListener.remove(position);
    if (_lastUpdated == position) _lastUpdated = null;
    if (_positionToListener.isEmpty) _lastUpdatedOffset = null;
  }

  @override
  void dispose() {
    for (final ScrollPosition position in positions) {
      assert(_positionToListener.containsKey(position));
      position.removeListener(_positionToListener[position]);
    }
    super.dispose();
  }
}

```
