### ISSUE TITLE
unhappy loo

### ISSUE THREAD

**Issue by fnfufnfu** [flutter/flutter#46921] opened 2019-12-12 23:59 UTC
'package:flutter/src/widgets/navigator.dart': Failed assertion: line 2330 pos 12: '!_debugLocked': is not true.
![e](https://user-images.githubusercontent.com/38098031/70758591-7e48b380-1d7e-11ea-85d3-e4b810f62d87.png)

**Comment by fnfufnfu** [comment] 2019-12-13 00:01
big god‘s，pleace help help me，wanna die hreat both have;

**Comment by jmagman** [comment] 2019-12-13 01:48
Probably a duplicate of https://github.com/flutter/flutter/issues/36177.

**Closed by jmagman** 2019-12-13 01:48 UTC
Labels: created via support template
