### ISSUE TITLE
Unable to run the example on the android_alarm_manager

### ISSUE THREAD

**Issue by rahulgul8** [flutter/flutter#20797] opened 2018-08-19 16:14 UTC
When trying to run the example project on the android_alarm_manager I get the following exception. 

```
Launching lib\main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...
Resolving dependencies...
Running 'gradlew assembleDebug'...
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
C:\code\experiments\android\plugins-master\packages\android_alarm_manager\android\src\main\java\io\flutter\plugins\androidalarmmanager\AlarmService.java:16: error: cannot find symbol
import io.flutter.view.FlutterCallbackInformation;
                      ^
  symbol:   class FlutterCallbackInformation
  location: package io.flutter.view
C:\code\experiments\android\plugins-master\packages\android_alarm_manager\android\src\main\java\io\flutter\plugins\androidalarmmanager\AlarmService.java:19: error: cannot find symbol
import io.flutter.view.FlutterRunArguments;
                      ^
  symbol:   class FlutterRunArguments
  location: package io.flutter.view
C:\code\experiments\android\plugins-master\packages\android_alarm_manager\android\src\main\java\io\flutter\plugins\androidalarmmanager\AlarmService.java:47: error: cannot find symbol
    FlutterCallbackInformation cb =
    ^
  symbol:   class FlutterCallbackInformation
  location: class AlarmService
C:\code\experiments\android\plugins-master\packages\android_alarm_manager\android\src\main\java\io\flutter\plugins\androidalarmmanager\AlarmService.java:48: error: cannot find symbol
        FlutterCallbackInformation.lookupCallbackInformation(callbackHandle);
        ^
  symbol:   variable FlutterCallbackInformation
  location: class AlarmService
C:\code\experiments\android\plugins-master\packages\android_alarm_manager\android\src\main\java\io\flutter\plugins\androidalarmmanager\AlarmService.java:57: error: constructor FlutterNativeView in class FlutterNativeView cannot be applied to given types;
    sBackgroundFlutterView = new FlutterNativeView(context, true);
                             ^
  required: Context
  found: Context,boolean
  reason: actual and formal argument lists differ in length
C:\code\experiments\android\plugins-master\packages\android_alarm_manager\android\src\main\java\io\flutter\plugins\androidalarmmanager\AlarmService.java:60: error: cannot find symbol
      FlutterRunArguments args = new FlutterRunArguments();
      ^
  symbol:   class FlutterRunArguments
  location: class AlarmService
C:\code\experiments\android\plugins-master\packages\android_alarm_manager\android\src\main\java\io\flutter\plugins\androidalarmmanager\AlarmService.java:60: error: cannot find symbol
      FlutterRunArguments args = new FlutterRunArguments();
                                     ^
  symbol:   class FlutterRunArguments
  location: class AlarmService
7 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':android_alarm_manager:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s
Finished with error: Gradle build failed: 1

```

My flutter doctor's output is as follows. 

```
C:\softwares\flutter\bin\flutter.bat --no-color doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v0.5.1, on Microsoft Windows [Version 10.0.16299.611], locale en-ZA)
[√] Android toolchain - develop for Android devices (Android SDK 28.0.0)
[√] Android Studio (version 3.1)
[!] VS Code, 64-bit edition (version 1.24.0)
[√] Connected devices (1 available)

! Doctor found issues in 1 category.
Process finished with exit code 0
```

**Comment by zoechi** [comment] 2018-08-19 17:32
Please try with `master` or `dev` channel
```
flutter channel master
flutter doctor
```

**Comment by rahulgul8** [comment] 2018-08-19 19:37
### Now the issue is fixed. I am able to run the android_alarm_manager example. I have documented the steps below.  

Thanks **Zoechi**

Running `flutter channel master` gave me the following . 

```
Switching to flutter channel 'master'...
git: Branch 'master' set up to track remote branch 'master' from 'origin'.
git: Switched to a new branch 'master'
'seconds...' is not recognized as an internal or external command,
operable program or batch file.

Waiting for 0 seconds, press CTRL+C to quit ...
Running pub upgrade...
Resolving dependencies...
The current Dart SDK version is 2.0.0-dev.58.0.flutter-f981f09760.

Because android_alarm_manager depends on flutter any from sdk which requires SDK version >=2.0.0-dev.68.0 <3.0.0, version solving failed.
Error Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (-1 tries left)

Waiting for 0 seconds, press CTRL+C to quit ...
Running pub upgrade...
Resolving dependencies...
The current Dart SDK version is 2.0.0-dev.58.0.flutter-f981f09760.

```

It kept on retrying and I had to quit it. 

Then I ran `flutter doctor`

which gave the following output. 

```
flutter doctor
Checking Dart SDK version...
Downloading Dart SDK from Flutter engine 03f8ba51e3d4d2f4de7875fe1607d781bf0a7409...
Unzipping Dart SDK...
Building flutter tool...
Running pub upgrade...
Failed to rename directory because access was denied.
This may be caused by a virus scanner or having a file
in the directory open in another application.
Error Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (9 tries left)

Waiting for 0 seconds, press CTRL+C to quit ...
Running pub upgrade...
Downloading package sky_engine...                            8,3s
Downloading common tools...                                 46,0s
Downloading windows-x64 tools...                            120,6s
Downloading android-arm-profile/windows-x64 tools...        17,3s
Downloading android-arm-release/windows-x64 tools...        16,1s
Downloading android-arm64-profile/windows-x64 tools...      20,8s
Downloading android-arm64-release/windows-x64 tools...      18,8s
Downloading android-x86 tools...                            109,3s
Downloading android-x64 tools...                            113,5s
Downloading android-arm tools...                            51,4s
Downloading android-arm-profile tools...                    44,0s
Downloading android-arm-release tools...                    34,6s
Downloading android-arm64 tools...                          56,2s
Downloading android-arm64-profile tools...                  47,8s
Downloading android-arm64-release tools...                  38,5s
Downloading android-arm-dynamic-profile tools...            51,3s
Downloading android-arm-dynamic-release tools...            40,9s
Downloading android-arm64-dynamic-profile tools...          55,9s
Downloading android-arm64-dynamic-release tools...          46,2s
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, v0.5.9-pre.84, on Microsoft Windows [Version 10.0.16299.611], locale en-ZA)
[√] Android toolchain - develop for Android devices (Android SDK 28.0.0)
[√] Android Studio (version 3.1)
[√] VS Code, 64-bit edition (version 1.24.0)
[√] Connected devices (1 available)

• No issues found!
```

**Comment by zoechi** [comment] 2018-08-19 20:06
Did you install Flutter in a directory where you need to be Admin for write permissions? (like `c:\Program Files`)
That's not supported.

**Comment by rahulgul8** [comment] 2018-08-20 10:28
No, I have created a seperate folder for flutter. 

But I am able to run only the sample. But when I add the plugin as a dependency to the project, I still get a compilation error saying the following. 

import io.flutter.view.FlutterCallbackInformation; and 
import io.flutter.view.FlutterRunArguments;    not recognized as an available class.

**Comment by zoechi** [comment] 2018-08-20 12:09
Did you try `flutter clean`?

**Comment by km16** [comment] 2018-08-28 06:30
Same issue. After installing the android_alarm_manager plugin, and then running the app I get this

```
/Users/name/.pub-cache/hosted/pub.dartlang.org/android_alarm_manager-0.2.1/android/src/main/java/io/flutter/plugins/androidalarmmanager/AlarmService.java:16: error: cannot find symbol
import io.flutter.view.FlutterCallbackInformation;
                      ^
  symbol:   class FlutterCallbackInformation
  location: package io.flutter.view
/Users/name/.pub-cache/hosted/pub.dartlang.org/android_alarm_manager-0.2.1/android/src/main/java/io/flutter/plugins/androidalarmmanager/AlarmService.java:19: error: cannot find symbol
import io.flutter.view.FlutterRunArguments;
                      ^
  symbol:   class FlutterRunArguments
  location: package io.flutter.view
/Users/name/.pub-cache/hosted/pub.dartlang.org/android_alarm_manager-0.2.1/android/src/main/java/io/flutter/plugins/androidalarmmanager/AlarmService.java:47: error: cannot find symbol
    FlutterCallbackInformation cb =
    ^
  symbol:   class FlutterCallbackInformation
  location: class AlarmService
/Users/name/.pub-cache/hosted/pub.dartlang.org/android_alarm_manager-0.2.1/android/src/main/java/io/flutter/plugins/androidalarmmanager/AlarmService.java:48: error: cannot find symbol
        FlutterCallbackInformation.lookupCallbackInformation(callbackHandle);
        ^
  symbol:   variable FlutterCallbackInformation
  location: class AlarmService
/Users/name/.pub-cache/hosted/pub.dartlang.org/android_alarm_manager-0.2.1/android/src/main/java/io/flutter/plugins/androidalarmmanager/AlarmService.java:57: error: constructor FlutterNativeView in class FlutterNativeView cannot be applied to given types;
    sBackgroundFlutterView = new FlutterNativeView(context, true);
                             ^
  required: Context
  found: Context,boolean
  reason: actual and formal argument lists differ in length
/Users/name/.pub-cache/hosted/pub.dartlang.org/android_alarm_manager-0.2.1/android/src/main/java/io/flutter/plugins/androidalarmmanager/AlarmService.java:60: error: cannot find symbol
      FlutterRunArguments args = new FlutterRunArguments();
      ^
  symbol:   class FlutterRunArguments
  location: class AlarmService
/Users/name/.pub-cache/hosted/pub.dartlang.org/android_alarm_manager-0.2.1/android/src/main/java/io/flutter/plugins/androidalarmmanager/AlarmService.java:60: error: cannot find symbol
      FlutterRunArguments args = new FlutterRunArguments();
                                     ^
  symbol:   class FlutterRunArguments
  location: class AlarmService
7 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':android_alarm_manager:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
```

**Comment by zoechi** [comment] 2018-08-28 06:44
@km16 Could you please try with a newer Flutter version as well?

**Comment by km16** [comment] 2018-08-28 07:16
Tried with the new version. This time I didn't see any errors, but the application crashes every time I run it. This does not happen without the `android_alarm_manager` package.

Not sure if it is related, here is a small section of the `adb logcat`:

```
I/MiniDeviceController: [MiniDeviceController-1] ACTIVATE (MountBlue Python) null
    [MiniDeviceController-1] connecting to /10.1.2.61
08-28 12:40:31.507 1757-16880/? E/CastSocket: [MiniDeviceController-1] IOException encountered. Tearing down the socket.
    java.net.SocketException: recvfrom failed: ECONNRESET (Connection reset by peer)
        at libcore.io.IoBridge.maybeThrowAfterRecvfrom(IoBridge.java:592)
        at libcore.io.IoBridge.recvfrom(IoBridge.java:568)
        at java.nio.SocketChannelImpl.readImpl(SocketChannelImpl.java:342)
        at java.nio.SocketChannelImpl.read(SocketChannelImpl.java:304)
        at mtx.read(:com.google.android.gms@12874008@12.8.74 (020306-204998136))
        at msw.j(:com.google.android.gms@12874008@12.8.74 (020306-204998136):5)
        at mtf.run(:com.google.android.gms@12874008@12.8.74 (020306-204998136):50)
        at java.lang.Thread.run(Thread.java:818)
     Caused by: android.system.ErrnoException: recvfrom failed: ECONNRESET (Connection reset by peer)
        at libcore.io.Posix.recvfromBytes(Native Method)
        at libcore.io.Posix.recvfrom(Posix.java:177)
        at libcore.io.BlockGuardOs.recvfrom(BlockGuardOs.java:245)
        at libcore.io.IoBridge.recvfrom(IoBridge.java:565)
        at java.nio.SocketChannelImpl.readImpl(SocketChannelImpl.java:342) 
        at java.nio.SocketChannelImpl.read(SocketChannelImpl.java:304) 
        at mtx.read(:com.google.android.gms@12874008@12.8.74 (020306-204998136)) 
        at msw.j(:com.google.android.gms@12874008@12.8.74 (020306-204998136):5) 
        at mtf.run(:com.google.android.gms@12874008@12.8.74 (020306-204998136):50) 
        at java.lang.Thread.run(Thread.java:818) 
08-28 12:40:31.508 1757-16880/? E/CastSocket: [MiniDeviceController-1] Failed to shutdown the output stream socket: mtx@2ee4df6e.
    java.net.SocketException: shutdown failed: ENOTCONN (Transport endpoint is not connected)
        at java.net.PlainSocketImpl.shutdownOutput(PlainSocketImpl.java:377)
        at java.net.Socket.shutdownOutput(Socket.java:652)
        at msw.b(:com.google.android.gms@12874008@12.8.74 (020306-204998136):21)
        at mtf.run(:com.google.android.gms@12874008@12.8.74 (020306-204998136):50)
        at java.lang.Thread.run(Thread.java:818)
     Caused by: android.system.ErrnoException: shutdown failed: ENOTCONN (Transport endpoint is not connected)
        at libcore.io.Posix.shutdown(Native Method)
        at libcore.io.ForwardingOs.shutdown(ForwardingOs.java:149)
        at java.net.PlainSocketImpl.shutdownOutput(PlainSocketImpl.java:375)
        at java.net.Socket.shutdownOutput(Socket.java:652) 
        at msw.b(:com.google.android.gms@12874008@12.8.74 (020306-204998136):21) 
        at mtf.run(:com.google.android.gms@12874008@12.8.74 (020306-204998136):50) 
        at java.lang.Thread.run(Thread.java:818) 
```

```
flutter doctor

[✓] Flutter (Channel master, v0.7.2-pre.18, on Mac OS X 10.13.6 17G65)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[!] iOS toolchain - develop for iOS devices (Xcode 9.3.1)
    ! CocoaPods out of date (1.5.0 is recommended).
        CocoaPods is used to retrieve the iOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work on iOS.
        For more info, see https://flutter.io/platform-plugins
      To upgrade:
        brew upgrade cocoapods
        pod setup
[✓] Android Studio (version 3.1)
[✓] Connected devices (1 available)

! Doctor found issues in 1 category.
```

**Comment by zoechi** [comment] 2018-08-28 07:28
Executing `pod install` in `ios/` might be worth a try.

**Comment by km16** [comment] 2018-08-28 07:59
This is just on the device. I am currently interested to implement it in an android app only.

**Comment by zoechi** [comment] 2018-08-28 08:41
Does that mean it works on the emulator or that you did not try with the emulator?

**Comment by ElMohMoh** [comment] 2018-08-28 18:10
@zoechi I have the same issue on beta. When switch to master I don't log issue but the app start and crash.
I am also in windows, my version of android_alarm manager is: 0.2.1 and I test on emulator and device and I have the error on both:

`D:\Documents\dev\projets\vsCodeWorkspace\relax-mobile-app\relax (feature/parametrage)
λ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, v0.7.2-pre.23, on Microsoft Windows [version 10.0.17134.228], locale fr-FR)
[!] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    X Android license status unknown.
[√] Android Studio (version 2.3)
    X Flutter plugin version 12.1 - the recommended minimum version is 16.0.0
[√] VS Code, 64-bit edition (version 1.24.1)
[√] Connected devices (1 available)

! Doctor found issues in 1 category.

D:\Documents\dev\projets\vsCodeWorkspace\relax-mobile-app\relax (feature/parametrage)
λ flutter run
Launching lib/main.dart on D6603 in debug mode...
Initializing gradle...                                       7,2s
Resolving dependencies...                                    9,0s
Running 'gradlew assembleDebug'...                          92,6s
Built build\app\outputs\apk\debug\app-debug.apk.
Installing build\app\outputs\apk\app.apk...                 29,2s
Syncing files to device D6603...
Lost connection to device.`

**Comment by km16** [comment] 2018-09-04 10:36
I did not try with the emulator.

**Comment by preachr** [comment] 2018-11-17 03:15
Hello, is a workaround now available for this ?

**Comment by zoechi** [comment] 2018-12-04 19:16
https://github.com/flutter/flutter/issues/24201#issuecomment-441182993 might help

**Comment by siepi** [comment] 2019-01-11 18:49
I install the plugin and run in emulator and real device. 

Ricardo Luiz Pinto:
I/AlarmService(13919): Starting AlarmService...
E/MethodChannel#plugins.flutter.io/android_alarm_manager(13919): Failed to handle method call
E/MethodChannel#plugins.flutter.io/android_alarm_manager(13919): java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.PluginRegistry$PluginRegistrantCallback.registerWith(io.flutter.plugin.common.PluginRegistry)' on a null object reference
E/MethodChannel#plugins.flutter.io/android_alarm_manager(13919):  at io.flutter.plugins.androidalarmmanager.AlarmService.startAlarmService(AlarmService.java:65)
E/MethodChannel#plugins.flutter.io/android_alarm_manager(13919):  at io.flutter.plugins.androidalarmmanager.AndroidAlarmManagerPlugin.startService(AndroidAlarmManagerPlugin.java:75)
E/MethodChannel#plugins.flutter.io/android_alarm_manager(13919):  at io.flutter.plugins.androidalarmmanager.AndroidAlarmManagerPlugin.onMethodCall(AndroidAlarmManagerPlugin.java:52)
E/MethodChannel#plugins.flutter.io/android_alarm_manager(13919):  at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:200)
E/MethodChannel#plugins.flutter.io/android_alarm_manager(13919):  at io.flutter.view.FlutterNativeView.handlePlatformMessage(FlutterNativeView.java:163)
E/MethodChannel#plugins.flutter.io/android_alarm_manager(13919):  at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#plugins.flutter.io/android_alarm_manager(13919):  at android.os.MessageQueue.next(MessageQueue.java:325)

**Comment by bparrishMines** [comment] 2019-04-25 18:27
> I install the plugin and run in emulator and real device.
> 
> ```
> Ricardo Luiz Pinto:
> I/AlarmService(13919): Starting AlarmService...
> E/MethodChannel#plugins.flutter.io/android_alarm_manager(13919): Failed to handle method call
> E/MethodChannel#plugins.flutter.io/android_alarm_manager(13919): java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.PluginRegistry$PluginRegistrantCallback.registerWith(io.flutter.plugin.common.PluginRegistry)' on a null object reference
> E/MethodChannel#plugins.flutter.io/android_alarm_manager(13919):  at io.flutter.plugins.androidalarmmanager.AlarmService.startAlarmService(AlarmService.java:65)
> E/MethodChannel#plugins.flutter.io/android_alarm_manager(13919):  at io.flutter.plugins.androidalarmmanager.AndroidAlarmManagerPlugin.startService(AndroidAlarmManagerPlugin.java:75)
> E/MethodChannel#plugins.flutter.io/android_alarm_manager(13919):  at io.flutter.plugins.androidalarmmanager.AndroidAlarmManagerPlugin.onMethodCall(AndroidAlarmManagerPlugin.java:52)
> E/MethodChannel#plugins.flutter.io/android_alarm_manager(13919):  at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:200)
> E/MethodChannel#plugins.flutter.io/android_alarm_manager(13919):  at io.flutter.view.FlutterNativeView.handlePlatformMessage(FlutterNativeView.java:163)
> E/MethodChannel#plugins.flutter.io/android_alarm_manager(13919):  at android.os.MessageQueue.nativePollOnce(Native Method)
> E/MethodChannel#plugins.flutter.io/android_alarm_manager(13919):  at android.os.MessageQueue.next(MessageQueue.java:325)
> ```

@siepi do you mind creating a separate issue for this?

**Comment by bparrishMines** [comment] 2019-04-25 18:30
@rahulgul8 @ghost

Are you still having this issue on the latest version 0.4.1+6?

**Comment by babulpatel1309** [comment] 2019-06-25 18:39
Yes, @bparrishMines  I am suffering from the same issue. Currently I'm trying with the above solution by switching between channels. Switched from stable to master. Is there any solution for that?

**Comment by abdullayev007** [comment] 2019-06-27 05:52
I am facing this issue too (0.4.1+6)

**Comment by bparrishMines** [comment] 2019-07-05 22:44
@bkonyi

**Comment by bkonyi** [comment] 2019-07-08 17:06
I'm unable to reproduce this failure myself on Linux with the latest Flutter build. If I had to guess, the failures above are due to an incorrect environment setup and the Flutter engine library artifacts not being found.

**Comment by cbracken** [comment] 2020-01-10 01:59
@rahulgul8 @ghost are you still encountering this issue with the latest release?

**Comment by rahulgul8** [comment] 2020-01-10 04:47
@cbracken I am currently not using it and don't have the setup to test it either. So I am unable to confirm.

**Comment by TahaTesser** [comment] 2020-03-16 15:43
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

**Closed by TahaTesser** 2020-03-16 15:43 UTC
Labels: p: android_alarm_manager, p: first party, plugin, severe: crash
