### ISSUE TITLE
[DevTool]Unable to connect to VM service

### ISSUE THREAD

**Issue by aboutlan** [flutter/flutter#75055] opened 2021-01-30 08:09 UTC
I ran into a problem when i opened DevTools ? And now I can't debug widget. How can i solve it. Thanks a lot !

<img width="605" alt="Snipaste_2021-01-30_16-00-59" src="https://user-images.githubusercontent.com/11730674/106351200-cd043480-6315-11eb-99c4-aefda195b2c3.png">

$ flutter doctor -v
[✓] Flutter (Channel unknown, 1.22.4, on macOS 11.0.1 20B29 darwin-x64, locale
    zh-Hans-CN)
    • Flutter version 1.22.4 at /Users/xangam/Documents/Develop/flutter
    • Framework revision 1aafb3a8b9 (3 months ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/xangam/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.0

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0

[✓] Connected device (2 available)
    • iPhone 12 Pro Max (mobile) • 91C9D3D1-D807-4858-9464-03BA4F2A7396 • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-14-2 (simulator)
    • iPhone8_13 (mobile)        • AA2359D5-F041-4CE5-87D1-C0C7AD105A85 • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-13-0 (simulator)

! Doctor found issues in 1 category.

$flutter pub global activate devtools
Package devtools is currently active at version 0.9.7.
Resolving dependencies...
+ args 1.6.0
+ async 2.4.2
+ browser_launcher 0.1.8
+ charcode 1.1.3
+ collection 1.14.13
+ convert 2.1.1
+ devtools 0.9.7
+ devtools_server 0.9.7
+ devtools_shared 0.9.7
+ http 0.12.2
+ http_multi_server 2.2.0
+ http_parser 3.1.4
+ intl 0.16.1
+ logging 0.11.4
+ meta 1.2.4
+ mime 0.9.7
+ path 1.7.0
+ pedantic 1.9.2
+ shelf 0.7.9
+ shelf_proxy 0.1.0+7
+ shelf_static 0.2.9+2
+ source_span 1.7.0
+ sse 3.6.1
+ stack_trace 1.9.6
+ stream_channel 2.0.0
+ string_scanner 1.0.5
+ term_glyph 1.1.0
+ typed_data 1.2.0
+ usage 3.4.2
+ vm_service 5.5.0
+ webkit_inspection_protocol 0.7.4
Precompiling executables...
Precompiled devtools:devtools.
Installed executable devtools.
Activated devtools 0.9.7.

**Comment by eli1stark** [comment] 2021-01-30 10:42
I have exactly the same issue at 1.22.5 and 1.22.6

**Comment by yuke27** [comment] 2021-01-30 11:46
me too

**Comment by eli1stark** [comment] 2021-01-30 12:07
I also noticed that my automatic Hot Reload in VSCode suddenly stopped working. I don't know if this somehow relates to this but it was working several days ago

**Comment by marvinpowell** [comment] 2021-01-30 13:35
I have the same issue with 1.22.6

**Comment by tengwm95** [comment] 2021-01-30 13:36
I have the same exact issue

**Comment by nelcab** [comment] 2021-01-30 14:57
I have the same issue with 1.22.6, 1.22.5 and 1.22.4.  I even uninstall the Flutter SDK and installed again and the problems persist.
Using IntelliJ and VSCode and on both got the same problem.  Using latest plugins and also rolling back to one before.

**Comment by FireFoxG** [comment] 2021-01-30 19:49
Got the same issue today. After digging a for some time I found that it's most likely related to newest Devtools that were released (0.9.7). Since we get latest Devtools installed automatically for some reason...

I'm running Windows 10, and after checking where Dart stores its dependencies and cache I found that
`%LOCALAPPDATA%\Pub\Cache\global_packages\devtools\bin`
contains two versions of devtools for me
devtools.dart-2.10.5.snapshot - obviously for freshly released Dart 2.10.5
devtools.dart-2.10.4.snapshot

Even though my Dart version got finally updated to 2.10.5, I still have the same issue, so I temporary solved it by downgrading the Devtools that are being used:

1) `%LOCALAPPDATA%\Pub\Cache\global_packages\devtools\bin\.packages`
Changed all 3 devtools related dependecies to lower version (in my case 0.9.3+4, but can be other version in 
your case, check which one you have cached in `%LOCALAPPDATA%\Pub\Cache\hosted\pub.dartlang.org`)

devtools-0.9.7 -> devtools-0.9.3+4 
devtools_server-0.9.7 -> devtools_server-0.9.3+4
devtools_shared-0.9.7 -> devtools_shared-0.9.3+4


2) **Set .packages file to read-only**
3) Restart your IDE

**Comment by tgoyal63** [comment] 2021-01-30 22:28
I am also getting the same error from past 10 hours. I tried updating the dev tolls and restarted the server also. Nothing worked!

**Comment by joaomrsouza** [comment] 2021-01-31 00:03
Same issue here!

**Comment by grandslammer** [comment] 2021-01-31 00:06
+1

**Comment by stkuwanda** [comment] 2021-01-31 02:46
> I have exactly the same issue at 1.22.5 and 1.22.6

having the exact same issues with both these versions with both vscode and android studio

**Comment by aboutlan** [comment] 2021-01-31 02:59
@FireFoxG Downgrading version may be a good idea. Because I found that error message is **xxx method not found**，I guess this error may be about DevTools’s version.

**Comment by erikd234** [comment] 2021-01-31 03:02
Just updated today and my dev tools stopped working exactly like they did for the OP.

**Comment by Qubits-Official** [comment] 2021-01-31 03:06
I have the same issue as well after I updated to 1.22.6.

**Comment by airingursb** [comment] 2021-01-31 06:13
You can see the same issue here: [evtools/issues/2648](https://github.com/flutter/devtools/issues/2648#issuecomment-770287743)

**Comment by oscar1234456** [comment] 2021-01-31 07:06
+1
I have the same issue.
1.22.6

**Comment by FireFoxG** [comment] 2021-01-31 08:31
> 
> 
> You can see the same issue here: [devtools/issues/2648](https://github.com/flutter/devtools/issues/2648#issuecomment-770287743)

The solution mentioned by developer there didn't work for me.

Fix was already merged in devtools master branch - https://github.com/flutter/devtools/pull/2650
So for now just downgrade, and keep an eye on a new version.

### Solution
Since VS Code is using pub directly, we need to be able to use it directly as well, so let's add it to PATH
`%your_flutter_folder%\.pub-cache\bin`
For downgrading run `pub global activate devtools 0.9.6+3`
Restart your VS Code

**Comment by MicahBCode** [comment] 2021-01-31 10:24
@FireFoxG mentioned solution did not work for me.
Still having the same issue since updating to version 1.22.6

**Comment by ofury** [comment] 2021-01-31 12:24
**Updated Solution**

1. Fall back to an older version of DevTools: 
`flutter pub global activate devtools 0.9.6+3`
2. restart IDE
3. Check devtools  version: 
`flutter pub global list`
4. Launch the DevTools:
`flutter pub global run devtools`
5. start an application:
`flutter run`
6. from your terminal copy the url that looks like:
> http://127.0.0.1:50976/Swm0bjIe0ks=/
7. open DevTools:
`http://localhost:9100`
8. use url from copied earlier to connect.

If everything works using steps above and doesn`t work that you open devtools from IDE, then devtools is updated by the IDE at launch to a last version. You can check the version by running:

`flutter pub global list`

**Comment by awnigharbia** [comment] 2021-01-31 12:35
@ofury I did every step and it wasn't working for me when I launched it from the IDE (VScode for me), but when I opened an external terminal (CMD in my case) it works with the HTTPS link too.

**Comment by ofury** [comment] 2021-01-31 12:51
@awnigharbia I haven`t check with VScode but IntelliJ IDEA launches devtools 0.9.7 even though 0.9.6+3 was activated.
So I suppose the only option for now is  to run devtools from the command line.

**Comment by FireFoxG** [comment] 2021-01-31 13:06
> 
> 
> @awnigharbia I haven`t check with VScode but IntelliJ IDEA launches devtools 0.9.7 even though 0.9.6+3 was activated.
> So I suppose the only option for now is to run devtools from the command line.

VScode was doing the same for me, because it is using `pub` directly, not via `flutter pub`.
That's why I suggested downgrading devtools via pub directly:
`pub global activate devtools 0.9.6+3`

not
`flutter pub global activate devtools 0.9.6+3`

This way it will work in IDE as well, not only via command line.

**Comment by awnigharbia** [comment] 2021-01-31 13:08
@FireFoxG  the `flutter pub global activate devtools 0.9.6+3` command works in IDE, But when you launch the `dev tools` from the IDE it'll use the latest version of `dev tools`, not the downgraded version. So when I opened an external `CMD` is launched with the downgraded version.

**Comment by GilesLeRockeur** [comment] 2021-01-31 13:49
@ofury thanks, I've started following your path and it indeed works on Chrome DevTool (http://localhost:9100) but not on my Android Studio.
But I'm sorry I just can't find the version of DevTools launched by my Android Studio. Where do I find that?
And how do I downgrade it afterwards ?
Thanks in advance !

**Comment by joaomrsouza** [comment] 2021-01-31 14:27
I tried to run `pub global activate devtools 0.9.6+3` but I can't find where is this pub command to run, so I just tried to downgrade devtools using pub with flutter and dart, because maybe devtools in the IDEs don't work because they use devtools from a different directory, that `flutter pub` doesn't downgrade. **This is just a blind shot, but it works for me.**

So if you want to use devtools through an IDE try to run:

`flutter pub global activate devtools 0.9.6+3`
and
`dart pub global activate devtools 0.9.6+3`

and launch devtools via IDE, it worked (for me) in VSCode at least.

**Comment by FireFoxG** [comment] 2021-01-31 14:48
> 
> 
> I tried to run `pub global activate devtools 0.9.6+3` but I can't find where is this pub command to run, so I just tried to downgrade devtools using pub with flutter and dart, because maybe devtools in the IDEs don't work because they use devtools from a different directory, that `flutter pub` doesn't downgrade. **This is just a blind shot, but it works for me.**
> 
> So if you want to use devtools through an IDE try to run:
> 
> `flutter pub global activate devtools 0.9.6+3`
> and
> `dart pub global activate devtools 0.9.6+3`
> 
> and launch devtools via IDE, it worked (for me) in VSCode at least.

To be able to run it directly on Windows you need to add it to `PATH`
`%your_flutter_folder%\.pub-cache\bin`

**Comment by GilesLeRockeur** [comment] 2021-01-31 15:07
@joaomrsouza thanks for sharing that blind shot :) I followed your advice and ended with a mysterious warning line that echoes with the Windows manipulation suggested by @FireFoxG. 
I'm willing to solve this but : 
- What does "_[...] which is not on your path_" mean?
- What are `.bashrc` or `.bash_profile`? Why would it solve the issue?
- What does this line do  `export PATH="$PATH":"$HOME/Developer/flutter/.pub-cache/bin"`? And from where should I execute it?
<img width="1182" alt="Screenshot 2021-01-31 at 16 01 51" src="https://user-images.githubusercontent.com/66418609/106388180-a4477200-63dd-11eb-97bc-626e33fefc02.png">
Thanks in advance friends,

**Comment by joaomrsouza** [comment] 2021-01-31 15:17
> > 
> > 
> > I tried to run `pub global activate devtools 0.9.6+3` but I can't find where is this pub command to run, so I just tried to downgrade devtools using pub with flutter and dart, because maybe devtools in the IDEs don't work because they use devtools from a different directory, that `flutter pub` doesn't downgrade. **This is just a blind shot, but it works for me.**
> > 
> > So if you want to use devtools through an IDE try to run:
> > 
> > `flutter pub global activate devtools 0.9.6+3`
> > and
> > `dart pub global activate devtools 0.9.6+3`
> > 
> > and launch devtools via IDE, it worked (for me) in VSCode at least.
> 
> To be able to run it directly on Windows you need to add it to `PATH`
> `%your_flutter_folder%\.pub-cache\bin`

O tried to add this location on path but didn't work 🤔🤔

**Comment by aboutlan** [comment] 2021-01-31 15:29
@GilesLeRockeur  In my case, I added **export PATH="$PATH":"$HOME/.pub-cache/bin"** in my ~/.zshrc on mac. It depends on the shell you are using.  I'm using zsh. so I added it in ~/.zshrc. just like this:
![image](https://user-images.githubusercontent.com/11730674/106389034-2a82a900-641c-11eb-89b5-f34b7529de05.png)

**Comment by aboutlan** [comment] 2021-01-31 15:43
@FireFoxG 

> > @awnigharbia I haven`t check with VScode but IntelliJ IDEA launches devtools 0.9.7 even though 0.9.6+3 was activated.
> > So I suppose the only option for now is to run devtools from the command line.
> 
> VScode was doing the same for me, because it is using `pub` directly, not via `flutter pub`.
> That's why I suggested downgrading devtools via pub directly:
> `pub global activate devtools 0.9.6+3`
> 
> not
> `flutter pub global activate devtools 0.9.6+3`
> 
> This way it will work in IDE as well, not only via command line.

It worked for me.  Even though launch devtools via VSCode. Thank you for your help!

![image](https://user-images.githubusercontent.com/11730674/106389396-0a53e980-641e-11eb-84e4-0fe7bf5ff44e.png)

![image](https://user-images.githubusercontent.com/11730674/106389403-1344bb00-641e-11eb-8699-8daa23417feb.png)

**Comment by eli1stark** [comment] 2021-01-31 16:53
DevTools are working now! I didn't do anything

**Comment by grandslammer** [comment] 2021-01-31 17:27
> DevTools are working now! I didn't do anything. If everyone can confirm then we can close the issue

Not working for me.

**Comment by stkuwanda** [comment] 2021-01-31 18:09
Not working

> DevTools are working now! I didn't do anything. If everyone can confirm then we can close the issue

**Comment by AhmedAbouelkher** [comment] 2021-01-31 19:04
> I tried to run `pub global activate devtools 0.9.6+3` but I can't find where is this pub command to run, so I just tried to downgrade devtools using pub with flutter and dart, because maybe devtools in the IDEs don't work because they use devtools from a different directory, that `flutter pub` doesn't downgrade. **This is just a blind shot, but it works for me.**
> 
> So if you want to use devtools through an IDE try to run:
> 
> `flutter pub global activate devtools 0.9.6+3`
> and
> `dart pub global activate devtools 0.9.6+3`
> 
> and launch devtools via IDE, it worked (for me) in VSCode at least.

It worked  🎉🎉🎉
I'm using VS Code, and when using `flutter pub global activate devtools 0.9.6+3` it didn't work, though when using `dart pub global activate devtools 0.9.6+3` and restarting my IDE the problem was solved.

I think it is a bug with the latest DevTools version.

![Screen Shot 2021-01-31 at 8 57 41 PM](https://user-images.githubusercontent.com/56558577/106394895-dc63aa80-6407-11eb-9fd7-4c326d0eff8a.png)

**Comment by vid-vidal** [comment] 2021-01-31 19:17
`flutter channel` --->get list of flutter channels
`flutter channel [channel name]`
`flutter upgrade`

At least that worked for me!

**Comment by bkonyi** [comment] 2021-01-31 21:52
Duplicate of https://github.com/flutter/devtools/issues/2648. This should be resolved in the latest version (`0.9.7+1`). Thanks for being patient while we tried to get this resolved!

**Closed by bkonyi** 2021-01-31 21:52 UTC
