### ISSUE TITLE
[iOS] autofill not working properly using password text field first

### ISSUE THREAD

**Issue by Jonathanmalique** [flutter/flutter#86010] opened 2021-07-07 08:45 UTC
## Steps to Reproduce

1. Run on iOS device.
2. First time, register your username and password
3. Focus on password text field, select your saved password => the password field remains empty but the focus goes to the username field which is filled with the right username
4. Beginning by focusing on username text field is working properly

I have attached a video to show the wrong behaviour.

**Expected results:**  Should fill both username and password, without regarding where is the focus.

**Actual results:**  The two fields are filled with autofill only if beginning by username text field. Everything is working properly when using an **Android device** !

No error logs

## Minimal Code Sample|

<details> 
<summary>minimal code sample</summary> 

```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  final _formKey = GlobalKey();
  bool _loggedIn = false;

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(),
        body: _loggedIn
            ? Center(
                child: ElevatedButton(
                child: Text('logout'),
                onPressed: _logMeOut,
              ))
            : AutofillGroup(
                child: Form(
                  key: _formKey,
                  child: Padding(
                    padding: const EdgeInsets.all(8.0),
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.stretch,
                      children: <Widget>[
                        TextFormField(
                          decoration: InputDecoration(labelText: "Username"),
                          textInputAction: TextInputAction.next,
                          autofillHints: [AutofillHints.username],
                        ),
                        SizedBox(height: 8),
                        TextFormField(
                          decoration: InputDecoration(labelText: "Password"),
                          obscureText: true,
                          textInputAction: TextInputAction.done,
                          autofillHints: [AutofillHints.password],
                          onEditingComplete: _logMeIn,
                        ),
                        SizedBox(height: 8),
                        ElevatedButton(
                          child: Text("login"),
                          onPressed: () {
                            TextInput.finishAutofillContext(shouldSave: true);
                            _logMeIn();
                          },
                        ),
                      ],
                    ),
                  ),
                ),
              ),
      ),
    );
  }

  _logMeIn() {
    setState(() {
      _loggedIn = true;
    });
  }

  _logMeOut() {
    setState(() {
      _loggedIn = false;
    });
  }
}
``` 

</details>

![myVideo](https://user-images.githubusercontent.com/36881624/124729723-fbafb800-df10-11eb-8adc-35b75eae55f6.gif)

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-x64, locale en-FR)
    • Flutter version 2.2.3 at /Users/az02682/Renault/Flutter/flutter
    • Framework revision f4abaa0735 (6 days ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/az02682/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/az02682/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.24.0

[✓] Connected device (2 available)
    • iPhone 12 Pro Max (mobile) • C6FC98F3-DE6A-4B19-A109-E07C56EF423F • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 91.0.4472.114

• No issues found!
```

</details>

**Comment by TahaTesser** [comment] 2021-07-07 14:23
Hi @Jonathanmalique 
Thanks for filing the issue, I can reproduce it on `iOS 14.6`

|  `stable`  | `master` |
| :---: |:---: |
|  ❌  |   ❌  | 

Check `flutter doctor -v` outputs for each channel below

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.2.3, on macOS 12.0 21A5268h darwin-x64, locale
    en-GB)
    • Flutter version 2.2.3 at /Users/tahatesser/Code/flutter_stable
    • Framework revision f4abaa0735 (6 days ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/tahatesser/Code/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.24.0

[✓] Connected device (3 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios            • iOS
      14.6
    • macOS (desktop)        • macos                     • darwin-x64     •
      macOS 12.0 21A5268h darwin-x64
    • Chrome (web)           • chrome                    • web-javascript •
      Google Chrome 91.0.4472.114

• No issues found!
```

```console
[✓] Flutter (Channel master, 2.4.0-1.0.pre.94, on macOS 12.0 21A5268h
    darwin-x64, locale en-GB)
    • Flutter version 2.4.0-1.0.pre.94 at /Users/tahatesser/Code/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ba143ae21e (9 hours ago), 2021-07-06 22:01:02 -0700
    • Engine revision 60eea42346
    • Dart version 2.14.0 (build 2.14.0-284.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/tahatesser/Code/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.24.0

[✓] Connected device (3 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios            • iOS 14.6 18F72
    • macOS (desktop)        • macos                     • darwin-x64     • macOS 12.0 21A5268h darwin-x64
    • Chrome (web)           • chrome                    • web-javascript • Google Chrome 91.0.4472.114

• No issues found!

```
		
</details>

✅ : No Issue ❌: Issue reproduced

**Comment by HansMuller** [comment] 2021-07-07 16:37
CC @LongCatIsLooong

**Comment by LongCatIsLooong** [comment] 2022-01-20 23:05
tentatively closing as a duplicate of #95362. Feel free to reopen the issue if it is not.

**Closed by LongCatIsLooong** 2022-01-20 23:05 UTC
Labels: a: text input, platform-ios, framework, f: material design, has reproducible steps, found in release: 2.2, found in release: 2.4
