### ISSUE TITLE
A KeyUpEvent is dispatched, but the state shows that the physical key is not pressed.

### ISSUE THREAD

**Issue by hrongyong** [flutter/flutter#160657] opened 2024-12-20 12:32 UTC
Had a bit of a problem on this not-so-pleasant Friday:

```console
The complete exception is as follows：
======== Exception caught by services library ======================================================
The following assertion was thrown during a platform message callback:
A KeyUpEvent is dispatched, but the state shows that the physical key is not pressed. If this occurs in real application, please report this bug to Flutter. If this occurs in unit tests, please ensure that simulated events follow Flutter's event model as documented in `HardwareKeyboard`. This was the event: KeyUpEvent#548d6(physicalKey: PhysicalKeyboardKey#7b545(usbHidUsage: "0x00070004", debugName: "Key A"), logicalKey: LogicalKeyboardKey#12bb1(keyId: "0x00000061", keyLabel: "A", debugName: "Key A"), character: null, timeStamp: 0:24:57.277662)
'package:flutter/src/services/hardware_keyboard.dart':
Failed assertion: line 432 pos 16: '_pressedKeys.containsKey(event.physicalKey)'

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      HardwareKeyboard._assertEventIsRegular.<anonymous closure> (package:flutter/src/services/hardware_keyboard.dart:432:16)
#3      HardwareKeyboard._assertEventIsRegular (package:flutter/src/services/hardware_keyboard.dart:443:6)
#4      HardwareKeyboard.handleKeyEvent (package:flutter/src/services/hardware_keyboard.dart:535:5)
#5      KeyEventManager.handleRawKeyMessage (package:flutter/src/services/hardware_keyboard.dart:954:37)
#6      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:214:49)
#7      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:393:35)
#8      _invoke2 (dart:ui/hooks.dart:183:13)
#9      _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:40:5)
#10     _Channel.push (dart:ui/channel_buffers.dart:130:31)
#11     ChannelBuffers.push (dart:ui/channel_buffers.dart:326:17)
#12     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:664:22)
#13     _dispatchPlatformMessage (dart:ui/hooks.dart:86:31)
(elided 2 frames from class _AssertionError)
===============================================================================================

===============================================================================================
doctor --verbose
![WX20241220-202558](https://github.com/user-attachments/assets/57c0efe0-2b25-4448-bf38-751d5461191b)
===============================================================================================

===============================================================================================
This is the simulator I turned on
（iPhone SE (3rd generation) (mobile) • 2DA50493-F54C-4936-9138-56572C00192D • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-0 (simulator)）
![Simulator Screenshot - iPhone SE (3rd generation) - 2024-12-20 at 20 23 04](https://github.com/user-attachments/assets/ca6b1309-b821-464a-b0d0-015953def54c)
===============================================================================================

This problem occurs when I'm typing something through my computer's physical keyboard or the emulator's keyboard input box. The good thing is that it doesn't appear on the emulator on other devices.

===============================================================================================
```

This is the code I used to enter the popup👇，At least I don't see the problem.
<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:calc_craft/craft_common/craft_widgets/craft_card_container.dart';

class CraftNicknameDialog extends StatefulWidget {
  final String initialNickname;
  final Function(String) onConfirm;
  final VoidCallback onCancel;

  const CraftNicknameDialog({
    super.key,
    required this.initialNickname,
    required this.onConfirm,
    required this.onCancel,
  });

  @override
  State<CraftNicknameDialog> createState() => _CraftNicknameDialogState();
}

class _CraftNicknameDialogState extends State<CraftNicknameDialog> {
  late TextEditingController _controller;
  bool _isValid = false;

  @override
  void initState() {
    super.initState();
    _controller = TextEditingController(text: widget.initialNickname);
    _controller.addListener(_validateInput);
  }

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  void _validateInput() {
    final nickname = _controller.text.trim();
    setState(() {
      _isValid = nickname.isNotEmpty && nickname.length <= _maxLength;
    });
  }


  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: EdgeInsets.only(
        bottom: MediaQuery.of(context).viewInsets.bottom,
      ),
      child: CraftCardContainer(
        margin: const EdgeInsets.all(20),
        padding: const EdgeInsets.all(20),
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            const Text(
              'Edit Nickname',
              style: TextStyle(
                fontSize: 18,
                fontWeight: FontWeight.bold,
                color: Colors.black,
              ),
            ),
            const SizedBox(height: 20),
            TextField(
              controller: _controller,
              autofocus: true,
              decoration: InputDecoration(
                hintText: 'Enter your nickname',
                border: OutlineInputBorder(
                  borderRadius: BorderRadius.circular(8),
                ),
                contentPadding: const EdgeInsets.symmetric(
                  horizontal: 16,
                  vertical: 12,
                ),
              ),
              style: const TextStyle(
                fontSize: 16,
                color: Colors.black,
              ),
            ),
            const SizedBox(height: 20),
            Row(
              mainAxisAlignment: MainAxisAlignment.end,
              children: [
                TextButton(
                  onPressed: widget.onCancel,
                  child: const Text(
                    'Cancel',
                    style: TextStyle(
                      color: Colors.grey,
                      fontSize: 16,
                    ),
                  ),
                ),
                const SizedBox(width: 16),
                ElevatedButton(
                  onPressed: _isValid
                      ? () => widget.onConfirm(_controller.text.trim())
                      : null,
                  style: ElevatedButton.styleFrom(
                    backgroundColor: Colors.orange,
                    padding: const EdgeInsets.symmetric(
                      horizontal: 24,
                      vertical: 12,
                    ),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(8),
                    ),
                  ),
                  child: const Text(
                    'Confirm',
                    style: TextStyle(
                      fontSize: 16,
                      color: Colors.white,
                    ),
                  ),
                ),
              ],
            ),
          ],
        ),
      ),
    );
  }
}
```
</details>

**Comment by maheshj01** [comment] 2024-12-21 00:13
Hi @hrongyong, Thanks for filing the issue. There have been number of [reports for this issue](https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+A+KeyUpEvent+is+dispatched%2C+but+the+state+shows+that+the+physical+key+is+not+pressed) in the past and I believe they were fixed.  Are you using the latest release of flutter stable? 
Can you please share the output of flutter doctor -v 

Also, Please share the steps to reproduce the issue.

**Comment by hrongyong** [comment] 2024-12-23 03:15
[doctor --verbose](https://github.com/user-attachments/assets/57c0efe0-2b25-4448-bf38-751d5461191b)

**Comment by hrongyong** [comment] 2024-12-23 03:16
![Uploading doctor__verbose.png…]()

**Comment by hrongyong** [comment] 2024-12-23 03:21
> Hi @hrongyong, Thanks for filing the issue. There have been number of [reports for this issue](https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+A+KeyUpEvent+is+dispatched%2C+but+the+state+shows+that+the+physical+key+is+not+pressed) in the past and I believe they were fixed. Are you using the latest release of flutter stable? Can you please share the output of flutter doctor -v
> 
> Also, Please share the steps to reproduce the issue.


============================================================================================
Okay, this one is the result of doctor -v

/Users/xxx/Desktop/flutter/bin/flutter doctor --verbose
[✓] Flutter (Channel stable, 3.7.12, on macOS 14.1.1 23B81 darwin-arm64 (Rosetta), locale zh-Hans-CN)
    • Flutter version 3.7.12 on channel stable at /Users/xxx/Desktop/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4d9e56e694 (1 year, 8 months ago), 2023-04-17 21:47:46 -0400
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1

[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/xxx/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    ! Some Android licenses not accepted. To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] Connected device (4 available)
    iPhone SE (3rd generation) (mobile) • 2DA50493-F54C-4936-9138-56572C00192D • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-0 (simulator)）
    • iPhone 15 Pro (mobile) • 0ADDF424-0620-4D88-AD94-BCFCAAE1629F     • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-0 (simulator)
    • macOS (desktop)        • macos                                    • darwin-arm64   • macOS 14.1.1 23B81 darwin-arm64 (Rosetta)
    • Chrome (web)           • chrome                                   • web-javascript • Google Chrome 131.0.6778.205
    ! Error: iPhone is busy: Preparing iPhone. Xcode will continue when iPhone is finished. (code -10)

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

**Comment by hrongyong** [comment] 2024-12-23 03:23
Has this been handled in the latest flutter version? Unfortunately for the sake of production safety, it is currently not possible to directly use the latest version of the

**Comment by maheshj01** [comment] 2024-12-24 00:29
Thanks for the details @hrongyong, This issue is currently not fixed. Closing  as duplicate of https://github.com/flutter/flutter/issues/107972. Please follow up on that issue thread for further updates.

**Closed by maheshj01** 2024-12-24 00:29 UTC
Labels: in triage
