### ISSUE TITLE
Update your apps to use latest Firebase Crashlytics SDKs before November 15, 2020

### ISSUE THREAD

**Issue by kw2019ltd** [flutter/flutter#59172] opened 2020-06-10 17:13 UTC
hi when flutter planning on update  Firebase Crashlytics SDKs 

mail from google: 
we are writing to let you know that the Fabric Crashlytics SDK is now deprecated and will continue reporting your app's crashes until November 15, 2020. After this date, the Fabric Crashlytics SDK and beta versions of the Firebase Crashlytics SDK will stop sending crash reports for your app.
What happened?

We are replacing Fabric Crashlytics SDKs and beta versions of the Firebase Crashlytics SDKs with the generally available Firebase Crashlytics SDKs.
What’s Next?

To continue getting crash reports in the Firebase console, make sure to upgrade your apps to the Firebase Crashlytics SDK versions 17.0.0+ for Android, 4.0.0+ for iOS, and 6.15.0+ for Unity before November 15, 2020.

    Android - upgrade instructions
    iOS - upgrade instructions
    Unity - upgrade instructions

The following project(s) linked with your account include apps that have enabled Crashlytics:

**Comment by TahaTesser** [comment] 2020-06-11 10:38
Hi  @kw2019ltd
From what I can see, the issue is related to a FlutterFire plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments, possibly providing a minimal reproducible code sample that does not use flutter fire or other 3rd party plugins, and I will reopen it.
Thank you

**Closed by TahaTesser** 2020-06-11 10:38 UTC
