### ISSUE TITLE
webview_flutter stopped working

### ISSUE THREAD

**Issue by pradgc** [flutter/flutter#53679] opened 2020-03-31 19:11 UTC
Suddenly webview stopped working. It shows a blank screen in the webview widget in API-29 device and emulator, but works fine with API-28. I tried with compile SDK version=28, no luck. Please help. Below is the error log (api-29) - 

I/flutter (21310): 333333333333333333
I/flutter (21310): 99999999999999999999
I/flutter (21310): 444444444444444444444
I/WebViewFactory(21310): Loading com.google.android.webview version 82.0.4062.3 (code 406200381)
I/ple.flutter_ap(21310): The ClassLoaderContext is a special shared library.
W/Gralloc4(21310): allocator 3.x is not supported
I/ple.flutter_ap(21310): The ClassLoaderContext is a special shared library.
I/cr_LibraryLoader(21310): Loaded native library version number "82.0.4062.3"
W/ple.flutter_ap(21310): Accessing hidden method Landroid/media/AudioManager;->getOutputLatency(I)I (greylist, reflection, allowed)
D/HostConnection(21310): HostConnection::get() New Host Connection established 0xedee6a10, tid 21497
W/cr_media(21310): Requires BLUETOOTH permission
D/HostConnection(21310): HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_YUV_Cache ANDROID_EMU_async_unmap_buffer GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_gles_max_version_2 
E/chromium(21310): [ERROR:gl_surface_egl.cc(490)] eglChooseConfig failed with error EGL_SUCCESS
D/EGL_emulation(21310): eglCreateContext: 0xedf6c380: maj 2 min 0 rcv 2
D/EGL_emulation(21310): eglMakeCurrent: 0xedf6c380: ver 2 0 (tinfo 0xbc8b9490)
E/MethodChannel#flutter/platform_views(21310): Failed to handle method call
E/MethodChannel#flutter/platform_views(21310): android.view.WindowManager$InvalidDisplayException: Unable to add window android.view.ViewRootImpl$W@6a9d400 -- the specified display can not be found
E/MethodChannel#flutter/platform_views(21310): 	at android.view.ViewRootImpl.setView(ViewRootImpl.java:1065)
E/MethodChannel#flutter/platform_views(21310): 	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:397)
E/MethodChannel#flutter/platform_views(21310): 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:105)
E/MethodChannel#flutter/platform_views(21310): 	at android.app.Dialog.show(Dialog.java:340)
E/MethodChannel#flutter/platform_views(21310): 	at android.app.Presentation.show(Presentation.java:252)
E/MethodChannel#flutter/platform_views(21310): 	at io.flutter.plugin.platform.VirtualDisplayController.<init>(VirtualDisplayController.java:93)
E/MethodChannel#flutter/platform_views(21310): 	at io.flutter.plugin.platform.VirtualDisplayController.create(VirtualDisplayController.java:53)
E/MethodChannel#flutter/platform_views(21310): 	at io.flutter.plugin.platform.PlatformViewsController$1.createPlatformView(PlatformViewsController.java:105)
E/MethodChannel#flutter/platform_views(21310): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:96)
E/MethodChannel#flutter/platform_views(21310): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:60)
E/MethodChannel#flutter/platform_views(21310): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:231)
E/MethodChannel#flutter/platform_views(21310): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:93)
E/MethodChannel#flutter/platform_views(21310): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:642)
E/MethodChannel#flutter/platform_views(21310): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#flutter/platform_views(21310): 	at android.os.MessageQueue.next(MessageQueue.java:335)
E/MethodChannel#flutter/platform_views(21310): 	at android.os.Looper.loop(Looper.java:176)
E/MethodChannel#flutter/platform_views(21310): 	at android.app.ActivityThread.main(ActivityThread.java:7464)
E/MethodChannel#flutter/platform_views(21310): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter/platform_views(21310): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:549)
E/MethodChannel#flutter/platform_views(21310): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:955)
E/flutter (21310): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(error, Unable to add window android.view.ViewRootImpl$W@6a9d400 -- the specified display can not be found, null)
E/flutter (21310): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
E/flutter (21310): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:321:33)
E/flutter (21310): <asynchronous suspension>
E/flutter (21310): #2      AndroidViewController._create (package:flutter/src/services/platform_views.dart:640:54)
E/flutter (21310): #3      AndroidViewController.setSize (package:flutter/src/services/platform_views.dart:557:14)
E/flutter (21310): #4      RenderAndroidView._sizePlatformView (package:flutter/src/rendering/platform_view.dart:174:29)
E/flutter (21310): #5      RenderAndroidView.performResize (package:flutter/src/rendering/platform_view.dart:155:5)
E/flutter (21310): #6      RenderObject.layout (package:flutter/src/rendering/object.dart:1703:9)
E/flutter (21310): #7      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (21310): #8      RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (21310): #9      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (21310): #10     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (21310): #11     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (21310): #12     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (21310): #13     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (21310): #14     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (21310): #15     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:505:15)
E/flutter (21310): #16     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (21310): #17     RenderAspectRatio.performLayout (package:flutter/src/rendering/proxy_box.dart:520:13)
E/flutter (21310): #18     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (21310): #19     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:744:15)
E/flutter (21310): #20     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (21310): #21     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:163:11)
E/flutter (21310): #22     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:477:7)
E/flutter (21310): #23     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:232:7)
E/flutter (21310): #24     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:391:14)
E/flutter (21310): #25     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1584:7)
E/flutter (21310): #26     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:844:18)
E/flutter (21310): #27     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:344:19)
E/flutter (21310): #28     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:774:13)
E/flutter (21310): #29     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:283:5)
E/flutter (21310): #30     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1102:15)
E/flutter (21310): #31     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1041:9)
E/flutter (21310): #32     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:957:5)
E/flutter (21310): #33     _rootRun (dart:async/zone.dart:1126:13)
E/flutter (21310): #34     _CustomZone.run (dart:async/zone.dart:1023:19)
E/flutter (21310): #35     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
E/flutter (21310): #36     _invoke (dart:ui/hooks.dart:259:10)
E/flutter (21310): #37     _drawFrame (dart:ui/hooks.dart:217:3)
E/flutter (21310): 
E/chromium(21310): [ERROR:gl_surface_egl.cc(490)] eglChooseConfig failed with error EGL_SUCCESS
I/VideoCapabilities(21310): Unsupported profile 4 for video/mp4v-es
W/cr_MediaCodecUtil(21310): HW encoder for video/avc is not available on this device.
D/EGL_emulation(21310): eglCreateContext: 0xedf74ff0: maj 2 min 0 rcv 2
D/EGL_emulation(21310): eglMakeCurrent: 0xedf74ff0: ver 2 0 (tinfo 0xbc8b9490)
D/EGL_emulation(21310): eglCreateContext: 0xedf7a150: maj 2 min 0 rcv 2
D/EGL_emulation(21310): eglMakeCurrent: 0xedf7a150: ver 2 0 (tinfo 0xbc8b9490)
D/EGL_emulation(21310): eglMakeCurrent: 0xedf74ff0: ver 2 0 (tinfo 0xbc8b9490)
W/System  (21310): A resource failed to call release. 

Here's flutter doctor - 
/home/system/development/flutter/bin/flutter doctor --verbose
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Linux, locale en_IN)
    • Flutter version 1.12.13+hotfix.8 at /home/system/development/flutter
    • Framework revision 0b8abb4724 (7 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /home/system/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /home/system/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed instructions.

[✓] Android Studio (version 3.6)
    • Android Studio at /home/system/android-studio
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] Connected device (1 available)
    • sdk gphone x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

! Doctor found issues in 1 category.
Process finished with exit code 0

**Comment by jason-simmons** [comment] 2020-03-31 21:48
Duplicate of https://github.com/flutter/flutter/issues/53444

**Closed by jason-simmons** 2020-03-31 21:48 UTC
