### ISSUE TITLE
Android Alarm Manager is not working when kill app?

### ISSUE THREAD

**Issue by pqtrong17** [flutter/flutter#69868] opened 2020-11-05 09:57 UTC
Sorry, my english is not good!
 I use `android_alarm_manager` to sending wishs to my user. But its seem when user close app (kill app completely),alarm is not working. It just running on foreground services. 
Is there a way to fix the error?

**Comment by darshankawar** [comment] 2020-11-05 12:59
@pqtrong17 
Please provide `flutter doctor -v` and a minimal complete reproducible code sample that shows the issue along with the expected and actual behavior.
Thanks.

**Comment by pqtrong17** [comment] 2020-11-06 03:01
The result when I running `flutter doctor -v`
```
[√] Flutter (Channel stable, 1.22.3, on Microsoft Windows [Version 10.0.18363.1139], locale en-US)
    • Flutter version 1.22.3 at C:\Users\pqtrong17\AppData\Local\Android\flutter
    • Framework revision 8874f21e79 (7 days ago), 2020-10-29 14:14:35 -0700
    • Engine revision a1440ca392
    • Dart version 2.10.3


[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\pqtrong17\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (1 available)
    • Google Pixel (mobile) • 192.168.242.101:5555 • android-x86 • Android 9 (API 28)

! Doctor found issues in 1 category.
```
For code:
 I  initialization like this:
```
final ReceivePort port = ReceivePort();

  Future<void> registerAlarmManager() async {
    // Register for events from the background isolate. These messages will
    // always coincide with an alarm firing.
    IsolateNameServer.registerPortWithName(
      port.sendPort,
      'isolate',
    );
  }
```
and on initState, I called:
```
registerAlarmManager();
 AndroidAlarmManager.initialize();
port.listen((_) async => await onFireAlarm());
```
`onFireAlarm` Simply just will displaying notification for user.
My `OneShot` and `callback`:
```
Future<void> startOneShot(int days, int id) async {
    await AndroidAlarmManager.oneShot(
      Duration(days: days),
      // Ensure we have a unique alarm ID.
      id,
      callback,
      exact: true,
      wakeup: true,
    );
  }

  // The background
  static SendPort uiSendPort;

  // The callback for our alarm
  static Future<void> callback() async {
    // This will be null if we're running in the background.
    uiSendPort ??= IsolateNameServer.lookupPortByName("isolate");
    uiSendPort?.send(null);
    print('Count done! Alarm service will fire now!');
  }
```
I hope you understand. Sorry cause my english. Tks @darshankawar

**Comment by pqtrong17** [comment] 2020-11-06 03:04
`flutter doctor -v` displaying error `plugin not install` is wrong because I installed both. I don't understand why it's get an error. (I just updated flutter version and get an error for plugin)

**Comment by pqtrong17** [comment] 2020-11-06 03:07
Bonus:
On `AndroidManifes.xml`:
```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.example.my_app">
    <!-- io.flutter.app.FlutterApplication is an android.app.Application that
         calls FlutterMain.startInitialization(this); in its onCreate method.
         In most cases you can leave this as-is, but you if you want to provide
         additional functionality it is fine to subclass or reimplement
         FlutterApplication and put your custom class here. -->
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>
    <uses-permission android:name="android.permission.WAKE_LOCK"/>
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>
    <uses-permission android:name="android.permission.VIBRATE" />
    <application
        android:name="io.flutter.app.FlutterApplication"
        android:label="my_app"
        android:icon="@mipmap/ic_launcher">
        <activity
```

**Comment by darshankawar** [comment] 2020-11-06 06:37
@pqtrong17 
Will need complete minimal reproducible code sample that we can copy paste and run in IDE to see the issue you are facing.
Thanks.

**Comment by pqtrong17** [comment] 2020-11-06 06:44
> @pqtrong17
> Will need complete minimal reproducible code sample that we can copy paste and run in IDE to see the issue you are facing.
> Thanks.

Ok. 
```
import 'dart:isolate';
import 'dart:math';
import 'dart:ui';

import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:android_alarm_manager/android_alarm_manager.dart';
import 'package:take_care_customer/main.dart';
import 'package:take_care_customer/storage/localization_storage.dart';
import 'package:take_care_customer/values/colors.dart';
import 'package:take_care_customer/values/strings.dart';
import 'package:take_care_customer/widgets/initial_widget.dart';
import 'package:take_care_customer/widgets/text_customized.dart';
import 'package:flutter_local_notifications/flutter_local_notifications.dart';
import 'package:take_care_customer/widgets/text_field_customized.dart';
import 'package:flutter_datetime_picker/flutter_datetime_picker.dart';

class ReminderBirthday extends StatefulWidget {
  @override
  _ReminderBirthdayState createState() => _ReminderBirthdayState();
}

class _ReminderBirthdayState extends State<ReminderBirthday> {
  @override
  Widget build(BuildContext context) {
    return _AlarmHomePage(title: "Reminder Birthday",);
  }
}


class _AlarmHomePage extends StatefulWidget {
  _AlarmHomePage({Key key, this.title}) : super(key: key);
  final String title;

  @override
  _AlarmHomePageState createState() => _AlarmHomePageState();
}

class _AlarmHomePageState extends State<_AlarmHomePage> {

  DateTime mUserBirthday;

  FlutterLocalNotificationsPlugin flutterLocalNotificationsPlugin =
  new FlutterLocalNotificationsPlugin();
  SharedPreferences pref;
  final ReceivePort port = ReceivePort();

  Future<void> registerAlarmManager() async {
    // Register for events from the background isolate. These messages will
    // always coincide with an alarm firing.
    IsolateNameServer.registerPortWithName(
      port.sendPort,
      'isolate',
    );
  }

@override
  void dispose() {
    // TODO: implement dispose
    super.dispose();
  }
  @override
  void initState()  {
    super.initState();
    registerAlarmManager();
    AndroidAlarmManager.initialize();
    port.listen((_) async => await onFireAlarm());

    var initializationSettingsAndroid = AndroidInitializationSettings(
        '@mipmap/ic_launcher'); // <- default icon name is @mipmap/ic_launcher
    var initializationSettingsIOS = IOSInitializationSettings(
        onDidReceiveLocalNotification: onDidReceiveLocalNotification);
    var initializationSettings = InitializationSettings(android :initializationSettingsAndroid, iOS: initializationSettingsIOS);

    flutterLocalNotificationsPlugin.initialize(initializationSettings,
        onSelectNotification: selectNotification);
  }

  Future onFireAlarm() async{
    await displayNotification();
    startedCount(DateTime(DateTime.now().year + 1, mUserBirthday.month, mUserBirthday.day));
  }


  Future displayNotification() async {
    var androidPlatformChannelSpecifics = new AndroidNotificationDetails(
        'default_notification_channel_id',
        'flutterfcm',
        'your channel description',
        importance: Importance.max,
        priority: Priority.high);
    var iOSPlatformChannelSpecifics = new IOSNotificationDetails();
    var platformChannelSpecifics = new NotificationDetails(android:
        androidPlatformChannelSpecifics,iOS: iOSPlatformChannelSpecifics);
    flutterLocalNotificationsPlugin.show(
      0,
      "Happy birthday to you (${DateTime.now().day}-${DateTime.now().month} )",
      "Wish you all",
      // _contentNotification.pushNotifyContent,
      platformChannelSpecifics,
      payload: 'success',
    );
  }

  Future selectNotification(String payload) async {
    if (payload != null) {
      debugPrint('notification payload: $payload');
    }
  }

  Future onDidReceiveLocalNotification(
      int id, String title, String body, String payload) async {
    // display a dialog with the notification details, tap ok to go to another page
    showDialog(
      context: context,
      builder: (BuildContext context) => new AlertDialog(
        title: new Text(title),
        content: new Text(body),
        actions: [
          CupertinoDialogAction(
            isDefaultAction: true,
            child: new Text('Ok'),
            onPressed: () async {
              Navigator.of(context, rootNavigator: true).pop();
            },
          ),
        ],
      ),
    );
  }

  int differenceBetweenTwoDay(DateTime birthday){
    final _nowDateTime = DateTime.now();
    final _dateForThisBirthday = DateTime(birthday.year, birthday.month, birthday.day,  _nowDateTime.hour, _nowDateTime.minute, _nowDateTime.second, _nowDateTime.millisecond, _nowDateTime.microsecond);
    int _difference = _dateForThisBirthday.difference(_nowDateTime).inDays;
    return _difference;
  }

  Future<void> startOneShot(int days, int id) async {
    await AndroidAlarmManager.oneShot(
      Duration(days: days),
      // Ensure we have a unique alarm ID.
      id,
      callback,
      exact: true,
      wakeup: true,
    );
  }

  // The background
  static SendPort uiSendPort;

  // The callback for our alarm
  static Future<void> callback() async {
    // This will be null if we're running in the background.
    uiSendPort ??= IsolateNameServer.lookupPortByName("isolate");
    uiSendPort?.send(null);
    print('Count done! Alarm service will fire now!');
  }

  @override
  Widget build(BuildContext context) {
    // TODO(jackson): This has been deprecated and should be replaced
    return InitialWidget(
      titleAppBar: widget.title,
      child: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            InkWell(
              onTap: () => DatePicker.showDatePicker(context,
                  showTitleActions: true,
                  minTime: DateTime(1920, 1, 1),
                  maxTime: DateTime(2099, 6, 7), onChanged: (date) {
                    print('change $date');
                  }, onConfirm: (date) async {
                    mUserBirthday = DateTime.now();
                    setState(() {
                      mUserBirthday = date;
                    });
                    startedCount(date);
                    }, currentTime: DateTime.now(), locale: LocaleType.vi),
              child: Container(
                padding: EdgeInsets.all(16),
                margin: EdgeInsets.symmetric(horizontal: 12),
                width: double.infinity,
                decoration: BoxDecoration(
                  border: Border.all(color: blackText),
                  borderRadius: BorderRadius.circular(8)
                ),
                child: Row(
                  children: [
                    Expanded(child: TextCustomized("Birthday")),
                    Icon(Icons.arrow_drop_down_sharp)
                  ],
                ),
              ),
            ),
            SizedBox(height: 16,),
          ],
        ),
      ),
    );
  }

  void startedCount(DateTime birthday) async {
    if (pref == null) {
      pref = await SharedPreferences.getInstance();
    }
    int _oneShotIdOld = pref.getInt('oneShotId');
    if(_oneShotIdOld != null){
      await AndroidAlarmManager.cancel(_oneShotIdOld);
      pref.remove("oneShotId");
    }
    int _oneShotIdNew = Random().nextInt(pow(2, 31));
    pref.setInt("oneShotId", _oneShotIdNew);
    int _differenceBetweenTwoDay = differenceBetweenTwoDay(DateTime(birthday.year, birthday.month, birthday.day));
    startOneShot(_differenceBetweenTwoDay, _oneShotIdNew);
  }
}
```

**Comment by darshankawar** [comment] 2020-11-06 10:18
@pqtrong17 
I see lot of custom and 3rd party plugin code in the sample you shared above. We are looking for a minimal code sample that we can directly run without needing to install any plugins (if not required). See [here](https://stackoverflow.com/help/minimal-reproducible-example) on how to provide a minimal workable reproducible code sample and only provide the code related to alarm manager.
Thanks.

**Comment by pedromassangocode** [comment] 2020-11-27 12:54
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2020-11-27 12:54 UTC
Labels: in triage, waiting for customer response

**Comment by adamk22** [comment] 2020-11-29 22:08
I ran into this same issue with the example app (https://pub.dev/packages/android_alarm_manager). Once killed off, it doesn't print any statements to the console. Similarly when the app is pushed to the background, it prints 1 or 2 statements and then stops while my expectation is that it returns a print statement every minute.

**Comment by sidharathjain2** [comment] 2021-02-26 17:41
I ran into this same issue with the example app (https://pub.dev/packages/android_alarm_manager). Once killed off
It shows error in console 

I/FlutterBackgroundExecutor(24917): Starting AlarmService...
E/AndroidRuntime(24917): FATAL EXCEPTION: main
E/AndroidRuntime(24917): Process: com.dexterous.flutter_local_notifications_example, PID: 24917
E/AndroidRuntime(24917): java.lang.RuntimeException: Unable to create service io.flutter.plugins.androidalarmmanager.AlarmService: java.lang.NullPointerException: Attempt to read from field 'java.lang.String io.flutter.embedding.engine.loader.FlutterApplicationInfo.flutterAssetsDir' on a null object reference
E/AndroidRuntime(24917):        at android.app.ActivityThread.handleCreateService(ActivityThread.java:3613)
E/AndroidRuntime(24917):        at android.app.ActivityThread.-wrap4(Unknown Source:0)
E/AndroidRuntime(24917):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1873)
E/AndroidRuntime(24917):        at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(24917):        at android.os.Looper.loop(Looper.java:210)
E/AndroidRuntime(24917):        at android.app.ActivityThread.main(ActivityThread.java:7080)        
E/AndroidRuntime(24917):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(24917):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:523)
E/AndroidRuntime(24917):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:863)
E/AndroidRuntime(24917): Caused by: java.lang.NullPointerException: Attempt to read from field 'java.lang.String io.flutter.embedding.engine.loader.FlutterApplicationInfo.flutterAssetsDir' on a null object reference
E/AndroidRuntime(24917):        at io.flutter.embedding.engine.loader.FlutterLoader.findAppBundlePath(FlutterLoader.java:324)
E/AndroidRuntime(24917):        at io.flutter.view.FlutterMain.findAppBundlePath(FlutterMain.java:97)
E/AndroidRuntime(24917):        at io.flutter.plugins.androidalarmmanager.FlutterBackgroundExecutor.startBackgroundIsolate(FlutterBackgroundExecutor.java:158)
E/AndroidRuntime(24917):        at io.flutter.plugins.androidalarmmanager.FlutterBackgroundExecutor.startBackgroundIsolate(FlutterBackgroundExecutor.java:126)
E/AndroidRuntime(24917):        at io.flutter.plugins.androidalarmmanager.AlarmService.onCreate(AlarmService.java:349)
E/AndroidRuntime(24917):        at android.app.ActivityThread.handleCreateService(ActivityThread.java:3603)
E/AndroidRuntime(24917):        ... 8 more
I/FlutterBackgroundExecutor(25150): Starting AlarmService...
E/AndroidRuntime(25150): FATAL EXCEPTION: main
E/AndroidRuntime(25150): Process: com.dexterous.flutter_local_notifications_example, PID: 25150
E/AndroidRuntime(25150): java.lang.RuntimeException: Unable to create service io.flutter.plugins.androidalarmmanager.AlarmService: java.lang.NullPointerException: Attempt to read from field 'java.lang.String io.flutter.embedding.engine.loader.FlutterApplicationInfo.flutterAssetsDir' on a null object reference
E/AndroidRuntime(25150):        at android.app.ActivityThread.handleCreateService(ActivityThread.java:3613)
E/AndroidRuntime(25150):        at android.app.ActivityThread.-wrap4(Unknown Source:0)
E/AndroidRuntime(25150):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1873)
E/AndroidRuntime(25150):        at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(25150):        at android.os.Looper.loop(Looper.java:210)
E/AndroidRuntime(25150):        at android.app.ActivityThread.main(ActivityThread.java:7080)
E/AndroidRuntime(25150):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(25150):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:523)
E/AndroidRuntime(25150):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:863)     
E/AndroidRuntime(25150): Caused by: java.lang.NullPointerException: Attempt to read from field 'java.lang.String io.flutter.embedding.engine.loader.FlutterApplicationInfo.flutterAssetsDir' on a null object reference
E/AndroidRuntime(25150):        at io.flutter.embedding.engine.loader.FlutterLoader.findAppBundlePath(FlutterLoader.java:324)
E/AndroidRuntime(25150):        at io.flutter.view.FlutterMain.findAppBundlePath(FlutterMain.java:97)
E/AndroidRuntime(25150):        at io.flutter.plugins.androidalarmmanager.FlutterBackgroundExecutor.startBackgroundIsolate(FlutterBackgroundExecutor.java:158)
E/AndroidRuntime(25150):        at io.flutter.plugins.androidalarmmanager.FlutterBackgroundExecutor.startBackgroundIsolate(FlutterBackgroundExecutor.java:126)
E/AndroidRuntime(25150):        at io.flutter.plugins.androidalarmmanager.AlarmService.onCreate(AlarmService.java:349)
E/AndroidRuntime(25150):        at android.app.ActivityThread.handleCreateService(ActivityThread.java:3603)
E/AndroidRuntime(25150):        ... 8 more


Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 1.22.6, on Microsoft Windows [Version 10.0.18363.1379], locale en-IN)   

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[√] Android Studio (version 4.0)
[√] VS Code (version 1.53.2)
[√] Connected device (1 available)

• No issues found!


And after some time my android show message
![error](https://user-images.githubusercontent.com/63875151/109335287-d686ab00-7887-11eb-9092-fa241290bac1.jpeg)

**Comment by pedromassangocode** [comment] 2021-03-01 10:42
> Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
> All system setups can be slightly different, so it's always better to open new issues and reference related issues.
