### ISSUE TITLE
Feature request for audio player

### ISSUE THREAD

**Issue by hritvikpatel4** [flutter/flutter#56969] opened 2020-05-12 04:25 UTC
## Use case
I have tried to use the audio player packages on pub.dev but none of them provide true cross platform support for audio files to be played remotely from a server.
I would appreciate if the Flutter team could implement the native audio player of both iOS and Android as a package.

## Proposal
The new package which is being proposed, should be able to take in a URL and play audio on both iOS and Android devices.

**Comment by TahaTesser** [comment] 2020-05-12 12:00
There is an issue open for this audio support, just comment what features you need on that issue
Closing as duplicate of #47105](https://github.com/flutter/flutter/issues/47105)
Thank you

**Closed by TahaTesser** 2020-05-12 12:00 UTC
