### ISSUE TITLE
Flutter driver is missing --pid-file

### ISSUE THREAD

**Issue by nerder** [flutter/flutter#54004] opened 2020-04-04 17:19 UTC
As in the title, at the moment `flutter drive` is missing `--pid-file`. This option will be very useful to have especially because in this way it will be possible to programmatically make the driver test to run both `hot restart` and `hot reload`.

**Comment by jonahwilliams** [comment] 2020-04-05 04:41
This is a duplicate of https://github.com/flutter/flutter/issues/36551 . Adding the PID file alone will not enable hot reload/restart, because the resident runner that managed the reload/restart cycle is not running during `flutter drive`

**Closed by jonahwilliams** 2020-04-05 04:41 UTC
