### ISSUE TITLE
No named parameter with the name 'shadowThemeOnly' at 1.24.0-10.2 sdk beta version

### ISSUE THREAD

**Issue by tazik561** [flutter/flutter#71785] opened 2020-12-05 21:37 UTC
I have a flutter pwa project that is works fine with `1.23.0-18.1.pre` sdk version. Now i upgraded sdk to `1.24.0-10.2.pre` :
```
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 1.24.0-10.2.pre, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0-rc1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.51.1)
[✓] Connected device (2 available)
```
Now i can't run my project:

```
[+9019 ms]
../../../../../Software/Linux/Flutter/flutter/.pub-cache/git/persianDatePicker-b20d15502d6cae5c5bc9b4219789e16b15debb26/lib/widget/dialo
                    g.dart:725:45: Error: No named parameter with the name 'shadowThemeOnly'.
[        ]   final ThemeData theme = Theme.of(context, shadowThemeOnly: true);
[        ]                                             ^^^^^^^^^^^^^^^
[        ] ../../../../../Software/Linux/Flutter/flutter/packages/flutter/lib/src/material/theme.dart:119:20: Context: Found this
candidate, but
           the arguments don't match.
[        ]   static ThemeData of(BuildContext context) {
[        ]                    ^^
[+1781 ms] lib/widget/date_picker/widget/dialog.dart:725:45: Error: No named parameter with the name 'shadowThemeOnly'.
[        ]   final ThemeData theme = Theme.of(context, shadowThemeOnly: true);
[        ]                                             ^^^^^^^^^^^^^^^
[        ] ../../../../../Software/Linux/Flutter/flutter/packages/flutter/lib/src/material/theme.dart:119:20: Context: Found this
candidate, but
           the arguments don't match.
[        ]   static ThemeData of(BuildContext context) {
[        ]                    ^^
[+23071 ms] Syncing files to device Chrome... (completed in 36.4s)
[        ] Synced 0.0MB.
[        ] Failed to compile application.
[   +2 ms] "flutter run" took 43,951ms.
[   +6 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:617:7)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1080:12)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:931:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #6      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
           <asynchronous suspension>
           #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #9      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #10     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:230:5)
           <asynchronous suspension>
           #11     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:9)
           <asynchronous suspension>
           #12     run.<anonymous closure> (package:flutter_tools/runner.dart:61:12)
           <asynchronous suspension>
           #13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #14     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #15     runInContext (package:flutter_tools/src/context_runner.dart:70:10)
           <asynchronous suspension>
           #16     main (package:flutter_tools/executable.dart:90:3)
           <asynchronous suspension>
```
• No issues found!

This is my pubspec.yaml:
```
dependency_overrides:
  analyzer: 0.40.4
  build_resolvers: '1.4.1'

dependencies:
  flutter:
    sdk: flutter
  persian_datetime_picker:
    git:
      url: https://gitlab.com/mortezabagheridev/persianDatePicker.git
  after_layout: ^1.0.7+2
  barcode_scan: ^1.0.0
  carousel_slider: ^2.2.1
  ...
dev_dependencies:
  flutter_localizations:
    sdk: flutter
  flutter_test:
    sdk: flutter
  build_runner: 1.10.3
  hive_generator: ^0.8.1
  json_serializable: ^3.5.0
  retrofit_generator: ^1.4.0+1
```

**Comment by iapicca** [comment] 2020-12-06 11:14
@tazik561 

from your logs the issue seems to depend from [persian_datetime_picker](https://pub.dev/packages/persian_datetime_picker)
can you provide a **_minimal reproducible code sample_** that does not depend from 3rd party plugins or packages

**Comment by tazik561** [comment] 2020-12-06 12:18
I removed `shadowThemeOnly: true` from ThemeData theme = Theme.of(context, shadowThemeOnly: true) on pup_cache and problem is solved . But is it correct way! ?

**Comment by darshankawar** [comment] 2020-12-07 09:36
@tazik561 
Check [this](https://github.com/Realank/flutter_datetime_picker/issues/197#issuecomment-725831759) comment. Not sure what is `pup_cache` ? or you meant `pub_cache` ?
Anyways, the said property seems to be removed in latest master per above link and documentation. So it could be related to the `pub` or 3rd party plugin you may be using and need to be followed-up with them.

**Comment by pedromassangocode** [comment] 2020-12-30 10:58
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2020-12-30 10:58 UTC
Labels: in triage, waiting for customer response

**Comment by wasd845** [comment] 2021-03-20 09:10
Dude, see this [https://github.com/flutter/flutter/pull/68922](url)

**Comment by iapicca** [comment] 2021-03-20 10:47
> Dude, see this [https://github.com/flutter/flutter/pull/68922](url)

@wasd845 
not sure what your comment means, but I'd follow the indication [above](https://github.com/flutter/flutter/issues/71785#issuecomment-752416510)

> Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of flutter doctor -v.
> All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by moeiscool** [comment] 2021-06-09 15:52
seems like this isn't fixed :( I forget what I do each time to get around it.
