### ISSUE TITLE
Text redering breaks in a scrollable widget on Flutter web on iOS Safari in landscape mode

### ISSUE THREAD

**Issue by sjoenk** [flutter/flutter#94125] opened 2021-11-23 21:44 UTC
## Steps to Reproduce

1. Execute `flutter run -d chrome` on the code sample. Choosing HTML or canvas renderer doesn't matter for this issue.
2. Open the running web app in the browser on a physical device or emulator.
3. Rotate the device in landscape mode.
4. Scroll down and watch the text in the second Text widget increase in size and get painted outside the parent widget (with the blue border).

**Expected results:**
Expected to see no difference in font size or any style between the two Text widgets.

**Actual results:**
The second Text widget increases in size after scrolling down.
This only happens when the text is long enough to get wrapped, has a border, and when the device is in portrait mode.

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(primarySwatch: Colors.blue),
      home: Scaffold(
        body: ListView(
          children: [
            // First text. This gets displayed right
            const Text(
              'This long text is displayed right. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.',
            ),
            // Second text with a border. This gets displayed wrong after scrolling
            DecoratedBox(
              decoration: BoxDecoration(border: Border.all(color: Colors.blue)),
              child: const Text(
                'But this text with a border is displayed wrong after scrolling down. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
              ),
            ),
            // This is to make the Listview scrollable
            const SizedBox(height: 900),
          ],
        ),
      ),
    );
  }
}
```

</details>

<details>
  <summary>Logs</summary>

```
$ flutter run -d chrome --verbose
[ +109 ms] executing: sysctl hw.optional.arm64
[  +20 ms] Exit code 1 from: sysctl hw.optional.arm64
[        ] sysctl: unknown oid 'hw.optional.arm64'
[   +7 ms] executing: [/Users/paul/Development/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +48 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 18116933e77adc82f80866c928266a5b4f1ed645
[   +1 ms] executing: [/Users/paul/Development/flutter/] git tag --points-at 18116933e77adc82f80866c928266a5b4f1ed645
[ +111 ms] Exit code 0 from: git tag --points-at 18116933e77adc82f80866c928266a5b4f1ed645
[        ] 2.5.3
[  +11 ms] executing: [/Users/paul/Development/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +16 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/Users/paul/Development/flutter/] git ls-remote --get-url origin
[  +19 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +114 ms] executing: [/Users/paul/Development/flutter/] git rev-parse --abbrev-ref HEAD
[  +16 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[   +6 ms] executing: sw_vers -productName
[  +22 ms] Exit code 0 from: sw_vers -productName
[        ] macOS
[        ] executing: sw_vers -productVersion
[  +16 ms] Exit code 0 from: sw_vers -productVersion
[        ] 11.6
[        ] executing: sw_vers -buildVersion
[  +17 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 20G165
[  +69 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +65 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +37 ms] executing: sysctl hw.optional.arm64
[   +5 ms] Exit code 1 from: sysctl hw.optional.arm64
[        ] sysctl: unknown oid 'hw.optional.arm64'
[        ] executing: xcrun xcodebuild -version
[+1601 ms] Exit code 0 from: xcrun xcodebuild -version
[        ] Xcode 13.1
           Build version 13A1030d
[  +69 ms] Skipping pub get: version match.
[ +144 ms] Generating /Users/paul/Projects/test_app_2/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[ +313 ms] Launching lib/main.dart on Chrome in debug mode...
[ +117 ms] Updating assets
[  +98 ms] Waiting for connection from debug service on Chrome...
[  +73 ms] <- reset
[   +8 ms] /Users/paul/Development/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev /Users/paul/Development/flutter/bin/cache/artifacts/engine/darwin-x64/frontend_server.dart.snapshot --sdk-root
/Users/paul/Development/flutter/bin/cache/flutter_web_sdk/ --incremental --target=dartdevc --debugger-module-names --experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true --output-dill
/var/folders/kh/0kpk7xb93m75cdz_dxm3cnnw0000gn/T/flutter_tools.Tzk5wu/flutter_tool.aGAjNU/app.dill --libraries-spec file:///Users/paul/Development/flutter/bin/cache/flutter_web_sdk/libraries.json --packages
/Users/paul/Projects/test_app_2/.dart_tool/package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-root
/var/folders/kh/0kpk7xb93m75cdz_dxm3cnnw0000gn/T/flutter_tools.Tzk5wu/flutter_tools.fuwi6W --filesystem-scheme org-dartlang-app --initialize-from-dill
build/b1b715402d823b7fd5c2b68d2edcb2ce.cache.dill.track.dill --platform file:///Users/paul/Development/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk_sound.dill --sound-null-safety
[  +15 ms] <- compile org-dartlang-app:/web_entrypoint.dart
[+16652 ms] Waiting for connection from debug service on Chrome... (completed in 16.7s)
[        ] Synced 26.2MB.
[        ] <- accept
[        ] Caching compiled dill
[ +343 ms] Using Google Chrome 96.0.4664.55 

[ +123 ms] executing: sysctl hw.optional.arm64
[   +7 ms] Exit code 1 from: sysctl hw.optional.arm64
[        ] sysctl: unknown oid 'hw.optional.arm64'
[ +836 ms] [CHROME]:
[   +1 ms] [CHROME]:DevTools listening on ws://127.0.0.1:56907/devtools/browser/582648bb-1046-4839-80f8-89819d8f6a11
[+1524 ms] DwdsInjector: Received request for entrypoint at http://localhost:56817/main_module.bootstrap.js
[   +6 ms] MetadataProvider: Loading debug metadata...
[  +14 ms] MetadataProvider: Loaded debug metadata (sound null safety)
[  +10 ms] DwdsInjector: Injected debugging metadata for entrypoint at http://localhost:56817/main_module.bootstrap.js
[+2715 ms] ChromeProxyService: Initializing expression compiler for main_module.bootstrap.js with sound null safety: true
[ +116 ms] DevHandler: Debug service listening on ws://127.0.0.1:56957/_IKany2yKwA=/ws

[  +35 ms] This app is linked to the debug service: ws://127.0.0.1:56957/_IKany2yKwA=/ws
[  +14 ms] Debug service listening on ws://127.0.0.1:56957/_IKany2yKwA=/ws
[        ] 💪 Running with sound null safety 💪
[   +6 ms] 🔥  To hot restart changes while running, press "r" or "R".
[        ] For a more detailed help message, press "h". To quit, press "q".
[   +1 ms] An Observatory debugger and profiler on Chrome is available at: http://127.0.0.1:56957/_IKany2yKwA=
[ +405 ms] DevTools activation throttled until 2021-11-24 07:09:22.038409.
[+1538 ms] The Flutter DevTools debugger and profiler on Chrome is available at: http://127.0.0.1:9102?uri=http://127.0.0.1:56957/_IKany2yKwA=
```

</details>

<details>
  <summary>Output of `flutter doctor -v`</summary>

```
[✓] Flutter (Channel stable, 2.5.3, on macOS 11.6 20G165 darwin-x64, locale en-NL)
    • Flutter version 2.5.3 at /Users/paul/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (6 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/paul/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.1, Build version 13A1030d
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.62.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.28.0

[✓] Connected device (5 available)
    • Android SDK built for x86 (mobile) • emulator-5556                        • android-x86    • Android 10 (API 29) (emulator)
    • iPhone 12 Pro (mobile)             • 00008101-00191DEA2130001E            • ios            • iOS 15.0.2 19A404
    • iPhone 13 (mobile)                 • B8F84B1A-EA1D-4C44-9824-BAAE85BF3111 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • macOS (desktop)                    • macos                                • darwin-x64     • macOS 11.6 20G165 darwin-x64
    • Chrome (web)                       • chrome                               • web-javascript • Google Chrome 96.0.4664.55

• No issues found!
```

</details>

Screenshot of the result:

![Simulator Screen Shot - iPhone 13 - 2021-11-23 at 22 20 21](https://user-images.githubusercontent.com/11338107/143133117-98ae59da-972d-4e63-a0bf-c9be10b90399.png)

**Comment by sjoenk** [comment] 2021-11-23 21:46
Maybe related to: https://github.com/flutter/flutter/issues/81970

**Comment by mamuseferha** [comment] 2021-11-24 11:03
Hi @sjoenk, thank you for filing this issue, yes it is a duplicate of https://github.com/flutter/flutter/issues/81970.

Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by mamuseferha** 2021-11-24 11:03 UTC
Labels: in triage
