### ISSUE TITLE
[Bug, Fedora 39] Debug console returns: Unknown CMake command "_minimum_required".

### ISSUE THREAD

**Issue by HatWearingMann** [flutter/flutter#138488] opened 2023-11-15 16:11 UTC
### Steps to reproduce

1. Attempt to compile program
2. Get error

### Expected results

The program compiles succesfully.

### Actual results

Compiler returns an error.

### Code sample

**First few lines of CMakeLists.txt:**
```

# This file controls Flutter-level build steps. It should not be edited.
cmake_minimum_required(VERSION 3.10)

set(EPHEMERAL_DIR "${CMAKE_CURRENT_SOURCE_DIR}/ephemeral")

# Configuration provided via flutter tool.
include(${EPHEMERAL_DIR}/generated_config.cmake)
```

### Logs

```
Launching lib/main.dart on Linux in debug mode...
CMake Error at CMakeLists.txt:2 (_minimum_required):
  Unknown CMake command "_minimum_required".

CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 3.27)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.

Exception: Unable to generate build files


Exited (1).

```

### Flutter Doctor output

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.9, on Fedora Linux 39
    (Workstation Edition) 6.5.11-300.fc39.x86_64, locale
    en_US.UTF-8)
[✓] Android toolchain - develop for Android devices
    (Android SDK version 34.0.0)
[✗] Chrome - develop for the web (Cannot find Chrome
    executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to
      a Chrome executable.
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.84.2)
[✓] Connected device (1 available)
[✓] Network resources

! Doctor found issues in 1 category.
```

**Comment by huycozy** [comment] 2023-11-16 07:34
Hi @HatWearingMann 
What is your current installed cmake version in the system? Please share the entire output of `flutter doctor -v`. 

Also, does this issue occur on a newly created Flutter project?

**Comment by HatWearingMann** [comment] 2023-11-16 10:30
My cmake version is 3.27.7, the error doesn't occur on newly created projects, but it does on projects that I haven't touched in two weeks (they compiled just fine back then).

And here is the verbose output of flutter doctor:

`[✓] Flutter (Channel stable, 3.13.9, on Fedora Linux 39
    (Workstation Edition) 6.5.11-300.fc39.x86_64, locale
    en_US.UTF-8)
    • Flutter version 3.13.9 on channel stable at
      /home/unabomber/mycoding/flutter
    • Upstream repository
      https://github.com/flutter/flutter.git
    • Framework revision d211f42860 (3 weeks ago),
      2023-10-25 13:42:25 -0700
    • Engine revision 0545f8705d
    • Dart version 3.1.5
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices
    (Android SDK version 34.0.0)
    • Android SDK at /home/unabomber/Android/Sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /opt/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome
    executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to
      a Chrome executable.

[✓] Linux toolchain - develop for Linux desktop
    • clang version 17.0.3 (Fedora 17.0.3-1.fc39)
    • cmake version 3.27.7
    • ninja version 1.11.1
    • pkg-config version 1.9.5

[✓] Android Studio (version 2022.3)
    • Android Studio at /opt/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.84.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.76.0

[✓] Connected device (1 available)
    • Linux (desktop) • linux • linux-x64 • Fedora Linux 39
      (Workstation Edition) 6.5.11-300.fc39.x86_64

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.`

**Comment by huycozy** [comment] 2023-11-17 05:51
It could be caused by using a plugin that uses a different CMake version and the plugin may have released a new version recently. I would recommend you check around plugins you are using to see if there is one.

**Comment by HatWearingMann** [comment] 2023-11-21 13:58
If by "plugins" you mean Visual Studio Code extensions, that is sadly not the case.

**Comment by huycozy** [comment] 2023-11-22 04:10
I mean the dependency you are using (in `pubspec.yaml`). There was a case that you may take a look https://github.com/flutter/flutter/issues/131555#issuecomment-1664943376.

**Comment by HatWearingMann** [comment] 2023-11-22 14:07
Having tried to compile that newly created, unedited project again, it does not work now (the one that compiled correctly right after it being created).

And here are the contents of the main project's pubspec.yaml file:
```
name: memory_embeder
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

```

**Comment by huycozy** [comment] 2023-11-23 03:39
I'm using `Ubuntu 22.04.3 LTS` distro with `cmake version 3.22.1` and can't see the issue. Labeling the issue for other's input.

**Comment by gspencergoog** [comment] 2023-11-30 19:24
I'm not sure what we can do to help here at this point, without more specific information. We explicitly support Debian and Ubuntu, but we don't really have the resources to debug things on Fedora (and we don't have machines with that installed).

So, unfortunately, we're going to have to close this issue. If you have a specific PR or solution to contribute, we would gladly review that.
(Desktop Triage)

**Closed by gspencergoog** 2023-11-30 19:24 UTC
Labels: platform-linux, a: desktop, needs repro info, team-desktop
