### ISSUE TITLE
Type error in dart:async

### ISSUE THREAD

**Issue by ZhangQinglian** [flutter/flutter#14698] opened 2018-02-14 14:13 UTC
## Steps to Reproduce

when I just do a https get, it throw the following exception

## Logs
```
[ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter (17806): 'dart:async/stream.dart': error: line 1277: signature type '((T) => bool, {() => Object defaultValue}) => Future' of function 'firstWhere' is not a subtype of signature type '((T) => bool, {() => dynamic defaultValue, () => T orElse}) => Future<T>' of function 'firstWhere'
E/flutter (17806):
E/flutter (17806):   Future < T > firstWhere(bool test(T element),
E/flutter (17806):   ^
E/flutter (17806): 'package:async/src/typed/stream.dart': error: line 56: class 'TypeSafeStream' overrides method 'firstWhere' of super class or interface 'Stream' with incompatible parameters
E/flutter (17806):   Future firstWhere(bool test(T element), { Object defaultValue() }) =>
E/flutter (17806):   ^
E/flutter (17806):
E/flutter (17806): #0      IOClient.send (package:http/src/io_client.dart:51)
E/flutter (17806): <asynchronous suspension>
E/flutter (17806): #1      BaseClient._sendUnstreamed (package:http/src/base_client.dart:171)
E/flutter (17806): <asynchronous suspension>
E/flutter (17806): #2      BaseClient.get (package:http/src/base_client.dart:34)
E/flutter (17806): #3      get.<anonymous closure> (package:http/http.dart:47)
E/flutter (17806): #4      _withClient (package:http/http.dart:167)
E/flutter (17806): <asynchronous suspension>
E/flutter (17806): #5      get (package:http/http.dart:47)
E/flutter (17806): #6      AppServer.loadClipping (package:kindle_clippings/clippings/server/server_api.dart:78)
E/flutter (17806): <asynchronous suspension>
E/flutter (17806): #7      GlobalRepo.loadUser.<anonymous closure> (package:kindle_clippings/clippings/repo/repository.dart:65)
E/flutter (17806): <asynchronous suspension>
E/flutter (17806): #8      new Future.sync (dart:async/future.dart:222)
E/flutter (17806): #9      GlobalRepo.loadUser (package:kindle_clippings/clippings/repo/repository.dart:60)
E/flutter (17806): <asynchronous suspension>
E/flutter (17806): #10     _MyHomePageState.initState (package:kindle_clippings/clippings/page/home/home_page.dart:41)
E/flutter (17806): #11     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3729)
E/flutter (17806): #12     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3595)
E/flutter (17806): #13     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2885)
E/flutter (17806): #14     Element.updateChild (package:flutter/src/widgets/framework.dart:2688)
E/flutter (17806): #15     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3631)
E/flutter (17806): #16     Element.rebuild (package:flutter/src/widgets/framework.dart:3473)
E/flutter (17806): #17     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3600)
E/flutter (17806): #18     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3595)
E/flutter (17806): #19     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2885)
E/flutter (17806): #20     Element.updateChild (package:flutter/src/widgets/framework.dart:2688)
E/flutter (17806): #21     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3631)
E/flutter (17806): #22     Element.rebuild (package:flutter/src/widgets/framework.dart:3473)
E/flutter (17806): #23     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3600)
E/flutter (17806): #24     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3595)
E/flutter (17806): #25     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2885)
E/flutter (17806): #26     Element.updateChild (package:flutter/src/widgets/framework.dart:2688)
E/flutter (17806): #27     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4606)
E/flutter (17806): #28     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2885)
E/flutter (17806): #29     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4711)
E/flutter (17806): #30     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2885)
E/flutter (17806): #31     Element.updateChild (package:flutter/src/widgets/framework.dart:2688)
E/flutter (17806): #32     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3631)
E/flutter (17806): #33     Element.rebuild (package:flutter/src/widgets/framework.dart:3473)
E/flutter (17806): #34     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3600)
E/flutter (17806): #35     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3736)
E/flutter (17806): #36     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3595)
E/flutter (17806): #37     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2885)
E/flutter (17806): #38     Element.updateChild (package:flutter/src/widgets/framework.dart:2688)
E/flutter (17806): #39     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4606)
E/flutter (17806): #40     Element.inflateWidget (package:flutter/src/widgets/f
```

## Flutter Doctor
```
Paste the output of running `flutter doctor -v` here.
[✓] Flutter (on Mac OS X 10.13.3 17D39a, locale zh-Hans-CN, channel master)
    • Flutter version 0.1.2-pre.8 at /Users/scott/dart/flutter
    • Framework revision 3723ec0383 (5 hours ago), 2018-02-14 10:24:08 +0100
    • Engine revision 05c5f817eb
    • Tools Dart version 2.0.0-dev.22.0
    • Engine Dart version 2.0.0-edge.3c4dccbd46f152be9e1b6ca95c57357e8e48057c

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.2)
    • Android SDK at /Users/scott/Library/Android/sdk
    • Android NDK at /Users/scott/Library/Android/sdk/ndk-bundle
    • Platform android-27, build-tools 27.0.2
    • ANDROID_HOME = /Users/scott/soft/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.2
    • CocoaPods version 1.3.1

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] IntelliJ IDEA Community Edition (version 2017.1.5)
    • Flutter plugin version 21.2.1
    • Dart plugin version 171.4694.29

[✓] VS Code (version 1.20.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Dart Code extension version 2.8.1

[✓] Connected devices
    • MI 6 • a3d8b48e • android-arm64 • Android 7.1.1 (API 25)
```

**Comment by btastic** [comment] 2018-02-14 16:42
Could you provide a code sample that leads to your issue?

**Comment by ZhangQinglian** [comment] 2018-02-15 06:37
```dart
@override
  Future<List<Clipping>> loadClipping(String userId) async{
    var where = {"user_id":userId};
    String url = API_CLIPPING_GET + JSON.encode(where) + "&count=1&limit=9999";
    var response = await get(url,headers: httpHead);
    List clippingList = JSON.decode(response.body)['results'];
    List<Clipping> result = new List();
    if(clippingList != null){
      print('------------- get clipping ${clippingList.length}');
      for(var clip in clippingList){
        result.add(new Clipping.fromJson(clip));
      }
    }
    return result;
  }
```

**Comment by btastic** [comment] 2018-02-15 08:12
Your code crashes at a "[...].whereFirst". I assume it is the code inside your get method. Can you show the code inside the get function?

**Comment by ZhangQinglian** [comment] 2018-02-15 14:39
```dart
/// Sends an HTTP GET request with the given headers to the given URL, which can
/// be a [Uri] or a [String].
///
/// This automatically initializes a new [Client] and closes that client once
/// the request is complete. If you're planning on making multiple requests to
/// the same server, you should use a single [Client] for all of those requests.
///
/// For more fine-grained control over the request, use [Request] instead.
Future<Response> get(url, {Map<String, String> headers}) =>
  _withClient((client) => client.get(url, headers: headers));
```
'get' function is part of ''package:http/http.dart''

**Comment by btastic** [comment] 2018-02-15 20:35
I can reproduce this issue in my code aswell. Seems to be a regression introduced in this commit from the dart:async package: https://github.com/dart-lang/async/commit/d2e984b5188a40000e6d6b6bab39e7a554698664

**Comment by btastic** [comment] 2018-02-15 20:47
The issue seems to be fixed in the master channel. I think we just have to wait until the dev branch gets updated.

**Comment by KevinTheGray** [comment] 2018-02-26 21:55
this is still open right?  I'm seeing this stem from `NetworkImage.load(...)`

**Comment by btastic** [comment] 2018-02-26 22:10
I am back on the dev channel, seems to be fine for me. I had the issues just using the HttpClient class.

**Comment by KevinTheGray** [comment] 2018-02-26 22:47
yeah, i think this actually may not be related to what I'm seeing... I need to investigate it some more.  Thanks

**Comment by ZhangQinglian** [comment] 2018-02-27 01:24
It is ok now.

**Comment by KevinTheGray** [comment] 2018-02-27 16:57
I also think my issue was fixed by updating properly.  I haven't seen it anymore

**Comment by mravn-google** [comment] 2018-02-27 21:42
The error may reappear after `flutter clean`. I currently get it when building example projects in `flutter/plugins` with the `--preview-dart-2` flag set:
```
$ flutter run --preview-dart-2
Running "flutter packages get" in example...          1.7s
Launching lib/main.dart on Nexus 5X in debug mode...
Initializing gradle...                                0.8s
Resolving dependencies...                             0.9s
Running 'gradlew assembleDebug'...                        
compiler message: file:///Users/mravn/.pub-cache/hosted/pub.dartlang.org/async-1.13.3/lib/src/typed/stream.dart:56:10: Error: The return type of the method 'TypeSafeStream::firstWhere' is dart.async::Future<dynamic>, which does not match the return type of the overridden method (dart.async::Future<#lib1::TypeSafeStream::T>).
compiler message: Change to a subtype of dart.async::Future<#lib1::TypeSafeStream::T>.
compiler message:   Future firstWhere(bool test(T element), {Object defaultValue()}) =>
compiler message:          ^
compiler message: : Error: This is the overriden method ('firstWhere').
compiler message: file:///Users/mravn/.pub-cache/hosted/pub.dartlang.org/async-1.13.3/lib/src/typed/stream.dart:56:10: Error: The method 'TypeSafeStream::firstWhere' has fewer named arguments than those of overridden method 'Stream::firstWhere'.
compiler message:   Future firstWhere(bool test(T element), {Object defaultValue()}) =>
compiler message:          ^
compiler message: : Error: This is the overriden method ('firstWhere').
compiler message: file:///Users/mravn/.pub-cache/hosted/pub.dartlang.org/async-1.13.3/lib/src/typed/stream.dart:59:10: Error: The return type of the method 'TypeSafeStream::lastWhere' is dart.async::Future<dynamic>, which does not match the return type of the overridden method (dart.async::Future<#lib1::TypeSafeStream::T>).
compiler message: Change to a subtype of dart.async::Future<#lib1::TypeSafeStream::T>.
compiler message:   Future lastWhere(bool test(T element), {Object defaultValue()}) =>
compiler message:          ^
compiler message: : Error: This is the overriden method ('lastWhere').
compiler message: file:///Users/mravn/.pub-cache/hosted/pub.dartlang.org/async-1.13.3/lib/src/typed/stream.dart:59:10: Error: The method 'TypeSafeStream::lastWhere' has fewer named arguments than those of overridden method 'Stream::lastWhere'.
compiler message:   Future lastWhere(bool test(T element), {Object defaultValue()}) =>
compiler message:          ^
compiler message: : Error: This is the overriden method ('lastWhere').
compiler message: file:///Users/mravn/.pub-cache/hosted/pub.dartlang.org/async-1.13.3/lib/src/typed/stream.dart:62:13: Error: The method 'TypeSafeStream::singleWhere' has fewer named arguments than those of overridden method 'Stream::singleWhere'.
compiler message:   Future<T> singleWhere(bool test(T element)) async =>
compiler message:             ^
compiler message: : Error: This is the overriden method ('singleWhere').
Built build/app/outputs/apk/debug/app-debug.apk (30.7MB).
Installing build/app/outputs/apk/app.apk...           9.2s
```
Flutter doctor:
```
[✓] Flutter (Channel master, v0.1.7-pre.11, on Mac OS X 10.13.3 17D102, locale en-US)
    • Flutter version 0.1.7-pre.11 at /Users/mravn/github/flutter
    • Framework revision 3b84503403 (17 hours ago), 2018-02-26 20:11:11 -0800
    • Engine revision ead227f118
    • Dart version 2.0.0-dev.28.0.flutter-0b4f01f759

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/mravn/Library/Android/sdk
    • Android NDK at /Users/mravn/Library/Android/sdk/ndk-bundle
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.2
    • CocoaPods version 1.2.1

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] IntelliJ IDEA Community Edition (version 2017.3.4)
    • Flutter plugin version 21.2.3
    • Dart plugin version 173.4548.30

[✓] Connected devices (1 available)
    • Nexus 5X • 00bff34682e4b2ab • android-arm64 • Android 8.1.0 (API 27)

• No issues found!
```

**Comment by mravn-google** [comment] 2018-02-27 21:58
cc @leafpetersen

**Comment by leafpetersen** [comment] 2018-02-27 22:27
@mravn-google The error message that you pasted in indicates that you are getting a very old version of async (1.13.3) that is not compatible with our latest dev releases.  There have been breaking changes leading up to Dart 2 , and we have been updating async to match them.  I'm not sure why you're getting an older version: flutter is up to date, and pins packages appropriately.  We have updated flutter to use 2.04 on master.  Perhaps plugins needs to upgrade its packages separately?  I don't really know how the flutter and flutter plugin repo keep their pubspecs in sync: I know that flutter framework does a global version solve on its own packages, but not sure if plugins does the same?

**Comment by leafpetersen** [comment] 2018-02-27 22:34
The original stacktrace on this issue looks to me like a mismatch in the engine that was being run and the async package being pulled in.  It looks like the VM version was using a snapshot of the core libraries from before the breaking changes to the Stream library, but was being run on a version of async which required a later VM.  It sounds like either there was a bad update, or else this caught things in a transiently bad state on master (though as far as I know we were never in a bad state - we deliberately staged things to be forward compatible as they rolled out).

**Comment by mravn-google** [comment] 2018-02-27 22:36
OK. `flutter packages upgrade` helped. Thanks.

**Comment by Hixie** [comment] 2018-05-30 22:57
Based on the comments here this seems to have been a transient issue. Closing. If you still see this please file a new bug and provide steps to reproduce. Thanks.

**Closed by Hixie** 2018-05-30 22:57 UTC
