### ISSUE TITLE
How to use SkSL-based shader warmup to build aar

### ISSUE THREAD

**Issue by TennisAndy** [flutter/flutter#92967] opened 2021-11-03 08:10 UTC
Hi Everyone,

I'm working on a project which is Flutter and Native Android mixed, and I need to build flutter part to aar.

My question is: How can I use flutter build aar to integrate the cached sksl.json file?

I have read [doc](https://flutter.dev/docs/perf/rendering/shader#how-to-use-sksl-warmup),  and know how to build apk with:
`flutter build apk --bundle-sksl-path flutter_01.sksl.json`

While when I try to build aar: 
`flutter build aar --no-debug --no-profile --build-number=1.0.0 --bundle-sksl-path flutter_01.sksl.json`
I can not make it work.

Dev env:
`D:\workspace\flutter_module_eight_eye>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.5.3, on Microsoft Windows [Version 10.0.19042.1165], locale zh-CN)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[√] Android Studio (version 2020.3)
[√] IntelliJ IDEA Ultimate Edition (version 2020.3)
[√] VS Code (version 1.54.3)
[√] Connected device (3 available)

• No issues found!
`

**Comment by darshankawar** [comment] 2021-11-04 06:22
Keeping it open for further insights from the team.

**Comment by MrBirb** [comment] 2021-12-08 14:08
@darshankawar Looks like a duplicate of #81919?

**Comment by darshankawar** [comment] 2021-12-09 05:05
Yes, thanks for the tip @MrBirb.
Closing this as a duplicate.

**Closed by darshankawar** 2021-12-09 05:05 UTC
Labels: platform-android, tool, d: api docs, a: existing-apps, documentation, passed first triage
