### ISSUE TITLE
problem in show/hide widget 

### ISSUE THREAD

**Issue by srkrishnan1989** [flutter/flutter#108435] opened 2022-07-27 13:32 UTC
problem in show/hide widget 

audio is separate state class,  I am playing 'v3' of song  , hiding player and restore player, player should show v3 but it shows 'v1'

<details>
<summary>code sample</summary>

```
import 'package:flutter/material.dart';
import '../AudioPlayPausedownlist.dart';
import '../Down_Select_Song.dart';
class ListviewDemo extends StatefulWidget {
  const ListviewDemo({Key? key}) : super(key: key);

  @override
  State<ListviewDemo> createState() => _ListviewDemoState();
}

class _ListviewDemoState extends State<ListviewDemo> {
  double _svalue = 19.0;
  bool scrolllockbutton = false;
  bool iconlockbutton = false;
  bool player = false;
  late double sleft;
  late double stop;

  final keyText = GlobalKey();

  List<String> dataList = [
    "2K",
    "86-DOS",
    "A/UX",
    "Acados",
    "ACP (Airline Control Program)",
    "AdaOS",
    "ADMIRAL",
    "Adrenaline",
    "aerolitheOS",
    "Aimos",
    "AIOS",
    "AIX",
    "Allegro",
    "AllianceOS",
    "Alpha OS",
    "Alto OS",
    "Amiga OS",
    "Amoeba",
    "Amstrad",
    "AMX RTOS",
    "AneedA",
  ];
   List<DownSong> mysong = [
    DownSong(
      showName: "song 1",
      downid: "https://www.thiruarutpa.org/Download/VG000029231F",
      dropdownname: "v1",
    ),
    DownSong(
      showName: "song 1",
      downid: "https://www.thiruarutpa.org/Download/VG000029312F",
      dropdownname: "v2",
    ),
    DownSong(
      showName: "song 1",
      downid: "https://www.thiruarutpa.org/Download/VG000029313F",
      dropdownname: "v3",
    ),
  ];
  @override
  void initState() {
    super.initState();
    initposition();
  }

  initposition() {
    sleft = 10;
    stop = 10;
  }
Widget audiotbutton() {
    return IconButton(
        icon: Icon(Icons.audiotrack, color: Colors.green, size: 25),
        onPressed: () {
          setState(() {
            player = !player;
          });
        }
        //)
        );
  }

  Widget audio() {
    return Visibility(
        visible: player,
        child: SingleChildScrollView(
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              Row(
                mainAxisAlignment: MainAxisAlignment.end,
                children: [
                  IconButton(
                      icon: Icon(Icons.cancel_rounded,
                          color: Colors.red, size: 25),
                      onPressed: () {
                        setState(() {
                          // player = false;
                          player = !player;
                        });
                      }),
                ],
              ),
              AudioPlayPauseDownList('ma6002', mysong)
            ],
          ),
        ));
  }
  Widget scrolllockappbutton() {
    return IconButton(
        icon: scrolllockbutton
            ? const Icon(Icons.lock, color: Colors.red, size: 25)
            : const Icon(Icons.lock_open_sharp, color: Colors.green, size: 25),
        onPressed: () {
          setState(() {
            scrolllockbutton = !scrolllockbutton;
          });
        }
        //)
        );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: NestedScrollView(
          // controller: ancon,
          floatHeaderSlivers: true,
          headerSliverBuilder: (BuildContext context, bool innerBoxIsScrolled) {
            return <Widget>[
              SliverAppBar(
                snap: true,
                pinned: false,
                floating: true,
                title: const Text("Demo"),
                actions: <Widget>[
                audiotbutton(),
                  scrolllockappbutton(),
                ],
              ),
            ];
          },
          body: Stack(children: [
           Column(children: [
            Expanded(
              child: ListView.builder(
                  itemCount: dataList.length,
                  itemBuilder: (context, index) {
                    return Column(children: [
                      ListTile(
                        title: Text(
                          '\n${dataList[index]}',
                          style: const TextStyle(fontSize: 50),
                        ),
                      ),
                      const Divider(
                        height: 1,
                        color: Colors.grey,
                      )
                    ]);
                  }),
            ),
            audio()
                             ]),
            Positioned(
                left: sleft,
                top: stop,
                child: scrolllockbutton
                    ? showbutton()
                    : Draggable(
                        feedback: showbutton(),
                        child: showbutton(),
                        onDragEnd: (drag) {
                          final renderbox =
                              context.findRenderObject() as RenderBox;
                          Offset off = renderbox.globalToLocal(drag.offset);
                          setState(() {
                            stop = off.dy - 55;
                            sleft = off.dx + 5;
                          });
                        },
                      ))
          ])),
    );
  }

  showbutton() {
    return Material(
        // key: keyText,
        child: ClipRRect(
            borderRadius: BorderRadius.circular(5.0),
            child: Container(
                //height: 50.0,
                color: Colors.red.shade100,
                child: iconlockbutton
                    ? TextButton(
                        // color: Colors.blue,
                        // icon:
                        child: const Icon(Icons.add_a_photo),
                        //const Text('data'),
                        onPressed: () {
                          setState(() {
                            iconlockbutton = !iconlockbutton;
                          });
                        },
                      )
                    : IconButton(
                        color: Colors.blue,
                        icon: const Icon(Icons.add_a_photo),
                        onPressed: () {
                          setState(() {
                            iconlockbutton = !iconlockbutton;
                          });
                        },
                      ))));
  }
}

import 'dart:async';
import 'dart:core';
import 'dart:io';

import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

import 'package:audioplayers/audioplayers.dart';
import '../Down_Select_Song.dart';

import 'package:path_provider/path_provider.dart';

import 'package:volume_controller/volume_controller.dart';

typedef void OnError(Exception exception);

enum PlayerState { stopped, playing, paused }

class AudioPlayPauseDownList extends StatefulWidget {
  AudioPlayPauseDownList(this.myplayerId, this.mysong);

  final String myplayerId;

  final List<DownSong> mysong;
  @override
  _AudioPlayPauseDownListState createState() => _AudioPlayPauseDownListState();
}

class _AudioPlayPauseDownListState extends State<AudioPlayPauseDownList> {
  TextEditingController controller = TextEditingController();
  TextEditingController metasController = TextEditingController();
  double bufferingProgress = 0.0;
  //Media? metasMedia;
  late double mp3size;
  late String mp3filename;
  late String mp3showname;
  late String mp3url;
  late String mp3dropdownname;
  late DownSong dropdownValue;

  bool ispresed = false;
  bool isstoped = false;
  bool istextclicked = false;
  bool player = false;
  final nowplaying = "Playing";
  final nowpaused = "Praused";
  final nowstopped = "Stopped";
  final listen = "Listen ";
  var status;

  //late StreamSubscription _positionSubscription;
  Duration _duration = const Duration();
  Duration _position = const Duration();
  late AudioPlayer advancedPlayer;
  late AudioCache audioCache;
  String getmp3filenamepath = '';
  late Directory directory2;
  bool veiw = false;
  double _getVolume = 0;
  double _setVolumeValue = 0;

  StreamSubscription? _durationSubscription;
  StreamSubscription? _positionSubscription;
  StreamSubscription? _playerCompleteSubscription;
  StreamSubscription? _playerStateChangeSubscription;
  PlayerState _playerState = PlayerState.stopped;
  PlayerState? _audioPlayerState;
  void changeview() {
    setState(() {
      veiw = true;
    });
    findpath();
    if (veiw) {
      play();
    }
  }

  void initandroidvolume() {
    VolumeController().listener((volume) {});

    VolumeController().getVolume().then((volume) => _setVolumeValue = volume);
  }

  @override
  void initState() {
    super.initState();
    _initStreams();

    status = listen;
    dropdownValue = widget.mysong[0];
    findpath();
    updatesong();
  }

  @override
  void dispose() {
    _durationSubscription?.cancel();
    _positionSubscription?.cancel();
    _playerCompleteSubscription?.cancel();
    _playerStateChangeSubscription?.cancel();
    super.dispose();
  }

  findpath() async {
    if (Platform.isLinux) {
      directory2 = (await getApplicationSupportDirectory());
      String newPath = "";
      //String newPath = "";
      print(directory2);

      newPath = newPath + "/thiruApp";
      newPath = directory2.path + "/thiruApp";

      directory2 = Directory(newPath);

      setState(() {
        getmp3filenamepath = newPath + "/$mp3filename";
        print(getmp3filenamepath);

        viewpath();
      });
    }
    if (Platform.isAndroid) {
      directory2 = (await getExternalStorageDirectory())!;
      String newPath = "";
      //String newPath = "";
      print(directory2);
      List<String> paths = directory2.path.split("/");
      for (int x = 1; x < paths.length; x++) {
        String folder = paths[x];
        if (folder != "Android") {
          //newPath += "/" + folder;
        } else {
          break;
        }
      }
      //newPath = newPath + "/thiruApp";
      newPath = directory2.path + "/thiruApp";
      setState(() {
        //getdataa= directory+"/thiruApp";
        //directory2=directory.path+"/thiruApp";

        getmp3filenamepath = newPath + "/$mp3filename";
        print('getmp3filenamepath is $getmp3filenamepath');
      });
      viewpath();
    }
  }

  viewpath() async {
    if (await File(getmp3filenamepath).exists() == true) {
      //if (await File(getmp3filenamepath + '.mp3').exists() == true) {
      print("$getmp3filenamepath is exists");
      setState(() {
        veiw = true;
        //getdataa='true';
      });
      print("view is now $veiw");
    }
  }

  PlayerState playerState = PlayerState.stopped;

  get isPlaying => playerState == PlayerState.playing;
  get isPaused => playerState == PlayerState.paused;
  get durationText =>
      _duration != null ? _duration.toString().split('.').first : '';

  get positionText =>
      _position != null ? _position.toString().split('.').first : '';
  get negpositionText => _duration != null
      ? (_duration - _position).toString().split('.').first
      : '';
  void _initStreams() {
    advancedPlayer = AudioPlayer(playerId: widget.myplayerId);
    _durationSubscription = advancedPlayer.onDurationChanged.listen((duration) {
      setState(() => _duration = duration);
    });

    _positionSubscription = advancedPlayer.onPositionChanged.listen(
      (p) => setState(() => _position = p),
    );

    advancedPlayer.onPlayerComplete.listen((event) {
      advancedPlayer.stop();
      onComplete();
      setState(() {
        _playerState = PlayerState.stopped;
        _position = _duration;
        print('stopped 1');
      });
    });
    print(advancedPlayer.state);
    if (advancedPlayer.state == PlayerState.playing) {
      setState(() {
        ispresed == true;
      });
      print('ispresed is $ispresed');
    }

    advancedPlayer.onPlayerStateChanged.listen((states) {
      // setState(() {
      // _audioPlayerState = states as PlayerState?;
      if (advancedPlayer.onPlayerComplete == true) {
        playerState = PlayerState.stopped;
        onComplete();
        setState(() {
          _position = _duration;
          print('stopped 2');
        });
      }
      onError:
      (msg) {
        setState(() {
          playerState = PlayerState.stopped;
          _duration = Duration(seconds: 0);
          _position = Duration(seconds: 0);
          print('stopped 3');
        });
      };
    });
  }

  late String localFilePath;

  void updatesong() async {
    DownSong instance = widget.mysong[0];

    mp3showname = instance.showName;
    mp3url = instance.downid;

    mp3dropdownname = instance.dropdownname;
  }

  Widget slider2() {
    return Row(
        mainAxisAlignment: MainAxisAlignment.spaceEvenly,
        children: <Widget>[
          slidernew(),
        ]);
  }

  Widget playbtn() {
    return TextButton(
      child: Icon(ispresed ? Icons.pause : Icons.play_arrow),
      onPressed: () {
        //audioCache.play('disco.mp3');
        //assetsAudioPlayer.open(Audio("assets/audios/${widget.mp3name}.mp3"));
        setState(() {
          if (ispresed == false) {
            play();
          } else if (ispresed == true) {
            pause();
          }
          // ignore: unrelated_type_equality_checks
          if (advancedPlayer.stop == true) {
            ispresed = false;
            isstoped = false;
          }
        });
      },
    );
  }

  Widget dropdownbtn() {
    return DropdownButton<DownSong>(
      value: dropdownValue,
      onChanged: (DownSong? newValue) async {
        setState(() {
          stop();
          veiw = false;
          dropdownValue = newValue!;
          mp3showname = newValue.showName;

          mp3url = newValue.downid;

          print('mp3filename is $mp3filename');

          findpath();

          play();
        });
      },
      items: widget.mysong.map<DropdownMenuItem<DownSong>>((DownSong newValue) {
        return DropdownMenuItem<DownSong>(
          value: newValue,
          child: Text(
            newValue.dropdownname,
            style: const TextStyle(
              fontFamily: 'MuktaMalar',
              fontSize: 17.0,

              //color: Colors.black
            ),
          ),
        );
      }).toList(),
    );
  }

  Widget stopbtn() {
    return TextButton(
        child: const Icon(Icons.stop),
        onPressed: () {
          stop();
        }
        //)
        );
  }

  Widget andriodVolume() {
    return Slider(
      min: 0,
      max: 1,
      onChanged: (double value) {
        setState(() {
          _setVolumeValue = value;
          VolumeController().setVolume(_setVolumeValue);
        });
      },
      value: _setVolumeValue,
    );
  }

  Widget showVolume() {
    return Row(
        mainAxisAlignment: MainAxisAlignment.spaceEvenly,
        children: <Widget>[
          andriodVolume(),
          // if (myplatformlinux) linuxVolume(),
          // andriodVolume()
        ]);
  }

  Widget slidernew() {
    return Expanded(
      child: SizedBox(
        width: MediaQuery.of(context).size.height * .90,
        child: Slider(
          onChanged: (v) {
            final duration = _duration;
            if (duration == null) {
              return;
            }
            final position = v * duration.inMilliseconds;
            advancedPlayer.seek(Duration(milliseconds: position.round()));
          },
          value: (_position != null &&
                  _duration != null &&
                  _position.inMilliseconds > 0 &&
                  _position.inMilliseconds < _duration.inMilliseconds)
              ? _position.inMilliseconds / _duration.inMilliseconds
              : 0.0,
        ),
      ),
    );
  }

  Widget showduration() {
    late String showduration;

    showduration = durationText;

    late String shownegpositionText;

    shownegpositionText = durationText;

    return GestureDetector(
        onTap: () {
          setState(() {
            if (istextclicked == false) {
              istextclicked = true;
            } else if (istextclicked == true) {
              istextclicked = false;
            }
          });
        },
        child: Padding(
            padding: const EdgeInsets.only(left: 8.0),
            child: SizedBox(
                width: 80,
                height: 20,
                //color: Colors.green,
                child: Center(
                  child: istextclicked
                      ? Text(
                          '-$shownegpositionText',
                          style: const TextStyle(fontSize: 18),
                        )
                      : Text(
                          showduration.toString(),
                          style: const TextStyle(fontSize: 18),
                        ),
                ))));
  }

  Widget showposition() {
    late String showposition;

    showposition = positionText;

    return Padding(
      padding: const EdgeInsets.only(left: 8.0),
      child: SizedBox(
        width: 80,
        height: 20,
        //color: Colors.green,
        child: Center(
          child: Text(
            showposition.toString(),
            style: const TextStyle(
                //fontFamily: 'MuktaMalar',
                //fontWeight: FontWeight.bold,
                fontSize: 18),
          ),
        ),
      ),
    );
  }

  Widget localplayer() {
    return Column(mainAxisAlignment: MainAxisAlignment.center, children: [
      Row(mainAxisAlignment: MainAxisAlignment.end,
          //crossAxisAlignment: CrossAxisAlignment.stretch,
          children: <Widget>[
            const Text(
              'Vol',
              style: TextStyle(fontSize: 18),
            ),
            showVolume(),
          ]),
      Padding(
        padding: EdgeInsets.only(
            left: MediaQuery.of(context).size.width / 97,
            right: MediaQuery.of(context).size.width / 97,
            bottom: 5.0),
        child: Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: <Widget>[
              showposition(),
              Row(//mainAxisAlignment: MainAxisAlignment.spaceBetween,
                  //crossAxisAlignment: CrossAxisAlignment.stretch,
                  children: <Widget>[
                playbtn(),
                stopbtn(),
              ]),
              showduration(),
            ]),
      ),
      slider2(),
    ]);
  }

  Widget localAsset() {
    return Column(mainAxisAlignment: MainAxisAlignment.center, children: <
        Widget>[
      Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: <Widget>[
        Flexible(
          flex: 1,
          child:
              Row(mainAxisAlignment: MainAxisAlignment.end, children: <Widget>[
            Padding(
              padding: EdgeInsets.only(right: 10),
              child: dropdownbtn(),
            ),
          ]),
        ),
      ]),
      Row(
        mainAxisAlignment: MainAxisAlignment.start,
        children: [
          Flexible(
            child: Padding(
              padding: const EdgeInsets.only(left: 4.0),
              child: Text(
                "$status $mp3showname",
                overflow: TextOverflow.ellipsis,
                style: const TextStyle(
                    fontFamily: 'MuktaMalar',
                    //fontWeight: FontWeight.bold,

                    fontSize: 18),
              ),
            ),
          ),
        ],
      ),
      localplayer()
    ]);
  }

  void seekToSecond(int second) {
    Duration newDuration = Duration(seconds: second);

    advancedPlayer.seek(newDuration);
  }

  Future play() async {
    await advancedPlayer.play(UrlSource(mp3url));

    ispresed = true;
    isstoped = true;

    setState(() {
      playerState = PlayerState.playing;
      status = nowplaying;
    });
    // }
  }

  Future pause() async {
    await advancedPlayer.pause();
    ispresed = false;
    isstoped = false;
    //audioPlayer.pause();
    setState(() {
      playerState = PlayerState.paused;
      status = nowpaused;
    });
  }

  Future stop() async {
    await advancedPlayer.stop();
    setState(() {
      playerState = PlayerState.stopped;
      //position = Duration();
      ispresed = false;
      _position = const Duration(hours: 0, minutes: 0, seconds: 0);
      _duration = const Duration(hours: 0, minutes: 0, seconds: 0);
      status = nowstopped;
    });
  }

  void onComplete() {
    setState(() {
      playerState = PlayerState.stopped;
      ispresed = false;
      istextclicked = false;
    });
  }

  @override
  Widget build(BuildContext context) {
    return localAsset();
  }
}

import 'dart:convert';

class DownSong {
  String showName;
  String downid;
  String dropdownname;

  DownSong({
    required this.showName,
    required this.downid,
    required this.dropdownname,
  });

  factory DownSong.fromJson(Map<String, dynamic> jsonData) {
    return DownSong(
      showName: jsonData['songname'],
      downid: jsonData['downid'],
      dropdownname: jsonData['dropdownname'],
    );
  }

  static Map<String, dynamic> toMap(DownSong downSong) => {
        'songname': downSong.showName,
        'downid': downSong.downid,
        'dropdownname': downSong.dropdownname,
      };

  static String encode(List<DownSong> musics) => json.encode(
        musics
            .map<Map<String, dynamic>>((music) => DownSong.toMap(music))
            .toList(),
      );

  static List<DownSong> decode(String musics) =>
      (json.decode(musics) as List<dynamic>)
          .map<DownSong>((item) => DownSong.fromJson(item))
          .toList();
}
```

</details>

https://user-images.githubusercontent.com/6891619/181259252-f31a8f7b-f053-475f-880d-d3212ae04c86.mp4

**Comment by danagbemava-nc** [comment] 2022-07-27 13:57
Hi @srkrishnan1989, your code sample contains too many moving parts for us to properly investigate this issue. 

Please provide only the relevant portion of the code required to reproduce the issue so that we can investigate this. 

Thank you

**Comment by srkrishnan1989** [comment] 2022-07-27 14:26
Hi @danagbemava-nc  create new flutter project save ListviewDemo Class as  list_view.dart file,  save AudioPlayPauseDownList Class as AudioPlayPausedownlist.dart file, save DownSong Class as Down_Select_Song.dart file

ListviewDemo Class is main, so assign to 'home' in MyApp on main.dart

AudioPlayPauseDownList Class and DownSong Class is for supporting purpose,

add these dependencies in pubspec.yaml
volume_controller: ^2.0.3
 path_provider: ^2.0.11
 audioplayers: ^1.0.1

**Comment by danagbemava-nc** [comment] 2022-07-28 08:26
Hi @srkrishnan1989, the reason your value is always reset is that in the initState of `AudioPlayPauseDownList`
you set the dropdownValue = the first item in the song list. 

```dart
 @override
  void initState() {
    super.initState();
    _initStreams();

    status = listen;
    **dropdownValue = widget.mysong[0];**
    findpath();
    updatesong();
  }
```

You need to find a way to make sure that the selected song is what is selected when the view is revealed. 

I'll be closing this as it is an issue with your implementation. 

Thank you

**Closed by danagbemava-nc** 2022-07-28 08:26 UTC
Labels: in triage
