### ISSUE TITLE
Implement window transparency for Flutter desktop apps

### ISSUE THREAD

**Issue by scotch-hub** [flutter/flutter#94438] opened 2021-12-01 00:40 UTC
I have been trying for the last few days to implement transparency for a Flutter Linux app but everything I have done hasn't worked. I tried modifying the my_application.cc file and use the cairo library like I normally would for any GTK app but this hasn't worked.

Would it be possible to implement window transparency into flutter desktop directly so that it can be easily accessible to developers?

**Comment by stuartmorgan** [comment] 2021-12-01 01:51
Duplicate of https://github.com/flutter/flutter/issues/66751

**Closed by stuartmorgan** 2021-12-01 01:51 UTC
