### ISSUE TITLE
startImageStream makes app crash when sent to background and then to foreground

### ISSUE THREAD

**Issue by pmcarlos** [flutter/flutter#27736] opened 2019-02-10 00:13 UTC
## Steps to Reproduce
```dart
CameraController controller;
controller = CameraController(cameras[0], ResolutionPreset.medium);
controller.initialize().then((_) {
      controller.startImageStream((CameraImage image) {
        print('statrtimage');
      });
});
setState(() {});
```

Running above command starts the camera (thats working fine) but when i add `startStreamImage` it starts working fine, it prints correctly the problem is once you click home menu or back and then you go back to the app it crashes:

## Logs

```
D/AndroidRuntime(22426): Shutting down VM
E/AndroidRuntime(22426): FATAL EXCEPTION: main
E/AndroidRuntime(22426): Process: com.pmcarlosdev.ctrlf, PID: 22426
E/AndroidRuntime(22426): java.lang.IllegalStateException: Session has been closed; further changes are illegal.
E/AndroidRuntime(22426): 	at android.hardware.camera2.impl.CameraCaptureSessionImpl.checkNotClosed(CameraCaptureSessionImpl.java:672)
E/AndroidRuntime(22426): 	at android.hardware.camera2.impl.CameraCaptureSessionImpl.setRepeatingRequest(CameraCaptureSessionImpl.java:235)

```

```
[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.14.3 18D42, locale en-MX)
    • Flutter version 1.0.0 at /Users/pmcarlos/Flutter
    • Framework revision 5391447fae (2 months ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/pmcarlos/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.31.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.22.3

[✓] Connected device (1 available)
    • Moto G 5 Plus • ZY224LWX3R • android-arm • Android 8.1.0 (API 27)
```

**Comment by Thetyne** [comment] 2019-02-22 13:22
Same here.
the problem is in CameraPlugin.java, inside CameraCaptureSession.StateCallback(), method onConfigured.

the plugin catch only CameraAccessException type, but it must catch all exception type.

sample:
before
````
new CameraCaptureSession.StateCallback() {
              @Override
              public void onConfigured(@NonNull CameraCaptureSession cameraCaptureSession) {
                try {
                  if (cameraDevice == null) {
                    result.error("configureFailed", "Camera was closed during configuration", null);
                    return;
                  }
                  Camera.this.cameraCaptureSession = cameraCaptureSession;
                  captureRequestBuilder.set(
                      CaptureRequest.CONTROL_MODE, CameraMetadata.CONTROL_MODE_AUTO);
                  cameraCaptureSession.setRepeatingRequest(
                      captureRequestBuilder.build(), null, null);
                  mediaRecorder.start();
                  result.success(null);
                } catch (CameraAccessException e) {
                  result.error("cameraAccess", e.getMessage(), null);
                }
              }

              @Override
              public void onConfigureFailed(@NonNull CameraCaptureSession cameraCaptureSession) {
                result.error("configureFailed", "Failed to configure camera session", null);
              }
            },
            null);
````

after
````
new CameraCaptureSession.StateCallback() {
              @Override
              public void onConfigured(@NonNull CameraCaptureSession cameraCaptureSession) {
                try {
                  if (cameraDevice == null) {
                    result.error("configureFailed", "Camera was closed during configuration", null);
                    return;
                  }
                  Camera.this.cameraCaptureSession = cameraCaptureSession;
                  captureRequestBuilder.set(
                      CaptureRequest.CONTROL_MODE, CameraMetadata.CONTROL_MODE_AUTO);
                  cameraCaptureSession.setRepeatingRequest(
                      captureRequestBuilder.build(), null, null);
                  mediaRecorder.start();
                  result.success(null);
                } catch (CameraAccessException e) {
                  result.error("cameraAccess", e.getMessage(), null);
                }catch (IllegalStateException e) {
                  result.error("IllegalStateException", e.getMessage(), null);
                }catch (Exception e) {
                  result.error("Exception", e.getMessage(), null);
                }
              }

              @Override
              public void onConfigureFailed(@NonNull CameraCaptureSession cameraCaptureSession) {
                result.error("configureFailed", "Failed to configure camera session", null);
              }
            },
            null);
````

**Comment by YuzhouZhang** [comment] 2019-02-26 08:07
Same problem!

When I try to stopImageStream() in deactivate(), if I run deactivate() twice, the app crashes.

`
  @override
  void deactivate() {
    print('deactivate');
    if (controller != null &&
        controller.value.isStreamingImages &&
        controller.value.isInitialized) {
      controller.stopImageStream();
    }
    super.deactivate();
  }
`

> D/AndroidRuntime(12039): Shutting down VM
E/AndroidRuntime(12039): FATAL EXCEPTION: main
E/AndroidRuntime(12039): Process: com.wingtech.quicklearnersdictionary, PID: 12039
E/AndroidRuntime(12039): java.lang.IllegalStateException: Session has been closed; further changes are illegal.
E/AndroidRuntime(12039): 	at android.hardware.camera2.impl.CameraCaptureSessionImpl.checkNotClosed(CameraCaptureSessionImpl.java:834)
E/AndroidRuntime(12039): 	at android.hardware.camera2.impl.CameraCaptureSessionImpl.setRepeatingRequest(CameraCaptureSessionImpl.java:288)
E/AndroidRuntime(12039): 	at io.flutter.plugins.camera.CameraPlugin$Camera$8.onConfigured(CameraPlugin.java:785)
E/AndroidRuntime(12039): 	at android.hardware.camera2.impl.CallbackProxies$SessionStateCallbackProxy.lambda$onConfigured$0(CallbackProxies.java:53)
E/AndroidRuntime(12039): 	at android.hardware.camera2.impl.-$$Lambda$CallbackProxies$SessionStateCallbackProxy$soW0qC12Osypoky6AfL3P2-TeDw.run(Unknown Source:4)
E/AndroidRuntime(12039): 	at android.os.Handler.handleCallback(Handler.java:873)
E/AndroidRuntime(12039): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(12039): 	at android.os.Looper.loop(Looper.java:193)
E/AndroidRuntime(12039): 	at android.app.ActivityThread.main(ActivityThread.java:6718)
E/AndroidRuntime(12039): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(12039): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/AndroidRuntime(12039): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by Thetyne** [comment] 2019-02-26 09:51
i have submit Pull request https://github.com/flutter/plugins/pull/1282

and temporary package : camera_fix_exception

**Comment by YuzhouZhang** [comment] 2019-03-22 08:48
> i have submit Pull request [flutter/plugins#1282](https://github.com/flutter/plugins/pull/1282)
> 
> and temporary package : camera_fix_exception

Hi, thank you for your camera_fix_exception plugin!

There is no uncaught Exception anymore.

But if I call dispose() when the camera is streaming images, then when I back to the camera view, its a black screen until I call startImageStream again.

**Comment by Thetyne** [comment] 2019-03-24 18:35
I will test your issue

**Comment by YuzhouZhang** [comment] 2019-04-02 07:21
> I will test your issue

Sorry, I found it's my fault.

Bad code:

```
  @override
  void initState() {
    super.initState();

    _cameraController =
        new CameraController(cameras[0], ResolutionPreset.medium);
    _cameraController.initialize().then((_) {
      if (!mounted) {
        return;
      }else{
        _cameraController.startImageStream(onAvailable);
      }
      setState(() {});
    });
  }

```

Good code:

```
  @override
  void initState() {
    super.initState();

    _cameraController =
        new CameraController(cameras[0], ResolutionPreset.medium);
    _cameraController.initialize().then((_) {
      if (!mounted) {
        return;
      }
      setState(() {});
    });
  }

```

I don't know why, but if I startImageStream() immediately after initialize(), it will make cameraPreview black. 

Move `_cameraController.startImageStream(onAvailable);` to another place will fix this issue.

**Comment by mukhtarfauzi** [comment] 2019-10-11 02:15
is there anyone who has solved this issue with stream and black camera preview?

**Comment by Thetyne** [comment] 2019-10-11 05:41
I stop stream and dispose the camera controller when app enter to pause state.

**Comment by stuartmorgan** [comment] 2022-02-24 21:42
According to the last comment in the PR, this was fixed some time ago; closing as obsolete.

**Closed by stuartmorgan** 2022-02-24 21:42 UTC
Labels: severe: crash, plugin, p: first party, p: camera, P4, severe: fatal crash
