### ISSUE TITLE
Poor error message if textBaseline not specified when crossAxisAlignment = CrossAxisAlignment.baseline

### ISSUE THREAD

**Issue by djlondon** [flutter/flutter#78468] opened 2021-03-17 21:27 UTC
## Steps to Reproduce

Create a `Row` or `Column` and set `crossAxisAlignment: CrossAxisAlignment.baseline`, without setting `textBaseline`:

```
Column(crossAxisAlignment: CrossAxisAlignment.baseline, children: []);
```

Raising this bug since the error message told me to! 
> Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.

<details>
<summary>version info</summary>

> Flutter 2.0.2 • channel stable • https://github.com/flutter/flutter.git
> Framework • revision 8962f6dc68 (6 days ago) • 2021-03-11 13:22:20 -0800
> Engine • revision 5d8bf811b3
> Tools • Dart 2.12.1

</details>

**Comment by pedromassangocode** [comment] 2021-03-18 08:05
Hi @djlondon 
I cannot reproduce this issue as the error message I get is well explained and different of what you are reporting.

```console
Performing hot restart...
Waiting for connection from debug service on Chrome...
Restarted application in 4,816ms.

======== Exception caught by widgets library =======================================================
The following assertion was thrown building MyHomePage(dirty):
Assertion failed: file:///Users/pedromassango/Code/flutter_stable/packages/flutter/lib/src/widgets/basic.dart:4134:15
crossAxisAlignment != CrossAxisAlignment.baseline || textBaseline != null
"textBaseline is required if you specify the crossAxisAlignment with CrossAxisAlignment.baseline"

The relevant error-causing widget was: 
  MyHomePage file:///Users/pedromassango/dev/Projects/flutter_example/lib/main.dart:16:13
When the exception was thrown, this was the stack: 
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 236:49  throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 29:3    assertFailed
packages/flutter/src/widgets/basic.dart 4134:80                               new
packages/flutter/src/widgets/basic.dart 4704:8                                new
packages/flutter_example/main.dart 28:15                                      build
...
====================================================================================================

```

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 2.0.2, on macOS 11.2.3 20D91 darwin-x64, locale en-AO)
    • Flutter version 2.0.2 at /Users/pedromassango/Code/flutter_stable
    • Framework revision 8962f6dc68 (6 days ago), 2021-03-11 13:22:20 -0800
    • Engine revision 5d8bf811b3
    • Dart version 2.12.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/pedromassango/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 54.0.3
    • Dart plugin version 203.7759

[✓] VS Code (version 1.54.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.2.3 20D91 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 89.0.4389.90

! Doctor found issues in 1 category.
```

</details>

**Comment by djlondon** [comment] 2021-03-18 12:16
Running the same app as @pedromassango, the output is still:
```
Launching lib/main.dart on sdk gphone x86 arm in debug mode...
Running Gradle task 'assembleDebug'...
Running Gradle task 'assembleDebug'... Done                        11.0s
✓ Built build/app/outputs/flutter-apk/app-debug.apk.

══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY╞═════════════════════════════
The following assertion was thrown building MyApp(dirty):
textBaseline is required if you specify the crossAxisAlignment with
CrossAxisAlignment.baseline
'package:flutter/src/widgets/basic.dart':
Failed assertion: line 4134 pos 15: 'crossAxisAlignment !=
CrossAxisAlignment.baseline ||
textBaseline != null'

Either the assertion indicates an error in the framework itself, or we should
provide substantially
more information in this error message to help you determine and fix the
underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was:
  MyApp file:///Users/dominic/Documents/dart/error_test/lib/main.dart:3:23

When the exception was thrown, this was the stack:
#2      new Flex (package:flutter/src/widgets/basic.dart:4134:15)
#3      new Column (package:flutter/src/widgets/basic.dart:4704:8)
#4      MyApp.build (package:error_test/main.dart:14:17)
#5      StatelessElement.build
(package:flutter/src/widgets/framework.dart:4569:28)
#6      ComponentElement.performRebuild
(package:flutter/src/widgets/framework.dart:4495:15)
#7      Element.rebuild (package:flutter/src/widgets/framework.dart:4189:5)
#8      ComponentElement._firstBuild
(package:flutter/src/widgets/framework.dart:4474:5)
#9      ComponentElement.mount
(package:flutter/src/widgets/framework.dart:4469:5)
#10     Element.inflateWidget
(package:flutter/src/widgets/framework.dart:3541:14)
#11     Element.updateChild
(package:flutter/src/widgets/framework.dart:3306:18)
#12     RenderObjectToWidgetElement._rebuild
(package:flutter/src/widgets/binding.dart:1182:16)
#13     RenderObjectToWidgetElement.mount
(package:flutter/src/widgets/binding.dart:1153:5)
#14     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure>
(package:flutter/src/widgets/binding.dart:1095:18)
#15     BuildOwner.buildScope
(package:flutter/src/widgets/framework.dart:2647:19)
#16     RenderObjectToWidgetAdapter.attachToRenderTree
(package:flutter/src/widgets/binding.dart:1094:13)
#17     WidgetsBinding.attachRootWidget
(package:flutter/src/widgets/binding.dart:934:7)
#18     WidgetsBinding.scheduleAttachRootWidget.<anonymous closure>
(package:flutter/src/widgets/binding.dart:915:7)
(elided 13 frames from class _AssertionError, class _RawReceivePortImpl, class
_Timer, dart:async, and dart:async-patch)
```

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.0.2, on macOS 11.2.3 20D91 darwin-x64, locale en-GB)
    • Flutter version 2.0.2 at /usr/local/Caskroom/flutter/2.0.2/flutter
    • Framework revision 8962f6dc68 (7 days ago), 2021-03-11 13:22:20 -0800
    • Engine revision 5d8bf811b3
    • Dart version 2.12.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/dominic/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.54.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (2 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 89.0.4389.90

• No issues found!
```
</details>

Tried with both sound and unsound null safety.

**Comment by pedromassangocode** [comment] 2021-03-18 12:48
Hi @djlondon 
Thanks for providing the logs, I see your log messages starts with:

> Launching lib/main.dart on sdk gphone x86 arm in debug mode...
> Running Gradle task 'assembleDebug'...
> Running Gradle task 'assembleDebug'... Done                        11.0s
> ✓ Built build/app/outputs/flutter-apk/app-debug.apk.
> 
> ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY╞═════════════════════════════
> The following assertion was thrown building MyApp(dirty):
> textBaseline is required if you specify the crossAxisAlignment with
> CrossAxisAlignment.baseline

For me it clearly states that `textBaseline` must be provided if you use `CrossAxisAlignment.baseline`. Can you please elaborate how this message should be improved?
Thank you

**Comment by djlondon** [comment] 2021-03-18 13:20
@pedromassangocode I think the message is ok, actually. The stacktrace is unnecessarily long and a bit intimidating though. I guess it's just a case of removing the call to raise a bug.

**Comment by pedromassangocode** [comment] 2021-03-18 13:55
> The stacktrace is unnecessarily long and a bit intimidating though. I guess it's just a case of removing the call to raise a bug.

Actually it is necessary for people working in Flutter to track issues, You can just ignore them and focus on the first lines which explains the problem.

I'm closing this as this seems to be working as intended.
Thank you

**Closed by pedromassangocode** 2021-03-18 13:55 UTC
Labels: in triage
