### ISSUE TITLE
[in_app_purchase]: Some consumables are not (automatically) consumed

### ISSUE THREAD

**Issue by RUSSCITY** [flutter/flutter#102973] opened 2022-05-03 12:56 UTC
Hello, my customers reporting the problem, that they cannot buy some items twice as Google Play says it is already owned. All the items are consumable, but on the Google side they are not consumed. 

Looking in source code I see that all consumables should be consumed automatically:
![image](https://user-images.githubusercontent.com/9445518/166453894-245a5896-a440-483f-a143-df35d08c0e91.png)

The problem is that sometimes this not happens (very rare, 2-5% of all payments). I cannot find any possibility to reproduce the problem on my side. This is what Google Play API returns for such a purchase:
![image](https://user-images.githubusercontent.com/9445518/166455024-b4f34bd9-6d46-4ff2-bc29-d04db861d9a5.png)

I have tried to acknowledge purchase on the server side(in Java):
```
PlayStorePublisherManager.getService().purchases().products()
                    .acknowledge(playStoreConsumablePaymentEntry.getPackageName(), playStoreConsumablePaymentEntry.getProductId(), playStoreConsumablePaymentEntry.getPurchaseToken(), new ProductPurchasesAcknowledgeRequest());
```
But this doesn't help, it doesn't trigger consume on the purchase, maybe because the item's state `acknowledgementState` is already acknowledged. 

So, it seems to be a bug in the `in_app_purchase` package.

My specs: 
pubspec.yaml:
```
  in_app_purchase: ^3.0.2
```

flutter doctor:
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.10.5, on Microsoft Windows [Version 10.0.19043.1645], locale de-DE)
 Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.5)
[√] Android Studio (version 2021.1)
[√] IntelliJ IDEA Ultimate Edition (version 2021.2)
[√] VS Code (version 1.62.3)
[√] Connected device (5 available)
[√] HTTP Host Availability

• No issues found!
```

Maybe there is some workaround to trigger `consumePurchase` manually? Please help 🙏

**Comment by RUSSCITY** [comment] 2022-05-03 13:47
ok, I think I have found how we can trigger consume purchase manually:
```
InAppPurchaseAndroidPlatformAddition androidPlatformAddition =
                InAppPurchase.instance.getPlatformAddition<
                    InAppPurchaseAndroidPlatformAddition>();
            androidPlatformAddition.consumePurchase(purchaseDetails);
```

Maybe we can call it when get stream on restore purchases:
```
      InAppPurchase.instance.restorePurchases();
```

But sadly I cannot test it on the fly. I have to publish an update to Play Store and ask my customer to try to restore purchases... this is a bit painful... Anyway the problem that not all purchases are marked as consumed still be there.

**Comment by darshankawar** [comment] 2022-05-04 07:36
@RUSSCITY 
Thanks for the report.

> InAppPurchase.instance.restorePurchases();

On Android, `InAppPurchase.instance.restorePurchases()` would return purchased but not consumed products in `InAppPurchase.instance.purchaseStream.listen` method with `purchaseDetailsList`.

From what I understand from your issue description is that, purchases that are not marked as consumed, are still available and not automatically consumed , wherein, they should all be consumed ?

Is there a way for you to replicate this issue locally or provide a minimal code sample ?

**Comment by RUSSCITY** [comment] 2022-05-04 13:22
@darshankawar 
Right, `InAppPurchase.instance.restorePurchases()` returns purchased but not consumed products. Sadly I can see it only on my server logs, where my customer triggers action to restore purchases. I cannot reproduce this issue on my local devices. 

In production this happens very rarely and I didn't found any connection between these customers as to what might be causing this issue. Therefore sadly I cannot provide any code, which could help to find/solve the problem.

When the new version of the app will be released, I will ask my customers, who has this problems, to try to restore purchases again. As I have described in my comment above, I will trigger consume purchase manually in `InAppPurchase.instance.purchaseStream.listen`. I will write back as soon as I have some feedback of them.

**Comment by nezoat** [comment] 2022-05-06 15:22
I am having this same problem.  A small percentage of users are reporting they are unable to purchase a product more than once, receiving "You already own this item" message and no option to buy it again, only an "OK" button to dismiss the message (On Android).   I also have this same problem for Apple users, also only occasionally.    I am unable to reproduce the issue.

**Closed** 2022-05-25 14:11 UTC
Labels: waiting for customer response, in triage
