### ISSUE TITLE
[Text] Interrupted underline decoration with CJKs characters and different baseline fonts

### ISSUE THREAD

**Issue by AlexV525** [flutter/flutter#105886] opened 2022-06-13 09:52 UTC
## Case 1

1. Use https://dartpad.dev/?id=e75b493dae1287757c5e1d77a0dc73f1.
2. Update texts to:
```dart
Text(
  '测试：$_counter times',
  style: Theme.of(context).textTheme.headline4?.copyWith(
    decoration: TextDecoration.underline,
  ),
)
```
3. <img width="308" alt="image" src="https://user-images.githubusercontent.com/15884415/173322482-b21b7982-1674-49bc-b505-e0a361829c78.png">

## Case 2

1. Add the [PT-Sans.ttf](https://github.com/flutter/flutter/files/8889947/PT-Sans.ttf.zip) to the app.
2. Use the text as:
```dart
Text(
  '测试 different characters 123。',
  style: TextStyle(
    fontFamily: 'PT Sans',
    decoration: TextDecoration.underline,
  ),
)
```
3. <img width="490" alt="image" src="https://user-images.githubusercontent.com/15884415/173328027-3bf14ec5-e325-4509-a5f5-51c65ee4d9fe.png">

```
[✓] Flutter (Channel stable, 3.0.2, on macOS 12.4 21F79 darwin-x64, locale zh-Hans-CN)
    • Flutter version 3.0.2 at /Users/alex/Documents/flutter-stable
    • Upstream repository https://github.com/flutter/flutter
    • Framework revision cd41fdd495 (5 days ago), 2022-06-08 09:52:13 -0700
    • Engine revision f15f824b57
    • Dart version 2.17.3
    • DevTools version 2.12.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] IntelliJ IDEA Ultimate Edition (version 2022.1.1)
    • IntelliJ at /Users/alex/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 68.1.4
    • Dart plugin version 221.5591.58

[✓] Connected device (4 available)
    • ONEPLUS A6010 (mobile) • f8e67ce3                  • android-arm64  • Android 11 (API 30)
    • Chrome (web)           • chrome                    • web-javascript • Google Chrome 102.0.5005.61

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

**Comment by danagbemava-nc** [comment] 2022-06-13 14:23
Issue is reproducible on stable and master. 
When I used the default fonts, it only reproduced for me on android and web-canvaskit, but when I used the PT-Sans font, it reproduced for me on all the platforms i tested aside the html renderer. 

Leaving this for further investigation. 

<details>
<summary>screenshots</summary>

### Using default fonts

| macOS | canvaskit | html | android | iOS | 
| -- | -- | -- | -- | -- |
| <img alt="Screenshot 2022-06-13 at 13 20 01" src="https://user-images.githubusercontent.com/88313112/173373184-df1c418b-fc15-4a06-a4b0-61f3264f8d77.png"> | <img  alt="Screenshot 2022-06-13 at 13 26 47" src="https://user-images.githubusercontent.com/88313112/173373224-edab3598-f89e-4324-940e-999eee26c6a5.png"> | <img alt="Screenshot 2022-06-13 at 13 28 54" src="https://user-images.githubusercontent.com/88313112/173373242-4bd9be80-8247-4ffb-939e-5e5816c774b9.png">| <img src="https://user-images.githubusercontent.com/88313112/173373260-f4734595-328d-44e8-a336-844b70ec023b.png" /> | <img src="https://user-images.githubusercontent.com/88313112/173373277-82a035b1-5eb6-4727-b75e-14df0b69459e.png" /> |


### Using PT-Sans font

| macOS | canvaskit | html | android | iOS | 
| -- | -- | -- | -- | -- |
| <img alt="Screenshot 2022-06-13 at 13 53 53" src="https://user-images.githubusercontent.com/88313112/173373250-775fab20-3358-46c7-a746-272c11ffac16.png">  | <img  alt="Screenshot 2022-06-13 at 13 56 51" src="https://user-images.githubusercontent.com/88313112/173373258-59f717d2-027c-4fe1-a682-b028874da3eb.png">| <img alt="Screenshot 2022-06-13 at 13 56 03" src="https://user-images.githubusercontent.com/88313112/173373254-0c5b68dc-0652-432d-9d71-65e62f1fe3b8.png"> |  <img src="https://user-images.githubusercontent.com/88313112/173373272-7a97374d-2d72-4639-a211-ce3f09c2f230.png" /> | <img src="https://user-images.githubusercontent.com/88313112/173373282-f573ae99-c05e-4529-a9aa-3e8c56bc309f.png" /> |

</details>


<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  final String title;

  const MyHomePage({
    Key? key,
    required this.title,
  }) : super(key: key);

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            const Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '测试：$_counter times',
              style: Theme.of(context).textTheme.headline4?.copyWith(
                    decoration: TextDecoration.underline,
                  ),
            ),
            const Text(
              '测试 different characters 123。',
              style: TextStyle(
                fontFamily: 'PT Sans',
                decoration: TextDecoration.underline,
              ),
            )
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}
```
</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.0.2, on macOS 12.3.1 21E258 darwin-arm, locale en-GB)
    • Flutter version 3.0.2 at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cd41fdd495 (5 days ago), 2022-06-08 09:52:13 -0700
    • Engine revision f15f824b57
    • Dart version 2.17.3
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.68.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.42.0

[✓] Connected device (4 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554                        • android-arm64  • Android 12 (API 31) (emulator)
    • iPhone 13 (mobile)          • DBB48503-41CE-4969-9043-3261726E438A • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-4 (simulator)
    • macOS (desktop)             • macos                                • darwin-arm64   • macOS 12.3.1 21E258 darwin-arm
    • Chrome (web)                • chrome                               • web-javascript • Google Chrome 102.0.5005.61
    ! Error: Nexus is not connected. Xcode will continue when Nexus is connected. (code -13)

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

```
[✓] Flutter (Channel master, 3.1.0-0.0.pre.1237, on macOS 12.3.1 21E258 darwin-arm, locale en-GB)
    • Flutter version 3.1.0-0.0.pre.1237 at /Users/nexus/dev/sdks/flutters
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6062e40510 (5 hours ago), 2022-06-12 23:53:08 -0400
    • Engine revision f80294b57e
    • Dart version 2.18.0 (build 2.18.0-180.0.dev)
    • DevTools version 2.14.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.68.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.42.0

[✓] Connected device (4 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554                        • android-arm64  • Android 12 (API 31) (emulator)
    • iPhone 13 (mobile)          • DBB48503-41CE-4969-9043-3261726E438A • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-4 (simulator)
    • macOS (desktop)             • macos                                • darwin-arm64   • macOS 12.3.1 21E258 darwin-arm
    • Chrome (web)                • chrome                               • web-javascript • Google Chrome 102.0.5005.61
    ! Error: Nexus is not connected. Xcode will continue when Nexus is connected. (code -13)

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by AlexV525** [comment] 2022-07-15 15:30
Related to #42833, #99730.

**Comment by LongCatIsLooong** [comment] 2024-05-29 00:57
Duplicate of https://github.com/flutter/flutter/issues/42833

**Closed by LongCatIsLooong** 2024-05-29 00:57 UTC
Labels: engine, a: typography, has reproducible steps, P2, found in release: 3.0, found in release: 3.1, team-engine, triaged-engine
