### ISSUE TITLE
Flutter Gallery recipe browser transition jank

### ISSUE THREAD

**Issue by ScottPierce** [flutter/flutter#6920] opened 2016-11-18 04:21 UTC
## Steps to Reproduce
1. Run Flutter Gallery in release mode.
`flutter run --release`

2. Open "Pesto - Simple recipe browser"

3. Observe dropped frames during the transition.

Below is the performance overlay from my Nexus 5X. It only lags the first load. After the first load, it's much faster.

![pesto](https://cloud.githubusercontent.com/assets/871169/20418530/42856cec-ad1c-11e6-86a8-7fb67aeac98b.png)

```
flutter doctor
[✓] Flutter (on Mac OS, channel master)
    • Flutter at /Volumes/MacintoshHD/Users/spierce7/frameworks/flutter
    • Framework revision 05fdc2910b (3 hours ago), 2016-11-17 17:50:47
    • Engine revision cea5ed2b9b
    • Tools Dart version 1.21.0-dev.6.0

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.0)
    • Android SDK at /Volumes/MacintoshHD/Users/spierce7/Android/sdk
    • Platform android-25, build-tools 25.0.0
    • ANDROID_HOME = /Volumes/MacintoshHD/Users/spierce7/Android/sdk
    • Java(TM) SE Runtime Environment (build 1.8.0_77-b03)

[-] iOS toolchain - develop for iOS devices
    x XCode not installed; this is necessary for iOS development.
      Download at https://developer.apple.com/xcode/download/.
    x ideviceinstaller not available; this is used to discover connected iOS devices.
      Install via 'brew install ideviceinstaller'.
    x ios-deploy not available; this is used to deploy to connected iOS devices.
      Install via 'brew install ios-deploy'.

[x] Flutter IDE Support (No supported IDEs installed)
    • IntelliJ - https://www.jetbrains.com/idea/
```

**Comment by eseidelGoogle** [comment] 2016-11-18 16:37
Possibly helped by @chinmaygarde's in progress raster caching fixes.

**Comment by sethladd** [comment] 2016-11-18 16:51
Thanks for the report! Probably related/same as https://github.com/flutter/flutter/issues/4991 and https://github.com/flutter/flutter/issues/5045 and https://github.com/flutter/flutter/issues/5626

Many of our loads/transitions miss frames on the first load. Then, they get faster and sustain their performance.

**Comment by ScottPierce** [comment] 2016-12-19 17:16
@sethladd Why is that it lags the first load? I was trying to track down the cause in observatory with out much luck.

Is it classes / files being loaded? Images being loaded into memory? I'm trying to understand the cause to understand if this is solvable. My Nexus5X dropped to 3 fps yesterday on an initial pesto transition.

**Comment by Hixie** [comment] 2016-12-28 19:24
@abarth likes to fix performance problems like this...

The chart suggests there's two problems, the initial build+layout is taking too long and then the first few frames are too expensive on the GPU side. Not clear why either of those would be better the second time though.

**Comment by ScottPierce** [comment] 2017-01-03 23:48
To be clear, this isn't specific to this screen. I find that on complex screens created with flutter, their opening animations tend to visibly lag on the first open. It's just easy to point this out in your sample app with Pesto, Shrine, and even Contact Profile (to a much smaller degree). After opening the screen a single time, the second or third screen open is drastically faster.

Again, I'm seeing this on my Nexus 5X.

**Comment by sethladd** [comment] 2017-01-03 23:56
> Why does it lag on the first load consistently?

Sorry, I don't know. But we'll take a look at it. I can confirm this behavior on a variety of Android devices.

**Comment by ScottPierce** [comment] 2017-01-06 07:33
As per @abarth 's request, here are some screen shots of the cpu profile:

First load (slow):
<img width="676" alt="screen shot 2017-01-06 at 2 12 51 am" src="https://cloud.githubusercontent.com/assets/871169/21710735/846e675e-d3b8-11e6-858c-adc199be7e86.png">


Second load (faster):
<img width="637" alt="screen shot 2017-01-06 at 2 15 33 am" src="https://cloud.githubusercontent.com/assets/871169/21710739/8bbcfc50-d3b8-11e6-8da7-f977449f6a83.png">

**Comment by ScottPierce** [comment] 2017-01-06 07:54
Also, with a stubbed out `_resolveImage()`:
<img width="655" alt="screen shot 2017-01-06 at 2 49 39 am" src="https://cloud.githubusercontent.com/assets/871169/21711187/6e904f58-d3bb-11e6-8297-b6e4f3dbe08e.png">

**Comment by Hixie** [comment] 2017-02-27 22:22
What's this like now? The scrolling refactor may have helped.

**Comment by ScottPierce** [comment] 2017-02-27 23:43
@Hixie is the scrolling refactor on the latest alpha, or is it only on master?

**Comment by ScottPierce** [comment] 2017-02-28 04:19
Just tried it on master on my Nexus 5X. Still not good.

![screenshot_20170227-231625](https://cloud.githubusercontent.com/assets/871169/23391417/1f4f61ac-fd43-11e6-8f64-c975526a9a54.png)

**Comment by ScottPierce** [comment] 2017-03-01 00:38
Yes. I built it off of the master branch.

**Comment by ScottPierce** [comment] 2017-03-30 18:38
@sethladd I wish this hadn't been de-prioritized. I've been waiting on this bug to get an understanding of whether or not this lag is just inherent to flutter, or if this can be resolved. The moment I talk or show flutter to any other dev, the first question they have is performance, and the moment they see the lag on the first time any screen opens, they dismiss it.

**Comment by sethladd** [comment] 2017-03-30 20:00
I totally hear you, apologies for the delay here. This issue (and others like it) will come back to the top, but we're in the middle of a big push to enable a few features for our early adopters. Once we get them unblocked, we can take a fresh look at performance again.

FWIW the thought process was: "first, ensure our early adopters _can_ build the UI mocks they were given by their designers and clients. Then, once they are able to make the screens and show progress, we make their screens and apps go faster."

Thanks for your patience here. We appreciate your support and thanks checking in.

**Comment by ScottPierce** [comment] 2017-09-23 21:12
I've confirmed this issue is still reproducible on my Nexus 5X, however it does seem to have gotten better. I've noticed the same degree of lag on some other screens as well.

**Comment by Hixie** [comment] 2017-12-19 03:26
@cbracken You're looking at perf now right?

**Comment by cbracken** [comment] 2017-12-19 17:32
Out until Jan 2, but yes I am.

**Comment by cbracken** [comment] 2018-01-31 00:13
Marking as dupe of #5363, which I'll generalise to be the catch-all Gallery bug associated with underlying root cause #813.

**Closed by cbracken** 2018-01-31 00:13 UTC
Labels: performance, prod: framework, team: gallery, ▣ platform-android
