### ISSUE TITLE
[url_launcher] Please add warning about NOT using async for iOS on web in documentation

### ISSUE THREAD

**Issue by jakusb** [flutter/flutter#130680] opened 2023-07-16 14:06 UTC
See https://github.com/flutter/flutter/issues/75227
Solution was to call launchUrl outside of any async context.
I spent many hours debugging to finally get to this solution. It should be a clear warning/statement in the documentation to prevent other users having to loose many hours including frustration. ;)

Proposal in web section:
Beware: iOS Safari will not open the url if launchUrl is called from an async context! Make sure to call launchUrl outside of async context.

**Comment by stuartmorgan** [comment] 2023-07-16 16:10
Closing as a duplicate of https://github.com/flutter/flutter/issues/78524

**Closed by stuartmorgan** 2023-07-16 16:10 UTC

**Comment by jakusb** [comment] 2023-07-16 17:10
Come on @stuartmorgan: this is not a duplicate. This is an explicit request to update the documentation. Please consider this as many people get trapped in this rabbit hole. 🙏🏻🙏🏻

**Comment by stuartmorgan** [comment] 2023-07-16 17:18
Please read https://github.com/flutter/flutter/issues/78524#issuecomment-807212100, https://github.com/flutter/flutter/issues/78524#issuecomment-1637129340, and the current title of that issue.

**Comment by jakusb** [comment] 2023-07-16 20:19
Many thanks. I was mislead by the ‘closed this as not planned’ status. 😉
