### ISSUE TITLE
SearchAnchor text selection or copy / paste not possible

### ISSUE THREAD

**Issue by PerLycke** [flutter/flutter#133122] opened 2023-08-23 09:16 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Run code sample
2. Write some text in search text field and try to select it. Or long press the text field to show the copy / paste menu

### Expected results

User can select entered text, and user can copy paste into the text field.

### Actual results

User cannot select text or copy paste text.

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(
          seedColor: Colors.deepPurple,
        ),
        useMaterial3: true,
      ),
      home: Scaffold(
        body: SafeArea(
          child: SearchAnchor.bar(
            suggestionsBuilder: (_, __) => [],
          ),
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.13.0, on macOS 13.4.1 22F770820d darwin-arm64, locale en-GB)
    • Flutter version 3.13.0 on channel stable at /Users/per/dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision efbf63d9c6 (7 days ago), 2023-08-15 21:05:06 -0500
    • Engine revision 1ac611c64e
    • Dart version 3.1.0
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/per/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.81.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.70.0

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 13 (API 33) (emulator)
    • macOS (desktop)             • macos         • darwin-arm64   • macOS 13.4.1 22F770820d darwin-arm64
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 116.0.5845.96

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by PerLycke** [comment] 2023-08-23 09:20
Am I missing something obvious here or is the search anchor really lacking this very very basic feature where the user can select text, or copy and paste text into the search bar text field?

**Comment by PerLycke** [comment] 2023-08-23 11:02
It's due to the IgnorePointer widget at https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/search_anchor.dart#L1271C36-L1271C36

I guess this was added due to the Flutter team wanting an InkWell widget above the text field in order to create feedback on search bar interaction. However, the drawback is significant as no text field interaction is now possible.

If things are to be kept the way they are, I suggest controlling the `ignoring` parameter of the IgnorePointer widget and disable ignoring if the SearchBar is focused. One could wrap the IgnorePointer in a ValueListenableBuilder and listen to the state with the already existing _internalStatesController.

```dart
ValueListenableBuilder(
    valueListenable: _internalStatesController,
    builder: (_, state, __) {
      return IgnorePointer(
        ignoring: !state.contains(MaterialState.focused),
        child: Padding(
          padding: effectivePadding,
          child: TextField(
            focusNode: _focusNode,
            onChanged: widget.onChanged,
            onSubmitted: widget.onSubmitted,
            controller: widget.controller,
            style: effectiveTextStyle,
            decoration: InputDecoration(
              hintText: widget.hintText,
            ).applyDefaults(InputDecorationTheme(
              hintStyle: effectiveHintStyle,

              // The configuration below is to make sure that the text field
              // in `SearchBar` will not be overridden by the overall `InputDecorationTheme`
              enabledBorder: InputBorder.none,
              border: InputBorder.none,
              focusedBorder: InputBorder.none,
              contentPadding: EdgeInsets.zero,
              // Setting `isDense` to true to allow the text field height to be
              // smaller than 48.0
              isDense: true,
            )),
          ),
        ),
      );
    })
```

**Comment by darshankawar** [comment] 2023-08-23 11:46
Thanks for the report @PerLycke 
As you correctly pointed out, it could be happening due to `ignorePointer` widget due to which the text can't be selected and hence no text selection toolbar appears. Can you check if [this](https://github.com/flutter/flutter/issues/131235) issue resembles your case which also [discusses](https://github.com/flutter/flutter/issues/131235#issuecomment-1654667927) about ignorepointer.  I think once the decision on usage of `ignorePointer` is implemented as part of that issue, the text selection tool bar would start appearing as well.

**Comment by PerLycke** [comment] 2023-08-23 14:27
It might reassemble it yes. And it is indeed the IgnorePointer that causes it. We had to copy the widget and make appropriate edits for text selection to work as users expected.

**Comment by Renzo-Olivares** [comment] 2023-08-23 18:09
Closing this as duplicate of #131235

**Closed by Renzo-Olivares** 2023-08-23 18:09 UTC
Labels: in triage
