### ISSUE TITLE
[Android]: `io.flutter.embedding.engine.FlutterJNI.nativeSurfaceChanged` log leading to ANR.

### ISSUE THREAD

**Issue by EArminjon** [flutter/flutter#98779] opened 2022-02-19 00:30 UTC
## Steps to Reproduce

1. Didn't know how to reproduce this issue, I've no crash on my tests devices...
2. I saw lot of crahslytics ANR since flutter >= 2.10 but I need these version to fix webview issues...
3. If some user got the same issue, please comment.

**Packages used :**

```yaml
 webview_flutter: 3.0.0
 google_mobile_ads: 1.0.1
 firebase_core: 1.12.0
 firebase_analytics: 9.1.0
 firebase_crashlytics: 2.5.0
```

**Expected results:** 
No crash on my dashboard <3

**Actual results:** 
Many crash

<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
main (native): tid=1 systid=22482
#00 pc 0x86b0c libc.so 
#01 pc 0x8a6f4 libc.so 
#02 pc 0xeac10 libc.so 
#03 pc 0x2efaa4 libflutter.so 
#04 pc 0x301f48 libflutter.so 
#05 pc 0x2ed454 libflutter.so 
       at io.flutter.embedding.engine.FlutterJNI.nativeSurfaceChanged(FlutterJNI.java)
       at io.flutter.embedding.engine.FlutterJNI.onSurfaceChanged(FlutterJNI.java)
       at io.flutter.embedding.engine.renderer.FlutterRenderer.surfaceChanged(FlutterRenderer.java)
       at io.flutter.embedding.android.FlutterSurfaceView.changeSurfaceSize(FlutterSurfaceView.java)
       at io.flutter.embedding.android.FlutterSurfaceView.access$300(FlutterSurfaceView.java)
       at io.flutter.embedding.android.FlutterSurfaceView$1.surfaceChanged(FlutterSurfaceView.java)
       at android.view.SurfaceView.updateSurface(SurfaceView.java:1277)
       at android.view.SurfaceView.setFrame(SurfaceView.java:601)
       at android.view.View.layout(View.java:23122)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
       at android.view.View.layout(View.java:23125)
       at android.view.ViewGroup.layout(ViewGroup.java:6460)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
       at android.view.View.layout(View.java:23125)
       at android.view.ViewGroup.layout(ViewGroup.java:6460)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
       at android.view.View.layout(View.java:23125)
       at android.view.ViewGroup.layout(ViewGroup.java:6460)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
       at com.android.internal.policy.DecorView.onLayout(DecorView.java:797)
       at android.view.View.layout(View.java:23125)
       at android.view.ViewGroup.layout(ViewGroup.java:6460)
       at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3626)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3085)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2075)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8522)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1077)
       at android.view.Choreographer.doCallbacks(Choreographer.java:897)
       at android.view.Choreographer.doFrame(Choreographer.java:826)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1062)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:233)
       at android.app.ActivityThread.main(ActivityThread.java:8052)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
```

```
```

```
[✓] Flutter (Channel stable, 2.10.1, on Microsoft Windows [version 10.0.19044.1526], locale fr-FR)
    • Flutter version 2.10.1 at C:\Users\*********\Documents\Softwares\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db747aa133 (9 days ago), 2022-02-09 13:57:35 -0600
    • Engine revision ab46186b24
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\*********\AppData\Local\Android\sdk
    • Platform android-32, build-tools 31.0.0
    • Java binary at:
      C:\Users\*********\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\211.7628.21.2111.8139111\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.0)
    • Visual Studio at D:\dev
    • Visual Studio Community 2019 version 16.9.31025.194
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 2021.1)
    • Android Studio at C:\Users\*********\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\211.7628.21.2111.8139111
    • Flutter plugin version 64.1.2
    • Dart plugin version 211.7798
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
```

</details>

![image](https://user-images.githubusercontent.com/37028599/154777869-9aeb7fc5-15ac-4188-8e60-7923e0de131d.png)
![image](https://user-images.githubusercontent.com/37028599/154777899-75036c41-a72d-4ee8-864a-4a73fb1dd48a.png)

**Comment by TheJulianJES** [comment] 2022-02-19 07:42
Did you test if you’re also experiencing this crash on 2.10.1 or 2.10.2?
Pretty sure this was one was fixed in 2.10.1

**Comment by EArminjon** [comment] 2022-02-19 09:01
Yes, experienced in  2.10.1, didn't try 2.10.2 (released today), i'm looking for patch note and test before deploy it...

**Comment by EArminjon** [comment] 2022-02-19 10:41
I think 2.10.2 will not fix that base on this changelog : https://github.com/flutter/flutter/compare/2.10.1...2.10.2

**Comment by kkoken** [comment] 2022-02-19 14:58
I have recently encountered with the same issue. It is causing lots of ANR

**Comment by sabifa** [comment] 2022-02-21 06:29
Experiencing the same issue

**Comment by darshankawar** [comment] 2022-02-21 08:12
@EArminjon 
Can you check your gradle dependency tree and confirm any of the dependency using `io.flutter:flutter_embedding` is using an outdated maven dependency containing the flutter lib ?
If this isn't the case, can you provide all crash logs in properly formatted text ? including the one you provided in the screenshot ?

**Comment by bhumkong** [comment] 2022-02-21 08:16
I also see the same error in Crashlytics after upgrade to Flutter 2.10.1
```
FlutterJNI.java
io.flutter.embedding.engine.FlutterJNI.nativeSurfaceChanged
```

**Comment by EArminjon** [comment] 2022-02-21 19:05
> @EArminjon Can you check your gradle dependency tree and confirm any of the dependency using `io.flutter:flutter_embedding` is using an outdated maven dependency containing the flutter lib ? If this isn't the case, can you provide all crash logs in properly formatted text ? including the one you provided in the screenshot ?


Hum, I will need some help because based on the following command : 
```
./gradlew build --scan
```

I got many, many, many dependencies which use io.flutter:flutter_embedding :

![image](https://user-images.githubusercontent.com/37028599/155012866-784bcbd9-2059-480e-88d4-f752852d8401.png)

**Comment by EArminjon** [comment] 2022-02-21 19:07
```
main (native): tid=1 systid=10392
#00 pc 0x4d5dc libc.so 
#01 pc 0x51dc4 libc.so 
#02 pc 0xb224c libc.so 
#03 pc 0x2efaa4 libflutter.so 
#04 pc 0x301f48 libflutter.so 
#05 pc 0x2ed454 libflutter.so 
       at io.flutter.embedding.engine.FlutterJNI.nativeSurfaceChanged(FlutterJNI.java)
       at io.flutter.embedding.engine.FlutterJNI.onSurfaceChanged(FlutterJNI.java)
       at io.flutter.embedding.engine.renderer.FlutterRenderer.surfaceChanged(FlutterRenderer.java)
       at io.flutter.embedding.android.FlutterSurfaceView.changeSurfaceSize(FlutterSurfaceView.java)
       at io.flutter.embedding.android.FlutterSurfaceView.access$300(FlutterSurfaceView.java)
       at io.flutter.embedding.android.FlutterSurfaceView$1.surfaceChanged(FlutterSurfaceView.java)
       at android.view.SurfaceView.updateSurface(SurfaceView.java:1362)
       at android.view.SurfaceView.setFrame(SurfaceView.java:675)
       at android.view.View.layout(View.java:24453)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
       at android.view.View.layout(View.java:24456)
       at android.view.ViewGroup.layout(ViewGroup.java:7412)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
       at android.view.View.layout(View.java:24456)
       at android.view.ViewGroup.layout(ViewGroup.java:7412)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
       at android.view.View.layout(View.java:24456)
       at android.view.ViewGroup.layout(ViewGroup.java:7412)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
       at com.android.internal.policy.DecorView.onLayout(DecorView.java:1290)
       at android.view.View.layout(View.java:24456)
       at android.view.ViewGroup.layout(ViewGroup.java:7412)
       at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:4505)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3927)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2833)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10335)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1063)
       at android.view.Choreographer.doCallbacks(Choreographer.java:845)
       at android.view.Choreographer.doFrame(Choreographer.java:780)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1048)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8633)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
       ```

**Comment by darshankawar** [comment] 2022-02-22 05:05
@EArminjon 
Is your app using native implementation (.e.g platform-views or add2app) ? Is there a way to find a pattern that leads to this crash ?

**Comment by EArminjon** [comment] 2022-02-22 05:37
> @EArminjon Is your app using native implementation (.e.g platform-views or add2app) ? Is there a way to find a pattern that leads to this crash ?

My apps didn't have Android native stuff for the moment (I didn't write kotlin). 
I didn't find yet by myself a way to reproduce the bug. I've 15 apps all have the issue....

**Comment by darshankawar** [comment] 2022-02-22 05:55
> My app use webview and Google ads interstitial.

I suspect if this has to do with `google_mobile_ads` plugin you are using. Please check this similar issue and see if it's related to your case: https://github.com/googleads/googleads-mobile-flutter/issues/499.

**Comment by EArminjon** [comment] 2022-02-22 08:36
> > My app use webview and Google ads interstitial.
> 
> I suspect if this has to do with `google_mobile_ads` plugin you are using. Please check this similar issue and see if it's related to your case: [googleads/googleads-mobile-flutter#499](https://github.com/googleads/googleads-mobile-flutter/issues/499).

Hum, I didn't use banner just interstitial. I tried many things around interstitial and background / foreground and I didn't achieve crash / weird logs.

I didn't know what to do :'(.

**Comment by alexislg2** [comment] 2022-02-22 10:07
I don't use the google_mobile_ads plugins and I still have tons of these crash since Flutter upgrade

**Comment by kkoken** [comment] 2022-02-22 10:10
In my app, I am using web view packages  ` webview_flutter: ^3.0.0` & `webview_cookie_manager: ^2.0.6`. I suspect that web view causing the problem.

**Comment by alexislg2** [comment] 2022-02-22 10:12
I don't use webview neither

**Comment by kkoken** [comment] 2022-02-22 10:31
> I don't use webview neither

What packages & configurations do you use? Please elaborate. I do not use this or that does not help.

**Comment by alexislg2** [comment] 2022-02-22 10:34
cupertino_icons: ^1.0.4
  google_fonts: ^2.3.1
  google_sign_in: ^5.2.3
  sign_button: ^2.0.2
  font_awesome_flutter: ^9.2.0
  cached_network_image: ^3.2.0
  http: ^0.13.4
  fluro: ^2.0.3
  timeago: ^3.2.2
  image_picker: ^0.8.4+7
  #flutter_facebook_auth: ^3.5.6
  equatable: ^2.0.3
  get_it: ^7.2.0
  flutter_bloc: ^8.0.1
  shared_preferences: ^2.0.13
  photo_view: ^0.13.0
  image_cropper: ^1.4.1
  intl: ^0.17.0
  flutter_secure_storage: ^5.0.2
  fluttertoast: ^8.0.8
  firebase_core: ^1.12.0
  firebase_messaging: ^11.2.6
  url_launcher: ^6.0.18
  flutter_local_notifications: ^9.2.0
  qr_flutter: ^4.0.0
  share_plus: ^3.0.4
  qr_code_scanner: ^0.7.0
  receive_sharing_intent: ^1.4.5
  flutter_facebook_auth: ^4.0.1
  sign_in_with_apple: ^3.3.0
  gallery_saver: ^2.3.2
  auto_size_text: ^3.0.0
  provider: ^6.0.1
  country_picker: ^2.0.11

**Comment by kkoken** [comment] 2022-02-22 10:39
> cupertino_icons: ^1.0.4 google_fonts: ^2.3.1 google_sign_in: ^5.2.3 sign_button: ^2.0.2 font_awesome_flutter: ^9.2.0 cached_network_image: ^3.2.0 http: ^0.13.4 fluro: ^2.0.3 timeago: ^3.2.2 image_picker: ^0.8.4+7 #flutter_facebook_auth: ^3.5.6 equatable: ^2.0.3 get_it: ^7.2.0 flutter_bloc: ^8.0.1 shared_preferences: ^2.0.13 photo_view: ^0.13.0 image_cropper: ^1.4.1 intl: ^0.17.0 flutter_secure_storage: ^5.0.2 fluttertoast: ^8.0.8 firebase_core: ^1.12.0 firebase_messaging: ^11.2.6 url_launcher: ^6.0.18 flutter_local_notifications: ^9.2.0 qr_flutter: ^4.0.0 share_plus: ^3.0.4 qr_code_scanner: ^0.7.0 receive_sharing_intent: ^1.4.5 flutter_facebook_auth: ^4.0.1 sign_in_with_apple: ^3.3.0 gallery_saver: ^2.3.2 auto_size_text: ^3.0.0 provider: ^6.0.1 country_picker: ^2.0.11

@EArminjon which packages are common in your case? As far as I can tell only package that concerns me right now `firebase` (with your gradlew findings)

**Comment by EArminjon** [comment] 2022-02-22 11:06
My dependencies : 

```yaml
  wonderpush_flutter: 2.1.8
  wonderpush_fcm_flutter: 1.0.5
  cached_network_image: 3.2.0
  http: 0.13.4
  intl: 0.17.0
  shared_preferences: 2.0.13
  cupertino_icons: 1.0.4
  just_audio: 0.9.20
  audio_session: 0.1.6+1
  audio_service: 0.18.3
  url_launcher: 6.0.20
  html: 0.15.0
  app_settings: 4.1.1
  flutter_local_notifications: 9.2.0
  volume_controller: 2.0.3
  webview_flutter: 3.0.0
  flutter_to_airplay: 2.0.2
  device_info_plus: 3.2.2
  google_mobile_ads: 1.0.1
  firebase_crashlytics: 2.5.0
  firebase_analytics: 9.1.0
  provider: 6.0.2
  share: 2.0.4
  flutter_cache_manager: 3.3.0
  flutter_bloc: 8.0.1
  rxdart: 0.27.3
  timezone: 0.8.0
  crypto: 3.0.1
  in_app_review: 2.0.4
  ```

**Comment by alexislg2** [comment] 2022-02-22 11:11
Let's hope it is not caused by crashlytics 😂

**Comment by yunnywu** [comment] 2022-02-22 12:26
happed when i upgrade to 2.10.0
when i switch my app between landscape  and portrait

**Comment by darshankawar** [comment] 2022-02-22 13:18
Based on the several reports on the same / similar error log being received, I am going ahead and labeling it for further insights from the team, as, there doesn't seem to be a concrete reproducible use case that triggers this error log.
Also, since the log seems to be coming from native Android, it may not be able to symbolicate since it doesn't seem to have Flutter frames in it.

/cc @blasten @jason-simmons

**Comment by hamberluo** [comment] 2022-02-22 13:37
> Based on the several reports on the same / similar error log being received, I am going ahead and labeling it for further insights from the team, as, there doesn't seem to be a concrete reproducible use case that triggers this error log. Also, since the log seems to be coming from native Android, it may not be able to symbolicate since it doesn't seem to have Flutter frames in it.
> 
> /cc @blasten @jason-simmons

I also meet the crash when android device orientation changes.

**Comment by chinmaygarde** [comment] 2022-02-22 22:30
Unfortunately, this doesn't seem to be an actionable issue as it has no reproducible or reduced test case. It doesn't seem isolated to a specific plugin nor is it tied to a commit range to check for regression. The only related line of work that comes to mind is https://github.com/flutter/engine/pull/31464 but even that is extremely speculative. cc @blasten for double checking on that. But I am inclined to close this this as un-actionable. Feel free to reopen if additional information is available.

**Comment by kaptnkoala** [comment] 2022-02-23 16:05
We also have a lot of ANRs showing up for Android devices in Crashlytics and Sentry. From the attached app events breadcrumbs, it seems that the ANR are happening directly at app start. Maybe it could be related that we are calling `SystemChrome.setPreferredOrientations([DeviceOrientation.portraitUp])`. If we are not able to identify the cause for the problem, we will probably have to roll back to Flutter 2.8.1.

**Comment by kkoken** [comment] 2022-02-23 16:11
> setPreferredOrientations

We have precisely set the same thing; it may be related.

**Comment by EArminjon** [comment] 2022-02-23 19:06
I've set the same thing on my apps.

**Comment by EArminjon** [comment] 2022-02-23 19:06
> > setPreferredOrientations
> 
> We have precisely set the same thing; it may be related.
I've set the same thing on my apps

**Comment by tigloo** [comment] 2022-02-24 08:12
We were also using `SystemChrome.setPreferredOrientations()`, after removing that call, the crash disappeared.

The crash occurred for us only after resuming the app from standby and only on a Xiaomi Mi 11 Lite. Couldn't reproduce it on a Google Pixel 6.

**Comment by tigloo** [comment] 2022-02-24 10:01
Here is a minimal test case that exhibits the crash on a Xiaomi Mi 11 lite:

https://github.com/evoleen/flutter_crash

It's a blank Flutter project, created with Flutter 2.10.2. The only change is to use a WidgetBindingObserver and lock the screen orientation to portrait on Android. I'm not sure which of these is mandatory to trigger the crash as we only have limited access to a test device, but this should be a minimal test case.

**Comment by EArminjon** [comment] 2022-02-25 09:34
Note that : this issue is happening only on Android 11 et 12 for the moment.

**Comment by kolotum** [comment] 2022-02-25 09:43
> Note that : this issue is happening only on Android 11 et 12 for the moment.

In Google Play Console we can see this ANR on Android 9, 10, 11 and 12.

**Comment by whiplashoo** [comment] 2022-02-27 11:31
Seeing the exact same ANR issues with **Flutter 2.10.0 and Android 11 devices**.

Google Play dashboard:

<img width="1715" alt="Screenshot 2022-02-27 at 1 11 26 PM" src="https://user-images.githubusercontent.com/9117427/155880065-3441779c-327f-45b0-a697-09a7b2a61575.png">

Firebase Crashlytics:

<img width="1429" alt="Screenshot 2022-02-27 at 1 12 10 PM" src="https://user-images.githubusercontent.com/9117427/155880082-dedf1f6a-5fb9-4c7c-a688-bb7dbba9aaf3.png">

I also have a WidgetsBinding.instance.addPostFrameCallback that checks for device's orientation when a screen is loaded, if that matters at all. I have not yet been able to reproduce this issue on an emulator.

**Comment by Vichet97** [comment] 2022-02-27 14:52
Is there any solution now ? Can't we use others beside that SystemChrome ?

**Comment by darshankawar** [comment] 2022-02-28 05:00
Thanks for everyone's feedback, patience on this and also for sharing reproducible use case. I am reopening this issue and will investigate further.

**Comment by chinmaygarde** [comment] 2022-02-28 18:49
This is fixed in https://github.com/flutter/flutter/issues/98973 and is being CPed.

**Closed by chinmaygarde** 2022-02-28 18:49 UTC
Labels: severe: crash, platform-android, engine, a: production

**Comment by EArminjon** [comment] 2022-03-01 07:05
When 2.10.3 will be deployed ? @darshankawar

**Comment by kkoken** [comment] 2022-03-14 08:01
@darshankawar @chinmaygarde  any news on the update?

**Comment by tigloo** [comment] 2022-03-14 08:40
Flutter 2.10.3 is out, we switched about 10 days ago and the issue seems to be resolved.

**Comment by kkoken** [comment] 2022-03-14 08:49
@tigloo thank you for your response. @EArminjon can you also confirm?
