### ISSUE TITLE
Flutter doesn't work after installation

### ISSUE THREAD

**Issue by Nsoer** [flutter/flutter#84177] opened 2021-06-08 07:56 UTC
Windows 10

```console
PS C:\windows\system32> flutter --version
Flutter 2.2.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 02c026b03c (12 days ago) • 2021-05-27 12:24:44 -0700
Engine • revision 0fdb562ac8
Tools • Dart 2.13.1
```

```
PS C:\windows\system32> flutter doctor -v
Error on line 11, column 3 of pubspec.yaml: Invalid description in the "flutter_tools" pubspec on the "archive" dependency: Scheme not starting with alphabetic character
   ╷
11 │   archive: 3.1.2
   │   ^^^^^^^
   ╵
Running "flutter pub get" in flutter_tools...
pub get failed (65;    ╵)

#0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
#1      _DefaultPub.batch (package:flutter_tools/src/dart/pub.dart:323:7)
<asynchronous suspension>
#2      _DefaultPub.get (package:flutter_tools/src/dart/pub.dart:223:7)
<asynchronous suspension>
#3      PubDependencies.update (package:flutter_tools/src/flutter_cache.dart:121:5)
<asynchronous suspension>
#4      Cache.updateAll (package:flutter_tools/src/cache.dart:546:9)
<asynchronous suspension>
#5      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1143:7)
<asynchronous suspension>
#6      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1043:27)
<asynchronous suspension>
#7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#8      CommandRunner.runCommand (package:args/command_runner.dart:196:13)
<asynchronous suspension>
#9      FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#11     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:232:5)
<asynchronous suspension>
#12     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#14     main (package:flutter_tools/executable.dart:91:3)
<asynchronous suspension>
```

**Comment by TahaTesser** [comment] 2021-06-08 11:01
Hi @Nsoer 
Make sure your Flutter SDK isn't modified after installation and also provide Flutter SDK location

**Comment by Nsoer** [comment] 2021-06-09 00:13
Hi @TahaTesser

> Make sure your Flutter SDK isn't modified after installation and also provide Flutter SDK location

Flutter installed both from GitHub and flutter.dev. Immediately after installing flutter doctor gives an error. Location Flutter SDK specified.

**Comment by TahaTesser** [comment] 2021-06-09 08:51
Hi @Nsoer 

> Location Flutter SDK specified.


`PS C:\windows\system32>` is. not a valid location,  if that's where you've installed your Flutter SDK. Make sure you've Flutter SDK under `c:/flutter` or better `c:/users/your_user/flutter`

Make sure your antivirus or firewall isn't interfering, whitelist Flutter and its directories.

I just tried a new installation on Windows, no such error when running `flutter doctor -v`. Delete the file and download it again be sure the setup is damaged or modified.

**Comment by Nsoer** [comment] 2021-06-09 23:49
Hi @TahaTesser

Flutter is installed in `c:\flutter`, registered in `PATH`, antivirus and firewall are disabled. I installed it many times, downloaded the files from flutter.dev and from GitHub.
I don't understand why `flutter doctor` is giving an error in `pubspec.yaml` file, because I am not creating a project. And where is the `pubspec.yaml` that flutter swears at.

**Comment by TahaTesser** [comment] 2021-06-10 07:29
Hi @Nsoer 
It is not your project's but `flutter_tools` yaml [source](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/pubspec.yaml)
Thanks for the update, I'm unable to reproduce the issue

cc: @jonahwilliams 
What could be messing with this pubspec.yaml from tools

> Error on line 11, column 3 of pubspec.yaml: Invalid description in the "flutter_tools" pubspec on the "archive" dependency: Scheme not starting with alphabetic character
>    ╷
> 11 │   archive: 3.1.2

**Comment by KaJunChan** [comment] 2021-07-06 03:29
I got the same problem. I can't run my project anymore.Plz, help!

**Comment by Debakripa** [comment] 2023-04-13 04:52
@Nsoer I recommend installing the stable Flutter SDK from flutter.dev and uninstalling the GitHub version. Because the GitHub version may be unstable due to being a Beta version.

**Comment by christopherfujino** [comment] 2023-08-02 22:09
@KaJunChan & @Nsoer I'm sorry it took us so long to look at this issue. Can either of you share the entire contents of the file that pub failed to parse? The only way I can think of that this happened was that somehow the file got corrupted during download or after that. If pub was not able to parse the checked in version of this file, every flutter customer would be broken.

**Closed** 2023-08-23 23:08 UTC
Labels: c: crash, waiting for customer response, tool, t: flutter doctor, a: first hour, P3, team-tool, triaged-tool
