### ISSUE TITLE
bottom sheet in scrolling list demo difficult to dismiss

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#8276] opened 2017-02-18 05:43 UTC
It should be possible to pull down from the top of the persistent bottom sheet to make it disappear, but it seems to have a very small hitbox to make that happen?

![hard_dismiss mov](https://cloud.githubusercontent.com/assets/11857803/23090740/1c87b528-f55a-11e6-9f78-dfec46c46f26.gif)

**Comment by abarth** [comment] 2017-02-18 06:06
Where are you starting your drag in this example?

**Comment by eseidelGoogle** [comment] 2017-02-19 04:08
I was attempting to start it on the divider line.  However playing with this kind of control in other Google apps on iOS, I should be able to start it in the sheet, however that doesn't work for this sheet at all, which presumably is why I tried the divider line (which does work, but is hard to hit).

**Comment by abarth** [comment] 2017-02-19 04:13
This is another duplicate of the "scrollable when overflowing" bug.  There's also some scroll-chaining stuff missing here, but the regression is that.

**Closed** 2017-02-22 00:54 UTC
Labels: customer: gallery
