### ISSUE TITLE
"Lexical or Preprocessor Issue (Xcode): Include of non-modular header inside framework module" using firebase libraries in IOS

### ISSUE THREAD

**Issue by dk-a-dev** [flutter/flutter#154783] opened 2024-09-07 23:54 UTC
### Steps to reproduce

1. `flutter pub add firebase_core` or importing any firebase package
2. flutter run -v

### results

![image](https://github.com/user-attachments/assets/2c2b949f-77bd-4836-8aff-86ff5d9ed377)

### Code sample

Here is my Podfile!!!
```
platform :ios, '13.0'

ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end

```

### Logs

I have tried all the solutions most of the solutions available on Stack-Overflow
which involves
- cd ios
- flutter clean 
- delete pod folder and Podfile.lock
- followed by flutter pub get
- pod install --repo-update

I tried changing stuff in Podfile but nothing worked
<img width="602" alt="Screenshot 2024-09-08 at 05 26 24" src="https://github.com/user-attachments/assets/46add0e0-e45d-4f2e-a2cc-59f36d54e375">

**Comment by huycozy** [comment] 2024-09-09 08:48
Hi @dk-a-dev 
I can't reproduce this issue on my end. Can you provide the entire output of `flutter run -v`? (The output may be too large to be uploaded to GitHub, you may upload it as a txt file or use online tools like https://pastebin.com/ to share it.)

Looks like you are using a beta version of XCode 16.0, please provide the output of `flutter doctor -v` that has full details of XCode build version with iOS version as well. Thanks!

I found a flutterfire issue https://github.com/firebase/flutterfire/issues/12993 that you can check https://github.com/firebase/flutterfire/issues/12993#issuecomment-2188776541 to see if it can work around this or not.

_Please provide the information (error output, flutter doctor) in text format instead of a screenshot for better readability and investigation, see [avoid posting screenshots of text](https://github.com/flutter/flutter/wiki/Issue-hygiene#avoid-posting-screenshots-of-text)._

/cc @jmagman

**Comment by dk-a-dev** [comment] 2024-09-09 13:53
@huycozy 
Thanks for your quick reponse [firebase/flutterfire#12993 (comment)](https://github.com/firebase/flutterfire/issues/12993#issuecomment-2188776541) solved the problem 🙏🏻

Feel free to close the Issue

Sorry for bothering

**Comment by huycozy** [comment] 2024-09-10 03:24
Glad to know it works for you. Closing this as solved.

**Closed by huycozy** 2024-09-10 03:24 UTC
Labels: in triage
