### ISSUE TITLE
Flutter VideoPlayer in video_player ^2.4.2 is not stretched in width to parent widget. Showing empty lines from L&R

### ISSUE THREAD

**Issue by DimaopLinkin** [flutter/flutter#105759] opened 2022-06-10 05:36 UTC
Hello!
I have some problem using VideoPlayer.

## Steps to Reproduce
If I try to play 1080x1920 video(ratio 0,5625) my player showing empty space around the video from left and right (portrait orientation, landscape is not tested). If I wrap it with colored container without any size properties it looks like player adds some padding.

To record these videos I used camera ^0.9.7+1 plugin or image_picker ^0.8.5+3 to pick them from gallery - same result.
Videos recorded using ResolutionPreset.veryHigh (1080x1920 ratio 0,5625) or ResolutionPreset.ultraHigh (same on my testing phone).

If I try to use lower ResolutionPreset to REC video, it starts to working great.
ResolutionPreset.low           (240x320 ratio 0,75) OK
ResolutionPreset.medium   (480x640 ratio 0,75) OK
ResolutionPreset.high         (720x1280 ratio 0,5625) OK
ResolutionPreset.veryHigh (1080x1920 ratio 0,5625) BUG
ResolutionPreset.ultraHigh ----//---- same on testing device

On TCL T766H bug. Screen 720x1600 (Native player playing veryHigh video without any problems)
On Galaxy A50 everything is OK. Screen 1080x2340
On iPhone 7 everything is OK. Screen 750x1334

<details>
<summary>Code sample</summary>
There's small sample to catch this bug

```dart
import 'dart:io';

import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';
import 'package:video_player/video_player.dart';

void main() {
  runApp(const PlayerWidget());
}

class PlayerWidget extends StatefulWidget {
  const PlayerWidget({Key? key}) : super(key: key);

  @override
  State<PlayerWidget> createState() => _PlayerWidgetState();
}

class _PlayerWidgetState extends State<PlayerWidget> {
  late final XFile? video;
  late final VideoPlayerController? videoPlayerController;

  @override
  void initState() async {
    video = await ImagePicker().pickVideo(source: ImageSource.gallery);
    if (video != null) {
      videoPlayerController = VideoPlayerController.file(File(video!.path));
    }
    super.initState();
  }

  @override
  void dispose() {
    videoPlayerController?.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      extendBodyBehindAppBar: true,
      body: Stack(
        alignment: Alignment.center,
        children: [
          videoPlayerController != null && videoPlayerController!.value.isInitialized
              ? AspectRatio(
                  aspectRatio: videoPlayerController!.value.aspectRatio,
                  child: Container(
                    color: Colors.red,
                    child: VideoPlayer(videoPlayerController!),
                  ),
                )
              : Container()
        ],
      ),
    );
  }
}
```

</details>

<details>
<summary>video/screenshot BUG 1080x1920</summary>

![veryHigh1080x1920(BUG)](https://user-images.githubusercontent.com/40660782/172989070-1fcf883e-75e9-47f2-810c-a03a2a7eff5b.jpg)

https://user-images.githubusercontent.com/40660782/172989071-f6b7232c-3765-4c87-820f-3bc324569b1a.mp4
</details>

</details>

<details>
<summary>video/screenshot OK 720x1280</summary>

![high720x1280(OK)](https://user-images.githubusercontent.com/40660782/172989062-ba7c7052-4ea8-44bf-bdeb-2e5eb20b9b6b.jpg)

https://user-images.githubusercontent.com/40660782/172989067-ba08ec5a-4a25-4269-ac60-79c350ed19b9.mp4
</details>

<details>
  <summary>flutter doctor -v</summary>
  
```
[✓] Flutter (Channel stable, 3.0.1, on macOS 12.4 21F79 darwin-arm, locale ru-RU)
    • Flutter version 3.0.1 at /Users/dmitrijkapustni/libs/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (3 weeks ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/dmitrijkapustni/Library/Android/sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.67.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.42.0

[✓] Connected device (3 available)
    • T766H RU (mobile) • 8TN7IVOZ5P4LSCMN • android-arm64  • Android 11 (API 30)
    • macOS (desktop)   • macos            • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 102.0.5005.61

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by exaby73** [comment] 2022-06-10 09:51
Duplicate of #104959

**Closed by exaby73** 2022-06-10 09:51 UTC
Labels: in triage
