### ISSUE TITLE
flutter install fails with release build to iOS Simulator

### ISSUE THREAD

**Issue by awhitford** [flutter/flutter#57913] opened 2020-05-25 03:30 UTC
## Steps to Reproduce

1. Run `flutter build ios --release`.
2. Run the iOS Simulator and open a Device (like iPhone 11 Pro).
3. Run `flutter install --verbose`

**Expected results:**

I want to run a _Release Build_ on the Simulator (so that I can screen capture on various devices that I do not own).

**Actual results:**

It fails:
```
[  +18 ms] Installing com.example.kozzetSimple to iPhone 11 Pro...
[   +1 ms] executing: /usr/bin/xcrun simctl get_app_container BF9D324A-ED08-4180-BFEE-F6C1AE23DAF4 com.example.kozzetSimple
[ +132 ms] executing: /usr/bin/xcrun simctl install BF9D324A-ED08-4180-BFEE-F6C1AE23DAF4 build/ios/iphonesimulator/Runner.app
[ +105 ms] An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
                    Failed to install the requested application
                    An application bundle was not found at the provided path.
                    Provide a valid path to the desired application bundle.
[  +12 ms] "flutter install" took 4,385ms.
Install failed
```

<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel stable, v1.17.1, on Mac OS X 10.15.4 19E287, locale en-US)
    • Flutter version 1.17.1 at /Users/anthony/flutter
    • Framework revision f7a6a7906b (12 days ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/anthony/Library/Android/sdk
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.2

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.2

[✓] Connected device (1 available)
    • iPhone 11 Pro • BF9D324A-ED08-4180-BFEE-F6C1AE23DAF4 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-5 (simulator)

• No issues found!
```

</details>

**Comment by TahaTesser** [comment] 2020-05-25 13:06
closing as duplicate of https://github.com/flutter/flutter/issues/11754

**Closed by TahaTesser** 2020-05-25 13:06 UTC
