### ISSUE TITLE
Flutter app gets stuck at splash screen during development

### ISSUE THREAD

**Issue by mwawrusch** [flutter/flutter#65690] opened 2020-09-12 15:46 UTC
## Steps to Reproduce

My rather large flutter app gets stuck at the splashscreen during development on ios. This happens about 35% of the time on an actual IOS device and about now 50% of the time on the simulator. Ways to fix it normally require one of the following:
* stop and restart
* flutter clean
* restart simulator

On the same machine, with smaller apps, I never experience those issues. It seems that there is some timeout happening that is not logged anywhere when the size of the flutter app gets too big.

This is a huge productivity problem for us as it takes up at least 45 mins a day now.

## Logs

no logs...

```
 Flutter (Channel stable, 1.20.3, on Mac OS X 10.15.6 19G2021, locale en-US)
    • Flutter version 1.20.3 at /Users/mwawrusch/Dev/flutter
    • Framework revision 216dee60c0 (11 days ago), 2020-09-01 12:24:47 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/mwawrusch/Library/Android/sdk
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.7, Build version 11E801a
    • CocoaPods version 1.9.3

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.48.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.0

[✓] Connected device (2 available)
    • moto g 7 power (mobile) • ZY3275PPV8                           • android-arm64 • Android 9 (API 28)
    • iPhone 11 (mobile)      • 627483D0-B33B-4F1B-91B5-4FFE52696DF0 • ios           • com.apple.CoreSimulator.SimRuntime.iOS-13-7 (simulator)

• No issues found!
```

**Comment by Abhishek01039** [comment] 2020-09-12 16:06
Hi @mwawrusch 
logs should be there
can you please try `flutter run -v` while you are running the app?
Thanks.

**Comment by markusaksli-nc** [comment] 2020-09-14 08:53
Hi @mwawrusch 
I see there's an open issue addressing the case you described https://github.com/flutter/flutter/issues/63800.
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by markusaksli-nc** 2020-09-14 08:53 UTC

**Comment by NatyN-teac** [comment] 2021-03-05 15:03
hi, i m also experiencing the same issue here, i have build app and when i directly run from android studio on real device it works but after i build signed apk and installed it but it stuck on splash screen only showing me my splash screen. some one who has solved it please put some hint on how to solve it

**Comment by felipebueno** [comment] 2021-03-12 13:23
Same problem here.

It get stuck on splash screen when running from the apk.

**Comment by hsm59** [comment] 2021-03-17 18:42
Facing this same issue, when trying to run the app through an APK, it's stuck on the Splash Screen.

**Comment by BartusZak** [comment] 2021-03-22 18:28
the same here

**Comment by markusaksli-nc** [comment] 2021-03-23 07:31
This issue was a duplicate of another issue. These were related to an older version of Flutter and likely had a different root cause to what you are facing. 

If you are still running into this issue please file a new issue, follow the template and provide the information on your specific case with your `flutter run -v` or device logs.

**Comment by rlavila8713** [comment] 2021-04-27 22:27
same problem happens to me ;(

**Comment by dombroks** [comment] 2021-05-11 14:18
Try with this:

buildTypes {
    release {
        shrinkResources false // Add this line.
        minifyEnabled false
        signingConfig signingConfigs.release
    }
}

**Comment by jkelley79** [comment] 2021-05-16 17:52
I had this issue until I upgraded to XCode 12.5 and my iPhone to 14.5.1. It did require allowing iproxy to be downloaded and run within the Security.

**Comment by isaacpitwa** [comment] 2021-05-30 07:46
same problem happens to me
