### ISSUE TITLE
Adjusting the stroke of the switch

### ISSUE THREAD

**Issue by denisgl7** [flutter/flutter#126536] opened 2023-05-11 12:52 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

It seems to me obvious that it is necessary to allow users to give the ability to adjust the stroke. Design should be as flexible as possible
<img width="52" alt="image" src="https://github.com/flutter/flutter/assets/18004353/1bf14727-96ae-430c-9a5b-2cf68d614a0f">

### Proposal

`    final Paint outlinePaint = Paint()
        ..style = PaintingStyle.stroke
        ..strokeWidth = 2 
    }
  }`

Need to add the strokeWidth parameter to the _paintTrackWith constructor, and further up the classes

**Comment by TahaTesser** [comment] 2023-05-11 14:47
Hi @denisgl7 

`Switch.trackOutlineWidth` allows you to adjust stroke width.  This was added https://github.com/flutter/flutter/pull/125848, only available on the `master` channel right now.

![Screenshot 2023-05-11 at 17 43 45](https://github.com/flutter/flutter/assets/48603081/f1303a7a-0160-4690-bf9e-4663215022fa)

```dart
    return Switch(
      // This bool value toggles the switch.
      value: light,
      activeColor: Colors.red,
      trackOutlineWidth: const MaterialStatePropertyAll<double?>(5.0),
      onChanged: (bool value) {
        // This is called when the user toggles the switch.
        setState(() {
          light = value;
        });


      },
    );
```

Closing as duplicate of dhttps://github.com/flutter/flutter/issues/122451

**Closed by TahaTesser** 2023-05-11 14:47 UTC
Labels: in triage
