### ISSUE TITLE
Tree status not updated in old PRs

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#118360] opened 2023-01-12 02:05 UTC
It seems like we only update tree status in the top N prs based on some criteria. This causes that old PRs waiting to be submitted may wait forever.

**Comment by ricardoamador** [comment] 2023-01-13 20:29
Keyong has mentioned this before. This is exactly the case thought I don't remember what the cutoff for the number of days open is.

**Comment by godofredoc** [comment] 2023-01-13 20:42
When updating can we make an union of PRs with the autosubmit label + the top N we are currently using?

**Comment by ricardoamador** [comment] 2023-01-13 20:44
I would need to look but that is certainly possible to do.

**Comment by ricardoamador** [comment] 2023-07-05 17:00
Duplicate of this: https://github.com/flutter/flutter/issues/106816

**Closed** 2023-07-05 17:01 UTC
Labels: team: infra, passed secondary triage
