### ISSUE TITLE
Ripple not disappear bug

### ISSUE THREAD

**Issue by hahafather007** [flutter/flutter#27761] opened 2019-02-11 09:20 UTC
When you press the Home button while holding the water ripple button, and then switch back to the app, the shadow of the water ripple will not disappear until you open another page and then return to normal.

Gif like this:
![b6fxj-ck9w8](https://user-images.githubusercontent.com/23414420/52606064-316d2580-2eac-11e9-9552-2cdf2dfbefea.gif)

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      floatingActionButton: FloatingActionButton(onPressed: () {
        Navigator.of(context)
            .push(MaterialPageRoute(builder: (_) => MyHomePage()));
      }),
      body: Container(
        alignment: Alignment.center,
        child: Row(
          children: <Widget>[
            Material(
              color: Colors.lightBlueAccent,
              child: InkWell(
                onTap: () {},
                child: Container(
                  width: 120,
                  height: 120,
                ),
              ),
            ),
            Material(
              color: Colors.lightBlueAccent,
              child: InkWell(
                onTap: () {},
                child: Container(
                  width: 120,
                  height: 120,
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}
```
Flutter doctor:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v1.1.5-pre.6, on Mac OS X 10.14.2 18C54, locale
    zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.3)
[!] IntelliJ IDEA Community Edition (version 2018.2.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
[✓] Connected device (2 available)

! Doctor found issues in 1 category.
```

**Comment by pepegich** [comment] 2019-02-11 10:30
reproduced on stable channel v1.0.0

**Comment by zoechi** [comment] 2019-02-11 11:43
Please test with `dev` or even `master`. `stable` is quite outdated already.

**Comment by hahafather007** [comment] 2019-02-12 02:30
Also on `Channel master, v1.2.1-pre.153`
@zoechi

**Comment by zoechi** [comment] 2019-02-13 16:16
Similar to #19021

**Comment by zoechi** [comment] 2019-02-13 16:17
Duplicate of #19021

**Closed by zoechi** 2019-02-13 16:17 UTC
Labels: f: material design, framework
