### ISSUE TITLE
Italic-styled text is clipped on web

### ISSUE THREAD

**Issue by znjameswu** [flutter/flutter#63460] opened 2020-08-11 06:53 UTC
In 1.20.0-7.4-pre version, italic-styled text will be clipped, if their skew ever extend out of the box.
![微信截图_20200810234805](https://user-images.githubusercontent.com/61373469/89866203-fd87c480-db63-11ea-8593-b5a5abdfc1af.png)

##  Steps to Reproduce
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(),
        body: Row(
          mainAxisAlignment: MainAxisAlignment.start,
          children: List.filled(
            10,
            Text(
              'f',
              style: TextStyle(fontStyle: FontStyle.italic, fontSize: 50),
            ),
          ),
        ),
      ),
    );
  }
}
```

**Expected results:** 
On mobile, the Text widget won't clip the characters inside.

This behavior is affecting typesetting systems using flutter. There are significant clippings on the render samples in my equation rendering app's demo page (since equations are italic in nature). [Flutter Math Demo](https://znjameswu.github.io/flutter_math_demo/#/)

## Flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, 1.20.0, on Microsoft Windows [Version 10.0.18363.959], locale zh-CN)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
[√] Chrome - develop for the web
[√] Android Studio (version 4.0)
[√] IntelliJ IDEA Community Edition (version 2019.3)
[√] VS Code (version 1.47.3)
[√] Connected device (3 available)

• No issues found!

**Comment by TahaTesser** [comment] 2020-08-11 12:37
I can reproduce it on Windows 

### Windows 

![image](https://user-images.githubusercontent.com/48603081/89895221-0e364a00-dbf9-11ea-8be2-348527af1975.png)

### Mac

<img width="204" alt="Screenshot 2020-08-11 at 5 34 32 PM" src="https://user-images.githubusercontent.com/48603081/89897841-4b9cd680-dbfd-11ea-9642-45f2594bdb44.png">

<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel beta, 1.20.0, on Mac OS X 10.15.6 19G73, locale en-GB)
    • Flutter version 1.20.0 at /Users/tahatesser/Code/flutter_beta
    • Framework revision 916c3ac648 (10 days ago), 2020-08-01 09:01:12 -0700
    • Engine revision d6ee1499c2
    • Dart version 2.9.0 (build 2.9.0-21.10.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

 
[✓] Connected device (3 available)            
    • SM M305F (mobile) • 32003c30dc19668f • android-arm64  • Android 10 (API 29)
    • Web Server (web)  • web-server       • web-javascript • Flutter Tools
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 84.0.4147.125

• No issues found! 
```

</details> 


<details> 
<summary>flutter doctor -v</summary> 

```

[✓] Flutter (Channel master, 1.21.0-8.0.pre.140, on Mac OS X 10.15.6 19G73, locale en-GB)
    • Flutter version 1.21.0-8.0.pre.140 at /Users/tahatesser/Code/flutter_master
    • Framework revision c8d051295a (8 hours ago), 2020-08-11 00:26:02 -0400
    • Engine revision a62703778b
    • Dart version 2.10.0 (build 2.10.0-5.0.dev e2a67723ca)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

 
S[✓] Connected device (3 available)            
    • SM M305F (mobile) • 32003c30dc19668f • android-arm64  • Android 10 (API 29)
    • Web Server (web)  • web-server       • web-javascript • Flutter Tools
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 84.0.4147.125

• No issues found!
 
```

</details>

**Comment by znjameswu** [comment] 2020-08-11 17:06
> ### Mac
> <img alt="Screenshot 2020-08-11 at 5 34 32 PM" width="204" src="https://user-images.githubusercontent.com/48603081/89897841-4b9cd680-dbfd-11ea-9642-45f2594bdb44.png">
> 

Actually there is still text clipping on Mac. If you compare your result to true [Roboto samples](https://fonts.google.com/specimen/Roboto?selection.family=Roboto:ital,wght@1,500&sidebar.open=true), you will see that a true Roboto italic 'f' should extend its head far right to the slash.

![微信截图_20200811100518](https://user-images.githubusercontent.com/61373469/89926799-35215b80-dbba-11ea-9c8e-4b4d4f612ed2.png)

**Comment by kunit1** [comment] 2020-08-13 19:08
Not OP but here is what I see,
HTML backend:
![image](https://user-images.githubusercontent.com/22163077/90176395-d81ed480-dd76-11ea-9bfa-11e74a2f861a.png)

CanvasKit backend:
![image](https://user-images.githubusercontent.com/22163077/90176308-bc1b3300-dd76-11ea-8d68-93e1642fa60f.png)

**Comment by znjameswu** [comment] 2020-08-13 20:17
> Can you please also provide the full `flutter run` command you use to run the app? (trying to determine whether HTML and/or CanvasKit backend is affected)

It is DomCanvas backend. I just tested CanvasKit and it seems CanvasKit doesn't have this problem.

**Comment by mdebbar** [comment] 2020-08-14 21:55
This is a problem in the browser itself. See this jsfiddle with pure HTML/CSS: https://jsfiddle.net/f5rjtbkz/1/

We'll have to find a workaround for this.

**Comment by fearlessambassador** [comment] 2020-12-20 08:30
I'm seeing the same problem

**Comment by mdebbar** [comment] 2021-03-17 18:18
There have been several changes to text rendering since this issue was filed. I'm not able to reproduce anymore. Could you try again and see if this issue still exist on master or the new stable version?

**Comment by pedromassangocode** [comment] 2021-04-07 12:56
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2021-04-07 12:56 UTC
Labels: P4, a: typography, engine, passed first triage, platform-web, waiting for customer response
