### ISSUE TITLE
can not run in device , can only run in simulator with  official article  https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps#ios  

### ISSUE THREAD

**Issue by imfaker** [flutter/flutter#38746] opened 2019-08-17 16:04 UTC
## Steps to Reproduce

1. II follow the instructions of the official article about Add-Flutter-to-existing-apps (https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps#ios)
2. when I finish , I can run it on the simulator , in my orginal iOS  project 
3. but if I add plugin in dart , like   cached_network_image: ^1.1.1
   ,  I can not   run it on the  device or release mode , only can run in  simulator with debug mode , it has compile  error .

## Logs

this  is  Xcode compile error

Ld /Users/fuxiaoquan/Library/Developer/Xcode/DerivedData/VpnMaster-gcxshtzmsgkvuledmnwyiqcfsdba/Build/Products/Debug-iphoneos/path_provider/path_provider.framework/path_provider normal arm64
    cd /Users/fuxiaoquan/Desktop/beginFromBegin/VpnMaster/Pods
    export IPHONEOS_DEPLOYMENT_TARGET=8.0
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch arm64 -dynamiclib -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.4.sdk -L/Users/fuxiaoquan/Library/Developer/Xcode/DerivedData/VpnMaster-gcxshtzmsgkvuledmnwyiqcfsdba/Build/Products/Debug-iphoneos/path_provider -F/Users/fuxiaoquan/Library/Developer/Xcode/DerivedData/VpnMaster-gcxshtzmsgkvuledmnwyiqcfsdba/Build/Products/Debug-iphoneos/path_provider -F/Users/fuxiaoquan/Desktop/beginFromBegin/VpnMaster/Pods/../../vpnmaster_flutter/.ios/Flutter/engine -filelist /Users/fuxiaoquan/Library/Developer/Xcode/DerivedData/VpnMaster-gcxshtzmsgkvuledmnwyiqcfsdba/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/path_provider.build/Objects-normal/arm64/path_provider.LinkFileList -install_name @rpath/path_provider.framework/path_provider -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -miphoneos-version-min=8.0 -dead_strip -Xlinker -object_path_lto -Xlinker /Users/fuxiaoquan/Library/Developer/Xcode/DerivedData/VpnMaster-gcxshtzmsgkvuledmnwyiqcfsdba/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/path_provider.build/Objects-normal/arm64/path_provider_lto.o -Xlinker -export_dynamic -Xlinker -no_deduplicate -fembed-bitcode-marker -fobjc-arc -fobjc-link-runtime -framework Foundation -compatibility_version 1 -current_version 1 -Xlinker -dependency_info -Xlinker /Users/fuxiaoquan/Library/Developer/Xcode/DerivedData/VpnMaster-gcxshtzmsgkvuledmnwyiqcfsdba/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/path_provider.build/Objects-normal/arm64/path_provider_dependency_info.dat -o /Users/fuxiaoquan/Library/Developer/Xcode/DerivedData/VpnMaster-gcxshtzmsgkvuledmnwyiqcfsdba/Build/Products/Debug-iphoneos/path_provider/path_provider.framework/path_provider

ld: warning: Could not find auto-linked framework 'Flutter'
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_FlutterStandardTypedData", referenced from:
      objc-class-ref in SqflitePlugin.o
  "_OBJC_CLASS_$_FlutterError", referenced from:
      objc-class-ref in SqflitePlugin.o
  "_OBJC_CLASS_$_FlutterMethodChannel", referenced from:
      objc-class-ref in SqflitePlugin.o
  "_FlutterMethodNotImplemented", referenced from:
      -[SqflitePlugin handleMethodCall:result:] in SqflitePlugin.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

<!-- If possible, paste the output of running `flutter doctor -v` here. -->

[✓] Flutter (Channel master, v1.9.1-pre.59, on Mac OS X 10.14.6 18G87, locale
    zh-Hans-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
[✓] Android Studio (version 3.4)
[✓] Connected device (2 available)
```

what should I do ?  can run in device or  release mode?

**Comment by jmagman** [comment] 2019-08-19 22:00
Flutter is not currently supported on the simulator in profile or release mode.  You should be able to run build configurations on a real device, though.

Are you running from your app's xcworkspace?  CocoaPods will create a xcworkspace (if one doesn't already exist) and add the plugin targets there.

**Comment by imfaker** [comment] 2019-08-20 09:46
> Flutter is not currently supported on the simulator in profile or release mode. You should be able to run build configurations on a real device, though.
> 
> Are you running from your app's xcworkspace? CocoaPods will create a xcworkspace (if one doesn't already exist) and add the plugin targets there.


I am running  very well in  simulator ,but can not running in device.  
And  I use cocoapods  and add the plugin  targets there  , follow (https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps#ios)

**Comment by jmagman** [comment] 2019-08-20 17:51
Can you confirm you are running from your original app's .xcworkspace that contains the Pods project and not the .xcodeproj?

**Comment by jmagman** [comment] 2019-08-20 17:54
And confirm that you ran `pod install`?

**Comment by imfaker** [comment] 2019-08-21 00:08
> And confirm that you ran `pod install`?

yes I am sure。If I did not   do this  , I can not runing in  simulator .`
<img width="276" alt="屏幕快照 2019-08-21 上午8 05 22" src="https://user-images.githubusercontent.com/16117902/63392771-a0db4900-c3ea-11e9-82df-0189a1ffd195.png">
<img width="255" alt="屏幕快照 2019-08-21 上午8 05 15" src="https://user-images.githubusercontent.com/16117902/63392787-b3ee1900-c3ea-11e9-85e6-b1756e9cad8d.png">
this is my pod project 

`

**Comment by jmagman** [comment] 2019-08-21 00:46
> yes I am sure。If I did not do this , I can not runing in simulator .`

Very fair point 😀

I am just trying to figure out why the arm* architecture Flutter framework isn't found in the search paths because I am not able to reproduce on Channel master, v1.9.2-pre.41.  I can run on a device and the simulator in Debug with sqflite plugin, etc.  And I see Flutter in your Development Pods...

>Whenever you change the Flutter plugin dependencies in some/path/my_flutter/pubspec.yaml, you need to run `flutter packages get` from some/path/my_flutter to refresh the list of plugins read by the podhelper.rb script. Then run pod install again from some/path/MyApp.

but you did that I assume since it's working from the simulator...

Are you able to make a test app that reproduces this?

**Comment by dntzee** [comment] 2019-08-23 06:59
I have the same error，I follow the instructions of the official article about Add-Flutter-to-existing-apps (https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps#ios).

Everything works fine, when I add these dependencies to the pubspec.yaml file, 

iOS won't run on the device,

it can only run in the simulator.

`  cupertino_icons: '0.1.2'
  dio: '2.1.13'
  path_provider: '1.2.0'
  dio_flutter_transformer: '2.0.10'
  page_transition: '1.1.4'
  flutter_easyrefresh: '1.2.7'
  fluro: '1.5.1'
  event_bus: '1.1.0'
  image_picker: '0.4.12+1'
  flutter_screenutil: '0.5.3'
  fluttertoast: '^2.2.11'
  video_player: '0.9.0'
  audioplayer: #^0.5.2
  cached_network_image: '1.1.1'
  shared_preferences: '0.5.3+4'
  flutter_html: '0.10.4'
  flutter_webview_plugin: '0.3.2'`

**Comment by imfaker** [comment] 2019-08-23 08:10
> I have the same error，I follow the instructions of the official article about Add-Flutter-to-existing-apps (https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps#ios).
> 
> Everything works fine, when I add these dependencies to the pubspec.yaml file,
> 
> iOS won't run on the device,
> 
> it can only run in the simulator.
> 
> ` cupertino_icons: '0.1.2' dio: '2.1.13' path_provider: '1.2.0' dio_flutter_transformer: '2.0.10' page_transition: '1.1.4' flutter_easyrefresh: '1.2.7' fluro: '1.5.1' event_bus: '1.1.0' image_picker: '0.4.12+1' flutter_screenutil: '0.5.3' fluttertoast: '^2.2.11' video_player: '0.9.0' audioplayer: #^0.5.2 cached_network_image: '1.1.1' shared_preferences: '0.5.3+4' flutter_html: '0.10.4' flutter_webview_plugin: '0.3.2'`

**Comment by leielyq** [comment] 2019-08-28 09:06
Me too,on iphone7

**Comment by leielyq** [comment] 2019-08-28 11:05
@imfaker 你弄好了吗

**Comment by imfaker** [comment] 2019-08-29 02:24
后面我反正用了其它方法 解决，   这个 问题可能原因 ，是你的 flutter 引擎可能对不上， 如果你的 flutter。framework 是别人 发给你的，不是自己生成的 ，检查下两边的对应库版本是不是 一样 ，都是master channel。然后还有可能 就是我也不知道是 bug 还是 什么原因，你再试试重新 flutter clean生成新的试试。    周末我可能会找下具体的原因，现在这个问题我是偶尔出现 ，有时候又好。

**Comment by imfaker** [comment] 2019-08-29 02:26
> @imfaker Did you mean to close this?

no， I solve this problen in other way ， and I think I would found reason  in this weekend ，

**Comment by jmagman** [comment] 2019-08-29 02:30
Yes, you need the same version of the framework that corresponds to the version of Flutter you have installed.
@leielyq is that your issue, too?

**Comment by leielyq** [comment] 2019-08-29 05:56
> Yes, you need the same version of the framework that corresponds to the version of Flutter you have installed.
> @leielyq is that your issue, too?

I know!  My project have path_provider and  sqflite .  And them has this.
then,I new project,And remove path_provider and  sqflite .this is OK!
I speack english a little.

**Comment by leielyq** [comment] 2019-08-29 05:57
> > Yes, you need the same version of the framework that corresponds to the version of Flutter you have installed.
> > @leielyq is that your issue, too?
> 
> I know! My project have path_provider and sqflite . And them has this.
> then,I new project,And remove path_provider and sqflite .this is OK!
> I speack english a little.

I discover oc and swift project, flutter no work

**Comment by leielyq** [comment] 2019-08-29 06:00
> > > Yes, you need the same version of the framework that corresponds to the version of Flutter you have installed.
> > > @leielyq is that your issue, too?
> > 
> > 
> > I know! My project have path_provider and sqflite . And them has this.
> > then,I new project,And remove path_provider and sqflite .this is OK!
> > I speack english a little.
> 
> I discover oc and swift project, flutter no work

But,my project use a lot of path_provider,sad

**Comment by leielyq** [comment] 2019-08-29 06:55
> 后面我反正用了其它方法 解决， 这个 问题可能原因 ，是你的 flutter 引擎可能对不上， 如果你的 flutter。framework 是别人 发给你的，不是自己生成的 ，检查下两边的对应库版本是不是 一样 ，都是master channel。然后还有可能 就是我也不知道是 bug 还是 什么原因，你再试试重新 flutter clean生成新的试试。 周末我可能会找下具体的原因，现在这个问题我是偶尔出现 ，有时候又好。

可能看一下你的path_provider版本吗

**Comment by imfaker** [comment] 2019-08-31 01:53
> > 后面我反正用了其它方法 解决， 这个 问题可能原因 ，是你的 flutter 引擎可能对不上， 如果你的 flutter。framework 是别人 发给你的，不是自己生成的 ，检查下两边的对应库版本是不是 一样 ，都是master channel。然后还有可能 就是我也不知道是 bug 还是 什么原因，你再试试重新 flutter clean生成新的试试。 周末我可能会找下具体的原因，现在这个问题我是偶尔出现 ，有时候又好。
> 
> 可能看一下你的path_provider版本吗

你报的什么错

**Comment by shawn736** [comment] 2019-09-17 07:33
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_FlutterMethodChannel", referenced from:
      objc-class-ref in PathProviderPlugin.o
  "_FlutterMethodNotImplemented", referenced from:
      ___47+[FLTPathProviderPlugin registerWithRegistrar:]_block_invoke in PathProviderPlugin.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Using the "stable" branch of the Flutter SDK, I have same error on the real device.  When I change to the "master" branch, it both works on the device and simulator.

**Comment by jmagman** [comment] 2019-09-17 19:18
> 后面我反正用了其它方法 解决， 这个 问题可能原因 ，是你的 flutter 引擎可能对不上， 如果你的 flutter。framework 是别人 发给你的，不是自己生成的 ，检查下两边的对应库版本是不是 一样 ，都是master channel。然后还有可能 就是我也不知道是 bug 还是 什么原因，你再试试重新 flutter clean生成新的试试。 周末我可能会找下具体的原因，现在这个问题我是偶尔出现 ，有时候又好。

The issue reported by the originator is that their version of the Flutter.framework did not match the version of Flutter that compiled their dart code (assuming I'm translating correctly).  This is expected behavior since there is not guaranteed binary compatibility between different versions of dart.  So I'm going to close this issue.

Anyone else with a similar linker error on a real device and not the simulator, should file a new issue and link to this one if:
1. You are on the [master channel](https://github.com/flutter/flutter/wiki/Flutter-build-release-channels#how-to-change-channels) and have run `flutter upgrade`.  Add-to-app must be run from the master channel.  See https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps#intro.
1. You have run `flutter clean`.
1. You didn't get Flutter.framework from somewhere other than the version that was downloaded on your machine with the `flutter` tools (the originator's issue).

A sample app reproducing the issue is always appreciated as well.

Thanks!

**Closed by jmagman** 2019-09-17 19:18 UTC
Labels: a: existing-apps
