### ISSUE TITLE
TextField with autofillHints enabled looks wrong since version 3.13.1

### ISSUE THREAD

**Issue by d-ukhanov** [flutter/flutter#134587] opened 2023-09-12 22:32 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I'm using TextFormField with AutofillHints.email in web (Chrome 117.0.5938.63). 
When I upgraded to 3.13.x (encountered this problem in 3.13.1 and 3.13.3), when I focus on the text field, a blue border appears around the text (not like a border or focusedBorder, this one is drawn with contentPadding).
When I don't pass anything to autofillHints, this border doesn't appear.

### Expected results

![image](https://github.com/flutter/flutter/assets/47328911/a4d5d71f-2b3b-47ec-a506-10524400d5f4)

### Actual results

![image](https://github.com/flutter/flutter/assets/47328911/f17cae01-2410-4ec0-8249-6acdc751a973)

### Code sample

<details><summary>Code sample</summary>

On the screenshot in Actual results
```dart
Widget _getInputEmailTextField(BuildContext context) {
    return AutofillGroup(
      child: DefaultTextFormField(
        controller: _emailController,
        isEnabled: widget.isChangeable,
        hintText: context.l10n.login_email,
        autofillHints: const [AutofillHints.email],
        onEditingComplete: _checkFields,
        validator: (val) {
          if (val != null && val.isNotEmpty && val.isEmail) {
            return null;
          }
          return context.l10n.login_email_empty;
        },
      ),
    );
  }
```
In DefaultTextFormField
```dart
TextFormField(
        controller: controller,
        enabled: isEnabled,
        keyboardType: isMultiline ? TextInputType.multiline : null,
        minLines: isMultiline ? 6 : 1,
        maxLines: isMultiline ? 6 : 1,
        style: TextStyle(
          fontSize: 16.0,
          height: isMultiline ? 1.4 : 1.0,
          color: context.theme.colorScheme.onSecondaryContainer,
        ),
        textAlign: TextAlign.left,
        decoration: InputDecoration(
          constraints: isMultiline
              ? null
              : BoxConstraints(minHeight: fieldHeight ?? 50.0),
          hintText: hintText,
          fillColor: backgroundColor,
          border: UnderlineInputBorder(
            borderRadius: BorderRadius.circular(10.0),
            borderSide: BorderSide.none,
          ),
        ),
        textInputAction: textInputAction,
        autofillHints: autofillHints,
        onChanged: onChanged,
        onEditingComplete: onEditingComplete,
        validator: validator,
)
```

On the screenshot in Expected results
```dart
Widget _getInputEmailTextField(BuildContext context) {
    return AutofillGroup(
      child: DefaultTextFormField(
        controller: _emailController,
        isEnabled: widget.isChangeable,
        hintText: context.l10n.login_email,
        //autofillHints: const [AutofillHints.email],
        onEditingComplete: _checkFields,
        validator: (val) {
          if (val != null && val.isNotEmpty && val.isEmail) {
            return null;
          }
          return context.l10n.login_email_empty;
        },
      ),
    );
  }
```
</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.13.3, on Microsoft Windows [Version 10.0.19045.3324], locale ru-RU)
    • Flutter version 3.13.3 on channel stable at D:\src\flutter                                  
    • Upstream repository https://github.com/flutter/flutter.git                                  
    • Framework revision 2524052335 (6 days ago), 2023-09-06 14:32:31 -0700                       
    • Engine revision b8d35810e9                                                                  
    • Dart version 3.1.1                                                                          
    • DevTools version 2.25.0                                                                     
                                                                                                  
[√] Windows Version (Installed version of Windows is version 10 or higher)                        

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at D:\Users\karan\SDK
    • Platform android-33, build-tools 30.0.3
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19045.3324]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 116.0.5845.187
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 94.0.992.38 (unsupported)

[√] Network resources
    • All expected network resources are available.
```

</details>

**Comment by danagbemava-nc** [comment] 2023-09-13 10:09
Hi @d-ukhanov, what renderer are you using for the web (html/canvaskit)? 
Is this only on the web or are other platforms affected? 

Lastly, your code sample is not complete. Please provide a complete minimal reproducible code sample so that we can investigate this issue. 

Thank you

**Comment by d-ukhanov** [comment] 2023-09-14 01:16
Only on the web (both html and canvaskit).

Finally managed to reproduce the bug in a new project. 
As it turned out, it is related to zoom web sdk. 
How to reproduce the bug: 
Import in web/index.html zoom web sdk:
```
  <link type="text/css" rel="stylesheet" href="https://source.zoom.us/2.16.0/css/react-select.css">
  <script src="https://source.zoom.us/2.16.0/lib/vendor/react.min.js"></script>
  <script src="https://source.zoom.us/2.16.0/lib/vendor/react-dom.min.js"></script>
  <script src="https://source.zoom.us/2.16.0/lib/vendor/redux.min.js"></script>
  <script src="https://source.zoom.us/2.16.0/lib/vendor/redux-thunk.min.js"></script>
  <script src="https://source.zoom.us/2.16.0/lib/vendor/lodash.min.js"></script>
  <script src="https://source.zoom.us/2.16.0/lib/av/1502_js_media.min.js"></script>
  <script src="https://source.zoom.us/zoom-meeting-2.16.0.min.js"></script>
```
Specifically, <script src="https://source.zoom.us/zoom-meeting-2.16.0.min.js"></script>. If I remove it, the bug disappears.
A project where you can test: https://github.com/d-ukhanov/textfieldtest

![image](https://github.com/flutter/flutter/assets/47328911/9932de10-8263-44b5-bb20-f66db1c1cfd3)

**Comment by danagbemava-nc** [comment] 2023-09-14 07:01
Hi @d-ukhanov, what version of flutter did you upgrade from? If the zoom library causes this, I'm not sure there's anything we can do about it. It might be injecting some code of its own into all text fields. I did a small test with codepen and saw that when the zoom library is added, the page changes significantly. However, in codepen, the change happened whether or not autocomplete was added. 

https://github.com/flutter/flutter/assets/88313112/97b825f7-ae53-4fac-a9ff-04c50eb5b1af

**Comment by d-ukhanov** [comment] 2023-09-14 13:20
@danagbemava-nc, from 3.10.6

**Comment by d-ukhanov** [comment] 2023-09-14 13:53
When autofillHints is null in TextField, the text field does not have type="text". 
If look in zoom-meeting-2.16.0.min.js, there is a style "input[type=text]:focus{outline:2px solid #2d8cff !important;outline-offset:1px". 
Is there any way to fix this other than manually changing and duplicating in my project zoom-meeting-2.16.0.min.js?

**Comment by d-ukhanov** [comment] 2023-09-14 16:58
For now, fixed it by putting this style after "<script src="https://source.zoom.us/zoom-meeting-2.16.0.min.js"></script>":
```css
 <style>
        input[type="text"]:focus {
            outline: none !important;
        }
 </style>
```

**Comment by danagbemava-nc** [comment] 2023-09-15 07:21
> When autofillHints is null in TextField, the text field does not have type="text".

This is because `<input />` defaults to `text` when a type is not specified. From what I see in the dom, it looks like there's a submit input field generated as well which handles the autofill submission, which is why when you have autofill the type of 
the textfield is specified as `text`. The submit input field is invisible to you (it seems like it is rendered off-screen). 
The submit button doesn't appear when you don't specify the autofill hints, which would explain why it doesn't show with the normal text field. 


It seems like your workaround in https://github.com/flutter/flutter/issues/134587#issuecomment-1719814241 is the way to go since this is coming from a third-party library. 

I'll be closing this for now. If you disagree, kindly leave a comment below and I will reopen this. Thank you

**Closed by danagbemava-nc** 2023-09-15 07:21 UTC
Labels: in triage
