### ISSUE TITLE
UI not updated when Foldable screen state changed

### ISSUE THREAD

**Issue by Huanxin1997** [flutter/flutter#137399] opened 2023-10-27 07:23 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Open the App in the expanded state of the phone.
2. Do not exit the App, close the folding screen.

### Expected results

The UI can refresh automatically when the state of the folding screen changes.

### Actual results

UI does not automatically adapt, then I need to manually setState to do this. This can also be done by calling MediaQuery.of(context).

### Code sample

```dart
  @override
  void didChangeMetrics() {
    final ui.Display? display = _view?.display;
    final ui.DisplayFeatureState? _displayFeatureState = _view?.displayFeatures.first.state;
    if (display == null) {
      return;
    }

    final double currentWidth = math.min(display.size.height, display.size.width);
    if (currentWidth / display.devicePixelRatio < kOrientationLockBreakpoint) {
      ScreenDesignAdapter.setDesignSize(378, 812);
    } else {
      ScreenDesignAdapter.setDesignSize(674, 842);
    }
  }
```

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

[✓] Flutter (Channel stable, 3.13.7, on macOS 14.0 23A344 darwin-x64, locale
    zh-Hans)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2022.3.3)
[✓] VS Code (version 1.80.0)
[✓] VS Code (version 1.72.2)
[✓] Connected device (2 available)

**Comment by huycozy** [comment] 2023-10-27 11:55
Hi @Huanxin1997 
I'm not sure what `UI can refresh` means. Could you explain more?

Also, I checked this on a foldable emulator with below sample code and saw that app state changed on didChangeAppLifecycleState when flipping screen.

<details>
<summary>Sample code</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);
  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> with WidgetsBindingObserver {
  int _counter = 0;

  void _incrementCounter() async {
    setState(() {
      _counter++;
    });
  }

  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addObserver(this);
  }

  @override
  void dispose() {
    super.dispose();
    WidgetsBinding.instance.removeObserver(this);
  }

  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    super.didChangeAppLifecycleState(state);

    print('+++++ state: $state');
    switch (state) {
      case AppLifecycleState.detached:
        break;
      case AppLifecycleState.inactive:
        break;
      case AppLifecycleState.resumed:
        break;
      case AppLifecycleState.paused:
        break;
      case AppLifecycleState.hidden:
      // TODO: Handle this case.
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headlineMedium,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}

```
</details>

Please try running it and confirm. If the issue only appears on your code, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this.

**Comment by Huanxin1997** [comment] 2023-10-30 00:58
> Hi @Huanxin1997 I'm not sure what `UI can refresh` means. Could you explain more?
> 
> Also, I checked this on a foldable emulator with below sample code and saw that app state changed on didChangeAppLifecycleState when flipping screen.
> 
> Sample code
> ```dart
> import 'package:flutter/material.dart';
> 
> void main() {
>   runApp(const MyApp());
> }
> 
> class MyApp extends StatelessWidget {
>   const MyApp({Key? key}) : super(key: key);
>   @override
>   Widget build(BuildContext context) {
>     return MaterialApp(
>       title: 'Flutter Demo',
>       theme: ThemeData(
>         primarySwatch: Colors.blue,
>       ),
>       home: const MyHomePage(title: 'Flutter Demo Home Page'),
>     );
>   }
> }
> 
> class MyHomePage extends StatefulWidget {
>   const MyHomePage({Key? key, required this.title}) : super(key: key);
>   final String title;
> 
>   @override
>   State<MyHomePage> createState() => _MyHomePageState();
> }
> 
> class _MyHomePageState extends State<MyHomePage> with WidgetsBindingObserver {
>   int _counter = 0;
> 
>   void _incrementCounter() async {
>     setState(() {
>       _counter++;
>     });
>   }
> 
>   @override
>   void initState() {
>     super.initState();
>     WidgetsBinding.instance.addObserver(this);
>   }
> 
>   @override
>   void dispose() {
>     super.dispose();
>     WidgetsBinding.instance.removeObserver(this);
>   }
> 
>   @override
>   void didChangeAppLifecycleState(AppLifecycleState state) {
>     super.didChangeAppLifecycleState(state);
> 
>     print('+++++ state: $state');
>     switch (state) {
>       case AppLifecycleState.detached:
>         break;
>       case AppLifecycleState.inactive:
>         break;
>       case AppLifecycleState.resumed:
>         break;
>       case AppLifecycleState.paused:
>         break;
>       case AppLifecycleState.hidden:
>       // TODO: Handle this case.
>     }
>   }
> 
>   @override
>   Widget build(BuildContext context) {
>     return Scaffold(
>       appBar: AppBar(
>         title: Text(widget.title),
>       ),
>       body: Center(
>         child: Column(
>           mainAxisAlignment: MainAxisAlignment.center,
>           children: <Widget>[
>             const Text(
>               'You have pushed the button this many times:',
>             ),
>             Text(
>               '$_counter',
>               style: Theme.of(context).textTheme.headlineMedium,
>             ),
>           ],
>         ),
>       ),
>       floatingActionButton: FloatingActionButton(
>         onPressed: _incrementCounter,
>         tooltip: 'Increment',
>         child: const Icon(Icons.add),
>       ),
>     );
>   }
> }
> ```
> 
> Please try running it and confirm. If the issue only appears on your code, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this.

Thanks for your response. Let me add to my fact sheet:
For example, when the device is changed from the compact state to the expanded state, the UI still maintains the compact size but is stretched, resulting in serious deformation. Only when you manually setState or call MediaQuery.of(context) can you update to a size that fits the expanded state.

**Comment by huycozy** [comment] 2023-10-30 04:46
I also checked the contrary case you mentioned (compact to expanded state) but still cannot reproduce the issue you are experiencing. Looking at the video demo below, you will see the UI is distorted for a while and be normal later, but it seems to be a simulator issue as the other native app has similar behavior (Chrome app)

https://github.com/flutter/flutter/assets/104349824/caefe09b-330b-474b-a04e-275029e89652

This may be a device-specific issue. What is your device model? Could you share a recorded video for this?

And please confirm if this issue occurs on a new Flutter project. Thanks!

**Comment by Huanxin1997** [comment] 2023-11-01 03:06
> I also checked the contrary case you mentioned (compact to expanded state) but still cannot reproduce the issue you are experiencing. Looking at the video demo below, you will see the UI is distorted for a while and be normal later, but it seems to be a simulator issue as the other native app has similar behavior (Chrome app)
> 
>  Screen.Recording.2023-10-30.at.11.38.12.mov 
> This may be a device-specific issue. What is your device model? Could you share a recorded video for this?
> 
> And please confirm if this issue occurs on a new Flutter project. Thanks!
Thanks for your response. Our project use ScreenUtil to adapt different device size. And when the foldable device change fold status, the font size not update automatically. And the widget which I not use ScreenUtil like your video, the issue will not happened.

**Comment by huycozy** [comment] 2023-11-01 03:44
>Our project use ScreenUtil to adapt different device size. And when the foldable device change fold status, the font size not update automatically. And the widget which I not use ScreenUtil like your video, the issue will not happened.

Looks like you are using a package or your own implementation class. I would suggest you open an issue on package's repository for better support there or ask the same on support channels like StackOverflow for solutions if any.

Closing this issue as it doesn't seem to be a Flutter framework issue. If you still believe this is a bug in the framework, please write in comments and I will reopen this.

**Closed by huycozy** 2023-11-01 03:44 UTC
Labels: in triage
