### ISSUE TITLE
Dartpad example in docs is broken

### ISSUE THREAD

**Issue by justinmc** [flutter/flutter#52766] opened 2020-03-17 22:13 UTC
The Dartpad example for CupertinoContextMenu in the live docs is broken right now: https://master-api.flutter.dev/flutter/cupertino/CupertinoContextMenu-class.html

You should be able to long press on the red square to get the menu to open.  Instead, lots of unhelpful errors show up in the console.

If I run the example in a simulator locally, it works fine.

**Comment by farheen21** [comment] 2020-03-18 18:27
Yeah ...i also observe the same thanks for raising the issue,When we run the code on the dartpad.dev it gives assertion failed error and script error

**Comment by RedBrogdon** [comment] 2020-03-19 20:19
I just tested this in Chrome with the master channel, and I'm seeing a similar exception:

```
══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
The following UnimplementedError was thrown during a scheduler callback:
UnimplementedError

When the exception was thrown, this was the stack:
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 196:49  throw_
lib/_engine/engine/surface/scene_builder.dart 223:5                           pushShaderMask
package:flutter/src/rendering/layer.dart 1855:26                              addToScene
package:flutter/src/rendering/layer.dart 442:5                                [_addToSceneWithRetainedRendering]
package:flutter/src/rendering/layer.dart 1065:14                              addChildrenToScene
package:flutter/src/rendering/layer.dart 1651:5                               addToScene
package:flutter/src/rendering/layer.dart 802:5                                buildScene
package:flutter/src/rendering/view.dart 230:36                                compositeFrame
package:flutter/src/rendering/binding.dart 405:18                             drawFrame
package:flutter/src/widgets/binding.dart 884:13                               drawFrame
package:flutter/src/rendering/binding.dart 283:5                              [_handlePersistentFrameCallback]
package:flutter/src/scheduler/binding.dart 1108:15                            [_invokeFrameCallback]
package:flutter/src/scheduler/binding.dart 1047:9                             handleDrawFrame
package:flutter/src/scheduler/binding.dart 963:5                              [_handleDrawFrame]
lib/_engine/engine.dart 191:21                                                <fn>
════════════════════════════════════════════════════════════════════════════════════════════════════
Another exception was thrown: UnimplementedError
Another exception was thrown: PersistedOffset: is in an unexpected state.
[More instances of the PersistedOffset exception]
```

Flutter doctor output:

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.15.4-pre.180, on Mac OS X 10.15.2 19C57, locale en-US)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.6)
[✓] IntelliJ IDEA Community Edition (version 2019.2.4)
[✓] VS Code (version 1.42.1)
[✓] Connected device (2 available)
```

**Comment by ferhatb** [comment] 2020-03-19 20:20
Web doesn't support pushShaderMask api yet. Workaround is to use regular context menu with if (kIsWeb) check.

**Comment by yjbanov** [comment] 2020-03-19 22:28
Sounds like duplicate of https://github.com/flutter/flutter/issues/44152

**Closed by yjbanov** 2020-03-19 22:28 UTC
Labels: d: api docs, ☸ platform-web

**Comment by justinmc** [comment] 2020-03-20 17:25
Let me know if there's anything I can do in the meantime before ShaderMask is supported.  I could conditionally remove the ShaderMask when the platform is web, or I could just turn the dartpad example into a code snippet for now.

**Comment by ferhatb** [comment] 2020-03-20 17:36
> Let me know if there's anything I can do in the meantime before ShaderMask is supported. I could conditionally remove the ShaderMask when the platform is web, or I could just turn the dartpad example into a code snippet for now.

@justinmc , yes would be great to conditionally remove for web for now, file an issue and add comment in code referring to that issue to revert in the future. Would be happy to review PR.

**Comment by justinmc** [comment] 2020-03-20 21:32
@ferhatb Thanks, great idea!  [PR](https://github.com/flutter/flutter/pull/52977) and [issue](https://github.com/flutter/flutter/issues/52967).

**Comment by ferhatb** [comment] 2020-03-20 22:35
Thank you! PR approved.
