### ISSUE TITLE
TextFormField backspace delete 2 characters at a time

### ISSUE THREAD

**Issue by lucasjinreal** [flutter/flutter#71404] opened 2020-11-30 13:45 UTC
Hi, I am using TextFormField input Chinese characters, but when using backspace deleting, everytime 2 characters will remove.

my TextFormField seems normal:

```dart
TextFormField(
                                      initialValue: tasks.title,
                                      decoration: new InputDecoration(
                                        contentPadding: EdgeInsets.all(0),
                                        hintText: "任务标题",
                                        hintStyle: TextStyle(
                                            fontWeight: FontWeight.bold,
                                            fontFamily:
                                                GlobalSettings.isUsingYishi
                                                    ? FONT_FANGSONG
                                                    : FONT_NAME,
                                            fontSize: 25),

                                        labelStyle: TextStyle(
                                            color: Color(tasks.projectColor),
                                            fontWeight: FontWeight.bold,
                                            fontFamily:
                                                GlobalSettings.isUsingYishi
                                                    ? FONT_FANGSONG
                                                    : FONT_NAME,
                                            fontSize: 25),
                                        focusColor: Color(tasks.projectColor),
                                        focusedErrorBorder: OutlineInputBorder(
                                            borderRadius:
                                                BorderRadius.circular(15),
                                            borderSide: BorderSide.none),
                                        border: OutlineInputBorder(
                                            borderRadius:
                                                BorderRadius.circular(15),
                                            borderSide: BorderSide.none),
                                        // border: new OutlineInputBorder(
                                        //     borderSide: new BorderSide(color: Colors.teal)),
                                      ),
                                      validator: (value) {
                                        var msg =
                                            value.isEmpty ? "标题不能为空" : null;
                                        return msg;
                                      },
                                      onChanged: (v) {
                                        createTaskBloc.updateTasksTitle(v);
                                      },
                                      maxLines: null,
                                      keyboardType: TextInputType.text,
                                      textInputAction: TextInputAction.done,
                                      style: TextStyle(
                                          fontFamily:
                                              GlobalSettings.isUsingYishi
                                                  ? FONT_FANGSONG
                                                  : FONT_NAME,
                                          color: Color(tasks.projectColor),
                                          fontWeight: FontWeight.bold,
                                          fontSize: 25),
                                    );
                                  },
                                )
```

Does anybody knows why????????????????????

**Comment by TahaTesser** [comment] 2020-11-30 14:11
Hi @jinfagang 
Are you experiencing this issue on iOS or Android? Emulator or physical device? 
Can you please provide your `flutter doctor -v`?
Thank you

**Comment by HansMuller** [comment] 2020-11-30 19:30
CC @LongCatIsLooong

**Comment by HansMuller** [comment] 2020-12-01 19:39
Also reported via Google internal issue: b/174115450

**Comment by LongCatIsLooong** [comment] 2020-12-01 19:40
Duplicate of https://github.com/flutter/flutter/issues/70744?

**Comment by jinfagang** [comment] 2020-12-02 03:09
@LongCatIsLooong @tadaspetra @TahaTesser  thanks for your response.
I think it's on both, but I can confirm it's definitely on Android.

Also, it seems happend with Chinese input, but sometimes English alphabetas would also happend.

**Comment by jinfagang** [comment] 2020-12-02 03:11
Also, I seems not got this except I switched to master and it happened for some reason.

Does the master fixed it now? I shall upgrade my flutter?

**Comment by TahaTesser** [comment] 2020-12-02 07:36
Hi @jinfagang 
Can you please provide your `flutter doctor -v`?
Not able to reproduce this issue using Chinese simplified input on Android (Gboard)  and iOS on the latest `stable` and `master` channels. Backspace deletes one character at a time

<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: TextFormField(
          decoration: InputDecoration(
            contentPadding: EdgeInsets.all(0),
            hintText: "任务标题",
          ),
          maxLines: null,
          keyboardType: TextInputType.text,
          textInputAction: TextInputAction.done,
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {},
      ),
    );
  }
}

``` 

</details>

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 1.22.4, on macOS 11.0.1 20B29 darwin-x64, locale
    en-GB)
    • Flutter version 1.22.4 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 1aafb3a8b9 (3 weeks ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.0

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

 
[✓] Connected device (2 available)            
    • RMX2001 (mobile)     • EUYTFEUSQSRGDA6D          • android-arm64 • Android
      10 (API 29)
    • Taha’s iPad (mobile) • 00008020-000255113EE8402E • ios           • iOS
      14.2

! Doctor found issues in 1 category.
```

```bash
[✓] Flutter (Channel master, 1.24.0-8.0.pre.406, on macOS 11.0.1 20B29
    darwin-x64, locale en-GB)
    • Flutter version 1.24.0-8.0.pre.406 at
      /Users/tahatesser/Code/flutter_master
    • Framework revision 60bdcf55fe (2 hours ago), 2020-12-01 21:24:21 -0800
    • Engine revision 20caf54969
    • Dart version 2.12.0 (build 2.12.0-76.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (5 available)
    • RMX2001 (mobile)     • EUYTFEUSQSRGDA6D          • android-arm64  •
      Android 10 (API 29)
    • Taha’s iPad (mobile) • 00008020-000255113EE8402E • ios            • iOS
      14.2
    • macOS (desktop)      • macos                     • darwin-x64     • macOS
      11.0.1 20B29 darwin-x64
    • Web Server (web)     • web-server                • web-javascript •
      Flutter Tools
    • Chrome (web)         • chrome                    • web-javascript • Google
      Chrome 87.0.4280.67

• No issues found!
```

</details>

**Comment by jinfagang** [comment] 2020-12-02 07:57
@TahaTesser  Hi, thanks for response. As this thread track: https://github.com/flutter/flutter/issues/70744 it seems happened in master previous, but it may fixed by someone. I am not sure is work on my side. I will test it later and post a video to show it.

**Comment by CNMathon** [comment] 2020-12-03 12:47
I had this problem too. When I delete a Chinese character or a number character, 2 Chinese characters will be deleted.

**Comment by raveesh08** [comment] 2020-12-05 10:06
I'm also facing the same issue, 2 characters ll be deleted at a time...  it seems it happened after I switched to beta version of Flutter SDK..

**Comment by CNMathon** [comment] 2020-12-07 02:31
I've solved it! You just need to switch the Flutter branch to master. At least I solved it this way.

**Comment by rgisi** [comment] 2020-12-08 15:05
I have the same issue when on the beta channel, backspace always deletes two characters. Works correctly on stable channel.

<details>
<summary>Stable channel flutter doctor -v:</summary>
flutter doctor -v
[√] Flutter (Channel stable, 1.22.4, on Microsoft Windows [Version 10.0.19041.630], locale de-CH)
    • Flutter version 1.22.4 at C:\flutter
    • Framework revision 1aafb3a8b9 (4 weeks ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\gregr\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = C:\Users\gregr\AppData\Local\Android\sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (1 available)
    • LG H870 (mobile) • LGH870f4432d2 • android-arm64 • Android 9 (API 28)

! Doctor found issues in 1 category.
</details>
<details>
<summary>Beta channel flutter doctor -v:</summary>
flutter doctor -v
[√] Flutter (Channel beta, 1.24.0-10.2.pre, on Microsoft Windows [Version 10.0.19041.630], locale de-CH)
    • Flutter version 1.24.0-10.2.pre at C:\flutter
    • Framework revision 022b333a08 (3 weeks ago), 2020-11-18 11:35:09 -0800
    • Engine revision 07c1eed46b
    • Dart version 2.12.0 (build 2.12.0-29.10.beta)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\gregr\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = C:\Users\gregr\AppData\Local\Android\sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (4 available)
    • LG H870 (mobile) • LGH870f4432d2 • android-arm64  • Android 9 (API 28)
    • Web Server (web) • web-server    • web-javascript • Flutter Tools
    • Chrome (web)     • chrome        • web-javascript • Google Chrome 86.0.4240.198
    • Edge (web)       • edge          • web-javascript • Microsoft Edge 85.0.564.63

• No issues found!
</details>

**Comment by TahaTesser** [comment] 2020-12-09 09:22
@rgisi  @raveesh08 
Does it reproduce on the latest flutter `master` as well?

**Comment by rgisi** [comment] 2020-12-09 10:52
@TahaTesser master channel seems to work fine.
(I could not build my original project on master channel due to some AndroidX problems, but used an empty new flutter project and a `TextField()` in it.)

2 characters got deleted when on the beta channel, but not when on master channel.

<details>
<summary>flutter doctor -v</summary>
[√] Flutter (Channel master, 1.25.0-5.0.pre.125, on Microsoft Windows [Version 10.0.19041.630], locale de-CH)
    • Flutter version 1.25.0-5.0.pre.125 at C:\flutter
    • Framework revision a12e2a473a (7 hours ago), 2020-12-08 23:13:04 -0500
    • Engine revision df39e5c515
    • Dart version 2.12.0 (build 2.12.0-133.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\gregr\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = C:\Users\gregr\AppData\Local\Android\sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (3 available)
    • LG H870 (mobile) • LGH870f4432d2 • android-arm64  • Android 9 (API 28)
    • Chrome (web)     • chrome        • web-javascript • Google Chrome 86.0.4240.198
    • Edge (web)       • edge          • web-javascript • Microsoft Edge 85.0.564.63

• No issues found!
</details>

**Comment by raveesh08** [comment] 2020-12-11 04:22
@TahaTesser Currently i like to continue with beta version only i can't switch to master version. but i found out one more clue regarding that issue... 
issue happens when i set `keyboardType` property of `TextFormField`
if not set then it seems to be working fine with beta.

**Comment by raveesh08** [comment] 2020-12-11 04:24
> ```dart
>  keyboardType: TextInputType.text,
> ```

try removing `keyboardType` property of `TextFormField` it seems to be working fine..

**Comment by alibt** [comment] 2020-12-12 09:49
got the same issue on beta
arabic and English characters 

flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 1.24.0-10.2.pre, on Linux, locale en_US.UTF-8)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] Connected device (3 available)

**switching to channel master solved the issue** :
flutter doctor
[✓] Flutter (Channel beta, 1.24.0-10.2.pre, on Linux, locale en_US.UTF-8)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] Connected device (3 available)

**Comment by CoderJava** [comment] 2020-12-14 15:32
I got the same issue. 

![bug_textfield](https://user-images.githubusercontent.com/17062085/102100423-fd723b00-3e5b-11eb-8c43-58c4874113f6.gif)

flutter doctor -v
```
[✓] Flutter (Channel beta, 1.24.0-10.2.pre, on Mac OS X 10.15.7 19H2 darwin-x64, locale en-EC)
    • Flutter version 1.24.0-10.2.pre at /Users/yudisetiawan/fvm/versions/beta
    • Framework revision 022b333a08 (4 weeks ago), 2020-11-18 11:35:09 -0800
    • Engine revision 07c1eed46b
    • Dart version 2.12.0 (build 2.12.0-29.10.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/yudisetiawan/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.50.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (3 available)
    • Redmi Note 4 (mobile) • faa168ce9804 • android-arm64  • Android 7.0 (API 24)
    • Web Server (web)      • web-server   • web-javascript • Flutter Tools
    • Chrome (web)          • chrome       • web-javascript • Google Chrome 87.0.4280.88

• No issues found!
```

**Comment by CoderJava** [comment] 2020-12-14 15:34
> > ```dart
> >  keyboardType: TextInputType.text,
> > ```
> 
> @jinfagang try removing `keyboardType` property of `TextFormField` it seems to be working fine..

It's not working for me.

**Comment by abjorck** [comment] 2020-12-15 14:52
Same. However the problem only occurs for me when I'm using the physical computer keyboard (with the emulator). The on screen keyboard works correct for me. :shrug:

**Comment by beingsalmanshaikh** [comment] 2020-12-25 21:28
Facing the same issue when using 
`TextInputType.phone` or `TextInputType.number`.

flutter doctor -v
```
[✓] Flutter (Channel beta, 1.24.0-10.2.pre, on macOS 11.1 20C69 darwin-x64, locale en-GB)
    • Flutter version 1.24.0-10.2.pre at /Users/admin/flutter_sdk/flutter
    • Framework revision 022b333a08 (5 weeks ago), 2020-11-18 11:35:09 -0800
    • Engine revision 07c1eed46b
    • Dart version 2.12.0 (build 2.12.0-29.10.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/admin/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Connected device (3 available)
    • GM1911 (mobile)  • 1ba8e297   • android-arm64  • Android 10 (API 29)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 87.0.4280.88

• No issues found!
```

**Comment by jmatsu** [comment] 2021-01-14 16:49
JFYI, it seems the root cause has been already fixed in the flutter engine and the fix is available since `1.25.0-4.0.pre`. I'm not familiar with the engine, but I guess no workaround is available on the app-code. The only way is to use the current master channel or newer tagged versions than `1.24.0-10.2.pre`. 

ref: 

- https://github.com/flutter/flutter/pull/71161 merged the fix into this repository
- https://github.com/flutter/flutter/compare/1.24.0-10.2.pre...1.25.0-4.0.pre

**Comment by piedcipher** [comment] 2021-03-19 19:30
I'm facing this in stable branch while building linux desktop app.

**Comment by vgobbi8** [comment] 2021-04-01 18:54
Me too, but in windows 10
Flutter channel stable 2.0.3

**Comment by gnprice** [comment] 2023-05-15 23:48
This issue seems to no longer reproduce.

It looks like there may have been a couple of different issues in this thread. But I don't reproduce the issue either with `TextField(keyboardType: TextInputType.text)` or `TextField(keyboardType: TextInputType.number)`. That's using a hardware keyboard's backspace key, in an Android emulator, on a current Flutter version from main/master.

If someone's still seeing an issue like this one, please file it as a fresh issue thread, filling in all the information requested in the issue template, and then someone can take a look.

**Closed by gnprice** 2023-05-15 23:48 UTC
Labels: a: text input, severe: regression, framework, f: material design, passed first triage, found in release: 1.22, found in release: 1.24
