### ISSUE TITLE
No podspec found for `connectivity_for_web` in `.symlinks/plugins/connectivity_for_web/ios`

### ISSUE THREAD

**Issue by kapilkiwi** [flutter/flutter#85211] opened 2021-06-24 10:38 UTC
After updating **connectivity** dependency get this issue every time  on Pod Install.

**Comment by aDrIaNo34500** [comment] 2021-06-24 10:57
Ère

**Comment by stuartmorgan** [comment] 2021-06-24 11:14
Duplicate of https://github.com/flutter/flutter/issues/79330

See https://github.com/flutter/flutter/issues/45197#issuecomment-642201335 for instructions to update your project.

**Closed by stuartmorgan** 2021-06-24 11:14 UTC
