### ISSUE TITLE
Android Studio File/Project Structure settings missing

### ISSUE THREAD

**Issue by AndrewByk** [flutter/flutter#68021] opened 2020-10-13 13:51 UTC
After Android Studio 4.1. update I missing Project Structure option in File menu 

![pic5](https://user-images.githubusercontent.com/53439982/95869368-31998480-0d63-11eb-82a4-ce1adf135411.png)

And for each new project, I need to manually update Gradle to 6.+
![pic7](https://user-images.githubusercontent.com/53439982/95869572-6dcce500-0d63-11eb-8288-15937c363d6d.png)

flutter doctor -v
![pic0](https://user-images.githubusercontent.com/53439982/95869739-9bb22980-0d63-11eb-9050-8ff3e2086af4.png)

**Comment by pedromassangocode** [comment] 2020-10-13 13:59
Hi @AndrewByk 
Following the indication of [jetbrains' Flutter plugin](https://plugins.jetbrains.com/plugin/9212-flutter), the correct way to address the problem is to open an issue in the dedicated [repository](https://github.com/flutter/flutter-intellij/issues).
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by pedromassangocode** 2020-10-13 13:59 UTC

**Comment by AndrewByk** [comment] 2020-10-13 14:42
People comments similar problems here, so I don't think you should close my case

**Comment by pedromassangocode** [comment] 2020-10-14 06:46
Hi @AndrewByk 
Android Studio is based on IntelliJ and the Flutter plugin is the same.
This issue is not related to Flutter that is why you should open the issue in the Plugin's repository.
