### ISSUE TITLE
flutter app socket exception when it running

### ISSUE THREAD

**Issue by shaomaicheng** [flutter/flutter#71769] opened 2020-12-05 07:41 UTC
hello, I have a problem when I run my Flutter Application in Android Studio:

```
Error connecting to the service protocol: failed to connect to http://127.0.0.1:61397/JGLqojHvWac=/
vm-service: Error: Unhandled exception:
WebSocketException: Invalid WebSocket upgrade request

[ERROR:flutter/runtime/dart_isolate.cc(993)] Unhandled exception:
WebSocketException: Invalid WebSocket upgrade request
```

but I can run success in my Terminal。

this is my "Flutter doctor":

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, 1.25.0-4.0.pre, on macOS 11.0.1 20B50 darwin-x64, locale
    zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.51.1)
[✓] Proxy Configuration
[✓] Connected device (2 available)
```

**Comment by shaomaicheng** [comment] 2020-12-05 07:43
At first I thought may be I do not setup noproxy, but i have no_proxy='127.0.0.1,localhost' in terminal and android studio...so i can not found the reason...

**Comment by iapicca** [comment] 2020-12-05 20:36
@shaomaicheng 
can you please provide a minimal reproducible code sample

**Comment by shaomaicheng** [comment] 2020-12-06 01:28
> @shaomaicheng
> can you please provide a minimal reproducible code sample

any project can recurrence it

**Comment by tommokmok** [comment] 2020-12-06 05:18
@shaomaicheng 
As iapicca suggested, please provide sample code about your issue. 
Otherwise, we can't help you just base on your logs.

**Comment by shaomaicheng** [comment] 2020-12-07 06:37
> @shaomaicheng
> As iapicca suggested, please provide sample code about your issue.
> Otherwise, we can't help you just base on your logs.

any project can recurrence it.
also include  use `flutter create` create a new project

**Comment by darshankawar** [comment] 2020-12-07 08:13
@shaomaicheng 
You may try to run `flutter clean` to see if it helps. Also check [this](https://github.com/flutter/flutter/issues/16875#issuecomment-384758566) and [this](https://github.com/flutter/flutter/issues/18776#issuecomment-399806400) comment to see if that works for you.

**Comment by tommokmok** [comment] 2020-12-07 12:35
@shaomaicheng,
Sorry that I miss understand you.
Originally, I think the issue is related to your projects that do some web requests and cause the problem.
However, it is not the case.

**Comment by shaomaicheng** [comment] 2020-12-08 16:04
> @shaomaicheng
> You may try to run `flutter clean` to see if it helps. Also check [this](https://github.com/flutter/flutter/issues/16875#issuecomment-384758566) and [this](https://github.com/flutter/flutter/issues/18776#issuecomment-399806400) comment to see if that works for you.
thank your! now i can run my app in Android Studio. but I have a new problem , in my ios simulator, i can not build my flutter app:

this is `flutter build ios --debug --verbose` 's input 👍 
          ↳
[   +1 ms] 
               [!] Invalid `Podfile` file: no implicit conversion of nil into String.
           
                #  from /Users/chenglei01/private/fataccount/ios/Podfile:57
                #  -------------------------------------------
                #      unless File.exist?(copied_framework_path)
                >        FileUtils.cp_r(File.join(cached_framework_dir, 'Flutter.framework'), copied_flutter_dir)
                #      end
                #  -------------------------------------------
           
               /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.10.0/lib/cocoapods-core/podfile.rb:318:in `rescue in block in from_ruby'
               /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.10.0/lib/cocoapods-core/podfile.rb:312:in `block in from_ruby'
               /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.10.0/lib/cocoapods-core/podfile.rb:50:in `instance_eval'
               /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.10.0/lib/cocoapods-core/podfile.rb:50:in `initialize'
               /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.10.0/lib/cocoapods-core/podfile.rb:310:in `new'
               /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.10.0/lib/cocoapods-core/podfile.rb:310:in `from_ruby'
               /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.10.0/lib/cocoapods-core/podfile.rb:276:in `from_file'
               /Users/chenglei01/.gem/ruby/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/config.rb:205:in `podfile'
               /Users/chenglei01/.gem/ruby/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/command.rb:160:in `verify_podfile_exists!'
               /Users/chenglei01/.gem/ruby/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/command/install.rb:46:in `run'
               /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
               /Users/chenglei01/.gem/ruby/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/command.rb:52:in `run'
               /Users/chenglei01/.gem/ruby/2.6.0/gems/cocoapods-1.10.0/bin/pod:55:in `<top (required)>'
               /usr/local/bin/pod:23:in `load'
               /usr/local/bin/pod:23:in `<main>'
           
[   +9 ms] "flutter ios" took 11,508ms.
[   +8 ms] Error running pod install

```
how can i resolve it?
and it can work to build macos ...

**Comment by darshankawar** [comment] 2020-12-09 06:26
@shaomaicheng 
Is your original issue related to socket exception has been resolved or not yet ?
The latest log shows ` Invalid Podfile file: no implicit conversion of nil into String.` which seem to be a different issue.

**Comment by shaomaicheng** [comment] 2020-12-09 07:26
> @shaomaicheng
> Is your original issue related to socket exception has been resolved or not yet ?
> The latest log shows ` Invalid Podfile file: no implicit conversion of nil into String.` which seem to be a different issue.

yes, this is a new issue on ios,  socket exception is resloved after I use `flutter clean`

**Comment by darshankawar** [comment] 2020-12-09 13:12
@shaomaicheng 
I'd suggest you to open a new issue and provide all required details to better address your new issue.
I am going ahead and closing this since your original issue has been resolved per your comment above.

**Closed by darshankawar** 2020-12-09 13:12 UTC
Labels: in triage

**Comment by aboutmydreams** [comment] 2020-12-31 21:42
> > @shaomaicheng
> > You may try to run `flutter clean` to see if it helps. Also check [this](https://github.com/flutter/flutter/issues/16875#issuecomment-384758566) and [this](https://github.com/flutter/flutter/issues/18776#issuecomment-399806400) comment to see if that works for you.
> > thank your! now i can run my app in Android Studio. but I have a new problem , in my ios simulator, i can not build my flutter app:
> 
> this is `flutter build ios --debug --verbose` 's input 👍
> ↳
> [ +1 ms]
> [!] Invalid `Podfile` file: no implicit conversion of nil into String.
> 
> ```
>             #  from /Users/chenglei01/private/fataccount/ios/Podfile:57
>             #  -------------------------------------------
>             #      unless File.exist?(copied_framework_path)
>             >        FileUtils.cp_r(File.join(cached_framework_dir, 'Flutter.framework'), copied_flutter_dir)
>             #      end
>             #  -------------------------------------------
>        
>            /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.10.0/lib/cocoapods-core/podfile.rb:318:in `rescue in block in from_ruby'
>            /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.10.0/lib/cocoapods-core/podfile.rb:312:in `block in from_ruby'
>            /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.10.0/lib/cocoapods-core/podfile.rb:50:in `instance_eval'
>            /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.10.0/lib/cocoapods-core/podfile.rb:50:in `initialize'
>            /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.10.0/lib/cocoapods-core/podfile.rb:310:in `new'
>            /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.10.0/lib/cocoapods-core/podfile.rb:310:in `from_ruby'
>            /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.10.0/lib/cocoapods-core/podfile.rb:276:in `from_file'
>            /Users/chenglei01/.gem/ruby/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/config.rb:205:in `podfile'
>            /Users/chenglei01/.gem/ruby/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/command.rb:160:in `verify_podfile_exists!'
>            /Users/chenglei01/.gem/ruby/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/command/install.rb:46:in `run'
>            /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
>            /Users/chenglei01/.gem/ruby/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/command.rb:52:in `run'
>            /Users/chenglei01/.gem/ruby/2.6.0/gems/cocoapods-1.10.0/bin/pod:55:in `<top (required)>'
>            /usr/local/bin/pod:23:in `load'
>            /usr/local/bin/pod:23:in `<main>'
> ```
> 
> [ +9 ms] "flutter ios" took 11,508ms.
> [ +8 ms] Error running pod install
> 
> ```
> how can i resolve it?
> and it can work to build macos ...
> ```

do you solve this problem ? I meet it today
