### ISSUE TITLE
Flutter Android Alarm Manager Null Activity

### ISSUE THREAD

**Issue by kelvinkoh0308** [flutter/flutter#74879] opened 2021-01-28 07:05 UTC
Hi,

Currently I am using one plugin (flutter_nearby_messages_api) in the callback of the alarm manager. However, it failed to call the function as the activity is null. Thus I want to ask whether it is possible to create activity inside alarm manager so that the function of the plugin can be called successfully.

I have also tried using dart Timer which will create isolate like the alarm manager and it works well. However, the timer cannot work in background.

The exception log is shown below:

E/MethodChannel#flutter_nearby_messages_api(19932): Failed to handle method call
E/MethodChannel#flutter_nearby_messages_api(19932): java.lang.NullPointerException: Activity must not be null
E/MethodChannel#flutter_nearby_messages_api(19932): 	at com.google.android.gms.common.internal.Preconditions.checkNotNull(com.google.android.gms:play-services-basement@@17.1.0:11)
E/MethodChannel#flutter_nearby_messages_api(19932): 	at com.google.android.gms.nearby.Nearby.getMessagesClient(Unknown Source:2)
E/MethodChannel#flutter_nearby_messages_api(19932): 	at vn.tmhtechlab.flutter_nearby_messages_api.FlutterNearbyMessagesApiPlugin.unPublish(FlutterNearbyMessagesApiPlugin.java:151)
E/MethodChannel#flutter_nearby_messages_api(19932): 	at vn.tmhtechlab.flutter_nearby_messages_api.FlutterNearbyMessagesApiPlugin.publish(FlutterNearbyMessagesApiPlugin.java:121)
E/MethodChannel#flutter_nearby_messages_api(19932): 	at vn.tmhtechlab.flutter_nearby_messages_api.FlutterNearbyMessagesApiPlugin.onMethodCall(FlutterNearbyMessagesApiPlugin.java:208)
E/MethodChannel#flutter_nearby_messages_api(19932): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/MethodChannel#flutter_nearby_messages_api(19932): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#flutter_nearby_messages_api(19932): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
E/MethodChannel#flutter_nearby_messages_api(19932): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#flutter_nearby_messages_api(19932): 	at android.os.MessageQueue.next(MessageQueue.java:345)
E/MethodChannel#flutter_nearby_messages_api(19932): 	at android.os.Looper.loop(Looper.java:194)
E/MethodChannel#flutter_nearby_messages_api(19932): 	at android.app.ActivityThread.main(ActivityThread.java:7604)
E/MethodChannel#flutter_nearby_messages_api(19932): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter_nearby_messages_api(19932): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
E/MethodChannel#flutter_nearby_messages_api(19932): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:953)
E/flutter (19932): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: PlatformException(error, Activity must not be null, null, java.lang.NullPointerException: Activity must not be null
E/flutter (19932): 	at com.google.android.gms.common.internal.Preconditions.checkNotNull(com.google.android.gms:play-services-basement@@17.1.0:11)
E/flutter (19932): 	at com.google.android.gms.nearby.Nearby.getMessagesClient(Unknown Source:2)
E/flutter (19932): 	at vn.tmhtechlab.flutter_nearby_messages_api.FlutterNearbyMessagesApiPlugin.unPublish(FlutterNearbyMessagesApiPlugin.java:151)
E/flutter (19932): 	at vn.tmhtechlab.flutter_nearby_messages_api.FlutterNearbyMessagesApiPlugin.publish(FlutterNearbyMessagesApiPlugin.java:121)
E/flutter (19932): 	at vn.tmhtechlab.flutter_nearby_messages_api.FlutterNearbyMessagesApiPlugin.onMethodCall(FlutterNearbyMessagesApiPlugin.java:208)
E/flutter (19932): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/flutter (19932): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/flutter (19932): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
E/flutter (19932): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (19932): 	at android.os.MessageQueue.next(MessageQueue.java:345)
E/flutter (19932): 	at android.os.Looper.loop(Looper.java:194)
E/flutter (19932): 	at android.app.ActivityThread.main(ActivityThread.java:7604)
E/flutter (19932): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (19932): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
E/flutter (19932): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:953)
E/flutter (19932): )
E/flutter (19932): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:582:7)
E/flutter (19932): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159:18)
E/flutter (19932): <asynchronous suspension>
E/flutter (19932): #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
E/flutter (19932): #3      FlutterNearbyMessagesApi.publish (package:flutter_nearby_messages_api/flutter_nearby_messages_api.dart:96:20)
E/flutter (19932): #4      update (package:sidp/screen/test_screen.dart:35:27)
E/flutter (19932): <asynchronous suspension>
E/flutter (19932): #5      _alarmManagerCallbackDispatcher.<anonymous closure> (package:android_alarm_manager/android_alarm_manager.dart:43:14)
E/flutter (19932): #6      MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:430:55)
E/flutter (19932): #7      MethodChannel.setMethodCallHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:383:34)
E/flutter (19932): #8      _DefaultBinaryMessenger.handlePlatformMessage (package:flutter/src/services/binding.dart:283:33)
E/flutter (19932): #9      _invoke3.<anonymous closure> (dart:ui/hooks.dart:280:15)
E/flutter (19932): #10     _rootRun (dart:async/zone.dart:1190:13)
E/flutter (19932): #11     _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter (19932): #12     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
E/flutter (19932): #13     _invoke3 (dart:ui/hooks.dart:279:10)
E/flutter (19932): #14     _dispatchPlatformMessage (dart:ui/hooks.dart:154:5)
E/flutter (19932):

**Comment by pedromassangocode** [comment] 2021-01-28 08:26
Hi @kelvinkoh0308 
Can you please provide your `flutter doctor -v`,  your `pubspec.yaml`
and a minimal reproducible code sample that does not use 3rd party plugins?
Thank you

**Comment by kelvinkoh0308** [comment] 2021-01-28 09:14
Hi,
It works well without plugin and also for the plugin that does not require activity to be created. The problem now for the plugin I am using is that it requires activity to be created.

minimal reproducible code without plugins:
```
Future<void> update() async {
  print("hello");
}
Future<void> initialize() async {
    await AndroidAlarmManager.initialize();
    AndroidAlarmManager.periodic(const Duration(seconds: 30), 0, update,
        exact: true, wakeup: true);
  }
```
[pubspec.txt](https://github.com/flutter/flutter/files/5885989/pubspec.txt)
[doctor.txt](https://github.com/flutter/flutter/files/5885990/doctor.txt)

**Comment by pedromassangocode** [comment] 2021-01-28 10:44
Hi @kelvinkoh0308 
Sorry, I cannot understand what this issue is about. is there a problem with the `android_alarm_manager` plugin?
What is the expected vs actual result of the code above?

**Comment by kelvinkoh0308** [comment] 2021-01-28 12:58
The problem is that the Alarm manager does not create android activity. The plugin I using now require the activity to be created.

E/MethodChannel#flutter_nearby_messages_api(19932): Failed to handle method call
E/MethodChannel#flutter_nearby_messages_api(19932): java.lang.NullPointerException: Activity must not be null

As you can see from the exception log, no activity is created inside the alarm manager.

**Comment by pedromassangocode** [comment] 2021-01-28 14:18
Hi @kelvinkoh0308 
From what I can see, the issue is related to a 3rd party plugin rather than to Flutter itself. Please open the issue in the dedicated repository.
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by pedromassangocode** 2021-01-28 14:18 UTC
Labels: in triage
