### ISSUE TITLE
Live HLS stream breaking on flutter_video

### ISSUE THREAD

**Issue by ollydixon** [flutter/flutter#55312] opened 2020-04-21 18:36 UTC
Trying to implement HLS streams for Flutter, seems like there is no solution...

Same as this issue which is closed for some reason...
https://github.com/flutter/flutter/issues/48053

Breaking stream example with no duration: http://static.france24.com/live/F24_EN_LO_HLS/live_web.m3u8

Working sample with asset size
http://qthttp.apple.com.edgesuite.net/1010qwoeiuryfg/sl.m3u8

You can check the stream in Safari on Mac (Doesn't work for Windows).

Also if anyone could give me some pointer on how we can copy a Flutter plugin easily?

The code is simple:

```
  VideoPlayerController _controller;

  @override
  void initState() {
    super.initState();
    print(widget.streamUrl);
    _controller = VideoPlayerController.network('http://static.france24.com/live/F24_EN_LO_HLS/live_web.m3u8', formatHint: VideoFormat.hls)
      ..initialize().then((_) {
        setState(() {});
        return Future.delayed(Duration(
          milliseconds: 500,
        ));
      }).then((v) {
        _controller.play();
      }).catchError((e) {
        print('Unable to play stream');
        print(e);
      });
  }

  @override
  void dispose() {
    super.dispose();
    _controller.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return _controller.value.initialized
        ? AspectRatio(
            aspectRatio: _controller.value.aspectRatio,
            child: VideoPlayer(
              _controller,
            ),
          )
        : Container();
  }
```

**Comment by VladyslavBondarenko** [comment] 2020-04-22 08:18
Hi @ollydixon 
how is your issue related to https://github.com/flutter/flutter/issues/48053?
are you getting the same `The getter '_duration' was called on null` error?

On iOS I can't see errors, but yes, only the second link can be played.

I would close it as duplicate of https://github.com/flutter/flutter/issues/48670

**Comment by ollydixon** [comment] 2020-04-22 08:21
#48670

**Closed** 2020-04-22 08:21 UTC
Labels: waiting for customer response
