### ISSUE TITLE
DropDownMenu does not filter/search on Android but works on Desktop

### ISSUE THREAD

**Issue by muchirajunior** [flutter/flutter#138343] opened 2023-11-13 13:08 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

When you create a DropDownMenu and supply it with fields on Android it doses not allow you to filter like on other platforms

### Expected results

Filter Should work same as Desktop 

### Actual results

The Widget does not trigger filter 

### Code sample

```Dart
import 'package:flutter/material.dart';

class Fruit{
  int? id;
  String? name;

  Fruit({this.id, this.name});
}

class Home extends StatefulWidget {
  const Home({super.key});

  @override
  State<Home> createState() => _HomeState();
}

class _HomeState extends State<Home> {
  var fruits=[
     Fruit(id: 1,name: 'passion'),
     Fruit(id: 1,name: 'apple'),
     Fruit(id: 1,name: 'banana'),
     Fruit(id: 1,name: 'grapes'),
     Fruit(id: 1,name: 'strawberry'),
     Fruit(id: 1,name: 'water melons'),
     Fruit(id: 1,name: 'mangos')
    ];

  var selectedFruit;

  @override
  Widget build(BuildContext context) {
    return  Scaffold(

      appBar: AppBar(title: const Text('Flutter Demo'),elevation: 3,),

      body: Container(
        padding: const EdgeInsets.all(10),
        width: double.infinity,
        // height: double.infinity,
        child: DropdownMenu(
          label: const Text('select fruit'),
          controller: TextEditingController(),
          enableSearch: true,
          menuHeight: 200,
          dropdownMenuEntries: fruits.map((fruit) => DropdownMenuEntry(
            value: fruit, label: fruit.name!
            )).toList(),
        ),
      ),
    );
  }
}
```

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

on android 
![image](https://github.com/flutter/flutter/assets/56454064/eac4f7f7-f2ea-47ed-8fe9-fb447ec5456b)

on desktop
![image](https://github.com/flutter/flutter/assets/56454064/701073c0-7259-45b1-860b-e9c144204deb)

### Flutter Doctor output

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.0, on Kali GNU/Linux Rolling 6.0.0-kali3-amd64, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.77.3)
[✓] Connected device (2 available)
[✓] Network resources

! Doctor found issues in 1 category.
```

**Comment by rydmike** [comment] 2023-11-13 13:54
I tested the sample on stable 3.13, got this:

Web and macOS build: Can enter text and search. (Did not try Linux and Windows builds).
Android and iOS build: Cannot enter text and search.

Switching to master and trying there as well, maybe it is fixed there. Will see soon and edit this.

**Comment by muchirajunior** [comment] 2023-11-13 14:07
okey thanks, i will be waiting for your feedback

**Comment by rydmike** [comment] 2023-11-13 14:27
This difference in behavior and issue is caused by these lines that sets `canRequestFocus` and `enableInteractiveSelection` for the `TextField` in the built `DropdownMenu`:

https://github.com/flutter/flutter/blob/4e77e7b10c4a710b82fa553e6deb7031c3b1fd6f/packages/flutter/lib/src/material/dropdown_menu.dart#L664

```dart
 final Widget textField = TextField(
    key: _anchorKey,
    mouseCursor: effectiveMouseCursor,
    canRequestFocus: canRequestFocus(),
    enableInteractiveSelection: canRequestFocus(),
    textAlignVertical: TextAlignVertical.center,
    style: effectiveTextStyle,
    controller: _textEditingController,
```

The `canRequestFocus()` then does this:

https://github.com/flutter/flutter/blob/4e77e7b10c4a710b82fa553e6deb7031c3b1fd6f/packages/flutter/lib/src/material/dropdown_menu.dart#L404C1-L419C4

```dart
  bool canRequestFocus() {
    if (widget.requestFocusOnTap != null) {
      return widget.requestFocusOnTap!;
    }

    switch (Theme.of(context).platform) {
      case TargetPlatform.iOS:
      case TargetPlatform.android:
      case TargetPlatform.fuchsia:
        return false;
      case TargetPlatform.macOS:
      case TargetPlatform.linux:
      case TargetPlatform.windows:
        return true;
    }
  }
```

If you set it to return `true` for all platforms, it works as **expected**.

Why it sets to `false` for iOS, Android and Fuchsia I do not know. Does not make sense to me.

However, if that is required, maybe `canRequestFocus` should be a property, also in theme not just widget. 

Then you can set to `true/false` as needed and if not defined it falls back to the current function.

Although I don't know why you would not want to use it with the search, but OK sure, for a locked simple dropdown feature it makes sense, but then that should also be supported on desktop platforms, so the config option makes sense. 

Regardless, the different default behavior on the platforms is very confusing.

**Comment by muchirajunior** [comment] 2023-11-13 16:39
i got it, when you set requestFocus onTap to true the edit never exits even when you press complete on the keyboard or enter. but i resolved with this 

```Dart
DropdownMenu(
          label: const Text('select fruit'),
          controller: TextEditingController(),
          onSelected: (value) {
            FocusScope.of(context).unfocus();
          },
          enableSearch: true,
          menuHeight: 200,
          requestFocusOnTap: true,
          dropdownMenuEntries: fruits.map((fruit) => DropdownMenuEntry(
            value: fruit, label: fruit.name!
            )).toList(),
        ),
````

this will remove all the focus once you select or press enter

**Comment by muchirajunior** [comment] 2023-11-13 19:03
@rydmike it's also good to note that there is an overflow of the drop menu when the label string is too long, I think the menu entry is the one supposed to overflow not the whole menu.

In that case having label overflow options just like text overflow would be great

**Comment by huycozy** [comment] 2023-11-14 09:19
@muchirajunior For the initial issue, it was a suggestion from https://github.com/flutter/flutter/issues/116587. Adding `requestFocusOnTap` will make it work on mobile platforms.
This change is also added to sample code at [DropdownMenu](https://master-api.flutter.dev/flutter/material/DropdownMenu-class.html) (only available on master API docs currently) (related issue: https://github.com/flutter/flutter/issues/127672).

For the overflow issue, please file a new issue for that. Thanks!

Closing the issue as solved.

**Closed by huycozy** 2023-11-14 09:19 UTC
Labels: in triage
