### ISSUE TITLE
Flutter does not print values that i've assigned to it

### ISSUE THREAD

**Issue by Nathan-Rambalducci-Ciarama** [flutter/flutter#108475] opened 2022-07-27 20:24 UTC
I'm trying to print two values of a String to check if it is working as inteed. But instead it is trowing an exception of an If method i've put before them and not printing the values at all. Not even after the exception. I think personally it is a bug but i don't know to be certain.

## Steps to Reproduce

Create a Regex method and use it on a String. Then save it's value on another String and try priting them both or just one of them. It doesn't matter if it is the two or one. Then use an If value to check if the String is empty. This one in particular =  if ("YourString".isEmpty) {(...)}.

Here my code sample where it happening to me:

```
if (expression.contains("(R)") &&
                expression.contains("(I)") &&
                ohm) {
              expression = equation.replaceAll("(R)", "*");
              expression = expression.replaceAll("(I)", "*");
              expression = expression.replaceFirst("*", "First");
              expression = expression.replaceAll("*", "Second");
              RegExp fir = RegExp("^[^F]*");
              RegExp sec = RegExp("(?<=t)(.*?)(?=S)");
              double pri = 0;
              double seg = 0;
              pri = double.parse(fir.stringMatch(expression)!);
              seg = double.parse(sec.stringMatch(expression)!);
              if (seg > pri) {
                expression = expression.replaceFirst(fir, seg.toString());
                expression = expression.replaceFirst(sec, pri.toString());
              }
              expression = expression.replaceFirst("First", "*");
              expression = expression.replaceFirst("Second", "");
             // The Above works fine without the code below
              expression2 = equation.replaceFirst("(R)", "RRr");
              expression2 = expression2.replaceFirst("(I)", "IIi");
              RegExp check =
                  RegExp("(?<=r)(.*?)(?=I)"); //check.stringMatch(expression2)!
              String look = check.stringMatch(expression2)!;
              print(check.stringMatch(expression2)!);
              print(look);
              if (look.isEmpty) {
                expression2 = "* ${check.stringMatch(expression2)!}";
              } else {
                RegExp oI = RegExp("^[^I]*");
                print(check.stringMatch(expression2)!);
                expression2 = "* ${oI.stringMatch(expression2)!}";
              }
            }
```

**Expected results:**  I'm trying to make a flutter calculator that also calculates Ohm's Law and Power. In "expression", it calculates the amps and ohmn to return the voltage value, and in "expression2", It calculates the watts. The method to calcultate the math is done later done the line. So, in pratice, it goes this way:

expression: 4(R)3(I)

4*3*

4First3Second

"Regex logic"

4First3Second

4*3Second

4*3

And then, in theory, expression2 should do:

4RRr3(I)

4RRr3IIi

(print check.stringMatch(expression2)!)

(print look)

(Check if it is empty, If true)

*  3

(else)

(regex) to get the first number(s)

* 3

**Actual results:** But instead i get this exception below

```
Restarted application in 1.744ms.

════════ Exception caught by gesture ═══════════════════════════════════════════
The following _CastError was thrown while handling a gesture:
Null check operator used on a null value

When the exception was thrown, this was the stack
#0      _calculadoraDeOhmState.buttonPressed.<anonymous closure>
#1      State.setState
#2      _calculadoraDeOhmState.buttonPressed
#3      _calculadoraDeOhmState.buildButton.<anonymous closure>
#4      _InkResponseState._handleTap
#5      GestureRecognizer.invokeCallback
#6      TapGestureRecognizer.handleTapUp
#7      BaseTapGestureRecognizer._checkUp
#8      BaseTapGestureRecognizer.handlePrimaryPointer
#9      PrimaryPointerGestureRecognizer.handleEvent
#10     PointerRouter._dispatch
#11     PointerRouter._dispatchEventToRoutes.<anonymous closure>
#12     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:614:13)
#13     PointerRouter._dispatchEventToRoutes
#14     PointerRouter.route
#15     GestureBinding.handleEvent
#16     GestureBinding.dispatchEvent
#17     RendererBinding.dispatchEvent
#18     GestureBinding._handlePointerEventImmediately
#19     GestureBinding.handlePointerEvent
#20     GestureBinding._flushPointerEventQueue
#21     GestureBinding._handlePointerDataPacket
#22     _invoke1 (dart:ui/hooks.dart:167:13)
#23     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:341:7)
#24     _dispatchPointerDataPacket (dart:ui/hooks.dart:94:31)
Handler: "onTap"
Recognizer: TapGestureRecognizer#b89f0
    debugOwner: GestureDetector
    state: possible
    won arena
    finalPosition: Offset(171.7, 400.0)
    finalLocalPosition: Offset(13.3, 25.8)
    button: 1
    sent tap down
════════════════════════════════════════════════════════════════════════════════

```
  <summary>Logs</summary>

</details>

```
info - Prefer const with constant constructors - lib\main.dart:14:10 - prefer_const_constructors
   info - Name types using UpperCamelCase - lib\main.dart:52:7 - camel_case_types
   info - Use key in widget constructors - lib\main.dart:52:7 - use_key_in_widget_constructors
   info - Avoid using private types in public APIs - lib\main.dart:57:3 - library_private_types_in_public_api
   info - Name types using UpperCamelCase - lib\main.dart:63:7 - camel_case_types
   info - Avoid `print` calls in production code - lib\main.dart:332:15 - avoid_print
   info - Avoid `print` calls in production code - lib\main.dart:333:15 - avoid_print
   info - Avoid `print` calls in production code - lib\main.dart:340:17 - avoid_print

8 issues found. (ran in 4.5s)

```

```
[√] Flutter (Channel beta, 3.1.0, on Microsoft Windows [versÆo 10.0.22000.795], locale pt-BR)
    • Flutter version 3.1.0 at C:\tools\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision bcea432bce (9 weeks ago), 2022-05-26 09:05:34 -0700
    • Engine revision 44e5b38ee8
    • Dart version 2.18.0 (build 2.18.0-44.1.beta)
    • DevTools version 2.12.2

[!] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at C:\Users\User\AppData\Local\Android\Sdk\
    • Platform android-32, build-tools 32.1.0-rc1
    • ANDROID_HOME = C:\Users\User\AppData\Local\Android\Sdk\tools\bin
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.2.3)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.2.32526.322
    • Windows 10 SDK version 10.0.22621.0

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] IntelliJ IDEA Community Edition (version 2022.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2022.1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code (version 1.69.2)
    • VS Code at C:\Users\User\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.44.0

[√] Connected device (4 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 7.1.1 (API 25) (emulator)
    • Windows (desktop)                  • windows       • windows-x64    • Microsoft Windows [versÆo 10.0.22000.795] 
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 103.0.5060.134
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 101.0.1210.39

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

</details>

**Comment by stuartmorgan** [comment] 2022-07-28 10:31
That error indicates that you are using `!` incorrectly in your code. For help with your own code, you can try one of the resources at http://flutter.dev/community#community-grid

Closing as this in not a bug in Flutter.

**Closed by stuartmorgan** 2022-07-28 10:31 UTC
Labels: in triage
