### ISSUE TITLE
SelectionArea throws ('!debugNeedsLayout': is not true)

### ISSUE THREAD

**Issue by stan-at-work** [flutter/flutter#152230] opened 2024-07-24 12:13 UTC
### Steps to reproduce

Run the code sample, but trigger it with deeplinking.

I have 3 page that are stacked (beamer)

When i got the detail page (thro deeplinking), the assertion is thrown from the second page.

I do not get this assertion when i nagivate normally within the app.

only when i navigate thro deeplinking.

The assertion is gone when i remove SelectionArea() from the tree, so its deffenitly that.

### Expected results

No assertion

### Actual results

The assertion throws

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.light().copyWith(
        useMaterial3: true,
      ),
      debugShowCheckedModeBanner: false,
      home: const Scaffold(
        body: Center(
          child: MyWidget(),
        ),
      ),
    );
  }
}

class MyWidget extends StatelessWidget {
  const MyWidget({super.key});

  @override
  Widget build(BuildContext context) {
    return const SelectionArea(
      child: Column(
        children: <Widget>[
          Text('How are you?'),
          Text('Good, and you?'),
          Text('Fine, thank you.'),
        ],
      ),
    );
  }
}
```

</details>

### Logs

<details open><summary>Logs</summary>

```console
flutter: ══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
flutter: The following assertion was thrown during a scheduler callback:
flutter: 'package:flutter/src/rendering/paragraph.dart': Failed assertion: line 982 pos 12:
paragraph.dart:982
flutter: '!debugNeedsLayout': is not true.
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new?template=2_bug.yml
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #2      RenderParagraph.getBoxesForSelection
paragraph.dart:982
flutter: #3      _SelectableFragment.boundingBoxes
paragraph.dart:2026
flutter: #4      MultiSelectableSelectionContainerDelegate._getBoundingBox
selectable_region.dart:1909
flutter: #5      MultiSelectableSelectionContainerDelegate._compareScreenOrder
selectable_region.dart:1926
flutter: #6      Sort._insertionSort (dart:_internal/sort.dart:69:36)
flutter: #7      Sort._doSort (dart:_internal/sort.dart:58:7)
flutter: #8      Sort.sort (dart:_internal/sort.dart:33:5)
flutter: #9      ListBase.sort (dart:collection/list.dart:321:10)
flutter: #10     MultiSelectableSelectionContainerDelegate._flushAdditions
selectable_region.dart:1824
flutter: #11     MultiSelectableSelectionContainerDelegate._updateSelectables
selectable_region.dart:1818
flutter: #12     MultiSelectableSelectionContainerDelegate._scheduleSelectableUpdate.runScheduledTask
selectable_region.dart:1797
flutter: #13     SchedulerBinding._invokeFrameCallback
binding.dart:1392
flutter: #14     SchedulerBinding.handleDrawFrame
binding.dart:1326

```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.22.3, on Microsoft Windows [Version 10.0.22631.3880], locale nl-BE)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.10.1)
[√] Android Studio (version 2023.3)
[√] VS Code, 64-bit edition (version 1.91.1)
[√] Connected device (2 available)
[√] Network resources```

</details>

**Comment by danagbemava-nc** [comment] 2024-07-24 13:05
Closing this as a duplicate of 
- https://github.com/flutter/flutter/issues/117527
- https://github.com/flutter/flutter/issues/119772

**Closed by danagbemava-nc** 2024-07-24 13:05 UTC
Labels: in triage
