### ISSUE TITLE
Google Sign In Web renderButton is interactable through ModalBarriers

### ISSUE THREAD

**Issue by LeoBound** [flutter/flutter#144987] opened 2024-03-12 11:33 UTC
### What package does this bug report belong to?

google_sign_in

### What target platforms are you seeing this bug on?

Web

### Have you already upgraded your packages?

Yes

### Dependency versions

<details><summary>pubspec.lock</summary>

```lock
# Generated by pub
# See https://dart.dev/tools/pub/glossary#lockfile
packages:
  async:
    dependency: transitive
    description:
      name: async
      sha256: "947bfcf187f74dbc5e146c9eb9c0f10c9f8b30743e341481c1e2ed3ecc18c20c"
      url: "https://tps-art.topcon.com/artifactory/api/pub/ttl-dart-pub/"
    source: hosted
    version: "2.11.0"
  boolean_selector:
    dependency: transitive
    description:
      name: boolean_selector
      sha256: "6cfb5af12253eaf2b368f07bacc5a80d1301a071c73360d746b7f2e32d762c66"
      url: "https://tps-art.topcon.com/artifactory/api/pub/ttl-dart-pub/"
    source: hosted
    version: "2.1.1"
  characters:
    dependency: transitive
    description:
      name: characters
      sha256: "04a925763edad70e8443c99234dc3328f442e811f1d8fd1a72f1c8ad0f69a605"
      url: "https://tps-art.topcon.com/artifactory/api/pub/ttl-dart-pub/"
    source: hosted
    version: "1.3.0"
  clock:
    dependency: transitive
    description:
      name: clock
      sha256: cb6d7f03e1de671e34607e909a7213e31d7752be4fb66a86d29fe1eb14bfb5cf
      url: "https://tps-art.topcon.com/artifactory/api/pub/ttl-dart-pub/"
    source: hosted
    version: "1.1.1"
  collection:
    dependency: transitive
    description:
      name: collection
      sha256: ee67cb0715911d28db6bf4af1026078bd6f0128b07a5f66fb2ed94ec6783c09a
      url: "https://tps-art.topcon.com/artifactory/api/pub/ttl-dart-pub/"
    source: hosted
    version: "1.18.0"
  fake_async:
    dependency: transitive
    description:
      name: fake_async
      sha256: "511392330127add0b769b75a987850d136345d9227c6b94c96a04cf4a391bf78"
      url: "https://tps-art.topcon.com/artifactory/api/pub/ttl-dart-pub/"
    source: hosted
    version: "1.3.1"
  flutter:
    dependency: "direct main"
    description: flutter
    source: sdk
    version: "0.0.0"
  flutter_test:
    dependency: "direct dev"
    description: flutter
    source: sdk
    version: "0.0.0"
  flutter_web_plugins:
    dependency: transitive
    description: flutter
    source: sdk
    version: "0.0.0"
  google_identity_services_web:
    dependency: transitive
    description:
      name: google_identity_services_web
      sha256: "9482364c9f8b7bd36902572ebc3a7c2b5c8ee57a9c93e6eb5099c1a9ec5265d8"
      url: "https://tps-art.topcon.com/artifactory/api/pub/ttl-dart-pub/"
    source: hosted
    version: "0.3.1+1"
  google_sign_in:
    dependency: "direct main"
    description:
      name: google_sign_in
      sha256: "0b8787cb9c1a68ad398e8010e8c8766bfa33556d2ab97c439fb4137756d7308f"
      url: "https://tps-art.topcon.com/artifactory/api/pub/ttl-dart-pub/"
    source: hosted
    version: "6.2.1"
  google_sign_in_android:
    dependency: transitive
    description:
      name: google_sign_in_android
      sha256: bfd42c81c30c6faba16e0f62968d5505a87504aaa672b3155ee931461abb0a49
      url: "https://tps-art.topcon.com/artifactory/api/pub/ttl-dart-pub/"
    source: hosted
    version: "6.1.21"
  google_sign_in_ios:
    dependency: transitive
    description:
      name: google_sign_in_ios
      sha256: a7d653803468d30b82ceb47ea00fe86d23c56e63eb2e5c2248bb68e9df203217
      url: "https://tps-art.topcon.com/artifactory/api/pub/ttl-dart-pub/"
    source: hosted
    version: "5.7.4"
  google_sign_in_platform_interface:
    dependency: transitive
    description:
      name: google_sign_in_platform_interface
      sha256: "1f6e5787d7a120cc0359ddf315c92309069171306242e181c09472d1b00a2971"
      url: "https://tps-art.topcon.com/artifactory/api/pub/ttl-dart-pub/"
    source: hosted
    version: "2.4.5"
  google_sign_in_web:
    dependency: "direct main"
    description:
      name: google_sign_in_web
      sha256: fc0f14ed45ea616a6cfb4d1c7534c2221b7092cc4f29a709f0c3053cc3e821bd
      url: "https://tps-art.topcon.com/artifactory/api/pub/ttl-dart-pub/"
    source: hosted
    version: "0.12.4"
  http:
    dependency: transitive
    description:
      name: http
      sha256: "761a297c042deedc1ffbb156d6e2af13886bb305c2a343a4d972504cd67dd938"
      url: "https://tps-art.topcon.com/artifactory/api/pub/ttl-dart-pub/"
    source: hosted
    version: "1.2.1"
  http_parser:
    dependency: transitive
    description:
      name: http_parser
      sha256: "2aa08ce0341cc9b354a498388e30986515406668dbcc4f7c950c3e715496693b"
      url: "https://tps-art.topcon.com/artifactory/api/pub/ttl-dart-pub/"
    source: hosted
    version: "4.0.2"
  leak_tracker:
    dependency: transitive
    description:
      name: leak_tracker
      sha256: "78eb209deea09858f5269f5a5b02be4049535f568c07b275096836f01ea323fa"
      url: "https://tps-art.topcon.com/artifactory/api/pub/ttl-dart-pub/"
    source: hosted
    version: "10.0.0"
  leak_tracker_flutter_testing:
    dependency: transitive
    description:
      name: leak_tracker_flutter_testing
      sha256: b46c5e37c19120a8a01918cfaf293547f47269f7cb4b0058f21531c2465d6ef0
      url: "https://tps-art.topcon.com/artifactory/api/pub/ttl-dart-pub/"
    source: hosted
    version: "2.0.1"
  leak_tracker_testing:
    dependency: transitive
    description:
      name: leak_tracker_testing
      sha256: a597f72a664dbd293f3bfc51f9ba69816f84dcd403cdac7066cb3f6003f3ab47
      url: "https://tps-art.topcon.com/artifactory/api/pub/ttl-dart-pub/"
    source: hosted
    version: "2.0.1"
  matcher:
    dependency: transitive
    description:
      name: matcher
      sha256: d2323aa2060500f906aa31a895b4030b6da3ebdcc5619d14ce1aada65cd161cb
      url: "https://tps-art.topcon.com/artifactory/api/pub/ttl-dart-pub/"
    source: hosted
    version: "0.12.16+1"
  material_color_utilities:
    dependency: transitive
    description:
      name: material_color_utilities
      sha256: "0e0a020085b65b6083975e499759762399b4475f766c21668c4ecca34ea74e5a"
      url: "https://tps-art.topcon.com/artifactory/api/pub/ttl-dart-pub/"
    source: hosted
    version: "0.8.0"
  meta:
    dependency: transitive
    description:
      name: meta
      sha256: d584fa6707a52763a52446f02cc621b077888fb63b93bbcb1143a7be5a0c0c04
      url: "https://tps-art.topcon.com/artifactory/api/pub/ttl-dart-pub/"
    source: hosted
    version: "1.11.0"
  path:
    dependency: transitive
    description:
      name: path
      sha256: "087ce49c3f0dc39180befefc60fdb4acd8f8620e5682fe2476afd0b3688bb4af"
      url: "https://tps-art.topcon.com/artifactory/api/pub/ttl-dart-pub/"
    source: hosted
    version: "1.9.0"
  plugin_platform_interface:
    dependency: transitive
    description:
      name: plugin_platform_interface
      sha256: "4820fbfdb9478b1ebae27888254d445073732dae3d6ea81f0b7e06d5dedc3f02"
      url: "https://tps-art.topcon.com/artifactory/api/pub/ttl-dart-pub/"
    source: hosted
    version: "2.1.8"
  sky_engine:
    dependency: transitive
    description: flutter
    source: sdk
    version: "0.0.99"
  source_span:
    dependency: transitive
    description:
      name: source_span
      sha256: "53e943d4206a5e30df338fd4c6e7a077e02254531b138a15aec3bd143c1a8b3c"
      url: "https://tps-art.topcon.com/artifactory/api/pub/ttl-dart-pub/"
    source: hosted
    version: "1.10.0"
  stack_trace:
    dependency: transitive
    description:
      name: stack_trace
      sha256: "73713990125a6d93122541237550ee3352a2d84baad52d375a4cad2eb9b7ce0b"
      url: "https://tps-art.topcon.com/artifactory/api/pub/ttl-dart-pub/"
    source: hosted
    version: "1.11.1"
  stream_channel:
    dependency: transitive
    description:
      name: stream_channel
      sha256: ba2aa5d8cc609d96bbb2899c28934f9e1af5cddbd60a827822ea467161eb54e7
      url: "https://tps-art.topcon.com/artifactory/api/pub/ttl-dart-pub/"
    source: hosted
    version: "2.1.2"
  string_scanner:
    dependency: transitive
    description:
      name: string_scanner
      sha256: "556692adab6cfa87322a115640c11f13cb77b3f076ddcc5d6ae3c20242bedcde"
      url: "https://tps-art.topcon.com/artifactory/api/pub/ttl-dart-pub/"
    source: hosted
    version: "1.2.0"
  term_glyph:
    dependency: transitive
    description:
      name: term_glyph
      sha256: a29248a84fbb7c79282b40b8c72a1209db169a2e0542bce341da992fe1bc7e84
      url: "https://tps-art.topcon.com/artifactory/api/pub/ttl-dart-pub/"
    source: hosted
    version: "1.2.1"
  test_api:
    dependency: transitive
    description:
      name: test_api
      sha256: "5c2f730018264d276c20e4f1503fd1308dfbbae39ec8ee63c5236311ac06954b"
      url: "https://tps-art.topcon.com/artifactory/api/pub/ttl-dart-pub/"
    source: hosted
    version: "0.6.1"
  typed_data:
    dependency: transitive
    description:
      name: typed_data
      sha256: facc8d6582f16042dd49f2463ff1bd6e2c9ef9f3d5da3d9b087e244a7b564b3c
      url: "https://tps-art.topcon.com/artifactory/api/pub/ttl-dart-pub/"
    source: hosted
    version: "1.3.2"
  vector_math:
    dependency: transitive
    description:
      name: vector_math
      sha256: "80b3257d1492ce4d091729e3a67a60407d227c27241d6927be0130c98e741803"
      url: "https://tps-art.topcon.com/artifactory/api/pub/ttl-dart-pub/"
    source: hosted
    version: "2.1.4"
  vm_service:
    dependency: transitive
    description:
      name: vm_service
      sha256: b3d56ff4341b8f182b96aceb2fa20e3dcb336b9f867bc0eafc0de10f1048e957
      url: "https://tps-art.topcon.com/artifactory/api/pub/ttl-dart-pub/"
    source: hosted
    version: "13.0.0"
  web:
    dependency: transitive
    description:
      name: web
      sha256: "97da13628db363c635202ad97068d47c5b8aa555808e7a9411963c533b449b27"
      url: "https://tps-art.topcon.com/artifactory/api/pub/ttl-dart-pub/"
    source: hosted
    version: "0.5.1"
sdks:
  dart: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"
```

</details>

### Steps to reproduce

Run the code below in flutter web press the floating action button to display a dialog.
You can press the google_sign_in_web renderButton through this.
I came across this when trying to show my sign up Dialog.fullscreen over the top of the page with this button on and accidentally pressed the button.

### Expected results

The dialog showed by the button should block taps to the renderButton underneath it.
This applies more generally to any modal barrier placed in front of it.
It also appears an IgnorePointer will not prevent taps being ignored.

### Actual results

The render button can be pressed 'through' the dialog.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:google_sign_in_platform_interface/google_sign_in_platform_interface.dart' show GoogleSignInPlatform;
import 'package:google_sign_in_web/google_sign_in_web.dart';
import 'package:google_sign_in_web/web_only.dart';

void main() async {
  final plugin = GoogleSignInPlatform.instance as GoogleSignInPlugin;
  await plugin.init(clientId: 'example.com');
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp();

  @override
  Widget build(BuildContext context) => const MaterialApp(home: MyHomePage());
}

class MyHomePage extends StatelessWidget {
  const MyHomePage();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(),
        body: Center(child: renderButton()),
        floatingActionButton: FloatingActionButton(
          onPressed: () => showDialog(
            context: context,
            builder: (_) => const AlertDialog(
              title: Text('Dialog'),
              content: Text("Hello!"),
            ),
          ),
        ));
  }
}

```

</details>

### Screenshots or Videos

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/flutter/flutter/assets/7754101/0bee8bdc-8c26-459a-96b8-0a8ce83a6dfd

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.19.1, on Microsoft Windows [Version 10.0.22631.3007], locale en-GB)
    • Flutter version 3.19.1 on channel stable at C:\tools\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision abb292a07e (3 weeks ago), 2024-02-20 14:35:05 -0800
    • Engine revision 04817c99c9
    • Dart version 3.3.0
    • DevTools version 2.31.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\lbound\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.9.1)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.9.34616.47
    • Windows 10 SDK version 10.0.22621.0

[√] Android Studio (version 2023.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)

[√] VS Code, 64-bit edition (version 1.87.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.50.0

[√] Connected device (4 available)
    • SM T220 (mobile)  • R9JT107SYXX • android-arm64  • Android 14 (API 34)
    • Windows (desktop) • windows     • windows-x64    • Microsoft Windows [Version 10.0.22631.3007]
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 121.0.6167.86
    • Edge (web)        • edge        • web-javascript • Microsoft Edge 122.0.2365.80

[√] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by darshankawar** [comment] 2024-03-12 13:17
@LeoBound 
I think the issue isn't specific to google_sign_in package but with underlying platform-views which are being used by flutter packages. Hence, I think the issue is same as https://github.com/flutter/flutter/issues/14720 in which you can follow-up for further updates. You can share your findings in it for better tracking.
Closing this as a duplicate. If you disagree, write in comments and i'll reopen it.

**Closed by darshankawar** 2024-03-12 13:17 UTC
Labels: in triage

**Comment by LeoBound** [comment] 2024-03-12 13:49
Hi @darshankawar 
Thanks for the quick response.
I have a couple of questions about this and the aforementioned issue.
#14720 seems to only mention iOS and shows native views on top of the flutter canvas letting touch events 'leak through' (I may be misunderstanding this, and I'm not familiar with the terminology)?

The issue I'm having pertains to flutter widgets covering native UI, I'm not too familiar about how this and flutter dialogs are implemented so this may be the same as #14720? It may be worth noting that the behaviour I have with showDialog above doesn't occur when you push a MaterialPageRoute with Navigator.push.

Is there an alternative to this button - it is recommended by [google_sign_in_web](https://pub.dev/packages/google_sign_in_web) when migrating to the latest version. It's a bit surprising to me that we have to use a platform button to show the Google sign in popup on web (or is there a way around this).

Thanks

**Comment by darshankawar** [comment] 2024-03-13 06:15
@LeoBound 
Can you try to make use of https://pub.dev/packages/pointer_interceptor and see if it helps in your case ?

**Comment by LeoBound** [comment] 2024-03-13 09:07
@darshankawar Doesn't work unfortunately (behaviour is the same as without it). I think this is because I have a HtmlElementView on top of flutter, whereas that package seems to be for flutter on top of HtmlElementViews.

**Comment by LeoBound** [comment] 2024-03-13 09:13
Wrapping the Dialog in PointerInterceptor seems to fix it, although it does also prevent the Dialog from being barrierDismissible.
I think this is a good enough solution for me for now 🙂
