### ISSUE TITLE
Flutter is dead

### ISSUE THREAD

**Issue by revenantcoder** [flutter/flutter#84071] opened 2021-06-06 10:48 UTC
After working on flutter for about a month, I am a little disappointed. The way they handle widgets is irregular without any particular pattern. Sometimes they use static property of a class, sometimes enums, sometimes named-constructor and sometimes inherited class as a parameter. WHY ?? Lets take a simple example of basic widget. If I want to change the color of a textbutton then this is the code

TextButton(
style: TextButton.styleFrom(
primary: Colors.purple,
),
and why not just
Textbutton(
primary: Colors.purple
)
and why I need 6 named constructor for EdgeInsets -> (all, fromLTRB, symmetic, only, etc ) when one constructor was sufficient EdgeInsets(L,R,T,B). These are the example of basic widgets, wondering what flutter team did with more advanced widgets.

**Comment by stuartmorgan** [comment] 2021-06-06 12:03
Duplicate of https://github.com/flutter/flutter/issues/84070

Deliberate abuse of the issue tracker is not consistent with our code of conduct. I have already explained that the issue tracker is not the place for your question. Please do not deliberately open a duplicate again.

**Closed by stuartmorgan** 2021-06-06 12:03 UTC
