### ISSUE TITLE
[tool_crash] SocketException: Write failed, OS Error: Broken pipe, errno = 32

### ISSUE THREAD

**Issue by Imransada** [flutter/flutter#152741] opened 2024-08-02 10:22 UTC
## Command
```
flutter --no-color run --machine --track-widget-creation --device-id=emulator-5554 --start-paused --dart-define=flutter.inspector.structuredErrors=true lib/main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
SocketException: Write failed, OS Error: Broken pipe, errno = 32
```
#0      _NativeSocket.write (dart:io-patch/socket_patch.dart:1246:34)
#1      _RawSocket.write (dart:io-patch/socket_patch.dart:2004:15)
#2      _Socket._write (dart:io-patch/socket_patch.dart:2481:18)
#3      _SocketStreamConsumer.write (dart:io-patch/socket_patch.dart:2216:28)
#4      _SocketStreamConsumer.addStream.<anonymous closure> (dart:io-patch/socket_patch.dart:2168:11)
#5      _rootRunUnary (dart:async/zone.dart:1407:47)
#6      _CustomZone.runUnary (dart:async/zone.dart:1308:19)
#7      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217:7)
#8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:365:11)
#9      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:297:7)
#10     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:784:19)
#11     _StreamController._add (dart:async/stream_controller.dart:658:7)
#12     _StreamController.add (dart:async/stream_controller.dart:606:5)
#13     _StreamSinkImpl.add (dart:io/io_sink.dart:154:17)
#14     _IOSinkImpl.write (dart:io/io_sink.dart:287:5)
#15     _Socket.write (dart:io-patch/socket_patch.dart:2314:36)
#16     _StdSink._write (dart:io/stdio.dart:401:13)
#17     _StdSink.writeln (dart:io/stdio.dart:419:5)
#18     DefaultResidentCompiler._compile (package:flutter_tools/src/compile.dart:907:20)
<asynchronous suspension>
#19     _CompilationRequest.run (package:flutter_tools/src/compile.dart:396:24)
<asynchronous suspension>
#20     DefaultResidentCompiler._handleCompilationRequest (package:flutter_tools/src/compile.dart:782:9)
<asynchronous suspension>
```
```
[!] Flutter (Channel stable, 3.22.2, on macOS 14.5 23F79 darwin-x64, locale en-NG)
    • Flutter version 3.22.2 on channel stable at /Users/chawaiwhitehouse/Desktop/flutter
    ! Warning: `flutter` on your path resolves to /usr/local/Caskroom/flutter/3.22.3/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/chawaiwhitehouse/Desktop/flutter. Consider adding /Users/chawaiwhitehouse/Desktop/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /usr/local/Caskroom/flutter/3.22.3/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/chawaiwhitehouse/Desktop/flutter. Consider adding /Users/chawaiwhitehouse/Desktop/flutter/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 761747bfc5 (8 weeks ago), 2024-06-05 22:15:13 +0200
    • Engine revision edd8546116
    • Dart version 3.4.3
    • DevTools version 2.34.3
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at /Users/chawaiwhitehouse/Library/Android/sdk
    • Platform android-35, build-tools 35.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    ✗ Unable to get list of installed Simulator runtimes.
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)

[✓] VS Code (version 1.90.0)
    • VS Code at /Users/chawaiwhitehouse/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.94.0

[✓] Connected device (3 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 12 (API 31) (emulator)
    • macOS (desktop)              • macos         • darwin-x64     • macOS 14.5 23F79 darwin-x64
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 127.0.6533.89

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 761747bfc538b5af34aa0d3fac380f1bc331ec49
### Plugins
flutter_keyboard_visibility-6.0.0
flutter_keyboard_visibility_linux-1.0.0
flutter_keyboard_visibility_macos-1.0.0
flutter_keyboard_visibility_web-2.0.0
flutter_keyboard_visibility_windows-1.0.0
path_provider_linux-2.2.1
path_provider_windows-2.3.0
shared_preferences-2.3.0
shared_preferences_android-2.3.0
shared_preferences_foundation-2.5.0
shared_preferences_linux-2.4.0
shared_preferences_web-2.4.0
shared_preferences_windows-2.4.0
webview_flutter-4.8.0
webview_flutter_android-3.16.6
webview_flutter_wkwebview-3.14.0

**Comment by danagbemava-nc** [comment] 2024-08-02 10:36
Closing this as a duplicate of https://github.com/flutter/flutter/issues/136753

**Closed by danagbemava-nc** 2024-08-02 10:36 UTC
Labels: in triage
