### ISSUE TITLE
[tool_crash] ProcessException: Process timed out: Command: /usr/bin/arch, OS error code: -1

### ISSUE THREAD

**Issue by makkasbed** [flutter/flutter#96723] opened 2022-01-16 22:28 UTC
## Command
```
flutter build ipa
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ProcessException: Process timed out:
 Command: /usr/bin/arch, OS error code: -1
```
#0      RunResult.throwException (package:flutter_tools/src/base/process.dart:171:5)
#1      _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart:394:19)
<asynchronous suspension>
#2      buildXcodeProject (package:flutter_tools/src/ios/mac.dart:371:47)
<asynchronous suspension>
#3      _BuildIOSSubCommand.runCommand (package:flutter_tools/src/commands/build_ios.dart:244:37)
<asynchronous suspension>
#4      BuildIOSArchiveCommand.runCommand (package:flutter_tools/src/commands/build_ios.dart:111:50)
<asynchronous suspension>
#5      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1157:12)
<asynchronous suspension>
#6      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1009:27)
<asynchronous suspension>
#7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#8      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
<asynchronous suspension>
#9      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
<asynchronous suspension>
#10     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:278:9)
<asynchronous suspension>
#11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#12     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 2.0.2,

**Comment by danagbemava-nc** [comment] 2022-01-17 12:19
Closing this as duplicate of #47633

**Closed by danagbemava-nc** 2022-01-17 12:19 UTC
Labels: in triage
