### ISSUE TITLE
Cancelling the sign in with google pop up is throwing Platform Exception Android

### ISSUE THREAD

**Issue by nirvikBasnet** [flutter/flutter#32493] opened 2019-05-10 15:26 UTC
## Steps to Reproduce

1. In the app when pressed login with google button the google sign in page appears with all the gmail accounts to choose from to login or signup.
2. Touch the outer area of the pop up to cancel the sign in , which then shuts down the pop up.
3. After that there is platform exception in the code saying : 

     Exception has occurred.
PlatformException (PlatformException(sign_in_canceled, 
com.google.android.gms.common.api.ApiException: 12501: , null))

4. Now the login button is not working and the app crashes,

## Logs

 Exception has occurred.
PlatformException (PlatformException(sign_in_canceled, 
com.google.android.gms.common.api.ApiException: 12501: , null))
![60352123_1079607862226157_6862370330321616896_n](https://user-images.githubusercontent.com/46699486/57538372-a0fb8f80-738b-11e9-989e-973aab7a7996.jpg)

**Comment by collinjackson** [comment] 2019-07-12 23:59
Have you filled in all the fields in the OAuth consent screen page? I've put up a PR that improves the docs a bit.

**Comment by OsaXma** [comment] 2019-12-15 20:31
Same issue here. Someone else and I posted more details on #44431

**Comment by TahaTesser** [comment] 2020-03-18 15:36
Duplicate of [#44431](https://github.com/flutter/flutter/issues/44431)
Closing this as duplicate has more activity 
Thank you

**Closed by TahaTesser** 2020-03-18 15:36 UTC
Labels: p: google_sign_in, plugin, severe: crash
