### ISSUE TITLE
App Crash when TextField delete text 

### ISSUE THREAD

**Issue by shingohu** [flutter/flutter#36809] opened 2019-07-24 06:13 UTC
There are problems with huawei phones
model:NEM-AL10
android-version:6.0

**question 1**

1. click the textfield and input any text

2. click the delete key on keyboard

The question is the textfield contents will be cleared

[question 1 video](https://pan.baidu.com/s/1b5vqv9S7AOFFvZD3x5rJmQ)

**question 2**

1. two textfield  T1 and T2
2. click T1 and input any text
3. click T2 and input any text
4. click the delete key when T2 focus （Same question like question 1）
5. click the T1 and click delete key ,app crash

nothing print (Android Studio and VSCode the same print) only:
I/Process (18227): Sending signal. PID: 18227 SIG: 9
Lost connection to device.
 [question 2 video](https://pan.baidu.com/s/164q3CcP3TyUu2_8gqALDAA)

```
(base) 1203:gongke.flutter hujie$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.7.8+hotfix.3, on Mac OS X 10.14.4 18E226, locale zh-Hans-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
[✓] iOS tools - develop for iOS devices
[✓] Android Studio (version 3.4)
[✓] VS Code (version 1.36.1)
[✓] Connected device (1 available)
```

**Comment by dasmikko** [comment] 2019-07-24 06:21
Use the hotfix 4 that fixes your issue

**Comment by shingohu** [comment] 2019-07-25 02:07
@dasmikko  question 2 is ok，but question 1 is still remain

**Comment by justinmc** [comment] 2019-07-31 21:42
I was finally able to reproduce this (question 1) using a Huawei EVA-AL00 running Android 6.0.0!  Code below.

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(
        appBar: AppBar(
          title: Text('Huawei Number Deletion Bug'),
        ),
        body: Center(
          child: TextField(
            keyboardType: TextInputType.phone,
          ),
        ),
      ),
    );
  }
}
```

I had no luck reproducing on all of these devices/simulators:

  * Huawei CLT-TL01 running Android 8.1.0
  * Huawei KNT-AL20 running Android 8.0.0
  * Huawei VCE-AL00 running Android 9.0.0
  * Virutal Nexus 6 running Android 7.1.1
  * Virtual Nexus 5 running Android 6.0.0

**Comment by shingohu** [comment] 2019-08-01 02:27
@justinmc Yes, a few devices have these problems.We also received some feedback from users, such as TextField cannot use the enter key to nextline, and keyboardType will not be switched when two textfields are switched

**Comment by GaryQian** [comment] 2019-08-01 21:21
Related to https://github.com/flutter/flutter/issues/36007

**Comment by justinmc** [comment] 2019-08-01 21:49
This seems to be a duplicate of https://github.com/flutter/flutter/issues/33642, which was just hotfixed.  See https://github.com/flutter/flutter/issues/33642#issuecomment-513889525 for how to get the fix.  Let me know if that doesn't fix the problem.

**Closed by justinmc** 2019-08-01 21:49 UTC
Labels: a: text input, e: device-specific, f: material design, framework, severe: crash, ▣ platform-android
