### ISSUE TITLE
Image picker corrects the wrong direction after zooming the image on IOS. The direction displayed on H5 is inconsistent with that displayed on app

### ISSUE THREAD

**Issue by yangyxd** [flutter/flutter#59226] opened 2020-06-11 02:52 UTC
I saw the following code in the source code dealing with the problem of image direction, but I feel that this way, the processed image is not compatible with H5. In H5, the direction of the image is not consistent with the display in the app.

```dart
  // Scaling the image always rotate itself based on the current imageOrientation of the original
  // Image. Set to orientationUp for the orignal image before scaling, so the scaled image doesn't
  // mess up with the pixels.
  UIImage *imageToScale = [UIImage imageWithCGImage:image.CGImage
                                              scale:1
                                        orientation:UIImageOrientationUp];

  // The image orientation is manually set to UIImageOrientationUp which swapped the aspect ratio in
  // some scenarios. For example, when the original image has orientation left, the horizontal
  // pixels should be scaled to `width` and the vertical pixels should be scaled to `height`. After
  // setting the orientation to up, we end up scaling the horizontal pixels to `height` and vertical
  // to `width`. Below swap will solve this issue.
  if ([image imageOrientation] == UIImageOrientationLeft ||
      [image imageOrientation] == UIImageOrientationRight ||
      [image imageOrientation] == UIImageOrientationLeftMirrored ||
      [image imageOrientation] == UIImageOrientationRightMirrored) {
    double temp = width;
    width = height;
    height = temp;
  }
```

I hope to solve this problem. Thank you very much.

**Comment by yangyxd** [comment] 2020-06-11 02:59
This is a solution of the netizens I found. Please refer to it. thank you.

```dart
- (UIImage *)fixOrientation:(UIImage *)aImage {  
       
    // No-op if the orientation is already correct  
    if (aImage.imageOrientation == UIImageOrientationUp)   
        return aImage;  
       
    // We need to calculate the proper transformation to make the image upright.  
    // We do it in 2 steps: Rotate if Left/Right/Down, and then flip if Mirrored.  
    CGAffineTransform transform = CGAffineTransformIdentity;  
       
    switch (aImage.imageOrientation) {  
        case UIImageOrientationDown:  
        case UIImageOrientationDownMirrored:  
            transform = CGAffineTransformTranslate(transform, aImage.size.width, aImage.size.height);  
            transform = CGAffineTransformRotate(transform, M_PI);  
            break;  
               
        case UIImageOrientationLeft:  
        case UIImageOrientationLeftMirrored:  
            transform = CGAffineTransformTranslate(transform, aImage.size.width, 0);  
            transform = CGAffineTransformRotate(transform, M_PI_2);  
            break;  
               
        case UIImageOrientationRight:  
        case UIImageOrientationRightMirrored:  
            transform = CGAffineTransformTranslate(transform, 0, aImage.size.height);  
            transform = CGAffineTransformRotate(transform, -M_PI_2);  
            break;  
        default:  
            break;  
    }  
       
    switch (aImage.imageOrientation) {  
        case UIImageOrientationUpMirrored:  
        case UIImageOrientationDownMirrored:  
            transform = CGAffineTransformTranslate(transform, aImage.size.width, 0);  
            transform = CGAffineTransformScale(transform, -1, 1);  
            break;  
               
        case UIImageOrientationLeftMirrored:  
        case UIImageOrientationRightMirrored:  
            transform = CGAffineTransformTranslate(transform, aImage.size.height, 0);  
            transform = CGAffineTransformScale(transform, -1, 1);  
            break;  
        default:  
            break;  
    }  
       
    // Now we draw the underlying CGImage into a new context, applying the transform  
    // calculated above.  
    CGContextRef ctx = CGBitmapContextCreate(NULL, aImage.size.width, aImage.size.height,  
                                             CGImageGetBitsPerComponent(aImage.CGImage), 0,  
                                             CGImageGetColorSpace(aImage.CGImage),  
                                             CGImageGetBitmapInfo(aImage.CGImage));  
    CGContextConcatCTM(ctx, transform);  
    switch (aImage.imageOrientation) {  
        case UIImageOrientationLeft:  
        case UIImageOrientationLeftMirrored:  
        case UIImageOrientationRight:  
        case UIImageOrientationRightMirrored:  
            // Grr...  
            CGContextDrawImage(ctx, CGRectMake(0,0,aImage.size.height,aImage.size.width), aImage.CGImage);  
            break;  
               
        default:  
            CGContextDrawImage(ctx, CGRectMake(0,0,aImage.size.width,aImage.size.height), aImage.CGImage);  
            break;  
    }  
       
    // And now we just create a new UIImage from the drawing context  
    CGImageRef cgimg = CGBitmapContextCreateImage(ctx);  
    UIImage *img = [UIImage imageWithCGImage:cgimg];  
    CGContextRelease(ctx);  
    CGImageRelease(cgimg);  
    return img;  
}  
```

**Comment by TahaTesser** [comment] 2020-06-11 11:39
Hi @yangyxd 
Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a minimal complete reproducible code sample.
Thank you

**Comment by yangyxd** [comment] 2020-06-12 05:15
Hi @TahaTesser 
My current environment is windows, but the code packaged on Mac OS is the same as the version of flutter.

Thank you!
```
[√] Flutter (Channel dev, 1.20.0-0.0.pre, on Microsoft Windows [Version 10.0.17763.1282], locale zh-CN)
    • Flutter version 1.20.0-0.0.pre at D:\Android\Flutter
    • Framework revision d9653445f4 (2 days ago), 2020-06-09 18:43:03 -0400
    • Engine revision e8c13aa012
    • Dart version 2.9.0 (build 2.9.0-14.0.dev 5c1376615e)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn


[!] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at D:\Android\sdk
    • Platform android-29, build-tools 29.0.1
    • ANDROID_HOME = D:\Android\sdk
    • Java binary at: D:\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Android Studio (version 4.0)
    • Android Studio at D:\Android\Android Studio
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.43.2)
    • VS Code at C:\Users\YangYxd\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.8.1

[√] VS Code, 64-bit edition (version 1.42.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.8.1

[√] Connected device (1 available)
    • Android SDK built for x86 64 • emulator-5554 • android-x64 • Android 10 (API 29) (emulator)

! Doctor found issues in 1 category.

```dart
  Future<String> uploadImage({ImageSource source = ImageSource.gallery, bool limitFileSize = true, UploadProgressCallback progress, VoidCallback onBeginUpload}) async {
    try {
      PickedFile _file = await ImagePicker().getImage(
        source: source,
        maxWidth: !limitFileSize ? null : 1920,
        maxHeight: !limitFileSize ? null : 1920,
        imageQuality: !limitFileSize ? null : 85,
      );
      if (_file == null || Utils.empty(_file.path))
        return null;
      return await upload(File(_file.path), progress: progress, onBeginUpload: onBeginUpload);
    } catch (e) {
      print(e);
      Utils.toast("上传图像失败：" + e.toString());
      return null;
    }
  }
```

**Comment by yangyxd** [comment] 2020-06-12 05:18
This is the problem image

![161ff692-03f6-4f3e-aebd-15ca91e5fed2](https://user-images.githubusercontent.com/14143779/84467554-1fbdad00-acaf-11ea-846f-147e77bb91d8.jpg)

**Comment by TahaTesser** [comment] 2020-06-12 08:54
Hi @yangyxd 
Tried your code sample and picked your sample image on iOS, i don't see any direction

![flutter_01](https://user-images.githubusercontent.com/48603081/84484366-49c79d00-acb8-11ea-9aff-1626ed05dc2c.png)


<details> 
<summary>Code Sample</summary> 

``` 
import 'dart:io';

import 'package:image_picker/image_picker.dart';

import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  File _image;
  final picker = ImagePicker();

  var source;
  var limitFileSize;

  Future getImage() async {
    //   final pickedFile = await picker.getImage(source: ImageSource.camera);

    //   setState(() {
    //     _image = File(pickedFile.path);
    //   });

    try {
      PickedFile pickedFile = await ImagePicker().getImage(
        source: ImageSource.gallery,
        // maxWidth: !limitFileSize ? null : 1920,
        // maxHeight: !limitFileSize ? null : 1920,
        // imageQuality: !limitFileSize ? null : 85,
      );
      if (pickedFile == null) return null;
      setState(() {
        _image = File(pickedFile.path);
      });

      // return await upload(File(_file.path), progress: progress, onBeginUpload: onBeginUpload);
    } catch (e) {
      print(e);
      // Utils.toast("上传图像失败：" + e.toString());
      return null;
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Image Picker Example'),
      ),
      body: Center(
        child: _image == null ? Text('No image selected.') : Image.file(_image),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: getImage,
        tooltip: 'Pick Image',
        child: Icon(Icons.add_a_photo),
      ),
    );
  }
}

``` 

</details> 


<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel dev, 1.20.0-0.0.pre, on Mac OS X 10.15.5 19F101, locale
    en-GB)
    • Flutter version 1.20.0-0.0.pre at /Users/tahatesser/Code/flutter_dev
    • Framework revision d9653445f4 (2 days ago), 2020-06-09 18:43:03 -0400
    • Engine revision e8c13aa012
    • Dart version 2.9.0 (build 2.9.0-14.0.dev 5c1376615e)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (5 available)
    • Android SDK built for x86 • emulator-5554             • android-x86    •
      Android 10 (API 29) (emulator)
    • Taha’s iPhone             • 00008020-001059882212002E • ios            •
      iOS 13.5.1
    • macOS                     • macOS                     • darwin-x64     •
      Mac OS X 10.15.5 19F101
    • Web Server                • web-server                • web-javascript •
      Flutter Tools
    • Chrome                    • chrome                    • web-javascript •
      Google Chrome 83.0.4103.97

• No issues found!
``` 

</details> 

if you please provide complete code sample and screenshot of the issue
Thank you

**Comment by yangyxd** [comment] 2020-06-12 09:52
Thank you very much.
Please use the following code to deal with the exception image I gave earlier, and then you use the < img > tag in the H5 page to display. You will find that the display effect in the browser is inconsistent with the direction in the app.

```dart
import 'dart:io';

import 'package:image_picker/image_picker.dart';

import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  File _image;
  final picker = ImagePicker();

  var source;
  var limitFileSize;

  Future getImage() async {
    try {
      PickedFile pickedFile = await ImagePicker().getImage(
        source: ImageSource.gallery,
        maxWidth: 1024,
        maxHeight: 1024,
        imageQuality: 85,
      );
      if (pickedFile == null) return null;
      setState(() {
        _image = File(pickedFile.path);
      });

      // return await upload(File(_file.path), progress: progress, onBeginUpload: onBeginUpload);
    } catch (e) {
      print(e);
      return null;
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Image Picker Example'),
      ),
      body: Center(
        child: _image == null ? Text('No image selected.') : Image.file(_image),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: getImage,
        tooltip: 'Pick Image',
        child: Icon(Icons.add_a_photo),
      ),
    );
  }
}
```

**Comment by TahaTesser** [comment] 2020-06-12 14:56
Hi @yangyxd 
Can you please provide code sample and screenshot for this?
```
then you use the < img > tag in the H5 page to display. You will find that the display effect in the browser is inconsistent with the direction in the app.

The main reason for this problem is that in the
```

**Comment by yangyxd** [comment] 2020-06-15 02:31
Hi @TahaTesser 

You can see the effect on GitHub. Do you see the difference? 
That is to say, the effect of direct display on mobile phone is different from that of < img SRC ='My image '/ >.

![image](https://user-images.githubusercontent.com/14143779/84612406-2b99b100-aef3-11ea-8f6e-a6aaa08aaea6.png)

**Comment by TahaTesser** [comment] 2020-06-15 14:24
Hi @yangyxd 

<img width="466" alt="Screenshot 2020-06-15 at 1 08 35 PM (1)" src="https://user-images.githubusercontent.com/48603081/84668987-e9e42700-af41-11ea-87b4-62d8c9e17a6e.png">

Your image isn't chrome rotated on my browser

I used the same image as seen from the screenshot and result is same, no issues

**Comment by yangyxd** [comment] 2020-06-17 01:53
There will be problems with chrome browsers and mobile phones.

**Comment by TahaTesser** [comment] 2020-06-17 08:12
Hi @yangyxd 
I am not sure this is related to image_picker, since using any image, picked image direction isn't change

**Comment by iapicca** [comment] 2020-07-08 14:09
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by iapicca** 2020-07-08 14:09 UTC
Labels: in triage
