### ISSUE TITLE
TextFormField - lines overlap with increased textScaleFactor

### ISSUE THREAD

**Issue by vvinogradsky** [flutter/flutter#34416] opened 2019-06-13 16:22 UTC
When used without a strutStyle, the internal line height is being calculated incorrectly, lines overlap. Adding even an empty strutStyle fixes the issue. Should it really require a strutStyle to work correctly?

```dart
class MultilineTextApp extends StatelessWidget {
  static const TITLE = 'Multiline Test';

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: TITLE,
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(
          appBar: AppBar(
            title: Text(TITLE),
          ),
          body: TextFormField(
            decoration: InputDecoration(
              filled: true,
            ),
            keyboardType: TextInputType.multiline,
            style: TextStyle(color: Colors.red.withOpacity(0.6)),
            maxLines: null,
            //strutStyle: StrutStyle(),  // uncomment to fix
          )),
      builder: (BuildContext context, Widget child) {
        return MediaQuery(
          data: MediaQuery.of(context).copyWith(
            textScaleFactor: 2,
          ),
          child: child,
        );
      },
    );
  }
}
```

Without a strutStyle:
![image](https://user-images.githubusercontent.com/7515118/59449777-c1c56380-8dd5-11e9-952d-8e161be1baee.png)

With strutStyle: StrutStyle():
![image](https://user-images.githubusercontent.com/7515118/59449790-cbe76200-8dd5-11e9-8764-80c5c96ec18e.png)

**Comment by eseidelGoogle** [comment] 2020-01-09 23:23
Doesn't seem to reproduce on the Web, but that may be that the Web doesn't yet support multiline?
https://gist.github.com/eseidelGoogle/98f313bae0355b4066963bf537f01608

This is probably a @GaryQian question.

**Comment by GaryQian** [comment] 2020-01-09 23:55
I was unable to reproduce on Samnsung Note 9 and a Pixel 4 XL.

Do you mind sharing what device you are seeing this on? This looks like it is device specific.

**Comment by vvinogradsky** [comment] 2020-01-10 03:58
I believe I was setting up this this test case in the emulator. The only physical device I had at the time was Samsung Galaxy S7, but I don't remember if I used it to run the test.

**Comment by GaryQian** [comment] 2020-03-05 21:01
Can you see if you can get it to repro on a real device, or if that is not feasible, at least a variety of emulators? I am still unable to repro this, so not sure how to proceed.

**Comment by TahaTesser** [comment] 2020-04-17 13:18
Hi @vvinogradsky 
Without additional information, we are unfortunately not sure how to resolve this issue. We are
therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the
bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.

**Closed by TahaTesser** 2020-04-17 13:18 UTC
Labels: a: text input, a: typography, f: material design, framework, waiting for customer response
