### ISSUE TITLE
startup problem (slow) with integrated `FlutterFragment` in a native  Android App 

### ISSUE THREAD

**Issue by evansherry** [flutter/flutter#40807] opened 2019-09-19 02:52 UTC
I want to integrate Flutter in the Android native project. When I add a `FlutterFragment`, the black screen appears. I try to add a `launchView`, which solves the black screen problem, but the white screen takes too long, so the experience is very bad.

 Is there any solution?

**Comment by janmoppel** [comment] 2019-09-19 08:42
Hello @evansherry !

Thank you for posting an issue.
Can you please attach an output of the `flutter doctor -v` command as well? Also, it would be very helpful if you could create a self-contained repository with provided code. So that your issue could be easily reproduced.

This question seems to be a good question for the StackOverflow as well. Flutter has a very active and helpful community there, so feel free to post it there too.

Thank you.

**Comment by evansherry** [comment] 2019-09-20 03:08
Hello @janmoppel
  Sorry,  This is my flutter doctor information：
[✓] Flutter (Channel master, v1.10.1-pre.21, on Mac OS X 10.13.6 17G7024, locale
    zh-Hans-CN)
    • Flutter version 1.10.1-pre.21 at /Users/XXX/code/Flutter
    • Framework revision e2325600ea (2 weeks ago), 2019-09-05 17:08:50 -0700
    • Engine revision ef2a452124
    • Dart version 2.5.0 (build 2.5.0-dev.4.0 be66176534)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/XXX/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      Support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/XXX/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • CocoaPods version 1.7.1

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 36.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1343-b01)

App.java
 ```
   public void onCreate() {
        super.onCreate();
        FlutterMain.startInitialization(this);
        FlutterMain.ensureInitializationComplete(this, null);
    }

```
CustomFlutterFragment
```
    public FlutterWrapView onCreateView(@NonNull LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        return new FlutterWrapView(getActivity(), getLifecycle(), mRoute);
    }
```
FlutterView and launchView are added to FlutterWrapView. The launchView refers to the implementation of launchView in FlutterActivityDelegate, which is a white background.
When I evoke the FlutterFragment in the native until the first frame of the flutterView is displayed, the interval is as long as 800 ms.

**Comment by evansherry** [comment] 2019-09-20 03:09
Hello @janmoppel
  Sorry,  This is my flutter doctor information：
[✓] Flutter (Channel master, v1.10.1-pre.21, on Mac OS X 10.13.6 17G7024, locale
    zh-Hans-CN)
    • Flutter version 1.10.1-pre.21 at /Users/XXX/code/Flutter
    • Framework revision e2325600ea (2 weeks ago), 2019-09-05 17:08:50 -0700
    • Engine revision ef2a452124
    • Dart version 2.5.0 (build 2.5.0-dev.4.0 be66176534)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/XXX/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      Support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/XXX/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • CocoaPods version 1.7.1

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 36.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1343-b01)

App.java
 ```
   public void onCreate() {
        super.onCreate();
        FlutterMain.startInitialization(this);
        FlutterMain.ensureInitializationComplete(this, null);
    }

```
CustomFlutterFragment
```
    public FlutterWrapView onCreateView(@NonNull LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        return new FlutterWrapView(getActivity(), getLifecycle(), mRoute);
    }
```
FlutterView and launchView are added to FlutterWrapView. The launchView refers to the implementation of launchView in FlutterActivityDelegate, which is a white background.
When I evoke the FlutterFragment in the native until the first frame of the flutterView is displayed, the interval is as long as 800 ms.

**Comment by timsneath** [comment] 2020-01-02 21:07
We have added new documentation on how to pre-warm the `FlutterEngine` to minimize loading time on first invocation. You can find it here: https://flutter.dev/docs/development/add-to-app/performance

Closing this issue for now, but please feel free to open a new one if you experience a reproducible bug with this scenario.

**Closed by timsneath** 2020-01-02 21:07 UTC
Labels: a: existing-apps, d: stackoverflow, severe: performance, ▣ platform-android
