### ISSUE TITLE
reporting error as instructed by output

### ISSUE THREAD

**Issue by polina-c** [flutter/flutter#49958] opened 2020-02-02 03:52 UTC
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

```
══╡ EXCEPTION CAUGHT BY FOUNDATION LIBRARY ╞════════════════════════════════════════════════════════
The following assertion was thrown while dispatching notifications for FocusNode:
Assertion failed: org-dartlang-app:///packages/flutter/src/rendering/box.dart:1691:12
hasSize
"RenderBox was not laid out: RenderEditable#c01bd NEEDS-LAYOUT NEEDS-PAINT"

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
https://github.com/flutter/flutter/issues/new?template=BUG.md

When the exception was thrown, this was the stack:
package:build_web_compilers/src/dev_compiler/C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/err
ors.dart 196:49  throw_
package:build_web_compilers/src/dev_compiler/C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/err
ors.dart 26:3    assertFailed
package:flutter/src/rendering/box.dart 1691:12
get size
package:flutter/src/widgets/editable_text.dart 1747:40
[_updateSizeAndTransform]
package:flutter/src/widgets/editable_text.dart 1433:7
[_openInputConnection]
package:flutter/src/widgets/editable_text.dart 1459:7
[_openOrCloseInputConnectionIfNeeded]
package:flutter/src/widgets/editable_text.dart 1725:5
[_handleFocusChanged]
package:flutter/src/foundation/change_notifier.dart 206:23
notifyListeners
package:flutter/src/widgets/focus_manager.dart 815:5
[_notify]
package:flutter/src/widgets/focus_manager.dart 1413:11
[_applyFocusChange]
package:build_web_compilers/src/dev_compiler/C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/schedule_microtask.dart 43:11
_microtaskLoop
package:build_web_compilers/src/dev_compiler/C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/schedule_microtask.dart 52:5
_startMicrotaskLoop
package:build_web_compilers/src/dev_compiler/C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart
168:15           <fn>

The FocusNode sending notification was:
FocusNode#41f30([PRIMARY FOCUS])
════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by dnfield** [comment] 2020-02-02 05:26
Can you share a simple test case that reproduces this?

This message can sometimes get printed out erroneously - sometimes it's due to an error in user code rather than the framework . We've recently fixed that, but it's not on stable yet.  Please also include the output of flutter doctor -v.

**Comment by polina-c** [comment] 2020-02-03 00:31
Sure:
1. Clone https://github.com/polina-c/flutter-auth-ui
2. Then run:

cd examples/always_sign_in
flutter pub get
flutter run -d chrome

The app will start and you should see the message. The error does not affect functionality though. Everything works perfectly.

**Comment by ditman** [comment] 2020-04-06 21:54
This must have gotten fixed elsewhere, I can't reproduce the issue in the latest `master` channel:

<details>
<summary><tt>flutter doctor -v</tt></summary>

```
dit@dit:~/github/flutter-auth-ui/example/always_sign_in$ flutter doctor -v
[✓] Flutter (Channel master, v1.18.1-pre.21, on Linux, locale en_US.UTF-8)
    • Flutter version 1.18.1-pre.21 at /usr/local/google/home/dit/github/flutter
    • Framework revision e3e189219b (20 minutes ago), 2020-04-06 14:31:38 -0700
    • Engine revision df257e59c2
    • Dart version 2.8.0 (build 2.8.0-dev.20.0 1210d27678)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at /usr/local/google/home/dit/Android/Sdk
    • Platform android-29, build-tools 29.0.1
    • Java binary at: /opt/android-studio-with-blaze-3.5/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[!] Android Studio (version 3.4)
    • Android Studio at /opt/android-studio-with-blaze-3.4
    • Flutter plugin version 38.2.1
    • Dart plugin version 183.6270
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] Android Studio (version 3.5)
    • Android Studio at /opt/android-studio-with-blaze-3.5
    • Flutter plugin version 40.2.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.43.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.9.1

[✓] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 80.0.3987.163
    • Web Server • web-server • web-javascript • Flutter Tools

! Doctor found issues in 1 category.
```

</details>

<img width="1285" alt="Screen Shot 2020-04-06 at 2 50 27 PM" src="https://user-images.githubusercontent.com/1255594/78608847-6bb72600-7816-11ea-94d6-ada0927fcc8f.png">

@polina-c can you please confirm if you're still seeing the issue?

**Comment by iapicca** [comment] 2020-05-29 13:55
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by iapicca** 2020-05-29 13:55 UTC
Labels: framework, platform-web, waiting for customer response
