### ISSUE TITLE
[Image_Picker] Exception after taping in blank space between Cancel and Shutter button on iOS

### ISSUE THREAD

**Issue by DamianC64** [flutter/flutter#110325] opened 2022-08-26 08:05 UTC
## Steps to Reproduce

1. Run image picker with ImageSource.camera on iOS
2. Tap blank space between Cancel and Shutter button

**Expected results:** 
Nothing should happen I think?

**Actual results:** 
Camera screen is called again with error in logs:
```
[log] Cancelled by a second request
      #0      ImagePickerApi.pickImage (package:image_picker_ios/src/messages.g.dart:133:7)
      <asynchronous suspension>
      #1      ImagePickerIOS.getImage (package:image_picker_ios/image_picker_ios.dart:168:26)
      <asynchronous suspension>
```

**Code example:**
```
   try {
      final maxSize = Platform.isAndroid ? 2200.0 : null;
      image = await ImagePicker().pickImage(
        source: imageSource,
        maxHeight: maxSize,
        maxWidth: maxSize,
      );
    } on PlatformException catch (error, stack) {
      log(error.message, stackTrace: stack);
    }
```

**flutter doctor -v**
```
[✓] Flutter (Channel stable, 2.10.5, on macOS 12.5.1 21G83 darwin-x64, locale en-PL)
    • Flutter version 2.10.5 at /Users/x/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (4 months ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2
```

Issue occured on iPhone 11 with iOS 15.6
image_picker: ^0.8.5+3

![image](https://user-images.githubusercontent.com/112159739/186853242-fdc4d8c0-866f-4e98-bb5b-3bb4457b2ecc.png)

**Comment by danagbemava-nc** [comment] 2022-08-26 10:37
Hi @DamianC64, this is a duplicate of https://github.com/flutter/flutter/issues/14720. 

Kindly follow up in the linked issue for updates. Please upvote the original issue.

Closing from here as duplicate. 

Thank you

**Closed by danagbemava-nc** 2022-08-26 10:37 UTC
Labels: in triage
