### ISSUE TITLE
Camera Plugin -  (Usb camera not detected)

### ISSUE THREAD

**Issue by savankumar** [flutter/flutter#71136] opened 2020-11-24 07:24 UTC
my issue is with getavailableCamera() return only 2 camera.

i have attached external camera usb stick (which contain four camera) with android tablet device.

but its not detected. getavailableCamera() always return total 2 camera. it should be 5.

please help me to solved this issue.

**Comment by darshankawar** [comment] 2020-11-24 09:04
Closing this as duplicate of [42413](https://github.com/flutter/flutter/issues/42413)

**Closed by darshankawar** 2020-11-24 09:04 UTC
