### ISSUE TITLE
 MediaQuery does not report correct orientation on Windows

### ISSUE THREAD

**Issue by AbdeMohlbi** [flutter/flutter#156001] opened 2024-10-01 15:52 UTC
### Steps to reproduce

consider running this code on windows :

### Expected results

The MediaQuery should correctly detect the screen orientation on both Android and Windows platforms
or the docs should mention that `MediaQuery` does not work normally.

### Actual results

by playing with window u could notice that MediaQuery  does snot report the correct orrientation and instead does report based on the height and width of the window. if this is expected then section in the docs should mention this

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: OrientationScreen(),
    );
  }
}

class OrientationScreen extends StatefulWidget {
  @override
  _OrientationScreenState createState() => _OrientationScreenState();
}

class _OrientationScreenState extends State<OrientationScreen> {
  @override
  Widget build(BuildContext context) {
    // Get the screen size and orientation using MediaQuery
    final Size screenSize = MediaQuery.of(context).size;
    final Orientation orientation = MediaQuery.of(context).orientation;

    return Scaffold(
      appBar: AppBar(title: Text('MediaQuery Example')),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Text(
              'Orientation: ${orientation == Orientation.portrait ? 'Portrait' : 'Landscape'}',
              style: TextStyle(fontSize: 24),
            ),
            SizedBox(height: 20),
            Text(
              'Screen size: ${screenSize.width.toStringAsFixed(2)} x ${screenSize.height.toStringAsFixed(2)}',
              style: TextStyle(fontSize: 24),
            ),
          ],
        ),
      ),
    );
  }
}

```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[√] Flutter (Channel master, 3.26.0-1.0.pre.207, on Microsoft Windows [version 10.0.19045.4239], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 35.0.0-rc4)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.3.2)
[√] Android Studio (version 2024.1)
[√] VS Code (version 1.93.1)
[√] Connected device (3 available)
[√] Network resources

• No issues found!
```

</details>

**Comment by danagbemava-nc** [comment] 2024-10-02 07:58
This feature has not yet been implemented. See https://github.com/flutter/flutter/issues/74597

Closing in favor of the issue linked above. 

Thank you

**Closed by danagbemava-nc** 2024-10-02 07:58 UTC
Labels: in triage

**Comment by AbdeMohlbi** [comment] 2024-10-02 10:13
> This feature has not yet been implemented. See https://github.com/flutter/flutter/issues/74597
> 
> Closing in favor of the issue linked above. 
> 
> Thank you 

Thanks for your reply but fom what i see the linked issue does propose adding a methode to get the current orientation, i'm reporting a bug in the MediaQuery

**Comment by danagbemava-nc** [comment] 2024-10-03 05:52
Hi @AbdeMohlbi, the actual issue is that the framework doesn't currently have a way to get the correct orientation, what we have with MediaQuery is just an approximation based on the height & width of the current screen (not the device) which is what you're also reporting. Since your issue will be fixed when the framework adds the correct orientation, this is a duplicate of the issue linked above
