### ISSUE TITLE
Can't play videos from vimeo links.

### ISSUE THREAD

**Issue by teekamsuthar** [flutter/flutter#51558] opened 2020-02-27 13:37 UTC
I'm trying to fetch and play my vimeo videos through video_player plugin, but it's throwing errors loading the url:
```
> E/ExoPlayerImplInternal( 7500): Source error.
> E/ExoPlayerImplInternal( 7500): com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor, AmrExtractor) could read the stream.
> E/ExoPlayerImplInternal( 7500): 	at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractorHolder.selectExtractor(ExtractorMediaPeriod.java:973)
> E/ExoPlayerImplInternal( 7500): 	at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:891)
> E/ExoPlayerImplInternal( 7500): 	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381)
> E/ExoPlayerImplInternal( 7500): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
> E/ExoPlayerImplInternal( 7500): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
> E/ExoPlayerImplInternal( 7500): 	at java.lang.Thread.run(Thread.java:919)
> 
```

**Comment by TahaTesser** [comment] 2020-02-27 13:53
Hi @teekamsuthar 
You can't play video Vimeo links in `video_player`
You must provide a video source which ends with video format

Example `http://www.sample-videos.com/video123/mp4/720/big_buck_bunny_720p_20mb.mp4`
Try the [example](https://raw.githubusercontent.com/flutter/plugins/master/packages/video_player/video_player/example/lib/main.dart)
Closing as this isn't issue with `video_player`
Thank you

**Closed by TahaTesser** 2020-02-27 13:53 UTC

**Comment by Aryankaushik2312** [comment] 2021-06-29 06:34
I'm trying to fetch and play my backend videos through the video_player plugin, but it's throwing errors loading the URL:

Link end with .mp4

E/ExoPlayerImplInternal(10564): Playback error
E/ExoPlayerImplInternal(10564):   com.google.android.exoplayer2.ExoPlaybackException: Source error
E/ExoPlayerImplInternal(10564):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:554)
E/ExoPlayerImplInternal(10564):       at android.os.Handler.dispatchMessage(Handler.java:102)
E/ExoPlayerImplInternal(10564):       at android.os.Looper.loop(Looper.java:223)
E/ExoPlayerImplInternal(10564):       at android.os.HandlerThread.run(HandlerThread.java:67)
E/ExoPlayerImplInternal(10564):   Caused by: com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (FragmentedMp4Extractor, Mp4Extractor, FlvExtractor, FlacExtractor, WavExtractor, AmrExtractor, PsExtractor, OggExtractor, TsExtractor, MatroskaExtractor, AdtsExtractor, Ac3Extractor, Ac4Extractor, Mp3Extractor) could read the stream.
E/ExoPlayerImplInternal(10564):       at com.google.android.exoplayer2.source.BundledExtractorsAdapter.init(BundledExtractorsAdapter.java:92)
E/ExoPlayerImplInternal(10564):       at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1024)
E/ExoPlayerImplInternal(10564):       at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:415)
E/ExoPlayerImplInternal(10564):       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/ExoPlayerImplInternal(10564):       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/ExoPlayerImplInternal(10564):       at java.lang.Thread.run(Thread.java:923)
