### ISSUE TITLE
[url_launcher: 6.0.x] CanLaunch() function not working correctly

### ISSUE THREAD

**Issue by italodea** [flutter/flutter#82496] opened 2021-05-14 01:00 UTC
I tried all the examples from the [plugin page](https://pub.dev/packages/url_launcher), but still not working for me. 

The code:

``` dart
import 'package:flutter/material.dart';
import 'package:url_launcher/url_launcher.dart';

const _url = 'https://flutter.dev';

void main() => runApp(
      const MaterialApp(
        home: Material(
          child: Center(
            child: ElevatedButton(
              onPressed: _launchURL,
              child: Text('Show Flutter homepage'),
            ),
          ),
        ),
      ),
    );

void _launchURL() async =>
    await canLaunch(_url) ? await launch(_url) : throw 'Could not launch $_url';
```

The output:

`Could not lauch https://flutter.dev`

================
More  #details
```shell
flutter --version
Flutter 2.0.6 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 1d9032c7e1 (2 weeks ago) • 2021-04-29 17:37:58 -0700
Engine • revision 05e680e202
Tools • Dart 2.12.3
```

**Comment by darshankawar** [comment] 2021-05-14 09:32
@italodea 
Not sure on which platform are you trying to run this on, but I tried your code sample using latest master on iOS simulator, on which there were no issues:


https://user-images.githubusercontent.com/67046386/118251361-1c393400-b4c5-11eb-9230-8229e84d6699.mov


<details>
<summary>flutter doctor -v</summary>

```

[✓] Flutter (Channel master, 2.3.0-2.0.pre.203, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-GB)
    • Flutter version 2.3.0-2.0.pre.203 at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c533ab6515 (3 hours ago), 2021-05-13 23:04:02 -0700
    • Engine revision 0507f4a9a7
    • Dart version 2.14.0 (build 2.14.0-114.0.dev)

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (3 available)
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 90.0.4430.212

! Doctor found issues in 1 category.

```

</details>

**Comment by italodea** [comment] 2021-05-14 15:08
Thanks to reply @darshankawar .
Sorry, the platform is the android, i tried on emulator and physical device, both running Android 11 and another physical device running Android 10.
My OS and hardware:
Linux Mint Cinnamon 20
AMD Ryzen 5 2500U
12Gb DDR4

```shell
italo@330s:~$ flutter doctor -v
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.6, on Linux, locale pt_BR.UTF-8)
    • Flutter version 2.0.6 at /home/italo/bin/flutter
    • Framework revision 1d9032c7e1 (2 weeks ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/italo/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2.20.04)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] VS Code (version 1.56.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.22.0

[✓] Connected device (2 available)
    • SM F415F (mobile) • 192.168.18.102:5555 • android-arm64  • Android 11 (API 30)
    • Chrome (web)      • chrome              • web-javascript • Google Chrome 90.0.4430.212

! Doctor found issues in 1 category.

```

**Comment by darshankawar** [comment] 2021-05-17 06:32
@italodea 
Thanks for the details. Can you try on latest master and see if issue still persists ?

**Comment by italodea** [comment] 2021-05-17 15:45
```shell
italo@330s:~$ flutter --version
Flutter 2.3.0-2.0.pre.241 • channel master •
https://github.com/flutter/flutter.git
Framework • revision c410ae35d7 (6 hours ago) • 2021-05-17 05:54:02 -0400
Engine • revision 26e217e6c3
Tools • Dart 2.14.0 (build 2.14.0-edge.a527411e5100a0a4f48c4009087a1b988aa784af)

```

The error persists

E/flutter ( 6853): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: Could not launch https://flutter.dev
E/flutter ( 6853): #0      _launchURL (package:connection_status_app/main.dart:20:50)
E/flutter ( 6853): <asynchronous suspension>
E/flutter ( 6853):

**Comment by italodea** [comment] 2021-05-17 19:58
Aditional info:
I searched on telegram other users with same problem, and constated that problem is with canLaunch() function.
If i replace
```dart
void _launchURL() async =>
    await canLaunch(_url) ? await launch(_url) : throw 'Could not launch $_url';
```
to
```dart
void _launchURL() async =>
    await launch(_url);
```
the problem is solved.

**Comment by darshankawar** [comment] 2021-05-18 06:14
@italodea 
Can you try something like below:
```

if (await canLaunch(url)) {
await launch(url);
} else {
throw 'could not launch $url';
}
```

Because I am wondering how replacing `canLaunch` with `launch` would work, since the original implementation worked on iOS, so not sure how it would fail on Android.

**Comment by italodea** [comment] 2021-05-19 02:53
```dart
void _launchURL() async {
  if (await canLaunch(_url)) {
    await launch(_url);
  } else {
    throw 'could not launch $_url';
  }
}
```

same error


Running with unsound null safety
For more information see https://dart.dev/null-safety/unsound-null-safety
E/flutter ( 9514): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: could not launch https://flutter.dev
E/flutter ( 9514): #0      _launchURL (package:connection_status_app/main.dart:23:5)
E/flutter ( 9514): <asynchronous suspension>
E/flutter ( 9514):

**Comment by darshankawar** [comment] 2021-05-19 06:16
Keeping this issue open for further investigation as I am unable to replicate it using Mac OS. (Maybe a Linux + Android specific issue).

**Comment by italodea** [comment] 2021-05-20 00:35
Ok, maybe i will try it on windows + android and confirm here if the bug persists.

**Comment by Hasilt** [comment] 2021-05-23 03:31
Hello, I'm using windows + android.

**Comment by italodea** [comment] 2021-05-25 21:24
Sorry for taking so long. I finally managed to test this code on windows 10. The output is the same.
![Windows 10](https://i.ibb.co/SnWfNYS/Captura-de-Tela-4.png)

``` shell
[√] Flutter (Channel stable, 2.2.0, on Microsoft Windows [versÃ£o 10.0.18362.1500], locale pt-BR)
    • Flutter version 2.2.0 at C:\flutter
    • Framework revision b22742018b (11 days ago), 2021-05-14 19:12:57 -0700
    • Engine revision a9d88a4d18
    • Dart version 2.13.0

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\italo\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files (x86)\Common Files\Oracle\Java\javapath\java.exe
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_291-b10)
    • All Android licenses accepted.

[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] Connected device (1 available)
    • SM F415F (mobile) • 192.168.18.5:5555 • android-arm64 • Android 11 (API 30)
````

**Comment by deepak-kumar-swain** [comment] 2021-06-07 15:35
I/m also facing the same issue with Android 11, MacOS BigSur

**Comment by dleurs** [comment] 2021-06-23 07:39
Same here, url_launcher not working on Android 11 Samsung s21

**Comment by TharaniP** [comment] 2021-06-23 09:23
Same here, url_launcher not working on Android 11 Samsung A30

**Comment by nickolight** [comment] 2021-06-24 15:26
The same issue for me. 
await canLaunch(url) - returns 'false' despite await launch(url) works correctly

**Comment by choudharydhaka** [comment] 2021-07-19 23:30
Please add a hostname to the data tag. 
```
  <!-- If your app opens https URLs -->
  <intent>
    <action android:name="android.intent.action.VIEW" />
    <category android:name="android.intent.category.BROWSABLE" />
    <data android:scheme="https" android:host="TODO_ADD_HOSTNAME"/>
  </intent>

```

[Ref](https://developer.android.com/guide/components/intents-common#ViewUrl)

**Comment by latygindenis** [comment] 2021-07-20 05:12
For custom scheme you can try add android:host="*"
`        <intent>
            <action android:name="android.intent.action.VIEW" />
            <data android:scheme="some_custom_scheme"
                  android:host="*" />
        </intent>
`

**Comment by yulkin2002** [comment] 2021-07-27 20:00
same issue on Android 9 device, solution in 63727 doesn't seem to apply to me as I'm using targetSdkVersion and compileSdkVersion 29.

**Comment by gvv-ua** [comment] 2021-08-05 11:23
For me some urls on Android 11 work fine, but youtube links (for example [https://www.youtube.com/watch?v=b_sQ9bMltGU)](https://www.youtube.com/watch?v=b_sQ9bMltGU) don't work.

**Comment by mamonraab** [comment] 2021-08-16 07:25
i faced same error using win and linux for android developments
and solve it with these steps
1-updated my gradle-wrapper.properties to gradle-6.7.1-all.zip
`distributionUrl=https\://services.gradle.org/distributions/gradle-6.7.1-all.zip
`

2- updated my classpath  in  android/build.gradle to com.android.tools.build:gradle:4.2.1
`buildscript {
    ext.kotlin_version = '1.3.50'
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:4.2.1'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"

    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
`

3- add the <queries> above <application> to my AndroidManifest.xml in app/src/main/AndroidManifest.xml
`
    <queries>
        
        <intent>
            <action android:name="android.intent.action.VIEW" />
            <data android:scheme="https" />
        </intent>
        
        <intent>
            <action android:name="android.intent.action.DIAL" />
            <data android:scheme="tel" />
        </intent>
        
        <intent>
            <action android:name="android.intent.action.SEND" />
            <data android:mimeType="*/*" />
        </intent>
    </queries>`

and now everything work fine

**Comment by Wes1324** [comment] 2021-09-12 16:33
[This line](https://github.com/flutter/plugins/blob/master/packages/url_launcher/url_launcher/android/src/main/java/io/flutter/plugins/urllauncher/UrlLauncher.java#L41) of the canLaunch method uses Android's Intent.resolveActivity(PackageManager) method to find a component that can handle the given URL. If it doesn't find a suitable component, then canLaunch returns false.

I believe that Intent.resolveActivity(PackageManager) is one of the methods that is affected by Android's recent package visibility changes. Thus, adding the <queries ... /> stuff to the Android manifest file allows the resolveActivity method to 'see' the components that can handle a given URL, meaning canLaunch() will start returning true.

However, the launch() method does not invoke Intent.resolveActivity(PackageManager). Instead, launch() uses the startActivity() method, as can be seen [here](https://github.com/flutter/plugins/blob/master/packages/url_launcher/url_launcher/android/src/main/java/io/flutter/plugins/urllauncher/UrlLauncher.java#L82). 

The [Android documentation](https://developer.android.com/training/package-visibility/use-cases#open-urls-browser-or-other-app) states that 'the startActivity() method is unaffected by the system's package visibility behaviour'. This is the reason why I believe launch() works for URLs that canLaunch() determines to be invalid.

This revelation makes me question the purpose of canLaunch, given that canLaunch is not representative of how launch() works. As the [dartdoc](https://github.com/flutter/plugins/blob/master/packages/url_launcher/url_launcher/lib/url_launcher.dart#L15) for the launch() method states, 'the returned future completes with a PlatformException on invalid URLs and schemes which cannot be handled, that is when canLaunch would complete with false.' For that reason, I would like to suggest that canLaunch be deprecated and users of the url_launcher package are simply advised to surround the call to launch() with a try-catch block. What do people think of this suggestion?

**Comment by Agondev** [comment] 2021-11-27 19:10
> For me some urls on Android 11 work fine, but youtube links (for example https://www.youtube.com/watch?v=b_sQ9bMltGU ) don't work.

Same here. All links work except YT.

**Comment by stuartmorgan** [comment] 2023-01-01 16:29
Closing as it looks like most of the comments here are duplicates of Android query issues, which have now been explained in the README, and some individual cases like YouTube are duplicates of other resolved issues.

If anyone still has issues using `canLaunch` in the current version after reading the current README, please file a new issue for the platform, with detailed reproduction steps.

Note also that the README generally recommends *against* using `canLaunch` now. In particular, in examples like https://github.com/flutter/flutter/issues/82496#issuecomment-842591253 there is no benefit to using `canLaunch`, only downsides.

**Closed by stuartmorgan** 2023-01-01 16:29 UTC
Labels: platform-android, plugin, p: first party, platform-linux, p: url_launcher, passed first triage, P4

**Comment by laspi94** [comment] 2023-02-07 03:52
I had exactly the same problem in url_launcher version: ^6.1.8
and use the launchUrlString() method instead of canLaunchUrlString() in case it helps anyone currently
