### ISSUE TITLE
Google sign in button for web causes UI glitches when scrolling on Android Chrome (with CanvasKit)

### ISSUE THREAD

**Issue by azalisa** [flutter/flutter#149764] opened 2024-06-05 19:52 UTC
### Steps to reproduce

Versions used:
- Flutter 3.22.1 (stable), with CanvasKit renderer
- `google_sign_in: ^6.2.1`
- `google_sign_in_web: ^0.12.4`
- `google_sign_in_platform_interface: ^2.4.5`

Devices: multiple Android phones running Chrome browser (happens on emulator as well, for example Pixel 4 API 31 emulator)

Steps to reproduce:
1. Create a plain Flutter web app with a Google sign in button inside of a scrollable container, and other widgets below the Google sign in button
2. Build the app for web, using CanvasKit renderer
```
# the issue happens with either `build` or `run`
flutter build web --web-renderer canvaskit --release
flutter run --release --web-renderer canvaskit -d web-server --web-hostname=0.0.0.0 --web-port=3000
```
3. Access the app from an Android device, using Chrome browser (I did this with `ngrok`, but the same issue happens with other methods of hosting the app)

### Expected results

The view should scroll normally, and the widgets below the sign in button should not have visual glitches.

### Actual results

Widgets placed below the Google sign in button will have visual glitches during/after scrolling, such as covering the Google sign in button. The effect is especially visible when using `Text` widgets, because the text is rendered multiple times.

Extra info:
- the bug seems to have appeared after upgrading from Flutter version 3.16.3 to 3.19.5, regardless of the package versions used; it continues to happen with the latest stable Flutter, and it also happens on the beta channel (`3.22.0-0.3.pre`)
- the bug does not happen when using the HTML web renderer
- as far as I tested, the bug does not seem to happen on other browsers, or on iOS devices, or on non-mobile devices
- the bug happens in both `debug` and `release` modes, neither one logs any errors during the scrolling

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:google_sign_in/google_sign_in.dart';
import 'package:google_sign_in_platform_interface/google_sign_in_platform_interface.dart';
import 'package:google_sign_in_web/google_sign_in_web.dart' as web;

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      title: 'Flutter Demo',
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key});

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final googleSignIn = GoogleSignIn(
    clientId: '<redacted>',
    serverClientId: null,
    scopes: ['email'],
  );

  @override
  Widget build(BuildContext context) {
    final screenHeight = MediaQuery.of(context).size.height;
    return Scaffold(
      appBar: AppBar(title: const Text('demo')),
      body: SingleChildScrollView(
        child: Column(
          children: <Widget>[
            Container(height: screenHeight / 2, width: 100, color: Colors.blue),
            SizedBox(
              height: 48,
              child: (GoogleSignInPlatform.instance as web.GoogleSignInPlugin).renderButton(),
            ),
            Container(
              height: screenHeight / 2,
              width: 100,
              color: Colors.red,
              child: const Text('Hello World!'),
            ),
          ],
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/flutter/flutter/assets/20167883/ddfa31e5-78f7-43b6-aac9-b84a38f923ba

</details>

### Logs

<details open><summary>Logs</summary>

```console
# command
flutter run --verbose --release --web-renderer canvaskit -d web-server --web-hostname=0.0.0.0 --web-port=3000

# log output
[   +9 ms] executing: sw_vers -productName
[  +27 ms] Exit code 0 from: sw_vers -productName
[        ] macOS
[        ] executing: sw_vers -productVersion
[  +16 ms] Exit code 0 from: sw_vers -productVersion
[        ] 13.2.1
[        ] executing: sw_vers -buildVersion
[  +15 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 22D68
[        ] executing: uname -m
[   +5 ms] Exit code 0 from: uname -m
[        ] x86_64
[   +6 ms] executing: sysctl hw.optional.arm64
[   +6 ms] Exit code 1 from: sysctl hw.optional.arm64
[        ] sysctl: unknown oid 'hw.optional.arm64'
[ +147 ms] executing: sysctl hw.optional.arm64
[   +6 ms] Exit code 1 from: sysctl hw.optional.arm64
[        ] sysctl: unknown oid 'hw.optional.arm64'
[        ] executing: xcrun xcodebuild -version
[ +223 ms] Exit code 0 from: xcrun xcodebuild -version
[        ] Xcode 14.2
           Build version 14C18
[   +3 ms] executing: xcrun xcdevice list --timeout 5
[   +6 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'LegacyCanvasKitRemover' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +63 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[  +10 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +87 ms] Skipping pub get: version match.
[  +48 ms] Found plugin google_sign_in at /Users/lazaalissa/.pub-cache/hosted/pub.dev/google_sign_in-6.2.1/
[   +6 ms] Found plugin google_sign_in_android at /Users/lazaalissa/.pub-cache/hosted/pub.dev/google_sign_in_android-6.1.24/
[   +5 ms] Found plugin google_sign_in_ios at /Users/lazaalissa/.pub-cache/hosted/pub.dev/google_sign_in_ios-5.7.6/
[   +8 ms] Found plugin google_sign_in_web at /Users/lazaalissa/.pub-cache/hosted/pub.dev/google_sign_in_web-0.12.4/
[  +96 ms] Found plugin google_sign_in at /Users/lazaalissa/.pub-cache/hosted/pub.dev/google_sign_in-6.2.1/
[   +6 ms] Found plugin google_sign_in_android at /Users/lazaalissa/.pub-cache/hosted/pub.dev/google_sign_in_android-6.1.24/
[   +2 ms] Found plugin google_sign_in_ios at /Users/lazaalissa/.pub-cache/hosted/pub.dev/google_sign_in_ios-5.7.6/
[   +5 ms] Found plugin google_sign_in_web at /Users/lazaalissa/.pub-cache/hosted/pub.dev/google_sign_in_web-0.12.4/
[  +81 ms] Found plugin google_sign_in at /Users/lazaalissa/.pub-cache/hosted/pub.dev/google_sign_in-6.2.1/
[   +1 ms] Found plugin google_sign_in_android at /Users/lazaalissa/.pub-cache/hosted/pub.dev/google_sign_in_android-6.1.24/
[   +1 ms] Found plugin google_sign_in_ios at /Users/lazaalissa/.pub-cache/hosted/pub.dev/google_sign_in_ios-5.7.6/
[   +2 ms] Found plugin google_sign_in_web at /Users/lazaalissa/.pub-cache/hosted/pub.dev/google_sign_in_web-0.12.4/
[  +33 ms] Generating /Users/lazaalissa/prototypes/web_html_glitch/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[ +118 ms] Launching lib/main.dart on Web Server in release mode...
[  +93 ms] Found plugin google_sign_in at /Users/lazaalissa/.pub-cache/hosted/pub.dev/google_sign_in-6.2.1/
[   +1 ms] Found plugin google_sign_in_android at /Users/lazaalissa/.pub-cache/hosted/pub.dev/google_sign_in_android-6.1.24/
[   +1 ms] Found plugin google_sign_in_ios at /Users/lazaalissa/.pub-cache/hosted/pub.dev/google_sign_in_ios-5.7.6/
[   +2 ms] Found plugin google_sign_in_web at /Users/lazaalissa/.pub-cache/hosted/pub.dev/google_sign_in_web-0.12.4/
[  +91 ms] generated_plugin_registrant.dart not found. Skipping.
[   +1 ms] Compiling lib/main.dart for the Web...
[   +8 ms] Initializing file store
[   +7 ms] Done initializing file store
[  +53 ms] Skipping target: web_entrypoint
[   +1 ms] Skipping target: gen_localizations
[   +1 ms] invalidated build due to missing files: /Users/lazaalissa/prototypes/web_html_glitch/web/*/index.html, /Users/lazaalissa/prototypes/web_html_glitch/web/flutter_bootstrap.js
[   +1 ms] web_templated_files: Starting due to {InvalidatedReasonKind.outputMissing: The following outputs were missing: /Users/lazaalissa/prototypes/web_html_glitch/build/web/*/index.html, InvalidatedReasonKind.inputMissing: The following inputs were missing: /Users/lazaalissa/prototypes/web_html_glitch/web/*/index.html,/Users/lazaalissa/prototypes/web_html_glitch/web/flutter_bootstrap.js}
[   +1 ms] web_static_assets: Starting due to {InvalidatedReasonKind.outputMissing: The following outputs were missing: /Users/lazaalissa/prototypes/web_html_glitch/.dart_tool/flutter_build/0b5a4a496649dd38ac70a947289da176/flutter.js,/Users/lazaalissa/prototypes/web_html_glitch/.dart_tool/flutter_build/0b5a4a496649dd38ac70a947289da176/canvaskit/skwasm.js,/Users/lazaalissa/prototypes/web_html_glitch/.dart_tool/flutter_build/0b5a4a496649dd38ac70a947289da176/canvaskit/skwasm.js.symbols,/Users/lazaalissa/prototypes/web_html_glitch/.dart_tool/flutter_build/0b5a4a496649dd38ac70a947289da176/canvaskit/canvaskit.js.symbols,/Users/lazaalissa/prototypes/web_html_glitch/.dart_tool/flutter_build/0b5a4a496649dd38ac70a947289da176/canvaskit/skwasm.wasm,/Users/lazaalissa/prototypes/web_html_glitch/.dart_tool/flutter_build/0b5a4a496649dd38ac70a947289da176/canvaskit/chromium/canvaskit.js.symbols,/Users/lazaalissa/prototypes/web_html_glitch/.dart_tool/flutter_build/0b5a4a496649dd38ac70a947289da176/canvaskit/chromium/canvaskit.js,/Users/lazaalissa/prototypes/web_html_glitch/.dart_tool/flutter_build/0b5a4a496649dd38ac70a947289da176/canvaskit/chromium/canvaskit.wasm,/Users/lazaalissa/prototypes/web_html_glitch/.dart_tool/flutter_build/0b5a4a496649dd38ac70a947289da176/canvaskit/canvaskit.js,/Users/lazaalissa/prototypes/web_html_glitch/.dart_tool/flutter_build/0b5a4a496649dd38ac70a947289da176/canvaskit/canvaskit.wasm,/Users/lazaalissa/prototypes/web_html_glitch/.dart_tool/flutter_build/0b5a4a496649dd38ac70a947289da176/canvaskit/skwasm.worker.js}
[ +735 ms] Skipping target: dart2js
[   +3 ms] web_static_assets: Complete
[  +28 ms] Warning: In index.html:37: Local variable for "serviceWorkerVersion" is deprecated. Use "{{flutter_service_worker_version}}" template token instead.
[   +2 ms] Warning: In index.html:46: "FlutterLoader.loadEntrypoint" is deprecated. Use "FlutterLoader.load" instead.
[   +3 ms] web_templated_files: Complete
[ +137 ms] Skipping target: web_release_bundle
[ +151 ms] web_service_worker: Starting due to {InvalidatedReasonKind.inputChanged: The following inputs have updated contents: build/web/flutter_bootstrap.js,build/web/index.html}
[ +265 ms] web_service_worker: Complete
[   +2 ms] Persisting file store
[   +6 ms] Done persisting file store
[  +18 ms] Compiling lib/main.dart for the Web... (completed in 1,418ms)
[        ] ✓ Built build/web
[  +49 ms] lib/main.dart is being served at http://0.0.0.0:3000
[        ] The web-server device requires the Dart Debug Chrome extension for debugging. Consider using the Chrome or Edge devices for an improved development workflow.
[   +5 ms] 🔥  To hot restart changes while running, press "r" or "R".
[        ] For a more detailed help message, press "h". To quit, press "q".
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[!] Flutter (Channel stable, 3.22.1, on macOS 13.2.1 22D68 darwin-x64, locale en-US)
    • Flutter version 3.22.1 on channel stable at /Users/lazaalissa/fvm/versions/3.22.1
    ! Warning: `flutter` on your path resolves to /Users/lazaalissa/fvm/versions/stable/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/lazaalissa/fvm/versions/3.22.1. Consider adding /Users/lazaalissa/fvm/versions/3.22.1/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /usr/local/Cellar/dart-sdk/3.0.5/libexec/bin/dart, which is not inside your current Flutter SDK checkout at /Users/lazaalissa/fvm/versions/3.22.1. Consider adding /Users/lazaalissa/fvm/versions/3.22.1/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a14f74ff3a (2 weeks ago), 2024-05-22 11:08:21 -0500
    • Engine revision 55eae6864b
    • Dart version 3.4.1
    • DevTools version 2.34.3
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/lazaalissa/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/lazaalissa/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    ! Flutter recommends a minimum Xcode version of 15.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)

[✓] VS Code (version 1.89.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.90.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 13.2.1 22D68 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 125.0.6422.142

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
```

</details>

**Comment by huycozy** [comment] 2024-06-06 08:32
Hi @azalisa 
I checked the issue on my end but couldn't reproduce it. You can watch my demo video below:

<details>
<summary>Demo</summary>

https://github.com/flutter/flutter/assets/104349824/73bef8b8-d2fd-4d4c-8b28-4e22fbd5524e
</details>

Do you modify web module code (index.html for example)? Could you share a minimal sample project on a GitHub repository so I can try it on my end? Thanks!

**Comment by azalisa** [comment] 2024-06-06 12:38
Hi @huycozy, thanks for checking this! There was nothing custom about my repro app, but your reply got me thinking about the version of Chrome being used, and I can confirm that after updating to the latest version of Chrome (125.0.6422.164), the bug doesn't happen anymore 😅 So you can close this issue now. For what it's worth, the latest version I can confirm had the bug was Chrome 98.0.4758.101, which was launched in Feb 2022, so it was quite outdated.

**Comment by huycozy** [comment] 2024-06-07 03:30
Glad you found it. It may be helpful for others facing this issue as well. Closing as solved.

**Closed by huycozy** 2024-06-07 03:30 UTC
Labels: in triage
