### ISSUE TITLE
Fail to pick image using image_picker plugin on Android 10

### ISSUE THREAD

**Issue by here4you81** [flutter/flutter#52518] opened 2020-03-13 03:48 UTC
In Android 10, there is a problem that images cannot be loaded from the gallery using the image_picker plugin.

https://github.com/flutter/flutter/issues/40339

This seems to be due to Android 10's external storage access policy.

I solved the problem by adding the requestLegacyExternalStorage property to the AndroidManifest file.
It would be nice if the content was added to the readme page of the image_picker plugin.

**Comment by TahaTesser** [comment] 2020-03-13 08:30
Duplicate of [#40339](https://github.com/flutter/flutter/issues/40339)

**Closed by TahaTesser** 2020-03-13 08:30 UTC
