### ISSUE TITLE
[tool_crash] FileSystemException: Cannot open file, OS Error: The system cannot find the file specified., errno = 2

### ISSUE THREAD

**Issue by hazims** [flutter/flutter#128185] opened 2023-06-04 00:29 UTC
## Command
```
flutter create mobile_pr
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Cannot open file, OS Error: The system cannot find the file specified.
, errno = 2
```
#0      _File.throwIfError (dart:io/file_impl.dart:675:7)
#1      _File.openSync (dart:io/file_impl.dart:490:5)
#2      _File.readAsBytesSync (dart:io/file_impl.dart:574:18)
#3      _File.readAsStringSync (dart:io/file_impl.dart:624:18)
#4      ForwardingFile.readAsStringSync (package:file/src/forwarding/forwarding_file.dart:99:16)
#5      ErrorHandlingFile.readAsStringSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:218:22)
#6      _runSync (package:flutter_tools/src/base/error_handling_io.dart:590:14)
#7      ErrorHandlingFile.readAsStringSync (package:flutter_tools/src/base/error_handling_io.dart:217:12)
#8      CreateBase._computeTemplateManifest (package:flutter_tools/src/commands/create_base.dart:665:37)
#9      CreateBase._templateManifest (package:flutter_tools/src/commands/create_base.dart:652:43)
#10     CreateBase._templateManifest (package:flutter_tools/src/commands/create_base.dart)
#11     CreateBase.renderMerged (package:flutter_tools/src/commands/create_base.dart:478:25)
#12     CreateBase.generateApp (package:flutter_tools/src/commands/create_base.dart:503:29)
#13     CreateCommand.runCommand (package:flutter_tools/src/commands/create.dart:350:37)
<asynchronous suspension>
#14     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1336:27)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#16     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#17     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:296:9)
<asynchronous suspension>
#18     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
```
```
[32m[✓][39m Flutter (Channel stable, 3.10.3, on Microsoft Windows [Version 10.0.19045.2965], locale en-US)
    [32m•[39m Flutter version 3.10.3 on channel stable at C:\Flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision f92f44110e (2 days ago), 2023-06-01 18:17:33 -0500
    [32m•[39m Engine revision 2a3401c9bb
    [32m•[39m Dart version 3.0.3
    [32m•[39m DevTools version 2.23.1

[32m[✓][39m Windows Version (Installed version of Windows is version 10 or higher)

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    [32m•[39m Android SDK at C:\Users\Administrator\AppData\Local\Android\sdk
    [32m•[39m Platform android-32, build-tools 32.1.0-rc1
    [32m•[39m Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[32m[✓][39m Visual Studio - develop for Windows (Visual Studio Professional 2022 17.5.3)
    [32m•[39m Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Professional
    [32m•[39m Visual Studio Professional 2022 version 17.5.33516.290
    [32m•[39m Windows 10 SDK version 10.0.22000.0

[32m[✓][39m Android Studio (version 2022.2)
    [32m•[39m Android Studio at C:\Program Files\Android\Android Studio
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)

[32m[✓][39m VS Code (version 1.77.1)
    [32m•[39m VS Code at C:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code
    [32m•[39m Flutter extension version 3.66.0

[32m[✓][39m Connected device (3 available)
    [32m•[39m Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19045.2965]
    [32m•[39m Chrome (web)      • chrome  • web-javascript • Google Chrome 113.0.5672.127
    [32m•[39m Edge (web)        • edge    • web-javascript • Microsoft Edge 113.0.1774.57

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[32m•[39m No issues found!

```

## Flutter Application Metadata
No pubspec in working directory.

**Comment by danagbemava-nc** [comment] 2023-06-05 07:05
Closing this as a duplicate of https://github.com/flutter/flutter/issues/91559.

**Closed by danagbemava-nc** 2023-06-05 07:05 UTC
Labels: in triage
