### ISSUE TITLE
Webview crashes the app on iOS 14

### ISSUE THREAD

**Issue by nicolasvac** [flutter/flutter#71316] opened 2020-11-27 16:20 UTC
## Steps to Reproduce

```dart
import 'dart:io';

import 'package:flutter/material.dart';
import 'package:fluttertoast/fluttertoast.dart';
import 'package:mylunch/Aziendale/ContractManager.dart';
import 'package:mylunch/configs/app_config.dart';
import 'package:rxdart/rxdart.dart';
import 'package:webview_flutter/webview_flutter.dart';

import '../../app_localization.dart';
import '../risto_widgets.dart';

class AuthWebviewPage extends StatefulWidget {
  @override
  _AuthWebviewPageState createState() => _AuthWebviewPageState();
}

class _AuthWebviewPageState extends State<AuthWebviewPage> {
  final BehaviorSubject<bool> loadingController = BehaviorSubject<bool>();

  @override
  void initState() {
    super.initState();

    // Enable hybrid composition.
    if (Platform.isAndroid) WebView.platform = SurfaceAndroidWebView();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: RistoWidgets.creaAppBar(
          title: Text(
            AppLocalizations.of(context).translate('signin'),
          ),
          actions: [
            StreamBuilder(
                stream: loadingController.stream,
                initialData: false,
                builder: (context, snapshot) {
                  if (snapshot.data)
                    return Container(
                      margin: const EdgeInsets.symmetric(vertical: 10.0, horizontal: 16.0),
                      child: RistoWidgets.loaderCenter(),
                    );
                  else
                    return SizedBox();
                })
          ]),
      body: WebView(
        javascriptMode: JavascriptMode.unrestricted,
        gestureNavigationEnabled: false,
        onWebViewCreated: (webViewController) {
          // Pulisci le sessioni ad ogni webview creata
          CookieManager().clearCookies();
        },
        initialUrl: App.instance.currentContract.webviewAuthEndpoint,
        onPageStarted: (_) => loadingController.sink.add(true),
        onPageFinished: (_) => loadingController.sink.add(false),
        javascriptChannels: <JavascriptChannel>[
          JavascriptChannel(
            name: 'MyLunchCloseWebView',
            onMessageReceived: (_) {
              Navigator.pop(context);
            },
          ),
          JavascriptChannel(
            name: 'MyLunchWebviewToken',
            onMessageReceived: (token) {
              ContractManager().getPrimaryContract().then((contract) {
                contract
                    .setRCToken(token.message)
                    .then((result) => result ? Navigator.pushReplacementNamed(context, '/Init') : Fluttertoast.showToast(msg: 'Errore salvataggio token'));
              });
            },
          ),
        ].toSet(),
      ),
    );
  }

  @override
  void dispose() {
    loadingController.close();
    super.dispose();
  }
}
```

**Expected results:** See the webview

**Actual results:** 
Webview completely crashes the app, and closes it.
The crash doesnt happen everytime, but only sometimes.

I do have 3 testflight crashes dump that im willing to upload, but privately only for the flutter devs.

<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel stable, 1.22.4, on macOS 11.0.1 20B29 darwin-x64, locale it-IT)
    • Flutter version 1.22.4 at /Users/nicolas/dev/flutter_sdk/flutter
    • Framework revision 1aafb3a8b9 (2 weeks ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/nicolas/Library/Android/Sdk
    • Platform android-30, build-tools 29.0.2
    • ANDROID_HOME = /Users/nicolas/Library/Android/Sdk
    • Java binary at: /Users/nicolas/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.6953283/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.9.3

[!] Android Studio (version 4.1)
    • Android Studio at /Users/nicolas/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.6953283/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[!] IntelliJ IDEA Ultimate Edition (version 2020.2.4)
    • IntelliJ at /Users/nicolas/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    • Dart plugin version 201.8538.45
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.49.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.1

[✓] Connected device (1 available)
    • ANE LX1 (mobile) • xx • android-arm64 • Android 9 (API 28)

! Doctor found issues in 2 categories.

```

</details>

**Comment by Abhishek01039** [comment] 2020-11-29 05:01
Hello @nicolasvac 
can you please provide `flutter run -v`?
Thanks

**Comment by darshankawar** [comment] 2020-11-30 06:58
@nicolasvac 
The code sample you provided seem to have 3rd party plugins and custom code such as `import 'package:mylunch/Aziendale/ContractManager.dart';` due to which I am unable to run it. Please provide a minimal code sample without any 3rd party plugins that we can simply copy paste and run in IDE that will help to replicate the issue.

Also, is the crash occuring locally or only when you publish it to testflight ?

**Comment by andriivachasov-ah** [comment] 2020-11-30 13:43
I am having the same behavior on simulator (iOS 14.2) and iPhone 11 (iOS 14.2) using release build.
@darshankawar here's the code:
```
import 'dart:io';

import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

class WebViewScreen extends StatefulWidget {
  const WebViewScreen({Key key}) : super(key: key);

  @override
  _WebViewScreenState createState() => _WebViewScreenState();
}

class _WebViewScreenState extends State<WebViewScreen> {
  WebViewController _webViewController;
  bool isLoading = true;

  @override
  void initState() {
    if (Platform.isAndroid) {
      WebView.platform = SurfaceAndroidWebView();
    }
    super.initState();
  }

  @override
  Widget build(BuildContext context) => WillPopScope(
        onWillPop: () async {
          if (await _webViewController?.canGoBack()) {
            await _webViewController.goBack();
            return false;
          }
          return true;
        },
        child: Scaffold(
          body: Stack(
            fit: StackFit.expand,
            children: [
              WebView(
                initialUrl: 'https://google.com',
                onWebViewCreated: (controller) => _webViewController = controller,
              ),
            ],
          ),
        ),
      );
}
```

flutter doctor output:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 1.24.0-10.2.pre, on Mac OS X 10.15.7 19H15 darwin-x64, locale en-UA)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2020.1)
[✓] IntelliJ IDEA Community Edition (version 2020.1.1)
[✓] VS Code (version 1.47.3)
[✓] Connected device (3 available)

• No issues found!
```

**Comment by andriivachasov-ah** [comment] 2020-12-03 09:14
FIY The problem was caused by the interference with videoplayer in my case.
I have two screens one of which has a videoplayer and a button, which navigates to the webview screen.
There's no useful information in the logs so i decided to do some experiments.
Pausing the videoplayer before navigation fixed the crash.

**Comment by nicolasvac** [comment] 2020-12-06 01:20
Hello @darshankawar
the crash happens only on iOS, and the only way we have tested it is from testflights.
I already have 3 testflights dumps that i can upload for investigation.

**Comment by Plegizplegiz** [comment] 2020-12-06 09:32
su 6.12.2020 klo 3.22 nicolasvac <notifications@github.com> kirjoitti:

**Comment by darshankawar** [comment] 2020-12-07 05:41
@nicolasvac 
Please provide the crash log for further analysis.

**Comment by brandonhub** [comment] 2020-12-13 19:55
I'm experiencing the same behavior, but only on test flight builds. Oddly enough, if I run a release build on my phone, I experience no issues.

@andriivachasov-ah you were able to reproduce this on a simulator? That is odd because whenever I try to run a run in release mode on a sim, flutter stops me and says `Exception: Release mode is not supported for iPhone 12.`

**Comment by pedromassangocode** [comment] 2021-01-06 12:22
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2021-01-06 12:22 UTC
Labels: in triage, waiting for customer response
