### ISSUE TITLE
[Material Icons] Inconsistencies in Material Icons naming conventions.

### ISSUE THREAD

**Issue by bernaferrari** [flutter/flutter#94894] opened 2021-12-08 23:02 UTC
![image](https://user-images.githubusercontent.com/351125/145304947-17e08d0a-ff31-430b-a83f-969733d872be.png)

If you look at [this](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/icons.dart), 60fps becomes `sixty_fps`. There is probably a number -> name conversion happening (because of Dart) that the Google Fonts official docs are unaware.

Posting here because I don't think they have an open tracker and this directly affects Flutter.

**Comment by bernaferrari** [comment] 2021-12-08 23:06
Also, 6_ft_apart has two underlines in Flutter:

![image](https://user-images.githubusercontent.com/351125/145305395-aca82f8d-4897-47c2-83a3-9929343d7c5b.png)

It was changed a few months ago:
![image](https://user-images.githubusercontent.com/351125/145305360-69e0dc35-afca-441b-8377-744b62a4b678.png)

**Comment by maheshmnj** [comment] 2021-12-09 09:11
Hi @bernaferrari, Thanks for filing the issue. I am able to reproduce the issue on master and stable channel. Double underscores are added to certain icons. 

> There is probably a number -> name conversion happening (because of Dart) that the Google Fonts official docs are unaware.

This doesn't seem related to number to word conversion since icons like `class_rounded` also have double underscores added.
 
 In total there are 7 icons with double underscores
```dart
  static const IconData six__ft_apart = IconData(0xe02a, fontFamily: 'MaterialIcons');
  static const IconData six__ft_apart_sharp = IconData(0xe72a, fontFamily: 'MaterialIcons');
  static const IconData six__ft_apart_rounded = IconData(0xf509, fontFamily: 'MaterialIcons');
  static const IconData six__ft_apart_outlined = IconData(0xee1c, fontFamily: 'MaterialIcons');
  static const IconData class__sharp = IconData(0xe862, fontFamily: 'MaterialIcons');
  static const IconData class__rounded = IconData(0xf641, fontFamily: 'MaterialIcons');
  static const IconData class__outlined = IconData(0xef54, fontFamily: 'MaterialIcons');
```

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.8.0, on macOS 12.0.1 21A559 darwin-arm, locale en-GB)
    • Flutter version 2.8.0 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cf44000065 (11 hours ago), 2021-12-08 14:06:50 -0800
    • Engine revision 40a99c5951
    • Dart version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.61.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (4 available)
    • Redmi K20 Pro (mobile) • 192.168.1.5:5555                     • android-arm64  • Android 11
      (API 30)
    • iPhone 11 (mobile)     • FC644E6C-7F02-40E5-9998-1F0CD162FBD8 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.0.1
      21A559 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome
      96.0.4664.93

• No issues found!
```

```
[✓] Flutter (Channel master, 2.6.0-12.0.pre.975, on macOS 12.0.1 21A559 darwin-arm, locale en-GB)
    • Flutter version 2.6.0-12.0.pre.975 at /Users/mahesh/Documents/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9b1bbdbd16 (4 hours ago), 2021-12-09 00:04:07 -0500
    • Engine revision 30b0105c72
    • Dart version 2.16.0 (build 2.16.0-85.0.dev)
    • DevTools version 2.9.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.61.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (4 available)
    • Redmi K20 Pro (mobile) • 192.168.1.5:5555                     • android-arm64  • Android 11
      (API 30)
    • iPhone 11 (mobile)     • FC644E6C-7F02-40E5-9998-1F0CD162FBD8 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.0.1
      21A559 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome
      96.0.4664.93

• No issues found!
```
</details>

**Comment by bernaferrari** [comment] 2021-12-09 11:58
> This doesn't seem related to number to word conversion

Yeah, you are right. What I was trying to say is that in the official docs it says 60fps and in Flutter it is sixty, so someone need to fix the Google Fonts doc.

**Comment by boldt** [comment] 2022-01-19 16:39
Any update regarting the double underscores in some icons (see #94918)?

**Comment by guidezpl** [comment] 2022-01-20 08:59
This is an easy fix, I'll get a PR out shortly

**Comment by guidezpl** [comment] 2022-01-20 09:08
For what's on Google Fonts' website, I'll work with the web team to get a better solution for these identifiers

**Comment by guidezpl** [comment] 2022-02-07 14:23
I'll close this issue since the remaining work is internal (b/181773926) but rest assured, I've got a nice solution ready which will show accurate Flutter IDs and also indicate when icons are unavailable.

**Closed by guidezpl** 2022-02-07 14:23 UTC
Labels: framework, f: material design, has reproducible steps, found in release: 2.6, found in release: 2.8
