### ISSUE TITLE
Flutter app running in Chrome gets stuck on Performing Hot Restart on latest stable, but works on latest master

### ISSUE THREAD

**Issue by JimTacobs** [flutter/flutter#77818] opened 2021-03-10 16:36 UTC
Related to https://github.com/flutter/flutter/issues/67194 and https://github.com/flutter/flutter/issues/71560.

This has been happening for 2 days now. I'm running my app in Chrome and can only change things within the main.dart file. Anything outside of it, the process gets stuck on 'Waiting for connection from debug service on Chrome...', having to manually refresh my chrome page to see any updated I've made. I've tried all solutions that are suggested in even somewhat related issues, nothing works.

<details>
<summary>Flutter version</summary>
Flutter 2.0.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision c5a4b4029c (6 days ago) • 2021-03-04 09:47:48 -0800
Engine • revision 40441def69
Tools • Dart 2.12.0
</details>

<details>
<summary>Android studio version</summary>
Android Studio 4.1.2
Build #AI-201.8743.12.41.7042882, built on December 20, 2020
Runtime version: 1.8.0_242-release-1644-b3-6915495 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.7
GC: ParNew, ConcurrentMarkSweep
Memory: 1979M
Cores: 12
Registry: ide.new.welcome.screen.force=true, external.system.auto.import.disabled=true
Non-Bundled Plugins: String Manipulation, com.intellij.marketplace, Dart, io.flutter
</details>

<details>
<summary>Run console (third line only appears once I manually refresh the page)</summary>
Performing hot restart...
Waiting for connection from debug service on Chrome...
Restarted application in 627,526ms.
</details>

<details>
<summary>flutter doctor -v</summary>
[✓] Flutter (Channel stable, 2.0.1, on Mac OS X 10.15.7 19H524 darwin-x64, locale en-NL)
    • Flutter version 2.0.1 at /Users/timjacobs/flutter
    • Framework revision c5a4b4029c (6 days ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/timjacobs/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Users/timjacobs/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.7042882/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Android Studio (version 4.1)
    • Android Studio at /Users/timjacobs/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.7042882/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.54.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (2 available)
    • iPhone 12 Pro (mobile) • BECFDABA-BABD-4B9C-B54E-5E765A49709F • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 89.0.4389.82

• No issues found!

</details>

<details>
<summary>Reproducable steps</summary>
While I haven't managed to reproduce this in a minimal code example, I do have a small repository with which this is easily reproduced (at least for me) https://github.com/TimJacobus/cijfers_enzo

To reproduce, clone and run the app (debug or no debug, doesn't matter) and first change the text inside the Scaffold in **main.dart**, you'll notice it hot reloads immediately after saving. Now open **hello.dart** (lib/shared/widgets) and change the text of the ElevatedButton. At this point I get completely stuck waiting for the hot reload, having to refresh the webpage to continue working.

I've tried changing the routing, removing riverpod, hooks, and font_awesome. All didn't make any difference.
</details>

**Comment by darshankawar** [comment] 2021-03-11 07:52
@TimJacobus 
I looked at your reproducible code, but it seems to have 3rd party plugins. It'll be great if you could provide a truncated but [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) without any 3rd party plugins, that we can use to verify this issue.

**Comment by TimJacobus** [comment] 2021-03-11 08:23
Hello Darshan, I've removed all 3rd party plugins from my code and the issue disappeared... I'll add back my plugins step by step and notify the creators of the plugin which causes the problems. I'll close this, thank you.

**Comment by TimJacobus** [comment] 2021-03-11 10:05
Actually nevermind, I stripped my code step-by-step of all third party packages, and still got the same problem of my hot restart being stuck. If you check the repo in my first post, you'll find it now completely stripped of 3rd party packages and unused code. 

Steps to reproduce:
1. Clone repo and run app in Chrome
2. Change text inside **main.dart**: hot restart works perfectly every time.
3. Change text inside **hello.dart**, which is the button in the top right of your screen, inside the AppBar. Gets stuck on 'Performing hot restart' immediately.

<details>
<summary>flutter doctor -v</summary>
[✓] Flutter (Channel stable, 2.0.1, on Mac OS X 10.15.7 19H524 darwin-x64, locale en-NL)
    • Flutter version 2.0.1 at /Users/timjacobs/flutter
    • Framework revision c5a4b4029c (7 days ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/timjacobs/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Users/timjacobs/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.7042882/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Android Studio (version 4.1)
    • Android Studio at /Users/timjacobs/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.7042882/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.54.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (2 available)
    • iPhone 12 Pro (mobile) • BECFDABA-BABD-4B9C-B54E-5E765A49709F • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 89.0.4389.82

• No issues found!

</details>

**Comment by darshankawar** [comment] 2021-03-11 13:33
Thanks @TimJacobus for updated repo. I cloned it and was able to replicate this issue on latest stable. Although the same doesn't occur on latest master, wherein, the hot restart for `hello.dart` works properly.

1. On latest master (2.1.0-11.0.pre.205), updating `main.dart` and `hello.dart` one by one and pressing `r` to restart works:

<img width="193" alt="Screenshot 2021-03-11 at 6 44 33 PM" src="https://user-images.githubusercontent.com/67046386/110794710-07a9a700-829c-11eb-97b2-b8e8e229dc09.png">

<img width="200" alt="Screenshot 2021-03-11 at 6 44 50 PM" src="https://user-images.githubusercontent.com/67046386/110794717-08dad400-829c-11eb-9782-15902f03a158.png">

```
Performing hot restart...                                           3.3s
Restarted application in 3,346ms.

Performing hot restart...                                          283ms
Restarted application in 284ms.

Performing hot restart...                                           3.0s
Restarted application in 3,045ms.

Performing hot restart...                                          267ms
Restarted application in 268ms.

Performing hot restart...                                        2,947ms
Restarted application in 2,947ms.
```

2. While, carrying out same steps on latest stable, only `main.dart` changes are updated, whereas, hot restart gets stuck, as shown below:

<img width="612" alt="Screenshot 2021-03-11 at 6 58 10 PM" src="https://user-images.githubusercontent.com/67046386/110794852-2f007400-829c-11eb-88a1-d46ec58e5775.png">


<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.0.1, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.0.1 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision c5a4b4029c (7 days ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.54.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • Mac OS X 10.15.4 19E2269
      darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 89.0.4389.82

! Doctor found issues in 1 category.


```

</details>

**Comment by harshshah1992** [comment] 2021-04-22 18:00
Hello Guys,

Channel master, 2.2.0-11.0.pre.226

I was in master channel. If we add flutter driver or test package dependency then it's also creating issue.

In that case, we have to remove driver package and need to check after that.

It works for me.

Please try the same thing with same or any other packages which you have added.

Thank you!

**Comment by cweagans** [comment] 2021-05-10 16:25
I was having this problem on the latest Stable, but it went away when I switched to the Beta channel.

**Comment by jonahwilliams** [comment] 2021-06-08 23:03
If this is working on master than the bug was fixed

**Closed by jonahwilliams** 2021-06-08 23:03 UTC
Labels: found in release: 2.0, has reproducible steps, platform-web, tool
