### ISSUE TITLE
Memory leaks when receiving GRPC continuos server stream

### ISSUE THREAD

**Issue by directx11** [flutter/flutter#139650] opened 2023-12-06 10:42 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Server application written in C++ using GRPC to send continuous data stream.
2. Client application written in Flutter wich calls GRPC RPC to open and receive continuos stream. Receiving is tested using two ways:

Using simple loop solution:
```
call = client.getTestStream(Empty());

try {
  await for (var data in call) {}
} catch (e) {
	print("Error: $e");
}
```

or
```
call = client.getTestStream(Empty());
subscription = callFeederList.listen(
  (data) {
  }
```

### Expected results

Data are received from server and no crashes, memory leaks or other issueas observed.

### Actual results

Data are received, no any particular issues observed except memory consumption by flutter application. After checking by Flutter DevTools Memory View, seems that _List and _DelayedData objects are continuosly growing in size while receiving data:

![obraz](https://github.com/flutter/flutter/assets/2478093/343ac46e-661c-4a2d-b7f5-4211a29c9384)

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
PS C:\> flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.16.0, on Microsoft Windows [Version 10.0.22631.2715], locale pl-PL)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Enterprise 2022 17.6.5)
[√] Android Studio (version 2022.2)
[√] VS Code (version 1.84.2)
[√] Connected device (3 available)
[√] Network resources

• No issues found!
```

</details>

**Comment by huycozy** [comment] 2023-12-07 05:31
Hi @directx11 
Could you provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this? I'm not sure if your server is exposed to the internet. If it is, you may only share Flutter sample code with defined domain inside. Thanks!

**Comment by huycozy** [comment] 2023-12-08 04:31
It's recommended to provide a [minimal sample code](https://stackoverflow.com/help/minimal-reproducible-example) rather than a complex project code or binaries so that we can look into it quickly.

**Comment by directx11** [comment] 2023-12-21 11:06
Sorry for being late with example. Here https://github.com/directx11/leak.git You could find minimal example, which shows incereasing memory usage problem. There two parts, server written in C++ and Flutter client. C++ part is build using cmake (see repo readme file). If You need any assistance with build let me know.

**Comment by danagbemava-nc** [comment] 2023-12-22 06:58
Hi @directx11, thanks for the sample. 

Quick question, what platform(s) are you experiencing this issue on?

**Comment by directx11** [comment] 2023-12-22 08:32
Hi. Observed both on Windows 11 and Linux Ubuntu 22 run on HyperV virtual machine.

**Comment by danagbemava-nc** [comment] 2023-12-27 09:49
Hi @directx11, after running the cmake commands in both directories before running the flutter app, I get this error

```
flutter: error gRPC Error (code: 14, codeName: UNAVAILABLE, message: Error connecting: SocketException: Connection refused (OS Error: Connection refused, errno = 111), address = 127.0.0.1, port = 39212, details: null, rawResponse: null, trailers: {})
```

Is there something I might be missing?

**Comment by directx11** [comment] 2023-12-27 10:20
> Hi @directx11, after running the cmake commands in both directories before running the flutter app, I get this error
> flutter: error gRPC Error (code: 14, codeName: UNAVAILABLE, message: Error connecting: SocketException: Connection refused (OS Error: Connection refused, errno = 111), address = 127.0.0.1, port = 39212, details: null, rawResponse: null, trailers: {})
> Is there something I might be missing?

Seems, that before running flutter app, c++ server is not run. Did You run 'grpc_test' application in server folder first? It should be available there if build was fine.

**Comment by danagbemava-nc** [comment] 2023-12-28 07:33
I was under the impression that the cmake build should run the app (at least that's what it seemed like from the readme). I run the `grpc_test` application but no data seems to be transmitted. I don't get any in the flutter app. Is there anything else I need to do? Also, can you check the package that the `_List` and `_DelayedData` objects belong to? You should see it when you hover over them in the devtools

**Comment by directx11** [comment] 2023-12-28 10:16
> I was under the impression that the cmake build should run the app (at least that's what it seemed like from the readme). I run the `grpc_test` application but no data seems to be transmitted. I don't get any in the flutter app. Is there anything else I need to do? Also, can you check the package that the `_List` and `_DelayedData` objects belong to? You should see it when you hover over them in the devtools

I've updated readme file with details how to run both sides. Also added logs both on  the server and client side to show GRPC communication. Let me know if still some assistance is needed, we could establish a call or chat if needed.

**Comment by danagbemava-nc** [comment] 2023-12-29 07:03
Hi @directx11, now when I run `cmake build .` in the server directory after running `cmake .` it fails with the error below. 
I tested on 2 different oses to just to be sure

```
CMake Error at CMakeLists.txt:10 (find_package):
  Could not find a package configuration file provided by "protobuf" with any
  of the following names:

    protobufConfig.cmake
    protobuf-config.cmake

  Add the installation prefix of "protobuf" to CMAKE_PREFIX_PATH or set
  "protobuf_DIR" to a directory containing one of the above files.  If
  "protobuf" provides a separate development package or SDK, be sure it has
  been installed.


-- Configuring incomplete, errors occurred!
```

**Comment by directx11** [comment] 2024-01-02 14:37
Hi. It looks like cmake in third_partry is not run first. What systems you tried on? I tested it on Ubuntu 22 and it seems to work fine. If You have Ubuntu 22 i could provide ready to use executable binary,

**Comment by huycozy** [comment] 2024-01-03 05:00
Hi @directx11 
I can set up server and run the Flutter app now. But I can't see the memory issue as you have. I checked this on the latest Flutter stable 3.16.5 and Ubuntu 22.04.3 LTS 6.2.0-37-generic.

I'm your main branch which runs the counter app. But I see it seems you are on a different code. Please confirm this to make sure we are checking on the same source code.


<details>
<summary>Demo recorded video</summary>

[Screencast from 03-01-2024 11:53:44.webm](https://github.com/flutter/flutter/assets/104349824/ab10cb9f-8f51-4353-9250-0c1618bae71e)

</details>

<details>
<summary>flutter doctor -v (stable & master)</summary>

```bash
[✓] Flutter (Channel stable, 3.16.5, on Ubuntu 22.04.3 LTS 6.2.0-37-generic, locale en_US.UTF-8)
    • Flutter version 3.16.5 on channel stable at /home/huynq/Documents/Working/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 78666c8dc5 (13 days ago), 2023-12-19 16:14:14 -0800
    • Engine revision 3f3e560236
    • Dart version 3.2.3
    • DevTools version 2.28.4

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0-rc3)
    • Android SDK at /home/huynq/Android/Sdk/
    • Platform android-33, build-tools 34.0.0-rc3
    • Java binary at: /home/huynq/Documents/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 14.0.0-1ubuntu1.1
    • cmake version 3.22.1
    • ninja version 1.10.1
    • pkg-config version 0.29.2

[✓] Android Studio (version 2022.3)
    • Android Studio at /snap/android-studio/128/android-studio
    • Flutter plugin version 76.2.2
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] Android Studio (version 2021.1)
    • Android Studio at /home/huynq/Documents/android-studio/
    • Flutter plugin version 67.0.1
    • Dart plugin version 211.7817
    • android-studio-dir = /home/huynq/Documents/android-studio/
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code (version 1.84.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.78.0

[✓] VS Code (version unknown)
    • VS Code at /snap/code/current
    • Flutter extension version 3.78.0
    ✗ Unable to determine VS Code version.

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 22.04.3 LTS 6.2.0-37-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 119.0.6045.123

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

```bash
[!] Flutter (Channel master, 3.18.0-18.0.pre.47, on Ubuntu 22.04.3 LTS 6.2.0-37-generic, locale en_US.UTF-8)
    • Flutter version 3.18.0-18.0.pre.47 on channel master at /home/huynq/Documents/Working/flutter_master
    ! Warning: `flutter` on your path resolves to /home/huynq/Documents/Working/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /home/huynq/Documents/Working/flutter_master. Consider adding /home/huynq/Documents/Working/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /home/huynq/Documents/Working/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /home/huynq/Documents/Working/flutter_master. Consider adding /home/huynq/Documents/Working/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3df4e735d5 (4 days ago), 2023-12-29 14:07:39 -0500
    • Engine revision 9e03a57cde
    • Dart version 3.3.0 (build 3.3.0-273.0.dev)
    • DevTools version 2.31.0-dev.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0-rc3)
    • Android SDK at /home/huynq/Android/Sdk/
    • Platform android-33, build-tools 34.0.0-rc3
    • Java binary at: /home/huynq/Documents/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 14.0.0-1ubuntu1.1
    • cmake version 3.22.1
    • ninja version 1.10.1
    • pkg-config version 0.29.2

[✓] Android Studio (version 2022.3)
    • Android Studio at /snap/android-studio/128/android-studio
    • Flutter plugin version 76.2.2
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] Android Studio (version 2021.1)
    • Android Studio at /home/huynq/Documents/android-studio/
    • Flutter plugin version 67.0.1
    • Dart plugin version 211.7817
    • android-studio-dir = /home/huynq/Documents/android-studio/
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code (version 1.84.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.78.0

[✓] VS Code (version 1.85.1)
    • VS Code at /snap/code/current/usr/share/code
    • Flutter extension version 3.78.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 22.04.3 LTS 6.2.0-37-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 119.0.6045.123

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>

**Comment by directx11** [comment] 2024-01-03 14:10
Hi huycozy
This is probably due to big delay between portions of data sent from server side. There was delay between next write 200ms, which lets garbage collector on client side to clean memory. Now i've changed delay to 0 (data are sent as quickly as possible, change is in repo) and let applications run for about and hour:

![obraz](https://github.com/flutter/flutter/assets/2478093/a57b6bda-fa7d-4d88-87a8-c72b4fd97e9a)
![obraz](https://github.com/flutter/flutter/assets/2478093/0ffeb63a-6e23-46f6-bf96-70cb7e27fff5)
![obraz](https://github.com/flutter/flutter/assets/2478093/76faab7e-8612-4e25-adc8-d9656ef3f6f2)

You could experiment changing delay in main.cpp file, line no 29, just uncomment line and set delay, like e.g.:

`std::this_thread::sleep_for(std::chrono::milliseconds(10));`

And let aaplications run for example one hour. But best results You will get, when there is no delay. Let's notice that there are no real data sent, only empty messages. If needed i could preapare some messages with more fields in proto structures.
Seems that garbage collector in Dart/Flutter is not able to release memory so fast. Wonder if the ony solution is slower rate data sending.

**Comment by huycozy** [comment] 2024-01-04 05:21
Thanks for the update. When I set a lower delay to 10 ms and wait for the sample app to run long enough (over 10 minutes) I can see `_List` and `_DelayedData` object sizes are continuously growing.

Although I think this is suited on [dart-lang/sdk](https://github.com/dart-lang/sdk) than here, can't find another way to detect memory issue without Flutter via Devtools. Thus, I will label this issue for other's insights. 

<details>
<summary>flutter doctor -v (stable & master)</summary>

```bash
[✓] Flutter (Channel stable, 3.16.5, on Ubuntu 22.04.3 LTS 6.2.0-37-generic, locale en_US.UTF-8)
    • Flutter version 3.16.5 on channel stable at /home/huynq/Documents/Working/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 78666c8dc5 (13 days ago), 2023-12-19 16:14:14 -0800
    • Engine revision 3f3e560236
    • Dart version 3.2.3
    • DevTools version 2.28.4

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0-rc3)
    • Android SDK at /home/huynq/Android/Sdk/
    • Platform android-33, build-tools 34.0.0-rc3
    • Java binary at: /home/huynq/Documents/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 14.0.0-1ubuntu1.1
    • cmake version 3.22.1
    • ninja version 1.10.1
    • pkg-config version 0.29.2

[✓] Android Studio (version 2022.3)
    • Android Studio at /snap/android-studio/128/android-studio
    • Flutter plugin version 76.2.2
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] Android Studio (version 2021.1)
    • Android Studio at /home/huynq/Documents/android-studio/
    • Flutter plugin version 67.0.1
    • Dart plugin version 211.7817
    • android-studio-dir = /home/huynq/Documents/android-studio/
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code (version 1.84.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.78.0

[✓] VS Code (version unknown)
    • VS Code at /snap/code/current
    • Flutter extension version 3.78.0
    ✗ Unable to determine VS Code version.

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 22.04.3 LTS 6.2.0-37-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 119.0.6045.123

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

```bash
[!] Flutter (Channel master, 3.18.0-18.0.pre.47, on Ubuntu 22.04.3 LTS 6.2.0-37-generic, locale en_US.UTF-8)
    • Flutter version 3.18.0-18.0.pre.47 on channel master at /home/huynq/Documents/Working/flutter_master
    ! Warning: `flutter` on your path resolves to /home/huynq/Documents/Working/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /home/huynq/Documents/Working/flutter_master. Consider adding /home/huynq/Documents/Working/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /home/huynq/Documents/Working/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /home/huynq/Documents/Working/flutter_master. Consider adding /home/huynq/Documents/Working/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3df4e735d5 (4 days ago), 2023-12-29 14:07:39 -0500
    • Engine revision 9e03a57cde
    • Dart version 3.3.0 (build 3.3.0-273.0.dev)
    • DevTools version 2.31.0-dev.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0-rc3)
    • Android SDK at /home/huynq/Android/Sdk/
    • Platform android-33, build-tools 34.0.0-rc3
    • Java binary at: /home/huynq/Documents/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 14.0.0-1ubuntu1.1
    • cmake version 3.22.1
    • ninja version 1.10.1
    • pkg-config version 0.29.2

[✓] Android Studio (version 2022.3)
    • Android Studio at /snap/android-studio/128/android-studio
    • Flutter plugin version 76.2.2
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] Android Studio (version 2021.1)
    • Android Studio at /home/huynq/Documents/android-studio/
    • Flutter plugin version 67.0.1
    • Dart plugin version 211.7817
    • android-studio-dir = /home/huynq/Documents/android-studio/
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code (version 1.84.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.78.0

[✓] VS Code (version 1.85.1)
    • VS Code at /snap/code/current/usr/share/code
    • Flutter extension version 3.78.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 22.04.3 LTS 6.2.0-37-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 119.0.6045.123

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>

**Comment by mraleph** [comment] 2024-01-04 09:15
@directx11 You need to place some open source license into the the reproduction repo, otherwise we can't look at the code. 

Also, do you see any memory grows if you don't attach Dev Tools? (e.g. run in release mode instead and use `ps` to measure memory consumption). Dev Tools has network profiling which retains response payloads and might skew memory measurement results. 

`_DelayedData` are data buffered by some broadcast stream - if they are growing it means some broadcast stream subscription is paused and not delivering events, or not processing events fast enough, so they accumulate.

Here is what I would recommend:

1. Check if there is a memory leak without Dev Tools (e.g. release mode). If there is no memory leak - good.
2. If there is a memory leak, check if it is an actual memory leak or it's GC not keeping up. This can be done by pressing GC button in DevTools. If you press GC button and memory goes down - then it is a GC issue and we can take a look. GC not keeping up needs to be reported to Dart SDK repo. If not - there is a leak. 
3. The leak probably should be reported to dart-grpc repo, not Dart SDK or Flutter. But best would be for you to check where `_DelayedData` are coming from with Dev Tools.

**Comment by directx11** [comment] 2024-01-04 10:02
@mraleph Thanks for feedeback. I've added MIT license to reproduction repo, hope that this is enough.
I've tried release version and it seems to grow quite fast (application name "client":

![obraz](https://github.com/flutter/flutter/assets/2478093/ef596608-cf9c-47bc-bfea-e3eec8dd8c60)
![obraz](https://github.com/flutter/flutter/assets/2478093/57331606-1ff9-4dd0-b33a-c3c8d140bb1e)
![obraz](https://github.com/flutter/flutter/assets/2478093/d6713f77-99f1-4c58-bf99-14c25504fdef)

Tried also with GC button in DevTools. Seems that memory goes down with every press, but not back exactly to initial levels, Looking simultaneously at Task Manager (on Windows), seems that memory is growing (not released any on pressing GC).

> But best would be for you to check where _DelayedData are coming from with Dev Tools.

You mean where this class is defined? Or something else? Legend shows, that this class comes from Dart SDK (green indicator):
![obraz](https://github.com/flutter/flutter/assets/2478093/dc804c6d-8cf9-48b4-a71d-e41e60d727b3)

**Comment by mraleph** [comment] 2024-01-04 12:24
Thanks. I took a quick look - this is caused by https://github.com/dart-lang/http2/commit/8917a55f467f38ee849118598c767ba5b1dcdc7a which introduced a leak into `package:http2` implementation. 

The leak is due to `_receivedFrame.add(null)` added in `Connection._handleFrameImpl` - if nobody is listening on the stream then stream will buffer indefinitely - this is a really subtle problem with Dart streams which I overlooked it in the code review here myself. We probably should not be sending information about frames if nobody is listening. 

@mosuem Could you take a look at this?

**Comment by mosuem** [comment] 2024-01-04 12:25
I think this is fixed by https://github.com/grpc/grpc-dart/pull/674 - I will speed up landing this.

**Comment by mraleph** [comment] 2024-01-04 12:27
I would have expected that we fix this on http2 side because other consumers of the package will be similarly affected as well.

**Comment by mosuem** [comment] 2024-01-04 12:28
Right. I will take a look.

**Comment by mosuem** [comment] 2024-01-11 11:18
Fixed with https://github.com/dart-lang/http2/pull/137. @jonahwilliams

**Comment by jonahwilliams** [comment] 2024-01-11 21:16
Thanks! Closing as fixed

**Closed by jonahwilliams** 2024-01-11 21:16 UTC
Labels: engine, dependency: dart, perf: memory, has reproducible steps, P1, team-engine, found in release: 3.16, found in release: 3.18

**Comment by przemek-kieszkowski** [comment] 2024-01-12 09:12
Thanks for all yours support!
