### ISSUE TITLE
The page property cannot be read when multiple PageViews are attached to the same PageController.Failed assertion: line 184 pos 7: 'positions.length == 1'

### ISSUE THREAD

**Issue by alsayedabdelbaqeyahmed** [flutter/flutter#76026] opened 2021-02-14 23:34 UTC
Iam trying to restart the quiz app but when iam press the restart i have this error message (The page property cannot be read when multiple PageViews are attached to the same PageController.Failed assertion: line 184 pos 7: 'positions.length == 1')
`       // my controller code

            class ProgParAnimation extends GetxController
          with SingleGetTickerProviderMixin {
            QuestionController controller = Get.put(QuestionController());
          // QuestionController quesCont = Get.put(QuestionController());
           AnimationController _animationController;
           Animation _animation;
          // so that we can access our animation outside
            Animation get animation => this._animation;

          PageController _pageController;
         PageController get pageconroller => _pageController;

        bool _isanswerd = false;
        bool get isanswerd => this._isanswerd;
        int _correctanse;
         int get correctanse => this._correctanse;
       int _selectedAns;
       int get selectedAns => this._selectedAns;
           var _questionNumber = 1.obs;
         RxInt get questionNumber => this._questionNumber;
        int _numOfCorrectAns = 0;
          int get numOfCorrectAns => this._numOfCorrectAns;

       @override
         void onInit() {
         // Our animation duration is 60 s
         // so our plan is to fill the progress bar within 60s
         // with SingleGetTickerProviderMixin for the animation process used with vsync
          _animationController =
              AnimationController(duration: Duration(seconds: 60), vsync: this);
           // update like setState
         _animation = Tween<double>(begin: 0, end: 1).animate(_animationController)
            ..addListener(() => update());
          // start the animation and forwarf to the next page when complete
         _animationController.forward().whenComplete(() {
             nextQuestion();
          });
           // to set the pagecontroller for the page changeing
         _pageController = PageController();

           super.onInit();
         }

           @override
         void onClose() {
          _animationController.dispose();
          _pageController.dispose();
 
           super.onClose();
         }

         void checkAnswer(int selectIndex, Questions question) {
         _isanswerd = true;
           _correctanse = question.answer;
            _selectedAns = selectIndex;
          if (_correctanse == _selectedAns) {
             _numOfCorrectAns++;
           }
          // to stop the animation after the user check the answer
          _animationController.stop();
           update();
         // Once user select an ans after 3s it will go to the next qn
         Future.delayed(
          Duration(seconds: 3),
             () {
             nextQuestion();
             },
            );
         }

          void nextQuestion() {
           if (_questionNumber.value != controller.question.length) {
             _isanswerd = false;
           _pageController == null
               ? print('error')
                : _pageController.nextPage(
                     duration: Duration(seconds: 1), curve: Curves.ease);
                 // Reset the counter
              _animationController.reset();
              // Then start it again
               // Once timer is finish go to the next qn so that the oninit only start once
                _animationController.forward().whenComplete(nextQuestion);
              } else {
               Get.to(ScoreScreen());
               }
           }

               void updateQuestion(int index) {
               _questionNumber.value = index + 1;
         }

         void startAgain() {
           _numOfCorrectAns = 0;
         _questionNumber.value = 1;

           nextQuestion();
          update();
      }
       }
    `

**Comment by alsayedabdelbaqeyahmed** [comment] 2021-02-14 23:50
my page builder code
`                      Expanded(
                        child: PageView.builder(
                         onPageChanged: controller.updateQuestion,
                          physics: NeverScrollableScrollPhysics(),
                          controller: controller.pageconroller,
                         itemBuilder: (ctx, index) => QuestionCard(
                           question: questionController.question[index],
                          ),
                         itemCount: questionController.question.length,
                       ),
                      ),
`

**Comment by alsayedabdelbaqeyahmed** [comment] 2021-02-14 23:50
my page view builder 
`Expanded(
                    child: PageView.builder(
                      onPageChanged: controller.updateQuestion,
                      physics: NeverScrollableScrollPhysics(),
                      controller: controller.pageconroller,
                      itemBuilder: (ctx, index) => QuestionCard(
                        question: questionController.question[index],
                      ),
                      itemCount: questionController.question.length,
                    ),
                  ),`

**Comment by pedromassangocode** [comment] 2021-02-15 07:45
Hi @alsayedabdelbaqeyahmed 
Can you please provide your `flutter doctor -v` along with a minimal reproducible code sample that does not uses any third-party plugin/package?
Thank you

**Comment by alsayedabdelbaqeyahmed** [comment] 2021-02-15 12:04
> Hi @alsayedabdelbaqeyahmed
> Can you please provide your `flutter doctor -v` along with a minimal reproducible code sample that does not uses any third-party plugin/package?
> Thank you

of course i will do now thank you

**Comment by alsayedabdelbaqeyahmed** [comment] 2021-02-15 12:10
my flutter doctor I work on VS code not android studio
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 1.22.6, on Microsoft Windows [Version 10.0.19042.746], locale en-US)
 
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[!] Android Studio (version 4.1.0)
    X Flutter plugin not installed; this adds Flutter specific functionality.   
    X Dart plugin not installed; this adds Dart specific functionality.
[√] VS Code (version 1.53.2)
[√] Connected device (1 available)

! Doctor found issues in 1 category.

**Comment by pedromassangocode** [comment] 2021-02-15 13:45
Hi @alsayedabdelbaqeyahmed 
I need you to provide a minimal reproducible code sample that does not uses any third-party plugin/package as well!

**Comment by alsayedabdelbaqeyahmed** [comment] 2021-02-15 18:03
> Hi @alsayedabdelbaqeyahmed
> I need you to provide a minimal reproducible code sample that does not uses any third-party plugin/package as well!

i don not understand what do you mean i already added my code that i am used and i need to find the solution to my error

**Comment by pedromassangocode** [comment] 2021-02-16 07:30
Hi @alsayedabdelbaqeyahmed 
I mean: I need you to provide a minimal reproducible code sample that does not uses any third-party plugin/package.
Thank you

**Comment by alsayedabdelbaqeyahmed** [comment] 2021-02-16 11:51
> Hi @alsayedabdelbaqeyahmed
> I mean: I need you to provide a minimal reproducible code sample that does not uses any third-party plugin/package.
> Thank you

my app based on third party package and my problem based on it how can i provide the without it and i provide the code where i thought it produce the error ?

**Comment by pedromassangocode** [comment] 2021-02-16 13:59
> my app based on third party package and my problem based on it

If you believe the issue is caused by a third-party package/plugin then please close this issue and open an issue on the repository of that same package/plugin, this repository to track Flutter related issues only.
Thank you

**Comment by alsayedabdelbaqeyahmed** [comment] 2021-02-16 14:23
> > my app based on third party package and my problem based on it
> 
> If you believe the issue is caused by a third-party package/plugin then please close this issue and open an issue on the repository of that same package/plugin, this repository to track Flutter related issues only.
> Thank you

i don not know the case of the issue i thought i can not use it correctly

**Closed** 2021-02-16 14:26 UTC
Labels: r: invalid
