### ISSUE TITLE
Inner shadow for BoxShadow

### ISSUE THREAD

**Issue by AcnoSaga** [flutter/flutter#52999] opened 2020-03-21 09:25 UTC
Can we have an inset property on BoxShadow similar to CSS to have the effect of an inner shadow ?

**Comment by shallx** [comment] 2020-03-30 02:37
Badly need this feature. I hope devs see this issue

**Comment by deepak-penaganti** [comment] 2021-07-15 20:17
> This should be resolved by #84733

New PR #86504 should resolve this

**Comment by AlexanderFarkas** [comment] 2022-01-26 13:44
Any updates on this?

**Comment by victorsanni** [comment] 2024-08-02 22:35
This should be closed as a duplicate of https://github.com/flutter/flutter/issues/18636.

**Closed** 2024-08-02 22:38 UTC
Labels: c: new feature, framework, f: material design, c: proposal, team-design, triaged-design
