### ISSUE TITLE
[go_router] ShellRoute is rendered above the sibling route

### ISSUE THREAD

**Issue by Tkko** [flutter/flutter#117730] opened 2022-12-28 11:59 UTC
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. Tap on "See details"

**Expected results:** 
The Details page should be above the navigation bar

<img width="200" src="https://user-images.githubusercontent.com/26390946/209808017-57f0a063-72e0-490d-ae7f-7ef3d8db7217.png" />

**Actual results:** 
The Details page is under the navigation bar

<img width="200" src="https://user-images.githubusercontent.com/26390946/209808045-b1f80419-a35d-45e0-8bf6-27074a5f59dc.png" />

Setting `parentNavigatorKey` solves the problem but the `/details` route isn't a child of the shell route, and it should work without it (see the code sample)
``` dart
      GoRoute(
        path: '/details',
        builder: (context, state) => const Details(),
        parentNavigatorKey: appNavigatorKey,
      ),
```

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';

class AppRouter {
  static final GlobalKey<NavigatorState> appNavigatorKey = GlobalKey<NavigatorState>();
  static final GlobalKey<NavigatorState> rootShellNavigatorKey = GlobalKey<NavigatorState>();

  static final GoRouter router = GoRouter(
    initialLocation: '/home',
    navigatorKey: appNavigatorKey,
    routes: [
      GoRoute(
        path: '/details',
        builder: (context, state) => const Details(),
      ),
      ShellRoute(
        navigatorKey: rootShellNavigatorKey,
        builder: (context, state, child) {
          return AppScaffoldWithNavBar(child: child);
        },
        routes: [
          GoRoute(
            path: '/',
            pageBuilder: (context, state) => const NoTransitionPage(child: Home()),
          ),
          GoRoute(
            path: '/home',
            pageBuilder: (context, state) => const NoTransitionPage(child: Home()),
          ),
          GoRoute(
            path: '/history',
            pageBuilder: (context, state) => const NoTransitionPage(child: History()),
          ),
          GoRoute(
            path: '/settings',
            pageBuilder: (context, state) => const NoTransitionPage(child: Settings()),
          ),
        ],
      )
    ],
  );
}

void main() {
  runApp(const App());
}

class App extends StatelessWidget {
  const App({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(
      routerConfig: AppRouter.router,
    );
  }
}

class Home extends StatelessWidget {
  const Home({super.key});

  @override
  Widget build(BuildContext context) {
    return InkWell(
      onTap: () => GoRouter.of(context).push('/details'),
      child: const Center(child: Text('See details')),
    );
  }
}

class History extends StatelessWidget {
  const History({super.key});

  @override
  Widget build(BuildContext context) {
    return const Center(child: Text('History'));
  }
}

class Settings extends StatelessWidget {
  const Settings({super.key});

  @override
  Widget build(BuildContext context) {
    return const Center(child: Text('Settings'));
  }
}

class Details extends StatelessWidget {
  const Details({super.key});

  @override
  Widget build(BuildContext context) {
    return const Scaffold(body: Center(child: Text('Details')));
  }
}

class AppScaffoldWithNavBar extends StatefulWidget {
  const AppScaffoldWithNavBar({super.key, required this.child});

  final Widget child;

  @override
  State<AppScaffoldWithNavBar> createState() => _AppScaffoldWithNavBarState();
}

class _AppScaffoldWithNavBarState extends State<AppScaffoldWithNavBar> {
  @override
  Widget build(BuildContext context) {
    return Stack(
      alignment: AlignmentDirectional.bottomCenter,
      children: [
        Scaffold(
          body: widget.child,
          extendBody: true,
          extendBodyBehindAppBar: true,
        ),
        const NavBar(),
      ],
    );
  }
}

class NavBar extends StatelessWidget {
  const NavBar({super.key});

  @override
  Widget build(BuildContext context) {
    return Positioned(
      bottom: 20,
      child: Container(
        height: 60,
        decoration: BoxDecoration(
          color: Colors.greenAccent,
          borderRadius: BorderRadius.circular(100),
        ),
        padding: const EdgeInsets.symmetric(horizontal: 12),
        child: Material(
          color: Colors.transparent,
          child: Row(
            mainAxisSize: MainAxisSize.min,
            children: ['home', 'history', 'profile'].map((item) {
              return IconButton(
                onPressed: () {},
                icon: const Icon(Icons.add),
              );
            }).toList(),
          ),
        ),
      ),
    );
  }
}

```

</details>

**flutter --version**

Flutter 3.3.10 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 135454af32 (4 weeks ago) • 2022-12-15 07:36:55 -0800
Engine • revision 3316dd8728
Tools • Dart 2.18.6 • DevTools 2.15.0

**GoRouter**

go_router: ^6.0.1

**Comment by darshankawar** [comment] 2022-12-28 12:57
Thanks for the report. Seeing same behavior on latest versions.

<details>
<summary> stable, master flutter doctor -v </summary>

```
[✓] Flutter (Channel stable, 3.3.10, on macOS 12.2.1 21D62 darwin-x64, locale
    en-GB)
    • Flutter version 3.3.10 on channel stable at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (15 hours ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

[!] Flutter (Channel master, 3.7.0-13.0.pre.51, on macOS 12.2.1 21D62
    darwin-x64, locale en-GB)
    • Flutter version 3.7.0-13.0.pre.51 on channel master at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6441a7dc62 (3 hours ago), 2022-12-22 20:38:18 -0500
    • Engine revision 12badb5459
    • Dart version 3.0.0 (build 3.0.0-60.0.dev)
    • DevTools version 2.20.0
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.



```

</details>

**Comment by hangyujin** [comment] 2023-01-09 19:31
I can not reproduce it
@Tkko can you provide a complete code example with all customized widgets like `AppScaffoldWithNavBar`

**Comment by carlosfiori** [comment] 2023-02-02 20:49
Facing same problem here, when I use `push` the route is rendered inside the ShellRoute builder, when used the `go` method, the route is rendered correct but then the `pop` method doesn't return to previous page, it closes the app

**Comment by carlosfiori** [comment] 2023-02-02 20:51
Seems related https://github.com/flutter/flutter/issues/111842

**Comment by chunhtai** [comment] 2023-08-08 21:40
This should be fixed by https://docs.google.com/document/d/1HCgLi7ialw2Eqv-f_2z9ogdOfcmepIIqCsRhF-DT9dM/edit

**Comment by chunhtai** [comment] 2023-12-07 18:50
duplicate of https://github.com/flutter/flutter/issues/120665

**Closed by chunhtai** 2023-12-07 18:50 UTC
Labels: package, has reproducible steps, P2, p: go_router, found in release: 3.3, found in release: 3.7, team-go_router, triaged-go_router, multiteam-retriage-candidate
