### ISSUE TITLE
Image picker web methods never return a result

### ISSUE THREAD

**Issue by kasyrm** [flutter/flutter#94248] opened 2021-11-26 13:23 UTC
I noticed that sometimes the image picker gets stack on Chrome desktop on the deployed website.
It works correctly when same code is run locally.  It also works both locally and when deployed on Safari and Firefox. 

When it happens both
`final imageList = await ImagePicker().pickMultiImage();`
and
`final videoList =
        await ImagePicker().pickVideo(source: ImageSource.gallery);`
never return. No error is logged. 
Restarting computer fixed the issue for me. 

Image picker version: image_picker: 0.8.4+2

Flutter doctor: 
[✓] Flutter (Channel stable, 2.5.2, on macOS 11.5.1 20G80 darwin-arm, locale pl-PL)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.59.1)
[✓] Connected device (2 available)

• No issues found!

**Comment by iapicca** [comment] 2021-11-26 21:04
dupe of https://github.com/flutter/flutter/issues/92176

**Comment by maheshmnj** [comment] 2021-11-29 10:07
Hi @kasyrm, Thanks for filing the issue, I ran this [official sample code](https://pub.dev/packages/image_picker/example) on the web in chrome and it works 100% of the time. Please share the complete output of `flutter doctor -v` and a minimal and complete reproducible code.

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.5.3, on macOS 12.0.1 21A559 darwin-arm, locale en-GB)
    • Flutter version 2.5.3 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (6 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.1, Build version 13A1030d
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.61.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.28.0

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • B622CBB7-F906-4FA7-8F49-FACEAAC905AB • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.0.1 21A559
      darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome
      96.0.4664.55

• No issues found!
```
</details>
 

Thanks

**Closed** 2021-12-20 10:10 UTC
Labels: waiting for customer response, in triage
