### ISSUE TITLE
Characters disappear when adding characters to a TextField while typing with IME.

### ISSUE THREAD

**Issue by MisakoGunjima** [flutter/flutter#72980] opened 2020-12-26 17:26 UTC
I want to input text input with both IME and button on Flutter and Android. I want to input text using both IME and buttons in Flutter and Android. but it is not correct with the following behavior.

1. press a button while typing a character from IME
2. enter additional characters from IME
3. The text entered by the button disappears.

<details><summary>Here's my code</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MaterialApp(home: HomePage()));
}

class HomePage extends StatefulWidget {
  @override
  _HomePageState createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  TextEditingController _messageInputController;

  @override
  void initState() {
    _messageInputController = TextEditingController();
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Demo"),
      ),
      body: SafeArea(
        child: Column(
          children: <Widget>[
            RaisedButton(
                child: Text("add text"),
                onPressed: () {
                  String oldText = _messageInputController.text;
                  String newText = oldText + "insertText";

                  var newValue = _messageInputController.value.copyWith(
                    text: newText,
                    selection: TextSelection.collapsed(
                      offset: newText.length,
                    ),
                    composing: TextRange.empty,
                  );

                  _messageInputController.value = newValue;
                }),
            TextField(
              controller: _messageInputController,
            ),
          ],
        ),
      ),
    );
  }
}
```
</details>

```
[√] Flutter (Channel stable, 1.22.5, on Microsoft Windows [Version 10.0.18363.1256], locale ja-JP)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Android Studio (version 4.1.0)
    • Android Studio at C:\tools\studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

```

</details>

**Comment by pedromassangocode** [comment] 2020-12-28 08:10
Hi @MisakoGunjima
Can you please elaborate the steps to reproduce the issue? I'm not sure if I understood what this issue is about.
Please provide your `flutter doctor -v` as well.

Thank you

**Comment by MisakoGunjima** [comment] 2020-12-28 13:25
flutter doctor -v

```
[√] Flutter (Channel stable, 1.22.5, on Microsoft Windows [Version 10.0.19041.685], locale ja-JP)
    • Flutter version 1.22.5 at D:\flutter_windows_1.17.2-stable\flutter
    • Framework revision 7891006299 (3 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\alice\AppData\Local\Android\sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.
[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
```


I took a video of the steps.
https://user-images.githubusercontent.com/6672138/103217133-34b41200-495b-11eb-9728-cd12dd64f887.mp4

In the video, the text is entered from the keyboard and then the addText button is pressed.
At this point, you can add text from the button by pressing Enter on the IME, but
If you do not press Enter, you will not be able to add text.

**Comment by justinmc** [comment] 2020-12-28 18:14
@MisakoGunjima Can you try reproducing this on the latest master?  I'm unable to reproduce there.

<img width="200" src="https://user-images.githubusercontent.com/389558/103234762-511d6380-48f5-11eb-8cda-ed038eb61e99.gif" />

**Comment by MisakoGunjima** [comment] 2020-12-29 03:20
Thanks!
I have been able to confirm that the problem does not occur in the latest beta channel.

**Comment by MisakoGunjima** [comment] 2020-12-29 08:25
It continues to occur in third party IME applications.
I tried the IME application "Simeji".　[GooglePlay](https://play.google.com/store/apps/details?id=com.adamrocker.android.input.simeji&hl=en&gl=US)

**Comment by pedromassangocode** [comment] 2020-12-29 10:57
Thanks to @darshankawar  who helped me to try to reproduce the issue with the "Simeji" keyboard app. And still cannot reproduce the issue on latest stable channel.

https://user-images.githubusercontent.com/67424416/103278656-4f729f00-49cc-11eb-8ac1-7964d00625b6.mp4


https://user-images.githubusercontent.com/67424416/103278901-dde72080-49cc-11eb-91f1-1fe3c09d081d.mp4

**Comment by MisakoGunjima** [comment] 2020-12-29 11:13
I'll upload a video of me trying it with "simeji".
https://user-images.githubusercontent.com/6672138/103279734-d302af00-4a11-11eb-9fbd-ac46e7b6040c.mp4

 I use Pixel5 / Android 11 (API 30)
Language settings Japanese

**Comment by pedromassangocode** [comment] 2020-12-30 07:40
This maybe device specific? @MisakoGunjima Are you able to reproduce the issue on a different device/emulator?

Leaving it opened for further investigation.

**Comment by MisakoGunjima** [comment] 2020-12-30 09:22
I tried the phenomenon on several devices I have.

Huawei LLD-AL10(Android8.0.0)、SHARP SH-03K(Android10.0)、Pixel4（Android11）、Pixel5（Android11）
I was able to reproduce this on the device I described above.

Simeji" cannot be installed on the emulator, so I checked it only on the device.

**Comment by justinmc** [comment] 2021-02-18 17:57
I was also able to reproduce this with the Simeji keyboard.  When I tried with other composing keyboards (Chinese and Japanese Gboard), I couldn't reproduce it.

This reminds me of a problem we have had with Samsung's keyboards (https://github.com/flutter/flutter/issues/31512).  I noticed that the Simeji keyboard does something similar to that as well:

  1. Type some composing text.
  2. Tap once to move the cursor to the beginning of the field.
  3. Type another character.
  4. The character will be inserted at the end of the text, not at the start where the cursor is.

It seems like somewhere in the engine, the IME needs to be told to stop composing.

**Comment by LongCatIsLooong** [comment] 2021-03-21 02:41
@MisakoGunjima IMEs generally don't expect someone to commit the composing text on behalf of themselves (in your case, changing it to empty: `composing: TextRange.empty,`) since there isn't a good way for them to get notified of such events. To avoid surprising the IME, try this instead: `composing: _messageInputController.value.composing,`

**Closed** 2021-03-29 23:29 UTC
Labels: a: text input, d: api docs, e: device-specific, f: material design, framework, passed first triage, platform-android
