### ISSUE TITLE
home_scroll_perf__timeline_summary 99th_percentile_frame_rasterizer_time_millis regression

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#30405] opened 2019-04-02 21:17 UTC
Around 2019-03-12, the worst case performance for `home_scroll_perf__timeline_summary 99th_percentile_frame_rasterizer_time_millis` regressed.

The 90th percentile rasterizer performance did not noticeably regress, nor did the worst frame rasterizer performance, which suggests that there's one particular frame in the benchmark which got worse, and that it's not an infrastructure problem.

cc @jason-simmons @liyuqian

**Comment by liyuqian** [comment] 2019-04-26 21:33
I pinpointed the regression on https://github.com/flutter/flutter/commit/c78ccb0 which happened on 03/12 :

![i30405](https://user-images.githubusercontent.com/22987568/56837689-23cf0700-6830-11e9-8eda-62d56013315b.png)

@Hixie @stereotype441

**Comment by liyuqian** [comment] 2019-04-26 21:35
It doesn't make much sense to me that https://github.com/flutter/flutter/commit/c78ccb0 could regress the performance. Maybe it's another instance of https://github.com/flutter/flutter/issues/27574

**Comment by liyuqian** [comment] 2019-04-26 21:38
There are two engine rolls https://github.com/flutter/flutter/commit/c2f4386c548b4f6a5a632d05ed80e4d28b243fa9 and https://github.com/flutter/flutter/commit/ddee4f716cf8fc07ee179671d25c66883a0876ea around https://github.com/flutter/flutter/commit/c78ccb0

Does anyone know how to verify which version of the engine that https://github.com/flutter/flutter/commit/c78ccb0 is using? @jonahwilliams @jason-simmons @dnfield

**Comment by jonahwilliams** [comment] 2019-04-26 21:40
https://github.com/flutter/flutter/blob/c78ccb0b5ef93a9799b0b37ef3a89802d27e7bb6/bin/internal/engine.version

**Comment by jonahwilliams** [comment] 2019-04-26 21:40
It is on 0d2cf5857b2be0949435f60c0188f1aed4d93c93

**Comment by liyuqian** [comment] 2019-04-26 22:05
Because of https://github.com/flutter/flutter/issues/27574, https://github.com/flutter/flutter/blob/c78ccb0b5ef93a9799b0b37ef3a89802d27e7bb6/bin/internal/engine.version is not a reliable source of the engine version.

**Comment by liyuqian** [comment] 2019-04-26 22:19
Never mind @jonahwilliams , @dnfield , @jason-simmons : https://github.com/flutter/flutter/commit/c78ccb0 doesn't change the engine.version so no matter how the engine artifact messed up, it should use the same engine as https://github.com/flutter/flutter/commit/e100514

Hence the engine and https://github.com/flutter/flutter/issues/27574 seem to be innocent here.

So https://github.com/flutter/flutter/commit/c78ccb0 is back to our major suspect now. I'll rerun my tests to verify that.

**Comment by liyuqian** [comment] 2019-04-26 23:43
I think that I may have found a bug in my bisection script. I'm rerunning it. https://github.com/flutter/flutter/commit/c78ccb0 is no longer our suspect due to the bug.

**Comment by liyuqian** [comment] 2019-04-27 21:38
After fixing the bug, I now pinpointed the regression on engine roll https://github.com/flutter/flutter/commit/a29906d .
![i30405](https://user-images.githubusercontent.com/22987568/56855311-f2bb0900-68f9-11e9-9d57-92b59db6e9ab.png)

The root cause is likely @dnfield 's [AA changes for shape layers](https://github.com/flutter/engine/commit/fdad56f5f).

I think the regression is in some sense expected, so we could just rebase the benchmark and close this bug. @dnfield : please confirm if that makes sense. If so, please rebase and close accordingly.

**Comment by dnfield** [comment] 2019-04-27 22:57
Makes sense to me

**Closed** 2019-04-27 23:18 UTC
Labels: engine, severe: performance, severe: regression
