### ISSUE TITLE
Wrongs icons in dev channel (Mobile/Desktop)

### ISSUE THREAD

**Issue by Bestfastfire** [flutter/flutter#84403] opened 2021-06-11 01:54 UTC
After change channel of beta to dev, practically all icons have changed, ex:

![Screenshot_183](https://user-images.githubusercontent.com/22732544/121619215-9e723500-ca3e-11eb-9cca-4ad179918b8c.png)

Including the default combobox icon:
![Screenshot_184](https://user-images.githubusercontent.com/22732544/121619261-b5b12280-ca3e-11eb-95a3-dc035bffddb5.png)

I've already tried:

`flutter pub cache repair`
`flutter pub cache clean`
`flutter clean`

The problem persists both running on released and debug.

```
[√] Flutter (Channel dev, 2.3.0-16.0.pre, on Microsoft Windows [versÃ£o 10.0.19042.985], locale pt-BR)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.8.3)
[√] Android Studio (version 4.2.0)
[√] VS Code (version 1.56.2)
[√] Connected device (3 available)

! Doctor found issues in 1 category.
```

Edit 1: I went to the stable channel, ran the commands to clear the cache again and the problem persists, strange, I'll go back to beta and see what happens, could the problem be something with Android Studio?

**Comment by Bestfastfire** [comment] 2021-06-11 02:38
Going back to the Beta channel didn't work, so I downloaded the stable version directly from the flutter site and did a clean install and voilà, it worked, which is weird, the version is the exact same as I tested it before, there's a problem with the exchange of channels.

It's not the first time this has happened to me but the other time it stopped out of nowhere.

**Comment by TahaTesser** [comment] 2021-06-11 09:49
Hi @Bestfastfire 
No issue in my testing 

<details> 
<summary>minimal code sample</summary> 

```dart
import 'package:flutter/material.dart';
 
void main() => runApp(MyApp());
 
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      home: Scaffold(
        appBar: AppBar(
          title: Text('Material App Bar'),
        ),
        body: Center(
          child: Icon(Icons.delete),
        ),
      ),
    );
  }
}
``` 

</details>

However, this is a duplicate of https://github.com/flutter/flutter/issues/76442 
See https://github.com/flutter/flutter/issues/80646
Please follow up on that issue, Closing as duplicate 
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-06-11 09:49 UTC
Labels: in triage
