### ISSUE TITLE
[tool_crash] StateError: Bad state: Future already completed

### ISSUE THREAD

**Issue by xuhang1993** [flutter/flutter#98892] opened 2022-02-22 03:09 UTC
## Command
```
flutter --no-color attach --machine --device-id=7b3e6a78 lib\main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
StateError: Bad state: Future already completed
```
#0      _AsyncCompleter.complete (dart:async/future_impl.dart:45:31)
#1      FlutterDevice.connect.<anonymous closure> (package:flutter_tools/src/resident_runner.dart:321:17)
<asynchronous suspension>
```
```
[✓] Flutter (Channel unknown, 2.5.2, on Microsoft Windows [Version 10.0.19042.1526], locale zh-CN)
    • Flutter version 2.5.2 at D:\Android\FlutterSDK\flutter
    • Upstream repository unknown
    • Framework revision 3595343e20 (5 months ago), 2021-09-30 12:58:18 -0700
    • Engine revision 6ac856380f
    • Dart version 2.14.3
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at D:\Android\SDK\
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 4.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.2)
    • IntelliJ at D:\JetBrains\IntelliJ IDEA 2018.2.2
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (4 available)
    • V1914A (mobile)  • 7b3e6a78             • android-arm64  • Android 10 (API 29)
    • Hi 1050 (mobile) • 192.169.222.128:5555 • android-arm    • Android 8.1.0 (API 27)
    • Chrome (web)     • chrome               • web-javascript • Google Chrome 92.0.4515.131
    • Edge (web)       • edge                 • web-javascript • Microsoft Edge 97.0.1072.62

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: module
**Version**: 1.0.0+1
**Material**: true
**Android X**: true
**Module**: true
**Plugin**: false
**Android package**: net.hexfuture.hex_flutter_family
**iOS bundle identifier**: net.hexfuture.hexFlutterFamily
**Creation channel**: stable
**Creation framework version**: f139b11009aeb8ed2a3a3aa8b0066e482709dde3
### Plugins
connectivity-3.0.6
connectivity_for_web-0.4.0+1
connectivity_macos-0.2.1+2
fijkplayer-0.10.0
flutter_boost-689596c077dd8ba21cf0317385487d6d553ae807
flutter_screen_orientation-0.0.1+1
orientation-1.3.0
wakelock-0.5.6
wakelock_macos-0.4.0
wakelock_web-0.4.0

**Comment by danagbemava-nc** [comment] 2022-02-22 07:21
Duplicate of #77581

**Closed by danagbemava-nc** 2022-02-22 07:21 UTC
Labels: in triage
