### ISSUE TITLE
Flutter "notification tray" (?) support

### ISSUE THREAD

**Issue by jdeltoft** [flutter/flutter#72715] opened 2020-12-21 13:57 UTC
Sorry, I've looked all over and am very surprised that it wasn't either obvious or maybe even supported?   I am writing an app that I want to have music like controls in the "notification tray".  That's maybe my first problem though?  I'm not even sure what the proper name is.  System tray, notification shade, alert pull down, etc.  Is that supported today in Flutter?  If not, can you add it?

**Comment by TahaTesser** [comment] 2020-12-21 14:57
Hi @jdeltoft 
Audio isn't fully built-in https://github.com/flutter/flutter/issues/47105
However, you can use https://pub.dev/packages/audio_service and ti has notification tray control support as well, just tried it and can confirm
Closing, as duplicate of https://github.com/flutter/flutter/issues/47105. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2020-12-21 14:57 UTC

**Comment by jdeltoft** [comment] 2020-12-21 21:42
@TahaTesser  Thanks for the fast reply!  I actually didn't ask my question well I think.  I'm not looking for a audio player.  I'm looking for a way to add widgets to a notificaition tray "scaffold".  So when my app is open, I can have the user either open the app, or just use the tray scaffold to use some subset of controls to my app.

**Comment by TahaTesser** [comment] 2020-12-22 09:18
@jdeltoft 
I understand but notifications are not of Flutter, they are created natively so you would need to reply on the package for those services, one example of such is https://pub.dev/packages/flutter_local_notifications#-screenshots.
You can probably make a proposal to control functionality for this package 
Thanks
