### ISSUE TITLE
Error (Xcode): Cycle inside Runner; building could produce unreliable results.

### ISSUE THREAD

**Issue by tkeithblack** [flutter/flutter#134256] opened 2023-09-07 23:04 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I have been using Flutter for about three years and have two production apps in the App Stores. After upgrading to Flutter 3.13.2 • channel stable I can no longer run or build my app from the VS Code studio (Run menu or command line: 'flutter build ios'). 

When I attempt to run or build it I get the error 
```
Failed to build iOS app
Error (Xcode): Cycle inside Runner; building could produce unreliable results.
```
(See full log below)

If I Debug Run directly from xCode it works fine. It's only when I attempt to Debug Run or build from VSCode.

I have tried many things to get around this issue including re-arranging the Build Phase steps in xCode as well as deleting and rebuild all derived data and Pod files multiple times with the following commands:

```
rm -r /Users/keithblack/Library/Developer/Xcode/DerivedData
rm -r -f /Users/keithblack/.pub-cache
rm -rf ~/GitHub/flutter/bin/cache/artifacts/engine/ios*

rm pubspec.lock

flutter pub cache repair
flutter clean
flutter pub get

cd ios
rm Podfile.lock
pod deintegrate
flutter precache --ios
pod install --repo-update
```

This issue seems to be related to an embedded App Extension I have in my xCode project, however, this has not changed for years. 

In order to verify that I have not inadvertently broken something I rolled back to a production branch of my app from several weeks ago but get the same error.

Thanks for any assistance.

### Expected results

Expect app to run.

### Actual results

Results are error is thrown (see log below).

### Code sample

<details><summary>Code sample</summary>

```dart
flutter build ios
```

</details>

### Screenshots or Video

The following shows my build phases:

![Build Phases](https://github.com/flutter/flutter/assets/16345467/3a75e8ee-368d-4eba-a4fa-e47ef74c2e22)

### Logs

<details><summary>Logs</summary>

```console
Launching lib/main.dart on iPhone 14 Pro in debug mode...
Xcode build done.                                           25.0s
Failed to build iOS app
Error (Xcode): Cycle inside Runner; building could produce unreliable results.
Cycle details:
→ Target 'Runner': CodeSign /Users/tkb/GitHub/MyApp/build/ios/Debug-iphonesimulator/Runner.app
○ That command depends on command in Target 'Runner': script phase “[CP] Embed Pods Frameworks”
○ That command depends on command in Target 'Runner': script phase “Thin Binary”
○ Target 'Runner' has process command with output '/Users/tkb/GitHub/MyApp/build/ios/Debug-iphonesimulator/Runner.app/Info.plist'
○ Target 'Runner' has copy command from '/Users/tkb/GitHub/MyApp/build/ios/Debug-iphonesimulator/MyAppServiceExtension.appex' to '/Users/tkb/GitHub/MyApp/build/ios/Debug-iphonesimulator/Runner.app/PlugIns/MyAppServiceExtension.appex'

Raw dependency cycle trace:

target:  ->

node: <all> ->

command: <all> ->

node: /Users/tkb/GitHub/MyApp/build/ios/Debug-iphonesimulator/Runner.app/_CodeSignature ->

command: P0:target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49-:Debug:CodeSign /Users/tkb/GitHub/MyApp/build/ios/Debug-iphonesimulator/Runner.app ->

node: /Users/tkb/GitHub/MyApp/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/DTFoundation.framework/ ->

directoryTreeSignature: v ->

directoryContents: /Users/tkb/GitHub/MyApp/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/DTFoundation.framework ->

CYCLE POINT ->

node: /Users/tkb/GitHub/MyApp/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/DTFoundation.framework ->

command: P2:target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49-:Debug:PhaseScriptExecution [CP] Embed Pods Frameworks /Users/tkb/Library/Developer/Xcode/DerivedData/Runner-hkqxcjzoywvdafdnofetqkxhxdkc/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Script-B4C75CA96A5685DF012BAD87.sh ->

node: /Users/tkb/Library/Developer/Xcode/DerivedData/Runner-hkqxcjzoywvdafdnofetqkxhxdkc/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Script-B4C75CA96A5685DF012BAD87.sh ->

command: P2:target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49-:Debug:WriteAuxiliaryFile /Users/tkb/Library/Developer/Xcode/DerivedData/Runner-hkqxcjzoywvdafdnofetqkxhxdkc/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Script-B4C75CA96A5685DF012BAD87.sh ->

node: <target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49--fused-phase4-thin-binary> ->

command: P0:::Gate target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49--fused-phase4-thin-binary ->

node: <execute-shell-script-18c1723432283e0cc55f10a6dcfd9e02f1eee2015e8ff5ebcd27678f788c2826-target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49-> ->

command: P2:target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49-:Debug:PhaseScriptExecution Thin Binary /Users/tkb/Library/Developer/Xcode/DerivedData/Runner-hkqxcjzoywvdafdnofetqkxhxdkc/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Script-3B06AD1E1E4923F5004D2608.sh ->

node: /Users/tkb/GitHub/MyApp/build/ios/Debug-iphonesimulator/Runner.app/Info.plist/ ->

directoryTreeSignature: _ ->

directoryContents: /Users/tkb/GitHub/MyApp/build/ios/Debug-iphonesimulator/Runner.app/Info.plist ->

node: /Users/tkb/GitHub/MyApp/build/ios/Debug-iphonesimulator/Runner.app/Info.plist ->

command: P0:target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49-:Debug:ProcessInfoPlistFile /Users/tkb/GitHub/MyApp/build/ios/Debug-iphonesimulator/Runner.app/Info.plist /Users/tkb/GitHub/MyApp/ios/Runner/Info.plist ->

node: /Users/tkb/GitHub/MyApp/build/ios/Debug-iphonesimulator/Runner.app/PlugIns/MyAppServiceExtension.appex ->

command: P0:target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49-:Debug:Copy /Users/tkb/GitHub/MyApp/build/ios/Debug-iphonesimulator/Runner.app/PlugIns/MyAppServiceExtension.appex /Users/tkb/GitHub/MyApp/build/ios/Debug-iphonesimulator/MyAppServiceExtension.appex ->

node: <target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49--fused-phase5--cp--embed-pods-frameworks> ->

command: P0:::Gate target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49--fused-phase5--cp--embed-pods-frameworks ->

node: /Users/tkb/GitHub/MyApp/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/DTFoundation.framework

Could not build the application for the simulator.
Error launching application on iPhone 14 Pro.


Exited (1).

```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.13.2, on macOS 13.5 22G74 darwin-x64, locale en-US)
    • Flutter version 3.13.2 on channel stable at /Users/keithblack/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ff5b5b5fa6 (2 weeks ago), 2023-08-24 08:12:28 -0500
    • Engine revision b20183e040
    • Dart version 3.1.0
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/keithblack/Library/Android/sdk
    • Platform android-33, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode-beta.app/Contents/Developer
    • Build 15A5229m
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.81.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.72.0

[✓] Connected device (4 available)
    • Keith’s iPhone 12 (mobile) • 00008101-0015445A3CD0001E            • ios            • iOS 17.0 21A5326a
    • iPhone 14 Pro (mobile)     • F4C613F1-8EFE-4A6F-815F-1FB67BE1F1D5 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-0 (simulator)
    • macOS (desktop)            • macos                                • darwin-x64     • macOS 13.5 22G74 darwin-x64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 116.0.5845.179

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

</details>

**Comment by huycozy** [comment] 2023-09-08 10:56
Hi @tkeithblack 
You are using XCode 15 beta, right? Which beta version are you on? 

This looks similar to a known issue (XCode issue) and can be solved by a given solution at https://github.com/flutter/flutter/issues/131586#issuecomment-1658281147. If you have tried this solution but it didn't work for you, can you try replicating the issue on a new Flutter project?

**Comment by tkeithblack** [comment] 2023-09-08 17:30
I am using xCode 15 beta 8. No problem building with this beta until upgrading to Flutter 3.13.2.

I will look at the solution above and if that does not work attempt to recreate in a new project.

Thanks for your reply,
KeithB

**Comment by tkeithblack** [comment] 2023-09-08 18:12
@huycozy,

The solution you pointed me to on the [Apple Forum](https://developer.apple.com/forums/thread/731287?answerId=756374022#756374022) worked. Thank you. 

What I did to fix the problem was go to Build Phase and move **Embed App Extensions** up to just below **Copy Bundle Resources**.

Also, I stated earlier that this worked when compiling from xCode, however, I was inadvertantly compiling from xCode 14 and not from xCode 15 beta 8. As soon as I tried in beta 8 it failed the same as from VSCode. Also, when I was rearranging the Build Phase order earlier I was doing it in xCode 14, not in xCode 15 beta.

The remaining mystery is why this was not happening with Flutter 3.7, but all is working now, thanks for your assistance!

**Comment by huycozy** [comment] 2023-09-11 04:00
Thanks for your response. Regarding the issue not happening with Flutter 3.7, perhaps we have to look specifically at many changes. Since the issue has been resolved with the above solution, I will close this issue. If it continues to happen on the next XCode stable release, please open a new issue for that. Thank you!

**Closed by huycozy** 2023-09-11 04:00 UTC
Labels: in triage

**Comment by esaOnesmile** [comment] 2023-09-21 09:21
> @huycozy,
> 
> The solution you pointed me to on the [Apple Forum](https://developer.apple.com/forums/thread/731287?answerId=756374022#756374022) worked. Thank you.
> 
> What I did to fix the problem was go to Build Phase and move **Embed App Extensions** up to just below **Copy Bundle Resources**.
> 
> Also, I stated earlier that this worked when compiling from xCode, however, I was inadvertantly compiling from xCode 14 and not from xCode 15 beta 8. As soon as I tried in beta 8 it failed the same as from VSCode. Also, when I was rearranging the Build Phase order earlier I was doing it in xCode 14, not in xCode 15 beta.
> 
> The remaining mystery is why this was not happening with Flutter 3.7, but all is working now, thanks for your assistance!

can you screen shot your code?

**Comment by huycozy** [comment] 2023-09-22 05:34
@esaOnesmile Unfortunately, I created a new project for reproducing this and deleted it already. If you still have this issue but the solution above doesn't work, please file a new issue so that we have more information to verify it.
