### ISSUE TITLE
Flutter The method 'openDrawer' was called on null. Navigator.pop(context) or on back widget

### ISSUE THREAD

**Issue by brianschardt** [flutter/flutter#66317] opened 2020-09-22 03:23 UTC
When I try to open the drawer in my flutter app I call key.currentState.openDrawer(); However, when i do a navigator.pop(context) or hit the back button and then call key.currentState.openDrawer(); I get the error The method 'openDrawer' was called on null.

Please help

Here is a link to a repo I made to demonstrate this bug. super easy to run and get started: https://github.com/brianschardt/flutter_drawer_bug

Base Widget I include in all my screens
```
class Base extends StatelessWidget {
  Base({this.child});
  final Widget child;

  final NavDrawerService navDrawerService = getIt<NavDrawerService>();
  @override
  Widget build(BuildContext context) {
    navDrawerService.key = new GlobalKey();//create a new key for every new page, save it in singleton service to open drawer from anywhere in the app.
    return Scaffold(
      body: child,
      key: navDrawerService.key,
      drawer: NavDrawer(),
    );
  }
}
```

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.20.2, on Mac OS X 10.15.6 19G2021, locale en-US)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.49.0)
[✓] Connected device (1 available)

• No issues found!
```

</details>

**Comment by darshankawar** [comment] 2020-09-22 07:59
Hi @brianschardt,
I cloned your repo but unable to see the error. What are the exact steps to replicate the issue ?
Thanks.

**Comment by brianschardt** [comment] 2020-09-22 14:50
@darshankawar 
if you run the app, click open drawer it opens(works as expected) 

Now click screen1, then click the back arrow, then click the open drawer

Now you get this error
```
The method 'openDrawer' was called on null.
Receiver: null
Tried calling: openDrawer()
```

This has to do with `Navigator.pop(context)` breaks something

**Comment by darshankawar** [comment] 2020-09-23 06:00
Hi @brianschardt,
I see that you've used `getIt`, a 3rd party plugin in your implementation. If I remove that part and directly use the core code to open drawer like below:

`onPressed: () => Scaffold.of(context).openDrawer()`

instead of 

`onPressed: () => drawerService.openDrawer(),`,  then I am able to open the drawer properly after coming back from screen 1 and don't see the exception.

That seem to indicate, it could be related to the plugin's implementation and not a bug with Flutter itself. you may try above change and see if you get the same error.
Thanks.

**Comment by TahaTesser** [comment] 2020-10-14 12:24
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

**Closed by TahaTesser** 2020-10-14 12:24 UTC
Labels: in triage
