### ISSUE TITLE
The event of dialog passes through to the PlatformView at the bottom on Flutter Web 

### ISSUE THREAD

**Issue by wangying3426** [flutter/flutter#102815] opened 2022-04-29 07:35 UTC
We encountered a problem with Flutter for Web. 
If a Dialog pops up on a PlatformView, when we click on the Dialog, the event continues through to the PlatformView below.

As shown in the figure, clicking on the Dialog will trigger the video to play or stop.
Because the code is for internal use only, so can not be uploaded, but any demo with PlatformView and Dialog can reproduce it.

<img width="1701" alt="Screen Shot 2022-04-28 at 6 12 28 PM" src="https://user-images.githubusercontent.com/4476512/165902198-0844def5-7c20-41e7-bec2-22b4e6a9e517.png">

This problem directly affects our business experience, hope it can be fixed as soon as possible, thanks.

**Comment by maheshmnj** [comment] 2022-04-29 11:42
Hi @wangying3426, Thanks for filing the issue. This is a known issue and is being tracked here https://github.com/flutter/flutter/issues/93887 

a similar issue was previously filed here https://github.com/flutter/flutter/issues/80655

Closing as duplicate of the above-linked issue. Incase you disagree feel free to write in the comments and we will reopen it .

Thank you.

**Closed by maheshmnj** 2022-04-29 11:43 UTC
Labels: in triage
