### ISSUE TITLE
Scrolling with physical mouse is super slow on Android 

### ISSUE THREAD

**Issue by selvam920** [flutter/flutter#82973] opened 2021-05-20 02:24 UTC
When i'm using keyboard and mouse in flutter android app, i found below issue.

1. Keyboard Backspace is not working when Num Lock is ON
2. move scroll by mouse it's smooth
i'm using Logitec Keyboard and mouse fo this test.

Same scenario is working fine in windows desktop

 Flutter (Channel stable, 2.2.0, on Microsoft Windows [Version 10.0.19043.928], locale en-US)
    • Flutter version 2.2.0 at D:\SW\flutter_windows_2.2.0-stable\flutter
    • Framework revision b22742018b (5 days ago), 2021-05-14 19:12:57 -0700
    • Engine revision a9d88a4d18
    • Dart version 2.13.0

**Comment by TahaTesser** [comment] 2021-05-20 15:18
Hi @selvam920 
Thanks for filing the issue.

### I can reproduce the  keyboard issue 

### Preview
| `stab;e` & `beta` | `dev` & `master` |
| --------------- | --------------- |
<img src="https://user-images.githubusercontent.com/48603081/119003322-4c397900-b996-11eb-840d-95b50194b307.gif" height="450" /> | <img src="https://user-images.githubusercontent.com/48603081/119004545-55771580-b997-11eb-8424-15cfa62ad7aa.gif" height="450" /> |




Reproduced the issue using the following minimal code sample 

<details> 
<summary>minimal code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: TextField(),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {},
      ),
    );
  }
}

``` 

</details>

This seems to be too fixed on the `dev` and `master`

Reproduced on the following channels
|  `stable`  |  `beta`  | `dev` | `master` |
| :---: | :---: | :---: |:---: |
|  ✅  |   ✅  |  ❌  |  ❌  |

Check `flutter doctor -v` outputs for each channel below

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.2.0, on Microsoft Windows [Version 10.0.19042.985], locale en-US)
    • Flutter version 2.2.0 at C:\Users\Taha\Code\flutter_stable
    • Framework revision b22742018b (6 days ago), 2021-05-14 19:12:57 -0700
    • Engine revision a9d88a4d18
    • Dart version 2.13.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\Taha\Code\SDK
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java.exe
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.6)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.9.31313.79
    • Windows 10 SDK version 10.0.19041.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[✓] IntelliJ IDEA Community Edition (version 2021.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.1.1
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.56.2)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.22.0

[✓] Connected device (4 available)
    • Redmi K20 Pro (mobile) • def0ad20 • android-arm64  • Android 10 (API 29)
    • Windows (desktop)      • windows  • windows-x64    • Microsoft Windows [Version 10.0.19042.985]
    • Chrome (web)           • chrome   • web-javascript • Google Chrome 90.0.4430.212
    • Edge (web)             • edge     • web-javascript • Microsoft Edge 90.0.818.56

! Doctor found issues in 1 category.
```

```console
[✓] Flutter (Channel beta, 2.2.0, on Microsoft Windows [Version 10.0.19042.985], locale en-US)
    • Flutter version 2.2.0 at C:\Users\Taha\Code\flutter_beta
    • Framework revision b22742018b (6 days ago), 2021-05-14 19:12:57 -0700
    • Engine revision a9d88a4d18
    • Dart version 2.13.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\Taha\Code\SDK
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java.exe
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.6)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.9.31313.79
    • Windows 10 SDK version 10.0.19041.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[✓] IntelliJ IDEA Community Edition (version 2021.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.1.1
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.56.2)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.22.0

[✓] Connected device (4 available)
    • Redmi K20 Pro (mobile) • def0ad20 • android-arm64  • Android 10 (API 29)
    • Windows (desktop)      • windows  • windows-x64    • Microsoft Windows [Version 10.0.19042.985]
    • Chrome (web)           • chrome   • web-javascript • Google Chrome 90.0.4430.212
    • Edge (web)             • edge     • web-javascript • Microsoft Edge 90.0.818.56

! Doctor found issues in 1 category.
```

```console
[✓] Flutter (Channel dev, 2.3.0-12.1.pre, on Microsoft Windows [Version 10.0.19042.985], locale en-US)
    • Flutter version 2.3.0-12.1.pre at C:\Users\Taha\Code\flutter_dev
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f9c825981c (2 days ago), 2021-05-18 14:07:52 -0700
    • Engine revision 26e217e6c3
    • Dart version 2.14.0 (build 2.14.0-edge.a527411e5100a0a4f48c4009087a1b988aa784af)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\Taha\Code\SDK
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.6)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.9.31313.79
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 4.2.0)
    • Android Studio at C:\Users\Taha\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[✓] IntelliJ IDEA Community Edition (version 2021.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.1.1
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.56.2)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.22.0

[✓] Connected device (5 available)
    • Redmi K20 Pro (mobile)  • def0ad20 • android-arm64   • Android 10 (API 29)
    • Windows (desktop)       • windows  • windows-x64     • Microsoft Windows [Version 10.0.19042.985]
    • Windows (UWP) (desktop) • winuwp   • windows-uwp-x64 •
    • Chrome (web)            • chrome   • web-javascript  • Google Chrome 90.0.4430.212
    • Edge (web)              • edge     • web-javascript  • Microsoft Edge 90.0.818.56

• No issues found!
```

```console
[✓] Flutter (Channel master, 2.3.0-13.0.pre.59, on Microsoft Windows [Version 10.0.19042.985], locale en-US)
    • Flutter version 2.3.0-13.0.pre.59 at C:\Users\Taha\Code\flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 1e35f4c0c6 (8 hours ago), 2021-05-20 03:14:01 -0400
    • Engine revision 67c537d41b
    • Dart version 2.14.0 (build 2.14.0-129.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\Taha\Code\SDK
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.6)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.9.31313.79
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 4.2.0)
    • Android Studio at C:\Users\Taha\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[✓] IntelliJ IDEA Community Edition (version 2021.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.1.1
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.56.2)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.22.0

[✓] Connected device (5 available)
    • Redmi K20 Pro (mobile)  • def0ad20 • android-arm64   • Android 10 (API 29)
    • Windows (desktop)       • windows  • windows-x64     • Microsoft Windows [Version 10.0.19042.985]
    • Windows (UWP) (desktop) • winuwp   • windows-uwp-x64 •
    • Chrome (web)            • chrome   • web-javascript  • Google Chrome 90.0.4430.212
    • Edge (web)              • edge     • web-javascript  • Microsoft Edge 90.0.818.56

• No issues found!
```
		
</details>

✅ : Reproducible ❌: Not Reproducible

### but I am not sure what's the mouse issue you're describing, please explain the mouse issue

**Comment by selvam920** [comment] 2021-05-20 18:41
The mouse is like scroll mouse wheel or hold left mouse and move up and down then the page is not moving smooth, looks like stuck in between

**Comment by TahaTesser** [comment] 2021-05-21 08:46
Hi @selvam920 
Thanks for the details 
The keyboard issue looks like a duplicate of https://github.com/flutter/flutter/issues/78769

I can now also reproduce the mouse

No matter how fast I scroll, scrolling is slow  as snail on Android when using Bluetooth mouse 

Reproduced on the following channels
|  `channel`  | `result` | 
| :---: |:---: |
|  `stable` |  reproduced  | 
|  `master` |  doesn't reproduced  | 


Check `flutter doctor -v` outputs for each channel below

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.2.0, on Microsoft Windows [Version 10.0.19042.985], locale en-US)
    • Flutter version 2.2.0 at C:\Users\Taha\Code\flutter_stable
    • Framework revision b22742018b (6 days ago), 2021-05-14 19:12:57 -0700
    • Engine revision a9d88a4d18
    • Dart version 2.13.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\Taha\Code\SDK
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java.exe
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.6)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.9.31313.79
    • Windows 10 SDK version 10.0.19041.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[✓] VS Code (version 1.56.2)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.22.0

[✓] Connected device (4 available)
    • Redmi K20 Pro (mobile) • def0ad20 • android-arm64  • Android 10 (API 29)
    • Windows (desktop)      • windows  • windows-x64    • Microsoft Windows [Version 10.0.19042.985]
    • Chrome (web)           • chrome   • web-javascript • Google Chrome 90.0.4430.212
    • Edge (web)             • edge     • web-javascript • Microsoft Edge 90.0.818.56

! Doctor found issues in 1 category.
```

```console
[✓] Flutter (Channel master, 2.3.0-13.0.pre.87, on Microsoft Windows [Version 10.0.19042.985], locale en-US)
    • Flutter version 2.3.0-13.0.pre.87 at C:\Users\Taha\Code\flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4d6a925326 (4 hours ago), 2021-05-21 01:09:02 -0400
    • Engine revision 20260fb95f
    • Dart version 2.14.0 (build 2.14.0-134.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\Taha\Code\SDK
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.6)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.9.31313.79
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 4.2.0)
    • Android Studio at C:\Users\Taha\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[✓] VS Code (version 1.56.2)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.22.0

[✓] Connected device (5 available)
    • Redmi K20 Pro (mobile)  • def0ad20 • android-arm64   • Android 10 (API 29)
    • Windows (desktop)       • windows  • windows-x64     • Microsoft Windows [Version 10.0.19042.985]
    • Windows (UWP) (desktop) • winuwp   • windows-uwp-x64 •
    • Chrome (web)            • chrome   • web-javascript  • Google Chrome 90.0.4430.212
    • Edge (web)              • edge     • web-javascript  • Microsoft Edge 90.0.818.56

```
		
</details>

**Comment by chinmaygarde** [comment] 2021-05-24 18:23
This may be a case of scroll wheel deltas not wired up correctly. Perhaps not taking into account DPI scaling? cc @gspencergoog

**Comment by selvam920** [comment] 2021-05-27 03:34
This issue not only android phone found in android tv, chromebook also

**Comment by selvam920** [comment] 2021-05-27 03:35
Tag P4 added this issue, when will it be fixed?

**Comment by rxvincent** [comment] 2022-08-09 07:08
Any update? This issue is still reproduced at 3.3.0-0.1pre.

**Comment by Onein** [comment] 2022-08-18 09:03
Would be great if this issue and #107400 would get some attention, because now Flutter apps are barely usable on Chrome OS devices.

**Comment by selvam920** [comment] 2022-09-25 16:30
Any update in this issue?

**Comment by selvam920** [comment] 2023-01-24 04:12
any update on this?

**Comment by esDotDev** [comment] 2023-04-18 19:24
Is there some sort of workaround we could use to fix this for all lists across the app? 

We could probably manually listen to the mouse wheel and drive the scroll controller ourselves, but we would need to do that manually for every list in the app. Maybe there is a more straightforward way?

**Comment by reidbaker** [comment] 2023-05-02 19:54
Code that could be relevent https://github.com/flutter/engine/blob/d7375ebfc6a88ac0e56f12e61d6320694b2ef128/shell/platform/android/io/flutter/embedding/android/AndroidTouchProcessor.java#L337

**Comment by selvam920** [comment] 2023-05-21 16:19
still waiting for this issue

**Comment by selvam920** [comment] 2023-05-26 10:04
anyone working for this issue?

**Comment by bksubhuti** [comment] 2023-06-09 09:39
I recently had a report about our app not supporting proper scrolling with Bluetooth mice.  Our app is multi-platform on Windows, Android, ioS, Mac, Linux.  I borrowed a BT mouse for testing.  I can confirm that **Bluetooth mouse support works with our desktop app** but with virtually the same code on android, it has the same issue reported here:  **very slow scroll wheel scrolling problem**.  I would imagine this was forgotten for Android because it was assumed that the user would use the touch features.  However, people connect BT keyboards and mice to tablets all of the time.  Our app also supports a desktop mode while rotated in landscape android.

We have over 2000 active devices for Android:  
Android App  https://play.google.com/store/apps/details?id=com.paauk.tipitakapalireader
Windows App  https://apps.microsoft.com/store/detail/tipitaka-pali-reader/9MTH9TD82TGR?hl=en-us&gl=us

Furthermore, to be sure it was a flutter problem I downloaded syncfusion (flutter gallery app) and went to the pdf reader sample.  This android bt mouse scroll problem also existed.   It is therefore a flutter framework problem.
https://play.google.com/store/apps/details?id=com.syncfusion.flutter.examples

**Comment by selvam920** [comment] 2023-06-09 09:47
Seems no one is working with this bug, this bug was created two years ago

**Comment by selvam920** [comment] 2023-06-09 10:53
This bug did not close from when i created

**Comment by bksubhuti** [comment] 2023-06-09 14:23
I think you have the power to close.  and you have the power to create.  The focus of the bug seemed to be diverted to keyboard.  I'd close it .. then make a new bug report .  If you have the minimum app, then you can explain.. plus you can reference 3 other apps.  Your own, mine, and syncfusion.  Furthermore, syncfusion and TPR are available on the store.  Furthermore, I can confirm that scrolling does work on windows desktop.  Lastly, there are 2000 android devices using our TPR app and we have stated a better reason why it is need.  

Close the issue.. and then make a new one.   share the link when you do.

**Comment by esDotDev** [comment] 2023-06-09 16:21
I'd keep this open, it has 15 upvotes which is a core metric the Flutter team uses to determine priority. I know this issue is already on the Flutter teams radar as well.  If anything just update the OP to be more clear/specific

**Comment by gspencergoog** [comment] 2023-06-09 16:27
We do look at comments on existing bugs, and filing a new identical bug will not get a different prioritization. I'm sorry this hasn't risen to the top of our queue: there are a lot of other issues to attend to.

I'm reopening this because it has a lot of context that would be lost in a new issue (including recent comments).

**Comment by selvam920** [comment] 2023-06-09 16:36
Is there any use to reopen this bug? Bcoz this bug we waited almost 2 years

**Comment by gspencergoog** [comment] 2023-06-09 16:50
Yes, in includes investigative work that we won't have to do again when we get to fixing it. It has a reproduction steps and verification, as well as upvotes that will help it get to the top of the queue. There's plenty of reason to keep it open.

**Comment by bksubhuti** [comment] 2023-06-10 09:46
okay.. looks like we got some attention.  I hope my information helped.  Furthermore, Flutter was quite new then.  I would imagine this is one of the issues they would like to solve at this point and tablet as a computer is more common now too.  Desktops were in beta back then.  I hope we can test a fix for this soon.

**Comment by selvam920** [comment] 2023-06-10 11:49
Let's see still how many years needs to wait

**Comment by selvam920** [comment] 2023-08-10 01:39
any update?

**Comment by bksubhuti** [comment] 2023-08-10 03:22
you would need to test and let me know.. However, we did add keyboard scrolling.  You can see if that works on android.
pageup and pagedown and updown arrows work on desktop.

**Comment by selvam920** [comment] 2023-08-10 04:44
Are you talking about android or desktop?

**Comment by bksubhuti** [comment] 2023-08-10 05:29
You are talking about android.. therefore I'm also saying.. hey you can try testing.  I don't have the ability to test without asking for equipment from another monk.  If you report back your findings with your own equipment based on android.

**Comment by reidbaker** [comment] 2023-08-15 14:21
Update I found a solution to this and am working on the unit tests now. It did however expose that flutter takes a few seconds longer than android to register mouse input. I may need to file a different issue to track that work.

**Closed** 2023-08-22 18:23 UTC
Labels: platform-android, engine, a: mouse, has reproducible steps, P2, found in release: 2.2, found in release: 2.3, team-android, triaged-android, multiteam-retriage-candidate

**Comment by selvam920** [comment] 2023-08-23 11:33
@reidbaker Wow, it's great working on master channel
