### ISSUE TITLE
App crash instantly without any logs on android api 19

### ISSUE THREAD

**Issue by hasanmhallak** [flutter/flutter#132005] opened 2023-08-06 08:06 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. create a new flutter project.
2. run the project on a android api 19 emulator or a real device with KItKat.

### Expected results

I tried changing GPA to 7.4 or 7.2 but it did not make any difference. I also tried to disable minifying like this:

```Groovy
    buildTypes {
        debug {
          minifyEnabled false
          shrinkResources false
        }
    }
```

I don't think this is revenant to  #115100 because it happens with/without minify.

### Actual results

The console hangs on `Waiting for VM Service port to be available...` and the app crash upon opening.

### Logs

[logs.txt](https://github.com/flutter/flutter/files/12268928/logs.txt)

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.10.6, on macOS 13.2 22D49 darwin-arm64, locale en-EG)
    • Flutter version 3.10.6 on channel stable at /Users/hasanm.hallak/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (3 weeks ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/hasanm.hallak/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • Java binary at: /Applications/Android Studio Preview.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio
    • Android Studio at /Applications/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.80.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.71.20230801

[✓] Connected device (2 available)
    • google sdk (mobile) • emulator-5554 • android-arm    • Android 4.4.2 (API 19) (emulator)
    • Chrome (web)        • chrome        • web-javascript • Google Chrome 115.0.5790.114

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by huycozy** [comment] 2023-08-07 10:54
Hi @hasanmhallak 
I see there are some reports at https://github.com/flutter/flutter/issues/115100 also mentioned the case without enabling minification as well (see https://github.com/flutter/flutter/issues/115100#issuecomment-1324431695, https://github.com/flutter/flutter/issues/115100#issuecomment-1328172982).

Can you try catching the crash log from adb and share it here?

**Comment by hasanmhallak** [comment] 2023-08-07 10:59
hey @huycozy, thank you for your respond. I checked that issue report and some them was an issue in the GPA, and eventually I read somewhere that they fix the gradle plugin with an update. so it wasn't a flutter issue per se.  

yet, I have tried multiple versions of GPA, and the crash still there.  

I'm happy to provide the crash log from the adb.

**Comment by hasanmhallak** [comment] 2023-08-07 11:10
Here is the crash report: 
[crash.txt](https://github.com/flutter/flutter/files/12278997/crash.txt)

**Comment by huycozy** [comment] 2023-08-08 04:13
Thanks for the update. I can see there are memory traces in the crash log. Also, looks like the log is from your production project, right? Can you retry on a newly created project and share the crash log again? (to make sure no implementation code can affect to the cause of this issue)

```console
I/WindowManager( 1045): Screenshot max retries 4 of Token{9e410c60 ActivityRecord{9e0aaa10 u0 com.hmh.height_weight_calculator/.MainActivity t28 f}} appWin=Window{9ddffe08 u0 Starting com.hmh.height_weight_calculator} drawState=4
W/WindowManager( 1045): Screenshot failure taking screenshot for (1080x2280) to layer 21015
W/ActivityManager( 1045): Exception thrown during pause
W/ActivityManager( 1045): android.os.DeadObjectException
W/ActivityManager( 1045): 	at android.os.BinderProxy.transact(Native Method)
W/ActivityManager( 1045): 	at android.app.ApplicationThreadProxy.schedulePauseActivity(ApplicationThreadNative.java:660)
W/ActivityManager( 1045): 	at com.android.server.am.ActivityStack.startPausingLocked(ActivityStack.java:761)
W/ActivityManager( 1045): 	at com.android.server.am.ActivityStack.finishActivityLocked(ActivityStack.java:2455)
W/ActivityManager( 1045): 	at com.android.server.am.ActivityStack.finishTopRunningActivityLocked(ActivityStack.java:2329)
W/ActivityManager( 1045): 	at com.android.server.am.ActivityStackSupervisor.finishTopRunningActivityLocked(ActivityStackSupervisor.java:2035)
W/ActivityManager( 1045): 	at com.android.server.am.ActivityManagerService.handleAppCrashLocked(ActivityManagerService.java:9543)
W/ActivityManager( 1045): 	at com.android.server.am.ActivityManagerService.makeAppCrashingLocked(ActivityManagerService.java:9436)
W/ActivityManager( 1045): 	at com.android.server.am.ActivityManagerService.crashApplication(ActivityManagerService.java:10081)
W/ActivityManager( 1045): 	at com.android.server.am.ActivityManagerService.handleApplicationCrashInner(ActivityManagerService.java:9632)
W/ActivityManager( 1045): 	at com.android.server.am.NativeCrashListener$NativeCrashReporter.run(NativeCrashListener.java:86)
```

**Comment by hasanmhallak** [comment] 2023-08-08 07:39
hey @huycozy thank you for checking out the logs. Here is the logs for an empty flutter project:  

[crash2.txt](https://github.com/flutter/flutter/files/12288584/crash2.txt)

**Comment by huycozy** [comment] 2023-08-09 04:16
Thanks for your update. Based on the stack trace, I just found there's an open issue similar to this: https://github.com/flutter/flutter/issues/92137.

Closing this issue as a duplicate, so please follow up on it for further updates. You can leave there your comment and react an upvote to the original comment will help to raise the issue. Thank you!

**Closed by huycozy** 2023-08-09 04:16 UTC
Labels: in triage
