### ISSUE TITLE
A standalone Flutter/Dart IDE

### ISSUE THREAD

**Issue by cleangist** [flutter/flutter#91295] opened 2021-10-05 11:55 UTC
In creating a Flutter Project using Android Studio, I find the Link to **New Image Asset** missing. See it here-- https://prnt.sc/1uac6qb

I'm also facing many small issues here and there with Android Studio.

From here (https://prntscr.com/1uqfk4n), I got some discomfort.

And I think something was being made clear to us that Flutter and Dart are on Rental to Android Studio-- as if Flutter is borrowing space in Android Studio, and Flutter doesn't have esteemed and equality Status with Android Studio's recognition of Java and Kotlin Projects.

It's as if the Android Studio’s structure was built in its core to see non-Java and Non-Kotlin Projects such as Flutter Projects like low-level projects, lower than the heels of Android Studio's Java and Kotlin Projects. As if Flutter/Dart projects are a kind of disdainful and inferior entity.

This is why I believe that the Dart/Flutter Project should also be a standalone project.

Since I believe that Android and Android Studio were Google supported creations.

And Dart/Flutter is now a Google supported creation.

Then it should be no problem allowing Dart/Flutter to use the sdk tools in Android Studio that makes it able to render APK Mobile App formats, without using Android Studio at all. But through a Custom IDE built specifically for Dart and Flutter to render Codes for Android and iOS Apps.

In this way, we don't have to face the seeming issues that we face in trying to use Android Studio for Flutter/Dart Projects.

Will be interested to see the Flutter/Dart Team tell me that this will be done soon.

Regards.

**Comment by maheshmnj** [comment] 2021-10-05 12:45
@cleangist, The standalone IDE in a flutter looks more of a personal use case to me which flutter might not be the right tool at this time since an IDE is much more than a code editor and has tonnes of integrated tools. IDE's like Android Studio is a result of years of development which has been improved over the years by understanding the needs and pain points of the developers.
On the Other hand, flutter is a UI toolkit that provides you with tools to build cross-platform apps and you free to build whatever you want to.

> I'm also facing many small issues here and there with Android Studio.

you can report your issue and proposal about Android studio here https://issuetracker.google.com/issues/new.

> It's as if the Android Studio’s structure was built in its core to see non-Java and Non-Kotlin Projects such as Flutter Projects like low-level projects, lower than the heels of Android Studio's Java and Kotlin Projects. As if Flutter/Dart projects are a kind of disdainful and inferior entity.

The doesn't seem to be a plausible reason to build a complete IDE in a flutter for sake of solving a small issue (if it really is).

If you are much interested in using an IDE built with flutter, there have been few efforts from the community member  one of them is by @lesnitsky, you can take a look here: https://twitter.com/lesnitsky_dev/status/1232703801850843136?lang=en 

Closing this issue, since this doesn't seem to describe a bug or feature request in the flutter framework.

Thank you.

**Closed by maheshmnj** 2021-10-05 12:45 UTC
Labels: in triage

**Comment by TahaTesser** [comment] 2021-10-05 12:49
duplicate of https://github.com/flutter/flutter/issues/91211
