### ISSUE TITLE
SelectedTileColor property

### ISSUE THREAD

**Issue by gohaneri** [flutter/flutter#83085] opened 2021-05-21 08:57 UTC
Started from Flutter 2.22, selectedTileColor property of ListTileTheme it seems to no longer work properly

Example:

```dart
ListTileTheme(
          iconColor: MyTheme.popBlue,
          textColor: MyTheme.popBlue,
          selectedColor: Colors.white,
          selectedTileColor: MyTheme.popBlue,
)
```

In this example, by selecting the Tile, its background does not change color

**Comment by SushantChandla** [comment] 2021-05-21 12:06
Can you please provide minimum reproducible code?

**Comment by SushantChandla** [comment] 2021-05-21 12:06
Can you please provide minimum reproducible code?

**Comment by TahaTesser** [comment] 2021-05-21 15:06
Hi @gohaneri 
Thanks for filing the issue, I cannot reproduce the issue on the `Channel stable, 2.2.0` 

<details> 
<summary>minimal code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: ListTileTheme(
          selectedTileColor: Colors.cyan,
          child: ListTile(
            title: Text('Text'),
            selected: true,
          ),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {},
      ),
    );
  }
}

``` 

</details>

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel beta, 2.2.0, on macOS 11.3.1 20E241 darwin-x64, locale en-GB)
    • Flutter version 2.2.0 at /Users/tahatesser/Code/flutter_beta
    • Framework revision b22742018b (7 days ago), 2021-05-14 19:12:57 -0700
    • Engine revision a9d88a4d18
    • Dart version 2.13.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.56.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.22.0

[✓] Connected device (3 available)
    • iPhone 12 (mobile) • D72A5DAA-24E6-421B-B4F5-7CFAFB498040 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)    • macos                                • darwin-x64     • macOS 11.3.1 20E241
      darwin-x64
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome
      90.0.4430.212

• No issues found!
```

</details>

**Comment by proninyaroslav** [comment] 2021-05-21 16:19
@TahaTesser 
Probably these problems are interrelated https://github.com/flutter/flutter/issues/83108

**Comment by gohaneri** [comment] 2021-05-21 17:41
> @TahaTesser
> Probably these problems are interrelated #83108

Yes, this could be related: i’ve the same structure and listtile color seems to be transaprent

**Comment by proninyaroslav** [comment] 2021-05-22 08:47
@gohaneri 
You can try using `Material` widget instead of `Container`, this helped me.

**Comment by TahaTesser** [comment] 2021-05-24 06:32
Hi @gohaneri 
Are you using also using a container with color?
Can you please provide a complete reproducible minimal code sample?
Thank you

**Comment by gohaneri** [comment] 2021-05-24 07:05
I noticed that in Flutter 2.22 the list_tile.dart is different:

Flutter 2.22:

Ink (
           decoration: ShapeDecoration (
             shape: shape ?? tileTheme.shape ?? const Border (),
             color: _tileBackgroundColor (tileTheme),
           )

Flutter <2.22

ColoredBox (
           color: _tileBackgroundColor (tileTheme),
)

Could this be related? ColoredBox seems working fine instead of Ink

**Comment by TahaTesser** [comment] 2021-05-24 07:27
Hi @gohaneri 
I already mentioned this here https://github.com/flutter/flutter/issues/83108
Since you didn't provide a code sample which has any difference, closing as a duplicate of https://github.com/flutter/flutter/issues/83108
Thank you

**Closed by TahaTesser** 2021-05-24 07:27 UTC
Labels: in triage
