### ISSUE TITLE
Flutter 3.22.3: Lack of Support for New Material 3 Slider Style

### ISSUE THREAD

**Issue by G705-Ghilan** [flutter/flutter#152738] opened 2024-08-02 09:20 UTC
### Use case

![Screenshot 2024-08-02 121138](https://github.com/user-attachments/assets/fed3fa6b-a17f-42c7-866a-23cc906991aa)
The current version of Flutter (3.22.3) does not support the new Material 3 design specifications for sliders. The existing Slider widget still applies the old Material 2 design and lacks the features and styling options required to implement the updated Material 3 slider design as outlined in the Material 3 style guides.

### Proposal

the issue is that developers cannot easily create sliders that conform to the new Material 3 design guidelines using the existing Slider widget in Flutter. This inconsistency makes it challenging to maintain a cohesive and modern design across applications.

**Comment by G705-Ghilan** [comment] 2024-08-02 09:20
I hope flutter team fix that as soon as possible :)

**Comment by danagbemava-nc** [comment] 2024-08-02 09:37
Closing this as a duplicate of https://github.com/flutter/flutter/issues/141842

**Closed by danagbemava-nc** 2024-08-02 09:37 UTC
Labels: in triage
