### ISSUE TITLE
plugins fail analysis right after creation

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#13646] opened 2017-12-18 12:17 UTC
## Steps to Reproduce

1. `flutter create -t plugin test01`
1. `cd test01`
1. `flutter analyze`

=>

```
Analyzing /Users/mit/tmp/test01...
  error • Target of URI doesn't exist: 'package:test01_example/main.dart' at example/test/widget_test.dart:10:8 • uri_does_not_exist
  error • The constructor returns type 'dynamic' that isn't of expected type 'Widget' at example/test/widget_test.dart:15:29 • strong_mode_invalid_cast_new_expr
  error • Undefined class 'MyApp' at example/test/widget_test.dart:15:33 • undefined_class
3 issues found.
(Ran in 5.4s)
```

**Comment by goderbauer** [comment] 2017-12-18 21:09
The reported issues are bogus and not really present. The problem is that the analyze command can't handle nested packages (the example package is nested inside the plugin packages).

Closing this as a dub of https://github.com/flutter/flutter/issues/10015.

**Closed by goderbauer** 2017-12-18 21:09 UTC
Labels: plugin, plugin: framework
