### ISSUE TITLE
[go_router] Add `BuildContext` to `GoRouterRedirect` signature

### ISSUE THREAD

**Issue by bambinoua** [flutter/flutter#103411] opened 2022-05-10 13:26 UTC
## Use case

To define if user is authenticated or no I use the `isAuthenticated` property of `AppState`. This state is provided via `Provider`. To get authentication boolean I need to read AppState from context but it is impossible due lack of provided `context`. 

As `GoRouter` is `final` property of owning class I cannot use non instance variable but only `static` one. And I think it is incorrect to create a `static` property just for redirection.

## Proposal

Change `GoRouterRedirect` signature so it contains `BuildContext`.

**Comment by bambinoua** [comment] 2022-05-10 16:12
If this issue is duplication of #99121, please close it.

**Comment by darshankawar** [comment] 2022-05-11 06:34
That does look like duplicate of linked issue. Please follow-up in it for further updates.

**Closed by darshankawar** 2022-05-11 06:34 UTC
Labels: in triage
