### ISSUE TITLE
Disabling animations on a device does not disable navigating animations for Flutter apps

### ISSUE THREAD

**Issue by JoseGeorges8** [flutter/flutter#71080] opened 2020-11-23 14:11 UTC
## Steps to Reproduce

1. Run any app
2. Disable animations on your device (easy search through device settings for most androids)
3. Navigate through pages

**Expected results:** 
To not animate between navigation

**Actual results:** 
App still animates navigation

**Comment by pedromassangocode** [comment] 2020-11-23 14:32
Hi @JoseGeorges8 
Can you please provide your `flutter doctor -v` and a minimal complete reproducible code sample?
Thank you

**Comment by sidrao2006** [comment] 2020-11-23 14:37
Related to #51571

**Comment by JoseGeorges8** [comment] 2020-11-23 15:19
```√] Flutter (Channel stable, 1.22.4, on Microsoft Windows [Version 10.0.19041.630], locale en-CA)
    • Flutter version 1.22.4 at C:\Users\Jose.Georges\Desktop\flutter
    • Framework revision 1aafb3a8b9 (10 days ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4


[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\Jose.Georges\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = C:\Users\Jose.Georges\AppData\Local\Android
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.51.1)
    • VS Code at C:\Users\Jose.Georges\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.16.0

[√] Connected device (2 available)
    • Pixel 3 XL (mobile)         • 8BQY12FAC     • android-arm64 • Android 10 (API 29)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86   • Android 11 (API 30) (emulator)

! Doctor found issues in 1 category.
```

Here's the doctor. I'm currently busy and cannot provide an example, although literally any app with a simple material app routing navigation works. Will provide an example later today.

**Comment by sidrao2006** [comment] 2020-11-23 15:25
Hello @JoseGeorges8 , this is reproducible but an intended behaviour as mentioned in #51571

**Comment by pedromassangocode** [comment] 2020-11-24 06:28
Yes, this seems to be the expected behavior, please see https://github.com/flutter/flutter/issues/51571#issuecomment-592203930. Closing this per https://github.com/flutter/flutter/issues/51571#issuecomment-592274813.

**Closed by pedromassangocode** 2020-11-24 06:28 UTC
Labels: in triage
