### ISSUE TITLE
Calling native API from [webview_flutter]?

### ISSUE THREAD

**Issue by leshik** [flutter/flutter#26462] opened 2019-01-12 14:14 UTC
I have ReactJS web application that is designed to work in Chrome on desktop (because of the WebKit Speech Recognition). On mobile I have to use native APIs for that (and also for the native social login with Facebook through their app). I'm doing this with Capacitor (Ionic replacement for Cordova) now. Would be nice if I could call native APIs from webview_flutter widget, thus using flutter plugins from javascript. Then I would be able to migrate to flutter gradually. Is this a planned functionality that we can expect in the future?

**Comment by zoechi** [comment] 2019-01-12 15:39
Looks like a duplicate of #24837 to me.

I doubt it's possible to have a direct way to access native features from JavaScript because the webview plugin is just the native browser component, nothing built by Flutter.
The webview plugin is just a wrapper.

**Closed by zoechi** 2019-01-12 15:39 UTC
