### ISSUE TITLE
======== Exception caught by widgets library ======================================================= The following assertion was thrown building MediaQuery(MediaQueryData(size: Size(360.0, 732.0), devicePixelRatio: 3.0, textScaleFactor: 1.0, platformBrightness: Brightness.dark, padding: EdgeInsets.zero, viewPadding: EdgeInsets.zero, viewInsets: EdgeInsets.zero, alwaysUse24HourFormat: false, accessibleNavigation: false, highContrast: false, disableAnimations: false, invertColors: false, boldText: false, navigationMode: traditional, gestureSettings: DeviceGestureSettings(touchSlop: 8.0), displayFeatures: [])): 'package:flutter/src/widgets/framework.dart': Failed assertion: line 4606 pos 14: 'owner!._debugCurrentBuildTarget == this': is not true.

### ISSUE THREAD

**Issue by Battleandroid** [flutter/flutter#114256] opened 2022-10-28 20:27 UTC
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by iapicca** [comment] 2022-10-29 16:26
self duplicate of https://github.com/flutter/flutter/issues/114255

**Closed** 2022-10-31 07:25 UTC
Labels: in triage
