### ISSUE TITLE
When setting `background_mode` to `transparent`, widgets flicker between it's previous and current state

### ISSUE THREAD

**Issue by neophob** [flutter/flutter#109226] opened 2022-08-09 14:08 UTC
## Steps to Reproduce

Tested and reproduced the flicking on Android - did not see the issue on iOS. We created a minimal example here: https://github.com/gyuri-fluttech/flutter_flicker_bug -> tested with all existing 3.0.x and 3.1.0 and 3.3.x-pre Flutter versions - all show the same issue - when the Flutter app resumes, some older frames are displayed, this looks like a flickering.

https://user-images.githubusercontent.com/837347/183669173-fc803a58-9f40-43f6-8b8f-9f575deb6ecb.MOV

Observations:
- When I add key: UniqueKey() to the text widget, I cannot reproduce the error anymore!
- The error is only visible when this line is active: https://github.com/gyuri-fluttech/flutter_flicker_bug/blob/8afea40d61e2fcee6ba69e55ec6ccef0de857a00/android/app/src/main/java/com/example/flicker_test/MainActivity.java#L47 
- The flickering is not visible every-time - on my test devices I had at lease one flickering when I locked/unlocked the device 10 times.
- Android Animation timings have an influence on this issue

What is the preferred way to have a transparent background

<details>
  <summary>Logs</summary>

```
[   +3 ms] Flutter run key commands.
[   +1 ms] r Hot reload. 🔥🔥🔥
[        ] R Hot restart.
[        ] h List all available interactive commands.
[        ] d Detach (terminate "flutter run" but leave application running).
[        ] c Clear the screen
[        ] q Quit (terminate the application on the device).
[        ] 💪 Running with sound null safety 💪
[        ] An Observatory debugger and profiler on LM G850 is available at: http://127.0.0.1:51922/Rs24BLfOTas=/
[  +22 ms] The Flutter DevTools debugger and profiler on LM G850 is available at: http://127.0.0.1:9101?uri=http://127.0.0.1:51922/Rs24BLfOTas=/
[+1035 ms] I/ViewRootImpl( 1749): ViewRoot's Touch Event : ACTION_DOWN
[   +4 ms] D/HandGripFilter( 1749): Filter[0] Ignore [Side] at x: 1060 y: 2248 with major: 194 minor:79 orientation: 0.05235988
[        ] D/HandGripFilter( 1749): mMiddleGripMask[0]
[ +112 ms] D/HandGripFilter( 1749): Filter[0] Pass
[        ] I/ViewRootImpl( 1749): ViewRoot's Touch Event : ACTION_POINTER_DOWN(1)
[   +3 ms] I/ViewRootImpl( 1749): ViewRoot's Touch Event : ACTION_POINTER_UP(1)
[   +8 ms] I/ViewRootImpl( 1749): ViewRoot's Touch Event : ACTION_POINTER_DOWN(1)
[ +397 ms] I/ViewRootImpl( 1749): ViewRoot's Touch Event : ACTION_POINTER_UP(0)
[   +9 ms] I/ViewRootImpl( 1749): ViewRoot's Touch Event : ACTION_POINTER_DOWN(0)
[        ] D/HandGripFilter( 1749): Filter[0] Ignore [Side] at x: 1070 y: 2239 with major: 79 minor:79 orientation: 0.0
[        ] D/HandGripFilter( 1749): mMiddleGripMask[0]
[  +12 ms] I/ViewRootImpl( 1749): ViewRoot's Touch Event : ACTION_POINTER_UP(0)
[  +18 ms] I/ViewRootImpl( 1749): ViewRoot's Touch Event : ACTION_POINTER_DOWN(0)
[        ] D/HandGripFilter( 1749): Filter[0] Ignore [Side] at x: 1071 y: 2239 with major: 79 minor:79 orientation: 0.0
[        ] D/HandGripFilter( 1749): mMiddleGripMask[0]
[ +444 ms] I/ViewRootImpl( 1749): ViewRoot's Touch Event : ACTION_POINTER_UP(1)
[ +217 ms] I/ViewRootImpl( 1749): ViewRoot's Touch Event : ACTION_UP
[+1187 ms] I/ViewRootImpl( 1749): ViewRoot's Touch Event : ACTION_DOWN
[ +221 ms] I/ViewRootImpl( 1749): ViewRoot's Touch Event : ACTION_UP
[+2568 ms] D/TextureView( 1749): getHardwareLayer, createNewSurface:false
[+2270 ms] D/TextureView( 1749): getHardwareLayer, createNewSurface:false
[+2237 ms] D/TextureView( 1749): getHardwareLayer, createNewSurface:false
[+2068 ms] D/TextureView( 1749): getHardwareLayer, createNewSurface:false
[+2048 ms] D/TextureView( 1749): getHardwareLayer, createNewSurface:false
[+5618 ms] I/ViewRootImpl( 1749): ViewRoot's Touch Event : ACTION_DOWN
[ +126 ms] I/ViewRootImpl( 1749): ViewRoot's Touch Event : ACTION_UP
[  +30 ms] I/ViewRootImpl( 1749): ViewRoot's Touch Event : ACTION_DOWN
[  +61 ms] I/ViewRootImpl( 1749): ViewRoot's Touch Event : ACTION_UP
```

```
Analyzing flutter_flicker_bug...

   info • Avoid using private types in public APIs • lib/time.dart:12:3 • library_private_types_in_public_api

1 issue found. (ran in 4.3s)
```

```
[✓] Flutter (Channel beta, 3.3.0-0.2.pre, on macOS 12.5 21G72 darwin-x64, locale de-CH)
    • Flutter version 3.3.0-0.2.pre on channel beta at /Users/michaelvogt/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7ac27ac8e6 (7 days ago), 2022-08-02 14:35:08 -0700
    • Engine revision d1e7dc18bf
    • Dart version 2.18.0 (build 2.18.0-271.4.beta)
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/michaelvogt/Library/Android/sdk
    • Platform android-31, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13F100
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.68.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.46.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.5 21G72 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 104.0.5112.79

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by huycozy** [comment] 2022-08-10 03:55
Hi @neophob 
I can not reproduce the issue on the latest `stable` and `master` channels with provided sample code. It is not flickering like yours.
Device information: Samsung Galaxy Tab A7 Lite Android 11 OneUI 3.1, SM-T225

Which Android device are you using? Please provide the affected device information.

<details>
<summary>Demo</summary>

https://user-images.githubusercontent.com/104349824/183808634-ba3e5ff8-a8d8-4834-8d02-b43192e3af2b.mov

</details>

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.2.1 21D62 darwin-x64, locale en-VN)
    • Flutter version 3.0.5 at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (9 hours ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2020.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.69.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.44.0

[✓] Connected device (3 available)
    • SM T225 (mobile) • R9JT3004VRJ • android-arm64  • Android 11 (API 30)
    • macOS (desktop)  • macos       • darwin-x64     • macOS 12.2.1 21D62 darwin-x64
    • Chrome (web)     • chrome      • web-javascript • Google Chrome 103.0.5060.114

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

```bash
[✓] Flutter (Channel master, 3.1.0-0.0.pre.2183, on macOS 12.5 21G72 darwin-x64, locale en-VN)
    • Flutter version 3.1.0-0.0.pre.2183 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f807e6390e (34 minutes ago), 2022-08-09 21:42:05 -0400
    • Engine revision a8a328bbe6
    • Dart version 2.19.0 (build 2.19.0-80.0.dev)
    • DevTools version 2.16.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13E113
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2020.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.70.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.46.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.5 21G72 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 104.0.5112.79

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!


```
</details>

**Comment by neophob** [comment] 2022-08-10 07:55
Thanks @huycozy for the fast reply. 

I tested it on:
- Android 12, LG G8X ThinQ, LM-G850EMW, V40a-EEA-XX
- Android 11, Custom tablet, alps-mp-r0.mp5-V4.129

More details:
- I had at least at 10% chance to hit the bug when I locked/unlocked the device
- Android Window animations (lock/unlock) definitive have an impact how often the bug is triggered
- We currently workaround the bug by setting a UniqueKey in the root widget

Let me know if I can provide more information to reproduce this issue!

**Comment by exaby73** [comment] 2022-08-10 12:09
Hello @neophob. Unfortunately, I am not able to reproduce this issue. There are a few similar issues:

- https://github.com/flutter/flutter/issues/27449
- https://github.com/flutter/flutter/issues/34864
- https://github.com/flutter/flutter/issues/57541

There is also a possible solution [here](https://github.com/flutter/flutter/issues/59552#issuecomment-713374392). Let me know if this solves your issue

**Comment by neophob** [comment] 2022-08-10 14:01
Thanks @exaby73 
- https://github.com/flutter/flutter/issues/27449 -> quite old (Flutter v1.22) and no solution/proposals
- https://github.com/flutter/flutter/issues/34864 -> also Flutter v1.22, there are artefacts visible that causing the "flickering", I think this is different from this issue
- https://github.com/flutter/flutter/issues/57541 -> think a different issue as the app does not render correctly in the overview mode (when switching tasks)

About the possible solution (https://github.com/flutter/flutter/issues/59552#issuecomment-713374392) - this is related to this error description:

> The error is only visible when this line is active: https://github.com/gyuri-fluttech/flutter_flicker_bug/blob/8afea40d61e2fcee6ba69e55ec6ccef0de857a00/android/app/src/main/java/com/example/flicker_test/MainActivity.java#L47

Only when app is made "transparent" the flickering happens. When I remote this settings, no flickering occurs! Does this help somehow?

**Comment by exaby73** [comment] 2022-08-10 15:07
Thank you @neophob. I agree these issues are different, though unfortunately I am unable to reproduce this issue. It might be device specific. Do you have access to other devices that you may try on? Can you also provide some information on the devices that you are able to reproduce on? Also, whether it reproduces on an emulator or not?

**Comment by neophob** [comment] 2022-08-10 15:14
I guess the problem with these kinds of errors is how to reproduce them - as this looks like an issue in all the similar reports. My wild guess with a limited test set is, that it is not device specific as I could reproduce it on different Android versions (11 and 12), different types (phone and tablet) and different brands (LG and custom).

What I observed is that any animation when the device is locked/unlocked make it harder to reproduce the issue. I also made sure that I had no special lock screen and no security enabled (no pattern, no pin). I set the window animation to the (default) 1x - this increased the chance the error was visible.

**Comment by exaby73** [comment] 2022-08-11 06:05
Thank you @neophob. Labelling for further insights from the team

**Comment by chinmaygarde** [comment] 2022-08-15 17:59
Have we been able to reproduce this on any device? I also cannot see anything in the attached videos. Without this information, there is little to go off of here. This isn't any usage of platform views here either. So not sure how to proceed. Closing this as unactionable. But please reopen if you have additional informaiton.

**Closed by chinmaygarde** 2022-08-15 17:59 UTC
Labels: platform-android, engine

**Comment by neophob** [comment] 2022-08-15 19:17
> Have we been able to reproduce this on any device? I also cannot see anything in the attached videos

I attached the video IMG_1577.MOV - depending on your browser/os you need to download this. I could reproduce it using

- Android 12, LG G8X ThinQ, LM-G850EMW, V40a-EEA-XX
- Android 11, Custom tablet, alps-mp-r0.mp5-V4.129

Let me know what you need so it's more actionable

**Comment by neophob** [comment] 2022-08-15 19:18
Oh - and I'm unable to reopen this issue..

**Comment by exaby73** [comment] 2022-08-16 07:55
@chinmaygarde Is the video not playing for you? If so, you can try on other browser. For me it doesn't play in Brave but it does on Edge and Safari.

In the video, you can see the seconds flickering between 24 and 25 for a short moment.

**Comment by gyuri-fluttech** [comment] 2022-08-17 08:31
I downloaded and converted the `mov` file to `mp4`.  

https://user-images.githubusercontent.com/89968543/185063354-42e288b4-129e-4037-bc3c-6d0ec12bd8e7.mp4
