### ISSUE TITLE
When try to copy something from the Terminal !!!

### ISSUE THREAD

**Issue by imeDevelopers** [flutter/flutter#66010] opened 2020-09-17 09:40 UTC
Terminate batch job (Y/N)? N
batch job have been Terminated !!

this is because you forced us to copy the content using CTRL+C and this maybe don't work as you see above ..

we need an option to copy using the mouse RIGHT click and select copy/paste like any other terminal or cmd ..

or simply fix the error above ...

thanks.

**Comment by pedromassangocode** [comment] 2020-09-17 10:21
Hi @imeDevelopers 
This does not seems to have anything to do with Flutter, can you elaborate what the issue is and how it is related to Flutter?
Thank you

**Comment by PixelToast** [comment] 2020-09-17 16:49
Conventionally in a terminal ctrl-c will abort the current task: https://en.m.wikipedia.org/wiki/Control-C

Because this is an issue with the terminal emulator you use to run commands, there is nothing we can really do.

As for the `Terminate batch job (Y/N)`

**Comment by TahaTesser** [comment] 2020-10-14 13:05
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

**Closed by TahaTesser** 2020-10-14 13:05 UTC
Labels: in triage
