### ISSUE TITLE
Exception caught by rendering library ===================================================== The following assertion was thrown during paint():

### ISSUE THREAD

**Issue by Manishkumar76** [flutter/flutter#129975] opened 2023-07-05 02:37 UTC
Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.

**Comment by darshankawar** [comment] 2023-07-05 07:56
@Manishkumar76 
Although the error says to file an issue, but in order to properly address the root-cause of the error, we need minimal reproducible code sample along with steps to replicate so that we can make the issue actionable.

Closing for now, since no information is provided. If you have concrete details, please use new issue template and fill out requested details so that we can properly analyze the issue.

**Closed by darshankawar** 2023-07-05 07:56 UTC
Labels: in triage
