### ISSUE TITLE
1️⃣,3️⃣..etc emojis not rendering if placed at beginning of text

### ISSUE THREAD

**Issue by rahul-2501** [flutter/flutter#114149] opened 2022-10-27 11:31 UTC
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. type 1️⃣ in the textfield, we can see emoji not rendered.
3. But enter any emoji in the beginning followed by this emoji, It renders as expected

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});
  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: const <Widget>[
            TextField(),
          ],
        ),
      ),
    );
  }
}

```

</details>

<details>
  <summary>Logs</summary>

```
No issues found! (ran in 1.6s)

```

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.1, on macOS 12.2.1 21D62 darwin-arm, locale en-IN)
[!] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] IntelliJ IDEA Community Edition (version 2022.1)
[✓] VS Code (version 1.72.0)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

! Doctor found issues in 1 category.


```

</details>

**Comment by rahul-2501** [comment] 2022-10-27 11:33
![emoji_bug](https://user-images.githubusercontent.com/38251726/198273706-bd6ef30c-1708-462b-a5c1-227314757bb8.gif)

**Comment by rahul-2501** [comment] 2022-10-27 11:41
@zanderso @LongCatIsLooong can you help? Thanks.

**Comment by exaby73** [comment] 2022-10-27 14:50
Hello @rahul-2501. Please refrain from mentioning people in issues. I can reproduce this issue on stable but it seems to be fixed in master. Since it's already fixed, I am closing this issue. If you disagree, please comment and I can reopen it. Thank you.

**Closed by exaby73** 2022-10-27 14:50 UTC
Labels: in triage
