### ISSUE TITLE
ideviceinfo returned an error: ERROR: Could not connect to lockdownd, error code -17

### ISSUE THREAD

**Issue by sunnyshingala** [flutter/flutter#37236] opened 2019-07-30 11:51 UTC
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```

```
```

**Comment by sunnyshingala** [comment] 2019-07-30 11:52
#0      IMobileDevice.getInfoForDevice
(package:flutter_tools/src/ios/mac.dart:88:9)
<asynchronous suspension>
#1      IOSDevice.getAttachedDevices
(package:flutter_tools/src/ios/devices.dart:162:55)
<asynchronous suspension>
#2      IOSDevices.pollingGetDevices
(package:flutter_tools/src/ios/devices.dart:111:57)
#3      PollingDeviceDiscovery.devices
(package:flutter_tools/src/device.dart:223:52)
<asynchronous suspension>
#4      DeviceManager.getAllConnectedDevices
(package:flutter_tools/src/device.dart:151:46)
<asynchronous suspension>
#5      DeviceValidator.validate (package:flutter_tools/src/doctor.dart:743:54)
<asynchronous suspension>
#6      Doctor.startValidatorTasks
(package:flutter_tools/src/doctor.dart:152:52)
#7      Doctor.diagnose (package:flutter_tools/src/doctor.dart:223:41)
#8      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
#9      Doctor.diagnose (package:flutter_tools/src/doctor.dart:213:24)
#10     DoctorCommand.runCommand
(package:flutter_tools/src/commands/doctor.dart:48:39)
#11     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
#12     DoctorCommand.runCommand
(package:flutter_tools/src/commands/doctor.dart:34:42)
#13     FlutterCommand.verifyThenRunCommand
(package:flutter_tools/src/runner/flutter_command.dart:478:18)
#14     _asyncThenWrapperHelper.<anonymous closure>
(dart:async-patch/async_patch.dart:77:64)
#15     _rootRunUnary (dart:async/zone.dart:1132:38)
#16     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#17     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#18     Future._propagateToListeners.handleValueCallback
(dart:async/future_impl.dart:639:45)
#19     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#20     Future._complete (dart:async/future_impl.dart:473:7)
#21     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#22     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:28:18)
#23     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:294:13)
#24     Cache.updateAll (package:flutter_tools/src/cache.dart)
#25     _asyncThenWrapperHelper.<anonymous closure>
(dart:async-patch/async_patch.dart:77:64)
#26     _rootRunUnary (dart:async/zone.dart:1132:38)
#27     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#28     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#29     Future._propagateToListeners.handleValueCallback
(dart:async/future_impl.dart:639:45)
#30     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#31     Future._complete (dart:async/future_impl.dart:473:7)
#32     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#33     _AsyncAwaitCompleter.complete.<anonymous closure>
(dart:async-patch/async_patch.dart:33:20)
#34     _rootRun (dart:async/zone.dart:1120:38)
#35     _CustomZone.run (dart:async/zone.dart:1021:19)
#36     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#37     _CustomZone.bindCallbackGuarded.<anonymous closure>
(dart:async/zone.dart:963:23)
#38     _rootRun (dart:async/zone.dart:1124:13)
#39     _CustomZone.run (dart:async/zone.dart:1021:19)
#40     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#41     _CustomZone.bindCallbackGuarded.<anonymous closure>
(dart:async/zone.dart:963:23)
#42     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#43     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#44     _runPendingImmediateCallback
(dart:isolate-patch/isolate_patch.dart:116:13)
#45     _RawReceivePortImpl._handleMessage
(dart:isolate-patch/isolate_patch.dart:173:5)

**Comment by sunnyshingala** [comment] 2019-07-30 11:54
ideviceinfo returned an error:
ERROR: Could not connect to lockdownd, error code -17


#0      IMobileDevice.getInfoForDevice
(package:flutter_tools/src/ios/mac.dart:88:9)
<asynchronous suspension>
#1      IOSDevice.getAttachedDevices
(package:flutter_tools/src/ios/devices.dart:162:55)
<asynchronous suspension>
#2      IOSDevices.pollingGetDevices
(package:flutter_tools/src/ios/devices.dart:111:57)
#3      PollingDeviceDiscovery.devices
(package:flutter_tools/src/device.dart:223:52)
<asynchronous suspension>
#4      DeviceManager.getAllConnectedDevices
(package:flutter_tools/src/device.dart:151:46)
<asynchronous suspension>
#5      DeviceValidator.validate (package:flutter_tools/src/doctor.dart:743:54)
<asynchronous suspension>
#6      Doctor.startValidatorTasks
(package:flutter_tools/src/doctor.dart:152:52)
#7      Doctor.diagnose (package:flutter_tools/src/doctor.dart:223:41)
#8      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
#9      Doctor.diagnose (package:flutter_tools/src/doctor.dart:213:24)
#10     DoctorCommand.runCommand
(package:flutter_tools/src/commands/doctor.dart:48:39)
#11     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
#12     DoctorCommand.runCommand
(package:flutter_tools/src/commands/doctor.dart:34:42)
#13     FlutterCommand.verifyThenRunCommand
(package:flutter_tools/src/runner/flutter_command.dart:478:18)
#14     _asyncThenWrapperHelper.<anonymous closure>
(dart:async-patch/async_patch.dart:77:64)
#15     _rootRunUnary (dart:async/zone.dart:1132:38)
#16     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#17     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#18     Future._propagateToListeners.handleValueCallback
(dart:async/future_impl.dart:639:45)
#19     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#20     Future._complete (dart:async/future_impl.dart:473:7)
#21     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#22     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:28:18)
#23     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:294:13)
#24     Cache.updateAll (package:flutter_tools/src/cache.dart)
#25     _asyncThenWrapperHelper.<anonymous closure>
(dart:async-patch/async_patch.dart:77:64)
#26     _rootRunUnary (dart:async/zone.dart:1132:38)
#27     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#28     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#29     Future._propagateToListeners.handleValueCallback
(dart:async/future_impl.dart:639:45)
#30     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#31     Future._complete (dart:async/future_impl.dart:473:7)
#32     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#33     _AsyncAwaitCompleter.complete.<anonymous closure>
(dart:async-patch/async_patch.dart:33:20)
#34     _rootRun (dart:async/zone.dart:1120:38)
#35     _CustomZone.run (dart:async/zone.dart:1021:19)
#36     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#37     _CustomZone.bindCallbackGuarded.<anonymous closure>
(dart:async/zone.dart:963:23)
#38     _rootRun (dart:async/zone.dart:1124:13)
#39     _CustomZone.run (dart:async/zone.dart:1021:19)
#40     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#41     _CustomZone.bindCallbackGuarded.<anonymous closure>
(dart:async/zone.dart:963:23)
#42     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#43     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#44     _runPendingImmediateCallback
(dart:isolate-patch/isolate_patch.dart:116:13)
#45     _RawReceivePortImpl._handleMessage
(dart:isolate-patch/isolate_patch.dart:173:5)

**Comment by stuartmorgan** [comment] 2019-07-30 12:50
Duplicate of #36789

**Closed by stuartmorgan** 2019-07-30 12:50 UTC

**Comment by sunnyshingala** [comment] 2019-07-30 13:25
I've resolved this issue. I have update my mac version.

**Comment by mab66** [comment] 2021-07-21 12:56
I had to authorize the computer to access to the device (iPhone) and it solves the issue
