### ISSUE TITLE
FlutterView.LayoutParam x = 0 is at the right most edge of the screen instead of left

### ISSUE THREAD

**Issue by tolotrasamuel** [flutter/flutter#122558] opened 2023-03-13 22:10 UTC
I was able to reproduce this on Flutter version 3.3.4 and 3.7.2

## Steps to Reproduce

I am minimum reproducible repo https://github.com/tolotrasamuel/bug_overlay_flutter

1. Execute `flutter run` on the repo
2. Tap on counter button
3. Drag FlutterView overlay left to right and see the inverted behavior of x position.

**Expected results:** 

According to Android specs, x = 0 positions should be to the left most edge of the screen  https://stackoverflow.com/questions/11483345/how-do-android-screen-coordinates-work

**Actual results:** 
`            WindowManager.LayoutParams params = (WindowManager.LayoutParams) flutterView.getLayoutParams();`
if you print `params` it will show zero when the view overlay is at the right most side of the screen.

<details>

I initially thought this is a bug with the plugin I was using but I went down to the Android code level by the plugin and realized that the `flutterView.getLayoutParams();` is not what is expected
<summary>Code sample</summary>

```dart

 @Override
    public boolean onTouch(View view, MotionEvent event) {
        if (windowManager != null && WindowSetup.enableDrag) {
            WindowManager.LayoutParams params = (WindowManager.LayoutParams) flutterView.getLayoutParams();
            switch (event.getAction()) {
                case MotionEvent.ACTION_DOWN:
                    dragging = false;
                    lastX = event.getRawX();
                    lastY = event.getRawY();
                    break;
                case MotionEvent.ACTION_MOVE:
                    float dx = event.getRawX() - lastX;
                    float dy = event.getRawY() - lastY;
                    if (!dragging && dx * dx + dy * dy < 25) {
                        return false;
                    }
                    lastX = event.getRawX();
                    lastY = event.getRawY();
                    int xx = params.x - (int) dx;
                    int yy = params.y + (int) dy;
                    Log.d("FlutterOverlayWindow", "onTouch: " + xx + " " + yy +" params.x: " + params.x + " params.y: " + params.y + " dx: " + dx + " dy: " + dy + " lastX: " + lastX + " lastY: " + lastY + " event.getRawX(): " + event.getRawX() + " event.getRawY(): " + event.getRawY());
                    params.x = xx;
                    params.y = yy;
                    windowManager.updateViewLayout(flutterView, params);
                    dragging = true;
                    break;
                case MotionEvent.ACTION_UP:
                case MotionEvent.ACTION_CANCEL:
                    lastYPosition = params.y;
                    if (WindowSetup.positionGravity != "none") {
                        windowManager.updateViewLayout(flutterView, params);
                        mTrayTimerTask = new TrayAnimationTimerTask();
                        mTrayAnimationTimer = new Timer();
                        mTrayAnimationTimer.schedule(mTrayTimerTask, 0, 25);
                    }
                    return dragging;
                default:
                    return false;
            }
            return false;
        }
        return false;
    }

```

</details>

<details>

  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by huycozy** [comment] 2023-03-14 08:50
Hi @tolotrasamuel 
From what I can see, the issue is related to a 3rd party plugin rather than to Flutter itself. I have seen your PR and issue at that repository as well. Please follow up on them for further updates. 

Closing, as this isn't an issue with Flutter itself.  If you disagree, please write in the comments, providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`, a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that does not use 3rd party plugins and I will reopen it.

Thank you!

**Closed by huycozy** 2023-03-14 08:50 UTC
Labels: in triage
