### ISSUE TITLE
Camera Exception is thrown on stopVideoRecording() 

### ISSUE THREAD

**Issue by tarang1998** [flutter/flutter#72994] opened 2020-12-27 07:16 UTC
In an application which I am currently working, we are supposed to record a video for an hour. We are capturing the video in 2 min window chunks in order to perform certain operations on the video chunks after recording them.

The consecutive startVideoRecording() and stopVideoRecording() works perfectly in most of the cases but in some devices it throws a Camera Exception

We are using the camera plugin ^0.5.8+11.
---------------------------------------------------------- 

Case 1:

1> Successfully captured multiple video chunks by using startVideoRecording() and stopVideoRecording().

2>After recording multiple chunks while capturing another chunk by using StartVideoRecording(), it doesn't throw an exception

3>Exception is thrown while stopping the video : CameraException(error, Attempt to invoke virtual method 'void android.media.MediaRecorder.stop()' on a null object reference)

4>Exception thrown while again starting the video Recording : CameraException(error, Attempt to invoke virtual method 'android.hardware.camera2.CaptureRequest$Builder android.hardware.camera2.CameraDevice.createCaptureRequest(int)' on a null object reference) 

5>Exception thrown while stopping the video :  CameraException(No video is recording, stopVideoRecording was called when no video is recording.)

And the pattern continous

-------------------------------------------------------

Case 2:

Exception thrown while stopping the video : CameraException(videoRecordingFailed, Illegal state encountered in camera service.)

Exception thrown while again starting the video Recording : CameraException(error, Attempt to invoke virtual method 'android.hardware.camera2.CaptureRequest$Builder android.hardware.camera2.CameraDevice.createCaptureRequest(int)' on a null object reference)

------------------------------------------------------

Case 3:

Exception thrown while stopping the video : CameraException(videoRecordingFailed, The camera device has encountered a serious error)

Exception thrown while again starting the video Recording : CameraException(error, Attempt to invoke virtual method 'android.hardware.camera2.CaptureRequest$Builder android.hardware.camera2.CameraDevice.createCaptureRequest(int)' on a null object reference)

It has been very difficult to reproduce this error as it occurs only in some devices and works perfectly in the rest of them.

Devices in which this error was encountered

Redmi Note 3,
vivo 1815
vivo 1601
vivo 1609
SM-J701F
vivo V3Max
Mi A1
SM-M105F
A37f
MotoG3
CPH1701
Redmi Y1
SM-G610F
vivo 1723
CPH1725
Moto G (4)

My question is could reinitializing the camera controller after encountering an error after stopVideoRecording() solve my problem. Coudn't test this thing out as the bug is really hard to reproduce.

**Comment by iapicca** [comment] 2020-12-27 08:44
@tarang1998 
the current version of [camera](https://pub.dev/packages/camera/install) is **_0.6.2+1_**
please try upgrading the package

if the issue persist 
please provide your `flutter doctor -v` and a minimal reproducible code sample or,
if the issue is in production your `flutter run --release -v` on one of the impacted devices

**Comment by tarang1998** [comment] 2020-12-27 11:53
@iapicca  
Camera version 0.6.2+1 have some changes.
- The startVideoRecording method no longer accepts the filePath. Instead the recorded video is now returned as a XFile instance when the stopVideoRecording method completes;
- The stopVideoRecording method now returns the captured video when it completes;

I don't want to change the structure of my code due to this. Ill keep this as the last option. 
I went through the source code for the version 0.5.8+11, 0.5.8 +17, 0.6.2+1.
There weren't any significant changes in them that were related to the startVideoRecording() and stopVideoRecording() functionality.

**Comment by tarang1998** [comment] 2020-12-27 11:58
All these issues I guess are related to the same problem

https://github.com/flutter/flutter/issues/23039
https://github.com/flutter/flutter/issues/18138
https://github.com/flutter/flutter/issues/31414
https://github.com/googlearchive/android-Camera2Video/issues/46
https://github.com/googlearchive/android-Camera2Video/issues/37

The solution has been provided in:

https://github.com/flutter/flutter/issues/31225
https://github.com/Petka17/plugins/pull/1
https://stackoverflow.com/questions/27907090/android-camera-2-api/32621903#32621903

I havent tested any of them out yet, hope they work !

**Comment by iapicca** [comment] 2020-12-27 12:04
> Camera version 0.6.2+1 have some changes.
> 
> * The startVideoRecording method no longer accepts the filePath. Instead the recorded video is now returned as a XFile instance when the stopVideoRecording method completes;
> * The stopVideoRecording method now returns the captured video when it completes;
> 
> I don't want to change the structure of my code due to this. Ill keep this as the last option.
> I went through the source code for the version 0.5.8+11, 0.5.8 +17, 0.6.2+1.

any bug fixing would inevitably occur on new releases of the plugin,
so I'm not sure such an issue could ever be solved sticking to a legacy version of said plugin

regardless for the issue to be workable needs to be reproducible
can you provide a **minimal reproducible code sample** (not snippet for production, or else)
with the latest version of the plugin and representative of the issue you are describing

**Comment by TahaTesser** [comment] 2020-12-28 11:45
Hi @tarang1998 
As @iapicca mentioned, any bug fixing would inevitably occur on the new version of the plugin. To better address  the issue we need a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) (not production code/snippet).
Thank you

**Comment by mvanbeusekom** [comment] 2021-01-07 09:54
@tarang1998 this exact issue has been addressed and resolved in version 0.6.4+3 of the Camera plugin (the PR adding the fix can be found [here](https://github.com/flutter/plugins/pull/3383)).

This does mean though that you will have to upgrade to this new version. Alternatively you could fork the camera plugin and add the fix yourself by replacing the `stopVideoRecording` method in the `Camera.java` file with the following:

```java
  public void stopVideoRecording(@NonNull final Result result) {
    if (!recordingVideo) {
      result.success(null);
      return;
    }

    try {
      recordingVideo = false;

      try {
        cameraCaptureSession.abortCaptures();
        mediaRecorder.stop();
      } catch (CameraAccessException | IllegalStateException e) {
        // Ignore exceptions and try to continue (changes are camera session already aborted capture)
      }

      mediaRecorder.reset();
      startPreview();
      result.success(null);
    } catch (CameraAccessException | IllegalStateException e) {
      result.error("videoRecordingFailed", e.getMessage(), null);
    }
  }
```

Note that this is not the recommended way to go and you will lose the benefit of all the bug fixes we have been doing recently. But it could get be a valid solution that will give you some space in which you can restructure your application to adopt the new version of the camera plugin.

**Comment by tarang1998** [comment] 2021-01-07 14:45
@mvanbeusekom  Thank you for your reply. I have been trying to upgrade the camera plugin, but I was facing some issues with it. I'll try it out again with the version 0.6.4+3

**Comment by TahaTesser** [comment] 2021-01-08 06:56
Hi @tarang1998 
Please do and let us know
Thank you

**Comment by pedromassangocode** [comment] 2021-01-29 13:27
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2021-01-29 13:27 UTC
Labels: in triage, waiting for customer response

**Comment by naveenreddyin** [comment] 2021-02-09 12:23
Hi guys,
I got the same error now on 0.7.0+1 and also on 0.7.0+2 version. 
`Exception has occurred.
PlatformException (PlatformException(error, stop failed., null, java.lang.RuntimeException: stop failed.
	at android.media.MediaRecorder.stop(Native Method)
	at io.flutter.plugins.camera.Camera.stopVideoRecording(Camera.java:645)
	at io.flutter.plugins.camera.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:120)
	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:335)
	at android.os.Looper.loop(Looper.java:183)
	at android.app.ActivityThread.main(ActivityThread.java:7656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
))`

**Comment by AbhishekDoshi26** [comment] 2021-03-26 05:32
@pedromassango Getting same issue in camera: ^0.8.0

**Comment by pedromassangocode** [comment] 2021-03-26 12:19
> Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
> All system setups can be slightly different, so it's always better to open new issues and reference related issues

**Comment by AbhishekDoshi26** [comment] 2021-03-26 12:24
@pedromassango solved the issue using proguard. Also have created a PR which includes instruction and content for the file:
https://github.com/flutter/plugins/pull/3759

**Comment by tarang1998** [comment] 2021-03-29 22:08
@pedromassango @TahaTesser @mvanbeusekom @iapicca 
Facing a similar problem with camera ^0.8.1
Raised a new issue for it 

https://github.com/flutter/flutter/issues/79306
Pls do have a look
Thank u :)

**Comment by pandazed** [comment] 2021-05-29 12:12
`<uses-feature android:name="android.hardware.camera2" android:required="false" />`
in `AndroidMainfest.xml` helped me
