### ISSUE TITLE
[image_picker] pickImage from ImageSource.camera orientation bug

### ISSUE THREAD

**Issue by acidjazz** [flutter/flutter#19458] opened 2018-07-17 09:13 UTC
This issue is confirmed with a Pixel 2 XL, a Samsung S5, and a Note 2

This is not an issue with most apple devices, tested with an iPhone 6, 7, or 10

* Launch ImagePicker.pickImage(source: ImageSource.camera) 
* Rotate your phone and take a photo in landscape mode

Displaying the result in flutter shows it orientated correctly, but when sending this to a server / s3 bucket / firebase resource the photo is not rotated.

**Comment by acidjazz** [comment] 2018-07-17 09:40
thanks @zoechi that makes a lot of sense, throwing away the EXIF data and then a "fix" to properly show it in flutter definitely makes this related.  any progress on ways to keep our EXIF data @goderbauer ? or actually just saving the image w/ the correct orientation?

**Comment by AnassKartit** [comment] 2018-07-25 09:43
I am having the same issue but on Android device Lenovo P2, after taking sometimes it is in the original direction sometimes it is rotated.

**Comment by eseidelGoogle** [comment] 2018-11-26 17:17
I've written notes about how to add exif on iOS/Android to: https://github.com/flutter/flutter/issues/10533#issuecomment-441719073 . I suspect all of these exif bugs are the same root cause and easy to fix.

**Comment by zoechi** [comment] 2018-11-26 17:34
A PR that seems to address this https://github.com/flutter/plugins/pull/866 (at least for iOS)

**Comment by callumclift** [comment] 2019-01-28 18:45
Is there a potential fix lined up for this? everything seems to work fine on iOS but all of my images are rotated 90 degrees on the android devices i'm using.

**Comment by quetool** [comment] 2019-02-04 14:22
Hi, is there any solution to this? On iOS is working right, the issue is on Android

**Comment by quetool** [comment] 2019-02-04 16:55
@callumclift that's great, thanks!

**Comment by quetool** [comment] 2019-02-04 17:05
@callumclift does this plugin support androidx?

**Comment by callumclift** [comment] 2019-02-04 17:10
@quetool i'm not sure to be honest, i think my app is using AndroidX and other packages that have been upgraded to AndroidX are still working in it so my guess is a yes

**Comment by quetool** [comment] 2019-02-04 17:12
I think not, I am having too many errors relatives to android.support.v4. Anyway, this is not the place, I will investigate, thanks

**Comment by mklim** [comment] 2019-02-21 22:09
So far I haven't been able to get problem to happen, can any of you post a simplified case where this triggers?

What I've tried so far is to edit the example app to save pictures to external storage.

```dart
// example/main.dart:190
Padding(
  padding: const EdgeInsets.only(top: 16.0),
  child: FloatingActionButton(
      backgroundColor: Colors.green,
      onPressed: () async {
        final File image = await _imageFile;
        if (image == null) {
          return;
        }
        // https://github.com/google/error-prone/blob/master/docs/bugpattern/android/HardCodedSdCardPath.md
        const String kHardcodedPathJustForDebugging = '/sdcard/Pictures/';
        final File output = File(kHardcodedPathJustForDebugging + image.path.split('/').last);
        output.writeAsBytesSync(await image.readAsBytes());
        print('Saved image to ' + output.path);
    },
    child: const Icon(Icons.save),
  ),
),
```

```xml
<!-- example/android/app/src/AndroidManifest.xml:6 -->
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
```

Then I'm using `adb pull /sdcard/Pictures/` examine the images on my computer. So far pictures taken with all camera rotations and both front and back camera look right to me, but I'm guessing I'm missing something here in how to hit the bug.

If this should be enough I can go back and keep testing with more Android devices and see if I can find it that way.

**Comment by collinjackson** [comment] 2019-03-07 19:12
It sounds like we're having trouble getting this to reproduce this. Since #20431 relates to some EXIF stuff that was fixed, it's possible that this issue has been fixed already. If anyone wants to post a repro case we can investigate further.

**Comment by quetool** [comment] 2019-03-07 19:54
I am currently using flutter_exif_rotation to work around this.

```
ImageSource imageSource = ImageSource.values[source];
File image = await ImagePicker.pickImage(source: imageSource);
if (Platform.isAndroid) {
  image = await FlutterExifRotation.rotateImage(path: image.path);
}
```

**Comment by collinjackson** [comment] 2019-03-14 18:08
@quetool can you confirm how you were able to reproduce the image_picker issue that caused you to want to use FlutterExifRotation? I think we'd like to have the EXIF stuff work out of the box without the need for external plugins. It would great if you could upload a photograph that you're experiencing this issue with, confirm the device you're using, and so on.

**Comment by quetool** [comment] 2019-03-14 18:21
Hi @collinjackson, I don't understand what you need.
Like I said before, in Android devices the image, after being shooted by the camera, was showing rotated by 90 degrees with the front camera and -90 with back camera.

This was my code before FlutterExifRotation
```
getImage(int source) async {
  ImageSource imageSource = ImageSource.values[source];
  File image = await ImagePicker.pickImage(source: imageSource);
  sinkPIFP(image);
}
```

And this after adding it
```
getImage(int source) async {
  ImageSource imageSource = ImageSource.values[source];
  File image = await ImagePicker.pickImage(source: imageSource);
  if (Platform.isAndroid) {
    image = await FlutterExifRotation.rotateImage(path: image.path);
  }
  sinkPIFP(image);
}
```

I just added
```
  if (Platform.isAndroid) {
    image = await FlutterExifRotation.rotateImage(path: image.path);
  }
```

because like I said, the issue is happening on android device only
I hope it helps!

**Comment by lifenautjoe** [comment] 2019-03-19 16:56
It's been almost a year since this, any chances of this hitting prod? 🙏

**Comment by Hixie** [comment] 2019-03-19 23:27
Is the problem "merely" that the server isn't honouring the EXIF data, maybe?

**Comment by quetool** [comment] 2019-03-20 01:48
@Hixie What server? Issue come out when you take a picture with the camera

**Comment by lifenautjoe** [comment] 2019-03-20 15:03
Nope, it's all on device @Hixie. Btw the https://pub.dartlang.org/packages/flutter_exif_rotation plugin does not work with AndroidX. So no way to fix rotated images right now 🙃

**Comment by Hixie** [comment] 2019-03-23 00:30
This bug is about the image showing at the wrong rotation when passed from Flutter to a server (see the first comment in this bug).

If you are seeing this issue with no server involved, please file a separate bug. Thanks!

**Comment by lifenautjoe** [comment] 2019-03-28 19:29
:-( this is stil an issue...

**Comment by lifenautjoe** [comment] 2019-03-28 19:30
Oh wait, my bad. My case doesn’t involve a server. Sorry!

**Comment by masewo** [comment] 2019-04-16 20:49
Happens in my app as well when sending image to a S3. Did you open a new ticket?

**Comment by NGhebreial** [comment] 2019-05-20 07:48
I made a plugin to fix this, hoping it's useful for you:
[https://pub.dev/packages/flutter_exif_rotation](https://pub.dev/packages/flutter_exif_rotation)

**Comment by quetool** [comment] 2019-05-20 12:26
@NGhebreial I am currently using it, many thanks!

**Comment by c0h1b4** [comment] 2019-05-25 12:40
No it is no use because I have this issue on iOS.

**Comment by decentcamper** [comment] 2019-06-25 01:54
This is definitely an issue. Is there any workaround for this? I wonder how are the things working for other users since it is such a critical piece of functionality.

**Comment by NGhebreial** [comment] 2019-06-25 07:13
> No it is no use because I have this issue on iOS.

Yeah, I don't have access to a macOS so I can't develop the plugin for iOS as well...
as @decentcamper said, hope they fix it

**Comment by c0h1b4** [comment] 2019-06-25 10:10
> This is definitely an issue. Is there any workaround for this? I wonder how are the things working for other users since it is such a critical piece of functionality.

There are several "old" bugs like this one that looks like they will never be solved and are being closed by bots. This is why the total of bugs on the project are sky rocketing. 

I fear for the future of the Flutter framework.

**Comment by eseidelGoogle** [comment] 2019-06-25 16:35
The problem with this bug was that we were never able to get the bug as reported to reproduce for one of the engineers working to fix it. :)

In that state, we had to simply spend our time on other bugs instead.

If someone is still experiencing issues with EXIF (which I certainly could believe), please file a new bug with clear reproduction steps, including the Dart code used to see the issue as well as the devices on which you've seen the problem.

https://github.com/flutter/flutter/issues/new

With such information someone (at Google or otherwise) should be able to quickly reproduce and solve the underlying issue. Thank you!

**Comment by mehmetf** [comment] 2019-07-17 22:10
*Technically* image_picker isn't buggy in the sense that it is including all the data a viewer needs to display the image properly.

The problem is that some viewers are ignoring the `orientation` directive in the EXIF assuming that it is 0.

@mklim Pulling the images to desktop won't reproduce this bug since the desktop viewers (correctly) interpret the orientation attribute. However, you can easily reproduce this in the sample app that ships with `image_picker` today. Taking a portrait picture with this sample app will result in the picture being displayed in landscape mode.

We now need to decide whether this is a bug in image_picker. To fix it, image_picker needs to normalize the photo to 0 orientation and I am not too sure that's image_picker's responsibility.

**Comment by mehmetf** [comment] 2019-07-17 22:12
I would say the bug is in Image() widget which is currently ignoring `orientation`.

**Comment by kroikie** [comment] 2019-10-13 19:01
@acidjazz

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/752. Any further collaboration will be done there.

**Comment by iapicca** [comment] 2019-11-08 13:12
Hi all,
I'm quite sure that this issue shouldn't have been transferred 
to [FlutterFire](https://github.com/FirebaseExtended/flutterfire),
I'm re-opening it.


@acidjazz 
if you are still experiencing the problem with the latest stable version
please provide your update `flutter doctor -v` 
together with a a minimal code sample to reproduce the problem
thank you

**Comment by Hixie** [comment] 2019-11-13 00:21
It wasn't transferred, it was closed due to no response back in March.

Please open new bugs if you still see this.

**Closed by Hixie** 2019-11-13 00:21 UTC
Labels: customer: crowd, p: first party, p: image_picker, plugin, severe: customer critical, waiting for customer response
