### ISSUE TITLE
 SocketException: Send failed (OS Error: No route to host, errno = 65) during flutter run.

### ISSUE THREAD

**Issue by valitakacs** [flutter/flutter#157347] opened 2024-10-22 14:11 UTC
### Steps to reproduce

**Steps to reproduce:** 
1.Run the command:flutter run --machine --start-paused -d xxxxxxxxxxxxxx --devtools-server-address http://127.0.0.1:9100/ --target lib/main_prod.dart --flavor prod
2. Attempt to deploy on a real iOS device.
3. The error occurs during the device deployment phase.

### Expected results

The app should launch successfully on the real iOS device, similar to how it runs on the simulator.

### Actual results

Flutter crash report.
Please report a bug at https://github.com/flutter/flutter/issues.

## command

flutter run --machine --start-paused -d 00008130-001118A134C1001C --devtools-server-address http://127.0.0.1:9100/ --target /Users/takacsvalentin/Documents/Work/swipework-app-main/swipe_work_ai/lib/main_prod.dart --flavor prod

## exception

SocketException: SocketException: Send failed (OS Error: No route to host, errno = 65), address = 0.0.0.0, port = 5353

```
#0      _NativeSocket.send (dart:io-patch/socket_patch.dart:1275:34)
#1      _RawDatagramSocket.send (dart:io-patch/socket_patch.dart:2590:15)
#2      MDnsClient.lookup (package:multicast_dns/multicast_dns.dart:219:22)
#3      MDnsVmServiceDiscovery._pollingVmService (package:flutter_tools/src/mdns_discovery.dart:232:66)
<asynchronous suspension>
#4      MDnsVmServiceDiscovery.firstMatchingVmService (package:flutter_tools/src/mdns_discovery.dart:188:56)
<asynchronous suspension>
#5      MDnsVmServiceDiscovery.getVMServiceUriForLaunch (package:flutter_tools/src/mdns_discovery.dart:433:50)
<asynchronous suspension>
#6      Future.any.onValue (dart:async/future.dart:628:5)
<asynchronous suspension>
```

## flutter doctor

```
[✓] Flutter (Channel stable, 3.24.3, on macOS 15.0.1 24A348 darwin-arm64, locale en-RO)
    • Flutter version 3.24.3 on channel stable at /Users/takacsvalentin/Documents/Dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2663184aa7 (6 weeks ago), 2024-09-11 16:27:48 -0500
    • Engine revision 36335019a8
    • Dart version 3.5.3
    • DevTools version 2.37.3

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/takacsvalentin/Library/Android/sdk
    • Platform android-34, build-tools 33.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16A242d
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.94.2)
    • VS Code at /Users/takacsvalentin/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.98.0

[✓] Connected device (5 available)
    • Vali Takacs (2) (mobile)        • 00008130-001118A134C1001C            • ios            • iOS 18.0.1 22A3370
    • iPhone 16 Pro (mobile)          • 3016F50B-2A0E-47E9-AB92-41E0C079F06E • ios            • com.apple.CoreSimulator.SimRuntime.iOS-18-0 (simulator)
    • macOS (desktop)                 • macos                                • darwin-arm64   • macOS 15.0.1 24A348 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad                • darwin         • macOS 15.0.1 24A348 darwin-arm64
    • Chrome (web)                    • chrome                               • web-javascript • Google Chrome 129.0.6668.103

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
Launching lib/main_prod.dart on Vali Takacs (2) in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: xxxxxxxxxx
Xcode build done.                                           202.3s
You may be prompted to give access to control Xcode. Flutter uses Xcode to run your app. If access is not allowed, you can change this through your Settings > Privacy & Security > Automation.

Oops; flutter has exited unexpectedly: "SocketException: Send failed (OS Error: No route to host, errno = 65), address = 0.0.0.0, port = 5353".
A crash report has been written to /Users/takacsvalentin/Documents/Work/swipework-app-main/swipe_work_ai/flutter_06.log
This crash may already be reported. Check GitHub for similar crashes.
https://github.com/flutter/flutter/issues?q=is%3Aissue+SocketException%3A+Send+failed+%28OS+Error%3A+No+route+to+host%2C+errno+%3D+65%29%2C+address+%3D+0.0.0.0%2C+port+%3D+5353

To report your crash to the Flutter team, first read the guide to filing a bug.
https://flutter.dev/to/report-bugs

Create a new GitHub issue by pasting this link into your browser and completing the issue template. Thank you!
https://github.com/flutter/flutter/issues/new?title=%5Btool_crash%5D+SocketException%3A+Send+failed%2C+OS+Error%3A+No+route+to+host%2C+errno+%3D+65&body=%23%23+Command%0A%60%60%60sh%0Aflutter+run+--machine+--start-paused+-d+00008130-001118A134C1001C+--devtools-server-address+http%3A%2F%2F127.0.0.1%3A9100%2F+--target+%2FUsers%2Ftakacsvalentin%2FDocuments%2FWork%2Fswipework-app-main%2Fswipe_work_ai%2Flib%2Fmain_prod.dart+--flavor+prod%0A%60%60%60%0A%0A%23%23+Steps+to+Reproduce%0A1.+...%0A2.+...%0A3.+...%0A%0A%23%23+Logs%0ASocketException%3A+Send+failed%2C+OS+Error%3A+No+route+to+host%2C+errno+%3D+65%0A%60%60%60console%0A%230++++++_NativeSocket.send+%28dart%3Aio-patch%2Fsocket_patch.dart%3A1275%3A34%29%0A%231++++++_RawDatagramSocket.send+%28dart%3Aio-patch%2Fsocket_patch.dart%3A2590%3A15%29%0A%232++++++MDnsClient.lookup+%28package%3Amulticast_dns%2Fmulticast_dns.dart%3A219%3A22%29%0A%233++++++MDnsVmServiceDiscovery._pollingVmService+%28package%3Aflutter_tools%2Fsrc%2Fmdns_discovery.dart%3A232%3A66%29%0A%3Casynchronous+suspension%3E%0A%234++++++MDnsVmServiceDiscovery.firstMatchingVmService+%28package%3Aflutter_tools%2Fsrc%2Fmdns_discovery.dart%3A188%3A56%29%0A%3Casynchronous+suspension%3E%0A%235++++++MDnsVmServiceDiscovery.getVMServiceUriForLaunch+%28package%3Aflutter_tools%2Fsrc%2Fmdns_discovery.dart%3A433%3A50%29%0A%3Casynchronous+suspension%3E%0A%236++++++Future.any.onValue+%28dart%3Aasync%2Ffuture.dart%3A628%3A5%29%0A%3Casynchronous+suspension%3E%0A%60%60%60%0A%60%60%60console%0A%5B%E2%9C%93%5D+Flutter+%28Channel+stable%2C+3.24.3%2C+on+macOS+15.0.1+24A348+darwin-arm64%2C+locale+en-RO%29%0A++++%E2%80%A2+Flutter+version+3.24.3+on+channel+stable+at+%2FUsers%2Ftakacsvalentin%2FDocuments%2FDev%2Fflutter%0A++++%E2%80%A2+Upstream+repository+https%3A%2F%2Fgithub.com%2Fflutter%2Fflutter.git%0A++++%E2%80%A2+Framework+revision+2663184aa7+%286+weeks+ago%29%2C+2024-09-11+16%3A27%3A48+-0500%0A++++%E2%80%A2+Engine+revision+36335019a8%0A++++%E2%80%A2+Dart+version+3.5.3%0A++++%E2%80%A2+DevTools+version+2.37.3%0A%0A%5B%E2%9C%93%5D+Android+toolchain+-+develop+for+Android+devices+%28Android+SDK+version+33.0.1%29%0A++++%E2%80%A2+Android+SDK+at+%2FUsers%2Ftakacsvalentin%2FLibrary%2FAndroid%2Fsdk%0A++++%E2%80%A2+Platform+android-34%2C+build-tools+33.0.1%0A++++%E2%80%A2+Java+binary+at%3A+%2FApplications%2FAndroid+Studio.app%2FContents%2Fjbr%2FContents%2FHome%2Fbin%2Fjava%0A++++%E2%80%A2+Java+version+OpenJDK+Runtime+Environment+%28build+11.0.15%2B0-b2043.56-8887301%29%0A++++%E2%80%A2+All+Android+licenses+accepted.%0A%0A%5B%E2%9C%93%5D+Xcode+-+develop+for+iOS+and+macOS+%28Xcode+16.0%29%0A++++%E2%80%A2+Xcode+at+%2FApplications%2FXcode.app%2FContents%2FDeveloper%0A++++%E2%80%A2+Build+16A242d%0A++++%E2%80%A2+CocoaPods+version+1.14.3%0A%0A%5B%E2%9C%93%5D+Chrome+-+develop+for+the+web%0A++++%E2%80%A2+Chrome+at+%2FApplications%2FGoogle+Chrome.app%2FContents%2FMacOS%2FGoogle+Chrome%0A%0A%5B%E2%9C%93%5D+Android+Studio+%28version+2022.1%29%0A++++%E2%80%A2+Android+Studio+at+%2FApplications%2FAndroid+Studio.app%2FContents%0A++++%E2%80%A2+Flutter+plugin+can+be+installed+from%3A%0A++++++%F0%9F%94%A8+https%3A%2F%2Fplugins.jetbrains.com%2Fplugin%2F9212-flutter%0A++++%E2%80%A2+Dart+plugin+can+be+installed+from%3A%0A++++++%F0%9F%94%A8+https%3A%2F%2Fplugins.jetbrains.com%2Fplugin%2F6351-dart%0A++++%E2%80%A2+Java+version+OpenJDK+Runtime+Environment+%28build+11.0.15%2B0-b2043.56-8887301%29%0A%0A%5B%E2%9C%93%5D+VS+Code+%28version+1.94.2%29%0A++++%E2%80%A2+VS+Code+at+%2FUsers%2Ftakacsvalentin%2FDownloads%2FVisual+Studio+Code.app%2FContents%0A++++%E2%80%A2+Flutter+extension+version+3.98.0%0A%0A%5B%E2%9C%93%5D+Connected+device+%285+available%29%0A++++%E2%80%A2+Vali+Takacs+%282%29+%28mobile%29++++++++%E2%80%A2+00008130-001118A134C1001C++++++++++++%E2%80%A2+ios++++++++++++%E2%80%A2+iOS+18.0.1+22A3370%0A++++%E2%80%A2+iPhone+16+Pro+%28mobile%29++++++++++%E2%80%A2+3016F50B-2A0E-47E9-AB92-41E0C079F06E+%E2%80%A2+ios++++++++++++%E2%80%A2+com.apple.CoreSimulator.SimRuntime.iOS-18-0+%28simulator%29%0A++++%E2%80%A2+macOS+%28desktop%29+++++++++++++++++%E2%80%A2+macos++++++++++++++++++++++++++++++++%E2%80%A2+darwin-arm64+++%E2%80%A2+macOS+15.0.1+24A348+darwin-arm64%0A++++%E2%80%A2+Mac+Designed+for+iPad+%28desktop%29+%E2%80%A2+mac-designed-for-ipad++++++++++++++++%E2%80%A2+darwin+++++++++%E2%80%A2+macOS+15.0.1+24A348+darwin-arm64%0A++++%E2%80%A2+Chrome+%28web%29++++++++++++++++++++%E2%80%A2+chrome+++++++++++++++++++++++++++++++%E2%80%A2+web-javascript+%E2%80%A2+Google+Chrome+129.0.6668.103%0A%0A%5B%E2%9C%93%5D+Network+resources%0A++++%E2%80%A2+All+expected+network+resources+are+available.%0A%0A%E2%80%A2+No+issues+found%21%0A%0A%60%60%60%0A%0A%23%23+Flutter+Application+Metadata%0A%2A%2AType%2A%2A%3A+app%0A%2A%2AVersion%2A%2A%3A+1.0.5%0A%2A%2AMaterial%2A%2A%3A+true%0A%2A%2AAndroid+X%2A%2A%3A+false%0A%2A%2AModule%2A%2A%3A+false%0A%2A%2APlugin%2A%2A%3A+false%0A%2A%2AAndroid+package%2A%2A%3A+null%0A%2A%2AiOS+bundle+identifier%2A%2A%3A+null%0A%2A%2ACreation+channel%2A%2A%3A+stable%0A%2A%2ACreation+framework+version%2A%2A%3A+2663184aa79047d0a33a14a3b607954f8fdd8730%0A%23%23%23+Plugins%0Acloud_firestore-4.17.5%0Acloud_firestore_web-3.12.5%0Acloud_functions-4.7.6%0Acloud_functions_web-4.9.6%0Afile_picker-8.0.7%0Afile_selector_linux-0.9.3%0Afile_selector_macos-0.9.4%2B2%0Afile_selector_windows-0.9.3%2B3%0Afirebase_analytics-10.10.7%0Afirebase_analytics_web-0.5.7%2B7%0Afirebase_auth-4.20.0%0Afirebase_auth_web-5.12.0%0Afirebase_core-2.32.0%0Afirebase_core_web-2.17.5%0Afirebase_messaging-14.9.4%0Afirebase_messaging_web-3.8.7%0Afirebase_storage-11.7.7%0Afirebase_storage_web-3.9.7%0Aflutter_plugin_android_lifecycle-2.0.23%0Afluttertoast-8.2.8%0Agoogle_sign_in-6.2.1%0Agoogle_sign_in_android-6.1.33%0Agoogle_sign_in_ios-5.7.8%0Agoogle_sign_in_web-0.12.4%2B2%0Aimage_picker-0.8.9%0Aimage_picker_android-0.8.12%2B15%0Aimage_picker_for_web-2.2.0%0Aimage_picker_ios-0.8.12%0Aimage_picker_linux-0.2.1%2B1%0Aimage_picker_macos-0.2.1%2B1%0Aimage_picker_windows-0.2.1%2B1%0Apath_provider-2.1.4%0Apath_provider_android-2.2.12%0Apath_provider_foundation-2.4.0%0Apath_provider_linux-2.2.1%0Apath_provider_windows-2.3.0%0Apermission_handler-11.3.1%0Apermission_handler_android-12.0.12%0Apermission_handler_apple-9.4.5%0Apermission_handler_html-0.1.3%2B2%0Apermission_handler_windows-0.2.1%0Ashared_preferences-2.3.2%0Ashared_preferences_android-2.3.3%0Ashared_preferences_foundation-2.5.3%0Ashared_preferences_linux-2.4.1%0Ashared_preferences_web-2.4.2%0Ashared_preferences_windows-2.4.1%0Asign_in_with_apple-5.0.0%0Asign_in_with_apple_web-1.0.1%0Asqflite-2.4.0%0Asqflite_android-2.4.0%0Asqflite_darwin-2.4.1-1%0Avideo_player-2.9.2%0Avideo_player_android-2.7.9%0Avideo_player_avfoundation-2.6.2%0Avideo_player_web-2.3.2%0A%0A&labels=tool%2Csevere%3A+crash


Exited (1).

```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.24.3, on macOS 15.0.1 24A348 darwin-arm64, locale en-RO)
    • Flutter version 3.24.3 on channel stable at /Users/takacsvalentin/Documents/Dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2663184aa7 (6 weeks ago), 2024-09-11 16:27:48 -0500
    • Engine revision 36335019a8
    • Dart version 3.5.3
    • DevTools version 2.37.3

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/takacsvalentin/Library/Android/sdk
    • Platform android-34, build-tools 33.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16A242d
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.94.2)
    • VS Code at /Users/takacsvalentin/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.98.0

[✓] Connected device (4 available)
    • Vali Takacs (2) (mobile)        • 00008130-001118A134C1001C • ios            • iOS 18.0.1 22A3370
    • macOS (desktop)                 • macos                     • darwin-arm64   • macOS 15.0.1 24A348 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad     • darwin         • macOS 15.0.1 24A348 darwin-arm64
    • Chrome (web)                    • chrome                    • web-javascript • Google Chrome 129.0.6668.103

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by huycozy** [comment] 2024-10-23 05:56
Closing this as a duplicate of https://github.com/flutter/flutter/issues/150131.

**Closed by huycozy** 2024-10-23 05:56 UTC
Labels: in triage
