### ISSUE TITLE
Provide a way to allow or disallow pull to refresh when the scrollable does not scroll to the top on android

### ISSUE THREAD

**Issue by branflake2267** [flutter/flutter#9690] opened 2017-04-29 18:00 UTC
The refresh indicator doesn't show up when scrolling up. In order for the refresh indicator to show, I noticed that the list has to be at the top, before scroll up occurs. I'll be recording the video tonight, and it may or may not show up. I will provide a link to it when finished, with a more complete source writeup. 

## Steps to Reproduce

1. With the refresh indicator wired up this way
```dart
/// place: "/todos"
class TodosPage extends StatefulWidget {
  TodosPage({Key key}) : super(key: key);

  static const String routeName = "/todos";

  @override
  _TodosPageState createState() => new _TodosPageState();
}

class _TodosPageState extends State<TodosPage> {
  final GlobalKey<RefreshIndicatorState> _refreshIndicatorKey = new GlobalKey<
      RefreshIndicatorState>();

  @override
  Widget build(BuildContext context) {
    return new Theme(
      data: _themeData,
      child: new Scaffold(
        appBar: new AppBar(title: new Text("My Todos")),
        body: new RefreshIndicator(
          key: _refreshIndicatorKey,
          child: new ListView.builder(
            itemBuilder: _itemBuilder,
          ),
          onRefresh: _onRefresh,
        ),
      ),
    );
  }

  // simulate a http request
  Future<Null> _onRefresh() {
    Completer<Null> completer = new Completer<Null>();

    new Timer(new Duration(seconds: 3), () {
      print("timer complete");
      completer.complete();
    });

    return completer.future;
  }

  Widget _itemBuilder(BuildContext context, int index) {
    Todo todo = new Todo(false, "Todo $index");
    return new TodoItemWidget(todo: todo);
  }
}
```
2. Scroll down some, then swipe up to activate refresh indicator

- If the list is part way down, the refresh indicator can't be pulled
- If the list is all the way to top, the refresh indicator can be pulled down

Notice the behavior here:
![refreshindicatorbug](https://cloud.githubusercontent.com/assets/1326504/25557674/f36ae64e-2cca-11e7-8031-9f60c0a8c081.gif)

## Logs

```
/Users/branflake2267/git/flutter/bin/flutter --no-color doctor
[✓] Flutter (on Mac OS X 10.12.4 16E195, channel master)
    • Flutter at /Users/branflake2267/git/flutter
    • Framework revision a4ba761bea (19 hours ago), 2017-04-28 16:01:14 -0700
    • Engine revision da8ebf40bd
    • Tools Dart version 1.23.0-dev.11.11

[✓] Host Executable Compatibility
    • Downloaded executables execute on host

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at /Users/branflake2267/Library/Android/sdk
    • Platform android-25, build-tools 25.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.3.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.3.2, Build version 8E2002
    • ios-deploy 1.9.1
    • CocoaPods version 1.2.1

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Gradle version 3.2
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Ultimate Edition (version 2017.1.2)
    • Dart plugin version 171.4424
    • Flutter plugin version 13.0

[✓] Connected devices
    • iPhone SE • 1C15BC7F-DA25-4E71-B479-B601B549CAA0 • ios • iOS 10.3 (simulator)

Process finished with exit code 0

```

**Comment by Hixie** [comment] 2017-04-30 05:52
This is working as designed. It's intended to make it so that someone who is just scrolling to the top of your list doesn't accidentally start a refresh.

**Comment by branflake2267** [comment] 2017-04-30 16:03
You may want to reconsider the design strategy for the pull down and here's why:
- The designed behavior Android vs IOS is different. 
- Those coming from android development will see this as a bug because the recycler view, one of the more popular containers by default will always show the refresh indicator if you scroll to top. 
- See the default behavior in an app called Youtube Studio done by Google, when you pull down, it will always show the refresh indicator. 
- Two different states of behavior for scrolling may confuse end users using the indicator.

Coming from android development it feels wonky to me. But like anything, I adjust, maybe it's different and I have to adjust.

**Comment by Hixie** [comment] 2017-04-30 17:49
Android apps differ on this front. For example, compare Chrome and Play Newsstand. The Material spec is a bit vague but I think a strict reading is that the "swipe-to-refresh" action is a "gesture" and thus separate from the scrolling action (meaning you have to lift your finger and put it back down to trigger it).

However, we can definitely provide an option if people want their app to work differently.

**Comment by eseidelGoogle** [comment] 2017-05-01 15:49
See also https://github.com/flutter/flutter/issues/9602

**Comment by oliverjanik** [comment] 2017-11-28 15:01
I'm going to back up @branflake2267 here. It does feel wonky.

Most common behaviour is the one from newsstand app. I feel like chrome team had to make a trade off because their scrolling is way more complicated due to HTML & CSS rendering.

Moreover the flutter gallery does not match either of those approaches when you 
1) pull down the indicator
2) do NOT release
3) push it back up (i.e. you changed your mind)

In both Chrome and Newsstand the indicator goes up and eventually disappears. In Flutter the indicator and the scrollable bellow it move together. Which feels broken.

**Comment by acoutts** [comment] 2020-05-13 11:44
I've got this issue as well. I notice in many other apps including the google feed app in the Pixel launcher, you can activate the refresh within the same scroll motion without needing to scroll to the top, lift your finger, then try to drag down to refresh.

It also seems like the scroll indicator doesn't match the system theme and always displays a white circle indicator.

Demo here:
https://photos.app.goo.gl/23v7z5bBzAkjhMp77

**Comment by Keetz** [comment] 2020-11-16 12:48
I also find it a bit weird that you can't reach the top and refresh in a single swipe.

For example, in the gmail app (Android 11) it is possible to both reach the top and refresh in a single swipe just like this issue explains the expected behavior.

**Comment by sarbagyastha** [comment] 2020-12-05 01:59
#71303

**Comment by chunhtai** [comment] 2020-12-08 19:27
I merged the change to enable refresh indicator event if the app is not scrolled to the top without knowing the discussion on this thread. I will use this issue to track that we add an API to enable or disable this behavior

**Comment by xu-baolin** [comment] 2020-12-09 00:48
Move some comment to here.
 I also test the Android native behavior, the RefreshIndicator should not be pulled out when the scrollable widget rolls to the top by inertia( scroll up with the momentum, release finger before reaching the top edge) and over scroll happens.

**Comment by xu-baolin** [comment] 2020-12-15 02:16
> I've got this issue as well. I notice in many other apps including the google feed app in the Pixel launcher, you can activate the refresh within the same scroll motion without needing to scroll to the top, lift your finger, then try to drag down to refresh.
> 
> It also seems like the scroll indicator doesn't match the system theme and always displays a white circle indicator.
> 
> Demo here:
> https://photos.app.goo.gl/23v7z5bBzAkjhMp77

Could you file a new issue to track the theme problem? Thanks.

**Closed** 2020-12-24 02:29 UTC
Labels: P5, f: material design, f: scrolling, framework, severe: new feature
