### ISSUE TITLE
Flutter crash in android release version only with firestore

### ISSUE THREAD

**Issue by braxtont** [flutter/flutter#44700] opened 2019-11-12 12:58 UTC
## Steps to Reproduce
This only seems to reproduce on a physical android device, with a release build. Seems like it crashes on first call to firestore. I do not have a small repro because I don't have a physical device for quick iteration. Stack traces from Google Play. I'm currently on flutter channel master, but I have tried from beta + dev channels as well. 

**Target Platform:** Any android
**Target OS version/browser:** NA
**Devices:** Physical only, doesn't reproduce in emulator

## Logs

I don't have a local run, as I don't have a physical android device, which is making this hard to debug :( Stack trace from google play.

```
java.lang.RuntimeException: 
  at com.google.firebase.firestore.util.AsyncQueue.a (AsyncQueue.java:379)
  at com.google.firebase.firestore.util.AsyncQueue$$Lambda$5.run (AsyncQueue.java:2)
  at android.os.Handler.handleCallback (Handler.java:883)
  at android.os.Handler.dispatchMessage (Handler.java:100)
  at android.os.Looper.loop (Looper.java:214)
  at android.app.ActivityThread.main (ActivityThread.java:7356)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:492)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:930)

Caused by: java.lang.AbstractMethodError: 
  at com.google.protobuf.GeneratedMessageLite.a (GeneratedMessageLite.java:1319)
  at com.google.firestore.v1.StructuredQuery.a (StructuredQuery.java:7346)
  at com.google.protobuf.GeneratedMessageLite.a (GeneratedMessageLite.java:1355)
  at com.google.protobuf.GeneratedMessageLite$DefaultInstanceBasedParser.d (GeneratedMessageLite.java:1340)
  at com.google.protobuf.GeneratedMessageLite$DefaultInstanceBasedParser.b (GeneratedMessageLite.java:1328)
  at com.google.protobuf.CodedInputStream.a (CodedInputStream.java:497)
  at com.google.firestore.v1.Target$QueryTarget.a (Target.java:1186)
  at com.google.protobuf.GeneratedMessageLite.a (GeneratedMessageLite.java:1355)
  at com.google.protobuf.GeneratedMessageLite$DefaultInstanceBasedParser.d (GeneratedMessageLite.java:1340)
  at com.google.protobuf.GeneratedMessageLite$DefaultInstanceBasedParser.b (GeneratedMessageLite.java:1328)
  at com.google.protobuf.CodedInputStream.a (CodedInputStream.java:497)
  at com.google.firebase.firestore.proto.Target.a (Target.java:1101)
  at com.google.protobuf.GeneratedMessageLite.a (GeneratedMessageLite.java:1355)
  at com.google.protobuf.GeneratedMessageLite.a (GeneratedMessageLite.java:1432)
  at com.google.protobuf.GeneratedMessageLite.a (GeneratedMessageLite.java:1449)
  at com.google.firebase.firestore.proto.Target.a (Target.java:538)
  at com.google.firebase.firestore.local.SQLiteQueryCache.a (SQLiteQueryCache.java:238)
  at com.google.firebase.firestore.local.SQLiteQueryCache.a (SQLiteQueryCache.java:221)
  at com.google.firebase.firestore.local.SQLiteQueryCache$$Lambda$4.accept (SQLiteQueryCache.java:8)
  at com.google.firebase.firestore.local.SQLitePersistence$Query.a (SQLitePersistence.java:431)
  at com.google.firebase.firestore.local.SQLiteQueryCache.a (SQLiteQueryCache.java:218)
  at com.google.firebase.firestore.local.LocalStore.a (LocalStore.java:513)
  at com.google.firebase.firestore.core.SyncEngine.a (SyncEngine.java:178)
  at com.google.firebase.firestore.core.EventManager.a (EventManager.java:91)
  at com.google.firebase.firestore.core.FirestoreClient.b (FirestoreClient.java:152)
  at com.google.firebase.firestore.core.FirestoreClient$$Lambda$6.run (FirestoreClient.java:4)
  at com.google.firebase.firestore.util.AsyncQueue.a (AsyncQueue.java:311)
  at com.google.firebase.firestore.util.AsyncQueue$$Lambda$4.call (AsyncQueue.java:2)
  at com.google.firebase.firestore.util.AsyncQueue.a (AsyncQueue.java:287)
  at com.google.firebase.firestore.util.AsyncQueue$$Lambda$3.run (AsyncQueue.java:4)
  at java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:462)
  at java.util.concurrent.FutureTask.run (FutureTask.java:266)
  at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run (ScheduledThreadPoolExecutor.java:301)
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1167)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:641)
  at com.google.firebase.firestore.util.AsyncQueue$DelayedStartFactory.run (AsyncQueue.java:205)
  at java.lang.Thread.run (Thread.java:919)
```

```
Analyzing swapmeet...

   info • The value of the field '_globalConResetTimer' isn't used • lib/model/convention.dart:16:9 • unused_field
   info • The value of the field '_subset' isn't used • lib/model/tokenset.dart:53:11 • unused_field
   info • This class (or a class which this class inherits from) is marked as '@immutable', but one or more of its instance fields are not final:
          Counter.selectedValue • lib/widgets/counter.dart:8:7 • must_be_immutable

3 issues found. (ran in 6.2s)
```

```
[✓] Flutter (Channel master, v1.10.17-pre.49, on Mac OS X 10.14.6 18G1012, locale en-US)
    • Flutter version 1.10.17-pre.49 at /Applications/flutter
    • Framework revision e7073f9a1f (3 days ago), 2019-11-09 17:08:53 -0800
    • Engine revision 31cd2dfca2
    • Dart version 2.7.0


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at /Users/braxton/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    • CocoaPods version 1.7.1

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 41.0.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Community Edition (version 2019.1.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 38.2.3
    • Dart plugin version 191.8423

[✓] Connected device (1 available)
    • iPhone 11 Pro Max • 048D2EB0-7B10-4BA5-B908-4B581EF1696A • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-1 (simulator)

• No issues found!
```

**Comment by iapicca** [comment] 2019-11-12 14:26
Hi @braxtont 
for what I can see the issue is related to a FlutterFire plugin,
please open the issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
thank you

**Closed by iapicca** 2019-11-12 14:26 UTC

**Comment by letiagoalves** [comment] 2019-12-10 18:22
@braxtont hi, I am having the same problem. Did you found what is causing this? Thanks in advance!

**Comment by braxtont** [comment] 2019-12-10 18:23
The only solution I had was to back up to an older Flutter version. See discussion in https://github.com/FirebaseExtended/flutterfire/issues/1412

**Comment by letiagoalves** [comment] 2019-12-10 18:27
I see. It makes sense since I updated Flutter version recently. This is a hard regression. I have been using beta channel, maybe I need to stick to stable channel. I will downgrade and try it out. Thank you for the quick response @braxtont 🙇
