### ISSUE TITLE
singleWhere function cannot return null anymore with the implementation of null safety

### ISSUE THREAD

**Issue by spiderion** [flutter/flutter#70930] opened 2020-11-20 10:17 UTC
Previously used "singleWhere" function on a list which could return the null element whenever used with "orElse" combination now can no longer return null with the implementation of "null-safety" 

LikedProduct? foundProduct = products.singleWhere((element) => element.productID == product.id, orElse: () => null);

**Comment by pedromassangocode** [comment] 2020-11-20 10:21
Hi @spiderion 
From what I can see, the issue is related to Dart rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/dart-lang/sdk).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by pedromassangocode** 2020-11-20 10:21 UTC
