### ISSUE TITLE
Assertion failed: _userProvidedRouteName != null is not true

### ISSUE THREAD

**Issue by johnpryan** [flutter/flutter#70299] opened 2020-11-11 16:05 UTC
By navigating with the back button, my app can get into a state where it starts throwing exceptions when the back button is pressed.

This app doesn't use Nav 2.0, just a Navigator.

## Steps to Reproduce

1. Run an app with a list / detail navigation setup
2. Navigate to and from the list and detail pages (using the back button)
3. Press the back button

```
Error: Assertion failed: org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/navigation/history.dart:284:14 _userProvidedRouteName != null is not true
```

<details>
  <summary>Logs</summary>
```
flutter analyze
Analyzing web_books...                                                  
No issues found! (ran in 2.0s)
```

```
flutter doctor -v
[✓] Flutter (Channel master, 1.24.0-8.0.pre.189, on Mac OS X 10.15.7 19H2 darwin-x64,
    locale en)
    • Flutter version 1.24.0-8.0.pre.189 at /Users/ryjohn/code/github/flutter/flutter
    • Framework revision 28ecf05692 (16 hours ago), 2020-11-10 16:29:13 -0800
    • Engine revision 5f660ce784
    • Dart version 2.12.0 (build 2.12.0-31.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/ryjohn/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 43.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 50.0
    • Dart plugin version 202.7206

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.0

[✓] Connected device (2 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 86.0.4240.193

• No issues found!
```

</details>

**Comment by johnpryan** [comment] 2020-11-11 16:08
This happened during development, and could be caused by refreshing the page while viewing the details screen.

**Comment by mdebbar** [comment] 2020-11-13 17:04
I thought initially that this was an assertion in the framework, but I wasn't looking carefully. This is being thrown in the engine. I'll take a look at this one.

**Comment by Maadhav** [comment] 2020-11-16 06:21
I am also facing this is in Flutter Web Project.

**Comment by chunhtai** [comment] 2020-12-10 19:31
Hi @johnpryan  Can you provide an example app?

**Comment by chunhtai** [comment] 2020-12-23 19:10
I cannot reproduce it, this is my current code
```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      // initialRoute: '/book/1',
      routes: {
        '/': (_) => Home(),
        '/book/1': (_) => Book(),
      },
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: Center(
        child: RaisedButton(
          onPressed: () {
            Navigator.of(context).pushNamed('/book/1');
          },
        ),
      ),
    );
  }
}

class Book extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: Center(
        child: SelectableText(
          'book 1',
          toolbarOptions: ToolbarOptions(copy: false, cut: false, paste: false, selectAll: true),
          onSelectionChanged: (TextSelection selection, cause) {
            print(selection);
          },
          enableInteractiveSelection: true,
        ),
      ),
    );
  }
}
```

**Comment by johnpryan** [comment] 2021-01-06 00:35
I can't reproduce this anymore

**Comment by chunhtai** [comment] 2021-01-06 00:38
closing

**Comment by nick-hoang** [comment] 2021-01-12 09:48
I can reproduce this issue in my test project.

### Steps to Reproduce

1. Run an app with a list / detail navigation setup [Download demo here](https://herncpa-my.sharepoint.com/:u:/g/personal/dr485_365proplus_site/EYxiNo8DtLdEssrsZmBDho8BIuvFQgVM0BJk395mr0NO4Q?e=KKN8XF)
2. Navigate to and from the list and detail pages 
3. Press the back button of **the browser**

**Comment by johnpryan** [comment] 2021-01-12 16:24
Opened https://github.com/flutter/flutter/issues/73793 with steps to reproduce. I also found https://github.com/flutter/flutter/issues/73792, which also produces the error. 

The problem seems to come from running a hot restart - perhaps we could clear the browser history when this happens?

**Comment by arualana** [comment] 2021-01-12 21:15
I happens also on production build

**Comment by krimpenrik** [comment] 2021-02-01 08:10
I am facing this same issue in my web project, works fine before hot restart

**Comment by Pitazzo** [comment] 2021-02-03 14:31
Same problem here

**Comment by Kainanchen** [comment] 2021-02-06 11:44
same here

**Comment by lohhans** [comment] 2021-02-09 13:58
I got this error when i've hot-reload the web-app at least one time, then I worked around the problem as follows:

- Running on Chrome, press f12 to open dev tools
- Right click on reload icon
- Select option "Empty Cache and Hard Reload"

Then this error go away until the next hot-reload...

**Comment by chunhtai** [comment] 2021-02-12 19:43
for people who face this issue, let me know if you are seeing this issue without hot restart. Otherwise, I will assume this issue is tied to https://github.com/flutter/flutter/issues/73793. I have a fix that I will put up shortly, and will close this issue as fixed when the pr lands.

**Comment by SIMMORSAL** [comment] 2021-06-26 03:34
I have this issue without hot restart. When I run the project by pressing F5 in vscode, after navigating to details page and clicking back button the Navigation Animation runs but at the end of it both pages are visible and app freezes, and no error is printed in DEBUG CONSOLE.

However when running the project in cmd with `flutter run -d chrome`, back button works without any problems but this error is thrown.

<details>
<summary>Logs</summary>

```
Error: Assertion failed:
org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/navigation/history.dart:284:14_userProvidedRouteName != null
is not true
    at Object.throw_ [as throw] (http://localhost:65122/dart_sdk.js:5041:11)
    at Object.assertFailed (http://localhost:65122/dart_sdk.js:4980:15)
    at _engine.SingleEntryBrowserHistory.new.onPopState
    (http://localhost:65122/dart_sdk.js:141776:59)
Error: Assertion failed:
org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/navigation/history.dart:239:12_isOriginEntry(state)
is not true
    at Object.throw_ [as throw] (http://localhost:65122/dart_sdk.js:5041:11)
    at Object.assertFailed (http://localhost:65122/dart_sdk.js:4980:15)
    at _engine.SingleEntryBrowserHistory.new.[_unwrapOriginState]
    (http://localhost:65122/dart_sdk.js:141753:46)
    at _engine.SingleEntryBrowserHistory.new.tearDown
    (http://localhost:65122/dart_sdk.js:141809:79)
    at tearDown.next (<anonymous>)
    at http://localhost:65122/dart_sdk.js:37403:33
    at _RootZone.runUnary (http://localhost:65122/dart_sdk.js:37274:59)
    at _FutureListener.thenAwait.handleValue
    (http://localhost:65122/dart_sdk.js:32530:29)
    at handleValueCallback (http://localhost:65122/dart_sdk.js:33057:49)
    at Function._propagateToListeners (http://localhost:65122/dart_sdk.js:33095:17)  
    at _Future.new.[_completeWithValue] (http://localhost:65122/dart_sdk.js:32943:23)    at async._AsyncCallbackEntry.new.callback
    (http://localhost:65122/dart_sdk.js:32964:35)
    at Object._microtaskLoop (http://localhost:65122/dart_sdk.js:37526:13)
    at _startMicrotaskLoop (http://localhost:65122/dart_sdk.js:37532:13)
    at http://localhost:65122/dart_sdk.js:33303:9
```

</details>

**Comment by chunhtai** [comment] 2021-06-28 16:43
@SIMMORSAL can you provide a minimal repro?

**Comment by SIMMORSAL** [comment] 2021-06-28 21:29
@chunhtai Finally found a way to reproduce it. In the example you wrote above, if you put `MaterialApp` inside another one, this error occurs:

```
...
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: MaterialApp(
        // initialRoute: '/book/1',
        routes: {
          '/': (_) => Home(),
          '/book/1': (_) => Book(),
        },
      ),
    );
  }
}
...
```

**Comment by Chai112** [comment] 2021-06-30 14:03
Hey sorry if this post is a bit old - just wanted to chime in seeing the latest post was two days ago - I also found this issue for Android Studios. Works fine on first load, however up on hot restart, going back in the navigator sometimes throws this error. Sometimes it just doesn't do anything or pops navigation twice. I checked I don't have nested `MaterialApp()`, and I'm using onGeneratedRoutes() instead of routes. Hope that helps,
<details>
<summary>Log</summary><pre>
Error: Assertion failed: org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/navigation/history.dart:284:14
_userProvidedRouteName != null
is not true
    at Object.throw_ [as throw] (http://localhost:54032/dart_sdk.js:5334:11)
    at Object.assertFailed (http://localhost:54032/dart_sdk.js:5270:15)
    at _engine.SingleEntryBrowserHistory.new.onPopState (http://localhost:54032/dart_sdk.js:148689:59)
Error: Assertion failed: org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/navigation/history.dart:284:14
_userProvidedRouteName != null
is not true
    at Object.throw_ [as throw] (http://localhost:54032/dart_sdk.js:5334:11)
    at Object.assertFailed (http://localhost:54032/dart_sdk.js:5270:15)
    at _engine.SingleEntryBrowserHistory.new.onPopState (http://localhost:54032/dart_sdk.js:148689:59)
Error: Assertion failed: org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/navigation/history.dart:284:14
_userProvidedRouteName != null
is not true
    at Object.throw_ [as throw] (http://localhost:54032/dart_sdk.js:5334:11)
    at Object.assertFailed (http://localhost:54032/dart_sdk.js:5270:15)
    at _engine.SingleEntryBrowserHistory.new.onPopState (http://localhost:54032/dart_sdk.js:148689:59)
</pre>
</details>

**Comment by SIMMORSAL** [comment] 2021-07-01 04:43
@Chai112 you can run you app using terminal with this command `flutter run -d chrome`. The app should run without this problem now

**Comment by chunhtai** [comment] 2021-08-06 20:55
@SIMMORSAL I still can't reproduce it. This is the current code
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: MaterialApp(
        // initialRoute: '/book/1',
        routes: {
          '/': (_) => Home(),
          '/book/1': (_) => BookWidget(),
        },
      ),
    );
  }
}
class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('home'),),
    );
  }
}


class BookWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('book'),),
    );
  }
}
```

I think it is probably fixed, closing this issue

**Closed by chunhtai** 2021-08-06 20:55 UTC
Labels: engine, f: routes, platform-web, passed first triage, P3
