### ISSUE TITLE
Problem with Flutter and VSCODE: Does not find any Flutter Widgets automatically

### ISSUE THREAD

**Issue by Manuelbaun** [flutter/flutter#61358] opened 2020-07-13 15:51 UTC
Hi guys, 

I have a problem, that VSCODE is not finding any flutter widgets. For example, when I stand to import `StatelessWidget` and I normally do `Crtl + .` or use the QuickFix bulb, then I get a suggestion, `import 'package:flutter/material.dart'`. But for some reason, this does not work anymore at all. Intellisense works for all Dart classes and also my classes in my project, but for no flutter classes.

I am normally on the master channel and I have also tried the stable channel with no success. 

![flutter issue](https://user-images.githubusercontent.com/8715085/87324905-0ff4eb00-c531-11ea-800b-b16cfc521f72.png)

my flutter version
```
Flutter 1.17.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 8af6b2f038 (13 days ago) • 2020-06-30 12:53:55 -0700
Engine • revision ee76268252
Tools • Dart 2.8.4
```

any idea, how I can resolve that issue?

**Comment by TahaTesser** [comment] 2020-07-14 08:07
Hi @Manuelbaun 
Following the indication of [VS Code Flutter Extension](https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter), the correct way to address the problem is to open an issue in the dedicated [repository](https://github.com/Dart-Code/Dart-Code/issues).
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2020-07-14 08:07 UTC

**Comment by Manuelbaun** [comment] 2020-07-14 14:51
Hi @TahaTesser,

thank you for your response and I will option an issue there. But note, I've also tried different versions of the VS Code Flutter extension with no success.
