### ISSUE TITLE
[web] SystemChrome.setPreferredOrientations crashes silently on Safari

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [flutter/flutter#67640] opened 2020-10-08 14:47 UTC
## Steps to Reproduce

0. Be on the `beta` channel or later with `flutter config --enable-web`.
1. Run `flutter create bug`.
2. Edit `main.dart` and add a `SystemChrome.setPreferredOrientations` (awaited) call:

```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await SystemChrome.setPreferredOrientations([]);

  runApp(MyApp());
}

...
```

3. `flutter run -d chrome` the app.
4. Open the localhost port displayed in Chrome on Safari.

**Expected results:** the app should start on both Chrome and Safari.

**Actual results:** will start on Chrome but not on Safari. Removing the `SystemChrome` line will fix the issue.

### JS console (debug mode)

The JS console in Safari will only show the following:

> Unhandled Promise Rejection: Error

There is nothing else.

## Release mode

The behavior is exactly the same in release builds, i.e. Safari does not run the app.  
More importantly: this happens **silently**, i.e. there is **nothing displayed in the JS console**.

Because of this, it was incredibly difficult for us to find out why our web app was not working on Safari. In addition to that, https://github.com/dart-lang/sdk/issues/43520 did not allow us to even run the app in debug mode initially.

<details>
  <summary>Versions (click to expand)</summary>

```
Flutter 1.22.0 • channel beta • https://github.com/flutter/flutter.git
Framework • revision d408d302e2 (9 days ago) • 2020-09-29 11:49:17 -0700
Engine • revision 5babba6c4d
Tools • Dart 2.10.0
```

</details>

**Comment by TahaTesser** [comment] 2020-10-08 16:02
Hi @creativecreatorormaybenot 
### I can reproduce the issue on the latest `Channel beta, 1.22.0,` and `Channel dev, 1.23.0-7.0.pr` 

<img width="1364" alt="Screenshot 2020-10-08 at 9 25 44 PM" src="https://user-images.githubusercontent.com/48603081/95483760-45349c00-09ad-11eb-9200-7f13412e396c.png">


<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel dev, 1.23.0-7.0.pre, on Mac OS X 10.15.7 19H2 x86_64,
    locale en-GB)
    • Flutter version 1.23.0-7.0.pre at /Users/tahatesser/Code/flutter_dev
    • Framework revision db6e2d8aa5 (13 days ago), 2020-09-25 06:47:03 -0400
    • Engine revision 3a73d073c8
    • Dart version 2.11.0 (build 2.11.0-161.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.10.0.rc.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.0

 
[✓] Connected device (4 available)            
    • iPhone 11 Pro Max (mobile) • 8077196C-CC09-401F-8842-06A94368FF46 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)
    • macOS (desktop)            • macos                                •
      darwin-x64     • Mac OS X 10.15.7 19H2 x86_64
    • Web Server (web)           • web-server                           •
      web-javascript • Flutter Tools
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 85.0.4183.121

• No issues found!

```

</details> 

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel beta, 1.22.0, on Mac OS X 10.15.7 19H2, locale en-GB)
    • Flutter version 1.22.0 at /Users/tahatesser/Code/flutter_beta
    • Framework revision d408d302e2 (9 days ago), 2020-09-29 11:49:17 -0700
    • Engine revision 5babba6c4d
    • Dart version 2.10.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.10.0.rc.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.0

 
[✓] Connected device (3 available)            
    • iPhone 11 Pro Max (mobile) • 8077196C-CC09-401F-8842-06A94368FF46 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)
    • Web Server (web)           • web-server                           • web-javascript • Flutter Tools
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome
      85.0.4183.121

• No issues found!
```

</details> 

### However issue seems to be fixed on the latest  `Channel master, 1.23.0-8.0.pre.223`, keeping the issue open to tracking the fix for beta 

<img width="1227" alt="Screenshot 2020-10-08 at 9 22 54 PM" src="https://user-images.githubusercontent.com/48603081/95484137-b70ce580-09ad-11eb-9739-f79ab07b7a8e.png">


<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel master, 1.23.0-8.0.pre.223, on Mac OS X 10.15.7 19H2 x86_64, locale en-GB)
    • Flutter version 1.23.0-8.0.pre.223 at /Users/tahatesser/Code/flutter_master
    • Framework revision 82ff246156 (49 minutes ago), 2020-10-08 11:09:27 -0400
    • Engine revision 2eac514f26
    • Dart version 2.11.0 (build 2.11.0-186.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.10.0.rc.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.0

 
[✓] Connected device (4 available)            
    • iPhone 11 Pro Max (mobile) • 8077196C-CC09-401F-8842-06A94368FF46 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)
    • macOS (desktop)            • macos                                • darwin-x64     • Mac OS X
      10.15.7 19H2 x86_64
    • Web Server (web)           • web-server                           • web-javascript • Flutter Tools
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome
      85.0.4183.121

• No issues found!
```

</details> 

<details> 
<summary>complete code sample</summary> 

```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await SystemChrome.setPreferredOrientations([]);
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: Container(
          child: Text('Hello World'),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {},
      ),
    );
  }
}

```

</details>

**Comment by creativecreatorormaybenot** [comment] 2020-10-08 16:38
@TahaTesser Thanks a lot! Did you also test on `dev`? I tested on `dev` (but not on `master`) and was able to produce the error on macOS Safari.

**Comment by TahaTesser** [comment] 2020-10-08 20:13
@creativecreatorormaybenot 
I did `dev` as mentioned earlier https://github.com/flutter/flutter/issues/67640#issuecomment-705668266 , Issue is existed on `dev`

**Comment by creativecreatorormaybenot** [comment] 2020-10-08 20:18
@TahaTesser I did not realize there were two channels in the first header, sorry.

**Comment by ferhatb** [comment] 2020-10-08 20:24
Closing. Will get fix on next dev release.

**Closed by ferhatb** 2020-10-08 20:24 UTC
Labels: a: layout, browser: safari, engine, found in release: 1.22, found in release: 1.23, has reproducible steps, platform-web, severe: crash
