### ISSUE TITLE
http request memory leak!

### ISSUE THREAD

**Issue by liqping** [flutter/flutter#108513] opened 2022-07-28 05:44 UTC
1.This issue associated with #62107 ,sky_engine http.dart and http dart package(http-0.13.4) memory leak!.
2.Request big image from net,  filtered memory continuous increase. 
3.Test platform: android and windows, other platform not test.
4.Test result:(--profile)
![微信图片_20220728133915](https://user-images.githubusercontent.com/62126718/181429063-18cec3c5-be79-4eb9-81d1-f445bb8189b4.png)
![微信图片_20220728133929](https://user-images.githubusercontent.com/62126718/181429064-89814e69-3e7a-426a-bb5d-31f3b34f339c.png)
5. Test code:

```dart
import 'package:http/http.dart' as http;
void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const TestPage(),
    );
  }
}

class TestPage extends StatefulWidget{
  const TestPage({super.key});

  @override
  State<StatefulWidget> createState() {
    return _TestPageState();
  }

}

class _TestPageState extends State<TestPage>{

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: const Text('image test'),),
      body: Padding(
        padding: const EdgeInsets.all(50),
        child: PageView.builder(
          itemCount: 80,
          itemBuilder: (BuildContext context, int index) {
            return Stack(
              children: [
                Positioned.fill(
                  child:
                  FutureBuilder<http.Response>(
                      builder:( context, snapshot){
                        if(snapshot.hasData){
                          return Center(child: Text('data:${snapshot.data!.bodyBytes.length}'),);
                        }
                        return Center(child: Text('loading....'),);
                      },
                      future: http.get(Uri.parse('http://p3.itc.cn/images01/20201026/ee591e48355545be901755083b8f6df3.jpeg',)),
                )),
                Positioned(top: 200,left:0,right: 0,bottom:0,child: Center(child: Text('index:$index',style: const TextStyle(color: Colors.red,fontSize: 24),),))
              ],
            );
          },

        ),
      ),
    );
  }
}
```

7.flutter doctor -v

```
[√] Flutter (Channel stable, 3.0.5, on Microsoft Windows [版本 10.0.19043.1826], locale zh-CN)
    • Flutter version 3.0.5 at D:\fluter
    • Upstream repository https://github.com/flutter/flutter.git
    • FLUTTER_GIT_URL = https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (2 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at C:\Users\liping\AppData\Local\Android\sdk
    • Platform android-32, build-tools 32.0.0
    • Java binary at: D:\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.10.3)
    • Visual Studio at D:\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.10.31424.327
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.2)
    • Android Studio at D:\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] Connected device (4 available)
    • yx rk3288 (mobile) • ML5RRGLM2Q • android-arm    • Android 5.1.1 (API 22)
    • Windows (desktop)  • windows    • windows-x64    • Microsoft Windows [版本 10.0.19043.1826]
    • Chrome (web)       • chrome     • web-javascript • Google Chrome 103.0.5060.134
    • Edge (web)         • edge       • web-javascript • Microsoft Edge 103.0.1264.71

[√] HTTP Host Availability
    • All required HTTP hosts are available
```

**Comment by liqping** [comment] 2022-07-28 05:45
Image url need big size, so that memory grow quick.

**Comment by liqping** [comment] 2022-07-28 05:48
Dio plugin has this issue also.  HttpClient not test, maybe has this issue yet!

**Comment by liqping** [comment] 2022-07-28 05:54
page index == 35 ,memory picture:
![微信图片_20220728135219](https://user-images.githubusercontent.com/62126718/181430790-d3d2c9ed-7ba5-4f8e-9c82-cec9e3197be7.png)

**Comment by liqping** [comment] 2022-07-28 06:18
The issue happened when use below code:
`class _MyHomePageState extends State<MyHomePage> {

  int? imageSize;

  void _incrementCounter(){
    // setState(() {
    //   // This call to setState tells the Flutter framework that something has
    //   // changed in this State, which causes it to rerun the build method below
    //   // so that the display can reflect the updated values. If we changed
    //   // _counter without calling setState(), then the build method would not be
    //   // called again, and so nothing would appear to happen.
    //   _counter++;
    // });

    // showDialog(barrierColor: Colors.transparent,context: context,barrierDismissible: false, builder: (_){
    //   return _NoticeDetailWidget();
    // });

    setState(() {
      imageSize = null;
    });

    http.get(Uri.parse('http://p3.itc.cn/images01/20201026/ee591e48355545be901755083b8f6df3.jpeg',)).then((value) {
      setState(() {
        imageSize = value.bodyBytes.length;
      });
    });
  }

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: Center(
        // Center is a layout widget. It takes a single child and positions it
        // in the middle of the parent.
        child: Column(
          // Column is also a layout widget. It takes a list of children and
          // arranges them vertically. By default, it sizes itself to fit its
          // children horizontally, and tries to be as tall as its parent.
          //
          // Invoke "debug painting" (press "p" in the console, choose the
          // "Toggle Debug Paint" action from the Flutter Inspector in Android
          // Studio, or the "Toggle Debug Paint" command in Visual Studio Code)
          // to see the wireframe for each widget.
          //
          // Column has various properties to control how it sizes itself and
          // how it positions its children. Here we use mainAxisAlignment to
          // center the children vertically; the main axis here is the vertical
          // axis because Columns are vertical (the cross axis would be
          // horizontal).
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the button this many times:',
            ),
            Text(
              imageSize == null ? 'loading...' : 'size:$imageSize',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}`

**Comment by liqping** [comment] 2022-07-28 08:52
The  filtered memory don't increase when Use android native okhttp rquest image.
![微信图片_20220728165224](https://user-images.githubusercontent.com/62126718/181464458-8f00d420-16aa-49c0-bdfc-25059d95fa4b.png)

**Comment by liqping** [comment] 2022-07-28 09:28
The issue happend by test HttpClient used Image.network(...) with below code yet.
`class _TestPageState extends State{

  static final HttpClient _sharedHttpClient = HttpClient()..autoUncompress = false;

  static HttpClient get _httpClient {
    HttpClient client = _sharedHttpClient;
    assert(() {
      if (debugNetworkImageHttpClientProvider != null) {
        client = debugNetworkImageHttpClientProvider!();
      }
      return true;
    }());
    return client;
  }

  Future<Uint8List?> requestImageData(String url) async{
    final Uri resolved = Uri.base.resolve(url);
    final HttpClientRequest request = await _httpClient.getUrl(resolved);
    final HttpClientResponse response = await request.close();
    if (response.statusCode != HttpStatus.ok) {
      // The network may be only temporarily unavailable, or the file will be
      // added on the server later. Avoid having future calls to resolve
      // fail to check the network again.
      await response.drain<List<int>>(<int>[]);
      return null;
    }
    final data =  await consolidateHttpClientResponseBytes(
      response,
    );
    return data;
  }


  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
// Here we take the value from the MyHomePage object that was created by
// the App.build method, and use it to set our appbar title.
        title: const Text('image test'),),
      body: Padding(
        padding: const EdgeInsets.all(50),
        child: PageView.builder(
          itemCount: 80,
          itemBuilder: (BuildContext context, int index) {
            return Stack(
              children: [
                Positioned.fill(
                    child:
                    FutureBuilder<Uint8List?>(
                      builder:( context, snapshot){
                        if(snapshot.hasData){
                          if(snapshot.data == null){
                            return const Center(child: Text('load error....'),);
                          }
                          return Center(child: Text('data:${snapshot.data!.length}'),);
                        }
                        return const Center(child: Text('loading....'),);
                      },
                      future: requestImageData('http://p3.itc.cn/images01/20201026/ee591e48355545be901755083b8f6df3.jpeg'),
                    )),
                Positioned(top: 200,left:0,right: 0,bottom:0,child: Center(child: Text('index:$index',style: const TextStyle(color: Colors.red,fontSize: 24),),))
              ],
            );
          },
        ),
      ),
    );
  }
}`

The same code in flutter NetworkImage:
![微信图片_20220728172651](https://user-images.githubusercontent.com/62126718/181471947-c2cdc8c4-6b0d-456d-9dcf-8119e20558ce.png)
![微信图片_20220728172700](https://user-images.githubusercontent.com/62126718/181472061-db272cb7-95db-49f1-9763-59b7cee9eea9.png)
![微信图片_20220728172705](https://user-images.githubusercontent.com/62126718/181472103-43f2867c-b716-4424-91c8-434dfa865fe1.png)

**Comment by maheshmnj** [comment] 2022-07-28 14:03
Hi @liqping, Thanks for filing the issue. I do see the memory is increasing with each network request on a pageView. But I am not sure which instances are not being cleared labeling for further investigation from the team.

<img width="1420" alt="image" src="https://user-images.githubusercontent.com/31410839/181524064-bf383796-a57f-4d53-9796-61cab6838163.png">


<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.4 21F79 darwin-arm, locale en-IN)
    • Flutter version 3.0.5 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (5 days ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-32, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.67.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.44.0

[✓] Connected device (3 available)
    • sdk gphone arm64 (mobile) • emulator-5554 • android-arm64  • Android 11 (API 30) (emulator)
    • macOS (desktop)           • macos         • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)              • chrome        • web-javascript • Google Chrome 103.0.5060.114

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

```
[✓] Flutter (Channel master, 3.1.0-0.0.pre.1868, on macOS 12.4 21F79 darwin-arm, locale en-IN)
    • Flutter version 3.1.0-0.0.pre.1868 on channel master at /Users/mahesh/Documents/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 925bee92e7 (2 days ago), 2022-07-26 04:49:06 -0400
    • Engine revision 5dcaeae656
    • Dart version 2.19.0 (build 2.19.0-34.0.dev)
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-32, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13C100
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.69.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.44.0

[✓] Connected device (3 available)
    • sdk gphone arm64 (mobile) • emulator-5554 • android-arm64  • Android 11 (API 30) (emulator)
    • macOS (desktop)           • macos         • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)              • chrome        • web-javascript • Google Chrome 103.0.5060.134

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by liqping** [comment] 2022-07-29 02:26
@maheshmnj I guess that it happend all platform. I test on windows 10,the issue did hanppen.
Request times from 0-18-67. Memory increase quickly!
![微信图片_1](https://user-images.githubusercontent.com/62126718/181669832-b0431c19-77b2-4146-95a6-1de68b1490e2.jpg)
![微信图片_2](https://user-images.githubusercontent.com/62126718/181669841-47bff75f-b15e-41f7-9381-37c23385c96a.jpg)
![微信图片_3](https://user-images.githubusercontent.com/62126718/181669847-c2f206e2-5fac-4b07-8098-d15aedb40a9d.jpg)

**Comment by liqping** [comment] 2022-07-29 02:31
test code: 
https://github.com/flutter/flutter/issues/108513#issuecomment-1197712375

**Comment by liqping** [comment] 2022-07-29 02:50
@dnfield

**Comment by dnfield** [comment] 2022-07-29 04:14
Your problem is that you are using a list that has items with no initial height, so it is eagerly inflating all of the items and doing all of the network requests.

Give your list an `itemExtent` or give your items a height somehow (e.g. wrap them in a sized box or give the image widget a height parameter) and your problem should go away.

Assuming I'm right, the bug here is https://github.com/flutter/flutter/issues/70147

I'm going to close this but feel free to ping it back if I'm missing something, or if you can produce a actually lazy listview that behaves this way.

**Comment by liqping** [comment] 2022-07-29 07:18
@dnfield Thanks! The issue maybe is not caused by itemExent and list.   
The code: https://github.com/flutter/flutter/issues/108513#issuecomment-1197712375 don't use listview or pageview.
Today,by test this question, it seem to don't happend on debug and release mode, even if on profile, it happend only when open DevTools to check memory. I think that the DevTools retain some memory maybe , so the filtered memory(dart/flutter not native) continuous increase.

**Comment by dnfield** [comment] 2022-07-29 16:21
The linked comment is not a complete example - can you try to add a complete code sample there? also /cc @kenzieschmoll fyi

**Comment by jason-simmons** [comment] 2022-07-29 20:03
I tried running the simple `http.get` call in https://github.com/flutter/flutter/issues/108513#issuecomment-1197712375 as well as the PageView example in https://github.com/flutter/flutter/issues/108513#issue-1320423009

In both cases I saw the expected behavior of the garbage collector.  Repeated calls to `http.get` will allocate memory up to some threshold, but the app eventually converges on a stable heap size.

**Comment by kenzieschmoll** [comment] 2022-07-29 21:36
@polina-c

**Comment by liqping** [comment] 2022-07-30 02:01
@dnfield 

Run code with --profile ,then open devtools check memory, tap button to http request.

`import 'package:http/http.dart' as http;
void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const TestPage(),
    );
  }
}

class TestPage extends StatefulWidget{
  const TestPage({super.key});

  @override
  State<StatefulWidget> createState() {
    return _TestPageState();
  }

}

class _TestPageState extends State<TestPage>{
 int? imageSize;

  void _incrementCounter(){
    // setState(() {
    //   // This call to setState tells the Flutter framework that something has
    //   // changed in this State, which causes it to rerun the build method below
    //   // so that the display can reflect the updated values. If we changed
    //   // _counter without calling setState(), then the build method would not be
    //   // called again, and so nothing would appear to happen.
    //   _counter++;
    // });

    // showDialog(barrierColor: Colors.transparent,context: context,barrierDismissible: false, builder: (_){
    //   return _NoticeDetailWidget();
    // });

    setState(() {
      imageSize = null;
    });

    http.get(Uri.parse('http://p3.itc.cn/images01/20201026/ee591e48355545be901755083b8f6df3.jpeg',)).then((value) {
      setState(() {
        imageSize = value.bodyBytes.length;
      });
    });
  }

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: Center(
        // Center is a layout widget. It takes a single child and positions it
        // in the middle of the parent.
        child: Column(
          // Column is also a layout widget. It takes a list of children and
          // arranges them vertically. By default, it sizes itself to fit its
          // children horizontally, and tries to be as tall as its parent.
          //
          // Invoke "debug painting" (press "p" in the console, choose the
          // "Toggle Debug Paint" action from the Flutter Inspector in Android
          // Studio, or the "Toggle Debug Paint" command in Visual Studio Code)
          // to see the wireframe for each widget.
          //
          // Column has various properties to control how it sizes itself and
          // how it positions its children. Here we use mainAxisAlignment to
          // center the children vertically; the main axis here is the vertical
          // axis because Columns are vertical (the cross axis would be
          // horizontal).
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the button this many times:',
            ),
            Text(
              imageSize == null ? 'loading...' : 'size:$imageSize',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
`

**Comment by liqping** [comment] 2022-07-30 02:03
@jason-simmons 
Do you run with --profile and open devtools check?

**Comment by Clon1998** [comment] 2022-07-30 21:58
I will join in this discussion since I have spent my last few days trying to find the reason why my app is leaking memory.
I narrowed it down to an `http.get` request that is periodically called through a `Timer` to fetch an updated JPEG and uses the [http](https://pub.dev/packages/http) package. The Widget is not wrapped inside any list and there is only a single Widget instance used in my app.

For me in debug mode the app is not leaking any memory however, once I am using profile mode it is.
Here is my sample/test widget that just sends/receives a request but does do much else with the data, still it leaks:

```dart
import 'dart:async';
import 'package:http/http.dart';
import 'package:flutter/widgets.dart';

class BuggyHttp extends StatefulWidget {
  const BuggyHttp({Key? key}) : super(key: key);

  @override
  State<BuggyHttp> createState() => _BuggyHttpState();
}

class _BuggyHttpState extends State<BuggyHttp> {
  Timer? _timer;
  final Client _httpClient = Client();
  int _cnt = 0;

  @override
  void initState() {
    super.initState();
    _restartTimer();
  }

  _restartTimer() {
    _timer = Timer(Duration(milliseconds: 100), _timerCb);
  }

  _timerCb() async {
    try {
      Response response = await _httpClient
          .get(Uri.parse("https://3.bp.blogspot.com/-g3VxuIl9lgg/XHQ2TP-HiHI/AAAAAAAAHJI/Cu1UbP_FysMIg7LM5whAQt2nJWhXGjSJgCLcBGAs/s1600/image4.jpg"))
          .timeout(const Duration(seconds: 10));
      print('Resp was: ${response.statusCode}');
      setState(() {
        _cnt++;
      });
      _restartTimer();
    } catch (e, s) {
      print('Exception $e');
    }
  }

  @override
  Widget build(BuildContext context) {
    return Text('NumOfReq: $_cnt');
  }

  @override
  void dispose() {
    super.dispose();
    _httpClient.close();
    _timer?.cancel();
  }
}

```

My memory after a few mins:
<img width="265" alt="Bildschirmfoto 2022-07-30 um 23 54 05" src="https://user-images.githubusercontent.com/10357775/182000147-1216bf53-5457-4119-80f0-6c48000c2068.png">

**Comment by jonahwilliams** [comment] 2022-08-01 18:13
I looked into this briefly and I think it may be related to dart:io holding request bodies in memory for debugging, but I'm not exactly sure how to track that down or where it would be stored. @bkonyi

**Comment by dnfield** [comment] 2022-08-01 18:20
If I'm reading the source right, it looks like this was added in https://dart-review.googlesource.com/c/sdk/+/189881 @bkonyi @rmacnak-google @kenzieschmoll 

Specifically, https://github.com/dart-lang/sdk/blob/main/sdk/lib/_http/http_impl.dart#L94, which is all guarded by `HttpClient.enableTimelineLogging`.

If you call `HttpClient.enableTimelineLogging = false` you might be ok.

@bkonyi @kenzieschmoll - it seems like this should probably be a simple `postEvent` rather than caching this data, or at the very least that it should only keep the last N requests (or N bytes total of response body data)...

**Comment by mraleph** [comment] 2022-08-01 20:51
It's a duplicate of https://github.com/dart-lang/sdk/issues/49506

**Comment by dnfield** [comment] 2022-08-01 21:18
Closing as duplicate

**Closed by dnfield** 2022-08-01 21:18 UTC
Labels: platform-android, engine, dependency: dart, r: invalid, perf: memory, has reproducible steps, P2, dart:io, found in release: 3.0, found in release: 3.1
