### ISSUE TITLE
flutter web taking 30+ seconds to launch in debug 

### ISSUE THREAD

**Issue by matthewchung74** [flutter/flutter#83565] opened 2021-05-28 16:43 UTC
## Steps to Reproduce

1. pull dev branch https://github.com/matthewchung74/inference_app/tree/dev
2. launch first debug configuration in vscode (Flutter Web 9000)
3. wait

## Logs

<details>
<summary>Logs</summary>

I'm not sure how to get logs, if there are instructions, I can insert.

```
Matt-MacBookPro:inference_app mattc$ flutter doctor -v
[✓] Flutter (Channel beta, 2.2.0-10.3.pre, on Mac OS X 10.15.7 19H114 darwin-x64, locale en-US)
    • Flutter version 2.2.0-10.3.pre at /Users/mattc/flutter
    • Framework revision 06e2fd6357 (3 weeks ago), 2021-05-08 11:28:22 -0700
    • Engine revision a123e75c60
    • Dart version 2.13.0 (build 2.13.0-211.14.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/mattc/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.56.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.22.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 90.0.4430.212

• No issues found!
```

</details>

(video taking 30+ seconds)

https://user-images.githubusercontent.com/1685700/120015219-f1a4ac00-bf97-11eb-8258-bd4192fdacd5.mov

and on the command line 20 seconds.
```
Matt-MacBookPro:inference_app mattc$ flutter run -d chrome --web-port 9000 --web-enable-expression-evaluation --web-renderer auto
^CMatt-MacBookPro:inference_app mattc$ flutter run  -d chrome --web-port 9000 --web-enable-expression-evaluation --web-renderer auto
Launching lib/main.dart on Chrome in debug mode...
Waiting for connection from debug service on Chrome...             20.8s
This app is linked to the debug service: ws://127.0.0.1:51023/uO39_EGTH4k=/ws
Debug service listening on ws://127.0.0.1:51023/uO39_EGTH4k=/ws
```
is that what I should be expecting?

**Comment by ZurMaD** [comment] 2021-05-28 21:02
I suspect that is a vscode trouble, and not from Flutter

**Comment by matthewchung74** [comment] 2021-05-28 21:04
thanks @ZurMaD , even using the command line, it's takes 20 seconds, does that sound about right?

**Comment by TahaTesser** [comment] 2021-05-31 11:19
Hi @matthewchung74 
I see there's an open issue addressing the case you described.
Please follow up on that issue, Closing as duplicate of https://github.com/flutter/flutter/issues/76009
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-05-31 11:19 UTC
Labels: in triage

**Comment by matthewchung74** [comment] 2021-05-31 21:12
thanks @TahaTesser . 

You are right, it does seem like the same issue.  However, if I am mainly developing now, and want to start flutter in debug using a browser that has cache, do you have a recommendation? Or is it not possible because it is actually the app that is cached? (I just don't know if the cache is referring to some flutter libraries or the application)
