### ISSUE TITLE
[tool_crash] StateError: Bad state: No element

### ISSUE THREAD

**Issue by ayushmw** [flutter/flutter#74717] opened 2021-01-26 11:07 UTC
[flutter_01.log](https://github.com/flutter/flutter/files/5872934/flutter_01.log)

**Comment by TahaTesser** [comment] 2021-01-26 11:35
Closing this as a duplicate of https://github.com/flutter/flutter/issues/72385. 
Thank you

**Closed by TahaTesser** 2021-01-26 11:35 UTC
