### ISSUE TITLE
Duplicate / invalid locale resolution on iOS

### ISSUE THREAD

**Issue by lukaspili** [flutter/flutter#37404] opened 2019-08-01 17:14 UTC
## Steps to Reproduce

The issue is reproductible on iOS only. 
Locale resolution works as expected on Android.

1. Create new flutter project
2. Implement `localeListResolutionCallback`
3. Observe duplicate locales

The following snippet shows the issue:

```dart
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Container(),
      supportedLocales: [Locale('en'), Locale('fr')],
      localeListResolutionCallback: (locales, supportedLocales) {
        debugPrint('Locales: $locales in $supportedLocales');
        if (locales.isEmpty) {
          return null;
        }

        for (var locale in locales) {
          if (supportedLocales.map((it) => it.languageCode).contains(locale.languageCode)) {
            return locale;
          }
        }

        return supportedLocales.first;
      },
    );
  }
}
```

## Logs

**English language only**

<img src="https://user-images.githubusercontent.com/512080/62312656-c1a02680-b45c-11e9-8f7f-b8529a81cfe1.png" height="500">

Logs:

```
Locales: [] in [en, fr]
Locales: [en_CA, en_CA] in [en, fr]
```

Duplicated `en_CA` locale.

**French, English languages**

<img src="https://user-images.githubusercontent.com/512080/62312760-075cef00-b45d-11e9-8d99-975274122826.png" height="500">

Logs:

```
Locales: [] in [en, fr]
Locales: [en_CA, fr_CA, en_CA] in [en, fr]
```

Duplicated `en_CA` locale, and always in the first position, while it should be `fr_CA`.
It breaks the localizations because the locale loaded is always `en_CA`.

Flutter doctor (I was also able to reproduce the issue on master)

```
[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.14.5 18F132, locale en-CA)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
[✓] iOS tools - develop for iOS devices
[!] Android Studio (version 3.4)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] IntelliJ IDEA Ultimate Edition (version 2019.1.3)
[✓] VS Code (version 1.36.1)
[✓] Connected device (1 available)
```

**Comment by GaryQian** [comment] 2020-05-19 10:43
https://github.com/flutter/engine/pull/18379 should fix this.

**Comment by GaryQian** [comment] 2020-05-19 10:44
Duplicate of https://github.com/flutter/flutter/issues/49775, let's track it there!

**Closed by GaryQian** 2020-05-19 10:44 UTC
Labels: a: internationalization, customer: crowd, f: material design, framework, platform-ios
