### ISSUE TITLE
Clarify text in Widget Gallery at flutter.io

### ISSUE THREAD

**Issue by jimbeveridge** [flutter/flutter#534] opened 2015-11-20 23:50 UTC
The opening sentence to http://flutter.io/widgets/ is, "This page describes the widgets available in Flutter."

To be clear, this page actually describes a small subset of the widgets available in Flutter. The rest of the widgets are awaiting documentation. (It might be nice to say this so developers don't try and search for the detailed docs.)

Also consider linking to the example/widgets directory in the source code.

**Comment by abarth** [comment] 2015-11-21 00:06
+1

**Comment by sethladd** [comment] 2015-11-23 17:37
cc @HansMuller

**Comment by sethladd** [comment] 2015-11-23 17:38
Thanks for the report! Dupe of https://github.com/flutter/flutter.github.io/issues/36 Will close this one out.

**Closed by sethladd** 2015-11-23 17:38 UTC
Labels: affects: docs, affects: material design
