### ISSUE TITLE
App crashes on Android when using apk generated by `flutter build apk`

### ISSUE THREAD

**Issue by moyashi-ikasui** [flutter/flutter#58055] opened 2020-05-27 01:53 UTC
I generated apks using `flutter build apk` with previous versions, and the app works fine on version v.1.15.1 or below, but crashes as soon as the app is ran on v.1.15.2 or above.
I'm thinking that a some kind of degrade has occurred when flutter was updated to v1.15.2, and is still not fixed in the previous version(v1.17.1).

---

By the way, the app won't crash on `v.1.15.2` or above if the app is installed on Android by `flutter run`. I would be happy if someone could tell me the difference between the two apks listed below.
- apk generated by `flutter build apk`
- apk generated by `flutter run`

---

`flutter doctor` doesn't show any problems both versions. 

- v.1.15.1
```
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, v1.15.1, on Mac OS X 10.15.4 19E287, locale ja-JP)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.45.1)
[✓] Connected device (1 available)

• No issues found!
```

- v.1.17.1
```
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.17.1, on Mac OS X 10.15.4 19E287, locale ja-JP)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.45.1)
[✓] Connected device (1 available)

• No issues found!
```

---
No problems on `flutter analyze` too.

- v.1.15.1
```
$ flutter analyze
Analyzing flutter_app...
No issues found! (ran in 15.8s)
```

- v.1.17.1
```
$ flutter analyze
Analyzing flutter_app...
No issues found! (ran in 6.5s)
```

**Comment by okursoftware** [comment] 2020-05-27 02:10
Flutter run -v  See detailed logs

**Comment by moyashi-ikasui** [comment] 2020-05-27 02:24
@okursoftware I'm not having any problems with `flutter run` on any versions.
The problem is, the app crashes on run if I use the apk generated by `flutter build apk` if the flutter version is v1.15.2 or above.

**Comment by iapicca** [comment] 2020-05-27 09:33
Hi @okursoftware 
can you please  run 
```console
flutter channel stable
flutter upgrade --force
```
and provide your `flutter doctor -v`,
your `flutter build apk --verbose` 
and your `pubspec.yaml`. 
Thank you

**Comment by moyashi-ikasui** [comment] 2020-05-27 12:29
Hi @iapicca 
Was the question meant to be asked to me?
If so, these are the logs and files.

### flutter doctor -v
[doctor.txt](https://github.com/flutter/flutter/files/4688655/doctor.txt)

### flutter build apk --verbose
[build.txt](https://github.com/flutter/flutter/files/4688656/build.txt)

### pubspec.yaml
[pubspec.yaml.txt](https://github.com/flutter/flutter/files/4688661/pubspec.yaml.txt)

**Comment by TahaTesser** [comment] 2020-05-28 08:38
Hi @moyashi-ikasui 
Can you please provide `flutter run --release --verbose`?
Also which device you're using the apk on?
Thank you

**Comment by moyashi-ikasui** [comment] 2020-05-28 15:30
Hi @TahaTesser 

> Can you please provide flutter run --release --verbose?

This is the log for `flutter run --release --verbose`
[run.txt](https://github.com/flutter/flutter/files/4696563/run.txt)
The app also crashes when I hit `flutter run --release`,  
but it won't crash when I hit `flutter run`.

> Also which device you're using the apk on?

I am using Pixel 3, and the software version is Android 10.

**Comment by iapicca** [comment] 2020-06-01 06:30
Hi @moyashi-ikasui 
you [mentioned](https://github.com/flutter/flutter/issues/58055#issuecomment-635422383) 

> The app also crashes when I hit flutter run --release,
> but it won't crash when I hit flutter run.

but I don't see any crash in your [logs](https://github.com/flutter/flutter/files/4696563/run.txt)
could you please provide the logs representative of the crush occurring when running
`flutter run --release --verbose`
thank you

**Comment by moyashi-ikasui** [comment] 2020-06-01 07:53
Hi @iapicca 
Before answering your question, let me ask a question.

I just tried `flutter run --release --verbose`  again to see what went wrong.
Last time I used flutter version v1.17.1, but this time the stable version was updated to v1.17.2 so I used it, and the app didn't crash. The app seems to work fine.
The apk generated by `flutter build apk` worked fine as well.
The issue doesn't seem to reproduce anymore on the newest stable version.

Should we close this issue, or should we keep on going with the investigation to find out what went wrong?

**Comment by TahaTesser** [comment] 2020-06-02 08:30
Hi @moyashi-ikasui 
Since the issue isn't reproducible on latest `stable`, no need to keep the issue open
given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you

**Closed by TahaTesser** 2020-06-02 08:30 UTC
Labels: in triage
