### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by shadowcz007** [flutter/flutter#25495] opened 2018-12-18 06:07 UTC
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command
```
flutter run
```
## exception
```
FileSystemException: FileSystemException: Getting current working directory failed, path = '' (OS Error: Too many open files, errno = 24)
```
```
#0      _uriBaseClosure (dart:io/runtime/bindirectory_patch.dart:64:5)
#1      Uri.base (dart:core/runtime/liburi_patch.dart:21:41)
#2      current (package:path/path.dart:84:17)
#3      new Context (package:path/src/context.dart:31:21)
#4      LocalFileSystem.path (package:file/src/backends/local/local_file_system.dart:34:29)
#5      writeBundle.<anonymous closure> (package:flutter_tools/src/bundle.dart:207:34)
<asynchronous suspension>
#6      MappedIterator.moveNext (dart:_internal/iterable.dart:392:18)
#7      Future.wait (dart:async/future.dart:392:26)
#8      writeBundle (package:flutter_tools/src/bundle.dart:205:16)
#9      _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#10     writeBundle (package:flutter_tools/src/bundle.dart:199:25)
#11     assemble (package:flutter_tools/src/bundle.dart:195:9)
#12     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#13     assemble (package:flutter_tools/src/bundle.dart:163:22)
#14     build (package:flutter_tools/src/bundle.dart:128:9)
#15     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#16     _rootRunUnary (dart:async/zone.dart:1132:38)
#17     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#18     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#19     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#20     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#21     Future._complete (dart:async/future_impl.dart:476:7)
#22     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#23     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
#24     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:295:13)
#25     buildAssets (package:flutter_tools/src/bundle.dart)
#26     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#27     _rootRunUnary (dart:async/zone.dart:1132:38)
#28     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#29     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#30     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#31     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#32     Future._complete (dart:async/future_impl.dart:476:7)
#33     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#34     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
#35     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:295:13)
#36     _ManifestAssetBundle.build (package:flutter_tools/src/asset.dart)
#37     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#38     _rootRunUnary (dart:async/zone.dart:1132:38)
#39     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#40     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#41     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#42     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#43     Future._complete (dart:async/future_impl.dart:476:7)
#44     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#45     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
#46     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:295:13)
#47     _obtainLicenses (package:flutter_tools/src/asset.dart)
#48     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#49     _rootRunUnary (dart:async/zone.dart:1132:38)
#50     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#51     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#52     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#53     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#54     Future._completeWithValue (dart:async/future_impl.dart:486:5)
#55     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:516:7)
#56     _rootRun (dart:async/zone.dart:1124:13)
#57     _CustomZone.run (dart:async/zone.dart:1021:19)
#58     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#59     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#60     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#61     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#62     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel master, v1.1.3-pre.23, on Mac OS X 10.13.6 17G2208, locale
    zh-Hans-CN)
    [32m•[39m Flutter version 1.1.3-pre.23 at /development/flutter
    [32m•[39m Framework revision 7ecef3aa27 (6 hours ago), 2018-12-17 15:56:26 -0800
    [32m•[39m Engine revision 5af435098d
    [32m•[39m Dart version 2.2.0 (build 2.2.0-dev.1.1 f9ebf21297)

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK 28.0.3)
    [32m•[39m Android SDK at /Users/shadow/Library/Android/sdk
    [32m•[39m Android NDK location not configured (optional; useful for native profiling
      support)
    [32m•[39m Platform android-28, build-tools 28.0.3
    [32m•[39m Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m iOS toolchain - develop for iOS devices (Xcode 10.1)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Xcode 10.1, Build version 10B61
    [32m•[39m ios-deploy 1.9.4
    [32m•[39m CocoaPods version 1.5.3

[32m[✓][39m Android Studio (version 3.2)
    [32m•[39m Android Studio at /Applications/Android Studio.app/Contents
    [32m•[39m Flutter plugin version 31.3.1
    [32m•[39m Dart plugin version 181.5656
    [32m•[39m Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)

[32m[✓][39m VS Code (version 1.30.0)
    [32m•[39m VS Code at /Users/shadow/Applications/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version 2.21.1

[32m[✓][39m Connected device (1 available)
    [32m•[39m iPhone XR • BC741659-E1A8-497D-B2AD-62EA065D33D8 • ios • iOS 12.1
      (simulator)

[32m•[39m No issues found!
```

**Comment by zoechi** [comment] 2018-12-18 07:00
Duplicate of #20316

**Closed by zoechi** 2018-12-18 07:00 UTC
