### ISSUE TITLE
[flutter_webview][platform macOS, windows] Add macOs and Windows support for flutter_webview

### ISSUE THREAD

**Issue by jaroslawdabrowski** [flutter/flutter#109253] opened 2022-08-09 20:05 UTC
In my company we are trying to decide what to use, flutter or react native. Important feature for us is web view. I really like flutter, but I can see that react native web view has macOS and windows support, while flutter web view doesn't. 

Are there any plans to add support for macOs and windows? React native library has it so it seems to be doable.

**Comment by stuartmorgan** [comment] 2022-08-09 20:27
Duplicate of https://github.com/flutter/flutter/issues/37597 and https://github.com/flutter/flutter/issues/41725

**Closed by stuartmorgan** 2022-08-09 20:27 UTC
