### ISSUE TITLE
iOS plugin - Xcode .xcframework isn't running on simulators

### ISSUE THREAD

**Issue by kndl22** [flutter/flutter#68605] opened 2020-10-20 13:47 UTC
## Steps to Reproduce
1. Add an .xcframework to iOS plugin:

at the plugin's ios folder, editting plugin_name.podspec:
```
Pod::Spec.new do |s|
  s.name             = 'web_plugin'
  s.version          = '0.0.1'
  s.summary          = 'A flutter plugin for web SDK'
  s.description      = <<-DESC
A flutter plugin for web SDK
                       DESC
  s.homepage         = 'http://example.com'
  s.license          = { :file => '../LICENSE' }
  s.author           = { 'Your Company' => 'email@example.com' }
  s.source           = { :path => '.' }
  s.source_files = 'Classes/**/*'
  s.dependency 'Flutter'
  s.platform = :ios, '12.0'

  # Flutter.framework does not contain a i386 slice. Only x86_64 simulators are supported.
  s.pod_target_xcconfig = { 'DEFINES_MODULE' => 'YES', 'VALID_ARCHS[sdk=iphonesimulator*]' => 'x86_64' }
  s.swift_version = '5.0'
  s.dependency 'EVReflection'

  s.preserve_paths = 'MySDK.xcframework', 'MySDKUILayer.xcframework'
  s.xcconfig = { 'OTHER_LDFLAGS' => '-framework MySDK -framework MySDKUILayer' }
  s.vendored_frameworks = 'MySDK.xcframework', 'MySDKUILayer.xcframework'
end
```

running pod install / update

2. Add the .xcframework to the target under "Embed Frameworks" (xCode)

3. Run app (simulator)

## Logs

```
ld: warning: ignoring file /Users/cnd/web-plugin/ios/MySDK.xcframework/ios-arm64_armv7/MySDK.framework/MySDK, missing required architecture x86_64 in file /Users/cnd/web-plugin/ios/MySDK.xcframework/ios-arm64_armv7/MySDK.framework/MySDK (2 slices)
ld: warning: ignoring file /Users/cnd/web-plugin/ios/MySDKUILayer.xcframework/ios-arm64_armv7/MySDKUILayer.framework/MySDKUILayer, missing required architecture x86_64 in file /Users/cnd/web-plugin/ios/MySDKUILayer.xcframework/ios-arm64_armv7/MySDKUILayer.framework/MySDKUILayer (2 slices)
Undefined symbols for architecture x86_64:
.
.
.
.
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Not sure how the plugin picks the correct architecture (real device or simulator), but currently it always fails on simulators even though the .xcframework contains the necessary x86_64.

**flutter doctor -v:**
```
[✓] Flutter (Channel stable, 1.22.2, on Mac OS X 10.15.7 19H2, locale en-IL)
    • Flutter version 1.22.2 at /Users/cnd/Developer/flutter
    • Framework revision 84f3d28555 (5 days ago), 2020-10-15 16:26:19 -0700
    • Engine revision b8752bbfff
    • Dart version 2.10.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/cnd/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (2 available)
    • Yuv’s iPhone (mobile) • 00008030-********            • ios • iOS
      14.0.1
    • iPhone 11 (mobile)      • 5CC25297-B0AA-4023-9B2D-34022BD842D3 • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)

• No issues found!

```

**Comment by TahaTesser** [comment] 2020-10-21 10:31
Hi @kndl22 
Is your project standard flutter or add2app, since you mentioned embed frameworks https://flutter.dev/docs/development/add-to-app/ios/project-setup#embed-the-frameworks
Can you please provide your `flutter run --verbose` ( if standard  app) and a complete reproducible minimal code sample in a repository with the plugin as well 
Thank you

**Comment by kndl22** [comment] 2020-10-21 11:04
Hi @TahaTesser ,
My project is a flutter plugin which has an Android & iOS integration. Each platform has it's own SDK, and when I'm trying to run the example inside the plugin i get the mentioned error.

I'm attaching the verbose log and meanwhile i'll work on a sample project.

[verbose log.txt](https://github.com/flutter/flutter/files/5415391/verbose.log.txt)

**Comment by TahaTesser** [comment] 2020-10-22 11:52
Hi @kndl22 
Running example folder, I am getting following, quite different than your logs
I am running pod version `1.10.0.rc.1`

```bash
[  +25 ms] Failed to build iOS app
[        ] Error output from Xcode build:
           ↳
[   +1 ms]     ** BUILD FAILED **
           
           
[        ] Xcode's output:
           ↳
[   +4 ms]     Command line invocation:
                   /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild
                   -configuration Debug VERBOSE_SCRIPT_LOGGING=YES -workspace
                   Runner.xcworkspace -scheme Runner

BUILD_DIR=/Users/tahatesser/AndroidStudioProjects/flutter-ios-plugin-tes
                   t/example/build/ios -sdk iphonesimulator -arch x86_64

SCRIPT_OUTPUT_STREAM_FILE=/var/folders/6w/rnw9ch3d2cv277x3nzm9t9ph0000gn

/T/flutter_tools.Nggfy4/flutter_build_log_pipe.P94QvL/pipe_to_stdout
                   FLUTTER_SUPPRESS_ANALYTICS=true
COMPILER_INDEX_STORE_ENABLE=NO
           
               Build settings from command line:
                   ARCHS = x86_64
                   BUILD_DIR =

/Users/tahatesser/AndroidStudioProjects/flutter-ios-plugin-test/example/
                   build/ios
                   COMPILER_INDEX_STORE_ENABLE = NO
                   FLUTTER_SUPPRESS_ANALYTICS = true
                   SCRIPT_OUTPUT_STREAM_FILE =

/var/folders/6w/rnw9ch3d2cv277x3nzm9t9ph0000gn/T/flutter_tools.Nggfy4/fl
                   utter_build_log_pipe.P94QvL/pipe_to_stdout
                   SDKROOT = iphonesimulator14.1
                   VERBOSE_SCRIPT_LOGGING = YES
           
               note: Using new build system
               note: Building targets in parallel
               note: Planning build
               note: Constructing build description
               Build system information
               error: Multiple commands produce

'/Users/tahatesser/AndroidStudioProjects/flutter-ios-plugin-test/example/bui

ld/ios/Debug-iphonesimulator/Runner.app/Frameworks/TransmitSDK3.framework':
               1) Target 'Runner' has copy command from

'/Users/tahatesser/AndroidStudioProjects/flutter-ios-plugin-test/ios/Transmi

tSDK3.xcframework/ios-i386_x86_64-simulator/TransmitSDK3.framework' to

'/Users/tahatesser/AndroidStudioProjects/flutter-ios-plugin-test/example/bui

ld/ios/Debug-iphonesimulator/Runner.app/Frameworks/TransmitSDK3.framework'
               2) That command depends on command in Target 'Runner': script
phase “[CP]
               Embed Pods Frameworks”
           
           
               Build system information
               error: Multiple commands produce

'/Users/tahatesser/AndroidStudioProjects/flutter-ios-plugin-test/example/bui

ld/ios/Debug-iphonesimulator/Runner.app/Frameworks/TransmitSDKUILayer.framew
               ork':
               1) Target 'Runner' has copy command from

'/Users/tahatesser/AndroidStudioProjects/flutter-ios-plugin-test/ios/Transmi

tSDKUILayer.xcframework/ios-i386_x86_64-simulator/TransmitSDKUILayer.framewo
               rk' to

'/Users/tahatesser/AndroidStudioProjects/flutter-ios-plugin-test/example/bui

ld/ios/Debug-iphonesimulator/Runner.app/Frameworks/TransmitSDKUILayer.framew
               ork'
               2) That command depends on command in Target 'Runner': script
phase “[CP]
               Embed Pods Frameworks”
           
           
               warning: duplicate output file

'/Users/tahatesser/AndroidStudioProjects/flutter-ios-plugin-test/example/bui

ld/ios/Debug-iphonesimulator/Runner.app/Frameworks/TransmitSDK3.framework'
               on task: PhaseScriptExecution [CP] Embed Pods Frameworks

/Users/tahatesser/Library/Developer/Xcode/DerivedData/Runner-frphiyoyebdfgsc

csnqftaoojifv/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator
               /Runner.build/Script-BB934714184608239DF48E2D.sh (in target
'Runner' from
               project 'Runner')
               warning: duplicate output file

'/Users/tahatesser/AndroidStudioProjects/flutter-ios-plugin-test/example/bui

ld/ios/Debug-iphonesimulator/Runner.app/Frameworks/TransmitSDKUILayer.framew
               ork' on task: PhaseScriptExecution [CP] Embed Pods Frameworks

/Users/tahatesser/Library/Developer/Xcode/DerivedData/Runner-frphiyoyebdfgsc

csnqftaoojifv/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator
               /Runner.build/Script-BB934714184608239DF48E2D.sh (in target
'Runner' from
               project 'Runner')
               warning: The iOS Simulator deployment target
'IPHONEOS_DEPLOYMENT_TARGET' is
               set to 8.0, but the range of supported deployment target versions
is 9.0 to
               14.1.99. (in target 'Flutter' from project 'Pods')
               warning: The iOS Simulator deployment target
'IPHONEOS_DEPLOYMENT_TARGET' is
               set to 8.0, but the range of supported deployment target versions
is 9.0 to
               14.1.99. (in target 'transmit_test_plugin' from project 'Pods')
           
[   +8 ms] Could not build the application for the simulator.
[        ] Error launching application on iPhone 12 Pro Max.
[   +6 ms] "flutter run" took 17,343ms.

```

I tried to reproduce it from scratch by adding `TransmitSDK3` in iOS but can you please clarify step 2? As there is no code project file in ios folder  in a plugin

**Comment by kndl22** [comment] 2020-10-22 13:05
Hi @TahaTesser ,
Not sure what's step 2, and where it comes from.
I didn't create the SDK - might be some build phases within the SDK itself?

**Comment by TahaTesser** [comment] 2020-10-23 11:12
Hi @kndl22 

> Step 2. Add the .xcframework to the target under "Embed Frameworks" (xCode)
Please clarify, provide step by step reproduce of the issue, ]
Thank you

**Comment by kndl22** [comment] 2020-10-25 07:55
I mean i added both .xcframework files to the "Embed Frameworks" build phase under the target "Build Phases" in xCode.

<img width="1148" alt="Screen Shot 2020-10-25 at 9 54 25" src="https://user-images.githubusercontent.com/6260759/97101697-1eae7a80-16a8-11eb-93d3-524b105090e5.png">

**Comment by TahaTesser** [comment] 2020-10-26 12:25
Hi @kndl22 
I followed your steps and also added Embed frameworks in a new project, same out as https://github.com/flutter/flutter/issues/68605#issuecomment-714440623 when running simulator or device, which is different than your logs  from https://github.com/flutter/flutter/issues/68605#issue-725608152 




<details> 
<summary>logs</summary> 

```bash
Running "flutter pub get" in example...
[38;5;248mLaunching lib/main.dart on iPhone 12 in debug mode...[39;49m
 lib/main.dart
Warning: Missing build name (CFBundleShortVersionString).
Warning: Missing build number (CFBundleVersion).
Action Required: You must set a build name and number in the pubspec.yaml file version field before submitting to the App Store.
Xcode build done.                                            5.0s
Failed to build iOS app
Error output from Xcode build:
↳
    2020-10-26 17:47:08.754 xcodebuild[9867:228981]  DTDeviceKit: deviceType from 00008020-001059882212002E was NULL
    2020-10-26 17:47:08.885 xcodebuild[9867:228983]  DTDeviceKit: deviceType from 00008020-001059882212002E was NULL
    2020-10-26 17:47:08.885 xcodebuild[9867:228983]  DTDeviceKit: deviceType from 00008020-001059882212002E was NULL
    ** BUILD FAILED **
Xcode's output:
↳
    error: Multiple commands produce '/Users/tahatesser/AndroidStudioProjects/hello/example/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/TransmitSDKUILayer.framework':
    1) Target 'Runner' has copy command from '/Users/tahatesser/AndroidStudioProjects/hello/example/ios/TransmitSDKUILayer.xcframework/ios-i386_x86_64-simulator/TransmitSDKUILayer.framework' to '/Users/tahatesser/AndroidStudioProjects/hello/example/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/TransmitSDKUILayer.framework'
    2) That command depends on command in Target 'Runner': script phase “[CP] Embed Pods Frameworks”
    error: Multiple commands produce '/Users/tahatesser/AndroidStudioProjects/hello/example/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/TransmitSDK3.framework':
    1) Target 'Runner' has copy command from '/Users/tahatesser/AndroidStudioProjects/hello/example/ios/TransmitSDK3.xcframework/ios-i386_x86_64-simulator/TransmitSDK3.framework' to '/Users/tahatesser/AndroidStudioProjects/hello/example/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/TransmitSDK3.framework'
    2) That command depends on command in Target 'Runner': script phase “[CP] Embed Pods Frameworks”
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description
    warning: duplicate output file '/Users/tahatesser/AndroidStudioProjects/hello/example/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/TransmitSDK3.framework' on task: PhaseScriptExecution [CP] Embed Pods Frameworks /Users/tahatesser/Library/Developer/Xcode/DerivedData/Runner-gjwvenielrxfwwcpbohirzlktdyx/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Script-02B532308D466C3BDC443BEC.sh (in target 'Runner' from project 'Runner')
    warning: duplicate output file '/Users/tahatesser/AndroidStudioProjects/hello/example/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/TransmitSDKUILayer.framework' on task: PhaseScriptExecution [CP] Embed Pods Frameworks /Users/tahatesser/Library/Developer/Xcode/DerivedData/Runner-gjwvenielrxfwwcpbohirzlktdyx/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Script-02B532308D466C3BDC443BEC.sh (in target 'Runner' from project 'Runner')
Could not build the application for the simulator.
Error launching application on iPhone 12.
Exited (sigterm)

```

</details> 

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 1.22.2, on Mac OS X 10.15.7 19H2, locale en-GB)
    • Flutter version 1.22.2 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 84f3d28555 (10 days ago), 2020-10-15 16:26:19 -0700
    • Engine revision b8752bbfff
    • Dart version 2.10.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.10.0.rc.1

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.1

[✓] Connected device (1 available)
    • iPhone 12 (mobile) • 318957C3-E4BB-4B35-A3C7-14F515B0E665 • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-14-1 (simulator)

! Doctor found issues in 1 category.
```

</details> 

Can you please provide steps to reproduce the issue same way

**Comment by kndl22** [comment] 2020-10-26 17:56
Finally figured it out -> We had different CocoaPods versions.
Seems that with the latest version (1.10.0) the original error is gone and there's the one you mentioned in the comment.

So the current error is:
```
error: Multiple commands produce '/Users/cnd/AndroidStudioProjects/transmit_test_plugin/example/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/TransmitSDKUILayer.framework':
    1) Target 'Runner' has copy command from '/Users/cnd/AndroidStudioProjects/transmit_test_plugin/ios/TransmitSDKUILayer.xcframework/ios-i386_x86_64-simulator/TransmitSDKUILayer.framework' to '/Users/cnd/AndroidStudioProjects/transmit_test_plugin/example/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/TransmitSDKUILayer.framework'
    2) That command depends on command in Target 'Runner': script phase “[CP] Embed Pods Frameworks”

```

Seems that the issue was kinda popular: https://github.com/flutter/flutter/issues/20685

But so far none of the suggested solution fixed it..

**Comment by jmagman** [comment] 2020-12-01 18:57
> Add the .xcframework to the target under "Embed Frameworks" (xCode)

This is unnecessary, CocoaPods embeds the framework for you.

Closing, this 100% a CocoaPods issue, Flutter is just calling `pod install`.  You should [file an issue](https://github.com/CocoaPods/CocoaPods/issues) with them if you believe you are hitting a bug.

**Closed by jmagman** 2020-12-01 18:57 UTC
Labels: found in release: 1.22, found in release: 1.24, has reproducible steps, p: framework, platform-ios, severe: crash, tool
