### ISSUE TITLE
Atom ⌘-R fails if there's another Flutter app running in background on the Android device

### ISSUE THREAD

**Issue by collinjackson** [flutter/flutter#1988] opened 2016-02-18 18:26 UTC
It complains that the Observatory port is in use and shows a black screen (because Atom launches the app with --start-paused)

**Comment by devoncarew** [comment] 2016-02-18 19:18
Hmm, right now sky shell on android starts the observatory listening to a fixed port - 8181. We change which host port we map this to in order to support the user running multiple apps at the same time, but just one app per device. Should we or do we need to support running multiple apps per device? It would require a bit more additional plumbing and complexity.

**Comment by collinjackson** [comment] 2016-02-18 19:22
I think it's reasonable to expect that developers will want to run multiple apps per device. I certainly do.

**Comment by johnmccutchan** [comment] 2016-02-18 20:34
I'll take this one.

**Comment by devoncarew** [comment] 2016-02-18 20:45
The tricky part here will be communicating the port number back to the clients that need to know it.

**Comment by abarth** [comment] 2016-02-18 20:49
We could pick a random one and retry on failure.

**Comment by eseidelGoogle** [comment] 2016-03-04 17:24
@turnidge just hit this as well.

**Comment by eseidelGoogle** [comment] 2016-03-04 17:25
Is this a dupe of https://github.com/flutter/flutter/issues/2188 ?

**Comment by collinjackson** [comment] 2016-03-04 18:33
Yes, or rather #2188 is a dupe of this

**Closed** 2016-03-17 21:24 UTC
Labels: affects: dev experience, affects: tools, ⚠ bug

**Comment by eseidelGoogle** [comment] 2016-03-17 21:32
:heart: Thank you @johnmccutchan!

**Comment by sethladd** [comment] 2016-03-17 22:11
:+1:
