### ISSUE TITLE
Memory leak on iOS when show animate webp image  on flutter channel beta

### ISSUE THREAD

**Issue by wasabia** [flutter/flutter#65362] opened 2020-09-08 04:53 UTC
on Flutter Channel stable is ok

```
[✓] Flutter (Channel beta, 1.21.0-9.2.pre, on Mac OS X 10.15.6 19G73, locale zh-Hans-CN)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.48.2)
[✓] Connected device (2 available)
```

##example code
```

import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

class DemoTest2Page extends StatefulWidget {
  DemoTest2Page({Key key}) : super(key: key);
  @override
  createState() => DemoTest2PageState();
}

class DemoTest2PageState extends State<DemoTest2Page> {

  @override
  void initState() {
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text("demo"),),
      body: _build(context)
    );
  }

  _build(BuildContext context) {
    return ListView.builder(
      itemBuilder: (BuildContext context, int index) {
        return Container(
          child: Image.asset("assets/1.webp", width: 200, height: 200, fit: BoxFit.contain,)
        );
      },
      itemCount: 20
    );
  }

}


```

[1.webp.zip](https://github.com/flutter/flutter/files/5186098/1.webp.zip)

**Comment by darshankawar** [comment] 2020-09-08 07:05
Hi @wasabia,
Can you provide `flutter run --verbose` and any screenshots / logs that shows the memory leak ?
Thanks.

**Comment by wasabia** [comment] 2020-09-08 08:56
Hi @darshankawar 
<img width="1137" alt="WX20200908-165553@2x" src="https://user-images.githubusercontent.com/1768228/92455419-3911bf00-f1f4-11ea-9c3c-52332b90c669.png">

**Comment by wasabia** [comment] 2020-09-08 08:58
[flutter_run_verbose.log](https://github.com/flutter/flutter/files/5187230/flutter_run_verbose.log)

**Comment by darshankawar** [comment] 2020-09-08 14:13
I verified this on latest beta  and stable on iPhone 6s and saw leak entries while scrolling the app, but not sure if that's expected or a bug.

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel beta, 1.21.0-9.2.pre, on Mac OS X 10.15.2 19C57, locale
    en-US)
    • Flutter version 1.21.0-9.2.pre at
      /Users/deeptibelsare/Documents/Fluttersdk/flutter
    • Framework revision 81a45ec2e5 (11 days ago), 2020-08-27 14:14:33 -0700
    • Engine revision 20a9531835
    • Dart version 2.10.0 (build 2.10.0-7.3.beta)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/deeptibelsare/Library/Android/sdk
    • Platform android-30, build-tools 29.0.3
    • ANDROID_HOME = /Users/deeptibelsare/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/deeptibelsare/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

 
[✓] Connected device (3 available)            
    • SM A260G (mobile) • 5200763ebcfa861f • android-arm    • Android 8.1.0 (API
      27)
    • Web Server (web)  • web-server       • web-javascript • Flutter Tools
    • Chrome (web)      • chrome           • web-javascript • Google Chrome
      85.0.4183.83

! Doctor found issues in 1 category.
```

</details>

![Screen Shot 2020-09-08 at 7 26 45 PM](https://user-images.githubusercontent.com/67046386/92487816-628a1500-f20b-11ea-875c-31a419750d7a.png)
![Screen Shot 2020-09-08 at 7 39 35 PM](https://user-images.githubusercontent.com/67046386/92487831-661d9c00-f20b-11ea-8a0e-036f42b0bb37.png)

Keeping this issue open for further analysis.

**Comment by wasabia** [comment] 2020-09-08 14:36
i do not scrolling the app just open the page, the memory keep grow,
maybe it is webp image problem

**Comment by dnfield** [comment] 2020-09-09 23:02
@darshankawar - those leaks are a problem but very unlikely the cause of this issue. There are a few small random leaks from the Dart VM last I was checking that on iOS, but it wasn't clear where they were coming from and they're very small. We should file a separate bug for that if there isn't one already.

It would be instructive to see if this problem goes away if a GC is triggered, although I'd expect this app to be GCing before the growth gets as high as it is.

I'll try to take a look at this today.

**Comment by dnfield** [comment] 2020-09-09 23:59
I'm not able to reproduce this issue on master. Can you try again?

**Comment by wasabia** [comment] 2020-09-17 09:11
this bug has gone on master channel

✓] Flutter (Channel master, 1.22.0-10.0.pre.221, on Mac OS X 10.15.6 19G73 x86_64, locale zh-Hans-CN)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.49.0)
[✓] Connected device (4 available)

**Comment by darshankawar** [comment] 2020-09-17 13:24
@wasabia thanks for confirming.
Given you last message, I am going ahead and closing this. If you disagree, write in comments and I'll reopen.
Thanks.

**Closed by darshankawar** 2020-09-17 13:24 UTC
Labels: a: images, framework, perf: memory, platform-ios
