### ISSUE TITLE
local_auth: App crashes on android 8.1 while authenticate

### ISSUE THREAD

**Issue by fabianbrandscheid** [flutter/flutter#94165] opened 2021-11-24 14:41 UTC
Hi,

when I try to call the authenticate method from the local_auth plugin my flutter app crashes.
Here is a small code snippet:
```

final _androidAuthMessages = AndroidAuthMessages(
    cancelButton: Txt.shared.cancel.translate,
    biometricNotRecognized: Txt.login.biometricNotRecognized.translate,
    biometricSuccess: Txt.login.biometricSuccess.translate,
    biometricHint: Txt.login.biometricHint.translate,
    signInTitle: Txt.login.signInTitle.translate,
    biometricRequiredTitle: Txt.login.biometricRequiredTitle.translate,
    deviceCredentialsRequiredTitle:
        Txt.login.deviceCredentialsRequiredTitle.translate,
    deviceCredentialsSetupDescription:
        Txt.login.deviceCredentialsSetupDescription.translate,
    goToSettingsButton: Txt.login.goToSettingsButton.translate,
    goToSettingsDescription: Txt.login.goToSettingsDescriptionAndroid.translate,
  );

  final _iOSAuthMessages = IOSAuthMessages(
    cancelButton: Txt.shared.cancel.translate,
    lockOut: Txt.login.lockOutIOS.translate,
    goToSettingsButton: Txt.login.goToSettingsButton.translate,
    goToSettingsDescription: Txt.login.goToSettingsDescriptionIOS.translate,
  );
// --> The app crashes at this call
  this.localAuthentication.authenticate(
          localizedReason: localizedReason,
          useErrorDialogs: true,
          androidAuthStrings: this._androidAuthMessages,
          iOSAuthStrings: this._iOSAuthMessages);
```

I tested the behaviour with many devices. It occurs on a Samsung Galaxy S7 and a Motorola G5. Both devices have android 8.1. With iOS or higher Android-Versions the use case works always fine.

The following error is logged to the console when the app crashes:

```
W/ResourceType(24847): Invalid package identifier when getting bag for resource number 0x00000526
D/AndroidRuntime(24847): Shutting down VM
E/AndroidRuntime(24847): FATAL EXCEPTION: main
E/AndroidRuntime(24847): Process: ******, PID: *****
E/AndroidRuntime(24847): java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
E/AndroidRuntime(24847): 	at androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java:846)
E/AndroidRuntime(24847): 	at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:809)
E/AndroidRuntime(24847): 	at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:696)
E/AndroidRuntime(24847): 	at androidx.appcompat.app.AppCompatDialog.setContentView(AppCompatDialog.java:95)
E/AndroidRuntime(24847): 	at androidx.appcompat.app.AlertController.installContent(AlertController.java:232)
E/AndroidRuntime(24847): 	at androidx.appcompat.app.AlertDialog.onCreate(AlertDialog.java:279)
E/AndroidRuntime(24847): 	at android.app.Dialog.dispatchOnCreate(Dialog.java:403)
E/AndroidRuntime(24847): 	at android.app.Dialog.show(Dialog.java:302)
E/AndroidRuntime(24847): 	at androidx.fragment.app.DialogFragment.onStart(DialogFragment.java:687)
E/AndroidRuntime(24847): 	at androidx.fragment.app.Fragment.performStart(Fragment.java:3021)
E/AndroidRuntime(24847): 	at androidx.fragment.app.FragmentStateManager.start(FragmentStateManager.java:589)
E/AndroidRuntime(24847): 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:300)
E/AndroidRuntime(24847): 	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
E/AndroidRuntime(24847): 	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
E/AndroidRuntime(24847): 	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
E/AndroidRuntime(24847): 	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:524)
E/AndroidRuntime(24847): 	at android.os.Handler.handleCallback(Handler.java:790)
E/AndroidRuntime(24847): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(24847): 	at android.os.Looper.loop(Looper.java:164)
E/AndroidRuntime(24847): 	at android.app.ActivityThread.main(ActivityThread.java:6626)
E/AndroidRuntime(24847): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(24847): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
E/AndroidRuntime(24847): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)
I/zygote  (24847): Do full code cache collection, code=251KB, data=207KB
I/zygote  (24847): After code cache collection, code=233KB, data=168KB
Lost connection to device.
```

many thanks for your help!

**Comment by danagbemava-nc** [comment] 2021-11-25 08:04
Duplicate of #https://github.com/flutter/flutter/issues/55638

Kindly follow up there for more information. 

You can also check https://github.com/flutter/flutter/issues/85536 & https://github.com/flutter/flutter/issues/81127
to see if they help fix your issue. 

Closing from here. 

Thank you

**Closed by danagbemava-nc** 2021-11-25 08:04 UTC
Labels: in triage
