### ISSUE TITLE
it's important for communicate with js by setcookies on webview_flutter

### ISSUE THREAD

**Issue by twopai** [flutter/flutter#39805] opened 2019-09-04 08:38 UTC
most of flutter webview, their all not method for the setcookies ,but communicate with js through the cookies before the webview_flutter load , so can you add the api directly or give me some codes for setcookies ? help me thanks !
 
i find the answer for most people and website about the question，but no answers ！

**Comment by BondarenkoStas** [comment] 2019-09-04 10:05
Duplicate of #27597
@twopai Please check there are two PRs, probably they may solve your problem. 
But so far right, the features are not yet merged.
Closing the issue if you don't mind.

**Closed by BondarenkoStas** 2019-09-04 10:05 UTC

**Comment by twopai** [comment] 2019-09-05 01:20
> Duplicate of #27597
> @twopai Please check there are two PRs, probably they may solve your problem.
> But so far right, the features are not yet merged.
> Closing the issue if you don't mind.

sorry,the problem solved on the webview_flutter  onWebViewCreated,but i need to as params for the webview_flutter before it load

**Comment by twopai** [comment] 2019-09-05 01:21
> Duplicate of #27597
> @twopai Please check there are two PRs, probably they may solve your problem.
> But so far right, the features are not yet merged.
> Closing the issue if you don't mind.

`WebView(
          initialUrl: model.getUser.landingPage,
          javascriptMode: JavascriptMode.unrestricted,
          onWebViewCreated: (WebViewController wvc) {
            wvc.evaluateJavascript('document.cookie = "SESSION-${model.getUser.client}=${model.getUser.token}"; path=/');
            wvc.evaluateJavascript('sessionStorage.setItem("${model.getUser.client}_live_token", "${model.getUser.token}")');
          },
        )`

**Comment by wbingz0719** [comment] 2019-10-11 02:30
Has this problem been solved? I haven't seen a way to set cookies yet.

**Comment by VadimOsovsky** [comment] 2019-11-07 13:17
@twopai "Uncaught SecurityError: Failed to read the 'sessionStorage' property from 'Window': Access is denied for this document."
