### ISSUE TITLE
on iOS mobile  the keyboard blocks the input box

### ISSUE THREAD

**Issue by steven-gao** [flutter/flutter#139794] opened 2023-12-08 09:56 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1 i open a web page on ios phone
2 i clicked the inputbox widget

### Expected results

the input box will be propped up

### Actual results

 keyboard blocks the input box

### Code sample

<details><summary>Code sample</summary>

```dart

// webview  page
class TradeH5Page extends BaseCommonView<CommonH5Controller> {
  TradeH5Page({super.key});

  bool? get isHiddenNav => false;
  bool? get resizeToAvoid => false;

  double get safeBarH => super.safeBarH;
  Color? get navColor => Colors.white;
  String? get navTitle => Get.parameters['title'] ?? "";
  Color? get navTitleColor => Colors.black;
  double? get navTitleSize => 18.sp;
  // 为了展示H5页面状态栏颜色设置成纯白
  double? get toolbHeight => Get.parameters['hideHeader'] == "true" ? 1 : 48;
  Widget? get leftButton =>
      Get.parameters['hideHeader'] == "true" ? Container() : buildBackWidget();

  double keyHeight = 0.0;

  @override
  Widget buildContent() {
    return GetBuilder<CommonH5Controller>(
      init: CommonH5Controller(),
      builder: (controller) => creatCommonView(
        controller,
        CommWidgetManager.CommPageScaffoldWidget(
          Get.context!,
          isShowBg: false,
          body: 
          SafeArea(
            child: BaseWebView(
              urlPath: Get.parameters['url'],
              doInnerBackLogic: true,
              hideHeader: Get.parameters['hideHeader'] == "true",
            ),
          ),
        ),
      ),
    );
  }
}



class BaseWebView extends StatefulWidget {
  static bool isOpenAnyWebPage = false;
  final String? urlPath;
  final bool doInnerBackLogic;
  final bool hideHeader;
  const BaseWebView(
      {super.key,
      this.urlPath,
      this.doInnerBackLogic = true,
      this.hideHeader = true});

  @override
  State<BaseWebView> createState() => _WebViewExampleState();
}

class _WebViewExampleState extends State<BaseWebView>
    with WidgetsBindingObserver {
  late final WebViewController _controller;

  String title = "";
  int eCode = 0;
  double keyboardHeight = 0.0;
  double dy = 0;
  bool isScrolled = false;

  @override
  void didChangeMetrics() {
    super.didChangeMetrics();

    WidgetsBinding.instance.addPostFrameCallback((_) {
      setState(() {
        // keyboardHeight = MediaQuery.of(context).viewInsets.bottom;
        keyboardHeight = MediaQuery.of(context).viewInsets.bottom;
        print(
            '99 MediaQuery.of(context).viewInsets.bottom:${MediaQuery.of(context).viewInsets.bottom}');
      });
      if (keyboardHeight > 0) {
      
        if (GetPlatform.isIOS) {
          if(!isScrolled){
            isScrolled = true;
              _controller.scrollTo(0, 1000);
          }
        } else if (GetPlatform.isAndroid) {

          _controller.getScrollPosition().then((value) {
            print(
                '55 _controller.getScrollPosition():${value.dx} / ${value.dy}');
            dy = value.dy;
          });
        }
      } else {

        if (keyboardHeight <= 0) {
          isScrolled = false;
          _controller.scrollTo(0, dy.toInt());
        }
      }
    });
  }

  @override
  void dispose() {
    super.dispose();
    WidgetsBinding.instance.removeObserver(this);
  }

  @override
  void initState() {
    super.initState();

    WidgetsBinding.instance.addObserver(this);
    // print('open web page url:${widget.urlPath}');
    BaseWebView.isOpenAnyWebPage = true;

    late final PlatformWebViewControllerCreationParams params;
    if (WebViewPlatform.instance is WebKitWebViewPlatform) {
      params = WebKitWebViewControllerCreationParams(
        allowsInlineMediaPlayback: true,
        mediaTypesRequiringUserAction: const <PlaybackMediaTypes>{},
      );
    } else {
      params = const PlatformWebViewControllerCreationParams();
    }

    //根据不同平台初始化不同的参数来构造controller，增加后面的回调是为了通过权限申请。否则人脸识别调不起来
    final WebViewController controller =
        WebViewController.fromPlatformCreationParams(
      params,
      onPermissionRequest: (request) {
        request.grant();
      },
    );
    if (controller.platform is AndroidWebViewController) {
      AndroidWebViewController.enableDebugging(true);
      (controller.platform as AndroidWebViewController)
          .setMediaPlaybackRequiresUserGesture(false);
    }

    // NavigationDelegate 是网页进度的回调，也可以拦截url
    // 例如想要通过webview打开app的原生页面，通过约定好的链接，拦截到指定链接后可跳转到原生页面。

    controller
      ..setJavaScriptMode(JavaScriptMode.unrestricted)
      ..setBackgroundColor(const Color(0x00000000))
      ..setNavigationDelegate(
        NavigationDelegate(
          onProgress: (int progress) {
            debugPrint('WebView is loading (progress : $progress%)');
          },
          onPageStarted: (String url) {
            debugPrint('Page started loading: $url');
          },
          onPageFinished: (String url) {
            debugPrint('Page finished loading: $url');
          },
          onWebResourceError: (WebResourceError error) {
            handleError(error);
            print('''
            Page resource error:
            code: ${error.errorCode}
            description: ${error.description}
            ''');
          },
          onNavigationRequest: (NavigationRequest request) {
            //对于需要拦截的操作 做判断
            String? urlPath = Uri.decodeFull(request.url);

            //做拦截处理
            if (urlPath.startsWith('jscallnative')) {
              Bridge.preventUrl(urlPath, controller);
              return NavigationDecision.prevent;
            }
            return NavigationDecision.navigate;
          },
          onUrlChange: (UrlChange change) {
            // eCode = 0;
            print('url change to ${change.url}');
          },
        ),
      )
      //加载网页
      ..loadRequest(Uri.parse(widget.urlPath ?? " "));

    // 判断controller类型
    if (controller.platform is AndroidWebViewController) {
      AndroidWebViewController.enableDebugging(true);
      (controller.platform as AndroidWebViewController)
          .setMediaPlaybackRequiresUserGesture(false);
      (controller.platform as AndroidWebViewController).setTextZoom(100);
    }

    _controller = controller;
  }

  void reloadPage() {
    setState(() {
      eCode = 0;
    });
    // 如果调用reload() 方法会默认加载本地的网页---空白页
    _controller.loadRequest(Uri.parse(widget.urlPath ?? " "));
  }

  handleError(WebResourceError error) {
    setState(() {
      eCode = error.errorCode;
    });
    // _controller.loadHtmlString(blankPage);
  }

  Future<bool> _willPopCallback() async {
    if (widget.doInnerBackLogic) {
      ///检查h5链接是否有上一页
      Future<bool> canGoBack = _controller.canGoBack();
      return canGoBack.then((isCanGoBack) {
        if (isCanGoBack) {
          ///有则回退至h5上一页
          _controller.goBack();
          return false;
        } else {
          ///无则返回app上一页
          back();
          return true;
        }
      });
    } else {
      ///不需要WebView内部判断返回逻辑的则 直接返回到app
      back();
      return true;
    }
  }

  back() {
    Get.back();
  }

  @override
  Widget build(BuildContext context) {
    return WillPopScope(
      onWillPop: () {
        return _willPopCallback();
      },
      child: eCode == -2
          ? WebViewUtils.buildErrorContent(
              reloadPage, eCode, widget.hideHeader, _controller)
          :
          SizedBox(
              width: Get.width,
              height: Get.height,
              child: Container(
                child: Column(
                  children: [
                    Expanded(
                      child:
                       WebViewWidget(
                        controller: _controller,
                        gestureRecognizers: [
                          Factory<LongPressGestureRecognizer>(
                              () => LongPressGestureRecognizer())
                        ].toSet(),
                      ),
                    ),
                    SizedBox(
                      height: keyboardHeight,
                      child: Container(),
                    )
                  ],
                ),
              ),
            ),
    );
  }
}

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

https://github.com/flutter/flutter/assets/4360916/070d1564-004d-4b69-9a79-8ec9d2275b80

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.13.1, on macOS 13.5.1 22G90 darwin-x64, locale zh-Hans-CN)
    • Flutter version 3.13.1 on channel stable at /Users/gaotaiwen/Desktop/flutter-sdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e1e47221e8 (4 months ago), 2023-08-22 21:43:18 -0700
    • Engine revision b20183e040
    • Dart version 3.1.0
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/gaotaiwen/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/gaotaiwen/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] IntelliJ IDEA Community Edition (version 2022.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.84.1)
    • VS Code at /Users/gaotaiwen/Desktop/Visual Studio Code.app/Contents
    • Flutter extension version 3.78.0

[✓] Connected device (3 available)
    • iPhone (2) (mobile) • 00008030-000C6D9434E0802E • ios            • iOS 15.4.1 19E258
    • macOS (desktop)     • macos                     • darwin-x64     • macOS 13.5.1 22G90 darwin-x64
    • Chrome (web)        • chrome                    • web-javascript • Google Chrome 120.0.6099.62
[!] Network resources                                        
    ✗ A cryptographic error occurred while checking "https://pub.dev/": Connection terminated during handshake
      You may be experiencing a man-in-the-middle attack, your network may be compromised, or you may have malware installed on your
      computer.
    ✗ A network error occurred while checking "https://maven.google.com/": Operation timed out
    ✗ A network error occurred while checking "https://github.com/": Operation timed out

! Doctor found issues in 1 category.
```

</details>

**Comment by steven-gao** [comment] 2023-12-08 10:01
above my code :
if (GetPlatform.isIOS) {
          if(!isScrolled){
            isScrolled = true;
              _controller.scrollTo(0, 1000);
          }
        } 
this block is not effect,you can ignore it.

**Comment by darshankawar** [comment] 2023-12-08 12:25
@steven-gao 
Can you provide complete runnable reproducible code sample without using any third party package implementation ? Just provide minimal but complete code so that we can directly use it to verify it further.

**Comment by steven-gao** [comment] 2023-12-08 14:46
> @steven-gao Can you provide complete runnable reproducible code sample without using any third party package implementation ? Just provide minimal but complete code so that we can directly use it to verify it further.

It is too difficult to remove third-party code. I'm so sorry. If you want to reproduce it, you can write a web page that is longer than one screen and put an input box at the bottom. Then use the flutter_webview library to open it on the Apple phone. You can see that the keyboard will cover the input box

**Comment by darshankawar** [comment] 2023-12-11 05:47
@steven-gao 
See if you are hitting https://github.com/flutter/flutter/issues/112354 or not.

**Comment by steven-gao** [comment] 2023-12-13 04:23
> @steven-gao See if you are hitting #112354 or not.

thank you ,i will try this .and i will feedback to you.

**Comment by steven-gao** [comment] 2023-12-13 11:38
> @steven-gao See if you are hitting #112354 or not.

 _con .runJavascriptReturningResult("document.documentElement.scrollHeight;")  this "runJavascriptReturningResult" method is not found ,can you tell me an alternative method？

**Comment by steven-gao** [comment] 2023-12-14 02:57
> @steven-gao See if you are hitting #112354 or not.

unfortunately，this not solve the problem,i download the latest demo which path is '/Users/gaotaiwen/Downloads/packages-main/packages/webview_flutter/webview_flutter',and use the test url
'https://mp.yeepay.com/boss-app-access/merchantManage/business?update=Y', the keyboad still blocks the input box.
can you have another solution？ thank your for your time.

**Comment by steven-gao** [comment] 2023-12-14 03:01
https://github.com/flutter/flutter/assets/4360916/d521a3e4-8eae-4428-bd5b-5119c7509c0a



> @steven-gao See if you are hitting #112354 or not.

i recorded the demo project which like. could you see it first?

**Comment by darshankawar** [comment] 2023-12-14 05:50
@steven-gao 
Can you try by using this property and check if it helps ? 
https://api.flutter.dev/flutter/material/Scaffold/resizeToAvoidBottomInset.html

**Comment by steven-gao** [comment] 2023-12-19 10:33
> @steven-gao Can you try by using this property and check if it helps ? https://api.flutter.dev/flutter/material/Scaffold/resizeToAvoidBottomInset.html

this not work，this attribute default value is true。

**Comment by darshankawar** [comment] 2023-12-19 12:44
> If you want to reproduce it, you can write a web page that is longer than one screen and put an input box at the bottom. Then use the flutter_webview library to open it on the Apple phone. You can see that the keyboard will cover the input box

I tried to come up with a runnable code based on it, but not sure if it represents the correct case as yours as I am not sure how would `webview_flutter` come into picture in below scenario. 

In order to make the issue actionable, please provide us a runnable reproducible code sample.

<details>
<summary> runnable code sample </summary>

```

import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: SingleChildScrollView(
          child: Column(
            children: [
              Container(
                  width: MediaQuery.of(context).size.width,
                  height: 600,
                  color: Colors.red),
              const TextField()
            ],
          )),
    );
  }
}


```

</details>

**Comment by steven-gao** [comment] 2023-12-20 05:27
> > If you want to reproduce it, you can write a web page that is longer than one screen and put an input box at the bottom. Then use the flutter_webview library to open it on the Apple phone. You can see that the keyboard will cover the input box
> 
> I tried to come up with a runnable code based on it, but not sure if it represents the correct case as yours as I am not sure how would `webview_flutter` come into picture in below scenario.
> 
> In order to make the issue actionable, please provide us a runnable reproducible code sample.
> 
> runnable code sample

my test html code:
`<!DOCTYPE html>

<html>
	<head>
		<style>
			.form-control {
	display:block;
	width:100%;
	height:34px;
	padding:6px 12px;
	font-size:14px;
	line-height:1.42857143;
	color:#555;
	background-color:#fff;
	border:1px solid #ccc;
	border-radius:4px;
	box-shadow:inset 0 1px 1px rgb(0,0,0,.08);
	transition:border-color ease-in-out .15s,box-shadow ease-in-out .15s;
}
.form-control:focus {
	box-shadow:none;
}
.form-control:focus {
	border-color:#66afe9;
	outline:0;
	box-shadow:inset 0 1px 1px rgb(0,0,0,.08),0 0 8px rgb(102,175,233,.6);
}
.block-area-box label {
	margin:0px 0px 5px 0px;
	font-weight:normal;
}
label {
	font-size:12px;
	color:#333;
}
body {
	margin:0px;
	padding:1px;
}
label {
	display:inline-block;
	max-width:100%;
	margin-bottom:5px;
	font-weight:700;
}
ul,ol,li {
	list-style:none
}
page-content {
	margin-top:15px
}
.list-paddingleft-2 {
	margin:0;
	padding:0;
}
img {
	width:100%;
}
</style>
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
	</head>
	<body>
		<p>This is a paragraph.</p>
		<p>This is a paragraph.</p>
		<p>This is a paragraph.</p>
		<p>This is a paragraph.</p>
		<p>This is a paragraph.</p>
		<p>This is a paragraph.</p>
		<p>This is a paragraph.</p>
		<p>This is a paragraph.</p>
		<p>This is a paragraph.</p>
		<p>This is a paragraph.</p>
		<p>This is a paragraph.</p>
		<p>This is a paragraph.</p>
		<p>This is a paragraph.</p>

		<div class="list-paddingleft-2">
			<ul class=" list-paddingleft-2">
				<li>
					<p>
						<label>
							<span class="star">*</span>Origin(Web App) Email:
						</label>
						<input tipid="email_errortip" type="text" datatype="*" placeholder="Origin (Web App) Email" nullmsg="email must be enter." sucmsg=" " name="Email" class="add-options-input form-control not-null">
					</p>
				</li>
				<li>
					<p>
						<label>
							<span class="star">*</span>Origin(Web App) Password:
						</label>
						<input tipid="password_errortip" type="password" datatype="*" placeholder="Origin (Web App) Password" nullmsg="password must be enter." sucmsg=" " name="Password" class="add-options-input form-control not-null">
					</p>
				</li>
				<li>
					<p>
						<label>
							<span class="star">*</span>Backup Code:
						</label>
						<textarea style="height: 135px;resize: none;" placeholder="Please enter Backup Code!" tipid="Backup Code_errortip" type="textarea" datatype="*" nullmsg="Backup Code must be enter." sucmsg=" " name="BackupCode" class="add-options-input form-control not-null"></textarea>
					</p>
				</li>
			</ul>
		</div>
	</body>
</html>`

**Comment by steven-gao** [comment] 2023-12-20 05:29
> > If you want to reproduce it, you can write a web page that is longer than one screen and put an input box at the bottom. Then use the flutter_webview library to open it on the Apple phone. You can see that the keyboard will cover the input box
> 
> I tried to come up with a runnable code based on it, but not sure if it represents the correct case as yours as I am not sure how would `webview_flutter` come into picture in below scenario.
> 
> In order to make the issue actionable, please provide us a runnable reproducible code sample.
> 
> runnable code sample

i upload the html file which name input.html
[input.html.zip](https://github.com/flutter/flutter/files/13723352/input.html.zip)

**Comment by steven-gao** [comment] 2023-12-20 05:51
> > If you want to reproduce it, you can write a web page that is longer than one screen and put an input box at the bottom. Then use the flutter_webview library to open it on the Apple phone. You can see that the keyboard will cover the input box
> 
> I tried to come up with a runnable code based on it, but not sure if it represents the correct case as yours as I am not sure how would `webview_flutter` come into picture in below scenario.
> 
> In order to make the issue actionable, please provide us a runnable reproducible code sample.
> 
> runnable code sample

i tested two phones ,one is huawei,android 10,the keyboard is not block the input box,and the other one is redmi,the keyboard blcoked the input box

https://github.com/flutter/flutter/assets/4360916/96790de0-df04-4d8a-9cf9-5c07095876c2


https://github.com/flutter/flutter/assets/4360916/a009243a-3660-4bd7-b715-3cd018c1de53

**Comment by dam-ease** [comment] 2023-12-20 07:52
Hi @steven-gao
This seems similar to https://github.com/flutter/flutter/issues/140121 you filed, can we keep up the conversation in one of these issues as keeping both will result in one being a duplicate of the other?

Closing this in favor of https://github.com/flutter/flutter/issues/140121, if you disagree, please comment and I'll reopen this.
Thank you!

**Comment by steven-gao** [comment] 2023-12-22 07:56
> Hi @steven-gao This seems similar to #140121 you filed, can we keep up the conversation in one of these issues as keeping both will result in one being a duplicate of the other?
> 
> Closing this in favor of #140121, if you disagree, please comment and I'll reopen this. Thank you!

OK，i will close #140121  this issue。

**Comment by steven-gao** [comment] 2023-12-27 12:18
@darshankawar have you any progress？

**Comment by dam-ease** [comment] 2023-12-28 07:54
Hi @steven-gao.
I see you closed https://github.com/flutter/flutter/issues/140121, kindly reopen that instead for further discussion on this issue. This was closed in favor of the issue you closed.
Kindly respond to https://github.com/flutter/flutter/issues/140121.

**Comment by steven-gao** [comment] 2024-01-05 08:10
> Hi @steven-gao. I see you closed #140121, kindly reopen that instead for further discussion on this issue. This was closed in favor of the issue you closed. Kindly respond to #140121.
sorry,i am  confused ,which iusse should i close?

**Comment by steven-gao** [comment] 2024-01-05 08:12
#140121 issue i closed ,but i can't reopent it. can we discuss on this issue?

**Comment by darshankawar** [comment] 2024-01-05 12:42
Reopening this for further analysis.

**Comment by darshankawar** [comment] 2024-01-05 12:53
@steven-gao 
I think https://github.com/flutter/flutter/issues/140953 is similar to the one you reported. So please follow-up in it for further updates. Closing this as a duplicate. If you disagree, write in comments and I'll reopen it.

**Closed by darshankawar** 2024-01-05 12:53 UTC
Labels: in triage
