### ISSUE TITLE
Why my bundle apk option is not working I had search this solution everywhere but nothing is getting fixed

### ISSUE THREAD

**Issue by tiklak** [flutter/flutter#63758] opened 2020-08-14 10:11 UTC
![PicsArt_08-14-03 40 09](https://user-images.githubusercontent.com/40028989/90238982-775dcd80-de44-11ea-9cd6-b81468d96579.png)

I had search and tried the solution everywhere but nothing worked for me I want to release my application to play store please help

**Comment by TahaTesser** [comment] 2020-08-14 13:12
Hi @tiklak 
You can build bundle by executing `flutter build bundle`

Following the indication of [jetbrains' Flutter plugin](https://plugins.jetbrains.com/plugin/9212-flutter), the correct way to address the problem is to open an issue in the dedicated [repository](https://github.com/flutter/flutter-intellij/issues).
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2020-08-14 13:12 UTC
