### ISSUE TITLE
Add ColorFilter.cube to apply 3D lookup table

### ISSUE THREAD

**Issue by cbenhagen** [flutter/flutter#55738] opened 2020-04-27 14:12 UTC
Blocked by https://github.com/flutter/flutter/issues/94235

## Use case
It would be nice to be able to add 3D LUT based, artistic color filters on any widget. Especially `Image`, `VideoPlayer` and `CameraPreview` widgets. 3D Lookup Tables are heavily used in the film and game industry for color correction and creative color grading. On mobile platforms they would be especially useful for all kinds of photo / video editor type tools.

![Photo by Caique Silva on Unsplash](https://user-images.githubusercontent.com/814785/80381428-3647aa80-88a1-11ea-9649-8c2171eb1115.jpg)
*image by [Caique Silva][caique-silva-page] LUTs: KURO B&W by [David Morgan Jones][david-morgan-jones-bw-free], Arabica 12 and Lenox 340 by [rocketstock][rocket-stock-35-free]*

### Alternatives
* On still images the [dart_lut plugin](https://github.com/NiKoTron/dart-lut) could be used.

* On iOS and macOS one could fork the video_player plugin and use a [CIColorCube](https://developer.apple.com/library/archive/documentation/GraphicsImaging/Reference/CoreImageFilterReference/index.html#//apple_ref/doc/filter/ci/CIColorCube) filter.

`ColorFilter.matrix` can not be used as an alternative as it is not as precise.

## Proposal
Convince the Skia team to revert https://github.com/google/skia/commit/efaad3cd53330f063e6feaee8b14ad43ca251184 so `SkColorCubeFilter` could be used by Flutter. Relevant discussion could be found [here](https://groups.google.com/d/topic/skia-discuss/Y1izDbocJf4/discussion).

[david-morgan-jones-bw-free]: https://davidmorganjones.net/blog/kuro-lut-free-dramatic-black-and-white-lut/
[rocket-stock-35-free]: https://www.rocketstock.com/free-after-effects-templates/35-free-luts-for-color-grading-videos/
[caique-silva-page]: https://unsplash.com/@caiqueportraits?utm_medium=referral&utm_campaign=photographer-credit&utm_content=creditBadge

**Comment by cbenhagen** [comment] 2020-05-21 07:41
@iapicca I don't think this can be done in a package. As far as I understand it would need to be added to the engine and even to Skia. If you see a way to do it from a package or in a simpler way please let me know.

**Comment by cbenhagen** [comment] 2020-05-31 10:31
Skia team kindly added an example of how to implement a 3D LUT filter using `SkRuntimeEffect`: https://github.com/google/skia/blob/master/gm/runtimeshader.cpp#L241-L333

**Comment by cbenhagen** [comment] 2021-11-26 09:33
Adding a 3D LUT is now possible in the main and dev branch using `FragmentProgram` with an `ImageShader` and `toImage` methods of the render layer as an input.

Creating a `ColorFilter` needs some more work and is tracked in https://github.com/flutter/flutter/issues/94235.

**Comment by zanderso** [comment] 2021-12-01 23:12
From feature request triage: The equivalent functionality should be provided using a fragment program rather than the old Skia API.

**Comment by chriscraws** [comment] 2021-12-13 16:48
@zanderso it seems like the main blocker here of using a FragmentProgram versus a ColorFilter is that there are no ways to synchronously obtain `Image` objects holding the content of a widget that can be provided to shaders. (every `toImage` method returns a `Future<Image>`. To me this implies that using a FragmentProgram to process the contents of a widget must be non-realtime - Providing an alternate, synchronous `toImage` method or allowing the construction of `ColorFilter`s are the only solutions I'm aware of right now, is there an alternative?

**Comment by esDotDev** [comment] 2022-03-10 19:31
Are there any code examples of how to apply a LUT to a Widget?

**Comment by cbenhagen** [comment] 2022-11-16 16:15
On flutter beta and master there are [`RenderRepaintBoundary.toImageSync`](https://master-api.flutter.dev/flutter/rendering/RenderRepaintBoundary/toImageSync.html)  and friends.

**Comment by jonahwilliams** [comment] 2024-08-13 03:40
We're not going to write this particular filter in the engine, but we will be exposing mechanisms to make writing these filters much simpler. Closing as dupe of https://github.com/flutter/flutter/issues/16296

**Closed by jonahwilliams** 2024-08-13 03:40 UTC
Labels: c: new feature, framework, engine, a: images, c: proposal, P3, team-engine, triaged-engine
