### ISSUE TITLE
dart analyzer does not consider Row, Flexible etc. as Widget

### ISSUE THREAD

**Issue by vy0592** [flutter/flutter#5968] opened 2016-09-20 21:35 UTC
Something similar to the following would cause dart analyzer complaining about type error.

var widget = new Row(...);
...
widget = new Container(...);

**Comment by abarth** [comment] 2016-09-20 21:38
`A value of type 'Container' cannot be assigned to a variable of type 'Row'`

/cc @pq

**Comment by abarth** [comment] 2016-09-20 21:39
@vy0592 You can work around the issue by using the type `Widget` instead of `var`.

**Comment by Hixie** [comment] 2016-09-20 21:57
I think this is because strong mode changes "var"'s semantics. In non-strong mode "var" means "dynamic"; in strong mode, "var" means "auto".

**Comment by pq** [comment] 2016-09-20 22:30
I'm with @Hixie on this one.

**Comment by Hixie** [comment] 2016-09-20 22:38
(Might mean we should change strong mode semantics for "var" somehow. Maybe by looking at the union of the types that are assigned to the variable, and taking the most specific common denominator?)

**Comment by eseidelGoogle** [comment] 2016-09-20 23:03
FYI @leafpetersen

**Comment by sethladd** [comment] 2016-09-21 17:13
Do we have a Strong Mode doc that we can point our users to?

Also, Thanks @vy0592 for your feedback and comments! This sounds like a question around how Dart and Strong Mode works. Sounds like we have an answer, at least a workaround. I'm going to close this issue, but if you still have questions about Dart Strong Mode's type system, please let us know. @leafpetersen might be able to direct you to the best place to ask those questions. But of course, we're always happy to try to help from Flutter.

**Closed by sethladd** 2016-09-21 17:13 UTC
Labels: affects: dev experience, dependency: analyzer

**Comment by leafpetersen** [comment] 2016-09-21 21:44
We've been deliberately avoiding going down the route of taking all uses into account, since it adds a very large amount of complexity for relatively small (not negligible, just probably small relative to the complexity) benefit, and potentially slows down the responsiveness of the inference system and hence the dev cycle.  The problem is that if you look at all definitions, you have to decide what to do with definitions that use the thing being defined (possibly via a larger cycle).  Examples:

```dart
  var f;
  var g;
  f = 0;
  for(...) {
    g = f;
    f = 2.0;
    f = g;
  }
 g = "hello";
```

You can solve this via a fixed point algorithm iterating up from `bottom`.  You start by assuming that all of the variables have type `bottom`.  If you do each iteration top down, then the first iteration raises f to `int`, then g to `int`, then f to `num` when it sees the assignment of 2.0, then g to `Object` when it sees the assignment of 'hello`.  The second iteration raises f to `Object` at the assignment of g to f, and then you're done.  

Depending on the details, you can easily end up with a quadratic (or worse) algorithm.   Note that each step in each iteration is a full inference step as well: you need to potentially re-infer all of the sub-expressions of each statement.  A more interesting example:

```dart
  var f;
  var g;
  f = (x) => g(x + 1)(3);
  g = (x) => f
```

This can all be worked out in various ways, and can likely be made sufficiently fast, but our sense so far have been that the bang for the buck is relatively low.  We're happy to take feedback to the contrary though.

**Comment by vy0592** [comment] 2016-09-22 18:36
Thanks for the comments!

**Comment by Hixie** [comment] 2016-09-22 19:43
Is there an issue that is tracking this problem? People expecting 'var' to work like 'dynamic' is going to be pretty common given that many of our developers are going to come from the Web.

**Comment by sethladd** [comment] 2016-09-22 19:50
> People expecting 'var' to work like 'dynamic'

Yet another reason we need a FAQ, and a "how to migrate your code" guide, for Strong Mode. :)

**Comment by Hixie** [comment] 2016-09-22 19:55
I think maybe the language should change, rather than this being a FAQ. This seems like something where even if the programmer understands the problem fully, they'll still hit it and be annoyed.

**Comment by sethladd** [comment] 2016-09-22 19:59
Let's move the discussion over to https://github.com/dart-lang/sdk/issues/new

**Comment by Hixie** [comment] 2016-09-24 02:40
Filed https://github.com/dart-lang/sdk/issues/27422
