### ISSUE TITLE
Tapping on ActionChip with backgroundColor doesn't show ripple effect

### ISSUE THREAD

**Issue by sm2017** [flutter/flutter#85409] opened 2021-06-27 13:57 UTC
## Steps to Reproduce

`InkWkell` is not working when we have `backgroundColor`
```dart
ActionChip(
  label: Text('Delete'),
  backgroundColor: Colors.red,
  onPressed: () {
    print('onPressed');
})
```

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by darshankawar** [comment] 2021-06-28 14:02
@sm2017 
I see no issues wrapping your code sample with `InkWell`, as below and then tapping on the chip, which prints the text properly:

```
body: Center(
          child: InkWell(
            child: ActionChip(
                label: Text('Delete'),
                backgroundColor: Colors.red,
                onPressed: () {
                  print('onPressed');
                }
            ),
          )
        ),
```

```
flutter: onPressed
flutter: onPressed
flutter: onPressed
flutter: onPressed
flutter: onPressed
flutter: onPressed
```

<details>
<summary> flutter doctor -v </summary>

```
[✓] Flutter (Channel stable, 2.2.2, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.2.2 at /Users/dhs/documents/fluttersdk/flutter
    • Framework revision d79295af24 (11 days ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.56.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (4 available)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 91.0.4472.106

• No issues found!



```

</details>

**Comment by sm2017** [comment] 2021-06-28 17:33
@darshankawar there is nothing wrong in it's functionality, and no need to wrap with InkWell
The problem is, when you have a AcrionChip without background and it has a ripple effect when pressed, but when we have a background there is jo ripple effect

**Comment by darshankawar** [comment] 2021-06-29 06:15
Thanks for the clarification. I see the same behavior, ie, commenting out the `backgroundColor: Colors.red` doesn't show the ripple effect after tapping on it.

Also, according to the [documentation](https://api.flutter.dev/flutter/material/ActionChip-class.html):

`The material button widgets, ElevatedButton, TextButton, and OutlinedButton, are an alternative to action chips, which should appear statically and consistently in a UI.`

So I tried using `ElevatedButton` and provided a backgroundColor to it like below and tapping on it, shows the ripple effect:

```
body: Center(
          child: ElevatedButton(
            style: ButtonStyle(
              backgroundColor: MaterialStateProperty.all(Colors.red),
            ),
            child: Text('Delete'),
            onPressed: () {
              print('pressed');
            },
          )
        ),
```

**Comment by aarontwf** [comment] 2021-09-06 04:05
Duplicate of #73215?

**Comment by darshankawar** [comment] 2021-09-06 05:40
Thanks for the tip. Yes, I think this is duplicate of https://github.com/flutter/flutter/issues/73215.
Closing.  Please follow-up in original linked issue for further updates.

**Closed by darshankawar** 2021-09-06 05:40 UTC
Labels: framework, f: material design, has reproducible steps, found in release: 2.2
