### ISSUE TITLE
Flutter web issue with script type=module on deployment

### ISSUE THREAD

**Issue by Hari-07** [flutter/flutter#80629] opened 2021-04-17 04:07 UTC
## Steps to Reproduce

1. Create a flutter web project which uses firebase
2. Follow https://codewithandrea.com/tips/flutter-firebase-web-config-gitignore/ to modularize the firebase initialise app
3. Run it in debugger
3. Build and deploy the same
**Expected results:** 

It should have worked exactly the same on debugger and deploy.

**Actual results:** 

This solution works when running in local using the debugger but when built and deployed, firebase not initialised error gets thrown. console.log(firebase) inside that script worked but when i used that variable , it was undefined. 

I think this is a flutter issue if it works on dart vm but not when built

Also after a  bit of searching I found module variables have to be attached to window to be treated as a global variable and this produced a very weird issue, I can now access the firebase and firebaseConfig variables on deployment, but when i run firebase.initializeApp(firebaseConfig) it says the app already exists despite throwing an error that its not initialized

![image](https://user-images.githubusercontent.com/22373191/115101230-0ab14a80-9f60-11eb-9069-3907d7fb4ce7.png)

Body of index.html is attached below
```
<body>
  <!-- This script installs service_worker.js to provide PWA functionality to
       application. For more information, see:
       https://developers.google.com/web/fundamentals/primers/service-workers -->
  <script>
    if ('serviceWorker' in navigator) {
      window.addEventListener('flutter-first-frame', function () {
        navigator.serviceWorker.register('flutter_service_worker.js');
      });
    }
  </script>

  <!--These versions are tricky official docs versions might not work-->
  <!--These versions are tricky official docs versions might not work-->
  <script src="https://www.gstatic.com/firebasejs/8.2.1/firebase-app.js"></script>
  <script src="https://www.gstatic.com/firebasejs/8.2.1/firebase-analytics.js"></script>
  <script src="https://www.gstatic.com/firebasejs/8.2.1/firebase-auth.js"></script>
  <script src="https://www.gstatic.com/firebasejs/8.0.1/firebase-firestore.js"></script>

  <script src="./firebase-config.js"></script>
  <script type="module">
    // Your web app's Firebase configuration
    // For Firebase JS SDK v7.20.0 and later, measurementId is optional
    
    import { firebaseConfig } from './firebase-config.js';
    
    // Initialize Firebase
    firebase.initializeApp(firebaseConfig);
    firebase.analytics();

    window.firebaseConfig = firebaseConfig;
    window.firebase = firebase;
  </script>
  <script type="text/javascript">
      window.flutterWebRenderer = "html";
  </script>
  <script src="main.dart.js?version=0.1.0" type="application/javascript"></script>
</body>
```

<details>
  <summary>Logs</summary>

```
[  +98 ms] executing: [C:\Softwares\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +102 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +2 ms] b1395592de68cc8ac4522094ae59956dd21a91db
[   +1 ms] executing: [C:\Softwares\flutter/] git tag --points-at b1395592de68cc8ac4522094ae59956dd21a91db
[  +81 ms] Exit code 0 from: git tag --points-at b1395592de68cc8ac4522094ae59956dd21a91db
[        ] 2.0.4
[  +52 ms] executing: [C:\Softwares\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +61 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\Softwares\flutter/] git ls-remote --get-url origin
[  +63 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +121 ms] executing: [C:\Softwares\flutter/] git rev-parse --abbrev-ref HEAD
[  +72 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[ +182 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[  +21 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +107 ms] executing: C:\Users\harin\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +72 ms] List of devices attached
[   +7 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +109 ms] Multiple devices found:
[  +34 ms] Chrome (web) • chrome • web-javascript • Google Chrome 89.0.4389.128
[   +2 ms] Edge (web)   • edge   • web-javascript • Microsoft Edge 89.0.774.77
[   +3 ms] [1]: Chrome (chrome)
[        ] [2]: Edge (edge)
[   +2 ms] Please choose one (To quit, press "q/Q")
[        ] : 
[+8550 ms] 1
[  +18 ms] Skipping pub get: version match.
[  +64 ms] Found plugin cloud_firestore at C:\Softwares\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore-0.16.0+1\
[  +10 ms] Found plugin cloud_firestore_web at C:\Softwares\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore_web-0.3.0+2\
[  +19 ms] Found plugin file_picker at C:\Softwares\flutter\.pub-cache\hosted\pub.dartlang.org\file_picker-2.1.7\
[   +2 ms] Found plugin firebase_auth at C:\Softwares\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-0.20.1\
[   +3 ms] Found plugin firebase_auth_web at C:\Softwares\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth_web-0.3.3\
[   +2 ms] Found plugin firebase_core at C:\Softwares\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-0.7.0\
[   +4 ms] Found plugin firebase_core_web at C:\Softwares\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core_web-0.2.1+3\
[   +2 ms] Found plugin firebase_storage at C:\Softwares\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_storage-7.0.0\
[   +4 ms] Found plugin firebase_storage_web at C:\Softwares\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_storage_web-0.1.1+3\
[  +10 ms] Found plugin flutter_plugin_android_lifecycle at
C:\Softwares\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_plugin_android_lifecycle-1.0.11\
[  +22 ms] Found plugin image_picker at C:\Softwares\flutter\.pub-cache\hosted\pub.dartlang.org\image_picker-0.6.7+22\
[ +120 ms] Found plugin cloud_firestore at C:\Softwares\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore-0.16.0+1\
[   +4 ms] Found plugin cloud_firestore_web at C:\Softwares\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore_web-0.3.0+2\
[  +12 ms] Found plugin file_picker at C:\Softwares\flutter\.pub-cache\hosted\pub.dartlang.org\file_picker-2.1.7\
[   +2 ms] Found plugin firebase_auth at C:\Softwares\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-0.20.1\
[   +2 ms] Found plugin firebase_auth_web at C:\Softwares\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth_web-0.3.3\
[   +1 ms] Found plugin firebase_core at C:\Softwares\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-0.7.0\
[   +3 ms] Found plugin firebase_core_web at C:\Softwares\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core_web-0.2.1+3\
[   +2 ms] Found plugin firebase_storage at C:\Softwares\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_storage-7.0.0\
[   +2 ms] Found plugin firebase_storage_web at C:\Softwares\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_storage_web-0.1.1+3\
[   +5 ms] Found plugin flutter_plugin_android_lifecycle at
C:\Softwares\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_plugin_android_lifecycle-1.0.11\
[  +12 ms] Found plugin image_picker at C:\Softwares\flutter\.pub-cache\hosted\pub.dartlang.org\image_picker-0.6.7+22\
[ +157 ms] Launching lib\main.dart on Chrome in debug mode...
[ +160 ms] Updating assets
[ +189 ms] Manifest contained wildcard assets. Inserting missing file into build graph to force rerun. for more information see #56466.
[   +5 ms] Waiting for connection from debug service on Chrome...
[  +29 ms] Found plugin cloud_firestore at C:\Softwares\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore-0.16.0+1\
[   +3 ms] Found plugin cloud_firestore_web at C:\Softwares\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore_web-0.3.0+2\
[  +11 ms] Found plugin file_picker at C:\Softwares\flutter\.pub-cache\hosted\pub.dartlang.org\file_picker-2.1.7\
[   +2 ms] Found plugin firebase_auth at C:\Softwares\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-0.20.1\
[   +3 ms] Found plugin firebase_auth_web at C:\Softwares\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth_web-0.3.3\
[   +2 ms] Found plugin firebase_core at C:\Softwares\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-0.7.0\
[   +3 ms] Found plugin firebase_core_web at C:\Softwares\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core_web-0.2.1+3\
[   +1 ms] Found plugin firebase_storage at C:\Softwares\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_storage-7.0.0\
[   +2 ms] Found plugin firebase_storage_web at C:\Softwares\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_storage_web-0.1.1+3\
[   +5 ms] Found plugin flutter_plugin_android_lifecycle at
C:\Softwares\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_plugin_android_lifecycle-1.0.11\
[  +10 ms] Found plugin image_picker at C:\Softwares\flutter\.pub-cache\hosted\pub.dartlang.org\image_picker-0.6.7+22\
[  +69 ms] Found plugin cloud_firestore at C:\Softwares\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore-0.16.0+1\
[   +3 ms] Found plugin cloud_firestore_web at C:\Softwares\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore_web-0.3.0+2\
[   +7 ms] Found plugin file_picker at C:\Softwares\flutter\.pub-cache\hosted\pub.dartlang.org\file_picker-2.1.7\
[   +1 ms] Found plugin firebase_auth at C:\Softwares\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-0.20.1\
[   +2 ms] Found plugin firebase_auth_web at C:\Softwares\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth_web-0.3.3\
[   +1 ms] Found plugin firebase_core at C:\Softwares\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-0.7.0\
[   +3 ms] Found plugin firebase_core_web at C:\Softwares\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core_web-0.2.1+3\
[   +1 ms] Found plugin firebase_storage at C:\Softwares\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_storage-7.0.0\
[   +2 ms] Found plugin firebase_storage_web at C:\Softwares\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_storage_web-0.1.1+3\
ld\.dart_tool\package_config.json -Ddart.vm.profile=false
-Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-root
C:\Users\harin\AppData\Local\Temp\flutter_tools.253e5d20\flutter_tools.1fcab193 --filesystem-scheme org-dartlang-app --initialize-from-dill
build\c7922d95bf4a2462b75c84a97c312edb.cache.dill.track.dill --platform file:///C:/Softwares/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk.dill 
--no-sound-null-safety
[  +19 ms] <- compile org-dartlang-app:/web_entrypoint.dart
Terminate batch job (Y/N)? y
PS C:\Codes\Uniworld> flutter run --verbose
[  +91 ms] executing: [C:\Softwares\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +94 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] b1395592de68cc8ac4522094ae59956dd21a91db
[   +1 ms] executing: [C:\Softwares\flutter/] git tag --points-at b1395592de68cc8ac4522094ae59956dd21a91db
[  +72 ms] Exit code 0 from: git tag --points-at b1395592de68cc8ac4522094ae59956dd21a91db
[        ] 2.0.4
[  +53 ms] executing: [C:\Softwares\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +58 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\Softwares\flutter/] git ls-remote --get-url origin
[  +54 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter.git
[  +93 ms] executing: [C:\Softwares\flutter/] git rev-parse --abbrev-ref HEAD
[  +53 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[ +100 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +70 ms] executing: C:\Users\harin\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +52 ms] List of devices attached
[   +5 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +98 ms] Multiple devices found:
[  +32 ms] Chrome (web) • chrome • web-javascript • Google Chrome 89.0.4389.128
[   +2 ms] Edge (web)   • edge   • web-javascript • Microsoft Edge 89.0.774.77
[   +2 ms] [1]: Chrome (chrome)
[        ] [2]: Edge (edge)
[   +2 ms] Please choose one (To quit, press "q/Q")
[        ] : 
[+2934 ms] 1
[  +15 ms] Skipping pub get: version match.
[  +69 ms] Found plugin cloud_firestore at C:\Softwares\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore-0.16.0+1\
[  +10 ms] Found plugin cloud_firestore_web at C:\Softwares\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore_web-0.3.0+2\
[  +19 ms] Found plugin file_picker at C:\Softwares\flutter\.pub-cache\hosted\pub.dartlang.org\file_picker-2.1.7\
[   +2 ms] Found plugin firebase_auth at C:\Softwares\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-0.20.1\
[   +4 ms] Found plugin firebase_auth_web at C:\Softwares\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth_web-0.3.3\
[   +2 ms] Found plugin firebase_core at C:\Softwares\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-0.7.0\
[   +4 ms] Found plugin firebase_core_web at C:\Softwares\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core_web-0.2.1+3\
[   +2 ms] Found plugin firebase_storage at C:\Softwares\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_storage-7.0.0\
[   +4 ms] Found plugin firebase_storage_web at C:\Softwares\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_storage_web-0.1.1+3\
[  +11 ms] Found plugin flutter_plugin_android_lifecycle at
C:\Softwares\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_plugin_android_lifecycle-1.0.11\
[  +23 ms] Found plugin image_picker at C:\Softwares\flutter\.pub-cache\hosted\pub.dartlang.org\image_picker-0.6.7+22\
[ +119 ms] Found plugin cloud_firestore at C:\Softwares\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore-0.16.0+1\
[   +5 ms] Found plugin cloud_firestore_web at C:\Softwares\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore_web-0.3.0+2\
[  +14 ms] Found plugin file_picker at C:\Softwares\flutter\.pub-cache\hosted\pub.dartlang.org\file_picker-2.1.7\
[   +2 ms] Found plugin firebase_auth at C:\Softwares\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-0.20.1\
[   +3 ms] Found plugin firebase_auth_web at C:\Softwares\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth_web-0.3.3\
[   +2 ms] Found plugin firebase_core at C:\Softwares\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-0.7.0\
[   +2 ms] Found plugin firebase_core_web at C:\Softwares\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core_web-0.2.1+3\
[   +2 ms] Found plugin firebase_storage at C:\Softwares\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_storage-7.0.0\
[   +3 ms] Found plugin firebase_storage_web at C:\Softwares\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_storage_web-0.1.1+3\
[   +6 ms] Found plugin flutter_plugin_android_lifecycle at
C:\Softwares\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_plugin_android_lifecycle-1.0.11\
[  +13 ms] Found plugin image_picker at C:\Softwares\flutter\.pub-cache\hosted\pub.dartlang.org\image_picker-0.6.7+22\
[ +183 ms] Launching lib\main.dart on Chrome in debug mode...
[ +173 ms] Updating assets
[ +210 ms] Manifest contained wildcard assets. Inserting missing file into build graph to force rerun. for more information see #56466.
[   +4 ms] Waiting for connection from debug service on Chrome...
[  +35 ms] Found plugin cloud_firestore at C:\Softwares\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore-0.16.0+1\
[   +3 ms] Found plugin cloud_firestore_web at C:\Softwares\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore_web-0.3.0+2\
[  +11 ms] Found plugin file_picker at C:\Softwares\flutter\.pub-cache\hosted\pub.dartlang.org\file_picker-2.1.7\
[   +1 ms] Found plugin firebase_auth at C:\Softwares\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-0.20.1\
[   +3 ms] Found plugin firebase_auth_web at C:\Softwares\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth_web-0.3.3\
[   +2 ms] Found plugin firebase_core at C:\Softwares\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-0.7.0\
[   +3 ms] Found plugin firebase_core_web at C:\Softwares\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core_web-0.2.1+3\
[   +1 ms] Found plugin firebase_storage at C:\Softwares\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_storage-7.0.0\
[   +3 ms] Found plugin firebase_storage_web at C:\Softwares\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_storage_web-0.1.1+3\
[   +4 ms] Found plugin flutter_plugin_android_lifecycle at
C:\Softwares\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_plugin_android_lifecycle-1.0.11\
[  +11 ms] Found plugin image_picker at C:\Softwares\flutter\.pub-cache\hosted\pub.dartlang.org\image_picker-0.6.7+22\
[  +74 ms] Found plugin cloud_firestore at C:\Softwares\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore-0.16.0+1\
[   +3 ms] Found plugin cloud_firestore_web at C:\Softwares\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore_web-0.3.0+2\
[  +10 ms] Found plugin file_picker at C:\Softwares\flutter\.pub-cache\hosted\pub.dartlang.org\file_picker-2.1.7\
[   +1 ms] Found plugin firebase_auth at C:\Softwares\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-0.20.1\
[   +2 ms] Found plugin firebase_auth_web at C:\Softwares\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth_web-0.3.3\
[   +1 ms] Found plugin firebase_core at C:\Softwares\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-0.7.0\
[   +2 ms] Found plugin firebase_core_web at C:\Softwares\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core_web-0.2.1+3\
[   +1 ms] Found plugin firebase_storage at C:\Softwares\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_storage-7.0.0\
[   +3 ms] Found plugin firebase_storage_web at C:\Softwares\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_storage_web-0.1.1+3\
[   +5 ms] Found plugin flutter_plugin_android_lifecycle at
C:\Softwares\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_plugin_android_lifecycle-1.0.11\
[  +12 ms] Found plugin image_picker at C:\Softwares\flutter\.pub-cache\hosted\pub.dartlang.org\image_picker-0.6.7+22\
[ +120 ms] <- reset
[  +10 ms] C:\Softwares\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev
C:\Softwares\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root C:\Softwares\flutter\bin\cache\flutter_web_sdk/       
--incremental --target=dartdevc --debugger-module-names --experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true --output-dill
C:\Users\harin\AppData\Local\Temp\flutter_tools.5e41b38e\flutter_tool.d0af6921\app.dill --libraries-spec
file:///C:/Softwares/flutter/bin/cache/flutter_web_sdk/libraries.json --packages C:\Codes\Uniworld\.dart_tool\package_config.json -Ddart.vm.profile=false  
-Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-root
C:\Users\harin\AppData\Local\Temp\flutter_tools.5e41b38e\flutter_tools.d4978147 --filesystem-scheme org-dartlang-app --initialize-from-dill
build\c7922d95bf4a2462b75c84a97c312edb.cache.dill.track.dill --platform file:///C:/Softwares/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk.dill 
--no-sound-null-safety
[  +43 ms] <- compile org-dartlang-app:/web_entrypoint.dart
[+27213 ms] Waiting for connection from debug service on Chrome... (completed in 27.6s)
[   +1 ms] Synced 39.2MB.
[        ] <- accept
[        ] Caching compiled dill
```

```
[√] Flutter (Channel stable, 2.0.4, on Microsoft Windows [Version 10.0.19042.928], locale en-IN)
    • Flutter version 2.0.4 at C:\Softwares\flutter
    • Framework revision b1395592de (2 weeks ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2) 
    • Android SDK at C:\Users\harin\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Softwares\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe      

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Softwares\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 89.0.4389.128
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 89.0.774.77

• No issues found!
```

</details>

**Comment by TahaTesser** [comment] 2021-04-19 07:51
Hi @Hari-07 
I can't find any  type="module" references related to  Flutter
From what I can see, the issue is related to a FlutterFire plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  providing your `flutter doctor -v`, your `pubspec.yaml`, a minimal reproducible code sample that does not use 3rd party plugins, your complete `flutter run -v` logs running the minimal code sample 
and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-04-19 07:51 UTC
Labels: in triage
