### ISSUE TITLE
I have issues with RTL(Arabic) back button Icon position

### ISSUE THREAD

**Issue by saleh-aleid** [flutter/flutter#153404] opened 2024-08-13 23:47 UTC
### What package does this bug report belong to?

go_router

### What target platforms are you seeing this bug on?

Android, iOS

### Have you already upgraded your packages?

Yes

### Dependency versions

<details><summary>pubspec.lock</summary>

```lock
[Paste file content here]
```

</details>

### Steps to reproduce

Create a login page then go to OTP page

### Expected results

![Simulator Screenshot - iPhone 15 Pro Max - 2024-08-14 at 02 28 54](https://github.com/user-attachments/assets/0c97f7a7-bd01-498f-b89d-080878fc66d7)

### Actual results

https://github.com/user-attachments/assets/33284483-2441-4acc-adc6-34556feb6f57

### Code sample

<details open><summary>GoRouter</summary>

```dart
final router = GoRouter(
  initialLocation: '/',
  debugLogDiagnostics: true,
  routes: [
    GoRoute(
      path: '/',
      builder: (context, state) => const LanguageScreen(),
    ),
    GoRoute(
      path: LanguageScreen.routeName,
      redirect: (context, state) => LanguageScreen.routeName,
      builder: (context, state) => const LanguageScreen(),
    ),
    GoRoute(
      path: SignInScreen.routeName,
      name: SignInScreen.routeName,
      builder: (context, state) => const SignInScreen(),
      routes: [
        GoRoute(
          path: OTPScreen.routeName,
          name: OTPScreen.routeName,
          builder: (context, state) => const OTPScreen(),
        ),
      ],
    ),
  ],
);
```
</details>

<details open><summary>LoginPage</summary>

```dart

class SignInFormWidget extends StatelessWidget {
  const SignInFormWidget({super.key});

  @override
  Widget build(BuildContext context) {
    return Form(
      autovalidateMode: AutovalidateMode.onUserInteraction,
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.stretch,
        mainAxisAlignment: MainAxisAlignment.start,
        children: [
          TextFormField(),
          TextFormField(),
          const SizedBox(height: 10),
          FilledButton(
            onPressed: () => context.goNamed(OTPScreen.routeName),
            child: Text(context.locale.signIn),
          ),
        ],
      ),
    );
  }
}

```
</details>

<details open><summary>OTPPage</summary>

```dart

class OTPScreen extends StatelessWidget {
  const OTPScreen({super.key});

  static const routeName = 'otp';

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: CustomScrollView(
        slivers: [
          SliverAppBar.large(
            title: Text(context.locale.verification),
          ),
          SliverFillRemaining(
            child: Column(
              // crossAxisAlignment: CrossAxisAlignment.,
              mainAxisAlignment: MainAxisAlignment.center,

              children: [
                Text(context.locale
                    .verificationSubtitle('+966-966-966-966-966')),
                SizedBox(
                  height: 50,
                ),
                const Directionality(
                  textDirection: TextDirection.ltr,
                  child: Pinput(
                    length: 4,
                  ),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }
}
```
</details>

### Screenshots or Videos

<details open>
<summary>Screenshots / Video demonstration</summary>

![Simulator Screenshot - iPhone 15 Pro Max - 2024-08-14 at 02 28 54](https://github.com/user-attachments/assets/bf0fbac5-38cc-4f48-98a1-dc48301b6b47)

https://github.com/user-attachments/assets/8300bcbd-c2b5-419c-a8a2-5339510a43f0

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[flutter] flutter doctor -v
[✓] Flutter (Channel stable, 3.24.0, on macOS 14.6.1 23G93 darwin-arm64, locale en-SA)
    • Flutter version 3.24.0 on channel stable at /Users/salehaleid/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 80c2e84975 (2 weeks ago), 2024-07-30 23:06:49 +0700
    • Engine revision b8800d88be
    • Dart version 3.5.0
    • DevTools version 2.37.2

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/salehaleid/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)

[✓] VS Code (version 1.92.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.94.0

[✓] Connected device (4 available)
    • iPhone 15 Pro Max (mobile)      • 0EBAD86E-5F74-4947-952B-23EB012A755D • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-2 (simulator)
    • macOS (desktop)                 • macos                                • darwin-arm64   • macOS 14.6.1 23G93 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad                • darwin         • macOS 14.6.1 23G93 darwin-arm64
    • Chrome (web)                    • chrome                               • web-javascript • Google Chrome 127.0.6533.100

[✓] Network resources
    • All expected network resources are available.

• No issues found!
exit code 0

```

</details>

**Comment by danagbemava-nc** [comment] 2024-08-14 07:20
Closing this as a duplicate of https://github.com/flutter/flutter/issues/153036

**Closed by danagbemava-nc** 2024-08-14 07:20 UTC
Labels: in triage
