### ISSUE TITLE
Using `IndexedStack` inside Scaffold and then trying to tap on `BottomNavigationTab` bar throws `package:flutter/src/rendering/stack.dart': Failed assertion: line 717 pos 12: 'child != null': is not true`. exception.

### ISSUE THREAD

**Issue by jackdaniels247** [flutter/flutter#96797] opened 2022-01-18 19:08 UTC
![image](https://user-images.githubusercontent.com/64647294/150002268-ae6d8ec3-977c-42e3-8d28-db6c0d132a3b.png)

<details> 
<summary> error </summary>

```


The following assertion was thrown during paint():
'package:flutter/src/rendering/stack.dart': Failed assertion: line 717 pos 12: 'child != null': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was: 
  IndexedStack IndexedStack:file:///C:/WorkSpace/chargefast.ui/lib/app_src/tabs/tab_containers.dart:62:15
When the exception was thrown, this was the stack: 
#2      RenderIndexedStack._childAtIndex (package:flutter/src/rendering/stack.dart:717:12)
#3      RenderIndexedStack.paintStack (package:flutter/src/rendering/stack.dart:742:29)
#4      RenderStack.paint (package:flutter/src/rendering/stack.dart:645:7)
#5      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2403:7)
#6      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#7      RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2792:15)
#8      RenderCustomMultiChildLayoutBox.paint (package:flutter/src/rendering/custom_layout.dart:408:5)
#9      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2403:7)
#10     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#11     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#12     _RenderInkFeatures.paint (package:flutter/src/material/material.dart:554:11)
#13     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2403:7)
#14     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#15     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#16     PaintingContext.pushLayer (package:flutter/src/rendering/object.dart:392:12)
#17     RenderPhysicalModel.paint (package:flutter/src/rendering/proxy_box.dart:1929:15)
#18     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2403:7)
#19     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#20     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#21     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2403:7)
#22     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#23     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#24     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2403:7)
#25     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:141:11)
#26     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:100:5)
#27     PipelineOwner.flushPaint (package:flutter/src/rendering/object.dart:973:29)
#28     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:499:19)
#29     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:883:13)
#30     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:363:5)
#31     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1145:15)
#32     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1082:9)
#33     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:996:5)
#37     _invoke (dart:ui/hooks.dart:150:10)
#38     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:270:5)
#39     _drawFrame (dart:ui/hooks.dart:114:31)
(elided 5 frames from class _AssertionError and dart:async)

```
</details>

<details>
<summary> code </summary>

```

class _TabContainerLoad1TimeState extends State<TabContainerLoad1Time> {
  List<Widget> originalList;
  Map<int, bool> originalDic;
  List<Widget> listScreens;
  List<int> listScreensIndex;

  int tabIndex = 0;
  @override
  void initState() {
    super.initState();
    originalList = [
      Google(),
      BookingDetails(),
      AccountDetails(),
    ];
    originalDic = {0: true, 1: false, 2: false};
    listScreens = [originalList.first];
    listScreensIndex = [0];
  }

//  @override
//  bool get wantKeepAlive =>
//      true; //by default it will be null, change it to true.

  void _selectedTab(int index) {
    if (originalDic[index] == false) {
      listScreensIndex.add(index);
      originalDic[index] = true;
      listScreensIndex.sort();
      listScreens = listScreensIndex.map((index) {
        return originalList[index];
      }).toList();
    }

    setState(() {
      tabIndex = index;
    });
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      color: Colors.yellow,
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        **body: IndexedStack(index: tabIndex, children: listScreens),** error causing statement
        bottomNavigationBar: BottomNavigationBar(
          elevation: 0,
            backgroundColor: Colors.white,
            type: BottomNavigationBarType.fixed,
            showUnselectedLabels: false,
            currentIndex: tabIndex,
            onTap:(index){
               _selectedTab(index);
            },
            selectedItemColor: Color.fromRGBO(56, 91, 198, 1),
            items: [
              BottomNavigationBarItem(
                icon: Icon(Icons.home_outlined),
                label:'Home',
              ),
              BottomNavigationBarItem(
                icon: Icon(Icons.bookmark_border),
                label: 'Bookings',
              ),
              BottomNavigationBarItem(
                icon: Icon(Icons.account_circle_outlined),
                label: 'Account',
              ),
            ]),
      ),
    );
  }
}

```
</details>

**Comment by darshankawar** [comment] 2022-01-19 05:39
@jackdaniels247 
Can you provide `flutter doctor -v` and a complete minimal reproducible code sample (e.g: main.dart) that we can directly copy paste and run which shows this exception ?

**Comment by jackdaniels247** [comment] 2022-01-19 09:14
C:\Users\ASUS\StudioProjects\sample>flutter doctor -v
[√] Flutter (Channel stable, 2.8.0, on Microsoft Windows [Version 10.0.22000.434], locale en-IN)
    • Flutter version 2.8.0 at C:\flutter_dev\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cf44000065 (6 weeks ago), 2021-12-08 14:06:50 -0800
    • Engine revision 40a99c5951
    • Dart version 2.15.0

[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\ASUS\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[☠] IntelliJ IDEA Community Edition (the doctor check crashed)
    X Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    X FormatException: Unexpected extension byte (at offset 5)
    • #0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1789:7)
      #1      Utf8Decoder.convert (dart:convert/utf.dart:318:42)
      #2      InputStream.readString (package:archive/src/util/input_stream.dart:207:30)
      #3      new ZipDirectory.read (package:archive/src/zip/zip_directory.dart:40:30)
      #4      ZipDecoder.decodeBuffer (package:archive/src/zip_decoder.dart:19:30)
      #5      ZipDecoder.decodeBytes (package:archive/src/zip_decoder.dart:14:12)
      #6      IntelliJPlugins._findPluginXml (package:flutter_tools/src/intellij/intellij.dart:130:44)
      #7      IntelliJPlugins._readPackageVersion (package:flutter_tools/src/intellij/intellij.dart:141:40)
      #8      IntelliJPlugins.validatePackage (package:flutter_tools/src/intellij/intellij.dart:63:35)
      #9      IntelliJValidator.validate (package:flutter_tools/src/intellij/intellij_validator.dart:103:15)
      #10     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      #11     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:109:18)
      #12     _rootRun (dart:async/zone.dart:1428:13)
      #13     _CustomZone.run (dart:async/zone.dart:1328:19)
      #14     _runZoned (dart:async/zone.dart:1863:10)
      #15     runZonedGuarded (dart:async/zone.dart:1851:12)
      #16     runZoned (dart:async/zone.dart:1782:12)
      #17     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #18     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:197:9)
      #19     Doctor.diagnose (package:flutter_tools/src/doctor.dart:301:47)
      #20     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:53:47)
      #21     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1290:12)
      <asynchronous suspension>
      #22     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1140:27)
      <asynchronous suspension>
      #23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #24     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
      <asynchronous suspension>
      #25     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
      <asynchronous suspension>
      #26     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #27     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
      <asynchronous suspension>
      #28     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
      <asynchronous suspension>
      #29     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #30     main (package:flutter_tools/executable.dart:94:3)
      <asynchronous suspension>


[√] Connected device (3 available)
    • RMX3241 (mobile) • LBCENJSSDIZ5LRJV • android-arm64  • Android 11 (API 30)
    • Chrome (web)     • chrome           • web-javascript • Google Chrome 97.0.4692.71
    • Edge (web)       • edge             • web-javascript • Microsoft Edge 97.0.1072.62

! Doctor found issues in 2 categories.


**main.dart**

//@dart=2.9
import 'package:flutter/material.dart';
import 'package:sample/tab_containers.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        title: 'ChargeFast your Dream!!!',
        theme: ThemeData(primarySwatch: Colors.blue),
        debugShowCheckedModeBanner: false,
        home: TabContainerLoad1Time());
  }
}


**tab_containers.dart**


//@dart=2.9

import 'package:flutter/material.dart';
import 'package:sample/screen1.dart';
import 'package:sample/screen2.dart';
import 'package:sample/screen3.dart';



class TabContainerLoad1Time extends StatefulWidget {
  TabContainerLoad1Time({Key key}) : super(key: key);

  @override
  _TabContainerLoad1TimeState createState() => _TabContainerLoad1TimeState();
}

class _TabContainerLoad1TimeState extends State<TabContainerLoad1Time> {
  List<Widget> originalList;
  Map<int, bool> originalDic;
  List<Widget> listScreens;
  List<int> listScreensIndex;

  int tabIndex = 0;
  @override
  void initState() {
    super.initState();
    originalList = [
      Screen1(),
      Screen2(),
      Screen3(),
    ];
    originalDic = {0: true, 1: false, 2: false};
    listScreens = [originalList.first];
    listScreensIndex = [0];
  }

//  @override
//  bool get wantKeepAlive =>
//      true; //by default it will be null, change it to true.

  void _selectedTab(int index) {
    if (originalDic[index] == false) {
      listScreensIndex.add(index);
      originalDic[index] = true;
      listScreensIndex.sort();
      listScreens = listScreensIndex.map((index) {
        return originalList[index];
      }).toList();
    }

    setState(() {
      tabIndex = index;
    });
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      color: Colors.yellow,
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: IndexedStack(index: tabIndex, children: listScreens),
        bottomNavigationBar: BottomNavigationBar(
            elevation: 0,
            backgroundColor: Colors.white,
            type: BottomNavigationBarType.fixed,
            showUnselectedLabels: false,
            currentIndex: tabIndex,
            onTap:(index){
              _selectedTab(index);
            },
            selectedItemColor: Color.fromRGBO(56, 91, 198, 1),
            items: [
              BottomNavigationBarItem(
                icon: Icon(Icons.home_outlined),
                label:'Screen 1',
              ),
              BottomNavigationBarItem(
                icon: Icon(Icons.bookmark_border),
                label: 'Screen 2',
              ),
              BottomNavigationBarItem(
                icon: Icon(Icons.account_circle_outlined),
                label: 'Screen 3',
              ),
            ]),
      ),
    );
  }
}


**screen1**

//@dart=2.9
import 'package:flutter/material.dart';

class Screen1 extends StatefulWidget {
  const Screen1({Key key}) : super(key: key);

  @override
  _Screen1State createState() => _Screen1State();
}

class _Screen1State extends State<Screen1> {
  @override
  Widget build(BuildContext context) {
    return Container(
      child: Center(
        child: Text("Screen 1"),
      ),
    );
  }
}


**screen 2**

//@dart=2.9
import 'package:flutter/material.dart';

class Screen2 extends StatefulWidget {
  const Screen2({Key key}) : super(key: key);

  @override
  _Screen2State createState() => _Screen2State();
}

class _Screen2State extends State<Screen2>with AutomaticKeepAliveClientMixin<Screen2> {
  @override
  Widget build(BuildContext context) {
    return Container(
      child: Center(
        child: Text("Screen2"),
      ),
    );
  }

  @override
  // TODO: implement wantKeepAlive
  bool get wantKeepAlive => true;
}


**screen3**


//@dart=2.9
import 'package:flutter/material.dart';

class Screen3 extends StatefulWidget {
  const Screen3({Key key}) : super(key: key);

  @override
  _Screen3State createState() => _Screen3State();
}

class _Screen3State extends State<Screen3>with AutomaticKeepAliveClientMixin<Screen3> {
  @override
  Widget build(BuildContext context) {
    return Container(
      child: Center(
        child: Text("Screen3"),
      ),
    );
  }

  @override
  // TODO: implement wantKeepAlive
  bool get wantKeepAlive => true;
}



**The error occurs when you navigate directly from first tab to last tab for the first time just after running the app**

**Comment by darshankawar** [comment] 2022-01-20 06:34
Verified this using the code sample provided and do see the same exception while directly tapping on third tab from first upon app launch.

<details>
<summary> console error log </summary>

```

══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
The following assertion was thrown during paint():
'package:flutter/src/rendering/stack.dart': Failed assertion: line 717 pos 12: 'child != null': is
not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was:
  IndexedStack IndexedStack:file:///Users/dhs/Documents/NCFlutter/ios_bug/lib/main.dart:2109:7

When the exception was thrown, this was the stack:
#2      RenderIndexedStack._childAtIndex (package:flutter/src/rendering/stack.dart:717:12)
#3      RenderIndexedStack.paintStack (package:flutter/src/rendering/stack.dart:742:29)
#4      RenderStack.paint (package:flutter/src/rendering/stack.dart:645:7)
#5      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2451:7)
#6      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#7      RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2847:15)
#8      RenderCustomMultiChildLayoutBox.paint (package:flutter/src/rendering/custom_layout.dart:408:5)
#9      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2451:7)
#10     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#11     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#12     _RenderInkFeatures.paint (package:flutter/src/material/material.dart:555:11)
#13     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2451:7)
#14     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#15     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#16     PaintingContext.pushLayer (package:flutter/src/rendering/object.dart:387:12)
#17     RenderPhysicalModel.paint (package:flutter/src/rendering/proxy_box.dart:1929:15)
#18     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2451:7)
#19     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#20     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#21     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2451:7)
#22     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#23     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#24     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2451:7)
#25     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:141:11)
#26     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:100:5)
#27     PipelineOwner.flushPaint (package:flutter/src/rendering/object.dart:995:29)
#28     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:499:19)
#29     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:883:13)
#30     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:363:5)
#31     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
#32     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1081:9)
#33     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:995:5)
#37     _invoke (dart:ui/hooks.dart:151:10)
#38     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308:5)
#39     _drawFrame (dart:ui/hooks.dart:115:31)
(elided 5 frames from class _AssertionError and dart:async)

The following RenderObject was being processed when the exception was fired: RenderIndexedStack#1392c relayoutBoundary=up1:
  creator: IndexedStack ← _BodyBuilder ← MediaQuery ← LayoutId-[<_ScaffoldSlot.body>] ←
    CustomMultiChildLayout ← AnimatedBuilder ← DefaultTextStyle ← AnimatedDefaultTextStyle ←
    _InkFeatures-[GlobalKey#c34c1 ink renderer] ← NotificationListener<LayoutChangedNotification> ←
    PhysicalModel ← AnimatedPhysicalModel ← ⋯
  parentData: offset=Offset(0.0, 0.0); id=_ScaffoldSlot.body (can use size)
  constraints: BoxConstraints(0.0<=w<=428.0, 0.0<=h<=836.0)
  size: Size(428.0, 836.0)
  alignment: AlignmentDirectional.topStart
  textDirection: ltr
  fit: loose
  index: 2
This RenderObject had the following descendants (showing up to depth 5):
    child 1: RenderPositionedBox#d143d relayoutBoundary=up2
      child: RenderParagraph#89f95 relayoutBoundary=up3
        text: TextSpan
    child 2: RenderPositionedBox#3b4ef relayoutBoundary=up2 NEEDS-PAINT
      child: RenderParagraph#da97c relayoutBoundary=up3 NEEDS-PAINT
        text: TextSpan
════════════════════════════════════════════════════════════════════════════════════════════════════

Another exception was thrown: 'package:flutter/src/rendering/stack.dart': Failed assertion: line 717 pos 12: 'child != null': is not true.

Another exception was thrown: 'package:flutter/src/rendering/stack.dart': Failed assertion: line 717 pos 12: 'child != null': is not true.

```
</details>

<details>
<summary> complete code sample </summary>

```

import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

// This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        title: 'ChargeFast your Dream!!!',
        theme: ThemeData(primarySwatch: Colors.blue),
        debugShowCheckedModeBanner: false,
        home: TabContainerLoad1Time());
  }
}

class TabContainerLoad1Time extends StatefulWidget {
  TabContainerLoad1Time({Key? key}) : super(key: key);

  @override
  _TabContainerLoad1TimeState createState() => _TabContainerLoad1TimeState();
}

class _TabContainerLoad1TimeState extends State<TabContainerLoad1Time> {
  late List<Widget> originalList;
  late Map<int, bool> originalDic;
  late List<Widget> listScreens;
  late List<int> listScreensIndex;

  int tabIndex = 0;

  @override
  void initState() {
    super.initState();
    originalList = [
      Screen1(),
      Screen2(),
      Screen3(),
    ];
    originalDic = {0: true, 1: false, 2: false};
    listScreens = [originalList.first];
    listScreensIndex = [0];
  }

//  @override
//  bool get wantKeepAlive =>
//      true; //by default it will be null, change it to true.

  void _selectedTab(int index) {
    if (originalDic[index] == false) {
      listScreensIndex.add(index);
      originalDic[index] = true;
      listScreensIndex.sort();
      listScreens = listScreensIndex.map((index) {
        return originalList[index];
      }).toList();
    }

    setState(() {
      tabIndex = index;
    });
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      color: Colors.yellow,
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: IndexedStack(index: tabIndex, children: listScreens),
        bottomNavigationBar: BottomNavigationBar(
            elevation: 0,
            backgroundColor: Colors.white,
            type: BottomNavigationBarType.fixed,
            showUnselectedLabels: false,
            currentIndex: tabIndex,
            onTap: (index) {
              _selectedTab(index);
            },
            selectedItemColor: Color.fromRGBO(56, 91, 198, 1),
            items: [
              BottomNavigationBarItem(
                icon: Icon(Icons.home_outlined),
                label: 'Screen 1',
              ),
              BottomNavigationBarItem(
                icon: Icon(Icons.bookmark_border),
                label: 'Screen 2',
              ),
              BottomNavigationBarItem(
                icon: Icon(Icons.account_circle_outlined),
                label: 'Screen 3',
              ),
            ]),
      ),
    );
  }
}

class Screen1 extends StatefulWidget {
  const Screen1({Key? key}) : super(key: key);

  @override
  _Screen1State createState() => _Screen1State();
}

class _Screen1State extends State<Screen1> {
  @override
  Widget build(BuildContext context) {
    return Container(
      child: Center(
        child: Text("Screen 1"),
      ),
    );
  }
}

class Screen2 extends StatefulWidget {
  const Screen2({Key? key}) : super(key: key);

  @override
  _Screen2State createState() => _Screen2State();
}

class _Screen2State extends State<Screen2>
    with AutomaticKeepAliveClientMixin<Screen2> {
  @override
  Widget build(BuildContext context) {
    return Container(
      child: Center(
        child: Text("Screen2"),
      ),
    );
  }

  @override
// TODO: implement wantKeepAlive
  bool get wantKeepAlive => true;
}

class Screen3 extends StatefulWidget {
  const Screen3({Key? key}) : super(key: key);

  @override
  _Screen3State createState() => _Screen3State();
}

class _Screen3State extends State<Screen3>
    with AutomaticKeepAliveClientMixin<Screen3> {
  @override
  Widget build(BuildContext context) {
    return Container(
      child: Center(
        child: Text("Screen3"),
      ),
    );
  }

  @override
// TODO: implement wantKeepAlive
  bool get wantKeepAlive => true;
}

```

</details>

<details>
<summary> flutter doctor -v </summary>

```

[✓] Flutter (Channel master, 2.9.0-1.0.pre.413, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-GB)
    • Flutter version 2.9.0-1.0.pre.413 at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ef8a841035 (19 minutes ago), 2022-01-19 21:35:19 -0800
    • Engine revision 3ccf02b5a7
    • Dart version 2.17.0 (build 2.17.0-31.0.dev)
    • DevTools version 2.9.2

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • Mac OS X 10.15.4 19E2269
      darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 97.0.4692.71

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

[✓] Flutter (Channel stable, 2.8.1, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.8.1 at /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (13 hours ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/dhs/Library/Android/sdk
    • Java binary at: /Users/dhs/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.    

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Users/dhs/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)        

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (4 available)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 93.0.4577.82


• No issues found!

```

</details>

The code sample uses `IndexedStack` as a body of  `Scaffold` followed by `bottomNavigationBar` due to which the above exception occurs. If we comment out `body: IndexedStack(index: tabIndex, children: listScreens),` and tap on third tab directly then the exception doesn't occur.

**Comment by WasserEsser** [comment] 2022-01-25 01:28
This is not a framework bug, but a bug in your code.

The list of children that you pass to `IndexedStack` does not contain all possible elements to begin with. When changing the index using the `BottomNavigationBar`, you add an item to the list if it's not already in there. The problem is that it's a list. Adding the third screen to the list before the second screen is added obviously results in the third screen being in the second position in the list, therefore at the wrong index. There is nothing wrong with IndexedStack here.

You should consider rewriting your logic to avoid this problem or pass an already built list to begin with and not build it dynamically.

**Comment by amanv8060** [comment] 2022-02-18 09:32
this is an issue with the author's code as suggested by Marcel. This can be closed @TahaTesser .

**Comment by darshankawar** [comment] 2022-02-18 13:05
@jackdaniels247 
Please check https://github.com/flutter/flutter/issues/96797#issuecomment-1020717156 comment and try updating your code implementation as suggested.
Although the console log does say to file an issue, I see a valid reason why this can be closed based on above linked comment. With this, I'll close this an not a framework issue. If you disagree, write in comments and I'll reopen it.

**Closed by darshankawar** 2022-02-18 13:05 UTC
Labels: framework, f: material design, a: error message, has reproducible steps, found in release: 2.8, found in release: 2.9
