### ISSUE TITLE
[webview_flutter] Add back support for JavaScriptMode on web

### ISSUE THREAD

**Issue by Keetz** [flutter/flutter#126533] opened 2023-05-11 12:22 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

I just upgraded to newest versions of the webview_flutter and webview_flutter_web plugins, and the web implementation has lost some functionality.

Before I was using the JavaScriptMode to let the webview run unrestricted, but now I can't set that so I lose a lot of performance on the game I am running inside the webview.

The only alternative is to rollback the webview plugin and run on the older version before 4.0.0/0.2.0.

### Proposal

Bring back JavaScriptMode for webviews on web.

**Comment by Keetz** [comment] 2023-05-11 13:24
@darshankawar yes, but the problem is  on the webview_flutter_web package, that is needed currently for the webview to work on web, but that doesn't support it.

https://pub.dev/packages/webview_flutter_web
This is an implementation of the [webview_flutter](https://pub.dev/packages/webview_flutter) plugin for web.

_It is currently severely limited and doesn't implement most of the available functionality. The following functionality is currently available:_

- _loadRequest_
- _loadHtmlString (Without baseUrl)_

_Nothing else is currently supported._

**Comment by darshankawar** [comment] 2023-05-12 05:23
Thanks for the feedback.

**Comment by stuartmorgan** [comment] 2023-05-12 12:27
> the web implementation has lost some functionality

This functionality has never existed for the web implementation; nothing has been lost.

> Before I was using the JavaScriptMode to let the webview run unrestricted

`flutter_webview_web` does not have any JavaScript restrictions.

> but now I can't set that so I lose a lot of performance on the game I am running inside the webview.

Even on platforms where this feature is supported—which again, has never included `webview_flutter_web`, it is unrelated to performance.

Closing, as the premise of the issue is incorrect in several critical respects.

If you have a performance regression in `webview_flutter_web`, please file a new issue and fill in all of the relevant information, including code to reproduce it and the versions you have tested, and we can investigate that.

**Closed by stuartmorgan** 2023-05-12 12:27 UTC
Labels: new feature, p: webview, platform-web, package, proposal

**Comment by Keetz** [comment] 2023-05-12 12:35
@stuartmorgan setting the mode was always on the webiew_flutter part, and yes it did work on web before, even when using the web implementation on top of it.

Saying it is unrelated to performance is probably true in some technical terms, but there is no doubt in practice, my game runs solid 60 fps when setting the mode to unrestricted before upgrading to the newest version. Now without the possibility at all to set the mode, my game runs ~15 fps, no other changes.

So it is not a performance regression for webivew_flutter_web, it is all about me wanting to be able to set the mode again, like before.

**Comment by Keetz** [comment] 2023-05-15 07:47
@stuartmorgan I wish I could be of more assistant, I just know that before 4.0.0/0.2.0 if I didn't set the JavascriptMode to unrestricted my game inside the webview ran ~15 fps and if I set the unrestricted mode it would run to its limit at 60 fps, so the unrestricted mode definitely did something, maybe not intended or what it was supposed to.

Now it is not possible to set the unrestricted mode at all in combination with the web plugin as it just gives the UnimplementedError, and I see the same result where my game runs ~15 fps as before without the JavasriptMode set.

**Comment by stuartmorgan** [comment] 2023-05-15 11:42
Please see the last paragraph of [my comment above](https://github.com/flutter/flutter/issues/126533#issuecomment-1545665389).
