### ISSUE TITLE
Launch Screen is blank

### ISSUE THREAD

**Issue by Lanch92** [flutter/flutter#69269] opened 2020-10-29 02:50 UTC
Random black screen appears when first lunch app
[<img width="533" alt="启动 app，启动页随机出现黑屏" src="https://user-images.githubusercontent.com/54097292/97519498-51bc7b00-19d4-11eb-9725-3f8f5a05b261.png">](url)

console log：[VERBOSE-2:profiler_metrics_ios.mm(184)] Error retrieving thread information: (ipc/send) invalid destination port

flutter doctor：
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.1, on Mac OS X 10.15.7 19H2, locale zh-Hans-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
[✓] Android Studio (version 4.0)
[✓] Connected device (2 available)
    ! Error: iPhone is busy: Copying cache files from device. Xcode will continue when iPhone is finished. (code -10)

• No issues found!

**Comment by sohilmemon** [comment] 2020-10-29 03:05
@Lanch92 Have you properly followed documentation in order to add LaunchScreen to the app? or may be this article might help you with the problem.

https://artem-diashkin.medium.com/flutter-launch-splash-screens-1ac21282a110

**Comment by darshankawar** [comment] 2020-10-29 08:22
@Lanch92 Please provide a complete minimal reproducible code sample that shows the issue you are facing. Also provide which device and OS version are you seeing this issue on. Check above link to see if you are following all steps in order to implement launch screen.

**Comment by Lanch92** [comment] 2020-10-29 08:23
> @Lanch92 Have you properly followed documentation in order to add LaunchScreen to the app? or may be this article might help you with the problem.
> 
> https://artem-diashkin.medium.com/flutter-launch-splash-screens-1ac21282a110

not all device black, but random device random sys black

**Comment by Lanch92** [comment] 2020-10-29 08:27
> @Lanch92 Please provide a complete minimal reproducible code sample that shows the issue you are facing. Also provide which device and OS version are you seeing this issue on. Check above link to see if you are following all steps in order to implement launch screen.

Any device and any OS version could happen.  At present, on iOS14.x iPhone7p, iOS12.x iPhone7 iPhone6  see this issue

**Comment by Lanch92** [comment] 2020-10-29 08:35
> @Lanch92 Please provide a complete minimal reproducible code sample that shows the issue you are facing. Also provide which device and OS version are you seeing this issue on. Check above link to see if you are following all steps in order to implement launch screen.

Maybe it'll be clearer that way：
[
![鲁安朝 2020-10-10 16](https://user-images.githubusercontent.com/54097292/97544409-86482b00-1a04-11eb-8612-14d203a1bfa6.gif)
](url)

**Comment by darshankawar** [comment] 2020-10-29 10:44
@Lanch92 
We will need a minimal complete reproducible code sample that we can try at our end to replicate the issue.
Thanks.

**Comment by Lanch92** [comment] 2020-10-30 06:57
> @Lanch92
> We will need a minimal complete reproducible code sample that we can try at our end to replicate the issue.
> Thanks.

Empty flutter project, add LaunchScreen.png and layout LaunchScreen.storyboard to Runner
[Runner.zip](https://github.com/flutter/flutter/files/5463427/Runner.zip)

**Comment by darshankawar** [comment] 2020-10-30 07:00
@Lanch92 
Provide a complete Flutter project, not just the `Runner` module, so that we can clone the project and run the app to see the issue.

**Comment by Lanch92** [comment] 2020-10-30 07:02
> @Lanch92
> Provide a complete Flutter project, not just the `Runner` module, so that we can clone the project and run the app to see the issue.

limit 10M

**Comment by Lanch92** [comment] 2020-10-30 07:12
> @Lanch92
> Provide a complete Flutter project, not just the `Runner` module, so that we can clone the project and run the app to see the issue.

[flutter_app.zip](https://github.com/flutter/flutter/files/5463484/flutter_app.zip)

**Comment by darshankawar** [comment] 2020-10-30 13:30
@Lanch92 
Ran the code from zip you sent and was able to launch the app. Not sure if it contains the launch screen code, because I didn't see any. How to replicate the issue you are facing using the zip your shared ?

**Comment by Lanch92** [comment] 2020-10-31 02:37
> @Lanch92
> Ran the code from zip you sent and was able to launch the app. Not sure if it contains the launch screen code, because I didn't see any. How to replicate the issue you are facing using the zip your shared ?

There is no any launch screen code contains. I don't know how to replicate the issue, because it happens randomly. It may take more time to discover patterns.  Suspend the problem for the time being

**Comment by darshankawar** [comment] 2020-11-02 06:54
@Lanch92 
I am going ahead and closing this since there's no concrete steps to replicate the issue and per your comment it happens randomly. If you are able to replicate the issue consistently and have proper steps to replicate, write in comments and I'll reopen.
Thanks.

**Closed by darshankawar** 2020-11-02 06:54 UTC
Labels: in triage

**Comment by vukhacbiet** [comment] 2021-02-04 02:57
I'm facing this issue, only in iOS device version 14.2+
