### ISSUE TITLE
Crash app with Windows7 - 32bit

### ISSUE THREAD

**Issue by letungcntt** [flutter/flutter#88336] opened 2021-08-17 05:30 UTC
My app working with windows 10, but windows 7 can't run.

<img width="609" alt="Screen Shot 2021-08-17 at 12 27 26 PM" src="https://user-images.githubusercontent.com/46608407/129668654-3b6974c9-7d6d-4b17-8a90-b9f65a5dbc81.png">

**Comment by letungcntt** [comment] 2021-08-17 05:36
flutter doctor -v
```
[✓] Flutter (Channel master, 2.4.0-5.0.pre.55, on Microsoft Windows [Version 10.0.22000.132], locale en-US)
    • Flutter version 2.4.0-5.0.pre.55 at C:\Users\letung\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b549e829e8 (5 weeks ago), 2021-07-14 15:51:10 -0700
    • Engine revision 093c4ed1a3
    • Dart version 2.14.0 (build 2.14.0-312.0.dev)

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.10.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.10.31515.178
    • Windows 10 SDK version 10.0.19041.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[✓] VS Code (version 1.59.0)
    • VS Code at C:\Users\letung\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.25.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22000.132]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 92.0.4515.131
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 91.0.864.64

! Doctor found issues in 2 categories.

**Comment by TahaTesser** [comment] 2021-08-17 07:48
Hi @letungcntt 
Closing as duplicate of https://github.com/flutter/flutter/issues/14925#
Check this [comment](https://github.com/flutter/flutter/issues/14925#issuecomment-369077739)

**Closed by TahaTesser** 2021-08-17 07:48 UTC
Labels: in triage
