### ISSUE TITLE
Scaffold.bottomNavigationBar should not assume a background color

### ISSUE THREAD

**Issue by cedvdb** [flutter/flutter#104938] opened 2022-05-29 23:11 UTC
Currently scaffolds sets a background color of surface onto the bottomNavigationBar. This is an issue when some parts of the bottom layer needs to be transparent (border radius).

It results to stuff like this (the darker triangle is not supposed to be there):

![image](https://user-images.githubusercontent.com/22280985/170894977-d9a0b25c-b5df-4c7b-b8c0-702e8b14af90.png)

# repro

```dart
import 'package:flutter/material.dart';

const Color darkBlue = Color.fromARGB(255, 18, 32, 47);

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: darkBlue,
      ),
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: ListView.builder(
          itemCount: 20,
          itemBuilder: (ctx, index) =>
              const Card(child: SizedBox(height: 200, width: 200)),
        ),
        bottomNavigationBar: const SizedBox(
          height: 70,
          child: Text('bottom'),
        ),
      ),
    );
  }
}

```

**Comment by exaby73** [comment] 2022-05-30 10:23
This issue is reproducible in the latest stable and master channels. The background visible at the corners of the `Container` after applying a `borderRadius` picks the parent `Scaffold`'s `backgroundColor`.

Changing the `bottomNavigationBar` property to `bottomSheet`, the corners then pick the `scaffoldBackgroundColor` of the default `ThemeData` and not the `scaffoldBackgroundColor` overridden in the `theme` of `MaterialApp`.

<details><summary>Screenshots and videos</summary>

###### Using `bottomNavigationBar`, see corners

https://user-images.githubusercontent.com/50555895/170972384-08019fc4-1955-458b-bb75-9372223a6aad.mov

###### Using `bottomSheet` instead

<img width="300" alt="image" src="https://user-images.githubusercontent.com/50555895/170971427-8f486647-9b95-4bf3-b3fc-0f88aa0a83b5.png">

</details>

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

final darkBlue = Colors.blue.shade900;

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: darkBlue,
      ),
      debugShowCheckedModeBanner: false,
      home: const HomePage(),
    );
  }
}

class HomePage extends StatelessWidget {
  const HomePage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: ListView.separated(
        itemCount: 20,
        itemBuilder: (ctx, index) {
          return Container(
            color: Colors.blue,
            height: 200,
          );
        },
        separatorBuilder: (context, index) => const SizedBox(height: 10),
      ),
      bottomNavigationBar: Container(
        decoration: BoxDecoration(
          borderRadius: const BorderRadius.vertical(top: Radius.circular(20)),
          color: Colors.blue.shade800,
        ),
        height: 70,
        child: Center(
          child: Text(
            'Bottom Navigation Bar',
            style: Theme.of(context)
                .textTheme
                .headline6
                ?.copyWith(color: Colors.white),
          ),
        ),
      ),
    );
  }
}
```

</details>

<details><summary><code>flutter doctor -v</code> (Stable)</summary>

```
[✓] Flutter (Channel stable, 3.0.1, on macOS 12.4 21F79 darwin-arm, locale en-US)
    • Flutter version 3.0.1 at /Users/nabeelparkar/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (10 days ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/nabeelparkar/Library/Android/sdk/
    • Platform android-32, build-tools 32.1.0-rc1
    • ANDROID_SDK_ROOT = /Users/nabeelparkar/Library/Android/sdk/
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /Applications/Brave Browser.app/Contents/MacOS/Brave Browser

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.1.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 67.1.4
    • Dart plugin version 221.5591.58

[✓] VS Code (version 1.67.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.40.0

[✓] Connected device (4 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554                        • android-arm64  • Android 12 (API 32) (emulator)
    • iPhone 13 Pro Max (mobile)  • 16B8F156-111C-489F-A6E5-2D79142036B4 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-5 (simulator)
    • macOS (desktop)             • macos                                • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)                • chrome                               • web-javascript • Brave Browser 102.1.39.111

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

<details><summary><code>flutter doctor -v</code> (Master)</summary>

```
[✓] Flutter (Channel master, 3.1.0-0.0.pre.1005, on macOS 12.4 21F79 darwin-arm, locale en-US)
    • Flutter version 3.1.0-0.0.pre.1005 at /Users/nabeelparkar/fvm/versions/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c2e10541f3 (2 hours ago), 2022-05-30 00:18:09 -0400
    • Engine revision bb9926b0e6
    • Dart version 2.18.0 (build 2.18.0-151.0.dev)
    • DevTools version 2.13.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/nabeelparkar/Library/Android/sdk/
    • Platform android-32, build-tools 32.1.0-rc1
    • ANDROID_SDK_ROOT = /Users/nabeelparkar/Library/Android/sdk/
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /Applications/Brave Browser.app/Contents/MacOS/Brave Browser

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.1.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 67.1.4
    • Dart plugin version 221.5591.58

[✓] VS Code (version 1.67.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.40.0

[✓] Connected device (4 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554                        • android-arm64  • Android 12 (API 32) (emulator)
    • iPhone 13 Pro Max (mobile)  • 16B8F156-111C-489F-A6E5-2D79142036B4 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-5 (simulator)
    • macOS (desktop)             • macos                                • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)                • chrome                               • web-javascript • Brave Browser 102.1.39.111

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by cedvdb** [comment] 2022-05-30 14:54
Note that using bottomSheet you can set a transparent background with:

```
   bottomSheetTheme: BottomSheetThemeData(backgroundColor: Colors.transparent),
```

The same cannot be said about nav rail

```
        navigationRailTheme: NavigationRailThemeData(backgroundColor: Colors.transparent),
```

**Comment by exaby73** [comment] 2022-05-31 06:43
When using a `bottomSheet`, the following works:

```
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: darkBlue,
        bottomSheetTheme: const BottomSheetThemeData(
          backgroundColor: Colors.transparent,
        ),
      ),
```

When using a `bottonNavigationBar`, following should work but doesn't

```
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: darkBlue,
        bottomNavigationBarTheme: const BottomNavigationBarThemeData(
          backgroundColor: Colors.transparent,
        ),
      ),
```

**Comment by cedvdb** [comment] 2022-05-31 09:36
the extend body works

**Comment by bleroux** [comment] 2022-05-31 12:05
@cedvdb
Thanks for this code sample.
When running this code sample, the color near the round corners is the scaffold background color.
As the bottomNavigationBar is part of the Scaffold, it is intended (from [Scaffold.backgroundColor documentation](https://api.flutter.dev/flutter/material/Scaffold/backgroundColor.html): "The color of the [Material](https://api.flutter.dev/flutter/material/Material-class.html) widget that underlies the entire Scaffold.").

Did you expect the green color from this screenshot?

![image](https://user-images.githubusercontent.com/840911/171167679-3334fb94-5c38-454d-932f-d8000c8ab87d.png)

(I set the Card color to Colors.green to make it easier to visualize)

<details>
<summary>Updated code sample</summary>

```dart

import 'package:flutter/material.dart';

const Color darkBlue = Color.fromARGB(255, 18, 32, 47);

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: darkBlue,
      ),
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: ListView.builder(
          itemCount: 20,
          itemBuilder: (ctx, index) =>
              const Card(child: SizedBox(height: 200, width: 200), color: Colors.green,),
        ),
        bottomNavigationBar:  SizedBox(
          height: 70,
          child: Card(
            color: Colors.cyan,
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(40),
            ),
            margin: const EdgeInsets.all(0),
            child: const SizedBox(
              width: double.infinity,
            ),
          ),
        ),
      ),
    );
  }
}
```
</details>

**Comment by bleroux** [comment] 2022-05-31 12:52
I wrote the following explanation before seeing your last comment (we both reach the same conclusion) :
"The green color can't be shown near the round corner, not because Scaffold set a background color before drawing the bottom navigation bar but because the `Scaffold.bottomNavigationBar` widget is drawn below the body. The green color is the Card color, and this Card belongs to `Scaffold.body`. The only way to have the widget drawn in `Scaffold.bottomNavigationBar` in front the body is to use `Scaffold.extendBody`."

It's possible that there is an issue with extendBody. I will close this issue as it will be more actionnable to file a new one when you have a repro when using extendBody. Thank you to investigate this.

**Closed by bleroux** 2022-05-31 12:52 UTC
Labels: framework, f: material design, r: invalid, found in release: 3.0, found in release: 3.1

**Comment by cedvdb** [comment] 2022-06-02 14:45
@bleroux FYI I opened the follow up for extendBody https://github.com/flutter/flutter/issues/105027

**Comment by bleroux** [comment] 2022-06-02 14:56
@cedvdb
Many thanks! I will have a look next week, I'm working on another issue for the moment.
