### ISSUE TITLE
The method 'signInWithGoogle' isn't defined for the class 'FirebaseAuth.

### ISSUE THREAD

**Issue by pojoba02** [flutter/flutter#27133] opened 2019-01-26 18:36 UTC
## Steps to Reproduce

1. ...After `firebase_auth` and `google_sign_in` update, and AndroidX migrate am facing an issue  with this code, it was working fine doe
2. ... 
```dart
if (await auth.currentUser() == null) {
    GoogleSignInAuthentication credentials =
        await googleSignIn.currentUser.authentication;
    await auth.signInWithGoogle(
        idToken: credentials.idToken, accessToken: credentials.accessToken);
  }
}
```
3. ...

## Logs

```
  +50 ms] executing: [/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +67 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [/flutter/] git rev-parse --abbrev-ref HEAD
[  +15 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[        ] executing: [/flutter/] git ls-remote --get-url origin
[  +14 ms] Exit code 0 from: git ls-remote --get-url origin
[   +6 ms] https://github.com/flutter/flutter.git
[   +1 ms] executing: [/flutter/] git log -n 1 --pretty=format:%H
[  +34 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] 04546cc69c627d8223b67097f957207a2904ac26
[        ] executing: [/flutter/] git log -n 1 --pretty=format:%ar
[  +31 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[        ] 11 hours ago
[   +1 ms] executing: [/flutter/] git describe --match v*.*.* --first-parent --long --tags
[ +156 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[   +5 ms] v1.1.9-194-g04546cc69
[ +576 ms] executing: /Users/test/Library/Android/sdk/platform-tools/adb devices -l
[   +9 ms] Exit code 0 from: /Users/test/Library/Android/sdk/platform-tools/adb devices -l
[        ] List of devices attached
           emulator-5554          device product:sdk_gphone_x86 model:Android_SDK_built_for_x86 device:generic_x86 transport_id:2
           emulator-5556          device product:sdk_gphone_x86 model:Android_SDK_built_for_x86 device:generic_x86 transport_id:3
[  +31 ms] executing: idevice_id -h
[  +60 ms] /usr/bin/xcrun simctl list --json devices
[ +304 ms] More than one device connected; please specify a device with the '-d <deviceId>' flag, or use '-d all' to act on all devices.
[  +12 ms] /Users/test/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell getprop
[  +57 ms] ro.hardware = ranchu
[   +3 ms] /Users/test/Library/Android/sdk/platform-tools/adb -s emulator-5556 shell getprop
[  +51 ms] ro.hardware = ranchu
[   +3 ms] Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)
[   +2 ms] Android SDK built for x86 • emulator-5556 • android-x86 • Android 9 (API 28) (emulator)
[  +19 ms] "flutter run" took 1,039ms.
[        ] "flutter run" took 1,039ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:26:3)
#1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:235:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:531:11)
<asynchronous suspension>
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:488:33)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#5      _rootRun (dart:async/zone.dart:1124:13)
#6      _CustomZone.run (dart:async/zone.dart:1021:19)
#7      _runZoned (dart:async/zone.dart:1516:10)
#8      runZoned (dart:async/zone.dart:1463:12)
#9      AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#10     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:479:20)
#11     CommandRunner.runCommand (package:args/command_runner.dart:196:27)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:396:21)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#14     _rootRun (dart:async/zone.dart:1124:13)
#15     _CustomZone.run (dart:async/zone.dart:1021:19)
#16     _runZoned (dart:async/zone.dart:1516:10)
#17     runZoned (dart:async/zone.dart:1463:12)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#19     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:356:19)
<asynchronous suspension>
#20     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:111:29)
#21     new Future.sync (dart:async/future.dart:224:31)
#22     CommandRunner.run (package:args/command_runner.dart:111:11)
#23     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:242:18)
#24     run.<anonymous closure> (package:flutter_tools/runner.dart:60:20)
<asynchronous suspension>
#25     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#26     _rootRun (dart:async/zone.dart:1124:13)
#27     _CustomZone.run (dart:async/zone.dart:1021:19)
#28     _runZoned (dart:async/zone.dart:1516:10)
#29     runZoned (dart:async/zone.dart:1463:12)
#30     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#31     runInContext (package:flutter_tools/src/context_runner.dart:49:24)
<asynchronous suspension>
#32     run (package:flutter_tools/runner.dart:51:10)
#33     main (package:flutter_tools/executable.dart:51:9)
<asynchronous suspension>
#34     main (file:///flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#35     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:298:32)
#36     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)


```

```
Analyzing ...                                                

   info • This class (or a class which this class inherits from) is marked as '@immutable', but one or more of its instance fields are not final: ActivityFeedItem.mediaPreview,
          ActivityFeedItem.actionText • lib/activity_feed.dart:65:7 • must_be_immutable
   info • Unused import: 'dart:async' • lib/edit_profile_page.dart:2:8 • unused_import
   info • This class (or a class which this class inherits from) is marked as '@immutable', but one or more of its instance fields are not final: EditProfilePage.nameController,
          EditProfilePage.bioController • lib/edit_profile_page.dart:7:7 • must_be_immutable
   info • Name non-constant identifiers using lowerCamelCase • lib/edit_profile_page.dart:11:35 • non_constant_identifier_names
   info • Unused import: 'package:async/async.dart' • lib/feed.dart:4:8 • unused_import
  error • The method 'signInWithGoogle' isn't defined for the class 'FirebaseAuth' • lib/main.dart:46:16 • undefined_method
  error • The method 'signInWithGoogle' isn't defined for the class 'FirebaseAuth' • lib/main.dart:90:16 • undefined_method

```

```
[✓] Flutter (Channel master, v1.1.10-pre.194, on Mac OS X 10.14.4 18E174f, locale en)
    • Flutter version 1.1.10-pre.194 at /flutter
    • Framework revision 04546cc69c (11 hours ago), 2019-01-25 23:37:19 -0800
    • Engine revision 36acd02c94
    • Dart version 2.1.1 (build 2.1.1-dev.3.2 f4afaee422)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/test/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.0.beta.1

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 32.0.1
    • Dart plugin version 182.5124
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.30.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.21.1

[✓] Connected device (2 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)
    • Android SDK built for x86 • emulator-5556 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!

```

**Comment by ebastuart** [comment] 2019-01-26 19:37
Look at the example on git ... they changed the procedure.
[https://github.com/flutter/plugins/blob/master/packages/firebase_auth/example/lib/main.dart](url)

hope that helps

```
  Future<String> _testSignInWithGoogle() async {
    final GoogleSignInAccount googleUser = await _googleSignIn.signIn();
    final GoogleSignInAuthentication googleAuth =
        await googleUser.authentication;
    final AuthCredential credential = GoogleAuthProvider.getCredential(
      accessToken: googleAuth.accessToken,
      idToken: googleAuth.idToken,
    );
    final FirebaseUser user = await _auth.signInWithCredential(credential);
    assert(user.email != null);
    assert(user.displayName != null);
    assert(!user.isAnonymous);
    assert(await user.getIdToken() != null);

    final FirebaseUser currentUser = await _auth.currentUser();
    assert(user.uid == currentUser.uid);

    return 'signInWithGoogle succeeded: $user';
  }
```

**Comment by rubensdemelo** [comment] 2019-01-26 20:44
> Look at the example on git ... they changed the procedure.
> [https://github.com/flutter/plugins/blob/master/packages/firebase_auth/example/lib/main.dart](url)
> 
> hope that helps
> 
> ```
>   Future<String> _testSignInWithGoogle() async {
>     final GoogleSignInAccount googleUser = await _googleSignIn.signIn();
>     final GoogleSignInAuthentication googleAuth =
>         await googleUser.authentication;
>     final AuthCredential credential = GoogleAuthProvider.getCredential(
>       accessToken: googleAuth.accessToken,
>       idToken: googleAuth.idToken,
>     );
>     final FirebaseUser user = await _auth.signInWithCredential(credential);
>     assert(user.email != null);
>     assert(user.displayName != null);
>     assert(!user.isAnonymous);
>     assert(await user.getIdToken() != null);
> 
>     final FirebaseUser currentUser = await _auth.currentUser();
>     assert(user.uid == currentUser.uid);
> 
>     return 'signInWithGoogle succeeded: $user';
>   }
> ```

It returns :

`PlatformException(ERROR_INTERNAL_ERROR, An internal error has occurred, print and inspect the error details for more information., null)`

**Comment by ebastuart** [comment] 2019-01-26 20:49
Can you add this to **build.gradle** in the android app folder and try it again. 

`implementation 'com.google.firebase:firebase-auth:16.1.0'`

**Comment by pojoba02** [comment] 2019-01-26 21:35
@rubensdemelo & @ebastuart, a lot of issues with this update and upgrade, have to downgrade all my packages to get it working since i have no time..

**Comment by zoechi** [comment] 2019-01-27 17:35
Duplicate of #27119

**Closed by zoechi** 2019-01-27 17:35 UTC
Labels: p: firebase, p: firebase_auth, p: first party, p: google_sign_in, plugin, severe: crash

**Comment by iftee939** [comment] 2019-06-02 19:40
Why is this coed giving an error??

 FirebaseUser firebaseUser = await firebaseAuth.signInWith(
      accessToken: googleAuth.accessToken,
      idToken: googleAuth.idToken,
    );

imports: 

import 'dart:async';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';
import 'package:google_sign_in/google_sign_in.dart';
import 'package:shared_preferences/shared_preferences.dart';

Pubspec:-

  firebase_core: ^0.4.0+3
  firebase_auth: ^0.11.1+5
  cloud_firestore: ^0.12.1
  firebase_storage: ^3.0.0
  google_sign_in: ^4.0.1+3

**Comment by relativityboy** [comment] 2019-06-18 13:19
@ebastuart  - your url is bad. you have `(url)` not `(https://github.com/flutter/plugins/blob/master/packages/firebase_auth/example/lib/main.dart)`

**Comment by Sajan-poudel** [comment] 2019-08-03 05:52
>     final FirebaseUser user = await _auth.signInWithCredential(credential);

i am getting this error ............

<i>A value of type 'AuthResult' can't be assigned to a variable of type 'FirebaseUser'.
Try changing the type of the variable, or casting the right-hand type to 'FirebaseUser'.</i>

**Comment by samuelrajasingh** [comment] 2019-08-24 04:19
I added cast now its working

**Comment by samuelrajasingh** [comment] 2019-08-24 04:40
final FirebaseUser user = (await _auth.signInWithCredential(credential)).user;
 use this line instead of that It'll work just fine .

**Comment by kroikie** [comment] 2019-10-13 18:30
@pojoba02

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/484. Any further collaboration will be done there.

**Comment by exeptionerror** [comment] 2021-06-26 05:24
All Possible working solution [[Solved] Undefined class ‘FirebaseUser’](https://fluttercorner.com/undefined-class-firebaseuser/)
