### ISSUE TITLE
Flutter image not rendering in physical device after picking up from gallery or taking shots from camera but in emulator, it only renders after pressing hot-restart while running the app.

### ISSUE THREAD

**Issue by thealiflab** [flutter/flutter#56503] opened 2020-05-07 01:59 UTC
I am using [ImagePicker](https://pub.dev/packages/image_picker) package to pick image both from camera and gallery. For cropping, I m using [ImageCropper](https://pub.dev/packages/image_cropper) package. 

All this package working well in the emulator but I have to press hot-restart to appear an image in the canvas. 

But in physical android device, image is not showing in the canvas after picking it and cropping it with those two packages.

You can see here the problem below: 
Physical device result: Image is not showing on the Canvas page after cropping.
![issue](https://user-images.githubusercontent.com/53125727/81243510-de900880-9031-11ea-823e-80937b5e0fbb.gif)

Emulator result: Showing the image after pressing hot-restart below
![emu](https://user-images.githubusercontent.com/53125727/81246081-7b55a480-9038-11ea-827f-8d88db4ccebe.gif)

Here is my full code of Canvas Page

```dart
import 'dart:io' as io;
import 'dart:math';
import 'dart:ui' as ui;

import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:zoom_widget/zoom_widget.dart';
import 'rectangle_painter.dart';
import 'package:image_picker/image_picker.dart';
import 'package:image_cropper/image_cropper.dart';

//constants
const buttonTextStyle = TextStyle(
  color: Colors.white,
  fontWeight: FontWeight.w900,
);

class CanvasPage extends StatefulWidget {
  @override
  _CanvasPageState createState() => _CanvasPageState();
}

class _CanvasPageState extends State<CanvasPage> {
  ui.Image _image;
  Image _imageWidget;
  List<ui.Offset> _points = [
    ui.Offset(90, 120),
    ui.Offset(90, 370),
    ui.Offset(320, 370),
    ui.Offset(320, 120)
  ];
  bool _clear = false;
  int _currentlyDraggedIndex = -1;

  double x, y;

  @override
  Widget build(BuildContext context) {
    final AppBar appBar = AppBar(
      backgroundColor: Theme.of(context).colorScheme.primary,
      title: Text(
        'Canvas',
        style: TextStyle(
          color: Colors.white,
        ),
      ),
      centerTitle: true,
    );

    return Scaffold(
      appBar: appBar,
      body: Column(
        mainAxisAlignment: MainAxisAlignment.center,
//        crossAxisAlignment: CrossAxisAlignment.center,
        children: <Widget>[
          if (_imageWidget == null) ...[
            Row(
              mainAxisAlignment: MainAxisAlignment.center,
              children: <Widget>[
                FloatingActionButton.extended(
                  onPressed: () => _pickImage(ImageSource.camera),
                  label: Text(
                    'Open Camera',
                    style: buttonTextStyle,
                  ),
                  icon: Icon(
                    Icons.camera,
                    color: Colors.white,
                  ),
                  heroTag: UniqueKey(),
                ),
                SizedBox(
                  width: 15,
                ),
                FloatingActionButton.extended(
                  onPressed: () => _pickImage(ImageSource.gallery),
                  label: Text(
                    'Open Gallery',
                    style: buttonTextStyle,
                  ),
                  icon: Icon(
                    Icons.photo_library,
                    color: Colors.white,
                  ),
                  heroTag: UniqueKey(),
                ),
              ],
            ),
          ],
          if (_imageWidget != null) ...[
            Expanded(
              child: Zoom(
                width: _image.width.toDouble(),
                height: _image.height.toDouble(),
                backgroundColor: Colors.white,
                colorScrollBars: Colors.cyan,
                opacityScrollBars: 0.9,
                scrollWeight: 10.0,
                centerOnScale: true,
                enableScroll: true,
                child: FittedBox(
                  fit: BoxFit.fill,
                  child: GestureDetector(
                    onPanStart: (DragStartDetails details) {
                      // get distance from points to check if is in circle
                      int indexMatch = -1;
                      for (int i = 0; i < _points.length; i++) {
                        double distance = sqrt(pow(
                                details.localPosition.dx - _points[i].dx, 2) +
                            pow(details.localPosition.dy - _points[i].dy, 2));
                        if (distance <= 30) {
                          indexMatch = i;
                          break;
                        }
                      }
                      if (indexMatch != -1) {
                        _currentlyDraggedIndex = indexMatch;
                      }
                    },
                    onPanUpdate: (DragUpdateDetails details) {
                      if (_currentlyDraggedIndex != -1) {
                        setState(() {
                          _points = List.from(_points);
                          _points[_currentlyDraggedIndex] =
                              details.localPosition;
                        });
                      }
                    },
                    onPanEnd: (_) {
                      setState(() {
                        _currentlyDraggedIndex = -1;
                      });
                    },
                    child: SizedBox(
                      width: _image.width.toDouble(),
                      height: _image.height.toDouble(),
                      child: CustomPaint(
                        painter: RectanglePainter(
                            points: _points, clear: _clear, image: _image),
                      ),
                    ),
                  ),
                ),
              ),
            )
          ]
        ],
      ),
    );
  }

  Future _pickImage(ImageSource imageSource) async {
    try {
      io.File imageFile = await ImagePicker.pickImage(source: imageSource);
      print("Before Cropping");
      print(" Image Size is : ${imageFile.lengthSync() / 1000} kB");

      io.File croppedImage = await ImageCropper.cropImage(
        sourcePath: imageFile.path,
        aspectRatioPresets: io.Platform.isAndroid
            ? [
                CropAspectRatioPreset.square,
                CropAspectRatioPreset.ratio3x2,
                CropAspectRatioPreset.original,
                CropAspectRatioPreset.ratio4x3,
                CropAspectRatioPreset.ratio16x9
              ]
            : [
                CropAspectRatioPreset.original,
                CropAspectRatioPreset.square,
                CropAspectRatioPreset.ratio3x2,
                CropAspectRatioPreset.ratio4x3,
                CropAspectRatioPreset.ratio5x3,
                CropAspectRatioPreset.ratio5x4,
                CropAspectRatioPreset.ratio7x5,
                CropAspectRatioPreset.ratio16x9
              ],
        androidUiSettings: AndroidUiSettings(
            toolbarTitle: 'Image Edit',
            toolbarColor: Colors.cyan,
            toolbarWidgetColor: Colors.white,
            initAspectRatio: CropAspectRatioPreset.original,
            lockAspectRatio: false),
        iosUiSettings: IOSUiSettings(
          title: 'Edit',
        ),
      );

      Future<ui.Image> _load(String asset) async {
        ByteData data = await rootBundle.load(asset);
        ui.Codec codec =
            await ui.instantiateImageCodec(data.buffer.asUint8List());
        ui.FrameInfo fi = await codec.getNextFrame();
        return fi.image;
      }

      ui.Image finalImg = await _load(croppedImage.path);
      setState(() {
        _imageWidget = Image.file(croppedImage);
        _image = finalImg;

        print("After");
        print(" Image Size is : ${imageFile.lengthSync() / 1000} kB");
        print("Image height: ${_image.height}");
        print("Image width: ${_image.width}");
      });
    } catch (e) {
      print(e);
    }
  }
}


```

Flutter Doctor:

```terminal
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.12.13+hotfix.9, on Microsoft Windows [Version 10.0.18363.778], locale en-US)       
 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[√] Android Studio (version 3.6)
[!] VS Code (version 1.44.2)
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[√] Connected device (1 available)

! Doctor found issues in 1 category.
```
I'm using the android studio to build apps instead of VS code editor so that I didn't install the VS Code flutter plugin in my system.

**Comment by TahaTesser** [comment] 2020-05-07 15:42
Hi @thealiflab 
In your code sample you're  missing code for `RectanglePainter`
it immediately crash when picking or taking image 
Thank you

**Comment by thealiflab** [comment] 2020-05-07 16:34
@TahaTesser I implemented it in another dart file, you can see at the top of my code that I imported it like this
```dart
import 'rectangle_painter.dart';
```

**Comment by TahaTesser** [comment] 2020-05-08 11:12
Hi @thealiflab 
I know you have not provided any code `rectangle_painter`

**Comment by thealiflab** [comment] 2020-05-08 20:35
Then why you said that I'm missing code for `RectanglePainter`
Are there any lines that I missed for `RectanglePainter`? Would you be more specific?

**Comment by thealiflab** [comment] 2020-05-09 04:02
@dnfield Hi there, Can you please look at my issue?

I have been seeing that you were responding similarly issue previously, that's why I mentioned you to look at my issue. Please help!

**Comment by TahaTesser** [comment] 2020-05-11 07:07
@thealiflab 

This is your code i have tired assemble, if you can try this then you can see you have not provided any code for `import 'rectangle_painter.dart';`

<details> 
<summary>Code Sample</summary> 

``` 
import 'dart:io' as io;
import 'dart:math';
import 'dart:ui' as ui;

import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:zoom_widget/zoom_widget.dart';
import 'rectangle_painter.dart';
import 'package:image_picker/image_picker.dart';
import 'package:image_cropper/image_cropper.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Material App',
      theme: ThemeData.dark(),
      home: CanvasPage(),
    );
  }
}

//constants
const buttonTextStyle = TextStyle(
  color: Colors.white,
  fontWeight: FontWeight.w900,
);

class CanvasPage extends StatefulWidget {
  @override
  _CanvasPageState createState() => _CanvasPageState();
}

class _CanvasPageState extends State<CanvasPage> {
  ui.Image _image;
  Image _imageWidget;
  List<ui.Offset> _points = [
    ui.Offset(90, 120),
    ui.Offset(90, 370),
    ui.Offset(320, 370),
    ui.Offset(320, 120)
  ];
  bool _clear = false;
  int _currentlyDraggedIndex = -1;

  double x, y;

  @override
  Widget build(BuildContext context) {
    final AppBar appBar = AppBar(
      backgroundColor: Theme.of(context).colorScheme.primary,
      title: Text(
        'Canvas',
        style: TextStyle(
          color: Colors.white,
        ),
      ),
      centerTitle: true,
    );

    return Scaffold(
      appBar: appBar,
      body: Column(
        mainAxisAlignment: MainAxisAlignment.center,
//        crossAxisAlignment: CrossAxisAlignment.center,
        children: <Widget>[
          if (_imageWidget == null) ...[
            Row(
              mainAxisAlignment: MainAxisAlignment.center,
              children: <Widget>[
                FloatingActionButton.extended(
                  onPressed: () => _pickImage(ImageSource.camera),
                  label: Text(
                    'Open Camera',
                    style: buttonTextStyle,
                  ),
                  icon: Icon(
                    Icons.camera,
                    color: Colors.white,
                  ),
                  heroTag: UniqueKey(),
                ),
                SizedBox(
                  width: 15,
                ),
                FloatingActionButton.extended(
                  onPressed: () => _pickImage(ImageSource.gallery),
                  label: Text(
                    'Open Gallery',
                    style: buttonTextStyle,
                  ),
                  icon: Icon(
                    Icons.photo_library,
                    color: Colors.white,
                  ),
                  heroTag: UniqueKey(),
                ),
              ],
            ),
          ],
          if (_imageWidget != null) ...[
            Expanded(
              child: Zoom(
                width: _image.width.toDouble(),
                height: _image.height.toDouble(),
                backgroundColor: Colors.white,
                colorScrollBars: Colors.cyan,
                opacityScrollBars: 0.9,
                scrollWeight: 10.0,
                centerOnScale: true,
                enableScroll: true,
                child: FittedBox(
                  fit: BoxFit.fill,
                  child: GestureDetector(
                    onPanStart: (DragStartDetails details) {
                      // get distance from points to check if is in circle
                      int indexMatch = -1;
                      for (int i = 0; i < _points.length; i++) {
                        double distance = sqrt(pow(
                                details.localPosition.dx - _points[i].dx, 2) +
                            pow(details.localPosition.dy - _points[i].dy, 2));
                        if (distance <= 30) {
                          indexMatch = i;
                          break;
                        }
                      }
                      if (indexMatch != -1) {
                        _currentlyDraggedIndex = indexMatch;
                      }
                    },
                    onPanUpdate: (DragUpdateDetails details) {
                      if (_currentlyDraggedIndex != -1) {
                        setState(() {
                          _points = List.from(_points);
                          _points[_currentlyDraggedIndex] =
                              details.localPosition;
                        });
                      }
                    },
                    onPanEnd: (_) {
                      setState(() {
                        _currentlyDraggedIndex = -1;
                      });
                    },
                    child: SizedBox(
                      width: _image.width.toDouble(),
                      height: _image.height.toDouble(),
                      child: CustomPaint(
                        painter: RectanglePainter(
                            points: _points, clear: _clear, image: _image),
                      ),
                    ),
                  ),
                ),
              ),
            )
          ]
        ],
      ),
    );
  }

  Future _pickImage(ImageSource imageSource) async {
    try {
      io.File imageFile = await ImagePicker.pickImage(source: imageSource);
      print("Before Cropping");
      print(" Image Size is : ${imageFile.lengthSync() / 1000} kB");

      io.File croppedImage = await ImageCropper.cropImage(
        sourcePath: imageFile.path,
        aspectRatioPresets: io.Platform.isAndroid
            ? [
                CropAspectRatioPreset.square,
                CropAspectRatioPreset.ratio3x2,
                CropAspectRatioPreset.original,
                CropAspectRatioPreset.ratio4x3,
                CropAspectRatioPreset.ratio16x9
              ]
            : [
                CropAspectRatioPreset.original,
                CropAspectRatioPreset.square,
                CropAspectRatioPreset.ratio3x2,
                CropAspectRatioPreset.ratio4x3,
                CropAspectRatioPreset.ratio5x3,
                CropAspectRatioPreset.ratio5x4,
                CropAspectRatioPreset.ratio7x5,
                CropAspectRatioPreset.ratio16x9
              ],
        androidUiSettings: AndroidUiSettings(
            toolbarTitle: 'Image Edit',
            toolbarColor: Colors.cyan,
            toolbarWidgetColor: Colors.white,
            initAspectRatio: CropAspectRatioPreset.original,
            lockAspectRatio: false),
        iosUiSettings: IOSUiSettings(
          title: 'Edit',
        ),
      );

      Future<ui.Image> _load(String asset) async {
        ByteData data = await rootBundle.load(asset);
        ui.Codec codec =
            await ui.instantiateImageCodec(data.buffer.asUint8List());
        ui.FrameInfo fi = await codec.getNextFrame();
        return fi.image;
      }

      ui.Image finalImg = await _load(croppedImage.path);
      setState(() {
        _imageWidget = Image.file(croppedImage);
        _image = finalImg;

        print("After");
        print(" Image Size is : ${imageFile.lengthSync() / 1000} kB");
        print("Image height: ${_image.height}");
        print("Image width: ${_image.width}");
      });
    } catch (e) {
      print(e);
    }
  }
}

``` 

</details> 

and commenting the code you have not provided results in crash when picking image
```
                    child: SizedBox(
                      width: _image.width.toDouble(),
                      height: _image.height.toDouble(),
                      // child: CustomPaint(
                      //   painter: RectanglePainter(
                      //       points: _points, clear: _clear, image: _image),
                      // ),
                    ),
```

Please created a gist and provide complete **runnable code sample**
Thank you

**Comment by thealiflab** [comment] 2020-05-12 17:26
@TahaTesser 

RectanglePainter

```dart

import 'package:flutter/material.dart';
import 'dart:ui' as ui;

class RectanglePainter extends CustomPainter {
  List<Offset> points;
  bool clear;
  final ui.Image image;

  RectanglePainter(
      {@required this.points, @required this.clear, @required this.image});

  @override
  void paint(Canvas canvas, Size size) {
    final paint = Paint()
      ..color = Colors.red
      ..strokeCap = StrokeCap.square
      ..style = PaintingStyle.fill
      ..strokeWidth = 2;

    final outputRect =
        Rect.fromPoints(ui.Offset.zero, ui.Offset(size.width, size.height));
    final Size imageSize =
        Size(image.width.toDouble(), image.height.toDouble());
    final FittedSizes sizes =
        applyBoxFit(BoxFit.contain, imageSize, outputRect.size);
    final Rect inputSubrect =
        Alignment.center.inscribe(sizes.source, Offset.zero & imageSize);
    final Rect outputSubrect =
        Alignment.center.inscribe(sizes.destination, outputRect);
    canvas.drawImageRect(image, inputSubrect, outputSubrect, paint);
    if (!clear) {
      final circlePaint = Paint()
        ..color = Colors.red
        ..strokeCap = StrokeCap.square
        ..style = PaintingStyle.fill
        ..blendMode = BlendMode.multiply
        ..strokeWidth = 2;

      for (int i = 0; i < points.length; i++) {
        if (i + 1 == points.length) {
          canvas.drawLine(points[i], points[0], paint);
        } else {
          canvas.drawLine(points[i], points[i + 1], paint);
        }
        canvas.drawCircle(points[i], 10, circlePaint);
      }
    }
  }

  @override
  bool shouldRepaint(RectanglePainter oldPainter) =>
      oldPainter.points != points || clear;
}

```

**Comment by TahaTesser** [comment] 2020-05-13 07:12
Hi @thealiflab 

You might still be missing something, this sample simply crashes unlike your gif

Please remove any third party package and provide minimal reproducible sample that address the flutter itself 

<details> 
<summary>Code Sample</summary> 

``` 
import 'dart:io' as io;
import 'dart:math';
import 'dart:ui' as ui;

import 'package:flutter/material.dart';
import 'dart:ui' as ui;
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:zoom_widget/zoom_widget.dart';
import 'package:image_picker/image_picker.dart';
import 'package:image_cropper/image_cropper.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Material App',
      theme: ThemeData.dark(),
      home: CanvasPage(),
    );
  }
}

//constants
const buttonTextStyle = TextStyle(
  color: Colors.white,
  fontWeight: FontWeight.w900,
);

class CanvasPage extends StatefulWidget {
  @override
  _CanvasPageState createState() => _CanvasPageState();
}

class _CanvasPageState extends State<CanvasPage> {
  ui.Image _image;
  Image _imageWidget;
  List<ui.Offset> _points = [
    ui.Offset(90, 120),
    ui.Offset(90, 370),
    ui.Offset(320, 370),
    ui.Offset(320, 120)
  ];
  bool _clear = false;
  int _currentlyDraggedIndex = -1;

  double x, y;

  @override
  Widget build(BuildContext context) {
    final AppBar appBar = AppBar(
      backgroundColor: Theme.of(context).colorScheme.primary,
      title: Text(
        'Canvas',
        style: TextStyle(
          color: Colors.white,
        ),
      ),
      centerTitle: true,
    );

    return Scaffold(
      appBar: appBar,
      body: Column(
        mainAxisAlignment: MainAxisAlignment.center,
//        crossAxisAlignment: CrossAxisAlignment.center,
        children: <Widget>[
          if (_imageWidget == null) ...[
            Row(
              mainAxisAlignment: MainAxisAlignment.center,
              children: <Widget>[
                FloatingActionButton.extended(
                  onPressed: () => _pickImage(ImageSource.camera),
                  label: Text(
                    'Open Camera',
                    style: buttonTextStyle,
                  ),
                  icon: Icon(
                    Icons.camera,
                    color: Colors.white,
                  ),
                  heroTag: UniqueKey(),
                ),
                SizedBox(
                  width: 15,
                ),
                FloatingActionButton.extended(
                  onPressed: () => _pickImage(ImageSource.gallery),
                  label: Text(
                    'Open Gallery',
                    style: buttonTextStyle,
                  ),
                  icon: Icon(
                    Icons.photo_library,
                    color: Colors.white,
                  ),
                  heroTag: UniqueKey(),
                ),
              ],
            ),
          ],
          if (_imageWidget != null) ...[
            Expanded(
              child: Zoom(
                width: _image.width.toDouble(),
                height: _image.height.toDouble(),
                backgroundColor: Colors.white,
                colorScrollBars: Colors.cyan,
                opacityScrollBars: 0.9,
                scrollWeight: 10.0,
                centerOnScale: true,
                enableScroll: true,
                child: FittedBox(
                  fit: BoxFit.fill,
                  child: GestureDetector(
                    onPanStart: (DragStartDetails details) {
                      // get distance from points to check if is in circle
                      int indexMatch = -1;
                      for (int i = 0; i < _points.length; i++) {
                        double distance = sqrt(pow(
                                details.localPosition.dx - _points[i].dx, 2) +
                            pow(details.localPosition.dy - _points[i].dy, 2));
                        if (distance <= 30) {
                          indexMatch = i;
                          break;
                        }
                      }
                      if (indexMatch != -1) {
                        _currentlyDraggedIndex = indexMatch;
                      }
                    },
                    onPanUpdate: (DragUpdateDetails details) {
                      if (_currentlyDraggedIndex != -1) {
                        setState(() {
                          _points = List.from(_points);
                          _points[_currentlyDraggedIndex] =
                              details.localPosition;
                        });
                      }
                    },
                    onPanEnd: (_) {
                      setState(() {
                        _currentlyDraggedIndex = -1;
                      });
                    },
                    child: SizedBox(
                      width: _image.width.toDouble(),
                      height: _image.height.toDouble(),
                      child: CustomPaint(
                        painter: RectanglePainter(
                            points: _points, clear: _clear, image: _image),
                      ),
                    ),
                  ),
                ),
              ),
            )
          ]
        ],
      ),
    );
  }

  Future _pickImage(ImageSource imageSource) async {
    try {
      io.File imageFile = await ImagePicker.pickImage(source: imageSource);
      print("Before Cropping");
      print(" Image Size is : ${imageFile.lengthSync() / 1000} kB");

      io.File croppedImage = await ImageCropper.cropImage(
        sourcePath: imageFile.path,
        aspectRatioPresets: io.Platform.isAndroid
            ? [
                CropAspectRatioPreset.square,
                CropAspectRatioPreset.ratio3x2,
                CropAspectRatioPreset.original,
                CropAspectRatioPreset.ratio4x3,
                CropAspectRatioPreset.ratio16x9
              ]
            : [
                CropAspectRatioPreset.original,
                CropAspectRatioPreset.square,
                CropAspectRatioPreset.ratio3x2,
                CropAspectRatioPreset.ratio4x3,
                CropAspectRatioPreset.ratio5x3,
                CropAspectRatioPreset.ratio5x4,
                CropAspectRatioPreset.ratio7x5,
                CropAspectRatioPreset.ratio16x9
              ],
        androidUiSettings: AndroidUiSettings(
            toolbarTitle: 'Image Edit',
            toolbarColor: Colors.cyan,
            toolbarWidgetColor: Colors.white,
            initAspectRatio: CropAspectRatioPreset.original,
            lockAspectRatio: false),
        iosUiSettings: IOSUiSettings(
          title: 'Edit',
        ),
      );

      Future<ui.Image> _load(String asset) async {
        ByteData data = await rootBundle.load(asset);
        ui.Codec codec =
            await ui.instantiateImageCodec(data.buffer.asUint8List());
        ui.FrameInfo fi = await codec.getNextFrame();
        return fi.image;
      }

      ui.Image finalImg = await _load(croppedImage.path);
      setState(() {
        _imageWidget = Image.file(croppedImage);
        _image = finalImg;

        print("After");
        print(" Image Size is : ${imageFile.lengthSync() / 1000} kB");
        print("Image height: ${_image.height}");
        print("Image width: ${_image.width}");
      });
    } catch (e) {
      print(e);
    }
  }
}

class RectanglePainter extends CustomPainter {
  List<Offset> points;
  bool clear;
  final ui.Image image;

  RectanglePainter(
      {@required this.points, @required this.clear, @required this.image});

  @override
  void paint(Canvas canvas, Size size) {
    final paint = Paint()
      ..color = Colors.red
      ..strokeCap = StrokeCap.square
      ..style = PaintingStyle.fill
      ..strokeWidth = 2;

    final outputRect =
        Rect.fromPoints(ui.Offset.zero, ui.Offset(size.width, size.height));
    final Size imageSize =
        Size(image.width.toDouble(), image.height.toDouble());
    final FittedSizes sizes =
        applyBoxFit(BoxFit.contain, imageSize, outputRect.size);
    final Rect inputSubrect =
        Alignment.center.inscribe(sizes.source, Offset.zero & imageSize);
    final Rect outputSubrect =
        Alignment.center.inscribe(sizes.destination, outputRect);
    canvas.drawImageRect(image, inputSubrect, outputSubrect, paint);
    if (!clear) {
      final circlePaint = Paint()
        ..color = Colors.red
        ..strokeCap = StrokeCap.square
        ..style = PaintingStyle.fill
        ..blendMode = BlendMode.multiply
        ..strokeWidth = 2;

      for (int i = 0; i < points.length; i++) {
        if (i + 1 == points.length) {
          canvas.drawLine(points[i], points[0], paint);
        } else {
          canvas.drawLine(points[i], points[i + 1], paint);
        }
        canvas.drawCircle(points[i], 10, circlePaint);
      }
    }
  }

  @override
  bool shouldRepaint(RectanglePainter oldPainter) =>
      oldPainter.points != points || clear;
}

``` 

</details> 

Thank you

**Comment by thealiflab** [comment] 2020-05-13 14:17
@TahaTesser Sorry for the inconvenience, also thank you so much for your kind lookup in my issue.

I invite you as a collaborator in my private repository so that you can look closely by cloning it and accessing into my full code. Thank you 😇

**Comment by dnfield** [comment] 2020-05-13 15:14
@thealiflab - thanks for continuing to work on narrowing this down.

Unfortunately, sharing private repositories with team members isn't really as helpful for this tracker. We all have a limited amount of time to work on a _lot_ of bugs from a lot of users. We naturally end up prioritizing ones that have clear, reproducible cases, and especially ones that can be worked on from those cases by anyone on the team, which is distributed throughout the world.

Sharing a private repository has two problems - a) the person you shared it with may not be the one who actually works on fixing this bug for a variety of reasons and b) it's quite likely that your repository is _not_ a minimal reproduction, requiring lots of extra time to figure out the root cause of your issue.

Sharing a repository may be appropriate, but please try to create a public one that is the minimum amount of code needed to reproduce this issue, and please provide clear instructions about how to reproduce the issue (including framework revision, device/emulator versions and models, etc.).

**Comment by thealiflab** [comment] 2020-05-19 00:42
I make this repo public @dnfield 

Here it is
https://github.com/thealiflab/ImageShapeApp

**Comment by TahaTesser** [comment] 2020-05-19 08:41
Hi @thealiflab 
Thanks for providing reproducible sample

Looks like only images only shown on homepage when they are cropped using preset aspect ratio and not when cropped using freeform 
Run the app on physical device or emulator 
Select preset crop or using freeform to form one of the preset aspect 

![flutter_01](https://user-images.githubusercontent.com/48603081/82304053-6df5ce00-99d9-11ea-82c8-2835738d40fb.png)

also i noticed this sometimes image is not loaded even after using preset 
```
I/flutter (12230): Unable to load asset: /data/user/0/com.ahmedalif.imageshapeapp/cache/image_cropper_1589877315132.jpg

```

and also you need adjust result preview with custom aspect ratio that matches your image aspect ratio

Looking at these issues, it looks like it is related to [image_cropper](https://pub.dev/packages/image_cropper) and not related Flutter or image_picker

<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel stable, v1.17.1, on Mac OS X 10.15.4 19E287, locale en-GB)
    • Flutter version 1.17.1 at /Users/tahatesser/Code/flutter_stable
    • Framework revision f7a6a7906b (6 days ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/tahatesser/Code/SDK
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.2

[✓] Connected device (2 available)
    • SM M305F                  • 32003c30dc19668f • android-arm64 • Android 10
      (API 29)
    • Android SDK built for x86 • emulator-5554    • android-x86   • Android 10
      (API 29) (emulator)

• No issues found!
``` 

</details> 

Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it 
Thank you

**Closed by TahaTesser** 2020-05-19 08:41 UTC
Labels: in triage
