### ISSUE TITLE
Camera not working after connecting my app to firebase , Using Pick_image 0.7.3

### ISSUE THREAD

**Issue by shema-ryan** [flutter/flutter#79004] opened 2021-03-24 20:18 UTC
using the latest version 0.7.3 before connecting my app to firebase everything work smoothly , an issue arise after connecting it to firebase 
using the same code as before .  This is kind weird 
E/flutter (22908): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: MissingPluginException(No implementation found for method pickImage on channel plugins.flutter.io/image_picker)
E/flutter (22908): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:7)
E/flutter (22908): <asynchronous suspension>
E/flutter (22908): #1      MethodChannelImagePicker.pickImage (package:image_picker_platform_interface/src/method_channel/method_channel_image_picker.dart:29:20)
E/flutter (22908): <asynchronous suspension>
E/flutter (22908): #2      _MyHomePageState.takePicture (package:garage/main.dart:73:17)
E/flutter (22908): <asynchronous suspension>
E/flutter (22908):

**Comment by iapicca** [comment] 2021-03-24 23:18
possible duplicate of https://github.com/flutter/flutter/issues/78625

@shema-ryan 
please consider that [firebase](https://firebase.flutter.dev/) is a 3rd party plugin, please  provide your `flutter doctor -v`, your `flutter run -v` 
and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) **_without 3rd party plugins_**

**Comment by TahaTesser** [comment] 2021-03-25 09:45
Hi @shema-ryan 
Are you running in release mode?   https://github.com/flutter/flutter/issues/78625

Can you please provide your `flutter doctor -v` and `flutter run --verbose` or `flutter run --release --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
Thank you

**Comment by pedromassangocode** [comment] 2021-04-16 08:51
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2021-04-16 08:51 UTC
Labels: in triage, waiting for customer response
