### ISSUE TITLE
In Flutter Web on iOS phone, when editing a TextField,it shows the system's default inputAccessoryView and cause some bug.

### ISSUE THREAD

**Issue by hakama99** [flutter/flutter#155388] opened 2024-09-19 03:49 UTC
### Steps to reproduce

In Flutter Web on iOS phone, when editing a TextField, the system's default inputAccessoryView can cause the focus to stay active even after the "Complete" button is pressed, leading to unexpected behavior where the keyboard disappears but the focus remains.

In demo video, my blue container is always on the bottom , but after press default inputAccessoryView "complete", it seperate a white space on the bottom.

### Expected results

1.dismiss default inputAccessoryView
2.do not seperate a white space on the bottom

### Actual results

1.keyboard disappears but the focus remains.
2.seperate a white space on the bottom

### Code sample

<details open><summary>Code sample</summary>

```dart
class OrderSearch extends ConsumerStatefulWidget {
  @override
  ConsumerState<OrderSearch> createState() => _OrderSearchState();
}

class _OrderSearchState extends ConsumerState<OrderSearch> {
  @override
  void dispose() {
    super.dispose();
  }

  @override
  void didChangeDependencies() async {
    super.didChangeDependencies();
  }

  var text = "step";

  @override
  void initState() {
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Column(
        children: [
          Expanded(
            child: SingleChildScrollView(
              child: Column(
                mainAxisAlignment: MainAxisAlignment.start,
                crossAxisAlignment: CrossAxisAlignment.stretch,
                mainAxisSize: MainAxisSize.max,
                children: [
                  SizedBox(height: 500),
                  TextField(
                    onEditingComplete: () {
                      print("onEditingComplete");
                      text = "onEditingComplete";
                      setState(() {});
                    },
                    onSubmitted: (value) {
                      print("onSubmitted");
                      text = "onSubmitted";
                      setState(() {});
                    },
                  ),
                  Text(text),
                  SizedBox(height: 100),
                ],
              ),
            ),
          ),
          Container(color: Colors.blue, height: 100),
        ],
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/user-attachments/assets/5fdc8454-5244-4dad-b50c-30519355def9

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.24.1, on macOS 14.5 23F79 darwin-arm64, locale zh-Hant-TW)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.92.2)
```

iphone 14
ios 17.6.1
</details>

**Comment by hakama99** [comment] 2024-09-19 03:56
here is the sample 
https://www.emmt-system.com/ecsale_test/OrderSearch

**Comment by danagbemava-nc** [comment] 2024-09-19 09:11
I believe this is a duplicate of https://github.com/flutter/flutter/issues/124205

Kindly subscribe to the original issue for updates. 

Closing from here. 

Thank you

**Closed by danagbemava-nc** 2024-09-19 09:11 UTC
Labels: in triage

**Comment by hakama99** [comment] 2024-09-20 08:49
OK, thanks for reply
