### ISSUE TITLE
The icon disappeared and turned into a color block

### ISSUE THREAD

**Issue by XGNoCopy** [flutter/flutter#72058] opened 2020-12-10 10:40 UTC
After our app has been running in the background for a long time, the normal tabbar icon becomes a color block. Not necessarily, but occasionally。Another widget turned into a pink block.

![image](https://user-images.githubusercontent.com/28725950/101761236-da235500-3b16-11eb-8504-23d3418a40b9.png)

![image](https://user-images.githubusercontent.com/28725950/101761462-22427780-3b17-11eb-81a2-f740a646c6bb.png)

**Comment by darshankawar** [comment] 2020-12-10 12:48
@XGNoCopy 
Please provide `flutter doctor -v` and a minimal complete reproducible code sample that shows the issue along with the platform on which you are seeing this issue (web or mobile).
Thanks.

**Comment by XGNoCopy** [comment] 2020-12-11 10:48
> @XGNoCopy
> Please provide `flutter doctor -v` and a minimal complete reproducible code sample that shows the issue along with the platform on which you are seeing this issue (web or mobile).
> Thanks.

Thank you for your attention, the following is a screenshot：
![image](https://user-images.githubusercontent.com/28725950/101894487-33f05180-3be1-11eb-86eb-cd45bf834ad9.png)

We guess it may be an abnormality of the Image widget, but we don't know how to solve it.

**Comment by xu-baolin** [comment] 2020-12-11 11:07
> > @XGNoCopy
> > Please provide `flutter doctor -v` and a minimal complete reproducible code sample that shows the issue along with the platform on which you are seeing this issue (web or mobile).
> > Thanks.
> 
> Thank you for your attention, the following is a screenshot：
> ![image](https://user-images.githubusercontent.com/28725950/101894487-33f05180-3be1-11eb-86eb-cd45bf834ad9.png)
> 
> We guess it may be an abnormality of the Image widget, but we don't know how to solve it.
> 
> code show as below：
> ![image](https://user-images.githubusercontent.com/28725950/101895087-03f57e00-3be2-11eb-9f10-92e346b2fa4f.png)
> 
> In order to solve the line texture of the gradient color in the vertical direction, we added "Paint.enableDithering = true;" to main.dart. I don't know if this will be a problem.

请提供可以复现问题的可运行的可复制的最小范围的代码，同时提供你所使用flutter版本的信息，这样才能方便我们复现和定位根因哈

**Comment by darshankawar** [comment] 2020-12-11 11:47
@XGNoCopy 
We will need a minimal complete reproducible code sample that we can copy paste and run in IDE to see the issue you are facing. And please provide that in text format and not in screenshots.

**Comment by XGNoCopy** [comment] 2020-12-11 12:10
> > > @XGNoCopy
> > > Please provide `flutter doctor -v` and a minimal complete reproducible code sample that shows the issue along with the platform on which you are seeing this issue (web or mobile).
> > > Thanks.
> > 
> > 
> > Thank you for your attention, the following is a screenshot：
> > ![image](https://user-images.githubusercontent.com/28725950/101894487-33f05180-3be1-11eb-86eb-cd45bf834ad9.png)
> > We guess it may be an abnormality of the Image widget, but we don't know how to solve it.
> > code show as below：
> > ![image](https://user-images.githubusercontent.com/28725950/101895087-03f57e00-3be2-11eb-9f10-92e346b2fa4f.png)
> > In order to solve the line texture of the gradient color in the vertical direction, we added "Paint.enableDithering = true;" to main.dart. I don't know if this will be a problem.
> 
> 请提供可以复现问题的可运行的可复制的最小范围的代码，同时提供你所使用flutter版本的信息，这样才能方便我们复现和定位根因哈

麻烦这里直接使用一张本地的图片资源测试。
AssetImage icon = AssetImage('assets/images/alarm/off_bg.png');
Container(
                width: 24,
                height: 24,
                child: Image(
                    color: Colors.white,
                    image: icon),
              )
这个问题不是能一定复现的，只会在 iPhone12 iOS 14.2.1 偶尔出现，程序安装之后就会出现。
flutter 版本：1.22.4
Dart 版本： 2.10.4

**Comment by darshankawar** [comment] 2020-12-11 13:59
@XGNoCopy 
So when you run above code, you see the icon (off_bg.png) disappear upon app launch ? When do you see this behavior ?

**Comment by plank-george** [comment] 2020-12-13 09:43
This problem occurs in out project , too. After user switch the app to background for a long time and then switch it back , the Image widget will turn to pink block.

**Comment by XGNoCopy** [comment] 2020-12-14 03:40
> @XGNoCopy
> So when you run above code, you see the icon (off_bg.png) disappear upon app launch ? When do you see this behavior ?


Yes, it will occasionally appear when the iOS program is first installed, and the killing process will return to normal after entering the program.

In order to solve the line texture of the gradient color in the vertical direction, we added "**Paint.enableDithering = true;"** to main.dart. I don't know if this will be a problem.

**Comment by darshankawar** [comment] 2020-12-14 06:09
@XGNoCopy 
Can you provide video of the issue you are facing ?

**Comment by XGNoCopy** [comment] 2020-12-14 12:38
> @XGNoCopy
> 您能提供您面临的问题的视频吗？
![IMG_8318](https://user-images.githubusercontent.com/28725950/102082063-3b676300-3e4c-11eb-88cb-a1c535959956.gif)

**Comment by darshankawar** [comment] 2020-12-14 13:39
@XGNoCopy 
Can you elaborate on the video as where exactly the issue is ? Is it the `Alarm` icon which is white or am I missing anything ?

**Comment by XGNoCopy** [comment] 2020-12-15 06:38
> @XGNoCopy
> Can you elaborate on the video as where exactly the issue is ? Is it the `Alarm` icon which is white or am I missing anything ?
> Also, can you also specify if the code sample you provided will help to replicate the issue ? or is there more to the code that need to be shared ?

When there is no abnormality, the icon of the white block in the video looks like this:
![image](https://user-images.githubusercontent.com/28725950/102179950-022e0200-3ee3-11eb-9c01-2376986cca1b.png)

As seen in the video, the white blocks above Alarm, Journal, Clinic, Settings, and the floating pink blocks are all Image Widgets. They should be the icons displayed normally, but they accidentally become icons when running on iOS 12.2.1. A solid color block. I cannot provide more code for the time being. The key code is that Image Widget loads a local png image.

**Comment by darshankawar** [comment] 2020-12-15 07:24
@XGNoCopy 
I am unable to replicate the issue with the given code sample. Would need a complete reproducible code sample that we can simply copy paste and run in IDE to see the issue.
Thanks.

**Comment by pedromassangocode** [comment] 2021-01-06 12:32
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2021-01-06 12:32 UTC
Labels: in triage, waiting for customer response

**Comment by xujinyang** [comment] 2021-02-03 07:52
【it will occasionally appear when the iOS program is first installed, and the killing process will return to normal after entering the program.Another case: re-actively run from the background】
we find all case happen in iphone 12 and 12 pro max

**Comment by plank-george** [comment] 2021-02-14 09:08
why did you close the issue without doing anything? have you read all the description customer response ?
**the issue only appears when you switch the app to  the background for a long time(maybe 8 or 12 hours) and then switch it back .
And we find all case happen in iPhone 12 and 12 pro max.**

Have you tried all the approach we told you to make the issue reappear?
