### ISSUE TITLE
Null check operator used on a null value in PlatformView. 

### ISSUE THREAD

**Issue by rahul-bst** [flutter/flutter#96384] opened 2022-01-10 07:39 UTC
https://github.com/flutter/flutter/blob/7fe3565a9b335b6a3aa71de1698a82b2ff0fadee/packages/flutter/lib/src/widgets/platform_view.dart#L898

setState is called when `element` is null.

Stacktrace received on crashlytics:

```
Non-fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: Null check operator used on a null value. Error thrown null.
       at State.setState(framework.dart:1108)
       at _PlatformViewLinkState._onPlatformViewCreated(platform_view.dart:889)
       at AndroidViewController.create(platform_views.dart:752)
```

**Comment by darshankawar** [comment] 2022-01-10 13:37
@rahul-bst 
Can you provide your `flutter doctor -v` and possibly a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that would throw this exception ?

**Comment by rahul-bst** [comment] 2022-01-10 13:54
Hi,

The app is built with Github Action on random remote machine where we use flutter v2.2.1. We have crashlytics added where we got this issue reported. 

flutter doctor of my machine doesn't matter much but here it goes:
`[✓] Flutter (Channel unknown, 2.2.1, on macOS 11.6.2 20G314 darwin-x64, locale en-GB)
    • Flutter version 2.2.1 at /Users/rahul/Library/flutter/flutter221/flutter2
    • Framework revision 02c026b03c (8 months ago), 2021-05-27 12:24:44 -0700
    • Engine revision 0fdb562ac8
    • Dart version 2.13.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0-rc4)
    • Android SDK at /Users/rahul/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0-rc4
    • ANDROID_HOME = /Users/rahul/Library/Android/sdk
    • Java binary at: /Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.0, Build version 13A233
    • CocoaPods version 1.11.2

[!] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] IntelliJ IDEA Community Edition (version 2021.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (1 available)
    • macOS (desktop) • macos • darwin-x64 • macOS 11.6.2 20G314 darwin-x64
    ! Error: Rahul’s iPhone is not connected. Xcode will continue when Rahul’s iPhone is connected. (code -13)

! Doctor found issues in 1 category.
`

I looked at the source code in master branch as well and it definitely has potential for the bug. By the time, `_onPlatformViewCreated` is called, the Widget might be disposed leading to above mentioned error. 

I don't have steps to reproduce it right now, but if the explanation is insufficient I can come up with set of steps to reproduce it. 

Thanks for the reply. 

Regards,
Rahul K

**Comment by darshankawar** [comment] 2022-01-11 05:53
Thanks for the update. It could be a possibililty that the widget has gone away by the time you call setState?
You can check https://master-api.flutter.dev/flutter/widgets/State/mounted.html and confirm the widget is mounted for the first time but the main thing to confirm if the widget is still mounted after it goes past any async calls ?

**Comment by Moncader** [comment] 2022-01-12 08:42
@darshankawar 
We have the coming up on Sentry/Crashlytics as well on Flutter 2.8.1 (stable).

The problem is obvious by just static code analyzing.

PlatformView's created callbacks get called from here:
https://github.com/flutter/flutter/blob/7fe3565a9b335b6a3aa71de1698a82b2ff0fadee/packages/flutter/lib/src/services/platform_views.dart#L775

This is an async function with an await in it. It's normal for an element to be in a different state before and after an `await` happens and a mounted check is always required before calling setState after an await like this.

The problem stems from the fact that this issues's crash line
https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/platform_view.dart#L898
expects this to only ever be called when not disposed (which it should not).

**Comment by Moncader** [comment] 2022-02-01 06:12
@darshankawar
Why did actions close this automatically?

We've given a direct view in to the problem and how to fix it.

**Comment by darshankawar** [comment] 2022-02-01 12:04
@Moncader 
Since this issue has `waiting` label and there wasn't any response from original author for 21 days, the bot automatically closed it.
But I am reopening this and labeling based on your findings.

**Closed** 2023-02-08 18:51 UTC
Labels: framework, a: platform-views, a: production, a: null-safety, P4
