### ISSUE TITLE
crash when minifyEnabled on Android

### ISSUE THREAD

**Issue by gaojuanjuan** [flutter/flutter#25309] opened 2018-12-13 06:42 UTC
# Error
```
Initializing gradle...                                       1.2s
Resolving dependencies...                                    6.7s
Gradle task 'assembleRelease'...
ProGuard, version 5.3.3
Reading input...
Reading program jar [C:\flutter\bin\cache\artifacts\engine\android-arm-release\flutter.jar] (filtered)
Reading program jar [C:\Users\73951\.gradle\caches\transforms-1\files-1.1\matisse-0.5.1.aar\5ad132de61ff6bde73994a36ddbfe241\jars\classes.jar] (filtered)
Reading program jar [C:\Users\73951\.gradle\caches\modules-2\files-2.1\com.github.bumptech.glide\glide\3.8.0\9bada650e1afe9c6174ddc0d113c1fce4dc26fe0\glide-3.8.0.jar] (filtered)
Reading program jar [C:\Users\73951\.gradle\caches\transforms-1\files-1.1\appcompat-v7-27.1.1.aar\eb4664dd0507b828a8df9d7f5a0e7d38\jars\classes.jar] (filtered)
Reading program jar [C:\Users\73951\.gradle\caches\modules-2\files-2.1\org.jetbrains.kotlin\kotlin-stdlib-jre7\1.2.30\b38fc19e670ebef931fef3ccdcb94eac2b65bb7d\kotlin-stdlib-jre7-1.
2.30.jar] (filtered)
Reading program jar [C:\Users\73951\.gradle\caches\transforms-1\files-1.1\support-v4-27.1.1.aar\f7cd93c32fe14c8aa41e2a7f1033dfda\jars\classes.jar] (filtered)
Reading program jar [C:\Users\73951\.gradle\caches\transforms-1\files-1.1\recyclerview-v7-27.1.1.aar\0b44cebe3afe864551d85bd949cd5d06\jars\classes.jar] (filtered)
Reading program jar [C:\Users\73951\.gradle\caches\transforms-1\files-1.1\support-fragment-27.1.1.aar\da1a6918761ebfc9834048196bd17530\jars\classes.jar] (filtered)
Reading program jar [C:\Users\73951\.gradle\caches\transforms-1\files-1.1\animated-vector-drawable-27.1.1.aar\7461f1b3f9add40d9b009dc506c5d61d\jars\classes.jar] (filtered)
Reading program jar [C:\Users\73951\.gradle\caches\transforms-1\files-1.1\support-core-ui-27.1.1.aar\0acb43feb9715eb7d1f779b5e7c70bfb\jars\classes.jar] (filtered)
Reading program jar [C:\Users\73951\.gradle\caches\transforms-1\files-1.1\support-core-utils-27.1.1.aar\d6bdf73b7f3eeaa8223aec16b63a578e\jars\classes.jar] (filtered)
Reading program jar [C:\Users\73951\.gradle\caches\transforms-1\files-1.1\support-vector-drawable-27.1.1.aar\505b6bf87513914240965d3a281a848b\jars\classes.jar] (filtered)
Reading program jar [C:\Users\73951\.gradle\caches\transforms-1\files-1.1\support-media-compat-27.1.1.aar\c11cc879e5ddbb7d091f4b8559a60654\jars\classes.jar] (filtered)
Reading program jar [C:\Users\73951\.gradle\caches\transforms-1\files-1.1\support-compat-27.1.1.aar\90c5961fb6922ebd58dd115491822bf9\jars\classes.jar] (filtered)
Reading program jar [C:\Users\73951\.gradle\caches\modules-2\files-2.1\com.android.support\support-annotations\27.1.1\39ded76b5e1ce1c5b2688e1d25cdc20ecee32007\support-annotations-2
7.1.1.jar] (filtered)
Reading program jar [C:\Users\73951\.gradle\caches\transforms-1\files-1.1\library-1.0.4.aar\721162f32b732334f0536f67cf49e994\jars\classes.jar] (filtered)
Reading program jar [C:\Users\73951\.gradle\caches\modules-2\files-2.1\org.jetbrains.kotlin\kotlin-stdlib\1.2.30\2dfac33f8b4e92c9dd1422cd286834701a6f6d6\kotlin-stdlib-1.2.30.jar] (
filtered)
Reading program jar [C:\Users\73951\.gradle\caches\transforms-1\files-1.1\library-1.0.2.aar\f4b69aeb528609a0bf40f74fbc78c3cc\jars\classes.jar] (filtered)
Reading program jar [C:\Users\73951\.gradle\caches\transforms-1\files-1.1\livedata-core-1.1.0.aar\9ebcadea932063750ca5877985a6ab56\jars\classes.jar] (filtered)
Reading program jar [C:\Users\73951\.gradle\caches\transforms-1\files-1.1\viewmodel-1.1.0.aar\5f53bea4dfb823b4e8d4121bc10dd588\jars\classes.jar] (filtered)
Reading program jar [C:\Users\73951\.gradle\caches\modules-2\files-2.1\org.jetbrains\annotations\13.0\919f0dfe192fb4e063e7dacadee7f8bb9a2672a9\annotations-13.0.jar] (filtered)
Reading program jar [C:\Users\73951\.gradle\caches\transforms-1\files-1.1\runtime-1.1.0.aar\631b7906b4cae8145ab2a6c8b195d7be\jars\classes.jar] (filtered)
Reading program jar [C:\Users\73951\.gradle\caches\modules-2\files-2.1\android.arch.lifecycle\common\1.1.0\edf3f7bfb84a7521d0599efa3b0113a0ee90f85\common-1.1.0.jar] (filtered)
Reading program jar [C:\Users\73951\.gradle\caches\transforms-1\files-1.1\runtime-1.1.0.aar\c239c0b0de3ac52c78d09bb6235ef7c3\jars\classes.jar] (filtered)
Reading program jar [C:\Users\73951\.gradle\caches\modules-2\files-2.1\android.arch.core\common\1.1.0\8007981f7d7540d89cd18471b8e5dcd2b4f99167\common-1.1.0.jar] (filtered)
Reading program jar [C:\MyWorkSpace\mengwaji_mobile\build\multi_image_picker\intermediates\intermediate-jars\release\classes.jar] (filtered)
Reading program jar [C:\MyWorkSpace\mengwaji_mobile\build\fluttertoast\intermediates\intermediate-jars\release\classes.jar] (filtered)
Reading program jar [C:\MyWorkSpace\mengwaji_mobile\build\sqflite\intermediates\intermediate-jars\release\classes.jar] (filtered)
Reading program jar [C:\MyWorkSpace\mengwaji_mobile\build\flutter_statusbar_manager\intermediates\intermediate-jars\release\classes.jar] (filtered)
Reading program jar [C:\MyWorkSpace\mengwaji_mobile\build\flutter_webview_plugin\intermediates\intermediate-jars\release\classes.jar] (filtered)
Reading program jar [C:\MyWorkSpace\mengwaji_mobile\build\url_launcher\intermediates\intermediate-jars\release\classes.jar] (filtered)
Reading program jar [C:\MyWorkSpace\mengwaji_mobile\build\statusbar\intermediates\intermediate-jars\release\classes.jar] (filtered)
Reading program jar [C:\MyWorkSpace\mengwaji_mobile\build\path_provider\intermediates\intermediate-jars\release\classes.jar] (filtered)
Reading program jar [C:\MyWorkSpace\mengwaji_mobile\build\shared_preferences\intermediates\intermediate-jars\release\classes.jar] (filtered)
Reading program jar [C:\MyWorkSpace\mengwaji_mobile\build\image_picker\intermediates\intermediate-jars\release\classes.jar] (filtered)
Reading program directory [C:\MyWorkSpace\mengwaji_mobile\build\app\intermediates\classes\release] (filtered)
Reading program jar [C:\MyWorkSpace\mengwaji_mobile\build\app\intermediates\transforms\mergeJavaRes\release\0.jar] (filtered)
Reading library jar [C:\Users\73951\AppData\Local\Android\Sdk\platforms\android-27\android.jar]
Reading library jar [C:\Users\73951\AppData\Local\Android\Sdk\platforms\android-27\optional\org.apache.http.legacy.jar]
Note: duplicate definition of library class [org.apache.http.params.HttpConnectionParams]
Note: duplicate definition of library class [org.apache.http.params.CoreConnectionPNames]
Note: duplicate definition of library class [org.apache.http.params.HttpParams]
Note: duplicate definition of library class [org.apache.http.conn.scheme.LayeredSocketFactory]
Note: duplicate definition of library class [org.apache.http.conn.scheme.SocketFactory]
Note: duplicate definition of library class [org.apache.http.conn.scheme.HostNameResolver]
Note: duplicate definition of library class [org.apache.http.conn.ConnectTimeoutException]
Note: duplicate definition of library class [android.net.http.SslCertificate]
Note: duplicate definition of library class [android.net.http.SslCertificate$DName]
Note: duplicate definition of library class [android.net.http.SslError]
Note: duplicate definition of library class [android.net.http.HttpResponseCache]
Initializing...
Note: there were 11 duplicate class definitions.
      (http://proguard.sourceforge.net/manual/troubleshooting.html#duplicateclass)
Warning: com.zhihu.matisse.engine.impl.PicassoEngine: can't find referenced class com.squareup.picasso.Picasso
Warning: com.zhihu.matisse.engine.impl.PicassoEngine: can't find referenced class com.squareup.picasso.Picasso
Warning: com.zhihu.matisse.engine.impl.PicassoEngine: can't find referenced class com.squareup.picasso.RequestCreator
Warning: com.zhihu.matisse.engine.impl.PicassoEngine: can't find referenced class com.squareup.picasso.RequestCreator
Warning: com.zhihu.matisse.engine.impl.PicassoEngine: can't find referenced class com.squareup.picasso.RequestCreator
Warning: com.zhihu.matisse.engine.impl.PicassoEngine: can't find referenced class com.squareup.picasso.RequestCreator
Warning: com.zhihu.matisse.engine.impl.PicassoEngine: can't find referenced class com.squareup.picasso.Picasso$Priority
Warning: com.zhihu.matisse.engine.impl.PicassoEngine: can't find referenced class com.squareup.picasso.RequestCreator
Warning: com.zhihu.matisse.engine.impl.PicassoEngine: can't find referenced class com.squareup.picasso.RequestCreator
Warning: com.zhihu.matisse.engine.impl.PicassoEngine: can't find referenced class com.squareup.picasso.Picasso
Warning: com.zhihu.matisse.engine.impl.PicassoEngine: can't find referenced class com.squareup.picasso.RequestCreator
Warning: com.zhihu.matisse.engine.impl.PicassoEngine: can't find referenced class com.squareup.picasso.Picasso$Priority
Note: kotlin.internal.PlatformImplementationsKt: can't find dynamically referenced class kotlin.internal.jdk8.JDK8PlatformImplementations
Note: kotlin.internal.PlatformImplementationsKt: can't find dynamically referenced class kotlin.internal.JRE8PlatformImplementations
Note: kotlin.internal.PlatformImplementationsKt: can't find dynamically referenced class kotlin.internal.jdk7.JDK7PlatformImplementations
Note: kotlin.jvm.internal.Reflection: can't find dynamically referenced class kotlin.reflect.jvm.internal.ReflectionFactoryImpl
Note: the configuration keeps the entry point 'com.flutter_webview_plugin.ObservableWebView { void setOnScrollChangedCallback(com.flutter_webview_plugin.ObservableWebView$OnScrollC
hangedCallback); }', but not the descriptor class 'com.flutter_webview_plugin.ObservableWebView$OnScrollChangedCallback'
Note: the configuration keeps the entry point 'com.zhihu.matisse.internal.ui.widget.MediaGrid { void setOnMediaGridClickListener(com.zhihu.matisse.internal.ui.widget.MediaGrid$OnMe
diaGridClickListener); }', but not the descriptor class 'com.zhihu.matisse.internal.ui.widget.MediaGrid$OnMediaGridClickListener'
Note: the configuration keeps the entry point 'it.sephiroth.android.library.imagezoom.ImageViewTouch { void setDoubleTapListener(it.sephiroth.android.library.imagezoom.ImageViewTou
ch$OnImageViewTouchDoubleTapListener); }', but not the descriptor class 'it.sephiroth.android.library.imagezoom.ImageViewTouch$OnImageViewTouchDoubleTapListener'
Note: the configuration keeps the entry point 'it.sephiroth.android.library.imagezoom.ImageViewTouch { void setSingleTapListener(it.sephiroth.android.library.imagezoom.ImageViewTou
ch$OnImageViewTouchSingleTapListener); }', but not the descriptor class 'it.sephiroth.android.library.imagezoom.ImageViewTouch$OnImageViewTouchSingleTapListener'
Note: the configuration keeps the entry point 'it.sephiroth.android.library.imagezoom.ImageViewTouchBase { void setOnDrawableChangedListener(it.sephiroth.android.library.imagezoom.
ImageViewTouchBase$OnDrawableChangeListener); }', but not the descriptor class 'it.sephiroth.android.library.imagezoom.ImageViewTouchBase$OnDrawableChangeListener'
Note: the configuration keeps the entry point 'it.sephiroth.android.library.imagezoom.ImageViewTouchBase { void setOnLayoutChangeListener(it.sephiroth.android.library.imagezoom.Ima
geViewTouchBase$OnLayoutChangeListener); }', but not the descriptor class 'it.sephiroth.android.library.imagezoom.ImageViewTouchBase$OnLayoutChangeListener'
Note: the configuration keeps the entry point 'it.sephiroth.android.library.imagezoom.ImageViewTouchBase { void setDisplayType(it.sephiroth.android.library.imagezoom.ImageViewTouch
Base$DisplayType); }', but not the descriptor class 'it.sephiroth.android.library.imagezoom.ImageViewTouchBase$DisplayType'
Note: there were 7 unkept descriptor classes in kept class members.
      You should consider explicitly keeping the mentioned classes
      (using '-keep').
      (http://proguard.sourceforge.net/manual/troubleshooting.html#descriptorclass)
Note: there were 4 unresolved dynamic references to classes or interfaces.
      You should check if you need to specify additional program jars.
      (http://proguard.sourceforge.net/manual/troubleshooting.html#dynamicalclass)
Warning: Exception while processing task java.io.IOException: Please correct the above warnings first.
Warning: there were 12 unresolved references to classes or interfaces.
         You may need to add missing library jars or update their versions.
         If your code works fine without the missing classes, you can suppress
         the warnings with '-dontwarn' options.
         (http://proguard.sourceforge.net/manual/troubleshooting.html#unresolvedclass)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesAndResourcesWithProguardForRelease'.
> Job failed, see logs for details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 15s
Gradle task 'assembleRelease'... Done                       16.3s
Gradle task assembleRelease failed with exit code 1

```
# flutter doctor
```
C:\MyWorkSpace\mengwaji_mobile>flutter doctor -v
[√] Flutter (Channel stable, v1.0.0, on Microsoft Windows [Version 10.0.17134.471], locale zh-CN)
    • Flutter version 1.0.0 at C:\flutter
    • Framework revision 5391447fae (13 days ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[!] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at C:\Users\73951\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = C:\Users\73951\AppData\Local\Android\Sdk
    • Java binary at: C:\DevelopmentTool\AndroidStudio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Android Studio (version 3.1)
    • Android Studio at C:\DevelopmentTool\AndroidStudio
    • Flutter plugin version 26.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[!] VS Code, 64-bit edition (version 1.23.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.

```

**Comment by zoechi** [comment] 2018-12-13 07:31
Duplicate of #19250

**Closed by zoechi** 2018-12-13 07:31 UTC
