### ISSUE TITLE
ShellTest.Screenshot is flaking on engine LUCI

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#65026] opened 2020-09-01 15:53 UTC
The first recent occurrence of this flake was on the Skia roll here https://github.com/flutter/engine/pull/20908.

```
[ RUN      ] ShellTest.Screenshot
../../flutter/shell/common/shell_unittests.cc:1541: Failure
Value of: reference_data->equals(screenshot_future.get().data.get())
  Actual: false
Expected: true
[  FAILED  ] ShellTest.Screenshot (119 ms)
```

Marking P0 since the tree is closed on this flake. Assigning @jason-simmons to investigate.

**Comment by dnfield** [comment] 2020-09-01 17:14
I was able to get flaky tests to reproduce more quickly by using `cpulimit`.  On macOS:

```
brew install cpulimit
# build the engine
cpulimit -l 5 out/target/shell_unittests --timeout 1000
```

Which will limit the test process to 5% of CPU and increase test timeouts since they'll likely take longer.

**Comment by dnfield** [comment] 2020-09-01 17:15
This should work on Linux too, although there you wouldn't use brew to get cpulimit :) Could try `sudo apt install cpulimit`, which I think should work.

**Comment by jason-simmons** [comment] 2020-09-01 22:30
I haven't been able to reproduce this.  I tried local Linux and Mac environments as well as running a locally built binary on a Mac LUCI bot.  Using the cpulimit tool also did not reproduce the test failure.

I'll try adding logging of the screenshot data so we can debug more the next time this test flakes on LUCI.

**Comment by jason-simmons** [comment] 2020-09-01 23:16
@blasten says that he was able to reproduce this and that it should be fixed by https://github.com/flutter/engine/pull/20931/commits/918a976f673b8a9afd77e8b5252a47848238a5c8

**Comment by dnfield** [comment] 2020-09-02 05:27
I've seen this in my presubmits a few times now, most recently in https://ci.chromium.org/p/flutter/builders/try/Mac%20Host%20Engine/14107

**Comment by jason-simmons** [comment] 2020-09-02 14:55
The proposed fix is part of https://github.com/flutter/engine/pull/20931, which has not landed yet.

The ShellTest.Screenshot failure happened in the presubmit of the PR that adds logging to the test:
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8870313825102458816/+/steps/Host_Tests_for_host_profile/0/stdout

In the failed run, the test captured a screenshot image that was the expected size but was blank.

**Comment by dnfield** [comment] 2020-09-02 15:58
Maybe we should just disable the test for now until the fix for it lands.

**Comment by dnfield** [comment] 2020-09-02 15:59
...and I see the fix already landed haha.  Sounds like we can lower the priority of this one until we see it flaking again?

I think we should still add the logging though.

**Comment by blasten** [comment] 2020-09-03 15:56
This issue seems fixed now.

**Closed by blasten** 2020-09-03 15:56 UTC
Labels: P0, engine, passed first triage, team: flakes
