### ISSUE TITLE
Segmentation fault in flutter build

### ISSUE THREAD

**Issue by timfreiheit** [flutter/flutter#21623] opened 2018-09-09 21:20 UTC
``` flutter build apk ``` crashes with the message

```
===== CRASH =====
version=2.1.0-dev.4.0.flutter-cd9a42239f (Fri Sep 7 21:08:23 2018 +0000) on "macos_simarm"
si_signo=Segmentation fault: 11(11), si_code=1, si_addr=0x148
Dart snapshot generator failed with exit code -6
Snapshotting exited with non-zero exit code: -6

FAILURE: Build failed with an exception.
```

## flutter doctor -v
```
[✓] Flutter (Channel master, v0.8.2-pre.24, on Mac OS X 10.13.6 17G65, locale en-DE)
    • Flutter version 0.8.2-pre.24 at XXXXXXX
    • Framework revision 4d9bbc10f2 (14 hours ago), 2018-09-09 03:15:34 -0400
    • Engine revision 1770f88548
    • Dart version 2.1.0-dev.4.0.flutter-cd9a42239f

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.0-rc1)
    • Android SDK at XXXXXXX/android_sdk
    • Android NDK at XXXXXXX/android_sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.0-rc1
    • ANDROID_HOME = XXXXXXX/android_sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 28.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[!] IntelliJ IDEA Community Edition (version 2017.3.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins


```

**Comment by zoechi** [comment] 2018-09-11 10:39
Can you please provide more information about how to reproduce?

**Comment by timfreiheit** [comment] 2018-09-11 11:02
I will try to create a minimal project to reproduce the crash without needing to share my whole project.

**Comment by zoechi** [comment] 2018-09-11 11:04
Are you seeing the same issues with the latest `beta`?

**Comment by timfreiheit** [comment] 2018-09-11 11:09
yes the problem appears there too

**Comment by timfreiheit** [comment] 2018-09-13 07:35
It seems that https://github.com/flutter/flutter/issues/21685 address the same issue. I will try to investigate further if the fix does not solve my problem as well

**Comment by mraleph** [comment] 2018-09-18 17:38
The fix for #21685 has reached master channel of Flutter - please try upgrading and let us know if it still does not work. Thanks for the report.

**Comment by mraleph** [comment] 2018-09-18 17:38
Duplicate of #21685

**Closed by mraleph** 2018-09-18 17:38 UTC
Labels: dependency: dart, severe: crash, tool

**Comment by kaumudpa** [comment] 2018-09-25 12:32
Flutter V0.8.2 which is currently Flutter Release Preview 2 still has the problem and the app gives similar output, Requesting the team to change the release preview 2 to v0.8.7 from 0.8.2
