### ISSUE TITLE
Module 'cloud_firestore' not found

### ISSUE THREAD

**Issue by luccaayerza** [flutter/flutter#79688] opened 2021-04-03 02:13 UTC
I am coding an app that is made on Flutter. I use Firebase Firestore as a database. I added cloud_firestore as a dependency in pubspec.yaml. When I build the apk for android it works perfectly fine, but in Xcode when I'm trying to build the app for iOS I have an error ( attached image ) 'Module cloud_firestore' not found, all the other dependencies are working. I've tried everything: pod install, pod update, remove Podfile, remove Podfile.lock, I even created a blank app and added cloud_firestore as dependency and it still happens.
<img width="1231" alt="pubspec" src="https://user-images.githubusercontent.com/76658044/113465234-e2c2d280-9408-11eb-9d66-155fb3984ee6.png">
<img width="1792" alt="xcode-error" src="https://user-images.githubusercontent.com/76658044/113465236-e5252c80-9408-11eb-8451-5c5474509e4d.png">

**Comment by Abhishek01039** [comment] 2021-04-03 03:36
Hello @luccaayerza 
https://stackoverflow.com/questions/64362285/flutter-on-ios-fatal-error-module-cloud-firestore-not-found
can you please have a look into it?
Thanks

**Comment by luccaayerza** [comment] 2021-04-03 16:03
Hello @Abhishek01039, thanks for answering. I tried what you suggested and other things but I couldn't solve it. Do you have any other suggestions to fix it. Thanks

**Comment by Abhishek01039** [comment] 2021-04-04 03:39
Hello @luccaayerza 
https://github.com/FirebaseExtended/flutterfire/issues/1979
Please take a look here then.
Thanks

**Comment by wliumelb** [comment] 2021-04-04 04:25
I'm having the same issue since upgrading to 2.0.4

**Comment by pedromassangocode** [comment] 2021-04-05 11:35
Hi @luccaayerza 
From what I can see, the issue is related to a FlutterFire plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by pedromassangocode** 2021-04-05 11:35 UTC
Labels: in triage

**Comment by luccaayerza** [comment] 2021-04-05 11:42
Hi @pedromassango, I appreciate your answer. I thought the issue was related to FlutterFire, but after making some tests I got to a conclusion. When I build the app is the problem, but when I run it on a device it is perfectly. So I think it is a Flutter Error.

**Comment by pedromassangocode** [comment] 2021-04-06 14:27
> If you disagree, please write in the comments,
> providing your `flutter doctor -v`, your `flutter run -v`, your `pubspec.yaml`
> a minimal reproducible code sample that does not use 3rd party plugins,
> and I will reopen it.

**Comment by bbudhiana** [comment] 2021-06-19 04:47
I have a same issue too, its annoying when you have project run well in android but not work in iOS, 'fatal error: module 'cloud_firestore' not found' bugs make me re-thinking using flutter in app project, please some one have solution for this
