### ISSUE TITLE
im unable to allow access media file on my mobile/emulator using flutter driver

### ISSUE THREAD

**Issue by dassusovan** [flutter/flutter#84918] opened 2021-06-19 18:22 UTC
**Already used this below code** 

final envVars = Platform.environment;
      final adbPath = join(
        envVars['ANDROID_SDK_ROOT'] ?? envVars['ANDROID_HOME'],
        'platform-tools',
        Platform.isWindows ? 'adb.exe' : 'adb',
      );
      await Process.run(adbPath, [
        'shell',
        'pm',
        'grant',
        'app_id', // replace with your app id
        'android.permission.ACCESS_MEDIA_LOCATION'
      ]);
      
**NOT WORKING !!!**

**Comment by darshankawar** [comment] 2021-06-21 10:45
Closing this as duplicate of https://github.com/flutter/flutter/issues/34345

**Closed by darshankawar** 2021-06-21 10:45 UTC
Labels: in triage
