### ISSUE TITLE
Stable release has to execute `Roll pub packages` or merge newer pinned versions for the stable channel because versions lag behind

### ISSUE THREAD

**Issue by MrCsabaToth** [flutter/flutter#114199] opened 2022-10-28 00:19 UTC
Steps to reproduce:

1. Install the most recent stable channel Flutter SDK (like 3.3.5, but this bug is true for all 3.3.x as I saw).
2. Check `integration_test`'s `pubspec.yaml` and the pinned package versions there
3. [vector_math](https://pub.dev/packages/vector_math/versions) was pinned to non latest version.

This is an issue since the `integration_test` became part of the SDK. Even though the `vector_math` is pinned to the most recent `2.1.4` version in the master branch and periodic `Roll pub packages` tasks keep that recent, but the `stable` branch lags behind despite of version releases. Currently I have to perform a `flutter update-packages --force-upgrade` manually on my installation.

Why is this a problem for me? My app doesn't just transitively depend on `vector_math` via `integration_test` but also directly. `pub outdated` and also Dependabot alerts constantly warned me that I don't have the most recent version of `vector_math`. I was not able to upgrade my direct dependency in my app because I got an error about the conflicting dependencies. Tracking that down I ended up at the auto generated section of `pubspec.yaml` of `integration_test` where everything is precisely pinned (https://github.com/flutter/flutter/blob/master/packages/integration_test/pubspec.yaml `vector_math: 2.1.3 # THIS LINE IS AUTOGENERATED - TO UPDATE USE "flutter update-packages --force-upgrade"`).

When I tried to upgrade these pinned versions with a less intrusive `flutter update-packages` nothing got changed. `flutter update-packages --force-upgrade` upgraded the versions however my Flutter installation became modified because it contained those code changes. Every time since then I have to undo these and then perform the `flutter update-packages --force-upgrade` after installation manually.

Questions:
1. Why are the latest stable releases didn't have the latest `vector_math`? Should that branch get latest pinned version via merge or some `Roll pub packages` doesnt' execute a sa part of stable release on that branch?
2. Why are those versions pinned precisely, why cannot they just be pinned by the major version (using the `^` version referencing)? This would avoid these problems in case the roll task would lag behind.
3. Maybe should it be executed on my local install right after upgrade? (I guess no because a change by that would make the repo clone un-upgradeable without stashing)

Related:
* https://github.com/TrackMyIndoorWorkout/TrackMyIndoorWorkout/commit/b934e39becd7104eedfe48a5f8d0176b3ef62566
* https://github.com/TrackMyIndoorWorkout/TrackMyIndoorWorkout/commit/fbaf4ac7c3a086b90249296b5c336df3782982f0
* The master branch is right now at vector_math 2.1.4
* The stable branch for the several Flutter 3.3.x releases is at vector_math 2.1.2 https://github.com/flutter/flutter/blob/6928314d505d2bb4777be05e45d7808a5aa91d2a/packages/integration_test/pubspec.yaml#L38

**Comment by MrCsabaToth** [comment] 2022-10-28 00:25
All right, so now I upgraded my SDK from 3.3.5 stable to 3.3.6. And a fresh pub get yields:
```
/home/csaba/flutter/bin/flutter --no-color pub get
Running "flutter pub get" in track_my_indoor_exercise...        
Because every version of integration_test from sdk depends on vector_math 2.1.2 and track_my_indoor_exercise depends on vector_math ^2.1.4, integration_test from sdk is forbidden.
So, because track_my_indoor_exercise depends on integration_test from sdk, version solving failed.
pub get failed (1; So, because track_my_indoor_exercise depends on integration_test from sdk, version solving failed.)
Process finished with exit code 1
```
And this is in the `integration_test`'s `pubspec.yaml`: `vector_math: 2.1.2 # THIS LINE IS AUTOGENERATED - TO UPDATE USE "flutter update-packages --force-upgrade"`

**Comment by MrCsabaToth** [comment] 2022-10-28 00:26
```
$ flutter doctor -v
[✓] Flutter (Channel stable, 3.3.6, on Devuan GNU/Linux 5 (daedalus/ceres) 6.0.0-2-amd64, locale en_US.UTF-8)
    • Flutter version 3.3.6 on channel stable at /home/csaba/flutter
    • Upstream repository https://github.com/flutter/flutter
    • Framework revision 6928314d50 (2 days ago), 2022-10-25 16:34:41 -0400
    • Engine revision 3ad69d7be3
    • Dart version 2.18.2
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /home/csaba/Android/Sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /home/csaba/android-studio-preview/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Debian clang version 14.0.6-6
    • cmake version 3.24.2
    • ninja version 1.11.1
    • pkg-config version 0.29.2

[✓] Android Studio (version 2021.3)
    • Android Studio at /home/csaba/android-studio-preview
    • Flutter plugin version 70.2.3
    • Dart plugin version 213.7433
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] Android Studio
    • Android Studio at /home/csaba/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.72.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.50.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Devuan GNU/Linux 5 (daedalus/ceres) 6.0.0-2-amd64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 107.0.5304.68

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

**Comment by MrCsabaToth** [comment] 2022-10-28 00:29
Ah, OK, so the problem is that the stable version's branch lags waaay behind with a 2.1.2 `vector_math`. https://github.com/flutter/flutter/blob/6928314d505d2bb4777be05e45d7808a5aa91d2a/packages/integration_test/pubspec.yaml#L38

Why is this not refreshed during release either by merge or executing `flutter update-packages --force-upgrade` as a part of some kind of a `Roll pub packages` for that branch?

**Comment by MrCsabaToth** [comment] 2022-10-28 00:32
I was trying to name this better, feel free to rename it. This is not infra?

**Comment by MrCsabaToth** [comment] 2022-10-28 00:39
I modified the original entry based on my realization

**Comment by jonahwilliams** [comment] 2022-10-28 02:23
The 3.3 version was branched in early July. The newer vector_math versions were released in August, and then at the end of September. Once a stable version has branched, the only updates it receives are critical and low risk bug fixes. In general, rolling versions is generally neither critical nor low risk, though we have done so in the past if there _is_ a severe issue. Based on my read of the vector_math changelog, these are appear to be cleanups and small API changes that don't necessitate a cherry pick.

The fact that the versions of this stable are out of date compared to the current master branch is working as intended. There is a trade-off to be made between how frequently a channel receives updates. More frequent updates mean more frequent bugs and regressions. Stable exists at one end up the spectrum, getting updates only a few times a year. If this is too slow, you might consider working on the beta channel until a new stable is released.

**Comment by stuartmorgan** [comment] 2022-10-28 02:25
> 1. Why are the latest stable releases didn't have the latest `vector_math`?

Because the only thing that lands in stable releases are cherry picks, following [the documented process](https://github.com/flutter/flutter/wiki/Flutter-Cherrypick-Process). Per those docs:

>> Stability of the release will be the overarching goal, so only high impactful and critical cherrypicks will be allowed across Dart and Flutter.

A dependency would only be updated in stable if doing do addressed a critical issue.

> 2\. Why are those versions pinned precisely, why cannot they just be pinned by the major version (using the `^` version referencing)

So that someone running a given version of Flutter is running the same code as everyone else running that version of Flutter: the version that was stabilized through the beta period and tested by everyone running on master and beta leading up to the stable release.

There has been discussion about reducing the number of dependencies we use in order to minimize this issue, but the specific request here of unpinning dependencies, or rolling them in stable as a standard practice, are not things we would do as they would undermine stability of the stable branch. Given that, I'm going to close this issue.

**Closed by stuartmorgan** 2022-10-28 02:25 UTC

**Comment by MrCsabaToth** [comment] 2022-10-28 02:44
Got it. Before the nullability I was on the beta channel, maybe I'll move back.
