### ISSUE TITLE
[web]: Scrollbar thumb get stuck in Listview.builder on web

### ISSUE THREAD

**Issue by nilesh-athghara** [flutter/flutter#86863] opened 2021-07-22 11:51 UTC
Scrolling through scroll thumb freezes the screen on web
Google Chrome : Version 91.0.4472.124 (Official Build) (64-bit)
Flutter : 2.2.0 • channel stable

Sample to reproduce the issue:

<details> 
<summary>minimal code sample</summary> 

```dart
import 'package:flutter/material.dart';
import 'package:http/http.dart';
import 'dart:convert';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, @required this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  List<Check> list = [];
  bool loading = false;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: loading
          ? Center(
              child: CircularProgressIndicator(),
            )
          : Scrollbar(
              isAlwaysShown: true,
              showTrackOnHover: true,
              child: ListView.builder(
                itemBuilder: (BuildContext context, int index) {
                  return Container(
                    color: Colors.grey[400],
                    width: 50,
                    margin: EdgeInsets.all(20),
                    child: Text(list[index].name),
                  );
                },
                itemCount: list.length,
              )),
      floatingActionButton: FloatingActionButton(
        onPressed: () async {
          setState(() {
            loading = true;
          });
          Response response = await get(Uri.parse(
              "https://raw.githubusercontent.com/lutangar/cities.json/master/cities.json"));
          setState(() {
            loading = false;
            list = checkFromJson(response.body);
            print(list.length);
          });
        },
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ),
    );
  }
}

List<Check> checkFromJson(String str) =>
    List<Check>.from(json.decode(str).map((x) => Check.fromJson(x)));

String checkToJson(List<Check> data) =>
    json.encode(List<dynamic>.from(data.map((x) => x.toJson())));

class Check {
  Check({
    this.country,
    this.name,
    this.lat,
    this.lng,
  });

  String country;
  String name;
  String lat;
  String lng;

  factory Check.fromJson(Map<String, dynamic> json) => Check(
        country: json["country"],
        name: json["name"],
        lat: json["lat"],
        lng: json["lng"],
      );

  Map<String, dynamic> toJson() => {
        "country": country,
        "name": name,
        "lat": lat,
        "lng": lng,
      };
}
``` 

</details>

**Comment by TahaTesser** [comment] 2021-07-22 14:23
HI @nilesh-athghara 
Thanks list you're loading from the link contains 772,616 lines of json data, both web qand desktop scroll are stuck

Even when I load this d[ata]( https://raw.githubusercontent.com/lutangar/cities.json/master/cities.json) directly in Google Chrome, itt takes few to load and render, you can see Googlr Chrome scroll also gets stuck for couple of seconds then it works .

I am not sure this is realistic to load these many lines whe when regular brwoser also can't handle it well.
Please try loading in batches, insteado of loading 3 quarter of a million lines of code at once

if you can reproduce the issue with reasonble size list, please provide update ssample

Thank you

**Comment by nilesh-athghara** [comment] 2021-08-03 14:36
Hi @TahaTesser, Thanks for the support. 
Scrolling is not smooth when scrolled through scroll thumb at fast speed. List length is reasonable in the sample - 50 items.

<Details>
<summary>flutter doctor -v</summary>

```

[√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.19043.1110], locale en-IN)
    • Flutter version 2.2.3 at C:\flutter
    • Framework revision f4abaa0735 (5 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\NILESH\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] IntelliJ IDEA Ultimate Edition (version 2021.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2019.3.4
    • Flutter plugin version 57.0.5
    • Dart plugin version 211.7665

[√] VS Code, 64-bit edition (version 1.58.0)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.24.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 92.0.4515.107
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 92.0.902.62

• No issues found!
```
</Details>

<Details>
<summary>Minimal Code</summary>

[main.txt](https://github.com/flutter/flutter/files/6924859/main.txt)


</Details>

**Comment by TahaTesser** [comment] 2021-08-04 07:21
Hi @nilesh-athghara 
Thanks for the code sample, it is a duplicate of https://github.com/flutter/flutter/issues/52207
Please follow up on the oriiginal issue

**Closed by TahaTesser** 2021-08-04 07:21 UTC
Labels: in triage
