### ISSUE TITLE
[tool_crash] FileSystemException: Failed to decode data using encoding 'utf-8', null

### ISSUE THREAD

**Issue by sureshkumar231** [flutter/flutter#154804] opened 2024-09-09 00:39 UTC
## Command
```sh
flutter --quiet assemble --no-version-check --depfile G:\AgriNova\agrinova\build\app\intermediates\flutter\debug/flutter_build.d --output G:\AgriNova\agrinova\build\app\intermediates\flutter\debug -dTargetFile=G:\AgriNova\agrinova\lib\main.dart -dTargetPlatform=android -dBuildMode=debug -dTrackWidgetCreation=true --DartDefines=Zmx1dHRlci5pbnNwZWN0b3Iuc3RydWN0dXJlZEVycm9ycz10cnVl -dFlavor= -dAndroidArchs=android-arm64 -dMinSdkVersion=21 debug_android_application
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Failed to decode data using encoding 'utf-8', null
```console
#0      _File._tryDecode (dart:io/file_impl.dart:615:7)
#1      _File.readAsStringSync (dart:io/file_impl.dart:624:7)
#2      ForwardingFile.readAsStringSync (package:file/src/forwarding/forwarding_file.dart:99:16)
#3      ErrorHandlingFile.readAsStringSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:230:22)
#4      _runSync (package:flutter_tools/src/base/error_handling_io.dart:600:14)
#5      ErrorHandlingFile.readAsStringSync (package:flutter_tools/src/base/error_handling_io.dart:229:12)
#6      SourceVisitor.visitDepfile (package:flutter_tools/src/build_system/source.dart:55:37)
#7      _Array.forEach (dart:core-patch/array.dart:41:8)
#8      Target._resolveConfiguration (package:flutter_tools/src/build_system/build_system.dart:259:14)
#9      Target.resolveInputs (package:flutter_tools/src/build_system/build_system.dart:202:12)
#10     Target._toNode (package:flutter_tools/src/build_system/build_system.dart:160:39)
#11     Target._toNode (package:flutter_tools/src/build_system/build_system.dart:167:58)
#12     Target._toNode (package:flutter_tools/src/build_system/build_system.dart:167:58)
#13     FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:624:30)
#14     AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:328:51)
#15     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1772:12)
<asynchronous suspension>
#16     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1408:27)
<asynchronous suspension>
#17     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#18     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#19     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:420:9)
<asynchronous suspension>
```
```console
[✓] Flutter (Channel stable, 3.24.2, on Microsoft Windows [Version 10.0.19045.4780], locale en-US)
    • Flutter version 3.24.2 on channel stable at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cf269e36d (5 days ago), 2024-09-03 14:30:00 -0700
    • Engine revision a6bd3f1de1
    • Dart version 3.5.2
    • DevTools version 2.37.2

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[!] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at C:\Users\sures\AppData\Local\Android\sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/to/windows-android-setup for more details.

[✗] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✗] Visual Studio - develop Windows apps
    ✗ Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[✓] Android Studio (version 2024.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0--11852314)

[✓] VS Code (version 1.93.0)
    • VS Code at C:\Users\sures\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.96.0

[✓] Connected device (3 available)
    • moto g34 5G (mobile) • ZA222KJTJ6 • android-arm64  • Android 14 (API 34)
    • Windows (desktop)    • windows    • windows-x64    • Microsoft Windows [Version 10.0.19045.4780]
    • Edge (web)           • edge       • web-javascript • Microsoft Edge 127.0.2651.98

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 3 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 4cf269e36de2573851eaef3c763994f8f9be494d

**Comment by huycozy** [comment] 2024-09-09 10:33
Closing this as a duplicate of https://github.com/flutter/flutter/issues/65021

**Closed by huycozy** 2024-09-09 10:33 UTC
Labels: in triage
