### ISSUE TITLE
[google_sign_in] How do I set consent=prompt for the sign in?

### ISSUE THREAD

**Issue by elertan** [flutter/flutter#97748] opened 2022-02-04 00:02 UTC
As of right now whenever a user has given consent for the scopes that were requested the sign in view does not show the consent prompt again.
This obviously is the expected behavior in most cases.
But it seems that the returned authorization code then cannot be exchanged once again to obtain a refresh token.

The issue is that if e.g. the user is able to perform the sign in with google, but afterwards is unable to successfully send the authorization code to my server for whatever reason, I am unable to obtain the refresh token anymore.
The user would need to revoke access and then try again which would be a terrible user experience.

Is there a way to force the consent prompt to come up?

**Comment by maheshmnj** [comment] 2022-02-04 08:04
Hi @elertan, The plugin currently doesn't support showing the consent screen once it is submitted, Unless the scopes are manually revoked. I believe this will be solved by https://github.com/flutter/flutter/issues/68882. Closing this issue as a duplicate of the above-linked issue. If you disagree feel free to write in the comments and we will reopen it. 

Thank you

**Closed by maheshmnj** 2022-02-04 08:04 UTC
Labels: in triage
