### ISSUE TITLE
[Obfuscate] Flutter build APK file be not real obfuscation

### ISSUE THREAD

**Issue by MrNinja** [flutter/flutter#47778] opened 2019-12-25 09:10 UTC
I tried to search from `stackoverflow` and `glitter` a lot but can't found the solution.

## Steps to Reproduce

1. Create a demo application which constant 2 button (The first one throw Exception from Dart code and the second one throw Exception from Kotlin code via Platform channel)

2. Build 3 versions of APK file.
2.1. Obfuscate settings off for both of Dart and Android.
2.2. Obfuscate settings off for Android, on for Dart (android/gradle.properties -> extra-gen-snapshot-options=--obfuscate).
2.3. Obfuscate settings on for both of Android and Dart.

3. Check the log from 3 APK.
3.1. The 2.1 apk print full log in Dart with full package (class, method, also) name.
3.2. The 2.2 apk print full log in Dart with full package (class, also) name. The logcat show obfuscated log from Kotlin.
3.3. The 2.3 apk print full log in Dart with full package (class, also) name. The logcat show obfuscated log from Kotlin.

I cant save obfuscation map file over --save-obfuscation-map option also.

> Therefore, the APK do not had obfuscate feature yet, is that right?

**Target Platform:** Android
**Devices:** Tested on Samsung Galaxy Note8

### The 2.1 apk

<details>
	<summary>logs</summary>

```bash
I/flutter (31019): Observatory listening on http://127.0.0.1:37111/pmC6X0YoUqg=/
I/flutter (31019): 難読化なし
I/flutter (31019): Message from android native
I/flutter (31019): ══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
I/flutter (31019): The following message was thrown while handling a gesture:
I/flutter (31019): 難読化なし
I/flutter (31019):
I/flutter (31019): When the exception was thrown, this was the stack:
I/flutter (31019): #0      _MyHomePageState._crashDart (package:flutter_demo_obfuscate/main.dart:31:5)
I/flutter (31019): #1      _MyHomePageState.build.<anonymous closure> (package:flutter_demo_obfuscate/main.dart:65:32)
I/flutter (31019): #2      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:706:14)
I/flutter (31019): #3      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:789:36)
I/flutter (31019): #4      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
I/flutter (31019): #5      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:486:11)
I/flutter (31019): #6      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:264:5)
I/flutter (31019): #7      BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:199:7)
I/flutter (31019): #8      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:467:9)
I/flutter (31019): #9      PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:76:12)
I/flutter (31019): #10     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:117:9)
I/flutter (31019): #11     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:379:8)
I/flutter (31019): #12     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:115:18)
I/flutter (31019): #13     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:7)
I/flutter (31019): #14     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218:19)
I/flutter (31019): #15     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
I/flutter (31019): #16     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
I/flutter (31019): #17     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
I/flutter (31019): #18     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
I/flutter (31019): #22     _invoke1 (dart:ui/hooks.dart:273:10)
I/flutter (31019): #23     _dispatchPointerDataPacket (dart:ui/hooks.dart:182:5)
I/flutter (31019): (elided 3 frames from package dart:async)
I/flutter (31019):
I/flutter (31019): Handler: "onTap"
I/flutter (31019): Recognizer:
I/flutter (31019):   TapGestureRecognizer#a722f
I/flutter (31019): ════════════════════════════════════════════════════════════════════════════════════════════════════
E/flutter (31019): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method crash on channel com.example.flutter_demo_obfuscate/crash)
E/flutter (31019): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:319:7)
E/flutter (31019): <asynchronous suspension>
E/flutter (31019): #1      _MyHomePageState._crashJava (package:flutter_demo_obfuscate/main.dart:35:20)
E/flutter (31019): #2      _MyHomePageState.build.<anonymous closure> (package:flutter_demo_obfuscate/main.dart:69:32)
E/flutter (31019): #3      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:706:14)
E/flutter (31019): #4      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:789:36)
E/flutter (31019): #5      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
E/flutter (31019): #6      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:486:11)
E/flutter (31019): #7      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:264:5)
E/flutter (31019): #8      BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:199:7)
E/flutter (31019): #9      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:467:9)
E/flutter (31019): #10     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:76:12)
E/flutter (31019): #11     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:117:9)
E/flutter (31019): #12     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:379:8)
E/flutter (31019): #13     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:115:18)
E/flutter (31019): #14     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:7)
E/flutter (31019): #15     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218:19)
E/flutter (31019): #16     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
E/flutter (31019): #17     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
E/flutter (31019): #18     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
E/flutter (31019): #19     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
E/flutter (31019): #20     _rootRunUnary (dart:async/zone.dart:1138:13)
E/flutter (31019): #21     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
E/flutter (31019): #22     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
E/flutter (31019): #23     _invoke1 (dart:ui/hooks.dart:273:10)
E/flutter (31019): #24     _dispatchPointerDataPacket (dart:ui/hooks.dart:182:5)
E/flutter (31019):
```

</details>

### The 2.2 apk

<details>
	<summary>logs</summary>

```bash
I/flutter (31961): 難読化あり_dart
I/flutter (31961): Message from android native
I/flutter (31961):
E/flutter (31961): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method crash on channel com.example.flutter_demo_obfuscate/crash)
E/flutter (31961): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:319)
E/flutter (31961): <asynchronous suspension>
E/flutter (31961): #1      _MyHomePageState._crashJava (package:flutter_demo_obfuscate/main.dart:35)
E/flutter (31961): #2      _MyHomePageState.build.<anonymous closure> (package:flutter_demo_obfuscate/main.dart:69)
E/flutter (31961): #3      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:706)
E/flutter (31961): #4      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:789)
E/flutter (31961): #5      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182)
E/flutter (31961): #6      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:486)
E/flutter (31961): #7      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:282)
E/flutter (31961): #8      BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:199)
E/flutter (31961): #9      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:467)
E/flutter (31961): #10     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:76)
E/flutter (31961): #11     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:117)
E/flutter (31961): #12     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:379)
E/flutter (31961): #13     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:115)
E/flutter (31961): #14     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101)
E/flutter (31961): #15     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218)
E/flutter (31961): #16     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198)
E/flutter (31961): #17     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156)
E/flutter (31961): #18     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102)
E/flutter (31961): #19     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86)
E/flutter (31961): #20     _rootRunUnary (dart:async/zone.dart:1138)
E/flutter (31961): #21     _CustomZone.runUnary (dart:async/zone.dart:1031)
E/flutter (31961): #22     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)
E/flutter (31961): #23     _invoke1 (dart:ui/hooks.dart:273)
E/flutter (31961): #24     _dispatchPointerDataPacket (dart:ui/hooks.dart:182)
E/flutter (31961):
```
</details>

<details>
	<summary>adb logcat</summary>

```
12-25 16:23:37.824 31019 31019 E DartMessenger: Uncaught exception in binary message listener
12-25 16:23:37.824 31019 31019 E DartMessenger: java.lang.Exception: Hi There!
12-25 16:23:37.824 31019 31019 E DartMessenger:     at com.example.flutter_demo_obfuscate.MainActivity.crash(MainActivity.kt:26)
12-25 16:23:37.824 31019 31019 E DartMessenger:     at com.example.flutter_demo_obfuscate.MainActivity.access$crash(MainActivity.kt:9)
12-25 16:23:37.824 31019 31019 E DartMessenger:     at com.example.flutter_demo_obfuscate.MainActivity$configureFlutterEngine$1.onMethodCall(MainActivity.kt:16)
12-25 16:23:37.824 31019 31019 E DartMessenger:     at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:231)
12-25 16:23:37.824 31019 31019 E DartMessenger:     at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:93)
12-25 16:23:37.824 31019 31019 E DartMessenger:     at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:642)
12-25 16:23:37.824 31019 31019 E DartMessenger:     at android.os.MessageQueue.nativePollOnce(Native Method)
12-25 16:23:37.824 31019 31019 E DartMessenger:     at android.os.MessageQueue.next(MessageQueue.java:325)
12-25 16:23:37.824 31019 31019 E DartMessenger:     at android.os.Looper.loop(Looper.java:142)
12-25 16:23:37.824 31019 31019 E DartMessenger:     at android.app.ActivityThread.main(ActivityThread.java:6940)
12-25 16:23:37.824 31019 31019 E DartMessenger:     at java.lang.reflect.Method.invoke(Native Method)
12-25 16:23:37.824 31019 31019 E DartMessenger:     at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
12-25 16:23:37.824 31019 31019 E DartMessenger:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
12-25 16:23:37.831 31019 31037 E flutter : [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method crash on channel com.example.flutter_demo_obfuscate/crash)
12-25 16:23:37.831 31019 31037 E flutter : #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:319:7)
12-25 16:23:37.831 31019 31037 E flutter : <asynchronous suspension>
12-25 16:23:37.831 31019 31037 E flutter : #1      _MyHomePageState._crashJava (package:flutter_demo_obfuscate/main.dart:35:20)
12-25 16:23:37.831 31019 31037 E flutter : #2      _MyHomePageState.build.<anonymous closure> (package:flutter_demo_obfuscate/main.dart:69:32)
12-25 16:23:37.831 31019 31037 E flutter : #3      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:706:14)
12-25 16:23:37.831 31019 31037 E flutter : #4      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:789:36)
12-25 16:23:37.831 31019 31037 E flutter : #5      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
12-25 16:23:37.831 31019 31037 E flutter : #6      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:486:11)
12-25 16:23:37.831 31019 31037 E flutter : #7      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:264:5)
12-25 16:23:37.831 31019 31037 E flutter : #8      BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:199:7)
12-25 16:23:37.831 31019 31037 E flutter : #9      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:467:9)
12-25 16:23:37.831 31019 31037 E flutter : #10     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:76:12)
12-25 16:23:37.831 31019 31037 E flutter : #11     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:117:9)
12-25 16:23:37.831 31019 31037 E flutter : #12     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:379:8)
12-25 16:23:37.831 31019 31037 E flutter : #13     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:115:18)
12-25 16:23:37.831 31019 31037 E flutter : #14     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:7)
12-25 16:23:37.831 31019 31037 E flutter : #15     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218:19)
12-25 16:23:37.831 31019 31037 E flutter : #16     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
12-25 16:23:37.831 31019 31037 E flutter : #17     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
12-25 16:23:37.831 31019 31037 E flutter : #18     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
12-25 16:23:37.831 31019 31037 E flutter : #19     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
12-25 16:23:37.831 31019 31037 E flutter : #20     _rootRunUnary (dart:async/zone.dart:1138:13)
12-25 16:23:37.831 31019 31037 E flutter : #21     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
12-25 16:23:37.831 31019 31037 E flutter : #22     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
12-25 16:23:37.831 31019 31037 E flutter : #23     _invoke1 (dart:ui/hooks.dart:273:10)
12-25 16:23:37.831 31019 31037 E flutter : #24     _dispatchPointerDataPacket (dart:ui/hooks.dart:182:5)
12-25 16:23:37.831 31019 31037 E flutter : 

```

</details>

### The 2.2 apk

<details>
	<summary>logs</summary>

```bash
I/flutter ( 5268): 難読化あり_dart_java
I/flutter ( 5268): Message from android native
I/flutter ( 5268):
E/flutter ( 5268): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method crash on channel com.example.flutter_demo_obfuscate/crash)
E/flutter ( 5268): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:319)
E/flutter ( 5268): <asynchronous suspension>
E/flutter ( 5268): #1      _MyHomePageState._crashJava (package:flutter_demo_obfuscate/main.dart:35)
E/flutter ( 5268): #2      _MyHomePageState.build.<anonymous closure> (package:flutter_demo_obfuscate/main.dart:69)
E/flutter ( 5268): #3      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:706)
E/flutter ( 5268): #4      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:789)
E/flutter ( 5268): #5      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182)
E/flutter ( 5268): #6      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:486)
E/flutter ( 5268): #7      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:282)
E/flutter ( 5268): #8      BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:199)
E/flutter ( 5268): #9      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:467)
E/flutter ( 5268): #10     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:76)
E/flutter ( 5268): #11     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:117)
E/flutter ( 5268): #12     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:379)
E/flutter ( 5268): #13     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:115)
E/flutter ( 5268): #14     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101)
E/flutter ( 5268): #15     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218)
E/flutter ( 5268): #16     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198)
E/flutter ( 5268): #17     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156)
E/flutter ( 5268): #18     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102)
E/flutter ( 5268): #19     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86)
E/flutter ( 5268): #20     _rootRunUnary (dart:async/zone.dart:1138)
E/flutter ( 5268): #21     _CustomZone.runUnary (dart:async/zone.dart:1031)
E/flutter ( 5268): #22     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)
E/flutter ( 5268): #23     _invoke1 (dart:ui/hooks.dart:273)
E/flutter ( 5268): #24     _dispatchPointerDataPacket (dart:ui/hooks.dart:182)
E/flutter ( 5268):

```

</details>

<details>
	<summary>adb logcat</summary>

```bash
12-25 16:43:33.328  1717  1717 E DartMessenger: Uncaught exception in binary message listener
12-25 16:43:33.328  1717  1717 E DartMessenger: java.lang.Exception: Hi There!
12-25 16:43:33.328  1717  1717 E DartMessenger:     at com.example.flutter_demo_obfuscate.MainActivity.q(Unknown Source:4)
12-25 16:43:33.328  1717  1717 E DartMessenger:     at com.example.flutter_demo_obfuscate.MainActivity.a(Unknown Source:0)
12-25 16:43:33.328  1717  1717 E DartMessenger:     at com.example.flutter_demo_obfuscate.MainActivity$a.a(Unknown Source:46)
12-25 16:43:33.328  1717  1717 E DartMessenger:     at b.a.c.a.i$a.a(Unknown Source:17)
12-25 16:43:33.328  1717  1717 E DartMessenger:     at io.flutter.embedding.engine.e.b.a(Unknown Source:57)
12-25 16:43:33.328  1717  1717 E DartMessenger:     at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(Unknown Source:4)
12-25 16:43:33.328  1717  1717 E DartMessenger:     at android.os.MessageQueue.nativePollOnce(Native Method)
12-25 16:43:33.328  1717  1717 E DartMessenger:     at android.os.MessageQueue.next(MessageQueue.java:325)
12-25 16:43:33.328  1717  1717 E DartMessenger:     at android.os.Looper.loop(Looper.java:142)
12-25 16:43:33.328  1717  1717 E DartMessenger:     at android.app.ActivityThread.main(ActivityThread.java:6940)
12-25 16:43:33.328  1717  1717 E DartMessenger:     at java.lang.reflect.Method.invoke(Native Method)
12-25 16:43:33.328  1717  1717 E DartMessenger:     at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
12-25 16:43:33.328  1717  1717 E DartMessenger:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
12-25 16:43:33.329  1717  1736 E flutter : [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method crash on channel com.example.flutter_demo_obfuscate/crash)
12-25 16:43:33.329  1717  1736 E flutter : #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:319)
12-25 16:43:33.329  1717  1736 E flutter : <asynchronous suspension>
12-25 16:43:33.329  1717  1736 E flutter : #1      _MyHomePageState._crashJava (package:flutter_demo_obfuscate/main.dart:35)
12-25 16:43:33.329  1717  1736 E flutter : #2      _MyHomePageState.build.<anonymous closure> (package:flutter_demo_obfuscate/main.dart:69)
12-25 16:43:33.329  1717  1736 E flutter : #3      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:706)
12-25 16:43:33.329  1717  1736 E flutter : #4      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:789)
12-25 16:43:33.329  1717  1736 E flutter : #5      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182)
12-25 16:43:33.329  1717  1736 E flutter : #6      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:486)
12-25 16:43:33.329  1717  1736 E flutter : #7      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:282)
12-25 16:43:33.329  1717  1736 E flutter : #8      BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:199)
12-25 16:43:33.329  1717  1736 E flutter : #9      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:467)
12-25 16:43:33.329  1717  1736 E flutter : #10     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:76)
12-25 16:43:33.329  1717  1736 E flutter : #11     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:117)
12-25 16:43:33.329  1717  1736 E flutter : #12     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:379)
12-25 16:43:33.329  1717  1736 E flutter : #13     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:115)
12-25 16:43:33.329  1717  1736 E flutter : #14     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101)
12-25 16:43:33.329  1717  1736 E flutter : #15     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218)
12-25 16:43:33.329  1717  1736 E flutter : #16     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198)
12-25 16:43:33.329  1717  1736 E flutter : #17     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156)
12-25 16:43:33.329  1717  1736 E flutter : #18     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102)
12-25 16:43:33.329  1717  1736 E flutter : #19     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86)
12-25 16:43:33.329  1717  1736 E flutter : #20     _rootRunUnary (dart:async/zone.dart:1138)
12-25 16:43:33.329  1717  1736 E flutter : #21     _CustomZone.runUnary (dart:async/zone.dart:1031)
12-25 16:43:33.329  1717  1736 E flutter : #22     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)
12-25 16:43:33.329  1717  1736 E flutter : #23     _invoke1 (dart:ui/hooks.dart:273)
12-25 16:43:33.329  1717  1736 E flutter : #24     _dispatchPointerDataPacket (dart:ui/hooks.dart:182)
12-25 16:43:33.329  1717  1736 E flutter : 
```

</details>

### `flutter doctor -v`

```console
>_$ flutter doctor -v                                                                                                                                            system.rb system.py
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.14.6 18G1012, locale ja-JP)
    • Flutter version 1.12.13+hotfix.5 at /Users/rikimaru/Downloads/flutter
    • Framework revision 27321ebbad (2 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/systena/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2, Build version 11B52
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[✓] Proxy Configuration
    • HTTP_PROXY is set
    • NO_PROXY is localhost, 127.0.0.1
    • NO_PROXY contains 127.0.0.1
    • NO_PROXY contains localhost

[✓] Connected device (1 available)
    • S 1B • c011a74207 • android-arm64 • Android 8.0.0 (API 26)

• No issues found!
```

**Comment by sebkoller** [comment] 2020-02-02 10:22
I ran into the same problem.
Obfuscation stopped working for me with Flutter 1.11.0 (Dart 2.7.0).
Building the same project with 1.10.9 (Dart 2.6.0) or 1.9.7 (Dart 2.5.0) works fine (including the obfuscation map)

If anyone's interested, I could produce a minimal, reproducible example.

**Comment by jonahwilliams** [comment] 2020-02-02 20:26
Duplicate of https://github.com/flutter/flutter/issues/47049

**Closed by jonahwilliams** 2020-02-02 20:26 UTC
Labels: dependency: android, dependency: dart, severe: crash, tool, ▣ platform-android
