### ISSUE TITLE
'flutter run' doesn't rebuild the app if it's changed

### ISSUE THREAD

**Issue by Goldtek** [flutter/flutter#18974] opened 2018-07-01 02:39 UTC
changes does not apply unless i delete build folder before it rebuilds 'android platform', so it does work as expected especially while using vscode editor

**Comment by ebeem** [comment] 2018-07-01 15:16
releasing does not seem to overwrite old build
the easier way I am aware of is to clean and then run/build
`flutter clean && flutter run --release ` instead of just `flutter run --release`

**Comment by Goldtek** [comment] 2018-07-01 15:18
Ok thanks

**Comment by stevenbrix** [comment] 2018-09-05 15:50
is there an actual plan to fix deploying via VS Code? if I deploy the app via "flutter run" from the flutter console it works fine. I'm not exactly sure what the issue is. I've also had issues with hot reload in VS Code, not sure if they are related.

**Comment by zoechi** [comment] 2018-09-05 19:35
Closing as dup of #16604

**Closed by zoechi** 2018-09-05 19:35 UTC
Labels: tool

**Comment by zoechi** [comment] 2018-09-05 19:38
@DanTup I assume you can answer @stevenbrix question.

**Comment by DanTup** [comment] 2018-09-05 20:30
@stevenbrix Can you reliably reproduce this? VS Code essentially just calls `flutter run` (with the `--machine` flag so that it gets JSON statuses). If you can reproduce, try capturing a log (run the `Dart: Capture Logs` command, select the `Flutter Run` category, and then repro) and then the same from the terminal (run with `-v` and pipe copy the output).
