### ISSUE TITLE
Exception 'ScrollController attached to multiple scroll views' on DraggableScrollableActuator.reset when  DraggableScrollableSheet's ScrollController is used in TabBarView child 

### ISSUE THREAD

**Issue by handofthecode** [flutter/flutter#55388] opened 2020-04-22 17:03 UTC
It seems I can either attach DraggableScrollableSheet's ScrollController to a nested list OR use DraggableScrollableActuator.reset(context) to reset the extent. I don't see why I can't do both. Is this a bug? Is there a work around or another way to achieve the same result?

```
class InterfaceSelector extends StatefulWidget {
  @override
  InterfaceSelectorState createState() => InterfaceSelectorState();
}

class InterfaceSelectorState extends State<InterfaceSelector> {
  double initialChildSize = 0.5;
  double minChildSize = 0.5;
  double maxChildSize = 0.7;

  @override
  Widget build(BuildContext context) {
    return DraggableScrollableActuator(
      child: DraggableScrollableSheet(
        initialChildSize: initialChildSize,
        minChildSize: minChildSize,
        maxChildSize: maxChildSize,
        builder: (BuildContext ctx, ScrollController scrollController) {
          return SingleChildScrollView(
            controller: scrollController,
            child: Container(
              height: MediaQuery.of(context).size.longestSide * .7,
              color: Theme.of(ctx).primaryColor,
              child: DefaultTabController(
                length: 4,
                child: Column(
                  children: <Widget>[
                    Material(
                      color: Theme.of(ctx).accentColor,
                      child: TabBar(
                        tabs: [
                          Tab(text: "One"),
                          Tab(text: "Two"),
                          Tab(text: "Three"),
                          Tab(text: "Four"),
                        ],
                      ),
                    ),
                    Expanded(
                      child: TabBarView(
                        children: [
                          One(),
                          Two(),
                          Three(scrollController),
                          Four(),
                        ],
                      ),
                    ),
                  ],
                ),
              ),
            ),
          );
        },
      ),
    );
  }
}

class Three extends StatefulWidget {
  ScrollController scrollController;
  Three(this.scrollController);
  @override
  _ThreeState createState() => _ThreeState();
}

class _ThreeState extends State<Three> with AutomaticKeepAliveClientMixin {
  @override
  bool get wantKeepAlive => true;

  @override
  Widget build(BuildContext context) {
    Stuff stuff = Provider.of<Stuff>(context);
    return Column(
      children: <Widget>[
        MaterialButton(onPressed: () {
          DraggableScrollableActuator.reset(context);
        }),
        Expanded(
          child: GridView.builder(
            controller: widget.scrollController,
            padding: const EdgeInsets.all(10),
            itemCount: stuff.all.length,
            itemBuilder: (ctx, i) => ChangeNotifierProvider.value(
              value: stuff.all[i],
              key: UniqueKey(),
              child: StuffCard(i, stuff.all[i], stuff),
            ),
            gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(
              crossAxisCount: 3,
              crossAxisSpacing: 10,
              mainAxisSpacing: 10,
            ),
          ),
        ),
      ],
    );
  }
}

```

I am getting this error:

```
The following assertion was thrown building _InheritedResetNotifier(dirty):
ScrollController attached to multiple scroll views.
'package:flutter/src/widgets/scroll_controller.dart':
Failed assertion: line 111 pos 12: '_positions.length == 1'
```

**Comment by VladyslavBondarenko** [comment] 2020-04-23 10:38
<details>
 <summary>complete code sample</summary>

```
import 'package:flutter/material.dart';

void main() => runApp(MaterialApp(home: InterfaceSelector()));

class InterfaceSelector extends StatefulWidget {
  @override
  InterfaceSelectorState createState() => InterfaceSelectorState();
}

class InterfaceSelectorState extends State<InterfaceSelector> {
  double initialChildSize = 0.5;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: DraggableScrollableActuator(
        child: DraggableScrollableSheet(
          initialChildSize: initialChildSize,
          builder: (BuildContext ctx, ScrollController scrollController) {
            return SingleChildScrollView(
              controller: scrollController,
              child: Container(
                height: MediaQuery.of(context).size.longestSide * .7,
                color: Theme.of(ctx).primaryColor,
                child: DefaultTabController(
                  length: 1,
                  child: Column(
                    children: <Widget>[
                      Material(
                        color: Theme.of(ctx).accentColor,
                        child: TabBar(
                          tabs: [
                            Tab(text: "One"),
                          ],
                        ),
                      ),
                      Expanded(
                        child: TabBarView(
                          children: [
                            Three(scrollController),
                          ],
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            );
          },
        ),
      ),
    );
  }
}

class Three extends StatefulWidget {
  final ScrollController scrollController;
  Three(this.scrollController);
  @override
  _ThreeState createState() => _ThreeState();
}

class _ThreeState extends State<Three> with AutomaticKeepAliveClientMixin {
  @override
  bool get wantKeepAlive => true;

  @override
  Widget build(BuildContext context) {
    return Column(
      children: <Widget>[
        MaterialButton(
          child: Text('DraggableScrollableActuator.reset'),
          onPressed: () {
            DraggableScrollableActuator.reset(context);
          },
        ),
        Expanded(
          child: GridView.builder(

            controller: widget.scrollController, // no exception without it

            padding: const EdgeInsets.all(10),
            itemCount: 10,
            itemBuilder: (ctx, i) => Text('StuffCard'),
            gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(
              crossAxisCount: 3,
              crossAxisSpacing: 10,
              mainAxisSpacing: 10,
            ),
          ),
        ),
      ],
    );
  }
}
```

</details>

It may be not the issue is related to not what is said in the title, because

<details>
 <summary>this doesn't throw exception</summary>

```
import 'package:flutter/material.dart';

void main() => runApp(MaterialApp(home: InterfaceSelector()));

class InterfaceSelector extends StatefulWidget {
  @override
  InterfaceSelectorState createState() => InterfaceSelectorState();
}

class InterfaceSelectorState extends State<InterfaceSelector> {
  double initialChildSize = 0.5;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: DraggableScrollableActuator(
        child: DraggableScrollableSheet(
          initialChildSize: initialChildSize,
          builder: (BuildContext ctx, ScrollController scrollController) {
            return SingleChildScrollView(
              controller: scrollController,
              child: Container(
                height: MediaQuery.of(context).size.longestSide * .7,
                color: Theme.of(ctx).primaryColor,
                child: Column(
                  children: <Widget>[
                    MaterialButton(
                      child: Text('DraggableScrollableActuator.reset'),
                      onPressed: () {
                        DraggableScrollableActuator.reset(context);
                      },
                    ),
                    Expanded(
                      child: GridView.builder(
                        controller: scrollController,
                        padding: const EdgeInsets.all(10),
                        itemCount: 10,
                        itemBuilder: (ctx, i) => Text('StuffCard'),
                        gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(
                          crossAxisCount: 3,
                          crossAxisSpacing: 10,
                          mainAxisSpacing: 10,
                        ),
                      ),
                    ),
                  ],
                ),
              ),
            );
          },
        ),
      ),
    );
  }
}
```

</details>

</details>

<details>
 <summary>flutter doctor -v </summary>

```
[✓] Flutter (Channel dev, v1.18.0-6.0.pre, on Mac OS X 10.15.4 19E287, locale en-GB)
    • Flutter version 1.18.0-6.0.pre at /Users/nevercode/dev/flutter_dev
    • Framework revision 84c84fb249 (2 days ago), 2020-04-20 21:35:01 -0400
    • Engine revision 2bde4f0ae4
    • Dart version 2.9.0 (build 2.9.0-1.0.dev a12c36dd97)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/nevercode/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.44.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1

[✓] Connected device (5 available)
    • Android SDK built for x86 • emulator-5554                            • android-x86    • Android 10 (API 29) (emulator)
    • Nevercode’s iPhone        • b668e524315069f3db3661ac11ff1f66afafebdb • ios            • iOS 13.4.5
    • macOS                     • macOS                                    • darwin-x64     • Mac OS X 10.15.4 19E287
    • Chrome                    • chrome                                   • web-javascript • Google Chrome 81.0.4044.122
    • Web Server                • web-server                               • web-javascript • Flutter Tools

• No issues found!
```

</details>

**Comment by VladyslavBondarenko** [comment] 2020-07-27 12:56
@handofthecode 
it works as intended if you use separate controllers for SingleChildScrollView and GridView.builder.
Closing since this is not an issue with flutter

**Closed by VladyslavBondarenko** 2020-07-27 12:56 UTC
Labels: d: stackoverflow, framework, has reproducible steps
