### ISSUE TITLE
Gradle build fails with error "File name too long"

### ISSUE THREAD

**Issue by szekelyisz** [flutter/flutter#140153] opened 2023-12-14 14:49 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Create a new flutter project
2. Try to run it on Android

### Actual results

Build fails.

### Logs

<details>
<summary>`flutter run -v`</summary>

```console
[  +11 ms] executing: uname -m
[   +9 ms] Exit code 0 from: uname -m
[        ] x86_64
[  +49 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'LegacyCanvasKitRemover' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +42 ms] executing: /home/szabi/Android/Sdk/platform-tools/adb devices -l
[  +40 ms] List of devices attached
           acd40725               device usb:1-3 product:OnePlus6T model:ONEPLUS_A6013 device:OnePlus6T transport_id:1
[   +4 ms] /home/szabi/Android/Sdk/platform-tools/adb -s acd40725 shell getprop
[  +90 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'LegacyCanvasKitRemover' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +137 ms] Skipping pub get: version match.
[ +123 ms] Generating /tmp/test/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +46 ms] ro.hardware = qcom
[  +40 ms] Initializing file store
[   +8 ms] Skipping target: gen_localizations
[   +4 ms] gen_dart_plugin_registrant: Starting due to {InvalidatedReasonKind.inputChanged: The following inputs have updated contents: /tmp/test/.dart_tool/package_config_subset}
[  +37 ms] gen_dart_plugin_registrant: Complete
[        ] Skipping target: _composite
[   +1 ms] complete
[   +4 ms] Launching lib/main.dart on ONEPLUS A6013 in debug mode...
[   +2 ms] /home/szabi/snap/flutter/common/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev /home/szabi/snap/flutter/common/flutter/bin/cache/dart-sdk/bin/snapshots/frontend_server.dart.snapshot --sdk-root
/home/szabi/snap/flutter/common/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --incremental --target=flutter --experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true
-DFLUTTER_WEB_CANVASKIT_URL=https://www.gstatic.com/flutter-canvaskit/54a7145303f0dd9d0f93424a2e124eb4abef5091/ --output-dill /tmp/flutter_tools.HWGUDF/flutter_tool.EGFDEX/app.dill --packages /tmp/test/.dart_tool/package_config.json
-Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill build/59906ac2072ea23d943f4334a0ae780f.cache.dill.track.dill --verbosity=error
--enable-experiment=alternative-invalidation-strategy
[  +10 ms] executing: /home/szabi/Android/Sdk/platform-tools/adb -s acd40725 shell -x logcat -v time -t 1
[   +7 ms] <- compile package:test/main.dart
[  +92 ms] --------- beginning of main
           12-14 15:45:50.161 D/ServerConnectionInfo(21572): localUrl is: false, usesInternalSsid is: false, usesWifi is: false
[   +8 ms] executing: /home/szabi/Android/Sdk/platform-tools/adb version
[   +6 ms] Android Debug Bridge version 1.0.41
           Version 34.0.5-10900879
           Installed as /home/szabi/Android/Sdk/platform-tools/adb
           Running on Linux 6.1.0-15-amd64 (x86_64)
[   +1 ms] executing: /home/szabi/Android/Sdk/platform-tools/adb start-server
[   +5 ms] Building APK
[   +8 ms] executing: /snap/android-studio/136/jbr/bin/java -version
[  +75 ms] Exit code 0 from: /snap/android-studio/136/jbr/bin/java -version
[        ] openjdk version "17.0.7" 2023-04-18
           OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
           OpenJDK 64-Bit Server VM (build 17.0.7+0-17.0.7b1000.6-10550314, mixed mode)
[        ] executing: /snap/android-studio/128/android-studio/jbr/bin/java -version
[  +67 ms] Exit code 0 from: /snap/android-studio/128/android-studio/jbr/bin/java -version
[        ] openjdk version "17.0.6" 2023-01-17
           OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
           OpenJDK 64-Bit Server VM (build 17.0.6+0-17.0.6b829.9-10027231, mixed mode)
[   +9 ms] executing: /snap/android-studio/136/jbr/bin/java --version
[  +70 ms] Exit code 0 from: /snap/android-studio/136/jbr/bin/java --version
[        ] openjdk 17.0.7 2023-04-18
           OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
           OpenJDK 64-Bit Server VM (build 17.0.7+0-17.0.7b1000.6-10550314, mixed mode)
[  +16 ms] Using gradle from /tmp/test/android/gradlew.
[   +5 ms] Running Gradle task 'assembleDebug'...
[   +6 ms] executing: [/tmp/test/android/] /tmp/test/android/gradlew --full-stacktrace --info -Pverbose=true -Ptarget-platform=android-arm64 -Ptarget=/tmp/test/lib/main.dart -Pbase-application-name=android.app.Application
-Pdart-defines=RkxVVFRFUl9XRUJfQVVUT19ERVRFQ1Q9dHJ1ZQ==,RkxVVFRFUl9XRUJfQ0FOVkFTS0lUX1VSTD1odHRwczovL3d3dy5nc3RhdGljLmNvbS9mbHV0dGVyLWNhbnZhc2tpdC81NGE3MTQ1MzAzZjBkZDlkMGY5MzQyNGEyZTEyNGViNGFiZWY1MDkxLw== -Pdart-obfuscation=false
-Ptrack-widget-creation=true -Ptree-shake-icons=false -Pfilesystem-scheme=org-dartlang-root assembleDebug
[ +396 ms] Initialized native services in: /home/szabi/.gradle/native
[        ] Initialized jansi services in: /home/szabi/.gradle/native
[ +205 ms] The client will now receive all logging from the daemon (pid: 17674). The daemon log file: /home/szabi/.gradle/daemon/7.5/daemon-17674.out.log
[        ] Starting 3rd build in daemon [uptime: 3 mins 20.281 secs, performance: 100%]
[        ] Using 12 worker leases.
[        ] Now considering [/tmp/test/android] as hierarchies to watch
[        ] Watching the file system is configured to be enabled if available
[        ] File system watching is active
[        ] Starting Build
[        ] Not watching /home/szabi/snap/flutter/common/flutter/packages/flutter_tools/gradle since the file system is not supported
[ +100 ms] > Configure project :gradle
[        ] Evaluating project ':gradle' using build file '/home/szabi/snap/flutter/common/flutter/packages/flutter_tools/gradle/build.gradle.kts'.
[        ] Caching disabled for Kotlin DSL accessors for project ':gradle' because:
[        ]   Build cache is disabled
[        ] Skipping Kotlin DSL accessors for project ':gradle' as it is up-to-date.
[        ] Resolve mutations for :gradle:compileJava (Thread[Execution worker,5,main]) started.
[        ] Resolve mutations for :gradle:compileJava (Thread[Execution worker,5,main]) completed. Took 0.0 secs.
[        ] :gradle:compileJava (Thread[included builds,5,main]) started.
[        ] > Task :gradle:compileJava NO-SOURCE
[        ] Skipping task ':gradle:compileJava' as it has no source files and no previous output files.
[        ] :gradle:compileJava (Thread[included builds,5,main]) completed. Took 0.002 secs.
[        ] Resolve mutations for :gradle:compileGroovy (Thread[Execution worker,5,main]) started.
[        ] Resolve mutations for :gradle:compileGroovy (Thread[Execution worker,5,main]) completed. Took 0.0 secs.
[        ] :gradle:compileGroovy (Thread[included builds,5,main]) started.
[ +594 ms] This JVM does not support getting OS memory, so no OS memory status updates will be broadcast
[+1400 ms] > Task :gradle:compileGroovy
[        ] Caching disabled for task ':gradle:compileGroovy' because:
[        ]   Build cache is disabled
[        ] Task ':gradle:compileGroovy' is not up-to-date because:
[        ]   Task has failed previously.
[        ] The input changes require a full rebuild for incremental task ':gradle:compileGroovy'.
[        ] Starting process 'Gradle Worker Daemon 3'. Working directory: /home/szabi/.gradle/workers Command: /snap/android-studio/136/jbr/bin/java --add-opens java.base/java.lang=ALL-UNNAMED --add-opens
java.base/java.lang.invoke=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.prefs/java.util.prefs=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED
@/home/szabi/.gradle/.tmp/gradle-worker-classpath8801432138939427564txt -Xmx512m -Dfile.encoding=US-ASCII -Duser.country=US -Duser.language=en -Duser.variant worker.org.gradle.process.internal.worker.GradleWorkerMain 'Gradle Worker Daemon
3'
[   +1 ms] Successfully started process 'Gradle Worker Daemon 3'
[        ] Started Gradle worker daemon (0.376 secs) with fork options DaemonForkOptions{executable=/snap/android-studio/136/jbr/bin/java, minHeapSize=null, maxHeapSize=null, jvmArgs=[--add-opens, java.base/java.lang=ALL-UNNAMED,
--add-opens, java.base/java.lang.invoke=ALL-UNNAMED, --add-opens, java.base/java.util=ALL-UNNAMED, --add-opens, java.prefs/java.util.prefs=ALL-UNNAMED], keepAliveMode=SESSION}.
[+1897 ms] startup failed:
[   +2 ms]
/home/szabi/snap/flutter/common/flutter/packages/flutter_tools/gradle/build/classes/groovy/main/FlutterPlugin$_addTasksForOutputsAppLinkSettings_closure22$_closure48$_closure50$_closure51$_closure52$_closure53$_closure55$_closure57$_closur
e58.class (File name too long)
[        ] 1 error
[        ] FAILURE: Build failed with an exception.
[        ] * What went wrong:
[        ] Execution failed for task ':gradle:compileGroovy'.
[        ] > Compilation failed; see the compiler error output for details.
[        ] * Try:
[        ] > Run with --debug option to get more log output.
[        ] > Run with --scan to get full insights.
[        ] * Exception is:
[        ] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':gradle:compileGroovy'.
[        ]      at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:142)
[        ]      at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:282)
[        ]      at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:140)
[        ]      at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:128)
[        ]      at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:77)
[        ]      at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
[        ]      at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:51)
[        ]      at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
[        ]      at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
[        ]      at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
[        ]      at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
[        ]      at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
[        ]      at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
[        ]      at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
[        ]      at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199)
[        ]      at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
[        ]      at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
[        ]      at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
[        ]      at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
[        ]      at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
[        ]      at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:73)
[        ]      at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
[        ]      at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:69)
[        ]      at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:327)
[        ]      at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:314)
[        ]      at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:307)
[        ]      at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:293)
[        ]      at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:417)
[        ]      at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:339)
[        ]      at org.gradle.execution.plan.DefaultPlanExecutor.process(DefaultPlanExecutor.java:96)
[        ]      at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph.executeWithServices(DefaultTaskExecutionGraph.java:140)
[        ]      at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph.execute(DefaultTaskExecutionGraph.java:125)
[        ]      at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:39)
[        ]      at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:51)
[        ]      at org.gradle.execution.BuildOperationFiringBuildWorkerExecutor$ExecuteTasks.call(BuildOperationFiringBuildWorkerExecutor.java:54)
[        ]      at org.gradle.execution.BuildOperationFiringBuildWorkerExecutor$ExecuteTasks.call(BuildOperationFiringBuildWorkerExecutor.java:43)
[        ]      at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
[        ]      at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199)
[        ]      at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
[        ]      at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
[        ]      at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
[        ]      at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
[        ]      at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
[        ]      at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:73)
[        ]      at org.gradle.execution.BuildOperationFiringBuildWorkerExecutor.execute(BuildOperationFiringBuildWorkerExecutor.java:40)
[        ]      at org.gradle.internal.build.DefaultBuildLifecycleController.lambda$executeTasks$7(DefaultBuildLifecycleController.java:161)
[        ]      at org.gradle.internal.model.StateTransitionController.doTransition(StateTransitionController.java:247)
[        ]      at org.gradle.internal.model.StateTransitionController.lambda$tryTransition$7(StateTransitionController.java:174)
[        ]      at org.gradle.internal.work.DefaultSynchronizer.withLock(DefaultSynchronizer.java:44)
[        ]      at org.gradle.internal.model.StateTransitionController.tryTransition(StateTransitionController.java:174)
[        ]      at org.gradle.internal.build.DefaultBuildLifecycleController.executeTasks(DefaultBuildLifecycleController.java:161)
[        ]      at org.gradle.internal.build.DefaultBuildWorkGraphController$DefaultBuildWorkGraph.runWork(DefaultBuildWorkGraphController.java:156)
[        ]      at org.gradle.internal.work.DefaultWorkerLeaseService.withLocks(DefaultWorkerLeaseService.java:249)
[        ]      at org.gradle.internal.work.DefaultWorkerLeaseService.runAsWorkerThread(DefaultWorkerLeaseService.java:109)
[        ]      at org.gradle.composite.internal.DefaultBuildController.doRun(DefaultBuildController.java:164)
[        ]      at org.gradle.composite.internal.DefaultBuildController.access$000(DefaultBuildController.java:45)
[        ]      at org.gradle.composite.internal.DefaultBuildController$BuildOpRunnable.run(DefaultBuildController.java:183)
[        ]      at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[        ]      at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[        ]      at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
[        ]      at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
[        ]      at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[        ]      at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[        ]      at java.base/java.lang.Thread.run(Thread.java:833)
[        ] Caused by: org.gradle.api.internal.tasks.compile.CompilationFailedException: Compilation failed; see the compiler error output for details.
[        ]      at org.gradle.api.internal.tasks.compile.ApiGroovyCompiler.execute(ApiGroovyCompiler.java:276)
[        ]      at org.gradle.api.internal.tasks.compile.ApiGroovyCompiler.execute(ApiGroovyCompiler.java:64)
[        ]      at org.gradle.api.internal.tasks.compile.GroovyCompilerFactory$DaemonSideCompiler.execute(GroovyCompilerFactory.java:97)
[        ]      at org.gradle.api.internal.tasks.compile.GroovyCompilerFactory$DaemonSideCompiler.execute(GroovyCompilerFactory.java:76)
[   +3 ms]      at org.gradle.api.internal.tasks.compile.daemon.AbstractDaemonCompiler$CompilerWorkAction.execute(AbstractDaemonCompiler.java:135)
[        ]      at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:63)
[        ]      at org.gradle.workers.internal.AbstractClassLoaderWorker$1.create(AbstractClassLoaderWorker.java:49)
[        ]      at org.gradle.workers.internal.AbstractClassLoaderWorker$1.create(AbstractClassLoaderWorker.java:43)
[        ]      at org.gradle.internal.classloader.ClassLoaderUtils.executeInClassloader(ClassLoaderUtils.java:100)
[        ]      at org.gradle.workers.internal.AbstractClassLoaderWorker.executeInClassLoader(AbstractClassLoaderWorker.java:43)
[        ]      at org.gradle.workers.internal.IsolatedClassloaderWorker.run(IsolatedClassloaderWorker.java:49)
[        ]      at org.gradle.workers.internal.IsolatedClassloaderWorker.run(IsolatedClassloaderWorker.java:30)
[        ]      at org.gradle.workers.internal.WorkerDaemonServer.run(WorkerDaemonServer.java:87)
[        ]      at org.gradle.workers.internal.WorkerDaemonServer.run(WorkerDaemonServer.java:56)
[        ]      at org.gradle.process.internal.worker.request.WorkerAction$1.call(WorkerAction.java:138)
[        ]      at org.gradle.process.internal.worker.child.WorkerLogEventListener.withWorkerLoggingProtocol(WorkerLogEventListener.java:41)
[        ]      at org.gradle.process.internal.worker.request.WorkerAction.run(WorkerAction.java:135)
[        ]      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[        ]      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[        ]      at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[        ]      at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[        ]      at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
[        ]      at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
[        ]      at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
[        ]      at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
[        ]      at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:414)
[        ]      at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
[        ]      at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
[        ]      at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[        ]      at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[        ]      at java.base/java.lang.Thread.run(Thread.java:833)
[        ] * Get more help at https://help.gradle.org
[        ] BUILD FAILED in 4s
[        ] > Task :gradle:compileGroovy FAILED
[        ] :gradle:compileGroovy (Thread[included builds,5,main]) completed. Took 3.905 secs.
[        ] 1 actionable task: 1 executed
[        ] Some of the file system contents retained in the virtual file system are on file systems that Gradle doesn't support watching. The relevant state was discarded to ensure changes to these locations are properly detected. You can
override this by explicitly enabling file system watching.
[        ] Stopped 1 worker daemon(s).
[ +325 ms] Running Gradle task 'assembleDebug'... (completed in 5.0s)
[+3457 ms] Exception: Gradle task assembleDebug failed with exit code 1
[   +3 ms] "flutter run" took 9,429ms.
[   +3 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:752:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1350:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:348:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:294:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:112:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:90:3)
           <asynchronous suspension>
           
           
[  +20 ms] ensureAnalyticsSent: 15ms
[        ] Running 1 shutdown hook
[   +5 ms] Shutdown hooks complete
[        ] exiting with code 1
```
</details>

### Flutter Doctor output

<details>
<summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.16.4, on Debian GNU/Linux 12 (bookworm) 6.1.0-15-amd64, locale en_CA.UTF-8)
    • Flutter version 3.16.4 on channel stable at /home/szabi/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2e9cb0aa71 (3 days ago), 2023-12-11 14:35:13 -0700
    • Engine revision 54a7145303
    • Dart version 3.2.3
    • DevTools version 2.28.4

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /home/szabi/Android/Sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /snap/android-studio/136/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 2023.1)
    • Android Studio at /snap/android-studio/136
    • Flutter plugin version 77.1.2
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] Android Studio (version 2022.3)
    • Android Studio at /snap/android-studio/128/android-studio
    • Flutter plugin version 76.3.2
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version unknown)
    • VS Code at /snap/code/current
    • Flutter extension version 3.78.0
    ✗ Unable to determine VS Code version.

[✓] Connected device (2 available)
    • ONEPLUS A6013 (mobile) • acd40725 • android-arm64 • Android 9 (API 28)
    • Linux (desktop)        • linux    • linux-x64     • Debian GNU/Linux 12 (bookworm) 6.1.0-15-amd64

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

**Comment by huycozy** [comment] 2023-12-15 06:23
Hi @szekelyisz 
Looks like your system has file-based encryption. If so, this is a known issue at https://github.com/flutter/flutter/issues/138748. 

I will close this issue as a duplicate of that one. So please follow up on it for updates. If your case is not the same, please write in the comments and I will reopen it.

**Closed by huycozy** 2023-12-15 06:23 UTC
Labels: in triage
