### ISSUE TITLE
[Flutter Web] Korean characters are displayed with a placeholder when entered for first time on CanvasKit

### ISSUE THREAD

**Issue by dohuon** [flutter/flutter#104597] opened 2022-05-25 09:19 UTC
![hangul](https://user-images.githubusercontent.com/10705819/170218682-72ca8238-c98c-45a9-9ce6-59ec9215e719.gif)

## Steps to Reproduce

1. Execute `flutter run -d chrome --web-renderer canvaskit` on the code sample 
2. Type any Korean sentance. You will see lots of box before correct font is shown.
3. If you type same sentance again, there is no box.
4. Type same sentance after refreshing browser or type totally new sentance to reproduce the problem.

It seems Flutter is lazy-loading Korean font and try to show character before font loading/rendering is complete.  Html web renderer does not have this problem.
This is huge blocker for us to release a product with Flutter.

* Ryzen 9 5900HS, 11.0/15.4GB, Chrome101.0.4951.67 (64 bit)
* There is no custom font

**Expected results:** 
There should not be any box ☒.

**Actual results:** 
Occasionally, ☒ is visible and it takes 5~50ms to show correct Korean character. 

**Logs**
When typing Korean it produces lots of debugging message. However, This log is not related to this issue. Those logs are printed when I combine Korean and other character like space, numbers, dot, bracket and so on. (ex: '1ㅂ1ㅂ1ㅂ') This problem should be fixed.

```
"A KeyUpEvent is dispatched, but the state shows that the physical key is pressed on a different logical key. If this occurs in real application, please report this bug to Flutter. If this occurs in unit tests, please ensure that simulated events follow Flutter's event model as documented in `HardwareKeyboard`. This was the event: KeyUpEvent#93fe4(physicalKey: PhysicalKeyboardKey#7002c(usbHidUsage: \"0x0007002c\", debugName: \"Space\"), logicalKey: LogicalKeyboardKey#00020(keyId: \"0x00000020\", keyLabel: \" \", debugName: \"Space\"), character: null, timeStamp: 0:05:15.243700, synthesized) and the recorded logical key LogicalKeyboardKey#602a3(keyId: \"0x10000070f\", keyLabel: \"Process\", debugName: \"Process\")"
```

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
        home: Scaffold(
            body: TextField(
      maxLines: null,
    )));
  }
}

```

</details>

<details>
  <summary>Logs</summary>

```
Error: Assertion failed: file:///C:/Users/dhchang/flutter/packages/flutter/lib/src/services/hardware_keyboard.dart:444:16
_pressedKeys[event.physicalKey] == event.logicalKey
"A KeyUpEvent is dispatched, but the state shows that the physical key is pressed on a different logical key. If this occurs in real application, please report this bug to Flutter. If this occurs in unit tests, please ensure that simulated events follow Flutter's event model as documented in `HardwareKeyboard`. This was the event: KeyUpEvent#93fe4(physicalKey: PhysicalKeyboardKey#7002c(usbHidUsage: \"0x0007002c\", debugName: \"Space\"), logicalKey: LogicalKeyboardKey#00020(keyId: \"0x00000020\", keyLabel: \" \", debugName: \"Space\"), character: null, timeStamp: 0:05:15.243700, synthesized) and the recorded logical key LogicalKeyboardKey#602a3(keyId: \"0x10000070f\", keyLabel: \"Process\", debugName: \"Process\")"
    at Object.throw_ [as throw] (http://localhost:63450/dart_sdk.js:5080:11)
    at Object.assertFailed (http://localhost:63450/dart_sdk.js:5005:15)
    at http://localhost:63450/packages/flutter/src/services/restoration.dart.lib.js:5444:98
    at hardware_keyboard.HardwareKeyboard.new.[_assertEventIsRegular] (http://localhost:63450/packages/flutter/src/services/restoration.dart.lib.js:5449:26)
    at hardware_keyboard.HardwareKeyboard.new.handleKeyEvent (http://localhost:63450/packages/flutter/src/services/restoration.dart.lib.js:5503:34)
    at hardware_keyboard.KeyEventManager.new.handleKeyData (http://localhost:63450/packages/flutter/src/services/restoration.dart.lib.js:5662:40)
    at http://localhost:63450/dart_sdk.js:171955:47
    at Object.invoke (http://localhost:63450/dart_sdk.js:191736:7)
    at _engine.EnginePlatformDispatcher.__.invokeOnKeyData (http://localhost:63450/dart_sdk.js:171955:17)
    at _engine.KeyboardBinding.__.[_onKeyData] (http://localhost:63450/dart_sdk.js:170642:49)
    at http://localhost:63450/dart_sdk.js:171008:21
    at _engine.KeyboardConverter.new.[_handleEvent] (http://localhost:63450/dart_sdk.js:170935:51)
    at _engine.KeyboardConverter.new.handleEvent (http://localhost:63450/dart_sdk.js:171011:27)
    at http://localhost:63450/dart_sdk.js:170648:76
    at loggedHandler (http://localhost:63450/dart_sdk.js:170625:18)
Error: Assertion failed: file:///C:/Users/dhchang/flutter/packages/flutter/lib/src/services/hardware_keyboard.dart:444:16
_pressedKeys[event.physicalKey] == event.logicalKey
"A KeyUpEvent is dispatched, but the state shows that the physical key is pressed on a different logical key. If this occurs in real application, please report this bug to Flutter. If this occurs in unit tests, please ensure that simulated events follow Flutter's event model as documented in `HardwareKeyboard`. This was the event: KeyUpEvent#f2fb5(physicalKey: PhysicalKeyboardKey#70037(usbHidUsage: \"0x00070037\", debugName: \"Period\"), logicalKey: LogicalKeyboardKey#0002e(keyId: \"0x0000002e\", keyLabel: \".\", debugName: \"Period\"), character: null, timeStamp: 0:05:16.704300, synthesized) and the recorded logical key LogicalKeyboardKey#602a3(keyId: \"0x10000070f\", keyLabel: \"Process\", debugName: \"Process\")"
    at Object.throw_ [as throw] (http://localhost:63450/dart_sdk.js:5080:11)
    at Object.assertFailed (http://localhost:63450/dart_sdk.js:5005:15)
    at http://localhost:63450/packages/flutter/src/services/restoration.dart.lib.js:5444:98
    at hardware_keyboard.HardwareKeyboard.new.[_assertEventIsRegular] (http://localhost:63450/packages/flutter/src/services/restoration.dart.lib.js:5449:26)
    at hardware_keyboard.HardwareKeyboard.new.handleKeyEvent (http://localhost:63450/packages/flutter/src/services/restoration.dart.lib.js:5503:34)
    at hardware_keyboard.KeyEventManager.new.handleKeyData (http://localhost:63450/packages/flutter/src/services/restoration.dart.lib.js:5662:40)
    at http://localhost:63450/dart_sdk.js:171955:47
    at Object.invoke (http://localhost:63450/dart_sdk.js:191736:7)
    at _engine.EnginePlatformDispatcher.__.invokeOnKeyData (http://localhost:63450/dart_sdk.js:171955:17)
    at _engine.KeyboardBinding.__.[_onKeyData] (http://localhost:63450/dart_sdk.js:170642:49)
    at http://localhost:63450/dart_sdk.js:171008:21
    at _engine.KeyboardConverter.new.[_handleEvent] (http://localhost:63450/dart_sdk.js:170935:51)
    at _engine.KeyboardConverter.new.handleEvent (http://localhost:63450/dart_sdk.js:171011:27)
    at http://localhost:63450/dart_sdk.js:170648:76
    at loggedHandler (http://localhost:63450/dart_sdk.js:170625:18)
```

</details>

<details>
 <summary>flutter doctor -v</summary>

```
flutter doctor -v
[√] Flutter (Channel stable, 3.0.1, on Microsoft Windows [Version 10.0.19044.1706], locale ko-KR)
    • Flutter version 3.0.1 at C:\Users\dhchang\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (5 days ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at C:\Users\dhchang\AppData\Local\Android\sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] VS Code (version 1.67.2)
    • VS Code at C:\Users\dhchang\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19044.1706]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 101.0.4951.67
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 101.0.1210.53

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

</details>

**Comment by maheshmnj** [comment] 2022-05-25 10:39
Hi @dohuon, thanks for filing the issue. I am able to reproduce the issue on stable and the master channel. The Korean characters are displayed with a `placeholder`  character before rendering for the first time. This issue is reproducible only with canvaskit and works fine with HTML renderer and also on Windows Desktop.

This happens with other languages too apart from korean, verified with Simplified Chinese.

### Canvaskit
https://user-images.githubusercontent.com/31410839/170243494-85ddb331-510c-48a6-9c5d-fc5326121130.mp4

### HTML

https://user-images.githubusercontent.com/31410839/170243506-be365117-50d1-4bf2-af73-d6919259f62e.mp4


<details>
<summary>logs</summary>

```
PS C:\Users\mahesh\Desktop\keyboardissue> flutter run -d chrome
Launching lib\main.dart on Chrome in debug mode...
Waiting for connection from debug service on Chrome...             30.1s
This app is linked to the debug service:
ws://127.0.0.1:55772/is0lJijDv5o=/ws    
Debug service listening on ws://127.0.0.1:55772/is0lJijDv5o=/ws

 Running with sound null safety 

  To hot restart changes while running, press "r" or "R".       
For a more detailed help message, press "h". To quit, press "q".

An Observatory debugger and profiler on Chrome is available at:
http://127.0.0.1:55772/is0lJijDv5o=
Flutter Web Bootstrap: Programmatic
The Flutter DevTools debugger and profiler on Chrome is available at:
http://127.0.0.1:9101?uri=http://127.0.0.1:55772/is0lJijDv5o=
Error: Assertion failed:
file:///C:/flutter_sdk/stable/packages/flutter/lib/src/services/hardware_keyboard.dart:444:16
_pressedKeys[event.physicalKey] == event.logicalKey
"A KeyUpEvent is dispatched, but the state shows that the physical key is   
pressed on a different logical key. If this occurs in real application,     
please report this bug to Flutter. If this occurs in unit tests, please     
ensure that simulated events follow Flutter's event model as documented in  
`HardwareKeyboard`. This was the event: KeyUpEvent#9cfe1(physicalKey:       
PhysicalKeyboardKey#700e0(usbHidUsage: \"0x000700e0\", debugName: \"Control 
Left\"), logicalKey: LogicalKeyboardKey#b7bd2(keyId: \"0x200000100\",       
keyLabel: \"Control Left\", debugName: \"Control Left\"), character: null,  
timeStamp: 0:01:00.683700, synthesized) and the recorded logical key        
LogicalKeyboardKey#602a3(keyId: \"0x10000070f\", keyLabel: \"Process\",     
debugName: \"Process\")"
    at Object.throw_ [as throw] (http://localhost:55717/dart_sdk.js:5080:11)    at Object.assertFailed (http://localhost:55717/dart_sdk.js:5005:15)     
    at
    http://localhost:55717/packages/flutter/src/services/restoration.dart.li    b.js:5444:98
    at hardware_keyboard.HardwareKeyboard.new.[_assertEventIsRegular]       
    (http://localhost:55717/packages/flutter/src/services/restoration.dart.l    ib.js:5449:26)
    at hardware_keyboard.HardwareKeyboard.new.handleKeyEvent
    (http://localhost:55717/packages/flutter/src/services/restoration.dart.l    ib.js:5503:34)
    at hardware_keyboard.KeyEventManager.new.handleKeyData
    (http://localhost:55717/packages/flutter/src/services/restoration.dart.l    ib.js:5662:40)
    at http://localhost:55717/dart_sdk.js:171955:47
    at Object.invoke (http://localhost:55717/dart_sdk.js:191736:7)
    at _engine.EnginePlatformDispatcher.__.invokeOnKeyData
    (http://localhost:55717/dart_sdk.js:171955:17)
    at _engine.KeyboardBinding.__.[_onKeyData]
    (http://localhost:55717/dart_sdk.js:170642:49)
    at http://localhost:55717/dart_sdk.js:171008:21
    at _engine.KeyboardConverter.new.[_handleEvent]
    (http://localhost:55717/dart_sdk.js:170935:51)
    at _engine.KeyboardConverter.new.handleEvent
    (http://localhost:55717/dart_sdk.js:171011:27)
    at http://localhost:55717/dart_sdk.js:170648:76
    at loggedHandler (http://localhost:55717/dart_sdk.js:170625:18)
Error: Assertion failed:
file:///C:/flutter_sdk/stable/packages/flutter/lib/src/services/hardware_keyboard.dart:444:16
_pressedKeys[event.physicalKey] == event.logicalKey
"A KeyUpEvent is dispatched, but the state shows that the physical key is   
pressed on a different logical key. If this occurs in real application,     
please report this bug to Flutter. If this occurs in unit tests, please     
ensure that simulated events follow Flutter's event model as documented in  
`HardwareKeyboard`. This was the event: KeyUpEvent#add4c(physicalKey:       
PhysicalKeyboardKey#70004(usbHidUsage: \"0x00070004\", debugName: \"Key     
A\"), logicalKey: LogicalKeyboardKey#00061(keyId: \"0x00000061\", keyLabel: 
\"A\", debugName: \"Key A\"), character: null, timeStamp: 0:01:00.870800,   
synthesized) and the recorded logical key LogicalKeyboardKey#602a3(keyId:   
\"0x10000070f\", keyLabel: \"Process\", debugName: \"Process\")"
    at Object.throw_ [as throw] (http://localhost:55717/dart_sdk.js:5080:11)    at Object.assertFailed (http://localhost:55717/dart_sdk.js:5005:15)     
    at
    http://localhost:55717/packages/flutter/src/services/restoration.dart.li    b.js:5444:98
    at hardware_keyboard.HardwareKeyboard.new.[_assertEventIsRegular]       
    (http://localhost:55717/packages/flutter/src/services/restoration.dart.l    ib.js:5449:26)
    at hardware_keyboard.HardwareKeyboard.new.handleKeyEvent
    (http://localhost:55717/packages/flutter/src/services/restoration.dart.l    at hardware_keyboard.KeyEventManager.new.handleKeyData
    (http://localhost:55717/packages/flutter/src/services/restoration.dart.l    ib.js:5662:40)
    at http://localhost:55717/dart_sdk.js:171955:47
    at Object.invoke (http://localhost:55717/dart_sdk.js:191736:7)
    at _engine.EnginePlatformDispatcher.__.invokeOnKeyData
    (http://localhost:55717/dart_sdk.js:171955:17)
    at _engine.KeyboardBinding.__.[_onKeyData]
    (http://localhost:55717/dart_sdk.js:170642:49)
    at http://localhost:55717/dart_sdk.js:171008:21
    at _engine.KeyboardConverter.new.[_handleEvent]
    at _engine.KeyboardConverter.new.handleEvent
    at http://localhost:55717/dart_sdk.js:170648:76
    at loggedHandler (http://localhost:55717/dart_sdk.js:170625:18)
Application finished.
```
</details>


<details>
<summary>flutter doctor -v (windows)</summary>

```
[√] Flutter (Channel stable, 3.0.1, on Microsoft Windows [Version 10.0.19044.1706], locale en-IN)
    • Flutter version 3.0.1 at C:\flutter_sdk\stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (3 days ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

Checking Android licenses is taking an unexpectedly long time...[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\mahesh\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java  
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe       

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.4)      
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31727.386
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] VS Code (version 1.64.2)
    • VS Code at C:\Users\mahesh\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.40.0

[√] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 12 (API 31) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version
      10.0.19044.1706]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 101.0.4951.67
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 100.0.1185.50

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
```
[√] Flutter (Channel master, 3.1.0-0.0.pre.854, on Microsoft Windows [Version 10.0.19044.1706], locale en-IN)
    • Flutter version 3.1.0-0.0.pre.854 at C:\flutter_sdk\master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ec20ea80ad (30 hours ago), 2022-05-21 16:28:06 -0400
    • Engine revision 1bfe551d6b
    • Dart version 2.18.0 (build 2.18.0-142.0.dev)
    • DevTools version 2.13.1

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\mahesh\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31727.386
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] VS Code (version 1.64.2)
    • VS Code at C:\Users\mahesh\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.40.0

[√] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 12 (API 31) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version
      10.0.19044.1706]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 101.0.4951.67
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 100.0.1185.50

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by maheshmnj** [comment] 2022-05-25 12:35
Closing as duplicate of https://github.com/flutter/flutter/issues/77023

**Closed by maheshmnj** 2022-05-25 12:35 UTC
Labels: a: text input, engine, a: internationalization, platform-windows, a: typography, platform-web, e: web_canvaskit, has reproducible steps, found in release: 3.0, found in release: 3.1
