### ISSUE TITLE
Assertion Error: Trailing widget consumes entire tile width

### ISSUE THREAD

**Issue by Mohanraj-SF4239** [flutter/flutter#160029] opened 2024-12-10 15:33 UTC
### Steps to reproduce

- Use the flutter latest sdk version.
- Execute the below given code.

### Expected results

When tapped on expand, the container should animate and expand.

### Actual results

When tapped on expand, assertion error is thrown.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: AnimatedContainerDemo(),
    );
  }
}

class AnimatedContainerDemo extends StatefulWidget {
  const AnimatedContainerDemo({super.key});

  @override
  AnimatedContainerDemoState createState() => AnimatedContainerDemoState();
}

class AnimatedContainerDemoState extends State<AnimatedContainerDemo> {
  bool _isExpanded = true;

  void _toggleContainer() {
    setState(() {
      _isExpanded = !_isExpanded;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Animated Container with Expansion Tiles')),
      body: Column(
        mainAxisSize: MainAxisSize.min,
        children: [
          ElevatedButton(
            onPressed: _toggleContainer,
            child: Text(_isExpanded ? 'Collapse' : 'Expand'),
          ),
          AnimatedContainer(
            decoration: const BoxDecoration(color: Colors.blue),
            duration: const Duration(milliseconds: 300),
            width: _isExpanded ? 300 : 80,
            height: 400,
            child: _isExpanded
                ? const SingleChildScrollView(
                  child: Column( // Use flexible layout constraints.
                      mainAxisSize: MainAxisSize.min,
                      children: [
                        ExpansionTile(
                          title: Text('Tile 1'),
                          trailing: SizedBox(
                            width: 60,
                            child: Icon(Icons.arrow_drop_down),
                          ),
                          children: <Widget>[
                            ListTile(title: Text('Item 1')),
                            ListTile(title: Text('Item 2')),
                          ],
                        ),
                        ExpansionTile(
                          trailing: SizedBox(
                            width: 60,
                            child: Icon(Icons.arrow_drop_down),
                          ),
                          title: Text('Tile 2'),
                          children: <Widget>[
                            ListTile(title: Text('Item 3')),
                            ListTile(title: Text('Item 4')),
                          ],
                        ),
                        ExpansionTile(
                          trailing: SizedBox(
                            width: 60,
                            child: Icon(Icons.arrow_drop_down),
                          ),
                          title: Text('Tile 3'),
                          children: <Widget>[
                            ListTile(title: Text('Item 5')),
                            ListTile(title: Text('Item 6')),
                          ],
                        ),
                      ],
                    ),
                )
                : Column(
                  children: [
                    Container(
                      height: 100,
                        color: Colors.amber,
                        child: const Text('Collapsed State 1'),
                      ),
                      Container(
                      height: 100,
                        color: Colors.green,
                        child: const Text('Collapsed State 2'),
                      ),
                  ],
                ),
          ),
        ],
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

![image](https://github.com/user-attachments/assets/6bbe0b28-f9a8-46b8-9b83-ae8a813c7c2f)
![image](https://github.com/user-attachments/assets/eb214907-3a00-47ac-9aaf-3d6e633aee77)

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.24.5, on Microsoft Windows [Version 10.0.22631.4460], locale en-US)
    • Flutter version 3.24.5 on channel stable at D:\flutter_windows_3.24.5-stable\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision dec2ee5c1f (4 weeks ago), 2024-11-13 11:13:06 -0800
    • Engine revision a18df97ca5
    • Dart version 3.5.4
    • DevTools version 2.37.3

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[!] Android toolchain - develop for Android devices (Android SDK version 35.0.0-rc3)
    • Android SDK at C:\Users\MohanRajSrinivasan\AppData\Local\Android\sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/to/windows-android-setup for more details.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✗] Visual Studio - develop Windows apps
    ✗ Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[✓] Android Studio (version 2022.3)
    • Android Studio at C:\Program Files\Android\Android Studio2
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)

[✓] VS Code (version 1.95.3)
    • VS Code at C:\Users\MohanRajSrinivasan\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.102.0

[✓] VS Code, 64-bit edition (version unknown)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.102.0
    ✗ Unable to determine VS Code version.

[✓] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 14 (API 34) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.22631.4460]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 131.0.6778.109
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 131.0.2903.86

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
```

</details>

**Comment by maheshj01** [comment] 2024-12-10 23:45
Hello @Mohanraj-SF4239, thanks for filing the issue.  This issue is reproducible on the latest stable and the master channel.
It looks like the Listtile is getting incorrect width


<details>
<summary>logs</summary>

```console
Restarted application in 1,071ms.
D/EGL_emulation(15583): app_time_stats: avg=20777.43ms min=6.13ms max=41548.74ms count=2
D/EGL_emulation(15583): app_time_stats: avg=3116.92ms min=3116.92ms max=3116.92ms count=1
D/EGL_emulation(15583): app_time_stats: avg=45.41ms min=3.47ms max=854.60ms count=30

════════ Exception caught by rendering library ═════════════════════════════════
The following assertion was thrown during performLayout():
Trailing widget consumes entire tile width. Please use a sized widget, or consider replacing ListTile with a custom widget (see https://api.flutter.dev/flutter/material/ListTile-class.html#material.ListTile.4)
'package:flutter/src/material/list_tile.dart':
Failed assertion: line 1356 pos 7: 'tileWidth != trailingSize?.width || tileWidth == 0.0'

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.yml

The relevant error-causing widget was:
    ExpansionTile ExpansionTile:file:///Users/mahesh/Desktop/platform_stack_test/lib/main.dart:55:25

When the exception was thrown, this was the stack:
#2      _RenderListTile._computeSizes (package:flutter/src/material/list_tile.dart:1356:7)
list_tile.dart:1356
```
</details> 

<details>
<summary>flutter doctor -v</summary>

```
mahesh@LT-328818-CCB platform_stack_test % flutter doctor -v
Could not load custom device from config index 0: Expected enabled to be a boolean.
[✓] Flutter (Channel stable, 3.24.3, on macOS 15.1.1 24B2091 darwin-arm64, locale en-IN)
    • Flutter version 3.24.3 on channel stable at /Users/mahesh/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2663184aa7 (3 months ago), 2024-09-11 16:27:48 -0500
    • Engine revision 36335019a8
    • Dart version 3.5.3
    • DevTools version 2.37.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-35, build-tools 34.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16A242d
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.94.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.100.0
```

```console
mahesh@LT-328818-CCB platform_stack_test % flutterm doctor -v
Could not load custom device from config index 0: Expected enabled to be a boolean.
[!] Flutter (Channel master, 3.27.0-1.0.pre.773, on macOS 15.1.1 24B2091 darwin-arm64, locale en-IN)
    • Flutter version 3.27.0-1.0.pre.773 on channel master at /Users/mahesh/Development/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/mahesh/Development/flutter/bin/flutter, which is not inside your current Flutter SDK
      checkout at /Users/mahesh/Development/flutter_master. Consider adding /Users/mahesh/Development/flutter_master/bin to the front of your
      path.
    ! Warning: `dart` on your path resolves to /Users/mahesh/Development/flutter/bin/dart, which is not inside your current Flutter SDK checkout
      at /Users/mahesh/Development/flutter_master. Consider adding /Users/mahesh/Development/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 0147b1f0ec (37 minutes ago), 2024-12-10 15:07:59 -0800
    • Engine revision 23fc43d5e6
    • Dart version 3.7.0 (build 3.7.0-231.0.dev)
    • DevTools version 2.41.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks
      and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-35, build-tools 34.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
      This is the JDK bundled with the latest Android Studio installation on this machine.
      To manually set the JDK path, use: `flutter config --jdk-dir="path/to/jdk"`.
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16A242d
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.94.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.100.0

[✓] Connected device (5 available)
    • sdk gphone64 arm64 (mobile)     • emulator-5554                        • android-arm64  • Android 12 (API 31) (emulator)
    • iPhone 16 Pro (mobile)          • 34497AEA-B6B0-4F79-99A3-6E40007745A3 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-18-0
      (simulator)
    • macOS (desktop)                 • macos                                • darwin-arm64   • macOS 15.1.1 24B2091 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad                • darwin         • macOS 15.1.1 24B2091 darwin-arm64
    • Chrome (web)                    • chrome                               • web-javascript • Google Chrome 128.0.6613.85

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>

**Comment by TahaTesser** [comment] 2024-12-11 13:53
Here is a simplified code sample reproducing this bug 

<details>
<summary>expand to view the code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: ListTileSample(),
    );
  }
}

class ListTileSample extends StatefulWidget {
  const ListTileSample({super.key});

  @override
  ListTileSampleState createState() => ListTileSampleState();
}

class ListTileSampleState extends State<ListTileSample> {
  bool _isExpanded = true;

  void _toggleExpansion() {
    setState(() {
      _isExpanded = !_isExpanded;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Column(
          spacing: 16,
          mainAxisSize: MainAxisSize.min,
          children: [
            AnimatedContainer(
              duration: Durations.medium4,
              width: _isExpanded ? 300 : 80,
              child: _isExpanded
                  ? const ListTile(
                      title: Text('Tile'),
                      tileColor: Colors.amber,
                      trailing: SizedBox(
                        width: 60,
                        child: Icon(Icons.arrow_drop_down),
                      ),
                    )
                  : const Placeholder(
                      fallbackHeight: 48,
                      fallbackWidth: 300,
                    ),
            ),
            ElevatedButton(
              onPressed: _toggleExpansion,
              child: Text(_isExpanded ? 'Collapse' : 'Expand'),
            ),
          ],
        ),
      ),
    );
  }
}

```

</details>

**Comment by TahaTesser** [comment] 2024-12-11 14:21
duplicate of https://github.com/flutter/flutter/issues/159380

**Closed by TahaTesser** 2024-12-11 14:21 UTC
Labels: framework, f: material design, a: error message, team-framework, found in release: 3.24, found in release: 3.27
