### ISSUE TITLE
[tool_crash] OutOfMemoryError: (null)

### ISSUE THREAD

**Issue by ramahussein47** [flutter/flutter#153164] opened 2024-08-09 14:23 UTC
## Command
```
flutter run
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
OutOfMemoryError: (null)
```
#0      new Uint8List (dart:typed_data-patch/typed_data_patch.dart:2236:3)
#1      _File.readAsBytesSync (dart:io/file_impl.dart:589:16)
#2      ForwardingFile.readAsBytesSync (package:file/src/forwarding/forwarding_file.dart:91:43)
#3      ForwardingFile.readAsBytesSync (package:file/src/forwarding/forwarding_file.dart:91:43)
#4      _calculateSha (package:flutter_tools/src/android/gradle.dart:933:32)
#5      AndroidGradleBuilder.buildGradleApp (package:flutter_tools/src/android/gradle.dart:594:36)
#6      _rootRunUnary (dart:async/zone.dart:1407:47)
#7      _CustomZone.runUnary (dart:async/zone.dart:1308:19)
#8      _FutureListener.handleValue (dart:async/future_impl.dart:162:18)
#9      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:838:45)
#10     Future._propagateToListeners (dart:async/future_impl.dart:867:13)
#11     Future._completeWithValue (dart:async/future_impl.dart:643:5)
#12     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:713:7)
#13     _rootRun (dart:async/zone.dart:1399:13)
#14     _CustomZone.run (dart:async/zone.dart:1301:19)
#15     _CustomZone.runGuarded (dart:async/zone.dart:1209:7)
#16     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1249:23)
#17     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#18     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
#19     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#20     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:185:5)
```
```
[32m[✓][39m Flutter (Channel stable, 3.19.0, on Microsoft Windows [Version 10.0.22631.3958], locale en-GB)
    [32m•[39m Flutter version 3.19.0 on channel stable at C:\Flutter\flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision bae5e49bc2 (6 months ago), 2024-02-13 17:46:18 -0800
    [32m•[39m Engine revision 04817c99c9
    [32m•[39m Dart version 3.3.0
    [32m•[39m DevTools version 2.31.1

[32m[✓][39m Windows Version (Installed version of Windows is version 10 or higher)

[33m[!][39m Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    [32m•[39m Android SDK at C:\Users\rama\AppData\Local\Android\sdk
    [31m✗[39m cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    [31m✗[39m Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[33m[!][39m Visual Studio - develop Windows apps (Visual Studio Community 2022 17.10.3)
    [32m•[39m Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    [32m•[39m Visual Studio Community 2022 version 17.10.35013.160
    [31m✗[39m The current Visual Studio installation is incomplete.
      Please use Visual Studio Installer to complete the installation or reinstall Visual Studio.

[32m[✓][39m Android Studio (version 2023.1)
    [32m•[39m Android Studio at D:\Andriod Studio
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)

[32m[✓][39m VS Code (version unknown)
    [32m•[39m VS Code at C:\Users\rama\AppData\Local\Programs\Microsoft VS Code
    [32m•[39m Flutter extension version 3.94.0
    [31m✗[39m Unable to determine VS Code version.

[32m[✓][39m Connected device (4 available)
    [32m•[39m Infinix X6517 (mobile) • 097784034P003530 • android-arm64  • Android 12 (API 31)
    [32m•[39m Windows (desktop)      • windows          • windows-x64    • Microsoft Windows [Version 10.0.22631.3958]
    [32m•[39m Chrome (web)           • chrome           • web-javascript • Google Chrome 127.0.6533.90
    [32m•[39m Edge (web)             • edge             • web-javascript • Microsoft Edge 127.0.2651.86

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[33m![39m Doctor found issues in 2 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: bae5e49bc2a867403c43b2aae2de8f8c33b037e4
### Plugins
camera-0.11.0+1
camera_android_camerax-0.6.5+2
camera_avfoundation-0.9.17+1
camera_web-0.3.4
cloud_firestore-5.2.1
cloud_firestore_web-4.1.1
file_selector_linux-0.9.2+1
file_selector_macos-0.9.4
file_selector_windows-0.9.3+2
firebase_auth-5.1.2
firebase_auth_web-5.12.4
firebase_core-3.3.0
firebase_core_web-2.17.4
flutter_plugin_android_lifecycle-2.0.19
google_mlkit_barcode_scanning-0.12.0
google_mlkit_commons-0.7.1
google_mlkit_digital_ink_recognition-0.12.0
google_mlkit_entity_extraction-0.13.0
google_mlkit_face_detection-0.11.0
google_mlkit_face_mesh_detection-0.2.0
google_mlkit_image_labeling-0.12.0
google_mlkit_language_id-0.11.0
google_mlkit_object_detection-0.13.0
google_mlkit_pose_detection-0.12.0
google_mlkit_selfie_segmentation-0.8.0
google_mlkit_smart_reply-0.11.0
google_mlkit_text_recognition-0.13.0
google_mlkit_translation-0.11.0
image_picker-1.1.2
image_picker_android-0.8.12+1
image_picker_for_web-3.0.4
image_picker_ios-0.8.12
image_picker_linux-0.2.1+1
image_picker_macos-0.2.1+1
image_picker_web-4.0.0
image_picker_windows-0.2.1+1
path_provider-2.1.3
path_provider_android-2.2.4
path_provider_foundation-2.4.0
path_provider_linux-2.2.1
path_provider_windows-2.3.0
Solution : the directory of the flutter project you are is full . Clear some files and try running the application again

**Comment by huycozy** [comment] 2024-08-12 05:03
Closing this as a duplicate of https://github.com/flutter/flutter/issues/133371

**Closed by huycozy** 2024-08-12 05:03 UTC
Labels: in triage
