### ISSUE TITLE
[macOS] Can't scroll on macOS High Sierra 10.13.6

### ISSUE THREAD

**Issue by AndroidNils** [flutter/flutter#56870] opened 2020-05-11 08:16 UTC
## Problem
Two customers reported that they can't scroll in our macOS app. Both have macOS High Sierra 10.13.6. Are there any known issue with scrolling in Flutter macOS apps and macOS High Sierra?

## Additional information: 

- We mostly use the `SingleChildScrollView` Widget.
- Link to our App: https://sharezone.net/macos
- We published our macOS App with Flutter master channel

**Comment by VladyslavBondarenko** [comment] 2020-05-11 12:48
Hi @AndroidNils 
provide please your `flutter doctor -v`

**Comment by stuartmorgan** [comment] 2020-05-13 22:39
Duplicate of https://github.com/flutter/flutter/issues/49242

We don't have any idea how this is happening; are you able to get more information from the people reporting this if we figure out the right questions?

**Closed by stuartmorgan** 2020-05-13 22:39 UTC
Labels: a: desktop, e: OS Version specific, f: scrolling, framework, platform-mac

**Comment by AndroidNils** [comment] 2020-05-14 12:00
@stuartmorgan Done ✅ I commented below the other issue (https://github.com/flutter/flutter/issues/49242)
