### ISSUE TITLE
Non-Material3 IconButton Isn't functioning like it's supposed to be.

### ISSUE THREAD

**Issue by psyirius** [flutter/flutter#121072] opened 2023-02-20 03:13 UTC
![image](https://user-images.githubusercontent.com/99079175/220000194-a1f529b9-aca8-446a-816f-07f923c3c1e4.png)

The selectable behavior of IconButton is as stated as above.

But what the code does is.

https://github.com/flutter/flutter/blob/c71e479fd4e5db49165578b9bca1311668d8ed08/packages/flutter/lib/src/material/icon_button.dart#L568-L693

The selection logic only happens when if it's a Material3 Button.

**Comment by psyirius** [comment] 2023-02-20 04:39
Our personal fix.

```dart
@override
Widget build(BuildContext context) {
  final ThemeData theme = Theme.of(context);

  // added
  Widget effectiveIcon = icon;
  if ((isSelected ?? false) && selectedIcon != null) {
    effectiveIcon = selectedIcon!;
  }
  
  // added
  if (tooltip != null) {
    effectiveIcon = Tooltip(
      message: tooltip,
      child: effectiveIcon,
    );
  }

  if (theme.useMaterial3) {
    final Size? minSize = constraints == null
        ? null
        : Size(constraints!.minWidth, constraints!.minHeight);
    final Size? maxSize = constraints == null
        ? null
        : Size(constraints!.maxWidth, constraints!.maxHeight);

    ButtonStyle adjustedStyle = styleFrom(
      visualDensity: visualDensity,
      foregroundColor: color,
      disabledForegroundColor: disabledColor,
      focusColor: focusColor,
      hoverColor: hoverColor,
      highlightColor: highlightColor,
      padding: padding,
      minimumSize: minSize,
      maximumSize: maxSize,
      iconSize: iconSize,
      alignment: alignment,
      enabledMouseCursor: mouseCursor,
      disabledMouseCursor: mouseCursor,
      enableFeedback: enableFeedback,
    );
    if (style != null) {
      adjustedStyle = style!.merge(adjustedStyle);
    }

    // removed
    // removed

    return _SelectableIconButton(
      style: adjustedStyle,
      onPressed: onPressed,
      autofocus: autofocus,
      focusNode: focusNode,
      isSelected: isSelected,
      child: effectiveIcon, // changed
    );
  }

  assert(debugCheckHasMaterial(context));

  Color? currentColor;
  if (onPressed != null) {
    currentColor = color;
  } else {
    currentColor = disabledColor ?? theme.disabledColor;
  }

  final VisualDensity effectiveVisualDensity = visualDensity ?? theme.visualDensity;

  final BoxConstraints unadjustedConstraints = constraints ?? const BoxConstraints(
    minWidth: _kMinButtonSize,
    minHeight: _kMinButtonSize,
  );
  final BoxConstraints adjustedConstraints = effectiveVisualDensity.effectiveConstraints(unadjustedConstraints);
  final double effectiveIconSize = iconSize ?? IconTheme.of(context).size ?? 24.0;
  final EdgeInsetsGeometry effectivePadding = padding ?? const EdgeInsets.all(8.0);
  final AlignmentGeometry effectiveAlignment = alignment ?? Alignment.center;
  final bool effectiveEnableFeedback = enableFeedback ?? true;

  Widget result = ConstrainedBox(
    constraints: adjustedConstraints,
    child: Padding(
      padding: effectivePadding,
      child: SizedBox(
        height: effectiveIconSize,
        width: effectiveIconSize,
        child: Align(
          alignment: effectiveAlignment,
          child: IconTheme.merge(
            data: IconThemeData(
              size: effectiveIconSize,
              color: currentColor,
            ),
            child: effectiveIcon, // changed
          ),
        ),
      ),
    ),
  );
  
  // removed

  return Semantics(
    button: true,
    enabled: onPressed != null,
    child: InkResponse(
      focusNode: focusNode,
      autofocus: autofocus,
      canRequestFocus: onPressed != null,
      onTap: onPressed,
      mouseCursor: mouseCursor ?? (onPressed == null ? SystemMouseCursors.basic : SystemMouseCursors.click),
      enableFeedback: effectiveEnableFeedback,
      focusColor: focusColor ?? theme.focusColor,
      hoverColor: hoverColor ?? theme.hoverColor,
      highlightColor: highlightColor ?? theme.highlightColor,
      splashColor: splashColor ?? theme.splashColor,
      radius: splashRadius ?? math.max(
        Material.defaultSplashRadius,
        (effectiveIconSize + math.min(effectivePadding.horizontal, effectivePadding.vertical)) * 0.7,
        // x 0.5 for diameter -> radius and + 40% overflow derived from other Material apps.
      ),
      child: result,
    ),
  );
}
```

**Comment by exaby73** [comment] 2023-02-20 12:43
Hello @psyirius. Thank you for filing this issue. Can you please provide the following information?

- A [complete and minimal, reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example). Ideally, a single `main.dart` file that can be run directly.
- The output of `flutter doctor -v`

Please provide the information in the form of text. See how to make collapsible sections with Markdown [here](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/organizing-information-with-collapsed-sections).

**Comment by psyirius** [comment] 2023-02-21 05:05
#### Flutter Doctor Info

```
~> flutter doctor --verbose

[√] Flutter (Channel stable, 3.7.3, on Microsoft Windows [Version 10.0.19045.2604], locale en-US)
    • Flutter version 3.7.3 on channel stable at C:\Flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9944297138 (12 days ago), 2023-02-08 15:46:04 -0800
    • Engine revision 248290d6d5
    • Dart version 2.19.2
    • DevTools version 2.20.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at D:/Android/SDK
    • Platform android-UpsideDownCake, build-tools 33.0.1
    • ANDROID_HOME = D:\Android\SDK
    • Java binary at: C:\Program Files\Java\jdk-19\bin\java
    • Java version Java(TM) SE Runtime Environment (build 19.0.2+7-44)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[!] Android Studio (version 2022.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    X Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[√] VS Code, 64-bit edition (version 1.75.0)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (5 available)
    • M2010J19SG (mobile)          • fab5c1300621  • android-arm64  • Android 13 (API 33)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 13 (API 33) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.19045.2604]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 110.0.5481.96
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 110.0.1587.50

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.
```

<details><summary>Reproducible code sample</summary>
<p>

#### A complete app to reproduce the bug

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter IconButton Selection Bug Demo',
      theme: ThemeData(
        useMaterial3: false, // enabling this makes it work
        primarySwatch: Colors.teal,
      ),
      home: const BugHomePage(title: 'Flutter IconButton Selection Bug Demo'),
    );
  }
}

class BugHomePage extends StatefulWidget {
  final String title;

  const BugHomePage({super.key, required this.title});

  @override
  State<BugHomePage> createState() => _BugHomePageState();
}

class _BugHomePageState extends State<BugHomePage> {
  bool _selected = false;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            IconButton(
              isSelected: _selected,
              onPressed: () {
                setState(() {
                  _selected = !_selected;
                });
              },
              icon: const Icon(Icons.add),
              selectedIcon: const Icon(Icons.add_box),
            ),
            const SizedBox(height: 32),
            Center(
              child: Text('Selected: $_selected'),
            )
          ],
        ),
      ),
    );
  }
}
```

</p>
</details>

**Comment by exaby73** [comment] 2023-02-21 08:25
Hello @psyirius. Looks like this is working as intended. The documentation states that `selectedIcon` only will work when `useMaterial3` is `true`

https://github.com/flutter/flutter/blob/c71e479fd4e5db49165578b9bca1311668d8ed08/packages/flutter/lib/src/material/icon_button.dart#L452-L466

**Comment by psyirius** [comment] 2023-02-21 13:21
Oh. didn't see that next line.
But why is that tho?
There is no Selectable Icon Button in Material design system?

**Comment by exaby73** [comment] 2023-02-21 15:27
The M2 equivalent is Toggle Buttons. In the spec, it does not have a selected icon state. While in M3, it does https://m3.material.io/components/icon-buttons/specs. Since this is working as expected, aligned to the specs, I am closing this issue. If you disagree, please comment with your reasoning and I can reopen the issue. Thank you

**Closed** 2023-02-21 15:27 UTC
Labels: r: invalid, in triage

**Comment by psyirius** [comment] 2023-02-21 16:12
Oh okay thanks for the clarification
