### ISSUE TITLE
Make 'print' throttle its output

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#232] opened 2015-11-09 21:51 UTC
<a href="https://github.com/Hixie"><img src="https://avatars.githubusercontent.com/u/551196?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Hixie](https://github.com/Hixie)**
_Monday Oct 26, 2015 at 21:30 GMT_
_Originally opened as https://github.com/flutter/engine/issues/1804_

---

We should move the `debugPrint()` logic in rendering/debug.dart to the C++ side. It does seem to have solved the problem of data loss during high-volume logging.

(Having it on the C++ side, as native behaviour of Dart's `print()` built-in, would mean that all debug output would be throttled the same way, so people writing new frameworks would get this automatically, and people wouldn't have to import rendering.dart to get it even in regular Flutter apps.)

**Comment by sethladd** [comment] 2016-09-14 17:12
Do we still plan to do this?

**Comment by Hixie** [comment] 2016-09-14 17:15
Yes. Having debugPrint and print do different things leads to a confusing debug experience.

**Comment by eseidelGoogle** [comment] 2017-06-06 20:19
FYI @cbracken who's been in print stuff recently. (Not important, just thought you might like to see.)

**Comment by pedromassangocode** [comment] 2020-08-26 09:35
Does this still a valid issue?

**Comment by cbracken** [comment] 2020-08-27 17:35
`debugPrint` has moved from rendering to `lib/src/foundation/print.dart` where you can find `debugPrintThrottled` which still buffers lines in a list of strings, then schedules periodic flushes.

The intent here is to shift that logic from the framework to `dart:ui` in the engine so that people writing alternative frameworks could make use of it without having to pull in bits of the Flutter framework. In that sense, the issue is still valid, but given that a vast majority of our users are using Flutter with the framework (and not just `dart:ui`), this is likely to remain low on our priority list for the time being. Given that we've pulled it out of the render layer and into the foundation layer of the framework, it's probably even lower priority than it once was.

 If someone in the community would like to implement this, I'll gladly review it though!

**Comment by pedromassangocode** [comment] 2020-08-28 06:34
I would like to take this. So what needs to be done is to move the `print.dart` file to the `sky_engine/ui` directory?

**Comment by Hixie** [comment] 2021-02-04 00:26
debugPrint has evolved into a more elaborate API than would make sense to squeeze into `print`, so I think this is now WONTFIX.

**Closed by Hixie** 2021-02-04 00:26 UTC
Labels: P5, engine, framework, passed first triage, team
