### ISSUE TITLE
Video_player volume back after a voice call

### ISSUE THREAD

**Issue by ReaganRealones** [flutter/flutter#57902] opened 2020-05-24 18:45 UTC
## Steps to Reproduce

1. Very simple to reproduce.
2. Mute the video player volume using `setVolume(0)`.
3. Run the example to and start playing video.
4. While the video is playing, make a voice call to the device and you will notice after the call, the whole volume is back. 

**Expected results:** 
I expected that if I mute the volume of the video, after the voice call the video is supposed to remain mute.

**Actual results:** 
The Video volume is back after the call, and trying to listen to the video controller for changes does not work for this as this change in volume is not picked up, i.e trying to print the volume still returns 0.0.
<details>
  <summary>Flutter Doctor Output</summary>

[√] Flutter (Channel stable, v1.17.1, on Microsoft Windows [Version 10.0.18363.476], locale en-UG)
    • Flutter version 1.17.1 at C:\flutter
    • Framework revision f7a6a7906b (12 days ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at C:\Android\sdk
    • Platform android-29, build-tools 29.0.1
    • ANDROID_HOME = C:\Android\sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 39.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] VS Code (version 1.45.0)
    • VS Code at C:\Users\Reagan Realones\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.10.1

[√] Connected device (1 available)
    • TECNO AB7 • 0456725988000504 • android-arm64 • Android 9 (API 28)

• No issues found!

```
```

</details>

**Comment by TahaTesser** [comment] 2020-05-25 11:50
duplicate of https://github.com/flutter/flutter/issues/43346

**Closed by TahaTesser** 2020-05-25 11:50 UTC
