### ISSUE TITLE
[web][question] Mouse pointer on hover buttons/clickable widgets on Flutter web in desktop browsers

### ISSUE THREAD

**Issue by ja2375** [flutter/flutter#49710] opened 2020-01-29 16:51 UTC
Hello!

I have a question. I know that i can implement this in my own project, but i want to know whether Flutter web will support changing mouse to pointer on desktop web browsers natively without adding any extra code.

I mean, in order to have a native web experience, it's somehow weird to me that, if any widget in my app is clickable, the mouse cursor does not change. There is already a super cool glow effect that works perfectly well, so it has to be possible and also really easy to make this part of Flutter web SDK natively.

Many thanks!

**Comment by goderbauer** [comment] 2020-01-30 22:01
Dupe of https://github.com/flutter/flutter/issues/31952.

**Closed by goderbauer** 2020-01-30 22:01 UTC
Labels: a: fidelity, framework, ☸ platform-web
