### ISSUE TITLE
window.physicalSize not initialised immediately in release build on Android

### ISSUE THREAD

**Issue by xvrh** [flutter/flutter#102963] opened 2022-05-03 08:44 UTC
## Steps to Reproduce

1. Execute `flutter run --release` on the code sample with an Android device (I test with a Pixel 6, Android 12) 
2. The code repeatedly query the property `window.physicalSize` from `dart:ui` after the start.

**Expected results:** 
1) `window.physicalSize` should be initialised immediately.
2) Debug & release should have the same behaviour.

**Actual results:** 

1) `window.physicalSize` is `Size(0, 0)` during a few milliseconds until it get it final value.
Here is what I see:
```
MediaQuery: Size(0.0, 0.0)
window.physicalSize: Size(0.0, 0.0)
window.physicalSize: Size(0.0, 0.0)
window.physicalSize: Size(0.0, 0.0)
window.physicalSize: Size(1080.0, 2274.0)
MediaQuery: Size(411.4, 866.3)
...
```

2) In debug & profile builds, it gets the correct value immediately. So the bug only happen in `release` build.

<details>
<summary>Code sample</summary>

```dart
import 'dart:async';
import 'dart:ui';

import 'package:flutter/material.dart';

void main() async {
  runApp(const MaterialApp(
    home: _App(),
  ));
}

class _App extends StatefulWidget {
  const _App({Key? key}) : super(key: key);

  @override
  __AppState createState() => __AppState();
}

class __AppState extends State<_App> {
  final _values = <String>[];
  var i = 0;
  late Timer _timer;

  @override
  void initState() {
    super.initState();

    _timer = Timer.periodic(const Duration(milliseconds: 5), (timer) {
      setState(() {
        _values.add('window.physicalSize: ${window.physicalSize}');
      });
      if (++i > 10) {
        timer.cancel();
      }
    });
  }

  @override
  Widget build(BuildContext context) {
    var mediaQuery = MediaQuery.of(context);
    _values.add('MediaQuery: ${mediaQuery.size}');
    return Scaffold(
      appBar: AppBar(
        title: const Text('Demo'),
      ),
      body: ListView(
        children: [for (var v in _values) Text(v)],
      ),
    );
  }

  @override
  void dispose() {
    _timer.cancel();
    super.dispose();
  }
}
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.4, on macOS 11.6.5 20G527 darwin-x64, locale en-BE)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[!] Android Studio
    ✗ Unable to find bundled Java version.
[✓] Android Studio (version 2020.3)
[✓] Android Studio (version 2020.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2022.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2022.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.3)
[✓] VS Code (version 1.63.2)
[✓] Connected device (5 available)
[✓] HTTP Host Availability

! Doctor found issues in 1 category.
```

</details>

Similar report: https://github.com/flutter/flutter/issues/101478. The issue was closed saying to use `MediaQuery.size`. Based on my experimentation is doesn't work either.

It created a bug in the `lottie` library (https://github.com/xvrh/lottie-flutter/issues/216) because it uses the value of `window.devicePixelRatio` during the parsing of the json file at startup.

**Comment by maheshmnj** [comment] 2022-05-03 10:19
Hi @xvrh, Thanks for filing the issue. This seems to be the expected behavior the startup size is expected to be Zero Please see the [docs](https://api.flutter.dev/flutter/dart-ui/FlutterView/physicalSize.html)

> At startup, the size of the view may not be known before Dart code runs. If this value is observed early in the application lifecycle, it may report [Size.zero](https://api.flutter.dev/flutter/dart-ui/Size/zero-constant.html).
  
Closing as this is working as intended. Incase you disagree feel free to write in the comments and we will reopen it.

Thank you.

**Closed by maheshmnj** 2022-05-03 10:19 UTC
Labels: in triage

**Comment by xvrh** [comment] 2022-05-03 11:03
@maheshmnj can we consider this bug as a request to change the behaviour?
I would like that in normal `flutter run`/`runApp` we never observe `Size(0, 0)`.

Furthermore, the behaviour is also incorrect for `window.devicePixelRatio` which is [not documented](https://api.flutter.dev/flutter/dart-ui/FlutterView/devicePixelRatio.html)

From my testing we only have this behaviour on Android `release` build. This can create subtle bugs that are hard to debug.

**Comment by maheshmnj** [comment] 2022-05-04 11:05
@xvrh Can you please check if this helps achieve your use case https://github.com/flutter/flutter/issues/14113#issuecomment-357864964?
