### ISSUE TITLE
video player shows blank snapshot

### ISSUE THREAD

**Issue by arashbi** [flutter/flutter#82876] opened 2021-05-19 01:07 UTC
I have a simple video picker page, when a video is clicked, it shows at the top of the page in a small video player, the issue I am facing is that when switching the videos, often the thumbnail rendered in the video player is blank. This happens on IOS, and I am using a device not emulator.
Beside from blank screen, the other functionality is very good. 
My code looks like this : 

```
import 'dart:io';

import 'package:video_player/video_player.dart';
import 'package:flutter/material.dart';

class VideoPlayerComponent extends StatefulWidget {
  final String path;

  VideoPlayerComponent({Key key, this.path = 'not passed'}) : super(key: key);

  @override
  _VideoPlayerComponentState createState() => _VideoPlayerComponentState();
}

class _VideoPlayerComponentState extends State<VideoPlayerComponent> {
  VideoPlayerController _controller;
  bool _initialized = false;

  @override
  void didUpdateWidget(VideoPlayerComponent oldWidget) {
    super.didUpdateWidget(oldWidget);
    if (oldWidget.path != widget.path) {
      debugPrint('video path is ${widget.path}');
      _initialized = false;
      _createController();
    }
  }

  @override
  void initState() {
    super.initState();
    _createController();
  }

  void _createController() async {
    if (_controller != null) {
      await _controller.dispose();
    }
   
      _controller = VideoPlayerController.file(File(widget.path));
    await _controller.initialize();
    // Ensure the first frame is shown after the video is initialized, even before the play button has been pressed.
    setState(() {
      _initialized = true;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Container(
      child: _initialized
          ? Stack(
              children: [
                Center(
                    child: AspectRatio(
                  aspectRatio: _controller.value.aspectRatio,
                  child: VideoPlayer(_controller),
                )),
                Center(
                  child: !_controller.value.isPlaying
                      ? FloatingActionButton(
                          backgroundColor: Colors.white38,
                          onPressed: () {
                            _controller.value.isPlaying
                                ? _controller.pause()
                                : _controller.play();
                            setState(() {});
                          },
                          child: Icon(
                            _controller.value.isPlaying
                                ? Icons.pause
                                : Icons.play_arrow,
                            color: AppColors.floatingActionButton_iconColor,
                          ),
                        )
                      : GestureDetector(
                          onTap: () {
                            _controller.pause();
                            setState(() {});
                          },
                          child: Container(
                            color: Colors.transparent,
                            width: 100,
                            height: 100,
                          ),
                        ),
                )
              ],
            )
          : Waiting(),
    );
  }

  @override
  void dispose() {
    super.dispose();
    _controller.dispose();
  }
}
```

flutter doctor output 
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.3, on macOS 11.3 20E232 darwin-x64, locale en-CA)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.1.1)
[✓] VS Code (version 1.56.2)
[✓] Connected device (3 available)
```

**Comment by darshankawar** [comment] 2021-05-19 11:03
@arashbi 
Tried your code sample which seems to be giving me compile error on `Waiting()` method:

<img width="672" alt="Screenshot 2021-05-19 at 4 30 46 PM" src="https://user-images.githubusercontent.com/67046386/118802615-f397ac80-b8bf-11eb-8f8f-81ab7821724d.png">

Can you provide the missing code ?

Thanks.

**Comment by arashbi** [comment] 2021-05-19 12:55
```

class Waiting extends StatelessWidget {
  const Waiting();
  @override
  Widget build(BuildContext context) {
    return Center(child: CircularProgressIndicator(valueColor: AlwaysStoppedAnimation(AppColors.waiting)));
  }
}
```

**Comment by darshankawar** [comment] 2021-05-19 13:46
I get a blank screen with loading indicator. Is this an actual issue you described ?
If so, what's the expected behavior are you looking for from your code ?

**Comment by arashbi** [comment] 2021-05-19 19:47
Not really. this is what I see. When I click a video, it is white, click again it shows the thumbnail, even if I press hot-reload it shows,  and also it just plays fine.


https://user-images.githubusercontent.com/445845/118875015-8e40bd00-b8b9-11eb-86e7-9c0e5e5373a4.mp4

**Comment by darshankawar** [comment] 2021-05-20 06:41
Running your full code on latest stable (2.2.0) is giving me below error and shows blank loading screen as mentioned earlier:

```
VERBOSE-2:ui_dart_state.cc(199)] Unhandled Exception: LateInitializationError: Field '_controller@549475816' has not been initialized.
#0      _VideoPlayerComponentState._controller (package:macbug/main.dart)
#1      _VideoPlayerComponentState._createController (package:macbug/main.dart:40:9)
#2      _VideoPlayerComponentState.initState (package:macbug/main.dart:36:5)
#3      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4711:57)
#4      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4548:5)
#5      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3611:14)
#6      Element.updateChild (package:flutter/src/widgets/framework.dart:3363:18)
#7      RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1189:16)
#8      RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:1159:5)
#9      RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:1104:18)
#10     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2535:19)
#11     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:1103:13)
#12     WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:937:7)
#13     WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:917:7)
#14     _rootRun (dart:async/zone.dart:1346:47)
#15     _CustomZone.run (dart:async/zone.dart:1258:19)
#16     _CustomZone.runGuarded (dart:async/zone.dart:1162:7)
#17     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1202:23)
#18     _rootRun (dart:async/zone.dart:1354:13)
#19     _CustomZone.run (dart:async/zone.dart:1258:19)
#20     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1186:23)
#21     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
#22     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:395:19)
#23     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:426:5)
#24     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)

```

<details>
<summary> flutter doctor -v </summary>

```
[✓] Flutter (Channel stable, 2.2.0, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.2.0 at /Users/dhs/documents/fluttersdk/flutter
    • Framework revision b22742018b (5 days ago), 2021-05-14 19:12:57 -0700
    • Engine revision a9d88a4d18
    • Dart version 2.13.0

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (3 available)
    • Darshan's iphone (mobile) • 21150b119064aecc249dfcfe05e259197461ce23 • ios
      • iOS 14.4.1
    • macOS (desktop)           • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)              • chrome                                   •
      web-javascript • Google Chrome 90.0.4430.212

! Doctor found issues in 1 category.


```

</details>

**Comment by TahaTesser** [comment] 2021-06-11 12:05
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by TahaTesser** 2021-06-11 12:05 UTC
