### ISSUE TITLE
FlutterViewController Could not launch engine with configuration. 

### ISSUE THREAD

**Issue by yathit** [flutter/flutter#20146] opened 2018-08-02 14:24 UTC
After the update `open_file` plugin does not work in iOS with the following message:

```
Syncing files to device iPhone 7 Plus...
[VERBOSE-2:engine.cc(157)] Could not prepare to run the isolate.
[VERBOSE-2:engine.cc(116)] Engine not prepare and launch isolate.
[VERBOSE-2:FlutterViewController.mm(407)] Could not launch engine with configuration.
```

To reproduce the issue, clone the project 

1. https://github.com/yathit/open_file 
2. go to example folder and
3. run the app

**Comment by yathit** [comment] 2018-08-02 14:31
```
Upgrading Flutter from /Users/kyawtun/flutter...
Already up to date.

Upgrading engine...
Already up-to-date.

Flutter 0.5.8-pre.216 • channel master • https://github.com/flutter/flutter.git
Framework • revision b280074815 (2 hours ago) • 2018-08-02 14:12:25 +0200
Engine • revision a76054f4b6
Tools • Dart 2.0.0-dev.69.5.flutter-8bad5c7b29

Running "flutter packages upgrade" in example...            13.4s

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v0.5.8-pre.216, on Mac OS X 10.13.6 17G65, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
[✓] Android Studio (version 3.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] IntelliJ IDEA Ultimate Edition (version 2018.2)
[!] VS Code (version 1.21.0)
[✓] Connected devices (2 available)

! Doctor found issues in 1 category.
```

**Comment by dresserm** [comment] 2018-09-09 22:41
I'm getting the same error message, with:
[VERBOSE-2:engine.cc(158)] Could not prepare to run the isolate.
[VERBOSE-2:engine.cc(117)] Engine not prepare and launch isolate.
[VERBOSE-2:FlutterViewController.mm(411)] Could not launch engine with configuration.

This happens when I return to my app from a web page by hitting "Done", after getting to the web page by using url_launcher (3.0.3).  The app seems to continue to run without issues.


[✓] Flutter (Channel beta, v0.7.3, on Mac OS X 10.13.6 17G65, locale en-US)
    • Flutter version 0.7.3 at /Users/dresserm/Work/flutter
    • Framework revision 3b309bda07 (12 days ago), 2018-08-28 12:39:24 -0700
    • Engine revision af42b6dc95
    • Dart version 2.1.0-dev.1.0.flutter-ccb16f7282

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/dresserm/Library/Android/sdk
    • Android NDK at /Users/dresserm/Library/Android/sdk/ndk-bundle
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = /Users/dresserm/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.2

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 22.2.1
    • Dart plugin version 171.4424
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] IntelliJ IDEA Community Edition (version 2017.3.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 21.2.3
    • Dart plugin version 173.4548.30

[✓] IntelliJ IDEA Ultimate Edition (version 2017.3.3 EAP)
    • IntelliJ at /Users/dresserm/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 28.0.1
    • Dart plugin version 173.4700

[✓] Connected devices (1 available)
    • iPhone X • 50357B30-5A17-4CC5-BF6B-CF635B204ADD • ios • iOS 11.4 (simulator)

• No issues found!

Hope this helps.

**Comment by dresserm** [comment] 2018-09-10 20:57
Also, this happens on Android and iOS, device and emulator.  I don't have this problem with the flutter_view example, and the flutter_assets subdirectory for the offending project is accessible and appears ~correct by comparison with the subdirectory generated by the flutter_view example.

**Comment by Nik99** [comment] 2018-09-18 06:41
It's happening to me too.

**Comment by dnfield** [comment] 2018-09-21 05:17
Able to reproduce this - after opening the file and returing to the app, the engine seems to not be able to restart the isolate.

That said, I'm wondering how serious it is.  The application continues to run and respond normally as far as I can tell after those logs are printed.  @yathit, are you seeing something different? After the log messages are printed, is your application not functioning properly?

**Comment by dnfield** [comment] 2018-09-21 05:18
Also, I've slightly extended the example `main.dart` to make it easier to reproduce/test this here: https://github.com/dnfield/open_file/tree/master/example/lib/main.dart

**Comment by dnfield** [comment] 2018-09-21 16:36
(And in case it wasn't clear, we should definitely fix this.  Just trying to get a sense of priority as to whether this is actually impacting functionality.)

**Comment by dresserm** [comment] 2018-09-21 16:43
I've upgraded to the most recent beta version and I still see the error message.  In terms of priority, as far as I can tell, this has no impact on the functioning of my app.  If it becomes more urgent for me, I'll shout louder.

**Comment by jogboms** [comment] 2018-09-22 07:38
Oh my goodness @dnfield, it really is, i can't move forward with the app i'm working on because it depends on the image_picker plugin. If i can, i will shout, top priority for me seeing i've told the client "Be patient, The flutter guys are fixing it".

**Comment by yathit** [comment] 2018-09-22 11:45
@dnfield I have disable the functionality in ios app.

**Comment by dnfield** [comment] 2018-09-22 14:36
@jogboms is this error preventing your app from functioning?  If so can you share a repro for that?

The issue here only logs error messages, the app continues to work fine.

**Comment by jogboms** [comment] 2018-09-22 20:18
Well @dnfield, the thing is that doesn't indeed break the app, the `image_picker` plugin simply doesn't work at this very moment. 😥

**Comment by dnfield** [comment] 2018-09-22 20:39
Can you open a separate issue for image picker not working?

**Comment by jogboms** [comment] 2018-09-22 23:29
@dnfield 

#21516 #21221

**Comment by dnfield** [comment] 2018-09-24 03:11
Closing this as a duplicate of #21221.

In this particular case, the `FlutterViewController` is trying to run the already-running isolate.  I don't think this should cause any serious problems, but it looks like some related path might be causing problems in the duplicate issue.  Let's just use that one to track.

**Closed by dnfield** 2018-09-24 03:11 UTC
Labels: a: existing-apps, engine, severe: crash, ⌺‬ platform-ios
