### ISSUE TITLE
Implement GraphQL client

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [flutter/flutter#85681] opened 2021-07-01 05:40 UTC
Hi, 
I know I have already wrote similar but this really makes me concerned.

Graphql is very high end way to develop multiplatform apps. This perfectly fits flutter vision (usually web requires more data than mobile). However flutter lacks graphql client.

Theres is a library called flutter_graphql (the only graphql client lib) but it has no active maintainer. I know you will say that community will pick it up, but reality is different - when there is no active maintainer bugs are not getting fixed. Changes are not being made at all and most disappointing thing that some members starting to use their own forks which never gets merged because there is no one who can approve PR (for example this guy works on a websocket disconnection fix on his fork: https://github.com/zino-app/graphql-flutter/issues/892)

I wrote to Apollo team asking do they want to maintain flutter client and their answer was - no.

Again, repo without active maintainer is dead same like .net core is open source and every one can commit to it but without MS behind it would die.

So asking you guys again - would you mind to think of taking ownership?

Thanks.

**Comment by TahaTesser** [comment] 2021-07-01 12:49
HI @vytautas-pranskunas- 
I don't think transferring ownership of third-party is feasible, this is already answered https://github.com/flutter/flutter/issues/83667#issuecomment-851709608
Closing as duplicate of https://github.com/flutter/flutter/issues/83667

**Closed by TahaTesser** 2021-07-01 12:49 UTC
Labels: in triage

**Comment by vytautas-pranskunas-** [comment] 2021-07-01 20:50
So maybe you are thinking of creating your one?
