### ISSUE TITLE
Crash in Dart VM JIT compiler while building Flutter engine

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#143223] opened 2024-02-09 16:54 UTC
In Dart version 3.4.0-116.0.dev

https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8756596836915641345/+/u/build_host_debug_unopt/stdout?format=raw

Those logs contain a native backtrace from the crash and the flow graph that the JIT compiler was working on at the time.

**Comment by aam** [comment] 2024-02-20 19:02
This crash we saw only once, correct?
I think I tried reproducing it locally, but unsuccessfully.

**Comment by aam** [comment] 2024-02-21 16:33
Closing until we get some way of reproducing the failure, it happens again.

**Closed by aam** 2024-02-21 16:33 UTC
Labels: dependency: dart, P1, team-engine, triaged-engine

**Comment by aam** [comment] 2024-02-21 18:29
Just for the record, it looks like this bot had [similarly looking dart crash](https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8757572395317193345/+/u/build_host_debug_unopt/stdout) few weeks before that one on a different test. No flow graph, but same frontend_server run failure.
```
[6066/6542] ACTION //flutter/testing/dart:compile_canvas_test.dart(//build/toolchain/mac:clang_x64)
FAILED: gen/canvas_test.dart.dill 
vpython3 ../../build/gn_run_binary.py ../../flutter/prebuilts/macos-x64/dart-sdk/bin/dart --disable-dart-dev /Volumes/Work/s/w/ir/cache/builder/src/out/host_debug_unopt/gen/frontend_server.dart.snapshot -DkFlutterSrcDirectory=/Volumes/Work/s/w/ir/cache/builder/src/flutter -DkFlutterBuildDirectory=/Volumes/Work/s/w/ir/cache/builder/src/out/host_debug_unopt/gen -DkSkiaGoldWorkDirectory=/Volumes/Work/s/w/ir/cache/builder/src/out/host_debug_unopt/gen/skia_gold_canvas_test.dart --packages ../../flutter/testing/dart/.dart_tool/package_config.json --sdk-root flutter_patched_sdk --target=flutter --depfile gen/canvas_test.dart.dill.d --output-dill gen/canvas_test.dart.dill ../../flutter/testing/dart/canvas_test.dart
result 8a951650-0e9d-4ec8-937f-e4234fc92948

===== CRASH =====
si_signo=Segmentation fault: 11(11), si_code=SEGV_MAPERR(1), si_addr=0x11df00000
version=3.4.0-82.0.dev (dev) (Sat Jan 27 00:03:42 2024 -0800) on "macos_x64"
pid=71319, thread=11011, isolate_group=main(0x7faa21009a00), isolate=(nil)(0x0)
os=macos, arch=x64, comp=no, sim=no
isolate_instructions=1109d0000, vm_instructions=10c02a6a0
fp=70000465bc60, sp=70000465bc20, pc=10c30af19
  pc 0x000000010c30af19 fp 0x000070000465bc60 /Volumes/Work/s/w/ir/cache/builder/src/flutter/prebuilts/macos-x64/dart-sdk/bin/dart+0x32ef19
  pc 0x000000010c264c46 fp 0x000070000465bc90 /Volumes/Work/s/w/ir/cache/builder/src/flutter/prebuilts/macos-x64/dart-sdk/bin/dart+0x288c46
  pc 0x000000010c307820 fp 0x000070000465bd00 /Volumes/Work/s/w/ir/cache/builder/src/flutter/prebuilts/macos-x64/dart-sdk/bin/dart+0x32b820
  pc 0x000000010c305b50 fp 0x000070000465bdf0 /Volumes/Work/s/w/ir/cache/builder/src/flutter/prebuilts/macos-x64/dart-sdk/bin/dart+0x329b50
  pc 0x000000010c304a2e fp 0x000070000465be70 /Volumes/Work/s/w/ir/cache/builder/src/flutter/prebuilts/macos-x64/dart-sdk/bin/dart+0x328a2e
  pc 0x000000010c305903 fp 0x000070000465bea0 /Volumes/Work/s/w/ir/cache/builder/src/flutter/prebuilts/macos-x64/dart-sdk/bin/dart+0x329903
  pc 0x000000010c2d11c7 fp 0x000070000465bf20 /Volumes/Work/s/w/ir/cache/builder/src/flutter/prebuilts/macos-x64/dart-sdk/bin/dart+0x2f51c7
  pc 0x000000010c2d1453 fp 0x000070000465bf50 /Volumes/Work/s/w/ir/cache/builder/src/flutter/prebuilts/macos-x64/dart-sdk/bin/dart+0x2f5453
  pc 0x000000010c250c2e fp 0x000070000465bfb0 /Volumes/Work/s/w/ir/cache/builder/src/flutter/prebuilts/macos-x64/dart-sdk/bin/dart+0x274c2e
  pc 0x00007ff806d921d3 fp 0x000070000465bfd0 _pthread_start+0x7d
  pc 0x00007ff806d8dbd3 fp 0x000070000465bff0 thread_start+0xf
-- End of DumpStackTrace
```
