### ISSUE TITLE
Android - Platform View Error - Surface has already been released - Flutter 3.24.1

### ISSUE THREAD

**Issue by walt-etermax** [flutter/flutter#156220] opened 2024-10-04 12:55 UTC
### Steps to reproduce

Hello. We are experiencing a new crash on our app after upgrading to Flutter 3.24.1.

It happens on our Android app. Seems to be related with the display of our PlatformViews. Sadly, we can't reproduce the issue on our end.

### Expected results

The application not to crash when trying to show a Platform View

### Actual results

The application crashing when trying to show a Platform View

### Code sample

We do not have a small sample code to reproduce this issue.

### Logs

<details open><summary>Logs</summary>

```console
java.lang.IllegalStateException: Surface has already been released.
        at android.view.Surface.checkNotReleasedLocked(Surface.java:785)
        at android.view.Surface.lockHardwareCanvas(Surface.java:535)
        at io.flutter.plugin.platform.PlatformViewWrapper.draw(PlatformViewWrapper:169)
        at android.view.View.updateDisplayListIfDirty(View.java:22297)
        at android.view.View.draw(View.java:23174)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4615)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4368)
        at android.view.View.updateDisplayListIfDirty(View.java:22288)
        at android.view.View.draw(View.java:23174)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4615)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4368)
        at android.view.View.updateDisplayListIfDirty(View.java:22288)
        at android.view.View.draw(View.java:23174)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4615)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4368)
        at android.view.View.updateDisplayListIfDirty(View.java:22288)
        at android.view.View.draw(View.java:23174)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4615)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4368)
        at android.view.View.updateDisplayListIfDirty(View.java:22288)
        at android.view.View.draw(View.java:23174)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4615)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4368)
        at android.view.View.updateDisplayListIfDirty(View.java:22288)
        at android.view.View.draw(View.java:23174)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4615)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4368)
        at android.view.View.updateDisplayListIfDirty(View.java:22288)
        at android.view.View.draw(View.java:23174)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4615)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4368)
        at com.android.internal.policy.DecorView.dispatchDraw(DecorView.java:2992)
        at android.view.View.draw(View.java:23469)
        at com.android.internal.policy.DecorView.draw(DecorView.java:896)
        at android.view.View.updateDisplayListIfDirty(View.java:22297)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:682)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:688)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:790)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:4897)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4588)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3774)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2474)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9482)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1412)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1420)
        at android.view.Choreographer.doCallbacks(Choreographer.java:1047)
        at android.view.ChoreographerExtImpl.checkScrollOptSceneEnable(ChoreographerExtImpl.java:450)
        at android.view.Choreographer.doFrame(Choreographer.java:918)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1395)
        at android.os.Handler.handleCallback(Handler.java:942)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:240)
        at android.os.Looper.loop(Looper.java:351)
        at android.app.ActivityThread.main(ActivityThread.java:8370)
        at java.lang.reflect.Method.invoke(Method.java:-2)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:568)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[!] Flutter (Channel [user-branch], 3.24.1, on macOS 14.5 23F79 darwin-arm64, locale es-AR)
    ! Flutter version 3.24.1 on channel [user-branch] at /Users/XXXX/XXXX/flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at https://flutter.dev/setup.
    ! Upstream repository unknown source is not a standard remote.
      Set environment variable "FLUTTER_GIT_URL" to unknown source to dismiss this error.
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.1)
[✓] VS Code (version 1.93.1)
[✓] Connected device (4 available)
[✓] Network resources
```

</details>

**Comment by darshankawar** [comment] 2024-10-04 13:10
Closing as duplicate of https://github.com/flutter/flutter/issues/155018. It is fixed per https://github.com/flutter/flutter/issues/155018#issuecomment-2377635744.

**Closed by darshankawar** 2024-10-04 13:10 UTC
Labels: in triage
