### ISSUE TITLE
CupertinoSliverRefreshControl blinks sometimes when Container is returned from builder

### ISSUE THREAD

**Issue by vanelizarov** [flutter/flutter#26884] opened 2019-01-22 11:28 UTC
## Steps to Reproduce

In my app I need to provide pull-to-refresh functionality on one of the screens. 
I've chosen `CupertinoSliverRefreshControl`. App's primary color is red, so the navbar, refresh control & searchbar need to be colored with it. 
When I return `Container` with color from `CupertinoSliverRefreshControl`'s method, the whole control kind-of blinks with white stripe, when reaches the zero position after onRefresh completes.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/5096148/51532627-a9b66d00-1e51-11e9-8825-0c87e5b32f22.gif)

Piece of code, where this problem occurs:

```dart
import 'package:flutter/cupertino.dart';

void main() {
  runApp(App());
}

class App extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return CupertinoApp(
      home: CupertinoPageScaffold(
        child: CustomScrollView(
          slivers: <Widget>[
            /// navbar
            CupertinoSliverNavigationBar(
              backgroundColor: Color(0xffe30613),
              largeTitle: Text(
                'App',
                style: TextStyle(
                  color: Color(0xffffffff),
                ),
              ),
            ),

            /// pull to refresh control
            CupertinoSliverRefreshControl(
              onRefresh: () => Future.delayed(Duration(milliseconds: 1000)),
              builder: (_, __, ___, ____, _____) {
                return Container(
                  color: Color(0xffe30613),
                  child: Center(
                    child: const CupertinoActivityIndicator(
                      radius: 12.0,
                    ),
                  ),
                );
              },
            ),

            /// searchbar
            SliverToBoxAdapter(
              child: Container(
                height: 56.0,
                padding: const EdgeInsets.symmetric(
                  horizontal: 8.0,
                  vertical: 10.0,
                ),
                color: Color(0xffe30613),
                child: Container(
                  color: Color(0xffffffff),
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}

```

## Output from flutter doctor

```
[✓] Flutter (Channel dev, v1.1.9, on Mac OS X 10.14.3 18D32a, locale en-RU)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.2)
[✓] VS Code (version 1.30.2)
[✓] Connected device (1 available)

• No issues found!
```

**Comment by zoechi** [comment] 2019-01-22 11:47
Can you please make the code a complete runnable reproduction so that copy-past int `lib/main.dart` is enough to reproduce.

**Comment by vanelizarov** [comment] 2019-01-22 12:01
@zoechi okay, give me a minute

**Comment by vanelizarov** [comment] 2019-01-22 12:07
> Can you please make the code a complete runnable reproduction so that copy-past int `lib/main.dart` is enough to reproduce.

Done.

**Comment by wouterhardeman** [comment] 2019-01-22 16:49
This is because the `refreshState` is set to `RefreshIndicatorMode.inactive` when the extent reaches 10% of the `refreshTriggerPullDistance` property. ([relevant code](https://github.com/flutter/flutter/blob/af0758e67d8f038383bba2af11ae5c9a0ed40c94/packages/flutter/lib/src/cupertino/refresh.dart#L500)) Once`refreshState` is set to inactive, an empty `Container` will be rendered. That is what you see in that split second.

There are multiple ways to fix this:
* Wrap the `CustomScrollView` in a `Container` with a background. Render the other content in a `Container` with the preferred background

Fixes that requires changes to the framework:
* Let the developers render the `inactive` state themselves. This could cause regression issues with developers that don't cover this themselves.
* Add an optional parameter to the `CupertinoSliverRefreshControl` that sets the background color on the empty `Container`.
* Remove the `_inactiveResetOverscrollFraction`. Not a good option because it was purposely added:
```
        // Let the transition back to inactive trigger before strictly going
        // to 0.0 since the last bit of the animation can take some time and
        // can feel sluggish if not going all the way back to 0.0 prevented
        // a subsequent pull-to-refresh from starting.
```

**Comment by VladyslavBondarenko** [comment] 2020-04-03 12:57
Closing as fixed.
@vanelizarov please comment if it's not so and I will reopen it
Thank you

**Closed by VladyslavBondarenko** 2020-04-03 12:57 UTC
Labels: f: scrolling, framework
