### ISSUE TITLE
[web]: compile issue when importing file from dependency package (build_runner?)

### ISSUE THREAD

**Issue by deckerst** [flutter/flutter#42218] opened 2019-10-08 09:00 UTC
Given a flutter package and a flutter web app that depends on it, I get a compilation error when the web app imports specific files from the dependency package.

Here's a repro (with the common package and the web app):
https://github.com/deckerst/flutter_web_compile_issue

Here's the compilation issue:
```
Building application for the web...
Unhandled exception:
NoSuchMethodError: The getter 'name' was called on null.
Receiver: null
Tried calling: name
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      _packageBuildConfig.<anonymous closure> (package:build_runner_core/src/package_graph/target_graph.dart:85:61)
#2      MappedListIterable.elementAt (dart:_internal/iterable.dart:415:29)
#3      ListIterable.toList (dart:_internal/iterable.dart:219:19)
#4      new BuildConfig.useDefault (package:build_config/src/build_config.dart:90:34)
#5      BuildConfig.fromBuildConfigDir (package:build_config/src/build_config.dart:52:26)
<asynchronous suspension>
#6      _packageBuildConfig (package:build_runner_core/src/package_graph/target_graph.dart:90:30)
<asynchronous suspension>
#7      TargetGraph.forPackageGraph (package:build_runner_core/src/package_graph/target_graph.dart:37:17)
<asynchronous suspension>
#8      BuildOptions.create (package:build_runner_core/src/generate/options.dart:168:39)
<asynchronous suspension>
#9      BuildRunnerDaemonBuilder.create (package:build_runner/src/daemon/daemon_builder.dart:195:43)
<asynchronous suspension>
#10     DaemonCommand.run (package:build_runner/src/entrypoint/daemon.dart:83:48)
<asynchronous suspension>
#11     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
<asynchronous suspension>
#12     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#13     new Future.sync (dart:async/future.dart:224:31)
#14     CommandRunner.run (package:args/command_runner.dart:112:14)
#15     run (package:build_runner/src/entrypoint/run.dart:24:31)
<asynchronous suspension>
#16     main (package:flutter_tools/src/build_runner/build_script.dart:196:28)
<asynchronous suspension>
#17     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:32)
#18     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
Finished with error: Failed to build application for the web.
```

It seems it is linked to `build_runner`, which is a dependency in the common package necessary to work with `json_serializable`. I'm not sure whether it's actually a problem with `build_runner` or with flutter web.

flutter doctor -v
```
[✓] Flutter (Channel dev, v1.10.13, on Mac OS X 10.14.6 18G95, locale en-KR)
    • Flutter version 1.10.13 at /Users/thibaultdeckers/projects/flutter
    • Framework revision 97e00b2288 (18 hours ago), 2019-10-07 08:11:45 -0700
    • Engine revision 7d90779bb6
    • Dart version 2.6.0 (build 2.6.0-dev.0.0 d6c6d12ebf)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/thibaultdeckers/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Users/thibaultdeckers/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/191.5900203/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    • CocoaPods version 1.6.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Users/thibaultdeckers/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/191.5900203/Android Studio.app/Contents
    • Flutter plugin version 40.0.2
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.38.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.5.1

[✓] Connected device (4 available)
    • SM G970N        • R39M4001Z1M                          • android-arm64  • Android 9 (API 28)
    • iPhone 11       • 75CFC2E6-18BA-4EA3-AC14-4E55B77A0C58 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-1
      (simulator)
    • Chrome          • chrome                               • web-javascript • Google Chrome 77.0.3865.90
    • Headless Server • headless-server                      • web-javascript • Flutter Tools

• No issues found!
```

**Comment by yjbanov** [comment] 2019-10-10 23:03
This looks like a duplicate of https://github.com/flutter/flutter/issues/42218

**Closed by yjbanov** 2019-10-10 23:03 UTC
Labels: customer: webeap, ☸ platform-web
