### ISSUE TITLE
Firestore feature like array-contains-any in JS

### ISSUE THREAD

**Issue by SaminYaser** [flutter/flutter#45005] opened 2019-11-15 20:52 UTC
In my app, I need to search if there's a matching document that has an array containing any of the elements of another array.
"array-contains-any" is like "IN" in flirestore.

**Comment by casvanluijtelaar** [comment] 2019-11-17 12:19
same, I'm waiting for an update to the firestore plugin

**Comment by iapicca** [comment] 2019-11-18 09:19
Hi @SaminYaser 
for what I can see the issue is related to a FlutterFire plugin,
please open the issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
thank you

**Closed by iapicca** 2019-11-18 09:19 UTC
