### ISSUE TITLE
Error when using ThemeData

### ISSUE THREAD

**Issue by AndreHaueisen** [flutter/flutter#16764] opened 2018-04-19 21:00 UTC
## Steps to Reproduce

The error started after adding ThemeData to the MaterialApp.

```dart
void main() {
  //debugPaintSizeEnabled = true;
  runApp(new MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final starredItem = new BottomNavigationBarItem(
        icon: new Icon(Icons.star), title: new Text("Starred"));
    final searchItem = new BottomNavigationBarItem(
        icon: new Icon(Icons.search), title: new Text("Search"));
    final bookmarksItem = new BottomNavigationBarItem(
        icon: new Icon(Icons.collections_bookmark),
        title: new Text("Bookmarks"));
    final myBooksItem = new BottomNavigationBarItem(
        icon: new Icon(Icons.library_books), title: new Text("My Books"));
    final profileItem = new BottomNavigationBarItem(
        icon: new Icon(Icons.person), title: new Text("Profile"));

    final bottomNavigationItems = [
      starredItem,
      searchItem,
      bookmarksItem,
      myBooksItem,
      profileItem
    ];

    return new MaterialApp(
      theme: new ThemeData(
        primaryColor: Colors.black45,
        primaryColorDark: Colors.black,
        primaryColorLight: Colors.black26,
        accentColor: Colors.amberAccent
      ),
      title: 'Flutter Demo',
      home: new Scaffold(
        appBar: new AppBar(title: new Text('Cronicalia'),),
        body: new Column(
          children: <Widget>[
            new Expanded(
                child: new ListView(
                  children: [
                    new Image.asset(
                  'images/lake.jpg',
                  width: 600.0,
                  height: 240.0,
                  fit: BoxFit.cover,
                ),
              ],
            )),
          ],
        ),
        bottomNavigationBar: new BottomNavigationBar(
          onTap: (int index) {},
          items: bottomNavigationItems,
          fixedColor: Colors.black45,
          currentIndex: 0,
        ),
      ),
    );
  }
}

```

## Logs
```
I/flutter (25870): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (25870): The following assertion was thrown building WidgetsApp-[GlobalObjectKey
I/flutter (25870): _MaterialAppState#a2348](dirty, state: _WidgetsAppState#5c897):
I/flutter (25870): 'package:flutter/src/widgets/title.dart': Failed assertion: line 24 pos 15: 'color != null &&
I/flutter (25870): color.alpha == 0xFF': is not true.
I/flutter (25870): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (25870): more information in this error message to help you determine and fix the underlying cause.
I/flutter (25870): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (25870):   https://github.com/flutter/flutter/issues/new
I/flutter (25870): When the exception was thrown, this was the stack:
I/flutter (25870): #2      new Title (package:flutter/src/widgets/title.dart)
I/flutter (25870): #3      _WidgetsAppState.build (package:flutter/src/widgets/app.dart:618:19)
I/flutter (25870): #4      StatefulElement.build (package:flutter/src/widgets/framework.dart:3713:27)
I/flutter (25870): #5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3625:15)
I/flutter (25870): #6      Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter (25870): #7      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
I/flutter (25870): #8      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3752:11)
I/flutter (25870): #9      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
I/flutter (25870): #10     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter (25870): #11     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
I/flutter (25870): #12     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter (25870): #13     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter (25870): #14     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
I/flutter (25870): #15     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
I/flutter (25870): #16     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter (25870): #17     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
I/flutter (25870): #18     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter (25870): #19     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter (25870): #20     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
I/flutter (25870): #21     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
I/flutter (25870): #22     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter (25870): #23     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
I/flutter (25870): #24     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter (25870): #25     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter (25870): #26     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
I/flutter (25870): #27     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
I/flutter (25870): #28     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter (25870): #29     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
I/flutter (25870): #30     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter (25870): #31     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter (25870): #32     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
I/flutter (25870): #33     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3752:11)
I/flutter (25870): #34     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
I/flutter (25870): #35     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter (25870): #36     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
I/flutter (25870): #37     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter (25870): #38     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter (25870): #39     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
I/flutter (25870): #40     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
I/flutter (25870): #41     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter (25870): #42     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
I/flutter (25870): #43     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter (25870): #44     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter (25870): #45     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
I/flutter (25870): #46     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3752:11)
I/flutter (25870): #47     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
I/flutter (25870): #48     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter (25870): #49     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
I/flutter (25870): #50     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter (25870): #51     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter (25870): #52     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
I/flutter (25870): #53     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
I/flutter (25870): #54     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter (25870): #55     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
I/flutter (25870): #56     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:852:16)
I/flutter (25870): #57     RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:823:5)
I/flutter (25870): #58     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:769:17)
I/flutter (25870): #59     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2205:19)
I/flutter (25870): #60     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:768:13)
I/flutter (25870): #61     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:657:7)
I/flutter (25870): #62     runApp (package:flutter/src/widgets/binding.dart:699:7)
I/flutter (25870): #63     main (file:///C:/Users/andre/Desktop/Flutter/flutter_app/lib/main.dart:12:3)
I/flutter (25870): #64     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:279:19)
I/flutter (25870): #65     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
I/flutter (25870): (elided 2 frames from class _AssertionError)
I/flutter (25870): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

## Flutter Doctor
```
[√] Flutter (Channel beta, v0.2.8, on Microsoft Windows [Version 10.0.16299.371], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[√] Android Studio (version 3.1)
[√] Connected devices (1 available)

• No issues found!
```
> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

**Comment by AndreHaueisen** [comment] 2018-04-19 21:56
I found the issue. The shades of blacks I was using have transparency (Colors.black45 and Colors.black26).
I think this is misleading. Maybe you could consider using a name like Colors.tranparentBlack45. I was getting a lot of strange shades when using black and now I know why.

**Comment by rami-a** [comment] 2019-03-27 19:50
I ran into this issue as well before. The documentation in `title.dart` explains that the color needs to be opaque since it is used by the Android operating system. And drilling into the implementation of colors like `Colors.black45` shows that they have transparency. Renaming those colors would be a breaking change and wouldn't necessarily provide enough value to warrant breaking, so for now, we'll leave it as-is.

I'm going to close this issue, as it is behaving as expected.

**Closed by rami-a** 2019-03-27 19:50 UTC
Labels: d: api docs, f: material design, framework, severe: crash

**Comment by atilkan** [comment] 2019-09-08 18:14
@rami-a At least make it throw something we can understand.

**Comment by kw2019ltd** [comment] 2020-05-21 09:56
Non-fatal Exception: java.lang.Exception: 'package:flutter/src/widgets/title.dart': Failed assertion: line 24 pos 15: 'color != null && color.alpha == 0xFF': is not true.
       at .new(title.dart:24)
       at _WidgetsAppState.build(app.dart:1381)
       at StatefulElement.build(framework.dart:4619)
       at ComponentElement.performRebuild(framework.dart:4502)
       at StatefulElement.performRebuild(framework.dart:4675)
       at Element.rebuild(framework.dart:4218)
       at ComponentElement._firstBuild(framework.dart:4481)
       at StatefulElement._firstBuild(framework.dart:4666)
       at ComponentElement.mount(framework.dart:4476)
       at Element.inflateWidget(framework.dart:3446)
       at Element.updateChild(framework.dart:3214)
       at ComponentElement.performRebuild(framework.dart:4527)
       at Element.rebuild(framework.dart:4218)
       at ComponentElement._firstBuild(framework.dart:4481)
       at ComponentElement.mount(framework.dart:4476)
       at Element.inflateWidget(framework.dart:3446)
       at Element.updateChild(framework.dart:3214)
       at ComponentElement.performRebuild(framework.dart:4527)
       at StatefulElement.performRebuild(framework.dart:4675)
       at Element.rebuild(framework.dart:4218)
       at ComponentElement._firstBuild(framework.dart:4481)
       at StatefulElement._firstBuild(framework.dart:4666)
       at ComponentElement.mount(framework.dart:4476)
       at Element.inflateWidget(framework.dart:3446)
       at Element.updateChild(framework.dart:3214)
       at ComponentElement.performRebuild(framework.dart:4527)
       at StatefulElement.performRebuild(framework.dart:4675)
       at Element.rebuild(framework.dart:4218)
       at ComponentElement._firstBuild(framework.dart:4481)
       at StatefulElement._firstBuild(framework.dart:4666)
       at ComponentElement.mount(framework.dart:4476)
       at Element.inflateWidget(framework.dart:3446)
       at Element.updateChild(framework.dart:3214)
       at ComponentElement.performRebuild(framework.dart:4527)
       at StatefulElement.performRebuild(framework.dart:4675)
       at Element.rebuild(framework.dart:4218)
       at ComponentElement._firstBuild(framework.dart:4481)
       at StatefulElement._firstBuild(framework.dart:4666)
       at ComponentElement.mount(framework.dart:4476)
       at Element.inflateWidget(framework.dart:3446)
       at Element.updateChild(framework.dart:3214)
       at RenderObjectToWidgetElement._rebuild(binding.dart:1148)
       at RenderObjectToWidgetElement.mount(binding.dart:1119)
       at RenderObjectToWidgetAdapter.attachToRenderTree.<fn>(binding.dart:1061)
       at BuildOwner.buildScope(framework.dart:2607)
       at RenderObjectToWidgetAdapter.attachToRenderTree(binding.dart:1060)
       at WidgetsBinding.attachRootWidget(binding.dart:941)
       at WidgetsBinding.scheduleAttachRootWidget.<fn>(binding.dart:922)

**Comment by moritzmorgenroth** [comment] 2020-07-31 07:58
I ran into the same issue when using `ThemeData.from()` without explicitly specifying a `primaryColor` via `copyWith`. Is this also expected behavior? It feels lie a bug in the `ThemeData.from()`. 
``` ThemeData appTheme =
    ThemeData.from(colorScheme: colorScheme, textTheme: textTheme).copyWith(
         //  primaryColor: generateMaterialColor(colorScheme.primary), // uncomment this line to solve the issue 
);
``` 
This is happening on flutter stable.
