### ISSUE TITLE
[firebase_admob] AdView not destroy on page navigation

### ISSUE THREAD

**Issue by Seedorf161** [flutter/flutter#32565] opened 2019-05-11 21:55 UTC
I'm trying to dispose adview while navigating to a video player page. 

I used
```
_bannerAd?.dispose();
_bannerAd = null;
```
to destroy the davies but the ad is still shown on the new page. I discovered that using `Navigator.pop` before `Navigator.push` solve the issue but i don't want to pop the previous page.

**Comment by SanchezQb** [comment] 2019-05-12 21:32
I can't seem to find a way around this too

**Comment by d-apps** [comment] 2019-07-06 17:53
I use myBanner.dipose() method before calling Navigator...push and it works fine.

class AdMob {
    static void closeBanner(){
      if(myBanner != null){
       myBanner.dispose();
       myBanner = null;
      }
    }
}
AdMob.closeBanner();
Navigator.of(context).push(MaterialPageRoute(builder....));

**Comment by BondarenkoStas** [comment] 2019-10-08 15:38
thank you @d-apps ! @Seedorf161 did it help?

**Comment by iapicca** [comment] 2019-11-08 10:38
Hi @Seedorf161 
for what I can see the issue is related to a FlutterFire plugin,
please open the issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
thank you

**Closed by iapicca** 2019-11-08 10:38 UTC
Labels: waiting for customer response
