### ISSUE TITLE
Tools should support Windows hosts

### ISSUE THREAD

**Issue by ssaurel** [flutter/flutter#16] opened 2015-05-06 20:02 UTC
Hello,

I follow the installation steps to use stocks examples which is in examples/stocks folder.

There, I executed pub get command and it was ok. Then, I tried to launch the sky_tool like said in the steps by steps instructions.

On examples/stocks folder :

`C:\Users\sylsau\MyDocuments\Android\dart\sky_sdk\examples\stocks>.\packages\sky\sky_tool start --install
'.\packages\sky\sky_tool' n'est pas reconnu en tant que commande interne
ou externe, un programme exécutable ou un fichier de commandes.`

Sorry, message is in french but problem is that sky_tool is not known as an executable. Is it normal ? sky_tool is not supported on Windows 8 ?

Thanks for your help.

Sylvain

**Comment by abarth** [comment] 2015-05-07 01:40
The underlying problem is that we haven't tested on Windows.  Can you try the following command:

python .\packages\sky\sky_tool start --install '.\packages\sky\sky_tool'

Another thing to try would be using cygwin or another unix-like shell on Windows.

**Comment by ssaurel** [comment] 2015-05-09 20:34
I tried the following command : 

>C:\Users\sylsau\MyDocuments\Android\dart\sky_sdk\examples\stocks>python.exe .\packages\sky\sky_tool start --install '.\packages\sky\sky_tool'
 File ".\packages\sky\sky_tool", line 131
    print '%s is not installed, installing.' % APK_NAME
                                           ^
SyntaxError: Missing parentheses in call to 'print'

I use Python 3.4.3. Another Python version is supported ?

**Comment by Pajn** [comment] 2015-05-09 21:02
print without parentheses is Python 2 syntax, try with 2.7.

Shouldn't new projects support Python 3?

**Comment by ssaurel** [comment] 2015-05-10 06:27
So, I installed Python 2.7. It would be good to mention on steps by steps documentation that Python 2.7 is mandatory.

I executed the command : 

`C:\Users\sylsau\MyDocuments\Android\dart\sky_sdk\examples\stocks>python .\packages\sky\sky_tool start --install
SkyDemo.apk is not installed, installing.
'C:\Users\sylsau\MyDocuments\Android\dart\sky_sdk\examples\stocks\packages\apks\SkyDemo.apk' does not exist?
WARNING:root:Failed to write pid file: /tmp/sky_tool.pids`

So, I copied packages\sky\apks\SkyDemo.apk to examples\stocks\packages\apks\SkyDemo.apk .

Then, I executed the command and now it works !

**Comment by abarth** [comment] 2015-05-10 06:35
Yay!  I'm glad it worked.  Would you be willing to send a pull request improving the documentation to explain how to get it working on Windows?

**Comment by ssaurel** [comment] 2015-05-10 06:55
Yes, I can. I try to update the documentation as soon as possible.

**Comment by adirkuhn** [comment] 2015-05-11 20:54
to run on windows 8 i need made this changes 
line 28 
```PID_FILE_PATH = "/tmp/sky_tool.pids"``` to ```PID_FILE_PATH = "c:/tmp/sky_tool.pids"```

line 169
```ADB_PATH, 'reverse', port_string, port_string```
to
```ADB_PATH, 'forward', port_string, port_string```

line 205
```subprocess.call([ADB_PATH, 'reverse', '--remove', port_string])```
to
```subprocess.call([ADB_PATH, 'forward', '--remove', port_string])```

**Comment by eseidelGoogle** [comment] 2015-05-12 17:25
We should fix PID_FILE_PATH to use tempfile.gettempdir().

ADB reverse and forward are not the same thing. :)  We require a very recent adb which has the reverse command.  Did the old adb forward command used to do what reverse does now?  If so, that's confusing. :/

**Comment by adirkuhn** [comment] 2015-05-13 12:25
Ok my mistake because I haven't found 'reverse' option on my adb. I updated it and get reverse option now.
Thanks

**Comment by TheBosZ** [comment] 2015-11-11 20:07
I wrote a batch file to take care of the "flutter" command: #297 
Also, the python script to update packages has been converted to Dart.

**Comment by Hixie** [comment] 2015-12-12 00:57
Closing as a duplicate of https://github.com/flutter/flutter/issues/138 - please reopen if I misunderstood what this was about.

**Closed by Hixie** 2015-12-12 00:57 UTC
Labels: affects: dev experience, affects: tools
