### ISSUE TITLE
how to convert _JsonMap with lint 2.0 ??

### ISSUE THREAD

**Issue by flexmeKim** [flutter/flutter#107452] opened 2022-07-12 08:42 UTC
my code here
```dart
    final List<Brand> brandList = [];
    final http.Response response = await http.get(
      Uri.parse(url),
      headers: headers,
    );

    final dynamic d1 = json.decode(response.body);
    final list = d1 as Map<dynamic, dynamic>;
    final da = list['result'] as List<dynamic>;
    da.map((dynamic e) {
      brandList.add(Brand.fromJson(e));
    }).toList();
```

Regardless of how you shape it, it comes out as a _JsonMap. Dynamic cannot be peeled off.

What should I do?

my lint here
<details>
<summary>lint rules</summary>

```
# Specify analysis options.
#
# Until there are meta linter rules, each desired lint must be explicitly enabled.
# See: https://github.com/dart-lang/linter/issues/288
#
# For a list of lints, see: http://dart-lang.github.io/linter/lints/
# See the configuration guide for more
# https://github.com/dart-lang/sdk/tree/main/pkg/analyzer#configuring-the-analyzer
#
# There are other similar analysis options files in the flutter repos,
# which should be kept in sync with this file:
#
#   - analysis_options.yaml (this file)
#   - https://github.com/flutter/plugins/blob/master/analysis_options.yaml
#   - https://github.com/flutter/engine/blob/master/analysis_options.yaml
#   - https://github.com/flutter/packages/blob/master/analysis_options.yaml
#
# This file contains the analysis options used by Flutter tools, such as IntelliJ,
# Android Studio, and the `flutter analyze` command.

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  errors:
    # treat missing required parameters as a warning (not a hint)
    missing_required_param: warning
    # treat missing returns as a warning (not a hint)
    missing_return: warning
    # allow having TODO comments in the code
    todo: ignore
    # allow self-reference to deprecated members (we do this because otherwise we have
    # to annotate every member in every test, assert, etc, when we deprecate something)
    deprecated_member_use_from_same_package: ignore
    # TODO(ianh): https://github.com/flutter/flutter/issues/74381
    # Clean up existing unnecessary imports, and remove line to ignore.
    unnecessary_import: ignore
    # Turned off until null-safe rollout is complete.
    unnecessary_null_comparison: ignore
  exclude:
    - "bin/cache/**"
    # Ignore protoc generated files
    - "dev/conductor/lib/proto/*"

linter:
  rules:
    # these rules are documented on and in the same order as
    # the Dart Lint rules page to make maintenance easier
    # https://github.com/dart-lang/linter/blob/master/example/all.yaml
    # - always_declare_return_types
    # - always_put_control_body_on_new_line
    # - always_put_required_named_parameters_first # we prefer having parameters in the same order as fields https://github.com/flutter/flutter/issues/10219
    - always_require_non_null_named_parameters
    # always_specify_types
    # - always_use_package_imports # we do this commonly
    - annotate_overrides
    # - avoid_annotating_with_dynamic # conflicts with always_specify_types
    - avoid_bool_literals_in_conditional_expressions
    # - avoid_catches_without_on_clauses # blocked on https://github.com/dart-lang/linter/issues/3023
    # - avoid_catching_errors # blocked on https://github.com/dart-lang/linter/issues/3023
    - avoid_classes_with_only_static_members
    - avoid_double_and_int_checks
    - avoid_dynamic_calls # 이걸 꼭 주석 해제 해서 dynamic을 제어 하자
    - avoid_empty_else
    - avoid_equals_and_hash_code_on_mutable_classes
    - avoid_escaping_inner_quotes
    - avoid_field_initializers_in_const_classes
    # - avoid_function_literals_in_foreach_calls
    - avoid_implementing_value_types
    # ★ [메모리 누수] null로 초기화 하면 예기치 않은 메모리 누수가 발생 할 수 있다.
    # 명시적으로 초기화 되지 않은 변수나 필드는 자동으로 Dart에서 null로 초기화 한다.
    - avoid_init_to_null
    - avoid_js_rounded_ints
    # - avoid_multiple_declarations_per_line # seems to be a stylistic choice we don't subscribe to
    - avoid_null_checks_in_equality_operators
    # - avoid_positional_boolean_parameters # would have been nice to enable this but by now there's too many places that break it
    # - avoid_print
    # - avoid_private_typedef_functions # we prefer having typedef (discussion in https://github.com/flutter/flutter/pull/16356)
    - avoid_redundant_argument_values
    - avoid_relative_lib_imports
    - avoid_renaming_method_parameters
    - avoid_return_types_on_setters
    - avoid_returning_null # still violated by some pre-nnbd code that we haven't yet migrated
    - avoid_returning_null_for_future
    - avoid_returning_null_for_void
    # - avoid_returning_this # there are enough valid reasons to return `this` that this lint ends up with too many false positives
    - avoid_setters_without_getters
    - avoid_shadowing_type_parameters
    - avoid_single_cascade_in_expression_statements
    - avoid_slow_async_io
    - avoid_type_to_string
    - avoid_types_as_parameter_names
    # - avoid_types_on_closure_parameters # conflicts with always_specify_types
    - avoid_unnecessary_containers
    - avoid_unused_constructor_parameters
    - avoid_void_async
    # - avoid_web_libraries_in_flutter # we use web libraries in web-specific code, and our tests prevent us from using them elsewhere
    - await_only_futures
    - camel_case_extensions
    - camel_case_types
    # ★ [메모리 누수] StreamSubscription은 취소 하지 말자.
    - cancel_subscriptions
    # - cascade_invocations # doesn't match the typical style of this repo
    - cast_nullable_to_non_nullable
    # ★ [메모리 누수] Sink 인스턴스를 닫으면 예기치 않은 메모리 누수가 발생 할 수 있다.
    - close_sinks # not reliable enough
    # - comment_references # blocked on https://github.com/dart-lang/linter/issues/1142
    # - constant_identifier_names # needs an opt-out https://github.com/dart-lang/linter/issues/204
    - control_flow_in_finally
    # - curly_braces_in_flow_control_structures # not required by flutter style
    - depend_on_referenced_packages
    - deprecated_consistency
    # - diagnostic_describe_all_properties # enabled only at the framework level (packages/flutter/lib)
    - directives_ordering
    # - do_not_use_environment # there are appropriate times to use the environment, especially in our tests and build logic
    - empty_catches
    - empty_constructor_bodies
    - empty_statements
    - eol_at_end_of_file
    - exhaustive_cases
    - file_names
    - flutter_style_todos
    - hash_and_equals
    - implementation_imports
    # - invariant_booleans # too many false positives: https://github.com/dart-lang/linter/issues/811
    - iterable_contains_unrelated_type
    # - join_return_with_assignment # not required by flutter style
    # - leading_newlines_in_multiline_strings
    - library_names
    - library_prefixes
    - library_private_types_in_public_api
    # - lines_longer_than_80_chars # not required by flutter style
    - list_remove_unrelated_type
    # - literal_only_boolean_expressions # too many false positives: https://github.com/dart-lang/linter/issues/453
    - missing_whitespace_between_adjacent_strings
    - no_adjacent_strings_in_list
    # - no_default_cases
    - no_duplicate_case_values
    - no_logic_in_create_state
    # - no_runtimeType_toString # ok in tests; we enable this only in packages/
    - non_constant_identifier_names
    - noop_primitive_operations
    - null_check_on_nullable_type_parameter
    - null_closures
    # - omit_local_variable_types # opposite of always_specify_types
    # - one_member_abstracts # too many false positives
    - only_throw_errors # this does get disabled in a few places where we have legacy code that uses strings et al
    - overridden_fields
    - package_api_docs
    - package_names
    - package_prefixed_library_names
    # - parameter_assignments # we do this commonly
    - prefer_adjacent_string_concatenation
    #    - prefer_asserts_in_initializer_lists
    # - prefer_asserts_with_message # not required by flutter style
    - prefer_collection_literals
    - prefer_conditional_assignment
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    # - prefer_constructors_over_static_methods # far too many false positives
    - prefer_contains
    # - prefer_double_quotes # opposite of prefer_single_quotes
    - prefer_equal_for_default_values
    # - prefer_expression_function_bodies # conflicts with https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#consider-using--for-short-functions-and-methods
    - prefer_final_fields
    - prefer_final_in_for_each
    - prefer_final_locals
    # - prefer_final_parameters # we should enable this one day (see also parameter_assignments)
    # - prefer_final_parameters # we should enable this one day (see also parameter_assignments)
    - prefer_for_elements_to_map_fromIterable
    - prefer_foreach
    - prefer_function_declarations_over_variables
    - prefer_generic_function_type_aliases
    - prefer_if_elements_to_conditional_expressions
    - prefer_if_null_operators
    - prefer_initializing_formals
    - prefer_inlined_adds
    # - prefer_int_literals # conflicts with https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#use-double-literals-for-double-constants
    - prefer_interpolation_to_compose_strings
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_is_not_operator
    - prefer_iterable_whereType
    # - prefer_mixin # Has false positives, see https://github.com/dart-lang/linter/issues/3018
    - prefer_null_aware_operators
    # - prefer_null_aware_method_calls # "call()" is confusing to people new to the language since it's not documented anywhere
    # - prefer_relative_imports
    - prefer_single_quotes
    - prefer_spread_collections
    - prefer_typing_uninitialized_variables
    - prefer_void_to_null
    - provide_deprecation_message
    # - public_member_api_docs # enabled on a case-by-case basis; see e.g. packages/analysis_options.yaml
    - recursive_getters
    # - require_trailing_commas # blocked on https://github.com/dart-lang/sdk/issues/47441
    - sized_box_for_whitespace
    - slash_for_doc_comments
    # - sort_child_properties_last
    - sort_constructors_first
    # - sort_pub_dependencies # prevents separating pinned transitive dependencies
    - sort_unnamed_constructors_first
    - test_types_in_equals
    - throw_in_finally
    - tighten_type_of_initializing_formals
    # - type_annotate_public_apis # subset of always_specify_types
    - type_init_formals
    # - unawaited_futures # too many false positives, especially with the way AnimationController works
    - unnecessary_await_in_return
    - unnecessary_brace_in_string_interps
    - unnecessary_const
    - unnecessary_constructor_name
    # - unnecessary_final # conflicts with prefer_final_locals
    - unnecessary_getters_setters
    # - unnecessary_lambdas # has false positives: https://github.com/dart-lang/linter/issues/498
    - unnecessary_new
    - unnecessary_null_aware_assignments
    - unnecessary_null_checks
    - unnecessary_null_in_if_null_operators
    - unnecessary_nullable_for_final_variable_declarations
    - unnecessary_overrides
    - unnecessary_parenthesis
    # - unnecessary_raw_strings # what's "necessary" is a matter of opinion; consistency across strings can help readability more than this lint
    - unnecessary_statements
    - unnecessary_string_escapes
    - unnecessary_string_interpolations
    - unnecessary_this
    - unrelated_type_equality_checks
    # - unsafe_html
    # ★ [CRASH] [use_build_context_synchronously] async 안에서 BuildContext를 사용하지 마십시오. 이 규칙은 현재 실험적입니다.
    # 세부사항은 async 간격에서 BuildContext를 사용하지 마십시오. 나중에 사용하기 위해 BuildContext를 저장하면 쉽게 크래시를 진단하기 어려울 수 있습니다.
    # async 간격은 암시적으로 BuildContext를 저장하며 코드를 작성할 때 간과하기 가장 쉬운 부분입니다.
    # StatefulWidget에서 BuildContext를 사용하는 경우 async 간격 후에 탑재된 속성을 확인해야 합니다.
    #
    # GOOD ==========================================
    # void onButtonTapped(BuildContext context) {
    #   Navigator.of(context).pop();
    # }
    #
    # BAD  ==========================================
    # void onButtonTapped(BuildContext context) async {
    #   await Future.delayed(const Duration(seconds: 1));
    #   Navigator.of(context).pop();
    # }
    #
    # GOOD ==========================================
    # class _MyWidgetState extends State<MyWidget> {
    #   ...
    #
    #   void onButtonTapped() async {
    #     await Future.delayed(const Duration(seconds: 1));
    #
    #     if (!mounted) return;
    #     Navigator.of(context).pop();
    #   }
    # }
    - use_build_context_synchronously
    - use_full_hex_values_for_flutter_colors
    - use_function_type_syntax_for_parameters
    - use_if_null_to_convert_nulls_to_bools # blocked on https://github.com/dart-lang/sdk/issues/47436
    - use_is_even_rather_than_modulo
    - use_key_in_widget_constructors
    - use_late_for_private_fields_and_variables
    # - use_named_constants
    - use_raw_strings
    - use_rethrow_when_possible
    - use_setters_to_change_properties
    # - use_string_buffers # has false positives: https://github.com/dart-lang/sdk/issues/34182
    - use_test_throws_matchers
    # - use_to_and_as_if_applicable # has false positives, so we prefer to catch this by code-review
    - valid_regexps
    - void_checks
```
</details>

**Comment by maheshmnj** [comment] 2022-07-12 09:42
Hi @flexmeKim, I am quite not sure what the bug is or How linting is related to JSON parsing? Can you please share the json data that you want to parse and the error that your are seeing?

**Comment by iapicca** [comment] 2022-07-12 20:56
@flexmeKim 
with this approach this approach `flutter_lints: ^2.0.1` & `Flutter 3.0.4` don't complain
try it in [dartpad](https://dartpad.dartlang.org/)

<details>
  <summary>code sample</summary>

```dart
import 'dart:convert';

import 'package:flutter/material.dart';

typedef Json = Map<String, Object?>;

const fakeResponseBody = '''
{
	"result": [{
			"name": "nike"
		},
		{
			"name": "under armor"
		},
		{
			"name": "adidas"
		},
		{
			"name": "puma"
		}
	]
}
''';

class Brand {
  final String name;
  const Brand(this.name);

  @override
  bool operator ==(Object other) => other is Brand && other.hashCode == hashCode;

  @override
  int get hashCode => name.hashCode;

  factory Brand.fromJson(Json json) => Brand(json['name'] as String);

  Json toJson() => {'name': name};
}

List<Brand> getBrands() {
  try {
    final parsedJson = jsonDecode(fakeResponseBody);
    final brands = List.from(parsedJson['result']);
    return [for (final brand in brands) Brand.fromJson(brand)];
  } catch (e) {
    debugPrint('#### HANDLE THIS BETTER IN PRODUCTION! ###' '\n' '$e');
    return [];
  }
}

void main() => runApp(
      MaterialApp(
        home: Scaffold(
          body: ListView(
            children: [
              for (final brand in getBrands()) Center(child: Text(brand.name)),
            ],
          ),
        ),
      ),
    );
  
```
</details>

**Comment by flexmeKim** [comment] 2022-07-13 00:54
> 
<img width="1156" alt="스크린샷 2022-07-13 오전 9 51 19" src="https://user-images.githubusercontent.com/102011574/178625101-aca62dff-5419-47d9-8379-6c34ef9a8a70.png">

{code: 200, message: success, result: [{brandId: 1, brand: A.P.C.}, {brandId: 2, brand: ALEXANDER MCQUEEN}, {brandId: 3, brand: ALEXANDER MCQUEEN}, {brandId: 4, brand: AMI}, {brandId: 5, brand: BALENCIAGA}, {brandId: 6, brand: BALLY}, {brandId: 7, brand: BALMAIN}, {brandId: 8, brand: BOTTEGA VENETA}, {brandId: 9, brand: BURBERRY}, {brandId: 10, brand: DOLCE & GABBANA}, {brandId: 11, brand: GOLDEN GOOSE DELUEXE BRAND}, {brandId: 12, brand: ISABEL MARANT ETOILE}, {brandId: 13, brand: KENZO}, {brandId: 14, brand: MAISON KITSUNE}, {brandId: 15, brand: MONCLER}, {brandId: 16, brand: PRADA}, {brandId: 17, brand: SAINT LAURENT}, {brandId: 18, brand: SALVATRORE FERRAGAMO}, {brandId: 19, brand: THOM BROWNE}, {brandId: 20, brand: VALENTINO GARAVANI}, {brandId: 21, brand: VERSACE}]}

value here 


Rather than an error, I want to remove the dynamic and specify the type, but I can't specify the type without being cast as at all.

**Comment by flexmeKim** [comment] 2022-07-13 00:56
@iapicca  Thank you, but it didn't help me ㅜㅜ

**Comment by maheshmnj** [comment] 2022-07-13 06:39
@flexmeKim, jsonDecode returns List<dynamic> for lists and Map<String, dynamic> for maps, so you cannot specify your custom Type there. Closing as this is working as intended.

**Closed** 2022-07-13 06:39 UTC
