### ISSUE TITLE
[tool_crash] FileSystemException: Failed to set file modification time, path = 'D:\download_teach-master\.packages' (OS Error: Access is denied., errno = 5)

### ISSUE THREAD

**Issue by abdoYoussef** [flutter/flutter#67929] opened 2020-10-12 16:13 UTC
## Command
```
flutter run --machine --target lib\main.dart -d emulator-5554 --track-widget-creation --dart-define=flutter.inspector.structuredErrors=true --start-paused
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: FileSystemException: Failed to set file modification time, path = 'D:\download_teach-master\.packages' (OS Error: Access is denied.
, errno = 5)
```
#0      _File.setLastModifiedSync (dart:io/file_impl.dart:473:7)
#1      ForwardingFile.setLastModifiedSync (package:file/src/forwarding/forwarding_file.dart:62:55)
#2      ForwardingFile.setLastModifiedSync (package:file/src/forwarding/forwarding_file.dart:62:55)
#3      _DefaultPub.get (package:flutter_tools/src/dart/pub.dart:213:19)
#4      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:706:17)
<asynchronous suspension>
#5      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:620:33)
<asynchronous suspension>
#6      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart)
#7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#8      _rootRun (dart:async/zone.dart:1184:13)
#9      _CustomZone.run (dart:async/zone.dart:1077:19)
#10     _runZoned (dart:async/zone.dart:1619:10)
#11     runZoned (dart:async/zone.dart:1539:10)
#12     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#13     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:610:20)
#14     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#15     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:339:21)
<asynchronous suspension>
#16     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart)
```
```
[✓] Flutter (Channel stable, v1.17.3, on Microsoft Windows [Version 10.0.18363.1082], locale en-US)
    • Flutter version 1.17.3 at C:\flutter_windows_v1.12.13+hotfix.9-stable\flutter
    • Framework revision b041144f83 (4 months ago), 2020-06-04 09:26:11 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Users\elsawah\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: C:\Users\elsawah\AppData\Local\Programs\AdoptOpenJDK\bin\java
    • Java version OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.6+10)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions.

[!] Android Studio
    • Android Studio at D:\android_install/to/android/studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    ✗ android-studio-dir = D:\android_install/to/android/studio
    ✗ Android Studio not found at D:\android_install/to/android/studio
    • Try updating or re-installing Android Studio.
    • Consider removing your android-studio-dir setting by running:
      flutter config --android-studio-dir=

[✓] VS Code (version 1.50.0)
    • VS Code at C:\Users\elsawah\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.15.0

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 7.1.1 (API 25) (emulator)

! Doctor found issues in 2 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: beta
**Creation framework version**: 2738a1148ba6c9a6114df62358109407c3ef2553
### Plugins
flutter_downloader-1.4.4
path_provider-1.6.10
path_provider_linux-0.0.1+1
path_provider_macos-0.0.4+3
permission_handler-5.0.1

**Comment by sidrao2006** [comment] 2020-10-12 17:19
Possible Duplicate of #67141

Hey @abdoYoussef , I found an open issue addressing your problem. Please follow up there
Thanks.

**Comment by sidrao2006** [comment] 2020-10-12 17:21
Hey @abdoYoussef , could you please try updating the Flutter tool as you are a few versions behind.

Thanks

**Comment by darshankawar** [comment] 2020-10-13 07:05
@abdoYoussef 
Please upgrade to latest stable and try again to see if you get same error or resolves your issue.
Thanks.

**Comment by pedromassangocode** [comment] 2020-11-04 12:39
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2020-11-04 12:39 UTC
