### ISSUE TITLE
Tests hang if they have an import error

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#3305] opened 2016-04-13 20:22 UTC
e.g. if you haven't run pub get, so package imports fail, "flutter test" just hangs forever.

**Comment by eseidelGoogle** [comment] 2016-04-15 21:53
Is https://github.com/flutter/flutter/issues/2182 the answer?  Not sure what the plan to solve this is.

**Comment by Hixie** [comment] 2016-04-15 21:55
yeah this is probably a dupe of that one

**Comment by eseidelGoogle** [comment] 2016-04-15 21:57
Dupe of #2182

**Closed by eseidelGoogle** 2016-04-15 21:57 UTC
Labels: affects: dev experience, affects: framework, affects: tests, ⚠ code health
