### ISSUE TITLE
Flutter with Firebase is completely broken in Xcode 12 

### ISSUE THREAD

**Issue by azamsharp** [flutter/flutter#72251] opened 2020-12-14 01:02 UTC
Flutter is completely broken when integrating with Firebase. Getting the following error: 

   <pb_decode.h>
    /Users/azamsharp/Desktop/todo_list/ios/Pods/Target Support Files/nanopb/nanopb-umbrella.h:19:9: error: double-quoted include
    "pb_common.h" in framework header, expected angle-bracketed instead [-Werror,-Wquoted-include-in-framework-header]
    #import "pb_common.h"
            ^~~~~~~~~~~~~
            <pb_common.h>
    /Users/azamsharp/Desktop/todo_list/ios/Pods/Target Support Files/nanopb/nanopb-umbrella.h:20:9: error: double-quoted include
    "pb.h" in framework header, expected angle-bracketed instead [-Werror,-Wquoted-include-in-framework-header]
    #import "pb.h"
            ^~~~~~
            <pb.h>

**Comment by pedromassangocode** [comment] 2020-12-14 08:30
Hi @azamsharp 
From what I can see, the issue is related to a FlutterFire plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by pedromassangocode** 2020-12-14 08:30 UTC
