### ISSUE TITLE
Korean characters are displayed abnormally in TextField when moved cursor.

### ISSUE THREAD

**Issue by foryou8033j** [flutter/flutter#29341] opened 2019-03-14 07:08 UTC
## Steps to reproduce
1. Input some Korean Characters into the TextField
`안녕하세요|`

2. Move cursor to middle of characters
`안녕|하세요`

3. input some characters or numbers whatever
`안녕5|하세요`

4. boom
`안녕하세요5|하세요`

**Check This**
1. Video
https://serviceapi.nmv.naver.com/flash/convertIframeTag.nhn?vid=98B4DFE49D13BFBEED4D444D7EAECFCF789A&outKey=V124950047e787575d0585747baa0b9e1633eb84b1000f944d5ac5747baa0b9e1633e&width=544&height=306

2. TextField Code

```dart
TextEditingController _textEditingController = TextEditingController();

return Container(
    color: Colors.transparent,
    padding: EdgeInsets.all(10.0),
    child: Card(
        color: Colors.transparent,
        elevation: 8,
        child: ClipRRect(
            borderRadius: BorderRadius.all(Radius.circular(16.0)),
            child: Container(
              height: 50.0,
              padding: EdgeInsets.symmetric(horizontal: 16.0),
              color: Theme.of(context).accentColor,
              child: TextField(
                decoration: InputDecoration(icon: Icon(Icons.search), border: InputBorder.none, hintStyle: TextStyle(fontSize: 18), hintText: getHintText()),
                textInputAction: TextInputAction.search,
                cursorColor: Colors.black,
                style: TextStyle(fontSize: 18),
                controller: _textEditingController,
                onSubmitted: (text) => handleSearch(context, searched_keyword, text, search_module_srl),
              ),
            ))),
    );
```

## Logs

**flutter analyze**
```
There is no `flutter analyze` Error.
```

**flutter doctor -v**
```
[√] Flutter (Channel stable, v1.0.0, on Microsoft Windows [Version 10.0.17134.648], locale ko-KR)
    • Flutter version 1.0.0 at C:\flutter
    • Framework revision 5391447fae (3 months ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at C:\Users\admin\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 29.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[!] VS Code, 64-bit edition (version 1.27.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (1 available)
    • SM G973N • R39M20E00AJ • android-arm64 • Android 9 (API 28)

! Doctor found issues in 1 category.
```

This problem only occurs on Android only .. iOS was fine.

**Comment by HansMuller** [comment] 2019-06-21 16:37
cc @GaryQian

**Comment by timsneath** [comment] 2019-09-03 08:58
I am not myself able to reproduce this on the latest Flutter master:
![image](https://user-images.githubusercontent.com/2319867/64158970-48467b80-cdee-11e9-8ec2-a6dc5d3f267e.png)

Could you try upgrading with `flutter upgrade` and try again on a more recent build? This may have been fixed since it was reported...

**Comment by timsneath** [comment] 2019-09-05 05:30
This bug reproduces on a Samsung Galaxy 9 with the Samsung keyboard, running v1.7.8 from the `stable` channel.

**Comment by GaryQian** [comment] 2019-09-05 17:51
This may be related to https://github.com/flutter/flutter/issues/31512

**Comment by GaryQian** [comment] 2019-09-05 21:33
I have determined the cause of the bug.

New versions of Samsung Keyboard no longer commit the text when attempting to edit within a composing region. Instead, it calls the `setComposingText` with the full composing string as if the caret had not moved. This causes Flutter to insert the entire string as composing text.

One potential solution is to manually commit composing regions when the caret is moved. This choice would bring Samsung keyboards to parity with other keyboards.

However, in the case this is an active choice by Samsung to allow editing in composing regions, we should attempt to properly handle this behavior by sanitizing the already-typed characters out of the `setComposingText` string.

**Comment by GaryQian** [comment] 2019-09-05 23:52
After working with @justinmc, We suspect a possible root cause is that Samsung implemented their keyboard against a modified android API. The input to `setComposingText` seems to be inconsistent with the docs and the behavior of the method, particularly, the API/vanilla implementation assumes that cursor must go at beginning or end of composing region, whereas Samsung cursor can to in the middle as well.

We are exploring options on how to resolve this.

**Comment by justinmc** [comment] 2019-09-07 01:11
I've been looking into this so I'm going to write out some notes.

Here is an example of the problem.  The vertical bar is the cursor.  Capital letters are part of the composing region.  The bold commands show what causes the difference in the final row.

| Unaffected Device | Affected Device |
| ------------------------- | -------------------- |
| A\|                           | A\|                       |
| AB\|                         | AB\|                      |
| ABC\|                      | ABC\|                      |
| ABCD\|                    | ABCD\|                      |
| ab\|cd                      | ab\|cd                      |
| **setComposingText "e"** | **setComposingRegion 0-2**                      |
|                                | **setComposingText "abcde"**                      |
| abE\|cd                   | ABCDE\|cd                      |

Here are the problems that I see happening.

  1. `setComposingRegion` is called on the affected device when it shouldn't be called at all.  The range that it's called with also seems quite strange.
  1. When inserting the final character, `setComposingText` is called with the entire string, as if the previous composing region is still active.
  1. Unrelated to this example, I also see the affected device sometimes calling `commitText` when the unaffected device only calls `setComposingText`.  I usually see this manifest as characters being inserted in strange places away from the cursor.

These behaviors seem to be an attempt to allow editing the middle of a composing region, as Gary mentioned above.  I was hoping that there was something in BaseInputConnection that Flutter wasn't handling well, but I can't find anything like that or any real pattern to the 3 problems.

I also tried hacking in various fixes that would ideally take care of all 3 problems, but wasn't able to find a hack that worked in all cases, especially not a hack that also worked on unaffected devices as well.

I'll keep digging into this!

**Comment by Hixie** [comment] 2019-09-10 23:38
@justinmc I assigned this to you since you said you'd keep digging into it.

**Comment by justinmc** [comment] 2019-09-13 15:29
Yesterday @jayoung-lee helped me figure out the difference between the old and new native keyboards.  The old keyboard does not allow re-opening a composing region for a previously typed character, but the new keyboard does.  For example:

  1. Type "ㄴ".
  1. Type a space, then a backspace.
  1. Type "ㅏ".

On the old keyboard, the composing region is now just the final character, but on the new keyboard, it's both characters.  This is a convenience improvement for Korean input.

**Comment by justinmc** [comment] 2019-09-13 22:05
If there's going to be a solution here where we just inform the keyboard of something we forgot about before, it may be for moving the cursor by tapping.  If I move the cursor by dragging on the keyboard, the bug doesn't happen.  If I move the cursor programmatically in native Android, I see strange behavior.

**Comment by GaryQian** [comment] 2019-09-16 17:34
We have a suspicion this may have something to do with the touch-to-coordinate-to-textposition stack of code that happens when you drag the caret around not updating the keyboard on its progress.

Investigating in this area.

**Comment by justinmc** [comment] 2019-09-17 16:50
I think this is a bug in the Samsung keyboard even in native Android.  It's exposed when the cursor is moved programmatically, like in this demo app I've made where the cursor is moved to the start after a timeout:

![korean_input_native](https://user-images.githubusercontent.com/389558/65061728-630d0a00-d92f-11e9-9282-702aeffdb863.gif)

The final text is "ㄴㅇ" when it should be "ㅇㄴ".

I get the same buggy result for every way to set selection that I've tried:

```java
// The most straightforward way to set selection (which I don't think Flutter
// could use anyway because Flutter has no EditText).
view.setSelection(selectionStart, selectionEnd);

// Flutter currently uses both of these.
mImm.updateSelection(myCustomView, selectionStart, selectionEnd, composingStart, composingEnd);
Selection.setSelection(mEditable, selectionStart, selectionEnd);

// This is a hack I came up with that fixed some cases, but not the case shown here.
sendKeyEvent(new KeyEvent(KeyEvent.ACTION_DOWN, KeyEvent.KEYCODE_DPAD_LEFT));
sendKeyEvent(new KeyEvent(KeyEvent.ACTION_UP, KeyEvent.KEYCODE_DPAD_LEFT));
```

I think the question from here is, is there any other way to programmatically set the cursor position that we could try?  How does Android handle taps on an EditText that change cursor position internally?

**Comment by markmoskalenko** [comment] 2019-09-18 06:34
Do you think you can expect an early solution to this problem on your part?

We already made the entire application on the flutter and are now in a stupor because we can’t solve the problem of duplicating text on Samsung phones..

**Comment by justinmc** [comment] 2019-09-18 14:51
I'm actively working on trying to fix this, it's a major priority.  That said, I don't know if the solution will be a quick hack or a bigger undertaking.  I'll keep posting updates to this issue so that everyone is informed as I learn more, though.

**Comment by justinmc** [comment] 2019-09-18 22:06
Here's a complete native Android app that shows how to reproduce the Samsung keyboard bug: https://github.com/justinmc/android-samsung-keyboard-bug-demo

**Comment by Kiboom** [comment] 2019-09-19 08:41
We made our flagship app with Flutter, but the bug blocks us from shipping the app.

It's a serious bug because Users write long text within the app, so the bug's expected to be occured more frequently.


And most of our users are Korean, and Samsung device

It may have the same cause as #31512. It does not reproduce with the Gboard keyboard. The bug is blocking a Korean company from shipping a flagship Flutter app, and so they are seeking a fix urgently.

**Comment by markmoskalenko** [comment] 2019-09-19 09:11
The error also does not reproduce on galaxy s7.
On s8 s9 is playing

**Comment by justinmc** [comment] 2019-09-20 15:45
I filed a bug on Android as I continue to investigate this: https://b.corp.google.com/issues/141367011

**Comment by justinmc** [comment] 2019-09-23 22:37
I'm making some progress but not quite there yet.  @mklim came up with a [fix](https://github.com/mklim/android-samsung-keyboard-bug-demo/commit/e0805a15ca293a4dd7cfb3ec1d1c624db6f2ed0a) that worked on native Android, but it didn't work when I tried copying it into Flutter.  I found that when I extended BaseInputConnection like [Flutter does](https://github.com/flutter/engine/blob/master/shell/platform/android/io/flutter/plugin/editing/InputConnectionAdaptor.java), then the solution didn't work in native Android either.  My conclusion is that Flutter's BaseInputConnection subclass is somehow causing this problem.

I found that I can make native Android work by adding these three methods from BaseInputClass to the subclass:

```java
public class InputConnectionAdapter extends BaseInputConnection {

    ...

    @Override
    public boolean beginBatchEdit() {
        synchronized(this) {
            if (mBatchEditNesting >= 0) {
                // Can't be called in Flutter because there is no mTextView.
                mTextView.beginBatchEdit();
                mBatchEditNesting++;
                return true;
            }
        }
        return false;
    }

    @Override
    public boolean endBatchEdit() {
        synchronized(this) {
            if (mBatchEditNesting > 0) {
                // Can't be called in Flutter because there is no mTextView.
                mTextView.endBatchEdit();
                mBatchEditNesting--;
                return true;
            }
        }
        return false;
    }

    @Override
    public ExtractedText getExtractedText(ExtractedTextRequest request, int flags) {
        if (mTextView != null) {
            ExtractedText et = new ExtractedText();
            // Can't be called in Flutter because there is no mTextView.
            if (mTextView.extractText(request, et)) {
                if ((flags&GET_EXTRACTED_TEXT_MONITOR) != 0) {
                    // Can't be called in Flutter or my Android app because setExtracting is hidden
                    // or something like that. However, that doesn't seem to matter!  Still works.
                    //mTextView.setExtracting(request);
                }
                return et;
            }
        }
        return null;
    }

    ...

}
```

As pointed out in the comments in the code block, there are three vital calls here that are not able to be made in Flutter due to Flutter not having an instance of TextView.  Removing any of these causes the solution to not work.

From here, maybe I can look into the source code of these three calls and see if I can figure out what exactly is making this work, and if we can somehow do the same in Flutter.

**Comment by mklim** [comment] 2019-09-24 20:56
I have one potential workaround up at mklim/engine@1134c9e7c557586d0a21a1b758c480532cbd12db. It still needs tests before I open it as a PR but I think the basic approach will unblock this. It's extremely heavy handed, but I think it is feasible. I'm restarting the IMM instead of `finishComposingText()`. From what I could tell since we're using `updateSelection` we need a full restart.

**Comment by Kiboom** [comment] 2019-09-25 09:45
We’re building a Q&A service using Flutter, which contains TextFields for the question.
Users tend to type lengthy text on it, so there's a high chance that they move cursor and insert some characters.
But like it's been discussed in the thread, the same issue reproduces in our TextFields on Samsung devices with Samsung Keyboard.
Since writing action is the key feature of our app, it's very critical issue that blocks us from shipping our flagship app.

It's a good new that potential workaround has been found :) 
Due to the time-sensitive schedule, we hope this issue can be resolved with a higher priority.

Thanks

**Closed** 2019-09-25 18:16 UTC
Labels: a: text input, customer: product, customer: raven, e: device-specific, f: material design, framework, severe: customer blocker, ▣ platform-android

**Comment by mklim** [comment] 2019-09-25 18:18
The work around has landed in the engine, but it will still take some time for it to roll into the framework and then the beta, dev, and finally stable channels.

**Comment by markmoskalenko** [comment] 2019-09-26 08:22
Included in the assembly of the Russian language!
Similar problem !!!!

**Comment by cwpark** [comment] 2019-11-25 12:43
This issue is still occurs when using the korean qwerty keyboard.
We tested on beta channel(1.11.0).

steps:
1. Enter `가나`.
> 가나|
2. Move the cursor to the center.
> 가|나
3. Enter `12`.
> 가12|나
4. Move the cursor to the center.
> 가1|2나
5. Enter `가`, then:
> 가1가1가|2나

**Comment by GaryQian** [comment] 2019-11-26 01:50
Thanks for the additional repro! The fix we landed was a workaround, and it doesn't seem to cover this case.

**Comment by timsneath** [comment] 2019-11-27 18:08
Any chance we can extend the fix to cover this? customer:raven are still
getting negative comments about this.
