### ISSUE TITLE
Drawer should draw over the status bar on iOS

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#5542] opened 2016-08-23 00:21 UTC
"On iOS the side nav is placed over both the app and status bars."

On the gallery, I see the drawer is drawing under the status bar.

Not sure if that's a config option of the Gallery, or something in our framework?

**Comment by sethladd** [comment] 2016-08-23 00:21
cc @Hixie is this something we can control in the framework?

**Comment by eseidelGoogle** [comment] 2016-08-23 01:48
See also https://github.com/flutter/flutter/issues/5127.  Was this a request from UX review?

**Comment by Hixie** [comment] 2016-08-23 16:28
This is a dupe of #5127. As noted in that bug, what's actually going on is that the few apps that appear to put the drawer over the status bar and the rest of the app under it are actually just hiding the status bar as they show their drawer. We could do that, but I could find no Apple apps that did it, so it's not clear to me why we would want to. It doesn't match what we do on other platforms, it's not needed for muscle memory, and in this case, it doesn't even match the local platform conventions.

**Comment by sethladd** [comment] 2016-08-23 16:46
Not from review. From an internal spec doc. Will send link out-of-band.

**Comment by Hixie** [comment] 2016-09-12 17:23
I'm going to close this on the basis that the document in question is impossible to implement on iOS, that no other application does it, and that it's arbitrarily different than our behavior on Android yet not necessary for muscle memory.

Please feel free to reopen if UX really want this, but only if there is information on how to implement it.

**Closed by Hixie** 2016-09-12 17:23 UTC
Labels: affects: fidelity, affects: framework, ⌺‬ platform-ios
