### ISSUE TITLE
Create a SearchAppBar Widget like Play Stores search interface

### ISSUE THREAD

**Issue by MichaelPriebe** [flutter/flutter#26396] opened 2019-01-11 00:03 UTC
![https://developer.android.com/images/search/search-ui.png](https://developer.android.com/images/search/search-ui.png)

The current SearchDelegate's look nothing like what Google does in the Play Store. Perhaps there can be a SearchAppBar Widget that works similar to the current AppBar but has the white outset for easier readability and a few methods:

`List<Widget> Function(String text) onType;` This should be called each time the user types into the field. Although maybe the return type could handle futures, for things like type-ahead http requests.

`void Function(String search) onSearch;` This should be called when the user completes the search, most likely navigating to a new route.

The typing suggestions could possibly be done with a ModalRoute, which could be popped for example pressing the back button to cancel the search or dismissing it with the barrier.

**Comment by JediBurrell** [comment] 2019-01-11 05:43
Duplicate: #17119

**Comment by MichaelPriebe** [comment] 2019-01-11 06:32
Wow isn't GitHubs search just terrible?? I'm glad to see someone has something prototyped, although there's no dismissal barrier.

**Comment by zoechi** [comment] 2019-01-11 06:50
Duplicate of #17119
Thanks @JediBurrell

**Closed by zoechi** 2019-01-11 06:50 UTC
