### ISSUE TITLE
[tool_crash] RPCError

### ISSUE THREAD

**Issue by OmarMahmoud2** [flutter/flutter#154739] opened 2024-09-06 18:17 UTC
## Command
```sh
flutter run
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
RPCError
```console
#0      new _OutstandingRequest (package:vm_service/src/vm_service.dart:261:34)
#1      VmService._call.<anonymous closure> (package:vm_service/src/vm_service.dart:1778:25)
#2      VmService._call (package:vm_service/src/vm_service.dart:1790:8)
#3      VmService.getVM (package:vm_service/src/vm_service.dart:1245:25)
#4      FlutterDevice.initLogReader (package:flutter_tools/src/resident_runner.dart:428:55)
#5      HotRunner.attach (package:flutter_tools/src/run_hot.dart:266:21)
<asynchronous suspension>
#6      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:867:27)
<asynchronous suspension>
#7      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1408:27)
<asynchronous suspension>
#8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#9      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#10     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:420:9)
<asynchronous suspension>
#11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:5)
<asynchronous suspension>
#13     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:130:9)
<asynchronous suspension>
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
```
```console
[32m[✓][39m Flutter (Channel stable, 3.24.2, on macOS 14.6.1 23G93 darwin-arm64, locale en-EG)
    [32m•[39m Flutter version 3.24.2 on channel stable at /Users/omarmahmoud/FlutterDev/flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision 4cf269e36d (3 days ago), 2024-09-03 14:30:00 -0700
    [32m•[39m Engine revision a6bd3f1de1
    [32m•[39m Dart version 3.5.2
    [32m•[39m DevTools version 2.37.2

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    [32m•[39m Android SDK at /Users/omarmahmoud/Library/Android/sdk
    [32m•[39m Platform android-35, build-tools 35.0.0
    [32m•[39m Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Xcode - develop for iOS and macOS (Xcode 15.4)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Build 15F31d
    [32m•[39m CocoaPods version 1.15.2

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[32m[✓][39m Android Studio (version 2024.1)
    [32m•[39m Android Studio at /Applications/Android Studio.app/Contents
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)

[32m[✓][39m VS Code (version 1.93.0)
    [32m•[39m VS Code at /Applications/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version 3.96.0

[32m[✓][39m Connected device (4 available)
    [32m•[39m sdk gphone64 arm64 (mobile)     • emulator-5554         • android-arm64  • Android 15 (API 35)
      (emulator)
    [32m•[39m macOS (desktop)                 • macos                 • darwin-arm64   • macOS 14.6.1 23G93
      darwin-arm64
    [32m•[39m Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         • macOS 14.6.1 23G93
      darwin-arm64
    [32m•[39m Chrome (web)                    • chrome                • web-javascript • Google Chrome 126.0.6478.115

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[32m•[39m No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: e1e47221e86272429674bec4f1bd36acc4fc7b77
### Plugins
device_info_plus-10.1.2
file_selector_linux-0.9.2+1
file_selector_macos-0.9.4
file_selector_windows-0.9.3+2
flutter_exit_app-1.1.4
flutter_jailbreak_detection-1.10.0
flutter_native_splash-2.4.1
flutter_paytabs_bridge-2.6.17
flutter_plugin_android_lifecycle-2.0.22
flutter_secure_storage-9.2.2
flutter_secure_storage_linux-1.2.1
flutter_secure_storage_macos-3.1.2
flutter_secure_storage_web-1.2.1
flutter_secure_storage_windows-3.1.2
flutter_share-2.0.0
image_picker-1.1.2
image_picker_android-0.8.12+13
image_picker_for_web-3.0.5
image_picker_ios-0.8.12
image_picker_linux-0.2.1+1
image_picker_macos-0.2.1+1
image_picker_windows-0.2.1+1
in_app_review-2.0.9
path_provider-2.1.4
path_provider_android-2.2.10
path_provider_foundation-2.4.0
path_provider_linux-2.2.1
path_provider_windows-2.3.0
purchases_flutter-8.1.0
shared_preferences-2.3.2
shared_preferences_android-2.3.2
shared_preferences_foundation-2.5.2
shared_preferences_linux-2.4.1
shared_preferences_web-2.4.2
shared_preferences_windows-2.4.1
sqflite-2.3.3+1
url_launcher-6.3.0
url_launcher_android-6.3.10
url_launcher_ios-6.3.1
url_launcher_linux-3.2.0
url_launcher_macos-3.2.0
url_launcher_web-2.3.3
url_launcher_windows-3.1.2

**Comment by andrewkolos** [comment] 2024-09-10 05:24
Closing as duplicate of https://github.com/flutter/flutter/issues/153471 since no repro steps were provided.

**Closed by andrewkolos** 2024-09-10 05:24 UTC
Labels: tool, team-tool
