### ISSUE TITLE
`FilterQuality` is not working as expected for Hi-res images

### ISSUE THREAD

**Issue by hohlfma** [flutter/flutter#109637] opened 2022-08-16 22:12 UTC
## Details

**Target Platform:** Web
**Target OS version/browser:** Windows 11, Google Chrome 104.0.5112.81

If showing a big (high resolution) Image with `FilterQuality.medium` and changing window size back and forth, the image begins to flicker and the app performance totally collapses at some point and doesn't recover again. 

The issue seems to be related to ~~a) size of the image and~~ b) applied filters, as it did not occur for `FilterQuality.low` ~~or a significantly smaller version of the image (i.e. 90dpi instead of 300dpi)~~ (**EDIT:** Issue also happens with lower resolution image of e.g. 90dpi)

Here is a minimal test app:

```
import 'package:flutter/material.dart';
import 'package:statsfl/statsfl.dart';

void main() {
  runApp(
    StatsFl(width: 240, totalTime: 30, child: const MyApp()),
  );
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(home: ImgFilterTest());
  }
}

class ImgFilterTest extends StatelessWidget {
  const ImgFilterTest({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const Scaffold(
      body: Center(
        child: Image(
          image: AssetImage('assets/map_grey_300dpi.png'),
          width: 600,
          filterQuality: FilterQuality.medium,
        ),
      ),
    );
  }
}
```

This is the test image I was using (~1MB, 300dpi, 7656x5025), but it also "works" with other big PNG images:

<details>
<summary>Test image</summary>

![map_grey_300dpi](https://user-images.githubusercontent.com/21358685/184993433-e768dba8-a783-412f-b944-7d837b9e92c7.png)

</details>

I ran this app using:

`flutter run --profile -d chrome --web-renderer canvaskit`

And here is a screen recording showing the issue (changing app size by changing width of Chrome dev tools tab here, but the issue also happens w/o dev tools by changing the real window size):

https://user-images.githubusercontent.com/21358685/184993348-da4538e3-1a48-4f25-97e0-6fea466978c4.mp4

If I take a look in Chrome performance monitor when the issue persists, it seems like the app continuously renders the image where every rendering takes more than 300ms(!).

## Logs

<details>
<summary>Logs</summary>

```
flutter analyze
Analyzing flutter_img_filter_test...                                    
No issues found! (ran in 3.9s)
```

```
flutter doctor -v
[√] Flutter (Channel stable, 3.0.5, on Microsoft Windows [Version 10.0.22000.856], locale de-DE)
    • Flutter version 3.0.5 at C:\build_tools\flutter-3
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (5 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at C:\Users\Marvin\AppData\Local\Android\Sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 2021.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] VS Code (version 1.70.1)
    • VS Code at C:\Users\Marvin\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.46.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 104.0.5112.81
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 104.0.1293.54

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by hohlfma** [comment] 2022-08-16 22:25
Some Additions: 

1. I tried to disable the new browser image decoding stuff (using `--dart-define=BROWSER_IMAGE_DECODING_ENABLED=false`) but this had no effect and the issue stills persists

2. The issues does *not* occur when using HTML renderer (`flutter run --profile -d chrome --web-renderer html`)

**Comment by exaby73** [comment] 2022-08-18 08:03
Hello @hohlfma. In my testing, I couldn't reproduce this issue on beta and master channels. Looks like this issue is already fixed. Therefore, I am closing this issue. If you disagree, please comment and we can reopen it. Thank you.

**Comment by hohlfma** [comment] 2022-08-18 10:06
Hi @exaby73 thanks for testing! I also tried with beta branch and at leats the FPS drop issue does not occur there. But not the whole image filtering seems to has no effect on my downscaled image:

**With Flutter 3.0.5 (stable):**

![image](https://user-images.githubusercontent.com/21358685/185368011-97417b18-ae6c-4d0b-ae5f-828cec15af02.png)

**With Flutter 3.3.0-0.3.pre (beta):**

![image](https://user-images.githubusercontent.com/21358685/185368217-c98377f6-c4d6-4067-81da-324ac63d45ce.png)

As you can see, there are heavy dropouts in the downscaled image with beta release. Setting filterQuality to 'high' didn't fix that. Has image filtering been changed? If so, how can a downscaled image been effectively smoothed like with the 'medium' filtering before? Or shall I open a new issue for this?

Thanks in advance!

**Comment by exaby73** [comment] 2022-08-18 11:40
Are you experiencing this issue in master as well?

**Comment by hohlfma** [comment] 2022-08-18 12:00
Unfortunately yes: 

**With Flutter 3.1.0-0.0.pre.2349 (master):**

![image](https://user-images.githubusercontent.com/21358685/185389410-38a608c1-e09c-43dc-8db3-c3a7f61d132f.png)

**Comment by exaby73** [comment] 2022-08-18 13:34
I can reproduce this issue on web, cavaskit.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/50555895/185407204-79b7385c-47cc-4d7a-8d88-314f31f72425.png)

</details>

Same code sample as https://github.com/flutter/flutter/issues/109637#issue-1340934372

<details><summary><code>flutter doctor -v</code> (Stable)</summary>

```
[✓] Flutter (Channel stable, 3.0.5, on Microsoft Windows [Version 10.0.22000.856], locale en-IN)
    • Flutter version 3.0.5 at C:\Users\Nabeel Parkar\fvm\versions\stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (5 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\android-sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2022 17.2.6)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.2.32630.192
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2022.2
    • Flutter plugin version 69.0.5
    • Dart plugin version 222.3739.24

[✓] VS Code (version 1.70.2)
    • VS Code at C:\Users\Nabeel Parkar\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.46.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22000.856]
    • Chrome (web)      • chrome  • web-javascript • unknown
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 104.0.1293.54

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

<details><summary><code>flutter doctor -v</code> (Master)</summary>

```
[✓] Flutter (Channel master, 3.1.0-0.0.pre.2346, on Microsoft Windows [Version 10.0.22000.856], locale en-IN)
    • Flutter version 3.1.0-0.0.pre.2346 on channel master at C:\Users\Nabeel Parkar\fvm\versions\master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision adda088bcc (4 hours ago), 2022-08-17 22:59:07 -0400
    • Engine revision a77ead45a8
    • Dart version 2.19.0 (build 2.19.0-108.0.dev)
    • DevTools version 2.16.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\android-sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2022 17.2.6)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.2.32630.192
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2022.2
    • Flutter plugin version 69.0.5
    • Dart plugin version 222.3739.24

[✓] VS Code (version 1.70.2)
    • VS Code at C:\Users\Nabeel Parkar\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.46.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22000.856]
    • Chrome (web)      • chrome  • web-javascript • unknown
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 104.0.1293.54

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by hohlfma** [comment] 2022-08-18 15:46
Thank you for confirming this issue! 

I just want to highlight that the main issue for me is that `FilterQuality.medium` ist not working like before. So its not that the image is "rendered oversharpened", but not properly filtered using the requested 'medium' filter, which would produce the smooth result after downsizing.

**Comment by yjbanov** [comment] 2022-08-18 17:01
In the profile recording I see that the framework continuously pumps frames, and behind-the-scenes Skia reuploads the image to the GPU on every frame (see `textImage2D`). A high-res image would take time to upload to GPU, so it should be uploaded once and cached.

For now I am going to forward this to the framework team, since the framework controls both the frames and image caching. However, if it turns out the issue is in the web engine, feel free to put the web label back.

There may be multiple issues here, including some unexpected change in the image scaling algorithm, but I'd be more comfortable addressing them one at a time. Let's fix the inexplicable frame pumping and image reupload. If that doesn't fix scaling, we can take a look at scaling as a follow-up.

**Comment by hohlfma** [comment] 2022-08-18 17:31
Hi @yjbanov, thanks for pointing that out!

The issue regarding the fps drop was not happening with html renderer, could it still have been a framework issue then? 

But anyway, the original issue regarding the fps drop seems to be already fixed on latest 'master' and 'beta', as there are no more rendering activities after resizing the window:

![image](https://user-images.githubusercontent.com/21358685/185456987-ad983d17-edbd-4ced-bdea-e37501f45f9b.png)

But the broken scaling / filtering is new compared to Flutter 3.0.5 and that is the remaining one to be fixed.

**Comment by yjbanov** [comment] 2022-08-23 02:23
The HTML renderer doesn't actually do much with the image. It just creates an `<img>` tag and drops the image URL into it. It then reports back the size of the image, which is pretty much the only piece of information you get from the browser (e.g. if the image is animated, the framework wouldn't know). CanvasKit reports a lot more to the framework, so the framework has more data to work with, and perhaps more opportunity to fail. We need to dig into it to understand what's going on.

**Closed** 2023-04-14 15:10 UTC
Labels: severe: regression, framework, a: images, has reproducible steps, P4, found in release: 3.1, found in release: 3.3
