### ISSUE TITLE
Plugin: ImagePicker - ImagePickerDelegate.java uses unchecked or unsafe operations.

### ISSUE THREAD

**Issue by zp5r5z** [flutter/flutter#90819] opened 2021-09-27 18:22 UTC
When launching the app: Note: C:\Flutter\.pub-cache\hosted\pub.dartlang.org\image_picker-0.8.4+2\android\src\main\java\io\flutter\plugins\imagepicker\ImagePickerDelegate.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

------------------------------------------------------------------------------------------------------------------------------------
Kotlin (Gradle) 1.5.30
Flutter 2.5.1
ImagePicker ^0.8.4+2

**Comment by Josiassejod1** [comment] 2021-09-28 02:52
@zp5r5z hey, can you do a flutter -v and flutter doctor to see your current version?

**Comment by TahaTesser** [comment] 2021-09-28 09:32
duplicate of https://github.com/flutter/flutter/issues/90811

**Closed by TahaTesser** 2021-09-28 09:32 UTC
Labels: in triage
