### ISSUE TITLE
Flutter Add2App - Could not find or use auto-linked framework 

### ISSUE THREAD

**Issue by kndl22** [flutter/flutter#109534] opened 2022-08-15 13:18 UTC
Hi, 

I'm trying to integrate flutter project inside my native iOS app following the Add2App module setup.
 
My flutter project works just fine without any errors or warnings. One of the project's dependencies is [Atomic plugin](https://pub.dev/packages/atomic_transact_flutter) which is implemented as a pub dependency at the pubspec.yaml and works as expected on the Flutter side.

I'm generating my module iOS artifacts (Following this [setup guide](https://docs.flutter.dev/development/add-to-app/ios/project-setup)), using Option B: 
`flutter build ios-framework --output=some/path/MyApp/Flutter/`

Now, following the setup guide I copy the iOS module artifacts (.xcframework files) to my native iOS project and there I get the error, at the xCode:

```
Could not find or use auto-linked framework 'AtomicTransact'

Undefined symbols for architecture x86_64:
  "static AtomicTransact.Atomic.presentTransact(from: __C.UIViewController, config: AtomicTransact.AtomicConfig, environment: AtomicTransact.TransactEnvironment, presentationStyle: __C.UIModalPresentationStyle, onInteraction: ((AtomicTransact.TransactInteraction) -> ())?, onDataRequest: ((AtomicTransact.TransactDataRequest) -> ())?, onCompletion: ((AtomicTransact.TransactResponse) -> ())?) -> ()", referenced from:
      atomic_transact_flutter.SwiftAtomicTransactFlutterPlugin.handle(_: __C.FlutterMethodCall, result: (Any?) -> ()) -> () in atomic_transact_flutter(SwiftAtomicTransactFlutterPlugin.o)
```
![Screen Shot 2022-08-15 at 16 10 02](https://user-images.githubusercontent.com/6260759/184641071-efc58764-dcab-4118-9dce-ca10e400abc1.png)

It's important to mention that I have another 7 plugins .xcframeworks integrated inside the native iOS app without any issues.
The Atomic .xcframework is the only one who's causing the errors.

I was looking for something that might be unique to the Atomic plugin and found out they're using static framework (mentioned at the plugin's podspec.json file)

![Screen Shot 2022-08-15 at 16 13 48](https://user-images.githubusercontent.com/6260759/184641778-f98bd48c-26e2-4c30-8389-101d08e67815.png)

Also, the way the Atomic Pod is built looks weird but I'm not sure it's related to this error. The .xcframework file is named "atomic_transact_flutter" but the Pod name is AtomicSDK, and that's also the naming that is used at the error logs.

![Screen Shot 2022-08-15 at 16 13 23](https://user-images.githubusercontent.com/6260759/184642470-2717f618-921d-4f42-9444-c0454e56d695.png)

I reached out to Atomic tech team and they're willing to help but I'm not sure what they should change, or maybe I should change on my end.

**Edit 1:**
Tried to exclude arm64 and got the same error with different architecture:
```
ld: warning: Could not find or use auto-linked framework 'AtomicTransact'
Undefined symbols for architecture x86_64:
```
<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.5 21G72 darwin-arm, locale
    en-IL)
    • Flutter version 3.0.5 at /Users/yuval/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (5 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version
    32.1.0-rc1)
    • Android SDK at /Users/yuval/Library/Android/sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)

[✓] Connected device (1 available)
    • macOS (desktop) • macos • darwin-arm64 • macOS 12.5 21G72 darwin-arm

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by huycozy** [comment] 2022-08-15 14:29
Hi @kndl22 
From what I can see, the issue is related to a 3rd party plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/atomicfi/atomic-transact-flutter/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments, providing your `flutter run -v`,  your `pubspec.yaml`, a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that does not use 3rd party plugins and I will reopen it.
Thank you!

**Closed by huycozy** 2022-08-15 14:29 UTC
Labels: in triage

**Comment by kndl22** [comment] 2022-08-15 15:11
Hey @huycozy! Thanks for the response. It's not that I disagree, but I think this is the right place to post it.

The issue is related to Flutter itself since the iOS .xcframework is generated by Flutter and the error starts only then (Flutter app works fine). I agree that the creator might need to adjust the plugin, but in order to do that we need to understand the problem first, and that's why i opened the issue.

Since we're talking about [Add2App](https://docs.flutter.dev/development/add-to-app) functionality, there's no option for flutter run here (it's a native iOS project).

Please let me know what else I can provide and i will!

**Comment by kndl22** [comment] 2022-08-17 10:48
@huycozy?

**Comment by huycozy** [comment] 2022-08-31 11:24
Hi @kndl22. 
I'm sorry, I missed this notification until having a new notification from the bot. 
From the error message, the issue relates to `Atomic` plugins, so the first thing I recommend you to create an issue in the Atomic [repository](https://github.com/atomicfi/atomic-transact-flutter/issues).

Also, please provide your your `flutter run -v`,  your `pubspec.yaml`, a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that does not use 3rd party plugins and I will reopen the issue for further discussion.
Thank you!
