### ISSUE TITLE
Flutter driver: compute function not working

### ISSUE THREAD

**Issue by Xavjer** [flutter/flutter#48515] opened 2020-01-09 17:52 UTC
## Steps to Reproduce

1. Create an application and try to load a large JSON File (Mine has 59740 Chars) using AssetBundle during a test driver run.
2. Now split them into slices smaller than 10240 and try again, it will now work as normal and fast.

As far as I know, all Platforms/Versions are affected

## Logs

I pinpointed it down to this location within AssetBundle:

```
  Future<String> loadString(String key, { bool cache = true }) async {
    final ByteData data = await load(key);
    if (data == null)
      throw FlutterError('Unable to load asset: $key');
    if (data.lengthInBytes < 10 * 1024) {
      // 10KB takes about 3ms to parse on a Pixel 2 XL.
      // See: https://github.com/dart-lang/sdk/issues/31954
      return utf8.decode(data.buffer.asUint8List());
    }
    return **compute(_utf8decode, data, debugLabel: 'UTF8 decode for "$key"');**
  }
```

As soon as it is above 10240 in length, it will try to compute, which seems to be way slower during the test driver run (30Second timeout reached)

It is working normally in debug/profiling/release mode.

I had this issue for the past 6 months and was finally able to get by it by splitting my localization.json into 8 different files, loading them with a Promise.

**Comment by jonahwilliams** [comment] 2020-01-09 17:55
Duplicate of https://github.com/flutter/flutter/issues/24703

**Closed by jonahwilliams** 2020-01-09 17:55 UTC
