### ISSUE TITLE
WidgetSpan offsets differently for languages

### ISSUE THREAD

**Issue by rockingdice** [flutter/flutter#39296] opened 2019-08-27 04:19 UTC
I'm using WidgetSpan heavily in a Wrap Widget. The issue can be demonstrated as the following image.

![image](https://user-images.githubusercontent.com/3458134/63740332-194a7a00-c8c3-11e9-9a19-16963af7f270.png)

You should see a slight offset for the icons on the left in English. The right side looks good in Japanese. 
The issue is more obvious if you scroll to the bottom of the Wrap widget (All in one Wrap). You may notice that the icon is hovering the text.

@GaryQian might have some ideas about it?

**Comment by rockingdice** [comment] 2019-08-27 04:34
After some tests, I can confirm the issue exists for other languages. As Japanese, the offset can be easily ignored for one line. But since the offsets are accumulated, you will notice a different result after many lines.

![image](https://user-images.githubusercontent.com/3458134/63741217-b78c0f00-c8c6-11e9-8810-77a2276d9855.png)

There are about 200 lines in the above image.

**Comment by rockingdice** [comment] 2019-08-28 06:36
Thank you! I'll try the workaround.

**Comment by GaryQian** [comment] 2019-08-28 21:16
I'm going to close this for now, but feel free to come back if the workaround isn't working for you! I'll update this bug once the rounding root cause is fixed.

**Closed by GaryQian** 2019-08-28 21:16 UTC
