### ISSUE TITLE
[go_router] Bug in path_utils (blocking FirebaseAuth Email Link from terminated state)

### ISSUE THREAD

**Issue by FranRiadigos** [flutter/flutter#140593] opened 2023-12-24 21:30 UTC
### Steps to reproduce

`go_router: ^12.1.3`

1. Setup your app to use `schema://yourhost` for deeplinking and opt-in enabling `flutter_deeplinking_enabled`
2. Properly configure a `Route` that handles the` initialLocation` path `/`
3. Tap a deeplink on your phone like `https://yourhost/?mode=signIn&oobCode=xyz` that opens your App

### Expected results

The `Route` configured to handle the path `/` should be fired.

### Actual results

`[GoRouter]` No initial matches: https://yourhost?mode=signIn&oobCode=xyz

See the `/` path after `yourhost` disappeared.
Sadly, the default error screen is not either displayed.

### Code sample

<details open><summary>Bug located at path_utils.dart</summary>

```dart
[134]  // /login/?from=/ => /login?from=/
[135]  // /?from=/ => /?from=/
[136]  canon = canon.replaceFirst('/?', '?', 1);
```

That statement returns for `/?from=/` -> `?from=/`, hence the initial path `/` is completely removed.

Normally, this code would be ok because the start index is at 1, however, because the string passed to the `canonicalUri` function contains a full URI including scheme and host `https://yourhost/?...`, the start index is not relevant anymore.

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.4, on macOS 12.6.7 21G651 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] IntelliJ IDEA Community Edition (version 2023.2.2)
[✓] VS Code (version 1.85.1)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by FranRiadigos** [comment] 2023-12-24 21:42
I just saw these comments in the parser

```dart
// TODO(chunhtai): After the migration from routeInformation's location
// to uri, empty path check might be required here; see
// https://github.com/flutter/packages/pull/5113#discussion_r1374861070
// ignore: deprecated_member_use, unnecessary_non_null_assertion
configuration.findMatch(routeInformation.location!, extra: state.extra);
```

I believe once `location` is moved to `uri` it will get sorted.

However, I keep this issue open as the code displayed above doesn't seem to match the expected comments.
Up for you consideration.

cc @chunhtai

**Comment by dam-ease** [comment] 2023-12-28 09:40
Thanks for filing this @FranRiadigos. 
This seems to be a duplicate of https://github.com/flutter/flutter/issues/133928.
There is a fix which has been merged to the master channel, could you check this out on `master`?
Also, to avoid keeping duplicates, I'll suggest you comment, upvote and follow up on the original issue.

**Closed** 2024-01-18 10:09 UTC
Labels: waiting for customer response, in triage
