### ISSUE TITLE
Flutter UI freeze after returning from native with AsyncTask

### ISSUE THREAD

**Issue by Alexufo** [flutter/flutter#66713] opened 2020-09-26 04:43 UTC
1. I load android activity and cache flutter
2. I call from cache flutter and user see flutter interface
3. User press 1 and 3 buttons and all works as expected.
4. User press "open camera" and see camera (SurfaceView) with "start" button.
5. User press the start button and call flutter back from cache.
6. User see Flutter interface but it  freezed.
7. If we press native android squre button and select app again - interface will unfreeze.

In FlutterMainActivity.java on 35 please 
    ` Intent intent = new Intent(this, MainActivity.class);`
change to 
  `Intent intent = new Intent(this, test_activity.class);`
To see how problem was absent without SurfaceView and background task.

I can't understand what happens.

I create a minimal code reproduction

https://github.com/Alexufo/test_r
I run code in Studio 4.0.1

====================

```
[√] Flutter (Channel stable, 1.20.2, on Microsoft Windows [Version 10.0.18362.1082], locale ru-RU)
    • Flutter version 1.20.2 at C:\flutter
    • Framework revision bbfbf1770c (6 weeks ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1

 
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\Salo\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.49.0)
    • VS Code at C:\Users\Salo\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.14.1

[√] Connected device (1 available)
    • Mi A2 Lite (mobile) • 67808e500305 • android-arm64 • Android 10 (API 29)
```

**Comment by TahaTesser** [comment] 2020-09-28 15:26
Hi @Alexufo 
I can reproduce the issue on the latest `stable` when replacing MainActivity with test_activity, there is no freeze indeed,
However, when I tried MainActivity on the latest `master, there is no issue


### Issue

**Comment by Alexufo** [comment] 2020-09-30 05:10
Yes! It works on master channel! 
But I see another case.

start project and press  button 3.

Did you see animation (in) to page2? No. I see only animation out (back). Your video show this case.

If you will did it twice (press button 3 again) you will see animation in and out. It is a normal. But first animation after flutter start is absent.

**Comment by TahaTesser** [comment] 2020-09-30 07:26
Hi @Alexufo 
That seems to be a different issue, please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
Since this is working on the `master` channel and doesn't freeze,  Closing, fixed. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2020-09-30 07:26 UTC
Labels: in triage
