### ISSUE TITLE
CupertinoTextField will CRASH the app and not move cursor correctly by dragging space bar in Chinese or Japanese characters!

### ISSUE THREAD

**Issue by gliese667c** [flutter/flutter#61531] opened 2020-07-15 10:18 UTC
![](https://user-images.githubusercontent.com/11246312/87533687-8d526400-c6c7-11ea-86f5-43d0b8d2019b.gif)

## Reproduce Code Sample

```dart
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            CupertinoTextField(),
          ],
        ),
      ),
    );
  }
}
```

```
[✓] Flutter (Channel master, 1.20.0-8.0.pre.99, on Mac OS X 10.15.5 19F101, locale en-CN)
    • Flutter version 1.20.0-8.0.pre.99 at /Users/leslieliu/Developer/flutter
    • Framework revision f25bd9c55c (10 hours ago), 2020-07-14 20:26:01 -0400
    • Engine revision 99c2b3a245
    • Dart version 2.9.0 (build 2.9.0-21.0.dev 20bf2fcf56)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/leslieliu/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.44.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

 
[✓] Connected device (1 available)            
    • HU (mobile) • 2faa9c12bdcbab2872e2fce1b32f0949cea178b1 • ios • iOS 13.3.1

• No issues found!
```

</details>

**Comment by TahaTesser** [comment] 2020-07-15 11:06
<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel dev, 1.20.0-7.1.pre, on Mac OS X 10.15.5 19F101, locale
    en-GB)
    • Flutter version 1.20.0-7.1.pre at /Users/taha/Code/flutter_dev
    • Framework revision 7736f3bc90 (4 days ago), 2020-07-10 16:33:05 -0700
    • Engine revision d48085141c
    • Dart version 2.9.0 (build 2.9.0-21.2.beta)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/taha/Code/sdk
    • Platform android-30, build-tools 30.0.0
    • ANDROID_HOME = /Users/taha/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[✓] Connected device (5 available)
    • SM M305F (mobile)      • 32003c30dc19668f          • android-arm64  •
      Android 10 (API 29)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios            • iOS
      13.5.1
    • macOS (desktop)        • macos                     • darwin-x64     • Mac
      OS X 10.15.5 19F101
    • Web Server (web)       • web-server                • web-javascript •
      Flutter Tools
    • Chrome (web)           • chrome                    • web-javascript •
      Google Chrome 83.0.4103.116

• No issues found!
```

</details>

**Comment by gliese667c** [comment] 2020-07-17 07:14
TextField has the same problem.

**Comment by gliese667c** [comment] 2020-08-07 18:24
Hello, @TahaTesser 
All apps that use flutter crash whenever the user uses Chinese or Japanese.
Seems like no updates but I will ask anyway. Any NEW updates?

**Comment by xu-baolin** [comment] 2021-04-26 09:14
FYI @LongCatIsLooong 
```dart
Launching lib/main.dart on ***的iPhone in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: ZYWF83HY3F
Running Xcode build...
Xcode build done.                                           15.1s
Installing and launching...
Debug service listening on ws://127.0.0.1:61798/DjC9oVsHYWw=/ws
Syncing files to device ***的iPhone...
[Assert] View <(null):0x0> does not conform to UITextInput protocol
[Assert] View <(null):0x0> does not conform to UITextInput protocol
[Assert] View <(null):0x0> does not conform to UITextInput protocol
[Assert] View <(null):0x0> does not conform to UITextInput protocol
```

**Comment by justinmc** [comment] 2022-10-05 22:13
@LongCatIsLooong to verify if this was recently fixed, thanks!

**Comment by LongCatIsLooong** [comment] 2022-10-06 03:19
duplicate of https://github.com/flutter/flutter/issues/70267

**Closed by LongCatIsLooong** 2022-10-06 03:19 UTC
Labels: a: text input, severe: crash, platform-ios, framework, f: material design, a: internationalization, f: cupertino, has reproducible steps, found in release: 1.20

**Comment by gliese667c** [comment] 2022-10-11 08:27
这是来自邮箱的自动回复。来信已收到，我会尽快回复给您。
