### ISSUE TITLE
Platform.environment empty on iOS and Web.  Not on MacOS

### ISSUE THREAD

**Issue by WorikQCI** [flutter/flutter#114849] opened 2022-11-07 21:52 UTC
## Steps to Reproduce

Examine `Platform.environment`.  

* On iOS and web it is empty
* On MacOS it is not empty

1. Execute `flutter run` on the code sample 
2. ... 
3. ... 

**Expected results:** 
on iOS and web as on MacOS

**Actual results:** 

Nothing on iOS or web.

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:universal_io/io.dart' show Platform;
void main() {
  runApp(const MyApp());
}
class MyApp extends StatelessWidget {
  const MyApp({super.key});
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}
String? getPath() {
  return Platform.environment['PATH'] ?? "No path";
}
class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});
  final String title;
  @override
  State<MyHomePage> createState() => _MyHomePageState();
}
class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    List<Widget> childs = [];
    int counter = 0;
    childs.add(Text(
      "Environment",
      style: Theme.of(context).textTheme.headline1,
    ));
    for (String key in Platform.environment.keys) {
      String value = Platform.environment[key]!;
      if (value.isNotEmpty) {
        childs.add(Text("$key -> $value",
            style: Theme.of(context).textTheme.bodyText2));
        counter++;
      }
      if (counter > 6) {
        break;
      }
    }
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: childs,
        ),
      ),
    );
  }
}
```

</details>

<details>
  <summary>Logs</summary>

Attached.

```
Analyzing trash_delete_this...                                  
No issues found! (ran in 2.1s)
```

```
[✓] Flutter (Channel stable, 3.3.7, on macOS 12.6 21G115 darwin-arm, locale en-AU)
    • Flutter version 3.3.7 on channel stable at /Users/user/Documents/Flutter/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e99c9c7cd9 (6 days ago), 2022-11-01 16:59:00 -0700
    • Engine revision 857bd6b74c
    • Dart version 2.18.4
    • DevTools version 2.15.0

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Xcode - develop for iOS and macOS (Xcode 13.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13F17a
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] VS Code (version 1.73.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.52.0

[✓] Connected device (3 available)
    • IPadOfWorik (mobile) • 00008103-000229CE1E31001E • ios            • iOS 15.7 19H12
    • macOS (desktop)      • macos                     • darwin-arm64   • macOS 12.6 21G115 darwin-arm
    • Chrome (web)         • chrome                    • web-javascript • Google Chrome 107.0.5304.87
    ! Error: IPadOfWorik is busy: Fetching debug symbols for IPadOfWorik. Xcode will continue when IPadOfWorik is finished. (code -10)

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.
```
</details>

**Comment by WorikQCI** [comment] 2022-11-07 21:54
[verbose_runlog.txt](https://github.com/flutter/flutter/files/9955789/verbose_runlog.txt)

**Comment by exaby73** [comment] 2022-11-08 08:27
Hello @WorikQCI. This makes sense since on Web, you don't have access to the `dart:io` library from where this comes from, and on iOS, you wouldn't be given access to environment variables of iOS. On MacOS you can access he environment variables from the host OS. If you need environment variables, I suggest using `--dart-define` to pass environment variables to the app, that can then be accessed using [`String.fromEnvironment`](https://api.flutter.dev/flutter/dart-core/String/String.fromEnvironment.html), [`int.fromEnvironment`](https://api.flutter.dev/flutter/dart-core/int/int.fromEnvironment.html) and [`bool.fromEnvironment`](https://api.flutter.dev/flutter/dart-core/bool/bool.fromEnvironment.html).

I am closing this issue as this is working as intended. Thank you

**Closed by exaby73** 2022-11-08 08:27 UTC
Labels: in triage

**Comment by WorikQCI** [comment] 2022-11-08 19:42
> This makes sense since on Web, you don't have access to the `dart:io` library

That is why I did not use `dart::io` library.

**Comment by exaby73** [comment] 2022-11-09 07:33
[`Platform.environment`](https://api.flutter.dev/flutter/dart-io/Platform/environment.html) comes from the `dart:io` library. Which library are you using then?

**Comment by WorikQCI** [comment] 2022-11-09 19:38
> [`Platform.environment`](https://api.flutter.dev/flutter/dart-io/Platform/environment.html) comes from the `dart:io` library. Which library are you using then?

In the code example above:

`import 'package:universal_io/io.dart' show Platform;`

**Comment by exaby73** [comment] 2022-11-10 08:10
Unfortunately, `universal_io` is not an official Flutter package/plugin. But it does the same thing as what I mentioned in https://github.com/flutter/flutter/issues/114849#issuecomment-1306820581. You can't access `Platform.environment` on web, and on Android and iOS, you would not get any env variables from your host machine as it's not being run on your host machine, but on a mobile OS
