### ISSUE TITLE
Web text overflow dot rendering exception

### ISSUE THREAD

**Issue by dong-lufei** [flutter/flutter#118019] opened 2023-01-05 04:19 UTC
The web page rendering overflows, displaying vertical rectangles with a fork inside the rectangles. while the windows application renders normally

```
Container(
      alignment: Alignment.center,
      child: Text("卢卡斯的积分路上看见我看了解放昆仑山大家是扩大飞机离开七九二楼123456789" * 2,
          maxLines: 3,
          overflow: TextOverflow.ellipsis,
      )
)
```

**Comment by danagbemava-nc** [comment] 2023-01-05 08:11
Hi @dong-lufei, please provide a complete minimal reproducible code sample so that we can investigate this. 

Please also provide the output of `flutter doctor -v` as well as what you expected to happen and the actual results. 

Thank you

**Comment by dong-lufei** [comment] 2023-01-05 09:17
$ flutter doctor -v
[✓] Flutter (Channel stable, 3.3.10, on Microsoft Windows [版本 10.0.22000.1335], locale zh-CN)
    • Flutter version 3.3.10 on channel stable at D:\Program_Files\scoop\apps\flutter\current
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (3 weeks ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

Checking Android licenses is taking an unexpectedly long time...[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at D:\Program_Files\scoop\apps\android-sdk\current
    • Platform android-32, build-tools 33.0.1
    • ANDROID_HOME = D:\Program_Files\scoop\apps\android-sdk\current
    • Java binary at: D:\Program_Files\scoop\apps\android-studio\current\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2022 17.4.2)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.4.33122.133
    • Windows 10 SDK version 10.0.22000.0

[✓] Android Studio (version 2021.3)
    • Android Studio at D:\Program_Files\scoop\apps\android-studio\current
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Community Edition (version 2022.3)
    • IntelliJ at D:\IDEA
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Proxy Configuration
    • HTTP_PROXY is set
    • NO_PROXY is 127.0.0.1;localhost;::1
    • NO_PROXY contains localhost
    • NO_PROXY contains ::1
    • NO_PROXY contains 127.0.0.1

[✓] Connected device (2 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [版本 10.0.22000.1335]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 108.0.5359.95

**Comment by danagbemava-nc** [comment] 2023-01-05 13:20
Hi @dong-lufei, below is what I see when I run the code snippet you posted above in the sample app (pasted below). If the code sample is not enough to reproduce the issue, please provide a complete minimal reproducible code sample so that we can verify this. Please also share what you see and what you expected to see. 

<img width="300" alt="Screenshot 2023-01-05 at 13 18 14" src="https://user-images.githubusercontent.com/88313112/210789056-52e23194-4535-478f-852c-6c5ca3e90a82.png">

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Container(
              alignment: Alignment.center,
              child: Text(
                "卢卡斯的积分路上看见我看了解放昆仑山大家是扩大飞机离开七九二楼123456789" * 2,
                maxLines: 3,
                overflow: TextOverflow.ellipsis,
              ),
            )
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}

```
</details>

**Comment by dong-lufei** [comment] 2023-01-05 13:38
溢出打点的效果：
你上面那都没溢出，你可以把浏览器宽度调小，让他充满3行：
```
我是第一行，我是第一行，我是第一行，
我是第二行，我是第二行，我是第二行，
我是第三行，我的内容超出3行，溢出...
```

**Comment by danagbemava-nc** [comment] 2023-01-06 07:13
Hi @dong-lufei, it would appear that this has been fixed on the master channel as I cannot reproduce this over there. Can you check on the master channel to see if it works for you as well? See the screenshots below

You can use the master channel by running 

```
flutter channel master
flutter upgrade
```

| stable | master | 
| -- | -- |
| <img width="616" alt="Screenshot 2023-01-06 at 07 06 53" src="https://user-images.githubusercontent.com/88313112/210949017-c4bd6413-3b26-4cb6-8038-8e95df4b0773.png"> | <img width="616" alt="Screenshot 2023-01-06 at 07 05 07" src="https://user-images.githubusercontent.com/88313112/210949024-0fd914ec-6dda-44a6-b160-546a768606f1.png"> |


<details>
<summary>sample used</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Container(
              alignment: Alignment.center,
              constraints: const BoxConstraints(maxWidth: 300),
              child: Text(
                "卢卡斯的积分路上看见我看了解放昆仑山大家是扩大飞机离开七九二楼123456789" * 2,
                maxLines: 3,
                overflow: TextOverflow.ellipsis,
              ),
            )
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}

```
</details>

**Comment by dong-lufei** [comment] 2023-01-06 07:45
Switching from the stable branch to the main branch reports an error

```
$ flutter channel master
Switching to flutter channel 'master'...
git: error: Your local changes to the following files would be overwritten by checkout:
git:    packages/flutter/lib/src/widgets/widget_inspector.dart
git: Please commit your changes or stash them before you switch branches.
git: Aborting
Switching channels failed with error code 1.
```

**Comment by danagbemava-nc** [comment] 2023-01-06 12:26
Hi @dong-lufei, you have made changes to `packages/flutter/lib/src/widgets/widget_inspector.dart` which is the tool cannot change the channel. If the change is not intended, kindly roll back to the original state of the file, otherwise stage the changes somewhere and try again. 

Thank you

**Comment by dong-lufei** [comment] 2023-01-07 05:04
I don't have git init in my project yet, so I can't roll back. In the above question, you said that as long as I switch to the master, it will be fine, but I failed to operate, how to operate or whether the updated stable version can solve the above text overflow problem

**Comment by danagbemava-nc** [comment] 2023-01-09 06:11
Hi @dong-lufei, the change isn't in your project but in one of the flutter source files. The flutter tool uses git so you can roll back the change you made to that particular file. You should be able to see this by navigating to your flutter director and running `git status`. 
 
> you said that as long as I switch to the master, it will be fine

I asked you to switch to master to check if it works as expected for you since I'm not familiar with how it should behave in your native language. 


Thank you

**Comment by danagbemava-nc** [comment] 2023-01-10 07:21
Given that it seems this issue has been fixed on the master channel I'll be closing this per our triage policy. 

The fix for this should make it to stable sometime in the future. 

If you still face this issue on the master channels or newer kindly file a new issue and provide detailed information required to reproduce. 

Closing as fixed.

Thank you

**Closed by danagbemava-nc** 2023-01-10 07:21 UTC
Labels: in triage
