### ISSUE TITLE
3D View Like swiftui

### ISSUE THREAD

**Issue by rajfrantic** [flutter/flutter#147117] opened 2024-04-20 12:50 UTC
### Use case

I am building a app where i want some 3D objects when user interact with the object it animate, right now I am unable to do this,
From This The UX part of app will enhance and flutter will more popular.
At this time all developer and user want something different in apps they want 3D feel,

### Proposal

All some library to build 3D object or you can implement 3D view in Custompaint

**Comment by iapicca** [comment] 2024-04-21 09:27
aren't there 3rd party packages for this?
https://pub.dev/packages/flutter_cube
https://www.geeksforgeeks.org/how-to-use-3d-models-in-flutter/

**Comment by rajfrantic** [comment] 2024-04-22 06:29
flutter_club is not support latest version of flutter. Last update of this package is 3 year ago

**Comment by danagbemava-nc** [comment] 2024-04-22 08:48
Closing this as a duplicate of https://github.com/flutter/flutter/issues/58145

**Closed by danagbemava-nc** 2024-04-22 08:48 UTC
Labels: in triage
