### ISSUE TITLE
[google_maps_flutter] Maps with strange behavior when dragging on 120Hz android devices

### ISSUE THREAD

**Issue by pietroid** [flutter/flutter#135763] opened 2023-09-29 18:36 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Since some days ago, for devices with 120Hz frame rate, when using it on 60Hz mode, it has this strange behavior when dragging the map. Also it happens on battery saver mode (on my Android Xiaomi Note 7 device):

https://github.com/flutter/flutter/assets/22605271/12ecbad5-f0c9-469c-adc6-adf8e83a8642

I Isolated everything I could, but this still happened even for past versions of our app.

Also tested it on other apps that uses google maps and it's having the same strange behavior:

https://github.com/flutter/flutter/assets/22605271/ce9ff468-d08a-43be-9807-1a0c11b64c60

### Expected results

Map must move smoothly

### Actual results

Map is moving in a glitchy way, markers and background oscillates when user is dragging the map.

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.7.7, on macOS 13.5 22G74 darwin-arm64, locale pt-BR)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] VS Code (version 1.82.0)
[✓] Connected device (3 available)
[✓] HTTP Host Availability
```

</details>

**Comment by darshankawar** [comment] 2023-10-02 06:50
Thanks for the report @pietroid 

> for devices with 120Hz frame rate, when using it on 60Hz mode

Can you elaborate how are you achieving this ? 

Also, can you try on other devices and check if you get same behavior ?

You can use the [plugin example](https://github.com/flutter/packages/tree/main/packages/google_maps_flutter/google_maps_flutter/example) and see if the behavior persists on affected and other devices.

**Comment by pietroid** [comment] 2023-10-04 21:42
Hello @darshankawar, thanks for the response! I just reproduced with latest `google_maps_flutter` version, run the example project, and had this same problem. 

I noticed this log here. Renderer seem to be set as null for some reason, and this `GoogleCertificatesRslt` exception is thrown. Might be related: 
![image](https://github.com/flutter/flutter/assets/22605271/9a627052-d17a-4da6-a9f7-c79e0c4099df)

I just reported this problem for google maps android SDK team, because even switching project API Keys it kept happening and by my researches it should not throw this exception with the latest renderer. So somethings seems off on their side:

https://issuetracker.google.com/issues/303474261

**Comment by darshankawar** [comment] 2023-10-05 05:13
Thanks for the update and linking the related google issue @pietroid 
I see another similar issue reported here that you can check https://github.com/flutter/flutter/issues/135929 and see if you can follow-up in it for further updates.

**Comment by pietroid** [comment] 2023-10-05 12:29
Attaching evidences of this happening on Flutter example project (I just download the example from the packages - version 2.5.0 - and put my API Key):

Devices this happen tested so far:
- Redmi note 7 (on battery saver mode)
- Redmi note 10 Pro (it has 120Hz screen refresh rate by default)
- Samsung galaxy S21 Plus (it has 120Hz screen refresh rate by default)

https://github.com/flutter/flutter/assets/22605271/81cac873-6053-49a8-a1f0-566a65e651ca

I also noticed that when running directly from a native Android app (using example they provide on the [documentation](https://developers.google.com/maps/documentation/android-sdk/map?hl=pt-br)), this problem doesn't happen (even having the same exception as I reported):

https://github.com/flutter/flutter/assets/22605271/be82a6a7-ddb4-4e35-be34-16758e1ed09c

So, for me it is clear that:

- This exception and `latestRenderer = null` happens on native side, independent of which version we use (and we can leave that for google maps android team to investigate).
- There is a problem probably with the `PlatformView` from flutter (because on pure native maps it works okay). It might be related to the certificate exception, but we are not really sure.

But, in conclusion, there is something on flutter side that must be done. Can you guys prioritize this? It's not clear for me how we can proceed the investigation, because I seem to have reached the limit of my understanding with flutter + native integration, I think this exception has something to do but I don't have the tools necessary to debug the platform view and native side integration.

Also, this is impacting users on Play store, we are already receiving some complaints.

**Comment by darshankawar** [comment] 2023-10-06 05:48
Thanks for the updates. Seeing the same behavior as reported in https://github.com/flutter/flutter/issues/135763#issuecomment-1748800240

<details>
<summary> stable, master flutter doctor -v </summary>

```
[!] Flutter (Channel stable, 3.13.6, on macOS 12.2.1 21D62 darwin-x64, locale
    en-GB)
    • Flutter version 3.13.6 on channel stable at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ead455963c (5 days ago), 2023-09-26 18:28:17 -0700
    • Engine revision a794cf2681
    • Dart version 3.1.3
    • DevTools version 2.25.0
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

[!] Flutter (Channel master, 3.16.0-5.0.pre.21, on macOS 12.2.1 21D62
    darwin-x64, locale en-GB)
    • Flutter version 3.16.0-5.0.pre.21 on channel master at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision bf1cdb1596 (6 hours ago), 2023-10-05 19:05:27 -0400
    • Engine revision 6492e1f8c3
    • Dart version 3.2.0 (build 3.2.0-231.0.dev)
    • DevTools version 2.28.1
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/dhs/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13C100
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 65.1.4
    • Dart plugin version 213.7228

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (3 available)
    • Darshan's iphone (mobile) • 21150b119064aecc249dfcfe05e259197461ce23 • ios
      • iOS 15.3.1 19D52
    • macOS (desktop)           • macos                                    •
      darwin-x64     • macOS 12.2.1 21D62 darwin-x64
    • Chrome (web)              • chrome                                   •
      web-javascript • Google Chrome 109.0.5414.119

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
      
[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.



```

</details>

**Comment by dayron9110** [comment] 2023-10-06 18:21
Same issue here, we have observed this behavior on different cell phones such as Motorola, Xiaomi, Realme and Samsung.

**Comment by stuartmorgan** [comment] 2023-10-10 19:36
> Also tested it on other apps that uses google maps and it's having the same strange behavior

Do you only see it in other Flutter apps that use Google Maps, or *all* Android apps that use Google Maps?

**Comment by pietroid** [comment] 2023-10-10 19:39
> Do you only see it in other Flutter apps that use Google Maps, or _all_ Android apps that use Google Maps?

I saw only for other Flutter apps (Realtor is an example of flutter app that I tested). On what seems to be native Android apps I haven't seen this issue. Please take a look on this comment https://github.com/flutter/flutter/issues/135763#issuecomment-1748800240 where I provide detailed description where it's reproducible or not.

**Comment by johnmccutchan** [comment] 2023-10-18 22:20
AFAICT this is a duplicate of: https://github.com/flutter/flutter/issues/135888

Closing this issue to avoid splitting information between the two issues.

**Closed by johnmccutchan** 2023-10-18 22:20 UTC
Labels: platform-android, a: platform-views, p: maps, package, has reproducible steps, team-android, found in release: 3.13, found in release: 3.16
