### ISSUE TITLE
ExpansionPanel potential bug

### ISSUE THREAD

**Issue by andytwoods** [flutter/flutter#24210] opened 2018-11-10 12:57 UTC
Hi, afraid I'm rather a newbie with Flutter. This may be a bug. Could well be I'm borking something though.
Best, 
Andy.

## Steps to Reproduce

Here is a gist demonstrating the bug https://gist.github.com/andytwoods/13c56c196bf50558f1a6979b983c326b

Dynamically adding a new panel with isExpanded = true, I don't get the expected gap. 
![image](https://user-images.githubusercontent.com/595166/48301558-cc3e1880-e4e7-11e8-9986-85b044101462.png)

Selecting minify, leads to this bug: 
![image](https://user-images.githubusercontent.com/595166/48301570-fb548a00-e4e7-11e8-88d5-3e3e3fc04cfd.png)

```
C:\Users\andytwoods\IdeaProjects\gear_log>flutter doctor -v
[√] Flutter (Channel unknown, v0.9.4, on Microsoft Windows [Version 10.0.17134.345], locale en-GB)
    • Flutter version 0.9.4 at C:\src\flutter
    • Framework revision f37c235c32 (7 weeks ago), 2018-09-25 17:45:40 -0400
    • Engine revision 74625aed32
    • Dart version 2.1.0-dev.5.0.flutter-a2eb050044

[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at C:\Users\andytwoods\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = C:\Users\andytwoods\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[√] Android Studio (version 3.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[√] IntelliJ IDEA Ultimate Edition (version 2018.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2018.2.4
    • Flutter plugin version 29.1.3
    • Dart plugin version 182.4999

[√] Connected devices (1 available)
    • Android SDK built for x86 64 • emulator-5554 • android-x64 • Android 9 (API 28) (emulator)

• No issues found!
```

```
Log: 
I/flutter ( 7452): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 7452): The following assertion was thrown building ExpansionPanelList(state:
I/flutter ( 7452): _ExpansionPanelListState#72d5c):
I/flutter ( 7452): 'package:flutter/src/material/mergeable_material.dart': Failed assertion: line 443 pos 18:
I/flutter ( 7452): '_children[j] is MaterialGap': is not true.
I/flutter ( 7452): 
I/flutter ( 7452): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter ( 7452): more information in this error message to help you determine and fix the underlying cause.
I/flutter ( 7452): In either case, please report this assertion by filing a bug on GitHub:
I/flutter ( 7452):   https://github.com/flutter/flutter/issues/new
I/flutter ( 7452): 
I/flutter ( 7452): When the exception was thrown, this was the stack:
I/flutter ( 7452): #2      _MergeableMaterialState.didUpdateWidget (package:flutter/src/material/mergeable_material.dart:443:18)
I/flutter ( 7452): #3      StatefulElement.update (package:flutter/src/widgets/framework.dart:3820:58)
I/flutter ( 7452): #4      Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter ( 7452): #5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter ( 7452): #6      Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter ( 7452): #7      StatefulElement.update (package:flutter/src/widgets/framework.dart:3835:5)
I/flutter ( 7452): #8      Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter ( 7452): #9      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter ( 7452): #10     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter ( 7452): #11     ProxyElement.update (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter ( 7452): #12     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter ( 7452): #13     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter ( 7452): #14     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter ( 7452): #15     ProxyElement.update (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter ( 7452): #16     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter ( 7452): #17     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter ( 7452): #18     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter ( 7452): #19     StatelessElement.update (package:flutter/src/widgets/framework.dart:3738:5)
I/flutter ( 7452): #20     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter ( 7452): #21     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4803:14)
I/flutter ( 7452): #22     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter ( 7452): #23     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter ( 7452): #24     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter ( 7452): #25     StatelessElement.update (package:flutter/src/widgets/framework.dart:3738:5)
I/flutter ( 7452): #26     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter ( 7452): #27     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter ( 7452): #28     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter ( 7452): #29     ProxyElement.update (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter ( 7452): #30     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter ( 7452): #31     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4803:14)
I/flutter ( 7452): #32     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter ( 7452): #33     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter ( 7452): #34     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter ( 7452): #35     StatelessElement.update (package:flutter/src/widgets/framework.dart:3738:5)
I/flutter ( 7452): #36     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter ( 7452): #37     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4803:14)
I/flutter ( 7452): #38     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter ( 7452): #39     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter ( 7452): #40     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter ( 7452): #41     ProxyElement.update (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter ( 7452): #42     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter ( 7452): #43     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4803:14)
I/flutter ( 7452): #44     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter ( 7452): #45     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4803:14)
I/flutter ( 7452): #46     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter ( 7452): #47     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4803:14)
I/flutter ( 7452): #48     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter ( 7452): #49     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4803:14)
I/flutter ( 7452): #50     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter ( 7452): #51     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter ( 7452): #52     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter ( 7452): #53     StatefulElement.update (package:flutter/src/widgets/framework.dart:3835:5)
I/flutter ( 7452): #54     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter ( 7452): #55     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4803:14)
I/flutter ( 7452): #56     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter ( 7452): #57     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4803:14)
I/flutter ( 7452): #58     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter ( 7452): #59     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4803:14)
I/flutter ( 7452): #60     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter ( 7452): #61     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4803:14)
I/flutter ( 7452): #62     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter ( 7452): #63     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter ( 7452): #64     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter ( 7452): #65     StatelessElement.update (package:flutter/src/widgets/framework.dart:3738:5)
I/flutter ( 7452): #66     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter ( 7452): #67     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter ( 7452): #68     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter ( 7452): #69     StatefulElement.update (package:flutter/src/widgets/framework.dart:3835:5)
I/flutter ( 7452): #70     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter ( 7452): #71     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter ( 7452): #72     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter ( 7452): #73     StatefulElement.update (package:flutter/src/widgets/framework.dart:3835:5)
I/flutter ( 7452): #74     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter ( 7452): #75     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter ( 7452): #76     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter ( 7452): #77     ProxyElement.update (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter ( 7452): #78     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter ( 7452): #79     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter ( 7452): #80     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter ( 7452): #81     StatelessElement.update (package:flutter/src/widgets/framework.dart:3738:5)
I/flutter ( 7452): #82     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter ( 7452): #83     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter ( 7452): #84     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter ( 7452): #85     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2273:33)
I/flutter ( 7452): #86     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:673:20)
I/flutter ( 7452): #87     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
I/flutter ( 7452): #88     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter ( 7452): #89     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter ( 7452): #90     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
I/flutter ( 7452): #91     _invoke (dart:ui/hooks.dart:139:13)
I/flutter ( 7452): #92     _drawFrame (dart:ui/hooks.dart:128:3)
I/flutter ( 7452): (elided 2 frames from class _AssertionError)
I/flutter ( 7452): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by xqwzts** [comment] 2018-11-19 16:19
```
//        List<MinimalModel> items = [MinimalModel(),MinimalModel()];
//
//          Timer(Duration(milliseconds: 500), (){ 
//            items.add(MinimalModel()); //should be wrapped with setState
//          });
//
// return ExpansionPanelIssue(items);
```

The problem is that you're passing in a `List` to the widget here: `ExpansionPanelIssue(items);`. Then modifying that list after it's been passed in and the `ExpansionPanelIssue` widget has done its initialization.

When passing in a List to a widget you should always treat it as an immutable structure. If you need to add or remove items, you should rather create a new List and have your build pass that in again [via `setState()`].

Quick pseudo code of a possible solution:

```
// StatefulWidget/State

List<MinimalModel> items;

@override
initState() {
  super.initState();
  items =  [MinimalModel(),MinimalModel()];
  _scheduleItemAddition();
}

void _scheduleItemAddition() {
  Timer(const Duration(milliseconds: 500), (){ 
    setState(() => items = new List.from(items)..add(MinimalModel()));
  });
}

@override
Widget build(BuildContext context) {
  return new ExpansionPanelIssue(items);
}
```

**Comment by andytwoods** [comment] 2018-11-20 10:59
Many thanks for the help :)
Afraid though I get an unchanging list adopting this setState way. Very likely that it's again a newbie mistake. Don't suppose you could eyeball my code below? Many thanks.

`// Copyright 2016 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

import 'dart:async';

import 'package:flutter/material.dart';

class MinimalModel {
  final selected = true;
}

class DemoIssue extends StatefulWidget {

  DemoIssue();

  @override
  _DemoIssueState createState() {
    return _DemoIssueState();
  }

}

class _DemoIssueState extends State<DemoIssue>{

  List<MinimalModel> items;

  @override
  Widget build(BuildContext context){
    return new ExpansionPanelIssue(items);
  }

  @override
  void initState() {
    items = [MinimalModel(),MinimalModel()];
    _scheduleItemAddition();
  }

  void _scheduleItemAddition() {
    Timer.periodic(const Duration(milliseconds: 500), (Timer t){
      setState(() => items = new List.from(items)..add(MinimalModel()));
      print('added');
    });
  }
}

class ExpansionPanelIssue extends StatefulWidget {
  static const String routeName = '/material/expansion_panels';

  final List<MinimalModel> minimalModel;

  ExpansionPanelIssue(List<MinimalModel> this.minimalModel);

  @override
  _ExpansionPanelIssue createState() {
    return _ExpansionPanelIssue(minimalModel);
  }
}

class _ExpansionPanelIssue extends State<ExpansionPanelIssue> {
  List<MinimalModel> _shoePairs;

  _ExpansionPanelIssue(this._shoePairs);

  @override
  Widget build(BuildContext context) {
    return SingleChildScrollView(
        child: SafeArea(
            top: false,
            bottom: false,
            child: Container(
              margin: const EdgeInsets.all(24.0),
              child: Theme(
                data: Theme.of(context).copyWith(cardColor: Colors.white),
                child: ExpansionPanelList(
                    expansionCallback: (int index, bool isExpanded) {
                      setState(() {});
                    },
                    children: _shoePairs.map<ExpansionPanel>(
                      (MinimalModel minimalModel) {
                        return ExpansionPanel(
                            isExpanded: minimalModel.selected,
                            headerBuilder:
                                (BuildContext context, bool isExpanded) {
                              return Container(child: Text('my header'));
                            },
                            body: Text('my body'));
                      },
                    ).toList()),
              ),
            )));
  }
}
`

**Comment by UnaDeKalamares** [comment] 2019-01-03 12:56
Hello! I wanted to report a very similar exception. In my case, it involves dynamically adding and deleting nested ExpansionPanel items, but only in certain order... You can reproduce the error with the following code:

```
import 'package:flutter/material.dart';

class SampleWidget extends StatefulWidget {
  @override
  State<StatefulWidget> createState() {
    return SampleState();
  }

}

class SampleState extends State<StatefulWidget> {

  final formKey = GlobalKey<FormState>();

  List<ExpandableItem<List<ExpandableItem<String>>>> items = List();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: Text("Sample"),
        ),
        body: Center(
          child: ListView(
            children: <Widget>[
              Padding(
                padding: EdgeInsets.all(15.0),
                child: Column(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: <Widget>[

                    ExpansionPanelList(
                      expansionCallback: (int parentIndex, bool isExpanded) {
                        setState(() {
                          items[parentIndex].isExpanded = !items[parentIndex].isExpanded;
                        });
                      },
                      children: items.map((ExpandableItem<List<ExpandableItem<String>>> parentItem) {
                        return ExpansionPanel(
                          headerBuilder: (BuildContext context, bool isExpanded) {
                            return Row(
                              children: <Widget>[
                                Expanded(
                                  child: Text("Parent " + items.indexOf(parentItem).toString()),
                                ),
                                IconButton(icon: Icon(Icons.delete), onPressed: () => onDeleteParent(items.indexOf(parentItem)))
                              ]
                            );
                          },
                          isExpanded: parentItem.isExpanded,
                          body: Column(
                            children: <Widget>[
                              ExpansionPanelList(
                                expansionCallback: (int childIndex, bool isExpanded) {
                                  setState(() {
                                    parentItem.item[childIndex].isExpanded = !parentItem.item[childIndex].isExpanded;
                                  });
                                },
                                children: parentItem.item.map((ExpandableItem<String> childItem) {
                                  return ExpansionPanel(
                                    headerBuilder: (BuildContext context, bool isExpanded) {
                                      return Row(
                                        children: <Widget>[
                                          Expanded(
                                            child: Text("Child " + parentItem.item.indexOf(childItem).toString()),
                                          ),
                                          IconButton(icon: Icon(Icons.delete), onPressed: () => onDeleteChild(parentItem.item, parentItem.item.indexOf(childItem)))
                                        ]
                                      );
                                    },
                                    isExpanded: childItem.isExpanded,
                                    body: Text(childItem.item)
                                  );
                                }).toList(),
                              ),
                              IconButton(icon: Icon(Icons.add), onPressed: () => onAddChild(parentItem.item))
                            ],
                          )
                        );
                      }).toList(),
                    ),
                    IconButton(icon: Icon(Icons.add), onPressed: onAddParent)
                  ],
                ),
              )
            ],
          ),
        ),
      );
  }

  void onAddParent() {
    setState(() {
      ExpandableItem<List<ExpandableItem<String>>> parent = ExpandableItem();
      parent.item = List();
      items.add(parent);
    });
  }

  void onDeleteParent(int position) {
    setState(() {
      items.removeAt(position);
    });
  }

  void onAddChild(List<ExpandableItem<String>> childItem) {
    setState(() {
      ExpandableItem<String> child = ExpandableItem();
      child.item = "Child content " + childItem.length.toString();
      childItem.add(child);
    });
  }

  void onDeleteChild(List<ExpandableItem<String>> childItem, int position) {
    setState(() {
      childItem.removeAt(position);
    });
  }

}

class ExpandableItem<T> {
  bool isExpanded = false;
  T item;
}
```

In order to experience the issue, do the following:

1. Add a parentItem, and expand it;
2. Add a childItem;
3. Add a second parentItem (the first one will still be expanded);
4. Delete the childItem created before.

If you alter these steps, the issue does not happen. For example, this sequence does work as expected:

1. Add a parentItem, and expand it;
2. Add a childItem;
3. Collapse the parentItem;
4. Add a second parentItem;
5. You can expand the first parentItem and delete its child.

It doesn't matter from which position you try the first sequence, it will always cause an exception.

I hope that helps!

**Comment by zoechi** [comment] 2019-01-31 07:46
Duplicate of #13780

**Closed** 2019-01-31 07:52 UTC
Labels: f: material design, framework, severe: crash

**Comment by sandeepng9** [comment] 2019-09-09 06:39
hi, how can we open only one ExpansionPanel at a time? 
please suggest 
Thanks :)
