### ISSUE TITLE
issue with named routes eventhough I have no home property in MaterialApp

### ISSUE THREAD

**Issue by MuhammamdArslanKhan** [flutter/flutter#48024] opened 2019-12-31 21:37 UTC
I have updated flutter from version1.7.8+hotfix.4 to latest version (Channel stable, v1.12.13+hotfix.5). it was working fine on prev version of flutter.
I have removed home property but still shows exception

```console
>  flutter doctor
>Doctor summary (to see all details, run flutter doctor -v):
>[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.18362.476], locale en-US)

>[√] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
>[√] Android Studio (version 3.5)
>[√] VS Code, 64-bit edition (version 1.41.1)
>[√] Connected device (1 available)
```

## Steps to Reproduce

```dart   
 void main() => runApp(
  new MaterialApp(

  debugShowCheckedModeBanner: false,
    theme: new ThemeData(
      fontFamily: 'OpenSans-Light'
    ),
initialRoute: "/",
    routes: <String, WidgetBuilder>{
      LOGIN_OTP_SCREEN: (BuildContext context) => new LoginOTP(),
      OTP_SCREEN: (BuildContext context) => new OtpPage(),
      LOGIN_SCREEN:(BuildContext context) => LoginPage(),
       HOME_SCREEN:(BuildContext context) => HomePage()
    }

));


const String
LOGIN_OTP_SCREEN = '/',
    OTP_SCREEN = '/OtpPage',
     LOGIN_SCREEN='/LoginPage',
      HOME_SCREEN='/HomePage',
      EMAIL_ADDRESS_SCREEN='/EmailAddingScreen';
```

**Target Platform:** Android 7.1 (Nougat) - API 25  
**Target OS version/browser:** 7.1 (Nougat) - API 25
**Devices:** Emulator version(27.3.10-4969155)

![flutter_error](https://user-images.githubusercontent.com/16595091/71634864-4e842180-2c41-11ea-9d0d-16bc805abe63.png)

```bash
flutter run
Using hardware rendering with device Android SDK built for x86 64. If you get graphics artifacts, consider enabling software rendering with
"--enable-software-rendering".
Launching lib\main.dart on Android SDK built for x86 64 in debug mode...
I/flutter (17295): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (17295): The following assertion was thrown building MaterialApp(dirty, state: _MaterialAppState#a184a):     
I/flutter (17295): If the home property is specified, the routes table cannot include an entry for "/", since it would 
I/flutter (17295): be redundant.
I/flutter (17295): 'package:flutter/src/widgets/app.dart':
I/flutter (17295): Failed assertion: line 172 pos 10: 'home == null ||
I/flutter (17295):          !routes.containsKey(Navigator.defaultRouteName)'
I/flutter (17295):
I/flutter (17295): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (17295): more information in this error message to help you determine and fix the underlying cause.
I/flutter (17295): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (17295):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter (17295):
I/flutter (17295): The relevant error-causing widget was:
I/flutter (17295):   MaterialApp file:///D:/T%20Mobile/Flutter%20Projects/mookodog/lib/main.dart:10:7
I/flutter (17295):
I/flutter (17295): When the exception was thrown, this was the stack:
I/flutter (17295): #2      new WidgetsApp (package:flutter/src/widgets/app.dart:172:10)
I/flutter (17295): #3      _MaterialAppState.build (package:flutter/src/material/app.dart:552:21)
I/flutter (17295): #4      StatefulElement.build (package:flutter/src/widgets/framework.dart:4334:27)
I/flutter (17295): #5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4223:15)
I/flutter (17295): #6      Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (17295): #7      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
I/flutter (17295): #8      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4381:11)
I/flutter (17295): #9      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
I/flutter (17295): #10     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
I/flutter (17295): #11     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
I/flutter (17295): #12     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1028:16)
I/flutter (17295): #13     RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:999:5)
I/flutter (17295): #14     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:942:17)
I/flutter (17295): #15     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2412:19)
I/flutter (17295): #16     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:941:13)
I/flutter (17295): #17     WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:819:7)
I/flutter (17295): #18     WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:804:7)
I/flutter (17295): #27     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:384:19)
I/flutter (17295): #28     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:418:5)
I/flutter (17295): #29     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
I/flutter (17295): (elided 10 frames from class _AssertionError, package dart:async, and package dart:async-patch)
I/flutter (17295):
I/flutter (17295): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (17607): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (17607): The following assertion was thrown building MaterialApp(dirty, state: _MaterialAppState#bf3e7):
I/flutter (17607): If the home property is specified, the routes table cannot include an entry for "/", since it would
I/flutter (17607): be redundant.
I/flutter (17607): 'package:flutter/src/widgets/app.dart':
I/flutter (17607): Failed assertion: line 172 pos 10: 'home == null ||
I/flutter (17607):          !routes.containsKey(Navigator.defaultRouteName)'
I/flutter (17607):
I/flutter (17607): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (17607): more information in this error message to help you determine and fix the underlying cause.
I/flutter (17607): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (17607):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter (17607):
I/flutter (17607): The relevant error-causing widget was:
I/flutter (17607):   MaterialApp file:///D:/T%20Mobile/Flutter%20Projects/mookodog/lib/main.dart:10:7
I/flutter (17607):
I/flutter (17607): When the exception was thrown, this was the stack:   
I/flutter (17607): #2      new WidgetsApp (package:flutter/src/widgets/app.dart:172:10)
I/flutter (17607): #3      _MaterialAppState.build (package:flutter/src/material/app.dart:552:21)
I/flutter (17607): #4      StatefulElement.build (package:flutter/src/widgets/framework.dart:4334:27)
I/flutter (17607): #5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4223:15)
I/flutter (17607): #6      Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (17607): #7      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
I/flutter (17607): #8      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4381:11)
I/flutter (17607): #9      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
I/flutter (17607): #10     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
I/flutter (17607): #11     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
I/flutter (17607): #12     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1028:16)
I/flutter (17607): #13     RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:999:5)
I/flutter (17607): #14     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:942:17)
I/flutter (17607): #15     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2412:19)
I/flutter (17607): #16     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:941:13)
I/flutter (17607): #17     WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:819:7)
I/flutter (17607): #18     WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:804:7)
I/flutter (17607): #27     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:384:19)
I/flutter (17607): #28     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:418:5)
I/flutter (17607): #29     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
I/flutter (17607): (elided 10 frames from class _AssertionError, package dart:async, and package dart:async-patch)
I/flutter (17607):
I/flutter (17607): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (17798): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (17798): The following assertion was thrown building MaterialApp(dirty, state: _MaterialAppState#ca0fa):
I/flutter (17798): If the home property is specified, the routes table cannot include an entry for "/", since it would
I/flutter (17798): be redundant.
I/flutter (17798): 'package:flutter/src/widgets/app.dart':
I/flutter (17798): Failed assertion: line 172 pos 10: 'home == null ||  
I/flutter (17798):          !routes.containsKey(Navigator.defaultRouteName)'
I/flutter (17798):
I/flutter (17798): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (17798): more information in this error message to help you determine and fix the underlying cause.
I/flutter (17798): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (17798):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter (17798):
I/flutter (17798): The relevant error-causing widget was:
I/flutter (17798):   MaterialApp file:///D:/T%20Mobile/Flutter%20Projects/mookodog/lib/main.dart:10:7
I/flutter (17798):
I/flutter (17798): When the exception was thrown, this was the stack:
I/flutter (17798): #2      new WidgetsApp (package:flutter/src/widgets/app.dart:172:10)
I/flutter (17798): #3      _MaterialAppState.build (package:flutter/src/material/app.dart:552:21)
I/flutter (17798): #4      StatefulElement.build (package:flutter/src/widgets/framework.dart:4334:27)
I/flutter (17798): #5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4223:15)
I/flutter (17798): #6      Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (17798): #7      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
I/flutter (17798): #8      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4381:11)
I/flutter (17798): #9      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
I/flutter (17798): #10     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
I/flutter (17798): #11     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
I/flutter (17798): #12     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1028:16)
I/flutter (17798): #13     RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:999:5)
I/flutter (17798): #14     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:942:17)
I/flutter (17798): #15     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2412:19)
I/flutter (17798): #16     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:941:13)
I/flutter (17798): #17     WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:819:7)
I/flutter (17798): #18     WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:804:7)
I/flutter (17798): #27     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:384:19)
I/flutter (17798): #28     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:418:5)
I/flutter (17798): #29     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
I/flutter (17798): (elided 10 frames from class _AssertionError, package dart:async, and package dart:async-patch)
I/flutter (17798):
I/flutter (17798): ════════════════════════════════════════════════════════════════════════════════════════════════════
Running Gradle task 'assembleDebug'...                                  
Running Gradle task 'assembleDebug'... Done                         6.2s
√ Built build\app\outputs\apk\debug\app-debug.apk.
I/flutter (17892): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (17892): The following assertion was thrown building MaterialApp(dirty, state: _MaterialAppState#7ab88):
I/flutter (17892): If the home property is specified, the routes table cannot include an entry for "/", since it would
I/flutter (17892): be redundant.
I/flutter (17892): 'package:flutter/src/widgets/app.dart':
I/flutter (17892): Failed assertion: line 172 pos 10: 'home == null ||
I/flutter (17892):          !routes.containsKey(Navigator.defaultRouteName)'
I/flutter (17892): 
I/flutter (17892): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (17892): more information in this error message to help you determine and fix the underlying cause.
I/flutter (17892): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (17892):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter (17892):
I/flutter (17892): The relevant error-causing widget was:
I/flutter (17892):   MaterialApp file:///D:/T%20Mobile/Flutter%20Projects/mookodog/lib/main.dart:10:7
I/flutter (17892):
I/flutter (17892): When the exception was thrown, this was the stack:
I/flutter (17892): #2      new WidgetsApp (package:flutter/src/widgets/app.dart:172:10)
I/flutter (17892): #3      _MaterialAppState.build (package:flutter/src/material/app.dart:552:21)
Syncing files to device Android SDK built for x86 64...                 
I/flutter (17892): #4      StatefulElement.build (package:flutter/src/widgets/framework.dart:4334:27)
I/flutter (17892): #5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4223:15)    
I/flutter (17892): #6      Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (17892): #7      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
I/flutter (17892): #8      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4381:11)
I/flutter (17892): #9      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
I/flutter (17892): #10     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
I/flutter (17892): #11     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
I/flutter (17892): #12     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1028:16)
I/flutter (17892): #13     RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:999:5)
I/flutter (17892): #14     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:942:17)
I/flutter (17892): #15     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2412:19)
I/flutter (17892): #16     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:941:13)
I/flutter (17892): #17     WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:819:7)
I/flutter (17892): #18     WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:804:7)
I/flutter (17892): #27     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:384:19)
I/flutter (17892): #28     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:418:5)
I/flutter (17892): (elided 10 frames from class _AssertionError, package dart:async, and package dart:async-patch)
I/flutter (17892):
I/flutter (17892): ════════════════════════════════════════════════════════════════════════════════════════════════════
Syncing files to device Android SDK built for x86 64...         12,502ms (!)

�🔥  To hot reload changes while running, press "r". To hot restart (and rebuild state), press "R".
An Observatory debugger and profiler on Android SDK built for x86 64 is available at: http://127.0.0.1:65451/9JXCzTpeiEg=/
For a more detailed help message, press "h". To detach, press "d"; to quit, press "q".

Application finished.
```

**Comment by MuhammamdArslanKhan** [comment] 2019-12-31 22:09
Now I created a new Project and it shows the same error.

**Comment by iapicca** [comment] 2020-01-02 07:45
Hi @MuhammamdArslanKhan 
I've just tested name routes with the latest stable ([sample](https://dartpad.dartlang.org/cc27882ed4e4757b2bb794ace972bc39)), 
but I cannot reproduce the issue you are encountering;
could you please run 
`flutter clean`
`flutter pub cache repair`
If the issue persist please provide your updated 
`flutter doctor -v` and `flutter run --verbose`
thank you

**Comment by Polydevelopment1** [comment] 2020-01-17 13:01
I have the same issue, i used the snippet on pub.dev does the same.

have done as @MuhammamdArslanKhan suggested cleaned flutter and cache cleaned.

Flutter Doctor Output:
flutter doctor -v
[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 6.1.7601], locale en-US)
    • Flutter version 1.12.13+hotfix.5 at C:\libs\flutter
    • Framework revision 27321ebbad (5 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\Braam\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = C:\Users\Braam\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.41.1)
    • VS Code at C:\Users\Braam\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.7.1

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

**Comment by TahaTesser** [comment] 2020-02-10 13:29
Hi @MuhammamdArslanKhan 
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

**Closed by TahaTesser** 2020-02-10 13:29 UTC
Labels: waiting for customer response

**Comment by bolagadalla** [comment] 2020-12-06 00:05
You might have already found a solution for this, but just incase someone else needs help with it.
Since you already declared a ```home: ,``` property on the ```MaterialApp``` you dont need to create a ```"/"``` route. Vice versa, since you already have an initial route ```"/"``` then you dont need to declare a ```home: ,``` property. They just conflict with each other, so you need to either delete the ```home: ,``` property or delete the initial route ```"/"```. I recommend to delete the home and have flutter manage all the routes for you.

**Comment by Plegizplegiz** [comment] 2020-12-06 09:33
su 6.12.2020 klo 2.07 Bola Gadalla <notifications@github.com> kirjoitti:
