### ISSUE TITLE
Engine cocoon/github check and LUCI disagree about tree status

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#98674] opened 2022-02-17 17:13 UTC
According to LUCI the tree is green:
<img width="1662" alt="Screen Shot 2022-02-17 at 9 10 38 AM" src="https://user-images.githubusercontent.com/6343103/154534217-f41f84ad-f662-4f60-9900-78ad47986b9a.png">

But go/engine-build says the tree is red:
<img width="399" alt="Screen Shot 2022-02-17 at 9 11 37 AM" src="https://user-images.githubusercontent.com/6343103/154534341-7cbb740e-c8a5-4ba3-b05f-c3aed4eb2f7e.png">

The github check is also showing that the tree is closed in this state.

Is there any way to get the tree back open other than landing a PR? /cc @CaseyHillers

**Comment by CaseyHillers** [comment] 2022-02-17 17:17
The issue is Cocoon didn't pick up the multiple attempts for that commit+target.

![image](https://user-images.githubusercontent.com/2148558/154535130-8481fb97-f78b-44e4-a8c1-e504ae581771.png)

I'm already looking into this issue for the Cocoon scheduler side, so I'll assign to myself

**Comment by CaseyHillers** [comment] 2022-02-17 17:23
Thanks! That's helpful, I didn't know about this script.

It's using Cocoon to reschedule the builds (the call to /api/reset-prod-task). This does appear to be an issue with Cocoon

**Comment by zanderso** [comment] 2022-02-28 16:27
Bumping up to P2 since the only way to open the tree now is to manually land a waiting PR.

**Comment by CaseyHillers** [comment] 2022-02-28 16:57
https://github.com/flutter/cocoon/pull/1610 will fix this. I'll re-add the logic to support the engine team's script workflows to /api/reset-prod-task, and re-send for review.

**Comment by CaseyHillers** [comment] 2022-03-14 16:13
This should be fixed now. The PR for the new retry logic has landed

**Closed by CaseyHillers** 2022-03-14 16:13 UTC
Labels: team: infra, passed secondary triage, P2
