### ISSUE TITLE
Clicking a button (IOS/Android): Moving your finger several pixels while still on the button cancels the clicking action

### ISSUE THREAD

**Issue by LeRomino** [flutter/flutter#143506] opened 2024-02-15 03:14 UTC
### Steps to reproduce

1. Create a button widget with an onPressed callback.
2. Create a page without scroll to ensure the test.
3. Run the app on an IOS or Android device.
4. Tap the button and move your finger slightly while still on the button.
5. Observe that the onPressed callback is not triggered.

### Expected results

The onPressed callback should always be triggered when the finger is released while still on the button, as in native ios. Even when the finger leaves the button while pressed and then returns, the onPressed callback should be triggered if the finger is released on the button.

### Actual results

According to my tests, the click pressure is released as soon as I move slightly.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

class ExamplePage extends StatefulWidget {
  const ExamplePage({super.key});

  @override
  ExamplePageState createState() => ExamplePageState();
}

class ExamplePageState extends State<ExamplePage> {
  bool _isPressed = false; // variable to track the button state

  @override
  Widget build(BuildContext context) {
    return Center(
      child: SizedBox(
        width: double.infinity,
        height: 50,
        child: Padding(
          padding: const EdgeInsets.symmetric(horizontal: 20),
          child: ElevatedButton(
            onPressed: () {
              debugPrint('pressed');
              setState(() {
                _isPressed = true;
              });
              Future.delayed(const Duration(milliseconds: 500), () {
                setState(() {
                  _isPressed = false;
                });
              });
            },
            child: Text(_isPressed ? 'Pressed !!' : 'Press me'),
          ),
        ),
      ),
    );
  }
}
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.16.9, on macOS 14.3.1 23D60 darwin-arm64, locale fr-FR)
    • Flutter version 3.16.9 on channel stable at /Users/leromino/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 41456452f2 (3 weeks ago), 2024-01-25 10:06:23 -0800
    • Engine revision f40e976bed
    • Dart version 3.2.6
    • DevTools version 2.28.5

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/leromino/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.86.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.82.0

[✓] Connected device (2 available)
    • macOS (desktop)    • macos                     • darwin-arm64   • macOS 14.3.1 23D60 darwin-arm64
    • Chrome (web)       • chrome                    • web-javascript • Google Chrome 120.0.6099.234

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by dam-ease** [comment] 2024-02-15 10:35
Hello @LeRomino
Thanks for the report!
I can reproduce this issue as well, this is similar/ related to https://github.com/flutter/flutter/issues/59142. 
I see there is a workaround to this as well https://github.com/flutter/flutter/issues/59142#issuecomment-1670905825
Kindly comment, upvote and follow up on the existing issue for updates.
Closing this as a duplicate of the existing issue, if you disagree, please comment and I'll reopen this.

**Closed by dam-ease** 2024-02-15 10:35 UTC
Labels: in triage
