### ISSUE TITLE
Textfield input jank on first row when maxlines present 

### ISSUE THREAD

**Issue by blaneyneil** [flutter/flutter#32158] opened 2019-05-06 19:10 UTC
if maxLines is set in TextField(), whether it be null, an int, or coupled with minLines, your input will bounce on every character until it wraps down to a second line (it looks like a change in padding).  at which point it's smooth the rest of the way and identical to TextField() w/o maxLines set.

```
[✓] Flutter (Channel beta, v1.5.4-hotfix.2, on Mac OS X 10.14.4 18E226, locale en-US)
    • Flutter version 1.5.4-hotfix.2 at /Users/neil/flutter
    • Framework revision 7a4c33425d (7 days ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/neil/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.1

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 35.0.1
    • Dart plugin version 183.5901
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] Connected device (2 available)
    • iPhone 6s     • D8ED12AC-9AE5-477F-8142-4A023058BA82     • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)
```

**Comment by justinmc** [comment] 2019-05-07 15:36
@blaneyneil I wasn't able to reproduce this with a quick attempt just now.  Can you take a look at my code and tell me if this is what you're doing to see it?  I'm using the iPhone 6s simulator.

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(
        appBar: AppBar(
          title: Text('Flutter demo'),
        ),
        body: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              TextField(minLines: 1, maxLines: 4),
            ],
          ),
        ),
      ),
    );
  }
}
```

![out](https://user-images.githubusercontent.com/389558/57312632-d27e0d80-70a2-11e9-87ee-d8a2a614dc16.gif)

Potentially related: https://github.com/flutter/flutter/issues/31817

**Comment by blaneyneil** [comment] 2019-05-07 16:04
i just copied that above Center() code into a standalone, stateless widget with nothing else and the bouncing is indeed there.  but only on iOS - i tested on a 6s and Xs max simulator.   on Android it was steady.

**Comment by blaneyneil** [comment] 2019-05-07 16:13
and i opened up a new codebase with the above snippet just to see if it could be traced back to something in my existing parent tree, but the same bouncing was present until it wrapped.

**Comment by justinmc** [comment] 2019-05-07 18:06
I just tried it again on the beta channel and couldn't reproduce it there either.  Maybe try it on master if you get a chance?  I'm trying to think of anything else I can try to reproduce this...

**Comment by xia-weiyang** [comment] 2019-05-08 05:45
like this  ?
![Peek 2019-05-08 13-41](https://user-images.githubusercontent.com/11485324/57352276-79dc6c80-7197-11e9-9523-58c88c92afbe.gif)

**Comment by justinmc** [comment] 2019-05-13 16:40
I was able to reproduce this on a physical iPhone 7 using an older build, but when I switched to master, the stuttering went away.  I'm going to close this since it seems like it's been fixed, but if anyone reproduces it on master, let me know and I'll reopen.

**Closed by justinmc** 2019-05-13 16:40 UTC
Labels: a: text input, f: material design, framework
