### ISSUE TITLE
Scrollbar don't work well when display long lists in web/macOS app

### ISSUE THREAD

**Issue by neonio** [flutter/flutter#77860] opened 2021-03-11 00:50 UTC
## Steps to Reproduce
I reproduce this issue in my macOS app. The scrollbar is not draggable.
Then I go to https://flutter.dev/docs/cookbook/lists/long-lists and add scrollbar widget to the demo app.
Then entire website freeze.
It doesn't seem to relate to scrollcontroller, even I add scrollcontroller to scrollbar, this issue happened as well.

**Expected results:** 

Scroll smoothly like native app, no freeze at least.(web)
Scrollbar should be draggable when display long list.(macOS)

**Actual results:** 

App freezes most time, base on data source amount.(web)
Scrollbar freezed.(macOS)

<details>
  <summary>Flutter doctor</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.1, on macOS 11.2.1 20D74 darwin-x64, locale en-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[!] Xcode - develop for iOS and macOS
    ! CocoaPods 1.9.1 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.
[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.54.1)
[✓] Connected device (1 available)

! Doctor found issues in 2 categories.
```

</details>

<details>
  <summary>Code</summary>

```
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp(
    items: List<String>.generate(10000, (i) => "Item $i"),
  ));
}

class MyApp extends StatelessWidget {
  final List<String> items;

  MyApp({Key key, @required this.items}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    final title = 'Long List';

    return MaterialApp(
      title: title,
      home: Scaffold(
        appBar: AppBar(
          title: Text(title),
        ),
        body: Scrollbar(
          child: ListView.builder(
          itemCount: items.length,
          itemBuilder: (context, index) {
            return ListTile(
              title: Text('${items[index]}'),
            );
          },
        )),
      ),
    );
  }
}
```

```
```

```
```

```
```

</details>

**Comment by pedromassangocode** [comment] 2021-03-11 09:03
Duplicate of https://github.com/flutter/flutter/issues/75399. Please follow up and subscribe on that issue for updates.
Thank you

**Closed by pedromassangocode** 2021-03-11 09:03 UTC
Labels: in triage
