### ISSUE TITLE
Flutter build fails when using gradle 4.0

### ISSUE THREAD

**Issue by swavkulinski** [flutter/flutter#10236] opened 2017-05-20 22:58 UTC
UPDATE:

**Happens only when Android Studio is 3.0 and uses Gradle 4.0-milestone-1**

---

I was working on my project for couple of days on my Mac. When I pushed to github to get it on my linux machine it failed to compile. This time I was using Android Studio 3.0 Canary. Problem is in line 20 of `android/build.gradle` file.
Running 'gradle assembleDebug' directly completes without failure. 
Similar issues 
```
com.android.build.gradle.tasks.factory.AndroidJavaCompile.setDependencyCacheDir(Ljava/io/File;)V
```
were reported for Kotlin and ReactNative plugins. 

some suggested problem may be related to case sensitive file systems. Mac isn't case sensitive. 

## Steps to Reproduce

run `flutter run` on linux (Ubuntu Gnome) 

observe build fails during `gradle assembleDebug` task

replicable 100%

## Logs

```
[  +79 ms] [/home/swav/Library/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +21 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/alpha
[        ] [/home/swav/Library/flutter/] git ls-remote --get-url origin
[  +13 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[        ] [/home/swav/Library/flutter/] git log -n 1 --pretty=format:%H
[  +13 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] 973304d5fbf737510ecc250b93d9ee2e872b563f
[        ] [/home/swav/Library/flutter/] git log -n 1 --pretty=format:%ar
[  +13 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[        ] 2 days ago
[ +210 ms] Listing devices using /home/swav/Android/Sdk/platform-tools/adb
[        ] /home/swav/Android/Sdk/platform-tools/adb devices -l
[  +12 ms] Exit code 0 from: /home/swav/Android/Sdk/platform-tools/adb devices -l
[        ] List of devices attached
           emulator-5554          device product:sdk_google_phone_x86 model:Android_SDK_built_for_x86 device:generic_x86
[  +59 ms] /home/swav/Android/Sdk/platform-tools/adb -s emulator-5554 shell getprop
[+3479 ms] Launching lib/main.dart on Android SDK built for x86 in debug mode...
[ +211 ms] Using gradle from /home/swav/Library/android-studio-3.0/gradle/gradle-4.0-milestone-1/bin/gradle.
[  +10 ms] [android/] /home/swav/Library/android-studio-3.0/gradle/gradle-4.0-milestone-1/bin/gradle app:properties
[ +753 ms] Exit code 1 from: /home/swav/Library/android-studio-3.0/gradle/gradle-4.0-milestone-1/bin/gradle app:properties
[        ] FAILURE: Build failed with an exception.
           
           * Where:
           Build file '/home/swav/Git/flutter/status-app/android/build.gradle' line: 20
           
           * What went wrong:
           A problem occurred evaluating root project 'android'.
           > A problem occurred configuring project ':app'.
              > Failed to notify project evaluation listener.
                 > com.android.build.gradle.tasks.factory.AndroidJavaCompile.setDependencyCacheDir(Ljava/io/File;)V
           
           * Try:
           Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
[        ] Error running gradle: Exit code 1 from: /home/swav/Library/android-studio-3.0/gradle/gradle-4.0-milestone-1/bin/gradle app:properties
[  +28 ms] /home/swav/Android/Sdk/platform-tools/adb -s emulator-5554 logcat -v time -t 1
[  +20 ms] Exit code 0 from: /home/swav/Android/Sdk/platform-tools/adb -s emulator-5554 logcat -v time -t 1
[        ] --------- beginning of main
           05-20 22:53:19.686 I/DeviceStateChecker( 5077): DeviceStateChecker cancelled
[   +1 ms] /home/swav/Android/Sdk/platform-tools/adb -s emulator-5554 logcat -v time
[   +4 ms] /home/swav/Android/Sdk/platform-tools/adb version
[  +37 ms] Android Debug Bridge version 1.0.39
           Revision 3db08f2c6889-android
           Installed as /home/swav/Android/Sdk/platform-tools/adb
[   +2 ms] /home/swav/Android/Sdk/platform-tools/adb start-server
[ +203 ms] Building APK
[ +224 ms] Using gradle from /home/swav/Library/android-studio-3.0/gradle/gradle-4.0-milestone-1/bin/gradle.
[   +6 ms] Running 'gradle assembleDebug'...
[   +1 ms] [android/] /home/swav/Library/android-studio-3.0/gradle/gradle-4.0-milestone-1/bin/gradle -Ptarget=/home/swav/Git/flutter/status-app/lib/main.dart assembleDebug
[ +652 ms] FAILURE: Build failed with an exception.
[        ] * Where:
[        ] Build file '/home/swav/Git/flutter/status-app/android/build.gradle' line: 20
[        ] * What went wrong:
[        ] A problem occurred evaluating root project 'android'.
[        ] > A problem occurred configuring project ':app'.
[        ]    > Failed to notify project evaluation listener.
[        ]       > com.android.build.gradle.tasks.factory.AndroidJavaCompile.setDependencyCacheDir(Ljava/io/File;)V
[        ] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
[   +4 ms] BUILD FAILED in 0s
[ +366 ms] "flutter run" took 6,247ms.
Gradle build failed: 1

#0      throwToolExit (package:flutter_tools/src/base/common.dart:29)
#1      buildGradleProjectV2 (package:flutter_tools/src/android/gradle.dart:244)
<asynchronous suspension>
#2      buildGradleProject (package:flutter_tools/src/android/gradle.dart:192)
<asynchronous suspension>
#3      buildApk (package:flutter_tools/src/commands/build_apk.dart:83)
<asynchronous suspension>
#4      AndroidDevice.startApp (package:flutter_tools/src/android/android_device.dart:334)
<asynchronous suspension>
#5      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:223)
<asynchronous suspension>
#6      HotRunner.run (package:flutter_tools/src/run_hot.dart:183)
<asynchronous suspension>
#7      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:321)
<asynchronous suspension>
#8      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:210)
<asynchronous suspension>
#9      RunCommand.verifyThenRunCommand (package:flutter_tools/src/commands/run.dart:210)
<asynchronous suspension>
#10     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:156)
<asynchronous suspension>
#11     CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:261)
<asynchronous suspension>
#13     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#14     Future.Future.sync (dart:async/future.dart:208)
#15     CommandRunner.run (package:args/command_runner.dart:109)
#16     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:156)
#17     run.<anonymous closure> (package:flutter_tools/executable.dart:140)
<asynchronous suspension>
#18     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#19     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#20     _rootRun (dart:async/zone.dart:1120)
#21     _CustomZone.run (dart:async/zone.dart:1001)
#22     runZoned (dart:async/zone.dart:1465)
#23     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#24     run (package:flutter_tools/executable.dart:113)
<asynchronous suspension>
#25     main (package:flutter_tools/executable.dart:66)
<asynchronous suspension>
#26     main (file:///home/swav/Library/flutter/packages/flutter_tools/bin/flutter_tools.dart:16)
#27     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#28     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)


[  +85 ms] ensureAnalyticsSent: 74ms
[ +158 ms] [/tmp/flutter_tools_uHo3u3/] zip -r -q /home/swav/Git/flutter/status-app/bugreport_03.zip .
[ +166 ms] Exit code 0 from: zip -r -q /home/swav/Git/flutter/status-app/bugreport_03.zip .
[        ] Bug report written to bugreport_03.zip.
           Note that this bug report contains local paths, device identifiers, and log snippets.
[   +9 ms] exiting with code 1

```

## Flutter Doctor

[✓] Flutter (on Linux, channel alpha)
    • Flutter at /home/swav/Library/flutter
    • Framework revision 973304d5fb (2 days ago), 2017-05-18 17:31:57 -0700
    • Engine revision f99d3ef108
    • Tools Dart version 1.23.0-dev.11.11

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at /home/swav/Android/Sdk
    • Platform android-25, build-tools 25.0.3
    • Java binary at: /home/swav/Library/android-studio-3.0/jre/bin/java
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b736)

[✓] Android Studio (version 3.0)
    • Android Studio at /home/swav/Library/android-studio-3.0
    • Gradle version 4.0-milestone-1
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b736)

[✓] Android Studio (version 2.3)
    • Android Studio at /home/swav/Library/android-studio-2.3.1
    • Gradle version 3.2
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] Connected devices
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 7.1.1 (API 25) (emulator)

**Comment by twotwotwo** [comment] 2017-05-22 04:58
It's possible the cause here is that Android Studio 3.0 bundles Gradle 4.0, which (from searching around) was scheduled to deprecate the setDependencyCacheDir API, which some plugins might still be written against. If that's it, I'm not sure what exactly you do to get the `flutter` tool to talk to the tools installed for Studio 2.3 instead, but that seems like a possible approach.

(I'm not writing this as a Flutter expert, just a user that ran into the same message after looking at both Flutter and Studio 3.0 after the recent I/O announcements.)

**Comment by eseidelGoogle** [comment] 2017-05-22 05:54
FYI @jakobr-google @jason-simmons.

**Comment by jakobr-google** [comment] 2017-05-22 08:07
If you have several versions of Android Studio installed, you can configure which one Flutter Tools uses by running `flutter config --android-studio-dir=<path to Studio>`.

If you just want to specify which Gradle to use, run `flutter config --gradle-dir=<path to Gradle>`.

But yeah, we'll need to figure out why we're failing with the latest Gradle, and fix that.

**Comment by eseidelGoogle** [comment] 2017-05-24 16:14
We got another report of this just now in Gitter.  The workaround (configure flutter to point to an older gradle) works.  @jason-simmons started looking at what it would take to use a wrapped gradel yesterday.  Unclear if that would help with this bug or not.

**Comment by dodyg** [comment] 2017-05-28 20:50
I got the same
```
[√] Flutter (on Microsoft Windows [Version 10.0.15063], channel alpha)
    • Flutter at C:\Flutter
    • Framework revision 973304d5fb (10 days ago), 2017-05-18 17:31:57 -0700
    • Engine revision f99d3ef108
    • Tools Dart version 1.23.0-dev.11.11

[√] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at C:\Users\dodyg\AppData\Local\Android\sdk
    • Platform android-25, build-tools 25.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[√] Android Studio (version 2.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Gradle version 3.2
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[√] IntelliJ IDEA Community Edition (version 2017.1)
    • Dart plugin version 171.4424.63
    • Flutter plugin version 14.0

[√] Connected devices
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 7.1.1 (API 25) (emulator)
```

**Comment by ojhariddhish** [comment] 2017-05-29 05:20
Thanks @jacobr-google. Changing Android Studio version to 2.4 in Flutter config fixed the issue.

**Comment by asaarnak** [comment] 2017-06-10 20:15
Seems like it's fixed by using:
```gradle 
classpath 'com.android.tools.build:gradle:2.3.3'
```
Currently the flutter create template has older version 2.2.3 
because it defaults to Android Studio gradle version, which is gradle 3.2 on latest stable studio 2.3.

**Comment by mravn-google** [comment] 2017-06-26 21:08
Update:

- Flutter now uses Gradle 3.3 (via Gradle Wrapper) and Android Gradle plugin 2.3.3. This configuration has been tested to work both from the Flutter CLI and from Android Studio 2.3.3.
- Changing `android/gradle/wrapper/gradle-wrapper.properties` to target Gradle 3.5 or Gradle 4.0 has also been tested to work in both scenarios.
- Use of Android Studio 3.0.0-xxx is not yet officially supported. For Canary 4 it is necessary to
    1. change `android/gradle/wrapper/gradle-wrapper.properties` to target Gradle 3.5 or later, and then
    1. decline Android Studio's suggestion to upgrade Gradle and the Android Gradle plugin.

**Closed** 2017-06-26 21:11 UTC
Labels: dev: tool - gradle, regression, ▣ platform-android

**Comment by Hixie** [comment] 2018-01-08 05:46
I just hit this trying to run the Flutter apps in the assets-for-api-docs repo, presumably because those are way out of date. We really need to have a way to upgrade people...

**Comment by Hixie** [comment] 2018-01-08 05:47
(Deleting the android/ directory and recreating it with `flutter create` fixed it.)

**Comment by jasdeepsingh** [comment] 2018-01-27 01:27
I'm having the same issue with:

```
------------------------------------------------------------
Gradle 4.4.1
------------------------------------------------------------

Build time:   2017-12-20 15:45:23 UTC
Revision:     10ed9dc355dc39f6307cc98fbd8cea314bdd381c

Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.9 compiled on February 2 2017
JVM:          1.8.0_152 (Oracle Corporation 25.152-b16)
OS:           Mac OS X 10.13.2 x86_64
```

And Android Studio 3.0

**Comment by sfthurber** [comment] 2018-03-17 13:10
i'm having the same issue with flutter and gradle 4.6 with this build (also tried various alternatives to 2.2.3:

buildscript {
    repositories {
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:2.2.3'
    }
}

apply plugin: 'com.android.application'

android {
    compileSdkVersion 26
    buildToolsVersion "26.0.3"
}

task wrapper(type: Wrapper) {
    gradleVersion = '4.6'
}

**Comment by charafau** [comment] 2018-03-17 19:51
android needs `3.0.1` version of gradle plugin to build with gradle >= 4.1

**Comment by sfthurber** [comment] 2018-03-17 20:13
i am using gradle 3.5.1

**Comment by davidair** [comment] 2018-04-15 04:37
Running into this with Android Studio 3.1.1, gradle 4.4 and com.android.tools.build:gradle:3.1.1. I'm able to run for release (flutter run --release) but not debug. I only have one (latest) version of Android Studio installed. Is there a workaround for this?

**Comment by davidair** [comment] 2018-04-15 23:50
The way I got into this situation was to create my Flutter project on my Mac and then attempt running it on Windows. Both Mac and Windows run Android Studio 3.1.1, but the output of `flutter --version` looks different:

Mac
`Flutter 0.0.22-pre.1 • channel alpha • https://github.com/flutter/flutter.git
Framework • revision 553fc4264e (6 weeks ago) • 2018-03-01 09:30:25 -0800
Engine • revision 6921873c71
Tools • Dart 2.0.0-dev.16.0`

Windows
`Flutter • channel alpha • https://github.com/flutter/flutter.git
Framework • revision e8aa40eddd (6 months ago) • 2017-10-17 15:42:40 -0700
Engine • revision 7c4142808c
Tools • Dart 1.25.0-dev.11.0`

When I create a new project on Mac, it uses the following settings:
- com.android.tools.build:gradle:3.0.1
- gradle 4.1

When I create a new project on Windows, it uses the following settings:
- com.android.tools.build:gradle:2.3.3
- Gradle 3.3

The later works - so I ended up downgrading the gradle files in my project and it now runs on my physical Android device both on Windows and Mac.

Note that attempting to manually roll forward to Gradle 4.4 and com.android.tools.build:gradle:3.1.1 on Windows didn't work

**Comment by mit-mit** [comment] 2018-04-16 07:24
@davidair those are very old flutter framework builds! I recommend you switch to the beta channel (run the command `flutter channel beta`), and then upgrade (run the command `flutter upgrade`).

**Comment by davidair** [comment] 2018-04-17 01:54
I upgraded flutter on both machines (was a bit of a mess on Windows because it was so old) and I was able to run a project using 3.1.1 plugin on my Windows box. Thanks for the tip!

Note: I'm surprised "flutter doctor" didn't tell me anything about running an old version.

**Comment by ffeu** [comment] 2018-04-21 01:01
I was having the same issues and upgrading both flutter and android studio didn't do it. I guess the problem happens once you're stuck with an old project and the tools get updates.

What got it right was updating:
- the compileSdkVersion and buildToolsVersion in the file [android/app/build.gradle];
- updating the dependencies classpath to grade:2.3.3 in [android/build.gradle] (as @asaarnak sugested). 

I used the latest sdk and buildtools versions I've found in the folders .../sdk/build-tools and .../sdk/platforms.

**Comment by rakz25** [comment] 2018-08-07 11:36
my grade.build file is below:
buildscript {
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.0.1'
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

Still have the same issue:
 line: 20

* What went wrong:
A problem occurred evaluating root project 'android'.
> A problem occurred configuring project ':app'.
   > Failed to notify project evaluation listener.
      > com.android.build.gradle.tasks.factory.AndroidJavaCompile.setDependencyCacheDir(Ljava/io/File;)V

**Comment by ffeu** [comment] 2018-08-07 11:43
I recommend you create a new project and transfer your files to the new one.

As flutter evolves, some of its improvements end up leaving old projects stuck.

I have even created a script for that, it copies the lib/*, assets/*, icons/*, pubspec.yaml, etc..
