### ISSUE TITLE
Calling setState rebuilds the cursor when MouseRegion is nested in a scroll view

### ISSUE THREAD

**Issue by kirill-21** [flutter/flutter#82103] opened 2021-05-08 11:56 UTC
I have a widget tree with SingleChildScrollView on top and a custom-made icon-button(Which works with help of Listener and MouseRegion) below. When i call setstate inside of my custom icon-button(to change color on click), it rebuilds and my selected cursor of type SystemMouseCursors.click changes to the default one until i move my mouse. As soon as i remove SingleChildScrollView or change physics to NeverScrollableScrollPhysics(), the problem disappears. 

Before removing scrollview:
![before](https://user-images.githubusercontent.com/63228361/117537861-45148180-b00c-11eb-8da9-fc4d6be11fc7.gif)

After removing scrollview:
![after](https://user-images.githubusercontent.com/63228361/117537880-59587e80-b00c-11eb-94e6-57ced09c1334.gif)

Also, if i use GestureDetector instead of Listener on my icon-button, the problem with cursor changing disappears, however, i have this result(i have to click and wait for 1 second before removing my finger from the mouse button to make flutter understand that i actually clicked in that place) [On this gif i clicked on the button about 20 times)
![nested gesutre](https://user-images.githubusercontent.com/63228361/117537997-d3890300-b00c-11eb-9613-d95ffcf95cf9.gif)

I think this issue happens because of nested GestureDetector. I've tried to change it's behavior and used RawGestureDetectors, but the problem doesn't disappear. Maybe there are some other widgets (except for Listener, GestureDetector and RawGestureDetector), which i can use (or other scrollable widgets that does not use gesturedetector)? 

My custom button:
![11](https://user-images.githubusercontent.com/63228361/117538392-a3dafa80-b00e-11eb-816e-7ce8b6c3e14a.png)

I'm using the latest flutter and dart versions from stable channel.

**Comment by TahaTesser** [comment] 2021-05-10 11:37
Hi @kirill-21 
I just created a minimal code sample to reproduce, however, I cannot replicate the issue. Can you please edit the code sample and match it to your issue?  What platform are you running your app? I ran on `windows`  as target 

<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatefulWidget {
  @override
  _HomeState createState() => _HomeState();
}

class _HomeState extends State<Home> {
  bool hovering = false;

  void changeLogo() {
    if (mounted) {
      setState(() {
        hovering = !hovering;
      });
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: MouseRegion(
          onEnter: (value) {
            print('MouseRegion:onEnter called');
            changeLogo();
          },
          onExit: (value) {
            print('MouseRegion:onExit called');
            changeLogo();
          },
          cursor: hovering ? SystemMouseCursors.click : SystemMouseCursors.move,
          child: Listener( 
            onPointerDown: (_) {
              print("Listener:onPointerDown called");
              changeLogo();
            },
            onPointerUp: (_) {
              print("Listener:onPointerUp called");
              changeLogo();
            },
            child: FlutterLogo(
              size: 250,
              style: hovering
                  ? FlutterLogoStyle.horizontal
                  : FlutterLogoStyle.stacked,
            ),
          ),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {},
      ),
    );
  }
}

``` 

</details>

Also, can you please provide your `flutter doctor -v`? (even if everything is okay with it, we need it to test the issue on same channel, device etc )
Thank you

**Comment by kirill-21** [comment] 2021-05-10 11:42
> ```dart
> Center
> ```

Yes, windows. Wrap your widget tree inside of GestureDetector or SingleChildScrollView(in this page should be enough high to activate scroll functionality)

**Comment by kirill-21** [comment] 2021-05-10 11:55
> Hi @kirill-21
> I just created a minimal code sample to reproduce, however, I cannot replicate the issue. Can you please edit the code sample and match it to your issue? What platform are you running your app? I ran on `windows` as target
> 
> code sample
> Also, can you please provide your `flutter doctor -v`? (even if everything is okay with it, we need it to test the issue on same channel, device etc )
> Thank you

![image](https://user-images.githubusercontent.com/63228361/117655432-bd5f7c00-b19f-11eb-9dcf-f88efbbe1ea0.png)

**Comment by TahaTesser** [comment] 2021-05-11 06:56
Hi @kirill-21 
I've tried to reproduce using `SingleChildScrollView`, there is no difference.

Can you please try the following code sample. please provide step by steps to reproduce the issue along with actual results/expected results 

<details> 
<summary>minimal code sample</summary> 

```dart
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatefulWidget {
  @override
  _HomeState createState() => _HomeState();
}

class _HomeState extends State<Home> {
  bool hovering = false;

  void changeLogo() {
    if (mounted) {
      setState(() {
        hovering = !hovering;
      });
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: SingleChildScrollView(
          child: MouseRegion(
            onEnter: (value) {
              print('MouseRegion:onEnter called');
              changeLogo();
            },
            onExit: (value) {
              print('MouseRegion:onExit called');
              changeLogo();
            },
            cursor:
                hovering ? SystemMouseCursors.click : SystemMouseCursors.move,
            child: Listener(
              onPointerDown: (_) {
                print("Listener:onPointerDown called");
                changeLogo();
              },
              onPointerUp: (_) {
                print("Listener:onPointerUp called");
                changeLogo();
              },
              child: FlutterLogo(
                size: 250,
                style: hovering
                    ? FlutterLogoStyle.horizontal
                    : FlutterLogoStyle.stacked,
              ),
            ),
          ),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {},
      ),
    );
  }
}
``` 

</details>

**Comment by TahaTesser** [comment] 2021-05-12 07:11
Hi @kirill-21 
Thanks for the code sample and previews!

` SingleChildScrollView + Listener` seems to be fixed on the `master`

### Preview
| `stable`, `beta`, `dev` | `master`  |
| --------------- | --------------- |
<img src="https://user-images.githubusercontent.com/48603081/117933353-282cc680-b30a-11eb-8100-bc8f76b758fe.gif" /> | <img src="https://user-images.githubusercontent.com/48603081/117933276-10edd900-b30a-11eb-8de6-74e06ad5f634.gif" /> |




Reproduced the issue using the following minimal code sample 

<details> 
<summary>minimal code sample</summary> 

```dart
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        backgroundColor: Colors.black,
        body: SingleChildScrollView(
          child: Body(),
          // physics: NeverScrollableScrollPhysics(), /// Uncomment to check result without SingleChildScrollView
        ),
      ),
    );
  }
}

class Body extends StatefulWidget {
  @override
  _BodyState createState() => _BodyState();
}

class _BodyState extends State<Body> {
  Color _color = Colors.greenAccent;

  _updateColor(Color color) => setState(() => _color = color);

  @override
  Widget build(BuildContext context) {
    return MouseRegion(
      onEnter: (_) => _updateColor(Colors.greenAccent.withOpacity(0.9)),
      onExit: (_) => _updateColor(Colors.greenAccent),
      cursor: SystemMouseCursors.click,
      child: Listener(
        onPointerDown: (_) => _updateColor(Colors.greenAccent.withOpacity(0.8)),
        onPointerUp: (_) => _updateColor(Colors.greenAccent.withOpacity(0.9)),
        child: Container(
          height: 2000,
          width: 400,
          color: _color,
        ),
      ),
    );
  }
}

``` 

</details>


Reproduced on the following channels
|  `stable`  |  `beta`  | `dev` | `master` |
| :---: | :---: | :---: |:---: |
|  ✅  |   ✅  |  ✅  |  ❌  |

Check `flutter doctor -v` outputs for each channel below

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.0.6, on macOS 11.3 20E232 darwin-x64, locale
    en-GB)
    • Flutter version 2.0.6 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 1d9032c7e1 (12 days ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.56.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.22.0

[✓] Connected device (3 available)
    • iPhone 12 (mobile) • 2F994696-D77F-4C1A-A926-732A6EEC8E49 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)    • macos                                • darwin-x64
      • macOS 11.3 20E232 darwin-x64
    • Chrome (web)       • chrome                               • web-javascript
      • Google Chrome 90.0.4430.93

! Doctor found issues in 1 category.
```

```console
[✓] Flutter (Channel beta, 2.2.0-10.3.pre, on macOS 11.3 20E232 darwin-x64,
    locale en-GB)
    • Flutter version 2.2.0-10.3.pre at /Users/tahatesser/Code/flutter_beta
    • Framework revision 06e2fd6357 (4 days ago), 2021-05-08 11:28:22 -0700
    • Engine revision a123e75c60
    • Dart version 2.13.0 (build 2.13.0-211.14.beta)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.56.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.22.0

[✓] Connected device (3 available)
    • iPhone 12 (mobile) • 2F994696-D77F-4C1A-A926-732A6EEC8E49 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)    • macos                                • darwin-x64
      • macOS 11.3 20E232 darwin-x64
    • Chrome (web)       • chrome                               • web-javascript
      • Google Chrome 90.0.4430.93

! Doctor found issues in 1 category.
```

```console
[✓] Flutter (Channel dev, 2.3.0-1.0.pre, on macOS 11.3 20E232 darwin-x64, locale
    en-GB)
    • Flutter version 2.3.0-1.0.pre at /Users/tahatesser/Code/flutter_dev
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d97f41caed (12 days ago), 2021-04-30 12:35:21 -0700
    • Engine revision e7939e091e
    • Dart version 2.14.0 (build 2.14.0-48.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.1.1)
    • IntelliJ at /Volumes/Extreme/IntelliJ IDEA CE.app
    • Flutter plugin version 55.1.5
    • Dart plugin version 211.7233

[✓] VS Code (version 1.56.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.22.0

[✓] Connected device (3 available)
    • iPhone 12 (mobile) • 2F994696-D77F-4C1A-A926-732A6EEC8E49 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)    • macos                                • darwin-x64
      • macOS 11.3 20E232 darwin-x64
    • Chrome (web)       • chrome                               • web-javascript
      • Google Chrome 90.0.4430.93

! Doctor found issues in 1 category.
```

```console
[✓] Flutter (Channel master, 2.3.0-2.0.pre.139, on macOS 11.3 20E232 darwin-x64,
    locale en-GB)
    • Flutter version 2.3.0-2.0.pre.139 at /Users/tahatesser/Code/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e621ebfb34 (4 hours ago), 2021-05-11 23:29:03 -0400
    • Engine revision 8e332453b8
    • Dart version 2.14.0 (build
      2.14.0-edge.b99466d472e369990eb22de332cb5b2967b3ea00)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.1.1)
    • IntelliJ at /Volumes/Extreme/IntelliJ IDEA CE.app
    • Flutter plugin version 55.1.5
    • Dart plugin version 211.7233

[✓] VS Code (version 1.56.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.22.0

[✓] Connected device (3 available)
    • iPhone 12 (mobile) • 2F994696-D77F-4C1A-A926-732A6EEC8E49 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)    • macos                                • darwin-x64
      • macOS 11.3 20E232 darwin-x64
    • Chrome (web)       • chrome                               • web-javascript
      • Google Chrome 90.0.4430.93

! Doctor found issues in 1 category.
```
		
</details>


Can you please upgrade to the latest  `master` and try again
Execute the following commands to upgrade
`flutter channel master`
`flutter upgrade --force`
`flutter doctor -v`

**Comment by kirill-21** [comment] 2021-05-12 11:56
> Hi @kirill-21
> Thanks for the code sample and previews!
> 
> ` SingleChildScrollView + Listener` seems to be fixed on the `master`
> 
> ### Preview
> `stable`, `beta`, `dev`	`master`
> ![](https://user-images.githubusercontent.com/48603081/117933353-282cc680-b30a-11eb-8100-bc8f76b758fe.gif)	![](https://user-images.githubusercontent.com/48603081/117933276-10edd900-b30a-11eb-8de6-74e06ad5f634.gif)
> Reproduced the issue using the following minimal code sample
> 
> minimal code sample
> Reproduced on the following channels
> 
> `stable`	`beta`	`dev`	`master`
> ✅	✅	✅	❌
> Check `flutter doctor -v` outputs for each channel below
> 
> flutter doctor -v
> Can you please upgrade to the latest `master` and try again
> Execute the following commands to upgrade
> `flutter channel master`
> `flutter upgrade --force`
> `flutter doctor -v`

The issue seems to be gone, however, scrollable functionality from SingleChildScrollView  has gone and i cannot scroll the page anymore

**Comment by TahaTesser** [comment] 2021-05-13 07:23
Hi @kirill-21 
Thanks for the confirmation.
Regarding mouse drag, that's by design, it is a recent change https://github.com/flutter/flutter/pull/81569


Complete details in https://github.com/flutter/flutter/issues/82103#issuecomment-839523618

**Comment by kirill-21** [comment] 2021-05-13 10:29
> Hi @kirill-21
> Thanks for the confirmation.
> Regarding mouse drag, that's by design, it is a recent change #81569
> 
> Complete details in [#82103 (comment)](https://github.com/flutter/flutter/issues/82103#issuecomment-839523618)

So, is there any way to disable scroll with mouse wheel but keep dragging?

**Comment by TahaTesser** [comment] 2021-05-13 11:22
@kirill-21 
My bad, missed the issue, If I'm not mistaken this also seems to be fixed on the `master` channel

On dev, just fast click doesn't work (same as you), holding it for a second does the job
On master, fast clicks works

### Preview
| `dev` | `master` |
| --------------- | --------------- |
<img src="https://user-images.githubusercontent.com/48603081/118119025-66071900-b3f6-11eb-9e9d-1c3c569eb61b.gif" height="450" /> | <img src="https://user-images.githubusercontent.com/48603081/118118949-4bcd3b00-b3f6-11eb-886d-9642d2e05e5c.gif" height="450" /> |




Reproduced on the following channels
|  `dev`  | `master` |
| :---: |:---: |
|  ✅  |   ✅  | 

Check `flutter doctor -v` outputs for each channel below

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel dev, 2.3.0-1.0.pre, on Microsoft Windows [Version 10.0.19042.928], locale en-US)
    • Flutter version 2.3.0-1.0.pre at C:\Users\Taha\Code\flutter_dev
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d97f41caed (13 days ago), 2021-04-30 12:35:21 -0700
    • Engine revision e7939e091e
    • Dart version 2.14.0 (build 2.14.0-48.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\Taha\Code\SDK
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.9.31205.134
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Users\Taha\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[✓] IntelliJ IDEA Community Edition (version 2021.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.3.3
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.56.1)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.22.0

[✓] Connected device (4 available)
    • sdk google atv x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Windows (desktop)           • windows       • windows-x64    • Microsoft Windows [Version 10.0.19042.928]
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 90.0.4430.212
    • Edge (web)                  • edge          • web-javascript • Microsoft Edge 90.0.818.56

• No issues found!
```

```console
[✓] Flutter (Channel master, 2.3.0-2.0.pre.163, on Microsoft Windows [Version 10.0.19042.928], locale en-US)
    • Flutter version 2.3.0-2.0.pre.163 at C:\Users\Taha\Code\flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 298f18b592 (8 hours ago), 2021-05-12 20:50:14 -0700
    • Engine revision a339374296
    • Dart version 2.14.0 (build 2.14.0-109.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\Taha\Code\SDK
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.9.31205.134
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Users\Taha\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[✓] IntelliJ IDEA Community Edition (version 2021.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.3.3
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.56.1)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.22.0

[✓] Connected device (4 available)
    • SM M025F (mobile) • R9ZR205XX0A • android-arm    • Android 10 (API 29)
    • Windows (desktop) • windows     • windows-x64    • Microsoft Windows [Version 10.0.19042.928]
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 90.0.4430.212
    • Edge (web)        • edge        • web-javascript • Microsoft Edge 90.0.818.56

• No issues found!
```
		
</details>

**Comment by TahaTesser** [comment] 2021-05-26 12:54
Let's keep the issue for further teacking into `stable` and `beta` channels

**Comment by kirill-21** [comment] 2021-05-26 14:07
> it it seems to be fi

I'm on a stable channel and issue is fixed there

**Comment by TahaTesser** [comment] 2021-05-26 14:14
Thanks, I feel safe to close then

**Closed by TahaTesser** 2021-05-26 14:14 UTC
Labels: a: mouse, f: gestures, found in release: 2.0, found in release: 2.2, found in release: 2.3, framework, has reproducible steps
