### ISSUE TITLE
PageController.jumpToPage doesnot work Occasionally happened.

### ISSUE THREAD

**Issue by zhouxinle** [flutter/flutter#82315] opened 2021-05-12 03:38 UTC
I am using flutter 1.22.6 stable.  when I run my application in iphone11, pageview switch successfully. But when the iphone lock screen, and  after a while ,I resume my application, Occasionally PageController.jumpToPage doesnot work. Pageview cannot switch page. This situation only happens Occasionally.

**Comment by zhouxinle** [comment] 2021-05-12 06:19
addition: other widgets on page can be clicked, only PageController.jumpToPage doesnot work.

**Comment by darshankawar** [comment] 2021-05-12 07:37
@zhouxinle 
You are on older version of stable. Current version is 2.0.6. I recommend to upgrade to latest and try again to see if issue still persists, because even this is a bug in 1.22.6, the fix won't be made to that version. So first step is to upgrade to latest.

If issue still persists on latest version, provide updated `flutter doctor -v` and a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that we can use to verify this issue.

Thanks.

**Comment by darshankawar** [comment] 2021-06-04 13:17
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by darshankawar** 2021-06-04 13:17 UTC
Labels: in triage, waiting for customer response
