### ISSUE TITLE
App doesn't start when "Debug" run configuration is used with CanvasKit

### ISSUE THREAD

**Issue by johnpryan** [flutter/flutter#71622] opened 2020-12-03 01:02 UTC
Chrome displays a blank screen when running in Debug mode from IntelliJ with CanvasKit enabled.

## Steps to Reproduce

1. Create a Run/Debug configuration in IntelliJ matching the screenshot below
2. Click the Debug button in IntelliJ
3. Observe that Chrome displays a blank screen with no console output

<img width="1183" alt="Screen Shot 2020-12-02 at 4 59 37 PM" src="https://user-images.githubusercontent.com/1145719/100949802-ec224980-34bf-11eb-928f-97bf3b88278a.png">

```
[✓] Flutter (Channel master, 1.25.0-5.0.pre.40, on Mac OS X 10.15.7 19H15 darwin-x64,
    locale en)
    • Flutter version 1.25.0-5.0.pre.40 at /Users/ryjohn/code/github/flutter/flutter
    • Framework revision 2520d53eca (65 minutes ago), 2020-12-02 17:50:40 -0600
    • Engine revision 20caf54969
    • Dart version 2.12.0 (build 2.12.0-76.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/ryjohn/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 51.0.3
    • Dart plugin version 202.8070

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.0

[✓] Connected device (3 available)
    • iPhone 8 (mobile) • 0A5F1D6F-B4A5-4146-A6C3-A5594C1EDE62 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)
    • Web Server (web)  • web-server                           • web-javascript • Flutter Tools
    • Chrome (web)      • chrome                               • web-javascript • Google Chrome 87.0.4280.88

• No issues found!
```

**Comment by pedromassangocode** [comment] 2020-12-03 12:07
I was not able to reproduce with the latest Flutter version on `master`.
![Screen Shot 2020-12-03 at 13 05 41](https://user-images.githubusercontent.com/67424416/101015829-41b23100-3568-11eb-9431-fa93d459d1e7.png)

<details><summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.25.0-5.0.pre.45, on Mac OS X 10.15.7 19H2 darwin-x64, locale en)
    • Flutter version 1.25.0-5.0.pre.45 at /Users/pedromassango/dev/SDKs/flutter_master
    • Framework revision 81e1f7d1ed (11 hours ago), 2020-12-02 17:19:57 -0800
    • Engine revision 20caf54969
    • Dart version 2.12.0 (build 2.12.0-76.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 51.0.3
    • Dart plugin version 202.8070

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (3 available)
    • macOS (desktop)  • macos      • darwin-x64     • Mac OS X 10.15.7 19H2 darwin-x64
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 86.0.4240.198

• No issues found!
Process finished with exit code 0
```
</details>

**Comment by johnpryan** [comment] 2020-12-03 17:15
I can't reproduce this anymore either.

**Comment by johnpryan** [comment] 2020-12-03 21:42
This is happening for me again

**Comment by grouma** [comment] 2020-12-09 19:34
This was a cors issue. Closing.

**Closed by grouma** 2020-12-09 19:34 UTC
Labels: debugging_web, e: web_canvaskit, passed first triage, platform-web
