### ISSUE TITLE
bottom_navigation_demo can not touch when change the tab

### ISSUE THREAD

**Issue by jiqimaogou** [flutter/flutter#44055] opened 2019-11-03 04:30 UTC
https://github.com/flutter/flutter/blob/dev/examples/flutter_gallery/lib/demo/material/bottom_navigation_demo.dart

in this demo, I add a button on each view, but when I change the tab, the button can not be touched.

**Comment by iapicca** [comment] 2019-11-04 14:23
Hi @jiqimaogou 
Could you please provide your `flutter doctor -v`?
If I understand correctly the issue is that during the animation 
the icon loses gestures detection, correct?
Thank you

**Comment by jiqimaogou** [comment] 2019-11-06 00:49
> Hi @jiqimaogou
> Could you please provide your `flutter doctor -v`?
> If I understand correctly the issue is that during the animation
> the icon loses gestures detection, correct?
> Thank you

chenhjohn@chenhJohndeMacBook-Pro:~/Downloads/mediapipe% flutter doctor -v
[✓] Flutter (Channel beta, v1.10.7, on Mac OS X 10.14.6 18G87, locale zh-Hans-CN)
    • Flutter version 1.10.7 at /Users/chenhjohn/Library/Android/sdk/flutter
    • Framework revision e70236e36c (5 weeks ago), 2019-10-02 09:32:30 -0700
    • Engine revision 9e6314d348
    • Dart version 2.6.0 (build 2.6.0-dev.0.0 1103600280)

**Comment by jiqimaogou** [comment] 2019-11-06 00:52
replace the icon with a button, it happended.

https://github.com/flutter/flutter/blob/dev/examples/flutter_gallery/lib/demo/material/bottom_navigation_demo.dart#L61

**Comment by jiqimaogou** [comment] 2019-11-16 13:02
@iapicca can you see it?

**Comment by markusaksli-nc** [comment] 2020-09-15 12:51
Closing this issue since it is no longer relevant here.

@jiqimaogou if you can provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that demonstrates this on the latest version of flutter I can reopen it.

**Closed by markusaksli-nc** 2020-09-15 12:51 UTC
Labels: f: material design, framework, team: gallery
