### ISSUE TITLE
webview_flutter can't fullscreen the video on android platform

### ISSUE THREAD

**Issue by kkzone** [flutter/flutter#71191] opened 2020-11-25 01:58 UTC
webview_flutter can't fullscreen the video on android platform when I touch the fullscreen button.

**Comment by sidrao2006** [comment] 2020-11-25 03:24
Hello @kkzone ,
Could you please post the outputs of `flutter run -v` and `flutter doctor -v` and a complete [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
Thank you!

**Comment by sidrao2006** [comment] 2020-11-25 03:26
Duplicate of #27101
Hey @kkzone , I found an issue addressing this problem. Please post the output of `flutter doctor -v` and follow up there.

Thanks.

**Comment by kkzone** [comment] 2020-11-25 03:32
@sidrao2006 
[✓] Flutter (Channel stable, 1.22.3, on Mac OS X 10.15.5 19F101, locale
    zh-Hans-CN)
    • Flutter version 1.22.3 at /Users/kkzone/flutter_1.22.3
    • Framework revision 8874f21e79 (4 weeks ago), 2020-10-29 14:14:35 -0700
    • Engine revision a1440ca392
    • Dart version 2.10.3
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/kkzone/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.10.0

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[!] IntelliJ IDEA Ultimate Edition (version 2018.1.5)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (1 available)
    • iPhone X (mobile) • C758DE44-F0F6-4764-9BD4-E34D1C218FDD • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-13-6 (simulator)

**Comment by darshankawar** [comment] 2020-11-25 08:08
Closing this as duplicate of [27101](https://github.com/flutter/flutter/issues/27101)

**Closed by darshankawar** 2020-11-25 08:08 UTC
