### ISSUE TITLE
Crash In Flutter Codecs, Simple Two Field Form

### ISSUE THREAD

**Issue by aspectgfg** [flutter/flutter#20514] opened 2018-08-13 03:54 UTC
Looks like this might be an issue with autofocus. App crashes on the first of two `TextFormField` with the first having max length 1. The crash occurs when inputting characters past the maxLength limit. Note, the crash happens objective-c side.

```dart
TextFormField(maxLength: 1, autofocus: true, inputFormatters: [EmojiInputFormatter()])
```

Input formatter:
Put a try catch here in case this was this issue

```dart
class EmojiInputFormatter extends TextInputFormatter {
  @override
  TextEditingValue formatEditUpdate(
      TextEditingValue oldValue, TextEditingValue newValue) {
    try {
      if (Emojis._emojisMap.isNotEmpty) {
        if (newValue.text.runes.length > oldValue.text.runes.length) {
          var newRunes = newValue.text.runes
              .toList(growable: false)
              .sublist(oldValue.text.runes.length);
          for (var rune in newRunes) {
            if (!Emojis._emojisMap[rune]) {
              return oldValue;
            }
          }
          return newValue;
        } else {
          Emojis.emojisMap;
          return oldValue;
        }
      }
    } catch (e) {
      print(e.toString());
    }
  }
}
```

**Crash**

```
assertion failure in -[FlutterJSONMessageCodec encode:], ../../flutter/shell/platform/darwin/ios/framework/Source/FlutterCodecs.mm:71
```

```
20:08:18.369 27 info flutter.tools *** First throw call stack:
20:08:18.369 28 info flutter.tools (
20:08:18.369 29 info flutter.tools 	0   CoreFoundation                      0x000000010fb521e6 __exceptionPreprocess + 294
20:08:18.369 30 info flutter.tools 	1   libobjc.A.dylib                     0x000000010f1e7031 objc_exception_throw + 48
20:08:18.369 31 info flutter.tools 	2   CoreFoundation                      0x000000010fb57472 +[NSException raise:format:arguments:] + 98
20:08:18.369 32 info flutter.tools 	3   Foundation                          0x000000010e10c652 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 193
20:08:18.369 33 info flutter.tools 	4   Flutter                             0x000000010c93b5e4 -[FlutterJSONMessageCodec encode:] + 413
20:08:18.369 34 info flutter.tools 	5   Flutter                             0x000000010c93b8e3 -[FlutterJSONMethodCodec encodeMethodCall:] + 190
20:08:18.369 35 info flutter.tools 	6   Flutter                             0x000000010c93a7ac -[FlutterMethodChannel invokeMethod:arguments:] + 58
20:08:18.388 36 info flutter.tools Lost connection to device.
20:08:18.419 37 info flutter.tools 	7   Flutter                             0x000000010c947931 -[FlutterViewController updateEditingClient:wit<…>
```

Flutter:
```
Flutter 0.5.9-pre.23 • channel master • https://github.com/flutter/flutter.git
Framework • revision ba723b6038 (5 hours ago) • 2018-08-12 16:01:39 -0700
Engine • revision e54bc4ea18
Tools • Dart 2.0.0-dev.69.5.flutter-eab492385c
```

**Comment by goderbauer** [comment] 2020-03-04 23:20
Looks like a crash in the iOS version of FlutterJSONMessageCodec.

**Comment by darshankawar** [comment] 2020-10-23 09:42
@aspectgfg 
Is this still a valid issue on latest Flutter version ? 
I tried your code sample, but it seems to be incomplete, especially, not sure which plugin did you use for this line of code `Emojis._emojisMap`.  
If this issue still persists, can you provide a complete minimal reproducible code sample ?
thanks.

**Comment by pedromassangocode** [comment] 2020-11-13 12:03
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2020-11-13 12:03 UTC
Labels: P4, a: text input, engine, p: framework, platform-ios, plugin, severe: crash
