### ISSUE TITLE
Fatal signal 11 (SEGV_ACCERR) when running release build

### ISSUE THREAD

**Issue by captnplanet** [flutter/flutter#17392] opened 2018-05-08 17:18 UTC
## Steps to Reproduce

1. Use any branch on or after commit https://github.com/flutter/flutter/commit/a2951a9a1fed437422f9530fe82e4761dbedddbf
2. Run the release build with `flutter run --release`
3. The app will crash on launch

## Logs

```
05-08 10:53:31.033   495   495 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
05-08 10:53:31.033   495   495 F DEBUG   : Build fingerprint: 'Verizon/trltevzw/trltevzw:6.0.1/MMB29M/N910VVRU2CQL1:user/release-keys'
05-08 10:53:31.033   495   495 F DEBUG   : Revision: '12'
05-08 10:53:31.033   495   495 F DEBUG   : ABI: 'arm'
05-08 10:53:31.033   495   495 F DEBUG   : pid: 12282, tid: 12310, name: 1.ui  >>> com.clanhq.app <<<
05-08 10:53:31.033   495   495 F DEBUG   : signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 0x9eb57000
05-08 10:53:31.053   495   495 F DEBUG   :     r0 9c5fd04d  r1 9dcc0021  r2 9dcc0021  r3 9eb56fff
05-08 10:53:31.053   495   495 F DEBUG   :     r4 9dcc0021  r5 9dcc37b1  r6 9dcc2df9  r7 00000003
05-08 10:53:31.053   495   495 F DEBUG   :     r8 9c2fefe9  r9 00000000  sl adc9c800  fp 9ee527fc
05-08 10:53:31.053   495   495 F DEBUG   :     ip 9dcc0021  sp 9ee527e8  lr b2aa7168  pc b2aa73dc  cpsr 000b0010
05-08 10:53:31.053   495   495 F DEBUG   : 
05-08 10:53:31.053   495   495 F DEBUG   : backtrace:
05-08 10:53:31.053   495   495 F DEBUG   :     #00 pc 000003dc  /data/data/com.clanhq.app/app_flutter/vm_snapshot_instr
05-08 10:53:31.053   495   495 F DEBUG   :     #01 pc 00000164  /data/data/com.clanhq.app/app_flutter/vm_snapshot_instr
```

```
```

```
[✓] Flutter (Channel unknown, v0.4.0, on Linux, locale en_US.UTF-8)
    • Flutter version 0.4.0 at /home/paul/flutter
    • Framework revision 7984f6e043 (4 days ago), 2018-05-04 10:48:06 -0700
    • Engine revision e976be13c5
    • Dart version 2.0.0-dev.53.0.flutter-e6d7d67f4b

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /home/paul/Android/Sdk
    • Android NDK at /home/paul/Android/Sdk/ndk-bundle
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /usr/local/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 3.1)
    • Android Studio at /usr/local/android-studio
    • Flutter plugin version 23.2.2
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Community Edition (version 2018.1)
    • IntelliJ at /home/paul/.local/share/JetBrains/Toolbox/apps/IDEA-C/ch-0/181.4203.550
    • Flutter plugin version 24.0.2
    • Dart plugin version 181.4203.498

[✓] IntelliJ IDEA Community Edition (version 2017.2)
    • IntelliJ at /usr/local/idea-intellij
    • Flutter plugin version 19.1
    • Dart plugin version 172.4343.25

[✓] IntelliJ IDEA Community Edition (version 2017.3)
    • IntelliJ at /home/paul/.local/share/JetBrains/Toolbox/apps/IDEA-C/ch-0/173.4548.28
    • Flutter plugin version 22.0.2
    • Dart plugin version 173.4548.30

[✓] VS Code (version 1.22.2)
    • VS Code at /usr/share/code
    • Dart Code extension version 2.11.1

[✓] Connected devices (1 available)
    • SM N910V • f4c0da82 • android-arm • Android 6.0.1 (API 23)

• No issues found!

```

**Comment by carnivorePaul** [comment] 2018-05-08 17:19
Can we add the label `carnivore` to this?

**Comment by carnivorePaul** [comment] 2018-05-09 19:44
This started occurring at this Flutter revision: https://github.com/flutter/flutter/commit/a2951a9a1fed437422f9530fe82e4761dbedddbf

Which leads to this engine revision: https://github.com/flutter/engine/commit/ed303c628fe4b322529f8cf01ecb38135a2bab73

and this Dart SDK revision: https://github.com/dart-lang/sdk/commit/23ae4fa098a1c2011b72f5ad4d00383e1ac10a59

**Comment by ebeem** [comment] 2018-05-24 22:31
same problem (v0.4.4)

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.4.4, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] Android Studio (version 3.1)
[✓] Android Studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] IntelliJ IDEA Ultimate Edition (version 2018.1)
[!] IntelliJ IDEA Ultimate Edition (version 2017.3)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] Connected devices (1 available)

! Doctor found issues in 1 category.
flutter doctor  6.25s user 0.50s system 123% cpu 5.446 total
```

**Comment by Joyuan** [comment] 2018-06-06 07:28
same problem

**Comment by zoechi** [comment] 2018-07-27 08:59
Looks like a dup of #16793

Do you still experience that with newer Flutter versions?

**Comment by zoechi** [comment] 2018-12-06 13:07
Duplicate of #16793

**Closed by zoechi** 2018-12-06 13:07 UTC
Labels: customer: carnivore
