### ISSUE TITLE
alwaysUse24HourFormatOf doesn't get updated when toggle changes

### ISSUE THREAD

**Issue by alefwd** [flutter/flutter#135657] opened 2023-09-28 09:10 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Create a skeleton template app: fvm flutter create -t skeleton test_always_use_24h_format
2. Add 2 debug lines at the beginning of MyApp build():
```
  @override
  Widget build(BuildContext context) {
    final use24Hour = MediaQuery.alwaysUse24HourFormatOf(context);
    debugPrint('use 24 hour format: $use24Hour at ${DateTime.now()}');
    // Glue the SettingsController to the MaterialApp.
    //
```
3. have a real iPhone device with a locale which uses 12h format (for instance US)
4. Deploy the app
5. Go to Settings -> General -> Date & Time -> and change the toggle for "24-Hour Time"

### Expected results

I would expect to see the debug output with the updated value of the toggle (true / false)

### Actual results

What it happens instead, is that nothing is output, until you navigate to the app and then back to the Settings once more. Only at that time, the output is triggered.
I also tested this with different scenarios, and wait some time to see if it was iOS delaying the update, but nothing influenced the output, the only way I noticed to make the update to happen, is to navigate back to the Settings.

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter_gen/gen_l10n/app_localizations.dart';
import 'package:flutter_localizations/flutter_localizations.dart';

import 'sample_feature/sample_item_details_view.dart';
import 'sample_feature/sample_item_list_view.dart';
import 'settings/settings_controller.dart';
import 'settings/settings_view.dart';

/// The Widget that configures your application.
class MyApp extends StatelessWidget {
  const MyApp({
    super.key,
    required this.settingsController,
  });

  final SettingsController settingsController;

  @override
  Widget build(BuildContext context) {
    final use24Hour = MediaQuery.alwaysUse24HourFormatOf(context);
    debugPrint('use 24 hour format: $use24Hour at ${DateTime.now()}');

    // Glue the SettingsController to the MaterialApp.
    //
    // The ListenableBuilder Widget listens to the SettingsController for changes.
    // Whenever the user updates their settings, the MaterialApp is rebuilt.
    return ListenableBuilder(
      listenable: settingsController,
      builder: (BuildContext context, Widget? child) {
        return MaterialApp(
          // Providing a restorationScopeId allows the Navigator built by the
          // MaterialApp to restore the navigation stack when a user leaves and
          // returns to the app after it has been killed while running in the
          // background.
          restorationScopeId: 'app',

          // Provide the generated AppLocalizations to the MaterialApp. This
          // allows descendant Widgets to display the correct translations
          // depending on the user's locale.
          localizationsDelegates: const [
            AppLocalizations.delegate,
            GlobalMaterialLocalizations.delegate,
            GlobalWidgetsLocalizations.delegate,
            GlobalCupertinoLocalizations.delegate,
          ],
          supportedLocales: const [
            Locale('en', ''), // English, no country code
          ],

          // Use AppLocalizations to configure the correct application title
          // depending on the user's locale.
          //
          // The appTitle is defined in .arb files found in the localization
          // directory.
          onGenerateTitle: (BuildContext context) =>
              AppLocalizations.of(context)!.appTitle,

          // Define a light and dark color theme. Then, read the user's
          // preferred ThemeMode (light, dark, or system default) from the
          // SettingsController to display the correct theme.
          theme: ThemeData(),
          darkTheme: ThemeData.dark(),
          themeMode: settingsController.themeMode,

          // Define a function to handle named routes in order to support
          // Flutter web url navigation and deep linking.
          onGenerateRoute: (RouteSettings routeSettings) {
            return MaterialPageRoute<void>(
              settings: routeSettings,
              builder: (BuildContext context) {
                switch (routeSettings.name) {
                  case SettingsView.routeName:
                    return SettingsView(controller: settingsController);
                  case SampleItemDetailsView.routeName:
                    return const SampleItemDetailsView();
                  case SampleItemListView.routeName:
                  default:
                    return const SampleItemListView();
                }
              },
            );
          },
        );
      },
    );
  }
}
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
$ fvm flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.4, on macOS 13.5.2 22G91 darwin-arm64, locale en-FI)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] IntelliJ IDEA Community Edition (version 2023.2.1)
[✓] VS Code (version 1.82.2)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by dam-ease** [comment] 2023-09-28 11:59
Hi @alefwd. Thanks for filing this. I can reproduce this on the latest `master` and `stable` channels following the steps highlighted above. 

<details><summary>Logs</summary>
<p>

```

2023-09-28 12:46:21.742624+0100 Runner[1444:386265] flutter: The Dart VM service is listening on http://127.0.0.1:52937/6teBzoWZ5sw=/
2023-09-28 12:46:21.920916+0100 Runner[1444:386228] flutter: use 24 hour format: false at 2023-09-28 12:46:21.897810
2023-09-28 12:47:33.059193+0100 Runner[1444:386228] flutter: use 24 hour format: true at 2023-09-28 12:47:33.054878
``` 

</p>
</details>

**Comment by TahaTesser** [comment] 2023-09-29 15:20
duplicate of https://github.com/flutter/flutter/issues/12531 
See https://github.com/flutter/flutter/issues/13703

**Closed by TahaTesser** 2023-09-29 15:20 UTC
Labels: framework, f: material design, a: internationalization, has reproducible steps, team-design, found in release: 3.13, found in release: 3.15

**Comment by TahaTesser** [comment] 2023-09-29 18:56
@alefwd
https://github.com/flutter/flutter/issues/13703 and other issues are closed for https://github.com/flutter/flutter/issues/12531 to address this problem systematically.  Please see why https://github.com/flutter/flutter/issues/13703 is closed [here](https://github.com/flutter/flutter/issues/13703#issuecomment-712437165)
