### ISSUE TITLE
The Impeller GLES backend is failing on Linux.

### ISSUE THREAD

**Issue by whiskeyPeak** [flutter/flutter#130558] opened 2023-07-14 05:14 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

This is running on a Dell XPS 9500, with an intel CPU and NVIDIA GPU.

### Steps to reproduce

1. Create a new flutter app on the master channel
2. Run `flutter run --enable-impeller`

I get 2 errors:

`[ERROR:flutter/impeller/base/validation.cc(49)] Break on 'ImpellerValidationBreak' to inspect point of failure: Could not determine GL version.`

`[ERROR:flutter/shell/common/platform_view.cc(76)] Failed to create platform view rendering surface`

This is what the window looks like:

![Screenshot from 2023-07-14 06-13-13](https://github.com/flutter/flutter/assets/73116038/d8c24338-d149-431a-8253-eef8ad78356b)

### Actual results

Flutter actually rendering something on screen with no log errors.

### Logs

<details>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

<details>
<summary>Doctor output</summary>

```console

[✓] Flutter (Channel master, 3.13.0-3.0.pre.55, on LMDE 5 (elsie) 5.10.0-23-amd64, locale en_GB.UTF-8)
    • Flutter version 3.13.0-3.0.pre.55 on channel master at /home/henryr/Dev/SDK/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4c0c8c3045 (37 minutes ago), 2023-07-14 00:37:12 -0400
    • Engine revision 8d14461f7b
    • Dart version 3.1.0 (build 3.1.0-309.0.dev)
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /home/henryr/Android/Sdk
    • Platform android-33, build-tools 33.0.2
    • Java binary at: /home/henryr/Dev/SDK/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Debian clang version 11.0.1-2
    • cmake version 3.18.4
    • ninja version 1.11.1
    • pkg-config version 0.29.2

[✓] Android Studio (version 2022.1)
    • Android Studio at /home/henryr/Dev/SDK/android-studio
    • Flutter plugin version 73.0.1
    • Dart plugin version 221.6103.1
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] IntelliJ IDEA Community Edition (version 2023.1)
    • IntelliJ at /home/henryr/Dev/SDK/idea-IC-231.9161.38
    • Flutter plugin version 74.0.4
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • LMDE 5 (elsie) 5.10.0-23-amd64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 114.0.5735.198

[✓] Network resources
    • All expected network resources are available.

• No issues found!


```

</details>

**Comment by jonahwilliams** [comment] 2023-07-14 05:24
Duplicate of https://github.com/flutter/flutter/issues/130514

**Closed by jonahwilliams** 2023-07-14 05:24 UTC
