### ISSUE TITLE
Writing 100% dart code to run in background. 

### ISSUE THREAD

**Issue by JuniorBee** [flutter/flutter#24086] opened 2018-11-08 00:16 UTC
There should be real way to execute code in background. I know that this is a duplicate. But it is FFF***ing hard to create a simple alarm clock using a Framework that "almighty Google" supports.

**Comment by zsirfs** [comment] 2018-11-08 01:40
Kill the dart process and restart dart analysis

**Comment by zoechi** [comment] 2019-01-04 10:04
Duplicate of #24278

**Closed by zoechi** 2019-01-04 10:04 UTC
Labels: engine, framework, p: framework, severe: new feature
