### ISSUE TITLE
[web] Apps shows wrong icons after updates

### ISSUE THREAD

**Issue by tbarbette** [flutter/flutter#80646] opened 2021-04-17 14:21 UTC
After updating my app, I now see these icons :
![image](https://user-images.githubusercontent.com/248961/115116150-74e5e180-9f98-11eb-9f6c-dfb82d70419e.png)
Instead of these ones : 
![image](https://user-images.githubusercontent.com/248961/115116180-99da5480-9f98-11eb-9767-8692923dec41.png)

Now when using Chrome's "disable cache" mode the issue appears, but in private navigation it does not show.

Results of analyze : 
```
Warning: You are using these overridden dependencies:
! args 2.0.0
! http 0.12.2 (0.13.1 available)
! intl 0.17.0
! package_config 2.0.0
! plugin_platform_interface 2.0.0
! xml 5.1.0
! yaml 3.1.0
Running "flutter pub get" in mariage...                          1 412ms
Analyzing mariage...

   info - This class (or a class that this class inherits from) is marked as '@immutable', but one or more of its instance fields aren't final:
          AdminModel.model, AdminModel.onSave - lib\admin\adminmodel.dart:63:7 - must_be_immutable
   info - This function has a return type of 'Widget', but doesn't end with a return statement - lib\admin\adminmodel.dart:111:10 - missing_return
warning - Missing case clause for 'manyForeign' - lib\admin\adminmodel.dart:113:5 - missing_enum_constant_in_switch
   info - This class (or a class that this class inherits from) is marked as '@immutable', but one or more of its instance fields aren't final:
          ImageField.controller, ImageField.onFieldSubmitted - lib\admin\imagefield.dart:7:7 - must_be_immutable
   info - Use `;` instead of `{}` for empty constructor bodies - lib\admin\imagefield.dart:11:56 - empty_constructor_bodies
   info - Name non-constant identifiers using lowerCamelCase - lib\adminevents.dart:15:10 - non_constant_identifier_names
   info - Avoid empty statements - lib\adminevents.dart:29:7 - empty_statements
   info - Avoid empty statements - lib\adminevents.dart:31:5 - empty_statements
   info - This method overrides a method annotated as '@mustCallSuper' in 'State', but doesn't invoke the overridden method -
          lib\adminevents.dart:36:8 - must_call_super
   info - Name non-constant identifiers using lowerCamelCase - lib\adminevents.dart:59:19 - non_constant_identifier_names
   info - Avoid using braces in interpolation when not needed - lib\adminevents.dart:85:53 - unnecessary_brace_in_string_interps
   info - Avoid using braces in interpolation when not needed - lib\adminevents.dart:85:73 - unnecessary_brace_in_string_interps
   info - Avoid using braces in interpolation when not needed - lib\adminevents.dart:85:142 - unnecessary_brace_in_string_interps
   info - Avoid using braces in interpolation when not needed - lib\adminevents.dart:85:163 - unnecessary_brace_in_string_interps
   info - Avoid using braces in interpolation when not needed - lib\adminevents.dart:85:183 - unnecessary_brace_in_string_interps
   info - Name non-constant identifiers using lowerCamelCase - lib\admingifts.dart:15:10 - non_constant_identifier_names
   info - This method overrides a method annotated as '@mustCallSuper' in 'State', but doesn't invoke the overridden method - lib\admingifts.dart:18:8
          - must_call_super
   info - Name non-constant identifiers using lowerCamelCase - lib\admingroupinvites.dart:16:10 - non_constant_identifier_names
   info - This method overrides a method annotated as '@mustCallSuper' in 'State', but doesn't invoke the overridden method -
          lib\admingroupinvites.dart:19:8 - must_call_super
   info - Unused import: 'model/guest.dart' - lib\admingroups.dart:8:8 - unused_import
   info - Name non-constant identifiers using lowerCamelCase - lib\admingroups.dart:16:10 - non_constant_identifier_names
   info - This method overrides a method annotated as '@mustCallSuper' in 'State', but doesn't invoke the overridden method -
          lib\admingroups.dart:19:8 - must_call_super
   info - Name non-constant identifiers using lowerCamelCase - lib\adminguests.dart:14:10 - non_constant_identifier_names
   info - This method overrides a method annotated as '@mustCallSuper' in 'State', but doesn't invoke the overridden method -
          lib\adminguests.dart:17:8 - must_call_super
   info - Name non-constant identifiers using lowerCamelCase - lib\answer.dart:25:10 - non_constant_identifier_names
   info - 'List' is deprecated and shouldn't be used. Use a list literal, [], or the List.filled constructor instead - lib\answer.dart:27:31 -
          deprecated_member_use
   info - Don't explicitly initialize variables to null - lib\answer.dart:36:12 - avoid_init_to_null
   info - Avoid empty statements - lib\answer.dart:293:33 - empty_statements
   info - Dead code - lib\answer.dart:293:33 - dead_code
  error - This requires the 'non-nullable' language feature to be enabled - lib\gen\assets.gen.dart:73:8 - experiment_not_enabled
  error - This requires the 'non-nullable' language feature to be enabled - lib\gen\assets.gen.dart:74:22 - experiment_not_enabled
  error - This requires the 'non-nullable' language feature to be enabled - lib\gen\assets.gen.dart:75:24 - experiment_not_enabled
  error - This requires the 'non-nullable' language feature to be enabled - lib\gen\assets.gen.dart:76:28 - experiment_not_enabled
  error - This requires the 'non-nullable' language feature to be enabled - lib\gen\assets.gen.dart:77:11 - experiment_not_enabled
  error - This requires the 'non-nullable' language feature to be enabled - lib\gen\assets.gen.dart:79:11 - experiment_not_enabled
  error - This requires the 'non-nullable' language feature to be enabled - lib\gen\assets.gen.dart:80:11 - experiment_not_enabled
  error - This requires the 'non-nullable' language feature to be enabled - lib\gen\assets.gen.dart:81:10 - experiment_not_enabled
  error - This requires the 'non-nullable' language feature to be enabled - lib\gen\assets.gen.dart:82:14 - experiment_not_enabled
  error - This requires the 'non-nullable' language feature to be enabled - lib\gen\assets.gen.dart:83:11 - experiment_not_enabled
  error - This requires the 'non-nullable' language feature to be enabled - lib\gen\assets.gen.dart:86:9 - experiment_not_enabled
   info - Don't import implementation files from another package - lib\generated_plugin_registrant.dart:7:8 - implementation_imports
   info - Avoid using braces in interpolation when not needed - lib\gifts.dart:63:49 - unnecessary_brace_in_string_interps
   info - The declaration '_kMinFlingVelocity' isn't referenced - lib\gifts.dart:161:14 - unused_element
   info - This class (or a class that this class inherits from) is marked as '@immutable', but one or more of its instance fields aren't final:
          GiftDetailPage.gift - lib\gifts.dart:260:7 - must_be_immutable
   info - This class (or a class that this class inherits from) is marked as '@immutable', but one or more of its instance fields aren't final:
          GridDemoPhotoItem.gift, GridDemoPhotoItem.onChange - lib\gifts.dart:357:7 - must_be_immutable
   info - The value of the local variable 'icon' isn't used - lib\gifts.dart:409:20 - unused_local_variable
   info - Name non-constant identifiers using lowerCamelCase - lib\home.dart:67:12 - non_constant_identifier_names
   info - Name non-constant identifiers using lowerCamelCase - lib\home.dart:68:10 - non_constant_identifier_names
   info - Use `;` instead of `{}` for empty constructor bodies - lib\home.dart:100:9 - empty_constructor_bodies
   info - The value of the local variable 'ps' isn't used - lib\home.dart:137:10 - unused_local_variable
   info - Name non-constant identifiers using lowerCamelCase - lib\home.dart:270:14 - non_constant_identifier_names
   info - Name non-constant identifiers using lowerCamelCase - lib\home.dart:336:16 - non_constant_identifier_names
   info - Name non-constant identifiers using lowerCamelCase - lib\home.dart:337:16 - non_constant_identifier_names
   info - Don't explicitly initialize variables to null - lib\home.dart:338:8 - avoid_init_to_null
   info - The value of the field '_reponse' isn't used - lib\home.dart:420:13 - unused_field
   info - The value of the field '_navigation' isn't used - lib\home.dart:421:13 - unused_field
   info - 'FlatButton' is deprecated and shouldn't be used. Use TextButton instead. See the migration guide in
          flutter.dev/go/material-button-migration-guide). This feature was deprecated after v1.26.0-18.0.pre. - lib\home.dart:550:36 -
          deprecated_member_use
   info - Name non-constant identifiers using lowerCamelCase - lib\home.dart:634:10 - non_constant_identifier_names
   info - This class (or a class that this class inherits from) is marked as '@immutable', but one or more of its instance fields aren't final:
          Loading.status - lib\loading.dart:16:7 - must_be_immutable
   info - This class (or a class that this class inherits from) is marked as '@immutable', but one or more of its instance fields aren't final:
          LoadingApp.status - lib\loading.dart:55:7 - must_be_immutable
   info - This class (or a class that this class inherits from) is marked as '@immutable', but one or more of its instance fields aren't final:
          MyLoginPage.bad - lib\login.dart:12:7 - must_be_immutable
   info - This method overrides a method annotated as '@mustCallSuper' in 'State', but doesn't invoke the overridden method - lib\login.dart:41:8 -
          must_call_super
   info - This class (or a class that this class inherits from) is marked as '@immutable', but one or more of its instance fields aren't final:
          MyApp.guest, MyApp.bad - lib\main.dart:99:7 - must_be_immutable
   info - The library 'package:mariage/model/event.dart' is legacy, and should not be imported into a null safe library - lib\main.mapper.g.dart:6:8 -
          import_of_legacy_library_into_null_safe
   info - The library 'package:mariage/model/gifts.dart' is legacy, and should not be imported into a null safe library - lib\main.mapper.g.dart:7:8 -
          import_of_legacy_library_into_null_safe
   info - The library 'package:mariage/model/group.dart' is legacy, and should not be imported into a null safe library - lib\main.mapper.g.dart:8:8 -
          import_of_legacy_library_into_null_safe
   info - The library 'package:mariage/model/guest.dart' is legacy, and should not be imported into a null safe library - lib\main.mapper.g.dart:9:8 -
          import_of_legacy_library_into_null_safe
   info - The library 'package:mariage/model/event.dart' is legacy, and should not be imported into a null safe library - lib\main.mapper.g.dart:19:8
          - import_of_legacy_library_into_null_safe
   info - The library 'package:mariage/model/gifts.dart' is legacy, and should not be imported into a null safe library - lib\main.mapper.g.dart:20:8
          - import_of_legacy_library_into_null_safe
   info - The library 'package:mariage/model/group.dart' is legacy, and should not be imported into a null safe library - lib\main.mapper.g.dart:21:8
          - import_of_legacy_library_into_null_safe
   info - The library 'package:mariage/model/guest.dart' is legacy, and should not be imported into a null safe library - lib\main.mapper.g.dart:22:8
          - import_of_legacy_library_into_null_safe
   info - The library 'package:mariage/model/model.dart' is legacy, and should not be imported into a null safe library - lib\main.mapper.g.dart:23:8
          - import_of_legacy_library_into_null_safe
   info - Don't import implementation files from another package - lib\model\backend.dart:1:8 - implementation_imports
   info - Don't explicitly initialize variables to null - lib\model\backend.dart:9:16 - avoid_init_to_null
   info - The name JsonProperty is shown, but isn’t used - lib\model\event.dart:4:40 - unused_shown_name
   info - Name non-constant identifiers using lowerCamelCase - lib\model\event.dart:15:7 - non_constant_identifier_names
   info - Name non-constant identifiers using lowerCamelCase - lib\model\event.dart:17:49 - non_constant_identifier_names
   info - 'List' is deprecated and shouldn't be used. Use a list literal, [], or the List.filled constructor instead - lib\model\event.dart:82:34 -
          deprecated_member_use
   info - The value of the local variable 'response' isn't used - lib\model\event.dart:144:22 - unused_local_variable
   info - The value of the local variable 'm' isn't used - lib\model\event.dart:167:9 - unused_local_variable
   info - The value of the local variable 'response' isn't used - lib\model\event.dart:228:24 - unused_local_variable
   info - The value of the local variable 'response' isn't used - lib\model\event.dart:231:24 - unused_local_variable
   info - Unnecessary cast - lib\model\event.dart:237:30 - unnecessary_cast
   info - The name SerializationOptions is shown, but isn’t used - lib\model\gifts.dart:5:36 - unused_shown_name
   info - 'List' is deprecated and shouldn't be used. Use a list literal, [], or the List.filled constructor instead - lib\model\gifts.dart:117:24 -
          deprecated_member_use
   info - 'List' is deprecated and shouldn't be used. Use a list literal, [], or the List.filled constructor instead - lib\model\gifts.dart:149:24 -
          deprecated_member_use
   info - The value of the local variable 'response' isn't used - lib\model\gifts.dart:181:22 - unused_local_variable
   info - 'List' is deprecated and shouldn't be used. Use a list literal, [], or the List.filled constructor instead - lib\model\group.dart:50:25 -
          deprecated_member_use
   info - The value of the local variable 'response' isn't used - lib\model\group.dart:81:22 - unused_local_variable
   info - The value of the local variable 'events' isn't used - lib\model\group.dart:89:17 - unused_local_variable
   info - 'List' is deprecated and shouldn't be used. Use a list literal, [], or the List.filled constructor instead - lib\model\group.dart:171:31 -
          deprecated_member_use
   info - The value of the local variable 'response' isn't used - lib\model\group.dart:222:22 - unused_local_variable
   info - Unnecessary cast - lib\model\group.dart:280:30 - unnecessary_cast
   info - The name JsonProperty is shown, but isn’t used - lib\model\guest.dart:5:40 - unused_shown_name
   info - 'List' is deprecated and shouldn't be used. Use a list literal, [], or the List.filled constructor instead - lib\model\guest.dart:163:25 -
          deprecated_member_use
   info - The value of the local variable 'response' isn't used - lib\model\guest.dart:197:22 - unused_local_variable

96 issues found. (ran in 10.1s)
```
Nothing looks related.

Doctor:
```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, 2.1.0-12.2.pre, on Microsoft Windows [version 10.0.19043.906], locale fr-BE)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] VS Code (version 1.55.2)
[√] Connected device (2 available)

• No issues found!
```

**Comment by tbarbette** [comment] 2021-04-17 17:58
Note that this disappeared when I switched back to the stable version.

**Comment by iapicca** [comment] 2021-04-17 21:33
I cannot reproduce the issue with the current beta (@tbarbette  just run `flutter upgrade -f`)

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(
    const MaterialApp(
      home: Material(
        child: Center(
          child: ListTile(
            leading: Text('ac_unit'),
            trailing: Icon(Icons.ac_unit),
          ),
        ),
      ),
    ),
  );
}

```
</details>

![image](https://user-images.githubusercontent.com/45637986/115127150-f65f6300-9fdc-11eb-9727-2bf463c46486.png)

<details>
<summary>doctor</summary>

```console
[✓] Flutter (Channel beta, 2.2.0-10.1.pre, on Linux, locale en_US.UTF-8)
    • Flutter version 2.2.0-10.1.pre at
      /home/francesco/snap/flutter/common/flutter
    • Framework revision 0941968447 (2 days ago), 2021-04-15 12:01:02 -0700
    • Engine revision d2a2e93510
    • Dart version 2.13.0 (build 2.13.0-211.6.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/francesco/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_SDK_ROOT = /home/francesco/Android/Sdk
    • Java binary at: /usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_282-8u282-b08-0ubuntu1~20.04-b08)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /snap/bin/chromium

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup
      for detailed instructions).

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Linux
    • Chrome (web)    • chrome • web-javascript • Chromium 90.0.4430.72 snap

! Doctor found issues in 1 category.
```

</details>

nevertheless this issue seems to keep reappearing https://github.com/flutter/flutter/issues/62472
it would be nice to add some test to prevent the issue from re-emerging 
before closing the issue

**Comment by pedromassangocode** [comment] 2021-04-19 10:48
Hi @tbarbette 
Can you please share a minimal reproducible code sample?

**Comment by iapicca** [comment] 2021-04-19 11:57
@pedromassango 
does this [code](https://github.com/flutter/flutter/issues/62472#issue-667602907)
reproduce with the version [initially reported](https://github.com/flutter/flutter/issues/80646#issue-860421352)?

> flutter doctor
> Doctor summary (to see all details, run flutter doctor -v):
> [√] Flutter (Channel beta, 2.1.0-12.2.pre, on Microsoft Windows [version 10.0.19043.906], locale fr-BE)
> [√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
> [√] Chrome - develop for the web
> [√] Android Studio (version 4.1.0)
> [√] VS Code (version 1.55.2)
> [√] Connected device (2 available)
> 
> • No issues found!

**Comment by tbarbette** [comment] 2021-04-19 12:06
That is not possible. It was due to an update I did not even really catched. My website was working, then after some recent updates (of flutter and really a little bit of code) it showed that icon shift. But private navigation and new browsers do not show the problem. Forcing cache reload ("disable cache" in chrome debugger) does not solve the problem. Probably I'd have to clear the local storage? But if I did that I would not be able to reproduce the problem and be sure my users do not face the problem. Now it is solved by going to stable (and upgrading all dependencies to do so).

I won't be able to help much further I think... Especially that it's a personal app and I don't have many resources. As @iapicca mentioned it just keeps re-appearing. I hoped by raising the flag someone in the team would think of how the icons can "shift" like that. Maybe the font has been updated, and the "index" of the icons is kept in the old storage? But it would take too much time for me to go back to an old unstable, publish a web version, re-publish after upgrade, etc...

**Comment by pedromassangocode** [comment] 2021-04-19 12:51
This seems to be the same as https://github.com/flutter/flutter/issues/76442 as you both said is just the same issue appearing from time to time. 

My suggestion is that we close this as duplicate of https://github.com/flutter/flutter/issues/76442 (by fixing https://github.com/flutter/flutter/issues/76442 this one get fixed as well) to make sure we don't have two different issues targeting the same problem.

**Comment by iapicca** [comment] 2021-04-19 12:53
@pedromassangocode sounds like a plan

**Comment by pedromassangocode** [comment] 2021-05-12 11:38
I'm closing this as a duplicate of https://github.com/flutter/flutter/issues/76442, please see https://github.com/flutter/flutter/issues/80646#issuecomment-822441994 for reasons.

Thank you

**Closed by pedromassangocode** 2021-05-12 11:38 UTC
Labels: in triage, waiting for customer response

**Comment by tbarbette** [comment] 2021-05-29 10:11
This just happened again, FYI. It was fine, then I just did an update in production like always and now it displays incorrectly again. The shift of icon is the same then last time. And again, in private browsing / new users don't see the problem. But existing ones do see the problem, even with the "No cache option" in Chrome dev.
**However I could try this time "clear site data" in "application" and it fixed the problem.**
Despite this is good news for debugging, I'm now in a very bad situation as I can't know if my problem is fixed for real users... This never showed in development, of course :) Wouldn't be fun.

![image](https://user-images.githubusercontent.com/248961/120066400-6ea65300-c076-11eb-8f08-7c84ee480fbf.png)
