### ISSUE TITLE
Hot reload not working on latest flutter beta on vs code auto save

### ISSUE THREAD

**Issue by Shreemanarjun** [flutter/flutter#75875] opened 2021-02-11 21:57 UTC
## Steps to Reproduce
![image](https://user-images.githubusercontent.com/24736211/107703585-d8763900-6ce1-11eb-97a2-cc64f1cb133e.png)

1. create default example app in vs code
2. change any strings or wrap any widget to auto save in vs code
3. no hot reload happen
 **Intended Behavior: Auto save and hot reload** 

## Logs

<details>
<summary>Logs</summary>

```
```

```
```

</details>

**Comment by nt4f04uNd** [comment] 2021-02-12 05:12
dup https://github.com/flutter/flutter/issues/75456

**Comment by TahaTesser** [comment] 2021-02-12 08:22
Hi @Shreemanarjun 
Please check out https://github.com/flutter/flutter/issues/75456#issuecomment-773724721
Closing as duplicate of https://github.com/flutter/flutter/issues/75456

For issues/proposals for [VS Code Flutter Extension](https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter), file issue on their [repository](https://github.com/Dart-Code/Dart-Code/issues).
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-02-12 08:22 UTC
