### ISSUE TITLE
[Impeller]: Text wobbles when transformation is applied via animation.

### ISSUE THREAD

**Issue by eli1stark** [flutter/flutter#151429] opened 2024-07-08 19:08 UTC
### Steps to reproduce

Flutter 3.24.0-1.0.pre.45 • channel master •
https://github.com/flutter/flutter.git
Framework • revision 0a4f1a7e55 (2 hours ago) • 2024-07-08 19:21:14 +0200
Engine • revision 69075e7e87

Not reproduced with Impeller disabled.

Reproduced on stable, beta and master.

1. Tested on the latest flutter revision with Impeller enabled.
2. Copy the code, paste it into your app.
3. Drag Containers and Press the top container to reproduce the bug.

### Expected results

Text should not wobble.

### Actual results

Text wobbles when transformation of scale or rotation is applied.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'dart:math' as math;

import 'package:flutter/material.dart';
import 'package:flutter/physics.dart';

class TextBug extends StatefulWidget {
  const TextBug({super.key});

  @override
  State<TextBug> createState() => _TextBugState();
}

class _TextBugState extends State<TextBug> with TickerProviderStateMixin {
  late final AnimationController _dragController;
  late final AnimationController _scaleController;
  late Animation<double> _animation;
  late Animation<double> _scale;

  double _dy = 0;

  final spring = const SpringDescription(
    mass: 1,
    stiffness: 400,
    damping: 20,
  );

  @override
  void initState() {
    super.initState();

    _scale = const AlwaysStoppedAnimation(1);
    _dragController = AnimationController(vsync: this);
    _scaleController = AnimationController(vsync: this);

    _dragController.addListener(() {
      setState(() {
        _dy = _animation.value;
      });
    });

    _scaleController.addListener(() {
      setState(() {});
    });
  }

  @override
  void dispose() {
    _dragController.dispose();
    super.dispose();
  }

  void _runAnimation() {
    _animation = _dragController.drive(
      Tween<double>(
        begin: _dy,
        end: 0,
      ),
    );

    _dragController.animateWith(SpringSimulation(spring, 0, 1, 1));
  }

  void _runScale(double begin, double end) {
    _scale = _scaleController.drive(
      Tween<double>(
        begin: begin,
        end: end,
      ),
    );

    _scaleController.animateWith(SpringSimulation(spring, 0, 1, 1));
  }

  double get _angle {
    return (12 * (_dy / 200)) * (math.pi / 180);
  }

  @override
  Widget build(BuildContext context) {
    return Transform.translate(
      offset: Offset(0, _dy),
      child: GestureDetector(
        onPanUpdate: (details) {
          setState(() {
            _dy += details.delta.dy;
          });
        },
        onPanDown: (_) {},
        onPanEnd: (_) async {
          _runAnimation();
        },
        child: Column(
          children: [
            GestureDetector(
              onPanDown: (_) {
                _runScale(1, 0.7);
              },
              onTapUp: (_) async {
                _runScale(0.7, 1);
              },
              child: Transform.scale(
                scale: _scale.value,
                child: const Sample(),
              ),
            ),
            const SizedBox(
              height: 20,
            ),
            Row(
              children: [
                Transform.rotate(
                  angle: _angle,
                  child: const Sample(),
                ),
                const SpaceW20(),
                Transform.rotate(
                  angle: -_angle,
                  child: const Sample(),
                ),
              ],
            ),
          ],
        ),
      ),
    );
  }
}

class Sample extends StatelessWidget {
  const Sample({super.key});

  @override
  Widget build(BuildContext context) {
    return Container(
      color: Colors.white,
      padding: const EdgeInsets.all(20),
      child: const Column(
        children: [
          Text(
            '600',
            style: TextStyle(
              color: Colors.black,
              fontSize: 50,
            ),
          ),
          Text(
            'buggy',
            style: TextStyle(
              color: Colors.black,
              fontSize: 30,
            ),
          ),
          Text(
            'AKQBC',
            style: TextStyle(
              color: Colors.black,
              fontSize: 30,
            ),
          ),
        ],
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/flutter/flutter/assets/57593530/6454361c-6c3a-4f49-a6f4-c1ee3f91f75d

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 3.24.0-1.0.pre.45, on macOS 14.5 23F79 darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.90.2)
[✓] Connected device (6 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by jonahwilliams** [comment] 2024-07-08 19:10
I believe this is a duplicate of https://github.com/flutter/flutter/issues/149652 .

**Closed by jonahwilliams** 2024-07-08 19:10 UTC
