### ISSUE TITLE
[Fidelity] - Unable to achieve navigation like the iOS Contacts app create flow.

### ISSUE THREAD

**Issue by patniemeyer** [flutter/flutter#45819] opened 2019-11-29 15:17 UTC
I would like to achieve a navigation effect like the one for adding a new Contact on iOS.   What iOS does in this case is to push a fullscreen modal add contact view which, when popped, does not return the user to the original screen but instead reveals a new navigation state where the user is shown the newly created contact’s view.  The effect is that the save has interposed a push to the Contact view screen “below” the current route, which is revealed by the pop and can then be dismissed normally to go back to the original screen.

I was hopeful that Navigator replaceRouteBelow() would solve this problem, but that only seems to be applicable if is there is a route to replace.  I can’t see any way to inject a new route into the stack. 

Am I missing a way to achieve this or is there a reason that Flutter does not expose the navigation stack more fully?

**Comment by humazed** [comment] 2019-12-01 12:41
A workaround would be using will `WillPopScope` and in `onWillPop` navigate to the newly created contact’s view by `pushReplacement` so when the user goes back he ends up in the original screen.

**Comment by patniemeyer** [comment] 2019-12-01 15:50
> A workaround would be using will `WillPopScope` and in `onWillPop` navigate to the newly created contact’s view by `pushReplacement` so when the user goes back he ends up in the original screen.

Thanks for the suggestion.   The issue with this is that the user still sees the push and it's not really "revealed" by the modal.  I'm currently doing something similar where I wait for the push to return (with `await Navigator.push()`) and then push the new view using a custom transition with no animation.  It's close, but not really correct.  It could be improved by further customizing the transition to do the forward push non-animated but then still show the correct reverse animation when the user goes back.  But I was hoping there might be better way :(

**Comment by HansMuller** [comment] 2019-12-04 16:04
CC @justinmc

**Comment by justinmc** [comment] 2019-12-16 23:02
@patniemeyer I think this is a duplicate of https://github.com/flutter/flutter/issues/33798, but let me know if I'm wrong and I'll reopen.

I did a little bit of exploration on how to achieve this and I hope to get back to it soon.  This is a major feature that I have planned.

**Closed by justinmc** 2019-12-16 23:02 UTC
Labels: a: fidelity, f: cupertino, f: routes, proposal
