### ISSUE TITLE
Flutter doctor gives "Unable to find bundled Java version" Android Studio Electric Eel version - Linux Mint 21.1

### ISSUE THREAD

**Issue by vgazioglu** [flutter/flutter#119142] opened 2023-01-25 15:05 UTC
Running "flutter doctor" after an upgrade to Android Studio Electric Eel version on Linux Mint 21.1, i get "Unable to find bundled Java version" .

Solution:
The bundled jre directory in this version of Android Studio installation folder is renamed to jbr

To resolve the issue, just create a sym link (For flatpak installation)

cd /var/lib/flatpak/app/com.google.AndroidStudio/current/active/files/extra/android-studio
sudo ln -s jbr jre

**Comment by crcdng** [comment] 2023-01-25 15:27
Same problem here on Flutter 3.7.0 Mac / Android Studio Electric Eel | 2022.1.1

**Comment by stuartmorgan** [comment] 2023-01-25 16:14
Duplicate of https://github.com/flutter/flutter/issues/106674

**Closed by stuartmorgan** 2023-01-25 16:14 UTC
