### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by waseemarain4u** [flutter/flutter#40660] opened 2019-09-17 10:30 UTC
```
D/skia    (21484): Errors:
D/skia    (21484): ERROR: The GPU does not support this version of OpenGL ES, try an older version
D/skia    (21484): 
I/Adreno  (21484): ERROR: The GPU does not support this version of OpenGL ES, try an older version
D/skia    (21484): Shader compilation error
D/skia    (21484): ------------------------
D/skia    (21484):    1	#version 310 es
D/skia    (21484):    2	
D/skia    (21484):    3	in highp vec4 sk_FragCoord_Workaround;
D/skia    (21484):    4	precision mediump float;
D/skia    (21484):    5	precision mediump sampler2D;
D/skia    (21484):    6	out mediump vec4 sk_FragColor;
D/skia    (21484):    7	uniform sampler2D uTextureSampler_0_Stage0;
D/skia    (21484):    8	in highp vec2 vTextureCoords_Stage0;
D/skia    (21484):    9	flat in highp int vTexIndex_Stage0;
D/skia    (21484):   10	in mediump vec4 vinColor_Stage0;
D/skia    (21484):   11	void main() {
D/skia    (21484):   12	    mediump vec4 outputColor_Stage0;
D/skia    (21484):   13	    mediump vec4 outputCoverage_Stage0;
D/skia    (21484):   14	    {
D/skia    (21484):   15	        outputColor_Stage0 = vinColor_Stage0;
D/skia    (21484):   16	        mediump vec4 texColor;
D/skia    (21484):   17	        {
D/skia    (21484):   18	            texColor = texture(uTextureSampler_0_Stage0, vTextureCoords_Stage0);
D/skia    (21484):   19	        }
D/skia    (21484):   20	        outputCoverage_Stage0 = texColor;
D/skia    (21484):   21	    }
D/skia    (21484):   22	    {
D/skia    (21484):   23	        sk_FragColor = outputColor_Stage0 * outputCoverage_Stage0;
D/skia    (21484):   24	    }
D/skia    (21484):   25	}
D/skia    (21484):   26	
D/skia    (21484): Errors:
D/skia    (21484): ERROR: The GPU does not support this version of OpenGL ES, try an older version
```

Facing error in stable flutter

**Comment by escamoteur** [comment] 2019-09-17 11:19
Could you please add more information about what you were doing when you received this error?

**Comment by MarcoMihaiCondrache** [comment] 2019-09-20 16:41
> Could you please add more information about what you were doing when you received this error?

I get that mistake too.
The error is logged when i run the app in debug on a physical device.
Below my device specs:

- CPU: ArmV7 (Cortex-A53 32bit)
- GPU: OpenGl ES 3.0 (No Vulkan)
- Android: 9.0
- Name: SM-J610FN
- Screen: 1480 * 720 (60Hz - 280dpi)

Flutter Doctor

```Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Linux, locale it_IT.UTF-8)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[!] Android Studio (version 3.5)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] Connected device (1 available)

! Doctor found issues in 1 category.
```

**Comment by escamoteur** [comment] 2019-09-21 09:48
Did this happen after you upgraded Flutter? Meaning did have this problem before?
Does it happen with a newly created project?

**Comment by MarcoMihaiCondrache** [comment] 2019-09-21 10:13
Yes, It has happen after flutter upgrade.
Every project that i make give me problems on the device that i talked you about before.

**Comment by escamoteur** [comment] 2019-09-21 10:54
Could you please give it a try switching to master?

**Comment by MarcoMihaiCondrache** [comment] 2019-09-21 14:03
@escamoteur
Ok i've switched to master channel and it works

**Comment by escamoteur** [comment] 2019-09-24 10:36
@waseemarain4u please also add your `flutter doctor`output and tell us on which platform this happens.
If the problem is solved, please close this issue.

**Comment by janmoppel** [comment] 2019-11-12 11:03
Hello @waseemarain4u !

Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the issue, if you have any more information for us; we will reopen it right away!

Thank you for your contribution.

P.S. If anyone still experience the same problem, please file a new issue with the information required in the template.
All system setups can be slightly different so it’s always better to open new issues and reference related issues.

**Closed by janmoppel** 2019-11-12 11:03 UTC
Labels: waiting for customer response
