### ISSUE TITLE
[tool_crash] HttpException

### ISSUE THREAD

**Issue by Vikaskumar75** [flutter/flutter#154742] opened 2024-09-06 19:03 UTC
## Command
```sh
flutter run --machine --start-paused -d chrome --devtools-server-address http://127.0.0.1:9100/ --target /Users/mr.rajput/Projects/federal_reserve_website/lib/main.dart
```

## Steps to Reproduce
1. Just run the web app and it crashes on it's own

## Logs
HttpException
```console
Connecting to VM Service at ws://127.0.0.1:64277/HQ_ydZoOZbs=/ws
Connected to the VM Service.
***** Supabase init completed Instance of 'Supabase'
***** SupabaseDeepLinkingMixin startAuthObserver
**** onAuthStateChange: AuthChangeEvent.initialSession
WebSocketException: Connection to 'http://localhost:64257/devtools/page/3A97DBC687DFABAECE3F413DE7470BC9#' was not upgraded to websocket
#0      _WebSocketImpl.connect (dart:_http/websocket_impl.dart:1011:41)
#1      WebSocket.connect (dart:_http/websocket.dart:320:22)
#2      WipConnection.connect (package:webkit_inspection_protocol/webkit_inspection_protocol.dart:231:22)
#3      ChromeTab.connect (package:webkit_inspection_protocol/webkit_inspection_protocol.dart:184:26)
#4      Chromium.close (package:flutter_tools/src/web/chrome.dart:519:55)
<asynchronous suspension>
#5      ChromiumDevice.stopApp (package:flutter_tools/src/web/web_device.dart:164:5)
<asynchronous suspension>
#6      ResidentWebRunner._cleanup (package:flutter_tools/src/isolated/resident_web_runner.dart:203:5)
<asynchronous suspension>
#7      ResidentWebRunner._cleanupAndExit (package:flutter_tools/src/isolated/resident_web_runner.dart:217:5)
<asynchronous suspension>
#8      Future._propagateToListeners.handleWhenCompleteCallback.<anonymous closure> (dart:async/future_impl.dart:854:56)
<asynchronous suspension>

Failed to establish connection with the application instance in Chrome.
This can happen if the websocket connection used by the web tooling is unable to correctly establish a connection, for example due to a firewall.

Oops; flutter has exited unexpectedly: "HttpException: Connection closed before full header was received, uri = http://localhost:64257/json".
A crash report has been written to /Users/mr.rajput/Projects/federal_reserve_website/flutter_01.log
```
```console
[✓] Flutter (Channel stable, 3.24.1, on macOS 14.6.1 23G93 darwin-arm64, locale en-IN)
    • Flutter version 3.24.1 on channel stable at /Users/mr.rajput/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5874a72aa4 (2 weeks ago), 2024-08-20 16:46:00 -0500
    • Engine revision c9b9d5780d
    • Dart version 3.5.1
    • DevTools version 2.37.2

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at /Users/mr.rajput/Library/Android/sdk
    • Platform android-35, build-tools 35.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)

[✓] VS Code (version 1.93.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.97.20240902

[✓] Connected device (4 available)
    • Vikas’s Iphone 15 (mobile)      • 00008120-000E39491450A01E • ios            • iOS 17.6.1 21G93
    • macOS (desktop)                 • macos                     • darwin-arm64   • macOS 14.6.1 23G93 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad     • darwin         • macOS 14.6.1 23G93 darwin-arm64
    • Chrome (web)                    • chrome                    • web-javascript • Google Chrome 127.0.6533.73

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 5874a72aa4c779a02553007c47dacbefba2374dc
### Plugins
app_links-6.3.2
app_links_linux-1.0.3
app_links_web-1.0.4
fluttertoast-8.2.8
gtk-2.1.0
path_provider-2.1.4
path_provider_android-2.2.10
path_provider_foundation-2.4.0
path_provider_linux-2.2.1
path_provider_windows-2.3.0
shared_preferences-2.3.2
shared_preferences_android-2.3.2
shared_preferences_foundation-2.5.2
shared_preferences_linux-2.4.1
shared_preferences_web-2.4.2
shared_preferences_windows-2.4.1
url_launcher-6.3.0
url_launcher_android-6.3.10
url_launcher_ios-6.3.1
url_launcher_linux-3.2.0
url_launcher_macos-3.2.0
url_launcher_web-2.3.3
url_launcher_windows-3.1.2

**Comment by darshankawar** [comment] 2024-09-09 06:55
Closing as duplicate of https://github.com/flutter/flutter/issues/154207

**Closed by darshankawar** 2024-09-09 06:55 UTC
Labels: in triage
