### ISSUE TITLE
problem occur after adding my firebase.

### ISSUE THREAD

**Issue by Saraalr** [flutter/flutter#60226] opened 2020-06-24 19:14 UTC
My project where work perfectly, but when I add the Firebase and start work on it the I could not open it agin on the simulator
the output which I resive
note: I m using tabBar in my project
Launching lib/main.dart on iPhone 11 Pro in debug mode...
Running Xcode build...
Xcode build done. 19.6s
Configuring the default Firebase app...
Connecting to the VM Service is taking longer than expected...
Still attempting to connect to the VM Service...
If you do NOT see the Flutter application running, it might have crashed. The device logs (e.g. from adb or XCode) might have more details.
If you do see the Flutter application running on the device, try re-running with --host-vmservice-port to use a specific port known to be available.
Exception attempting to connect to the VM Service: SocketException: OS Error: Connection refused, errno = 61, address = 127.0.0.1, port = 60093
This was attempt #50. Will retry in 0:00:01.600000.
Exception attempting to connect to the VM Service: SocketException: OS Error: Connection refused, errno = 61, address = 127.0.0.1, port = 60230
This was attempt #100. Will retry in 0:00:01.600000.

my flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 1.20.0-1.0.pre.157, on Mac OS X 10.15.5 19F101,
locale en-SA)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
[✓] Android Studio (version 3.6)
[✓] Connected device (1 available)

• No issues found!
MBPalkhasbSara:~ saraalrabiah$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 1.20.0-1.0.pre.157, on Mac OS X 10.15.5 19F101,
locale en-SA)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
[✓] Android Studio (version 3.6)
[✓] Connected device (1 available)

• No issues found!

**Comment by TahaTesser** [comment] 2020-06-25 12:56
Hi @Saraalr 
From what I can see, the issue is related to a FlutterFire plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments, possibly providing a minimal reproducible code sample that does not use flutter fire or other 3rd party plugins, and I will reopen it.
Thank you

**Closed by TahaTesser** 2020-06-25 12:56 UTC

**Comment by fradamlee** [comment] 2020-09-02 22:38
In my case, I got that error because I added the google file by second time
like this: GoogleService-Info (2).plist,
So my solution was delate all the google files from Downloads and from my .xcworkspace
And repeat the steps to link with Firebase
When you download one more time the google file you must always include like this: GoogleService-Info.plist
