### ISSUE TITLE
API documents are not getting generated 

### ISSUE THREAD

**Issue by dharanidharandharmasivam** [flutter/flutter#76367] opened 2021-02-19 07:50 UTC
We have published [our package](https://pub.dev/packages/syncfusion_flutter_charts) in the pub. After publishing the new version, the API documents are not generated and shown as failed to run `dartdoc `which I have shown below. 

![image](https://user-images.githubusercontent.com/19346074/108471945-1fe86080-72b2-11eb-94ab-40491d79467b.png)

But from the above, I couldn't find the exact cause/issue. I have tried to replicate this locally, but while generating API documents using `dartdoc `command, there were no errors in it and API documents are generated properly. I have ensured in latest stable and beta channels. In both, API documents are generating properly without any errors.

In the **stable** channel, dartdoc tool version is **0.32.4** and in the **beta** channel, dartdoc tool version is **0.39.0**. 

## Steps to Reproduce

1. Download the package
2. Run `dartdoc`

<details>
  <summary>Logs</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, 1.26.0-17.6.pre, on Microsoft Windows [Version 10.0.19042.804], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] VS Code (version 1.53.2)
[√] Connected device (2 available)

• No issues found!

C:\Users\TempKaruna>flutter doctor -v
[√] Flutter (Channel beta, 1.26.0-17.6.pre, on Microsoft Windows [Version 10.0.19042.804], locale en-US)
    • Flutter version 1.26.0-17.6.pre at C:\FlutterSDK\beta\flutter
    • Framework revision a29104a69b (3 days ago), 2021-02-16 09:26:56 -0800
    • Engine revision 21fa8bb99e
    • Dart version 2.12.0 (build 2.12.0-259.12.beta)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\TempKaruna\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.53.2)
    • VS Code at C:\Users\TempKaruna\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.19.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 88.0.4324.182
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 88.0.705.68

• No issues found!
```

</details>

**Comment by TahaTesser** [comment] 2021-02-19 11:06
Hi @dharanidharandharmasivam 
From what I can see, the issue is related to a 3rd party plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/dart-lang/dartdoc/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-02-19 11:06 UTC
Labels: in triage
