### ISSUE TITLE
Flutter Web: Regression - Widgets have random ghosting behavior  in master and dev branch -- Can be observed with Link widget but applies to others as well

### ISSUE THREAD

**Issue by khari998** [flutter/flutter#89497] opened 2021-09-05 10:53 UTC
Took me a while to figure out why my app was breaking and I wasn't getting any errors describing why. In the stable branch, Flutter is using version 6.0.3 of the Link widget from url_launcher, which seems to work fine. But when moving to dev and master that both use version 6.0.10 of the Link widget, weird things happen. Code example is provided below. I also tried changing the version of url_launcher back to 6.0.3 on master branch to downgrade it from 6.0.10 and it still did not work.

Expected behavior: Scrolling to work normally as it does in stable.

Actual behavior: After scrolling and reaching the footer and scrolling back up, the last image that was rendered makes a ghost rendering of itself that persists as you scroll back up, the route using the Link widget in the AppBar moves out of place or disappears altogether, and a ghost rendering of the AppBar is created. Scrolling is generally buggy. When removing the link widget, everything works normally. Functionality of the Link widget does not seem to be affected as clicking the button still navigates to the right link. It's just causing major rendering issues across the application for some reason. 

```
[✓] Flutter (Channel master, 2.6.0-1.0.pre.191, on macOS 11.5.2 20G95 darwin-arm, locale en-US)
    • Flutter version 2.6.0-1.0.pre.191 at /Users/khari/Documents/dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 81142c1f9a (6 hours ago), 2021-09-05 00:41:02 -0400
    • Engine revision dbc97a09b4
    • Dart version 2.15.0 (build 2.15.0-82.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/khari/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.5)
    • Xcode at /Applications/Xcode-beta.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.60.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (2 available)
    • iPhone 12 Pro Max (mobile) • 175F58A7-794B-44B9-85FE-D67E9879E190 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 92.0.4515.159
```

```dart
import 'package:flutter/material.dart';
import 'package:url_launcher/link.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: MyHomePage(),
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: RawScrollbar(
        thickness: 9,
        radius: const Radius.circular(15),
        child: CustomScrollView(
          slivers: [
            SliverAppBar(
              floating: true,
              automaticallyImplyLeading: false,
              expandedHeight: 252,
              backgroundColor: Colors.white,
              flexibleSpace: FlexibleSpaceBar(
                collapseMode: CollapseMode.pin,
                background: Column(
                  children: [
                    const SizedBox(height: 18),
                    Container(
                      padding: const EdgeInsets.symmetric(vertical: 18),
                      decoration: const BoxDecoration(
                        border: Border.symmetric(
                          horizontal: BorderSide(
                            color: Colors.red,
                            width: 2.0,
                          ),
                        ),
                      ),
                      width: 1080,
                      child: const Padding(
                        padding: EdgeInsets.symmetric(horizontal: 18.0),
                        child: _NavButtons(),
                      ),
                    ),
                  ],
                ),
              ),
            ),
            SliverToBoxAdapter(
              child: _PageBody(),
            ),
            const SliverToBoxAdapter(child: _Footer())
          ],
        ),
      ),
    );
  }
}

class _NavButtons extends StatelessWidget {
  const _NavButtons({
    Key? key,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Row(
      mainAxisAlignment: MainAxisAlignment.spaceEvenly,
      children: [
        Link(
            // Sometimes randomly disappears
            uri: Uri.parse("https://www.google.com"),
            builder: (context, func) =>
                TextButton(onPressed: func, child: Text("Route1"))),
        Text("Route2"),
        Text("Route3"),
        Text("Route4")
      ],
    );
  }
}

class _PageBody extends StatelessWidget {
  _PageBody({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        SizedBox(
          height: 600,
          width: 300,
          child: Image.network(
            "https://images.unsplash.com/photo-1526336024174-e58f5cdd8e13?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=3334&q=80",
          ),
        ),
        SizedBox(
          height: 600,
          width: 300,
          child: Image.network(
            "https://images.unsplash.com/photo-1526336024174-e58f5cdd8e13?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=3334&q=80",
          ),
        ),
        SizedBox(
          height: 600,
          width: 300,
          child: Image.network(
            "https://images.unsplash.com/photo-1526336024174-e58f5cdd8e13?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=3334&q=80",
          ),
        ),
      ],
    );
  }
}

class _Footer extends StatelessWidget {
  const _Footer({Key? key}) : super(key: key);
  @override
  Widget build(BuildContext context) {
    return Container(
      width: MediaQuery.of(context).size.width,
      color: Colors.blue,
      height: 250,
      child: Center(
        child: TestButton(),
      ),
    );
  }
}

class TestButton extends StatelessWidget {
  const TestButton({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    const _testUrl = "https://google.com";
    return Link(
      target: LinkTarget.blank,
      uri: Uri.parse(_testUrl),
      builder: (
        BuildContext context,
        Future<void> Function()? followLink,
      ) =>
          TextButton(
        style: TextButton.styleFrom(
            padding: const EdgeInsets.all(
              18,
            ),
            backgroundColor: Colors.black,
            shape:
                RoundedRectangleBorder(borderRadius: BorderRadius.circular(9))),
        onPressed: followLink,
        child: Text(
          "Breaks Here When Reached",
        ),
      ),
    );
  }
}
```

**Comment by khari998** [comment] 2021-09-05 18:13
So I removed the Link widget from my app, and while It did stop this exact error from occurring on the homepage of my app, this issue is still prevalent throughout my application.

Even thought this widget causes the issues with scrolling and ghosting, I am noticing ghost widgets (widgets stuck on the screen and not changing position while the rest of the application scrolls normally) in other parts of my application that I did not have before. Everything from widgets appearing on top of the SliverAppBar while scrolling to widgets from a previous page loaded over top of new pages that are being navigated to. There are times when I scroll where the application will act as if it has scrolled to the bottom but none of the widgets from the initial position have changed at all. The ghost widgets paint on top of everything so dropdowns are not visible when clicked on if a ghost widget is on top of it. However, even in this case, flutter still recognizes the clicks on my drop down menu as clicking it retains the correct functionality. 

There's no way right now that Flutter web for me is usable on the master branch. I've re-downloaded flutter 3 times and it happens every time when switching to the mater branch. I believe this framework issue is deeper than just this widget but for some reason the widget easily triggers this bug. The ghosting and unexpected behavior

**Comment by zambetpentru** [comment] 2021-09-06 06:40
Hi, I think this is the same as what I've come across a few days back and you can check and see if it happens at the same version. https://github.com/flutter/flutter/issues/88688 and hopefully will be fixed in the same work in https://github.com/flutter/flutter/issues/86809. Do you get the same errors in your Dev Tools as I had?

**Comment by khari998** [comment] 2021-09-06 09:35
> Hi, I think this is the same as what I've come across a few days back and you can check and see if it happens at the same version. #88688 and hopefully will be fixed in the same work in #86809. Do you get the same errors in your Dev Tools as I had?

Different errors but same behavior. @yjbanov mentioned issues with the link widget in #86809 but I'm getting this behavior throughout my application at random it seems. Widgets like Link just make it worse.

**Comment by TahaTesser** [comment] 2021-09-06 10:51
Hi @khari998 
It looks like a duplicate of https://github.com/flutter/flutter/issues/88688, reproducible test might be different but cause looks the same

**Closed by TahaTesser** 2021-09-06 10:51 UTC
Labels: in triage

**Comment by ditman** [comment] 2021-09-13 21:00
@khari998 I verified the latest changes to `master` fix the issues you describe on your app, please give it another shot with `flutter channel master`!

```
dit@dit:~/github/repro-cases/issue_89497$ flutter --version
Flutter 2.6.0-6.0.pre.76 • channel master • git@github.com:ditman/flutter.git
Framework • revision fad5e4cf89 (22 minutes ago) • 2021-09-13 13:37:07 -0700
Engine • revision abb1980f65
Tools • Dart 2.15.0 (build 2.15.0-96.0.dev)
```
