### ISSUE TITLE
Back swipe navigation on iOS should be mutually exclusive with taps

### ISSUE THREAD

**Issue by jklint-g** [flutter/flutter#23984] opened 2018-11-06 07:33 UTC
## Steps to Reproduce

On an iOS Flutter app, I can tap an outgoing screen at the same time that I am popping it by swiping back. This can happen pretty easily when navigating quickly with both thumbs, and it causes Flutter errors if the tapped widget on the outgoing screen happens to push a route. 

In contrast, native iOS list navigation disallows tapping once you start swiping back, and vice-versa. It does however permit scrolling vertically with a second finger after starting a tap, just not horizontally.

Here's a simple app with an infinite depth of routes to navigate, which is a good playground for the problem:
```dart
import 'package:flutter/material.dart';
import 'package:flutter/widgets.dart';

void main() {
  runApp(
    MaterialApp(
      home: Builder(builder:(context) => _buildScaffold(context, 0)),
    ),
  );
}

Scaffold _buildScaffold(BuildContext context, int depth) {
  return Scaffold(
          appBar: AppBar(
            title: Text('Screen $depth'),
          ),
          body: Center(child: 
            MaterialButton(child: Text('Next'), onPressed: (){
              Navigator.of(context).push(
                MaterialPageRoute(builder: (_) => _buildScaffold(context, depth + 1)));
            }),
          ),
        );
} 

```
You can induce errors by:
1. Press Next a couple times to push a couple routes.
2. With the left thumb, start a back swipe gesture but don't lift off the screen yet.
3. With the right thumb, start a tap gesture on a button on the outgoing screen. Both thumbs are still on the screen.
4. Continue the back gesture until it's >50% done, such that when you release it will cause the route to pop. Both thumbs still on the screen.
5. Quickly lift the left thumb followed by the right thumb. Or vice-versa. If you do it right, there will be a brief animation flicker, the log will populate with errors, and you won't be able to navigate forward or backward anymore by the Next button or the app bar back button.

Note that I was only testing this on iOS; there could be similar issues with the back button on Android.

## Logs

```
══╡ EXCEPTION CAUGHT BY ANIMATION LIBRARY ╞═════════════════════════════════════════════════════════
The following assertion was thrown while notifying status listeners for AnimationController:
Cannot reuse a MaterialPageRoute<dynamic> after disposing it.
'package:flutter/src/widgets/routes.dart': Failed assertion: line 218 pos 12:
'!_transitionCompleter.isCompleted'

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new

When the exception was thrown, this was the stack:
#2      TransitionRoute.didPopNext (package:flutter/src/widgets/routes.dart:218:12)
#3      NavigatorState.pop (package:flutter/src/widgets/navigator.dart:1792:23)
#4      _CupertinoBackGestureController._handleStatusChanged (package:flutter/src/cupertino/route.dart:610:17)
#5      _AnimationController&Animation&AnimationEagerListenerMixin&AnimationLocalListenersMixin&AnimationLocalStatusListenersMixin.notifyStatusListeners (package:flutter/src/animation/listener_helpers.dart:161:19)
#6      AnimationController._checkStatusChanged (package:flutter/src/animation/animation_controller.dart:678:7)
#7      AnimationController._tick (package:flutter/src/animation/animation_controller.dart:694:5)
#8      Ticker._tick (package:flutter/src/scheduler/ticker.dart:228:5)
#9      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
#10     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleBeginFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:906:11)
#11     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection/runtime/libcompact_hash.dart:370:8)
#12     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:904:17)
#13     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleBeginFrame (package:flutter/src/scheduler/binding.dart:834:5)
#14     _invoke1 (dart:ui/hooks.dart:153:13)
#15     _beginFrame (dart:ui/hooks.dart:123:3)
(elided 2 frames from class _AssertionError)

The AnimationController notifying status listeners was:
  AnimationController#e1d28(⏮ 0.000; paused; DISPOSED; for MaterialPageRoute<dynamic>(null))
════════════════════════════════════════════════════════════════════════════════════════════════════
Another exception was thrown: 'package:flutter/src/widgets/navigator.dart': Failed assertion: line 1531 pos 12: '!_debugLocked': is not true.
[VERBOSE-2:shell.cc(181)] Dart Error: Unhandled exception:
'package:flutter/src/widgets/navigator.dart': Failed assertion: line 1744 pos 12: 'route._navigator == this': is not true.
#0      _AssertionError._doThrowNew (dart:core/runtime/liberrors_patch.dart:40:39)
#1      _AssertionError._throwNew (dart:core/runtime/liberrors_patch.dart:36:5)
#2      NavigatorState.maybePop (package:flutter/src/widgets/navigator.dart:1744:12)
<asynchronous suspension>
#3      Navigator.maybePop (package:flutter/src/widgets/navigator.dart:1117:34)
#4      BackButton.build.<anonymous closure> (package:flutter/src/material/back_button.dart:91:19)
#5      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:507:14)
#6      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:562:30)
#7      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
#8      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:242:9)
#9      TapGestu
```

```

[✓] Flutter (Channel beta, v0.9.4, on Mac OS X 10.13.6 17G65, locale en-US)
    • Flutter version 0.9.4
    • Framework revision f37c235c32 (6 weeks ago), 2018-09-25 17:45:40 -0400
    • Engine revision 74625aed32
    • Dart version 2.1.0-dev.5.0.flutter-a2eb050044

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).
      If Android SDK has been installed to a custom location, set $ANDROID_HOME to that location.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✗] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[✓] IntelliJ IDEA Community Edition (version 2018.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 25.0.2
    • Dart plugin version 181.4203.498

```

**Comment by benjaminhorner** [comment] 2019-02-18 13:26
To build on @jklint-g 's issue, the exact same error also occurs when one has 2 pages. Page a is a list with list item that are tappable and push view B.

Swipe to pop view B, tap very quickly on a list item and the same error occurs. IMO during the animation (and during the swipe) all other user interactions should be cancelled.

**Comment by benjaminhorner** [comment] 2019-02-20 07:52
@zoechi this is reproductible in the **Google Ads** app on iOS. Push a new screen. Swipe back with one thumb and with the other tap the back button. Release the swipe: **all screens are popped** and one is left with an "empty" app.

I took a look at the **AliBaba** app and they seem to have found a way to prevent this. Same goes for the **Google** app on iOS (IF it was made with Flutter of course).

**Comment by TahaTesser** [comment] 2020-03-31 15:05
Issue still exist on 

flutter doctor -v
```
[✓] Flutter (Channel dev, v1.16.3, on Mac OS X 10.15.4 19E266, locale en-GB)
    • Flutter version 1.16.3 at /Users/taha/Code/flutter_dev
    • Framework revision be3a4b37b3 (5 days ago), 2020-03-26 18:08:05 -0700
    • Engine revision b2bdeb3f0f
    • Dart version 2.8.0 (build 2.8.0-dev.17.0 1402e8e1a4)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/taha/Code/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/taha/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4, Build version 11E146
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.43.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[✓] Connected device (6 available)
    • SM M305F      • 32003c30dc19668f                     • android-arm64  •
      Android 10 (API 29)
    • Taha’s iPhone • 00008020-001059882212002E            • ios            •
      iOS 13.4
    • iPhone 11     • 41EB2A85-7EB4-4FD2-8978-FBBE2A681D74 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-13-4 (simulator)
    • macOS         • macOS                                • darwin-x64     •
      Mac OS X 10.15.4 19E266
    • Chrome        • chrome                               • web-javascript •
      Google Chrome 80.0.3987.149
    • Web Server    • web-server                           • web-javascript •
      Flutter Tools

• No issues found!
```

**Comment by darshankawar** [comment] 2022-11-09 12:05
I am unable to replicate this behavior using latest versions and with sample code provided above. I followed the steps to replicate and assuming done right :), I didn't see the reported error in the console.
Also, it looked similar to https://github.com/flutter/flutter/issues/30416 which was not replicable too.

With these findings, I am going ahead and closing as not replicable and probably fixed in later versions since the issue was filed. If anybody disagrees or see a same issue using latest versions, please file a new issue.

**Closed by darshankawar** 2022-11-09 12:05 UTC
Labels: platform-ios, framework, f: cupertino, f: routes, a: quality, f: gestures, has reproducible steps, P4, found in release: 1.21
