### ISSUE TITLE
Move to Gradle 4.0

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#10833] opened 2017-06-19 18:11 UTC
Gradle 4.0 is now stable.  @lukef recommends we move our templates and plugins to use such.  @mit-mit @mravn-google

**Comment by mravn-google** [comment] 2017-06-19 19:48
Dupe of https://github.com/flutter/flutter/issues/10236

**Closed** 2017-06-20 20:35 UTC
Labels: dev: tool - gradle

**Comment by mravn-google** [comment] 2017-06-26 21:25
We decided to be consistent with Android Studio here. Current stable version of Android Studio is 2.3.3, and it uses Gradle 3.3 in its project templates. So that's what we do too.

Once Android Studio 3.0.0 is out, we'll use whatever version of Gradle it uses for new projects.
