### ISSUE TITLE
Samsung Handwriting issues

### ISSUE THREAD

**Issue by TypicalDarkness** [flutter/flutter#30656] opened 2019-04-08 01:58 UTC
## Steps to Reproduce

1. Use a samsung device with handwriting capabilities
2. Select a textfield in a Flutter App
3. Switch to handwriting mode
4. Write something
5. Leave keyboard mode and enter it again (or press space bar)
6. Write again
Issue: The already written text is no longer shown in the keyboard and any additional text is added in front of the old text.

It seems like the samsung keyboard isn't able to retrieve the text from the textfield.

It happens with any flutter app (I tested a few on [itsallwidgets.com](https://itsallwidgets.com/)), so providing logs/flutter doctor would probably be useless, I will instead provide a video demonstrating the issue
[https://www.youtube.com/watch?v=KUBDWRs2HaI](https://www.youtube.com/watch?v=KUBDWRs2HaI)

![2019_04_08_03_44_56_trim](https://user-images.githubusercontent.com/11584285/55694090-afccdc00-59b2-11e9-9faf-c10e6f9b925d.gif)

**Comment by g3rry99** [comment] 2019-04-16 22:52
Can confirm this

**Comment by GaryQian** [comment] 2019-10-04 19:52
@justinmc This does not seemed to be fixed by https://github.com/flutter/engine/pull/12780, was able to repro on Note 9 with the change

**Comment by justinmc** [comment] 2019-10-04 20:16
Darn.  Thanks for taking the time to try it.

**Comment by GaryQian** [comment] 2019-10-08 22:38
This may be caused by this root issue: https://github.com/flutter/flutter/issues/41990

**Comment by GaryQian** [comment] 2020-02-26 00:25
Update: The recent changes to `finishComposingText` did not resolve this. This bug should be a separate issue from the other Samsung issues.

**Comment by GaryQian** [comment] 2020-04-08 21:12
I tried this with the changes from https://github.com/flutter/engine/pull/17426

It seems to be resolved!

**Closed by GaryQian** 2020-04-08 21:12 UTC
Labels: a: text input, customer: crowd, engine, framework, platform-android
