### ISSUE TITLE
bug in dropdown sample.

### ISSUE THREAD

**Issue by CrazyBunnyz** [flutter/flutter#118255] opened 2023-01-10 16:51 UTC
i found a bug in your documentation. 

here is the link of your documentation : https://api.flutter.dev/flutter/material/DropdownMenu-class.html
![image](https://user-images.githubusercontent.com/52201618/211612808-426abd1b-f838-4bc5-a60b-1c31a43acef3.png)
I try to run your sample but it won't work. here is the error that can be found in the console 
Error compiling to JavaScript:
/tmp/dartpadBDOIQS/lib/main.dart:20:16: Error: 'DropdownMenuEntry' isn't a type.
    final List<DropdownMenuEntry<ColorLabel>> colorEntries =
               ^^^^^^^^^^^^^^^^^
/tmp/dartpadBDOIQS/lib/main.dart:21:10: Error: 'DropdownMenuEntry' isn't a type.
        <DropdownMenuEntry<ColorLabel>>[];
         ^^^^^^^^^^^^^^^^^
/tmp/dartpadBDOIQS/lib/main.dart:27:16: Error: 'DropdownMenuEntry' isn't a type.
    final List<DropdownMenuEntry<IconLabel>> iconEntries =
               ^^^^^^^^^^^^^^^^^
/tmp/dartpadBDOIQS/lib/main.dart:28:10: Error: 'DropdownMenuEntry' isn't a type.
        <DropdownMenuEntry<IconLabel>>[];
         ^^^^^^^^^^^^^^^^^
/tmp/dartpadBDOIQS/lib/main.dart:23:24: Error: The method 'DropdownMenuEntry' isn't defined for the class '_DropdownMenuExampleState'.
 - '_DropdownMenuExampleState' is from 'package:dartpad_sample/main.dart' ('/tmp/dartpadBDOIQS/lib/main.dart').
Try correcting the name to the name of an existing method, or defining a method named 'DropdownMenuEntry'.
      colorEntries.add(DropdownMenuEntry<ColorLabel>(
                       ^^^^^^^^^^^^^^^^^
/tmp/dartpadBDOIQS/lib/main.dart:31:16: Error: The method 'DropdownMenuEntry' isn't defined for the class '_DropdownMenuExampleState'.
 - '_DropdownMenuExampleState' is from 'package:dartpad_sample/main.dart' ('/tmp/dartpadBDOIQS/lib/main.dart').
Try correcting the name to the name of an existing method, or defining a method named 'DropdownMenuEntry'.
          .add(DropdownMenuEntry<IconLabel>(value: icon, label: icon.label));
               ^^^^^^^^^^^^^^^^^
/tmp/dartpadBDOIQS/lib/main.dart:45:19: Error: The method 'DropdownMenu' isn't defined for the class '_DropdownMenuExampleState'.
 - '_DropdownMenuExampleState' is from 'package:dartpad_sample/main.dart' ('/tmp/dartpadBDOIQS/lib/main.dart').
Try correcting the name to the name of an existing method, or defining a method named 'DropdownMenu'.
                  DropdownMenu<ColorLabel>(
                  ^^^^^^^^^^^^
/tmp/dartpadBDOIQS/lib/main.dart:57:19: Error: The method 'DropdownMenu' isn't defined for the class '_DropdownMenuExampleState'.
 - '_DropdownMenuExampleState' is from 'package:dartpad_sample/main.dart' ('/tmp/dartpadBDOIQS/lib/main.dart').
Try correcting the name to the name of an existing method, or defining a method named 'DropdownMenu'.
                  DropdownMenu<IconLabel>(
                  ^^^^^^^^^^^^

I also try to download the sample with flutter create --sample=material.DropdownMenu.1 mysample, but it still gives a failure.
i want really need this sample.
please help

**Comment by TahaTesser** [comment] 2023-01-10 18:00
duplicate of https://github.com/flutter/flutter/issues/118161

**Closed by TahaTesser** 2023-01-10 18:00 UTC
Labels: team: infra
