### ISSUE TITLE
Gallery, Pesto: FAB has square shadow while transitioning up

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#5203] opened 2016-08-03 21:33 UTC
Please see this movie, from my Nexus 5X: https://youtu.be/VC6spk7P6Xg

Notice how the FAB, while transitioning up, has a square shadow around it. It doesn't have the square the entire transition, but starting at second 3 of the transition.

**Comment by abarth** [comment] 2016-08-03 21:36
This is a bug in Skia.  We ask skia what the bounding box of the fab is and it reports a size that goes out some number of standard deviations into the shadow but not sufficiently far to avoid this artifact.

**Comment by sethladd** [comment] 2016-08-03 21:37
Thanks for the quick diagnosis. It's hard to notice at full speed, so probably not a high priority right now. If we know the Skia bug, we can link it here.

**Comment by abarth** [comment] 2016-08-03 21:49
I don't think I've filed it against skia yet.  We should probably make a reduced test case for them.

**Comment by joeblew99** [comment] 2016-08-05 18:52
@sethladd 
The video is an awesome way of documenting issues. 
How did you do the video screen capture ?

**Comment by eseidelGoogle** [comment] 2016-08-05 19:20
Personally I use:
```
adb screenrecord /data/demo.mp4
adb pull /data/demo.mp4
```
Then send it to YouTube and file bug. :)  https://github.com/flutter/flutter/issues/3496 is on file about making that easier (and iOS enabled).

**Comment by sethladd** [comment] 2016-08-08 17:45
What @eseidelGoogle said :)

**Comment by joeblew99** [comment] 2016-09-29 14:36
@eseidel nice thanks

**Comment by sethladd** [comment] 2017-01-27 21:27
This came up in a review from our material design team.

**Comment by eseidelGoogle** [comment] 2017-02-02 02:54
Considering for M2 since this showed up in UX review.

**Comment by sethladd** [comment] 2017-02-02 03:06
I'm not sure this is Pesto specific, so it might show an issue in our framework/engine. If so, M2 feels right.

**Comment by sethladd** [comment] 2017-03-08 21:52
hi @chinmaygarde ! Do we think this is addressed?  (just doing a little cleanup)

**Comment by eseidelGoogle** [comment] 2017-04-11 22:29
@chinmaygarde any update?  Is this the same as the other raster cache/shadow flash bug?

**Comment by chinmaygarde** [comment] 2017-04-11 22:37
This is a duplicate of the raster cache issue being tracked here in [Flutter](https://github.com/flutter/flutter/issues/5231) and here in [Skia](https://bugs.chromium.org/p/skia/issues/detail?id=5974#c9).

**Comment by eseidelGoogle** [comment] 2017-04-25 22:23
@chinmaygarde This is fixed now, right?

**Comment by eseidelGoogle** [comment] 2017-05-02 22:19
@chinmaygarde this is fixed, correct?

**Comment by chinmaygarde** [comment] 2017-05-05 14:22
As mentioned earlier, the underlying issue was the same as that in https://github.com/flutter/flutter/issues/5231. However, in recent versions of the gallery, the raster cache does not seem to be considering this FAB for caching (maybe because the picture layer boundary was introduced at a higher level). So yes, this is "fixed". But the correct fix is the one applied for https://github.com/flutter/flutter/issues/5231.

**Closed by chinmaygarde** 2017-05-05 14:22 UTC
Labels: customer: gallery, dependency: skia, from: review, prod: engine
