### ISSUE TITLE
[web]: JS interop does not work within a flutter_web project with build_web_compilers 2.x

### ISSUE THREAD

**Issue by aryzhov** [flutter/flutter#32524] opened 2019-05-10 23:09 UTC
I tried using the `firebase` package in my simple flutter_web app as follows:

```dart
import 'package:flutter_web/material.dart';
import 'package:firebase/firebase.dart';
import 'package:firebase/firestore.dart';

void main() {
  // The values were copied from Firebase console 
  initializeApp(
    apiKey: "...",
    authDomain: "...",
    databaseURL: "...",
    projectId: "...",
    storageBucket: "...",
    messagingSenderId: "...",
    name: "...",
  );
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(
        appBar: AppBar(
          title: Text("Hello"),
        ),
        body: Center(
          child: Text("Hello, Flutter"),
        ),
      ),
    );
  }
}
```

When I run the application, with the `initializeApp()` call, I get a blank page with an error in JS console:
```
Uncaught Error: type arguments should not be null: T => {
    class JsObjectWrapper extends core.Object {
      get jsObject() {
        return this[jsObject$];
      }
      set jsObject(value) {
        super.jsObject = value;
      }
    }
    (JsObjectWrapper.fromJsObject = function(jsObject) {
      this[jsObject$] = jsObject;
      ;
    }).prototype = JsObjectWrapper.prototype;
    dart.addTypeTests(JsObjectWrapper);
    JsObjectWrapper.prototype[_is_JsObjectWrapper_default] = true;
    const jsObject$ = Symbol("JsObjectWrapper.jsObject");
    dart.setFieldSignature(JsObjectWrapper, () => ({
      __proto__: dart.getFields(JsObjectWrapper.__proto__),
      jsObject: dart.finalFieldType(T)
    }));
    return JsObjectWrapper;
  }
    at Object.dart.throwInternalError (dart_sdk.js:3610)
    at Object.makeGenericType [as JsObjectWrapper$] (dart_sdk.js:3773)
    at top_level.dart:23
    at Object.execCb (require.js:1696)
    at Module.check (require.js:878)
    at Module.<anonymous> (require.js:1139)
    at require.js:134
    at require.js:1189
    at each (require.js:59)
    at Module.emit (require.js:1188)
    at Module.check (require.js:938)
    at Module.enable (require.js:1176)
    at Module.init (require.js:788)
    at callGetModule (require.js:1203)
    at Object.completeLoad (require.js:1590)
    at HTMLScriptElement.onScriptLoad (require.js:1717)
```
Removing `initializeApp()` makes it run ok, so the error must be the result of `initializeApp()`.
I was assuming `firebase` package should work because its dependencies are only `http` and `js`.

## flutter doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v1.5.8, on Mac OS X 10.13.6 17G6030, locale en-US)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[!] iOS toolchain - develop for iOS devices (Xcode 10.1)
    ✗ ios-deploy out of date (1.9.4 is required). To upgrade with Brew:
        brew upgrade ios-deploy
[✓] Android Studio (version 3.4)
[✓] VS Code (version 1.33.1)
[✓] Connected device (2 available)

! Doctor found issues in 1 category.
```

## pubspec.yaml
```
name: helloworld
description: An app built using Flutter for web

environment:
  # You must be using Flutter >=1.5.0 or Dart >=2.3.0
  sdk: '>=2.3.0-dev.0.1 <3.0.0'

dependencies:
  flutter_web: any
  flutter_web_ui: any
  firebase: any

dev_dependencies:
  build_runner: ^1.4.0
  build_web_compilers: ^2.0.0
  pedantic: ^1.0.0

dependency_overrides:
  flutter_web:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web
  flutter_web_ui:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_ui
```

**Comment by natebosch** [comment] 2019-05-10 23:26
This is most likely https://github.com/dart-lang/sdk/issues/36912

**Comment by kevmoo** [comment] 2019-05-10 23:31
Going to close this out as a duplicate of dart-lang/sdk#36912 – not related to Flutter web work

**Comment by kevmoo** [comment] 2019-05-10 23:34
Reopening so folks can find this one.

**Comment by bgetsug** [comment] 2019-05-11 05:41
@aryzhov, I reported the same thing in #32347. Downgrading `build_web_compilers` worked for me:
```yaml
dev_dependencies:
  build_runner: any
  build_web_compilers: '>=1.0.0 <2.0.0'
```

**Comment by aryzhov** [comment] 2019-05-11 17:02
@bgetsug I have verified that this is a valid workaround. I have managed to make `firebase` work with flutter_web, including authentication and firestore stream subscriptions.

**Comment by Akaike0** [comment] 2019-05-16 20:18
Have the same issue, it helps to downgrade the build_web_compiler ...

**Comment by vsmenon** [comment] 2019-05-28 14:08
FYI - underlying issue is https://github.com/dart-lang/sdk/issues/36944

Expecting to have a fix soon.  This is prioritized for the next Dart release.

**Comment by vsmenon** [comment] 2019-06-05 20:33
This should be fixed in Dart 2.3.2-dev.0.1.  That hasn't been rolled into Flutter yet.

**Comment by vsmenon** [comment] 2019-06-12 16:09
Flutter's dev channel has this now (as does Dart's).

fyi @kevmoo

**Comment by kevmoo** [comment] 2019-06-12 16:29
Calling this fixed! Folks should use the latest Flutter dev channel – and remove the downgrade of `build_web_compilers`

**Closed by kevmoo** 2019-06-12 16:29 UTC
Labels: dependency: dart, ☸ platform-web

**Comment by aryzhov** [comment] 2019-06-20 18:19
This works, I confirm. Thank you!

**Comment by gazialankus** [comment] 2019-07-09 10:34
@aryzhov were you able to use firebase auth without the popup at every refresh? Here's what I can do at the moment: 

```
// Copyright 2019 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
import 'package:firebase/firebase.dart' as fb;
import 'package:flutter_web_ui/ui.dart' as ui;
import 'package:fire_pump_webreport/main.dart' as app;

main() async {
  fb.initializeApp(
    apiKey: "...", //redacted
    authDomain: "...",
    databaseURL: "...",
    projectId: "...",
    storageBucket: "...",
    messagingSenderId: "...",
  );

  await ui.webOnlyInitializePlatform();

  final fb.Auth auth = fb.auth();

  if (auth.currentUser == null) {
    final fb.UserCredential userCredential = await auth.signInWithPopup(fb.GoogleAuthProvider());
    print("logged in");
    print(userCredential);
  } else {
    print("already logged in"); // THIS NEVER HAPPENS
  }

  app.main(auth.currentUser);
}
```

This is not ideal since it pops up the Google Sign In window with every refresh. Is this also your current solution, or do you have something better? 

Specifically: 

1. Can you make it remember the sign in info, rather than asking at every page refresh? 
2. Do you have a widget or something that prevents a popup altogether?

**Comment by slightfoot** [comment] 2019-07-09 15:18
@gazialankus auth.currentUser's initial value is not synchronous. You need to listen to the auth.onAuthStateChanged listener and you'll be notified that the user is already logged in.

https://firebase.google.com/docs/reference/js/firebase.auth.Auth#on-auth-state-changed

**Comment by gazialankus** [comment] 2019-07-09 20:04
@slightfoot thank you! simply adding `await auth.onAuthStateChanged.first;` here fixed it!

Interestingly I had an AngularDart app in the past that I was using `auth.currentUser` without any `onAuthStateChanged` and it was working fine. I'll remember to use `onAuthStateChanged` to be on the safe side. Thanks again!

**Comment by Parmendrakumar** [comment] 2019-08-11 09:34
I am Getting same white blank screen and I am on Developer build, What should I do

**Comment by Parmendrakumar** [comment] 2019-08-11 09:34
dependencies:
  flutter_web: any
  flutter_web_ui: any
  firebase: any

dev_dependencies:
  build_runner: any
  build_web_compilers: any
  pedantic: ^1.7.0

**Comment by vikramkapoor** [comment] 2019-08-18 10:35
I am getting a blank screen too on dev channel. 

name: safeho
description: An app built using Flutter for web

environment:
  # You must be using Flutter >=1.5.0 or Dart >=2.3.0
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  flutter_web: any
  flutter_web_ui: any
  provider: ^3.0.0+1
  firebase: ^5.0.3
  after_layout: any
  json_annotation: ^2.4.0
  charts_flutter:
    path: ./flutter
 # meta: ^1.1.1
 # intl: ^0.15.2

dev_dependencies:
  build_runner: ^1.6.2
  build_web_compilers: '>=1.0.0 <2.0.0'
  pedantic: ^1.7.0
  flutter_web_test: any
  json_serializable: ^3.0.0
  mockito: ^4.0.0
  
dependency_overrides:
  flutter_web:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web
  flutter_web_test:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_test    
  flutter_web_ui:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_ui
  provider:
    git:
      url: https://github.com/AppleEducate/provider
      path: packages/provider
      ref: web
  after_layout:
    git:
      url: https://github.com/AppleEducate/flutter_after_layout
      ref: web

**Comment by gazialankus** [comment] 2019-08-18 10:47
You should take a look at the error in the JS console, just like OP has done. Also, [disabling minification](https://github.com/flutter/flutter/issues/32347#issuecomment-491061798) may create more informative errors.
