### ISSUE TITLE
Have to clean project everytime before i run my app.

### ISSUE THREAD

**Issue by DevarshRanpara** [flutter/flutter#58156] opened 2020-05-28 09:56 UTC
I am on flutter stable channel with version 1.7.1.
If i try to run my project in Debug mode dart.exe eats all memory and my computer stopes responding. I have to force shut down it and start everything again.

If i clean my project everytime before i run, it works fine but its not the solution, as after i clean my project it takes roo much time to run again.

Computer specs : 
Processor : Intel code i7 7th Gen
RAM : 8 GB

Flutter doctor -v output
``` 

[√] Flutter (Channel stable, v1.17.1, on Microsoft Windows [Version 10.0.17134.165], locale en-IN)
    • Flutter version 1.17.1 at E:\Flutter\flutter
    • Framework revision f7a6a7906b (2 weeks ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\Devarsh Ranpara\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.45.1)
    • VS Code at C:\Users\Devarsh Ranpara\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.10.2

[√] Connected device (1 available)
    • Redmi 6 • 192.168.225.93:5555 • android-arm • Android 9 (API 28)

! Doctor found issues in 1 category.

```

**Comment by mraleph** [comment] 2020-05-28 10:55
Duplicate of #54420

**Closed by mraleph** 2020-05-28 10:55 UTC

**Comment by mraleph** [comment] 2020-05-28 10:57
@DevarshRanpara could you try the following in `E:\Flutter\flutter`

```
> git checkout -b patched-stable origin/stable
> git revert f149eec31bfeb5b165cdd507397c657c8c876b56
> del bin\cache\*.snapshot
> flutter doctor
```

After that try to work with your project and let us know if it ever hangs again.

**Comment by DevarshRanpara** [comment] 2020-05-28 12:27
> @DevarshRanpara could you try the following in `E:\Flutter\flutter`
> 
> ```
> > git checkout -b patched-stable origin/stable
> > git revert f149eec31bfeb5b165cdd507397c657c8c876b56
> > del bin\cache\*.snapshot
> > flutter doctor
> ```
> 
> After that try to work with your project and let us know if it ever hangs again.

It worked.
Thank you.

**Comment by BirjuVachhani** [comment] 2020-06-11 07:04
What about master branch...I am facing this too.

**Comment by mraleph** [comment] 2020-06-11 10:11
This has been fixed on the master branch. Make sure you update to the most recent master.
