### ISSUE TITLE
Flutter crash report

### ISSUE THREAD

**Issue by sumeetbhut** [flutter/flutter#48029] opened 2020-01-01 06:39 UTC
Value was missing for variable tag: macosIdentifier. (11:29)
PRODUCT_BUNDLE_IDENTIFIER = {{macosIdentifier}}

**Comment by stuartmorgan** [comment] 2020-01-01 17:42
Duplicate of #43734

Your tree has files from two different versions of Flutter.

**Closed by stuartmorgan** 2020-01-01 17:42 UTC
