### ISSUE TITLE
when i scroll in listview in flutter web it shows this error

### ISSUE THREAD

**Issue by anandsubbu007** [flutter/flutter#62847] opened 2020-08-04 08:57 UTC
Can anyone help me with this?

```
Error running hot-restart: hot restart already in progress
Restarted application in 8,928ms.
══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
The following assertion was thrown during a scheduler callback:
Assertion failed: org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/surface/clip.dart:294:12
_clipElement == null
is not true
When the exception was thrown, this was the stack:
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 213:49  throw_
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 24:3    assertFailed
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/surface/clip.dart 294:28                   [_applyShape]
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/surface/clip.dart 220:5                    apply
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/surface/surface.dart 364:5                 build
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/surface/surface.dart 662:11                build
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/surface/surface.dart 681:14                build
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/surface/surface.dart 966:19                [_updateManyToMany]
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/surface/surface.dart 718:7                 update
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/surface/clip.dart 100:11                   update
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/surface/surface.dart 878:15                [_updateManyToOne]
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/surface/surface.dart 714:7                 update
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/surface/offset.dart 46:11                  update
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/surface/surface.dart 853:15                [_updateManyToOne]
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/surface/surface.dart 714:7                 update
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/surface/offset.dart 46:11                  update
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/surface/surface.dart 950:17                [_updateManyToMany]
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/surface/surface.dart 718:7                 update
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/surface/offset.dart 46:11                  update
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/surface/surface.dart 950:17                [_updateManyToMany]
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/surface/surface.dart 718:7                 update
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/surface/clip.dart 317:11                   update
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/surface/surface.dart 950:17                [_updateManyToMany]
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/surface/surface.dart 718:7                 update
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/surface/clip.dart 317:11                   update
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/surface/surface.dart 853:15                [_updateManyToOne]
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/surface/surface.dart 714:7                 update
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/surface/offset.dart 46:11                  update
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/surface/surface.dart 853:15                [_updateManyToOne]
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/surface/surface.dart 714:7                 update
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/surface/offset.dart 46:11                  update
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/surface/surface.dart 950:17                [_updateManyToMany]
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/surface/surface.dart 718:7                 update
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/surface/transform.dart 42:11               update
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/surface/surface.dart 853:15                [_updateManyToOne]
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/surface/surface.dart 714:7                 update
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/surface/scene_builder.dart 545:25          <fn>
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/profiler.dart 36:18                        timeAction
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/surface/scene_builder.dart 541:12          build
packages/flutter/src/rendering/layer.dart 776:35                                                                           buildScene
packages/flutter/src/rendering/view.dart 243:36                                                                            compositeFrame
packages/flutter/src/rendering/binding.dart 408:18                                                                         drawFrame
packages/flutter/src/widgets/binding.dart 881:13                                                                           drawFrame
packages/flutter/src/rendering/binding.dart 286:5                                                                          [_handlePersistentFrameCallback]
packages/flutter/src/scheduler/binding.dart 1117:15                                                                        [_invokeFrameCallback]
packages/flutter/src/scheduler/binding.dart 1056:9                                                                         handleDrawFrame
packages/flutter/src/scheduler/binding.dart 972:5                                                                          [_handleDrawFrame]
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/window.dart 756:13                         _invoke
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/window.dart 356:5                          invokeOnDrawFrame
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine.dart 226:18                                <fn>
════════════════════════════════════════════════════════════════════════════════════════════════════

[38;5;248m════════ Exception caught by scheduler library ═════════════════════════════════[39;49m
[38;5;244mThe following assertion was thrown during a scheduler callback:[39;49m
Assertion failed: org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/surface/clip.dart:294:12
_clipElement == null
is not true

[38;5;244mWhen the exception was thrown, this was the stack[39;49m
[38;5;244mC:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 213:49  throw_[39;49m
[38;5;244mC:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 24:3    assertFailed[39;49m
[38;5;244mC:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/surface/clip.dart 294:28                   [_applyShape][39;49m
[38;5;244mC:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/surface/clip.dart 220:5                    apply[39;49m
[38;5;244mC:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/surface/surface.dart 364:5                 build[39;49m
[38;5;244m...[39;49m
[38;5;248m════════════════════════════════════════════════════════════════════════════════[39;49m
Another exception was thrown: PersistedOffset: is in an unexpected state.

[38;5;248m════════ Exception caught by scheduler library ═════════════════════════════════[39;49m
PersistedOffset: is in an unexpected state.
Expected one of: PersistedSurfaceState.active, PersistedSurfaceState.released
But was: PersistedSurfaceState.pendingRetention
[38;5;248m════════════════════════════════════════════════════════════════════════════════[39;49m
Another exception was thrown: PersistedOffset: is in an unexpected state.

[38;5;248m════════ Exception caught by scheduler library ═════════════════════════════════[39;49m
PersistedOffset: is in an unexpected state.
Expected one of: PersistedSurfaceState.active, PersistedSurfaceState.released
But was: PersistedSurfaceState.pendingRetention
[38;5;248m════════════════════════════════════════════════════════════════════════════════[39;49m
Another exception was thrown: PersistedOffset: is in an unexpected state.

```

**Comment by pedromassangocode** [comment] 2020-08-04 09:37
Hi @anandsubbu007 
Can you please provide your `flutter doctor -v` and a [minimal complete reproducible code](https://stackoverflow.com/help/minimal-reproducible-example) sample.
Thank you

**Comment by anandsubbu007** [comment] 2020-08-04 10:30
```
[√] Flutter (Channel dev, 1.21.0-1.0.pre, on Microsoft Windows [Version 10.0.18363.959], locale en-IN)
    • Flutter version 1.21.0-1.0.pre at C:\Program Files\Flutter
    • Framework revision f25bd9c55c (3 weeks ago), 2020-07-14 20:26:01 -0400
    • Engine revision 99c2b3a245
    • Dart version 2.9.0 (build 2.9.0-21.0.dev 20bf2fcf56)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\Anand\AppData\Local\Android\Sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = C:\Users\Anand\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.47.3)
    • VS Code at C:\Users\Anand\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.13.1

[√] Connected device (3 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 84.0.4147.105
    • Edge (web)       • edge       • web-javascript • Microsoft Edge 84.0.522.52

• No issues found!
```

**Comment by pedromassangocode** [comment] 2020-08-04 11:44
Hi @anandsubbu007 
Can you please provide a [minimal complete reproducible code](https://stackoverflow.com/help/minimal-reproducible-example) sample. I need some Flutter code that reproduces the issue.
Thank you

**Comment by anandsubbu007** [comment] 2020-08-04 12:16
```
          Expanded(
            child: ListView.builder(
              shrinkWrap: true,
              itemBuilder: (context, idx) {
                return InkWell(
                  onTap: () {
                    setState(() {
                      selectedid = customerlist[idx].id;
                      widget.ontap(selectedid);
                    });
                  },
                  child: CustomerListview(
                      width: widget.width,
                      customer: customerlist[idx],
                      isselected: selectedid == customerlist[idx].id),
                );
              },
              itemCount: customerlist.length,
            ),
```

is this code enough? 
this part of code raise error.
when scrolling down it is working fine. when i try to scroll up it raise this error

**Comment by pedromassangocode** [comment] 2020-08-04 12:51
Hi @anandsubbu007 
I need a [minimal complete reproducible code](https://stackoverflow.com/help/minimal-reproducible-example) sample. I need a code to just copy/paste and run it. Please create a new project with just the code that reproduces the issue. The code you provided looks like contains some personal code and I'm unable to run it.

You can follow the link above to see how to create such minimal reproducible code.
Thank you

**Comment by anandsubbu007** [comment] 2020-08-05 06:17
```
import 'package:flutter/material.dart';

class Sample extends StatefulWidget {
  static const routeName = '/sample';
  Sample({Key key}) : super(key: key);

  @override
  _SampleState createState() => _SampleState();
}

class _SampleState extends State<Sample> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      drawer: Drawer(),
      body: Container(width: 600, child: ListoftextS()),
    );
  }
}

class ListoftextS extends StatefulWidget {
  const ListoftextS({Key key}) : super(key: key);

  @override
  _ListoftextSState createState() => _ListoftextSState();
}

class _ListoftextSState extends State<ListoftextS> {
  List listoftext;
  @override
  Widget build(BuildContext context) {
    listoftext = List<int>.generate(20, (i) => i + 1);
    return Container(
      color: Colors.black12,
      padding: EdgeInsets.all(5),
      child: Column(
        children: [
          SizedBox(height: 10),
          SizedBox(height: 5),
          Expanded(
            child: ListView.builder(
              shrinkWrap: true,
              itemBuilder: (context, idx) {
                return Card(
                    elevation: 5,
                    margin: EdgeInsets.all(1.5),
                    shape: BeveledRectangleBorder(),
                    child: Container(
                        child: Text('${listoftext[idx]}'),
                        width: 100,
                        height: 70));
              },
              itemCount: listoftext.length,
            ),
          ),
        ],
      ),
    );
  }
}

```

when i scroll up & down again & again it raise error.
In Flutter Web

![image](https://user-images.githubusercontent.com/55450843/89378414-580ec400-d711-11ea-8fde-4f7ff8f513ce.png)

![image](https://user-images.githubusercontent.com/55450843/89378408-55ac6a00-d711-11ea-92b0-39cd94bc845e.png)
**

**Comment by anandsubbu007** [comment] 2020-08-05 06:19
Is this details ok?

**Comment by pedromassangocode** [comment] 2020-08-05 06:44
Hi @anandsubbu007 
I see there's an open issue addressing the case you described (https://github.com/flutter/flutter/issues/60461).
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by pedromassangocode** 2020-08-05 06:44 UTC
Labels: in triage, waiting for customer response
