### ISSUE TITLE
HttpException: Connection closed before full header was received

### ISSUE THREAD

**Issue by ibrahimGit2019** [flutter/flutter#39122] opened 2019-08-23 16:06 UTC
i am getting this error when i use  ```FireDataBase.reference().child('path').set({"firstName": "Ibrahim"});```

```
Launching lib\main.dart on Android SDK built for x86 in debug mode...
Built build\app\outputs\apk\debug\app-debug.apk.
Error connecting to the service protocol: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:50708/PA9iiKV16q4=/ws
Exited (sigterm)
```

**Comment by mannprerak2** [comment] 2019-08-24 07:46
This happens when the library closes the connection after a certain time limit. (Connection Time Out)
It's probably due to no internet connection or an extremely slow connection.

**Comment by BondarenkoStas** [comment] 2019-08-30 14:57
@ibrahimGit2019 Please report do you still encounter the issue?

**Comment by iapicca** [comment] 2019-11-14 15:58
Hi @ibrahimGit2019 
for what I can see the issue is related to a FlutterFire plugin,
please open the issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
thank you

**Closed by iapicca** 2019-11-14 15:58 UTC
Labels: waiting for customer response
