### ISSUE TITLE
`pod setup --verbose` does nothing

### ISSUE THREAD

**Issue by CedricGrothues** [flutter/flutter#41501] opened 2019-09-27 19:16 UTC
## Steps to Reproduce

1. Install Cocoapods  using `sudo gem install cocoa pods`
2. Set up cocoa pods by running `pod setup` or `pod setup --verbose`
3. Watch how nothing happens

## Logs

`pod setup --verbose`
```
MacBook-Pro:cityapp user$ pod setup --verbose
MacBook-Pro:cityapp user$
```

```
MacBook-Pro:cityapp cedricgrothues$ flutter doctor -v
[✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Mac OS X 10.14.6 18G103, locale en-DE)
    • Flutter version 1.9.1+hotfix.2 at /Users/user/development/flutter
    • Framework revision 2d2a1ffec9 (3 weeks ago), 2019-09-06 18:39:49 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/user/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.0, Build version 11A420a
    ✗ CocoaPods installed but not initialized.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart
        side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To initialize CocoaPods, run:
        pod setup
      once to finalize CocoaPods' installation.

[!] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.38.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.4.1

[✓] Connected device (1 available)
    • iPhone 11 Pro Max • ... • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-0 (simulator)

! Doctor found issues in 2 categories.
```

**Comment by jmagman** [comment] 2019-09-27 19:29
Duplicate of https://github.com/flutter/flutter/issues/41253.
Workaround: https://github.com/flutter/flutter/issues/41253#issuecomment-536039050

**Closed by jmagman** 2019-09-27 19:29 UTC
