### ISSUE TITLE
Add support for command line arguments when running on desktop platforms

### ISSUE THREAD

**Issue by gspencergoog** [flutter/flutter#51425] opened 2020-02-25 18:42 UTC
Right now, the only argument that can be passed to an app is the initial route, and even then, only on mobile.

On desktop apps, it is common to be able to pass command line arguments to the executable when launching to configure the app.

We need a way to pass arbitrary arguments via `flutter run`, and we need to hook up passing the argv array to the Dart main.  Right now, if I make an app that prints the args on startup, even if I run the release version without using the `flutter` command, and with args, they don't get passed:
```dart
void main(List<String> args) {
  print ('Args: $args');
  runApp(MyApp());
}
```
Produces:
```
% build/macos/Build/Products/Release/manual_tests.app/Contents/MacOS/manual_tests --foo
flutter: Args: []
```
whereas I would have expected:
```
% build/macos/Build/Products/Release/manual_tests.app/Contents/MacOS/manual_tests --foo
flutter: Args: ['--foo']
```

**Comment by jonahwilliams** [comment] 2020-02-25 19:44
Related: https://github.com/flutter/flutter/issues/46005

**Comment by stuartmorgan** [comment] 2020-02-25 20:12
Duplicate of #32986

**Closed by stuartmorgan** 2020-02-25 20:12 UTC
Labels: a: desktop, tool

**Comment by gspencergoog** [comment] 2020-02-25 20:31
There it is!  I searched all over for that bug.  I'm surprised I didn't find it.
