### ISSUE TITLE
Textfield autocompletes from previous textfield on IOS

### ISSUE THREAD

**Issue by mihai-idava** [flutter/flutter#86338] opened 2021-07-13 08:21 UTC
Hello,

If first textfield keyboard type is email and the second is number after typing an email address in the first when you tap on the second it autocomplets with what you typed in the first one and you can't delete until changing focus. It behaves like this only on IOS.

<img src="https://user-images.githubusercontent.com/73276162/125417060-64ae2171-68f5-454b-8359-b6d6eed83c2f.gif" width="400"/>

```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Home(),
    );
  }
}

class Home extends StatefulWidget {
  const Home({Key? key}) : super(key: key);

  @override
  _HomeState createState() => _HomeState();
}

class _HomeState extends State<Home> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: Column(
        children: [
          TextField(
            keyboardType: TextInputType.emailAddress,
          ),
          TextField(
            keyboardType: TextInputType.number,
          )
        ],
      ),
    );
  }
}

```

**Comment by maheshmnj** [comment] 2021-07-13 09:08
Hi @mihai-idava,
Thanks for filing the issue. Could you please share the output of ```flutter doctor -v```. This helps to better address the issue.
Thank you

**Comment by mihai-idava** [comment] 2021-07-13 09:17
Sure, here is the output:

```
mihai@Mihais-MacBook-Air ~ % flutter doctor -v
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-arm, locale
    en-RO)
    • Flutter version 2.2.3 at /Users/mihai/development/flutter
    • Framework revision f4abaa0735 (12 days ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/mihai/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio
    • Android Studio at /Applications/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.24.0

[✓] Connected device (3 available)
    • SM J530F (mobile) • 192.168.0.113:5555 • android-arm    • Android 9 (API
      28)
    • macOS (desktop)   • macos              • darwin-arm64   • macOS 11.4 20F71
      darwin-arm
    • Chrome (web)      • chrome             • web-javascript • Google Chrome
      91.0.4472.114
    ! Error: iPhone is not connected. Xcode will continue when iPhone is
      connected. (code -13)

! Doctor found issues in 2 categories.
mihai@Mihais-MacBook-Air ~ % 

```

**Comment by maheshmnj** [comment] 2021-07-13 10:08
Thanks for the info, I am unable to reproduce the issue ran your exact sample code on the stable channel.
Steps 
1. entered the email address
2. tapped on the number field.

<details>
<summary>Output</summary>

https://user-images.githubusercontent.com/31410839/125433735-895e3f15-ffa1-464f-9267-f0e37bc86883.mov


</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-arm, locale en-GB)
    • Flutter version 2.2.3 at /Users/mahesh/Documents/flutter
    • Framework revision f4abaa0735 (12 days ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 57.0.5
    • Dart plugin version 211.7233

[✓] VS Code (version 1.58.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.24.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 11.4 20F71 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 91.0.4472.114

• No issues found!
```
</details>

Let me know if I missed any step.

Thank you.

**Comment by mihai-idava** [comment] 2021-07-13 11:01
can you please also try on a real device, on the simulator it doesn't seem to reproduce, i am using an iphone xr (ios 14.6) and it is reproducible every single time.

thanks

**Comment by maheshmnj** [comment] 2021-07-13 12:39
Could you please try switching to master channel by running  ```flutter channel master``` and then run ```flutter doctor -v``` and then verify if the issue is reproducible. You can switch back to stable channel again by running ```flutter channel stable```

**Comment by mihai-idava** [comment] 2021-07-13 14:18
I confirm that in the master channel it doesn't reproduce. The problem could be because of the phone or the ios version, i also tested on an iphone 6 (12.4.9) and the issue didn't reproduced.

**Comment by maheshmnj** [comment] 2021-07-14 06:18
Hi @mihai-idava, 
Thanks for the confirmation, As you are not able to reproduce on the master channel, So the fix will land on stable in the upcoming stable release, So you may use the master channel for now until this is available on stable. You may read more about the flutter channels here https://github.com/flutter/flutter/wiki/Flutter-build-release-channels

So I am going to close this issue as fixed. Feel free to revert back if you disagree.

Thank you.

**Closed by maheshmnj** 2021-07-14 06:18 UTC
Labels: in triage

**Comment by mihai-idava** [comment] 2021-07-14 06:51
ok, thank you for your support.
