### ISSUE TITLE
SelectionArea doesn't work when inwarping RichText

### ISSUE THREAD

**Issue by gkdgo** [flutter/flutter#123667] opened 2023-03-29 05:29 UTC
## Steps to Reproduce

1. run main on macos
2. try to select the text shown
**Expected results:** 
select the text
**Actual results:** 
cannot select
<details>
<summary>Code sample</summary>

```dart

import 'package:flutter/material.dart';

Future<void> main() async {
  return runApp(const MyApp());
}

class MyApp extends StatefulWidget {
  const MyApp({super.key});

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  Widget build(context) {
    return const MaterialApp(
      home: PageHome(),
    );
  }
}

class PageHome extends StatefulWidget {
  const PageHome({Key? key}) : super(key: key);

  @override
  State<PageHome> createState() => _PageHomeState();
}

class _PageHomeState extends State<PageHome> {
  final GlobalKey<NavigatorState> homeNavigatorKey = GlobalKey();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Home'),
      ),
      body: SelectionArea(
        child: RichText(
          selectionColor: Colors.green,
          text: const TextSpan(
            style: TextStyle(
              color: Colors.black,
              fontSize: 16,
            ),
            children: [
              TextSpan(
                text: 'Hello World',
              ),
            ],
          ),
        ),
      ),
    );
  }
}

```

</details>
<img width="276" alt="image" src="https://user-images.githubusercontent.com/55651847/228435338-7a7ab1f6-f455-423b-a96c-665b93bfd6ed.png">

**Comment by exaby73** [comment] 2023-03-29 07:46
Duplicate of https://github.com/flutter/flutter/issues/113530. See the solution there

**Closed by exaby73** 2023-03-29 07:46 UTC
Labels: in triage
