### ISSUE TITLE
[webview_flutter] Listen URL path change in webview_flutter 

### ISSUE THREAD

**Issue by baonv-acbs-com-vn** [flutter/flutter#109978] opened 2022-08-22 04:56 UTC
## Use case

Listen URL path change https://domain.com/path_A to https://domain.com/path_B

## Proposal

```
NSString *const FLTWKWebViewURLObserverKeyPath = @"URL"; 

- (instancetype)initWithWebView:(WKWebView *)webView channel:(FlutterMethodChannel *)channel {
  self = [super init];
  if (self) {
    [webView addObserver:self
              forKeyPath:FLTWKWebViewURLObserverKeyPath
                 options:NSKeyValueObservingOptionNew
                 context:nil];
  }
  return self;
}

- (void)stopObservingURLPath:(WKWebView *)webView {
  [webView removeObserver:self forKeyPath:FLTWKWebViewURLObserverKeyPath];
}

- (void)observeValueForKeyPath:(NSString *)keyPath
                      ofObject:(id)object
                        change:(NSDictionary<NSKeyValueChangeKey, id> *)change
                       context:(void *)context {
if ([keyPath isEqualToString:FLTWKWebViewURLObserverKeyPath] ){
      NSURL *newValueNSURL = change[NSKeyValueChangeNewKey];
      NSString *urlPath = newValueNSURL.path;
      const char *_urlPath = [urlPath UTF8String];
      [_methodChannel invokeMethod:@"onUrlChange" arguments:@{@"urlChange" : @(_urlPath)}];
  }
}
```

**Comment by baonv-acbs-com-vn** [comment] 2022-08-22 06:09
Android using:
`     @Override
       public void doUpdateVisitedHistory(WebView view, String url, boolean isReload) {
          FlutterWebViewClient.this.doUpdateVisitedHistory(view, url, isReload);
       }
`

**Comment by EmreSURK** [comment] 2022-08-22 07:18
There are two callbacks named onPageFinished and navigationDelegate. Why don't you use one of them?

**Comment by baonv-acbs-com-vn** [comment] 2022-08-22 07:56
> 
I need an example from you. i have tried and run only 1 first time. same domain when web change router webview_flutter can't listen for changes. URL path change https://domain.com/path_A to https://domain.com/path_B => path_A to path_B

**Comment by stuartmorgan** [comment] 2022-08-22 12:57
Duplicate of https://github.com/flutter/flutter/issues/27729

**Closed by stuartmorgan** 2022-08-22 12:57 UTC

**Comment by baonv-acbs-com-vn** [comment] 2022-08-23 01:56
> 

i don't see onUrlChanged on webview_flutter: ^3.0.4.
