### ISSUE TITLE
Getting error 'W/IInputConnectionWrapper( 5317)' when placing cursor at TextField

### ISSUE THREAD

**Issue by Hasanmehdi1** [flutter/flutter#75766] opened 2021-02-10 07:45 UTC
@FlutterIssues @TheMeullenator @anjelabauer

W/IInputConnectionWrapper( 5317): getTextAfterCursor on inactive InputConnection
W/IInputConnectionWrapper( 5317): getSelectedText on inactive InputConnection
W/IInputConnectionWrapper( 5317): endBatchEdit on inactive InputConnection
W/IInputConnectionWrapper( 5317): setComposingRegion on inactive InputConnection

**No values returned from text field whatever I insert there. Below is the code snippet.**
```dart
Container(
                padding: EdgeInsets.all(20.0),
                child: TextField(
                  autofocus: true,
                  style: TextStyle(color: Colors.black),
                  decoration: kTextFieldInputDecoration,
                  onChanged: (value) {
                    cityName = value;
                  }
                ),
              ),
```

**Comment by pedromassangocode** [comment] 2021-02-10 08:25
Hi @Hasanmehdi1 
As far as I know those are just logs printed while you focus/unfocus a text field.

Is it causing any critical issue in you Flutter app?
Thank you

**Comment by HansMuller** [comment] 2021-02-10 22:12
This appears to be a duplicate of https://github.com/flutter/flutter/issues/9471

**Comment by pedromassangocode** [comment] 2021-02-11 10:47
Yes it is, closing as duplicate of https://github.com/flutter/flutter/issues/75766. For anyone interested in this issue pleas follow up on https://github.com/flutter/flutter/issues/75766.
Thank you

**Closed by pedromassangocode** 2021-02-11 10:47 UTC
Labels: in triage, waiting for customer response

**Comment by Hasanmehdi1** [comment] 2021-02-11 16:08
> Hi @Hasanmehdi1
> As far as I know those are just logs printed while you focus/unfocus a text field.
> 
> Is it causing any critical issue in you Flutter app?
> Thank you

Yes, it is causing issue in my flutter app. Whatever value I'm inserting in TextField, it's not getting shown on console as well as not performing any action for that value when I'm submitting it by clicking on button.

**Comment by pedromassangocode** [comment] 2021-02-12 11:59
> Whatever value I'm inserting in TextField, it's not getting shown on console as well as not performing any action for that value when I'm submitting it by clicking on button.

This seems to be a different issue. Please feel free to open a new issue and mention me so I can take a look.
Thank you
