### ISSUE TITLE
Regression: setting TextFormField value from the onChanged method does not work

### ISSUE THREAD

**Issue by yosikal** [flutter/flutter#65714] opened 2020-09-13 07:24 UTC
## Steps to Reproduce

Setting TextFormField value from the onChanged method does not work unless running the update itself from a Timer with 1 second delay. 

I've implemented credit card expiry field. Part of the functionality is that when the user types numbers, the code adds/removes slash so the field will be in the standard of "MM/YY". The code worked in older Flutter version  but now it's not working. The following is a code that demonstrates the problem by simply trying to set a number higher by one from the number the user entered:

```
import 'package:flutter/material.dart';

void main() {
  runApp(TestField());
}

class TestField extends StatefulWidget {
  TestField({Key key}) : super(key: key);

  @override
  _TestFieldState createState() => _TestFieldState();
}

class _TestFieldState extends State {
  TextEditingController _textEditingController;

  @override
  void initState() {
    _textEditingController = TextEditingController();
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: Text('Welcome to Flutter'),
        ),
        body: Center(
          child: TextFormField(
            onChanged: (String txt) {
              int d = int.parse(txt);
              d++;

              /* does not work */
              _setValue(d.toString());

              /* does work
          Timer(Duration(seconds: 1), () {
            _setValue(d.toString());
          }); */
            },
            controller: _textEditingController,
            keyboardType: TextInputType.number,
          ),
        ),
      ),
    );
  }

  _setValue(String val) {
    setState(() {
      _textEditingController.value = TextEditingValue(
        text: val,
        selection: TextSelection.fromPosition(
          TextPosition(offset: val.length),
        ),
      );
    });
  }
}

```

<details>
  <summary>Logs</summary>

```
[√] Flutter (Channel stable, 1.20.3, on Microsoft Windows [Version 6.1.7601], locale he-IL)
    • Flutter version 1.20.3 at C:\tools\flutter
    • Framework revision 216dee60c0 (12 days ago), 2020-09-01 12:24:47 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at C:\Users\yosikal\AppData\Local\Android\sdk1
    • Platform android-30, build-tools 29.0.0
    • ANDROID_HOME = C:\Users\yosikal\AppData\Local\Android\sdk1
    • ANDROID_SDK_ROOT = C:\Users\yosikal\AppData\Local\Android\sdk1
    • Java binary at: C:\Program Files\Android\Android Studio1\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[!] Android Studio (version 2.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    X Unable to determine bundled Java version.
    • Try updating or re-installing Android Studio.

[!] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio1
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.49.0)
    • VS Code at C:\Users\yosikal\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.14.1

[√] VS Code, 64-bit edition (version 1.16.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.14.1

[!] Connected device
    ! No devices available

! Doctor found issues in 4 categories.
```

</details>

**Comment by iapicca** [comment] 2020-09-13 10:16
@yosikal try this [code](https://dartpad.dartlang.org/fbf49bb5cc73f7900d8c2c7b81f14b87), it seems to work as intended

**Comment by yosikal** [comment] 2020-09-13 10:19
Thanks, your code example does work at intended. However, that's what this bug is opened about, we need to wrap the call to _textEditingController.value in Timer or Future otherwise it doesn't work.

**Comment by iapicca** [comment] 2020-09-13 10:21
@yosikal sorry I edited the code this [code](https://dartpad.dartlang.org/fbf49bb5cc73f7900d8c2c7b81f14b87) should work

**Comment by yosikal** [comment] 2020-09-14 05:43
Tried it, doesn't work. Which Flutter version are you using?

**Comment by markusaksli-nc** [comment] 2020-09-14 09:36
Hi @yosikal 

I think DartPad is behind master. The code provided by @iapicca works on both latest master `1.22.0-10.0.pre.161` and latest stable `1.20.3`. Could you please provide your `flutter doctor -v`?

<details>
 <summary>flutter doctor -v</summary>

```
[√] Flutter (Channel master, 1.22.0-10.0.pre.161, on Microsoft Windows [Version 10.0.19041.508], locale en-US)
    • Flutter version 1.22.0-10.0.pre.161 at C:\Development\flutter_master
    • Framework revision cba91c97d0 (7 hours ago), 2020-09-13 18:57:03 -0400
    • Engine revision 2fc054147e
    • Dart version 2.10.0 (build 2.10.0-121.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Users\marku\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.6.5)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.6.30320.27
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.0)
    • Android Studio at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (6 available)
    • SM G950F (mobile)           • ce12171c51cc001c03 • android-arm64  • Android 9 (API 28)
    • sdk gphone x86 arm (mobile) • emulator-5554      • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)           • windows            • windows-x64    • Microsoft Windows [Version 10.0.19041.508]
    • Web Server (web)            • web-server         • web-javascript • Flutter Tools
    • Chrome (web)                • chrome             • web-javascript • Google Chrome 85.0.4183.102
    • Edge (web)                  • edge               • web-javascript • Microsoft Edge 85.0.564.44

• No issues found!
```
</details>

As a side note, you don't need to `setState` and deal with the resulting boilerplate, code complexity, and performance considerations. For formatting input please see [inputFormatters](https://api.flutter.dev/flutter/material/TextField/inputFormatters.html).

The documentation for [onChanged](https://api.flutter.dev/flutter/material/TextField/onChanged.html) may need to be improved here (see https://github.com/flutter/flutter/issues/64535 as well). Even though `inputFormatters` is mentioned, there still seems to be confusion regarding this.

**Comment by yosikal** [comment] 2020-09-14 10:09
Hi, It's in the logs section in the issue, pasting it again:

[√] Flutter (Channel stable, 1.20.3, on Microsoft Windows [Version 6.1.7601], locale he-IL)
    • Flutter version 1.20.3 at C:\tools\flutter
    • Framework revision 216dee60c0 (12 days ago), 2020-09-01 12:24:47 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at C:\Users\yosikal\AppData\Local\Android\sdk1
    • Platform android-30, build-tools 29.0.0
    • ANDROID_HOME = C:\Users\yosikal\AppData\Local\Android\sdk1
    • ANDROID_SDK_ROOT = C:\Users\yosikal\AppData\Local\Android\sdk1
    • Java binary at: C:\Program Files\Android\Android Studio1\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[!] Android Studio (version 2.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    X Unable to determine bundled Java version.
    • Try updating or re-installing Android Studio.

[!] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio1
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.49.0)
    • VS Code at C:\Users\yosikal\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.14.1

[√] VS Code, 64-bit edition (version 1.16.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.14.1

[!] Connected device
    ! No devices available

! Doctor found issues in 4 categories.

**Comment by iapicca** [comment] 2020-09-14 14:01
@yosikal 
just to be clear, my sample contains `setState` to mirror the original
I totally agree with @markusaksli-nc 
> As a side note, you don't need to `setState`

Regardless the use of `inputFormatters`, `setState` or good practice
the assertion `setting TextFormField value from the onChanged method does not work` is just **not true**;
my best guess is that in your code you are trying to `int d = int.parse(txt);` something that isn't an **int**

The problem is almost certainly with your implementation and not with flutter,
I recommend you to close this issue and if you need assistance for your code ask a question on stackoverflow.com

**Comment by markusaksli-nc** [comment] 2020-09-15 11:28
I'll close this issue for now as code assistance. If this topic crops up again I'll make sure the documentation improvement is suggested.

**Closed by markusaksli-nc** 2020-09-15 11:28 UTC
Labels: in triage

**Comment by yosikal** [comment] 2020-09-15 11:33
Hi Markus, just to confirm that there is no misunderstanding here:  I opened this issue with a reproducible code that doesn't involve setState. This still doesn't work for me on Flutter 1.20.3.

**Comment by markusaksli-nc** [comment] 2020-09-15 11:43
Well yes, the issue is that you **need** to set state for your code to work. This is the case any time you want to change the state of a widget (modifying the properties). I don't see this code without setState in your original post or history. My point was that inputFormatters is better suited for formatting input.
