### ISSUE TITLE
When VideoPlayer and TextButton are placed on the Stack, buttons do not work when Transform or FittedBox is used

### ISSUE THREAD

**Issue by sgbai78** [flutter/flutter#126993] opened 2023-05-17 07:14 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

When VideoPlayer and TextButton are placed on the Stack, buttons do not work when Transform or FittedBox is used.

At first, I tried to apply FittedBox's BoxFit, but I found a problem that buttons on the web did not work.

I applied Transform.scale to find another solution, but the same problem occurred.

If I remove the Transform widget or change Transform.scale to 1, the problem does not occur.
The same problem occurs when the Transform widget is changed to FittedBox.

### Expected results

A button event is fired at the button's position.

### Actual results

Button events are firing in the wrong place on the screen.
When you move the mouse, you can see that the button hover effect occurs in a completely different place.

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:video_player/video_player.dart';

void main() {
  runApp(const MainApp());
}

class MainApp extends StatefulWidget {
  const MainApp({super.key});

  @override
  State<MainApp> createState() => _MainAppState();
}

class _MainAppState extends State<MainApp> {
  late VideoPlayerController _controller;

  @override
  void initState() {
    _controller = VideoPlayerController.network(
      'https://flutter.github.io/assets-for-api-docs/assets/videos/bee.mp4',
    )..initialize().then((_) {
        setState(() {});
      });

    super.initState();
  }

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Stack(
          fit: StackFit.expand,
          children: [
            ClipRect(
              child: Transform.scale(
                scale: 1.5,
                child: Container(
                  width: double.infinity,
                  height: double.infinity,
                  color: Colors.red,
                  child: TestVideoPlayer(controller: _controller),
                ),
              ),
            ),
            DecoratedBox(
              decoration: const BoxDecoration(color: Color.fromRGBO(0, 0, 0, 0.5)),
              child: Column(
                children: [
                  SizedBox(
                    width: 48,
                    height: 48,
                    child: TextButton(
                      onPressed: () {
                        print("touch");
                        if (_controller.value.isPlaying) {
                          _controller.pause();
                        } else {
                          _controller.play();
                        }
                      },
                      child: const Icon(
                        Icons.settings,
                        color: Colors.white,
                      ),
                    ),
                  ),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }
}

class TestVideoPlayer extends StatelessWidget {
  const TestVideoPlayer({
    super.key,
    required VideoPlayerController controller,
  }) : _controller = controller;

  final VideoPlayerController _controller;

  @override
  Widget build(BuildContext context) {
    return Stack(
      children: [
        AspectRatio(
          aspectRatio: _controller.value.aspectRatio,
          child: VideoPlayer(_controller),
        ),
      ],
    );
  }
}


```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

https://github.com/flutter/flutter/assets/75677950/a2672a0e-05ee-46e6-ac5e-cfadf843c539

</details>

### Logs

<details><summary>Logs</summary>

```console
Launching lib\main.dart on Edge in debug mode...
This app is linked to the debug service: ws://127.0.0.1:51980/u60XV3c1OD0=/ws
Debug service listening on ws://127.0.0.1:51980/u60XV3c1OD0=/ws
Connecting to VM Service at ws://127.0.0.1:51980/u60XV3c1OD0=/ws
touch
touch
touch
touch
touch
touch
Application finished.

Exited.

```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[√] Flutter (Channel master, 3.11.0-6.0.pre.86, on Microsoft Windows [Version 10.0.22621.1555], locale ko-KR)
    • Flutter version 3.11.0-6.0.pre.86 on channel master at D:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ea5eddb5a9 (27 hours ago), 2023-05-15 21:39:26 -0700
    • Engine revision c4d4b40c65
    • Dart version 3.1.0 (build 3.1.0-113.0.dev)
    • DevTools version 2.23.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at D:\Android\sdk
    • Platform android-33-ext5, build-tools 33.0.2
    • ANDROID_HOME = D:\Android\sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.2.3)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.2.32526.322
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2022.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)

[√] VS Code (version 1.78.2)
    • VS Code at C:\Users\sgbai\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.64.0

[√] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 12 (API 31) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.22621.1555]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 113.0.5672.93
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 112.0.1722.64

[√] Network resources
    • All expected network resources are available.

```

</details>

**Comment by huycozy** [comment] 2023-05-17 10:56
Hi @sgbai78 
This issue looks similar to a recent issue at https://github.com/flutter/flutter/issues/126754. After checking this on Flutter 3.7.12, I see it can work as expected.

So I will close this issue as a duplicate of https://github.com/flutter/flutter/issues/126754, please follow up on that issue for further updates. Thanks!

**Closed by huycozy** 2023-05-17 10:56 UTC
Labels: in triage
