### ISSUE TITLE
JS Promise working with debug compiler, but not using production compiler

### ISSUE THREAD

**Issue by trott13** [flutter/flutter#43157] opened 2019-10-21 07:07 UTC
I'm accessing the navigator.usb API through "dart:html" and "package:js/js.dart".

Having a Promise declared:
```dart
@JS()
@anonymous
class Promise {
    external void then(Function onFulfilled, Function onRejected);
}
```
and using it like this:
```dart
@JS('navigator.usb.requestDevice')
external Promise usb_requestDevice(USBDeviceFilters filters);
```

and this:
```dart
usb_requestDevice(dfilter).then((USBDevice selectedDevice) { //onFulfilled
          print("usb_requestDevice/selected:");
          // some code opening it
      }, (error) {  // onRejected
          print("usb_requestDevice: $error");
          errorNFC(context, error);
      });
```

This works pretty well, in VSCode debugging mode. However,
switching to production mode (using "flutter build web") it seems none of 
the promise callbacks are called anymore (I don't see any of the prints).

I'm really down on this....

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.10.15-pre.186, on Mac OS X 10.14.6 18G95, locale de-DE)

**Comment by natebosch** [comment] 2019-10-23 20:21
The root cause here is that you need to call [`allowInterop`](https://api.dartlang.org/stable/2.5.1/dart-js/allowInterop.html) from `package:js` around the callback you are passing to `.then`.

DDC is currently less strict than dart2js about using `allowInterop` in all cases. We'd like to close this gap. That work is being tracked in https://github.com/dart-lang/sdk/issues/39074

The normal failure for this would have something like "<minfied ID> is not a function". I'm not sure why that isn't happening here and why it's silent.

Wrapping both functions passed here with `allowInterop` will solve the immediate issue.

**Closed by natebosch** 2019-10-23 20:21 UTC
Labels: dependency: dart, ☸ platform-web
