### ISSUE TITLE
Setting systemNavigationBarColor in SystemUiOverlayStyle undos setting of Status Bar Text/Icon Color

### ISSUE THREAD

**Issue by adifyr** [flutter/flutter#111839] opened 2022-09-18 16:17 UTC
## Steps to Reproduce

I would like to set the Status Bar to a white background with black overlay text. It works when I set the `statusBarIconBrightness: Brightness.dark`. However, once I set the `systemNavigationBarColor: <your color here>`. The text color goes back to the default white again. No matter what I do after that, the Status Bar text color stays white as long as I'm changing something with the System Navigation Bar as well. 

1. Execute `flutter run` on the code sample 
2. First, run the code without the line `systemNavigationBarColor: <your color here>`. You will see that the Status Bar has a white background with black text. Everything is running fine for the moment.
3. Now run the code again while including the `systemNavigationBarColor: <your color here>` line. You will see that the Status Bar Text Color changes back to the default white. The background of the Status Bar is as set, but the text changes back to white.

**Expected results:** 
I wanted to see the Status Bar Text Brightness remain what I set it as.

**Actual results:** 
When you include the `systemNavigationBarColor: <your color here>` line, the Status Bar Text Color changes back to the default white color (light brightness). And no matter what you do to change it to black, as long as the `systemNavigationBarColor` setting is there in `SystemUiOverlayStyle`, the Status Bar Text Color does NOT change.

<details>
<summary>Code sample</summary>

```dart
void main(List<String> args) async {
  WidgetsFlutterBinding.ensureInitialized();
  SystemChrome.setSystemUIOverlayStyle(const SystemUiOverlayStyle(
    statusBarColor: Colors.transparent,
    statusBarBrightness: Brightness.dark,
    statusBarIconBrightness: Brightness.dark,
    systemNavigationBarColor: Colors.transparent,
  ));
  runApp(const ProviderScope(child: MyProjectApp()));
}
```

</details>

<details>
  <summary>Logs</summary>

```
Analyzing myproject...                                                
No issues found! (ran in 2.3s)
```

```
[✓] Flutter (Channel stable, 3.3.1, on macOS 12.6 21G115 darwin-arm, locale en-US)
    • Flutter version 3.3.1 on channel stable at /Users/adityam/Documents/Dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4f9d92fbbd (12 days ago), 2022-09-06 17:54:53 -0700
    • Engine revision 3efdf03e73
    • Dart version 2.18.0
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc2)
    • Android SDK at /Users/adityam/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A309
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /Applications/Brave Browser.app/Contents/MacOS/Brave Browser

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.71.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (3 available)
    • POCO M2 Pro (mobile) • fd46886c • android-arm64  • Android 11 (API 30)
    • macOS (desktop)      • macos    • darwin-arm64   • macOS 12.6 21G115 darwin-arm
    • Chrome (web)         • chrome   • web-javascript • Brave Browser 105.1.43.93

[✓] HTTP Host Availability
    • All required HTTP hosts are available
```

</details>

**Comment by exaby73** [comment] 2022-09-19 15:56
Hello @adifyr. I cannot reproduce what you're describing. See the code and what I output I am observing below. Could you explain exactly what you are experiencing?

<details>
<summary>Code Sample</summary>

```dart
SystemChrome.setSystemUIOverlayStyle(const SystemUiOverlayStyle(
  statusBarColor: Colors.transparent,
  statusBarBrightness: Brightness.dark,
  statusBarIconBrightness: Brightness.dark,
  systemNavigationBarColor: Colors.red,
));
```

</details>

<details>
<summary>Screenshot</summary>

<img width="300" src="https://user-images.githubusercontent.com/50555895/191060652-38d9b81b-d08c-4c49-bc2a-4228023f5e12.png">

</details>

**Comment by adifyr** [comment] 2022-09-20 12:52
Hi. This is the output I am receiving below. My device is POCO M2 Pro with MIUI 12.5.6:

1. WITH `systemNavigationBarColor: <color>`
```dart
SystemChrome.setSystemUIOverlayStyle(const SystemUiOverlayStyle(
  statusBarColor: Colors.transparent,
  statusBarBrightness: Brightness.dark,
  statusBarIconBrightness: Brightness.dark,
  systemNavigationBarColor: Colors.red,
));
```
![WhatsApp Image 2022-09-20 at 6 16 16 PM](https://user-images.githubusercontent.com/86793553/191261517-21e3d8bf-585b-4d90-b177-05e576a6cbba.jpeg)

2. WITHOUT `systemNavigationBarColor: <color>`
```dart
SystemChrome.setSystemUIOverlayStyle(const SystemUiOverlayStyle(
  statusBarColor: Colors.transparent,
  statusBarBrightness: Brightness.dark,
  statusBarIconBrightness: Brightness.dark,
));
```
![WhatsApp Image 2022-09-20 at 6 15 30 PM](https://user-images.githubusercontent.com/86793553/191261570-e1be71c7-2a7f-4ad8-a6f0-1a733d07d0bc.jpeg)

**Comment by exaby73** [comment] 2022-09-21 09:25
I cannot reproduce this on a simulator running Android 13. Can you confirm if this is specific to your device or the Android version you are running on?

**Comment by adifyr** [comment] 2022-09-23 18:24
It may be specific to my device.

**Comment by exaby73** [comment] 2022-09-27 12:14
@adifyr I am marking this as a duplicate of https://github.com/flutter/flutter/issues/100027. If you disagree, please comment and I can reopen the issue. Thank you.

**Closed** 2022-09-27 12:14 UTC
Labels: r: duplicate
