### ISSUE TITLE
[camera][iOS]: LateInitializationError: Field '_controller@<number>' has not been initialized.

### ISSUE THREAD

**Issue by thecherrie** [flutter/flutter#95876] opened 2021-12-27 20:22 UTC
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. Wait until page initialises.

**Expected results:** 
Should display a full page with the camera preview.

**Actual results:** 
Receive error of: `LateInitializationError: Field '_camera' has not been initialized.`

https://stackoverflow.com/questions/67888648/how-do-i-solve-the-lateinitializationerror-in-flutter
https://stackoverflow.com/questions/70499891/flutter-camera-plugin-cameracontroller-not-initialising

<details>
<summary>Code sample</summary>

```dart
  late List<CameraDescription> cameras;
  late CameraController _controller;


  Future<void> setupCameras() async {
    try {
      cameras = await availableCameras();
      _controller =
      new CameraController(cameras[0], ResolutionPreset.medium);
      await _controller.initialize();
    }catch(e){
      throw e;
    }
  }

  @override
  Widget build(BuildContext context) {
    return FutureBuilder(
        future: setupCameras(),
        builder: (BuildContext context, AsyncSnapshot snapshot) {
          return AspectRatio(
              aspectRatio: _controller.value.aspectRatio,
              child: CameraPreview(_controller)
          );
        }
    );
  }
```

</details>

<details>
  <summary>Logs</summary>

```
The following LateError was thrown building FutureBuilder<void>(dirty, state: _FutureBuilderState<void>#b5aae):
LateInitializationError: Field '_controller@31048062' has not been initialized.
```

```
No errors pertaining to this issue. (flutter analyze)
```

```
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.5.2 20G95 darwin-x64, <omitted>)
    • Flutter version 2.2.3 at <omitted>
    • Framework revision f4abaa0735 (6 months ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at <omitted>
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] Connected device (2 available)
    • iPhone 12 (mobile) • <omitted> • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 96.0.4664.110

• No issues found!
```

</details>

![image](https://user-images.githubusercontent.com/14931384/147504725-456dc86a-717a-4e77-96df-44767d5e5214.png)

**Comment by nt4f04uNd** [comment] 2021-12-27 23:42
At the moment `_controller` is accessed in the builder, it is not initialized, hence the error. Closing, since this is not an issue with the camera package.

**Closed by nt4f04uNd** 2021-12-27 23:42 UTC

**Comment by thecherrie** [comment] 2021-12-28 12:51
Sorry I don't understand what you mean, in my `setupCameras()` function I'm initialising the `_controller`. If it is not being initialised here, how do I initialise it?

**Comment by nt4f04uNd** [comment] 2021-12-28 14:04
You are initializing it asynchrounously, so when the builder is called, the controller is not initialized yet. I would suggest reading [FutureBuilder docs](https://api.flutter.dev/flutter/widgets/FutureBuilder-class.html) and following the answers on the SO questions you linked in your post.

**Comment by thecherrie** [comment] 2021-12-28 15:18
> You are initializing it asynchronously, so when the builder is called, the controller is not initialized yet. I would suggest reading [FutureBuilder docs](https://api.flutter.dev/flutter/widgets/FutureBuilder-class.html) and following the answers on the StackOverflow questions you linked in your post.

I've read numerous articles on the internet telling me to do exactly as you're telling me not to do. Literally just walked through [this one](https://medium.com/geekculture/build-a-camera-app-flutter-in-app-camera-825b829fe138) and it's displaying the exact same error message. 

I've literally copied and pasted the code on the Flutter docs: https://docs.flutter.dev/cookbook/plugins/picture-using-camera and it's displaying the exact same error. 

Could you please provide some code?

`LateInitializationError: Field '_initialiseControllerFuture@25048062' has not been initialized.`

My `main.dart`:

```
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  // Obtain a list of the available cameras on the device.
  final cameras = await availableCameras();
  runApp(App(cameras: cameras));
}

class App extends StatelessWidget {

  final List<CameraDescription> cameras;
  const App({Key? key, required this.cameras}) : super(key: key);
```

My stateful page widget:

```
late CameraController _controller;
  late Future<void> _initializeControllerFuture;

  @override
  void initState() {
    super.initState();
    // To display the current output from the Camera,
    // create a CameraController.
    _controller = CameraController(
      // Get a specific camera from the list of available cameras.
      widget.cameras[0],
      // Define the resolution to use.
      ResolutionPreset.medium,
    );

    // Next, initialize the controller. This returns a Future.
    _initializeControllerFuture = _controller.initialize();
  }

  @override
  void dispose() {
    // Dispose of the controller when the widget is disposed.
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Take a picture')),
      // You must wait until the controller is initialized before displaying the
      // camera preview. Use a FutureBuilder to display a loading spinner until the
      // controller has finished initializing.
      body: FutureBuilder<void>(
        future: _initializeControllerFuture,
        builder: (context, snapshot) {
          if (snapshot.connectionState == ConnectionState.done) {
            // If the Future is complete, display the preview.
            return CameraPreview(_controller);
          } else {
            // Otherwise, display a loading indicator.
            return const Center(child: CircularProgressIndicator());
          }
        },
      ),
    );
  }
```

**Comment by nt4f04uNd** [comment] 2021-12-28 16:12
I copied the code from https://docs.flutter.dev/cookbook/plugins/picture-using-camera#complete-example and wasn't able to reproduce the error.

**Comment by thecherrie** [comment] 2021-12-28 17:24
The issue has something to do with it running on iOS, I've now tried it on my Android simulator and it runs.
