### ISSUE TITLE
Google sign in requestion redirect_uri, How to define it

### ISSUE THREAD

**Issue by zafferh** [flutter/flutter#135773] opened 2023-09-29 21:22 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. When clicking on the google sign in app I am met with an error saying "missing required parameter: redirect_uri". 
2. Where is this redirect uri supposed to be passed in the code below ?

### Actual results

met with 400: missing redirect uri

### Logs

```

Future<UserCredential> signInWithGoogle() async {
  // Trigger the authentication flow

  final GoogleSignInAccount? googleUser = await GoogleSignIn().signIn();

  // Obtain the auth details from the request
  final GoogleSignInAuthentication? googleAuth =
      await googleUser?.authentication;

  // Create a new credential
  final credential = GoogleAuthProvider.credential(
    accessToken: googleAuth?.accessToken,
    idToken: googleAuth?.idToken,
  );

  // Once signed in, return the UserCredentials
  return await FirebaseAuth.instance.signInWithCredential(credential);
}
```

### Flutter Doctor output

<details>
<summary>Doctor output</summary>

```console

[✓] Flutter (Channel stable, 3.13.6, on macOS 13.3.1 22E772610a darwin-arm64, locale en-US)
    • Flutter version 3.13.6 on channel stable at /Users/zafferhussein/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ead455963c (5 days ago), 2023-09-26 18:28:17 -0700
    • Engine revision a794cf2681
    • Dart version 3.1.3
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/zafferhussein/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.77.3)
    • VS Code at /Users/zafferhussein/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.64.0

[✓] Connected device (3 available)
    • iPhone 14 Pro Max (mobile) • A121F4C3-6397-42B7-80FD-DF8D8A4E5E36 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 13.3.1 22E772610a darwin-arm64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 117.0.5938.132

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

</details>

**Comment by opxdelwin** [comment] 2023-09-30 14:34
Hi @zafferh ,
For us to help you better please attach your `flutter doctor -v` output in your question.

Please do ensure the following as well:
 - App has been added in Firebase, preferably using `FlutterFire CLI`
 - SHA keys has been added in FirebaseAuth console (Project settings -> Apps -> Add Fingerprint)
 - Correct scopes has been added, see plugin usage policy [here](https://pub.dev/packages/google_sign_in#use-the-plugin)
 - 0Auth consent screen has been filled in Google Cloud Platform, see [here](https://console.cloud.google.com/apis/credentials/consent)

**Comment by zafferh** [comment] 2023-10-01 18:32
hey ran through that list and everything is setup properly. Still running into same problem. Added the doctor output to my original post. Thanks

**Comment by opxdelwin** [comment] 2023-10-01 21:00
could you confirm if the issue is only happening on the emulator or on a real device as well?

**Comment by darshankawar** [comment] 2023-10-02 07:49
@zafferh 
Have you already added and set the redirect uri to the project through google developer console ? Also, check if your project / setup supports Google's OAuth 2.0 policy.
It most probably looks like a setup / config issue in your project for which you can raise the question in support channels like StackOverflow.
Closing from here, as this doesn't look a like a bug in plugin. If you disagree, write in comments and I'll reopen it.

**Closed by darshankawar** 2023-10-02 07:49 UTC
Labels: in triage
