### ISSUE TITLE
"FAB per tab" missing frames when animating FAB

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#3383] opened 2016-04-18 21:10 UTC
Open the gallery app, open Demos, and select "floating action buttons". Swipe between tabs, and watch the FAB animate in.

Tested on a Nexus 5, running Android 6.0

![screenshot_20160418-140713](https://cloud.githubusercontent.com/assets/5479/14619974/29580694-056f-11e6-951c-b0a73414acd4.png)

**Comment by abarth** [comment] 2016-04-21 03:29
I've seen this anecdotally as well.  /me will investigate.

**Comment by abarth** [comment] 2016-04-21 03:37
Also, the ink response in the FAB is janky.

**Comment by abarth** [comment] 2016-04-21 03:40
Note: This screenshot is from slow mode, but I think I've see it in production mode as well.

**Comment by sethladd** [comment] 2016-04-21 04:52
Yeah, sorry about leaving Slow Mode on by accident :(

**Comment by chinmaygarde** [comment] 2016-04-21 06:07
Checked mode should not affect rasterizer time. Besides, I observed the same on precompiled mode on iOS. Took a capture in the OpenGLES frame debugger. A large chunk was being rendered offscreen with most of the being spent in two fragment shaders.

**Comment by abarth** [comment] 2016-04-25 16:41
Something pathological is going on in the rasterization phase:

![tabs-fab](https://cloud.githubusercontent.com/assets/112007/14791246/e3a7fdf6-0ac9-11e6-8412-81432267e8f1.png)

**Comment by abarth** [comment] 2016-04-25 22:38
The problem is that Skia is creating new blur kernels on every frame because we're scaling with a matrix that's novel each time due to floating point precision.  The blur kernels are n^2 to create.

**Comment by abarth** [comment] 2016-04-25 22:54
Filed https://bugs.chromium.org/p/skia/issues/detail?id=5224 for the Skia issue.

**Comment by sethladd** [comment] 2016-04-25 22:57
Thanks for tracking it down!

**Comment by eseidelGoogle** [comment] 2016-05-24 15:27
Should we close this @abarth?

**Comment by abarth** [comment] 2016-05-24 16:04
Yep.  The Skia folks fixenated it.

**Closed by abarth** 2016-05-24 16:04 UTC
Labels: affects: animation, affects: material design, dependency: skia, ⚠ astounding performance

**Comment by sethladd** [comment] 2016-05-24 16:07
Thanks for the help!
