### ISSUE TITLE
text_painter_test.dart test is failing on engine commit 973cfbc6cb030526269acc8dc03d524abb199e94

### ISSUE THREAD

**Issue by gw280** [flutter/flutter#49331] opened 2020-01-23 04:39 UTC
After https://github.com/flutter/engine/commit/973cfbc6cb030526269acc8dc03d524abb199e94, the build_and_test_linux_unopt_debug CI run is failing:

```
01:41 +4359 ~10 -1: /tmp/master_framework/flutter/packages/flutter/test/painting/text_painter_test.dart: TextPainter line metrics [E]

  Expected: <true>
    Actual: <false>
  package:test_api                                   expect
  package:flutter_test/src/widget_tester.dart 348:3  expect
  painting/text_painter_test.dart 762:5              main.<fn>
```

**Comment by GaryQian** [comment] 2020-01-24 01:16
Dupe of https://github.com/flutter/flutter/issues/43763 and https://github.com/flutter/flutter/pull/49364 disables the test.

**Closed by GaryQian** 2020-01-24 01:16 UTC
Labels: engine, team
