### ISSUE TITLE
"Element.inflateWidget","abs_path":"package:flutter/src/widgets/framework.dart","value":"NoSuchMethodError: The getter 'key' was called on null

### ISSUE THREAD

**Issue by LaxmikanthMadhyastha** [flutter/flutter#42594] opened 2019-10-12 19:36 UTC
I'm having this strange issue which pop-ups only one some devices and hence im not able to debug the problem
So I decided to use sentry for error reporting and still im not able to figure out the issue
I tried looking at the stack trace but there is no mention of any UI page that I have designed

Flutter doctor -v
```
[✓] Flutter (Channel stable, v1.9.1+hotfix.4, on Linux, locale en_GB.UTF-8)
    • Flutter version 1.9.1+hotfix.4 at /home/sugar/flutter
    • Framework revision cc949a8e8b (2 weeks ago), 2019-09-27 15:04:59 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at /home/sugar/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0
    • ANDROID_HOME = /home/sugar/Android/Sdk
    • Java binary at: /home/sugar/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)
    • All Android licenses accepted.

[✓] Android Studio (version 3.4)
    • Android Studio at /home/sugar/android-studio
    • Flutter plugin version 37.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)

[✓] Connected device (1 available)
    • Redmi 5 • 47b96007d250 • android-arm64 • Android 8.1.0 (API 27)

• No issues found!
```
Below is the stack trace i got from sentry

`
{"event_id":"ae86bbded77c442eb2fecc3879e79025","project":1777761,"release":null,"dist":null,"platform":"other","message":"","datetime":"2019-10-12T18:43:03.000000Z","time_spent":null,"tags":[["level","error"],["logger","SentryClient"]],"_meta":{"platform":{"":{"val":"dart"}}},"culprit":"framework.dart in Element.inflateWidget","exception":{"values":[{"stacktrace":{"frames":[{"function":"_drawFrame","abs_path":"dart:ui/hooks.dart","in_app":false,"lineno":207,"filename":"hooks.dart"},{"function":"_invoke","abs_path":"dart:ui/hooks.dart","in_app":false,"lineno":249,"filename":"hooks.dart"},{"function":"_CustomZone.runGuarded","abs_path":"dart:async/zone.dart","in_app":false,"lineno":923,"filename":"zone.dart"},{"function":"_CustomZone.run","abs_path":"dart:async/zone.dart","in_app":false,"lineno":1021,"filename":"zone.dart"},{"function":"_rootRun","abs_path":"dart:async/zone.dart","in_app":false,"lineno":1124,"filename":"zone.dart"},{"function":"SchedulerBinding._handleDrawFrame","abs_path":"package:flutter/src/scheduler/binding.dart","in_app":true,"lineno":891,"filename":"binding.dart"},{"function":"SchedulerBinding.handleDrawFrame","abs_path":"package:flutter/src/scheduler/binding.dart","in_app":true,"lineno":975,"filename":"binding.dart"},{"function":"SchedulerBinding._invokeFrameCallback","abs_path":"package:flutter/src/scheduler/binding.dart","in_app":true,"lineno":1033,"filename":"binding.dart"},{"function":"RendererBinding._handlePersistentFrameCallback","abs_path":"package:flutter/src/rendering/binding.dart","in_app":true,"lineno":280,"filename":"binding.dart"},{"function":"WidgetsBinding.drawFrame","abs_path":"package:flutter/src/widgets/binding.dart","in_app":true,"lineno":760,"filename":"binding.dart"},{"function":"BuildOwner.buildScope","abs_path":"package:flutter/src/widgets/framework.dart","in_app":true,"lineno":2348,"filename":"framework.dart"},{"function":"Element.rebuild","abs_path":"package:flutter/src/widgets/framework.dart","in_app":true,"lineno":3738,"filename":"framework.dart"},{"function":"ComponentElement.performRebuild","abs_path":"package:flutter/src/widgets/framework.dart","in_app":true,"lineno":3961,"filename":"framework.dart"},{"function":"Element.updateChild","abs_path":"package:flutter/src/widgets/framework.dart","in_app":true,"lineno":2893,"filename":"framework.dart"},{"function":"StatefulElement.update","abs_path":"package:flutter/src/widgets/framework.dart","in_app":true,"lineno":4120,"filename":"framework.dart"},{"function":"Element.rebuild","abs_path":"package:flutter/src/widgets/framework.dart","in_app":true,"lineno":3738,"filename":"framework.dart"},{"function":"ComponentElement.performRebuild","abs_path":"package:flutter/src/widgets/framework.dart","in_app":true,"lineno":3961,"filename":"framework.dart"},{"function":"Element.updateChild","abs_path":"package:flutter/src/widgets/framework.dart","in_app":true,"lineno":2893,"filename":"framework.dart"},{"function":"ProxyElement.update","abs_path":"package:flutter/src/widgets/framework.dart","in_app":true,"lineno":4254,"filename":"framework.dart"},{"function":"Element.rebuild","abs_path":"package:flutter/src/widgets/framework.dart","in_app":true,"lineno":3738,"filename":"framework.dart"},{"function":"ComponentElement.performRebuild","abs_path":"package:flutter/src/widgets/framework.dart","in_app":true,"lineno":3961,"filename":"framework.dart"},{"function":"Element.updateChild","abs_path":"package:flutter/src/widgets/framework.dart","in_app":true,"lineno":2893,"filename":"framework.dart"},{"function":"ProxyElement.update","abs_path":"package:flutter/src/widgets/framework.dart","in_app":true,"lineno":4254,"filename":"framework.dart"},{"function":"Element.rebuild","abs_path":"package:flutter/src/widgets/framework.dart","in_app":true,"lineno":3738,"filename":"framework.dart"},{"function":"ComponentElement.performRebuild","abs_path":"package:flutter/src/widgets/framework.dart","in_app":true,"lineno":3961,"filename":"framework.dart"},{"function":"Element.updateChild","abs_path":"package:flutter/src/widgets/framework.dart","in_app":true,"lineno":2893,"filename":"framework.dart"},{"function":"StatefulElement.update","abs_path":"package:flutter/src/widgets/framework.dart","in_app":true,"lineno":4120,"filename":"framework.dart"},{"function":"Element.rebuild","abs_path":"package:flutter/src/widgets/framework.dart","in_app":true,"lineno":3738,"filename":"framework.dart"},{"function":"ComponentElement.performRebuild","abs_path":"package:flutter/src/widgets/framework.dart","in_app":true,"lineno":3961,"filename":"framework.dart"},{"function":"Element.updateChild","abs_path":"package:flutter/src/widgets/framework.dart","in_app":true,"lineno":2893,"filename":"framework.dart"},{"function":"StatefulElement.update","abs_path":"package:flutter/src/widgets/framework.dart","in_app":true,"lineno":4120,"filename":"framework.dart"},{"function":"Element.rebuild","abs_path":"package:flutter/src/widgets/framework.dart","in_app":true,"lineno":3738,"filename":"framework.dart"},{"function":"ComponentElement.performRebuild","abs_path":"package:flutter/src/widgets/framework.dart","in_app":true,"lineno":3961,"filename":"framework.dart"},{"function":"Element.updateChild","abs_path":"package:flutter/src/widgets/framework.dart","in_app":true,"lineno":2893,"filename":"framework.dart"},{"function":"SingleChildRenderObjectElement.update","abs_path":"package:flutter/src/widgets/framework.dart","in_app":true,"lineno":5134,"filename":"framework.dart"},{"function":"Element.updateChild","abs_path":"package:flutter/src/widgets/framework.dart","in_app":true,"lineno":2893,"filename":"framework.dart"},{"function":"StatelessElement.update","abs_path":"package:flutter/src/widgets/framework.dart","in_app":true,"lineno":4016,"filename":"framework.dart"},{"function":"Element.rebuild","abs_path":"package:flutter/src/widgets/framework.dart","in_app":true,"lineno":3738,"filename":"framework.dart"},{"function":"ComponentElement.performRebuild","abs_path":"package:flutter/src/widgets/framework.dart","in_app":true,"lineno":3961,"filename":"framework.dart"},{"function":"Element.updateChild","abs_path":"package:flutter/src/widgets/framework.dart","in_app":true,"lineno":2893,"filename":"framework.dart"},{"function":"SingleChildRenderObjectElement.update","abs_path":"package:flutter/src/widgets/framework.dart","in_app":true,"lineno":5134,"filename":"framework.dart"},{"function":"Element.updateChild","abs_path":"package:flutter/src/widgets/framework.dart","in_app":true,"lineno":2893,"filename":"framework.dart"},{"function":"StatefulElement.update","abs_path":"package:flutter/src/widgets/framework.dart","in_app":true,"lineno":4120,"filename":"framework.dart"},{"function":"Element.rebuild","abs_path":"package:flutter/src/widgets/framework.dart","in_app":true,"lineno":3738,"filename":"framework.dart"},{"function":"ComponentElement.performRebuild","abs_path":"package:flutter/src/widgets/framework.dart","in_app":true,"lineno":3961,"filename":"framework.dart"},{"function":"Element.updateChild","abs_path":"package:flutter/src/widgets/framework.dart","in_app":true,"lineno":2893,"filename":"framework.dart"},{"function":"ProxyElement.update","abs_path":"package:flutter/src/widgets/framework.dart","in_app":true,"lineno":4254,"filename":"framework.dart"},{"function":"Element.rebuild","abs_path":"package:flutter/src/widgets/framework.dart","in_app":true,"lineno":3738,"filename":"framework.dart"},{"function":"ComponentElement.performRebuild","abs_path":"package:flutter/src/widgets/framework.dart","in_app":true,"lineno":3961,"filename":"framework.dart"},{"function":"Element.updateChild","abs_path":"package:flutter/src/widgets/framework.dart","in_app":true,"lineno":2893,"filename":"framework.dart"},{"function":"StatefulElement.update","abs_path":"package:flutter/src/widgets/framework.dart","in_app":true,"lineno":4120,"filename":"framework.dart"},{"function":"Element.rebuild","abs_path":"package:flutter/src/widgets/framework.dart","in_app":true,"lineno":3738,"filename":"framework.dart"},{"function":"ComponentElement.performRebuild","abs_path":"package:flutter/src/widgets/framework.dart","in_app":true,"lineno":3961,"filename":"framework.dart"},{"function":"Element.updateChild","abs_path":"package:flutter/src/widgets/framework.dart","in_app":true,"lineno":2893,"filename":"framework.dart"},{"function":"MultiChildRenderObjectElement.update","abs_path":"package:flutter/src/widgets/framework.dart","in_app":true,"lineno":5243,"filename":"framework.dart"},{"function":"RenderObjectElement.updateChildren","abs_path":"package:flutter/src/widgets/framework.dart","in_app":true,"lineno":4852,"filename":"framework.dart"},{"function":"Element.updateChild","abs_path":"package:flutter/src/widgets/framework.dart","in_app":true,"lineno":2893,"filename":"framework.dart"},{"function":"ProxyElement.update","abs_path":"package:flutter/src/widgets/framework.dart","in_app":true,"lineno":4254,"filename":"framework.dart"},{"function":"Element.rebuild","abs_path":"package:flutter/src/widgets/framework.dart","in_app":true,"lineno":3738,"filename":"framework.dart"},{"function":"ComponentElement.performRebuild","abs_path":"package:flutter/src/widgets/framework.dart","in_app":true,"lineno":3961,"filename":"framework.dart"},{"function":"Element.updateChild","abs_path":"package:flutter/src/widgets/framework.dart","in_app":true,"lineno":2893,"filename":"framework.dart"},{"function":"ProxyElement.update","abs_path":"package:flutter/src/widgets/framework.dart","in_app":true,"lineno":4254,"filename":"framework.dart"},{"function":"Element.rebuild","abs_path":"package:flutter/src/widgets/framework.dart","in_app":true,"lineno":3738,"filename":"framework.dart"},{"function":"ComponentElement.performRebuild","abs_path":"package:flutter/src/widgets/framework.dart","in_app":true,"lineno":3961,"filename":"framework.dart"},{"function":"Element.updateChild","abs_path":"package:flutter/src/widgets/framework.dart","in_app":true,"lineno":2893,"filename":"framework.dart"},{"function":"StatefulElement.update","abs_path":"package:flutter/src/widgets/framework.dart","in_app":true,"lineno":4120,"filename":"framework.dart"},{"function":"Element.rebuild","abs_path":"package:flutter/src/widgets/framework.dart","in_app":true,"lineno":3738,"filename":"framework.dart"},{"function":"ComponentElement.performRebuild","abs_path":"package:flutter/src/widgets/framework.dart","in_app":true,"lineno":3961,"filename":"framework.dart"},{"function":"Element.updateChild","abs_path":"package:flutter/src/widgets/framework.dart","in_app":true,"lineno":2893,"filename":"framework.dart"},{"function":"MultiChildRenderObjectElement.update","abs_path":"package:flutter/src/widgets/framework.dart","in_app":true,"lineno":5243,"filename":"framework.dart"},{"function":"RenderObjectElement.updateChildren","abs_path":"package:flutter/src/widgets/framework.dart","in_app":true,"lineno":4852,"filename":"framework.dart"},{"function":"Element.updateChild","abs_path":"package:flutter/src/widgets/framework.dart","in_app":true,"lineno":2893,"filename":"framework.dart"},{"function":"StatefulElement.update","abs_path":"package:flutter/src/widgets/framework.dart","in_app":true,"lineno":4120,"filename":"framework.dart"},{"function":"Element.rebuild","abs_path":"package:flutter/src/widgets/framework.dart","in_app":true,"lineno":3738,"filename":"framework.dart"},{"function":"ComponentElement.performRebuild","abs_path":"package:flutter/src/widgets/framework.dart","in_app":true,"lineno":3961,"filename":"framework.dart"},{"function":"Element.updateChild","abs_path":"package:flutter/src/widgets/framework.dart","in_app":true,"lineno":2893,"filename":"framework.dart"},{"function":"SingleChildRenderObjectElement.update","abs_path":"package:flutter/src/widgets/framework.dart","in_app":true,"lineno":5134,"filename":"framework.dart"},{"function":"Element.updateChild","abs_path":"package:flutter/src/widgets/framework.dart","in_app":true,"lineno":2893,"filename":"framework.dart"},{"function":"StatefulElement.update","abs_path":"package:flutter/src/widgets/framework.dart","in_app":true,"lineno":4120,"filename":"framework.dart"},{"function":"Element.rebuild","abs_path":"package:flutter/src/widgets/framework.dart","in_app":true,"lineno":3738,"filename":"framework.dart"},{"function":"ComponentElement.performRebuild","abs_path":"package:flutter/src/widgets/framework.dart","in_app":true,"lineno":3961,"filename":"framework.dart"},{"function":"Element.updateChild","abs_path":"package:flutter/src/widgets/framework.dart","in_app":true,"lineno":2893,"filename":"framework.dart"},{"function":"SingleChildRenderObjectElement.update","abs_path":"package:flutter/src/widgets/framework.dart","in_app":true,"lineno":5134,"filename":"framework.dart"},{"function":"Element.updateChild","abs_path":"package:flutter/src/widgets/framework.dart","in_app":true,"lineno":2893,"filename":"framework.dart"},{"function":"SingleChildRenderObjectElement.update","abs_path":"package:flutter/src/widgets/framework.dart","in_app":true,"lineno":5134,"filename":"framework.dart"},{"function":"Element.updateChild","abs_path":"package:flutter/src/widgets/framework.dart","in_app":true,"lineno":2893,"filename":"framework.dart"},{"function":"StatefulElement.update","abs_path":"package:flutter/src/widgets/framework.dart","in_app":true,"lineno":4120,"filename":"framework.dart"},{"function":"Element.rebuild","abs_path":"package:flutter/src/widgets/framework.dart","in_app":true,"lineno":3738,"filename":"framework.dart"},{"function":"ComponentElement.performRebuild","abs_path":"package:flutter/src/widgets/framework.dart","in_app":true,"lineno":3961,"filename":"framework.dart"},{"function":"Element.updateChild","abs_path":"package:flutter/src/widgets/framework.dart","in_app":true,"lineno":2904,"filename":"framework.dart"},{"function":"Element.inflateWidget","abs_path":"package:flutter/src/widgets/framework.dart","in_app":true,"lineno":3101,"filename":"framework.dart"},{"function":"MultiChildRenderObjectElement.mount","abs_path":"package:flutter/src/widgets/framework.dart","in_app":true,"lineno":5233,"filename":"framework.dart"},{"function":"Element.inflateWidget","abs_path":"package:flutter/src/widgets/framework.dart","in_app":true,"lineno":3087,"filename":"framework.dart"}]},"type":"NoSuchMethodError","value":"NoSuchMethodError: The getter 'key' was called on null.\nReceiver: null\nTried calling: key"}]},"fingerprint":["{{ default }}"],"grouping_config":{"enhancements":"eJybzDhxY3J-bm5-npWRgaGlroGxrpHxBABcTQcY","id":"newstyle:2019-05-08"},"hashes":["a4e99a1d5ce9ba07ba0d35336bcc6a52","03b96e5eefd292aac3e026a4a39f76c6"],"key_id":"958249","level":"error","location":"framework.dart","logger":"SentryClient","metadata":{"function":"Element.inflateWidget","type":"NoSuchMethodError","value":"NoSuchMethodError: The getter 'key' was called on null.\nReceiver: null\nTried calling: key","filename":"framework.dart"},"received":1570905785.266,"sdk":{"version":"2.2.0","name":"dart"},"timestamp":1570905783.0,"title":"NoSuchMethodError: NoSuchMethodError: The getter 'key' was called on null.","type":"error","version":"6"}
`

![e2ce48e6-9d4d-4d35-8e17-56ba47008e47](https://user-images.githubusercontent.com/35574146/66706820-95a2fa80-ed55-11e9-8558-f9fb17e06bef.jpeg)

**Comment by BondarenkoStas** [comment] 2019-10-14 18:03
@LaxmikanthMadhyastha On which exactly devices do you experience the crash? Can you came up with some minimal app which will reproduce the issue?

**Comment by LaxmikanthMadhyastha** [comment] 2019-10-15 04:28
@BondarenkoStas Thanks for the response, this is happening in 'oppo f9'.Since I dont know what is causing this problem its difficult to come up with the minimal app

**Comment by BondarenkoStas** [comment] 2019-10-15 10:10
@LaxmikanthMadhyastha can you try to copy the project and start to delete different parts until you see that the crash disappeared? So something which called the getter 'key' became null, but it won't be possible to debug without code.

**Comment by LaxmikanthMadhyastha** [comment] 2019-10-15 15:11
@BondarenkoStas Thanks will try that

**Comment by VladyslavBondarenko** [comment] 2020-01-15 15:12
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!

**Closed by VladyslavBondarenko** 2020-01-15 15:12 UTC
Labels: severe: crash

**Comment by priezz** [comment] 2020-06-18 18:34
Hello, I have exactly the same issue, which happens just to two users. Devices are Samsung Galaxy S9+ (SM-G965F, Android 10, happens constantly) and iPhone 11 (iOS 13.4.1, happened once). Can't reproduce on development devices.
