### ISSUE TITLE
Cloud firestore issue and BoringSSL-GRPC fatal error: 'openssl/base.h' file not found

### ISSUE THREAD

**Issue by arunkumarv** [flutter/flutter#62060] opened 2020-07-22 19:32 UTC
When I add cloud_firestore to my project I get an error. Previously it was working fine. Airtel hotspot was blocking `flutter pub get`. Unaware of that I run the following. 

```
 cd ~/.cocoapods/repos
 git clone --depth 1 https://github.com/CocoaPods/Specs.git master
```
Now this is the error
```
Launching lib/main.dart on iPhone 11 Pro Max in debug mode...
Running Xcode build...
Xcode build done.                                            7.7s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    In file included from /Users/akv/Desktop/FSProjects/fluttershare/ios/Pods/BoringSSL-GRPC/src/crypto/asn1/a_dup.c:57:
    /Users/akv/Desktop/FSProjects/fluttershare/ios/Pods/BoringSSL-GRPC/src/include/openssl/asn1.h:61:10: fatal error: 'openssl/base.h' file not found
    #include <openssl/base.h>
             ^~~~~~~~~~~~~~~~
    1 error generated.
    In file included from /Users/akv/Desktop/FSProjects/fluttershare/ios/Pods/BoringSSL-GRPC/src/crypto/x509/x_x509a.c:59:
    /Users/akv/Desktop/FSProjects/fluttershare/ios/Pods/BoringSSL-GRPC/src/include/openssl/asn1t.h:60:10: fatal error: 'openssl/base.h' file not found
    #include <openssl/base.h>
             ^~~~~~~~~~~~~~~~
    1 error generated.
    Command CompileC failed with a nonzero exit code
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description
    warning: Capabilities for Signing & Capabilities may not function correctly because its entitlements use a placeholder team ID. To resolve this, select a development team in the Runner editor. (in target 'Runner' from project 'Runner')

Could not build the application for the simulator.
Error launching application on iPhone 11 Pro Max.
```
My pubspec.yaml
```
pubspec.yaml
dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: 0.13.7
```
flutter doctor -v
```
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.2 19C57, locale en-GB)
    • Flutter version 1.17.5 at /Users/akv/Softwares/flutter
    • Framework revision 8af6b2f038 (3 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/akv/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4, Build version 11E146
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[✓] Connected device (1 available)
    • iPhone 11 Pro Max • C3E53B5F-F1AC-4DEE-A3C0-9D28A632D86D • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-4 (simulator)
```
I deleted ~/.cocoapods, tried uninstall and reinstall cocoapods, flutter upgrade, [this fix](https://medium.com/@phongyewtong/how-to-fix-flutter-stuck-at-running-pod-install-when-run-578ad867774), tried iPhone target 8, 13.4(iPhone 11). 
All to no avail

**Comment by TahaTesser** [comment] 2020-07-23 08:42
Hi @arunkumarv 
From what I can see, the issue is related to a FlutterFire plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by TahaTesser** 2020-07-23 08:42 UTC
