### ISSUE TITLE
Incorrect offset of text selection when using WidgetSpan within a TextField.

### ISSUE THREAD

**Issue by Ian-Suris** [flutter/flutter#150864] opened 2024-06-26 18:05 UTC
### Steps to reproduce

1. Create a TextField
2. Create a class inherited from TextEditingController
3. Set it as the controller for the TextField
4. Implement buildTextSpan where a set of words are displayed as WidgetSpan
5. Write in the TextField the words that will be displayed as WidgetSpan
6. Play a bit with the selection position moving forward and backwards
7. Delete or enter some characters a few positions after ending the WidgetSpan

### Expected results

The characters deleted should be the ones you are selection or are inmediately aside the cursor.

### Actual results

The cursor position is calculated as if widgets were a single character, while it is displayed as if their length were their string's size.
For example, if I have this tring "AABBCCDD" where "BBCC" is displayed with a WidgetSpan and the cursos is positioned between the two "D", when I press return it will delete the second "B" instead of the first "D".

### Code sample

<details open><summary>Code sample</summary>
It is fully reproducible in DartPad.

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Directionality(
          textDirection: TextDirection.ltr,
          child: ChipTextInput(),
        ),
      ),
    );
  }
}

class ChipTextInput extends StatefulWidget {
  const ChipTextInput({
    super.key,
    this.onChanged,
  });

  final ValueChanged<String>? onChanged;

  @override
  ChipTextInputState createState() => ChipTextInputState();
}

class ChipTextInputState extends State<ChipTextInput> {
  @override
  void initState() {
    super.initState();
    _keyWordsRegex = RegExp(r'\<(AABBCC|DDEEFF|GGHHII)\>');
    _controller = RichTextEditingController(_keyWordsRegex);
  }

  late final RichTextEditingController _controller;
  late final RegExp _keyWordsRegex;

  @override
  Widget build(BuildContext context) {
    return TextField(
      controller: _controller,
      onChanged: widget.onChanged,
    );
  }
}

class RichTextEditingController extends TextEditingController {
  RichTextEditingController(RegExp keyWordsRegex)
      : _keyWordsRegex = keyWordsRegex;

  final RegExp _keyWordsRegex;

  @override
  TextSpan buildTextSpan({
    required BuildContext context,
    TextStyle? style,
    required bool withComposing,
  }) {
    Iterable<RegExpMatch> matches = _keyWordsRegex.allMatches(text);
    List<InlineSpan> result = [];
    int lastEnd = 0;

    for (RegExpMatch match in matches) {
      int start = match.start;
      int end = match.end;

      if (lastEnd < start) {
        result.add(TextSpan(
          text: text.substring(lastEnd, start),
        ));
      }

      result.add(
        WidgetSpan(
          child: Container(
            decoration: BoxDecoration(
                border: Border.all(
              color: Colors.black,
            )),
            child: Text(
              text.substring(start, end),
            ),
          ),
        ),
      );

      lastEnd = end;
    }
    if (lastEnd < text.length) {
      result.add(TextSpan(
        text: text.substring(lastEnd),
      ));
    }
    return TextSpan(children: result);
  }
}

```

</details>

### Flutter Doctor output

[√] Flutter (Channel stable, 3.22.1, on Microsoft Windows [Versi¢n 10.0.22631.3737], locale es-MX)
    • Flutter version 3.22.1 on channel stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a14f74ff3a (5 weeks ago), 2024-05-22 11:08:21 -0500
    • Engine revision 55eae6864b
    • Dart version 3.4.1
    • DevTools version 2.34.3

[√] Windows Version (Installed version of Windows is version 10 or higher)

[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.8.5)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.8.34511.84
    X Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop development with C++" workload, and include these components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK

[√] Android Studio (version 2023.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)

[√] VS Code (version 1.90.2)
    • VS Code
    • Flutter extension version 3.90.0

[√] Connected device (3 available)
    • Windows (desktop)   • windows          • windows-x64    • Microsoft Windows [Version 10.0.22631.3737]
    • Chrome (web)        • chrome           • web-javascript • Google Chrome 126.0.6478.114
    • Edge (web)          • edge             • web-javascript • Microsoft Edge 126.0.2592.68

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.

**Comment by darshankawar** [comment] 2024-06-27 07:07
@Ian-Suris 
What platform are you seeing the reported behavior ?
I tried the code sample using latest stable version on web and desktop, and was able to see that the first `D` gets deleted upon pressing `delete` button.

**Comment by Ian-Suris** [comment] 2024-06-27 21:09
Both Android with SDK 12 and online DartPad. I also tried dartPad in Chrome and Firefox, it still has the same behavior.

**Comment by darshankawar** [comment] 2024-06-28 06:06
I am unable to replicate upon running on android emulator as well. Please provide us a short video.

**Comment by gorkovv** [comment] 2024-06-28 06:34
I confirm, the same garbage started with version 3.22.0. Multiple WidgetSpans now overlap each other. And along with them the text (TextSpan) - everything gets bunched up, layered on top of each other.
Thanks to the author for describing the problem, otherwise I was too lazy -))
In my text editor, which I write, the text with pictures now looks like this.
![image](https://github.com/flutter/flutter/assets/7299332/a470804f-eb47-4c2e-b7ca-b28ea0c44f3f)

**Comment by Ian-Suris** [comment] 2024-06-28 17:59
Here's the code snippet running:
https://github.com/flutter/flutter/assets/171177505/0124d2ce-d0d0-4256-9d67-a701fe288af0

**Comment by darshankawar** [comment] 2024-07-01 05:45
Thanks for the video. Using the code sample provided, I was able to replicate the reported behavior in latest versions.

<details>
<summary> stable, master flutter doctor -v </summary>

```
[!] Flutter (Channel stable, 3.22.2, on macOS 12.2.1 21D62 darwin-x64, locale
    en-GB)
    • Flutter version 3.22.2 on channel stable at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 761747bfc5 (33 hours ago), 2024-06-05 22:15:13 +0200
    • Engine revision edd8546116
    • Dart version 3.4.3
    • DevTools version 2.34.3
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

[!] Flutter (Channel master, 3.23.0-13.0.pre.357, on macOS 12.2.1 21D62
    darwin-x64, locale en-GB)
    • Flutter version 3.23.0-13.0.pre.357 on channel master at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 805d79607e (87 minutes ago), 2024-06-27 05:53:58 +0200
    • Engine revision a9194f0f01
    • Dart version 3.5.0 (build 3.5.0-304.0.dev)
    • DevTools version 2.36.0
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/dhs/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13C100
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 65.1.4
    • Dart plugin version 213.7228

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (3 available)
    • Darshan's iphone (mobile) • 21150b119064aecc249dfcfe05e259197461ce23 • ios
      • iOS 15.3.1 19D52
    • macOS (desktop)           • macos                                    •
      darwin-x64     • macOS 12.2.1 21D62 darwin-x64
    • Chrome (web)              • chrome                                   •
      web-javascript • Google Chrome 109.0.5414.119

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
      
[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.



```

</details>

**Comment by Renzo-Olivares** [comment] 2024-07-23 21:49
Hi @Ian-Suris, thank you for reporting this issue. This is a duplicate of https://github.com/flutter/flutter/issues/107432 . I think  https://github.com/flutter/flutter/issues/107432#issuecomment-1186003674 provides a good explanation on why this behavior is happening. Closing this issue in favor of the original one.

**Closed by Renzo-Olivares** 2024-07-23 21:49 UTC
Labels: a: text input, framework, a: typography, has reproducible steps, team-text-input, found in release: 3.22, found in release: 3.23
