### ISSUE TITLE
[tool_crash] ProcessException: The command failedStdout:Stderr:error:  cannot delete old /Users/user2022/Desktop/development/flutter/bin/cache/artifacts/engine/darwin-x64/FlutterMacOS.framework/Resources        Operation not permittederror: 

### ISSUE THREAD

**Issue by sfyanbel** [flutter/flutter#77590] opened 2021-03-08 11:58 UTC
## Command
```
flutter doctor
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ProcessException: The command failed
Stdout:

Stderr:
error:  cannot delete old /Users/user2022/Desktop/development/flutter/bin/cache/artifacts/engine/darwin-x64/FlutterMacOS.framework/Resources
        Operation not permitted
error:  cannot delete old /Users/user2022/Desktop/development/flutter/bin/cache/artifacts/engine/darwin-x64/FlutterMacOS.framework/Versions/Current
        Operation not permitted
error:  cannot delete old /Users/user2022/Desktop/development/flutter/bin/cache/artifacts/engine/darwin-x64/FlutterMacOS.framework/Headers
        Operation not permitted
error:  cannot delete old /Users/user2022/Desktop/development/flutter/bin/cache/artifacts/engine/darwin-x64/FlutterMacOS.framework/Modules
        Operation not permitted
 Command: unzip, OS error code: 50
```
#0      RunResult.throwException (package:flutter_tools/src/base/process.dart:172:5)
#1      _DefaultProcessUtils.runSync (package:flutter_tools/src/base/process.dart:463:17)
#2      _PosixUtils.unzip (package:flutter_tools/src/base/os.dart:231:19)
#3      EngineCachedArtifact.updateInner (package:flutter_tools/src/cache.dart:727:22)
#4      _rootRunUnary (dart:async/zone.dart:1198:47)
#5      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#6      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#8      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#9      Future._completeWithValue (dart:async/future_impl.dart:529:5)
#10     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#11     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#12     ArtifactUpdater._downloadArchive (package:flutter_tools/src/cache.dart)
#13     _rootRunUnary (dart:async/zone.dart:1198:47)
#14     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#15     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#16     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#17     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#18     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#19     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
#20     _rootRun (dart:async/zone.dart:1190:13)
#21     _CustomZone.run (dart:async/zone.dart:1093:19)
#22     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#23     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#24     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
```
```
[✓] Flutter (Channel unknown, 1.22.5, on macOS 11.1 20C69 darwin-x64, locale
    en-GB)
    • Flutter version 1.22.5 at /Users/user2022/Desktop/development/flutter
    • Framework revision 7891006299 (3 months ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/user2022/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Library/Internet
      Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_281-b09)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.1

[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup
      for detailed instructions).

[✓] Connected device (1 available)
    • iPhone 12 Pro Max (mobile) • 952ABEA3-B73D-4A1F-B0C0-ED8306CBC59C • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-14-2 (simulator)

! Doctor found issues in 2 categories.

```

## Flutter Application Metadata
No pubspec in working directory.

**Comment by pedromassangocode** [comment] 2021-03-08 12:49
This seems to be a duplicate of https://github.com/flutter/flutter/issues/77234 which was recently fixed by https://github.com/flutter/flutter/pull/77316.

Please upgrade your Flutter version and try again.
Thank you

**Closed** 2021-03-09 12:27 UTC
Labels: in triage, waiting for customer response
