### ISSUE TITLE
[go_router]The queryParams always exists when refreshed browser

### ISSUE THREAD

**Issue by JDongKhan** [flutter/flutter#122175] opened 2023-03-08 07:33 UTC
1、goto  go_router/examplelib/main.dart
2、add field id to DetailsScreen and modify GoRouter 
3、run flutter run -d chrome 
4、tap Go to the Details screen button
5、refresh browser
6、tap backbutton
7、the queryParams always exists  when navigate to HomeScreen.

```
dependencies:
   go_router: ^6.2.0


[✓] Flutter (Channel stable, 3.7.6, on macOS 13.0 22A380 darwin-x64, locale zh-Hans-CN)
    • Flutter version 3.7.6 on channel stable at /Users/sn/fvm/versions/3.7.6
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 12cb4eb7a0 (7 days ago), 2023-03-01 10:29:26 -0800
    • Engine revision ada363ee93
    • Dart version 2.19.3
    • DevTools version 2.20.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn


```

<details>
<summary>Code sample</summary>

```dart

// Copyright 2013 The Flutter Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';

/// This sample app shows an app with two screens.
///
/// The first route '/' is mapped to [HomeScreen], and the second route
/// '/details' is mapped to [DetailsScreen].
///
/// The buttons use context.go() to navigate to each destination. On mobile
/// devices, each destination is deep-linkable and on the web, can be navigated
/// to using the address bar.
void main() => runApp(const MyApp());

/// The route configuration.
final GoRouter _router = GoRouter(
  routes: <RouteBase>[
    GoRoute(
      path: '/',
      builder: (BuildContext context, GoRouterState state) {
        return const HomeScreen();
      },
      routes: <RouteBase>[
        GoRoute(
          path: 'details',
          builder: (BuildContext context, GoRouterState state) {
            return DetailsScreen(id: state.queryParams['id'].toString());
          },
        ),
      ],
    ),
  ],
);

/// The main app.
class MyApp extends StatelessWidget {
  /// Constructs a [MyApp]
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(
      routerConfig: _router,
    );
  }
}

/// The home screen
class HomeScreen extends StatelessWidget {
  /// Constructs a [HomeScreen]
  const HomeScreen({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Home Screen')),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            ElevatedButton(
              onPressed: () => context.push(
                '/details?id=1',
              ),
              child: const Text('Go to the Details screen'),
            ),
          ],
        ),
      ),
    );
  }
}

/// The details screen
class DetailsScreen extends StatelessWidget {
  final String id;

  /// Constructs a [DetailsScreen]
  const DetailsScreen({Key? key, required this.id}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Details Screen')),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <ElevatedButton>[
            ElevatedButton(
              onPressed: () => context.go('/'),
              child: Text('Go back to the Home screen:${id}'),
            ),
          ],
        ),
      ),
    );
  }
}


```

</details>

https://user-images.githubusercontent.com/4929805/223649803-4d660067-dc33-4ce3-b4fd-ab039317cbc0.mov

**Comment by exaby73** [comment] 2023-03-08 10:41
Duplicate of https://github.com/flutter/flutter/issues/117657. This is working as intended

**Closed by exaby73** 2023-03-08 10:41 UTC
Labels: in triage
