### ISSUE TITLE
`flutter doctor --android-licenses`  throws `Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema`

### ISSUE THREAD

**Issue by sbane256** [flutter/flutter#84325] opened 2021-06-10 05:41 UTC
- On the installation steps, ran flutter doctor in powershell and it comes up with the following:
```console
√] Flutter (Channel stable, 2.2.0, on Microsoft Windows [Version 10.0.18363.1556], locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[√] Chrome - develop for the web
[!] Android Studio (not installed)
[√] IntelliJ IDEA Community Edition (version 2021.1)
[√] Connected device (2 available)

- Then ran flutter doctor --android-licenses:
- Unrecognized option: -
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

I have jdk-16.0.1 installed. Not sure what to do

**Comment by tnc1997** [comment] 2021-06-10 06:04
Hi @sbane256, I have experienced this in the past when using a newer version of the JDK to perform actions such as accepting the Android licenses. I believe that Android still requires version 8, could you try running that command again using JDK 8?

![image](https://user-images.githubusercontent.com/17160067/121473006-ec912500-c9b9-11eb-8ec9-b22567840d4c.png)

**Comment by darshankawar** [comment] 2021-06-10 09:57
@sbane256 
Check above comment and try with JDK 8 to see if it resolves your issue. If it does and running the command again gives you another error like `Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema`, then you'll need to install Android SDK Command-line tools from Android Studio with which you should be able to accept licenses.

**Comment by mehtahardikr** [comment] 2021-06-10 11:40
Related to https://github.com/flutter/flutter/issues/83648
issue can be resolved by installing Android SDK Command-line tools from Android Studio.

**Comment by sbane256** [comment] 2021-06-10 16:55
Thanks-still running into some issues:
- Uninstalled JDK 16
- Downloaded JDK 8 from https://www.oracle.com/java/technologies/javase/javase-jdk8-downloads.html
- Made sure and tried to see the version on Powershell:

PS C:\Users\banersh> java -version
java version "1.8.0_291"
Java(TM) SE Runtime Environment (build 1.8.0_291-b10)
Java HotSpot(TM) 64-Bit Server VM (build 25.291-b10, mixed mode)

- Ran flutter doctor and still getting the same issue (see below). Also already installed Android SDK command-line tools from Android Studio:

**PS C:\Users\banersh> flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.2.0, on Microsoft Windows [Version 10.0.18363.1556], locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[√] Chrome - develop for the web
[!] Android Studio (not installed)
[√] IntelliJ IDEA Community Edition (version 2021.1)
[√] Connected device (2 available)**

! Doctor found issues in 2 categories.
PS C:\Users\banersh> flutter doctor --android-licenses
Unrecognized option: -
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

-Tried exiting out and editing variables to include JAVA_HOME and the java/bin in the Path but that didn't help either.

Any help?

**Comment by tnc1997** [comment] 2021-06-10 18:19
Hi @sbane256, sorry that the above didn't work, out of interest do you get the same error running this command?

```powershell
& "$Env:ANDROID_SDK_ROOT\tools\bin\sdkmanager" --licenses --verbose
```

**Comment by chamithopatha** [comment] 2021-06-10 19:07
I had
![Screenshot (74)](https://user-images.githubusercontent.com/33263487/121582873-2cedb300-ca4d-11eb-9fcc-7c0fbf343b72.png)
 face this problem

**Comment by tnc1997** [comment] 2021-06-10 20:26
Hi @sbane256, apologies that didn't work, yeah it looks like an issue with Flutter & Java for some reason. Are there any additional details that you might be able to share by running `flutter doctor --verbose`?

**Comment by sbane256** [comment] 2021-06-10 23:23
Hi @tnc1997 Thanks for sharing. I ran it and this is what it executed:

Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS C:\Users\banersh> flutter doctor --verbose
[√] Flutter (Channel stable, 2.2.0, on Microsoft Windows [Version 10.0.18363.1556], locale en-US)
    • Flutter version 2.2.0 at C:\Users\banersh\OneDrive - EY\Desktop\Flutter\flutter
    • Framework revision b22742018b (4 weeks ago), 2021-05-14 19:12:57 -0700
    • Engine revision a9d88a4d18
    • Dart version 2.13.0

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\banersh\OneDrive - EY\Desktop\Flutter\android-sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_SDK_ROOT = C:\Users\banersh\OneDrive - EY\Desktop\Flutter\android-sdk
    • Java binary at: C:\Program Files\Java\jdk1.8.0_291\bin\java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_291-b10)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] IntelliJ IDEA Community Edition (version 2021.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 91.0.4472.77
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 91.0.864.41

! Doctor found issues in 2 categories.
PS C:\Users\banersh> flutter doctor --android-licenses
Unrecognized option: -
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
PS C:\Users\banersh>

**Comment by darshankawar** [comment] 2021-06-11 05:58
`Unrecognized option: -` seems to be incomplete, so can't really know what option is it pointing to. Usually it points to an exe or module which is not recognized.

Keeping this open for further investigation from team.

**Comment by TrustDec** [comment] 2021-06-24 06:21
➜ ~ flutter doctor
Running "flutter pub get" in flutter_tools...                       5.8s
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.2, on macOS 11.4 20F71 darwin-x64, locale
    zh-Hans-CN)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] VS Code (version 1.57.1)
[✓] Connected device (2 available)


➜ ~ flutter doctor --android-licenses
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
	at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
	at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
	at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 5 more
➜ ~ java -version
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_212-b03)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.212-b03, mixed mode)

**Comment by TahaTesser** [comment] 2021-07-13 09:08
Hi @sbane256  and everyone
First, make sure you've also installed cmd tools and then `flutter doctor --android-licenses` 
![image](https://user-images.githubusercontent.com/48603081/125423425-88796caa-f1f0-4d9b-a7c2-e0cc8edf1a88.png)


If the problem persists, I am not sure where I read it but this is likely a bug with this particular java version too

`C:\Users\Taha\Code\android-studio\jre\bin\java` 

My Java path is set to default JDK that comes with Android Studio itself, which java 11, and there is no issue when executing `flutter doctor --android-licenses` 


```console
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\android-sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_SDK_ROOT = C:\Users\Taha\Code\android-sdk
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.
```

Hope this helps

**Comment by PrakTech** [comment] 2021-07-17 08:47
i do have same issue that why i installed the java 8 from oracle and set  JAVA_HOME  but i ran below issue 
```
C:\Windows\system32>flutter doctor --android-licenses

ERROR: JAVA_HOME is set to an invalid directory: C:\Program Files\Java\jdk1.8.0_29

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation.
```
Then i follow the https://github.com/flutter/flutter/issues/84325#issuecomment-878915400 and install Android SDK Command line tools. After that i run flutter doctor --android-licenses , still throw java_home error then i removed environment variable JAVA_HOME  then i restart my system and run flutter doctor --android-licenses then it works. 
 Conclusion : No need to install external jdk 8  or any version. 
 Thanks TahaTesser and other

**Comment by TahaTesser** [comment] 2021-07-21 10:28
@PrakTech 
Thanks for the confirmation, I feel safe to close the issue

**Closed** 2021-07-21 10:29 UTC
Labels: passed first triage, t: flutter doctor, tool
