### ISSUE TITLE
flutter build apk does not fails if the compiler fails

### ISSUE THREAD

**Issue by sherpya** [flutter/flutter#18477] opened 2018-06-14 11:35 UTC
the package dson_core-0.13.2 raises a compiler error, but `flutter build apk` does not stops and produces a crashing apk, here the output of the command:

```
Running "flutter packages get" in flutter_seafuture...       0.5s
Initializing gradle...                                       0.6s
Resolving dependencies...                                    1.1s
Running 'gradlew assembleRelease'...                             
Configuration 'compile' in project ':barcode_scan' is deprecated. Use 'implementation' instead.
compiler message: file:///home/sherpya/.pub-cache/hosted/pub.dartlang.org/dson_core-0.13.2/lib/src/deserializer.dart:167:43: Error: The method 'add' isn't defined for the class 'dart._internal::EfficientLengthIterable<dynamic>'.
compiler message: Try correcting the name to the name of an existing method, or defining a method named 'add'.
compiler message:   fillerList.forEach((item) => resultList.add(_convertValue(subType, item, "@LIST_ITEM")));
compiler message:                                           ^
Compiler terminated unexpectedly.
Built build/app/outputs/apk/release/app-release.apk (9.0MB).
```

After two runs the compiler error disappears but obviously the apk is incorrect

```
Initializing gradle...                                       0.6s
Resolving dependencies...                                    0.9s
Running 'gradlew assembleRelease'...                             
Configuration 'compile' in project ':barcode_scan' is deprecated. Use 'implementation' instead.
Built build/app/outputs/apk/release/app-release.apk (9.0MB).
```

**Comment by mit-mit** [comment] 2018-06-14 15:47
Duplicate of https://github.com/flutter/flutter/issues/14012

**Closed by mit-mit** 2018-06-14 15:47 UTC
