### ISSUE TITLE
reapaintBoundary can't catch pictures in platformview

### ISSUE THREAD

**Issue by wanjm** [flutter/flutter#70522] opened 2020-11-14 04:18 UTC
reapaintBoundary can't catch pictures in platformview

both pictures in webview_flutter and video_player can't be catched  by toImage of repaintBoundary;

**Comment by pedromassangocode** [comment] 2020-11-16 09:21
Hi @wanjm 
Can you please provide your `flutter doctor -v`, the actual vs expected results and a minimal complete reproducible code sample?
Thank you

**Comment by wanjm** [comment] 2020-12-05 14:30
#25306 is talking the same problem, though he thought it is a problem of webview_flutter, in fact it is a problem with PlatformView

**Comment by pedromassangocode** [comment] 2020-12-07 07:48
Hi @wanjm 
Thanks for pointing that out.

I'm going to close this one as a duplicate of https://github.com/flutter/flutter/issues/25306. I will update https://github.com/flutter/flutter/issues/25306 to cover platform views and not just `webview`. Please follow up on that issue.

Thank you

**Closed by pedromassangocode** 2020-12-07 07:48 UTC
Labels: in triage
