### ISSUE TITLE
Squircle button decoration

### ISSUE THREAD

**Issue by lukepighetti** [flutter/flutter#18752] opened 2018-06-23 12:16 UTC
Looking for a button decoration to give it squircle corners (g3 curvature continuity) instead of just rounded corners. Will improve the native look on iOS.

**Comment by nesscx** [comment] 2018-06-25 10:04
#13914

**Comment by goderbauer** [comment] 2019-01-02 18:50
This looks like a dupe of https://github.com/flutter/flutter/issues/13914.

**Closed by goderbauer** 2019-01-02 18:50 UTC
Labels: a: fidelity, framework, ⌺‬ platform-ios

**Comment by dnfield** [comment] 2019-01-10 20:23
FYI this is now available as of #26295 in the framework.

#13914 will stay open to track actually using it when on iOS.
