### ISSUE TITLE
Infra Failure: Step('Upload metrics.upload metrics') (canceled) (retcode: -15)

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#82972] opened 2021-05-20 02:03 UTC
Several tasks are failing to upload metrics to the cocoon backend.

Links:

https://ci.chromium.org/p/flutter/builders/prod/Linux%20flutter_test_performance/1432
https://ci.chromium.org/p/flutter/builders/prod/Linux%20complex_layout_semantics_perf/1442

**Comment by yusufm** [comment] 2021-05-20 17:10
The upload step was cancelled, seemingly, due to timing out. Some characteristics of the failure:

- These issues all happened during a small time window. 
- They succeeded on reruns.
- Seem to only have occurred on linux bots.
- But not isolated to one specific bot (linux-1, linux-3, etc.)

We have noted recently increase in failures that seem to be due to unexplained network issues.

Will continue to investigate the issue, but for the last few weeks we have not been able to pinpoint the cause of (assumed) network outages that have been happening, especially in the windows and linux fleets.

**Comment by godofredoc** [comment] 2021-06-01 18:21
@yusufm any updates on this bug?

**Comment by godofredoc** [comment] 2021-07-29 19:51
Moving as P2 as this is happening very frequently. Did we ever implemented the retries at the http request level?

**Comment by yusufm** [comment] 2021-08-04 20:31
Fix is in, the upload metrics failures should not show up any more. If they do, please reopen this issue.

**Closed by yusufm** 2021-08-04 20:31 UTC
Labels: P2, passed secondary triage, team: infra
