### ISSUE TITLE
Potential memory leak with misbehaving plugins

### ISSUE THREAD

**Issue by ened** [flutter/flutter#61546] opened 2020-07-15 14:55 UTC
## Steps to Reproduce

We have noticed that a particular plugin generates **endless errors** and pushes them to the Engine through a `EventChannel` error signal.

This behaviour, while faulty itself, caused a memory leak and eventually got the App OOM killed.

In a isolated debug session this quickly shows up like so:

<img width="1020" alt="Screenshot 2020-07-15 at 15 42 42" src="https://user-images.githubusercontent.com/269860/87559147-d39cc880-c6b1-11ea-8078-75c57b126783.png">

The increased memory usage on "native" (Flutter side) can be clearly seen.

Example project is here: https://github.com/ened/flt_perf_11_error_events and has 3 features:

- Generate a error in the plugin as often as possible
- Generate a error in dart consumer side as often as possible
- Just successfully listen to as many events as possible

Cases 1 & 2 show the memory spike, case 3 does not.

```
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.5 19F101, locale en-GB)
    • Flutter version 1.17.5 at /Users/sebastian/dev/flutter
    • Framework revision 8af6b2f038 (2 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/sebastian/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/sebastian/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2
```

**Comment by zanderso** [comment] 2020-07-16 20:02
If possible can you connect to the Observatory and collect an allocation profile while in the midst of the unbounded growth?

https://dart-lang.github.io/observatory/allocation-profile.html

**Comment by ened** [comment] 2020-07-16 21:27
Ok will try. I'm not sure if the observatory will be responsive as the app is not responsive either. (Pointing to a main thread blockage).

**Comment by ened** [comment] 2020-07-17 08:55
@zanderso please take a look:

It seems the memory allocation in Dart on the left stayed somewhat reasonable, but the growth could be seen when enabling the "Android Memory" chart. Eventually the dev tools stopped responding.

<img width="2293" alt="Screenshot 2020-07-17 at 09 48 06" src="https://user-images.githubusercontent.com/269860/87767527-b0d5f580-c812-11ea-878d-1b0c61e20dcb.png">

**Comment by ened** [comment] 2020-07-17 09:00
To be honest, I may not understand the Observatory, in regards to the link sent above. I can not find the screenshots or the buttons mentioned. It seems to me the leak happens in the native side (engine) rather than Dart as the numbers increase there instead of Dart objects. 

Happy to learn what I'm doing wrong. :)

**Comment by jason-simmons** [comment] 2020-07-18 00:44
Took a look at this, and from what I can tell memory usage is increasing because the Java side is generating events faster than the Dart side can handle them.

Try this:
* on the Java side, add a counter and increment and log it each time an event is sent
* on the Dart side, add a counter and increment and log it each time an event is received
* reduce the maximum iteration count in the app to something like 100000

The sent counter will quickly outpace the received counter, and native heap usage will increase rapidly until the sent counter reaches the maximum iteration.  At that point heap usage will stabilize as the Dart side processes the queued messages.  After all the messages have been drained, garbage collection will run and native heap usage should revert to roughly where it started.

**Comment by ened** [comment] 2020-07-18 20:12
@jason-simmons you mention "events" - does this cover regular data events as well? In my quick test the regular data event did not cause a memory spike, only the error cases.

I can see how the case of a rogue plugin causing memory havoc is probably not worthy of any bugfix time. 

Although, the error may also appear with a much lower number like 1000 or 10000, depending on the target phone, RAM constraints etc.
Once the issue happens, it's extremely cumbersome to decipher "abort" unless the phone is directly connected to the developer machine.

**Comment by jason-simmons** [comment] 2020-07-18 20:29
This applies to any message sent between Java and Dart.  If the Java side sends messages faster than the Dart side can consume them, then the messages will accumulate in a queue until the Dart side can catch up.

If the queue is consuming too much memory, then the Java side will need to limit the rate at which it sends messages.

**Comment by zanderso** [comment] 2020-07-20 16:57
Based on this discussion, it looks like this is working as intended, so I will go ahead and close this. @ened please feel free to re-open if the leak persists after implementing @jason-simmons' suggestions. Thanks!

**Closed by zanderso** 2020-07-20 16:57 UTC
Labels: engine, found in release: 1.17, has reproducible steps, p: framework, perf: memory

**Comment by ened** [comment] 2020-07-20 16:58
Alright, thank you all for the help and seems like no action needed at this moment.
