### ISSUE TITLE
[tool_crash] FileSystemException: Cannot create link, OS Error: Incorrect function., errno = 1

### ISSUE THREAD

**Issue by Shaileshkanoriya** [flutter/flutter#136321] opened 2023-10-11 05:14 UTC
## Command
```
flutter --no-color pub upgrade
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Cannot create link, OS Error: Incorrect function.
, errno = 1
```
#0      _Link.throwIfError (dart:io/link.dart:254:7)
#1      _Link.createSync (dart:io/link.dart:182:5)
#2      ForwardingLink.createSync (package:file/src/forwarding/forwarding_link.dart:20:16)
#3      ForwardingLink.createSync (package:file/src/forwarding/forwarding_link.dart:20:16)
#4      _createPlatformPluginSymlinks (package:flutter_tools/src/flutter_plugins.dart:1055:12)
#5      createPluginSymlinks (package:flutter_tools/src/flutter_plugins.dart:985:5)
#6      refreshPluginsList (package:flutter_tools/src/flutter_plugins.dart:1087:5)
<asynchronous suspension>
#7      FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:357:5)
<asynchronous suspension>
#8      PackagesGetCommand.runCommand (package:flutter_tools/src/commands/packages.dart:337:7)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1297:27)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#11     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:339:9)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:285:5)
<asynchronous suspension>
#15     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:115:9)
```
```
[✓] Flutter (Channel stable, 3.13.5, on Microsoft Windows [Version 10.0.22621.2361], locale en-IN)
    • Flutter version 3.13.5 on channel stable at E:\Android\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 12fccda598 (3 weeks ago), 2023-09-19 13:56:11 -0700
    • Engine revision bd986c5ed2
    • Dart version 3.1.2
    • DevTools version 2.25.0

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at E:\Android\Sdk
    • Platform android-UpsideDownCakePrivacySandbox, build-tools 34.0.0
    • ANDROID_HOME = E:\Android\Sdk
    • Java binary at: E:\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.7.4)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.7.34031.279
    • Windows 10 SDK version 10.0.22621.0

[✓] Android Studio (version 2022.2)
    • Android Studio at E:\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)

[✓] VS Code (version 1.82.3)
    • VS Code at C:\Users\APPLE\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22621.2361]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 117.0.5938.149
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 117.0.2045.60

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: cd41fdd495f6944ecd3506c21e94c6567b073278
### Plugins
connectivity-3.0.6
connectivity_for_web-0.4.0+1
connectivity_macos-0.2.1+2
file_selector_linux-0.9.2+1
file_selector_macos-0.9.3+3
file_selector_windows-0.9.3+1
firebase_auth-4.10.1
firebase_auth_web-5.8.2
firebase_core-2.17.0
firebase_core_web-2.8.0
firebase_messaging-14.6.9
firebase_messaging_web-3.5.8
flutter_local_notifications-12.0.4
flutter_login_facebook-1.8.0
flutter_phone_direct_caller-2.1.1
flutter_plugin_android_lifecycle-2.0.16
fluttertoast-8.2.2
geocoding-2.1.1
geocoding_android-2.1.2
geocoding_ios-2.1.0
geolocator-9.0.2
geolocator_android-4.3.1
geolocator_apple-2.3.2
geolocator_web-2.2.0
geolocator_windows-0.1.3
google_api_headers-1.6.0
google_maps_flutter-2.5.0
google_maps_flutter_android-2.5.1
google_maps_flutter_ios-2.3.2
google_maps_flutter_web-0.5.4+2
google_sign_in-5.4.4
google_sign_in_android-6.1.20
google_sign_in_ios-5.6.3
google_sign_in_web-0.10.2+1
image_picker-0.8.9
image_picker_android-0.8.8+1
image_picker_for_web-2.2.0
image_picker_ios-0.8.8+2
image_picker_linux-0.2.1+1
image_picker_macos-0.2.1+1
image_picker_windows-0.2.1+1
location-4.4.0
location_web-3.1.1
package_info_plus-4.1.0
path_provider-2.1.1
path_provider_android-2.2.0
path_provider_foundation-2.3.1
path_provider_linux-2.2.1
path_provider_windows-2.2.1
permission_handler-10.4.5
permission_handler_android-10.3.6
permission_handler_apple-9.1.4
permission_handler_windows-0.1.3
razorpay_flutter-1.3.5
shared_preferences-2.2.2
shared_preferences_android-2.2.1
shared_preferences_foundation-2.3.4
shared_preferences_linux-2.3.1
shared_preferences_web-2.2.1
shared_preferences_windows-2.3.1
sqflite-2.3.0
url_launcher-6.1.14
url_launcher_android-6.1.0
url_launcher_ios-6.1.5
url_launcher_linux-3.0.6
url_launcher_macos-3.0.7
url_launcher_web-2.0.20
url_launcher_windows-3.0.8

**Comment by danagbemava-nc** [comment] 2023-10-11 07:29
Closing this as a duplicate of https://github.com/flutter/flutter/issues/66224. 

Kindly subscribe to the original issue for updates. 

Thank you

**Closed by danagbemava-nc** 2023-10-11 07:29 UTC
Labels: r: duplicate
