### ISSUE TITLE
[InteractiveViewer] Support trackpad gestures pinch zoom and two finger scroll  

### ISSUE THREAD

**Issue by SahajRana** [flutter/flutter#63084] opened 2020-08-06 13:38 UTC
Hi Flutter Team, 
I just used the Interactive Viewer for windows but it still is far from convenient when used for the actual use-case.

Problem:
The mouse-tap-and-drag for Pan Gesture. This behavior is mostly used to drag-select multiple items in most use-cases. 
We can disable the pan in it. But how can we enable it with scroll to move up and down?
As this behavior is also reserved for the zoom scale in the Interactive Viewer. 

If we can have something like this

> Pan: trackpad (two finger Horizontal-Vertical Scroll)/mouse (wheel scroll) 
> Zoom: trackpad(pinch zoom)/mouse(ctrl+wheel-scroll)

This is for Windows Flutter App.

**Comment by TahaTesser** [comment] 2020-08-06 14:29
Hi @SahajRana 
Desktop doesn't trackpad gestures yet https://github.com/flutter/flutter/issues/23604
Closing as duplicate of https://github.com/flutter/flutter/issues/23604

**Comment by SahajRana** [comment] 2020-08-06 14:42
@TahaTesser, Is there a way to stop the zoom when the mouse wheel is scrolled in InteractiveViewer?

As pinch to zoom works with trackpad/touchpad on windows in InteractiveViewer.

**Comment by TahaTesser** [comment] 2020-08-07 13:09
@SahajRana

**Comment by justinmc** [comment] 2020-08-07 15:39
Related (duplicate?): https://github.com/flutter/flutter/issues/63060

You're right that we should probably support alternate input configurations like this.  You can disable scaling altogether now ([scaleEnabled](https://master-api.flutter.dev/flutter/widgets/InteractiveViewer/scaleEnabled.html)), but I don't think there's an easy way to disable it only for the mouse wheel.

**Comment by rodydavis** [comment] 2020-09-12 00:14
Just ran into this! I was able to hack it by detecting when shift is pressed and scrolling vs panning

**Comment by marcosagni98** [comment] 2021-05-17 07:07
@rodydavis could you share code?

**Closed** 2022-04-13 02:47 UTC
Labels: severe: new feature, framework, f: material design, f: gestures, a: desktop, P5
