### ISSUE TITLE
Android SDK 34 - Is it necessary?

### ISSUE THREAD

**Issue by burekas7** [flutter/flutter#143665] opened 2024-02-18 10:56 UTC
### Steps to reproduce

When building the application I'm getting this warning:
```
Warning: The plugin url_launcher_android requires Android SDK version 34.
For more information about build configuration, see https://docs.flutter.dev/deployment/android#reviewing-the-gradle-build-configuration.
One or more plugins require a higher Android SDK version.
Fix this issue by adding the following to /Users/aditzoref/vscodeProjects/Deliveright/mobile_xp_driver/android/app/build.gradle:
android {
  compileSdkVersion 34
  ...
}
```

When I'm updating from 33 to 34 I'm getting other errors.
So my question is if it is necessary to update to 34?

Currently this are my sdk versions:
  compileSdkVersion 33
  targerSdkVersion 34

**Comment by stuartmorgan** [comment] 2024-02-18 12:34
Duplicate of https://github.com/flutter/flutter/issues/143605

**Closed by stuartmorgan** 2024-02-18 12:34 UTC
