### ISSUE TITLE
Keystore file not found for signing config 'release'.

### ISSUE THREAD

**Issue by dhillm920** [flutter/flutter#93212] opened 2021-11-07 12:57 UTC
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:validateSigningRelease'.
> Keystore file 'D:\bank_card_application-master\LaniaKey\lania.jks>' not found for signing config 'release'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 16s

<details>
<summary>key.properties</summary>

```properties
storePassword=XXXXXXXXXXX
keyPassword=XXXXXXXXXX
keyAlias=upload
storeFile=D:/bank_card_application-master/LaniaKey/lania.jks>
```
</details>

**Comment by danagbemava-nc** [comment] 2021-11-08 08:43
Hi @dhillm920, is the content of the `key.properties` info you posted above the actual content in your `key.properties` or was the '>' at the end a typo?

If it wasn't that may be the cause of the issue, also see this SO thread for more information on your error. 
https://stackoverflow.com/questions/53973333/flutter-picking-wrong-keystore-path-and-giving-error-key-jks-not-found

**Comment by maheshmnj** [comment] 2021-12-06 12:25
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by maheshmnj** 2021-12-06 12:25 UTC
