### ISSUE TITLE
[tool_crash] OSError: OS Error: Can't assign requested address, errno = 49

### ISSUE THREAD

**Issue by wangzhiming8916** [flutter/flutter#122986] opened 2023-03-20 02:04 UTC
## Command
```
flutter attach
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
OSError: OS Error: Can't assign requested address, errno = 49
```
#0      _NativeSocket.nativeSetRawOption (dart:io-patch/socket_patch.dart:1699:74)
#1      _NativeSocket.setRawOption (dart:io-patch/socket_patch.dart:1595:5)
#2      _RawDatagramSocket.setRawOption (dart:io-patch/socket_patch.dart:2527:56)
#3      MDnsClient.start (package:multicast_dns/multicast_dns.dart:141:16)
<asynchronous suspension>
#4      MDnsObservatoryDiscovery.query (package:flutter_tools/src/mdns_discovery.dart:63:7)
<asynchronous suspension>
#5      MDnsObservatoryDiscovery.getObservatoryUri (package:flutter_tools/src/mdns_discovery.dart:153:52)
<asynchronous suspension>
#6      AttachCommand._attachToDevice (package:flutter_tools/src/commands/attach.dart:277:11)
<asynchronous suspension>
#7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#8      AttachCommand.runCommand (package:flutter_tools/src/commands/attach.dart:224:5)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1161:27)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#11     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 2.10.5, on macOS 13.1 22C65 darwin-x64, locale zh-Hans-CN)
    • Flutter version 2.10.5 at /Users/wangzhiming26/flutter_2.10.5
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (11 个月前), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc2)
    • Android SDK at /Users/wangzhiming26/Library/Android/sdk
    • Platform android-32, build-tools 33.0.0-rc2
    • ANDROID_HOME = /Users/wangzhiming26/Library/Android/sdk
    • Java binary at: /Library/Java/JavaVirtualMachines/jdk-18.0.1.1.jdk/Contents/Home/Library/Java/JavaVirtualMachines/jdk-18.0.1.1.jdk/Contents/Home/bin/java
    ✗ Cannot execute /Library/Java/JavaVirtualMachines/jdk-18.0.1.1.jdk/Contents/Home/Library/Java/JavaVirtualMachines/jdk-18.0.1.1.jdk/Contents/Home/bin/java to determine the version

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] VS Code (version 1.76.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.60.0

[✓] Connected device (2 available)
    • iPhone 14 Pro Max (mobile) • 9C287E14-5926-418A-92DF-50E43138D2EA • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-2 (simulator)
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 92.0.4515.131

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.

```

## Flutter Application Metadata
**Type**: module
**Version**: 1.0.0+1
**Material**: true
**Android X**: true
**Module**: true
**Plugin**: false
**Android package**: com.jd.massmail_flutter
**iOS bundle identifier**: com.jd.massmailFlutter
**Creation channel**: unknown
**Creation framework version**: 8af6b2f038c1172e61d418869363a28dffec3cb4
### Plugins
connectivity-3.0.6
connectivity_for_web-0.4.0+1
connectivity_macos-0.2.1+2
device_info_plus-4.0.0
device_info_plus_linu

**Comment by danagbemava-nc** [comment] 2023-03-20 07:43
Closing this as a duplicate of https://github.com/flutter/flutter/issues/97489. 

Kindly subscribe to the issue linked above for updates. 

Thank you

**Closed by danagbemava-nc** 2023-03-20 07:43 UTC
Labels: in triage
