### ISSUE TITLE
Unable to open pdf link using url_launcher on Android emulator (api = 23, os = 6.0)

### ISSUE THREAD

**Issue by DK15** [flutter/flutter#27309] opened 2019-01-30 18:14 UTC
I am using `url_launcher` plugin to open **pdf link** in Android emulator's web browser, which crashes. 

![screen shot 2019-01-30 at 11 05 07 pm](https://user-images.githubusercontent.com/16548367/52002359-ce60b380-24e7-11e9-83a9-9d38f50c581b.png)

The same pdf link opens properly on iOS simulator.

![screen shot 2019-01-30 at 11 06 16 pm](https://user-images.githubusercontent.com/16548367/52002383-dddffc80-24e7-11e9-8cb4-3bae66d486e9.png)

Android emulator is on Marshmallow and api = 23.

Logcat:

```
java.lang.SecurityException: No permission to write to /storage/emulated/0/Download/QuickCarl_Terms_of_Service.pdf: Neither user 10020 nor current process has android.permission.WRITE_EXTERNAL_STORAGE.
        at android.app.ContextImpl.enforce(ContextImpl.java:1438)
        at android.app.ContextImpl.enforceCallingOrSelfPermission(ContextImpl.java:1470)
        at android.content.ContextWrapper.enforceCallingOrSelfPermission(ContextWrapper.java:675)
        at com.android.providers.downloads.DownloadProvider.checkFileUriDestination(DownloadProvider.java:724)
        at com.android.providers.downloads.DownloadProvider.insert(DownloadProvider.java:558)
        at android.content.ContentProvider$Transport.insert(ContentProvider.java:263)
        at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:163)
        at android.os.Binder.execTransact(Binder.java:453)
``` 
After googling around the issue, I came to know that for api level >= 23, we need to set `WRITE_EXTERNAL_STORAGE` in `androidManifest` which I did. But I would like to know what else need to be specified (ex : runtime permissions) in dart / flutter, in order to properly open the pdf link in the device's web browser.

**Flutter Doctor:**
```

 [✓] Flutter (Channel beta, v0.11.10, on Mac OS X 10.13.6 17G65, locale en-US)
    • Flutter version 0.11.10 at
      /Users/deeptibelsare/Documents/DarshanUdacity/Flutter/flutter
    • Framework revision c27c4a265e (9 weeks ago), 2018-11-26 17:07:24 -0500
    • Engine revision eebc6a5895
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[!] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/deeptibelsare/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1024-b01)
    ✗ Android license status unknown.

[!] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    ✗ Verify that all connected devices have been paired with this computer in
      Xcode.
      If all devices have been paired, libimobiledevice and ideviceinstaller may
      require updating.
      To update with Brew, run:
        brew update
        brew uninstall --ignore-dependencies libimobiledevice
        brew uninstall --ignore-dependencies usbmuxd
        brew install --HEAD usbmuxd
        brew unlink usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    • ios-deploy 2.0.0
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 26.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1024-b01)

[✓] Connected device (2 available)
    • Android SDK built for x86 • emulator-5554                        •
      android-x86 • Android 6.0 (API 23) (emulator)
    • iPhone 8                  • FB2DF839-2E8D-44E0-90B8-CCA0F138C932 • ios
      • iOS 11.4 (simulator)
```

**Comment by zoechi** [comment] 2019-01-30 18:21
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by BondarenkoStas** [comment] 2019-10-25 16:44
@DK15 did you solve the issue?

**Comment by TahaTesser** [comment] 2020-03-17 15:53
Issue is reproduced on

<details>
 <summary>flutter doctor -v</summary>

```
[√] Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [Version 10.0.19041.84], locale en-US)
    • Flutter version 1.12.13+hotfix.8 at C:\Code\flutter_stable
    • Framework revision 0b8abb4724 (4 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Code\SDK
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = C:\Code\SDK
    • Java binary at: C:\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Code\android-studio
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.43.0)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.8.1

[√] Connected device (1 available)
    • SM M305F • 32003c30dc19668f • android-arm64 • Android 10 (API 29)

• No issues found!
```

</details>


<details>
 <summary>Code Sample</summary>

```
import 'package:flutter/material.dart';
import 'package:url_launcher/url_launcher.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      home: Home(),
    );
  }
}

class Home extends StatefulWidget {
  @override
  _HomeState createState() => _HomeState();
}

class _HomeState extends State<Home> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: RaisedButton(
          onPressed: _launchURL,
          child: Text('Show Flutter homepage'),
        ),
      ),
    );
  }

  _launchURL() async {
    const url =
        'http://93.174.95.29/main/29000/f93497c097df03bce57ac52bdc191146/Arthur%20Israel%20Vogel%20-%20Vogel%27s%20Textbook%20Of%20Macro%20And%20SemiMicro%20Qualitative%20Inorganic%20Analysis-Longman%20%281979%29.pdf';
    if (await canLaunch(url)) {
      await launch(url);
    } else {
      throw 'Could not launch $url';
    }
  }
}

```

</details>

![Screenshot_1584460392](https://user-images.githubusercontent.com/48603081/76874700-922c1600-6895-11ea-96ef-4a463555ca07.png)

**Comment by chakrihacker** [comment] 2020-09-03 10:11
Any updates on this?

**Comment by Sempakonka** [comment] 2020-10-07 11:12
Hi @DK15,

It seems that in API 23 the browser does not automatically get access to the device's storage. I was able to fix your issue by giving the browser access to the phone's storage. To do this go to Settings -> Apps -> Browser -> Permissions and add the storage to the permissions.

**Comment by amirh** [comment] 2020-10-21 04:15
Closing per @Sempakonka's comment.

**Closed by amirh** 2020-10-21 04:15 UTC
Labels: p: first party, p: url_launcher, plugin, severe: crash

**Comment by gnprice** [comment] 2023-08-17 04:39
Cross-linking to a later issue with related symptoms:
* #105205 

(The symptoms are different and these are likely separate issues, but it looks like people are sometimes finding this one when looking for that other one.)
