### ISSUE TITLE
Support "smart selection" in Android 0

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#11714] opened 2017-08-21 23:36 UTC
https://developer.android.com/reference/android/view/textclassifier/TextClassifier.html
appears to be the API.

**Comment by zoechi** [comment] 2018-11-11 12:13
Is it ok to close this as dup of #22619 which seems to have a bit more information?

**Comment by zoechi** [comment] 2018-12-11 15:55
Duplicate of #22619

**Closed by zoechi** 2018-12-11 15:55 UTC
Labels: a: text input, framework, severe: new feature, waiting for customer response, ▣ platform-android
