### ISSUE TITLE
Do not restore status bar color on iphone

### ISSUE THREAD

**Issue by ManoyloK** [flutter/flutter#43338] opened 2019-10-23 12:44 UTC
## Steps to Reproduce
1. Using url_launcher launch launch(httpUrl, forceSafariVC: true, statusBarBrightness:Brightness.light,) where statusBarBrightness!=default app statusBarBrightness.
2. Close webView.
3. statusBarBrightness(light) set for all application

**Target Platform: IOS**
**Target OS version: 12.1.4**
**Devices: Iphone X**
Do not reproduces on iphone 6 with  ios 12.1

**Comment by iapicca** [comment] 2019-10-23 13:01
Hi @ManoyloK 
can you please provide your `flutter doctor -v`?
Thank you

**Comment by ManoyloK** [comment] 2019-10-23 13:04
> Hi @ManoyloK
> can you please provide your `flutter doctor -v`?
> Thank you

[✓] Flutter (Channel stable, v1.9.1+hotfix.5, on Mac OS X 10.15 19A602, locale en-UA)
    • Flutter version 1.9.1+hotfix.5 at /Users/k.manoilo/development/flutter
    • Framework revision 1aedbb1835 (6 days ago), 2019-10-17 08:37:27 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/k.manoilo/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    • CocoaPods version 1.8.3

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 40.2.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Community Edition (version 2019.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 39.0.5
    • Dart plugin version 192.6603.23

**Comment by darshankawar** [comment] 2020-06-26 11:03
Hi @ManoyloK, can you please confirm if you are still experiencing this issue on latest versions of Flutter and `webview_flutter` plugin ?

**Comment by VladyslavBondarenko** [comment] 2020-07-22 15:40
I tried with master `1.21.0-2.0.pre.94`, `url_launcher: ^5.5.0`, running on iPhone 7 iOS 13.5.
I have dark mode set, so status bar color is white. With `statusBarBrightness:Brightness.light` status bar color of opened by url_launcher safari is black and status bar color of flutter app after closing safari is black.

@ManoyloK 
closing since based on https://github.com/flutter/plugins/blob/master/packages/url_launcher/url_launcher/lib/url_launcher.dart#L51 

> /// [statusBarBrightness] Sets the status bar brightness of the application
/// after opening a link on iOS. Does nothing if no value is passed. This does
/// not handle resetting the previous status bar style.

this is intended behavior

**Closed by VladyslavBondarenko** 2020-07-22 15:40 UTC
Labels: a: images, e: device-specific, framework, p: first party, p: webview, platform-ios, plugin, waiting for customer response
