### ISSUE TITLE
[web] Skia engine fails when using gradient

### ISSUE THREAD

**Issue by iampopal** [flutter/flutter#50327] opened 2020-02-07 09:55 UTC
Repeatedly seeing the following errors
```
Assertion failed: org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/surface/scene_builder.dart:267:12
retainedSurface.isActive || retainedSurface.isReleased
is not true
```
flutter doctor: 
`[√] Flutter (Channel beta, v1.14.6, on Microsoft Windows [Version 10.0.15063], locale
    en-US)

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses
[√] Chrome - develop for the web
[√] Android Studio (version 3.5)
[!] IntelliJ IDEA Ultimate Edition (version 2017.1)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] VS Code (version 1.41.1)
[√] Connected device (3 available)`

**Comment by VladyslavBondarenko** [comment] 2020-02-07 10:55
Hi @iampopal 
Could you provide a code sample to reproduce?

Similar to https://github.com/flutter/flutter/issues/50010

**Comment by VladyslavBondarenko** [comment] 2020-02-07 11:20
Hi @iampopal 
Could you provide a minimal code sample when this assertion is failed?

Related to https://github.com/flutter/flutter/issues/50010

**Comment by thasmin** [comment] 2020-02-07 13:17
This issue occured on my project as well. Downgrading to v1.14.5 fixed the problem. This project is supposed to be delivered soon so I did not get a chance to debug or provide a minimal sample. This code does use gradients, however.

Here is my error log:

```-------- Exception caught by scheduler library ---------------------------------
The following assertion was thrown during a scheduler callback:
Assertion failed: org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/dom_canvas.dart:74:12
paint.shader == null
is not true

When the exception was thrown, this was the stack
throw_ (package:build_web_compilers/src/dev_compiler/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart:196:49)
assertFailed (package:build_web_compilers/src/dev_compiler/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart:26:3)
[_drawRect] (package:build_web_compilers/src/dev_compiler/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/dom_canvas.dart:74:28)
drawRRect (package:build_web_compilers/src/dev_compiler/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/dom_canvas.dart:136:28)
apply (package:build_web_compilers/src/dev_compiler/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/surface/recording_canvas.dart:865:11)
...
--------------------------------------------------------------------------------

-------- Exception caught by scheduler library ---------------------------------
Assertion failed: org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/surface/scene_builder.dart:267:12
retainedSurface.isActive || retainedSurface.isReleased
is not true
--------------------------------------------------------------------------------

... last error repeated
```

**Comment by Ahmadre** [comment] 2020-02-12 15:25
I got the same error: https://github.com/flutter/flutter/issues/50417

**Comment by yjbanov** [comment] 2020-02-13 23:20
This is a duplicate of https://github.com/flutter/flutter/issues/50417.

**Closed by yjbanov** 2020-02-13 23:20 UTC
Labels: e: web_html, engine, severe: crash, ☸ platform-web
