### ISSUE TITLE
Calling PlatformView.NotifyDestroyed still leaks IOSurfaces

### ISSUE THREAD

**Issue by xster** [flutter/flutter#38736] opened 2019-08-17 07:07 UTC
Traces 
https://drive.google.com/file/d/1gFj_fxjHZ_rmvhC7UNGklHScb7ilTBbE/view?usp=sharing
https://drive.google.com/drive/folders/1ZQpyw8bZw1pdCiKduZRil8_Y3Bcx-myt?usp=sharing

Repro
Clone https://github.com/xster/flutter-test/tree/master/t132_performance_test_ios and https://github.com/xster/flutter-test/tree/master/t132_performance_test_flutter. 

flutter build ios --debug --no-codesign or wtv in t132_performance_test_flutter
pod install in t132_performance_test_ios run in instruments. 

Press 'load engine', 'show vc' and 'pop'.
PlatformView.NotifyDestroyed is called through FlutterViewController.viewDidDisappear. But looking at the VM: IOSurface allocation, they're still not freed.

1
<img width="580" alt="Screen Shot 2019-08-17 at 12 06 33 AM" src="https://user-images.githubusercontent.com/156888/63207910-e57d8200-c082-11e9-8063-ba5eecaaa38d.png">

2
<img width="580" alt="Screen Shot 2019-08-17 at 12 06 20 AM" src="https://user-images.githubusercontent.com/156888/63207911-e7dfdc00-c082-11e9-9de4-3434114a2bd8.png">

3
<img width="585" alt="Screen Shot 2019-08-17 at 12 06 11 AM" src="https://user-images.githubusercontent.com/156888/63207912-ea423600-c082-11e9-9428-1535f3c95085.png">

@chinmaygarde can you take a look?

**Comment by xster** [comment] 2019-08-22 02:17
@chinmaygarde says run it again and look for EAGLContext instances on the IO thread and see the retention tree.

**Comment by xster** [comment] 2019-08-24 00:51
![Screen Shot 2019-08-23 at 5 50 33 PM](https://user-images.githubusercontent.com/156888/63630343-8eba0000-c5ce-11e9-8dfe-f60df14bf0a9.png)
![Screen Shot 2019-08-23 at 5 43 16 PM](https://user-images.githubusercontent.com/156888/63630344-8eba0000-c5ce-11e9-8ce8-8f8d4020fb06.png)

**Comment by xster** [comment] 2019-08-24 00:58
Maybe we need to hook PlatformViewIos to override NotifyDestroyed too to clean up what's kept from https://github.com/flutter/engine/pull/8387?

**Comment by xster** [comment] 2019-08-24 01:02
cc @dnfield

**Comment by dnfield** [comment] 2019-08-24 03:44
We have to keep the IO resource context around as long as the engine is around. It looks like one of those is the IO context.

**Comment by dnfield** [comment] 2019-08-30 16:51
We talked offline about this. The `IOSGLContext` class is owned by the `PlatformViewIOS`, and right now manages both the resource context (IO thread images and fonts) and the on screen context.  The resource context is the primary context in the sharegroup, and has to be so that textures Dart needs for Images/Fonts don't get lost - it has to survive when the FlutterView is created or destroyed.

What we want to do is make the FlutterView own the on screen GL context, so that it can just dispose of it when it's gone and create a new one when it's back.

/cc @gw280 who is interested in this

**Comment by gw280** [comment] 2019-08-30 21:09
So I spoke with @dnfield about this and I'm not a huge fan of moving the `EAGLContext` ownership from the `IOSGLContext` into the `FlutterView` itself, as there are operations in `IOSGLContext` that will still need the onscreen `EAGLContext` to function, so we'd still need to keep a weak ref to the onscreen context in `IOSGLContext`.

Talking about this further, we think it makes more sense to move to a model where `IOSGLContext` manages a single `EAGLContext`, and we have two; one for the resource context (managed by `PlatformViewIOS`) and one for the onscreen context (managed by `FlutterView`).

I'll be working on this and will see how involved it'll be. Thanks @dnfield for the advice/suggestion in getting me started.

**Comment by xster** [comment] 2019-08-30 21:40
> we think it makes more sense to move to a model where IOSGLContext manages a single EAGLContext, and we have two; one for the resource context (managed by PlatformViewIOS) and one for the onscreen context (managed by FlutterView)
 
That sounds ok. Didn't look in detail but how do you reconcile "as there are operations in IOSGLContext that will still need the onscreen EAGLContext to function"? Is the current 1 IOSGLContext injected into places that needs to operate against both EAGLContexts?

**Comment by dnfield** [comment] 2019-08-30 22:31
One would be given to the other as the sharegroup owner (the resource context).  So the platform view would own the resource context's IOSGLContext, and the flutter view would own the on screen context's IOSGLContext.

**Comment by xster** [comment] 2019-08-31 00:12
So the PlatformViewIOS still makes a IOGLContext on construct (but it only has one EAGLContext) and when it's [FlutterView createSurface:]ing, it uses a factory on the first IOGLContext to create another one with the same sharegroup?

**Comment by gw280** [comment] 2019-09-03 18:19
The way I've done it for now is to add a getter for the sharegroup and in `createSurface` pull the sharegroup from the resource context and use it for the onscreen context. I have no real opinion on whether a factory or a getter would be more desirable.

https://github.com/flutter/engine/pull/11798

**Comment by gw280** [comment] 2019-09-03 18:20
> That sounds ok. Didn't look in detail but how do you reconcile "as there are operations in IOSGLContext that will still need the onscreen EAGLContext to function"? Is the current 1 IOSGLContext injected into places that needs to operate against both EAGLContexts?

I've plumbed through both contexts where they are needed.

**Comment by xster** [comment] 2019-09-17 00:07
Mostly done now in https://github.com/flutter/engine/pull/12277. Remaining work is to make sure that it isn't recreated when the app comes back into foreground but with no FlutterViewController visible.

**Comment by gw280** [comment] 2019-09-19 17:39
Created a separate issue so closing this one.

**Comment by xster** [comment] 2019-10-25 19:32
@gw280 we were saying this one got reverted right? Should we reopen it?

**Comment by gw280** [comment] 2019-10-25 19:38
Yes

**Comment by gw280** [comment] 2019-10-28 17:14
Original PR: https://github.com/flutter/engine/pull/12277

**Comment by gaaclarke** [comment] 2019-10-28 18:30
This only leaks if you've allowed your FlutterEngine to execute headlessly: https://github.com/gaaclarke/engine/blob/ddf98c0cba0b1c95e69f27cf4c9783956c4a91f4/shell/platform/darwin/ios/framework/Source/FlutterEngine.mm#L189

If you specify NO for allowHeadlessExecution the context is cleaned up correctly.

**Comment by dnfield** [comment] 2019-10-28 20:07
Discussed this offline - that is because in headless mode, the PlatformViewIOS will get released, which will release the GL context.

However, this bug is really meant for Add-to-app cases where you add and remove a ViewController and you want to make sure you release all graphics resources between.

**Comment by xster** [comment] 2019-10-30 20:07
@gaaclarke we can close this now right?

**Comment by gaaclarke** [comment] 2019-10-30 20:22
@xster yup

**Comment by xster** [comment] 2019-11-12 01:17
This seems to still happen for me on head. 

`flutter build ios-framework` in https://github.com/xster/flutter-test/tree/master/t142_build_framework, then run the sibling https://github.com/xster/flutter-test/tree/master/t142_import_framework. 

Click the launch flutter button and swipe the flutter page away. 

![Screen Shot 2019-11-11 at 5 17 02 PM](https://user-images.githubusercontent.com/156888/68633535-19601c00-04a7-11ea-9aca-4391ac9bfac6.png)

**Comment by gaaclarke** [comment] 2019-11-13 18:29
@xster From your previous screenshots it seems like we have leaked a flutter::Shell.  Does that match your read as well?  The previous captures have a flutter::Shell that is owned by an flutter::Engine.

**Comment by gaaclarke** [comment] 2019-11-13 19:03
I've been able to verify the leak on a5680f9388ebcef6012c446c5226a79a5ab8000c.  I stepped through the code that the PR fixed in issue on #13396, it is no longer behaving as it was intended.

Namely this branch doesn't execute because platform_view is null: https://github.com/flutter/engine/blob/a5680f9388ebcef6012c446c5226a79a5ab8000c/shell/platform/darwin/ios/framework/Source/FlutterEngine.mm#L208

I'm unable to easily bisect since there are required framework changes between the commits.

**Comment by gaaclarke** [comment] 2019-11-13 20:37
I've verified that the bug shows up on master(a5680f9388ebcef6012c446c5226a79a5ab8000c) and the fixing PR (f8a7ce56555f090fc9d824b657f4bb3ac6e3267a).  I was checking that ios_surface was getting deleted and it is, unfortunately that isn't enough to clear the context.

I've also verified that you leak at most 1 context at a time since the old one will be dealloc'd when a new view is attached to the engine.

**Comment by gaaclarke** [comment] 2019-11-13 21:05
This is a capture before we've presented a ViewController.  Notice there are 2 contexts.
<img width="1480" alt="Screen Shot 2019-11-13 at 12 56 48 PM" src="https://user-images.githubusercontent.com/30870216/68803681-12efb280-0615-11ea-8614-ab32033e16fd.png">

If you push and pop multiple view controllers you'll notice that the 2 live contexts are always the same.  The way it is implemented is that there are 2 omnipresent contexts.  Therefore this isn't a leak, but it is how the system is designed to work.

**Closed** 2019-11-13 21:05 UTC
Labels: a: existing-apps, engine, severe: performance, ⌺‬ platform-ios
