### ISSUE TITLE
allow shared_preferences to use existing file

### ISSUE THREAD

**Issue by tapeo** [flutter/flutter#35862] opened 2019-07-10 08:43 UTC
Current Android implementation of shared_preferences create a new file (called FlutterSharedPreferences.xml) instead reusing already existing preferences file.

This can't let my app to migrate from existing app using the keys stored in the old preferences file. The same for iOS. With Android I can retrieve the old file and convert it to XML and parse it to recover the keys but with iOS there aren't ways.

Is there a workaround to retrieve the preferences from old file for both platforms?

**Comment by janmoppel** [comment] 2019-09-30 08:37
Hello @tapeo !

Does the problem still persist in the latest plugin version?

Thank you.

**Comment by bipinvaylu** [comment] 2019-10-11 07:00
Hey Guys, I am also stuck at this point. For Android, We can do but iOS we can't able to do that. Any update on this so far?

**Comment by imajercsik** [comment] 2020-05-05 20:44
Hi @bipinvaylu ,

I still encounter this issue, it seems it's not yet solved. What it is your approach for Android? 

Thanks for helping

**Comment by bipinvaylu** [comment] 2020-05-06 04:17
Hi @imajercsik I have used file provider plugin and find out the old file path and then read its current state and write it into a new file and then deleted the old file. I think i have used Path Provider package for that: https://pub.dev/packages/path_provider

**Comment by imajercsik** [comment] 2020-05-06 08:28
Thank you @bipinvaylu !

**Comment by CaptainWeb1** [comment] 2020-12-02 15:07
> Hi @imajercsik I have used file provider plugin and find out the old file path and then read its current state and write it into a new file and then deleted the old file. I think i have used Path Provider package for that: https://pub.dev/packages/path_provider

Hey thank you for this idea. Which one of the path provider is Shared Preferences Flutter path ? I don't find it in app directory (Device file explorer in Android Studio). I know that in native android app it's located in data > data > package name > shared_prefs

**Comment by CaptainWeb1** [comment] 2020-12-02 15:10
> Hi @imajercsik I have used file provider plugin and find out the old file path and then read its current state and write it into a new file and then deleted the old file. I think i have used Path Provider package for that: https://pub.dev/packages/path_provider

Hey thank you for this idea. Which one of the directory given by the path provider package is Shared Preferences path in Flutter ? I don't find it in app directory (Device file explorer in Android Studio). I know that in native android app it's located in data > data > package name > shared_prefs

**Comment by aleripe** [comment] 2021-03-16 21:23
Any news on this issue?

**Comment by nirbar89** [comment] 2021-04-13 21:35
> Hi @imajercsik I have used file provider plugin and find out the old file path and then read its current state and write it into a new file and then deleted the old file. I think i have used Path Provider package for that: https://pub.dev/packages/path_provider

Hey @bipinvaylu can you share your approach? example code will be very appreciated.

**Comment by bipinvaylu** [comment] 2021-04-16 05:02
> > Hi @imajercsik I have used file provider plugin and find out the old file path and then read its current state and write it into a new file and then deleted the old file. I think i have used Path Provider package for that: https://pub.dev/packages/path_provider
> 
> Hey @bipinvaylu can you share your approach? example code will be very appreciated.

Hey @nirbar89 I am able to handle this for Android app only using Path Provider package. But for iOS, There is issue related to use their internal files.

Sample Code:
```
Future<FileSystemEntity> getAndroidOldPrefsFile() async {
  try {
    final appDir = await getApplicationDocumentsDirectory();
    final directory = appDir.parent;
    debugPrint(
        "FileStorageUtil - findFile - directory: $directory, path: ${directory.path}");
    List<FileSystemEntity> files = directory.listSync(recursive: true);
    return files.firstWhere(
      (file) => file.path.endsWith("app_prefs.xml"),
      orElse: () => null,
    );
  } catch (e, s) {
    debugPrint("FileStorageUtil - findFile failed. Error: $s");
  }
  return null;
}

Future<Map<dynamic, dynamic>> _performMigrationForAndroid() async {
  debugPrint("MigrationUtil - performMigrationTo104 called");
  try {
    final File file = await getAndroidOldPrefsFile();
    if (file != null) {
      final String xmlString = file.readAsStringSync(encoding: utf8);
      debugPrint(
          "MigrationUtil - _performMigrationForAndroid - xmlString: $xmlString");
      final Xml2Json transformer = Xml2Json();
      transformer.parse(xmlString);
      final gdataJson = transformer.toGData();
      debugPrint(
          "MigrationUtil - _performMigrationForAndroid - gdataJson: $gdataJson");
      Map<dynamic, dynamic> gDataMap = jsonDecode(gdataJson);
      debugPrint(
          "MigrationUtil - _performMigrationForAndroid - map: $gDataMap");
      Map<dynamic, dynamic> map = gDataMap["map"];
      debugPrint(
          "MigrationUtil - _performMigrationForAndroid - map: $map");

      // Boolean value
      Map<dynamic, dynamic> dataMap = Map();
      dataMap.addAll(_getProperMap(map["boolean"], "name", "value"));
      debugPrint(
          "MigrationUtil - _performMigrationForAndroid - dataMap-boolean: $dataMap");

      // String value
      dataMap.addAll(_getProperMap(map["string"], "name", "\$t"));
      debugPrint(
          "MigrationUtil - _performMigrationForAndroid - dataMap-string: $dataMap");

      // Int value
      dataMap.addAll(_getProperMap(map["int"], "name", "value"));
      debugPrint(
          "MigrationUtil - _performMigrationForAndroid - dataMap-int: $dataMap");
      // Delete file once app ran on new version
      file.deleteSync();
      return dataMap;
    }
  } catch (e, s) {
    debugPrint(
        "MigrationUtil - _performMigrationForAndroid - stackTrace: $s");
  }
  debugPrint("MigrationUtil - _performMigrationForAndroid completed");
  return null;
}
``` 

This is simple approach, Find out old prefs file from app storage, read out its and write down it into newly generated prefs file and then finally delete old pref file.

**Comment by nirbar89** [comment] 2021-04-19 12:35
> > > Hi @imajercsik I have used file provider plugin and find out the old file path and then read its current state and write it into a new file and then deleted the old file. I think i have used Path Provider package for that: https://pub.dev/packages/path_provider
> > 
> > 
> > Hey @bipinvaylu can you share your approach? example code will be very appreciated.
> 
> Hey @nirbar89 I am able to handle this for Android app only using Path Provider package. But for iOS, There is issue related to use their internal files.
> 
> Sample Code:
> 
> ```
> Future<FileSystemEntity> getAndroidOldPrefsFile() async {
>   try {
>     final appDir = await getApplicationDocumentsDirectory();
>     final directory = appDir.parent;
>     debugPrint(
>         "FileStorageUtil - findFile - directory: $directory, path: ${directory.path}");
>     List<FileSystemEntity> files = directory.listSync(recursive: true);
>     return files.firstWhere(
>       (file) => file.path.endsWith("app_prefs.xml"),
>       orElse: () => null,
>     );
>   } catch (e, s) {
>     debugPrint("FileStorageUtil - findFile failed. Error: $s");
>   }
>   return null;
> }
> 
> Future<Map<dynamic, dynamic>> _performMigrationForAndroid() async {
>   debugPrint("MigrationUtil - performMigrationTo104 called");
>   try {
>     final File file = await getAndroidOldPrefsFile();
>     if (file != null) {
>       final String xmlString = file.readAsStringSync(encoding: utf8);
>       debugPrint(
>           "MigrationUtil - _performMigrationForAndroid - xmlString: $xmlString");
>       final Xml2Json transformer = Xml2Json();
>       transformer.parse(xmlString);
>       final gdataJson = transformer.toGData();
>       debugPrint(
>           "MigrationUtil - _performMigrationForAndroid - gdataJson: $gdataJson");
>       Map<dynamic, dynamic> gDataMap = jsonDecode(gdataJson);
>       debugPrint(
>           "MigrationUtil - _performMigrationForAndroid - map: $gDataMap");
>       Map<dynamic, dynamic> map = gDataMap["map"];
>       debugPrint(
>           "MigrationUtil - _performMigrationForAndroid - map: $map");
> 
>       // Boolean value
>       Map<dynamic, dynamic> dataMap = Map();
>       dataMap.addAll(_getProperMap(map["boolean"], "name", "value"));
>       debugPrint(
>           "MigrationUtil - _performMigrationForAndroid - dataMap-boolean: $dataMap");
> 
>       // String value
>       dataMap.addAll(_getProperMap(map["string"], "name", "\$t"));
>       debugPrint(
>           "MigrationUtil - _performMigrationForAndroid - dataMap-string: $dataMap");
> 
>       // Int value
>       dataMap.addAll(_getProperMap(map["int"], "name", "value"));
>       debugPrint(
>           "MigrationUtil - _performMigrationForAndroid - dataMap-int: $dataMap");
>       // Delete file once app ran on new version
>       file.deleteSync();
>       return dataMap;
>     }
>   } catch (e, s) {
>     debugPrint(
>         "MigrationUtil - _performMigrationForAndroid - stackTrace: $s");
>   }
>   debugPrint("MigrationUtil - _performMigrationForAndroid completed");
>   return null;
> }
> ```
> 
> This is simple approach, Find out old prefs file from app storage, read out its and write down it into newly generated prefs file and then finally delete old pref file.

Thank you very much! you help me a lot!

can you please share also the _getProperMap method?

**Comment by bipinvaylu** [comment] 2021-05-13 03:18
Hi @nirbar89 Sorry for bit late reply, I got stuck on some of personal stuff. Here you go with `_getProperMap` method.

```
Map<String, dynamic> _getProperMap(
    dynamic item, String keyConstant, String valueConstant) {
  if (item is Map) {
    String key = item[keyConstant];
    dynamic value = item[valueConstant];
    debugPrint("MigrationUtil - _getProperMapEntry - key: $key, value: $value");
    Map<String, dynamic> map = Map<String, dynamic>();
    map[key] = value;
    return map;
  } else if (item is List) {
    Map<String, dynamic> itemMap = Map<String, dynamic>();
    item.forEach((each) =>
        itemMap.addAll(_getProperMap(each, keyConstant, valueConstant)));
    return itemMap;
  } else {
    return Map<String, dynamic>();
  }
}
```

**Comment by stuartmorgan** [comment] 2023-04-30 16:46
Closing as a duplicate of https://github.com/flutter/flutter/issues/14337

**Closed by stuartmorgan** 2023-04-30 16:46 UTC
Labels: new feature, plugin, customer: crowd, p: shared_preferences, proposal, P4
