### ISSUE TITLE
Bad UTF-8 encoding (U+FFFD; REPLACEMENT CHARACTER) found while decoding string

### ISSUE THREAD

**Issue by Dohun-choi** [flutter/flutter#147509] opened 2024-04-29 08:38 UTC
### Steps to reproduce

I send a HTTP request to https://cataas.com/cat and i print request and response by using dio package.

![image](https://github.com/flutter/flutter/assets/139415969/295f8f21-1128-4360-844a-d18cd6ea1bb4)
[239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 0, 67, 0, 6, 4, 5, 6, 5, 4, 6, 6, 5, 6, 7, 7, 6, 8, 10] 

i really don't no about this issue...

### Expected results

just print...

### Actual results

![image](https://github.com/flutter/flutter/assets/139415969/c09cbd6a-1eef-4836-a50e-8b1d89307898)

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:dio/dio.dart';
import 'package:flutter/material.dart';
import 'package:flutter_dotenv/flutter_dotenv.dart';

final api = Dio(
  BaseOptions(
    baseUrl: dotenv.get('BASE_URL'),
  ),
);

final interceptors = InterceptorsWrapper(
  onRequest: (RequestOptions options, RequestInterceptorHandler handler) {
    debugPrint('REQUEST[${options.method}] => PATH: ${options.path}');
    debugPrint("${options.data}");
    return handler.next(options);
  },
  onResponse: (Response response, ResponseInterceptorHandler handler) {
    debugPrint(
        'RESPONSE[${response.statusCode}] => PATH: ${response.requestOptions.path}');
    debugPrint("${response.data}");
    return handler.next(response);
  },
  onError: (DioException error, ErrorInterceptorHandler handler) {
    debugPrint(
        'ERROR[${error.response?.statusCode}] => PATH: ${error.requestOptions.path}');
    return handler.next(error);
  },
);
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
Bad UTF-8 encoding (U+FFFD; REPLACEMENT CHARACTER) found while decoding string: ����C
. The Flutter team would greatly appreciate if you could file a bug explaining exactly what you were doing when this   
happened:
https://github.com/flutter/flutter/issues/new/choose
The source bytes were:
[239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 0, 67, 0, 6, 4, 5, 6, 5, 4, 6, 6, 5, 6, 7, 7, 6, 8, 10]   ```

</details>


### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.19.6, on Microsoft Windows [Version 10.0.19045.4291], locale ko-KR)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.9.5)
[√] Android Studio (version 2023.2)
[√] IntelliJ IDEA Community Edition (version 2023.3)
[√] VS Code (version 1.85.1)
[√] Connected device (3 available)
[√] Network resources

• No issues found!
```

</details>

**Comment by Dohun-choi** [comment] 2024-04-29 09:03
> ### Steps to reproduce
> I send a HTTP request to https://cataas.com/cat and i print request and response by using dio package.
> 
> ![image](https://private-user-images.githubusercontent.com/139415969/326373236-295f8f21-1128-4360-844a-d18cd6ea1bb4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzODE2MTAsIm5iZiI6MTcxNDM4MTMxMCwicGF0aCI6Ii8xMzk0MTU5NjkvMzI2MzczMjM2LTI5NWY4ZjIxLTExMjgtNDM2MC04NDRhLWQxOGNkNmVhMWJiNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyOVQwOTAxNTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iOThhNzY0MDAxODM0OWVhOWZlODViMzFlMThjMzU2NDcyY2IzMzBjZWI4MWNmOWQyNzc2YTZjNWFhNDVjYjFhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.4I2xcAG_XS_Ic666jX54scCmwOah8WtdOo47xSgPA2Y) [239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 0, 67, 0, 6, 4, 5, 6, 5, 4, 6, 6, 5, 6, 7, 7, 6, 8, 10]
> 
> i really don't no about this issue...
> 
> ### Expected results
> just print...
> 
> ### Actual results
> ![image](https://private-user-images.githubusercontent.com/139415969/326373935-c09cbd6a-1eef-4836-a50e-8b1d89307898.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzODE2MTAsIm5iZiI6MTcxNDM4MTMxMCwicGF0aCI6Ii8xMzk0MTU5NjkvMzI2MzczOTM1LWMwOWNiZDZhLTFlZWYtNDgzNi1hNTBlLThiMWQ4OTMwNzg5OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyOVQwOTAxNTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMTQ0MGYxMzViZWZjM2UzZTcxYThmMDhkMDJlNDI5ZDQ1ZGVlNmE5ZGU0Y2Y2N2YwZTA4OTkxNWFlMTZiYzBkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.PrwLzvyex6frgfZFztqEAeuVRTMP0FPpjvY43Ke8DeQ)
> 
> ### Code sample
> Code sample
> ```dart
> import 'package:dio/dio.dart';
> import 'package:flutter/material.dart';
> import 'package:flutter_dotenv/flutter_dotenv.dart';
> 
> final api = Dio(
>   BaseOptions(
>     baseUrl: dotenv.get('BASE_URL'),
>   ),
> );
> 
> final interceptors = InterceptorsWrapper(
>   onRequest: (RequestOptions options, RequestInterceptorHandler handler) {
>     debugPrint('REQUEST[${options.method}] => PATH: ${options.path}');
>     debugPrint("${options.data}");
>     return handler.next(options);
>   },
>   onResponse: (Response response, ResponseInterceptorHandler handler) {
>     debugPrint(
>         'RESPONSE[${response.statusCode}] => PATH: ${response.requestOptions.path}');
>     debugPrint("${response.data}");
>     return handler.next(response);
>   },
>   onError: (DioException error, ErrorInterceptorHandler handler) {
>     debugPrint(
>         'ERROR[${error.response?.statusCode}] => PATH: ${error.requestOptions.path}');
>     return handler.next(error);
>   },
> );
> ```
> 
> ### Screenshots or Video
> Screenshots / Video demonstration
> [Upload media here]
> 
> ### Logs
> Logs
> ```
> Bad UTF-8 encoding (U+FFFD; REPLACEMENT CHARACTER) found while decoding string: ����C
> . The Flutter team would greatly appreciate if you could file a bug explaining exactly what you were doing when this   
> happened:
> https://github.com/flutter/flutter/issues/new/choose
> The source bytes were:
> [239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 0, 67, 0, 6, 4, 5, 6, 5, 4, 6, 6, 5, 6, 7, 7, 6, 8, 10]   ```
> 
> </details>
> 
> 
> ### Flutter Doctor output
> 
> <details open><summary>Doctor output</summary>
> 
> ```console
> $ flutter doctor
> Doctor summary (to see all details, run flutter doctor -v):
> [√] Flutter (Channel stable, 3.19.6, on Microsoft Windows [Version 10.0.19045.4291], locale ko-KR)
> [√] Windows Version (Installed version of Windows is version 10 or higher)
> [√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
> [√] Chrome - develop for the web
> [√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.9.5)
> [√] Android Studio (version 2023.2)
> [√] IntelliJ IDEA Community Edition (version 2023.3)
> [√] VS Code (version 1.85.1)
> [√] Connected device (3 available)
> [√] Network resources
> 
> • No issues found!
> ```

I think i found reason..
${response.data} was image file and it's length of toString() was too long to print...?

**Comment by danagbemava-nc** [comment] 2024-04-29 12:26
Closing this as a duplicate of https://github.com/flutter/flutter/issues/137025

**Closed by danagbemava-nc** 2024-04-29 12:26 UTC
Labels: in triage
