### ISSUE TITLE
DropdowMenu Class Focus/Highlight issue

### ISSUE THREAD

**Issue by gitabhisingh** [flutter/flutter#136171] opened 2023-10-09 00:26 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I actually foudn this issue when I was working with PaginatedDataTable, where it has a rowsPerPage dropdown in the pagination footer. 

To easily reproduce

1. Use DropdownMenu class using a simple 1st example provided in DropdownMenuButton here: https://api.flutter.dev/flutter/material/DropdownButton-class.html
2. Click on the menu, and select any menu item

### Expected results

After selecting, the focus on Menu should go away

### Actual results

The focus still remains on the menu even though the item is already selected

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

/// Flutter code sample for [DropdownButton].

const List<String> list = <String>['One', 'Two', 'Three', 'Four'];

void main() => runApp(const DropdownButtonApp());

class DropdownButtonApp extends StatelessWidget {
  const DropdownButtonApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(title: const Text('DropdownButton Sample')),
        body: const Center(
          child: DropdownButtonExample(),
        ),
      ),
    );
  }
}

class DropdownButtonExample extends StatefulWidget {
  const DropdownButtonExample({super.key});

  @override
  State<DropdownButtonExample> createState() => _DropdownButtonExampleState();
}

class _DropdownButtonExampleState extends State<DropdownButtonExample> {
  String dropdownValue = list.first;

  @override
  Widget build(BuildContext context) {
    return DropdownButton<String>(
      value: dropdownValue,
      icon: const Icon(Icons.arrow_downward),
      elevation: 16,
      style: const TextStyle(color: Colors.deepPurple),
      underline: Container(
        height: 2,
        color: Colors.deepPurpleAccent,
      ),
      onChanged: (String? value) {
        // This is called when the user selects an item.
        setState(() {
          dropdownValue = value!;
        });
      },
      items: list.map<DropdownMenuItem<String>>((String value) {
        return DropdownMenuItem<String>(
          value: value,
          child: Text(value),
        );
      }).toList(),
    );
  }
}

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

<img width="646" alt="image" src="https://github.com/flutter/flutter/assets/10572694/1e1e2a40-b3ca-41e8-ae52-3807d0cc20d8">

<img width="687" alt="Screenshot 2023-10-08 at 8 14 59 PM" src="https://github.com/flutter/flutter/assets/10572694/eacb5594-e7ec-43ef-94f4-391335a78ae3">
<img width="805" alt="Screenshot 2023-10-08 at 8 15 05 PM" src="https://github.com/flutter/flutter/assets/10572694/36618455-fde7-4fbd-880b-db934984a54a">
<img width="795" alt="Screenshot 2023-10-08 at 8 15 24 PM" src="https://github.com/flutter/flutter/assets/10572694/b35523d5-e391-423d-b0cf-d0e16adb3d12">
<img width="801" alt="Screenshot 2023-10-08 at 8 15 15 PM" src="https://github.com/flutter/flutter/assets/10572694/a24f6a71-4f3b-4909-8810-887dd945c903">

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
shine@Abhijeets-MacBook-Pro demo_app % fl
utter doctor
Doctor summary (to see all details, run
flutter doctor -v):
[!] Flutter (Channel stable, 3.13.6, on
    macOS 13.5.2 22G91 darwin-x64, locale
    en-CA)
    ! Warning: `flutter` on your path
      resolves to
      /Users/shine/Docs/Flutter/flutter/b
      in/flutter, which is not inside
      your current Flutter SDK checkout
      at
      /Users/shine/docs/Flutter/flutter.
      Consider adding
      /Users/shine/docs/Flutter/flutter/b
      in to the front of your path.
    ! Warning: `dart` on your path
      resolves to
      /Users/shine/Docs/Flutter/flutter/b
      in/dart, which is not inside your
      current Flutter SDK checkout at
      /Users/shine/docs/Flutter/flutter.
      Consider adding
      /Users/shine/docs/Flutter/flutter/b
      in to the front of your path.
[✓] Android toolchain - develop for
    Android devices (Android SDK version
    29.0.2)
[!] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a
      full installation is necessary for
      iOS and macOS development.
      Download at:
      https://developer.apple.com/xcode/d
      ownload/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch
        /Applications/Xcode.app/Contents/
        Developer
        sudo xcodebuild -runFirstLaunch
[✓] Chrome - develop for the web
[!] Android Studio (not installed)
[✓] VS Code (version 1.82.2)
[✓] Connected device (2 available)
[✓] Network resources

! Doctor found issues in 3 categories.
```

</details>

**Comment by danagbemava-nc** [comment] 2023-10-09 09:34
Closing this as a duplicate of https://github.com/flutter/flutter/issues/94605

**Closed by danagbemava-nc** 2023-10-09 09:34 UTC
Labels: in triage
