### ISSUE TITLE
iOS CupertinoTextField gallery text jitters with selection handles 

### ISSUE THREAD

**Issue by GaryQian** [flutter/flutter#31817] opened 2019-04-30 00:30 UTC
@xster discovered that in the Flutter gallery Cupertino text field demo, if you slide the selection handle back and forth, the text will jitter slightly up and down.

This repros on iPhone XR, other devices unconfirmed but likely affected.

https://streamable.com/d0nia

This text selection handles PR landed recently, so it may be a good place to start: https://github.com/flutter/flutter/pull/31332

**Comment by GaryQian** [comment] 2019-04-30 00:30
cc @justinmc

**Comment by GaryQian** [comment] 2019-04-30 00:32
This does not (from manual testing) seem to impact material text fields or raw CupertinoTextFields by themselves.

**Comment by pakyo-pan** [comment] 2019-04-30 02:43
same here . 
in `_buildChatTextField()` method of the Flutter gallery Cupertino_text_field demo . When typing text, the text will jitter .

**Comment by justinmc** [comment] 2019-04-30 15:36
I can't seem to reproduce this on a physical Pixel 2 or a Pixel 2 emulator.  Maybe it's only iOS.  I'll try on iPhone later.

**Comment by justinmc** [comment] 2019-04-30 16:55
I reproduced it on iPhone XR.  The culprit seems to be a different PR of mine: https://github.com/flutter/flutter/pull/31088

I think bouncing scroll physics on cupertino fields is causing this tiny jitter.

**Comment by tvolkert** [comment] 2020-01-13 02:51
@justinmc https://github.com/flutter/flutter/issues/31817#issuecomment-488030706 indicates that we know the culprit for this - was it reverted, or is this still open?

**Comment by justinmc** [comment] 2020-01-13 21:44
I believe this has been fixed in subsequent updates to text height.  I just tried it on the same iPhone XR simulator and couldn't reproduce it.

I'm going to close this, but if anyone still sees it, please let me know!

**Closed by justinmc** 2020-01-13 21:44 UTC
Labels: a: text input, f: cupertino, framework, waiting for customer response, ⌺‬ platform-ios
