### ISSUE TITLE
In app purchases product purchases confirmation issues 

### ISSUE THREAD

**Issue by AmadIrfan** [flutter/flutter#147169] opened 2024-04-22 15:54 UTC
### Steps to reproduce

no verification of purchased products.
if i use this methods it return a bool value that we can't use any whare 
bool response = await iapConnection.buyConsumable( purchaseParam: param,)
no any method available to verify product purchases 

### Actual results

no verification of purchased products.
if i use this methods it return a bool value that we can't use any whare 
bool response = await iapConnection.buyConsumable( purchaseParam: param,)
no any method available to verify product purchases 

### Logs

<details open>
<summary>Logs</summary>

```console

no logs

```

</details>

### Flutter Doctor output

<details open>
<summary>Doctor output</summary>

```console

<!-- Paste your output here -->

```

</details>

>

**Comment by huycozy** [comment] 2024-04-23 08:09
Hi @AmadIrfan 
You should check PurchaseStatus on purchaseStream. This thing is already documented at [buyConsumable method](https://github.com/flutter/packages/blob/88572212ae3fc45d634a31e2328d77651121f1af/packages/in_app_purchase/in_app_purchase/lib/in_app_purchase.dart#L139-L159), you can check it for more details.

Closing the issue as it's not a bug or feature request.

**Closed by huycozy** 2024-04-23 08:09 UTC
Labels: in triage
