### ISSUE TITLE
[web]: Flutter web is missing the ability to connect to a performance profiler in profile mode.

### ISSUE THREAD

**Issue by UliPrantz** [flutter/flutter#65266] opened 2020-09-04 21:18 UTC
Normally when a flutter application is run with something like:

`flutter run -d chrome`

A url is printed which can be used to connect to debug service or a performance profiler like the new DevTools this is indeed the case for a flutter web app in debug mode (something like this: `Debug service listening on ws://127.0.0.1:50205/hxcFjpOgB5U=`) but when run the following way:

`flutter run -d chrome --profile`

Which is needed to get accurate performance information nothing like this is printed to the console. Therefore it isn't possible to profile performance or debug performance issues of a flutter web app properly right now.

**Comment by UliPrantz** [comment] 2020-09-06 22:15
Could be combined with #52258

**Comment by TahaTesser** [comment] 2020-09-07 14:12
Hi @UliPrantz 
This is not supported yet, when the feature is implemented, the ability to connect to a performance profiler would be added anyway, hence don't need separate issue for this
Duplicate of  https://github.com/flutter/flutter/issues/52258
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2020-09-07 14:12 UTC
