### ISSUE TITLE
.uid: The getter 'uid' isn't defined for the type 'UserCredential'. - Flutter, FirebaseAuth

### ISSUE THREAD

**Issue by DANISOVUT** [flutter/flutter#76233] opened 2021-02-17 21:16 UTC
Hello. My .uid says: The getter 'uid' isn't defined for the type 'UserCredential'.

<img width="871" alt="Bildschirmfoto 2021-02-17 um 22 10 35" src="https://user-images.githubusercontent.com/71729545/108268925-89128b80-716d-11eb-8f05-e86bbd651f22.png">

My Code:

`import 'package:firebase_auth/firebase_auth.dart';

class AuthService {
  final FirebaseAuth _firebaseAuth = FirebaseAuth.instance;

  Stream<String> get onAuthStateChanged => _firebaseAuth.authStateChanges().map(
        (User user) => user?.uid,
      );

  Future<String> createUserWithEmailAndPassword(
      String email, String password, String name) async {
    final currentUser = await _firebaseAuth.createUserWithEmailAndPassword(
      email: email,
      password: password,
    );

    var updateInfo = UserUpdateInfo();
    //updateInfo.displayName = name;
    await FirebaseAuth.instance.currentUser.updateProfile(displayName:name);
    await FirebaseAuth.instance.currentUser.reload();
    return FirebaseAuth.instance.currentUser.uid;
  }

  Future<String> signInWithEmailAndPassword(
      String email, String password) async {
    return (await _firebaseAuth.signInWithEmailAndPassword(
            email: email, password: password))
        .uid;
  }

  signOut() {
    return _firebaseAuth.signOut();
  }
}

class UserUpdateInfo {
}
`

How can I fix it? Thanks!

**Comment by pedromassangocode** [comment] 2021-02-18 08:49
Hi @DANISOVUT 
From what I can see, the issue is related to a FlutterFire plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself.  

Note that this may be an caused by your implementation.

If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by pedromassangocode** 2021-02-18 08:49 UTC
Labels: team: infra
