### ISSUE TITLE
Use TabBarView with AutomaticKeepAliveClientMixin and with 4 or more pages will cause error

### ISSUE THREAD

**Issue by debuggerx01** [flutter/flutter#16502] opened 2018-04-12 06:22 UTC
## What I Try to do
I use the AutomaticKeepAliveClientMixin in my widget , because I want to build a TabView with 4 pages and they can save self's state after scroll Automaticlly.
And I follow the issue #16445 , then switch my flutter channel to master , and yes , AutomaticKeepAlive works now , but I got a crush when I try to switch page 4  from page 1 directly after app launched.

## Steps to Reproduce
Here is my demo code : 
[https://gist.github.com/debuggerx01/69668ff96926d4fddf7a51167045be5b](https://gist.github.com/debuggerx01/69668ff96926d4fddf7a51167045be5b)

And I record a gif to show this problem:
![tabbatview_issue](https://user-images.githubusercontent.com/19624835/38659535-8dc3d2ca-3e5c-11e8-8598-6b4a2517dbd4.gif)

## Logs

```
I/flutter ( 6641): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 6641): The following assertion was thrown building NotificationListener<KeepAliveNotification>:
I/flutter ( 6641): 'package:flutter/src/rendering/object.dart': Failed assertion: line 2732 pos 14:
I/flutter ( 6641): '_debugUltimatePreviousSiblingOf(after, equals: _firstChild)': is not true.
I/flutter ( 6641): 
I/flutter ( 6641): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter ( 6641): more information in this error message to help you determine and fix the underlying cause.
I/flutter ( 6641): In either case, please report this assertion by filing a bug on GitHub:
I/flutter ( 6641):   https://github.com/flutter/flutter/issues/new
I/flutter ( 6641): 
I/flutter ( 6641): When the exception was thrown, this was the stack:
I/flutter ( 6641): #2      _RenderSliverMultiBoxAdaptor&RenderSliver&ContainerRenderObjectMixin._insertIntoChildList (package:flutter/src/rendering/object.dart)
I/flutter ( 6641): #3      _RenderSliverMultiBoxAdaptor&RenderSliver&ContainerRenderObjectMixin.insert (package:flutter/src/rendering/object.dart:2766:5)
I/flutter ( 6641): #4      RenderSliverMultiBoxAdaptor.insert (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:209:11)
I/flutter ( 6641): #5      SliverMultiBoxAdaptorElement.insertChildRenderObject (package:flutter/src/widgets/sliver.dart:849:18)
I/flutter ( 6641): #6      RenderObjectElement.attachRenderObject (package:flutter/src/widgets/framework.dart:4496:35)
I/flutter ( 6641): #7      RenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4262:5)
I/flutter ( 6641): #8      SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4636:11)
I/flutter ( 6641): #9      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter ( 6641): #10     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
I/flutter ( 6641): #11     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter ( 6641): #12     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter ( 6641): #13     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
I/flutter ( 6641): #14     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
I/flutter ( 6641): #15     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter ( 6641): #16     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
I/flutter ( 6641): #17     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter ( 6641): #18     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter ( 6641): #19     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
I/flutter ( 6641): #20     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
I/flutter ( 6641): #21     ParentDataElement.mount (package:flutter/src/widgets/framework.dart:3938:11)
I/flutter ( 6641): #22     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter ( 6641): #23     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
I/flutter ( 6641): #24     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter ( 6641): #25     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter ( 6641): #26     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
I/flutter ( 6641): #27     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3752:11)
I/flutter ( 6641): #28     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
I/flutter ( 6641): #29     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter ( 6641): #30     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
I/flutter ( 6641): #31     SliverMultiBoxAdaptorElement.performRebuild (package:flutter/src/widgets/sliver.dart:702:34)
I/flutter ( 6641): #32     SliverMultiBoxAdaptorElement.update (package:flutter/src/widgets/sliver.dart:671:7)
I/flutter ( 6641): #33     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter ( 6641): #34     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4362:32)
I/flutter ( 6641): #35     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4752:17)
I/flutter ( 6641): #36     _ViewportElement.update (package:flutter/src/widgets/viewport.dart:187:11)
I/flutter ( 6641): #37     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter ( 6641): #38     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter ( 6641): #39     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter ( 6641): #40     ProxyElement.update (package:flutter/src/widgets/framework.dart:3892:5)
I/flutter ( 6641): #41     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter ( 6641): #42     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4644:14)
I/flutter ( 6641): #43     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter ( 6641): #44     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4644:14)
I/flutter ( 6641): #45     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter ( 6641): #46     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4644:14)
I/flutter ( 6641): #47     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter ( 6641): #48     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4644:14)
I/flutter ( 6641): #49     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter ( 6641): #50     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter ( 6641): #51     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter ( 6641): #52     StatefulElement.update (package:flutter/src/widgets/framework.dart:3782:5)
I/flutter ( 6641): #53     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter ( 6641): #54     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4644:14)
I/flutter ( 6641): #55     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter ( 6641): #56     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4644:14)
I/flutter ( 6641): #57     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter ( 6641): #58     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4644:14)
I/flutter ( 6641): #59     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter ( 6641): #60     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4644:14)
I/flutter ( 6641): #61     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter ( 6641): #62     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter ( 6641): #63     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter ( 6641): #64     StatelessElement.update (package:flutter/src/widgets/framework.dart:3685:5)
I/flutter ( 6641): #65     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter ( 6641): #66     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter ( 6641): #67     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter ( 6641): #68     StatefulElement.update (package:flutter/src/widgets/framework.dart:3782:5)
I/flutter ( 6641): #69     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter ( 6641): #70     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter ( 6641): #71     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter ( 6641): #72     StatefulElement.update (package:flutter/src/widgets/framework.dart:3782:5)
I/flutter ( 6641): #73     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter ( 6641): #74     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter ( 6641): #75     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter ( 6641): #76     StatelessElement.update (package:flutter/src/widgets/framework.dart:3685:5)
I/flutter ( 6641): #77     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter ( 6641): #78     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter ( 6641): #79     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter ( 6641): #80     StatefulElement.update (package:flutter/src/widgets/framework.dart:3782:5)
I/flutter ( 6641): #81     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter ( 6641): #82     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter ( 6641): #83     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter ( 6641): #84     StatelessElement.update (package:flutter/src/widgets/framework.dart:3685:5)
I/flutter ( 6641): #85     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter ( 6641): #86     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter ( 6641): #87     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter ( 6641): #88     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2225:33)
I/flutter ( 6641): #89     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:621:20)
I/flutter ( 6641): #90     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
I/flutter ( 6641): #91     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter ( 6641): #92     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter ( 6641): #93     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
I/flutter ( 6641): #94     _invoke (dart:ui/hooks.dart:120:13)
I/flutter ( 6641): #95     _drawFrame (dart:ui/hooks.dart:109:3)
I/flutter ( 6641): (elided 2 frames from class _AssertionError)
I/flutter ( 6641): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter ( 6641): Another exception was thrown: 'package:flutter/src/rendering/object.dart': Failed assertion: line 2732 pos 14: '_debugUltimatePreviousSiblingOf(after, equals: _firstChild)': is not true.
I/flutter ( 6641): Another exception was thrown: 'package:flutter/src/rendering/object.dart': Failed assertion: line 2732 pos 14: '_debugUltimatePreviousSiblingOf(after, equals: _firstChild)': is not true.
I/flutter ( 6641): Another exception was thrown: 'package:flutter/src/rendering/object.dart': Failed assertion: line 2732 pos 14: '_debugUltimatePreviousSiblingOf(after, equals: _firstChild)': is not true.
I/flutter ( 6641): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3480 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
I/flutter ( 6641): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3480 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
I/flutter ( 6641): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3480 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
I/flutter ( 6641): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3480 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
I/flutter ( 6641): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3480 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
I/flutter ( 6641): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3480 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
I/flutter ( 6641): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3480 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
I/flutter ( 6641): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3480 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
I/flutter ( 6641): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3480 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
I/flutter ( 6641): Another exception was thrown: The _ScaffoldLayout custom multichild layout delegate forgot to lay out the following children:`

## Flutter Doctor
`flutter doctor -v
[✓] Flutter (Channel master, v0.2.12-pre.15, on Linux, locale zh_CN.UTF-8)
    • Flutter version 0.2.12-pre.15 at /home/debuggerx/flutter
    • Framework revision da9e1a4aca (3 小时前), 2018-04-11 20:50:25 -0700
    • Engine revision 4db7a00677
    • Dart version 2.0.0-dev.47.0.flutter-4126459025

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /opt/android-sdk
    • Android NDK at /opt/android-sdk/ndk-bundle
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = /opt/android-sdk
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version openjdk version "1.8.0_152-release"
    • All Android licenses accepted.

[✓] Android Studio (version 3.1)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 23.2.2
    • Dart plugin version 173.4700
    • Java version openjdk version "1.8.0_152-release"

[!] IntelliJ IDEA Ultimate Edition (version 2016.2)
    • IntelliJ at /home/debuggerx/idea
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins
    ✗ This install is older than the minimum recommended version of 2017.1.0.

[!] IntelliJ IDEA Ultimate Edition (version 2017.2)
    • IntelliJ at /opt/idea
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    • Dart plugin version 172.4343.25
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[✓] Connected devices (1 available)
    • Custom Phone, 7 1 0, API 25, 768x1280 • 192.168.56.101:5555 • android-x86 • Android 7.1.1 (API 25)
```

**Comment by debuggerx01** [comment] 2018-04-19 04:34
NOT fixed until now (Channel master, v0.3.1-pre.35)
@Hixie

**Comment by shitb** [comment] 2018-04-19 07:27
The same problem.

**Comment by Hixie** [comment] 2018-04-23 19:41
cc @goderbauer This way be related to your recent change?

**Comment by marekchen** [comment] 2018-05-21 02:37
@Hixie The same problem happened to me.

**Comment by JakeyYe** [comment] 2018-05-27 03:48
The same problem,me too.

**Comment by marekchen** [comment] 2018-05-28 12:32
#17718

**Comment by Hixie** [comment] 2018-06-12 22:30
Duplicate of https://github.com/flutter/flutter/issues/11895.

**Closed by Hixie** 2018-06-12 22:30 UTC
Labels: f: material design, framework, severe: crash
