### ISSUE TITLE
[ios] Some of the markers fed to the map is not displayed in google map ios device

### ISSUE THREAD

**Issue by rsachiendran** [flutter/flutter#123677] opened 2023-03-29 08:59 UTC
**Details**

This issue can be reproduced if more than 1300 markers are fed to the map. The markers after that count are not displayed  in iOS device but in android all the markers are displayed.
The total number of markers that I need to show in the map is about 1800 in average. But the issue is iOS device only show limited number of markers which is around 1300.

The issue is only with iOS devices.

Devices Tested :

- iPhone 11 Pro (v 16.3.1)
- iOS Simulator (v 16.2)

Package:

[google_maps_flutter 2.2.5](https://pub.dev/packages/google_maps_flutter)

Code snippet:

Future<void> loadMarkers(
      List<LatLng> markers, BitmapDescriptor markerIcon) async {
    for (int i = 0; i < markers.length; i++) {
      _markers.add(
        Marker(
          markerId: MarkerId(i.toString()),
          position: markers[i],
          icon: markerIcon,
          onTap: () async {
            facilityMarkerHighlight(
                _context!, _filteredFacilities[i], markers[i]);
          },
        ),
      );
    }
    _markers.toSet;
    notifyListeners();
}

GoogleMap(
            initialCameraPosition: model.cameraPosition,
            markers: Set<Marker>.of(model.getMarkers).map((e) => e).toSet(),
            zoomControlsEnabled: false,
            mapType: MapType.normal,
            rotateGesturesEnabled: true,
            onMapCreated: (GoogleMapController mapController) {
              model.initializeContext(context);
              model.googleMapController = mapController;
         },
),

Target Platform: iOS
Target OS version: 12 and above
Devices: iOS mobile device / simulator

Logs: 
![Screenshot 2023-03-29 at 1 27 50 PM](https://user-images.githubusercontent.com/112466842/228479028-05472f64-d811-434b-acbd-1e0da45692eb.png)

`Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.2, on macOS 13.0 22A380 darwin-arm, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.76.1)
[✓] Connected device (4 available)
[✓] HTTP Host Availability

• No issues found!`

Screenshots:

iOS - Markers are lesser than in the android screenshot 
![IMG_1320](https://user-images.githubusercontent.com/112466842/228479663-d69f70a3-b9c8-4653-8836-ec932a838136.PNG)

Android - Works as expected
![Screenshot_1680077742](https://user-images.githubusercontent.com/112466842/228481576-9b9b3fd8-c2e6-496d-9618-1a2587be1551.png)

Very much appreciated if this issue can be addressed soon as possible as this is a major impact to our clients.

**Comment by huycozy** [comment] 2023-03-29 11:24
Hi @rsachiendran 
Which `google_maps_flutter` plugin version are you using? Could you please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this? Also, please provide the output of `flutter doctor -v` as well.
Thank you!

**Comment by huycozy** [comment] 2023-03-31 04:05
Thank you so much for the complete sample code. I checked this on both Android and iOS and I can see it's more lagging on iOS than on Android when zooming or dragging the map, though I can not verify the number of markers on these platforms:).

However, I see there are some (similar) issues: #60750, #45508 (is closed as a duplicate of #60750). So I will close this issue in favor of #60750. I will also leave my comment there and link to this issue. 

Please follow up on it for further updates. You can also leave there your comment and react an upvote to the original comment will help to raise the issue. Thank you!

**Closed by huycozy** 2023-03-31 04:05 UTC
Labels: in triage
