### ISSUE TITLE
[tool_crash] FileSystemException: Cannot open file, path = ... (OS Error: Permission denied, errno = 13)

### ISSUE THREAD

**Issue by AMJADH195** [flutter/flutter#50425] opened 2020-02-09 04:31 UTC
## Command
```console
flutter run
```

## Logs

```bash
FileSystemException: FileSystemException: Cannot open file, path = '/Users/user/Desktop/development/myapp/ios/Flutter/Generated.xcconfig' (OS Error: Permission denied, errno = 13)
```

```bash
#0      _File.throwIfError (dart:io/file_impl.dart:645:7)
#1      _File.openSync (dart:io/file_impl.dart:489:5)
#2      _File.writeAsBytesSync (dart:io/file_impl.dart:614:31)
#3      _File.writeAsStringSync (dart:io/file_impl.dart:638:5)
#4      ForwardingFile.writeAsStringSync (package:file/src/forwarding/forwarding_file.dart:154:16)
#5      _updateGeneratedXcodePropertiesFile (package:flutter_tools/src/ios/xcodeproj.dart:96:32)
#6      updateGeneratedXcodeProperties (package:flutter_tools/src/ios/xcodeproj.dart:66:3)
#7      IosProject._updateGeneratedXcodeConfigIfNeeded (package:flutter_tools/src/project.dart:472:13)
#8      IosProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:467:11)
#9      FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:215:17)
<asynchronous suspension>
#10     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:654:21)
<asynchronous suspension>
#11     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:567:33)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#13     _rootRun (dart:async/zone.dart:1126:13)
#14     _CustomZone.run (dart:async/zone.dart:1023:19)
#15     _runZoned (dart:async/zone.dart:1518:10)
#16     runZoned (dart:async/zone.dart:1465:12)
```

```console
[✓] Flutter (Channel master, v1.14.7-pre.138, on Mac OS X 10.14.5 18F132, locale en-LV)
    • Flutter version 1.14.7-pre.138 at /Users/user/Downloads/flutter
    • Framework revision 49be146953 (3 days ago), 2020-02-05 18:02:20 -0800
    • Engine revision 81dffd1241
    • Dart version 2.8.0 (build 2.8.0-dev.7.0 c8ed304e97)

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://

**Comment by iapicca** [comment] 2020-02-10 11:42
Hi @AMJADH195 
can you please provide your full `flutter doctor -v` ,
your `flutter run --verbose` 
Thank you

**Comment by Incr3dible** [comment] 2020-02-10 15:13
I get the same error for a root Dictionary on Android even when the app has root access. Any solution? (Android 10)

**Comment by iapicca** [comment] 2020-02-12 08:33
Hi @Incr3dible 
can you please provide your full `flutter doctor -v` ,
your `flutter run --verbose`  as well
Thank you

**Comment by jonahwilliams** [comment] 2020-02-15 22:01
Duplicate of https://github.com/flutter/flutter/issues/50880

**Closed by jonahwilliams** 2020-02-15 22:01 UTC
Labels: severe: crash, tool, waiting for customer response
