### ISSUE TITLE
[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method getApplicationDocumentsDirectory on channel plugins.flutter.io/path_provider)

### ISSUE THREAD

**Issue by ahmaddarwesh** [flutter/flutter#61226] opened 2020-07-10 11:39 UTC
I have create a flutter app 
this app use Hive package as database and use Shared preferences 
the app working perfectly on
-iOS Simulator 13.5 
-Android Emulator all android version 
-physical device (debugging mode)
-physical device (Profiling mode)

but when  I trying to get app as release mode and install it on my physical device I have this issue:

` [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences)`
 
**and this another issue happened when app call this** 

`var dir = await getApplicationDocumentsDirectory();
   await Hive.initFlutter(dir.path);`

**Issue** 
`[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method getApplicationDocumentsDirectory on channel plugins.flutter.io/path_provider)`

Additional information 

**doctor -verbose** 

```
`[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.5 19F101, locale en-LB)
    • Flutter version 1.17.5 at /Users/ahmaddarwesh/Documents/Development/flutter
    • Framework revision 8af6b2f038 (10 days ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/ahmaddarwesh/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/ahmaddarwesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.2

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (2 available)
    • MHA L29   • AHK7N17216007023                     • android-arm64 • Android 9 (API 28)
    • iPhone 11 • B2558C2D-C6E8-47CF-8CE1-8BD935A9F761 • ios           • com.apple.CoreSimulator.SimRuntime.iOS-13-5 (simulator)

• No issues found!`
```

**pubspace.yaml**

```
`dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^0.5.8
  smooth_page_indicator: ^0.1.5
  #responsive and Sizes
  flutter_screenutil: ^2.2.0
  #badges for Cart and Notification
  badges: ^1.1.1
  #Animate for clicking
  flutter_bounce: ^1.0.8
  #For Expendable List (Categories)
  sticky_and_expandable_list: ^0.2.1
 
  cupertino_icons: ^0.1.3
  #Icons Material
  material_design_icons_flutter: 4.0.5345
  #Button to progress
  flutter_progress_button: ^1.0.0
  #Text Replacment
  auto_size_text: ^2.1.0
  #hasura connect for graphql database
  graphql_flutter: ^3.0.1
  #dialogs
  flutter_animated_dialog: ^1.1.0
  #zooming
  pinch_zoom_image_last: ^0.3.1
  #Scrollable List
  scrollable_positioned_list: ^0.1.6
  #Routing management
  get: ^3.2.2
  #Database
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2
  #shimmer
  shimmer: ^1.1.1
  #Permission manager
  permission_handler: ^5.0.1+1
  #map helper
  google_maps_flutter: ^0.5.28+1
  #Location helper
  geolocator: ^5.3.2+2

  path_provider: ^1.6.11

dev_dependencies:
  flutter_test:
    sdk: flutter`
```

**Comment by VladyslavBondarenko** [comment] 2020-07-10 12:49
Hi @ahmaddarwesh 
could you attach your `MainActivity.kt`? it may be case similar to https://github.com/flutter/flutter/issues/41119#issuecomment-625128400
or even better if you could attach a minimal complete reproducible project.

**Comment by ahmaddarwesh** [comment] 2020-07-10 14:03
@VladyslavBondarenko 



> Hi @ahmaddarwesh
> could you attach your `MainActivity.kt`? it may be case similar to [#41119 (comment)](https://github.com/flutter/flutter/issues/41119#issuecomment-625128400)
> or even better if you could attach a minimal complete reproducible project.

My MainActivity.kt
 
```
import io.flutter.embedding.android.FlutterActivity


class MainActivity : FlutterActivity() {

}
```

My main.dart

```
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  runApp(
    GetBuilder<DataCont>(
      init: DataCont(),
      builder: (_) {
        return MyApp();
      },
    ),
  );
  hive().initHive();
}

initHive() async {
    var dir = await getApplicationDocumentsDirectory();
    await Hive.initFlutter(dir.path);

    var count = await Hive.openBox("cart_count");
    await Hive.openBox("favorite_list");
    await Hive.openBox("cart");
    if (count.get('cart_all') == null) {
      count.put('cart_all', 0);
    }
  }
```

**Comment by ahmaddarwesh** [comment] 2020-07-10 14:13
> Hi @ahmaddarwesh
> could you attach your `MainActivity.kt`? it may be case similar to [#41119 (comment)](https://github.com/flutter/flutter/issues/41119#issuecomment-625128400)
> or even better if you could attach a minimal complete reproducible project.

when I replace my MainActivity.kt to be like this [MainActivity.kt](https://github.com/flutter/flutter/issues/41119#issuecomment-625128400)

**I get this error**

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.moreforless, PID: 14053
    java.lang.IllegalAccessError: Interface androidx.lifecycle.b implemented by class io.flutter.plugins.googlemaps.GoogleMapsPlugin is inaccessible (declaration of 'io.flutter.plugins.googlemaps.GoogleMapsPlugin' appears in /data/app/com.moreforless-IBKzRpFwNyYl7jQYQK8QxA==/base.apk)
        at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(Unknown Source:0)
        at com.moreforless.MainActivity.e(Unknown Source:5)
```

**Comment by ahmaddarwesh** [comment] 2020-07-10 15:04
Okkkay after 3 days of searching and trying..
Thanks @VladyslavBondarenko 

after change my MainActivity.kt like yours, then Just replace version of Gradle in gradle.build file
from 4.0.0 to 3.6.2
like this 
`classpath 'com.android.tools.build:gradle:3.6.2'`

it's worked

**Comment by VladyslavBondarenko** [comment] 2020-07-10 15:20
@ahmaddarwesh 
Interesting, thanks for the input.
I was playing with this and this is what I noticed:

Tried with a new app created with stable, running on Android 9 (API 28) device
`path_provider: ^1.6.11`

<details>
 <summary>code sample</summary>

```
import 'package:flutter/material.dart';
import 'package:path_provider/path_provider.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  runApp(MaterialApp(home: MyApp()));
}

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  String dirName = '';

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            RaisedButton(
              child: Text('getApplicationDocumentsDirectory'),
              onPressed: () async {
                var dir = await getApplicationDocumentsDirectory();
                setState(() {
                  dirName = dir.path;
                });
              },
            ),
            Text(dirName),
          ],
        ),
      ),
    );
  }
}
```

</details>

I tried before with `flutter run --release` - path_provider works, ApplicationDocumentsDirectory is shown.
But when I tried with `flutter build apk` and installed `app-release.apk` - it doesn't work.
Then I tried with another channels - it works when I build with current master `1.20.0-8.0.pre.40` and beta `1.19.0-4.3.pre`.

I had `classpath 'com.android.tools.build:gradle:3.5.0'` - default for project created with stable.
And yes, when I change it to 3.6.2 - it works when I build with stable too

**Comment by ahmaddarwesh** [comment] 2020-07-10 17:57
> @ahmaddarwesh
> Interesting, thanks for the input.
> I was playing with this and this is what I noticed:
> 
> Tried with a new app created with stable, running on Android 9 (API 28) device
> `path_provider: ^1.6.11`
> 
> code sample
> I tried before with `flutter run --release` - path_provider works, ApplicationDocumentsDirectory is shown.
> But when I tried with `flutter build apk` and installed `app-release.apk` - it doesn't work.
> Then I tried with another channels - it works when I build with current master `1.20.0-8.0.pre.40` and beta `1.19.0-4.3.pre`.
> 
> I had `classpath 'com.android.tools.build:gradle:3.5.0'` - default for project created with stable.
> And yes, when I change it to 3.6.2 - it works when I build with stable too

I hope fix this bug as soon as possible 
Thanks again

**Comment by thongvo109** [comment] 2020-07-13 04:37
@ahmaddarwesh 

You try: https://github.com/flutter/flutter/issues/58113#issuecomment-657348672 
I think when creating Project Flutter version 3.5.0 there will be an error on the Android side can not call the plug-in.

**Comment by VladyslavBondarenko** [comment] 2020-07-13 10:58
@ahmaddarwesh 
I tried `classpath 'com.android.tools.build:gradle:4.0.0'` with current beta `1.19.0-4.3.pre` and master `1.20.0-8.0.pre.57`.
It works. Seems to be fixed, closing since there is not need then to track the issue.
Please comment if you have another result

**Closed by VladyslavBondarenko** 2020-07-13 10:58 UTC
Labels: in triage

**Comment by ahmaddarwesh** [comment] 2020-07-13 19:40
> @ahmaddarwesh
> I tried `classpath 'com.android.tools.build:gradle:4.0.0'` with current beta `1.19.0-4.3.pre` and master `1.20.0-8.0.pre.57`.
> It works. Seems to be fixed, closing since there is not need then to track the issue.
> Please comment if you have another result

Thank you That's worked perfectly

**Comment by marcschw** [comment] 2020-12-20 12:41
I had exactly the same issue coming back with the current beta 1.25.0-8.1.pre
Switching back to stable now to see if it will work again

**Comment by Dhi13man** [comment] 2021-01-13 10:34
Setting the following in app level `build.gradle` is another viable workaround for anyone facing this with Gradle version 6+ for with Path provider. For me the issue seems to occur only when I'm trying to combine Hive and Firebase for giving the choice between Local Database (Hive in my case) or Cloud Database (Firestore) to the user, and doesn't occur if I am only trying to use the local Database.

```
android {
    ...

    buildTypes {
        release {
            ...
            minifyEnabled false
            shrinkResources false
        }
    }
}
```

I'd guess, the bulkiness of Firebase is messing up the code shrinking in release builds, and that is breaking Path Provider, which in my case is breaking Hive.
