### ISSUE TITLE
[Documentation] How to call integration_test with --dart-define env variable?

### ISSUE THREAD

**Issue by ciripel** [flutter/flutter#109212] opened 2022-08-09 09:20 UTC
Hello, 
I have found out that i can't seem to call integration_test with an env variable.
```
flutter test integration_test --dart-define=ENV_VARIABLE=$ENV_VARIABLE_PLACEHOLDER
```
returns `Integration tests and unit tests cannot be run in a single invocation. Use separate invocations of `flutter test` to run integration tests and unit tests.`
I also checked online for solutions to this issue and have not found anything. Does anyone know how can i achieve this?
Thank you in advance!

**Comment by exaby73** [comment] 2022-08-09 09:32
Hello @ciripel. You can pass `--dart-define` to `flutter test` like this

```sh
flutter test --dart-define=ENV_VARIABLE=$ENV_VARIABLE_PLACEHOLDER integration_test
```

Hope this helps :)

**Comment by ciripel** [comment] 2022-08-09 10:35
thanks @exaby73 issue is closed! problem is with spaces in the env variable itself!

**Comment by ciripel** [comment] 2022-08-09 11:13
I setup env variable like this:
```
export ENV_VARIABLE_PLACEHOLDER = "\"word1 word2 word3\""
```
if i run 
```
flutter test integration_test --dart-define=ENV_VARIABLE=$ENV_VARIABLE_PLACEHOLDER
```
i get error `Integration tests and unit tests cannot be run in a single invocation. Use separate invocations of flutter test to run integration tests and unit tests.`
when i check `echo $ENV_VARIABLE_PLACEHOLDER` i get `"word1 word2 word3"`

if i run 
```
flutter test integration_test --dart-define=ENV_VARIABLE="word1 word2 word3"
```
integration test runs correctly!

where is the issue cause i really do not get it!

**Comment by ciripel** [comment] 2022-08-09 11:16
> Hello @ciripel. You can pass `--dart-define` to `flutter test` like this
> 
> ```shell
> flutter test --dart-define=ENV_VARIABLE=$ENV_VARIABLE_PLACEHOLDER integration_test
> ```
> 
> Hope this helps :)

There is no difference if u change the arguments order after `flutter test`!

**Comment by exaby73** [comment] 2022-08-09 11:24
Can you try running the following:

```
flutter test integration_test --dart-define=ENV_VARIABLE="$ENV_VARIABLE_PLACEHOLDER"

**Comment by ciripel** [comment] 2022-08-09 11:33
> Can you try running the following:
> 
> ```
> flutter test integration_test --dart-define=ENV_VARIABLE="$ENV_VARIABLE_PLACEHOLDER"
> ```

How can this run? like this it actually works but i was thinking like this the ENV_VARIABLE will be the actual String `$ENV_VARIABLE_PLACEHOLDER` not the value of that variable!.
Thank you @exaby73

**Comment by ciripel** [comment] 2022-08-09 11:35
Maybe it will be good to add this in the [DOCUMENTATION] of `--dart-define`?

**Comment by exaby73** [comment] 2022-08-09 11:36
This behavior is part of how bash/zsh works. This is not specific to Flutter. I'm glad that works for you :) I'm closing this issue since it's not a bug or feature request. Thank you

**Closed** 2022-08-09 11:36 UTC
Labels: in triage, r: solved
