### ISSUE TITLE
'package:flutter/src/widgets/transitions.dart': Failed assertion: line 43 pos 15: 'listenable != I/flutter ( 3529): null': is not true.

### ISSUE THREAD

**Issue by Jellevanlith35** [flutter/flutter#18638] opened 2018-06-20 17:40 UTC
```
I/flutter ( 3529): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter ( 3529): more information in this error message to help you determine and fix the underlying cause.
I/flutter ( 3529): In either case, please report this assertion by filing a bug on GitHub:
I/flutter ( 3529):   https://github.com/flutter/flutter/issues/new
I/flutter ( 3529): When the exception was thrown, this was the stack:
```

```dart
import 'package:flutter/material.dart';
import 'package:flutter/animation.dart';

class AnimatedLogo extends AnimatedWidget {
  // The Tweens are static because they don't change.
  static final _opacityTween = new Tween<double>(begin: 0.1, end: 1.0);
  static final _sizeTween = new Tween<double>(begin: 0.0, end: 300.0);

  AnimatedLogo({Key key, Animation<double> animation})
      : super(key: key, listenable: animation);

  Widget build(BuildContext context) {
    final Animation<double> animation = listenable;
    return new Center(
      child: new Opacity(
        opacity: _opacityTween.evaluate(animation),
        child: new Container(
          margin: new EdgeInsets.symmetric(vertical: 10.0),
          height: _sizeTween.evaluate(animation),
          width: _sizeTween.evaluate(animation),
          child: new FlutterLogo(),
        ),
      ),
    );
  }
}

class InputScreen extends StatefulWidget {
  @override
  _InputScreenState createState() => _InputScreenState();
}

class _InputScreenState extends State<InputScreen> with SingleTickerProviderStateMixin {
  Animation<double> animation;
  AnimationController controller;

  initState() {
    super.initState();
    controller = new AnimationController(
        duration: const Duration(milliseconds: 2000), vsync: this);
    animation = new CurvedAnimation(parent: controller, curve: Curves.easeIn);

    animation.addListener(() {
            setState(() {
              // the animation object’s value is the changed state
            });
          });

    controller.forward();
  }


  Widget build(BuildContext context) {
    return new AnimatedLogo(animation: animation);

  }  

  dispose() {
    controller.dispose();
    super.dispose();
  }
}`
```

**Comment by HansMuller** [comment] 2018-06-21 15:54
I've tried your app, restarted it a few times, and I'm not seeing the error. 

Can you provide the output from flutter doctor - so we can see what version of Flutter you're running - and any details about how exactly to trigger the error.

Note also: the animation.addListener() statement in initState() isn't needed.

**Comment by zoechi** [comment] 2018-08-26 17:02
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.

**Closed by zoechi** 2018-08-26 17:02 UTC

**Comment by pravaibh** [comment] 2018-09-16 05:10
It probably needs a restart, I was facing the same error while doing hot restart. The error went away upon restart.

**Comment by zoechi** [comment] 2018-09-19 15:35
@pravaibh can you please post a runnable reproduction and instructions how to reproduce.
Please also add the output of `flutter doctor -v`.

**Comment by pravaibh** [comment] 2018-09-21 05:15
@zoechi I can't seem to reproduce it in my code either. The issue initially came up when I tried something similar to @Jellevanlith35 's code while my application was already up and went for a hot-reload. A restart after application shutdown helped me at that time. I will raise a separate issue if I come across the issue again.

**Comment by N1nJaC0d3** [comment] 2019-01-20 13:19
`import 'package:flutter/material.dart';

// Animaion
import 'animation/basics/animation1.dart';
import 'animation/basics/animation2.dart';
import 'animation/basics/animation3.dart';


void main() {
//  runApp(MyApp());
  //runApp(Tab3App());

  runApp(BasicAnimation3());
}
`

**If I run the animation code in main.dart, no error occurs !  Why??**

**Comment by deoficial** [comment] 2020-10-18 04:43
I've with similar problem 

'package:flutter/src/widgets/transitions.dart': Failed assertion: line 1427 pos 16: 'animation != null': is not true.
Y_Y

**Comment by CastilloLuis** [comment] 2020-11-11 13:58
I'm having this issue with iOs 14 and Flutter 1.22.1 , `flutter: 'package:flutter/src/widgets/transitions.dart': Failed assertion: line 1420 pos 15: 'animation !=`. And "restart" workaround is not working :/

**Comment by pratikthakkar** [comment] 2020-12-15 04:33
Still this issue seems to be happening.
