### ISSUE TITLE
[flutter_markdown] Jump to a certain section in markdown upon clicking on a text/header using the flutter_markdown package

### ISSUE THREAD

**Issue by dev-zeb** [flutter/flutter#116162] opened 2022-11-29 04:03 UTC
## Use case

In my app, I want to display markdown data using the `flutter_markdown` package. And, the data consists of a **Table of contents** where I can see the contents, and upon clicking on a content option, it'd take the user to that particular section. But, the hyperlinked text doesn't take the user to a certain section nor it works when used inside the `launch(URL)` method in the `onTapLink()` method.

However, I can use the `scrollController.jumpTo()` method to jump to a certain position using the `offset` value of that position here but the catch is I don't know the **offset** value of that particular section where I want to navigate to. 

I've provided the `build()` method below:
```
Widget build(BuildContext context) {
    String data = """
    # Table of contents
    ## [Section 01](#section-one)
    ## [Section 02](#section-two)
    
    A long paragraph might be here . . .
    And then the sections.
    
    # Section One
    # Section Two
    """;

    return Scaffold(
      appBar: AppBar(
        title: const Text("Reading View"),
      ),
      body: Markdown(
        onTapLink: (text, link, title) {
          debugPrint("Text -> $text");
          debugPrint("Link -> $link");
          debugPrint("Title -> $title");
          scrollController.(text);
        },
        key: _globalKey,
        controller: scrollController,
        data: data,
        selectable: true,
      ),
    );
  }
```

## Proposal
It would be great if either of the following things is added to the package:
1. Allow hyperlink texts to work properly.
2. Get the exact **offset** value of a given String present in the markdown data so that we can use the `jumpTo()` method to navigate to that section.

**Comment by exaby73** [comment] 2022-11-29 14:01
Hello @dev-zeb. Thank you for filing this issue. Labeling for further insights and visibility from the team

**Comment by stuartmorgan** [comment] 2022-11-29 21:02
This looks like a duplicate of https://github.com/flutter/flutter/issues/81777

**Closed by stuartmorgan** 2022-11-29 21:02 UTC
Labels: new feature, p: first party, package, proposal, p: flutter_markdown
