### ISSUE TITLE
Web test flaky timeouts

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#133262] opened 2023-08-24 16:41 UTC
Here is an example of a web engine presubmit test flaky timeout, which blocked a Dart -> Engine roll

https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20Engine%20Drone/1269249/overview

**Comment by zanderso** [comment] 2023-08-24 16:41
```
21:11 +1512 ~142 -1: loading /b/s/w/ir/x/w/flutter/packages/flutter/test/cupertino/checkbox_test.dart [E]                                                                                              
  TimeoutException after 0:12:00.000000: Test timed out after 12 minutes.
  package:test_api/src/backend/invoker.dart 338:28  Invoker._handleError.<fn>
  dart:async/zone.dart 1391:47                      _rootRun
  dart:async/zone.dart 1301:19                      _CustomZone.run
  package:test_api/src/backend/invoker.dart 336:10  Invoker._handleError
  package:test_api/src/backend/invoker.dart 291:9   Invoker.heartbeat.<fn>.<fn>
  dart:async/zone.dart 1399:13                      _rootRun
  dart:async/zone.dart 1301:19                      _CustomZone.run
  package:test_api/src/backend/invoker.dart 290:38  Invoker.heartbeat.<fn>
  dart:async-patch/timer_patch.dart 18:15           Timer._createTimer.<fn>
  dart:isolate-patch/timer_impl.dart 398:19         _Timer._runTimers
  dart:isolate-patch/timer_impl.dart 429:5          _Timer._handleMessage
  dart:isolate-patch/isolate_patch.dart 184:12      _RawReceivePort._handleMessage
```

**Comment by yjbanov** [comment] 2023-09-01 00:52
Duplicate of https://github.com/flutter/flutter/issues/132654

**Closed by yjbanov** 2023-09-01 00:52 UTC
Labels: team-web
