### ISSUE TITLE
Numpad numbers in web app (in Linux web browsers)  are not working in textformfield

### ISSUE THREAD

**Issue by bhuphathi** [flutter/flutter#148629] opened 2024-05-19 03:23 UTC
Numpad numbers in web app (in Linux web browsers)  are not working in textformfield

_Originally posted by @bhuphathi in https://github.com/flutter/flutter/issues/145464#ref-issue-2304406040

**Comment by bhuphathi** [comment] 2024-05-19 03:32
Numpad numbers in web app (in Linux web browsers) are not working, after adding numpad navigation shortcuts for Linux [#145464](https://github.com/flutter/flutter/pull/145464)

**Comment by danagbemava-nc** [comment] 2024-05-20 07:45
Closing this as a duplicate of https://github.com/flutter/flutter/issues/148447

**Closed by danagbemava-nc** 2024-05-20 07:45 UTC
Labels: in triage
