### ISSUE TITLE
Positioned color disappears in mobile browser

### ISSUE THREAD

**Issue by Constans** [flutter/flutter#45607] opened 2019-11-26 12:13 UTC
This issue was introduced in version **1.11.0** and higher - **1.12.13** is still buggy (after upgrading from **1.10.16** - where it worked fine).

## Steps to Reproduce

1. Create a widget with this structure (or similar) - this is the exact one I use, but I think is something with the Card or Stack layout:
```
Widget build(BuildContext context) { 
  return Column(
    crossAxisAlignment: CrossAxisAlignment.start,
    children: <Widget> [
      Expanded(
        flex: 10,
        child: Card(
          margin: EdgeInsets.only(left: 9.0, right: 9.0),
          color: Colors.black12,
          child: Column( 
            children: <Widget>[
              SizedBox(
                height: 170,
                width: 240,
                child: Stack(
                  children: <Widget>[
                    Positioned.fill(
                      child: FadeInImage.assetNetwork(
                        image: pathToImage,
                        placeholder: 'images/transparent.png',
                        fit: BoxFit.cover,
                      ),
                    ),
                    Positioned(
                      top: 5.0,
                      left: 5.0,
                      child: Text(
                        'NEW',
                        textAlign: TextAlign.left
                      )
                    ),
                    Positioned(
                      top: 0,
                      right: 0,
                      child: IconButton(
                        icon: Icon(
                          Icons.search,
                          size: 36,
                        ),
                        color: Colors.white,
                        onPressed: () {
                          _launchURL(url, '_blank');
                        },
                      ),
                    ),
                    Positioned(
                      bottom: 0.0,
                      left: 0.0,
                      right: 0.0,
                      child: Container(
                        color: Colors.green,
                        padding: EdgeInsets.all(5.0),
                          child: Text(
                            'TEST', 
                            maxLines: 3,
                            style: TextStyle(fontSize: 13.0, color: Colors.white), 
                            textAlign: TextAlign.center
                        ),
                      ),
                    ),
                  ],
                ),
              ),
            ],
          ),
        ),
      ),
    ],
  );
}
```
2. Place a couple of these in a vertical scrolling list.
3. When you run / build and deployed with v 1.11.0 or higher the green overlay disappears at render time. 

**Target Platform:**
Web
**Target OS version/browser:**
macOS Catalina Version 10.15.1 (19B88) / 
Chrome Version 78.0.3904.108 (Official Build) (64-bit) (**happens only on mobile**)
**Devices:**
Chrome Version 78.0.3904.108 (Official Build) (64-bit)

## Logs

```
flutter doctor -v
[✓] Flutter (Channel unknown, v1.10.16, on Mac OS X 10.15.1 19B88, locale en-NL)
    • Flutter version 1.10.16 at /Users/constantins/development/flutter
    • Framework revision 798e4272a2 (3 weeks ago), 2019-11-06 21:04:17 -0500
    • Engine revision 34a40cfbfd
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/user/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    • CocoaPods version 1.8.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 40.2.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Ultimate Edition (version 2017.1.6)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 23.2.1
    • Dart plugin version 171.4694.29

[✓] Connected device (3 available)
    • User’s iPad • 308580731e7fc46b563fe33fe7bc60db5cb8b1ee • ios            • iOS 13.1.3
    • Chrome       • chrome                                   • web-javascript • Google Chrome 78.0.3904.108
    • Web Server   • web-server                               • web-javascript • Flutter Tools

• No issues found!
```

**Comment by iapicca** [comment] 2019-11-26 13:42
possible duplicate https://github.com/flutter/flutter/issues/45405

**Comment by Constans** [comment] 2019-11-26 14:00
It seems that in my case happened only in the mobile browser. In the desktop browser worked fine until the last tests (on 1.12.13). 
Versions 1.12.6 and up web builds became so unstable that I decided to play with 1.10.16 for a while (the last stable version for web as far as I've tested).
I suppose there are major changes happening across the framework and things get broken on the way.

**Comment by yjbanov** [comment] 2019-12-05 23:54
Currently we're pretty sure this is a duplicate, so I'll close it. But if it's not fixed feel free to reopen.

**Comment by yjbanov** [comment] 2019-12-05 23:54
Duplicate of https://github.com/flutter/flutter/issues/44845

**Closed by yjbanov** 2019-12-05 23:54 UTC
Labels: a: images, framework, severe: regression, ☸ platform-web
