### ISSUE TITLE
[tool_crash] FileSystemException: Failed to decode data using encoding 'utf-8', null

### ISSUE THREAD

**Issue by onetabsen** [flutter/flutter#141071] opened 2024-01-07 01:03 UTC
## Command
```
flutter gen-l10n --arb-dir=lib/assets/strings/intl/l10n --template-arb-file=intl_ru.arb --no-nullable-getter
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Failed to decode data using encoding 'utf-8', null
```
#0      _File._tryDecode (dart:io/file_impl.dart:615:7)
#1      _File.readAsStringSync (dart:io/file_impl.dart:624:7)
#2      ForwardingFile.readAsStringSync (package:file/src/forwarding/forwarding_file.dart:99:16)
#3      ErrorHandlingFile.readAsStringSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:218:22)
#4      _runSync (package:flutter_tools/src/base/error_handling_io.dart:590:14)
#5      ErrorHandlingFile.readAsStringSync (package:flutter_tools/src/base/error_handling_io.dart:217:12)
#6      new AppResourceBundle (package:flutter_tools/src/localizations/gen_l10n_types.dart:575:35)
#7      new AppResourceBundleCollection (package:flutter_tools/src/localizations/gen_l10n_types.dart:675:40)
#8      LocalizationsGenerator._allBundles (package:flutter_tools/src/localizations/gen_l10n.dart:548:56)
#9      LocalizationsGenerator._allBundles (package:flutter_tools/src/localizations/gen_l10n.dart)
#10     LocalizationsGenerator.loadResources.<anonymous closure> (package:flutter_tools/src/localizations/gen_l10n.dart:915:7)
#11     MappedIterator.moveNext (dart:_internal/iterable.dart:403:20)
#12     new _GrowableList._ofOther (dart:core-patch/growable_array.dart:202:26)
#13     new _GrowableList.of (dart:core-patch/growable_array.dart:152:26)
#14     new List.of (dart:core-patch/array_patch.dart:39:18)
#15     Iterable.toList (dart:core/iterable.dart:497:7)
#16     LocalizationsGenerator.loadResources (package:flutter_tools/src/localizations/gen_l10n.dart:921:8)
#17     generateLocalizations (package:flutter_tools/src/localizations/gen_l10n.dart:77:9)
#18     GenerateLocalizationsCommand.runCommand (package:flutter_tools/src/commands/generate_localizations.dart:260:11)
#19     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1662:12)
<asynchronous suspension>
#20     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1350:27)
<asynchronous suspension>
#21     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
```
```
[32m[✓][39m Flutter (Channel stable, 3.16.5, on Microsoft Windows [Version 10.0.19045.2728], locale ru-RU)
    [32m•[39m Flutter version 3.16.5 on channel stable at C:\dev\flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision 78666c8dc5 (3 weeks ago), 2023-12-19 16:14:14 -0800
    [32m•[39m Engine revision 3f3e560236
    [32m•[39m Dart version 3.2.3
    [32m•[39m DevTools version 2.28.4

[32m[✓][39m Windows Version (Installed version of Windows is version 10 or higher)

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    [32m•[39m Android SDK at C:\Users\PC\AppData\Local\Android\sdk
    [32m•[39m Platform android-34, build-tools 33.0.2
    [32m•[39m Java binary at: E:\Android Studio\jbr\bin\java
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[32m[✓][39m Visual Studio - develop Windows apps (Visual Studio Community 2022 17.8.3)
    [32m•[39m Visual Studio at E:\vs\ide
    [32m•[39m Visual Studio Community 2022 version 17.8.34330.188
    [32m•[39m Windows 10 SDK version 10.0.22621.0

[32m[✓][39m Android Studio (version 2023.1)
    [32m•[39m Android Studio at E:\Android Studio
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)

[32m[✓][39m VS Code (version 1.85.1)
    [32m•[39m VS Code at C:\Users\PC\AppData\Local\Programs\Microsoft VS Code
    [32m•[39m Flutter extension version 3.80.0

[32m[✓][39m Connected device (3 available)
    [32m•[39m Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19045.2728]
    [32m•[39m Chrome (web)      • chrome  • web-javascript • Google Chrome 120.0.6099.130
    [32m•[39m Edge (web)        • edge    • web-javascript • Microsoft Edge 120.0.2210.91

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[32m•[39m No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 78666c8dc57e9f7548ca9f8dd0740fbf0c658dc9

**Comment by danagbemava-nc** [comment] 2024-01-08 08:03
Closing this as a duplicate of https://github.com/flutter/flutter/issues/65021

**Closed by danagbemava-nc** 2024-01-08 08:03 UTC
Labels: in triage
