### ISSUE TITLE
Cannot run example projects

### ISSUE THREAD

**Issue by fralways** [flutter/flutter#15738] opened 2018-03-20 09:03 UTC
## Steps to Reproduce

I cloned your repository and opened (ex.) flutter_gallery example project in Android Studio.
When I go to pubspec.yaml flutter packages get fails with following message:
```
Running "flutter packages get" in flutter_gallery...
Package collection has no versions that match 1.14.5 derived from:
- async 2.0.6 depends on version ^1.5.0
- flutter 0.0.0 depends on version 1.14.5
- flutter_gallery depends on version 1.14.6
pub get failed (1)
```

I tried flutter packages upgrade - same error.
Flutter upgrade - Already up to date.
If I click on 'Get Dependencies' I get:
```
Resolving dependencies...
Package connectivity has no versions that match 0.3.0 derived from:
- flutter_gallery depends on version 0.3.0
```
Flutter doctor - 
```
[√] Flutter (Channel beta, v0.1.5, on Microsoft Windows [Version 10.0.16299.248], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[√] Android Studio (version 3.0)
[√] IntelliJ IDEA Ultimate Edition (version 2017.3)
[√] Connected devices (1 available)
```

Any idea how to fix this?

**Comment by zoechi** [comment] 2018-03-20 09:05
Might be a dup of #15318 ?

**Comment by fralways** [comment] 2018-03-20 09:21
You are correct, it was duplicate and switching to master channel did fix the issue (flutter channel master).
Examples are essential for us newbies and it was very frustrating for me that after a clean install official project did not work. My suggestion is to either add additional hint in error message or be sure that examples always build for beta channel.

**Comment by zoechi** [comment] 2018-03-20 11:09
@fralways I think it's pretty difficult to maintain instructions how to fix possible future bugs ;-)
Instead of trying to publish such instructions it's better to publish a fix (what has happened here), but all these things need to go through a process which takes time until it becomes available to all developers.

**Comment by fkorotkov** [comment] 2018-04-02 19:20
I think it's a different issue. I can reproduce it in CI on my fork of `flutter/flutter`: https://travis-ci.org/fkorotkov/flutter/jobs/361304260

Seems it's passing on the main repository because `$HOME/.pub-cache` is cached. I think there might be a regression in how flutter determines its version.

**Comment by DaveShuckerow** [comment] 2018-04-02 20:06
I am also getting this issue.  It happens when I build from the master branch of Flutter as well.

**Comment by fkorotkov** [comment] 2018-04-02 22:25
Here is a script to reproduce. It uses the same single branch clone as Travis CI does:

```
git clone --branch=master https://github.com/flutter/flutter.git flutter
cd flutter
./bin/flutter update-packages
```

**Comment by fkorotkov** [comment] 2018-04-03 01:32
I figured my fork thing out. I needed to rebase master of my fork and most importantly get the latest tag because Flutter uses it. Now it works.

**Comment by zoechi** [comment] 2018-07-02 06:41
I believe this is fixed now.

**Closed by zoechi** 2018-07-02 06:41 UTC
