### ISSUE TITLE
Add ability to compile a portable Windows exe

### ISSUE THREAD

**Issue by YazeedAlKhalaf** [flutter/flutter#81134] opened 2021-04-24 20:55 UTC
## Use case

I have this app called Flutter Installer made using Flutter which installs Flutter using a GUI. So the problem is telling somebody to install some app with its required files is a bit not appealing. I would rather have one `exe` that contains the required files and runs the app on its own. I am not sure how to do it but believe it is possible.

Flutter Installer: [https://github.com/YazeedAlKhalaf/Flutter_Installer](https://github.com/YazeedAlKhalaf/Flutter_Installer)

This would make it easier for people to run apps instead of creating installers. Gives them two options, and they go with whichever works for them.

## Proposal

Add a flag to `flutter build windows` that compiles the app as a portable version like this: `flutter build windows --portable`. This way inside the Release folder I get only one `exe` file that can be just clicked to run the app.

I am not sure if this can be done by putting files in the temp folder when starting the app then running from there. Or it would be like some other things related to Visual Studio maybe.

## Extra

Also if this wouldn't be made part of the framework can anybody share a way to export the flutter app as a portable, for Windows.

**Comment by stuartmorgan** [comment] 2021-04-24 22:38
Duplicate of https://github.com/flutter/flutter/issues/75200.

**Closed by stuartmorgan** 2021-04-24 22:38 UTC

**Comment by stuartmorgan** [comment] 2021-04-24 22:55
To clarify though, you are conflating two unrelated things: a portable application, and a single-file application. The former is not only possible, but exactly what the current build output produces. The latter is the duplicate, which is not possible.

A portable application is simply one that does not need an installer (so that it can be run from, say, a USB stick), and doesn't write data outside of its self-contained bundle. The build output is exactly that (assuming your so doesn't write data anywhere other than a relative location). Bundling it into an installer is a completely optional step, and the docs cover that.

**Comment by YazeedAlKhalaf** [comment] 2021-04-25 09:00
@stuartmorgan Thanks a lot for the clarification 🚀

**Comment by YazeedAlKhalaf** [comment] 2021-04-26 22:49
@stuartmorgan If you can help me on how to open the windows native folder in Visual Studio, in the same way we open the android folder in Android Studio. I am not really able to open the project, I never worked with Windows native apps so I have no clue on what to do and which folder to open, and how. Thanks in advance 🚀.
