### ISSUE TITLE
[firebase_admob] AdMob plugin shows wrong banner on iOS

### ISSUE THREAD

**Issue by orestesgaolin** [flutter/flutter#54438] opened 2020-04-10 10:12 UTC
## Steps to Reproduce

1. Create new project with AdMob on iOS, use test ad ids `ca-app-pub-4985116795725715~3065639438`, plugin version `0.9.3+1`
2. When app is running create 2 banners as follows:

```dart
      final targetingInfo = MobileAdTargetingInfo(
        childDirected: false,
        testDevices: <String>[],
      );

      final _banner1 = BannerAd(
        adUnitId: BannerAd.testAdUnitId,
        size: AdSize.mediumRectangle,
        targetingInfo: targetingInfo,
        listener: (event) {
          print(event);
        },
      );
      await _banner1.load();

      final _banner2 = BannerAd(
        adUnitId: BannerAd.testAdUnitId,
        size: AdSize.banner,
        targetingInfo: targetingInfo,
        listener: (event) {
          print(event);
        },
      );
      await _banner2.load();
```

3. When the ads are loaded (event is `MobileAdEvent.loaded` for both banners) show `_banner1` (`AdSize.mediumRectangle`).
4. Small banner is shown (`AdSize.banner`).

The same implementation works correctly on Android i.e. large banner `AdSize.mediumRectangle` is shown at the same stage.

**Expected results:** 

Large banner should be shown (`AdSize.mediumRectangle`)

**Actual results:** 

Small banner is shown (`AdSize.banner`) instead of large (`AdSize.mediumRectangle`)

<details>
  <summary>Logs</summary>

These are logs from my custom AdMobAdsManager that keeps references to banners and invokes 
load(), show() and dispose() methods on them. No information from AdMob plugin is visible in the log.

```
flutter: [AdMobAdsManager] Creating the AdSize.mediumRectangle banner. Test mode: true
flutter: [AdMobAdsManager] Loading the AdSize.mediumRectangle banner
flutter: [AdMobAdsManager] Loading AdSize.mediumRectangle banner result: true
flutter: [AdMobAdsManager] Creating the AdSize.banner banner. Test mode: true
flutter: [AdMobAdsManager] Loading the AdSize.banner banner
flutter: [AdMobAdsManager] BannerAd event for AdSize.mediumRectangle is MobileAdEvent.loaded
flutter: [AdMobAdsManager] Setting the banner AdSize.mediumRectangle as ready
flutter: [AdMobAdsManager] Loading AdSize.banner banner result: true
flutter: [AdMobAdsManager] BannerAd event for AdSize.banner is MobileAdEvent.loaded
flutter: [AdMobAdsManager] Setting the banner AdSize.banner as ready
flutter: [AdMobAdsManager] Showing the AdSize.mediumRectangle banner
// Small banner is shown on screen even though the reference is to large

```

Firebase Admob version:

```
  firebase_admob:
    dependency: "direct main"
    description:
      name: firebase_admob
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.9.3+1"
```

```
[✓] Flutter (Channel beta, v1.17.0, on Mac OS X 10.15.3 19D76, locale pl-PL)
    • Flutter version 1.17.0 at /Users/dominik/fvm/versions/beta
    • Framework revision d3ed9ec945 (4 days ago), 2020-04-06 14:07:34 -0700
    • Engine revision c9506cb8e9
    • Dart version 2.8.0 (build 2.8.0-dev.18.0 eea9717938)


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/dominik/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/dominik/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4, Build version 11E146
    • CocoaPods version 1.8.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.44.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1

[✓] Connected device (3 available)
    • iPhone (Dominik) • f96e187ec1f51b6be1830c7965a482dc653765d2 • ios            • iOS 13.4
    • Chrome           • chrome                                   • web-javascript • Google Chrome 80.0.3987.163
    • Web Server       • web-server                               • web-javascript • Flutter Tools

• No issues found!
```

</details>

**Comment by iapicca** [comment] 2020-04-13 08:30
Hi @orestesgaolin 
for what I can see the issue is related to a FlutterFire plugin.

If the flutterfire issue you linked isn't representative of your case
please open a new issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues).

Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
thank you

**Closed by iapicca** 2020-04-13 08:30 UTC
