### ISSUE TITLE
IFrame size changes issue on Chrome 91+ 

### ISSUE THREAD

**Issue by kubatatami** [flutter/flutter#83797] opened 2021-06-02 15:32 UTC
New chrome version 91+ doesn't send event to `window.visualViewport.onResize` listener inside IFrame. I am not sure is it a bug or intended behaviour but in result Flutter UI doesn't follow IFrame size changes what you can see here:

![iframe_chrome91+](https://user-images.githubusercontent.com/4519462/120508301-e4d4ed80-c3c7-11eb-9b0d-bcdf719c94ad.gif)

It works fine on safari and chrome <91:

![iframe_safari](https://user-images.githubusercontent.com/4519462/120508418-fcac7180-c3c7-11eb-9e90-276126a03ba7.gif)

Here is the line that should be probably modified:
https://github.com/flutter/engine/blob/b5f8141e9d39a638ba05b564a8477995ff9d2cc6/lib/web_ui/lib/src/engine/dom_renderer.dart#L623

Because it broke my production app I found an ugly workaround:
` 
html.window.onResize.listen((_) {
    html.window.visualViewport?.dispatchEvent(new html.Event('resize'));
});
`

**Comment by TahaTesser** [comment] 2021-06-03 10:57
Hi @kubatatami 
Can you please provide your `flutter doctor -v`, a complete reproducible minimal code sample, and complete `flutter run -- -d chrome verbose` logs running the minimal code sample?
Thank you

**Comment by kubatatami** [comment] 2021-06-03 11:54
Hi @TahaTesser 

Minimal code sample:
https://www.w3schools.com/code/tryit.asp?filename=GR6BLL782AMM

**Comment by slavap** [comment] 2021-06-04 03:04
@TahaTesser 
Confirming that I have the same problem with Chrome 91, and it is critical for my app as well.
Workaround that works for me:
```js
(function init() {
      window.addEventListener("resize", function() {
        var frame = document.getElementsByClassName("myFlutterFrame")[0];
        frame.contentWindow.visualViewport?.dispatchEvent(new Event('resize'));
        console.log('resize event sent to iframe');
      });
    })();
```

**Comment by TahaTesser** [comment] 2021-06-04 06:47
Hi @kubatatami 
Thanks for the details, it doesn't look like a Flutter issue but a chrome issue.
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-06-04 06:47 UTC
Labels: in triage
