### ISSUE TITLE
Engine fails to compile on windows due to un-included std::string

### ISSUE THREAD

**Issue by aykutkilic-avl** [flutter/flutter#116883] opened 2022-12-12 11:48 UTC
## Steps to Reproduce

1. Install VS2022 on windows 10.
2. Prepare development environment
3. Pull flutter from upstream in `src\flutter` folder
4. ´gclient sync´ in admin mode `engine\src` folder
5. `python flutter\tools\gn --unoptimized`
6. `ninja -C out\host_debug_unopt`

Please note that adding `#include <string>` to `ax_table_info.h` fixes this error:
![image](https://user-images.githubusercontent.com/74344355/207037495-1a07ed0d-7869-4701-b680-c4f117e27e72.png)

## Logs

<details>
<summary>Logs</summary>

```
```

```
```

</details>

```ninja -t msvc -e environment.x64 -- ../../buildtools/windows-x64/clang/bin/clang-cl.exe  /nologo /showIncludes @obj/flutter/third_party/accessibility/ax/ax.ax_table_info.obj.rsp /c ../../flutter/third_party/accessibility/ax/ax_table_info.cc /Foobj/flutter/third_party/accessibility/ax/ax.ax_table_info.obj /Fdobj/flutter/third_party/accessibility/ax/ax_cc.pdb

../../flutter/third_party/accessibility/ax/ax_table_info.h(100,8): error: no type named 'string' in namespace 'std'
  std::string ToString() const;
  ~~~~~^
1 error generated.
Note: including file: ../../flutter/third_party/accessibility/ax/ax_table_info.h
Note: including file:  C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.34.31933\include\map
Note: including file:   C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.34.31933\include\yvals_core.h
Note: including file:    C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.34.31933\include\vcruntime.h
Note: including file:     C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.34.31933\include\sal.h
Note: including file:      C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.34.31933\include\concurrencysal.h
Note: including file:     C:\git\engine\src\buildtools\windows-x64\clang\lib\clang\16.0.0\include\vadefs.h
Note: including file:      C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.34.31933\include\vadefs.h
Note: including file:    C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.34.31933\include\xkeycheck.h
Note: including file:   C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.34.31933\include\tuple
Note: including file:    C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.34.31933\include\__msvc_iter_core.hpp
Note: including file:     C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.34.31933\include\utility
Note: including file:      C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.34.31933\include\type_traits
Note: including file:       C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.34.31933\include\cstdint
Note: including file:        C:\git\engine\src\buildtools\windows-x64\clang\lib\clang\16.0.0\include\stdint.h
Note: including file:         C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.34.31933\include\stdint.h
Note: including file:       C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.34.31933\include\xstddef
Note: including file:        C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.34.31933\include\cstddef
Note: including file:         C:\git\engine\src\buildtools\windows-x64\clang\lib\clang\16.0.0\include\stddef.h
Note: including file:          C:\git\engine\src\buildtools\windows-x64\clang\lib\clang\16.0.0\include/__stddef_max_align_t.h
Note: including file:         C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.34.31933\include\xtr1common
Note: including file:        C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.34.31933\include\cstdlib
Note: including file:         C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt\math.h
Note: including file:          C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt\corecrt_math.h
Note: including file:           C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt\corecrt.h
Note: including file:         C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt\stdlib.h
Note: including file:          C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt\corecrt_malloc.h
Note: including file:          C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt\corecrt_search.h
Note: including file:           C:\git\engine\src\buildtools\windows-x64\clang\lib\clang\16.0.0\include\stddef.h
Note: including file:          C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt\corecrt_wstdlib.h
Note: including file:          C:\git\engine\src\buildtools\windows-x64\clang\lib\clang\16.0.0\include\limits.h
Note: including file:           C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.34.31933\include\limits.h
Note: including file:        C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.34.31933\include\initializer_list
Note: including file:   C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.34.31933\include\xtree
Note: including file:    C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.34.31933\include\xmemory
Note: including file:     C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.34.31933\include\limits
Note: including file:      C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.34.31933\include\cfloat
Note: including file:       C:\git\engine\src\buildtools\windows-x64\clang\lib\clang\16.0.0\include\float.h
Note: including file:        C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt\float.h
Note: including file:      C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.34.31933\include\climits
Note: including file:      C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.34.31933\include\cwchar
Note: including file:       C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.34.31933\include\cstdio
Note: including file:        C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt\stdio.h
Note: including file:         C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt\corecrt_wstdio.h
Note: including file:          C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt\corecrt_stdio_config.h
Note: including file:       C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt\wchar.h
Note: including file:        C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt\corecrt_memcpy_s.h
Note: including file:         C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt\errno.h
Note: including file:         C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.34.31933\include\vcruntime_string.h
Note: including file:        C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt\corecrt_wconio.h
Note: including file:        C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt\corecrt_wctype.h
Note: including file:        C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt\corecrt_wdirect.h
Note: including file:        C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt\corecrt_wio.h
Note: including file:         C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt\corecrt_share.h
Note: including file:        C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt\corecrt_wprocess.h
Note: including file:        C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt\corecrt_wstring.h
Note: including file:        C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt\corecrt_wtime.h
Note: including file:        C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt\sys/stat.h
Note: including file:         C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt\sys/types.h
Note: including file:      C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.34.31933\include\intrin0.h
Note: including file:       C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.34.31933\include\intrin0.inl.h
Note: including file:      C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.34.31933\include\isa_availability.h
Note: including file:     C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.34.31933\include\new
Note: including file:      C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.34.31933\include\exception
Note: including file:       C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.34.31933\include\yvals.h
Note: including file:        C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt\crtdbg.h
Note: including file:         C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.34.31933\include\vcruntime_new_debug.h
Note: including file:          C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.34.31933\include\vcruntime_new.h
Note: including file:        C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.34.31933\include\crtdefs.h
Note: including file:        C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.34.31933\include\use_ansi.h
Note: including file:     C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.34.31933\include\xatomic.h
Note: including file:     C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.34.31933\include\xutility
Note: including file:      C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.34.31933\include\cstring
Note: including file:       C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt\string.h
Note: including file:        C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt\corecrt_memory.h
Note: including file:    C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.34.31933\include\xnode_handle.h
Note: including file:   C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.34.31933\include\xpolymorphic_allocator.h
Note: including file:  C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.34.31933\include\set
Note: including file:  C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.34.31933\include\unordered_map
Note: including file:   C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.34.31933\include\xhash
Note: including file:    C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.34.31933\include\cmath
Note: including file:    C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.34.31933\include\list
Note: including file:    C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.34.31933\include\vector
Note: including file:    C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.34.31933\include\xbit_ops.h
Note: including file:  ../../flutter/third_party/accessibility/ax/ax_export.h
Note: including file: ../../flutter/third_party/accessibility/ax/ax_constants.h
Note: including file: ../../flutter/third_party/accessibility/ax/ax_enums.h
Note: including file: ../../flutter/third_party/accessibility/ax/ax_node.h
Note: including file:  C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.34.31933\include\memory
Note: including file:   C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.34.31933\include\iosfwd
Note: including file:   C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.34.31933\include\typeinfo
Note: including file:    C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.34.31933\include\vcruntime_typeinfo.h
Note: including file:     C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.34.31933\include\vcruntime_exception.h
Note: including file:      C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.34.31933\include\eh.h
Note: including file:       C:\git\engine\src\buildtools\windows-x64\clang\lib\clang\16.0.0\include\vadefs.h
Note: including file:       C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt\corecrt_terminate.h
Note: including file:  C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.34.31933\include\optional
Note: including file:   C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.34.31933\include\xsmf_control.h
Note: including file:  C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.34.31933\include\ostream
Note: including file:   C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.34.31933\include\ios
Note: including file:    C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.34.31933\include\xlocnum
Note: including file:     C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.34.31933\include\iterator
Note: including file:     C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.34.31933\include\streambuf
Note: including file:      C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.34.31933\include\xiosbase
Note: including file:       C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt\share.h
Note: including file:       C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.34.31933\include\system_error
Note: including file:        C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.34.31933\include\__msvc_system_error_abi.hpp
Note: including file:        C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.34.31933\include\cerrno
Note: including file:        C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.34.31933\include\stdexcept
Note: including file:         C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.34.31933\include\xstring
Note: including file:        C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.34.31933\include\xcall_once.h
Note: including file:        C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.34.31933\include\xerrc.h
Note: including file:        C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.34.31933\include\atomic
Note: including file:         C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.34.31933\include\xthreads.h
Note: including file:          C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.34.31933\include\xtimec.h
Note: including file:           C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.34.31933\include\ctime
Note: including file:            C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt\time.h
Note: including file:       C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.34.31933\include\xlocale
Note: including file:        C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.34.31933\include\xfacet
Note: including file:        C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.34.31933\include\xlocinfo
Note: including file:         C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.34.31933\include\__msvc_xlocinfo_types.hpp
Note: including file:         C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.34.31933\include\cctype
Note: including file:          C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt\ctype.h
Note: including file:         C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.34.31933\include\clocale
Note: including file:          C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt\locale.h
Note: including file:  C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.34.31933\include\string
Note: including file:  ../../flutter/third_party/accessibility\ax_build/build_config.h
Note: including file:  ../../flutter/third_party/accessibility/ax/ax_node_data.h
Note: including file:   ../../flutter/third_party/accessibility/ax/ax_base_export.h
Note: including file:   ../../flutter/third_party/accessibility/ax/ax_node_text_styles.h
Note: including file:   ../../flutter/third_party/accessibility/ax/ax_relative_bounds.h
Note: including file:    ../../flutter/third_party/accessibility\gfx/geometry/rect_f.h
Note: including file:     ../../flutter/third_party/accessibility\gfx/geometry/point_f.h
Note: including file:      ../../flutter/third_party/accessibility\gfx/gfx_export.h
Note: including file:      ../../flutter/third_party/accessibility\gfx/geometry/point.h
Note: including file:       ../../flutter/third_party/accessibility\base/numerics/clamped_math.h
Note: including file:        ../../flutter/third_party/accessibility\base/numerics/clamped_math_impl.h
Note: including file:         ../../flutter/third_party/accessibility\base/numerics/checked_math.h
Note: including file:          ../../flutter/third_party/accessibility\base/numerics/checked_math_impl.h
Note: including file:           ../../flutter/third_party/accessibility\base/numerics/safe_conversions.h
Note: including file:            ../../flutter/third_party/accessibility\base/numerics/safe_conversions_impl.h
Note: including file:           ../../flutter/third_party/accessibility\base/numerics/safe_math_shared_impl.h
Note: including file:            C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.34.31933\include\cassert
Note: including file:             C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt\assert.h
Note: including file:            ../../flutter/third_party/accessibility\base/numerics/safe_math_clang_gcc_impl.h
Note: including file:             C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.34.31933\include\cassert
Note: including file:              C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt\assert.h
Note: including file:       ../../flutter/third_party/accessibility\gfx/geometry/vector2d.h
Note: including file:        ../../flutter/third_party/accessibility\gfx/geometry/vector2d_f.h
Note: including file:     ../../flutter/third_party/accessibility\gfx/geometry/rect.h
Note: including file:      ../../flutter/third_party/accessibility\base/logging.h
Note: including file:       C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.34.31933\include\sstream
Note: including file:        C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.34.31933\include\istream
Note: including file:       ../../flutter/third_party/accessibility\base/macros.h
Note: including file:      ../../flutter/third_party/accessibility\gfx/geometry/size.h
Note: including file:       C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.34.31933\include\algorithm
Note: including file:       ../../flutter/third_party/accessibility\base/compiler_specific.h
Note: including file:       ../../flutter/third_party/accessibility\base/numerics/safe_math.h
Note: including file:     ../../flutter/third_party/accessibility\gfx/geometry/size_f.h
Note: including file:      ../../flutter/third_party/accessibility\base/compiler_specific.h
Note: including file:    ../../flutter/third_party/accessibility\gfx/transform.h
Note: including file:  ../../flutter/third_party/accessibility/ax/ax_tree_id.h
Note: including file:   ../../flutter/third_party/accessibility\base/no_destructor.h
Note: including file:   ../../flutter/third_party/accessibility\base/simple_token.h
Note: including file:    C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.34.31933\include\functional
Note: including file: ../../flutter/third_party/accessibility/ax/ax_role_properties.h
Note: including file: ../../flutter/third_party/accessibility/ax/ax_tree.h
Note: including file:  ../../flutter/third_party/accessibility/ax/ax_tree_data.h
Note: including file:   ../../flutter/third_party/accessibility/ax/ax_tree_id_registry.h
Note: including file:    ../../flutter/third_party/accessibility/ax/ax_action_handler.h
Note: including file:     ../../flutter/third_party/accessibility/ax/ax_action_handler_base.h
Note: including file:  ../../flutter/third_party/accessibility/ax/ax_tree_update.h
Note: including file:   ../../flutter/third_party/accessibility/ax/ax_enum_util.h
Note: including file:   ../../flutter/third_party/accessibility/ax/ax_event_intent.h
Note: including file:   ../../flutter/third_party/accessibility\base/string_utils.h
Note: including file: ../../flutter/third_party/accessibility/ax/ax_tree_observer.h```

**Comment by exaby73** [comment] 2022-12-13 10:42
Labeling this issue for further insights from the team

**Comment by chinmaygarde** [comment] 2023-01-09 19:14
Closing as duplicate of https://github.com/flutter/flutter/issues/116966 which tracks compilation issues with MSVC2022.

**Closed by chinmaygarde** 2023-01-09 19:14 UTC
Labels: severe: crash, engine, platform-windows
