### ISSUE TITLE
Can't start Alice HTTP Inspector. Please add NavigatorKey to your application

### ISSUE THREAD

**Issue by jigarparmar21** [flutter/flutter#60066] opened 2020-06-23 06:16 UTC
navigatorKey has already been added to the code, still it shows error(red line) under the navigatorKey.
 i have run individual Alice inspector once. it works properly , but i want to integrate alice in my existing code. so i can track the live http calls in app.
I have not get any alice package in pubspec.yaml

@override
Widget build(BuildContext context) {
return WillPopScope(
navigatorKey: _alice.getNavigatorKey(),
child: Theme(
data: ThemeData(
brightness: Brightness.light,
primarySwatch: AppColor.appColor,
primaryColor: AppColor.white,
buttonTheme: ButtonThemeData().copyWith(
buttonColor: AppColor.appColor,
textTheme: ButtonTextTheme.primary),
fontFamily: "EncodeSans",
),
child: layout()),

onWillPop: () {
return handleBackPress();
});
}

**Comment by iapicca** [comment] 2020-06-24 07:56
duplicate of https://github.com/flutter/flutter/issues/59972

**Closed by iapicca** 2020-06-24 07:56 UTC
