### ISSUE TITLE
[go_router] When scrolling the `nested_nav` example, you will get this exception: `The provided ScrollController is currently attached to more than one ScrollPosition.` 

### ISSUE THREAD

**Issue by nilsreichardt** [flutter/flutter#103922] opened 2022-05-16 19:34 UTC
## Steps to reproduce
1. Clone `packages` repo
2. Navigate to the `packages/go_router/example`
3. Run `flutter run -d chrome -t lib/nested_nav.dart`
4. Navigate to the "Hunting" tab
5. Scroll

## Demo
https://user-images.githubusercontent.com/24459435/168668229-29a03155-de3d-4dde-928c-a621e462055c.mov

## Logs
```
══╡ EXCEPTION CAUGHT BY ANIMATION LIBRARY ╞═════════════════════════════════════════════════════════
The following assertion was thrown while notifying status listeners for AnimationController:
The provided ScrollController is currently attached to more than one ScrollPosition.
The Scrollbar requires a single ScrollPosition in order to be painted.
When the scrollbar is interactive, the associated Scrollable widgets must have unique
ScrollControllers. The provided ScrollController must be unique to a Scrollable widget.

When the exception was thrown, this was the stack:
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 251:49      throw_
packages/flutter/src/widgets/scrollbar.dart 1508:9                                <fn>
packages/flutter/src/widgets/scrollbar.dart 1531:14                               [_debugCheckHasValidScrollPosition]
packages/flutter/src/widgets/scrollbar.dart 1445:14                               [_validateInteractions]
packages/flutter/src/animation/listener_helpers.dart 233:27                       notifyStatusListeners
packages/flutter/src/animation/animation_controller.dart 815:7                    [_checkStatusChanged]
packages/flutter/src/animation/animation_controller.dart 749:5                    [_startSimulation]
packages/flutter/src/animation/animation_controller.dart 612:12                   [_animateToInternal]
packages/flutter/src/animation/animation_controller.dart 461:12                   forward
packages/flutter/src/widgets/scrollbar.dart 1821:46                               [_handleScrollNotification]
packages/flutter/src/widgets/notification_listener.dart 130:22                    onNotification
packages/flutter/src/widgets/framework.dart 3078:18                               dispatchNotification
packages/flutter/src/widgets/framework.dart 3081:13                               dispatchNotification
packages/flutter/src/widgets/framework.dart 4375:24                               dispatchNotification
packages/flutter/src/widgets/notification_listener.dart 60:13                     dispatch
packages/flutter/src/widgets/scroll_activity.dart 94:90                           dispatchScrollUpdateNotification
packages/flutter/src/widgets/scroll_position.dart 900:5                           didUpdateScrollPositionBy
packages/flutter/src/widgets/scroll_position_with_single_context.dart 224:7       pointerScroll
packages/flutter/src/widgets/scrollable.dart 722:16                               [_handlePointerScroll]
packages/flutter/src/gestures/pointer_signal_resolver.dart 88:7                   resolve
packages/flutter/src/gestures/binding.dart 451:29                                 handleEvent
packages/flutter/src/gestures/binding.dart 425:14                                 dispatchEvent
packages/flutter/src/rendering/binding.dart 329:11                                dispatchEvent
packages/flutter/src/gestures/binding.dart 380:7                                  [_handlePointerEventImmediately]
packages/flutter/src/gestures/binding.dart 344:5                                  handlePointerEvent
packages/flutter/src/gestures/binding.dart 302:7                                  [_flushPointerEventQueue]
packages/flutter/src/gestures/binding.dart 285:32                                 [_handlePointerDataPacket]
lib/_engine/engine/platform_dispatcher.dart 1105:13                               invoke1
lib/_engine/engine/platform_dispatcher.dart 185:5                                 invokeOnPointerDataPacket
lib/_engine/engine/pointer_binding.dart 130:39                                    [_onPointerData]
lib/_engine/engine/pointer_binding.dart 295:14                                    [_handleWheelEvent]
lib/_engine/engine/pointer_binding.dart 559:7                                     <fn>
lib/_engine/engine/pointer_binding.dart 284:84                                    <fn>
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 334:14  _checkAndCall
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 339:39  dcall

The AnimationController notifying status listeners was:
  AnimationController#a16de(▶ 0.000)
════════════════════════════════════════════════════════════════════════════════════════════════════
Another exception was thrown: The provided ScrollController is currently attached to more than one ScrollPosition.
Another exception was thrown: The provided ScrollController is currently attached to more than one ScrollPosition.
Another exception was thrown: The provided ScrollController is currently attached to more than one ScrollPosition.
Another exception was thrown: The provided ScrollController is currently attached to more than one ScrollPosition.
Another exception was thrown: The provided ScrollController is currently attached to more than one ScrollPosition.
Another exception was thrown: The provided ScrollController is currently attached to more than one ScrollPosition.
Another exception was thrown: The provided ScrollController is currently attached to more than one ScrollPosition.
```

## Flutter Version
```
Flutter 3.0.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision ee4e09cce0 (7 days ago) • 2022-05-09 16:45:18 -0700
Engine • revision d1b9a6938a
Tools • Dart 2.17.0 • DevTools 2.12.2
```

**Comment by huycozy** [comment] 2022-05-17 08:49
Hi @nilsreichardt, thanks for filing the issue. 
I see there's an open issue addressing the case you described.
Closing as duplicate of #100264, so please follow up on it for further updates.

**Closed by huycozy** 2022-05-17 08:49 UTC
Labels: in triage

**Comment by nilsreichardt** [comment] 2022-05-17 09:05
Great, thanks @huycozy
