### ISSUE TITLE
Autocomplete options widget

### ISSUE THREAD

**Issue by The28AWG** [flutter/flutter#79227] opened 2021-03-28 14:04 UTC
## Use case
I noticed that there is a blank space in the autocomplete prompts. It seems to me that this is not correct.
<img width="348" alt="111995133-98a33c80-8b3e-11eb-83ff-06f90144b172" src="https://user-images.githubusercontent.com/1275371/112754983-275d0100-8ff8-11eb-9ef1-8c56d16e590c.png">
## Proposal
I replaced the widget in optionsViewBuilder with the code:

<details>
<summary>code sample</summary>

```dart
class _AutocompleteOptions<T extends Object> extends StatelessWidget {
  const _AutocompleteOptions({
    Key? key,
    required this.displayStringForOption,
    required this.onSelected,
    required this.options,
  }) : super(key: key);

  final AutocompleteOptionToString<T> displayStringForOption;

  final AutocompleteOnSelected<T> onSelected;

  final Iterable<T> options;

  @override
  Widget build(BuildContext context) {
    return Align(
      alignment: Alignment.topLeft,
      child: Material(
        elevation: 4.0,
        child: ConstrainedBox(
          constraints: BoxConstraints(
            maxHeight: 200,
          ),
          child: SingleChildScrollView(
            child: ListView.builder(
              shrinkWrap: true,
              physics: NeverScrollableScrollPhysics(),
              padding: EdgeInsets.zero,
              itemCount: options.length,
              itemBuilder: (BuildContext context, int index) {
                final T option = options.elementAt(index);
                return InkWell(
                  onTap: () {
                    onSelected(option);
                  },
                  child: Padding(
                    padding: const EdgeInsets.all(16.0),
                    child: Text(displayStringForOption(option)),
                  ),
                );
              },
            ),
          ),
        ),
      ),
    );
  }
}
```
</details>

Thus, we solve the problem of blank space.

**Comment by pedromassangocode** [comment] 2021-03-29 09:12
Hi @The28AWG 
Can you please provide your `flutter doctor -v` and a minimal complete reproducible code sample?
Thank you

**Comment by The28AWG** [comment] 2021-03-29 09:29
sample code from https://api.flutter.dev/flutter/material/Autocomplete-class.html , put "k" in text field:
```dart
/// Flutter code sample for Autocomplete

// This example shows how to create a very basic Autocomplete widget using the
// default UI.

import 'package:flutter/material.dart';

void main() => runApp(const AutocompleteExampleApp());

class AutocompleteExampleApp extends StatelessWidget {
  const AutocompleteExampleApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Autocomplete Basic'),
        ),
        backgroundColor: Colors.red, // set contrast background
        body: const Center(
          child: AutocompleteBasicExample(),
        ),
      ),
    );
  }
}

class AutocompleteBasicExample extends StatelessWidget {
  const AutocompleteBasicExample({Key? key}) : super(key: key);

  static const List<String> _kOptions = <String>[
    'aardvark',
    'bobcat',
    'chameleon',
  ];

  @override
  Widget build(BuildContext context) {
    return Autocomplete<String>(
      optionsBuilder: (TextEditingValue textEditingValue) {
        if (textEditingValue.text == '') {
          return const Iterable<String>.empty();
        }
        return _kOptions.where((String option) {
          return option.contains(textEditingValue.text.toLowerCase());
        });
      },
      onSelected: (String selection) {
        print('You just selected $selection');
      },
    );
  }
}
```
>  flutter doctor -v
[✓] Flutter (Channel master, 2.1.0-13.0.pre.261, on Linux, locale ru_RU.UTF-8)
    • Flutter version 2.1.0-13.0.pre.261 at /home/the28awg/Apps/flutter
    • Framework revision b44e536c62 (4 дня назад), 2021-03-24 23:09:02 -0700
    • Engine revision d59a01d2d3
    • Dart version 2.13.0 (build 2.13.0-150.0.dev)
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/the28awg/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /snap/android-studio/current/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.
> 
> [✓] Chrome - develop for the web
    • Chrome at google-chrome
> 
> [✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1
> 
> [✓] Android Studio (version 4.1)
    • Android Studio at /snap/android-studio/101/android-studio
    • Flutter plugin version 54.1.1
    • Dart plugin version 201.9335
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
> 
> [✓] Android Studio
    • Android Studio at /snap/android-studio/current/android-studio/
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /snap/android-studio/current/android-studio/
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
> 
> [✓] IntelliJ IDEA Ultimate Edition (version 2020.3)
    • IntelliJ at /snap/intellij-idea-ultimate/285
    • Flutter plugin version 54.1.4
    • Dart plugin version 203.7759
> 
> [✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Linux
    • Chrome (web)    • chrome • web-javascript • Google Chrome 89.0.4389.90
> 
> • No issues found!

**Comment by pedromassangocode** [comment] 2021-03-29 13:49
I was able to reproduce this issue.

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel master, 2.1.0-13.0.pre.294, on macOS 11.2.3 20D91 darwin-x64, locale en-AO)
    • Flutter version 2.1.0-13.0.pre.294 at /Users/pedromassango/Code/flutter_master
    • Framework revision a603714610 (20 hours ago), 2021-03-28 03:54:02 -0700
    • Engine revision b5e15d055d
    • Dart version 2.13.0 (build 2.13.0-162.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/pedromassango/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 54.0.3
    • Dart plugin version 203.7759

[✓] VS Code (version 1.54.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (3 available)
    • iPhone 11 Pro Max (mobile) • 7A82F29E-E49E-4B3C-8609-1570361DBC17 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)
    • macOS (desktop)            • macos                                • darwin-x64     • macOS 11.2.3 20D91 darwin-x64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 89.0.4389.90

! Doctor found issues in 1 category.
```

</details>

**Comment by HansMuller** [comment] 2021-03-29 16:08
CC @justinmc @shihaohong

**Comment by justinmc** [comment] 2021-03-29 17:25
When I wrote this I just hardcoded the height to 200 since I thought that looked alright in most cases ([link to the code](https://github.com/flutter/flutter/blob/a603714610f8c9c831e7d85071274460d70c18da/packages/flutter/lib/src/material/autocomplete.dart#L270)).  Maybe I could change it to a maximum height?  Then in your screenshot it would tightly wrap the three results, but if the list were very long, it wouldn't grow larger than 200.  What do you think of that @The28AWG?

**Comment by The28AWG** [comment] 2021-03-30 02:24
If the list is very long, then it may go beyond the screen. Therefore, the maximum height of the list is still needed, and it should not be too large for the convenience of working with small screens.
At the same time, if the list is very small, then the height of 200 is clearly not needed.

**Comment by The28AWG** [comment] 2021-03-30 02:33
Going beyond the screen is not the subject of this issue. But sometimes the height 200 may not fit the screen.

**Comment by The28AWG** [comment] 2021-03-30 02:38
At the very beginning, I suggested a way how I solved this problem for myself. Unfortunately, I cannot do something smarter than this.

**Comment by justinmc** [comment] 2021-03-31 20:34
Oh I see, sorry I missed that proposal.  If you're interested and have time, I think that would make a good PR, and I'd be happy to review.  You would also need a test.

If not then I can do it myself when I get around to it.

**Comment by The28AWG** [comment] 2021-03-31 21:04
I'm afraid my knowledge is not enough for PR.

**Comment by justinmc** [comment] 2021-03-31 21:10
No worries, I'll take a look at this later.

**Comment by The28AWG** [comment] 2021-04-06 09:58
If this helps anyone, here is my final version autocomplete:
<details>
<summary>autocomplete_field.dart</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';

class AutocompleteField<T> extends StatefulWidget {
  final AutocompleteOptionToString<T> displayStringForOption;
  final AutocompleteOptionsBuilder<T> optionsBuilder;
  final AutocompleteOnSelected<T> onSelected;
  final String labelText;

  const AutocompleteField({
    Key key,
    @required this.optionsBuilder,
    @required this.labelText,
    this.displayStringForOption = RawAutocomplete.defaultStringForOption,
    @required this.onSelected,
  }) : super(key: key);

  @override
  _AutocompleteFieldState<T> createState() => _AutocompleteFieldState<T>();
}

class _AutocompleteFieldState<T> extends State<AutocompleteField<T>> {
  Size childSize;

  @override
  Widget build(BuildContext context) => Autocomplete<T>(
        displayStringForOption: widget.displayStringForOption,
        optionsBuilder: widget.optionsBuilder,
        onSelected: widget.onSelected,
        optionsViewBuilder: (context, onSelected, options) =>
            _AutocompleteOptions(
          displayStringForOption: widget.displayStringForOption,
          onSelected: onSelected,
          options: options,
          constraints: BoxConstraints(
            maxHeight: 200.0,
            maxWidth: childSize?.width,
          ),
        ),
        fieldViewBuilder: (
          context,
          textEditingController,
          focusNode,
          onFieldSubmitted,
        ) =>
            MeasureSize(
                onChange: (size) => setState(() {
                      childSize = size;
                    }),
                child: TextFormField(
                  controller: textEditingController,
                  decoration: InputDecoration(
                    contentPadding: EdgeInsets.fromLTRB(
                      20.0,
                      10.0,
                      20.0,
                      10.0,
                    ),
                    border: OutlineInputBorder(),
                    labelText: widget.labelText,
                  ),
                  autovalidateMode: AutovalidateMode.onUserInteraction,
                  focusNode: focusNode,
                  onFieldSubmitted: (String value) {
                    onFieldSubmitted();
                  },
                )),
      );
}

class _AutocompleteOptions<T extends Object> extends StatelessWidget {
  const _AutocompleteOptions({
    Key key,
    @required this.displayStringForOption,
    @required this.onSelected,
    @required this.options,
    @required this.constraints,
  }) : super(key: key);

  final AutocompleteOptionToString<T> displayStringForOption;

  final AutocompleteOnSelected<T> onSelected;

  final Iterable<T> options;

  final BoxConstraints constraints;

  @override
  Widget build(BuildContext context) {
    return Align(
      alignment: Alignment.topLeft,
      child: Material(
        elevation: 4.0,
        child: ConstrainedBox(
          constraints: constraints,
          child: SingleChildScrollView(
            // height: 200.0,
            child: ListView.builder(
              shrinkWrap: true,
              padding: EdgeInsets.zero,
              itemCount: options.length,
              itemBuilder: (BuildContext context, int index) {
                final T option = options.elementAt(index);
                return InkWell(
                  onTap: () {
                    onSelected(option);
                  },
                  child: Padding(
                    padding: const EdgeInsets.all(16.0),
                    child: Text(displayStringForOption(option)),
                  ),
                );
              },
            ),
          ),
        ),
      ),
    );
  }
}

typedef OnWidgetSizeChange = void Function(Size size);

class MeasureSizeRenderObject extends RenderProxyBox {
  Size oldSize;
  final OnWidgetSizeChange onChange;

  MeasureSizeRenderObject(this.onChange);

  @override
  void performLayout() {
    super.performLayout();

    Size newSize = child.size;
    if (oldSize == newSize) return;

    oldSize = newSize;
    WidgetsBinding.instance.addPostFrameCallback((_) {
      onChange(newSize);
    });
  }
}

class MeasureSize extends SingleChildRenderObjectWidget {
  final OnWidgetSizeChange onChange;

  const MeasureSize({
    Key key,
    @required this.onChange,
    @required Widget child,
  }) : super(key: key, child: child);

  @override
  RenderObject createRenderObject(BuildContext context) {
    return MeasureSizeRenderObject(onChange);
  }
}
```
</details>

This code fixes this issue https://github.com/flutter/flutter/issues/78746

**Comment by maheshmnj** [comment] 2021-04-08 17:40
@justinmc  shouldn't the list take the full size(The full height of container lies in)?  hardcoding with a height certainly won't help. If could guide me on the expected behavior I would love to work on this.

**Comment by justinmc** [comment] 2021-04-08 20:37
I think the expected behavior is that the options list has a maximum height of 200, and beyond that it scrolls.  If the options take up less than 200px of height, then their container will match their height.

Some separate stuff mentioned in this issue that should probably be saved for later PRs:

  * We may want to make the max height configurable.
  * The overlay should be aware of its position relative to the edge of the screen, so if it's going to extend past the edge of the screen, it will display above the field instead of below.

**Comment by The28AWG** [comment] 2021-04-08 21:58
+ The options list should not be wider than the input field.

**Comment by maheshmnj** [comment] 2021-04-09 03:06
> I think the expected behavior is that the options list has a maximum height of 200, and beyond that it scrolls. If the options take up less than 200px of height, then their container will match their height.
> 
> Some separate stuff mentioned in this issue that should probably be saved for later PRs:
> 
> * We may want to make the max height configurable.
> * The overlay should be aware of its position relative to the edge of the screen, so if it's going to extend past the edge of the screen, it will display above the field instead of below.

okay got it can you assign this to me I would like to send a PR which basically fixes this

**Comment by maheshmnj** [comment] 2021-04-09 03:08
here's a sample demo

https://user-images.githubusercontent.com/31410839/114122849-c5ad6880-990e-11eb-8015-b75964c3df42.mov

**Comment by The28AWG** [comment] 2021-04-09 04:14
@maheshmnj do not ignore oversizing width the options list. see: https://github.com/flutter/flutter/issues/79227#issuecomment-813993684 and https://github.com/flutter/flutter/issues/78746

**Comment by maheshmnj** [comment] 2021-04-09 04:32
yes I saw that let me check how can I fix it

**Closed** 2021-05-20 16:04 UTC
Labels: f: material design, found in release: 2.1, framework, has reproducible steps
