### ISSUE TITLE
Text selection menu on iOS may attempt to draw invalid path and throw error

### ISSUE THREAD

**Issue by stx** [flutter/flutter#112140] opened 2022-09-22 02:12 UTC
We've seen a rare production issue on 3.3.0 on different iPhones, dating back to Flutter 2.x:

```
StateError: Bad state: Path.combine() failed.  This may be due an invalid path; in particular, check for NaN values.
  File "painting.dart", line 2657, in Path.combine
  File "text_selection_toolbar.dart", line 282, in _RenderCupertinoTextSelectionToolbarShape._clipPath
  File "text_selection_toolbar.dart", line 296, in _RenderCupertinoTextSelectionToolbarShape.paint
  File "object.dart", line 2796, in RenderObject._paintWithContext
  File "object.dart", line 155, in PaintingContext._repaintCompositedChild
  File "object.dart", line 98, in PaintingContext.repaintCompositedChild
  File "object.dart", line 1116, in PipelineOwner.flushPaint
  File "binding.dart", line 515, in RendererBinding.drawFrame
  File "binding.dart", line 884, in WidgetsBinding.drawFrame
  File "binding.dart", line 378, in RendererBinding._handlePersistentFrameCallback
  File "binding.dart", line 1175, in SchedulerBinding._invokeFrameCallback
  File "binding.dart", line 1104, in SchedulerBinding.handleDrawFrame
  File "binding.dart", line 1015, in SchedulerBinding._handleDrawFrame
  File "zone.dart", line 1391, in _rootRun
  File "zone.dart", line 1293, in _CustomZone.run
  File "zone.dart", line 1201, in _CustomZone.runGuarded
  File "hooks.dart", line 150, in _invoke
  File "platform_dispatcher.dart", line 318, in PlatformDispatcher._drawFrame
  File "hooks.dart", line 115, in _drawFrame
```

### Steps to Reproduce

Not certain, but seems like it may be due to SelectableText that's wrapping in a Flexible.

**Comment by LongCatIsLooong** [comment] 2022-09-22 03:13
Duplicate of https://github.com/flutter/flutter/issues/110076

**Closed by LongCatIsLooong** 2022-09-22 03:13 UTC
