### ISSUE TITLE
flutter upgrade/downgrade commands don't support the fixed target version.

### ISSUE THREAD

**Issue by JunhuaLin** [flutter/flutter#110744] opened 2022-09-01 03:24 UTC
## Steps to Reproduce

My Flutter current version 2.5.3 wanted to upgrade to 3.0.5 but went straight to the latest version 3.3.0！！！
<img width="565" alt="image" src="https://user-images.githubusercontent.com/20511081/187824631-43badebe-6a8e-4205-8a3c-5fc0cbc2d948.png">

```
flutter upgrade 3.0.5
flutter upgrade v3.0.5
flutter downgrade 3.0.5
flutter downgrade v3.0.5
```
Cannot be upgraded or downgraded to a specified version

## Logs

<details>
<summary>Logs</summary>

```
~ flutter doctor -v
[✓] Flutter (Channel stable, 3.3.0, on macOS 11.6 20G165 darwin-x64, locale
    zh-Hans-CN)
    • Flutter version 3.3.0 on channel stable at /Library/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffccd96b62 (2 days ago), 2022-08-29 17:28:57 -0700
    • Engine revision 5e9e0e0aa8
    • Dart version 2.18.0
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version
    32.0.0-rc1)
    • Android SDK at /Users/junhualin/Library/Android/sdk
    • Platform android-32, build-tools 32.0.0-rc1
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS
      development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.6 20G165 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 103.0.5060.114

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

</details>

**Comment by stuartmorgan** [comment] 2022-09-01 03:38
Closing as a duplicate of https://github.com/flutter/flutter/issues/71723

Currently neither `upgrade` nor `downgrade` take a version argument.

**Closed by stuartmorgan** 2022-09-01 03:38 UTC
