### ISSUE TITLE
[webview_flutter] Text is rendered outside of its boundary

### ISSUE THREAD

**Issue by XuanTung95** [flutter/flutter#100842] opened 2022-03-27 03:33 UTC
## Steps to Reproduce

 - There are 2 Flutter projects: web and android app (on tablet).
 - The app use webview_flutter to display web project.
 - Currently, text is rendered outside of its boundary in `webview_flutter: ^3.0.1`
 - It's OK when opening url in Chrome browser of the same machine.
 - It's OK when using `flutter_inappwebview` package

**Actual results:** 
 - **Specific device**: Galaxy Tab A, model SM-T515, Android 11
 - Output of `console.log(navigator.userAgent)`:
`"Mozilla/5.0 (Linux; Android 11; SM-T515 Build/RP1A.200720.012; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/99.0.4844.73 Safari/537.36", source:  (1)`
 
<img width="332" alt="Screen Shot 2022-03-27 at 09 54 30" src="https://user-images.githubusercontent.com/26743089/160264858-0a31f3fa-ef52-4e13-a33a-db83ea62165d.png">
<details>
<summary>Code sample</summary>

Web:

```
Scaffold(
  body: Center(
            child: Container(
              width: 400,
              color: Colors.green,
              child: Text(
                  "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", 
             style: TextStyle(fontSize: 18, color: Colors.black),),
            ),
          )
)
```

App:

```
WebView(
      javascriptMode: JavascriptMode.unrestricted,
      initialUrl: url,
    )
```

</details>

<details>
  <summary>Logs</summary>

```
[+5582 ms] I/ViewRootImpl@91a2323[MainActivity]( 8313): ViewPostIme pointer 0
[  +93 ms] I/ViewRootImpl@91a2323[MainActivity]( 8313): ViewPostIme pointer 1
[ +253 ms] I/flutter ( 8313): On View Created
[  +31 ms] W/libEGL  ( 8313): EGLNativeWindowType 0xb2877408 disconnect failed
[+4768 ms] I/chromium( 8313): [INFO:CONSOLE(1)] "Mozilla/5.0 (Linux; Android 11; SM-T515 Build/RP1A.200720.012; wv)
AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/99.0.4844.73 Safari/537.36", source:  (1)

```

</details>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.3, on macOS 11.4 20F71 darwin-x64, locale en)
[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.64.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

! Doctor found issues in 1 category.

```

**Comment by maheshmnj** [comment] 2022-03-28 12:01
Hi @XuanTung95, Thanks for filing the issue. I am able to see the text rendering outside the boundary of the container on Xioami k20 pro (Android 11) from the bottom when rendering the flutter web app in webview.  This issue isn't reproducible when running the same web app in chrome. Here's the deployed web app for quick reproduction https://text-overflow.netlify.app/

IOS             |  Android | Android Chrome
:-------------------------:|:-------------------------:|:-------------------------:
![Simulator Screen Shot - iPhone 12 Pro - 2022-03-28 at 17 24 01](https://user-images.githubusercontent.com/31410839/160392875-b2d34364-5be7-4804-bf1f-b51acacef529.png) | ![flutter_01](https://user-images.githubusercontent.com/31410839/160393012-6586c50c-e352-4df8-bf74-9c2b2c5ebb3d.png) | ![flutter_02](https://user-images.githubusercontent.com/31410839/160393354-79f21f04-e188-41e2-a00b-5114c541bab8.png)


<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);
  final String title;
  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;
  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: const WebView(
        initialUrl: 'https://text-overflow.netlify.app/#/',
        javascriptMode: JavascriptMode.unrestricted,
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}

```
</details> 

<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel stable, 2.10.4, on macOS 12.3 21E230 darwin-arm, locale en-GB)
    • Flutter version 2.10.4 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (3 days ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.65.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.37.20220301

[✓] Connected device (4 available)
    • Redmi K20 Pro (mobile) • 192.168.1.2:55555                    • android-arm64  • Android 11 (API 30)
    • iPhone 12 Pro (mobile) • 535317A4-921C-488F-B234-C2CC6D4AE5A1 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.3 21E230 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 99.0.4844.83

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

```
[✓] Flutter (Channel master, 2.13.0-0.0.pre.277, on macOS 12.3 21E230 darwin-arm, locale en-GB)
    • Flutter version 2.13.0-0.0.pre.277 at /Users/mahesh/Documents/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 13d2381109 (6 hours ago), 2022-03-27 21:00:08 -0400
    • Engine revision 559e259c54
    • Dart version 2.17.0 (build 2.17.0-246.0.dev)
    • DevTools version 2.11.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! CocoaPods 1.10.2 out of date (1.11.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin
        usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.65.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.37.20220301

[✓] Connected device (4 available)
    • Redmi K20 Pro (mobile) • 192.168.1.2:55555                    • android-arm64  • Android 11 (API 30)
    • iPhone 12 Pro (mobile) • 535317A4-921C-488F-B234-C2CC6D4AE5A1 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.3 21E230 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 99.0.4844.83

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```
</details>

**Comment by stuartmorgan** [comment] 2022-04-05 19:46
I don't see how this can be a plugin bug; we're just loading a page in the system-provided webview, and it's apparently rendering incorrectly. Re-triaging as a web bug.

**Comment by mdebbar** [comment] 2023-08-31 14:35
@XuanTung95 is this still an issue? There have been several fixes to text rendering since 2022.

**Comment by XuanTung95** [comment] 2023-08-31 16:25
I cannot test this. Could you self-test and close if it is fixed?

**Comment by yjbanov** [comment] 2023-09-01 18:41
Can this be deduplicated into https://github.com/flutter/flutter/issues/111352?

**Comment by mdebbar** [comment] 2023-09-01 18:50
Duplicate of https://github.com/flutter/flutter/issues/111352

**Closed** 2023-09-01 18:50 UTC
Labels: a: typography, platform-web, has reproducible steps, found in release: 2.10, found in release: 2.13, team-web
