### ISSUE TITLE
[local_auth] Android throws auth_error.notAvailable instead of showing Dialog to enable pin-code

### ISSUE THREAD

**Issue by LueNC** [flutter/flutter#134731] opened 2023-09-14 13:47 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing package issues](https://github.com/flutter/flutter/issues?q=is%3Aopen+is%3Aissue+label%3Apackage)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### What package does this bug report belong to?

local_auth

### What target platforms are you seeing this bug on?

Android

### Have you already upgraded your packages?

No

### Dependency versions

<details><summary>pubspec.lock</summary>

```lock
[Paste file content here]
```

</details>

### Steps to reproduce

1. Make sure pincode and biometrics are disabled
2. Call localAuth.authenticate()
3. It will crash and throw auth_error.notAvailable

This reminds me a lot of #96646 and might very well be the same issue. 

### Expected results

It should show the dialog for the user to add pin-code

### Actual results

It throws an error notAvailable.

### Code sample

<details><summary>Code sample</summary>

```dart
bool _authenticated = await localAuth.authenticate(
      localizedReason:
          isSetup ? Translations.biometrics.setUp.localization : Translations.biometrics.login.localization,
      authMessages: <AuthMessages>[
        iosStrings,
        androidString,
      ],
      options: const AuthenticationOptions(
        useErrorDialogs: true,
        stickyAuth: false,
        sensitiveTransaction: true,
        biometricOnly: true,
      ),
    );
```

</details>

### Screenshots or Videos

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.3.4, on macOS 13.4.1 22F770820d darwin-x64, locale
    en-DK)
    • Flutter version 3.3.4 on channel stable at
      /Users/lue/Documents/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision eb6d86ee27 (11 months ago), 2022-10-04 22:31:45 -0700
    • Engine revision c08d7d5efc
    • Dart version 2.18.2
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/lue/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 74.0.4
    • Dart plugin version 231.9161.14

[✓] VS Code (version 1.80.0)
    • VS Code at /Users/lue/Downloads/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • SM G960F (mobile) • 2174a6b8150d7ece • android-arm64  • Android 10 (API 29)
    • macOS (desktop)   • macos            • darwin-x64     • macOS 13.4.1
      22F770820d darwin-x64
    • Chrome (web)      • chrome           • web-javascript • Google Chrome
      117.0.5938.62

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

</details>

**Comment by danagbemava-nc** [comment] 2023-09-15 10:21
Hi @LueNC, this is indeed a duplicate of https://github.com/flutter/flutter/issues/96646. 

Kindly subscribe to the original issue for updates. 

Closing from here, thank you.

**Closed by danagbemava-nc** 2023-09-15 10:21 UTC
Labels: in triage
