### ISSUE TITLE
My flutter web project can run on higher  browser, but it can't work on lower level browser

### ISSUE THREAD

**Issue by chkkassd** [flutter/flutter#45251] opened 2019-11-20 13:16 UTC
## Steps to Reproduce

My flutter web project can run on android 6.x,but it can't work on android 4.4.2, and the browser is chrome 74.0.3729.157 and chrome 30.0.0.0, so I wanner know the minimum version supported by the browser.

**Target Platform: Web
**Target OS version/browser: chrome 74.0.3729.157 and chrome 30.0.0.0
**Devices:**

## Logs

```
```

```
```

```
[✓] Flutter (Channel dev, v1.10.14, on Mac OS X 10.15 19A602, locale zh-Hans-CN)
    • Flutter version 1.10.14 at /Users/petershi/Downloads/flutter
    • Framework revision 1946fc4da0 (6 周前), 2019-10-07 15:23:31 -0700
    • Engine revision 1d62160fdb
    • Dart version 2.6.0 (build 2.6.0-dev.1.0 d6c6d12ebf)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/petershi/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit
      https://flutter.dev/setup/#android-setup for detailed instructions.

[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    • CocoaPods version 1.8.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 40.1.2
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.40.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.6.0

[✓] Connected device (2 available)
    • Chrome          • chrome          • web-javascript • Google Chrome
      78.0.3904.97
    • Headless Server • headless-server • web-javascript • Flutter Tools
```

**Comment by iapicca** [comment] 2019-11-20 14:05
Hi @chkkassd 
if I understand correctly you are experiencing issues 
with both android 4.4.2 and and chrome 30.0.0
and your `flutter run --verbose` on the mentioned circumstances?
Also, to better address the issue, would be helpful
if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by chkkassd** [comment] 2019-11-20 14:55
> Hi @chkkassd
> if I understand correctly you are experiencing issues
> with both android 4.4.2 and and chrome 30.0.0
> and your `flutter run --verbose` on the mentioned circumstances?
> Also, to better address the issue, would be helpful
> if you could post a minimal code sample to reproduce the problem
> Thank you

hi,@iapicca
thanks for reply me.I just go home, so my computer is not with me.Tomorrow morning I will attach the output of flutter run --verbose.
In fact, my problem is that i create a flutter web project, and I flutter build web and then deploy it.Our company's app load the url, and in android 6.0 and later, it works well, however in another phone, android 4.4.2, it can't work，page cannot be rendered. So I wonder if it's related to the version of the browser kernel.
Thank you.

**Comment by iapicca** [comment] 2019-11-20 16:00
Hi @chkkassd
I apologize for the misunderstanding,
so there's no native app, only a PWA built with flutter web
that works as intended when running in Chrome on an Android 6.0,
but doesn't load in Chrome on and Android 4.4, am I correct?
thank you

**Comment by chkkassd** [comment] 2019-11-21 02:25
> Hi @chkkassd
> I apologize for the misunderstanding,
> so there's no native app, only a PWA built with flutter web
> that works as intended when running in Chrome on an Android 6.0,
> but doesn't load in Chrome on and Android 4.4, am I correct?
> thank you

Yes, you are correct. So I wonder if it's related to the version of the browser kernel and the version of Android?

**Comment by ferhatb** [comment] 2019-12-04 20:12
Hi @chkkassd , do you see error in console when you debug?

**Comment by chkkassd** [comment] 2019-12-13 09:15
> Hi @chkkassd , do you see error in console when you debug?

Hi,@ferhatb, when I debug in vscode, everything is ok,but when I run my project in old android phone in Android 4.4, it can't be rendered.

**Comment by ferhatb** [comment] 2019-12-16 22:04
@chkkassd   : Please setup chrome remote debugging, you should be able to see console on your desktop. Also make sure you are using --release version of your app.

**Comment by VladyslavBondarenko** [comment] 2020-01-10 09:07
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.

**Closed by VladyslavBondarenko** 2020-01-10 09:07 UTC
Labels: e: device-specific, waiting for customer response, ☸ platform-web
