### ISSUE TITLE
[webview_flutter] support onReceivedHttpAuthRequest for Basic Auth

### ISSUE THREAD

**Issue by letrungdo** [flutter/flutter#114876] opened 2022-11-08 07:50 UTC
My webview needs a proxy to access it. My proxy has basic authen.
I tried using InAppWebView with the following config and it works ok:
```dart
 onReceivedHttpAuthRequest: (controller, challenge) async {
        return HttpAuthResponse(
          username: "xxxx",
          password: "xxxx",
          action: HttpAuthResponseAction.PROCEED,
          permanentPersistence: true,
        );
      }
```
I'd be grateful if the team adds this feature.

**Comment by exaby73** [comment] 2022-11-08 09:41
Hello @letrungdo. If you're using Basic Auth, can't you just change the url to include the username and password like: `https://username:password@example.com`?

**Comment by letrungdo** [comment] 2022-11-25 12:17
@exaby73 You're right, I tried but it doesn't work.

**Comment by exaby73** [comment] 2022-11-25 13:57
Could you provide a [complete and minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) so that I may verify this issue?

**Comment by letrungdo** [comment] 2022-11-25 14:20
@exaby73 Sorry I'm pretty busy right now so I can't send you an example repo. I have now switched to using a proxy without basic authen. Since webview_flutter does not yet have an implementation of onReceivedHttpAuthRequest, you can refer to this document:
https://developer.android.com/reference/android/webkit/WebViewClient#onReceivedHttpAuthRequest(android.webkit.WebView,%20android.webkit.HttpAuthHandler,%20java.lang.String,%20java.lang.String)

**Comment by exaby73** [comment] 2022-11-28 07:25
Okay thanks for the docs. I'll label this issue as a valid proposal

**Comment by stuartmorgan** [comment] 2022-12-01 19:44
Duplicate of https://github.com/flutter/flutter/issues/83556

**Closed by stuartmorgan** 2022-12-01 19:44 UTC
Labels: new feature, plugin, p: first party, p: webview, proposal, r: duplicate
