### ISSUE TITLE
sendPlatformMessage to support error callback

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#6579] opened 2016-10-28 16:12 UTC
In [`ui.window.sendPlatformMessage`](https://github.com/flutter/engine/blob/master/lib/ui/window.dart#L219), we should have a way to pass an error callback.

Once we had that, in [`PlatformMessages._sendPlatformMessage`](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/services/platform_messages.dart#L49), we could wire it up so as to call `Completer.completeError()`

**Comment by abarth** [comment] 2016-10-28 16:16
Duplicate of #5962.  Feel free to grab #5962 from me if you're interested in implementing it.

**Closed by abarth** 2016-10-28 16:16 UTC
Labels: affects: engine, affects: services
