### ISSUE TITLE
flutter doctor --android-licenses

### ISSUE THREAD

**Issue by SavanRajyaguru** [flutter/flutter#83234] opened 2021-05-24 04:56 UTC
Hii, I show all website and Issues but the error is not solve.
**Installed java 15**

> ### flutter doctor --android-licenses

```
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
        at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
        at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
        at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 5 more
```

> ### flutter doctor -v
```
[√] Flutter (Channel dev, 2.3.0-0.1.pre, on Microsoft Windows [Version 10.0.19042.928], locale en-IN)
    • Flutter version 2.3.0-0.1.pre at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d72bfb8d07 (4 weeks ago), 2021-04-26 06:05:55 -0700
    • Engine revision de6e1adf97
    • Dart version 2.14.0 (build 2.14.0-18.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Savan Rajyaguru\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] VS Code (version 1.56.0)
    • VS Code at C:\Users\Savan Rajyaguru\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 90.0.4430.212
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 90.0.818.66

! Doctor found issues in 1 category.
```

![image](https://user-images.githubusercontent.com/65443618/119298329-70d56f80-bc7a-11eb-950d-9169dbe00cf3.png)

**Comment by junwha0511** [comment] 2021-05-24 06:37
You have to install Android SDK Command-line Tools!
After install the tool, you can  agree licenses:)

**Comment by TahaTesser** [comment] 2021-05-24 09:57
Hi @SavanRajyaguru 
This has been fixed by https://github.com/flutter/flutter/issues/80273

> You have to install Android SDK Command-line Tools!

Please install this and accept licenes
Closing as duplicate of  https://github.com/flutter/flutter/issues/80273
Thank you

**Closed by TahaTesser** 2021-05-24 09:57 UTC
Labels: in triage

**Comment by SavanRajyaguru** [comment] 2021-05-24 10:23
Hi @TahaTesser 
I installed Android SDK Command-line Tools It shows me this error

### flutter doctor --android-licenses

```
Error: Could not find or load main class Rajyaguru\AppData\Local\Android\Sdk\cmdline-tools\latest\bin\\..
Caused by: java.lang.ClassNotFoundException: Rajyaguru\AppData\Local\Android\Sdk\cmdline-tools\latest\bin\\//

```

**Comment by TahaTesser** [comment] 2021-05-24 10:40
@SavanRajyaguru 
`Rajyaguru\AppData\Local\Android\Sdk\cmdline-tools\` 
Delete `cmdline-tools` and download it manually from [here ](https://developer.android.com/studio), scroll all the way down until you `Command line tools only`

**Comment by SavanRajyaguru** [comment] 2021-05-24 10:57
@TahaTesser 
I download and set to this location `Rajyaguru\AppData\Local\Android\Sdk\` 
But when i run command `flutter doctor --android-licenses` it show me same error

```
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
        at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
        at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
        at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 5 more
```

**Comment by TahaTesser** [comment] 2021-05-26 13:32
@SavanRajyaguru 
Make sure you've not extracted Cmd tools into another Cmd tools folder
it should be like this `SDK\cmdline-tools\latest\bin`
