### ISSUE TITLE
Some flutter.io page are not readable on mobile

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#10120] opened 2017-05-16 18:31 UTC
See screenshot below. Note: It's impossible to scroll to the left to see the beginning of each line.

![screen shot 2017-05-16 at 11 29 29 am](https://cloud.githubusercontent.com/assets/1227763/26122038/014ee0b8-3a2b-11e7-9c91-5a2d5c658fd0.png)

Issue also present on real iOS device (tested on iPhone 6s).

/cc @sethladd @LarkAscending

**Comment by sethladd** [comment] 2017-05-16 18:32
thanks!

**Comment by LarkAscending** [comment] 2017-05-27 01:37
Likely related to #10153 ... only on iPhone and only specific pages.

**Comment by LarkAscending** [comment] 2017-05-31 23:22
Root cause is the following characters in the MD file:
` --some-string`

The issue is with double-dashes surrounded by single-grave characters, inline in a paragraph of text. That's the common trait.

In ios-setup.md, there's a single instance in the Install Xcode section. So that's easily fixed. In platform-plugins.md, there are multiple instances in the Create a platform plugin section and thus a full-on triage of the formatting in that section is called for...

My guess is the MD parser needs double-dashes escaped but won't let us escape them when they're inline-code-formatted.

**Comment by LarkAscending** [comment] 2017-06-01 01:08
@mit-mit It's an issue with forward slashes, which our MD parser interprets as escape characters. Here's the problem section in platform-plugins.md:
```
* `android/src/main/java/com/yourcompany/hello/HelloPlugin.java`:
   * The Android platform specific implementation of the plugin API.
* `ios/Classes/HelloPlugin.m`: 
   * The iOS platform specific implementation of the plugin API.
* `example/`:
   * A Flutter app that depends on the plugin, and illustrates how to use it.

By default, the plugin project uses Objective-C for iOS code and
Java for Android code. If you prefer Swift or Kotlin, you can specify the
iOS language using `-I` and the Android language using `-a`. For example:

```
flutter create --plugin -i swift -a kotlin hello
```

### Editing plugin source code {#edit-code}

#### Plugin API code (.dart)

To edit the Dart plugin API code, open `hello/` in IntelliJ IDEA (or your
favorite Dart editor). The plugin API is located in `lib/main.dart` shown in the 
Project view.

To run the plugin, you need to launch the plugin example app, which requires
defining a launch configuration:

1. Select **Run > Edit Configurations…**.
1. Select **+** and then **Flutter**.
1. In the Dart entrypoint field, enter `<plugin folder>/example/lib/main.dart`.
1. Select **OK**.
1. Launch the example app with **Run** or **Debug**.

*Note*: [Hot reload](https://flutter.io/faq/#hot-reload) is only supported for changes to Dart code, not for Android and iOS code. 

#### Android platform code (.java/.kt)

Before editing the Android platform code in Android Studio, first make sure that
the code has been built at least once by running the example app from IntelliJ, 
or running the following at the command line:

```
cd hello/example
flutter build apk
```

Next,

1. Launch Android Studio.
1. Select **Import project** in the Welcome screen, or select 
**File > New > Import Project…** in the menu, and navigate to the
`hello/example/android/build.gradle` file.
1. In the Gradle Sync dialog, select **OK**.
1. In the Android Gradle Plugin Update dialog, select **Don't remind me again for this project**. 

The Android platform code of your plugin is located in `hello/java/com.yourcompany.hello/HelloPlugin`.
```
Am now committing an incremental in-progress version of this file, with multiple formatting fixes (to exclude specific cases from troubleshooting). You'll want to start from this version.

The likely fix is some sort of automated syntax parsing via [kramdown options](https://kramdown.gettalong.org/syntax.html). To do this, you specify option(s) in _config.yml. They affect the whole site so need to be tested and rolled out carefully. It's worth playing with, though, rather than trying to figure out how to dance around the parser with each slash character....

**Comment by mit-mit** [comment] 2017-06-07 10:41
This is the same as https://github.com/flutter/flutter/issues/10153; closing as a dupe.

**Closed by mit-mit** 2017-06-07 10:41 UTC
Labels: dev: docs, dev: docs - website
