### ISSUE TITLE
Windows 7 desktop, flutter doctor crash

### ISSUE THREAD

**Issue by marinat** [flutter/flutter#40238] opened 2019-09-11 09:34 UTC
Installed flutter on windows 7 x64 sp1, enabled flutter desktop development, installed visual studio 2019, got this:
```
flutter doctor -v
[√] Flutter (Channel master, v1.10.2-pre.36, on Microsoft Windows [Version 6.1.7601], locale ru-RU)
• Flutter version 1.10.2-pre.36 at C:\flutter
• Framework revision 32c946f31b (6 hours ago), 2019-09-10 20:49:27 -0700
• Engine revision 7ea9884ab0
• Dart version 2.5.0 (build 2.5.0-dev.4.0 be66176534)

[X] Android toolchain - develop for Android devices
X Unable to locate Android SDK.
Install Android Studio from: https://developer.android.com/studio/index.html
On first launch it will assist you in installing the Android SDK components.
(or visit https://flutter.dev/setup/#android-setup for detailed instructions).
If the Android SDK has been installed to a custom location, set ANDROID_HOME to that location.
You may also want to add it to your PATH environment variable.


[☠] Visual Studio - develop for Windows (the doctor check crashed)
X Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know
about this issue at https://github.com/flutter/flutter/issues.
X type 'String' is not a subtype of type 'bool'
• #0 VisualStudio.isPrerelease (package:flutter_tools/src/windows/visual_studio.dart:40:7)
#1 VisualStudioValidator.validate (package:flutter_tools/src/windows/visual_studio_validator.dart:33:24)
<asynchronous suspension>
#2 asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
<asynchronous suspension>
#3 _rootRun (dart:async/zone.dart:1124:13)
#4 _CustomZone.run (dart:async/zone.dart:1021:19)
#5 _runZoned (dart:async/zone.dart:1516:10)
#6 runZoned (dart:async/zone.dart:1500:12)
#7 asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
#8 Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:151:11)
#9 Doctor.diagnose (package:flutter_tools/src/doctor.dart:244:41)
#10 _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#11 Doctor.diagnose (package:flutter_tools/src/doctor.dart:234:24)
#12 DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:59:39)
#13 _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#14 DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:45:42)
#15 FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:490:18)
#16 _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#17 _rootRunUnary (dart:async/zone.dart:1132:38)
#18 _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#19 _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#20 Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#21 Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#22 Future._completeWithValue (dart:async/future_impl.dart:522:5)
#23 Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552:7)
#24 _rootRun (dart:async/zone.dart:1124:13)
#25 _CustomZone.run (dart:async/zone.dart:1021:19)
#26 _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#27 _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#28 _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#29 _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#30 _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#31 _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)


[!] Android Studio (not installed)
• Android Studio not found; download from https://developer.android.com/studio/index.html
(or visit https://flutter.dev/setup/#android-setup for detailed instructions).

[√] Connected device (1 available)
• Windows • Windows • windows-x64 • Microsoft Windows [Version 6.1.7601]

! Doctor found issues in 3 categories.
```

**Comment by squeezeboxhuf** [comment] 2019-09-11 10:56
Same thing happening for me today - trying to set up Flutter Desktop, I just installed Visual Studio 2019 Community Edition, but flutter doctor not happy with exact same messages as above

**Comment by daimonkor** [comment] 2019-09-11 14:16
I found the same problem at Windows 10 http://prntscr.com/p4rxi4

**Comment by stuartmorgan** [comment] 2019-09-11 15:28
@franciscojma86 It looks like your mock data doesn't correspond to the actual JSON output from vswhere; you're using a bool for `productMilestoneIsPreRelease`, but, e.g., https://devblogs.microsoft.com/setup/new-vswhere-with-more-properties/ shows it as a string. (There's a top-level `isPrerelease` that is a bool; maybe we should be using that?)

**Comment by stuartmorgan** [comment] 2019-09-11 15:31
@franciscojma86  Also, I'm noticing that that output doesn't contain `isRebootRequired`, `isComplete`, or `isLaunchable`, which suggests they were added relatively recently. Given that, you should remove the assertions that they are present, and instead make the code default to returning the "good" answers for each of those keys if they are missing.

**Comment by franciscojma86** [comment] 2019-09-11 17:09
Fixing!

**Comment by daimonkor** [comment] 2019-09-11 17:53
@franciscojma86 Please write requirement visual studio components for desktop support. I mean C++ development and etc.

**Comment by stuartmorgan** [comment] 2019-09-11 18:14
> Please write requirement visual studio (2017 or 2019) components for desktop support. I mean C++ development and etc.

`flutter doctor` already provides that information (once the crash is fixed). If you check hash `f7d86a5b7950402f5f3e0ff1e2d51e0846b638cb` for instance, which is just before the regression, you'll see that.

**Comment by daimonkor** [comment] 2019-09-11 18:20
@stuartmorgan thanks, found http://prntscr.com/p4vcdi, but what components are needed?

**Comment by stuartmorgan** [comment] 2019-09-11 19:01
@daimonkor Ah, I see what you mean. Thanks for highlighting that flow issue; I filed #40267 to improve the way that's handled. (For now, the answer to your question is 'Desktop development with C++' workload with [these components](https://github.com/flutter/flutter/blob/362cde43ff35189810e198047c1c745286a7d271/packages/flutter_tools/lib/src/windows/visual_studio.dart#L104))

**Comment by daimonkor** [comment] 2019-09-11 19:36
@stuartmorgan thanks for help

**Comment by varunreddy3** [comment] 2019-09-12 02:36
It was working fine till yesterday. But I get this error when I updated flutter and Dart to use the newly release ffi features. Any fix for this yet?


`C:\Users\527980\Documents\flutterdesktop\flutter-desktop-embedding\example>flutter doctor -v
[√] Flutter (Channel master, v1.10.2-pre.36, on Microsoft Windows [Version 10.0.15063], locale en-US)
    • Flutter version 1.10.2-pre.36 at C:\src\flutter
    • Framework revision 32c946f31b (23 hours ago), 2019-09-10 20:49:27 -0700
    • Engine revision 7ea9884ab0
    • Dart version 2.5.0 (build 2.5.0-dev.4.0 be66176534)


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\527980\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[☠] Visual Studio - develop for Windows (the doctor check crashed)
    X Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know
      about this issue at https://github.com/flutter/flutter/issues.
    X type 'String' is not a subtype of type 'bool'
    • #0      VisualStudio.isPrerelease (package:flutter_tools/src/windows/visual_studio.dart:40:7)
      #1      VisualStudioValidator.validate (package:flutter_tools/src/windows/visual_studio_validator.dart:33:24)
      <asynchronous suspension>
      #2      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      <asynchronous suspension>
      #3      _rootRun (dart:async/zone.dart:1124:13)
      #4      _CustomZone.run (dart:async/zone.dart:1021:19)
      #5      _runZoned (dart:async/zone.dart:1516:10)
      #6      runZoned (dart:async/zone.dart:1500:12)
      #7      asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #8      Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:151:11)
      #9      Doctor.diagnose (package:flutter_tools/src/doctor.dart:244:41)
      #10     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
      #11     Doctor.diagnose (package:flutter_tools/src/doctor.dart:234:24)
      #12     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:59:39)
      #13     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
      #14     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:45:42)
      #15     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:490:18)
      #16     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
      #17     _rootRunUnary (dart:async/zone.dart:1132:38)
      #18     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
      #19     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
      #20     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
      #21     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
      #22     Future._completeWithValue (dart:async/future_impl.dart:522:5)
      #23     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552:7)
      #24     _rootRun (dart:async/zone.dart:1124:13)
      #25     _CustomZone.run (dart:async/zone.dart:1021:19)
      #26     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
      #27     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
      #28     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
      #29     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
      #30     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
      #31     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)


[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] IntelliJ IDEA Community Edition (version 2019.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.2
    • Flutter plugin version 38.2.4
    • Dart plugin version 192.6262.13

[√] VS Code, 64-bit edition (version 1.38.0)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.4.1

[√] Connected device (1 available)
    • Windows • Windows • windows-x64 • Microsoft Windows [Version 10.0.15063]

! Doctor found issues in 1 category.`

**Comment by stuartmorgan** [comment] 2019-09-12 02:55
> It was working fine till yesterday.

Yes, the cause of the regression (including the timing of when the change landed) is well understood.

> Any fix for this yet?

The PR linked above is the fix, it just hasn't landed yet. You can apply it locally if you absolutely need the latest master before it lands.

**Comment by mofada** [comment] 2019-09-12 03:48
Ok, it has been fixed, please update the `flutter upgrade` command.

```
Flutter 1.10.2-pre.52 • channel master • https://github.com/flutter/flutter.git
Framework • revision 270878fc50 (13 minutes ago) • 2019-09-11 20:29:27 -0700
Engine • revision da84d59f64
Tools • Dart 2.6.0 (build 2.6.0-dev.0.0 be66176534)
```

**Closed** 2019-09-12 04:03 UTC
Labels: a: desktop, severe: crash, t: flutter doctor, tool, ❖ platform-windows

**Comment by stuartmorgan** [comment] 2019-09-12 04:05
> please update the `flutter upgrade` command

I'm not sure what this means; if you have an issue with `flutter upgrade`, please file a new bug with details.

If your issue was that you still had this crash after running `flutter upgrade`, that is expected behavior, because the fix hadn't landed when you wrote that comment.

**Comment by mofada** [comment] 2019-09-12 04:34
> 我不确定这意味着什么; 如果您遇到问题`flutter upgrade`，请提交详细信息的新错误。

I mean, please update the flutter with `flutter upgrade`

**Comment by varunreddy3** [comment] 2019-09-12 06:09
Upgraded flutter. Failed to find windows executable name.

`C:\Users\527980\Documents\flutterdesktop\flutter-desktop-embedding\example>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, v1.10.2-pre.54, on Microsoft Windows [Version 10.0.15063], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Android Studio (version 3.5)
[√] IntelliJ IDEA Community Edition (version 2019.2)
[√] VS Code, 64-bit edition (version 1.38.0)
[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

C:\Users\527980\Documents\flutterdesktop\flutter-desktop-embedding\example>set ENABLE_FLUTTER_DESKTOP=true

C:\Users\527980\Documents\flutterdesktop\flutter-desktop-embedding\example>flutter clean
Deleting build...                                                  138ms
Deleting ephemeral...                                                3ms

C:\Users\527980\Documents\flutterdesktop\flutter-desktop-embedding\example>flutter run
Running "flutter pub get" in example...                             1.1s
Launching lib\main.dart on Windows in debug mode...
Building Windows application...
Failed to find Windows executable name`
