### ISSUE TITLE
BottomAppBar shape for FloatingActionButton.extended

### ISSUE THREAD

**Issue by Goolpe** [flutter/flutter#29835] opened 2019-03-23 09:20 UTC
Hello, I add BottomAppBar with FloatingActionButton and shape: CircularNotchedRectangle, it looks good, but if I add FloatingActionButton.extended, it looks [so](https://photos.app.goo.gl/Yk6psHpS7sUayvsb6).

flutter doctor -v
```
[√] Flutter (Channel dev, v1.3.13, on Microsoft Windows [Version 6.1.7601], locale ru-RU)
    • Flutter version 1.3.13 at C:\flutter
    • Framework revision 59ce7d6bff (5 days ago), 2019-03-18 11:20:10 -0700
    • Engine revision e75f6de01f
    • Dart version 2.2.1 (build 2.2.1-dev.1.1 None)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\Freedlee\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = C:\Users\Freedlee\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[√] VS Code (version 1.32.3)
    • VS Code at C:\Users\Freedlee\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 2.24.0

[√] Connected device (1 available)
    • Redmi Note 3 • 89ab2252 • android-arm64 • Android 6.0.1 (API 23)

• No issues found!
```

**Comment by JamesMcIntosh** [comment] 2019-07-10 08:35
@Goolpe Is this a duplicate of https://github.com/flutter/flutter/issues/21650

**Closed** 2019-07-10 09:43 UTC
Labels: f: material design, framework
