### ISSUE TITLE
[image_picker][Android]: Support Animated Gif with resizing option.

### ISSUE THREAD

**Issue by HyeokeunMun** [flutter/flutter#144546] opened 2024-03-04 16:45 UTC
### Use case

When picking a GIF image with maxWidth/maxHeight on Android, there's an issue where the animation of the file gets removed. 
It seems necessary to either add proper resizing logic for GIF files or, if that's difficult, to implement logic that returns the original file for GIFs.

Implementing logic to return the original file for GIFs should be straightforward, but since the plugins project is read-only now, I'll register this as an issue.

### Proposal

plugins/packages/image_picker/image_picker_android/android/src/main/java/io/flutter/plugins/imagepicker/
**ImageResizer.java: 33**

``` java
String resizeImageIfNeeded(
      String imagePath,
      @Nullable Double maxWidth,
      @Nullable Double maxHeight,
      @Nullable Integer imageQuality) {
    Bitmap bmp = decodeFile(imagePath);
    if (bmp == null) {
      return null;
    }
    boolean shouldScale = maxWidth != null || maxHeight != null || isImageQualityValid(imageQuality);
    if (!shouldScale) {
      return imagePath;
    }

    /// *The additional code
    /// Check if the file extension is "gif"
    String[] parts = imagePath.split("\\.");
    String extension = parts[parts.length - 1];
    if (extension.toLowerCase().equals("gif")) {
      /// Return the imagePath without any processing
      return imagePath;
    }
    ///

    try {
      String[] pathParts = imagePath.split("/");
      String imageName = pathParts[pathParts.length - 1];
      File file = resizedImage(bmp, maxWidth, maxHeight, imageQuality, imageName);
      copyExif(imagePath, file.getPath());
      return file.getPath();
    } catch (IOException e) {
      throw new RuntimeException(e);
    }
  }
```

**Comment by stuartmorgan** [comment] 2024-03-04 21:11
Closing as a duplicate of https://github.com/flutter/flutter/issues/34134

**Closed by stuartmorgan** 2024-03-04 21:11 UTC
