### ISSUE TITLE
Get building "Flutter Version" from program

### ISSUE THREAD

**Issue by dodatw** [flutter/flutter#72194] opened 2020-12-12 13:36 UTC
## Use case

Flutter has updated many stable versions in the past few months. (from 1.20 to 1.22.5)
We release our app based on many different versions of flutter. 
I want an easy way to easily query which version of flutter use when building the app. 

It will be very useful for us to clarify the problem.

Like "Platform.version", but that is Dart Version, not Flutter version.

## Proposal

Provide a api that can query flutter version or add a parameter flutterVersion in Platform. (ex: Platform.flutterVersion.)
The value like: "Flutter (Channel stable, 1.22.5)"

**Comment by jmagman** [comment] 2020-12-16 00:59
Duplicate of https://github.com/flutter/flutter/issues/26037

**Closed by jmagman** 2020-12-16 00:59 UTC
Labels: framework, passed first triage, proposal, severe: new feature, tool
