### ISSUE TITLE
build tools mac vs android development

### ISSUE THREAD

**Issue by rbucker** [flutter/flutter#41694] opened 2019-10-01 14:37 UTC
### background

I recently read an ISSUE that referred to android and iphone development and how upgrading gradle made the problem go away. ("taking too long") However, on my mac/iPhone setup gradle was never installed. Is it required or not for all platforms?

**Comment by escamoteur** [comment] 2019-10-01 15:15
What's the problem?

**Comment by rbucker** [comment] 2019-10-01 16:07
my project builds on my linux machine but when I cloned it to build for iPhone the project refused. Nothing but errors. While it did compile ONCE and RUN once I have no idea what I did in order to reproduce it. Since the baseline committed to GIT did not work I cannot even start there. Also since the tools modify the environment and not just the project I cannot start from scratch.

**Comment by jmagman** [comment] 2019-10-01 17:44
Setting up an Android development environment would not be required strictly for macOS/iOS development.  What errors were you seeing?  What does "project refused" mean?  What does  "tools modify the environment" mean (in what way?).

Steps to reproduce and a clear description of the errors you are seeing would be very helpful!

**Comment by rbucker** [comment] 2019-10-08 02:49
my project no longer builds and runs and I have not added any code. The only thing I have done is update flutter, dart, cocaopods, some xcode flags, and some android flags. Sadly the flutter environment is not stable enough for real work. I'm sure there are people who have working projects but the secret sauce is still locked up. Just not ready for ordinary people with real project time constraints.

**Comment by jmagman** [comment] 2019-10-08 02:54
What errors are you seeing when you saw "my project no longer builds and runs"?  What does "project refused" mean? What does "tools modify the environment" mean (in what way?).

We would like to help you track down your issues, particularly if they are the result of a serious Flutter bug.  However, we need more information to make this actionable.

**Comment by rbucker** [comment] 2019-10-09 01:20
I do not know if it's a flutter bug other than to say that once I included firebase into my base app the dev system starts to throw errors. When I repair them for ios they cause android to fail and when I fix them for android ios fails.

there has to be some STABLE configuration that just works.

**Comment by bernaferrari** [comment] 2019-10-09 01:22
The issues you are mentioning are really hard to reproduce. If it is that simple (i.e. including firebase into main app), could you just create an easy simple project that breaks and share here?

**Comment by rbucker** [comment] 2019-10-09 03:52
I'll see what I can do tomorrow... can someone provide a project template that uses firebase and works so that I can make sure it's not something not project related?

**Comment by escamoteur** [comment] 2019-10-09 08:58
@rbucker also some logs with error messages would be really helpful

**Comment by rbucker** [comment] 2019-10-09 18:58
this is the best starting point for ios, android with firebase.
https://blog.codemagic.io/firebase-authentication-google-sign-in-using-flutter/

**Comment by escamoteur** [comment] 2019-10-09 19:18
Can you build that project?

**Comment by rbucker** [comment] 2019-10-09 23:10
@escamoteur yes I can build this project... there are still some issues because that tutorial was for flutter 17... but there are some other tweeks that flutter failed to mention.... the project name needs to be simple when you ```flutter create``` because ios and android seem to behave differently with _ and -.  But that's just the start of my complaints

**Comment by rbucker** [comment] 2019-10-09 23:11
I need to try to port my project using this new knowledge... still not convinced it' gonna work... new info... gotta find all the references to com.example.

**Comment by escamoteur** [comment] 2019-10-10 06:44
Please always keep in mind this is a free open source project.
Cross platform dev can have it's quirk which anyone has to fight with. For limitations of the target OS like the project name has Flutter no responsibility. 
A lot of people here contribute and help for free on their spare time

**Comment by rbucker** [comment] 2019-10-10 10:28
While there are contributors who work without a salary; there is nothing free about flutter. This is clearly a play by google to be relevant. Also and more importantly it's the backend revenue from services like firebase not to mention the human capital. Just like google is not a marketing or advertising company. Or was that search.

**Comment by escamoteur** [comment] 2019-10-10 11:15
Still Flutter is free to use for you and you are not locked in in any way to paid Google services. Lately we had a Flutter project with Azure backend e.g.

**Comment by rbucker** [comment] 2019-10-10 16:51
I think you do not understand google's profit motive or business model. But this is way off topic.

**Comment by escamoteur** [comment] 2019-10-10 20:06
I will close this issue now as it looks like the problem is based on your project settings and not on the Flutter installation.
This site is not intended for individual support but to report bugs and propose new features.

**Closed** 2019-10-10 20:07 UTC
Labels: d: stackoverflow, t: gradle, tool
