### ISSUE TITLE
[Go_router] queryParameters is null on web

### ISSUE THREAD

**Issue by tas-unn** [flutter/flutter#137529] opened 2023-10-30 10:32 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

If I pass queryParameter in the browser's address bar, it always returns null.
http://localhost:60299/app?id=43

But if I follow a link in the code, everything is fine.
GoRouter.of(context).push( '/app?id=43')

### Expected results

id=43

### Actual results

returns null

### Code sample

<details><summary>Code sample</summary>

```dart
GoRoute(
                path: "app",
                builder: (BuildContext context, state) {
                  return  Wizard(
                      id: state.uri.queryParameters['id'] ==
                              null
                          ? null
                          : state
                              .uri
                              .queryParameters['id']!
                              .toString(),
                      
                    );}),
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.13.9, on Microsoft Windows [Version 10.0.19045.2311], locale ru-RU)
    • Flutter version 3.13.9 on channel stable at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d211f42860 (5 days ago), 2023-10-25 13:42:25 -0700
    • Engine revision 0545f8705d
    • Dart version 3.1.5
    • DevTools version 2.25.0

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at C:\Users\tyuntyaev\AppData\Local\Android\sdk
    • Platform android-34, build-tools 33.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.7.5)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.7.34202.233
    • Windows 10 SDK version 10.0.22621.0

[√] Android Studio (version 2022.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19045.2311]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 118.0.5993.89
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 118.0.2088.61

[√] Network resources
    • All expected network resources are available.

• No issues found!

```

</details>

**Comment by huycozy** [comment] 2023-10-30 10:59
Closing this as a duplicate of https://github.com/flutter/flutter/issues/137513. Please follow up on it for updates.

**Closed by huycozy** 2023-10-30 10:59 UTC
Labels: in triage
