### ISSUE TITLE
[tool_crash] OutOfMemoryError: (null)

### ISSUE THREAD

**Issue by CarlosS2022** [flutter/flutter#149144] opened 2024-05-27 21:14 UTC
## Command
```
flutter --no-color run --machine --track-widget-creation --device-id=emulator-5554 --start-paused --dart-define=flutter.inspector.structuredErrors=true lib\main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
OutOfMemoryError: (null)
```
#0      new Uint8List (dart:typed_data-patch/typed_data_patch.dart:2305:3)
#1      Uint8Buffer._createBuffer (package:typed_data/src/typed_buffer.dart:328:40)
#2      TypedDataBuffer._createBiggerBuffer (package:typed_data/src/typed_buffer.dart:259:12)
#3      TypedDataBuffer._ensureCapacity (package:typed_data/src/typed_buffer.dart:241:21)
#4      TypedDataBuffer._insertKnownLength (package:typed_data/src/typed_buffer.dart:209:5)
#5      TypedDataBuffer._addAll (package:typed_data/src/typed_buffer.dart:186:7)
#6      TypedDataBuffer.addAll (package:typed_data/src/typed_buffer.dart:91:5)
#7      HashSink.add (package:crypto/src/hash_sink.dart:79:18)
#8      _ByteAdapterSink.add (dart:convert/byte_conversion.dart:49:11)
#9      Hash.convert (package:crypto/src/hash.dart:28:15)
#10     _calculateSha (package:flutter_tools/src/android/gradle.dart:928:20)
#11     AndroidGradleBuilder.buildGradleApp (package:flutter_tools/src/android/gradle.dart:586:36)
#12     _rootRunUnary (dart:async/zone.dart:1407:47)
#13     _CustomZone.runUnary (dart:async/zone.dart:1308:19)
#14     _FutureListener.handleValue (dart:async/future_impl.dart:163:18)
#15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:847:45)
#16     Future._propagateToListeners (dart:async/future_impl.dart:876:13)
#17     Future._completeWithValue (dart:async/future_impl.dart:652:5)
#18     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:722:7)
#19     _rootRun (dart:async/zone.dart:1399:13)
#20     _CustomZone.run (dart:async/zone.dart:1301:19)
#21     _CustomZone.runGuarded (dart:async/zone.dart:1209:7)
#22     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1249:23)
#23     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
#24     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:185:5)
```
```
[✓] Flutter (Channel stable, 3.22.1, on Microsoft Windows [Versi¢n 10.0.22631.3593], locale es-CL)
    • Flutter version 3.22.1 on channel stable at C:\Users\joses\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a14f74ff3a (5 days ago), 2024-05-22 11:08:21 -0500
    • Engine revision 55eae6864b
    • Dart version 3.4.1
    • DevTools version 2.34.3

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\joses\AppData\Local\Android\sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✗] Visual Studio - develop Windows apps
    ✗ Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[!] Android Studio (version 2023.3)
    • Android Studio at C:\Users\joses\Android
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to determine bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] IntelliJ IDEA Ultimate Edition (version 2024.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2024.1.1
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 14 (API 34) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Versi¢n 10.0.22631.3593]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 125.0.6422.77
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 125.0.2535.67

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 3 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: a14f74ff3a1cbd521163c5f03d68113d50af93d3
### Plugins
flutter_native_splash-2.4.0
path_provider-2.1.3
path_provider_android-2.2.4
path_provider_foundation-2.4.0
path_provider_linux-2.2.1
path_provider_windows-2.2.1
url_launcher-6.2.6
url_launcher_android-6.3.2
url_launcher_ios-6.3.0
url_launcher_linux-3.1.1
url_launcher_macos-3.2.0
url_launcher_web-2.3.1
url_launcher_windows-3.1.1

**Comment by darshankawar** [comment] 2024-05-28 08:05
Closing this as a duplicate of https://github.com/flutter/flutter/issues/133371.

**Closed by darshankawar** 2024-05-28 08:05 UTC
Labels: in triage
