### ISSUE TITLE
AppBar 导致Widget 多次实例化 (AppBar causes Widget to be instantiated multiple times)

### ISSUE THREAD

**Issue by ksiventy** [flutter/flutter#41456] opened 2019-09-27 09:03 UTC
## Steps to Reproduce

1. ...  MaterialApp   routes  Or   Fluro
2. ... Navigator.of(context).pushNamed('second');
3. ... print>>>

## Logs
Console Print:

I/flutter (23802): >>>>>>    我是第二个页面
I/flutter (23802): State<MyHomePage>
I/flutter (23802): >>>>>>    我是第二个页面
I/flutter (23802): State<MyHomePage>

```
import 'package:fluro/fluro.dart';
import 'package:flutter/material.dart';
import 'package:flutter_app_19/routes.dart';

import 'application.dart';

void main() {
//  Router router = Router();
//  Routes.configureRoutes(router);
//  Application.router = router;

  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
      ),
      initialRoute: '/',
      routes: {
        'second':(context)=>SecondPage(),
      },
//      onGenerateRoute:Application.router.generator,
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      // This call to setState tells the Flutter framework that something has
      // changed in this State, which causes it to rerun the build method below
      // so that the display can reflect the updated values. If we changed
      // _counter without calling setState(), then the build method would not be
      // called again, and so nothing would appear to happen.
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    print('State<MyHomePage>');
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.display1,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
//        onPressed: _incrementCounter,
        onPressed: () {
//          Application.router.navigateTo(context, 'second');
          Navigator
              .of(context)
              .pushNamed('second');
        },
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}

class SecondPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    print('>>>>>>    我是第二个页面');
    return Scaffold(
      appBar: AppBar(
        title: Text(
          'Second',
        ),
        elevation: 0.0,
        centerTitle: true,
        leading: GestureDetector(
          child: Icon(Icons.keyboard_arrow_left),
          onTap: () => Navigator.pop(context),
        ),
      ),
      body: Container(child: Text('我是第二个页面')),
    );
  }
}
```

```
flutter analyze
Analyzing flutter_app_19...                                             

   info • Unused import: 'package:fluro/fluro.dart' • lib/main.dart:1:8 • unused_import
   info • Unused import: 'package:flutter_app_19/routes.dart' • lib/main.dart:3:8 • unused_import
   info • Unused import: 'application.dart' • lib/main.dart:5:8 • unused_import
   info • The declaration '_incrementCounter' isn't referenced • lib/main.dart:64:8 • unused_element

4 issues found. (ran in 3.6s)
```

```
flutter doctor -v
[✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Mac OS X 10.12.6 16G1815, locale zh-Hans-CN)
    • Flutter version 1.9.1+hotfix.2 at /Users/niuxiaowei/Development/flutter
    • Framework revision 2d2a1ffec9 (3 weeks ago), 2019-09-06 18:39:49 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/niuxiaowei/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = /Users/niuxiaowei/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • CocoaPods version 1.7.1

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 34.0.4
    • Dart plugin version 191.6183.88

[✓] VS Code (version 1.37.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.3.0

[✓] Connected device (1 available)
    • MIX 2 • 192.168.83.189:5555 • android-arm64 • Android 8.0.0 (API 26)

• No issues found!
```

**Comment by escamoteur** [comment] 2019-09-27 13:15
Hi could you please tell us in English what the problem is?

**Comment by iapicca** [comment] 2019-11-15 13:56
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of ' flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.

**Closed by iapicca** 2019-11-15 13:56 UTC
Labels: f: material design, framework, waiting for customer response
