### ISSUE TITLE
Why flutter run -d chrome can't fetch json url but flutter run -d windows can fetch

### ISSUE THREAD

**Issue by matekhong** [flutter/flutter#68752] opened 2020-10-22 02:07 UTC
I've create Board View List function by fetching json url via flutter When I run with  
**flutter run -d windows** it works properly as this below
![image](https://user-images.githubusercontent.com/17153200/96809252-b6ac2a00-1444-11eb-9fde-5171d247d222.png)

But when I run with **flutter run -d chrome** It is not working as below
![image](https://user-images.githubusercontent.com/17153200/96809411-03900080-1445-11eb-9cfd-971d196d7a8f.png)

Here this is my code 
![image](https://user-images.githubusercontent.com/17153200/96810015-a5175200-1445-11eb-91a0-bdca57d31fad.png)

I don't know is it because chrome cannot read from http://127.0.0.1 or not but even I tried with localhost or Computer's IP the result was same

**Comment by TahaTesser** [comment] 2020-10-22 09:24
Hu @matekhong 
Can you please provide your `flutter doctor -v` your `flutter run -d chrome --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by matekhong** [comment] 2020-10-27 07:07
### Flutter Doctor
[√] Flutter (Channel master, 1.22.0-2.0.pre.105, on Microsoft Windows [Version 10.0.18363.720], locale en-US)
    • Flutter version 1.22.0-2.0.pre.105 at C:\src\flutter
    • Framework revision cad4d1333e (9 weeks ago), 2020-08-27 17:48:05 -0700
    • Engine revision 77dd1c05b9
    • Dart version 2.10.0 (build 2.10.0-67.0.dev)

 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\matek\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.2)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30413.136
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.50.1)
    • VS Code at C:\Users\matek\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.15.1

[√] Connected device (4 available)
    • Windows (desktop) • windows    • windows-x64    • Microsoft Windows [Version 10.0.18363.720]
    • Web Server (web)  • web-server • web-javascript • Flutter Tools
    • Chrome (web)      • chrome     • web-javascript • Google Chrome 86.0.4240.111
    • Edge (web)        • edge       • web-javascript • Microsoft Edge 86.0.622.51

### Flutter run -d chrome --verbose
[ +110 ms] Could not find an option named "verboseflutter".

[  +14 ms] Run 'flutter -h' (or 'flutter <command> -h') for available flutter commands and options.
[   +6 ms] executing: git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +83 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] 158eadf2938918985b94cbb012cca43d0cb5baef
[   +1 ms] executing: git tag --points-at HEAD
[  +51 ms] Exit code 0 from: git tag --points-at HEAD
[   +2 ms] executing: git describe --match *.*.* --first-parent --long --tags
[  +50 ms] Exit code 128 from: git describe --match *.*.* --first-parent --long --tags
[   +1 ms] fatal: No names found, cannot describe anything.
[   +3 ms] Could not interpret results of "git describe": 
[   +2 ms] executing: git rev-parse --abbrev-ref HEAD
[  +41 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] master
[  +27 ms] ensureAnalyticsSent: 5ms
[   +2 ms] Running shutdown hooks
[   +1 ms] Shutdown hooks complete
[   +1 ms] exiting with code 64


### Source Code to reproduce

I've created build Widget that return FutureBuilder by fecthBoardList function
<pre><code>
@override
  Widget build(BuildContext context) {
    List<BoardList> _lists = List<BoardList>();
      return FutureBuilder(
        future: fetchBoardList(),
        builder: (context, snapshot){
        if(snapshot.hasData){
          List<MachineAllot> _listData = snapshot.data;
          for (int i = 0; i < _listData.length; i++) {
            print(_listData[i]);
            _lists.add(_createBoardList(_listData[i]));
          }
          return BoardView(
            lists: _lists,
            boardViewController: boardViewController,
          );
        } else {
          return CircularProgressIndicator();
        }
      }
    );
  }
</pre></code>

And this is fetchBoardList function use http.get to read rest api url (created by Django)

<pre><code>
Future<List<MachineAllot>> fetchBoardList() async {
  final response = await http.get('http://127.0.0.1:3000/drkoutei/machineallot/MILL/');
  if (response.statusCode == 200){
    Map<String, dynamic> map = json.decode(response.body);
    List<dynamic> responseJson = map["machineallot"];
    return responseJson.map((e) => new MachineAllot.fromJson(e)).toList();
  } else {
    throw Exception('error :(');
  }
}
</pre></code>

**Comment by TahaTesser** [comment] 2020-10-27 08:59
Hi @matekhong 
Your link is protected so it can't be even on windows so instead i used another public API link to test

<details> 
<summary>code sample</summary> 

```dart
import 'dart:convert';

import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: Container(
          child: Text('Hello World'),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: fetchBoardList,
      ),
    );
  }

  Future fetchBoardList() async {
    final response =
        await http.get('https://jsonplaceholder.typicode.com/todos/1');
    if (response.statusCode == 200) {
      Map map = json.decode(response.body);
      print(map);
    } else {
      throw Exception('error :(');
    }
  }
}

```

</details> 

Looks like you're on the older `master ` channel |
Can you please upgrade to the latest  `master ` and try again
`flutter channel master `
`flutter upgrade --force`
`flutter doctor -v`


If the problem persists, From what I can see, the issue is related to `http` plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/dart-lang/http/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by TahaTesser** 2020-10-27 08:59 UTC
Labels: in triage
