### ISSUE TITLE
Back button shows on AppBar while pushReplacement animates in

### ISSUE THREAD

**Issue by abbadabbatech** [flutter/flutter#13686] opened 2017-12-20 00:44 UTC
## Steps to Reproduce

I have pages that when an action is taken it pushes a route to goto another page, I use the code below:
```dart
Route route = new MaterialPageRoute(
        settings: new RouteSettings(name: "/PostAuthHome"),
        builder: (BuildContext context) => new PostAuthHome.PostAuthHome(title: "LOOP Home"),
      );
      Navigator.of(context).pushReplacement(route);
```
When I do the Appbar has a back button and should not.

## Flutter Doctor

```
[✓] Flutter (on Mac OS X 10.12.6 16G1036, locale en-US, channel master)
    • Flutter at /Users/dnetman99/flutter
    • Framework revision 0c09179b65 (10 days ago), 2017-12-09 22:04:06 -0800
    • Engine revision edb0201fa2
    • Tools Dart version 1.25.0-dev.11.0
    • Engine Dart version 2.0.0-edge.a38ac7cf127f4611c873c2f2d523c06ce06b1342

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.2)
    • Android SDK at /Users/dnetman99/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-26, build-tools 26.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.2
    • CocoaPods version 1.2.1

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] IntelliJ IDEA Ultimate Edition (version 2017.2.5)
    • Flutter plugin version 18.4
    • Dart plugin version 172.4343.25

[✓] Connected devices
    • Android SDK built for x86 • emulator-5554                        • android-x86 • Android 7.1.1 (API 25) (emulator)
    • iPhone 8                  • 1D8F1697-B7FC-4319-B06F-C0C3A9C9A626 • ios         • iOS 11.2 (simulator)

```

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

**Comment by zoechi** [comment] 2019-01-30 16:47
Looks like a duplicate of #12691

**Closed** 2019-01-30 16:51 UTC
Labels: f: material design, f: routes, framework
