### ISSUE TITLE
TabBarView offset when changing viewport from portrait to landscape

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#60288] opened 2020-06-25 14:52 UTC
b/159737324

Commit 98bc176 introduced a strange bug that remained undiscovered until now. To reproduce, run the following demo for tabs:

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(TabBarDemo());
}

class TabBarDemo extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: DefaultTabController(
        length: 3,
        child: Scaffold(
          appBar: AppBar(
            bottom: TabBar(
              tabs: [
                Tab(icon: Icon(Icons.directions_car)),
                Tab(icon: Icon(Icons.directions_transit)),
                Tab(icon: Icon(Icons.directions_bike)),
              ],
            ),
            title: Text('Tabs Demo'),
          ),
          body: TabBarView(
            children: [
              Icon(Icons.directions_car),
              Icon(Icons.directions_transit),
              Icon(Icons.directions_bike),
            ],
          ),
        ),
      ),
    );
  }
}
```

- Select the last tab (this is important; this does not reproduce for any other tab).
- Switch orientation from portrait to landscape.

You will see that the content of the last tab is offset quite a bit. You can scroll to the left to get the content back.

@Hixie FYI.

**Comment by Eimji** [comment] 2020-07-05 16:27
Hello,

I confirm the bug. Today, I have just discovered this issue with my application. I spent hours to debug my code... before finding this report on Github!

**Comment by Hixie** [comment] 2020-07-07 23:10
@Eimji Do you have a sample app we could look at that shows this problem?

**Comment by markusaksli-nc** [comment] 2020-07-20 13:50
Reproducible on the latest master `1.21.0-2.0.pre.66`.
<details>
 <summary>flutter doctor -v</summary>

 ```
[√] Flutter (Channel master, 1.21.0-2.0.pre.66, on Microsoft Windows [Version 10.0.18362.900], locale et-EE)
    • Flutter version 1.21.0-2.0.pre.66 at C:\Development\flutter_master
    • Framework revision 54c9441723 (3 days ago), 2020-07-17 18:56:12 -0400
    • Engine revision d327828632
    • Dart version 2.9.0 (build 2.9.0-21.0.dev 9dca49e71e)


[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at C:\Users\Isa\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: C:\Users\Isa\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.6.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.6.30309.148
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.0)
    • Android Studio at C:\Users\Isa\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.47.2)
    • VS Code at C:\Users\Isa\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.12.2

[√] Connected device (6 available)
    • SM G950F (mobile)           • ce12171c51cc001c03 • android-arm64  • Android 9 (API 28)
    • sdk gphone x86 (mobile)     • emulator-5554      • android-x86    • Android 11 (API 30) (emulator)
    • sdk gphone x86 arm (mobile) • emulator-5556      • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)           • windows            • windows-x64    • Microsoft Windows [Version 10.0.18362.900]
    • Web Server (web)            • web-server         • web-javascript • Flutter Tools
    • Chrome (web)                • chrome             • web-javascript • Google Chrome 84.0.4147.89

• No issues found!
```
</details>

**Comment by markusaksli-nc** [comment] 2020-07-20 14:04
<details>
 <summary>PageView sample from #61156, where scrolling back doesn't work</summary>

 ```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Pageview Orientation Bug',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: HomePage(),
    );
  }
}

class HomePage extends StatefulWidget {
  @override
  _HomePageState createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  int _page = 0;
  PageController _controller = PageController();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: PageView(
        controller: _controller,
        physics: NeverScrollableScrollPhysics(),
        children: [Page1(), Page2(), Page3(), Page4()],
      ),
      bottomNavigationBar: BottomNavigationBar(
        type: BottomNavigationBarType.fixed,
        currentIndex: _page,
        onTap: (page) {
          setState(() {
            _page = page;
          });
          _controller.jumpToPage(page);
        },
        items: [
          BottomNavigationBarItem(
            icon: Icon(Icons.library_books),
            title: Text(
              'Page 1',
            ),
          ),
          BottomNavigationBarItem(
            icon: Icon(Icons.event_note),
            title: Text(
              'Page 2',
            ),
          ),
          BottomNavigationBarItem(
            icon: Icon(Icons.pie_chart),
            title: Text(
              'Page 3',
            ),
          ),
          BottomNavigationBarItem(
            icon: Icon(Icons.more_horiz),
            title: Text(
              'Page 4',
            ),
          ),
        ],
      ),
    );
  }
}

class Page1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Page 1"),
      ),
    );
  }
}

class Page2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Page 2"),
      ),
    );
  }
}

class Page3 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Page 3"),
      ),
    );
  }
}

class Page4 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Page 4"),
      ),
    );
  }
}
```
</details>

**Comment by markusaksli-nc** [comment] 2020-07-20 14:20
Related issue with window resizing #60374.
<img src="https://user-images.githubusercontent.com/68219924/87948218-19d89a00-caad-11ea-9247-2e14ec27a6ef.gif" height="400" />

**Comment by rydmike** [comment] 2020-07-20 16:34
Same as reported in https://github.com/flutter/flutter/issues/61156#issuecomment-658523208
![TabBarViewResizeIssue](https://user-images.githubusercontent.com/39990307/87962494-f703b100-cabf-11ea-8781-c4e54e77ab07.gif)

**Comment by Eimji** [comment] 2020-08-06 10:31
Hello,

The bug is present with the latest stable version 1.20.0 of Flutter. When you have a TabBarView (and a bottom tabbar as menu), orientation from portrait to landscape makes the scroll offset lost his position. This is really a regression and annoying bug for applications which support the landscape mode...

**Comment by markusaksli-nc** [comment] 2020-08-06 11:02
Confirming as reproducible on the new stable `1.20.0`
<details>
 <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 1.20.0, on Mac OS X 10.15.6 19G73, locale en-GB)
    • Flutter version 1.20.0 at /Users/markus/development/flutter_stable
    • Framework revision 840c9205b3 (31 hours ago), 2020-08-04 20:55:12 -0700
    • Engine revision c8e3b94853
    • Dart version 2.9.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/markus/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Users/markus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6626763/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Users/markus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6626763/Android Studio.app/Contents
    • Flutter plugin version 48.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

 
[✓] Connected device (1 available)            
    • SM G950F (mobile) • ce12171c51cc001c03 • android-arm64 • Android 9 (API 28)

• No issues found!
```
</details>

Seems like a hotfix candidate but that's not for me to decide.

**Comment by Hixie** [comment] 2020-08-06 23:41
I think I have a fix for this.

**Comment by Hixie** [comment] 2020-08-06 23:53
Proposed fix: https://github.com/flutter/flutter/pull/63146

**Comment by tvolkert** [comment] 2020-08-07 07:00
Since this is a P2 regression, we should consider this for cherrypick into a 1.20 update.

**Comment by Eimji** [comment] 2020-08-11 07:59
Hello,
thanks for the fix, when will you release the fix for the stable channel?

**Comment by goderbauer** [comment] 2020-08-11 18:31
Since #63146 is submitted, should this be closed? What is left to do?

**Comment by rydmike** [comment] 2020-08-12 00:11
The fix also seem to have landed at least on (Channel master, 1.21.0-8.0.pre.170, because I cannot repeat the issue on master anymore at least.  Nice 😄 ! 

I tested on Android build doing the orientation rotation and Web with resize. Was going to test on a Windows build too, but for me Windows builds are broken on master (https://github.com/flutter/flutter/issues/63534) at the moment and I have not been able to resolve it yet, so I can't confirm it yet, but I assume it will work there to once I can build for Windows again.

**Comment by tvolkert** [comment] 2020-08-12 00:18
FYI, we're considering this for cherrypick into `1.20`, but since the fix just landed, and it's not trivial, we'd like to let it sit on master for a bit to make sure it didn't introduce any other regressions before cherrypicking it to stable.

**Comment by allanwolski** [comment] 2020-08-14 13:35
I expected to see this in 1.20.2.

We are waiting for this to release an update.

**Comment by kunit1** [comment] 2020-08-14 15:20
@allanwolski The fix got reverted on master it seems.

**Comment by tvolkert** [comment] 2020-08-14 16:28
The fix broke some automated customer tests and was reverted yesterday afternoon.  Re-opening this (sorry - forgot to re-open yesterday).

@goderbauer, given that @Hixie and @HansMuller are both OOO, do you have the bandwidth to look at the failures that caused this to be reverted and re-apply?

**Comment by rydmike** [comment] 2020-08-15 13:58
@tvolkert Understandable, still that's a pity, this is quite an annoying little bug. I hope the cause gets resolved and we can have it back soon. I think I will stay on a master channel rev that still has the fix for now. 

As this issue also has two other reports (https://github.com/flutter/flutter/issues/60374 and https://github.com/flutter/flutter/issues/61156) tracking this same problem, albeit from a bit different angle, their fix of course also got reverted. I think we can keep those issues closed as duplicates of this one. I'll drop a note on them to let anybody tracking those issues know that the fix has been reverted. Just in case they miss the mention via this comment. This being the first report of the issue those issues should have been closed as duplicates anyway.

**Comment by dannyvalentesonos** [comment] 2020-08-15 14:03
Same thing with #62209

**Comment by Hixie** [comment] 2020-08-18 19:26
This is a high priority issue.

**Comment by rs5173** [comment] 2020-08-28 16:24
+1.

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 1.20.1, on Microsoft Windows [Version 10.0.18362.836], locale zh-CN)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
[√] Android Studio (version 4.0)
[√] VS Code
[√] Connected device (1 available)

• No issues found!

**Comment by fpisidoro** [comment] 2020-08-29 15:05
I just switched to Channel master, 1.22.0-2.0.pre.129 and the bug still exists. Is that expected, or am I doing something wrong?

**Comment by dannyvalentesonos** [comment] 2020-08-31 21:51
@Hixie @goderbauer Do you have an update on this one? Thanks.

**Comment by Hixie** [comment] 2020-09-01 23:18
I need to try relanding my fix now that @mehmetf has fixed the Google side of things.

**Comment by pcsosinski** [comment] 2020-09-02 17:34
putting this on the 1.22 milestone so it's on our radar

**Comment by tvolkert** [comment] 2020-09-02 23:52
Re-application of fix out for review in https://github.com/flutter/flutter/pull/65135

**Comment by kw2019ltd** [comment] 2020-09-03 08:38
same issue pls fix it in the coming release flutter 1.20.4

**Closed** 2020-09-07 18:40 UTC
Labels: P2, customer: amplify, f: material design, f: scrolling, found in release: 1.20, found in release: 1.21, framework, has reproducible steps, severe: regression, waiting for PR to land (fixed)

**Comment by tvolkert** [comment] 2020-09-10 16:20
All, [the fix for this](https://github.com/flutter/flutter/commit/e10bdbbd9de69a79101d8e79030532ee2be58b89) was fairly complex, so as much as we'd like to get the fix to stable ASAP, cherry-picking it without going through the dev and beta channels first runs the risk of introducing new breakages.

The fix is currently on master and will be released to the dev and beta channels in the near future (in preparation for the next stable release).

**Comment by reddevil111296** [comment] 2020-09-21 12:30
@tvolkert wanted to know the status on this issue, has this been fixed in the latest flutter stable version(1.20.4) ?

**Comment by pcsosinski** [comment] 2020-09-21 16:37
@reddevil111296 due to the complexity of the change we're not planning to cherrypick it to the 1.20 release.  it is currently available on 1.22.0-12.1.pre in the beta channel.

**Comment by darylstone** [comment] 2020-09-21 16:50
@pcsosinski I just tested it on the recent beta version 1.22.0-12.1.pre and the issuedoesn't exists for me anymore. However, the issue still persists on the stable version as u said. :) Do you know on which version or when it might be able in stable or if there is an workaround for now?

**Comment by pcsosinski** [comment] 2020-09-21 16:53
@darylstone great, thanks.  our next stable release is coming in a few weeks, based on the 1.22 branch (so 1.22.0-12.1.pre+some cherrypicks will be our stable release.)

**Comment by darylstone** [comment] 2020-09-21 16:55
@pcsosinski That's awesome. Thank you! )))

**Comment by reddevil111296** [comment] 2020-09-21 18:29
@pcsosinski Thanks a lot for the update !!!
