### ISSUE TITLE
Slivertoboxadapter goes under SliverPersistentHeader

### ISSUE THREAD

**Issue by Lingeshwaran78** [flutter/flutter#135584] opened 2023-09-27 10:41 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

```dart
import 'dart:ui';

import 'package:flutter/material.dart';

void main() {
  runApp(const MaterialApp(
    title: 'Flutter Demo',
    debugShowCheckedModeBanner: false,
    home: HomePage(),
  ));
}

class HomePage extends StatefulWidget {
  const HomePage({Key? key}) : super(key: key);

  @override
  State createState() => _HomePageState();
}

class _HomePageState extends State {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.transparent,
      body: Material(
        elevation: 0.8,
        color: Colors.black,
        child: BackdropFilter(
          filter: ImageFilter.blur(sigmaX: 13, sigmaY: 13),
          child: ScrollConfiguration(
            behavior: const ScrollBehavior().copyWith(overscroll: false),
            child: CustomScrollView(
              slivers: [
                buildSliverPersistentHeader(context),
                buildSliverToBoxAdapter(),
              ],
            ),
          ),
        ),
      ),
    );
  }

  SliverPersistentHeader buildSliverPersistentHeader(BuildContext context) {
    return SliverPersistentHeader(
      pinned: true,
      floating: true,
      delegate: Widget1(
        max: MediaQuery.of(context).size.height * 0.75,
        min: MediaQuery.of(context).size.height * 0.5,
      ),
    );
  }

  SliverToBoxAdapter buildSliverToBoxAdapter() {
    return SliverToBoxAdapter(
      child: ScrollConfiguration(
        behavior: const ScrollBehavior().copyWith(overscroll: false),
        child: Container(
            decoration: const BoxDecoration(
              color: Colors.white,
              borderRadius: BorderRadius.only(
                topLeft: Radius.circular(23),
                topRight: Radius.circular(23),
              ),
            ),
            padding: const EdgeInsets.symmetric(horizontal: 16),
            child: Container(
              height: 700,
              width: MediaQuery.of(context).size.width,
              color: Colors.red,
            )),
      ),
    );
  }
}

class Widget1 extends SliverPersistentHeaderDelegate {
  double max;
  double min;
  Widget1({
    required this.max,
    required this.min,
  });

  @override
  Widget build(
      BuildContext context, double shrinkOffset, bool overlapsContent) {
    var progress = shrinkOffset / (200 - 50);
    progress = progress > 0 ? progress : 0;
    progress = progress > 1 ? 1 : progress;
    final avatarAlignTween1 = AlignmentTween(
      begin: const Alignment(0, 0.65),
      end: const Alignment(0, 0.25),
    );

    return Material(
      color: Colors.transparent,
      child: Stack(
        children: [
          const SizedBox(height: double.maxFinite),
          Positioned(
            left: 20,
            top: 50,
            child: GestureDetector(
              onTap: () => Navigator.pop(context),
              child: const Icon(
                Icons.close,
                color: Colors.white,
                size: 30,
              ),
            ),
          ),
          Align(
              alignment: avatarAlignTween1.lerp(progress),
              child: Container(height: 300, width: 300, color: Colors.white)),
        ],
      ),
    );
  }

  @override
  bool shouldRebuild(covariant SliverPersistentHeaderDelegate oldDelegate) {
    return true;
  }

  @override
  double get maxExtent => max;

  @override
  double get minExtent => min;
}

``` 

### Expected results

What I need is the sliver persistent header should goes under Sliverboxtoadapter

### Actual results

Sliverboxtoadapter goes under SliverPersistentHeader

### Code sample

<details><summary>Code sample</summary>
import 'dart:ui';
import 'package:flutter/material.dart';

class HomePage extends StatefulWidget {
  const HomePage({Key? key}) : super(key: key);

  @override
  State<HomePage> createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.transparent,
      body: Material(
        elevation: 0.8,
        color: Colors.black,
        child: BackdropFilter(
          filter: ImageFilter.blur(sigmaX: 13, sigmaY: 13),
          child: ScrollConfiguration(
            behavior: const ScrollBehavior().copyWith(overscroll: false),
            child: CustomScrollView(
              slivers: [
                buildSliverPersistentHeader(context),
                buildSliverToBoxAdapter(),
              ],
            ),
          ),
        ),
      ),
    );
  }

  SliverPersistentHeader buildSliverPersistentHeader(BuildContext context) {
    return SliverPersistentHeader(
      pinned: true,
      floating: true,
      delegate: Widget1(
        max: MediaQuery.of(context).size.height * 0.75,
        min: MediaQuery.of(context).size.height * 0.5,
      ),
    );
  }

  SliverToBoxAdapter buildSliverToBoxAdapter() {
    return SliverToBoxAdapter(
      child: ScrollConfiguration(
        behavior: const ScrollBehavior().copyWith(overscroll: false),
        child: Container(
            decoration: const BoxDecoration(
              color: Colors.white,
              borderRadius: BorderRadius.only(
                topLeft: Radius.circular(23),
                topRight: Radius.circular(23),
              ),
            ),
            padding: const EdgeInsets.symmetric(horizontal: 16),
            child: Container(
              height: 700,
              width: MediaQuery.of(context).size.width,
              color: Colors.red,
            )),
      ),
    );
  }
}

class Widget1 extends SliverPersistentHeaderDelegate {
  double max;
  double min;
  Widget1({
    required this.max,
    required this.min,
  });

  @override
  Widget build(
      BuildContext context, double shrinkOffset, bool overlapsContent) {

    var progress = shrinkOffset / (200 - 50);
    progress = progress > 0 ? progress : 0;
    progress = progress > 1 ? 1 : progress;
    final avatarAlignTween1 = AlignmentTween(
      begin: const Alignment(0, 0.65),
      end: const Alignment(0, 0.25),
    );

    return Material(
      color: Colors.transparent,
      child: Stack(
        children: [
          const SizedBox(height: double.maxFinite),
          Positioned(
            left: 20,
            top: 50,
            child: GestureDetector(
              onTap: () => Navigator.pop(context),
              child: const Icon(
                Icons.close,
                color: Colors.white,
                size: 30,
              ),
            ),
          ),
          Align(
              alignment: avatarAlignTween1.lerp(progress),
              child: Container(height: 300, width: 300, color: Colors.white)),
        ],
      ),
    );
  }

  @override
  bool shouldRebuild(covariant SliverPersistentHeaderDelegate oldDelegate) {
    return true;
  }

  @override
  double get maxExtent => max;

  @override
  double get minExtent => min;
}

</details>

### Screenshots or Video

https://github.com/flutter/flutter/assets/102861213/e15e67bd-4d3a-48b7-a9fa-195e48f051fc

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.7.3, on Microsoft Windows [Version 10.0.19045.3448], locale en-IN)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[√] Chrome - develop for the web
[√] Android Studio (version 2022.2)
[√] Connected device (5 available)
[√] HTTP Host Availability

! Doctor found issues in 1 category.
``` 

</details>

**Comment by dam-ease** [comment] 2023-09-27 12:34
Hi @Lingeshwaran78. Thanks for filing this. I see a similar/related issue which has been closed https://github.com/flutter/flutter/issues/62194. Can you check the suggestion out to see if it works in your case?

**Comment by Lingeshwaran78** [comment] 2023-09-27 12:47
I have already tried but doesn't work on my case. btw , thanks for the response

**Comment by dam-ease** [comment] 2023-09-28 08:02
Thanks for your response. I can reproduce this on the latest `master` and `stable` channels following the steps highlighted above.

<details><summary>stable, master flutter doctor -v</summary>
<p>

```
[✓] Flutter (Channel stable, 3.13.5, on macOS 13.0 22A380 darwin-arm64, locale
    en-NG)
    • Flutter version 3.13.5 on channel stable at
      /Users/damilolaalimi/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 12fccda598 (6 days ago), 2023-09-19 13:56:11 -0700
    • Engine revision bd986c5ed2
    • Dart version 3.1.2
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/damilolaalimi/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/damilolaalimi/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.82.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (5 available)
    • sdk gphone64 arm64 (mobile)     • emulator-5554                        •
      android-arm64  • Android 14 (API 34) (emulator)
    • iPhone 14 Pro Max (mobile)      • BB55E997-7F31-462D-B3B1-6B177D9B40C7 •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • iPad (10th generation) (mobile) • 5B1DA2B3-69EC-435B-95F8-550B7F3A9FBB •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)                 • macos                                •
      darwin-arm64   • macOS 13.0 22A380 darwin-arm64
    • Chrome (web)                    • chrome                               •
      web-javascript • Google Chrome 116.0.5845.187

[✓] Network resources
    • All expected network resources are available.

• No issues found!
``` 
```
[✓] Flutter (Channel master, 3.15.0-9.0.pre.4, on macOS 13.0 22A380 darwin-arm64, locale en-NG)
    • Flutter version 3.15.0-9.0.pre.4 on channel master at /Users/damilolaalimi/fvm/versions/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f6f18d0688 (5 hours ago), 2023-09-25 23:09:32 -0400
    • Engine revision 75950dc280
    • Dart version 3.2.0 (build 3.2.0-198.0.dev)
    • DevTools version 2.28.0-dev.12

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/damilolaalimi/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/damilolaalimi/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.82.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (5 available)
    • sdk gphone64 arm64 (mobile)     • emulator-5554                        • android-arm64  • Android 14 (API 34) (emulator)
    • iPhone 14 Pro Max (mobile)      • BB55E997-7F31-462D-B3B1-6B177D9B40C7 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • iPad (10th generation) (mobile) • 5B1DA2B3-69EC-435B-95F8-550B7F3A9FBB • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)                 • macos                                • darwin-arm64   • macOS 13.0 22A380 darwin-arm64
    • Chrome (web)                    • chrome                               • web-javascript • Google Chrome 116.0.5845.187

[✓] Network resources
    • All expected network resources are available.

• No issues found!
``` 

</p>
</details>

**Comment by Piinks** [comment] 2023-09-28 21:16
> What I need is the sliver persistent header should goes under Sliverboxtoadapter

Since the SliverPersistentHeader is pinned, the SliverToBoxAdaptor is scrolling under it as expected. This all appears to be working as expected, the header should not be rendering underneath the box adaptor. Can you share more about what behavior you are expecting?

Also, it may be helpful to simply the code reproduction. Our wiki discusses this in https://github.com/flutter/flutter/wiki/Issue-hygiene#provide-reduced-test-cases
> The best way to help us [debug an issue] is to provide code, [...] that has been reduced as far as possible (such that removing anything further stops showing the bug).

**Comment by Lingeshwaran78** [comment] 2023-09-29 06:14
"If I set pinned to false, my close icon and SliverPersistentHeader will scroll beyond the screen. What I'm expecting is that I want to scroll my box adapter above the SliverPersistentHeader."

**Comment by Piinks** [comment] 2023-09-29 17:08
> If I set pinned to false, my close icon and SliverPersistentHeader will scroll beyond the screen. What I'm expecting is that I want to scroll my box adapter above the SliverPersistentHeader.

Hi @Lingeshwaran78 these widgets are not intended to behave in this way.

I would recommend maybe trying a Stack with the Positioned widget to create the overlap behavior you are looking for.
This may be a good question for stackoverflow, or one of the other support channels like Slack listed on the website under Community: https://flutter.dev/community

Since this does not appear to be a bug, I am going to close this for now. Thank you!

**Closed by Piinks** 2023-09-29 17:08 UTC
Labels: f: material design, f: scrolling, has reproducible steps, team-design, found in release: 3.13, found in release: 3.15
