### ISSUE TITLE
starter flutter project unable to build app using Xcode 12.1 

### ISSUE THREAD

**Issue by anjan713** [flutter/flutter#71366] opened 2020-11-29 09:25 UTC
# Xcode 12 latest update 

I am unable to run the starter project counter app in Xcode 12.1 as soon as I have updated it to latest version
I am facing with three errors 

 
<img width="1792" alt="Screenshot 2020-11-29 at 2 48 01 PM" src="https://user-images.githubusercontent.com/40123185/100537853-f17a5c80-3251-11eb-8541-979b78a3b68c.png">

No issues found on flutter doctor

 I have searched for the solution in online but couldn't get it running on Xcode 

#Specifications
flutter sdk version 1.22.4
Xcode 12.1
Dart 2.10.4

It is running successfully on iOS emulator if the build occurs on vscode 

<img width="1792" alt="Screenshot 2020-11-29 at 2 52 09 PM" src="https://user-images.githubusercontent.com/40123185/100537967-c7756a00-3252-11eb-9dec-1a4db41aab62.png">

**Comment by aadarshadhakalg** [comment] 2020-11-30 10:07
Are you trying to do release build?

**Comment by anjan713** [comment] 2020-11-30 11:28
currently debug future release build

**Comment by aadarshadhakalg** [comment] 2020-11-30 11:35
I guess first you should use command
```
flutter build ios
``` 

and then only try to build in Xcode. Try this once. Not sure though.

**Comment by pedromassangocode** [comment] 2020-11-30 11:56
Hi @anjan713 
Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and your `pubspec.yaml`.
Thank you

**Comment by anjan713** [comment] 2020-12-01 14:01
this a basic starter project using flutter create app name . I have ran the three commands on flutter run --verbose I got red color text 

raj@MacBook-Pro ~ % flutter doctor -v
[✓] Flutter (Channel stable, 1.22.4, on Mac OS X 10.15.7 19H2 darwin-x64, locale
    en-IN)
    • Flutter version 1.22.4 at /Users/raj/flutter
    • Framework revision 1aafb3a8b9 (3 weeks ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4


[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/raj/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android Studio
      2.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio 2.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

---------------pub spec.yaml---------------------------------------------

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

-------------------------- flutter run --verbose ----------------------------

[  +17 ms] Artifact Instance of 'MaterialFonts' is not required,
skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required,
skipping update.
[        ] Artifact Instance of 'AndroidMavenArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not
required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not
required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required,
skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping
update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not
required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not
required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not
required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not
required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not
required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required,
skipping update.
[  +55 ms] No supported devices connected.
[  +11 ms] "flutter run" took 3,366ms.

------------------------- red color code---------------------------- 

[   +9 ms] 
           #0      throwToolExit
(package:flutter_tools/src/base/common.dart:14:3)
           #1      RunCommand.validateCommand
           (package:flutter_tools/src/commands/run.dart:353:7)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand

(package:flutter_tools/src/runner/flutter_command.dart:933:11)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure>

(package:flutter_tools/src/runner/flutter_command.dart:836:33)
           <asynchronous suspension>
           #4      FlutterCommand.run.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command.dart)
           #5      AppContext.run.<anonymous closure>
           (package:flutter_tools/src/base/context.dart:150:29)
           #6      _rootRun (dart:async/zone.dart:1190:13)
           #7      _CustomZone.run (dart:async/zone.dart:1093:19)
           #8      _runZoned (dart:async/zone.dart:1630:10)
           #9      runZoned (dart:async/zone.dart:1550:10)
           #10     AppContext.run
           (package:flutter_tools/src/base/context.dart:149:18)
           #11     FlutterCommand.run

(package:flutter_tools/src/runner/flutter_command.dart:825:20)
           #12     CommandRunner.runCommand
           (package:args/command_runner.dart:197:27)
           #13     FlutterCommandRunner.runCommand.<anonymous closure>

(package:flutter_tools/src/runner/flutter_command_runner.dart:335:21)
           #14     _rootRunUnary (dart:async/zone.dart:1198:47)
           #15     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #16     _FutureListener.handleValue
(dart:async/future_impl.dart:143:18)
           #17     Future._propagateToListeners.handleValueCallback
           (dart:async/future_impl.dart:696:45)
           #18     Future._propagateToListeners
           (dart:async/future_impl.dart:725:32)
           #19     Future._completeWithValue
(dart:async/future_impl.dart:529:5)
           #20     _AsyncAwaitCompleter.complete
           (dart:async-patch/async_patch.dart:40:15)
           #21     _completeOnAsyncReturn
           (dart:async-patch/async_patch.dart:311:13)
           #22     FlutterVersion.checkFlutterVersionFreshness
           (package:flutter_tools/src/version.dart)
           #23     _rootRunUnary (dart:async/zone.dart:1198:47)
           #24     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #25     _FutureListener.handleValue
(dart:async/future_impl.dart:143:18)
           #26     Future._propagateToListeners.handleValueCallback
           (dart:async/future_impl.dart:696:45)
           #27     Future._propagateToListeners
           (dart:async/future_impl.dart:725:32)
           #28     Future._completeWithValue
(dart:async/future_impl.dart:529:5)
           #29     Future._asyncCompleteWithValue.<anonymous closure>
           (dart:async/future_impl.dart:567:7)
           #30     _rootRun (dart:async/zone.dart:1190:13)
           #31     _CustomZone.run (dart:async/zone.dart:1093:19)
           #32     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #33     _CustomZone.bindCallbackGuarded.<anonymous closure>
           (dart:async/zone.dart:1037:23)
           #34     _microtaskLoop
(dart:async/schedule_microtask.dart:41:21)
           #35     _startMicrotaskLoop
(dart:async/schedule_microtask.dart:50:5)
           #36     _runPendingImmediateCallback
           (dart:isolate-patch/isolate_patch.dart:118:13)
           #37     _RawReceivePortImpl._handleMessage
           (dart:isolate-patch/isolate_patch.dart:169:5)
           
           
[   +6 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1

**Comment by pedromassangocode** [comment] 2020-12-01 14:15
I was able to reproduce this in the stable channel.

Steps:
1. Run `flutter create myapp`.
2. Open the myapp/ios folder with Xcode 12.1
3. Build.

Xcode will show the following logs:

```
Flutter.framework/Flutter: signed bundle with Mach-O universal (armv7 x86_64 arm64) [io.flutter.flutter]
error: Runner.app/Info.plist does not exist. The Flutter "Thin Binary" build phase must run after "Copy Bundle Resources".
```

<details><summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 1.22.4, on Mac OS X 10.15.7 19H2 darwin-x64, locale
    en)
    • Flutter version 1.22.4 at /Users/pedromassango/dev/SDKs/flutter_stable
    • Framework revision 1aafb3a8b9 (3 weeks ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.9.3

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin installed
    • Dart plugin version 202.8070

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (2 available)
    • Redmi 5 Plus (mobile)       • 0258ff700005  • android-arm64 • Android
      8.1.0 (API 27)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86   • Android 11
      (API 30) (emulator)

! Doctor found issues in 1 category.
```
</details>

**Comment by anjan713** [comment] 2020-12-01 16:19
that is the issue have you found solution

**Comment by pedromassangocode** [comment] 2020-12-02 07:20
No. You will get updated by GiHub once this is fixed!

**Comment by dexedrine-01** [comment] 2020-12-02 10:50
The same problem.

**Comment by jmagman** [comment] 2020-12-08 21:44
Duplicate of https://github.com/flutter/flutter/issues/70422

**Closed by jmagman** 2020-12-08 21:44 UTC
Labels: a: first hour, found in release: 1.22, has reproducible steps, platform-ios, severe: crash, t: xcode, tool
