### ISSUE TITLE
SkParagraph regresses time to first frame on iOS

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#97384] opened 2022-01-27 16:37 UTC
Starting with the Engine roll here https://github.com/flutter/flutter/commit/55e8a2cd5bc319f9aa9f28f7e3e68ec7672d4a04 containing only the SkParagraph flag flip, there is a big regression in time to first frame, and first frame build times on iOS.

https://flutter-flutter-perf.skia.org/e/?begin=1643075719&end=1643149114&keys=Xf98240cb6f1160c361037486d85f96fa&num_commits=50&request_type=1&xbaroffset=27306

On chat @jason-simmons wrote:

> SkShaper's font loader may be a major factor in the high cost of the initial text layout (https://github.com/google/skia/blob/main/modules/skshaper/src/SkShaper_harfbuzz.cpp#L266)
> SkShaper's create_hb_face is calling SkTypeface::openStream, and on iOS it appears that the openStream implementation is making copies of all of the font's tables.
> On Android it looks like the font data is being loaded on demand during calls to other HarfBuzz APIs used by create_hb_face.

**Comment by goderbauer** [comment] 2022-01-27 18:45
Maybe related: https://github.com/flutter/flutter/issues/94419

**Comment by jason-simmons** [comment] 2022-01-27 22:28
The SkShaper_harfbuzz `create_hb_face` function has another code path that calls `hb_face_create_for_tables` with a callback that loads font tables on demand.

This is similar to how Libtxt operates and avoids copying the complete font asset when loading fonts.

https://github.com/flutter/flutter/issues/69566 has some previous discussion about this.  In particular, loading the entire font can noticeably increase memory usage for large fonts such as emoji.

@bungeman @Rusino Would it make sense for SkShaper to provide a flag that Flutter could set on iOS that would opt into use of `hb_face_create_for_tables`?

**Comment by bungeman** [comment] 2022-01-27 22:42
No, a flag would be wrong. I don't have time to work on this right now, but we understand what needs to be done.

**Comment by zanderso** [comment] 2022-01-28 16:56
@jason-simmons @bungeman Is there a Skia issue we should cross-reference here, or is this github issue sufficient to track this?

**Comment by chinmaygarde** [comment] 2022-01-31 18:33
@heathmill: Is there anything we can do to elevate the priority of this issue? This regression may be severe enough to reconsider flipping the switch for the next stable release.

**Comment by Rusino** [comment] 2022-02-08 14:24
I submitted the fix yesterday (Feb, 7) to Skia main branch. It should be in Flutter now.

**Comment by zanderso** [comment] 2022-02-08 18:19
The Skia change has rolled through to the framework, but the benchmark has not recovered. Is there follow-up work needed in the Engine to use the new API? Should we re-assign this to @jason-simmons?

**Comment by Rusino** [comment] 2022-02-08 18:54
No, it should work without any changes.

**Comment by zanderso** [comment] 2022-02-08 19:17
To clarify, it looks like the memory benchmarks have recovered:

https://flutter-flutter-perf.skia.org/e/?begin=1644284719&end=1644314715&keys=X5844b97c0a37edd15278ccad36a0a878&num_commits=50&request_type=1&xbaroffset=27492

But the startup regression has not recovered:

https://flutter-flutter-perf.skia.org/e/?begin=1642718442&end=1644344757&keys=Xf98240cb6f1160c361037486d85f96fa&requestType=0&xbaroffset=27306

**Comment by Rusino** [comment] 2022-02-08 19:24
So, by not using all that extra memory we didn't save any time?

**Comment by jason-simmons** [comment] 2022-02-09 00:16
I've been unable to reproduce the performance issue.

I've tried various benchmarks (complex_layout_ios__start_up, flutter_gallery_ios__start_up, flutter_gallery_ios__transition_perf) but the metrics have been consistent between SkParagraph and Libtxt on the iPhone 7 that I have.

The devicelab is using an iPhone 6s - possibly this issue is device related?

The dashboard is not showing any issues for the Android benchmarks, so presumably this involves something specific to the iOS platform.  I can confirm that the `SkTypeface_Mac::onOpenStream` calls are no longer happening on the latest head.

**Comment by zanderso** [comment] 2022-02-09 00:19
@godofredoc Do we have any newer iPhones in the devicelab?

**Comment by godofredoc** [comment] 2022-02-09 00:33
No yet, we are planning to replace the 6s with iphone 11s but we haven't started creating the replacement plan.

**Comment by Rusino** [comment] 2022-02-10 15:41
So, what are we going to do with it? I don't have iPhone 6 available for testing, and I don't think that we should tune up our software for old devices...

**Comment by zanderso** [comment] 2022-02-10 22:55
Just to clarify, one of the selling points of Flutter is support for older devices, which is important for customers targeting NBU. That's why we have older devices in the lab. Data I could find is a little out of date, but suggests that iPhone 6s is still ~5% of users, which sounds small, but in absolute terms that's millions of people.

That's why I'm interested in at least determining the cause of the regression. @chinmaygarde do you or @bdero have an iPhone 6s handy, or know if we have one in the device library?

**Comment by bdero** [comment] 2022-02-10 23:46
I don't have a 6s on hand, but I went ahead and ordered one. I can repro/debug it on ~Feb 16th if we haven't figured it out by then.

**Comment by zanderso** [comment] 2022-02-10 23:57
@bdero cool. It'll be good to have one on hand. @jmagman has one as well, and mentioned that she'd take a stab at reproing.

**Comment by jmagman** [comment] 2022-02-11 02:56
Ran `complex_layout_ios__start_up` on iPhone 6s on baseline 7981bc47b13ab6a8f8043825a1b7232075526773 (last commit before SkParagraph as default):
Run 1:
```
    "engineEnterTimestampMicros": 12648761563,
    "timeToFrameworkInitMicros": 150091,
    "timeToFirstFrameRasterizedMicros": 544382,
    "timeToFirstFrameMicros": 226888,
    "timeAfterFrameworkInitMicros": 76797
```
Run 2:
```
    "engineEnterTimestampMicros": 12895897769,
    "timeToFrameworkInitMicros": 142967,
    "timeToFirstFrameRasterizedMicros": 538370,
    "timeToFirstFrameMicros": 221117,
    "timeAfterFrameworkInitMicros": 78149
```
Run 3:
```
    "engineEnterTimestampMicros": 13123936132,
    "timeToFrameworkInitMicros": 141089,
    "timeToFirstFrameRasterizedMicros": 538101,
    "timeToFirstFrameMicros": 221742,
    "timeAfterFrameworkInitMicros": 80653
```

_______
Same test on 55e8a2cd5bc319f9aa9f28f7e3e68ec7672d4a04 (the first commit with SkParagraph as the default):

Run 1:
```
    "engineEnterTimestampMicros": 11360955093,
    "timeToFrameworkInitMicros": 145250,
    "timeToFirstFrameRasterizedMicros": 540088,
    "timeToFirstFrameMicros": 229748,
    "timeAfterFrameworkInitMicros": 84497
```
Run 2:
```
    "engineEnterTimestampMicros": 11893867449,
    "timeToFrameworkInitMicros": 160863,
    "timeToFirstFrameRasterizedMicros": 550930,
    "timeToFirstFrameMicros": 267791,
    "timeAfterFrameworkInitMicros": 106928
```
Run 3:
```
    "engineEnterTimestampMicros": 13428308057,
    "timeToFrameworkInitMicros": 150290,
    "timeToFirstFrameRasterizedMicros": 540590,
    "timeToFirstFrameMicros": 242057,
    "timeAfterFrameworkInitMicros": 91766
```
Run 4 for luck:
```
    "engineEnterTimestampMicros": 13694916840,
    "timeToFrameworkInitMicros": 142149,
    "timeToFirstFrameRasterizedMicros": 532832,
    "timeToFirstFrameMicros": 233950,
    "timeAfterFrameworkInitMicros": 91800
```

**Comment by zanderso** [comment] 2022-02-14 17:57
before:
timeToFirstFrameRasterizedMicros (avg): 540284
timeToFirstFrameMicros (avg): 223249

after:
timeToFirstFrameRasterizedMicros (avg): 541110
timeToFirstFrameMicros (avg): 243387

The values coming from the device lab are way off the numbers we get locally, both before and after the change. However it does look like there is still a ~10% regression in `timeToFirstFrameMicros` in the runs from @jmagman.

@jason-simmons Would the next step be to collect before/after timeline traces?

**Comment by chinmaygarde** [comment] 2022-02-14 18:52
Closing this in favor of tracking progress on performance in https://github.com/flutter/flutter/issues/94419.

**Closed by chinmaygarde** 2022-02-14 18:52 UTC
Labels: severe: regression, engine, severe: performance, dependency: skia, perf: speed, passed secondary triage, P1

**Comment by jmagman** [comment] 2022-02-14 20:18
Let me know if you need anything else from that iPhone 6S.
