### ISSUE TITLE
Better error message when Scrollbar tries to use an unattached PrimaryScrollController

### ISSUE THREAD

**Issue by klop78** [flutter/flutter#72424] opened 2020-12-16 10:44 UTC
flutter sdk version：1.24.0-7.0.pre

reproduce code：
![image](https://user-images.githubusercontent.com/8023834/102338130-6679c000-3fce-11eb-8ed3-9efecc1d67ac.png)

error：
![image](https://user-images.githubusercontent.com/8023834/102337654-b906ac80-3fcd-11eb-9843-894994ea2838.png)

**Comment by TahaTesser** [comment] 2020-12-16 15:10
Hi @klop78 
I can reproduce the issue on the latest `stable`, `beta`, and `dev` channels. However, this seems to be fixed on the latest `Channel master, 1.25.0-9.0.pre.88`.

<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Scrollbar(
        isAlwaysShown: true,
        child: ListView.builder(
          itemCount: 25,
          itemBuilder: (BuildContext context, int index) {
            return Padding(
              padding: const EdgeInsets.all(10),
              child: Image.network('https://i.imgur.com/QCNbOAo.png'),
            );
          },
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {},
      ),
    );
  }
}

``` 

</details>

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel master, 1.25.0-9.0.pre.88, on macOS 11.1 20C69 darwin-x64,
    locale en-GB)
    • Flutter version 1.25.0-9.0.pre.88 at /Users/tahatesser/Code/flutter_master
    • Framework revision e24e763872 (3 hours ago), 2020-12-16 07:33:03 -0500
    • Engine revision e9f2f0eaea
    • Dart version 2.12.0 (build 2.12.0-157.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[!] Android Studio
    • Android Studio at /Applications/Android/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Android Studio not found at /Applications/Android/Contents
    • Try updating or re-installing Android Studio.

[✓] VS Code (version 1.52.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.17.0

[✓] Connected device (4 available)
    • Taha’s iPad (mobile) • 00008020-000255113EE8402E            • ios
      • iOS 14.3
    • iPhone 12 (mobile)   • 01685E98-F396-4EB9-9C58-8B92677E24D5 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)      • macos                                • darwin-x64
      • macOS 11.1 20C69 darwin-x64
    • Chrome (web)         • chrome                               •
      web-javascript • Google Chrome 87.0.4280.88

! Doctor found issues in 1 category.
```

</details>

Labelling the issue to track fix for other issues channels

**Comment by HansMuller** [comment] 2020-12-16 18:57
CC @Piinks

**Comment by Piinks** [comment] 2020-12-16 20:41
@klop78 the example you provided does not appear to attach the ScrollController to a ScrollView. The Scrollbar should be given a ScrollController that is also passed to the relevant ScrollView.

@TahaTesser your code sample does not have a `ScrollController` given to `Scrollbar.controller`, in which case the `Scrollbar` will use the `PrimaryScrollController`.  Since your `ListView` is not marked as `primary`, the `PrimaryScrollController` is not attached to a `ScrollView`, thus the error.

I believe this is working as intended, but we should definitely catch this case and provide a better error.

**Comment by Piinks** [comment] 2020-12-16 21:15
Actually I checked and was mistaken - this appears to work fine as @TahaTesser reported. :) 
I am going to close this as fixed then.

**Closed by Piinks** 2020-12-16 21:15 UTC
Labels: f: material design, f: scrolling, found in release: 1.22, found in release: 1.24, found in release: 1.25, framework, has reproducible steps, severe: regression

**Comment by TahaTesser** [comment] 2020-12-17 08:12
@Piinks 
Yep, it reproduces without using ScrollController,`isAlwaysShown` just throws assertion error and a red screen.   fixed on the master channel. still reproduces on the `dev` version that released a few hours ago. Need the fix for `stable`, `beta` & `dev` 



CC @pcsosinski

**Comment by TahaTesser** [comment] 2020-12-17 09:36
Retitled based on https://github.com/flutter/flutter/issues/72424#issuecomment-747031245

**Comment by Piinks** [comment] 2020-12-17 14:14
This is not a regression and does not need to be fixed on stable, beta or dev.

The 'fix' is part of a new feature. isAlwaysShown previously required a scroll controller, we refactored all of the scrollbars recently and then decided to make it possible to not pass a scroll controller.
Before adding this feature, the assertion is expected so the behavior on the other channels is as intended. 

I don't think this requires further action, you cannot cherry pick https://github.com/flutter/flutter/pull/72316 because it is dependent on #71664, which is a massive change full of these new features.

**Comment by TahaTesser** [comment] 2020-12-17 14:38
@Piinks 
Thank you so much for the clarification!
