### ISSUE TITLE
Flutter doesn't have a way to handle bottom view insets/notches on Android devices

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#35404] opened 2019-07-01 14:25 UTC
Mirror issue for https://b.corp.google.com/issues/136122352. Customer related comments should go there, please.

**Comment by jackschedel** [comment] 2019-07-01 14:31
does SafeArea bit work?

**Comment by Hixie** [comment] 2019-07-01 17:49
Looks like a legit bug:
https://github.com/flutter/engine/blob/3f4f606105a8f6217cfbe08e193aa9a54b19dbef/shell/platform/android/io/flutter/view/FlutterView.java#L537

**Comment by kf6gpe** [comment] 2019-07-08 16:34
cc @jason-simmons, with whom I discussed this last week. Jason, is this something you can look at this week?

**Comment by jason-simmons** [comment] 2019-07-11 22:05
The Android embedding is mapping the system window bottom inset to `window.viewInsets.bottom` on the framework side.  This is intended to force a relayout excluding the keyboard region when the keyboard is shown.

@Hixie is the framework expecting different behavior here?  Should the Android embedding also set `window.viewPadding.bottom` to the same value as `window.viewInsets.bottom`?

**Comment by kf6gpe** [comment] 2019-07-30 22:17
A note from `customer: fun(g3)`: 

> Hey, just an update. I tested locally and I found out that Scaffold automatically avoids the bottom
> insets. To see the behavior we're seeing, either don't use a scaffold, or set 
> `resizeToAvoidBottomInset` to false on the scaffold. There are some widgets that should extend 
> their layouts under the padding, but right now the bottom padding is mistaken as a view/keyboard 
> inset (which isn't expected to have content laid out under).

**Comment by Hixie** [comment] 2019-08-02 23:38
@Piinks was working on this recently.

**Comment by Piinks** [comment] 2019-08-05 16:48
Here's a few points of reference to some of the recent work here:
https://github.com/flutter/engine/pull/8848
https://github.com/flutter/flutter/pull/33999
https://github.com/flutter/flutter/pull/34298

cc/ @dnfield he may know the answer to your question @jason-simmons. Do we have a runnable reproduction of this? I'm not sure I understand what is happening here versus the expectation.

**Comment by dnfield** [comment] 2019-08-05 17:02
We introduced a distinction between Window insets and Window padding to maintain some compatibility with how it used to work, which turned out to have some problems on iPhone X: https://github.com/flutter/engine/blob/master/lib/ui/window.dart#L531 and https://flutter.github.io/assets-for-api-docs/assets/widgets/window_padding.mp4

It looks like that Java class should be setting the `viewPadding` now.

**Comment by spkersten** [comment] 2019-08-20 08:27
@csells Could you mark this with "customer: solaris"?

**Comment by xster** [comment] 2020-10-12 18:32
This is fixed on https://github.com/flutter/engine/pull/20921 for Android 11 but worth fixing for lower versions too. Thanks for your PR @lazylazyllama

**Comment by lazylazyllama** [comment] 2020-10-30 22:47
This should now be fixed since flutter/engine#21730 landed.

**Closed** 2020-12-16 06:00 UTC
Labels: P4, customer: fun (g3), customer: solaris, engine, passed first triage, platform-android
