### ISSUE TITLE
VS Code can't hot reload via ctrl+s

### ISSUE THREAD

**Issue by huangbao21** [flutter/flutter#29275] opened 2019-03-13 05:44 UTC
## Steps to Reproduce

1.  VSCode's version is
![image](https://user-images.githubusercontent.com/17422412/54256053-9001ee00-4595-11e9-92d8-cfc1ae577e78.png)

2.  ![image](https://user-images.githubusercontent.com/17422412/54256101-c8a1c780-4595-11e9-9e1c-a6909fbc0783.png)

3.  I can't hot reload on save. And also can't find Toggle debug painting on Command Palette

## Logs

```
```

[√] Flutter (Channel master, v1.3.10-pre.29, on Microsoft Windows [Version 10.0.17134.619], locale zh-CN)
    • Flutter version 1.3.10-pre.29 at D:\d\flutter
    • Framework revision 89a51272d5 (4 hours ago), 2019-03-12 18:32:42 -0700
    • Engine revision 5ccee95373
    • Dart version 2.2.1 (build 2.2.1-dev.1.0 674fd0e060)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at D:\d\Program Files\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = D:\d\Program Files\Android\Sdk
    • Java binary at: D:\d\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.3)
    • Android Studio at D:\d\Program Files\Android\Android Studio
    • Flutter plugin version 32.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[!] IntelliJ IDEA Ultimate Edition (version 2018.1)
    • IntelliJ at D:\d\Program Files\JetBrains\IntelliJ IDEA 2018.1.1
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[√] Connected device (2 available)
    • SM G9350                     • 37ff6895      • android-arm64 • Android 8.0.0 (API 26)
    • Android SDK built for x86 64 • emulator-5554 • android-x64   • Android 9 (API 28) (emulator)

**Comment by richiethom** [comment] 2019-03-13 06:04
I have the same problem as you. Does hot reloading via the Restart button (circular green arrow in the debug menu) work?

![image](https://user-images.githubusercontent.com/299693/54257002-287c7c00-455e-11e9-96b2-73d45828574a.png)

**Comment by huangbao21** [comment] 2019-03-13 06:09
> I have the same problem as you. Does hot reloading via the Restart button (circular green arrow in the debug menu) work?
> 
> ![image](https://user-images.githubusercontent.com/299693/54257002-287c7c00-455e-11e9-96b2-73d45828574a.png)

Restart button And Flutter run, press r  work. I try to set key shortcut binding hot reload, but it's useless

**Comment by jonahwilliams** [comment] 2019-03-13 06:45
I believe the underlying issue is https://github.com/Dart-Code/Dart-Code/issues/1518. From the comments, the only current fix is to downgrade to 1.31 or update to 1.33 when it is available.



Duplicate of https://github.com/Dart-Code/Dart-Code/issues/1518

**Comment by huangbao21** [comment] 2019-03-13 07:16
> I believe the underlying issue is [Dart-Code/Dart-Code#1518](https://github.com/Dart-Code/Dart-Code/issues/1518). From the comments, the only current fix is to downgrade to 1.31 or update to 1.33 when it is available.
> 
> Duplicate of [Dart-Code/Dart-Code#1518](https://github.com/Dart-Code/Dart-Code/issues/1518)

thanks, now, i use insiders version(1.33)

**Comment by DanTup** [comment] 2019-03-13 15:43
> From the comments, the only current fix is to downgrade to 1.31 or update to 1.33 when it is available.

The VS Code team is also preparing a v1.32.2 recovery build. I'm hoping it's this week, but it's out of our hands (the bug is in VS Code, and not our VS Code extension). You can track the progress of that at https://github.com/Microsoft/vscode/issues/70350

(Closing this, since it's fixed upstream and nothing we can do here but direct people at 1.31 stable, 1.33 insiders, or wait).

**Closed by DanTup** 2019-03-13 15:43 UTC

**Comment by DanTup** [comment] 2019-03-14 07:57
VS Code 1.32.2 has now been released and contains the fix for this.

**Comment by huangbao21** [comment] 2019-03-14 08:00
> VS Code 1.32.2 has now been released and contains the fix for this.

@DanTup 
I saw it.but Toggle debug painting is still not

**Comment by DanTup** [comment] 2019-03-14 08:06
@huangbao21 If the other functionality is now working, this sounds like a different bug - please open a new issue and include a log (from running [Dart: Capture Logs](https://dartcode.org/docs/logging/#capture-logs-command) when reproducing) and I'll take a look.

**Comment by huangbao21** [comment] 2019-03-14 10:13
@DanTup sorry, now i find it's ok
![image](https://user-images.githubusercontent.com/17422412/54348824-cff3ce80-4684-11e9-95b0-4a318ae02e38.png)

**Comment by huangbao21** [comment] 2019-03-14 10:13
@DanTup sorry, now i find it's ok
![image](https://user-images.githubusercontent.com/17422412/54348824-cff3ce80-4684-11e9-95b0-4a318ae02e38.png)

**Comment by DanTup** [comment] 2019-03-14 11:03
@huangbao21 Ok, if you see it again please do open an issue in the Dart-Code repo and we can investigate. Thanks!

**Comment by gegobyte** [comment] 2020-02-21 14:02
One year later and the bug still exists.

**Comment by DanTup** [comment] 2020-02-21 14:07
@gegobyte the issue above was in VS Code and was fixed by the VS Code team very quickly (https://github.com/microsoft/vscode/issues/69534). If you're having issues, please file a new bug in the Dart-Code repro with specific details, as it's probably not the same issue.

**Comment by ggsant** [comment] 2021-06-03 11:36
Two year later and the bug still exists.

**Comment by DanTup** [comment] 2021-06-03 12:34
@ggsant as mentioned in the comment above, the issue described here was a bug in VS Code and was fixed by the VS Code team. If you're having issues with hot-reload-on-save it's probably not related to this. Please file a new issue with a detailed description/sample code illustrating the problem.
