### ISSUE TITLE
Mac_android microbenchmarks failing, "type 'Null' is not a subtype of type 'String'" at  (package:dds/src/isolate_manager.dart:236:32)

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#111482] opened 2022-09-13 15:03 UTC
Example: https://ci.chromium.org/ui/p/flutter/builders/prod/Mac_android%20microbenchmarks/7106/overview

It looks like it is failing due to not finding the Xcode command line tools?

```
[microbenchmarks] [STDOUT] [STDOUT] [        ] executing: xcrun xcodebuild -version
[microbenchmarks] [STDOUT] [STDOUT] [   +6 ms] Exit code 1 from: xcrun xcodebuild -version
[microbenchmarks] [STDOUT] [STDOUT] [        ] xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
```

The stderr log also reports a null safety runtime error, but there is no backtrace, so it is not useful.

Routing to the infra ticket queue in case the issue is missing Xcode command line tools.

**Comment by GaryQian** [comment] 2022-09-13 15:26
This test has been periodically passing since yesterday afternoon, so it is a flaky rather than a hard failure. The current roll commit it is failing on seems unrelated.

**Comment by keyonghan** [comment] 2022-09-13 16:06
Take an initial look, failures happened on different mac/android testbeds (mac20, 21, 22 and 31), whereas these testbeds are passing on all other mac/android tasks. This sounds like a test issue.

**Comment by GaryQian** [comment] 2022-09-13 16:10
This is the engine roll it seems to have begun failing on: https://github.com/flutter/flutter/pull/111426

**Comment by keyonghan** [comment] 2022-09-13 16:12
For any case, marking it as flaky first: https://github.com/flutter/flutter/pull/111486

**Comment by keyonghan** [comment] 2022-09-13 17:41
This is a mac/android test which should not rely on Xcode (it complains about xcodebuild, or xcrun in a [green build](https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8803120884528113217/+/u/run_microbenchmarks/test_stdout) as well. So this should not be the culprit.

From the log
```
 executing: xcrun xcodebuild -version
[microbenchmarks] [STDOUT] [STDOUT] [   +7 ms] Exit code 1 from: xcrun xcodebuild -version
[microbenchmarks] [STDOUT] [STDOUT] [        ] xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
[microbenchmarks] [STDOUT] [STDOUT] [        ] Xcode not found. Run 'flutter doctor' for more information.
[microbenchmarks] [STDOUT] [STDOUT] [        ] This crash may already be reported. Check GitHub for similar crashes.
[microbenchmarks] [STDOUT] [STDOUT] [        ] https://github.com/flutter/flutter/issues?q=is%3Aissue+type+%27Null%27+is+not+a+subtype+of+type+%27String%27
[microbenchmarks] [STDOUT] [STDOUT] 
[microbenchmarks] [STDOUT] [STDOUT] [        ] To report your crash to the Flutter team, first read the guide to filing a bug.
[microbenchmarks] [STDOUT] [STDOUT] [        ] https://flutter.dev/docs/resources/bug-reports
```
It points to the GitHub issue link with `type 'Null' is not a subtype of type 'String' `, I am wondering if this is related to some hidden null safety issue.

**Comment by keyonghan** [comment] 2022-09-13 17:42
BTW: this is flaking in staging as well:
https://ci.chromium.org/ui/p/flutter/builders/staging/Mac_android%20microbenchmarks/47/overview
https://ci.chromium.org/ui/p/flutter/builders/staging/Mac_android%20microbenchmarks/45/overview

**Comment by jmagman** [comment] 2022-09-13 17:44
> It points to the GitHub issue link with `type 'Null' is not a subtype of type 'String' `, I am wondering if this is related to some hidden null safety issue.

You're right from that link, this is the stack:
```
_TypeError: (#0      IsolateManager.initialize.<anonymous closure> (package:dds/src/isolate_manager.dart:236:32))

#0      IsolateManager.initialize.<anonymous closure> (package:dds/src/isolate_manager.dart:236:32)
<asynchronous suspension>
#1      Mutex.runGuarded (package:dds/src/utils/mutex.dart:20:14)
<asynchronous suspension>
#2      IsolateManager.initialize (package:dds/src/isolate_manager.dart:217:5)
<asynchronous suspension>
#3      DartDevelopmentServiceImpl.startService (package:dds/src/dds_impl.dart:113:7)
<asynchronous suspension>
#4      DartDevelopmentService.startDartDevelopmentService (package:dds/dds.dart:97:5)
<asynchronous suspension>
#5      DartDevelopmentService.startDartDevelopmentService (package:flutter_tools/src/base/dds.dart:55:22)
<asynchronous suspension>
#6      FlutterDevice.connect.<anonymous closure> (package:flutter_tools/src/resident_runner.dart:280:11)
<asynchronous suspension>
```

**Comment by jmagman** [comment] 2022-09-13 17:46
The Xcode logging is a red herring, the tool is checking if Xcode is installed, and it's not, so it continues:
https://github.com/flutter/flutter/blob/71b47975a98303d1e5b1905664eb0653a65a4300/packages/flutter_tools/lib/src/ios/xcodeproj.dart#L106-L111

**Comment by jmagman** [comment] 2022-09-13 17:52
Either the id or the name of the isolate is null
https://github.com/dart-lang/sdk/blob/d1fbc73bf1dece66e564f142d16f479f28c787cd/pkg/dds/lib/src/isolate_manager.dart#L225-L237

**Comment by zanderso** [comment] 2022-09-13 18:02
@bkonyi ptal

**Comment by bkonyi** [comment] 2022-09-13 18:16
There haven't been any recent releases of DDS, so I'm not sure why we'd start seeing this issue now. Were we seeing this failure before the last engine roll?

**Comment by keyonghan** [comment] 2022-09-13 18:20
Actually it started from https://github.com/flutter/flutter/commit/e3b9223a74bc89cfa07c3b65362ab89a97708fa5
Flake build: https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8803179078151639633/+/u/run_microbenchmarks/test_stdout

**Comment by bkonyi** [comment] 2022-09-13 18:29
Ah, so only after we've enabled strong null safety in flutter_tools? That's unfortunate. Are you able to reproduce this locally somewhat consistently?

If this is still a P0, I'd recommend reverting https://github.com/flutter/flutter/commit/e3b9223a74bc89cfa07c3b65362ab89a97708fa5 for now as we'll need to add some null checks in DDS to actually figure out what's null (`id` or `name`).

**Comment by zanderso** [comment] 2022-09-13 18:35
cc @liamappelbe

**Comment by jason-simmons** [comment] 2022-09-13 20:51
I can reproduce this locally.

The isolate's name is missing:
  `isolate={type: Sentinel, kind: Collected, valueAsString: <collected>}`

The IsolateRef does contain an `id`:
```
{type: @Isolate, id: isolates/4086051790706887, name: Closure: (int) => List<Data> from Function 'test': static., number: 4086051790706887, isSystemIsolate: false, isolateGroupId: isolateGroups/1003754909991569502}
```

**Comment by liamappelbe** [comment] 2022-09-13 21:07
@bkonyi Is this going through the VM service JSON encoder at some point? If so, it might accidentally already be fixed by https://dart-review.googlesource.com/c/sdk/+/258100 :P

**Comment by jmagman** [comment] 2022-09-13 21:23
Column 32 is name:
```
            isolateStarted(id, name);
                               ^
```

**Comment by jmagman** [comment] 2022-09-13 21:31
@christopherfujino found the missing crash logs, they were in stderr:
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8803170379930354273/+/u/run_microbenchmarks/test_stderr

**Comment by christopherfujino** [comment] 2022-09-13 21:48
> @bkonyi Is this going through the VM service JSON encoder at some point? If so, it might accidentally already be fixed by https://dart-review.googlesource.com/c/sdk/+/258100 :P

Ooh yeah!

**Comment by jason-simmons** [comment] 2022-09-13 23:00
This is not affected by https://dart-review.googlesource.com/c/sdk/+/258100

DDS' `IsolateManager.initialize` is calling the VM service's `getIsolate` for an isolate that may no longer exist.  The VM service's `RunningIsolates` wrapper is returning a sentinel instead of an isolate.

`IsolateManager.initialize` will then try to read a `name` from the sentinel and will get a null, which it then passes to `isolateStarted`.

Prior to https://github.com/flutter/flutter/commit/e3b9223a74bc89cfa07c3b65362ab89a97708fa5 flutter_tools was running DDS without null safety checks.  So the `isolateStarted` call completes and the benchmark continues.

With null safety checks enabled the `isolateStarted` call is now throwing.

@bkonyi What is DDS' policy for handling sentinels?

**Comment by bkonyi** [comment] 2022-09-15 13:17
> @bkonyi Is this going through the VM service JSON encoder at some point? If so, it might accidentally already be fixed by https://dart-review.googlesource.com/c/sdk/+/258100 :P

Nope, this is just a raw request using `package:json_rpc_2`.

> @bkonyi What is DDS' policy for handling sentinels?

That's a good question, but it should handle them gracefully. I'll patch this today.

**Comment by bkonyi** [comment] 2022-09-15 13:59
DDS `v2.3.0` with the fix for this issue has been published and just needs to be rolled into Flutter.

**Comment by liamappelbe** [comment] 2022-09-16 17:51
Looks like DDS 2.3.0 has [landed in flutter_tools](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/pubspec.yaml), so I'll reland the null safety migration

**Closed** 2022-09-16 19:40 UTC
Labels: team: flakes, team: infra, passed secondary triage, P0, severe: flake
