### ISSUE TITLE
[video_player] pixels stretched bug

### ISSUE THREAD

**Issue by goyourfly** [flutter/flutter#37387] opened 2019-08-01 11:04 UTC
I found a bug in the video player, this problem appeared on the Android platform, iOS no problem.
As in the screenshot, the pixels at the bottom of the video are stretched.

## Screenshot
![image](https://user-images.githubusercontent.com/7019862/62287634-f3c97c80-b48c-11e9-85e7-2dfb6e3f606c.png)

## Steps to Reproduce

1. git clone https://github.com/goyourfly/plugins
2. cd plugins/packages/video_player/example/
3. flutter run

**Comment by BondarenkoStas** [comment] 2019-09-19 23:45
@goyourfly Please specify which devices you used? I tried to reproduce on current stable v1.9.1+hotfix.2 and master with android emulator API28, it was fine.

**Comment by goyourfly** [comment] 2019-09-20 01:15
@BondarenkoStas I just tried it on v1.9.1+hotfix. The emulator seems to have no problem, but the real machine still has problems. The phone I tested is: OnePlus 7 pro (API 28/29), Pixel 2 (API 28/29)

**Comment by giandifra** [comment] 2019-11-05 10:22
Same problem , Pixel 2 XL.
Flutter 1.9.1+hotfix.6 • channel stable

**Comment by otopba** [comment] 2019-11-12 19:11
I have same problem on OnePlus 6T Android 9.0
![image](https://user-images.githubusercontent.com/4225279/68702071-2b21ec00-0599-11ea-927f-5711c75a7431.png)

And no problem on emulator
![image](https://user-images.githubusercontent.com/4225279/68702120-4a207e00-0599-11ea-8c3b-905b51b6eac5.png)

**Comment by frankyvij** [comment] 2020-12-27 15:23
Do we not have a solution for this yet? I have the same problem. The video appears fine on iOS but is stretched on the right for Android..

**Comment by frankyvij** [comment] 2021-02-16 10:30
Hello, isn't anyone else facing this problem?

**Comment by FeleConvo** [comment] 2021-04-12 22:06
Can confirm this is happening only on Android.

| iOS  | Android |
| ------------- | ------------- |
| ![Image from iOS (5)](https://user-images.githubusercontent.com/35459194/114468490-966e5400-9bb9-11eb-8012-aa225d0e8b92.png) | ![Screenshot_20210412-102117](https://user-images.githubusercontent.com/35459194/114468555-ae45d800-9bb9-11eb-8d24-fcec9e21c309.png)  |

**Comment by maheshmnj** [comment] 2021-06-28 07:39
Hi @goyourfly,
 Thanks for filing the issue, I verified this issue using the latest stable version of flutter with ```video_player: ^2.1.6```, but I could not reproduce the issue. I would request you  and  everyone who is facing this issue to upgrade to latest stable version of flutter and use the latest plugin and verify  the issue.
 
 Tested on Xiaomi k20Pro, Xiaomi mi4i, Samsung s10 and the Android emulator Pixel_3a(Api 30) in both debug and release mode.
  
  <details>
 <summary>Heres a Screenshot taken on k20 Pro </summary>

<img src="https://user-images.githubusercontent.com/31410839/123598089-c371f080-d811-11eb-9ffe-0a681d6f2ae5.png" width="400">

 </details>
 
 <details>
 <summary>flutter doctor -v</summary>

 ```
 [✓] Flutter (Channel stable, 2.2.2, on macOS 11.4 20F71 darwin-arm, locale en-IN)
    • Flutter version 2.2.2 at /Users/mahesh/Documents/flutter
    • Framework revision d79295af24 (2 weeks ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2021.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 57.0.5
    • Dart plugin version 211.7233

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.23.0

[✓] Connected device (3 available)
    • iPhone 12 Pro Max (mobile) • 6A434744-B348-4FB3-AB10-131292174456 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-4
      (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 11.4 20F71 darwin-arm
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 91.0.4472.114

• No issues found!
 ```
 </details>
 
 Thank you.

**Comment by TahaTesser** [comment] 2021-07-21 12:13
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by TahaTesser** 2021-07-21 12:13 UTC
Labels: P4, a: quality, customer: crowd, p: first party, p: video_player, platform-android, plugin, waiting for customer response
