### ISSUE TITLE
Can't test tap on Stack Positioned widget

### ISSUE THREAD

**Issue by masfranzhuo** [flutter/flutter#79612] opened 2021-04-02 05:01 UTC
```
Stack(
        children: [
          Container(
            child: ClipRRect(
              child: image,
              borderRadius: BorderRadius.circular(8.0),
            ),
          ),
          Positioned(
            bottom: 8,
            right: 8,
            width: 25,
            height: 25,
            child: FloatingActionButton(
              onPressed: () => _pickFile(context),
              backgroundColor: Colors.white,
              child: Icon(
                Icons.camera_alt,
                color: Theme.of(context).primaryColor,
                size: 14,
              ),
            ),
          ),
        ],
      );
```

```
await tester.tap(find.byType(FloatingActionButton));
```

I can't perform tap on this if the FloatingActionButton in wrap in Positioned widget, any clue how to handle this? maybe we need to check location of widget?

**Comment by iapicca** [comment] 2021-04-02 06:01
@masfranzhuo 
seem to work as intended with the latest master

```dart
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(
    MaterialApp(
      home: Material(
        child: Stack(
          children: [
            Positioned(
              child: FloatingActionButton(
                onPressed: () => print('### hello ###'),
              ),
            )
          ],
        ),
      ),
    ),
  );
}

```

```bash
💪 Running with sound null safety 💪

🔥  To hot restart changes while running, press "r" or "R".
For a more detailed help message, press "h". To quit, press "q".
### hello ###
### hello ###
### hello ###
```

```console
[✓] Flutter (Channel master, 2.1.0-13.0.pre.416, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[!] Android Studio (not installed)
[✓] Connected device (2 available)
```

**Comment by masfranzhuo** [comment] 2021-04-02 06:07
It wont work if you put value in Positioned widget, such as bottom:4. I tried Positioned only without added any params value, but what i need is Positined with bottom and right value included which makes the tap not workint in test

**Comment by iapicca** [comment] 2021-04-02 06:19
> It wont work if you put value in Positioned widget, such as bottom:4. I tried Positioned only without added any params value, but what i need is Positined with bottom and right value included which makes the tap not workint in test

@masfranzhuo 
I tried

```diff
            Positioned(
+             bottom: 4,
              child: FloatingActionButton(
                onPressed: () => print('### hello ###'),
              ),
            )
```
still works

```bash
💪 Running with sound null safety 💪

🔥  To hot restart changes while running, press "r" or "R".
For a more detailed help message, press "h". To quit, press "q".
### hello ###
### hello ###
### hello ###


Performing hot restart...                                          329ms
Restarted application in 329ms.
### hello ###
### hello ###
### hello ###
### hello ###
### hello ###
### hello ###
### hello ###
### hello ###
### hello ###
### hello ###


```

**Comment by masfranzhuo** [comment] 2021-04-02 07:05
it won't work on test widget `await tester.tap(find.byType(FloatingActionButton));`

**Comment by iapicca** [comment] 2021-04-02 07:34
@masfranzhuo 
sorry I missed that was about testing
I can reproduce the issue

<details>
<summary>sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

class Stub {
  int counter = 0;
  void call() => counter++;
}

void main() {
  testWidgets(
    'Find and Tap a `FloatingActionButton` in `Positioned` ',
    (tester) async {
      final stub = Stub();
      await tester.pumpWidget(
        MaterialApp(
          home: Material(
            child: Stack(
              children: [
                Positioned(
                  bottom: 4,
                  child: FloatingActionButton(
                    onPressed: stub,
                  ),
                )
              ],
            ),
          ),
        ),
      );
      expect(
        find.byType(FloatingActionButton),
        findsOneWidget,
        reason: 'should find a FAB',
      );

      await tester.tap(find.byType(FloatingActionButton));
      await tester.pumpAndSettle();

      expect(
        stub.counter,
        findsNothing,
        reason: 'FAB should be "tapped"',
      );
    },
  );

  testWidgets(
    'Find and Tap a `FloatingActionButton` in `Positioned` with KEY',
    (tester) async {
      final stub = Stub();
      final key = UniqueKey();
      await tester.pumpWidget(
        MaterialApp(
          home: Material(
            child: Stack(
              children: [
                Positioned(
                  bottom: 4,
                  child: FloatingActionButton(
                    key: key,
                    onPressed: stub,
                  ),
                )
              ],
            ),
          ),
        ),
      );
      expect(
        find.byKey(key),
        findsOneWidget,
        reason: 'should find a FAB',
      );

      await tester.tap(find.byKey(key));
      await tester.pumpAndSettle();

      expect(
        stub.counter,
        findsNothing,
        reason: 'FAB should be "tapped"',
      );
    },
  );
}
```

</details>

possibly related to https://github.com/flutter/flutter/issues/54651

**Comment by masfranzhuo** [comment] 2021-04-02 07:40
Thanks, anyway I change the code so it could pass the test (without Positioned), weird way but work for now.

```
Stack(
        alignment: Alignment.bottomRight,
        children: [
          Container(
            child: ClipRRect(
              child: image,
              borderRadius: BorderRadius.circular(8.0),
            ),
          ),
          Container(
            margin: const EdgeInsets.all(8),
            width: 25,
            height: 25,
            child: FloatingActionButton(
              onPressed: () => _pickFile(context),
              backgroundColor: Colors.white,
              child: Icon(
                Icons.camera_alt,
                color: Theme.of(context).primaryColor,
                size: 14,
              ),
            ),
          ),
        ],
      );
```

**Comment by TahaTesser** [comment] 2021-04-05 12:42
Hi @masfranzhuo 
Test also passes for me when using https://github.com/flutter/flutter/issues/79612#issuecomment-812389834 on the latest `master` channel

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel master, 2.1.0-13.0.pre.444, on Microsoft Windows [Version 10.0.19042.870], locale en-US)
    • Flutter version 2.1.0-13.0.pre.444 at C:\Users\Taha\Code\flutter_master
    • Framework revision 824b1ad3f8 (2 days ago), 2021-04-03 15:24:02 -0400
    • Engine revision e393800c63
    • Dart version 2.13.0 (build 2.13.0-196.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\Taha\Code\SDK
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.2)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.9.31112.23
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Users\Taha\Code\android-studio
    • Flutter plugin can be installed from:
      � https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      � https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.55.0)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • IN2011 (mobile)         • c9d8ee0c      • android-arm64  • Android 11 (API 30)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)       • windows       • windows-x64    • Microsoft Windows [Version 10.0.19042.870]
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 89.0.4389.114
    • Edge (web)              • edge          • web-javascript • Microsoft Edge 89.0.774.63

• No issues found!
```
	
</details>


Can you please provide a complete reproducible minimal code sample?

**Comment by masfranzhuo** [comment] 2021-04-09 17:33
Hello it was my mistake after I changed the `onPressed​:​ () ​=>​ ​_pickFile​(context)` into `onPressed​:​ ​_pickFile​` it works.

**Comment by TahaTesser** [comment] 2021-04-12 06:19
Hi @masfranzhuo 
Given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you

**Closed by TahaTesser** 2021-04-12 06:19 UTC
Labels: in triage
