### ISSUE TITLE
[tool_crash] FileSystemException: Cannot create file, path = 'E:\formations\[FreeCourseSite.com] Udemy - The Complete Flutter UI Masterclass  iOS & Android in Dart\02 Food Delivery App\002 flutter-food-delivery-ui-starter\flutter_food_delivery_ui\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java' (OS Error: Le chemin d’accès spécifié est introuvable., errno = 3)

### ISSUE THREAD

**Issue by ndjaka** [flutter/flutter#59618] opened 2020-06-16 23:40 UTC
## Command
```
flutter --no-color run --machine --track-widget-creation --device-id=emulator-5554 lib\main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: FileSystemException: Cannot create file, path = 'E:\formations\[FreeCourseSite.com] Udemy - The Complete Flutter UI Masterclass  iOS & Android in Dart\02 Food Delivery App\002 flutter-food-delivery-ui-starter\flutter_food_delivery_ui\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java' (OS Error: Le chemin d’accès spécifié est introuvable.
, errno = 3)
```
#0      _File.throwIfError (dart:io/file_impl.dart:645:7)
#1      _File.createSync (dart:io/file_impl.dart:283:5)
#2      ForwardingFile.createSync (package:file/src/forwarding/forwarding_file.dart:24:16)
#3      ForwardingFile.createSync (package:file/src/forwarding/forwarding_file.dart:24:16)
#4      _renderTemplateToFile (package:flutter_tools/src/plugins.dart:27:8)
#5      _writeAndroidPluginRegistrant (package:flutter_tools/src/plugins.dart:641:3)
#6      injectPlugins (package:flutter_tools/src/plugins.dart:1079:11)
#7      FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:232:11)
<asynchronous suspension>
#8      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:707:21)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:619:33)
<asynchronous suspension>
#10     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart)
#11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#12     _rootRun (dart:async/zone.dart:1184:13)
#13     _CustomZone.run (dart:async/zone.dart:1077:19)
#14     _runZoned (dart:async/zone.dart:1619:10)
#15     runZoned (dart:async/zone.dart:1539:10)
#16     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
```
```
[✓] Flutter (Channel stable, v1.17.0, on Microsoft Windows [version 10.0.18363.900], locale fr-FR)
    • Flutter version 1.17.0 at C:\Users\eugen\Documents\tools\flutter_windows_1.17.0-stable\flutter
    • Framework revision e6b34c2b5c (6 weeks ago), 2020-05-02 11:39:18 -0700
    • Engine revision 540786dd51
    • Dart version 2.8.1

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\eugen\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[✓] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 44.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[!] IntelliJ IDEA Ultimate Edition (version 2019.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2019.1.2
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.46.0)
    • VS Code at C:\Users\eugen\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.11.0

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 1aedbb1835bd6eb44550293d57d4d124f19901f0

**Comment by TahaTesser** [comment] 2020-06-17 10:03
possibly related to
https://github.com/flutter/flutter/issues/58529
https://github.com/flutter/flutter/issues/58928
https://github.com/flutter/flutter/issues/20579 (closed)
https://github.com/flutter/flutter/issues/50880

**Comment by christopherfujino** [comment] 2020-06-24 17:25
I'm closing this as a duplicate of #50880. @ndjaka you can fix this by moving your Flutter app to a directory that your user has write permissions to.

**Closed** 2020-06-24 17:25 UTC
Labels: severe: crash, tool
