### ISSUE TITLE
[tool_crash] FileSystemException: Cannot open file, path = '/Users/sujantuladhar/.flutter_tool_state' (OS Error: Permission denied, errno = 13)

### ISSUE THREAD

**Issue by sujanmt** [flutter/flutter#71393] opened 2020-11-30 07:57 UTC
## Command
```
flutter upgrade
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: FileSystemException: Cannot open file, path = '/Users/sujantuladhar/.flutter_tool_state' (OS Error: Permission denied, errno = 13)
```
#0      _File.throwIfError (dart:io/file_impl.dart:645:7)
#1      _File.openSync (dart:io/file_impl.dart:489:5)
#2      _File.writeAsBytesSync (dart:io/file_impl.dart:614:31)
#3      _File.writeAsStringSync (dart:io/file_impl.dart:638:5)
#4      ForwardingFile.writeAsStringSync (package:file/src/forwarding/forwarding_file.dart:154:16)
#5      ErrorHandlingFile.writeAsStringSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_file_system.dart:137:22)
#6      ErrorHandlingFile._runSync (package:flutter_tools/src/base/error_handling_file_system.dart:163:16)
#7      ErrorHandlingFile.writeAsStringSync (package:flutter_tools/src/base/error_handling_file_system.dart:136:5)
#8      Config._flushValues (package:flutter_tools/src/base/config.dart:86:11)
#9      Config.setValue (package:flutter_tools/src/base/config.dart:75:5)
#10     _DefaultPersistentToolState.updateLastActiveVersion (package:flutter_tools/src/persistent_tool_state.dart:105:13)
#11     UpgradeCommandRunner.recordState (package:flutter_tools/src/commands/upgrade.dart:151:33)
#12     UpgradeCommandRunner.runCommandFirstHalf (package:flutter_tools/src/commands/upgrade.dart:133:5)
<asynchronous suspension>
#13     UpgradeCommandRunner.runCommand (package:flutter_tools/src/commands/upgrade.dart:85:13)
#14     UpgradeCommand.runCommand (package:flutter_tools/src/commands/upgrade.dart:60:27)
#15     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:681:18)
#16     _rootRunUnary (dart:async/zone.dart:1134:38)
#17     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#18     _FutureListener.handleValue (dart:async/future_impl.dart:140:18)
```
```
[✓] Flutter (Channel master, v1.15.4-pre.97, on Mac OS X 10.15.7 19H15,
    locale en-US)
    • Flutter version 1.15.4-pre.97 at /Users/sujantuladhar/Documents/flutter
    • Framework revision f81588a5a3 (10 months ago), 2020-02-18 16:33:55
      -0800
    • Engine revision 77c5812d48
    • Dart version 2.8.0 (build 2.8.0-dev.9.0 999eeea5a3)

[!] Android toolchain - develop for Android devices (Android SDK version
    30.0.0-rc4)
    • Android SDK at /Users/sujantuladhar/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native
      profiling support)
    • Platform android-30, build-tools 30.0.0-rc4
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    ! Some Android licenses not accepted.  To resolve this, run: flutter
      doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.8.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin installed
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (3 available)
    • ONEPLUS A3003 • ac96841c   • android-arm64  • Android 9 (API 28)
    • Chrome        • chrome     • web-javascript • Google Chrome
      87.0.4280.67
    • Web Server    • web-server • web-javascript • Flutter Tools

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
No pubspec in working directory.

**Comment by iapicca** [comment] 2020-11-30 08:22
possible duplicate of https://github.com/flutter/flutter/issues/71218

**Comment by pedromassangocode** [comment] 2020-11-30 09:33
@sujanmt 
Please upgrade to latest stable version (1.22.4) and try again to see if it works. Else, switch to latest master version and try again.
Thanks.

**Comment by pedromassangocode** [comment] 2020-12-23 09:15
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2020-12-23 09:15 UTC
Labels: in triage, waiting for customer response
