### ISSUE TITLE
go_router does not respond to sideslip

### ISSUE THREAD

**Issue by jayrao5566** [flutter/flutter#151530] opened 2024-07-10 09:18 UTC
### Steps to reproduce

1.When i open a new page using the go_router and then sideshow back to the previous page, the sideshow effect fails

### Expected results

Sideslip successfully returned to previous page

### Actual results

Sideslip failed

### Code sample

<details open><summary>Code sample</summary>

```dart
GoRoute(
        path: EvSearchPage.routeName,
        name: EvSearchPage.routeName,
        pageBuilder: (context, state) {
          // return MaterialPage(
          //   key: state.pageKey,
          //   restorationId: state.pageKey.value,
          //   child: const EvSearchPage(),
          // );
          return CustomTransitionPage(
            key: state.pageKey,
            restorationId: state.pageKey.value,
            child: const EvSearchPage(),
            transitionsBuilder:
                (context, animation, secondaryAnimation, child) {
              return FadeTransition(
                opacity: animation,
                child: child,
              );
            },
          );
        },
      ),
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.22.2, on macOS 14.5 23F79 darwin-arm64 (Rosetta), locale zh-Hans-CN)
    • Flutter version 3.22.2 on channel stable at /Users/rao/Developer/Git/Flutter/SDK/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 761747bfc5 (5 weeks ago), 2024-06-05 22:15:13 +0200
    • Engine revision edd8546116
    • Dart version 3.4.3
    • DevTools version 2.34.3
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/rao/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

[✓] Android Studio (version 2023.2)
    • Android Studio at /Users/rao/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

[✓] IntelliJ IDEA Community Edition (version 2023.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Community Edition (version 2023.3)
    • IntelliJ at /Users/rao/Applications/IntelliJ IDEA Community Edition.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.91.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.92.0

[✓] Connected device (5 available)
    • 🍎 (mobile)                • xxxxxx            • ios            • iOS 17.5.1 21F90
    • iPhone 15 Pro (mobile)          • 7EAFDBF7-1884-40A5-9485-89DDC456BBB3 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-17-2 (simulator)
    • macOS (desktop)                 • macos                                • darwin-arm64   • macOS 14.5 23F79 darwin-arm64
      (Rosetta)
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad                • darwin         • macOS 14.5 23F79 darwin-arm64
      (Rosetta)
    • Chrome (web)                    • chrome                               • web-javascript • Google Chrome 126.0.6478.127

[✓] Network resources
    • All expected network resources are available.
```

</details>

**Comment by danagbemava-nc** [comment] 2024-07-10 10:25
Hi @jayrao5566, please provide a complete minimal reproducible code sample without any third-party packages so that we can properly investigate this. 

Please also provide the version of `go_router` you're using. 

Thank you

**Comment by jayrao5566** [comment] 2024-07-10 11:37
> Hi @jayrao5566, please provide a complete minimal reproducible code sample without any third-party packages so that we can properly investigate this.您好，@jayrao5566，请提供一个完整的最小可重现代码示例，而无需任何第三方包，以便我们对此进行适当的调查。
> 
> Please also provide the version of `go_router` you're using. If you could also provide a recording of the issue, that would help.还请提供您正在使用的 `go_router` 版本。如果您还可以提供问题的录音，那将会有所帮助。
> 
> Thank you 谢谢

hi.

[test_go_router.zip](https://github.com/user-attachments/files/16160106/test_go_router.zip)


go_router: ^14.2.0

**Comment by danagbemava-nc** [comment] 2024-07-11 06:02
Hi @jayrao5566, what device(s) are you experiencing this issue on?

**Comment by jayrao5566** [comment] 2024-07-12 01:29
> Hi @jayrao5566, what device(s) are you experiencing this issue on?嗨，@jayrao5566，您在什么设备上遇到此问题？

hi  ， Running on an **iPhone 12 pro  ios 17.5.1**     or     Running on an i**Phone simulator**

**Comment by danagbemava-nc** [comment] 2024-07-12 07:49
Hi @jayrao5566, do you get any errors in your console when the back swipe fails?

**Comment by jayrao5566** [comment] 2024-07-15 01:32
> Hi @jayrao5566, do you get any errors in your console when the back swipe fails?嗨，@jayrao5566，当向后滑动失败时，您的控制台是否有任何错误？

hi。No errors detected.

**Comment by danagbemava-nc** [comment] 2024-07-15 06:59
Hi @jayrao5566, this is working by design. See https://github.com/flutter/flutter/issues/101696#issuecomment-1099603781

Closing from here.

Thank you

**Closed by danagbemava-nc** 2024-07-15 06:59 UTC
Labels: in triage

**Comment by jayrao5566** [comment] 2024-07-16 01:32
> Hi @jayrao5566, this is working by design. See [#101696 (comment)](https://github.com/flutter/flutter/issues/101696#issuecomment-1099603781)嗨，@jayrao5566，这是设计工作。参见 #101696（评论）
> 
> Closing from here. 从这里结束。
> 
> Thank you 谢谢
I see. Thank you
