### ISSUE TITLE
Getting "Error retrieving thread information: (ipc/send) invalid destination port" in the logs on Apple Silicon M1

### ISSUE THREAD

**Issue by heyiamZer0** [flutter/flutter#71395] opened 2020-11-30 09:03 UTC
When compiling the counter app I receive the following error every ~200 ms:

`[ +206 ms] [VERBOSE-2:profiler_metrics_ios.mm(184)] Error retrieving thread
information: (ipc/send) invalid destination port`

flutter doctor and flutter run -v doesn't give any visible errors.

<img width="807" alt="Screenshot 2020-11-28 at 10 48 16" src="https://user-images.githubusercontent.com/15111096/100589112-f5aa8680-32f2-11eb-88cb-6dc0f8a672f7.png">

**Comment by TahaTesser** [comment] 2020-11-30 09:17
Hi @heyiamZer0 
Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample

Related https://github.com/flutter/flutter/issues/71192  https://github.com/flutter/flutter/issues/60118
Thank you

**Comment by heyiamZer0** [comment] 2020-11-30 09:40
Hi @TahaTesser, the code is the one provided by the flutter example. 


```
[✓] Flutter (Channel stable, 1.22.4, on macOS 11.0.1 20B29 darwin-arm, locale
    en-GB)
    • Flutter version 1.22.4 at /Users/danielivanov/Development/flutter
    • Framework revision 1aafb3a8b9 (2 weeks ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/danielivanov/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.0

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin installed
    • Dart plugin version 201.9245
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```


**flutter run -v**: https://pastebin.com/raw/kXGmxqhH

**Comment by TahaTesser** [comment] 2020-11-30 15:18
Hi @heyiamZer0 
Are you firebase or anything third party packages, 
`Error retrieving threadinformation: (ipc/send) invalid destination port` is not specific to Apple silicon 
Can you please reproduce this in a fresh project `flutter create testapp`
Thank you

**Comment by heyiamZer0** [comment] 2020-11-30 15:38
@TahaTesser it is the testapp already

**Comment by Tofil** [comment] 2020-11-30 15:59
I saw this exact bug on a youtube video attempting the same thing https://youtu.be/Jo16qB6vbdc?t=240
(at 4min)

**Comment by heyiamZer0** [comment] 2020-11-30 17:48
@Tofil is definitely something regarding with M1 since on my Intel is running without any issues

**Comment by joniaiuser** [comment] 2020-12-01 02:14
I can confirm this issue, replicable on my M1 Macbook Air device.

The workaround is to run in Master channel.

**Comment by TahaTesser** [comment] 2020-12-01 07:36
@Tofil  @heyiamZer0  @joniaiuser 
Thanks for confirming, I don't have access to M1 yet to reproduce this issue. 
This doesn't reproduce intel mac when testing on a new fresh project

[run.log](https://github.com/flutter/flutter/files/5620895/run.log)

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 1.22.4, on macOS 11.0.1 20B29 darwin-x64, locale
    en-GB)
    • Flutter version 1.22.4 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 1aafb3a8b9 (3 weeks ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.0

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (1 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios • iOS 14.2

! Doctor found issues in 1 category.
```

</details>

**Comment by heyiamZer0** [comment] 2020-12-01 08:39
> @Tofil is definitely something regarding with M1 since on my Intel is running without any issues

thank you!

**Comment by mzl1988** [comment] 2020-12-08 03:48
M1 Macbook pro. I have the same problem

![image](https://user-images.githubusercontent.com/11645762/101437376-0a1dfd00-394b-11eb-8c67-3256168a8fa3.png)
![image](https://user-images.githubusercontent.com/11645762/101437424-23bf4480-394b-11eb-946c-cea2d484e387.png)

**Comment by ajaygautam** [comment] 2020-12-10 00:25
Got the new MacBook Air with M1 chip today (Dec 9, 2020).
Same Issue.
I get about 5 messages every second. 

Since everything seems to be working fine... 
Is there a way to disable this?

```
flutter: ===== STARTING APP =====
flutter: 2020-12-09 19:19:33.388298: MainApp INFO: ===== STARTING APP =====
[VERBOSE-2:profiler_metrics_ios.mm(184)] Error retrieving thread information: (ipc/send) invalid destination port
[VERBOSE-2:profiler_metrics_ios.mm(184)] Error retrieving thread information: (ipc/send) invalid destination port
[VERBOSE-2:profiler_metrics_ios.mm(184)] Error retrieving thread information: (ipc/send) invalid destination port
[VERBOSE-2:profiler_metrics_ios.mm(184)] Error retrieving thread information: (ipc/send) invalid destination port
flutter: 2020-12-09 19:19:34.147637: MainApp INFO: AppNavigationObserver didPush from null to CupertinoPageRoute<dynamic>(RouteSettings("/", null), animation: AnimationController#98bbb(⏭ 1.000; paused; for CupertinoPageRoute<dynamic>(/)))
```

Brand new fresh setup....
```
flutter doctor -v
[✓] Flutter (Channel stable, 1.22.4, on macOS 11.0.1 20B29 darwin-arm, locale en-US)
    • Flutter version 1.22.4 at /Users/agautam/tools/flutter
    • Framework revision 1aafb3a8b9 (4 weeks ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/agautam/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.0

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.17.0

[✓] Connected device (1 available)
    • iPhone 12 Pro Max (mobile) • 791FFAFB-CD39-4FA5-9A1B-DE42A8406147 • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-2 (simulator)

```

**Comment by ajaygautam** [comment] 2020-12-10 00:48
Interesting... switching to beta channel seem to have fixed it! yay 👍 

```
flutter channel beta
flutter upgrade
flutter clean
flutter run
```

Then launched Android studio, ran app from there... don't see the error anymore.
(Interestingly enough... it also fixed the issue where doctor wasn't able to locate flutter plugins for Android studio!

```
% flutter doctor -v
[✓] Flutter (Channel beta, 1.24.0-10.2.pre, on macOS 11.0.1 20B29 darwin-arm, locale en-US)
    • Flutter version 1.24.0-10.2.pre at /Users/agautam/tools/flutter
    • Framework revision 022b333a08 (3 weeks ago), 2020-11-18 11:35:09 -0800
    • Engine revision 07c1eed46b
    • Dart version 2.12.0 (build 2.12.0-29.10.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/agautam/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.0

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.17.0

[✓] Connected device (1 available)
    • iPhone 12 Pro Max (mobile) • 791FFAFB-CD39-4FA5-9A1B-DE42A8406147 • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-2 (simulator)

• No issues found!
```

**Comment by markusaksli-nc** [comment] 2020-12-18 16:03
I'm seeing this as well on stable `1.22.5` but not on the latest master `1.26.0-2.0.pre.84`.
<details>
 <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 1.22.5, on macOS 11.0.1 20B29 darwin-arm, locale en-GB)
    • Flutter version 1.22.5 at /Users/nevercode/development/flutter_stable
    • Framework revision 7891006299 (8 days ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/nevercode/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Users/nevercode/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.6953283/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.0

[!] Android Studio (version 4.1)
    • Android Studio at /Users/nevercode/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.6953283/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Connected device (2 available)
    • Nevercode’s iPhone (mobile) • b668e524315069f3db3661ac11ff1f66afafebdb • ios • iOS 14.2
    • iPhone 12 Pro Max (mobile)  • 09D9E93F-A98D-4735-B6E6-6E57F9CD01D8     • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)

! Doctor found issues in 1 category.
```
</details>

**Comment by jchokoch** [comment] 2020-12-26 11:52
Having struggled for several days with exactly the same problem, today I succeeded by following Ajay Gautam's method.
Thank you so much!!

**Comment by naxiemolv** [comment] 2020-12-29 13:43
# same issue on macbook M1

    • Flutter version 1.22.5 at /Users/liyuyang/development/flutter
    • Framework revision 7891006299 (3 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

**Comment by REKURDennis** [comment] 2021-01-02 09:28
Is there a plan to bring a fix to stable soon?

**Comment by kshitijahuja** [comment] 2021-01-07 20:43
I have the same issue with the M1. The error is on the Stable channel and goes away when switched to Beta.

```
Flutter 1.22.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 7891006299 (4 weeks ago) • 2020-12-10 11:54:40 -0800
Engine • revision ae90085a84
Tools • Dart 2.10.4
```

**Comment by AgustinOliver98** [comment] 2021-01-07 20:57
I have the same issue with the M1 chip

**Comment by abbas-25** [comment] 2021-01-08 15:23
same issue on m1 air on my side too!

**Comment by markusaksli-nc** [comment] 2021-01-08 15:45
Please thumbs up the original issue comment instead of commenting that you have the same issue

**Comment by zy1041081552** [comment] 2021-01-10 03:56
> Interesting... switching to beta channel seem to have fixed it! yay 👍
> 
> ```
> flutter channel beta
> flutter upgrade
> flutter clean
> flutter run
> ```
> 
> Then launched Android studio, ran app from there... don't see the error anymore.
> (Interestingly enough... it also fixed the issue where doctor wasn't able to locate flutter plugins for Android studio!
> 
> ```
> % flutter doctor -v
> [✓] Flutter (Channel beta, 1.24.0-10.2.pre, on macOS 11.0.1 20B29 darwin-arm, locale en-US)
>     • Flutter version 1.24.0-10.2.pre at /Users/agautam/tools/flutter
>     • Framework revision 022b333a08 (3 weeks ago), 2020-11-18 11:35:09 -0800
>     • Engine revision 07c1eed46b
>     • Dart version 2.12.0 (build 2.12.0-29.10.beta)
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
>     • Android SDK at /Users/agautam/Library/Android/sdk
>     • Platform android-30, build-tools 30.0.3
>     • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
>     • All Android licenses accepted.
> 
> [✓] Xcode - develop for iOS and macOS (Xcode 12.2)
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • Xcode 12.2, Build version 12B45b
>     • CocoaPods version 1.10.0
> 
> [✓] Android Studio (version 4.1)
>     • Android Studio at /Applications/Android Studio.app/Contents
>     • Flutter plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/9212-flutter
>     • Dart plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/6351-dart
>     • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
> 
> [✓] VS Code (version 1.51.1)
>     • VS Code at /Applications/Visual Studio Code.app/Contents
>     • Flutter extension version 3.17.0
> 
> [✓] Connected device (1 available)
>     • iPhone 12 Pro Max (mobile) • 791FFAFB-CD39-4FA5-9A1B-DE42A8406147 • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-2 (simulator)
> 
> • No issues found!
> ```

yes，is OK

**Comment by y-alkhateeb** [comment] 2021-01-14 18:20
I have the same issue with the M1, on Flutter SDK 1.22.5

**Comment by NakGun** [comment] 2021-01-18 00:40
Channel change is done?
Every channel is error plugin
Because force version nullable then other plugin is not match so im cant be change channel
Plz any other solution

**Comment by barangayretli** [comment] 2021-01-18 00:45
I am also having problems with master and beta channels because it enforces null safety. Is there any other workarounds?

**Comment by barangayretli** [comment] 2021-01-18 12:04
> Please thumbs up the original issue comment instead of commenting that you have the same issue unless you have anything unmentioned to contribute.
> 
> 
> 
> To be clear here, the issue is only on the stable channel and you can fix it by switching to a newer channel with the `flutter channel` command.

This is not working if you are already working on a big project because master and beta channels forces us to use null safety.

**Comment by geisterfurz007** [comment] 2021-01-20 09:37
For those who don't want to switch to the beta channel, you can just pipe flutter run to grep with the -v flag to drop the spammy lines.

`flutter run | grep -v "Error retrieving thread information"` works quite reliably for me, I can still use the hotkeys to hot reload/restart, etc. There are a few blank lines thrown into the terminal while the XCode build is running but once the app is running, the terminal remains tame.

**Comment by lewcianci** [comment] 2021-01-23 11:20
> Please thumbs up the original issue comment instead of commenting that you have the same issue unless you have anything unmentioned to contribute.
> 
> To be clear here, the issue is only on the stable channel and you can fix it by switching to a newer channel with the `flutter channel` command.

This isn't actually correct - you can't 'fix it' by switching to the stable channel because a lot of dependant plugins don't work on beta or dev channels. It's not as simple as just switching channels and carrying on.

**Comment by theomkale** [comment] 2021-01-24 00:00
Had same issue with **M1 Mac air.**
`flutter channel master`
`flutter upgrade`
`flutter clean`
`flutter run`

This worked for me.

**Comment by lewcianci** [comment] 2021-01-26 11:21
> Had same issue with **M1 Mac air.**
> `flutter channel master`
> `flutter upgrade`
> `flutter clean`
> `flutter run`
> 
> This worked for me.

I see these comments quite a bit. Do you realise that, by doing this, you are changing to the `master` branch of Flutter, and are essentially alpha-testing an unreleased version of Flutter? And that you couldn't reliably release an app built against the master branch?

**Comment by theomkale** [comment] 2021-01-26 14:39
> > Had same issue with **M1 Mac air.**
> > `flutter channel master`
> > `flutter upgrade`
> > `flutter clean`
> > `flutter run`
> > This worked for me.
> 
> I see these comments quite a bit. Do you realise that, by doing this, you are changing to the `master` branch of Flutter, and are essentially alpha-testing an unreleased version of Flutter? And that you couldn't reliably release an app built against the master branch?

Very true. Don't use the same channel for development. It was just a quick fix. As a student this doesn't bother me. Hope this gets fixed as soon as possible.

**Comment by royryando** [comment] 2021-01-29 12:27
this issue opened since November and the beta channel works fine, when is the beta channel released?
I don't know if deploying app using current beta channel will cause some unwanted things in the future, but no one want take a risk in the production

**Comment by bink3060** [comment] 2021-01-29 22:57
Just to notice...
I have this issue with my IOS emulator (Iphone 12 pro) but nothing on my real device (12 pro too).

**Comment by giorgio79** [comment] 2021-02-01 15:28
I think this was a change around Apple ID.

There is no point in changing to Master, since Apple Store does not allow releasing beta or master builds.

**Comment by joniaiuser** [comment] 2021-02-02 00:11
> I think this was a change around Apple ID.
> 
> There is no point in changing to Master, since Apple Store does not allow releasing beta or master builds.

I have submitted builds using beta channel to App Store that got approved before..

**Comment by cattris** [comment] 2021-02-02 18:44
> For those who don't want to switch to the beta channel, you can just pipe flutter run to grep with the -v flag to drop the spammy lines.
> 
> `flutter run | grep -v "Error retrieving thread information"` works quite reliably for me, I can still use the hotkeys to hot reload/restart, etc. There are a few blank lines thrown into the terminal while the XCode build is running but once the app is running, the terminal remains tame.

Is it possible to configure Android Studio so that the "Play" button runs flutter together with "grep"?

**Comment by geisterfurz007** [comment] 2021-02-02 19:17
> @geisterfurz007 Is it possible to configure Android Studio so that the "Play" button runs flutter together with "grep"?

Have a look at the Grep Console plugin for IntelliJ. I don't use Android Studio for iOS Development but it has prooven itself many times on other occasions.  
It adds a new button to the Run task window that allows for removing lines based on a regex and a bunch of other things.

**Comment by teamiqbal** [comment] 2021-02-08 03:39
> Interesting... switching to beta channel seem to have fixed it! yay 👍
> 
> ```
> flutter channel beta
> flutter upgrade
> flutter clean
> flutter run
> ```
> 
> Then launched Android studio, ran app from there... don't see the error anymore.
> (Interestingly enough... it also fixed the issue where doctor wasn't able to locate flutter plugins for Android studio!
> 
> ```
> % flutter doctor -v
> [✓] Flutter (Channel beta, 1.24.0-10.2.pre, on macOS 11.0.1 20B29 darwin-arm, locale en-US)
>     • Flutter version 1.24.0-10.2.pre at /Users/agautam/tools/flutter
>     • Framework revision 022b333a08 (3 weeks ago), 2020-11-18 11:35:09 -0800
>     • Engine revision 07c1eed46b
>     • Dart version 2.12.0 (build 2.12.0-29.10.beta)
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
>     • Android SDK at /Users/agautam/Library/Android/sdk
>     • Platform android-30, build-tools 30.0.3
>     • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
>     • All Android licenses accepted.
> 
> [✓] Xcode - develop for iOS and macOS (Xcode 12.2)
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • Xcode 12.2, Build version 12B45b
>     • CocoaPods version 1.10.0
> 
> [✓] Android Studio (version 4.1)
>     • Android Studio at /Applications/Android Studio.app/Contents
>     • Flutter plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/9212-flutter
>     • Dart plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/6351-dart
>     • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
> 
> [✓] VS Code (version 1.51.1)
>     • VS Code at /Applications/Visual Studio Code.app/Contents
>     • Flutter extension version 3.17.0
> 
> [✓] Connected device (1 available)
>     • iPhone 12 Pro Max (mobile) • 791FFAFB-CD39-4FA5-9A1B-DE42A8406147 • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-2 (simulator)
> 
> • No issues found!
> ```

thanks a lot!

**Comment by xhidnoda** [comment] 2021-02-09 16:35
any plan to fix this in the stable channel?

**Comment by riveraj33** [comment] 2021-02-13 17:02
When will this fix be undated to Stable?

**Comment by elliotops** [comment] 2021-02-14 15:29
I've had this issue since last year, and not on an M1 chip but an older iMac. 
I hoped it pertained to the iPhone simulator alone & have been ignoring it for the time-- 
But am tossing in that the same occurs sans M1.

**Comment by markusaksli-nc** [comment] 2021-02-15 12:30
I'd like to mention that when the beta channel rolls into a new stable this should get fixed. I don't know when this will be though.

https://github.com/flutter/flutter/wiki/Flutter-build-release-channels#beta

**Comment by jatintolwani** [comment] 2021-02-16 17:43
I m also facing this issue in my MacBook M1.

**Comment by silvafb** [comment] 2021-02-19 00:38
> Had same issue with **M1 Mac air.**
> `flutter channel master`
> `flutter upgrade`
> `flutter clean`
> `flutter run`
> 
> This worked for me.

what a scare, i had the same problem in m1 too, that solved the problem.

**Comment by fadious** [comment] 2021-02-21 20:49
I'm experiencing same issue on Mac Mini M1, fixed by switching to `master`.

**Comment by riveraj33** [comment] 2021-02-23 16:36
Would something break if I go to master and then back to stable before publishing to the AppStore?

**Comment by eduardoflorence** [comment] 2021-02-23 22:15
> Would something break if I go to master and then back to stable before publishing to the AppStore?

This is a problem only on iOS Simulator, it does not happen on the device itself

**Comment by loidoan** [comment] 2021-02-26 04:49
ipc/send) invalid destination port" in the logs on Apple M1 - using channel statle : 1.22.6 still error. Anybody help me!

**Comment by TobseW** [comment] 2021-02-26 15:55
I'm experiencing the same on my Apple M1 when using the flutter stable branch.
So far you can either switch to flutter master branch or wait until the fix gets merged into the stable branch.
As I cannot see anything harming the execution of my app, I decided to exercise patience and live with the log spam for now.

Hope this gets merged soon! 👍

**Comment by loidoan** [comment] 2021-03-04 04:35
> I'm experiencing the same on my Apple M1 when using the flutter stable branch.
> So far you can either switch to flutter master branch or wait until the fix gets merged into the stable branch.
> As I cannot see anything harming the execution of my app, I decided to exercise patience and live with the log spam for now.
> 
> Hope this gets merged soon! 👍

Thanks so much

**Comment by markusaksli-nc** [comment] 2021-03-04 16:21
Not seeing this anymore on stable `2.0.0`
<details>
 <summary>flutter doctor -v</summary>

```console
[✓] Flutter (Channel stable, 2.0.0, on macOS 11.2 20D64 darwin-arm, locale
    en-GB)
    • Flutter version 2.0.0 at /Users/nevercode/development/flutter_stable
    • Framework revision 60bd88df91 (23 hours ago), 2021-03-03 09:13:17 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/nevercode/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Users/nevercode/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.7042882/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Users/nevercode/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.7042882/Android
      Studio.app/Contents
    • Flutter plugin can be installed from:
      � https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      � https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] Connected device (4 available)
    • Nevercode’s iPhone (mobile) • b668e524315069f3db3661ac11ff1f66afafebdb •
      ios            • iOS 14.4
    • iPhone 12 Pro Max (mobile)  • 42B7F3DF-3053-419B-BA8F-FF1218F7A174     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • macOS (desktop)             • macos                                    •
      darwin-arm64   • macOS 11.2 20D64 darwin-arm
    • Chrome (web)                • chrome                                   •
      web-javascript • Google Chrome 88.0.4324.192

• No issues found!
```
</details>

**Closed by markusaksli-nc** 2021-03-04 16:21 UTC
Labels: P4, a: error message, customer: crowd, engine, found in release: 1.22, has reproducible steps, passed first triage, platform-host-arm, platform-ios, platform-mac

**Comment by fakru02** [comment] 2021-06-11 08:50
im using m1 and getting this annoying error too. i dont fix it instead i just right click on the error dialogue and it gave some options, then select [Fold lines like this] and then click ok. then your console will look like this 
<img width="553" alt="Screenshot 2021-06-11 at 4 49 50 PM" src="https://user-images.githubusercontent.com/85636497/121659631-13904980-cad5-11eb-8737-162c7198f8b7.png">
