### ISSUE TITLE
Flutter crashes on Android One after a little interaction

### ISSUE THREAD

**Issue by eklavya** [flutter/flutter#488] opened 2015-11-19 09:59 UTC
Hi,

I just created a simple template project with flutter.
```dart
import 'package:flutter/material.dart';
 
void main() {
  runApp(
    new MaterialApp(
      title: "Flutter Demo",
      routes: {
        '/': (RouteArguments args) => new FlutterDemo()
      }
    )
  );
}
 
class FlutterDemo extends StatelessComponent {
  Widget build(BuildContext context) {
    return new Scaffold(
      toolBar: new ToolBar(
        center: new Text("Flutter Demo")
      ),
      body: new Material(
        child: new Center(
          child: new Text("Hello world!")
        )
      ),
      floatingActionButton: new FloatingActionButton(
        child: new Icon(
          icon: 'content/add'
        ),
        onPressed: () {
          print("I was pressed");
        }
      )
    );
  }
}
```
If you tap on that floating action button 9 times, the app will crash.
Tested on an "android one Spice dream uno" with latest android 6.0

**Comment by sethladd** [comment] 2015-11-19 17:53
Thanks for the report! If you see anything in your logs (running `flutter logs`), please paste it in here.

**Comment by eklavya** [comment] 2015-11-20 04:35
flutter version 7be58b1ae0d4bddd181b3f44f509721ab070177f
```log

android: W/ActivityManager: Launch timeout has expired, giving up wake lock!
android: W/ActivityManager: Permission Denial: Accessing service ComponentInfo{com.google.android.music/com.google.android.music.dial.DialMediaRouteProviderService} from pid=3103, uid=10054 that is not exported from uid 10052
android: W/ActivityManager: Permission Denial: Accessing service ComponentInfo{com.google.android.music/com.google.android.music.dial.DialMediaRouteProviderService} from pid=3103, uid=10054 that is not exported from uid 10052
android: W/ActivityManager: Permission Denial: Accessing service ComponentInfo{com.google.android.music/com.google.android.music.dial.DialMediaRouteProviderService} from pid=3103, uid=10054 that is not exported from uid 10052
android: W/ActivityManager: Launch timeout has expired, giving up wake lock!
android: W/ActivityManager: Permission Denial: opening provider com.android.providers.contacts.ContactsProvider2 from ProcessRecord{f3ad6b4 4636:com.google.android.apps.plus/u0a56} (pid=4636, uid=10056) requires android.permission.READ_CONTACTS or android.permission.WRITE_CONTACTS
android: W/ActivityManager: Permission Denial: opening provider com.android.providers.contacts.ContactsProvider2 from ProcessRecord{f3ad6b4 4636:com.google.android.apps.plus/u0a56} (pid=4636, uid=10056) requires android.permission.READ_CONTACTS or android.permission.WRITE_CONTACTS
android: W/ActivityManager: Permission Denial: opening provider com.android.providers.contacts.ContactsProvider2 from ProcessRecord{f3ad6b4 4636:com.google.android.apps.plus/u0a56} (pid=4636, uid=10056) requires android.permission.READ_CONTACTS or android.permission.WRITE_CONTACTS
android: W/ActivityManager: Permission Denial: Accessing service ComponentInfo{com.google.android.music/com.google.android.music.dial.DialMediaRouteProviderService} from pid=3103, uid=10054 that is not exported from uid 10052
android: W/ActivityManager: Slow operation: 113783ms so far, now at getContentProviderImpl: after checkContentProviderPermission
android: W/ActivityManager: Slow operation: 113783ms so far, now at getContentProviderImpl: incProviderCountLocked
android: W/ActivityManager: Slow operation: 113783ms so far, now at getContentProviderImpl: before updateOomAdj
android: W/ActivityManager: Slow operation: 113783ms so far, now at getContentProviderImpl: after updateOomAdj
android: W/ActivityManager: Slow operation: 113783ms so far, now at getContentProviderImpl: done!
android: W/ActivityManager: Permission Denial: Accessing service ComponentInfo{com.google.android.music/com.google.android.music.dial.DialMediaRouteProviderService} from pid=3103, uid=10054 that is not exported from uid 10052
android: W/ActivityManager: Permission Denial: Accessing service ComponentInfo{com.google.android.music/com.google.android.music.dial.DialMediaRouteProviderService} from pid=3103, uid=10054 that is not exported from uid 10052
android: --------- beginning of crash
android: F/libc    : Fatal signal 4 (SIGILL), code 1, fault addr 0xa2e936e0 in tid 5423 (Thread-340)
android: W/ActivityManager: Force removing ActivityRecord{51b4c1 u0 org.domokit.sky.shell/.SkyActivity t147}: app died, no saved state
android: F/libc    : Fatal signal 4 (SIGILL), code 1, fault addr 0xa2e936e0 in tid 5473 (Thread-344)
android: W/ActivityManager: Force removing ActivityRecord{10a0f9b u0 org.domokit.sky.shell/.SkyActivity t147}: app died, no saved state
android: W/ActivityManager: Scheduling restart of crashed service org.telegram.messenger/.NotificationsService in 1000ms
android: W/ActivityManager: Scheduling restart of crashed service com.whatsapp/.messaging.MessageService in 1000ms
android: W/ActivityManager: Scheduling restart of crashed service com.whatsapp/.ExternalMediaManager in 11000ms
android: W/ActivityManager: Permission Denial: Accessing service ComponentInfo{com.google.android.music/com.google.android.music.dial.DialMediaRouteProviderService} from pid=3103, uid=10054 that is not exported from uid 10052
android: W/ActivityManager: Permission Denial: Accessing service ComponentInfo{com.google.android.music/com.google.android.music.dial.DialMediaRouteProviderService} from pid=3103, uid=10054 that is not exported from uid 10052
android: F/libc    : Fatal signal 4 (SIGILL), code 1, fault addr 0xa2d946e0 in tid 5758 (Thread-359)
android: W/ActivityManager: Force removing ActivityRecord{79f474a u0 org.domokit.sky.shell/.SkyActivity t149}: app died, no saved state
android: W/ActivityManager: Permission Denial: Accessing service ComponentInfo{com.google.android.music/com.google.android.music.dial.DialMediaRouteProviderService} from pid=3103, uid=10054 that is not exported from uid 10052
android: F/libc    : Fatal signal 4 (SIGILL), code 1, fault addr 0xa2e936e0 in tid 5839 (Thread-363)
android: W/ActivityManager: Force removing ActivityRecord{78d9e75 u0 org.domokit.sky.shell/.SkyActivity t150}: app died, no saved state
android: W/ActivityManager: Permission Denial: Accessing service ComponentInfo{com.google.android.music/com.google.android.music.dial.DialMediaRouteProviderService} from pid=3103, uid=10054 that is not exported from uid 10052
android: W/ActivityManager: Activity pause timeout for ActivityRecord{618cb89 u0 com.google.android.dialer/com.android.incallui.InCallActivity t151}
android: --------- beginning of main
android: W/ActivityManager: Permission Denial: Accessing service ComponentInfo{com.google.android.music/com.google.android.music.dial.DialMediaRouteProviderService} from pid=3103, uid=10054 that is not exported from uid 10052
android: W/ActivityManager: Activity pause timeout for ActivityRecord{b2b0617 u0 com.google.android.dialer/com.android.incallui.InCallActivity t166}
android: W/ActivityManager: SLOW OOM ADJ: 11747ms for pid 2398 = 13
android: W/ActivityManager: SLOW OOM ADJ: 14449ms for pid 1168 = 9
android: W/ActivityManager: Activity pause timeout for ActivityRecord{82f7628 u0 com.android.systemui/.usb.UsbDebuggingActivity t169}
android: F/libc    : Fatal signal 4 (SIGILL), code 1, fault addr 0xa2d946e0 in tid 7090 (Thread-428)
android: W/ActivityManager: Force removing ActivityRecord{fe3da20 u0 org.domokit.sky.shell/.SkyActivity t170}: app died, no saved state
android: W/ActivityManager: Activity pause timeout for ActivityRecord{4ec5567 u0 com.google.android.GoogleCamera/com.android.camera.CameraLauncher t171 f}
```

**Comment by Bema** [comment] 2015-11-20 15:26
Same here, few taps and both demo and shopping list apps crash. 

flutter version 7be58b1ae0d4bddd181b3f44f509721ab070177f

```
android: --------- beginning of crash
android: F/libc    : Fatal signal 4 (SIGILL), code 1, fault addr 0xa565d6e0 in tid 29824 (ui_thread)
android: F/libc    : Fatal signal 4 (SIGILL), code 1, fault addr 0xa4c436e0 in tid 30070 (ui_thread)
android: F/libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0xb4f55018 in tid 2215 (Binder_1)
android: F/libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0xb4f33018 in tid 5018 (Binder_1)
android: F/libc    : Fatal signal 4 (SIGILL), code 1, fault addr 0xa4c3b6e0 in tid 7262 (Thread-8041)
android: F/libc    : Fatal signal 4 (SIGILL), code 1, fault addr 0xa565a6e0 in tid 7499 (Thread-8056)
android: F/libc    : Fatal signal 4 (SIGILL), code 1, fault addr 0xa565f6e0 in tid 7680 (Thread-8066)
android: F/libc    : Fatal signal 4 (SIGILL), code 1, fault addr 0xa4c436e0 in tid 8084 (Thread-8076)
android: F/libc    : Fatal signal 4 (SIGILL), code 1, fault addr 0xa4c3b6e0 in tid 9263 (Thread-8092)
android: F/libc    : Fatal signal 4 (SIGILL), code 1, fault addr 0xa4c416e0 in tid 12347 (Thread-8152)
android: --------- beginning of system
android: W/ActivityManager: Spurious death for ProcessRecord{29120c4c 24941:org.domokit.sky.shell/u0a103}, curProc for 24941: null
android: W/ActivityManager: Force removing ActivityRecord{27c0d9aa u0 org.domokit.sky.shell/.SkyActivity t240}: app died, no saved state
android: W/ActivityManager: Spurious death for ProcessRecord{363d406a 25810:org.domokit.sky.shell/u0a103}, curProc for 25810: null
android: W/ActivityManager: Spurious death for ProcessRecord{78dedad 26430:org.domokit.sky.shell/u0a103}, curProc for 26430: null
android: F/libc    : Fatal signal 4 (SIGILL), code 1, fault addr 0xa4b436e0 in tid 26905 (Thread-8551)
android: W/ActivityManager: Force removing ActivityRecord{f86a473 u0 org.domokit.sky.shell/.SkyActivity t242}: app died, no saved state
android: --------- beginning of main
android:
android: F/libc    : Fatal signal 4 (SIGILL), code 1, fault addr 0xa56546e0 in tid 27881 (Thread-8561)
android: W/ActivityManager: Force removing ActivityRecord{181ea6e6 u0 org.domokit.sky.shell/.SkyActivity t243}: app died, no saved state
android: F/libc    : Fatal signal 4 (SIGILL), code 1, fault addr 0xa4c436e0 in tid 28630 (Thread-8602)
android: W/ActivityManager: Force removing ActivityRecord{1f16b8d1 u0 org.domokit.sky.shell/.SkyActivity t244}: app died, no saved state
```

**Comment by sethladd** [comment] 2015-11-20 15:54
Thanks for the additional info!

**Comment by abarth** [comment] 2015-11-20 20:07
Yes, I've seen this on an Android One device as well.

**Comment by Bema** [comment] 2015-11-23 09:52
It happened to me on a Moto G (2nd G).

**Comment by dglinyanov** [comment] 2015-11-24 18:08
Also experience this on Lenovo A316i (Android 4.2.2) and LG L90 (Android 5.0.1).

**Comment by eklavya** [comment] 2015-11-30 17:55
flutter f91c3dfb7ed93a7ea3bbfa1df0e9d99224c894ea

Doesn't crash on Nexus 5x and Spice dream uno both on latest android 6.

**Comment by abarth** [comment] 2015-12-05 09:35
@jason-simmons wasn't able to reproduce this issue.

**Comment by jimbeveridge** [comment] 2016-03-10 21:42
Retested on a 1+1 and a Nexus 5, with trivial changes to support the latest version of Flutter. Ran correctly, even after tapping the Add button many times. Also tested with --no-checked for good measure.

Closing this issue because it appears that the crash has been resolved, but please reopen the bug if you see the problem happen again.

**Closed by jimbeveridge** 2016-03-10 21:42 UTC
Labels: device-specific, ▣ platform-android, ⚠ crash
