### ISSUE TITLE
[video_player] hls gets real-time aspectRatio, video player adaptive height

### ISSUE THREAD

**Issue by JoinLi** [flutter/flutter#106862] opened 2022-06-30 09:54 UTC
Use videoPalyer to play hls live broadcast. The video stream may change aspectRatio in real time, but the video player cannot adapt to the ratio. Is there any way to get the real-time ratio of the video?

**Comment by danagbemava-nc** [comment] 2022-06-30 09:57
Hi @JoinLi, please refrain from filing multiple issues for the same request. 

Closing this as a duplicate of #106860.

Thank you

**Closed by danagbemava-nc** 2022-06-30 09:57 UTC
Labels: in triage
