### ISSUE TITLE
[Add2App] Cannot not compile on AOS (AndroidX enabled) with Flutter version > 1.12.0 -> Imports Error

### ISSUE THREAD

**Issue by michael-chiu** [flutter/flutter#48238] opened 2020-01-06 13:55 UTC
Cannot compile with AOS once updated to **Flutter version > v1.12.0**, tried with latest version on channel master / dev / stable, the same issue:

`Error: Unresolved reference: facade`   on this line `import   io.flutter.facade.Flutter`

From my observation, the FlutterActivity is importing non-AndroidX references, so I guess it maybe the AndroidX issue. 

My Android project has enabled AndroidX support, and also my Flutter module has specified ->  `module:`
`    androidX: true`
The project works great before upgrading to Flutter version 1.12.x. There's no problem for the imports and the FlutterActivity is using AndroidX references.

Once I have upgraded to Flutter version 1.12.x. `flutter packages get` give me the following warning:
```
The plugin `flutter_native_image` is built using an older version of the Android plugin API which assumes that it's running in a full-Flutter environment. It may have undefined behaviors when
Flutter is integrated into an existing app as a module.
```
Can this be the reason why the Flutter SDK is still referencing the non-AndroidX reference, when some of the Flutter plugins I am using gave me this error?

Please help. Thanks so much!

**Flutter Doctor:**
```
[✓] Flutter (Channel master, v1.13.7-pre.24, on Mac OS X 10.14.6 18G95, locale en-HK)
 
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
[✓] Android Studio (version 3.4)
[!] IntelliJ IDEA Ultimate Edition (version 2019.2.4)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] Connected device (2 available)

! Doctor found issues in 2 categories.
```

**Comment by VladyslavBondarenko** [comment] 2020-01-06 15:28
Hi @michael-chiu 
As I understand that your are referring to a 3rd party plugin [flutter_native_image](https://pub.dev/packages/flutter_native_image)
You might want to search for solution on [the plugin's github](https://github.com/btastic/flutter_native_image/issues) and consider opening an issue there
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it.
Thank you

**Comment by michael-chiu** [comment] 2020-01-07 05:41
@VladyslavBondarenko , thank you for your help. 

I agree it maybe an issue that can be fixed on the plugins side. However, I am getting the below error on a number of plugins, even on some from flutter.dev, like `image_picker`(the plugins themselves support AndroidX) :
```
The plugin `xxx` is built using an older version of the Android plugin API which assumes that it's running in a full-Flutter environment. It may have undefined behaviors when
Flutter is integrated into an existing app as a module.
```

This stop me from upgrading my Flutter version to above 1.12.x. So I would like to know in Add2App case, I need to wait all the plugins my project using to implement v2 Android Plugin APIs to fix this issue? 
Is it possible for the latest Flutter version being compatible with the v1 Android Plugin APIs for Add2App case? Any temporary workaround for this issue would be nice.

Thank you.

**Comment by VladyslavBondarenko** [comment] 2020-01-10 11:03
@michael-chiu 
I would upgrade plugins and check whether the new Flutter version is compatible with them.
And or would use for a while older Flutter version, or if the problem is in some third-party plugins, which don't update regularly, and there are exists analogs from Flutter team, and it's easy to replace them, I would consider this option too.
Unfortunately I don't possess more info and can not answer the second question

**Comment by VladyslavBondarenko** [comment] 2020-01-10 11:08
@michael-chiu 
If you face with this problem with plugins from flutter/plugins repository, it would be better to create separate issue(s) for them.
Closing, if you disagree please write in the comments and I will reopen it.
Thank you

**Closed by VladyslavBondarenko** 2020-01-10 11:08 UTC
