### ISSUE TITLE
Plumb Emulator support into packages/packages recipe

### ISSUE THREAD

**Issue by ricardoamador** [flutter/flutter#120736] opened 2023-02-15 00:15 UTC
Add the plumbing for supporting the packages/packages recipe so that we can generate an emulator from that recipe for use in the tests.

The tests are cirrus so this will have no effect immediately.

**Comment by stuartmorgan** [comment] 2023-02-15 00:36
> The tests are cirrus so this will have no effect immediately.

🤦🏻 Sorry, I spaced on that when I sent you that trial PR. We can try spinning up an initial Linux LUCI test for this; I think the plan of record for moving everything is Dockerfile support, but doing just Android without it is probably doable.

**Comment by ricardoamador** [comment] 2023-02-16 01:04
No problem. Sounds good. I will reach out when I begin this work shortly.

**Comment by ricardoamador** [comment] 2023-06-13 23:23
Hi Stuart, can you provide a candidate test that I can take a look at from start to finish that requires an android emulator? Do any of the current tests run on emulators or is this a "new feature" for the packages tests?

**Comment by stuartmorgan** [comment] 2023-06-14 03:44
It's a new feature. I have a test that would be perfect for this, which is the custom package test, but it's still on Cirrus because there hasn't been much progress on migrating Linux tests to LUCI. (I believe @keyonghan was planning on doing at least some of that, but I'm not sure what the timeline is.)

If someone can migrate [this task](https://github.com/flutter/packages/blob/f9314a3b833aa5bd5eceadebb27f28f97388ef94/.cirrus.yml#L241-L249) to LUCI, it would then be a trivial change to [enable an emulator test in it](https://github.com/flutter/packages/pull/4210).

**Comment by ricardoamador** [comment] 2023-06-14 04:43
Okay, I will get with Keyong about this to see what he has already done.

**Comment by keyonghan** [comment] 2023-06-14 17:05
> It's a new feature. I have a test that would be perfect for this, which is the custom package test, but it's still on Cirrus because there hasn't been much progress on migrating Linux tests to LUCI. (I believe @keyonghan was planning on doing at least some of that, but I'm not sure what the timeline is.)

I should have sync'ed with you about the cirrus to LUCI migration. @yusuf-goog is helping with the remaining migration now due to me working on something else. @ricardoamador Please touch base with yusuf about the progress.

**Comment by stuartmorgan** [comment] 2023-07-05 17:09
@ricardoamador I've hacked up a test PR that should work for testing emulator recipe support:
https://github.com/flutter/packages/pull/4377

I've replaced the script run by `Linux dart_unit_test_shard_1 master` and `Linux dart_unit_test_shard_2 master` to instead `flutter drive` Android tests. It's currently showing `No Android devices available` as expected; with emulator support working it should instead drive integration tests.

(I expect it'll time out with only two shards, but we'll be able to see it successfully complete several packages' tests before that, so it should still work as a PoC).

**Comment by ricardoamador** [comment] 2023-07-06 17:57
@stuartmorgan that is great news! I will take a look in the next few days. Trying to wrap up some changes before getting to this one.

**Comment by stuartmorgan** [comment] 2023-07-07 19:44
> I've replaced the script run by `Linux dart_unit_test_shard_1 master` and `Linux dart_unit_test_shard_2 master` to instead `flutter drive` Android tests. It's currently showing `No Android devices available` as expected; with emulator support working it should instead drive integration tests.
> 
> (I expect it'll time out with only two shards, but we'll be able to see it successfully complete several packages' tests before that, so it should still work as a PoC).

We've now landed partial migration of Android platform tests (just not including `drive`), so I updated the trial PR to be less hacky. It's now the `Linux_android android_platform_tests_shard_*` tests that run it, and the sharding is higher, so things may actually pass once emulators are there.

**Comment by ricardoamador** [comment] 2023-07-13 17:50
Taking a look.

**Comment by ricardoamador** [comment] 2023-07-13 18:06
@stuartmorgan the .ci.yaml defines the recipe but it looks like packages primarily uses another yaml file to pass arguments down in to the test runner. Is this an artifact of using Cirrus or will packages continue to use this structure even when migrated to LUCI for testing?

**Comment by stuartmorgan** [comment] 2023-07-13 18:23
flutter/packages uses a generic recipe so that almost all CI changes can be made in-repo, instead of the cumbersome process of having to change another repo (where we don't get presubmit, and changes are out-of-band relative to the affected repo). We will continue to use this structure until/unless there's a centralized replacement with those same semantics provided for all of the Flutter repos (my understanding is that there is or was some kind of plan around that), because moving away from it would be a huge usability regression.

**Comment by ricardoamador** [comment] 2023-07-13 19:40
Thank you for the context.

**Comment by ricardoamador** [comment] 2023-07-13 23:48
@stuartmorgan okay I was able to get an emulator to support this target: [Linux_android android_platform_tests_shard_1 master](https://luci-milo.appspot.com/p/flutter/builders/prod/Linux_android%20android_platform_tests_shard_1%20master).
However there is currently a limitation where the machine that supports kvm which is needed for the emulator has only 8 cores. Now normally this would not be an issue but I see that for each of the shards you are specifying 32 cores which I would assumes reduces the runtime of this test. Is that a correct assumption?

**Comment by stuartmorgan** [comment] 2023-07-14 00:25
I don't know how much difference the machine configuration makes in practice; we could do some tests and see how reasonable it it, and how much we need to adjust sharding.

That run is definitely not a fewer-cores-is-slower problem though, the test hung. It got to `Pause and resume video recording` at minute three, and then spent the rest of the hour there waiting. Could we get this all wired up without making the test change yet, if the infra part is working, and then I can investigate the hangs by experimenting further once that's in place?

**Comment by ricardoamador** [comment] 2023-07-14 02:25
@stuartmorgan That is good to know. I am going to reach out to the chromium team to see about getting a 32core with kvm configuration but good to know this is not a 'cores' issue. For sure I can add the plumbing if you would like to investigate further. The change is fairly simple and I can have it in tomorrow for sure. I just need to clean it up and then make sure the tests work.

**Comment by ricardoamador** [comment] 2023-07-14 18:44
https://flutter-review.googlesource.com/c/recipes/+/47340

I added instructions into the description on how to activate the emulators for packages.

Basically you just add the 'android_virtual_device' dependency which will make the recipe assume you want to run with an emulator for the test.

Let me know if you have questions or anything when you get to testing.

**Comment by ricardoamador** [comment] 2023-07-14 21:22
I am going to reopen for tracking and that we might need to provide other methods for supplying emulation.

**Comment by stuartmorgan** [comment] 2023-07-16 13:16
I was able to successfully set up a different emulator-based test (https://github.com/flutter/packages/pull/4484) so it's looking good! Next week I'll investigate the hang in the primary Android integration tests.

**Comment by stuartmorgan** [comment] 2023-07-27 17:23
None of the problems were infra-related, they are all test-specific. Given that, we can close this as done. Thanks again for getting this set up!

**Closed by stuartmorgan** 2023-07-27 17:23 UTC
Labels: team-infra
