### ISSUE TITLE
🔍 web_benchmarks_canvaskit bench_picture_recording.canvaskit.estimatePaintBounds and web_benchmarks_canvaskit bench_picture_recording.canvaskit.estimatePaintBounds have regressed

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#55381] opened 2020-04-22 16:07 UTC
Looks like this engine roll:
https://github.com/flutter/flutter/commit/5c5bb485a0db95fabc040253da42cd7d43cfac78

![Screen Shot 2020-04-22 at 9 06 47 AM](https://user-images.githubusercontent.com/1435716/80005569-9ccf6180-8478-11ea-9304-d1c7605f9836.png)

**Comment by yjbanov** [comment] 2020-04-23 21:56
Duplicate of https://github.com/flutter/flutter/issues/55389

**Closed by yjbanov** 2020-04-23 21:56 UTC
Labels: engine, perf: speed, platform-web, severe: performance, severe: regression, team: benchmark, ⚠ TODAY
