### ISSUE TITLE
path_provider package dependency on old platform package 3.0.x blocks update to latest version of Flutter

### ISSUE THREAD

**Issue by jamesncl** [flutter/flutter#102978] opened 2022-05-03 14:45 UTC
I've just updated to Flutter 2.10.4 and have the following build error:

```
/C:/Users/me/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/platform-3.0.2/lib/src/interface/local_platform.dart:46:19: Error: Member not found: 'packageRoot'.
      io.Platform.packageRoot; // ignore: deprecated_member_use
```

Running `flutter pub deps` reveals that the offending package is `path_provider` (specifically, `path_provider_platform_interface`) which relies on an old version of `platform` package:

```
-- path_provider 2.0.9
|   |-- flutter...
...
|   |-- path_provider_platform_interface 2.0.1
|   |   |-- flutter...
|   |   |-- meta...
|   |   |-- platform 3.0.2             <-------------------------
|   |   '-- plugin_platform_interface...
```

As noted in [the change log for platform](https://pub.dev/packages/platform/changelog#310), `platform` version 3.1.0 has fixed this problem:

> Removed Platform.packageRoot, which was already marked deprecated, and which didn't work in Dart 2. 

Please update [the `platform` dependency in `path_provider_platform_interface`](https://github.com/flutter/plugins/blob/master/packages/path_provider/path_provider_platform_interface/pubspec.yaml) to 3.1.0 to un-block updates to the latest version of Flutter.

**Comment by stuartmorgan** [comment] 2022-05-03 18:30
Duplicate of https://github.com/flutter/flutter/issues/96711

> which relies on an old version of `platform` package

This is not the case; see my comments in that issue.

**Closed by stuartmorgan** 2022-05-03 18:30 UTC
