### ISSUE TITLE
iOS debug build failing using Android Studio and Xcode

### ISSUE THREAD

**Issue by DK15** [flutter/flutter#52231] opened 2020-03-09 10:57 UTC
I am unable to build on iPhone device and on simulator due to below error:

```
Undefined symbols for architecture x86_64:
      "_OBJC_CLASS_$_FlutterMethodChannel", referenced from:
          objc-class-ref in ConnectivityPlugin.o
      "_OBJC_CLASS_$_FlutterEventChannel", referenced from:
          objc-class-ref in ConnectivityPlugin.o
      "_FlutterMethodNotImplemented", referenced from:
          -[FLTConnectivityPlugin handleMethodCall:result:] in ConnectivityPlugin.o
    ld: symbol(s) not found for architecture x86_64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Flutter Doctor**

```
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.2 19C57, locale en-US)
    • Flutter version 1.12.13+hotfix.5 at /Users/deeptibelsare/Documents/Flutter-sdk/flutter
    • Framework revision 27321ebbad (3 months ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/deeptibelsare/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = /Users/deeptibelsare/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/deeptibelsare/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed instructions.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 34.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] Connected device (1 available)
    • iPhone 11 Pro Max • BBC1F461-DD1E-4149-94DE-BFB7A8DFAA65 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)

! Doctor found issues in 1 category.

```

Appreciate any help in resolving this issue.

**Comment by VladyslavBondarenko** [comment] 2020-03-09 11:23
Hi @DK15 
do you use [connectivity plugin](https://pub.dev/packages/connectivity)? what version?
can you check whether are you experiencing this with the last stable version or the last master or dev?

**Comment by lesnitsky** [comment] 2020-03-09 11:25
I have the same issue on `Flutter 1.15.19-pre.9 • channel master` using vscode
```
Undefined symbols for architecture x86_64:
      "_OBJC_CLASS_$_UniLinksPlugin", referenced from:
          objc-class-ref in GeneratedPluginRegistrant.o
      "_OBJC_CLASS_$_SqflitePlugin", referenced from:
          objc-class-ref in GeneratedPluginRegistrant.o
      "_OBJC_CLASS_$_FLTPackageInfoPlugin", referenced from:
          objc-class-ref in GeneratedPluginRegistrant.o
      "_OBJC_CLASS_$_FLTImagePickerPlugin", referenced from:
          objc-class-ref in GeneratedPluginRegistrant.o
      "_OBJC_CLASS_$_FLTGoogleSignInPlugin", referenced from:
          objc-class-ref in GeneratedPluginRegistrant.o
      "_OBJC_CLASS_$_FLTUrlLauncherPlugin", referenced from:
          objc-class-ref in GeneratedPluginRegistrant.o
      "_OBJC_CLASS_$_FLTSharedPreferencesPlugin", referenced from:
          objc-class-ref in GeneratedPluginRegistrant.o
      "_OBJC_CLASS_$_FLTPathProviderPlugin", referenced from:
          objc-class-ref in GeneratedPluginRegistrant.o
      "_OBJC_CLASS_$_FLTFirebaseMessagingPlugin", referenced from:
          objc-class-ref in GeneratedPluginRegistrant.o
      "_OBJC_CLASS_$_FLTKeyboardVisibilityPlugin", referenced from:
          objc-class-ref in GeneratedPluginRegistrant.o
      "_OBJC_CLASS_$_FLTDeviceInfoPlugin", referenced from:
          objc-class-ref in GeneratedPluginRegistrant.o
```

@VladyslavBondarenko my output suggests that the issue is not about the connectivity plugin (all plugins fail)

**Comment by VladyslavBondarenko** [comment] 2020-03-09 12:15
Similar to https://github.com/flutter/flutter/issues/51992

**Comment by DK15** [comment] 2020-03-09 12:21
@VladyslavBondarenko Yes I use `connectivity` plugin version `0.4.2`. I updated it to latest version but it didn't help. I am a bit apprehensive to upgrade to latest stable since it might break few other things for me (as I had noticed earlier as well).

**Comment by VladyslavBondarenko** [comment] 2020-03-09 13:10
@DK15 `0.4.2` is already year old version, can you try with the last `0.4.8+1`?

**Comment by jmagman** [comment] 2020-03-09 20:06
Duplicate of https://github.com/flutter/flutter/issues/51992

**Closed by jmagman** 2020-03-09 20:06 UTC
Labels: tool, waiting for customer response, ⌺‬ platform-ios
