### ISSUE TITLE
Redundant Icons Card

### ISSUE THREAD

**Issue by wmleler** [flutter/flutter#10042] opened 2017-05-12 17:22 UTC
Visit https://flutter.io/widgets/assets/
Notice that the card for "Icon" is shown twice.

![screen shot 2017-05-12 at 10 21 52 am](https://cloud.githubusercontent.com/assets/50357/26009283/f2716bb4-36fc-11e7-9afe-1a70417bdedb.png)

**Comment by sethladd** [comment] 2017-05-12 18:17
Thanks!

Dupe of https://github.com/flutter/flutter/issues/10003

**Closed by sethladd** 2017-05-12 18:17 UTC
Labels: dev: docs - website
