### ISSUE TITLE
[tool_crash] String: <57 characters>

### ISSUE THREAD

**Issue by mahdiqdi** [flutter/flutter#128129] opened 2023-06-02 18:06 UTC
## Command
```
flutter --no-color run --machine --device-id=4d00b5df65599097 --profile --dart-define=flutter.inspector.structuredErrors=true lib/main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
String: <57 characters>
```

```
```
[✓] Flutter (Channel stable, 3.10.0, on macOS 12.6.1 21G217 darwin-x64, locale en-TR)
    • Flutter version 3.10.0 on channel stable at /Users/mac/tools/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 84a1e904f4 (3 weeks ago), 2023-05-09 07:41:44 -0700
    • Engine revision d44b5a94c9
    • Dart version 3.0.0
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/mac/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio Preview.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio
    • Android Studio at /Applications/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] Connected device (3 available)
    • SM N900 (mobile) • 4d00b5df65599097 • android-arm    • Android 5.0 (API 21)
    • macOS (desktop)  • macos            • darwin-x64     • macOS 12.6.1 21G217 darwin-x64
    • Chrome (web)     • chrome           • web-javascript • Google Chrome 113.0.5672.126

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 84a1e904f44f9b0e9c4510138010edcc653163f8
### Plugins
connectivity_plus-4.0.1
device_info-2.0.3
firebase_analytics-10.4.2
firebase_analytics_web-0.5.4+2
firebase_core-2.13.1
firebase_core_web-2.5.0
firebase_messaging-14.6.2
firebase_messaging_web-3.5.2
flutter_local_notifications-14.1.0
flutter_plugin_android_lifecycle-2.0.15
google_sign_in-6.1.3
google_sign_in_android-6.1.14
google_sign_in_ios-5.6.2
google_sign_in_web-0.12.0
image_picker-0.8.7+5
image_picker_android-0.8.6+16
image_picker_for_web-2.1.12
image_picker_ios-0.8.7+4
local_auth-2.1.6
local_auth_android-1.0.28
local_auth_ios-1.1.3
local_auth_windows-1.0.8
package_info_plus-4.0.2
path_provider-2.0.15
path_provider_android-2.0.27
path_provider_foundation-2.2.3
path_provider_linux-2.1.10
path_provider_windows-2.1.6
share_plus-7.0.2
sqflite-2.2.8+4
url_launcher-6.1.11
url_launcher_android-6.0.34
url_launcher_ios-6.1.4
url_launcher_linux-3.0.5
url_launcher_macos-3.0.5
url_launcher_web-2.0.16
url_launcher_windows-3.0.6
webview_flutter-4.2.1
webview_flutter_android-3.7.0
webview_flutter_wkwebview-3.4.3

**Comment by huycozy** [comment] 2023-06-05 05:25
Closing as duplicate of https://github.com/flutter/flutter/issues/108812 which has the same crash log (log is truncated). May be also related: https://github.com/flutter/flutter/issues/118400.

**Closed by huycozy** 2023-06-05 05:25 UTC
Labels: in triage
