### ISSUE TITLE
Template Project Exception: "A KeyUpEvent is dispatched, but the state shows that the physical key is not pressed."

### ISSUE THREAD

**Issue by QazCetelic** [flutter/flutter#101931] opened 2022-04-14 19:45 UTC
This is my first attempt trying Flutter, this error occurred with the default template (using the IntelliJ plugin).
It said that I should report it if it occurred in a "real application", I think this fits that, but I hope you don't mind if I've wasted your time if this wasn't a real problem.

## Steps to Reproduce

1. Create new project using IntelliJ plugin default settings except that I enabled the Web Target.
2. Run Project

**Expected results:** No exception

**Actual results:** Exception occurs

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      // This call to setState tells the Flutter framework that something has
      // changed in this State, which causes it to rerun the build method below
      // so that the display can reflect the updated values. If we changed
      // _counter without calling setState(), then the build method would not be
      // called again, and so nothing would appear to happen.
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: Center(
        // Center is a layout widget. It takes a single child and positions it
        // in the middle of the parent.
        child: Column(
          // Column is also a layout widget. It takes a list of children and
          // arranges them vertically. By default, it sizes itself to fit its
          // children horizontally, and tries to be as tall as its parent.
          //
          // Invoke "debug painting" (press "p" in the console, choose the
          // "Toggle Debug Paint" action from the Flutter Inspector in Android
          // Studio, or the "Toggle Debug Paint" command in Visual Studio Code)
          // to see the wireframe for each widget.
          //
          // Column has various properties to control how it sizes itself and
          // how it positions its children. Here we use mainAxisAlignment to
          // center the children vertically; the main axis here is the vertical
          // axis because Columns are vertical (the cross axis would be
          // horizontal).
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}

```

</details>

<details>
  <summary>Logs</summary>

```
```

```
No issues found! (ran in 2.6s)
```

```
[✓] Flutter (Channel stable, 2.10.3, on Fedora 34 (KDE Plasma) 5.16.18-100.fc34.x86_64, locale en_US.UTF-8)
    • Flutter version 2.10.3 at /home/qaz/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (6 weeks ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] IntelliJ IDEA Community Edition (version 2021.2)
    • IntelliJ at /home/qaz/.local/share/JetBrains/Toolbox/apps/IDEA-C/ch-0/212.5457.46
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Community Edition (version 2021.3)
    • IntelliJ at /home/qaz/.local/share/JetBrains/Toolbox/apps/IDEA-C/ch-0/213.6777.52
    • Flutter plugin version 65.1.4
    • Dart plugin version 213.7227

[✓] VS Code
    • VS Code at /snap/code/current
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • Linux (desktop) • linux • linux-x64 • Fedora 34 (KDE Plasma) 5.16.18-100.fc34.x86_64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 3 categories.
```

</details>

![image](https://user-images.githubusercontent.com/51381523/163464325-4d9bbf00-a0e8-41cd-b3d7-0a659e14bf82.png)

UPDATE: I've restarted IntelliJ and now it runs but still prints out the following errors:
```
/snap/flutter/current/usr/bin/ld: warning: /usr/lib/gcc/x86_64-redhat-linux/11/../../../../lib64/crt1.o: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0008002

(stoko:166464): Gtk-WARNING **: 21:45:57.846: Locale not supported by C library.
	Using the fallback 'C' locale.
```

**Comment by maheshmnj** [comment] 2022-04-18 07:14
Hi @QazCetelic, Thanks for reporting the issue. There have been [several reports of similar error ](https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+%22A+KeyUpEvent+is+dispatched%22) in the console. Which is intermittent can you please try to identify when this issue occurs and share more info? 
from your logs, it looks like this seems to have happened on pressing "U" Key, But doing so doesn't seem to reproduce error on my side.

> UPDATE: I've restarted IntelliJ and now it runs but still prints out the following errors:

This seems like a different issue can you please file that as a separate issue and provide all the details requested in the issue template?


<details>
<summary>flutter doctor -v (Linux)</summary>

```
[✓] Flutter (Channel stable, 2.10.4, on Ubuntu 20.04.4 LTS 5.13.0-30-generic, locale en_GB.UTF-8)
    • Flutter version 2.10.4 at /home/mahesh/Development/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (12 days ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /home/mahesh/Android/Sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /home/mahesh/Downloads/android-studio-2020.3.1.25-linux/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 2020.3)
    • Android Studio at /home/mahesh/Downloads/android-studio-2020.3.1.25-linux/android-studio
    • Flutter plugin version 63.2.1
    • Dart plugin version 203.8452
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.64.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.38.1

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 20.04.4 LTS 5.13.0-30-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 98.0.4758.102

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by QazCetelic** [comment] 2022-04-18 08:10
I wasn’t pressing any key when I started the app. I was targeting Linux because I was developing it using the Fedora distro. I’m starting to think this might be some obscure toolchain issue if that is the case or it’s a duplicate feel free to close this issue. I’m currently not able to investigate further, but I’ll try to figure it out soon.

**Comment by maheshmnj** [comment] 2022-04-18 12:50
> I’m starting to think this might be some obscure toolchain issue if that is the case or it’s a duplicate feel free to close this issue

However, We would need the complete readable logs to investigate further. The logs share aren;t readable In the future whenever sharing logs or code snippets please do share them as a text instead of image.

> I’m currently not able to investigate further, but I’ll try to figure it out soon.

Feel free to write back  if you were able to dig further on this issue.

**Comment by QazCetelic** [comment] 2022-04-19 09:06
I'm unable to reproduce the issue. I do get these errors, but I feel like these are unrelated tot the original issue. Finding the cause of the original issue seems like a lost cause, so I personally think this issue can be closed unless you know of another method to reproduce it.

```
Launching lib/main.dart on Linux in debug mode...
Building Linux application...
/snap/flutter/current/usr/bin/ld: warning: /usr/lib/gcc/x86_64-redhat-linux/11/../../../../lib64/crt1.o: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0008002

(stoko:9029): Gtk-WARNING **: 10:58:45.893: Locale not supported by C library.
	Using the fallback 'C' locale.
Debug service listening on ws://127.0.0.1:44821/Gv7jT-c_b0U=/ws
Syncing files to device Linux...
```

**Comment by maheshmnj** [comment] 2022-04-19 10:27
Thanks for the update @QazCetelic, I am  going to close this then, In case you have more info for us to investigate further feel free to file a new issue or comment on this issue and we will reopen it.

**Closed by maheshmnj** 2022-04-19 10:27 UTC
Labels: in triage
