### ISSUE TITLE
Scroll position is not saved in NestedScrollView

### ISSUE THREAD

**Issue by autolainen** [flutter/flutter#89582] opened 2021-09-07 12:44 UTC
I compiled and run example from NestedScrollView description. In this example nested scrollable lists expected to save and restore its scroll position while tabs are switched. When lists scrolled forward everything works as expected but if you scroll (or flinge slightly) any of the lists backward, the scroll position of the list on the other tab will be reset to 0.
```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        title: 'Flutter Demo',
        theme: ThemeData(primarySwatch: Colors.blue),
        home: MyHomePage());
  }
}

class MyHomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final List<String> _tabs = <String>['Tab 1', 'Tab 2'];
    return DefaultTabController(
        length: _tabs.length, // This is the number of tabs.
        child: Scaffold(
            body: NestedScrollView(
                headerSliverBuilder:
                    (BuildContext context, bool innerBoxIsScrolled) {
                  return <Widget>[
                    SliverOverlapAbsorber(
                        handle: NestedScrollView.sliverOverlapAbsorberHandleFor(
                            context),
                        sliver: SliverAppBar(
                            title: const Text('Books'),
                            pinned: true,
                            expandedHeight: 150.0,
                            forceElevated: innerBoxIsScrolled,
                            bottom: TabBar(
                                tabs: _tabs
                                    .map((String name) => Tab(text: name))
                                    .toList())))
                  ];
                },
                body: TabBarView(
                    children: _tabs.map((String name) {
                  return SafeArea(
                      top: false,
                      bottom: false,
                      child: Builder(builder: (BuildContext context) {
                        return CustomScrollView(
                            key: PageStorageKey<String>(name),
                            slivers: <Widget>[
                              SliverOverlapInjector(
                                  handle: NestedScrollView
                                      .sliverOverlapAbsorberHandleFor(context)),
                              SliverPadding(
                                  padding: const EdgeInsets.all(8.0),
                                  sliver: SliverFixedExtentList(
                                      itemExtent: 48.0,
                                      delegate: SliverChildBuilderDelegate(
                                          (BuildContext context, int index) {
                                        return ListTile(
                                            title: Text('Item $index'));
                                      }, childCount: 30)))
                            ]);
                      }));
                }).toList()))));
  }
}
```

**Comment by TahaTesser** [comment] 2021-09-07 12:47
Hi @autolainen 
I see there's an open issue addressing the case you described.
Please follow up on that issue, Closing as duplicate of https://github.com/flutter/flutter/issues/36419
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-09-07 12:47 UTC
Labels: in triage
