### ISSUE TITLE
Error: Getting current working directory failed, path = '' (OS Error: Interrupted system call, errno = 4)

### ISSUE THREAD

**Issue by haamaanaa** [flutter/flutter#70940] opened 2020-11-20 14:36 UTC
## Steps to Reproduce

1. upgraded to MacOS Big Sur: 
      System Version: macOS 11.0.1 (20B29)
      Kernel Version: Darwin 20.1.0
2. running any unit test that flutter project already had before updating laptop OS version

did try to clean flutter pub cache with flutter pub cache repair, and also by deleting said cache folder from laptop and then running flutter pub get again on project and running tests.... still failed

**Expected results:** 

unit test to run successfully at all times
(In Catalina OS version, same test(s) run without fail)

**Actual results:** 

at random runs the test fails 

  Verbose Log
```
[  +28 ms] test 0: awaiting initial result for pid 20741
00:04 +0: loading /Users/me/dev-env/app/packages/collector/test/collector_test.dart                [ +810 ms] test 0: process with pid 20741 connected to test harness
[   +1 ms] test 0: awaiting test result for pid 20741
00:04 +0 -1: loading /Users/me/dev-env/app/packages/collector/test/collector_test.dart [E]         
  Failed to load "/Users/me/dev-env/app/packages/collector/test/collector_test.dart": Getting current working directory failed, path = '' (OS Error: Interrupted system call, errno = 4)
  dart:io-patch/directory_patch.dart 64:5                                                                                 _uriBaseClosure
  dart:core-patch/uri_patch.dart 21:41                                                                                    Uri.base
  package:path/src/style.dart 42:14                                                                                       Style._getPlatformStyle
  package:path/src/style.dart 33:33                                                                                       Style.platform
  package:path/src/style.dart                                                                                             Style.platform
  package:flutter_test/src/_goldens_io.dart 71:52                                                                         LocalFileComparator._getPath
  package:flutter_test/src/_goldens_io.dart 75:34                                                                         LocalFileComparator._getBasedir
  package:flutter_test/src/_goldens_io.dart 67:17                                                                         new LocalFileComparator
  /var/folders/rz/dt7c_sjs3hv2hk3pxz9qf2f80000gn/T/flutter_tools.xUGs3h/flutter_test_listener.9FVTCU/listener.dart 42:24  main.<fn>
  package:test_api/src/remote_listener.dart 68:27                                                                         RemoteListener.start.<fn>.<fn>.<fn>
  package:test_api/src/remote_listener.dart 65:25                                                                         RemoteListener.start.<fn>.<fn>.<fn>
  dart:async/zone.dart 1186:13                                                                                            _rootRun
  dart:async/zone.dart 1090:19                                                                                            _CustomZone.run
  dart:async/zone.dart 1626:10                                                                                            _runZoned
  dart:async/zone.dart 1614:12                                                                                            runZonedGuarded
  package:test_api/src/remote_listener.dart 65:9                                                                          RemoteListener.start.<fn>.<fn>
  dart:async/zone.dart 1186:13                                                                                            _rootRun
  dart:async/zone.dart 1090:19                                                                                            _CustomZone.run
  dart:async/zone.dart 1626:10                                                                                            _runZoned
  dart:async/zone.dart 1546:10                                                                                            runZoned
  package:test_api/src/backend/stack_trace_formatter.dart 42:7                                                            StackTraceFormatter.asCurrent
  package:test_api/src/remote_listener.dart 64:29                                                                         RemoteListener.start.<fn>
  dart:async/zone.dart 1186:13                                                                                            _rootRun
  dart:async/zone.dart 1090:19                                                                                            _CustomZone.run
  dart:async/zone.dart 1626:10                                                                                            _runZoned
  dart:async/zone.dart 1546:10                                                                                            runZoned
  package:test_api/src/suite_channel_manager.dart 35:7                                                                    SuiteChannelManager.asCurrent
  package:test_api/src/remote_listener.dart 63:27                                                                         RemoteListener.start
  /var/folders/rz/dt7c_sjs3hv2hk3pxz9qf2f80000gn/T/flutter_tools.xUGs3h/flutter_test_listener.9FVTCU/listener.dart 15:25  serializeSuite
  /var/folders/rz/dt7c_sjs3hv2hk3pxz9qf2f80000gn/T/flutter_tools.xUGs3h/flutter_test_listener.9FVTCU/listener.dart 40:36  main
  dart:ui/hooks.dart 136:25                                                                                               _runMainZoned.<fn>.<fn>
  dart:async/zone.dart 1186:13                                                                                            _rootRun
  dart:async/zone.dart 1090:19                                                                                            _CustomZone.run
  dart:async/zone.dart 1626:10                                                                                            _runZoned
  dart:async/zone.dart 1614:12                                                                                            runZonedGuarded
  dart:ui/hooks.dart 132:5                                                                                                _runMainZoned.<fn>
  dart:isolate-patch/isolate_patch.dart 283:19                                                                            _delayEntrypointInvocation.<fn>
  dart:isolate-patch/isolate_patch.dart 184:12                                                                            _RawReceivePortImpl._handleMessage
```

     Run `flutter analyze`
no issues

      Run `flutter doctor -v`

[✓] Flutter (Channel stable, 1.22.4, on macOS 11.0.1 20B29 darwin-x64, locale en-FI)
    • Flutter version 1.22.4 at /Users/me/dev-env/flutter
    • Framework revision 1aafb3a8b9 (7 days ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/me/Library/Android/sdk
    • Platform android-30, build-tools 29.0.2
    • ANDROID_HOME = /Users/me/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

 
[!] Connected device                          
    ! No devices available

! Doctor found issues in 1 category.

**Comment by MoustafaMesbah** [comment] 2020-11-20 15:26
+1

**Comment by thisdarktao** [comment] 2020-11-23 20:49
Experiencing the same issue.

```
Л flutter doctor -v
[✓] Flutter (Channel stable, 1.22.4, on macOS 11.0.1 20B29 darwin-x64, locale
    en-GB)
    • Flutter version 1.22.4 at /Users/adam/Development/flutter
    • Framework revision 1aafb3a8b9 (10 days ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4


[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/adam/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Users/adam/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.6953283/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.9.3

[!] Android Studio (version 4.1)
    • Android Studio at /Users/adam/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.6953283/Android
      Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.49.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2


[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```

**Comment by haamaanaa** [comment] 2020-11-24 07:52
@jonahwilliams any ideas on what is causing this? or even when there might be a fix?

**Comment by haamaanaa** [comment] 2020-11-25 09:12
https://github.com/dart-lang/sdk/issues/44214

different error code / number, but coming from same class / line number.

**Comment by jmagman** [comment] 2020-11-30 17:57
\cc @devoncarew another `current working directory failed` issue.  Should these cases be moved to dart-lang/sdk for investigation?

**Comment by devoncarew** [comment] 2020-11-30 22:34
The fix for that sdk issue landed (https://github.com/dart-lang/sdk/commit/ce272daae8a881a5199fc749a4643d36b4fa6fc4), but w/o digging into it I would guess that that specific problem only existing on dev releases of the sdk and not for flutter stable.

**Comment by haamaanaa** [comment] 2020-12-03 07:40
I was using 1.22.4 stable flutter and error persisted with unit tests

Had to actually downgrade back to Catalina to resume working environment, so any updates on this issue would be much appriciated

**Comment by PieterAelse** [comment] 2020-12-04 13:39
I also run into this issue when running tests with Flutter 1.22.4, but I'm still on macOS Catalina.. 
So what's the real issue here?

**Comment by sgorbyo** [comment] 2020-12-06 23:02
Same error for me on Big Sur

flutter doctor -v
[✓] Flutter (Channel stable, 1.22.4, on macOS 11.0.1 20B29 darwin-x64, locale it-IT)
    • Flutter version 1.22.4 at /Users/danilo/DevEnvironments/flutter
    • Framework revision 1aafb3a8b9 (3 weeks ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/danilo/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.0

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin installed
    • Dart plugin version 201.9245
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.48.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

**Comment by remonh87** [comment] 2020-12-08 09:23
Am having the same on Big Sur with Flutter stable.Spend quite sometime playing with different parameters. I found out that if I run `flutter test --no-test-assets` it has a higher chance of passing (around 1/3 passes now). However this is not a sustainable solution. Really hope this gets fixed soon.

**Comment by jmagman** [comment] 2020-12-08 18:12
> The fix for that sdk issue landed ([dart-lang/sdk@ce272da](https://github.com/dart-lang/sdk/commit/ce272daae8a881a5199fc749a4643d36b4fa6fc4)), but w/o digging into it I would guess that that specific problem only existing on dev releases of the sdk and not for flutter stable.

@devoncarew This is reported on 1.22.4 stable.  Can we move this to dart for investigation?

**Comment by devoncarew** [comment] 2020-12-08 18:42
@jmagman I'm really not the right person to dig into this. Perhaps @a-siva, as this might be a dart:io issue on Bug Sur?

**Comment by jmagman** [comment] 2020-12-08 18:43
Sorry @devoncarew, I totally missed that your comment was replying to a comment about a different issue.

**Comment by haamaanaa** [comment] 2020-12-15 07:42
Hi! Was solving this moved somewhere else or is someone still looking into this issue?

any link to dart:io issue if this is being fixed in that project?

**Comment by haamaanaa** [comment] 2020-12-16 08:07
>  Big Sur, has new APIs that prevent Little Snitch from working the same way. The new APIs don’t permit Little Snitch to inspect or block any OS level processes. Additionally, the new rules in macOS 11 even hobble VPNs so that Apple apps will simply bypass them.

https://sneak.berlin/20201112/your-computer-isnt-yours/

any ideas if that "new APIs don’t permit.... inspect or block any OS level processes" is the cause here? is that just some tin foil hat stuff?

**Comment by jmagman** [comment] 2020-12-17 23:24
I just ran `flutter test` 20 times on Big Sur machine and it passed every time.  This was a new machine and not migrated from Catalina (it's an M1).

I filed https://github.com/dart-lang/sdk/issues/44509 so the dart team can take a look.

**Closed by jmagman** 2020-12-17 23:24 UTC
Labels: dependency: dart, passed first triage, severe: crash, 💻platform-bigsur

**Comment by sgorbyo** [comment] 2020-12-18 08:21
Closed?
So all the reporter are just crazy stupid people?

**Comment by haamaanaa** [comment] 2021-02-10 08:59
so solution is to buy every one new macbooks?

**Comment by ihorvitruk** [comment] 2021-02-16 20:10
I faced the same issue, when I migrated to Big Sur. Now I have Big Sur 11.2, but the issue with tests running is still reproducible.

I managed to find temporary workaround for it: to run command with `concurrency` parameter set to 1 (by default it is 10):
``` 
flutter test --concurrency 1
```
In 95% of runs, error does not appear, but in rest 10% - it does. 
I suppose, error is somehow related to **filesystem access** or some **access race condition**. And I do not rely on my temporary solution, because it decrease running time (because only 1 job is used). 

I believe the issue will be investigated and fixed asap.

**Comment by jmagman** [comment] 2021-02-16 20:20
@ihorvitruk Can you update https://github.com/dart-lang/sdk/issues/44509 with your findings so the dart team can see it?

**Comment by kotlincodes** [comment] 2021-04-20 11:57
I am facing this issue randomly in mac os big sur

**Comment by a-siva** [comment] 2021-04-20 22:17
Is the only way to reproduce this problem is running an existing flutter project unit test after upgrading to Mac OS Big Sur ?

**Comment by kuhnroyal** [comment] 2021-04-26 15:15
I can reproduce this almost every time with Anti-Virus enabled. Disable it and everything works.

**Comment by ihorvitruk** [comment] 2021-04-26 19:37
See [this](https://github.com/dart-lang/sdk/issues/44509#issuecomment-822627552)

**Comment by haamaanaa** [comment] 2021-05-06 06:41
with latest release of 11.3 macOS version, issue seems to have been fixed.

Might also be that Microsoft silently fixed something in MS ATP

Anyways, works for me. No OS Error anymore in test runs.
