### ISSUE TITLE
Running "flutter test --machine --coverage" does not generate a coverage report

### ISSUE THREAD

**Issue by coreysprague** [flutter/flutter#56675] opened 2020-05-08 14:45 UTC
Issue #30108 added the ability to now run flutter test with both the --machine and --coverage arguments together. The command now succeeds, however, no coverage report is generated (which defeats the purpose of wanting to run both commands together).

Steps to repro:
- create a new project: ```flutter create sample```
- ```cd sample```
- ```flutter test --machine --coverage```
Observe that no coverage directory is created
- ```flutter test --coverage```
Observe that a coverage directory is properly created

For context, running both of these arguments together is useful in order to get test & code coverage reports from a single invocation of flutter test in CI scenarios. Otherwise, if you want both, you have to run your test suite twice.

Flutter doctor output:
```
~/Library/Code/sample $ flutter doctor -v
[✓] Flutter (Channel stable, v1.17.0, on Mac OS X 10.15.4 19E266, locale en-US)
    • Flutter version 1.17.0 at /Users/cosprague/Library/Code/flutter
    • Framework revision e6b34c2b5c (6 days ago), 2020-05-02 11:39:18 -0700
    • Engine revision 540786dd51
    • Dart version 2.8.1

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/cosprague/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.45.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.1

[✓] Connected device (2 available)
    • iPhone 11 Pro Max                     • 359B4892-0E76-4165-BAA7-6A5C885E466F • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-13-4 (simulator)
    • iPad Pro (12.9-inch) (4th generation) • 7D3B9249-3558-4636-B1BA-30BA59ACC7CD • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-13-4 (simulator)

• No issues found!
```

**Comment by TahaTesser** [comment] 2020-05-08 16:21
<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel stable, v1.17.0, on Mac OS X 10.15.4 19E287, locale en-GB)
    • Flutter version 1.17.0 at /Users/tahatesser/Code/flutter_stable
    • Framework revision e6b34c2b5c (6 days ago), 2020-05-02 11:39:18 -0700
    • Engine revision 540786dd51
    • Dart version 2.8.1

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/tahatesser/Code/SDK
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.45.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.1

 
[✓] Connected device (1 available)            
    • SM M305F • 32003c30dc19668f • android-arm64 • Android 10 (API 29)

• No issues found!

``` 

</details>

**Comment by NanYeYe** [comment] 2020-05-11 03:37
I have this problem, too.

**Comment by jason-simmons** [comment] 2020-05-11 23:57
This has been fixed on the current master branch (see https://github.com/flutter/flutter/commit/9cc69d47)

@jonahwilliams

**Comment by NanYeYe** [comment] 2020-05-13 07:02
> This has been fixed on the current master branch (see [9cc69d4](https://github.com/flutter/flutter/commit/9cc69d47))
> 
> @jonahwilliams

-------------------------------------------------------------------
I change branch to master and it can use < `flutter test --machine --coverage`>
But, i can not use <`flutter test --machine --coverage | tojunit > test-results.xml`>
Error Msg:
![image](https://user-images.githubusercontent.com/11953895/81781419-a8b7bc00-952a-11ea-8ed4-dffca5c04d62.png)
@jason-simmons @jonahwilliams

**Comment by kuhnroyal** [comment] 2020-05-19 21:39
I can confirm that the output changed and can no longer be parsed with `junitreport:tojunit`.
This is due to new lines of the observatory URL in the output which I am not sure if they should be there. There is alway one prior empty line for each event.
```

[{"event":"test.startedProcess","params":{"observatoryUri":"http://127.0.0.1:54903/oOizQbM20p8=/"}}]
```
If I remove these line from the output then everything works.

**Comment by rspilker** [comment] 2020-05-26 20:22
If I look at the output, I see three things that are different. The `--machine` is supposed to produce a `ndjson` or `jsonl` file.

When using `--machine --coverage`
1. The fist line is not a valid json value: `Running "flutter pub get" in fluttertest...                         1,7s`
2. There is an empty line
3. followed by an unspecified list: `[{"event":"test.startedProcess","params":{"observatoryUri":"http://127.0.0.1:59667/T1vwpBGVriE=/"}}]`

Although it is not according to the `--machine` specification, I can modify `tojunit` to ignore every line that does not start with a brace `{`. It would hide the problem, but I prefer a more permanent solution.

**Comment by kuhnroyal** [comment] 2020-05-27 08:09
@rspilker You can always run the tests with `--no-pub`. The first line only occurs when you didn't run `pub get` before the tests.

**Comment by tarek360** [comment] 2020-12-03 01:05
### To make it works:
You have to specify your tests folder.

for example, if your test folder is `/test`, then add "test" to the command
```
 flutter test --machine --coverage test
```

**Comment by TahaTesser** [comment] 2021-01-29 13:18
Hi @coreysprague 
Both `flutter test --machine --coverage` and `flutter test --coverage` are now creating coverage directory and `lcov.info` file on the latest `stable` and `master`.

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 1.22.6, on macOS 11.1 20C69 darwin-x64, locale en-GB)
    • Flutter version 1.22.6 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 9b2d32b605 (7 days ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (1 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios • iOS 14.4

! Doctor found issues in 1 category.
```
```bash
[✓] Flutter (Channel master, 1.26.0-18.0.pre.73, on macOS 11.1 20C69 darwin-x64, locale en-GB)
    • Flutter version 1.26.0-18.0.pre.73 at /Users/tahatesser/Code/flutter_master
    • Framework revision 791edc230d (5 hours ago), 2021-01-28 21:54:03 -0800
    • Engine revision 4ba79a34a0
    • Dart version 2.12.0 (build 2.12.0-272.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (3 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios            • iOS 14.4
    • macOS (desktop)        • macos                     • darwin-x64     • macOS 11.1 20C69 darwin-x64
    • Chrome (web)           • chrome                    • web-javascript • Google Chrome 88.0.4324.96

• No issues found!
```

</details>

Closing as fixed. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-01-29 13:18 UTC
Labels: P4, a: tests, engine, found in release: 1.17, has reproducible steps
