### ISSUE TITLE
i can try to solve the issue . give me access

### ISSUE THREAD

**Issue by leylinazi99** [flutter/flutter#137026] opened 2023-10-21 23:57 UTC
i can try to solve the issue . give me access

_Originally posted by @mandgeprathamesh in https://github.com/flutter/flutter/issues/136126#issuecomment-1751792820_

**Comment by stuartmorgan** [comment] 2023-10-22 00:09
Closing as this does not describe an issue or feature request.

If you are interested in contributing a fix for the issue that was marked as a duplicate of, please see our contributing guide.

**Closed by stuartmorgan** 2023-10-22 00:09 UTC
