### ISSUE TITLE
[in_app_purchase] - macOS Support

### ISSUE THREAD

**Issue by Ahmadre** [flutter/flutter#89507] opened 2021-09-05 15:13 UTC
## Use case

There's no macOS implementation for in_app_purchase.

I added that and you can view the PR here: https://github.com/flutter/plugins/pull/4313

## Proposal

Because the Plugin Developers added a platform_interface to in_app_purchase, it is easily possible now to add a new platform as clean as possible, so I tried to do that here. If you have any concerns or questions, please leave a comment in the PR or here.

Thanks :)

**Comment by stuartmorgan** [comment] 2021-09-05 17:26
Duplicate of https://github.com/flutter/flutter/issues/84391

**Closed by stuartmorgan** 2021-09-05 17:26 UTC
