### ISSUE TITLE
Android sdkmanager tool not found

### ISSUE THREAD

**Issue by raphtlw** [flutter/flutter#51854] opened 2020-03-03 15:14 UTC
## Steps to Reproduce

1. Run `flutter doctor`
2. It will say that sdkmanager is not found
3. Error

## Logs

```
```

```
Android sdkmanager tool not found
(C:\Users\raphp\AppData\Local\Android\sdk\tools\bin\sdkmanager).
Try re-installing or updating your Android SDK,
visit https://flutter.dev/setup/#android-setup for detailed instructions.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      AndroidLicenseValidator.runLicenseManager
(package:flutter_tools/src/android/android_workflow.dart:311:7)
#2      Doctor.diagnose (package:flutter_tools/src/doctor.dart:243:38)
#3      DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:59:39)
#4      FlutterCommand.verifyThenRunCommand
(package:flutter_tools/src/runner/flutter_command.dart:615:18)
#5      _asyncThenWrapperHelper.<anonymous closure>
(dart:async-patch/async_patch.dart:73:64)
#6      _rootRunUnary (dart:async/zone.dart:1134:38)
#7      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#8      _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#9      Future._propagateToListeners.handleValueCallback
(dart:async/future_impl.dart:680:45)
#10     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#11     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#12     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
#13     _rootRun (dart:async/zone.dart:1126:13)
#14     _CustomZone.run (dart:async/zone.dart:1023:19)
#15     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#16     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#17     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#18     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#19     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#20     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)
```

**Comment by TahaTesser** [comment] 2020-03-03 15:18
Duplicate of [#51712](https://github.com/flutter/flutter/issues/51712)

**Closed by TahaTesser** 2020-03-03 15:18 UTC
