### ISSUE TITLE
Calling PathMetrics.length causes a mutation in the PathMetrics object

### ISSUE THREAD

**Issue by zbarryte-luminopia** [flutter/flutter#48980] opened 2020-01-16 18:41 UTC
## Steps to Reproduce

1. Create a new flutter project, and replace the contents of your main.dart file with the following:
```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Page(),
    );
  }
}

class Page extends StatefulWidget {
  @override
  State<StatefulWidget> createState() => _PageState();
}

class _PageState extends State<Page> {
  @override
  void initState() {
    super.initState();
    final path = Path()
      ..moveTo(0, 0)
      ..lineTo(1, 1)
      ..lineTo(1, 0)
      ..close();
    final metrics = path.computeMetrics();
    print('1st time print metrics length: ${metrics.length}');
    print('2nd time print metrics length: ${metrics.length}');
  }

  @override
  Widget build(BuildContext context) {
    return Container();
  }
}

```
2. Launch the application on an iOS device or simulator.
3. Observe the logs.

**Expected results:** It was expected that both print statements would log the same value for length: 1.

**Actual results:** Instead, 1 was logged the first time, but the second time, 0 was logged.  No changes were made to the `PathMetrics` object between the print statements, so it is unexpected that the object would have mutated simply by querying a property of it.

<details>

Output of `flutter analyze`:

```
Analyzing metrics_defect...                                             
No issues found! (ran in 3.6s)
```

Output of `flutter doctor -v`:

```
[✓] Flutter (Channel master, v1.13.3-pre.31, on Mac OS X 10.14.5 18F132, locale en-US)
    • Flutter version 1.13.3-pre.31 at /Users/me/Library/Flutter/flutter
    • Framework revision ba73cfc149 (4 weeks ago), 2019-12-16 13:34:17 -0800
    • Engine revision e0e0ac0a68
    • Dart version 2.8.0 (build 2.8.0-dev.0.0 45db297095)

 
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/me/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/me/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    • CocoaPods version 1.7.4

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 34.0.2
    • Dart plugin version 183.5901
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[✓] Connected device (1 available)
    • iPad (7th generation) • 57D859A7-57D0-4FE6-BD06-4BE65D21B70C • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-13-2 (simulator)

! Doctor found issues in 1 category.
```

The one issue listed here does not affect the output of this defect, because it is an Android issue, and this was run on an iOS simulator.  The same result occurs when running on an iOS device.

</details>

**Comment by zbarryte-luminopia** [comment] 2020-01-16 18:43
n.b. This issue was filed, because issue 27139 was closed, but the defect still exists.

**Comment by zbarryte-luminopia** [comment] 2020-01-16 18:44
@dnfield - Here is the issue.  I've tagged you, as requested.

**Comment by dnfield** [comment] 2020-01-16 18:50
This is a little different than the linked bug.

` final metrics = path.computeMetrics();` returns an `Iterable<PathMetric>`, and that iterable is not a list. To do what you want to do, you have to memoize it, for example by materializing it into a list.  This code should work as expected:

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Page(),
    );
  }
}

class Page extends StatefulWidget {
  @override
  State<StatefulWidget> createState() => _PageState();
}

class _PageState extends State<Page> {
  @override
  void initState() {
    super.initState();
    final path = Path()
      ..moveTo(0, 0)
      ..lineTo(1, 1)
      ..lineTo(1, 0)
      ..close();
    final metrics = path.computeMetrics().toList();
    print('1st time print metrics length: ${metrics.length}');
    print('2nd time print metrics length: ${metrics.length}');
  }

  @override
  Widget build(BuildContext context) {
    return Container();
  }
}
```

Note the addition of `toList()` :)

Can you verify this works as intended?

**Comment by dnfield** [comment] 2020-01-16 18:52
See for example https://dartpad.dev/c4721ced107d98202e8685abf294b3da

**Comment by zbarryte-luminopia** [comment] 2020-01-16 18:58
Ah, I see the difference between the other issue and this issue.

Yes, memoizing the `PathMetrics` object via `toList()` works, but is it really expected behavior that calling `PathMetrics.length` would allow mutation in the first place?  I understand that `PathMetrics` is an `Interable<PathMetric>`, but why does that mean that calling a property causes the object itself to mutate?

**Comment by dnfield** [comment] 2020-01-16 19:06
The interface is designed this way because iterating all the metrics can be expensive, and you might only want the first one.  A user who only cares about the first one shouldn't be forced to pay the cost of visiting all of them - but a user who always wants all of them should just call `toList` or use some other memoziing strategy.

I agree that having properties on `Iterable` that can cause mutation can be confusing, but that's a Dart language issue - and AFAIK, it's by design.  I personally try to avoid properties that have side effects/can be slow, but the Dart team took a different approach when designing Iterable.

I get this can be confusing - but this is also a fairly low level API. I'm going to close this as WAI.

**Comment by dnfield** [comment] 2020-01-16 19:08
Actually, I'll add that if you think it'd be helpful we could add documentation to `computeMetrics` to clarify this.

**Comment by zbarryte-luminopia** [comment] 2020-01-16 19:19
Thanks for your explanation!  Ah, I understand that this is a Dart choice, rather than a Flutter choice.

Definitely adding documentation on the Flutter side would be helpful!  Thank you!

**Closed** 2020-01-17 18:03 UTC
Labels: d: api docs, documentation, engine, waiting for PR to land (fixed)
