### ISSUE TITLE
Focus is not working as a child of MaterialApp on Mac OS

### ISSUE THREAD

**Issue by rockingdice** [flutter/flutter#87609] opened 2021-08-04 01:43 UTC
I don't know if I'm using it wrong, but I cannot find documents about this situation. I've made a minimal repro:

1. Create a project 
2. Replaced the main.dart with: 

<details> 
<summary>minimal code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return Focus(
      onKey: (node, event) {
        print(111);
        return false;
      },
      child: MaterialApp(
        title: 'Flutter Demo',
        theme: ThemeData(
          primarySwatch: Colors.blue,
        ),
        home: Focus(
          child: MyHomePage(title: 'Flutter Demo Home Page'),
          onKey: (n, e) {
            print(222);
            return false;
          },
        ),
      ),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key? key, required this.title}) : super(key: key);

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      // This call to setState tells the Flutter framework that something has
      // changed in this State, which causes it to rerun the build method below
      // so that the display can reflect the updated values. If we changed
      // _counter without calling setState(), then the build method would not be
      // called again, and so nothing would appear to happen.
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: Center(
        // Center is a layout widget. It takes a single child and positions it
        // in the middle of the parent.
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
``` 

</details>

3. Run it.
4. tap a single key then observe the log:
+ You can only find '111' but no '222'

Expected Behavior:
I can use Focus inside the MaterialApp.

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.2.3, on Mac OS X 10.15.7 19H2 darwin-x64, locale zh-Hans-CN)
    • Flutter version 2.2.3 at /Users/li9s/github/flutter
    • Framework revision f4abaa0735 (5 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/li9s/Library/Android/sdk
    • Platform android-30, build-tools 29.0.2
    • ANDROID_HOME = /Users/li9s/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/li9s/Library/Android/sdk
    • Java binary at: /Applications/Dev/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Dev/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Dev/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Connected device (3 available)
    • TAS AN00 (mobile) • GCL5T19B28016911 • android-arm64  • Android 10 (API 29)
    • macOS (desktop)   • macos            • darwin-x64     • Mac OS X 10.15.7 19H2 darwin-x64
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 92.0.4515.107

• No issues found!
```

</details>

**Comment by bernaferrari** [comment] 2021-08-04 02:06
Possible duplicate of https://github.com/flutter/flutter/issues/74287? There are some samples there for you to try.

**Comment by rockingdice** [comment] 2021-08-04 02:24
@bernaferrari I've discovered the `Focus` widget just from that issue, and found it's not working inside a `MaterialApp`, so I submitted a new issue. 
It's working fine outside of it, so I don't think it's the same issue. 
It seems that the `MaterialApp` is blocking all decendent `Focus` child widgets, and I don't find anything helpful from the `MaterialApp` or `Focus` documents.
I don't know if it's related with the different routes or others, just guess.

**Comment by hndrbrm** [comment] 2021-08-04 02:46
From what i understand from the documentation for [Focus](https://api.flutter.dev/flutter/widgets/Focus-class.html)
`A widget that manages a FocusNode to allow keyboard focus to be given to this widget and its descendants.`
`For keyboard events, onKey is called if FocusNode.hasFocus is true for this widget's focusNode, unless a focused descendant's onKey callback returns true when called.`

When i press tab on keyboard, it works.

**Comment by rockingdice** [comment] 2021-08-04 03:02
@hndrbrm Did you try the example code that I posted? Can you see `222` from the logs?

**Comment by hndrbrm** [comment] 2021-08-04 03:33
Yes i have tried those code on macOS and dartpad.dev. Both print `111` and `222` when i press `tab` key on keyboard.

**Comment by rockingdice** [comment] 2021-08-04 05:20
I tested it too, if you don't press the `Tab` key, it won't accept any events for `222`. So it's the issue that the MaterialApp doesn't focus on app starts, until a tab key pressed?

**Comment by hndrbrm** [comment] 2021-08-04 06:12
From what i read in the docs, i think `onKey` is about keyboard event.
It doesn't specify about mouse/touch event.

But we could use use `FocusNode.requestFocus()` or `FocusNode.unfocus()` to focus and unfocus it programatically. For example by using `GestureDetector` and put it into event detection such as `onTap`.

**Comment by TahaTesser** [comment] 2021-08-04 11:48
Hi @rockingdice 
When running the code on the latest stable on macOS, pressing any keys shows this result
```console
[        ] 💪 Running with sound null safety 💪
[        ] An Observatory debugger and profiler on macOS is available at:
           http://127.0.0.1:59879/v7cwDmgSJXQ=/
[ +694 ms] The Flutter DevTools debugger and profiler on macOS is available at:

http://127.0.0.1:9102?uri=http%3A%2F%2F127.0.0.1%3A59879%2Fv7cwDmgSJXQ%3D%2F
[+2313 ms] flutter: 222
[        ] flutter: 111
```

As you can see 222 is printed too

Can you please provide complete `flutter run -d macos -v` logs with a key pressed?
Thank you

**Comment by rockingdice** [comment] 2021-08-05 23:57
@TahaTesser I've changed a bit to log more details when pressing keys:
<details> 
<summary> Updated codes </summary>

```.dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return Focus(
      onKey: (node, event) {
        print('key event (111): ${event.data}');

        return false;
      },
      child: MaterialApp(
        title: 'Flutter Demo',
        theme: ThemeData(
          primarySwatch: Colors.blue,
        ),
        home: Focus(
          child: MyHomePage(title: 'Flutter Demo Home Page'),
          onKey: (n, e) {
            print('key event (222): ${e.data}');

            return false;
          },
        ),
      ),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key? key, required this.title}) : super(key: key);

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      // This call to setState tells the Flutter framework that something has
      // changed in this State, which causes it to rerun the build method below
      // so that the display can reflect the updated values. If we changed
      // _counter without calling setState(), then the build method would not be
      // called again, and so nothing would appear to happen.
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: Center(
        // Center is a layout widget. It takes a single child and positions it
        // in the middle of the parent.
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}

```
</details>

[test_focus.log](https://github.com/flutter/flutter/files/6942158/test_focus.log)


You can see when I'm pressing keys after the application starts, it only logs `111` UNTIL I press the `tab` key (keyCode:48).

**Comment by rockingdice** [comment] 2021-08-06 00:00
From my app, after navigation (Opening drawer and close it, repeat), the `tab` key cannot solve all the issues - It will fail eventually and after that, I cannot get key events anymore if I press the `tab` key again.

**Comment by TahaTesser** [comment] 2021-08-06 09:09
Hi @rockingdice 
I still see both 111 and 222 printed on macOS as the app launches when using arrows, but pressing letter keys only prints `111`. Are you suggesting letter keys should focus from `Focus` with 111 to `Focus` with 222? 


> From my app, after navigation (Opening drawer and close it, repeat), the tab key cannot solve all the issues - It will fail eventually and after that, I cannot get key events anymore even I press the tab key again.

Can you please provide a sample for this scenario we can get an idea of the real issue with such a use case
Thank you

**Comment by rockingdice** [comment] 2021-08-07 01:45
@TahaTesser Oh, I think it's the point. I want to listen to key events no matter what key is pressed (Imagine working on a game project), so the real scenario is only the keys that might change focus (Arrows, Tabs..) will trigger the event, right? 
I thought the `Focus` could be triggered by all keys instead of certain keys. Is that by design? Is there any widget that can intercept all events of keyboard no matter what key is pressed?

**Comment by TahaTesser** [comment] 2021-08-09 07:18
Hi @rockingdice 

> @TahaTesser Oh, I think it's the point. I want to listen to key events no matter what key is pressed (Imagine working on a game project), so the real scenario is only the keys that might change focus (Arrows, Tabs..) will trigger the event, right?

Yes, arrows and tab keys are expected to move focus but if you do the same thing with any random then how you would get input from those keys? if we plan to listen to those keys on a widget, the focus will move away and it will take make it impossible to get input while focusing on one widget

**Comment by rockingdice** [comment] 2021-08-09 07:32
I thought the `Focus` widget could get the events from its children. I'll put the `Focus` widget on top of the widget tree, and handle all kinds of keyboard events. So maybe I'm not on the correct way?

**Comment by TahaTesser** [comment] 2021-08-10 08:18
Hi @rockingdice 
If you add onfocus change on both focus widget , press keys, you can see focus is not moved and if you arrows or tabs, focused is moved so this is working as expected 
<details> 
<summary>minimal code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return Focus(
      onKey: (node, event) {
        print('key event (111): ${event.data}');

        return KeyEventResult.handled;
      },
      onFocusChange: (value) {
        print('outer focus change: ${value}');
      },
      child: MaterialApp(
        title: 'Flutter Demo',
        theme: ThemeData(
          primarySwatch: Colors.blue,
        ),
        home: Focus(
          child: MyHomePage(title: 'Flutter Demo Home Page'),
          onKey: (n, e) {
            print('key event (222): ${e.data}');

            return KeyEventResult.handled;
          },
          onFocusChange: (value) {
            print('inner  focus change: ${value}');
          },
        ),
      ),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key? key, required this.title}) : super(key: key);

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      // This call to setState tells the Flutter framework that something has
      // changed in this State, which causes it to rerun the build method below
      // so that the display can reflect the updated values. If we changed
      // _counter without calling setState(), then the build method would not be
      // called again, and so nothing would appear to happen.
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: Center(
        // Center is a layout widget. It takes a single child and positions it
        // in the middle of the parent.
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}

``` 

</details>

**Comment by TahaTesser** [comment] 2021-09-03 10:38
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by TahaTesser** 2021-09-03 10:38 UTC
