### ISSUE TITLE
Text Within a TextField Bounces When Typing

### ISSUE THREAD

**Issue by scottdewald** [flutter/flutter#34421] opened 2019-06-13 18:01 UTC
## Steps to Reproduce

On iOS, when the user increases the operating system's font size through the accessibility settings, the text within a `TextField` bounces/wobbles while the user is typing. The bouncing only happens when the `maxLines` field is set to some value other than `1` (`2` or `null` cause the issue). Below is a sample app which reproduces the issue. First on iOS go to Settings -> General -> Accessibility -> Larger Text, and change the text to a larger value than the nominal. Then run the application below and watch the text wobble.

```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Text Field Test',
      home: MainScreen(),
    );
  }
}
class MainScreen extends StatefulWidget {
  @override
  _MainScreenState createState() => _MainScreenState();
}

class _MainScreenState extends State<MainScreen> {
  final _textController = TextEditingController();

  @override
  void dispose() {
    _textController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("TextField Test"),
      ),
      body: Center(
        child: Padding(
          padding: const EdgeInsets.all(16.0),
          child: TextField(
            controller: _textController,
            maxLines: null,
          ),
        ),
      ),
    );
  }
}
```

## Flutter Doctor

```
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.5 18F203, locale en-US)
    • Flutter version 1.5.4-hotfix.2 at /Users/scottdewald/Tools/flutter
    • Framework revision 7a4c33425d (6 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/scottdewald/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 36.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 36.1.4
    • Dart plugin version 191.7830

[✓] IntelliJ IDEA Community Edition (version 2019.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 35.3.3
    • Dart plugin version 191.7141.49

[✓] VS Code (version 1.35.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.1.0

[✓] Connected device (1 available)
    • iPhone Xs • 291E02F8-C63C-4CA4-87BF-9E05C801C54E • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)

• No issues found!
```

**Comment by scottdewald** [comment] 2019-06-13 18:05
Here is what the wobbling text looks like

![ezgif-5-7580257efc9c](https://user-images.githubusercontent.com/1852625/59456371-cc82f700-8ddb-11e9-9748-d90595a5a709.gif)

**Comment by jonahwilliams** [comment] 2019-06-14 03:55
@justinmc I think you've looked at similar issues?

**Comment by justinmc** [comment] 2019-06-14 14:05
Yep like this one: https://github.com/flutter/flutter/issues/32158

@scottdewald Can you try this on the [master channel](https://github.com/flutter/flutter/wiki/Flutter-build-release-channels)?  I couldn't reproduce this on a physical iPhone 7 or on an iPhoneX simulator.

**Comment by scottdewald** [comment] 2019-06-14 15:26
@justinmc There was no wobble when I switched to the master channel on the iPhoneX simulator. Do you have any estimated timeline for when this fix will make it into stable or can you suggest any workarounds given the current stable build?

**Comment by justinmc** [comment] 2019-06-14 15:54
I would recommend that you switch to the dev or beta channels and see if they have the fix, and use one of them if so.  I know that's not possible for everyone using Flutter, but those pre-stable channels are more reliable than you might think.

I haven't checked exactly which version fixed this bug, but it could definitely be a few months before the fix makes it into stable.

I'll go ahead and close this, but feel free to comment if anything else comes up.  And thank you for writing such a clear issue!

**Closed by justinmc** 2019-06-14 15:54 UTC
Labels: a: text input, f: material design

**Comment by guopeng1994** [comment] 2019-07-08 09:40
yes! stable version of v1.5.4-hotfix.2 has this problem.

**Comment by justinmc** [comment] 2019-07-08 15:49
v1.7.4 and above should definitely have the fix, maybe earlier.  You'll have to switch channels to get it.  See https://github.com/flutter/flutter/wiki/Flutter-build-release-channels

**Comment by Alqueraf** [comment] 2019-12-11 18:47
I'm currently on `v1.9.1+hotfix.6` and experiencing the same issue. 
The cause is `maxLines: true`

**Comment by justinmc** [comment] 2019-12-16 20:54
@Alqueraf I couldn't reproduce this on master just now using the OP's example app code and the iPhone 11 simulator.  Can you reproduce it on master?  If so can you post some details about how you reproduce it?
