### ISSUE TITLE
Cupertino NavigationBar animation

### ISSUE THREAD

**Issue by praven07** [flutter/flutter#42759] opened 2019-10-15 14:59 UTC
## Steps to Reproduce

When I updated flutter to version 1.9.1+hotfix.4. The title in the navigation bar seems to have a weird animation. You can see that in the screenshot.

1. Use flutter version v1.9.1+hotfix.4
2. I've attached some screenshots of the code

**Target Platform:** iOS
**Target OS version/browser:** iOS13
**Devices:** iPhone6s

## Screenshots

<img width="646" alt="Screen Shot 2019-10-15 at 9 52 40 AM" src="https://user-images.githubusercontent.com/2223191/66842996-c63f8b80-ef31-11e9-950e-011cb976fcc7.png">

![screenshot](https://user-images.githubusercontent.com/2223191/66843192-0dc61780-ef32-11e9-9d17-a4ce334609d5.gif)

**Comment by BondarenkoStas** [comment] 2019-10-16 08:49
@praven07 Please do not include screenshots of code. This makes it extremely tedious to reproduce the issue, as we would have to manually transcribe your example.
Please paste the text version of your example here. Also provide your flutter doctor -v output.
Does it behave in the same way on emulator? Did you try it with android, or any not iOS13 device/emulator?

**Comment by praven07** [comment] 2019-11-25 22:40
@BondarenkoStas Hi, is there any update on the fix?

**Comment by dim971** [comment] 2019-12-05 10:50
I'm having the same weird animation with version `1.9.1+hotfix.6`

**Comment by justinmc** [comment] 2019-12-16 21:24
@GaryQian I think this could be related to the iOS 13 font weirdness issue, what do you think? https://github.com/flutter/flutter/issues/43998

I tried this on iOS 13 and 12 simulators using [praven07's code above](https://github.com/flutter/flutter/issues/42759#issuecomment-542724129) and it only happened on iOS 13.

**Comment by praven07** [comment] 2019-12-16 21:55
@justinmc If you see the back arrow it changes the size. So if it was affected by the font in iOS then the back arrow should work fine.

**Comment by dennis-tra** [comment] 2020-01-10 12:44
I can also confirm this issue:
iPhone X + iOS 13.3 + Flutter 1.13.7-pre.24

**Comment by bangfalse** [comment] 2020-02-07 20:50
I have this problem occurring for both my title and the back chevron, but only it only occurs when the system font size setting (textScaleFactor) is set to a non-default (1.0) size. I can reproduce this on 1.14.6, with both iOS 13 and iOS 12 simulators, and iOS 13 devices. It basically seems like the logic to fix the textScaleFactor at 1.0 isn't be applied during the animation, but I haven't dug into the nav bar code enough to figure out how that would be.

Setting a breakpoint during _BackChevron's build() method shows 1.0 sometimes and my system setting other times. The most reliable time to see the system setting is immediate after pressing the back chevron.

**Comment by bjacobgordon** [comment] 2020-02-25 21:48
I was having the exact same problem just this morning until I stumbled upon a helpful paragraph in the documentation for the CupertinoNavigationBar class:

> When used in a CupertinoPageScaffold, CupertinoPageScaffold.navigationBar has its text scale factor set to 1.0 and does not respond to text scale factor changes from the operating system, to match the native iOS behavior. To override this behavior, wrap each of the navigationBar's components inside a MediaQuery with the desired MediaQueryData.textScaleFactor value. The text scale factor value from the operating system can be retrieved in many ways, such as querying MediaQuery.textScaleFactorOf against CupertinoApp's BuildContext.

Applying this to your code, you'll have to explicitly pass in an instance of a `CupertinoNavigationBarBackButton` into the `CupertinoNavigationBar.leading` argument of each nav bar. From there, wrap the widgets passed into the `CupertinoNavigationBar.leading` and `CupertinoNavigationBar.middle` fields in a `MediaQuery` instance and pass `MediaQueryData(textScaleFactor: MediaQuery.textScaleFactorOf(context))` into the `MediaQuery .data` argument.

In the grand scheme of things, it would seem a lot more intuitive for any Navigation Bar to use the context by default for details like this.

**Comment by praven07** [comment] 2020-02-26 00:01
Setting the `textScaleFactor` worked for me!

**Comment by xster** [comment] 2020-04-07 21:29
https://github.com/flutter/flutter/issues/42759#issuecomment-591087271 is the right answer. I don't necessarily agree with the design choices but since the cupertino widgets model after UIKit and that's what iOS does, I'm going to close this. Any API ergonomics suggestions while maintaining the existing UI behavior welcome though.

**Closed by xster** 2020-04-07 21:29 UTC
Labels: f: cupertino, framework, platform-ios, severe: regression
