### ISSUE TITLE
%5Btool_crash%5D HttpException

### ISSUE THREAD

**Issue by MuhammadRauf07** [flutter/flutter#153484] opened 2024-08-15 05:04 UTC
%23%23 Command%0A%60%60%60sh%0Aflutter run -d chrome --web-renderer html%0A%60%60%60%0A%0A%23%23 Steps to Reproduce%0A1. ...%0A2. ...%0A3. ...%0A%0A%23%23 Logs%0AHttpException%0A%60%60%60console%0A%0A%60%60%60%0A%60%60%60console%0A%1B%5B32m%5B%E2%9C%93%5D%1B%5B39m Flutter %28Channel stable%2C 3.24.0%2C on Microsoft Windows %5BVersion 10.0.19045.4651%5D%2C locale en-US%2

**Comment by danagbemava-nc** [comment] 2024-08-15 07:51
Closing this as a duplicate of https://github.com/flutter/flutter/issues/73743

**Closed by danagbemava-nc** 2024-08-15 07:51 UTC
Labels: in triage
