### ISSUE TITLE
Typo on webview plugin source causing crash

### ISSUE THREAD

**Issue by ttznn** [flutter/flutter#82857] opened 2021-05-18 21:36 UTC
## Steps to Reproduce

1. Clean install flutter and android studio
2. Start new flutter project
3. Add web view plugin according to instructions `flutter pub add webview_flutter`

**Expected results:** 

Expected it to compile and run.

**Actual results:** 

`C:\flutter\.pub-cache\hosted\pub.dartlang.org\webview_flutter-2.0.6\android\src\main\java\io\flutter\plugins\webviewflutter\Input
AwareWebView.java:31: error: cannot find symbol
  private ThreadedInputConnectionProxyAdapterView proxyAdapterView;
          ^
  symbol:   class ThreadedInputConnectionProxyAdapterView
  location: class InputAwareWebView`

**Cause**

Upon inspection i found out that the file `ThreadedInputConnectionProxyAdapterView` is missing a letter in the extension, its `.jav` instead of `.java`, correcting the extension solves the issue.

![image](https://user-images.githubusercontent.com/3512737/118726599-ef0fbd00-b807-11eb-9435-3de6c8ef1a33.png)

<details>
  <summary>Logs</summary>
C:\flutter\.pub-cache\hosted\pub.dartlang.org\webview_flutter-2.0.6\android\src\main\java\io\flutter\plugins\webviewflutter\Input
AwareWebView.java:31: error: cannot find symbol
  private ThreadedInputConnectionProxyAdapterView proxyAdapterView;
          ^
  symbol:   class ThreadedInputConnectionProxyAdapterView
  location: class InputAwareWebView
C:\flutter\.pub-cache\hosted\pub.dartlang.org\webview_flutter-2.0.6\android\src\main\java\io\flutter\plugins\webviewflutter\Input
AwareWebView.java:112: error: cannot find symbol
        new ThreadedInputConnectionProxyAdapterView(
            ^
  symbol:   class ThreadedInputConnectionProxyAdapterView
  location: class InputAwareWebView
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
2 errors

</details>

**Comment by stuartmorgan** [comment] 2021-05-19 00:29
Duplicate of https://github.com/flutter/flutter/issues/82803

**Closed by stuartmorgan** 2021-05-19 00:29 UTC
