### ISSUE TITLE
Not getting unique device id on play-store or release app from device info : Flutter

### ISSUE THREAD

**Issue by krish-bhanushali** [flutter/flutter#81821] opened 2021-05-04 11:07 UTC
This is a strange thing or I am missing something here. The scenario is I am using device id from device-info plugin as an unique key at remote database.

Before Uploading to Playstore: I used to get same device id on my device whether I was building debug apk or release-apk which I distributed to 50 users for testing.

After Uploading to Playstore: My device id got changed and my server was taking it as a different user. Same Happened when I ran it into release build. But It stays the old one when I build it in release mode.

plugin and version : device_info: ^1.0.0.

Same thing happened with another app but this time with same key but different flutter version : AndroidId got changed after I updated my app.

**Comment by TahaTesser** [comment] 2021-05-04 14:23
Hi @krish-bhanushali 
This is by design, please check out https://github.com/flutter/flutter/issues/64063#issuecomment-678987167
Closing as duplicate of https://github.com/flutter/flutter/issues/64063

**Closed by TahaTesser** 2021-05-04 14:23 UTC
Labels: in triage
