### ISSUE TITLE
Phone auth feature for firebase_auth

### ISSUE THREAD

**Issue by MichaelSowah** [flutter/flutter#11527] opened 2017-08-05 13:11 UTC
Phone auth support would be great inclusion, lately its one of the quickest sign process in mobile app development
 T**ext below picked from this page** https://firebase.google.com/products/auth/ l**inked in the plugin's** page
Firebase Authentication aims to make building secure authentication system easy, while improving the sign-in and onboarding experience for end users. It provides an end-to-end identity solution, supporting **Email/password accounts, phone auth, Google, Twitter, Facebook, GitHub login** and more.

**Comment by Brahmasmi** [comment] 2017-10-07 13:07
@eseidelGoogle This seems to be a dupe of #10404 . Perhaps, we could close this.

**Comment by mit-mit** [comment] 2017-11-06 10:09
Closing as a duplicate

**Closed by mit-mit** 2017-11-06 10:09 UTC
Labels: plugin: firebase

**Comment by kroikie** [comment] 2019-10-13 19:26
@MichaelSowah

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/976. Any further collaboration will be done there.
