### ISSUE TITLE
video_player minimum Android version support?

### ISSUE THREAD

**Issue by JesseRMeyer** [flutter/flutter#25434] opened 2018-12-16 16:55 UTC
After attempting to run the video_player example code on my Moto E4, the debug console outputs a long series of errors, most of which stem from the very first line:

````
D8: Invoke-customs are only supported starting with Android O (--min-api 26)
````

Moto E4 only supports officially up to Android 7.x. Does the error above imply all Android phones < O cannot run the video_player plugin? If it can, how do I skirt around the issue above?

```
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':app:transformClassesWithDexBuilderForDebug'.
> com.android.build.api.transform.TransformException: com.android.builder.dexing.DexArchiveBuilderException: com.android.builder.dexing.DexArchiveBuilderException:`
```
flutter doctor -v
```
[√] Flutter (Channel stable, v1.0.0, on Microsoft Windows [Version 6.1.7601], locale en-US)
    • Flutter version 1.0.0 at C:\Mobile App\flutter
    • Framework revision 5391447fae (2 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at C:\Users\j\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[√] Android Studio (version 3.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 31.2.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[√] VS Code (version 1.30.0)
    • VS Code at C:\Users\j\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 2.21.1

[√] VS Code, 64-bit edition (version 1.23.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 2.21.1

[√] Connected device (1 available)
    • Moto E 4 • ZY2245BRZN • android-arm • Android 7.1.1 (API 25)

• No issues found!
```

**Comment by zoechi** [comment] 2018-12-17 08:07
Please add the output of `flutter doctor -v`.

You could try https://github.com/flutter/flutter/issues/24565#issuecomment-443356389

**Comment by zoechi** [comment] 2018-12-17 08:07
Looks similar to #25424

**Comment by JesseRMeyer** [comment] 2018-12-17 13:18
> 
> 
> Please add the output of `flutter doctor -v`.
> 
> You could try [#24565 (comment)](https://github.com/flutter/flutter/issues/24565#issuecomment-443356389)

That resolved the build errors, but I don't know why, so I'm hesitant to consider this resolved.

**Comment by zoechi** [comment] 2018-12-17 13:37
@JesseRMeyer thanks for the feedback. 
We can leave it open until a plugin specialist had a closer look.

**Comment by jamiegau** [comment] 2018-12-18 00:21
On this topic, I have been testing out video_player on numerous devices.  One device, a very old device. (4.4 from memory) And it does appear to work ok, especially with mp4 a the specific specs for the Android platform you using.
But it still comes down to  showstopper bug #24565    Unless this issue in that after a certain number of plays (And it is different for different hardware/Android versions)  the video_player will stop working, either refusing to start without error (Hanging in the video_player lib), or in some cases, causing a form of memory error when initialising the playback of the file.

As flutter-V1 just came out, I can understand that there has not been much work on this. (Core dev very busy).  But I wait patiently.  I have a lot of ideas for Apps once this is rectified.  But until video playback under flutter is reliable (more than running a handful of MP4s before kicking it out of memory)  It is pretty useless.

**Comment by kroikie** [comment] 2019-10-13 18:37
@JesseRMeyer

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/540. Any further collaboration will be done there.

**Comment by iapicca** [comment] 2019-10-22 14:06
I don't see any connection with FlutterFire,
I'm closing https://github.com/FirebaseExtended/flutterfire/issues/540 and reopening this issue.

Hi @JesseRMeyer
If you are still experiencing this issue 
with the latest version of Flutter
can you please provide your updated  `flutter doctor -v`
and your and your `flutter run --verbose`/`flutter build --verbose` ?
Also, to better address the issue, would be helpful
if you could post a self contained app on github
or the steps to reproduce it.
Thank you

**Comment by JesseRMeyer** [comment] 2019-10-22 20:11
Hi @iapicca,

It's been nearly 10 months since I looked at this and am no longer investigating this problem.  It may still exist for the same reasons that I posted it, but I don't know.

I have reason to return to this in the future but have made no definite plans.

**Comment by jamiegau** [comment] 2019-10-23 02:13
I will likely be attempting to use this plugin for updating my small app in the near future and doing considerable reliability testing.  I'll flag a new BUG if I see one at that time.  Its been a long time and flutter has changed a lot since this issue first popped up.

**Comment by iapicca** [comment] 2019-11-06 14:43
Hi @JesseRMeyer 
given your last message I feel safe to close this issue, for now
if the situation changes please write in the comments
and I will reopen it. 
Thank you

**Closed by iapicca** 2019-11-06 14:43 UTC
Labels: p: first party, p: video_player, plugin, severe: crash
