### ISSUE TITLE
image_picker package : Issue getting GPS info from Exif data on Android device

### ISSUE THREAD

**Issue by Vavinci** [flutter/flutter#134378] opened 2023-09-10 13:08 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing package issues](https://github.com/flutter/flutter/issues?q=is%3Aopen+is%3Aissue+label%3Apackage)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### What package does this bug report belong to?

image_picker

### What target platforms are you seeing this bug on?

Android

### Have you already upgraded your packages?

Yes

### Dependency versions

<details><summary>pubspec.lock</summary>

```lock
```

</details>

### Steps to reproduce

I am using the image_picker package to pick a file from the image : gallery (source) and read the Exif data. But when i check the GPS Info the latitude and longitude are set to [0/0, 0/0, 0/0]. I have seen a similar issue reported in 2022 #99817 but that was closed and #132827 reports of a missing Exif Tags. 

The image has the GPS data.

This issue is only on Android as it works as expected on IOS.

image_picker package version : '1.0.4'.

### Expected results

flutter: GPS GPSLatitudeRef: N
flutter: GPS GPSLatitude: [37, 39, 1324/25]
flutter: GPS GPSLongitudeRef: W
flutter: GPS GPSLongitude: [61, 22, 241/100]
flutter: GPS GPSAltitudeRef: 0
flutter: GPS GPSAltitude: 18859/100
flutter: GPS GPSImgDirectionRef: M
flutter: GPS GPSImgDirection: 340

### Actual results

I/flutter ( 6114): GPS GPSLatitudeRef: 
I/flutter ( 6114): GPS GPSLatitude: [0/0, 0/0, 0/0]
I/flutter ( 6114): GPS GPSLongitudeRef: 
I/flutter ( 6114): GPS GPSLongitude: [0/0, 0/0, 0/0]
I/flutter ( 6114): GPS GPSAltitudeRef: 0
I/flutter ( 6114): GPS GPSAltitude: 0/0
I/flutter ( 6114): GPS GPSTimeStamp: [0/0, 0/0, 0/0]
I/flutter ( 6114): GPS GPSImgDirectionRef: 
I/flutter ( 6114): GPS GPSImgDirection: 0/0
I/flutter ( 6114): GPS GPSDate: 

### Code sample

<details><summary>Code sample</summary>

```dart
void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter EXIF Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const ExifDemo(),
    );
  }
}

XFile? _image;

class ExifDemo extends StatefulWidget {
  const ExifDemo({Key? key}) : super(key: key);

  @override
  _ExifDemoState createState() => _ExifDemoState();
}

class _ExifDemoState extends State<ExifDemo> {
  Future<void> getImage({required bool isGallery}) async {
    ImagePicker picker = ImagePicker();
    XFile? pickedFile;

    try {
      pickedFile = isGallery
          ? await picker.pickImage(source: ImageSource.gallery)
          : await picker.pickImage(source: ImageSource.camera);
    } on PlatformException catch (error) {
      switch (error.code.toLowerCase()) {
        case 'photo_access_denied':
          print(error.code);
          break;
        case 'camera_access_denied':
          print(error.code);
          break;
        default:
          print(error.code);
          break;
      }
    } catch (error) {
      print(error);
    }

    if (pickedFile != null) {
      setState(() {
        _image = pickedFile;
      });
      readExifData();
    }
  }

  readExifData() async {
    if (_image != null) {
      final fileBytes = File(_image!.path).readAsBytesSync();
      final data = await readExifFromBytes(fileBytes);

      if (data.isEmpty) {
        print("No EXIF information found");
        return;
      }

      print('Path : ${_image!.path}');
      for (final entry in data.entries) {
        print("${entry.key}: ${entry.value}");
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Center(
      child: SingleChildScrollView(
        child: Padding(
          padding: const EdgeInsets.only(
            left: 10.0,
            top: 10.0,
            right: 10.0,
          ),
          child: Column(
            mainAxisAlignment: MainAxisAlignment.start,
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: [
              Visibility(
                  visible: _image != null,
                  child: ElevatedButton(
                    onPressed: () {
                      setState(() {
                        _image = null;
                      });
                    },
                    child: const Text('CLEAR'),
                  )),
              if (_image != null)
                Card(
                  shape: RoundedRectangleBorder(
                    borderRadius: BorderRadius.circular(0.0),
                  ),
                  elevation: 5,
                  margin: const EdgeInsets.all(10),
                  child: Stack(children: [
                    Image.file(
                      File(_image!.path),
                      fit: BoxFit.fill,
                    ),
                  ]),
                ),
              Visibility(
                visible: _image == null,
                child: Row(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: [
                    RawMaterialButton(
                      fillColor: Theme.of(context).primaryColor,
                      elevation: 8,
                      onPressed: () {
                        getImage(isGallery: false);
                      },
                      padding: const EdgeInsets.all(10),
                      shape: const CircleBorder(),
                      child: const Icon(
                        Icons.camera,
                        color: Colors.white,
                        size: 25,
                      ),
                    ),
                    RawMaterialButton(
                      fillColor: Theme.of(context).primaryColor,
                      elevation: 8,
                      onPressed: () {
                        getImage(isGallery: true);
                      },
                      padding: const EdgeInsets.all(10),
                      shape: const CircleBorder(),
                      child: const Icon(
                        Icons.photo_library_rounded,
                        color: Colors.white,
                        size: 25,
                      ),
                    ),
                  ],
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Videos

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
I/flutter (16418): Path : /data/user/0/exif_demo/cache/c5d20b6a-29fa-4b6f-9e7f-c099a4f03366/1000014685.jpg
I/flutter (16418): Image ImageWidth: 3072
I/flutter (16418): Image ImageLength: 4080
I/flutter (16418): Image Make: Google
I/flutter (16418): Image Model: Pixel 7
I/flutter (16418): Image Orientation: Horizontal (normal)
I/flutter (16418): Image XResolution: 72
I/flutter (16418): Image YResolution: 72
I/flutter (16418): Image ResolutionUnit: Pixels/Inch
I/flutter (16418): Image Software: HDR+ 1.0.540104767zd
I/flutter (16418): Image DateTime: 2023:09:05 14:39:22
I/flutter (16418): Image YCbCrPositioning: Centered
I/flutter (16418): Image ExifOffset: 242
I/flutter (16418): GPS GPSLatitudeRef: 
I/flutter (16418): GPS GPSLatitude: [0/0, 0/0, 0/0]
I/flutter (16418): GPS GPSLongitudeRef: 
I/flutter (16418): GPS GPSLongitude: [0/0, 0/0, 0/0]
I/flutter (16418): GPS GPSAltitudeRef: 0
I/flutter (16418): GPS GPSAltitude: 0/0
I/flutter (16418): GPS GPSTimeStamp: [0/0, 0/0, 0/0]
I/flutter (16418): GPS GPSImgDirectionRef: 
I/flutter (16418): GPS GPSImgDirection: 0/0
I/flutter (16418): GPS GPSDate: 
I/flutter (16418): Image GPSInfo: 976
I/flutter (16418): Thumbnail ImageWidth: 241
I/flutter (16418): Thumbnail ImageLength: 321
I/flutter (16418): Thumbnail Compression: JPEG (old-style)
I/flutter (16418): Thumbnail Orientation: Horizontal (normal)
I/flutter (16418): Thumbnail XResolution: 72
I/flutter (16418): Thumbnail YResolution: 72
I/flutter (16418): Thumbnail ResolutionUnit: Pixels/Inch
I/flutter (16418): Thumbnail JPEGInterchangeFormat: 1331
I/flutter (16418): Thumbnail JPEGInterchangeFormatLength: 12955
I/flutter (16418): EXIF ExposureTime: 15393/500000
I/flutter (16418): EXIF FNumber: 37/20
I/flutter (16418): EXIF ExposureProgram: Program Normal
I/flutter (16418): EXIF ISOSpeedRatings: 47
I/flutter (16418): EXIF ExifVersion: 0232
I/flutter (16418): EXIF DateTimeOriginal: 2023:09:05 14:39:22
I/flutter (16418): EXIF DateTimeDigitized: 2023:09:05 14:39:22
I/flutter (16418): EXIF OffsetTime: -04:00
I/flutter (16418): EXIF OffsetTimeOriginal: -04:00
I/flutter (16418): EXIF OffsetTimeDigitized: -04:00
I/flutter (16418): EXIF ComponentsConfiguration: YCbCr
I/flutter (16418): EXIF ShutterSpeedValue: 251/50
I/flutter (16418): EXIF ApertureValue: 89/50
I/flutter (16418): EXIF BrightnessValue: 289/100
I/flutter (16418): EXIF ExposureBiasValue: 0
I/flutter (16418): EXIF MaxApertureValue: 89/50
I/flutter (16418): EXIF SubjectDistance: 723/500
I/flutter (16418): EXIF MeteringMode: CenterWeightedAverage
I/flutter (16418): EXIF Flash: Flash did not fire, compulsory flash mode
I/flutter (16418): EXIF FocalLength: 681/100
I/flutter (16418): EXIF SubSecTime: 480
I/flutter (16418): EXIF SubSecTimeOriginal: 480
I/flutter (16418): EXIF SubSecTimeDigitized: 480
I/flutter (16418): EXIF FlashPixVersion: 0100
I/flutter (16418): EXIF ColorSpace: sRGB
I/flutter (16418): EXIF ExifImageWidth: 3072
I/flutter (16418): EXIF ExifImageLength: 4080
I/flutter (16418): Interoperability InteroperabilityIndex: R98
I/flutter (16418): Interoperability InteroperabilityVersion: [48, 49, 48, 48]
I/flutter (16418): EXIF InteroperabilityOffset: 946
I/flutter (16418): EXIF SensingMethod: One-chip color area
I/flutter (16418): EXIF SceneType: Directly Photographed
I/flutter (16418): EXIF CustomRendered: Custom
I/flutter (16418): EXIF ExposureMode: Auto Exposure
I/flutter (16418): EXIF WhiteBalance: Auto
I/flutter (16418): EXIF DigitalZoomRatio: 159/100
I/flutter (16418): EXIF FocalLengthIn35mmFilm: 24
I/flutter (16418): EXIF SceneCaptureType: Standard
I/flutter (16418): EXIF Contrast: Normal
I/flutter (16418): EXIF Saturation: Normal
I/flutter (16418): EXIF Sharpness: Normal
I/flutter (16418): EXIF SubjectDistanceRange: 2
I/flutter (16418): EXIF LensMake: Google
I/flutter (16418): EXIF LensModel: Pixel 7 back camera 6.81mm f/1.85
I/flutter (16418): EXIF Tag 0xA460: 3
I/flutter (16418): JPEGThumbnail:
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.13.3, on macOS 13.3.1 22E261 darwin-arm64, locale en-US)
    • Flutter version 3.13.3 on channel stable at /Users/davinci/dev_lib/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2524052335 (4 days ago), 2023-09-06 14:32:31 -0700
    • Engine revision b8d35810e9
    • Dart version 3.1.1
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/xyz/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.81.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • Pixel 7 (mobile) • 2A201FDH2001EX • android-arm64  • Android 13 (API 33)
    • macOS (desktop)  • macos          • darwin-arm64   • macOS 13.3.1 22E261 darwin-arm64
    • Chrome (web)     • chrome         • web-javascript • Google Chrome 116.0.5845.179

[✓] Network resources
    • All expected network resources are available.

• No issues found!


```

</details>

**Comment by dam-ease** [comment] 2023-09-11 10:51
Hi @Vavinci. Thanks for filing this. I am able to reproduce this on the latest versions of Flutter. This seems similar/related to https://github.com/flutter/flutter/issues/132827 but I see it occurs both with resized and non-resized images.

<details><summary>Details</summary>
<p>

```dart
import 'dart:io';

import 'package:exif/exif.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:image_picker/image_picker.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter EXIF Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const ExifDemo(),
    );
  }
}

XFile? _image;

class ExifDemo extends StatefulWidget {
  const ExifDemo({Key? key}) : super(key: key);

  @override
  _ExifDemoState createState() => _ExifDemoState();
}

class _ExifDemoState extends State<ExifDemo> {
  Future<void> getImage({required bool isGallery}) async {
    ImagePicker picker = ImagePicker();
    XFile? pickedFile;

    try {
      pickedFile = isGallery
          ? await picker.pickImage(source: ImageSource.gallery)
          : await picker.pickImage(source: ImageSource.camera);
    } on PlatformException catch (error) {
      switch (error.code.toLowerCase()) {
        case 'photo_access_denied':
          print(error.code);
          break;
        case 'camera_access_denied':
          print(error.code);
          break;
        default:
          print(error.code);
          break;
      }
    } catch (error) {
      print(error);
    }

    if (pickedFile != null) {
      setState(() {
        _image = pickedFile;
      });
      readExifData();
    }
  }

  readExifData() async {
    if (_image != null) {
      final fileBytes = File(_image!.path).readAsBytesSync();
      final data = await readExifFromBytes(fileBytes);

      if (data.isEmpty) {
        print("No EXIF information found");
        return;
      }

      print('Path : ${_image!.path}');
      for (final entry in data.entries) {
        print("${entry.key}: ${entry.value}");
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Center(
      child: SingleChildScrollView(
        child: Padding(
          padding: const EdgeInsets.only(
            left: 10.0,
            top: 10.0,
            right: 10.0,
          ),
          child: Column(
            mainAxisAlignment: MainAxisAlignment.start,
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: [
              Visibility(
                  visible: _image != null,
                  child: ElevatedButton(
                    onPressed: () {
                      setState(() {
                        _image = null;
                      });
                    },
                    child: const Text('CLEAR'),
                  )),
              if (_image != null)
                Card(
                  shape: RoundedRectangleBorder(
                    borderRadius: BorderRadius.circular(0.0),
                  ),
                  elevation: 5,
                  margin: const EdgeInsets.all(10),
                  child: Stack(children: [
                    Image.file(
                      File(_image!.path),
                      fit: BoxFit.fill,
                    ),
                  ]),
                ),
              Visibility(
                visible: _image == null,
                child: Row(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: [
                    RawMaterialButton(
                      fillColor: Theme.of(context).primaryColor,
                      elevation: 8,
                      onPressed: () {
                        getImage(isGallery: false);
                      },
                      padding: const EdgeInsets.all(10),
                      shape: const CircleBorder(),
                      child: const Icon(
                        Icons.camera,
                        color: Colors.white,
                        size: 25,
                      ),
                    ),
                    RawMaterialButton(
                      fillColor: Theme.of(context).primaryColor,
                      elevation: 8,
                      onPressed: () {
                        getImage(isGallery: true);
                      },
                      padding: const EdgeInsets.all(10),
                      shape: const CircleBorder(),
                      child: const Icon(
                        Icons.photo_library_rounded,
                        color: Colors.white,
                        size: 25,
                      ),
                    ),
                  ],
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}

``` 

</p>
</details> 

<details><summary>Image Used</summary>
<p>

https://user-images.githubusercontent.com/9675199/261601258-48beaae9-ae58-484f-a9f5-405c121dd9de.jpeg

</p>
</details> 

<details><summary>stable, master flutter doctor</summary>
<p>

```
[✓] Flutter (Channel stable, 3.13.3, on macOS 13.0 22A380 darwin-arm64, locale
    en-NG)
    • Flutter version 3.13.3 on channel stable at
      /Users/damilolaalimi/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2524052335 (4 days ago), 2023-09-06 14:32:31 -0700
    • Engine revision b8d35810e9
    • Dart version 3.1.1
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/damilolaalimi/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/damilolaalimi/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.81.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.0 22A380 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 116.0.5845.179

[✓] Network resources
    • All expected network resources are available.

• No issues found!
``` 
```
[!] Flutter (Channel master, 3.14.0-14.0.pre.211, on macOS 13.0 22A380 darwin-arm64, locale en-NG)
    • Flutter version 3.14.0-14.0.pre.211 on channel master at /Users/damilolaalimi/fvm/versions/master
    ! Warning: `flutter` on your path resolves to /Users/damilolaalimi/sdks/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/damilolaalimi/fvm/versions/master. Consider adding /Users/damilolaalimi/fvm/versions/master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/damilolaalimi/sdks/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/damilolaalimi/fvm/versions/master. Consider adding /Users/damilolaalimi/fvm/versions/master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 69f6e7d15d (3 hours ago), 2023-09-11 00:50:38 -0400
    • Engine revision 7e41b064eb
    • Dart version 3.2.0 (build 3.2.0-134.0.dev)
    • DevTools version 2.27.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/damilolaalimi/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/damilolaalimi/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.81.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.0 22A380 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 116.0.5845.179

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
``` 

</p>
</details>

**Comment by Vavinci** [comment] 2023-09-13 15:05
Hi @dam-ease. I was doing some research on my end and it seems like this bug with latitude / longitude was introduced in Android API 31 and has continued since. 

As a workaround, If I can get the path to the actual image I can use that to get the GPS info from the original exif data but not sure how to go about that.

**Comment by Vavinci** [comment] 2023-09-14 17:14
After much research on my end the issue seem to be happening with the new android photo picker. Apparently, the android photo picker redacts the gps information from the image exif data. Not sure why the Android team would modify exif data.  

According to the Image Picker documentation the 'Android Photo Picker' is optional but it doesn't seem to the the case with API 33 anymore. Workaround, I found was to hit the 3 dots on the photo picker and then browse which takes back to the old interface, but this is not a good experience for my clients.

**Comment by gmackall** [comment] 2023-09-19 19:58
> After much research on my end the issue seem to be happening with the new android photo picker. Apparently, the android photo picker redacts the gps information from the image exif data. Not sure why the Android team would modify exif data.

It does unfortunately seem as though this is intended: https://b.corp.google.com/issues/243294058.

> According to the Image Picker documentation the 'Android Photo Picker' is optional but it doesn't seem to the the case with API 33 anymore. Workaround, I found was to hit the 3 dots on the photo picker and then browse which takes back to the old interface, but this is not a good experience for my clients.

The Android Photo picker should still be optional. If you try running the example app with [this line](https://github.com/flutter/packages/blob/d08ebfd2b725e1df569c9065f7831d52f8588c47/packages/image_picker/image_picker_android/example/lib/main.dart#L31) commented (or set to false), do you not see the old behavior?

**Comment by Vavinci** [comment] 2023-09-20 03:25
> > After much research on my end the issue seem to be happening with the new android photo picker. Apparently, the android photo picker redacts the gps information from the image exif data. Not sure why the Android team would modify exif data.
> 
> It does unfortunately seem as though this is intended: https://b.corp.google.com/issues/243294058.
> 
> > According to the Image Picker documentation the 'Android Photo Picker' is optional but it doesn't seem to the the case with API 33 anymore. Workaround, I found was to hit the 3 dots on the photo picker and then browse which takes back to the old interface, but this is not a good experience for my clients.
> 
> The Android Photo picker should still be optional. If you try running the example app with [this line](https://github.com/flutter/packages/blob/d08ebfd2b725e1df569c9065f7831d52f8588c47/packages/image_picker/image_picker_android/example/lib/main.dart#L31) commented (or set to false), do you not see the old behavior?

Unfortunately @gmackall that's not the behavior I am seeing on pixel 7 device running android version 13. When I run on the emulator with API 33 it show the old behavior, but when I run on an actual pixel 7 device the Android photo picker is what is being displayed. 

In the code sample I provided I am simply calling the image_picker : 
**_await picker.pickImage(source: ImageSource.gallery)_**

I know in the image_picker_android library, the Android Photo picker is defaulted to false, but it seems like on an actual device (Pixel 7 - Android version 13) this setting is completely ignored.

Is there something you suggest I should try?

**Comment by gmackall** [comment] 2023-09-20 18:01
Interesting, I'll try testing on a device and report back!

**Comment by omnitrogen** [comment] 2023-10-05 16:08
Thanks @Vavinci for creating that issue. I am faced with the same problem.

I am using `imagePickerImplementation.useAndroidPhotoPicker = false;` in my code as well, but it does not seem to work for newer Android versions (including many vendors Android tweaked version, e.g. Samsung).

The "3 dots" workaround works but it is really not convenient for end users.

I am working on an app to share biodiversity observations, and the pic location is a __very__ important data.

**Comment by gmackall** [comment] 2023-10-09 16:35
Hi, sorry I've been traveling for a bit - I'll be able to test this on a device tomorrow and update with more info. Sorry again for the delay!

**Comment by gmackall** [comment] 2023-10-11 01:22
I was able to test this out today, and am able to recreate it working differently than the emulator (and as described by @Vavinci). Interestingly it doesn't seem to be completely ignoring the setting, as I only get the "three dots" that let me browse (and therefore get to the old behavior) when setting `useAndroidPhotoPicker` to `useAndroidPhotoPicker`.

Still looking in to why this is!

**Comment by prasadsunny1** [comment] 2023-10-17 19:45
The underlying photo picker library does not give location data even if the picture itself does have lat long 

https://stackoverflow.com/questions/73571692/new-android-13-photo-picker-exif-location-not-working

**Comment by ankhanguit** [comment] 2023-10-26 08:09
> The underlying photo picker library does not give location data even if the picture itself does have lat long
> 
> https://stackoverflow.com/questions/73571692/new-android-13-photo-picker-exif-location-not-working

Yes, that why we need set  "Android Photo Picker"  be optional. if you use "file_picker" you will able to get gps. but i like to use image_picker. i'm still waiting for updating

**Comment by Vavinci** [comment] 2023-11-04 18:42
@gmackall Any updates on this issue?

**Comment by sachinbpatil619** [comment] 2023-11-07 11:03
Any updates ?

**Comment by mkaticic** [comment] 2023-12-15 21:51
Hi, I am also very interested in this issue. Similar as @omnitrogen I am developing GEOTropa app. Main feature in my app is 'observation' entry. Observation record is used to store information about any taxon observed (fungi, plants or animals). Pictures related to the observation are very important and I use EXIF info to get observation location. 
I was very happy when I found this question because now I at least understand why this does not work anymore, but I vote that this behaviour should be optional! I agree that file_picker workaround is not desired solution for the apps that depend on location info.
I hope we will have some solution soon...

**Comment by Vavinci** [comment] 2024-01-30 07:35
Any updates regarding this issue. I have android users who are not happy about this. Trying to explain them the issue and suggesting them a work around is not cutting it.

Also for those effected by this there is an Android issue tracker regarding this issue. 
Here is the link: https://issuetracker.google.com/issues/243294058?pli=1

**Comment by ValentinVignal** [comment] 2024-04-09 09:59
@gmackall Reading through https://issuetracker.google.com/issues/243294058?pli=1 , does that mean there is no fix possible for it? We would need to first wait for the android team to change this behavior, but this is not what they seem to want.

Am I correct? Or is there still something that can be done on the flutter side?

**Comment by Vavinci** [comment] 2024-04-17 15:45
@ValentinVignal Looks like Android team just reopened this issue.

**Comment by gmackall** [comment] 2024-04-17 18:26
It looks like the photo picker is no longer optional, on newer versions of Android.
See the "GET_CONTENT takover" section of
https://android-developers.googleblog.com/2023/04/photo-picker-everywhere.html
And the linked blog, section "`ACTION_GET_CONTENT` behavior change"
https://medium.com/androiddevelopers/permissionless-is-the-future-of-storage-on-android-3fbceeb3d70a

This intent is what the `image_picker` android implementation used in its non-photo picker code path, which explains the inability to override to not use the new photo picker. 
https://github.com/flutter/packages/blob/0dd8de289ea735759a5e06753eba3db6420e865d/packages/image_picker/image_picker_android/android/src/main/java/io/flutter/plugins/imagepicker/ImagePickerDelegate.java#L452

So I'm going to close this issue, as unfortunately there isn't much the plugin can do here (the lack of GPS info in the photo picker is intended per https://b.corp.google.com/issues/243294058?pli=1, and the inability to override to non-photo picker is also intended per the links above).

**Closed by gmackall** 2024-04-17 18:26 UTC
Labels: platform-android, p: image_picker, package, has reproducible steps, P2, team-android, triaged-android, found in release: 3.13, :hourglass_flowing_sand:, found in release: 3.14
