### ISSUE TITLE
[in_app_purchase] PurchaseDetails.status is null on Android

### ISSUE THREAD

**Issue by talent-apps** [flutter/flutter#43632] opened 2019-10-28 15:34 UTC
When calling `queryPastPurchases` on Android, a list of `PurchaseDetails` is returned, but the `status` field is set to null which is inconsistent with the iOS implementation.

**On iOS:**
```
      pastPurchases =
          restoredTransactions.map((SKPaymentTransactionWrapper transaction) {
        assert(transaction.transactionState ==
            SKPaymentTransactionStateWrapper.restored);
        return PurchaseDetails.fromSKTransaction(transaction, receiptData)
          ..status = SKTransactionStatusConverter()
              .toPurchaseStatus(transaction.transactionState)
```

I.e. the status field is set explicitly according to the `transactionState`.

**On Android:**
```
    List<PurchaseDetails> pastPurchases =
        responses.expand((PurchasesResultWrapper response) {
      return response.purchasesList;
    }).map((PurchaseWrapper purchaseWrapper) {
      return PurchaseDetails.fromPurchase(purchaseWrapper);
    }).toList();
```

I.e. the status field is **NOT** set.

**Comment by ilyasKerbal** [comment] 2019-11-05 03:55
Same issue

**Comment by talent-apps** [comment] 2019-12-30 21:23
Any update on this?

**Comment by raulbro** [comment] 2020-04-06 03:41
Any update on this?

**Comment by Dimous** [comment] 2020-04-06 07:05
Consider trying out RevenueCat. I heard it's working like a charm.

**Comment by BeMacized** [comment] 2021-04-01 13:28
Closing this as I'm quite sure this is a duplicate of #38671.

**Closed by BeMacized** 2021-04-01 13:28 UTC
Labels: customer: crowd, p: first party, p: in_app_purchase, platform-android, plugin
