### ISSUE TITLE
Running Flutter doctor leads to error

### ISSUE THREAD

**Issue by sebastianbuechler** [flutter/flutter#67286] opened 2020-10-05 07:12 UTC
When running flutter doctor an error regarding the SDK version comes up. 

## Steps to Reproduce
1. Flutter doctor

## Logs

>flutter doctor
Checking Dart SDK version...
Building flutter tool...
Running pub upgrade...
The current Dart SDK version is 2.9.2.
Because flutter_tools depends on test >=1.16.0-nullsafety which requires SDK version >=2.10.0-0 <2.11.0, version solving failed.

**Comment by darshankawar** [comment] 2020-10-05 11:54
@sebastianbuechler 
What Flutter channel are you getting this error ? Did you upgrade recently ?
Thanks.

**Comment by sebastianbuechler** [comment] 2020-10-05 12:24
@darshankawar I'm on channel stable and v.1.20.4. I wanted to upgrade but the error does not allow it. I had to delete the SDK in order to upgrade to 1.22, but unfortunately, the new version is too buggy with so many packages that I downgraded again. Now flutter doctor runs again smoothly.

**Comment by darshankawar** [comment] 2020-10-06 05:52
@sebastianbuechler thanks for details.
Not sure what could be the cause of getting that error. Next time if you want to upgrade, you may try `flutter upgrade --force` and see if it works for you.
Also, given your last message, I am going ahead and closing this issue. If you encounter same issue, feel free to reopen this or comment and I'll reopen.
Thanks.

**Closed by darshankawar** 2020-10-06 05:52 UTC
Labels: in triage

**Comment by AnujPundir29** [comment] 2020-10-06 15:56
> When running flutter doctor an error regarding the SDK version comes up.
> 
> ## Steps to Reproduce
> 1. Flutter doctor
> 
> ## Logs
> > flutter doctor
> > Checking Dart SDK version...
> > Building flutter tool...
> > Running pub upgrade...
> > The current Dart SDK version is 2.9.2.
> > Because flutter_tools depends on test >=1.16.0-nullsafety which requires SDK version >=2.10.0-0 <2.11.0, version solving failed.

I am getting the same error and it always says initializing flutter... What to do please help

**Comment by sebastianbuechler** [comment] 2020-10-06 16:01
> > When running flutter doctor an error regarding the SDK version comes up.
> > ## Steps to Reproduce
> > 
> > 1. Flutter doctor
> > 
> > ## Logs
> > > flutter doctor
> > > Checking Dart SDK version...
> > > Building flutter tool...
> > > Running pub upgrade...
> > > The current Dart SDK version is 2.9.2.
> > > Because flutter_tools depends on test >=1.16.0-nullsafety which requires SDK version >=2.10.0-0 <2.11.0, version solving failed.
> 
> I am getting the same error and it always says initializing flutter... What to do please help

For me it worked to delete the flutter folder and reinstall it completely. However, I don't think that this has to be necessary. As @darshankawar mentioned you can try to force upgrade with `flutter upgrade --force` first.

**Comment by AnujPundir29** [comment] 2020-10-06 16:05
> > > When running flutter doctor an error regarding the SDK version comes up.
> > > ## Steps to Reproduce
> > > 
> > > 1. Flutter doctor
> > > 
> > > ## Logs
> > > > flutter doctor
> > > > Checking Dart SDK version...
> > > > Building flutter tool...
> > > > Running pub upgrade...
> > > > The current Dart SDK version is 2.9.2.
> > > > Because flutter_tools depends on test >=1.16.0-nullsafety which requires SDK version >=2.10.0-0 <2.11.0, version solving failed.
> > 
> > 
> > I am getting the same error and it always says initializing flutter... What to do please help
> 
> For me it worked to delete the flutter folder and reinstall it completely. However, I don't think that this has to be necessary. As @darshankawar mentioned you can try to force upgrade with `flutter upgrade --force` first.

I am not able to upgrade it forcibly also

**Comment by adarshhegde** [comment] 2020-10-07 04:38
I am facing exactly the same issue also.

**Comment by sebastianbuechler** [comment] 2020-10-07 06:29
As I said earlier, there is always the method of reinstalling flutter from scratch if you really need it to work again. 

On Windows, rename `C:\src\flutter` to `C:\src\flutter.old` so you have a backup. Then open a command line in `C:\src` and run git `clone https://github.com/flutter/flutter.git -b stable` and it will install the newest flutter on channel stable. To test the installation just run `flutter doctor` after installation. Hope this helps.

**Comment by svrohith9** [comment] 2021-02-27 19:52
Changed the flutter sdk repo from default branch to **beta** branch and, 
```
flutter channel beta
flutter upgrade
flutter config --enable-web
```

**Comment by sebastianbuechler** [comment] 2021-02-27 20:04
> Changed the flutter sdk repo from default branch to **beta** branch and, 
> ```
> flutter channel beta
> flutter upgrade
> flutter config --enable-web
> ```
> 

This issue here has nothing to do with the beta channel nor with web.

What is your point?
