### ISSUE TITLE
[image_picker] Unable to pick a WebP image on iOS

### ISSUE THREAD

**Issue by oandreyev** [flutter/flutter#88094] opened 2021-08-12 08:13 UTC
## Steps to Reproduce

1. Run plugin example application on iOS.
2. Try to pick a WebP image.

Nothing happens. The image is not loaded. Neither Flutter not Xcode provide useful output in the logs.
No exceptions. The future is not completed.

I would expect PlatformException if we cannot process this kind of images on iOS.

<details>
  <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.5.2 20G95 darwin-arm, locale en-UA)
    • Flutter version 2.2.3 at /Users/oandreyev/Tools/flutter
    • Framework revision f4abaa0735 (6 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/oandreyev/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] IntelliJ IDEA Community Edition (version 2021.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 59.0.4
    • Dart plugin version 212.4746.57

[✓] Connected device (2 available)
    • Oleg’s Dev iPhone (mobile) • 46424eb83323aec8a7172c9bbe20446bb493b4d2 • ios            • iOS 14.6
    • Chrome (web)               • chrome                                   • web-javascript • Google Chrome 92.0.4515.131

```

</details>

**Comment by matejvagic** [comment] 2021-10-12 09:54
I'm having the same issue. Is there some workaround?

**Comment by burcus** [comment] 2021-11-24 11:16
@TrGiLong Hi, did you solve this problem? It's still reproducable.

**Comment by TrGiLong** [comment] 2021-11-24 11:38
Hi, @burcus 

I have fixed it but the branch isn't been merged into main branch. I have to write some extra code to pass their requirements so it will last time. The PR is [here](https://github.com/flutter/plugins/pull/4448)

You can also use my branch for your project while waiting. As far as i know there aren't any important changes in package :D

**Comment by burcus** [comment] 2021-11-24 12:31
Thank you for feedback @TrGiLong. How long do you think it would take to merge with the main branch?

**Comment by TrGiLong** [comment] 2021-11-24 13:05
@burcus 
I can't say how long it will exactly take because it depends on the reviewer. I will try to fix the code today and request a new review for it 😅

**Comment by burcus** [comment] 2021-11-24 13:18
Hope this error will fix immediately. I think it's critical because there's no chance for catching the error. Waiting for review good luck.

**Closed** 2022-02-25 21:31 UTC
Labels: platform-ios, plugin, p: first party, p: image_picker, has reproducible steps, P4, found in release: 2.2, found in release: 2.5
