### ISSUE TITLE
[tool_crash] SessionNotCreatedException

### ISSUE THREAD

**Issue by nadyshalaby** [flutter/flutter#152441] opened 2024-07-27 18:44 UTC
## Command
```
flutter drive --driver=./test_driver/integration_test.dart --target=./integration_test/login_test.dart -d chrome
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
SessionNotCreatedException
```
#0      parseW3cResponse (package:webdriver/src/handler/w3c/utils.dart:81:9)
#1      W3cSessionHandler.parseCreateResponse (package:webdriver/src/handler/w3c/session.dart:19:21)
#2      InferSessionHandler.parseCreateResponse (package:webdriver/src/handler/infer_handler.dart:106:34)
#3      AsyncRequestClient.send (package:webdriver/src/common/request_client.dart:96:32)
<asynchronous suspension>
#4      createDriver (package:webdriver/async_core.dart:62:19)
<asynchronous suspension>
#5      WebDriverService.startTest (package:flutter_tools/src/drive/web_driver_service.dart:157:19)
<asynchronous suspension>
#6      DriveCommand.runCommand (package:flutter_tools/src/commands/drive.dart:324:30)
<asynchronous suspension>
#7      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1394:27)
<asynchronous suspension>
#8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#9      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#10     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:372:9)
<asynchronous suspension>
#11     AppContext.run.<anony

**Comment by danagbemava-nc** [comment] 2024-07-29 07:40
Closing this as a duplicate of https://github.com/flutter/flutter/issues/141010

**Closed by danagbemava-nc** 2024-07-29 07:40 UTC
Labels: in triage
