### ISSUE TITLE
[tool_crash] _TypeError: (#0      Session._refreshSessionData.parseContents (package:unified_analytics/src/session.dart:85:43))

### ISSUE THREAD

**Issue by Munna005** [flutter/flutter#145285] opened 2024-03-17 07:41 UTC
## Command
```
flutter doctor
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
_TypeError: (#0      Session._refreshSessionData.parseContents (package:unified_analytics/src/session.dart:85:43))
```
#0      Session._refreshSessionData.parseContents (package:unified_analytics/src/session.dart:85:43)
#1      Session._refreshSessionData (package:unified_analytics/src/session.dart:89:7)
#2      new Session (package:unified_analytics/src/session.dart:28:5)
#3      new AnalyticsImpl (package:unified_analytics/src/analytics.dart:326:23)
#4      new Analytics (package:unified_analytics/src/analytics.dart:67:12)
#5      runInContext.<anonymous closure> (package:flutter_tools/src/context_runner.dart:91:24)
#6      AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:104:42)
#7      _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:535:23)
#8      AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:92:20)
#9      AppContext.get (package:flutter_tools/src/base/context.dart:121:32)
#10     analytics (package:flutter_tools/src/globals.dart:93:36)
#11     _exit (package:flutter_tools/runner.dart:302:15)
#12     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:120:24)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#14     main (package:flutter_tools/executable.dart:90:3)
<asynchronous suspension>
```
```
[32m[✓][39m Flutter (Channel stable, 3.13.6, on macOS 14.3.1 23D60 darwin-arm64 (Rosetta), locale en-NG)
    [32m•[39m Flutter version 3.13.6 on channel stable at /Users/victor/Desktop/devs/flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision ead455963c (6 months ago), 2023-09-26 18:28:17 -0700
    [32m•[39m Engine revision a794cf2681
    [32m•[39m Dart version 3.1.3
    [32m•[39m DevTools version 2.25.0

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    [32m•[39m Android SDK at /Users/victor/Library/Android/sdk
    [32m•[39m Platform android-34, build-tools 33.0.0
    [32m•[39m Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    [32m•[39m All Android licenses accepted.

[33m[!][39m Xcode - develop for iOS and macOS (Xcode 15.2)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Build 15C500b
    [31m✗[39m CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your
        plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see https://guides.cocoapods.org/using/getting-started.html#installa

**Comment by huycozy** [comment] 2024-03-18 09:11
I guess you hit the recent issue https://github.com/flutter/flutter/issues/145201 which also is caused by casting type. But the stack trace above doesn't have a clear message, like `type 'Null' is not a subtype of type 'int' in type cast` (perhaps this is due to your current Flutter version is quite old)

Since https://github.com/flutter/flutter/issues/145201 is fixed on master channel, could you try switching to this channel and re-check?

**Comment by huycozy** [comment] 2024-03-19 10:45
Closing this in favor of https://github.com/flutter/flutter/issues/145201. If you still encounter the issue, please write a comment there.

**Closed by huycozy** 2024-03-19 10:45 UTC
Labels: waiting for customer response, in triage
