### ISSUE TITLE
[webview_flutter] PlatformException on firsttime install

### ISSUE THREAD

**Issue by thanhhuan1990** [flutter/flutter#39803] opened 2019-09-04 08:22 UTC
## Steps to Reproduce
1. Define WebView normally
2. Setup push notification by FCM
3. Uninstall app and reinstall again

## Logs

```
PlatformException(create_failed, can't create a view on a headless engine, null)
```

## flutter analyze
```
No issues found! (ran in 3.1s)
```

```
[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.14.6 18G87, locale en-US)
    • Flutter version 1.7.8+hotfix.4 at /Users/apple/Development/flutter
    • Framework revision 20e59316b8 (7 weeks ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/apple/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/apple/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • CocoaPods version 1.7.5

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 38.2.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 37.0.3
    • Dart plugin version 191.7830

[✓] Connected device (3 available)
    • Android SDK built for x86 • emulator-5554                            • android-x86 • Android 9 (API 28) (emulator)
    • com.apple.CoreSimulator.SimRuntime.iOS-12-4 (simulator)

• No issues found!

```

**Comment by abumoallim** [comment] 2019-11-03 07:08
Any solution to this ?

**Comment by sweeepty** [comment] 2020-01-16 11:21
I have the same issue. Does anyone has solution?

**Comment by ricnaaru** [comment] 2020-04-08 03:37
i think most of the time this error will happen if it has to render the NativeView while the phone is asking some permission, and this is particularly happen only on IOS

**Comment by ricnaaru** [comment] 2020-04-08 08:28
this happens when the app is requesting for any permission in ios, and the flutter NativeView try to render itself. so as long as the permission dialog hanging there, i think it's considered to be "headless".

i think, what you can do to fix this is basically wait until the permission request is finished, and then try to render / call the build NativeView (whatever it is, could be WebView or GoogleMap). For what i know, ios permission request will only prompt only when the service is called (start motion activity update / get current location from GPS / Notification received)

although this case is relatively hard to reproduce, and considered to be rare occasion (need to have ios permission request script [calling the GPS location / Notification received thus will prompt notification permission request / start motion activity update], and render the NativeView at the same time)

**Comment by darshankawar** [comment] 2020-07-03 10:17
Hi @thanhhuan1990,
Can you please confirm if you still experience this issue on latest Flutter version (eg : dev) and with latest `webview_flutter` plugin ?

**Comment by thanhhuan1990** [comment] 2020-07-06 02:37
hi @darshankawar ,
I'm so sorry, since my project are released few months ago without WebView because this issue. So I cannot reproduce it now.
So if another members do not face this issue, please close it. 
thank for you support.

**Comment by darshankawar** [comment] 2020-07-06 09:52
Since @thanhhuan1990 is unable to replicate this issue. I feel safe to close this ticket.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
Thank you.

**Closed by darshankawar** 2020-07-06 09:52 UTC
Labels: p: first party, p: webview, plugin, severe: crash
