### ISSUE TITLE
[Impeller] `SurfaceTexture`s created by some critical plugins do not render in OpenGL.

### ISSUE THREAD

**Issue by matanlurey** [flutter/flutter#141636] opened 2024-01-16 20:49 UTC
_Blocking https://github.com/flutter/flutter/issues/139702_, blocked by https://github.com/flutter/flutter/issues/141890.

---

As of HEAD, using Impeller and the OpenGLES backend:

```xml
<!-- AndroidManifest.xml -->
<meta-data android:name="io.flutter.embedding.android.EnableImpeller" android:value="true" />
<meta-data android:name="io.flutter.embedding.android.ImpellerBackend" android:value="opengles" />
```

... plugins considered important (i.e. `video_player`, `camera`) do not render:

<details>

<summary><code>packages/packages/video_player/video_player/example</code></summary>

```shell
$ cd $PACKAGES/packages/video_player/video_player/example

$ flutter run --local-engine=$ENGINE/out/android_debug_unopt_arm64 --local-engine-host=$ENGINE/out/host_debug_unopt_arm64
```

![image](https://github.com/flutter/flutter/assets/168174/637c0bf0-703e-4273-97ba-3ea942d328dc)

</details>

Do note that my [contrived sample app](https://github.com/matanlurey/flutter_engine_demos/tree/main/surface_texture) _does_ render, but it uses the surface different than the plugins:

<details>

<summary><code>surface_texture</code></summary>

```shell

```

![image](https://github.com/flutter/flutter/assets/168174/ab11d2ad-b327-473c-8aaf-4ceacd5feed4)

</details>

**Comment by matanlurey** [comment] 2024-01-16 20:53
I checked an assumption that potentially frames aren't being pumped:

```diff
diff --git a/shell/platform/android/surface_texture_external_texture_gl.cc b/shell/platform/android/surface_texture_external_texture_gl.cc
index b1cadee7f30..87ee983f8f4 100644
--- a/shell/platform/android/surface_texture_external_texture_gl.cc
+++ b/shell/platform/android/surface_texture_external_texture_gl.cc
@@ -70,7 +70,9 @@ SurfaceTextureExternalTextureImpellerGL::
         const fml::jni::ScopedJavaGlobalRef<jobject>& surface_texture,
         const std::shared_ptr<PlatformViewAndroidJNI>& jni_facade)
     : SurfaceTextureExternalTexture(id, surface_texture, jni_facade),
-      impeller_context_(context) {}
+      impeller_context_(context) {
+  FML_LOG(ERROR) << "SurfaceTextureExternalTextureImpellerGL";
+}
 
 SurfaceTextureExternalTextureImpellerGL::
     ~SurfaceTextureExternalTextureImpellerGL() {}
@@ -105,6 +107,7 @@ void SurfaceTextureExternalTextureImpellerGL::ProcessFrame(
   Update();
 
   dl_image_ = impeller::DlImageImpeller::Make(texture_);
+  FML_LOG(ERROR) << "SurfaceTextureExternalTextureImpellerGL::ProcessFrame";
 }
 
 void SurfaceTextureExternalTextureImpellerGL::Detach() {
```

... but it is:

```txt
E/flutter (21273): [ERROR:flutter/shell/platform/android/surface_texture_external_texture_gl.cc(110)] SurfaceTextureExternalTextureImpellerGL::ProcessFrame
E/flutter (21273): [ERROR:flutter/shell/platform/android/surface_texture_external_texture_gl.cc(110)] SurfaceTextureExternalTextureImpellerGL::ProcessFrame
E/flutter (21273): [ERROR:flutter/shell/platform/android/surface_texture_external_texture_gl.cc(110)] SurfaceTextureExternalTextureImpellerGL::ProcessFrame
E/flutter (21273): [ERROR:flutter/shell/platform/android/surface_texture_external_texture_gl.cc(110)] SurfaceTextureExternalTextureImpellerGL::ProcessFrame
E/flutter (21273): [ERROR:flutter/shell/platform/android/surface_texture_external_texture_gl.cc(110)] SurfaceTextureExternalTextureImpellerGL::ProcessFrame
E/flutter (21273): [ERROR:flutter/shell/platform/android/surface_texture_external_texture_gl.cc(110)] SurfaceTextureExternalTextureImpellerGL::ProcessFrame
```

**Comment by matanlurey** [comment] 2024-01-16 23:31
Ok I appear to have narrowed it down to _something_, TBD if this is the problem or not:

**There is no representation of `kTextureExternalOES` within `impeller::TextureGLES`**. That is, despite this:

```cc
// shell/platform/android/surface_texture_external_texture_gl.cc
void SurfaceTextureExternalTextureImpellerGL::ProcessFrame(
    PaintContext& context,
    const SkRect& bounds) {
  if (state_ == AttachmentState::kUninitialized) {
    // Generate the texture handle.
    impeller::TextureDescriptor desc;
    desc.type = impeller::TextureType::kTextureExternalOES;
    desc.storage_mode = impeller::StorageMode::kDevicePrivate;
    desc.format = impeller::PixelFormat::kR8G8B8A8UNormInt;
    desc.size = {static_cast<int>(bounds.width()),
                 static_cast<int>(bounds.height())};
    desc.mip_count = 1;
    texture_ = std::make_shared<impeller::TextureGLES>(
        impeller_context_->GetReactor(), desc,
        impeller::TextureGLES::IsWrapped::kWrapped);
```

... it's later interpreted as `A8UNormInt` (maybe OK, maybe not) and `Texture2D` (not OK). Will investigate further.

**Comment by matanlurey** [comment] 2024-01-16 23:50
Ok that above bit might be a false flag. I can confirm this code branch is never executed though:

```cc
    case TextureType::kTextureExternalOES:
      texture_type = GL_TEXTURE_EXTERNAL_OES;
      texture_target = GL_TEXTURE_EXTERNAL_OES;
      break;
```

**Comment by johnmccutchan** [comment] 2024-01-17 03:07
@bdero (who did a bunch of the OES Impeller plumbing work) could something have regressed in the OES code paths? I know we had to rewrite shaders and there were other complications in Impeller. AFAIK, this code is not tested today.

**Comment by bdero** [comment] 2024-01-17 18:26
Has this ever worked after being wired up in Android? If so, perhaps it's bisectable?

**Comment by matanlurey** [comment] 2024-01-17 18:27
> Has this ever worked after being wired up in Android? If so, perhaps it's bisectable?

I could try https://github.com/flutter/engine/pull/44734.

**Comment by johnmccutchan** [comment] 2024-01-17 18:56
it definitely worked when we landed it as I manually tested a bunch of platform views

**Comment by matanlurey** [comment] 2024-01-17 19:17
Ok, I'll start at https://github.com/flutter/flutter/pull/132609 I suppose.

**Comment by matanlurey** [comment] 2024-01-17 19:41
@johnmccutchan:

> it definitely worked when we landed it as I manually tested a bunch of platform views

Confirmed that it worked in https://github.com/flutter/flutter/pull/132609. I'll bisect.

**Comment by matanlurey** [comment] 2024-01-17 20:06
Started a bisect with a local Pixel 6 emulator:

- ✅ August 16
  https://github.com/flutter/flutter/pull/132609
  
- 🚫 September 25
  https://github.com/flutter/flutter/pull/135480
  ```txt
  E/emuglGLESv2_enc( 8187): device/generic/goldfish-opengl/system/GLESv2_enc/GL2Encoder.cpp:s_glTexParameteri:2604 GL error 0x500 condition [(target == GL_TEXTURE_EXTERNAL_OES && !isValidTextureExternalParam(pname, (GLenum)param))]
  ```

- 🚫 August 30
  https://github.com/flutter/flutter/pull/133683
  ```txt
  E/emuglGLESv2_enc( 8426): device/generic/goldfish-opengl/system/GLESv2_enc/GL2Encoder.cpp:s_glTexParameteri:2604 GL error 0x500 condition [(target == GL_TEXTURE_EXTERNAL_OES && !isValidTextureExternalParam(pname, (GLenum)param))]
  ```

- 🚫 August 22
  https://github.com/flutter/flutter/pull/133106
  ```txt
   E/emuglGLESv2_enc( 8620): device/generic/goldfish-opengl/system/GLESv2_enc/GL2Encoder.cpp:s_glTexParameteri:2604 GL error 0x500 condition [(target == GL_TEXTURE_EXTERNAL_OES && !isValidTextureExternalParam(pname, (GLenum)param))]
     ```

- ✅ August 18
  https://github.com/flutter/flutter/pull/132857

- ✅ August 20
  https://github.com/flutter/flutter/pull/132914

- ✅ August 21
  https://github.com/flutter/flutter/pull/132937

---

... so, something broke between https://github.com/flutter/flutter/pull/132937 and https://github.com/flutter/flutter/pull/133106. Investigating.

**Comment by matanlurey** [comment] 2024-01-17 20:15
My suspicion is https://github.com/flutter/engine/pull/44979, I have yet to confirm because building an older version of the engine that works with a particular version of the framework and video_player demo is NP-hard

I am going to just locally back out that change at HEAD and verify.

**Comment by matanlurey** [comment] 2024-01-17 20:35
Ok confirmed. I'll pair with @jonahwilliams this PM on a fix that hopefully doesn't break what @johnmccutchan was originally trying to fix :)

**Comment by matanlurey** [comment] 2024-01-17 21:14
Sat down with @jonahwilliams for ~10 minutes. Here is a quick summary:

- This comes down to implicitly using `TiledTextureContents` instead of `TextureContents`
- `DrawImactRect` uses `TextureContents` (optimized for "just a rectangle")
- `DrawRect` with an image shader will use `TiledTextureContents` (arbitrary path, anything really)

If we look in [`texture_contents.cc`](https://github.com/flutter/engine/blob/c16710721f7c18121a70650bcebc4a96a03353ae/impeller/entity/contents/texture_contents.cc#L163-L167), we'll see some branching code specific for OpenGLES, as well as similar code in `tiled_texture_contents.cc`.

We were originally hitting some validation errors (ironically when I made those breaking), so some of these branches might incorrect somewhere (we only tested on a static image, and not `video_player` or `camera`).

I'll need to look at the branching code for external OES textures in `TiledTextureContents` (and friends, potentially all the way down to the compiler and shaders if necessary) and see if anything stands out, possibly diffing this with the non-tiled branch. It's _something_ in there most likely.

**Comment by matanlurey** [comment] 2024-01-19 02:01
I didn't look at this today as long as I wanted, but I'll start fresh tomorrow.

Some resources I'm referencing:

- https://community.khronos.org/t/how-to-bind-a-framebuffer-to-an-gl-texture-external-oes-texture/104576
- https://registry.khronos.org/OpenGL/extensions/OES/OES_EGL_image_external.txt

---

We do have this block:

```cc
// tiled_texture_contents.cc

  if (is_external_texture) {
    SamplerDescriptor sampler_desc;
    // OES_EGL_image_external states that only CLAMP_TO_EDGE is valid, so we
    // emulate all other tile modes here by remapping the texture coordinates.
    sampler_desc.width_address_mode = SamplerAddressMode::kClampToEdge;
    sampler_desc.height_address_mode = SamplerAddressMode::kClampToEdge;
```

I wonder if we could or should use `EXT_EGL_image_external_wrap_modes`, considering the input:

```cc
// surface_texture_external_texture.cc

    if (!transform_.isIdentity()) {
      DlImageColorSource source(dl_image_, DlTileMode::kRepeat,
                                DlTileMode::kRepeat, sampling, &transform_);
```

> which adds REPEAT, MIRRORED_REPEAT, and CLAMP_TO_BORDER (if [OES_texture_border_clamp](https://www.khronos.org/registry/OpenGL/extensions/OES/OES_texture_border_clamp.txt)).

---

Nothing appeared off in the (generated) `texture_fill_external.frag.*` v `tiled_texture_fill_external.frag.*`:

<details>

<summary>Generated Code</summary>

```h
// texture_fill_external.frag.h

// THIS FILE IS GENERATED BY impellerc.
// DO NOT EDIT OR CHECK THIS INTO SOURCE CONTROL

#pragma once

#include "impeller/core/buffer_view.h"                
#include "impeller/core/sampler.h"                    
#include "impeller/core/shader_types.h"               
#include "impeller/core/resource_binder.h"            
#include "impeller/core/texture.h"                    

namespace impeller {

struct TextureFillExternalFragmentShader {
  // ===========================================================================
  // Stage Info ================================================================
  // ===========================================================================
  static constexpr std::string_view kLabel = "TextureFillExternal";
  static constexpr std::string_view kEntrypointName = "texture_fill_external_fragment_main";
  static constexpr ShaderStage kShaderStage = ShaderStage::kFragment;
  // The generator used to prepare these bindings. Metal generators may be used
  // by GLES backends but GLES generators are unsuitable for the metal backend.
  static constexpr std::string_view kGeneratorName = "OpenGL Shading Language (Relaxed Vulkan Semantics)";

  // ===========================================================================
  // Stage Inputs ==============================================================
  // ===========================================================================

  static constexpr auto kInputVTextureCoords = ShaderStageIOSlot { // v_texture_coords
    "v_texture_coords",             // name
    0u,          // attribute location
    0u,    // attribute set
    0u,           // attribute binding
    ShaderType::kFloat,     // type
    32u,    // bit width of type
    2u,     // vec size
    1u,      // number of columns
    0u,            // offset for interleaved layout
  };

  static constexpr auto kInputVAlpha = ShaderStageIOSlot { // v_alpha
    "v_alpha",             // name
    1u,          // attribute location
    0u,    // attribute set
    0u,           // attribute binding
    ShaderType::kFloat,     // type
    32u,    // bit width of type
    1u,     // vec size
    1u,      // number of columns
    0u,            // offset for interleaved layout
  };

  static constexpr std::array<const ShaderStageIOSlot*, 2> kAllShaderStageInputs = {
    &kInputVTextureCoords, // v_texture_coords
    &kInputVAlpha, // v_alpha
  };


  // ===========================================================================
  // Sampled Images ============================================================
  // ===========================================================================

  static constexpr auto kResourceSAMPLEREXTERNALOESTextureSampler = SampledImageSlot { // SAMPLER_EXTERNAL_OES_texture_sampler
    "SAMPLER_EXTERNAL_OES_texture_sampler",      // name
    64u,  // ext_res_0
    0u,        // set
    64u,    // binding
  };
  static ShaderMetadata kMetadataSAMPLEREXTERNALOESTextureSampler;
  // ===========================================================================
  // Stage Outputs =============================================================
  // ===========================================================================
  static constexpr auto kOutputFragColor = ShaderStageIOSlot { // frag_color
    "frag_color",             // name
    0u,          // attribute location
    0u,    // attribute set
    0u,           // attribute binding
    ShaderType::kFloat,     // type
    32u,    // bit width of type
    4u,     // vec size
    1u       // number of columns
  };
  static constexpr std::array<const ShaderStageIOSlot*, 1> kAllShaderStageOutputs = {
    &kOutputFragColor, // frag_color
  };

  // ===========================================================================
  // Resource Binding Utilities ================================================
  // ===========================================================================

  /// Bind combined image sampler for resource named SAMPLER_EXTERNAL_OES_texture_sampler.
  static bool BindSAMPLEREXTERNALOESTextureSampler(ResourceBinder& command, std::shared_ptr<const Texture> texture, std::shared_ptr<const Sampler> sampler) {
    return command.BindResource(ShaderStage::kFragment, kResourceSAMPLEREXTERNALOESTextureSampler, kMetadataSAMPLEREXTERNALOESTextureSampler, std::move(texture), std::move(sampler));
  }


  // ===========================================================================
  // Metadata for Vulkan =======================================================
  // ===========================================================================
  static constexpr std::array<DescriptorSetLayout,1> kDescriptorSetLayouts{
    DescriptorSetLayout{
      64, // binding = 64
      DescriptorType::kSampledImage, // descriptor_type = DescriptorType::kSampledImage
      ShaderStage::kFragment, // shader_stage = ShaderStage::kFragment
    },
  };

};  // struct TextureFillExternalFragmentShader

}  // namespace impeller

```

```h
// tiled_texture_fill_external_frag.h

// THIS FILE IS GENERATED BY impellerc.
// DO NOT EDIT OR CHECK THIS INTO SOURCE CONTROL

#pragma once

#include "impeller/core/buffer_view.h"                
#include "impeller/core/sampler.h"                    
#include "impeller/core/shader_types.h"               
#include "impeller/core/resource_binder.h"            
#include "impeller/core/texture.h"                    

namespace impeller {

struct TiledTextureFillExternalFragmentShader {
  // ===========================================================================
  // Stage Info ================================================================
  // ===========================================================================
  static constexpr std::string_view kLabel = "TiledTextureFillExternal";
  static constexpr std::string_view kEntrypointName = "tiled_texture_fill_external_fragment_main";
  static constexpr ShaderStage kShaderStage = ShaderStage::kFragment;
  // The generator used to prepare these bindings. Metal generators may be used
  // by GLES backends but GLES generators are unsuitable for the metal backend.
  static constexpr std::string_view kGeneratorName = "OpenGL Shading Language (Relaxed Vulkan Semantics)";
  // ===========================================================================
  // Struct Definitions ========================================================
  // ===========================================================================

  struct FragInfo {
    Scalar x_tile_mode; // (offset 0, size 4)
    Scalar y_tile_mode; // (offset 4, size 4)
  }; // struct FragInfo (size 8)

  // ===========================================================================
  // Stage Uniform & Storage Buffers ===========================================
  // ===========================================================================

  static constexpr auto kResourceFragInfo = ShaderUniformSlot { // FragInfo
    "FragInfo",     // name
    65u, // ext_res_0
    0u,       // set
    65u,   // binding
  };
  static ShaderMetadata kMetadataFragInfo;

  // ===========================================================================
  // Stage Inputs ==============================================================
  // ===========================================================================

  static constexpr auto kInputVTextureCoords = ShaderStageIOSlot { // v_texture_coords
    "v_texture_coords",             // name
    0u,          // attribute location
    0u,    // attribute set
    0u,           // attribute binding
    ShaderType::kFloat,     // type
    32u,    // bit width of type
    2u,     // vec size
    1u,      // number of columns
    0u,            // offset for interleaved layout
  };

  static constexpr auto kInputVAlpha = ShaderStageIOSlot { // v_alpha
    "v_alpha",             // name
    1u,          // attribute location
    0u,    // attribute set
    0u,           // attribute binding
    ShaderType::kFloat,     // type
    32u,    // bit width of type
    1u,     // vec size
    1u,      // number of columns
    0u,            // offset for interleaved layout
  };

  static constexpr std::array<const ShaderStageIOSlot*, 2> kAllShaderStageInputs = {
    &kInputVTextureCoords, // v_texture_coords
    &kInputVAlpha, // v_alpha
  };


  // ===========================================================================
  // Sampled Images ============================================================
  // ===========================================================================

  static constexpr auto kResourceSAMPLEREXTERNALOESTextureSampler = SampledImageSlot { // SAMPLER_EXTERNAL_OES_texture_sampler
    "SAMPLER_EXTERNAL_OES_texture_sampler",      // name
    64u,  // ext_res_0
    0u,        // set
    64u,    // binding
  };
  static ShaderMetadata kMetadataSAMPLEREXTERNALOESTextureSampler;
  // ===========================================================================
  // Stage Outputs =============================================================
  // ===========================================================================
  static constexpr auto kOutputFragColor = ShaderStageIOSlot { // frag_color
    "frag_color",             // name
    0u,          // attribute location
    0u,    // attribute set
    0u,           // attribute binding
    ShaderType::kFloat,     // type
    32u,    // bit width of type
    4u,     // vec size
    1u       // number of columns
  };
  static constexpr std::array<const ShaderStageIOSlot*, 1> kAllShaderStageOutputs = {
    &kOutputFragColor, // frag_color
  };

  // ===========================================================================
  // Resource Binding Utilities ================================================
  // ===========================================================================

  /// Bind uniform buffer for resource named FragInfo.
  static bool BindFragInfo(ResourceBinder& command, BufferView view) {
    return command.BindResource(ShaderStage::kFragment, kResourceFragInfo, kMetadataFragInfo, std::move(view));
  }

  /// Bind combined image sampler for resource named SAMPLER_EXTERNAL_OES_texture_sampler.
  static bool BindSAMPLEREXTERNALOESTextureSampler(ResourceBinder& command, std::shared_ptr<const Texture> texture, std::shared_ptr<const Sampler> sampler) {
    return command.BindResource(ShaderStage::kFragment, kResourceSAMPLEREXTERNALOESTextureSampler, kMetadataSAMPLEREXTERNALOESTextureSampler, std::move(texture), std::move(sampler));
  }


  // ===========================================================================
  // Metadata for Vulkan =======================================================
  // ===========================================================================
  static constexpr std::array<DescriptorSetLayout,2> kDescriptorSetLayouts{
    DescriptorSetLayout{
      65, // binding = 65
      DescriptorType::kUniformBuffer, // descriptor_type = DescriptorType::kUniformBuffer
      ShaderStage::kFragment, // shader_stage = ShaderStage::kFragment
    },
    DescriptorSetLayout{
      64, // binding = 64
      DescriptorType::kSampledImage, // descriptor_type = DescriptorType::kSampledImage
      ShaderStage::kFragment, // shader_stage = ShaderStage::kFragment
    },
  };

};  // struct TiledTextureFillExternalFragmentShader

}  // namespace impeller
```

</details>

**Comment by matanlurey** [comment] 2024-01-19 02:11
Note to myself: probably debug-log the PROC table for GL* calls and see if anything stands out.

**Comment by matanlurey** [comment] 2024-01-19 19:26
@jonahwilliams helped me track down the cause: _transform math_/coordinate systems: https://github.com/flutter/flutter/issues/141890.

**Comment by matanlurey** [comment] 2024-01-22 17:05
@bdero 

> @matanlurey I think the effect transform is behaving correctly (as per this [new golden](https://github.com/flutter/engine/pull/49930)). Could you try out this diff to see if it works?
> 
> ```diff
> diff --git a/shell/platform/android/surface_texture_external_texture.cc b/shell/platform/android/surface_texture_external_texture.cc
> index de83114e32..759f9d98e2 100644
> --- a/shell/platform/android/surface_texture_external_texture.cc
> +++ b/shell/platform/android/surface_texture_external_texture.cc
> @@ -62,7 +62,7 @@ void SurfaceTextureExternalTexture::Paint(PaintContext& context,
>      // back. OpenGL's coordinate system has Positive Y equivalent to up, while
>      // Skia's coordinate system has Negative Y equvalent to up.
>      context.canvas->Translate(bounds.x(), bounds.y() + bounds.height());
> -    context.canvas->Scale(bounds.width(), -bounds.height());
> +    context.canvas->Scale(1, -1);
> 
>      if (!transform_.isIdentity()) {
>        DlImageColorSource source(dl_image_, DlTileMode::kRepeat,
> @@ -73,7 +73,8 @@ void SurfaceTextureExternalTexture::Paint(PaintContext& context,
>          paintWithShader = *context.paint;
>        }
>        paintWithShader.setColorSource(&source);
> -      context.canvas->DrawRect(SkRect::MakeWH(1, 1), paintWithShader);
> +      context.canvas->DrawRect(SkRect::MakeWH(bounds.width(), bounds.height()),
> +                               paintWithShader);
>      } else {
>        context.canvas->DrawImage(dl_image_, {0, 0}, sampling, context.paint);
>      }
> ```

I can give this is a shot if it's more correct - I do want to note though the previous (pre-diff) canvas calls _do_ work on Skia.

**Comment by bdero** [comment] 2024-01-22 17:47
If you print the `transform_` under the `if (!transform_.isIdentity())` branch and switch between Impeller and Skia, does it print the same Matrix on both?

**Comment by johnmccutchan** [comment] 2024-01-22 17:48
Yeah, the fix can't be in surface_texture_external_texture.cc because it works fine on Skia. Unless we want to branch on skia and make it work differently there.

**Comment by johnmccutchan** [comment] 2024-01-22 17:48
@bdero they would be the same the matrix is coming from Java.

**Comment by matanlurey** [comment] 2024-01-22 17:48
> Yeah, the fix can't be in surface_texture_external_texture.cc because it works fine on Skia. Unless we want to branch on skia and make it work differently there.

The new patch works correctly on both fwiw.

**Comment by johnmccutchan** [comment] 2024-01-22 17:49
oh, well then, I'll stop chiming in :)

**Comment by matanlurey** [comment] 2024-01-22 17:50
> oh, well then, I'll stop chiming in :)

Wait, no it does not. Keep chiming in.

**Comment by johnmccutchan** [comment] 2024-01-22 17:50
I was going to say, the root bug here is that DlImage calls behave differently under Skia and Impeller.

**Comment by matanlurey** [comment] 2024-01-22 17:51
![Screenshot 2024-01-22 at 9 50 27 AM](https://github.com/flutter/flutter/assets/168174/277af7c9-f560-4b4f-86e2-e43f8a1d002d)

Skia is borked at https://github.com/flutter/flutter/issues/141636#issuecomment-1903677360. I'm going to chat with @bdero in a few minutes via VC if you're interested.

**Comment by johnmccutchan** [comment] 2024-01-22 17:51
ping me when y'all chat

**Comment by bdero** [comment] 2024-01-22 22:22
After playing with this locally, it turns out that [the patch I posted](https://github.com/flutter/flutter/issues/141636#issuecomment-1904434914) is actually correct.

The further issue is that when we're wrapping the external texture for Skia, were supplying a texture size of 1x1, which then causes Skia to map the UVs wrong. Full diff:

```diff
diff --git a/shell/platform/android/image_external_texture_gl.cc b/shell/platform/android/image_external_texture_gl.cc
index fd966c8a10..71823fd722 100644
--- a/shell/platform/android/image_external_texture_gl.cc
+++ b/shell/platform/android/image_external_texture_gl.cc
@@ -148,8 +148,8 @@ sk_sp<flutter::DlImage> ImageExternalTextureGLSkia::CreateDlImage(
     const SkRect& bounds) {
   GrGLTextureInfo textureInfo = {GL_TEXTURE_EXTERNAL_OES,
                                  texture_.get().texture_name, GL_RGBA8_OES};
-  auto backendTexture =
-      GrBackendTextures::MakeGL(1, 1, skgpu::Mipmapped::kNo, textureInfo);
+  auto backendTexture = GrBackendTextures::MakeGL(
+      bounds.width(), bounds.height(), skgpu::Mipmapped::kNo, textureInfo);
   return DlImage::Make(SkImages::BorrowTextureFrom(
       context.gr_context, backendTexture, kTopLeft_GrSurfaceOrigin,
       kRGBA_8888_SkColorType, kPremul_SkAlphaType, nullptr));
diff --git a/shell/platform/android/surface_texture_external_texture.cc b/shell/platform/android/surface_texture_external_texture.cc
index de83114e32..759f9d98e2 100644
--- a/shell/platform/android/surface_texture_external_texture.cc
+++ b/shell/platform/android/surface_texture_external_texture.cc
@@ -62,7 +62,7 @@ void SurfaceTextureExternalTexture::Paint(PaintContext& context,
     // back. OpenGL's coordinate system has Positive Y equivalent to up, while
     // Skia's coordinate system has Negative Y equvalent to up.
     context.canvas->Translate(bounds.x(), bounds.y() + bounds.height());
-    context.canvas->Scale(bounds.width(), -bounds.height());
+    context.canvas->Scale(1, -1);

     if (!transform_.isIdentity()) {
       DlImageColorSource source(dl_image_, DlTileMode::kRepeat,
@@ -73,7 +73,8 @@ void SurfaceTextureExternalTexture::Paint(PaintContext& context,
         paintWithShader = *context.paint;
       }
       paintWithShader.setColorSource(&source);
-      context.canvas->DrawRect(SkRect::MakeWH(1, 1), paintWithShader);
+      context.canvas->DrawRect(SkRect::MakeWH(bounds.width(), bounds.height()),
+                               paintWithShader);
     } else {
       context.canvas->DrawImage(dl_image_, {0, 0}, sampling, context.paint);
     }
diff --git a/shell/platform/android/surface_texture_external_texture_gl.cc b/shell/platform/android/surface_texture_external_texture_gl.cc
index b1cadee7f3..18c61c13ae 100644
--- a/shell/platform/android/surface_texture_external_texture_gl.cc
+++ b/shell/platform/android/surface_texture_external_texture_gl.cc
@@ -49,7 +49,7 @@ void SurfaceTextureExternalTextureGL::ProcessFrame(PaintContext& context,
   GrGLTextureInfo textureInfo = {GL_TEXTURE_EXTERNAL_OES, texture_name_,
                                  GL_RGBA8_OES};
   auto backendTexture =
-      GrBackendTextures::MakeGL(1, 1, skgpu::Mipmapped::kNo, textureInfo);
+      GrBackendTextures::MakeGL(bounds.width(), bounds.height(), skgpu::Mipmapped::kNo, textureInfo);
   dl_image_ = DlImage::Make(SkImages::BorrowTextureFrom(
       context.gr_context, backendTexture, kTopLeft_GrSurfaceOrigin,
       kRGBA_8888_SkColorType, kPremul_SkAlphaType, nullptr));
```

**Comment by matanlurey** [comment] 2024-01-30 01:06
Re-opened, https://github.com/flutter/engine/pull/50158 (reverted).

**Comment by matanlurey** [comment] 2024-01-30 20:36
I am dropping working on this for at least a week to focus on Android embedder testing in the engine.

**Comment by matanlurey** [comment] 2024-02-01 17:59
This is not closed :(

**Comment by bdero** [comment] 2024-02-06 01:05
@matanlurey Catching up on this situation. Are there any remaining Impeller-related unknowns I could help track down here? I'd be happy to take a look.

**Comment by matanlurey** [comment] 2024-02-06 01:11
> @matanlurey Catching up on this situation. Are there any remaining Impeller-related unknowns I could help track down here? I'd be happy to take a look.

Thanks!

Not _exactly_ Impeller specific, but the [change you proposed](https://github.com/flutter/flutter/issues/141636#issuecomment-1904930742) was reverted because it broke the `camera` plugin.

We still lack a solution that:

1. Works on Skia 
2. Works on Impeller + OpenGLES (I think this is no longer a top priority, fwiw)
3. Works on the `camera` and `video_player` plugin examples (since we don't have strong testing in this area)

The more Impeller specific issue is the Impeller + Vulkan support - perhaps you could reach out to John @ https://github.com/flutter/flutter/issues/142082#issuecomment-1917827593 and see if he could use help (it is a pixel/format issue).

**Comment by johnmccutchan** [comment] 2024-02-06 01:15
@bdero I could use your help wiring up support for https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VK_KHR_sampler_ycbcr_conversion.html. Fixing Impeller texture sampling with ycbcr format would unblock video_player (and maybe? camera).

**Comment by bdero** [comment] 2024-02-06 04:51
@matanlurey 
> Fixing Impeller texture sampling with ycbcr format would unblock video_player (and maybe? camera).

I see. So looking at the [revert](https://github.com/flutter/engine/pull/50158), it looks like you were able to reproduce the issue against the `packages/packages/camera/camera/example` package. To clarify, it sounds like Skia was busted with the change (and Impeller is up in the air because we haven't quite gotten it working right yet due to the conversion issue you linked)?

@johnmccutchan
> Fixing Impeller texture sampling with ycbcr format would unblock video_player (and maybe? camera).

I haven't taken a close look yet, but would it be viable to just use `impeller::DlImageImpeller::MakeFromYUVTextures` as a stopgap? This is what we do for handling external yCbCr textures on [MacOS/iOS](https://github.com/flutter/engine/blob/7c2f6c811270237bfab5d2d4bc508ea5a015bca9/shell/platform/darwin/graphics/FlutterDarwinExternalTextureMetal.mm#L193-L217) and does not rely on extensions. Granted, this route uses a filter and I'm sure we can improve perf later by adding specialized sampler support.

On MacOS/iOS we receive the Y and UV components as separate textures and wrap them, but if a different configuration is necessary adding support should be easy.

**Comment by bdero** [comment] 2024-02-07 18:37
I talked with @matanlurey offline and it sounds like this bug is not a blocker for releasing Impeller on Android.

@johnmccutchan I checked the codebase and it looks like we don't have the external image/surface stuff for Vulkan checked in yet. It sounds like you've got this mostly in the bag, but I'm happy to pair with you on the YUV aspect sometime if you'd like. Let me know how I can help!

**Comment by matanlurey** [comment] 2024-02-07 18:50
I concur Brandon.

I'm removing us as assignees and we can keep it a P2.

**Comment by jonahwilliams** [comment] 2024-02-07 19:25
Yes that confused me too: this is specific to GLES.

**Comment by johnmccutchan** [comment] 2024-02-07 19:26
Is there a Vulkan version of this bug or can we just use this one?

**Comment by bdero** [comment] 2024-02-07 19:41
> I'm confused We've had external texture support for Vulkan checked-in for months: See https://github.com/flutter/engine/blob/main/impeller/renderer/backend/vulkan/android_hardware_buffer_texture_source_vk.h

Where's the spot in the codebase where we're forming the DisplayList image for external textures and asking Impeller to render it? Or does it not work similarly to the OpenGL route in the Android embedder?

**Comment by bdero** [comment] 2024-02-07 19:45
I'm gonna post this on the other issue so as to not risk clogging up this issue more 😄

**Comment by vashworth** [comment] 2024-02-07 20:01
> This is not closed :(

@matanlurey I have no idea how this got closed, looks like when I merged main into my local branch it auto-closed it? Do you know how I can prevent that? Anyways, sorry about that.

**Comment by gmackall** [comment] 2024-02-15 19:48
> > This is not closed :(
> 
> @matanlurey I have no idea how this got closed, looks like when I merged main into my local branch it auto-closed it? Do you know how I can prevent that? Anyways, sorry about that.

Yes, for some reason updating a branch (at least on the github ui) in a way that pulls in a commit that says it fixes an issue will repeatedly close that issue. I've run in to this on a couple of other issues

**Comment by matanlurey** [comment] 2024-03-28 20:37
OpenGL + Impeller is no longer a priority. Downgrading.

**Closed** 2024-09-24 19:25 UTC
Labels: platform-android, engine, P3, blocked, e: impeller, a: plugins, team-engine, triaged-engine, e: opengl
