### ISSUE TITLE
firebase_database setPersistenceCacheSizeBytes throws exception

### ISSUE THREAD

**Issue by benadrasni** [flutter/flutter#51710] opened 2020-02-29 20:54 UTC
## Steps to Reproduce

Call: FirebaseDatabase.instance.setPersistenceCacheSizeBytes(1024 * 1024 * 20);

**Expected results:** 

No exception

**Actual results:** 
Exception:

E/MethodChannel#plugins.flutter.io/firebase_database(28048): Failed to handle method call
E/MethodChannel#plugins.flutter.io/firebase_database(28048): java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Long
E/MethodChannel#plugins.flutter.io/firebase_database(28048): 	at io.flutter.plugins.firebase.database.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:275)
E/MethodChannel#plugins.flutter.io/firebase_database(28048): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:231)
E/MethodChannel#plugins.flutter.io/firebase_database(28048): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:93)
E/MethodChannel#plugins.flutter.io/firebase_database(28048): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:642)
E/MethodChannel#plugins.flutter.io/firebase_database(28048): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#plugins.flutter.io/firebase_database(28048): 	at android.os.MessageQueue.next(MessageQueue.java:336)
E/MethodChannel#plugins.flutter.io/firebase_database(28048): 	at android.os.Looper.loop(Looper.java:174)
E/MethodChannel#plugins.flutter.io/firebase_database(28048): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/MethodChannel#plugins.flutter.io/firebase_database(28048): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.flutter.io/firebase_database(28048): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/MethodChannel#plugins.flutter.io/firebase_database(28048): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

<details>
  <summary>Logs</summary>

Analyzing abherbs_flutter...
No issues found! (ran in 7.6s)

[√] Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [Version 6.1.7601], locale sk-SK)
    • Flutter version 1.12.13+hotfix.8 at C:\Dev\flutter
    • Framework revision 0b8abb4724 (3 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Dev\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = C:\Dev\Android\sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[!] IntelliJ IDEA Ultimate Edition (version 2019.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2018.3.3
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 7.0 (API 24) (emulator)

! Doctor found issues in 1 category.

</details>

**Comment by iapicca** [comment] 2020-03-02 08:50
Hi @benadrasni 
for what I can see the issue is related to a FlutterFire plugin,
please open the issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
thank you

**Closed by iapicca** 2020-03-02 08:50 UTC
