### ISSUE TITLE
Expansion Tile programmatic expansion control

### ISSUE THREAD

**Issue by glaceon2000** [flutter/flutter#110257] opened 2022-08-25 10:40 UTC

**Comment by danagbemava-nc** [comment] 2022-08-25 11:06
Closing this as a duplicate of https://github.com/flutter/flutter/issues/60387. 

Kindly follow up in the linked issue for updates. Please upvote the original issue as well. 

Thank you

**Closed by danagbemava-nc** 2022-08-25 11:06 UTC
Labels: in triage
