### ISSUE TITLE
LUCI agent for mac_module_test_ios developer cert expired?

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#68061] opened 2020-10-14 00:10 UTC
```
[module_test_ios] [STDOUT] stdout: Xcode's output:
[module_test_ios] [STDOUT] stdout: ↳
[module_test_ios] [STDOUT] stdout:     note: Using new build systemnote: Planning buildnote: Constructing build descriptionerror: unable to resolve run destination SDK: 'iphoneos13.0' (in target 'Runner' from project 'Runner')error: unable to find sdk 'iphoneos13.0' (in target 'Runner' from project 'Runner')
[module_test_ios] [STDOUT] stdout: 
[module_test_ios] [STDOUT] stderr: ════════════════════════════════════════════════════════════════════════════════
[module_test_ios] [STDOUT] stderr: Building a deployable iOS app requires a selected Development Team with a 
[module_test_ios] [STDOUT] stderr: Provisioning Profile. Please ensure that a Development Team is selected by:
[module_test_ios] [STDOUT] stderr:   1- Open the Flutter project's Xcode target with
[module_test_ios] [STDOUT] stderr:        open ios/Runner.xcworkspace
[module_test_ios] [STDOUT] stderr:   2- Select the 'Runner' project in the navigator then the 'Runner' target
[module_test_ios] [STDOUT] stderr:      in the project settings
[module_test_ios] [STDOUT] stderr:   3- Make sure a 'Development Team' is selected. 
[module_test_ios] [STDOUT] stderr:      - For Xcode 10, look under General > Signing > Team.
[module_test_ios] [STDOUT] stderr:      - For Xcode 11 and newer, look under Signing & Capabilities > Team.
[module_test_ios] [STDOUT] stderr:      You may need to:
[module_test_ios] [STDOUT] stderr:          - Log in with your Apple ID in Xcode first
[module_test_ios] [STDOUT] stderr:          - Ensure you have a valid unique Bundle ID
[module_test_ios] [STDOUT] stderr:          - Register your device with your Apple Developer Account
[module_test_ios] [STDOUT] stderr:          - Let Xcode automatically provision a profile for your app
[module_test_ios] [STDOUT] stderr:   4- Build or run your project again
[module_test_ios] [STDOUT] stderr: 
[module_test_ios] [STDOUT] stderr: For more information, please visit:
[module_test_ios] [STDOUT] stderr:   https://flutter.dev/setup/#deploy-to-ios-devices
[module_test_ios] [STDOUT] stderr: 
[module_test_ios] [STDOUT] stderr: Or run on an iOS simulator without code signing
```

**Comment by keyonghan** [comment] 2020-10-14 00:31
The rerun succeeded, but it hit this error again for the latest commit run..

**Comment by keyonghan** [comment] 2020-10-15 22:34
Turns out to be duplicate of https://github.com/flutter/flutter/issues/68144

**Closed by keyonghan** 2020-10-15 22:34 UTC
Labels: P1, passed first triage, passed secondary triage, team: infra
