### ISSUE TITLE
"pub get" out of work after fail on "pub global activate devtools"

### ISSUE THREAD

**Issue by mingoal** [flutter/flutter#47034] opened 2019-12-14 09:17 UTC
hi,
I can't add new package with `flutter pub get` anymore. Is there anyway to rescure it manually? `flutter pub get` worked for a while. It should not a virus or permissions issue.

With fresh install, `flutter pub get` worked. Adding new packages worked fine. When I tried to use the devtools, ran `flutter pub global activate devtools` fails and said _Failed to rename xxx_, then `flutter pub get` never works correctly.

## Steps to Reproduce

1. flutter pub global activate devtools    >>>>> failed to rename directory ...
2. flutter pub get                                    >>>>> failed to rename directory ...

## Logs

`flutter pub global activate devtools` output
```
flutter pub global activate devtools
Resolving dependencies...
+ args 1.5.2
+ async 2.4.0
+ browser_launcher 0.1.5
+ charcode 1.1.2
+ collection 1.14.12
+ convert 2.1.1
+ crypto 2.1.4
+ devtools 0.1.13
+ devtools_server 0.1.12
+ http 0.12.0+2
+ http_multi_server 2.1.0
+ http_parser 3.1.3
+ logging 0.11.3+2
+ meta 1.1.8
+ mime 0.9.6+3
+ path 1.6.4
+ pedantic 1.9.0
+ shelf 0.7.5
+ shelf_static 0.2.8
+ source_span 1.5.5
+ sse 2.1.2 (3.0.0 available)
+ stack_trace 1.9.3
+ stream_channel 2.0.0
+ string_scanner 1.0.5
+ term_glyph 1.1.0
+ typed_data 1.1.6
+ usage 3.4.1
+ uuid 2.0.4
+ vm_service 2.1.3
+ webkit_inspection_protocol 0.5.0
Downloading devtools 0.1.13...
Failed to rename directory because access was denied.
This may be caused by a virus scanner or having a file
in the directory open in another application.
pub finished with exit code 1
```

`flutter pub get` output
```
Failed to rename directory because access was denied.
This may be caused by a virus scanner or having a file
in the directory open in another application.
Running "flutter pub get" in XXXXX...
pub get failed (1; in the directory open in another application.)
```

`flutter doctor -v` output
```
[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.17763.864], locale
    zh-CN)
    • Flutter version 1.12.13+hotfix.5 at C:\Users\XXXXX\bin\flutter
    • Framework revision 27321ebbad (3 days ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\XXXXXX\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 42.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code, 64-bit edition (version 1.31.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.7.0

[!] Connected device
    ! No devices available
```

**Comment by jonahwilliams** [comment] 2020-01-09 21:15
This is likely an issue that needs to be solved in pub

**Comment by pedromassangocode** [comment] 2020-09-24 12:14
Hi @mingoal 
From what I can see, the issue is related to a Pub rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/dart-lang/pub).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by pedromassangocode** 2020-09-24 12:14 UTC
Labels: dependency: dart, framework
