### ISSUE TITLE
Bug when User re-chose video 

### ISSUE THREAD

**Issue by QuDaMyker** [flutter/flutter#156047] opened 2024-10-02 08:26 UTC
### Steps to reproduce

First, the init video is correct (New Video), but when I go back to the previous page and re-init the video (take old video) about 5-7 times, it throws exceptions, It only go correct when I turn off app and re-open

### Expected results

Good working

### Actual results

Throw excpetion

### Code sample

<details open><summary>Code sample</summary>

```dart
videoPlayerController = VideoPlayerController.file(File(videoPath))
        ..initialize().then((_) {
          videoPlayerController?.setLooping(isLooping.value);
          
          log('init video');
        })
        ..addListener(_updateVideoState);
```

</details>

### Logs

<details open><summary>Logs</summary>

```console
E/MediaCodecVideoRenderer( 8833):       at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:1137)
E/MediaCodecVideoRenderer( 8833):       ... 12 more
E/ExoPlayerImplInternal( 8833): Playback error
E/ExoPlayerImplInternal( 8833):   androidx.media3.exoplayer.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, avc1.64001F, -1, null, [800, 800, 8.0, ColorInfo(Unset color space, Limited range, Unset color transfer, false, 8bit Luma, 8bit Chroma)], [-1, -1]), format_supported=YES
E/ExoPlayerImplInternal( 8833):       at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:640)
E/ExoPlayerImplInternal( 8833):       at android.os.Handler.dispatchMessage(Handler.java:102)
E/ExoPlayerImplInternal( 8833):       at android.os.Looper.loopOnce(Looper.java:230)
E/ExoPlayerImplInternal( 8833):       at android.os.Looper.loop(Looper.java:319)
E/ExoPlayerImplInternal( 8833):       at android.os.HandlerThread.run(HandlerThread.java:67)
E/ExoPlayerImplInternal( 8833):   Caused by: androidx.media3.exoplayer.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.sprd.h264.decoder, Format(1, null, null, video/avc, avc1.64001F, -1, null, [800, 800, 8.0, ColorInfo(Unset color space, Limited range, Unset color transfer, false, 8bit Luma, 8bit Chroma)], [-1, -1])
E/ExoPlayerImplInternal( 8833):       at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:1144)
E/ExoPlayerImplInternal( 8833):       at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.maybeInitCodecOrBypass(MediaCodecRenderer.java:588)
E/ExoPlayerImplInternal( 8833):       at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1602)
E/ExoPlayerImplInternal( 8833):       at androidx.media3.exoplayer.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:1182)
E/ExoPlayerImplInternal( 8833):       at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.readSourceOmittingSampleData(MediaCodecRenderer.java:1042)
E/ExoPlayerImplInternal( 8833):       at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:860)
E/ExoPlayerImplInternal( 8833):       at androidx.media3.exoplayer.video.MediaCodecVideoRenderer.render(MediaCodecVideoRenderer.java:1018)
E/ExoPlayerImplInternal( 8833):       at androidx.media3.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:1136)
E/ExoPlayerImplInternal( 8833):       at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:561)
E/ExoPlayerImplInternal( 8833):       ... 4 more
E/ExoPlayerImplInternal( 8833):   Caused by: android.media.MediaCodec$CodecException: Failed to initialize OMX.sprd.h264.decoder, error 0xfffffff4 (NO_MEMORY)
E/ExoPlayerImplInternal( 8833):       at android.media.MediaCodec.native_setup(Native Method)
E/ExoPlayerImplInternal( 8833):       at android.media.MediaCodec.<init>(MediaCodec.java:2094)
E/ExoPlayerImplInternal( 8833):       at android.media.MediaCodec.<init>(MediaCodec.java:2072)
E/ExoPlayerImplInternal( 8833):       at android.media.MediaCodec.createByCodecName(MediaCodec.java:2042)
E/ExoPlayerImplInternal( 8833):       at androidx.media3.exoplayer.mediacodec.AsynchronousMediaCodecAdapter$Factory.createAdapter(AsynchronousMediaCodecAdapter.java:105)
E/ExoPlayerImplInternal( 8833):       at androidx.media3.exoplayer.mediacodec.DefaultMediaCodecAdapterFactory.createAdapter(DefaultMediaCodecAdapterFactory.java:137)
E/ExoPlayerImplInternal( 8833):       at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:1225)
E/ExoPlayerImplInternal( 8833):       at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:1137)
E/ExoPlayerImplInternal( 8833):       ... 12 more
E/flutter ( 8833): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(VideoError, Video player had error androidx.media3.exoplayer.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, avc1.64001F, -1, null, [800, 800, 8.0, ColorInfo(Unset color space, Limited range, Unset color transfer, false, 8bit Luma, 8bit Chroma)], [-1, -1]), format_supported=YES, null, null)
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by huycozy** [comment] 2024-10-02 11:16
Hi @QuDaMyker 
What is your `video_player_android` version? (please check it from `pubspec.lock` file). Maybe related to https://github.com/flutter/flutter/issues/154559 which was fixed recently.

Can you provide detailed steps to reproduce this issue? A demo video would be helpful. And please provide the complete output error trace as well. Thanks!

**Comment by QuDaMyker** [comment] 2024-10-03 02:32
> Hi @QuDaMyker What is your `video_player_android` version? (please check it from `pubspec.lock` file). Maybe related to #154559 which was fixed recently.
> 
> Can you provide detailed steps to reproduce this issue? A demo video would be helpful. And please provide the complete output error trace as well. Thanks!

Thanks, currently my project uses video_player: 2.9.1
Sorry, I cannot provide a video because it contains private data
Fortunately, I found a solution for this issue
```dart
void _initializeVideoPlayer(String videoPath) {
    try {
      if (videoPlayerController != null) {
        videoPlayerController!.removeListener(_updateVideoState);
        videoPlayerController!.dispose();
        videoPlayerController = null;
      }

      videoPlayerController = VideoPlayerController.file(File(videoPath))
        ..initialize().then((_) {
          videoPlayerController?.setLooping(isLooping.value);
          videoState.value = FetchState.LOADED;
          log('init video');
        })
        ..addListener(_updateVideoState);
    } catch (e) {
      print(e);
      videoState.value = FetchState.ERROR;
    }
  }
```

**Comment by huycozy** [comment] 2024-10-03 05:00
Looks like an implementation issue. Closing this as solved as mentioned above.

**Closed by huycozy** 2024-10-03 05:00 UTC
Labels: in triage
