### ISSUE TITLE
[shared_preferences] cast exception with get/setStringList: `type 'List<Object?>' is not a subtype of type 'List?'`

### ISSUE THREAD

**Issue by itismejy** [flutter/flutter#152607] opened 2024-07-31 09:07 UTC
### Steps to reproduce

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: type 'List<Object?>' is not a subtype of type 'List<String>?' in type cast

### Expected results

setStringList is not working properly

### Actual results

Should be a `List<String>`, not `List<Object>`

### Code sample

<details open><summary>Code sample</summary>

```dart
final SharedPreferencesWithCache prefsWithCache =
    await SharedPreferencesWithCache.create(
  cacheOptions: const SharedPreferencesWithCacheOptions(
    // When an allowlist is included, any keys that aren't included cannot be used.
    allowList: <String>{'action'},
  ),
);

await prefsWithCache!.setStringList('action', <String>['Earth', 'Moon', 'Sun']);
                            
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by iapicca** [comment] 2024-07-31 09:46
works for me

```dart
import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

final class SharedPreferencesKeys {
  static const action = 'action';
}

void main() async {
  final prefsWithCache = await SharedPreferencesWithCache.create(
    cacheOptions: const SharedPreferencesWithCacheOptions(
      allowList: {SharedPreferencesKeys.action},
    ),
  );

  await prefsWithCache.setStringList(
    SharedPreferencesKeys.action,
    const ['Earth', 'Moon', 'Sun'],
  );

  final actions =
      prefsWithCache.getStringList(SharedPreferencesKeys.action) ?? [];

  runApp(
    MaterialApp(
      home: Material(
        child: Column(
          children: [
            for (final action in actions) Text(action),
          ],
        ),
      ),
    ),
  );
}
```
```console
[!] Flutter (Channel stable, 3.22.3, on macOS 14.5 23F79 darwin-arm64, locale en-US)
    ! Warning: `dart` on your path resolves to /opt/homebrew/Cellar/dart/3.4.4/libexec/bin/dart, which is not inside your current Flutter SDK checkout at
      /Users/francesco/fvm/versions/stable. Consider adding /Users/francesco/fvm/versions/stable/bin to the front of your path.
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.91.1)
[✓] Connected device (3 available)
[✓] Network resources
```
```yaml
name: issue_152607
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
```

**Comment by itismejy** [comment] 2024-07-31 09:49
is this required?
final class SharedPreferencesKeys {
  static const action = 'action';
}

The docs says just using the string as the key is fine

**Comment by iapicca** [comment] 2024-07-31 09:52
> is this required? final class SharedPreferencesKeys { static const action = 'action'; }
> 
> The docs says just using the string as the key is fine

no, this is just me avoiding hard-coding the string 'action' all over the place

**Comment by itismejy** [comment] 2024-07-31 09:57
prefsWithCache = await SharedPreferencesWithCache.create(
    cacheOptions: const SharedPreferencesWithCacheOptions(),
  );
  // await prefsWithCache!.clear();

  List<String>? savedIngredients = prefsWithCache!.getStringList('ingredients');
  
  
   await prefsWithCache!.setStringList('ingredients', ingredientsState.ingredients);

**Comment by itismejy** [comment] 2024-07-31 10:02
I think it has somethign to do when prefsWithCache is used outside of main? I cant seem to setStringList when its outside of main, it keeps complaining of List<Object?>, no issue when doing setString  outside of main

**Comment by itismejy** [comment] 2024-07-31 10:03
eg something like this:

import 'package:easybites/globals/constants.dart';
import 'package:easybites/pages/ingredients/ingredients_state.dart';
import 'package:easybites/router/router.dart';
import 'package:easybites/router/router_observer.dart';
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:shared_preferences/shared_preferences.dart';

void main() async {
  await WidgetsFlutterBinding.ensureInitialized();
  prefsWithCache = await SharedPreferencesWithCache.create(
    cacheOptions: const SharedPreferencesWithCacheOptions(),
  );
  // await prefsWithCache!.clear();

  List<String>? savedIngredients = prefsWithCache!.getStringList('ingredients');

  print("ingredients");
  // await prefsWithCache!.setStringList('ingredients', ['cherry', 'diamond']);
  print(savedIngredients);

  runApp(ChangeNotifierProvider(
      create: (context) => IngredientsState()..updateState(savedIngredients ?? []), child: const MainApp()));
}

class MainApp extends StatelessWidget {
  const MainApp({super.key});

  @override
  Widget build(BuildContext context) {
    prefsWithCache!.setStringList('ingredients', ['cherry', 'diamond']);
    screenWidth = MediaQuery.of(context).size.width;
    screenWidthRatio = screenWidth / prototypeWidth;
    screenHeight = MediaQuery.of(context).size.height;
    screenHeightRatio = screenHeight / prototypeHeight;

    return MaterialApp(
      navigatorObservers: [routeObserver],
      debugShowCheckedModeBanner: false,
      onGenerateRoute: generateRoute,
    );
  }
}

**Comment by iapicca** [comment] 2024-07-31 10:16
> I have a global variable of:

please don't do that,
if you really really want something similar to a global variable you can use a `singleton`

<details>
  <summary>singleton example</summary>

```dart
import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

final class SharedPreferencesKeys {
  static const action = 'action';
}

class SharedPreferencesSingleton {
  SharedPreferencesSingleton._internal();

  factory SharedPreferencesSingleton() => _instance;
  static final _instance = SharedPreferencesSingleton._internal();
  SharedPreferencesWithCache? _prefsWithCache;

  /// you have to remember to call `initialize()`
  Future<void> initialize({Set<String>? allowList}) async {
    _prefsWithCache ??= await SharedPreferencesWithCache.create(
      cacheOptions: SharedPreferencesWithCacheOptions(
        allowList: allowList,
      ),
    );
  }

  /// you have to remember to call `dispose()`
  void dispose() {
    _prefsWithCache = null;
  }

  SharedPreferencesWithCache get prefsWithCache =>
      _prefsWithCache ??
      () {
        throw Exception('you forgot to initialize');
      }();
}

void main() async {
  await SharedPreferencesSingleton().initialize(
    allowList: {SharedPreferencesKeys.action},
  );

  await SharedPreferencesSingleton().prefsWithCache.setStringList(
    SharedPreferencesKeys.action,
    const ['Earth', 'Moon', 'Sun'],
  );

  runApp(const MyApp());
}

class MyApp extends StatefulWidget {
  const MyApp({super.key});

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  void dispose() {
    SharedPreferencesSingleton().dispose();
    super.dispose();
  }

  @override
  Widget build(context) => const MaterialApp(home: MyHomePage());
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key});

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(context) {
    final actions = SharedPreferencesSingleton()
            .prefsWithCache
            .getStringList(SharedPreferencesKeys.action) ??
        [];
    return Material(
      child: Column(
        children: [
          for (final action in actions) Text(action),
        ],
      ),
    );
  }
}
```

</details>

but what you might actually need is a state management
I can recommend riverpod.dev

**Comment by itismejy** [comment] 2024-07-31 10:20
id like for my variables to be stored locally, so when user starts app again the data is stored again. and throughout the app the user can write to shared preferences. im already using providers for state management

**Comment by iapicca** [comment] 2024-07-31 10:32
I think this is more a discussion on best practices rather than an issue with flutter,
maybe it's better to close the issue and discuss it on discord

**Comment by darshankawar** [comment] 2024-07-31 11:14
@itismejy 
Check the plugin [example](https://github.com/flutter/packages/blob/main/packages/shared_preferences/shared_preferences/example/lib/main.dart) to see if it helps in your case or not.
Also check if [this](https://github.com/flutter/flutter/issues/128560) helps.

**Comment by stuartmorgan** [comment] 2024-07-31 11:44
@itismejy Please provide a complete reproducible test case that someone can run to see the issue; so far you've only provided fragments that don't compile in isolation, and the description of the error are too vague to be able to investigate (e.g., [this comment](https://github.com/flutter/flutter/issues/152607#issuecomment-2260130683) only shows one line of code and says it causes an exception, but the line of code is a `set` call and the exception described can only come from `get`, so there are clearly missing steps there.)

**Comment by stuartmorgan** [comment] 2024-07-31 11:47
> I think this is more a discussion on best practices rather than an issue with flutter,
> maybe it's better to close the issue and discuss it on discord

Please do not discourage people from reporting exceptions. Whether `shared_preferences` is the subjectively best tool for the use case, or whether globals are good or bad, is not material to the issue here. If a valid sequence of calls to the `shared_preferences` API can cause a cast exception, then there's a bug in `shared_preferences`.

**Comment by stuartmorgan** [comment] 2024-07-31 12:02
Oh, I see how this happens.

@tarrinneal In the review I said we didn't need element-level casting for `getStringList` with the cached version because the entries would already be strongly typed from the setter, but that's not true when the cache is populated via `getAll`. So on macOS for instance, I get the exception if I simply store a string list, quit, and then try to read it on launch.

We either need to element-cast in `getStringList` after all, or we need to element-cast every `List` value type once in `getAll`.

**Comment by iapicca** [comment] 2024-07-31 12:04
> > > I think it has somethign to do when prefsWithCache is used outside of main? I cant seem to setStringList when its outside of main, it keeps complaining of List<Object?>, no issue when doing setString outside of main
> >
> > I think this is more a discussion on best practices rather than an issue with flutter,
> > maybe it's better to close the issue and discuss it on discord
> 
> @iapicca Please do not discourage people from reporting exceptions. Whether `shared_preferences` is the subjectively best tool for the use case, or whether globals are good or bad, is not material to the issue here. If a valid sequence of calls to the `shared_preferences` API can cause a cast exception, then there's a bug in `shared_preferences`.

I thought the reporter identified the issue in being caused by the use of the package rather than the package itself,
my bad

**Comment by itismejy** [comment] 2024-08-01 13:03
Thanks guys for your work!

**Closed** 2024-08-01 17:52 UTC
Labels: p: shared_preferences, package, team-ecosystem, P1, triaged-ecosystem
