### ISSUE TITLE
UI examples under https://docs.flutter.dev/ are not working

### ISSUE THREAD

**Issue by bharatbhaskar** [flutter/flutter#125377] opened 2023-04-23 02:06 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Go to https://docs.flutter.dev/development/ui/widgets-intro
2. Click Run in first example.
3. It gives JS compilation issue (Screenshot attached).
4. None of the UI examples are working. Same issue in all.

### Expected results

The RUN should give UI output in the Widgets' examples.

### Actual results

No UI Result.

### Code sample

NA

### Screenshots or Video

![image](https://user-images.githubusercontent.com/46080232/233815476-22492431-5842-4226-9bb3-39dd3aeeaa6f.png)

### Logs

Error compiling to JavaScript:
LateInitializationError: Field 'version' has not been initialized.

### Flutter Doctor output

NA

**Comment by parlough** [comment] 2023-04-23 13:09
Duplicate of https://github.com/flutter/website/issues/8611

Thanks for taking the time to report the issue! I've prepared a fix in https://github.com/dart-lang/dart-pad/pull/2495.

If you want to run an example in the browser in the meantime, consider copy and pasting code into the full [dartpad.dev](https://dartpad.dev) editor.

**Closed by parlough** 2023-04-23 13:09 UTC
Labels: r: duplicate
