### ISSUE TITLE
AppBar actions - theme not correctly applied

### ISSUE THREAD

**Issue by fhuonder** [flutter/flutter#64942] opened 2020-08-31 08:59 UTC
Hi,

I have a simple app bar with a `TextButton` as action.

```dart
import 'package:flutter/material.dart';

main() => runApp(Example());

class Example extends StatelessWidget {
  @override
  Widget build(BuildContext context) => MaterialApp(
      home: Scaffold(
          appBar: AppBar(
              title: Text("My AppBar"), actions: [IconButton(icon: Icon(Icons.person), onPressed: () {}), TextButton(child: Text("SAVE"), onPressed: () {})])));
}
```
My expectation is that the text SAVE should have the same color as the title but it is invisible.
As I understand it: the color falls back to the default and the default is the primary color. In case of the AppBar the background is in the primary color as well, so the button is not visible.
When the action is an IconButton the color is correctly applied.

My workaround is to apply the following style
```dart
TextButton(child: Text("SAVE", style: Theme.of(context).primaryTextTheme.button), onPressed: () {})]));
```

```
# flutter doctor -v
[√] Flutter (Channel unknown, 1.21.0-1.0.pre, on Microsoft Windows [Version 10.0.19041.450], locale de-CH)
    • Flutter version 1.21.0-1.0.pre at D:\git_repos\prolutions\forks\flutter
    • Framework revision f25bd9c55c (7 weeks ago), 2020-07-14 20:26:01 -0400
    • Engine revision 99c2b3a245
    • Dart version 2.9.0 (build 2.9.0-21.0.dev 20bf2fcf56)


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Android\android-sdk
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = C:\Android\android-sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code, 64-bit edition (version 1.48.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.13.2

[√] Connected device (4 available)
    • Android SDK built for x86 64 (mobile) • emulator-5554 • android-x64    • Android 10 (API 29) (emulator)
    • Web Server (web)                      • web-server    • web-javascript • Flutter Tools
    • Chrome (web)                          • chrome        • web-javascript • Google Chrome 85.0.4183.83
    • Edge (web)                            • edge          • web-javascript • Microsoft Edge 81.0.416.88

• No issues found!
```

Regards,
Florian

**Comment by pedromassangocode** [comment] 2020-08-31 12:09
Hi @fhuonder 
Can you please provide a minimal complete reproducible code sample?
Thank you

**Comment by fhuonder** [comment] 2020-08-31 12:27
> Hi @fhuonder
> Can you please provide a minimal complete reproducible code sample?
> Thank you

Hi @pedromassangocode,
I edited the original question with a working example. The IconButton is shown, the TextButton isn't.

**Comment by pedromassangocode** [comment] 2020-08-31 14:09
I was able to reproduce this on latest `master` and `beta` channels. 

<details>
<summary> flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.22.0-2.0.pre.140, on Mac OS X 10.15.6 19G2021,
    locale en)
    • Flutter version 1.22.0-2.0.pre.140 at
      /Users/pedromassango/dev/SDKs/flutter_master
    • Framework revision 6d1242dd4b (6 hours ago), 2020-08-31 03:53:04 -0400
    • Engine revision 784e6d746e
    • Dart version 2.10.0 (build 2.10.0-76.0.dev)

 
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2020.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 48.1.4
    • Dart plugin version 202.7206

[!] VS Code (version 1.48.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (5 available)
    • Redmi 5 Plus (mobile)       • 0258ff700005  • android-arm64  • Android
      8.1.0 (API 27)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11
      (API 30) (emulator)
    • macOS (desktop)             • macos         • darwin-x64     • Mac OS X
      10.15.6 19G2021
    • Web Server (web)            • web-server    • web-javascript • Flutter
      Tools
    • Chrome (web)                • chrome        • web-javascript • Google
      Chrome 84.0.4147.135

! Doctor found issues in 3 categories.
```
</details>

**Comment by HansMuller** [comment] 2020-10-19 23:03
AppBar does need some improvements so that it aligns better with the theme's [ColorScheme](https://api.flutter.dev/flutter/material/ThemeData/colorScheme.html). However, it really only guarantees to configure the foreground color of IconButtons by default.  It's easy enough to style the foreground of TextButtons by overriding their primary color:

```dart
TextButton(
  style: TextButton.styleFrom(primary: Colors.white),
  onPressed: () { },
  child: Text('TextButton'),
)

TextButton.icon(
  style: TextButton.styleFrom(primary: Colors.white),
  onPressed: () { },
  icon: Icon(Icons.account_circle),
  label: Text('TextButton.icon'),
)
```

I'm going to leave this issue open, since it's reasonable to assume that AppBar would override TextButtonTheme for you. However it should be easy to workaround the issue for now.

**Comment by HansMuller** [comment] 2020-12-02 19:53
I've decided to close this after putting together a PR that significantly updates AppBar: https://github.com/flutter/flutter/pull/71184.

As noted [above](https://github.com/flutter/flutter/issues/64942#issuecomment-712488180), it's easy enough to configure  TextButtons directly or with TextButtonTheme. Having AppBar create a TextButtonTheme automatically would be confusing for developers who created a TextButtonTheme above the AppBar (like as part of the App's theme) and would call into question all of the other component theme's that could be similarly configured.  

Automatically theming TextButtons is a reasonable request, but like many other features that make some situations a little simpler, doing so would also make AppBar just a little harder to understand in other situations.

**Closed by HansMuller** 2020-12-02 19:53 UTC
Labels: f: material design, found in release: 1.21, found in release: 1.22, framework, has reproducible steps
