### ISSUE TITLE
Material 3 Switch `trackOutlineColor`

### ISSUE THREAD

**Issue by buraktabn** [flutter/flutter#120024] opened 2023-02-05 02:28 UTC
**Expected results:** 

Ability to change `Switch`'s outline color from `SwitchThemeData`.

**Actual results:** 

It is not changable and uses colors from color scheme.

https://github.com/flutter/flutter/blob/5187b45e4d1468c13ca9ab1795b300d876fd9453/packages/flutter/lib/src/material/switch.dart#L1805-L1816

<details>
  <summary>flutter doctor</summary>

```
% flutter doctor   
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 3.8.0-4.0.pre, on Pop!_OS 22.04 LTS 6.0.12-76060006-generic, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2021.3)
[✓] IntelliJ IDEA Community Edition (version 2022.3)
[✓] Connected device (1 available)
[✓] HTTP Host Availability
```

</details>

<details>
  <summary>Code Sample</summary>

```dart
import 'package:flutter/material.dart';


void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark(useMaterial3: true).copyWith(
        colorScheme: const ColorScheme.dark().copyWith(outline: Colors.red), 
        scaffoldBackgroundColor: Colors.black,
        switchTheme: SwitchThemeData(
          thumbColor: MaterialStatePropertyAll(Colors.blue.shade800),
          trackColor: MaterialStatePropertyAll(Colors.blue.shade300),
          // trackOutlineColor: MaterialStatePropertyAll(Colors.blue.shade300),
        ),
      ),
      home: const Home(),
    );
  }
}

class Home extends StatefulWidget {
  const Home({Key? key}) : super(key: key);

  @override
  State<Home> createState() => _HomeState();
}

class _HomeState extends State<Home> {
  bool _value = false;
  
  void _toggle() => setState(() => _value = !_value);
  
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Switch(
          onChanged: (_) => _toggle(),
          value: _value,
        ),
      ),
    );
  }
}
```
</details>

**Comment by exaby73** [comment] 2023-02-08 14:26
Hello @buraktabn. Thank you for filing this issue. Can you please provide the following information?

- A [complete and minimal, reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example). Ideally, a single `main.dart` file that can be run directly.

Please provide the information in the form of text. See how to make collapsible sections with Markdown [here](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/organizing-information-with-collapsed-sections).

**Comment by Pszione** [comment] 2023-02-08 15:13
I managed to change the color this way:
`Theme(
          data: Theme.of(context).copyWith(
              colorScheme: Theme.of(context).colorScheme.copyWith(
                    outline: Colors.white,
                  )),
          child: Builder(builder: (context) {
            return Switch(
              value: isLocked,
              onChanged: onChangeLock,
              thumbColor: MaterialStateProperty.all(Colors.white),
            );
          }),
        ),`

**Comment by buraktabn** [comment] 2023-02-08 19:45
@exaby73, I've updated the issue. Basically I'm looking for the field `trackOutlineColor` to be edited in `SwitchThemeData` and if it's not set, we can default to `outline`.

 <hr />
 
 Thanks for the workaround, @Pszione!

**Comment by exaby73** [comment] 2023-02-09 07:02
Looks like `trackOutlineColor` exists in `SwitchThemeData` on the master channel :) Since it's already added, this is an invalid issue. Therefore, I am closing it. Thank you

**Closed by exaby73** 2023-02-09 07:02 UTC
Labels: in triage
