### ISSUE TITLE
Slow frametimes with focused TextField

### ISSUE THREAD

**Issue by JimvanKleef** [flutter/flutter#51933] opened 2020-03-04 14:06 UTC
Internal: b/173532098

## Details

When having a TextField that is currently focused, the frame time goes beyond 16ms regularly, usually between 20 and 50ms.
You can check it when you click "Write your text here" in the example. You don't have to write any Text, it's is just slow all the time.

<details>
<summary>sourcecode main.dart</summary>

```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final focusNode = FocusNode();
  final controller = TextEditingController();
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          // Here we take the value from the MyHomePage object that was created by
          // the App.build method, and use it to set our appbar title.
          title: Text(widget.title),
        ),
        body: Center(
            // Center is a layout widget. It takes a single child and positions it
            // in the middle of the parent.
            child: TextField(
          keyboardAppearance: Brightness.light,
          autocorrect: false,
          enabled: true,
          autofocus: false,
          textCapitalization: TextCapitalization.sentences,
          focusNode: focusNode,
          decoration: const InputDecoration(
              isDense: true,
              filled: false,
              border: InputBorder.none,
              contentPadding: EdgeInsets.only(right: 35),
              hintText: 'Write your text here'),
          controller: controller,
          onChanged: (text) {
            print('changed text to: $text');
          },
          onSubmitted: (text) {
            print('submitted text $text');
          },
        )));
  }
}
```
</details>

**Target Platform:** Android (others not tested)
**Target OS version/browser:** Phone1: Android 8.0.0, Samsung Experience-Version 9.0, Phone 2: Android 9, EMUI-Version 9.1.0
**Devices:** Phone1: Samsung Galaxy S9, Phone2: Honor View 10

I have tried this with both the current stable version v1.12.13+hotfix.8 and the current latest release v1.15.3 (from which I included the traces). As I have included the traces I didn't bother creating a video.

## Logs
[traces acquired with `flutter run --profile --trace-skia`](https://github.com/flutter/flutter/files/4287643/timeline_2020_3_4-1583329470509000.zip)

```
flutter analyze
Analyzing text_field_example...                                         
No issues found! (ran in 1.3s)
```

```
flutter doctor -v
[✓] Flutter (Channel unknown, v1.15.3, on Linux, locale en_US.UTF-8)
    • Flutter version 1.15.3 at /home/jimvankleef/git/flutter
    • Framework revision 67826bdce5 (3 weeks ago), 2020-02-10 14:59:32 -0800
    • Engine revision 6158f03ef5
    • Dart version 2.8.0 (build 2.8.0-dev.8.0 514a8d4c84)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/jimvankleef/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /snap/android-studio/82/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 3.3)
    • Android Studio at /home/jimvankleef/tools/android-studio-ide-182.5199772-linux/android-studio
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] Android Studio (version 3.5)
    • Android Studio at /snap/android-studio/82/android-studio
    • Flutter plugin version 33.4.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Community Edition (version 2019.3)
    • IntelliJ at /snap/intellij-idea-community/208
    • Flutter plugin version 42.1.4
    • Dart plugin version 193.5731

[✓] VS Code (version 1.42.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.8.1

[✓] Connected device (4 available)
    • SM G960F                  • 23a36f8918017ece • android-arm64  • Android 8.0.0 (API 26)
    • Android SDK built for x86 • emulator-5554    • android-x86    • Android 9 (API 28) (emulator)
    • Chrome                    • chrome           • web-javascript • Google Chrome 80.0.3987.122
    • Web Server                • web-server       • web-javascript • Flutter Tools

! Doctor found issues in 1 category.
```

**Comment by TahaTesser** [comment] 2020-07-09 10:18
<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel dev, 1.20.0-3.0.pre, on Mac OS X 10.15.5 19F101, locale
    en-GB)
    • Flutter version 1.20.0-3.0.pre at /Users/taha/Code/flutter_dev
    • Framework revision 0af027f805 (5 days ago), 2020-07-04 12:19:20 -0700
    • Engine revision a751393804
    • Dart version 2.9.0 (build 2.9.0-20.0.dev 22da8934ac)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/taha/Code/sdk
    • Platform android-30, build-tools 30.0.0
    • ANDROID_HOME = /Users/taha/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.1

[✓] Connected device (4 available)
    • SM M305F (mobile)      • 32003c30dc19668f          • android-arm64  •
      Android 10 (API 29)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios            • iOS
      13.5.1
    • Web Server (web)       • web-server                • web-javascript •
      Flutter Tools
    • Chrome (web)           • chrome                    • web-javascript •
      Google Chrome 83.0.4103.116

• No issues found!
``` 

</details>

**Comment by andrefedev** [comment] 2020-07-25 00:42
@TahaTesser This has been fixed in development versions?

**Comment by Hixie** [comment] 2020-11-18 00:01
Removed 'material' label since this is probably a core framework issue.

**Comment by dnfield** [comment] 2020-11-18 00:50
Caret animation is a likely culprit. It'd be worth checking if this goes away if the caret animation is disabled

**Comment by dnfield** [comment] 2020-11-18 01:01
I tried a quick repro with and without the cursor - I'm seeing frames staying more consistently under budget without the animating cursor. That said, I'm also not seeing many frames go over budget with the cursor on a Pixel 4.

**Comment by Hixie** [comment] 2020-12-15 23:35
This almost certainly depends on how much is being repainted. If the repaint boundary that contains the cursor involves clips and opacity and blurs and so on, it'll be a different story than if the repaint boundary is otherwise empty.

**Comment by Hixie** [comment] 2021-01-06 00:06
Update from @goderbauer: We will look at it this week.

**Comment by goderbauer** [comment] 2021-01-12 00:08
I tried this on a Samsung S8 and Pixel 4. I was unable to reproduce this on either of these devices. The trace produced on those devices looks reasonable for the cursor tick.

What I noticed in @JimvanKleef's trace is that the work items are spending a lot of time waiting for the CPU (wall duration for many items is much larger than CPU duration). I wonder, if there's something else hogging the CPU or if something like GC is a problem here?  @JimvanKleef  Any chance you can provide a trace of your example app on the device on question with all "recording streams" checked, to get us a little more information of what's going on:

![Screen Shot 2021-01-11 at 4 06 38 PM](https://user-images.githubusercontent.com/1227763/104252478-063c3980-5427-11eb-8788-0f93c75ea9b8.png)

I've also asked "customer: money" for more information on how to reproduce the problem on their end.

**Comment by andrefedev** [comment] 2021-01-12 00:28
@goderbauer You can also reproduce the same problem with a Galaxy A30.

**Comment by goderbauer** [comment] 2021-01-12 21:18
@LongCatIsLooong Is https://github.com/flutter/flutter/pull/72828 targeting the performance issues raised in this bug?

**Comment by goderbauer** [comment] 2021-01-12 21:38
Can somebody with a device that shows the performance problem check whether #72828 makes a difference for the code given in https://github.com/flutter/flutter/issues/51933#issue-575428518 and report back?

**Comment by goderbauer** [comment] 2021-01-14 18:53
I just got my hands on a Moto G4 and it also doesn't reproduce the problem. All frames of the blinking cursor are well within their budget, the worst Raster time I am seeing is 12.2ms/frame and the worst UI time I am seeing is 1.7ms/frame.

**Comment by goderbauer** [comment] 2021-01-14 19:09
FWIW, I also just tested this with Flutter v1.15.3 (the version this was reported on) and it also has the same perf characteristics where everything stays in budget.

**Comment by goderbauer** [comment] 2021-01-14 19:32
Wondering whether this is specific to a certain GPU. Looks like all devices this has been reported ship - at least in some regions - with a Mali-G71 or Mali-G72 GPU. I am trying to get my hands on a device with such a chip.

**Comment by dnfield** [comment] 2021-01-14 19:38
I've only been able to test with Adreno based devices. Testing with a Mali based GPU seems like a good way to go.

**Comment by goderbauer** [comment] 2021-01-20 21:09
I tried this on a Honor 9 with a "Mali-G71 MP8" GPU. In the timeline view, all frames of the blinking cursor are under budget and come in at about 12 to 14ms. However, when the performance overlay is turned on, frame times jump to 23ms. Seems like the overhead of the performance overlay is pretty high.

Looks like the trace posted in the first message of this bug was recorded without the performance overlay, though, and still showed high frame times...

**Comment by goderbauer** [comment] 2021-01-20 21:41
(On the Moto G4 the cost of the performance overlay is smaller: 8.5ms vs 12ms)

**Comment by goderbauer** [comment] 2021-01-25 18:29
b/173532098 reported that they can no longer reproduce this. Reducing priority of this bug.

**Comment by goderbauer** [comment] 2021-01-25 18:52
On second thought: I am going to close this issue for now since we don't have a way to reproduce it. If you experience this issue, feel free to ping this bug with your device model and make (ideally including the GPU of the device) and a timeline trace that showcases the issue.

**Closed by goderbauer** 2021-01-25 18:52 UTC
Labels: P4, a: animation, a: text input, customer: money (g3), found in release: 1.20, framework, has reproducible steps, perf: speed, severe: performance, waiting for customer response
