### ISSUE TITLE
[firebase_messaging] iOS Archive build fails

### ISSUE THREAD

**Issue by moo7md** [flutter/flutter#74292] opened 2021-01-20 03:18 UTC
Recently, I'm encountering this error while trying to build my iOS version in Xcode. The build logs complain about the firebase messaging package and I can't just figure out why it's happening. 
Here are the error messages I get:

```
#if defined(__IPHONE_10_0) && __IPHONE_OS_VERSION_MAX_ALLOWED >= __IPHONE_10_0
// Received data message on iOS 10 devices while app is in the foreground.
// Only invoked if method swizzling is enabled.
- (void)applicationReceivedRemoteMessage:(FIRMessagingRemoteMessage *)remoteMessage { //Error: Expected a type
  [self didReceiveRemoteNotification:remoteMessage.appData]; //Error: Property 'appData' not found on object of type '__strong id'
}
```

```
 else if ([@"configure" isEqualToString:method]) {
    [FIRMessaging messaging].shouldEstablishDirectChannel = true; //Error: Property 'shouldEstablishDirectChannel' not found on object of type 'FIRMessaging *'
    [[UIApplication sharedApplication] registerForRemoteNotifications];
    if (_launchNotification != nil && _launchNotification[kGCMMessageIDKey]) {
      [_channel invokeMethod:@"onLaunch" arguments:_launchNotification];
    }
    result(nil);
  }
```
**Errors:**
```
FLTFirebaseMessagingPlugin.m:196:52: error: property 'appData' not found on object of type '__strong id'
      [self didReceiveRemoteNotification:remoteMessage.appData];

error: nullability specifier 'nonnull' conflicts with existing specifier 'nullable'
        didReceiveRegistrationToken:(nonnull NSString *)fcmToken {

error: property 'shouldEstablishDirectChannel' not found on object of type 'FIRMessaging *'
        [FIRMessaging messaging].shouldEstablishDirectChannel = true;

```
`flutter analyze`

```
Analyzing ios...                                                        
No issues found! (ran in 2.0s)
```
`flutter doctor -v`
````
[✓] Flutter (Channel master, 1.26.0-2.0.pre.401, on macOS 11.1 20C69 darwin-x64, locale en-US)
    • Flutter version 1.26.0-2.0.pre.401 at /Users/moo7md/flutter/flutter
    • Framework revision da5a454d5c (3 days ago), 2021-01-17 01:24:03 -0500
    • Engine revision 609036f2bf
    • Dart version 2.12.0 (build 2.12.0-236.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/moo7md/Library/Android/sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2018.2.5)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 88.0.4324.96

• No issues found!
```

**Comment by moo7md** [comment] 2021-01-20 03:23
Also this is my pubspec.yaml file:
```
  firebase_core: ^0.7.0

  # Add the dependency for the FlutterFire plugin for Google Analytics
  firebase_analytics: ^7.0.1

  # Add the dependencies for any other Firebase products you want to use in your app
  # For example, to use Firebase Authentication and Cloud Firestore
  firebase_auth: ^0.20.0+1
  cloud_firestore: ^0.16.0
  firebase_storage: ^7.0.0
  firebase_messaging: ^6.0.9
  cloud_functions: ^0.9.0
  #firebase_admob api
  firebase_admob: ^0.11.0+1
  #firebase_dynamic_links api
  firebase_dynamic_links: ^0.7.0+1

  #flutter_twitter_login api
  flutter_twitter_login: ^1.1.0

  #flutter_facebook_login api
  flutter_facebook_login: ^3.0.0

  #cached_network_image api
  cached_network_image: ^2.5.0

  #fluttertoast api
  fluttertoast: ^7.1.6

  #firebase_in_app_messaging api
  firebase_in_app_messaging: ^0.3.0+1
```

**Comment by TahaTesser** [comment] 2021-01-20 07:22
Hi @moo7md 
From what I can see, the issue is related to a FlutterFire plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-01-20 07:22 UTC
