### ISSUE TITLE
Firebase cloud messaging - all notifications at once

### ISSUE THREAD

**Issue by sergitovar91** [flutter/flutter#60865] opened 2020-07-05 16:31 UTC
Hi ! I would need your help. I have an application mobile (android and iOS) with flutter and firebase cloud messaging.

My case: I receive 4 notifications on the device (as an example) and I want to read all of them when I click in the application’s icon. Currently I have to click each notification to read it and be able to create the widgets

How can I do it ?

For both Android and iOS ! Thanks !!!

**Comment by iapicca** [comment] 2020-07-06 06:28
Hi @sergitovar91 
From what I can see, the issue is related to a FlutterFire plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by iapicca** 2020-07-06 06:28 UTC
