### ISSUE TITLE
iOS Flutter 2.10.1 Crash EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000000000010

### ISSUE THREAD

**Issue by Wian-TMC** [flutter/flutter#100545] opened 2022-03-22 09:53 UTC
## Steps to Reproduce

This crash seems to be random when the app is in the foreground and was supposedly fixed in flutter version 2.10.1, but here it seems to still occur even when using Flutter version 2.10.1

<details>
  <summary>Logs</summary>

```
Crashed: com.apple.main-thread
0  libobjc.A.dylib                0x1540 objc_msgSend + 32
1  Flutter                        0x50d684 (Missing UUID 5e7cb7aa584b3ca8ba93141161ceba72)
2  Flutter                        0x419fc (Missing UUID 5e7cb7aa584b3ca8ba93141161ceba72)
3  Flutter                        0x3d39b8 (Missing UUID 5e7cb7aa584b3ca8ba93141161ceba72)
4  Flutter                        0x2fb904 (Missing UUID 5e7cb7aa584b3ca8ba93141161ceba72)
5  Flutter                        0x2feed0 (Missing UUID 5e7cb7aa584b3ca8ba93141161ceba72)
6  CoreFoundation                 0xae318 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 32
7  CoreFoundation                 0x32cf0 __CFRunLoopDoTimer + 1076
8  CoreFoundation                 0x2d4ec __CFRunLoopDoTimers + 328
9  CoreFoundation                 0xbd08 __CFRunLoopRun + 1944
10 CoreFoundation                 0x1f468 CFRunLoopRunSpecific + 600
11 GraphicsServices               0x138c GSEventRunModal + 164
12 UIKitCore                      0x5195d0 -[UIApplication _run] + 1100
13 UIKitCore                      0x297f74 UIApplicationMain + 364
14 Runner                         0x4bd4 main + 6 (AppDelegate.swift:6)
15 ???                            0x101625aa4 (Missing)
```

```
[✓] Flutter (Channel stable, 2.10.1, on macOS 11.6.2 20G314 darwin-x64, locale en-ZA)
    • Flutter version 2.10.1 at /Users/wiansnyman/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db747aa133 (6 weeks ago), 2022-02-09 13:57:35 -0600
    • Engine revision ab46186b24
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/wiansnyman/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/wiansnyman/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.65.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.36.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 99.0.4844.83

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by Wian-TMC** [comment] 2022-03-23 07:08
Hi @maheshmnj, browsing through #98481, it still seems to occur on `stable 2.10.3`. I am not able to reproduce the crash on an emulator and I have no iOS device myself, but our testers have iOS devices which seem to crash relatively often (once or twice a day).

**Comment by maheshmnj** [comment] 2022-03-23 10:50
Thanks for the info @Wian-TMC, I am closing this issue as duplicate of #98481. Please follow up there for further updates. Incase you disagree feel free to write in the comments and we will reopen it.

Thank you.

**Closed by maheshmnj** 2022-03-23 10:50 UTC
Labels: in triage
