### ISSUE TITLE
LateInitializationError in _NativeSocket for windows

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#57125] opened 2020-05-13 16:00 UTC
Happened on a test run: https://cirrus-ci.com/task/5414957229539328?command=main#LNaN-L183

```
01:34 +26: test\commands.shard\permeable\create_test.dart: can create a default project                                                                                                                Expected: empty
  Actual: 'Unhandled exception:\n'
            'LateInitializationError: localAddress\n'
            '#0      _NativeSocket.localAddress (dart:io-patch/socket_patch.dart:443:24)\n'
            '#1      _NativeSocket.address (dart:io-patch/socket_patch.dart:1018:34)\n'
            '#2      _NativeSocket.reportError (dart:io-patch/socket_patch.dart:1304:41)\n'
            '#3      _NativeSocket.multiplex (dart:io-patch/socket_patch.dart:1146:13)\n'
            '#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)\n'
            ''
#0      fail (package:test_api/src/frontend/expect.dart:154:30)
#1      _expect (package:test_api/src/frontend/expect.dart:148:3)
#2      expect (package:test_api/src/frontend/expect.dart:60:3)
#3      assertContains (file:///C:/Windows/Temp/flutter%20sdk/packages/flutter_tools/test/commands.shard/permeable/analyze_once_test.dart:362:5)
#4      main.runCommand (file:///C:/Windows/Temp/flutter%20sdk/packages/flutter_tools/test/commands.shard/permeable/analyze_once_test.dart:58:5)
<asynchronous suspension>
#5      main.runCommand (file:///C:/Windows/Temp/flutter%20sdk/packages/flutter_tools/test/commands.shard/permeable/analyze_once_test.dart)
#6      main.<anonymous closure> (file:///C:/Windows/Temp/flutter%20sdk/packages/flutter_tools/test/commands.shard/permeable/analyze_once_test.dart:315:23)
#7      testUsingContext.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///C:/Windows/Temp/flutter%20sdk/packages/flutter_tools/test/src/context.dart:152:42)
#8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#9      _rootRun (dart:async/zone.dart:1190:13)
#10     _CustomZone.run (dart:async/zone.dart:1093:19)
#11     _runZoned (dart:async/zone.dart:1630:10)
#12     runZoned (dart:async/zone.dart:1550:10)
#13     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#14     testUsingContext.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///C:/Windows/Temp/flutter%20sdk/packages/flutter_tools/test/src/context.dart:141:30)
```

**Comment by jonahwilliams** [comment] 2020-05-13 16:06
FYI @zichangg

**Comment by jonahwilliams** [comment] 2020-05-13 17:02
Might affect  users of the tool on windows, marking TODAY

**Comment by jonahwilliams** [comment] 2020-05-13 17:02
See also: https://cirrus-ci.com/task/4679244297011200

**Comment by sortie** [comment] 2020-05-13 17:55
OK, taking a look.

**Comment by sortie** [comment] 2020-05-13 18:00
I'm not familiar with your CI. Can you link to the source code of the test in question that fails and ideally the line? Looking at the dart:io internals right now and trying to find the relevant code path that can fail to initialize the variable.

**Comment by jonahwilliams** [comment] 2020-05-13 18:24
The line where the exception is caught is https://github.com/flutter/flutter/blob/master/packages/flutter_tools/test/commands.shard/permeable/analyze_once_test.dart#L315

unfortunately this is an integration test, its not directly manipulating an HTTP client at all.

**Comment by sortie** [comment] 2020-05-13 18:39
Thanks Jonah. Based on that and reading the source code, my initial assessment is that it seems that when the process pipe code attempts to raise an error, it tries to add the local socket address, but that field was never initialized for non-socket pipes. Previously it would raise a socket exception with a null address.

I'll reproduce the issue and redesign the code so this class of issues becomes impossible. I suspect it might also happen for other non-socket sockets like stdio and perhaps signal handlers / filesystem watch channels. I'm out of time today so I'll continue work tomorrow as a top priority.

**Comment by jonahwilliams** [comment] 2020-05-13 18:51
Thanks @sortie !

**Comment by zichangg** [comment] 2020-05-13 20:50
@jonahwilliams I just created a hot fix to stop the breakage. https://dart-review.googlesource.com/c/sdk/+/148003

This piece of code probably needs a small redesign to completely solve the problem.

**Comment by sortie** [comment] 2020-05-14 08:54
I have a reproduction:

```dart
import 'dart:io';

Future<void> main() async {
  final process = await Process.start("false", []);
  process.stdout.drain();
  process.stderr.drain();
  bool finished = false;
  process.stdin.done.catchError((e) {
    finished = true;
  }, test: (e) => e is SocketException);
  while (!finished) {
    process.stdin.write("a");
    await Future.delayed(new Duration(microseconds: 1));
  }
  await process.exitCode;
}
```

The test succeeds on Dart 2.8.1 but fails similarly on the unforked dart:

```
$ out/ReleaseX64/dart-sdk/bin/dart flutter_57125_regress.dart
Unhandled exception:
LateInitializationError: localAddress
#0      _NativeSocket.localAddress (dart:io-patch/socket_patch.dart:443:24)
#1      _NativeSocket.address (dart:io-patch/socket_patch.dart:1018:34)
#2      _NativeSocket.reportError (dart:io-patch/socket_patch.dart:1304:41)
#3      _NativeSocket.write.<anonymous closure> (dart:io-patch/socket_patch.dart:945:31)
#4      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#5      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#6      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#7      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:404:11)
#8      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:428:5)
#9      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

**Comment by sortie** [comment] 2020-05-14 10:43
I have a fix with a test up for review at https://dart-review.googlesource.com/c/sdk/+/148063

**Comment by sortie** [comment] 2020-05-14 12:44
The fix for the unfork issue in dart:io has landed in the Dart SDK in 2676764792b2170b5f7867600a2144e7493fa950.

This issue can be closed once it has rolled into Flutter and the fix is confirmed.

cc @franklinyow @mit-mit

**Comment by renyou** [comment] 2020-05-19 23:19
@sortie Any updates on this one??

**Comment by sortie** [comment] 2020-05-20 09:28
The SDK fix landed 6 days ago in https://github.com/dart-lang/sdk/commit/2676764792b2170b5f7867600a2144e7493fa950. The issue should be fixed when it rolls into Flutter.

I am not on the Flutter team however. I don't know Flutter's infrastructure and don't know how to check if these issues have disappeared. Can somebody who knows Flutter's infrastructure verify the issue is gone now and close this issue?

**Comment by zanderso** [comment] 2020-05-20 16:26
It looks like the Dart SDK change has rolled into flutter/flutter master. Presuming fixed.

**Closed by zanderso** 2020-05-20 16:26 UTC
Labels: dependency: dart, team: flakes, unfork, ⚠ TODAY
