### ISSUE TITLE
Unresolved reference: FlutterActivity 

### ISSUE THREAD

**Issue by mehtahardikr** [flutter/flutter#63951] opened 2020-08-17 12:26 UTC
![Screen Shot 2020-08-17 at 5 54 14 PM](https://user-images.githubusercontent.com/12496655/90395837-ce68da00-e0b2-11ea-84d3-8b9b0c04b5e0.png)

getting `Unresolved reference: FlutterActivity ` inside `MainActivity.kt` file

Please help me to resolved this.

**Comment by Abhishek01039** [comment] 2020-08-17 14:50
Hi @mehtahardikr 
please refer this https://flutter.dev/docs/development/platform-integration/platform-channels
Thanks

**Comment by mehtahardikr** [comment] 2020-08-18 06:24
@Abhishek01039 : so , you mean to say that it will work when i open android module as stand alone project in android studio ?
as per error , its not able to find `embedding class` inside `io.flutter` package

**Comment by pedromassangocode** [comment] 2020-08-18 10:27
Hi @mehtahardikr 
From what I can see, the issue is related to Flutter itself. When working in the Android module it is recommended to open it as a stand alone project using an IDE with Android plugin installed (Android Studio/IntelliJ IDEA) so that the IDE can find the reference of the classes in your Android module. The same happens with iOS projects you may want to open it using Xcode to get code completion and other features.

Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by pedromassangocode** 2020-08-18 10:27 UTC

**Comment by mehtahardikr** [comment] 2020-08-18 13:06
hello @pedromassangocode  :
Here is the content  of file  `pubspec.yaml`

```
name: flutter_app
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:


  uses-material-design: true
```

```
flutter doctor -v
[✓] Flutter (Channel stable, 1.20.2, on Mac OS X 10.13.6 17G65, locale en-IN)
    • Flutter version 1.20.2 at /Users/VishakhaP/flutter
    • Framework revision bbfbf1770c (5 days ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/VishakhaP/Library/Android/sdk
    • Platform android-30, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ! CocoaPods 1.6.1 out of date (1.8.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade:
        sudo gem install cocoapods

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • SM G615FU (mobile) • 42007d3b9a168429 • android-arm • Android 8.1.0 (API 27)

! Doctor found issues in 1 category.

```
```
flutter run -v
[ +422 ms] executing: [/Users/user1/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +219 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] bbfbf1770cca2da7c82e887e4e4af910034800b6
[        ] executing: [/Users/user1/flutter/] git tag --contains HEAD
[+1293 ms] Exit code 0 from: git tag --contains HEAD
[        ] 1.20.2
[  +25 ms] executing: [/Users/user1/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +12 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] origin/stable
[        ] executing: [/Users/user1/flutter/] git ls-remote --get-url origin
[  +12 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +139 ms] executing: [/Users/user1/flutter/] git rev-parse --abbrev-ref HEAD
[  +19 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +3 ms] stable
[  +45 ms] executing: sw_vers -productName
[ +146 ms] Exit code 0 from: sw_vers -productName
[        ] Mac OS X
[        ] executing: sw_vers -productVersion
[  +12 ms] Exit code 0 from: sw_vers -productVersion
[        ] 10.13.6
[        ] executing: sw_vers -buildVersion
[  +16 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 17G65
[ +135 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[  +11 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +92 ms] executing: /Users/user1/Library/Android/sdk/platform-tools/adb devices -l
[   +8 ms] executing: /usr/bin/xcode-select --print-path
[  +27 ms] Exit code 0 from: /usr/bin/xcode-select --print-path
[        ] /Library/Developer/CommandLineTools
[   +1 ms] executing: /usr/bin/xcodebuild -version
[   +5 ms] Exit code 1 from: /usr/bin/xcodebuild -version
[        ] xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance
[        ] Xcode not found. Run 'flutter doctor' for more information.
[   +2 ms] executing: /usr/bin/xcodebuild -version
[   +5 ms] Exit code 1 from: /usr/bin/xcodebuild -version
[        ] xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance
[  +52 ms] List of devices attached
           42007d3b9a168429       device usb:342884352X product:j7maxltedd model:SM_G615FU device:j7maxlte transport_id:5
[  +11 ms] /Users/user1/Library/Android/sdk/platform-tools/adb -s 42007d3b9a168429 shell getprop
[ +107 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +4 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +10 ms] executing: /usr/bin/xcodebuild -version
[   +5 ms] Exit code 1 from: /usr/bin/xcodebuild -version
[        ] xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance
[ +275 ms] Found plugin path_provider_linux at /Users/user1/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_linux-0.0.1+2/
[  +55 ms] Found plugin shared_preferences at /Users/user1/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences-0.5.8/
[  +13 ms] Found plugin shared_preferences_linux at /Users/user1/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_linux-0.0.2+1/
[   +2 ms] Found plugin shared_preferences_macos at /Users/user1/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_macos-0.0.1+10/
[  +19 ms] Found plugin shared_preferences_web at /Users/user1/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_web-0.1.2+7/
[ +196 ms] Found plugin path_provider_linux at /Users/user1/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_linux-0.0.1+2/
[   +8 ms] Found plugin shared_preferences at /Users/user1/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences-0.5.8/
[   +2 ms] Found plugin shared_preferences_linux at /Users/user1/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_linux-0.0.2+1/
[   +1 ms] Found plugin shared_preferences_macos at /Users/user1/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_macos-0.0.1+10/
[   +3 ms] Found plugin shared_preferences_web at /Users/user1/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_web-0.1.2+7/
[ +131 ms] Generating /Users/user1/StudioProjects/flutterprojects/flutter_app/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +37 ms] executing: /usr/bin/xcodebuild -version
[   +9 ms] Exit code 1 from: /usr/bin/xcodebuild -version
[   +1 ms] xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance
[  +12 ms] ro.hardware = mt6757
[        ] ro.build.characteristics = default
[ +127 ms] Starting incremental build...
[  +17 ms] Initializing file store
[  +12 ms] Skipping target: gen_localizations
[   +8 ms] complete
[   +7 ms] Launching lib/main.dart on SM G615FU in debug mode...
```

**Comment by pedromassangocode** [comment] 2020-08-19 06:27
Hi @mehtahardikr as I mentioned before if you believe this is a Flutter issue you need to provide a minimal reproducible code sample that does not use 3rd party plugins too.
Thank you

**Comment by mehtahardikr** [comment] 2020-08-19 06:50
@pedromassangocode : there is no 3rd party plugins as you see `pubspec.yaml file`.

**Comment by pedromassangocode** [comment] 2020-08-19 07:34
Hi @mehtahardikr 
I need you to provide a code that reproduces the issue you're facing so that I can verify the issue on my side.
Thank you

**Comment by mehtahardikr** [comment] 2020-08-19 09:00
Hi @pedromassangocode : i have just created new `kotlin` application through `android studio ide` and selected kotlin codebase for android platform and the flutter sdk is latest one that is `flutter_macos_1.20.2-stable` and nothing was added to code as i have created new project.

**Comment by pedromassangocode** [comment] 2020-08-19 12:11
Hi @mehtahardikr 
As I said I recommend you to open the Android module with Android Studio and the error may disappear. This clearly does not seems to be a Flutter issue.
Thank you

**Comment by mehtahardikr** [comment] 2020-08-19 12:40
hi @pedromassangocode  : yup its works fine when open `android module` with `Android studio` 
Thanks for your help.

**Comment by Lorenzo-Garcia** [comment] 2021-05-04 01:16
Hola! Tengo el mismo problema pero para Visual Code... Cree un proyecto kotlin desde el terminal (en flutter obvio), la carpeta esta alojada en el mismo directorio que los otros proyectos, abrí el proyecto desde la carpeta Android.. Y bueno no me reconoce nada del codigo: 
package com.example.battery

import io.flutter.embedding.android.FlutterActivity

import io.flutter.plugin.common.MethodChannel
import android.os.Bundle
import io.flutter.app.FlutterActivity

class MainActivity: FlutterActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        GeneratedPluginRegistrant.registerWith(this)
    }
}
---------------------------------------------------- PROBLEMAS ---------------------
Unresolved reference: io
Unresolved reference: io
Unresolved reference: FlutterActivity
'onCreate' overrides nothing
Unresolved reference: onCreate
Unresolved reference: GeneratedPluginRegistrant

**Comment by Lorenzo-Garcia** [comment] 2021-05-04 01:22
Ejecuto flutter doctor y recibo el siguiente error al intentar aceptar las licencias:
Windows PowerShell
Copyright (C) 2009 Microsoft Corporation. Reservados todos los derechos.

PS C:\MyappProyecto\battery\android> flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.0.4, on Microsoft Windows [VersiÃ³n 6.1.7601], locale es-AR)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[√] Chrome - develop for the web
[!] Android Studio (version 4.1.0)
    X Unable to determine bundled Java version.
[√] VS Code (version 1.55.2)
[√] Connected device (1 available)


PS C:\MyappProyecto\battery\android> flutter doctor --android-licenses
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
        at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
        at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
        at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 5 more
PS C:\MyappProyecto\battery\android>
