### ISSUE TITLE
Hot restart doesn't work for web app

### ISSUE THREAD

**Issue by jmewes** [flutter/flutter#82555] opened 2021-05-14 18:06 UTC
## Observed result

I wanted to change something in a web app, and to test the change wanted to do a hot reload. However, the hot reload didn't finish even after waiting for 15 minutes. It just hangs.

In the following, there is a description of the observed result for a [minimal app which can reproduce the problem](https://github.com/jmewes/flutter_hot_restart).

### Current stable branch

On the current stable branch, just nothing happens after the hot reload was requested after changing some text in a widget.

See this screen recording for details:

https://youtu.be/_aP5XPnoryk

### Current master branch

On the current master branch the hot reload not only hangs but actually crashes the application.

See this screen recording for details:

https://youtu.be/-FOnzYMxB9w

## Expected result

The hot restart should have been executed within a few milliseconds, displaying the new text on the screen.

## Steps to Reproduce

1. Start demo app with Chrome

```
git clone https://github.com/jmewes/flutter_hot_restart.git
cd flutter_hot_restart
flutter run --verbose -d chrome lib/main.dart
```

(see https://github.com/jmewes/flutter_hot_restart )

Then wait for the browser to open the app

2. Edit the text in the `Foo` widget

In the file `lib/util/form_stepper/src/form_stepper.dart` there is a widget called `Foo` which contains a `Text` widget with some text.

e.g. in another terminal tab, like this:

```
sed -i 's/continue/discontinue/g' lib/util/form_stepper/src/form_stepper.dart
```

3. Request hot reload

Go back to the terminal where the app is running, and press the "r" key to request the hot reload.

### macOS

```
$ uname -a
Darwin macbook-jm 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64 i386 MacBookPro11,4 Darwin
```

### Hint for problem cause

It is important for the widget being pulled in from the nested file structure. If the widget is coming from the same file, the hot restart works like expected.

### Log file

Here is the log file which was reported after the crash on the `master` branch:

[flutter_02.log](https://github.com/flutter/flutter/files/6480297/flutter_02.log)

### Console output

Here is the verbose console output from the test on the current master branch:

```
flutter run --verbose -d chrome lib/main.dart > /tmp/master.log 2>&1
```

[master.log](https://github.com/flutter/flutter/files/6480330/master.log)

### flutter analyze

```
$ flutter analyze
Analyzing flutter_hot_restart...
No issues found! (ran in 1.9s)
```

### flutter doctor

<details>
  <summary>flutter doctor -v</summary>

```
$ flutter doctor -v
[✓] Flutter (Channel master, 2.3.0-2.0.pre.207, on macOS 11.2.3 20D91 darwin-x64, locale de-DE)
    • Flutter version 2.3.0-2.0.pre.207 at /Users/jmewes/src/misc/flutter
    • Upstream repository git@github.com:flutter/flutter.git
    • Framework revision 5bc348904e (59 minutes ago), 2021-05-14 09:38:50 -0700
    • Engine revision c75ec8ea4d
    • Dart version 2.14.0 (build 2.14.0-115.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/jmewes/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Users/jmewes/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.6858069/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Users/jmewes/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.6858069/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Android Studio (version 4.1)
    • Android Studio at /Users/jmewes/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.6858069/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2020.3.3)
    • IntelliJ at /Users/jmewes/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/203.7717.56/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Community Edition (version 2020.1.2)
    • IntelliJ at /Users/jmewes/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/201.7846.76/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.54.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.2.3 20D91 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 90.0.4430.212

! Doctor found issues in 1 category.
```

</details>

**Comment by jmewes** [comment] 2021-05-14 18:21
With the steps described above I could reproduce the issue on Ubuntu, too.

```
$ flutter --version
Flutter 2.0.6 • channel stable • git@github.com:flutter/flutter.git
Framework • revision 1d9032c7e1 (vor 2 Wochen) • 2021-04-29 17:37:58 -0700
Engine • revision 05e680e202
Tools • Dart 2.12.3
$ uname -a
Linux laptop-jm 5.8.0-53-generic #60~20.04.1-Ubuntu SMP Thu May 6 09:52:46 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by darshankawar** [comment] 2021-05-17 08:48
Thanks for the detailed report and code sample @jmewes.
I was able to replicate the issue on latest stable, as below using both renderers:

<img width="862" alt="Screenshot 2021-05-17 at 2 00 36 PM" src="https://user-images.githubusercontent.com/67046386/118459920-d6c17480-b719-11eb-9c1b-b87291de397f.png">

<details>
<summary> stable flutter doctor -v </summary>

```
[✓] Flutter (Channel stable, 2.0.6, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.0.6 at /Users/dhs/documents/fluttersdk/flutter
    • Framework revision 1d9032c7e1 (2 weeks ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (3 available)
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 90.0.4430.212

! Doctor found issues in 1 category.



```

</details>

With latest master though, (2.3.0-2.0.pre.240), I was able to hot reload properly without any issues, as below:


https://user-images.githubusercontent.com/67046386/118460302-315ad080-b71a-11eb-9a6a-486acdffbb05.mov

<details>
<summary> code sample </summary>

```
[✓] Flutter (Channel master, 2.3.0-2.0.pre.240, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-GB)
    • Flutter version 2.3.0-2.0.pre.240 at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e364e30c90 (6 hours ago), 2021-05-16 19:40:00 -0700
    • Engine revision 193be59942
    • Dart version 2.14.0 (build
      2.14.0-edge.a527411e5100a0a4f48c4009087a1b988aa784af)

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (3 available)
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 90.0.4430.212

! Doctor found issues in 1 category.



```

</details>

You may try on latest master and see if you still see the crash after hot reload. Meantime, labeling it based on stable version's behavior.

**Comment by darshankawar** [comment] 2021-05-17 08:50
There was similar issue reported with similar behavior which we were unable to replicate and then got closed due to timeout / inactivity from author, https://github.com/flutter/flutter/issues/78570

**Comment by jmewes** [comment] 2021-05-17 10:03
I can confirm that hot restart with the demo app works for me on macOS and Flutter version "Flutter (Channel master, 2.3.0-2.0.pre.241"

**Comment by jonahwilliams** [comment] 2021-05-17 23:29
The crash on master looks related to change to avoid writing content length headers on 304 content not modified responses.

**Comment by jonahwilliams** [comment] 2021-05-17 23:30
uhhh, maybe @natebosch for shelf . Is this something we should be working around in the tool or do we need a shelf roll?

**Comment by natebosch** [comment] 2021-05-17 23:44
> The crash on master looks related to change to avoid writing content length headers on 304 content not modified responses.

We did intentionally stop sending content length headers for not modified responses. Can you elaborate on the crash this is causing and which version you are on?

https://github.com/dart-lang/shelf/pull/183

Versions of `shelf` before `1.1.2` would have sent a content length of `0` for these responses. Versions `1.1.2` leaves the header as is which causes a problem if you had set it to anything _other_ than `0` because the Dart SDK throws an error. Version `1.1.3` and above remove the header entirely which is the correct thing to do most often.

**Comment by jonahwilliams** [comment] 2021-05-17 23:46
The error message is:

```

HttpException: HttpException: Content size below specified contentLength.  0 bytes written but expected 1225., uri = /main_module.bootstrap.js

```
```

## flutter doctor

```
[✓] Flutter (Channel master, 2.3.0-2.0.pre.207, on macOS 11.2.3 20D91 darwin-x64, locale de-DE)
    • Flutter version 2.3.0-2.0.pre.207 at /Users/jmewes/src/misc/flutter
```

Which sounds like what we would get with an old version of shelf. i'll double check the last version update

**Comment by jonahwilliams** [comment] 2021-05-17 23:48
yeah we're setting the response length ourselves, I'll have to fix that

**Comment by natebosch** [comment] 2021-05-17 23:55
I suspect upgrading to version `1.1.3` or newer will solve this for you - that error looks like the bug I was fixing by removing the content length header entirely.

**Comment by jonahwilliams** [comment] 2021-05-18 00:01
it looks like we're on 1.1.4 now so we should be good

**Comment by jmewes** [comment] 2021-05-21 05:05
> @darshankawar can you check it works on beta? A bisect would be great to know if something needs hotfixing.
> 

@jmagman ,

The hot restart works for the [flutter_hot_restart](https://github.com/jmewes/flutter_hot_restart) project on the current "beta" channel.

<details>
  <summary>flutter doctor -v</summary>

```
$ flutter doctor -v
[✓] Flutter (Channel beta, 2.2.0, on macOS 11.3.1 20E241 darwin-x64, locale de-DE)
    • Flutter version 2.2.0 at /Users/jmewes/fvm/versions/beta
    • Framework revision b22742018b (6 days ago), 2021-05-14 19:12:57 -0700
    • Engine revision a9d88a4d18
    • Dart version 2.13.0

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/jmewes/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Users/jmewes/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.6858069/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Users/jmewes/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.6858069/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.56.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.3.1 20E241 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 90.0.4430.212

! Doctor found issues in 1 category.
```

</details>

**Comment by bambinoua** [comment] 2021-05-25 06:22
I confirmed this issue. On one of my web app hot restart is not working. I am in beta channel but the proble is in stable channel too.
When I changed something in the code `Save` I see in VS Code debug console `Restarted application in 490ms`, in Chrome console `3 module(s) were hot-reloaded` but the page was not refreshed (just a blank page). Whan I refresh browser in console I see `Loading from service worker` and the the page is refreshed.

**Comment by bambinoua** [comment] 2021-05-25 11:44
@jmewes, I tested your `flutter_hot_restart` and it works for me. :( But my project is not hot restarted anymore.
Any newly created app is working. Weird thing.

**Comment by bambinoua** [comment] 2021-05-25 12:18
I also noticed some differences in network log of Chrome.
1. Network log of default flutter app.
![f_app_1](https://user-images.githubusercontent.com/45417992/119496356-17e60400-bd6c-11eb-840d-256da71fb930.jpg)

2. Network log of my flutter app.
![f_app_2](https://user-images.githubusercontent.com/45417992/119496396-1fa5a880-bd6c-11eb-87e8-304bc1735259.jpg)
In my app I do not see that `favicon.ico`, `main.dart.lib.js` and `web_entrypoint.dart.lib.js` are not loaded. Why does this happens?

**Comment by jmewes** [comment] 2021-05-25 18:11
> @jmewes, I tested your `flutter_hot_restart` and it works for me. :( But my project is not hot restarted anymore.
> Any newly created app is working. Weird thing.

@bambinoua,

Without a minimal app and steps to reproduce, the problem cannot be analyzed and fixed.

See the following links for hints how to chop off small parts of your project until all lines of code which are not relevant to the problem are removed:

- https://stackoverflow.com/help/minimal-reproducible-example
- https://dzone.com/articles/debugging-step-step-delta
- https://www-archive.mozilla.org/newlayout/bugathon#testcase

**Comment by bambinoua** [comment] 2021-05-27 16:23
It seems I found my problem. And in regarding to this issue I came to conclusion that there is no flutter issue when this is occurred but this is the issue in the project code. In my case I tried to read the first item of stream while stream does not emit anything.
P.S. I will remove my above comments.

**Comment by jonahwilliams** [comment] 2021-07-20 21:52
Closing as resolved

**Closed by jonahwilliams** 2021-07-20 21:52 UTC
Labels: P3, found in release: 2.0, has reproducible steps, platform-web, t: hot reload, tool
