### ISSUE TITLE
[BUG] flutter analyze exit code -1 in info level

### ISSUE THREAD

**Issue by btd1337** [flutter/flutter#57880] opened 2020-05-24 03:30 UTC
Hi devs,

When you run the commad below:

```bash
flutter analyze
```

Although it only has `info level` the command return `exit code 1 (Fail)`

The problem begin when u try to use one githook tool in your project like `lefthook`:

```bash
   info • 'body1' is deprecated and shouldn't be used. This is the term used in the 2014 version of material design. The modern term is bodyText2. This feature was deprecated after v1.13.8. • lib/views/serviceProvider/service_provider_profile.dart:303:53 • deprecated_member_use
   info • 'body1' is deprecated and shouldn't be used. This is the term used in the 2014 version of material design. The modern term is bodyText2. This feature was deprecated after v1.13.8. • lib/views/serviceProvider/service_provider_profile.dart:599:55 • deprecated_member_use
   info • 'body1' is deprecated and shouldn't be used. This is the term used in the 2014 version of material design. The modern term is bodyText2. This feature was deprecated after v1.13.8. • lib/views/serviceProvider/service_provider_profile.dart:617:55 • deprecated_member_use
   info • 'body1' is deprecated and shouldn't be used. This is the term used in the 2014 version of material design. The modern term is bodyText2. This feature was deprecated after v1.13.8. • lib/views/serviceProvider/service_provider_profile.dart:635:55 • deprecated_member_use
   info • 'body1' is deprecated and shouldn't be used. This is the term used in the 2014 version of material design. The modern term is bodyText2. This feature was deprecated after v1.13.8. • lib/views/serviceProvider/service_provider_profile_editing_screen.dart:352:65 • deprecated_member_use

138 issues found. (ran in 6.2s)

SUMMARY: (done in 20.74 seconds)
✔️  tests
🥊  linter
error: failed to push some refs to 'git@bitbucket.org:xxx/yyyy.git'
```
I think that any analyze tool should have an option to you set the error level. In this case I would not  include `info` and `warning` level like `error level`.

This is an error or a bug. Please help to solve this problem.

Thanks in advance

**Comment by TahaTesser** [comment] 2020-05-25 11:34
Hi @btd1337 
can you please provide your `flutter doctor -v` and `flutter analyze -v`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by btd1337** [comment] 2020-05-27 17:33
@TahaTesser Checked in https://github.com/dart-lang/sdk/issues/42029:

`Dartanalyzer` it's OK, but `Flutter Analyze` is not.

```bash
dartanalyzer .
                 
Analyzing xxx-mobile...
  lint • Unnecessary new keyword. • lib/styles/components/progress_indicators.dart:36:21 • unnecessary_new
  lint • Unnecessary new keyword. • lib/styles/components/progress_indicators.dart:59:21 • unnecessary_new
  lint • Don't explicitly initialize variables to null. • lib/styles/components/text_fields.dart:93:5 • avoid_init_to_null
  lint • Don't explicitly initialize variables to null. • lib/styles/components/text_fields.dart:94:5 • avoid_init_to_null
  lint • DO use curly braces for all flow control structures. • lib/styles/components/text_fields.dart:985:35 • curly_braces_in_flow_control_structures
  lint • DO use curly braces for all flow control structures. • lib/styles/components/time_picker.dart:106:7 • curly_braces_in_flow_control_structures
  lint • Use isEmpty instead of length • lib/views/common/confirm_email.dart:334:11 • prefer_is_empty
  lint • Use isEmpty instead of length • lib/views/common/confirm_email.dart:340:11 • prefer_is_empty
  lint • Use isEmpty instead of length • lib/views/common/forgot_password/forgot_password_step_2.dart:130:11 • prefer_is_empty
  lint • Use isEmpty instead of length • lib/views/common/forgot_password/forgot_password_step_2.dart:153:11 • prefer_is_empty
  lint • DO use curly braces for all flow control structures. • lib/views/customer/customer_jobs_historic_page.dart:91:15 • curly_braces_in_flow_control_structures
  lint • DO use curly braces for all flow control structures. • lib/views/customer/customer_jobs_historic_page.dart:94:15 • curly_braces_in_flow_control_structures
  lint • Equality operator `==` invocation with references of unrelated types. • lib/views/serviceProvider/service_provider_jobs_historic_page.dart:321:31 • unrelated_type_equality_checks
  hint • Unused import: 'package:bridi_mobile/services/server.service.dart'. • lib/views/customer/add_credit_card.dart:16:8 • unused_import
13 lints and 1 hint found.

return 0
```

```bash
flutter analyze

Analyzing xxx-mobile...                                               

   info • Unnecessary new keyword • lib/styles/components/progress_indicators.dart:36:21 • unnecessary_new
   info • Unnecessary new keyword • lib/styles/components/progress_indicators.dart:59:21 • unnecessary_new
   info • Don't explicitly initialize variables to null • lib/styles/components/text_fields.dart:93:5 • avoid_init_to_null
   info • Don't explicitly initialize variables to null • lib/styles/components/text_fields.dart:94:5 • avoid_init_to_null
   info • DO use curly braces for all flow control structures • lib/styles/components/text_fields.dart:985:35 •
          curly_braces_in_flow_control_structures
   info • DO use curly braces for all flow control structures • lib/styles/components/time_picker.dart:106:7 • curly_braces_in_flow_control_structures
   info • Use isEmpty instead of length • lib/views/common/confirm_email.dart:334:11 • prefer_is_empty
   info • Use isEmpty instead of length • lib/views/common/confirm_email.dart:340:11 • prefer_is_empty
   info • Use isEmpty instead of length • lib/views/common/forgot_password/forgot_password_step_2.dart:130:11 • prefer_is_empty
   info • Use isEmpty instead of length • lib/views/common/forgot_password/forgot_password_step_2.dart:153:11 • prefer_is_empty
   info • Unused import: 'package:bridi_mobile/services/server.service.dart' • lib/views/customer/add_credit_card.dart:16:8 • unused_import
   info • DO use curly braces for all flow control structures • lib/views/customer/customer_jobs_historic_page.dart:91:15 •
          curly_braces_in_flow_control_structures
   info • DO use curly braces for all flow control structures • lib/views/customer/customer_jobs_historic_page.dart:94:15 •
          curly_braces_in_flow_control_structures
   info • Equality operator `==` invocation with references of unrelated types •
          lib/views/serviceProvider/service_provider_jobs_historic_page.dart:321:31 • unrelated_type_equality_checks

14 issues found. (ran in 4.5s)

return 1
```

```bash
flutter doctor -v
[✓] Flutter (Channel stable, v1.17.1, on Linux, locale pt_BR.UTF-8)
    • Flutter version 1.17.1 at /opt/flutter
    • Framework revision f7a6a7906b (2 weeks ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /opt/android/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /opt/android/sdk
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Android Studio (version 3.6)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```

```flutter analyze -v
.
.
.
[  +17 ms] Analyzing bridi-mobile... (completed in 4,7s)
[   +8 ms]    info • Unnecessary new keyword • lib/styles/components/progress_indicators.dart:36:21 • unnecessary_new
[   +1 ms]    info • Unnecessary new keyword • lib/styles/components/progress_indicators.dart:59:21 • unnecessary_new
[        ]    info • Don't explicitly initialize variables to null • lib/styles/components/text_fields.dart:93:5 • avoid_init_to_null
[        ]    info • Don't explicitly initialize variables to null • lib/styles/components/text_fields.dart:94:5 • avoid_init_to_null
[   +2 ms]    info • DO use curly braces for all flow control structures • lib/styles/components/text_fields.dart:985:35 •
                     curly_braces_in_flow_control_structures
[        ]    info • DO use curly braces for all flow control structures • lib/styles/components/time_picker.dart:106:7 •
curly_braces_in_flow_control_structures
[   +1 ms]    info • Use isEmpty instead of length • lib/views/common/confirm_email.dart:334:11 • prefer_is_empty
[        ]    info • Use isEmpty instead of length • lib/views/common/confirm_email.dart:340:11 • prefer_is_empty
[        ]    info • Use isEmpty instead of length • lib/views/common/forgot_password/forgot_password_step_2.dart:130:11 • prefer_is_empty
[        ]    info • Use isEmpty instead of length • lib/views/common/forgot_password/forgot_password_step_2.dart:153:11 • prefer_is_empty
[        ]    info • Unused import: 'package:bridi_mobile/services/server.service.dart' • lib/views/customer/add_credit_card.dart:16:8 • unused_import
[   +1 ms]    info • DO use curly braces for all flow control structures • lib/views/customer/customer_jobs_historic_page.dart:91:15 •
                     curly_braces_in_flow_control_structures
[   +2 ms]    info • DO use curly braces for all flow control structures • lib/views/customer/customer_jobs_historic_page.dart:94:15 •
                     curly_braces_in_flow_control_structures
[   +1 ms]    info • Equality operator `==` invocation with references of unrelated types •
                     lib/views/serviceProvider/service_provider_jobs_historic_page.dart:321:31 • unrelated_type_equality_checks
[   +9 ms] "flutter analyze" took 6.232ms.
14 issues found. (ran in 4.7s)

#0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
#1      AnalyzeOnce.analyze (package:flutter_tools/src/commands/analyze_once.dart:180:9)
#2      _rootRunUnary (dart:async/zone.dart:1192:38)
#3      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#4      _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#5      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#6      Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#7      Future._completeWithValue (dart:async/future_impl.dart:526:5)
#8      Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
#9      _rootRun (dart:async/zone.dart:1184:13)
#10     _CustomZone.run (dart:async/zone.dart:1077:19)
#11     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
#12     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
#13     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#14     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#15     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#16     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

**Comment by TahaTesser** [comment] 2020-05-28 07:35
Issue reproduces on latest `master`

<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel master, 1.19.0-2.0.pre.173, on Mac OS X 10.15.5 19F96,
    locale en-GB)
    • Flutter version 1.19.0-2.0.pre.173 at
      /Users/tahatesser/Code/flutter_master
    • Framework revision 5663e02645 (9 hours ago), 2020-05-27 18:32:01 -0400
    • Engine revision 2663be8370
    • Dart version 2.9.0 (build 2.9.0-11.0.dev e007545c42)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.2

[✓] Connected device (4 available)
    • Taha’s iPhone • 00008020-001059882212002E • ios            • iOS 13.5
    • macOS         • macOS                     • darwin-x64     • Mac OS X
      10.15.5 19F96
    • Web Server    • web-server                • web-javascript • Flutter Tools
    • Chrome        • chrome                    • web-javascript • Google Chrome
      83.0.4103.61

• No issues found!
``` 

</details> 

Closing as duplicate of https://github.com/flutter/flutter/issues/20855

**Closed by TahaTesser** 2020-05-28 07:35 UTC
Labels: in triage
