### ISSUE TITLE
[tool_crash] ProcessException: Failed to find "D:\Flutter\FlutterSDK\bin\cache\dart-sdk\bin\dartaotruntime.exe" in the search path. Command: D:\Flutter\FlutterSDK\bin\cache\dart-sdk\bin\dartaotruntime.exe, OS error code: 0

### ISSUE THREAD

**Issue by TaifRaoof** [flutter/flutter#145749] opened 2024-03-26 11:31 UTC
## Command
```
flutter --no-color run --machine --track-widget-creation --device-id=192.168.20.10:5555 --start-paused --dart-define=flutter.inspector.structuredErrors=true lib\main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ProcessException: Failed to find "D:\Flutter\FlutterSDK\bin\cache\dart-sdk\bin\dartaotruntime.exe" in the search path. Command: D:\Flutter\FlutterSDK\bin\cache\dart-sdk\bin\dartaotruntime.exe, OS error code: 0
```
#0      LocalProcessManager.start (package:process/src/interface/local_process_manager.dart:56:7)
#1      ErrorHandlingProcessManager.start.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:686:24)
#2      _run (package:flutter_tools/src/base/error_handling_io.dart:556:20)
#3      ErrorHandlingProcessManager.start (package:flutter_tools/src/base/error_handling_io.dart:685:12)
#4      DefaultResidentCompiler._compile (package:flutter_tools/src/compile.dart:874:37)
#5      DefaultResidentCompiler._recompile (package:flutter_tools/src/compile.dart:734:14)
#6      _RecompileRequest._run (package:flutter_tools/src/compile.dart:420:16)
#7      _CompilationRequest.run (package:flutter_tools/src/compile.dart:394:30)
#8      DefaultResidentCompiler._handleCompilationRequest (package:flutter_tools/src/compile.dart:780:23)
#9      _rootRunUnary (dart:async/zone.dart:1407:47)
#10     _CustomZone.runUnary (dart:async/zone.dart:1308:19)
#11     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217:7)
#12     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#13     _DelayedData.perform (dart:async/stream_impl.dart:515:14)
#14     _PendingEvents.handleNext (dart:async/stream_impl.dart:620:11)
#15     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:591:7)
#16     _rootRun (dart:async/zone.dart:1391:47)
#17     _CustomZone.run (dart:async/zone.dart:1301:19)
#18     _CustomZone.runGuarded (dart:async/zone.dart:1209:7)
#19     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1249:23)
#20     _rootRun (dart:async/zone.dart:1399:13)
#21     _CustomZone.run (dart:async/zone.dart:1301:19)
#22     _CustomZone.runGuarded (dart:async/zone.dart:1209:7)
#23     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1249:23)
#24     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
```
```
[✓] Flutter (Channel stable, 3.19.4, on Microsoft Windows [Version 10.0.19045.3930], locale en-US)
    • Flutter version 3.19.4 on channel stable at D:\Flutter\FlutterSDK
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 68bfaea224 (6 days ago), 2024-03-20 15:36:31 -0700
    • Engine revision a5c24f538d
    • Dart version 3.3.2
    • DevTools version 2.31.1

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at D:\Flutter\AndroidSDK
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = D:/Flutter/AndroidSDK
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0--11185874)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop Windows apps (Visual Studio Build Tools 2019 16.11.7)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
    • Visual Studio Build Tools 2019 version 16.11.31911.196
    ✗ The current Visual Studio installation is incomplete.
      Please use Visual Studio Installer to complete the installation or reinstall Visual Studio.

[✓] Android Studio (version 2023.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 17.0.9+0--11185874)

[✓] VS Code (version 1.70.2)
    • VS Code at C:\Users\Taief\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.60.0

[✓] Connected device (4 available)
    • Pixel 8 Pro (mobile) • 192.168.20.10:5555 • android-arm64  • Android 14 (API 34)
    • Windows (desktop)    • windows            • windows-x64    • Microsoft Windows [Version 10.0.19045.3930]
    • Chrome (web)         • chrome             • web-javascript • Google Chrome 123.0.6312.59
    • Edge (web)           • edge               • web-javascript • Microsoft Edge 122.0.2365.92

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 796c8ef79279f9c774545b3771238c3098dbefab
### Plugins
barcode_scan2-4.3.0
file_picker-8.0.0+1
flutter_plugin_android_lifecycle-2.0.17
google_maps_flutter-2.6.0
google_maps_flutter_android-2.7.0
google_maps_flutter_ios-2.5.0
google_maps_flutter_web-0.5.6+2
location-5.0.3
location_web-4.2.0
onesignal_flutter-5.1.3
package_info_plus-6.0.0
path_provider-2.1.2
path_provider_android-2.2.2
path_provider_foundation-2.3.2
path_provider_linux-2.2.1
path_provider_windows-2.2.1
shared_preferences-2.2.2
shared_preferences_android-2.2.1
shared_preferences_foundation-2.3.5
shared_preferences_linux-2.3.2
shared_preferences_web-2.3.0
shared_preferences_windows-2.3.2
sqflite-2.3.2
url_launcher-6.2.5
url_launcher_android-6.3.0
url_launcher_ios-6.2.5
url_launcher_linux-3.1.1
url_launcher_macos-3.1.0
url_launcher_web-2.3.0
url_launcher_windows-3.1.1

**Comment by danagbemava-nc** [comment] 2024-03-26 12:56
Closing this as a duplicate of https://github.com/flutter/flutter/issues/143391

**Closed by danagbemava-nc** 2024-03-26 12:56 UTC
Labels: in triage
