### ISSUE TITLE
Hot Reload No constructor 'StatefulWidget.' with matching arguments declared in class 'StatefulWidget'.

### ISSUE THREAD

**Issue by XcodeSheng** [flutter/flutter#84685] opened 2021-06-16 06:39 UTC
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following NoSuchMethodError was thrown building
ComponentWidget<ForwardLinkState>-[<ForwardLinkComponent>](dirty, state:
ComponentState<ForwardLinkState>#f00b4):
No constructor 'StatefulWidget.' with matching arguments declared in class 'StatefulWidget'.
Receiver: StatefulWidget
Tried calling: new StatefulWidget.()
Found: new StatefulWidget.({Key? key}) => StatefulWidget

Widget creation tracking is currently disabled. Enabling it enables improved error messages. It can
be enabled by passing `--track-widget-creation` to `flutter run` or `flutter test`.

![image](https://user-images.githubusercontent.com/28858857/122169667-40b37200-ceb0-11eb-9cf1-04291373cf4e.png)

![image](https://user-images.githubusercontent.com/28858857/122169903-8bcd8500-ceb0-11eb-8b4e-c690390ff948.png)

**Comment by darshankawar** [comment] 2021-06-16 10:36
@XcodeSheng 
Can you provide [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that shows this issue ?
Thanks.

**Comment by XcodeSheng** [comment] 2021-06-16 13:10
[example.zip](https://github.com/flutter/flutter/files/6663210/example.zip)
你可以使用这个demo
1、 flutter pub get 
2、cd  example/iOS   pod install
3、 run and HotReload  it will be  repeat

**Comment by darshankawar** [comment] 2021-06-16 13:32
@XcodeSheng 
From your code, I see that you are using `flutter_boost` which is 3rd party:

```
flutter_boost:
    git:
        url: 'https://github.com/alibaba/flutter_boost.git'
        ref: 'v3.0-beta.11'
```

Can you remove that and try again to see if issue persists ?

**Comment by XcodeSheng** [comment] 2021-06-17 01:47
I'm sorry, our project depends on it；Is this situation caused by flutter_boost?

**Comment by darshankawar** [comment] 2021-06-17 05:33
@XcodeSheng 
I am not completely sure, but since you are using that plugin heavily, I suggest you to open this issue in plugin's dedicated repo: https://github.com/alibaba/flutter_boost/issues

If they comeback saying it's a framework issue and not the plugin, please write in comments here and I'll reopen.

Closing for now.

**Closed by darshankawar** 2021-06-17 05:33 UTC
Labels: in triage
