### ISSUE TITLE
[tool_crash] FileSystemException: Cannot copy file to '/Users/rahulrawat/newErpProject/ios/Podfile', path = '/Users/rahulrawat/sdkpath/flutter/packages/flutter_tools/templates/cocoapods/Podfile-ios-swift' (OS Error: No such file or directory, errno = 2)

### ISSUE THREAD

**Issue by rahulrawat-n** [flutter/flutter#60283] opened 2020-06-25 14:07 UTC
## Command
```
flutter --no-color run --machine --track-widget-creation --device-id=43DCF916-265E-4E53-8FD6-69E41997FDFC lib/main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: FileSystemException: Cannot copy file to '/Users/rahulrawat/newErpProject/ios/Podfile', path = '/Users/rahulrawat/sdkpath/flutter/packages/flutter_tools/templates/cocoapods/Podfile-ios-swift' (OS Error: No such file or directory, errno = 2)
```
#0      _File.throwIfError (dart:io/file_impl.dart:645:7)
#1      _File.copySync (dart:io/file_impl.dart:350:5)
#2      ForwardingFile.copySync (package:file/src/forwarding/forwarding_file.dart:30:50)
#3      ForwardingFile.copySync (package:file/src/forwarding/forwarding_file.dart:30:50)
#4      CocoaPods.setupPodfile (package:flutter_tools/src/macos/cocoapods.dart:282:21)
<asynchronous suspension>
#5      injectPlugins (package:flutter_tools/src/plugins.dart:1100:33)
<asynchronous suspension>
#6      FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:232:11)
<asynchronous suspension>
#7      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:707:21)
<asynchronous suspension>
#8      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:619:33)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart)
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#11     _rootRun (dart:async/zone.dart:1184:13)
#12     _CustomZone.run (dart:async/zone.dart:1077:19)
#13     _runZoned (dart:async/zone.dart:1619:10)
#14     runZoned (dart:async/zone.dart:1539:10)
```
```
[✓] Flutter (Channel stable, v1.17.0, on Mac OS X 10.15.2 19C57, locale en-GB)
    • Flutter version 1.17.0 at /Users/rahulrawat/sdkpath/flutter
    • Framework revision e6b34c2b5c (8 weeks ago), 2020-05-02 11:39:18 -0700
    • Engine revision 540786dd51
    • Dart version 2.8.1

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/rahulrawat/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.9.3

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] Connected device (3 available)
    • Redmi Note 8 Pro          • 5t7tusozugvopbda                     • android-arm64 • Android 9 (API 28)
    • Android SDK built for x86 • emulator-5554                        • android-x86   • Android 10 (API 29) (emulator)
    • iPhone 11 Pro Max         • 43DCF916-265E-4E53-8FD6-69E41997FDFC • ios           • com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: f139b11009aeb8ed2a3a3aa8b0066e482709dde3
### Plugins
cloud_firestore-0.13.5
cloud_firestore_web-0.1.1+2
connectivity-0.4.8+6
connectivity_macos-0.1.0+3
fijkplayer-0.8.4
file_picker-1.9.0+1
firebase_auth-0.16.1
firebase_auth_web-0.1.3+1
firebase_core-0.4.4+3
firebase_core_web-0.1.1+2
firebase_messaging-6.0.16
firebase_storage-3.1.5
flutter_local_notifications-1.4.3
flutter_plugin_android_lifecycle-1.0.7
google_sign_in-4.5.1
google_sign_in_web-0.9.1+1
image_cropper-1.2.3
image_picker-0.6.6+1
open_file-3.0.1
path_provider-1.6.7
path_provider_macos-0.0.4+2
shared_preferences-0.5.7+3
shared_preferences_macos-0.0.1+10
shared_preferences_web-0.1.2+7
sqflite-1.3.1
url_launcher-5.4.10
url_launcher_macos-0.0.1+7
url_launcher_web-0.1.1+6
video_thumbnail-0.2.1

**Comment by TahaTesser** [comment] 2020-06-25 14:37
related https://github.com/flutter/flutter/issues/59637

**Comment by jmagman** [comment] 2020-07-14 23:54
@rahulrawat-n Does `/Users/rahulrawat/sdkpath/flutter/packages/flutter_tools/templates/cocoapods/Podfile-ios-swift` exist?  Is there anything in that directory? What's the output of:
```
$ cd /Users/rahulrawat/sdkpath/flutter
$ git status
```

**Comment by TahaTesser** [comment] 2020-08-05 14:16
Closing as. duplicate of https://github.com/flutter/flutter/issues/50880

**Closed by TahaTesser** 2020-08-05 14:16 UTC
Labels: severe: crash, tool, waiting for customer response
