### ISSUE TITLE
Can't build appbundle with current stable version

### ISSUE THREAD

**Issue by tomkastek** [flutter/flutter#36943] opened 2019-07-25 12:30 UTC
I have a Flutter App in the Play Store. So I wanted to upgrade to current stable version to build my Flutter App as appbundle. On the first builds, I got a warning with the hint that androidX could be the problem. So I used the recommended way with Android studio to update my App. After I still wasn't able to build with the error `Gradle build failed to produce an Android bundle package`. If I use `flutter build apk` everything works fine but that I cannot use for play store. (Also `flutter build apk --split-per-abi` fails for me)

The full output of the `flutter build appbundle --flavor my_flavor --release -t "bin/main_my_flavor.dart"` command is:

```
Initializing gradle...                                              1,6s
Resolving dependencies...                                           3,7s
Note: Some input files use or override a deprecated API.                
Note: Recompile with -Xlint:deprecation for details.                    
Note: /Users/tom/development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_webview_plugin-0.3.5/android/src/main/java/com/flutter_webview_plugin/WebviewManager.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.                      
ProGuard, version 6.0.3                                                 
Reading input...                                                        
Reading program jar [/Users/tom/development/test/test2/my-app/build/app/intermediates/flutter/app_StagingRelease/libs.jar] (filtered)
Reading program jar [/Users/tom/.gradle/caches/transforms-2/files-2.1/5e98fb800668bcfddef5476e0866b66d/jetified-flutter.jar] (filtered)
Reading program jar [/Users/tom/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jdk7/1.2.71/4ce93f539e2133f172f1167291a911f83400a5d0/kotlin-stdlib-jdk7-1.2.71.jar] (filtered)
Reading program jar [/Users/tom/.gradle/caches/transforms-2/files-2.1/b3aa2a123e1bd29a1f966c996b88eb62/jars/classes.jar] (filtered)
Reading program jar [/Users/tom/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.2.71/d9717625bb3c731561251f8dd2c67a1011d6764c/kotlin-stdlib-1.2.71.jar] (filtered)
Reading program jar [/Users/tom/.gradle/caches/transforms-2/files-2.1/c809aa0a752b29782eeaaae81427831a/jars/classes.jar] (filtered)
Reading program jar [/Users/tom/.gradle/caches/transforms-2/files-2.1/c2a6a9c5cae1c96a66361218dc2a0755/jars/classes.jar] (filtered)
Reading program jar [/Users/tom/.gradle/caches/transforms-2/files-2.1/4048c6ba803d0dda61df807151cf1211/jars/classes.jar] (filtered)
Reading program jar [/Users/tom/.gradle/caches/transforms-2/files-2.1/534fdc409d339713f2c3f9326289a4f5/jars/classes.jar] (filtered)
Reading program jar [/Users/tom/.gradle/caches/transforms-2/files-2.1/a53b5c2a89a8583e22a3700aa0a86278/jars/classes.jar] (filtered)
Reading program jar [/Users/tom/.gradle/caches/transforms-2/files-2.1/caa12a1a86a5606c6193a5edbb6f8774/jars/classes.jar] (filtered)
Reading program jar [/Users/tom/.gradle/caches/transforms-2/files-2.1/f9e86b226d87e6c7b4225bff6972b83b/jars/classes.jar] (filtered)
Reading program jar [/Users/tom/.gradle/caches/transforms-2/files-2.1/8dbf01bb52d1baa837a0eeef5421152c/jars/classes.jar] (filtered)
Reading program jar [/Users/tom/.gradle/caches/transforms-2/files-2.1/b6fa691cc75dfdb9af642074da1de15a/jars/classes.jar] (filtered)
Reading program jar [/Users/tom/.gradle/caches/transforms-2/files-2.1/74fd6958fef953e07056b7ed855004c3/jars/classes.jar] (filtered)
Reading program jar [/Users/tom/.gradle/caches/transforms-2/files-2.1/e7bb227bfb9310a8d51ba09094081e93/jars/classes.jar] (filtered)
Reading program jar [/Users/tom/.gradle/caches/transforms-2/files-2.1/5a608068ab03b4620e08d0e1497c3515/jars/classes.jar] (filtered)
Reading program jar [/Users/tom/.gradle/caches/transforms-2/files-2.1/d53b5d236b8b6b150577e77a85a5e5a7/jars/classes.jar] (filtered)
Reading program jar [/Users/tom/.gradle/caches/transforms-2/files-2.1/e0ac1cba174727edc682a33788a48e63/jars/classes.jar] (filtered)
Reading program jar [/Users/tom/.gradle/caches/transforms-2/files-2.1/8137fd4a9d8cdda86d539072df116de2/jars/classes.jar] (filtered)
Reading program jar [/Users/tom/.gradle/caches/modules-2/files-2.1/androidx.collection/collection/1.0.0/42858b26cafdaa69b6149f45dfc2894007bc2c7a/collection-1.0.0.jar] (filtered)
Reading program jar [/Users/tom/.gradle/caches/transforms-2/files-2.1/04c995228f74e8c7682a408610fda8c2/jars/classes.jar] (filtered)
Reading program jar [/Users/tom/.gradle/caches/transforms-2/files-2.1/7590b60b7feb91ffc20a48dc1ab1d94f/jars/classes.jar] (filtered)
Reading program jar [/Users/tom/.gradle/caches/transforms-2/files-2.1/9d623a75802c56b2014698b0c16b8183/jars/classes.jar] (filtered)
Reading program jar [/Users/tom/.gradle/caches/transforms-2/files-2.1/73586c2edb8cb09601aaf8687cfc95cd/jars/classes.jar] (filtered)
Reading program jar [/Users/tom/.gradle/caches/transforms-2/files-2.1/e2967b46b14927f76b24aa2d015c0b0c/jars/classes.jar] (filtered)
Reading program jar [/Users/tom/.gradle/caches/transforms-2/files-2.1/5d55c0fc42d34408b31213919c8280c4/jars/classes.jar] (filtered)
Reading program jar [/Users/tom/.gradle/caches/transforms-2/files-2.1/b5a66ceb1766f381089f206bd7f31f5b/jars/classes.jar] (filtered)
Reading program jar [/Users/tom/.gradle/caches/transforms-2/files-2.1/99d729219484002a50eeb4924ff7b546/jars/classes.jar] (filtered)
Reading program jar [/Users/tom/.gradle/caches/modules-2/files-2.1/androidx.lifecycle/lifecycle-common/2.0.0/e070ffae07452331bc5684734fce6831d531785c/lifecycle-common-2.0.0.jar] (filtered)
Reading program jar [/Users/tom/.gradle/caches/transforms-2/files-2.1/6064df98affb4c6982156f379137bf1d/jars/classes.jar] (filtered)
Reading program jar [/Users/tom/.gradle/caches/modules-2/files-2.1/androidx.arch.core/core-common/2.0.0/bb21b9a11761451b51624ac428d1f1bb5deeac38/core-common-2.0.0.jar] (filtered)
Reading program jar [/Users/tom/.gradle/caches/transforms-2/files-2.1/acff4e1c36c1cb345e334e98decafdfe/jars/classes.jar] (filtered)
Reading program jar [/Users/tom/.gradle/caches/modules-2/files-2.1/androidx.annotation/annotation/1.0.0/45599f2cd5965ac05a1488fa2a5c0cdd7c499ead/annotation-1.0.0.jar] (filtered)
Reading program jar [/Users/tom/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-common/1.2.71/ba18ca1aa0e40eb6f1865b324af2f4cbb691c1ec/kotlin-stdlib-common-1.2.71.jar] (filtered)
Reading program jar [/Users/tom/.gradle/caches/modules-2/files-2.1/org.jetbrains/annotations/13.0/919f0dfe192fb4e063e7dacadee7f8bb9a2672a9/annotations-13.0.jar] (filtered)
Reading program jar [/Users/tom/development/test/test2/my-app/build/shared_preferences/intermediates/intermediate-jars/release/classes.jar] (filtered)
Reading program jar [/Users/tom/development/test/test2/my-app/build/url_launcher/intermediates/intermediate-jars/release/classes.jar] (filtered)
Reading program jar [/Users/tom/development/test/test2/my-app/build/flutter_webview_plugin/intermediates/intermediate-jars/release/classes.jar] (filtered)
Reading program jar [/Users/tom/development/test/test2/my-app/build/uni_links/intermediates/intermediate-jars/release/classes.jar] (filtered)
Reading program jar [/Users/tom/development/test/test2/my-app/build/package_info/intermediates/intermediate-jars/release/classes.jar] (filtered)
Reading program jar [/Users/tom/development/test/test2/my-app/build/device_info/intermediates/intermediate-jars/release/classes.jar] (filtered)
Reading program directory [/Users/tom/development/test/test2/my-app/build/app/intermediates/javac/app_StagingRelease/compileapp_StagingReleaseJavaWithJavac/classes] (filtered)
Reading program directory [/Users/tom/development/test/test2/my-app/build/app/tmp/kotlin-classes/app_StagingRelease] (filtered)
Reading program jar [/Users/tom/development/test/test2/my-app/build/app/intermediates/transforms/mergeJavaRes/app_Staging/release/0.jar] (filtered)
Reading library jar [/Users/tom/Library/Android/sdk/platforms/android-28/android.jar]
Reading library jar [/Users/tom/Library/Android/sdk/build-tools/28.0.3/core-lambda-stubs.jar]
Reading library jar [/Users/tom/Library/Android/sdk/platforms/android-28/optional/org.apache.http.legacy.jar]
Reading library jar [/Users/tom/Library/Android/sdk/platforms/android-28/optional/android.test.mock.jar]
Reading library jar [/Users/tom/Library/Android/sdk/platforms/android-28/optional/android.test.base.jar]
Reading library jar [/Users/tom/Library/Android/sdk/platforms/android-28/optional/android.test.runner.jar]
Initializing...                                                         
Note: io.flutter.view.AccessibilityViewEmbedder$ReflectionAccessors: can't find dynamically referenced class android.util.LongArray
Note: kotlin.internal.PlatformImplementationsKt: can't find dynamically referenced class kotlin.internal.jdk8.JDK8PlatformImplementations
Note: kotlin.internal.PlatformImplementationsKt: can't find dynamically referenced class kotlin.internal.JRE8PlatformImplementations
Note: kotlin.internal.PlatformImplementationsKt: can't find dynamically referenced class kotlin.internal.JRE7PlatformImplementations
Note: kotlin.jvm.internal.Reflection: can't find dynamically referenced class kotlin.reflect.jvm.internal.ReflectionFactoryImpl
Note: the configuration keeps the entry point 'com.flutter_webview_plugin.ObservableWebView { void setOnScrollChangedCallback(com.flutter_webview_plugin.ObservableWebView$OnScrollChangedCallback); }', but not the descriptor class 'com.flutter_webview_plugin.ObservableWebView$OnScrollChangedCallback'
Note: there were 1 unkept descriptor classes in kept class members.     
      You should consider explicitly keeping the mentioned classes      
      (using '-keep').                                                  
      (http://proguard.sourceforge.net/manual/troubleshooting.html#descriptorclass)
Note: there were 5 unresolved dynamic references to classes or interfaces.
      You should check if you need to specify additional program jars.  
      (http://proguard.sourceforge.net/manual/troubleshooting.html#dynamicalclass)
Note: you're ignoring all warnings!                                     
Ignoring unused library classes...                                      
  Original number of library classes: 4803                              
  Final number of library classes:    1331                              
Printing kept classes, fields, and methods...                           
Inlining subroutines...                                                 
Shrinking...                                                            
Printing usage to [/Users/tom/development/test/test2/my-app/build/app/outputs/mapping/app_Staging/release/usage.txt]...
Removing unused program classes and class elements...                   
  Original number of program classes: 2310                              
  Final number of program classes:    821                               
Obfuscating...                                                          
Printing mapping to [/Users/tom/development/test/test2/my-app/build/app/outputs/mapping/app_Staging/release/mapping.txt]...
Preverifying...                                                         
Writing output...                                                       
Preparing output jar [/Users/tom/development/test/test2/my-app/build/app/intermediates/transforms/proguard/app_Staging/release/0.jar]
  Copying resources from program jar [/Users/tom/development/test/test2/my-app/build/app/intermediates/flutter/app_StagingRelease/libs.jar] (filtered)
  Copying resources from program jar [/Users/tom/.gradle/caches/transforms-2/files-2.1/5e98fb800668bcfddef5476e0866b66d/jetified-flutter.jar] (filtered)
  Copying resources from program jar [/Users/tom/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jdk7/1.2.71/4ce93f539e2133f172f1167291a911f83400a5d0/kotlin-stdlib-jdk7-1.2.71.jar] (filtered)
  Copying resources from program jar [/Users/tom/.gradle/caches/transforms-2/files-2.1/b3aa2a123e1bd29a1f966c996b88eb62/jars/classes.jar] (filtered)
  Copying resources from program jar [/Users/tom/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.2.71/d9717625bb3c731561251f8dd2c67a1011d6764c/kotlin-stdlib-1.2.71.jar] (filtered)
  Copying resources from program jar [/Users/tom/.gradle/caches/transforms-2/files-2.1/c809aa0a752b29782eeaaae81427831a/jars/classes.jar] (filtered)
  Copying resources from program jar [/Users/tom/.gradle/caches/transforms-2/files-2.1/c2a6a9c5cae1c96a66361218dc2a0755/jars/classes.jar] (filtered)
  Copying resources from program jar [/Users/tom/.gradle/caches/transforms-2/files-2.1/4048c6ba803d0dda61df807151cf1211/jars/classes.jar] (filtered)
  Copying resources from program jar [/Users/tom/.gradle/caches/transforms-2/files-2.1/534fdc409d339713f2c3f9326289a4f5/jars/classes.jar] (filtered)
  Copying resources from program jar [/Users/tom/.gradle/caches/transforms-2/files-2.1/a53b5c2a89a8583e22a3700aa0a86278/jars/classes.jar] (filtered)
  Copying resources from program jar [/Users/tom/.gradle/caches/transforms-2/files-2.1/caa12a1a86a5606c6193a5edbb6f8774/jars/classes.jar] (filtered)
  Copying resources from program jar [/Users/tom/.gradle/caches/transforms-2/files-2.1/f9e86b226d87e6c7b4225bff6972b83b/jars/classes.jar] (filtered)
  Copying resources from program jar [/Users/tom/.gradle/caches/transforms-2/files-2.1/8dbf01bb52d1baa837a0eeef5421152c/jars/classes.jar] (filtered)
  Copying resources from program jar [/Users/tom/.gradle/caches/transforms-2/files-2.1/b6fa691cc75dfdb9af642074da1de15a/jars/classes.jar] (filtered)
  Copying resources from program jar [/Users/tom/.gradle/caches/transforms-2/files-2.1/74fd6958fef953e07056b7ed855004c3/jars/classes.jar] (filtered)
  Copying resources from program jar [/Users/tom/.gradle/caches/transforms-2/files-2.1/e7bb227bfb9310a8d51ba09094081e93/jars/classes.jar] (filtered)
  Copying resources from program jar [/Users/tom/.gradle/caches/transforms-2/files-2.1/5a608068ab03b4620e08d0e1497c3515/jars/classes.jar] (filtered)
  Copying resources from program jar [/Users/tom/.gradle/caches/transforms-2/files-2.1/d53b5d236b8b6b150577e77a85a5e5a7/jars/classes.jar] (filtered)
  Copying resources from program jar [/Users/tom/.gradle/caches/transforms-2/files-2.1/e0ac1cba174727edc682a33788a48e63/jars/classes.jar] (filtered)
  Copying resources from program jar [/Users/tom/.gradle/caches/transforms-2/files-2.1/8137fd4a9d8cdda86d539072df116de2/jars/classes.jar] (filtered)
  Copying resources from program jar [/Users/tom/.gradle/caches/modules-2/files-2.1/androidx.collection/collection/1.0.0/42858b26cafdaa69b6149f45dfc2894007bc2c7a/collection-1.0.0.jar] (filtered)
  Copying resources from program jar [/Users/tom/.gradle/caches/transforms-2/files-2.1/04c995228f74e8c7682a408610fda8c2/jars/classes.jar] (filtered)
  Copying resources from program jar [/Users/tom/.gradle/caches/transforms-2/files-2.1/7590b60b7feb91ffc20a48dc1ab1d94f/jars/classes.jar] (filtered)
  Copying resources from program jar [/Users/tom/.gradle/caches/transforms-2/files-2.1/9d623a75802c56b2014698b0c16b8183/jars/classes.jar] (filtered)
  Copying resources from program jar [/Users/tom/.gradle/caches/transforms-2/files-2.1/73586c2edb8cb09601aaf8687cfc95cd/jars/classes.jar] (filtered)
  Copying resources from program jar [/Users/tom/.gradle/caches/transforms-2/files-2.1/e2967b46b14927f76b24aa2d015c0b0c/jars/classes.jar] (filtered)
  Copying resources from program jar [/Users/tom/.gradle/caches/transforms-2/files-2.1/5d55c0fc42d34408b31213919c8280c4/jars/classes.jar] (filtered)
  Copying resources from program jar [/Users/tom/.gradle/caches/transforms-2/files-2.1/b5a66ceb1766f381089f206bd7f31f5b/jars/classes.jar] (filtered)
  Copying resources from program jar [/Users/tom/.gradle/caches/transforms-2/files-2.1/99d729219484002a50eeb4924ff7b546/jars/classes.jar] (filtered)
  Copying resources from program jar [/Users/tom/.gradle/caches/modules-2/files-2.1/androidx.lifecycle/lifecycle-common/2.0.0/e070ffae07452331bc5684734fce6831d531785c/lifecycle-common-2.0.0.jar] (filtered)
  Copying resources from program jar [/Users/tom/.gradle/caches/transforms-2/files-2.1/6064df98affb4c6982156f379137bf1d/jars/classes.jar] (filtered)
  Copying resources from program jar [/Users/tom/.gradle/caches/modules-2/files-2.1/androidx.arch.core/core-common/2.0.0/bb21b9a11761451b51624ac428d1f1bb5deeac38/core-common-2.0.0.jar] (filtered)
  Copying resources from program jar [/Users/tom/.gradle/caches/transforms-2/files-2.1/acff4e1c36c1cb345e334e98decafdfe/jars/classes.jar] (filtered)
  Copying resources from program jar [/Users/tom/.gradle/caches/modules-2/files-2.1/androidx.annotation/annotation/1.0.0/45599f2cd5965ac05a1488fa2a5c0cdd7c499ead/annotation-1.0.0.jar] (filtered)
  Copying resources from program jar [/Users/tom/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-common/1.2.71/ba18ca1aa0e40eb6f1865b324af2f4cbb691c1ec/kotlin-stdlib-common-1.2.71.jar] (filtered)
  Copying resources from program jar [/Users/tom/.gradle/caches/modules-2/files-2.1/org.jetbrains/annotations/13.0/919f0dfe192fb4e063e7dacadee7f8bb9a2672a9/annotations-13.0.jar] (filtered)
  Copying resources from program jar [/Users/tom/development/test/test2/my-app/build/shared_preferences/intermediates/intermediate-jars/release/classes.jar] (filtered)
  Copying resources from program jar [/Users/tom/development/test/test2/my-app/build/url_launcher/intermediates/intermediate-jars/release/classes.jar] (filtered)
  Copying resources from program jar [/Users/tom/development/test/test2/my-app/build/flutter_webview_plugin/intermediates/intermediate-jars/release/classes.jar] (filtered)
  Copying resources from program jar [/Users/tom/development/test/test2/my-app/build/uni_links/intermediates/intermediate-jars/release/classes.jar] (filtered)
  Copying resources from program jar [/Users/tom/development/test/test2/my-app/build/package_info/intermediates/intermediate-jars/release/classes.jar] (filtered)
  Copying resources from program jar [/Users/tom/development/test/test2/my-app/build/device_info/intermediates/intermediate-jars/release/classes.jar] (filtered)
  Copying resources from program directory [/Users/tom/development/test/test2/my-app/build/app/intermediates/javac/app_StagingRelease/compileApp_StagingReleaseJavaWithJavac/classes] (filtered)
  Copying resources from program directory [/Users/tom/development/test/test2/my-app/build/app/tmp/kotlin-classes/app_StagingRelease] (filtered)
  Copying resources from program jar [/Users/tom/development/test/test2/my-app/build/app/intermediates/transforms/mergeJavaRes/app_Staging/release/0.jar] (filtered)
Running Gradle task 'bundleApp_stagingRelease'...                   
Running Gradle task 'bundleApp_stagingRelease'... Done         80,0s
Gradle build failed to produce an Android bundle package.
```

output of `flutter analyze`:

```
Analyzing ovy-app...                                                    
No issues found! (ran in 8.6s)
```

output of `flutter doctor -v`:

```
[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.14.5 18F132, locale de-DE)
    • Flutter version 1.7.8+hotfix.4 at /Users/tom/development/flutter
    • Framework revision 20e59316b8 (6 days ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/tom/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • CocoaPods version 1.6.1

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 36.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] Connected device (1 available)
    • iPhone Xʀ • 095B1A07-E138-4A80-9783-8CA36DC8049A • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-4 (simulator)

• No issues found!
```

And if it is interesting my yaml file:

```
name: name
description: description

dependencies:
  cupertino_icons: "^0.1.2"
  device_info: "^0.4.0+2"
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: "0.13.0"
  flutter_webview_plugin: "^0.3.5"
  http: "^0.12.0+2"
  package_info: "^0.4.0+4"
  protobuf: "^0.13.12"
  shared_preferences: "^0.5.3+1"
  uni_links: "^0.2.0"
  url_launcher: "^5.0.3"

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl_translation: "^0.17.0"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/downloaded/
```

**Comment by lucaslcode** [comment] 2019-07-29 11:19
Same here, however in my case I can split per abi. No obvious errors with `flutter build appbundle -v`.

**Comment by blasten** [comment] 2019-08-01 23:33
This is a duplicate of https://github.com/flutter/flutter/issues/36067.

**Closed by blasten** 2019-08-01 23:33 UTC
