### ISSUE TITLE
RawKeyboardListener for soft keyboard

### ISSUE THREAD

**Issue by LiangHuangBC** [flutter/flutter#86560] opened 2021-07-16 15:28 UTC
How can I detect soft keyboard key event? 
Soft keyboard input trigger RawKeyboardListener on Flutter 1. But not Flutter 2.2.

On some android device, it scan barcode and send message like soft keyboard. I cannot get this input on flutter 2.2 without focus on some text field.

**Comment by iapicca** [comment] 2021-07-17 18:33
@LiangHuangBC 
how are you opening the soft keyboard w/o textfield?
can you show some code?

**Comment by TahaTesser** [comment] 2021-07-19 11:00
Hi @LiangHuangBC 
See https://github.com/flutter/flutter/issues/84925#issuecomment-865107014
Closing as duplicate of https://github.com/flutter/flutter/issues/84925

**Closed by TahaTesser** 2021-07-19 11:00 UTC
Labels: in triage

**Comment by LiangHuangBC** [comment] 2021-07-19 13:21
> @LiangHuangBC
> how are you opening the soft keyboard w/o textfield?
> can you show some code?

I don't need to open soft keyboard, I just click a hard key on android QR scanner, and the RawKeyboard listener will be triggered by QR code input, which is kind of "soft", but only on Flutter 1.

**Comment by LiangHuangBC** [comment] 2021-07-19 13:22
> Hi @LiangHuangBC
> See [#84925 (comment)](https://github.com/flutter/flutter/issues/84925#issuecomment-865107014)
> Closing as duplicate of #84925

Yes, I saw that issue, where can I add a request to Flutter, to let RawKeyboardListener listen to the soft keyboard input.

**Comment by LiangHuangBC** [comment] 2021-07-19 13:37
![image](https://user-images.githubusercontent.com/40865875/126168399-d217ab81-d7ee-4088-8a87-8a8c4112eb03.png)

**Comment by LiangHuangBC** [comment] 2021-07-19 14:36
Could you please reopen this issue? @TahaTesser

**Comment by TahaTesser** [comment] 2021-07-19 14:43
Hi @LiangHuangBC 
 

> how are you opening the soft keyboard w/o textfield?
> can you show some code?

Can you please provide your `flutter doctor -v`, a complete reproducible minimal code sample, and complete `flutter run --verbose` logs running the minimal code sample?
Thank you

**Comment by LiangHuangBC** [comment] 2021-07-19 14:50
relating issue :  #14809 https://github.com/flutter/flutter/issues/14809

**Comment by LiangHuangBC** [comment] 2021-07-19 14:51
flutter doctor -v 

`[✓] Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-x64, locale en-CA)
    • Flutter version 2.2.3 at /Users/lianghuang/dev/flutter
    • Framework revision f4abaa0735 (3 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/lianghuang/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/lianghuang/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/lianghuang/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.58.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.23.0

[✓] Connected device (3 available)
    • Liang’s iPhone (mobile) • 563e22fd81a284a4516cab5c993171146564ba6e • ios            • iOS 14.6
    • macOS (desktop)         • macos                                    • darwin-x64     • macOS 11.4 20F71 darwin-x64
    • Chrome (web)            • chrome                                   • web-javascript • Google Chrome 91.0.4472.114

• No issues found!`

**Comment by LiangHuangBC** [comment] 2021-07-19 14:55
Code sample for reproduce:

`@override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: Text("Soft keyboard", style: Get.textTheme.headline3),
          centerTitle: true,
        ),
        drawer: isPhone ? MenuView() : null,
        body: RawKeyboardListener(
          child: Container(),
          focusNode: FocusNode(),
          onKey: (e) => print(e),
        ));
  }`

**Comment by LiangHuangBC** [comment] 2021-07-19 15:10
LOGS:   
Keydown event is from Clicking hard scan key. There is no following soft key event which is what I need, I could focus on a text field to get soft input, but user don't focus on it.      

[+16986 ms] I/View    ( 3392): Key down dispatch to io.flutter.embedding.android.FlutterView{95573e9 VFE...... .F......
0,0-480,800}, event = KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_BUTTON_L1, scanCode=66, metaState=0, flags=0x8,
repeatCount=0, eventTime=384065, downTime=384065, deviceId=8, source=0x501 }
[ +471 ms] I/View    ( 3392): Key down dispatch to io.flutter.embedding.android.FlutterView{95573e9 VFE...... .F......
0,0-480,800}, event = KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_BUTTON_L1, scanCode=66, metaState=0, flags=0x88,
repeatCount=1, eventTime=384566, downTime=384065, deviceId=8, source=0x501 }
[  +47 ms] I/View    ( 3392): Key down dispatch to io.flutter.embedding.android.FlutterView{95573e9 VFE...... .F......
0,0-480,800}, event = KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_BUTTON_L1, scanCode=66, metaState=0, flags=0x8,
repeatCount=2, eventTime=384616, downTime=384065, deviceId=8, source=0x501 }
[  +49 ms] I/View    ( 3392): Key down dispatch to io.flutter.embedding.android.FlutterView{95573e9 VFE...... .F......
0,0-480,800}, event = KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_BUTTON_L1, scanCode=66, metaState=0, flags=0x8,
repeatCount=3, eventTime=384667, downTime=384065, deviceId=8, source=0x501 }
[  +53 ms] I/View    ( 3392): Key down dispatch to io.flutter.embedding.android.FlutterView{95573e9 VFE...... .F......
0,0-480,800}, event = KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_BUTTON_L1, scanCode=66, metaState=0, flags=0x8,
repeatCount=4, eventTime=384717, downTime=384065, deviceId=8, source=0x501 }
[  +48 ms] I/View    ( 3392): Key down dispatch to io.flutter.embedding.android.FlutterView{95573e9 VFE...... .F......
0,0-480,800}, event = KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_BUTTON_L1, scanCode=66, metaState=0, flags=0x8,
repeatCount=5, eventTime=384768, downTime=384065, deviceId=8, source=0x501 }
[  +54 ms] I/View    ( 3392): Key down dispatch to io.flutter.embedding.android.FlutterView{95573e9 VFE...... .F......
0,0-480,800}, event = KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_BUTTON_L1, scanCode=66, metaState=0, flags=0x8,
repeatCount=6, eventTime=384819, downTime=384065, deviceId=8, source=0x501 }
[  +50 ms] I/View    ( 3392): Key down dispatch to io.flutter.embedding.android.FlutterView{95573e9 VFE...... .F......
0,0-480,800}, event = KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_BUTTON_L1, scanCode=66, metaState=0, flags=0x8,
repeatCount=7, eventTime=384869, downTime=384065, deviceId=8, source=0x501 }
[  +51 ms] I/View    ( 3392): Key down dispatch to io.flutter.embedding.android.FlutterView{95573e9 VFE...... .F......
0,0-480,800}, event = KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_BUTTON_L1, scanCode=66, metaState=0, flags=0x8,
repeatCount=8, eventTime=384920, downTime=384065, deviceId=8, source=0x501 }
[  +49 ms] I/View    ( 3392): Key down dispatch to io.flutter.embedding.android.FlutterView{95573e9 VFE...... .F......
0,0-480,800}, event = KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_BUTTON_L1, scanCode=66, metaState=0, flags=0x8,
repeatCount=9, eventTime=384970, downTime=384065, deviceId=8, source=0x501 }
[  +50 ms] I/View    ( 3392): Key down dispatch to io.flutter.embedding.android.FlutterView{95573e9 VFE...... .F......
0,0-480,800}, event = KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_BUTTON_L1, scanCode=66, metaState=0, flags=0x8,
repeatCount=10, eventTime=385020, downTime=384065, deviceId=8, source=0x501 }
[  +50 ms] I/View    ( 3392): Key down dispatch to io.flutter.embedding.android.FlutterView{95573e9 VFE...... .F......
0,0-480,800}, event = KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_BUTTON_L1, scanCode=66, metaState=0, flags=0x8,
repeatCount=11, eventTime=385070, downTime=384065, deviceId=8, source=0x501 }
[  +25 ms] I/View    ( 3392): Key up dispatch to io.flutter.embedding.android.FlutterView{95573e9 VFE...... .F...... 0,0-480,800},
event = KeyEvent { action=ACTION_UP, keyCode=KEYCODE_BUTTON_L1, scanCode=66, metaState=0, flags=0x208, repeatCount=0,
eventTime=385093, downTime=384065, deviceId=8, source=0x501 }

**Comment by TahaTesser** [comment] 2021-07-21 10:56
@LiangHuangBC 
You cannot get raw key events from soft keyboard as explained https://github.com/flutter/flutter/issues/84925#issuecomment-865107014

There is no issue here if it is not possible

**Comment by LiangHuangBC** [comment] 2021-07-23 16:06
But is there a way to get soft keyboard key events?
