### ISSUE TITLE
Flicker Issue when using ListView and SingleChildScrollView

### ISSUE THREAD

**Issue by iSaqibShafique** [flutter/flutter#150987] opened 2024-06-28 16:30 UTC
### Steps to reproduce

When scrolling inside the ListView, getting graphics flicker issue.

### Expected results

Works normally

### Actual results

Flickering

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

class IndividualSignup extends StatelessWidget {
  const IndividualSignup({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        leadingWidth: 120,
        leading: OutlinedButton.icon(
          onPressed: () => GoRouter.of(context).pop(),
          label: const Text("Back"),
          icon: const Icon(Icons.arrow_back),
        ),
      ),
      body: ListView(
        padding: const EdgeInsets.only(top: 50, left: 50, right: 50),
        children: [
          const Center(
              child: TextWidget(
                  text: "Create Accout",
                  size: 32,
                  weight: FontWeight.w700,
                  color: AppColors.primary)),
          const Gap(10),
          Padding(
            padding: const EdgeInsets.symmetric(horizontal: 20),
            child: TextWidget(
              text: "Just a few details, and you are ready to start"
                  .toUpperCase(),
              size: 20,
              weight: FontWeight.w700,
              textAlign: TextAlign.center,
              color: AppColors.secondary,
            ),
          ),
          const Gap(30),
          const TextFormFieldWithText(),
          const Gap(20),
          const TextFormFieldWithText(
              heading: "Email Address", hint: "Enter a valid email address"),
          const Gap(20),
          const TextFormFieldWithText(
              heading: "Password", hint: "Use a strong password"),
          const Gap(30),
          CheckBoxWithText(
            isChecked: true,
            widget: Text.rich(
              TextSpan(
                children: List.generate(
                  2,
                  (index) => TextSpan(
                    text: index == 0 ? "You agreed to " : "Terms & Conditions",
                    style: style(
                      size: 16,
                      color: index == 0
                          ? Colors.black.withOpacity(.6)
                          : AppColors.primary,
                      weight: index == 1 ? FontWeight.w600 : null,
                    ),
                  ),
                ),
              ),
            ),
          ),
          const Gap(15),
          const CheckBoxWithText(text: "Send me marketing content"),
          const Gap(15),
          Watch((_) => CheckBoxWithText(
                text: "I have company code",
                isChecked: _controller.haveCompanyCode.value,
                onTap: () => _controller.onHaveCompanyCode(),
              )),
          Watch((_) => _controller.haveCompanyCode.value
              ? WhenHaveCompanyCode(
                  showInsight: _controller.showInsights,
                  onShowInsight: () => _controller.onShowInsights,
                )
              : const SizedBox()),
          const Gap(30),
          TextButton(onPressed: () {}, child: Text("signup".toUpperCase())),
        ],
      ),
    );
  }
}

https://github.com/flutter/flutter/assets/118008210/d18d1981-2f01-43ae-857a-41e0a251f82b

### Logs

Nothing found in Logs

### Flutter Doctor output

[✓] Flutter (Channel stable, 3.22.2, on macOS 14.5 23F79 darwin-x64, locale
    en-PK)
    • Flutter version 3.22.2 on channel stable at
      /Users/saqibshafique/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 761747bfc5 (3 weeks ago), 2024-06-05 22:15:13 +0200
    • Engine revision edd8546116
    • Dart version 3.4.3
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at /Users/saqibshafique/Library/Android/sdk
    • Platform android-35, build-tools 35.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.10+0-17.0.10b1087.21-11609105)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✗] Chrome - develop for the web (Cannot find Chrome executable at
    /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.10+0-17.0.10b1087.21-11609105)

[✓] VS Code (version 1.90.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.90.0

[✓] Connected device (2 available)
    • iPhone 15 Pro Max (mobile) • B2AF237B-B6B9-4127-87CB-5228B0C39C66 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-17-5 (simulator)
    • macOS (desktop)            • macos                                •
      darwin-x64 • macOS 14.5 23F79 darwin-x64

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

**Comment by jonahwilliams** [comment] 2024-06-28 17:37
Duplicate of https://github.com/flutter/flutter/issues/148660

**Closed by jonahwilliams** 2024-06-28 17:37 UTC

**Comment by iSaqibShafique** [comment] 2024-06-28 17:55
Not only on iOS Simulator but on Android
