### ISSUE TITLE
Flutter should provide access to Mozart's FrameInfo::presentation_time, possibly in BuildContext.

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#33216] opened 2019-05-22 20:51 UTC
Tracking item for [FL-222](https://fuchsia.atlassian.net/browse/FL-222) in Fuchsia's Jira repository.

**Comment by Hixie** [comment] 2019-06-04 17:21
Assigning to @goderbauer for the trivial framework-side fix, but the engine side will also need to be done.

**Comment by goderbauer** [comment] 2019-06-06 01:03
The framework-side of this change is done.

@cbracken Can anybody on the engine side verify 2) of FL-222?

**Comment by cbracken** [comment] 2019-06-17 18:30
Engine side work on this is blocked waiting for [FL-233](https://fuchsia.atlassian.net/browse/FL-233) to be resolved.

**Comment by goderbauer** [comment] 2019-07-03 22:10
I resubmitted the framework side of this.

**Comment by Hixie** [comment] 2019-08-20 23:23
Now https://bugs.fuchsia.dev/p/fuchsia/issues/detail?id=8810

**Comment by iskakaushik** [comment] 2019-12-03 00:19
Duplicate of https://github.com/flutter/flutter/issues/10850. Please re-open if I misunderstood the intent of this issue.

**Closed by iskakaushik** 2019-12-03 00:19 UTC
Labels: customer: fuchsia, engine, severe: customer critical
