### ISSUE TITLE
[ios] [flutter] GeneratedPluginRegistrant.m Module not found.

### ISSUE THREAD

**Issue by Xyz3R** [flutter/flutter#81204] opened 2021-04-26 14:24 UTC
I am having issues with a module not being found when trying to archive my app for distribution on iOS. This happens on my local machine and in the Codemagic CI.

I already tried all suggested solutions mentioned in https://github.com/flutter/flutter/issues/53573.
However, I did not have any success. The error persists, no matter what I try.

I have set my `MinimumOSVersion` to 13.0. I also set the specific entries for all flavours in my xcode workspace. (Screenshots below)

Things I already tried without success:
- setting the version to 10.0 instead of 13.0 (error persists)
- setting the version to 9.0 (firestore pod requires 10.0 in the most up2date version)
- enforcing the version in the podfile via `platform :ios, '13.0'`. I also tried it with 9.0 and 10.0. (error persists)
- pod deintegrate + delete Pods directory + removing podfile.lock & podfile. With version 9.0, 10.0 and 13.0 (error persists after rebuild)

## Steps to reproduce

1. Build the app via `flutter build ipa --release --flavor prod`
2. Open ios/Runner.xcworkspace  in xcode
3. Product -> archive

or simply run Codemagics CI with the default configuration (+signing set for app store distribution)

**This is currently stopping me from creating any release builds for iOS.**

## Logs

Error while archiving:
![image](https://user-images.githubusercontent.com/10122569/116096179-5aeb8380-a6a9-11eb-9ef5-bea6d4a873ce.png)

OS-Versions are set:
![image](https://user-images.githubusercontent.com/10122569/116096927-f7ae2100-a6a9-11eb-8f1c-82bcd46cd966.png)
![image](https://user-images.githubusercontent.com/10122569/116096974-0268b600-a6aa-11eb-8bbd-60afba945198.png)

## Podfile
```
# Uncomment this line to define a global platform for your project
# platform :ios, '13.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
```

## Flutter doctor -v:

```
[✓] Flutter (Channel stable, 2.0.5, on macOS 11.2.3 20D91 darwin-x64, locale en-GB)
    • Flutter version 2.0.5 at /Users/xyz3r/Development/sdks/flutter
    • Framework revision adc687823a (10 days ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/xyz3r/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_252-b09)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio
    • Android Studio at /Users/xyz3r/bin/idea/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Android Studio not found at /Users/xyz3r/bin/idea/Contents
    • Try updating or re-installing Android Studio.

[✓] IntelliJ IDEA Ultimate Edition (version 2021.1)
    • IntelliJ at /Users/xyz3r/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 55.1.5
    • Dart plugin version 211.7179

[✓] VS Code (version 1.53.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • sdk gphone x86 (mobile)    • emulator-5554                        • android-x86    • Android 11 (API 30) (emulator)
    • iPhone 12 Pro Max (mobile) • C3F90610-9177-4B93-AF65-878EC891F082 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 90.0.4430.85

! Doctor found issues in 1 category.
```

</details>

**Comment by TahaTesser** [comment] 2021-04-27 08:40
Hi @Xyz3R 
I just tried to reproduce the issue a flavors sample project with firestore.

```console
tahatesser@Tahas-MBP flavors_example % flutters build ipa --release  --flavor dev -t lib/main_dev.dart
Archiving com.nevercode.triage...
Automatically signing iOS for device deployment using specified development team in Xcode project: X8NNQ9CYL2
Running Xcode build...                                                  
 └─Compiling, linking and signing...                        26.3s
Xcode archive done.                                         490.1s
Built
/Users/tahatesser/AndroidStudioProjects/triage-examples/flutter_examples/flavors_example/build/ios/archive/Runner.xcarchive.
Building without sound null safety
For more information see https://dart.dev/null-safety/unsound-null-safety
tahatesser@Tahas-MBP flavors_example % 
```

<details> 
<summary>flutter doctor -v</summary> 

```console
[✓] Flutter (Channel stable, 2.0.5, on macOS 11.2.3 20D91 darwin-x64, locale
    en-GB)
    • Flutter version 2.0.5 at /Users/tahatesser/Code/flutter_stable
    • Framework revision adc687823a (11 days ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.
[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1
[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0
[✓] Connected device (4 available)
    • Taha's iPhone (mobile) • 00008020-001059882212002E            • ios
      • iOS 14.4.2
    • iPhone 12 (mobile)     • 83060656-28E7-44CD-801E-B11EC3EC89BA • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • macOS (desktop)        • macos                                • darwin-x64
      • macOS 11.2.3 20D91 darwin-x64
    • Chrome (web)           • chrome                               •
      web-javascript • Google Chrome 90.0.4430.93
• No issues found!
```
		
</details>

and the archive also works fine 

Please try to reproduce the issue without third-party packages. issue could be caused by flutterfire
Can you please provide steps from starting, step by step so we can follow and reproduce the issue
Thank you

**Comment by Xyz3R** [comment] 2021-04-29 08:15
I am trying to create a new project with a setup to reproduce this and step by step changes.
I will probably come back to this on the weekend with an update.

**Comment by pedromassangocode** [comment] 2021-05-21 08:18
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2021-05-21 08:18 UTC
Labels: in triage, waiting for customer response

**Comment by effortsteven** [comment] 2021-07-31 07:01
I am experiencing same problem and i have gone though all possible solution found in internet but still error persist.
