### ISSUE TITLE
AppBar Overlays notification bar while using curved bottom navigation.

### ISSUE THREAD

**Issue by Prthvii** [flutter/flutter#72779] opened 2020-12-22 05:52 UTC
**When i use curved bottom navigation bar, my appbar overlays the notification bar, only pages having bottom navigation have this issue, This is my code. Anyone have any idea?**

`import 'package:flutter/material.dart';
// import 'package:flutter_ecommerce_app/main.dart';
import 'package:flutter/cupertino.dart';
// import 'package:font_awesome_flutter/font_awesome_flutter.dart';
import 'package:curved_navigation_bar/curved_navigation_bar.dart';
import 'package:flutter_ecommerce_app/screens/ShoppingCartPage(p).dart';
import 'package:flutter_ecommerce_app/screens/HomeScreen.dart';
import 'package:flutter_ecommerce_app/screens/profilePage.dart';
import 'package:flutter_ecommerce_app/screens/OurStores.dart';
import 'package:flutter_ecommerce_app/screens/NotificationsScreen.dart';
import 'package:flutter_ecommerce_app/screens/circularMenuScreen.dart';
import 'package:circular_menu/circular_menu.dart';
import 'dart:math';
import 'newAppBarEmpty.dart';

class BottomNavBarWidget extends StatefulWidget {
  @override
  _BottomNavBarWidgetState createState() => new _BottomNavBarWidgetState();
}

class _BottomNavBarWidgetState extends State<BottomNavBarWidget> {
  int currentIndex = 0;
  GlobalKey _bottomNavigationKey = GlobalKey();
  final List<Widget> viewContainer = [
    HomeScreen(),
    notifications(),
    CircularMenuScreen(),
    CartScreen(),
    ProfilePage()
  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: EmptyAppBar(),
      primary: true,
      body: SafeArea(child: viewContainer[currentIndex]),
      bottomNavigationBar: CurvedNavigationBar(
        key: _bottomNavigationKey,
        index: currentIndex,
        height: 45.0,
        items: <Widget>[
          Icon(
            Icons.home,
          ),
          Icon(
            Icons.notifications_active_rounded,
          ),
          Container(
            width: 40,
            height: 40,
            child: Image.asset('assets/images/app-icon-logo.png'),
          ),
          Icon(
            Icons.shopping_cart,
          ),
          Icon(
            Icons.person,
          ),
        ],
        color: Colors.grey[300],
        buttonBackgroundColor: Colors.grey[300],
        backgroundColor: Colors.white60,
        animationCurve: Curves.fastOutSlowIn,
        animationDuration: Duration(milliseconds: 600),
        onTap: (index) {
          setState(() {
            currentIndex = index;
            print(currentIndex);
          });
        },
      ),
    );
  }
}

class EmptyAppBar extends StatelessWidget implements PreferredSizeWidget {
  @override
  Widget build(BuildContext context) {
    return Container();
  }

  @override
  Size get preferredSize => Size(0.0, 0.0);
}
`

**Comment by pedromassangocode** [comment] 2020-12-22 07:04
Hi @Prthvii
From what I can see, the issue is related to a 3rd party plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/rafalbednarczuk/curved_navigation_bar).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by pedromassangocode** 2020-12-22 07:04 UTC

**Comment by Prthvii** [comment] 2020-12-22 08:07
@pedromassangocode i haven't used any third party plugin other than curved navigation bar in this page. The issue is only there on the pages with bottom navigation.

**Comment by pedromassangocode** [comment] 2020-12-22 11:54
Hi @Prthvii 


> If you disagree, please write in the comments,
> providing your `flutter doctor -v`, your `flutter run -v`, your `pubspec.yaml`
> a minimal reproducible code sample that does not use 3rd party plugins,
> and I will reopen it.
