### ISSUE TITLE
Strange behavior of ListView when items get removed

### ISSUE THREAD

**Issue by tunymedia02** [flutter/flutter#85691] opened 2021-07-01 11:04 UTC
1.  Please tell us exactly how to reproduce the problem you are running into, and how you measured the performance.

Build a ListView where each Element consists of a Text with String A and a stateful widget which also builds a Text widget with String A like so:

```
ListView(
    children: _names
    .map((String name) => Row(
       children: [
       StatefulNameWidget(name: name),
       Text(name),
     ],
   ))
   .toList(),
 )
```
The StatefulNameWidget receives a String and passes it forward to its state like so:

```
class StatefulNameWidget extends StatefulWidget {
  final String name;

  const StatefulNameWidget({Key? key, required this.name}) : super(key: key);

  @override
  _StatefulNameWidgetState createState() =>
      _StatefulNameWidgetState(name: this.name);
}

class _StatefulNameWidgetState extends State<StatefulNameWidget> {
  final String name;

  _StatefulNameWidgetState({required this.name});

  @override
  Widget build(BuildContext context) {
    return Text(this.name);
  }
}
```
If you now add strings to the _names list, we see rows where each consists of two times the string (which is working fine). For example if my _names list is ['A','B','C'], I see:
```
AA
BB
CC
```
But if i now remove the first item (so that the list becomes ['B','C']) and call setState, the output is the following:
```
AB
BC
```
instead of:
```
BB
CC
```
So there is still a StatefulNameWidget with the string 'A' rendered, even tough the 'A' does not exist in the list anymore. Is this the intended behavior?

If i return ```Text(widget.name)``` inside the build method, the output is as expected. Also if i use a StatelessWidget, the output is as expected ('BB\nCC'). (See attached main.dart file)

2.  Please attach a small application (ideally just one main.dart file) that
     reproduces the problem. You could use https://gist.github.com/ for this.

https://gist.github.com/tunymedia02/a65d805af58a372942f25e40a41dfeb3

**Comment by maheshmnj** [comment] 2021-07-06 06:56
Hi @tunymedia02,
Thanks for filing the issue it looks like it is the expected behaviour, When you pass on the value to the widget for the first time,  

```
StatefulNameWidget(name: name)
``` 
 
 the widget is created and the value is being stored in the state by calling create state.
 
```
 @override
  _StatefulNameWidgetState createState() =>
      _StatefulNameWidgetState(name: this.name);
}
```

which basically maintains the state and it is only called in these scenarios
[ taken from the docs](https://api.flutter.dev/flutter/widgets/StatefulWidget/createState.html)

>The framework can call this method multiple times over the lifetime of a StatefulWidget. For example, if the widget is inserted into the tree in multiple locations, the framework will create a separate State object for each location. Similarly, if the widget is removed from the tree and later inserted into the tree again, the framework will call createState again to create a fresh State object, simplifying the lifecycle of State objects.

so when you are try to access ```this.name``` in your ```StatefulNameWidget```

```
return Text(
      this.name,  // it will always return the initial value stored in the state and not the one updated via setState 
    );
```
if you need the updated value you could either  access it like this 

```
return Text(
      widget.name, 
    );
```
or add a uniqueKey to your ```StatefulNameWidget``` widget so that when the setState is called uniquekey is assigned everytime and ```createState``` is called on each setState to update the state value

```
 StatefulNameWidget(
   name: name,
   key: UniqueKey(),
  ), 
```

So I am going to close this issue considering it to be invalid, if you disagree feel free to write back, if the argument stands valid I will reopen it.

Thank you.

**Closed by maheshmnj** 2021-07-06 06:56 UTC
Labels: in triage
