### ISSUE TITLE
iOS: TextField can't input after pop back with a swipe gesture

### ISSUE THREAD

**Issue by DeanFs** [flutter/flutter#149032] opened 2024-05-24 08:41 UTC
### Steps to reproduce

1. Add TextField, button in page A
2. Click the button to push to page B
3. Return to page A from page B with a swipe gesture
4. Click on TextField in page A

### Expected results

The keyboard should pop up when you perform step 4

### Actual results

When executing step 4, there is no response when clicking the TextField, and the keyboard does not pop up.

### Code sample

<details open><summary>Code sample</summary>

```dart
class A extends StatefulWidget {
  const A({super.key});
  
  @override
  State<A> createState() => _AState();
}

class _AState extends State<A> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: const Text("Demo"),
      ),
      body: Center(
        child: Column(
          children: [
            const TextField(
              maxLength: 10,
              maxLines: 1,
              style: TextStyle(fontSize: 14),
              decoration: InputDecoration(
                  contentPadding: EdgeInsets.symmetric(horizontal: 6),
                  counterText: "",
                  hintText: "Please Input",
                  border: InputBorder.none),
            ),
            InkWell(
              onTap: () {
                Navigator.push(
                  context,
                  MaterialPageRoute(builder: (context) => const B()),
                );
              },
              child: Container(color: Colors.red, height: 40, width: 100),
            ),
          ],
        ),
      ),
    );
  }
}

class B extends StatefulWidget {
  const B({super.key});

  @override
  State<B> createState() => _BState();
}

class _BState extends State<B> {
  @override
  Widget build(BuildContext context) {
    return const Placeholder();
  }
}
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.22.1, on macOS 14.5 23F79 darwin-x64, locale
    zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2020.1)
[✓] VS Code (version 1.89.1)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by louislamme** [comment] 2024-05-24 10:21
Related to issue #148573, #148867?

**Comment by darshankawar** [comment] 2024-05-24 10:59
@DeanFs This is a duplicate of https://github.com/flutter/flutter/issues/148867 and per [verification](https://github.com/flutter/flutter/issues/148867#issuecomment-2128629306), it works properly in master but not in latest stable. 
Closing as such.

**Closed by darshankawar** 2024-05-24 10:59 UTC
Labels: in triage

**Comment by DeanFs** [comment] 2024-05-25 07:07
> @DeanFs This is a duplicate of #148867 and per [verification](https://github.com/flutter/flutter/issues/148867#issuecomment-2128629306), it works properly in master but not in latest stable. Closing as such.


After I switched to Channel master, 3.22.0-45.0.pre, extended_text was incompatible and an exception was thrown during compilation: "Error (Xcode): ../../../.pub-cache/hosted/pub-web .flutter-io.cn/extended_text-13.0.0/lib/src/extended/text_overflow_mixin.dart:882:31: Error: The method 'TextOverflowMixin.layoutInlineChildren' has fewer positional arguments than those of overridden method 'RenderBox with ContainerRenderObjectMixin, RenderInlineChildrenContainerDefaults.layoutInlineChildren'."
I see there is no new version available for extended_text
