### ISSUE TITLE
Webview goes blank when redirecting to another local html file or anchors inside the same html file

### ISSUE THREAD

**Issue by kakyoism** [flutter/flutter#65379] opened 2020-09-08 11:02 UTC
## Steps to Reproduce

I'm using webview to show localized html files. In each HTML file there are  `href` links to redirect to corresponding language files. I'm using this little class below to show the HTML as a page.

```dart
with this little class
class LocalLoader {
  Future<String> loadLocal(String filename) async {
    return await rootBundle.loadString('assets/$filename');
  }
}
class HtmlPage extends StatelessWidget {
  final Completer<WebViewController> controller;
  final String htmlFile;
  HtmlPage({
    @required this.htmlFile,
    @required this.controller,
  });
  @override
  Widget build(BuildContext context) {
    return Container(
      child: FutureBuilder<String>(
        future: LocalLoader().loadLocal(htmlFile),
        builder: (context, snapshot) {
          if (snapshot.hasData) {
            return WebView(
              debuggingEnabled: true,
              initialUrl: Uri.dataFromString(snapshot.data,
                  mimeType: 'text/html',
                  // CAUTION
                  // - required for non-ascii chars
                  encoding: Encoding.getByName("UTF-8")
              ).toString(),
              javascriptMode: JavascriptMode.unrestricted,
              onWebViewCreated: (WebViewController webViewController) {
                // CAUTION
                // - avoid exception "Bad state: Future already completed"
                if(!controller.isCompleted) {
                  controller.complete(webViewController);
                }
              },
            );
          } else if (snapshot.hasError) {
            return Text("${snapshot.error}");
          } else {
            print('undefined behaviour');
          }
          return CircularProgressIndicator();
        },
      ),);
  }
}
class HelpPage extends HtmlPage {
  HelpPage(ctrl) : super(htmlFile: 'help_en.html', controller: ctrl);
}

class AboutPage extends HtmlPage {
  AboutPage(ctrl) : super(htmlFile: 'about_en.html', controller: ctrl);
}

```

And the relevant html code looks like this in each language files

```html
<p><span style="font-size: 20px;"><a href="help_en.html">English</a></span> <span class="math inline">    </span> <span style="font-size: 20px;"><a href="help_fr.html">Français</a></span></p>
```

## Repro 1

Open my app

1. Place `help_en.html` and `help_fr.html` in `assets` folder, and add the corresponding yaml section.
2. Load the initial page "help_en.html" and it shows correctly
3. Click the `Français` link on the page

**Expected results:** 

We should see the `help_fr.html` upon clicking its redirection link.

**Actual results:** 

We see a blank page

## Repro 2

I suspected it may have been a relative path error.  So I modified the HTML page so that the href looks like

```html
<p><span style="font-size: 20px;"><a href="assets/help_en.html">English</a></span> <span class="math inline">    </span> <span style="font-size: 20px;"><a href="assets/help_fr.html">Français</a></span></p>
```

But the result is the same as in Repro 1.

<details>
  <summary>Logs</summary>

```
E/InputMethodManager(24228): b/117267690: Failed to get fallback IMM with expected displayId=215 actual IMM#displayId=0 view=io.flutter.plugins.webviewflutter.InputAwareWebView{f259a5f VFEDHVC.. .F...... 0,0-2075,706}
E/InputMethodManager(24228): b/117267690: Failed to get fallback IMM with expected displayId=215 actual IMM#displayId=0 view=io.flutter.plugins.webviewflutter.InputAwareWebView{f259a5f VFEDHVC.. .F...... 0,0-2075,706}

```

No `flutter analyze` errors
```
```

```
$ flutter doctor -v
[✓] Flutter (Channel dev, 1.22.0-9.0.pre, on Mac OS X 10.15.6 19G2021, locale en-CN)
    • Flutter version 1.22.0-9.0.pre at /Applications/flutter
    • Framework revision 7a43175198 (10 days ago), 2020-08-28 23:18:04 -0400
    • Engine revision 07e2520d5d
    • Dart version 2.10.0 (build 2.10.0-73.0.dev)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Applications/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • ANDROID_HOME = /Applications/Android/sdk
    • ANDROID_SDK_ROOT = /Applications/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.7, Build version 11E801a
    • CocoaPods version 1.9.1

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.48.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[✓] Connected device (2 available)
    • ONEPLUS A6000 (mobile)   • <my udid>                                 • android-arm64 • Android 10 (API 29)
    • MyiPhone (mobile) •<my udid> • ios           • iOS 13.6.1
    ! Device emulator-5554 is offline.

• No issues found!
```

</details>

**Comment by pedromassangocode** [comment] 2020-09-08 11:43
I was able to reproduce this issue with the latest version of the plugin (`webview_flutter: ^0.3.22+1`).

<details><summary>sample code</summary>

```
import 'dart:async';
import 'dart:convert';

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:webview_flutter/webview_flutter.dart';

void main() => runApp(MaterialApp(home: Scaffold(body: Padding(
  padding: EdgeInsets.only(top: 50),
  child:   HtmlPage(
    htmlFile: 'help_en.html',
  ),
))));

class LocalLoader {
  Future<String> loadLocal(String filename) async {
    return await rootBundle.loadString('assets/$filename');
  }
}
class HtmlPage extends StatelessWidget {
  final Completer<WebViewController> controller = Completer();
  final String htmlFile;

  HtmlPage({@required this.htmlFile});

  @override
  Widget build(BuildContext context) {
    return Container(
      margin: EdgeInsets.only(top: 100),
      child: FutureBuilder<String>(
        future: LocalLoader().loadLocal(htmlFile),
        builder: (context, snapshot) {
          if (snapshot.hasData) {
            return WebView(
              debuggingEnabled: true,
              initialUrl: Uri.dataFromString(snapshot.data,
                  mimeType: 'text/html',
                  // CAUTION
                  // - required for non-ascii chars
                  encoding: Encoding.getByName("UTF-8")
              ).toString(),
              javascriptMode: JavascriptMode.unrestricted,
              navigationDelegate: (error) async {
                print(error.url);
                return NavigationDecision.navigate;
              },
              onWebViewCreated: (WebViewController webViewController) {
                // CAUTION
                // - avoid exception "Bad state: Future already completed"
                if(!controller.isCompleted) {
                  controller.complete(webViewController);
                }
              },
            );
          } else if (snapshot.hasError) {
            return Text("${snapshot.error}");
          } else {
            print('undefined behaviour');
          }
          return CircularProgressIndicator();
        },
      ),);
  }
}

```
</details>

<details><summary>Logs</summary>

```
Syncing files to device sdk gphone x86 arm...
V/InputMethodManager(11153): b/117267690: Failed to get fallback IMM with expected displayId=12 actual IMM#displayId=0 view=io.flutter.plugins.webviewflutter.InputAwareWebView{1fe638d VFEDHVC.. .F...... 0,0-1080,1676}
E/chromium(11153): [ERROR:aw_browser_terminator.cc(125)] Renderer process (11621) crash detected (code -1).
Restarted application in 1,689ms.
I/flutter (11153): undefined behaviour
V/InputMethodManager(11153): b/117267690: Failed to get fallback IMM with expected displayId=13 actual IMM#displayId=0 view=io.flutter.plugins.webviewflutter.InputAwareWebView{7959a08 VFEDHVC.. .F...... 0,0-1080,1676}
I/flutter (11153): about:blank#blocked
V/InputMethodManager(11153): b/117267690: Failed to get fallback IMM with expected displayId=13 actual IMM#displayId=0 view=io.flutter.plugins.webviewflutter.InputAwareWebView{7959a08 VFEDHVC.. .F...... 0,0-1080,1676}

```
</details>

<details><summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.22.0-10.0.pre.88, on Mac OS X 10.15.6 19G2021, locale en)
    • Flutter version 1.22.0-10.0.pre.88 at /Users/pedromassango/dev/SDKs/flutter_master
    • Framework revision e10bdbbd9d (17 hours ago), 2020-09-07 11:40:03 -0700
    • Engine revision ac8b9c4c52
    • Dart version 2.10.0 (build 2.10.0-86.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.7, Build version 11E801a
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2020.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 48.1.4
    • Dart plugin version 202.7206

[✓] VS Code (version 1.48.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[✓] Connected device (4 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • macOS (desktop)             • macos         • darwin-x64     • Mac OS X 10.15.6 19G2021
    • Web Server (web)            • web-server    • web-javascript • Flutter Tools
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 85.0.4183.83

! Doctor found issues in 1 category.
```
</details>

**Comment by kakyoism** [comment] 2020-09-08 13:53
I dug further and thought this might be related to #27086, but it turned out to be even worse, see below:

To work around this issue, I thought about merging `help_en.html` and `help_fr.html` and turn the href's into anchors in the same html file. However, to my surprise, this didn't work either! I still see blank pages when trying to go to the anchors. The same anchors work fine in an Electron test app and in the browsers.

So to me this is beyond the fuss of running an http server to work around a very simple webpage doc. It is actually a much more serious bug to me.

**Comment by pedromassangocode** [comment] 2020-09-08 14:10
Hi @kakyoism 
I will close this as a duplicate of https://github.com/flutter/flutter/issues/27086 so that is easy to keep track of this issue.
Thank you

**Comment by kakyoism** [comment] 2020-09-08 14:35
> Hi @kakyoism
> I will close this as a duplicate of #27086 so that is easy to keep track of this issue. Please follow up on that issue for updates.
> 
> Thank you

May I suggest that this should stay as a separate issue? Please see my latest comment. The problem is that the webview does not even redirect correctly to **the anchors in the same html file**, while #27086 only talks about linking to a local asset from html. My finding is clearly a different symptom.

**Comment by pedromassangocode** [comment] 2020-09-09 07:00
Hi @kakyoism

**Comment by e-oj** [comment] 2020-11-26 11:41
Any updates on this issue? I'm getting the same error when I set the initial url to a twitch oauth url: https://id.twitch.tv/oauth2/authorize?client_id=fx9d4xcwzswjzwt8cfzj8lh8paphdu&redirect_uri=https://www.eswagers.com/oauth&state=twitchAuth&scope=user:read:email&response_type=token

```dart
WebView authenticate({@required Function onDone}){
    String authUrl = '$baseUrl'
        '?client_id=$clientID'
        '&redirect_uri=$redirectUri'
        '&state=$state'
        '&scope=$scope'
        '&response_type=token';

    print('auth url: $authUrl');
    if (Platform.isAndroid) WebView.platform = SurfaceAndroidWebView();

    return WebView(
      initialUrl: authUrl,
      onPageStarted: (url) async {
        if (url.startsWith(redirectUri)){
          String token = _getToken(url);
          onDone(token);
        }
      },
    );
  }
```

**Comment by aleripe** [comment] 2020-12-29 11:09
No updates? This greatly impacts my app...

**Comment by danagbemava-nc** [comment] 2021-08-11 09:53
The issue is reproducible on `master 2.5.0-6.0.pre.46` and `stable 2.2.3` with `webview_flutter: ^2.0.12`.

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 2.5.0-6.0.pre.46, on macOS 11.5.1 20G80 darwin-arm,
    locale en-GH)
    • Flutter version 2.5.0-6.0.pre.46 at /Users/nexus/dev/sdks/flutters
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 41ff30c871 (16 minutes ago), 2021-08-10 23:03:48 -0700
    • Engine revision 4fef55db10
    • Dart version 2.14.0 (build 2.14.0-385.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.59.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554                        •
      android-arm64  • Android 12 (API 31) (emulator)
    • iPhone 12 (mobile)          • F2592D43-5FE3-46BB-8A2B-A38BA468DCE9 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • Chrome (web)                • chrome                               •
      web-javascript • Google Chrome 92.0.4515.131

• No issues found!
```

```
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.5.1 20G80 darwin-arm, locale
    en-GH)
    • Flutter version 2.2.3 at /Users/nexus/dev/sdks/flutter
    • Framework revision f4abaa0735 (6 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.59.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554                        •
      android-arm64  • Android 12 (API 31) (emulator)
    • iPhone 12 (mobile)          • F2592D43-5FE3-46BB-8A2B-A38BA468DCE9 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • Chrome (web)                • chrome                               •
      web-javascript • Google Chrome 92.0.4515.131

• No issues found!
```
</details>

**Comment by giorgio79** [comment] 2022-06-27 05:21
As a workaround, just use full hyperlinks, and capture them with navigationDelegate (seen in the example https://pub.dev/packages/webview_flutter/example)

**Comment by stuartmorgan** [comment] 2023-05-21 17:38
Closing as obsolete; the error shown is specific to data URLs, and we now have API for loading files and assets that don't rely on data URL workarounds.

**Closed by stuartmorgan** 2023-05-21 17:38 UTC
Labels: plugin, a: assets, p: webview, has reproducible steps, P4, found in release: 2.2, found in release: 2.5

**Comment by giorgio79** [comment] 2023-05-21 18:29
So we can use anchor links?
