### ISSUE TITLE
[image_picker] app crashes when rotating the device at a specific moment

### ISSUE THREAD

**Issue by caylab** [flutter/flutter#102364] opened 2022-04-22 10:06 UTC
When rotating the device just before or after the `getImage()` method of the `image_picker` plugin is called, the app occasionally crashes. The camera however remains open until it is closed or a photo is taken.

This seems to be primarily an Android related issue since we were not able to reproduce it on an iOS device.

We are using image_picker v0.6.7+22 as we are still in the process of migrating our app to null-safety. So if this issue has been known and is already fixed, it would be very helpful to know the related issue.

But we encountered this issue quite often on a Galaxy Tab S5e. Unfortunately, it is quite hard to reproduce this since the timeing must be very precise. Further more, we were not able to find a specific point in the dart code of the `image_picker` plugin, to which we could debug and before/after which this issue is garanteed to happen. So we assume, this issue is rooted in the platform specific implementation of the plugin.

The device's speed - be it due to the hardware or low battery - might also have an influence on the likelyhood of this happening.

**Comment by stuartmorgan** [comment] 2022-04-22 10:15
See https://github.com/flutter/flutter/issues/48016#issuecomment-971918009

Closing as a duplicate of that issue.

**Closed by stuartmorgan** 2022-04-22 10:15 UTC
