### ISSUE TITLE
APNGs are not decoded/rendered correctly

### ISSUE THREAD

**Issue by Craftplacer** [flutter/flutter#130665] opened 2023-07-15 15:10 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Use the Image widget to display one of the affected APNGs

### Expected results

The APNG is animates with transparency as it is intended to

### Actual results

The APNG contains an unwanted background.

### Code sample

<details><summary>Code sample</summary>

```dart
Image.network("https://user-images.githubusercontent.com/120563837/253730206-ce9149bb-b2c6-425a-a013-ee2b20612c93.png"),
Image.network("https://user-images.githubusercontent.com/120563837/253730258-c48d3ec6-2130-4023-af01-06d88c04621a.png"),
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

**Rendered in Flutter 3.11.0-2.0.pre.42**: (notice the white box within the pink background)
![image](https://github.com/flutter/flutter/assets/22963120/1dc351ea-fb60-4dcf-aee1-3f51f9460143)

**Firefox**:
![image](https://github.com/flutter/flutter/assets/22963120/0e092a31-1d07-44d6-a08e-5df5de65090a)

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel master, 3.11.0-2.0.pre.42, on Void Linux 6.3.10_1, locale en_US.UTF-8)
    • Flutter version 3.11.0-2.0.pre.42 on channel master at /home/craftplacer/.local/lib/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d5df458684 (2 months ago), 2023-05-06 02:21:14 +0530
    • Engine revision 6b467df16e
    • Dart version 3.1.0 (build 3.1.0-81.0.dev)
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /home/craftplacer/.local/lib/android-sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /home/craftplacer/.local/lib/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /usr/bin/chromium

[✓] Linux toolchain - develop for Linux desktop
    • clang version 15.0.7
    • cmake version 3.26.4
    • ninja version 1.11.1
    • pkg-config version 0.29.2

[✓] Android Studio (version 2021.3)
    • Android Studio at /home/craftplacer/.local/lib/android-studio
    • Flutter plugin version 71.2.3
    • Dart plugin version 213.7433
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Community Edition (version 2022.2)
    • IntelliJ at /usr/lib/intellij-idea
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin version 222.4167.21

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Void Linux 6.3.10_1
    • Chrome (web)    • chrome • web-javascript • Chromium 114.0.5735.106

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

</details>

**Comment by stuartmorgan** [comment] 2023-07-15 15:12
Closing as a duplicate of https://github.com/flutter/flutter/issues/128102

**Closed by stuartmorgan** 2023-07-15 15:12 UTC
