### ISSUE TITLE
[web] AutofillHints not capturing username in web browsers

### ISSUE THREAD

**Issue by MyBuzzTechnologies** [flutter/flutter#83265] opened 2021-05-24 16:01 UTC
When using AutofillHints on a Form widget with 2 TextFormField() widgets set to have AutofillHints = [AutofillHints.username] and [AutofillHints.password] (i.e. standard login form), after these are used, Google Chrome (and Safari) offers to save the credentials but the username is never captured correctly so is empty in the password save pop-up.

My Form code is as follows (abbreviated):
```dart
Form(
    key: _formKey,
    child: Column(children: [
        TextFormField(
              controller: _usernameController,
              keyboardType: TextInputType.emailAddress,
              autocorrect: false,
              autofocus: true,
              autofillHints: const [AutofillHints.username],
            ),
        TextFormField(
                    controller: _passwordController,
                    obscureText: _passwordHidden,
                    autocorrect: false,
                    autofillHints: const [AutofillHints.password],
                    onFieldSubmitted: (value) => _signInPressed(),
                  ),
        ]),
```

The pop-up in Chrome after the route of the app changes is:
![Screenshot 2021-05-18 at 13 58 13](https://user-images.githubusercontent.com/37405280/119374054-07248800-bcb1-11eb-800d-f171ea993790.png)

The username is always blank yet password is always captured correctly using the above code.

Doctor summary (to see all details, run flutter doctor -v):
```console
[✓] Flutter (Channel beta, 2.2.0-10.3.pre, on macOS 11.3 20E232 darwin-arm, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - Version 90.0.4430.212 (Official Build) (x86_64 translated)
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.56.2)
```

**Comment by TahaTesser** [comment] 2021-05-25 10:33
Hi @MyBuzzTechnologies 
Thanks for filing the issue, I can reproduce the issue on macOS & windows chrome

Reproduced the issue using the following minimal code sample 

<details> 
<summary>minimal code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatefulWidget {
  @override
  _HomeState createState() => _HomeState();
}

class _HomeState extends State<Home> {
  final _formKey = GlobalKey<FormState>();
  TextEditingController _usernameController = TextEditingController();
  TextEditingController _passwordController = TextEditingController();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: Form(
          key: _formKey,
          child: Column(children: [
            TextFormField(
              controller: _usernameController,
              keyboardType: TextInputType.emailAddress,
              autocorrect: false,
              autofocus: true,
              autofillHints: const [AutofillHints.username],
            ),
            TextFormField(
              controller: _passwordController,
              obscureText: true,
              autocorrect: false,
              autofillHints: const [AutofillHints.password],
              onFieldSubmitted: (value) => {},
            ),
          ]),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () => _formKey.currentState.validate(),
      ),
    );
  }
}

``` 

</details>

Reproduced on the following channels
|  `stable`  | `master` |
| :---: |:---: |
|  ❌  |   ❌  | 

Check `flutter doctor -v` outputs for each channel below

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.2.0, on macOS 11.3.1 20E241 darwin-x64, locale
    en-GB)
    • Flutter version 2.2.0 at /Users/tahatesser/Code/flutter_stable
    • Framework revision b22742018b (10 days ago), 2021-05-14 19:12:57 -0700
    • Engine revision a9d88a4d18
    • Dart version 2.13.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.56.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.22.0

[✓] Connected device (3 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios            • iOS
      14.6
    • macOS (desktop)        • macos                     • darwin-x64     •
      macOS 11.3.1 20E241 darwin-x64
    • Chrome (web)           • chrome                    • web-javascript •
      Google Chrome 90.0.4430.212

• No issues found!
```

```console
[✓] Flutter (Channel master, 2.3.0-13.0.pre.145, on macOS 11.3.1 20E241
    darwin-x64, locale en-GB)
    • Flutter version 2.3.0-13.0.pre.145 at
      /Users/tahatesser/Code/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fdb1fb184d (5 hours ago), 2021-05-24 22:04:02 -0700
    • Engine revision b1385c0df1
    • Dart version 2.14.0 (build 2.14.0-145.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.1.1)
    • IntelliJ at /Volumes/Extreme/IntelliJ IDEA CE.app
    • Flutter plugin version 56.0.5
    • Dart plugin version 211.7233

[✓] VS Code (version 1.56.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.22.0

[✓] Connected device (3 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios            • iOS
      14.6
    • macOS (desktop)        • macos                     • darwin-x64     •
      macOS 11.3.1 20E241 darwin-x64
    • Chrome (web)           • chrome                    • web-javascript •
      Google Chrome 90.0.4430.212

• No issues found!

```
		
</details>

✅ : No Issue ❌: has Issue

**Comment by yjbanov** [comment] 2021-05-27 22:16
As a test, what happens if you fill out password first and username second? Is the username captured but not the password?

**Comment by TahaTesser** [comment] 2021-05-28 14:37
@yjbanov 
The same result, only password is captured

**Comment by darshankawar** [comment] 2022-02-03 13:08
I verified this issue since a [similar](https://github.com/flutter/flutter/issues/97653) one was closed in favor of this.

Using the code sample provided [here](https://github.com/flutter/flutter/issues/83265#issuecomment-847754592), the issue still persists on latest stable and master. 

But, if we wrap `Form` with `AutofillGroup`, then, on latest master, the `username` is captured as expected:

<img width="1121" alt="Screenshot 2022-02-03 at 4 47 02 PM" src="https://user-images.githubusercontent.com/67046386/152347701-9c664d01-08af-40f3-ac49-d67bf9a4a7a4.png">

And the same was observed in the closed issue: https://github.com/flutter/flutter/issues/97653#issuecomment-1028651219

This only works on latest master though, whereas, on stable, it still shows `username` as blank using above change:

<img width="1121" alt="Screenshot 2022-02-03 at 4 59 27 PM" src="https://user-images.githubusercontent.com/67046386/152347909-d4ba7685-1404-44a1-acde-a83d6faf5090.png">

@LongCatIsLooong Can you please confirm if wrapping `Form` with `AutofillGroup` can be considered as an acceptable solution ? Accordingly, we can update this issue to reflect current and correct status.

Updated code snippet to make it work on latest master:

```
body: Center(
        child: AutofillGroup(
          child: Form(
            key: _formKey,
            child: Column(children: [
```

<details>
<summary> master, stable flutter doctor -v </summary>

```

[✓] Flutter (Channel master, 2.10.0-1.0.pre.402, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-GB)
    • Flutter version 2.10.0-1.0.pre.402 at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ac52901c14 (86 minutes ago), 2022-02-02 19:28:25 -0800
    • Engine revision baadc162a9
    • Dart version 2.17.0 (build 2.17.0-79.0.dev)
    • DevTools version 2.10.0

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • Mac OS X 10.15.4 19E2269
      darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 97.0.4692.99

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

[✓] Flutter (Channel stable, 2.8.1, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.8.1 at /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (7 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.0.0.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (4 available)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 97.0.4692.99

! Doctor found issues in 1 category.

```

</details>

**Comment by masus04** [comment] 2022-08-03 11:11
Are there any updates on this issue?

**Comment by coman3** [comment] 2023-02-26 02:28
Still seeing this in the latest flutter, with an AutofillGroup and nested Form surrounding both text fields.

Any thoughts / updates on how we can fix this?

**Comment by zs-dima** [comment] 2023-02-28 09:45
The same issue
FLUTTER_WEB_USE_SKIA=true

**Comment by mdebbar** [comment] 2023-08-10 18:30
Is this issue still happening today?

**Comment by masus04** [comment] 2023-08-17 11:23
For me this issue still persists on Flutter Web.

**Closed** 2023-08-31 19:07 UTC
Labels: a: text input, waiting for customer response, framework, engine, f: material design, platform-web, has reproducible steps, found in release: 2.3, team-web, multiteam-retriage-candidate
