### ISSUE TITLE
Flutter build with 3.22 for iOS failing: The method 'scheduleWarmUpFrame' isn't defined for the class 'PlatformDispatcher'.

### ISSUE THREAD

**Issue by geokala** [flutter/flutter#148414] opened 2024-05-15 14:12 UTC
### Steps to reproduce

I'm trying to build an app (source not currently externally available unfortunately) for iOS, but it fails with the error
`The method 'scheduleWarmUpFrame' isn't defined for the class 'PlatformDispatcher'.`

I'm not sure where to begin debugging this or making a minimal repro, as we don't directly call this function, and it sounds like this is part of flutter rather than something third party (per https://api.flutter.dev/flutter/dart-ui/PlatformDispatcher-class.html).

The command used to build was: `flutter -v build ipa --no-codesign --release --flavor Release`

Versions of flutter, macOS, and Xcode are: [✓] Flutter (Channel stable, 3.22.0, on macOS 13.6.3 22G436 darwin-x64, locale en-US)
                     [✓] Xcode - develop for iOS and macOS (Xcode 15.2)

Build target is iOS 11, which complains it is unsupported (so could be the issue), but was working until recently.
The most recent successful build we have is from a few days ago where the only difference was the flutter version being 3.19.6.

### Expected results

Flutter iOS app builds.

### Actual results

Flutter iOS app fails to build with:
[  +21 ms] Error (Xcode): [+4068 ms] /path/to/build/dir/packages/flutter/lib/src/scheduler/binding.dart:1028:33: Error: The method 'scheduleWarmUpFrame' isn't defined for the class 'PlatformDispatcher'.

### Code sample

Can't currently provide this as noted in the description.

### Screenshots or Video

NA

### Logs

Logs not currently available.

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.22.0, on macOS 13.6.3 22G436 darwin-x64, locale en-US)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[!] Android Studio (not installed)
[✓] Connected device (1 available)
[✓] Network resources

! Doctor found issues in 3 categories.
```

</details>

**Comment by darshankawar** [comment] 2024-05-16 07:43
Thanks for the report @geokala 


> The method 'scheduleWarmUpFrame' isn't defined for the class 'PlatformDispatcher'.

It seems the method is part of the class and is present per https://github.com/flutter/engine/blob/9bc449ee2e8bfbd97ab1d56c98837e39cda0289a/lib/ui/platform_dispatcher.dart#L833



> Build target is iOS 11,

Per documentation, supported ios versions starts from 12 : https://docs.flutter.dev/reference/supported-platforms
Can you try to change it to 12 and run your scenario again to check if you still get same error or not ?

**Comment by geokala** [comment] 2024-05-16 10:34
I've forced the minimum version to be 12 and am not seeing the warning about iOS version any more.

However, the scheduleWarmUpFrame error is still occurring. Do you have any recommendations for troubleshooting further?

From looking at the logs, I also see that analytics were sent- I'm not sure if that's something you have access to (or what is actually sent and thus whether it can be helpful).

**Comment by darshankawar** [comment] 2024-05-17 05:54
Thanks for the update. The method `scheduleWarmUpFrame` was added as part of https://github.com/flutter/engine/pull/50570 which also made it to 3.22.0, so I am not sure why it could be resulting in the error.
I'll keep the issue open for team's input / attention.

/cc @dkwingsmt

**Comment by geokala** [comment] 2024-05-17 09:08
Sounds good. I've temporarily pinned our iOS build to 3.19.6 but if there's any more investigation I can do, let me know and I'll fit it in as soon as I can.

**Comment by dkwingsmt** [comment] 2024-05-17 13:15
This should has nothing to do with `scheduleWarmUpFrame`, but is caused by an outdated `dart:ui` library. Can you show me the command you used to switch to 3.22? Anyway, can you try `flutter upgrade`?

**Comment by geokala** [comment] 2024-05-17 13:17
The commands used to ensure the flutter dir was up to date were:
`        rm -rf /tmp/flutter-ios
        git clone https://github.com/flutter/flutter.git -b stable /tmp/flutter-ios
        /tmp/flutter-ios/bin/flutter channel stable
`

I'll try them with a flutter upgrade tacked onto the end in case that helps and let you know.

**Comment by vishna** [comment] 2024-05-18 10:11
after upgrading to 3.22.0 I've deleted `build` folder and that fixed it for me

**Comment by geokala** [comment] 2024-05-20 13:18
I believe that the system this is happening on has a clean build directory every time but I will double check that.

 Also, I believe the system in question might be running on x86_64 rather than the newer m1 (arm? I don't recall). Might that have an impact?

I can't access the system right at this moment but as noted, I'll check the build dir tomorrow and look to confirm whether it's x86_64.

**Comment by jonahwilliams** [comment] 2024-05-20 17:53
If this is consistently broken it might be an issue with the downloaded SDK or a tooling bug.

**Comment by joelpramos** [comment] 2024-05-20 20:31
Just stumbled upon the same issue... following on the thread below it appears my VS Code is running dart instead of flutter.

https://stackoverflow.com/questions/52483773/dartui1-error-not-found-dartui-flutter-dart

Running `flutter run main.dart` instead of using debugger from VSCode seems to have done the trick. Should be something that's "confusing" the IDE to run the app using the dart command.

**Comment by geokala** [comment] 2024-05-21 15:07
OK, I've had another look, adding the following commands before the build command:
`rm -rf build`
`flutter clean`
`flutter pub cache clean`
`flutter pub get`
`flutter -v build ipa --no-codesign --release --flavor Release`
That results in xcode faffing around for a while and then a different error: ../../../.pub-cache/hosted/pub.dev/win32-5.5.1/lib/win32.dart:1:1: Error: The specified language version is too high. The highest supported language version is 3.3.
Given that pub.dev tells me that 5.5.1 targets 3.4, and all the other systems we have using this are working fine, something seems screwy here.

vscode isn't involved in this instance, as it's running as part of a build pipeline.

I can confirm that it's running on x86_64 architecture, though I don't know if that's had any impact on this.

Either way, there doesn't seem to be much we can productively do with this at the moment so I'm leaving it pinned to 3.19.6 and will come back to it next time flutter updates and see if the next updates make it happier. Given that there don't seem to be a lot of other sightings of this problem, I'm happy for this ticket to be closed if nobody has any epiphanies.

**Comment by joelpramos** [comment] 2024-05-21 15:23
I am on arm.. oddly after that "trick" started workign again from VSCode so there must be some cache of some sorts. I had no need to pin an iOS build.

**Comment by geokala** [comment] 2024-05-21 17:12
Oh, I should also note (regarding jonahwilliams' comment that the system this was on downloads flutter to a temp location on each build, so it /could/ be a download/SDK issue, but I'd expect that to result in more variety in the errors, where we've had fairly stable error states on these.

**Comment by joelpramos** [comment] 2024-05-28 13:02
Just for reference I stumbled upon this again after leaving debugging connected over night (and closing laptop) and having spent some time doing code generation. No clue the actual cause of this coming back but a `flutter clean` etc. sorted it.

Just dropping it here for reference ... don't have much more to pin point the issue.

**Comment by jonahwilliams** [comment] 2024-05-28 17:45
I think we lack actionable context on this issue. its possible there is some kind of cache invalidation issue or similar.

**Closed by jonahwilliams** 2024-05-28 17:45 UTC
Labels: platform-ios, engine, team-engine

**Comment by LinkCore** [comment] 2024-05-31 10:39
<img width="1098" alt="Снимок экрана 2024-05-31 в 13 37 48" src="https://github.com/flutter/flutter/assets/90643699/a73cb41f-0602-4111-8fd4-db3d30cf9a90">

Also encountered this problem, flutter run main.dart helped with the solution scheduleWarmUpFrame, but MediaQuery.boldTextOverride remained
