### ISSUE TITLE
Unable to send firebase push notification

### ISSUE THREAD

**Issue by harshmodi3812** [flutter/flutter#79759] opened 2021-04-05 08:03 UTC
![Screenshot 2021-04-05 at 1 32 39 PM](https://user-images.githubusercontent.com/71534334/113552202-6c45f080-9613-11eb-8d4e-17d03c3e5ed6.png)

**Comment by pedromassangocode** [comment] 2021-04-05 09:28
Hi @harshmodi3812 
From what I can see, the issue is related to a FlutterFire plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by pedromassangocode** 2021-04-05 09:28 UTC
Labels: in triage
