### ISSUE TITLE
[tool_crash] FileSystemException: Failed to decode data using encoding 'utf-8', null

### ISSUE THREAD

**Issue by feixiang0806** [flutter/flutter#82333] opened 2021-05-12 08:54 UTC
## Command
```
flutter pub get
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Failed to decode data using encoding 'utf-8', null
```
#0      _File._tryDecode (dart:io/file_impl.dart:564:7)
#1      _File.readAsStringSync (dart:io/file_impl.dart:584:7)
#2      ForwardingFile.readAsStringSync (package:file/src/forwarding/forwarding_file.dart:96:16)
#3      ErrorHandlingFile.readAsStringSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:209:22)
#4      _runSync (package:flutter_tools/src/base/error_handling_io.dart:556:14)
#5      ErrorHandlingFile.readAsStringSync (package:flutter_tools/src/base/error_handling_io.dart:208:12)
#6      AndroidPlugin._getSupportedEmbeddings (package:flutter_tools/src/platform_plugins.dart:138:53)
#7      AndroidPlugin._supportedEmbedings (package:flutter_tools/src/platform_plugins.dart:92:70)
#8      AndroidPlugin.toMap (package:flutter_tools/src/platform_plugins.dart:84:30)
#9      _extractPlatformMaps (package:flutter_tools/src/plugins.dart:604:40)
#10     _writeAndroidPluginRegistrant (package:flutter_tools/src/plugins.dart:620:5)
#11     injectPlugins (package:flutter_tools/src/plugins.dart:1177:11)
<asynchronous suspension>
#12     FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:292:5)
<asynchronous suspension>
#13     PackagesGetCommand.runCommand (package:flutter_tools/src/commands/packages.dart:164:5)
<asynchronous suspension>
#14     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1157:12)
<asynchronous suspension>
#15     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1009:27)
<asynchronous suspension>
#16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#17     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 2.0.5, on Microsoft Windows [Version 10.0.18363.836], locale
    zh-CN)
    • Flutter version 2.0.5 at D:\program\flutter_2.0.1
    • Framework revision adc687823a (4 weeks ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\ubtech\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: D:\program\android_studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 4.1.0)
    • Android Studio at D:\program\android_studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] Connected device (3 available)
    • PBCM30 (mobile) • 4950ea76 • android-arm64  • Android 10 (API 29)
    • Chrome (web)    • chrome   • web-javascript • Google Chrome 90.0.4430.93
    • Edge (web)      • edge     • web-javascript • Microsoft Edge 90.0.818.42

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+36
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 78910062997c3a836feee883712c241a5fd22983
### Plugins
audioplayers-0.17.4
auto_orientation-1.0.6
connectivity-3.0.3
connectivity_for_web-0.4.0
connectivity_macos-0.2.0
device_info-1.0.0
flutter_aliplayer-5.3.1
flutter_full_pdf_viewer-1.0.6
flutter_inappwebview
flutter_keyboard_visibility-4.0.6
flutter_keyboard_visibility_web-1.0.1
flutter_plugin_android_lifecycle-1.0.11
flutter_tts-2.1.0
fluttertoast-7.1.8
image_cropper-1.4.0
image_editor-1.0.0
image_picker-0.6.7+22
import_js_library-1.0.2
native_pdf_renderer-2.4.0
package_info-0.4.3+4
path_provider-1.6.28
path_provider_linux-0.0.1+2
path_provider_macos-0.0.4+8
path_provider_windows-0.0.5
permission_handler-3.3.0
screen-0.0.5
shared_preferences-0.5.12+4
shared_preferences_linux-0.0.2+4
shared_preferences_macos-0.0.1+11
shared_preferences_web-0.1.2+7
shared_preferences_windows-0.0.2+3
sqflite-1.3.2+4
url_launcher-6.0.3
url_launcher_linux-2.0.0
url_launcher_macos-2.0.0
url_launcher_web-2.0.0
url_launcher_windows-2.0.0
video_player-1.0.1
video_player_web-0.1.4+1
wakelock-0.2.1+1
wakelock_web-0.1.0+3

**Comment by darshankawar** [comment] 2021-05-12 09:17
Closing this as duplicate of https://github.com/flutter/flutter/issues/65021

**Closed by darshankawar** 2021-05-12 09:17 UTC
Labels: in triage
