### ISSUE TITLE
Linux/GTK: Mouse wheel scrolling is slow on Wayland

### ISSUE THREAD

**Issue by ell1e** [flutter/flutter#71385] opened 2020-11-30 00:45 UTC
## Steps to Reproduce

1. Run https://flathub.org/apps/search/fluffychat on a Linux x64 desktop (I use GNOME Shell in Wayland mode, in case that should be relevant)
2. Scroll in the chat log, the chat list, or the settings listing

**Expected results:**  mouse wheel scrolling is super slow, not laggy but the speed is just *way too low*. like, it's really bad. clicking and dragging is fine but that is a very clumsy gesture with a mouse (as opposed to a finger on a touch device)

**Actual results:** scrolls as fast as all the other applications I use on linux. some of them differ a little in scrolling speed, but all of them - outside of fluffychat/flutter - are acceptable.

<details>
  <summary>Logs</summary>
 I don't have any flutter tools installed so I'm not sure how to do any of that

```
```
</details>

**Comment by TahaTesser** [comment] 2020-11-30 10:06
Hi @ell1e 
Can you please provide your `flutter doctor -v` your `flutter run -d linux --verbose`
Thank you

**Comment by HansMuller** [comment] 2020-11-30 19:40
CC @dkwingsmt @gspencergoog

**Comment by gspencergoog** [comment] 2020-11-30 21:04
cc: @robert-ancell

**Comment by robert-ancell** [comment] 2020-12-03 02:59
The [code for this](https://github.com/flutter/engine/blob/master/shell/platform/linux/fl_view.cc#L313) looks like:
```c
  // TODO(robert-ancell): See if this can be queried from the OS; this value is
  // chosen arbitrarily to get something that feels reasonable.
  const int kScrollOffsetMultiplier = 20;
  scroll_delta_x *= kScrollOffsetMultiplier;
  scroll_delta_y *= kScrollOffsetMultiplier;
```

and is a straight copy from the equivalent Windows code. The issue as I understand it is GTK sends scroll events in steps (?), and Flutter wants them in pixels. I don't know if there's a reliable method we can convert between these units. So we can change the constant, but I don't know if that will work for all systems and what a reliable value is. @ell1e if you are able to compile your own engine could you give a value that seems right on your system and we can compare it to ours?

@stuartmorgan did you have any longer term ideas on what the correct solution is here or insight into exactly what Flutter expects?

**Comment by stuartmorgan** [comment] 2020-12-04 16:17
Chromium code might be useful to look at; I know they've tuned their scroll delta values on each platform.

The issue is that there isn't necessarily a well defined value for how many pixels a (non-smooth-scroll-source) scroll step should be. macOS provides an API for doing this conversion, but I don't know if GTK does. If not, it's a matter of weighing feedback, comparing to other common applications that have scheduling, and deciding on a value.

**Comment by ell1e** [comment] 2020-12-15 17:02
I don't build any flutter apps so I haven't ever really touched it ever beyond using the fluffychat app that happens to be built with it, where I noticed the scrolling. However, I never had an issue with electron apps' scrolling. So if anyone who *does* actually know how to use flutter just compares and changes it such that it matches to be at minimum as fast as with Electron then I imagine I'm probably going to be happy with the result.

**Comment by robert-ancell** [comment] 2020-12-16 01:11
The GTK code uses `page_size ^ 2/3` as the scroll delta when scroll events are received as steps ([source](https://gitlab.gnome.org/GNOME/gtk/-/blob/gtk-3-24/gtk/gtkrange.c#L3047)). The `page_size` is the height of the area being scrolled. We're not going to be able to replicate that here with the current Flutter code as we don't have any context at the point we're converting. Perhaps there should be a non-smooth scroll event to pass to Flutter so it can decide?

**Comment by robert-ancell** [comment] 2020-12-16 23:15
I found the code in Chromium ([source](https://chromium.googlesource.com/chromium/src.git/+/refs/heads/master/ui/events/x/events_x_utils.cc#34)):
```c++
// Scroll amount for each wheelscroll event. 53 is also the value used for GTK+.
const int kWheelScrollAmount = 53;
```

I'm not sure where the original author got the 53 from, I looked back to GTK 2 and it was still using the `pow()` method there. So I suspect it was measured from a running GTK app where the widget happened to be the correct size for this value.

**Comment by stuartmorgan** [comment] 2020-12-16 23:52
I don't see any reason not to start by just updating our constant to match Chromium. 20 wasn't chosen for the Linux embedding by any real process, and matching Chromium will be much more likely to match people's expectations given how common web usage is.

**Comment by robert-ancell** [comment] 2020-12-17 01:17
@stuartmorgan right, I'm working on confirming that 53 in fact gives the same behaviour and will make a PR when I've done that. It may still be worth considering in the future to handle scroll steps in a different way - scrolling turns out to be a lot more complicated than I knew :)

**Comment by robert-ancell** [comment] 2020-12-17 20:39
I'm also working on fixing why we get both smooth and non-smooth scrolling events in Flutter. This causes us to double events and we currently have an effective scroll step of 20 + 20 pixels. I've found [someone else](https://stackoverflow.com/questions/63552967/duplicate-scroll-events-from-gtk) has the same issue, but they also haven't found a solution. Digging deep into GTK to work out how `GtkScrolledWindow` only gets one set of events...

This does suggest that changing to 53 will be about 33% faster, it will be interesting if this feels fast enough compared to other apps.

**Comment by robert-ancell** [comment] 2020-12-18 02:00
Ah, now I understand why @ell1e is getting slow scrolling - the double event issue doesn't occur there, so on Wayland the scroll step is 20px, and on X11 it is 40px.

**Comment by robert-ancell** [comment] 2020-12-18 02:39
The issue seems to be due to the underlying X11 window we use to render with GL. It causes the scroll events to be delivered directly to the `FlView` widget connected to that X11 window, rather than them going to the `GtkWindow` and being processed there (as is the case in a simple GTK application). If you remove the `gtk_widget_set_can_focus(GTK_WIDGET(self), TRUE)` from the `FlView`, then scrolling works correctly, but keyboard input doesn't work.

So more investigation will have to be done in the new year but hopefully we can adjust things to get the events going to the right place.

**Closed** 2021-01-13 20:06 UTC
Labels: P4, a: desktop, f: scrolling, framework, passed first triage, perf: speed, platform-linux, severe: performance
