### ISSUE TITLE
flutter.tools: Application name is not set.

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [flutter/flutter#28397] opened 2019-02-23 16:34 UTC
I started receiving the following warning for my Flutter application when running it on Android that appear every so often:

```
flutter.tools W/zze: Application name is not set. Call Builder#setApplicationName.
```

I cannot make sense of it.
Happens in `master, v1.2.2-pre.46` and also in `dev, v1.2.2`.

It is fairly annoying because it appears in the logs a lot.

**Comment by shadowsheep1** [comment] 2019-02-25 11:53
It seems related with Firebase (specifically in [this](https://stackoverflow.com/questions/54766725/android-firebase-remote-config-application-name-is-not-set-call-buildersetapp) case and mine) with RemoteConfig. @creativecreatorormaybenot  Does your application make use of Firebase plugin(s) and if it does, which ones?

**Comment by creativecreatorormaybenot** [comment] 2019-02-25 16:26
@shadowsheep1 Yes, this is definitely the same issue with `firebase_remote_config`.

**Comment by jonahwilliams** [comment] 2019-04-22 01:13
Duplicate of https://github.com/firebase/firebase-android-sdk/issues/254

**Closed by jonahwilliams** 2019-04-22 01:13 UTC
Labels: tool
