### ISSUE TITLE
problem getting doucment id from firestore 

### ISSUE THREAD

**Issue by moahaimen** [flutter/flutter#38917] opened 2019-08-20 21:16 UTC
hi i have a almost a similar problem  i  have a medical app i have several collections ,  the customer , wanted to make phone login which i did successfully but now i need  to show now i have a problem with geting the document id which is offcourse the same of the userid from authintication
<img width="744" alt="firestoreissue1" src="https://user-images.githubusercontent.com/30658799/63384537-bc713000-c3a7-11e9-8a48-70a9c7ad8240.png">
<img width="502" alt="autheissue" src="https://user-images.githubusercontent.com/30658799/63384539-bd09c680-c3a7-11e9-894c-ea4d388b4429.png">

i did this code
```
class _profilState extends State<profil> {
  String _name;
  String _age;
  String _address;
  String _user;
  int _phone;
    
  
@override
void initState(){
  super.initState();
 FirebaseAuth.instance.currentUser().then((user){
   _user =user.uid;

  }).catchError((e)
  {
    print(e);
  });
}

  @override
  Widget build(BuildContext context) {
`  return StreamBuilder(

      stream: Firestore.instance.collection('profile').snapshots(),
      builder: (context, snapshot) {
        if (!snapshot.hasData) {
          return Center(
            child: Text('loading'),
          );
        }

then i tried to make each user when he/ she  login  and go the user profile  get his full information i used this  code 
`Text("name:" +  snapshot.data.documents[_user]['name'].get(),`)
```
the problem is it doesnt show any thing and i get an error 
but when i edit the code and change it and give the number like this

```
Text("name:" +  snapshot.data.documents[1]['name'].get(),`)
```
it works 
i need to make it show for profile of each user  please help me

**Comment by ali7234** [comment] 2019-09-03 11:11
Actually you got list of documents, iterate through each document and then get the document id.
`stream: Firestore.instance.collection('profile').snapshots(),
  builder: (context, snapshot) {
    if (!snapshot.hasData) {
      return Center(
        child: Text('loading'),
      );
    }else if(snapshot.data){
return ListView.builder(
                          itemCount: snapshot.data.documents.length,
                          itemBuilder: (BuildContext context, int index) {
                            return Text(
                              "Document ID:" +
                                  snapshot.data.documents[index].documentID,
                            );
                          },
                        );}
}`

**Comment by BondarenkoStas** [comment] 2019-09-04 14:17
@moahaimen Please report if you solved your issue, and close it if it's so.

For future, this is a kind of questions better suited for StackOverflow, since there doesn’t seem to be anything wrong with Flutter itself, but related to implementation.

**Comment by moahaimen** [comment] 2019-09-04 15:31
no it didnt help

**Comment by moahaimen** [comment] 2019-09-04 15:31
i need a profile for a single user to be shown not a list of users

**Comment by moahaimen** [comment] 2019-09-04 15:50
> @moahaimen Please report if you solved your issue, and close it if it's so.
> 
> For future, this is a kind of questions better suited for StackOverflow, since there doesn’t seem to be anything wrong with Flutter itself, but related to implementation.

ok sir my mistake next time i will do your advice

**Comment by iapicca** [comment] 2020-01-17 07:35
Hi @moahaimen 
for what I can see the issue is related to a FlutterFire plugin,
please open the issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
thank you

**Closed by iapicca** 2020-01-17 07:35 UTC
Labels: d: stackoverflow
