### ISSUE TITLE
Unable to build web flutter engine locally

### ISSUE THREAD

**Issue by MariaMelnik** [flutter/flutter#70372] opened 2020-11-12 11:22 UTC
I am trying to build flutter engine locally (engine revision: c5c7e83b).

Setup according this [this page](https://github.com/flutter/flutter/wiki/Setting-up-the-Engine-development-environment).
And use `felt build` to build engine [(felt readme)](https://github.com/flutter/engine/blob/master/lib/web_ui/dev/README.md)

But getting error:
```
[5557/5729] ACTION //third_party/dart/utils/dartdevc:dartdevc(//build/toolchain/mac:clang_x64)
FAILED: gen/dartdevc.dart.snapshot 
python ../../third_party/dart/build/gn_run_binary.py compiled_action dart --deterministic --packages=/Users/mariamelnik/flutter_test/engine/src/third_party/dart/.packages --snapshot=gen/dartdevc.dart.snapshot --snapshot-depfile=/Users/mariamelnik/flutter_test/engine/src/out/host_debug_unopt/gen/dartdevc.dart.snapshot.d --snapshot-kind=app-jit --dfe=/Users/mariamelnik/flutter_test/engine/src/third_party/dart/pkg/vm/bin/kernel_service.dart /Users/mariamelnik/flutter_test/engine/src/out/host_debug_unopt/gen/third_party/dart/utils/dartdevc/dartdevc.dart.dill --dart-sdk /Users/mariamelnik/flutter_test/engine/src/third_party/dart/sdk --dart-sdk-summary /Users/mariamelnik/flutter_test/engine/src/out/host_debug_unopt/ddc_outline.dill -k -o dartdevc.js /Users/mariamelnik/flutter_test/engine/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart
Command failed: ./dart --deterministic --packages=/Users/mariamelnik/flutter_test/engine/src/third_party/dart/.packages --snapshot=gen/dartdevc.dart.snapshot --snapshot-depfile=/Users/mariamelnik/flutter_test/engine/src/out/host_debug_unopt/gen/dartdevc.dart.snapshot.d --snapshot-kind=app-jit --dfe=/Users/mariamelnik/flutter_test/engine/src/third_party/dart/pkg/vm/bin/kernel_service.dart /Users/mariamelnik/flutter_test/engine/src/out/host_debug_unopt/gen/third_party/dart/utils/dartdevc/dartdevc.dart.dill --dart-sdk /Users/mariamelnik/flutter_test/engine/src/third_party/dart/sdk --dart-sdk-summary /Users/mariamelnik/flutter_test/engine/src/out/host_debug_unopt/ddc_outline.dill -k -o dartdevc.js /Users/mariamelnik/flutter_test/engine/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart
output: Error: Could not resolve the package 'bazel_worker' in 'package:bazel_worker/bazel_worker.dart'.
Error: Could not resolve the package 'dev_compiler' in 'package:dev_compiler/src/compiler/shared_command.dart'.
Error: Could not resolve the package 'dev_compiler' in 'package:dev_compiler/src/kernel/expression_compiler_worker.dart'.
../../third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:15:8: Error: Not found: 'package:bazel_worker/bazel_worker.dart'
import 'package:bazel_worker/bazel_worker.dart';
       ^
../../third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:16:8: Error: Not found: 'package:dev_compiler/src/compiler/shared_command.dart'
import 'package:dev_compiler/src/compiler/shared_command.dart';
       ^
../../third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:17:8: Error: Not found: 'package:dev_compiler/src/kernel/expression_compiler_worker.dart'
import 'package:dev_compiler/src/kernel/expression_compiler_worker.dart';
       ^
../../third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:56:31: Error: Type 'AsyncWorkerLoop' not found.
class _CompilerWorker extends AsyncWorkerLoop {
                              ^^^^^^^^^^^^^^^
../../third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:58:9: Error: Type 'ParsedArguments' not found.
  final ParsedArguments _startupArgs;
        ^^^^^^^^^^^^^^^
../../third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:60:38: Error: Type 'AsyncWorkerConnection' not found.
  _CompilerWorker(this._startupArgs, AsyncWorkerConnection workerConnection)
                                     ^^^^^^^^^^^^^^^^^^^^^
../../third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:65:3: Error: Type 'CompilerResult' not found.
  CompilerResult lastResult;
  ^^^^^^^^^^^^^^
../../third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:69:10: Error: Type 'WorkResponse' not found.
  Future<WorkResponse> performRequest(WorkRequest request) async {
         ^^^^^^^^^^^^
../../third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:69:39: Error: Type 'WorkRequest' not found.
  Future<WorkResponse> performRequest(WorkRequest request) async {
                                      ^^^^^^^^^^^
../../third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:94:17: Error: Type 'ParsedArguments' not found.
Future runBatch(ParsedArguments batchArgs) async {
                ^^^^^^^^^^^^^^^
../../third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:25:20: Error: Getter not found: 'ParsedArguments'.
  var parsedArgs = ParsedArguments.from(args);
                   ^^^^^^^^^^^^^^^
../../third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:29:11: Error: Method not found: 'StdAsyncWorkerConnection'.
        ? StdAsyncWorkerConnection()
          ^^^^^^^^^^^^^^^^^^^^^^^^
../../third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:30:11: Error: Method not found: 'SendPortAsyncWorkerConnection'.
        : SendPortAsyncWorkerConnection(sendPort);
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../../third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:38:26: Error: Getter not found: 'ExpressionCompilerWorker'.
      var worker = await ExpressionCompilerWorker.createFromArgs(
                         ^^^^^^^^^^^^^^^^^^^^^^^^
../../third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:46:17: Error: Getter not found: 'ExpressionCompilerWorker'.
          await ExpressionCompilerWorker.createFromArgs(parsedArgs.rest);
                ^^^^^^^^^^^^^^^^^^^^^^^^
../../third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:50:24: Error: Method not found: 'compile'.
    var result = await compile(parsedArgs);
                       ^^^^^^^
../../third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:31:57: Error: The method 'run' isn't defined for the class '_CompilerWorker'.
 - '_CompilerWorker' is from '../../third_party/dart/pkg/dev_compiler/bin/dartdevc.dart'.
Try correcting the name to the name of an existing method, or defining a method named 'run'.
    await _CompilerWorker(parsedArgs, workerConnection).run();
                                                        ^^^
../../third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:58:9: Error: 'ParsedArguments' isn't a type.
  final ParsedArguments _startupArgs;
        ^^^^^^^^^^^^^^^
../../third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:60:38: Error: 'AsyncWorkerConnection' isn't a type.
  _CompilerWorker(this._startupArgs, AsyncWorkerConnection workerConnection)
                                     ^^^^^^^^^^^^^^^^^^^^^
../../third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:61:15: Error: No named parameter with the name 'connection'.
      : super(connection: workerConnection);
              ^^^^^^^^^^
../../third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:65:3: Error: 'CompilerResult' isn't a type.
  CompilerResult lastResult;
  ^^^^^^^^^^^^^^
../../third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:69:39: Error: 'WorkRequest' isn't a type.
  Future<WorkResponse> performRequest(WorkRequest request) async {
                                      ^^^^^^^^^^^
../../third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:77:20: Error: The method 'sourcePathToUri' isn't defined for the class '_CompilerWorker'.
 - '_CompilerWorker' is from '../../third_party/dart/pkg/dev_compiler/bin/dartdevc.dart'.
Try correcting the name to the name of an existing method, or defining a method named 'sourcePathToUri'.
      inputDigests[sourcePathToUri(input.path)] = input.digest;
                   ^^^^^^^^^^^^^^^
../../third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:82:13: Error: The method 'compile' isn't defined for the class '_CompilerWorker'.
 - '_CompilerWorker' is from '../../third_party/dart/pkg/dev_compiler/bin/dartdevc.dart'.
Try correcting the name to the name of an existing method, or defining a method named 'compile'.
            compile(args, previousResult: context, inputDigests: inputDigests),
            ^^^^^^^
../../third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:87:12: Error: The method 'WorkResponse' isn't defined for the class '_CompilerWorker'.
 - '_CompilerWorker' is from '../../third_party/dart/pkg/dev_compiler/bin/dartdevc.dart'.
Try correcting the name to the name of an existing method, or defining a method named 'WorkResponse'.
    return WorkResponse()
           ^^^^^^^^^^^^
../../third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:94:17: Error: 'ParsedArguments' isn't a type.
Future runBatch(ParsedArguments batchArgs) async {
                ^^^^^^^^^^^^^^^
../../third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:102:3: Error: 'CompilerResult' isn't a type.
  CompilerResult result;
  ^^^^^^^^^^^^^^
../../third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:110:22: Error: Method not found: 'compile'.
      result = await compile(args, previousResult: result);
                     ^^^^^^^

[5566/5729] ACTION //flutter/flutter_frontend_server:frontend_server(//build/toolchain/mac:clang_x64)
ninja: build stopped: subcommand failed.
```

There is similar closed [dart sdk issue](https://github.com/dart-lang/sdk/issues/35834).

**Comment by hello-addweb** [comment] 2020-11-12 13:52
Please once do configure like below

```
1. flutter channel master 
2. flutter upgrade 
3. flutter config --enable-web
4. cd into project directory 
5. flutter create . 
6. flutter run -d chrome
```

**Comment by TahaTesser** [comment] 2020-11-12 15:26
Hi @MariaMelnik 
Are you building it on Linux?  Do you experience with the latest update engine in `src/futter`?  please update your engine repo and `git fetch upstream`
Double-check if you have followed  all the steps
Thank you

**Comment by MariaMelnik** [comment] 2020-11-12 17:55
@TahaTesser I've just tried again from scratch (created new folder, sync repo and so on). I got same issue.

**Comment by TahaTesser** [comment] 2020-11-13 13:55
Hi @MariaMelnik 
I tried from scratch, have no issues with the latest engine fork 

`felt build --watch`
```bash
tahatesser@Tahas-MacBook-Pro src % felt build --watch
Running on MacOS. Will check the file and user limits.
File limits too low increasing the file limits
User limits too low increasing the user limits
Problem changing the user limit. Please try to reboot to use the higher limits. error: \n/Volumes/Extreme/engine/src/flutter/lib/web_ui/dev/felt: line 91: ulimit: max user processes: cannot modify limit: Operation not permitted
Running gn...
Generating GN files in: out/host_debug_unopt
Generating Xcode projects took 399ms
Done. Made 713 targets from 223 files in 3699ms
Running autoninja...
ninja: Entering directory `/Volumes/Extreme/engine/src/out/host_debug_unopt'
[21/21] STAMP obj/default.stamp
Initial build done!
Watching directory: flutter/lib/web_ui/lib/
```

To confirm the engine is attached, I modified canvaskit font size to 20 

<img width="726" alt="Screenshot 2020-11-13 at 7 22 00 PM" src="https://user-images.githubusercontent.com/48603081/99079297-c18e5080-25e5-11eb-848b-00a08103a7a8.png">


```bash
tahatesser@Tahas-MacBook-Pro master_flutter % flutterm run --local-engine-src-path /Volumes/Extreme/engine/src  --local-engine=/Volumes/Extreme/engine/src/out/host_debug_unopt --dart-define=FLUTTER_WEB_USE_SKIA=true  -d chrome
Launching lib/main.dart on Chrome in debug mode...
Syncing files to device Chrome...                                  16.6s
Debug service listening on ws://127.0.0.1:50236/HPfxVzl9TbI=/ws

Warning: Flutter's support for web development is not stable yet and hasn't
been thoroughly tested in production environments.
For more information see https://flutter.dev/web

🔥  To hot restart changes while running, press "r" or "R".
For a more detailed help message, press "h". To quit, press "q".
```

**Comment by MariaMelnik** [comment] 2020-11-14 09:46
@TahaTesser I'm not sure what additional information I can provide for this issue.

**Comment by TahaTesser** [comment] 2020-11-16 07:08
Tried to reproduce this on Mac, engine compiles for web withno issues, I’m unable to reproduce the issue to pinpoint the cause. The issue needs further investigation.

**Comment by yjbanov** [comment] 2020-12-02 18:42
@MariaMelnik try running `gclient sync -D` before running felt. I would also `rm lib/web_ui/.dart_tool/felt.snapshot*` before using felt to make sure it's not picking up an out-of-date build of felt.

**Comment by pedromassangocode** [comment] 2020-12-23 09:29
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2020-12-23 09:29 UTC
Labels: engine, passed first triage, platform-web, waiting for customer response
