### ISSUE TITLE
Row causing exception in widget test

### ISSUE THREAD

**Issue by EthanBarlow** [flutter/flutter#90988] opened 2021-09-29 21:19 UTC
The output in the console said to report this assertion.

## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
The only file to change is the /test/widget_test.dart
3. 

Below the default widget test add another widget test to pump some empty widgets. (My app has content in these widgets, but the exception is still reproducible without the content.)

```
  testWidgets('Container with child Row that has two SizedBox children',
      (WidgetTester tester) async {
    await tester.pumpWidget(
      Container(
        child: Row(
          children: [
            SizedBox(),
            SizedBox(),
          ],
        ),
      ),
    );
  });
```

Run the test.

Note: adding `textDirection: TextDirection.ltr,` to the Row widget allows the test to pass, but it seems odd that this error does not occur when running the app (i.e., not the tests). Maybe the Row widget when being used in a test can have a default Directionality based on the developer's language settings.

**Expected results:** 
I expected to see that all the tests passed.

**Actual results:** 
I get an exception caught by the rendering library.

<details>
  <summary>Logs</summary>

✓ Counter increments smoke test
══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
The following assertion was thrown during performLayout():
Horizontal RenderFlex with multiple children has a null textDirection, so the layout order is
undefined.
'package:flutter/src/rendering/flex.dart':
Failed assertion: line 453 pos 18: 'textDirection != null'

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was:
  Row Row:file:///C:/Programming/bug/test/widget_test.dart:35:16

When the exception was thrown, this was the stack:
#2      RenderFlex._debugHasNecessaryDirections (package:flutter/src/rendering/flex.dart:453:18)
#3      RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:918:12)
#4      RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#5      RenderView.performLayout (package:flutter/src/rendering/view.dart:165:14)
#6      RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1713:7)
#7      PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:885:18)
#8      AutomatedTestWidgetsFlutterBinding.drawFrame (package:flutter_test/src/binding.dart:1142:23)
#9      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:319:5)
#10     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1143:15)
#11     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1080:9)
#12     AutomatedTestWidgetsFlutterBinding.pump.<anonymous closure> (package:flutter_test/src/binding.dart:1006:9)
#15     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:71:41)
#16     AutomatedTestWidgetsFlutterBinding.pump (package:flutter_test/src/binding.dart:993:27)
#17     WidgetTester.pumpWidget.<anonymous closure> (package:flutter_test/src/widget_tester.dart:554:22)
#20     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:71:41)
#21     WidgetTester.pumpWidget (package:flutter_test/src/widget_tester.dart:551:27)
#22     main.<anonymous closure> (file:///C:/Programming/bug/test/widget_test.dart:33:18)
#23     main.<anonymous closure> (file:///C:/Programming/bug/test/widget_test.dart:32:7)
#24     testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:176:29)
<asynchronous suspension>
<asynchronous suspension>
(elided 7 frames from class _AssertionError, dart:async, and package:stack_trace)

The following RenderObject was being processed when the exception was fired: RenderFlex#b30d2:
  creator: Row ← Container ← [root]
  parentData: <none>
  constraints: BoxConstraints(w=800.0, h=600.0)
  size: MISSING
  direction: horizontal
  mainAxisAlignment: start
  mainAxisSize: max
  crossAxisAlignment: center
  verticalDirection: down
This RenderObject had the following descendants (showing up to depth 5):
    child 1: RenderConstrainedBox#9ca7f NEEDS-LAYOUT NEEDS-PAINT
    child 2: RenderConstrainedBox#7fa0e NEEDS-LAYOUT NEEDS-PAINT
════════════════════════════════════════════════════════════════════════════════════════════════════

```
```

```
```

`flutter doctor -v`
```
PS C:\Programming\bug> flutter doctor -v
[✓] Flutter (Channel stable, 2.5.0, on Microsoft Windows [Version 10], locale en-US)
    • Flutter version 2.5.0 at C:\Flutter\FlutterSDK\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cc385b4b8 (3 weeks ago), 2021-09-07 23:01:49 -0700
    • Engine revision f0826da7ef
    • Dart version 2.14.0

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Ethan\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 4.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[✓] IntelliJ IDEA Community Edition (version 2021.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.2.1
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.60.2)
    • VS Code at C:\Users\Ethan\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.26.0

[✓] Connected device (3 available)
    • moto g 7 play (mobile) • ZY323QHBZ8 • android-arm    • Android 10 (API 29)
    • Chrome (web)           • chrome     • web-javascript • Google Chrome 94.0.4606.61
    • Edge (web)             • edge       • web-javascript • Microsoft Edge 93.0.961.52

```

</details>

**Comment by darshankawar** [comment] 2021-09-30 09:14
Thanks for the report. I see the same behavior upon running the said test in a new app.

<details>
<summary>test console error</summary>

```


══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
The following assertion was thrown during performLayout():
Horizontal RenderFlex with multiple children has a null textDirection, so the layout order is
undefined.
'package:flutter/src/rendering/flex.dart':
Failed assertion: line 453 pos 18: 'textDirection != null'

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was:
  Row Row:file:///Users/dhs/Documents/NCFlutter/testapp_demo/test/widget_test.dart:35:20

When the exception was thrown, this was the stack:
#2      RenderFlex._debugHasNecessaryDirections (package:flutter/src/rendering/flex.dart:453:18)
#3      RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:918:12)
#4      RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#5      RenderView.performLayout (package:flutter/src/rendering/view.dart:165:14)
#6      RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1713:7)
#7      PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:885:18)
#8      AutomatedTestWidgetsFlutterBinding.drawFrame (package:flutter_test/src/binding.dart:1128:23)
#9      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:319:5)
#10     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1145:15)
#11     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1082:9)
#12     AutomatedTestWidgetsFlutterBinding.pump.<anonymous closure> (package:flutter_test/src/binding.dart:992:9)
#15     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:71:41)
#16     AutomatedTestWidgetsFlutterBinding.pump (package:flutter_test/src/binding.dart:979:27)
#17     WidgetTester.pumpWidget.<anonymous closure> (package:flutter_test/src/widget_tester.dart:548:22)
#20     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:71:41)
#21     WidgetTester.pumpWidget (package:flutter_test/src/widget_tester.dart:545:27)
#22     main.<anonymous closure> (file:///Users/dhs/Documents/NCFlutter/testapp_demo/test/widget_test.dart:33:22)
#23     main.<anonymous closure> (file:///Users/dhs/Documents/NCFlutter/testapp_demo/test/widget_test.dart:32:11)
#24     testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:170:29)
<asynchronous suspension>
<asynchronous suspension>
(elided 7 frames from class _AssertionError, dart:async, and package:stack_trace)

The following RenderObject was being processed when the exception was fired: RenderFlex#6dda9:
  creator: Row ← Container ← [root]
  parentData: <none>
  constraints: BoxConstraints(w=800.0, h=600.0)
  size: MISSING
  direction: horizontal
  mainAxisAlignment: start
  mainAxisSize: max
  crossAxisAlignment: center
  verticalDirection: down
This RenderObject had the following descendants (showing up to depth 5):
    child 1: RenderConstrainedBox#e2641 NEEDS-LAYOUT NEEDS-PAINT
    child 2: RenderConstrainedBox#0eb7b NEEDS-LAYOUT NEEDS-PAINT
════════════════════════════════════════════════════════════════════════════════════════════════════
══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
The following assertion was thrown during a scheduler callback:
Updated layout information required for RenderConstrainedBox#e2641 NEEDS-LAYOUT NEEDS-PAINT to
calculate semantics.
'package:flutter/src/rendering/object.dart':
Failed assertion: line 2747 pos 12: '!_needsLayout'

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack:
#2      RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:2747:12)
#3      RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:2759:61)
#4      ContainerRenderObjectMixin.visitChildren (package:flutter/src/rendering/object.dart:3412:14)
#5      RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:2836:5)
#6      RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:2757:5)
#7      RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:2759:61)
#8      RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:3128:14)
#9      RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:2836:5)
#10     RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:2757:5)
#11     RenderObject._updateSemantics (package:flutter/src/rendering/object.dart:2725:41)
#12     PipelineOwner.flushSemantics (package:flutter/src/rendering/object.dart:1080:16)
#13     AutomatedTestWidgetsFlutterBinding.drawFrame (package:flutter_test/src/binding.dart:1137:31)
#14     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:319:5)
#15     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1145:15)
#16     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1082:9)
#17     AutomatedTestWidgetsFlutterBinding.pump.<anonymous closure> (package:flutter_test/src/binding.dart:992:9)
#20     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:71:41)
#21     AutomatedTestWidgetsFlutterBinding.pump (package:flutter_test/src/binding.dart:979:27)
#22     WidgetTester.pumpWidget.<anonymous closure> (package:flutter_test/src/widget_tester.dart:548:22)
#25     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:71:41)
#26     WidgetTester.pumpWidget (package:flutter_test/src/widget_tester.dart:545:27)
#27     main.<anonymous closure> (file:///Users/dhs/Documents/NCFlutter/testapp_demo/test/widget_test.dart:33:22)
#28     main.<anonymous closure> (file:///Users/dhs/Documents/NCFlutter/testapp_demo/test/widget_test.dart:32:11)
#29     testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:170:29)
<asynchronous suspension>
<asynchronous suspension>
(elided 7 frames from class _AssertionError, dart:async, and package:stack_trace)
════════════════════════════════════════════════════════════════════════════════════════════════════
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following message was thrown:
Multiple exceptions (2) were detected during the running of the current test, and at least one was
unexpected.
════════════════════════════════════════════════════════════════════════════════════════════════════

Test failed. See exception logs above.
The test description was: Container with child Row that has two SizedBox children





```


</details>

<details>
<summary> stable, master flutter doctor -v </summary>

```
[✓] Flutter (Channel stable, 2.5.1, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.5.1 at /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffb2ecea52 (2 days ago), 2021-09-17 15:26:33 -0400
    • Engine revision b3af521a05
    • Dart version 2.14.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/dhs/Library/Android/sdk
    • Java binary at: /Users/dhs/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.    

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Users/dhs/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)        

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (4 available)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 93.0.4577.82


• No issues found!

[✓] Flutter (Channel master, 2.6.0-12.0.pre.150, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-GB)
    • Flutter version 2.6.0-12.0.pre.150 at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 367531447c (8 hours ago), 2021-09-29 20:03:04 -0400
    • Engine revision 9224a17d1c
    • Dart version 2.15.0 (build 2.15.0-162.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/dhs/Library/Android/sdk
    • Java binary at: /Users/dhs/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.    

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Users/dhs/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)        

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[[✓] Connected device (4 available)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 93.0.4577.82


• No issues found!




```

</details>

**Comment by jason-simmons** [comment] 2021-10-04 21:16
A `Row` with multiple children requires a `TextDirection` (see https://api.flutter.dev/flutter/widgets/Row/Row.html)

In the full app some ancestor of the `Row` is presumably providing the `TextDirection`.  If that ancestor is not present in the test, then the test `Row` needs to specify the `TextDirection`.

**Comment by darshankawar** [comment] 2021-10-05 05:40
Closing this as working as intended. You'll need to specify `TextDirection` as mentioned above and based on your original comment, when you pass it, the test passes as expected.

**Closed by darshankawar** 2021-10-05 05:40 UTC
Labels: a: tests, framework, a: error message, has reproducible steps, found in release: 2.5, found in release: 2.6
