### ISSUE TITLE
Allow changing the Android `minSDKVersion` used for add-to-app module builds

### ISSUE THREAD

**Issue by neiljaywarner** [flutter/flutter#106047] opened 2022-06-15 16:41 UTC
Problem:
Important features/packages for Android such as webview, firebase (analytics, crashlytics etc), google play services require at least minapi 19.
`uses-sdk:minSdkVersion 16 cannot be smaller than version 19 declared in library `

Normal instructions will say to upgrade it in android/app/build.gradle but in modules this is autogenerated and in gitignore.
This would alienate 0.4% of users maximum it looks like.
I think in the real world companies that use add2app have been utilizing 20 or 21 as a min api level for 4-5 years or more because it came with such large changes its cost/benefit ratio worked well.

see https://apilevels.com/
and https://firebase.google.com/docs/android/setup
and https://android-developers.googleblog.com/2021/07/google-play-services-discontinuing-jelly-bean.html
and even https://github.com/JakeWharton/timber/issues/117
and yes, of course https://github.com/flutter/flutter/issues/82000

**Comment by stuartmorgan** [comment] 2022-06-15 17:52
Are you asking for Flutter to change the autogenerated minimum SDK version, or are you asking for the ability to control the version used at the level of your application? Those are very different requests, and it's not clear which this is asking for.

**Comment by neiljaywarner** [comment] 2022-06-15 17:58
Let's change the auto generated version please
The pros of having one so old are much less than the cons


....sent from my phone

**Comment by stuartmorgan** [comment] 2022-06-15 18:11
That makes this a duplicate of https://github.com/flutter/flutter/issues/82000 then; we don't use different versions for different kinds of builds. We have a consistent minimum version by design.

**Comment by neiljaywarner** [comment] 2022-06-15 21:55
@stuartmorgan  thank you so much

**Comment by danagbemava-nc** [comment] 2022-06-16 08:33
I believe this feature request is a subset of the discussion in https://github.com/flutter/flutter/issues/98077.

Kindly follow up in the linked issue for updates. 

Closing from here as duplicate. 

Thank you

**Closed by danagbemava-nc** 2022-06-16 08:33 UTC
Labels: in triage
