### ISSUE TITLE
[Android] Flutter template project is misconfigured and causing incompatible Kotlin and Gradle versions issue

### ISSUE THREAD

**Issue by drrnbrns** [flutter/flutter#153885] opened 2024-08-21 21:39 UTC
### Steps to reproduce

First seen in 3.24.1.  Wasn't happening in 3.22.3.  The generated APK works, but there shouldn't be errors reported in the sample project.

1. flutter create --platforms=android test
2. cd test
3. flutter build apk

### Expected results

No errors about mismatched Kotlin versions

### Actual results

```
Font asset "MaterialIcons-Regular.otf" was tree-shaken, reducing it from 1645184 to 1384 bytes (99.9% reduction). Tree-shaking can be disabled by providing the --no-tree-shake-icons flag when building your app.
e: C:/Users/User/.gradle/caches/transforms-3/c683cde5b1f5377825fe27da54e1b718/transformed/fragment-1.7.1/jars/classes.jar!/META-INF/fragment_release.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.
e: C:/Users/User/.gradle/caches/transforms-3/4b07bb875192e8c29c9b76677237c5c8/transformed/jetified-activity-1.8.1/jars/classes.jar!/META-INF/activity_release.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.
e: C:/Users/User/.gradle/caches/transforms-3/455c428e62a6dd75da98c7152f7af462/transformed/jetified-lifecycle-livedata-core-ktx-2.7.0/jars/classes.jar!/META-INF/lifecycle-livedata-core-ktx_release.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.
```
(etc).  Note that removing that C:/Users/User/.gradle/caches folder does not help.

### Code sample

Uses sample code generated as descried above

### Logs

Logs shown in "Expected results"

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.24.1, on Microsoft Windows [Version 10.0.19045.4780], locale en-US)
    • Flutter version 3.24.1 on channel stable at C:\Users\User\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5874a72aa4 (24 hours ago), 2024-08-20 16:46:00 -0500
    • Engine revision c9b9d5780d
    • Dart version 3.5.1
    • DevTools version 2.37.2

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at C:\Users\User\AppData\Local\Android\sdk
    • Platform android-35, build-tools 35.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0--11852314)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2024.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0--11852314)

[√] VS Code (version 1.92.2)
    • VS Code at C:\Users\User\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.94.0

[√] Connected device (4 available)
    • Nexus 5 (mobile)  • 06b053caf0e9599b • android-arm    • Android 6.0.1 (API 23)
    • Windows (desktop) • windows          • windows-x64    • Microsoft Windows [Version 10.0.19045.4780]
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 127.0.6533.120
    • Edge (web)        • edge             • web-javascript • Microsoft Edge 127.0.2651.105

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

**Comment by huycozy** [comment] 2024-08-22 09:21
Hi @drrnbrns 
This is most likely an incompatible Kotlin and Gradle versions issue. Please check https://github.com/flutter/flutter/issues/137886#issuecomment-1793852741 to see if it works for you. I'm going ahead and closing this issue. If you disagree, please write in the comments and I will reopen it. Thanks!

**Comment by drrnbrns** [comment] 2024-08-22 15:33
Hi @huycozy , I think I do disagree actually!  I'd found similar advice on how to patch existing Flutter projects, but the reason I logged this bug is that the sample provided by `flutter create ` is created in a misconfigured state.  I don't think a brand new project created by the latest Flutter should require patching.

**Comment by huycozy** [comment] 2024-08-23 04:36
Re-opening the issue. 

>I logged this bug is that the sample provided by flutter create  is created in a misconfigured state. I don't think a brand new project created by the latest Flutter should require patching.

I see. The template project generated by flutter tool should be tweaked beforehand to avoid this incompatibility.

**Comment by reidbaker** [comment] 2024-08-26 13:25
Possible dupe of https://github.com/flutter/flutter/issues/153668.

**Comment by drrnbrns** [comment] 2024-08-26 15:29
> Possible dupe of #153668.

That looks closely related, but I don't think it's the same since it's a build failure, not just warnings.  Following the steps in #153668 I'm unable to repro the build failure that some people are seeing.  For me, it succeeds with the warnings that are described in this issue.

**Comment by gmackall** [comment] 2024-08-26 22:29
I believe this is due to a mismatch between the versions of kotlin used by the [androidx libraries in the engine](https://github.com/flutter/engine/blob/main/tools/androidx/files.json), and the version of kotlin that AGP itself uses. You can fix this log spam by upgrading the version of AGP in `<project>/android/settings.gradle` to `8.1.0` or higher. 

It's already fixed on master - we can consider cherry picking in https://github.com/flutter/flutter/pull/151433 to fix it on stable (as I agree this log spam is not a great experience when building a freshly created project), though from what I can tell it isn't actually an error (doesn't block the build, and the resulting apk seems to work fine).

cc @reidbaker, what do you think about cherry picking this as well?

**Comment by drrnbrns** [comment] 2024-08-27 00:13
Thanks @gmackall .  I was never blocked by this, so I don't have a strong opinion on cherry picking to stable, but I agree it's not a good look as-is.

I can confirm that after running `flutter channel main` and repeating the steps, the Kotlin errors went away.  I did get one new warning though, just FYI: "Warning: SDK processing. This version only understands SDK XML versions up to 3 but an SDK XML file of version 4 was encountered. This can happen if you use versions of Android Studio and the command-line tools that were released at different times.".

**Comment by reidbaker** [comment] 2024-08-27 15:14
Most of that pr is testing but it is a lot of files. The main change is to constants that define what versions we know about it so that seems safe enough. @gmackall if you want to cherry pick for this weeks build it needs to happen today.

**Comment by gmackall** [comment] 2024-08-28 18:23
Closing this as the cherry pick has landed

**Closed by gmackall** 2024-08-28 18:23 UTC
Labels: platform-android, tool, t: gradle, has reproducible steps, team-android, found in release: 3.24
