### ISSUE TITLE
[Desktop]:Border color does not count opacity

### ISSUE THREAD

**Issue by kirill-21** [flutter/flutter#82750] opened 2021-05-17 21:47 UTC
Code to repeat the issue:
```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  Color color = Colors.yellow;
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      home: Scaffold(
        backgroundColor: Colors.black,
        body: Center(
          child: MouseRegion(
            onEnter: (_) => setState(() => color = Colors.yellow.withOpacity(0.85)),
            onExit: (_) => setState(() => color = Colors.yellow),
            child: Container(
              width: 425.0,
              height: 225.0,
              decoration: BoxDecoration(
                color: color,
                border: Border.all(
                  width: 10.0,
                  color: color
                )
              ),
              child: Text('123'),
            ),
          ),
        ),
      ),
    );
  }
}
```
Setstate changes the container's color, but the border's color stays the same.
![5wS2KTeVP8](https://user-images.githubusercontent.com/63228361/118560628-790d4680-b772-11eb-8a41-2bf91b6dea72.gif)

Also, there are some strange 1px lines on each side of the border which don't match any color
![image](https://user-images.githubusercontent.com/63228361/118561354-86770080-b773-11eb-8dac-baf6fcba149d.png)

Flutter version: The latest from stable channel

**Comment by darshankawar** [comment] 2021-05-18 10:00
@kirill-21 
I am assuming this is on web ?
What's the expected behavior are you looking for from your code sample ?

**Comment by kirill-21** [comment] 2021-05-18 10:04
> @kirill-21
> I am assuming this is on web ?
> What's the expected behavior are you looking for from your code sample ?

Forgot to mention this, the issue was found on Windows Desktop

**Comment by darshankawar** [comment] 2021-05-18 12:43
Thanks for clarifying. See the same behavior on macOS desktop.

<img width="502" alt="Screenshot 2021-05-18 at 6 10 56 PM" src="https://user-images.githubusercontent.com/67046386/118652874-a30f4900-b804-11eb-9c31-97e46f4722a0.png">

<details>
<summary> flutter doctor -v </summary>

```
[✓] Flutter (Channel master, 2.3.0-2.0.pre.253, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-GB)
    • Flutter version 2.3.0-2.0.pre.253 at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision bac5a0db3b (9 hours ago), 2021-05-18 10:19:03 +0800
    • Engine revision 3cda7f5807
    • Dart version 2.14.0 (build 2.14.0-119.0.dev)

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (4 available)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 90.0.4430.212

! Doctor found issues in 1 category.



```

</details>

**Comment by kirill-21** [comment] 2021-05-18 14:37
> Thanks for clarifying. See the same behavior on macOS desktop.

And what about this strange 1px lines? 
![image](https://user-images.githubusercontent.com/63228361/118670947-b966d600-b7ff-11eb-8d5f-31d26d65e7eb.png)

**Comment by gspencergoog** [comment] 2021-05-20 21:19
> What about my question above? Is it a normal behaviour or it's a bug? (About 1px lines)

These are almost certainly due to antialiasing between the border and the contents/background, and is normal.

**Comment by bleroux** [comment] 2022-05-09 06:19
It might be surprising, but it works as expected, let me explain why.

As described in `BoxDecoration.border` [documentation](https://github.com/flutter/flutter/blob/0656a5c0333e690eac26211a022dcfa4a8144d25/packages/flutter/lib/src/painting/box_decoration.dart#L151), the border is drawn above the background color.
So if the border color has an opacity < 1.0 it will make the background color partially visible. 

In your sample code, the background color is yellow with a 0.85 opacity and the border color is the same, so the border is painted using yellow with opacity 0.85 above yellow with same opacity, the result is a brighter yellow than the one you expected.

To make this more visible, here is a modified code sample using 0.5 opacity so it’s easier to see yellow nuances. This sample also displays, on the right, another container whose color is standard Colors.yellow for an easier comparison.

<details>
<summary>Code sample</summary>

```dart

import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  Color color = Colors.yellow;

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      home: Scaffold(
        backgroundColor: Colors.black,
        body: Row(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            MouseRegion(
              onEnter: (_) => setState(() => color = Colors.yellow.withOpacity(0.5)),
              onExit: (_) => setState(() => color = Colors.yellow),
              child: Container(
                width: 425.0,
                height: 225.0,
                decoration: BoxDecoration(
                  color: color,
                  border: Border.all(width: 10.0, color: color),
                ),
                // Inner container to show the rendering of two level of opacified color
                child: Center(
                  child: Container(
                    width: 100,
                    height: 100,
                    color: color,
                  ),
                ),
              ),
            ),
            // Second container to show the original color (opacity = 1.0)
            Container(
              width: 425.0,
              height: 225.0,
              decoration: BoxDecoration(
                color: Colors.yellow,
                border: Border.all(width: 10.0, color: Colors.yellow),
              ),
            ),
          ],
        ),
      ),
    );
  }
}

```

</details>

I will close this issue, but do not hesitate to comment here or to create a new one if you think this answer is not accurate.

**Closed by bleroux** 2022-05-09 06:19 UTC
Labels: framework, f: material design, a: mouse, has reproducible steps, found in release: 2.3
