### ISSUE TITLE
Shadow gradients do not perfectly match MDC-iOS

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#16540] opened 2018-04-12 22:59 UTC
This was reported by a Google user of who embedded Flutter into their existing app and would notice side-by-side differences between Flutter content and Obj-C/MDC-iOS content.

![image](https://user-images.githubusercontent.com/11857803/38708253-36141234-3e6a-11e8-8457-fb93da10c17a.png)
![image](https://user-images.githubusercontent.com/11857803/38708263-41280eb4-3e6a-11e8-951f-28a50e34a3b8.png)

I'm actually not sure which is Flutter off the top of my head (someone else should feel free to edit this comment to label them). @willlarche mentioned this is expected since MDC-iOS doesn't perfectly match the MD spec yet. (I'm not sure if Flutter does, but @jason-simmons certainly spent a lot of time trying).

**Comment by Hixie** [comment] 2018-04-25 21:13
Closing as duplicate of https://github.com/flutter/flutter/issues/16540 which is covering basically the same issue.

**Closed by Hixie** 2018-04-25 21:13 UTC
Labels: a: fidelity, ⌺‬ platform-ios

**Comment by Hixie** [comment] 2018-06-27 19:37
Sorry I meant https://github.com/flutter/flutter/issues/10238.

**Comment by eseidelGoogle** [comment] 2018-09-04 15:47
@willlarche Is there something more we can learn about the MDC shadow revamp?  I believe this issue will become more common as more folks start to embed Flutter into existing apps.

**Comment by willlarche** [comment] 2018-09-04 15:51
Explorations have begun with designers and engineers on possible corrections to elevation and shadow rendering. Nothing approved for dev at the moment.

**Comment by willlarche** [comment] 2018-09-04 15:53
I can also mention that in an audit, the shadows were different in traditional iOS, traditional Android, web, and Flutter (both from each other and the spec). So this isn't a Flutter issue and MDC-iOS isn't correct.
