### ISSUE TITLE
How does the message data returned by web_socket_channel monitor Unit8List turn into Map

### ISSUE THREAD

**Issue by LQS5858** [flutter/flutter#80632] opened 2021-04-17 05:15 UTC
1. web_socket_channel:^1.2.0
2. flutter:2.0.0
 response:
`[31, 139, 8, 0, 0, 0, 0, 0, 0, 0, 21, 78, 187, 14, 130, 64, 16, 252, 21, 51, 245, 177, 97, 23, 110, 129, 235, 16, 72, 48, 26, 45, 60, 27, 59, 16, 10, 11, 26, 197, 138, 240, 239, 222, 77, 51, 153, 204, 35, 179, 225, 181, 76, 112, 248, 254, 70, 250, 12, 235, 12, 131, 105, 88, 7, 184, 13, 143, 123, 235, 35, 31, 155, 30, 78, 75, 166, 210, 26, 52, 245, 185, 131, 147, 140, 152, 43, 131, 246, 22, 18, 121, 74, 89, 128, 193, 179, 107, 130, 197, 74, 26, 196, 197, 71, 97, 153, 10, 53, 224, 211, 53, 142, 88, 82, 181, 18, 139, 190, 239, 124, 13, 199, 66, 92, 85, 186, 239, 6, 235, 123, 153, 195, 15, 73, 133, 147, 52, 79, 152, 15, 34, 193, 119, 89, 129, 253, 15, 73, 66, 141, 178, 165, 0, 0, 0]`

**Comment by iapicca** [comment] 2021-04-17 08:08
@LQS5858 
this issue doesn't seem to describe a bug or a feature request
if you need assistance with your code please follow the link `I want help writing my application` in the [new issue menu](https://github.com/flutter/flutter/issues/new/choose)
or ask on [discord](https://discord.gg/N7Yshp4), [reddit](https://www.reddit.com/r/FlutterDev/) and [slack](https://fluttercommunity.dev/joinslack) 

if you are reporting a bug, please provide your `flutter doctor -v` your `flutter run -v`
and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by stuartmorgan** [comment] 2021-04-17 15:34
Closing as a duplicate of https://github.com/dart-lang/web_socket_channel/issues/167

Please don't cross-post issues that aren't about Flutter itself to the Flutter issue tracker.

**Closed by stuartmorgan** 2021-04-17 15:34 UTC
