### ISSUE TITLE
Flutter TextField widget problem ..

### ISSUE THREAD

**Issue by imeDevelopers** [flutter/flutter#54557] opened 2020-04-11 18:58 UTC
there is an issue in the last flutter updates .. , if i have focus on some textfield and trying to press the system back button to hide the keyboard .. it dont work , the full android system bottom bar not work if i have complete focus on any text field .. , this happens after i upgraded flutter to latest version ..

android: 9 pie ..
flutter latest in 11/4/2020

**Comment by VladyslavBondarenko** [comment] 2020-04-13 12:19
Hi @imeDevelopers 

<details>
 <summary>I tried with such code</summary>
 
```
import 'package:flutter/material.dart';

void main() => runApp(MaterialApp(home: MyApp()));

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return SafeArea(
      child: Scaffold(
        body: Center(
          child: TextField(),
        )
      ),
    );
  }
}
```

</details>

With `dev v1.18.0` and with `master v1.18.0-5.0.pre.99` with Android 9 device.
System bottom bar is working as intended. 
Can you reproduce the issue with current master version?
Provide please your `flutter doctor -v`

**Comment by imeDevelopers** [comment] 2020-04-14 00:24
[Video](https://drive.google.com/file/d/1XAN133PmpCDNtndvd2SJHLoOkeGwHTh8/view?usp=sharing)


i upgraded before see your comment .. and the problem still exist ..


flutter doctor -v:

`[√] Flutter (Channel master, v1.18.0-6.0.pre.15, on Microsoft Windows [Version 6.1.7601], locale ar-EG)
    • Flutter version 1.18.0-6.0.pre.15 at D:\Android\flutter
    • Framework revision db36d3b98a (49 minutes ago), 2020-04-13 19:15:02 -0400
    • Engine revision deef2663ac
    • Dart version 2.8.0 (build 2.8.0-dev.20.0 c9710e5059)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at D:\Android\sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = D:\Android\sdk
    • Java binary at: D:\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.3.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.3.29409.12

[√] Android Studio (version 3.6)
    • Android Studio at D:\Android\Android Studio
    • Flutter plugin version 40.2.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] Connected device (2 available)
    • RMX1911 • 9fb8e7d7 • android-arm64 • Android 9 (API 28)
    • Windows • Windows  • windows-x64   • Microsoft Windows [Version 6.1.7601]

• No issues found!`

**Comment by VladyslavBondarenko** [comment] 2020-04-14 12:13
@imeDevelopers 
provide please a minimal complete code sample to reproduce your case

**Comment by imeDevelopers** [comment] 2020-04-14 14:24
it's any textfield in the whole app ... , any textfield ....

**Comment by VladyslavBondarenko** [comment] 2020-04-14 15:06
@imeDevelopers 
do you mean bottom bar will not work with this code sample as well https://github.com/flutter/flutter/issues/54557#issuecomment-612875730?
with what devices are you experiencing this?

**Comment by imeDevelopers** [comment] 2020-04-14 15:08
if i pulled the system status bar (for example to see notifications) and pressed system back button it works .. , but without pull the status bar it dont never work .. , i will try your code now .. give me 5 min ..

**Comment by imeDevelopers** [comment] 2020-04-14 15:32
wtf ? it take more than 20 minutes to compile your code in new empty project !! , lol ! , its too long time to compile empty project :-1:

now still compiling

**Comment by imeDevelopers** [comment] 2020-04-14 15:54
your code works fine , and i tried to add texteditingcontroller and focusnode and works fine , i don't know where is the problem in my case !!

**Comment by imeDevelopers** [comment] 2020-04-16 17:58
I remember that i updated android studio from 3.5 to 3.6 before see this problem ..

**Comment by TahaTesser** [comment] 2020-04-23 08:07
Hi @imeDevelopers 
This issue isn't reproducible on latest `master` 

Can you please upgrade to latest `master` and try again?  Also try another device, if it happening on other device too

If you're still experiencing this issue after upgrade to latest `master`
can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by imeDevelopers** [comment] 2020-05-06 11:02
I need to resolve it much more you think .. i dont know where the problem .. any help ? , Any idea ?

**Comment by imeDevelopers** [comment] 2020-05-06 11:03
@TahaTesser
I will try to provide it as soon as possible ..

**Comment by TahaTesser** [comment] 2020-05-29 09:59
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

**Comment by imeDevelopers** [comment] 2020-07-17 21:08
actually [google_maps_flutter] plugin was the reason of all these errors ! , it's the most stupid plugin on earth .. there's no real attention to it .. , i replaced it with [flutter_map] plugin and everything is fixed and all errors are gone ... , tried to get google maps back and the whole errors are back ... , now i use [flutter_map] and will always do until you fix these stupid errors , i set 6 months try to find the reason of these errors , i checked every single part of my app (600MB) , and in the end find that the thing what my app are built on is the problem ! .. now there is no problem of these problems in my app !!

https://github.com/flutter/flutter/issues/55114
https://github.com/flutter/flutter/issues/61322
https://github.com/flutter/flutter/issues/60731

**Comment by iapicca** [comment] 2020-07-20 06:33
Hi @imeDevelopers 
for the issue to be workable needs to be reproducible 
please provide the info requested [above](https://github.com/flutter/flutter/issues/54557#issuecomment-618249332) by @TahaTesser 
Thank you

**Comment by darshankawar** [comment] 2020-09-02 09:52
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by darshankawar** 2020-09-02 09:52 UTC
Labels: in triage, waiting for customer response
