### ISSUE TITLE
[web]: Text doesn't wrap on multiline when used with TextOverflow.ellipsis

### ISSUE THREAD

**Issue by GyuriMajercsik** [flutter/flutter#60274] opened 2020-06-25 11:24 UTC
Below you can find a simple code snippet which reproduces this issue. 

I attached two screenshots, one from my Android device and one from Chrome. 

**Rendered on an Android device:** 
<img width="334" alt="Screenshot 2020-06-25 at 14 11 54" src="https://user-images.githubusercontent.com/1482221/85709716-340d9b00-b6ee-11ea-8f28-e734bf5e4b88.png">

**Rendered on Web:** 
<img width="334" alt="Screenshot 2020-06-25 at 14 10 43" src="https://user-images.githubusercontent.com/1482221/85709760-3ec83000-b6ee-11ea-870a-2edb3a4d6b57.png">

```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Web issue',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: TextWrapIssue(),
    );
  }
}

class TextWrapIssue extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Container(
          decoration: ShapeDecoration(
            shape: CircleBorder(
              side: BorderSide(),
            ),
          ),
          child: Container(
            width: 144,
            height: 144,
            padding: EdgeInsets.all(8),
            child: Center(
              child: Text(
                'Flutter is awesome. Let\'s make it even better.',
                textAlign: TextAlign.center,
                maxLines: 5,
                overflow: TextOverflow.ellipsis,
              ),
            ),
          ),
        ),
      ),
    );
  }
}

```
[✓] Flutter (Channel beta, 1.19.0-4.1.pre, on Mac OS X 10.15.5 19F101, locale en-GB)
    • Flutter version 1.19.0-4.1.pre at /Users/gyuri/tools/flutter
    • Framework revision f994b76974 (2 weeks ago), 2020-06-09 15:53:13 -0700
    • Engine revision 9a28c3bcf4
    • Dart version 2.9.0 (build 2.9.0-14.1.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/gyuri/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (3 available)
    • ONEPLUS A6003 • 192.168.1.116:5555 • android-arm64  • Android 10 (API 29)
    • Web Server    • web-server         • web-javascript • Flutter Tools
    • Chrome        • chrome             • web-javascript • Google Chrome 83.0.4103.116

• No issues found!

**Comment by TahaTesser** [comment] 2020-06-25 14:01
duplicate of https://github.com/flutter/flutter/issues/49594

**Closed by TahaTesser** 2020-06-25 14:01 UTC
