### ISSUE TITLE
Goggle map animate camera does not works for the second time.

### ISSUE THREAD

**Issue by anmolgupta321** [flutter/flutter#144915] opened 2024-03-11 06:51 UTC
### Steps to reproduce

1. initialise a controller inside a provider
2. open the map screen and navigate to camera position
3. pop the screen 
4. again open the map and navigate to camera position

### Expected results

The camera should move.

### Actual results

E/flutter (28717): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method camera#move on channel plugins.flutter.dev/google_maps_android_0)
E/flutter (28717): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:332:7)
E/flutter (28717): <asynchronous suspension>

### Code sample

<details open><summary>Code sample</summary>

```dart
class ItineraryModel extends ChangeNotifier {
  FFLatLng? googleMapsCenter;
  var googleMapsController = Completer<GoogleMapController>();
}


  onUserLocation: (p0) async {
        var controller = await exploreMapModel.googleMapsController.future;
        controller.moveCamera(
          CameraUpdate.newLatLngZoom(
            FFLatLng(p0.latitude!, p0.longitude!).toGoogleMaps(),
            21,
          ),
        );
      },

     if (userLocation != null)
              Positioned(
                top: 16.0,
                right: 16.0,
                child: CircleAvatar(
                  backgroundColor: FlutterFlowTheme.of(context).primary,
                  child: IconButton(
                    onPressed: () async {
                      print(userLocation);
                      if (userLocation != null) {
                        widget.onUserLocation(userLocation!);
                      }
                    },
                    icon: Icon(
                      Icons.my_location,
                      color: FlutterFlowTheme.of(context).secondary,
                    ),
                  ),
                ),
              ),
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
 flutter doctor -v


[✓] Flutter (Channel stable, 3.19.0, on macOS 14.3.1 23D60 darwin-arm64, locale en-IN)
    • Flutter version 3.19.0 on channel stable at /Users/anmolgupta/Downloads/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision bae5e49bc2 (4 weeks ago), 2024-02-13 17:46:18 -0800
    • Engine revision 04817c99c9
    • Dart version 3.3.0
    • DevTools version 2.31.1

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/anmolgupta/Library/Android/sdk
    • Platform android-34, build-tools 33.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    ! Some Android licenses not accepted. To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Community Edition (version 2023.3.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.68.1)
    • VS Code at /Users/anmolgupta/Desktop/Visual Studio Code.app/Contents
    • Flutter extension version 3.60.0

[✓] Connected device (3 available)
    • RMX3242 (mobile) • SOT4RKPRMJWCKRJF • android-arm64  • Android 13 (API 33)
    • macOS (desktop)  • macos            • darwin-arm64   • macOS 14.3.1 23D60 darwin-arm64
    • Chrome (web)     • chrome           • web-javascript • Google Chrome 122.0.6261.112

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

```

</details>

**Comment by danagbemava-nc** [comment] 2024-03-11 13:09
Closing this as a duplicate of https://github.com/flutter/flutter/issues/43785. 

Kindly subscribe to the original issue for updates. 

Thank you

**Closed by danagbemava-nc** 2024-03-11 13:09 UTC
Labels: in triage
