### ISSUE TITLE
The assertion occurred in semantics.dart after upgrade to syncfusion_flutter_calendar: ^18.4.32 

### ISSUE THREAD

**Issue by misici234** [flutter/flutter#73182] opened 2021-01-01 06:33 UTC
[✓] Flutter (Channel stable, 1.22.5, on Mac OS X 10.15.7 19H2 darwin-x64, locale en-CA)
    • Flutter version 1.22.5 at /Users/ABCDEFGHIJKL/Developer/SDKs/flutter
    • Framework revision 7891006299 (3 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

======== Exception caught by scheduler library =====================================================
The following assertion was thrown during a scheduler callback:
Child SemanticsNode#65165(STALE, owner: null, Rect.fromLTRB(50.0, 620.0, 373.0, 619.0), invisible, label: "please come but don’t create duplicate appointment.03 30 PM-03 30 PM 31/December/2020", textDirection: ltr) is invisible and should not be added as a child of SemanticsNode#60135(STALE, owner: null, Rect.fromLTRB(0.0, 350.0, 375.0, 841.0)).
'package:flutter/src/semantics/semantics.dart':
Failed assertion: line 1417 pos 16: '!child.isInvisible'

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

When the exception was thrown, this was the stack: 
#2      SemanticsNode._replaceChildren (package:flutter/src/semantics/semantics.dart:1417:16)
#3      SemanticsNode.updateWith (package:flutter/src/semantics/semantics.dart:1878:5)
#4      RenderObject.assembleSemanticsNode (package:flutter/src/rendering/object.dart:2778:10)
#5      _MultiChildContainerRenderObject.assembleSemanticsNode (package:syncfusion_flutter_calendar/src/calendar/views/multi_child_container.dart:174:11)
#6      _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:3717:13)
...

**Comment by iapicca** [comment] 2021-01-01 09:40
@misici234 
the problem seems to be caused by the 3rd party package [syncfusion_flutter_calendar](https://pub.dev/packages/syncfusion_flutter_calendar) please open an issue in the dedicated [github](https://github.com/syncfusion/flutter-examples/issues)

**Comment by Abhishek01039** [comment] 2021-01-03 18:12
@misici234 
This might be happening because of you are creating appointments at the same time
```
Child SemanticsNode#65165(STALE, owner: null, Rect.fromLTRB(50.0, 620.0, 373.0, 619.0), invisible, label: "please come but don’t create duplicate appointment.03 30 PM-03 30 PM 31/December/2020", textDirection: ltr) is invisible and should not be added as a child of SemanticsNode#60135(STALE, owner: null, Rect.fromLTRB(0.0, 350.0, 375.0, 841.0)).
```

**Comment by pedromassangocode** [comment] 2021-01-04 07:48
Hi @misici234 
From what I can see, the issue is related to a 3rd party plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://pub.dev/packages/syncfusion_flutter_calendar).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by pedromassangocode** 2021-01-04 07:48 UTC
