### ISSUE TITLE
[androidx-migration]

### ISSUE THREAD

**Issue by san-2015** [flutter/flutter#52197] opened 2020-03-08 14:19 UTC
i don't migrate my project to androidx

**Comment by dnfield** [comment] 2020-03-09 05:19
It's not really clear what the issue is here.  If you're looking for instructions about migrating, please see https://flutter.dev/docs/development/androidx-migration

I'm going to close this since it's not really actionable in its current state.  Please feel free to ping the bug if you have additional details to add indicating that there's some bug in Flutter itself.

**Closed by dnfield** 2020-03-09 05:19 UTC
