### ISSUE TITLE
closeButtonLabel on german locales is not displayed correctly on some devices on Android

### ISSUE THREAD

**Issue by knaeckeKami** [flutter/flutter#55202] opened 2020-04-20 14:13 UTC
## Steps to Reproduce
- Use one of the affected devices, e.g. a Samsung A50 Android phone (Unfortunately, I do not own one of the affected devices, I just got a screenshot from a user)
- Set your device locale to german
- Display the localization String "closeButtonLabel", e.g. by calling `showAboutDialog`

**Expected results:**

The String is displayed correctly as "SCHLIEẞEN", as defined in the class MaterialLocalizatonsDe

```dart
  @override
  String get closeButtonLabel => 'SCHLIEẞEN';
```

**Actual results:**

The character "ẞ" is not displayed correctly on some devices. See this screenshot:

https://imgur.com/a/V3HfVNn

**Possible Workarounds**

The character 'ẞ' is quite new and uncommon. It's more common to just use 'SS' instead, so the string could be changed to 'SCHLIESSEN'.

```
[✓] Flutter (Channel beta, v1.17.0, on Mac OS X 10.15.4 19E287, locale en-GB)
    • Flutter version 1.17.0 at /Users/kami/diagnosia/neocortex-mobile/.flutter
    • Framework revision d3ed9ec945 (2 weeks ago), 2020-04-06 14:07:34 -0700
    • Engine revision c9506cb8e9
    • Dart version 2.8.0 (build 2.8.0-dev.18.0 eea9717938)


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/kami/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/kami/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.8.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[!] IntelliJ IDEA Ultimate Edition (version 2019.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.44.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1
```

**Comment by HansMuller** [comment] 2020-04-20 16:07
CC @GaryQian

**Comment by JSANL** [comment] 2020-04-20 22:06
Some context (German here): 

ẞ is uppercase version of the ß in German. 
It was included into Unicode at the beginning of 2008 and is used officially in Germany only since a few years.   
Before that ß was commonly uppercased to "SS".

**Comment by JSANL** [comment] 2020-05-02 11:46
It seems like Google uses the ẞ instead of ss in their YouTube app for dialogs (can't upload an image right now unfortunately).

**Comment by TahaTesser** [comment] 2020-07-09 10:40
Hi @knaeckeKami 
Not able ti reproduce this issue on Samsung device

![flutter_01](https://user-images.githubusercontent.com/48603081/87030048-adcd7a80-c1fe-11ea-8fe8-8740d95fc94c.png)


<details> 
<summary>Code Sample</summary> 

``` 
import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:i18n_example/generated/i18n.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final i18n = I18n.delegate;

    return MaterialApp(
      onGenerateTitle: (context) => I18n.of(context).title,
      theme: ThemeData.dark(),
      home: Home(),
      locale: Locale('de', 'DE'),
      localizationsDelegates: [
        i18n,
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
      ],
      supportedLocales: i18n.supportedLocales,
      localeResolutionCallback: i18n.resolution(
        fallback: Locale('en', 'US'),
      ),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(I18n.of(context).title),
      ),
      body: Center(
        child: Container(
          child: Text(I18n.of(context).greetTo('World!')),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () async {
           showAboutDialog(
              context: context,
              applicationName: 'Flutter',
              applicationIcon: FlutterLogo(),
              applicationVersion: '1.0.0',
              children: [
                Text('This is an About Dialog in Flutter'),
              ]);
        },
      ),
    );
  }
}

``` 

</details> 

<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel dev, 1.20.0-3.0.pre, on Mac OS X 10.15.5 19F101, locale
    en-GB)
    • Flutter version 1.20.0-3.0.pre at /Users/taha/Code/flutter_dev
    • Framework revision 0af027f805 (5 days ago), 2020-07-04 12:19:20 -0700
    • Engine revision a751393804
    • Dart version 2.9.0 (build 2.9.0-20.0.dev 22da8934ac)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/taha/Code/sdk
    • Platform android-30, build-tools 30.0.0
    • ANDROID_HOME = /Users/taha/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.1

[✓] Connected device (4 available)
    • SM M305F (mobile)      • 32003c30dc19668f          • android-arm64  •
      Android 10 (API 29)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios            • iOS
      13.5.1
    • Web Server (web)       • web-server                • web-javascript •
      Flutter Tools
    • Chrome (web)           • chrome                    • web-javascript •
      Google Chrome 83.0.4103.116

• No issues found!
``` 

</details> 

Are you still experiencing this issue on latest `dev` channel? 
If yes, please provide `flutter doctor -v` with latest `dev`
Thank you

**Comment by knaeckeKami** [comment] 2020-07-09 12:05
I could never reproduce it on any of my devices/emulators, I just got a screenshot from a user of their Samsung A50 device with my app.
I haven't heard from them since; it might be fixed by now.

**Comment by TahaTesser** [comment] 2020-07-09 12:54
Hi @knaeckeKami 
given your last message I feel safe to close this issue, if you disagree or issue reproduces on your devices(s) please write in the comments and I will reopen it. 
Thank you

**Closed by TahaTesser** 2020-07-09 12:54 UTC
Labels: a: internationalization, a: typography, e: device-specific, f: material design, framework, platform-android
