### ISSUE TITLE
Flutter caches old exceptions even after fixing and rebuilding when developing on a Mac

### ISSUE THREAD

**Issue by PandaGeek1024** [flutter/flutter#46875] opened 2019-12-12 12:16 UTC
## Steps to Reproduce

_Edit: Added reproduction steps at the top of the issue_

1. Clone the [sample project](https://github.com/shihaohong/locale_test_46875)
2. Make sure you're on Flutter v1.12.13+hotfix.5
3. Start your device/emulator in a Spanish system locale
4. Comment out or remove the global delegates and keep only Custom Delegate
```
localizationsDelegates: [
     AppLocalizationsDelegate()
],
```
5. Build the application, notice the error message:
```
I/flutter (31669): ════════
I/flutter (31669): Warning: This application's locale, es_, is not supported by all of its
I/flutter (31669): localization delegates.
I/flutter (31669): > A MaterialLocalizations delegate that supports the es_ locale was not found.
I/flutter (31669): See https://flutter.dev/tutorials/internationalization/ for more
I/flutter (31669): information about configuring an app's locale, supportedLocales,
I/flutter (31669): and localizationsDelegates parameters.
I/flutter (31669): ════════
I/flutter (31669): 
I/flutter (31669): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY 
```
6. Uncomment or add back the Global Delegates
```
localizationsDelegates: [
        AppLocalizationsDelegate(),
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate
      ],
```
7. Restart/reload the application, and the error message goes away. However, rebuilding the app after stopping the build will cause the error message to resurface(For VSCode, select "start without debugging" after stopping the build).

I'm using the official internationalization approach from the doc, but after upgrade to 1.12.13+hotfix.5, and have android studio + flutter plugin updated to latest version, this error just pops up. It used to work fine. The weird thing is that the error message only shows up before the app runs. The app somehow still works. The only thing that I noticed is on the old version of sdk it returns **es** instead of **es_**. The same for **en** now returns **en_**

```I/flutter (31669): ════════
I/flutter (31669): Warning: This application's locale, es_, is not supported by all of its
I/flutter (31669): localization delegates.
I/flutter (31669): > A MaterialLocalizations delegate that supports the es_ locale was not found.
I/flutter (31669): See https://flutter.dev/tutorials/internationalization/ for more
I/flutter (31669): information about configuring an app's locale, supportedLocales,
I/flutter (31669): and localizationsDelegates parameters.
I/flutter (31669): ════════
I/flutter (31669): 
I/flutter (31669): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY 
```

**Target Platform:** .  Android
**Target OS version/browser:** API 28
**Devices:** Simulator and Samsung device

My Code
```
void main() => runApp(new MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      localizationsDelegates: [
        AppLocalizationsDelegate(),
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate
      ],
      supportedLocales: [const Locale("en"), const Locale("es"), const Locale("fr")],
      onGenerateTitle: (BuildContext context) =>
      AppLocalizations.of(context).title,
      theme: new ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: new MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatelessWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(AppLocalizations.of(context).title),
      ),
      body: Center(
        child: Text(
          AppLocalizations.of(context).hello,
          style: Theme.of(context).textTheme.display1,
        ),
      ),
    );
  }
}
```
```
class AppLocalizations {
  static Future<AppLocalizations> load(Locale locale) {
    final String name =
    locale.countryCode == null ? locale.languageCode : locale.toString();
    final String localeName = Intl.canonicalizedLocale(name);

    return initializeMessages(localeName).then((bool _) {
      Intl.defaultLocale = localeName;
      return new AppLocalizations();
    });
  }

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations);
  }

  String get title {
    return Intl.message('Hello world App',
        name: 'title', desc: 'The application title');
  }

  String get hello {
    return Intl.message('Hello', name: 'hello');
  }
}

class AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    return ['en', 'es', 'fr'].contains(locale.languageCode);
  }

  @override
  Future<AppLocalizations> load(Locale locale) {
    return AppLocalizations.load(locale);
  }

  @override
  bool shouldReload(LocalizationsDelegate<AppLocalizations> old) {
    return false;
  }
}
```

```
```

```
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.14.6 18G103,
    locale en-NZ)
    • Flutter version 1.12.13+hotfix.5 at
      /Users/pengfeihuang/Developer/Flutter/flutter
    • Framework revision 27321ebbad (34 hours ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/pengfeihuang/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/pengfeihuang/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)

[!] IntelliJ IDEA Community Edition (version 2018.3.5)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.40.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API
      28) (emulator)

! Doctor found issues in 1 category.
```

**Comment by iapicca** [comment] 2019-12-12 15:10
Hi @PandaGeek1024 
could you please run
`flutter clean`
`flutter pub cache repair`
let me know if the issue persists
thank you

**Comment by shihaohong** [comment] 2019-12-12 20:08
If the issue still persists, could you also share the contents of your `messages_all.dart` and `messages_<locale>.dart` files? This is so that I can create a small reproducible case to pinpoint the source of the problem.

**Comment by PandaGeek1024** [comment] 2019-12-13 05:30
@iapicca Thanks for your suggestion. Unfortunately, those commands did not help. After a day of testing, I finally caught the pattern. I suspect it is more related to the build cache thing.

The steps to produce are as follow:
1. only provide "AppLocalizationsDelegate()" at the beginning
```
localizationsDelegates: [
     AppLocalizationsDelegate()
],
```
2. Run the app, and caught the exception.
3. Add MaterialLocalizationDelegates back and rerun the app, the exception persists and keeps going on.
```
localizationsDelegates: [
        AppLocalizationsDelegate(),
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate
      ],
```
4. If I restart the device/simulator, here's the magic part, the error is then gone. Builds normally again!

And this can happen to any cases if I do not provide this or that required delegates. But all of the exceptions will be gone if I just restart the device/simulator. It feels like during the build process it somehow cache something that will not let go until the device is restarted.

@shihaohong please check the below code for my messages files
messages_all.dart
```
import 'dart:async';

import 'package:intl/intl.dart';
import 'package:intl/message_lookup_by_library.dart';
import 'package:intl/src/intl_helpers.dart';

import 'messages_en.dart' as messages_en;
import 'messages_es.dart' as messages_es;
typedef Future<dynamic> LibraryLoader();
Map<String, LibraryLoader> _deferredLibraries = {
  'en': () => new Future.value(null),
  'es': () => new Future.value(null),
};

MessageLookupByLibrary _findExact(String localeName) {
  switch (localeName) {
    case 'en':
      return messages_en.messages;
    case 'es':
      return messages_es.messages;
    default:
      return null;
  }
}

/// User programs should call this before using [localeName] for messages.
Future<bool> initializeMessages(String localeName) async {
  var availableLocale = Intl.verifiedLocale(
    localeName,
    (locale) => _deferredLibraries[locale] != null,
    onFailure: (_) => null);
  if (availableLocale == null) {
    return new Future.value(false);
  }
  var lib = _deferredLibraries[availableLocale];
  await (lib == null ? new Future.value(false) : lib());
  initializeInternalMessageLookup(() => new CompositeMessageLookup());
  messageLookup.addLocale(availableLocale, _findGeneratedMessagesFor);
  return new Future.value(true);
}

bool _messagesExistFor(String locale) {
  try {
    return _findExact(locale) != null;
  } catch (e) {
    return false;
  }
}

MessageLookupByLibrary _findGeneratedMessagesFor(String locale) {
  var actualLocale = Intl.verifiedLocale(locale, _messagesExistFor,
      onFailure: (_) => null);
  if (actualLocale == null) return null;
  return _findExact(actualLocale);
}
```
message_en.dart
```
import 'package:intl/intl.dart';
import 'package:intl/message_lookup_by_library.dart';

final messages = new MessageLookup();

typedef String MessageIfAbsent(String messageStr, List<dynamic> args);

class MessageLookup extends MessageLookupByLibrary {
  String get localeName => 'en';

  final messages = _notInlinedMessages(_notInlinedMessages);
  static _notInlinedMessages(_) => <String, Function> {
    "hello" : MessageLookupByLibrary.simpleMessage("Hello"),
    "title" : MessageLookupByLibrary.simpleMessage("Hello world App")
  };
}
```
message_es.dart
```
import 'package:intl/intl.dart';
import 'package:intl/message_lookup_by_library.dart';

final messages = new MessageLookup();

typedef String MessageIfAbsent(String messageStr, List<dynamic> args);

class MessageLookup extends MessageLookupByLibrary {
  String get localeName => 'es';

  final messages = _notInlinedMessages(_notInlinedMessages);
  static _notInlinedMessages(_) => <String, Function> {
    "hello" : MessageLookupByLibrary.simpleMessage("Hola"),
    "title" : MessageLookupByLibrary.simpleMessage("App Hola Mundo")
  };
}
```

**Comment by shihaohong** [comment] 2019-12-13 19:23
@PandaGeek1024 Hmm, that's interesting. I would imagine that your app should have this from the get-go: 
```
localizationsDelegates: [
        AppLocalizationsDelegate(),
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate
      ],
```

At what point or how do you initially end up with `AppLocalizationsDelegate()` and not the rest of the delegates? The error you're experiencing sounds like it should occur before even before your upgrade. Since your app does not have access to the `MaterialLocalizations` delegate at first, the error is thrown because it does not have access to your translated messages, and upon adding the delegates and a simulator restart, all delegates are correctly loaded and your app is able to access the necessarily translated messages for your application.

**Comment by PandaGeek1024** [comment] 2019-12-15 21:48
@shihaohong I was following a tutorial that only came with AppLocalizationsDelegate() and ran into that issue. I originally thought it was the tutorial approach messed up something but eventually found out it happened to the official approach as well.

Your last statement is correct. The only problem would be the weird persistence of exception even when all codes are corrected.

**Comment by shihaohong** [comment] 2019-12-16 05:31
I'm not quite sure what you mean. So you're saying that with the full, correct list of localizations delegates, upon running your app, you see an exception, but upon restarting your app, the exception goes away? And does it only go away upon restarting, or also when hot reloading? 

Could you also point out where the exception occurs following the official approach and where you're referencing the official approach?

**Comment by PandaGeek1024** [comment] 2019-12-16 11:59
I will try to make it more clear. With the above code that I provided,

1. When I first have this
```
localizationsDelegates: [
        AppLocalizationsDelegate(),
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate
      ],
```
It works fine.

2. But when I remove the globbal delegates:
```
localizationsDelegates: [
     AppLocalizationsDelegate()
]
```
The error occurs
```
A MaterialLocalizations delegate that supports the es_ locale was not found.
```
It appears right before the app runs, but app still works fine.

3. Even when I put the global delegates back again, the error still exists on every build( right before the app is started). More interestingly, when I build other projects, the error appears in android studio as well(That's why I believe this is the build cache issue).

4. Restart the device/simulator, then the error is gone.

I can provide a sample project for you to test if that's necessary.

**Comment by shihaohong** [comment] 2019-12-17 17:59
I could not reproduce it with the code you provided. Here is the [sample project I created](https://github.com/shihaohong/locale_test_46875). 

Here is the results of flutter doctor -v:
```
[✓] Flutter (Channel unknown, v1.12.13+hotfix.5, on Linux, locale en_US.UTF-8)
    • Flutter version 1.12.13+hotfix.5
    • Framework revision 27321ebbad (7 days ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[!] Android Studio (version 4.0)
    • Android Studio at /opt/android-studio-with-blaze-4.0
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.39.2)
    • Flutter extension version 3.7.1

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)
```

**Comment by PandaGeek1024** [comment] 2019-12-17 22:29
@shihaohong Have you tried to change the locale on the device/simulator? It works fine at the beginning with English as default locale for me too. But when I change to another locale, Spanish in my case, the error pops up. I have tried your sample project as well, works fine with English but error when change device to Spanish.
![image](https://user-images.githubusercontent.com/3827781/71039616-6c557f00-2189-11ea-9085-d3fbf15dca73.png)

**Comment by shihaohong** [comment] 2019-12-17 22:35
I tried switching to Spanish while the app was already running and I don't run into any errors.

![image](https://user-images.githubusercontent.com/27032613/71040036-81270980-20da-11ea-8575-b2e1fadc1402.png)

**Comment by PandaGeek1024** [comment] 2019-12-17 22:51
Weird. Have you tried
1. change device locale to Spanish first
2. remove global delegates but keeps AppLocalizationsDelegate() and run the app?

**Comment by shihaohong** [comment] 2019-12-17 22:57
I've tried starting with Spanish. Why would you remove the global delegates and run the app?

**Comment by PandaGeek1024** [comment] 2019-12-17 23:02
I understand that we should keep the global delegates, the steps that I state is just to help reproduce the issues. I think the main problem in my case is even when I add the global delegates back, the error still persists.

**Comment by shihaohong** [comment] 2019-12-17 23:53
The reason I asked again was I wasn't sure what exact workflow you'd like me to test, and the first thing that came to mind was if the app would just work with the correct code in it. Now, if I understand your question correctly, I think you're asking if the app, after starting in an erroneous state, would still persist in an erroneous state after fixing the issue and reload/restarting the app.

It seems to work fine on my end, I don't see any persistent error messages. 

## When I start without the global delegates and in Spanish:
My code:
```
  Widget build(BuildContext context) {
    return MaterialApp(
      localizationsDelegates: [
        AppLocalizationsDelegate(),
        // GlobalMaterialLocalizations.delegate,
        // GlobalWidgetsLocalizations.delegate,
        // GlobalCupertinoLocalizations.delegate
      ],
      supportedLocales: [const Locale("en"), const Locale("es"), const Locale("fr")],
      onGenerateTitle: (BuildContext context) =>
      AppLocalizations.of(context).title,
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
```
Expected error message:
```
I/flutter (15164): ════════
I/flutter (15164): Warning: This application's locale, es, is not supported by all of its
I/flutter (15164): localization delegates.
I/flutter (15164): > A MaterialLocalizations delegate that supports the es locale was not found.
I/flutter (15164): See https://flutter.dev/tutorials/internationalization/ for more
I/flutter (15164): information about configuring an app's locale, supportedLocales,
I/flutter (15164): and localizationsDelegates parameters.
I/flutter (15164): ════════
I/flutter (15164):
I/flutter (15164): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (15164): The following assertion was thrown building AppBar(dirty, dependencies:
I/flutter (15164): [_LocalizationsScope-[GlobalKey#21a9f]], state: _AppBarState#763f5):
I/flutter (15164): No MaterialLocalizations found.
I/flutter (15164): AppBar widgets require MaterialLocalizations to be provided by a Localizations widget ancestor.
I/flutter (15164): Localizations are used to generate many different messages, labels,and abbreviations which are used
I/flutter (15164): by the material library.
```
App:
![image](https://user-images.githubusercontent.com/27032613/71043853-c5b7a280-20e4-11ea-806f-dc90cecb5ee8.png)

## After adding them back in and hot reloading the app:
Code:
```
  Widget build(BuildContext context) {
    return MaterialApp(
      localizationsDelegates: [
        AppLocalizationsDelegate(),
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate
      ],
      supportedLocales: [const Locale("en"), const Locale("es"), const Locale("fr")],
      onGenerateTitle: (BuildContext context) =>
      AppLocalizations.of(context).title,
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
```
Output:
```
Reloaded 1 of 497 libraries in 296ms.
```
App:
![image](https://user-images.githubusercontent.com/27032613/71043825-b46e9600-20e4-11ea-8222-8e6273a8fcbe.png)

**Comment by shihaohong** [comment] 2019-12-18 01:35
@PandaGeek1024 Let me know if I'm missing something or if there's some configuration I do not have right, but basically this was the main changes I saw running the latest stable on the sample app I shared earlier in this issue. I tested on an API 29 Android emulator

**Comment by PandaGeek1024** [comment] 2019-12-18 01:49
thanks for your patience @shihaohong. So Im assuming you are using VSCode? I just did some test on VSCode as well, looks like hot reload works for me too. But after I stopped the build and run "Start without debugging", the error happens again.

**Comment by PandaGeek1024** [comment] 2019-12-18 01:52
For some reason hot reload works but not for re-running the app

**Comment by shihaohong** [comment] 2019-12-18 02:37
Oh that might be a caching thing. When you stop the build, try deleting the app from the device/emulator, and then try re-running it again

**Comment by PandaGeek1024** [comment] 2019-12-18 03:19
I have tried deleted the app and rebuilt, error log still exist. The only way to get rid of it so far is to restart the device/simulator.

**Comment by maheshmnj** [comment] 2019-12-18 05:30
@PandaGeek1024  can you please try ```flutter clean ``` and do a hot restart and not hot reload after you add/remove a Global Delegate in the Material App.

**Comment by shihaohong** [comment] 2019-12-18 17:37
Definitely try @maheshmnj's suggestion as well, but I still cannot reproduce the error that you're seeing. 

I'll update the the first comment on the issue and the remove the `regression` tag with your reproduction steps and unassign myself for now, but I'll monitor this thread in case anything comes up!

**Comment by shihaohong** [comment] 2019-12-18 17:41
Also, please revise the reproduction steps if they're incorrect

**Comment by PandaGeek1024** [comment] 2019-12-19 02:04
@maheshmnj thanks for your suggestion, I have already tried that and it did not work.

@shihaohong I have added a bit more detail to the reproduction steps but basically should be no big difference. Can you please review it to see if that's exactly what you have done? 

I have also tried re-download the sdk, clean the pub cache, re-install android studio but the error still exists. I have also tried them on the home mac and office mac and both reproducible. If that's still not the case for you, I guess I will just live with restarting the device then. Until eventually someone else also face the same issue so that we can have a bit more information on this. 

Btw, really appreciate your effort on this. Thanks.

**Comment by shihaohong** [comment] 2019-12-19 04:52
Thanks for adding to the reproduction steps, I think I actually managed to reproduce the issue! 

What's really strange is that I'm pretty sure I tried those exact steps before, but the only difference is that I tested it on my mac instead of my linux machine at work. I'll confirm this hypothesis and also test to see if this occurs with the previous stable version as well.

I'll update this thread tomorrow when I get into work.

**Comment by PandaGeek1024** [comment] 2019-12-19 04:55
yeah, probably a mac specific issue?

**Comment by shihaohong** [comment] 2019-12-19 05:06
I can also confirm it's not IDE-specific, since flutter run in the terminal displays the same warning.

**Comment by shihaohong** [comment] 2019-12-26 16:40
I just tested it on my Linux machine and could not reproduce it. This is likely a Mac-specific issue, but it's unclear why this is the case.

**Comment by PandaGeek1024** [comment] 2020-01-05 22:21
Yeah, it is probably some cache is not cleared on the Mac during re-run.

**Comment by PandaGeek1024** [comment] 2020-01-31 02:31
Ok, looks like when you encounter some other exceptions on Mac, it will cache the log as well.
When Im debugging with following code that assert fail
`assert(exception is PlatformException || exception is MissingPluginException),`
It keeps reporting the below log, this is an annoying issue. I have to restart and clean cache the AS every time to get rid of it.

`E/flutter (28340): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: 'package:track_sdk_plugin/exception/track_sdk_exception.dart': Failed assertion: line 19 pos 16: 'exception is PlatformException || exception is MissingPluginException': is not true.
E/flutter (28340): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:42:39)
E/flutter (28340): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:38:5)
E/flutter (28340): #2      new TrackSDKException.fromException (package:track_sdk_plugin/exception/track_sdk_exception.dart:19:16)`

**Comment by shihaohong** [comment] 2020-01-31 16:05
@jonahwilliams would this be a tool issue, or something else?

**Comment by jonahwilliams** [comment] 2020-01-31 17:35
The tool isn't directly involved with intl work - there is of course package:intl stuff + flutter_localizations

**Comment by shihaohong** [comment] 2020-01-31 18:12
Based on the latest comment, it seems like it might be a general problem for Mac exceptions that isn't just the `intl` package and/or flutter_localizations

**Comment by PandaGeek1024** [comment] 2020-01-31 20:45
Could be related to this [bug](https://github.com/flutter/flutter/issues/47629)?

**Comment by shihaohong** [comment] 2020-01-31 21:06
It does seem related, but that issue is specific to Android, so let's keep a separate issue (this one) open to track the Mac side of things. I'll also update the title of the issue to be more correct, since it's unlikely that it's specific to just localizations delegates

**Comment by jonahwilliams** [comment] 2020-01-31 21:15
Is the problem _just_ that the logs are stale, or is the application actually crashing as well?

**Comment by PandaGeek1024** [comment] 2020-02-03 05:29
@jonahwilliams it just keeps showing the previous log even though the app runs absolutely fine.

**Comment by jonahwilliams** [comment] 2020-02-03 17:41
Since this is android, this is a duplicate of https://github.com/flutter/flutter/issues/47629 .

**Comment by jmagman** [comment] 2020-02-04 22:27
Closing as duplicate of https://github.com/flutter/flutter/issues/47629.

**Closed by jmagman** 2020-02-04 22:27 UTC
Labels: tool, ⌺‬ platform-ios
