### ISSUE TITLE
Implement hotfix for quick bug fixing like CodePush

### ISSUE THREAD

**Issue by byemylove203** [flutter/flutter#123996] opened 2023-04-03 08:21 UTC
## Use case

Codepush is such a powerful feature that allows developers to instantly deploy mobile updates to end users. I hope flutter will have this feature for quick bug fixing.

## Proposal
- Implement hotfix module like Codepush

**Comment by danagbemava-nc** [comment] 2023-04-03 09:09
Closing this as a duplicate of https://github.com/flutter/flutter/issues/14330.

**Closed by danagbemava-nc** 2023-04-03 09:09 UTC
Labels: in triage
