### ISSUE TITLE
[tool_crash] FileSystemException: Failed to decode data using encoding 'utf-8', null

### ISSUE THREAD

**Issue by TanmaySurlekar-Octalogic** [flutter/flutter#154535] opened 2024-09-03 07:28 UTC
## Command
```
flutter build ios
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Failed to decode data using encoding 'utf-8', null
```
#0      _File._tryDecode (dart:io/file_impl.dart:615:7)
#1      _File.readAsStringSync (dart:io/file_impl.dart:624:7)
#2      _File.readAsLinesSync (dart:io/file_impl.dart:630:36)
#3      ForwardingFile.readAsLinesSync (package:file/src/forwarding/forwarding_file.dart:107:16)
#4      ForwardingFile.readAsLinesSync (package:file/src/forwarding/forwarding_file.dart:107:16)
#5      ProjectMigrator.processFileLines (package:flutter_tools/src/base/project_migrator.dart:40:37)
#6      IOSDeploymentTargetMigration.migrate (package:flutter_tools/src/ios/migrations/ios_deployment_target_migration.dart:31:7)
#7      ProjectMigration.run (package:flutter_tools/src/base/project_migrator.dart:84:16)
#8      buildXcodeProject (package:flutter_tools/src/ios/mac.dart:138:13)
#9      _BuildIOSSubCommand.runCommand (package:flutter_tools/src/commands/build_ios.dart:650:43)
<asynchronous suspension>
#10     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1336:27)
<asynchronous suspension>
#11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#12     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#13     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:296:9)
<asynchronou

**Comment by danagbemava-nc** [comment] 2024-09-03 08:46
Closing this as a duplicate of https://github.com/flutter/flutter/issues/65021

**Closed by danagbemava-nc** 2024-09-03 08:46 UTC
Labels: in triage
