### ISSUE TITLE
can not run my web app on chrome; help please

### ISSUE THREAD

**Issue by ah1me5d04** [flutter/flutter#73562] opened 2021-01-08 15:47 UTC
when i am trying to run or debug it i get this error:

> Unable to connect to Chrome debug port: 36237
 HttpException: Connection closed before full header was received, uri = http://localhost:36237/json
Exited (1)
### that is flutter doctor result 
![DeepinScreenshot_select-area_20210108165436](https://user-images.githubusercontent.com/62748691/104035190-8457d080-51da-11eb-9a5d-acadd464bebe.png)
**i am using chromium om manjaro linux + vs code as IDE**

**Comment by iapicca** [comment] 2021-01-08 16:42
@ah1me5d04 
I cannot reproduce the issue on ubuntu 20.04

<details>
<summary>logs</summary>

```bash
[ +243 ms] Launching lib/main.dart on Chrome in debug mode...
[ +182 ms] Updating assets
[ +270 ms] Waiting for connection from debug service on Chrome...
[  +58 ms] Found plugin integration_test at /home/francesco/snap/flutter/common/flutter/packages/integration_test/
[  +54 ms] Found plugin integration_test at /home/francesco/snap/flutter/common/flutter/packages/integration_test/
[  +51 ms] <- reset
[  +11 ms] /home/francesco/snap/flutter/common/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev
/home/francesco/snap/flutter/common/flutter/bin/cache/artifacts/engine/linux-x64/frontend_server.dart.snapshot --sdk-root /home/francesco/snap/flutter/common/flutter/bin/cache/flutter_web_sdk/
--incremental --target=dartdevc --debugger-module-names --experimental-emit-debug-metadata --output-dill /tmp/flutter_tools.UOKOKJ/flutter_tool.QUSSLY/app.dill --libraries-spec
file:///home/francesco/snap/flutter/common/flutter/bin/cache/flutter_web_sdk/libraries.json --packages /home/francesco/projects/issue/.dart_tool/package_config.json -Ddart.vm.profile=false
-Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-root /tmp/flutter_tools.UOKOKJ/flutter_tools.ZVAOWD --filesystem-scheme org-dartlang-app --initialize-from-dill
build/fbbe6a61fb7a1de317d381f8df4814e5.cache.dill.track.dill --platform file:///home/francesco/snap/flutter/common/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk.dill --no-sound-null-safety
[  +42 ms] <- compile org-dartlang-app:/web_entrypoint.dart
[+26329 ms] Waiting for connection from debug service on Chrome... (completed in 26.5s)
[        ] Synced 28.7MB.
[        ] <- accept
[        ] Caching compiled dill
[ +384 ms] Using Chromium 87.0.4280.141 snap

[ +596 ms] [CHROME]:
[        ] [CHROME]:(chrome:224079): Gtk-WARNING **: 18:37:46.009: Theme parsing error: gtk.css:1555:23: 'font-feature-settings' is not a valid property name
[   +3 ms] [CHROME]:
[        ] [CHROME]:(chrome:224079): Gtk-WARNING **: 18:37:46.014: Theme parsing error: gtk.css:3591:25: 'font-feature-settings' is not a valid property name
[   +1 ms] [CHROME]:
[        ] [CHROME]:(chrome:224079): Gtk-WARNING **: 18:37:46.016: Theme parsing error: gtk.css:4053:23: 'font-feature-settings' is not a valid property name
[ +711 ms] [CHROME]:
[        ] [CHROME]:DevTools listening on ws://127.0.0.1:45607/devtools/browser/8c32b3f0-debe-4ff6-8fe1-38c5467a5fc5
[+3805 ms] DwdsInjector: Received request for entrypoint at http://localhost:34741/main_module.bootstrap.js
[  +42 ms] MetadataProvider: Loading debug metadata...
[  +41 ms] MetadataProvider: Loaded debug metadata
[  +20 ms] DwdsInjector: Injected debugging metadata for entrypoint at http://localhost:34741/main_module.bootstrap.js
[+3987 ms] DevHandler: Debug service listening on ws://127.0.0.1:46691/lGi0TKU7I1A=/ws

[  +23 ms] Debug service listening on ws://127.0.0.1:46691/lGi0TKU7I1A=/ws
[        ] Running with unsound null safety
[        ] For more information see https://dart.dev/null-safety/unsound-null-safety
[   +1 ms] Warning: Flutter's support for web development is not stable yet and hasn't
[        ] been thoroughly tested in production environments.
[        ] For more information see https://flutter.dev/web
[        ] 🔥  To hot restart changes while running, press "r" or "R".
[   +2 ms] For a more detailed help message, press "h". To quit, press "q".
[+11496 ms] Application finished.
[   +6 ms] "flutter run" took 49,094ms.
[  +10 ms] DevHandler: Stopped debug service on ws://127.0.0.1:38323

[ +245 ms] ensureAnalyticsSent: 251ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hook priority 4
[   +1 ms] Shutdown hooks complete
[        ] exiting with code 0

```
</details>

<details>
<summary>doctor & neofetch</summary>

```console
[✓] Flutter (Channel master, 1.26.0-2.0.pre.251, on Linux, locale en_US.UTF-8)
    • Flutter version 1.26.0-2.0.pre.251 at /home/francesco/snap/flutter/common/flutter
    • Framework revision 5bc725bea8 (9 hours ago), 2021-01-08 08:12:36 +0100
    • Engine revision 2e5833b7c5
    • Dart version 2.12.0 (build 2.12.0-179.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/francesco/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_SDK_ROOT = /home/francesco/Android/Sdk
    • Java binary at: /usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_275-8u275-b01-0ubuntu1~20.04-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /snap/bin/chromium

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Linux
    • Chrome (web)    • chrome • web-javascript • Chromium 87.0.4280.141 snap

! Doctor found issues in 1 category.

```
```bash
            .-/+oossssoo+/-.               francesco@francesco-yoga720 
        `:+ssssssssssssssssss+:`           --------------------------- 
      -+ssssssssssssssssssyyssss+-         OS: Ubuntu 20.04.1 LTS x86_64 
    .ossssssssssssssssssdMMMNysssso.       Host: 80X6 Lenovo YOGA 720-13IKB 
   /ssssssssssshdmmNNmmyNMMMMhssssss/      Kernel: 5.8.0-34-generic 
  +ssssssssshmydMMMMMMMNddddyssssssss+     Uptime: 3 hours, 59 mins 
 /sssssssshNMMMyhhyyyyhmNMMMNhssssssss/    Packages: 1736 (dpkg), 6 (flatpak), 27 (snap) 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Shell: bash 5.0.17 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   Resolution: 1920x1080 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   DE: GNOME 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   WM: Mutter 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   WM Theme: Adwaita 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Theme: Yaru-dark [GTK2/3] 
 /sssssssshNMMMyhhyyyyhdNMMMNhssssssss/    Icons: Yaru [GTK2/3] 
  +sssssssssdmydMMMMMMMMddddyssssssss+     Terminal: gnome-terminal 
   /ssssssssssshdmNNNNmyNMMMMhssssss/      CPU: Intel i5-7200U (4) @ 2.500GHz 
    .ossssssssssssssssssdMMMNysssso.       GPU: Intel HD Graphics 620 
      -+sssssssssssssssssyyyssss+-         Memory: 5587MiB / 7685MiB 
        `:+ssssssssssssssssss+:`
            .-/+oossssoo+/-.                                       
                                                                   
```

</details>

can you run the following and provide your logs

```console
flutter create issue
cd issue
flutter run -d chrome -v
```

**Comment by AbhishekDoshi26** [comment] 2021-01-08 18:57
Hey @ah1me5d04 are you using any HTTP call in initState()?

**Comment by iapicca** [comment] 2021-01-08 21:09
@AbhishekDoshi26 
I just run the commands I listed above

> ```
> flutter create issue
> cd issue
> flutter run -d chrome -v
> ```

I thought you were reporting a bug
if that's the case and assuming the with the steps above don't produce any crash
the issue might depend from your code
please provide a minimal reproducible code sample

if instead you need assistance with your code
please follow the link `I want help writing my application` in the [new issue choice](https://github.com/flutter/flutter/issues/new/choose)

**Comment by darshankawar** [comment] 2021-01-11 06:58
@ah1me5d04 
As suggested above, please provide a minimal complete reproducible code sample along with `pubspec.yaml` that shows the issue you are facing.
Thanks.

**Comment by pedromassangocode** [comment] 2021-02-03 15:11
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2021-02-03 15:11 UTC
Labels: in triage, waiting for customer response
