### ISSUE TITLE
[tool_crash] SocketException: Send failed, OS Error: No route to host, errno = 65

### ISSUE THREAD

**Issue by jsalmond** [flutter/flutter#159651] opened 2024-12-01 20:08 UTC
## Command
```sh
flutter --no-color run --machine --track-widget-creation --device-id=00008140-00022D3A2EC0801C --start-paused --dart-define=flutter.inspector.structuredErrors=true lib/main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
SocketException: Send failed, OS Error: No route to host, errno = 65
```console
#0      _NativeSocket.send (dart:io-patch/socket_patch.dart:1275:34)
#1      _RawDatagramSocket.send (dart:io-patch/socket_patch.dart:2590:15)
#2      MDnsClient.lookup (package:multicast_dns/multicast_dns.dart:219:22)
#3      MDnsVmServiceDiscovery._pollingVmService (package:flutter_tools/src/mdns_discovery.dart:232:66)
<asynchronous suspension>
#4      MDnsVmServiceDiscovery.firstMatchingVmService (package:flutter_tools/src/mdns_discovery.dart:188:56)
<asynchronous suspension>
#5      MDnsVmServiceDiscovery.getVMServiceUriForLaunch (package:flutter_tools/src/mdns_discovery.dart:433:50)
<asynchronous suspension>
#6      Future.any.onValue (dart:async/future.dart:628:5)
<asynchronous suspension>
```
```console
[✓] Flutter (Channel stable, 3.24.2, on macOS 15.0 24A335 darwin-arm64, locale en-US)
    • Flutter version 3.24.2 on channel stable at /Users/josephsalmond/Documents/FlutterDev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cf269e36d (3 months ago), 2024-09-03 14:30:00 -0700
    • Engine revision a6bd3f1de1
    • Dart version 3.5.2
    • DevTools version 2.37.2

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/josephsalmond/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 21.0.3+-79915917-b509.11)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16B40
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.3+-79915917-b509.11)

[✓] VS Code (version 1.94.2)
    • VS Code at /Users/josephsalmond/Desktop/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (4 available)
    • Joseph Salmond’s iPhone (mobile) • 00008140-00022D3A2EC0801C • ios            • iOS 18.1.1 22B91
    • macOS (desktop)                  • macos                     • darwin-arm64   • macOS 15.0 24A335 darwin-arm64
    • Mac Designed for iPad (desktop)  • mac-designed-for-ipad     • darwin         • macOS 15.0 24A335 darwin-arm64
    • Chrome (web)                     • chrome                    • web-javascript • Google Chrome 131.0.6778.86
    ! Error: Browsing on the local area network for iPad. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 2.0.2+137
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 4cf269e36de2573851eaef3c763994f8f9be494d
### Plugins
audioplayers-6.1.0
audioplayers_android-5.0.0
audioplayers_darwin-6.0.0
audioplayers_linux-4.0.0
audioplayers_web-5.0.1
audioplayers_windows-4.0.0
cloud_firestore-4.17.5
cloud_firestore_web-3.12.5
cloud_functions-4.7.6
cloud_functions_web-4.9.6
connectivity_plus-6.0.5
device_info_plus-10.1.2
file_picker-8.0.7
file_selector_linux-0.9.2+1
file_selector_macos-0.9.4
file_selector_windows-0.9.3+2
firebase_analytics-10.10.5
firebase_analytics_web-0.5.7+7
firebase_auth-4.20.0
firebase_auth_web-5.12.0
firebase_core-2.32.0
firebase_core_web-2.17.5
firebase_remote_config-4.4.7
firebase_remote_config_web-1.6.7
firebase_storage-11.6.5
firebase_storage_web-3.6.22
flutter_plugin_android_lifecycle-2.0.22
fluttertoast-8.2.8
google_sign_in-6.2.1
google_sign_in_android-6.1.30
google_sign_in_ios-5.7.7
google_sign_in_web-0.12.4+2
image_picker-1.1.2
image_picker_android-0.8.12+13
image_picker_for_web-3.0.5
image_picker_ios-0.8.12
image_picker_linux-0.2.1+1
image_picker_macos-0.2.1+1
image_picker_windows-0.2.1+1
in_app_purchase-3.2.0
in_app_purchase_android-0.3.6+8
in_app_purchase_storekit-0.3.18+1
launch_app_store-1.1.2
package_info_plus-8.0.2
path_provider-2.1.4
path_provider_android-2.2.10
path_provider_foundation-2.4.0
path_provider_linux-2.2.1
path_provider_windows-2.3.0
permission_handler-11.3.1
permission_handler_android-12.0.12
permission_handler_apple-9.4.5
permission_handler_html-0.1.3+2
permission_handler_windows-0.2.1
shared_preferences-2.3.2
shared_preferences_android-2.3.2
shared_preferences_foundation-2.5.2
shared_preferences_linux-2.4.1
shared_preferences_web-2.4.2
shared_preferences_windows-2.4.1
sign_in_with_apple-6.1.2
sign_in_with_apple_web-2.1.0
syncfusion_flutter_pdfviewer-26.2.14
syncfusion_pdfviewer_macos-26.2.14
syncfusion_pdfviewer_web-26.2.14
syncfusion_pdfviewer_windows-26.2.14
url_launcher-6.3.0
url_launcher_android-6.3.10
url_launcher_ios-6.3.1
url_launcher_linux-3.2.0
url_launcher_macos-3.2.0
url_launcher_web-2.3.3
url_launcher_windows-3.1.2
video_player-2.8.6
video_player_android-2.7.3
video_player_avfoundation-2.6.1
video_player_web-2.3.2

**Comment by jsalmond** [comment] 2024-12-01 20:09
will not run on android studios on my iphone 16 pro max but if i run it from xcode it works just fine why?

**Comment by danagbemava-nc** [comment] 2024-12-02 09:05
Closing this as a duplicate of https://github.com/flutter/flutter/issues/150131

Kindly try https://github.com/flutter/flutter/issues/150131#issuecomment-2366836574 to see if it helps

**Closed by danagbemava-nc** 2024-12-02 09:05 UTC
Labels: in triage
