### ISSUE TITLE
Flutter exception handler for plugins exceptions

### ISSUE THREAD

**Issue by JCKodel** [flutter/flutter#73117] opened 2020-12-29 22:54 UTC
## Use case

I don't know why, but plugins like https://github.com/MaikuB/flutter_local_notifications sometimes just crashes (it's not something wrong with the code, nor the device model - I have 3.5 million downloads and a few thousand of devices have exceptions while trying to setup or trigger a local notification - and most of the time there crashes and non-crashes for the same device model).

Being unable to find the reason and fixed, my only option is to hack the native code with `try{}catch{}`, ignoring such exceptions (my users won't have notifications, but at least they can use the app).

## Proposal

Let's take Android, for example. When Dart invokes a method from a plugin, the Flutter engine runs the native Java method from `FlutterPlugin`: `public void onMethodCall(MethodCall call, Result result)`.

My proposal is to Flutter engine intercept any exceptions on any native methods (`init` included) and then throws a Dart `PlatformException` exception, so we can decide what to do in Dart code (at least the app won't crash and terminate).

So the Flutter engine native code that calls a plugin will be enveloped in a try catch statement and, in the case of an exception, it will generate a `PlatformException` with the native error message.

The whole point is to be able to treat native exceptions without changing the plugin source code (that would require us to fork and mantain the sync for each plugin).

**Comment by zanderso** [comment] 2021-05-26 23:19
FYI @stuartmorgan

**Comment by stuartmorgan** [comment] 2021-06-03 19:14
> My proposal is to Flutter engine intercept any exceptions on any native methods (`init` included) and then throws a Dart `PlatformException` exception, so we can decide what to do in Dart code (at least the app won't crash and terminate).
> 
> So the Flutter engine native code that calls a plugin will be enveloped in a try catch statement and, in the case of an exception, it will generate a `PlatformException` with the native error message.

Can you provide some concrete examples? It's not at all clear to me how what you are describing here is different from https://github.com/flutter/engine/blob/138c91c614d742c52aa5432b4cb921f0ff9fdee2/shell/platform/android/io/flutter/plugin/common/MethodChannel.java#L232-L256

**Comment by JCKodel** [comment] 2021-06-03 20:33
@stuartmorgan Plugins often crashes the app (a "native" Java/Kotlin crash that will terminate the app).

For instance:

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void io.flutter.plugin.common.MethodChannel.invokeMethod(java.lang.String, java.lang.Object, io.flutter.plugin.common.MethodChannel$Result)' on a null object reference
       at io.flutter.plugins.firebase.auth.FlutterFirebaseAuthPlugin.lambda$null$1$FlutterFirebaseAuthPlugin(FlutterFirebaseAuthPlugin.java:546)
       at io.flutter.plugins.firebase.auth.-$$Lambda$FlutterFirebaseAuthPlugin$SQAGnfsVv7byAY7rk65tey1yNTg.onIdTokenChanged(:4)
```

For some reason, `firebase_auth` crashes and terminates the app.

Here's another example with Google Ads plugin:

```
Fatal Exception: java.lang.IllegalArgumentException: Could not find a string for errorCode: 0
       at io.flutter.plugins.webviewflutter.FlutterWebViewClient.errorCodeToString(FlutterWebViewClient.java:77)
       at io.flutter.plugins.webviewflutter.FlutterWebViewClient.onWebResourceError(FlutterWebViewClient.java:142)
       at io.flutter.plugins.webviewflutter.FlutterWebViewClient.access$300(FlutterWebViewClient.java:29)
       at io.flutter.plugins.webviewflutter.FlutterWebViewClient$1.onReceivedError(FlutterWebViewClient.java:195)
       at h9.handleMessage(chromium-TrichromeWebViewGoogle.aab-stable-447207730:124)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:7814)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)
```

The last one was clearly from a plugin, but it is not clear if it was a direct call.

Here is one that triggers often because I'm too lazy to implement a disk free checking before trying to create a database:

```
Fatal Exception: android.database.sqlite.SQLiteFullException: disk I/O error (code 7178): , while compiling: PRAGMA journal_mode
#################################################################
Error Code : 7178 (SQLITE_IOERR_SHMSIZE_FULL)
Caused By : No available space in disk.(ENOSPC)
	(disk I/O error (code 7178): , while compiling: PRAGMA journal_mode)
#################################################################
       at android.database.sqlite.SQLiteConnection.nativePrepareStatement(SQLiteConnection.java)
       at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1062)
       at android.database.sqlite.SQLiteConnection.executeForString(SQLiteConnection.java:766)
       at android.database.sqlite.SQLiteConnection.setJournalMode(SQLiteConnection.java:443)
       at android.database.sqlite.SQLiteConnection.setWalModeFromConfiguration(SQLiteConnection.java:414)
       at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:315)
       at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:210)
       at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:512)
       at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:206)
       at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:178)
       at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:925)
       at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:895)
       at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:708)
       at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:646)
       at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:283)
       at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:223)
       at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163)
       at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.getWritableSupportDatabase(FrameworkSQLiteOpenHelper.java:92)
       at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper.getWritableDatabase(FrameworkSQLiteOpenHelper.java:53)
       at androidx.room.RoomDatabase.beginTransaction(RoomDatabase.java:328)
       at androidx.work.impl.utils.ForceStopRunnable.cleanUp(ForceStopRunnable.java:135)
       at androidx.work.impl.utils.ForceStopRunnable.run(ForceStopRunnable.java:79)
       at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:75)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)
```

Since SQLite is FFI, I guess that code you provided won't run.

The point is: there is a LOT of crashes in Flutter app that just terminates the app. Since we don't program anything in "native", there is no way to know what went wrong or showing some alert to the user or even know what the user was doing at the time. The app just closes.

And most of the stack trace that appears on my Crashlytics is useless, because it is not my code or I don't even know why it is running =P

**Comment by stuartmorgan** [comment] 2021-06-03 21:01
> @stuartmorgan Plugins often crashes the app (a "native" Java/Kotlin crash that will terminate the app).

Native code can crash applications, yes. That's not a problem that can be solved in the abstract, so it's only useful to discuss in the context of specific cases where we can look at the details and whether Flutter is involved.

> For instance:
> 
> ```
> Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void io.flutter.plugin.common.MethodChannel.invokeMethod(java.lang.String, java.lang.Object, io.flutter.plugin.common.MethodChannel$Result)' on a null object reference
>        at io.flutter.plugins.firebase.auth.FlutterFirebaseAuthPlugin.lambda$null$1$FlutterFirebaseAuthPlugin(FlutterFirebaseAuthPlugin.java:546)
>        at io.flutter.plugins.firebase.auth.-$$Lambda$FlutterFirebaseAuthPlugin$SQAGnfsVv7byAY7rk65tey1yNTg.onIdTokenChanged(:4)
> ```

What is the the full stack for this? It seems very likely that this is an async callback that would not have Flutter in the stack anywhere, in which case there is nowhere for Flutter to put an exception handler.

> Here's another example with Google Ads plugin:
> 
> ```
> Fatal Exception: java.lang.IllegalArgumentException: Could not find a string for errorCode: 0
>        at io.flutter.plugins.webviewflutter.FlutterWebViewClient.errorCodeToString(FlutterWebViewClient.java:77)
>        at io.flutter.plugins.webviewflutter.FlutterWebViewClient.onWebResourceError(FlutterWebViewClient.java:142)
>        at io.flutter.plugins.webviewflutter.FlutterWebViewClient.access$300(FlutterWebViewClient.java:29)
>        at io.flutter.plugins.webviewflutter.FlutterWebViewClient$1.onReceivedError(FlutterWebViewClient.java:195)
>        at h9.handleMessage(chromium-TrichromeWebViewGoogle.aab-stable-447207730:124)
>        at android.os.Handler.dispatchMessage(Handler.java:107)
>        at android.os.Looper.loop(Looper.java:237)
>        at android.app.ActivityThread.main(ActivityThread.java:7814)
>        at java.lang.reflect.Method.invoke(Method.java)
>        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
>        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)
> ```

This is an async callback to the webview; no general Flutter-level solution is possible. That can definitely be fixed in the plugin though; please file an issue for that, and CC me.

> Here is one that triggers often because I'm too lazy to implement a disk free checking before trying to create a database:
> 
> ```
> Fatal Exception: android.database.sqlite.SQLiteFullException: disk I/O error (code 7178): , while compiling: PRAGMA journal_mode
> #################################################################
> Error Code : 7178 (SQLITE_IOERR_SHMSIZE_FULL)
> Caused By : No available space in disk.(ENOSPC)
> 	(disk I/O error (code 7178): , while compiling: PRAGMA journal_mode)
> #################################################################
>        at android.database.sqlite.SQLiteConnection.nativePrepareStatement(SQLiteConnection.java)
>        at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1062)
>        at android.database.sqlite.SQLiteConnection.executeForString(SQLiteConnection.java:766)
>        at android.database.sqlite.SQLiteConnection.setJournalMode(SQLiteConnection.java:443)
>        at android.database.sqlite.SQLiteConnection.setWalModeFromConfiguration(SQLiteConnection.java:414)
>        at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:315)
>        at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:210)
>        at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:512)
>        at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:206)
>        at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:178)
>        at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:925)
>        at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:895)
>        at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:708)
>        at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:646)
>        at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:283)
>        at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:223)
>        at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163)
>        at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.getWritableSupportDatabase(FrameworkSQLiteOpenHelper.java:92)
>        at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper.getWritableDatabase(FrameworkSQLiteOpenHelper.java:53)
>        at androidx.room.RoomDatabase.beginTransaction(RoomDatabase.java:328)
>        at androidx.work.impl.utils.ForceStopRunnable.cleanUp(ForceStopRunnable.java:135)
>        at androidx.work.impl.utils.ForceStopRunnable.run(ForceStopRunnable.java:79)
>        at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:75)
>        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
>        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
>        at java.lang.Thread.run(Thread.java:818)
> ```

Flutter is not anywhere on this stack, so again there is nowhere for Flutter to put a handler.

> The point is: there is a LOT of crashes in Flutter app that just terminates the app.

That's going to depend entirely on what code is running in that Flutter app.

> Since we don't program anything in "native"

Someone is programming the native code that is crashing. In the first case, it's the Firebase auth plugin developers. In the second, it's the developers of webview_flutter (i.e., the Flutter team). In the third, it's whoever wrote the code that you are calling via FFI.

> there is no way to know what went wrong or showing some alert to the user or even know what the user was doing at the time.

The middle statement (that there's no way of showing an alert) is true, but the others are not necessarily. You've already indicated that you know the cause for your third example. In the second, the user was trying to load a page in the webview that failed with an error condition that the plugin doesn't have a mapping for, and what went wrong is that is that the plugin currently doesn't correctly handle that situation.

> The app just closes.

This is why crashes are generally treated as high-priority issues in essentially all client software development.

> And most of the stack trace that appears on my Crashlytics is useless, because it is not my code or I don't even know why it is running =P

They are not useless; they provide you information to provide to the authors of the code you are using. Just as if you had Dart exceptions from a package you were using, you would presumably file issues with the authors of the code.

---

Every case you've provided above is actionable by the authors of the relevant code; none are anything that Flutter itself can solve in a generic way. Do you have examples of cases that have Flutter in the stack?

**Comment by stuartmorgan** [comment] 2022-02-24 16:43
> Every case you've provided above is actionable by the authors of the relevant code; none are anything that Flutter itself can solve in a generic way. Do you have examples of cases that have Flutter in the stack?

Absent a response to this question, closing as unactionable.

**Closed by stuartmorgan** 2022-02-24 16:43 UTC
Labels: severe: new feature, engine, plugin, proposal, passed first triage, P5
