### ISSUE TITLE
Regression in  99th_percentile_frame_build_time_millis new_gallery__crane_perf

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#70390] opened 2020-11-12 16:56 UTC
See https://flutter-flutter-perf.skia.org/e/?begin=1604950316&end=1604963043&keys=X79977886e5d56b92be2a53faf431ee5d&num_commits=50&request_type=1&xbaroffset=22452

Looks like a gallery roll: https://github.com/flutter/flutter/pull/70130. @willlarche Can you help us assign, please?

**Comment by clocksmith** [comment] 2020-11-12 17:28
This is a duplicate of https://github.com/flutter/flutter/issues/70300

**Closed by clocksmith** 2020-11-12 17:28 UTC
Labels: P0, perf: speed, severe: performance, severe: regression, team: benchmark
