### ISSUE TITLE
Expose dart:web_gl to flutter web

### ISSUE THREAD

**Issue by lesnitsky** [flutter/flutter#78861] opened 2021-03-23 12:36 UTC
Currently, there is no way to use WebGL enums in flutter web apps and get webgl methods autocomplete

Example use-case:

```dart

import 'dart:html' show CanvasElement;
import 'dart:ui' as ui;
import 'dart:web_gl' show RenderingContext; // <- currently "Target of URI doesn't exist: 'dart:web_gl'."
import 'package:flutter/widgets.dart';

void main() {
  runApp(App());
}

class App extends StatefulWidget {
  @override
  _AppState createState() => _AppState();
}

class _AppState extends State<App> {
  @override
  void initState() {
    ui.platformViewRegistry.registerViewFactory('canvas', (viewId) {
      final c = CanvasElement()
        ..width = 1024
        ..height = 768;

      final gl = c.getContext3d();
     
      final shader = gl.createShader(RenderingContext.VERTEX_SHADER); // <- RenderingContext is unavailable
      // more gl code here

      return c;
    });

    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Container(
      child: HtmlElementView(viewType: 'canvas'),
    );
  }
}
```

This will allow [FlutterGL/flutter_web_gl](https://github.com/FlutterGL/flutter_web_gl) to enable web

**Comment by sigmundch** [comment] 2021-11-19 23:47
I believe the issue is in how the flutter-engine SDK is setup on the flutter side, rather than an issue on the dart sdk. /cc @yjbanov

**Comment by TimNjeru** [comment] 2023-12-15 08:47
Hi @lesnitsky did you find a way to import 'dart:web_gl'?

**Comment by lesnitsky** [comment] 2023-12-15 14:44
https://github.com/lesnitsky/dash_3d/tree/master

**Comment by sigmundch** [comment] 2023-12-15 16:35
A couple updates:
* I believe this issue is a duplicate of https://github.com/flutter/flutter/issues/49849. That issue was resolved after a change was made to expose all `dart:` libraries that expose DOM APIs, including `dart:web_gl` (https://github.com/dart-lang/sdk/pull/53242). I haven't tried, but I believe the current version of flutter allows you to import `dart:web_gl`.
 
* A separate effort has been pushing for a new package, [`package:web`](https://pub.dev/packages/web), that exposes all the browser bindings directly. It is planned to be a long term replacement for most libraries in the SDK that expose DOM APIs like `dart:html`, `dart:web_gl`, `dart:svg`, etc. This package is already supported in flutter web as well.

My recommendation between these two options is to use package:web. That's because dart:web_gl won't be supported in dart2wasm (one of the possible ways to build flutter web apps), and eventually it will be deprecated in favor of package:web.

**Closed** 2024-08-08 08:29 UTC
Labels: c: new feature, engine, platform-web, c: proposal, P3, team-web, triaged-web
