### ISSUE TITLE
Cannot launch webpage in safari/iOSusing url_launcher package.

### ISSUE THREAD

**Issue by opxdelwin** [flutter/flutter#104846] opened 2022-05-27 17:35 UTC
## Steps to Reproduce

- Flutter project with Elevated button and url_launcher package installed.
- onPressed function of button to be async.
- String url be set to await response from firebase.
- launch new tab/link using launchUrl method of url_launcher.

I'm making a web app using flutter which has a brochurePage and a button that gets a download link from firebase and redirects to the website. 

As the firebase request takes time, it's an async function with await for result. This button works fine in chrome (both pc and mobile) but doesn't redirect to the page in Safari (tested multiple times on iPad). If I remove async from the onPressed and provide a static URL for redirection, it works like a charm, but I need the response from firebase for analytical purposes, etc. I'm using the [url_launcher](https://pub.dev/packages/url_launcher/example) package from pub.dev and used their example to write the initial code (which didn't work on iOS only). Later tried multiple methods to achieve the same result, but if it fixes for one platform, the other one breaks. Checked in Stackoverflow for relevant questions but no hope.

I'd highly encourage you to check/test button on iMac, iPhones to test the website's functionality.
You can test out the button/website at https://textel-technologies-pvt-af40e.web.app/#/ -> products 
```
input mail '@.in' &
phno - 1111111111 ,
click get brochure
```

**Expected results:** Button to redirect user to new website on iOS

**Actual results:** no change

<details>
<summary>Code sample</summary>

Here's snippet of onPressed function, works well on chrome, but safari-:
![snippet](https://user-images.githubusercontent.com/84124091/170765996-04396524-7be4-46d5-9ebd-8d32ca97ffdd.jpg)
 
Here's validation logic:

![image](https://user-images.githubusercontent.com/84124091/170762196-3f4319f1-ee7a-4259-a3c0-f129df18df5b.png)

If async removed and static URL, say https://flutter.dev provided, works like charm; but that's not something I want.

```dart
```

</details>

<details>
  <summary>Logs</summary>
No access to any mac device, so no logs on that. 

```
[  +60 ms] executing: [C:\src\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +79 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] fb57da5f945d02ef4f98dfd9409a72b7cce74268
[        ] executing: [C:\src\flutter/] git tag --points-at fb57da5f945d02ef4f98dfd9409a72b7cce74268
[  +61 ms] Exit code 0 from: git tag --points-at fb57da5f945d02ef4f98dfd9409a72b7cce74268
[        ] 3.0.1
[   +7 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +52 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\src\flutter/] git ls-remote --get-url origin
[  +48 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +116 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref HEAD
[  +54 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +69 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +105 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +90 ms] Skipping pub get: version match.
[  +40 ms] Found plugin firebase_app_check at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_app_check-0.0.6+12\
[   +8 ms] Found plugin firebase_app_check_web at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_app_check_web-0.0.5+12\
[   +2 ms] Found plugin firebase_core at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-1.17.0\
[   +4 ms] Found plugin firebase_core_web at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core_web-1.6.4\
[   +3 ms] Found plugin firebase_storage at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_storage-10.2.16\
[   +4 ms] Found plugin firebase_storage_web at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_storage_web-3.2.15\
[   +5 ms] Found plugin fluttertoast at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\fluttertoast-8.0.9\
[  +19 ms] Found plugin path_provider at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-2.0.10\
[   +4 ms] Found plugin path_provider_android at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_android-2.0.14\
[   +3 ms] Found plugin path_provider_ios at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_ios-2.0.9\
[   +2 ms] Found plugin path_provider_linux at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_linux-2.1.6\
[   +3 ms] Found plugin path_provider_macos at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_macos-2.0.6\
[   +4 ms] Found plugin path_provider_windows at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_windows-2.0.6\
[  +22 ms] Found plugin url_launcher at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher-6.1.2\
[   +4 ms] Found plugin url_launcher_android at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_android-6.0.17\
[   +3 ms] Found plugin url_launcher_ios at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_ios-6.0.17\
[   +2 ms] Found plugin url_launcher_linux at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_linux-3.0.1\
[   +3 ms] Found plugin url_launcher_macos at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_macos-3.0.1\
[   +4 ms] Found plugin url_launcher_web at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_web-2.0.11\
[   +3 ms] Found plugin url_launcher_windows at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_windows-3.0.1\
[  +64 ms] Found plugin firebase_app_check at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_app_check-0.0.6+12\
[   +2 ms] Found plugin firebase_app_check_web at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_app_check_web-0.0.5+12\
[   +1 ms] Found plugin firebase_core at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-1.17.0\
[   +2 ms] Found plugin firebase_core_web at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core_web-1.6.4\
[   +1 ms] Found plugin firebase_storage at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_storage-10.2.16\
[   +2 ms] Found plugin firebase_storage_web at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_storage_web-3.2.15\
[   +3 ms] Found plugin fluttertoast at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\fluttertoast-8.0.9\
[  +10 ms] Found plugin path_provider at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-2.0.10\
[   +2 ms] Found plugin path_provider_android at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_android-2.0.14\
[   +1 ms] Found plugin path_provider_ios at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_ios-2.0.9\
[   +2 ms] Found plugin path_provider_linux at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_linux-2.1.6\
[   +1 ms] Found plugin path_provider_macos at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_macos-2.0.6\
[   +2 ms] Found plugin path_provider_windows at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_windows-2.0.6\
[  +10 ms] Found plugin url_launcher at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher-6.1.2\
[   +2 ms] Found plugin url_launcher_android at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_android-6.0.17\
[   +1 ms] Found plugin url_launcher_ios at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_ios-6.0.17\
[   +1 ms] Found plugin url_launcher_linux at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_linux-3.0.1\
[   +1 ms] Found plugin url_launcher_macos at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_macos-3.0.1\
[   +2 ms] Found plugin url_launcher_web at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_web-2.0.11\
[   +1 ms] Found plugin url_launcher_windows at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_windows-3.0.1\
[  +57 ms] Generating C:\Users\delu8\StudioProjects\ttpl_website\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[ +144 ms] Launching lib\main.dart on Chrome in release mode...
[ +119 ms] Found plugin firebase_app_check at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_app_check-0.0.6+12\
[   +2 ms] Found plugin firebase_app_check_web at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_app_check_web-0.0.5+12\
[   +1 ms] Found plugin firebase_core at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-1.17.0\
[   +1 ms] Found plugin firebase_core_web at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core_web-1.6.4\
[   +1 ms] Found plugin firebase_storage at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_storage-10.2.16\
[   +2 ms] Found plugin firebase_storage_web at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_storage_web-3.2.15\
[   +3 ms] Found plugin fluttertoast at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\fluttertoast-8.0.9\
[   +8 ms] Found plugin path_provider at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-2.0.10\
[   +2 ms] Found plugin path_provider_android at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_android-2.0.14\
[   +1 ms] Found plugin path_provider_ios at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_ios-2.0.9\
[   +1 ms] Found plugin path_provider_linux at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_linux-2.1.6\
[   +1 ms] Found plugin path_provider_macos at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_macos-2.0.6\
[   +1 ms] Found plugin path_provider_windows at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_windows-2.0.6\
[   +7 ms] Found plugin url_launcher at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher-6.1.2\
[   +1 ms] Found plugin url_launcher_android at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_android-6.0.17\
[   +2 ms] Found plugin url_launcher_ios at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_ios-6.0.17\
[   +1 ms] Found plugin url_launcher_linux at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_linux-3.0.1\
[   +1 ms] Found plugin url_launcher_macos at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_macos-3.0.1\
[   +1 ms] Found plugin url_launcher_web at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_web-2.0.11\
[        ] Found plugin url_launcher_windows at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_windows-3.0.1\
[  +15 ms] Found plugin firebase_app_check at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_app_check-0.0.6+12\
[   +2 ms] Found plugin firebase_app_check_web at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_app_check_web-0.0.5+12\
[   +1 ms] Found plugin firebase_core at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-1.17.0\
[   +1 ms] Found plugin firebase_core_web at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core_web-1.6.4\
[        ] Found plugin firebase_storage at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_storage-10.2.16\
[   +1 ms] Found plugin firebase_storage_web at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_storage_web-3.2.15\
[   +1 ms] Found plugin fluttertoast at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\fluttertoast-8.0.9\
[   +8 ms] Found plugin path_provider at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-2.0.10\
[   +1 ms] Found plugin path_provider_android at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_android-2.0.14\
[   +1 ms] Found plugin path_provider_ios at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_ios-2.0.9\
[   +1 ms] Found plugin path_provider_linux at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_linux-2.1.6\
[        ] Found plugin path_provider_macos at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_macos-2.0.6\
[   +1 ms] Found plugin path_provider_windows at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_windows-2.0.6\
[   +6 ms] Found plugin url_launcher at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher-6.1.2\
[   +1 ms] Found plugin url_launcher_android at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_android-6.0.17\
[   +1 ms] Found plugin url_launcher_ios at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_ios-6.0.17\
[        ] Found plugin url_launcher_linux at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_linux-3.0.1\
[        ] Found plugin url_launcher_macos at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_macos-3.0.1\
[   +1 ms] Found plugin url_launcher_web at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_web-2.0.11\
[        ] Found plugin url_launcher_windows at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_windows-3.0.1\
[   +6 ms] Compiling lib\main.dart for the Web...
[   +8 ms] Initializing file store
[  +27 ms] web_entrypoint: Starting due to {InvalidatedReasonKind.inputChanged: The following inputs have updated contents:
C:\src\flutter\packages\flutter_tools\lib\src\build_system\targets\web.dart}
[   +3 ms] Skipping target: gen_localizations
[   +2 ms] web_static_assets: Starting due to {}
[  +45 ms] web_entrypoint: Complete
[   +2 ms] web_static_assets: Complete
[   +1 ms] dart2js: Starting due to {}
[+30799 ms] dart2js: Complete
[ +445 ms] web_release_bundle: Starting due to {}
[ +114 ms] Manifest contained wildcard assets. Inserting missing file into build graph to force rerun. for more information see #56466.
[  +63 ms] web_release_bundle: Complete
[ +656 ms] web_service_worker: Starting due to {}
[ +244 ms] web_service_worker: Complete
[ +191 ms] Persisting file store
[   +9 ms] Done persisting file store
[  +20 ms] Compiling lib\main.dart for the Web... (completed in 32.6s)
[ +342 ms] [CHROME]:
[   +3 ms] [CHROME]: DevTools listening on ws://127.0.0.1:53811/devtools/browser/40681327-90b4-453f-9300-635b438affc2
[ +129 ms]   To hot restart changes while running, press "r" or "R".
[   +1 ms] For a more detailed help message, press "h". To quit, press "q".
[+23574 ms] Application finished.
[   +5 ms] "flutter run" took 57,628ms.
[ +260 ms] ensureAnalyticsSent: 257ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 0

```
</details>

<details>
<summary>Flutter Analyze</summary>

```
info - Unused import: 'package:firebase_app_check/firebase_app_check.dart' - lib\main.dart:1:8 - unused_import
   info - Unused import: 'package:ttpl_website/screens/services/ResponsiveServices.dart' - lib\main.dart:6:8 - unused_import
   info - Name source files using `lowercase_with_underscores` - lib\screens\brochure\ResponsiveBrochure.dart:1:1 - file_names
   info - Avoid using web-only libraries outside Flutter web plugin packages - lib\screens\brochure\brochure.dart:8:1 - avoid_web_libraries_in_flutter
   info - Unused import: 'dart:html' - lib\screens\brochure\brochure.dart:8:8 - unused_import
   info - Unused import: 'package:url_launcher/url_launcher_string.dart' - lib\screens\brochure\brochure.dart:10:8 - unused_import
   info - Avoid `print` calls in production code - lib\screens\brochure\brochure.dart:205:37 - avoid_print
   info - Avoid `print` calls in production code - lib\screens\brochure\brochure.dart:206:33 - avoid_print
   info - Avoid `print` calls in production code - lib\screens\brochure\brochure.dart:406:27 - avoid_print
   info - Unused import: 'package:flutter/services.dart' - lib\screens\footer.dart:2:8 - unused_import
   info - Name source files using `lowercase_with_underscores` - lib\screens\landing\LandingResponsive.dart:1:1 - file_names
   info - Avoid using web-only libraries outside Flutter web plugin packages - lib\screens\products\product_page.dart:1:1 - avoid_web_libraries_in_flutter
   info - The value of the field '_screenController' isn't used - lib\screens\products\product_page.dart:240:25 - unused_field
   info - The value of the field '_compatibleProductController' isn't used - lib\screens\products\product_page.dart:241:25 - unused_field
   info - Name source files using `lowercase_with_underscores` - lib\screens\products\responsiveProduct.dart:1:1 - file_names
   info - Name source files using `lowercase_with_underscores` - lib\screens\services\ResponsiveServices.dart:1:1 - file_names
   info - Unused import: 'package:drop_cap_text/drop_cap_text.dart' - lib\screens\services\services.dart:6:8 - unused_import
```

</details>
<details>
<summary>Flutter doctor</summary>
```
[√] Flutter (Channel stable, 3.0.1, on Microsoft Windows [Version 10.0.19043.1706], locale en-IN)
    • Flutter version 3.0.1 at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (8 days ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at C:\Users\delu8\AppData\Local\Android\Sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19043.1706]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 101.0.4951.67
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 101.0.1210.39

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```
</details>

**Comment by stuartmorgan** [comment] 2022-05-27 21:27
Duplicate of https://github.com/flutter/flutter/issues/78524

**Closed by stuartmorgan** 2022-05-27 21:27 UTC
