### ISSUE TITLE
app resizes when keyboard is shown in different app

### ISSUE THREAD

**Issue by lesnitsky** [flutter/flutter#27769] opened 2019-02-11 14:23 UTC
Steps to reproduce:

* open flutter app
* open some other app with text input, make keyboard pop
* go back to flutter app, notice layout changes

I understand that this could be easily fixed with `resizeToAvoidBottomPadding: false`, but all in all this is really weird behavior. What's the motivation behind this? Are there some real use cases where this behavior is expected?

This issue seem to be iOS specific, I wasn't able to reproduce it neither on Pixel 2XL with gestures app switcher, nor on HTC 10 with "old" app switcher

**Comment by zoechi** [comment] 2019-02-11 15:33
Please add the output of `flutter doctor -v`.

**Comment by lesnitsky** [comment] 2019-02-11 15:36
```
[✓] Flutter (Channel beta, v1.1.8, on Mac OS X 10.14 18A391, locale en-BY)
    • Flutter version 1.1.8 at /Users/r1zzu/flutter
    • Framework revision 985ccb6d14 (5 weeks ago), 2019-01-08 13:45:55 -0800
    • Engine revision 7112b72cc2
    • Dart version 2.1.1 (build 2.1.1-dev.0.1 ec86471ccc)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/r1zzu/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/r1zzu/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/r1zzu/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[!] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[!] IntelliJ IDEA Community Edition (version 2017.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.31.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.22.3

[✓] Connected device (1 available)
    • iPhone 6 • D5B9AE18-0DA0-4F13-8CAA-10CB70DAD228 • ios • iOS 12.1 (simulator)
```

**Comment by zoechi** [comment] 2019-02-12 08:32
Duplicate of #23926

**Closed by zoechi** 2019-02-12 08:32 UTC
Labels: engine, framework, ⌺‬ platform-ios
