### ISSUE TITLE
Map functions not working in Flutter release and profile on web, but are in debug

### ISSUE THREAD

**Issue by Dall127** [flutter/flutter#85488] opened 2021-06-28 22:04 UTC
## Steps to Reproduce

1. Run `flutter build web --profile`.
2. Run below function 

```
  static bool isAuthorized(String output) {
    Map<String, dynamic> decoded = tryDecode(output);
    if (decoded.isEmpty) {
      return true;
    } else if (decoded.containsValue("Invalid token.")) {
      return false;
    } else if (decoded.containsKey("detail")) {
      return false;
    } else {
      return true;
    }
  }
```

(Web profile generated code that throws error) 
```
    API_isAuthorized: function(output) {
      var decoded = E.API_tryDecode(output),
        t1 = J.getInterceptor$asx(decoded);
      if (t1.get$isEmpty(decoded))
        return true;
      if (t1.containsValue$1(decoded, "Invalid token."))
        return false;
      else if (t1.containsKey$1(decoded, "detail"))
        return false;
      else
        return true;
    },
```
**Expected results:** 
No error 

**Actual results:** 
`Uncaught TypeError: t1.containsValue$1 is not a function`

<details>
  <summary>Logs</summary>

```
```

```
Analyzing true_lake...                                                  
No issues found! (ran in 5.6s)
```

```
[✓] Flutter (Channel stable, 2.2.2, on macOS 11.4 20F71 darwin-x64, locale en-US)
    • Flutter version 2.2.2 at /Users/REDACTED/LocalFrameworks/flutter
    • Framework revision d79295af24 (2 weeks ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/REDACTED/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.23.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.4 20F71 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 91.0.4472.114

• No issues found!
```

</details>
It seems to be something with the Map object not containing the functions during release builds, other than that I'm not sure as to what is wrong

**Comment by TahaTesser** [comment] 2021-06-29 13:46
Hi @Dall127 
I cannot reproduce it in `release`, `profile` & `debug` modes, 

The string I've provided doesn't `detail` hence the value false is working as expected, no error are throwns

### Preview

<img width="1041" alt="Screen Shot 2021-06-29 at 16 41 27" src="https://user-images.githubusercontent.com/48603081/123808366-59cd1180-d8f9-11eb-9cfd-d7758bf385d8.png">



<details> 
<summary>minimal code sample</summary> 

```dart
import 'dart:convert';

import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  static Map<String, dynamic> tryDecode(String text) {
    return jsonDecode(text);
  }

  static bool isAuthorized(String output) {
    Map<String, dynamic> decoded = tryDecode(output);
    if (decoded.isEmpty) {
      return true;
    } else if (decoded.containsValue("Invalid token.")) {
      return false;
    } else if (decoded.containsKey("detail")) {
      return false;
    } else {
      return true;
    }
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      home: Scaffold(
        appBar: AppBar(
          title: Text('Material App Bar'),
        ),
        body: Center(
          child:ElevatedButton(onPressed: (){
            print(isAuthorized('{"detail": "test", "id": 1}'));
          }, child: Text('Decode')),
        ),
      ),
    );
  }
}

``` 

</details>


<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.2.2, on macOS 11.4 20F71 darwin-x64, locale en-US)
    • Flutter version 2.2.2 at /Users/tahatesser/Code/flutter_stable
    • Framework revision d79295af24 (3 weeks ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.23.0

[✓] Connected device (4 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E            • ios            •
      iOS 14.6
    • iPhone 12 Pro (mobile) • 4819C924-80DB-4DE5-9093-71A234590ABB • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-x64     •
      macOS 11.4 20F71 darwin-x64
    • Chrome (web)           • chrome                               • web-javascript •
      Google Chrome 91.0.4472.114

• No issues found!
```

</details>

**Comment by Dall127** [comment] 2021-06-29 15:40
Here is another part that I noticed in trying to recreate it this morning in the web console 

 ```Could not load content for org-dartlang-sdk:///lib/_internal/js_runtime/lib/js_helper.dart (HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME)```


<details>
<summary>Minimal Code Sample</summary>
```
class API {
  static bool isAuthorized(String output) {
    Map<String, dynamic> decoded = tryDecode(output);
    if (decoded.isEmpty) {
      return true;
    } else if (decoded.containsValue("Invalid token.")) {
      return false;
    } else if (decoded.containsKey("detail")) {
      return false;
    } else {
      return true;
    }
  }
 // Example function using isAuthorized
  static Future<Preferences?> getPreferences(User user) async {
    final Uri url = Uri.parse(baseUri.toString() + "/api/preferences/");
    if (user.token != null) {
      baseHeader.addAll({"AUTHORIZATION": "Token " + user.token!});

      if (await workingConneciton()) {
        var response = await http.get(url, headers: baseHeader);
        if (isAuthorized(response.body)) {
          Map<String, dynamic> decoded = tryDecode(response.body);
          if (decoded.isNotEmpty) {
            return Preferences.fromMap(decoded);
          }
        } else {
          logout();
        }
      }
    }

    return null;
  }


</details>


## Expected Results 
 No error is thrown and the function and returns a boolean

##Actual results
 Error is thrown inside web console only on release and profile builds

**Comment by TahaTesser** [comment] 2021-06-30 10:08
Hi @Dall127 
Since you is not complete (runnable) so I have created complete sample from you snippet, still no issue in any mode

<details> 
<summary>minimal code sample</summary> 

```dart
import 'dart:convert';
import 'package:http/http.dart' as http;
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: Text('Material App Bar'),
        ),
        body: Center(
          child: Container(
            child: Text('Hello World'),
          ),
        ),
        floatingActionButton: FloatingActionButton(
          child: Icon(Icons.add),
          onPressed: () async => print(
            await API.getTodo(),
          ),
        ));
  }
}

class API {
  static bool isAuthorized(String output) {
    Map<String, dynamic> decoded = tryDecode(output);
    if (decoded.isEmpty) {
      return true;
    } else if (decoded.containsValue("Invalid token.")) {
      return false;
    } else if (decoded.containsKey("completed")) {
      return true;
    } else {
      return true;
    }
  }

  static Map<String, dynamic> tryDecode(var toDecode) {
    try {
      return jsonDecode(toDecode);
    } catch (e) {
      return {};
    }
  }

  // Example function using isAuthorized
  static Future<String?> getTodo() async {
    final Uri url = Uri.parse('https://jsonplaceholder.typicode.com/todos/1');
    var response = await http.get(url);
    if (isAuthorized(response.body)) {
      Map<String, dynamic> decoded = tryDecode(response.body);
      if (decoded.isNotEmpty) {
        return Future.value(decoded.toString());
      }
    }

    return null;
  }
}

``` 

</details>

### Preview
![image](https://user-images.githubusercontent.com/48603081/123942755-1f6c7e80-d9a4-11eb-9d81-57783f55c666.png)


<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.2.2, on Microsoft Windows [Version 10.0.19043.1081], locale en-US)
    • Flutter version 2.2.2 at C:\Users\Taha\Code\flutter_stable
    • Framework revision d79295af24 (3 weeks ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_SDK_ROOT = C:\Users\Taha\Code\SDK
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java.exe
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.10.2)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.10.31410.357
    • Windows 10 SDK version 10.0.19041.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[✓] IntelliJ IDEA Community Edition (version 2021.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.1.1
    • Flutter plugin version 57.0.5
    • Dart plugin version 211.7233

[✓] VS Code (version 1.57.1)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.23.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19043.1081]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 91.0.4472.114
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 91.0.864.59

! Doctor found issues in 1 category.
```

</details>


Please prvodie complete sample that reprpduces the isuee
Thank you

**Comment by Dall127** [comment] 2021-07-06 17:12
I was able to reproduce the issue with the minimal (and runnable) code sample below. 


##Steps to reproduce: 
1) Modify function to recreate output of a server (provided code for expected login output if helpful) 
2) Run code in profile or release mode and observe 

**Note:**
The expected response of login for recreation purposes: ```{expiry: 2021-07-07T02:59:51.066026Z, token: b765c31440bd4ac1d6bafa49ab21ee3e8bf53c6081a4af0537dfe497bd5dba50}
 ```


**Expected Results:**
No Error, successfully print out output of api endpoint 



**Actual results:** 
![image](https://user-images.githubusercontent.com/31700756/124640353-8679af80-de4a-11eb-923d-768733c595a6.png)




<details>
<summary>Minimal Code Sample</summary>

```
import 'dart:convert';
import 'package:http/http.dart' as http;
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: Text('Material App Bar'),
        ),
        body: Center(
          child: Container(
            child: Text('Hello World'),
          ),
        ),
        floatingActionButton: FloatingActionButton(
          child: Icon(Icons.add),
          onPressed: () async => print(
            await API.login("username", "password"),
          ),
        ));
  }
}

class API {
  static Map<String, String> baseHeader = {"content-type": "application/json"};
  static Uri baseUri = Uri.parse("http://localhost");

  static bool isAuthorized(String output) {
    Map<String, dynamic> decoded = tryDecode(output);
    if (decoded.isEmpty) {
      return true;
    } else if (decoded.containsValue("Invalid token.")) {
      return false;
    } else if (decoded.containsKey("completed")) {
      return true;
    } else {
      return true;
    }
  }

  static Map<String, dynamic> tryDecode(var toDecode) {
    try {
      return jsonDecode(toDecode);
    } catch (e) {
      return {};
    }
  }

  static Future<dynamic> login(String username, String password) async {
    final Uri url = Uri.parse(baseUri.toString() + "/api/login/");
    var data = jsonEncode({"username": username, "password": password});

    var response = await http.post(url, headers: baseHeader, body: data);
    Map<String, dynamic> json = jsonDecode(response.body);
    if (json.containsKey("token")) {
      return getBooks(json["token"]);
    } else {
      return null;
    }
  }

  static Future<dynamic> getBooks(String token) async {
    final Uri url = Uri.parse(baseUri.toString() + "/api/books/");
    baseHeader.addAll({"AUTHORIZATION": "Token " + token});
    var response = await http.get(url, headers: baseHeader);
    if (isAuthorized(response.body)) {
      return Future.value(response.body);
    } else {
      return null;
    }
  }
}

```

</details>

**Comment by Dall127** [comment] 2021-07-06 17:34
**Upon Further inspection:**

when running in different modes, the runtime return type of jsonDecode varies when given different responses  varies. The isAuthorized function was only designed to handle Maps, not Lists and Maps, and thus was the main cause on my part.  

However, I think that the consistency between debug and profile modes in terms of how they handle runtime types is a bug, or at least should be a heavily documented phenomena and something to be on the radar when developing for flutter web.

In debug, the type is: 
```IdentityMap<String, dynamic>  ```
yet in release and profile, it is 
```JSArray<dynamic> ```

thus causing map functions to not be accessible in the later two compilation modes.

**Comment by TahaTesser** [comment] 2021-07-07 07:20
Hi @Dall127 
Thanks for the details, for issues related to jsonDecodate, please file an issue on Dart's repository as `dart:convert` is not part of Flutter.

Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-07-07 07:20 UTC
Labels: in triage
