### ISSUE TITLE
CupertinoSliverRefreshControl doesn't work when it's in a GrowthDirection.reverse sliver

### ISSUE THREAD

**Issue by tarobins** [flutter/flutter#38492] opened 2019-08-13 22:07 UTC
would be nice if it did so it can be used as a sliver above the centered sliver in a CustomScrollView.

**Comment by Piinks** [comment] 2019-10-01 20:51
Hi @tarobins,
Could provide more context for your issue? It seems the title is cut-off.
Could you also provide the output of `flutter doctor -v`?
Currently on the master branch, `CupertinoSliverRefreshControl` works in a `CustomScrollView` as intended, and even interchangeably with Material elements. I have provided a minimal sample below.
 
```dart
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: CustomScrollView(
          slivers: <Widget>[
            CupertinoSliverNavigationBar(largeTitle: Text('Demo')),
            CupertinoSliverRefreshControl(),
            SliverToBoxAdapter(child: Container(height: 100, color: Colors.blue)),
          ],
        )
      )
    );
  }
}
```

Is there a different use case you are referring to?

**Comment by tarobins** [comment] 2019-10-01 21:33
Think it was supposed to say something like:  CupertinoSliverRefreshControl doesn't work when its in the GrowthDirection.reverse sliver.  

There's a little more context here: https://github.com/flutter/flutter/issues/12319#issuecomment-520989794

**Comment by Piinks** [comment] 2019-10-04 16:40
Ah! Thanks for clarifying!

**Comment by pedromassangocode** [comment] 2020-09-10 09:46
Is this still a valid issue? Would be be great to have a reproducible sample code for this issue.

**Comment by pedromassangocode** [comment] 2020-11-24 10:06
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2020-11-24 10:06 UTC
Labels: f: cupertino, f: scrolling, framework, passed first triage, waiting for customer response
