### ISSUE TITLE
[quick_actions] Android support open app without restarting entire app

### ISSUE THREAD

**Issue by TabooSun** [flutter/flutter#83251] opened 2021-05-24 11:22 UTC
## Use case

Currently, iOS allows the app state to be retained when the quick_actions is triggered. However, Android does not work the same, the entire app will be restarted when the quick_actions is triggered.

**Comment by nt4f04uNd** [comment] 2021-09-12 14:02
This seems to be a duplicate of https://github.com/flutter/flutter/issues/87259, which was fixed

**Comment by nt4f04uNd** [comment] 2021-09-12 14:10
Actually no, the isolate is still restarted each time the app is opened with the action

**Comment by workerbee22** [comment] 2022-04-21 09:13
Confirmed this is still an issue. You can check this yourself:

1. Run your app using Quick Actions plugin in Debug (and debug logging to IDE)
2. On device, while the app is running, background the app and go back too the Android launcher and long press the app again and start it with a Quick Action

If you do this you will see the app restart, which does not occur with iOS.

**Comment by dw2kim** [comment] 2022-07-06 19:33
+1

This is still an issue in Android.

**Comment by stuartmorgan** [comment] 2022-08-31 14:47
This wasn't auto-closed when the PR landed for some reason; closing as fixed.

**Closed by stuartmorgan** 2022-08-31 14:47 UTC
Labels: platform-android, plugin, p: first party, p: quick_actions, proposal, passed first triage, P5
