### ISSUE TITLE
Flutter Web Back Button bug

### ISSUE THREAD

**Issue by MakufonSkifto** [flutter/flutter#87199] opened 2021-07-28 15:14 UTC
## Steps to Reproduce

1. Clone this project: https://github.com/MakufonSkifto/MakufonSkifto-s-Work/tree/master/lib
2. Do `flutter run web` on Edge

**Expected results:**
I want to see a back button with the back icon on my appbar when I navigate using pushNamed

**Actual results:** 
I saw a bookmark icon instead of the back one

This is an image representation of the problem:
![image](https://user-images.githubusercontent.com/63517174/127347104-320f7217-e76e-4815-af1f-b51087c0089d.png)

<details>
  <summary>Logs</summary>

```
[  +64 ms] executing: [C:\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +388 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] f4abaa0735eba4dfd8f33f73363911d63931fe03
[        ] executing: [C:\flutter/] git tag --points-at f4abaa0735eba4dfd8f33f73363911d63931fe03
[  +50 ms] Exit code 0 from: git tag --points-at f4abaa0735eba4dfd8f33f73363911d63931fe03
[        ] 2.2.3
[   +4 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +41 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\flutter/] git ls-remote --get-url origin
[  +37 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +108 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref HEAD
[  +40 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +75 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +46 ms] executing: C:\Users\emirs\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +39 ms] List of devices attached
[   +4 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[  +10 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +65 ms] Multiple devices found:
[  +22 ms] Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19043.1110]
[   +1 ms] Chrome (web)      • chrome  • web-javascript • Google Chrome 85.0.4183.102
[        ] Edge (web)        • edge    • web-javascript • Microsoft Edge 92.0.902.55
[   +1 ms] [1]: Windows (windows)
[        ] [2]: Chrome (chrome)
[        ] [3]: Edge (edge)
[   +2 ms] Please choose one (To quit, press "q/Q")
[        ] : 
[+5007 ms] 3
[  +10 ms] Skipping pub get: version match.
[  +30 ms] Found plugin path_provider at C:\Users\emirs\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\path_provider-2.0.1\
[   +5 ms] Found plugin path_provider_linux at C:\Users\emirs\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\path_provider_linux-2.0.0\
[   +2 ms] Found plugin path_provider_macos at C:\Users\emirs\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\path_provider_macos-2.0.0\
[   +3 ms] Found plugin path_provider_windows at C:\Users\emirs\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\path_provider_windows-2.0.1\
[   +9 ms] Found plugin url_launcher at C:\Users\emirs\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\url_launcher-6.0.3\
[   +1 ms] Found plugin url_launcher_linux at C:\Users\emirs\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\url_launcher_linux-2.0.0\
[   +3 ms] Found plugin url_launcher_macos at C:\Users\emirs\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\url_launcher_macos-2.0.0\
[   +3 ms] Found plugin url_launcher_web at C:\Users\emirs\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\url_launcher_web-2.0.0\
[   +2 ms] Found plugin url_launcher_windows at C:\Users\emirs\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\url_launcher_windows-2.0.0\
[  +78 ms] Found plugin path_provider at C:\Users\emirs\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\path_provider-2.0.1\
[   +1 ms] Found plugin path_provider_linux at C:\Users\emirs\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\path_provider_linux-2.0.0\
[   +1 ms] Found plugin path_provider_macos at C:\Users\emirs\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\path_provider_macos-2.0.0\
[   +2 ms] Found plugin path_provider_windows at C:\Users\emirs\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\path_provider_windows-2.0.1\
[   +7 ms] Found plugin url_launcher at C:\Users\emirs\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\url_launcher-6.0.3\
[   +1 ms] Found plugin url_launcher_linux at C:\Users\emirs\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\url_launcher_linux-2.0.0\
[   +1 ms] Found plugin url_launcher_macos at C:\Users\emirs\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\url_launcher_macos-2.0.0\
[   +2 ms] Found plugin url_launcher_web at C:\Users\emirs\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\url_launcher_web-2.0.0\
[   +1 ms] Found plugin url_launcher_windows at C:\Users\emirs\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\url_launcher_windows-2.0.0\
[   +9 ms] Generating C:\Users\emirs\AndroidStudioProjects\emirsurmen_com\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +86 ms] Launching lib\main.dart on Edge in debug mode...
[ +117 ms] Updating assets
[ +245 ms] Waiting for connection from debug service on Edge...
[  +13 ms] Found plugin path_provider at C:\Users\emirs\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\path_provider-2.0.1\
[   +1 ms] Found plugin path_provider_linux at C:\Users\emirs\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\path_provider_linux-2.0.0\
[   +1 ms] Found plugin path_provider_macos at C:\Users\emirs\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\path_provider_macos-2.0.0\
[   +2 ms] Found plugin path_provider_windows at C:\Users\emirs\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\path_provider_windows-2.0.1\
[   +8 ms] Found plugin url_launcher at C:\Users\emirs\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\url_launcher-6.0.3\
[   +1 ms] Found plugin url_launcher_linux at C:\Users\emirs\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\url_launcher_linux-2.0.0\
[   +1 ms] Found plugin url_launcher_macos at C:\Users\emirs\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\url_launcher_macos-2.0.0\
[   +2 ms] Found plugin url_launcher_web at C:\Users\emirs\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\url_launcher_web-2.0.0\
[   +1 ms] Found plugin url_launcher_windows at C:\Users\emirs\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\url_launcher_windows-2.0.0\
[  +15 ms] Found plugin path_provider at C:\Users\emirs\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\path_provider-2.0.1\
[   +1 ms] Found plugin path_provider_linux at C:\Users\emirs\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\path_provider_linux-2.0.0\
[   +1 ms] Found plugin path_provider_macos at C:\Users\emirs\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\path_provider_macos-2.0.0\
[   +1 ms] Found plugin path_provider_windows at C:\Users\emirs\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\path_provider_windows-2.0.1\
[   +4 ms] Found plugin url_launcher at C:\Users\emirs\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\url_launcher-6.0.3\
[   +1 ms] Found plugin url_launcher_linux at C:\Users\emirs\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\url_launcher_linux-2.0.0\
[   +1 ms] Found plugin url_launcher_macos at C:\Users\emirs\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\url_launcher_macos-2.0.0\
[   +2 ms] Found plugin url_launcher_web at C:\Users\emirs\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\url_launcher_web-2.0.0\
[   +1 ms] Found plugin url_launcher_windows at C:\Users\emirs\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\url_launcher_windows-2.0.0\
[ +131 ms] <- reset
[   +8 ms] C:\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev C:\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root C:\flutter\bin\cache\flutter_web_sdk/ --incremental
--target=dartdevc --debugger-module-names --experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true --output-dill C:\Users\emirs\AppData\Local\Temp\flutter_tools.6a02a643\flutter_tool.affc95d9\app.dill --libraries-spec
file:///C:/flutter/bin/cache/flutter_web_sdk/libraries.json --packages C:\Users\emirs\AndroidStudioProjects\emirsurmen_com\.dart_tool\package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts
--track-widget-creation --filesystem-root C:\Users\emirs\AppData\Local\Temp\flutter_tools.6a02a643\flutter_tools.fc2594ee --filesystem-scheme org-dartlang-app --initialize-from-dill
build\c7922d95bf4a2462b75c84a97c312edb.cache.dill.track.dill --platform file:///C:/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk.dill --no-sound-null-safety
[  +12 ms] <- compile org-dartlang-app:/web_entrypoint.dart
[+16673 ms] Waiting for connection from debug service on Edge... (completed in 16,9s)
[        ] Synced 36.9MB.
[        ] <- accept
[        ] Caching compiled dill
[+1218 ms] [CHROME]:[17124:10968:0728/181259.527:ERROR:token_service_table.cc(140)] Failed to decrypt token for service AccountId-00037FFE1F736011
[  +51 ms] [CHROME]:
[   +8 ms] [CHROME]:DevTools listening on ws://127.0.0.1:50712/devtools/browser/a178a580-3911-45da-a6b7-ef215bfce37e
[+1161 ms] DwdsInjector: Received request for entrypoint at http://localhost:50689/main_module.bootstrap.js
[   +5 ms] MetadataProvider: Loading debug metadata...
[  +11 ms] MetadataProvider: Loaded debug metadata (no sound null safety)
[   +7 ms] DwdsInjector: Injected debugging metadata for entrypoint at http://localhost:50689/main_module.bootstrap.js
[+2577 ms] ChromeProxyService: Initializing expression compiler for main_module.bootstrap.js with sound null safety: false
[  +62 ms] DevHandler: Debug service listening on ws://127.0.0.1:53397/1VtubsJKOa8=/ws

[  +20 ms] This app is linked to the debug service: ws://127.0.0.1:53397/1VtubsJKOa8=/ws
[   +9 ms] Debug service listening on ws://127.0.0.1:53397/1VtubsJKOa8=/ws
[   +1 ms] Running with unsound null safety
[        ] For more information see https://dart.dev/null-safety/unsound-null-safety
[   +2 ms]   To hot restart changes while running, press "r" or "R".
[        ] For a more detailed help message, press "h". To quit, press "q".

```

```
Analyzing emirsurmen_com...

   info - Unused import: 'package:emirsurmen_com/main.dart' - test\widget_test.dart:11:8 - unused_import
  error - The function 'MyApp' isn't defined - test\widget_test.dart:16:29 - undefined_function

2 issues found. (ran in 1.4s)
```

```
[√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.19043.1110], locale tr-TR)
    • Flutter version 2.2.3 at C:\flutter
    • Framework revision f4abaa0735 (4 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\emirs\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Java\jdk-14.0.1\bin\java
    • Java version Java(TM) SE Runtime Environment (build 14.0.1+7)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.3)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30503.244
    X The current Visual Studio installation is incomplete. Please reinstall Visual Studio.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] IntelliJ IDEA Ultimate Edition (version 2021.1)
    • IntelliJ at C:\Users\emirs\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\211.7628.21
    • Flutter plugin version 58.0.3
    • Dart plugin version 211.7665

[√] VS Code (version 1.56.0)
    • VS Code at C:\Users\emirs\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.22.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19043.1110]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 85.0.4183.102
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 92.0.902.55

! Doctor found issues in 3 categories.

```

</details>

I also asked this on [StackOverflow](https://stackoverflow.com/questions/68337582/flutter-web-back-button)

**Comment by TahaTesser** [comment] 2021-07-29 08:36
Hi @MakufonSkifto 
Using same Fluter channel and Edge version `Version 92.0.902.55 (Official build) (64-bit)`

Running your code in release mode on Edge  `flutter run -d edge --release`

https://user-images.githubusercontent.com/48603081/127458383-16f37c3f-35a3-4a94-b7dd-78bcdd978fe0.mp4



<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.19043.1110], locale en-US)
    • Flutter version 2.2.3 at C:\Users\Taha\Code\flutter_stable
    • Framework revision f4abaa0735 (4 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\android-sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_SDK_ROOT = C:\Users\Taha\Code\android-sdk
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java.exe
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.10.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.10.31515.178
    • Windows 10 SDK version 10.0.19041.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[✓] VS Code (version 1.58.2)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.24.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19043.1110]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 92.0.4515.107
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 92.0.902.55

! Doctor found issues in 1 category.
```

</details>


> I saw a bookmark icon instead of the back one

Is the issue reproducible consistently?

**Comment by MakufonSkifto** [comment] 2021-07-29 08:40
@TahaTesser When I run it on Edge in release mode, just like you did, there is no problem and works as intended. The problem starts when I put it on GitHub pages and access it through the domain, https://emirsurmen.com

**Comment by TahaTesser** [comment] 2021-07-30 08:56
Hi @TahaTesser 
I can see the bookmark icon in your link but when I build the app myself in release mode locally or on GitHub page or Netlify, none of them show a bookmark icon

![image](https://user-images.githubusercontent.com/48603081/127628464-5681ea27-0548-405a-8c8f-bee80f4f322f.png)

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.19043.1110], locale en-US)
    • Flutter version 2.2.3 at C:\Users\Taha\Code\flutter_stable
    • Framework revision f4abaa0735 (4 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\android-sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_SDK_ROOT = C:\Users\Taha\Code\android-sdk
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java.exe
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2022 17.0.0 Preview 2.1)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Preview
    • Visual Studio Community 2022 version 17.0.31521.260
    • The current Visual Studio installation is a pre-release version. It may not be supported by Flutter yet.
    • Windows 10 SDK version 10.0.19041.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[✓] VS Code (version 1.58.2)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.24.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19043.1110]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 92.0.4515.107
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 92.0.902.55

! Doctor found issues in 1 category.
```

</details>

Can you please try again?

**Comment by MakufonSkifto** [comment] 2021-07-30 09:34
Hi @TahaTesser 

Even after using a different GitHub pages, the result is still the same. Should I delete and re-install flutter?

**Comment by TahaTesser** [comment] 2021-07-30 10:44
@MakufonSkifto 
I think this is same as https://github.com/flutter/flutter/issues/83703
Closing as duplicate of https://github.com/flutter/flutter/issues/83703

**Closed by TahaTesser** 2021-07-30 10:44 UTC
Labels: in triage
