### ISSUE TITLE
dart roller failing to load windows artifacts

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#115666] opened 2022-11-18 21:28 UTC
The dart roller is stuck.  It appears to be trying to load artifacts from dart windows builds, but it is failing to do so.  I'm not sure where the failure is.  Hopefully the infra team has a better idea.

Example failed roll: https://github.com/flutter/engine/pull/37759

Error log
```
________ running 'cipd ensure -log-level error -root C:\b\s\w\ir\cache\builder -ensure-file C:\b\s\w\ir\x\t\tmpq63vqxx5.ensure' in '.'
Errors:
  failed to resolve flutter/dart-sdk/windows-arm64@git_revision:d4cff06c810cf486d190e6e05f8e50f4525d22d6 (line 8): no such tag
Error: Command 'cipd ensure -log-level error -root C:\\b\\s\\w\\ir\\cache\\builder -ensure-file C:\\b\\s\\w\\ir\\x\\t\\tmpq63vqxx5.ensure' returned non-zero exit status 1
Errors:
  failed to resolve flutter/dart-sdk/windows-arm64@git_revision:d4cff06c810cf486d190e6e05f8e50f4525d22d6 (line 8): no such tag
```

cc @a-siva in case he has some dart background on the issue of the missing artifacts

**Comment by gaaclarke** [comment] 2022-11-18 21:36
Looks like the Dart infra failed to build the windows artifacts: https://ci.chromium.org/ui/p/dart-internal/builders/ci/dart-sdk-win-arm64-dev/61/overview

**Comment by gaaclarke** [comment] 2022-11-18 23:16
The dart windows build has happened now.  In theory the autoroller should keep rolling and pick up the artifacts on the next roll.

**Comment by chifandeyu** [comment] 2022-11-27 01:30
> The dart windows build has happened now. In theory the autoroller should keep rolling and pick up the artifacts on the next roll.

same error when run "gclient sync"

**Comment by Hixie** [comment] 2022-11-30 00:00
Looks like this is a duplicate of the more recent https://github.com/flutter/flutter/issues/116107 now.

**Closed by Hixie** 2022-11-30 00:00 UTC
Labels: P0
