### ISSUE TITLE
Empty linter rules turns off rules from include directive in 2.2.3 (Stable)

### ISSUE THREAD

**Issue by davidjaldred** [flutter/flutter#86747] opened 2021-07-20 22:40 UTC
Following the migration guide here: https://flutter.dev/docs/release/breaking-changes/flutter-lints-package

Using the template [analysis_options.yaml](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/templates/app_shared/analysis_options.yaml.tmpl) (same as the one that is created with `flutter create` using Flutter version 2.3.0-12.0.pre or newer), linter rules from the include directive are not being used. I'm only seeing 3 lints in my project: dart(todo), dart(missing_required_param), dart(unused_import), which is actually less than the default set of lints I was seeing before migrating.

This can be fixed if I comment out/remove the empty `linter: rules:`, or by adding a linter rule, e.g. by uncommenting `# avoid_print: false`. The rules from the include directive are then applied correctly.

## Steps to Reproduce

1. Create a new Flutter 2.2.3 project using `flutter create`. 
2. Follow the migration guide provided in [Introducing package:flutter_lints](https://flutter.dev/docs/release/breaking-changes/flutter-lints-package).
3. Run `flutter analyze`, see no issues found.
4. Comment out `linter:` and `rules:` in analysis_options.yaml (lines 11 and 23)
5. Run `flutter analyze`, see 4 issues found:
info - Use key in widget constructors - lib\main.dart:7:7 - use_key_in_widget_constructors
info - Prefer declaring const constructors on `@immutable` classes - lib\main.dart:31:3 - prefer_const_constructors_in_immutables
info - Prefer const with constant constructors - lib\main.dart:96:13 - prefer_const_constructors
info - Prefer const with constant constructors - lib\main.dart:109:16 - prefer_const_constructors

**Expected results:**

Those 4 issues should be identified after following the migration guide, without any modification to analysis_options.yaml.

**Actual results:**

The issues are only found after removing the empty `linter: rules:` code, or by adding a lint rule.

**Comment by maheshmnj** [comment] 2021-07-21 08:23
Hi @davidjaldred,
Thanks for filing the issue, I am able to replicate this issue on the stable channel but This is not reproducible on the master channel. This will be available on the stable channel in the upcoming release. Until this is available you may use the master channel by running

```
flutter channel master
flutter upgrade.
``` 
You may read more about the [flutter channels here](https://github.com/flutter/flutter/wiki/Flutter-build-release-channels).
 I am going to close this issue as fixed since this is not reproducible on the master channel. If you disagree feel free to comment and I will reopen it. 

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-arm, locale en-GB)
    • Flutter version 2.2.3 at /Users/mahesh/Documents/flutter
    • Framework revision f4abaa0735 (3 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 57.0.5
    • Dart plugin version 211.7233

[✓] VS Code (version 1.58.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.24.0

[✓] Connected device (3 available)
    • iPhone 12 Pro Max (mobile) • 6A434744-B348-4FB3-AB10-131292174456 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS
      11.4 20F71 darwin-arm
    • Chrome (web)               • chrome                               • web-javascript • Google
      Chrome 91.0.4472.164

• No issues found!
```

```
[✓] Flutter (Channel master, 2.4.0-5.0.pre.87, on macOS 11.4 20F71 darwin-arm, locale en-GB)
    • Flutter version 2.4.0-5.0.pre.87 at /Users/mahesh/Documents/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e084e9d946 (2 days ago), 2021-07-17 12:00:21 -0700
    • Engine revision 14a9e9a50e
    • Dart version 2.14.0 (build 2.14.0-321.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 57.0.5
    • Dart plugin version 211.7233

[✓] VS Code (version 1.58.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.24.0

[✓] Connected device (3 available)
    • iPhone 12 Pro Max (mobile) • 6A434744-B348-4FB3-AB10-131292174456 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-4
      (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 11.4 20F71 darwin-arm
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 91.0.4472.114

• No issues found!
```
</details>
 
 Thank you.

**Closed by maheshmnj** 2021-07-21 08:23 UTC
Labels: in triage
