### ISSUE TITLE
[Video Player]AVPlayerItem videoComposition may cause the app to crash

### ISSUE THREAD

**Issue by indeedshaw** [flutter/flutter#151024] opened 2024-06-29 03:52 UTC
### Steps to reproduce

In some cases, incorrect video composition parameters may cause the program to crash.I get a crash report, and I navigate here, but I don't have a video to reproduce.
[https://github.com/flutter/packages/blob/b63626c31b919a97baa7c6ac542e8a9fa93dc3e6/packages/video_player/video_player_avfoundation/darwin/video_player_avfoundation/Sources/video_player_avfoundation/FVPVideoPlayerPlugin.m#L294](url)
Comments in AVFoundation:
`/*!
 @property 		videoComposition
				This property throws an exception if a video composition is set with any of the following values:
					- renderSize, renderScale, or frameDuration is less than or equal to zero
					- sourceTrackIDForFrameTiming is less than or equal to zero
					- uses AVVideoCompositionCoreAnimationTool (works for offline rendering only)
 */`

Maybe we should check the resulting parameters here.I'm not familiar with the code design of this plugin. How should we handle AVPlayer after we got an exception.
[https://github.com/flutter/packages/blob/b63626c31b919a97baa7c6ac542e8a9fa93dc3e6/packages/video_player/video_player_avfoundation/darwin/video_player_avfoundation/Sources/video_player_avfoundation/FVPVideoPlayerPlugin.m#L211](url)

ps:We can set some wrong parameters for AVPlayerItem to reproduce, although that is not very appropriate.
// or other
videoComposition.renderSize = CGSizeMake(0, 1280);
item.videoComposition = videoComposition;

### Expected results

Application don't crash.

### Actual results

Application crashed.

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
libc++abi: terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[AVPlayerItem setVideoComposition:] video composition must have a positive renderSize'
terminating with uncaught exception of type NSException
CoreSimulator 857.14 - Device: iPhone 14 Pro Max (F24BF7F8-F42C-412B-B330-667120A94C13) - Runtime: iOS 16.2 (20C52) - DeviceType: iPhone 14 Pro Max
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console

┌─────────────────────────────────────────────────────────┐
│ A new version of Flutter is available!                  │
│                                                         │
│ To update to the latest version, run "flutter upgrade". │
└─────────────────────────────────────────────────────────┘
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.12, on macOS 12.6 21G115 darwin-arm64, locale
    zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✗] Chrome - develop for the web (Cannot find Chrome executable at
    /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Android Studio (version 2021.2)
[✓] IntelliJ IDEA Community Edition (version 2022.1.4)
[✓] VS Code (version 1.90.0)
[✓] Connected device (2 available)
HTTP Host availability check is taking a long time...[!] HTTP Host Availability
    ✗ HTTP host "https://maven.google.com/" is not reachable. Reason: An error
      occurred while checking the HTTP host: Operation timed out
    ✗ HTTP host "https://cloud.google.com/" is not reachable. Reason: An error
      occurred while checking the HTTP host: Operation timed out

! Doctor found issues in 2 categories.
```

</details>

**Comment by danagbemava-nc** [comment] 2024-09-19 06:39
This is a duplicate of https://github.com/flutter/flutter/issues/151031. 

Kindly follow up in the original issue for updates. 

Closing from here

Thank you

**Closed by danagbemava-nc** 2024-09-19 06:39 UTC
Labels: in triage
