### ISSUE TITLE
Cannot retain previously cached data

### ISSUE THREAD

**Issue by ModWU** [flutter/flutter#86934] opened 2021-07-23 11:14 UTC
[video_player]Locating video progress using the **seekTo** function cannot retain previously cached data，The video buffer data starts again！

## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. using the **seekTo** function

**Expected results:** 
Save previous buffered data and progress.

**Actual results:** 
The video buffer data starts again.

<details>
  <summary>Logs</summary>

_**flutter doctor -v**_
```
[√] Flutter (Channel master, 2.4.0-5.0.pre.6, on Microsoft Windows [Version 10.0.17763.194], locale zh-CN)
    • Flutter version 2.4.0-5.0.pre.6 at D:\flutter\last-new\flutter
    • Upstream repository git@github.com:flutter/flutter.git
    • Framework revision 08ef7752d5 (11 days ago), 2021-07-11 23:25:25 -0700
    • Engine revision ed25e8f01e
    • Dart version 2.14.0 (build 2.14.0-301.0.dev)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at D:\Android\Sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = D:\Android\Sdk
    • Java binary at: D:\AndroidStudio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.2.0)
    • Android Studio at D:\AndroidStudio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] Connected device (2 available)
    • SM G9500 (mobile) • 988bdc424259355033 • android-arm64  • Android 9 (API 28)
    • Chrome (web)      • chrome             • web-javascript • Google Chrome 85.0.4183.83
```

</details>

**Comment by TahaTesser** [comment] 2021-07-23 14:18
Hi @ModWU 
Is this on Android or the web?  As `video_player` both platforms

Can you please provide a complete reproducible minimal code sample
Thank you

**Comment by ModWU** [comment] 2021-07-25 18:32
> Hi @ModWU
> Is this on Android or the web? As `video_player` both platforms
> 
> Can you please provide a complete reproducible minimal code sample
> Thank you

Android

**Comment by ModWU** [comment] 2021-07-26 05:29
> > Hi @ModWU
> > Is this on Android or the web? As `video_player` both platforms
> > Can you please provide a complete reproducible minimal code sample
> > Thank you
> 
> Android

Hi，Here's my demo.

<details>
  <summary>DEMO</summary>

```
import 'package:flutter/material.dart';
import 'package:video_player/video_player.dart';

void main() => runApp(MaterialApp(home: VideoApp(),));

class VideoApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return DefaultTabController(
      length: 3,
      child: Scaffold(
        key: const ValueKey<String>('home_page'),
        body: _BumbleBeeRemoteVideo(),
      ),
    );
  }
}

class _BumbleBeeRemoteVideo extends StatefulWidget {
  @override
  _BumbleBeeRemoteVideoState createState() => _BumbleBeeRemoteVideoState();
}

class _BumbleBeeRemoteVideoState extends State<_BumbleBeeRemoteVideo> {
  late VideoPlayerController _controller;

  Future<ClosedCaptionFile> _loadCaptions() async {
    final String fileContents = await DefaultAssetBundle.of(context)
        .loadString('assets/bumble_bee_captions.srt');
    return SubRipCaptionFile(fileContents);
  }

  @override
  void initState() {
    super.initState();
    _controller = VideoPlayerController.network(
      'http://vfx.mtime.cn/Video/2019/02/04/mp4/190204084208765161.mp4',
      closedCaptionFile: _loadCaptions(),
      videoPlayerOptions: VideoPlayerOptions(mixWithOthers: true),
    );

    _controller.addListener(() {
      setState(() {});
    });
    _controller.setLooping(true);
    _controller.initialize();
  }

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return SingleChildScrollView(
      child: Column(
        children: <Widget>[
          Container(padding: const EdgeInsets.only(top: 20.0)),
          const Text('With remote mp4'),
          Container(
            padding: const EdgeInsets.all(20),
            child: AspectRatio(
              aspectRatio: _controller.value.aspectRatio,
              child: Stack(
                alignment: Alignment.bottomCenter,
                children: <Widget>[
                  VideoPlayer(_controller),
                  ClosedCaption(text: _controller.value.caption.text),
                  _ControlsOverlay(controller: _controller),
                  VideoProgressIndicator(_controller, allowScrubbing: true, colors: const VideoProgressColors(playedColor: Colors.white, bufferedColor: Colors.red),),
                ],
              ),
            ),
          ),
        ],
      ),
    );
  }
}

class _ControlsOverlay extends StatelessWidget {
  const _ControlsOverlay({Key? key, required this.controller})
      : super(key: key);

  static const _examplePlaybackRates = [
    0.25,
    0.5,
    1.0,
    1.5,
    2.0,
    3.0,
    5.0,
    10.0,
  ];

  final VideoPlayerController controller;

  @override
  Widget build(BuildContext context) {
    return Stack(
      children: <Widget>[
        AnimatedSwitcher(
          duration: Duration(milliseconds: 50),
          reverseDuration: Duration(milliseconds: 200),
          child: controller.value.isPlaying
              ? SizedBox.shrink()
              : Container(
                  color: Colors.black26,
                  child: Center(
                    child: Icon(
                      Icons.play_arrow,
                      color: Colors.white,
                      size: 100.0,
                    ),
                  ),
                ),
        ),
        GestureDetector(
          onTap: () {
            controller.value.isPlaying ? controller.pause() : controller.play();
          },
        ),
        Align(
          alignment: Alignment.topRight,
          child: PopupMenuButton<double>(
            initialValue: controller.value.playbackSpeed,
            tooltip: 'Playback speed',
            onSelected: (speed) {
              controller.setPlaybackSpeed(speed);
            },
            itemBuilder: (context) {
              return [
                for (final speed in _examplePlaybackRates)
                  PopupMenuItem(
                    value: speed,
                    child: Text('${speed}x'),
                  )
              ];
            },
            child: Padding(
              padding: const EdgeInsets.symmetric(
                // Using less vertical padding as the text is also longer
                // horizontally, so it feels like it would need more spacing
                // horizontally (matching the aspect ratio of the video).
                vertical: 12,
                horizontal: 16,
              ),
              child: Text('${controller.value.playbackSpeed}x'),
            ),
          ),
        ),
      ],
    );
  }
}

```
  
</details>

**_Show_**
Uploading device-2021-07-26-132301.mp4…

_**Tips:**
In the above video show, each time drag progress is called (called to the `seekTo` function),  
The red buffer starts again!_

**Comment by TahaTesser** [comment] 2021-07-26 09:56
Hi @ModWU 
I see there's an open issue addressing the case you described.
Please follow up on that issue, Closing as duplicate of https://github.com/flutter/flutter/issues/28094
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-07-26 09:56 UTC
Labels: in triage
