### ISSUE TITLE
FlutterView.runFromBundle not working when called 2nd time

### ISSUE THREAD

**Issue by radzish** [flutter/flutter#16998] opened 2018-04-26 10:01 UTC
## Steps to Reproduce

Launching entry points using FlutterView.runFromBundle is broken (master as of now and latest beta 0.3.1 are affected). Steps:
- create flutter project
- add following line to MainActivity.onCreate
```dart
    getFlutterView().runFromBundle(FlutterMain.findAppBundlePath(getApplicationContext()), null, "entry_point");
```
- add following code to main.dart
```dart
void entry_point() {
  print("test");
}
```

I am assuming now one can not call **FlutterView.runFromBundle** second time. In my real application I first call non-main entry point (let say from background service) and then when activity is launched it tries to call main one and fails, which results in black screen.
This issue is quite important to application we are working on, as it affects its architecture and the way how android background processing is implemented.
Please note that everything was working fine on previous beta release. So this stuff was broken with latest one. 

## Logs

The following line can be found in logs
```
[  +89 ms] E/flutter ( 8319): [ERROR:flutter/shell/platform/android/android_shell_holder.cc(104)] Could not launch engine in configuration.
``` 
instead of expected "test" output

## Flutter Doctor
```
[✓] Flutter (Channel beta, v0.3.1, on Linux, locale en_US.UTF-8)
    • Flutter version 0.3.1 at 
    • Framework revision 12bbaba9ae (6 days ago), 2018-04-19 23:36:15 -0700
    • Engine revision 09d05a3891
    • Dart version 2.0.0-dev.48.0.flutter-fe606f890b

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).
      If Android SDK has been installed to a custom location, set $ANDROID_HOME to that location.

[✓] Android Studio (version 3.1)
    • Android Studio at 
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[!] IntelliJ IDEA Ultimate Edition (version 2018.1)
    • IntelliJ at 
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[!] IntelliJ IDEA Ultimate Edition (version 2017.3)
    • IntelliJ at 
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.22.2)
    • VS Code at /usr/share/code
    • Dart Code extension version 2.10.0

[!] Connected devices
    ! No devices available

! Doctor found issues in 4 categories.
```

**Comment by gazialankus** [comment] 2018-05-01 01:07
I believe android_alarm_manager is broken at the moment. I set up frequent periodic alarms but only get the first ones. I see the quoted error in the logs.

**Comment by gazialankus** [comment] 2018-05-01 18:52
I can confirm that downgrading Flutter to v0.2.4 https://github.com/flutter/flutter/commit/3352a3fb488df4742ff323243d3dc44d9b7cd3e8 makes this problem go away.

**Comment by alanrussian** [comment] 2018-05-09 23:51
Thanks for filing this issue. mulligan is facing this too.

**Comment by marcmo** [comment] 2018-05-11 15:01
just ran into this... might be good to mention it on the android_alarm_manager plugin repo

**Comment by radzish** [comment] 2018-05-11 16:56
btw.. I overcame that issue. So now I am always calling "main". In case I run it from background, I just call main but on dart side I am not launching "runApp" from main. Instead I am setting up background stuff and channel, subscribe to that channel and then when MainActivity is run (when app UI is launched), I am just invoking method on that channel which in turn calls "runApp". Doing this way I do not need different entry points anymore.
as for "android_alarm_manager", I just implemented it myself and it is based on calling channel method rather than calling dart entry point.

**Comment by radzish** [comment] 2018-05-12 09:27
@alanrussian I just copied all I needed from FlutterActivity and FlutterActivityDelegate into my activity, and yes, I am omitting runFromBundle call rather calling method on channel

**Comment by zoechi** [comment] 2018-12-04 12:58
Is this still an issue?

**Comment by alanrussian** [comment] 2018-12-04 17:16
I believe so, yes

**Comment by DevFatani** [comment] 2019-01-22 20:53
@radzish solving this by add this code
1️⃣
`override fun onDestroy() {
        if (flutterView != null) {
            flutterView.destroy()
        }
        super.onDestroy()
    }`

2️⃣
`  override fun onPause() {
        super.onPause()
        flutterView.onPause()
    }
`

3️⃣
`  override fun onPostResume() {
        super.onPostResume()
        flutter_slide.onPostResume()
    }`

4️⃣
`override fun onStart() {
        super.onStart()
        t_f_v.onStart()
    }`

5️⃣
` override fun onStop() {
        super.onStop()
        t_f_v.onStop()
    }`

**Comment by markusaksli-nc** [comment] 2020-10-15 09:19
Closing this since it isn't relevant anymore in the current embedding workflow.

**Closed by markusaksli-nc** 2020-10-15 09:19 UTC
Labels: P4, customer: mulligan (g3), engine
