### ISSUE TITLE
[tool_crash] _TypeError: (#0      AndroidStudioJavaGradleConflictMigration.migrate (package:flutter_tools/src/android/migrations/android_studio_java_gradle_conflict_migration.dart:107:39))

### ISSUE THREAD

**Issue by whitewidow31** [flutter/flutter#125687] opened 2023-04-28 15:07 UTC
## Command
```
flutter --no-color run --machine --track-widget-creation --device-id=emulator-5554 --start-paused --dart-define=flutter.inspector.structuredErrors=true lib/main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
_TypeError: (#0      AndroidStudioJavaGradleConflictMigration.migrate (package:flutter_tools/src/android/migrations/android_studio_java_gradle_conflict_migration.dart:107:39))
```
#0      AndroidStudioJavaGradleConflictMigration.migrate (package:flutter_tools/src/android/migrations/android_studio_java_gradle_conflict_migration.dart:107:39)
#1      ProjectMigration.run (package:flutter_tools/src/base/project_migrator.dart:84:16)
#2      AndroidGradleBuilder.buildGradleApp (package:flutter_tools/src/android/gradle.dart:280:15)
#3      AndroidGradleBuilder.buildApk (package:flutter_tools/src/android/gradle.dart:208:11)
#4      AndroidDevice.startApp (package:flutter_tools/src/android/android_device.dart:578:29)
<asynchronous suspension>
#5      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:468:33)
<asynchronous suspension>
#6      Future.wait.<anonymous closure> (dart:async/future.dart:525:21)
<asynchronous suspension>
#7      HotRunner.run (package:flutter_tools/src/run_hot.dart:421:34)
<asynchronous suspension>
#8      AppDomain.launch.<anonymous closure> (package:flutter_tools/src/commands/daemon.dart:649:9)
<asynchronous suspension>
#9      AppDomain.launch (package:flutter_tools/src/commands/daemon.dart:647:5)
<asynchronous suspension>
#10     RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:638:15)
<asynchronous suspension>
#11     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1294:27)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#13     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:296:9)
```
```
[✓] Flutter (Channel master, 3.10.0-16.0.pre.24, on macOS 12.6.5 21G531 darwin-x64, locale en-GB)
    • Flutter version 3.10.0-16.0.pre.24 on channel master at /Users/craignelson/Developer/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f87d208742 (39 minutes ago), 2023-04-28 22:24:49 +0800
    • Engine revision 1d25906b4c
    • Dart version 3.1.0 (build 3.1.0-49.0.dev)
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/craignelson/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] IntelliJ IDEA Community Edition (version 2022.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Community Edition (version 2023.1)
    • IntelliJ at /Users/craignelson/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/231.8109.175/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Community Edition (version 2022.3.3)
    • IntelliJ at /Users/craignelson/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/223.8836.41/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.77.3)
    • VS Code at /Users/craignelson/Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.62.0

[✓] Connected device (3 available)
    • sdk gphone x86 64 (mobile) • emulator-5554 • android-x64    • Android 13 (API 33) (emulator)
    • macOS (desktop)            • macos         • darwin-x64     • macOS 12.6.5 21G531 darwin-x64
    • Chrome (web)               • chrome        • web-javascript • Google Chrome 112.0.5615.137

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: master
**Creation framework version**: 55c988fb453eddd97cb2e4d6df9ec28d72e2e899

**Comment by whitewidow31** [comment] 2023-04-28 15:08
Working fine before flutter and dart upgrade?

**Comment by danagbemava-nc** [comment] 2023-05-02 06:55
Closing this as a duplicate of https://github.com/flutter/flutter/issues/125712 which has more details on https://github.com/flutter/flutter/issues/125712#issuecomment-1528101662 and possible fix as mentioned https://github.com/flutter/flutter/issues/125712#issuecomment-1530238853, so please upgrade to latest master and see if you still get the same crash or not. If yes, please write in the comments and I'll reopen it.

**Closed by danagbemava-nc** 2023-05-02 06:55 UTC
Labels: in triage
