### ISSUE TITLE
crash camera on android 9

### ISSUE THREAD

**Issue by shivamagarwal2097** [flutter/flutter#127954] opened 2023-05-31 12:03 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Choose Image Picker camera option one plus android 9

### Expected results

Get image path

### Actual results

crash application

### Code sample

<details><summary>Code sample</summary>

  final ImagePicker _picker = ImagePicker();
    final XFile? image = await _picker.pickImage(source: imageSource,requestFullMetadata: false);

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

java.lang.SecurityException: Permission Denial: writing com.android.providers.media.MediaProvider uri content://media/external/file from pid=22262, uid=10154 requires android.permission.WRITE_EXTERNAL_STORAGE, or grantUriPermission()

</details>
<img width="1260" alt="image" src="https://github.com/flutter/flutter/assets/67942307/0b671e62-babf-4578-947a-34d5d2467221">

### Logs

<details><summary>Logs</summary>

java.lang.SecurityException: Permission Denial: writing com.android.providers.media.MediaProvider uri content://media/external/file from pid=22262, uid=10154 requires android.permission.WRITE_EXTERNAL_STORAGE, or grantUriPermission()

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

java.lang.SecurityException: Permission Denial: writing com.android.providers.media.MediaProvider uri content://media/external/file from pid=22262, uid=10154 requires android.permission.WRITE_EXTERNAL_STORAGE, or grantUriPermission()

</details>

**Comment by danagbemava-nc** [comment] 2023-05-31 13:42
Closing this as a duplicate of https://github.com/flutter/flutter/issues/87896. 

Kindly subscribe to the original issue for updates. 

Thank you

**Closed by danagbemava-nc** 2023-05-31 13:42 UTC
Labels: in triage
