### ISSUE TITLE
Feature Request: Expose a system service API for keyboard backspace event

### ISSUE THREAD

**Issue by sgon00** [flutter/flutter#33167] opened 2019-05-22 05:46 UTC
Hi, Can flutter expose an API (maybe in services lib) to call the keyboard backspace delete event somehow?
I need to build a custom backspace raised button to backspace delete the textfield's text programmatically from the current cursor position in TextField, and since dart does not support dealing with grapheme clusters in string, it makes it's very hard to write a backspace function (when removing complex emojis). If I can simulate the keyboard backspace event somehow by calling flutter's API, that will make life much simpler.
Thank you very much.

**Comment by GaryQian** [comment] 2019-05-22 20:36
Just for reference, the way we handle keyboard events currently is from the "bottom up" where the platform itself (eg, Android, iOS, etc) directly handles much of the text data and keyboard, and passes those events up to Flutter. Exposing a truly similar call would probably involve some sort of method channel call down to native APIs to achieve.

**Comment by GaryQian** [comment] 2019-05-23 18:36
So right now, it should actually be possible to achieve what you want by using the same native API we (now) using through a method channel. A full exposure of text editing API would involve significant discussion, but it seems like you are mainly concerned with backspace, which you should be able to implement yourself.

Something along the lines of write a native method that takes the buffer and position, then returns the backspaced buffer back up to flutter through a method channel reply. In flutter, you should be able to update the buffers and position in the relevant widget.

**Comment by sgon00** [comment] 2019-05-24 06:40
@GaryQian Thanks a lot for the follow-up. I haven't written any native Android/iOS code yet. So I think I will simply stick with my current workaround, disallowing users to input emojis which have length greater than 2. I am OK for the current workaround. If exposure of text editing API would involve significant discussion and not will happen in the near future, do you want me to close this issue (feature request)? You can also close it if you want. It's not a big deal. Thanks.

**Comment by GaryQian** [comment] 2019-05-28 20:15
Let's keep this open for now, as if it gets closed, we will likely loose track of it.

**Comment by altShiftDev** [comment] 2019-11-15 18:35
I'd also like this feature. My current app uses a widget "[emoji picker](https://github.com/JeffG05/emoji_picker)" which does not have a backspace key. For this reason a user switching from text input to emoji input would have to switch back to text input in order to erase the last inputted emoji. If that was confusing let me explain:

Step1: user types "hello "
Step2: user switches to a flutterbased emoji keyboard and adds in"😁😗" (full string becomes "hello 😁😗")
Step3: user realizes the second emoji was inputted by accident and can't erase it with the currently open emoji text field so they switch back to native keyboard.
Step4: user erases it with native backspace and sends message.

Steps 3 & 4 are redundant and can be improved with a programmatic backspace key. I tried my hand at creating one like so:

```
Icon(Icons.backspace),
  onPressed: () => {
    print(messageController.text),
    print(messageController.text.substring(0, messageController.text.length - 1)),
  },
),
```
This would work if emojis were treated like normal characters but what happens in console is the following:

```
I/flutter (15055): 😗
I/flutter (15055): ���
```
The emoji character does not like being manipulated with a substring method and becomes corrupted, this wouldn't happen if we could expose the native backspace method.

**Comment by justinmc** [comment] 2020-03-30 19:55
@altShiftDev I wonder if you could work around this by using the [Runes](https://master-api.flutter.dev/flutter/dart-core/Runes-class.html) API.  The emoji 😗 is a surrogate, so Dart's String class considers it to have length 2, but Runes correctly identifies it as 1.  If you could detect that, you could cut off 2 in your `substring` call instead of 1.

However, you'd still have problems with grapheme clusters like 👨‍👩‍👦, which Runes considers to be of length 5 (and String length 8), but a user would expect to delete with one key press.  You'd have to use the [characters package](https://pub.dev/packages/characters) to handle grapheme clusters as well.

**Comment by pedromassangocode** [comment] 2020-11-30 13:27
@GaryQian @justinmc 
Isn't this a duplicate of https://github.com/flutter/flutter/issues/14809?

**Comment by justinmc** [comment] 2020-12-03 00:54
I don't think this is a duplicate of https://github.com/flutter/flutter/issues/14809, but I actually think that this can be closed now that the characters package is a part of Flutter.

You could use @altShiftDev's approach [above](https://github.com/flutter/flutter/issues/33167#issuecomment-554477791), but the onPressed would look something like this:

```dart
onPressed: () => {
  // This will print the current text minus the final character.
  // Works for extended grapheme clusters, surrogate pairs,
  // and plain text.
  print(messageController.text.characters.skipLast(1).string.length);
}
```

Let me know if there's still a problem here and I'll reopen!

**Closed by justinmc** 2020-12-03 00:54 UTC
Labels: a: text input, engine, passed first triage, severe: new feature
