### ISSUE TITLE
Firebase codelab is missing step to enable storage?

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#12763] opened 2017-10-27 13:37 UTC
RE: https://codelabs.developers.google.com/codelabs/flutter-firebase/#9

We could not get this step to work. After running the app, and selecting the image, the app failed with an "-13000" error in the log file. 

Going to the Firebase console, opening the Storage section, and selecting "Get Started" seemingly fixed this.

This bug was found during a "dryrun" of the Firebase codelab in AAR by @floitschG, @mravn-google, and @mit-mit.

**Comment by mit-mit** [comment] 2017-10-27 13:37
@collinjackson does this ring a bell? is this a required step?

**Comment by emshack** [comment] 2017-10-27 16:27
This is a duplicate of [#35](https://github.com/flutter/friendlychat-steps/issues/35) in the friendlychat-steps repo, where we've been tracking other codelab bugs.

**Comment by emshack** [comment] 2017-10-27 16:27
(I believe it has been fixed)

**Comment by LarkAscending** [comment] 2017-10-27 17:39
It has been fixed.

@mit-mit @floitschG @mravn-google 
Feel free to ping before dry running through any codelab. There are likely fixes that you can't see... and a update process you can plug into to stay in sync. Thanks!

**Closed by LarkAscending** 2017-10-27 17:39 UTC
Labels: dev: docs - codelab
