### ISSUE TITLE
Got socket error trying to find package dio at https://pub.flutter-io.cn. -> https://pub.flutter-io.cn ?

### ISSUE THREAD

**Issue by sonderss** [flutter/flutter#66423] opened 2020-09-23 06:29 UTC
Get socket error trying to find package DIO at is reported when pub get in Android studio https://pub.flutter-io.cn.

But when I remove the (DIO comment)

dependencies:
cupertino_ icons: ^0.1.3
// dio: ^3.0.10

pub get is success

**Comment by TahaTesser** [comment] 2020-09-23 08:55
Hi @sonderss 
Duplicate of https://github.com/flutter/flutter/issues/57982, check your firewall https://github.com/flutter/flutter/issues/57982#issuecomment-634384315

For issues related to pub, please file an issue on their dedicated GitHub [repository](https://github.com/dart-lang/pub)

Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2020-09-23 08:55 UTC
