### ISSUE TITLE
VirtualView node must not be the root node. on stable channel 

### ISSUE THREAD

**Issue by heshesh2010** [flutter/flutter#50919] opened 2020-02-17 13:10 UTC
I'm run on stable flutter and i get this error on my real device running  :

VirtualView node must not be the root node.

here is my log :

     `Installing build\app\outputs\apk\app.apk...
Syncing files to device SM N920C...
I/Choreographer(15799): Skipped 35 frames!  The application may be doing too much work on its main thread.
D/ViewRootImpl@746611[MainActivity](15799): Relayout returned: oldFrame=[0,0][1080,1920] newFrame=[0,0][1080,1920] result=0x1 surface={isValid=true 530729369088} surfaceGenerationChanged=false
D/SurfaceView(15799): Relayout returned: oldFrame=[0,0][1080,1920] newFrame=[0,0][1080,1920] result=0x1 surface={Surface(name=null)/@0x2d8db4e isValid=true 530628408832}
D/ViewRootImpl@746611[MainActivity](15799): MSG_RESIZED_REPORT: ci=Rect(0, 63 - 0, 0) vi=Rect(0, 63 - 0, 0) or=1
D/ViewRootImpl@746611[MainActivity](15799): MSG_WINDOW_FOCUS_CHANGED 1
D/ViewRootImpl@746611[MainActivity](15799): mHardwareRenderer.initializeIfNeeded()#2 mSurface={isValid=true 530729369088}
V/InputMethodManager(15799): Starting input: tba=android.view.inputmethod.EditorInfo@57b546f nm : com.hesham.order_vendor_app ic=null
I/InputMethodManager(15799): [IMM] startInputInner - mService.startInputOrWindowGainedFocus
D/InputTransport(15799): Input channel constructed: fd=94
V/InputMethodManager(15799): Starting input: tba=android.view.inputmethod.EditorInfo@616f57c nm : com.hesham.order_vendor_app ic=null
I/flutter (15799): ar_
D/ViewRootImpl@746611[MainActivity](15799): MSG_WINDOW_FOCUS_CHANGED 0
E/AccessibilityBridge(15799): VirtualView node must not be the root node.
I/flutter (15799): eQnZmLWjehE:APA91bGQP3PWAwDD_0fPVaMFhDCQ8fqFHW_8sSvY22SSh1iueC4Omsn80T3SEDQnQQ8A-z3TW5hO8cBMd0gtoRcja08wA2ZViBCWMXOPN6TGpLLcpbuDl22ZUvu0YpCPK3KEdJUZhqOW
I/flutter (15799): ar_
E/flutter (15799): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: Connection closed before full header was received
E/flutter (15799): #0      IOClient.send (package:http/src/io_client.dart:65:7)
E/flutter (15799): <asynchronous suspension>
E/flutter (15799): #1      BaseClient._sendUnstreamed (package:http/src/base_client.dart:176:38)
E/flutter (15799): #2      BaseClient.get (package:http/src/base_client.dart:35:7)
E/flutter (15799): #3      get.<anonymous closure> (package:http/http.dart:46:36)
E/flutter (15799): #4      _withClient (package:http/http.dart:166:20)
E/flutter (15799): #5      get (package:http/http.dart:46:5)
E/flutter (15799): #6      initSettings (package:order_vendor_app/src/repository/settings_repository.dart:21:26)
E/flutter (15799): #7      Controller.initState (package:order_vendor_app/src/controllers/controller.dart:18:5)
E/flutter (15799): #8      StateMVC.initState.<anonymous closure> (package:mvc_pattern/mvc_pattern.dart:448:56)
E/flutter (15799): #9      List.forEach (dart:core-patch/growable_array.dart:285:8)
E/flutter (15799): #10     StateMVC.initState (package:mvc_pattern/mvc_pattern.dart:448:21)
E/flutter (15799): #11     SplashScreenState.initState (package:order_vendor_app/src/pages/splash_screen.dart:27:11)
E/flutter (15799): #12     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4355:58)
E/flutter (15799): #13     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
E/flutter (15799): #14     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter (15799): #15     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter (15799): #16     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
E/flutter (15799): #17     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter (15799): #18     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter (15799): #19     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
E/flutter (15799): #20     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
E/flutter (15799): #21     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
E/flutter (15799): #22     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
E/flutter (15799): #23     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter (15799): #24     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter (15799): #25     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
E/flutter (15799): #26     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter (15799): #27     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter (15799): #28     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
E/flutter (15799): #29     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter (15799): #30     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter (15799): #31     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
E/flutter (15799): #32     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
E/flutter (15799): #33     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
E/flutter (15799): #34     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4381:11)
E/flutter (15799): #35     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
E/flutter (15799): #36     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter (15799): #37     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter (15799): #38     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
E/flutter (15799): #39     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter (15799): #40     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter (15799): #41     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
E/flutter (15799): #42     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter (15799): #43     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter (15799): #44     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
E/flutter (15799): #45     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
E/flutter (15799): #46     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
E/flutter (15799): #47     StatefulElement._firstBuild (
E/AccessibilityBridge(15799): VirtualView node must not be the root node.
D/ViewRootImpl@746611[MainActivity](15799): MSG_WINDOW_FOCUS_CHANGED 1
D/ViewRootImpl@746611[MainActivity](15799): mHardwareRenderer.initializeIfNeeded()#2 mSurface={isValid=true 530729369088}
D/ViewRootImpl@746611[MainActivity](15799): MSG_WINDOW_FOCUS_CHANGED 0
D/InputTransport(15799): Input channel destroyed: fd=94
E/AccessibilityBridge(15799): VirtualView node must not be the root node.
E/AccessibilityBridge(15799): VirtualView node must not be the root node.
D/ViewRootImpl@746611[MainActivity](15799): Relayout returned: oldFrame=[0,0][1080,1920] newFrame=[0,0][1080,1920] result=0x1 surface={isValid=true 530729369088} surfaceGenerationChanged=false
E/AccessibilityBridge(15799): VirtualView node must not be the root node.
E/AccessibilityBridge(15799): VirtualView node must not be the root node.
D/ViewRootImpl@746611[MainActivity](15799): MSG_WINDOW_FOCUS_CHANGED 1
D/ViewRootImpl@746611[MainActivity](15799): mHardwareRenderer.initializeIfNeeded()#2 mSurface={isValid=true 530729369088}
V/InputMethodManager(15799): Starting input: tba=android.view.inputmethod.EditorInfo@99da937 nm : com.hesham.order_vendor_app ic=null
I/InputMethodManager(15799): [IMM] startInputInner - mService.startInputOrWindowGainedFocus
D/InputTransport(15799): Input channel constructed: fd=94
D/ViewRootImpl@746611[MainActivity](15799): ViewPostImeInputStage processPointer 0
W/System  (15799): ClassLoader referenced unknown path: /system/framework/QPerformance.jar
E/BoostFramework(15799): BoostFramework() : Exception_1 = java.lang.ClassNotFoundException: Didn't find class "com.qualcomm.qti.Performance" on path: DexPathList[[],nativeLibraryDirectories=[/system/lib64, /vendor/lib64]]
V/BoostFramework(15799): BoostFramework() : mPerf = null
D/ViewRootImpl@746611[MainActivity](15799): ViewPostImeInputStage processPointer 1
E/AccessibilityBridge(15799): VirtualView node must not be the root node.
E/AccessibilityBridge(15799): VirtualView node must not be the root node.`

`Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [Version 10.0.17763.1039], locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed instructions.
[√] Android Studio (version 3.5)
[√] Connected device (2 available)

! Doctor found issues in 1 category.
`

**Comment by TahaTesser** [comment] 2020-02-17 13:24
Duplicate of [#50857](https://github.com/flutter/flutter/issues/50857) [#50892](https://github.com/flutter/flutter/issues/50892)

**Closed by TahaTesser** 2020-02-17 13:24 UTC
