### ISSUE TITLE
ios32 tests failing to install gems on MacOS 12

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#94480] opened 2021-12-01 18:17 UTC
```
  cocoapods was resolved to 1.11.2, which depends on
    cocoapods-core was resolved to 1.11.2, which depends on
      typhoeus was resolved to 1.4.0, which depends on
        ethon was resolved to 0.14.0, which depends on
          ffi
```

https://ci.chromium.org/ui/p/flutter/builders/staging/Mac_ios32%20flutter_gallery__transition_perf_e2e_ios32/449/overview

**Comment by CaseyHillers** [comment] 2021-12-01 18:17
\cc @jmagman

**Comment by jmagman** [comment] 2021-12-01 19:04
This doesn't have anything to do with the ios32 tests, it's that the staging pool is running macOS 12, which needs the new Xcode 13 package.  

This is a duplicate of https://github.com/flutter/flutter/issues/91633#issuecomment-983372733--I believe all staging tests running both macOS 12.0.1 and Xcode 13 are passing.  So when the infra team is ready, both should be applied to try and prod. 🤞

**Closed by jmagman** 2021-12-01 19:04 UTC
Labels: platform-ios, platform-mac, team: infra

**Comment by CaseyHillers** [comment] 2021-12-01 19:24
Full circle, back to infra :partying_face:
