### ISSUE TITLE
Unable build and run flutter project for mobile side on device since onward flutter ver 3.3.7

### ISSUE THREAD

**Issue by Dumasia** [flutter/flutter#123849] opened 2023-03-31 09:23 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I create a new project with the latest flutter version 3.7.9 and the same occurs flutter_plugin_android_lifecycle is not supported by the flutter version and some libraries but flutter_plugin_android_lifecycle is a major issue. This started appearing after flutter version 3.3.7. Please look into it because the flutter team is releasing a new version and has not been able to test wheater there is running/building fine or not.

### Actual results

Multiple build operations failed.
    Could not create task ':flutter_plugin_android_lifecycle:generateDebugUnitTestConfig'.
    Could not create task ':google_sign_in_android:generateDebugUnitTestConfig'.
    Could not create task ':image_picker_android:generateDebugUnitTestConfig'.
    Could not create task ':path_provider_android:generateDebugUnitTestConfig'.
    Could not create task ':shared_preferences_android:generateDebugUnitTestConfig'.
    Could not create task ':url_launcher_android:generateDebugUnitTestConfig'.
    Could not create task ':video_player_android:generateDebugUnitTestConfig'.
Could not create task ':flutter_plugin_android_lifecycle:generateDebugUnitTestConfig'.
this and base files have different roots: E:\Andriod Project\Github\dumasia\build\flutter_plugin_android_lifecycle and C:\Users\yazad\AppData\Local\Pub\Cache\hosted\pub.dev\flutter_plugin_android_lifecycle-2.0.9\android.

### Logs

<details>
<summary>Logs</summary>

```console

Multiple build operations failed.
    Could not create task ':flutter_plugin_android_lifecycle:generateDebugUnitTestConfig'.
    Could not create task ':google_sign_in_android:generateDebugUnitTestConfig'.
    Could not create task ':image_picker_android:generateDebugUnitTestConfig'.
    Could not create task ':path_provider_android:generateDebugUnitTestConfig'.
    Could not create task ':shared_preferences_android:generateDebugUnitTestConfig'.
    Could not create task ':url_launcher_android:generateDebugUnitTestConfig'.
    Could not create task ':video_player_android:generateDebugUnitTestConfig'.
Could not create task ':flutter_plugin_android_lifecycle:generateDebugUnitTestConfig'.
this and base files have different roots: E:\Andriod Project\Github\dumasia\build\flutter_plugin_android_lifecycle and C:\Users\yazad\AppData\Local\Pub\Cache\hosted\pub.dev\flutter_plugin_android_lifecycle-2.0.9\android.

```

</details>

### Flutter Doctor output

<details>
<summary>Doctor output</summary>

```console

E:\flutter\flutter_lastest\flutter\bin\flutter.bat doctor --verbose
[√] Flutter (Channel stable, 3.7.9, on Microsoft Windows [Version 10.0.19045.2728], locale en-IN)
    • Flutter version 3.7.9 on channel stable at E:\flutter\flutter_lastest\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 62bd79521d (15 hours ago), 2023-03-30 10:59:36 -0700
    • Engine revision ec975089ac
    • Dart version 2.19.6
    • DevTools version 2.20.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at E:\AndriodSdk
    • Platform android-33-ext4, build-tools 33.0.2
    • ANDROID_HOME = E:/AndriodSdk
    • ANDROID_SDK_ROOT = E:\AndriodSdk\platform-tools
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 2022.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)

[√] VS Code (version 1.76.2)
    • VS Code at C:\Users\yazad\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.20.0

[√] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 12 (API 31) (emulator)
    • sdk gphone64 x86 64 (mobile) • emulator-5556 • android-x64    • Android 12 (API 31) (emulator)
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 111.0.5563.147
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 111.0.1661.54

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
Process finished with exit code 0

```

</details>

**Comment by danagbemava-nc** [comment] 2023-03-31 13:47
Hi @Dumasia,

Please provide `flutter run --verbose` logs (this may be huge so kindly put it into a .txt file and attach it here) , and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) along with steps to reproduce so that we can investigate this issue. 

Thank you

**Comment by danagbemava-nc** [comment] 2023-04-03 06:39
Hi @Dumasia, please provide the complete output of `flutter run -v` in a .txt file. Please also provide your `android/build.gradle` & `android/app/build.gradle` along with the content of your `pubspec.lock`.

Thank you

**Comment by Dumasia** [comment] 2023-04-05 17:27
I just create a new Flutter project in Android Studio. Then normally add my
library for my project and then afterward clean the building project and
then try to build the Android module for permission and this issue arise .
.

Android Studio Electric Eel | 2022.1.1 Patch 2
Build #AI-221.6008.13.2211.9619390, built on February 17, 2023
Runtime version: 11.0.15+0-b2043.56-9505619 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 3072M
Cores: 8
Registry:
    external.system.auto.import.disabled=true
    debugger.watches.in.variables=false
    ide.text.editor.with.preview.show.floating.toolbar=false
    ide.instant.shutdown=false

Non-Bundled Plugins:
    idea.plugin.protoeditor (221.6095)
    com.jaeger.findviewbyme (1.4.3)
    com.bloc.intellij_generator_plugin (3.4.0)
    com.ankit.mahadik.json.dart.class (2.15)
    Dart (221.6103.1)
    com.developerphil.adbidea (1.6.8)
    io.flutter (73.0.1)

**Comment by danagbemava-nc** [comment] 2023-04-06 06:35
Hi @Dumasia, it turns out this is a duplicate of https://github.com/flutter/flutter/issues/105395. 

Your workaround, for now, is to make sure the project is on the same drive as your flutter SDK. 

Kindly follow up in the issue linked above for updates. 

Closing from here as duplicate. 

Thank you

**Closed by danagbemava-nc** 2023-04-06 06:35 UTC
Labels: in triage

**Comment by Dumasia** [comment] 2023-04-06 17:36
[flutter_run_logs.txt](https://github.com/flutter/flutter/files/11173097/flutter_run_logs.txt)
