### ISSUE TITLE
Program execution bug

### ISSUE THREAD

**Issue by alirezabashi98** [flutter/flutter#124924] opened 2023-04-15 16:23 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Why does Flutter give this error?
I searched a lot, but I didn't find anything. There is no problem with my code. I had added a PageView and it got this error. I went and removed it, but it didn't work.

Launching lib/main.dart on Linux in debug mode...
ERROR: /opt/flutter/packages/flutter/lib/src/rendering/viewport.dart:1457:15: Error: 'orthrow' isn't a type.
ERROR:               orthrow FlutterError.fromParts(<DiagnosticsNode>[
ERROR:               ^^^^^^^
ERROR: /opt/flutter/packages/flutter/lib/src/rendering/viewport.dart:1457:23: Error: Expected ';' after this.
ERROR:               orthrow FlutterError.fromParts(<DiagnosticsNode>[
ERROR:                       ^^^^^^^^^^^^
ERROR: /opt/flutter/packages/flutter/lib/src/rendering/viewport.dart:1457:35: Error: Expected an identifier, but got '.'.
ERROR: Try inserting an identifier before '.'.
ERROR:               orthrow FlutterError.fromParts(<DiagnosticsNode>[
ERROR:                                   ^
ERROR: Target kernel_snapshot failed: Exception
Building Linux application...                                           
Exception: Build process failed

### Expected results

When I deleted the code that caused the error, it should work. I deleted the Linux folder and took the output again, but it still didn't work. It's the same for my Android.

### Actual results

It's not a wrong code that I can use, it's normal Flutter code, I just added PageView, and then I got a problem. Before, I was getting output. After that, even after I deleted it and Flutter's default code, I had a problem again. I had this problem before in another project. I tried to update Flutter and it was fixed, but now I can't update Flutter to the latest version and it shouldn't be like this at all.

### Code sample

<details><summary>Code sample</summary>

```dart
It is not an error code, it is a normal flutter code

import 'package:flutter/material.dart';
import 'package:flutter_svg/flutter_svg.dart';
import 'package:story_studio/r.dart';

class HomeScreen extends StatelessWidget {
  const HomeScreen({super.key});

  @override
  Widget build(BuildContext context) {
    var controller = PageController(viewportFraction: 0.9);

    return Scaffold(
      body: CustomScrollView(
        slivers: [
          SliverToBoxAdapter(
            child: Stack(
              alignment: Alignment.topRight,
              children: [
                const SizedBox(
                  height: 220,
                  width: double.infinity,
                ),
                Positioned(
                  right: -12,
                  top: -8,
                  child: SizedBox(
                    height: 200,
                    width: 200,
                    child: FittedBox(
                      fit: BoxFit.fitHeight,
                      child: SvgPicture.asset(
                        AssetImages.backgroundHome,
                        semanticsLabel: 'Acme Logo',
                      ),
                    ),
                  ),
                ),
                Positioned(
                  right: 32,
                  top: 74,
                  child: Container(
                    width: 36,
                    height: 36,
                    padding: const EdgeInsets.all(8),
                    decoration: BoxDecoration(
                      color: Colors.white,
                      borderRadius: BorderRadius.circular(50),
                    ),
                    child: FittedBox(
                      fit: BoxFit.contain,
                      child: SvgPicture.asset(
                        AssetImages.search,
                        semanticsLabel: 'Acme Logo',
                      ),
                    ),
                  ),
                ),
                Positioned(
                  left: 0,
                  top: 22,
                  child: Padding(
                    padding:
                        const EdgeInsets.only(left: 20, right: 20, top: 38),
                    child: RichText(
                      text: const TextSpan(
                        text: 'Alireza,\n',
                        style: TextStyle(
                          color: Color(0xff2ADB7F),
                          fontSize: 33,
                          fontFamily: 'PB',
                        ),
                        children: <TextSpan>[
                          TextSpan(
                            text: 'welcome back',
                            style: TextStyle(
                              color: Colors.black,
                            ),
                          ),
                        ],
                      ),
                    ),
                  ),
                ),
              ],
            ),
          ),
          SliverToBoxAdapter(
            child: SizedBox(
              height: 150,
              child: PageView.builder(
                controller: controller,
                itemCount: 3,
                itemBuilder: (context, index) {
                  return Container(
                    margin: const EdgeInsets.symmetric(horizontal: 6),
                    decoration:
                        BoxDecoration(borderRadius: BorderRadius.circular(15)),
                    child: Image.asset(AssetImages.book),
                  );
                },
              ),
            ),
          ),
        ],
      ),
    );
  }
}


```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media [here]]([url]([url](url)))

</details>

### Logs

<details><summary>Logs</summary>

```console
Launching lib/main.dart on Linux in debug mode...
ERROR: /opt/flutter/packages/flutter/lib/src/rendering/viewport.dart:1457:15: Error: 'orthrow' isn't a type.
ERROR:               orthrow FlutterError.fromParts(<DiagnosticsNode>[
ERROR:               ^^^^^^^
ERROR: /opt/flutter/packages/flutter/lib/src/rendering/viewport.dart:1457:23: Error: Expected ';' after this.
ERROR:               orthrow FlutterError.fromParts(<DiagnosticsNode>[
ERROR:                       ^^^^^^^^^^^^
ERROR: /opt/flutter/packages/flutter/lib/src/rendering/viewport.dart:1457:35: Error: Expected an identifier, but got '.'.
ERROR: Try inserting an identifier before '.'.
ERROR:               orthrow FlutterError.fromParts(<DiagnosticsNode>[
ERROR:                                   ^
ERROR: Target kernel_snapshot failed: Exception
Building Linux application...                                           
Exception: Build process failed
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
flutter doctor -v                                                ✔ 
[✓] Flutter (Channel stable, 3.7.11, on Manjaro Linux 5.15.104-2-MANJARO, locale
    en_US.UTF-8)
    • Flutter version 3.7.11 on channel stable at /opt/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f72efea43c (4 days ago), 2023-04-11 11:57:21 -0700
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1

Checking Android licenses is taking an unexpectedly long time...[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /home/alireza/Android/Sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /opt/google/chrome/chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 15.0.7
    • cmake version 3.26.1
    • ninja version 1.11.1
    • pkg-config version 1.8.1

[✓] Android Studio (version 2021.3)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 71.0.3
    • Dart plugin version 213.7433
    • Java version OpenJDK Runtime Environment (build
      11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.3)
    • IntelliJ at /opt/idea-IU-223.8214.52
    • Flutter plugin version 71.2.6
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Proxy Configuration
    • HTTP_PROXY is set
    • NO_PROXY is localhost,127.0.0.0/8,::1,127.0.0.1
    • NO_PROXY contains localhost
    • NO_PROXY contains 127.0.0.1
    • NO_PROXY contains ::1

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Manjaro Linux
      5.15.104-2-MANJARO
    • Chrome (web)    • chrome • web-javascript • Google Chrome 112.0.5615.49
      unknown

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

</details>

**Comment by stuartmorgan** [comment] 2023-04-16 12:28
> ERROR: /opt/flutter/packages/flutter/lib/src/rendering/viewport.dart:1457:15: Error: 'orthrow' isn't a type.
> ERROR: orthrow FlutterError.fromParts([
> ERROR: ^^^^^^^

You have modified your local copy of the Flutter SDK; the actual code is just `throw`:

https://github.com/flutter/flutter/blob/3.7.11/packages/flutter/lib/src/rendering/viewport.dart#L1457

If you modify your copy of Flutter it's up to you to ensure that it continues to compile. Closing as this is not a bug in Flutter.

**Closed by stuartmorgan** 2023-04-16 12:28 UTC
