### ISSUE TITLE
Have started getting an error in my application after running flutter upgrade

### ISSUE THREAD

**Issue by kavyabhargava** [flutter/flutter#104048] opened 2022-05-18 07:23 UTC
: Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null.
../…/src/overlay_entry.dart:101
- 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../flutter/packages/flutter/lib/src/widgets/binding.dart').
        WidgetsBinding.instance?.scheduleFrameCallback((_) => animateRemove());
                       ^
e: /Users/kavyabhargava/FlutterDev/flutter/.pub-cache/hosted/pub.dartlang.org/share_plus-3.1.0/android/src/main/kotlin/dev/fluttercommunity/plus/share/MethodCallHandler.kt: (34, 24): Type mismatch: inferred type is String? but String was expected

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':share_plus:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 13s
Exception: Gradle task assembleDebug failed with exit code 1

Flutter doctor -v output:
```
[✓] Flutter (Channel stable, 3.0.0, on macOS 12.2.1 21D62 darwin-arm, locale en-IN)
    • Flutter version 3.0.0 at /Users/kavyabhargava/FlutterDev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ee4e09cce0 (8 days ago), 2022-05-09 16:45:18 -0700
    • Engine revision d1b9a6938a
    • Dart version 2.17.0
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/kavyabhargava/Library/Android/sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] VS Code (version 1.67.0)
    • VS Code at /Users/kavyabhargava/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.40.0

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 12 (API 32)
      (emulator)
    • macOS (desktop)             • macos         • darwin-arm64   • macOS 12.2.1 21D62
      darwin-arm
    • Chrome (web)                • chrome        • web-javascript • Google Chrome
      101.0.4951.54

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

**Comment by maheshmnj** [comment] 2022-05-18 07:44
Hi @kavyabhargava, Thanks for filing the issue. The build seems to be failing due to the null safety error in the `share_plus` plugin.


>e: /Users/kavyabhargava/FlutterDev/flutter/.pub-cache/hosted/pub.dartlang.org/share_plus-3.1.0/android/src/main/kotlin/dev/fluttercommunity/plus/share/MethodCallHandler.kt: (34, 24): Type mismatch: inferred type is String? but String was expected
FAILURE: Build failed with an exception.

>What went wrong:
Execution failed for task ':share_plus:compileDebugKotlin'.

 I would suggest filing that issue in its dedicated repo. Additionally, you may try using the latest version of the plugin `4.0.4` and see if it helps fix the issue.

partial duplicate of https://github.com/flutter/flutter/issues/103561  
Closing as this is not really a bug in flutter but with the third party plugin. In case you disagree feel free to write in the comments and we will reopen it.

Thank you.

**Closed by maheshmnj** 2022-05-18 07:44 UTC
Labels: in triage
