### ISSUE TITLE
Flutter v1.12.13+hotfix.5 unstable on android10

### ISSUE THREAD

**Issue by JCKodel** [flutter/flutter#48039] opened 2020-01-01 14:52 UTC
![image](https://user-images.githubusercontent.com/379339/71642567-1229e300-2c8c-11ea-8caf-1f5122206cd9.png)

Prior to point A: version 1.10.7 beta (because of Adreno 308 bug which rendered black screen on many devices).

Point A: applying the new "stable" version 1.12 (that fixes the Adreno 308 bug). It's the exactly same code. Thousands of crashes. Thousands of affected users (I have 140k users and the crashes affected +20k)

Point B: rollback to version 1.10.7 beta. (Not perfect, but at least I get 99.86% crash free)

I can't provide "steps to reproduce" nor more info because I don't have them (none of my devices show abnormal behavior), but I'm happy to share all Crashlytics and Google Play Console data, if it is usefull.

```console
[√] Flutter (Channel unknown, v1.10.7, on Microsoft Windows [Version 10.0.18362.535], locale pt-BR)
    • Flutter version 1.10.7 at C:\flutter
    • Framework revision e70236e36c (3 months ago), 2019-10-02 09:32:30 -0700
    • Engine revision 9e6314d348
    • Dart version 2.6.0 (build 2.6.0-dev.4.0 1103600280)


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\jckod\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = C:\Users\jckod\AppData\Local\Android\Sdk
    • ANDROID_SDK_ROOT = C:\Users\jckod\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.4.0)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.4.29519.181

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code, 64-bit edition (version 1.41.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.7.1

[√] Connected device (3 available)
    • XT1033   • 0423490246 • android-arm • Android 5.0.2 (API 21)
    • SM J415G • 785dd05b   • android-arm • Android 9 (API 28)
    • Windows  • Windows    • windows-x64 • Microsoft Windows [Version 10.0.18362.535]

• No issues found!
```

```yaml
environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  before_after: ^2.0.0
  cached_network_image: ^1.1.3
  connectivity: ^0.4.4
  datetime_picker_formfield: ^1.0.0-pre.5
  device_info: ^0.4.1+1
  diacritic: ^0.1.1
  dio: ^3.0.1
  firebase_admob: ^0.9.0+10
  firebase_analytics: ^5.0.2
  firebase_auth: ^0.15.1+1
  firebase_crashlytics: ^0.1.2+4
  firebase_messaging: ^6.0.9
  flutter_alert: ^0.4.0
  flutter_custom_tabs: ^0.6.0
  flutter_device_type: ^0.2.0
  flutter_email_sender: ^2.2.2
  flutter_facebook_login:
    git:
      url: https://github.com/CodeArtBR/flutter_facebook_login.git
  flutter_html: ^0.11.1
  flutter_image_compress: ^0.6.3
  flutter_local_notifications: ^0.9.1
  flutter_masked_text: ^0.8.0
  flutter_mobx: ^0.3.4+1
  flutter_secure_storage: ^3.3.1+1
  flutter_speed_dial: ^1.2.1
  flutter_svg: ^0.15.0
  flutter_svprogresshud: ^0.0.2
  google_api_availability: ^2.0.1
  google_sign_in: ^4.0.16
  image_cropper:
    git:
      url: https://github.com/hsangtini/flutter_image_cropper
  image_picker: ^0.6.1+4
  in_app_purchase: ^0.2.2+2
  jaguar_jwt: ^2.1.6
  material_design_icons_flutter: ^3.4.4795
  mobx: ^0.3.10
  path_provider: ^1.5.1
  photo_view: ^0.9.0
  rate_my_app: ^0.4.0
  sqflite: ^1.1.8
  sticky_headers: ^0.1.8
  table_calendar: ^2.0.2
  timeago: ^2.0.19
  timeago_flutter: ^0.1.0
  url_launcher: ^5.2.7
  uuid: ^2.0.2
  zefyr: ^0.8.0

dev_dependencies:
  build_runner: ^1.7.1
  mobx_codegen: ^0.3.9+1

dependency_overrides:
  json_annotation:
    path: lib/wsfx/builders/json_annotation
  json_serializable:
    path: lib/wsfx/builders/json_serializable
```

**Comment by mamm26** [comment] 2020-01-01 17:35
Is the problem of crash in Huawei? I was downloading the stable to see if it was fixed, but if it's this problem then no.

**Comment by JCKodel** [comment] 2020-01-01 17:53
> Is the problem of crash in Huawei? I was downloading the stable to see if it was fixed, but if it's this problem then no.

No. Is crashing in a lot of devices (mostly Samsung and Motorola, but those are more common in my country). Huawei are uncommon here.

**Comment by cielo** [comment] 2020-01-01 22:24
Is it possible that some of your plugins are not yet compatible with flutter 1.12+?

**Comment by iapicca** [comment] 2020-01-02 09:33
Hi @JCKodel 
I'm not sure how this issue would be workable without steps to reproduce it.

You also show a long list of dependencies, many of which 3rd party
that might not be "1.12 ready" which might mean that the error
could be unrelated the flutter sdk or 1st party plugins.

Could you provide the crash logs?
thank you

**Comment by carocean** [comment] 2020-01-02 14:09
该问题出现在： v1.12.13+hotfix.5 on android10

**Comment by JCKodel** [comment] 2020-01-02 14:22
> Hi @JCKodel
> I'm not sure how this issue would be workable without steps to reproduce it.
> 
> You also show a long list of dependencies,
> many of which 3rd party that might not be "1.12 ready";
> this means that the error **could** be unrelated
> to the flutter sdk or 1st party plugins.
> 
> Could you provide the crash logs?
> thank you

I will try to export the Crashlytics logs. In the meantime, here are some issues (some of them with Google Insights):

https://github.com/flutter/flutter/issues/47756
https://github.com/flutter/flutter/issues/47755
https://github.com/flutter/flutter/issues/47754  <-- This one happened a lot (resulting in "My app won't open" reviews)

**Comment by JCKodel** [comment] 2020-01-02 14:33
Firebase Crashlytics only exports logs to Big Data in a paid account (which I don't have).
Google Play Console doesn't have an export function ¬¬, so, I cannot share the crashes details =\

If anyone knows how can I export the crash logs without paying for them, please, let me know.

**Comment by JCKodel** [comment] 2020-01-02 14:35
Also, there is a lot of crashes that doesn't contain usefull information:

![image](https://user-images.githubusercontent.com/379339/71672143-e6723000-2d53-11ea-8a2f-0e6b840ea7f0.png)

This happens a lot with 1.12 and it crashes before the app is opened (showing that "App X has stopped working" dialog)

**Comment by carocean** [comment] 2020-01-03 04:11
Flutter 1.12.13.h5
Android 10
只要是以上环境，无论是模拟器还是真机，都会出现黑屏现象，即便是flutter官网例程也一样（flutter_gallery）

发自我的iPhone

**Comment by bhan** [comment] 2020-01-03 14:17
For anyone running into JNI crashes, I believe the relevant commit introducing the issue is in this thread: https://github.com/flutter/flutter/issues/48015

**Comment by iapicca** [comment] 2020-02-26 13:02
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.

**Closed by iapicca** 2020-02-26 13:02 UTC
Labels: e: device-specific, severe: crash, waiting for customer response, ▣ platform-android
