### ISSUE TITLE
[share] plugin - Add ability to share image/files

### ISSUE THREAD

**Issue by Sun3** [flutter/flutter#48821] opened 2020-01-14 18:13 UTC
## Use case

When sharing items from the app, most of the time its necessary to also share and image or a file, not just text.

## Proposal

Add the ability to share images or files along with text.

**Comment by Zazo032** [comment] 2020-01-14 18:25
Duplicate of https://github.com/flutter/flutter/issues/19607 https://github.com/flutter/flutter/issues/36894 https://github.com/flutter/flutter/issues/16712 https://github.com/flutter/flutter/issues/9817

Fixed by https://github.com/flutter/plugins/pull/970

**Comment by Sun3** [comment] 2020-01-14 19:17
@Zazo032 I hope it gets merged. I did not see if you can share both text and image together, it looks like it's either share text or share image separately? Can you clarify?

Thanks

**Comment by iapicca** [comment] 2020-01-15 08:48
Hi @Sun3 
as @Zazo032  pointed out 
there are issues already open addressing the case you described.
Please follow up on those issues,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you

**Comment by Sun3** [comment] 2020-01-16 20:39
@iapicca I understand what you are saying, I hope at the end the final result is to be able to share text and images(files) at the same time.

Thanks

**Closed** 2020-01-30 09:51 UTC
