### ISSUE TITLE
Webview_flutter there will be some strange phenomenon when SurfaceAndroidWebView is used, Flutter Page elements disappear or flash

### ISSUE THREAD

**Issue by allan-hx** [flutter/flutter#68295] opened 2020-10-16 10:13 UTC
#### The sample code
This is using a WebView to open up a Web page, and then floating on the WebView a button that has been written with a Flutter on the right
```
import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

void main() {
  WebView.platform = SurfaceAndroidWebView();
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  void show(BuildContext context) {
    final overlayState = Overlay.of(context);
    OverlayEntry overlayEntry;

    overlayEntry = new OverlayEntry(builder: (context) {
      return DefaultTextStyle(
          style: Theme.of(context).textTheme.bodyText1,
          child: Stack(
            children: [
              GestureDetector(
                onTap: () {
                  overlayEntry.remove();
                },
                child: Container(
                  width: double.infinity,
                  height: double.infinity,
                  color: Color.fromRGBO(0, 0, 0, 0.5),
                ),
              ),
              Positioned(
                left: 0,
                right: 0,
                bottom: 0,
                child: Container(
                  color: Colors.white,
                  width: double.infinity,
                  padding: EdgeInsets.all(20),
                  child: Text('This is the content'),
                ),
              ),
            ],
          ));
    });
    overlayState.insert(overlayEntry);
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Stack(
        children: [
          WebView(
            initialUrl: 'https://github.com/',
          ),
          Positioned(
            top: 500,
            right: 0,
            child: MaterialButton(
              color: Colors.blue,
              onPressed: () {
                show(context);
              },
              child: Text(
                'Show',
                style: TextStyle(
                  color: Colors.white,
                ),
              ),
            ),
          )
        ],
      ),
    );
  }
}
```
**Expected results:** 
![微信图片_20201016175933](https://user-images.githubusercontent.com/37947922/96244974-6151c200-0fd9-11eb-9f16-b494819bb92e.jpg)

**Actual results:** 
![微信截图_20201016180025](https://user-images.githubusercontent.com/37947922/96245067-7dedfa00-0fd9-11eb-9743-1811e4a646f4.png)

<details>
[✓] Flutter (Channel stable, 1.22.1, on Microsoft Windows [Version 10.0.18363.1139], locale zh-CN)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
[!] Android Studio (version 3.6)
    ✗ Unable to determine bundled Java version.
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.50.0)
[✓] Connected device (2 available)
</details>

**Comment by darshankawar** [comment] 2020-10-16 10:47
@allan-hx 
Does it occur in debug mode on same phone ? Also, what's the api level of the phone you are seeing this behavior on ?

I tried your sample code on Android 8.1.0 device in debug and release mode, but see the button rendering properly.

**Comment by allan-hx** [comment] 2020-10-16 11:07
@darshankawar 
My mobile phone system is Android 10. It seems that this phenomenon does not appear when debug is on, and it does not appear when release is on. The button has to be clicked for several times to switch, instead of being fixed

**Comment by allan-hx** [comment] 2020-10-16 11:08
@darshankawar 
I tested it on Samsung Android 9.0 and didn't find it

**Comment by darshankawar** [comment] 2020-10-16 11:53
@allan-hx 
It seem to indicate that this could be device-specific issue. Please provide video of the issue when you tap the button several times which then shows the issue.
Thanks.

**Comment by ycv005** [comment] 2020-10-16 13:27
I am too facing similar kind of problem.

Hybrid Compositon is causing AlertDialog to disappear and reappears when touches the screen & after few time later app crash.

I am raising issue here, as it is flutter's issues instead of the plugin. Video - https://photos.app.goo.gl/UjMA5AYGsH2iXnJm7

Here is the link to issue- [Link](https://github.com/pichillilorenzo/flutter_inappwebview/issues/553#issuecomment-709814284).

Thanks

**Comment by allan-hx** [comment] 2020-10-17 10:41
@darshankawar 
[https://photos.app.goo.gl/X3wwuPZtxp2FXETA6](https://photos.app.goo.gl/X3wwuPZtxp2FXETA6)
This is the result of the case code running on the mobile phone. This does not happen every time. Sometimes it only appears after a few clicks.

**Comment by allan-hx** [comment] 2020-10-17 10:44
@darshankawar 
![image](https://user-images.githubusercontent.com/37947922/96335119-a42e9b00-10a8-11eb-984c-80f2be9fd790.png)
When the button is clicked, the position of the button is still wrong, and it also appears in the video

**Comment by darshankawar** [comment] 2020-10-19 06:35
I am unable to replicate the issue on devices I tried (Android Samsung Galaxy A2Core 8.1.0 and Samsung S10+). Hence, keeping this open for further analysis.

[68295.mp4.zip](https://github.com/flutter/flutter/files/5399539/68295.mp4.zip)

**Comment by allan-hx** [comment] 2020-10-19 08:24
@darshankawar 
If possible, you can find a Huawei phone with Android 10 and test it. Not all phones will appear

**Comment by joknjokn** [comment] 2020-11-27 10:36
I have a somehow similar issue. Some widgets in an OverlayEntry-page area invisible in release-versions of the app, apparantly on all devices, including iOS. It seems random which widgets are invisible, but the same everytime, including a TextSpan-widget and the content of a RaisedButton. The page uses some standard animation stuff, but i.e. the RaisedButton is not animated. Not a problem in debug-mode.

I get no error/debugging info (release mode). I have absolutely no idea what the cause is.

**Comment by joknjokn** [comment] 2020-11-27 10:43
After removing all animations, the issue disappeared. I'm not sure how related this is to this issue ticket, but maybe it's a clue. I have no idea why there are no problems in debug, but only in release.

**Comment by nnkti18** [comment] 2020-12-15 10:17
I have an Xiaomi Mi9T and faced the exact same issue on the latest version of Flutter and webview_flutter

**Comment by danagbemava-nc** [comment] 2021-08-11 13:55
Hi, @allan-hx, can you please confirm if you're still experiencing this issue?

**Comment by allan-hx** [comment] 2021-08-15 14:40
> 嗨，@allan-hx，你能确认一下你是否仍然遇到这个问题吗？

因为我们项目还未迁移到最新版，所以不知道最新版是否还存在此问题

**Comment by allan-hx** [comment] 2021-08-16 04:14
> Hi, @allan-hx, can you please confirm if you're still experiencing this issue?

Since our project has not yet been migrated to the latest version, I don’t know if this problem still exists. The old version does exist.

**Comment by danagbemava-nc** [comment] 2021-08-16 10:06
@allan-hx would it be possible for your project to be migrated to the latest version, to confirm if the issue still exits?

**Comment by allan-hx** [comment] 2021-08-17 05:56
> @allan-hx would it be possible for your project to be migrated to the latest version, to confirm if the issue still exits?

I created a demo to test, using the latest version of Flutter and webview plug-ins, did not find this problem, it should be fixed, if there are problems in the follow-up, I will continue to feedback

**Comment by danagbemava-nc** [comment] 2021-08-17 06:01
> > @allan-hx would it be possible for your project to be migrated to the latest version, to confirm if the issue still exits?
> 
> I created a demo to test, using the latest version of Flutter and webview plug-ins, did not find this problem, it should be fixed, if there are problems in the follow-up, I will continue to feedback


Thanks, I will be closing the issue then. If you do experience the issue, kindly leave a comment with your `flutter doctor -v` and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) and I will reopen this issue.

Thank you

**Closed by danagbemava-nc** 2021-08-17 06:01 UTC
Labels: e: device-specific, plugin, p: first party, a: platform-views, p: webview, a: release, P4
