### ISSUE TITLE
I have a problem with my Flutter application that I use flutter_screenutil when I use widget about animation

### ISSUE THREAD

**Issue by progressorTCH** [flutter/flutter#37380] opened 2019-08-01 09:33 UTC
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```

```
```

**Comment by jerald-jacob** [comment] 2019-08-01 09:41
This plugin is still under development, and some APIs might not be available yet.
https://github.com/OpenFlutter/flutter_screenutil

**Comment by BondarenkoStas** [comment] 2019-09-19 22:55
Duplicate of #37381

**Closed by BondarenkoStas** 2019-09-19 22:55 UTC
