### ISSUE TITLE
Widgets not re-render after AppLifeCycleState inactive state

### ISSUE THREAD

**Issue by firstmetcs** [flutter/flutter#119505] opened 2023-01-30 11:07 UTC
On iOS I want to refresh UI in the multi task overview, just like #33236 dose，but it seems not work for me.

My flutter doctor output as follows

➜  ~ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.6, on macOS 12.3 21E230 darwin-arm, locale
    zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.74.3)
[✓] Connected device (2 available)

• No issues found!

**Comment by stevenosse** [comment] 2023-01-30 12:26
Please, can you share a sample code ?

**Comment by danagbemava-nc** [comment] 2023-01-30 13:43
Hi @firstmetcs, you are on an older version of flutter for which support is no longer provided. 

Kindly upgrade to the latest version of flutter stable (3.7.0) and try again. This issue has already been fixed by https://github.com/flutter/engine/pull/25196 which is available in version 2.2.0 upwards. 

If you do face this issue on the latest version of flutter stable kindly provide the updated output of `flutter doctor -v` along with a complete minimal reproducible code sample. 

Android is being tracked in https://github.com/flutter/flutter/issues/80369. 

Closing this since the issue has already been fixed for iOS. 

Thank you

**Closed by danagbemava-nc** 2023-01-30 13:43 UTC
Labels: in triage
