### ISSUE TITLE
Window10 Visual Studio2017 bug

### ISSUE THREAD

**Issue by wind-cludy** [flutter/flutter#103577] opened 2022-05-12 06:54 UTC
hi, when I'm run "flutter doctor -v" on widows10 then some error is output.

      flutter doctor -v
[√] Flutter (Channel stable, 3.0.0, on Microsoft Windows [Version 10.0.19044.1706], locale
    ja-JP)
    • Flutter version 3.0.0 at C:\PRJ\2021\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ee4e09cce0 (2 days ago), 2022-05-09 16:45:18 -0700
    • Engine revision d1b9a6938a
    • Dart version 2.17.0
    • DevTools version 2.12.2

[X] Android toolchain - develop for Android devices
    X Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for        
      detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[☠] Visual Studio - develop for Windows (the doctor check crashed)
    X Due to an error, the doctor check did not complete. If the error message below is not
      helpful, please let us know about this issue at
      https://github.com/flutter/flutter/issues.
    X Exception: Bad UTF-8 encoding (U+FFFD; REPLACEMENT CHARACTER) found while decoding      
      string: [
        {
          "instanceId": "8383bd7c",
          "installDate": "2022-05-12T06:35:59Z",
          "installationName": "VisualStudio/15.9.48+28307.1974",
          "installationPath": "C:\\Program Files (x86)\\Microsoft Visual
          Studio\\2017\\Community",
          "installationVersion": "15.9.28307.1974",
          "productId": "Microsoft.VisualStudio.Product.Community",
          "productPath": "C:\\Program Files (x86)\\Microsoft Visual
          Studio\\2017\\Community\\Common7\\IDE\\devenv.exe",
          "state": 4294967295,
          "isComplete": true,
          "isLaunchable": true,
          "isPrerelease": false,
          "isRebootRequired": false,
          "displayName": "Visual Studio Community 2017",
          "description": "�w���A�I�[�v�� �\�[�X�A����ьX�̊J���҂̂��߂̖����Ŋ��S�ȋ@�\������� IDE",
          "channelId": "VisualStudio.15.Release",
          "channelUri": "https://aka.ms/vs/15/release/channel",
          "enginePath": "C:\\Program Files (x86)\\Microsoft Visual
          Studio\\Installer\\resources\\app\\ServiceHub\\Services\\Microsoft.VisualStudio.Setu          p.Service",
          "installedChannelUri": "https://aka.ms/vs/15/release/channel",
          "releaseNotes": "https://go.microsoft.com/fwlink/?LinkId=660692#15.9.48",
          "thirdPartyNotices": "https://go.microsoft.com/fwlink/?LinkId=660708",
          "updateDate": "2022-05-12T06:35:59.2387533Z",
          "catalog": {
            "buildBranch": "d15.9",
            "buildVersion": "15.9.28307.1974",
            "id": "VisualStudio/15.9.48+28307.1974",
            "localBuild": "build-lab",
            "manifestName": "VisualStudio",
            "manifestType": "installer",
            "productDisplayVersion": "15.9.48",
            "productLine": "Dev15",
            "productLineVersion": "2017",
            "productMilestone": "RTW",
            "productMilestoneIsPreRelease": "False",
            "productName": "Visual Studio",
            "productPatchVersion": "48",
            "productPreReleaseMilestoneSuffix": "1.0",
            "productRelease": "RTW",
            "productSemanticVersion": "15.9.48+28307.1974",
            "requiredEngineVersion": "1.18.1063.29791"
          },
          "properties": {
            "campaignId": "2030:423e43b9-4bf4-4c65-a44f-84e5c5c695d8",
            "channelManifestId": "VisualStudio.15.Release/15.9.48+28307.1974",
            "nickname": "",
            "setupEngineFilePath": "C:\\Program Files (x86)\\Microsoft Visual
            Studio\\Installer\\setup.exe"
          }
        }
      ]
      . The Flutter team would greatly appreciate if you could file a bug explaining exactly  
      what you were doing when this happened:
      https://github.com/flutter/flutter/issues/new/choose
      The source bytes were:
      [91, 13, 10, 32, 32, 123, 13, 10, 32, 32, 32, 32, 34, 105, 110, 115, 116, 97, 110, 99,
      101, 73, 100, 34, 58, 32, 34, 56, 51, 56, 51, 98, 100, 55, 99, 34, 44, 13, 10, 32, 32,  
      32, 32, 34, 105, 110, 115, 116, 97, 108, 108, 68, 97, 116, 101, 34, 58, 32, 34, 50, 48, 
      50, 50, 45, 48, 53, 45, 49, 50, 84, 48, 54, 58, 51, 53, 58, 53, 57, 90, 34, 44, 13, 10, 
      32, 32, 32, 32, 34, 105, 110, 115, 116, 97, 108, 108, 97, 116, 105, 111, 110, 78, 97,   
      109, 101, 34, 58, 32, 34, 86, 105, 115, 117, 97, 108, 83, 116, 117, 100, 105, 111, 47,  
      49, 53, 46, 57, 46, 52, 56, 43, 50, 56, 51, 48, 55, 46, 49, 57, 55, 52, 34, 44, 13, 10, 
      32, 32, 32, 32, 34, 105, 110, 115, 116, 97, 108, 108, 97, 116, 105, 111, 110, 80, 97,   
      116, 104, 34, 58, 32, 34, 67, 58, 92, 92, 80, 114, 111, 103, 114, 97, 109, 32, 70, 105, 
      108, 101, 115, 32, 40, 120, 56, 54, 41, 92, 92, 77, 105, 99, 114, 111, 115, 111, 102,   
      116, 32, 86, 105, 115, 117, 97, 108, 32, 83, 116, 117, 100, 105, 111, 92, 92, 50, 48,   
      49, 55, 92, 92, 67, 111, 109, 109, 117, 110, 105, 116, 121, 34, 44, 13, 10, 32, 32, 32, 
      32, 34, 105, 110, 115, 116, 97, 108, 108, 97, 116, 105, 111, 110, 86, 101, 114, 115,    
      105, 111, 110, 34, 58, 32, 34, 49, 53, 46, 57, 46, 50, 56, 51, 48, 55, 46, 49, 57, 55,  
      52, 34, 44, 13, 10, 32, 32, 32, 32, 34, 112, 114, 111, 100, 117, 99, 116, 73, 100, 34,  
      58, 32, 34, 77, 105, 99, 114, 111, 115, 111, 102, 116, 46, 86, 105, 115, 117, 97, 108,  
      83, 116, 117, 100, 105, 111, 46, 80, 114, 111, 100, 117, 99, 116, 46, 67, 111, 109, 109,      117, 110, 105, 116, 121, 34, 44, 13, 10, 32, 32, 32, 32, 34, 112, 114, 111, 100, 117,   
      99, 116, 80, 97, 116, 104, 34, 58, 32, 34, 67, 58, 92, 92, 80, 114, 111, 103, 114, 97,  
      109, 32, 70, 105, 108, 101, 115, 32, 40, 120, 56, 54, 41, 92, 92, 77, 105, 99, 114, 111,      115, 111, 102, 116, 32, 86, 105, 115, 117, 97, 108, 32, 83, 116, 117, 100, 105, 111, 92,      92, 50, 48, 49, 55, 92, 92, 67, 111, 109, 109, 117, 110, 105, 116, 121, 92, 92, 67, 111,      109, 109, 111, 110, 55, 92, 92, 73, 68, 69, 92, 92, 100, 101, 118, 101, 110, 118, 46,   
      101, 120, 101, 34, 44, 13, 10, 32, 32, 32, 32, 34, 115, 116, 97, 116, 101, 34, 58, 32,  
      52, 50, 57, 52, 57, 54, 55, 50, 57, 53, 44, 13, 10, 32, 32, 32, 32, 34, 105, 115, 67,   
      111, 109, 112, 108, 101, 116, 101, 34, 58, 32, 116, 114, 117, 101, 44, 13, 10, 32, 32,  
      32, 32, 34, 105, 115, 76, 97, 117, 110, 99, 104, 97, 98, 108, 101, 34, 58, 32, 116, 114,      117, 101, 44, 13, 10, 32, 32, 32, 32, 34, 105, 115, 80, 114, 101, 114, 101, 108, 101,   
      97, 115, 101, 34, 58, 32, 102, 97, 108, 115, 101, 44, 13, 10, 32, 32, 32, 32, 34, 105,  
      115, 82, 101, 98, 111, 111, 116, 82, 101, 113, 117, 105, 114, 101, 100, 34, 58, 32, 102,      97, 108, 115, 101, 44, 13, 10, 32, 32, 32, 32, 34, 100, 105, 115, 112, 108, 97, 121, 78,      97, 109, 101, 34, 58, 32, 34, 86, 105, 115, 117, 97, 108, 32, 83, 116, 117, 100, 105,   
      111, 32, 67, 111, 109, 109, 117, 110, 105, 116, 121, 32, 50, 48, 49, 55, 34, 44, 13, 10,      32, 32, 32, 32, 34, 100, 101, 115, 99, 114, 105, 112, 116, 105, 111, 110, 34, 58, 32,   
      34, 138, 119, 144, 182, 129, 65, 131, 73, 129, 91, 131, 118, 131, 147, 32, 131, 92, 129,      91, 131, 88, 129, 65, 130, 168, 130, 230, 130, 209, 140, 194, 129, 88, 130, 204, 138,   
      74, 148, 173, 142, 210, 130, 204, 130, 189, 130, 223, 130, 204, 150, 179, 151, 191, 130,      197, 138, 174, 145, 83, 130, 200, 139, 64, 148, 92, 130, 240, 148, 245, 130, 166, 130,  
      189, 32, 73, 68, 69, 34, 44, 13, 10, 32, 32, 32, 32, 34, 99, 104, 97, 110, 110, 101,    
      108, 73, 100, 34, 58, 32, 34, 86, 105, 115, 117, 97, 108, 83, 116, 117, 100, 105, 111,  
      46, 49, 53, 46, 82, 101, 108, 101, 97, 115, 101, 34, 44, 13, 10, 32, 32, 32, 32, 34, 99,      104, 97, 110, 110, 101, 108, 85, 114, 105, 34, 58, 32, 34, 104, 116, 116, 112, 115, 58, 
      47, 47, 97, 107, 97, 46, 109, 115, 47, 118, 115, 47, 49, 53, 47, 114, 101, 108, 101, 97,      115, 101, 47, 99, 104, 97, 110, 110, 101, 108, 34, 44, 13, 10, 32, 32, 32, 32, 34, 101, 
      110, 103, 105, 110, 101, 80, 97, 116, 104, 34, 58, 32, 34, 67, 58, 92, 92, 80, 114, 111,      103, 114, 97, 109, 32, 70, 105, 108, 101, 115, 32, 40, 120, 56, 54, 41, 92, 92, 77, 105,      99, 114, 111, 115, 111, 102, 116, 32, 86, 105, 115, 117, 97, 108, 32, 83, 116, 117, 100,      105, 111, 92, 92, 73, 110, 115, 116, 97, 108, 108, 101, 114, 92, 92, 114, 101, 115, 111,      117, 114, 99, 101, 115, 92, 92, 97, 112, 112, 92, 92, 83, 101, 114, 118, 105, 99, 101,  
      72, 117, 98, 92, 92, 83, 101, 114, 118, 105, 99, 101, 115, 92, 92, 77, 105, 99, 114,    
      111, 115, 111, 102, 116, 46, 86, 105, 115, 117, 97, 108, 83, 116, 117, 100, 105, 111,   
      46, 83, 101, 116, 117, 112, 46, 83, 101, 114, 118, 105, 99, 101, 34, 44, 13, 10, 32, 32,      32, 32, 34, 105, 110, 115, 116, 97, 108, 108, 101, 100, 67, 104, 97, 110, 110, 101, 108,      85, 114, 105, 34, 58, 32, 34, 104, 116, 116, 112, 115, 58, 47, 47, 97, 107, 97, 46, 109,      115, 47, 118, 115, 47, 49, 53, 47, 114, 101, 108, 101, 97, 115, 101, 47, 99, 104, 97,   
      110, 110, 101, 108, 34, 44, 13, 10, 32, 32, 32, 32, 34, 114, 101, 108, 101, 97, 115,    
      101, 78, 111, 116, 101, 115, 34, 58, 32, 34, 104, 116, 116, 112, 115, 58, 47, 47, 103,  
      111, 46, 109, 105, 99, 114, 111, 115, 111, 102, 116, 46, 99, 111, 109, 47, 102, 119,    
      108, 105, 110, 107, 47, 63, 76, 105, 110, 107, 73, 100, 61, 54, 54, 48, 54, 57, 50, 35, 
      49, 53, 46, 57, 46, 52, 56, 34, 44, 13, 10, 32, 32, 32, 32, 34, 116, 104, 105, 114, 100,      80, 97, 114, 116, 121, 78, 111, 116, 105, 99, 101, 115, 34, 58, 32, 34, 104, 116, 116,  
      112, 115, 58, 47, 47, 103, 111, 46, 109, 105, 99, 114, 111, 115, 111, 102, 116, 46, 99, 
      111, 109, 47, 102, 119, 108, 105, 110, 107, 47, 63, 76, 105, 110, 107, 73, 100, 61, 54, 
      54, 48, 55, 48, 56, 34, 44, 13, 10, 32, 32, 32, 32, 34, 117, 112, 100, 97, 116, 101, 68,      97, 116, 101, 34, 58, 32, 34, 50, 48, 50, 50, 45, 48, 53, 45, 49, 50, 84, 48, 54, 58,   
      51, 53, 58, 53, 57, 46, 50, 51, 56, 55, 53, 51, 51, 90, 34, 44, 13, 10, 32, 32, 32, 32, 
      34, 99, 97, 116, 97, 108, 111, 103, 34, 58, 32, 123, 13, 10, 32, 32, 32, 32, 32, 32, 34,      98, 117, 105, 108, 100, 66, 114, 97, 110, 99, 104, 34, 58, 32, 34, 100, 49, 53, 46, 57, 
      34, 44, 13, 10, 32, 32, 32, 32, 32, 32, 34, 98, 117, 105, 108, 100, 86, 101, 114, 115,  
      105, 111, 110, 34, 58, 32, 34, 49, 53, 46, 57, 46, 50, 56, 51, 48, 55, 46, 49, 57, 55,  
      52, 34, 44, 13, 10, 32, 32, 32, 32, 32, 32, 34, 105, 100, 34, 58, 32, 34, 86, 105, 115, 
      117, 97, 108, 83, 116, 117, 100, 105, 111, 47, 49, 53, 46, 57, 46, 52, 56, 43, 50, 56,  
      51, 48, 55, 46, 49, 57, 55, 52, 34, 44, 13, 10, 32, 32, 32, 32, 32, 32, 34, 108, 111,   
      99, 97, 108, 66, 117, 105, 108, 100, 34, 58, 32, 34, 98, 117, 105, 108, 100, 45, 108,   
      97, 98, 34, 44, 13, 10, 32, 32, 32, 32, 32, 32, 34, 109, 97, 110, 105, 102, 101, 115,   
      116, 78, 97, 109, 101, 34, 58, 32, 34, 86, 105, 115, 117, 97, 108, 83, 116, 117, 100,   
      105, 111, 34, 44, 13, 10, 32, 32, 32, 32, 32, 32, 34, 109, 97, 110, 105, 102, 101, 115, 
      116, 84, 121, 112, 101, 34, 58, 32, 34, 105, 110, 115, 116, 97, 108, 108, 101, 114, 34, 
      44, 13, 10, 32, 32, 32, 32, 32, 32, 34, 112, 114, 111, 100, 117, 99, 116, 68, 105, 115, 
      112, 108, 97, 121, 86, 101, 114, 115, 105, 111, 110, 34, 58, 32, 34, 49, 53, 46, 57, 46,      52, 56, 34, 44, 13, 10, 32, 32, 32, 32, 32, 32, 34, 112, 114, 111, 100, 117, 99, 116,   
      76, 105, 110, 101, 34, 58, 32, 34, 68, 101, 118, 49, 53, 34, 44, 13, 10, 32, 32, 32, 32,      32, 32, 34, 112, 114, 111, 100, 117, 99, 116, 76, 105, 110, 101, 86, 101, 114, 115, 105,      111, 110, 34, 58, 32, 34, 50, 48, 49, 55, 34, 44, 13, 10, 32, 32, 32, 32, 32, 32, 34,   
      112, 114, 111, 100, 117, 99, 116, 77, 105, 108, 101, 115, 116, 111, 110, 101, 34, 58,   
      32, 34, 82, 84, 87, 34, 44, 13, 10, 32, 32, 32, 32, 32, 32, 34, 112, 114, 111, 100, 117,      99, 116, 77, 105, 108, 101, 115, 116, 111, 110, 101, 73, 115, 80, 114, 101, 82, 101,    
      108, 101, 97, 115, 101, 34, 58, 32, 34, 70, 97, 108, 115, 101, 34, 44, 13, 10, 32, 32,  
      32, 32, 32, 32, 34, 112, 114, 111, 100, 117, 99, 116, 78, 97, 109, 101, 34, 58, 32, 34, 
      86, 105, 115, 117, 97, 108, 32, 83, 116, 117, 100, 105, 111, 34, 44, 13, 10, 32, 32, 32,      32, 32, 32, 34, 112, 114, 111, 100, 117, 99, 116, 80, 97, 116, 99, 104, 86, 101, 114,   
      115, 105, 111, 110, 34, 58, 32, 34, 52, 56, 34, 44, 13, 10, 32, 32, 32, 32, 32, 32, 34, 
      112, 114, 111, 100, 117, 99, 116, 80, 114, 101, 82, 101, 108, 101, 97, 115, 101, 77,    
      105, 108, 101, 115, 116, 111, 110, 101, 83, 117, 102, 102, 105, 120, 34, 58, 32, 34, 49,      46, 48, 34, 44, 13, 10, 32, 32, 32, 32, 32, 32, 34, 112, 114, 111, 100, 117, 99, 116,   
      82, 101, 108, 101, 97, 115, 101, 34, 58, 32, 34, 82, 84, 87, 34, 44, 13, 10, 32, 32, 32,      32, 32, 32, 34, 112, 114, 111, 100, 117, 99, 116, 83, 101, 109, 97, 110, 116, 105, 99,  
      86, 101, 114, 115, 105, 111, 110, 34, 58, 32, 34, 49, 53, 46, 57, 46, 52, 56, 43, 50,   
      56, 51, 48, 55, 46, 49, 57, 55, 52, 34, 44, 13, 10, 32, 32, 32, 32, 32, 32, 34, 114,    
      101, 113, 117, 105, 114, 101, 100, 69, 110, 103, 105, 110, 101, 86, 101, 114, 115, 105, 
      111, 110, 34, 58, 32, 34, 49, 46, 49, 56, 46, 49, 48, 54, 51, 46, 50, 57, 55, 57, 49,   
      34, 13, 10, 32, 32, 32, 32, 125, 44, 13, 10, 32, 32, 32, 32, 34, 112, 114, 111, 112,    
      101, 114, 116, 105, 101, 115, 34, 58, 32, 123, 13, 10, 32, 32, 32, 32, 32, 32, 34, 99,  
      97, 109, 112, 97, 105, 103, 110, 73, 100, 34, 58, 32, 34, 50, 48, 51, 48, 58, 52, 50,   
      51, 101, 52, 51, 98, 57, 45, 52, 98, 102, 52, 45, 52, 99, 54, 53, 45, 97, 52, 52, 102,  
      45, 56, 52, 101, 53, 99, 53, 99, 54, 57, 53, 100, 56, 34, 44, 13, 10, 32, 32, 32, 32,   
      32, 32, 34, 99, 104, 97, 110, 110, 101, 108, 77, 97, 110, 105, 102, 101, 115, 116, 73,  
      100, 34, 58, 32, 34, 86, 105, 115, 117, 97, 108, 83, 116, 117, 100, 105, 111, 46, 49,   
      53, 46, 82, 101, 108, 101, 97, 115, 101, 47, 49, 53, 46, 57, 46, 52, 56, 43, 50, 56, 51,      48, 55, 46, 49, 57, 55, 52, 34, 44, 13, 10, 32, 32, 32, 32, 32, 32, 34, 110, 105, 99,   
      107, 110, 97, 109, 101, 34, 58, 32, 34, 34, 44, 13, 10, 32, 32, 32, 32, 32, 32, 34, 115,      101, 116, 117, 112, 69, 110, 103, 105, 110, 101, 70, 105, 108, 101, 80, 97, 116, 104,   
      34, 58, 32, 34, 67, 58, 92, 92, 80, 114, 111, 103, 114, 97, 109, 32, 70, 105, 108, 101, 
      115, 32, 40, 120, 56, 54, 41, 92, 92, 77, 105, 99, 114, 111, 115, 111, 102, 116, 32, 86,      105, 115, 117, 97, 108, 32, 83, 116, 117, 100, 105, 111, 92, 92, 73, 110, 115, 116, 97, 
      108, 108, 101, 114, 92, 92, 115, 101, 116, 117, 112, 46, 101, 120, 101, 34, 13, 10, 32, 
      32, 32, 32, 125, 13, 10, 32, 32, 125, 13, 10, 93, 13, 10]

    • #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
      #1      Utf8Decoder.convert (package:flutter_tools/src/convert.dart:54:7)
      #2      Codec.decode (dart:convert/codec.dart:26:34)
      #3      _ProcessImpl._runAndWait.getOutput (dart:io-patch/process_patch.dart:498:23)    
      #4      _ProcessImpl._runAndWait (dart:io-patch/process_patch.dart:506:9)
      #5      _runNonInteractiveProcessSync (dart:io-patch/process_patch.dart:632:18)
      #6      Process.runSync (dart:io-patch/process_patch.dart:68:12)
      #7      LocalProcessManager.runSync
      (package:process/src/interface/local_process_manager.dart:103:22)
      #8      ErrorHandlingProcessManager.runSync.<anonymous closure>
      (package:flutter_tools/src/base/error_handling_io.dart:712:24)
      #9      _runSync (package:flutter_tools/src/base/error_handling_io.dart:597:14)
      #10     ErrorHandlingProcessManager.runSync
      (package:flutter_tools/src/base/error_handling_io.dart:711:12)
      #11     _DefaultProcessUtils.runSync
      (package:flutter_tools/src/base/process.dart:373:51)
      #12     VisualStudio._visualStudioDetails
      (package:flutter_tools/src/windows/visual_studio.dart:314:51)
      #13     VisualStudio._anyVisualStudioDetails
      (package:flutter_tools/src/windows/visual_studio.dart:403:39)
      #14     VisualStudio._bestVisualStudioDetails
      (package:flutter_tools/src/windows/visual_studio.dart:419:12)
      #15     VisualStudio.isInstalled
      (package:flutter_tools/src/windows/visual_studio.dart:36:27)
      #16     VisualStudioValidator.validate
      (package:flutter_tools/src/windows/visual_studio_validator.dart:29:23)
      #17     Doctor.startValidatorTasks.<anonymous closure>
      (package:flutter_tools/src/doctor.dart:216:72)
      #18     asyncGuard.<anonymous closure>
      (package:flutter_tools/src/base/async_guard.dart:111:32)
      #19     asyncGuard.<anonymous closure>
      (package:flutter_tools/src/base/async_guard.dart:109:18)
      #20     _rootRun (dart:async/zone.dart:1426:13)
      #21     _CustomZone.run (dart:async/zone.dart:1328:19)
      #22     _runZoned (dart:async/zone.dart:1861:10)
      #23     runZonedGuarded (dart:async/zone.dart:1849:12)
      #24     runZoned (dart:async/zone.dart:1780:12)
      #25     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #26     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:208:9)        
      #27     Doctor.diagnose (package:flutter_tools/src/doctor.dart:339:72)
      #28     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:50:48) 
      #29     FlutterCommand.verifyThenRunCommand
      (package:flutter_tools/src/runner/flutter_command.dart:1342:12)
      <asynchronous suspension>
      #30     FlutterCommand.run.<anonymous closure>
      (package:flutter_tools/src/runner/flutter_command.dart:1183:27)
      <asynchronous suspension>
      #31     AppContext.run.<anonymous closure>
      (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #32     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
      <asynchronous suspension>
      #33     FlutterCommandRunner.runCommand.<anonymous closure>
      (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
      <asynchronous suspension>
      #34     AppContext.run.<anonymous closure>
      (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #35     FlutterCommandRunner.runCommand
      (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
      <asynchronous suspension>
      #36     run.<anonymous closure>.<anonymous closure>
      (package:flutter_tools/runner.dart:62:9)
      <asynchronous suspension>
      #37     AppContext.run.<anonymous closure>
      (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #38     main (package:flutter_tools/executable.dart:94:3)
      <asynchronous suspension>

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 44.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code, 64-bit edition (version 1.66.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version
      10.0.19044.1706]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 101.0.4951.54
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 101.0.1210.39

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.

**Comment by darshankawar** [comment] 2022-05-12 09:32
Closing this as duplicate of https://github.com/flutter/flutter/issues/102451

**Closed by darshankawar** 2022-05-12 09:32 UTC
Labels: in triage
