### ISSUE TITLE
When CustomPainter needs to paint many complex paths in each frame, performance gets degraded when zooming or panning the CustomPaint widget

### ISSUE THREAD

**Issue by whiplashoo** [flutter/flutter#72066] opened 2020-12-10 13:12 UTC
Please tell us exactly how to reproduce the problem you are running into:

- Create a CustomPaint object.
- Paint on it a number of complex paths. In my case, I parse an SVG file of a map of Germany and extract the path (`d`) attribute. 
- Make the CustomPaint widget zoomable and pannable. I opted to use the [MatrixGestureDetector](https://pub.dev/packages/matrix_gesture_detector) package, which exposes a Matrix4 object to transform the canvas when the user zooms or pans the map. I also faced the same issues when wrapping the CustomPaint with an InteractiveViewer widget though.
- Try to move around or zoom the map. I mostly get around 10-20 fps when panning and <10 fps when zooming.

**Drawing these paths continuously when the transformation matrix changes seems to take too long in the raster thread.** This makes the whole zooming and moving around process really laggy. Issue is more apparent in Android devices (emulator and physical); when I run on iPhone devices refresh is a lot faster.

**Alternative routes I tried:**
- Using InteractiveViewer widget instead of transforming the canvas with a matrix yielded similar results.
- Transforming each path individually (`path.transform(notifier.value.storage)`), instead of transforming the whole canvas (`canvas.transform(notifier.value.storage)`) worsened the performance.
- Using single values (i.e. `scale`, `offsetX`, `offsetY`) to apply the transforms instead of a matrix: similar results.

**Optimizations I implemented in the demo:**
- Using a `ValueNotifier` instead of `setState` to update the transformation matrix.
- Before drawing a path, check if it is off-screen (out of the viewport). This didn't have any effect as far as I can see; probably the CustomPaint function already takes this into account before drawing.
- Optimized the SVG with svgo. 
- Wrapped CustomPaint with a RepaintBoundary.
- Set `isComplex: true` and `willChange: true` for the CustomPaint widget. 

Wondering if there is any kind of optimization I could apply for this? Or an alternative way to implement fast zooming and panning for a CustomPaint with complex paths like this map?

[Demo to reproduce](https://gist.github.com/whiplashoo/e22c3e1401944bc74da9b70cd28a09e1)
In the gist I have also attached my pubspec.yaml and the sample SVG file.

[Video on master channel/profile/skia tracing enabled](https://streamable.com/01ot8c)

**Target Platform/Devices:**
Android mostly, iOS devices seem to perform a lot better.

## Logs

```
[√] Flutter (Channel master, 1.25.0-5.0.pre.141, on Microsoft Windows [Version 10.0.18363.1198], locale el-GR)
    • Flutter version 1.25.0-5.0.pre.141 at C:\src\flutter
    • Framework revision 36bed2b4c3 (12 hours ago), 2020-12-09 20:13:04 -0500
    • Engine revision 8518a5bbe6
    • Dart version 2.12.0 (build 2.12.0-135.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\whipl\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:/Program Files/Android/Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Android Studio
    • Android Studio at C:/Program Files/Android/Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = C:/Program Files/Android/Android Studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (3 available)
    • STF L09 (mobile) • 7BK0218122001115 • android-arm64  • Android 9 (API 28)
    • Chrome (web)     • chrome           • web-javascript • Google Chrome 87.0.4280.88
    • Edge (web)       • edge             • web-javascript • Microsoft Edge 87.0.664.57

```

**Comment by pedromassangocode** [comment] 2020-12-11 10:42
Hi @whiplashoo 
Can you please provide a code that does not uses any third-party package?
Thank you

**Comment by whiplashoo** [comment] 2020-12-11 11:20
Hi @pedromassangocode 

You would need all other packages stripped out?

Here is [an updated gist](https://gist.github.com/whiplashoo/bc40e303f200bc65b12b8bc64e314d1f) without the [matrix_gesture_detector](https://pub.dev/packages/matrix_gesture_detector) package. It uses a default `GestureDetector` that updates the transformation matrix when the user zooms or pans (i.e. `onScaleUpdate`). 

There is only one external dependency that I am not able to strip from the demo and it is the path parser from the [path_drawing](https://pub.dev/packages/path_drawing) package. It is used in the SVG parser and essentially converts the path data property from the SVG to Dart instructions for making a Path object e.g.:

`parseSvgPathData("M 0.092045,0.1 H 160.7516 V 123.98077 H 0.092045 Z")  //The d property of an SVG <path> `

converts to:

```
path = Path();
path.lineTo(0, 0);
path.cubicTo(0, 0, size.width, 0, size.width, 0);
path.cubicTo(size.width, 0, size.width, size.height, size.width, size.height);
path.cubicTo(size.width, size.height, 0, size.height, 0, size.height);
path.cubicTo(0, size.height, 0, 0, 0, 0);
```

This function is however called only when initializing the app route, to parse the SVG and extract the path instructions to draw it on the canvas; it doesn't affect the performance issue at hand.

**Comment by pedromassangocode** [comment] 2020-12-14 07:53
<details><summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.25.0-9.0.pre.43, on Mac OS X 10.15.7 19H2 darwin-x64, locale en)
    • Flutter version 1.25.0-9.0.pre.43 at /Users/pedromassango/dev/SDKs/flutter_master
    • Framework revision 63062a6443 (17 hours ago), 2020-12-13 23:19:13 +0800
    • Engine revision 4797b06652
    • Dart version 2.12.0 (build 2.12.0-141.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 52.0.5
    • Dart plugin version 203.5981.152

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (4 available)
    • Redmi 5 Plus (mobile)       • 0258ff700005  • android-arm64  • Android 8.1.0 (API 27)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • macOS (desktop)             • macos         • darwin-x64     • Mac OS X 10.15.7 19H2 darwin-x64
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 87.0.4280.88

• No issues found!
Process finished with exit code 0
```
</details>

**Comment by RomanJos** [comment] 2020-12-19 17:35
Hello, I did exactly the same things and my customPainter was constantly rebuilding when zooming and panning so I wrapped it inside a RepaintBoundary and its not rebuilding anymore.

If this work then we may need to implement it directly inside InteractiveViewer but I don't have much experience with it so idk

**Comment by whiplashoo** [comment] 2021-02-18 11:20
#72718 is probably related to this.

**Comment by whiplashoo** [comment] 2021-03-20 19:58
Similar example of this issue with a video in #78543.

**Comment by whiplashoo** [comment] 2021-05-08 18:05
I finally found a workaround for this issue:

It seems that the `drawCanvas()` call to draw each path on the canvas is by far the most expensive process. We can optimize this call by **batching (grouping) all the path objects into one path and drawing that on the canvas**. In our case we need to draw two batch paths, one for the fill and one for the stroke of the sub-paths.

So, instead of:

```
  void paint(Canvas canvas, Size size) {
    int n = 0;
    canvas.transform(notifier.value.storage);
    paths.forEach((path) {
      // Check if path is not inside canvas viewport to skip drawing it.
      final Path transformedPath = path.transform(notifier.value.storage);
      final Rect boundsRect = transformedPath.getBounds();
      final bool isOutsideViewport =
          boundsRect.left > size.width || boundsRect.right < 0 || boundsRect.top > size.height || boundsRect.bottom < 0;

      if (!isOutsideViewport) {
        n++;
        _paint
          ..style = PaintingStyle.fill
          ..color = Color(0xffd1dbee);
        canvas.drawPath(path, _paint);
        _paint
          ..style = PaintingStyle.stroke
          ..color = Colors.black
          ..strokeWidth = 0.5;
        canvas.drawPath(path, _paint);
      }
    });
    print("PAINTED: $n paths");
  }
```

we should do:

```
void paint(Canvas canvas, Size size) {
    int n = 0;
    var batchPathsForFill = Path();
    var batchPathsForStroke = Path();
    paths.forEach((path) {
      // Check if path is not inside canvas viewport to skip drawing it.
      final Path transformedPath = path.transform(notifier.value.storage);
      final Rect boundsRect = transformedPath.getBounds();
      final bool isOutsideViewport =
          boundsRect.left > size.width || boundsRect.right < 0 || boundsRect.top > size.height || boundsRect.bottom < 0;

      if (!isOutsideViewport) {
        n++;
       //Add it to the batch paths.
        batchPathsForFill.addPath(transformedPath, Offset.zero);
        batchPathsForStroke.addPath(transformedPath, Offset.zero);
      }
    });
    _paint
      ..style = PaintingStyle.fill
      ..color = Color(0xffd1dbee);
    // Draw the fill of all paths to the canvas
    canvas.drawPath(batchPathsForFill, _paint);
    _paint
      ..style = PaintingStyle.stroke
      ..color = Colors.black
      ..strokeWidth = 0.5;
    // Draw the stroke of all paths to the canvas
    canvas.drawPath(batchPathsForStroke, _paint);
    print("PAINTED: $n paths");
  }
```

This way, instead of having to draw 400+ different paths, we group and perform just two draws on the canvas. In my use-case, it made a huge difference. Lag is mostly gone from all maps that I use this functionality and FPS has been increased, although it still doesn't reach 60 fps on larger files.

Caveats:

- Obviously, if the paths have different fill or stroke colors, you need to use more batch paths, one for each different color, and paint these separately. Again, you would need to have more colors than the total number of paths, for this to be not an optimization of the drawing process.
- When you add a path to its parent (batch) path with addPath(), it performs a union of the added path with the ones already inserted. This means that if a path is on top of another one, and you add them to the same path, you get a "hole" inside the batch path. Essentially, no paths should be on top of one another, their borders should be distinct.

**I consider this a workaround, as I still don't know why there is such a huge difference for the original setup between the Android and iOS devices**. As I said, even older iPhones didn't have an issue even with drawing over 3,000 different paths on the canvas. On the other side, I have seen lag on high-end Androids and even crashes on lower-end ones. 

Could it be that the implementation of drawPath() is different for Android vs iOS? Is it just an issue of raw computing power for iOS devices?

**Comment by Piinks** [comment] 2022-06-16 23:07
This looks like a duplicate of https://github.com/flutter/flutter/issues/78543. To focus conversation and work to resolve the issue, I am going to close this. Please follow up there. A lot of discussion has already occurred with potential solutions.

If you feel this is a separate issue, let us know and we'll take another look! Thanks!

**Closed by Piinks** 2022-06-16 23:07 UTC
Labels: framework, severe: performance, severe: rendering, has reproducible steps, found in release: 1.25
