### ISSUE TITLE
'package:flutter/src/rendering/box.dart': Failed assertion: line 1604 pos 12: I/flutter ( 4813): '!_debugDoingBaseline': is not true.

### ISSUE THREAD

**Issue by KittyTiger7** [flutter/flutter#19131] opened 2018-07-07 06:13 UTC
```dart
import 'dart:async';
import 'dart:io';
import 'package:flutter/material.dart';
import 'package:path_provider/path_provider.dart';


/*
reading and writing data from a file is showcased in the following steps:
  steps 1-4: the foundation for saving/reading data to/from txt files

*/


void main() async {

  var data = await readData();
  if (data != null) {
    String message = await readData();
    print(message);
  }

    runApp(new MaterialApp(
      title: "IO",
      home: new Home(),
    ));
  }





class Home extends StatefulWidget {
  @override
  _HomeState createState() => _HomeState();
}



class _HomeState extends State<Home> {

  var _enterDataField = new TextEditingController();

  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: new AppBar(
        title: new Text("Read/Write"),
        centerTitle: true,
        backgroundColor: Colors.greenAccent,
      ),

      body: new Container(
        padding: const EdgeInsets.all(13.0),
        alignment: Alignment.topCenter,
        child: new ListTile(
          title: new TextField(
            controller: _enterDataField,
            decoration: new InputDecoration(
                labelText: 'Write Something here'
            ),
          ),
          subtitle: new FlatButton(
              onPressed: () {
                if (_enterDataField.text.isNotEmpty)
                  writeData(_enterDataField.text);
              },
              child: new Column(
                children: <Widget>[
                  new Text('Save Data'),
                  new Padding(padding: new EdgeInsets.all(14.0)),
                  new Text('Saved data goes here')
                ],
              )),
        ),
      ),
    );
  }
}





  // 1st step:
  // this gets the path to local directory
  Future<String> get _localPath async {

    final directory = await getApplicationDocumentsDirectory();
    return directory.path;
  }


  // 2nd step:
  // this is to create a file
  Future<File> get _localFile async {

    final path = await _localPath;
    // the name is what's after $path/
    return new File('$path/data.txt');
  }


  // 3rd step:
  // write data to file
  Future<File> writeData(String message) async {
     final file = await _localFile;
     //write to file
     return file.writeAsString('$message');
  }


  // 4th step:
  // read data from file
  Future<String> readData() async {
      try {
        final file = await _localFile;
        //read from file
        String data = await file.readAsString();
        return data;
      }
      catch(e) {
        debugPrint(e.toString());
        return "nothing saved yet!";
      }
  }

```

```
Console:

Initializing hot reload...
I/flutter ( 4813): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter ( 4813): The following assertion was thrown during performLayout():
I/flutter ( 4813): 'package:flutter/src/rendering/box.dart': Failed assertion: line 1604 pos 12:
I/flutter ( 4813): '!_debugDoingBaseline': is not true.
I/flutter ( 4813): 
I/flutter ( 4813): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter ( 4813): more information in this error message to help you determine and fix the underlying cause.
I/flutter ( 4813): In either case, please report this assertion by filing a bug on GitHub:
I/flutter ( 4813):   https://github.com/flutter/flutter/issues/new
I/flutter ( 4813): 
I/flutter ( 4813): When the exception was thrown, this was the stack:
I/flutter ( 4813): #2      RenderBox.getDistanceToBaseline (package:flutter/src/rendering/box.dart)
I/flutter ( 4813): #3      _RenderDecoration._layout.layoutLineBox (package:flutter/src/material/input_decorator.dart:751:35)
I/flutter ( 4813): #4      _RenderDecoration._layout (package:flutter/src/material/input_decorator.dart:782:18)
I/flutter ( 4813): #5      _RenderDecoration.performLayout (package:flutter/src/material/input_decorator.dart:905:44)
I/flutter ( 4813): #6      RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 4813): #7      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter ( 4813): #8      RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 4813): #9      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter ( 4813): #10     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 4813): #11     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter ( 4813): #12     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 4813): #13     _RenderListTile._layoutBox (package:flutter/src/material/list_tile.dart:726:9)
I/flutter ( 4813): #14     _RenderListTile.performLayout (package:flutter/src/material/list_tile.dart:756:28)
I/flutter ( 4813): #15     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 4813): #16     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:199:11)
I/flutter ( 4813): #17     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 4813): #18     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter ( 4813): #19     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 4813): #20     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter ( 4813): #21     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 4813): #22     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter ( 4813): #23     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 4813): #24     RenderPositionedBox.performLayout (package:flutter/src/rendering/shifted_box.dart:381:13)
I/flutter ( 4813): #25     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 4813): #26     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:199:11)
I/flutter ( 4813): #27     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 4813): #28     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:141:11)
I/flutter ( 4813): #29     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:399:7)
I/flutter ( 4813): #30     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:211:7)
I/flutter ( 4813): #31     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:355:14)
I/flutter ( 4813): #32     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 4813): #33     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter ( 4813): #34     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 4813): #35     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter ( 4813): #36     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1143:11)
I/flutter ( 4813): #37     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 4813): #38     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter ( 4813): #39     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 4813): #40     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter ( 4813): #41     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 4813): #42     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter ( 4813): #43     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 4813): #44     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter ( 4813): #45     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 4813): #46     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter ( 4813): #47     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 4813): #48     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter ( 4813): #49     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 4813): #50     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter ( 4813): #51     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 4813): #52     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter ( 4813): #53     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:2831:13)
I/flutter ( 4813): #54     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 4813): #55     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:520:15)
I/flutter ( 4813): #56     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 4813): #57     __RenderTheatre&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter ( 4813): #58     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 4813): #59     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter ( 4813): #60     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 4813): #61     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter ( 4813): #62     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 4813): #63     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter ( 4813): #64     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 4813): #65     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter ( 4813): #66     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 4813): #67     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter ( 4813): #68     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 4813): #69     RenderView.performLayout (package:flutter/src/rendering/view.dart:125:13)
I/flutter ( 4813): #70     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1445:7)
I/flutter ( 4813): #71     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:709:18)
I/flutter ( 4813): #72     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:270:19)
I/flutter ( 4813): #73     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:627:13)
I/flutter ( 4813): #74     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
I/flutter ( 4813): #75     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter ( 4813): #76     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter ( 4813): #77     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:751:7)
I/flutter ( 4813): #79     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
I/flutter ( 4813): #80     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
I/flutter ( 4813): #81     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
I/flutter ( 4813): (elided 3 frames from class _AssertionError and package dart:async)
I/flutter ( 4813): 
I/flutter ( 4813): The following RenderObject was being processed when the exception was fired:
I/flutter ( 4813):   _RenderDecoration#2ed2f relayoutBoundary=up11 NEEDS-LAYOUT NEEDS-PAINT
I/flutter ( 4813):   creator: _Decorator ← InputDecorator ← AnimatedBuilder ← Listener ← RawGestureDetector ←
I/flutter ( 4813):   GestureDetector ← IgnorePointer ← Semantics ← TextField ← DefaultTextStyle ←
I/flutter ( 4813):   AnimatedDefaultTextStyle ← _ListTile ← ⋯
I/flutter ( 4813):   parentData: <none> (can use size)
I/flutter ( 4813):   constraints: BoxConstraints(w=353.4, 0.0<=h<=577.4)
I/flutter ( 4813):   size: Size(353.4, 59.0)
I/flutter ( 4813): This RenderObject had the following descendants (showing up to depth 5):
I/flutter ( 4813):   RenderRepaintBoundary#53a61 relayoutBoundary=up12 NEEDS-PAINT
I/flutter ( 4813):     RenderRepaintBoundary#dfec3 relayoutBoundary=up13 NEEDS-PAINT
I/flutter ( 4813):       RenderCustomPaint#d1b2d relayoutBoundary=up14 NEEDS-PAINT
I/flutter ( 4813):         RenderRepaintBoundary#790bc relayoutBoundary=up15 NEEDS-PAINT
I/flutter ( 4813):           RenderPointerListener#45d71 relayoutBoundary=up16 NEEDS-PAINT
I/flutter ( 4813):   RenderTransform#5d68a relayoutBoundary=up12 NEEDS-PAINT
I/flutter ( 4813):     RenderParagraph#539b5 relayoutBoundary=up13 NEEDS-PAINT
I/flutter ( 4813):   RenderConstrainedBox#e3086 relayoutBoundary=up12 NEEDS-LAYOUT NEEDS-PAINT
I/flutter ( 4813):   RenderCustomPaint#37e69 NEEDS-LAYOUT NEEDS-PAINT
I/flutter ( 4813): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter ( 4813): Another exception was thrown: 'package:flutter/src/rendering/box.dart': Failed assertion: line 1604 pos 12: '!_debugDoingBaseline': is not true.
I/flutter ( 4813): Another exception was thrown: RenderBox was not laid out: _RenderListTile#285aa relayoutBoundary=up7 NEEDS-PAINT
I/flutter ( 4813): Another exception was thrown: RenderBox was not laid out: RenderPadding#7f10e relayoutBoundary=up6 NEEDS-PAINT
I/flutter ( 4813): Another exception was thrown: RenderBox was not laid out: RenderSemanticsAnnotations#3363e relayoutBoundary=up5 NEEDS-PAINT
I/flutter ( 4813): Another exception was thrown: RenderBox was not laid out: RenderPointerListener#31536 relayoutBoundary=up4 NEEDS-PAINT
I/flutter ( 4813): Another exception was thrown: 'package:flutter/src/rendering/shifted_box.dart': Failed assertion: line 310 pos 12: 'child.hasSize': is not true.
Reloaded 1 of 392 libraries in 945ms.
```

**Comment by zoechi** [comment] 2018-08-02 07:43
Looks like a dup of #18755

**Comment by zoechi** [comment] 2019-01-29 13:00
Duplicate of #24705

**Closed by zoechi** 2019-01-29 13:00 UTC
Labels: framework, severe: crash
