### ISSUE TITLE
basic_material_app_win__compile regressed with kotlin

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#39162] opened 2019-08-24 01:12 UTC
"[flutter_tool] Flip create language defaults to swift and kotlin #38339" caused basic_material_app_win__compile to regress.

cc @zanderso @timsneath

**Comment by zanderso** [comment] 2019-08-24 02:30
In a separate discussion, I believe that @cbracken and @jason-simmons mentioned that additional overhead from the swift and kotlin templates was expected.

**Comment by audkar** [comment] 2019-08-24 05:47
Kotlin has worse compile time then Java. However Flutter project template uses very old versions of Gradle and Kotlin. And newer versions has a lot of improvements on speed (especially incremental build and cache)

**Comment by zanderso** [comment] 2019-09-03 17:25
Upgrading versions is in progress here https://github.com/flutter/flutter/pull/32550

**Comment by audkar** [comment] 2019-09-03 17:39
That PR is being reviewed for such long time that new stable versions are already released :)

**Comment by blasten** [comment] 2019-09-10 21:55
Was the baseline updated recently? It doesn't look like a regression on the dashboard anymore.

**Comment by zanderso** [comment] 2019-09-16 15:00
Since the dashboard is green, I'll close this issue. We can track upgrading the version in the place we're already doing that.

**Closed by zanderso** 2019-09-16 15:00 UTC
Labels: severe: regression, tool
