### ISSUE TITLE
[web]: XMLHttpRequest Error

### ISSUE THREAD

**Issue by redixbit115** [flutter/flutter#70979] opened 2020-11-21 04:56 UTC
Am building an application that contains HTTP network calls. These calls are running successfully on android and ios, but when i try it on web it throws the above mentioned error.

Here is my flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, 1.23.0-18.1.pre, on Microsoft Windows [Version 10.0.18362.900], locale en-IN)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[√] Chrome - develop for the web
[√] Android Studio (version 4.0)
[√] VS Code (version 1.51.1)
[√] Connected device (4 available)

• No issues found!

**Comment by sidrao2006** [comment] 2020-11-21 05:40
Hello @redixbit115 ,
Could you please post the outputs of `flutter run -v` and `flutter doctor -v` and a complete minimal reproducible code sample?
Thank you!

**Comment by melwinlobo18** [comment] 2020-11-21 11:09
Hey @redixbit115 , this is caused by [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS).

If you have access to the backend then add the required headers in the response as given in the above doc. Or you can do either of the following:
- Use a **proxy server** e.g [cors-anywhere](https://github.com/Rob--W/cors-anywhere)
- Run the app in Chrome with [disabled security](https://alfilatov.com/posts/run-chrome-without-cors/)

**Comment by darshankawar** [comment] 2020-11-23 09:43
@redixbit115 
Check [this](https://github.com/flutter/flutter/issues/57421#issuecomment-638843037) issue comment and it doesn't look like an issue with Flutter web, but with the backend you are using. Also check above comment and possible solution.
Closing this from here. If you disagree, write in comments and I'll reopen it.
Thanks.

**Closed by darshankawar** 2020-11-23 09:43 UTC

**Comment by eqrakhattak** [comment] 2021-05-29 23:17
> Hey @redixbit115 , this is caused by [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS).
> 
> If you have access to the backend then add the required headers in the response as given in the above doc. Or you can do either of the following:
> 
> * Use a **proxy server** e.g [cors-anywhere](https://github.com/Rob--W/cors-anywhere)
> * Run the app in Chrome with [disabled security](https://alfilatov.com/posts/run-chrome-without-cors/)

Where do I add the headers? Especially if I'm running my flutter website on localhost.

**Comment by melwinlobo18** [comment] 2021-05-30 02:40
Deploy the proxy server in Heroku or Vercel. You'll get an URL after deployment. After that you need to add the URL before your API endpoint while making the calls. i.e "proxy_server_url/api_endpoint". The proxy server will add the necessary headers

**Comment by eqrakhattak** [comment] 2021-05-30 15:41
@melwinlobo18 I tried using this solution  #[https://github.com/lejard-h/google_maps_webservice/issues/70#issuecomment-636919093](url) but I got stuck in this error

**Comment by Usman90422** [comment] 2021-06-13 14:05
@eqrakhattak Did you find a solution for this? I am using flutter web and facing the same issue.
