### ISSUE TITLE
A line between appbar and body, with PreferredSize

### ISSUE THREAD

**Issue by chcarmen** [flutter/flutter#57881] opened 2020-05-24 04:23 UTC
when using PreferredSize, there is a line between appbar and body:

**code**:
```
Scaffold(
    appBar: PreferredSize(
          preferredSize: Size.fromHeight(45.3),
          child: AppBar(elevation: 0, backgroundColor: Colors.red,),
     ),
    body: Container(color: Colors.red )
)
```

**effect**:
![捕获](https://user-images.githubusercontent.com/33441480/82745546-51320f80-9db8-11ea-8225-63e228b119a4.JPG)

on thing deserve to notice is that, it happens only when the value of preferredSize height has decimal fraction，here it is 45.3.  While if set it to 45.0 or 46.0, this issue disappear. and also, it happens only on some phones, not all the phones.

here are similar issues, but not exactly the same:
#40947  #40939

**Comment by iapicca** [comment] 2020-05-25 09:51
Hi @chcarmen 
the issue seems to be same of https://github.com/flutter/flutter/issues/40947 ,
but you are mentioning it isn't;
could you please detail the difference
Thank you

**Comment by chcarmen** [comment] 2020-05-25 12:09
**Issue #40947 nothing related to PreferredSize, while this issue is related to PreferredSize.**

with the latest flutter 1.17, on my device:

The following code works well, but as  #40947 described, it shows a line between appbar and body.
```
Scaffold(
    appBar: AppBar(elevation: 0, backgroundColor: Colors.red,),
    body: Container(color: Colors.red )
)
```

line appears only for me with the following code:
```
Scaffold(
    appBar: PreferredSize(
          preferredSize: Size.fromHeight(45.3),
          child: AppBar(elevation: 0, backgroundColor: Colors.red,),
     ),
    body: Container(color: Colors.red )
)
```

**Comment by TahaTesser** [comment] 2020-05-26 09:16
Hi @chcarmen 
Using `PreferredSize` doesn't make it a different issue, this is still cause by AppBar
Closing as duplicate of https://github.com/flutter/flutter/issues/40947

**Closed by TahaTesser** 2020-05-26 09:16 UTC
Labels: in triage

**Comment by ghenry** [comment] 2020-08-23 17:50
I'm seeing this white line on the latest Flutter stable as per the example. 

```
Scaffold(
    appBar: AppBar(elevation: 0, backgroundColor: Colors.red,),
    body: Container(color: Colors.red )
)
 ```

**Comment by ghenry** [comment] 2020-08-23 18:06
![Screenshot_20200823-190536](https://user-images.githubusercontent.com/159608/90985414-c1952c00-e573-11ea-87fc-e33f9f36fbc5.jpg)

**Comment by TahaTesser** [comment] 2020-08-24 15:16
Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by mohamedenab** [comment] 2020-10-02 07:55
i solve it with a workaround 
here is my code with white line 
`Scaffold(
      key: _scaffoldKey,
      backgroundColor: Color(0xffe11e27),
      resizeToAvoidBottomInset: true,
      appBar: AppBar(
        elevation: 0.0,
      ),
      body: Container(
        color: Colors.white,
        child: Column(
          children: [
            Expanded(
              child: SingleChildScrollView(
                child: Stack(
                  children: [
                    Arc(
                      arcType: ArcType.CONVEX,
                      edge: Edge.BOTTOM,
                      height: 40.0,
                      // clipShadows: [ClipShadow(color: Colors.black)],
                      child: new Container(
                        height: sizes.size.height * .3,
                        width: sizes.size.width,
                        color: Color(0xffe11e27),
                      ),
                    ),
                    Center(
                      child: Column(.....`
preview: 
![Screenshot_20201002-093805](https://user-images.githubusercontent.com/32667940/94899419-91ef1300-0493-11eb-9447-2ef18076650b.jpg)
i solve by put `   Positioned(
                      top: -1,
                        child: Container(
                          width: sizes.size.width,
                          height: 2,
                      color: Color(0xffe11e27),
                    )),` as first child of the stack so it will cover the with line you can use the same by putting the rest of your body in the seconde child of the stack so Positioned will be behind the body and cover the white line 
` Stack(
                  children: [
                    Positioned(
                      top: -1,
                        child: Container(
                          width: sizes.size.width,
                          height: 2,
                      color: Color(0xffe11e27),
                    )),
                    Arc(
                      arcType: ArcType.CONVEX,
                      edge: Edge.BOTTOM,
                      height: 40.0,
                      // clipShadows: [ClipShadow(color: Colors.black)],
                      child: new Container(
                        height: sizes.size.height * .3,
                        width: sizes.size.width,
                        color: Color(0xffe11e27),
                      ),
                    ),
                   `
preview: 

![Screenshot_20201002-093812](https://user-images.githubusercontent.com/32667940/94899420-93204000-0493-11eb-9625-0d96d3a4ec39.jpg )
