### ISSUE TITLE
There is black space on top when using `SystemUiMode.immersiveSticky`

### ISSUE THREAD

**Issue by samithe7** [flutter/flutter#96193] opened 2022-01-05 21:23 UTC
```dart
void main() {
  WidgetsFlutterBinding.ensureInitialized();

  SystemChrome.setEnabledSystemUIMode(
    SystemUiMode.immersiveSticky,

     overlays: [
       SystemUiOverlay.bottom, SystemUiOverlay.top
    ]
  
  );

  SystemChrome.setSystemUIOverlayStyle(
    const SystemUiOverlayStyle(
      systemNavigationBarColor: Colors.transparent,
      systemNavigationBarDividerColor: Colors.transparent,
      // statusBarBrightness: Brightness.light,
      statusBarColor: Colors.transparent,
    ),
  );

  late final _connectivity = Connectivity();
  runApp(
    riverpod.ProviderScope(
      child: MyApp(
   
        connectivity: _connectivity,
      ),
    ),
  );
}

**Comment by samithe7** [comment] 2022-01-05 21:26
- > 


![Screenshot_1641417699](https://user-images.githubusercontent.com/53804061/148291721-08ce14b5-ac7d-4dfc-9015-f476cd48b6a5.png)
)

**Comment by samithe7** [comment] 2022-01-05 21:28
![InkedScreenshot_1641417699_LI](https://user-images.githubusercontent.com/53804061/148291976-4ae2a034-a804-49e7-a99a-2cdc48f89463.jpg)

**Comment by danagbemava-nc** [comment] 2022-01-06 08:28
Hi @samithe7, thanks for filing the issue. 
Please provide the output of `flutter doctor -v` as well as a complete minimal reproducible code sample without any third party packages. 

Thank you

**Comment by samithe7** [comment] 2022-01-06 12:10
[√] Flutter (Channel stable, 2.8.1, on Microsoft Windows
    [Version 10.0.19042.1415], locale en-US)
    • Flutter version 2.8.1 at C:\src\flutter
    • Upstream repository
      https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (3 weeks ago),      
      2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[√] Android toolchain - develop for Android devices   
    (Android SDK version 31.0.0-rc4)
    • Android SDK at
      C:\Users\samiu\AppData\Local\Android\sdk        
    • Platform android-31, build-tools 31.0.0-rc4     
    • Java binary at: C:\Program Files\Android\Android
      Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build   
      11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program
      Files\Google\Chrome\Application\chrome.exe        

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android
      Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart   
    • Java version OpenJDK Runtime Environment (build   
      11.0.10+0-b96-7249189)

[√] VS Code (version 1.63.2)
    • VS Code at
      C:\Users\samiu\AppData\Local\Programs\Microsoft VS
      Code
    • Flutter extension version 3.32.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google
      Chrome 96.0.4664.110
    • Edge (web)   • edge   • web-javascript • Microsoft  
      Edge 96.0.1054.62

• No issues found!

**Comment by maheshmnj** [comment] 2022-01-06 12:43
Duplicate of https://github.com/flutter/flutter/issues/95403

**Comment by danagbemava-nc** [comment] 2022-01-06 12:44
@samithe7 kindly follow up in #95403

**Closed** 2022-01-06 12:44 UTC
Labels: in triage
