### ISSUE TITLE
Performance issues on iOS simulator

### ISSUE THREAD

**Issue by FaisalAbid** [flutter/flutter#9366] opened 2017-04-13 05:48 UTC
The performance of the iOS simulator is terrible for the past few days when developing.

Android Emulator on the other hand is snappy and super fast

See flutter doctor below, I know its not much info right now but please let me know what else to provide for this bug!

 flutter doctor
[✓] Flutter (on Mac OS X 10.12.5 16F54b, channel master)
    • Flutter at /Users/FaisalAbid/Development/workspace/Verve/Elixer/flutter
    • Framework revision c12c019bcc (33 hours ago), 2017-04-11 13:48:04 -0700
    • Engine revision 5d9a642257
    • Tools Dart version 1.23.0-dev.11.6

[✓] Host Executable Compatibility
    • Downloaded executables execute on host

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.2)
    • Android SDK at /Users/FaisalAbid/Library/Android/sdk/
    • Platform android-25, build-tools 25.0.2
    • ANDROID_HOME = /Users/FaisalAbid/Library/Android/sdk/
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[-] iOS toolchain - develop for iOS devices (Xcode 8.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.3.1, Build version 8E1000a
    • ios-deploy 1.9.1
    ✗ libimobiledevice is incompatible with the installed Xcode version. To update, run:
        brew update
        brew uninstall --ignore-dependencies libimobiledevice
        brew install --HEAD libimobiledevice
    • CocoaPods version 1.2.0

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Gradle version 3.2
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Ultimate Edition (version 2017.1.1)
    • Dart plugin version 171.4006
    • Flutter plugin version 12.1

[✓] Connected devices
    • Android SDK built for x86 • emulator-5554                            • android-x86 • Android 7.1.1 (API 25) (emulator)
    •                           • 6d94d49f82c3be9201b2ccaca5b55e53a5d5f32c • ios         • iOS  ()
    • iPhone 6                  • 420A0FA6-F4C4-442E-A398-A912FC17917E     • ios         • iOS 10.3 (simulator)

**Comment by eseidelGoogle** [comment] 2017-04-13 13:55
We've had now 3 customers report that simulator performance *regressed* recently.  I've seen bad perf myself, but I'm not sure if it's a regression: https://github.com/flutter/flutter/issues/9171

@chinmaygarde says it should be easy to make fast, but given the number of reports I think we should consider doing so soon.

**Comment by chinmaygarde** [comment] 2017-04-17 21:18
Just an update: Patches related to scaling on the surface have landed. Will close this ticket when everything lands and there is an engine roll.

**Comment by eseidelGoogle** [comment] 2017-04-27 20:09
This should be mostly fix, correct @chinmaygarde ?

**Comment by eseidelGoogle** [comment] 2017-05-10 19:38
@lukef told me this morning that Posse has stopped using the iOS simulator for development because it's too janky to do the animation work they need to do.  So they now are using Android devices.

**Comment by eseidelGoogle** [comment] 2017-05-22 17:46
@chinmaygarde are you still actively working on this?  Can you leave instructions for someone else for next-steps if you are not?

**Comment by chinmaygarde** [comment] 2017-05-22 19:10
I should have closed this ticket once the fixes in https://github.com/flutter/flutter/issues/9366#issuecomment-294595867 had landed (which they have). If we are still facing performance issues, I can be more aggressive with the scaling. I am going to attempt this now. So yes, I am still working on this. Also, see my comment on [this ticket](https://github.com/flutter/flutter/issues/9965#issuecomment-303192259). I think it is a good idea to port this work to Android emulators as well.

**Comment by eseidelGoogle** [comment] 2017-05-22 19:19
@lukef are you and your team able to use iOS simulators for development?

**Comment by Hixie** [comment] 2017-06-06 20:56
@chinmaygarde Any updates since your last comment?

**Closed** 2017-12-12 23:53 UTC
Labels: customer: posse (eap), customer: tunes (eap), performance, ⌺‬ platform-ios
