### ISSUE TITLE
Android toolchain marked and Android license status unknown

### ISSUE THREAD

**Issue by JudeIsong** [flutter/flutter#86296] opened 2021-07-12 15:30 UTC
I get these response when i run flutter doctor
```
"C:\Windows\System32>flutter doctor ==android-licenses
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.2.2, on Microsoft Windows [Version 10.0.19043.1083], locale en-NG)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[√] Chrome - develop for the web
[√] Android Studio
[√] VS Code (version 1.53.0)
[√] Connected device (2 available)

! Doctor found issues in 1 category."
```
I have installed android, again and again, I have java installed with "java version "1.8.0_291"
Java(TM) SE Runtime Environment (build 1.8.0_291-b10)
Java HotSpot(TM) 64-Bit Server VM (build 25.291-b10, mixed mode)"

After running flutter doctor --android-licenses, i get these response
```
"C:\Windows\System32>flutter doctor --android-licenses --verbose
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
        at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
        at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
        at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 5 more"
```
I need assistance with this please.

Thanks guys

**Comment by asashour** [comment] 2021-07-12 15:32
I guess this is similar to #66907, please read https://github.com/flutter/flutter/issues/66907#issuecomment-742639300

**Comment by TahaTesser** [comment] 2021-07-13 09:07
Hi @JudeIsong 
First, make sure you've also installed cmd tools and then `flutter doctor --android-licenses` 
![image](https://user-images.githubusercontent.com/48603081/125423425-88796caa-f1f0-4d9b-a7c2-e0cc8edf1a88.png)


If the problem persists, I am not sure where I read it but this is likely a bug with this particular java version too

`C:\Users\Taha\Code\android-studio\jre\bin\java` 

My Java path is set to default JDK that comes with Android Studio itself, which java 11, and there is no issue when executing `flutter doctor --android-licenses` 


```console
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\android-sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_SDK_ROOT = C:\Users\Taha\Code\android-sdk
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.
```



I see there's an open issue addressing the case you described.
Please follow up on that issue, Closing as duplicate of https://github.com/flutter/flutter/issues/84325
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-07-13 09:07 UTC
Labels: in triage
