### ISSUE TITLE
[devicelab] integration tests are failing due to git checkout error.

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#155550] opened 2024-09-23 17:43 UTC
When trying to restore the gallery state after running a test, we run a git checkout sometimes. This seems to be failing at an elevated rate.

**Comment by jonahwilliams** [comment] 2024-09-23 17:45
The test is actually failing when it tries and fails to connect via a vm service extension method here: https://github.com/flutter/flutter/blob/master/dev/devicelab/lib/framework/runner.dart#L235-L249

**Comment by jonahwilliams** [comment] 2024-09-23 17:45
@zanderso

**Comment by zanderso** [comment] 2024-09-23 17:48
From the logs:
```
[new_gallery_opengles_impeller__transition_perf] Task runner system failed with exception!
ext.cocoonRunTask: (-32000) Service connection disposed
#0      new _OutstandingRequest (package:vm_service/src/vm_service.dart:261:34)
#1      VmService._call.<anonymous closure> (package:vm_service/src/vm_service.dart:1778:25)
#2      VmService._call (package:vm_service/src/vm_service.dart:1790:8)
#3      VmService.callServiceExtension (package:vm_service/src/vm_service.dart:1729:14)
#4      runTask (package:flutter_devicelab/framework/runner.dart:240:73)
<asynchronous suspension>
#5      rerunTask (package:flutter_devicelab/framework/runner.dart:119:29)
<asynchronous suspension>
#6      runTasks (package:flutter_devicelab/framework/runner.dart:52:16)
<asynchronous suspension>
#7      TestCommand.run (package:flutter_devicelab/command/test.dart:86:5)
<asynchronous suspension>
#8      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
```

**Comment by zanderso** [comment] 2024-09-23 20:39
This is possibly a duplicate of https://github.com/flutter/flutter/issues/155475.

**Comment by christopherfujino** [comment] 2024-09-24 21:33
Closing as a duplicate

**Closed** 2024-09-24 21:32 UTC
Labels: team-tool
