### ISSUE TITLE
Icons not displaying correctly for certain Colors

### ISSUE THREAD

**Issue by pauldemarco** [flutter/flutter#11475] opened 2017-08-02 00:12 UTC
## Steps to Reproduce

1. Navigate to flutter_gallery and run with ```flutter run```
2. Navigate to the Icons demo page within the app
3. Notice the size 48.0 Icon displays incorrectly for certain colors.
![flutter_01](https://user-images.githubusercontent.com/16725750/28852134-fdd3a318-76f4-11e7-8b01-c4deb7992ffb.png)
![flutter_02](https://user-images.githubusercontent.com/16725750/28852133-fdd0ccb0-76f4-11e7-85c1-7a1f1619aed4.png)

The problem seems to be apparent for any Icon sizes between 40.5 -> 96.0, inclusively.
Please note, I've only tested this on a Samsung S6.

**Comment by pauldemarco** [comment] 2017-08-02 00:19
Colors.blueGrey seems to be a color that still works at any size, while Colors.blue is afflicted.

**Comment by Skylled** [comment] 2017-08-03 14:38
I'm running into this problem too with my black icons, on both Master and Alpha branches.
Whether the icons display correctly seems to vary from build to build.

**Comment by eseidelGoogle** [comment] 2017-08-09 14:20
I suspect this is a race down in our text/skia code.  @jason-simmons might be able to look?

**Comment by Skylled** [comment] 2017-08-09 14:28
I'm experiencing the same behavior in `showTimePicker` too, [screenshot](http://i.imgur.com/tnlblyM.png)

**Comment by eseidelGoogle** [comment] 2017-08-10 05:07
@Skylled what's your device information?

My understanding is that @pauldemarco is seeing this on a `Samsung S6`.

@jason-simmons I don't think we have a Samsung S6 in our cube, but the central lab does if needed.

**Comment by Skylled** [comment] 2017-08-10 13:47
@eseidelGoogle I can consistently repro on my LG v20, but not on a Samsung S8.

**Comment by eseidelGoogle** [comment] 2017-08-10 15:22
LG v20 is an Adreno 530 gpu.
Samsung S6 is a Mali-T760MP8 gpu.

Unfortunately it looks like the central lab doesn't have either of those two phones. :(

**Comment by eseidelGoogle** [comment] 2017-08-10 15:26
Adreno 530: http://www.phonebunch.com/phone-filter/gpu/adreno-530/page/1/
Mali-T760MP8: http://www.phonebunch.com/phone-filter/gpu/mali-t760mp8/page/1/

I believe we have a Galaxy Note 5 in our cube which has the Mali-T760MP8.

**Comment by eseidelGoogle** [comment] 2017-08-14 20:56
@jason-simmons are you able to investigate?

**Comment by jason-simmons** [comment] 2017-08-15 00:01
I experimented with this on a few devices and was able to reproduce the missing icons on a Nexus 7.  If I arrange a GridView of icons with iconSize=128, the icons fail to render some of the time.  It's inconsistent across runs and seems to be sensitive to timing (e.g. it occurred more often in profile mode than in debug mode)

I was able to make the text render consistently as intended by forcing path rendering mode (specifically, by turning on the glyph->fTooLargeForAtlas flag in GrAtlasTextBlob::appendGlyph)

I'm not sure why the text wasn't rendering in the usual GrAtlasTextOp / GrDistanceFieldA8TextGeoProc code path.

Skia team: any ideas?

@bsalomon @jvanverth

**Comment by bsalomon** [comment] 2017-08-15 12:52
@jvanverth is out today. I'll take a look at this. We most likely have a device that can reproduce the issue. Is this the 2012 (Tegra) or 2013 (Adreno) Nexus 7?

**Comment by jason-simmons** [comment] 2017-08-15 16:43
It's a 2012 Nexus 7

**Comment by jason-simmons** [comment] 2017-08-15 17:29
Try running this Flutter app in profile mode on the Nexus 7:

```
import 'package:flutter/material.dart';

void main() {
  runApp(new MaterialApp(
    home: new Scaffold(
      body: new IconButton(icon: new Icon(Icons.mail), iconSize: 128.0)
    ),
  ));
}
```

On my device, the icon fails to render on roughly one third of the times I've started the app.

**Comment by collinjackson** [comment] 2017-08-22 00:54
This appears to be an issue affecting Posse -- large text is showing up as white squares, and they'd like to get a fix in for their next release. @bsalomon or @jvanverth could you please take a look?

@jason-simmons's test case was complaining about a missing `onPressed` handler. Here's my version:

```
import 'package:flutter/material.dart';

void main() {
  runApp(new MaterialApp(
    home: new Scaffold(
      body: new IconButton(
        icon: new Icon(Icons.mail),
        iconSize: 128.0,
        onPressed: () {},
      ),
    ),
  ));
}
```

(I ordered a Galaxy S7 so we'll soon have a device in Mountain View that can confirm that Posse's issue was fixed. It doesn't seem to repro on the S8.)

**Comment by bsalomon** [comment] 2017-08-22 11:33
I'll pick this back up again today. I had run into a crash issue running on Android when I attempted to investigate last week but I believe that is resolved now.

**Comment by bsalomon** [comment] 2017-08-22 15:06
I've run both Colin and Jason's code both several times on a Galaxy 7 Edge and not reproduced the bug. I'll try some other devices.

**Comment by bsalomon** [comment] 2017-08-22 16:17
I've now tried N6, N6P, N5, and Android One devices and not been able to reproduce.

**Comment by jason-simmons** [comment] 2017-08-22 16:45
This issue is very sensitive to the specific GPU and drivers.  I've tried various devices but have only been able to reproduce it on the Nexus 7 (running Jellybean 4.1.2 / JZO54K)

**Comment by collinjackson** [comment] 2017-08-22 17:19
I am investigating workarounds for the posse to unblock them; it seems like I should be able to force path-based rendering by drawing text at [with dimensions >256](https://github.com/google/skia/blob/master/src/gpu/GrDrawOpAtlas.h#L173) and then scale it down with a transform.

**Comment by collinjackson** [comment] 2017-08-22 19:42
Here's an example that repros the issue with regular text, not using icons.

```
import 'package:flutter/material.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(new MaterialApp(
    home: new Scaffold(
      body: new Container(
        margin: const EdgeInsets.all(200.0),
        color: Colors.blueAccent,
        child: new Text('12', style: new TextStyle(fontSize: 128.0)),
      ),
    ),
  ));
}
```

In profile mode on the Nexus 7, it sometimes looks like this:

![flutter_01](https://user-images.githubusercontent.com/394889/29579835-df175566-8728-11e7-8c58-50357f988587.png)

Other times it works:

![flutter_02](https://user-images.githubusercontent.com/394889/29580313-704dbc40-872a-11e7-83d2-117bc9e47bcc.png)

The logs look similar. Both successful and failed runs include this warning in the logs (probably unrelated).

```
D/skia    ( 7350): [SkFontMgr Android Parser] '/system/etc/fonts.xml' could not be opened
D/skia    ( 7350): [SkFontMgr Android Parser] '/vendor/etc/fallback_fonts.xml' could not be opened
```

I found that if I rasterize the text to a Picture and then draw, it always works:

```
import 'dart:ui' as ui;
import 'package:flutter/material.dart';
import 'package:meta/meta.dart';

class _TextWorkaroundPainter extends CustomPainter {
  _TextWorkaroundPainter(this.text, { @required this.style });
  final String text;
  final TextStyle style;

  @override
  void paint(Canvas canvas, Size size) {
    final double scaleFactor = 4.0;
    final ui.PictureRecorder recorder = new ui.PictureRecorder();
    final ui.Canvas scaledCanvas = new ui.Canvas(
      recorder,
      ui.Offset.zero & (size * scaleFactor),
    );
    final ui.ParagraphBuilder paragraphBuilder = new ui.ParagraphBuilder(
        new ui.ParagraphStyle(fontSize: style.fontSize * scaleFactor),
    )
      ..pushStyle(new ui.TextStyle(color: style.color))
      ..addText(text);
    final ui.Paragraph paragraph = paragraphBuilder.build()
      ..layout(new ui.ParagraphConstraints(width: size.width * scaleFactor));
    scaledCanvas
      ..drawParagraph(
        paragraph,
        Offset.zero,
      );
    final ui.Picture picture = recorder.endRecording();
    canvas
      ..save()
      ..scale(1.0 / scaleFactor, 1.0 / scaleFactor)
      ..drawPicture(picture)
      ..restore();
  }

  @override
  bool shouldRepaint(_TextWorkaroundPainter other) {
    return other.text != text || other.style != style;
  }
}

/// Workaround for https://github.com/flutter/flutter/issues/11475
class TextWorkaround extends StatelessWidget {
  TextWorkaround(this.text, { @required this.style });
  final String text;
  final TextStyle style;

  @override
  Widget build(BuildContext context) {
    return new CustomPaint(
      foregroundPainter: new _TextWorkaroundPainter(text, style: style),
      child: new Text(
        text,
        style: style.copyWith(color: Colors.transparent)
      ),
    );
  }
}

void main() {
  runApp(new MaterialApp(
    home: new Scaffold(
      body: new Container(
        margin: const EdgeInsets.all(200.0),
        color: Colors.blueAccent,
        child: new TextWorkaround(
          '12',
          style: new TextStyle(fontSize: 128.0, color: Colors.white),
        )
      ),
    ),
  ));
}
```

If I use other values for `scaleFactor` (e.g. `1.0`) text doesn't always draw, so I think that it's important to get over that 256.0 threshold.

![flutter_10](https://user-images.githubusercontent.com/394889/29584010-3e50c1da-8737-11e7-8e6f-19b7bc99d4bc.png)

**Comment by jvanverth** [comment] 2017-08-22 20:07
A few comments while we try to duplicate here:

Skia will use SDFs for paths/text of sizes 162 to 324. For all those cases it will upload a path/glyph of size ~162, so it shouldn't ever exceed the kGlyphMaxDim. You'd need to push the max dimension of the path up over 324 to get the regular path renderers. If you want to disable SDFs to confirm that's the issue, you can set fUsesDistanceField to 'false' around lines 161 to 166 in GrSmallPathRenderer.cpp. Or, alternatively, clear the GpuPathRenderers::kSmall bit in GrContextOptions::fGpuPathRenderers. Short-term, we could probably just disable that path renderer on the Tegra3.

**Comment by bsalomon** [comment] 2017-08-22 22:10
I had to work from home this afternoon. I brought a N7 2012 with me. It's running L and I don't have a repro. I tried flashing JZO54K to it but I'm having trouble with fastboot. Jim and I will be traveling to NYC for the day tomorrow and back in NC on Thursday. We can pick this back up when when I have access to flashstation.

**Comment by collinjackson** [comment] 2017-08-22 22:54
Sounds good, thanks! If you want me to ship our Nexus 7 to NC, I can.

**Comment by bsalomon** [comment] 2017-08-24 14:57
I think I have a repro. I have a N7 running JKO54K. I installed Collin's code that draws the envelope icon by running "flutter run --profile". I then launched and closed the app several times on the device and once the icon did not display.

**Comment by bsalomon** [comment] 2017-08-24 15:07
I'm trying to use my own engine after sync'ing (profile_unopt or profile) and I get:

F/flutter ( 5298): [FATAL:flutter/shell/common/engine.cc(159)] Check failed: !aot_snapshot_path.empty().

Commenting out that line just delays failure.

**Comment by bsalomon** [comment] 2017-08-24 15:15
It works if I also add --profile to the flutter command line.

**Comment by bsalomon** [comment] 2017-08-24 21:12
We have two stages of fallbacks for large glyphs. Above the some size threshold we render as a distance field and above a larger threshold we render as a path. This is hitting the distance field case. When the repro occurs I've verified that we are computing a distance field for the glyph and attempting to upload it to the atlas texture. I'm guessing that it is the texture update that fails. Otherwise, I'd expect that subsequent frames would be correct.

**Comment by chinmaygarde** [comment] 2017-08-28 18:58
The patches have landed in Skia. I am performing a roll now and verifying the fix. Thanks @jvanverth .

**Comment by chinmaygarde** [comment] 2017-08-28 23:01
The fixes have landed. Can someone verify?

**Comment by pauldemarco** [comment] 2017-08-29 04:59
It looks to be fixed on my Samsung S6 :+1: 
Thanks!

**Comment by Hixie** [comment] 2017-08-29 20:11
Thanks for the fix and the verification! I'm going to close this. Please reopen if it's still a problem.

**Closed by Hixie** 2017-08-29 20:11 UTC
Labels: customer blocker, customer: posse (eap), dependency: skia
