### ISSUE TITLE
Subsequent calls on ScaleTransition causes element to be invisible

### ISSUE THREAD

**Issue by themadmrj** [flutter/flutter#76530] opened 2021-02-22 13:59 UTC
When calling `animationController.forward()` and then `animationController.reverse()` multiple times in a row, the element ends up not being drawn.

<details>
  <summary>Minimal app</summary>

```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(

        primarySwatch: Colors.blue,

        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);


  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {


  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Input(),
      ),
    );
  }
}

class Input extends StatefulWidget {
  Input({Key key}) : super(key: key);

  @override
  _InputSate createState() => _InputSate();
}

class _InputSate extends State<Input>
    with TickerProviderStateMixin {
  AnimationController _animationControllerCheckMark;
  AnimationController _animationControllerSend;
  Animation<double> _animationCheckmark;
  Animation<double> _animationSend;

  bool isAnimating = false;

  @override
  void initState() {
    _animationControllerCheckMark =
        AnimationController(vsync: this, duration: Duration(milliseconds: 150));
    _animationControllerSend =
        AnimationController(vsync: this, duration: Duration(milliseconds: 150));
    _animationCheckmark =
        Tween<double>(begin: 0, end: 1).animate(_animationControllerCheckMark);
    _animationSend =
        Tween<double>(begin: 1, end: 0).animate(_animationControllerSend);
    super.initState();
  }

  void sendMessage() {
    isAnimating = true;
    _animationControllerSend
        .forward()
        .then((value) => _animationControllerCheckMark.forward());

    Future.delayed(Duration(seconds: 2), () {
      _animationControllerCheckMark
          .reverse()
          .then((value) => _animationControllerSend.reverse().then((value) {
                isAnimating = false;
              }));
    });
  }

  @override
  Widget build(BuildContext context) {
    return RaisedButton(
        onPressed: sendMessage,
        child: Stack(alignment: Alignment.center, children: [
          ScaleTransition(
              key: Key("ScaleTransition1"),
              scale: _animationCheckmark,
              child: Icon(Icons.check)),
          ScaleTransition(
              key: Key("ScaleTransition2"),
              scale: _animationSend,
              child: Text("SEND")),
        ]));
  }

  @override
  void dispose() {
    _animationControllerCheckMark.dispose();
    _animationControllerSend.dispose();
    super.dispose();
  }
}
```
</details>

<details>
  <summary>Logs</summary>

```

[√] Flutter (Channel stable, 1.22.5, on Microsoft Windows [Version 10.0.19041.804], locale fr-FR)
    • Flutter version 1.22.5 at E:\Flutter
    • Framework revision 7891006299 (2 months ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\MrJ\AppData\Local\Android\sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: E:\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.1.0)
    • Android Studio at E:\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[!] Connected device
    ! Device emulator-5554 is offline.

! Doctor found issues in 2 categories.


```

</details>

Somehow screen recording doesn't work on my emulator, if someone would be so kind and post the result, that would certainly make things clearer. Just start the app and click the button everytime you see "SEND".

**Comment by TahaTesser** [comment] 2021-02-22 15:19
Hi @themadmrj 
Here I tried several times, nothing odd


https://user-images.githubusercontent.com/48603081/108728099-3f4fe980-754f-11eb-9eef-9d8291eaa10f.mp4

<details>
<summary>flutter doctor -v</summary>

```bash
  ╔════════════════════════════════════════════════════════════════════════════╗
  ║                 Welcome to Flutter! - https://flutter.dev                  ║
  ║                                                                            ║
  ║ The Flutter tool uses Google Analytics to anonymously report feature usage ║
  ║ statistics and basic crash reports. This data is used to help improve      ║
  ║ Flutter tools over time.                                                   ║
  ║                                                                            ║
  ║ Flutter tool analytics are not sent on the very first run. To disable      ║
  ║ reporting, type 'flutter config --no-analytics'. To display the current    ║
  ║ setting, type 'flutter config'. If you opt out of analytics, an opt-out    ║
  ║ event will be sent, and then no further information will be sent by the    ║
  ║ Flutter tool.                                                              ║
  ║                                                                            ║
  ║ By downloading the Flutter SDK, you agree to the Google Terms of Service.  ║
  ║ Note: The Google Privacy Policy describes how data is handled in this      ║
  ║ service.                                                                   ║
  ║                                                                            ║
  ║ Moreover, Flutter includes the Dart SDK, which may send usage metrics and  ║
  ║ crash reports to Google.                                                   ║
  ║                                                                            ║
  ║ Read about data we send with crash reports:                                ║
  ║ https://flutter.dev/docs/reference/crash-reporting                         ║
  ║                                                                            ║
  ║ See Google's privacy policy:                                               ║
  ║ https://policies.google.com/privacy                                        ║
  ╚════════════════════════════════════════════════════════════════════════════╝
[✓] Flutter (Channel stable, 1.22.6, on macOS 11.2.1 20D74 darwin-x64, locale en-GB)
    • Flutter version 1.22.6 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 9b2d32b605 (4 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_SDK_ROOT to that location.
      You may also want to add it to your PATH environment variable.
[!] Xcode - develop for iOS and macOS (Xcode 12.4)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install:
        sudo gem install cocoapods
[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
[✓] VS Code (version 1.53.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0
[✓] Connected device (1 available)
    • Taha’s iPad (mobile) • 00008020-000255113EE8402E • ios • iOS 14.4
! Doctor found issues in 3 categories.
```

</details>


I cannot reproduce this issue on the latest `stable` channel.
Can you please upgrade to the latest  `stable` and try again
`flutter channel stable`
`flutter upgrade --force`
`flutter doctor -v`

Thank you

**Comment by pedromassangocode** [comment] 2021-03-17 13:40
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2021-03-17 13:40 UTC
Labels: in triage, waiting for customer response
