### ISSUE TITLE
Share plugin: share more than text

### ISSUE THREAD

**Issue by modulovalue** [flutter/flutter#19607] opened 2018-07-20 16:23 UTC
There is a flutter plugin for sharing text. 

#### [Official 'Share plugin'](https://github.com/flutter/plugins/tree/master/packages/share/)

What's missing is the ability to share files with specific MIME types (e.g. image/png) 

#7111 was supposed to track the progress on this.

Related issues:
#9817 #9817 #15790 #16743

### In a nutshell:

The Share plugin should provide a way to share more than text. 

Edit:
Check out the [esys-flutter-share](https://github.com/esysberlin/esys-flutter-share) plugin if you want to share images.

**Comment by pablote** [comment] 2018-08-03 19:45
I'd really need this to share files. There's a bunch of unofficial libs around but they don't work very well. Seems like a key piece of functionality that shouldn't be missing.

**Comment by zoechi** [comment] 2018-12-06 14:17
Duplicate of #9817

I'm closing this because the other has more discussion.
There is also a community plugin available now.

**Comment by modulovalue** [comment] 2018-12-06 14:51
This is not a duplicate. #9817 is (only) about sharing images. I think this is such an essential feature and should be supported by an official flutter plugin. 

There is no ambiguity or multiple interpretations of this feature. Android and iOS support it natively therefore flutter should also do that.

**Comment by zoechi** [comment] 2018-12-06 15:49
I don't think there is much difference once you are beyond sharing text. 
But of course we can keep this more generic issue open as well.

**Comment by zoechi** [comment] 2018-12-06 15:50
Did you check the plugin mentioned in #9817?

**Comment by modulovalue** [comment] 2018-12-06 17:49
Yes and unfortunately it's only for text & images. I've added a link to it in the issue description.

**Comment by pboos** [comment] 2018-12-07 14:01
For those interested, I just created a pull request that adds file sharing to the share plugin for both ios and android.

https://github.com/flutter/plugins/pull/970

**Comment by peek4y** [comment] 2019-04-08 09:52
Any plans to merge @pboos PR?

**Comment by p30arena** [comment] 2019-04-08 11:20
https://github.com/flutter/plugins/pull/970
https://github.com/flutter/plugins/pull/1423

@bparrishMines @amirh 
We need this feature ASAP, Thanks!

**Comment by AkramChauhan** [comment] 2019-05-07 01:54
You can share images with this plugin.
```
dependencies:
  esys_flutter_share: ^1.0.1
```
import 'package:esys_flutter_share/esys_flutter_share.dart';
``
Share file:

```
final ByteData bytes = await rootBundle.load('assets/image1.png');
await Share.file('esys image', 'esys.png', bytes.buffer.asUint8List(), 'image/png');
```

Share file from url:

```
var request = await HttpClient().getUrl(Uri.parse('https://shop.esys.eu/media/image/6f/8f/af/amlog_transport-berwachung.jpg'));
var response = await request.close();
Uint8List bytes = await consolidateHttpClientResponseBytes(response);
await Share.file('ESYS AMLOG', 'amlog.jpg', bytes, 'image/jpg');
```

read more at
https://pub.dev/packages/esys_flutter_share#-readme-tab-

**Comment by AndreHaueisen** [comment] 2019-06-27 13:07
Will the plugin also support video sharing?

**Comment by MaterialTime** [comment] 2019-06-29 00:14
@AndreHaueisen Should support any files. Unless it uses different platform-specific methods for sharing pictures and videos.

**Comment by ammaratef45** [comment] 2019-07-13 13:03
Any updates about this issue?

**Comment by ashishrathod989816** [comment] 2019-10-18 16:20
when i am using this plugin for sharing url image and text simultaneous and using it for sharing in ios it only sharing text image is not displayed .
whats happening ..
i  am stucked with this from last 24 hours..
please suggest me what i am doing wrong..

**Comment by AriCohen8** [comment] 2019-11-16 10:15
Any update on this?

**Comment by ejain** [comment] 2020-01-11 02:21
Note that the most recent (and final?) version of the _esys_flutter_share plugin_ (1.0.2)  [doesn't work on iPadOS](https://github.com/esysberlin/esys-flutter-share/issues/46).

**Comment by pboos** [comment] 2020-01-11 06:46
Updated pull request is ready at https://github.com/flutter/plugins/pull/970. All tests pass. Just waiting for it to get merged in. But so far no response from Google.
Android and iOS worked when I tested it. But if someone can further test it on a iPadOS, it would be helpful.

**Comment by iapicca** [comment] 2020-03-11 10:39
Hi @modulovalue 
I see there's an open issues [[1](https://github.com/flutter/flutter/issues/9817), [2](https://github.com/flutter/flutter/issues/36894)] addressing the case you described.
Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you

**Comment by modulovalue** [comment] 2020-03-11 13:34
@iapicca The flutter team is taking the "thumbs up" emoji into consideration when prioritizing issues. Since this issue has almost as many thumbs-ups as the issues that you linked combined, closing this issue and not the others would distort the demand for this feature.

**Comment by iapicca** [comment] 2020-03-11 16:09
Hi @modulovalue 
https://github.com/flutter/flutter/issues/36894 has a pr attached
https://github.com/flutter/plugins/pull/970
reopening to not distort the demand for this feature.
thank you

**Comment by audkar** [comment] 2020-03-11 16:31
> has a pr attached

Ye... since 2018...

It's quite fun to watch how work is "getting done" on paper. Replace old high voted ticket with newer ones every year. And then fill yearly report how much tickets was closed.

2016 - original issue opened.
2017 - prototype created. Original issue closed.
2018 - others highly voted issues created.
2018 - PR donated by 3rd party developer
2019 - nothing. More issues created. Including one which whole purpose is to merge PR request.
2020 - same prototype is still in production. Close old highly voted ticket. Create new ones.
Future - TBD

(didn't want to _ref_ all issues with irrelevant whining, but all of them can be backtracked from this ticket)

Lets see what happens first. Internet disappears or sharing functionality gets implemented.

**Comment by jtkeyva** [comment] 2020-03-31 03:16
@mpfaff thanks for the esys_flutter_share snippet but i was unable to get it working. any help or example project appreciated!

**Comment by maheshkumar2150** [comment] 2020-04-02 18:37
> You can share images with this plugin.
> 
> ```
> dependencies:
>   esys_flutter_share: ^1.0.1
> ```
> 
> import 'package:esys_flutter_share/esys_flutter_share.dart';
> ``
> Share file:
> 
> ```
> final ByteData bytes = await rootBundle.load('assets/image1.png');
> await Share.file('esys image', 'esys.png', bytes.buffer.asUint8List(), 'image/png');
> ```
> 
> Share file from url:
> 
> ```
> var request = await HttpClient().getUrl(Uri.parse('https://shop.esys.eu/media/image/6f/8f/af/amlog_transport-berwachung.jpg'));
> var response = await request.close();
> Uint8List bytes = await consolidateHttpClientResponseBytes(response);
> await Share.file('ESYS AMLOG', 'amlog.jpg', bytes, 'image/jpg');
> ```
> 
> read more at
> https://pub.dev/packages/esys_flutter_share#-readme-tab-

The problem is

This plugin is maintained by flutter.
But the one you told was from someone else. The plugin has some bugs in android 10 and some different models. I have samsung it is not working.

**Comment by steve28100** [comment] 2020-04-22 07:36
> > You can share images with this plugin.
> > ```
> > dependencies:
> >   esys_flutter_share: ^1.0.1
> > ```
> > 
> > 
> > import 'package:esys_flutter_share/esys_flutter_share.dart';
> > ``
> > Share file:
> > ```
> > final ByteData bytes = await rootBundle.load('assets/image1.png');
> > await Share.file('esys image', 'esys.png', bytes.buffer.asUint8List(), 'image/png');
> > ```
> > 
> > 
> > Share file from url:
> > ```
> > var request = await HttpClient().getUrl(Uri.parse('https://shop.esys.eu/media/image/6f/8f/af/amlog_transport-berwachung.jpg'));
> > var response = await request.close();
> > Uint8List bytes = await consolidateHttpClientResponseBytes(response);
> > await Share.file('ESYS AMLOG', 'amlog.jpg', bytes, 'image/jpg');
> > ```
> > 
> > 
> > read more at
> > https://pub.dev/packages/esys_flutter_share#-readme-tab-
> 
> The problem is
> 
> This plugin is maintained by flutter.
> But the one you told was from someone else. The plugin has some bugs in android 10 and some different models. I have samsung it is not working. The plugin was last updated on 2019.

Right that library also have problem when sharing image and text in IOS also it seems not updated anymore. Is there any solution that we can use for share both image and text?

**Comment by Gulnur1** [comment] 2020-05-28 08:43
Any updates on this?

**Comment by li8607** [comment] 2020-07-09 09:23
还需要等多久？

**Comment by GManzke** [comment] 2020-08-28 20:00
Was fixed today!! 👏👏👏👏👏🏆🏆🏆🏆

**Comment by iapicca** [comment] 2020-08-30 08:56
@TahaTesser

**Comment by TahaTesser** [comment] 2020-08-31 13:56
Thanks @GManzke   @iapicca  
Closing as fixed. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2020-08-31 13:56 UTC
Labels: P5, customer: crowd, p: first party, p: share, plugin, severe: new feature, waiting for PR to land (fixed), would be a good package

**Comment by ceosss** [comment] 2021-05-17 16:28
Hey @TahaTesser ,
I'm using this [share plugin by flutter](https://pub.dev/packages/share).
And I'm trying to share an image as well as text,
but only text gets shared while sharing on Whatsapp.
Here is the code.

```
Future<void> shareApp({@required String referralCode}) async {

  final ByteData bytes = await rootBundle.load('assets/images/share.jpg');

  final Uint8List list = bytes.buffer.asUint8List();

  final tempDir = await getTemporaryDirectory();

  final file = await new File('${tempDir.path}/image.jpg').create();

  file.writeAsBytesSync(list);

  Share.shareFiles(
    ['${tempDir.path}/image.jpg'],
    text:
        "Hey! Download the app and use this referral code $referralCode.",
  );

}
```

**Comment by TahaTesser** [comment] 2021-05-18 13:10
@ceosss 
Please file a new issue with the details

**Comment by samuelprogmattic** [comment] 2021-06-03 14:32
> ar response = await request.close();
> Uint8List bytes = await consolidateHttpClientResponseBytes(response);
> await Share.file('ESYS AMLOG', 'amlog.jpg', bytes, 'image/jpg');

i also want to share text as well with image how to that
