### ISSUE TITLE
CupertinoSliverRefreshControl doesn't appear with box widget above it

### ISSUE THREAD

**Issue by cvolzke4** [flutter/flutter#43790] opened 2019-10-30 02:58 UTC
CupertinoSliverRefreshControl won't appear if there's a box widget above it (ie. a SliverToBoxAdapter).

These can be reproduced in the demo app by removing the CupertinoSliverNavigationBar, and adding a box widget above the CupertinoSliverRefreshControl sliver:

SliverToBoxAdapter(child: Text('xxx')),
CupertinoSliverRefreshControl(...)

https://github.com/flutter/flutter/blob/master/examples/flutter_gallery/lib/demo/cupertino/cupertino_refresh_demo.dart

#quill

**Comment by LongCatIsLooong** [comment] 2019-11-08 04:41
Per `CupertinoSliverRefreshControl`'s documentation:
> When inserted as the first sliver in a scroll view or behind other slivers that still lets the scrollable overscroll in front of this sliver (such as the CupertinoSliverNavigationBar ...:

So that behavior is by design. Could you provide a use case where a `CupertinoSliverRefreshControl` has to be placed below a box widget?

**Comment by cvolzke4** [comment] 2019-11-11 22:14
There's a separate issue for it, but CupertinoSliverRefreshControl also overlaps the system bar on iPhone X.

**Comment by TahaTesser** [comment] 2020-03-31 14:53
Hi @cvolzke4 
I am not sure if it's bug or by design. this [comment](https://github.com/flutter/flutter/issues/43790#issuecomment-551382070) says it is by design 

please link  the separate if it already filled 

Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it 
Thank you

**Closed by TahaTesser** 2020-03-31 14:53 UTC
Labels: f: cupertino, f: scrolling, framework
