### ISSUE TITLE
[tool_crash] StateError: Bad state: No context with the running Dart application.

### ISSUE THREAD

**Issue by mbulucay** [flutter/flutter#96882] opened 2022-01-19 21:46 UTC
## Command
```
flutter run --no-sound-null-safety
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
StateError: Bad state: No context with the running Dart application.
```
#0      RemoteDebuggerExecutionContext.id (package:dwds/src/debugging/execution_context.dart:55:7)
<asynchronous suspension>
#1      AppInspector._getExtensionRpcs (package:dwds/src/debugging/inspector.dart:527:20)
<asynchronous suspension>
#2      AppInspector._initialize (package:dwds/src/debugging/inspector.dart:93:34)
<asynchronous suspension>
#3      AppInspector.initialize (package:dwds/src/debugging/inspector.dart:156:5)
<asynchronous suspension>
#4      ChromeProxyService.createIsolate (package:dwds/src/services/chrome_proxy_service.dart:218:18)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 2.5.3, on Microsoft Windows [Version 10.0.19042.1466], locale en-US)
    • Flutter version 2.5.3 at P:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (3 months ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\M Bedir ULUCAY\AppData\Local\Android\sdk
    • Platform android-30, build-tools 31.0.0
    • Java binary at: P:\android studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 4.1)
    • Android Studio at P:\android studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 97.0.4692.71
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 97.0.1072.62

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 18116933e77adc82f80866c928266a5b4f1ed645
### Plugins
cloud_firestore-3.1.5
cloud_firestore_web-2.6.5
firebase_auth-3.3.4
firebase_auth_web-3.3.5
firebase_core-1.10.6
firebase_core_web-1.5.3
firebase_storage-10.2.4
firebase_storage_web-3.2.5
flutter_plugin_android_lifecycle-2.0.5
fluttertoast-8.0.8
google_sign_in-5.2.1
google_sign_in_web-0.10.0+3
image_picker-0.8.4+4
image_picker_for_web-2.1.4
path_provider-2.0.8
path_provider_android-2.0.10
path_provider_ios-2.0.7
path_provider_linux-2.1.4
path_provider_macos-2.0.4
path_provider_windows-2.0.4
share-2.0.4
url_launcher-6.0.18
url_launcher_android-6.0.14
url_launcher_ios-6.0.14
url_launcher_linux-2.0.2
url_launcher_macos-2.0.2
url_launcher_web-2.0.6
url_launcher_windows-2.0.2

**Comment by danagbemava-nc** [comment] 2022-01-20 07:36
Duplicate of #95916

**Closed by danagbemava-nc** 2022-01-20 07:36 UTC
Labels: in triage
