### ISSUE TITLE
NPE on image_picker 0.4.1 Plugin

### ISSUE THREAD

**Issue by putraxor** [flutter/flutter#17186] opened 2018-05-02 08:10 UTC
```
java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
```

# ImageResizer.java line 48
```
Fatal Exception: java.lang.RuntimeException
Failure delivering result ResultInfo{who=null, request=2342, result=-1, data=Intent { dat=content://com.google.android.apps.docs.storage/document/acc=1;doc=2 flg=0x1 }} to activity {id.tridee.mobile/id.tridee.mobile.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
android.app.ActivityThread.deliverResults (ActivityThread.java:4162)
android.app.ActivityThread.handleSendResult (ActivityThread.java:4205)
android.app.ActivityThread.-wrap20 (ActivityThread.java)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:1572)
android.os.Handler.dispatchMessage (Handler.java:102)
android.os.Looper.loop (Looper.java:163)
android.app.ActivityThread.main (ActivityThread.java:6221)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:904)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:794)

**Caused by java.lang.NullPointerException**
Attempt to invoke virtual method `'int android.graphics.Bitmap.getWidth()'` on a null object reference
`io.flutter.plugins.imagepicker.ImageResizer.resizedImage`

io.flutter.plugins.imagepicker.ImageResizer.resizedImage (ImageResizer.java:48)
io.flutter.plugins.imagepicker.ImageResizer.resizeImageIfNeeded (ImageResizer.java:37)
io.flutter.plugins.imagepicker.ImagePickerDelegate.handleResult (ImagePickerDelegate.java:262)
io.flutter.plugins.imagepicker.ImagePickerDelegate.handleChoosePictureResult (ImagePickerDelegate.java:230)
io.flutter.plugins.imagepicker.ImagePickerDelegate.onActivityResult (ImagePickerDelegate.java:217)
io.flutter.app.FlutterPluginRegistry.onActivityResult (FlutterPluginRegistry.java:194)
io.flutter.app.FlutterActivityDelegate.onActivityResult (FlutterActivityDelegate.java:139)
io.flutter.app.FlutterActivity.onActivityResult (FlutterActivity.java:128)
android.app.Activity.dispatchActivityResult (Activity.java:7128)
android.app.ActivityThread.deliverResults (ActivityThread.java:4158)
android.app.ActivityThread.handleSendResult (ActivityThread.java:4205)
android.app.ActivityThread.-wrap20 (ActivityThread.java)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:1572)
android.os.Handler.dispatchMessage (Handler.java:102)
android.os.Looper.loop (Looper.java:163)
android.app.ActivityThread.main (ActivityThread.java:6221)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:904)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:794)

# ImagePickerDelegate.java line 265

**Fatal Exception: java.lang.RuntimeException**
Unable to resume activity {id.tridee.mobile/id.tridee.mobile.MainActivity}: java.lang.RuntimeException: Failure delivering result `ResultInfo{who=null, request=2342, result=-1, data=Intent { dat=content://media/external/images/media/103134 (has extras) }} to activity {id.tridee.mobile/id.tridee.mobile.MainActivity}`: java.lang.IllegalStateException: Received images from picker that were not requested
android.app.ActivityThread.performResumeActivity
**Caused by java.lang.RuntimeException**
Failure delivering result `ResultInfo{who=null, request=2342, result=-1, data=Intent { dat=content://media/external/images/media/103134 (has extras) }}` to activity {id.tridee.mobile/id.tridee.mobile.MainActivity}: java.lang.IllegalStateException: Received images from picker that were not requested
android.app.ActivityThread.deliverResults

**Caused by java.lang.IllegalStateException**
Received images from picker that were not requested

io.flutter.plugins.imagepicker.ImagePickerDelegate.handleResult (ImagePickerDelegate.java:265)
io.flutter.plugins.imagepicker.ImagePickerDelegate.handleChoosePictureResult (ImagePickerDelegate.java:230)
io.flutter.plugins.imagepicker.ImagePickerDelegate.onActivityResult (ImagePickerDelegate.java:217)
io.flutter.app.FlutterPluginRegistry.onActivityResult (FlutterPluginRegistry.java:194)
io.flutter.app.FlutterActivityDelegate.onActivityResult (FlutterActivityDelegate.java:139)
io.flutter.app.FlutterActivity.onActivityResult (FlutterActivity.java:128)
android.app.Activity.dispatchActivityResult (Activity.java:5639)
android.app.ActivityThread.deliverResults (ActivityThread.java:3637)
android.app.ActivityThread.performResumeActivity (ActivityThread.java:3043)
android.app.ActivityThread.handleResumeActivity (ActivityThread.java:3085)
android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:2498)
android.app.ActivityThread.access$800 (ActivityThread.java:166)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:1283)
android.os.Handler.dispatchMessage (Handler.java:102)
android.os.Looper.loop (Looper.java:136)
android.app.ActivityThread.main (ActivityThread.java:5590)
java.lang.reflect.Method.invokeNative (Method.java)
java.lang.reflect.Method.invoke (Method.java:515)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1280)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1096)
dalvik.system.NativeStart.main (NativeStart.java)
```

# flutter doctor

```
[✓] Flutter (Channel master, v0.3.6-pre.68, on Linux, locale en_US.UTF-8)
    • Flutter version 0.3.6-pre.68 at /home/putraxor/DEV/flutter
    • Framework revision 1680e55c02 (30 hours ago), 2018-04-30 23:29:46 -0400
    • Engine revision 613aae032f
    • Dart version 2.0.0-dev.50.0.flutter-cd0c4e4fe1

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /home/putraxor/Android/Sdk
    • Android NDK at /home/putraxor/Android/Sdk/ndk-bundle
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = /home/putraxor/Android/Sdk
    • Java binary at: /home/putraxor/DEV/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 3.1)
    • Android Studio at /home/putraxor/DEV/android-studio
    • Flutter plugin version 23.2.2
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2017.2)
    • IntelliJ at /home/putraxor/DEV/idea-IU-172.3757.52
    • Flutter plugin version 21.2.2
    • Dart plugin version 172.4343.25

[✓] VS Code (version 1.22.2)
    • VS Code at /usr/share/code
    • Dart Code extension version 2.12.0

[!] Connected devices
    ! No devices available
```

**Comment by zoechi** [comment] 2018-05-02 08:48
Please add the output of `flutter doctor`

**Comment by putraxor** [comment] 2018-05-02 09:07
ok @zoechi

**Comment by goderbauer** [comment] 2018-05-02 23:29
Possibly a dup of https://github.com/flutter/flutter/issues/17165.

What was the source of the image you picked?

**Comment by putraxor** [comment] 2018-05-03 14:31
@goderbauer from gallery

**Comment by CaiJingLong** [comment] 2018-06-05 01:32
same crash,

```
Process: cn.sxw365.driverphone, PID: 7078
                                                 java.lang.RuntimeException: Unable to resume activity {cn.sxw365.driverphone/cn.sxw365.driverphone.MainActivity}: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=2342, result=-1, data=Intent { dat=content://media/external/images/media/4692 flg=0x1 }} to activity {cn.sxw365.driverphone/cn.sxw365.driverphone.MainActivity}: java.lang.IllegalStateException: Received images from picker that were not requested
                                                     at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3132)
                                                     at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3163)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2509)
                                                     at android.app.ActivityThread.access$900(ActivityThread.java:165)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1368)
                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                     at android.os.Looper.loop(Looper.java:150)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5546)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:792)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:682)
                                                  Caused by: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=2342, result=-1, data=Intent { dat=content://media/external/images/media/4692 flg=0x1 }} to activity {cn.sxw365.driverphone/cn.sxw365.driverphone.MainActivity}: java.lang.IllegalStateException: Received images from picker that were not requested
                                                     at android.app.ActivityThread.deliverResults(ActivityThread.java:3730)
                                                     at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3119)
                                                     at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3163) 
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2509) 
                                                     at android.app.ActivityThread.access$900(ActivityThread.java:165) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1368) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                     at android.os.Looper.loop(Looper.java:150) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:5546) 
                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:792) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:682) 
                                                  Caused by: java.lang.IllegalStateException: Received images from picker that were not requested
                                                     at io.flutter.plugins.imagepicker.ImagePickerDelegate.handleResult(ImagePickerDelegate.java:392)
                                                     at io.flutter.plugins.imagepicker.ImagePickerDelegate.handleChoosePictureResult(ImagePickerDelegate.java:359)
                                                     at io.flutter.plugins.imagepicker.ImagePickerDelegate.onActivityResult(ImagePickerDelegate.java:346)
                                                     at io.flutter.app.FlutterPluginRegistry.onActivityResult(FlutterPluginRegistry.java:194)
                                                     at io.flutter.app.FlutterActivityDelegate.onActivityResult(FlutterActivityDelegate.java:146)
                                                     at io.flutter.app.FlutterActivity.onActivityResult(FlutterActivity.java:139)
                                                     at cn.sxw365.driverphone.MainActivity.onActivityResult(MainActivity.java:52)
                                                     at android.app.Activity.dispatchActivityResult(Activity.java:6597)
                                                     at android.app.ActivityThread.deliverResults(ActivityThread.java:3726)
                                                     at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3119) 
                                                     at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3163) 
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2509) 
                                                     at android.app.ActivityThread.access$900(ActivityThread.java:165) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1368) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                     at android.os.Looper.loop(Looper.java:150) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:5546) 
                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:792) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:682) 
```

flutter doctor -v
```
[✓] Flutter (Channel master, v0.4.5-pre.85, on Mac OS X 10.12.6 16G29, locale zh-Hans-CN)
    • Flutter version 0.4.5-pre.85 at /Users/cai/fluttersdk/flutter
    • Framework revision 677df7c351 (11 days ago), 2018-05-24 16:33:46 -0700
    • Engine revision abd74ed5ed
    • Dart version 2.0.0-dev.55.0.flutter-97b6c2e09d

[!] Android toolchain - develop for Android devices (Android SDK 26.0.2)
    • Android SDK at /Users/cai/Library/Android/sdk
    • Android NDK at /Users/cai/Library/Android/sdk/ndk-bundle
    • Platform android-27, build-tools 26.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.0

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 23.1.2
    • Dart plugin version 171.4424
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.1.4)
    • IntelliJ at /Users/cai/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 24.0.2
    • Dart plugin version 181.4203.498

[✓] VS Code (version 1.23.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Dart Code extension version 2.12.1

[✓] Connected devices (1 available)
    • GEM 703LT • XJC6R16107001515 • android-arm64 • Android 6.0 (API 23)

```

**Comment by zoechi** [comment] 2018-09-15 08:47
Looks similar to #17950

**Comment by zoechi** [comment] 2018-10-29 14:48
@yeshwanthkanekal it would be quite a surprise if these changes would have any effect.
Perhaps `flutter clean` had helped in your case.

**Comment by zoechi** [comment] 2019-01-03 07:43
Duplicate of #17165

**Closed by zoechi** 2019-01-03 07:43 UTC
Labels: p: first party, plugin, severe: crash
