### ISSUE TITLE
Unit Test output showing last failed test, after running passed test. its confusing 

### ISSUE THREAD

**Issue by DwiYI** [flutter/flutter#70070] opened 2020-11-09 04:26 UTC
output test showing last failed test, after running passed test. its confusing. 
expected maybe show passed message on output message test

![ts](https://user-images.githubusercontent.com/19425248/98499860-6ecb3680-227d-11eb-9d19-c8bc32421534.png)

**Comment by pedromassangocode** [comment] 2020-11-09 09:13
Hi @DwiYI 
Following the indication of [VS Code Flutter Extension](https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter), the correct way to address the problem is to open an issue in the dedicated [repository](https://github.com/Dart-Code/Dart-Code/issues).
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by pedromassangocode** 2020-11-09 09:13 UTC
