### ISSUE TITLE
Flutter does not support TV device

### ISSUE THREAD

**Issue by coderJohnZhang** [flutter/flutter#13633] opened 2017-12-16 10:49 UTC
TV device does not support touch operation, users have to use Remote Control. We need move focus by press left, top, right, bottom direction key, and when the target widget get focus, we will press OK button to response kinds of event. But I cannot find any flutter interface to solve this interaction, much appreciate it if can add key event support for TV apps developed by flutter.

**Comment by eseidelGoogle** [comment] 2017-12-19 17:00
I've seen teams successfully build apps with Flutter and run them on Android TV.  They responded to remote control presses.  I believe they used
https://docs.flutter.io/flutter/widgets/RawKeyboardListener-class.html
to listen to the remote inputs.

This also sounds somewhat similar to https://github.com/flutter/flutter/issues/1608 or https://github.com/flutter/flutter/issues/13264?

**Comment by coderJohnZhang** [comment] 2017-12-20 02:27
I'm a beginner to flutter, much appreciate it if you can give me a simple demo. I had also read [DartDocs - SystemChannels.keyEvent](https://www.dartdocs.org/documentation/flutter/0.0.41-dev/services/SystemChannels/keyEvent-constant.html), but I don't know how to use it.

**Comment by athornz** [comment] 2017-12-28 04:28
I'd also be keen to see a bit more of an example for this.

**Comment by eseidelGoogle** [comment] 2017-12-30 20:33
One example of listening to a RawKeyboard (including remotes), which I've verified works on an Android TV Emulator:
https://github.com/flutter/flutter/blob/master/dev/manual_tests/lib/raw_keyboard.dart

To run it in your flutter checkout:
```
cd dev/manual_tests
flutter run lib/raw_keyboard.dart
```

**Comment by coderJohnZhang** [comment] 2018-01-04 12:09
This [https://github.com/coderJohnZhang/flutter_tv](https://github.com/coderJohnZhang/flutter_tv) may show what I want to do. What's more, this demo is too simple, the child menu has the same size, and I have written many bad or dead codes.

**Comment by Hixie** [comment] 2018-01-05 00:55
Duplicate of https://github.com/flutter/flutter/issues/13749.

**Closed by Hixie** 2018-01-05 00:55 UTC

**Comment by ott-web** [comment] 2019-02-21 20:50
@eseidelGoogle Your demo doesn't seem to work on iOS Simulator. I am using my MacOS keyboard and Hardware Keyboard is enabled.

**Comment by ott-web** [comment] 2019-02-21 20:57
This is another issue though...
```
flutter devices
1 connected device:

Apple TV • ADE82C61-2035-4FB3-B4AC-C53441575CFC • ios • tvOS 12.1 (unsupported) (simulator)
```

```
flutter run lib/raw_keyboard.dart 
No supported devices connected.
```

**Comment by eseidelGoogle** [comment] 2019-02-21 21:37
I don't know the state of the raw keyboard code on iOS.  iOS uses a different method for inputing from the keyboard / remotes.  I believe the `flutter` tool currently marks tvOS devices as unsupported, but it's possible someone could make them work.

**Comment by ott-web** [comment] 2019-02-22 18:44
`flutter` tool does mark Apple TV as unsupported. Here is where the train stops...
https://github.com/flutter/flutter/blob/5169ab5974571918121fa8a7ddb0d3e0623bc987/packages/flutter_tools/lib/src/ios/simulators.dart#L274

Would the different method for input on iOS be an engine change or a framework change? Or both? I wouldn't mind creating issues for adding spatial navigation and general tvOS + Android TV support and writing code to satisfy that. We'd really like to use Flutter for Connected TV apps and currently have to settle for RN.

**Comment by eseidelGoogle** [comment] 2019-02-22 18:56
Last I knew tvOS store submissions required bitcode, which we do not currently offer official support for: https://github.com/flutter/flutter/issues/15288

My expectation is that it would be possible to make Flutter work on Apple TVs, but it might be a non-trivial amount of work.  I don't know for sure, since I'm not aware of anyone having scoped the work yet.

**Comment by UmairKhalid786** [comment] 2020-12-03 10:48
I wrote a simple app which demonstrate focus and click events in different way. Link attached below.

https://github.com/UmairKhalid786/Flutter_DPad
