### ISSUE TITLE
No console output when debugging in Visual Studio 2019

### ISSUE THREAD

**Issue by deekay42** [flutter/flutter#53618] opened 2020-03-31 00:06 UTC
Not exactly a bug report, but I was wondering if console output is supported when debugging on windows using Visual Studio 2019. About a year ago I'm pretty sure this used to work, so I was wondering if it is still supported.
Running my app in VS 2019 everything works fine, but the console window stays blank.
Looking at main.cpp I see:
```
// Attach to console when present (e.g., 'flutter run') or create a
  // new console when running with a debugger.
    if (!::AttachConsole(ATTACH_PARENT_PROCESS) && ::IsDebuggerPresent()) {
        ::AllocConsole();
``` 
so I started messing around with that.
After adding the following code below the above
```
FILE* fDummy;
        
freopen_s(&fDummy, "CONIN$", "r", stdin);
        
freopen_s(&fDummy, "CONOUT$", "w", stderr);
        
freopen_s(&fDummy, "CONOUT$", "w", stdout);
```
the console shows printf output from within main.cpp, but still no dart output.
Is there a simple way to get full console output like in the past or has the engine evolved to a point where this isn't easily possible anymore?

**Comment by stuartmorgan** [comment] 2020-03-31 03:57
Duplicate of https://github.com/flutter/flutter/issues/53169

> About a year ago I'm pretty sure this used to work

The application used to (incorrectly) be built as a console application, and always open a console no matter how it was started.

**Closed by stuartmorgan** 2020-03-31 03:57 UTC
