### ISSUE TITLE
[tool_crash] String: <57 characters>

### ISSUE THREAD

**Issue by aankurjyotisetia** [flutter/flutter#145825] opened 2024-03-27 12:13 UTC
## Command
```
flutter --no-color run --machine --device-id=ZD222J42L5 --profile --dart-define=flutter.inspector.structuredErrors=true lib\main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
String: <57 characters>
```

```
```
[✓] Flutter (Channel stable, 3.10.6, on Microsoft Windows [Version 10.0.19045.4170], locale en-IN)
    • Flutter version 3.10.6 on channel stable at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (9 months ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\Ankur\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 2022.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)

[✓] VS Code (version 1.87.2)
    • VS Code at C:\Users\Ankur\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • moto g54 5G (mobile) • ZD222J42L5 • android-arm64  • Android 13 (API 33)
    • Chrome (web)         • chrome     • web-javascript • Google Chrome 123.0.6312.59
    • Edge (web)           • edge       • web-javascript • Microsoft Edge 123.0.2420.53

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 4.0.6+35
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: f468f3366c26a5092eb964a230ce7892fda8f2f8
### Plugins
android_id-0.3.6
camera-0.10.5+9
camera_android-0.10.8+16
camera_avfoundation-0.9.13+10
camera_web-0.3.2+2
connectivity_plus-5.0.2
device_info_plus-9.1.2
file_selector_linux-0.9.2+1
file_selector_macos-0.9.3+3
file_selector_windows-0.9.3+1
flutter_image_compress-2.2.0
flutter_image_compress_common-1.0.5
flutter_image_compress_macos-1.0.2
flutter_image_compress_ohos-0.0.2
flutter_image_compress_web-0.1.4+1
flutter_plugin_android_lifecycle-2.0.17
fluttertoast-8.2.4
geocoding-3.0.0
geocoding_android-3.3.0
geocoding_ios-3.0.1
geolocator-10.1.1
geolocator_android-4.4.1
geolocator_apple-2.3.7
geolocator_web-2.2.1
geolocator_windows-0.2.3
image_picker-1.0.7
image_picker_android-0.8.9+3
image_picker_for_web-3.0.2
image_picker_ios-0.8.9+1
image_picker_linux-0.2.1+1
image_picker_macos-0.2.1+1
image_picker_windows-0.2.1+1
location-5.0.3
location_web-4.2.0
modal_progress_hud_nsn-0.4.0
package_info_plus-4.2.0
path_provider-2.1.2
path_provider_android-2.2.2
path_provider_foundation-2.3.2
path_provider_linux-2.2.1
path_provider_windows-2.2.1
permission_handler-10.4.5
permission_handler_android-10.3.6
permission_handler_apple-9.1.4
permission_handler_windows-0.1.3
shared_preferences-2.2.2
shared_preferences_android-2.2.1
shared_preferences_foundation-2.3.5
shared_preferences_linux-2.3.2
shared_preferences_web-2.2.1
shared_preferences_windows-2.3.2
url_launcher-6.1.14
url_launcher_android-6.3.0
url_launcher_ios-6.2.4
url_launcher_linux-3.1.1
url_launcher_macos-3.1.0
url_launcher_web-2.0.19
url_launcher_windows-3.1.1

**Comment by darshankawar** [comment] 2024-03-27 12:39
Closing this as a duplicate of https://github.com/flutter/flutter/issues/108812

**Closed by darshankawar** 2024-03-27 12:39 UTC
Labels: in triage
