### ISSUE TITLE
Flutter Application leaving a black space on the notch

### ISSUE THREAD

**Issue by divided7** [flutter/flutter#53056] opened 2020-03-22 17:20 UTC
I want the application's top container to cover the status bar's area too, but right now my application is leaving a black area near the top.
I have tried using the SafeArea widget and applying the bottom:false attribute to it.
How can I fill the black area? I see the same even when I display a splash screen.
![Screenshot_2020-03-22-22-49-31-84_3d7008b5276af334b5e61c79e5330364 1](https://user-images.githubusercontent.com/41837037/77255721-8bcfdc80-6c8f-11ea-9f8b-91575e603e06.jpg)

**Comment by itsJoKr** [comment] 2020-03-22 20:15
Are you using any of the `SystemChrome.setEnabledSystemUIOverlays` or `WindowManager.LayoutParams`?

**Comment by divided7** [comment] 2020-03-23 08:55
@itsJoKr nope

**Comment by TahaTesser** [comment] 2020-03-23 09:47
Hi @divided7 

You're probably wrapping `SafeArea` around your Scaffold
Wrap in your body

### Check out this code sample
```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

// After
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      home: Scaffold(
        appBar: AppBar(),
        body: SafeArea(
          child: Center(
            child: Container(
              child: Text('Hello World'),
            ),
          ),
        ),
      ),
    );
  }
}

// Before
// class MyApp extends StatelessWidget {
//   @override
//   Widget build(BuildContext context) {
//     return MaterialApp(
//       title: 'Material App',
//       home: SafeArea(
//         child: Scaffold(
//           appBar: AppBar(),
//           body: Center(
//             child: Container(
//               child: Text('Hello World'),
//             ),
//           ),
//         ),
//       ),
//     );
//   }
// }

```

Thank you

**Comment by itsJoKr** [comment] 2020-03-23 10:00
You must be setting `WindowManager.LayoutParams` in some way. Maybe through some library/method that you don't know.

If you `flutter create new_project` you'll see that in fresh setup it will draw around the notch and you'll see status bar.

**Comment by divided7** [comment] 2020-03-23 11:11
![Screenshot_170](https://user-images.githubusercontent.com/41837037/77310859-0f87d880-6d25-11ea-9bc1-56f73cd05652.png)
I have wrapped my safe area around my body @TahaTesser

**Comment by divided7** [comment] 2020-03-23 12:15
@itsJoKr Is there a way I can check for that method?
I am only using the google maps, geolocator and location plugins for flutter.

**Comment by iapicca** [comment] 2020-03-23 12:23
possible duplicate of https://github.com/flutter/flutter/issues/46486

**Comment by divided7** [comment] 2020-03-23 12:27
@iapicca my code doesn't have any instance of `SystemChrome.setEnabledSystemUIOverlays([])`; or `WindowManager.LayoutParams.FLAG_FULLSCREEN`  being used, that's why I created a new issue

**Comment by TahaTesser** [comment] 2020-03-23 13:06
Closing duplicate of [#53056](https://github.com/flutter/flutter/issues/53056)

**Closed by TahaTesser** 2020-03-23 13:06 UTC
Labels: in triage
