### ISSUE TITLE
[tool_crash] ArgumentError: Invalid argument(s): Cannot find executable for /Users/nagendrababu/Documents/flutter/bin/cache/artifacts/engine/android-arm-release/darwin-x64/gen_snapshot.

### ISSUE THREAD

**Issue by Nagendrababu61** [flutter/flutter#68120] opened 2020-10-14 17:22 UTC
## Command
```
flutter --quiet assemble --depfile /Users/nagendrababu/Documents/GitHub/ReVend_Flutter_UI/build/app/intermediates/flutter/release/flutter_build.d --output /Users/nagendrababu/Documents/GitHub/ReVend_Flutter_UI/build/app/intermediates/flutter/release -dTargetFile=lib/main.dart -dTargetPlatform=android -dBuildMode=release -dTrackWidgetCreation=true -dTreeShakeIcons=true android_aot_bundle_release_android-arm android_aot_bundle_release_android-arm64 android_aot_bundle_release_android-x64
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ArgumentError: Invalid argument(s): Cannot find executable for /Users/nagendrababu/Documents/flutter/bin/cache/artifacts/engine/android-arm-release/darwin-x64/gen_snapshot.
```
#0      _getExecutable (package:process/src/interface/local_process_manager.dart:127:5)
#1      LocalProcessManager.start (package:process/src/interface/local_process_manager.dart:43:30)
#2      _DefaultProcessUtils.start (package:flutter_tools/src/base/process.dart:466:28)
#3      _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart:484:35)
#4      GenSnapshot.run (package:flutter_tools/src/base/build.dart:74:26)
#5      AOTSnapshotter.build (package:flutter_tools/src/base/build.dart:198:56)
#6      AndroidAot.build (package:flutter_tools/src/build_system/targets/android.dart:235:52)
#7      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:795:27)
<asynchronous suspension>
#8      _BuildInstance.invokeTarget.<anonymous closure> (package:flutter_tools/src/build_system/build_system.dart:738:35)
#9      new Future.sync (dart:async/future.dart:223:31)
#10     AsyncMemoizer.runOnce (package:async/src/async_memoizer.dart:43:45)
#11     _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:738:21)
<asynchronous suspension>
<asynchronous suspension>
<asynchronous suspension>
#12     FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:560:36)
#13     AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:221:58)
#14     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:860:18)
<asynchronous suspension>
#15     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:741:33)
<asynchronous suspension>
#16     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart)
#17     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#18     _rootRun (dart:async/zone.dart:1190:13)
```
```
[✓] Flutter (Channel stable, 1.20.1, on Mac OS X 10.15.5 19F101, locale en-GB)
    • Flutter version 1.20.1 at /Users/nagendrababu/Documents/flutter
    • Framework revision 2ae34518b8 (2 months ago), 2020-08-05 19:53:19 -0700
    • Engine revision c8e3b94853
    • Dart version 2.9.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/nagendrababu/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.10.0.beta.1

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.0

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: null
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: null
**Creation framework version**: null
### Plugins
connectivity-0.4.9+2
connectivity_for_web-0.3.1+2
connectivity_macos-0.1.0+4
device_info-0.4.2+7
flutter_plugin_android_lifecycle-1.0.8
geolocator-5.3.2+2
google_api_availability-2.0.4
image_picker-0.6.7+7
location_permissions-3.0.0+1
path_provider-1.6.14
path_provider_linux-0.0.1+2
path_provider_macos-0.0.4+3
share-0.6.4+5
shared_preferences-0.5.10
shared_preferences_linux-0.0.2+2
shared_preferences_macos-0.0.1+10
shared_preferences_web-0.1.2+7
sqflite-1.3.1+1
url_launcher-5.5.0
url_launcher_linux-0.0.1+1
url_launcher_macos-0.0.1+7
url_launcher_web-0.1.2+1

**Comment by pedromassangocode** [comment] 2020-10-15 07:35
Hi @Nagendrababu61 ,
Please see [this](https://github.com/flutter/flutter/issues/57929) related issue. You seem to be on old version of Flutter. I'd suggest you to upgrade to latest stable or master and try again.

This seems to be a regression since it was fixed https://github.com/flutter/flutter/pull/57874.

Thanks.

**Comment by pedromassangocode** [comment] 2020-11-06 10:24
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2020-11-06 10:24 UTC

**Comment by lenin55** [comment] 2021-05-11 12:23
Oops; flutter has exited unexpectedly: "Invalid argument(s): Cannot find executable for /Users/lenin-8016/Downloads/flutter/bin/cache/artifacts/engine/android-arm-release/darwin-x64/gen_snapshot.".

**Comment by lenin55** [comment] 2021-05-11 12:24
how to resolve this ?
