### ISSUE TITLE
Make alertDialog grow to automatically fit ListView items - exception thrown

### ISSUE THREAD

**Issue by giaur500** [flutter/flutter#27881] opened 2019-02-13 13:17 UTC
Please look at this code:

 ```dart
showDialog(
        context: context,
        builder: (BuildContext context) {
          return AlertDialog(
            title: Text('Select city'),
            content: Column(
                mainAxisSize: MainAxisSize.min,
                children: <Widget>[
                  Container(
                    child: ListView.builder(
                      shrinkWrap: true,
                      itemCount: 2,
                      itemBuilder: (BuildContext context, int index) {
                        return ListTile(
                          title: Text("City"),
                          onTap: () => {},
                        );
                      },
                    ),
                  )
                ]
            ),
          );
        }
    );
```

From my understanding, because dialog content is `Column` with `mainAxisSize: MainAxisSize.min`, there should be known size that dialog uses as its `width` and `height` (similar to `wrap_content` in native Android). 

But I am getting exception:

```
RenderShrinkWrappingViewport does not support returning intrinsic dimensions.
I/flutter ( 6960): Calculating the intrinsic dimensions would require instantiating every child of the viewport, which
I/flutter ( 6960): defeats the point of viewports being lazy.
I/flutter ( 6960): If you are merely trying to shrink-wrap the viewport in the main axis direction, you should be able
I/flutter ( 6960): to achieve that effect by just giving the viewport loose constraints, without needing to measure its
I/flutter ( 6960): intrinsic dimensions.
```

**I don't want to set fixed width and height** - dialog width and height needs to be calculated depending from content. For example, if there is only one `ListView` row, dialog height should not include empty room below last `ListView` item. When many rows in there, dialog height must be as big as possible to show max lines without need to scroll.

As far as I understand, my code should work? Please confirm - I am doing something wrong, my requirement is impossible in Flutter or it's some kind of bug.

**Comment by zoechi** [comment] 2019-02-13 16:21
Did you try asking on StackOverflow?

**Comment by giaur500** [comment] 2019-02-14 20:49
Yes, I got some partial solution, code is complicated, but still does not meet my requirements fully.

We can assume what I'm asking for is currently not possible to do. Shouldn't we consider to make this specific thing supported without need to use any hacks? This is widely used with native Android and also very common use case.

**Comment by zoechi** [comment] 2019-02-15 07:57
Please post the link.

**Comment by giaur500** [comment] 2019-02-15 08:07
https://stackoverflow.com/questions/54669630/flutter-auto-size-alertdialog-to-fit-list-content/54670952

Nice try to get it working, however it looks more as a hack and did not worked properly on Android either for me. We need this officially supported with standard `AlertDialog` to make sure it works fine on all platforms.

**Comment by TahaTesser** [comment] 2020-04-29 12:43
duplicate of [#18108](https://github.com/flutter/flutter/issues/18108)

**Closed by TahaTesser** 2020-04-29 12:43 UTC
Labels: f: material design, framework
