### ISSUE TITLE
The Scrollbar() Widget in Flutter Web is not working as expected

### ISSUE THREAD

**Issue by Wissperwind** [flutter/flutter#75613] opened 2021-02-08 08:49 UTC
Hi,

Imagin you have a list of cards in a Scrollbar widget. You set show the scrollbar allways to true.
What does work as expected:
- If the browser window is large enough to display all cards, no scrollbar is shown.
- If I decrease the size of the window so that not all cards can be shown anymore, a scrollbar appears.

What does not work as expected:
- If I increase the size of the window, so that all cards can be shown again, the scrollbar does not dissapear again. But it should.
- If I use expandable cards, and I expand one so that not all cards can be shown anymore, no scrollbar appears. I had to resize the window to make it appear.

Here is my doctor -v output

<details>
<summary>flutter doctor -v</summary>

```bash
[√] Flutter (Channel beta, 1.26.0-17.3.pre, on Microsoft Windows [Version 10.0.19042.685], locale de-DE)
    • Flutter version 1.26.0-17.3.pre at C:\Users\akilian\Flutter SDK\flutter
    • Framework revision 4b50ca7f7f (3 days ago), 2021-02-04 19:44:27 -0800
    • Engine revision 2c527d6c7e
    • Dart version 2.12.0 (build 2.12.0-259.8.beta)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\akilian\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.52.1)
    • VS Code at C:\Users\akilian\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 88.0.4324.146
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 88.0.705.56
```
</details>

**Comment by pedromassangocode** [comment] 2021-02-08 09:00
Hi @Wissperwind 
Can you please provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
Thank you

**Comment by Wissperwind** [comment] 2021-02-15 12:44
Here it is:

```
import 'package:flutter/material.dart';


void main() {
  runApp(BugExample());
}

class BugExample extends StatelessWidget {

  Widget buildCard(BuildContext context, int index) {

    SizedBox sizedBox = SizedBox(width: 300, height: 200);

    //Create an expansion tile
    var expansionTile = ExpansionTile(title: Text(""),
        children: [sizedBox]);

    final expanderTheme = Theme.of(context).copyWith(dividerColor: Colors.white, hoverColor: Colors.white);
    var themedExp = Theme(data: expanderTheme, child: expansionTile);

    Column cardColumn = Column(children: [sizedBox, themedExp]);

    Card card = Card(child: cardColumn);

    return card;
  }


@override
  Widget build(BuildContext context) {


  List<Widget> cards = <Widget>[];


  var scrollController = ScrollController();

  //Build a nice ListView
  var listView = ListView.builder(
      itemCount: 3,
      itemBuilder: buildCard,
      controller: scrollController
  );


  //Default flutter scrollbar
  var scrollbar = Scrollbar(child: listView, isAlwaysShown: true, controller: scrollController);

  Container c = Container(child: scrollbar, constraints: BoxConstraints(maxWidth: 800));
  Row r = Row(children: [c]);


  Scaffold myScaffold = Scaffold(body: r);

  MaterialApp app = MaterialApp(
    title: 'Example',
    home: myScaffold,
  );

  return app;

}
}
```

**Comment by pedromassangocode** [comment] 2021-02-15 13:56
I can reproduce the issue on latest Master channel.

![gif](https://user-images.githubusercontent.com/67424416/107955330-f1127780-6f9d-11eb-849c-3843fe42f8a9.gif)


<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel master, 1.27.0-2.0.pre.101, on macOS 11.2 20D64 darwin-x64, locale en-AO)
    • Flutter version 1.27.0-2.0.pre.101 at /Users/pedromassango/Code/flutter_master
    • Framework revision c2ee916a5d (3 hours ago), 2021-02-14 23:01:04 -0500
    • Engine revision 1d537824d6
    • Dart version 2.13.0 (build 2.13.0-30.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 53.1.5
    • Dart plugin version 203.6912

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.2 20D64 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 88.0.4324.150

! Doctor found issues in 1 category.
```

</details>

**Comment by Piinks** [comment] 2021-05-17 22:26
This may be a duplicate of #67690, both may be resolved by #82687

**Comment by Ali-Fadaei** [comment] 2021-06-22 10:35
any update?

**Comment by AMuellerAtAHS** [comment] 2021-07-29 12:37
@xu-baolin 
Hi, did you successfully merge this into master? When will it be merged to stable?

**Comment by AMuellerAtAHS** [comment] 2021-07-29 12:37
Is there a workaround for stable release?

**Comment by xu-baolin** [comment] 2021-07-29 12:43
The patch is still in the final review, I believe it will be on the master soon, but it will take a while to push to the stable branch, I think it may take several weeks.

**Closed** 2021-07-30 20:19 UTC
Labels: P4, a: desktop, f: scrolling, found in release: 1.27, framework, has reproducible steps, platform-web, waiting for PR to land (fixed)
