### ISSUE TITLE
Investigate failures on `Windows_android flutter_gallery_win__compile` and `Windows_android hot_mode_dev_cycle_win__benchmark`

### ISSUE THREAD

**Issue by Renzo-Olivares** [flutter/flutter#115111] opened 2022-11-10 20:27 UTC
We are seeing consistent failures on `Windows_android flutter_gallery_win__compile` and `Windows_android hot_mode_dev_cycle_win__benchmark`. The tree is currently red.

```
Cannot run a document in the middle of a pipeline: C:\salt\Get-ChildItem.
At line:1 char:1
+ gci -Recurse cert: |Where-Object {$_.Subject -like "*GTS CA 1D4*" -or ...
+ ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (C:\salt\Get-ChildItem:String) [], RuntimeException
    + FullyQualifiedErrorId : CantActivateDocumentInPipeline
```

**Comment by Renzo-Olivares** [comment] 2022-11-10 20:37
Also seeing it on `Windows_android basic_material_app_win__compile`
https://ci.chromium.org/ui/p/flutter/builders/prod/Windows_android%20basic_material_app_win__compile/7148/overview

**Comment by Renzo-Olivares** [comment] 2022-11-10 20:44
`Windows_android windows_chrome_dev_mode`
https://ci.chromium.org/ui/p/flutter/builders/prod/Windows_android%20windows_chrome_dev_mode/7181/overview

**Comment by Renzo-Olivares** [comment] 2022-11-10 20:53
`Windows_android_complex_layout_win__compile`
https://ci.chromium.org/ui/p/flutter/builders/prod/Windows_android%20windows_chrome_dev_mode/7181/overview

**Comment by keyonghan** [comment] 2022-11-10 20:55
Duplicate of https://github.com/flutter/flutter/issues/114935

**Closed by keyonghan** 2022-11-10 20:55 UTC
Labels: team: infra, P0
