### ISSUE TITLE
TAB character rendered as "missing character" on CanvasKit and Windows

### ISSUE THREAD

**Issue by nt4f04uNd** [flutter/flutter#79153] opened 2021-03-26 18:08 UTC
in canvaskit `\t` isn't rendered if it goes before some text
on windows it's not rendered at all

<details>
<summary>screenshots</summary>

(don't be confused, i consciously attached screenshots from platforms where it's working fine)

| android | ios | windows | macos |
| ------------ | ------------ | ------------ | ------------ |
| ![android](https://user-images.githubusercontent.com/39104740/112673247-90683b80-8e75-11eb-8b1a-62ca28d1a0eb.png) | ![ios](https://user-images.githubusercontent.com/39104740/112673260-9231ff00-8e75-11eb-94f7-29cfe1441cd4.PNG) | ![windows](https://user-images.githubusercontent.com/39104740/112673251-9100d200-8e75-11eb-905f-ce5978a23b06.png) | ![macos](https://user-images.githubusercontent.com/39104740/112673262-9231ff00-8e75-11eb-98dd-ff53dc908f42.png)  |
| chrome_canvas_kit (windows) | chrome_html (windows) | chrome_canvas_kit (macos) | chrome_html (macos) |
| ![chrome_canvas_kit](https://user-images.githubusercontent.com/39104740/112673254-91996880-8e75-11eb-9b0d-4077738ee870.png) | ![chrome_html](https://user-images.githubusercontent.com/39104740/112673257-91996880-8e75-11eb-8546-253ba64e9cf0.png) | ![chrome_macos_canvas_kit](https://user-images.githubusercontent.com/39104740/112673264-92ca9580-8e75-11eb-9e17-4a55ecb03ee9.png) | ![chrome_macos_html](https://user-images.githubusercontent.com/39104740/112673266-92ca9580-8e75-11eb-93b6-086903c81829.png) |

</details>

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    const title = 'code sample';
    return MaterialApp(
      title: title,
      home: Scaffold(
        appBar: AppBar(
          title: Text(title),
        ),
        body: Home(),
      ),
    );
  }
}

class Home extends StatelessWidget {
  const Home({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Center(
      child: Column(
        mainAxisSize: MainAxisSize.min,
        children: [
          Text('\t\t\t Text \t\t\t'),
          Text.rich(
            TextSpan(
              children: [
                TextSpan(text: '\t\t\t'),
                TextSpan(text: ' RichText '),
                TextSpan(text: '\t\t\t'),
              ]
            )
          ),
        ],
      ),
    );
  }
}


```
</details>

<details>
<summary>flutter doctor -v (windows)</summary>

```
[√] Flutter (Channel master, 2.1.0-13.0.pre.288, on Microsoft Windows [Version 10.0.19041.867], locale ru-RU)
    • Flutter version 2.1.0-13.0.pre.288 at c:\dev\src\flutter
    • Framework revision e384ca7979 (80 minutes ago), 2021-03-26 17:34:03 +0100
    • Engine revision b5e15d055d
    • Dart version 2.13.0 (build 2.13.0-162.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)    
    • Android SDK at C:\Users\danya\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)   
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.7)       
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30621.155
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)   

[√] VS Code (version 1.54.3)
    • VS Code at C:\Users\danya\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.20.0

[√] Connected device (4 available)
    • Redmi Note 5 (mobile) • 40c9f14 • android-arm64  • Android 9 (API 28)
    • Windows (desktop)     • windows • windows-x64    • Microsoft Windows [Version 10.0.19041.867]
    • Chrome (web)          • chrome  • web-javascript • Google Chrome 89.0.4389.90
    • Edge (web)            • edge    • web-javascript • Microsoft Edge 89.0.774.57

• No issues found!
```
</details>

<details>
<summary>flutter doctor -v (macos)</summary>

```
[✓] Flutter (Channel master, 2.1.0-13.0.pre.288, on macOS 11.2.3 20D91 darwin-x64, locale ru-RU)
    • Flutter version 2.1.0-13.0.pre.288 at /Users/danya/dev/src/flutter
    • Framework revision e384ca7979 (78 minutes ago), 2021-03-26 17:34:03 +0100
    • Engine revision b5e15d055d
    • Dart version 2.13.0 (build 2.13.0-162.0.dev)

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] VS Code (version 1.54.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (3 available)
    • iPhone (mobile)          • 86b0b059a5210f26163e88a385ca2c87c7fc5115 • ios            • iOS 14.3
    • macOS (desktop)          • macos                                    • darwin-x64     • macOS 11.2.3 20D91 darwin-x64
    • Chrome (web)             • chrome                                   • web-javascript • Google Chrome 89.0.4389.90

! Doctor found issues in 2 categories.
```
</details>

**Comment by nt4f04uNd** [comment] 2021-03-26 18:13
for someone from the team fixing this: i saw a lot of issues whe some specific char is not rendered - why does it fail so often, is there some generic cause?

**Comment by au-top** [comment] 2021-03-28 12:57
#78974 
Maybe the two problems are caused by the same reasons

**Comment by TahaTesser** [comment] 2021-03-29 11:11
Hi @nt4f04uNd 
Thanks for filing the issue, I can reproduce it on Linux well on the web

 <details> 
<summary>preview</summary> 

| Canvaskit | HTML |
| --------------- | --------------- |
![image (1)](https://user-images.githubusercontent.com/48603081/112828534-7bb7bd80-9098-11eb-9e6b-13af685e27c4.png) | ![image (2)](https://user-images.githubusercontent.com/48603081/112828547-81ad9e80-9098-11eb-8dd1-fa1566c19eb9.png)




</details>

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel master, 2.1.0-13.0.pre.294, on Linux, locale en_IN)
    • Flutter version 2.1.0-13.0.pre.294 at /home/taha/Code/flutter_master
    • Framework revision a603714610 (24 hours ago), 2021-03-28 03:54:02 -0700
    • Engine revision b5e15d055d
    • Dart version 2.13.0 (build 2.13.0-162.0.dev)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/taha/Code/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /home/taha/Code/SDK
    • Java binary at: /home/taha/Code/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.
[✓] Chrome - develop for the web
    • Chrome at google-chrome
[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1
[✓] Android Studio (version 4.1)
    • Android Studio at /home/taha/Code/android-studio
    • Flutter plugin version 54.1.1
    • Dart plugin version 201.9335
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
[✓] VS Code (version 1.54.3)
    • VS Code at /usr/share/code
    • Flutter extension version 3.20.0
[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Linux
    • Chrome (web)    • chrome • web-javascript • Google Chrome 89.0.4389.90
• No issues found!
```
	
</details>

Thank you

**Comment by HansMuller** [comment] 2021-03-29 16:13
CC @gspencergoog

**Comment by gspencergoog** [comment] 2021-03-29 17:24
Looks like CanvasKit and Windows are having font problems for tab characters, either that, or we're somehow translating them into a Unicode character that isn't present on all fonts.

**Comment by gspencergoog** [comment] 2021-03-29 17:26
@nt4f04uNd or @TahaTesser can you give me an indication of the font family you used when rendering the samples?

**Comment by nt4f04uNd** [comment] 2021-03-29 17:52
i'm really not sure, but i believe they were:
1. windows desktop - `Segoe UI`
2. web - `Roboto` both on windows and macos

i think this is a better question for someone who knows about typography defaults
honestly, i think this should be documented

**Comment by nt4f04uNd** [comment] 2021-03-29 18:06
just tested another a font called Manrope, same results

<details>
<summary>screenshot</summary>

![image](https://user-images.githubusercontent.com/39104740/112879847-5cd61d00-90d2-11eb-9686-9d0b2db0c55a.png)
 </details>

**Comment by gspencergoog** [comment] 2021-03-29 19:57
OK, thanks.  There's not just one default: on some platforms, it depends on the settings that the user of that system/browser has set.

**Comment by hterkelsen** [comment] 2021-08-10 23:46
Skia bug filed here: https://bugs.chromium.org/p/skia/issues/detail?id=12334

**Comment by Hanprogramer** [comment] 2021-12-03 02:29
Could this be fixed temporarily by changing to some specific fonts?

**Comment by namangor04** [comment] 2022-01-11 16:04
Is there some/any progress on this ? Is there any way to presently change this by switching fonts ?

**Comment by Obezyan** [comment] 2022-03-11 14:32
Have the similar issue on Red OS Linux distribution based on Red Hat Linux. The Tab character is displayed as crossed out box if there is some symbol after it. 
![image](https://user-images.githubusercontent.com/43404660/157884608-86308622-d7ba-4774-968a-b4d4837c3f4f.png)

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.10.3, on RED OS MUROM (7.3.1) 5.15.10-1.el7.x86_64, locale en_US.UTF-8)
    • Flutter version 2.10.3 at /home/user/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (9 days ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[!] Connected device
    ! No devices available

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 4 categories.

```
</details>
<details>
<summary>/etc/os-release</summary>

```
NAME="RED OS"
VERSION="MUROM (7.3.1)"
PLATFORM_ID="platform:el7"
ID="redos"
ID_LIKE="rhel centos fedora"
VERSION_ID="7.3.1"
PRETTY_NAME="RED OS MUROM (7.3.1)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redos:redos:7"
HOME_URL="http://red-soft.ru/ru/main_products.html#redos"
BUG_REPORT_URL="http://redos-support.red-soft.ru"
EDITION="Standard"
```
</details>

**Comment by leecommamichael** [comment] 2022-04-17 23:12
I wanted to write a simple Notes app for Flutter Desktop, but this stopped me pretty quickly.

I cloned, built and debugged Skia on Windows to see what was going on, and was able to reproduce the issue with the HelloWorld Skia example. I've added some (hopefully not misleading) thoughts on the Skia bug report https://bugs.chromium.org/p/skia/issues/detail?id=12334

Is there a simple way to build Flutter which swaps to FreeType from DirectWrite on Windows? I heard Chromium uses FreeType on Windows, and it seems to do a good job of rendering tabs 😅

**Comment by maheshmnj** [comment] 2022-05-25 05:32
I am able to reproduce the issue on Web (Mac, Windows, Linux) and Windows Desktop and it works fine on Mobile platforms (Android and IOS).  

### Desktop
Windows  ❌           |  Linux ✅ |  MacOS ✅
:-------------------------:|:-------------------------:|:-------------------------: 
![Capture](https://user-images.githubusercontent.com/31410839/170035320-9293da3a-340e-402f-8934-314adcd43511.PNG) | ![Screenshot from 2022-05-24 17-40-15](https://user-images.githubusercontent.com/31410839/170036148-65cea2d0-c655-4a82-930d-4ff33f982bee.png) | <img width="760" alt="Screenshot 2022-05-24 at 5 39 59 PM" src="https://user-images.githubusercontent.com/31410839/170037449-50b96d28-6343-474a-8e07-d4b4e487be21.png">

### Web ❌

Windows             |  Linux |  MacOS
:-------------------------:|:-------------------------:|:-------------------------: 
![Capture_web](https://user-images.githubusercontent.com/31410839/170035354-a1db8bcc-0f64-41a7-87dd-779ad579f2a2.PNG) | ![Screenshot from 2022-05-24 17-42-30](https://user-images.githubusercontent.com/31410839/170036155-619626e9-87d9-4753-a2e5-5f2928953a92.png) | <img width="817" alt="Screenshot 2022-05-24 at 5 43 39 PM" src="https://user-images.githubusercontent.com/31410839/170036976-d16a555f-0a6e-463a-96d7-b906f6018326.png">

### Mobile ✅

IOS  | Android 
:-------------------------:|:-------------------------:
![Simulator Screen Shot - iPhone 12 Pro - 2022-05-24 at 18 10 14](https://user-images.githubusercontent.com/31410839/170036935-89d05691-755c-495a-8d8c-9c19cb2ca1aa.png)| ![Screenshot_1653394656](https://user-images.githubusercontent.com/31410839/170036087-cf2a91e6-9373-4f14-97ed-088759111ded.png)


|  `Android`  | `IOS` | `Web(Mac,Linux,Windows)` | `Windows Desktop` | `Linux Desktop` | `MacOS Desktop` |
| :---: |:---: |:---: |:---: |:---: |:---: |
|  ✅  |   ✅   | ❌   |  ❌    | ✅   |  ✅  | 

✅ : No Issue 
❌: Issue reproduced 

<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel stable, 3.0.1, on macOS 12.3 21E230 darwin-arm, locale en-IN)
    • Flutter version 3.0.1 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (3 days ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! CocoaPods 1.10.2 out of date (1.11.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin
        usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.66.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.40.0

[✓] Connected device (4 available)
    • Redmi K20 Pro (mobile) • 192.168.1.2:5555                     • android-arm64  • Android 11 (API 30)
    • iPhone 12 Pro (mobile) • 19FD0231-BFF0-441D-B584-AD94C4084525 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.3 21E230 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 101.0.4951.64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```
```
[✓] Flutter (Channel master, 3.1.0-0.0.pre.854, on macOS 12.3 21E230 darwin-arm, locale en-IN)
    • Flutter version 3.1.0-0.0.pre.854 at /Users/mahesh/Documents/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ec20ea80ad (35 hours ago), 2022-05-21 16:28:06 -0400
    • Engine revision 1bfe551d6b
    • Dart version 2.18.0 (build 2.18.0-142.0.dev)
    • DevTools version 2.13.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! CocoaPods 1.10.2 out of date (1.11.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin
        usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.66.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.40.0

[✓] Connected device (4 available)
    • Redmi K20 Pro (mobile) • 192.168.1.2:5555                     • android-arm64  • Android 11 (API 30)
    • iPhone 12 Pro (mobile) • 19FD0231-BFF0-441D-B584-AD94C4084525 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.3 21E230 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 101.0.4951.64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```
</details>


<details>
<summary>flutter doctor -v (windows)</summary>

```
[√] Flutter (Channel stable, 3.0.1, on Microsoft Windows [Version 10.0.19044.1706], locale en-IN)
    • Flutter version 3.0.1 at C:\flutter_sdk\stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (3 days ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

Checking Android licenses is taking an unexpectedly long time...[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\mahesh\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java  
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe       

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.4)      
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31727.386
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] VS Code (version 1.64.2)
    • VS Code at C:\Users\mahesh\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.40.0

[√] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 12 (API 31) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version
      10.0.19044.1706]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 101.0.4951.67
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 100.0.1185.50

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
```
[√] Flutter (Channel master, 3.1.0-0.0.pre.854, on Microsoft Windows [Version 10.0.19044.1706], locale en-IN)
    • Flutter version 3.1.0-0.0.pre.854 at C:\flutter_sdk\master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ec20ea80ad (30 hours ago), 2022-05-21 16:28:06 -0400
    • Engine revision 1bfe551d6b
    • Dart version 2.18.0 (build 2.18.0-142.0.dev)
    • DevTools version 2.13.1

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\mahesh\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31727.386
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] VS Code (version 1.64.2)
    • VS Code at C:\Users\mahesh\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.40.0

[√] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 12 (API 31) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version
      10.0.19044.1706]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 101.0.4951.67
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 100.0.1185.50

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>


<details>
<summary>flutter doctor -v (Linux)</summary>

```
[✓] Flutter (Channel stable, 3.0.1, on Ubuntu 20.04.4 LTS 5.13.0-30-generic, locale en_GB.UTF-8)
    • Flutter version 3.0.1 at /home/mahesh/Development/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (5 days ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /home/mahesh/Android/Sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /home/mahesh/Downloads/android-studio-2020.3.1.25-linux/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 2020.3)
    • Android Studio at /home/mahesh/Downloads/android-studio-2020.3.1.25-linux/android-studio
    • Flutter plugin version 67.1.2
    • Dart plugin version 212.5744
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.66.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.40.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 20.04.4 LTS 5.13.0-30-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 100.0.4896.75

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
```
[✓] Flutter (Channel master, 3.1.0-0.0.pre.799, on Ubuntu 20.04.4 LTS 5.13.0-30-generic, locale en_GB.UTF-8)
    • Flutter version 3.1.0-0.0.pre.799 at /home/mahesh/Development/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 348a2b4f2f (5 days ago), 2022-05-19 00:33:08 -0400
    • Engine revision 1965c92ea4
    • Dart version 2.18.0 (build 2.18.0-130.0.dev)
    • DevTools version 2.13.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /home/mahesh/Android/Sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /home/mahesh/Downloads/android-studio-2020.3.1.25-linux/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 2020.3)
    • Android Studio at /home/mahesh/Downloads/android-studio-2020.3.1.25-linux/android-studio
    • Flutter plugin version 67.1.2
    • Dart plugin version 212.5744
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.66.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.40.0

[✓] Connected device (3 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Linux (desktop)         • linux         • linux-x64      • Ubuntu 20.04.4 LTS 5.13.0-30-generic
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 100.0.4896.75

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by matt-zory** [comment] 2022-05-25 06:26
For those looking for a workaround, the only Unicode space I found that does not react improperly to TextAlign.justify is the Figure Space (U+2007) https://www.compart.com/en/unicode/U+2007
I search and replace the \t character with two Figure Spaces, then render that string.
`"\u{2007}\u{2007}"`

**Comment by jjoelson** [comment] 2022-07-25 14:18
I am seeing this same phenomenon using the Poppins font on a Pixel 4a Android device, so possibly this is not limited to CanvasKit and Windows.

**Comment by loic-sharma** [comment] 2022-07-27 17:22
@jjoelson Could you [switch to Flutter's `master` channel](https://docs.flutter.dev/development/tools/sdk/upgrading#switching-flutter-channels) and check if the issue still reproduces?

**Comment by aprzedecki** [comment] 2022-08-30 08:57
also reproduced that on Pixel4a with Android 13, `\t` character is rendered in a box with question mark

**Comment by loic-sharma** [comment] 2022-09-16 16:51
Hello, this is now fixed in [the `master` channel](https://docs.flutter.dev/development/tools/sdk/upgrading#switching-flutter-channels) for all platforms, including Windows and web. You can try this using:

```
flutter channel master
flutter upgrade
```

Please let me know if you can still reproduce this issue while on the `master` channel!

**Closed by loic-sharma** 2022-09-16 16:51 UTC
Labels: framework, engine, platform-windows, a: typography, platform-web, e: web_canvaskit, has reproducible steps, P3, found in release: 3.0, found in release: 3.1
