### ISSUE TITLE
PlatformException(Error performing get, Failed to get document because the client is offline., null

### ISSUE THREAD

**Issue by William-cpu** [flutter/flutter#61543] opened 2020-07-15 14:20 UTC
Hello. I tried Stackoverflow, Reddit(/r/flutterhelp), Slack(fluttercommunity.slack.com) and Flutterfire on GitHub (https://github.com/FirebaseExtended/flutterfire) but I still can't resolve this issue. I didn't get any response to my question. 

This is the last bug for an application that is ready for launch. And I don't know how to fix it. Hopefully someone can help.

## Steps to Reproduce

1. Run flutter build apk
2. Install app-release.apk on Android phone. This case Samsung S10
3. Open app and navigate to a view that has all items in a ListView
4. Close phone leaving the app open
5. Opening phone after a few minutes and trying to access an item from the list which navigates to the below widget the `client is offline` error appears. 

I'm using these plugins

```
cloud_firestore: ^0.13.7
firebase_auth: ^0.16.1
```

Widget
```

class Item extends StatefulWidget {
  Item({
    Key key,
    this.items,
    this.showAd,
    this.user,
    this.item,
    this.favorites,
  }) : super(key: key);
  final List<Imodel> items;
  final bool showAd;
  final UserModel user;
  final item;
  final List<FireFavorites> favorites;

  @override
  _ItemState createState() => _ItemState();
}

class _ItemState extends State<Item> {
  DateTime _lastViewed;
  bool _viewRequest = true;
  final _adWidget = AdMobWidget();
  bool _favoriteItem = false;

  @override
  void initState() {
    super.initState();

    final isFavorite = widget.favorites
        .where((element) => element.id == widget.item.documentID);

    if (isFavorite.length > 0) {
      _favoriteItem = true;
    }
  }

  @override
  Widget build(BuildContext context) {
    if (widget.showAd) {
      _adWidget.showAd();
    }

    final _headerStyle = TextStyle(fontWeight: FontWeight.bold);

    Widget _itemBody(item) {
      return ListView(
        children: <Widget>[
          Column(
            mainAxisAlignment: MainAxisAlignment.start,
            crossAxisAlignment: CrossAxisAlignment.start,
            children: <Widget>[
             ...
            ],
          ),
        ],
      );
    }

    _future() {
      return FutureBuilder<DocumentSnapshot>(
        future: Firestore.instance
            .collection('content')
            .document(widget.item.documentID)
            .get(source: Source.serverAndCache),
        builder:
            (BuildContext context, AsyncSnapshot<DocumentSnapshot> snapshot) {
          List<Widget> children;
          if (snapshot.hasData) {
            children = <Widget>[Expanded(child: _itemBody(snapshot.data))];
          } else if (snapshot.hasError) {
            children = <Widget>[
              Icon(
                Icons.error_outline,
                color: Colors.red,
                size: 60,
              ),
              Padding(
                padding: const EdgeInsets.only(top: 16),
                child: Text('Error: ${snapshot.error}'),
              )
            ];
          } else {
            children = <Widget>[
              SizedBox(
                child: CircularProgressIndicator(),
                width: 60,
                height: 60,
              ),
              const Padding(
                padding: EdgeInsets.only(top: 16),
                child: Text('Awaiting result...'),
              )
            ];
          }
          return Center(
            child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              crossAxisAlignment: CrossAxisAlignment.center,
              children: children,
            ),
          );
        },
      );
    }

    return Scaffold(
      resizeToAvoidBottomPadding: false,
      backgroundColor: Color(0xff2398C3),
      appBar: AppBar(
        elevation: 0,
        flexibleSpace: Container(
          decoration: BoxDecoration(
            gradient: LinearGradient(
              begin: Alignment.topCenter,
              end: Alignment.bottomCenter,
              colors: [Color(0xff042C5C), Color(0xff2398C3)],
            ),
          ),
        ),
        actions: <Widget>[
          BookmarkIcon(
            isFav: _favoriteItem,
            documentID: widget.item.documentID,
            userID: widget.user.uid,
          ),
          Padding(
            padding: EdgeInsets.only(
              right: 20.0,
            ),
            child: GestureDetector(
              onTap: () {},
              child: Icon(
                Icons.share,
                size: 18.0,
              ),
            ),
          ),
        ],
      ),
      body: Container(
        width: double.infinity,
        height: double.infinity,
        padding: EdgeInsets.only(
          top: 25.0,
          left: 30.0,
          right: 15.0,
        ),
        decoration: BoxDecoration(
          color: Colors.white,
          borderRadius: BorderRadius.only(
            topLeft: Radius.circular(32),
            topRight: Radius.circular(32),
          ),
        ),
        child: widget.item.documentID != null ? _future() : Container(),
      ),
    );
  }
}

```

**Expected results:** 

I expect to get the requested document from Firestore

**Actual results:** 
```
PlatformException(Error performing get, Failed to get document because the client is offline., null
```
<details>
  <summary>Logs</summary>

```
```

```
flutter analyze doesn't return anything related to the widget causing the error
```

```
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.5 19F101, locale en-RO)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[!] Android Studio (version 3.5)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.47.0)
[✓] Connected device (1 available)
```

</details>

**Comment by TahaTesser** [comment] 2020-07-15 15:49
Hi @William-cpu 
From what I can see, the issue is related to a FlutterFire plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by TahaTesser** 2020-07-15 15:49 UTC

**Comment by William-cpu** [comment] 2020-07-15 17:49
@TahaTesser I already did. You closed it there as well. Said it was a duplicate. I upvoted and commented on the duplicate, then someone else commented saying that he has the same problem. Since then, nothing. 

This is the duplicate. Maybe someone will take a look. https://github.com/FirebaseExtended/flutterfire/issues/2498
