### ISSUE TITLE
Flutter is not providing sufficient iOS Debug symbols for Sentry

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#12352] opened 2017-10-02 13:42 UTC
https://github.com/getsentry/sentry-cocoa/issues/205

**Comment by eseidelGoogle** [comment] 2017-10-02 13:43
I think https://github.com/getsentry/sentry-cocoa/issues/205#issuecomment-326953227 shows an example of what is desired.  @chinmaygarde or @cbracken likely knows how to fix.

**Comment by Hixie** [comment] 2017-10-03 20:54
Dupe of https://github.com/flutter/flutter/issues/12012

**Closed by Hixie** 2017-10-03 20:54 UTC
Labels: dev: tool, prod: engine, ⌺‬ platform-ios
