### ISSUE TITLE
[shared_preferences] Warnings after latest 0.5.4 release

### ISSUE THREAD

**Issue by Zazo032** [flutter/flutter#43254] opened 2019-10-22 09:18 UTC
## Steps to Reproduce

1. Upgrade `shared_preferences` to latest version (`0.5.4`)
2. Run an app that uses the plugin

Note that warnings are gone after second run.

**Target Platform:** Android
**Target OS version/browser:** 10
**Devices:** Pixel 3 XL

## Logs

```
11:11:40.837 4 info flutter.tools Running Gradle task 'assembleDebug'...
11:12:04.212 5 info flutter.tools C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences-0.5.4\android\src\main\java\io\flutter\plugins\sharedpreferences\MethodCallHandlerImpl.java:137: warning: [unchecked] unchecked cast
11:12:04.212 6 info flutter.tools       return (List<String>) stream.readObject();
11:12:04.213 7 info flutter.tools                                              ^
11:12:04.214 8 info flutter.tools   required: List<String>
11:12:04.214 9 info flutter.tools   found:    Object
11:12:04.214 10 info flutter.tools C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences-0.5.4\android\src\main\java\io\flutter\plugins\sharedpreferences\MethodCallHandlerImpl.java:182: warning: [unchecked] unchecked method invocation: constructor <init> in class ArrayList is applied to given types
11:12:04.214 11 info flutter.tools           List<String> listValue = new ArrayList<>((Set) value);
11:12:04.214 12 info flutter.tools                                    ^
11:12:04.214 13 info flutter.tools   required: Collection<? extends E>
11:12:04.214 14 info flutter.tools   found: Set
11:12:04.214 15 info flutter.tools   where E is a type-variable:
11:12:04.214 16 info flutter.tools     E extends Object declared in class ArrayList
11:12:04.215 17 info flutter.tools C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences-0.5.4\android\src\main\java\io\flutter\plugins\sharedpreferences\MethodCallHandlerImpl.java:182: warning: [unchecked] unchecked conversion
11:12:04.215 18 info flutter.tools           List<String> listValue = new ArrayList<>((Set) value);
11:12:04.215 19 info flutter.tools                                                    ^
11:12:04.215 20 info flutter.tools   required: Collection<? extends E>
11:12:04.215 21 info flutter.tools   found:    Set
11:12:04.215 22 info flutter.tools   where E is a type-variable:
11:12:04.215 23 info flutter.tools     E extends Object declared in class ArrayList
11:12:04.215 24 info flutter.tools C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences-0.5.4\android\src\main\java\io\flutter\plugins\sharedpreferences\MethodCallHandlerImpl.java:182: warning: [unchecked] unchecked conversion
11:12:04.215 25 info flutter.tools           List<String> listValue = new ArrayList<>((Set) value);
11:12:04.215 26 info flutter.tools                                    ^
11:12:04.215 27 info flutter.tools   required: List<String>
11:12:04.215 28 info flutter.tools   found:    ArrayList
11:12:04.274 29 info flutter.tools 4 warnings
11:12:30.410 30 info flutter.tools Built build\app\outputs\apk\debug\app-debug.apk.
```

## Flutter doctor

```
[√] Flutter (Channel master, v1.10.15-pre.202, on Microsoft Windows [VersiÃ³n 10.0.18362.418], locale es-ES)
    • Flutter version 1.10.15-pre.202 at C:\src\flutter
    • Framework revision 46ea99122b (5 hours ago), 2019-10-21 20:54:02 -0700
    • Engine revision 8882bf3c73
    • Dart version 2.6.0 (build 2.6.0-dev.8.0 a61c775db8)


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\crist\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including following components:
        MSBuild
        MSVC v142 - VS 2019 C++ x64/x86 build tools
       - If there are multiple versions, install the latest one
        Windows 10 SDK (10.0.17763.0)

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 40.2.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] Connected device (2 available)
    • Pixel 3 XL • 89PY09NNV • android-arm64 • Android 10 (API 29)
    • Windows    • Windows   • windows-x64   • Microsoft Windows [VersiÃ³n 10.0.18362.418]
```

**Comment by grandpa-guru** [comment] 2019-10-22 11:44
```
C:\Programs\Flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences-0.5.4\android\src\main\java\io\flutter\plugins\sharedpreferences\MethodCallHandlerImpl.java:137: warning: [unchecked] unchecked cast
      return (List<String>) stream.readObject();
                                             ^
  required: List<String>
  found:    Object
C:\Programs\Flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences-0.5.4\android\src\main\java\io\flutter\plugins\sharedpreferences\MethodCallHandlerImpl.java:182: warning: [unchecked] unchecked method invocation: constructor <init> in class ArrayList is applied to given types
          List<String> listValue = new ArrayList<>((Set) value);
                                   ^
  required: Collection<? extends E>
  found: Set
  where E is a type-variable:
    E extends Object declared in class ArrayList
C:\Programs\Flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences-0.5.4\android\src\main\java\io\flutter\plugins\sharedpreferences\MethodCallHandlerImpl.java:182: warning: [unchecked] unchecked conversion
          List<String> listValue = new ArrayList<>((Set) value);
                                                   ^
  required: Collection<? extends E>
  found:    Set
  where E is a type-variable:
    E extends Object declared in class ArrayList
C:\Programs\Flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences-0.5.4\android\src\main\java\io\flutter\plugins\sharedpreferences\MethodCallHandlerImpl.java:182: warning: [unchecked] unchecked conversion
          List<String> listValue = new ArrayList<>((Set) value);
                                   ^
  required: List<String>
  found:    ArrayList
4 warnings

```

**Comment by dibusch** [comment] 2019-10-22 14:04
The same happens here.
shared_preferences: 0.5.4 not really tested ????

I solved it by myself:
In your file:
C:\Programs\Flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences-0.5.4\android\src\main\java\io\flutter\plugins\sharedpreferences\MethodCallHandlerImpl.java

Add this:
 `  private List<String> decodeList(String encodedList) throws IOException {
    ObjectInputStream stream = null;
    try {
      stream = new ObjectInputStream(new ByteArrayInputStream(Base64.decode(encodedList, 0)));
      return (List<String>) stream.readObject();
    } catch (ClassNotFoundException e) {
      throw new IOException(e);
    } catch (ClassCastException e){
      throw new IOException(e);
    } finally{
      if (stream != null) {
        stream.close();
      }
    }
  }`

`catch (ClassCastException e){
      throw new IOException(e);
    } `

**Comment by fauzipadlaw** [comment] 2019-10-24 04:29
@dibusch i added but warnings still occur 

```
private List<String> decodeList(String encodedList) throws IOException {
    ObjectInputStream stream = null;
    try {
      stream = new ObjectInputStream(new ByteArrayInputStream(Base64.decode(encodedList, 0)));
      return (List<String>) stream.readObject();
    } catch (ClassNotFoundException e) {
      throw new IOException(e);
    } catch (ClassCastException e) {
      throw new IOException(e);
    }
    finally {
      if (stream != null) {
        stream.close();
      }
    }
  }
```

warnings:
```
C:\Users\fauzi\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\shared_preferences-0.5.4\android\src\main\java\io\flutter\plugins\sharedpreferences\MethodCallHandlerImpl.java:185: warning: [unchecked] unchecked method invocation: constructor <init> in class ArrayList is applied to given types
          List<String> listValue = new ArrayList<>((Set) value);
                                   ^
  required: Collection<? extends E>
  found: Set
  where E is a type-variable:
    E extends Object declared in class ArrayList
C:\Users\fauzi\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\shared_preferences-0.5.4\android\src\main\java\io\flutter\plugins\sharedpreferences\MethodCallHandlerImpl.java:185: warning: [unchecked] unchecked conversion
          List<String> listValue = new ArrayList<>((Set) value);
                                                   ^
  required: Collection<? extends E>
  found:    Set
  where E is a type-variable:
    E extends Object declared in class ArrayList
C:\Users\fauzi\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\shared_preferences-0.5.4\android\src\main\java\io\flutter\plugins\sharedpreferences\MethodCallHandlerImpl.java:185: warning: [unchecked] unchecked conversion
          List<String> listValue = new ArrayList<>((Set) value);
                                   ^
  required: List<String>
  found:    ArrayList
4 warnings
```

**Comment by fauzipadlaw** [comment] 2019-10-24 10:04
@tbm98 yeah, me as well

**Comment by dibusch** [comment] 2019-10-24 15:12
@fauzipadlaw try this:
    List<String> listValue = new ArrayList<>((Set<String>) value);

**Comment by nebnhoj** [comment] 2019-10-25 09:13
I was experiencing this issue after updating the library.

**Comment by workerbee22** [comment] 2019-10-25 23:53
Me too.

**Comment by rakib205** [comment] 2019-10-26 12:16
Use **shared_preferences: ^0.5.3+5** for now. This is ok for me.

**Comment by Zazo032** [comment] 2019-10-28 10:13
Latest version `0.5.4+1` is giving one extra warning:

```
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences-0.5.4+1\android\src\main\java\io\flutter\plugins\sharedpreferences\MethodCallHandlerImpl.java:137: warning: [unchecked] unchecked cast
      return (List<String>) stream.readObject();
                                             ^
  required: List<String>
  found:    Object
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences-0.5.4+1\android\src\main\java\io\flutter\plugins\sharedpreferences\MethodCallHandlerImpl.java:182: warning: [unchecked] unchecked method invocation: constructor <init> in class ArrayList is applie
d to given types
          List<String> listValue = new ArrayList<>((Set) value);
                                   ^
  required: Collection<? extends E>
  found: Set
  where E is a type-variable:
    E extends Object declared in class ArrayList
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences-0.5.4+1\android\src\main\java\io\flutter\plugins\sharedpreferences\MethodCallHandlerImpl.java:182: warning: [unchecked] unchecked conversion
          List<String> listValue = new ArrayList<>((Set) value);
                                                   ^
  required: Collection<? extends E>
  found:    Set
  where E is a type-variable:
    E extends Object declared in class ArrayList
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences-0.5.4+1\android\src\main\java\io\flutter\plugins\sharedpreferences\MethodCallHandlerImpl.java:182: warning: [unchecked] unchecked conversion
          List<String> listValue = new ArrayList<>((Set) value);
                                   ^
  required: List<String>
  found:    ArrayList
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences-0.5.4+1\android\src\main\java\io\flutter\plugins\sharedpreferences\SharedPreferencesPlugin.java:26: warning: [deprecation] getFlutterEngine() in FlutterPluginBinding has been deprecated
    setupChannel(binding.getFlutterEngine().getDartExecutor(), binding.getApplicationContext());
                        ^
5 warnings
```

**Comment by LampeMW** [comment] 2019-10-28 15:19
Also having this issue after upgrading to 0.5.4+1.

**Comment by zigang93** [comment] 2019-10-28 19:04
Same issue here

**Comment by cyanglaz** [comment] 2019-10-28 22:45
This is fixed in https://github.com/flutter/plugins/pull/2241. Closing the issue.

**Closed by cyanglaz** 2019-10-28 22:45 UTC
Labels: customer: crowd, p: first party, p: shared_preferences, plugin, severe: regression, ▣ platform-android

**Comment by Zazo032** [comment] 2019-10-29 09:50
That version still throws 1 warning:

```
10:49:03.450 5 info flutter.tools Note: Some input files use unchecked or unsafe operations.
10:49:03.450 6 info flutter.tools 
10:49:03.450 7 info flutter.tools Note: Recompile with -Xlint:unchecked for details.
10:49:03.451 8 info flutter.tools 
10:49:03.823 9 info flutter.tools C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences-0.5.4+3\android\src\main\java\io\flutter\plugins\sharedpreferences\SharedPreferencesPlugin.java:25: warning: [deprecation] getFlutterEngine() in FlutterPluginBinding has been deprecated
10:49:03.823 10 info flutter.tools     setupChannel(binding.getFlutterEngine().getDartExecutor(), binding.getApplicationContext());
10:49:03.824 11 info flutter.tools                         ^
10:49:03.824 12 info flutter.tools 
10:49:03.824 13 info flutter.tools 1 warning
```

**Comment by fauzipadlaw** [comment] 2019-10-29 10:11
@Zazo032 did you try `shared_preferences: ^0.5.4+3`?

**Comment by Zazo032** [comment] 2019-10-29 10:28
Yes, you can see it in the logs. I'm using latest master, BTW.

**Comment by nihalreddy33** [comment] 2019-11-07 01:22
@fauzipadlaw even I am facing the same error with shared_preferences: ^0.5.4+3

**Comment by godlessturtle** [comment] 2019-11-11 12:05
still getting error
 getFlutterEngine() in FlutterPluginBinding has been deprecated
    setupChannel(binding.getFlutterEngine().getDartExecutor(), binding.getApplicationContext());                   
                        ^

**Comment by cyanglaz** [comment] 2019-11-14 05:03
> That version still throws 1 warning:
> 
> ```
> 10:49:03.450 5 info flutter.tools Note: Some input files use unchecked or unsafe operations.
> 10:49:03.450 6 info flutter.tools 
> 10:49:03.450 7 info flutter.tools Note: Recompile with -Xlint:unchecked for details.
> 10:49:03.451 8 info flutter.tools 
> 10:49:03.823 9 info flutter.tools C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences-0.5.4+3\android\src\main\java\io\flutter\plugins\sharedpreferences\SharedPreferencesPlugin.java:25: warning: [deprecation] getFlutterEngine() in FlutterPluginBinding has been deprecated
> 10:49:03.823 10 info flutter.tools     setupChannel(binding.getFlutterEngine().getDartExecutor(), binding.getApplicationContext());
> 10:49:03.824 11 info flutter.tools                         ^
> 10:49:03.824 12 info flutter.tools 
> 10:49:03.824 13 info flutter.tools 1 warning
> ```

@Zazo032 This warning is different from the ones in the original post. It is caused by a deprecation of one of our Android embedding API. It shouldn't prevent you from using the plugin.
If you are interested to have this warning fixed soon. Please open another issue specifically for this warning and we will triage it.

**Comment by Zazo032** [comment] 2019-11-14 07:28
Thanks @cyanglaz! Will leave it closed as there's already an issue open for that: https://github.com/flutter/flutter/issues/44569
