### ISSUE TITLE
FadeTransition cannot animate to 0 opacity smoothly

### ISSUE THREAD

**Issue by nt4f04uNd** [flutter/flutter#95300] opened 2021-12-15 01:53 UTC
## Steps to Reproduce

1. Execute `flutter run` on the code sample
2. Press the FloatingActionButton

**Expected results:** Regular transition

**Actual results:** The animating back layer cannot reach 0 opacity smoothly, it stays there almost fully transperent, until the animation reaches the end, and then it sort of snaps out

The code sample uses the `animations` package, but I'm still filing this issue for FadeTransition, because animations package doesn't seem to have changed in the recent few months and I noticed this when I built my app with new version of Flutter

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:animations/animations.dart';
import 'package:flutter/scheduler.dart';

void main() {
  runApp(App());
}

class App extends StatefulWidget {
  @override
  State<App> createState() => _AppState();
}

class _AppState extends State<App> {
  int index = 0;
  void _handleTap() {
    setState(() {
      index += 1;
      if (index == 2) {
        index = 0;
      }
    });
  }

  @override
  Widget build(BuildContext context) {
    final views = [
      Container(key: const ValueKey('1'), color: Colors.black),
      Container(
        key: const ValueKey('2'),
        color: Colors.blue,
        child: const Center(
          child: Text(
            "I'M STILL HERE!",
            style: TextStyle(fontSize: 50, color: Colors.white),
          ),
        ),
      ),
    ];
    timeDilation = 5;
    return MaterialApp(
      title: 'App',
      home: Scaffold(
        floatingActionButton: FloatingActionButton(onPressed: _handleTap),
        body: PageTransitionSwitcher(
          duration: const Duration(milliseconds: 300),
          reverse: true,
          transitionBuilder: (child, animation, secondaryAnimation) {
            return SharedAxisTransition(
              transitionType: SharedAxisTransitionType.horizontal,
              animation: animation,
              secondaryAnimation: secondaryAnimation,
              fillColor: Colors.transparent,
              child: child,
            );
          },
          child: views[index],
        ),
      ),
    );
  }
}
```

</details>

<details>
  <summary>Logs</summary>

```
[√] Flutter (Channel refresh, 2.6.0-12.0.pre.1015, on Microsoft Windows [Version 10.0.19041.1348], locale ru-RU)
    • Flutter version 2.6.0-12.0.pre.1015 at C:\dev\src\flutter
    • Upstream repository git@github.com:nt4f04und/flutter.git
    • FLUTTER_GIT_URL = git@github.com:nt4f04und/flutter.git
    • Framework revision 13fa98cf4e (27 hours ago), 2021-12-14 01:27:02 +0300
    • Engine revision f16c96c31f
    • Dart version 2.16.0 (build 2.16.0-85.0.dev)
    • DevTools version 2.9.1

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\danya\AppData\Local\Android\sdk
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.7)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30621.155
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 4.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Community Edition (version 2020.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.3.3
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code (version 1.63.1)
    • VS Code at C:\Users\danya\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.29.0

[√] Connected device (4 available)
    • Redmi Note 5 (mobile) • 40c9f14 • android-arm64  • Android 9 (API 28)
    • Windows (desktop)     • windows • windows-x64    • Microsoft Windows [Version 10.0.19041.1348]
    • Chrome (web)          • chrome  • web-javascript • Google Chrome 96.0.4664.93
    • Edge (web)            • edge    • web-javascript • Microsoft Edge 96.0.1054.53

! Doctor found issues in 1 category.
```

</details>

<details>
<summary>Video</summary>

https://user-images.githubusercontent.com/39104740/146108338-50b5a3d1-0165-443f-af8b-92874a1af7b3.mp4
</details>

**Comment by nt4f04uNd** [comment] 2021-12-15 02:09
Just checked into 2.5.3 and the problem has gone

/cc @flar

<details>
<summary>video (2.5.3) - ✔ no bug</summary>

https://user-images.githubusercontent.com/39104740/146109942-1380c8b0-8432-4e62-8ec4-8a8231972ba0.mp4

</details>

<details>
<summary>flutter doctor -v (2.5.3)</summary>

```
[√] Flutter (Channel unknown, 2.5.3, on Microsoft Windows [Version 10.0.19041.1348], locale ru-RU)
    • Flutter version 2.5.3 at C:\dev\src\flutter
    • Upstream repository unknown
    • FLUTTER_GIT_URL = git@github.com:nt4f04und/flutter.git
    • Framework revision 18116933e7 (9 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\danya\AppData\Local\Android\sdk
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.7)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30621.155
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 4.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Community Edition (version 2020.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.3.3
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code (version 1.63.1)
    • VS Code at C:\Users\danya\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.29.0

[√] Connected device (4 available)
    • Redmi Note 5 (mobile) • 40c9f14 • android-arm64  • Android 9 (API 28)
    • Windows (desktop)     • windows • windows-x64    • Microsoft Windows [Version 10.0.19041.1348]
    • Chrome (web)          • chrome  • web-javascript • Google Chrome 96.0.4664.93
    • Edge (web)            • edge    • web-javascript • Microsoft Edge 96.0.1054.53

! Doctor found issues in 1 category.
```
</details>

<details>
<summary>video (2.8.0) - 🛑 bug exists</summary>

https://user-images.githubusercontent.com/39104740/146110058-6864a082-2931-4da5-a153-135dfadea49e.mp4

</details>

<details>
<summary>flutter doctor -v (2.8.0)</summary>

```
[√] Flutter (Channel stable, 2.8.0, on Microsoft Windows [Version 10.0.19041.1348], locale ru-RU)
    • Flutter version 2.8.0 at C:\dev\src\flutter
    • Upstream repository git@github.com:flutter/flutter.git
    • FLUTTER_GIT_URL = git@github.com:nt4f04und/flutter.git
    • Framework revision cf44000065 (6 days ago), 2021-12-08 14:06:50 -0800
    • Engine revision 40a99c5951
    • Dart version 2.15.0

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\danya\AppData\Local\Android\sdk
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.7)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30621.155
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 4.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Community Edition (version 2020.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.3.3
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code (version 1.63.1)
    • VS Code at C:\Users\danya\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.29.0

[√] Connected device (4 available)
    • Redmi Note 5 (mobile) • 40c9f14 • android-arm64  • Android 9 (API 28)
    • Windows (desktop)     • windows • windows-x64    • Microsoft Windows [Version 10.0.19041.1348]
    • Chrome (web)          • chrome  • web-javascript • Google Chrome 96.0.4664.93
    • Edge (web)            • edge    • web-javascript • Microsoft Edge 96.0.1054.53

! Doctor found issues in 1 category.
```
</details>

**Comment by maheshmnj** [comment] 2021-12-15 08:18
Proabably duplicate of https://github.com/flutter/flutter/issues/95270

**Comment by mamuseferha** [comment] 2021-12-15 08:42
Hi @nt4f04uNd 
I see there's an open issue addressing the case you described https://github.com/flutter/flutter/issues/95270.
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by mamuseferha** 2021-12-15 08:42 UTC
Labels: in triage
