### ISSUE TITLE
Build fails because GeneratedPluginRegistrant.m is missing

### ISSUE THREAD

**Issue by HugoSart** [flutter/flutter#84810] opened 2021-06-17 21:15 UTC
My build stopped working after I replaced my .gitginore file with a proper one.
All recent .gitignore I found on the web has this line in it:

`**/ios/Runner/GeneratedPluginRegistrant.*`

So, I assume that the GeneratedPluginRegistrant.{m, h} files should not be included in version control.
The problem is that, without these files, the `flutter build ios --release --no-codesign` fails with the following error:
```
3 warnings generated.
error: Build input file cannot be found: '/Users/vagrant/git/ios/Runner/GeneratedPluginRegistrant.m' (in target 'Runner' from project 'Runner')
note: Using new build system
note: Building targets in parallel
note: Planning build
note: Constructing build description
warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.4.99. (in target 'AppAuth' from project 'Pods')
warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.4.99. (in target 'Toast' from project 'Pods')
warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.4.99. (in target 'Reachability' from project 'Pods')
warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.4.99. (in target 'Flutter' from project 'Pods')
warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.4.99. (in target 'GoogleSignIn' from project 'Pods')
warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.4.99. (in target 'AppsFlyerFramework' from project 'Pods')
```
This issue is happening since I upgraded my Flutter SDK from 1.26 to 2.2.2.
If I comment the .gitgnore line mentioned above, the build works, although it looks like it's not the proper solution.
I already tested it on a MacOS and Bitrise CI, both build fails with the same error.

Flutter info (log generated from Bitrise CI):
```
Flutter 2.2.2 • channel unknown • unknown source
Framework • revision d79295af24 (6 days ago) • 2021-06-11 08:56:01 -0700
Engine • revision 91c9fc8fe0
Tools • Dart 2.13.3
```

**Comment by TahaTesser** [comment] 2021-06-18 11:08
Hi @HugoSart 
`GeneratedPluginRegistrant` is not required when building or running the app

First of all, it is already ignored by default inside `gitignore` file in `your/ios` folder
``
Runner/GeneratedPluginRegistrant.*
```

Nevertheless when I deleted `GeneratedPluginRegistrant` files (both of them), run the `flutter build ios --release --no-codesign` works fine, these files are generated as expected. Then I added `**/ios/Runner/GeneratedPluginRegistrant.*` Flutter app-level `gitignore` and pushed the changes to Codemagic for testing, App still builds fine.


Since this doesn't; reproduce locally and CI/CD is out of the Fluter repository's scope.
If you run into issues without these files locally, please let me know 


Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-06-18 11:08 UTC
Labels: in triage

**Comment by HugoSart** [comment] 2021-06-18 20:28
@TahaTesser as I said, on my local MacOS this issue also happens. If I delete the GeneratedPluginRegistrant files and run `flutter build ios --release --no-codesign` the same error happens, the files are not generated. It was working without the .gitgnore change because these two files were already versioned from older commits and not because the build is working locally. 

So, I still can't build the app either locally or in CI.

**Comment by HugoSart** [comment] 2021-06-22 18:39
@TahaTesser I just found that this issue is also happening on Android. If I add the class GeneratedPluginRegistrant in .gitgnore, the build works but then when I deploy my app to Play Store I just get a black screen and the following log:
```
2021-06-22 15:33:02.710 1611-2905/? I/ActivityTaskManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=me.itini.travelassistant/io.flutter.embedding.android.FlutterActivity bnds=[54,1136][222,1304] (has extras)} from uid 10076
2021-06-22 15:33:02.834 1611-1748/? I/ActivityManager: Start proc 5858:me.itini.travelassistant/u0a454 for activity {me.itini.travelassistant/io.flutter.embedding.android.FlutterActivity} caller=com.mi.android.globallauncher
2021-06-22 15:33:02.995 5858-5858/? E/GeneratedPluginsRegister: Tried to automatically register plugins with FlutterEngine (io.flutter.embedding.engine.FlutterEngine@f34c5e3) but could not find or invoke the GeneratedPluginRegistrant.
2021-06-22 15:33:02.995 5858-5858/? E/GeneratedPluginsRegister: Received exception while registering
    java.lang.ClassNotFoundException: io.flutter.plugins.GeneratedPluginRegistrant
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:454)
        at java.lang.Class.forName(Class.java:379)
        at io.flutter.embedding.engine.plugins.util.GeneratedPluginRegister.registerGeneratedPlugins(Unknown Source:2)
        at io.flutter.embedding.android.FlutterActivity.configureFlutterEngine(Unknown Source:9)
        at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(Unknown Source:58)
        at io.flutter.embedding.android.FlutterActivity.onCreate(Unknown Source:13)
        at android.app.Activity.performCreate(Activity.java:7916)
        at android.app.Activity.performCreate(Activity.java:7903)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3288)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3462)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2049)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7565)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
     Caused by: java.lang.ClassNotFoundException: io.flutter.plugins.GeneratedPluginRegistrant
        at java.lang.Class.classForName(Native Method) 
        at java.lang.Class.forName(Class.java:454) 
        at java.lang.Class.forName(Class.java:379) 
        at io.flutter.embedding.engine.plugins.util.GeneratedPluginRegister.registerGeneratedPlugins(Unknown Source:2) 
        at io.flutter.embedding.android.FlutterActivity.configureFlutterEngine(Unknown Source:9) 
        at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(Unknown Source:58) 
        at io.flutter.embedding.android.FlutterActivity.onCreate(Unknown Source:13) 
        at android.app.Activity.performCreate(Activity.java:7916) 
        at android.app.Activity.performCreate(Activity.java:7903) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3288) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3462) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2049) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:224) 
        at android.app.ActivityThread.main(ActivityThread.java:7565) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950) 
2021-06-22 15:33:02.995 5858-5858/? D/ForceDarkHelper: updateByCheckExcludeList: pkg: me.itini.travelassistant activity: io.flutter.embedding.android.FlutterActivity@8fc1a12
2021-06-22 15:33:03.000 5858-5858/? D/ForceDarkHelper: updateByCheckExcludeList: pkg: me.itini.travelassistant activity: io.flutter.embedding.android.FlutterActivity@8fc1a12
2021-06-22 15:33:03.000 5858-5858/? D/ForceDarkHelper: updateByCheckExcludeList: pkg: me.itini.travelassistant activity: io.flutter.embedding.android.FlutterActivity@8fc1a12
2021-06-22 15:33:03.007 5858-5858/? D/ForceDarkHelper: updateByCheckExcludeList: pkg: me.itini.travelassistant activity: io.flutter.embedding.android.FlutterActivity@8fc1a12
2021-06-22 15:33:03.022 5858-5858/? D/ForceDarkHelper: updateByCheckExcludeList: pkg: me.itini.travelassistant activity: io.flutter.embedding.android.FlutterActivity@8fc1a12
2021-06-22 15:33:03.184 5858-5916/? E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(213)] Unhandled Exception: MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences)
2021-06-22 15:33:03.198 1611-1708/? I/Timeline: Timeline: Activity_windows_visible id: ActivityRecord{d563e28 u0 me.itini.travelassistant/io.flutter.embedding.android.FlutterActivity t1755} time:349887927
2021-06-22 15:33:03.205 1611-1742/? I/ActivityTaskManager: Displayed me.itini.travelassistant/io.flutter.embedding.android.FlutterActivity: +489ms
```

**Comment by HugoSart** [comment] 2021-06-22 20:07
@TahaTesser I think this issue should be re-opened. I tried several solutions and the only workaround so far was to commit the GeneratedPluginRegistrant files.

**Comment by HugoSart** [comment] 2021-06-23 13:03
I finally found the problem. First I investigated the source code of flutter_tools to check if any of the above conditions were true, and I found out that my project was being processed as a plugin because I had the plugin: tag in my pubspec.yml. I have no idea why I put this in my pubspec.
