### ISSUE TITLE
Launching lib\main.dart on Chrome in debug mode , [tool_crash] SocketException: The remote computer refused the network connection. 

### ISSUE THREAD

**Issue by mbuenoc** [flutter/flutter#153664] opened 2024-08-18 19:45 UTC
## Command
```sh
flutter run --release
```

## Steps to Reproduce
1. ... flutter pub get
2. ...Try `flutter pub outdated` 
3. ...Try `flutter pub upgrade`
4.  flutter pub run flutter_launcher_icons:main
Deprecated. Use `dart run` instead.
5. flutter run --release
6. Terminal show...  Launching lib\main.dart on Chrome in release mode...
Warning: In index.html:51: Local variable for "serviceWorkerVersion" is deprecated. Use "{{flutter_service_worker_version}}"template token instead. See https://docs.flutter.dev/platform-integration/web/initialization for more details.
Warning: In index.html:66: "FlutterLoader.loadEntrypoint" is deprecated. Use "FlutterLoader.load" instead. See
https://docs.flutter.dev/platform-integration/web/initialization for more details.

## Logs
SocketException: The remote computer refused the network connection.
, OS Error: The remote computer refused the network connection.
, errno = 1225
```console
#0      _NativeSocket.startConnect (dart:io-patch/socket_patch.dart:721:35)
#1      _RawSocket.startConnect (dart:io-patch/socket_patch.dart:1920:26)
#2      RawSocket.startConnect (dart:io-patch/socket_patch.dart:27:23)
#3      Socket._startConnect (dart:io-patch/socket_patch.dart:2144:22)
#4      Socket.startConnect (dart:io/socket.dart:825:21)
#5      _ConnectionTarget.connect (dart:_http/http_impl.dart:2491:20)
#6      _HttpClient._getConnection.connect (dart:_http/http_impl.dart:2930:12)
#7      _HttpClient._getConnection (dart:_http/http_impl.dart:2935:12)
#8      _HttpClient._openUrl (dart:_http/http_impl.dart:2790:12)
#9      _HttpClient.getUrl (dart:_http/http_impl.dart:2632:48)
#10     ChromeConnection.getUrl (package:webkit_inspection_protocol/webkit_inspection_protocol.dart:108:33)
#11     ChromeConnection.getTabs (package:webkit_inspection_protocol/webkit_inspection_protocol.dart:53:26)
#12     ChromeConnection.getTab (package:webkit_inspection_protocol/webkit_inspection_protocol.dart:90:31)
#13     Chromium.close (package:flutter_tools/src/web/chrome.dart:510:53)
#14     ChromiumDevice.stopApp (package:flutter_tools/src/web/web_device.dart:164:20)
#15     ResidentWebRunner._cleanup (package:flutter_tools/src/isolated/resident_web_runner.dart:203:27)
<asynchronous suspension>
#16     ResidentWebRunner.cleanupAfterSignal (package:flutter_tools/src/isolated/resident_web_runner.dart:186:5)
<asynchronous suspension>
#17     TerminalHandler._cleanUp (package:flutter_tools/src/resident_runner.dart:1872:5)
<asynchronous suspension>
#18     TerminalHandler.processTerminalInput (package:flutter_tools/src/resident_runner.dart:1843:7)
<asynchronous suspension>
```
```console
[32m[✓][39m Flutter (Channel stable, 3.24.0, on Microsoft Windows [Version 10.0.19045.4780], locale en-US)
    [32m•[39m Flutter version 3.24.0 on channel stable at C:\flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision 80c2e84975 (3 weeks ago), 2024-07-30 23:06:49 +0700
    [32m•[39m Engine revision b8800d88be
    [32m•[39m Dart version 3.5.0
    [32m•[39m DevTools version 2.37.2

[32m[✓][39m Windows Version (Installed version of Windows is version 10 or higher)

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    [32m•[39m Android SDK at C:\Users\Marisol\AppData\Local\Android\sdk
    [32m•[39m Platform android-34, build-tools 35.0.0
    [32m•[39m Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.11+0--11852314)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[32m[✓][39m Visual Studio - develop Windows apps (Visual Studio Community 2019 16.8.4)
    [32m•[39m Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    [32m•[39m Visual Studio Community 2019 version 16.8.30907.101
    [32m•[39m Windows 10 SDK version 10.0.18362.0

[32m[✓][39m Android Studio (version 2024.1)
    [32m•[39m Android Studio at C:\Program Files\Android\Android Studio
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.11+0--11852314)

[32m[✓][39m VS Code (version 1.92.2)
    [32m•[39m VS Code at C:\Users\Marisol\AppData\Local\Programs\Microsoft VS Code
    [32m•[39m Flutter extension version 3.94.0

[32m[✓][39m Connected device (3 available)
    [32m•[39m Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19045.4780]
    [32m•[39m Chrome (web)      • chrome  • web-javascript • Google Chrome 127.0.6533.120
    [32m•[39m Edge (web)        • edge    • web-javascript • Microsoft Edge 127.0.2651.105

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[32m•[39m No issues found!

```

## Flutter Application Metadata
**Type**: malformed
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: null
**Creation framework version**: null
### Plugins
cloud_firestore-5.2.1
cloud_firestore_web-4.1.1
file_picker-8.0.7
file_selector_linux-0.9.2+1
file_selector_macos-0.9.4
file_selector_windows-0.9.3+2
firebase_auth-5.1.4
firebase_auth_web-5.12.5
firebase_core-3.3.0
firebase_core_web-2.17.4
firebase_performance-0.10.0+4
firebase_performance_web-0.1.6+12
firebase_storage-12.1.3
firebase_storage_web-3.9.12
flutter_plugin_android_lifecycle-2.0.21
google_sign_in-6.2.1
google_sign_in_android-6.1.28
google_sign_in_ios-5.7.6
google_sign_in_web-0.12.4+2
image_picker-1.1.2
image_picker_android-0.8.12+12
image_picker_for_web-3.0.5
image_picker_ios-0.8.12
image_picker_linux-0.2.1+1
image_picker_macos-0.2.1+1
image_picker_windows-0.2.1+1
package_info_plus-8.0.2
path_provider-2.1.4
path_provider_android-2.2.10
path_provider_foundation-2.4.0
path_provider_linux-2.2.1
path_provider_windows-2.3.0
shared_preferences-2.3.2
shared_preferences_android-2.3.1
shared_preferences_foundation-2.5.2
shared_preferences_linux-2.4.1
shared_preferences_web-2.4.2
shared_preferences_windows-2.4.1
sign_in_with_apple-6.1.1
sign_in_with_apple_web-2.1.0
sqflite-2.3.3+1
url_launcher-6.3.0
url_launcher_android-6.3.9
url_launcher_ios-6.3.1
url_launcher_linux-3.2.0
url_launcher_macos-3.2.0
url_launcher_web-2.3.3
url_launcher_windows-3.1.2
video_player-2.9.1
video_player_android-2.6.0
video_player_avfoundation-2.6.1
video_player_web-2.3.2
wakelock_plus-1.2.8

**Comment by mqhamdam** [comment] 2024-08-19 01:49
This is known issue, follow here #152953

**Comment by huycozy** [comment] 2024-08-19 07:47
Closing this as a duplicate of https://github.com/flutter/flutter/issues/153064. This has been fixed on Flutter master channel so you can try switching to master channel and retry.

**Closed by huycozy** 2024-08-19 07:47 UTC
Labels: in triage
