### ISSUE TITLE
Tap on TextField shouldn't rebuild whole StatefulWidget

### ISSUE THREAD

**Issue by SokHo** [flutter/flutter#69689] opened 2020-11-03 17:16 UTC
```
@override
  Widget build(BuildContext context) {
    **print("rebuild context again");**
    int prevUserId;
    return Scaffold(       
      body: Column(
        children: <Widget>[
          Expanded(
            child: ListView.builder(
              reverse: true,
              padding: EdgeInsets.all(20),
              itemCount: messages.length,
              itemBuilder: (BuildContext context, int index) {
                final Message message = messages[index];
                final bool isMe = message.sender.id == currentUser.id;
                final bool isSameUser = prevUserId == message.sender.id;
                prevUserId = message.sender.id;
                return _chatBubble(message, isMe, isSameUser);
              },
            ),
          ),
          **_sendMessageArea(),**
        ],
      ),
    );
  }

  _sendMessageArea() {
    return Container(
      padding: EdgeInsets.symmetric(horizontal: 8),
      height: 70,
      color: Colors.white,
      child: Row(
        children: <Widget>[
          IconButton(
            icon: Icon(Icons.photo),
            iconSize: 25,
            color: Theme.of(context).primaryColor,
            onPressed: () {},
          ),
          **Expanded(
            child: TextField(
              decoration: InputDecoration.collapsed(
                hintText: 'Send a message..',
              ),
              textCapitalization: TextCapitalization.sentences,
            ),
          ),**
          IconButton(
            icon: Icon(Icons.send),
            iconSize: 25,
            color: Theme.of(context).primaryColor,
            onPressed: () {},
          ),
        ],
      ),
    );
  }
```

I just sample short code but you can download full from here
[Pradip Debnath](https://github.com/itzpradip/flutter-chat-app)

problem was every time we tab on TextField it rebuild whole widget.

**Comment by darshankawar** [comment] 2020-11-04 07:50
@SokHo 
Cloned your repo and tapped on textfield to type in a message, but didn't notice the screen being rebuild.

[69689.mp4.zip](https://github.com/flutter/flutter/files/5486237/69689.mp4.zip)

Also try [this](https://github.com/flutter/flutter/issues/13325#issuecomment-349148641) and see what actually is triggering a rebuild in your case. And see [this](https://github.com/flutter/flutter/issues/13325#issuecomment-349457806) comment for your reference.

**Comment by SokHo** [comment] 2020-11-04 16:55
@darshankawar 
I mean you can add some print code to see rebuild,

@override
 Widget build(BuildContext context) {
   **print("rebuild context again and again");** `try print over here`
   int prevUserId;
....

**Comment by darshankawar** [comment] 2020-11-05 06:14
<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 1.22.3, on Mac OS X 10.15.4 19E2269, locale en-IN)
    • Flutter version 1.22.3 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 8874f21e79 (6 days ago), 2020-10-29 14:14:35 -0700
    • Engine revision a1440ca392
    • Dart version 2.10.3

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.1

[✓] Connected device (2 available)
    • Darshan's iphone (mobile)           •
      21150b119064aecc249dfcfe05e259197461ce23 • ios • iOS 14.0
    • iPhone SE (2nd generation) (mobile) • 6C85835D-FBFD-4AB3-8DE8-B4FAD35E5367
      • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)

• No issues found!



```

</details>


```
flutter: rebuild context again and again
flutter: rebuild context again and again
flutter: rebuild context again and again
flutter: rebuild context again and again
flutter: rebuild context again and again
flutter: rebuild context again and again
```

**Comment by SokHo** [comment] 2020-11-05 08:02
> flutter doctor -v
> ```
> flutter: rebuild context again and again
> flutter: rebuild context again and again
> flutter: rebuild context again and again
> flutter: rebuild context again and again
> flutter: rebuild context again and again
> flutter: rebuild context again and again
> ```

Yes, as you can see it's rebuild all the time when we tap on TextField.
So did you have solution for this?

**Comment by maheshmnj** [comment] 2022-11-30 16:54
Hi @SokHo, I verified the issue on the latest stable and the master channel and cannot reproduce the issue. I think this issue has been fixed.


<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: Center(
          child: TestWidget(),
        ),
      ),
    );
  }
}

 class TestWidget extends StatefulWidget {
  const TestWidget({super.key});

  @override
  State<TestWidget> createState() => _TestWidgetState();
}

class _TestWidgetState extends State<TestWidget> {

   _sendMessageArea() {
   return Container(
     padding: EdgeInsets.symmetric(horizontal: 8),
     height: 70,
     color: Colors.white,
     child: Row(
       children: <Widget>[
         IconButton(
           icon: Icon(Icons.photo),
           iconSize: 25,
           color: Theme.of(context).primaryColor,
           onPressed: () {},
         ),
         const Expanded(
           child: TextField(
             decoration: InputDecoration.collapsed(
               hintText: 'Send a message..',
             ),
             style: TextStyle(color:Colors.black),
             textCapitalization: TextCapitalization.sentences,
           ),
         ),
         IconButton(
           icon: const Icon(Icons.send),
           iconSize: 25,
           color: Theme.of(context).primaryColor,
           onPressed: () {},
         ),
       ],
     ));
 }

  @override
  Widget build(BuildContext context) {
    print('Widget rebuilds');
    return Scaffold(
     body: Column(
       children: <Widget>[
         Expanded(
           child: ListView.builder(
             reverse: true,
             padding: EdgeInsets.all(20),
             itemCount: 20,
             itemBuilder: (BuildContext context, int index) {
                return ListTile(
                  title: Text('User $index'),
                  onTap: () {
                   FocusScope.of(context).unfocus();
                  },
                );
             },
           ),
         ),
        _sendMessageArea(),
       ],
     ),
   );
  }
}
```
</details>  

<details>
<summary>logs</summary>

```
Restarted application in 356ms.
flutter: Widget rebuilds
```
</details> 

Closing, Incase you still encounter the issue. Feel free to write in the comments and we will reopen it.

Thank you.

**Closed by maheshmnj** 2022-11-30 16:54 UTC
Labels: a: text input, framework, f: material design, passed first triage, has reproducible steps, found in release: 1.22
