### ISSUE TITLE
Flutter Linux build error X window system error 

### ISSUE THREAD

**Issue by abdulrasol** [flutter/flutter#91216] opened 2021-10-04 07:41 UTC
Hello Guys 
I have updated my system to (Elementary os) and after updating and install builds tools for flutter for Linux build to get this error

when run `flutter run -d linux` i get that:
```
Launching lib/main.dart on Linux in debug mode...
(store_items:6176): Gdk-ERROR **: 10:22:28.017: The program 'store_items' received an X Window System error.
This probably reflects a bug in the program.
The error was 'GLXBadFBConfig'.
  (Details: serial 244 error_code 167 request_code 152 (GLX) minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
Error waiting for a debug connection: The log reader stopped unexpectedly.
Error launching application on Linux.
Exited (sigterm)
```

and `flutter doctor` output is:

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.3, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.60.2)
[✓] Connected device (2 available)

• No issues found!

```

OS Elementary OS
Flutter (Channel stable, 2.2.3, on Linux, locale en_US.UTF-8)

**Comment by TahaTesser** [comment] 2021-10-04 12:45
Hi @abdulrasol 
Unfortunately, the Flutter version you're using is outdated and is no longer supported, it's not feasible to provide any bug fixes for such an old version of Flutter.

I kindly advise you to update to the latest Flutter `stable`, if you encounter the issue again, please comment below with the details from the latest stable, including steps to replicate the issue.

Can you please upgrade to the latest  `stable` and try again
Execute the following commands to upgrade
`flutter channel stable`
`flutter upgrade --force`
`flutter doctor -v`

If the problem persists, can you please provide your `flutter doctor -v` with the upgrade, complete reproducible minimal code sample, and complete `flutter run --verbose` logs running the minimal code sample?

Thank you

**Comment by abdulrasol** [comment] 2021-10-05 07:04
@TahaTesser 
Thanks for your reply dear
but still the same issue

now I use flutter 2.5.2
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.5.2, on elementary OS 6 Odin 5.11.0-37-generic, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.60.2)
[✓] Connected device (2 available)
```

 ` flutter doctor -v` output:
```
Flutter (Channel stable, 2.5.2, on elementary OS 6 Odin 5.11.0-37-generic, locale en_US.UTF-8)
    • Flutter version 2.5.2 at /home/rasol/DevTools/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3595343e20 (4 days ago), 2021-09-30 12:58:18 -0700
    • Engine revision 6ac856380f
    • Dart version 2.14.3

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /home/rasol/DevTools/Android
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /home/rasol/DevTools/android
    • Java binary at: /home/rasol/Apps/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 2020.3)
    • Android Studio at /home/rasol/Apps/android-studio
    • Flutter plugin version 59.0.2
    • Dart plugin version 203.8292
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.60.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.26.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • elementary OS 6 Odin 5.11.0-37-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 94.0.4606.71

• No issues found!

```

**Comment by TahaTesser** [comment] 2021-10-05 07:14
Hi @abdulrasol 
Are you using a virtual machine or very old hardware?  The error seems to be related to the environment itself based on my search. Please file an issue on the Elementary OS forum or try a different machine with the same OS
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-10-05 07:14 UTC
Labels: in triage
