### ISSUE TITLE
Does this lib supports USB camera on android device? 

### ISSUE THREAD

**Issue by cityvoice** [flutter/flutter#141058] opened 2024-01-06 13:17 UTC
### Steps to reproduce

My camera's version ^0.10.5+3.But it still doesnot recognize my external USB camera on my Android Pad, how to do?

Feature:
Android 12
Android SDK 34
Does not recognize usb camera
usb camera can work with Androidusbcamera sdk.

### Expected results

Can use usb camera

### Actual results

doesnot work

### Code sample

<details open><summary>Code sample</summary>

```dart
class CameraView extends StatefulWidget {
  const CameraView(
      {Key? key,
      this.customPaint,
      required this.onImage,
      this.onCameraFeedReady,
      this.onDetectorViewModeChanged,
      this.onCameraLensDirectionChanged,
      this.initialCameraLensDirection = CameraLensDirection.external})
      : super(key: key);

    .....
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by stuartmorgan** [comment] 2024-01-07 13:01
Duplicate of https://github.com/flutter/flutter/issues/42413

**Closed by stuartmorgan** 2024-01-07 13:01 UTC
