### ISSUE TITLE
flutter 1.12.13+hotfix5 Black screen appears when loading

### ISSUE THREAD

**Issue by ltq2017** [flutter/flutter#47582] opened 2019-12-21 10:46 UTC
flutter 1.12.13+hotfix5 Black screen appears when loading
![Video_20191221_062939_30](https://user-images.githubusercontent.com/33394752/71306841-91afea80-2420-11ea-9de3-15bb30e02702.gif)

flutter v1.9.1+hotfix.6 Display normal

Please How to solve it.

**Comment by ltq2017** [comment] 2019-12-21 10:48
![Video_20191221_062939_30](https://user-images.githubusercontent.com/33394752/71306940-54e4f300-2422-11ea-8e01-db1c784bbafd.gif)

**Comment by ltq2017** [comment] 2019-12-21 11:01
12/21 18:59:21: Launching 'app' on OPPO PADM00.
$ adb shell am start -n "flutter2.flutter_app2/flutter2.flutter_app2.MainActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Waiting for process to come online...
Connected to process 21093 on device 'oppo-padm00-MJPVZL9THY7SAALR'.
Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
I/ResourceExtractor: Found extracted resources res_timestamp-1-1576924733583
    Resource version mismatch res_timestamp-1-1576925982542
D/FlutterActivityAndFragmentDelegate: Setting up FlutterEngine.
    No preferred FlutterEngine was provided. Creating a new FlutterEngine for this FlutterFragment.
I/ResourceExtractor: Extracted baseline resource assets/flutter_assets/kernel_blob.bin
I/ResourceExtractor: Extracted baseline resource assets/flutter_assets/vm_snapshot_data
I/ResourceExtractor: Extracted baseline resource assets/flutter_assets/isolate_snapshot_data
D/libEGL: ARC_TRACE: arc_initARCTraceLevel
    Active EGL Table is EglArcHook
I/zygote64: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 0
W/GiFTMANAGER: OppoGiFTServiceManager::getGiFTPara nRetSize = 1
I/libARC: gli_eglCreateContextRet() tid:21093, ctx: 0x7dbaa5ef90, ARC not Enabled.
D/libEGL: ARC_TRACE: ARCASM_eglCreateContext() => ctx: 0x7dbaa5ef90
D/libEGL: ARC_TRACE: ARCASM_eglMakeCurrent(ctx:0x7dbaa5ef90)
D/FlutterActivityAndFragmentDelegate: Attaching FlutterEngine to the Activity that owns this Fragment.
I/SurfaceFactory: [static] sSurfaceFactory = com.mediatek.view.impl.SurfaceFactoryImpl@8ef20a7
D/skia_mt: canRunInCoworker = true
I/flutter: Observatory listening on http://127.0.0.1:40627/aupSjhaBEi0=/
D/WindowClient: Add to mViews: DecorView@21442b5[MainActivity], this = android.view.WindowManagerGlobal@bf1bd4a
D/OpenGLRenderer: Dumper init 4 threads <0x7dc98f6c80>
    <flutter2.flutter_app2> is running.
D/OpenGLRenderer: HWUI GL Pipeline
D/ViewRootImpl[MainActivity]: hardware acceleration = true , fakeHwAccelerated = false, sRendererDisabled = false, forceHwAccelerated = false, sSystemRendererDisabled = false
D/libARC: etEventThreadFunc()::thread Begin. eventRefCnt: 1
I/InputTransport: Create ARC handle: 0x7dbaba5800
V/PhoneWindow: DecorView setVisiblity: visibility = 0, Parent = ViewRoot{ed654bb flutter2.flutter_app2/flutter2.flutter_app2.MainActivity,ident = 0}, this = DecorView@21442b5[MainActivity]
D/FlutterView: Attaching to a FlutterEngine: io.flutter.embedding.engine.FlutterEngine@2b53dd8
D/FlutterActivityAndFragmentDelegate: Executing Dart entrypoint: main, and sending initial route: /
I/Choreographer: Skipped 2 frames!  The application may be doing too much work on its main thread.
I/OpenGLRenderer: Initialized EGL, version 1.4
D/OpenGLRenderer: Swap behavior 2
D/libEGL: [GIFT] clean GIFT bit (0)
I/libARC: gli_eglCreateContextRet() tid:21336, ctx: 0x7db8e82cb8, ARC not Enabled.
D/libEGL: ARC_TRACE: ARCASM_eglCreateContext() => ctx: 0x7db8e82cb8
    ARC_TRACE: ARCASM_eglMakeCurrent(ctx:0x7db8e82cb8)
D/OpenGLRenderer: [init] completed
D/HWUIExtension: MTKProgramCache.init: enable enhancement 1
I/HWUIExtension: Get disable program binary service property (0)
    Initializing program atlas...
I/ProgramBinary/Service: ProgramBinaryService client side disable debugging.
    ProgramBinaryService client side disable binary content debugging.
D/ProgramBinary/Service: BpProgramBinaryService.getReady
    zhiyin- 1 BpProgramBinaryService::getReady()
D/ProgramBinary/Service: zhiyin- 2 BpProgramBinaryService::getReady()
    BpProgramBinaryService.getProgramBinaryData
I/HWUIExtension: Program binary detail: Binary length is 193832, program map length is 104.
    Succeeded to mmap program binaries. File descriptor is 87, and path is /dev/ashmem.
I/HWUIExtension: No need to use file discriptor anymore, close fd(87).
D/HWUIExtension: Dumper init 4 threads <0x7db7d25400>
    <flutter2.flutter_app2> is running.
    Initializing program cache from 0x0, size = -1
D/Surface: Surface::connect(this=0x7db8ed3000,api=1)
I/libARC: gli_eglCreateContextRet() tid:21292, ctx: 0x7dcf2a1ef0, ARC not Enabled.
D/libEGL: ARC_TRACE: ARCASM_eglCreateContext() => ctx: 0x7dcf2a1ef0
D/Surface: Surface::connect(this=0x7db8edc000,api=1)
D/mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, egl_color_buffer_format *, EGLBoolean) returns 0x3000
D/mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, egl_color_buffer_format *, EGLBoolean) returns 0x3000
D/libEGL: ARC_TRACE: ARCASM_eglMakeCurrent(ctx:0x7dcf2a1ef0)
D/libEGL: ARC_TRACE: ARCASM_eglMakeCurrent(ctx:0x0)
I/Choreographer: Skipped 12 frames!  The application may be doing too much work on its main thread.
D/libEGL: ARC_TRACE: ARCASM_eglMakeCurrent(ctx:0x7db8e82cb8)
D/HWUIExtension: MTKProgramCache.generateProgram: 1
D/HWUIExtension: createProgram 0x0000000000000001, binary 0x7e59d4f59c, length 4912, format 36705 within 506ns
    MTKProgramCache.generateProgram: 34359738368
D/HWUIExtension: createProgram 0x0000000800000000, binary 0x7e59d508cc, length 4336, format 36705 within 355ns
D/libEGL: ARC_TRACE: ARCASM_eglMakeCurrent(ctx:0x7dcf2a1ef0)
D/HWUIExtension: MTKProgramCache.generateProgram: 0
D/HWUIExtension: createProgram 0x0000000000000000, binary 0x7e59d29000, length 4336, format 36705 within 497ns

**Comment by rs5173** [comment] 2019-12-21 17:32
https://github.com/flutter/flutter/issues/47287#issuecomment-566879767

**Comment by iapicca** [comment] 2019-12-22 12:18
Hi @ltq2017  
can you please provide  a minimal code sample
or the steps to reproduce the problem.
Thank you

**Comment by ltq2017** [comment] 2019-12-22 14:29
[flutter_test2.zip](https://github.com/flutter/flutter/files/3992559/flutter_test2.zip)

code example


> Hi @ltq2017
> can you please provide a minimal code sample
> or the steps to reproduce the problem.
> Thank you

example code file
[flutter_test2.zip](https://github.com/flutter/flutter/files/3992568/flutter_test2.zip)
[flutter_test.zip](https://github.com/flutter/flutter/files/3992572/flutter_test.zip)

**Comment by ltq2017** [comment] 2019-12-22 14:45
> Hi @ltq2017
> can you please provide a minimal code sample
> or the steps to reproduce the problem.
> Thank you

<img width="575" alt="QQ20191222-224248@2x" src="https://user-images.githubusercontent.com/33394752/71323316-a7024300-250c-11ea-9989-ff82ad4cc592.png">

**Comment by sky126** [comment] 2019-12-23 10:18
same issues

**Comment by mardonedias** [comment] 2019-12-23 23:05
same issues

**Comment by wdp1990821** [comment] 2019-12-25 02:31
same issues

**Comment by hayderux** [comment] 2019-12-25 03:28
same issues

**Comment by moy921021** [comment] 2019-12-25 13:28
same issues

**Comment by MudassirMansoor** [comment] 2019-12-25 23:54
Same Issue. Any one got it resolved ?

**Comment by MiloHwb** [comment] 2019-12-26 08:10
same issue

**Comment by ltq2017** [comment] 2019-12-26 08:22
has someone solved the problem,please?
Thank you！

**Comment by Qishiyuan** [comment] 2019-12-26 09:14
same issues

**Comment by ltq2017** [comment] 2019-12-30 17:21
has someone solved the problem,please?
Thank you！

**Comment by IronRen** [comment] 2019-12-30 17:34
create a  new project, then execute ”flutter build apk “ is Ok, this bug occurs when run directly.

**Comment by yk3372** [comment] 2019-12-31 07:17
same issues

**Comment by yk3372** [comment] 2019-12-31 07:32
add this can lighten it
```<meta-data
                android:name="io.flutter.embedding.android.SplashScreenDrawable"
                android:resource="@drawable/launch_background" />```

I think maybe below code cause the issue
![image](https://user-images.githubusercontent.com/1514899/71613641-9e7fcb80-2be2-11ea-8cdb-4ce6f3f66d08.png)

**Comment by hjianjie** [comment] 2020-01-01 04:06
same issues，how do solve it.

**Comment by carocean** [comment] 2020-01-02 13:54
别要人家上传代码了，这个问题在android10下会出现，而且flutter_gallery官方的例程也会出现该问题。希望尽快解决！flutter团队，加油！

**Comment by rinekri** [comment] 2020-01-10 14:05
> > 别要人家上传代码了，这个问题在android10下会出现，而且flutter_gallery官方的例程也会出现该问题。希望尽快解决！flutter团队，加油！
> 
> Don't ask others to upload the code, this problem will appear under android10, and the official routine of flutter_gallery will also have this problem. Hope to solve it soon! flutter team, come on!

Yeah, it should be fixed as soon as possible, because it affects release applications :(

**Comment by rdsuncn** [comment] 2020-01-19 10:12
I resolve it by remove the kotlin compiler  in  the version 1.12.13. 
1.  In  build.gradle file remove the plugin kotlin and all others related to kotlin
2.  remove the <meta-data
            android:name="flutterEmbedding"
            android:value="2" /> in AndroidManifest.xml
3.  copy the old  start file MainActivity.java to \src\main\java. now it sounds good

**Comment by carocean** [comment] 2020-01-20 02:36
@rdsuncn 我照你说的试了几遍都还是那样黑屏。
你这样做好像是等同于降低了版本。
remove the meta-data
android:name="flutterEmbedding"
android:value="2" in AndroidManifest.xml
去掉这个MainActivity.java 在12.13版本下缺少api，必须降级才能使用，这便没啥意思了，因为降级后根本没问题

**Comment by syntaxp** [comment] 2020-01-22 14:34
please

**Comment by iamvitaminx** [comment] 2020-01-26 06:11
Follow [this](https://flutter.dev/docs/development/ui/splash-screen/android-splash-screen)

**Comment by proghjy** [comment] 2020-02-06 07:42
add your activity meta-data in AndroidManifast.xml

```xml
<meta-data
    android:name="io.flutter.embedding.android.SplashScreenDrawable"
    android:resource="@drawable/launch_background"/>
```

**Comment by praveenb** [comment] 2020-02-06 20:05
I find a solution as shown in below link,  
Please see this link [https://github.com/flutter/flutter/issues/49932#issuecomment-583084421](url)

Hope it helps somebody

**Comment by xing634325131** [comment] 2020-02-07 09:34
> I find a solution as shown in below link,
> Please see this link [https://github.com/flutter/flutter/issues/49932#issuecomment-583084421](url)
> 
> Hope it helps somebody



> I find a solution as shown in below link,
> Please see this link [https://github.com/flutter/flutter/issues/49932#issuecomment-583084421](url)
> 
> Hope it helps somebody

not ok

**Comment by praveenb** [comment] 2020-02-07 09:54
@xing634325131 , I updated link pls check it once.

**Comment by littleGnAl** [comment] 2020-02-08 14:26
Pls follow the official guide [https://flutter.dev/docs/development/ui/splash-screen/android-splash-screen](https://flutter.dev/docs/development/ui/splash-screen/android-splash-screen)

**Comment by TahaMalas** [comment] 2020-02-09 20:02
> add this can lighten it
> 
> ```
> <meta-data
>                 android:name="io.flutter.embedding.android.SplashScreenDrawable"
>                 android:resource="@drawable/launch_background" />
> ```
> 
> I think maybe below code cause the issue， default use the splashview.
> If not set, it show default black.
> 
> ![image](https://user-images.githubusercontent.com/1514899/71613641-9e7fcb80-2be2-11ea-8cdb-4ce6f3f66d08.png)

This fix works perfectly, but the splash screen remains in the backstack of the app, so when I press the back button the splash screen shows! is there any fix to that

**Comment by carocean** [comment] 2020-02-10 03:46
Hi，哥们儿，试了你的方一，没用

发自我的iPhone

**Comment by Piinks** [comment] 2020-02-10 21:10
This looks very similar to #39494

**Comment by Piinks** [comment] 2020-02-11 00:42
Following up, this does appear to be a duplicate of #39494. Please track that issue for updates. If you believe we've made an error, please reply here with more details that explain the difference and we'll re-open this issue.

Also, please avoid commenting “me too”, “+1”, or similar on issues. Instead, we encourage you to add a thumbs-up reaction to the original comment on the linked issue. We use thumbs-up 👍 
 reactions as part of our issue prioritization process, so this will help get your issue addressed quicker. If you’d like to receive updates, click the subscribe button in the right hand column on the linked issue. :)

**Closed by Piinks** 2020-02-11 00:42 UTC
Labels: a: animation, customer: crowd, dependency: android, framework, severe: regression, ▣ platform-android

**Comment by dongtvse05344** [comment] 2020-03-10 07:34
The reason of the black screen because of this 
<
 
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
>
I have solution:
1. remove above code in AndroidManifest.xml
2. Replace this code in MainActivity 
<
import android.os.Bundle

import io.flutter.app.FlutterActivity
import io.flutter.plugins.GeneratedPluginRegistrant

class MainActivity: FlutterActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        GeneratedPluginRegistrant.registerWith(this)
    }
}
>

It's worked with me.

**Comment by CaptMustache** [comment] 2020-04-02 18:52
Problem still exists on my android phone and non of the above mentioned solution worked. 
```

[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.3 19D76, locale en-DE)
    • Flutter version 1.12.13+hotfix.8 at /Users/dev/flutter/sdk
    • Framework revision 0b8abb4724 (7 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/dev/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4, Build version 11E146
    • CocoaPods version 1.9.0

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.43.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[✓] Connected device (2 available)
    • Pixel 4           • 99061FFAZ00H36                       • android-arm64 • Android 10 (API 29)
    • iPhone 11 Pro Max • B8902A39-1CE9-4842-BAE5-9E5913285940 • ios           • com.apple.CoreSimulator.SimRuntime.iOS-13-4 (simulator)

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  kt_dart: ^0.7.0+1

  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2

  flutter_svg: ^0.17.3+1
  provider: ^4.0.4
  cupertino_icons: ^0.1.3

dev_dependencies:
  test:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
  hive_generator: ^0.7.0+2
  build_runner: ^1.8.0

```

**Comment by githubjin** [comment] 2020-04-03 03:52
same inssues
![Uploading image.png…]()

**Comment by githubjin** [comment] 2020-04-03 03:54
same inssues

Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.15.3 19D76,
    locale zh-Hans-CN)

**Comment by windows7lake** [comment] 2020-04-03 06:18
> Problem still exists on my android phone and non of the above mentioned solution worked.
> 
> ```
> 
> [✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.3 19D76, locale en-DE)
>     • Flutter version 1.12.13+hotfix.8 at /Users/dev/flutter/sdk
>     • Framework revision 0b8abb4724 (7 weeks ago), 2020-02-11 11:44:36 -0800
>     • Engine revision e1e6ced81d
>     • Dart version 2.7.0
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
>     • Android SDK at /Users/dev/Library/Android/sdk
>     • Android NDK location not configured (optional; useful for native profiling support)
>     • Platform android-29, build-tools 29.0.2
>     • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
>     • All Android licenses accepted.
> 
> [✓] Xcode - develop for iOS and macOS (Xcode 11.4)
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • Xcode 11.4, Build version 11E146
>     • CocoaPods version 1.9.0
> 
> [✓] Android Studio (version 3.6)
>     • Android Studio at /Applications/Android Studio.app/Contents
>     • Flutter plugin version 44.0.2
>     • Dart plugin version 192.7761
>     • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
> 
> [✓] VS Code (version 1.43.2)
>     • VS Code at /Applications/Visual Studio Code.app/Contents
>     • Flutter extension version 3.8.1
> 
> [✓] Connected device (2 available)
>     • Pixel 4           • 99061FFAZ00H36                       • android-arm64 • Android 10 (API 29)
>     • iPhone 11 Pro Max • B8902A39-1CE9-4842-BAE5-9E5913285940 • ios           • com.apple.CoreSimulator.SimRuntime.iOS-13-4 (simulator)
> 
> version: 1.0.0+1
> 
> environment:
>   sdk: ">=2.6.0 <3.0.0"
> 
> dependencies:
>   flutter:
>     sdk: flutter
>   flutter_localizations:
>     sdk: flutter
>   kt_dart: ^0.7.0+1
> 
>   hive: ^1.4.1+1
>   hive_flutter: ^0.3.0+2
> 
>   flutter_svg: ^0.17.3+1
>   provider: ^4.0.4
>   cupertino_icons: ^0.1.3
> 
> dev_dependencies:
>   test:
>   flutter_test:
>     sdk: flutter
>   mockito: ^4.1.1
>   hive_generator: ^0.7.0+2
>   build_runner: ^1.8.0
> ```

Create a new issue should be better.

**Comment by Piinks** [comment] 2020-04-03 17:09
> Create a new issue should be better.

@ windows7lake  @CaptMustache @githubjin This issue has been resolved by #52913, which has not reached the stable channel yet. It looks like it has been tagged first at v1.16.3, which is currently available on the dev channel. Please check and see if the issue persists on that channel before filing another issue.

**Comment by m-sadegh-sh** [comment] 2020-04-06 16:36
@Piinks Finally I can confirm that my issue is now completely resolved after a long while 👍 Thank you all guy. 🥂 🥂 🥂  I really appreciate for your commitment.

**Comment by orestesgaolin** [comment] 2020-04-14 12:35
When using Flutter beta channel (1.17.0) I can observe that on Android the short black screen between splash screen and initial frame of Flutter in release mode occurs on average 1 out of 3 launches.

What I do to test is:
1. Launch the app, looks OK
2. Kill the app by swiping in task manager
3. Launch again, looks OK
4. Kill the app
5. Launch again, most of the time black screen blinks for a split second

**Comment by RaashVision** [comment] 2020-05-02 15:07
> ~When using Flutter beta channel (1.17.0) I can observe that on Android the short black screen between splash screen and initial frame of Flutter in release mode occurs on average 1 out of 3 launches.~
> 
> ~What I do to test is:~
> ~1. Launch the app, looks OK~
> ~2. Kill the app by swiping in task manager~
> ~3. Launch again, looks OK~
> ~4. Kill the app~
> ~5. Launch again, most of the time black screen blinks for a split second~
> 
> **Edit**: ok, I copied the metadata from project generated on Flutter 1.17 in AndroidManifest. Now it works as described in the PR.
> 
> ```
> <activity
>     android:name=".MainActivity"
>     android:launchMode="singleTop"
>     android:theme="@style/LaunchTheme"
>     android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
>     android:hardwareAccelerated="true"
>     android:windowSoftInputMode="adjustResize">
>     
>     <meta-data
>         android:name="io.flutter.embedding.android.NormalTheme"
>         android:resource="@style/NormalTheme"
>         />
>     
>     <meta-data
>         android:name="io.flutter.embedding.android.SplashScreenDrawable"
>         android:resource="@drawable/launch_background"
>         />
>     <intent-filter>
>         <action android:name="android.intent.action.MAIN"/>
>         <category android:name="android.intent.category.LAUNCHER"/>
>     </intent-filter>
> </activity>
> ```

I guess only this line make it works

 <meta-data
        android:name="io.flutter.embedding.android.SplashScreenDrawable"
        android:resource="@drawable/launch_background"
        />

**Comment by AhmadAbuRjeila** [comment] 2020-06-09 18:09
> > ~When using Flutter beta channel (1.17.0) I can observe that on Android the short black screen between splash screen and initial frame of Flutter in release mode occurs on average 1 out of 3 launches.~
> > ~What I do to test is:~
> > ~1. Launch the app, looks OK~
> > ~2. Kill the app by swiping in task manager~
> > ~3. Launch again, looks OK~
> > ~4. Kill the app~
> > ~5. Launch again, most of the time black screen blinks for a split second~
> > **Edit**: ok, I copied the metadata from project generated on Flutter 1.17 in AndroidManifest. Now it works as described in the PR.
> > ```
> > <activity
> >     android:name=".MainActivity"
> >     android:launchMode="singleTop"
> >     android:theme="@style/LaunchTheme"
> >     android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
> >     android:hardwareAccelerated="true"
> >     android:windowSoftInputMode="adjustResize">
> >     
> >     <meta-data
> >         android:name="io.flutter.embedding.android.NormalTheme"
> >         android:resource="@style/NormalTheme"
> >         />
> >     
> >     <meta-data
> >         android:name="io.flutter.embedding.android.SplashScreenDrawable"
> >         android:resource="@drawable/launch_background"
> >         />
> >     <intent-filter>
> >         <action android:name="android.intent.action.MAIN"/>
> >         <category android:name="android.intent.category.LAUNCHER"/>
> >     </intent-filter>
> > </activity>
> > ```
> 
> I guess only this line make it works
> 
> ` <meta-data android:name="io.flutter.embedding.android.SplashScreenDrawable" android:resource="@drawable/launch_background" />`

Thanks, worked for me

**Comment by JayakumarB** [comment] 2020-07-07 14:36
> add this can lighten it
> 
> ```
> <meta-data
>                 android:name="io.flutter.embedding.android.SplashScreenDrawable"
>                 android:resource="@drawable/launch_background" />
> ```
> 
> I think maybe below code cause the issue， default use the splashview.
> If not set, it show default black.
> 
> ![image](https://user-images.githubusercontent.com/1514899/71613641-9e7fcb80-2be2-11ea-8cdb-4ce6f3f66d08.png)

This works like a Charm @proghjy Thank you

**Comment by JayakumarB** [comment] 2020-07-07 14:37
> add your activity meta-data in AndroidManifast.xml
> 
> ```
> <meta-data
>     android:name="io.flutter.embedding.android.SplashScreenDrawable"
>     android:resource="@drawable/launch_background"/>
> ```

This works like a charm. Thank you @proghjy

**Comment by AlmogRnD** [comment] 2021-01-06 17:38
I'm still getting this issue both on Android and iOS using Flutter stable 1.22.5. Is there any news about this ?

**Comment by iapicca** [comment] 2021-01-06 23:58
@AlmogRnD 
this issue was closed almost a year ago and is not actively worked on
please open a new issue providing your `flutter doctor -v`, your `flutter run -v`
and a minimal reproducible code sample

**Comment by AlmogRnD** [comment] 2021-01-07 06:40
@iapicca thanks I already did that yesterday https://github.com/flutter/flutter/issues/73418

**Comment by irajeshh** [comment] 2021-07-03 13:06
Using this plugin as dev dependency solved the issue 
[flutter_native_splash](https://pub.dev/packages/flutter_native_splash)

Add to your Pubspec 

```
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_native_splash: ^1.2.0
flutter_native_splash:
  color: "#32b3a4"
  image: assets/logo.png #u must place logo.png in your assets folder
  android: true
  ios: true

flutter:
  uses-material-design: true

```

More customization are given in the ReadMe of the plugin
