### ISSUE TITLE
Allow to configure the behavior of deleting the .gradle folder if there is a connection problem

### ISSUE THREAD

**Issue by leynier** [flutter/flutter#89959] opened 2021-09-13 04:02 UTC
## Use case

This issue is to request that the behavior of removing the contents of the `.gradle` folder when a problem occurs with the internet connection can be enabled or disabled by a setting, perhaps a parameter of `flutter run` and `flutter build`, perhaps through an operating system environment variable or perhaps through a configuration file.

Many developers do not have a stable Internet connection so the delete behavior if an Internet connection problem occurs, is really inconvenient, because downloading the files again is a problem. I understand that the delete behavior is to prevent corrupt Gradle files from being used, but it would be great if that behavior is configurable.

It was already mentioned in another issue (#89000) and it was concluded that it is expected behavior.

https://github.com/flutter/flutter/blob/2e5ad37b063928d080de7839f08999ed0dc521c9/packages/flutter_tools/lib/src/android/gradle_errors.dart#L211

**Comment by alejandrogiubel** [comment] 2021-09-13 14:02
Yes. The new version 2.5 of Flutter removes the .gradle cache folder when there are connection errors. Deleting this directory causes having to download gradle files again. Some users have poor internet connections and expensive data plans. Some alternative mentioned by @leynier would be very useful.

**Comment by asatayo** [comment] 2021-09-27 12:07
This problem is too bad, I think next version should have a better option regarding gradle updates (Delete or Edit, Add). Last time I had no internet switched on in my machine everything went fine but I got to the network the previous was deleted and requested to download another one. While both were 6.7-all, this is so insane for sure. We should at least find a way to configure the issue or, redownload only when the app gradle is not compatible with multiple gradle however there should an option for switching the gradles, so as we can as many as we want without deleting the previous one.

**Comment by Hatem-Saad** [comment] 2021-11-08 13:27
I just wasted like 50 GB
I have stable internet but I don't know it keeps on failing and re-downloading 
and I'm now left with an empty .gradle folder.

**Comment by senthilraja570** [comment] 2021-11-14 19:42
Having to delete .gradle folder is really bad! 
The most annoying part is that not only does it delete the directory of current gradle version in context... It deletes all!
My connection is unstable and I feel stucked!
Going back to previous flutter version.

**Comment by asatayo** [comment] 2021-11-14 22:43
Hey I recommend 2.5.3 it’s really stable, Since I started using it  , I
have experienced neither of the challenges. It’s now supper 🔥🔥🔥

**Comment by solokingjec** [comment] 2021-11-15 21:28
Am on 2.5.3 and the same problem is happening. It’s 3days now. I haven’t done anything because of this

**Comment by kwameopareasiedu** [comment] 2021-12-31 18:11
> Am on 2.5.3 and the same problem is happening. It’s 3days now. I haven’t done anything because of this

Same here. Flutter 2.5.3

**Comment by kwameopareasiedu** [comment] 2022-01-01 03:42
Downgrading to Flutter 2 is the current workaround I found for intermittent internet connections. Flutter 2 doesn't delete the `.gradle/` folder if an error occurs. It just resumes from where it left off on the next run.

Hope this helps someone...

**Comment by kwameopareasiedu** [comment] 2022-01-01 03:44
@flutter As a suggestion, in the next update, make it such that when an error occurs downloading a particular dependency, delete only the dependency's files so that the Gradle cache is not corrupted and can be updated on the next Flutter run...

**Comment by ameenbadri7** [comment] 2022-01-25 11:45
It's wasted my 30GB of cached Gradle files. 
it makes me very angry .. 
please help us .. do anything to stop this madness..

**Comment by ameenbadri7** [comment] 2022-01-25 12:19
I'm pretty constrained about bandwidth and in this same position are many developers in my country. For example if flutter deletes my gradle cache due to unstable network (which is pretty usual) losing 2-4 GB of previously downloaded data is a hit. And as a workaround I've made a backup of the gradle folder and re-extract it every time flutter-beta cleans my cache , which sadly happens many times a day. At least for me as a developer with inconsistent internet access due to connection resets its really a stepback. Personally manually managing gradle issues and zip corruptions at least for me has not been that common issue. Would it be possible to evaluate this default behavior or at least provide a configuration flag to turn it off. This would really be an impediment for me to work with flutter.

**Comment by ameenbadri7** [comment] 2022-01-25 12:21
on 2.8.0 it's also happening. 
conformed.

**Comment by ameenbadri7** [comment] 2022-01-25 12:23
from https://github.com/flutter/flutter/issues/89000
> I'm pretty constrained about bandwidth and in this same position are many developers in my country. For example if flutter deletes my gradle cache due to unstable network (which is pretty usual) losing 2-4 GB of previously downloaded data is a hit. And as a workaround I've made a backup of the gradle folder and re-extract it every time flutter-beta cleans my cache , which sadly happens many times a day. At least for me as a developer with inconsistent internet access due to connection resets its really a stepback. Personally manually managing gradle issues and zip corruptions at least for me has not been that common issue. Would it be possible to evaluate this default behavior or at least provide a configuration flag to turn it off. This would really be an impediment for me to work with flutter.

**Comment by asatayo** [comment] 2022-01-25 12:44
The only workaround I had to do is to create the copy of zip file every
moment certainly one hour, so When it gets deleted I unzip the copy and
life goes on 🔥🔥

**Comment by Nawbc** [comment] 2022-02-25 14:54
Any update on this? It also deletes other projects' cache. 🤒

**Comment by iampato** [comment] 2022-02-28 20:12
Quick fix that works for me disable network, open project and run the project once it is run enable network

**Comment by ameenbadri7** [comment] 2022-03-02 19:21
> The only workaround I had to do is to create the copy of zip file every moment certainly one hour, so When it gets deleted I unzip the copy and life goes on 🔥🔥

this saves me the rest life i have.
thank you sir

**Comment by ziakhan110** [comment] 2022-03-07 10:05
this is not acceptable, wasted 2 days on this, also another developer from our company lost a week, he has poor internet, this is completely impractical solution.

**Comment by asatayo** [comment] 2022-03-07 11:26
I had only to what I shared above, only keep a  copy of zipped .gradle
directory anytime it gets deleted you simply unzip the zip one 🔥🔥🔥

**Comment by ZhangQinglian** [comment] 2022-03-22 06:25
It is crazy, It will also delete gradle.properties and other project caches.

**Comment by nisiddharth** [comment] 2022-03-22 17:10
Apart from the data wastage stuff I am facing a very serious issue due to this problem.

At my college, my WiFi internet is behind an authenticated Squid proxy and I have to configure `systemProp.http.proxyHost` and other stuff in global `gradle.properties` for gradle downloads to work.

But this issue causes the whole `~/.gradle` directory to be deleted and hence taking down all settings with it. I can't Flutter build/run anymore. And for some reason adding the lines in project gradle.properties doesn't work for me.

**Comment by Ikxyz** [comment] 2022-03-24 13:18
Have wasted days on this, the worst part is it fails and start downloading again from beginning. this is frustrating

**Comment by Abdulrasheed1729** [comment] 2022-03-28 10:22
I have not been able to anything significant since last three days just because of this. It keeps deleting the `.gradle` folder whenever the internet connection is goes down sincey connection is not that really good.

**Comment by luiscib3r** [comment] 2022-04-03 14:13
I think I have partially solved this problem.

The solution:

1. Go to the folder where the sdk is located, for example: `~/flutter`
2. Locate the following file: ` ~/flutter/packages/flutter_tools/lib/src/android/gradle_errors.dart` and open it for editing.
3. Locate the definition of `networkErrorHandler`. In my case I found it on line 210. You can also do the following search: `The Gradle cache directory must be deleted`.
4. Comment out all code related to deleting the `.gradle` folder

```dart
@visibleForTesting
final GradleHandledError networkErrorHandler = GradleHandledError(
  test: _lineMatcher(const <String>[
    'java.io.FileNotFoundException: https://downloads.gradle.org',
    'java.io.IOException: Unable to tunnel through proxy',
    'java.lang.RuntimeException: Timeout of',
    'java.util.zip.ZipException: error in opening zip file',
    'javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake',
    'java.net.SocketException: Connection reset',
    'java.io.FileNotFoundException',
    "> Could not get resource 'http",
  ]),
  handler: ({
    required String line,
    required FlutterProject project,
    required bool usesAndroidX,
    required bool multidexEnabled,
  }) async {
    globals.printError(
      '${globals.logger.terminal.warningMark} Gradle threw an error while downloading artifacts from the network. '
      'Retrying to download...'
    );
    // try {
    //   final String? homeDir = globals.platform.environment['HOME'];
    //   if (homeDir != null) {
    //     final Directory directory = globals.fs.directory(globals.fs.path.join(homeDir, '.gradle'));
    //     ErrorHandlingFileSystem.deleteIfExists(directory, recursive: true);
    //   }
    // } on FileSystemException catch (err) {
    //   globals.printTrace('Failed to delete Gradle cache: $err');
    // }
    return GradleBuildStatus.retry;
  },
  eventLabel: 'network',
);
```

Now you need the flutter_tools package to be recompiled. To do this go to the `~/flutter/bin/cache` folder and delete the following files: `flutter_tools.stamp`  and `flutter_tools.snapshot`

Then run the `flutter doctor` command. You will see a message: `Building flutter tool...`. With this the `flutter_tools` package has been recompiled and this time it should not delete the `.gradle` folder when it detects a connection failure.

I assume that every time you update the SDK the same operation should be performed, so you should keep this in mind when you update to a new version of the SDK.

**Comment by dellgreen** [comment] 2022-05-05 09:18
As per @luiscib3r 

Ultimately, we have decided to patch this out in our flutter fork as this is costing us time and money to restore from the periodic damage that this is causing across the whole team and CI/CD pipeline.

**Comment by fzyzcjy** [comment] 2022-05-12 00:24
Hi, is there any updates?

**Comment by dellgreen** [comment] 2022-05-12 08:00
Duplicate of.  #92469 where it's now acknowledged as a mistake. Probably awaiting consensus on agreed solution by community and a pull request.

**Comment by blasten** [comment] 2022-05-31 20:20
https://github.com/flutter/flutter/pull/105054 fixes this issue

**Closed** 2022-06-03 17:08 UTC
Labels: tool, waiting for PR to land (fixed), t: gradle, customer: crowd, proposal, passed first triage, P4
