### ISSUE TITLE
image_picker crash on iPhone when tapping photo button more than once

### ISSUE THREAD

**Issue by callumclift** [flutter/flutter#26816] opened 2019-01-20 07:39 UTC
## Steps to Reproduce

 
Raising my first issue here so go easy on me if I don't get everything right!
```yml
image_picker: 0.4.12+1
```
When using the `image_picker` plugin on a real iPhone 8 Plus device I can reproduce a crash every time whereby if you tap the button to take a photo more than once in quick succession it is crashing the app. The chances are users of my app will run into this issue as maybe they will be impatient and tap the button to take a photo in quick succession.

Also i've found another crash whereby after you have successfully taken a photo and you are presented with the options 'Retake' and 'Use Photo' if you tap in the middle of the bottom bar in the same place where the button to take a picture is it will crash the app every time!

Really hope someone is able to take a look into this as I don't think I will be able to production release my app without the camera functionality being pretty nailed on as it is an essential part of the app, thanks!

Here is where the image_picker is called in my code but as far as i'm aware it's an issue with the plugin not with my code as the code is waiting for the image picker to do it's thing before setting the thumbnails in my app:
```dart
  void _getImage(BuildContext context, ImageSource source, int index) {
    //fetch an image using the image picker class
    ImagePicker.pickImage(source: source, maxWidth: 400.0).then((File image) {
      if (images[index] != null) {
        setState(() {
          //this is setting the image locally here
          images[index] = image;
        });
      } else {
        setState(() {
          images[index] = image;
        });
      }
      widget.setImages(images);
      Navigator.pop(context);
    });
  }
```
## Logs

I can't get any logs (maybe i'm just being stupid here) because even with the iPhone plugged in whenever the crash occurs the console just says 'Lost connection to device'

```
flutter doctor -v
[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.14 18A391, locale en-GB)
    • Flutter version 1.0.0 at /Users/*********/appDevelopment/flutter
    • Framework revision 5391447fae (7 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/********/Library/Android/sdk
    • Android NDK at /Users/**********/Library/Android/sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/***********/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[!] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    ✗ Verify that all connected devices have been paired with this computer in Xcode.
      If all devices have been paired, libimobiledevice and ideviceinstaller may require updating.
      To update with Brew, run:
        brew update
        brew uninstall --ignore-dependencies libimobiledevice
        brew uninstall --ignore-dependencies usbmuxd
        brew install --HEAD usbmuxd
        brew unlink usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    • ios-deploy 1.9.2
    ✗ ios-deploy out of date (1.9.4 is required). To upgrade with Brew:
        brew upgrade ios-deploy
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 25.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Community Edition (version 2017.3.5)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 25.0.1
    • Dart plugin version 173.4700

[✓] Connected device (2 available)
    • My iPhone • **************************************************** • ios • iOS 12.1.2
    • iPhone X        • 1E1BBC5A-D458-412B-BB6B-EC3AC1888009     • ios • iOS 12.1 (simulator)

! Doctor found issues in 1 category.
```

**Comment by zoechi** [comment] 2019-01-20 12:34
Duplicate of #19819

**Closed by zoechi** 2019-01-20 12:34 UTC

**Comment by ngoctranfire** [comment] 2020-02-19 11:47
I'm sadly still able to reproduce this and I'm on

  image_picker: ^0.6.0+17

Here is what my error looks like:

`java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.MethodChannel$Result.success(java.lang.Object)' on a null object reference
E/AndroidRuntime( 6932): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4845)
E/AndroidRuntime( 6932): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4886)
E/AndroidRuntime( 6932): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
E/AndroidRuntime( 6932): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime( 6932): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime( 6932): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
E/AndroidRuntime( 6932): 	at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime( 6932): 	at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime( 6932): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/AndroidRuntime( 6932): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 6932): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/AndroidRuntime( 6932): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
E/AndroidRuntime( 6932): Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.MethodChannel$Result.success(java.lang.Object)' on a null object reference
E/AndroidRuntime( 6932): 	at vn.hunghd.flutter.plugins.imagecropper.ImageCropperDelegate.finishWithSuccess(ImageCropperDelegate.java:115)
E/AndroidRuntime( 6932): 	at vn.hunghd.flutter.plugins.imagecropper.ImageCropperDelegate.onActivityResult(ImageCropperDelegate.java:99)
E/AndroidRuntime( 6932): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEnginePluginRegistry.java:634)
E/AndroidRuntime( 6932): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry.onActivityResult(FlutterEnginePluginRegistry.java:367)
E/AndroidRuntime( 6932): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:546)
E/AndroidRuntime( 6932): 	at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:594)
E/AndroidRuntime( 6932): 	at android.app.Activity.dispatchActivityResult(Activity.java:8110)
E/AndroidRuntime( 6932): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4838)
E/AndroidRuntime( 6932): 	... 11 more
I/Process ( 6932): Sending signal. PID: 6932 SIG: 9`
