### ISSUE TITLE
[webview_flutter][IOS][Flutter 2.0] WebViews into ScrollView are partly visible after scrolling them out of page

### ISSUE THREAD

**Issue by bohdan1krokhmaliuk** [flutter/flutter#79276] opened 2021-03-29 15:12 UTC
## Description
[IOS only, Flutter 2.0 only]
WebViews used in flutter v1.22.6 were working just fine. But after upgrading to flutter 2.0 webviews in SingleChildScrollView or in CustomScrollView are overriding other elements / sticking to the top of the page. No errors or exceptions are not thrown.

I tried it with different versions of `webview_flutter` and it works same bad on flutter 2.0 and it works absolutely fine on flutter 1.22.6

## Steps to Reproduce

1. fetch project https://github.com/bohdan1krokhmaliuk/Flutter-2.0-WebView-issue.git
2. run it with flutter 2.0
3. scroll single child scroll view in order vimeo webview to hide under the header.

https://user-images.githubusercontent.com/59435984/112861832-d7487200-90bd-11eb-9bec-058a9d25a5a7.mov

**Comment by TahaTesser** [comment] 2021-03-30 08:05
Hi @bohdan1krokhmaliuk 
Thanks for filing the issue

I can reproduce the issue on latest flutter `stable` & `master` channels and i can comfirm the issue doesn't exist on `1.22.6` 
it looks like a duplicate of https://github.com/flutter/flutter/issues/76097, which also doesn't reproduce on `1.22.6`

|  webview (1.22.6)| webiew (2.1) | maps (1.22.6) |  maps (2.1) |
| --------------- | --------------- |--------------- |--------------- |
 ![ezgif com-gif-maker (4)](https://user-images.githubusercontent.com/48603081/112954823-71083180-9147-11eb-9826-a09dafc816bd.gif) | ![ezgif com-gif-maker (5)](https://user-images.githubusercontent.com/48603081/112954965-985efe80-9147-11eb-9940-0d20ff8c12ae.gif) | ![ezgif com-gif-maker (2)](https://user-images.githubusercontent.com/48603081/112954657-44541a00-9147-11eb-9f75-b22d641eb2aa.gif) | ![ezgif com-gif-maker (3)](https://user-images.githubusercontent.com/48603081/112954734-59c94400-9147-11eb-8eae-57409f8a1a4d.gif)

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 2.0.3, on macOS 11.2.3 20D91 darwin-x64, locale
    en-GB)
    • Flutter version 2.0.3 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 4d7946a68d (11 days ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.54.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (3 available)
    • iPhone 12 (mobile) • 83060656-28E7-44CD-801E-B11EC3EC89BA • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • macOS (desktop)    • macos                                • darwin-x64
      • macOS 11.2.3 20D91 darwin-x64
    • Chrome (web)       • chrome                               • web-javascript
      • Google Chrome 89.0.4389.90

• No issues found!
```

```bash
[✓] Flutter (Channel master, 2.1.0-13.0.pre.322, on macOS 11.2.3 20D91
    darwin-x64, locale en-GB)
    • Flutter version 2.1.0-13.0.pre.322 at
      /Users/tahatesser/Code/flutter_master
    • Framework revision e93590474d (2 hours ago), 2021-03-30 02:14:03 -0400
    • Engine revision dbcbf69a57
    • Dart version 2.13.0 (build 2.13.0-175.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.54.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (3 available)
    • iPhone 12 (mobile) • 83060656-28E7-44CD-801E-B11EC3EC89BA • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • macOS (desktop)    • macos                                • darwin-x64
      • macOS 11.2.3 20D91 darwin-x64
    • Chrome (web)       • chrome                               • web-javascript
      • Google Chrome 89.0.4389.90

• No issues found!
```
	
</details>

Closing as duplicate of https://github.com/flutter/flutter/issues/76097
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-03-30 08:05 UTC
Labels: in triage
