### ISSUE TITLE
Long press drag on Android selects word and expands selection by words

### ISSUE THREAD

**Issue by xster** [flutter/flutter#26394] opened 2019-01-10 23:40 UTC

**Comment by xster** [comment] 2019-02-07 01:50
This is actually implemented in #26001 now but I didn't implement edge scrolling from the drag in that PR.

**Comment by Renzo-Olivares** [comment] 2022-09-23 20:23
cc @xster what is missing to be able to close this issue? I think the behavior described in the issue is working as expected on master.

**Comment by justinmc** [comment] 2022-09-26 18:41
It looks to me like long press + drag + edge scroll still doesn't work (there are more than 4 lines of text here):

https://user-images.githubusercontent.com/389558/192354969-dd6cc2d4-4612-461b-a997-9b1eaa46ea0a.mov

**Closed** 2022-10-24 21:14 UTC
Labels: a: text input, platform-android, framework, f: material design, passed first triage, P4
