### ISSUE TITLE
Issue with Flutter version 3.13.9 - Loss of focus during password input on Android due to secure keyboard, while version 3.10.7 does not have this problem

### ISSUE THREAD

**Issue by 21pages** [flutter/flutter#140580] opened 2023-12-24 06:00 UTC
### Steps to reproduce

1. `git clone https://github.com/21pages/flutter_android_password_focus.git`
2. Prepare a mobile phone that will pop up a secure keyboard when entering the password. My mobile phone is vivo, android 13
3. Run project `password_focus_3_10_7` with flutter 3.10.7,  
    click `name` TextField , the focus is on `name` TextField ; 
    click `password` TextField , secure keyboard pops up, the focus is still on `password` TextField.
4. Run project `password_focus_3_13_9` with flutter 3.13.9, 
    click `name` TextField , the focus is on `name` TextField ; 
    click `password` TextField , secure keyboard pops up, the focus is not on `password` TextField.

### Expected results

Click `password` TextField , secure keyboard pops up, the focus is still on `password` TextField.

### Actual results

Click `password` TextField , secure keyboard pops up, the focus is not on `password` TextField.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter 3.13.9'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: const Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            TextField(
              decoration: InputDecoration(hintText: 'name'),
            ),
            TextField(
              obscureText: true,
              decoration: InputDecoration(hintText: 'password will lose focus'),
            )
          ],
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

Can't record screen when input password.

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[!] Flutter (Channel [user-branch], 3.13.9, on Ubuntu 22.04.3 LTS 6.2.0-39-generic, locale zh_CN.UTF-8)
    ! Flutter version 3.13.9 on channel [user-branch] at /home/sun/flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at https://flutter.dev/docs/get-started/install.
    ! Upstream repository unknown source is not a standard remote.
      Set environment variable "FLUTTER_GIT_URL" to unknown source to dismiss this error.
    • Framework revision d211f42860 (8 周前), 2023-10-25 13:42:25 -0700
    • Engine revision 0545f8705d
    • Dart version 3.1.5
    • DevTools version 2.25.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and
      upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /home/sun/Android/Sdk
    • Platform android-33-ext5, build-tools 33.0.2
    • Java binary at: /home/sun/android/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 14.0.0-1ubuntu1.1
    • cmake version 3.22.1
    • ninja version 1.10.1
    • pkg-config version 0.29.2

[✓] Android Studio (version 2022.1)
    • Android Studio at /home/sun/android/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.82.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.78.0

[✓] Connected device (3 available)
    • V2196A (mobile) • 10AC4F0S0Y000P3 • android-arm64  • Android 13 (API 33)
    • Linux (desktop) • linux           • linux-x64      • Ubuntu 22.04.3 LTS 6.2.0-39-generic
    • Chrome (web)    • chrome          • web-javascript • Google Chrome 117.0.5938.88

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

**Comment by dam-ease** [comment] 2023-12-27 10:57
Thanks for filing this @21pages.
I can't seem to reproduce this on the latest version of flutter `3.16.5`.
Can you upgrade to the latest version to confirm this issue still persists on your end?

**Comment by dam-ease** [comment] 2023-12-28 07:48
Thanks for your response @21pages.
I can't reproduce this on my end (see video below), this could be device-specific, can you share a video of how this code sample reproduces this issue on your end?

[untitled2.webm](https://github.com/flutter/flutter/assets/53122008/72e0dd9d-b405-4578-94af-a60424a13d23)

**Comment by 21pages** [comment] 2023-12-28 07:57
https://github.com/flutter/flutter/assets/14891774/56996a0c-e6ea-43b5-8a7e-ea8db1a45cc4

**Comment by camsim99** [comment] 2024-01-04 19:48
This seems to be the same issue as https://github.com/flutter/flutter/issues/140369. Closing as a duplicate but feel free to follow up there.

**Closed by camsim99** 2024-01-04 19:48 UTC
Labels: a: text input, c: regression, e: device-specific, platform-android, team-android
