### ISSUE TITLE
after updating to new version 1.6.18 or above i am getting this issue

### ISSUE THREAD

**Issue by HetalGohil** [flutter/flutter#72126] opened 2020-12-11 09:19 UTC
/D:/flutter_windows_v1.12.13+hotfix.5-stable/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_cache_manager-2.0.0/lib/src/storage/cache_info_repositories/cache_object_provider.dart:82:18: Error: The method 'isDuplicateColumnError' isn't defined for the class 'DatabaseException'.
 - 'DatabaseException' is from 'package:sqflite_common/src/exception.dart' ('/D:/flutter_windows_v1.12.13+hotfix.5-stable/flutter/.pub-cache/hosted/pub.dartlang.org/sqflite_common-1.0.1/lib/src/exception.dart').
Try correcting the name to the name of an existing method, or defining a method named 'isDuplicateColumnError'.
          if (!e.isDuplicateColumnError(CacheObject.columnLength)) rethrow;
                 ^^^^^^^^^^^^^^^^^^^^^^

**Comment by pedromassangocode** [comment] 2020-12-11 09:38
Hi @HetalGohil 
From what I can see, the issue is related to a 3rd party package rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/Baseflow/flutter_cache_manager).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by pedromassangocode** 2020-12-11 09:38 UTC
