### ISSUE TITLE
[plugins/firebase_auth] [plugins/cloud_firestore] custom claims not propagated on Android with user.getIdToken(refresh: true)

### ISSUE THREAD

**Issue by pboos** [flutter/flutter#22801] opened 2018-10-08 07:03 UTC
According to https://firebase.google.com/docs/auth/admin/custom-claims#propagate_custom_claims_to_the_client one can update the claims locally by calling `currentUser.getIdToken(true)`.

In flutter I guess one should be able to do the same with:

```dart
final user = await FirebaseAuth.instance.currentUser();
await user.getIdToken(refresh: true);
```

Sadly this seems not reflected when I try to use firestore. After updating claims through a cloud function and then calling getIdToken as above it will still not have the claims correct in firestore rules. It returns "PERMISSION_DENIED". When I then close the app and reopen the app, firestore rules go through correctly though (seems like claims then get updated).

Additional problem is, that I can not see if the claims locally got updated or not because the API for that is not yet implemented (see separate issue #20238).

Now the issue is: How can force propagation of the claims in flutter? The way the documentation says seems not to be correct. Is this a bug in the documentation or a bug in the flutter client?

flutter: v0.8.2
cloud_firestore: 0.8.1
firebase_auth: 0.5.20

### Edit
After further investigations it seems to only be happening on Android. On iOS the claims seem to be updated nicely (seems to work even without calling getIdToken() ). So this problem seems Android specific.

**Comment by vishant-jaiswal** [comment] 2018-11-30 12:01
any update on this

**Comment by YamauchiEA** [comment] 2018-12-07 17:11
Same problem.  The custom claims are extremely important for security questions.

**Comment by zoechi** [comment] 2018-12-09 16:00
Duplicate of #20238

**Comment by hariprasadiit** [comment] 2018-12-19 08:55
@zoechi I don't this is a duplicate of #20238 . This issue talks about bug where custom claims are not getting updated when they are updated using firebase admin SDK. This seems to be the issue with native Firebase Android Auth SDK bug. Related SO question https://stackoverflow.com/questions/48042934/firebase-auth-custom-claims-not-propagating-to-client

#20238 talks about just accessing custom claims from flutter, which are already accessible using native SDKs with 
```java
user.getIdToken(false).addOnSuccessListener(new OnSuccessListener<GetTokenResult>() {
  @Override
  public void onSuccess(GetTokenResult result) {
    boolean isAdmin = result.getClaims().get("admin");
    if (isAdmin) {
      // Show admin UI.
      showAdminUI();
    } else {
      // Show regular user UI.
      showRegularUI();
    }
  }
});

```

`getClaims()` method is not available in flutter

**Comment by pboos** [comment] 2018-12-21 06:34
Yes, even though I would like the API to be accessible. This issue has nothing to do with the API not being available in flutter. It has to do with Android not behaving as the documentation says. iOS on the other hand works correctly. It could probably be that this is actually a bug on android itself and not the flutter plugin.

**Comment by long1eu** [comment] 2019-07-29 06:38
I'm doing a RP for this.

**Comment by kroikie** [comment] 2019-10-13 18:46
@pboos

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/621. Any further collaboration will be done there.

**Closed by kroikie** 2019-10-13 18:46 UTC
Labels: p: cloud_firestore, p: firebase, p: firebase_auth, p: first party, plugin
