### ISSUE TITLE
 in flutter project dart code completion,delete the after normal code

### ISSUE THREAD

**Issue by longforus** [flutter/flutter#25356] opened 2018-12-14 07:08 UTC
## Steps to Reproduce

Android studio Build: 3.2.1, AI-181.5540.7.32.5056338, 201810090144,
flutter version: 1.0.0
my code like this:
```dart
  Widget _titleSection(BuildContext context) {
    return Container(
      padding: const EdgeInsets.all(32.0),
      child: Row(
        children: <Widget>[
          Expanded(child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: <Widget>[
              Container(
                padding: const EdgeInsets.only(bottom: 8.0),
                child: Text('Long for us',
                  style: TextStyle(
                    fontWeight: FontWeight.b  // code completion here


                ),),
              )
            ],
          ))
        ],
      ),
    );
  }
```
After completing the FontWeight.bold  code auto change to :
```dart
  Widget _titleSection(BuildContext context) {
    return Container(
      padding: const EdgeInsets.all(32.0),
      child: Row(
        children: <Widget>[
          Expanded(child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: <Widget>[
              Container(
                padding: const EdgeInsets.only(bottom: 8.0),
                child: Text('Long for us',
                  style: TextStyle(
                    fontWeight: FontWeight.bold,
          ))
        ],
      ),
    );
  }
```

auto deleted
```           
               ),),
              )
            ],
```

This caused an error in my code,this is a bug.

today ,I found that it only appeared when I didn't write the `new` keyword, It still needs fixing

**Comment by zoechi** [comment] 2018-12-14 10:16
Would you mind reporting this in https://github.com/dart-lang/sdk
This functionality is provided by dartanalyzer which is maintained there 
and the issue will probably get more attention there.

**Comment by longforus** [comment] 2018-12-15 05:47
@zoechi ok

**Comment by zoechi** [comment] 2018-12-16 13:40
Duplicate of dart-lang/sdk#35422

**Closed** 2018-12-16 13:41 UTC
