### ISSUE TITLE
Render Issue When Trying To Fill A Container With A Custom Emoji

### ISSUE THREAD

**Issue by JeffersonBledsoe** [flutter/flutter#21707] opened 2018-09-11 23:01 UTC
## Steps to Reproduce
When trying to fill a Text or Icon widget with an emoji, the icon does not fill the height of the container. After a set height which is less than the height of the container (haven't been able to figure out a correlation to the container height and the set height), the emoji does not get displayed. 

```
  @override
  Widget build(BuildContext context) {
    // emojiCode is an int
    final _icon = IconData (model.emojiCode, fontFamily: "Noto Emoji");

    return Container (
      color: Colors.green,
      height: 200.0,
      child: Icon (
        _icon,
        size: 85.0, // Displayed at 85, but not at 86
      ),
    );
  }
```

Custom icon at `size: 85.0`:
<img width="265" alt="screen shot" src="https://user-images.githubusercontent.com/30210785/45392360-e742f800-b61e-11e8-8add-c25bf2e94c88.png">

Custom icon at `size: 86.0`:
<img width="266" alt="screen shot 1" src="https://user-images.githubusercontent.com/30210785/45392373-f5911400-b61e-11e8-96ad-4c2ddc9ac5b8.png">

In-built Flutter Icon at `size: 190.0`:
<img width="266" alt="screen shot 2" src="https://user-images.githubusercontent.com/30210785/45392389-02156c80-b61f-11e8-87d4-ada5edf722d9.png">

**Comment by zoechi** [comment] 2018-09-12 05:50
Please add the output of `flutter doctor -v`.

Your question title is "Render error ...". Do you actually see any error output in the console?

With this code

```dart
import 'package:flutter/material.dart';

void main() => runApp(new MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      home: new MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => new _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      body: new Center(
        child:
            // emojiCode is an int
            Container(
          color: Colors.green,
          height: 200.0,
          child: Icon(
            IconData(0x1F603, fontFamily: "Noto Emoji"),
            size: 86.0, // Displayed at 85, but not at 86
          ),
        ),
      ),
    );
  }
}
```

I get 
![image](https://user-images.githubusercontent.com/405837/45404365-d7e39f00-b65e-11e8-84b9-55fb6d4e7863.png)

```
 $ flutter doctor -v
[✓] Flutter (Channel dev, v0.8.2, on Mac OS X 10.13.6 17G65, locale en-AT)
    • Flutter version 0.8.2 at /Users/zoechi/flutter/flutter
    • Framework revision 5ab9e70727 (4 days ago), 2018-09-07 12:33:05 -0700
    • Engine revision 58a1894a1c
    • Dart version 2.1.0-dev.3.1.flutter-760a9690c2

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.1)
    • Android SDK at /usr/local/opt/android-sdk
    • Android NDK at /usr/local/opt/android-sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.1
    • ANDROID_HOME = /usr/local/opt/android-sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 2.0.0
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 23.1.2
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 26.0.3
    • Dart plugin version 182.3569.4

[✓] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

• No issues found!
```

**Comment by JeffersonBledsoe** [comment] 2018-09-12 23:05
Here is the `flutter doctor` output:
```
[✓] Flutter (Channel beta, v0.7.3, on Mac OS X 10.13.6 17G65, locale en-GB)
    • Flutter version 0.7.3 at /Applications/flutter
    • Framework revision 3b309bda07 (2 weeks ago), 2018-08-28 12:39:24 -0700
    • Engine revision af42b6dc95
    • Dart version 2.1.0-dev.1.0.flutter-ccb16f7282

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/Jefferson/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.0, Build version 10L176w
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 27.1.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] VS Code (version 1.27.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.18.0

[✓] Connected devices (1 available)
    • iPhone 8 Plus • 949E938F-6DB0-4FA3-9C9D-447E88D4D485 • ios • iOS 12.0 (simulator)

• No issues found!
```

I don't receive any errors from the dart analysis or from the runtime output. Copy-pasting your code into a new flutter project still gives me the same results, anything over the size of 85 causes the emoji to disappear. I've also tried setting larger heights of the container (400 rather than 200) and setting the width to both 200 and 400, and any value after 85.3 causes the emoji to not be displayed

**Comment by jason-simmons** [comment] 2018-10-03 00:42
This is similar to https://github.com/flutter/flutter/issues/16386

When the font size exceeds some threshold `SkPaint::TooBigToUseCache` will return true, causing `SkGlyphRunListPainter::drawForBitmapDevice` to try to draw the text as a path.  However, `SkScalerContext_FreeType::generatePath` can not create a path for the glyphs in the emoji bitmap font. 

The perPath handler in `SkDraw::drawGlyphRunList` then receives the null path and is unable to render anything.

**Comment by GaryQian** [comment] 2020-03-26 22:27
cc @jason-simmons It has been a while since the last update, and Skia seems to claim this is fixed. Can you verify?

**Comment by darshankawar** [comment] 2020-09-08 10:22
Verified this on latest stable (1.20.3) on Samsung S10+ device and confirmed that with size 86, the emoji is displayed properly.

![21707_85](https://user-images.githubusercontent.com/67046386/92464702-2646bc80-f1eb-11ea-9051-b661cc4ded2a.png)

![21707_86](https://user-images.githubusercontent.com/67046386/92464709-29da4380-f1eb-11ea-96cb-8fc1edee8692.png)


<details>
<summary>flutter doctor -v</summary>

```
Flutter 1.20.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 216dee60c0 (2 days ago) • 2020-09-01 12:24:47 -0700
Engine • revision d1bc06f032
Tools • Dart 2.9.2

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.20.3, on Mac OS X 10.15.2 19C57, locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions.
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
[✓] Android Studio (version 3.6)
[✓] Connected device (1 available)
```

</details>

Closing this as fixed. If you disagree, write in comments and I'll reopen.
Thanks.

**Closed by darshankawar** 2020-09-08 10:22 UTC
Labels: P4, a: typography, dependency: skia, engine, framework
