### ISSUE TITLE
[integration_test] Flutter drive reports "All tests passed" when an exception occurs in setup block

### ISSUE THREAD

**Issue by swallow66** [flutter/flutter#151480] opened 2024-07-09 18:39 UTC
### Steps to reproduce

While "flutter test" is still not implemented for web devices, we use flutter drive command to run flutter integration tests for web application in Chrome. 

1. Implement flutter integration test containing setUp (setUpAll) block
2. Setup block throws an exception
3. Run integration test with flutter drive command

`flutter drive --verbose-system-logs --driver=C:\App\test_driver\integration_test.dart --target=C:\App\integration_test\test.dart -d web-server --browser-name=chrome --web-port=2021 --browser-dimension=1600,1024 --dart-define-from-file "C:\App\appsettings.dev.json" --no-headless`

### Expected results

Flutter drive command reports test body result as Failed or at least Skipped/Indistinct

### Actual results

Test body itself is not executed. Flutter drive command reports "All tests passed" result, so the test is considered PASSED, but it was not even executed.

### Code sample

<details open><summary>Code sample</summary>

```dart

-------------- test.dart ------------------
import 'package:flutter/widgets.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:integration_test/integration_test.dart';

void main() {
   final binding = IntegrationTestWidgetsFlutterBinding.ensureInitialized();

  group('network check page', () {
    setUp(() async {
       throw new Exception("test message");
    });
    tearDownAll(() async {
       // teardown actions
    });
    testWidgets('verify home page', (tester) async {
      expect(find.byKey("homeCardId"), findsOneWidget);
      await tester.pumpAndSettle();
    });
  });
}

--------------------- test_driver/integration_test.dart -------------------
import 'dart:io';
import 'package:integration_test/integration_test_driver_extended.dart';
import 'package:intl/intl.dart';

Future<void> main() async {
  try {
    await integrationDriver(
      writeResponseOnFailure: true,
      onScreenshot: (screenshotName, screenshotBytes, [args]) async {
        String name = 'integration_test/results/screenshots/$screenshotName.png';
        final File image = await File(name).create(recursive: true);
        image.writeAsBytesSync(screenshotBytes);
        return true;
      }
    );
  } catch (e) {
    print('Error occured: $e');
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.19.2, on Microsoft Windows [Version 10.0.19045.4529], locale en-CA)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[√] Android Studio (version 2022.3)
[√] VS Code (version 1.91.0)
[√] Connected device (3 available)
[√] Network resources
```

</details>

**Comment by darshankawar** [comment] 2024-07-10 07:18
Closing this as duplicate of https://github.com/flutter/flutter/issues/129041. Please follow-up in it for further updates.

**Closed by darshankawar** 2024-07-10 07:18 UTC
Labels: in triage
