### ISSUE TITLE
Several web tests flaking in presubmit, blocking rolls

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#124679] opened 2023-04-12 14:59 UTC
https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20linux_web_engine/2178/overview from the Dart roll attempt here https://github.com/flutter/engine/pull/41113.

If the flakes are caused by the roll, that should also be determined, but I suspect the tests are just flaking.

**Comment by eyebrowsoffire** [comment] 2023-04-12 17:12
I think the ones popping up on Windows (`chrome-dart2js-html-engine` suite) are legitimate test failures from the roll. Error output here:

```
00:18 +331 ~18 -1: history_test.dart: MultiEntriesBrowserHistory handle user-provided url [E]                                                                                                          
  NoSuchMethodError: method not found: '$index' on null
  ..\..\..\..\flutter\lib\web_ui\lib\src\engine\navigation\history.dart 204:52  MultiEntriesBrowserHistory.onPopState
  org-dartlang-sdk:///lib/_internal/js_runtime/lib/js_helper.dart 2303:9        tear.off.<fn>
  ..\..\..\..\flutter\lib\web_ui\lib\src\engine\test_embedding.dart 176:7       TestUrlStrategy._firePopStateEvent
  ..\..\..\..\flutter\lib\web_ui\lib\src\engine\test_embedding.dart 131:7       TestUrlStrategy.simulateUserTypingUrl.<fn>
  ..\..\..\..\flutter\lib\web_ui\lib\src\engine\test_embedding.dart 167:60      TestUrlStrategy._nextEventLoop.<fn>
  org-dartlang-sdk:///lib/async/zone.dart 1407:39                               StaticClosure._rootRunUnary
  org-dartlang-sdk:///lib/async/zone.dart 1307:34                               _CustomZone.runUnary
  org-dartlang-sdk:///lib/async/future_impl.dart 147:18                         _FutureListener.handleValue
  org-dartlang-sdk:///lib/async/future_impl.dart 784:36                         _Future._propagateToListeners.handleValueCallback
  org-dartlang-sdk:///lib/async/future_impl.dart 813:13                         Object._Future._propagateToListeners
```

 The failures on Mac (`safari-dart2js-canvaskit-ui`) seem like a separate issue having to do with the skia-gold client: 

```
/Volumes/Work/s/w/ir/cache/gold/goldctl imgtest init --instance flutter-engine --work-dir /Volumes/Work/s/w/ir/cache/builder/src/flutter/lib/web_ui/.dart_tool/skia_gold/safari-dart2js-canvaskit-ui/temp --commit f1fb2098cb69c78aacc887bcb706d5c5fabdfa44 --keys-file /Volumes/Work/s/w/ir/cache/builder/src/flutter/lib/web_ui/.dart_tool/skia_gold/safari-dart2js-canvaskit-ui/keys.json --failure-file /Volumes/Work/s/w/ir/cache/builder/src/flutter/lib/web_ui/.dart_tool/skia_gold/safari-dart2js-canvaskit-ui/failures.json --passfail --crs github --patchset_id f1fb2098cb69c78aacc887bcb706d5c5fabdfa44 --changelist 41113 --cis buildbucket --jobid 8784030208939787873
/Volumes/Work/s/w/ir/cache/gold/goldctl imgtest add --work-dir /Volumes/Work/s/w/ir/cache/builder/src/flutter/lib/web_ui/.dart_tool/skia_gold/safari-dart2js-canvaskit-ui/temp --test-name scene_builder_centered_circle --png-file /Volumes/Work/s/w/ir/cache/builder/src/flutter/lib/web_ui/.dart_tool/skia_gold/safari-dart2js-canvaskit-ui/scene_builder_centered_circle.png --add-test-optional-key image_matching_algorithm:fuzzy --add-test-optional-key fuzzy_max_different_pixels:900 --add-test-optional-key fuzzy_pixel_delta_threshold:21

00:02 [32m+4[0m[31m -1[0m: [1m[90mloading scene_builder_test.dart[0m [1m[31m[E][0m[0m                                                                                                                                                       
  Exception: Unexpected Gold tryjobAdd failure.
  Tryjob execution for golden file test scene_builder_centered_circle.png failed for
  a reason unrelated to pixel comparison.
  
  Debug information for Gold:
  stdout: 
  stderr: Error running command: ''invalid test config: field "gitHash", "commit_id", or "change_list_id" must be set.. At jsonio.go:153 goldclient.go:314 goldclient.go:277 cmd_imgtest.go:363 cmd_imgtest.go:294 command.go:860 command.go:974 command.go:902 command.go:895 main.go:54 proc.go:255 asm_amd64.s:1581''
  
  
  
  package:skia_gold_client/skia_gold_client.dart 347:7  SkiaGoldClient._tryjobAdd
  ===== asynchronous gap ===========================
  package:skia_gold_client/skia_gold_client.dart 206:7  SkiaGoldClient.addImg
  ```

That seems unlikely to be related to the roll.

**Comment by eyebrowsoffire** [comment] 2023-04-12 18:20
I did a bisect and the `MultiEntriesBrowserHistory` was caused by https://dart-review.googlesource.com/c/sdk/+/271480, but that has already been reverted here: https://dart-review.googlesource.com/c/sdk/+/271480. So at least that one should not be blocking the roll.

**Comment by yjbanov** [comment] 2023-04-13 18:31
Closing as the offending commit was reverted.

**Closed by yjbanov** 2023-04-13 18:31 UTC
Labels: team: flakes, platform-web
