### ISSUE TITLE
Snackbar appearing on top with SnackBarBehavior.floating and FloatingActionButtonLocation.miniCenterTop

### ISSUE THREAD

**Issue by neerajyadav** [flutter/flutter#66210] opened 2020-09-20 08:24 UTC
### Problem
Snackbar appears on top of screen if used with behavior `SnackBarBehavior.floating` and FAB location is `miniCenterTop`. 

### Expected Behaviour
Snackbar should appear at bottom of the screen.

### Steps to Reproduce
Run `main.dart`

``` dart
import 'package:flutter/material.dart';

final Color darkBlue = Color.fromARGB(255, 18, 32, 47);

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(scaffoldBackgroundColor: darkBlue),
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: Center(
          child: MyWidget(),
        ),
        floatingActionButton: MyFAB(),
        floatingActionButtonLocation:
            FloatingActionButtonLocation.miniCenterTop,
      ),
    );
  }
}

class MyWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Text('Hello, World!', style: Theme.of(context).textTheme.headline4);
  }
}

class MyFAB extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return ElevatedButton.icon(
      style: ElevatedButton.styleFrom(
        padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 10),
      ),
      icon: Icon(Icons.error_outline_sharp),
      label: Text('Breakdown'),
      onPressed: () {
        print('sdfsdfdf');
        Scaffold.of(context).showSnackBar(SnackBar(
            behavior: SnackBarBehavior.floating,
            content: Text('Data saved successfully.')));
      },
    );
  }
}
```

### Flutter Doctor
``` log
[✓] Flutter (Channel beta, 1.22.0-12.1.pre, on macOS 11.0 20A5364e, locale en-IN)
    • Flutter version 1.22.0-12.1.pre at /Users/a/Library/flutter
    • Framework revision 8b3760638a (4 days ago), 2020-09-15 17:47:13 -0700
    • Engine revision 4654fc6cf6
    • Dart version 2.10.0 (build 2.10.0-110.3.beta)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/a/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.8.4

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[!] VS Code (version 1.49.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • AOSP on IA Emulator (mobile) • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)
```

**Comment by hamdikahloun** [comment] 2020-09-20 10:56
Hi @neerajyadav 

SnackBarBehavior.floating
This behavior will cause SnackBar to be shown above other widgets in the Scaffold. This includes being displayed above a BottomNavigationBar and a **FloatingActionButton**.

> floatingActionButtonLocation:  FloatingActionButtonLocation.miniCenterTop,

**Comment by darshankawar** [comment] 2020-09-21 08:26
Hi @neerajyadav,
This seems to be working as intended. Per the document:

```
floating → const SnackBarBehavior
This behavior will cause SnackBar to be shown above other widgets in the Scaffold. This includes being displayed above a BottomNavigationBar and a FloatingActionButton.

See material.io/design/components/snackbars.html for more details.

const SnackBarBehavior(1)
```

See [this](https://api.flutter.dev/flutter/material/SnackBarBehavior-class.html) for more details.

I am going ahead and closing this as WAI. If you disagree, write in comments and I'll reopen.
Thanks.

**Closed by darshankawar** 2020-09-21 08:26 UTC
