### ISSUE TITLE
Unable to find modules for some sources. No meaningful information provided on compile error. 

### ISSUE THREAD

**Issue by omontoya** [flutter/flutter#41012] opened 2019-09-21 03:23 UTC
flutter build web --verbose
```
[  +26 ms] executing: [/Users/omontoya/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +41 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 919cc97f6a3067faf84a0946132319933d0743a5
[        ] executing: [/Users/omontoya/flutter/] git describe --match v*.*.* --first-parent --long --tags
[  +23 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.10.5-29-g919cc97f6
[   +8 ms] executing: [/Users/omontoya/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +9 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [/Users/omontoya/flutter/] git ls-remote --get-url origin
[   +8 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +53 ms] executing: [/Users/omontoya/flutter/] git rev-parse --abbrev-ref HEAD
[  +10 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[   +6 ms] executing: sw_vers -productName
[  +15 ms] Exit code 0 from: sw_vers -productName
[        ] Mac OS X
[        ] executing: sw_vers -productVersion
[  +14 ms] Exit code 0 from: sw_vers -productVersion
[        ] 10.14.6
[        ] executing: sw_vers -buildVersion
[  +13 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 18G95
[  +13 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[ +282 ms] Compiling lib/main.dart for the Web...
[+8103 ms] Starting daemon...
[ +247 ms] Initializing inputs
[  +11 ms] Reading cached asset graph...
[ +278 ms] Reading cached asset graph completed, took 276ms

[ +254 ms] Checking for updates since last build...
[+1008 ms] Checking for updates since last build completed, took 1.0s

[  +14 ms] Initializing inputs
[   +2 ms] Reading cached asset graph...
[        ] Reading cached asset graph completed, took 276ms
[        ] Checking for updates since last build...
[        ] Checking for updates since last build completed, took 1.0s
[+1250 ms] About to build [web, test]...
[   +6 ms] Running build...
[ +254 ms] Running build completed, took 122ms

[   +1 ms] Caching finalized dependency graph...
[   +9 ms] Caching finalized dependency graph completed, took 168ms

[  +10 ms] Unable to find modules for some sources, this is usually the result of either a
           bad import, a missing dependency in a package (or possibly a dev_dependency
           needs to move to a real dependency), or a build failure (if importing a
           generated file).
           
           Please check the following imports:
           
           
[   +1 ms] #0      Module.computeTransitiveDependencies (package:build_modules/src/modules.dart:172:7)
           <asynchronous suspension>
           #1      _ensureTransitiveJsModules (package:build_web_compilers/src/dev_compiler_bootstrap.dart:144:37)
           <asynchronous suspension>
           #2      bootstrapDdc (package:build_web_compilers/src/dev_compiler_bootstrap.dart:37:33)
           <asynchronous suspension>
           #3      FlutterWebTestEntrypointBuilder.build (package:flutter_tools/src/build_runner/build_script.dart:221:11)
           <asynchronous suspension>
           #4      runBuilder.buildForInput (package:build/src/generate/run_builder.dart:45:21)
           <asynchronous suspension>
           #5      MappedListIterable.elementAt (dart:_internal/iterable.dart:415:29)
           #6      ListIterator.moveNext (dart:_internal/iterable.dart:344:26)
           #7      Future.wait (dart:async/future.dart:393:26)
           #8      runBuilder.<anonymous closure> (package:build/src/generate/run_builder.dart:51:36)
           #9      _rootRun (dart:async/zone.dart:1124:13)
           #10     _CustomZone.run (dart:async/zone.dart:1021:19)
           #11     _runZoned (dart:async/zone.dart:1516:10)
           #12     runZoned (dart:async/zone.dart:1500:12)
           #13     scopeLogAsync (package:build/src/builder/logging.dart:22:3)
           #14     runBuilder (package:build/src/generate/run_builder.dart:51:9)
           <asynchronous suspension>
           #15     _SingleBuild._runForInput.<anonymous closure>.<anonymous closure>.<anonymous closure>
           (package:build_runner_core/src/generate/build_impl.dart:472:19)
           #16     _NoOpBuilderActionTracker.trackStage (package:build_runner_core/src/generate/performance_tracker.dart:300:15)
           #17     _SingleBuild._runForInput.<anonymous closure>.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:470:23)
           <asynchronous suspension>
           #18     NoOpTimeTracker.track (package:timing/src/timing.dart:222:44)
           #19     _SingleBuild._runForInput.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:429:22)
           #20     Pool.withResource (package:pool/pool.dart:127:28)
           <asynchronous suspension>
           #21     _SingleBuild._runForInput (package:build_runner_core/src/generate/build_impl.dart:425:17)
           #22     _SingleBuild._runBuilder.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:373:38)
           #23     MappedIterator.moveNext (dart:_internal/iterable.dart:393:18)
           #24     Future.wait (dart:async/future.dart:393:26)
           #25     _SingleBuild._runBuilder (package:build_runner_core/src/generate/build_impl.dart:372:36)
           <asynchronous suspension>
           #26     _SingleBuild._runPhases.<anonymous closure>.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:319:20)
           <asynchronous suspension>
           #27     _NoOpBuildPerformanceTracker.trackBuildPhase (package:build_runner_core/src/generate/performance_tracker.dart:184:15)
           #28     _SingleBuild._runPhases.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:315:47)
           <asynchronous suspension>
           #29     NoOpTimeTracker.track (package:timing/src/timing.dart:222:44)
           #30     _SingleBuild._runPhases (package:build_runner_core/src/generate/build_impl.dart:309:32)
           #31     logTimedAsync (package:build_runner_core/src/logging/logging.dart:25:30)
           <asynchronous suspension>
           #32     _SingleBuild._safeBuild.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:266:26)
           <asynchronous suspension>
           #33     _rootRun (dart:async/zone.dart:1124:13)
           #34     _CustomZone.run (dart:async/zone.dart:1021:19)
           #35     _runZoned (dart:async/zone.dart:1516:10)
           #36     runZoned (dart:async/zone.dart:1500:12)
           #37     _SingleBuild._safeBuild (package:build_runner_core/src/generate/build_impl.dart:261:5)
           #38     _SingleBuild.run (package:build_runner_core/src/generate/build_impl.dart:208:24)
           <asynchronous suspension>
           #39     BuildImpl.run (package:build_runner_core/src/generate/build_impl.dart:96:42)
           #40     BuildRunnerDaemonBuilder.build (package:build_runner/src/daemon/daemon_builder.dart:100:35)
           <asynchronous suspension>
           #41     Server._build.<anonymous closure> (package:build_daemon/src/server.dart:122:25)
           #42     Pool.withResource (package:pool/pool.dart:127:28)
           <asynchronous suspension>
           #43     Server._build (package:build_daemon/src/server.dart:119:13)
           #44     Server.listen.<anonymous closure>.<anonymous closure> (package:build_daemon/src/server.dart:85:17)
           <asynchronous suspension>
           #45     _rootRunUnary (dart:async/zone.dart:1132:38)
           #46     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
           #47     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
           #48     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
           #49     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
           #50     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:764:19)
           #51     _StreamController._add (dart:async/stream_controller.dart:640:7)
           #52     _StreamController.add (dart:async/stream_controller.dart:586:5)
           #53     new WebSocketImpl.fromSocket.<anonymous closure> (package:web_socket_channel/src/copy/web_socket_impl.dart:719:21)
           #54     _rootRunUnary (dart:async/zone.dart:1132:38)
           #55     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
           #56     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
           #57     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
           #58     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
           #59     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
           #60     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
           #61     _WebSocketProtocolTransformer._messageFrameEnd (package:web_socket_channel/src/copy/web_socket_impl.dart:316:22)
           #62     _WebSocketProtocolTransformer.add (package:web_socket_channel/src/copy/web_socket_impl.dart:214:46)
           #63     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
           #64     _rootRunUnary (dart:async/zone.dart:1132:38)
           #65     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
           #66     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
           #67     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
           #68     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
           #69     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:764:19)
           #70     _StreamController._add (dart:async/stream_controller.dart:640:7)
           #71     _StreamController.add (dart:async/stream_controller.dart:586:5)
           #72     _Socket._onData (dart:io-patch/socket_patch.dart:1829:41)
           #73     _rootRunUnary (dart:async/zone.dart:1136:13)
           #74     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
           #75     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
           #76     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
           #77     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
           #78     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:764:19)
           #79     _StreamController._add (dart:async/stream_controller.dart:640:7)
           #80     _StreamController.add (dart:async/stream_controller.dart:586:5)
           #81     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1377:33)
           #82     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:897:14)
           #83     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #84     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #85     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
           #86     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)

[   +5 ms] Unable to find modules for some sources, this is usually the result of either a
           bad import, a missing dependency in a package (or possibly a dev_dependency
           needs to move to a real dependency), or a build failure (if importing a
           generated file).
           
           Please check the following imports:
           
           
[        ] #0      Module.computeTransitiveDependencies (package:build_modules/src/modules.dart:172:7)
           <asynchronous suspension>
           #1      bootstrapDart2Js (package:flutter_tools/src/build_runner/build_script.dart:425:45)
           <asynchronous suspension>
           #2      FlutterWebEntrypointBuilder.build (package:flutter_tools/src/build_runner/build_script.dart:248:13)
           <asynchronous suspension>
           #3      runBuilder.buildForInput (package:build/src/generate/run_builder.dart:45:21)
           <asynchronous suspension>
           #4      MappedListIterable.elementAt (dart:_internal/iterable.dart:415:29)
           #5      ListIterator.moveNext (dart:_internal/iterable.dart:344:26)
           #6      Future.wait (dart:async/future.dart:393:26)
           #7      runBuilder.<anonymous closure> (package:build/src/generate/run_builder.dart:51:36)
           #8      _rootRun (dart:async/zone.dart:1124:13)
           #9      _CustomZone.run (dart:async/zone.dart:1021:19)
           #10     _runZoned (dart:async/zone.dart:1516:10)
           #11     runZoned (dart:async/zone.dart:1500:12)
           #12     scopeLogAsync (package:build/src/builder/logging.dart:22:3)
           #13     runBuilder (package:build/src/generate/run_builder.dart:51:9)
           <asynchronous suspension>
           #14     _SingleBuild._runForInput.<anonymous closure>.<anonymous closure>.<anonymous closure>
           (package:build_runner_core/src/generate/build_impl.dart:472:19)
           #15     _NoOpBuilderActionTracker.trackStage (package:build_runner_core/src/generate/performance_tracker.dart:300:15)
           #16     _SingleBuild._runForInput.<anonymous closure>.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:470:23)
           <asynchronous suspension>
           #17     NoOpTimeTracker.track (package:timing/src/timing.dart:222:44)
           #18     _SingleBuild._runForInput.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:429:22)
           #19     Pool.withResource (package:pool/pool.dart:127:28)
           <asynchronous suspension>
           #20     _SingleBuild._runForInput (package:build_runner_core/src/generate/build_impl.dart:425:17)
           #21     _SingleBuild._runBuilder.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:373:38)
           #22     MappedIterator.moveNext (dart:_internal/iterable.dart:393:18)
           #23     Future.wait (dart:async/future.dart:393:26)
           #24     _SingleBuild._runBuilder (package:build_runner_core/src/generate/build_impl.dart:372:36)
           <asynchronous suspension>
           #25     _SingleBuild._runPhases.<anonymous closure>.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:319:20)
           <asynchronous suspension>
           #26     _NoOpBuildPerformanceTracker.trackBuildPhase (package:build_runner_core/src/generate/performance_tracker.dart:184:15)
           #27     _SingleBuild._runPhases.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:315:47)
           <asynchronous suspension>
           #28     NoOpTimeTracker.track (package:timing/src/timing.dart:222:44)
           #29     _SingleBuild._runPhases (package:build_runner_core/src/generate/build_impl.dart:309:32)
           #30     logTimedAsync (package:build_runner_core/src/logging/logging.dart:25:30)
           <asynchronous suspension>
           #31     _SingleBuild._safeBuild.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:266:26)
           <asynchronous suspension>
           #32     _rootRun (dart:async/zone.dart:1124:13)
           #33     _CustomZone.run (dart:async/zone.dart:1021:19)
           #34     _runZoned (dart:async/zone.dart:1516:10)
           #35     runZoned (dart:async/zone.dart:1500:12)
           #36     _SingleBuild._safeBuild (package:build_runner_core/src/generate/build_impl.dart:261:5)
           #37     _SingleBuild.run (package:build_runner_core/src/generate/build_impl.dart:208:24)
           <asynchronous suspension>
           #38     BuildImpl.run (package:build_runner_core/src/generate/build_impl.dart:96:42)
           #39     BuildRunnerDaemonBuilder.build (package:build_runner/src/daemon/daemon_builder.dart:100:35)
           <asynchronous suspension>
           #40     Server._build.<anonymous closure> (package:build_daemon/src/server.dart:122:25)
           #41     Pool.withResource (package:pool/pool.dart:127:28)
           <asynchronous suspension>
           #42     Server._build (package:build_daemon/src/server.dart:119:13)
           #43     Server.listen.<anonymous closure>.<anonymous closure> (package:build_daemon/src/server.dart:85:17)
           <asynchronous suspension>
           #44     _rootRunUnary (dart:async/zone.dart:1132:38)
           #45     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
           #46     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
           #47     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
           #48     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
           #49     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:764:19)
           #50     _StreamController._add (dart:async/stream_controller.dart:640:7)
           #51     _StreamController.add (dart:async/stream_controller.dart:586:5)
           #52     new WebSocketImpl.fromSocket.<anonymous closure> (package:web_socket_channel/src/copy/web_socket_impl.dart:719:21)
           #53     _rootRunUnary (dart:async/zone.dart:1132:38)
           #54     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
           #55     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
           #56     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
           #57     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
           #58     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
           #59     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
           #60     _WebSocketProtocolTransformer._messageFrameEnd (package:web_socket_channel/src/copy/web_socket_impl.dart:316:22)
           #61     _WebSocketProtocolTransformer.add (package:web_socket_channel/src/copy/web_socket_impl.dart:214:46)
           #62     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
           #63     _rootRunUnary (dart:async/zone.dart:1132:38)
           #64     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
           #65     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
           #66     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
           #67     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
           #68     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:764:19)
           #69     _StreamController._add (dart:async/stream_controller.dart:640:7)
           #70     _StreamController.add (dart:async/stream_controller.dart:586:5)
           #71     _Socket._onData (dart:io-patch/socket_patch.dart:1829:41)
           #72     _rootRunUnary (dart:async/zone.dart:1136:13)
           #73     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
           #74     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
           #75     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
           #76     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
           #77     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:764:19)
           #78     _StreamController._add (dart:async/stream_controller.dart:640:7)
           #79     _StreamController.add (dart:async/stream_controller.dart:586:5)
           #80     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1377:33)
           #81     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:897:14)
           #82     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #83     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #84     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
           #85     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)

[   +2 ms] Failed after 305ms
[  +13 ms] Compiling lib/main.dart for the Web... (completed in 11.5s)
[   +4 ms] "flutter web" took 11,848ms.
Failed to compile lib/main.dart for the Web.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      buildWeb (package:flutter_tools/src/web/compile.dart:62:5)
<asynchronous suspension>
#2      BuildWebCommand.runCommand (package:flutter_tools/src/commands/build_web.dart:56:11)
<asynchronous suspension>
#3      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:527:18)
#4      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#5      _rootRunUnary (dart:async/zone.dart:1132:38)
#6      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#7      _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#8      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#9      Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#10     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#11     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552:7)
#12     _rootRun (dart:async/zone.dart:1124:13)
#13     _CustomZone.run (dart:async/zone.dart:1021:19)
#14     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#15     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#16     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#17     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#18     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#19     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)


```

**Comment by omontoya** [comment] 2019-09-21 03:24
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.10.6-pre.29, on Mac OS X 10.14.6 18G95, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.5)
[✓] IntelliJ IDEA Community Edition (version 2019.2)
[✓] VS Code
[✓] Connected device (2 available)

• No issues found!

**Comment by jonahwilliams** [comment] 2019-09-21 05:17
This has been "fixed" at master - "flutter build web" was never supposed to allow creating web debug builds.

**Comment by jonahwilliams** [comment] 2019-09-21 05:17
Nevermind, possibly same issue as https://github.com/flutter/flutter/issues/40996

**Comment by yjbanov** [comment] 2019-10-03 22:22
@vsmenon does this look `dart:io` related?

**Comment by vsmenon** [comment] 2019-10-03 22:57
I don't think it'd be related to `dart:io` directly - those sources are in the SDK itself.

@jakemac53 @grouma - anything we can do to improve that error?

**Comment by jakemac53** [comment] 2019-10-04 14:02
We have seen a few reports of this from flutter_web - one thing I noticed here is that it looks like this is doing a dart2js compile, which I didn't think we would ever do through build_runner for flutter_web (I thought it used dart2js directly)?

We previously added support to bootstrapDdc to skip these checks entirely, and I did add them to  bootstrapDart2js at the same time but the previous functionality we had only existed on bootstrapDdc (it let you skip the checks on certain whitelisted packages).

This message does try to give you the actual location of the file with the unsupported import, so something is going wrong and it wasn't able to find it.

**Comment by yjbanov** [comment] 2019-10-04 16:19
@jonahwilliams will https://github.com/flutter/flutter/issues/41951 also fix this issue?

**Comment by jakemac53** [comment] 2019-10-04 16:34
Yes - that workflow won't do this check at all.

**Comment by yjbanov** [comment] 2019-10-04 17:25
Ok, closing as duplicate of #41951 then.

**Closed by yjbanov** 2019-10-04 17:25 UTC
Labels: dependency: dart, ☸ platform-web

**Comment by divan** [comment] 2020-01-29 08:18
Is there any workaround for this (until fix is not, at least, in a dev or master channel)?

I'm having the same issue with the latest Flutter build. `flutter build web` seems to work fine, but `flutter run -d chrome` always fails if I add third-party package, and this blocks development.

**Comment by jakemac53** [comment] 2020-01-29 16:03
@divan are you adding those packages to your `pubspec.yaml`? What packages are having issues?

**Comment by divan** [comment] 2020-01-29 16:49
@jakemac53 yes, sure. Pretty much all charts libraries I tried (`flutter_charts`, `multicharts` and couple of others) and now `http` package (`http: ^0.12.0+4`).
Is this problem a package-specific?

**Comment by jakemac53** [comment] 2020-01-29 16:59
It indicates a problem in project setup - it is possible that those packages could have a bad `build.yaml` that would cause this for downstream users (if it excludes some of their sources). It is unlikely though.

Where I would expect to see this issue is if you are missing dependencies in your pubspec.

It is also weird that the offending imports haven't been listed. I have only really seen this issue with flutter projects so I don't know what the problem is exactly.

It is possible that it is some flutter specific invalidation issue or something. You can try doing a `flutter clean` and see if that helps.

**Comment by divan** [comment] 2020-02-01 19:58
Thanks @jakemac53. I don't know why, but just waiting 3 days, switching flutter channels 3 times and running `flutter clean` 3 times fixed the problem 🙃😃
