### ISSUE TITLE
[BUG] TextPainter getOffsetForCaret returns wrong value for correct offset

### ISSUE THREAD

**Issue by vuhminh** [flutter/flutter#54047] opened 2020-04-05 17:46 UTC
With a `TextSpan` that contains a `WidgetSpan` in the middle, when calling `getOffsetForCaret` for the last character it returns 0.

If this actually works as intended, then please ignore the issue. However, it does not seem to be the right behavior.

## Steps to reproduce

Given a text span: `a<widget>b`,
When calling `getOffsetForCaret` with offset pointing to `b`
It returns offset with `x` that is **0** instead of expected **78**

Paste the snippet in **test_painter_test.dart**

```
test('TextPainter bug', () {
  final TextPainter painter = TextPainter()
    ..textDirection = TextDirection.ltr;

  painter.text = const TextSpan(
    children: <InlineSpan>[
      TextSpan(text: 'a'),
      WidgetSpan(child: SizedBox(width: 50, height: 30)),
      TextSpan(text: 'b'),
    ],
  );

  painter.setPlaceholderDimensions(const <PlaceholderDimensions>[
    PlaceholderDimensions(size: Size(50, 30), baselineOffset: 25, alignment: ui.PlaceholderAlignment.bottom),
  ]);

  painter.layout(maxWidth: 500);

  Offset caretOffset = painter.getOffsetForCaret(const ui.TextPosition(offset: 1), ui.Rect.zero);
  expect(caretOffset.dx, 14);
  caretOffset = painter.getOffsetForCaret(const ui.TextPosition(offset: 2), ui.Rect.zero);
  expect(caretOffset.dx, 64);
  caretOffset = painter.getOffsetForCaret(const ui.TextPosition(offset: 3), ui.Rect.zero);
  expect(caretOffset.dx, 78); // fails because the offset is 0

}, skip: isBrowser);
```

## Flutter Doctor
```
[✓] Flutter (Channel master, v1.16.4-pre.88, on Mac OS X 10.15.4 19E266, locale en-VN)
    • Flutter version 1.16.4-pre.88 at /Users/minheq/Documents/GitHub/flutter
    • Framework revision ab14307e0c (3 days ago), 2020-04-03 00:56:01 -0400
    • Engine revision f5127cc07a
    • Dart version 2.8.0 (build 2.8.0-dev.19.0 fae35fca47)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/minheq/Library/Android/sdk
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4, Build version 11E146
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.43.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.0

[✓] Connected device (3 available)
    • iPhone 11 Pro Max • 9A8DC723-8011-47B4-AFA7-DAA87B5F064A • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-4 (simulator)
    • Chrome            • chrome                               • web-javascript • Google Chrome 80.0.3987.149
    • Web Server        • web-server                           • web-javascript • Flutter Tools
```

**Comment by TahaTesser** [comment] 2020-04-06 08:22
Related to [#47491](https://github.com/flutter/flutter/issues/47491)

**Comment by pinyin** [comment] 2020-11-13 04:04
Still reproducible on Flutter 1.24.0-8.0.pre.229.

**Comment by pinyin** [comment] 2020-11-13 04:12
code:

```
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

final text = '01';

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    final richTextKey = GlobalKey();
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: RichText(
            text: TextSpan(
              children: [
                WidgetSpan(child: Container()),
                TextSpan(text: text),
              ],
            ),
            key: richTextKey),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          final RenderParagraph paragraph =
              richTextKey.currentContext.findRenderObject();
          print(
              paragraph.getOffsetForCaret(TextPosition(offset: 0), Rect.zero));
          print(
              paragraph.getOffsetForCaret(TextPosition(offset: 1), Rect.zero));
          print(
              paragraph.getOffsetForCaret(TextPosition(offset: 2), Rect.zero));
          print(
              paragraph.getOffsetForCaret(TextPosition(offset: 3), Rect.zero));
        },
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ),
    );
  }
}

```
On Flutter 1.24.0-8.0.pre.229, clicking the button would print:

```
I/flutter (11614): Offset(0.0, 3.0)
I/flutter (11614): Offset(0.0, 2.6)
I/flutter (11614): Offset(7.9, 2.6)
I/flutter (11614): Offset(0.0, 0.0)
```
If comment out the line with the WidgetSpan, the result would be as expected: 
```
I/flutter (11614): Offset(0.0, -0.4)
I/flutter (11614): Offset(7.9, -0.4)
I/flutter (11614): Offset(15.7, -0.4)
I/flutter (11614): Offset(0.0, 0.0)
```

**Comment by TahaTesser** [comment] 2021-01-07 13:24
Code sample

https://github.com/flutter/flutter/issues/54047#issuecomment-726496086

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 1.22.5, on macOS 11.1 20C69 darwin-x64, locale en-GB)
    • Flutter version 1.22.5 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 7891006299 (4 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.0

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (2 available)
    • Taha’s iPad (mobile) • 00008020-000255113EE8402E            • ios • iOS 14.3
    • iPhone 12 (mobile)   • 181EDE6A-AA9B-4619-8352-9CD6F7A9CD61 • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)

! Doctor found issues in 1 category.
```
```bash
[✓] Flutter (Channel master, 1.26.0-2.0.pre.222, on macOS 11.1 20C69 darwin-x64, locale en-GB)
    • Flutter version 1.26.0-2.0.pre.222 at /Users/tahatesser/Code/flutter_master
    • Framework revision 655cd1e2a6 (5 hours ago), 2021-01-07 03:19:03 -0500
    • Engine revision 7f00e2f6c5
    • Dart version 2.12.0 (build 2.12.0-179.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (4 available)
    • Taha’s iPad (mobile) • 00008020-000255113EE8402E            • ios            • iOS 14.3
    • iPhone 12 (mobile)   • 181EDE6A-AA9B-4619-8352-9CD6F7A9CD61 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)      • macos                                • darwin-x64     • macOS 11.1 20C69 darwin-x64
    • Chrome (web)         • chrome                               • web-javascript • Google Chrome 87.0.4280.141

• No issues found!
```

</details>

**Comment by petermakeswebsites** [comment] 2022-01-07 16:34
I'm encountering this bug as well

**Comment by maheshmnj** [comment] 2022-12-22 23:04
Hi @vuhminh, I verified the issue on the latest master channel and It doesn't seem to reproduce. I believe the issue is fixed.

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

const text = '01';

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    final richTextKey = GlobalKey();
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Container(
          color: Colors.red,
          child: RichText(
              text: TextSpan(
                style: const TextStyle(
                  fontSize: 20,
                  color: Colors.black,
                ),
                children: [
                  const TextSpan(text: 'a'),
                  WidgetSpan(child: Container()),
                  const TextSpan(text: 'b'),
                ],
              ),
              key: richTextKey),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          final RenderParagraph paragraph =
              richTextKey.currentContext!.findRenderObject() as RenderParagraph;
          print(paragraph.getOffsetForCaret(
              const TextPosition(offset: 0), Rect.zero));
          print(paragraph.getOffsetForCaret(
              const TextPosition(offset: 1), Rect.zero));
          print(paragraph.getOffsetForCaret(
              const TextPosition(offset: 2), Rect.zero));
          print(paragraph.getOffsetForCaret(
              const TextPosition(offset: 3), Rect.zero));
        },
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}

```
</details>  

```console
Could not load custom device from config index 0: Expected enabled to be a boolean.
Launching lib/main.dart on iPhone 12 Pro in debug mode...
Xcode build done.                                           12.8s
Connecting to VM Service at ws://127.0.0.1:63692/rg7e5YwQdMg=/ws
flutter: Offset(0.0, 0.1)
flutter: Offset(11.0, 0.1)
flutter: Offset(0.0, 48.1)
flutter: Offset(12.3, 48.1)
```


Closing. In case you still encounter the issue, Please feel free to write in the comments and we will reopen it.

Thank you.

**Closed by maheshmnj** 2022-12-22 23:04 UTC
Labels: framework, f: material design, a: quality, has reproducible steps, found in release: 1.22, found in release: 1.26
