### ISSUE TITLE
[video_player] video sound should not mute when mute control is muted

### ISSUE THREAD

**Issue by jerryzhoujw** [flutter/flutter#48558] opened 2020-01-10 08:46 UTC
When playing video, video sound will be muted when muted controller is muted.

It's maybe as design, but not same as most of the video & audio apps(Youtube for example)

**Target Platform:** iOS
**Target OS version/browser:** 13.3
**Devices:** iPhone8

**Comment by cbenhagen** [comment] 2020-01-10 09:25
Duplicate of #47524. Please check the solutions in the issue.

**Comment by VladyslavBondarenko** [comment] 2020-01-10 10:10
Thanks @cbenhagen !
I'm closing the current one as duplicate [#47524](https://github.com/flutter/flutter/issues/47524).
If you disagree please write in the comments
and I will reopen it.
Thank you

**Closed by VladyslavBondarenko** 2020-01-10 10:10 UTC

**Comment by jerryzhoujw** [comment] 2020-01-10 14:29
@cbenhagen oh I see, I just search the issue with `[video_player]` before I create this,  you maybe better to create issue with title start with `[video_player]`
