### ISSUE TITLE
Flutter app not working after reopening from recent apps

### ISSUE THREAD

**Issue by Vaibhavck** [flutter/flutter#64459] opened 2020-08-24 13:56 UTC
I am working on a flutter application and I am stuck on following error.
When I close the flutter application **without removing it from recent apps** and reopen it from **recent apps** I get this type of error:

    D/MALI    ( 3778): gles_state_set_error_internal:75: [MALI] GLES ctx: 0x88f80008, error code:0x505
    D/MALI    ( 3778): gles_state_set_error_internal:76: [MALI] GLES error info: execution failed
    D/MALI    ( 3778): gles_state_set_error_internal:75: [MALI] GLES ctx: 0x88f80008, error code:0x505
    D/MALI    ( 3778): gles_state_set_error_internal:76: [MALI] GLES error info: execution failed
    D/MALI    ( 3778): gles_state_set_error_internal:75: [MALI] GLES ctx: 0x88f80008, error code:0x505
    D/MALI    ( 3778): gles_state_set_error_internal:76: [MALI] GLES error info: execution failed
    D/MALI    ( 3778): gles_state_set_error_internal:75: [MALI] GLES ctx: 0x88f80008, error code:0x505
    D/MALI    ( 3778): gles_state_set_error_internal:76: [MALI] GLES error info: execution failed
    D/MALI    ( 3778): gles_state_set_error_internal:75: [MALI] GLES ctx: 0x88f80008, error code:0x505
    D/MALI    ( 3778): gles_state_set_error_internal:76: [MALI] GLES error info: execution failed
    D/MALI    ( 3778): gles_state_set_error_internal:75: [MALI] GLES ctx: 0x88f80008, error code:0x505
    D/MALI    ( 3778): gles_state_set_error_internal:76: [MALI] GLES error info: execution failed
    D/MALI    ( 3778): gles_state_set_error_internal:75: [MALI] GLES ctx: 0x88f80008, error code:0x505
    D/MALI    ( 3778): gles_state_set_error_internal:76: [MALI] GLES error info: execution failed
    D/MALI    ( 3778): gles_state_set_error_internal:75: [MALI] GLES ctx: 0x88f80008, error code:0x505
    D/MALI    ( 3778): gles_state_set_error_internal:76: [MALI] GLES error info: execution failed
    D/MALI    ( 3778): gles_state_set_error_internal:75: [MALI] GLES ctx: 0x88f80008, error code:0x505
    D/MALI    ( 3778): gles_state_set_error_internal:76: [MALI] GLES error info: execution failed
    D/MALI    ( 3778): gles_state_set_error_internal:75: [MALI] GLES ctx: 0x88f80008, error code:0x505
    D/MALI    ( 3778): gles_state_set_error_internal:76: [MALI] GLES error info: execution failed
    D/MALI    ( 3778): gles_state_set_error_internal:75: [MALI] GLES ctx: 0x88f80008, error code:0x505
    D/MALI    ( 3778): gles_state_set_error_internal:76: [MALI] GLES error info: execution failed
    D/MALI    ( 3778): gles_state_set_error_internal:75: [MALI] GLES ctx: 0x88f80008, error code:0x505
    D/MALI    ( 3778): gles_state_set_error_internal:76: [MALI] GLES error info: execution failed

<br>
And the current screen in the app freezes. The app doesn't work ( even after hot restart) unless I rebuilt (flutter clean and the build) and reinstall it. I tried searching online for solution but found nothing!<br>
Result of <strong>flutter doctor</strong> :

    flutter doctor
    Doctor summary (to see all details, run flutter doctor -v):
    [√] Flutter (Channel stable, 1.20.1, on Microsoft Windows [Version 10.0.18362.1016], locale en-IN)
    
    [√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    [√] Android Studio (version 3.6)
    [√] VS Code (version 1.48.1)
    [√] Connected device (1 available)
    
    • No issues found!

Thanks in advance.

**Comment by sidrao2006** [comment] 2020-08-24 14:06
Hey @Vaibhavck , you are getting an opengl es error `GLES error info: OpenGL ES API version mismatch`

**Comment by sidrao2006** [comment] 2020-08-24 14:08
This may be due to one of your packages

**Comment by sidrao2006** [comment] 2020-08-24 14:19
Duplicate of #64453 
PLease close this issue

**Comment by pedromassangocode** [comment] 2020-08-24 14:37
Hi @Vaibhavck 
I see there's an open issue addressing the case you described (https://github.com/flutter/flutter/issues/64453).
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by pedromassangocode** 2020-08-24 14:37 UTC
