### ISSUE TITLE
flutter doctor -v

### ISSUE THREAD

**Issue by ted0528** [flutter/flutter#151219] opened 2024-07-03 09:18 UTC
### Steps to reproduce

0. on windows 10 cmd
1. flutter doctor -v
2. Network resources (the doctor check crashed)
    X Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know
      about this issue at https://github.com/flutter/flutter/issues.
    X Exception: Network resources exceeded maximum allowed duration of 0:04:30.000000
! Doctor found issues in 1 category.

note: attempting to reach cocoapods.org...   timed out.

### Expected results

no errors.

### Actual results

timed out

### Code sample

<details open><summary>Code sample</summary>

```dart
flutter doctor -v
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
D:\flutter_projects\meals>flutter doctor -v
Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
[√] Flutter (Channel stable, 3.22.1, on Microsoft Windows [Version 10.0.19045.4529], locale en-US)
    • Flutter version 3.22.1 on channel stable at D:\mobile_dev_tools\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a14f74ff3a (6 weeks ago), 2024-05-22 11:08:21 -0500
    • Engine revision 55eae6864b
    • Dart version 3.4.1
    • DevTools version 2.34.3
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at D:\Android\android33.0.3SDK
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = D:\Android\android33.0.3SDK
    • ANDROID_SDK_ROOT = D:\Android\android33.0.3SDK
    • Java binary at: D:\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.8.3)
    • Visual Studio at d:\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.8.34330.188
    • Windows 10 SDK version 10.0.22621.0

[√] Android Studio (version 2022.2)
    • Android Studio at D:\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19045.4529]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 125.0.6422.61
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 125.0.2535.92

[☠] Network resources (the doctor check crashed)
    X Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know
      about this issue at https://github.com/flutter/flutter/issues.
    X Exception: Network resources exceeded maximum allowed duration of 0:04:30.000000
    •

! Doctor found issues in 1 category.
```

</details>

**Comment by danagbemava-nc** [comment] 2024-07-03 09:32
Closing this as a duplicate of https://github.com/flutter/flutter/issues/125488

**Closed by danagbemava-nc** 2024-07-03 09:32 UTC
Labels: in triage
