### ISSUE TITLE
[Camera] - Camera Plugin for windows

### ISSUE THREAD

**Issue by hoaibn-0332** [flutter/flutter#93776] opened 2021-11-17 08:50 UTC
## Use case
I am using the Flutter for app development on Windows (win 10) and my application has the feature take the picture from camera. I checked the [camera package](https://pub.dev/packages/camera) and it not support for windows

## Proposal
- Camera Plugin for windows 

Can you support me to write the plugin?. Thank you so much!

**Comment by darshankawar** [comment] 2021-11-17 08:57
Closing this as duplicate of https://github.com/flutter/flutter/issues/41709

**Closed by darshankawar** 2021-11-17 08:57 UTC
Labels: in triage
