### ISSUE TITLE
Flutter crash report. SocketException: SocketException: The remote computer refused the network connection.

### ISSUE THREAD

**Issue by limouzeen** [flutter/flutter#153706] opened 2024-08-17 14:58 UTC
<-- Please describe your problem here. Be sure to include repro steps. -->

Flutter crash report.
Please report a bug at https://github.com/flutter/flutter/issues.

## command

flutter run --machine --start-paused -d chrome --devtools-server-address http://127.0.0.1:9101/ --target D:\src\sau_coffee_app_project\lib\main.dart

## exception

SocketException: SocketException: The remote computer refused the network connection.
 (OS Error: The remote computer refused the network connection.
, errno = 1225), address = localhost, port = 59041

```
#0      _NativeSocket.startConnect (dart:io-patch/socket_patch.dart:721:35)
flutter/devtools#1      _RawSocket.startConnect (dart:io-patch/socket_patch.dart:1920:26)
flutter/devtools#2      RawSocket.startConnect (dart:io-patch/socket_patch.dart:27:23)
flutter/devtools#3      Socket._startConnect (dart:io-patch/socket_patch.dart:2144:22)
flutter/devtools#4      Socket.startConnect (dart:io/socket.dart:825:21)
flutter/devtools#5      _ConnectionTarget.connect (dart:_http/http_impl.dart:2491:20)
flutter/devtools#6      _HttpClient._getConnection.connect (dart:_http/http_impl.dart:2930:12)
flutter/devtools#7      _HttpClient._getConnection (dart:_http/http_impl.dart:2935:12)
flutter/devtools#8      _HttpClient._openUrl (dart:_http/http_impl.dart:2790:12)
flutter/devtools#9      _HttpClient.getUrl (dart:_http/http_impl.dart:2632:48)
flutter/devtools#10     ChromeConnection.getUrl (package:webkit_inspection_protocol/webkit_inspection_protocol.dart:108:33)
flutter/devtools#11     ChromeConnection.getTabs (package:webkit_inspection_protocol/webkit_inspection_protocol.dart:53:26)
flutter/devtools#12     ChromeConnection.getTab (package:webkit_inspection_protocol/webkit_inspection_protocol.dart:90:31)
flutter/devtools#13     Chromium.close (package:flutter_tools/src/web/chrome.dart:510:53)
flutter/devtools#14     ChromiumDevice.stopApp (package:flutter_tools/src/web/web_device.dart:164:20)
flutter/devtools#15     ResidentWebRunner._cleanup (package:flutter_tools/src/isolated/resident_web_runner.dart:203:27)
<asynchronous suspension>
flutter/devtools#16     ResidentWebRunner.cleanupAtFinish (package:flutter_tools/src/isolated/resident_web_runner.dart:191:5)
<asynchronous suspension>
flutter/devtools#17     ResidentRunner.waitForAppToFinish (package:flutter_tools/src/resident_runner.dart:1482:5)
<asynchronous suspension>
flutter/devtools#18     RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:788:26)
<asynchronous suspension>
flutter/devtools#19     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1408:27)
<asynchronous suspension>
flutter/devtools#20     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
flutter/devtools#21     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
flutter/devtools#22     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:420:9)
<asynchronous suspension>
flutter/devtools#23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
flutter/devtools#24     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:5)
<asynchronous suspension>
flutter/devtools#25     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:130:9)
<asynchronous suspension>
flutter/devtools#26     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
flutter/devtools#27     main (package:flutter_tools/executable.dart:93:3)
<asynchronous suspension>
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel stable, 3.24.0, on Microsoft Windows [Version 10.0.22631.4037], locale en-US)
    [32m•[39m Flutter version 3.24.0 on channel stable at D:\src\flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision 80c2e84975 (3 weeks ago), 2024-07-30 23:06:49 +0700
    [32m•[39m Engine revision b8800d88be
    [32m•[39m Dart version 3.5.0
    [32m•[39m DevTools version 2.37.2

[32m[✓][39m Windows Version (Installed version of Windows is version 10 or higher)

[33m[!][39m Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    [32m•[39m Android SDK at C:\Users\Admin\AppData\Local\Android\Sdk
    [31m✗[39m cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    [31m✗[39m Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/to/windows-android-setup for more details.

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[33m[!][39m Visual Studio - develop Windows apps (Visual Studio Community 2022 17.4.4)
    [32m•[39m Visual Studio at D:\unity\Visual Studio
    [32m•[39m Visual Studio Community 2022 version 17.4.33213.308
    [32m•[39m Windows 10 SDK version 10.0.22000.0
    [31m✗[39m Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop development with C++" workload, and include these components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK

[32m[✓][39m Android Studio (version 2023.1)
    [32m•[39m Android Studio at D:\Android\Android Studio
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)

[32m[✓][39m VS Code (version 1.92.2)
    [32m•[39m VS Code at C:\Users\Admin\AppData\Local\Programs\Microsoft VS Code
    [32m•[39m Flutter extension version 3.94.0

[32m[✓][39m Connected device (3 available)
    [32m•[39m Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22631.4037]
    [32m•[39m Chrome (web)      • chrome  • web-javascript • Google Chrome 127.0.6533.120
    [32m•[39m Edge (web)        • edge    • web-javascript • Microsoft Edge 127.0.2651.105

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[33m![39m Doctor found issues in 2 categories.
___
**DevTools version**: 2.37.2

**Comment by huycozy** [comment] 2024-08-20 05:00
Closing this as a duplicate of https://github.com/flutter/flutter/issues/153064. This has been fixed on Flutter master channel so you can try switching to master channel and retry.

**Closed by huycozy** 2024-08-20 05:00 UTC
Labels: in triage
