### ISSUE TITLE
Can't delete a user

### ISSUE THREAD

**Issue by arnair** [flutter/flutter#36627] opened 2019-07-21 05:58 UTC
Hello I try to delete  a user but don't recognise the delete() function, is it working?
this is my code:
```
  final FirebaseAuth _auth = FirebaseAuth.instance;
      var user = _auth.currentUser();
      user.delete();
```
Thanks

**Comment by artashsanoyan** [comment] 2019-07-21 08:56
The instance method of FirebaseAuth class returns future, meaning you have to await for it.

You can read about this and other methods in firebase documentation: 
[https://firebase.google.com/docs/auth/web/manage-users](url)

At the end you'r code should looks like: 
```
void deleteUser() async {
  final FirebaseAuth _auth = FirebaseAuth.instance;
  var user = await _auth.currentUser();
  user.delete();
}
```

**Comment by arnair** [comment] 2019-07-22 20:13
> The instance method of FirebaseAuth class returns future, meaning you have to await for it.
> 
> You can read about this and other methods in firebase documentation:
> https://firebase.google.com/docs/auth/web/manage-users
> 
> At the end you'r code should looks like:
> 
> ```
> void deleteUser() async {
>   final FirebaseAuth _auth = FirebaseAuth.instance;
>   var user = await _auth.currentUser();
>   user.delete();
> }
> ```

yes that's what i tried but nothing, did you done? if yes which version are you using?
thanks

**Comment by artashsanoyan** [comment] 2019-07-23 07:45
At first try i've encountered exception: 
```
PlatformException (PlatformException(ERROR_REQUIRES_RECENT_LOGIN, This operation is sensitive and requires recent authentication. Log in again before retrying this request., null))
```
maybe this is a problem for you too.

I've tried with 0.11.1+11 version and it works for me after relogin, currently new version was released.

If there is any error message or warning please provide them with your pubspec.yaml file so i can try to reproduce it's.

**Comment by BondarenkoStas** [comment] 2019-09-23 17:11
@arnair is the issue still relevant?

**Comment by iapicca** [comment] 2019-11-11 15:47
Hi @arnair 
for what I can see the issue is related to a FlutterFire plugin,
please open the issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
thank you

**Comment by arnair** [comment] 2019-11-11 16:35
it works now thanks

**Closed** 2019-11-11 16:44 UTC
