### ISSUE TITLE
[Android][Samsung Keyboard]: Backspace do not delete the text / characters if it has spaces in it in TextFormField

### ISSUE THREAD

**Issue by trungdn0401** [flutter/flutter#80938] opened 2021-04-22 11:09 UTC
It just happened on Samsung Keyboard, the Google Keyboard or Microsoft Keyboard Swiftkey is works fine.
Please see the video for more detail:
https://user-images.githubusercontent.com/22168484/115704505-a6deb580-a395-11eb-9209-2331e40cb601.mp4

Sample code:
`TextFormField(
              decoration: const InputDecoration(icon: Icon(Icons.person),
              hintText: 'hint nè nè nè',
              labelText: 'Ngọc trung nè',
              ),
              keyboardType: TextInputType.emailAddress,
            ),`

Here is flutter doctor -v:
`[√] Flutter (Channel stable, 2.0.5, on Microsoft Windows [Version 10.0.19042.928], locale en-US)
    • Flutter version 2.0.5 at D:\2-Software\FlutterSDK
    • Framework revision adc687823a (6 days ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at D:\2-Software\AndroidSDK
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = D:\2-Software\AndroidSDK
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.55.2)
    • VS Code at C:\Users\trung\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.21.0

[√] Connected device (4 available)
    • SM N980F (mobile)     • RF8N80WSREL          • android-arm64  • Android 11 (API 30)

• No issues found!`

P/s: Press and hold the backspace key, it's working fine.

**Comment by darshankawar** [comment] 2021-04-22 13:36
@trungdn0401 
Please check if [this](https://github.com/flutter/flutter/issues/73544) issue is similar / resemble your use case.

**Comment by trungdn0401** [comment] 2021-04-23 01:57
> @trungdn0401
> Please check if [this](https://github.com/flutter/flutter/issues/73544) issue is similar / resemble your use case.

Hi, it seems that not the same.
I think I just happened with backspace when it faced a space character. Hold and delete is working fine.

**Comment by darshankawar** [comment] 2021-04-23 06:21
@trungdn0401 
Do you have a localized language setup on your device with which this behavior is occuring ?
Can you try the same with English default like below:
`
TextFormField( decoration: const InputDecoration(icon: Icon(Icons.person), hintText: 'enter here', labelText: 'sample text', ), keyboardType: TextInputType.emailAddress, ),`

**Comment by trungdn0401** [comment] 2021-04-23 09:00
Hi @darshankawar ,

It still happens with English text.
https://user-images.githubusercontent.com/22168484/115847349-106dcb00-a44d-11eb-8172-7c7fabd7afda.mp4

**Comment by darshankawar** [comment] 2021-04-23 11:02
Thanks for the details. I see the same behavior using S10 device and using latest stable version, wherein, if a text has spaces in it, the backspace button from the Samsung keyboard deletes all texts leading upto the space, but can't delete the space.

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.0.5, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.0.5 at /Users/dhs/documents/fluttersdk/flutter
    • Framework revision adc687823a (3 days ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
    
[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)    

[✓] VS Code (version 1.55.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (3 available)
	  • SM G975F (mobile) • RZ8M802WY0X • android-arm64 • Android 10 (API 29)
    • Darshan's iphone (mobile) • 21150b119064aecc249dfcfe05e259197461ce23 • ios
      • iOS 14.4.1
    • macOS (desktop)           • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)              • chrome                                   •
      web-javascript • Google Chrome 89.0.4389.114

! Doctor found issues in 1 category.

```

</details>

**Comment by LongCatIsLooong** [comment] 2021-04-30 00:42
I can't reproduce this on Tab A (SMT-510, keyboard version 3.3.31.83). Could you check if this is reproducible on the latest master? I'm not sure the exact cause of this issue but https://github.com/flutter/engine/pull/25180 may have fixed this.

**Comment by oodavid** [comment] 2021-05-06 16:14
Our client is reporting the same issue with a Samsung S20 using the default keyboard. I believe that's the stock Samsung keyboard. I've advised him to change to the Google keyboard.

Our product is using flutter `2.0.4`. No strange modifications to the `TextField` widget from our end.

**Comment by edrick27** [comment] 2021-05-26 21:59
i have the same issue when use a TextInputClient

**Comment by LongCatIsLooong** [comment] 2021-05-28 07:52
Has anyone reproduced the issue on the lastest master or stable? There's a high chance that this is fixed in https://github.com/flutter/flutter/commit/9de26095feb29088c7760724258617c7e1d915b4

**Comment by lckhanh** [comment] 2021-05-28 16:53
Hi, Has anyone has the solution for this issue? 
I'm using TextInputClient in my app with Flutter 1 and this issue didn't happen - but when upgrading Flutter to 2.0 (stable version Flutter 2.2.1) I got this issue.

**Comment by rcosar** [comment] 2021-06-03 08:59
Hi, I was having this problem too.
I was using custom inputFormatters. I removed this and the problem was fixed.

Flutter 2.2.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 02c026b03c (7 days ago) • 2021-05-27 12:24:44 -0700
Engine • revision 0fdb562ac8
Tools • Dart 2.13.1

**Closed** 2021-06-10 20:29 UTC
Labels: a: text input, e: device-specific, f: material design, found in release: 2.0, framework, has reproducible steps, platform-android, waiting for customer response
