### ISSUE TITLE
cannot connect to a websocket server

### ISSUE THREAD

**Issue by Safwene12** [flutter/flutter#82698] opened 2021-05-17 14:49 UTC
Hey I'm trying to connect to a spring boot websocket server using socket_io_client version1.0.1 
here it is my connect service 

```dart
     Future<Socket> connect() async{
       String url ='http://192.168.1.103:8761/socket';
    Socket socket = io(url,
        OptionBuilder()
            .setTransports(['websocket']) // for Flutter or Dart VM
            .disableAutoConnect()  // disable auto-connection
            .setExtraHeaders({'Authorization': 'Bearer $token'})
            .build()
    );
    socket.onConnect((data) => {
      print('connected')
    });
    socket.onError((data) => print(data.toString()));
    socket.onConnectError((data) => print(data.toString()));
    socket.connect();
    print(socket.connected);
    return socket;}
```
and here it is the implementation
 
` Socket client= io('ws://$baseUrl:$portApiGatway/socket');`
 ```dart
getClient() async{
    WebSocketService webSocketService = WebSocketService();
    client = await webSocketService.connect();

@override
  void initState() {
    // TODO: implement initState
    super.initState();
    refreshStore();
    WidgetsBinding.instance.addObserver(this);
    getClient();
    print(client.connected);
  }
```

my problem is client.connected is always false and this exception is thrown 
I/flutter (12400): WebSocketException: Connection to 'http://192.168.1.103:8761/socket.io/?EIO=3&transport=websocket#' was not upgraded to websocket
Any Help Please ??!
Flutter version 2.0.1 
Dart version 2.12.0

**Comment by TahaTesser** [comment] 2021-05-18 09:00
Hi @Safwene12 
From what I can see, the issue is related to a 3rd party plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/rikulo/socket.io-client-dart/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`, a minimal reproducible code sample that does not use 3rd party plugins, your complete `flutter run -v` logs running the minimal code sample 
and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-05-18 09:00 UTC
Labels: in triage
