### ISSUE TITLE
[tool_crash] FileSystemException: Cannot create file, OS Error: The system cannot find the path specified., errno = 3

### ISSUE THREAD

**Issue by picasso999** [flutter/flutter#72226] opened 2020-12-13 08:50 UTC
## Command
```
flutter run --verbose
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Cannot create file, OS Error: The system cannot find the path specified.
, errno = 3
```
#0      _File.throwIfError (dart:io/file_impl.dart:635:7)
#1      _File.createSync (dart:io/file_impl.dart:273:5)
#2      ForwardingFile.createSync (package:file/src/forwarding/forwarding_file.dart:24:16)
#3      ForwardingFile.createSync (package:file/src/forwarding/forwarding_file.dart:24:16)
#4      _renderTemplateToFile (package:flutter_tools/src/plugins.dart:26:8)
#5      _writeAndroidPluginRegistrant (package:flutter_tools/src/plugins.dart:677:3)
#6      injectPlugins (package:flutter_tools/src/plugins.dart:1165:11)
#7      _rootRunUnary (dart:async/zone.dart:1198:47)
#8      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#9      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#10     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#11     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#12     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#13     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#14     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#15     findPlugins (package:flutter_tools/src/plugins.dart)
#16     _rootRunUnary (dart:async/zone.dart:1198:47)
#17     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#18     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#19     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#20     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#21     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#22     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#23     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#24     loadPackageConfigWithLogging (package:flutter_tools/src/dart/package_map.dart)
```
```
[✓] Flutter (Channel stable, 1.22.5, on Microsoft Windows [Version 10.0.18363.1198], locale en-IN)
    • Flutter version 1.22.5 at C:\src\flutter
    • Framework revision 7891006299 (3 days ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\PC Dell\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: D:\softwares\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[✓] Android Studio (version 4.0)
    • Android Studio at D:\softwares\Android Studio
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] Connected device (2 available)
    • RMX1931 (mobile)                   • ddbfcad8      • android-arm64 • Android 10 (API 29)
    • Android SDK built for x86 (mobile) • emulator-5556 • android-x86   • Android 10 (API 29) (emulator)

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: null
**Version**: 1.8.0+11
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: null
**Creation framework version**: null
### Plugins
admob_flutter-0.3.4
apple_sign_in-0.1.0
braintree_payment-1.2.4
connectivity-0.4.8+6
connectivity_macos-0.1.0+7
esys_flutter_share-1.0.2
firebase_auth-0.15.5+3
firebase_auth_web-0.1.3+1
firebase_core-0.4.5
firebase_core_web-0.1.1+2
firebase_database-3.1.6
firebase_messaging-6.0.16
flutter_facebook_login-3.0.0
flutter_native_image-0.0.5+2
flutter_webview_plugin-0.3.11
fluttertoast-4.0.1
geocoder-0.2.1
google_sign_in-4.5.1
google_sign_in_web-0.9.2
launch_review-2.0.0
multi_image_picker-4.6.7
package_info-0.4.0+18
path_provider-1.6.9
path_provider_macos-0.0.4+6
permission_handler-5.0.0+hotfix.6
razorpay_flutter-1.2.1
shared_preferences-0.5.7+3
shared_preferences_macos-0.0.1+11
shared_preferences_web-0.1.2+7
sqflite-1.3.2+1
stripe_payment-1.0.7
url_launcher-5.4.10
url_launcher_macos-0.0.1+9
url_launcher_web-0.1.5+1
video_player-0.10.12+5
video_player_web-0.1.4+1
wakelock-0.1.4+2
webview_flutter-0.3.24

**Comment by iapicca** [comment] 2020-12-13 09:08
@picasso999 
please note this [comment](> @ranasaim3215
> This issue is already fixed and merged, but only available in master. Please see [this](https://github.com/flutter/flutter/issues/66415#issuecomment-701003004) comment.
> Please switch to latest master and try again to see if it works.
> I am going ahead and closing this as fixed. If you disagree or think the issue is still occuring on master, write in comments and I'll reopen.
> Thanks.

) 

> This issue is already fixed and merged, but only available in master. Please see [this](https://github.com/flutter/flutter/issues/66415#issuecomment-701003004) comment.
> Please switch to latest master and try again to see if it works.
> I am going ahead and closing this as fixed. If you disagree or think the issue is still occuring on master, write in comments and I'll reopen.
> Thanks.

**Comment by TahaTesser** [comment] 2020-12-14 09:32
Closing as duplicate of https://github.com/flutter/flutter/issues/69565

**Closed by TahaTesser** 2020-12-14 09:32 UTC
