### ISSUE TITLE
[tool_crash] FileSystemException: Failed to decode data using encoding utf-8 null

### ISSUE THREAD

**Issue by nanatopsy** [flutter/flutter#144646] opened 2024-03-05 22:52 UTC
%23%

**Comment by danagbemava-nc** [comment] 2024-03-06 07:00
Closing this as a duplicate of https://github.com/flutter/flutter/issues/65021.

In the future, please provide all the information from the crash log. 

Thank you

**Closed by danagbemava-nc** 2024-03-06 07:00 UTC
Labels: in triage
