### ISSUE TITLE
Uri.dataFromString factory prepends string value with ","

### ISSUE THREAD

**Issue by DominikStarke** [flutter/flutter#120438] opened 2023-02-10 13:49 UTC
## Steps to Reproduce

1. final uri = Uri.dataFromString("example.com")
2. uri.path is now ",example.com" (notice the comma)
3. await canLaunchUrl(url) ? await launchUrl(url) : throw 'Could not launch $url'; will then throw.

This is probably due to UriData.fromString calling buffer.write(',') before _uriEncodeBytes on values that aren't base64 encoded

Calling the Uri default constructor works as expected.

```
[✓] Flutter (Channel stable, 3.7.1, on macOS 13.1 22C65 darwin-arm64, locale de-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/chrome-unsafe)
    ! /Applications/Google Chrome.app/Contents/MacOS/chrome-unsafe is not executable.
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.74.3)
[✓] Connected device (2 available)
[✓] HTTP Host Availability
```

**Comment by stuartmorgan** [comment] 2023-02-10 18:35
In the future, please file issues with Dart classes in [the Dart repository](https://github.com/dart-lang/sdk/issues) rather than the Flutter repository.

> 1. final uri = Uri.dataFromString("example.com")
> 2. uri.path is now ",example.com" (notice the comma)

That is the correct encoding of a data URL whose data is the string "example.com", per [the spec](https://www.rfc-editor.org/rfc/rfc2397#section-2). However:

> 3. await canLaunchUrl(url) ? await launchUrl(url) : throw 'Could not launch $url'; will then throw.

You don't want a data URL for this use case; you cannot launch a data URL. You should be creating a normal URL, a constructor like [this one](https://api.dart.dev/stable/2.19.2/dart-core/Uri/Uri.html).

Closing as this is not a bug.

**Closed by stuartmorgan** 2023-02-10 18:35 UTC
