### ISSUE TITLE
NestedScrollView + ListView in iOS13 scroll bug

### ISSUE THREAD

**Issue by epoll-j** [flutter/flutter#43086] opened 2019-10-20 14:08 UTC
Hello guys,
I wrote a very basic page that has a NestedScrollView and a SliverAppBar and some listview wrapped inside tab.
Whenever I scrolling the page, it will often reset position to the top in iOS13, but it's normal in Android.

It look like this:
![avatar](https://public.bobolaile.com/111.gif)

my code:
```dart
import 'package:flutter/material.dart';

class TestPage extends StatefulWidget {
  @override
  State<StatefulWidget> createState() => _TestPageState();

}

class _TestPageState extends State<TestPage> with TickerProviderStateMixin {
  ScrollController _scrollViewController =
  ScrollController(initialScrollOffset: 0.0);

  TabController _tabController;

  @override
  Widget build(BuildContext context) {
    _tabController = TabController(length: 4, vsync: this);
    return Scaffold(
      appBar: AppBar(
        title: const Text("title"),
      ),
      body: _buildBody(context),
    );
  }

  Widget _buildBody(BuildContext context) {
    List<String> _tabList = ["1", "2", "3", "4"];

    return NestedScrollView(
      controller: _scrollViewController,
      headerSliverBuilder: (BuildContext context, bool boxIsScrolled) {
        return <Widget>[
          SliverAppBar(
            pinned: true,
            floating: true,
            forceElevated: boxIsScrolled,
            backgroundColor: Colors.white,
            flexibleSpace: FlexibleSpaceBar(
              collapseMode: CollapseMode.pin,
              background: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: <Widget>[
                  Center(
                    child: Container(
                      height: 100,
                      width: 200,
                      color: Colors.blue,
                    ),
                  ),
                  Center(
                    child: Container(
                      height: 100,
                      width: 200,
                      color: Colors.red,
                    ),
                  ),
                  Center(
                    child: Container(
                      height: 100,
                      width: 200,
                      color: Colors.green,
                    ),
                  ),
                  Center(
                    child: Container(
                      height: 100,
                      width: 200,
                      color: Colors.yellow,
                    ),
                  )
                ],
              ),
            ),
            expandedHeight: 470,
            bottom: PreferredSize(
                child: TabBar(
                    controller: _tabController,
                    tabs: _tabList.map((item) {
                      return Tab(
                        child: Text(item, style: TextStyle(color: Colors.green),),
                      );
                    }).toList()),
                preferredSize: Size(double.infinity, 60)),
          )
        ];
      },
      body: TabBarView(
        controller: _tabController,
        children: _tabList.map((_) {
          return Center(
            child: ListView.builder(
              itemBuilder: (content, index) {
                return Center(
                  child: Text("$index"),
                );
              },
              itemCount: 100,
            ),
          );
        }).toList(),
      ),
    );
  }
}

```

fultter doctor:
```
[✓] Flutter (Channel stable, v1.9.1+hotfix.5, on Mac OS X 10.15 19A583, locale zh-Hans-CN)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
[✓] Android Studio (version 3.4)
[!] IntelliJ IDEA Ultimate Edition (version 2019.1.4)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.39.2)
[✓] Connected device (1 available)
```

**Comment by iapicca** [comment] 2019-10-21 08:13
Hi @dubhe-jk 
you might want to use a **_SliverList_** instead of a **_ListView.builder_**
Here's some documentation [[1](https://youtu.be/ORiTTaVY6mM
), [2](https://medium.com/flutter/slivers-demystified-6ff68ab0296f
)]that can help your case

**Comment by dubhe-jk** [comment] 2019-10-21 08:27
Thank you for your answer @iapicca 
but how to use SliverList with TabBarView

**Comment by wangfengnan** [comment] 2019-10-25 02:09
same problem!

**Comment by Tecode** [comment] 2020-01-09 02:42
try NestedScrollView set physics ClampingScrollPhysics
`
NestedScrollView(
            physics: ClampingScrollPhysics(),
            body:Text(''),
)`

**Comment by iapicca** [comment] 2020-03-16 12:14
Hi all
if @Tecode [solution](https://github.com/flutter/flutter/issues/43086#issuecomment-572356247)
doesn't work for you and you are experiencing the issue
with the latest stable version of flutter 
can you please provide your update `flutter doctor -v` , 
your `flutter run --verbose` 
and a reproducible minimal code sample.
Thank you

**Comment by xiechunyan** [comment] 2020-03-27 03:24
There is still a problem on the iphone after adding physics. Is there a solution?

**Comment by RockinPaul** [comment] 2020-03-27 04:51
> There is still a problem on the iphone after adding physics. Is there a solution?

Hello! Regarding @Tecode solution which doesn't work for me either - try to set ClampingScrollPhysics to a nested ListView, but not NestedScrollView itself. This is the only workaround I found for now.

**Comment by xiechunyan** [comment] 2020-03-27 06:03
I've tried to do this before, but if you use it in the nested ListView, the iphone's sliding feature is gone.Is there any other solution?

**Comment by VladyslavBondarenko** [comment] 2020-05-06 15:48
Hi @RockinPaul 
Does the issue persist?
I can't reproduce it with iOS 13.4.5 on `dev 1.18.0-10.0.pre`

**Comment by RockinPaul** [comment] 2020-05-21 08:19
Hi @VladyslavBondarenko,
It seems to be fixed, I can't reproduce it as well.

**Comment by VladyslavBondarenko** [comment] 2020-05-21 12:07
oh, I accidentally tagged not the author)
Closing. If somebody still experiences the issue - feel free to comment or file a new issue

**Closed by VladyslavBondarenko** 2020-05-21 12:07 UTC
Labels: e: OS Version specific, f: scrolling, framework, platform-ios, waiting for customer response

**Comment by themobilecoder** [comment] 2020-06-11 02:41
> -

This problem still exists in the stable version though: Flutter v1.17.3

**Comment by do4Mother** [comment] 2020-07-12 23:09
> > Hi @RockinPaul
> > Does the issue persist?
> > I can't reproduce it with iOS 13.4.5 on `dev 1.18.0-10.0.pre`
> 
> This problem still exists in the stable version though: Flutter v1.17.3

confirm, i think this problem still exists in the stable version. i use flutter 1.17.5

here is my flutter doctor

Last login: Mon Jul 13 05:19:43 on console
 ~ flutter doctor -v
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.5 19F101, locale en-ID)
    • Flutter version 1.17.5 at /Users/do4mother/Development/flutter
    • Framework revision 8af6b2f038 (12 days ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/do4mother/Development/Android
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/do4mother/Development/Android
    • Java binary at:
      /Library/Java/JavaVirtualMachines/jdk1.8.0_251.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_251-b08)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1

[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup
      for detailed instructions).

[✓] VS Code (version 1.47.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[✓] Connected device (1 available)
    • iPhone SE (2nd generation) • 31E88AFA-14F6-4278-8A80-1328744FC4EA • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-13-4 (simulator)

! Doctor found issues in 1 category.

**Comment by iapicca** [comment] 2020-07-20 06:08
Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by AcmeField** [comment] 2020-07-29 13:40
> > 添加物理后，iphone上仍然存在问题。有解决方案吗？
> 
> 你好！关于对我也不起作用的@Tecode解决方案-尝试将ClampingScrollPhysics设置为嵌套的ListView，而不是NestedScrollView本身。这是我目前发现的唯一解决方法。

nice ， got it

**Comment by 939333606** [comment] 2020-08-10 06:15
这个问题还没修复吗？可不可以贴一个终极解决方法的代码？
