### ISSUE TITLE
[firebase-auth/google_sign_in] Visual bug when signing in

### ISSUE THREAD

**Issue by tensor-programming** [flutter/flutter#45483] opened 2019-11-24 05:25 UTC
## Steps to Reproduce

1. Sign in with google on an account that has already signed in once before in a flutter app

**Target Platform:** Android
**Devices:** Emulator and Physical Devices

**Flutter Version:** Flutter (Channel stable, v1.9.1+hotfix.6, on Microsoft Windows [Version 10.0.19025.1052], locale en-US)
**firebase_auth:** ^0.15.0+1
**google_sign_in:** ^4.0.14

You can see an example of this visual bug from a live stream I did a bit ago: https://youtu.be/OlcYP6UXlm8?t=3132

When you click sign in with google, the screen fades slightly and then a bar drops down from the top before the screen fades back in.  According to one of my Subscribers, this problem persists on the current stable version of flutter and it also exists while running in a physical application with a release version of the app.  I have verified this bug myself after the subscriber mentioned it to me.  There is nothing in my application that I can see that would cause this behavior.  I also recall seeing it in previous applications.

**Comment by iapicca** [comment] 2019-11-25 10:47
Hi @tensor-programming (big fan here)
I see you recently update the [source code](https://github.com/tensor-programming/firebase_auth_example_stream) available in the video you linked,
I take it as a viable minimal code sample to reproduce the problem;
could you please provide your `flutter run --verbose` ?

If you believe that the issue is caused by firebase-auth,
please open the issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues).
thank you

**Comment by tensor-programming** [comment] 2019-11-28 19:42
Thank you (flattered that a core contributor is a fan!).  

I did not realize that you guys had split off some of the `flutterfire plugins` to their own repository.  I am not sure if the problem is in `firebase_auth` though that seems likely.  After thanksgiving today, Ill take the code and bring it down to a much more minimal example. I think all I need to do to replicate the problem is just sign in with `firebase_auth` using a provider like Google or Facebook instead of email/password.  What part of the `flutter run --verbose` log do you require?  Should I just give you the portion of the log as I am clicking on the button or the entire log from boot up till close?

**Comment by iapicca** [comment] 2019-11-29 08:17
> Should I just give you the portion of the log as I am clicking on the button or the entire log from boot up till close?

yes please, 
thanks again 
and have a nice thanksgiving

**Comment by tensor-programming** [comment] 2019-11-30 06:01
Not really sure if that means the entire log or what. 

[Here is the log that I generated](https://pastebin.com/yd8raXfr) (at least as much as I could grab given my terminal's line limit).  

At the bottom, I included a set of lines that happen when you click on the sign in to google button in the application.

```
// Information from clicking the login button:
[+4126 ms] W/ActivityThread( 8147): handleWindowVisibility: no activity for token android.os.BinderProxy@d7bc475
[ +121 ms] D/EGL_emulation( 8147): eglMakeCurrent: 0xe6d7c4a0: ver 3 0 (tinfo 0xd32aefd0)
[ +331 ms] D/EGL_emulation( 8147): eglMakeCurrent: 0xe6d7c4a0: ver 3 0 (tinfo 0xd32aefd0)
[  +45 ms] W/BiChannelGoogleApi( 8147): [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzak@1f49dd
[ +390 ms] D/FirebaseAuth( 8147): Notifying id token listeners about user ( ueAquSTWLrViVSdbLtFxtyYZNO82 ).
// print function call
[   +5 ms] I/flutter ( 8147): signed in with google ueAquSTWLrViVSdbLtFxtyYZNO82
```

The log that this was taken from is a simplified version of the original app without the router logic and the facebook signin process. (You can just click the button to sign in with a gmail account but it doesn't go anywhere).  The source is [here](https://github.com/tensor-programming/firebase_auth_example_stream/tree/gltich-example)  I still see the visual glitch which indicates that its likely `google_sign_in` related. The screen fade does look similar to what happens when the screen fades and you sign in for the first time.

**Comment by ditman** [comment] 2020-01-13 18:00
I'm closing this issue in favor of the slightly more recent #48371 (seems to contain a smaller repro case). Thanks for reporting!

**Closed by ditman** 2020-01-13 18:00 UTC
Labels: p: first party, p: google_sign_in, plugin, ▣ platform-android
