### ISSUE TITLE
Flutter 2 web development , How to proxy  backend service ?

### ISSUE THREAD

**Issue by toplinuxsir** [flutter/flutter#77305] opened 2021-03-05 01:00 UTC
Flutter 2 web development , How to proxy  backend service ?
For Example:
 My real service running on: http://web-server:8080
 flutter run -d chrome:
http://localhost:57900/
For CORS  ,

how to access http://web-server:8080/login in flutter app ?

**Comment by darshankawar** [comment] 2021-03-05 09:50
Closing this as duplicate of https://github.com/flutter/flutter/issues/51530

**Closed by darshankawar** 2021-03-05 09:50 UTC
Labels: in triage

**Comment by toplinuxsir** [comment] 2021-03-07 06:52
@darshankawar  When will the feature be ready ?
