### ISSUE TITLE
[image_picker] App crashes on camera click on Android 10 (Redmi 7A)

### ISSUE THREAD

**Issue by tanushreeShelare** [flutter/flutter#98014] opened 2022-02-08 07:50 UTC
I am using the latest package of `image_picker 0.8.4+6`  and compileSdkVersion 31. It is crashing on opening camera.

**Comment by maheshmnj** [comment] 2022-02-08 09:39
Hi @tanushreeShelare, Thanks for filing the issue. Please share the complete output of `flutter run -v` in a text file along with the output of `flutter doctor -v` to investigate further.

**Comment by maheshmnj** [comment] 2022-02-08 12:22
thanks for the info could you please recheck your log file I see lot of `\cf6` characters in between, Probably this is due to some different terminal

**Comment by tanushreeShelare** [comment] 2022-02-09 05:22
Hi, please check this file. 
[logrunv.txt](https://github.com/flutter/flutter/files/8029683/logrunv.txt)

**Comment by maheshmnj** [comment] 2022-02-09 05:45
@tanushreeShelare, The logs doesn't seem to show any crash errors could you please re run `flutter run -v` and interact with the app so as to reproduce the crash and then share the logs.

**Comment by tanushreeShelare** [comment] 2022-02-09 06:11
https://user-images.githubusercontent.com/40851611/153132129-452dcfd8-19ae-46ef-8725-6f42b07730be.mp4

Sorry, I could not log the crash due to unavailability of android10 phone currently. And the crash is not logged in crashlytics too. I am sending a video if that helps.

**Comment by maheshmnj** [comment] 2022-02-09 06:50
@tanushreeShelare from the video it doesn't seem like app is crashing, on the 17th second did the app navigate to correct route, or did it restart the app? if the latter this seems same issue as https://github.com/flutter/flutter/issues/96859

**Comment by tanushreeShelare** [comment] 2022-02-09 07:23
Okay. Thanks for the response. on the 17th second , it restarts the app. Can you suggest anything we could do to solve this memory/OS issue?

**Comment by maheshmnj** [comment] 2022-02-09 07:42
Thanks for the confirmation. This has been a frustrating issue for quite a few years now, see this https://github.com/flutter/flutter/issues/48016 and this seems to be happening because the OS is killing the application to free memory, You can read more about this issue and How to handle it in this comment [this comment](https://github.com/flutter/flutter/issues/48016#issuecomment-971918009), same has been updated in the [readme of the plugin.](https://pub.dev/packages/image_picker)

Closing as this is not really an issue with flutter. In case you disagree feel free to write in the comments and we will reopen it.

Thank you.

**Closed by maheshmnj** 2022-02-09 07:42 UTC
Labels: in triage
