### ISSUE TITLE
"Writing platform-specific code" android code not working

### ISSUE THREAD

**Issue by jeffersondarcy** [flutter/flutter#56674] opened 2020-05-08 14:39 UTC
the code example from https://flutter.dev/docs/development/platform-integration/platform-channels?tab=android-channel-java-tab produces an error if I use another plugins in my app  
seems like I have to add 
`super.configureFlutterEngine(flutterEngine);`
as a first line of `public void configureFlutterEngine(`  
or I will get an error `Unhandled Exception: MissingPluginException(No implementation found for method` for the other plugin  
https://github.com/flutter/flutter/issues/56548

**Comment by TahaTesser** [comment] 2020-05-08 15:03
Hi @jeffersondarcy 
can you please provide your `flutter doctor -v` and `flutter run --verbose`? '
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by jeffersondarcy** [comment] 2020-05-11 08:38
```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v1.17.0, on Linux, locale en_US.UTF-8)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions.
[!] Android Studio (version 3.6)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] VS Code (version 1.43.2)
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[!] Connected device
    ! No devices available

! Doctor found issues in 4 categories.

```

**Comment by jeffersondarcy** [comment] 2020-05-11 08:42
MainActivity.java
```
package com.example.einkapp;

import androidx.annotation.NonNull;
import io.flutter.embedding.android.FlutterActivity;
import io.flutter.embedding.engine.FlutterEngine;
import io.flutter.plugin.common.MethodChannel;

public class MainActivity extends FlutterActivity {
  private static final String CHANNEL = "e-ink.fitdev.io/screen-capture";

  @Override
  public void configureFlutterEngine(@NonNull FlutterEngine flutterEngine) {
    super.configureFlutterEngine(flutterEngine);
    new MethodChannel(flutterEngine.getDartExecutor().getBinaryMessenger(), CHANNEL)
      .setMethodCallHandler(
        (call, result) -> {
          if (call.method.equals("getScreenImage")) {
                result.success("hello bla bla");
            } else {
              result.notImplemented();
            }
        }
      );
  }
}
```

**Comment by jeffersondarcy** [comment] 2020-05-11 08:45
if I don't use other plugins everything works without the line
`super.configureFlutterEngine(flutterEngine);`  
but if I do it breaks without

**Comment by TahaTesser** [comment] 2020-05-11 14:50
There is already an issue for this  [#4004](https://github.com/flutter/website/issues/4004)

**Comment by goderbauer** [comment] 2020-05-13 21:31
Closing as a duplicate of https://github.com/flutter/website/issues/4004.

/cc @sfshaza2 FYI.

**Closed by goderbauer** 2020-05-13 21:31 UTC
Labels: customer: crowd, d: examples, d: website - content, documentation, framework
