### ISSUE TITLE
[tool_crash] FileSystemException: Cannot open file, OS Error: The system cannot find the file specified., errno = 2

### ISSUE THREAD

**Issue by NININAHAZWE04** [flutter/flutter#159603] opened 2024-11-29 05:22 UTC
## Command
```sh
flutter 
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Cannot open file, OS Error: The system cannot find the file specified.
, errno = 2
```console
#0      _File.throwIfError (dart:io/file_impl.dart:675:7)
#1      _File.openSync (dart:io/file_impl.dart:490:5)
#2      _File.writeAsBytesSync (dart:io/file_impl.dart:644:31)
#3      _File.writeAsStringSync (dart:io/file_impl.dart:668:5)
#4      ForwardingFile.writeAsStringSync (package:file/src/forwarding/forwarding_file.dart:150:16)
#5      ErrorHandlingFile.writeAsStringSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:279:22)
#6      _runSync (package:flutter_tools/src/base/error_handling_io.dart:600:14)
#7      ErrorHandlingFile.writeAsStringSync (package:flutter_tools/src/base/error_handling_io.dart:278:5)
#8      Cache.setStampFor (package:flutter_tools/src/cache.dart:673:35)
#9      VersionCheckStamp.store (package:flutter_tools/src/version.dart:798:30)
#10     FlutterVersion._getLatestAvailableFlutterDate (package:flutter_tools/src/version.dart:338:31)
<asynchronous suspension>
#11     FlutterVersion.checkFlutterVersionFreshness (package:flutter_tools/src/version.dart:285:47)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:383:11)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:5)
<asynchronous suspension>
#15     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:130:9)
<asynchronous suspension>
#16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#17     main (package:flutter_tools/executable.dart:93:3)
```
```console
[32m[✓][39m Flutter (Channel stable, 3.24.5, on Microsoft Windows [Version 10.0.22635.4515], locale en-US)
    [32m•[39m Flutter version 3.24.5 on channel stable at C:\Users\ninin\Documents\flutter\flutter_windows_3.24.5-stable\flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision dec2ee5c1f (2 weeks ago), 2024-11-13 11:13:06 -0800
    [32m•[39m Engine revision a18df97ca5
    [32m•[39m Dart version 3.5.4
    [32m•[39m DevTools version 2.37.3



**Comment by darshankawar** [comment] 2024-11-29 09:01
Closing this as a duplicate of https://github.com/flutter/flutter/issues/68958

**Closed by darshankawar** 2024-11-29 09:01 UTC
Labels: in triage
