### ISSUE TITLE
[firebase_messaging] and [shared_preferences] don't work together

### ISSUE THREAD

**Issue by devxpy** [flutter/flutter#99176] opened 2022-02-25 20:57 UTC
Hey, I've noticed that in `shared_preferences: 2.0.9`, the migration to federated packages broke the ability to use it in the `FirebaseMessaging.onBackgroundMessage` handler.

If I try to use `SharedPreferences.getInstance()` inside of `FirebaseMessaging.onBackgroundMessage`, I get the following error -

```
I/flutter (21244): FlutterFire Messaging: An error occurred in your background messaging handler:
I/flutter (21244): MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences)
```

Note that this works fine in `shared_preferences: 2.0.8`.

<details>
  <summary>Logs</summary>

```
$ flutter doctor -v
[✓] Flutter (Channel stable, 2.10.2, on macOS 12.2.1 21D62 darwin-arm, locale en-IN)
    • Flutter version 2.10.2 at /Users/dev/Tools/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 097d3313d8 (7 days ago), 2022-02-18 19:33:08 -0600
    • Engine revision a83ed0e5e3
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0-rc3)
    • Android SDK at /Users/dev/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0-rc3
    • Java binary at: /Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_275-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.2)
    • IntelliJ at /Users/dev/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/213.6777.52/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.56.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.22.0

[✓] Connected device (3 available)
    • POCO F1 (mobile) • e19ec1f6 • android-arm64  • Android 11 (API 30)
    • macOS (desktop)  • macos    • darwin-arm64   • macOS 12.2.1 21D62 darwin-arm
    • Chrome (web)     • chrome   • web-javascript • Google Chrome 98.0.4758.109
    ! Error: iPad is not connected. Xcode will continue when iPad is connected. (code -13)

[✓] HTTP Host Availability
    • All required HTTP hosts are available

```

</details>

**Comment by stuartmorgan** [comment] 2022-02-25 21:50
Duplicate of https://github.com/flutter/flutter/issues/98473

See https://github.com/flutter/flutter/issues/98473#issuecomment-1041895729 for a workaround.

**Closed by stuartmorgan** 2022-02-25 21:50 UTC
