### ISSUE TITLE
Textinput bug on Samsung device

### ISSUE THREAD

**Issue by seritaApp** [flutter/flutter#41315] opened 2019-09-25 19:10 UTC
Tested with flutter gallery app on Samsung Galaxy Tab S4

1. Begin to type a word
2. Leave keyboard mode
3. Refocus and continue typing
Instead of adding the new characters, the previous word gets repeated again
Happens even on the gallery app so it's not related to my code.

Edit: I was trying to type "words" here
![ezgif-4-241b62f05f83](https://user-images.githubusercontent.com/55809519/65631923-d1f5fd00-dfd8-11e9-84ca-47715927cbf2.gif)

**Comment by mklim** [comment] 2019-09-25 21:27
Can you post the output of `flutter doctor -v`?

**Comment by justinmc** [comment] 2019-09-25 21:29
Related: https://github.com/flutter/flutter/issues/31512

**Comment by seritaApp** [comment] 2019-09-25 21:31
> Can you post the output of `flutter doctor -v`? Thank you for filing an issue!

[✓] Flutter (Channel master, v1.10.6-pre.75, on Linux, locale de_DE.UTF-8)
    • Flutter version 1.10.6-pre.75 at /opt/flutter
    • Framework revision bcbe822d02 (vor 16 Minuten), 2019-09-25 17:12:41 -0400
    • Engine revision efb7bf434f
    • Dart version 2.6.0 (build 2.6.0-dev.2.0 69b5681546)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /home/jofu/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Android Studio (version 3.5)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] IntelliJ IDEA Community Edition (version 2019.2)
    • IntelliJ at /usr/share/idea
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] Connected device (1 available)
    • SM T835 • ce03182369165611017e • android-arm64 • Android 9 (API 28)

! Doctor found issues in 1 category.

**Comment by mklim** [comment] 2019-09-25 21:37
@seritaApp thanks. It could be related to flutter/engine#12432 since you are using a version of Flutter that includes it. I do think it's unlikely though because that code shouldn't behave any differently when using a non-Korean input method like in the reproduction GIF. This looks like a duplicate of #31512 to me.

If you see the problem consistently now, do you mind testing out an earlier version of Flutter and seeing if you still see it? That would help narrow it down some. `flutter channel dev` would switch to a week old version at this point that doesn't have that new commit.

**Comment by seritaApp** [comment] 2019-09-25 21:51
I have tested it in dev, beta and stable and can reproduce the issue. I have also downloaded apps from the Playstore which were made with flutter according to itsallwidgets.com and they all had the issue.

**Comment by seritaApp** [comment] 2019-09-25 21:52
Also related: [#30656](https://github.com/flutter/flutter/issues/30656)

**Comment by seritaApp** [comment] 2019-09-25 21:56
Yep you are right, it's probably a duplicate of #31512

**Comment by justinmc** [comment] 2019-09-25 21:58
Maybe that engine fix needs to happen for English input as well as Korean?

**Comment by mklim** [comment] 2019-09-25 22:00
Okay, thank you for the detailed reproduction info @seritaApp . I'm going to close this as a duplicate of #31512.

@justinmc I'm not totally convinced that the restart IMM engine fix actually covers this issue, or is the least invasive fix for it. It may, just not sure. If we get repro though we could test it out and enable it for all Samsung keyboards if that makes sense.

**Closed by mklim** 2019-09-25 22:00 UTC
Labels: a: text input, e: device-specific, ▣ platform-android
