### ISSUE TITLE
Scaffold.extendBody does not respect the navigationBar height when the body is a CustomScrollView

### ISSUE THREAD

**Issue by cedvdb** [flutter/flutter#105027] opened 2022-05-31 12:59 UTC
follow up of https://github.com/flutter/flutter/issues/104938 which was a misidentified issue.

The actual issue is that when a CustomScrollView is used in the body of a scaffold, it seems like it is not possible to scroll till the end as it would be with a ListView

# Repro

```dart

import 'package:flutter/material.dart';

const Color darkBlue = Color.fromARGB(255, 18, 32, 47);

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: darkBlue,
      ),
      home: Column(
        children: [
          Expanded(
            child: Scaffold(
              extendBody: true,
              body: CustomScrollView(
                slivers: [
                  SliverList(
                    delegate: SliverChildBuilderDelegate(
                        childCount: 10,
                        (ctx, index) => const Card(
                            child: SizedBox(height: 200, width: 200))),
                  ),
                ],
              ),
              bottomNavigationBar: SizedBox(
                height: 70,
                child: Card(
                  color: Colors.cyan,
                  shape: RoundedRectangleBorder(
                    borderRadius: BorderRadius.circular(40),
                  ),
                  margin: const EdgeInsets.all(0),
                  child: const SizedBox(
                    width: double.infinity,
                  ),
                ),
              ),
            ),
          ),
          Container(
            color: Colors.green,
            height: 100,
            width: double.infinity,
          ),
        ],
      ),
    );
  }
}

```

If the body is a simple ListView it works as expected.

```dart
import 'package:flutter/material.dart';

const Color darkBlue = Color.fromARGB(255, 18, 32, 47);

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: darkBlue,
      ),
      debugShowCheckedModeBanner: false,
      home: Column(
        children: [
          Expanded(
            child: Scaffold(
              extendBody: true,
              body: ListView.builder(
          itemCount: 20,
          itemBuilder: (ctx, index) =>
              const Card(child: SizedBox(height: 200, width: 200)),
        ),
              bottomNavigationBar: SizedBox(
                height: 70,
                child: Card(
                  color: Colors.cyan,
                  shape: RoundedRectangleBorder(
                    borderRadius: BorderRadius.circular(40),
                  ),
                  margin: const EdgeInsets.all(0),
                  child: const SizedBox(
                    width: double.infinity,
                  ),
                ),
              ),
            ),
          ),
          Container(
            color: Colors.green,
            height: 100,
            width: double.infinity,
          ),
        ],
      ),
    );
  }
}
```

**Comment by exaby73** [comment] 2022-05-31 13:43
Hey @cedvdb. Should you share a video showing the expected and actual behaviors? I can't notice any UI difference in the 2 code samples you provided.

**Comment by cedvdb** [comment] 2022-05-31 13:46
This is scrolled until the end with the list view:

![image](https://user-images.githubusercontent.com/22280985/171188708-0899b292-6ed6-449e-b293-99c2f032e66b.png)

This is with the custom scroll view:

![image](https://user-images.githubusercontent.com/22280985/171188815-8707ac2b-7e67-4fb9-a2ad-3c151e1c2ed1.png)

Notice that the card is under the bottomNavBar

**Comment by bleroux** [comment] 2022-06-07 08:54
@cedvdb 
I had a look to the PR that introduced `extendBody` : https://github.com/flutter/flutter/pull/27973
So the code sample using `CustomScrollView` works as intended and it's up to the developper to add a blank space at the end of the body (for instance with a `SliverPadding`) :

<details>
<summary>Updated code sample with a `SliverPadding`</summary>

```dart

import 'package:flutter/material.dart';

const Color darkBlue = Color.fromARGB(255, 18, 32, 47);

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: darkBlue,
      ),
      home: Column(
        children: [
          Expanded(
            child: Scaffold(
              extendBody: true,
              body: CustomScrollView(
                slivers: [
                  SliverPadding(
                    padding: const EdgeInsets.only(bottom: 70),
                    sliver: SliverList(
                      delegate: SliverChildBuilderDelegate(
                          childCount: 10,
                          (ctx, index) => const Card(
                              child: SizedBox(height: 200, width: 200))),
                    ),
                  ),
                ],
              ),
              bottomNavigationBar: SizedBox(
                height: 70,
                child: Card(
                  color: Colors.cyan,
                  shape: RoundedRectangleBorder(
                    borderRadius: BorderRadius.circular(40),
                  ),
                  margin: const EdgeInsets.all(0),
                  child: const SizedBox(
                    width: double.infinity,
                  ),
                ),
              ),
            ),
          ),
          Container(
            color: Colors.green,
            height: 100,
            width: double.infinity,
          ),
        ],
      ),
    );
  }
}

```

</details>

I had a look to `ListView` code and found that it adds its own `SliverPadding`.
From `BoxScrollView.buildSlivers` : https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/scroll_view.dart#L660).

Once again, thank you for filing an issue with a great reproducible code sample.
I will close it as it works as intended. Feel free to reopen it, if you think it is still a valid one.

**Closed by bleroux** 2022-06-07 08:54 UTC
Labels: framework, f: material design, f: scrolling, found in release: 3.0, found in release: 3.1
