### ISSUE TITLE
Flutter Web - Font not Loaded in iOS

### ISSUE THREAD

**Issue by billyinferno** [flutter/flutter#94697] opened 2021-12-05 17:38 UTC
## Steps to Reproduce

1. Build flutter web and serve
2. Open application from iOS browser

**Expected results:**
Default font should be loaded

**Actual results:**
Default font is not loaded

**Flutter Doctor**
```
[√] Flutter (Channel beta, 2.8.0-3.3.pre, on Microsoft Windows [Version 10.0.19042.1348], locale en-SG)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[√] Chrome - develop for the web
[√] Android Studio (version 2020.3)
[√] VS Code (version 1.62.3)
[√] Connected device (2 available)
```

**Details Info**
There are no custom font being set on the pubspec. Revert back
Revert back to Flutter 2.7.0-3.1.pre fix the problem.

**Comparison**
|iOS Result|PC Result|
|----------|----------|
|<img src="https://user-images.githubusercontent.com/20193342/144757015-8092f7a6-e3d2-4296-87b3-b02e0d19cfe3.jpeg" width="300">|<img src="https://user-images.githubusercontent.com/20193342/144757087-6eb320df-0997-4ff2-8b74-8fbb5bf4bbd8.JPG" width="300">|

**Comment by danagbemava-nc** [comment] 2021-12-06 10:55
Hi @billyinferno, this is due to a workaround that was introduced due to a bug in `WebKit` in `iOS` 15. This issue was initially caught on master and reported https://github.com/flutter/flutter/issues/93140. 

Kindly see [this comment](https://github.com/flutter/flutter/issues/93140#issuecomment-968982568) for an explanation on why it is that way. 

I tested it with the workaround stated in https://github.com/flutter/flutter/issues/93140#issuecomment-977124254 and it seemed to fix the issue. 

Kindly try the workaround and let me know how it goes, but ultimately, this is a duplicate of #93140.

**Comment by billyinferno** [comment] 2021-12-06 11:02
Hi @danagbemava-nc, noted, and thanks for the info, can close this, and I'll just subscribe to the existing issue report.

Thanks a lot.

**Comment by danagbemava-nc** [comment] 2021-12-06 11:04
Closing as duplicate of #93140

**Closed by danagbemava-nc** 2021-12-06 11:04 UTC
Labels: in triage
