### ISSUE TITLE
'flutter channel beta' breaks flutter command: /e/Src/flutter/bin/cache/dart-sdk/bin/pub: No such file or directory

### ISSUE THREAD

**Issue by remoteportal** [flutter/flutter#48499] opened 2020-01-09 14:46 UTC
Starting out to try my first 'hello, Flutter web' project using these [get-started/web](https://flutter.dev/docs/get-started/web) instructions, the very first command breaks my Flutter or dart environment:

bash # **flutter channel beta**

seemed to work:

> Switching to flutter channel 'beta'...
> git: From https://github.com/flutter/flutter
> git:    41a911099b..a3bbdfb23a  dev             -> origin/dev
> git:  * [new branch]            dnfield-patch-1 -> origin/dnfield-patch-1
> git:    67778b7591..b3deb9139d  fill_paginated_data_table_card -> origin/fill_paginated_data_table_card
> git:    924efae96c..fabf4e3d0d  master          -> origin/master
> git:  * [new branch]            revert-45126-gallery_enable_platform_views -> origin/revert-45126-gallery_enable_platform_views
> git:  * [new branch]            revert-48437-roll_branch -> origin/revert-48437-roll_branch
> git:  * [new tag]               v1.13.7         -> v1.13.7
> git:  * [new tag]               v1.13.6         -> v1.13.6
> git: Branch 'beta' set up to track remote branch 'beta' from 'origin'.
> git: Switched to a new branch 'beta'
> 

But now I can't type ANY flutter command:

bash # **flutter**

> Building flutter tool...
> /e/Src/flutter/bin/flutter: line 46: /e/Src/flutter/bin/cache/dart-sdk/bin/pub: No such file or directory
> Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (9 tries left)

Obviously, I can't use **flutter channel stable** to get back.  Do I have to re-install Flutter/Dart/Android Studio??

My environment some recent time before this happened:

> [√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 6.1.7601], locale en-US)
>     • Flutter version 1.12.13+hotfix.5 at E:\Src\flutter
>     • Framework revision 27321ebbad (4 weeks ago), 2019-12-10 18:15:01 -0800
>     • Engine revision 2994f7e1e6
>     • Dart version 2.7.0
> 
> [√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
>     • Android SDK at C:\Users\pete\AppData\Local\Android\sdk
>     • Android NDK location not configured (optional; useful for native profiling support)
>     • Platform android-29, build-tools 29.0.2
>     • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
>     • All Android licenses accepted.
> 
> [√] Android Studio (version 3.5)
>     • Android Studio at C:\Program Files\Android\Android Studio
>     • Flutter plugin version 42.1.1
>     • Dart plugin version 191.8593
>     • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
> 
> [√] Connected device (1 available)
>     • Mi 9T • 844fb80a • android-arm64 • Android 9 (API 28)
> 
> • No issues found!

**Comment by VladyslavBondarenko** [comment] 2020-01-09 16:27
Hi @remoteportal 
Related to [#12666](https://github.com/flutter/flutter/issues/12666)
Does[ this comment](https://github.com/flutter/flutter/issues/12666#issuecomment-339395571) help to you?
Thank you

**Comment by VladyslavBondarenko** [comment] 2020-02-13 14:55
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. 
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, minimal reproducible sample code (if related), logs and the output of 'flutter doctor -v'  please.

**Closed by VladyslavBondarenko** 2020-02-13 14:55 UTC
Labels: waiting for customer response

**Comment by glowinthedark** [comment] 2021-03-01 21:15
In my case the problem was caused by having the git config key `core.autocrlf=auto` on a _non-windows_ system.

To check the current value use

```bash
git config --global core.autocrlf
```

On a linux/unix-like/mac system it should be either `false` or `input` :

```
git config --global core.autocrlf input
```
