### ISSUE TITLE
Hot restart on Flutter Web taking much longer in 2.5 over 2.2.3

### ISSUE THREAD

**Issue by crazedVic** [flutter/flutter#89874] opened 2021-09-10 18:44 UTC
## Steps to Reproduce

- Create new Flutter application using Android Studio, target platform web.
- Set flutter SDK to 2.5.0.
- Run application in Chrome or Edge.
- Wait for application to appear in browser window.
- Change any Text value to trigger a hot reload.

I only installed FVM to switch between SDK's quickly to specifically troubleshoot this problem.   
I do a flutter clean and pub get after every version switch, before running the app.

**Expected results:** 
Same machine, same project, using Flutter 2.2.3 shows these results, so this is what I would expect:  
```
Performing hot restart...
Waiting for connection from debug service on Chrome...
Restarted application in 175ms.
```

**Actual results:** 
Time for hot restart to take effect varies wildly from 20,000ms to 300,000ms:  
```
Performing hot restart...
Waiting for connection from debug service on Chrome...
Restarted application in 288,483ms
```
<details>
  <summary>Logs</summary>

```
C:\Users\User\projects\Flutter\untitled>flutter run --verbose
[  +54 ms] executing: [C:\Users\User\fvm\default/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +74 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 4cc385b4b84ac2f816d939a49ea1f328c4e0b48e
[        ] executing: [C:\Users\User\fvm\default/] git tag --points-at 4cc385b4b84ac2f816d939a49ea1f328c4e0b48e
[  +59 ms] Exit code 0 from: git tag --points-at 4cc385b4b84ac2f816d939a49ea1f328c4e0b48e
[        ] 2.5.0
[   +6 ms] executing: [C:\Users\User\fvm\default/] git rev-parse --abbrev-ref --symbolic @{u}
[  +52 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\Users\User\fvm\default/] git ls-remote --get-url origin
[  +46 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +93 ms] executing: [C:\Users\User\fvm\default/] git rev-parse --abbrev-ref HEAD
[  +42 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +58 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +48 ms] executing: C:\Users\User\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +35 ms] List of devices attached
[   +6 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +57 ms] Multiple devices found:
[  +20 ms] Chrome (web) • chrome • web-javascript • Google Chrome 93.0.4577.63
[   +1 ms] Edge (web)   • edge   • web-javascript • Microsoft Edge 93.0.961.38
[   +1 ms] [1]: Chrome (chrome)
[        ] [2]: Edge (edge)
[   +1 ms] Please choose one (To quit, press "q/Q")
[        ] : 
[+3289 ms] 1
[  +16 ms] Skipping pub get: version match.
[  +85 ms] Generating C:\Users\User\projects\Flutter\untitled\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +64 ms] Launching lib\main.dart on Chrome in debug mode...
[  +93 ms] Updating assets
[  +60 ms] Waiting for connection from debug service on Chrome...
[  +71 ms] <- reset
[   +5 ms] C:\Users\User\fvm\default\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev C:\Users\User\fvm\default\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root
C:\Users\User\fvm\default\bin\cache\flutter_web_sdk/ --incremental --target=dartdevc --debugger-module-names --experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true --output-dill
C:\Users\User\AppData\Local\Temp\flutter_tools.c8ee1c2b\flutter_tool.b0b55a36\app.dill --libraries-spec file:///C:/Users/User/fvm/default/bin/cache/flutter_web_sdk/libraries.json --packages
C:\Users\User\projects\Flutter\untitled\.dart_tool\package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-root
C:\Users\User\AppData\Local\Temp\flutter_tools.c8ee1c2b\flutter_tools.ca2fe960 --filesystem-scheme org-dartlang-app --initialize-from-dill build\b1b715402d823b7fd5c2b68d2edcb2ce.cache.dill.track.dill
--platform file:///C:/Users/User/fvm/default/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk_sound.dill --sound-null-safety
[   +7 ms] <- compile org-dartlang-app:/web_entrypoint.dart
[+13039 ms] Waiting for connection from debug service on Chrome... (completed in 13.1s)
[   +1 ms] Synced 26.3MB.
[        ] <- accept
[        ] Caching compiled dill
[ +263 ms] [CHROME]:
[   +6 ms] [CHROME]:DevTools listening on ws://127.0.0.1:18262/devtools/browser/2feb0cab-8845-44d9-a925-082a50a45e0c
[ +292 ms] DwdsInjector: Received request for entrypoint at http://localhost:18190/main_module.bootstrap.js
[   +3 ms] MetadataProvider: Loading debug metadata...
[   +8 ms] MetadataProvider: Loaded debug metadata (sound null safety)
[   +5 ms] DwdsInjector: Injected debugging metadata for entrypoint at http://localhost:18190/main_module.bootstrap.js
[+2045 ms] ChromeProxyService: Initializing expression compiler for main_module.bootstrap.js with sound null safety: true
[  +53 ms] DevHandler: Debug service listening on ws://127.0.0.1:26044/wPb4FlpCFrc=/ws

[  +19 ms] This app is linked to the debug service: ws://127.0.0.1:26044/wPb4FlpCFrc=/ws
[   +8 ms] Debug service listening on ws://127.0.0.1:26044/wPb4FlpCFrc=/ws
[        ]  Running with sound null safety 
[   +1 ms]   To hot restart changes while running, press "r" or "R".
[        ] For a more detailed help message, press "h". To quit, press "q".
[   +1 ms] An Observatory debugger and profiler on Chrome is available at: http://127.0.0.1:26044/wPb4FlpCFrc=
[ +392 ms] DevTools activation throttled until 2021-09-10 20:38:38.043538.
[+1392 ms] The Flutter DevTools debugger and profiler on Chrome is available at: http://127.0.0.1:9102?uri=http://127.0.0.1:26044/wPb4FlpCFrc=

```

```
C:\Users\User\projects\Flutter\untitled>flutter analyze
Analyzing untitled...
No issues found! (ran in 1.3s)

```

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.5.0, on Microsoft Windows [Version 10.0.18363.1734], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Chrome - develop for the web
[√] Android Studio (version 2020.3)
[√] VS Code (version 1.60.0)
[√] VS Code, 64-bit edition (version 1.57.0)
[√] Connected device (2 available)
```

</details>

**Comment by vkimone** [comment] 2021-09-10 22:27
same problem

**Comment by iandis** [comment] 2021-09-11 08:16
There's a trick for this. When the hot restarting happen, interact with the web browser (e.g. clicks, scrolls, etc), and boom the ever-lasting hot restart's gone

**Comment by zeksdev** [comment] 2021-09-11 13:05
> There's a trick for this. When the hot restarting happen, interact with the web browser (e.g. clicks, scrolls, etc), and boom the ever-lasting hot restart's gone

The trick is really working fine. Thank you iandis!

**Comment by khari998** [comment] 2021-09-11 16:37
Experiencing the same thing

**Comment by khari998** [comment] 2021-09-11 17:36
I can also confirm that moving my mouse over the chrome window my application is open in triggers the hot reload instantly when it hangs.

**Comment by cyberpwnn** [comment] 2021-09-11 22:48
`Restarted application in 91,068ms.`, and yes, can confirm, hovering over the chrome window oddly finishes the reload.

**Comment by maheshmnj** [comment] 2021-09-13 09:15
Hi @crazedVic, Thanks for filing the issue I can reproduce the issue on the latest stable channel. When I did hot restart while running on `flutter 2.5`, the hot restart never completed until I hovered on the window and it took 

```
Restarted application in 249,053ms.

``` 
and when running on the older version of `flutter 2.2.3` it's quite fast 

```
Restarted application in 762ms.
Restarted application in 288ms.
Restarted application in 478ms.
```

<details>
<summary>flutter doctor -v</summary>


```
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.5.2 20G95 darwin-arm, locale en-GB)
    • Flutter version 2.2.3 at /Users/mahesh/Documents/flutter_dev
    • Framework revision f4abaa0735 (2 months ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.59.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 11.5.2 20G95 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 93.0.4577.63

• No issues found!
```

```
[✓] Flutter (Channel stable, 2.5.0, on macOS 11.5.2 20G95 darwin-arm, locale en-GB)
    • Flutter version 2.5.0 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cc385b4b8 (5 days ago), 2021-09-07 23:01:49 -0700
    • Engine revision f0826da7ef
    • Dart version 2.14.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.59.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 11.5.2 20G95 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 93.0.4577.63

• No issues found!
```
</details>

**Comment by khari998** [comment] 2021-09-14 04:05
Somewhat of a clue as to what is going on. When testing in mobile mode on flutter web, hot reload can permanently hang. In mobile mode, the HTML renderer is used in Flutter. Might have something to do with it.

**Comment by burhankhanzada** [comment] 2021-09-14 17:49
Hot reload working fine if you run project from android studio

**Comment by FiercestT** [comment] 2021-09-15 14:25
Having the exact same issue, my logs are in #90091.

**Comment by annagrin** [comment] 2021-09-16 22:22
should be fixed by https://github.com/flutter/flutter/commit/383930c2bc8a0c68727c3662ad61a5de0022dcb9

(versions 2.6.0-5.2.pre  2.6.0-5.1.pre 2.6.0-5.0.pre currently)

**Comment by annagrin** [comment] 2021-09-16 23:58
@khari998 
> Somewhat of a clue as to what is going on. When testing in mobile mode on flutter web, hot reload can permanently hang regardless of whether you interact with the browser. In mobile mode, the HTML renderer is used in Flutter. Might have something to do with it.

This looks like a different issue - could you please open a separate issue for that?

**Comment by TahaTesser** [comment] 2021-09-17 12:55
@annagrin 
Thanks for the confirmation https://github.com/flutter/flutter/issues/89874#issuecomment-921299387, closing as fixed

**Closed by TahaTesser** 2021-09-17 12:55 UTC
Labels: severe: regression, tool, customer: crowd, a: debugging, platform-web, has reproducible steps, P3, found in release: 2.5, found in release: 2.6

**Comment by christopherfujino** [comment] 2021-10-11 18:28
It looks like we'll need a special dwds release, bumping stable to 11.2.3 brings a `vm_service` conflict:

```
Because flutter_tools depends on dwds 11.2.3 which depends on vm_service 7.2.0, vm_service
  7.2.0 is required.
So, because flutter_tools depends on vm_service 7.1.1, version solving failed.
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (9 tries left)
```

cc @annagrin
