### ISSUE TITLE
Cannot develop in Android only without iOS toolchain

### ISSUE THREAD

**Issue by agbaraka** [flutter/flutter#15062] opened 2018-03-02 12:43 UTC
Hello everyone,

I came across an issue where I cannot build for android platform without having a complete iOS toolchain. This happens when I start working with third party plugins such as google_sign_in and firebase_auth. 
After importing a plugin in 'pubspec.yaml' file and run 'flutter package get', the process fails with a following error:

`xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance`

Is there a way to disable ios toolchain for someone who just wants to work with android platform because installing Xcode is not an option to everyone especially if you are on an old Macbook. By the way Im running macOS 10.11. (and upgrading is not an option).

Happy Hacking everyone!!!

**Comment by mshipton** [comment] 2018-03-02 13:07
I noticed this same issue after upgrading to 0.1.5. I installed Xcode following the Flutter setup instructions and the problem went away. However, when I run my app now on Android I see the following in the logs:

```
Error executing simctl: -6
dyld: Library not loaded: /Library/Developer/PrivateFrameworks/CoreSimulator.framework/Versions/A/CoreSimulator
  Referenced from: /Applications/Xcode.app/Contents/Developer/usr/bin/simctl
  Reason: image not found
```

The app runs on the Android device but it looks like the run tool is try to interact with the iOS simulator. I'm running my app from IntelliJ.

**Comment by mit-mit** [comment] 2018-03-02 15:00
Duplicate of https://github.com/flutter/flutter/issues/14875

**Closed by mit-mit** 2018-03-02 15:00 UTC
