### ISSUE TITLE
Image Picker camera is opening twice time for the first time after permission allow in android

### ISSUE THREAD

**Issue by shruti-techindustan** [flutter/flutter#53748] opened 2020-04-01 12:44 UTC
I am using 29 compile SDK Version. When I capture image from camera after permission allow, it open camera and capture image it again open camera and then capture image. means twice time.
I am only getting issue when permission is requested and tap on allow. It open the camera twice and same for gallery. But its working fine in 28 compile sdk.

**Comment by VladyslavBondarenko** [comment] 2020-04-01 12:58
Hi @shruti-techindustan 
could you provide your `flutter doctor -v`?
are you using the last `image_picker 0.6.4`?

Related to https://github.com/flutter/flutter/issues/50002

**Comment by shruti-techindustan** [comment] 2020-04-01 15:07
@VladyslavBondarenko 
Yes, I am using Version 0.6.4
flutter doctor -v
[√] Flutter (Channel unknown, v1.12.13+hotfix.5, on Microsoft Windows [Version 6.3.9600], locale en-US)
    • Flutter version 1.12.13+hotfix.5 at E:\FlutterSdk\flutter
    • Framework revision 27321ebbad (4 months ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\Mahajan\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 44.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[!] IntelliJ IDEA Community Edition (version 2019.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.2.3
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[!] VS Code, 64-bit edition (version 1.25.0)
    • VS Code at C:\Program Files\Microsoft VS Code
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (3 available)
    • SM M307F   • RZ8M90AZWWA • android-arm64  • Android 10 (API 29)
    • Chrome     • chrome      • web-javascript • Google Chrome 80.0.3987.149
    • Web Server • web-server  • web-javascript • Flutter Tools

! Doctor found issues in 2 categories.

**Comment by zenghuixiang** [comment] 2020-05-09 03:42
I had the same problem, and I solved it this way.
```
Future getImage(index) async {
    Map<PermissionGroup, PermissionStatus> permissions =
    await PermissionHandler()
        .requestPermissions([PermissionGroup.camera]);
    if(permissions[PermissionGroup.camera] != PermissionStatus.granted){
      showToast("无相机访问权限，请设置允许相机权限");
      return;
    }
    var image = await ImagePicker.pickImage(source: ImageSource.camera);
    setState(() {
       _image = image;
    });
  }
```

**Comment by darshankawar** [comment] 2021-02-11 12:13
Verified this issue using latest `image_picker` [repo](https://github.com/flutter/plugins/tree/master/packages/image_picker/image_picker/example) on latest master which uses `compilesdkversion 29`. The issue isn't reproducible.


https://user-images.githubusercontent.com/67046386/107634962-63c6de80-6c90-11eb-97c4-1ff7077d893e.mp4

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.27.0-2.0.pre.65, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-IN)
    • Flutter version 1.27.0-2.0.pre.65 at
      /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision a8075deea3 (8 hours ago), 2021-02-10 22:46:02 -0500
    • Engine revision cdc49c575b
    • Dart version 2.13.0 (build 2.13.0-25.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.53.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (4 available)
    • SM A260G (mobile)           • 5200763ebcfa861f • android-arm    • Android
      8.1.0 (API 27)
    • sdk gphone x86 arm (mobile) • emulator-5554    • android-x86    • Android
      11 (API 30) (emulator)
    • macOS (desktop)             • macos            • darwin-x64     • Mac OS X
      10.15.4 19E2269 darwin-x64
    • Chrome (web)                • chrome           • web-javascript • Google
      Chrome 88.0.4324.150

! Doctor found issues in 1 category.

```

</details>

Closing this as not producible. If anybody disagrees or facing same issue still, write in comments and I'll reopen it.

**Closed by darshankawar** 2021-02-11 12:13 UTC
Labels: p: image_picker, platform-android, plugin
