### ISSUE TITLE
 Crash in InputDecorator after updating to Flutter 1.12

### ISSUE THREAD

**Issue by feinstein** [flutter/flutter#46834] opened 2019-12-12 01:55 UTC
I just upgraded to:

Flutter 1.12.13+hotfix.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 27321eb (23 hours ago) • 2019-12-10 18:15:01 -0800
Engine • revision 2994f7e1e6
Tools • Dart 2.7.0

And my app was running just fine before, but now I got this error:

>An InputDecorator, which is typically created by a TextField, cannot have an unbounded width.
This happens when the parent widget does not provide a finite width constraint. For example, if the InputDecorator is contained by a Row, then its width must be constrained. An Expanded widget or a SizedBox can be used to constrain the width of the InputDecorator or the TextField that contains it.
'package:flutter/src/material/input_decorator.dart':
Failed assertion: line 926 pos 7: 'layoutConstraints.maxWidth < double.infinity'

I can't find it listed as a breaking change [here](https://flutter.dev/docs/development/tools/sdk/release-notes/release-notes-1.12.13), should the docs be updated or isn't this supposed to be a breaking change?

**Comment by feinstein** [comment] 2019-12-12 18:54
I fixed this placing the `TextField` that contains the `InputDecorator` inside an `Expanded`, but since it was rendering just fine before the upgrade, I think there was a breaking change that trigger this different behavior.

**Comment by timsneath** [comment] 2020-01-02 23:22
What version of Flutter were you previously using? The last relevant change I could find (to add this assert) was made in this commit: https://github.com/flutter/flutter/pull/30796

I wonder if we just swallowed the error before? This should always have been an error, as far as I can tell. It would be somewhat interesting to know more about the calling code, but as you say, the fix is the `Expanded` wrapper. It's possible that this is a breaking change that we didn't spot ourselves. Adding @justinmc in case he has any ideas.

One other note for anyone who stumbles upon this issue: you can contribute your own unit tests here: https://github.com/flutter/tests and that will help us identify any change that we make that will break your code.

**Comment by feinstein** [comment] 2020-01-03 13:53
The version was the latest stable version, I only upgrade from stable versions. I will try to find the calling code at the time, but I can't promise, the code was upgraded since then and it was a bit big, so I can assure you that it will break again in a simplified snippet.

**Comment by justinmc** [comment] 2020-01-13 21:35
@feinstein Any progress on finding what the relevant code is?  I can get the error simply by putting a TextField in a Row, but it seems to give me the same error on v1.9.1 as well.

This reminds me of [this recent flutter-dev thread](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/flutter-dev/CNZbwyRfeAk/sYpMVNfDDwAJ), which makes me suspicious.  I'd like to try to bisect this and find the offending commit if I can.

**Comment by feinstein** [comment] 2020-01-13 22:23
sorry @justinmc I just spent 30 minutes trying to find the old code, but I can't see anything on my commits. I think my code wasn't committed when the breaking change happened and then I just changed the whole UI altogether and thus I lost the bug's origin and I can't remember where it was. So sorry :/

**Comment by justinmc** [comment] 2020-01-16 01:16
No worries, thanks for checking.  I see this issue has a few 👍's, let's keep it open.  If anyone else has this problem and can reproduce it, please comment!

**Comment by perclasson** [comment] 2020-02-06 16:00
I tried to investigate this now, and between the two stable versions (v1.12.13 and v1.9.1) there does not seem to have been any suspicious changes  to the TextField:
`git log v1.9.1...v1.12.13 packages/flutter/lib/src/material/text_field.dart`

The examples posted flutter-dev thread are behaving the same on both versions. 

Since we do not have a reproducible example I will close this ticket (feel free to open if we do have reproducible code that behaves differently on the two versions). For anyone else who gets the same error message as the ticket, make sure are using `Expanded`:

```dart
Row(
  children: [
    Expanded(
      child: Column(
        children: [
          TextField(),
        ],
      ),
    ),
  ],
)
```

Or that you have set a max width for the `TextField`:
```dart
Row(
  children: [
    SizedBox(
      width: 400,
      child: TextField(),
    ),
  ],
)
```

**Closed by perclasson** 2020-02-06 16:00 UTC
Labels: a: text input, f: material design, framework, severe: crash, severe: regression

**Comment by feinstein** [comment] 2020-02-06 16:05
Maybe the change wasn't at `TextField` but at `InputDecorator`? Who throws that error message that I posted originally?

**Comment by perclasson** [comment] 2020-02-06 16:14
I agree, it could have been in `InputDecorator` or the other widgets you suggest. I tried to look for changes there too to find a reproducible example, but was unsuccessful:
`git log v1.9.1...v1.12.13 packages/flutter/lib/src/material/input_decorator.dart`

Also the assert is done here: https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/input_decorator.dart#L93

If we do find the root cause, we should make sure to document/fix it as you say.

**Comment by feinstein** [comment] 2020-02-06 16:22
Perfect, thanks.
