### ISSUE TITLE
[video_player] [web] Videos are not working on iOS 17, both Safari and Chrome

### ISSUE THREAD

**Issue by PawlikMichal25** [flutter/flutter#137023] opened 2023-10-21 16:36 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Well, try to show any video using [video_player](https://pub.dev/packages/video_player).

Not sure if it matters, but we're using canvaskit in our app.
We had exactly same implementation for a couple of months and it was working fine, but stopped after iOS 17 update.
It happens both in Safari and Chrome on iOS, also in Incognito.

Exactly same implementation is still working good on Native Android and Flutter Web on Android.

### Expected results

Video plays

### Actual results

Video fails to load and play.

### Code sample

You can just run https://docs.flutter.dev/cookbook/plugins/play-video#complete-example

### Screenshots or Video

I'm aware it might look like some random error or just a networking issue on the video here, but it happens consistently. 

https://github.com/flutter/flutter/assets/15315707/74d660a1-d0ee-4225-8d7e-7bcd5f9c1344

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
flutter doctor -v
[✓] Flutter (Channel stable, 3.13.7, on macOS 14.0 23A344 darwin-x64, locale en-PL)
    • Flutter version 3.13.7 on channel stable at /Users/michal/Dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2f708eb839 (12 days ago), 2023-10-09 09:58:08 -0500
    • Engine revision a794cf2681
    • Dart version 3.1.3
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/michal/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.13.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 14.0 23A344 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 117.0.5938.92

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by huycozy** [comment] 2023-10-23 09:24
Hi @PawlikMichal25 
I checked this on my device `iPhone 7, iOS 15.7.9` and see the video can't be loaded as well. 

There's an open issue addressing a similar case: https://github.com/flutter/flutter/issues/47030 (I see your comment there). Closing this issue in favor of that one, so please follow up on it for further updates.

**Comment by PawlikMichal25** [comment] 2023-10-23 11:01
Are you sure it's gonna receive the same level of attention?

I'm aware of [this](https://github.com/flutter/flutter/issues/47030) issue, but since video actually worked for us for some time, I guess there might be some new problem, related specifically to iOS 17.

**Comment by huycozy** [comment] 2023-10-24 03:25
Re-opening the issue for further info. 

I see you reported that the issue also appeared on iOS 16.7.1 at https://github.com/flutter/flutter/issues/47030#issuecomment-1763315829. Could you share the iOS version that the video player worked on?

**Comment by PawlikMichal25** [comment] 2023-10-24 06:41
on iOS 16.7.1 it was happening 'sometimes' on my iPhone.
on iOS 17 it happens 'always'

**Comment by mdebbar** [comment] 2023-10-26 19:01
From a quick look:
- There are no errors printed in the console.
- The network tab shows 2 (successful) requests to the `butterfly.mp4` video (presumably initiated by the video element):
![image](https://github.com/flutter/flutter/assets/1278212/9bb2f450-a695-495d-a1b5-e5543b9b0334)
- The video element is never inserted into the DOM (which probably means we are failing somewhere before that happens).

Anything rings a bell, @ditman?

I also noticed there was a somewhat [recent PR](https://github.com/flutter/packages/pull/4961) that might be related. Not sure though.

**Comment by ditman** [comment] 2023-10-26 19:18
@mdebbar doesn't ring a bell, but I'll take a look at this ASAP!

If it were related to that change, people could directly depend on the version of the video_player_for_web package released right before that and see if that works for them, so it's not a huge deal.

I'm more concerned that something changed on iOS 17 wrt video. What's most disconcerting is that the video element doesn't even get injected.

**Comment by ditman** [comment] 2023-10-26 19:18
(Assigned to self to debug root cause, at least!)

**Comment by ditman** [comment] 2023-10-28 01:00
OK, I've uploaded a super simple test app here: https://dit-videoplayer-tests.web.app

After some debugging, the problem in Safari is that the Future returned from `VideoPlayerController.initialize()` never completes.

This is because **the web player is not listening to any of the events that the `video` element in Safari is emitting** during initialization. [Code](https://github.com/flutter/packages/blob/main/packages/video_player/video_player_web/lib/src/video_player.dart#L73-L124).

These are the events that are being fired from Safari mobile when initializing the player:

<img width="302" alt="Events fired: loadstart, progress, suspend, durationchange, loadedmetadata" src="https://github.com/flutter/flutter/assets/1255594/dfca9dc0-deae-4a9c-937f-9b748936a7f2">

**IMO we should listen for the [`loadedmetadata` event](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/loadedmetadata_event) (maybe in addition to `canplay`) to signal that the player is initialized.**

(I'll prepare a PR next week addressing this issue, it's late now)


<details>

<summary><tt>main.dart</tt></summary>

```dart
import 'package:flutter/material.dart';
import 'package:video_player/video_player.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Testing video_player'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});
  final String title;
  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  late VideoPlayerController _controller;
  late Future<bool> _initialized;

  @override
  void initState() {
    super.initState();
    _controller = VideoPlayerController.networkUrl(
      Uri.parse('https://flutter.github.io/assets-for-api-docs/assets/videos/bee.mp4'));
    _initialized = _controller.initialize().then((_) async => true);
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            FutureBuilder(future: _initialized, builder: (BuildContext ctx, AsyncSnapshot snap) {
              if (snap.hasData) {
                return AspectRatio(
                  aspectRatio: _controller.value.aspectRatio,
                  child: VideoPlayer(_controller),
                );
              } else {
                return const CircularProgressIndicator();
              }
            }),
          ],
        ),
      ),
    );
  }
}
```

</details>

**Comment by mahdiramezani-mr** [comment] 2023-10-31 20:30
> OK, I've uploaded a super simple test app here: https://dit-videoplayer-tests.web.app (source below)
> 
> After some debugging, the problem in Safari is that the Future returned from `VideoPlayerController.initialize()` never completes.
> 
> This is because **the web player is not listening to any of the events that the `video` element in Safari is emitting** during initialization. [Code](https://github.com/flutter/packages/blob/main/packages/video_player/video_player_web/lib/src/video_player.dart#L73-L124).
> 
> These are the events that are being fired from Safari mobile when initializing the player:
> 
> <img alt="Events fired: loadstart, progress, suspend, durationchange, loadedmetadata" width="302" src="https://user-images.githubusercontent.com/1255594/278782285-dfca9dc0-deae-4a9c-937f-9b748936a7f2.png">
> **IMO we should listen for the [`loadedmetadata` event](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/loadedmetadata_event) (maybe in addition to `canplay`) to signal that the player is initialized.**
> 
> _(I'll prepare a PR next week addressing this issue, it's somewhat late in my TZ now)_
> 
> Source for the test app: main.dart

Hi,
How can I fix that? I also have this problem with ios 17.
VideoPlayerController.initialize never completes.

**Comment by ditman** [comment] 2023-10-31 22:14
**(I'll prepare a PR next week addressing this issue, it's somewhat late in my TZ now)**

Patience friends!

**Comment by ditman** [comment] 2023-11-01 10:53
Everybody on this thread could potentially use [my branch](https://github.com/ditman/flutter-packages/tree/video-player-listen-ios17-events/packages/video_player/video_player_web) as a `dependency_overrides` on their puspec.yaml to get the fix before it lands.

[Docs on git dependencies](https://dart.dev/tools/pub/dependencies#git-packages).

* `url`: git@github.com:ditman/flutter-packages.git
* `ref`: video-player-listen-ios17-events
* `path`: packages/video_player/video_player_web

**Comment by mahdiramezani-mr** [comment] 2023-11-01 15:02
> Everybody on this thread could potentially use [my branch](https://github.com/ditman/flutter-packages/tree/video-player-listen-ios17-events/packages/video_player/video_player_web) as a `dependency_overrides` on their puspec.yaml to get the fix before it lands.
> 
> [Docs on git dependencies](https://dart.dev/tools/pub/dependencies#git-packages).
> 
> * `url`: `git@github.com:ditman/flutter-packages.git`
> * `ref`: `video-player-listen-ios17-events`
> * `path`: `packages/video_player/video_player_web`

Thank you for your attention! 👏

**Comment by ditman** [comment] 2023-11-01 21:16
The fix has landed in the repo, and will be published to pub.dev as `video_player_web: ^2.1.2` (by [this job](https://github.com/flutter/packages/actions/runs/6725008388/job/18278493184)).

The fix should be picked up automatically by `flutter pub`. You may need to `flutter pub upgrade` to ensure that the latest version is downloaded.

**Comment by ditman** [comment] 2023-11-01 22:30
The fix is now published on pub:

* https://pub.dev/packages/video_player_web/changelog

Apologies for the breakage, and thanks for reporting this issue! Keep them coming!

**Closed** 2023-11-01 23:11 UTC
Labels: platform-web, p: video_player, package, e: OS-version specific, assigned for triage, P1, browser: safari-ios, team-web, triaged-web
