### ISSUE TITLE
The Container widget border cannot be set to a dashed line.

### ISSUE THREAD

**Issue by gionchat** [flutter/flutter#51755] opened 2020-03-02 02:02 UTC
The Container widget border cannot be set to a dashed line.
like this:
- - - - - - - - - - - - -

**Comment by JosepBove** [comment] 2020-03-02 06:04
This is a duplicated of #4858

**Comment by jonahwilliams** [comment] 2020-03-02 07:07
Duplicate of https://github.com/flutter/flutter/issues/4858

**Closed by jonahwilliams** 2020-03-02 07:07 UTC
