### ISSUE TITLE
Spanish date picker input's placeholder is wrong

### ISSUE THREAD

**Issue by Zazo032** [flutter/flutter#66227] opened 2020-09-20 19:04 UTC
https://github.com/flutter/flutter/blob/51fa704642774c6b6ae64c91642b62801e233e1b/packages/flutter_localizations/lib/src/l10n/material_es.arb#L58

This line should be `dd/mm/aaaa`. If you select a date, it shows it in the correct format (dd/mm/aaaa), but placeholder has a wrong format.

```
Flutter 1.22.0-10.0.pre.269 • channel master • https://github.com/flutter/flutter.git
Framework • revision 51fa704642 (25 hours ago) • 2020-09-19 11:27:04 -0700
Engine • revision 4b8477d115
Tools • Dart 2.10.0 (build 2.10.0-142.0.dev)
```

**Comment by pedromassangocode** [comment] 2020-09-21 09:14
Reproducible on latest `master` channel.

Leaving this for reference: https://en.wikipedia.org/wiki/Date_and_time_notation_in_Spain

**Comment by TheBiirb** [comment] 2020-09-23 05:22
Can we have a sample code for this? Thanks!

**Comment by Zazo032** [comment] 2020-10-06 08:49
> Can we have a sample code for this? Thanks!

Sample code:

<details>
<summary>pubspec.yaml</summary>

```yaml
name: sample
description: Sample Flutter application.
version: 1.0.0+1

environment:
  flutter: ^1.22.0
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

flutter:
  uses-material-design: true
```
</details>

<details>
<summary>main.dart</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';

void main() => runApp(SampleApp());

class SampleApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: HomeRoute(),
      locale: Locale('es'),
      localizationsDelegates: GlobalMaterialLocalizations.delegates,
    );
  }
}

class HomeRoute extends StatelessWidget {
  const HomeRoute();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      floatingActionButton: FloatingActionButton(
        child: const Icon(Icons.calendar_today),
        onPressed: () {
          showDatePicker(
            context: context,
            initialDate: DateTime.now(),
            firstDate: DateTime(2020, 1, 1),
            lastDate: DateTime(2020, 12, 31),
            initialEntryMode: DatePickerEntryMode.input,
          );
        },
      ),
    );
  }
}
```
</details>

**Comment by asashour** [comment] 2021-07-10 19:08
Possibly related to #70341

**Comment by MichaelMarner** [comment] 2021-12-09 22:31
Yes, it's the same issue but for Spanish. This seems to be affecting a lot of locales that use dd/mm/yyyy format.

According to the [comment](https://github.com/flutter/flutter/pull/70421#issuecomment-726495255) on my declined PR for fixing en_AU, this needs to be dealt with from inside Google.

**Comment by darshankawar** [comment] 2023-01-04 10:47
Verified this issue using latest versions and observed that the issue persists.

The placeholder shows `mm/dd/aaaa`, but accepts date in `dd/mm/aaaa` format.

<img width="267" alt="Screenshot 2023-01-04 at 4 14 08 PM" src="https://user-images.githubusercontent.com/67046386/210538737-0f6b5cb8-37eb-42f9-a341-8a3072ddaeaf.png">

<img width="137" alt="Screenshot 2023-01-04 at 4 15 14 PM" src="https://user-images.githubusercontent.com/67046386/210538741-4f73bc24-e441-4138-9f55-a6ed006fdd63.png">

<details>
<summary> runnable code sample </summary>

```

import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';

void main() => runApp(SampleApp());

class SampleApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: HomeRoute(),
     // locale: Locale('es'),
      localizationsDelegates: [
        GlobalMaterialLocalizations.delegate
      ],
      supportedLocales: [
        const Locale('es'),
      //  const Locale('fr')
      ],
    );
  }
}

class HomeRoute extends StatelessWidget {
  const HomeRoute();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      floatingActionButton: FloatingActionButton(
        child: const Icon(Icons.calendar_today),
        onPressed: () {
          showDatePicker(
            locale: const Locale("es", "ES"),
            context: context,
            initialDate: DateTime.now(),
            firstDate: DateTime(2023, 1, 1),
            lastDate: DateTime(2023, 12, 31),
            initialEntryMode: DatePickerEntryMode.input,
          );
        },
      ),
    );
  }
}

```

</details>

<details>
<summary> stable, master flutter doctor -v </summary>

```
[✓] Flutter (Channel stable, 3.3.10, on macOS 12.2.1 21D62 darwin-x64, locale
    en-GB)
    • Flutter version 3.3.10 on channel stable at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (15 hours ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

[!] Flutter (Channel master, 3.7.0-14.0.pre.30, on macOS 12.2.1 21D62
    darwin-x64, locale en-GB)
    • Flutter version 3.7.0-14.0.pre.30 on channel master at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c53501d835 (83 minutes ago), 2023-01-03 23:00:08 -0500
    • Engine revision 32c468507b
    • Dart version 3.0.0 (build 3.0.0-77.0.dev)
    • DevTools version 2.20.0
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.



```

</details>

**Comment by thkim1011** [comment] 2023-05-31 17:30
This is fixed as of https://github.com/flutter/flutter/pull/124094.
![image](https://github.com/flutter/flutter/assets/2004742/b5834127-ddf2-4add-90bf-64617a1faffb)

**Closed by thkim1011** 2023-05-31 17:30 UTC
Labels: framework, f: material design, f: date/time picker, a: internationalization, has reproducible steps, P4, found in release: 3.3, found in release: 3.7
