### ISSUE TITLE
The switch case expression type 'LogicalKeyboardKey' can't override the == operator.

### ISSUE THREAD

**Issue by jimmyff** [flutter/flutter#73863] opened 2021-01-13 15:22 UTC
```dart
onKey: (LogicalKeyboardKey key) {
   switch (key) {
     //  ...
```

results in :
```
The switch case expression type 'LogicalKeyboardKey' can't override the == operator.
```

However this works:
```
if(key== LogicalKeyboardKey.keyW) {
```

Not sure if this is expected behaviour but seems strange i couldn't use it in a switch statement?

**Comment by mkiisoft** [comment] 2021-01-13 15:35
"Switch statements in Dart compare integer, string, or compile-time constants using =="

LINK: https://dart.dev/guides/language/language-tour#switch-and-case

Your logic it's not going to work as Dart can't manage that class using switch/case statement.

**Comment by TahaTesser** [comment] 2021-01-13 15:41
Hi @jimmyff 
This seems to be working as designed, thanks @mkiisoft!
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-01-13 15:41 UTC
