### ISSUE TITLE
[tool_crash] FileSystemException: Cannot create link, OS Error: Access is denied., errno = 5

### ISSUE THREAD

**Issue by 1nternerd** [flutter/flutter#99688] opened 2022-03-07 15:17 UTC
## Command
```
flutter test
```

## Steps to Reproduce
I tried creating a CI/CD pipeline building a Flutter application to Windows with [DroneCI](https://www.drone.io/), but it seems that even though I allowed full access to `C:\drone` permission is still denied when creating a link in `C:\drone\src\windows\flutter\ephemeral\.plugin_symlinks\path_provider_windows`.
I also used a custom image for running the jobs (can be found [here](https://hub.docker.com/r/internerd/windows-flutter)) with Flutter and Dart installed (see the `flutter doctor -v` output below).

1. Create a Drone CI host (eg., via a docker-compose file, can be provided if needed)
2. Create a Windows runner which registers to the DroneCI host (can also be provided)
3. With the following `drone.yml` the logs below are reproducable:
```yml
kind: pipeline
type: docker
name: windows-app

platform:
  platform:
  os: windows
  version: "1809"

steps:
  - name: test
    image: internerd/windows-flutter
    commands:
      - whoami
      - flutter doctor
      - flutter test
```

## Logs
FileSystemException: Cannot create link, path= 'C:\drone\src\windows\flutter\ephemeral\.plugin_symlinks\path_provider_windows' OS Error: Access is denied.
, errno = 5
```
#0      _Link.throwIfError (dart:io/link.dart:263:7)
#1      _Link.createSync (dart:io/link.dart:184:5)
#2      ForwardingLink.createSync (package:file/src/forwarding/forwarding_link.dart:20:16)
#3      ForwardingLink.createSync (package:file/src/forwarding/forwarding_link.dart:20:16)
#4      _createPlatformPluginSymlinks (package:flutter_tools/src/flutter_plugins.dart:1076:12)
#5      createPluginSymlinks (package:flutter_tools/src/flutter_plugins.dart:1011:5)
#6      refreshPluginsList (package:flutter_tools/src/flutter_plugins.dart:1102:5)
<asynchronous suspension>
#7      FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:316:5)
<asynchronous suspension>
#8      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1310:7)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1165:27)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#11     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
<asynchronous suspension>
#15     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
```
```
[✓] Flutter (Channel dev, 2.11.0-0.1.pre, on Microsoft Windows [Version 10.0.17763.2565], locale en-US)
    • Flutter version 2.11.0-0.1.pre at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b101bfe32f (3 weeks ago), 2022-02-16 07:36:54 -0800
    • Engine revision e355993572
    • Dart version 2.17.0 (build 2.17.0-69.2.beta)
    • DevTools version 2.10.0-dev.1

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✗] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Visual Studio - develop for Windows (Visual Studio Build Tools 2019 16.11.10)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
    • Visual Studio Build Tools 2019 version 16.11.32126.315
    • Windows 10 SDK version 10.0.20348.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[✓] Connected device (1 available)
    • Windows (desktop) • windows • windows-x64 • Microsoft Windows [Version 10.0.17763.2565]

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 3 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+2
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 5f105a6ca7a5ac7b8bc9b241f4c2d86f4188cf5c

### Plugins
firebase_core-1.12.0
firebase_core_web-1.5.4
path_provider-2.0.9
path_provider_android-2.0.11
path_provider_ios-2.0.7
path_provider_linux-2.1.5
path_provider_macos-2.0.5
path_provider_windows-2.0.5

**Comment by darshankawar** [comment] 2022-03-08 06:40
Closing this as duplicate of https://github.com/flutter/flutter/issues/96568

**Closed by darshankawar** 2022-03-08 06:40 UTC
Labels: in triage
