### ISSUE TITLE
About Flutter Supporting Hot Repair

### ISSUE THREAD

**Issue by zxylovewl1** [flutter/flutter#36509] opened 2019-07-19 02:19 UTC
Users can fix bugs by downloading patches after installing apk

**Comment by BondarenkoStas** [comment] 2019-09-25 14:08
@zxylovewl1 Probably I just don't know the context, but please explain it in more details.

**Comment by jonahwilliams** [comment] 2019-09-25 14:38
This is a duplicate of https://github.com/flutter/flutter/issues/14330

**Closed by jonahwilliams** 2019-09-25 14:38 UTC
Labels: waiting for customer response
