### ISSUE TITLE
Flutter build failed while copy the flutter_assets, could not generator App.framework.

### ISSUE THREAD

**Issue by LongXiangGuo** [flutter/flutter#50542] opened 2020-02-11 06:38 UTC
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter run --verbose-system-logs --trace-startup --trace-skia

## exception

```
FileSystemException: FileSystemException: Directory listing failed, path = '/Users/xxxx/mobile-connected/feature_modules/destinations/sandbox/build/flutter_assets/packages/destinations/sandbox/build/flutter_assets/packages/destinations/sandbox/ios/Flutter/App.framework/flutter_assets/packages/destinations/sandbox/build/flutter_assets/packages/destinations/sandbox/ios/Flutter/App.framework/flutter_assets/packages/destinations/sandbox/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/App.framework/flutter_assets/packages/destinations/sandbox/build/flutter_assets/packages/destinations/sandbox/ios/Flutter/App.framework/flutter_assets/packages/destinations/sandbox/build/flutter_assets/packages/destinations/sandbox/build/flutter_assets/packages/destinations/sandbox/build/flutter_assets/packages/destinations/sandbox/build/flutter_assets/packages/destinations/sandbox/build/flutter_assets/packages/destinations/sandbox/ios/Flutter/App.framework/flutter_assets/packages/destinations/sandbox/ios/.symlinks/plugins/webview_flutter/example/ios/Runner/Assets.xcassets/LaunchImage.imageset/READ' (OS Error: File name too long, errno = 63)
```

```
#0      _Directory._fillWithDirectoryListing (dart:io-patch/directory_patch.dart:37:68)
#1      _Directory.listSync (dart:io/directory_impl.dart:249:5)
#2      ForwardingDirectory.listSync (package:file/src/forwarding/forwarding_directory.dart:45:12)
#3      _AssetDirectoryCache.variantsFor (package:flutter_tools/src/asset.dart:500:63)
#4      _parseAssetFromFile (package:flutter_tools/src/asset.dart:640:29)
#5      _parseAssets (package:flutter_tools/src/asset.dart:564:7)
#6      _ManifestAssetBundle.build (package:flutter_tools/src/asset.dart:174:57)
<asynchronous suspension>
#7      buildAssets (package:flutter_tools/src/bundle.dart:137:40)
<asynchronous suspension>
#8      BundleBuilder.build (package:flutter_tools/src/bundle.dart:106:38)
<asynchronous suspension>
#9      IOSSimulator._sideloadUpdatedAssetsForInstalledApplicationBundle (package:flutter_tools/src/ios/simulators.dart:442:28)
#10     IOSSimulator._setupUpdatedApplicationBundle (package:flutter_tools/src/ios/simulators.dart:410:11)
<asynchronous suspension>
#11     IOSSimulator.startApp (package:flutter_tools/src/ios/simulators.dart:339:15)
<asynchronous suspension>
#12     FlutterDevice.runCold (package:flutter_tools/src/resident_runner.dart:439:46)
#13     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#14     _rootRunUnary (dart:async/zone.dart:1132:38)
#15     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#16     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#17     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#18     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#19     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#20     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552:7)
#21     _rootRun (dart:async/zone.dart:1124:13)
#22     _CustomZone.run (dart:async/zone.dart:1021:19)
#23     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#24     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#25     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#26     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#27     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#28     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.14.6 18G103, locale zh-Hans-CN)
    [32m•[39m Flutter version 1.9.1+hotfix.6 at /Users/qxq4633/Desktop/development/flutter
    [32m•[39m Framework revision 68587a0916 (5 months ago), 2019-09-13 19:46:58 -0700
    [32m•[39m Engine revision b863200c37
    [32m•[39m Dart version 2.5.0

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    [32m•[39m Android SDK at /Users/qxq4633/Library/Android/sdk
    [32m•[39m Android NDK location not configured (optional; useful for native profiling support)
    [32m•[39m Platform android-29, build-tools 29.0.2
    [32m•[39m ANDROID_HOME = /Users/qxq4633/Library/Android/sdk
    [32m•[39m Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Xcode - develop for iOS and macOS (Xcode 10.2.1)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Xcode 10.2.1, Build version 10E1001
    [32m•[39m CocoaPods version 1.6.1

[32m[✓][39m Android Studio (version 3.5)
    [32m•[39m Android Studio at /Applications/Android Studio.app/Contents
    [32m•[39m Flutter plugin version 42.1.1
    [32m•[39m Dart plugin version 191.8593
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[32m[✓][39m VS Code (version 1.42.0)
    [32m•[39m VS Code at /Applications/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version 3.8.1

[32m[✓][39m Connected device (1 available)
    [32m•[39m iPhone Xʀ • 46D06E76-B98A-4FBE-A021-882B3A981D7E • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)

[32m•[39m No issues found!
```

**Comment by dnfield** [comment] 2020-02-11 06:56
This looks like some kind of path concatenation gone awry...

@jonahwilliams ?

**Comment by jonahwilliams** [comment] 2020-02-11 06:57
No clue, but 100% of that code has changed since 1.9.1

**Comment by dnfield** [comment] 2020-02-11 07:14
@LongXiangGuo can you try to reproduce this on master and see if it still happens?

**Comment by LongXiangGuo** [comment] 2020-02-11 08:42
Comment this line of code  it works well. (#/bin/sh "$FLUTTER_ROOT/packages/flutter_tools/bin/xcode_backend.sh" thin )

**Comment by LongXiangGuo** [comment] 2020-02-11 12:18
The Internet download is too slow, will test it tomorrow, while change to master channel it aways download failed, will test it tomorrow. The is a demo for this issue.
- link: https://github.com/LongXiangGuo/flutter_assets_copy_issue.git

**Comment by LongXiangGuo** [comment] 2020-02-12 01:49
> @LongXiangGuo can you try to reproduce this on master and see if it still happens?
Yes, you could test with this demo(https://github.com/LongXiangGuo/flutter_assets_copy_issue.git)

**Comment by jonahwilliams** [comment] 2020-02-15 22:01
Duplicate of https://github.com/flutter/flutter/issues/50880

**Comment by LongXiangGuo** [comment] 2020-02-19 08:46
> Duplicate of #50880

It's not same, Flutter assets in the App.Framwork was copied many times.

**Comment by jonahwilliams** [comment] 2020-02-19 23:46
This sounds a bit like https://github.com/flutter/flutter/issues/45075

Are your assets in a folder or in the directory root?

**Comment by LongXiangGuo** [comment] 2020-02-20 17:27
> This sounds a bit like #45075
> 
> Are your assets in a folder or in the directory root?

In the assets. folder.  
- `feature package` contains a `feature sandbox flutter application`,  
-  Add path refer the to the. In the `feature package` in `feature sandbox flutter application pubspec.yaml.
-  In this way it caused recursive copying, when executor iOS buildPhase thin script, the sandbox directory and feature package assets was copied many times.

**Comment by LongXiangGuo** [comment] 2020-02-21 18:22
> > This sounds a bit like #45075
> > Are your assets in a folder or in the directory root?
> 
> In the assets. folder.
> 
> * `feature package` contains a `feature sandbox flutter application`,
> * Add path refer the to the. In the `feature package` in `feature sandbox flutter application pubspec.yaml.
> * In this way it caused recursive copying, when executor iOS buildPhase thin script, the sandbox directory and feature package assets was copied many times.

@jonahwilliams It **caused by the `- README.md` assets that defined in the feature package pubspec.yaml, and the sandbox both have the same name assets `README. md`, so it caused the  recursive copying, and both copy the whole sandbox directory.  **

**Comment by jonahwilliams** [comment] 2020-02-21 18:25
Thanks for the additional information. This is fundamentally the same issue as https://github.com/flutter/flutter/issues/45075

**Closed by jonahwilliams** 2020-02-21 18:25 UTC
Labels: t: xcode, tool, waiting for customer response, ⌺‬ platform-ios

**Comment by LongXiangGuo** [comment] 2020-02-22 01:42
> Thanks for the additional information. This is fundamentally the same issue as #45075

Yes, thanks for you help, we add the readme just to fix another issue, test unit does not load the assets while run test unit. 

- Package A has no assets.
- Package A dependency Package B, and load assets from Package B.
- When run package A test unit,  could not load the assets.
- So we have to add an default assets to fix sub package assets loading issue. 

I have a idea may be can solve the assets copy issue, add an default naming space for each assets to avoid copy the whole project in to flutter assets. 
And assets folder should not container the Mac OS target.
