### ISSUE TITLE
[google_sign_in] PlatformException(sign_in_failed, com.google.android.gms.common.api.ApiException: 10: , null, null)

### ISSUE THREAD

**Issue by Joldersman** [flutter/flutter#97806] opened 2022-02-04 15:26 UTC
After run await GoogleSignIn().signIn();
get in Console (Nexus 5X_API 32:5554)

PlatformException(sign_in_failed, com.google.android.gms.common.api.ApiException: 10: , null, null)
D/TransportRuntime.SQLiteEventStore( 6791): Storing event with priority=DEFAULT, name=FIREPERF for destination cct
D/TransportRuntime.JobInfoScheduler( 6791): Upload for context TransportContext(cct, DEFAULT, MSRodHRwczovL2ZpcmViYXNlbG9nZ2luZy1wYS5nb29nbGVhcGlzLmNvbS92MS9maXJlbG9nL2xlZ2FjeS9iYXRjaGxvZ1xBSXphU3lDY2traUg4aTJaQVJ3T3MxTEV6RktsZDE1YU9HOG96S28=) is already scheduled. Returning...

**Comment by maheshmnj** [comment] 2022-02-07 06:50
Hi @Joldersman, Thanks for filing the issue. Please ensure that you have added the sha1 fingerprint in the firebase console. if the issue persists please share the output of `flutter doctor -v` the version of the `google_sign_in` plugin along with the steps to reproduce the issue.

duplicate of https://github.com/flutter/flutter/issues/56235 (closed)

**Closed** 2022-02-28 07:10 UTC
Labels: waiting for customer response, in triage
