### ISSUE TITLE
Error waiting for a debug connection: The log reader stopped unexpectedly. Error launching application on V2153

### ISSUE THREAD

**Issue by KeerthanaAnnamalai** [flutter/flutter#143050] opened 2024-02-07 07:57 UTC
### Steps to reproduce

When i try to usb debugging with VIVO V2153, it showing the error. but if i gone with emulator everything is fine.

OS - funtouch OS 13 Global

### Expected results

Need to solve the issue

### Actual results

Launching lib\main.dart on V2153 in debug mode...
Parameter format not correct -
Running Gradle task 'assembleDebug'...                              4.3s
√  Built build\app\outputs\flutter-apk\app-debug.apk.
Error waiting for a debug connection: The log reader stopped unexpectedly
Error launching application on V2153.

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by danagbemava-nc** [comment] 2024-02-07 09:09
Closing this as a duplicate of https://github.com/flutter/flutter/issues/106086

**Closed by danagbemava-nc** 2024-02-07 09:09 UTC
Labels: in triage
