### ISSUE TITLE
issue at cmd when running flutter doctor

### ISSUE THREAD

**Issue by cafej** [flutter/flutter#15130] opened 2018-03-04 14:13 UTC
After cloning the repo, and updating my path variable, the instructions says to `flutter doctor`  and gives me this error
` Checking Dart SDK version...
Downloading Dart SDK from Flutter engine ead227f118077d1f2b57842a32abaf105b573b8a...
Start-BitsTransfer : The service cannot be started, either because it is disabled or because it has no enabled devices
associated with it. (Exception from HRESULT: 0x80070422)
At C:\Users\Carlos\Documents\flutter\bin\internal\update_dart_sdk.ps1:47 char:1
+ Start-BitsTransfer -Source $dartSdkUrl -Destination $dartSdkZip
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Start-BitsTransfer], COMException
    + FullyQualifiedErrorId : StartBitsTransferCOMException,Microsoft.BackgroundIntelligentTransfer.Management.NewBits
   TransferCommand

Error: Unable to update Dart SDK. Retrying...

Waiting for 2 seconds, press CTRL+C to quit ... `

**Comment by starba3** [comment] 2018-03-10 20:30
having the same issue
except i have (Exception from HRESULT: 0x80070424) instead of (Exception from HRESULT: 0x80070422)

**Comment by Hixie** [comment] 2018-06-08 20:57
@cafej The 0x80070422 issue is probably a duplicate of https://github.com/flutter/flutter/issues/12664, so I'm going to close this bug as being caused by that one. Check that bug for suggestions regarding Windows Update settings.

@starba3 Please file a new bug regarding 0x80070424. We will need full logs, a description of your setup, etc. Thanks.

**Closed by Hixie** 2018-06-08 20:57 UTC
