### ISSUE TITLE
Add options to specify GPU memory size for resource cache in Flutter engine

### ISSUE THREAD

**Issue by zexu-xu** [flutter/flutter#22430] opened 2018-09-28 15:56 UTC
## Steps to Reproduce

1. Any apps that loads a lot of images
2. Run the app in memory constrained device like 1 GB ram
3. When GPU memory exhausted, the app is either rendering extremely slow or crashed

In Flutter engine the GPU memory for resource cache is fixed at 512MB [https://github.com/flutter/engine/blob/master/shell/gpu/gpu_surface_gl.cc](https://github.com/flutter/engine/blob/master/shell/gpu/gpu_surface_gl.cc)

If we build an engined with lower values, the rendering and crash issue is gone. But it should make much more sense to add an option and pass the value to the engine on  startup.

**Comment by MaxZeng** [comment] 2018-11-13 13:04
I modified the kGrCacheMaxByteSize from 512MB to 256MB, and the out-of-memory issue is gone on iPhone6 device, but this value is not modified recently, so the OOM issue is not caused by this issue ,but we can temp fix it by changing this value.

The last modification of this value is committed by @chinmaygarde at Feb8 2017 (commit id 0904cf3) 
"Bump up limits on the GrResourceCache used for the main GrContext. (#3394)"

**Comment by jonahwilliams** [comment] 2024-08-13 03:14
This cache is now unused with Impeller. We don't plan to make these values configurable.

**Closed by jonahwilliams** 2024-08-13 03:14 UTC
Labels: engine, c: performance, P2, team-engine, triaged-engine
