### ISSUE TITLE
The video_player plugin fails to play videos (sometimes)

### ISSUE THREAD

**Issue by recastrodiaz** [flutter/flutter#19953] opened 2018-07-29 17:27 UTC
There is a race condition in the video_player plugin code that prevents videos from displaying on a Widget.

## Steps to Reproduce

1. Download a video on your phone: http://www.sample-videos.com/video/mp4/720/big_buck_bunny_720p_20mb.mp4
2. Edit the `image_picker` sample app (https://github.com/flutter/plugins/blob/master/packages/image_picker/example/lib/main.dart#L50) and add the following in line 50 just after `if (file != null && mounted) {`:
``` DART
print(file);
```
3. Run the `image_picker` sample app, enable read permissions from external storage and choose the video from the gallery. Keep note of the video path. It will look something like `/storage/emulated/0/Download/big_buck_bunny_720p_20mb.mp4` (remove the file:// prefix if needed)
4. Replace the main.dart content in `image_picker` by the code below (Based on the `video_player` sample app found [here](https://github.com/flutter/plugins/tree/master/packages/video_player).
4. Open and close the app until the video no longer shows. You should see a blank screen.

```DART
import 'dart:io';

import 'package:video_player/video_player.dart';
import 'package:flutter/material.dart';

void main() => runApp(VideoApp());

class VideoApp extends StatefulWidget {
  @override
  _VideoAppState createState() => _VideoAppState();
}

class _VideoAppState extends State<VideoApp> {
  VideoPlayerController _controller;

  @override
  void initState() {
    try {
      super.initState();
      // _controller = VideoPlayerController.network('http://www.sample-videos.com/video/mp4/720/big_buck_bunny_720p_20mb.mp4',)
      _controller = VideoPlayerController.file(
          new File('/storage/emulated/0/Download/big_buck_bunny_720p_20mb.mp4'))
        ..addListener(() {
          print('controller listener: $_controller');
          // Ensure the first frame is shown after the video is initialized, even before the play button has been pressed.
          setState(() {});
        })
        ..initialize().then((_) {
          print('initialized listener: $_controller');
          setState(() {});
        }).catchError((error) {
          print('Unexpected error1: $error');
        });
      print('controller is set');
    } catch (e) {
      print('Unexpected error: $e');
    }
  }

  @override
  Widget build(BuildContext context) {
    try {
      print('entering build. Needs _controller $_controller');
      return MaterialApp(
        title: 'Video Demo',
        home: Scaffold(
          body: Center(
            child: _controller.value.initialized
                ? AspectRatio(
                    aspectRatio: _controller.value.aspectRatio,
                    child: VideoPlayer(_controller),
                  )
                : Container(),
          ),
          floatingActionButton: FloatingActionButton(
            onPressed: _controller.value.isPlaying
                ? _controller.pause
                : _controller.play,
            child: Icon(
              _controller.value.isPlaying ? Icons.pause : Icons.play_arrow,
            ),
          ),
        ),
      );
    } catch (e) {
      print('Unexpected error: $e');
    }
  }
}

```

Buggy app:

![buggy](https://user-images.githubusercontent.com/1159610/43369080-7193f5fa-935f-11e8-8b68-f689a061317a.png)

Expected:
![not-buggy](https://user-images.githubusercontent.com/1159610/43369083-7b986f86-935f-11e8-9a5a-a3baab00cd36.png)

## Logs

When the video works. You'll see in the logs:
```
I/flutter ( 8147): controller listener: VideoPlayerController#fff7e(VideoPlayerValue(duration: 0:01:57.312000, size: Size(1280.0, 720.0), position: 0:00:00.000000, buffered: [], isPlaying: false, isLooping: false, isBuffering: falsevolume: 1.0, errorDescription: null,rotationDegrees: 0))
I/flutter ( 8147): initialized listener: VideoPlayerController#fff7e(VideoPlayerValue(duration: 0:01:57.312000, size: Size(1280.0, 720.0), position: 0:00:00.000000, buff
```

Otherwise you will see something like (the _controller.value is an empty/default video instance). Notice the initialized listener is never called:

```LOG
I/flutter (10928): controller listener: VideoPlayerController#0235e(VideoPlayerValue(duration: null, size: null, position: 0:00:00.000000, buffered: [], isPlaying: false, isLooping: false, isBuffering: falsevolume: 1.0, errorDescription: null,rotationDegrees: null))
```

## Root Cause

The `initialized` event is not always received in the dart code. This event is sent from the ExoPlayer to the Java code, from there to the Dart world through an Event Channel. However it is possible that the init event from the ExoPlayer is fired before the dart code had a chance to listen to any broadcasts from the Java code (eventSink is null in https://github.com/flutter/plugins/blob/master/packages/video_player/android/src/main/java/io/flutter/plugins/videoplayer/VideoPlayerPlugin.java#L213). In such a case, the init event is not fired and the video cannot be played nor displayed.

``` LOG
flutter doctor -v
[✓] Flutter (Channel master, v0.5.8-pre.152, on Mac OS X 10.12.6 16G1510, locale fr-FR)
    • Flutter version 0.5.8-pre.152 at /Users/rodrigo/Libs/flutter
    • Framework revision 8b05629658 (3 days ago), 2018-07-26 19:12:04 -0700
    • Engine revision 6f7bdc9fab
    • Dart version 2.0.0-dev.69.3.flutter-937ee2e8ca

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/rodrigo/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 26.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[!] IntelliJ IDEA Community Edition (version 2018.1.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[!] VS Code (version 1.25.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected devices (1 available)
    • SM G920F • 02157df2bc245b2a • android-arm64 • Android 7.0 (API 24)

! Doctor found issues in 2 categories.
```

**Comment by recastrodiaz** [comment] 2018-07-29 17:32
This is possibly the same issue experienced by https://github.com/flutter/flutter/issues/19197, https://github.com/flutter/flutter/issues/14198 and https://github.com/flutter/flutter/issues/18836

Note: I have yet to check the iOS plugin code. So some of those issues could be a different bug.

**Comment by sigurdm** [comment] 2018-09-06 13:26
Closing as duplicate of https://github.com/flutter/flutter/issues/21483

**Closed by sigurdm** 2018-09-06 13:26 UTC
Labels: a: video, p: first party, plugin

**Comment by zhen1991** [comment] 2018-11-23 13:09
Hi!
I have just a question can i play a video offline in flutter ?does it work for both ios and android ?

**Comment by zhen1991** [comment] 2018-11-26 17:20
Hi!
I mean without halving network on my device so the wi-fi is off!

**Comment by zoechi** [comment] 2018-11-26 17:32
@zhen1991 yes, when it's stored as a file on your device.

**Comment by sujitpasalkar** [comment] 2018-12-12 11:55
Hi,
i also have one question.
sorry may be this is not the right to ask different question,
Q. i'm using VideoPalyer plugin,this plugin works perfectly,but...video player displaying green overlay on screen.

**Comment by zoechi** [comment] 2018-12-12 13:02
@sujitpasalkar there was a bug fixed recently. Ensure you have the latest Flutter and video_player plugin.

**Comment by P-B1101** [comment] 2020-08-19 12:41
i have same problem on ios 14 beta.
it play online video perfectly but when i download that file and try to play it, nothing happens.
it would not throw error neither.
show nothing in logs.
i'm losing my mind :|

**Comment by leochiu-work** [comment] 2020-09-18 02:20
@P-B1101 , I am not sure if I have the same problem as you.
One of my iOS 14 GM can play video with ONLY sound.
However, my another iOS 14 GM is totally fine.
I am losing my mind also.

**Comment by MisterioRee** [comment] 2020-09-18 19:17
@leochiu-work  You may wanna refer to [this Issue](https://github.com/flutter/flutter/issues/36849) cause i've been suffering from same issue over a week where as issue was https

**Comment by purutechno** [comment] 2020-10-01 01:54
Initialize the initial value of controller as empty url ("") in initState and then place your build function below it.

 _controller = VideoPlayerController.network("")
      ..addListener(() => setState(() {
        videoPosition = _controller.value.position;
      }))
      ..initialize().then((_) => setState(() {
        videoLength = _controller.value.duration;
      }));

**Comment by kamleshwebtech** [comment] 2020-11-07 09:20
I am getting an error 

`E/flutter (22049): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: PlatformException(VideoError, Video player had error com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.audio.AudioSink$InitializationException: AudioTrack init failed: 0, Config(48000, 12, 61504), null, null)`

Any suggestion will be appreciated. Thanks.

**Comment by deepikanathan** [comment] 2021-01-25 15:54
@kamleshwebtech 
Were you able to fix the Platform Exception? If yes, can you please share how?
Thanks.

**Comment by pawanbhardwaj** [comment] 2021-03-05 03:00
> I am getting an error
> 
> `E/flutter (22049): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: PlatformException(VideoError, Video player had error com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.audio.AudioSink$InitializationException: AudioTrack init failed: 0, Config(48000, 12, 61504), null, null)`
> 
> Any suggestion will be appreciated. Thanks.

I am facing the same. 
If anyone can help please!
