### ISSUE TITLE
video_player add header&ssl 

### ISSUE THREAD

**Issue by bensinos** [flutter/flutter#56185] opened 2020-05-02 09:45 UTC
add header api :
add skip ssl check api:

_videoPlayerController.addHeader({header:"xxx"});
_videoPlayerController.setSkipSSLChain(true); 

i need in my project, add please

**Comment by bensinos** [comment] 2020-05-02 09:50
and buffer size api
_videoPlayerController.setBufferSize(1024);

**Comment by TahaTesser** [comment] 2020-05-04 11:02
Hi @bensinos 
Can you please describe in detail why you need features and what use cases you have?
Thank you

**Comment by Akash9151** [comment] 2020-05-06 08:45
Hey @TahaTesser 
I want the header because want to send the cookies and tokens when trying to playing the network video. And the website I'm using to play my videos has as SSL issue and it is creating a problem to play. So Please Can you add these features?

**Comment by TahaTesser** [comment] 2020-05-19 15:30
duplicate of https://github.com/flutter/flutter/issues/16466

**Closed by TahaTesser** 2020-05-19 15:30 UTC
Labels: in triage, waiting for customer response
