### ISSUE TITLE
How to integrate the customized flutter engine into the flutter sdk after compilation

### ISSUE THREAD

**Issue by SpringSea28** [flutter/flutter#152798] opened 2024-08-03 04:00 UTC
### Use case

There are three developer in our flutter app development team. How can the other two use the flutter engine I compiled. 
Maybe we can  integrate it into the flutter sdk, but how to do this? 

### Proposal

Is there any documentation?

**Comment by huycozy** [comment] 2024-08-05 06:43
Hi @SpringSea28
>Maybe we can integrate it into the flutter sdk, but how to do this?

The tool doesn't support this currently, please see https://github.com/flutter/flutter/issues/134426#issuecomment-1724136103.

Closing this as a duplicate of https://github.com/flutter/flutter/issues/134426.

**Closed by huycozy** 2024-08-05 06:43 UTC
Labels: in triage

**Comment by SpringSea28** [comment] 2024-08-05 07:26
Thanks for your reply.  But #134426  seems to be no solution. Could you give me some more help? thanks！

**Comment by huycozy** [comment] 2024-08-06 03:02
The solution for that is: "_You will have to setup a custom CI workflow to distribute locally built engines._". Please see flutter's [community](https://flutter.dev/community) for resources and you may also get some help if you post it on [flutterhelp](https://www.reddit.com/r/flutterhelp/).

**Comment by SpringSea28** [comment] 2024-08-06 06:16
@huycozy Thank you for your patience. 
"You will have to setup a custom CI workflow to distribute locally built engines."，can you please tell me how to setup a custom CI workflow? 
Please help me again, thank you very much！

**Comment by huycozy** [comment] 2024-08-12 03:40
Sorry, this seems to take times to set up such a CI. I may try it later when having spare time. In the meantime, you can try this simpler solution:

From your side:
1. Build your custom engine
2. Push it to your forked repository
3. Share your forked repository to your team

From your team side:
1. Pull your forked repository with your changes on engine
2. Link to the custom engine path with `--local-engine`, `--local-engine-src-path` and `--local-engine-host` flags when running app with flutter tool, see https://github.com/flutter/flutter/tree/master/docs/tool#using-a-locally-built-engine-with-the-flutter-tool

Please note that the above steps are from my idea only, I haven't tried it yet. Hope it helps!

**Comment by SpringSea28** [comment] 2024-08-13 06:48
@huycozy ,thank you very much for your answer. 
Because the compiled engine is 40-50G, your suggestion may not be very suitable for us. 
Thank you very much, you are a very patient and enthusiastic person.
