### ISSUE TITLE
App bar shadow replaced with solid red block during transition

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#6137] opened 2016-09-29 16:22 UTC
Some demos in the Flutter Gallery app show solid red blocks where the app bar shadow is supposed to be (video attached). There's nothing in `flutter logs`.

## Steps to Reproduce

- `flutter run`
- Open, for example, the "Tabs" demo

Gif recording:

![red_shadow](https://cloud.githubusercontent.com/assets/211513/18962554/37624d2a-8626-11e6-8fa7-700e5360cd9c.gif)

## Flutter Doctor

$ flutter doctor
[✓] Flutter (on Mac OS, channel unknown)
    • Flutter at /Users/yjbanov/code/flutter/flutter
    • Framework revision 7f9c8c4b3e (20 hours ago), 2016-09-28 13:09:38
    • Engine revision 3551e7a48e
    • Tools Dart version 1.20.0-dev.5.0

[✓] Android toolchain - develop for Android devices (Android SDK 23.0.3)
    • Android SDK at /Users/yjbanov/Library/Android/sdk
    • Platform android-23, build-tools 23.0.3
    • Java(TM) SE Runtime Environment (build 1.8.0_91-b14)

[✓] iOS toolchain - develop for iOS devices (Xcode 7.3.1)
    • XCode at /Applications/Xcode.app/Contents/Developer
    • Xcode 7.3.1, Build version 7D1014

[✓] Atom - a lightweight development environment for Flutter
    • flutter plugin version 0.2.6
    • dartlang plugin version 0.6.40

[✓] Connected devices
    • Nexus 5 • 0489410543877bdb • android-arm

/cc @sethladd

**Comment by abarth** [comment] 2016-09-29 16:24
Yes, this happens in debug builds.  It's showing you that the toolbar is visually overflowing.  We should probably just remove the debug painting in that case.  It just confuses people.

**Comment by Hixie** [comment] 2016-09-29 16:48
dupe of https://github.com/flutter/flutter/issues/2387

**Closed by Hixie** 2016-09-29 16:48 UTC
Labels: affects: dev experience, customer: gallery, ⚠ bug
