### ISSUE TITLE
Flutter web showing 2 cursors when I run my application in mobile

### ISSUE THREAD

**Issue by PavlyukovYegor** [flutter/flutter#53244] opened 2020-03-25 12:39 UTC
## Steps to Reproduce

1. Run `flutter run -d chrome` or `flutter build web` in docker.
2. Access the application from your phone using any browser.
3. Tap on the text box and try typing.
4. Tap on any part of the text.  (optional)

**Expected results:** 
![image](https://user-images.githubusercontent.com/8119719/77536409-eee68c80-6ea4-11ea-8146-1b2dea06127a.png)

**Actual results:** 
![image](https://user-images.githubusercontent.com/8119719/77536603-438a0780-6ea5-11ea-8c73-4b7005e30180.png)

<details>
  <summary>Logs</summary>

```
[  +26 ms] executing: [/Users/artemboiko/Documents/flutter/] git -c
log.showSignature=false log -n 1 --pretty=format:%H
[  +57 ms] Exit code 0 from: git -c log.showSignature=false log -n 1
--pretty=format:%H
[        ] fabeb2a16f1d008ab8230f450c49141d35669798
[        ] executing: [/Users/artemboiko/Documents/flutter/] git describe
--match v*.*.* --first-parent --long --tags
[  +76 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long
--tags
[        ] v1.14.6-0-gfabeb2a16
[   +9 ms] executing: [/Users/artemboiko/Documents/flutter/] git rev-parse
--abbrev-ref --symbolic @{u}
[   +9 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/beta
[        ] executing: [/Users/artemboiko/Documents/flutter/] git ls-remote
--get-url origin
[   +8 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +47 ms] executing: [/Users/artemboiko/Documents/flutter/] git rev-parse
--abbrev-ref HEAD
[  +10 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] beta
[   +4 ms] executing: sw_vers -productName
[  +13 ms] Exit code 0 from: sw_vers -productName
[        ] Mac OS X
[        ] executing: sw_vers -productVersion
[  +12 ms] Exit code 0 from: sw_vers -productVersion
[        ] 10.15.3
[        ] executing: sw_vers -buildVersion
[  +12 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 19D76
[  +28 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping
update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required,
skipping update.
[  +35 ms] executing: /Users/artemboiko/Library/Android/sdk/platform-tools/adb
devices -l
[   +7 ms] Exit code 0 from:
/Users/artemboiko/Library/Android/sdk/platform-tools/adb devices -l
[        ] List of devices attached
           emulator-5554          device product:sdk_gphone_x86
           model:Android_SDK_built_for_x86 device:generic_x86 transport_id:2
[  +14 ms] executing:
/Users/artemboiko/Documents/flutter/bin/cache/artifacts/libimobiledevice/idevice
_id -h
[  +48 ms] executing: /usr/bin/xcode-select --print-path
[  +10 ms] Exit code 0 from: /usr/bin/xcode-select --print-path
[        ] /Volumes/HDD/Xcode.app/Contents/Developer
[   +1 ms] executing: /usr/bin/xcodebuild -version
[ +722 ms] Exit code 0 from: /usr/bin/xcodebuild -version
[   +1 ms] Xcode 11.3
           Build version 11C29
[   +2 ms] /usr/bin/xcrun simctl list --json devices
[ +129 ms] /Users/artemboiko/Library/Android/sdk/platform-tools/adb -s
emulator-5554 shell getprop
[  +37 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required,
skipping update.
[   +7 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping
update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required,
skipping update.
[  +51 ms] More than one device connected; please specify a device with the '-d
<deviceId>'
           flag, or use '-d all' to act on all devices.
[   +2 ms] ro.hardware = ranchu
[  +39 ms] Android SDK built for x86 вЂў emulator-5554 вЂў android-x86    вЂў Android
10 (API 29)
           (emulator)
[   +1 ms] Chrome                    вЂў chrome        вЂў web-javascript вЂў Google
Chrome
           80.0.3987.149
[        ] Web Server                вЂў web-server    вЂў web-javascript вЂў Flutter
Tools
[  +10 ms] "flutter run" took 1В 217ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:27:3)
#1      RunCommand.validateCommand
(package:flutter_tools/src/commands/run.dart:325:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand
(package:flutter_tools/src/runner/flutter_command.dart:619:11)
<asynchronous suspension>
#3      FlutterCommand.run.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command.dart:537:33)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:150:29)
#5      _rootRun (dart:async/zone.dart:1126:13)
#6      _CustomZone.run (dart:async/zone.dart:1023:19)
#7      _runZoned (dart:async/zone.dart:1518:10)
#8      runZoned (dart:async/zone.dart:1465:12)
#9      AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#10     FlutterCommand.run
(package:flutter_tools/src/runner/flutter_command.dart:527:20)
#11     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#12     FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:338:21)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:150:29)
#14     _rootRun (dart:async/zone.dart:1126:13)
#15     _CustomZone.run (dart:async/zone.dart:1023:19)
#16     _runZoned (dart:async/zone.dart:1518:10)
#17     runZoned (dart:async/zone.dart:1465:12)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#19     FlutterCommandRunner.runCommand
(package:flutter_tools/src/runner/flutter_command_runner.dart:288:19)
#20     CommandRunner.run.<anonymous closure>
(package:args/command_runner.dart:112:25)
#21     new Future.sync (dart:async/future.dart:224:31)
#22     CommandRunner.run (package:args/command_runner.dart:112:14)
#23     FlutterCommandRunner.run
(package:flutter_tools/src/runner/flutter_command_runner.dart:231:18)
#24     run.<anonymous closure>.<anonymous closure>
(package:flutter_tools/runner.dart:64:22)
#25     _rootRun (dart:async/zone.dart:1126:13)
#26     _CustomZone.run (dart:async/zone.dart:1023:19)
#27     _runZoned (dart:async/zone.dart:1518:10)
#28     runZoned (dart:async/zone.dart:1502:12)
#29     run.<anonymous closure> (package:flutter_tools/runner.dart:62:18)
<asynchronous suspension>
#30     AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:150:29)
#31     _rootRun (dart:async/zone.dart:1126:13)
#32     _CustomZone.run (dart:async/zone.dart:1023:19)
#33     _runZoned (dart:async/zone.dart:1518:10)
#34     runZoned (dart:async/zone.dart:1465:12)
#35     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#36     runInContext (package:flutter_tools/src/context_runner.dart:64:24)
#37     run (package:flutter_tools/runner.dart:51:10)
#38     main (package:flutter_tools/executable.dart:65:9)
#39     main
(file:///Users/artemboiko/Documents/flutter/packages/flutter_tools/bin/flutter_t
ools.dart:8:3)
#40     _startIsolate.<anonymous closure>
(dart:isolate-patch/isolate_patch.dart:299:32)
#41     _RawReceivePortImpl._handleMessage
(dart:isolate-patch/isolate_patch.dart:168:12)
```

```
   info вЂў The declaration '_adding' isn't referenced вЂў
          lib/bloc/admin_house.dart:53:19 вЂў unused_element
   info вЂў The declaration '_editing' isn't referenced вЂў
          lib/bloc/admin_house.dart:59:19 вЂў unused_element
   info вЂў Unused import: 'dart:convert' вЂў
          lib/infrastructure/firebase_repository.dart:1:8 вЂў unused_import
   info вЂў Unused import: 'dart:io' вЂў
          lib/infrastructure/firebase_repository.dart:2:8 вЂў unused_import
   info вЂў Unused import: 'package:firebase_auth/firebase_auth.dart' вЂў
          lib/infrastructure/firebase_repository.dart:7:8 вЂў unused_import
   info вЂў Unused import: 'package:osmd_admin/pages/home.dart' вЂў
          lib/main.dart:11:8 вЂў unused_import
   info вЂў 'title' is deprecated and shouldn't be used. This is the term used in
          the 2014 version of material design. The modern term is headline6.
          This feature was deprecated after v1.13.8. вЂў
          lib/style/theme/theme.dart:35:13 вЂў deprecated_member_use
   info вЂў 'headline' is deprecated and shouldn't be used. This is the term used
          in the 2014 version of material design. The modern term is headline5.
          This feature was deprecated after v1.13.8. вЂў
          lib/style/theme/theme.dart:41:9 вЂў deprecated_member_use
   info вЂў 'title' is deprecated and shouldn't be used. This is the term used in
          the 2014 version of material design. The modern term is headline6.
          This feature was deprecated after v1.13.8. вЂў
          lib/style/theme/theme.dart:42:9 вЂў deprecated_member_use
   info вЂў Unused import: 'package:osmd_admin/widgets/news_state_cards.dart' вЂў
          lib/widgets/flat_section.dart:7:8 вЂў unused_import
   info вЂў Unused import: 'package:domain/news.dart' вЂў lib/widgets/house.dart:1:8
          вЂў unused_import
   info вЂў Don't import implementation files from another package вЂў
          lib/widgets/house.dart:4:8 вЂў implementation_imports
   info вЂў Unused import: 'package:flutter/src/scheduler/ticker.dart' вЂў
          lib/widgets/house.dart:4:8 вЂў unused_import
   info вЂў Unused import: 'package:osmd_admin/widgets/news_state_cards.dart' вЂў
          lib/widgets/house.dart:13:8 вЂў unused_import
   info вЂў The value of the field '_maxHeight' isn't used вЂў
          lib/widgets/house.dart:32:10 вЂў unused_field
   info вЂў Unused import: 'package:flutter/material.dart' вЂў
          test/widget_test.dart:8:8 вЂў unused_import
   info вЂў Unused import: 'package:flutter_test/flutter_test.dart' вЂў
          test/widget_test.dart:9:8 вЂў unused_import
   info вЂў Unused import: 'package:osmd_admin/main.dart' вЂў
          test/widget_test.dart:11:8 вЂў unused_import

```

```
[✓] Flutter (Channel beta, v1.14.6, on Mac OS X 10.15.3 19D76, locale ru-UA)
    • Flutter version 1.14.6 at /Users/artemboiko/Documents/flutter
    • Framework revision fabeb2a16f (8 weeks ago), 2020-01-28 07:56:51 -0800
    • Engine revision c4229bfbba
    • Dart version 2.8.0 (build 2.8.0-dev.5.0 fc3af737c7)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/artemboiko/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Volumes/HDD/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.9.0.beta.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (3 available)
    • Android SDK built for x86 • emulator-5554 • android-x86    • Android 10
      (API 29) (emulator)
    • Chrome                    • chrome        • web-javascript • Google Chrome
      80.0.3987.149
    • Web Server                • web-server    • web-javascript • Flutter Tools
```

</details>

**Comment by VladyslavBondarenko** [comment] 2020-03-25 13:16
Hi @PavlyukovYegor 
Could you share a minimal code sample to reproduce it?
Does it happen when using the last version `beta v1.15.17`?

**Comment by PavlyukovYegor** [comment] 2020-03-25 14:30
Yes, this happens on the latest version `beta v1.15.17`

Code sample:

`import 'dart:async';

import 'package:flutter/material.dart';
import 'package:osmd_admin/generated/i18n.dart';
import 'package:osmd_admin/pages/home.dart';
import 'package:osmd_admin/resource/asset.dart';
import 'package:osmd_admin/style/indent/indent.dart';
import 'package:osmd_admin/style/theme/theme.dart';
import 'package:osmd_admin/widgets/text_field.dart';
import 'package:provider/provider.dart';
import 'package:bloc/session.dart';

class SignInPage extends StatefulWidget {
  static const String pageKey = "/sign_in";

  static Widget builder(BuildContext context) => SignInPage();

  @override
  _SignInPageState createState() => _SignInPageState();
}

class _SignInPageState extends State<SignInPage> {
  final GlobalKey<ScaffoldState> _scaffoldKey = GlobalKey<ScaffoldState>();
  final TextEditingController _emailController = TextEditingController();
  final TextEditingController _passwordController = TextEditingController();

  StreamSubscription<Object> _errorSubscription;
  StreamSubscription<Object> _navigationSubscription;

  @override
  void initState() {
    super.initState();
    final SessionBloc sessionBloc =
        Provider.of<SessionBloc>(context, listen: false);
    _errorSubscription = sessionBloc.stateStream
        .where((SessionState state) => state.hasError)
        .map((SessionState state) => state.error)
        .listen((Object error) {
      _scaffoldKey.currentState.showSnackBar(SnackBar(
        content: Text("Error occurred: $error"),
      ));
      sessionBloc.onErrorHandled();
    });
    _navigationSubscription = sessionBloc.stateStream
        .where((SessionState state) => state.isAuthenticated)
        .take(1)
        .listen((_) {
      Navigator.of(context)
          .pushReplacement(MaterialPageRoute<void>(builder: AdminPage.builder));
    });
  }

  @override
  void dispose() {
    _errorSubscription.cancel();
    _navigationSubscription.cancel();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      key: _scaffoldKey,
      body: Consumer<SessionBloc>(
        builder: (_, SessionBloc bloc, __) => StreamBuilder<SessionState>(
          initialData: bloc.currentState,
          stream: bloc.stateStream,
          builder: (BuildContext ctx, AsyncSnapshot<SessionState> state) {
            if (state.data.isUnauthenticated) {
              return _buildSignInFormPage(ctx);
            } else {
              return const Center(child: CircularProgressIndicator());
            }
          },
        ),
      ),
    );
  }

  Widget _buildSignInFormPage(BuildContext context) {
    return Center(
      child: SingleChildScrollView(
        child: Padding(
          padding: const EdgeInsets.all(20),
          child: Card(
            child: Container(
              width: 500,
              padding: const EdgeInsets.symmetric(vertical: 20),
              child:  Column(
                mainAxisAlignment: MainAxisAlignment.spaceAround,
                crossAxisAlignment: CrossAxisAlignment.center,
                children: <Widget>[
                  _buildLogo(),
                  _buildSignInForm(),
                ],
              ),
            ),
          ),
        ),
      ),
    );
  }

  Widget _buildLogo() {
    return Padding(
      padding: const EdgeInsets.symmetric(horizontal: Indent.minimal),
      child:
      Center(child: Container(height: 200, child: Image.asset(Asset.logo))),
    );
  }

  Widget _buildSignInForm() {
    final ThemeData theme = Theme.of(context);
    final S localizations = S.of(context);
    return Form(
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.center,
        mainAxisSize: MainAxisSize.min,
        children: <Widget>[
          _buildEmailField(localizations),
          _buildPasswordField(localizations),
          _buildSignInButton(theme, localizations)
        ],
      ),
    );
  }

  Widget _buildEmailField(S localizations) {
    return Padding(
      padding: const EdgeInsets.symmetric(
          vertical: Indent.minimal, horizontal: Indent.regular),
      child: ColoredTextFormField(
        controller: _emailController,
        labelText: "E-mail",
        hintText: "me@something.com",
        keyboardType: TextInputType.emailAddress,
      ),
    );
  }

  Widget _buildPasswordField(S localizations) {
    return Padding(
      padding: const EdgeInsets.symmetric(
          vertical: Indent.minimal, horizontal: Indent.regular),
      child: ColoredTextFormField(
        controller: _passwordController,
        labelText: "Password",
        hintText: "qwerty123456",
        obscureText: true,
      ),
    );
  }

  Widget _buildSignInButton(ThemeData theme, S localizations) {
    return Padding(
      padding: const EdgeInsets.only(
          top: Indent.minimal, left: Indent.regular, right: Indent.regular),
      child: SizedBox(
        width: double.infinity,
        child: RaisedButton(
          child: Padding(
            padding: Indent.all_minimal,
            child: Text("Р’С…РѕРґ",
                style: TextStyle(color: Colors.white)),
          ),
          color: secondaryColorAccentDark,
          onPressed: () => Provider.of<SessionBloc>(context, listen: false)
              .onSignIn(_emailController.text, _passwordController.text),
        ),
      ),
    );
  }
}
`

**Comment by VladyslavBondarenko** [comment] 2020-03-25 15:01
@PavlyukovYegor 
With what device/browser can you see that?
I see interface as on the first image and single cursor not only with Chrome with Android, but also with Safari on iPhone 7 (iOS 13.4)

**Comment by PavlyukovYegor** [comment] 2020-03-25 15:04
@VladyslavBondarenko Best seen on iPhone SE

**Comment by nttd-kudouyus** [comment] 2020-03-25 15:49
InternetExplorer also has the same problem（ ;  ; ）

**Comment by yjbanov** [comment] 2020-03-26 21:55
This looks like a discrepancy in text layout. /cc @mdebbar

**Comment by mdebbar** [comment] 2020-03-26 22:00
There seems to be 2 issues here:
1. Flutter's cursor isn't at the same position as the browser cursor (text layout issue).
2. Browser's cursor is visible (it should be hidden cc @nturgut).

@PavlyukovYegor regarding (1) could you try the new text layout implementation by following instructions in the description of [this issue](https://github.com/flutter/flutter/issues/33523)?

**Comment by PavlyukovYegor** [comment] 2020-03-30 09:37
@mdebbar I tried a new text layout implementation following the instructions. Added a flag during build, but the issue remained the same
![image](https://user-images.githubusercontent.com/8119719/77898016-24172400-7283-11ea-8dff-f315493be423.png)

**Comment by mdebbar** [comment] 2020-03-30 17:22
From the screenshot, it looks like issue (1) is fixed. The Flutter cursor is at the same spot as the browser cursor.

As for issue (2) I wouldn't expect it to be fixed by the new text layout implementation.

**Comment by nturgut** [comment] 2020-03-30 21:18
I tested the framework latest master, with the [flutter_gallery](https://github.com/flutter/gallery) repo. I didn't observed visible cursor.

- Chrome Desktop (not observed)
- Safari Desktop (not observed)
- Chrome on Android (not observed)
- Safari on IOS (IOS13) (not observed)

Can you please use the latest master and let us know the outcome?

**Comment by nturgut** [comment] 2020-03-30 22:03
I tested on Windows on Edge(ver. 81) and not able to reproduce 2 cursors. I assume it might be an issue with the older versions of Edge (based on EdggeHTML). I haven't tested on IE11 though.

**Comment by PavlyukovYegor** [comment] 2020-03-31 08:58
@nturgut I tried to test from the last master, the result is in the screenshot

![image](https://user-images.githubusercontent.com/8119719/78006988-5c336b00-7346-11ea-848f-b566b3f2fae6.png)

**Comment by mdebbar** [comment] 2020-03-31 17:34
@PavlyukovYegor we aren't able to reproduce this issue in the flutter gallery, so we need to try with your code. Could you please share a minimal, self-contained flutter app that works and demonstrates the issue?

**Comment by PavlyukovYegor** [comment] 2020-04-01 11:46
@mdebbar here is the repository

[https://github.com/PavlyukovYegor/flutter_issue/tree/develop](url)

**Comment by webertim** [comment] 2020-04-08 21:11
I don't know if it helps, but I have the same issue on Edge.
![flutter_2_cursors](https://user-images.githubusercontent.com/39098775/78834055-3cf3a800-79ee-11ea-8847-82b4a791709f.png)

Version information:
Microsoft Edge 42.17134.1098.0
Microsoft EdgeHTML 17.17134

**Closed** 2020-07-29 23:18 UTC
Labels: P4, a: text input, framework, platform-web

**Comment by fourman-alex** [comment] 2020-10-21 08:58
> @PavlyukovYegor we aren't able to reproduce this issue in the flutter gallery, so we need to try with your code. Could you please share a minimal, self-contained flutter app that works and demonstrates the issue?

Not sure if the issue I'm seeing is rooted at the same problem but I'll add it here.
Running on Chrome/Safari on iOS 14.0.1
<details><summary>Reproducable Code</summary>
<p>

```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(
        resizeToAvoidBottomInset: false,
        body: Center(
          child: TextField(),
        ),
      ),
    );
  }
}
```

</p>
</details>

### The bug
When selecting on iOS produces the following result:
As if the selection is positioned with some offset.
<details><summary>###Screenshot</summary>
<p>

![photo5224626642851311657](https://user-images.githubusercontent.com/5362998/96696288-45f90500-1393-11eb-9304-b98c15bff32d.jpg)

</p>
</details>

The reason this is not reproducable in the Gallery is the use of a different font.
Changing the code to be more similar to the Gallery text field no longer produces the bug (though this feels like a workaround)

<details><summary>Workaround</summary>
<p>

```
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(
        primarySwatch: Colors.blue,
        textTheme: _buildCraneTextTheme(ThemeData.light().textTheme),
      ),
      home: Scaffold(
        resizeToAvoidBottomInset: false,
        body: Center(
          child: TextField(),
        ),
      ),
    );
  }
}

TextTheme _buildCraneTextTheme(TextTheme base) {
  return GoogleFonts.ralewayTextTheme(
    base.copyWith(
      headline1: base.headline1.copyWith(
        fontWeight: FontWeight.w300,
        fontSize: 96,
      ),
      headline2: base.headline2.copyWith(
        fontWeight: FontWeight.w400,
        fontSize: 60,
      ),
      headline3: base.headline3.copyWith(
        fontWeight: FontWeight.w600,
        fontSize: 48,
      ),
      headline4: base.headline4.copyWith(
        fontWeight: FontWeight.w600,
        fontSize: 34,
      ),
      headline5: base.headline5.copyWith(
        fontWeight: FontWeight.w600,
        fontSize: 24,
      ),
      headline6: base.headline6.copyWith(
        fontWeight: FontWeight.w600,
        fontSize: 20,
      ),
      subtitle1: base.subtitle1.copyWith(
        fontWeight: FontWeight.w500,
        fontSize: 16,
        // letterSpacing: letterSpacingOrNone(0.5),
      ),
      subtitle2: base.subtitle2.copyWith(
        fontWeight: FontWeight.w600,
        fontSize: 12,
        // color: craneGrey,
      ),
      bodyText1: base.bodyText1.copyWith(
        fontWeight: FontWeight.w500,
        fontSize: 16,
      ),
      bodyText2: base.bodyText2.copyWith(
        fontWeight: FontWeight.w400,
        fontSize: 14,
      ),
      button: base.button.copyWith(
        fontWeight: FontWeight.w600,
        fontSize: 13,
        // letterSpacing: letterSpacingOrNone(0.8),
      ),
      caption: base.caption.copyWith(
        fontWeight: FontWeight.w500,
        fontSize: 12,
        // color: craneGrey,
      ),
      overline: base.overline.copyWith(
        fontWeight: FontWeight.w600,
        fontSize: 12,
      ),
    ),
  );
}
```

</p>
</details>

**Comment by cmarpert** [comment] 2020-12-12 22:19
Hi,

I'm facing the same issue on android chrome mobile.

![20201212_231447 1](https://user-images.githubusercontent.com/57644403/101996173-557c3680-3cd0-11eb-9e98-4edab6c487d0.jpg)

Here is my  setup:
Flutter 1.24.0-10.2.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision 022b333a08 (3 weeks ago) • 2020-11-18 11:35:09 -0800
Engine • revision 07c1eed46b
Tools • Dart 2.12.0 (build 2.12.0-29.10.beta)

Do I have to switch channels for it to disappear?

**Comment by Cinux-Chosan** [comment] 2021-07-23 14:47
same issue on android chrome mobile, other browsers are fine.
