### ISSUE TITLE
unable to connect to 10.0.2.2

### ISSUE THREAD

**Issue by steelx** [flutter/flutter#64931] opened 2020-08-31 05:55 UTC
Everything was working fine, until today I did `flutter upgrade`.

I have a dart backend service running at `0.0.0.0:8080` If I hit my backend API from postman it responds fine, but doesnt respond to any flutter calls, seem flutter is not making any calls at all. But when I did console log to my api client, this was flutter print, but backend didn't receive any request.

No matter which API_ENDPOINT I pass it fails everytime, but from emulator chrome I can made those requests fine.

```
I/flutter ( 6513): POST: http://10.0.2.2:8080/login
I/flutter ( 6513): error ------>>>>> Error: Password wont match!
```

Now My flutter app wont connect to my localhost server at API_ENDPOINT:
`const API_ENDPOINT = String.fromEnvironment('API_ENDPOINT', defaultValue: 'http://10.0.2.2:8080');`

When I run this locally I do not pass any env variable and hence it should pickup `10.0.2.2`.

```bash
> flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 1.22.0-2.0.pre.135, on Microsoft Windows [Version
    10.0.19041.450], locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Chrome - develop for the web
[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.5.4)
[✓] Android Studio (version 4.0)
[✓] VS Code, 64-bit edition (version 1.47.3)
[✓] Connected device (5 available)

• No issues found!

```

**Comment by pedromassangocode** [comment] 2020-08-31 10:55
Hi @steelx 
Can you please provide your `flutter doctor -v`, your `pubspec.yaml` and a minimal complete reproducible code sample?
Thank you

**Comment by steelx** [comment] 2020-08-31 11:58
> 
> 
> Hi @steelx
> Can you please provide your `flutter doctor -v`, your `pubspec.yaml` and a minimal complete reproducible code sample?
> Thank you

Thanks for responding.
The same code works fine on Mac OS.

**flutter doctor -v** :
```bash

PS C:\Users\ajink> flutter doctor -v
[✓] Flutter (Channel master, 1.22.0-2.0.pre.135, on Microsoft Windows [Version 10.0.19041.450], locale en-IN)
    • Flutter version 1.22.0-2.0.pre.135 at C:\src\flutter
    • Framework revision 8fa5c55e54 (10 hours ago), 2020-08-30 19:05:20 -0700
    • Engine revision 1e302a111d
    • Dart version 2.10.0 (build 2.10.0-76.0.dev)


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\ajink\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.5.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.5.30011.22
    • Windows 10 SDK version 10.0.18362.0

[✓] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code, 64-bit edition (version 1.47.3)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.13.1

[✓] Connected device (4 available)
    • Windows (desktop) • windows    • windows-x64    • Microsoft Windows [Version 10.0.19041.450]
    • Web Server (web)  • web-server • web-javascript • Flutter Tools
    • Chrome (web)      • chrome     • web-javascript • Google Chrome 83.0.4103.116
    • Edge (web)        • edge       • web-javascript • Microsoft Edge 84.0.522.63

• No issues found!
```

and here is the **pubspec** file:
```yml
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  rxdart: ^0.24.1
  provider: ^4.1.3
  http: ^0.12.2
  sqflite: ^1.3.1
  path_provider: ^1.6.11
  flutter_secure_storage: ^3.3.3
  fluttertoast: ^7.0.2
  flutter_svg: ^0.18.0
  common:
    path: ./common
  video_player:
  webview_flutter: ^0.3.22+1
  flutter_local_notifications: ^1.4.4+2
  shared_preferences:
  printing: 3.5.0
  pdf: 1.9.0
  numberpicker: ^1.2.1
  camera:
  path:

dev_dependencies:
  flutter_test:
    sdk: flutter

  mockito: ^4.1.1
  network_image_mock: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  assets:
     - assets/images/
     - assets/images/monthly_move_resources/
```

**Comment by pedromassangocode** [comment] 2020-08-31 13:39
Hi @steelx 
Please provide a [minimal complete reproducible code](https://stackoverflow.com/help/minimal-reproducible-example) sample that I can use to reproduce the issue?
Thank you

**Comment by felipecs81** [comment] 2020-09-01 03:00
Same happening here.

After run flutter upgrade today the http requests stopped working, they are always returning socket error.

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 1.22.0-2.0.pre.161, on Mac OS X 10.15.6 19G73, locale en-AU)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
[✓] Android Studio (version 4.0)
[✓] Connected device (2 available)

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  hive: ^1.4.3
  hive_flutter: ^0.3.1
  shared_preferences: ^0.5.8
  provider: ^4.3.1
  country_code_picker: ^1.4.0
  flutter_circular_slider: ^2.5.0
  http: ^0.12.2
  firebase_auth: ^0.16.1
  toast: ^0.1.5
  google_sign_in: ^4.5.1
  sign_in_with_apple: ^2.5.2
  flutter_facebook_login: ^3.0.0
  multi_masked_formatter: ^0.1.1
  intl: ^0.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  hive_generator: ^0.7.1
  build_runner: ^1.10.2

flutter:

  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: Bree
      fonts:
        - asset: fonts/bree_regular.ttf
    - family: Bree-Thin
      fonts:
        - asset: fonts/bree_thin.otf

Http request:

Future<dynamic> getData(String token, String url) async {
    var responseJson;
    try {
      final response = await http.get(
        url,
        headers: {
          "Authorization": token,
          "Accept": "application/json",
          "Content-Type": "application/json"
        },
      );
      responseJson = _returnResponse(response);
    } on SocketException {
      throw FetchDataException('Unable to connect to server');
    }
    return responseJson;
  }

It is throwing SocketException for all request, my app stopped to work.

Not sure what to do know to get the project working again.

Thank you.

**Comment by steelx** [comment] 2020-09-01 03:17
> Hi @steelx
> Please provide a [minimal complete reproducible code](https://stackoverflow.com/help/minimal-reproducible-example) sample that I can use to reproduce the issue?
> Thank you

its just a simple http GET call...

**Comment by pedromassangocode** [comment] 2020-09-01 08:29
Hi @steelx 
From what I can see, the issue is related to the Http package rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/dart-lang/http/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by pedromassangocode** 2020-09-01 08:29 UTC
Labels: in triage
