### ISSUE TITLE
MaterialApp home call build widget multi time.

### ISSUE THREAD

**Issue by Centny** [flutter/flutter#23063] opened 2018-10-14 03:47 UTC
i found the MaterialApp home widget call build multi time in multi case. i think it is issue.

### case 1
the official example
```.dart
import 'package:flutter/material.dart';

void main() {
  runApp(MaterialApp(
    title: 'Named Routes Demo',
    // Start the app with the "/" named route. In our case, the app will start
    // on the FirstScreen Widget
    initialRoute: "/",
    routes: {
      "/": (context) => FirstScreen(),
      // When we navigate to the "/second" route, build the SecondScreen Widget
      '/second': (context) => SecondScreen(),
    },
  ));
}

class FirstScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    print("first called");
    return Scaffold(
      appBar: AppBar(
        title: Text('First Screen'),
      ),
      body: Center(
        child: RaisedButton(
          child: Text('Launch screen'),
          onPressed: () {
            // Navigate to the second screen using a named route
            Navigator.pushNamed(context, '/second');
          },
        ),
      ),
    );
  }
}

class SecondScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    print("second called");
    return Scaffold(
      appBar: AppBar(
        title: Text("Second Screen"),
      ),
      body: Center(
        child: RaisedButton(
          onPressed: () {
            // Navigate back to the first screen by popping the current route
            // off the stack
            Navigator.pop(context);
          },
          child: Text('Go back!'),
        ),
      ),
    );
  }
}
```
the output log

```
Launching lib/main.dart on iPhone XS Max in debug mode...
Xcode build done.                                            4.4s
flutter: first called
flutter: first called
flutter: first called
```

it is ok when using home
```.dart
void main() {
  runApp(MaterialApp(
    title: 'Named Routes Demo',
    // Start the app with the "/" named route. In our case, the app will start
    // on the FirstScreen Widget
    home: FirstScreen(),
    // initialRoute: "/",
    routes: {
      // "/": (context) => FirstScreen(),
      // When we navigate to the "/second" route, build the SecondScreen Widget
      '/second': (context) => SecondScreen(),
    },
  ));
}
```

```
Launching lib/main.dart on iPhone XS Max in debug mode...
Xcode build done.                                            4.2s
flutter: first called
```

### case 2
when the home widget is stateful, it will call build every time when navigating to other router

```.dart
import 'package:flutter/material.dart';

void main() {
  runApp(MaterialApp(
    title: 'Named Routes Demo',
    // Start the app with the "/" named route. In our case, the app will start
    // on the FirstScreen Widget
    home: FirstScreen(),
    // initialRoute: "/",
    routes: {
      // "/": (context) => FirstScreen(),
      // When we navigate to the "/second" route, build the SecondScreen Widget
      '/second': (context) => SecondScreen(),
    },
  ));
}

class FirstScreen extends StatefulWidget {
  @override
  State<FirstScreen> createState() {
    return FirstScreenState();
  }
}

class FirstScreenState extends State<FirstScreen> {
  @override
  Widget build(BuildContext context) {
    print("first called");
    return Scaffold(
      appBar: AppBar(
        title: Text('First Screen'),
      ),
      body: Center(
        child: RaisedButton(
          child: Text('Launch screen'),
          onPressed: () {
            // Navigate to the second screen using a named route
            Navigator.pushNamed(context, '/second');
          },
        ),
      ),
    );
  }
}

class SecondScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    print("second called");
    return Scaffold(
      appBar: AppBar(
        title: Text("Second Screen"),
      ),
      body: Center(
        child: RaisedButton(
          onPressed: () {
            // Navigate back to the first screen by popping the current route
            // off the stack
            Navigator.pop(context);
          },
          child: Text('Go back!'),
        ),
      ),
    );
  }
}
```
the output
```
Launching lib/main.dart on iPhone XS Max in debug mode...
Xcode build done.                                            4.3s
flutter: first called
flutter: second called
flutter: first called
```

if using routes
```.dart
void main() {
  runApp(MaterialApp(
    title: 'Named Routes Demo',
    // Start the app with the "/" named route. In our case, the app will start
    // on the FirstScreen Widget
    // home: FirstScreen(),
    initialRoute: "/",
    routes: {
      "/": (context) => FirstScreen(),
      // When we navigate to the "/second" route, build the SecondScreen Widget
      '/second': (context) => SecondScreen(),
    },
  ));
}
```
the output
```
Launching lib/main.dart on iPhone XS Max in debug mode...
Xcode build done.                                            4.1s
flutter: first called
flutter: first called
flutter: first called
flutter: second called
flutter: first called
```

### flutter analyze
```
Analyzing test1...
No issues found! (ran in 0.8s)
```

### flutter doctor -v
```
[✓] Flutter (Channel beta, v0.9.4, on Mac OS X 10.13.6 17G65, locale en-CN)
    • Flutter version 0.9.4 at /Users/vty/Pkg/flutter
    • Framework revision f37c235c32 (3 weeks ago), 2018-09-25 17:45:40 -0400
    • Engine revision 74625aed32
    • Dart version 2.1.0-dev.5.0.flutter-a2eb050044

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/vty/Library/Android/sdk
    • Android NDK at /Users/vty/Library/Android/sdk/ndk-bundle
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = /Users/vty/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.0, Build version 10A255
    • ios-deploy 2.0.0
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[!] IntelliJ IDEA Community Edition (version 2018.1.6)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.28.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.19.0

[✓] Connected devices (1 available)
    • iPhone XS Max • D8A03577-F9B0-4DB3-B41D-FBB90838D81F • ios • iOS 12.0 (simulator)

! Doctor found issues in 1 category.
```

**Comment by zoechi** [comment] 2018-10-15 08:33
That's working as intended. 
`build()` can be called any time and multiple times. 
Setting https://docs.flutter.io/flutter/material/MaterialPageRoute/maintainState.html to `false` might reduce the number of `build` calls.

**Comment by Centny** [comment] 2018-10-16 02:34
@zoechi it is meaning that must using memory cache to make widget build only once.

**Comment by zoechi** [comment] 2018-10-16 07:44
@Centny sorry, but I don't really understand your last comment.
Can you please elaborate a bit more?

**Comment by Centny** [comment] 2018-10-16 07:54
@zoechi 
like this
```.dart
  @override
  Widget build(BuildContext context) {
    if (_cached == null) {
      _cached = widget.builder(context, _snapshot);
    }
    return _cached;
  }
```
It seems that everything is normal，after i add code in each stateful widget.

**Comment by zoechi** [comment] 2018-10-16 07:59
What should this code demonstrate?

**Comment by Centny** [comment] 2018-10-16 08:56
it is builder like GetFutureBuilder by custom event.

**Comment by mbpatel6245** [comment] 2019-01-13 09:54
I think if you are called print("first called"); on initstate then it's called only once.
@override
  void initState() {
    super.initState();

  }

**Comment by zoechi** [comment] 2019-01-13 12:05
Closing as working as intended. `build()` is expected to be called more than once and at various times.

**Closed by zoechi** 2019-01-13 12:05 UTC
Labels: f: routes, framework

**Comment by magnocasmor** [comment] 2019-01-18 12:24
I face the same issue in both cases. I believe thats is not normal, in my application it's like case 1 and always occurs. When set `initialRoute`, build twice or more, but when set `home`, build only once. I face case 2 too in my application, then the Stateful Widget is rebuild in each screen that I navigate.

**Comment by zoechi** [comment] 2019-01-18 13:50
@magnocasmor `build()` being called multiple times is normal.
You could return a cached instance if you know it hasn't changed.

**Comment by magnocasmor** [comment] 2019-01-18 14:00
Why set `home` call only once and set `initialRoute` call twice or thrice always?

**Comment by zoechi** [comment] 2019-01-18 14:04
@magnocasmor I don't know but I don't have any information about your application.
I'd suggest you ask on StackOverflow with code that allows to reproduce.

**Comment by magnocasmor** [comment] 2019-01-18 14:10
You can try the demo that @Centny post in this issue. In case 1, always occurs thats results

**Comment by zoechi** [comment] 2019-01-18 14:12
If you push another page, then the previous and new page are rendered (the previous behind the new one)

**Comment by hoaquo** [comment] 2019-07-02 13:29
I don't think this is normal, I have ``Home`` (tap)-> ``Screen1`` (tap)-> ``Screen 2`` (tap back), event from ``Screen1`` to ``Screen2``, the ```Home``'s build() also called? Can you explain to us why this is intention for calling ``Home``'s build() if we navigating from ``Screen 1`` to ``Screen 2``?

**Comment by mrserfr** [comment] 2019-07-02 17:42
I encounter this behavior even when I use stateless widgets. This is not described anywhere in the documentation, and I do not understand why this is happening. It looks like a bug

**Comment by ASemeniuk** [comment] 2019-08-16 07:34
I hoped you asked the **correct** question, but you didn't. Oh, boy...
The correct question is: why `initState()` is called multiple times in `StatefulWidget`? Each time I use `Navigator.pushNamed()` method, my home screen state gets recreated (the code is the same as in case2 above). Why?

**Comment by Zhogolev** [comment] 2019-10-09 05:32
Why it's closed? Where is the answer?

**Comment by ph55** [comment] 2019-12-15 15:22
Even following simple app:

```dart
import 'package:flutter/widgets.dart';

void main() {
  runApp(Home());
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    print('home....');
    return Container();
  }
}
```

Without any state or variables will build twice and produce following output:

```
Performing hot restart...
Syncing files to device iPhone 11 Pro Max...
Restarted application in 836ms.
flutter: home....
flutter: home....
```

**Comment by neutronixx** [comment] 2020-02-06 19:47
Hello, any fix to this issue?

**Comment by krishnaji-yedlapalli** [comment] 2020-02-23 06:01
Hello, Still i'm  facing this issue, is there any solution

**Comment by DigaoParceiro** [comment] 2020-02-29 21:27
I'm facing this issue as well

**Comment by DigaoParceiro** [comment] 2020-02-29 21:42
What I did to make it to solve for now

App:
```
class MyApp extends StatelessWidget {
  static Widget _appCache;

  @override
  Widget build(BuildContext context) {
    if(_appCache==null)
      _appCache = _buildApp();
    return _appCache;
  }
  
  static Widget _buildApp () ....

}
```
Main:
```
void main(){
  runApp(DoshApp());
}
```

**Comment by botty87** [comment] 2020-03-28 23:38
Same problem. Closed without a reason and a fix!
Even a simple app build twice.

> Even following simple app:
> 
> ```dart
> import 'package:flutter/widgets.dart';
> 
> void main() {
>   runApp(Home());
> }
> 
> class Home extends StatelessWidget {
>   @override
>   Widget build(BuildContext context) {
>     print('home....');
>     return Container();
>   }
> }
> ```
> 
> Without any state or variables will build twice and produce following output:
> 
> ```
> Performing hot restart...
> Syncing files to device iPhone 11 Pro Max...
> Restarted application in 836ms.
> flutter: home....
> flutter: home....
> ```
