### ISSUE TITLE
No exceptions or logs shown in flutter run on physical iOS 13 phone

### ISSUE THREAD

**Issue by stx** [flutter/flutter#41133] opened 2019-09-23 19:27 UTC
Everything is at latest update. Device is an iPhone X on iOS 13.

The only thing that ever appears is the following:

```
Launching lib/main.dart on Virgo in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: [...]
Xcode build done.                                           31.6s
Checking for advertised Dart observatories...
Checking for available port on [...]
Checking for authentication code for [...]
```

Tried `flutter clean` + `rm -rf Podfile.lock Pods/`, rebooting, etc.

Can't move to non-master Flutter channels to test due to active iOS 13/Xcode 11 build bugs.

```
[✓] Flutter (Channel master, v1.10.6-pre.33, on Mac OS X 10.14.6 18G95, locale en-US)
    • Flutter version 1.10.6-pre.33 at /Users/james/Development/flutter
    • Framework revision 961f1b746d (2 hours ago), 2019-09-23 10:09:38 -0700
    • Engine revision b875c7a5ff
    • Dart version 2.6.0 (build 2.6.0-dev.0.0 7c1821c4aa)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/james/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.0, Build version 11A420a
    • CocoaPods version 1.7.4

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 38.2.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.38.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.4.1

[✓] Connected device (1 available)
    • Virgo • b01937a10ffe8461ea409b3bd137ac0bf8ecc921 • ios • iOS 13.0

• No issues found!
```

**Comment by escamoteur** [comment] 2019-09-23 21:55
So your app works, you just don't get  debug output do I understand this right?

**Comment by stx** [comment] 2019-09-23 21:56
@escamoteur Correct.

**Comment by christopherfujino** [comment] 2019-09-23 22:02
Thanks for filing this @stx. This is related to https://github.com/flutter/flutter/issues/40448. This isn't a regression, but rather that something changed in iOS 13 that we are no longer able to read logs. I worked around this in that issue by using mDNS to discover the app observatory, but we still need to fix the lack of logs.

**Comment by stx** [comment] 2019-09-23 23:21
@christopherfujino Thanks for looking into it. The app observatory logs are nearly unusable for us because they spam frames and we're animating constantly. Effectively, this means that we don't get to do iOS debugging until this is fixed.

**Comment by IRIG** [comment] 2019-09-25 16:23
The title of this issue does not explicitly state that the problem occurs only with physical devices. In my case it happens only with physical iOS devices with iOS 13 but not with a iOS simulator with iOS 13.

**Comment by escamoteur** [comment] 2019-09-25 17:48
@stx is this correct? It only happens on a physical device?

**Comment by divan** [comment] 2019-09-25 18:56
After switching my devices to iOS 13, also hit this issue, and can confirm that logs still work with simulator (XCode beta, simulator devices running iOS 13, string from simulator About page: `Version 11.0 (SimulatorApp-912.1 SimulatorKit-570.3 CoreSimulator-681.5.1)`)

Also, just in case, if I run app from XCode, logs are shown.

<details>
<summary>My `flutter doctor` output</summary>
<pre>$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.10.6-pre.29, on Mac OS X 10.14.6 18G95, locale en-ES)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
[!] Android Studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] Android Studio (version 3.3)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.38.1)
[✓] Connected device (2 available)

! Doctor found issues in 2 categories.
</pre>
</details

**Comment by stx** [comment] 2019-09-25 19:18
@escamoteur Just tested this and can also confirm that logs work on simulator.

**Comment by RyanRamchandar** [comment] 2019-09-28 04:55
This is also blocking me. Is there a workaround? 

Sometimes verbose logs show print statements but these logs are very chatty not very useful for debugging.

**Comment by christopherfujino** [comment] 2019-09-30 16:28
@RyanRamchandar none that I know of at this time, other than using a simulator.

**Comment by lookfirst** [comment] 2019-10-01 01:27
No output from `print()`

(Adding this comment here because it was hard for me to search for. Hope it helps others.)

**Comment by lookfirst** [comment] 2019-10-01 09:12
Seeing a lot of this message in the Xcode console. Maybe related.

`[] nw_connection_receive_internal_block_invoke [C1] Receive reply failed with error "Operation canceled"`

**Comment by lookfirst** [comment] 2019-10-01 09:13
@RyanRamchandar The workaround for me right now has to been to just set breakpoints in the debugger. Kind of a pain when you just want to print something out, but shrug... it works.

**Comment by RyanRamchandar** [comment] 2019-10-02 05:48
Update: I am able to see app logs when I run from Xcode directly but not via IntelliJ or the flutter run command. The logs from Xcode include more than just flutter logs.

```
[✓] Flutter (Channel stable, v1.9.1+hotfix.4, on Mac OS X 10.14.6 18G103, locale en-CA)
    • Flutter version 1.9.1+hotfix.4 at /Users/ryan/Documents/flutter
    • Framework revision cc949a8e8b (4 days ago), 2019-09-27 15:04:59 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.0, Build version 11A420a
    • CocoaPods version 1.7.4

[✓] Connected device (1 available)
    • iPhone XS • 00008020-0019544602D8002E • ios • iOS 13.1.1

! Doctor found issues in 1 category.

```

**Comment by tarunt815** [comment] 2019-10-03 16:51
Also having the issue above. print() not appearing in vscode, but are appearing in Xcode. Any update on  a fix for this?

**Comment by malikdoksoz** [comment] 2019-10-03 19:32
> Also having the issue above. print() not appearing in vscode, but are appearing in Xcode. Any update on a fix for this?

Exactly, I have that same problem.

**Comment by wuyugege** [comment] 2019-10-08 02:06
when this issue will be fixed? @escamoteur

**Comment by escamoteur** [comment] 2019-10-08 06:00
All I can say, that the team is aware of the urgency of this and working on a solution. Sorry that I can't offer a concrete date

**Comment by lookfirst** [comment] 2019-10-08 06:26
Tag the issue as a high-priority P1?

Thanks for all your hard work.

**Comment by TharinduNM** [comment] 2019-10-08 09:55
As a quick fix, for the time being, you can follow the following steps.

Click on **More Actions** on Android studio Run tab.
![image](https://user-images.githubusercontent.com/13645690/66386169-5c7a2b80-e9df-11e9-949b-4f85878fcb26.png)

Click on **Open Observatory**.
Click on see **debug** on right-hand side of the opened Observatory.
![image](https://user-images.githubusercontent.com/13645690/66386339-a8c56b80-e9df-11e9-8498-32f42cb78cac.png)


You can see the logs there. 
You still can do hot reload from Android studio and meantime see the logs from the observatory.

**Comment by lukepighetti** [comment] 2019-10-09 16:28
Also having this issue on physical device on iOS 13.

**Comment by lukepighetti** [comment] 2019-10-09 16:31
Anyone have an idea what the cause is? Is anyone currently working on a PR for this?

**Comment by christopherfujino** [comment] 2019-10-09 16:34
I have this queued up next. From the fact that logs are visible in the observatory, I'm guessing this is a problem with idevicesyslog, which is a libimobiledevice tool.

**Comment by team-ant** [comment] 2019-10-13 09:53
> As a quick fix, for the time being, you can follow the following steps.
> 
> Click on **More Actions** on Android studio Run tab.
> ![image](https://user-images.githubusercontent.com/13645690/66386169-5c7a2b80-e9df-11e9-949b-4f85878fcb26.png)
> 
> Click on **Open Observatory**.
> Click on see **debug** on right-hand side of the opened Observatory.
> ![image](https://user-images.githubusercontent.com/13645690/66386339-a8c56b80-e9df-11e9-8498-32f42cb78cac.png)
> 
> You can see the logs there.
> You still can do hot reload from Android studio and meantime see the logs from the observatory.

Thanks! 

For those who are using VS code, you can do
View -> Command Palette -> Dart: Open Observatory

You have then get the same page.

**Comment by jmagman** [comment] 2019-10-21 21:24
Flutter is using libimobiledevice to grab device logs, but it doesn't support unified logging (os_log), which is the only non-deprecated iOS logging API.
 https://github.com/libimobiledevice/libimobiledevice/issues/733

I don't see a command line tool that can scrape those kinds of logs from the device.  I can only see it in a GUI in Console and Configurator.

**Comment by digarahayu** [comment] 2019-10-23 10:38
Same issue i hope that cant be fix as soon as possible. cause log really important thing

**Comment by christopherfujino** [comment] 2019-10-23 16:28
@digarahayu we are working on a fix...in the meantime you can either use a simulator or attach an observatory to see logs, please see comments above.

**Comment by jmagman** [comment] 2019-10-23 20:22
Stealing this since I've been investigating a fix.  It's tricky because there's no (publicly exposed) way to get live unified logs off a device from the host's command line.  I'm investigating getting logs directly from the VM service, which is a start, but probably won't work for picking up crash backtraces.

You can see live logs in Console, Xcode, Configurator, or the observatory, or after the fact from a sysdiagnose.

**Comment by bardram** [comment] 2019-10-25 14:52
I'm also experiencing this issue in IntelliJ. However, in contrast to comments above, I'm also experiencing problems when I run my app in **Xcode**. Basically, after a few lines being printed, it writes:

```
Swift: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 5.994211e-05, 4.7150796e-05, -0.0010471394, 0.000605365, 0.00058622187, -0.001310105, 0.00072336785, 0.0017543962, 0.005778763, 0.0061493237, 0.005587057, 0.001201549, -0.0047287, -0.009116093, -0.01141525, -0.011034533, -0.009562274, -0.0054757376, -0.0030476877, -0.001019987, 0.00040858824, 
```

and starts printing a **LOT** of data like this.... And no more debug/print() info is printed.

**Comment by kekedaine** [comment] 2019-10-25 17:56
This is an important bug, but the flutter team fixes it too slowly.

**Comment by jmagman** [comment] 2019-10-25 18:01
We're working on it.  See my comment for why this is non-trivial: https://github.com/flutter/flutter/issues/41133#issuecomment-545619696.  There is no publicly exposed way to get unified logs off a device from an attached Mac host.

Also testing to avoid regressing pre-iOS 13 devices or any other platform (mostly concerned about double-logging).  In the meantime you can see live logs in Console, Xcode, Configurator, or the observatory, or after the fact from a sysdiagnose.

**Comment by lookfirst** [comment] 2019-10-26 05:49
> There is no publicly exposed way to get unified logs off a device from an attached Mac host from the command line.

Have you filed a radar bug with Apple? Seems like it is in their best interest to provide something like this for development. Of course, we know yea... yea... apple... but still can't hurt to try.

**Comment by johnyK** [comment] 2019-10-27 10:59
same problem here...

**Comment by telinx** [comment] 2019-10-29 10:07
experiencing same problem

**Comment by ldemyanenko** [comment] 2019-10-29 17:01
Same issue. No logs in output when launching on iOS device

**Comment by jmagman** [comment] 2019-10-29 17:31
If you are experiencing this issue (everyone on iOS 13+ is) you can 👍 the issue.  "Me too" comments just add noise.  Thanks!

**Comment by lordmacu** [comment] 2019-10-31 15:25
i cant show logs, i think logs is very important for development, please fix this, thanks.

**Comment by lidroider** [comment] 2019-10-31 15:57
me too, i can't show any log

**Comment by christopherfujino** [comment] 2019-10-31 16:28
@lordmacu & @lidroider please add a :+1: to the original post rather than simply adding that you are also experiencing this. :+1:'s are used for prioritization, while "me too" comments only make the thread noisier and bury the workarounds. Thanks!

**Comment by ferdiamg** [comment] 2019-10-31 23:20
What I don't get, is that it worked until yesterday. I was happily printing logs and updated exactly nothing and whoops, this issue occured.

Flutter doctors runs fine, no issues found!

- iOS 13.1.2 on iPhone X
- Xcode Version 11.1 (11A1027)
- v1.9.1+hotfix.6

**Comment by vagrantrobbie** [comment] 2019-10-31 23:24
Did you update to iOS13 yesterday?

**Comment by ferdiamg** [comment] 2019-11-01 00:33
> Did you update to iOS13 yesterday?

Nope! No updates, I've been on iOS 13.1.2 for like 2 weeks now.

**Comment by vagrantrobbie** [comment] 2019-11-01 00:37
maybe time to start rolling back flutter versions?

Maybe to `v1.9.1`

**Comment by ferdiamg** [comment] 2019-11-01 00:41
> maybe time to start rolling back flutter versions?
> 
> Maybe to `v1.9.1`

You think that would fix my print()/log issues? Because if iOS13 is the issue here, then this problem should still occur right?

**Comment by vagrantrobbie** [comment] 2019-11-01 00:47
> I am not sure if this is really iOS 13 related

Just wondering out loud if possibly rolling back flutter versions may do something.

I know that I realised it straight after upgrading to iOS13 on my physical iPhone and iPad and the logs no longer printed. I have a iPhone6+ still running iOS12 that has the same app, running the same same flutter version (v1.9.1+hotfix.6) and the log are printing fine

**Closed** 2019-11-01 21:37 UTC
Labels: a: debugging, tool, ⌺‬ platform-ios

**Comment by jmagman** [comment] 2019-11-01 23:09
Fix at https://github.com/flutter/flutter/pull/43915.  It will take awhile for this to propagate to the [stable channel](https://github.com/flutter/flutter/wiki/Flutter-build-release-channels).

Until it does, you can see iOS 13+ live logs in Console, Xcode, Configurator, observatory debug logs, or after the fact from a sysdiagnose.

**Comment by quetool** [comment] 2019-11-05 17:29
Hi @jmagman, is there a way to log something (maybe with some plugin) while we wait this to propagate to stable channel?

**Comment by jmagman** [comment] 2019-11-05 18:31
> Hi @jmagman, is there a way to log something (maybe with some plugin) while we wait this to propagate to stable channel?

Not that I'm aware of.  If Console, Xcode, Configurator, and the observatory debug logs aren't enough, you can `git cherry-pick` https://github.com/flutter/flutter/commit/2e7d9130b2099549cdb9c47ff57e42d37c69029b onto the stable branch.  Please don't try this if you aren't familiar with git.  In other words, if you try this, you've voided your upgrade warranty: please don't file issues since it's not officially supported.

**Comment by quetool** [comment] 2019-11-05 18:46
@jmagman Thanks! Do you know how long it will take to have this fix on stable channel?

**Comment by jmagman** [comment] 2019-11-05 22:09
There should be a dev release soon (days?), and that will propagate through the beta and eventually stable channels.  I don't have an exact timeline on that.
https://github.com/flutter/flutter/wiki/Release-process
https://github.com/flutter/flutter/wiki/Flutter-build-release-channels#will-a-particular-bug-fix-be-provided-in-a-hotfix-release

**Comment by christopherfujino** [comment] 2019-11-07 21:50
This change was just published to dev in version 1.10.15.

**Comment by stx** [comment] 2019-11-08 22:41
I'm not seeing pre-runApp() exceptions printed to log in VSCode or `flutter run`, so this is still hugely problematic.

Reproduce:
```
void main() {
  print('pre-exception');
  throw Exception('this is a test here!');
  print('post-exception');

  runApp(MyApp());
}
```

```
[✓] Flutter (Channel master, v1.10.16-pre.98, on Mac OS X 10.15.1 19B88, locale en-US)
    • Flutter version 1.10.16-pre.98 at /Users/james/Development/flutter
    • Framework revision 03ac37af08 (2 hours ago), 2019-11-08 12:47:26 -0800
    • Engine revision 5f5713e339
    • Dart version 2.7.0

 
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/james/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2, Build version 11B52
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 38.2.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.40.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.6.0

[✓] Connected device (1 available)
    • Virgo • 00008030-000848D11EF0802E • ios • iOS 13.2.2

! Doctor found issues in 1 category.
```

**Comment by christopherfujino** [comment] 2019-11-11 19:22
@stx yes, could you file a new issue for that?

**Comment by stx** [comment] 2019-11-12 15:44
@christopherfujino I'm not seeing logs shown on iOS devices on first build, only on hot restart:

```
➜  testproject flutter run       
Launching lib/main.dart on Virgo in debug mode...
Running Xcode build...                                                  
 ├─Assembling Flutter resources...                           7.3s
 └─Compiling, linking and signing...                         7.2s
Xcode build done.                                           15.9s
Installing and launching...                                        24.7s
Syncing files to device Virgo...                                        
 4,509ms (!)                                       

🔥  To hot reload changes while running, press "r". To hot restart (and rebuild state), press "R".
An Observatory debugger and profiler on Virgo is available at: http://127.0.0.1:1033/uK9tw0PQzw8=/
For a more detailed help message, press "h". To detach, press "d"; to quit, press "q".

Performing hot restart...                                              ⣻flutter: here's a message
flutter: here's a second message
        
Restarted application in 966ms.
```

Reproduce:

```
void main() {
  print("here's a message");
  print("here's a second message");
  runApp(MyApp());
}
```

**Comment by christopherfujino** [comment] 2019-11-13 00:41
@stx isn't your reproduction the same as https://github.com/flutter/flutter/issues/44717?

**Comment by stx** [comment] 2019-11-13 00:48
@christopherfujino Yeah, it's the same issue. I created it after posting it here, because both it and #44718 seem to be new, resulting from the fix from this issue.

**Comment by christopherfujino** [comment] 2019-11-13 00:49
Sorry, I just caught up with all this, I can see you filed two issues, one for exceptions one for logs:

https://github.com/flutter/flutter/issues/44717
https://github.com/flutter/flutter/issues/44718

**Comment by stx** [comment] 2019-11-13 00:52
The issues seem to be slightly different in nature:

#44717 - exceptions before runApp seem to never print, period.
#44718 - logs before runApp DO print, but only on hot restart, never on first build.

**Comment by christopherfujino** [comment] 2019-11-13 00:53
Understood.

**Comment by joaowd** [comment] 2019-11-13 13:55
I'm having the same issue, print() not working

**Comment by christopherfujino** [comment] 2019-11-14 00:18
@joaowd this has been fixed on version 1.10.15. You can get the fix by switching to the dev channel. This will be in the next stable release of flutter.

**Comment by andrea689** [comment] 2019-11-19 15:45
This logger works:

```dart
import 'dart:developer' as logger;

logger.log();
```

**Comment by quetool** [comment] 2019-11-19 17:24
> This logger works:
> 
> ```dart
> import 'dart:developer' as logger;
> 
> logger.log();
> ```

Can confirm! That´s nice!

**Comment by vagrantrobbie** [comment] 2019-11-19 23:22
why does  
```
import 'dart:developer' as logger;

logger.log();
```

work but not `print()`. Can anyone explain?

**Comment by DanTup** [comment] 2019-12-01 20:03
@vagrantrobbie output from `print()` is written to the apps `stdout` stream and read via the devices logs (which is what is failing here). `dart:developer` is instead sent as messages over the VM service (this is the service that the IDE connects to in order to communiticate with the VM - for example to control debugging). The IDEs need to have specific handling for these messages (added [fairly recently](https://dartcode.org/releases/v3-3/#debugger-changes) in the VS Code extension).

**Comment by lgArlequin** [comment] 2019-12-02 12:08
It is already working on the dev channel

**Comment by jerryhamby** [comment] 2019-12-15 22:23
Same problem here (more info);

I have 2 iPhones (iPhone 7 and 11) 
iPhone 7 (13.3) this device works with the debug window
iPhone 11 (13.3) this device does not work with the debug window
Flutter: 1.12.13+hotfix.5. this is sable release

Wants happening with iPhone 11 ???

**Comment by cnjeffliu** [comment] 2019-12-26 01:50
I had met the same problem, but I worked in Windows.I just upgrade my flutter sdk without anything else.

**Comment by SmallBlackBeans** [comment] 2020-05-06 05:08
is it solved?  it happens again in 1.12.13+hotfix9...

**Comment by SmallBlackBeans** [comment] 2020-05-06 11:51
> een fixed on version 1.10.15. You can get the fix by switching to the dev channel. This will be in the next stable release of flutter.

is it solved? it happens again in 1.12.13+hotfix9...

**Comment by SmallBlackBeans** [comment] 2020-05-06 11:52
> @joaowd this has been fixed on version 1.10.15. You can get the fix by switching to the dev channel. This will be in the next stable release of flutter.

@joaowd is it solved? it happens again in 1.12.13+hotfix9...

**Comment by joaowd** [comment] 2020-05-06 11:54
> > @joaowd this has been fixed on version 1.10.15. You can get the fix by switching to the dev channel. This will be in the next stable release of flutter.
> 
> @joaowd is it solved? it happens again in 1.12.13+hotfix9...

Yes!

**Comment by kafkalxh** [comment] 2020-05-07 08:36
> Same problem here (more info);
> 
> I have 2 iPhones (iPhone 7 and 11)
> iPhone 7 (13.3) this device works with the debug window
> iPhone 11 (13.3) this device does not work with the debug window
> Flutter: 1.12.13+hotfix.5. this is sable release
> 
> Wants happening with iPhone 11 ???

I have met the same question.
iPhone 11 pro max could't work.

**Comment by lookfirst** [comment] 2020-05-14 03:22
working with `v1.17.1`

**Comment by cihadturhan** [comment] 2020-05-17 03:56
**NOT** working with v1.17.1
`iPhone XR 13.4.1`
And, execution doesn't stop at breakpoints on first run. It works after I do a refresh.

**Comment by lookfirst** [comment] 2020-05-17 05:53
Working for me. iPhone 11 13.4.1. 🤷

**Comment by thenexus00** [comment] 2020-05-18 04:27
I recently upgrade to the latest on the production branch and it is not working for me either now.

logger.log() does nothing as well.

**Comment by ZhuBoao** [comment] 2020-05-25 15:53
Mine is not working 
(Channel stable, v1.17.1, on Mac OS X 10.15.4 19E2269)
(Physical iOS 13 device, iPhone X)

**Comment by brizaldi** [comment] 2020-05-26 07:46
using latest master branch and still not working

[✓] Flutter (Channel master, 1.19.0-2.0.pre.143, on Mac OS X 10.15.4 19E287, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
[✓] Android Studio (version 3.6)

tested on iPhone 6S iOS version 13.3.1

**Comment by thenexus00** [comment] 2020-06-05 06:37
The only way it shows up is if you run the Debug tool rather then going "flutter run" in Visual Studio Code

**Comment by i-schuetz** [comment] 2020-07-04 16:41
I'm using `1.17.5` and also don't see any plugin outputs from Swift (using `print` or `NSLog`) when starting the app from Flutter. Neither in the debug console in VSCode, in the console app or in Xcode. I see them if I run the iOS example app in Xcode. I'm using the simulator.

**Comment by papmodern** [comment] 2020-07-28 08:01
This is one of the biggest flaws of dart/flutter. Always I have to use dart devtools to see the console outputs. Also I'm heavily using generators and I have to use terminal to see the build-runner exceptions!!!

P.S I'm a windows user

**Comment by owenkealey** [comment] 2020-08-09 23:44
can we please fix this

**Comment by jmagman** [comment] 2020-08-10 16:14
This is a closed issue.  If you are seeing a problem, please file a new GitHub issue and completely fill out the template so we know what version you're on and can investigate or duplicate to an open issue.  Sometimes we investigate this complaint and the app isn't even running when people think it is due to a crash on launch.

There are already several open issues tracking various manifestations of this like https://github.com/flutter/flutter/issues/44717 and https://github.com/flutter/flutter/issues/44718.

**Comment by jmagman** [comment] 2020-09-23 01:23
This should be fixed as of https://github.com/flutter/flutter/pull/66399.
