### ISSUE TITLE
Unable to connect to Chrome debug port: 37095

### ISSUE THREAD

**Issue by mictadlo** [flutter/flutter#90265] opened 2021-09-17 12:06 UTC
I installed Flutter and VS Code in the following way:

```
$ sudo snap install --classic code
$ sudo snap install --classic flutter 
$ tail -n 1 ~/.bashrc
export CHROME_EXECUTABLE="/usr/bin/chromium"
```

```
$ flutter doctor -v
[✓] Flutter (Channel stable, 2.2.1, on Linux, locale en_AU.UTF-8)
    • Flutter version 2.2.1 at /home/debian/snap/flutter/common/flutter
    • Framework revision 02c026b03c (4 months ago), 2021-05-27 12:24:44 -0700
    • Engine revision 0fdb562ac8
    • Dart version 2.13.1

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /usr/bin/chromium

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Chromium 90.0.4430.212 built on Debian 11.0, running on Debian 11.0

! Doctor found issues in 2 categories.
```
I can start the Flutter app in terminal.

[![enter image description here][1]][1]

However, under VS code I get `Unable to connect to Chrome debug port: 37095`

[![enter image description here][2]][2]

What did I miss?

  [1]: https://i.stack.imgur.com/ZEPxp.png
  [2]: https://i.stack.imgur.com/kEZa8.png

**Comment by TahaTesser** [comment] 2021-09-17 13:11
Hi @mictadlo 
I can't reproduce it on the latest Flutter `stable` channel. 

Can you please upgrade to the latest  `stable` and try again
Execute the following commands to upgrade
`flutter channel stable`
`flutter upgrade --force`
`flutter doctor -v`


Also, make sure your Flutter VS Code is up to date

**Comment by mictadlo** [comment] 2021-09-17 15:33
Hi @TahaTesser ,
I execucted all the commands but the  problem still remained.

```
$ flutter channel stable
Switching to flutter channel 'stable'...
git: From https://github.com/flutter/flutter
git:  + 02c026b03c...4cc385b4b8 stable                  -> origin/stable  (forced update)
git:  + b22742018b...400608f101 beta                    -> origin/beta  (forced update)
git:  + f9c825981c...f2903d3da5 dev                     -> origin/dev  (forced update)
git:  * [new branch]            dnfield-patch-1         -> origin/dnfield-patch-1
git:  + 42c3e45fb7...1e436a4460 experimental_skshaper   -> origin/experimental_skshaper  (forced update)
git:    02c026b03c..07d2f6f4b1  flutter-2.2-candidate.10 -> origin/flutter-2.2-candidate.10
git:  * [new branch]            flutter-2.3-candidate.19 -> origin/flutter-2.3-candidate.19
git:  * [new branch]            flutter-2.3-candidate.20 -> origin/flutter-2.3-candidate.20
git:  * [new branch]            flutter-2.3-candidate.21 -> origin/flutter-2.3-candidate.21
git:  * [new branch]            flutter-2.3-candidate.22 -> origin/flutter-2.3-candidate.22
git:  * [new branch]            flutter-2.3-candidate.23 -> origin/flutter-2.3-candidate.23
git:  * [new branch]            flutter-2.3-candidate.24 -> origin/flutter-2.3-candidate.24
git:  * [new branch]            flutter-2.3-candidate.25 -> origin/flutter-2.3-candidate.25
git:  * [new branch]            flutter-2.3-candidate.26 -> origin/flutter-2.3-candidate.26
git:  * [new branch]            flutter-2.3-candidate.27 -> origin/flutter-2.3-candidate.27
git:  * [new branch]            flutter-2.3-candidate.28 -> origin/flutter-2.3-candidate.28
git:  * [new branch]            flutter-2.4-candidate.0 -> origin/flutter-2.4-candidate.0
git:  * [new branch]            flutter-2.4-candidate.1 -> origin/flutter-2.4-candidate.1
git:  * [new branch]            flutter-2.4-candidate.2 -> origin/flutter-2.4-candidate.2
git:  * [new branch]            flutter-2.4-candidate.3 -> origin/flutter-2.4-candidate.3
git:  * [new branch]            flutter-2.4-candidate.4 -> origin/flutter-2.4-candidate.4
git:  * [new branch]            flutter-2.4-candidate.5 -> origin/flutter-2.4-candidate.5
git:  * [new branch]            flutter-2.4-candidate.6 -> origin/flutter-2.4-candidate.6
git:  * [new branch]            flutter-2.4-candidate.7 -> origin/flutter-2.4-candidate.7
git:  * [new branch]            flutter-2.4-candidate.8 -> origin/flutter-2.4-candidate.8
git:  * [new branch]            flutter-2.5-candidate.0 -> origin/flutter-2.5-candidate.0
git:  * [new branch]            flutter-2.5-candidate.1 -> origin/flutter-2.5-candidate.1
git:  * [new branch]            flutter-2.5-candidate.2 -> origin/flutter-2.5-candidate.2
git:  * [new branch]            flutter-2.5-candidate.3 -> origin/flutter-2.5-candidate.3
git:  * [new branch]            flutter-2.5-candidate.4 -> origin/flutter-2.5-candidate.4
git:  * [new branch]            flutter-2.5-candidate.5 -> origin/flutter-2.5-candidate.5
git:  * [new branch]            flutter-2.5-candidate.6 -> origin/flutter-2.5-candidate.6
git:  * [new branch]            flutter-2.5-candidate.7 -> origin/flutter-2.5-candidate.7
git:  * [new branch]            flutter-2.5-candidate.8 -> origin/flutter-2.5-candidate.8
git:  * [new branch]            flutter-2.5-candidate.9 -> origin/flutter-2.5-candidate.9
git:  * [new branch]            flutter-2.6-candidate.0 -> origin/flutter-2.6-candidate.0
git:  * [new branch]            flutter-2.6-candidate.1 -> origin/flutter-2.6-candidate.1
git:  * [new branch]            flutter-2.6-candidate.10 -> origin/flutter-2.6-candidate.10
git:  * [new branch]            flutter-2.6-candidate.2 -> origin/flutter-2.6-candidate.2
git:  * [new branch]            flutter-2.6-candidate.3 -> origin/flutter-2.6-candidate.3
git:  * [new branch]            flutter-2.6-candidate.4 -> origin/flutter-2.6-candidate.4
git:  * [new branch]            flutter-2.6-candidate.5 -> origin/flutter-2.6-candidate.5
git:  * [new branch]            flutter-2.6-candidate.6 -> origin/flutter-2.6-candidate.6
git:  * [new branch]            flutter-2.6-candidate.7 -> origin/flutter-2.6-candidate.7
git:  * [new branch]            flutter-2.6-candidate.8 -> origin/flutter-2.6-candidate.8
git:  * [new branch]            flutter-2.6-candidate.9 -> origin/flutter-2.6-candidate.9
git:    58ac7b85d9..a8a27635a1  master                  -> origin/master
git:  * [new branch]            pull-87493              -> origin/pull-87493
git:  * [new branch]            revert-81813-ExpansionPanelList_elevation -> origin/revert-81813-ExpansionPanelList_elevation
git:  * [new branch]            revert-82570-patch-1    -> origin/revert-82570-patch-1
git:  * [new branch]            revert-84342-flutter-engine-flutter-autoroll-a31192cf-636b-427f-821f-ace70b4be488-1623321347 -> origin/revert-84342-flutter-engine-flutter-autoroll-a31192cf-636b-427f-821f-ace70b4be488-1623321347
git:  * [new branch]            revert-86171-revert-83924-textTheme -> origin/revert-86171-revert-83924-textTheme
git:  * [new branch]            revert-86198-deprecate_appbar_backwards_compatibility_flag -> origin/revert-86198-deprecate_appbar_backwards_compatibility_flag
git:  * [new branch]            revert-89885-scrollVelocity -> origin/revert-89885-scrollVelocity
git:  * [new branch]            revert-skia-to-82d4c12d -> origin/revert-skia-to-82d4c12d
git:  * [new branch]            test                    -> origin/test
git:  * [new branch]            test2                   -> origin/test2
git:  * [new branch]            timsneath-accent-deprecations -> origin/timsneath-accent-deprecations
git:  * [new branch]            zanderso-patch-1        -> origin/zanderso-patch-1
git:  * [new tag]               2.3.0-16.0.pre          -> 2.3.0-16.0.pre
git:  * [new tag]               2.3.0-24.1.pre          -> 2.3.0-24.1.pre
git:  * [new tag]               2.4.0-0.0.pre           -> 2.4.0-0.0.pre
git:  * [new tag]               2.4.0-4.0.pre           -> 2.4.0-4.0.pre
git:  * [new tag]               2.4.0-4.2.pre           -> 2.4.0-4.2.pre
git:  * [new tag]               2.5.0                   -> 2.5.0
git:  * [new tag]               2.5.0-1.0.pre           -> 2.5.0-1.0.pre
git:  * [new tag]               2.5.0-5.0.pre           -> 2.5.0-5.0.pre
git:  * [new tag]               2.5.0-5.1.pre           -> 2.5.0-5.1.pre
git:  * [new tag]               2.5.0-5.2.pre           -> 2.5.0-5.2.pre
git:  * [new tag]               2.5.0-5.3.pre           -> 2.5.0-5.3.pre
git:  * [new tag]               2.5.0-6.0.pre           -> 2.5.0-6.0.pre
git:  * [new tag]               2.6.0-0.0.pre           -> 2.6.0-0.0.pre
git:  * [new tag]               2.6.0-5.1.pre           -> 2.6.0-5.1.pre
git:  * [new tag]               2.6.0-5.2.pre           -> 2.6.0-5.2.pre
git:  * [new tag]               2.2.2                   -> 2.2.2
git:  * [new tag]               2.2.3                   -> 2.2.3
git:  * [new tag]               2.3.0-24.0.pre          -> 2.3.0-24.0.pre
git:  * [new tag]               2.4.0-4.1.pre           -> 2.4.0-4.1.pre
git:  * [new tag]               2.6.0-5.0.pre           -> 2.6.0-5.0.pre
git: Already on 'stable'
git: Your branch and 'origin/stable' have diverged,
git: and have 13 and 1846 different commits each, respectively.
git:   (use "git pull" to merge the remote branch into yours)
Successfully switched to flutter channel 'stable'.
To ensure that you're on the latest build from this channel, run 'flutter upgrade'
(base) debian@appdev:/mnt/OneTB/projects/flutter/testapp$ flutter upgrade --force
Upgrading Flutter to 2.5.0 from 2.2.1 in /home/debian/snap/flutter/common/flutter...
Downloading Dart SDK from Flutter engine f0826da7ef2d301eb8f4ead91aaf026aa2b52881...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0  221M    0  6971    0     0   8846      0  7:17:20 --:--:--  7:17:20  8835
  4  221M    4 10.2M    0     0  5044k      0  0:00:44  0:00:02  0:00:42 5044k
 14  221M   14 32.2M    0     0  10.6M      0  0:00:20  0:00:03  0:00:17 10.6M
 28  221M   28 64.1M    0     0  16.0M      0  0:00:13  0:00:03  0:00:10 16.0M
 43  221M   43 96.0M    0     0  19.5M      0  0:00:11  0:00:04  0:00:07 19.5M
 47  221M   47  104M    0     0  17.7M      0  0:00:12  0:00:05  0:00:07 20.5M
 68  221M   68  152M    0     0  21.7M      0  0:00:10  0:00:07  0:00:03 28.9M
 83  221M   83  184M    0     0  23.7M      0  0:00:09  0:00:07  0:00:02 32.1M
100  221M  100  221M    0     0  27.0M      0  0:00:08  0:00:08 --:--:-- 37.4M
Building flutter tool...

Upgrading engine...
Downloading android-arm-profile/linux-x64 tools...               1,522ms
Downloading android-arm-release/linux-x64 tools...               1,030ms
Downloading android-arm64-profile/linux-x64 tools...             1,015ms
Downloading android-arm64-release/linux-x64 tools...               359ms
Downloading android-x64-profile/linux-x64 tools...                 882ms
Downloading android-x64-release/linux-x64 tools...                 839ms
Downloading android-x86 tools...                                 1,576ms
Downloading android-x64 tools...                                 2,247ms
Downloading android-arm tools...                                 1,278ms
Downloading android-arm-profile tools...                           538ms
Downloading android-arm-release tools...                           412ms
Downloading android-arm64 tools...                                 820ms
Downloading android-arm64-profile tools...                         568ms
Downloading android-arm64-release tools...                         492ms
Downloading android-x64-profile tools...                           564ms
Downloading android-x64-release tools...                           467ms
Downloading android-x86-jit-release tools...                       631ms
Downloading Web SDK...                                           2,843ms
Downloading package sky_engine...                                  321ms
Downloading flutter_patched_sdk tools...                           457ms
Downloading flutter_patched_sdk_product tools...                   424ms
Downloading linux-x64 tools...                                   2,146ms
Downloading linux-x64/font-subset tools...                         309ms

Flutter 2.5.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 4cc385b4b8 (9 days ago) • 2021-09-07 23:01:49 -0700
Engine • revision f0826da7ef
Tools • Dart 2.14.0

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.5.0, on Debian GNU/Linux 11 (bullseye) 5.10.0-8-amd64, locale en_AU.UTF-8)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✓] Chrome - develop for the web
[!] Android Studio (not installed)
[✓] VS Code
[✓] Connected device (1 available)

! Doctor found issues in 2 categories.

$ flutter doctor -v
[✓] Flutter (Channel stable, 2.5.0, on Debian GNU/Linux 11 (bullseye) 5.10.0-8-amd64, locale en_AU.UTF-8)
    • Flutter version 2.5.0 at /home/debian/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cc385b4b8 (9 days ago), 2021-09-07 23:01:49 -0700
    • Engine revision f0826da7ef
    • Dart version 2.14.0

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /usr/bin/chromium

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] VS Code
    • VS Code at /snap/code/current
    • Flutter extension version 3.26.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Chromium 90.0.4430.212 built on Debian 11.0, running on Debian 11.0

! Doctor found issues in 2 categories.
```

![image](https://user-images.githubusercontent.com/588297/133812073-7d9f3658-2aa6-4ca2-8629-64c5901cf076.png)

What did I miss?

**Comment by mictadlo** [comment] 2021-09-17 15:36
P.S. I use Flutter v3.26.0 for VS code.

**Comment by TahaTesser** [comment] 2021-09-20 07:13
HI @mictadlo 
This might a bug with just VS Code. Do you mind giving Android Studio plugin try? Also from CLI, `flutter run -d chrome`?
Thank you

**Comment by mictadlo** [comment] 2021-09-20 07:55
Hi @TahaTesser,
It works with `flutter run -d chrome` and I opened an issue on VS Code https://github.com/microsoft/vscode/issues/133428

![image](https://user-images.githubusercontent.com/588297/133970794-e89a00cd-08e1-43ab-b3a4-5cc9c0f0c8b6.png)

**Comment by TahaTesser** [comment] 2021-09-20 08:21
Hi @mictadlo 
Thanks for reporting it at Dart Code

Given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you

**Closed by TahaTesser** 2021-09-20 08:21 UTC
Labels: in triage

**Comment by mictadlo** [comment] 2021-09-20 08:59
Could we please open it again because on the Dart - Code it looks like it was solved?

**Comment by DanTup** [comment] 2021-09-20 09:12
I responded at https://github.com/Dart-Code/Dart-Code/issues/3568#issuecomment-922752858, although I don't think it's a Dart-Code issue - I think it might either be a proxy issue or Snap-related. There's an open issue that seems similar here:

https://github.com/flutter/flutter/issues/73743

There are comments there suggesting mixing Snap and non-Snap installs of VS Code/Flutter/Chromium might cause issues, eg. [this comment](https://github.com/flutter/flutter/issues/73743#issuecomment-836642774) says using Snap for all works, and [this comment](https://github.com/flutter/flutter/issues/73743#issuecomment-856438379) says using non-Snap for all works.

I'm not familiar enough with Snap to understand why mixing Snap/non-Snap apps may have issues, but it's worth trying to see if that resolves the problem.

**Comment by TahaTesser** [comment] 2021-09-20 12:28
@mictadlo 
To be sure, can you please try [manual installation ](https://flutter.dev/docs/get-started/install/linux#install-flutter-manually)and remove the snap installation

`snap remove --purge flutter`
`rm -rf ~/snap/flutter`

**Comment by mictadlo** [comment] 2021-09-20 20:48
It works now after I did:

```
sudo apt remove chromium
sudo snap install --classic chromium
$ tail -n 1 ~/.bashrc
export CHROME_EXECUTABLE="/snap/bin/chromium"
```
```
(base) debian@appdev:/mnt/OneTB/projects/flutter/testapp$ echo $HTTP_PROXY

(base) debian@appdev:/mnt/OneTB/projects/flutter/testapp$ echo $NO_PROXY

(base) debian@appdev:/mnt/OneTB/projects/flutter/testapp$
```

Now is Flutter, VS Code and Chromium from Snap. Is it better to have everything from Snap or from deb?

Thank you in advance,

Michal

**Comment by DanTup** [comment] 2021-09-21 08:35
Glad to hear!


>  Is it better to have everything from Snap or from deb?

I don't know enough about Snap to know the answer to this, but I think as long as you're consistent and things seem to be working, there's probably not much difference.
