### ISSUE TITLE
MouseRegion - pointer events' localPosition is really the global position

### ISSUE THREAD

**Issue by mtcliatt** [flutter/flutter#40072] opened 2019-09-09 06:00 UTC
After PR #32192, MouseRegion's Pointer*Event's (for example PointerHoverEvent, PointerEnterEvent) have a localPosition field, but the field's value is the global position rather than the local position.

Could you please add the customer: octopod tag?

```
Flutter 1.8.5-pre.86 • channel unknown • unknown source
Framework • revision f1ea485018 (4 weeks ago) • 2019-08-08 14:48:07 -0700
Engine • revision f200ee13aa
Tools • Dart 2.5.0 (build 2.5.0-dev.1.0 f29f41f1a5)
```

**Comment by goderbauer** [comment] 2019-09-09 23:26
Transformations are currently not implemented for Mouse events. Sorry. The work for this is tracked in https://github.com/flutter/flutter/issues/33675. I am closing this as a dupe of that issue.

**Closed by goderbauer** 2019-09-09 23:26 UTC
Labels: customer: octopod, f: gestures, framework
