### ISSUE TITLE
ARCore in Flutter?

### ISSUE THREAD

**Issue by mehrdad372** [flutter/flutter#25354] opened 2018-12-14 06:19 UTC
hi i want to create my app to use ARCore in Flutter like this project : https://www.youtube.com/watch?v=EP-s2ayECsI
my project is Google Reverse Image Search
please guide me
thanks

**Comment by zoechi** [comment] 2018-12-14 10:37
Duplicate of #22860

**Closed by zoechi** 2018-12-14 10:37 UTC

**Comment by khalithartmann** [comment] 2019-03-17 16:01
Checkout my new ARCore plugin : https://pub.dartlang.org/packages/arcore_plugin#-analysis-tab-
Feedback is always welcome

**Comment by mohammad-salehealizadegan** [comment] 2020-03-06 10:03
> 
> 
> Checkout my new ARCore plugin : https://pub.dartlang.org/packages/arcore_plugin#-analysis-tab-
> Feedback is always welcome

hi i use your plugin but my app didnt get anything...it just show white screen and not thing else
please help me 
can you send me example with full directories?
or send me apk out put?
