### ISSUE TITLE
use video player in listview fast scrolling error

### ISSUE THREAD

**Issue by getpu** [flutter/flutter#78006] opened 2021-03-12 08:35 UTC
<details>
<summary>logs</summary>

```bash
E/ACodec (22100): signalError(omxError 0x80001001, internalError -19)
E/ACodec (22100): Error occurred while disabling the output port
E/MediaCodec(22100): Codec reported err 0xffffffed, actionCode 0, while in state 6
D/SurfaceUtils(22100): disconnecting from surface 0x718dc0f010, reason disconnectFromSurface
E/ExoPlayerImplInternal(22100): Playback error
E/ExoPlayerImplInternal(22100): com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, null, -1, null, [1080, 1920, 30.0], [-1, -1]), format_supported=YES
E/ExoPlayerImplInternal(22100): at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:542)
E/ExoPlayerImplInternal(22100): at android.os.Handler.dispatchMessage(Handler.java:108)
E/ExoPlayerImplInternal(22100): at android.os.Looper.loop(Looper.java:216)
E/ExoPlayerImplInternal(22100): at android.os.HandlerThread.run(HandlerThread.java:65)
E/ExoPlayerImplInternal(22100): Caused by: com.google.android.exoplayer2.video.MediaCodecVideoDecoderException: Decoder failed: OMX.hisi.video.decoder.avc
E/ExoPlayerImplInternal(22100): at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.createDecoderException(MediaCodecVideoRenderer.java:1377)
E/ExoPlayerImplInternal(22100): at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:872)
E/ExoPlayerImplInternal(22100): at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:892)
E/ExoPlayerImplInternal(22100): at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:467)
E/ExoPlayerImplInternal(22100): ... 3 more
E/ExoPlayerImplInternal(22100): Caused by: java.lang.IllegalStateException
E/ExoPlayerImplInternal(22100): at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
E/ExoPlayerImplInternal(22100): at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2705)
E/ExoPlayerImplInternal(22100): at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.dequeueOutputBufferIndex(SynchronousMediaCodecAdapter.java:58)
E/ExoPlayerImplInternal(22100): at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1774)
E/ExoPlayerImplInternal(22100): at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:857)
E/ExoPlayerImplInternal(22100): ... 5 more
E/ExoPlayerImplInternal(22100): Disable failed.
E/ExoPlayerImplInternal(22100): java.lang.IllegalStateException
E/ExoPlayerImplInternal(22100): at android.media.MediaCodec.native_flush(Native Method)
E/ExoPlayerImplInternal(22100): at android.media.MediaCodec.flush(MediaCodec.java:2138)
E/ExoPlayerImplInternal(22100): at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.flush(SynchronousMediaCodecAdapter.java:81)
E/ExoPlayerImplInternal(22100): at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.flushOrReleaseCodec(MediaCodecRenderer.java:914)
E/ExoPlayerImplInternal(22100): at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onDisabled(MediaCodecRenderer.java:773)
E/ExoPlayerImplInternal(22100): at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onDisabled(MediaCodecVideoRenderer.java:454)
E/ExoPlayerImplInternal(22100): at com.google.android.exoplayer2.BaseRenderer.disable(BaseRenderer.java:175)
E/ExoPlayerImplInternal(22100): at com.google.android.exoplayer2.ExoPlayerImplInternal.disableRenderer(ExoPlayerImplInternal.java:1507)
E/ExoPlayerImplInternal(22100): at com.google.android.exoplayer2.ExoPlayerImplInternal.resetInternal(ExoPlayerImplInternal.java:1254)
E/ExoPlayerImplInternal(22100): at com.google.android.exoplayer2.ExoPlayerImplInternal.stopInternal(ExoPlayerImplInternal.java:1218)
E/ExoPlayerImplInternal(22100): at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:546)
E/ExoPlayerImplInternal(22100): at android.os.Handler.dispatchMessage(Handler.java:108)
E/ExoPlayerImplInternal(22100): at android.os.Looper.loop(Looper.java:216)
E/ExoPlayerImplInternal(22100): at android.os.HandlerThread.run(HandlerThread.java:65)
I/ACodec (22100): [OMX.hisi.video.decoder.avc] forcing the release of codec
```
</details>

**this question it's been a long time, have you solved it. how to scrolling VideoController dispose???**

**Comment by iapicca** [comment] 2021-03-12 09:25
@getpu 
everything seems to work just fine
please try this [code sample](https://gist.github.com/iapicca/595e112a561088954780bee2c95606cb)

**Comment by getpu** [comment] 2021-03-12 10:21
> @getpu
> everything seems to work just fine
> please try this [code sample](https://gist.github.com/iapicca/595e112a561088954780bee2c95606cb)

in android real machine or what sample error.

![1615543931080](https://user-images.githubusercontent.com/21093942/110926781-c8448e80-835f-11eb-81b6-d6e8407c7074.jpg)

**Comment by iapicca** [comment] 2021-03-12 10:30
@getpu 
it worked well on my `pixel 3a` using the latest `master`
can you provide your `flutter doctor -v` and your `flutter run -v`

**Comment by getpu** [comment] 2021-03-12 10:43
getpu@192 ~ % flutter doctor -v
[✓] Flutter (Channel master, 2.1.0-11.0.pre.179, on macOS 11.2.3 20D91 darwin-x64, locale zh-Hans-CN)
    • Flutter version 2.1.0-11.0.pre.179 at /usr/local/Caskroom/flutter/1.22.6/flutter
    • Framework revision 07e04484ea (2 days ago), 2021-03-09 20:10:05 -0800
    • Engine revision 7764b5c55f
    • Dart version 2.13.0 (build 2.13.0-116.0.dev)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/getpu/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.54.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (3 available)
    • PAR AL00 (mobile)  • FJH7N18A19005332                     • android-arm64  • Android 9 (API 28)
    • iPhone 12 (mobile) • E1A2E19A-B5A2-4608-9F00-01A032F8AD92 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-4
      (simulator)
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 89.0.4389.82

I do as you say, but so as error, this question is a long time, I 've seen them have the same problem， I don't know if they worked it out，this isuse not context.

**Comment by iapicca** [comment] 2021-03-12 10:59
@getpu
can you provide your `flutter run -v`

> I do as you say, but so as error, this question is a long time, I 've seen them have the same problem， 

if you are referring to an open issue can you reference it please

**Comment by getpu** [comment] 2021-03-12 11:09
> @getpu
> can you provide your `flutter run -v`
> 
> > I do as you say, but so as error, this question is a long time, I 've seen them have the same problem，
> 
> if you are referring to an open issue can you reference it please

[        ] I/ACodec  (20622): onStart
[   +1 ms] I/ExoPlayerImpl(20622): Release aab2252 [ExoPlayerLib/2.12.1] [HWPAR, PAR-AL00, HUAWEI, 28] [goog.exo.core]
[  +21 ms] D/SurfaceUtils(20622): disconnecting from surface 0x71ac17f010, reason setNativeWindowSizeFormatAndUsage
[        ] D/SurfaceUtils(20622): connecting to surface 0x71ac17f010, reason setNativeWindowSizeFormatAndUsage
[        ] E/BufferQueueProducer(20622): [SurfaceTexture-0-20622-45] connect: BufferQueue has been abandoned
[        ] E/SurfaceUtils(20622): Failed to connect to surface 0x71ac17f010, err -19
[        ] E/SurfaceUtils(20622): nativeWindowConnect failed: No such device (19)
[        ] E/ACodec  (20622): Failed to allocate buffers after transitioning to IDLE state (error 0xffffffed)
[        ] E/ACodec  (20622): signalError(omxError 0x80001001, internalError -19)
[        ] E/MediaCodec(20622): Codec reported err 0xffffffed, actionCode 0, while in state 5
[   +1 ms] E/ACodec  (20622): [OMX.hisi.video.decoder.avc] ERROR(0x80001012)
[        ] E/ACodec  (20622): signalError(omxError 0x80001012, internalError -2147483648)
[        ] E/ACodec  (20622): [OMX.hisi.video.decoder.avc] ERROR(0x80001012)
[        ] E/ACodec  (20622): signalError(omxError 0x80001012, internalError -2147483648)
[        ] D/SurfaceUtils(20622): disconnecting from surface 0x71ac17f010, reason disconnectFromSurface
[        ] E/MediaCodec(20622): Codec reported err 0x80001012, actionCode 0, while in state 0
[        ] E/MediaCodec(20622): Codec reported err 0x80001012, actionCode 0, while in state 0
[   +9 ms] W/MediaCodecRenderer(20622): Failed to initialize decoder: OMX.hisi.video.decoder.avc
[        ] W/MediaCodecRenderer(20622):   android.media.MediaCodec$CodecException: start failed
[        ] W/MediaCodecRenderer(20622):       at android.media.MediaCodec.native_start(Native Method)
[        ] W/MediaCodecRenderer(20622):       at android.media.MediaCodec.start(MediaCodec.java:2075)
[        ] W/MediaCodecRenderer(20622):       at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.start(SynchronousMediaCodecAdapter.java:48)
[        ] W/MediaCodecRenderer(20622):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:1146)
[        ] W/MediaCodecRenderer(20622):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:1040)
[        ] W/MediaCodecRenderer(20622):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecOrBypass(MediaCodecRenderer.java:604)
[        ] W/MediaCodecRenderer(20622):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1470)
[        ] W/MediaCodecRenderer(20622):       at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:640)
[        ] W/MediaCodecRenderer(20622):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readToFlagsOnlyBuffer(MediaCodecRenderer.java:994)
[        ] W/MediaCodecRenderer(20622):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:844)
[        ] W/MediaCodecRenderer(20622):       at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:892)
[        ] W/MediaCodecRenderer(20622):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:467)
[        ] W/MediaCodecRenderer(20622):       at android.os.Handler.dispatchMessage(Handler.java:108)
[        ] W/MediaCodecRenderer(20622):       at android.os.Looper.loop(Looper.java:216)
[        ] W/MediaCodecRenderer(20622):       at android.os.HandlerThread.run(HandlerThread.java:65)
[   +4 ms] E/ExoPlayerImplInternal(20622): Playback error
[        ] E/ExoPlayerImplInternal(20622):   com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, null, -1, null, [1280, 720, 29.973475], [-1, -1]), format_supported=YES
[        ] E/ExoPlayerImplInternal(20622):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:542)
[        ] E/ExoPlayerImplInternal(20622):       at android.os.Handler.dispatchMessage(Handler.java:108)
[        ] E/ExoPlayerImplInternal(20622):       at android.os.Looper.loop(Looper.java:216)
[        ] E/ExoPlayerImplInternal(20622):       at android.os.HandlerThread.run(HandlerThread.java:65)
[        ] E/ExoPlayerImplInternal(20622):   Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.hisi.video.decoder.avc, Format(1, null, null, video/avc, null, -1, null, [1280, 720,
29.973475], [-1, -1])
[        ] E/ExoPlayerImplInternal(20622):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:1047)
[        ] E/ExoPlayerImplInternal(20622):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecOrBypass(MediaCodecRenderer.java:604)
[        ] E/ExoPlayerImplInternal(20622):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1470)
[        ] E/ExoPlayerImplInternal(20622):       at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:640)
[        ] E/ExoPlayerImplInternal(20622):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readToFlagsOnlyBuffer(MediaCodecRenderer.java:994)
[        ] E/ExoPlayerImplInternal(20622):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:844)
[        ] E/ExoPlayerImplInternal(20622):       at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:892)
[        ] E/ExoPlayerImplInternal(20622):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:467)
[        ] E/ExoPlayerImplInternal(20622):       ... 3 more
[        ] E/ExoPlayerImplInternal(20622):   Caused by: android.media.MediaCodec$CodecException: start failed
[        ] E/ExoPlayerImplInternal(20622):       at android.media.MediaCodec.native_start(Native Method)
[        ] E/ExoPlayerImplInternal(20622):       at android.media.MediaCodec.start(MediaCodec.java:2075)
[        ] E/ExoPlayerImplInternal(20622):       at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.start(SynchronousMediaCodecAdapter.java:48)
[        ] E/ExoPlayerImplInternal(20622):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:1146)
[        ] E/ExoPlayerImplInternal(20622):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:1040)
[        ] E/ExoPlayerImplInternal(20622):       ... 10 more
[  +19 ms] I/ExoPlayerImpl(20622): Init 7bf1175 [ExoPlayerLib/2.12.1] [HWPAR, PAR-AL00, HUAWEI, 28]

this flutter run -v result error.

**Comment by pedromassangocode** [comment] 2021-03-12 11:15
Hi @getpu 
Does the code in https://github.com/flutter/flutter/issues/78006#issuecomment-797396683 reproduce this issue? If yes, can you provide your `flutter doctor -v`?
Thank you

**Comment by getpu** [comment] 2021-03-12 11:19
> Hi @getpu
> Does the code in [#78006 (comment)](https://github.com/flutter/flutter/issues/78006#issuecomment-797396683) reproduce this issue? If yes, can you provide your `flutter doctor -v`?
> Thank you

getpu@192 ~ % flutter doctor -v
[✓] Flutter (Channel master, 2.1.0-11.0.pre.179, on macOS 11.2.3 20D91 darwin-x64, locale zh-Hans-CN)
    • Flutter version 2.1.0-11.0.pre.179 at /usr/local/Caskroom/flutter/1.22.6/flutter
    • Framework revision 07e04484ea (2 days ago), 2021-03-09 20:10:05 -0800
    • Engine revision 7764b5c55f
    • Dart version 2.13.0 (build 2.13.0-116.0.dev)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/getpu/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.54.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (3 available)
    • PAR AL00 (mobile)  • FJH7N18A19005332                     • android-arm64  • Android 9 (API 28)
    • iPhone 12 (mobile) • E1A2E19A-B5A2-4608-9F00-01A032F8AD92 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-4
      (simulator)
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 89.0.4389.82

this doctor -v infomation.

**Comment by pedromassangocode** [comment] 2021-03-16 07:47
Hi @getpu 
IU cannot reproduce this on latest master.

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel master, 2.1.0-13.0.pre.103, on macOS 11.2.2 20D80 darwin-x64, locale en-AO)
    • Flutter version 2.1.0-13.0.pre.103 at /Users/pedromassango/Code/flutter_master
    • Framework revision 0cbe597540 (7 hours ago), 2021-03-15 16:28:02 -0700
    • Engine revision 20375cebcf
    • Dart version 2.13.0 (build 2.13.0-137.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/pedromassango/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 54.0.3
    • Dart plugin version 203.7759

[✓] VS Code (version 1.54.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (3 available)
    • iPhone 12 Pro Max (mobile) • AE2F4F51-880E-44FB-BB29-171B766D9B54 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • macOS (desktop)            • macos                                • darwin-x64     • macOS 11.2.2 20D80 darwin-x64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 89.0.4389.82

! Doctor found issues in 1 category.
```

</details>

**Comment by pedromassangocode** [comment] 2021-04-07 12:52
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2021-04-07 12:52 UTC
Labels: in triage, waiting for customer response
