### ISSUE TITLE
Flutter web taking too much time to load in first time

### ISSUE THREAD

**Issue by Ananthu46** [flutter/flutter#120006] opened 2023-02-04 18:01 UTC
Flutter web downloads too much resources at the first loading time and take too much time to load. if network speed is slow it take very huge time and make users very irritating.

I have tried different rendering options, Still it download 2 MB of data.

As a user its very irritating

**Comment by LappalainenMatias** [comment] 2023-02-04 22:04
Duplicate of [#76009](https://github.com/flutter/flutter/issues/76009)

**Comment by danagbemava-nc** [comment] 2023-02-06 06:41
Closing this as a duplicate of https://github.com/flutter/flutter/issues/76009

**Closed by danagbemava-nc** 2023-02-06 06:41 UTC
Labels: in triage
