### ISSUE TITLE
Cannot run on Android-arm 6.0.1 (API 23) (Channel dev, v1.2.2)

### ISSUE THREAD

**Issue by csshuai** [flutter/flutter#28418] opened 2019-02-24 10:36 UTC
## Logs

```
    UncaughtException detected: java.lang.NoSuchMethodError: No virtual method getLocales()Landroid/os/LocaleList; in class Landroid/content/res/Configuration; or its super classes (declaration of 'android.content.res.Configuration' appears in /system/framework/framework.jar)
        at io.flutter.view.FlutterView.sendLocalesToDart(FlutterView.java:323)
        at io.flutter.view.FlutterView.<init>(FlutterView.java:187)
        at io.flutter.app.FlutterActivityDelegate.onCreate(FlutterActivityDelegate.java:161)
        at io.flutter.app.FlutterActivity.onCreate(FlutterActivity.java:89)
```

[FlutterView.sendLocalesToDart()](https://github.com/flutter/engine/blob/e11d0e96fb16811e4c989ec39bb1965d7924655a/shell/platform/android/io/flutter/view/FlutterView.java#L323)

```
flutter doctor -v
[✓] Flutter (Channel dev, v1.2.2, on Mac OS X 10.14.3 18D109, locale zh-Hans-CN)
    • Flutter version 1.2.2 at /Users/william/git/dart/flutter
    • Framework revision 007a415c2a (2 days ago), 2019-02-21 20:22:47 -0800
    • Engine revision f1f19bba8f
    • Dart version 2.2.0 (build 2.2.0-dev.2.1 c92d5ca288)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/william/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Users/william/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/182.5264788/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.3)
    • Android Studio at /Users/william/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/182.5264788/Android Studio.app/Contents
    • Flutter plugin version 33.1.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.3.4)
    • IntelliJ at /Users/william/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 30.0.2
    • Dart plugin version 182.5124

[✓] VS Code (version 1.30.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.23.0

[✓] Connected device (3 available)
    • MI 4LTE   • 9121afb0                                 • android-arm • Android 6.0.1 (API 23)
```

@matthew-carroll

**Comment by Azazel** [comment] 2019-02-24 11:06
Similar to https://github.com/flutter/flutter/issues/28412

**Comment by pjcau** [comment] 2019-02-24 11:53
I verify this issue, crash on sdk 21, 22, 23. It's running from 24 to 28.

**Comment by jonahwilliams** [comment] 2019-02-24 20:45
duplicate of https://github.com/flutter/flutter/issues/28321

**Closed by jonahwilliams** 2019-02-24 20:45 UTC
