### ISSUE TITLE
The cupertino picker cuts off emojis when disabling a button on the page while scrolling the picker

### ISSUE THREAD

**Issue by dannyvalentesonos** [flutter/flutter#41903] opened 2019-10-03 12:41 UTC
This bug exists with Flutter 1.8 and 1.9 also.

If the last item in the Cupertino picker widget only contains emojis, then the emojis can get cut off once scrolling the picker stops, but only if disabling a material button on the same page while scrolling.

**Extra info**: If scrolling the picker without disabling a button on the page, this doesn't happen. If calling setState() to disable the button still happens, but actually disabling the button is commented, it doesn't happen.
If the last item in the picker has text mixed with the emojis, it doesn't happen.
If another item in the picker has only emojis, that item renders correctly.
Finally, it looks like the eyes emojis themselves even _change_ as they scroll.

The following code leads to the problem:

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

class PickerEmojiHomePage extends StatefulWidget {
  @override
  _PickerEmojiHomePageState createState() => _PickerEmojiHomePageState();
}

class _PickerEmojiHomePageState extends State<PickerEmojiHomePage> {

  FixedExtentScrollController _scrollController;
  bool _scrolling = false;

  List<String> _items = [
    "Testing 1",
    "Testing 2",
    "Testing 3",
    "👀😍👀",
    "👀😍👀"
  ];

  @override
  void initState() {
    super.initState();
    _scrollController = FixedExtentScrollController(initialItem: 0);
  }

  Widget _getItem(int index) {
    String item = _items[index];
    return Center(
      child: Text(
        item,
        overflow: TextOverflow.ellipsis,
        style: TextStyle(fontSize: 16),
        strutStyle: StrutStyle(
            forceStrutHeight: true
        ),
      ),
    );
  }

  bool _onScrollNotification(ScrollNotification notification) {
    if (notification is ScrollStartNotification) {
      setState(() {
        _scrolling = true;
      });
    }
    else if (notification is ScrollEndNotification) {
      setState(() {
        _scrolling = false;
      });
    }

    return true;
  }

  @override
  Widget build(BuildContext context) {

    return Material(
        elevation: 0,
        child: SafeArea(
          child: Column(
            children: <Widget>[
              Expanded(
                child: Container(
                    height: 40,
                    child: NotificationListener<ScrollNotification> (
                        onNotification: _onScrollNotification,
                        child: CupertinoPicker.builder(
                            scrollController: _scrollController,
                            onSelectedItemChanged: (index) {

                            },
                            itemExtent: 40,
                            diameterRatio: 20.0,
                            squeeze: 1.0,
                            backgroundColor: Colors.white,
                            childCount: _items.length,
                            itemBuilder: (context, index) {
                              return _getItem(index);
                            }
                        )
                    )
                ),
              ),
              FlatButton(
                child: Text("Continue"),
                onPressed: _scrolling ? null : () {},
              )
            ],
          )
        )
    );
  }
}
```
</details>

**Comment by dannyvalentesonos** [comment] 2019-10-03 12:42
Flutter doctor:

[✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Mac OS X 10.14.6 18G103, locale en-US)
    • Flutter version 1.9.1+hotfix.2 at /Users/danny.valente/Library/flutter/1.9.1+hotfix.2-stable
    • Framework revision 2d2a1ffec9 (4 weeks ago), 2019-09-06 18:39:49 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/danny.valente/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.0, Build version 11A420a
    • CocoaPods version 1.7.5

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (1 available)
    • Danny's iPhone 6 • 48d0e286e01ae6e0908aaa2a606aabdcd3fd33b5 • ios • iOS 10.1.1

• No issues found!

**Comment by dannyvalentesonos** [comment] 2019-10-03 12:43
[emoji_picker_issue.mov.zip](https://github.com/flutter/flutter/files/3686051/emoji_picker_issue.mov.zip)

Adding a zip file which contains the video showing the issue.

**Comment by LongCatIsLooong** [comment] 2019-10-03 23:05
Looks like it's only reproducible on iOS. @GaryQian any chance this could be related to https://github.com/flutter/flutter/issues/28894?

**Comment by justinmc** [comment] 2019-10-04 18:18
I agree, I tried to reproduce this on a physical Pixel 2 and the iOS 13 simulator, and I only saw it on the simulator.

**Comment by VladyslavBondarenko** [comment] 2020-05-05 15:42
@dannyvalentesonos 
I can't reproduce it with iOS-13-4 (simulator) and `dev 1.18.0-8.0.pre`.
Seems to be fixed, closing. Comment please if I'm wrong and I'll reopen

<details>
 <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel dev, v1.18.0-8.0.pre, on Mac OS X 10.15.4 19E287, locale en-GB)
    • Flutter version 1.18.0-8.0.pre at /Users/nevercode/dev/flutter_dev
    • Framework revision e0c63cd35e (12 days ago), 2020-04-23 22:29:01 -0400
    • Engine revision d2ec21221e
    • Dart version 2.9.0 (build 2.9.0-3.0.dev b0d35855d8)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/nevercode/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.44.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1

[✓] Connected device (5 available)
    • Redmi Note 7      • 6345c469                             • android-arm64  • Android 9 (API 28)
    • iPhone 11 Pro Max • 5D5365D0-C0F6-4440-B758-FFA83896129E • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-4 (simulator)
    • macOS             • macOS                                • darwin-x64     • Mac OS X 10.15.4 19E287
    • Web Server        • web-server                           • web-javascript • Flutter Tools
    • Chrome            • chrome                               • web-javascript • Google Chrome 81.0.4044.129

• No issues found!
```

</details>

**Comment by dannyvalentesonos** [comment] 2020-05-06 18:02
@VladyslavBondarenko I just tested with `1.18.0-10.0.pre`, and this is the result I got. The bug is still present.

![Screen Shot 2020-05-06 at 2 01 16 PM](https://user-images.githubusercontent.com/40898687/81211976-2d8e5d00-8fa2-11ea-895b-da0954b9add5.png)

**Comment by VladyslavBondarenko** [comment] 2020-05-07 10:28
@dannyvalentesonos 
ohh, I see, I was looking only on the cropping last selected item as on your video

**Comment by dannyvalentesonos** [comment] 2020-05-07 12:58
Yes, I believe it might be worse now, seeing every non-selected item now presents the problem. I haven't looked into this bug in a long time, so I'm not sure this is new behavior, but by looking back at the video I logged, I would say it is.

**Comment by dannyvalentesonos** [comment] 2020-05-07 13:17
@VladyslavBondarenko  I just re-ran the sample app I had created, and I can confirm the behavior is now worse. I'm attaching a new video.
Thanks!

**Comment by dannyvalentesonos** [comment] 2020-05-07 13:17
[emoji_picker_issue_new.mov.zip](https://github.com/flutter/flutter/files/4593143/emoji_picker_issue_new.mov.zip)

**Comment by dannyvalentesonos** [comment] 2020-05-27 01:41
@VladyslavBondarenko Can you please re-open this bug seeing it still happens, and is even worse now? Thanks

**Comment by VladyslavBondarenko** [comment] 2020-05-27 06:58
@dannyvalentesonos sorry, I thought I reopened

**Comment by TahaTesser** [comment] 2021-01-27 13:18
Issues reproduce in the latest `stable` and `master` channels as well. 

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 1.22.6, on macOS 11.1 20C69 darwin-x64, locale en-GB)
    • Flutter version 1.22.6 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 9b2d32b605 (5 days ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (2 available)
    • RMX2001 (mobile)     • EUYTFEUSQSRGDA6D          • android-arm64 • Android 10 (API 29)
    • Taha’s iPad (mobile) • 00008020-000255113EE8402E • ios           • iOS 14.3

! Doctor found issues in 1 category.
```
```bash
[✓] Flutter (Channel master, 1.26.0-13.0.pre.194, on macOS 11.1 20C69 darwin-x64, locale en-GB)
    • Flutter version 1.26.0-13.0.pre.194 at /Users/tahatesser/Code/flutter_master
    • Framework revision 71aec53acb (5 hours ago), 2021-01-26 21:53:04 -0800
    • Engine revision b11bef83a5
    • Dart version 2.12.0 (build 2.12.0-263.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (4 available)
    • RMX2001 (mobile)     • EUYTFEUSQSRGDA6D          • android-arm64  • Android 10 (API 29)
    • Taha’s iPad (mobile) • 00008020-000255113EE8402E • ios            • iOS 14.3
    • macOS (desktop)      • macos                     • darwin-x64     • macOS 11.1 20C69 darwin-x64
    • Chrome (web)         • chrome                    • web-javascript • Google Chrome 88.0.4324.96

• No issues found!
```

</details>

**Comment by justinmc** [comment] 2021-01-28 17:28
@LongCatIsLooong Will this be affected by your work on half-leading?

**Comment by LongCatIsLooong** [comment] 2021-02-02 05:49
half-leading (or ascent/descent-scaling) only affects text layout when a height multiplier is specified (`TextStyle.height`), so it's unlikely to affect this issue.

**Comment by maheshmnj** [comment] 2022-12-09 05:55
Hi @dannyvalentesonos, I verified the issue on the latest master channel and I am unable to reproduce it. I believe this issue is fixed.



https://user-images.githubusercontent.com/31410839/206634224-eab40bc7-144c-489c-8398-8d3041c516a2.mov

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData.dark(),
      home: PickerEmojiHomePage(),
    );
  }
}

class PickerEmojiHomePage extends StatefulWidget {
  @override
  _PickerEmojiHomePageState createState() => _PickerEmojiHomePageState();
}

class _PickerEmojiHomePageState extends State<PickerEmojiHomePage> {
  late FixedExtentScrollController _scrollController;
  bool _scrolling = false;

  final List<String> _items = [
    "Testing 1",
    "Testing 2",
    "Testing 3",
    "👀😍👀",
    "👀😍👀"
  ];

  @override
  void initState() {
    super.initState();
    _scrollController = FixedExtentScrollController(initialItem: 0);
  }

  Widget _getItem(int index) {
    String item = _items[index];
    return Center(
      child: Text(
        item,
        overflow: TextOverflow.ellipsis,
        style: const TextStyle(fontSize: 16, color: Colors.black),
        strutStyle: const StrutStyle(forceStrutHeight: true),
      ),
    );
  }

  bool _onScrollNotification(ScrollNotification notification) {
    if (notification is ScrollStartNotification) {
      setState(() {
        _scrolling = true;
      });
    } else if (notification is ScrollEndNotification) {
      setState(() {
        _scrolling = false;
      });
    }

    return true;
  }

  @override
  Widget build(BuildContext context) {
    return Material(
        elevation: 0,
        child: SafeArea(
            child: Column(
          children: <Widget>[
            Expanded(
              child: SizedBox(
                  height: 40,
                  child: NotificationListener<ScrollNotification>(
                      onNotification: _onScrollNotification,
                      child: CupertinoPicker.builder(
                          scrollController: _scrollController,
                          onSelectedItemChanged: (index) {},
                          itemExtent: 40,
                          diameterRatio: 20.0,
                          squeeze: 1.0,
                          backgroundColor: Colors.white,
                          childCount: _items.length,
                          itemBuilder: (context, index) {
                            return _getItem(index);
                          }))),
            ),
            OutlinedButton(
              onPressed: _scrolling ? null : () {},
              child: const Text("Continue"),
            )
          ],
        )));
  }
}

```
</details>  

<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel master, 3.7.0-3.0.pre.33, on macOS 12.6 21G115 darwin-arm64, locale en-IN)
    • Flutter version 3.7.0-3.0.pre.33 on channel master 
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5201856805 (38 minutes ago), 2022-12-05 18:27:21 -0800
    • Engine revision a309d239c4
    • Dart version 2.19.0 (build 2.19.0-463.0.dev)
    • DevTools version 2.20.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly
      to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.70.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.55.20221129

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • 026D5789-9E78-4AD5-B1B2-3F8D4E7F65E4 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.6 21G115 darwin-arm64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 108.0.5359.94

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

Closing, since this is no longer reproducible, In case you still encounter the bug, Please feel free to write in the comments and we will reopen it.

Thank you.

**Closed by maheshmnj** 2022-12-09 05:55 UTC
Labels: framework, f: scrolling, f: cupertino, a: typography, customer: amplify, has reproducible steps, found in release: 1.22, found in release: 1.26
