### ISSUE TITLE
Why app try to run on AOSP on IA emulator although my device is nexus 6 API 28

### ISSUE THREAD

**Issue by vnxz** [flutter/flutter#84919] opened 2021-06-19 19:34 UTC
I start running first flutter .
I installed ADV as document 
My device is nexus 6 API 28
But why run on AOSP on IA emulator although choose nexus 6 

![Screenshot_2](https://user-images.githubusercontent.com/76085185/122653625-d0d11000-d16b-11eb-9ed5-c2832c01b951.png)

![Screenshot_3](https://user-images.githubusercontent.com/76085185/122653628-d62e5a80-d16b-11eb-9ff6-377b32df2cd0.png)

![Screenshot_4](https://user-images.githubusercontent.com/76085185/122653633-dd556880-d16b-11eb-9914-c05bb0b14e15.png)

**Comment by behzodfaiziev** [comment] 2021-06-19 21:20
@vnxz If it isn't making any issue there is no problem that `nexus 6 API 28`  is  `AOSP on IA emulator `
Duplicate of  #61823

**Comment by behzodfaiziev** [comment] 2021-06-19 21:22
@vnxz That might probably help #61823

**Comment by vnxz** [comment] 2021-06-20 04:33
> 
> 
> @vnxz That might probably help #61823
thanks ,but not ok for me .how can I solve . another solution?

**Comment by vnxz** [comment] 2021-06-20 07:29
> 
> 
> I start running first flutter .
> I installed ADV as document
> My device is nexus 6 API 28
> But why run on AOSP on IA emulator although choose nexus 6
> 
> ![Screenshot_2](https://user-images.githubusercontent.com/76085185/122653625-d0d11000-d16b-11eb-9ed5-c2832c01b951.png)
> 
> ![Screenshot_3](https://user-images.githubusercontent.com/76085185/122653628-d62e5a80-d16b-11eb-9ff6-377b32df2cd0.png)
> 
> ![Screenshot_4](https://user-images.githubusercontent.com/76085185/122653633-dd556880-d16b-11eb-9914-c05bb0b14e15.png)

can someone help me why this AOSP on emulator  appear

why  not device name appear.
![Screenshot_2](https://user-images.githubusercontent.com/76085185/122665830-a87afd00-d1cf-11eb-8800-dbd4d5d64cc1.png)

**Comment by TahaTesser** [comment] 2021-06-21 13:19
Hi @behzodfaiziev 
Can you please provide your `flutter doctor -v` and your `flutter emulators`
Thank you

**Comment by wwk45** [comment] 2021-06-22 05:16
Hello @TahaTesser 
I have the same problem
i have attached the output of the following commands
`flutter doctor -v `and `flutter emulators` 
![Capture](https://user-images.githubusercontent.com/75829787/122867397-09791100-d347-11eb-9266-7f5c61197586.JPG)

**Comment by TahaTesser** [comment] 2021-07-01 11:02
@vnxz  @wwk45 
Based on logs, there is "AOSP" in flutter logs, this must be plugin issue, please file an issue for plugin

**Comment by ritish2002** [comment] 2021-07-18 12:42
Hey @wwk45 , is your issue resolved?
If yes can you please explain me what to do as I've been trying for it all day but i'm still facing the same issue. 

Thank You!

**Closed** 2021-07-18 13:19 UTC
Labels: in triage, waiting for customer response
