### ISSUE TITLE
VSCode - Debug logs are not consistent between platforms

### ISSUE THREAD

**Issue by ValentinVignal** [flutter/flutter#97754] opened 2022-02-04 01:53 UTC
## Steps to Reproduce

1. run `flutter create my_app`
2. `cd my_app`

add the file `.vscode/launch.json` : 
```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Run",
      "request": "launch",
      "type": "dart",
      "program": "lib/main.dart"
    },
  ]
}
```

Then for iOS, macOS, and chrome, press `F5` to run the application with VSCode. The logs are not consistent. For example, `"💪 Running with sound null safety 💪"` log is only visible on chrome.

Because of that, I spent quite some time trying to find why my app was not running null-safely on macOS and iOS (it was not the same code). But from this issue, I believe it is running null-safely but it is only not logged?

I also opened a issue there: https://github.com/Dart-Code/Dart-Code/issues/3812

**Expected results:** 

The logs should be consistent between the platforms.

**Actual results:** 

**Chrome:**

<details>

<summary>VSCode launch</summary>

```
Launching lib[/main.dart]() on Chrome in debug mode...
lib/main.dart:1
This app is linked to the debug service: ws://127.0.0.1:53511[/ozhDRx6xrqM]()%3D[/ws]()
Debug service listening on ws://127.0.0.1:53511[/ozhDRx6xrqM]()=[/ws]()
💪 Running with sound null safety 💪
Connecting to VM Service at ws://127.0.0.1:53511[/ozhDRx6xrqM]()=[/ws]()
```

</details>

<details>

<summary>Command line</summary>

Running with `flutter run lib/main.dart`

```
Launching lib/main.dart on Chrome in debug mode...
Waiting for connection from debug service on Chrome...             16.1s
This app is linked to the debug service: ws://127.0.0.1:54213/a29Uqn05_vY=/ws
Debug service listening on ws://127.0.0.1:54213/a29Uqn05_vY=/ws

💪 Running with sound null safety 💪

🔥  To hot restart changes while running, press "r" or "R".
For a more detailed help message, press "h". To quit, press "q".

An Observatory debugger and profiler on Chrome is available at: http://127.0.0.1:54213/a29Uqn05_vY=
The Flutter DevTools debugger and profiler on Chrome is available at:
http://127.0.0.1:9101?uri=http://127.0.0.1:54213/a29Uqn05_vY=
```

</details>

**iOS:**

<details>

<summary>VSCode launch</summary>

```
Launching lib[/main.dart]() on iPhone 12 Pro Max in debug mode...
lib/main.dart:1
Xcode build done.                                            8.1s
Connecting to VM Service at ws://127.0.0.1:54344[/4nX6XeDauZg]()=[/ws]()
```

</details>

<details>

<summary>Command line</summary>

Running with `flutter run lib/main.dart`

```
Launching lib/main.dart on iPhone 12 Pro Max in debug mode...
Running Xcode build...                                                  
 └─Compiling, linking and signing...                      2,328ms
Xcode build done.                                            8.0s
Syncing files to device iPhone 12 Pro Max...                        91ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

💪 Running with sound null safety 💪

An Observatory debugger and profiler on iPhone 12 Pro Max is available at:
http://127.0.0.1:54468/GF1QrQ6IbsE=/
The Flutter DevTools debugger and profiler on iPhone 12 Pro Max is available at:
http://127.0.0.1:9101?uri=http://127.0.0.1:54468/GF1QrQ6IbsE=/
```

</details>

**macOS:**

<details>

<summary>VSCode launch</summary>

```
Launching lib[/main.dart]() on macOS in debug mode...
lib/main.dart:1
Connecting to VM Service at ws://127.0.0.1:54540[/cAD_JOHmRow]()=[/ws]()
```

</details>

<details>

<summary>Command line</summary>

Running with `flutter run lib/main.dart`

```
Launching lib/main.dart on macOS in debug mode...
Building macOS application...                                           
Syncing files to device macOS...                                   104ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

💪 Running with sound null safety 💪

An Observatory debugger and profiler on macOS is available at: http://127.0.0.1:53306/4qNSLtaDOHU=/
The Flutter DevTools debugger and profiler on macOS is available at: http://127.0.0.1:9101?uri=http://127.0.0.1:53306/4qNSLtaDOHU=/
```

</details>

<details>
  <summary>Logs</summary>

```
Analyzing flutter_app...                                                
No issues found! (ran in 1.6s)
```

```
[✓] Flutter (Channel stable, 2.8.1, on macOS 11.5.1 20G80 darwin-x64, locale en-GB)
    • Flutter version 2.8.1 at /Users/valentin/flutter/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (7 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /usr/local/Caskroom/android-sdk/4333796
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[!] Xcode - develop for iOS and macOS (Xcode 12.5.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.0.0.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.27.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.5.1 20G80 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 97.0.4692.99

! Doctor found issues in 2 categories.
```

**Versions (please complete the following information):**
 - VS Code version: `1.63.2`
 - Dart extension version: `v3.27.2`
 - Flutter extension version: `v3.27.0`
 - Dart/Flutter SDK version: 
Running `flutter --version` :
```
Flutter 2.8.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 77d935af4d (7 weeks ago) • 2021-12-16 08:37:33 -0800
Engine • revision 890a5fca2e
Tools • Dart 2.15.1
```

</details>

**Comment by maheshmnj** [comment] 2022-02-04 10:25
Hi @ValentinVignal, Thanks for filing the issue. I am able to see the same behavior on stable and the master channel The "unsound null safety" log is only available in chrome logs and not in other platforms.
 

<details>
<summary>IOS</summary>

```
Launching lib/main.dart on iPhone 12 Pro in debug mode...
Xcode build done.                                           37.3s
Connecting to VM Service at ws://127.0.0.1:49207/2uV0_lZQbmk=/ws
```
</details>


<details>
<summary>Android</summary>

```
Launching lib[/main.dart]() on Redmi K20 Pro in debug mode...
lib/main.dart:1
Warning: Mapping new ns [http://schemas.android.com/repository/android/common/02]() to old ns [http://schemas.android.com/repository/android/common/01]()
Warning: Mapping new ns [http://schemas.android.com/repository/android/generic/02]() to old ns [http://schemas.android.com/repository/android/generic/01]()
Warning: Mapping new ns [http://schemas.android.com/sdk/android/repo/addon2/02]() to old ns [http://schemas.android.com/sdk/android/repo/addon2/01]()
Warning: Mapping new ns [http://schemas.android.com/sdk/android/repo/repository2/02]() to old ns [http://schemas.android.com/sdk/android/repo/repository2/01]()
Warning: Mapping new ns [http://schemas.android.com/sdk/android/repo/sys-img2/02]() to old ns [http://schemas.android.com/sdk/android/repo/sys-img2/01]()
Warning: Mapping new ns [http://schemas.android.com/repository/android/common/02]() to old ns [http://schemas.android.com/repository/android/common/01]()
Warning: Mapping new ns [http://schemas.android.com/repository/android/generic/02]() to old ns [http://schemas.android.com/repository/android/generic/01]()
Warning: Mapping new ns [http://schemas.android.com/sdk/android/repo/addon2/02]() to old ns [http://schemas.android.com/sdk/android/repo/addon2/01]()
Warning: Mapping new ns [http://schemas.android.com/sdk/android/repo/repository2/02]() to old ns [http://schemas.android.com/sdk/android/repo/repository2/01]()
```
</details>


<details>
<summary>chrome</summary>

```console
Launching lib/main.dart on Chrome in debug mode...
This app is linked to the debug service: ws://127.0.0.1:65306/KOlcs-N0Yn4%3D/ws
Debug service listening on ws://127.0.0.1:65306/KOlcs-N0Yn4=/ws
💪 Running with sound null safety 💪
Connecting to VM Service at ws://127.0.0.1:65306/KOlcs-N0Yn4=/ws
```
</details>


<details>
<summary>macos</summary>

```console
Launching lib/main.dart on macOS in debug mode...
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:macOS, arch:x86_64, id:6A745C96-D83E-5C8D-8EE9-5958E598001B }
{ platform:macOS, name:Any Mac }
Connecting to VM Service at ws://127.0.0.1:65025/azrxZb7SAF0=/ws
```
</details>


<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.10.0, on macOS 12.1 21C52 darwin-arm, locale en-GB)
    • Flutter version 2.10.0 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5f105a6ca7 (3 days ago), 2022-02-01 14:15:42 -0800
    • Engine revision 776efd2034
    • Dart version 2.16.0
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.34.0

[✓] Connected device (4 available)
    • Redmi K20 Pro (mobile) • 192.168.1.2:5555                     • android-arm64  • Android 11 (API
      30)
    • iPhone 12 Pro (mobile) • 14F40EC6-3B73-469A-A1C0-8CF0B152290F • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.1 21C52
      darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome
      98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

```
[✓] Flutter (Channel master, 2.10.0-1.0.pre.371, on macOS 12.1 21C52 darwin-arm, locale en-GB)
    • Flutter version 2.10.0-1.0.pre.371 at /Users/mahesh/Documents/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d1285eef1b (2 days ago), 2022-02-02 00:50:20 -0500
    • Engine revision 5bbdb7a6f7
    • Dart version 2.17.0 (build 2.17.0-74.0.dev)
    • DevTools version 2.10.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.34.0

[✓] Connected device (4 available)
    • Redmi K20 Pro (mobile) • 192.168.1.2:5555                     • android-arm64  • Android 11 (API
      30)
    • iPhone 12 Pro (mobile) • 14F40EC6-3B73-469A-A1C0-8CF0B152290F • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.1 21C52
      darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome
      98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by christopherfujino** [comment] 2022-02-04 17:06
Thanks for filing this and the detailed information (it really helps us when triaging!). However, since from the logs you shared it looks like the message is correctly showing from the command line tool, and the problem is that VSCode is not showing it, I will close this issue in favor of https://github.com/Dart-Code/Dart-Code/issues/3812, as it seems like the command-line tool is working correctly.

Thanks again for filing the detailed issue however!

**Closed by christopherfujino** 2022-02-04 17:06 UTC
Labels: tool, a: debugging, has reproducible steps, found in release: 2.10

**Comment by DanTup** [comment] 2022-02-09 15:21
@christopherfujino I believe the problem is that Flutter isn't sending the output when using `--machine`. I would expect the issue is also present in Android Studio for this same reason. Below is my comment from the other issue explaining what I think the problem is.

---

This seems to be a difference in Flutter behaviour, so should be filed at https://github.com/flutter/flutter/.

For non-web, the line is printed here:

https://github.com/flutter/flutter/blob/d7688ca0930fe80d162361be30405a15c929ada9/packages/flutter_tools/lib/src/run_hot.dart#L1012

This is part of `printHelp()`, so it only appears when Flutter prints the shortcut keys for using the terminal. When running from the IDE (which runs `flutter run --machine`), this code is not called, so the message is not printed.

However for Web, it looks like both the standard and `--machine` versions go through a different path and into `resident_web_runner` which always prints the message:

https://github.com/flutter/flutter/blob/61a0add2865c51bfee33939c1820709d1115c77d/packages/flutter_tools/lib/src/isolated/resident_web_runner.dart#L638

I suspect the best fix will be to move the message in `run_hot.dart` to somewhere called in both modes so that the message is always printed for all types (it seems like useful info to have in the IDE output too).

If you raise in Flutter, please post the link back here. Thanks!
