### ISSUE TITLE
[tool_crash] FileSystemException: Cannot open file, OS Error: The file or directory is corrupted and unreadable., errno = 1392

### ISSUE THREAD

**Issue by abdul-basit-dev** [flutter/flutter#80117] opened 2021-04-09 14:42 UTC
## Command
```
flutter doctor
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Cannot open file, OS Error: The file or directory is corrupted and unreadable.
, errno = 1392
```
#0      _File.throwIfError (dart:io/file_impl.dart:635:7)
#1      _File.openSync (dart:io/file_impl.dart:479:5)
#2      _File.writeAsBytesSync (dart:io/file_impl.dart:604:31)
#3      _File.writeAsStringSync (dart:io/file_impl.dart:628:5)
#4      ForwardingFile.writeAsStringSync (package:file/src/forwarding/forwarding_file.dart:147:16)
#5      ErrorHandlingFile.writeAsStringSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:259:22)
#6      _runSync (package:flutter_tools/src/base/error_handling_io.dart:560:14)
#7      ErrorHandlingFile.writeAsStringSync (package:flutter_tools/src/base/error_handling_io.dart:258:5)
#8      Cache.setStampFor (package:flutter_tools/src/cache.dart:529:35)
#9      VersionCheckStamp.store (package:flutter_tools/src/version.dart:587:19)
#10     FlutterVersion._getLatestAvailableFlutterDate (package:flutter_tools/src/version.dart:494:31)
<asynchronous suspension>
#11     FlutterVersion.checkFlutterVersionFreshness (package:flutter_tools/src/version.dart:399:46)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:257:11)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:152:19)
<asynchronous suspension>
#14     AppContext.run (package:flutter_tools/src/base/context.dart:151:12)
<asynchronous suspension>
#15     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:239:5)
<asynchronous suspension>
#16     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
<asynchronous suspension>
#17     run.<anonymous closure> (package:flutter_tools/runner.dart:60:12)
```
```
[✓] Flutter (Channel dev, 1.27.0-8.0.pre, on Microsoft Windows [Version
    10.0.19042.867], locale en-US)
    • Flutter version 1.27.0-8.0.pre at D:\AbdulsWork\flutter
    • Framework revision b7d4806243 (7 weeks ago), 2021-02-19 09:22:45 -0800
    • Engine revision 6993cb229b
    • Dart version 2.13.0 (build 2.13.0-30.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Sony\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.55.1)
    • VS Code at C:\Users\Sony\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.21.0

[✓] Connected device (3 available)
    • Redmi Note 8 (mobile) • 1701f8c7 • android-arm64  • Android 9 (API 28)
    • Chrome (web)          • chrome   • web-javascript • Google Chrome
      89.0.4389.114
    • Edge (web)            • edge     • web-javascript • Microsoft Edge
      89.0.774.57

• No issues found!

```

## Flutter Application Metadata
No pubspec in working directory.

**Comment by iapicca** [comment] 2021-04-10 14:01
@abdul-basit-dev
the issue might be caused by a corrupted installation https://github.com/flutter/flutter/issues/60107#issuecomment-695061619
please try this [fix](https://github.com/flutter/flutter/wiki/Workarounds-for-common-issues#flutter-installation-corrupted)

**Comment by darshankawar** [comment] 2021-04-12 06:43
@abdul-basit-dev 
Check above link and solution to see if it resolves your issue.
Thanks.

**Comment by pedromassangocode** [comment] 2021-05-07 10:56
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2021-05-07 10:56 UTC
Labels: in triage, waiting for customer response
