### ISSUE TITLE
No support for Isolate.resolvePackageUri

### ISSUE THREAD

**Issue by srawlins** [flutter/flutter#14815] opened 2018-02-22 05:16 UTC
## Steps to Reproduce

When running an app and calling [`Isolate.resolvePackageUri()`](https://docs.flutter.io/flutter/dart-isolate/Isolate/resolvePackageUri.html), which I assumed would be safe on any platform, I see that it is an unsupported operation.

## Logs

```none
E/flutter (27891): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter (27891): Unsupported operation: Isolate.resolvePackageUri
E/flutter (27891): #0      initializeTimeZone.<anonymous closure> (package:timezone/standalone.dart:74:5)
E/flutter (27891): #1      _RootZone.runUnary (dart:async/zone.dart:1381)
E/flutter (27891): #2      _FutureListener.handleError (dart:async/future_impl.dart:144)
E/flutter (27891): #3      _Future._propagateToListeners.handleError (dart:async/future_impl.dart:645)
E/flutter (27891): #4      _Future._propagateToListeners (dart:async/future_impl.dart:666)
E/flutter (27891): #5      _Future._completeError (dart:async/future_impl.dart:485)
E/flutter (27891): #6      _SyncCompleter._completeError (dart:async/future_impl.dart:55)
E/flutter (27891): #7      _Completer.completeError (dart:async/future_impl.dart:27)
E/flutter (27891): #8      _loadAsBytes (package:timezone/standalone.dart)
```

## Question

Is it intentionally unsupported? Or is it just not supported yet? I could not find any documentation on this.

**Comment by a-siva** [comment] 2018-02-23 01:29
On the command line VM the embedder sets up the VMLibraryHooks class which has the resolvePackageUri functionality by calling into the '_setupHooks' method in builtin.dart.
For some reason we don't do the same in flutter engine, need to investigate why.

**Comment by pedzed** [comment] 2018-08-15 17:57
Any updates on this?

**Comment by chenasraf** [comment] 2019-02-26 01:38
Also have this problem, trying to use my own package which uses a static data json file - I can't load it, via `File` nor the `Resource` package.

**Comment by acherkashyn** [comment] 2019-04-17 02:35
Also getting this error when trying to run tests with [mock_web_server](https://pub.dartlang.org/packages/mock_web_server). 

```
Unsupported operation: Isolate.resolvePackageUri

dart:isolate                              Isolate.resolvePackageUri
package:resource/src/resolve.dart 11:20   resolveUri
package:resource/src/resource.dart 64:21  Resource.readAsBytes
===== asynchronous gap ===========================
dart:async                                _AsyncAwaitCompleter.completeError
package:resource/src/resource.dart        Resource.readAsBytes
```

Any progress on this issue?

**Comment by eseidelGoogle** [comment] 2019-04-25 02:27
https://pub.dartlang.org/packages/path_provider or https://docs.flutter.io/flutter/services/AssetBundle-class.html might be the path-lookups you're looking for.  https://flutter.dev/docs/development/ui/assets-and-images

I'm not sure whether this was intentional or not.  But it's also not immediately clear what this API should do in Flutter?

**Comment by ened** [comment] 2019-04-30 07:35
@eseidelGoogle `Isolate.spawn` seems to be using it:

From current testing, this prevents background Isolates on iOS (created using `FlutterEngine(name: "MyIsolate", project: nil, allowHeadlessExecution: true)`) from creating further child Isolates themselves.

**Comment by ened** [comment] 2019-04-30 07:37
Related to https://github.com/rmawatson/flutter_isolate/issues/5 - this is a major headache now.

**Comment by ened** [comment] 2019-05-07 18:29
Adding on - code that relies on executing `compute` calls to lift tasks out of the main thread will also not run in the iOS background.

**Comment by liamappelbe** [comment] 2019-05-07 23:40
@a-siva Actually Flutter doesn't use [dart:_builtin](https://github.com/dart-lang/sdk/blob/master/runtime/bin/builtin.dart). Flutter's equivalent of _builtin is [ui/natives.dart](https://github.com/flutter/engine/blob/master/lib/ui/natives.dart), and they are calling that library's _setupHooks() method [here](https://github.com/flutter/engine/blob/master/lib/ui/dart_runtime_hooks.cc#L86).

So I think the issue here is that there's some functionality missing from ui/natives.dart required to make Isolate.resolvePackageUri work.

**Comment by ened** [comment] 2019-05-08 03:13
@liamappelbe is it an easy fix?

**Comment by liamappelbe** [comment] 2019-05-08 16:04
Not sure yet. Still investigating.

**Comment by liamappelbe** [comment] 2019-05-09 20:29
Looks like we can't just naively copy the implementation that dart uses. We'll need to implement something custom.

@cbracken Any ideas about what this API should do on Flutter? It's supposed to turn "package:" URIs into absolute URIs. For example, when I run this on Linux I get an absolute path to the dart file of the package. Does that make sense on all Flutter platforms?

**Comment by ened** [comment] 2019-05-15 13:08
@liamappelbe apps are stored in containers on iOS, so it would make sense to resolve to the absolute path of filesystem + container?

**Comment by lrhn** [comment] 2019-06-06 06:29
The entire "package URI resolution" does not make sense for AOT compilation. It assumes that source files are available at run-time, and then further assumes that other files can be found next to them. This model works fine for programs distirbuted as source, but an AOT-compiled program has no need to replicate the source directory structure anywhere.

One option is to include resources in the binary in a virtual file system, and resolve package URIs for those resources to internal URIs like `dart-resource://packagename/foo/bar.txt`. Some code may fail to handle that because it assumes `file` URIs, but we never promised that.
It does mean that the build step will have to have a way to specify resource files (or maybe just assume that any non-`.dart` file in a `lib/` directory is a resource, but you probably still want to be able to tree-shake resources.

**Comment by ened** [comment] 2019-06-06 06:45
This is starting to sound like code smell for the `Isolate.spawn` mechanism? Why would it require access to resources, by default & thus prevent the spawn itself?

**Comment by lrhn** [comment] 2019-06-06 08:12
The `Isolate.spawn` function should not require anything which is not already available for the cloned isolate. It really should just clone the current isolate's code (reinitializing global variables), and then run the specified function.

It's `Isolate.spawnUri` that is not really meaningful for AOT-compiled code. You have to have a compiled image ready for the given target URI, and you don't actually use that URI for anything except looking up the image. It would make more sense to have a "resource"/"asset" concept, and make compiled isolate images a resource made available by the deployment system, not something referenced by source URI.

**Comment by ened** [comment] 2019-06-27 10:18
@lrhn how to move on from here? Based on your comment and the source code visible at https://api.flutter.dev/flutter/foundation/compute.html, the Flutter `compute` function should simply work?

**Comment by lrhn** [comment] 2019-06-27 10:48
I see no issue in that code either (from a cursory reading), so I'm not sure what you are asking about.

If the `Isolate.resolvePackageUri` function doesn't work, then it's not because of this code, but an underlying issue in the Flutter isolate set-up phase, as discussed above.

**Comment by markusaksli-nc** [comment] 2020-10-02 07:07
Reproducible on the latest master `1.23.0-8.0.pre.105`.
<details>
 <summary>flutter doctor -v</summary>

```
[√] Flutter (Channel master, 1.23.0-8.0.pre.105, on Microsoft Windows [Version 10.0.19041.508], locale en-US)
    • Flutter version 1.23.0-8.0.pre.105 at C:\Development\flutter_master
    • Framework revision f1013e6873 (5 hours ago), 2020-10-02 09:50:33 +0800
    • Engine revision 0522ff22cc
    • Dart version 2.11.0 (build 2.11.0-181.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Users\marku\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.6.5)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.6.30320.27
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.0)
    • Android Studio at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (6 available)
    • SM G950F (mobile)           • ce12171c51cc001c03 • android-arm64  • Android 9 (API 28)
    • sdk gphone x86 arm (mobile) • emulator-5554      • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)           • windows            • windows-x64    • Microsoft Windows [Version 10.0.19041.508]
    • Web Server (web)            • web-server         • web-javascript • Flutter Tools
    • Chrome (web)                • chrome             • web-javascript • Google Chrome 85.0.4183.121
    • Edge (web)                  • edge               • web-javascript • Microsoft Edge 85.0.564.51

• No issues found!
```
</details>

Minimal reproducible code sample

```dart
import 'dart:isolate';
void main()=> Isolate.resolvePackageUri(Uri());
```

**Comment by gahms** [comment] 2020-10-29 15:07
Just to be clear, this missing piece has pretty big implications IMO. The result of missing `Isolate.resolvePackageUri()` is that anything but quite trivial pieces of Dart code cannot be used in background isolates on iOS. 

An non-obvious example is `rootBundle.loadString()` as it uses `compute()` for large (> 10 kB) strings. You will never know when a piece of code will fail at run-time because it deep down, in some low-level Flutter code `compute()` is used.

Missing `Isolate.resolvePackageUri()` also blocks anything but very simple handling of background (data-only) push notifications on iOS. https://github.com/FirebaseExtended/flutterfire/issues/47

Another area is backgrounded downloads. No advanced processing in Dart code can be performed.

Another area is background updates on iOS that also requires a headless background isolate. This can tie in to background update of iOS widgets.

This is all areas where any data load and algorithms held by the main app needs to be re-implemented in native code solely because we cannot generally rely on our Dart code to be able to run in the background.

My point is that a bunch of low-level Flutter code hits this limitation on iOS and it is not at obvious. It is much more broadly applicable than the obscurity of `Isolate.resolvePackageUri()` indicate to me.

**Comment by JetA2** [comment] 2021-05-09 19:01
Is there a workaround for this issue? I'm using `compute` in a background Isolate in response from a request from Apple Watch on iOS and getting the "Unsupported operation: Isolate.resolvePackageUri" error.

**Comment by aam** [comment] 2022-02-25 04:32
like @lrhn said, failing to do `Isolate.spawn` if `resolvePackageUri` is unimplemented(https://github.com/dart-lang/sdk/blob/main/sdk/lib/_internal/vm/lib/isolate_patch.dart#L368) is too harsh - there is no additional source loading needed for it, that uri is only used in diagnostic messages in `Isolate.spawn` flow.

**Comment by aam** [comment] 2022-03-01 17:09
fix, which removes use of `Isolate.resolvePackageUri` from `Isolate.spawn`, should have landed in flutter in https://github.com/flutter/flutter/commit/38455c515f1adf349dc5f74ef8278d85969e58e9

**Closed by aam** 2022-03-01 17:09 UTC
Labels: engine, dependency: dart, customer: crowd, has reproducible steps, P4, found in release: 1.23

**Comment by kuhnroyal** [comment] 2022-03-01 17:12
Awesome work, thanks @aam
