### ISSUE TITLE
DrawerHeader content ignores Container constraints

### ISSUE THREAD

**Issue by DaveShuckerow** [flutter/flutter#4565] opened 2016-06-14 23:47 UTC
I created a Container in a DrawerHeader as follows:

```
      new DrawerHeader(
          background: new Material(color: theme.primaryColor),
              child: new Container(
                  constraints: const BoxConstraints.expand(height: 48.0),
      ...
```

However, the constraints on height are ignored unless I put the Container inside of a Center:

```
      new DrawerHeader(
          background: new Material(color: theme.primaryColor),
          content: new Center(
              widthFactor: 1.0,
              child: new Container(
                  constraints: const BoxConstraints.expand(height: 48.0),
```

Is this happening because DrawerHeader expects its entire size to be filled by its child widget?  If so, is there a way to make this more explicit or to respect the constraints imposed on Container?

**Comment by Hixie** [comment] 2016-06-15 00:39
`Center` tries to grow as big as possible, and gives the child the flexibility to be whatever size it wants. Does that answer your question?

I'm not sure what effect you're trying to get here.

**Comment by DaveShuckerow** [comment] 2016-06-15 00:53
This is related to the view that we discussed offline, with the nested leafs in different shades of green.

**Comment by Hixie** [comment] 2016-06-15 02:39
If you call debugDumpRenderTree() you should be able to see if maybe the drawer header or one of its widgets is setting a tight constraint that's overriding the height constraint you're giving.

**Comment by Hixie** [comment] 2017-01-30 06:46
DrawerHeader does intentionally grow its children to a particular size, but that's because it has a size. You can still Align or Center the children as you wish.

Closing, working as intended.

**Closed by Hixie** 2017-01-30 06:46 UTC
Labels: prod: framework
