### ISSUE TITLE
Migrate example apps and other Flutter projects 

### ISSUE THREAD

**Issue by blasten** [flutter/flutter#102183] opened 2022-04-20 00:04 UTC
There are still a number of example apps that have outdated files.

Specifically, https://github.com/flutter/flutter/pull/88502 changed some manifest files, but there are others like https://github.com/flutter/flutter/blob/master/packages/integration_test/example/android/app/src/main/AndroidManifest.xml that still need this change.

The compileSdkVersion, Gradle and AGP versions are also outdated.

**Comment by blasten** [comment] 2022-04-20 00:05
cc @GaryQian - it would great to use the migration tool here.

**Comment by christopherfujino** [comment] 2022-06-21 21:48
Raising the priority as this is likely causing https://github.com/flutter/flutter/issues/103230 which is a p1.

@GaryQian do you want to try locally using `flutter migrate` on these example apps?

**Comment by GaryQian** [comment] 2022-06-21 22:29
Yeah, let me finish refactoring the migrate start Pr to get back into a working state.

Btw, the migrate resolve-conflicts is ready for review.

**Comment by Hixie** [comment] 2022-07-12 22:58
Reducing back to P3 per @christopherfujino since the flakiness has gone down a lot, but it's quite possible this'll become a higher volume flake again in the future.

**Comment by GaryQian** [comment] 2022-07-12 23:10
Still Pending migrate refactor and landing

**Comment by christopherfujino** [comment] 2023-07-17 16:50
@gmackall I know you made a lot of updates to our example apps, would you say this bug is obsolete?

**Comment by gmackall** [comment] 2023-07-17 17:15
The way the issue is written is pretty general, but I can say that
1. Gradle and AGP versions have been updated in many places (but we still have room to update further)
2. We have added the specific `android:exported` line in some places, including the particular place that was called out in the issue.

I don't know if many `compileSdkVersion`s have been updated in the time since the issue was created. It also seems like the issue might have been written with the `migrate` command in mind, which did not land and has been de-prioritized. 

I can bring this up in the next android triage to see if its close-able currently/would be better to close and open more specific sub-issues.

**Comment by christopherfujino** [comment] 2023-07-17 17:47
> I can bring this up in the next android triage to see if its close-able currently/would be better to close and open more specific sub-issues.

Sounds like a plan. And yeah, I would lean towards more specific sub-issues--as written, it's difficult to determine whether or not this completed.

**Comment by gmackall** [comment] 2023-07-18 17:51
Assigning to myself to make sure I remember it in triage 🙂

**Closed** 2023-07-27 17:30 UTC
Labels: platform-android, d: examples, P2, c: tech-debt, team-android
