### ISSUE TITLE
Firebase Auth PlatformExceptions should be formatted the same on iOS and Android

### ISSUE THREAD

**Issue by mortenboye** [flutter/flutter#15105] opened 2018-03-03 10:20 UTC
When logging in to Firebase Auth with invalid credentials, the fields in the resulting PlatformException containing information about the error, is not filled out the same on iOS and Android.

On Android it looks like:
```
errorCode = "exception"
errorMessage = "There is no user record corresponding to this identifier. The user may have been deleted."
errorDetails = null
```
And on iOS its:
```
errorCode = "Error 17011"
errorMessage = "FIRAuthErrorDomain"
errorDetails = "There is no user record corresponding to this identifier. The user may have been deleted."
```
The values in errorMessage and errorDetails should be aligned between the two platforms.

## Flutter Doctor
```
[✓] Flutter (on Mac OS X 10.12.6 16G1212, locale en-DK, channel beta)
[✓] Android toolchain - develop for Android devices (Android SDK 26.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
[✓] Android Studio (version 3.0)
[✓] IntelliJ IDEA Community Edition (version 2017.2.6)
[✓] Connected devices

• No issues found!
```

**Comment by mortenboye** [comment] 2018-03-04 09:50
The cause of this seems to be

```
@implementation NSError (FlutterError)
- (FlutterError *)flutterError {
  return [FlutterError errorWithCode:[NSString stringWithFormat:@"Error %d", (int)self.code]
                             message:self.domain
                             details:self.localizedDescription];
}
@end
```

or variations thereof, in a number of firebase related plugins.

I tried switching the contents around in a local repo of firebase_auth, but did not see any changes. 
Turns our this particular NSError category implementation was override by the corresponding one in the firebase_storage plugin (FirebaseStoragePlugin.m). My guess is this is because firebase_storage is my last dependency.

**Comment by buntagonalprism** [comment] 2018-06-10 00:50
Any progress on this? Only having a plain text message in the Android PlatformException is frustrating when attempting to handle the errors gracefully. 

The cause on Android is repeated snippets like the following in firebase plugins, such as in [FirebaseAuthPlugin.java](https://github.com/flutter/plugins/blob/master/packages/firebase_auth/android/src/main/java/io/flutter/plugins/firebaseauth/FirebaseAuthPlugin.java)

```java
private static final String ERROR_REASON_EXCEPTION = "exception";

// ...

@Override
public void onComplete(@NonNull Task<AuthResult> task) {
  if (!task.isSuccessful()) {
    Exception e = task.getException();
    result.error(ERROR_REASON_EXCEPTION, e.getMessage(), null);
  } else {
    FirebaseUser user = task.getResult().getUser();
    ImmutableMap<String, Object> userMap = mapFromUser(user);
    result.success(userMap);
  }
}
```
Although I suspect full consistency between Android and iOS might not be possible due to the underlying Firebase platform implementations - it looks like what are handled with error codes like `FIRAuthErrorCodeUserNotFound` in iOS are handled with exceptions in Java like `FirebaseAuthInvalidUserException` 

A more complete list of error codes exists in the [legacy documentation](https://www.firebase.com/docs/android/guide/user-auth.html#section-full-error) than I could find in the [current documentation](https://firebase.google.com/docs/reference/android/com/google/firebase/auth/FirebaseAuthException), but unsure if they are still accurate.

**Comment by HerrNiklasRaab** [comment] 2018-10-11 18:47
Me too!

**Comment by HerrNiklasRaab** [comment] 2018-10-11 18:48
Needed!

**Comment by cyanglaz** [comment] 2019-02-06 22:58
I believe this issue is similar to https://github.com/flutter/flutter/issues/20223 and it was fixed here https://github.com/flutter/plugins/pull/775
I am closing the issue. If any related issue is found, please feel free to reopen it with details.

**Closed by cyanglaz** 2019-02-06 22:58 UTC
Labels: p: firebase, p: firebase_auth, p: first party, plugin

**Comment by kroikie** [comment] 2019-10-13 19:18
@mortenboye

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/897. Any further collaboration will be done there.
