### ISSUE TITLE
[tool_crash] FileSystemException: Cannot create link, OS Error: Incorrect function., errno = 1

### ISSUE THREAD

**Issue by weneverknow** [flutter/flutter#99618] opened 2022-03-06 06:55 UTC
%23%23 Command
```
flutter pub get
```

%23%23 Steps to Reproduce
1. ...
2. ...
3. ...

%23%23 Logs
FileSystemException: Cannot create link, OS Error: Incorrect function.
, errno = 1
```
%230      _Link.throwIfError (dart:io/link.dart:263:7)
%231      _Link.createSync (dart:io/link.dart:184:5)
%232      ForwardingLink.createSync (package:file/src/forwarding/forwarding_link.dart:20:16)
%233      ForwardingLink.createSync (package:file/src/forwarding/forwarding_link.dart:20:16)
%234      _createPlatformPluginSymlinks (package:flutter_tools/src/flutter_plugins.dart:1029:12)
%235      createPluginSymlinks (package:flutter_tools/src/flutter_plugins.dart:964:5)
%236      refreshPluginsList (package:flutter_tools/src/flutter_plugins.dart:1055:5)
<asynchronous suspension>
%237      FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:316:5)
<asynchronous suspension>
%238      PackagesGetCommand.runCommand (package:flutter_tools/src/commands/packages.dart:177:5)
<asynchronous suspension>
%239      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1161:27)
<asynchronous suspension>
%2310     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
%2311     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
%2312     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
<asynchronous suspension>
%2313     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
%2314     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
<asynchronous suspension>
%2315     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
```
```
[✓] Flutter (Channel stable, 2.10.3, on Microsoft Windows [Version 10.0.19044.1466], locale en-US)
    • Flutter version 2.10.3 at F:\Flutter\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (4 days ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\riza\AppData\Local\Android\sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools

**Comment by danagbemava-nc** [comment] 2022-03-07 09:03
Duplicate of #66224

**Closed by danagbemava-nc** 2022-03-07 09:03 UTC
Labels: in triage
