### ISSUE TITLE
Switch keyboard animation is not available on iOS

### ISSUE THREAD

**Issue by luckysmg** [flutter/flutter#92248] opened 2021-10-21 08:19 UTC
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. Tap the `TextField` in the page ,and tap the blank area or `FloatingActionButton` to remove focus

**Expected results:** 

https://user-images.githubusercontent.com/49340347/138239075-32538d57-60cf-4dc3-9ba2-eb6ffd16e97b.MP4

**Actual results:** 

https://user-images.githubusercontent.com/49340347/138238365-bbe09f19-af04-4f60-87b7-fd160448c0f7.MP4

<details>
<summary>Code sample</summary>

```dart

import 'package:device_info_plus/device_info_plus.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  static final DeviceInfoPlugin deviceInfoPlugin = DeviceInfoPlugin();
  Map<String, dynamic> deviceData = <String, dynamic>{};

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const TextFieldPage(),
    );
  }
}

class TextFieldPage extends StatefulWidget {
  const TextFieldPage({Key? key}) : super(key: key);

  @override
  _TextFieldPageState createState() => _TextFieldPageState();
}

class _TextFieldPageState extends State<TextFieldPage> {
  TextEditingController controller = TextEditingController();

  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      onTap: () {
        FocusScope.of(context).unfocus();
      },
      child: Scaffold(
        floatingActionButton: FloatingActionButton(
          onPressed: () {
            FocusScope.of(context).unfocus();
          },
        ),
        body: Center(
          child: SizedBox(
            height: 50,
            child: CupertinoTextField(
              decoration: BoxDecoration(color: Colors.grey[200]),
              controller: controller,
            ),
          ),
        ),
      ),
    );
  }
}
```

**Comment by MrBirb** [comment] 2021-10-21 16:05
Duplicate of #19279 ?

**Closed** 2021-10-21 16:09 UTC
Labels: customer: gold
