### ISSUE TITLE
The intrinsic dimension methods of the RenderFlex class returned values that violate the intrinsic protocol contract.

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#7419] opened 2017-01-10 19:01 UTC
```
I/flutter (23068): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (23068): The following assertion was thrown during performLayout():
I/flutter (23068): The intrinsic dimension methods of the RenderFlex class returned values that violate the intrinsic
I/flutter (23068): protocol contract.
I/flutter (23068): The following failures was detected:
I/flutter (23068):  * getMinIntrinsicHeight(Infinity) returned a non-finite value: NaN
I/flutter (23068):  * getMaxIntrinsicHeight(Infinity) returned a non-finite value: NaN
I/flutter (23068):  * getMinIntrinsicHeight(48.0) returned a non-finite value: NaN
I/flutter (23068):  * getMaxIntrinsicHeight(48.0) returned a non-finite value: NaN
I/flutter (23068): If you are not writing your own RenderBox subclass, then this is not
I/flutter (23068): your fault. Contact support: https://github.com/flutter/flutter/issues/new
I/flutter (23068): 
I/flutter (23068): When the exception was thrown, this was the stack:
I/flutter (23068): #0      RenderBox.debugAssertDoesMeetConstraints.<anonymous closure> (package:flutter/src/rendering/box.dart:1600)
I/flutter (23068): #2      RenderBox.debugAssertDoesMeetConstraints (package:flutter/src/rendering/box.dart:1494)
I/flutter (23068): #3      RenderBox.size=.<anonymous closure> (package:flutter/src/rendering/box.dart:1398)
I/flutter (23068): #5      RenderBox.size= (package:flutter/src/rendering/box.dart:1398)
I/flutter (23068): #6      RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:570)
I/flutter (23068): #7      RenderObject.layout (package:flutter/src/rendering/object.dart:1735)
I/flutter (23068): #8      RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:100)
I/flutter (23068): #9      _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:974)
I/flutter (23068): #10     RenderObject.layout (package:flutter/src/rendering/object.dart:1735)
I/flutter (23068): #11     RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:261)
I/flutter (23068): #12     RenderObject.layout (package:flutter/src/rendering/object.dart:1735)
I/flutter (23068): #13     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:394)
I/flutter (23068): #14     RenderObject.layout (package:flutter/src/rendering/object.dart:1735)
I/flutter (23068): #15     _RenderLayoutBuilder.performLayout (package:flutter/src/widgets/layout_builder.dart:209)
I/flutter (23068): #16     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1611)
I/flutter (23068): #17     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:953)
I/flutter (23068): #18     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding.beginFrame (package:flutter/src/rendering/binding.dart:220)
I/flutter (23068): #19     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding&WidgetsBinding.beginFrame (package:flutter/src/widgets/binding.dart:314)
I/flutter (23068): #20     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:165)
I/flutter (23068): #21     BindingBase&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:652)
I/flutter (23068): #22     BindingBase&SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:587)
I/flutter (23068): #23     _beginFrame (file:///b/build/slave/Linux_Engine/build/src/flutter/lib/ui/hooks.dart:83)
I/flutter (23068): (elided 2 frames from class _AssertionError)
I/flutter (23068): 
I/flutter (23068): The following RenderObject was being processed when the exception was fired:
I/flutter (23068):   RenderFlex NEEDS-LAYOUT
I/flutter (23068):   creator: Column ← ClipRRect ← SizedBox ← SimulatedSizedBox-[GlobalKey 282319772] ← Positioned ←
I/flutter (23068):   SimulatedPositioned-[GlobalKey 61563716] ← StoryPositioned ← Stack ← LayoutBuilder ← Container ←
I/flutter (23068):   StoryPanels ← _InheritedSizeManager ← ⋯
I/flutter (23068):   parentData: <none>
I/flutter (23068):   constraints: BoxConstraints(w=853.3, h=48.0)
I/flutter (23068):   size: Size(853.3, 48.0)
I/flutter (23068):   direction: Axis.vertical
I/flutter (23068):   mainAxisAlignment: MainAxisAlignment.start
I/flutter (23068):   mainAxisSize: MainAxisSize.max
I/flutter (23068):   crossAxisAlignment: CrossAxisAlignment.stretch
I/flutter (23068):   textBaseline: null
I/flutter (23068): This RenderObject had the following descendants (showing up to depth 5):
I/flutter (23068):   RenderPadding relayoutBoundary=up1
I/flutter (23068):     RenderSemanticsGestureHandler relayoutBoundary=up2
I/flutter (23068):       RenderPointerListener relayoutBoundary=up3
I/flutter (23068):         RenderConstrainedBox relayoutBoundary=up4
I/flutter (23068):           RenderDecoratedBox
I/flutter (23068):   RenderFractionallySizedOverflowBox
I/flutter (23068):     RenderDecoratedBox
I/flutter (23068):       RenderFittedBox
I/flutter (23068):         RenderConstrainedBox relayoutBoundary=up1
I/flutter (23068):           _RenderLayoutBuilder
I/flutter (23068): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (23068): Another exception was thrown: The intrinsic dimension methods of the RenderClipRRect class returned values that violate the intrinsic protocol contract.
```

**Comment by apwilson** [comment] 2017-01-10 19:10
Recently clamped some sizes that were going negative to 0.0 and then got this.

**Comment by eseidelGoogle** [comment] 2017-02-23 17:32
I'm not sure how important this is / what milestone it should be in?

**Comment by Hixie** [comment] 2017-12-20 00:26
Without knowing exactly what values it was that caused the problem, it's hard to know how to fix this.

**Comment by Hixie** [comment] 2017-12-20 00:28
I'm going to close this since we have no way to reproduce it.

**Closed by Hixie** 2017-12-20 00:28 UTC
Labels: crash, prod: framework, regression
