### ISSUE TITLE
Memory issue with isolate in Flutter

### ISSUE THREAD

**Issue by hoangquy4897** [flutter/flutter#43623] opened 2019-10-28 10:45 UTC
When I use compute function or isolate in my Flutter app, the memory keep growing linearly then out of memory and my app crashed.

If I don't use compute or isolate, the memory is stable at 40-60mb. Is there anyway to fix this? Or Did I do it wrong? Please help.

**Target Platform: Android
**Target OS version/browser:**
**Devices: Physical devices

## Logs
```
[√] Flutter (Channel stable, v1.7.8+hotfix.4, on Microsoft Windows [Version 10.0.15063], locale en-US)
    • Flutter version 1.7.8+hotfix.4 at C:\src\flutter\flutter
    • Framework revision 20e59316b8 (3 months ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\quy-nh-ttv\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed
      instructions.

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 38.2.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[!] IntelliJ IDEA Community Edition (version 2019.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.1.3
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[!] VS Code (version 1.36.1)
    • VS Code at C:\Users\quy-nh-ttv\AppData\Local\Programs\Microsoft VS Code
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (1 available)
    • SM T295 • R9WM913Y9QJ • android-arm64 • Android 9 (API 28)
```

**Comment by BondarenkoStas** [comment] 2019-10-28 14:55
@hoangquy4897 Can you please try it with current master channel? A possible fix may went with https://github.com/flutter/engine/pull/10068 to 1.10.14

**Comment by hoangquy4897** [comment] 2019-10-28 15:04
Sorry, seem like it not relate with my issue.

**Comment by hoangquy4897** [comment] 2019-10-30 01:55
any help guys?

**Comment by hoangquy4897** [comment] 2019-10-31 06:22
flutter 1.10.14 make the memory not growing linear but it still growing after gc and I feel like it not stable, in the end my app still crash because of out of memory. Sorry I can't post the image memory view here, here is the link of image memory view:

[https://send.firefox.com/download/a092957fff72ec0b/#bZcJwWZFWcmRRIvK3YTFpA](url)

**Comment by chinmaygarde** [comment] 2020-06-15 03:17
This may be related to the old-space Dart heap growing more aggressively because of the presence of additional isolates (I believe each isolate gets its own heap) and not been trimmed as aggressively as we'd like. @dnfield has been working on a similar issue where the old memory is not being collected as aggressively as we'd like. This work is being tracked in https://github.com/flutter/flutter/issues/56482 with on possible solution being documented in flutter.dev/go/downward-memory-pressure.

**Comment by chinmaygarde** [comment] 2020-06-15 03:17
cc @dnfield @rmacnak-google

**Comment by chinmaygarde** [comment] 2020-06-15 03:23
Ok, I believe this is related to / duplicate of https://github.com/flutter/flutter/issues/48360. Closing.

**Closed by chinmaygarde** 2020-06-15 03:23 UTC
Labels: P3, engine, severe: performance
