### ISSUE TITLE
RenderSliverGrid assert on SliverGridLayout too strict

### ISSUE THREAD

**Issue by spkersten** [flutter/flutter#28056] opened 2019-02-16 20:21 UTC
While `SliverGridLayout`'s documentation specifies that

> *The tiles can be placed arbitrarily*, but it is more efficient to place tiles in roughly in order by scroll offset because grids reify a contiguous sequence of children.

`RenderSliverGrid` asserts that `firstChild.layoutOffset <= scrollOffset`, which fails when the first child is offset vertically.

# Minimal example

```dart
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) => MaterialApp(home: Page1());
}

class Page1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: CustomScrollView(
        slivers: <Widget>[
          SliverGrid(
            delegate: SliverChildBuilderDelegate((context, index) => Container(
                  color: Colors.red,
                  margin: EdgeInsets.all(8),
                )),
            gridDelegate: MySliverGridDelegate(),
          )
        ],
      ),
    );
  }
}

class MySliverGridDelegate extends SliverGridDelegate {
  @override
  SliverGridLayout getLayout(SliverConstraints constraints) => MySliverGridLayout();

  @override
  bool shouldRelayout(MySliverGridDelegate oldDelegate) => true;
}

class MySliverGridLayout extends SliverGridLayout {
  @override
  int getMinChildIndexForScrollOffset(double scrollOffset) => 0;

  @override
  int getMaxChildIndexForScrollOffset(double scrollOffset) => 10;

  @override
  SliverGridGeometry getGeometryForChildIndex(int index) {
    final double crossAxisStart = (index % 4) * 80.0;
    return SliverGridGeometry(
      scrollOffset: (index ~/ 4) * 80 + 80 - (index % 4) * 20.0,
      crossAxisOffset: crossAxisStart,
      mainAxisExtent: 80,
      crossAxisExtent: 80,
    );
  }

  @override
  double computeMaxScrollOffset(int childCount) => 50;
}
```

Output:

```
flutter: ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
flutter: The following assertion was thrown during performLayout():
flutter: 'package:flutter/src/rendering/sliver_grid.dart': Failed assertion: line 602 pos 12:
flutter: 'childScrollOffset(firstChild) <= scrollOffset': is not true.
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new?template=BUG.md
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #2      RenderSliverGrid.performLayout (package:flutter/src/rendering/sliver_grid.dart:602:12)
flutter: #3      RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
```

![simulator screen shot - iphone 8 - 2019-02-16 at 21 15 06](https://user-images.githubusercontent.com/4456832/52904714-3f1a0680-3230-11e9-874a-f17cef908f93.png)

The grid looks like I'd expect, so my proposal would be to remove the assert. Unless there's a less strict condition that can be checked. (Maybe that the child *before* firstChild is completely outside of the visible area of the grid?)

```
[✓] Flutter (Channel master, v1.2.2-pre.21, on Mac OS X 10.14.3 18D109, locale en-NL)
    • Flutter version 1.2.2-pre.21 at /Users/spkersten/Development/flutter
    • Framework revision 035e0765cc (8 hours ago), 2019-02-16 01:48:28 -0500
    • Engine revision f37b09a11b
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 c92d5ca288)
```

**Comment by dnfield** [comment] 2020-02-13 22:11
Perhaps we want to just update the assert so that it checks that the child's scroll offset has left it visible on the screen.  I suspect that's the intent, and that the assert was just copypasted from some other widget where this kind of layout could never happen.

@goderbauer @chunhtai @Piinks WDYT?

**Comment by Piinks** [comment] 2020-02-19 22:27
I think removing this assert will be ok. I'm looking into it now. :)

**Comment by Piinks** [comment] 2020-02-20 01:13
After a quick look, so far, as it is, removing this assert seems to open the door for some unexpected behavior.

I took the sample you provided and added another sliver after the grid to help visualize this a bit better:

```dart
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) => MaterialApp(home: Page1());
}

class Page1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: CustomScrollView(
        slivers: <Widget>[
          SliverGrid(
            delegate: SliverChildBuilderDelegate((context, index) {
              return Container(
                color: Colors.red,
                margin: EdgeInsets.all(8),
              );
            }),
            gridDelegate: MySliverGridDelegate(),
          ),
          SliverToBoxAdapter(
            child: Container(
              color: Colors.blue,
              height: 100,
            ),
          )
        ],
      ),
    );
  }
}

class MySliverGridDelegate extends SliverGridDelegate {
  @override
  SliverGridLayout getLayout(SliverConstraints constraints) => MySliverGridLayout();

  @override
  bool shouldRelayout(MySliverGridDelegate oldDelegate) => true;
}

class MySliverGridLayout extends SliverGridLayout {
  @override
  int getMinChildIndexForScrollOffset(double scrollOffset) => 0;

  @override
  int getMaxChildIndexForScrollOffset(double scrollOffset) => 3;

  @override
  SliverGridGeometry getGeometryForChildIndex(int index) {
    final double crossAxisStart = (index % 4) * 80.0;
    return SliverGridGeometry(
      scrollOffset: (index ~/ 4) * 80 + 80 - (index % 4) * 20.0,
      crossAxisOffset: crossAxisStart,
      mainAxisExtent: 80,
      crossAxisExtent: 80,
    );
  }

  @override
  double computeMaxScrollOffset(int childCount) => 50;
}
```

By adding this follow up sliver, we can see that the grid ends up overlapping it visually, and further more, scrolls in a funny way where the grid scrolls over the blue sliver until they line up and scroll together.

Also, with or without the blue sliver after the grid, it appears to scroll infinitely. When the blue sliver is included, it sticks to the top, but it continues to scroll infinitely. I captured this below where I have to scroll way up to find the grid again.

![ezgif com-optimize](https://user-images.githubusercontent.com/16964204/74890963-6ff8b400-533a-11ea-803d-0cf60d66a926.gif)


This assert does seem intentional. I have checked the other render objects that use a [`RenderSliverBoxChildManager`](https://api.flutter.dev/flutter/rendering/RenderSliverBoxChildManager-class.html), and it does not appear that this assert came from a copy paste. The git history does not provide much help either, as this assert was present when `SliverGrid` was created. The documentation seem to be wrong here regarding arbitrary placement.

I think staggered grids like this can work, although I am not sure what would need to be changed at this precise moment.

I can continue to look into this, although I am curious to know what others think. 

What would you expect the behavior to be in the situations above? 
I have seen packages that create staggered grids, could  there already be an existing solution in that case?

**Comment by spkersten** [comment] 2020-02-20 10:49
@Piinks I think that the infinite scrolling results from the hardcoded value returned by `computeMaxScrollOffset` in my example. (I didn't think that was needed to show the issue.) I believe that the overlapping is similarly a result of my crude example.

I'm attempting to create a reorderable `SliverGrid` which animates the tiles to their new positions while the user drags a tile over the grid. For example like this:
![https://i.stack.imgur.com/AQaL6.gif](https://i.stack.imgur.com/AQaL6.gif)

My current approach is to use the `SliverGridDelegate` wrapper to change (and animate) the positions of the cards in the grid. The assert failed in an early version when I dragged the first card, which was then shown not as the first along the main axis. I can probably avoid doing this, but generally it would be nice if the framework wouldn't impose unnecessary limitations (of course, while still having asserts where it helps :) ).

**Comment by Piinks** [comment] 2020-02-20 18:34
Hey @spkersten thanks for the update! I have some more thoughts, let me know what you think! :relaxed:

> I'm attempting to create a reorderable `SliverGrid` which animates the tiles to their new positions while the user drags a tile over the grid. 

Are you able to provide a reproduction for this use case?
  
<br>

I also did a quick search and found a few packages that do animated reorder-able grids if its helpful: 
- https://pub.dev/packages/dragablegridview_flutter
- https://pub.dev/packages/reorderables

<br>

I noticed the Flutter doctor provided above is version 1.2, is this reproducing on master for your reorder-able animated `SliverGrid`? 

It sounds like this might be similar to #42142, where the `layoutOffset` of the `firstChild` is incorrect, causing issues when children are rearranged. @chunhtai is working on a fix for that in #42703. We can see if something similar is happening here with a reproduction.

<br>

> The assert failed in an early version when I dragged the first card, which was then shown not as the first along the main axis.

You mentioned running into this in an earlier version, does this mean you are not experiencing this anymore, or that you found a workaround?

> it would be nice if the framework wouldn't impose unnecessary limitations (of course, while still having asserts where it helps :) ).

I don't know that we have proven this assert is unnecessary. While the reproduction provided above may not be a real use case, it does look like an example of the assert doing its job.

**Comment by spkersten** [comment] 2020-02-24 12:45
@Piinks I don't have anything more to share yet. I was exploring options when I encountered this issue and reported it, hoping it would be fixed by the time I needed to make a proper implementation. On that, I will work this week.

> You mentioned running into this in an earlier version, does this mean you are not experiencing this anymore, or that you found a workaround?

Yes, I think I can work around it.

> I also did a quick search and found a few packages that do animated reorder-able grids if its helpful:
> 
> - https://pub.dev/packages/dragablegridview_flutter
> - https://pub.dev/packages/reorderables

Neither offers a reorderable `SliverGird` but they might provide some more inspiration. Thanks.

**Comment by spkersten** [comment] 2020-02-25 12:32
@Piinks update: The issue still still relevant and working around it is more cumbersome than I expected (wrapping `SliverChildDelegate` and adding a zero size dummy widget at the start).

**Comment by spkersten** [comment] 2020-03-04 14:21
@Piinks I have created a repo with the SliverReorderableGrid I created including an example here: https://github.com/spkersten/sliver_draggables

You can observe the issue of this ticker by making the window short enough so there is only a single row and dragging an item to the first spot:
![ezgif-6-09a8e01c38a6](https://user-images.githubusercontent.com/4456832/75888484-badef500-5e2b-11ea-9fe4-000400734748.gif)
(I used latest master)

I'm also very interested in any other feedback on the code. I think it reveals several shortcomings of Flutter's existing `Draggable` and `DragTarget`.

**Comment by Piinks** [comment] 2020-08-18 17:08
A duplicate issue has been filed for this, and it has been escalated: https://github.com/flutter/flutter/issues/64006
I am going to close this one since the escalated one is under higher priority review.

**Closed by Piinks** 2020-08-18 17:08 UTC
Labels: P4, customer: solaris, f: scrolling, framework, severe: crash

**Comment by aytunch** [comment] 2020-08-18 17:18
Ccvt
Vf(( f

On 18 Aug 2020 Tue at 20:08 Kate Lovett <notifications@github.com> wrote:f
