### ISSUE TITLE
hot_mode_dev_cycle_linux__benchmark is showing a regression after the post 1.7 Dart BE roll

### ISSUE THREAD

**Issue by a-siva** [flutter/flutter#35551] opened 2019-07-03 21:04 UTC
Starting with
https://github.com/flutter/flutter/commit/3a674421299e9a90700e7e23b6112f04c7687c61
the hot_mode_dev_cycle_linux__benchmark is showing a regression of about 161 ms.

The CL contains a Dart BE roll https://github.com/flutter/engine/pull/9588 after a gap of about 2-3 weeks, the roll has about 435 commits to the Dart repo.
A bisect through these commits is needed now to identify the cause for this performance regression.

**Comment by tvolkert** [comment] 2019-07-12 19:56
What's the current status of this?  Have we identified the culprit yet?  It's been 10 days since the regression hit.

**Comment by a-siva** [comment] 2019-07-12 19:59
Not yet, I am still bisecting the changes to find the culprit.

**Comment by a-siva** [comment] 2019-07-15 18:18
The regression appears to be because of this change in Dart
dart-lang/sdk@d47bb87 [vm, compiler] Disable unopt megamorphic call specialization.
Renabling this option in the engine fixes the regressions and confirms that this change caused the regression.

**Comment by a-siva** [comment] 2019-07-15 18:22
We would like for this option to be used consistently in the command like Dart VM and the engine and so turning the option on in the engine would not be the right fix. We will turn it on by default in the VM and the next Dart roll into flutter would pick it up. We would need to reevaluate the dart2js regression because of which the option was turned off.

**Comment by Hixie** [comment] 2019-07-16 23:10
How does the flag in the engine or in the VM affect dart2js?

**Comment by a-siva** [comment] 2019-07-17 02:05
The flag in the engine does not affect dart2js but we don't want this flag to be turned on in the engine instead we want it to be on by default in the VM.

**Comment by Hixie** [comment] 2019-07-24 00:04
@a-siva says the change in the flag has landed. I presume this means we're waiting for a dart roll and engine roll to see the change in the benchmarks?

**Comment by a-siva** [comment] 2019-07-24 00:14
dart roll with the change has landed in the engine and the hot_mode_dev_cycle_linux__benchmark now shows a time of 1291 ms.

**Comment by tvolkert** [comment] 2019-07-24 00:58
It's still averaging 100-200 ms slower than it was before 3a67442.  Are we still  driving this back down  to where it was?

**Comment by jason-simmons** [comment] 2019-07-26 00:48
I tried bisecting this, and it looks like the change in hot reload cycle time started with https://github.com/dart-lang/sdk/commit/1e24fe7d699a1c36be142afa21859c6a9c82d035

Setting `unopt_megamorphic_calls=true` improves the cycle time but doesn't match the results prior to that commit.

**Comment by franciscojma86** [comment] 2019-07-31 22:58
This metric is still regressing, has there been any progress?

**Comment by a-siva** [comment] 2019-08-01 03:22
The benchmark turned green after we turned back the unopt megamorphic call specialization, but it did have a 100-200 ms difference which we are still investigating.

**Comment by Hixie** [comment] 2019-08-01 17:26
@a-siva Any news on this issue?

**Comment by tvolkert** [comment] 2019-08-01 18:27
Can we back out the culprit while we investigate?

**Comment by a-siva** [comment] 2019-08-07 04:40
We did back out the change but that did not get back all the performance. We are now profiling the reload path to see if we can get back the 200 ms difference.

**Comment by aam** [comment] 2019-08-09 16:50
monomorphic/megamorphic call specialization introduced in https://github.com/dart-lang/sdk/commit/1e24fe7d699a1c36be142afa21859c6a9c82d035 changes how method calls are counted towards being optimized, so the code is getting optimized at slightly different times(can be sooner or later).
This particular benchmark seems to be affected by code(package:flutter/src/widgets/framework.dart_Element_ancestorWidgetOfExactType) _not_ being optimized for the short duration of this benchmark(the benchmark loads flutter gallery, reloads it once with no changes, then changes caption from 'Flutter Gallery' to 'Updated Flutter Gallery', reloads it again and measure how long second reload took).

**Comment by Hixie** [comment] 2019-08-09 16:54
Awesome! Thanks for tracking it down!

**Comment by tvolkert** [comment] 2019-08-09 16:56
Thanks!  Is the benchmark operation not indicative of real user experiences, or did it catch real cases where UX took a hit?  If the former, is there a way we can/should change the benchmark operation to better capture real user experiences?

**Comment by aam** [comment] 2019-08-09 17:30
> Is the benchmark operation not indicative of real user experiences, or did it catch real cases where UX took a hit? If the former, is there a way we can/should change the benchmark operation to better capture real user experiences?

Measuring impact of the optimizations on real user experience is hard - in this particular case it depends on amount of code changed for hot reload(in this case we are changing just single string literal), when you requested reload(how long the app ran, since last reload was requested), composition of the app(how much code is actually executed/optimized).

I think hotReloadMillisecondsToFrameAfterChange is reasonable basic benchmark. It's just that Flutter performance on this benchmark should be looked at in context of other benchmarks - for example hotReloadMillisecondsToFrame improved - second chart at the bottom(that is first hot reload without any changes).
Having more benchmarks(changing class structures, introducing new classes, deleting existing classes) will provide even better sense of real world UX.

![rmYFifnZD2k](https://user-images.githubusercontent.com/381137/62797337-5673d700-ba90-11e9-8f5b-7cfd344bd6f7.png)
![wjiYPfCjnFN](https://user-images.githubusercontent.com/381137/62797342-583d9a80-ba90-11e9-885f-0d66c0dfdad0.png)

**Comment by tvolkert** [comment] 2019-08-09 18:10
sg - thanks!

So it sounds like we should re-baseline hotReloadMillisecondsToFrameAfterChange?

**Comment by aam** [comment] 2019-08-09 18:21
> So it sounds like we should re-baseline hotReloadMillisecondsToFrameAfterChange?

Yes. Rebaselined.

**Closed** 2019-08-09 18:26 UTC
Labels: customer: crowd, dependency: dart, severe: customer blocker, severe: performance

**Comment by a-siva** [comment] 2019-08-21 17:57
The change 9ae1d02537 [vm] Reduce Code::ResetSwitchableCalls from quadratic to log-linear time by rmacnak@ has reclaimed the 150-200 ms degradation we saw earlier.

![image](https://user-images.githubusercontent.com/8633293/63455862-7a290c80-c402-11e9-9ecc-7043db7a8807.png)

**Comment by tvolkert** [comment] 2019-08-21 18:48
Thanks @a-siva! I've re-baselined the benchmark.
