### ISSUE TITLE
use canvas some drawRect, between of them have seam

### ISSUE THREAD

**Issue by liu1013269528** [flutter/flutter#89639] opened 2021-09-08 08:44 UTC
I'm trying make a pixel app, when i use canvas draw some Rect, There will be a gap
`
class PaperPainter extends CustomPainter {
  final Map<String, Point> pointList;
  final double pixelLength;
  PaperPainter({required this.pixelLength, required this.pointList});
  @override
  void paint(Canvas canvas, Size size) {
    Paint paint = new Paint() //设置笔的属性
      ..strokeCap = StrokeCap.square
      ..isAntiAlias = true
      ..style = PaintingStyle.fill
      ..color = Colors.black
      ..blendMode = BlendMode.clear
      ..strokeWidth = 1;
    double errorLength = 0.01;
    canvas.drawRect(Rect.fromLTWH(0, 0, 20, 20), paint);
    canvas.drawRect(Rect.fromLTWH(0, 20, 20, 20), paint);
    canvas.drawRect(Rect.fromLTWH(20, 0, 20, 20), paint);
    canvas.drawRect(Rect.fromLTWH(20, 20, 20, 20), paint);
  }

  @override
  // bool shouldRepaint(CustomPainter oldDelegate) => true;
  @override
  bool shouldRepaint(covariant PaperPainter oldDelegate) =>
      oldDelegate.pointList != pointList || oldDelegate.pixelLength != pixelLength;
}
`
![image](https://user-images.githubusercontent.com/11382555/132476653-8a9496bb-82c4-40ec-8e51-33dc4262586a.png)

**Comment by TahaTesser** [comment] 2021-09-08 09:38
Hi @liu1013269528 
This is an Antialiasing issue
Closing as duplicate of https://github.com/flutter/flutter/issues/14288

**Closed by TahaTesser** 2021-09-08 09:38 UTC
Labels: in triage
