### ISSUE TITLE
crash report when creating first app on VS code

### ISSUE THREAD

**Issue by ndlive** [flutter/flutter#18762] opened 2018-06-24 04:25 UTC
## Steps to Reproduce

Hello there,
im having trouble when creating my first app on Visual Studio.
is there anyone could help?
thank you 

regards 
Zai

## Logs

```
[first_app] flutter create first_app
Waiting for another flutter command to release the startup lock...
Creating project first_app...
  first_app\.gitignore (created)

Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Crash report sent (report ID: 14a761dad3f39ee6)
Crash report written to C:\Users\LIVEW\AppData\Local\Temp\flutter_07.log;
please let us know at https://github.com/flutter/flutter/issues.
exit code 1
```

```
[first_app] flutter create first_app
Waiting for another flutter command to release the startup lock...
Creating project first_app...
  first_app\.gitignore (created)

Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Crash report sent (report ID: 14a761dad3f39ee6)
Crash report written to C:\Users\LIVEW\AppData\Local\Temp\flutter_07.log;
please let us know at https://github.com/flutter/flutter/issues.
exit code 1
```

**Comment by jonahwilliams** [comment] 2018-06-24 07:03
@ndlive could you include the log that shows the error message and your flutter version?

**Comment by ndlive** [comment] 2018-06-24 08:03
Hello Jonah,
thank you for your reply.
the problem solved, it was blocked by windows firewall.
but the flutter doctor still can not detect VS code (ss attached)
thank you

best wishes
Olivia

**Comment by escamoteur** [comment] 2018-06-24 11:44
@ndlive have you also installed the Flutter plugin besides DartCode? this is now necessary to get detected

**Comment by DanTup** [comment] 2018-07-19 10:13
@ndlive If you can still reproduce the first issue, it would be great to see what's in the log file mentioned in the error message (`C:\Users\LIVEW\AppData\Local\Temp\flutter_07.log` in the case above). Even if the issue is caused by Windows Firewall, we shouldn't crash like that, we should provide a better error message to the user.

> but the flutter doctor still can not detect VS code (ss attached)

As @escamoteur says, you need the Flutter plugin; but there's also a bug in the current `beta` channel that generates an incorrect report here. The fix will be in an future update.

(Closing this since issues ares resolved, but please do still post a log for the crash if you can).

**Closed by DanTup** 2018-07-19 10:13 UTC
