### ISSUE TITLE
[tool_crash] FormatException

### ISSUE THREAD

**Issue by Junkmer** [flutter/flutter#157511] opened 2024-10-24 15:08 UTC
## Command
```sh
flutter --no-color run --machine --track-widget-creation --device-id=83b76f3a --start-paused --dart-define=flutter.inspector.structuredErrors=true lib\main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FormatException
```console
#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1465:5)
#1      _ChunkedJsonParser.parseNumber (dart:convert-patch/convert_patch.dart:1332:9)
#2      _ChunkedJsonParser.parse (dart:convert-patch/convert_patch.dart:933:22)
#3      _JsonStringDecoderSink.addSlice (dart:convert-patch/convert_patch.dart:1551:13)
#4      _JsonStringDecoderSink.add (dart:convert-patch/convert_patch.dart:1556:5)
#5      _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:69:18)
#6      _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:111:24)
#7      _rootRunUnary (dart:async/zone.dart:1407:47)
#8      _CustomZone.runUnary (dart:async/zone.dart:1308:19)
#9      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217:7)
#10     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:365:11)
#11     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:297:7)
#12     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:63:11)
#13     _EventSinkWrapper.add (dart:async/stream_transformers.dart:13:11)
#14     _StringAdapterSink.add (dart:convert/string_conversion.dart:228:11)
#15     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:233:7)
#16     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:307:20)
#17     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:300:5)
#18     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:69:18)
#19     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:111:24)
#20     _rootRunUnary (dart:async/zone.dart:1407:47)
#21     _CustomZone.runUnary (dart:async/zone.dart:1308:19)
#22     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217:7)
#23     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:365:11)
#24     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:297:7)
```
```console
[✓] Flutter (Channel master, 3.24.0-1.0.pre.528, on Microsoft Windows [版本 10.0.22631.4317], locale zh-CN)
    • Flutter version 3.24.0-1.0.pre.528 on channel master at D:\Junker\Flutter\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 493c453d57 (3 months ago), 2024-08-09 12:53:15 +0200
    • Engine revision c9ec468c75
    • Dart version 3.6.0 (build 3.6.0-131.0.dev)
    • DevTools version 2.38.0
    • Pub download mirror https://pub.flutter-io.cn

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at D:\Junker\MyProject\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: D:\Junker\zzzzzzTest\android-studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 21.0.3+-12099254-b509.4)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.11.5)
    • Visual Studio at D:\Junker\Microsoft\Visual Studio
    • Visual Studio Community 2022 version 17.11.35327.3
    • Windows 10 SDK version 10.0.22621.0

[✓] Android Studio (version 2024.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0--11852314)

[✓] Android Studio (version 2024.2)
    • Android Studio at D:\Junker\zzzzzzTest\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.3+-12099254-b509.4)

[✓] Connected device (4 available)
    • MI 9 (mobile)     • 83b76f3a • android-arm64  • Android 11 (API 30)
    • Windows (desktop) • windows  • windows-x64    • Microsoft Windows [版本 10.0.22631.4317]
    • Chrome (web)      • chrome   • web-javascript • Google Chrome 130.0.6723.59
    • Edge (web)        • edge     • web-javascript • Microsoft Edge 130.0.2849.46

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: master
**Creation framework version**: 493c453d578054912fd7eca655de71ab437e3ce0
### Plugins
path_provider-2.1.4
path_provider_android-2.2.10
path_provider_foundation-2.4.0
path_provider_linux-2.2.1
path_provider_windows-2.3.0
tencent_cloud_chat_sdk-8.2.6325+1

**Comment by danagbemava-nc** [comment] 2024-10-25 06:54
Closing this as a duplicate of https://github.com/flutter/flutter/issues/98905

**Closed by danagbemava-nc** 2024-10-25 06:54 UTC
Labels: in triage
