### ISSUE TITLE
[tool_crash] FileSystemException: Cannot create link, OS Error: Incorrect function., errno = 1

### ISSUE THREAD

**Issue by ahmadxpanahi** [flutter/flutter#111036] opened 2022-09-06 16:05 UTC
## Command
```
flutter --no-color pub upgrade
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Cannot create link, OS Error: Incorrect function.
, errno = 1
```
#0      _Link.throwIfError (dart:io/link.dart:263:7)
#1      _Link.createSync (dart:io/link.dart:184:5)
#2      ForwardingLink.createSync (package:file/src/forwarding/forwarding_link.dart:20:16)
#3      ForwardingLink.createSync (package:file/src/forwarding/forwarding_link.dart:20:16)
#4      _createPlatformPluginSymlinks (package:flutter_tools/src/flutter_plugins.dart:1057:12)
#5      createPluginSymlinks (package:flutter_tools/src/flutter_plugins.dart:987:5)
#6      refreshPluginsList (package:flutter_tools/src/flutter_plugins.dart:1089:5)
<asynchronous suspension>
#7      FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:350:5)
<asynchronous suspension>
#8      PackagesInteractiveGetCommand.runCommand (package:flutter_tools/src/commands/packages.dart:355:5)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1209:27)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#11     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
<asynchronous suspension>
#15     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
```
```
[✓] Flutter (Channel stable, 3.3.0, on Microsoft Windows [Version 10.0.19043.1806], locale en-US)
    • Flutter version 3.3.0 on channel stable at G:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffccd96b62 (8 days ago), 2022-08-29 17:28:57 -0700
    • Engine revision 5e9e0e0aa8
    • Dart version 2.18.0
    • DevTools version 2.15.0

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at G:/Android sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = G:/Android sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✗] Visual Studio - develop for Windows
    ✗ Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[✓] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] Connected device (4 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 8.1.0 (API 27) (emulator)
    • Windows (desktop)                  • windows       • windows-x64    • Microsoft Windows [Version 10.0.19043.1806]
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 104.0.5112.102
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 105.0.1343.27

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 77d935af4db863f6abd0b9c31c7e6df2a13de57b
### Plugins
audio_session-0.1.10
audioplayers-0.20.1
file_picker-5.0.1
flutter_image_compress-1.1.2
flutter_keyboard_visibility-5.3.0
flutter_keyboard_visibility_web-2.0.0
flutter_local_notifications-9.9.1
flutter_plugin_android_lifecycle-2.0.7
image_cropper-3.0.0
image_cropper_for_web-1.0.2
image_gallery_saver-1.7.1
just_audio-0.9.28
just_audio_web-0.4.7
libphonenumber-2.0.2
libphonenumber_plugin-0.2.3
libphonenumber_web-0.2.0+1
package_info_plus-1.4.3+1
package_info_plus_linux-1.0.5
package_info_plus_macos-1.3.0
package_info_plus_web-1.0.5
package_info_plus_windows-2.1.0
path_provider-2.0.11
path_provider_android-2.0.20
path_provider_ios-2.0.11
path_provider_linux-2.1.7
path_provider_macos-2.0.6
path_provider_windows-2.1.3
share_plus-4.1.0
share_plus_linux-3.0.0
share_plus_macos-3.0.1
share_plus_web-3.0.1
share_plus_windows-3.0.1
sqflite-2.0.3+1
syncfusion_flutter_pdfviewer-20.2.48-beta
syncfusion_pdfviewer_macos-20.2.48-beta
syncfusion_pdfviewer_web-20.2.48-beta
syncfusion_pdfviewer_windows-20.2.48-beta
system_settings-2.1.0
url_launcher-6.1.5
url_launcher_android-6.0.17
url_launcher_ios-6.0.17
url_launcher_linux-3.0.1
url_launcher_macos-3.0.1
url_launcher_web-2.0.13
url_launcher_windows-3.0.1
video_compress-3.1.1
video_player-2.4.7
video_player_android-2.3.9
video_player_avfoundation-2.3.5
video_player_web-2.0.12
webview_flutter-2.8.0
webview_flutter_android-2.10.0
webview_flutter_wkwebview-2.9.3

**Comment by iapicca** [comment] 2022-09-06 17:21
possibly related to https://github.com/flutter/flutter/issues/66224

**Comment by exaby73** [comment] 2022-09-06 18:05
Hi @ahmadxpanahi
This indeed does look like a duplicate of https://github.com/flutter/flutter/issues/66224
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by exaby73** 2022-09-06 18:05 UTC
Labels: in triage
