### ISSUE TITLE
Changing the `SystemUiMode` results in a stuttery keyboard opening animation on Android

### ISSUE THREAD

**Issue by iamcosmin** [flutter/flutter#109623] opened 2022-08-16 17:51 UTC
When changing the system ui mode using `SystemChrome.setEnabledSystemUIMode`, the keyboard opening animation is stuttery on devices that support the new smooth keyboard animation (I think starting Android 11, though I am encountering this bug on Android 12).
This issue can be reproduced in both latest stable and latest beta.

## Steps to reproduce
1. Run the code sample provided below on an Android device, preferably running Android 12 and using profile mode (to see the stutter more clearly).
2. Switch through the different `SystemUiMode`s using the provided top buttons.
3. Press on the `TextFormField` placed in the middle of the app and observe the bottom red bar animating with the keyboard opening.

### Expected results
- The whole bottom red bar is on the top of the keyboard during the entrance animation, without a sudden stutter in all the provided states.

### Actual results
- When in the `Default` state, the bottom red bar is animating smoothly with the entrance of the keyboard, no stutters, as expected.
- When in the other modes, you can observe that, while animating, a part of the bottom red bar is not visible, but towards the end, the bottom red bar suddenly and abruptly reappears in its full shape on the screen, resulting in a stuttery experience.

I'm thinking this is because of some bottom insets evaluation errors when running in a different from default `SystemUiMode`.

<details>
 <summary>Code sample</summary>

``` dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() {
  WidgetsFlutterBinding.ensureInitialized();

  // I discovered this bug when I wanted to make the color of the system navigation bar reflect the
  // modern android behavior: showing the scaffold color.
  // This is why I made the navigation bar transparent here. Though, this line is not necesarry
  // in the reproduction of this bug.
  SystemChrome.setSystemUIOverlayStyle(
    const SystemUiOverlayStyle(
      systemNavigationBarColor: Colors.transparent,
    ),
  );
  runApp(const App());
}

class App extends StatelessWidget {
  const App({super.key});

  @override
  Widget build(context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(title: const Text('Keyboard Stutter')),
        body: Padding(
          padding: const EdgeInsets.fromLTRB(10, 10, 10, 0),
          child: Column(
            children: [
              Wrap(
                spacing: 10,
                children: [
                  // Here is the deal. Setting any SystemUIMode other than the default one induces
                  // this bug.
                  ElevatedButton(
                    onPressed: () {
                      SystemChrome.setEnabledSystemUIMode(
                        SystemUiMode.manual,
                        overlays: SystemUiOverlay.values,
                      );
                    },
                    child: const Text('Default'),
                  ),
                  ElevatedButton(
                    onPressed: () {
                      SystemChrome.setEnabledSystemUIMode(
                        SystemUiMode.edgeToEdge,
                      );
                    },
                    child: const Text('Edge to Edge'),
                  ),
                  ElevatedButton(
                    onPressed: () {
                      SystemChrome.setEnabledSystemUIMode(
                        SystemUiMode.immersive,
                      );
                    },
                    child: const Text('Immersive'),
                  ),
                  ElevatedButton(
                    onPressed: () {
                      SystemChrome.setEnabledSystemUIMode(
                        SystemUiMode.immersiveSticky,
                      );
                    },
                    child: const Text('Immersive Sticky'),
                  ),
                  ElevatedButton(
                    onPressed: () {
                      SystemChrome.setEnabledSystemUIMode(
                        SystemUiMode.leanBack,
                      );
                    },
                    child: const Text('Leanback'),
                  ),
                ],
              ),
              Expanded(
                child: Align(
                  child: TextFormField(
                    decoration: const InputDecoration(
                      labelText:
                          'Focus on this TextField and observe the bottom.',
                      border: OutlineInputBorder(),
                    ),
                  ),
                ),
              ),
              SizedBox.fromSize(
                size: const Size.fromHeight(50),
                child: const ColoredBox(
                  color: Colors.red,
                  child: Center(
                    child: Text('Observe the behavior of this bar.'),
                  ),
                ),
              )
            ],
          ),
        ),
      ),
    );
  }
}
```
</details>

### Reproduction of the bug
Here is a recording of the bug being reproduced.

https://user-images.githubusercontent.com/47219753/184942814-a6fdd0e1-3a90-482e-94b9-2f98cdc363ab.mp4

## Debug info
<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel beta, 3.3.0-0.3.pre, on Microsoft Windows [Version 10.0.22622.575], locale ro-RO)
    • Flutter version 3.3.0-0.3.pre on channel beta at C:\Users\iamco\fvm\default
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 8c1149878b (6 days ago), 2022-08-10 12:15:36 -0500
    • Engine revision f16e757d5d
    • Dart version 2.18.0 (build 2.18.0-271.4.beta)
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at C:\Users\iamco\AppData\Local\Android\sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2022 17.2.6)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.2.32630.192
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[✓] VS Code (version 1.70.1)
    • VS Code at C:\Users\iamco\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.44.0

[✓] Connected device (4 available)
    • SM A528B (mobile) • 12.21.11.122:45699 • android-arm64  • Android 12 (API 31)
    • Windows (desktop) • windows            • windows-x64    • Microsoft Windows [Version 10.0.22622.575]
    • Chrome (web)      • chrome             • web-javascript • Google Chrome 104.0.5112.81
    • Edge (web)        • edge               • web-javascript • Microsoft Edge 104.0.1293.54

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

Also, a small nit: when using `SystemUiMode.edgeToEdge`, and at the same time having gesture navigation enabled in my Android's settings, in the code sample provided, the entire app UI kind of just slides behind the navigation bar? (you can observe this on the provided recording when selecting `Edge to Edge`). An easy solution would be to put a `SafeArea` widget as a parent of the `Column` and child of `Scaffold`, but you would assume that `Scaffold` already rocks `SafeArea` under the hood. I don't know, it seems strange, though I did not want to make a separate issue because I thought it's not that big of a deal. Though, if you want me to report this as a separate issue, I will happily do so.

Thank you!

**Comment by exaby73** [comment] 2022-08-16 20:12
I can reproduce this issue on stable and master channels

<details>
<summary>Video</summary>

https://user-images.githubusercontent.com/50555895/184974571-8b7bf9a9-9243-47f1-a701-e439622bff7f.mp4

</details>

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() {
  WidgetsFlutterBinding.ensureInitialized();

  // I discovered this bug when I wanted to make the color of the system navigation bar reflect the
  // modern android behavior: showing the scaffold color.
  // This is why I made the navigation bar transparent here. Though, this line is not necesarry
  // in the reproduction of this bug.
  SystemChrome.setSystemUIOverlayStyle(
    const SystemUiOverlayStyle(
      systemNavigationBarColor: Colors.transparent,
    ),
  );
  runApp(const App());
}

class App extends StatelessWidget {
  const App({Key? key}) : super(key: key);

  @override
  Widget build(context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(title: const Text('Keyboard Stutter')),
        body: Padding(
          padding: const EdgeInsets.fromLTRB(10, 10, 10, 0),
          child: Column(
            children: [
              Wrap(
                spacing: 10,
                children: [
                  // Here is the deal. Setting any SystemUIMode other than the default one induces
                  // this bug.
                  ElevatedButton(
                    onPressed: () {
                      SystemChrome.setEnabledSystemUIMode(
                        SystemUiMode.manual,
                        overlays: SystemUiOverlay.values,
                      );
                    },
                    child: const Text('Default'),
                  ),
                  ElevatedButton(
                    onPressed: () {
                      SystemChrome.setEnabledSystemUIMode(
                        SystemUiMode.edgeToEdge,
                      );
                    },
                    child: const Text('Edge to Edge'),
                  ),
                  ElevatedButton(
                    onPressed: () {
                      SystemChrome.setEnabledSystemUIMode(
                        SystemUiMode.immersive,
                      );
                    },
                    child: const Text('Immersive'),
                  ),
                  ElevatedButton(
                    onPressed: () {
                      SystemChrome.setEnabledSystemUIMode(
                        SystemUiMode.immersiveSticky,
                      );
                    },
                    child: const Text('Immersive Sticky'),
                  ),
                  ElevatedButton(
                    onPressed: () {
                      SystemChrome.setEnabledSystemUIMode(
                        SystemUiMode.leanBack,
                      );
                    },
                    child: const Text('Leanback'),
                  ),
                ],
              ),
              Expanded(
                child: Align(
                  child: TextFormField(
                    decoration: const InputDecoration(
                      labelText:
                      'Focus on this TextField and observe the bottom.',
                      border: OutlineInputBorder(),
                    ),
                  ),
                ),
              ),
              SizedBox.fromSize(
                size: const Size.fromHeight(50),
                child: const ColoredBox(
                  color: Colors.red,
                  child: Center(
                    child: Text('Observe the behavior of this bar.'),
                  ),
                ),
              )
            ],
          ),
        ),
      ),
    );
  }
}
```

</details>

<details><summary><code>flutter doctor -v</code> (Stable)</summary>

```
[✓] Flutter (Channel stable, 3.0.5, on Microsoft Windows [Version 10.0.22000.856], locale en-IN)
    • Flutter version 3.0.5 at C:\Users\Nabeel Parkar\fvm\versions\stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (5 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\android-sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2022 17.2.6)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.2.32630.192
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2022.2
    • Flutter plugin version 69.0.5
    • Dart plugin version 222.3345.108

[✓] VS Code (version 1.70.1)
    • VS Code at C:\Users\Nabeel Parkar\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.46.0

[✓] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 13 (API 33) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.22000.856]
    • Chrome (web)                 • chrome        • web-javascript • unknown
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 104.0.1293.54

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

<details><summary><code>flutter doctor -v</code> (Master)</summary>

```
[✓] Flutter (Channel master, 3.1.0-0.0.pre.2301, on Microsoft Windows [Version 10.0.22000.856], locale en-IN)
    • Flutter version 3.1.0-0.0.pre.2301 on channel master at C:\Users\Nabeel Parkar\fvm\versions\master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ff9fe35682 (68 minutes ago), 2022-08-16 11:22:45 -0700
    • Engine revision db741c85ad
    • Dart version 2.19.0 (build 2.19.0-100.0.dev)
    • DevTools version 2.16.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\android-sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2022 17.2.6)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.2.32630.192
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2022.2
    • Flutter plugin version 69.0.5
    • Dart plugin version 222.3345.108

[✓] VS Code (version 1.70.1)
    • VS Code at C:\Users\Nabeel Parkar\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.46.0

[✓] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 13 (API 33) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.22000.856]
    • Chrome (web)                 • chrome        • web-javascript • unknown
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 104.0.1293.54

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by goderbauer** [comment] 2022-08-16 22:20
@Piinks

**Comment by Piinks** [comment] 2022-08-16 22:23
This looks like a duplicate of https://github.com/flutter/flutter/issues/89914
Please follow that issue for updates.

If you feel that this is a separate issue, let us know and we will take another look! Thanks!

**Closed by Piinks** 2022-08-16 22:23 UTC
Labels: a: text input, framework, has reproducible steps, found in release: 3.0, found in release: 3.1
