### ISSUE TITLE
Flutter crash on Galaxy S20+ & S21 : AbstractMethodError

### ISSUE THREAD

**Issue by Akiat** [flutter/flutter#75290] opened 2021-02-02 23:08 UTC
I got a Sentry report with a crash from production that happens only on these devices (Samsung Galaxy S20+ & S21).

The only things returned by Sentry is this:

```
java.lang.AbstractMethodError: abstract method "android.view.WindowInsets android.view.WindowInsetsAnimation$Callback.onProgress(android.view.WindowInsets, java.util.List)"
    at android.view.View.dispatchWindowInsetsAnimationProgress(View.java:12131)
    at android.view.ViewGroup.dispatchWindowInsetsAnimationProgress(ViewGroup.java:8457)
    at android.view.ViewGroup.dispatchWindowInsetsAnimationProgress(ViewGroup.java:8463)
    at android.view.ViewGroup.dispatchWindowInsetsAnimationProgress(ViewGroup.java:8463)
    at android.view.ViewGroup.dispatchWindowInsetsAnimationProgress(ViewGroup.java:8463)
    at android.view.ViewGroup.dispatchWindowInsetsAnimationProgress(ViewGroup.java:8463)
    at android.view.ViewRootInsetsControllerHost.dispatchWindowInsetsAnimationProgress(ViewRootInsetsControllerHost.java:111)
    at android.view.InsetsController.lambda$new$2$InsetsController(InsetsController.java:626)
    at android.view.-$$Lambda$InsetsController$zpmOxHfTFV_3me2u3C8YaXSUauQ.run
    at android.view.InsetsController.scheduleApplyChangeInsets(InsetsController.java:1488)
    at android.view.InsetsAnimationControlImpl.setInsetsAndAlpha(InsetsAnimationControlImpl.java:188)
    at android.view.InsetsAnimationControlImpl.setInsetsAndAlpha(InsetsAnimationControlImpl.java:172)
    at android.view.InsetsController$InternalAnimationControlListener.lambda$onReady$0$InsetsController$InternalAnimationControlListener(InsetsController.java:364)
    at android.view.-$$Lambda$InsetsController$InternalAnimationControlListener$SInf91MjJKDQFXwrp7C-HBi0xaQ.onAnimationUpdate
    at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1566)
    at android.animation.ValueAnimator.setCurrentFraction(ValueAnimator.java:692)
    at android.animation.ValueAnimator.setCurrentPlayTime(ValueAnimator.java:655)
    at android.animation.ValueAnimator.start(ValueAnimator.java:1087)
    at android.animation.ValueAnimator.start(ValueAnimator.java:1106)
    at android.view.InsetsController$InternalAnimationControlListener.onReady(InsetsController.java:381)
    at android.view.InsetsController.lambda$startAnimation$6$InsetsController(InsetsController.java:1471)
    at android.view.-$$Lambda$InsetsController$VzAUS17blucBK1u6-37NlEpdYqI.run
    at android.view.ViewRootInsetsControllerHost$1.onPreDraw(ViewRootInsetsControllerHost.java:72)
    at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:1124)
    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3731)
    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2508)
    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9784)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1010)
    at android.view.Choreographer.doCallbacks(Choreographer.java:809)
    at android.view.Choreographer.doFrame(Choreographer.java:744)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:995)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:246)
    at android.app.ActivityThread.main(ActivityThread.java:8456)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:596)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

Here is my flutter doctor:
```
[√] Flutter (Channel dev, 1.26.0-1.0.pre, on Microsoft Windows [version 10.0.18363.1316], locale fr-FR)
    • Flutter version 1.26.0-1.0.pre at C:\src\flutter
    • Framework revision 63062a6443 (7 weeks ago), 2020-12-13 23:19:13 +0800
    • Engine revision 4797b06652
    • Dart version 2.12.0 (build 2.12.0-141.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\Akiat\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = C:\Users\Akiat\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • CHROME_EXECUTABLE = C:\Users\Akiat\Desktop\chrome.bat

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code, 64-bit edition (version 1.52.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.19.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 88.0.4324.104
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 87.0.664.66

• No issues found!
```

Do you have an idea of what could cause this ?

**Comment by TahaTesser** [comment] 2021-02-03 08:17
Hi @Akiat 
This looks like a duplicate of https://github.com/flutter/flutter/issues/72787
Fix seems to be landed in the `master` and `dev`, https://github.com/flutter/flutter/issues/72787#issuecomment-769278974
Can you please upgrade to the latest  `dev` and try again
`flutter channel dev`
`flutter upgrade --force`
`flutter doctor -v`
Thank you

**Comment by Akiat** [comment] 2021-02-03 18:12
Thank you @TahaTesser, and sorry for the duplicate, I missed it.

The update fixed the crash :)

**Comment by TahaTesser** [comment] 2021-02-04 07:29
Hi @Akiat 
No worries, given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you

**Closed by TahaTesser** 2021-02-04 07:29 UTC
Labels: in triage
