### ISSUE TITLE
TextFormField with IntrinsicHeight leads to incorrect rendering of errorText

### ISSUE THREAD

**Issue by viplifes** [flutter/flutter#62524] opened 2020-07-29 21:48 UTC
<img src="https://user-images.githubusercontent.com/286489/88856491-456e2980-d1fd-11ea-904a-113119f7f9b9.png" width ="300"> 

## Steps to Reproduce

1. Run `flutter create bug`.
2. Replace main.dart with
```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  GlobalKey<FormState> _formKey = GlobalKey();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
          child: Form(
              key: _formKey,
              child: IntrinsicHeight(
                  child: Row(
                children: <Widget>[
                  Flexible(
                    flex: 2,
                    fit: FlexFit.tight,
                    child: TextFormField(
                      validator: (_) =>
                          'error 1 error 1 error 1 error 1 error 1 error 1 error 1 error 1',
                      decoration: InputDecoration(
                          contentPadding:
                              EdgeInsets.symmetric(horizontal: 10.0),
                          labelText: 'label 1',
                          errorMaxLines: 10),
                    ),
                  ),
                  SizedBox(
                    width: 10,
                  ),
                  Flexible(
                    flex: 8,
                    fit: FlexFit.tight,
                    child: TextFormField(
                        validator: (_) => 'error 2 ',
                        decoration: InputDecoration(
                            contentPadding:
                                EdgeInsets.symmetric(horizontal: 10.0),
                            labelText: 'label 2',
                            errorMaxLines: 10)),
                  ),
                ],
              )))),
      floatingActionButton: FloatingActionButton(
        onPressed: () => _formKey.currentState.validate(),
        child: Icon(Icons.send),
      ),
    );
  }
}

```

3. Run app and click on FloatingActionButton
Expected results: errorText is displayed under the field.
Actual results: errorText is overlaps the field.

<details>
  <summary>Logs</summary>

```
[+10807 ms] flutter: ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
[  +10 ms] flutter: The following assertion was thrown during performLayout():
[        ] flutter: BoxConstraints has a negative minimum height.
[        ] flutter: These invalid constraints were provided to RenderCustomPaint's layout() function by the following
[        ] flutter: function, which probably computed the invalid constraints in question:
[        ] flutter:   _RenderDecoration.performLayout (package:flutter/src/material/input_decorator.dart:1298:17)
[        ] flutter: The offending constraints were:
[        ] flutter:   BoxConstraints(w=80.8, h=-8.0; NOT NORMALIZED)
[        ] flutter:
[        ] flutter: The relevant error-causing widget was:
[        ] flutter:   TextFormField file:///Users/dimir/projects/git/flutter/test1/flutter_app_test/lib/main.dart:40:28
[        ] flutter:
[        ] flutter: When the exception was thrown, this was the stack:
[        ] flutter: #0      BoxConstraints.debugAssertIsValid.<anonymous closure>.throwError (package:flutter/src/rendering/box.dart:519:9)
[  +23 ms] flutter: #1      BoxConstraints.debugAssertIsValid.<anonymous closure> (package:flutter/src/rendering/box.dart:550:19)
[        ] flutter: #2      BoxConstraints.debugAssertIsValid (package:flutter/src/rendering/box.dart:567:6)
[        ] flutter: #3      RenderObject.layout (package:flutter/src/rendering/object.dart:1678:24)
[        ] flutter: #4      _RenderDecoration.performLayout (package:flutter/src/material/input_decorator.dart:1298:17)
[        ] flutter: #5      RenderObject.layout (package:flutter/src/rendering/object.dart:1775:7)
[        ] flutter: #6      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
[        ] flutter: #7      RenderObject.layout (package:flutter/src/rendering/object.dart:1775:7)
[        ] flutter: #8      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
[        ] flutter: #9      RenderObject.layout (package:flutter/src/rendering/object.dart:1775:7)
[        ] flutter: #10     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
[        ] flutter: #11     RenderObject.layout (package:flutter/src/rendering/object.dart:1775:7)
[        ] flutter: #12     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
[        ] flutter: #13     RenderObject.layout (package:flutter/src/rendering/object.dart:1775:7)
[        ] flutter: #14     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:833:17)
[        ] flutter: #15     RenderObject.layout (package:flutter/src/rendering/object.dart:1775:7)
[        ] flutter: #16     RenderIntrinsicHeight.performLayout (package:flutter/src/rendering/proxy_box.dart:752:13)
[        ] flutter: #17     RenderObject.layout (package:flutter/src/rendering/object.dart:1775:7)
[   +3 ms] flutter: #18     RenderPositionedBox.performLayout (package:flutter/src/rendering/shifted_box.dart:396:13)
[        ] flutter: #19     RenderObject.layout (package:flutter/src/rendering/object.dart:1775:7)
[        ] flutter: #20     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:173:11)
[        ] flutter: #21     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:497:7)
[        ] flutter: #22     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:242:7)
[        ] flutter: #23     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:401:14)
[        ] flutter: #24     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1638:7)
[        ] flutter: #25     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:896:18)
[        ] flutter: #26     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:403:19)
[  +15 ms] flutter: #27     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:881:13)
[        ] flutter: #28     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:286:5)
[        ] flutter: #29     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1114:15)
[        ] flutter: #30     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1053:9)
[        ] flutter: #31     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:969:5)
[        ] flutter: #35     _invoke (dart:ui/hooks.dart:253:10)
[        ] flutter: #36     _drawFrame (dart:ui/hooks.dart:211:3)
[        ] flutter: (elided 3 frames from dart:async)
[        ] flutter:
[        ] flutter: The following RenderObject was being processed when the exception was fired: _RenderDecoration#5f579 relayoutBoundary=up8 NEEDS-LAYOUT
NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE:
[   +3 ms] flutter:   needs compositing
[        ] flutter:   creator: _Decorator ← InputDecorator ← AnimatedBuilder ← _PointerListener ← Listener ←
[        ] flutter:     RawGestureDetector ← TextSelectionGestureDetector ← Semantics ← AnimatedBuilder ← IgnorePointer ←
[        ] flutter:     _RawMouseRegion ← MouseRegion ← ⋯
[        ] flutter:   parentData: <none> (can use size)
[        ] flutter:   constraints: BoxConstraints(w=80.8, 0.0<=h<=99.0)
[        ] flutter:   size: Size(80.8, 48.0)
[        ] flutter: This RenderObject had the following descendants (showing up to depth 5):
[        ] flutter:     input: RenderRepaintBoundary#59fa6 NEEDS-PAINT
[        ] flutter:       child: RenderMouseRegion#a33e6 NEEDS-PAINT
[  +28 ms] flutter:         child: RenderPointerListener#3cd56 NEEDS-PAINT
[        ] flutter:           child: RenderPointerListener#5ccf9 NEEDS-PAINT
[   +5 ms] flutter:             child: RenderSemanticsAnnotations#d58db NEEDS-PAINT
[        ] flutter:     label: RenderTransform#f9520 relayoutBoundary=up9 NEEDS-PAINT
[        ] flutter:       child: RenderAnimatedOpacity#0913c relayoutBoundary=up10 NEEDS-PAINT
[        ] flutter:         child: RenderParagraph#598e7 relayoutBoundary=up11 NEEDS-PAINT
[        ] flutter:           text: TextSpan
[        ] flutter:     helperError: RenderSemanticsAnnotations#3ba9a relayoutBoundary=up9 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
[        ] flutter:       child: RenderOpacity#9f186 relayoutBoundary=up10 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
[        ] flutter:         child: RenderFractionalTranslation#06e4e relayoutBoundary=up11 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
[        ] flutter:           child: RenderParagraph#68899 relayoutBoundary=up12 NEEDS-PAINT
[        ] flutter:             text: TextSpan
[        ] flutter:     container: RenderCustomPaint#fa8ef NEEDS-PAINT
[        ] flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════


```

```
Analyzing flutter_app_test...                                           
No issues found! (ran in 1.8s;)
```

```
[✓] Flutter (Channel master, 1.21.0-6.0.pre.106, on Mac OS X 10.15.5 19F101, locale en-UA)
    • Flutter version 1.21.0-6.0.pre.106 at /Users/dimir/bin/flutter
    • Framework revision 392e25c8f2 (48 minutes ago), 2020-07-30 08:46:29 +1200
    • Engine revision a9910e409c
    • Dart version 2.10.0 (build 2.10.0-1.0.dev 24c7666def)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/dimir/Library/Android/sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.8.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2020.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 46.0.3
    • Dart plugin version 201.7846.93

[✓] Connected device (4 available)
    • AOSP on IA Emulator (mobile) • emulator-5554                        • android-x86    • Android 9 (API 28) (emulator)
    • iPhone 11 Pro Max (mobile)   • 7B5722C2-CA51-43AE-9918-C7DB3135A877 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-5 (simulator)
    • Web Server (web)             • web-server                           • web-javascript • Flutter Tools
    • Chrome (web)                 • chrome                               • web-javascript • Google Chrome 84.0.4147.105

• No issues found!
Process finished with exit code 0
```

</details>

**Comment by TahaTesser** [comment] 2020-07-30 08:53
<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel master, 1.21.0-6.0.pre.116, on Mac OS X 10.15.6 19G73,
    locale en-GB)
    • Flutter version 1.21.0-6.0.pre.116 at
      /Users/tahatesser/Code/flutter_master
    • Framework revision 685590f872 (3 hours ago), 2020-07-29 22:54:58 -0700
    • Engine revision a9910e409c
    • Dart version 2.10.0 (build 2.10.0-1.0.dev 24c7666def)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[✓] Connected device (5 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E            • ios
      • iOS 13.6
    • iPhone 11 (mobile)     • 7863E29F-EEE8-499E-BB28-6B111B76E3EE • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-13-6 (simulator)
    • macOS (desktop)        • macos                                • darwin-x64
      • Mac OS X 10.15.6 19G73
    • Web Server (web)       • web-server                           •
      web-javascript • Flutter Tools
    • Chrome (web)           • chrome                               •
      web-javascript • Google Chrome 84.0.4147.105

• No issues found!
```

</details>

**Comment by HansMuller** [comment] 2020-07-30 15:12
CC @justinmc

**Comment by justinmc** [comment] 2020-07-30 20:28
Strangely this doesn't happen on Mac desktop.  I did see it on iOS and Android, though.

<img width="342" alt="Screen Shot 2020-07-30 at 1 22 43 PM" src="https://user-images.githubusercontent.com/389558/88971276-923b1a00-d268-11ea-9c27-11ad44550fa3.png">


Here's the error on Android for the record:

```
I/flutter (12308): The following assertion was thrown during performLayout():
I/flutter (12308): BoxConstraints has a negative minimum height.
I/flutter (12308): These invalid constraints were provided to RenderCustomPaint's layout() function by the following
I/flutter (12308): function, which probably computed the invalid constraints in question:
I/flutter (12308):   _RenderDecoration.performLayout (package:flutter/src/material/input_decorator.dart:1298:17)
I/flutter (12308): The offending constraints were:
I/flutter (12308):   BoxConstraints(w=76.5, h=-8.0; NOT NORMALIZED)
I/flutter (12308):
I/flutter (12308): The relevant error-causing widget was:
I/flutter (12308):   TextFormField file:///Users/jmccandless/Projects/issues/sandbox/lib/main.dart:40:28
I/flutter (12308):
I/flutter (12308): When the exception was thrown, this was the stack:
I/flutter (12308): #0      BoxConstraints.debugAssertIsValid.<anonymous closure>.throwError (package:flutter/src/rendering/box.dart:519:9)
```

**Comment by almamarie** [comment] 2022-02-07 09:50
solution can be found here:
https://stackoverflow.com/questions/56674596/validator-error-message-changes-textformfields-height

**Comment by zs-dima** [comment] 2022-11-07 19:13
@almamarie your link is not the IntrinsicHeight case
IntrinsicHeight still has this issue

**Comment by maheshmnj** [comment] 2023-01-04 05:01
Hi @viplifes, I am not able to reproduce the issue on latest stable 3.3 or master 3.7, I believe this is fixed.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/31410839/210487582-458e3a12-93e7-46d7-8e99-02a04ad17d41.png">


<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      title: 'Flutter Demo',
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final GlobalKey<FormState> _formKey = GlobalKey();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
          child: Form(
              key: _formKey,
              child: IntrinsicHeight(
                  child: Row(
                children: <Widget>[
                  Flexible(
                    flex: 2,
                    fit: FlexFit.tight,
                    child: TextFormField(
                      validator: (_) =>
                          'error 1 error 1 error 1 error 1 error 1 error 1 error 1 error 1',
                      decoration: const InputDecoration(
                          contentPadding:
                              EdgeInsets.symmetric(horizontal: 10.0),
                          labelText: 'label 1',
                          errorMaxLines: 10),
                    ),
                  ),
                  const SizedBox(
                    width: 10,
                  ),
                  Flexible(
                    flex: 8,
                    fit: FlexFit.tight,
                    child: TextFormField(
                        validator: (_) => 'error 2 ',
                        decoration: const InputDecoration(
                            contentPadding:
                                EdgeInsets.symmetric(horizontal: 10.0),
                            labelText: 'label 2',
                            errorMaxLines: 10)),
                  ),
                ],
              )))),
      floatingActionButton: FloatingActionButton(
        onPressed: () => _formKey.currentState!.validate(),
        child: const Icon(Icons.send),
      ),
    );
  }
}

```
</details> 

<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel master, 3.7.0-13.0.pre.131, on macOS 13.1 22C65 darwin-arm64, locale en-IN)
    • Flutter version 3.7.0-13.0.pre.131 on channel master at /Users/mahesh/Development/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 0196e6050b (2 days ago), 2022-12-31 11:10:23 -0500
    • Engine revision 932591ec04
    • Dart version 3.0.0 (build 3.0.0-76.0.dev)
    • DevTools version 2.20.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks
      and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.74.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.56.0

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • 026D5789-9E78-4AD5-B1B2-3F8D4E7F65E4 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 13.1 22C65 darwin-arm64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 108.0.5359.124

[✓] HTTP Host Availability
    • All required HTTP hosts are available
    
• No issues found!
```
```
[✓] Flutter (Channel stable, 3.3.9, on macOS 12.6 21G115 darwin-arm, locale en-IN)
    • Flutter version 3.3.9 on channel stable at /Users/mahesh/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b8f7f1f986 (24 hours ago), 2022-11-23 06:43:51 +0900
    • Engine revision 8f2221fbef
    • Dart version 2.18.5
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.70.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.53.20221101

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • 026D5789-9E78-4AD5-B1B2-3F8D4E7F65E4 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.6 21G115 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 107.0.5304.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

Closing as fixed, Incase you still encounter the issue then please feel free to write in the comments and we will reopen it.

Thank you.

**Closed by maheshmnj** 2023-01-04 05:01 UTC
Labels: a: text input, framework, f: material design, has reproducible steps, found in release: 1.21
