### ISSUE TITLE
Flutter Doctor Issue

### ISSUE THREAD

**Issue by SyeedShovon** [flutter/flutter#59066] opened 2020-06-09 11:50 UTC
## Steps to Reproduce

1. ...After installing flutter by git clone while flutter doctor is typed in flutter_console.bat then it shows error and says flutter has exited unexpectedly.
2. ...
3. ...

## Logs

Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter doctor

## exception

IndexError: RangeError (index): Index out of range: no indices are valid: 0

```
#0      _Uint8ArrayView.[] (dart:typed_data-patch/typed_data_patch.dart:3932:7)
#1      InputStream.readUint16 (package:archive/src/util/input_stream.dart:206:22)
#2      GZipDecoder._readHeader (package:archive/src/gzip_decoder.dart:89:29)
#3      GZipDecoder.decodeBuffer (package:archive/src/gzip_decoder.dart:26:5)
#4      GZipDecoder.decodeBytes (package:archive/src/gzip_decoder.dart:17:12)
#5      _WindowsUtils.verifyGzip (package:flutter_tools/src/base/os.dart:352:21)
#6      CachedArtifact._downloadArchive.<anonymous closure> (package:flutter_tools/src/cache.dart:605:20)
#7      CachedArtifact._withDownloadFile (package:flutter_tools/src/cache.dart:638:26)
#8      CachedArtifact._downloadArchive (package:flutter_tools/src/cache.dart:604:12)
#9      CachedArtifact._downloadZippedTarball (package:flutter_tools/src/cache.dart:630:12)
#10     GradleWrapper.updateInner (package:flutter_tools/src/cache.dart:1070:12)
#11     CachedArtifact.update (package:flutter_tools/src/cache.dart:560:11)
#12     Cache.updateAll (package:flutter_tools/src/cache.dart:432:24)
#13     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:698:27)
#14     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:620:33)
<asynchronous suspension>
#15     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart)
#16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#17     _rootRun (dart:async/zone.dart:1184:13)
#18     _CustomZone.run (dart:async/zone.dart:1077:19)
#19     _runZoned (dart:async/zone.dart:1619:10)
#20     runZoned (dart:async/zone.dart:1539:10)
#21     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#22     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:610:20)
#23     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#24     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:339:21)
<asynchronous suspension>
#25     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart)
#26     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#27     _rootRun (dart:async/zone.dart:1184:13)
#28     _CustomZone.run (dart:async/zone.dart:1077:19)
#29     _runZoned (dart:async/zone.dart:1619:10)
#30     runZoned (dart:async/zone.dart:1539:10)
#31     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#32     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:288:19)
#33     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#34     new Future.sync (dart:async/future.dart:224:31)
#35     CommandRunner.run (package:args/command_runner.dart:112:14)
#36     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:231:18)
#37     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
#38     _rootRun (dart:async/zone.dart:1184:13)
#39     _CustomZone.run (dart:async/zone.dart:1077:19)
#40     _runZoned (dart:async/zone.dart:1619:10)
#41     runZonedGuarded (dart:async/zone.dart:1608:12)
#42     runZoned (dart:async/zone.dart:1536:12)
#43     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#44     run.<anonymous closure> (package:flutter_tools/runner.dart)
#45     runInContext.runnerWrapper (package:flutter_tools/src/context_runner.dart:64:18)
<asynchronous suspension>
#46     runInContext.runnerWrapper (package:flutter_tools/src/context_runner.dart)
#47     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#48     _rootRun (dart:async/zone.dart:1184:13)
#49     _CustomZone.run (dart:async/zone.dart:1077:19)
#50     _runZoned (dart:async/zone.dart:1619:10)
#51     runZoned (dart:async/zone.dart:1539:10)
#52     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#53     runInContext (package:flutter_tools/src/context_runner.dart:67:24)
#54     run (package:flutter_tools/runner.dart:48:10)
#55     main (package:flutter_tools/executable.dart:69:9)
#56     main (file:///C:/src/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#57     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#58     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

## flutter doctor

```
[✓] Flutter (Channel stable, v1.17.3, on Microsoft Windows [Version 10.0.17134.1], locale en-US)
    • Flutter version 1.17.3 at C:\src\flutter
    • Framework revision b041144f83 (5 days ago), 2020-06-04 09:26:11 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\syeed.shovon\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    ✗ Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[!] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.
```
[flutter_01.log](https://github.com/flutter/flutter/files/4751955/flutter_01.log)

Oops; flutter has exited unexpectedly: "RangeError (index): Index out of range: no indices are valid: 0".
A crash report has been written to C:\Users\syeed.shovon\flutter_03.log.
This crash may already be reported. Check GitHub for similar crashes.
https://git.io/JeyYe

To report your crash to the Flutter team, first read the guide to filing a bug.
https://flutter.dev/docs/resources/bug-reports

Create a new GitHub issue by pasting this link into your browser and completing the issue template. Thank you!
https://git.io/JfyRZ

**Comment by TahaTesser** [comment] 2020-06-09 15:14
duplicate of https://github.com/flutter/flutter/issues/48014

**Closed by TahaTesser** 2020-06-09 15:14 UTC

**Comment by SyeedShovon** [comment] 2020-06-10 05:27
Thanks for checking this out. But what is the solution?? plz help
