### ISSUE TITLE
[tool_crash] ProcessException: The requested operation requires elevation. Command: "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe", OS error code: 740

### ISSUE THREAD

**Issue by yacinegithub** [flutter/flutter#98649] opened 2022-02-17 10:02 UTC
## Command
```
flutter run -d chrome
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ProcessException: The requested operation requires elevation.
 Command: "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe", OS error code: 740
```
#0      _ProcessImpl._start (dart:io-patch/process_patch.dart:401:33)
#1      Process.start (dart:io-patch/process_patch.dart:38:20)
#2      LocalProcessManager.start (package:process/src/interface/local_process_manager.dart:42:22)
#3      ErrorHandlingProcessManager.start.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:691:24)
#4      _run (package:flutter_tools/src/base/error_handling_io.dart:567:20)
#5      ErrorHandlingProcessManager.start (package:flutter_tools/src/base/error_handling_io.dart:690:12)
#6      ChromiumLauncher._spawnChromiumProcess (package:flutter_tools/src/web/chrome.dart:256:53)
#7      ChromiumLauncher.launch (package:flutter_tools/src/web/chrome.dart:221:36)
<asynchronous suspension>
#8      ChromiumDevice.startApp (package:flutter_tools/src/web/web_device.dart:134:17)
<asynchronous suspension>
#9      ResidentWebRunner.run.<anonymous closure> (package:flutter_tools/src/isolated/resident_web_runner.dart:307:9)
<asynchronous suspension>
#10     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:24)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 2.8.1, on Microsoft Windows [Version 10.0.19043.1466], locale en-US)
    • Flutter version 2.8.1 at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (9 weeks ago), 2021-12-16 08:37:33 -0800
    • Eng

**Comment by maheshmnj** [comment] 2022-02-17 11:48
Hi @yacinegithub, Thanks for filing the issue.

Do you get this error with a newly created flutter project too? if Not are there any steps to reproduce it?
from the logs, It looks like this is caused by not running the process as an administrator.

However, There is a similar issue describing this case https://github.com/flutter/flutter/issues/78240, Please follow up there for further updates, Closing this issue as a duplicate. If you disagree feel free to write in the comments and we will reopen it.

Thank you.

**Closed by maheshmnj** 2022-02-17 11:48 UTC
Labels: in triage

**Comment by yacinegithub** [comment] 2022-02-17 13:24
> Do you get this error with a newly created flutter project too? if Not are there any steps to reproduce it?

Old and new
