### ISSUE TITLE
TextField 'keyboardType: TextInputType.number' doesn't bring the number keyboard on some Android devices (web) & iOS12

### ISSUE THREAD

**Issue by tomasbaran** [flutter/flutter#58510] opened 2020-06-02 17:55 UTC
Works well on iOS13, not on iOS12. On some Android devices works well, on some it does NOT.

**Expected results:** 
<img width="454" alt="Captura de pantalla 2020-06-02 a las 18 47 03" src="https://user-images.githubusercontent.com/25743901/83552309-74b83100-a501-11ea-8869-8fc0d154e344.png">

**Actual results:** 
<img width="346" alt="Captura de pantalla 2020-06-02 a las 18 44 11" src="https://user-images.githubusercontent.com/25743901/83552293-6d912300-a501-11ea-8fc5-7bee5813d761.png">
<details>
  <summary>Logs</summary>

```
```

```
```

```
[✓] Flutter (Channel dev, 1.19.0-2.0.pre, on Mac OS X 10.15.5 19F101, locale es-ES)
    • Flutter version 1.19.0-2.0.pre at /Users/tomas/Development/flutter
    • Framework revision 1d395c5e18 (2 days ago), 2020-05-31 07:41:50 -0700
    • Engine revision 923687f0e7
    • Dart version 2.9.0 (build 2.9.0-11.0.dev 6489a0c68d)


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/tomas/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (3 available)
    • iPhone 11  • 04298E38-2633-4586-B868-1FBD5C708AF7 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-5 (simulator)
    • Web Server • web-server                           • web-javascript • Flutter Tools
    • Chrome     • chrome                               • web-javascript • Google Chrome 83.0.4103.61

• No issues found!
```

</details>

**Comment by TahaTesser** [comment] 2020-06-03 07:48
Left iOS 12 and right iOS 13 


![image](https://user-images.githubusercontent.com/48603081/83609936-869ae200-a59c-11ea-88ef-99e2eb9475f7.png)

Thanks! @VladyslavBondarenko 

<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel dev, 1.19.0-3.0.pre, on Mac OS X 10.15.5 19F96, locale
    en-GB)
    • Flutter version 1.19.0-3.0.pre at /Users/tahatesser/Code/flutter_dev
    • Framework revision 6135091de9 (31 hours ago), 2020-06-01 17:17:03 -0700
    • Engine revision e39301f23f
    • Dart version 2.9.0 (build 2.9.0-11.0.dev 6489a0c68d)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (4 available)
    • iPhone 11  • 0EC80516-8F99-4A0C-89ED-2273579862F9 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-13-5 (simulator)
    • macOS      • macOS                                • darwin-x64     • Mac
      OS X 10.15.5 19F96
    • Web Server • web-server                           • web-javascript •
      Flutter Tools
    • Chrome     • chrome                               • web-javascript •
      Google Chrome 83.0.4103.61

• No issues found!
``` 

</details>

**Comment by tomasbaran** [comment] 2020-06-03 14:08
Since this issue is also present only on iOS12 and on iPhone SE, it may be related to this one (which is also present only on iOS12 on iPhone SE: https://github.com/flutter/flutter/issues/58518

**Comment by tomasbaran** [comment] 2020-06-06 23:13
iPad mini (iOS 12) doesn't show the numeric keyboard either.

**Comment by tomasbaran** [comment] 2020-06-27 13:36
Doesn't work on Android on Huawei (Android 9 - EMUI 9.1.0) (web) either. Only shows alphabetical keyboard.

**Comment by tomasbaran** [comment] 2020-06-27 13:49
May be related: https://github.com/flutter/flutter/issues/25454 ?

**Comment by hr1995** [comment] 2020-07-21 02:16
flutter_web 1.17.0-3.4.pre have the same problem， besides on iPhone iPad devices，some Android devices too。

**Comment by hr1995** [comment] 2020-07-21 02:19
> flutter_web 1.17.0-3.4.pre have the same problem， besides on iPhone iPad devices，some Android devices too。

this issue has solved?

**Comment by tomasbaran** [comment] 2020-07-21 09:27
@hr1995 as far as I know it hasn't been solved. If you want the issue to be solved faster, please +1 thumb up the original post.

**Comment by way1001** [comment] 2020-07-31 03:24
+1

**Comment by tomasbaran** [comment] 2020-07-31 07:39
@way1001 if you want the issue to be solved faster, please +1 thumb up the original post (not as a separate post, which doesn't move the issue up in the queue)

**Comment by gonzalodev92** [comment] 2020-07-31 18:13
same problem

**Comment by luishar0** [comment] 2020-08-05 03:45
I have a similar issue and believe it might be related. When using TextField or CupertinoTextField, setting the keyboardType to any of the types will make no difference on iOS (simulator or physical), it always shows the same keyboards regardless of the setting. Using master, 1.21.0-6.0.pre.140

**Comment by TahaTesser** [comment] 2021-02-02 14:05
<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel beta, 1.25.0-8.3.pre, on macOS 11.1 20C69 darwin-x64, locale en-GB)
    • Flutter version 1.25.0-8.3.pre at /Users/tahatesser/Code/flutter_beta
    • Framework revision 5d36f2e7f5 (3 weeks ago), 2021-01-14 15:57:49 -0800
    • Engine revision 7a8f8ca02c
    • Dart version 2.12.0 (build 2.12.0-133.7.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0

[✓] Connected device (2 available)
    • Taha’s iPad (mobile) • 00008020-000255113EE8402E • ios            • iOS 14.4
    • Chrome (web)         • chrome                    • web-javascript • Google Chrome 88.0.4324.96
    ! Error: Taha’s iPad is busy: Copying cache files from device. Xcode will continue when Taha’s iPad is finished. (code -10)

• No issues found!
```
```bash
[✓] Flutter (Channel master, 1.26.0-18.0.pre.128, on macOS 11.1 20C69 darwin-x64, locale en-GB)
    • Flutter version 1.26.0-18.0.pre.128 at /Users/tahatesser/Code/flutter_master
    • Framework revision 502ff3dbfe (59 minutes ago), 2021-02-02 05:41:03 -0500
    • Engine revision 7334085fc1
    • Dart version 2.12.0 (build 2.12.0-281.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0

[✓] Connected device (4 available)
    • RMX2001 (mobile)                   • EUYTFEUSQSRGDA6D • android-arm64  • Android 10 (API 29)
    • Android SDK built for x86 (mobile) • emulator-5554    • android-x86    • Android 10 (API 29) (emulator)
    • macOS (desktop)                    • macos            • darwin-x64     • macOS 11.1 20C69 darwin-x64
    • Chrome (web)                       • chrome           • web-javascript • Google Chrome 88.0.4324.96

• No issues found!
```

</details>

**Comment by SunlightBro** [comment] 2021-03-29 12:58
Any update on this, or any know workaround ?
for some old ipad-app I have to work on the old stable flutter-1.22-candidate.12. 
but I also testet it on the newest version, where this still exists ...
[✓] Flutter (Channel stable, 2.0.3, on macOS 11.2.3 20D91 darwin-arm, locale en-DE)
    • Flutter version 2.0.3 at /Users/dave/flutter
    • Framework revision 4d7946a68d (11 days ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2
[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

<img width="689" alt="Screenshot 2021-03-29 at 14 52 39" src="https://user-images.githubusercontent.com/22753153/112839961-13b8a580-909f-11eb-8f89-ae016c0b479e.png">

**Comment by diegopq** [comment] 2021-03-30 00:25
I am using a TextFormField with the keyboardType: TextInputType.number and it works fine on ios 13 but if I put the autofillHints: [AutofillHints.creditCardNumber] change the keyboard type, the same happens if I have keyboardType: TextInputType.numberWithOptions (decimal: false, signed : false). I have another TextFormField with the same type of keyboard but with autofillHints: [AutofillHints.creditCardExpirationDate] and there it shows the correct keyboard with only the numbers

**Comment by ishannadeep** [comment] 2021-03-31 09:22
@tomasbaran  I'm having the same issue with Huawei nova 7i

**Comment by mahaiyi2** [comment] 2021-05-07 02:54
+1

**Comment by jacopofranza** [comment] 2021-05-07 09:03
Same problem here

**Comment by omidraha** [comment] 2021-05-18 06:04
same [issue](https://github.com/flutter/flutter/issues/25454#issuecomment-842869871).

**Comment by Riscait** [comment] 2021-06-16 01:38
I am having the same problem.
When `keyboardType: TextInputType.number` and `autofillHints: [AutofillHints.creditCardNumber]` are specified in `TextFormField`, the keyboard is not number-only.
The issue was confirmed on Flutter 2.0.6, iOS14,5 / 15 Beta.

**Comment by Ancx95328** [comment] 2021-07-28 08:32
+1

**Comment by danielgomezrico** [comment] 2021-07-28 12:39
Is there any updates on this?

**Comment by innerk** [comment] 2021-08-17 02:38
+1 it happens to me in some android devices

**Comment by liveaffiliates** [comment] 2021-09-09 12:26
This should have been fixed by now it is basic functionality of every app but still happening on android

**Comment by timokz** [comment] 2021-10-21 21:05
+1, on web
```
[√] Flutter (Channel stable, 2.5.3, on Microsoft Windows [Version 10.0.19043.1288], locale en-AT)
    • Flutter version 2.5.3 at W:\Flutter\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (6 days ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at **\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: W:\AndroidStd\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.2)
    • Android Studio at W:\AndroidStd
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] IntelliJ IDEA Ultimate Edition (version 2021.1)
    • IntelliJ at Y:\IntelliJ IDEA 2021.1.1
    • Flutter plugin version 61.0.4
    • Dart plugin version 212.5486

[√] IntelliJ IDEA Ultimate Edition (version 2021.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2021.2.2
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5486

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 95.0.4638.54
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 93.0.961.52

```

**Comment by tappbatter** [comment] 2021-11-08 03:46
Don't forget to double check your I/O >> Input settings if using an iOS emulator:

![Screen Shot 2021-11-07 at 7 44 31 PM](https://user-images.githubusercontent.com/93172949/140681149-2721b60f-33ea-4590-a828-6d2229d5be84.png)

It was working for me then restarted the emulator, stopped working, then figured out the settings had selected the keyboard input (perhaps I hit the keyboard when testing?).

**Comment by justinmc** [comment] 2021-11-18 21:10
I'm going to close this issue because based on my analysis (details below), the only problem that I can reproduce is due to browser compatibility.  The only place where I was able to reproduce this bug was Safari on iOS 12, which doesn't seem to support the numeric keypad keyboard.

If anyone has a specific repro of Flutter doing the wrong thing here, please comment or open a new issue and I'd be happy to take a look.

### Analysis

On all platforms that I tried except for iOS 12 Safari, I got the correct behavior:

| Platform | Shows the correct number keyboard? |
| -- | -- |
| Simulator iPhone X iOS 12.4 | ✅ |
| Simulator iPhone X iOS 12.4 Safari | ❌ |
| Simulator iPhone X iOS 14.5 | ✅ |
| Simulator iPhone X iOS 14.5 Safari | ✅ |
| Physical Pixel 6 Android 12 Chrome | ✅ |

Here's what I get in the incorrect case for the iPhoneX iOS 12.4 Safari:

<img width="200" src="https://user-images.githubusercontent.com/389558/142485254-90b53717-e00d-4d00-865a-1545c352fa78.png" />

I believe that's just because iOS 12 doesn't support the "number" keyboard.  If I create a plain HTML page with an input with  `type="number"`, I get the same keyboard:

<img width="451" alt="Screen Shot 2021-11-18 at 1 03 16 PM" src="https://user-images.githubusercontent.com/389558/142497040-8cc2441f-aff8-49e3-953f-64c3f84b6525.png">

<details>

<summary>Example HTML page</summary>

```html
<!doctype html>
<html class="no-js" lang="">

<head>
  <meta charset="utf-8">
  <title></title>
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <meta property="og:title" content="">
  <meta property="og:type" content="">
  <meta property="og:url" content="">
  <meta property="og:image" content="">

  <link rel="manifest" href="site.webmanifest">
  <link rel="apple-touch-icon" href="icon.png">
  <!-- Place favicon.ico in the root directory -->

  <link rel="stylesheet" href="css/normalize.css">
  <link rel="stylesheet" href="css/main.css">

  <meta name="theme-color" content="#fafafa">
</head>

<body>

  <!-- Add your site or application content here -->
  <p>Hello world! This is HTML5 Boilerplate.</p>
  <input type="number" />
  <script src="js/vendor/modernizr-3.11.2.min.js"></script>
  <script src="js/plugins.js"></script>
  <script src="js/main.js"></script>

  <!-- Google Analytics: change UA-XXXXX-Y to be your site's ID. -->
  <script>
    window.ga = function () { ga.q.push(arguments) }; ga.q = []; ga.l = +new Date;
    ga('create', 'UA-XXXXX-Y', 'auto'); ga('set', 'anonymizeIp', true); ga('set', 'transport', 'beacon'); ga('send', 'pageview')
  </script>
  <script src="https://www.google-analytics.com/analytics.js" async></script>
</body>

</html>
```

</details>

<details>

<summary>Example Flutter app</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(
        body: Padding(
          padding: const EdgeInsets.all(32.0),
          child: Column(
            children: const <Widget>[
              TextField(
                keyboardType: TextInputType.number,
              ),
            ],
          ),
        ),
      ),
    );
  }
}
```

</details>

**Closed** 2021-11-18 21:12 UTC
Labels: a: text input, platform-ios, framework, f: material design, platform-web, e: OS Version specific, has reproducible steps, P5, found in release: 1.22, found in release: 1.26
