### ISSUE TITLE
RefreshIndicator not working with ReorderableListView when the list isn't long enough 

### ISSUE THREAD

**Issue by parth22** [flutter/flutter#44794] opened 2019-11-13 04:31 UTC
I tried to wrap my re-orderable list view with RefreshIndicator it's working but, when list don't have minimum data for scroll RefreshIndicator didn't refresh my re-orderable list. 

I checked the flutter Doc. and found:
In simple listview If the Scrollable might not have enough content to overscroll, we can set physics property to AlwaysScrollableScrollPhysics:
is there any way to done something like that in re-orderable list.
```
Future<dynamic> refreshList() async {
    await Future.delayed(const Duration(seconds: 1));
    testBloc.testList(
      prefsObject.getString('testId'),
    );
  }

return RefreshIndicator(
      key: refreshKey,
      color: pinkColor,
      onRefresh: () async {
        await refreshList();
      },
      child: ReorderableListView(
        header: null,
        onReorder: _onReorder,
        children: child,
        scrollDirection: Axis.vertical,
      ),
    );

**Comment by iapicca** [comment] 2019-11-14 08:29
Hi @parth22 
could you please provide your updated  `flutter doctor -v`?
Thank you

**Comment by parth22** [comment] 2019-11-14 13:35
Output of  flutter doctor -v

[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.13.6 17G65, locale
    en-IN)
    • Flutter version 1.9.1+hotfix.6 at /Volumes/Data/flutterSDK/flutter_hotFix2
    • Framework revision 68587a0916 (9 weeks ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at /Volumes/Data/AndroidSDK/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.1
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 40.2.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.40.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.6.0

[✓] Connected device (1 available)
    • iPhone X • 86A60205-090F-4BE5-8963-6590C33AA6BB • ios • iOS 12.1
      (simulator)

• No issues found!

**Comment by DavideBicego** [comment] 2020-01-24 15:10
Same problem here!!


[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Versione 10.0.18363.592], locale it-IT)
    • Flutter version 1.12.13+hotfix.5 at C:\src\flutter
    • Framework revision 27321ebbad (6 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\biceg\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = C:\Users\biceg\AppData\Local\Android\sdk
    • ANDROID_SDK_ROOT = C:\Users\biceg\AppData\Local\Android\sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code, 64-bit edition (version 1.40.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.7.1

[√] Connected device (1 available)
    • JSN L21 • 9YHNW18919008867 • android-arm64 • Android 9 (API 28)

• No issues found!

**Comment by piuskamil** [comment] 2020-03-04 09:25
Same here!

**Comment by andreu-sergienko** [comment] 2020-05-05 06:15
Add padding for ReorderableListView in your code. Final code result must be:

`Future<dynamic> refreshList() async {
    await Future.delayed(const Duration(seconds: 1));
    testBloc.testList(
      prefsObject.getString('testId'),
    );
  }

return RefreshIndicator(
      key: refreshKey,
      color: pinkColor,
      onRefresh: () async {
        await refreshList();
      },
      child: ReorderableListView(
        header: null,
        onReorder: _onReorder,
        children: child,
        **padding: const EdgeInsets.symmetric(vertical: 30.0),**
        scrollDirection: Axis.vertical,
      ),
    );`

This code work for me!

**Comment by TahaTesser** [comment] 2020-07-02 15:13
`RefreshIndicator` only works when list has long content, if you set it to 5 in the code sample below, it won't work 

<details> 
<summary>Code Sample</summary> 

``` 
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatefulWidget {
  @override
  _HomeState createState() => _HomeState();
}

class _HomeState extends State<Home> {
  final List<String> _list = List.generate(50, (i) => "${i}");

  final GlobalKey<RefreshIndicatorState> _refreshIndicatorKey =
      new GlobalKey<RefreshIndicatorState>();

  Future<dynamic> refreshList() async {
    await Future.delayed(const Duration(seconds: 1));
    print('test');
    // testBloc.testList(
    //   prefsObject.getString('testId'),
    // );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: RefreshIndicator(
        key: _refreshIndicatorKey,
        color: Colors.pink,
        onRefresh: () async {
          await refreshList();
        },
        child: ReorderableListView(
          // padding: const EdgeInsets.symmetric(vertical: 30.0),
          children: _list
              .map((String string) => ListTile(
                  key: Key(_list[_list.indexOf(string)]), title: Text(string)))
              .toList(),
          onReorder: (oldIndex, newIndex) {
            String old = _list[oldIndex];
            if (oldIndex > newIndex) {
              for (int i = oldIndex; i > newIndex; i--) {
                _list[i] = _list[i - 1];
              }
              _list[newIndex] = old;
            } else {
              for (int i = oldIndex; i < newIndex - 1; i++) {
                _list[i] = _list[i + 1];
              }
              _list[newIndex - 1] = old;
            }
            setState(() {});
          },
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {},
      ),
    );
  }
}

``` 

</details> 

<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel dev, 1.20.0-2.0.pre, on Mac OS X 10.15.5 19F101, locale
    en-GB)
    • Flutter version 1.20.0-2.0.pre at /Users/tahatesser/Code/flutter_dev
    • Framework revision 15a28159bc (9 days ago), 2020-06-23 04:52:58 -0700
    • Engine revision 91a63d6a44
    • Dart version 2.9.0 (build 2.9.0-19.0.dev 7e72c9ae7e)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.0
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.1

[✓] Connected device (5 available)
    • SM M305F      • 32003c30dc19668f          • android-arm64  • Android 10
      (API 29)
    • Taha’s iPhone • 00008020-001059882212002E • ios            • iOS 13.5.1
    • macOS desktop • macos                     • darwin-x64     • Mac OS X
      10.15.5 19F101
    • Web Server    • web-server                • web-javascript • Flutter Tools
    • Chrome        • chrome                    • web-javascript • Google Chrome
      83.0.4103.116

• No issues found!

``` 

</details>

**Comment by dave** [comment] 2020-08-26 15:02
Making a copy of the ReorderableListView and adding the `physics` property seems to work fine, so I pushed it as a package: https://pub.dev/packages/refreshable_reorderable_list 

You can use it like this: 

```yaml
refreshable_reorderable_list: ^0.0.1
```

```dart
import 'package:refreshable_reorderable_list/refreshable_reorderable_list.dart';
```

```dart
RefreshableReorderableListView(
  physics: AlwaysScrollableScrollPhysics(),
  onReorder: (oldIndex, newIndex) {
    //...
  },
  children: //...
),
```

**Comment by Bonsai11** [comment] 2020-12-21 17:42
@dave Wouldn't that be something you should rather try to get pulled in the actual widget and not create your own?

Is there any solution that does not require third party widgets or editing the flutter widgets code?

**Comment by dave** [comment] 2020-12-21 17:47
I'm pretty new at Flutter development so I was basically just randomly tweaking stuff so I have no idea if this method has side effects 😉

**Comment by nt4f04uNd** [comment] 2021-12-14 02:20
I cannot reproduce this on latest master

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const App());
}

class App extends StatelessWidget {
  const App({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'App',
      home: Scaffold(
        body: RefreshIndicator(
          onRefresh: () => Future.delayed(const Duration(seconds: 1)),
          child: ReorderableListView(
            header: null,
            onReorder: (_, __) {},
            children: [
              ListTile(key: ValueKey('1'), title: Text('1')),
              ListTile(key: ValueKey('2'), title: Text('2')),
              ListTile(key: ValueKey('3'), title: Text('3')),
            ],
            scrollDirection: Axis.vertical,
          ),
        ),
      ),
    );
  }
}
```
</details>

<details>
<summary>flutter doctor -v</summary>

```
[√] Flutter (Channel refresh, 2.6.0-12.0.pre.1015, on Microsoft Windows [Version 10.0.19041.1348], locale ru-RU)
    • Flutter version 2.6.0-12.0.pre.1015 at C:\dev\src\flutter
    • Upstream repository git@github.com:nt4f04und/flutter.git
    • FLUTTER_GIT_URL = git@github.com:nt4f04und/flutter.git
    • Framework revision 13fa98cf4e (4 hours ago), 2021-12-14 01:27:02 +0300
    • Engine revision f16c96c31f
    • Dart version 2.16.0 (build 2.16.0-85.0.dev)
    • DevTools version 2.9.1

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\danya\AppData\Local\Android\sdk
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.7)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30621.155
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 4.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Community Edition (version 2020.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.3.3
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code (version 1.63.0)
    • VS Code at C:\Users\danya\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.29.0

[√] Connected device (4 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)       • windows       • windows-x64    • Microsoft Windows [Version 10.0.19041.1348]
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 96.0.4664.93
    • Edge (web)              • edge          • web-javascript • Microsoft Edge 96.0.1054.53

! Doctor found issues in 1 category.
```
</details>

**Comment by TahaTesser** [comment] 2021-12-14 08:02
Closing per the last comment, please follow up there. Thanks!

**Closed by TahaTesser** 2021-12-14 08:02 UTC
Labels: framework, f: material design, has reproducible steps, found in release: 1.20
