### ISSUE TITLE
[tool_crash] FileSystemException: Cannot create link, OS Error: Incorrect function., errno = 1

### ISSUE THREAD

**Issue by ibrahimwswas5** [flutter/flutter#131570] opened 2023-07-30 12:43 UTC
## Command
```
flutter pub get
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Cannot create link, OS Error: Incorrect function.
, errno = 1
```
#0      _Link.throwIfError (dart:io/link.dart:254:7)
#1      _Link.createSync (dart:io/link.dart:182:5)
#2      ForwardingLink.createSync (package:file/src/forwarding/forwarding_link.dart:20:16)
#3      ForwardingLink.createSync (package:file/src/forwarding/forwarding_link.dart:20:16)
#4      _createPlatformPluginSymlinks (package:flutter_tools/src/flutter_plugins.dart:1055:12)
#5      createPluginSymlinks (package:flutter_tools/src/flutter_plugins.dart:985:5)
#6      refreshPluginsList (package:flutter_tools/src/flutter_plugins.dart:1087:5)
<asynchronous suspension>
#7      FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:355:5)
<asynchronous suspension>
#8      PackagesGetCommand.runCommand (package:flutter_tools/src/commands/packages.dart:326:7)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1336:27)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#11     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:296:9)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:244:5)
<asynchronous suspension>
#15     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:91:9)
```
```
[✓] Flutter (Channel stable, 3.10.5, on Microsoft Windows [Version 10.0.22621.2070], locale en-US)
    • Flutter version 3.10.5 on channel stable at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (7 weeks ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\ibrah\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Professional 2022 17.6.5)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Professional
    • Visual Studio Professional 2022 version 17.6.33829.357
    • Windows 10 SDK version 10.0.22000.0

[✓] Android Studio (version 2022.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)

[✓] VS Code (version 1.80.2)
    • VS Code at C:\Users\ibrah\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.68.0

[✓] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 14 (API 34) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.22621.2070]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 115.0.5790.110
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 115.0.1901.188

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 796c8ef79279f9c774545b3771238c3098dbefab
### Plugins
cloud_firestore-4.8.4
cloud_firestore_web-3.6.3
file_selector_linux-0.9.2
file_selector_macos-0.9.3+1
file_selector_windows-0.9.3
firebase_auth-4.7.2
firebase_auth_web-5.6.2
firebase_core-2.15.0
firebase_core_web-2.6.0
firebase_messaging-14.6.5
firebase_messaging_web-3.5.4
firebase_storage-11.2.5
firebase_storage_web-3.6.5
flutter_native_splash-2.3.1
flutter_plugin_android_lifecycle-2.0.15
google_sign_in-6.1.4
google_sign_in_android-6.1.18
google_sign_in_ios-5.6.2
google_sign_in_web-0.12.0+2
image_picker-1.0.1
image_picker_android-0.8.7+4
image_picker_for_web-2.2.0
image_picker_ios-0.8.8
image_picker_linux-0.2.1
image_picker_macos-0.2.1
image_picker_windows-0.2.1
path_provider_linux-2.1.11
path_provider_windows-2.1.7
rive_common-0.2.3
shared_preferences-2.2.0
shared_preferences_android-2.2.0
shared_preferences_foundation-2.3.2
shared_preferences_linux-2.3.0
shared_preferences_web-2.2.0
shared_preferences_windows-2.3.0

**Comment by danagbemava-nc** [comment] 2023-07-31 06:47
Closing this as a duplicate of https://github.com/flutter/flutter/issues/66224

**Closed by danagbemava-nc** 2023-07-31 06:47 UTC
Labels: in triage
