### ISSUE TITLE
Add multiple image picker to [image_picker] plugin

### ISSUE THREAD

**Issue by tbm98** [flutter/flutter#57097] opened 2020-05-13 09:53 UTC
I know plugin for multiple image picker is exist. But why doesn't the Flutter team add this feature to the existing image_picker library

**Comment by TahaTesser** [comment] 2020-05-13 10:16
duplicate of [#16054](https://github.com/flutter/flutter/issues/16054)

**Closed by TahaTesser** 2020-05-13 10:16 UTC
