### ISSUE TITLE
TextFormField multiline not recognising mouse events in web

### ISSUE THREAD

**Issue by jmolins** [flutter/flutter#57791] opened 2020-05-22 07:25 UTC
When using a `TextFormField` in Flutter Web taht it is configured for multiline, it does not responds to clicks and other mouse events.

The cursor is always kept at the first position of first line.

When there is only one line there is no such problem.

This behaviour can be tested in the Flutter Gallery TextFields section:

[https://gallery.flutter.dev/#/demo/text-field](https://gallery.flutter.dev/#/demo/text-field)

Just write some lines and try to position the cursor anywhere in the new lines.

**Comment by iapicca** [comment] 2020-05-22 08:00
Hi @jmolins 
running the [code](https://github.com/flutter/gallery) with the latest master

<details>
  <summary>logs</summary>

```bash
[+1080 ms] Debug service listening on ws://127.0.0.1:54004/CP2B3b000Zs=
[   +1 ms] Warning: Flutter's support for web development is not stable yet and hasn't
[        ] been thoroughly tested in production environments.
[        ] For more information see https://flutter.dev/web
[   +1 ms] 🔥  To hot restart changes while running, press "r" or "R".
[   +1 ms] For a more detailed help message, press "h". To quit, press "q".
[+4437 ms] Overflow on channel: flutter/mousecursor.  Messages on this channel are being discarded in FIFO fashion.  The engine may not be running or you need to adjust the
buffer size if
                    of the channel.

[+2366 ms] Overflow on channel: flutter/mousecursor.  Messages on this channel are being discarded in FIFO fashion.  The engine may not be running or you need to adjust the
buffer size if
                    of the channel.

[+7220 ms] Overflow on channel: flutter/mousecursor.  Messages on this channel are being discarded in FIFO fashion.  The engine may not be running or you need to adjust the
buffer size if
                    of the channel.

[  +69 ms] Overflow on channel: flutter/mousecursor.  Messages on this channel are being discarded in FIFO fashion.  The engine may not be running or you need to adjust the
buffer size if
           of the channel.

[+1376 ms] Overflow on channel: flutter/mousecursor.  Messages on this channel are being discarded in FIFO fashion.  The engine may not be running or you need to adjust the
buffer size if
                    of the channel.

[+9494 ms] Overflow on channel: flutter/mousecursor.  Messages on this channel are being discarded in FIFO fashion.  The engine may not be running or you need to adjust the
buffer size if
                    of the channel.

[+34180 ms] Stopped debug service on ws://127.0.0.1:54004

[ +109 ms] Application finished.
[   +4 ms] "flutter run" took 208,026ms.
[ +265 ms] Running shutdown hooks
[        ] Shutdown hook priority 4
[ +197 ms] Shutdown hooks complete
```

</details>


<details>
  <summary>doctor</summary>

```console
[✓] Flutter (Channel master, 1.19.0-2.0.pre.142, on Mac OS X 10.15.4 19E287, locale en-GB)
    • Flutter version 1.19.0-2.0.pre.142 at /Users/nevercode/development/flutter_master
    • Framework revision 721927efd3 (7 hours ago), 2020-05-21 17:52:02 -0700
    • Engine revision 9ce1e5c5c7
    • Dart version 2.9.0 (build 2.9.0-10.0.dev 7706afbcf5)


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/nevercode/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.9.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.2

[✓] Connected device (2 available)
    • Web Server • web-server • web-javascript • Flutter Tools
    • Chrome     • chrome     • web-javascript • Google Chrome 81.0.4044.138

• No issues found!
```

</details> 

the issue is still present
Thank you for reporting this

**Comment by yjbanov** [comment] 2020-05-28 22:23
The fix for this is the same as for https://github.com/flutter/flutter/issues/55627, so I will deduplicate this issue.

/cc @mdebbar @mariamhas

**Closed by yjbanov** 2020-05-28 22:23 UTC
Labels: a: text input, f: material design, found in release: 1.19, framework, has reproducible steps, platform-web

**Comment by mariamhas** [comment] 2020-05-28 22:26
workaround details for this issue can be found in this duplicate issue: https://github.com/flutter/flutter/issues/50101
