### ISSUE TITLE
"Adding in-app purchases" codelab does not work for Google Play

### ISSUE THREAD

**Issue by ccrusius** [flutter/flutter#102881] opened 2022-04-30 17:01 UTC
Here's the problem: in steps 10 and 11 of the [Adding in-app purchases to your flutter app](https://codelabs.developers.google.com/codelabs/flutter-in-app-purchases#10), when trying to keep track of purchases in Firestore, the Firestore functions provided in the codelab fail with

```
Error: 5 NOT_FOUND: No document to update: projects/texne-fb88c/databases/(default)/documents/purchases/google_play_GPA.3325-5681-0818-04289
    at Object.callErrorFromStatus (/workspace/node_modules/@grpc/grpc-js/build/src/call.js:31:26)
    at Object.onReceiveStatus (/workspace/node_modules/@grpc/grpc-js/build/src/client.js:189:52)
    at Object.onReceiveStatus (/workspace/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:365:141)
    at Object.onReceiveStatus (/workspace/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:328:181)
    at /workspace/node_modules/@grpc/grpc-js/build/src/call-stream.js:187:78
    at processTicksAndRejections (node:internal/process/task_queues:78:11) 
```

I believe this is due to the user ID not being plumbed through, and I can not see an elegant way of doing it. Any help or a fix to the codelab would be appreciated, as this is blocking further development.

Here's the code logic and why it fails as far as I can tell: the pub/sub gets handled by `handleServerEvent`, which in the Google case [always sets the user id to `null`](https://github.com/flutter/codelabs/blob/master/in_app_purchases/complete/firebase-backend/functions/src/google-play.purchase-handler.ts#L213). If this is `null`, [`handleSubscription` ends up calling `updatePurchase`](https://github.com/flutter/codelabs/blob/master/in_app_purchases/complete/firebase-backend/functions/src/google-play.purchase-handler.ts#L149) which then [calls Firestore's `update` on a non-existing document](https://github.com/flutter/codelabs/blob/master/in_app_purchases/complete/firebase-backend/functions/src/iap.repository.ts#L42). We then get the error above, always. I haven't set up the Apple Store yet, but from the code it looks like user IDs are properly plumbed.

**Comment by ccrusius** [comment] 2022-05-02 16:34
I found the problem yesterday - I was trying to monitor the Firestore backend without verifying purchases from the app: I had my IAP subscription just print out what was coming but doing little else. In that case I see the error (for the reasons mentioned above).

After adding the verification logic things work: the `verifyPurchase` HTTPS function is then called from the app, which means there's a user available, and `handleSubscription` gets what it needs.

So this isn't an urgent problem - but it may be worth highlighting that without the verification step the pub/sub scheme will raise errors every time there is a purchase.

**Comment by jbryanh** [comment] 2022-05-11 14:37
I've just finished debugging my implementation of this.  I could be wrong, but my sense is that some of this is by design, a simple, elegant, but a flawed design.  

On Android, on creation of a sub, the handleServerEvent must fail, because it can fire first (before your http call from client to validate and create the doc).  The reason it SHOULD fail is that no UID is provided, so you'd have incomplete info.  It fails because it's an update command, not set, and the doc isn't created yet.  

I had changed the updatePurchase to a set, with merge: true and tried to get a uid from Android unsuccessfully, which helped me square this flow in my mind.  So that error you see is good, and by design.  The validation and creation event initiated from your client is where your purchases doc will be initially created, not from the handleServerEvent.  The handleServerEvent only updates, without a need for a UID.

Now, for off the codelab scenarios where you are CHANGING subs (where handleServerEvent comes into play), the code lab provides an elegant, simple, yet somewhat frustrating design: the Android side always creates a new doc when starting or changing subscriptions.  This would be preferable, as you have a purchase history.  The frustrating part is the iOS side.

On Apple, there are no new docs created when changing subs within a group...they are simply updated.  This isn't optimal, as you have no history in your server (from the codebase implementation).  This is because Apple handles subscription changes within groups internally and sends server events to handle on your server.  So all changes are just handleServerEvents, but getting the UID, handling the order of the receipts and the considerable complexity with which Apple handles upgrades, cross-grades and down-grades probably was more than the code-lab folks wanted to take on.

To fix this, really, both stores require more unique handling of subscription changes, whereas, the codelab guys probably got stuck, were bothered that they were tracking a purchase history for Android, but not for Apple, but figured that with Apple going to v2 of server events, they'd be updating the codelab soon anyway, and would provide the better solution then.

So my request would be to fix the codelab to provide a purchase history for Apple consistent with Android., and handle the v2 notificaitions...which I hope gives a little better way to decode these sub changes and provide a history on your server from the serverEvents.  

In the meantime, the codelab is wrong on step 10.8, Instructions say to use Version 2 Notifications, which is wrong.  Use Version 1.

I started down the road of fixing everything to get a purchase history like Android for iOS, but i was unable to get the UID from serverEvents on apple either.  The plugin provides an applicationUserName, but getting it consistently through to the serverEvent seems to be quite an accomplishment.  app_account_token from latest receipt was always empty.  [It's been logged as a bug.](https://github.com/flutter/flutter/issues/95637)

**Comment by miquelbeltran** [comment] 2022-05-12 11:57
I've been working on reimplementing the codelab in Dart for the server instead of Node.js.

It is still pretty much work in progress, and unfortunately the Apple part is yet not done, but if you want to take a look, it is here: https://github.com/flutter/codelabs/pull/735 any feedback is appreciated

**Comment by miquelbeltran** [comment] 2023-03-02 10:09
Just for the record, the re-implementation of the codelab continues and you can follow the progress here: https://github.com/flutter/codelabs/pull/1447

**Comment by miquelbeltran** [comment] 2023-04-25 15:05
The codelab has been re-implemented, including the code that takes care of writing to Firestore. It should all work now.

**Closed by miquelbeltran** 2023-04-25 15:05 UTC
Labels: plugin, d: codelabs, p: in_app_purchase, documentation, P4
