### ISSUE TITLE
CheckedPopupMenuItem padding is too large

### ISSUE THREAD

**Issue by agordeev** [flutter/flutter#133116] opened 2023-08-23 08:47 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

[This issue](https://github.com/flutter/flutter/issues/3561) still persist. Apparently, `CheckedPopupMenuItem` is not Material3-ready yet.

### Expected results

![image](https://github.com/flutter/flutter/assets/2883524/80d75f62-751c-43ef-a3b2-d9edd2c0c962)

### Actual results

<img width="260" alt="Screenshot 2023-08-23 at 10 44 16" src="https://github.com/flutter/flutter/assets/2883524/418e0a12-3a32-4bab-9e13-50861026492a">

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);
  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: MyHomePage(
        title: 'Example',
      ),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final int _counter = 0;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          PopupMenuButton<String>(
            padding: EdgeInsets.zero,
            icon: const Text('Press me'),
            onSelected: (value) {},
            itemBuilder: (BuildContext context) => <PopupMenuEntry<String>>[
              PopupMenuItem(
                onTap: () {},
                child: const Row(
                  children: [
                    Icon(Icons.copy),
                    SizedBox(width: 16),
                    Text('PopupMenuItem looks good'),
                  ],
                ),
              ),
              const PopupMenuDivider(),
              const CheckedPopupMenuItem<String>(
                value: '1',
                checked: true,
                child: Text('First'),
              ),
              const CheckedPopupMenuItem<String>(
                value: '2',
                child: Text('Second'),
              ),
              const CheckedPopupMenuItem<String>(
                value: '3',
                child: Row(
                  children: [
                    Text('Third'),
                  ],
                ),
              ),
            ],
          ),
        ],
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.13.0, on macOS 13.4 22F66 darwin-arm64, locale en-RU)
    • Flutter version 3.13.0 on channel stable at /Users/andrey/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision efbf63d9c6 (7 days ago), 2023-08-15 21:05:06 -0500
    • Engine revision 1ac611c64e
    • Dart version 3.1.0
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/andrey/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.80.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.68.0

[✓] VS Code (version 1.82.0-insider)
    • VS Code at /Applications/Visual Studio Code - Insiders.app/Contents
    • Flutter extension version 3.71.20230801

[✓] Connected device (4 available)
    • sdk gphone64 arm64 (mobile)                    • emulator-5554                        • android-arm64  • Android 13 (API 33) (emulator)
    • iPad Pro (12.9-inch) (6th generation) (mobile) • CB4B1BFD-75B9-4611-B12E-D1323187943A • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)                                • macos                                • darwin-arm64   • macOS 13.4 22F66 darwin-arm64
    • Chrome (web)                                   • chrome                               • web-javascript • Google Chrome 116.0.5845.96

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by TahaTesser** [comment] 2023-08-23 09:12
Hi!

This is fixed in https://github.com/flutter/flutter/pull/132555 and it is currently on the `master` branch.
duplicate of https://github.com/flutter/flutter/issues/128553

**Closed by TahaTesser** 2023-08-23 09:12 UTC
Labels: in triage
