### ISSUE TITLE
pass themed context to new pages

### ISSUE THREAD

**Issue by DJafari** [flutter/flutter#93210] opened 2021-11-07 10:53 UTC
i'm not sure this is bug or normal behavior, please check my sample code, if it's normal, how can achieve to that ?

```dart
import 'package:flutter/material.dart';

void main() => runApp(MaterialApp(
  theme: ThemeData(
    colorScheme: ColorScheme.fromSwatch(
      primarySwatch: Colors.red,
    ),
  ),
  home: Builder(
    builder: (context) {
      print('base: ${Theme.of(context).colorScheme.primary}');
      return Scaffold(
        body: Center(
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              ElevatedButton(
                child: const Text("Button"),
                onPressed: () {},
              ),
              Theme(
                data: Theme.of(context).copyWith(
                  colorScheme: ColorScheme.fromSwatch(
                    primarySwatch: Colors.blue,
                  ),
                ),
                child: Builder(
                  builder: (context) {
                    print('themed: ${Theme.of(context).colorScheme.primary}');
                    return ElevatedButton(
                      child: const Text("Button"),
                      onPressed: () {
                        print('beforePush: ${Theme.of(context).colorScheme.primary}');
                        Navigator.of(context).push(MaterialPageRoute(
                          builder: (context) {
                            print('afterPush: ${Theme.of(context).colorScheme.primary}');
                            return Scaffold(
                              body: Center(
                                child: ElevatedButton(
                                  child: const Text("Button"),
                                  onPressed: () {},
                                ),
                              ),
                            );
                          },
                        ));
                      },
                    );
                  },
                ),
              ),
            ],
          ),
        ),
      );
    },
  ),
));
```

**flutter doctor -v :**

```
[✓] Flutter (Channel master, 2.6.0-12.0.pre.618, on macOS 12.0.1 21A559 darwin-arm, locale en-IR)
    • Flutter version 2.6.0-12.0.pre.618 at /Users/davood/fvm/versions/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3fba55a18d (4 hours ago), 2021-11-06 23:40:10 -0700
    • Engine revision 5140e30cec
    • Dart version 2.15.0 (build 2.15.0-268.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Volumes/My/SDK/Android
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Volumes/My/SDK/Android
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.28.0

[✓] Connected device (3 available)
    • iPhone 13 (mobile) • 4E79803B-8249-4839-82D9-3E40E230222D • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • macOS (desktop)    • macos                                • darwin-arm64   • macOS 12.0.1 21A559 darwin-arm
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 95.0.4638.69

• No issues found!
```

if you run my code see this log :

```
base: MaterialColor(primary value: Color(0xfff44336))
themed: MaterialColor(primary value: Color(0xff2196f3))
beforePush: MaterialColor(primary value: Color(0xff2196f3))
afterPush: MaterialColor(primary value: Color(0xfff44336))
```

i expect afterPush primary color be `MaterialColor(primary value: Color(0xff2196f3))` because i passed themed context to navigator but changed to base primary

thanks

**Comment by mamuseferha** [comment] 2021-11-08 07:46
Hi @DJafari `afterPush` primary color is different from `themed` primary color because they have different `BuildContext`. When you push to a new screen it has a different `BuildContext` context from the previous screen.

**Comment by HansMuller** [comment] 2021-11-08 23:28
You might want to take a look at [InheritedTheme.captureAll()](https://api.flutter.dev/flutter/widgets/InheritedTheme/captureAll.html), it can be used to "capture" the inherited themes visible from a BuildContext so that they can be applied in a new context.

**Comment by mamuseferha** [comment] 2021-11-09 07:04
Hi @DJafari 
Since this issue is not a bug or feature request, I'll go ahead and close it. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by mamuseferha** 2021-11-09 07:04 UTC
Labels: in triage
