### ISSUE TITLE
Is google_sign_in supported on macOS? Throws 

### ISSUE THREAD

**Issue by jshirley** [flutter/flutter#49508] opened 2020-01-26 14:05 UTC
This is similar to #14137 but with `flutter run -d macOS` I get the following error:
```
MissingPluginException (MissingPluginException(No implementation found for method init on channel plugins.flutter.io/google_sign_in))
```

## Steps to Reproduce

1. Setup flutter to enable the macos target
2. Run `flutter create bug`, import sign in content from [google_sign_in](https://github.com/flutter/plugins/blob/master/packages/google_sign_in/google_sign_in/example/lib/main.dart)
3. Follow the integration guide at https://github.com/flutter/plugins/tree/master/packages/google_sign_in/google_sign_in
4. Verify sign-in works with ios
5. Switch target to macos, get an error

**Expected results:** 

I would like to use google_sign_in with a macos target.

**Actual results:** 

Only works with iOS targets 😢 

(I omitted the logs in this report, but happy to put them in if this is something missing -- I suspect it is either some configuration undocumented and a documentation bug, or a relatively small change to the `google_sign_in` package. If it is something I can contribute with guidance, happy to do so but I'm very new to Flutter and Xcode)

**Comment by stuartmorgan** [comment] 2020-01-26 15:31
Duplicate of #46157.

In general, as noted [here](https://flutter.dev/desktop#plugin-support), most plugins do not yet support macOS. You can always [check the supported platforms in the pubspec.yaml](https://github.com/flutter/plugins/blob/master/packages/google_sign_in/google_sign_in/pubspec.yaml#L9)

> I suspect it is either some configuration undocumented and a documentation bug, or a relatively small change to the google_sign_in package.

Unfortunately not; see my comments in the other issue.

**Closed by stuartmorgan** 2020-01-26 15:32 UTC
