### ISSUE TITLE
Failed assertion: line 776 pos 12: 'elapsedInSeconds >= 0.0': is not true

### ISSUE THREAD

**Issue by timolehto** [flutter/flutter#43501] opened 2019-10-25 12:27 UTC
## Steps to Reproduce

Unfortunately I do not have a good repro on this. At least not yet. This is happening in our application sometimes when we have a long running `CircularProgressIndicator` (long running background process on the native Android side). When it happens the animation freezes. 

Sometimes, but this happens much less frequently, flutter freezes entirely too, i.e. becomes entirely unresponsive. I can see our native Android code continues to run, but can not click on anything in the app UI, even back button doesn't work.

I suppose this is a duplicate of https://github.com/flutter/flutter/issues/33193, but it lacked any information so it was closed. Linking to it just to show that apparently this is happening to others as well.

Issues are happening with Android 5.1.

**Target Platform:**
**Target OS version/browser:**
**Devices:**

## Logs

```
════════ Exception caught by scheduler library ═════════════════════════════════
The following assertion was thrown during a scheduler callback:
'package:flutter/src/animation/animation_controller.dart': Failed assertion: line 776 pos 12: 'elapsedInSeconds >= 0.0': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

When the exception was thrown, this was the stack
#2      AnimationController._tick 
package:flutter/…/animation/animation_controller.dart:776
#3      Ticker._tick 
package:flutter/…/scheduler/ticker.dart:228
#4      SchedulerBinding._invokeFrameCallback 
package:flutter/…/scheduler/binding.dart:1043
#5      SchedulerBinding.handleBeginFrame.<anonymous closure> 
package:flutter/…/scheduler/binding.dart:958
#6      _LinkedHashMapMixin.forEach  (dart:collection-patch/compact_hash.dart:377:8)
...

This exception was thrown in the context of a scheduler callback. When the scheduler callback was _registered_ (as opposed to when the exception was thrown), this was the stack
#0      new _FrameCallbackEntry.<anonymous closure> 
package:flutter/…/scheduler/binding.dart:112
#1      new _FrameCallbackEntry 
package:flutter/…/scheduler/binding.dart:115
#2      SchedulerBinding.scheduleFrameCallback 
package:flutter/…/scheduler/binding.dart:459
#3      Ticker.scheduleTick 
package:flutter/…/scheduler/ticker.dart:243
#4      Ticker.start 
package:flutter/…/scheduler/ticker.dart:159
...

```

```
flutter analyze
Analyzing mobile_client...

   info • Name non-constant identifiers using lowerCamelCase • lib/card_issuing_wizard/take_photo_page.dart:31:9 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/widgets.dart:24:8 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/widgets.dart:31:8 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/widgets.dart:37:8 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/widgets.dart:43:8 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/widgets.dart:55:8 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/widgets.dart:66:8 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/widgets.dart:80:8 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/widgets.dart:92:8 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/widgets.dart:104:8 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/widgets.dart:116:8 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/widgets.dart:129:8 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/widgets.dart:146:8 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/widgets.dart:159:8 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/widgets.dart:168:8 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/widgets.dart:177:8 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/widgets.dart:216:8 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/widgets.dart:236:8 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/widgets.dart:254:8 • non_constant_identifier_names

19 issues found. (ran in 3.1s)
```

```
flutter doctor -v
[✓] Flutter (Channel beta, v1.10.7, on Mac OS X 10.14.6 18G95, locale en-FI)
    • Flutter version 1.10.7 at /Users/timok/personal/flutter
    • Framework revision e70236e36c (3 weeks ago), 2019-10-02 09:32:30 -0700
    • Engine revision 9e6314d348
    • Dart version 2.6.0 (build 2.6.0-dev.0.0 1103600280)


[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/timok/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install:
        sudo gem install cocoapods

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 40.2.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] IntelliJ IDEA Ultimate Edition (version 2019.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    • Dart plugin version 191.8369
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] Connected device (1 available)
    • FP07 • HF20190401000458 • android-arm • Android 5.1 (API 21)

! Doctor found issues in 2 categories.
```

**Comment by timolehto** [comment] 2019-10-25 13:34
It seems this is related to debug mode (well I guess the asserts are removed from release builds?) only. I've not able to repro any kind of animation or app freezes with release mode builds. Still this is very annoying.

**Comment by iapicca** [comment] 2019-10-25 14:23
Hi @timolehto 
you might want to take a look at this possible [solution](https://flutter.dev/docs/testing/debugging#debug-mode-assertions)
Thank you

**Comment by timolehto** [comment] 2019-10-25 19:43
@iapicca thanks, but could you elaborate a bit on that? Are you suggesting to use `release` mode in order to avoid assertions or was there some other option I could try and tweak? I mean, I already said it works with `release` mode. It confirmed my suspicion that the asserts are removed from release builds, so that was great information at least. However, developing in `release` mode is kinda pita, so would be great to be able to run the app reliably in `debug` mode as well... as I'm not able to make the app freeze in release mode I assume the debug mode not only leaves out the asserts, but also somehow causes the total freezes where flutter just dies completely.

**Comment by TahaTesser** [comment] 2020-04-30 14:27
Hi @timolehto 
Are you still experiencing with this issue with latest stable?
if yes,  can you please provide your `flutter doctor -v` and `flutter run --verbose`? Also, to better address the issue, would be helpful
if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by timolehto** [comment] 2020-04-30 16:43
@TahaTesser I'm not currently able to reproduce this issue. Not sure if it's due to significant changes in our code base or due to fixes in Flutter.

**Comment by VladyslavBondarenko** [comment] 2020-05-27 13:24
Then closing the issue.
Could everyone who still has this problem please comment or file a new issue with linking the current one, descriptions what happens, reproducible code sample/project, logs and the output of `flutter doctor -v`.

**Closed by VladyslavBondarenko** 2020-05-27 13:24 UTC
Labels: in triage, waiting for customer response

**Comment by hongfeiyang** [comment] 2020-11-21 08:35
I am able to produce this bug while on the master channel
`'package:flutter/src/animation/animation_controller.dart': Failed assertion: line 802 pos 12: 'elapsedInSeconds >= 0.0': is not true.`

and there are some additional info 
```

When the exception was thrown, this was the stack
#2      AnimationController._tick
package:flutter/…/animation/animation_controller.dart:802
#3      Ticker._tick
package:flutter/…/scheduler/ticker.dart:238
#4      SchedulerBinding._invokeFrameCallback
package:flutter/…/scheduler/binding.dart:1119
#5      SchedulerBinding.handleBeginFrame.<anonymous closure>
package:flutter/…/scheduler/binding.dart:1033
#6      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:387:8)
...

This exception was thrown in the context of a scheduler callback. When the scheduler callback was _registered_ (as opposed to when the exception was thrown), this was the stack
#2      SchedulerBinding.scheduleFrameCallback
package:flutter/…/scheduler/binding.dart:523
#3      Ticker.scheduleTick
package:flutter/…/scheduler/ticker.dart:253
#4      Ticker.start
package:flutter/…/scheduler/ticker.dart:162
#5      AnimationController._startSimulation
package:flutter/…/animation/animation_controller.dart:727
#6      AnimationController.animateWith
package:flutter/…/animation/animation_controller.dart:718
...
```

This bug occurs while I was running my application in debug mode on iOS 14.2 on my iPad Pro 1st gen, macOS 11.0.1

I was building a gallery application which involves of loading large images. I loaded a 54MB image using the MemoryImage() widget and sometime it triggers this bug, sometimes it doesn't.  I am not sure why.

```
[✓] Flutter (Channel master, 1.24.0-8.0.pre.321, on macOS 11.0.1 20B29 darwin-x64, locale en-AU)
    • Flutter version 1.24.0-8.0.pre.321 at /Users/H.F.Yang/flutter
    • Framework revision 05dadb0120 (31 hours ago), 2020-11-20 07:33:05 +0530
    • Engine revision a0da844845
    • Dart version 2.12.0 (build 2.12.0-50.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/H.F.Yang/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.1.4)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 47.1.3
    • Dart plugin version 201.7846.93

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (4 available)
    • Hongfei’s iPad (mobile) •xxxx(my device id) • ios            • iOS 14.2
    • macOS (desktop)         • macos                                    • darwin-x64     • macOS 11.0.1 20B29 darwin-x64
    • Web Server (web)        • web-server                               • web-javascript • Flutter Tools
    • Chrome (web)            • chrome                                   • web-javascript • Google Chrome 86.0.4240.198

• No issues found!
```

**Comment by hongfeiyang** [comment] 2020-11-21 08:46
ok I used `flutter run --verbose` and have captured some detailed debug info:

```
[+10432 ms] flutter: ══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
[   +2 ms] flutter: The following assertion was thrown during a scheduler callback:
[        ] flutter: 'package:flutter/src/animation/animation_controller.dart': Failed assertion: line 802 pos 12:
[        ] flutter: 'elapsedInSeconds >= 0.0': is not true.
[        ] flutter:
[        ] flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
[        ] flutter: more information in this error message to help you determine and fix the underlying cause.
[        ] flutter: In either case, please report this assertion by filing a bug on GitHub:
[        ] flutter:   https://github.com/flutter/flutter/issues/new?template=2_bug.md
[        ] flutter:
[        ] flutter: When the exception was thrown, this was the stack:
[        ] flutter: #2      AnimationController._tick (package:flutter/src/animation/animation_controller.dart:802:12)
[        ] flutter: #3      Ticker._tick (package:flutter/src/scheduler/ticker.dart:238:12)
[   +9 ms] flutter: #4      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1119:15)
[        ] flutter: #5      SchedulerBinding.handleBeginFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:1033:11)
[        ] flutter: #6      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:387:8)
[        ] flutter: #7      SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:1031:17)
[        ] flutter: #8      SchedulerBinding._handleBeginFrame (package:flutter/src/scheduler/binding.dart:965:5)
[        ] flutter: #12     _invoke1 (dart:ui/hooks.dart:176:10)
[        ] flutter: #13     PlatformDispatcher._beginFrame (dart:ui/platform_dispatcher.dart:231:5)
[        ] flutter: #14     _beginFrame (dart:ui/hooks.dart:108:31)
[        ] flutter: (elided 5 frames from class _AssertionError and dart:async)
[        ] flutter:
[        ] flutter:
[        ] flutter: This exception was thrown in the context of a scheduler callback. When the scheduler callback was _registered_ (as opposed to when the exception was
thrown), this was the stack:
[        ] flutter: #2      SchedulerBinding.scheduleFrameCallback (package:flutter/src/scheduler/binding.dart:523:49)
[        ] flutter: #3      Ticker.scheduleTick (package:flutter/src/scheduler/ticker.dart:253:47)
[        ] flutter: #4      Ticker.start (package:flutter/src/scheduler/ticker.dart:162:7)
[        ] flutter: #5      AnimationController._startSimulation (package:flutter/src/animation/animation_controller.dart:727:42)
[        ] flutter: #6      AnimationController.animateWith (package:flutter/src/animation/animation_controller.dart:718:12)
[        ] flutter: #7      new BallisticScrollActivity (package:flutter/src/widgets/scroll_activity.dart:524:9)
[        ] flutter: #8      ScrollPositionWithSingleContext.goBallistic (package:flutter/src/widgets/scroll_position_with_single_context.dart:147:21)
[        ] flutter: #9      ScrollDragController.end (package:flutter/src/widgets/scroll_activity.dart:399:14)
[        ] flutter: #10     ScrollableState._handleDragEnd (package:flutter/src/widgets/scrollable.dart:607:12)
[        ] flutter: #11     DragGestureRecognizer._checkEnd.<anonymous closure> (package:flutter/src/gestures/monodrag.dart:467:47)
[        ] flutter: #12     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:183:24)
[        ] flutter: #13     DragGestureRecognizer._checkEnd (package:flutter/src/gestures/monodrag.dart:467:5)
[        ] flutter: #14     DragGestureRecognizer.didStopTrackingLastPointer (package:flutter/src/gestures/monodrag.dart:379:9)
[        ] flutter: #15     OneSequenceGestureRecognizer.stopTrackingPointer (package:flutter/src/gestures/recognizer.dart:342:9)
[        ] flutter: #16     DragGestureRecognizer._giveUpPointer (package:flutter/src/gestures/monodrag.dart:388:5)
[        ] flutter: #17     DragGestureRecognizer.handleEvent (package:flutter/src/gestures/monodrag.dart:312:7)
[        ] flutter: #18     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:77:12)
[        ] flutter: #19     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:122:9)
[        ] flutter: #20     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:387:8)
[        ] flutter: #21     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:120:18)
[        ] flutter: #22     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:106:7)
[        ] flutter: #23     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:381:19)
[        ] flutter: #24     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:361:22)
[        ] flutter: #25     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:279:11)
[        ] flutter: #26     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:316:7)
[        ] flutter: #27     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:280:5)
[        ] flutter: #28     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:238:7)
[        ] flutter: #29     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:221:7)
[        ] flutter: #33     _invoke1 (dart:ui/hooks.dart:176:10)
[        ] flutter: #34     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:276:7)
[        ] flutter: #35     _dispatchPointerDataPacket (dart:ui/hooks.dart:96:31)
[        ] flutter: (elided 5 frames from class _FrameCallbackEntry and dart:async)
[        ] flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by hongfeiyang** [comment] 2020-11-21 09:00
[file.txt](https://github.com/flutter/flutter/files/5577290/file.txt)
full debug info

**Comment by iapicca** [comment] 2020-11-21 10:04
@hongfeiyang  could you please file a new issue as suggested [here](https://github.com/flutter/flutter/issues/43501#issuecomment-634658846), providing a minimal reproducible code sample as well

> Could everyone who still has this problem please comment or file a new issue with linking the current one, descriptions what happens, reproducible code sample/project, logs and the output of `flutter doctor -v`.

**Comment by hongfeiyang** [comment] 2020-11-21 12:10
> @hongfeiyang  could you please file a new issue as suggested [here](https://github.com/flutter/flutter/issues/43501#issuecomment-634658846), providing a minimal reproducible code sample as well
> 
> 
> 
> > Could everyone who still has this problem please comment or file a new issue with linking the current one, descriptions what happens, reproducible code sample/project, logs and the output of `flutter doctor -v`.
> 
> 

It's very difficult for me to give you a minimal sample code cause I don't know exactly how this bug can occur, unless I give you my full project but that is against the company's policy... I can provide any other additional material though,

**Comment by iapicca** [comment] 2020-11-21 13:35
@hongfeiyang 
for the issue to be workable need to be reproducible 
and without a code sample there is no way to discriminate between a flutter bug or an issue with your implementation

please do not provide production code, just a minimal code sample
thanks

**Comment by hongfeiyang** [comment] 2020-11-21 13:38
> @hongfeiyang 
> 
> for the issue to be workable need to be reproducible 
> 
> and without a code sample there is no way to discriminate between a flutter bug or an issue with your implementation
> 
> 
> 
> please do not provide production code, just a minimal code sample
> 
> thanks 

I will try to isolate this issue in a code sample.

**Comment by timolehto** [comment] 2020-11-25 13:31
@hongfeiyang if you manage to create that repro and new issue be sure to link to this existing one as well. I'm very interested in this case though it presently has not been haunting us that much anymore..

**Comment by timolehto** [comment] 2020-11-25 13:37
Dealing with images, background processes and circular progress indicator.. sounds a lot like what we have had so it must be something related to that combination.. we have this animated gif which is probably fairly "large", though really not that large, like 500 kilos or so.

**Comment by hongfeiyang** [comment] 2020-11-26 02:24
> Dealing with images, background processes and circular progress indicator.. sounds a lot like what we have had so it must be something related to that combination.. we have this animated gif which is probably fairly "large", though really not that large, like 500 kilos or so.

Yea and I noticed this will get triggered while scrolling with a layout builder of multiple isolates downloading images and each one showing a circular progress indicator. On stable channel it seems to jank as well, just that it does not throw this error unlike on the master channel. I am a bit busy with this project recently and will try to create a repo once my currently project got released (and I seriously need to investigate into this issue)

**Comment by hongfeiyang** [comment] 2020-12-10 06:04
> Dealing with images, background processes and circular progress indicator.. sounds a lot like what we have had so it must be something related to that combination.. we have this animated gif which is probably fairly "large", though really not that large, like 500 kilos or so.

I put everything in single thread and not use multiple isolates together and the problem is gone...

**Comment by hongfeiyang** [comment] 2020-12-10 23:37
I think this problem only occurs on iOS 14. Same code running on iOS 13.3 does not have the issue, but iOS 14.2 does.

**Comment by hongfeiyang** [comment] 2020-12-16 03:56
@iapicca @timolehto 
Here is a small code snippet to reproduce this bug but it may not be consistent.
```
import 'package:flutter/material.dart';
void main() {
  runApp(MyApp());
}
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}
class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;
  @override
  _MyHomePageState createState() => _MyHomePageState();
}
class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
            InnerWidget(
              callback: triggerBugFn,
            ),
          ],
        ),
      ),
    );
  }
  Future<void> triggerBugFn() async {
    // This will trigger the ElapsedSeconds >= 0 assertion bug
    Scaffold.of(context).showSnackBar(SnackBar(content: Text('test')));
  }
}
class InnerWidget extends StatefulWidget {
  InnerWidget({this.callback});
  final VoidCallback callback;
  @override
  _InnerWidgetState createState() => _InnerWidgetState();
}
class _InnerWidgetState extends State<InnerWidget> {
  @override
  Widget build(BuildContext context) {
    return FlatButton(
      onPressed: () {
        widget.callback();
      },
      child: Icon(Icons.radio_button_checked),
    );
  }
}
```

***How to reproduce***
create a new flutter project, replace everything in main with the snippet above. Use a **real** device (mine is iPad Pro 12.9 1st gen, running iOS 14.2, simulator may not be able to reproduce this error), compile using the latest flutter stable channel (as of the day of this post) its 
```
Flutter 1.22.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 7891006299 (5 days ago) • 2020-12-10 11:54:40 -0800
Engine • revision ae90085a84
Tools • Dart 2.10.4
```
Then immediately after it loads on your physical device, press the only button at the centre of this page as many times as fast as you can, then you may get the animation elapsed seconds >= 0 assertion error.

I know calling a snacker bar in this case is illegal, because scaffold.of(context) does not have a valid context in this case, but at least it should show a `Scaffold` related error, not an animation elapsed seconds >= 0 issue. My original code is not doing illegal things like this but its too complicated to isolate, and I know this might not be a fair example, but I hope by looking into this issue, it may provide some insight in finding out the underlying animation issue.

**Comment by iapicca** [comment] 2020-12-16 09:36
@hongfeiyang 

I believe the problem is with your code
please check the fix below

```diff
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ), 
-            InnerWidget(
-              callback: triggerBugFn,
-             ),
+            Builder(
+               builder: (context) => InnerWidget(   /// <= `this context has a Scaffold`
+                callback: () => Scaffold.of(context).showSnackBar(
+                  SnackBar(
+                    content: Text('test'),
+                  ),
+                ),
+              ),
            ),
          ],
        ),
      ),
    );
  }

  /// `this is the wrong 'context'`, it doesn't have a scaffold
-   Future<void> triggerBugFn() async {
-     // This will trigger the ElapsedSeconds >= 0 assertion bug
-     Scaffold.of(context).showSnackBar(SnackBar(content: Text('test')));
-   }
}

class InnerWidget extends StatefulWidget {
  InnerWidget({this.callback});
  final VoidCallback callback;
  @override
  _InnerWidgetState createState() => _InnerWidgetState();
}

class _InnerWidgetState extends State<InnerWidget> {
  @override
  Widget build(BuildContext context) {
    return FlatButton(
      onPressed: () {
        widget.callback();
      },
      child: Icon(Icons.radio_button_checked),
    );
  }
}

```

**Comment by tree1891** [comment] 2021-01-18 13:54
`════════ Exception caught by scheduler library ═════════════════════════════════
The following assertion was thrown during a scheduler callback:
'package:flutter/src/animation/animation_controller.dart': Failed assertion: line 789 pos 12: 'elapsedInSeconds >= 0.0': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

When the exception was thrown, this was the stack
#2      AnimationController._tick
package:flutter/…/animation/animation_controller.dart:789
#3      Ticker._tick
package:flutter/…/scheduler/ticker.dart:238
#4      SchedulerBinding._invokeFrameCallback
package:flutter/…/scheduler/binding.dart:1117
#5      SchedulerBinding.handleBeginFrame.<anonymous closure>
package:flutter/…/scheduler/binding.dart:1031
#6      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
...

This exception was thrown in the context of a scheduler callback. When the scheduler callback was _registered_ (as opposed to when the exception was thrown), this was the stack
#2      SchedulerBinding.scheduleFrameCallback
package:flutter/…/scheduler/binding.dart:523
#3      Ticker.scheduleTick
package:flutter/…/scheduler/ticker.dart:253
#4      Ticker.start
package:flutter/…/scheduler/ticker.dart:162
#5      AnimationController._startSimulation
package:flutter/…/animation/animation_controller.dart:714
#6      AnimationController.animateWith
package:flutter/…/animation/animation_controller.dart:705
...
`
