### ISSUE TITLE
Ability to use Canvas in Isolates

### ISSUE THREAD

**Issue by nfriend** [flutter/flutter#75755] opened 2021-02-10 01:17 UTC
## Use case

I'm building a drawing application that renders _lots_ of lines:

<p align="center">
   <img src="https://user-images.githubusercontent.com/1638631/107449305-559e8400-6b11-11eb-9e4c-6ddeddf47a10.gif">
</p>

Since each of these designs can include hundreds of thousands of points, I regularly (every 1000 points) rasterize the line, set the result as the background image of the drawing canvas, and remove the captured points. This keeps the total number of non-rasterized lines low and keeps the frame-rate high even after lots of drawing.

### The problem

However, there's a noticeable jank when I perform this rasterization process. (You can see it happen about 5 times in the GIF above.)

I've already optimized this process a bit by breaking the background canvas into tiles and only updating the tiles that have changed. This helps tremendously, but it's still not enough to avoid noticeable jank.

### My attempt at a solution

I thought moving this rasterization process to an [`Isolate`](https://api.dart.dev/stable/2.10.5/dart-isolate/Isolate-class.html) might help smooth the frame rate a bit. However, `dart:ui` isn't available in `Isolate`s ([source](https://github.com/flutter/flutter/issues/10647#issuecomment-308019915)).

## Proposal

Allow a `Canvas` to be instantiated and rendered in a `Isolate`. This would allow computationally complex image manipulations to be performed off the main Isolate.

## Related issues

- https://github.com/flutter/flutter/issues/53985
- https://github.com/flutter/flutter/issues/13343
- https://github.com/flutter/flutter/issues/10647

### Disclaimer

I'm not actually sure if this would solve my problem - perhaps copying the image data between `Isolate`s would be just as expensive as the render itself 🤷 

## Source code

In case it's useful, the source code for my Flutter app can be found here: https://gitlab.com/nfriend/inspiral

**Comment by Solido** [comment] 2021-03-10 15:24
Follow-up on this since I am stuck with the same problem for advanced rendering.

**Comment by steffenSuess** [comment] 2021-03-12 19:39
I could also use this feature very well when generating images for PDFs.

**Comment by JonLatane** [comment] 2021-05-11 22:27
This would be immensely useful for my app [BeatScratch](https://beatscratch.io).

**Comment by rlueders** [comment] 2022-09-28 19:58
@nfriend ,  how did you work around this, or is the rasterization jank unavoidable with Flutter?

**Comment by nfriend** [comment] 2022-09-29 00:09
@rlueders If I remember correctly, I did not find a solution 😞 The jank shown in the screenshot above is still present in the production version of my app.

**Comment by FaFre** [comment] 2023-02-17 16:56
Right now this is a huge bottleneck for rendering vector tiles directly in dart, which would massively benefit from this feature. A lot of users are waiting for a performance improvement (https://github.com/greensopinion/flutter-vector-map-tiles)

**Comment by rlueders** [comment] 2023-02-17 17:05
> Right now this is a huge bottleneck for rendering vector tiles directly in dart, which would massively benefit from this feature. A lot of users are waiting for a performance improvement (https://github.com/greensopinion/flutter-vector-map-tiles)

FYI, you can use most of dart.UI from [Flutter Isolates](https://pub.dev/packages/flutter_isolate).   I have been using it for a while with dramatic improvements when generating hundreds of thousands of images from Canvas. However, use with caution as calls dart.ui from Flutter Isolates seems to have broken after I enable Impeller on IOS.  Still works with on Android and with Impeller disabled.

**Comment by Medit8r** [comment] 2023-04-06 20:45
Perhaps the issue could be addressed by allowing the creation of lightweight Flutter engines in isolates in a pure Flutter app (not Add-to-app)?  Since the lightweight Flutter engines share some context they would start up quickly, but would allow the developer to generate images in background isolates.  This would open up so many GIS use cases, given the amount of data and rendering which is required!!  Restricting the use of writing to the Canvas to a single thread, means for all intents and purposes, a Flutter GIS solution is an order of magnitude slower than a native GIS implementation. (Even in Xamarin you can draw to the canvas in background threads).

**Comment by jonahwilliams** [comment] 2024-09-18 16:01
Duplicate of https://github.com/flutter/flutter/issues/13343

**Closed by jonahwilliams** 2024-09-18 16:01 UTC
Labels: c: new feature, engine, a: images, c: proposal, c: rendering, P3, team-engine, triaged-engine
