### ISSUE TITLE
Slow Firestore query on large collections

### ISSUE THREAD

**Issue by uehsnap** [flutter/flutter#18570] opened 2018-06-18 14:55 UTC
A simple query like 
```
firestore.collection('small_collection').limit(1).getDocuments()
```
on a relatively small collection is almost "instantaneous". However, the same query on a collection with more than 100k documents takes more than 10-20s.
I think this is a `cloud_firestore` plugin issue because this query running on Python on the same large collection is also "instantaneous".

**Comment by zoechi** [comment] 2018-06-18 15:44
Please add the output of `flutter doctor` and the cloud_firestore version you are using.

@collinjackson

**Comment by uehsnap** [comment] 2018-06-18 17:16
I'm using cloud_firestore 0.7.3 and below is the output of flutter doctor

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.4.4, on Mac OS X 10.13.5 17F77, locale en-BR)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.4)
[✓] Android Studio (version 3.1)
[✓] Connected devices (1 available)

• No issues found!
Process finished with exit code 0

Also, when I run the query on a small collection there's no output on Android Studio's console. However, when running on the large collections there're dozens of outputs like these:

> W/CursorWindow( 6915): Window is full: requested allocation 2355 bytes, free space 1925 bytes, window size 2097152 bytes
> I/art     ( 6915): Background partial concurrent mark sweep GC freed 5351226(159MB) AllocSpace objects, 0(0B) LOS objects, 35% free, 28MB/44MB, paused 1.453ms total 198.925ms

Thank you for your help.

**Comment by eharango** [comment] 2018-06-22 18:04
I'm seeing the same problem, with a 10k collection.

flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.5.1, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] Android Studio (version 3.1)
[!] VS Code (version 1.24.1)
[✓] Connected devices (1 available)

! Doctor found issues in 1 category.

**Comment by BerndWessels** [comment] 2018-08-19 21:56
I'm seeing this too

```
W/CursorWindow(21291): Window is full: requested allocation 253420 bytes, free space 67821 bytes, window size 2097152 bytes
W/CursorWindow(21291): Window is full: requested allocation 253420 bytes, free space 68329 bytes, window size 2097152 bytes
I/zygote64(21291): Background concurrent copying GC freed 535155(13MB) AllocSpace objects, 5(1240KB) LOS objects, 50% free, 17MB/35MB, paused 60us total 102.836ms
I/zygote64(21291): Background concurrent copying GC freed 586382(13MB) AllocSpace objects, 9(1508KB) LOS objects, 49% free, 24MB/48MB, paused 102us total 212.880ms
```

And I do only have a few dozens of documents returned from the request.

This also seems to put huge load on the main thread and the navigation stutters (at least in debug, haven't build the release version yet).

Any ideas?

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel dev, v0.5.8, on Microsoft Windows [Version 10.0.17134.228], locale en-NZ)
[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[√] Android Studio (version 3.1)
[√] IntelliJ IDEA Community Edition (version 2017.3)
[√] Connected devices (1 available)

• No issues found!
```

**Comment by aureliopetrone** [comment] 2018-09-08 21:31
@BerndWessels it's the same for me. I've a collection of 5k documents and it takes 10s to load. 

Is there any workaround?

**Comment by 5ummit** [comment] 2018-10-14 22:06
Any fixes?

**Comment by xqwzts** [comment] 2018-10-25 23:11
Started seeing this as well on previously stable versions. Upgrading dependencies did not resolve it.

A few notes of what I'm seeing:

Web versions of the same query work fine.

The collection being queried is large, but the query result only contains a single document.

This behavior started appearing for no obvious reason, no packages were upgraded, the queries were not modified - but the collection did grow in size.

Running in debug mode (with a simple DateTime.now() comparison for timing) to resolve a query that returns a single document.takes ~20 seconds on first run, and ~10 seconds on subsequent runs.

Resolving the query to a Future (via `.getDocuments()`) or a Stream (via `.snapshots()`) makes no difference.



Previous versions: Flutter 0.8.2 / cloud_firestore 0.7.3:
```
[✓] Flutter (Channel beta, v0.8.2, on Linux, locale en_US.UTF-8)
    • Flutter version 0.8.2 at /home/vic/devel/flutter
    • Framework revision 5ab9e70727 (7 weeks ago), 2018-09-07 12:33:05 -0700
    • Engine revision 58a1894a1c
    • Dart version 2.1.0-dev.3.1.flutter-760a9690c2
```

Upgraded to latest (beta): Flutter 0.9.4 / cloud_firestore 0.8.2+1
```
[✓] Flutter (Channel beta, v0.9.4, on Linux, locale en_US.UTF-8)
    • Flutter version 0.9.4 at /home/vic/devel/flutter
    • Framework revision f37c235c32 (4 weeks ago), 2018-09-25 17:45:40 -0400
    • Engine revision 74625aed32
    • Dart version 2.1.0-dev.5.0.flutter-a2eb050044

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /home/vic/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /usr/local/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)
    • All Android licenses accepted.
```

**Comment by xqwzts** [comment] 2018-10-25 23:58
Resolved by disabling firestore persistence, it seems that Firestore persists by loading the whole database [just the collection being queried?] and then querying locally. So even a query with `limit(1)` would load all the data. 

My assumption is that the data has grown to such a point that it can no longer be held in memory, so loading it seems to thrash while the GC clears up space to continue and query [?!].

Surprisingly this happens on every query, not just the very first, so I guess as long as the app is online, every query will download the whole collection :confused: 

Disabling persistence results in sub-second loading:

````
  await Firestore.instance.settings(
    persistenceEnabled: false,
    timestampsInSnapshotsEnabled: true,
  );
```

**Comment by blaneyneil** [comment] 2018-11-04 21:49
can confirm that performance really degraded once a collection i was querying got to over 1k records. i'm querying about 12 snapshots concurrently:
```

    List<Future<QuerySnapshot>> _feeds = [];

    for (var i = 0; i < docs.length; i++) {

      String _id = docs[i].data['id'];

      _feeds.add(dbTable
        .where('id', isEqualTo: _id)
        .limit(1)
        .getDocuments()
      );
    }

   Stopwatch stopwatch = new Stopwatch()..start();

    Future.wait(_feeds, eagerError: false, cleanUp: (val) {
      print(val);
    }).then((result){
      print('took ${stopwatch.elapsed}');
    }).catchError(print);

```
prior to the last several days, when dbTable only had 100-200 records, this always finished in less than a second (i wasn't using Stopwatch til now, so don't have an actual number).  now, after batch inserting over 1k records, it takes 6-7 seconds to return.  and the above query is stripped down - the real one had 2 more where clauses, an orderby, and a limit of 50.

cloud_firestore: "^0.8.2+1"

[✓] Flutter (Channel dev, v0.10.2, on Mac OS X 10.14 18A391, locale en-US)
    • Flutter version 0.10.2 at /Users/neil/flutter
    • Framework revision d8cbb80206 (10 days ago), 2018-10-26 01:30:21 -0400
    • Engine revision 6c2ade9fa2
    • Dart version 2.1.0-dev.8.0.flutter-bf26f760b1

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/neil/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 29.1.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] Connected device (1 available)
    • iPhone X      • 09913D8F-AAA2-4959-B2DA-06D3229A683A     • ios • iOS 12.1 (simulator)

• No issues found!

**Comment by blaneyneil** [comment] 2018-11-04 22:39
running the real query on my current data took 8 seconds.  i deleted approx 800 records from that dbTable and it's now 1.1 seconds.  dbTable has 26 fields, mostly strings and bools, and negligible amounts of data in each field.

**Comment by blaneyneil** [comment] 2018-12-10 06:55
this is also a problem that's far more pronounced on iOS.   using my aforementioned ~12 concurrent calls, with and without @xqwzts solution:

iOS
----------------------
persistenceEnabled: true - 2.96 seconds 
persistenceEnabled: false - 2.3 seconds 

android
----------------------
persistenceEnabled: true -  2.47 seconds 
persistenceEnabled: false -  0.38 seconds

**Comment by BerndWessels** [comment] 2018-12-13 00:48
Not sure how related this is, but I have a loading indicator and it seems that

`persistenceEnabled: true` blocks the UI and the loading indicator animation stutters and gets stuck.

`persistenceEnabled: false` takes longer but leaves the loading indicator animation much smoother.

I even put the deserialization (using `built_value`) into another "threat" via `compute(...)` which makes me think that `persistenceEnabled: true` really messes up the UI "threat".

**Comment by ssp** [comment] 2019-01-04 14:03
I am also seeing performance issues with the cloud_firestore once my collection grows in size.

More specifically: I want to sync a large (10K-100K) collection of small (~1KiB) documents to my app so they can also be accessed offline.

That part on its own seems to work just fine: Documents are available in the app and running queries with few results on them is fast.

However, running large updates on the underlying data in Firestore (e.g. deleting all documents in Firestore and then adding them again) seems to be very slow in apps (Android on phone or in the Simulator) or make them freeze.

I wouldn’t even mind the update itself taking a while in the background but the UI seems to lock up as well while the update is running (which breaks the charm of having out-of-the-box data-sync for offline usage), rendering the app unusable.

As my issue feels similar to what is described in this ticket, I am adding this comment. Please let me know if this sounds different to you and should be in a separate ticket.

In case the data volume I have in mind exceeds the scope Firestore and its flutter integration are designed for, it would also be helpful to know the intended limits of the technology, so I can investigate alternative approaches.

Thanks

**Comment by rave1502** [comment] 2019-02-10 18:56
I am seeing the same behavior on Android libraries also.

**Comment by collinjackson** [comment] 2019-02-13 16:58
This seems to me to be an issue with the underlying iOS/Android Firebase SDK rather than Flutterfire. You could open up an issue against https://github.com/firebase/firebase-ios-sdk if the issue reproduces there.

**Comment by MichalMisiaszek** [comment] 2019-04-20 08:03
I have the same issue, for example `.limit()` is completely ignored. I read somewhere that full collection if downloaded to client and the query conditions applied (very inefficient). There is no way to disable persistenceEnabled  for single query (only for full connection in plugin ?) as this method is depreciated.

**Comment by pschneider** [comment] 2019-04-27 20:05
> This seems to me to be an issue with the underlying iOS/Android Firebase SDK rather than Flutterfire. You could open up an issue against https://github.com/firebase/firebase-ios-sdk if the issue reproduces there.

This is definitely a problem of the SDKs as this also happens for non flutter users. There are multiple issues related (some of it is related to missing indexing of the local db) to this but it looks like there is no solution in sight right now. 

https://github.com/firebase/firebase-ios-sdk/issues/1868

We're seeing performance issues on 4k documents already.

**Comment by collinjackson** [comment] 2019-04-29 12:18
If this issue is showing up in the native SDKs then unfortunately I don't think there's much we can do in the cloud_firestore plugin. Closing the issue for now but happy to reopen if anyone has any ideas.

**Closed by collinjackson** 2019-04-29 12:18 UTC
Labels: p: cloud_firestore, p: firebase, p: first party, plugin, severe: performance

**Comment by shasaf1986** [comment] 2019-05-21 23:26
In the native SDKs there is a cache size option.
I think it can solve it the issue, if we could set it via dart code ...
https://firebase.google.com/docs/firestore/manage-data/enable-offline

**Comment by algrid** [comment] 2019-06-24 21:36
I'm having a similar problem with the native lib, I added an issue there: https://github.com/firebase/firebase-android-sdk/issues/565

**Comment by kroikie** [comment] 2019-10-13 19:05
@uehsnap

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/791. Any further collaboration will be done there.
