### ISSUE TITLE
target android_aot_release_android-arm failed

### ISSUE THREAD

**Issue by lycstar** [flutter/flutter#85434] opened 2021-06-28 05:32 UTC
I try to run build apk in Debian(arm64), but it got wrong because no linux_arm64/gen_snapshot，how can I compile engine to get it?

**Comment by TahaTesser** [comment] 2021-06-28 14:24
Hi @lycstar 
Your description of the issue isn't clear. please explain the issue in detail. if you're simply building APK, you're not required to compile the engine just for building an APK. 

also, provide your `flutter doctor -v`
Thank you

**Comment by lycstar** [comment] 2021-06-30 21:49
@TahaTesser 
<details>
  <summary>flutter doctor -v</summary>
  [✓] Flutter (Channel master, 2.3.0-17.0.pre.561, on Debian GNU/Linux 10
    (buster) 4.9.186-perf-g83532fd, locale zh_CN.UTF-8)
    • Flutter version 2.3.0-17.0.pre.561 at /home/lycstar/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 67e4aeb602 (2 天前), 2021-06-28 23:16:05 -0700
    • Engine revision 9d09594272
    • Dart version 2.14.0 (build 2.14.0-253.0.dev)

[✗] Chrome - develop for the web (Cannot find Chrome executable at
    google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome
      executable.

[✓] Linux toolchain - develop for Linux desktop
    • clang version 7.0.1-8+deb10u2 (tags/RELEASE_701/final)
    • cmake version 3.13.4
    • ninja version 1.8.2
    • pkg-config version 0.29

[✓] VS Code (version 1.57.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.23.0

[✓] Connected device (1 available)
    • Linux (desktop) • linux • linux-arm64 • Debian GNU/Linux 10 (buster)
      4.9.186-perf-g83532fd

! Doctor found issues in 1 category.
</details>

<details>
  <summary>flutter build apk -v</summary>
  [ +163 ms] executing: uname -m
[ +121 ms] Exit code 0 from: uname -m
[   +1 ms] aarch64
[  +13 ms] executing: [/home/lycstar/flutter/] git -c
log.showSignature=false log -n 1 --pretty=format:%H
[ +110 ms] Exit code 0 from: git -c log.showSignature=false log -n 1
--pretty=format:%H
[   +2 ms] 67e4aeb602c2b753a0c75d591d2e81224da54650
[   +2 ms] executing: [/home/lycstar/flutter/] git tag --points-at
67e4aeb602c2b753a0c75d591d2e81224da54650
[ +261 ms] Exit code 0 from: git tag --points-at
67e4aeb602c2b753a0c75d591d2e81224da54650
[   +8 ms] executing: [/home/lycstar/flutter/] git describe --match *.*.*
--long --tags 67e4aeb602c2b753a0c75d591d2e81224da54650
[ +125 ms] Exit code 0 from: git describe --match *.*.* --long --tags
67e4aeb602c2b753a0c75d591d2e81224da54650
[   +1 ms] 2.3.0-16.0.pre-561-g67e4aeb602
[  +10 ms] executing: [/home/lycstar/flutter/] git rev-parse --abbrev-ref
--symbolic @{u}
[  +61 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [/home/lycstar/flutter/] git ls-remote --get-url
origin
[  +55 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +293 ms] executing: [/home/lycstar/flutter/] git rev-parse --abbrev-ref
HEAD
[  +69 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] master
[ +129 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not
required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not
required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping
update.
[   +7 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required,
skipping update.
[   +1 ms] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required,
skipping update.
[ +149 ms] Artifact Instance of 'MaterialFonts' is not required, skipping
update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping
update.
[  +12 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not
required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping
update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping
update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required,
skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'PubDependencies' is not required, skipping
update.
[ +104 ms] Skipping pub get: version match.
[ +388 ms] Generating
/home/lycstar/myapp/android/app/src/main/java/io/flutter/plugins/GeneratedPl
uginRegistrant.java
[ +212 ms] 💪 Building with sound null safety 💪
[  +54 ms] Running Gradle task 'assembleRelease'...
[  +14 ms] Using gradle from /home/lycstar/myapp/android/gradlew.
[  +98 ms] executing: [/home/lycstar/myapp/android/]
/home/lycstar/myapp/android/gradlew -Pverbose=true
-Ptarget-platform=android-arm,android-arm64,android-x64
-Ptarget=lib/main.dart -Pdart-obfuscation=false -Ptrack-widget-creation=true
-Ptree-shake-icons=true assembleRelease
[+8468 ms] > Task :app:compileFlutterBuildRelease
[   +1 ms] [ +155 ms] executing: uname -m
[   +1 ms] [ +117 ms] Exit code 0 from: uname -m
[   +1 ms] [   +1 ms] aarch64
[   +1 ms] [  +17 ms] executing: [/home/lycstar/flutter/] git -c
log.showSignature=false log -n 1 --pretty=format:%H
[   +2 ms] [  +56 ms] Exit code 0 from: git -c log.showSignature=false log
-n 1 --pretty=format:%H
[        ] [   +1 ms] 67e4aeb602c2b753a0c75d591d2e81224da54650
[        ] [   +2 ms] executing: [/home/lycstar/flutter/] git tag
--points-at 67e4aeb602c2b753a0c75d591d2e81224da54650
[        ] [  +90 ms] Exit code 0 from: git tag --points-at
67e4aeb602c2b753a0c75d591d2e81224da54650
[   +1 ms] [   +5 ms] executing: [/home/lycstar/flutter/] git describe
--match *.*.* --long --tags 67e4aeb602c2b753a0c75d591d2e81224da54650
[   +1 ms] [ +120 ms] Exit code 0 from: git describe --match *.*.* --long
--tags 67e4aeb602c2b753a0c75d591d2e81224da54650
[        ] [   +2 ms] 2.3.0-16.0.pre-561-g67e4aeb602
[        ] [  +13 ms] executing: [/home/lycstar/flutter/] git rev-parse
--abbrev-ref --symbolic @{u}
[        ] [  +48 ms] Exit code 0 from: git rev-parse --abbrev-ref
--symbolic @{u}
[        ] [        ] origin/master
[        ] [        ] executing: [/home/lycstar/flutter/] git ls-remote
--get-url origin
[        ] [  +52 ms] Exit code 0 from: git ls-remote --get-url origin
[   +2 ms] [   +1 ms] https://github.com/flutter/flutter.git
[        ] [ +140 ms] executing: [/home/lycstar/flutter/] git rev-parse
--abbrev-ref HEAD
[        ] [  +50 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] [   +1 ms] master
[        ] [ +135 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is
not required, skipping update.
[   +1 ms] [   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts'
is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'IOSEngineArtifacts' is not
required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required,
skipping update.
[        ] [   +6 ms] Artifact Instance of 'WindowsEngineArtifacts' is not
required, skipping update.
[        ] [        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is
not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not
required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not
required, skipping update.
[   +1 ms] [   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not
required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not
required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is
not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is
not required, skipping update.
[        ] [ +332 ms] Artifact Instance of 'MaterialFonts' is not required,
skipping update.
[        ] [   +1 ms] Artifact Instance of 'GradleWrapper' is not required,
skipping update.
[   +1 ms] [   +6 ms] Artifact Instance of 'AndroidInternalBuildArtifacts'
is not required, skipping update.
[        ] [   +2 ms] Artifact Instance of 'IOSEngineArtifacts' is not
required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required,
skipping update.
[        ] [   +2 ms] Artifact Instance of 'FlutterSdk' is not required,
skipping update.
[        ] [        ] Artifact Instance of 'WindowsEngineArtifacts' is not
required, skipping update.
[        ] [   +1 ms] Artifact Instance of 'WindowsUwpEngineArtifacts' is
not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not
required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not
required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not
required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not
required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is
not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is
not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not
required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not
required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not
required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not
required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not
required, skipping update.
[        ] [        ] Artifact Instance of 'FontSubsetArtifacts' is not
required, skipping update.
[        ] [        ] Artifact Instance of 'PubDependencies' is not
required, skipping update.
[   +1 ms] [  +99 ms] Initializing file store
[        ] [  +23 ms] Done initializing file store
[ +294 ms] [ +332 ms] Skipping target: gen_localizations
[  +99 ms] [  +31 ms] Skipping target: gen_dart_plugin_registrant
[+1103 ms] [+1086 ms] Skipping target: kernel_snapshot
[        ] [   +6 ms] android_aot_release_android-arm: Starting due to {}
[        ] [  +20 ms] executing:
/home/lycstar/flutter/bin/cache/artifacts/engine/android-arm-release/linux-a
rm64/gen_snapshot --deterministic --snapshot_kind=app-aot-elf
--elf=/home/lycstar/myapp/.dart_tool/flutter_build/67a03ea555ae2f5a668cf4153
24ce9e7/armeabi-v7a/app.so --strip --no-sim-use-hardfp
--no-use-integer-division
/home/lycstar/myapp/.dart_tool/flutter_build/67a03ea555ae2f5a668cf415324ce9e
7/app.dill
[   +1 ms] [  +57 ms] Skipping target: aot_android_asset_bundle
[        ] [   +1 ms] android_aot_release_android-arm64: Starting due to {}
[   +8 ms] [   +1 ms] executing:
/home/lycstar/flutter/bin/cache/artifacts/engine/android-arm64-release/linux
-arm64/gen_snapshot --deterministic --snapshot_kind=app-aot-elf
--elf=/home/lycstar/myapp/.dart_tool/flutter_build/67a03ea555ae2f5a668cf4153
24ce9e7/arm64-v8a/app.so --strip
/home/lycstar/myapp/.dart_tool/flutter_build/67a03ea555ae2f5a668cf415324ce9e
7/app.dill
[   +1 ms] [        ] android_aot_release_android-x64: Starting due to {}
[   +2 ms] [   +1 ms] executing:
/home/lycstar/flutter/bin/cache/artifacts/engine/android-x64-release/linux-a
rm64/gen_snapshot --deterministic --snapshot_kind=app-aot-elf
--elf=/home/lycstar/myapp/.dart_tool/flutter_build/67a03ea555ae2f5a668cf4153
24ce9e7/x86_64/app.so --strip
/home/lycstar/myapp/.dart_tool/flutter_build/67a03ea555ae2f5a668cf415324ce9e
7/app.dill
[  +81 ms] [   +7 ms] Persisting file store
[        ] [  +19 ms] Done persisting file store
[   +1 ms] [  +15 ms] Target android_aot_release_android-arm failed:
ProcessException: Failed to find
"/home/lycstar/flutter/bin/cache/artifacts/engine/android-arm-release/linux-
arm64/gen_snapshot" in the search path.
[   +7 ms]              Command:
/home/lycstar/flutter/bin/cache/artifacts/engine/android-arm-release/linux-a
rm64/gen_snapshot
[        ]            #0      LocalProcessManager.start
(package:process/src/interface/local_process_manager.dart:58:7)
[   +3 ms]            #1      ErrorHandlingProcessManager.start.<anonymous
closure> (package:flutter_tools/src/base/error_handling_io.dart:691:24)
[        ]            #2      _run
(package:flutter_tools/src/base/error_handling_io.dart:567:20)
[        ]            #3      ErrorHandlingProcessManager.start
(package:flutter_tools/src/base/error_handling_io.dart:690:12)
[        ]            #4      _DefaultProcessUtils.start
(package:flutter_tools/src/base/process.dart:425:28)
[        ]            #5      _DefaultProcessUtils.stream
(package:flutter_tools/src/base/process.dart:444:35)
[        ]            #6      GenSnapshot.run
(package:flutter_tools/src/base/build.dart:73:26)
[        ]            #7      AOTSnapshotter.build
(package:flutter_tools/src/base/build.dart:207:56)
[        ]            #8      AndroidAot.build
(package:flutter_tools/src/build_system/targets/android.dart:247:52)
[        ]            #9      _BuildInstance._invokeInternal
(package:flutter_tools/src/build_system/build_system.dart:836:27)
[        ]            <asynchronous suspension>
[        ]            #10     Future.wait.<anonymous closure>
(dart:async/future.dart)
[        ]            <asynchronous suspension>
[        ]            #11     _BuildInstance.invokeTarget
(package:flutter_tools/src/build_system/build_system.dart:774:32)
[   +2 ms]            <asynchronous suspension>
[        ]            #12     Future.wait.<anonymous closure>
(dart:async/future.dart)
[        ]            <asynchronous suspension>
[        ]            #13     _BuildInstance.invokeTarget
(package:flutter_tools/src/build_system/build_system.dart:774:32)
[        ]            <asynchronous suspension>
[        ]            #14     FlutterBuildSystem.build
(package:flutter_tools/src/build_system/build_system.dart:603:16)
[        ]            <asynchronous suspension>
[        ]            #15     AssembleCommand.runCommand
(package:flutter_tools/src/commands/assemble.dart:314:32)
[        ]            <asynchronous suspension>
[        ]            #16     FlutterCommand.run.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command.dart:1126:27)
[        ]            <asynchronous suspension>
[        ]            #17     AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #18     CommandRunner.runCommand
(package:args/command_runner.dart:196:13)
[        ]            <asynchronous suspension>
[        ]            #19     FlutterCommandRunner.runCommand.<anonymous
closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
[        ]            <asynchronous suspension>
[        ]            #20     AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #21     FlutterCommandRunner.runCommand
(package:flutter_tools/src/runner/flutter_command_runner.dart:232:5)
[        ]            <asynchronous suspension>
[        ]            #22     run.<anonymous closure>.<anonymous closure>
(package:flutter_tools/runner.dart:62:9)
[        ]            <asynchronous suspension>
[        ]            #23     AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #24     main
(package:flutter_tools/executable.dart:91:3)
[        ]            <asynchronous suspension>
[        ] [   +6 ms] Target android_aot_release_android-arm64 failed:
ProcessException: Failed to find
"/home/lycstar/flutter/bin/cache/artifacts/engine/android-arm64-release/linu
x-arm64/gen_snapshot" in the search path.
[        ]              Command:
/home/lycstar/flutter/bin/cache/artifacts/engine/android-arm64-release/linux
-arm64/gen_snapshot
[        ]            #0      LocalProcessManager.start
(package:process/src/interface/local_process_manager.dart:58:7)
[        ]            #1      ErrorHandlingProcessManager.start.<anonymous
closure> (package:flutter_tools/src/base/error_handling_io.dart:691:24)
[        ]            #2      _run
(package:flutter_tools/src/base/error_handling_io.dart:567:20)
[        ]            #3      ErrorHandlingProcessManager.start
(package:flutter_tools/src/base/error_handling_io.dart:690:12)
[        ]            #4      _DefaultProcessUtils.start
(package:flutter_tools/src/base/process.dart:425:28)
[        ]            #5      _DefaultProcessUtils.stream
(package:flutter_tools/src/base/process.dart:444:35)
[        ]            #6      GenSnapshot.run
(package:flutter_tools/src/base/build.dart:73:26)
[        ]            #7      AOTSnapshotter.build
(package:flutter_tools/src/base/build.dart:207:56)
[        ]            #8      AndroidAot.build
(package:flutter_tools/src/build_system/targets/android.dart:247:52)
[        ]            #9      _BuildInstance._invokeInternal
(package:flutter_tools/src/build_system/build_system.dart:836:27)
[        ]            <asynchronous suspension>
[        ]            #10     Future.wait.<anonymous closure>
(dart:async/future.dart)
[        ]            <asynchronous suspension>
[        ]            #11     _BuildInstance.invokeTarget
(package:flutter_tools/src/build_system/build_system.dart:774:32)
[        ]            <asynchronous suspension>
[        ]            #12     Future.wait.<anonymous closure>
(dart:async/future.dart)
[        ]            <asynchronous suspension>
[        ]            #13     _BuildInstance.invokeTarget
(package:flutter_tools/src/build_system/build_system.dart:774:32)
[        ]            <asynchronous suspension>
[        ]            #14     FlutterBuildSystem.build
(package:flutter_tools/src/build_system/build_system.dart:603:16)
[        ]            <asynchronous suspension>
[        ]            #15     AssembleCommand.runCommand
(package:flutter_tools/src/commands/assemble.dart:314:32)
[        ]            <asynchronous suspension>
[        ]            #16     FlutterCommand.run.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command.dart:1126:27)
[        ]            <asynchronous suspension>
[        ]            #17     AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #18     CommandRunner.runCommand
(package:args/command_runner.dart:196:13)
[        ]            <asynchronous suspension>
[        ]            #19     FlutterCommandRunner.runCommand.<anonymous
closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
[        ]            <asynchronous suspension>
[        ]            #20     AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #21     FlutterCommandRunner.runCommand
(package:flutter_tools/src/runner/flutter_command_runner.dart:232:5)
[        ]            <asynchronous suspension>
[        ]            #22     run.<anonymous closure>.<anonymous closure>
(package:flutter_tools/runner.dart:62:9)
[        ]            <asynchronous suspension>
[        ]            #23     AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #24     main
(package:flutter_tools/executable.dart:91:3)
[        ]            <asynchronous suspension>
[   +1 ms] [   +1 ms] Target android_aot_release_android-x64 failed:
ProcessException: Failed to find
"/home/lycstar/flutter/bin/cache/artifacts/engine/android-x64-release/linux-
arm64/gen_snapshot" in the search path.
[        ]              Command:
/home/lycstar/flutter/bin/cache/artifacts/engine/android-x64-release/linux-a
rm64/gen_snapshot
[        ]            #0      LocalProcessManager.start
(package:process/src/interface/local_process_manager.dart:58:7)
[        ]            #1      ErrorHandlingProcessManager.start.<anonymous
closure> (package:flutter_tools/src/base/error_handling_io.dart:691:24)
[        ]            #2      _run
(package:flutter_tools/src/base/error_handling_io.dart:567:20)
[        ]            #3      ErrorHandlingProcessManager.start
(package:flutter_tools/src/base/error_handling_io.dart:690:12)
[        ]            #4      _DefaultProcessUtils.start
(package:flutter_tools/src/base/process.dart:425:28)
[        ]            #5      _DefaultProcessUtils.stream
(package:flutter_tools/src/base/process.dart:444:35)
[        ]            #6      GenSnapshot.run
(package:flutter_tools/src/base/build.dart:73:26)
[        ]            #7      AOTSnapshotter.build
(package:flutter_tools/src/base/build.dart:207:56)
[        ]            #8      AndroidAot.build
(package:flutter_tools/src/build_system/targets/android.dart:247:52)
[        ]            #9      _BuildInstance._invokeInternal
(package:flutter_tools/src/build_system/build_system.dart:836:27)
[        ]            <asynchronous suspension>
[        ]            #10     Future.wait.<anonymous closure>
(dart:async/future.dart)
[        ]            <asynchronous suspension>
[        ]            #11     _BuildInstance.invokeTarget
(package:flutter_tools/src/build_system/build_system.dart:774:32)
[        ]            <asynchronous suspension>
[        ]            #12     Future.wait.<anonymous closure>
(dart:async/future.dart)
[        ]            <asynchronous suspension>
[        ]            #13     _BuildInstance.invokeTarget
(package:flutter_tools/src/build_system/build_system.dart:774:32)
[        ]            <asynchronous suspension>
[        ]            #14     FlutterBuildSystem.build
(package:flutter_tools/src/build_system/build_system.dart:603:16)
[        ]            <asynchronous suspension>
[        ]            #15     AssembleCommand.runCommand
(package:flutter_tools/src/commands/assemble.dart:314:32)
[        ]            <asynchronous suspension>
[        ]            #16     FlutterCommand.run.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command.dart:1126:27)
[        ]            <asynchronous suspension>
[        ]            #17     AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #18     CommandRunner.runCommand
(package:args/command_runner.dart:196:13)
[        ]            <asynchronous suspension>
[        ]            #19     FlutterCommandRunner.runCommand.<anonymous
closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
[        ]            <asynchronous suspension>
[        ]            #20     AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #21     FlutterCommandRunner.runCommand
(package:flutter_tools/src/runner/flutter_command_runner.dart:232:5)
[        ]            <asynchronous suspension>
[        ]            #22     run.<anonymous closure>.<anonymous closure>
(package:flutter_tools/runner.dart:62:9)
[        ]            <asynchronous suspension>
[        ]            #23     AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #24     main
(package:flutter_tools/executable.dart:91:3)
[        ]            <asynchronous suspension>
[        ] [  +13 ms]
[        ]            #0      throwToolExit
(package:flutter_tools/src/base/common.dart:10:3)
[        ]            #1      AssembleCommand.runCommand
(package:flutter_tools/src/commands/assemble.dart:331:7)
[        ]            <asynchronous suspension>
[        ]            #2      FlutterCommand.run.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command.dart:1126:27)
[        ]            <asynchronous suspension>
[        ]            #3      AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #4      CommandRunner.runCommand
(package:args/command_runner.dart:196:13)
[        ]            <asynchronous suspension>
[        ]            #5      FlutterCommandRunner.runCommand.<anonymous
closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
[        ]            <asynchronous suspension>
[        ]            #6      AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #7      FlutterCommandRunner.runCommand
(package:flutter_tools/src/runner/flutter_command_runner.dart:232:5)
[        ]            <asynchronous suspension>
[        ]            #8      run.<anonymous closure>.<anonymous closure>
(package:flutter_tools/runner.dart:62:9)
[        ]            <asynchronous suspension>
[        ]            #9      AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #10     main
(package:flutter_tools/executable.dart:91:3)
[        ]            <asynchronous suspension>
[   +1 ms] [  +21 ms] "flutter assemble" took 2,141ms.
[ +229 ms] [ +262 ms] ensureAnalyticsSent: 259ms
[        ] [   +3 ms] Running shutdown hooks
[        ] [   +1 ms] Shutdown hooks complete
[        ] [   +2 ms] exiting with code 1
[  +99 ms] > Task :app:compileFlutterBuildRelease FAILED
[ +102 ms] FAILURE: Build failed with an exception.
[        ] * Where:
[        ] Script
'/home/lycstar/flutter/packages/flutter_tools/gradle/flutter.gradle' line:
1052
[        ] * What went wrong:
[        ] Execution failed for task ':app:compileFlutterBuildRelease'.
[        ] > Process 'command '/home/lycstar/flutter/bin/flutter'' finished
with non-zero exit value 1
[        ] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with
--info or --debug option to get more log output. Run with --scan to get full
insights.
[   +1 ms] * Get more help at https://help.gradle.org
[        ] BUILD FAILED in 10s
[   +1 ms] Deprecated Gradle features were used in this build, making it
incompatible with Gradle 7.0.
[        ] Use '--warning-mode all' to show the individual deprecation
warnings.
[        ] See
https://docs.gradle.org/6.7/userguide/command_line_interface.html#sec:comman
d_line_warnings
[        ] 1 actionable task: 1 executed
[ +490 ms] Running Gradle task 'assembleRelease'... (completed in 11.2s)
[  +12 ms] "flutter apk" took 12,241ms.
[   +8 ms] Gradle task assembleRelease failed with exit code 1
[   +2 ms]
           #0      throwToolExit
(package:flutter_tools/src/base/common.dart:10:3)
           #1      AndroidGradleBuilder.buildGradleApp
           (package:flutter_tools/src/android/gradle.dart:462:9)
           <asynchronous suspension>
           #2      AndroidGradleBuilder.buildApk
           (package:flutter_tools/src/android/gradle.dart:229:5)
           <asynchronous suspension>
           #3      BuildApkCommand.runCommand
           (package:flutter_tools/src/commands/build_apk.dart:105:5)
           <asynchronous suspension>
           #4      FlutterCommand.run.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command.dart:1126:27)
           <asynchronous suspension>
           #5      AppContext.run.<anonymous closure>
           (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #6      CommandRunner.runCommand
(package:args/command_runner.dart:196:13)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand.<anonymous closure>

(package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
           <asynchronous suspension>
           #8      AppContext.run.<anonymous closure>
           (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #9      FlutterCommandRunner.runCommand

(package:flutter_tools/src/runner/flutter_command_runner.dart:232:5)
           <asynchronous suspension>
           #10     run.<anonymous closure>.<anonymous closure>
           (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #11     AppContext.run.<anonymous closure>
           (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #12     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>


[ +261 ms] ensureAnalyticsSent: 257ms
[   +6 ms] Running shutdown hooks
[   +1 ms] Shutdown hooks complete
[   +1 ms] exiting with code 1
</details>
<details>
  <summary>error log part in buikd apk</summary>
  [   +1 ms] [  +15 ms] Target android_aot_release_android-arm failed:
ProcessException: Failed to find
"/home/lycstar/flutter/bin/cache/artifacts/engine/android-arm-release/linux-arm64/gen_snapshot" in the search path.
[   +7 ms]              Command:
/home/lycstar/flutter/bin/cache/artifacts/engine/android-arm-release/linux-a
rm64/gen_snapshot
</details>

**Comment by TahaTesser** [comment] 2021-07-01 07:25
Hi @lycstar 
Thanks for the logs, unfortunately, I don't have access to arm Linux system to reproduce this  
https://github.com/flutter/flutter/issues/56992 confirms Linux host arm is supported, i will label it for further triage 

Thank you

**Comment by kf6gpe** [comment] 2021-07-07 21:13
Oh, this is building the engine on arm64 itself instead of cross-compiling? I'm not sure we support that out of the box. Maybe @chinmaygarde has some pointers?

**Comment by Hixie** [comment] 2021-07-13 22:59
@lycstar Can you try different versions of Flutter and see if this happens with all of them?

**Comment by chinmaygarde** [comment] 2021-07-15 18:19
Out of the box, we don't supporting building host snapshotters on arm64 hosts. The x64 gen_snapshot binary for arm64 targets (say the Android variant) should work just fine. Closing since this is not a supported target.

**Closed by chinmaygarde** 2021-07-15 18:19 UTC
Labels: engine, passed first triage, platform-android, platform-host-arm, platform-linux, severe: crash, will need additional triage

**Comment by lycstar** [comment] 2021-07-16 02:48
@chinmaygarde You mean x64 gen_snapshot work file? 
But run file gen_snapshot commond get :
gen_ snapshot: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 3.2.0, BuildID[sha1]=98a9a88e147db764f55588235bf444e5f34b4f95, stripped.
Executable file format error.
