### ISSUE TITLE
crash when hot reloading app on android

### ISSUE THREAD

**Issue by bohrmeista** [flutter/flutter#22908] opened 2018-10-10 15:16 UTC
The problem started occuring when I started working with ThemeData's buttonTheme and UI refactoring.

I update for example the `textColor` of a `RaisedButton` and after hot reload this happens:
```
Initializing hot reload... 
I/flutter (24260): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
⣯I/flutter (24260): The following assertion was thrown building MediaQuery(MediaQueryData(size: Size(411.4, 683.4),
I/flutter (24260): devicePixelRatio: 2.6, textScaleFactor: 1.0, padding: EdgeInsets.zero, viewInsets: EdgeInsets.zero,
I/flutter (24260): alwaysUse24HourFormat: false, accessibleNavigation: falsedisableAnimations: falseinvertColors:
I/flutter (24260): falseboldText: false)):
I/flutter (24260): 'package:flutter/src/rendering/object.dart': Failed assertion: line 1853 pos 12: '() {
I/flutter (24260):       final AbstractNode parent = this.parent;
I/flutter (24260):       if (parent is RenderObject)
I/flutter (24260):         return parent._needsCompositing;
I/flutter (24260):       return true;
I/flutter (24260):     }()': is not true.
I/flutter (24260):
I/flutter (24260): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (24260): more information in this error message to help you determine and fix the underlying cause.
I/flutter (24260): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (24260):   https://github.com/flutter/flutter/issues/new
I/flutter (24260):
I/flutter (24260): When the exception was thrown, this was the stack:
I/flutter (24260): #2      RenderObject.markNeedsCompositingBitsUpdate (package:flutter/src/rendering/object.dart:1853:12)
I/flutter (24260): #3      RenderObject.attach (package:flutter/src/rendering/object.dart:1293:7)
I/flutter (24260): #4      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin.attach (package:flutter/src/rendering/object.dart:2721:11)
I/flutter (24260): #5      AbstractNode.adoptChild (package:flutter/src/foundation/node.dart:132:13)
I/flutter (24260): #6      RenderObject.adoptChild (package:flutter/src/rendering/object.dart:1138:11)
I/flutter (24260): #7      _RenderCustomMultiChildLayoutBox&RenderBox&ContainerRenderObjectMixin.insert (package:flutter/src/rendering/object.dart:2898:5)
I/flutter (24260): #8      MultiChildRenderObjectElement.insertChildRenderObject (package:flutter/src/widgets/framework.dart:4860:18)
I/flutter (24260): #9      RenderObjectElement.attachRenderObject (package:flutter/src/widgets/framework.dart:4655:35)
I/flutter (24260): #10     Element.attachRenderObject.<anonymous closure> (package:flutter/src/widgets/framework.dart:2857:13)
I/flutter (24260): #11     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3712:14)
I/flutter (24260): #12     Element.attachRenderObject (package:flutter/src/widgets/framework.dart:2856:5)
I/flutter (24260): #13     Element.attachRenderObject.<anonymous closure> (package:flutter/src/widgets/framework.dart:2857:13)
I/flutter (24260): #14     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3712:14)
I/flutter (24260): #15     Element.attachRenderObject (package:flutter/src/widgets/framework.dart:2856:5)
I/flutter (24260): #16     Element.attachRenderObject.<anonymous closure> (package:flutter/src/widgets/framework.dart:2857:13)
I/flutter (24260): #17     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3712:14)
I/flutter (24260): #18     Element.attachRenderObject (package:flutter/src/widgets/framework.dart:2856:5)
I/flutter (24260): #19     Element.attachRenderObject.<anonymous closure> (package:flutter/src/widgets/framework.dart:2857:13)
I/flutter (24260): #20     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3712:14)
I/flutter (24260): #21     Element.attachRenderObject (package:flutter/src/widgets/framework.dart:2856:5)
I/flutter (24260): #22     Element.attachRenderObject.<anonymous closure> (package:flutter/src/widgets/framework.dart:2857:13)
I/flutter (24260): #23     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3712:14)
I/flutter (24260): #24     Element.attachRenderObject (package:flutter/src/widgets/framework.dart:2856:5)
I/flutter (24260): #25     Element.attachRenderObject.<anonymous closure> (package:flutter/src/widgets/framework.dart:2857:13)
I/flutter (24260): #26     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3712:14)
I/flutter (24260): #27     Element.attachRenderObject (package:flutter/src/widgets/framework.dart:2856:5)
I/flutter (24260): #28     Element.attachRenderObject.<anonymous closure> (package:flutter/src/widgets/framework.dart:2857:13)
I/flutter (24260): #29     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3712:14)
I/flutter (24260): #30     Element.attachRenderObject (package:flutter/src/widgets/framework.dart:2856:5)
I/flutter (24260): #31     Element.attachRenderObject.<anonymous closure> (package:flutter/src/widgets/framework.dart:2857:13)
I/flutter (24260): #32     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3712:14)
I/flutter (24260): #33     Element.attachRenderObject (package:flutter/src/widgets/framework.dart:2856:5)
I/flutter (24260): #34     Element.attachRenderObject.<anonymous closure> (package:flutter/src/widgets/framework.dart:2857:13)
I/flutter (24260): #35     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3712:14)
I/flutter (24260): #36     Element.attachRenderObject (package:flutter/src/widgets/framework.dart:2856:5)
I/flutter (24260): #37     Element.attachRenderObject.<anonymous closure> (package:flutter/src/widgets/framework.dart:2857:13)
I/flutter (24260): #38     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3712:14)
I/flutter (24260): #39     Element.attachRenderObject (package:flutter/src/widgets/framework.dart:2856:5)
I/flutter (24260): #40     Element._activateWithParent (package:flutter/src/widgets/framework.dart:3004:5)
I/flutter (24260): #41     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2929:18)
I/flutter (24260): #42     Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter (24260): #43     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (24260): #44     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (24260): #45     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3658:5)
I/flutter (24260): #46     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3653:5)
I/flutter (24260): #47     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter (24260): #48     Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter (24260): #49     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (24260): #50     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (24260): #51     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3658:5)
I/flutter (24260): #52     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3653:5)
I/flutter (24260): #53     ParentDataElement.mount (package:flutter/src/widgets/framework.dart:3993:11)
I/flutter (24260): #54     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter (24260): #55     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4901:32)
I/flutter (24260): #56     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter (24260): #57     Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter (24260): #58     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (24260): #59     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (24260): #60     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3658:5)
I/flutter (24260): #61     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3805:11)
I/flutter (24260): #62     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3653:5)
I/flutter (24260): #63     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter (24260): #64     Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter (24260): #65     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (24260): #66     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (24260): #67     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3658:5)
I/flutter (24260): #68     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3653:5)
I/flutter (24260): #69     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter (24260): #70     Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter (24260): #71     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (24260): #72     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (24260): #73     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3658:5)
I/flutter (24260): #74     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3805:11)
I/flutter (24260): #75     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3653:5)
I/flutter (24260): #76     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter (24260): #77     Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter (24260): #78     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4796:14)
I/flutter (24260): #79     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter (24260): #80     Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter (24260): #81     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (24260): #82     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (24260): #83     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3658:5)
I/flutter (24260): #84     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3653:5)
I/flutter (24260): #85     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter (24260): #86     Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter (24260): #87     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4796:14)
I/flutter (24260): #88     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter (24260): #89     Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter (24260): #90     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (24260): #91     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (24260): #92     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3658:5)
I/flutter (24260): #93     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3805:11)
I/flutter (24260): #94     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3653:5)
I/flutter (24260): #95     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter (24260): #96     Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter (24260): #97     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (24260): #98     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (24260): #99     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3658:5)
I/flutter (24260): #100    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3805:11)
I/flutter (24260): #101    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3653:5)
I/flutter (24260): #102    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter (24260): #103    Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter (24260): #104    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (24260): #105    Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (24260): #106    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3658:5)
I/flutter (24260): #107    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3653:5)
I/flutter (24260): #108    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter (24260): #109    Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter (24260): #110    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (24260): #111    Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (24260): #112    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3658:5)
I/flutter (24260): #113    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3653:5)
I/flutter (24260): #114    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter (24260): #115    Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter (24260): #116    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (24260): #117    Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (24260): #118    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3658:5)
I/flutter (24260): #119    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3805:11)
I/flutter (24260): #120    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3653:5)
I/flutter (24260): #121    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter (24260): #122    Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter (24260): #123    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (24260): #124    Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (24260): #125    StatefulElement.update (package:flutter/src/widgets/framework.dart:3835:5)
I/flutter (24260): #126    Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (24260): #127    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (24260): #128    Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (24260): #129    StatefulElement.update (package:flutter/src/widgets/framework.dart:3835:5)
I/flutter (24260): #130    Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (24260): #131    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4803:14)
⣷I/flutter (24260): Api: getting preview 0 of job with uid 323527cdba9ce320b6529a033e459a9edc67a8501111aeb09687845145627735

Reloaded 6 of 568 libraries in 1.441ms.
I/flutter (24260): Api: preview for 323527cdba9ce320b6529a033e459a9edc67a8501111aeb09687845145627735 already found in cache, returning path
I/flutter (24260): Api: getting jobs
I/flutter (24260): Api: "/jobs": 200 success
I/flutter (24260): Api: "/jobs": 200 success
I/flutter (24260): #132    Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (24260): #133    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (24260): #134    Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (24260): #135    StatelessElement.update (package:flutter/src/widgets/framework.dart:3738:5)
I/flutter (24260): #136    Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (24260): #137    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4803:14)
I/flutter (24260): #138    Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (24260): #139    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4803:14)
I/flutter (24260): #140    Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (24260): #141    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4803:14)
I/flutter (24260): #142    Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (24260): #143    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4803:14)
I/flutter (24260): #144    Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (24260): #145    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (24260): #146    Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (24260): #147    StatefulElement.update (package:flutter/src/widgets/framework.dart:3835:5)
I/flutter (24260): #148    Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (24260): #149    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (24260): #150    Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (24260): #151    StatelessElement.update (package:flutter/src/widgets/framework.dart:3738:5)
I/flutter (24260): #152    Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (24260): #153    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (24260): #154    Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (24260): #155    StatefulElement.update (package:flutter/src/widgets/framework.dart:3835:5)
I/flutter (24260): #156    Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (24260): #157    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4803:14)
I/flutter (24260): #158    Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (24260): #159    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (24260): #160    Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (24260): #161    ProxyElement.update (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (24260): #162    Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (24260): #163    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4803:14)
I/flutter (24260): #164    Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (24260): #165    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (24260): #166    Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (24260): #167    StatefulElement.update (package:flutter/src/widgets/framework.dart:3835:5)
I/flutter (24260): #168    Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (24260): #169    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (24260): #170    Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (24260): #171    StatelessElement.update (package:flutter/src/widgets/framework.dart:3738:5)
I/flutter (24260): #172    Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (24260): #173    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4803:14)
I/flutter (24260): #174    Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (24260): #175    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (24260): #176    Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (24260): #177    ProxyElement.update (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (24260): #178    Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (24260): #179    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (24260): #180    Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (24260): #181    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2273:33)
I/flutter (24260): #182    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:670:20)
I/flutter (24260): #183    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
I/flutter (24260): #184    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter (24260): #185    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter (24260): #186    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:751:7)
I/flutter (24260): #188    _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
I/flutter (24260): #189    _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
I/flutter (24260): #190    _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
I/flutter (24260): (elided 3 frames from class _AssertionError and package dart:async)
I/flutter (24260): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (24260): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 4077 pos 14: '_dependents.isEmpty': is not true.
I/flutter (24260): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 2271 pos 16: '!_dirtyElements[index]._active || _dirtyElements[index]._debugIsInScope(context)': is not true.
```

My `flutter doctor`output:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v0.10.1-pre.11, on Mac OS X 10.14 18A391, locale de-DE)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
[✓] Android Studio (version 3.2)
[✓] Connected device (1 available)
```

**Comment by zoechi** [comment] 2018-10-10 16:16
Could you try to come up with a minimal reproduction and the exact changes you made that led to the exception?

**Comment by zoechi** [comment] 2018-12-10 15:53
Duplicate of #12261

**Closed by zoechi** 2018-12-10 15:53 UTC
Labels: severe: crash, t: hot reload, tool
