### ISSUE TITLE
[web] Text doesn't render properly on Firefox using HTML rendering

### ISSUE THREAD

**Issue by aguilaair** [flutter/flutter#71846] opened 2020-12-07 14:50 UTC
## Steps to Reproduce

Create a new flutter project
Delete the whole main file and add the following:
```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(
        body: Center(
          child: Text("Hello, how are you?"),
        ),
      ),
    );
  }
}
```

Run the app on web and open Firefox. Change the zoom to achieve the result.

**Expected results:** 
![image](https://user-images.githubusercontent.com/29983481/101365145-b60c0d80-38a3-11eb-9c5c-83c915ab2ad7.png)

**Actual results:** 
![image](https://user-images.githubusercontent.com/29983481/101365168-bc01ee80-38a3-11eb-8afa-0e88e140aa78.png)

### Doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, 1.24.0-10.2.pre, on Microsoft Windows [VersiÃ³n 10.0.19042.630], locale es-ES)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[√] Chrome - develop for the web
[√] Android Studio (version 3.6)
[√] VS Code (version 1.51.1)
[√] Connected device (3 available)

• No issues found!
```

**Comment by aguilaair** [comment] 2020-12-07 14:51
Also affects SelectableText (I imagine other too)

**Comment by TahaTesser** [comment] 2020-12-07 16:01
Hi @aguilaair 
Thanks for filing the issue,  I can reproduce it in DOM Canvas, no issues in canvaskit 
Really strange rendering issues

#### If we provide one-line text, we get the following results,  as you can see some text is missing in Firefox
| Firefox | Chrome |
| --------------- | --------------- |
![image](https://user-images.githubusercontent.com/48603081/101372551-0a2de680-38d2-11eb-8bbe-bb43bea4ee24.png) | ![image](https://user-images.githubusercontent.com/48603081/101372598-144fe500-38d2-11eb-84e6-cd07a5793d06.png)


#### If I put `\n` and copies the same sentence, the first sentence renders properly but issue shift to the second setense 
| Firefix | Chrome |
| --------------- | --------------- | 
![image](https://user-images.githubusercontent.com/48603081/101373035-858f9800-38d2-11eb-8402-4a9a7f93a448.png) | ![image](https://user-images.githubusercontent.com/48603081/101373073-8cb6a600-38d2-11eb-936f-fd74bbf1a31c.png)

#### Renders fine in Canvaskit
| Firefix | Chrome |  
| --------------- | --------------- | 
![image](https://user-images.githubusercontent.com/48603081/101373552-14041980-38d3-11eb-872c-cafb9e352a62.png) | ![image](https://user-images.githubusercontent.com/48603081/101373582-1bc3be00-38d3-11eb-8545-f3ab8d546eb6.png)

<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.purple,
      ),
      home: Scaffold(
        body: Center(
          // child: Text("Hello, how are you?"),
          child: Text(
              "Hello world, this is Flutter and it is amazing\nHello world, this is Flutter and it is amazing\n"),
        ),
      ),
    );
  }
}

``` 

</details>

<details> 
<summary>multiple flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel dev, 1.25.0-4.0.pre, on Microsoft Windows [Version 10.0.19042.630], locale en-US)
    • Flutter version 1.25.0-4.0.pre at C:\Code\flutter_dev
    • Framework revision a7f5fd5360 (7 days ago), 2020-11-30 13:14:13 +0100
    • Engine revision 20caf54969
    • Dart version 2.12.0 (build 2.12.0-76.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Code\sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = C:\Code\sdk
    • Java binary at: C:\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.8.2)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.8.30717.126
    • Windows 10 SDK version 10.0.18362.0

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] IntelliJ IDEA Community Edition (version 2020.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.2.4
    • Flutter plugin version 52.0.5
    • Dart plugin version 203.5981.152

[✓] VS Code (version 1.51.1)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.17.0

[✓] Connected device (4 available)
    • Windows (desktop) • windows    • windows-x64    • Microsoft Windows [Version 10.0.19042.630]
    • Web Server (web)  • web-server • web-javascript • Flutter Tools
    • Chrome (web)      • chrome     • web-javascript • Google Chrome 87.0.4280.88
    • Edge (web)        • edge       • web-javascript • Microsoft Edge 87.0.664.52

• No issues found!
```

```bash
[✓] Flutter (Channel beta, 1.24.0-10.2.pre, on Microsoft Windows [Version 10.0.19042.630], locale en-US)
    • Flutter version 1.24.0-10.2.pre at C:\Code\flutter_beta
    • Framework revision 022b333a08 (3 weeks ago), 2020-11-18 11:35:09 -0800
    • Engine revision 07c1eed46b
    • Dart version 2.12.0 (build 2.12.0-29.10.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Code\sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = C:\Code\sdk
    • Java binary at: C:\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] IntelliJ IDEA Community Edition (version 2020.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.2.4
    • Flutter plugin version 52.0.5
    • Dart plugin version 203.5981.152

[✓] VS Code (version 1.51.1)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.17.0

[✓] Connected device (3 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 87.0.4280.88
    • Edge (web)       • edge       • web-javascript • Microsoft Edge 87.0.664.52

• No issues found
```

```bash
[✓] Flutter (Channel master, 1.25.0-5.0.pre.92, on Microsoft Windows [Version 10.0.19042.630], locale en-US)
    • Flutter version 1.25.0-5.0.pre.92 at C:\Code\flutter_master
    • Framework revision 90f08769a3 (4 hours ago), 2020-12-07 12:33:03 +0100
    • Engine revision 6491c7518f
    • Dart version 2.12.0 (build 2.12.0-120.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Code\sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = C:\Code\sdk
    • Java binary at: C:\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.8.2)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.8.30717.126
    • Windows 10 SDK version 10.0.18362.0

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] IntelliJ IDEA Community Edition (version 2020.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.2.4
    • Flutter plugin version 52.0.5
    • Dart plugin version 203.5981.152

[✓] VS Code (version 1.51.1)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.17.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19042.630]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 87.0.4280.88
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 87.0.664.52

• No issues found!
```


</details>

**Comment by aguilaair** [comment] 2020-12-07 16:04
Yes, that's the same behaviour I'm seeing. Really hope it gets solved soon, IMHO it's a pretty severe issue.

**Comment by mdebbar** [comment] 2020-12-07 17:45
This is due to minor differences between canvas-based and dom-based text measurement. In most of the cases I've seen, the difference is around 1 pixel, but that's enough to cause the last character or the last word to disappear from the text.

The difference is more visible and easily reproducible when zoom level is high (e.g. 1.5x or 2x).

This is a duplicate of https://github.com/flutter/flutter/issues/67327

**Closed by mdebbar** 2020-12-07 17:45 UTC
Labels: a: typography, assigned for triage, browser: firefox, e: web_html, engine, found in release: 1.24, found in release: 1.25, has reproducible steps, platform-web, severe: regression, severe: rendering
