### ISSUE TITLE
[google_maps_flutter_web] GoogleMap on Web recognizes gestures and taps on open dialogs and modals

### ISSUE THREAD

**Issue by Ayman-Kortobaa** [flutter/flutter#80655] opened 2021-04-17 23:36 UTC
## Steps to Reproduce

- Create a GoogleMap widget and show a dialog or modal on top of it, it can have buttons or other gesture recognizing widgets.
- You can drag the map on top of the dialog or modal and gestures ripple down to the GoogleMap widget underneath.

**Expected results:**
The dialog or modal should block the gestures and don't let them ripple down to the GoogleMap

**Actual results:**
You can drag the map on top of the dialog or modal and gestures ripple down to the GoogleMap widget underneath.

A gif showing the current behavior: 

![map_gestures_web](https://user-images.githubusercontent.com/59527019/115129409-e5ffb600-9fe5-11eb-84d5-8ff54406e032.gif)

**Flutter Doctor**

<details>

```
[✓] Flutter (Channel stable, 2.0.4, on Microsoft Windows [Version 10.0.19041.928], locale en-US)
    • Flutter version 2.0.4 at C:\src\flutter
    • Framework revision b1395592de (2 weeks ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\pc\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 29.0.3
    • ANDROID_HOME = C:\Users\pc\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.55.2)
    • VS Code at C:\Users\pc\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.21.0

[✓] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 89.0.4389.128
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 90.0.818.39

• No issues found!
```

</details>

**Comment by TahaTesser** [comment] 2021-04-19 08:20
Hi @Ayman-Kortobaa 
Thanks for filing the issue

Here I created a complete minimal runnable code sample to reproduce the issue

<details> 
<summary>code sample</summary> 

```dart
import 'dart:async';

import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Google Maps Demo',
      home: MapSample(),
    );
  }
}

class MapSample extends StatefulWidget {
  @override
  State<MapSample> createState() => MapSampleState();
}

class MapSampleState extends State<MapSample> {
  Completer<GoogleMapController> _controller = Completer();

  static final CameraPosition _kGooglePlex = CameraPosition(
    target: LatLng(37.42796133580664, -122.085749655962),
    zoom: 14.4746,
  );

  static final CameraPosition _kLake = CameraPosition(
      bearing: 192.8334901395799,
      target: LatLng(37.43296265331129, -122.08832357078792),
      tilt: 59.440717697143555,
      zoom: 19.151926040649414);

  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      body: GoogleMap(
        mapType: MapType.hybrid,
        initialCameraPosition: _kGooglePlex,
        onMapCreated: (GoogleMapController controller) {
          _controller.complete(controller);
        },
      ),
      floatingActionButton: FloatingActionButton.extended(
        onPressed: _neverSatisfied,
        label: Text('Open dialog'),
        icon: Icon(Icons.bug_report),
      ),
    );
  }

  Future<void> _neverSatisfied() async {
    return showDialog<void>(
      context: context,
      barrierDismissible: false, // user must tap button!
      builder: (BuildContext context) {
        return AlertDialog(
          title: Text('Flutter Dialog'),
          content: SingleChildScrollView(
            child: ListBody(
              children: <Widget>[
                Text('Try to drag the map over this dialog'),
                Text(
                    'You can notice cursor icon stays the same when hovering over this dialog'),
              ],
            ),
          ),
          actions: <Widget>[
            FlatButton(
              child: Text('Dismiss'),
              onPressed: () {
                Navigator.of(context).pop();
              },
            ),
          ],
        );
      },
    );
  }

  // Future<void> _goToTheLake() async {
  //   final GoogleMapController controller = await _controller.future;
  //   controller.animateCamera(CameraUpdate.newCameraPosition(_kLake));
  // }
}

``` 

</details>

### Preview
https://user-images.githubusercontent.com/48603081/115204320-07a19000-a101-11eb-97d0-6d5361045686.mov


 
### Reproduced on the `web`
|  `web`  |  canvaskit  | html | 
| :---: | :---: | :---: |
debug | ✅ | ✅ |
release | ✅ |✅ |



<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 2.0.5, on macOS 11.2.3 20D91 darwin-x64, locale
    en-GB)
    • Flutter version 2.0.5 at /Users/tahatesser/Code/flutter_stable
    • Framework revision adc687823a (3 days ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.2.3 20D91 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 89.0.4389.128

• No issues found!
```

```bash
[✓] Flutter (Channel master, 2.2.0-11.0.pre.161, on macOS 11.2.3 20D91
    darwin-x64, locale en-GB)
    • Flutter version 2.2.0-11.0.pre.161 at
      /Users/tahatesser/Code/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ce18d702e9 (3 hours ago), 2021-04-19 01:44:02 -0400
    • Engine revision 60f12daf85
    • Dart version 2.14.0 (build 2.14.0-8.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2021.1)
    • IntelliJ at /Volumes/Extreme/IntelliJ IDEA CE.app
    • Flutter plugin version 55.0.5
    • Dart plugin version 211.6693.108

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.2.3 20D91 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 89.0.4389.128

• No issues found!

```
	
</details>

**Comment by Sammius** [comment] 2021-04-20 14:20
@Ayman-Kortobaa try using the widget specially made to solve this problem [pointer_interceptor](https://pub.dev/packages/pointer_interceptor)

I haven't used it on modals, but for buttons above the google map, it works well.

**Comment by stuartmorgan** [comment] 2021-04-22 18:05
@ditman Should we be tracking this as a bug, or is it unfixable other than a workaround like pointer_interceptor?

**Comment by ditman** [comment] 2021-04-22 19:51
@stuartmorgan this is a web framework issue with platform views, and for now it requires the `pointer_interceptor` package, yes. 

(Any flutter UI overlaid on top of a platform view in web, needs to be wrapped in the `pointer_interceptor` widget.)

**Comment by stuartmorgan** [comment] 2021-04-23 00:43
Is there an existing issue tracking a framework-level fix?

**Comment by TahaTesser** [comment] 2021-04-23 10:21
Removed wait abel, question was asked to the non-author user

**Comment by ditman** [comment] 2021-04-23 18:32
@stuartmorgan 

One part of the Scenelets proposal should address this: flutter.dev/go/flutter-web-scenelets

I can only find this issue that links to the proposal: https://github.com/flutter/flutter/issues/71884

**Comment by jonbhanson** [comment] 2021-06-02 16:31
I have run into this problem using `showModalBottomSheet` over a Google Map.  It can be solved for the contents of the bottom sheet by wrapping the contents with a [`PointerInterceptor`](https://pub.dev/packages/pointer_interceptor) as mentioned above. However, this is only half of the solution: Clicking on the greyed-out area that covers the portion of the app not covered by the bottom sheet should dismiss the bottom sheet, but if this click is over an `HtmlElementView`, the click is captured by the `HtmlElementView` and the sheet is not dismissed.  I am not aware of a way for me to fix this on my end.

It seems the solution would be to modify the bottom sheet to have a `PointerInterceptor` built-in, including the greyed out portion.  Is this possible?

**Comment by ditman** [comment] 2021-06-02 18:19
> It seems the solution would be to modify the bottom sheet to have a PointerInterceptor built-in, including the greyed out portion. Is this possible?

@jonbhanson yes, we're trying to figure out how to do that at the framework level.

In the meantime, have you tried stacking a transparent `PointerInterceptor` on top of your `GoogleMap` widget when you're showing the `ModalBottomSheet`? That might be a way to get the gray area to dismiss the sheet.

(I haven't tested that approach myself, but it might work?)

**Comment by jonbhanson** [comment] 2021-06-02 20:22
> In the meantime, have you tried stacking a transparent `PointerInterceptor` on top of your `GoogleMap` widget when you're showing the `ModalBottomSheet`? That might be a way to get the gray area to dismiss the sheet.

Thanks for the suggestion, @ditman!  It's a little hacky, but yes it does solve the problem.  👍🏻 I'll use that solution for the time being and look forward to a more permanent solution.

**Comment by ditman** [comment] 2021-06-02 20:39
Thanks for confirming @jonbhanson!

I might end up putting some helper in the PointerInterceptor package to block interactions with a component on the web, until we figure out the way to do this at the framework level (at which point the PointerInterceptor widget could be retired)

**Comment by ravidhu** [comment] 2021-06-30 10:11
Hello, 

I have this behavior with DraggableScrollableSheet and ListView. Here an example with DraggableScrollableSheet :

![flutterwebgesture](https://user-images.githubusercontent.com/3116614/123942916-e0d2c600-d99b-11eb-8427-eaf351446705.gif)

Chrome Browser on left, iPhone 8 Simulator on right. As you can see when i drag and swipe inside the DraggableScrollableSheet on the Browser, the map also move. This behavior is not present on the iphone.

This behavior is also present in "sliding_up_panel" package.

I dont know how i cant implement @ditman solution in my situation, can you give me more information please.

Here some code to reproduce :

main.dart
```
Future main() async {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.amber,
      ),
      routes: <String, WidgetBuilder>{
        '/': (BuildContext context) => HomeScreen()
      },
    );
  }
}
```

home.dart
```
class HomeScreen extends StatefulWidget {
  const HomeScreen({Key? key}) : super(key: key);

  @override
  _HomeScreenState createState() => _HomeScreenState();
}

class _HomeScreenState extends State<HomeScreen> {

  initState() {
    super.initState();
  }

  @override
  Widget build(BuildContext context) {

    return Stack(
      children: [
        ResponsiveLayout(
            mobileBody: Stack(
              children: [
                HomeMap(),
                BottomSlider(
                  child: ContentContainer(),
                )
              ],
            ),
            desktopBody: Stack(
              children: [
                HomeMap(),
                Sidebar(
                  child: ContentContainer(),
                )
              ],
            ),
        ),
      ],
    );
  }

}

```

responsive_layout.dart
```
class ResponsiveLayout extends StatelessWidget {

  final Widget mobileBody;
  final Widget? tabletBody;
  final Widget? desktopBody;

  const ResponsiveLayout({
    Key? key,
    required this.mobileBody,
    this.tabletBody,
    this.desktopBody,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return LayoutBuilder(
      builder: (context, dimens) {
        if (dimens.maxWidth < breakpointTablet) {
          return mobileBody;
        } else if (dimens.maxWidth >= breakpointTablet && dimens.maxWidth < breakpointDesktop) {
          return tabletBody ?? mobileBody;
        } else {
          return desktopBody ?? mobileBody;
        }
      },
    );
  }
}
```

home_map.dart
```
class HomeMap extends StatefulWidget {
  @override
  State<HomeMap> createState() => HomeMapState();
}

class HomeMapState extends State<HomeMap> {
  Completer<GoogleMapController> _controller = Completer();

  static final CameraPosition _parisPosition = CameraPosition(
    target: LatLng(48.8534, 2.3488),
    zoom: 14.4746,
  );

  @override
  Widget build(BuildContext context) {

    return GoogleMap(
      mapType: MapType.normal,
      initialCameraPosition: _parisPosition,
      onMapCreated: (GoogleMapController controller) {
        _controller.complete(controller);
      },
    );
  }

}
```

bottom_slider.dart
```
class BottomSlider extends StatelessWidget {
  final Widget child;

  const BottomSlider({Key? key, required this.child}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return DraggableScrollableSheet(
        initialChildSize: 0.2,
        minChildSize: 0.2,
        maxChildSize: 0.8,
        builder: (BuildContext context, ScrollController scrollController) {
          return Container(
              color: Colors.blue[100],
              child: child
          );
        }
    );
  }
}
```

sidebar.dart
```
class Sidebar extends StatelessWidget {

  final Widget child;

  const Sidebar({Key? key, required this.child}) : super(key: key);

  @override
  Widget build(BuildContext context) {

    double height = MediaQuery.of(context).size.height;

    return Container(
      height: height,
      width: 200,
      child: child,
    );
  }
}
```

content_container.dart
```
class ContentContainer extends StatelessWidget {
  const ContentContainer({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Container(
      color: Colors.blue[100],
      child: ListView.builder(
        itemCount: 25,
        itemBuilder: (BuildContext context, int index) {
          return Card(
            child: ListTile(title: Text('Item $index')),
          );
        },
      ),
    );
  }
}
```
Hope somebody can help me,
Best

**Comment by ditman** [comment] 2021-06-30 18:42
@ravidhu have you tried wrapping your `DraggableScrollableSheet` in a `PointerInterceptor` widget?

**Comment by ravidhu** [comment] 2021-07-02 20:31
> @ravidhu have you tried wrapping your `DraggableScrollableSheet` in a `PointerInterceptor` widget?

Works great ! do you think [this widget](https://pub.dev/packages/pointer_interceptor/example) will be part of flutter ?

**Comment by ditman** [comment] 2021-07-02 22:06
> @ravidhu do you think this widget will be part of flutter ?

It's already part of flutter, it's just not vended with the core framework :P

_(It's not part of flutter/flutter because we want to make it unnecessary in the future, but we're still not close to tackling that problem yet.)_

**Comment by yjbanov** [comment] 2022-01-07 20:37
Let's deduplicate with https://github.com/flutter/flutter/issues/93887. This is a good example how lack of pointer interceptor in modals manifests in practice, but it's not a new issue.

**Closed by yjbanov** 2022-01-07 20:37 UTC
Labels: engine, plugin, p: first party, p: maps, platform-web, e: web_html, e: web_canvaskit, has reproducible steps, P4, found in release: 2.0, found in release: 2.2
