### ISSUE TITLE
PopupMenuButton misplaced position

### ISSUE THREAD

**Issue by slavap** [flutter/flutter#68930] opened 2020-10-24 01:42 UTC
## Steps to Reproduce

Run attached app and press button on appBar.
Reproducible on both Web and Android.

![image](https://user-images.githubusercontent.com/4129763/97064875-4db8d500-155e-11eb-85f7-a7499e83fe24.png)

[popmenubtn_bug.zip](https://github.com/flutter/flutter/files/5432264/popmenubtn_bug.zip)

Could be related to https://github.com/flutter/flutter/issues/65724

flutter doctor -v

```
 Flutter (Channel beta, 1.23.0-18.1.pre, on Microsoft Windows [Version 10.0.19041.572], locale en-US)
    • Flutter version 1.23.0-18.1.pre at c:\Programs\flutter
    • Framework revision 198df796aa (8 days ago), 2020-10-15 12:04:33 -0700
    • Engine revision 1d12d82d9c
    • Dart version 2.11.0 (build 2.11.0-213.1.beta)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\slavap\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • CHROME_EXECUTABLE = c:\Programs\chrome-debug.bat

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code, 64-bit edition (version 1.50.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.15.1

[√] Connected device (3 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Web Server (web)                   • web-server    • web-javascript • Flutter Tools
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 86.0.4240.111

! Doctor found issues in 1 category.
```

**Comment by shihaohong** [comment] 2020-10-26 03:25
Hi @slavap could you share a code sample through a gist or as a comment? I'd prefer not to open a zip file posted on GitHub since it could be anything but a code sample :) Thank you!

**Comment by slavap** [comment] 2020-10-26 03:51
@shihaohong Don't be so paranoid 😃You cannot catch a virus from zip archive, only from running executable.
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        title: 'PopupMenuButton misplacement',
        theme: ThemeData(primarySwatch: Colors.blue),
        builder: (BuildContext context, Widget child) {
          final MediaQueryData m = MediaQuery.of(context);
          var horzOffset = m.size.width / 4;
          var d = m.copyWith(padding: EdgeInsets.fromLTRB(horzOffset, m.padding.top, horzOffset, m.padding.bottom));
          return MediaQuery(
            data: d,
            child: Navigator(
              pages: [
                MaterialPage(
                  key: ValueKey('Page1'),
                  child: SafeArea(
                    child: Scaffold(
                      appBar: AppBar(
                        title: Text('PopupMenuButton misplacement'),
                        actions: [
                          PopupMenuButton<int>(
                              itemBuilder: (context) => [
                                    PopupMenuItem<int>(
                                      value: 0,
                                      child: ListTile(
                                        leading: Icon(Icons.settings),
                                        title: Text('Settings'),
                                        contentPadding: EdgeInsets.symmetric(horizontal: 0.0),
                                        dense: true,
                                      ),
                                    ),
                                  ]),
                        ],
                      ),
                      body: Center(),
                    ),
                  ),
                )
              ],
              onPopPage: (route, result) => route.didPop(result),
            ),
          );
        });
  }
}
```

**Comment by slavap** [comment] 2020-10-29 04:10
@shihaohong Are you able to reproduce?

**Comment by pedromassangocode** [comment] 2020-10-30 13:21
I'm closing this as a duplicate of https://github.com/flutter/flutter/issues/68930.

Please follow up on that issue for updates.
Thank you

**Comment by shihaohong** [comment] 2020-11-08 05:53
@pedromassangocode Isn't #68930 this issue? I'll reopen it for now, you might've meant to tag a different issue.

**Comment by pedromassangocode** [comment] 2020-11-09 08:07
Thanks @shihaohong. I meant https://github.com/flutter/flutter/issues/65724

**Closed by pedromassangocode** 2020-11-09 08:07 UTC
Labels: f: material design, framework

**Comment by slavap** [comment] 2021-02-09 04:58
@pedromassangocode @shihaohong 
Guys, this issue is NOT fixed, the same problem in 1.26.0-17.3.pre, please reopen.

**Comment by slavap** [comment] 2021-02-24 22:37
@TahaTesser Could you please reopen this one, it is not fixed.

**Comment by pedromassangocode** [comment] 2021-02-25 11:40
> @TahaTesser Could you please reopen this one, it is not fixed.

This was closed as a duplicate of https://github.com/flutter/flutter/issues/65724, if you go to https://github.com/flutter/flutter/issues/65724 you can see that is was closed as duplicate as well, see https://github.com/flutter/flutter/issues/65724#issuecomment-758750599 and finally you can find the related (yet opened) issue there which is https://github.com/flutter/flutter/issues/31683. Please follow up on that issue and subscribe for updates.

Thank you

**Comment by slavap** [comment] 2021-02-25 13:38
@pedromassangocode Thanks! Actually sounds like investigation :-)
