### ISSUE TITLE
[Web] : Overlays with white barrier color flash black before going to the right color.

### ISSUE THREAD

**Issue by FabrizioG2000** [flutter/flutter#67354] opened 2020-10-05 21:23 UTC
I'm trying to change the grey-out effect that runs when a dialog (or drawer) opens, from the default value which is a shade of Black to a shade of White.
I get the desired effect when the animation of the barrier "fading in" ends but while the animation runs, the barrier flashes gray/black before going white.

The effect is more visible if the barrierColor is set to `Colors.white.withOpacity(1.0)`

A video of the effect:
https://youtu.be/E2gdm77T8Q8

The effect can be replicated using this code:
```
  showDialog(
    context: context,
    barrierColor: Colors.white.withOpacity(0.2),
    builder: (context) {
      return Center(
        child: Container(
          color: Colors.white,
          child: Material(
            child: Padding(
              padding: const EdgeInsets.all(20.0),
              child: Text("Dialog"),
            ),
          ),
        ),
      );
    });
```

Flutter doctor:
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, 1.23.0-8.0.pre.35, on Microsoft Windows, locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.5.4)
[√] Android Studio (version 4.0)
[√] VS Code, 64-bit edition (version 1.49.3)
[√] Connected device (4 available)
```

This effect doesn't happen when changing the opacity of a white container from 0.0 to 0.5 for example, so is this an intended effect or is there a way to fix this?

**Comment by darshankawar** [comment] 2020-10-06 09:48
@FabrizioG2000 
Can you provide a video / gif of the issue you are facing ? that way it'll be easier to understand issue better.
Thanks,

**Comment by FabrizioG2000** [comment] 2020-10-07 20:10
I've added a link to the video displaying this effect:
https://youtu.be/E2gdm77T8Q8

**Comment by darshankawar** [comment] 2020-10-08 07:01
@FabrizioG2000 
Tried on latest beta using your code sample, but didn't notice the black flash upon tap, unless I missed any step to properly replicate.

[67354.mov.zip](https://github.com/flutter/flutter/files/5345862/67354.mov.zip)

```
body: Center(
  child: RaisedButton(
    child: Text('Open'),
    onPressed: () {
      showDialog(
          context: context,
          barrierColor: Colors.white.withOpacity(0.5),
          builder: (context) {
            return Center(
              child: Container(
                color: Colors.white,
                child: Material(
                  child: Padding(
                    padding: const EdgeInsets.all(20.0),
                    child: Text("Dialog"),
                  ),
                ),
              ),
            );
          });
    },
  )
)
```

**Comment by FabrizioG2000** [comment] 2020-10-08 13:44
I copied the your code in the latest beta (i ran `flutter channel beta` and `flutter upgrade --force `as I tried modifying the dialog class before to remove this effect) but the strange flash still shows unlike your video. Maybe It depends on the platform? I recorded the video on windows but the effect shows on android too.

**Comment by FabrizioG2000** [comment] 2020-10-08 13:51
I also noticed that the effect becomes more visible the more the opacity of the white used for barrierColor

**Comment by darshankawar** [comment] 2020-10-09 06:18
@FabrizioG2000 
Tried on latest master with increased opacity. Noticed a black flash before moving to show dialog. Is that an exact interpretation of your issue ?

[67354.mov.zip](https://github.com/flutter/flutter/files/5352877/67354.mov.zip)

**Comment by FabrizioG2000** [comment] 2020-10-09 10:14
Yes, that's it. I don't know why the last time you tried it didn't show.

**Comment by darshankawar** [comment] 2020-10-09 11:32
I was able to replicate the issue per my earlier [comment](https://github.com/flutter/flutter/issues/67354#issuecomment-705992266).

**Comment by sysint64** [comment] 2021-03-31 12:16
@FabrizioG2000, @chunhtai #69668 should fix it. I checked on flutter 2.0, and it works fine.

**Comment by darshankawar** [comment] 2022-11-24 12:47
Verified using latest versions and observed that the issue is not replicable.


https://user-images.githubusercontent.com/67046386/203788150-117cd9c8-5f47-49f9-9060-2c40399ec6c1.mov


<details>
<summary> stable, master flutter doctor -v </summary>

```
[✓] Flutter (Channel stable, 3.3.8, on macOS 12.2.1 21D62 darwin-x64, locale
    en-GB)
    • Flutter version 3.3.8 on channel stable at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 52b3dc25f6 (25 hours ago), 2022-11-09 12:09:26 +0800
    • Engine revision 857bd6b74c
    • Dart version 2.18.4
    • DevTools version 2.15.0

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

[!] Flutter (Channel master, 3.6.0-7.0.pre.18, on macOS 12.2.1 21D62 darwin-x64,
    locale en-GB)
    • Flutter version 3.6.0-7.0.pre.18 on channel master at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2921ca0c48 (2 hours ago), 2022-11-21 21:43:26 -0500
    • Engine revision 8dd8e092e4
    • Dart version 2.19.0 (build 2.19.0-415.0.dev)
    • DevTools version 2.19.0
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.



```

</details>


Closing as fixed.

**Closed by darshankawar** 2022-11-24 12:47 UTC
Labels: framework, f: material design, platform-web, has reproducible steps, P4, found in release: 1.23
