### ISSUE TITLE
[tool_crash] FileSystemException: Failed to set file modification time, path = 'F:\FlutterProject\TestLearnFlutter\flutter_app\.packages' (OS Error: 拒绝访问。, errno = 5)

### ISSUE THREAD

**Issue by zhangrurong8** [flutter/flutter#56747] opened 2020-05-09 03:20 UTC
## Command
```
flutter --no-color run --machine --track-widget-creation --device-id=0123456789ABCDEF lib\main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: FileSystemException: Failed to set file modification time, path = 'F:\FlutterProject\TestLearnFlutter\flutter_app\.packages' (OS Error: 拒绝访问。
, errno = 5)
```
#0      _File.setLastModifiedSync (dart:io/file_impl.dart:473:7)
#1      ForwardingFile.setLastModifiedSync (package:file/src/forwarding/forwarding_file.dart:62:55)
#2      ForwardingFile.setLastModifiedSync (package:file/src/forwarding/forwarding_file.dart:62:55)
#3      _DefaultPub.get (package:flutter_tools/src/dart/pub.dart:213:19)
#4      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:705:17)
<asynchronous suspension>
#5      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:619:33)
<asynchronous suspension>
#6      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart)
#7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#8      _rootRun (dart:async/zone.dart:1184:13)
#9      _CustomZone.run (dart:async/zone.dart:1077:19)
#10     _runZoned (dart:async/zone.dart:1619:10)
#11     runZoned (dart:async/zone.dart:1539:10)
#12     AppContext.run (package:flutte

**Comment by TahaTesser** [comment] 2020-05-11 07:44
Duplicate of [#49948](https://github.com/flutter/flutter/issues/49948)
Closing in favor of [#50880](https://github.com/flutter/flutter/issues/50880) based on this [comment](https://github.com/flutter/flutter/issues/49948#issuecomment-586645352)
Thank you

**Closed by TahaTesser** 2020-05-11 07:44 UTC
