### ISSUE TITLE
Got socket error trying to find package sqflite at https://pub.dartlang.org. - visual studio code

### ISSUE THREAD

**Issue by Emred360** [flutter/flutter#66515] opened 2020-09-24 01:54 UTC
Please any solution. thanks.

![problem](https://user-images.githubusercontent.com/33384064/94091890-402cf580-fdce-11ea-85bd-7d0185f789e2.PNG)

**Comment by TahaTesser** [comment] 2020-09-24 08:01
Hi @Emred360 
From what I can see, the issue is related to a `pub` rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/dart-lang/pub/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by TahaTesser** 2020-09-24 08:01 UTC

**Comment by Emred360** [comment] 2020-09-27 03:12
Hi @TahaTesser 

I ran flutter doctor -v as instructed.
However, this particular problem has been solved, but it appears that there exists another problem. 
I will attach both screenshots to this comment
![image](https://user-images.githubusercontent.com/33384064/94354928-8b484200-0034-11eb-8aa4-74937a026eab.png)

![image](https://user-images.githubusercontent.com/33384064/94354940-a4e98980-0034-11eb-9a8a-64eba1fb9419.png)

**Comment by TahaTesser** [comment] 2020-09-28 14:14
hI @Emred360 
That is unrelated to this, please file a new issue and provide all the details and logs, instead of screenshots
