### ISSUE TITLE
Issue from website page Flutter FAQ

### ISSUE THREAD

**Issue by 15271480287** [flutter/flutter#89360] opened 2021-09-02 10:13 UTC
From URL: https://www.flutterchina.club/faq.md
![P XLA4$6(_YJ0S722 O(}%9](https://user-images.githubusercontent.com/42195248/131826170-65ffc39f-2e25-4715-8bd4-2d9a6368b853.png)

**Comment by TahaTesser** [comment] 2021-09-02 11:09
Hi @15271480287 
The link provided is not an official 

duplicate of https://github.com/flutter/flutter/issues/59770

**Closed by TahaTesser** 2021-09-02 11:09 UTC
Labels: in triage
