### ISSUE TITLE
firebase_admob 0.10.2 has a crash and don't loads Ads

### ISSUE THREAD

**Issue by yoavsbg** [flutter/flutter#70082] opened 2020-11-09 09:04 UTC
In firebase admob version: [0.10.2 ](https://pub.dev/packages/firebase_admob/versions/0.10.2)
I'm getting an exception which does not reproduce in version [0.10.0 ](https://pub.dev/packages/firebase_admob/versions/0.10.0)
the exception details is:

W/ConnectionTracker(15436): Exception thrown while unbindingW/ConnectionTracker(15436): java.lang.IllegalArgumentException: Service not registered: com.google.android.gms.measurement.internal.zzji@9686ccfW/ConnectionTracker(15436): at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1870)W/ConnectionTracker(15436): at android.app.ContextImpl.unbindService(ContextImpl.java:1848)W/ConnectionTracker(15436): at android.content.ContextWrapper.unbindService(ContextWrapper.java:755)W/ConnectionTracker(15436): at com.google.android.gms.common.stats.ConnectionTracker.zza(com.google.android.gms:play-services-basement@@17.3.0:55)W/ConnectionTracker(15436): at com.google.android.gms.common.stats.ConnectionTracker.unbindService(com.google.android.gms:play-services-basement@@17.3.0:50)W/ConnectionTracker(15436): at com.google.android.gms.measurement.internal.zzio.zzag(com.google.android.gms:play-services-measurement-impl@@17.6.0:245)W/ConnectionTracker(15436): at com.google.android.gms.measurement.internal.zzio.zzal(com.google.android.gms:play-services-measurement-impl@@17.6.0:262)W/ConnectionTracker(15436): at com.google.android.gms.measurement.internal.zzio.zzc(com.google.android.gms:play-services-measurement-impl@@17.6.0:336)W/ConnectionTracker(15436): at com.google.android.gms.measurement.internal.zzir.zza(com.google.android.gms:play-services-measurement-impl@@17.6.0:2)W/ConnectionTracker(15436): at com.google.android.gms.measurement.internal.zzai.run(com.google.android.gms:play-services-measurement-impl@@17.6.0:7)W/ConnectionTracker(15436): at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)W/ConnectionTracker(15436): at java.util.concurrent.FutureTask.run(FutureTask.java:266)W/ConnectionTracker(15436): at com.google.android.gms.measurement.internal.zzfs.run(com.google.android.gms:play-services-measurement-impl@@17.6.0:21)

**Comment by pedromassangocode** [comment] 2020-11-09 10:35
Hi @yoavsbg 
From what I can see, the issue is related to a FlutterFire plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by pedromassangocode** 2020-11-09 10:35 UTC
