### ISSUE TITLE
image_picker plugin can not get image's  origin file path

### ISSUE THREAD

**Issue by zlmClover** [flutter/flutter#79789] opened 2021-04-05 15:46 UTC
My function is that a picture can only be imported once，so I need to get the original file path  of the picture for comparison,but I found image_picker not support it.

**Comment by pedromassangocode** [comment] 2021-04-06 07:51
This is a duplicate of https://github.com/flutter/flutter/issues/64685 / https://github.com/flutter/flutter/issues/54815. Please follow up on those issues for updates.
Thank you

**Closed by pedromassangocode** 2021-04-06 07:51 UTC
Labels: in triage
