### ISSUE TITLE
java.lang.IllegalStateException

### ISSUE THREAD

**Issue by gabrc52** [flutter/flutter#26997] opened 2019-01-24 01:50 UTC
On a production app, a single device (HWDRA-MG on Android 8.1) is crashing with `java.lang.IllegalStateException`: (I can't reproduce this, and Play Console says it happens only on a single device)

```
java.lang.RuntimeException: 
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2969)
  at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:3047)
  at android.app.ActivityThread.-wrap11 (Unknown Source)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1777)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:166)
  at android.app.ActivityThread.main (ActivityThread.java:6857)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:450)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:936)
Caused by: java.lang.IllegalStateException: 
  at io.flutter.view.FlutterMain.ensureInitializationComplete (FlutterMain.java:178)
  at io.flutter.app.FlutterActivityDelegate.onCreate (FlutterActivityDelegate.java:152)
  at io.flutter.app.FlutterActivity.onCreate (FlutterActivity.java:85)
  at [App's package name].MainActivity.onCreate (MainActivity.java:11)
  at android.app.Activity.performCreate (Activity.java:7110)
  at android.app.Activity.performCreate (Activity.java:7101)
  at android.app.Instrumentation.callActivityOnCreate (Instrumentation.java:1214)
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2922)
```

Are Dart exceptions caught on the Java side? Does this mean there's a bug in Flutter or in my app? I don't think there's any documentation on this.

**Comment by jason-simmons** [comment] 2019-01-24 02:06
This exception is thrown by the Java libraries used to integrate Flutter into an application.  See https://github.com/flutter/engine/blob/master/shell/platform/android/io/flutter/view/FlutterMain.java#L177, or https://docs.flutter.io/javadoc/

`ensureInitializationComplete` might throw if it was called from the wrong thread or if it was called before `startInitialization`.  The standard Android host code provided by Flutter should do this initialization sequence correctly.  We'd have to reproduce this on the affected device to learn more.

**Comment by allanwolski** [comment] 2019-02-27 12:58
Possible duplicate of #24287

**Comment by gabrc52** [comment] 2019-02-28 19:13
Closing as duplicate

**Closed** 2019-02-28 19:13 UTC
Labels: a: existing-apps, engine, severe: crash
