### ISSUE TITLE
[tool_crash] StateError: Bad state: No context with the running Dart application.

### ISSUE THREAD

**Issue by KarimAbdo** [flutter/flutter#98885] opened 2022-02-21 22:03 UTC
## Command
```
flutter --no-color run --machine --track-widget-creation --device-id=chrome --start-paused --web-port=3000 --web-renderer html --dart-define=flutter.inspector.structuredErrors=true lib/main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
StateError: Bad state: No context with the running Dart application.
```
#0      RemoteDebuggerExecutionContext.id (package:dwds/src/debugging/execution_context.dart:55:7)
<asynchronous suspension>
#1      AppInspector._getExtensionRpcs (package:dwds/src/debugging/inspector.dart:538:20)
<asynchronous suspension>
#2      AppInspector._initialize (package:dwds/src/debugging/inspector.dart:97:34)
<asynchronous suspension>
#3      AppInspector.initialize (package:dwds/src/debugging/inspector.dart:160:5)
<asynchronous suspension>
#4      ChromeProxyService.createIsolate (package:dwds/src/services/chrome_proxy_service.dart:217:18)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 2.8.1, on Mac OS X 10.15.7 19H1713 darwin-x64, locale en-US)
    • Flutter version 2.8.1 at /Users/karimabdo/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (10 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/karimabdo/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2020.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 63.2.1
    • Dart plugin version 203.8452

[✓] VS Code (version 1.52.1)
    • VS Code at /Users/karimabdo/Downloads/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 98.0.4758.102

! Doctor found issues in 2 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 2.2.0
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: dev
**Creation framework version**: ed90d05596d85b0ec8e841395bce9d3b6edea134
### Plugins
add_2_calendar-2.1.2
background_location-0.8.1
camera-0.8.1+7
device_info-2.0.3
devicelocale-0.4.3
file_picker-3.0.4
firebase_analytics-8.3.4
firebase_analytics_web-0.3.0+1
firebase_core-1.10.0
firebase_core_web-1.2.0
firebase_dynamic_links-2.0.11
firebase_messaging-10.0.9
firebase_messaging_web-2.1.0
firebase_remote_config-0.10.0+5
flutter_app_badger-1.3.0
flutter_geocoder-0.2.2-nullsafety
flutter_image_compress-1.1.0
flutter_inappwebview-5.3.2
flutter_keyboard_visibility-5.1.0
flutter_keyboard_visibility_web-2.0.0
flutter_plugin_android_lifecycle-2.0.5
gallery_saver-2.3.2
google_api_headers-1.1.1
google_maps_flutter-2.0.9
google_maps_flutter_web-0.3.2
image_cropper-1.4.1
image_picker-0.8.4+1
image_picker_for_web-2.1.4
launch_review-3.0.1
location-4.3.0
location_web-3.1.1
maps_launcher-2.0.1
native_device_orientation-1.0.0
open_file-3.2.1
open_mail_app-0.1.1
package_info-2.0.2
package_info_plus-1.3.0
package_info_plus_macos-1.3.0
package_info_plus_web-1.0.4
path_provider-2.0.8
path_provider_android-2.0.11
path_provider_ios-2.0.7
path_provider_linux-2.1.2
path_provider_macos-2.0.3
path_provider_windows-2.0.4
permission_handler-7.2.0
share-2.0.4
shared_preferences-2.0.7
shared_preferences_linux-2.0.3
shared_preferences_macos-2.0.2
shared_preferences_web-2.0.2
shared_preferences_windows-2.0.3
social_share-2.2.1
sqflite-2.0.0+4
twilio_programmable_video-0.8.0+1
uni_links-0.5.1
uni_links_web-0.1.0
url_launcher-6.0.10
url_launcher_linux-2.0.2
url_launcher_macos-2.0.2
url_launcher_web-2.0.4
url_launcher_windows-2.0.2
video_player-2.2.3
video_player_web-2.0.4
wakelock-0.4.0
wakelock_macos-0.1.0+3
wakelock_web-0.2.0+3
webview_flutter-2.0.13

**Comment by danagbemava-nc** [comment] 2022-02-22 07:16
Duplicate of #95916

**Closed by danagbemava-nc** 2022-02-22 07:16 UTC
Labels: in triage
