### ISSUE TITLE
FadeInImage placeholder property should be a widget not an Image

### ISSUE THREAD

**Issue by ride4sun** [flutter/flutter#13320] opened 2017-12-02 18:20 UTC
`FadeInImage` property `placeholder` requires a Image. That could be way more flexible with an widget. Than the API user can provide what ever he needs to. E.g. I would like to show just a blury square with a progress indicator

```
Microsoft Windows [Version 10.0.16299.98]
(c) 2017 Microsoft Corporation. All rights reserved.

C:\Projects\lambDev\lookatmybaby_flutter>flutter doctor
[√] Flutter (on Microsoft Windows [Version 10.0.16299.98], locale en-US, channel alpha)
    • Flutter at c:\sdks\flutter
    • Framework revision d957c8f040 (2 days ago), 2017-11-30 13:29:59 -0800
    • Engine revision 77d8acb9be
    • Tools Dart version 1.25.0-dev.11.0
    • Engine Dart version 2.0.0-dev.9.0

[√] Android toolchain - develop for Android devices (Android SDK 27.0.1)
    • Android SDK at C:\Users\ride4\AppData\Local\Android\sdk
    • Unable to locate Android NDK.

    • Unable to locate compiler in Android NDK.

    • Platform android-27, build-tools 27.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] Android Studio (version 3.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] IntelliJ IDEA Community Edition (version 2017.2)
    • Flutter plugin version 19.1
    • Dart plugin version 172.4343.25

[√] Connected devices
    • None
```

**Comment by samuelg123** [comment] 2019-04-25 10:31
Any updates?

**Comment by iapicca** [comment] 2019-11-01 14:05
Hi @ride4sun 
I'm closing this issue as it refer to an older version of Flutter.
If you are you still experiencing this issue with the latest version of Flutter,
you may want to open a new issue or comment below;
either way please provide your updated `flutter doctor -v`.
It would be helpful to have also your` flutter run --verbose`
and a self contained app on github (or the steps to reproduce it).
Thank you

**Closed by iapicca** 2019-11-01 14:05 UTC
Labels: framework, severe: new feature

**Comment by ride4sun** [comment] 2019-11-01 18:26
Could u not just check if it accepts a widget now and closes it because it does or leaves it open because it does not.

**Comment by matuella** [comment] 2021-06-30 16:58
I don't think this issue should still be closed, as it seems to be like an API design-flaw. I don't see why not expand this particular use-case, where one would want FadeInImage.placeholder to be any possible Widget other than having to update the implementation that takes advantage of both properties being an Image (more specifically the _AnimatedFadeOutFadeIn widget).

I'm up to suggest a PR for this change, but I would like to know if this is an acceptable update to `FadeInNetwork` API update.

**Comment by ride4sun** [comment] 2021-06-30 18:10
Totally
