### ISSUE TITLE
Flutter autocomplete stops working after launching Android emulator

### ISSUE THREAD

**Issue by SarunasDaubaris** [flutter/flutter#74886] opened 2021-01-28 09:17 UTC
I ran into a problem where Android Studio/IntelliJ Flutter/Dart autocomplete and imports suggestion stops working. Once AS is restarted the problem disappears.

Description and steps to reproduces are given below.

**Steps to reproduce**
 1. Open existing Flutter project in Android Studio;
 2. Create a new variable;
 3. Click Alt+Enter to import the variable's class;
 4. The Dart package is imported;
 5. Launch Android emulator
 6. Create another variable;
 7. Click Alt+Enter to import the variable's class;
 *Expected*: class is imported
 *Actual*: No import suggestions are given. When writing the class name, no autocomplete

**Software versions**
Windows 10 Pro x64
Android Studio 4.1.2
Android Emulator 30.3.5 version

**Flutter doctor**
Flutter (Channel stable, 1.22.5, on Microsoft Windows [Version 10.0.19042.685], locale lt-LT)

**System**
Dell Precision 7540

I tried googling for this but haven't found similar questions. I guess this is related to what ports are used by the Dart analysis server and the Android emulator. Restarting AS 20 times per day doesn't seem like an efficient solution.

**Comment by pedromassangocode** [comment] 2021-01-28 09:27
Hi @SarunasDaubaris 
Following the indication of [jetbrains' Flutter plugin](https://plugins.jetbrains.com/plugin/9212-flutter), the correct way to address the problem is to open an issue in the dedicated [repository](https://github.com/flutter/flutter-intellij/issues).
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by pedromassangocode** 2021-01-28 09:27 UTC
