### ISSUE TITLE
Flutter --launch apple emulators crashing

### ISSUE THREAD

**Issue by andreimcristof** [flutter/flutter#19387] opened 2018-07-15 11:22 UTC
Hello, trying to start either the "apple" simulator or the "iOS Simulator" is crashing, please see error log below. 

## Steps to Reproduce

flutter emulators --launch apple --verbose

## Logs

```
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter emulators --launch apple --verbose

## exception

_TypeError: type '_TypeError' is not a subtype of type 'String'

#0      EmulatorsCommand._launchEmulator (package:flutter_tools/src/commands/emulators.dart:75:20)
<asynchronous suspension>
#1      EmulatorsCommand.runCommand (package:flutter_tools/src/commands/emulators.dart:47:13)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:347:18)
#3      _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#4      _rootRunUnary (dart:async/zone.dart:1134:38)
#5      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#6      _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:638:45)
#8      Future._propagateToListeners (dart:async/future_impl.dart:667:32)
#9      Future._complete (dart:async/future_impl.dart:472:7)
#10     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#11     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
#12     _rootRun (dart:async/zone.dart:1126:13)
#13     _CustomZone.run (dart:async/zone.dart:1023:19)
#14     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:949:23)
#15     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#16     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#17     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:113:13)
#18     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:166:5)
```

```
[✓] Flutter (Channel master, v0.5.7-pre.122, on Mac OS X 10.13.4 17E199, locale en-DE)
    • Flutter version 0.5.7-pre.122 at /Users/andreicristof1/Library/flutter
    • Framework revision e7832a3897 (19 hours ago), 2018-07-14 09:32:41 -0700
    • Engine revision c5a63d28bf
    • Dart version 2.0.0-dev.67.0.flutter-84ca27a09e

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/andreicristof1/Library/Android/sdk/
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = /Users/andreicristof1/Library/Android/sdk/
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 20.0.1
    • Dart plugin version 171.4424
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] VS Code (version 1.25.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.15.0

[!] Connected devices
    ! No devices available

! Doctor found issues in 1 category.
```

**Comment by zoechi** [comment] 2018-07-19 09:13
@DanTup is this related to your work? 
I think you were working on starting the emulator from `flutter`?

**Comment by DanTup** [comment] 2018-07-19 09:31
Yeah, it was a bug that Dart1 was happy to ignore but Dart2 is not.

Fix is at https://github.com/flutter/flutter/pull/19454 awaiting review - I'm hoping to get it reviewed and merged to master today.

**Comment by DanTup** [comment] 2018-07-19 09:32
(So this is a dupe of https://github.com/flutter/flutter/issues/19453).

**Closed by DanTup** 2018-07-19 09:32 UTC
Labels: tool, ⌺‬ platform-ios

**Comment by DanTup** [comment] 2018-07-19 09:33
Fix has landed. Please update and lmk if you still see any issues.

**Comment by andreimcristof** [comment] 2018-07-19 09:37
Works now!

**Comment by DanTup** [comment] 2018-07-19 09:43
Great, thanks for confirming!
