### ISSUE TITLE
transparent image show black background in ios (iOS 9.3.1) with Flutter version 1.2.0

### ISSUE THREAD

**Issue by zmtzawqlp** [flutter/flutter#28973] opened 2019-03-07 01:28 UTC
transparent image show black background in ios (iOS 9.3.1)

please run transparent_image_test1.zip demo, 
two image looks like the same, but 
empty_light_bad.png will show black background
empty_light_good.png looks good.
for more,  Flutter version 1.1.5-1.1.9 is good, and  Flutter version 1.2.0-1.30 is bad.
the code is broken in 1.2.0,please take a look.

[transparent_image_test1.zip](https://github.com/flutter/flutter/files/2939026/transparent_image_test1.zip)

```
[✓] Flutter (Channel unknown, v1.2.1, on Mac OS X 10.14.1 18B75, locale en-GB)
    • Flutter version 1.2.1 at
      /Users/huilee/Documents/Company/flutter_all/flutter_1.2.1
    • Framework revision 8661d8aecd (3 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from:
      https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK
      components.
      (or visit https://flutter.io/setup/#android-setup for detailed
      instructions).
      If Android SDK has been installed to a custom location, set ANDROID_HOME
      to that location.
      You may also want to add it to your PATH environment variable.


[!] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    ! CocoaPods out of date (1.5.0 is recommended).
        CocoaPods is used to retrieve the iOS platform side's plugin code that
        responds to your plugin usage on the Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work
        on iOS.
        For more info, see https://flutter.io/platform-plugins
      To upgrade:
        brew upgrade cocoapods
        pod setup

[!] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[!] IntelliJ IDEA Ultimate Edition (version 2017.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.30.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.24.0

[✓] Connected device (1 available)
    • iPhone (10) • 1b9c5686e9adb996bd21a9c66ec5a61eec1683d6 • ios • iOS 9.3.1

! Doctor found issues in 4 categories.

```

**Comment by zmtzawqlp** [comment] 2019-03-07 03:38
![aa69d8ed-d6d0-4062-a538-1bd852c30fc8](https://user-images.githubusercontent.com/16477333/53930787-8ed04d00-40cd-11e9-8f16-c6fb7a3a9be2.png)

**Comment by Kartik1607** [comment] 2019-03-07 14:42
Which device are you testing on? Is the issue repetitive and reproduced every time? I had no issue on Pixel (API 28) emulator.
![image](https://user-images.githubusercontent.com/17377741/53964387-489edc00-4115-11e9-8cae-81e3b2d84c07.png)

**Comment by zmtzawqlp** [comment] 2019-03-07 14:52
> Which device are you testing on? Is the issue repetitive and reproduced every time? I had no issue on Pixel (API 28) emulator.
> ![image](https://user-images.githubusercontent.com/17377741/53964387-489edc00-4115-11e9-8cae-81e3b2d84c07.png)

this is flutter doctor info, iPhone (10) • 1b9c5686e9adb996bd21a9c66ec5a61eec1683d6 • ios • iOS 9.3.1
and test device is iPhone6, this issue is  reproduced every time

**Comment by lihui2333** [comment] 2019-03-08 07:01
@zoechi Any solution?

**Comment by zmtzawqlp** [comment] 2019-03-08 07:23
@lihui2333 guy , the same issue for you ?

**Comment by lihui2333** [comment] 2019-03-08 07:28
Yes,hope to solve as soon as possible @zmtzawqlp

**Comment by GaryQian** [comment] 2019-03-08 19:06
@liyuqian could this be skia related?

**Comment by liyuqian** [comment] 2019-03-08 22:27
I just ran it on an iPhone 6s and a iPhone simulator. Both of them are on iOS 12.1.2 and there's no issue for both PNGs. Is this issue specific to iOS 9.3.1? If so, I'd suspect some GPU driver issue that some new Skia change reveals, which is later fixed by newer iOS versions.

![flutter_03](https://user-images.githubusercontent.com/22987568/54059415-f067e880-41ad-11e9-8e25-26c81992fded.png)

**Comment by GaryQian** [comment] 2019-03-08 23:09
Do you think it could be related to https://github.com/flutter/flutter/issues/28227?

**Comment by liyuqian** [comment] 2019-03-08 23:25
Probably not related to https://github.com/flutter/flutter/issues/28227 because that's about vector graphics specifically. This issue is about PNG which seems to have no vector graphics at all.

**Comment by 991518961** [comment] 2019-03-09 01:47
only happens on flutter version or above，it will not happen below version 2.0.maybe some changes in engine causeed this issue.

**Comment by lihui2333** [comment] 2019-03-09 01:49
only happens on flutter version or above，it will not happen below version 2.0.maybe some changes in engine causeed this issue.

**Comment by songfei** [comment] 2019-03-11 02:25
@GaryQian    look this  https://github.com/dnfield/flutter_svg/issues/126  ,    I think it is not related to #28227.

**Closed** 2019-03-29 22:35 UTC
Labels: a: images, waiting for customer response, ⌺‬ platform-ios

**Comment by hahn** [comment] 2019-08-22 01:39
any solution or update  on this issue? I have same problems, in iOS (version 12.1) can't load transparent png
flutter version: 1.9.0
