### ISSUE TITLE
Flutter demo app that includes all official plugins for CI and testing

### ISSUE THREAD

**Issue by ghost** [flutter/flutter#16736] opened 2018-04-19 08:33 UTC
I am doing CI testing on different devices.

Could the team make a Flutter Plugin Gallery please that uses all the official plugins and publish it to the Play and Apple store please ?

It will make it much easier to test on various real devices and in saucelabs.

**Comment by stuartmorgan** [comment] 2021-12-02 03:35
Closing as a duplicate of https://github.com/flutter/flutter/issues/18237, which seems to be requesting the same thing but has more discussion.

**Closed by stuartmorgan** 2021-12-02 03:35 UTC
Labels: a: tests, severe: new feature, plugin, p: first party, P5
