### ISSUE TITLE
Macos desktop embedder not allowing copy/paste into a textfield

### ISSUE THREAD

**Issue by DaveShuckerow** [flutter/flutter#42535] opened 2019-10-11 17:19 UTC
Running the following code in the Mac or Linux desktop embedder, I can't paste text into the `TextField` widget:
https://github.com/flutter/devtools/blob/master/packages/devtools_app/lib/src/flutter/connect_screen.dart#L81

```
~$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.10.15-pre.84, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 3.4)
[✓] IntelliJ IDEA Ultimate Edition (version 2018.3)
[✓] VS Code (version 1.38.1)
[✓] Connected device (4 available)
```

**Comment by stuartmorgan** [comment] 2019-10-11 18:40
Duplicate of #30709

**Closed by stuartmorgan** 2019-10-11 18:40 UTC
Labels: a: desktop
