### ISSUE TITLE
[isolate] Exception thrown from isolate cant catch (ie: type cant filter)

### ISSUE THREAD

**Issue by peterweb2005** [flutter/flutter#90922] opened 2021-09-29 02:35 UTC
for example, i throw a exception inside isolate,

```
throw SocketException('io or read timeout')
```

then i CAN catch the "exception" from the isolate call
```
        await compute(isolateRequest, [
          client,
          request,
        ]);
```

but the error or "exception" caught cant filter
even cant filter by the "case Exception" clause, the error is not Exception?

and when the error thrown not thought isolate is good, can filter

```
    switch (error.runtimeType) {
      case SocketException: // socket or conn
        message = fromSocketException(error);
        break;
      case Exception:
        message = fromException(error);
        break;
      default:
    }
```

**Comment by TahaTesser** [comment] 2021-09-29 09:19
Hi @peterweb2005 
The issue is not related to Flutter itself, please file an issue on the Dart SDK repository.
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-09-29 09:19 UTC
Labels: in triage
