### ISSUE TITLE
RefreshIndicator breaks when the ListView is a child of SingleChildScrollView

### ISSUE THREAD

**Issue by ibyet05** [flutter/flutter#69468] opened 2020-10-31 13:24 UTC
Hi, 

I have similar problem which is stated at #22180. But the suggested solution did not work for me in the below code.

Can you please help me, how I can solve this problem. thanks. 

```
> SingleChildScrollView(
>           scrollDirection: Axis.horizontal,
>           child: SizedBox(
>             width: 2000,
>             child: RefreshIndicator(
>               onRefresh: () {
>                 return Future.delayed(Duration(seconds: 2));
>               },
>               child: ListView.builder(
>                 itemCount: 100,
>                 physics: const AlwaysScrollableScrollPhysics(),
>                 itemBuilder: (context, i) => ListTile(
>                   title: Text("Text $i"),
>                 ),
>               ),
>             ),
>           )),

```

**Comment by hamdikahloun** [comment] 2020-10-31 14:11
Hi @ibyet05 

Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a minimal complete reproducible code sample?

Thank you

**Comment by ibyet05** [comment] 2020-10-31 14:22
> Hi @ibyet05
> 
> Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a minimal complete reproducible code sample?
> 
> Thank you

it is not related with flutter doctor, please use the above code in any flutter app.  You will see that refresh indicator does not work.

**Comment by renanzdm** [comment] 2020-10-31 17:40
I copied your code and it worked here, but the problem is that you defined the width of your sizedBox in 2000 so the refresh appears only in the middle of the screen. To solve it just put the width as MediaQuery.of (context) .size.width;
Doing this will solve your problem

` return Scaffold(
      body: SafeArea(
        child: SingleChildScrollView(
            scrollDirection: Axis.horizontal,
            child: SizedBox(
              width: 2000,
              height: sizes.height,
              child: RefreshIndicator(
                onRefresh: () {
                  return Future.delayed(Duration(seconds: 2));
                },
                child: ListView.builder(
                  itemCount: 100,
                  physics: const AlwaysScrollableScrollPhysics(),
                  itemBuilder: (context, i) => ListTile(
                    title: Text("Text $i"),
                  ),
                ),
              ),
            )),
      ),
    );`

**Comment by iapicca** [comment] 2020-10-31 21:08
@ibyet05 
I agree with @renanzdm 
it works perfectly, the issue must be with your implementation
try running the code sample below on [dartpad](https://dartpad.dartlang.org/)

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  const MyApp() : super(key: const Key('MyApp'));

  @override
  Widget build(BuildContext context) => MaterialApp(
        home: MyHomePage(),
      );
}

class MyHomePage extends StatelessWidget {
  const MyHomePage() : super(key: const Key('MyHomePage'));

  @override
  Widget build(BuildContext context) => Scaffold(
        body: Builder(
          builder: (context) => SingleChildScrollView(
            scrollDirection: Axis.horizontal,
            child: SizedBox(
              width: MediaQuery.of(context).size.width,
              height: MediaQuery.of(context).size.height,
              child: RefreshIndicator(
                onRefresh: () => Future.delayed(
                  Duration(seconds: 2),
                  () => Scaffold.of(context).showBottomSheet(
                    (context) => Container(
                      height: 200,
                      width: MediaQuery.of(context).size.width,
                      color: Colors.black12,
                      child: const Center(
                        child: Text('refreshing', textScaleFactor: 1.5),
                      ),
                    ),
                  ),
                ),
                child: ListView.builder(
                  itemBuilder: (context, i) => ListTile(
                    title: Text("Item $i"),
                  ),
                ),
              ),
            ),
          ),
        ),
      );
}
```

</details>

**Comment by iapicca** [comment] 2020-10-31 21:18
I see an interesting behavior
setting the `width` larger then the `MediaQuery.of(context).size.width`
the refresh indicator works, but without showing the `refresh icon`

try copy/pasting the code below on [dartpad](https://dartpad.dartlang.org/) and just swipe down

<details>
<summary>code sampel</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp() : super(key: const Key('MyApp'));

  @override
  Widget build(BuildContext context) => MaterialApp(
        home: MyHomePage(),
      );
}

class MyHomePage extends StatelessWidget {
  const MyHomePage() : super(key: const Key('MyHomePage'));

  @override
  Widget build(BuildContext context) => Scaffold(
        body: Builder(
          builder: (context) => SingleChildScrollView(
            scrollDirection: Axis.horizontal,
            child: SizedBox(
              width: MediaQuery.of(context).size.width * 2,
              height: MediaQuery.of(context).size.height,
              child: RefreshIndicator(
                onRefresh: () async => Scaffold.of(context).showBottomSheet(
                  (context) => Container(
                    height: 200,
                    width: MediaQuery.of(context).size.width,
                    color: Colors.black12,
                    child: const Center(
                      child: Text('refreshing', textScaleFactor: 1.5),
                    ),
                  ),
                ),
                child: ListView.builder(
                  itemBuilder: (context, i) => ListTile(
                    title: Text("Item $i"),
                  ),
                ),
              ),
            ),
          ),
        ),
      );
}
```

</details>

**Comment by ibyet05** [comment] 2020-11-01 05:09
Hi @renanzdm,

Now It makes sense.  But unfortunately, I need to use sizedbox because rows should be longer than screen size.
And there are also other widgets above the listbox in my application, they have to also scroll horizontally together with the listbox.  So I think I need to use another solution instead of RefreshIndicator. 


> I copied your code and it worked here, but the problem is that you defined the width of your sizedBox in 2000 so the refresh appears only in the middle of the screen. To solve it just put the width as MediaQuery.of (context) .size.width;
> Doing this will solve your problem
> 
> return Scaffold(
> body: SafeArea(
> child: SingleChildScrollView(
> scrollDirection: Axis.horizontal,
> child: SizedBox(
> width: 2000,
> height: sizes.height,
> child: RefreshIndicator(
> onRefresh: () {
> return Future.delayed(Duration(seconds: 2));
> },
> child: ListView.builder(
> itemCount: 100,
> physics: const AlwaysScrollableScrollPhysics(),
> itemBuilder: (context, i) => ListTile(
> title: Text("Text $i"),
> ),
> ),
> ),
> )),
> ),
> );

**Comment by renanzdm** [comment] 2020-11-01 09:18
I understand, in several ways to do this, but it was not a mistake.
But I didn’t see the sense of having lines larger than the screen size, and it will not appear

**Comment by iapicca** [comment] 2020-11-01 12:41
> I understand, in several ways to do this, but it was not a mistake.
> But I didn’t see the sense of having lines larger than the screen size, and it will not appear

I kind-of-agree with you, 
but you have to admit that it's unusual that the `callback` works and the `icon` doesn't...
also in case it isn't supposed to work, those restriction should be explicitly documented

**Comment by ibyet05** [comment] 2020-11-01 13:47
> But I didn’t see the sense of having lines larger than the screen size, and it will not appear
Long lines will appear, when you scroll horizontally. this why I use SingleChildScrollView as parent.

**Comment by renanzdm** [comment] 2020-11-01 14:06
got it but but and unusual behavior

**Comment by iapicca** [comment] 2020-11-01 18:33
@ibyet05 @renanzdm My apologize
please ignore my previous [comment](https://github.com/flutter/flutter/issues/69468#issuecomment-719989599)
the code posted in that comment actually works as intended, the refresh icon is not visible because the width I set
please run the fixed code below

<details>
<summary>new 'code sample</summary>

```dart

import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp() : super(key: const Key('MyApp'));

  @override
  Widget build(BuildContext context) => const MaterialApp(
        home: MyHomePage(),
      );
}

class MyHomePage extends StatelessWidget {
  const MyHomePage() : super(key: const Key('MyHomePage'));

  @override
  Widget build(BuildContext context) => Scaffold(
        body: Builder(
          builder: (context) => SingleChildScrollView(
            scrollDirection: Axis.horizontal,
            child: SizedBox(
              width: MediaQuery.of(context).size.width * 1.1,
              height: MediaQuery.of(context).size.height,
              child: RefreshIndicator(
                onRefresh: () async => Scaffold.of(context).showBottomSheet(
                  (context) => Container(
                    height: 200,
                    width: MediaQuery.of(context).size.width,
                    color: Colors.black12,
                    child: const Center(
                      child: Text('refreshing', textScaleFactor: 1.5),
                    ),
                  ),
                ),
                child: ListView.builder(
                  itemBuilder: (context, i) => ListTile(
                    title: Text("Item $i"),
                  ),
                ),
              ),
            ),
          ),
        ),
      );
}

```

everything works just fine, my bad
I recommend to close this issue

**Comment by darshankawar** [comment] 2020-11-02 10:20
Closing this issue as resolved per @iapicca's comment and updated code sample. 
@ibyet05 If you disagree, write in comments and I'll reopen.
Thanks.

**Closed by darshankawar** 2020-11-02 10:20 UTC
