### ISSUE TITLE
flutter all pictures turn pink

### ISSUE THREAD

**Issue by WuKong94** [flutter/flutter#114594] opened 2022-11-03 10:02 UTC
### Problem description

Occasionally, it will appear after entering the foreground from the background, and all the pictures will turn purple. After restarting the APP, the pictures will load normally,

I see similar questions being asked [64558](https://github.com/flutter/flutter/issues/64558)  [71074](https://github.com/flutter/flutter/issues/71074) 

It seems to have been fixed in version [2.2.0](https://github.com/flutter/flutter/commit/4266d629c26213ac5cd3f51c875f84e408d33a14), but I still have this problem in version 3.0.0

@gaaclarke 

Expected results:

The picture is displayed normally.
Actual results:

![image](https://user-images.githubusercontent.com/16898532/199692094-604ed28d-ef4e-4d6a-9e19-f6e9461d3df4.png)

Development environment
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.0, on macOS 12.3.1 21E258 darwin-x64, locale
zh-Hans-CN)
Checking Android licenses is taking an unexpectedly long time...[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.69.2)
[✓] Connected device (3 available)
! Error: 孙武东 is not connected. Xcode will continue when 孙武东 is connected.
(code -13)
[✓] HTTP Host Availability

• No issues found!

code desc
I am sorry that I cannot provide the code because It's hard for him to reproduce

**Comment by WuKong94** [comment] 2022-11-07 02:09
> Hello @WuKong94. I can see you're using an older version of Flutter (3.0.0). Can you confirm if this issue is still reproducible on the latest 3.3.7 stable version, if possible?
> 
> Edit: Can you try enabling [Fast App Termination](https://stackoverflow.com/questions/14969396/how-can-i-simulate-app-being-killed-in-background/14969498#14969498) to see if this issue is reproducible then? Also, if possible, can you provide a code snippet of how you're loading the images and/or the image source URLs?


Thank you for your answer,I upgraded to the latest 3.3.7 version, but the problem still occurs,

**Comment by exaby73** [comment] 2022-11-07 08:16
> Edit: Can you try enabling [Fast App Termination](https://stackoverflow.com/questions/14969396/how-can-i-simulate-app-being-killed-in-background/14969498#14969498) to see if this issue is reproducible then? Also, if possible, can you provide a code snippet of how you're loading the images and/or the image source URLs?

Have you tried this step?

**Comment by WuKong94** [comment] 2022-11-08 02:13
> 

I tried, but it seems that this kind of problem only occurs in release mode, so I can't test it in this way.

**Comment by exaby73** [comment] 2022-11-08 07:55
@WuKong94, there isn't enough information to go on here. I understand the issue occurs on release mode only on specific devices, but that isn't enough information for the team to investigate. I have asked for source URLs for images or code snippets or to test Fast App Termination if that changes the result, for a [complete and minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) so that we can try to reproduce it, but this is all information you can't seem to give.

Without more information, this issue is unactionable since we wouldn't know where to look for this bug as we don't have a way to reproduce it, neither do we understand what causes it. Please provide any information on this issue that would help in moving it forward else, like https://github.com/flutter/flutter/issues/109827, this issue too will be closed.

**Comment by WuKong94** [comment] 2022-11-09 01:57
@exaby73 Ok, I tried to provide the minimal example, but it doesn't seem to appear, I will continue to try and provide it as soon as it can be reproduced

**Comment by exaby73** [comment] 2022-11-09 07:33
Thank you :)

**Closed** 2022-11-30 08:10 UTC
Labels: waiting for customer response, in triage
