### ISSUE TITLE
[tool_crash] ArgumentError: Invalid argument(s): Cannot find executable for C:\xx\flutter\bin\cache\artifacts\engine\android-arm-profile\windows-x64\gen_snapshot.

### ISSUE THREAD

**Issue by benedicte69** [flutter/flutter#71371] opened 2020-11-29 11:24 UTC
## Command
```
flutter --quiet assemble --depfile C:\xxxx\flutter\profile/flutter_build.d --output C:\xxxx\build\app\intermediates\flutter\profile -dTargetFile=lib/main.dart -dTargetPlatform=android -dBuildMode=profile -dTrackWidgetCreation=true android_aot_bundle_profile_android-arm android_aot_bundle_profile_android-arm64 android_aot_bundle_profile_android-x64
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ArgumentError: Invalid argument(s): Cannot find executable for C:\xxxx\flutter\bin\cache\artifacts\engine\android-arm-profile\windows-x64\gen_snapshot.
```
#0      _getExecutable (package:process/src/interface/local_process_manager.dart:124:5)
#1      LocalProcessManager.start (package:process/src/interface/local_process_manager.dart:40:30)
#2      ErrorHandlingProcessManager.start.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:627:33)
#3      _run (package:flutter_tools/src/base/error_handling_io.dart:521:20)
#4      ErrorHandlingProcessManager.start (package:flutter_tools/src/base/error_handling_io.dart:627:12)
#5      _DefaultProcessUtils.start (package:flutter_tools/src/base/process.dart:472:28)
#6      _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart:491:35)
#7      GenSnapshot.run (package:flutter_tools/src/base/build.dart:73:26)
#8      AOTSnapshotter.build (package:flutter_tools/src/base/build.dart:196:56)
#9      AndroidAot.build (package:flutter_tools/src/build_system/targets/android.dart:232:52)
#10     _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:796:27)
<asynchronous suspension>
#11     Future.wait.<anonymous closure> (dart:async/future.dart)
<asynchronous suspension>
#12     _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:734:32)
<asynchronous suspension>
#13     Future.wait.<anonymous closure> (dart:async/future.dart)
<asynchronous suspension>
#14     _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:734:32)
<asynchronous suspension>
#15     FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:563:16)
<asynchronous suspension>
#16     AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:220:32)
<asynchronous suspension>
#17     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1119:12)
```
```
[✓] Flutter (Channel master, 1.24.0-8.0.pre.374, on Microsoft Windows [version 10.0.19042.630], locale fr-FR)
    • Flutter version 1.24.0-8.0.pre.374 at C:xxxx\flutter
    • Framework revision 183f0e797a (3 days ago), 2020-11-26 19:12:28 +0100
    • Engine revision 20caf54969
    • Dart version 2.12.0 (build 2.12.0-76.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\xxxx
    • Platform android-30, build-tools 30.0.2
    • ANDROID_SDK_ROOT = C:\xxxx
    • Java binary at: C:\xxxx\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.7)
    • Visual Studio at C:\xxxxCommunity
    • Visual Studio Community 2019 version 16.7.30621.155
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:xxxx
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] Connected device (4 available)
    • Windows (desktop) • windows    • windows-x64    • Microsoft Windows [version 10.0.19042.630]
    • Web Server (web)  • web-server • web-javascript • Flutter Tools
    • Chrome (web)      • chrome     • web-javascript • Google Chrome 87.0.4280.66
    • Edge (web)        • edge       • web-javascript • Microsoft Edge 87.0.664.47

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: master
**Creation framework version**: 05dadb0120b4aa3e5c0ccb1cf302632bf563d104

**Comment by iapicca** [comment] 2020-11-29 15:02
duplicate of https://github.com/flutter/flutter/issues/68475

**Comment by pedromassangocode** [comment] 2020-11-30 08:13
Closing as duplicate of https://github.com/flutter/flutter/issues/68475.

**Closed by pedromassangocode** 2020-11-30 08:13 UTC
