### ISSUE TITLE
exception during copy and paste in a multiline textfield

### ISSUE THREAD

**Issue by ride4sun** [flutter/flutter#14415] opened 2018-02-01 05:47 UTC
## Steps to Reproduce

I selected text in a multi line Text Field and tested copy and pasting text and I moved the selection handles than I got this exception:
Note: The textfield is in scrollView and grows when lines are added until it reaches maxheights. Than it starts scrolling.

```
 Scrollbar _renderInputField(BuildContext context) => new Scrollbar(
      child: new SingleChildScrollView(
          scrollDirection: Axis.vertical,
          reverse: true,
          child: new TextField(
              focusNode: _textFieldFocusNode,
              style: _appContext.customTheme.textInputStyle,
              autofocus: true,
              controller: _textController,
              autocorrect: true,
              onChanged: (text) {
                // The first future does not have the
                // updated height value of the text input field.
                // On the second one the size is
                // correctly updated. The height
                // is necessary to update the
                // scroll offset in the [ChatMessageListWidget]
                new Future.delayed(
                    const Duration(milliseconds: 60),
                    () => setState(() {
                          updateAppContext(context);
                        })).then((_) => new Future.delayed(
                    const Duration(milliseconds: 60),
                    () => setState(() {
                          updateAppContext(context);
                        })));
                groupController.messageComposeController.textChanged(text);
              },
              onSubmitted: _submitTextMessage,
              maxLines: null, //unlimited lines

              decoration: new InputDecoration.collapsed(
                  hintText:
                      /* _textFieldFocusNode.hasFocus
                      ? 'has focus'
                      : */
                      'Send a message',
                  hintStyle: _customTheme.textInputHintStyle))));
```

## Logs
```
[   +1 ms] W/IInputConnectionWrapper(23423): getTextAfterCursor on inactive InputConnection
[        ] W/IInputConnectionWrapper(23423): getSelectedText on inactive InputConnection
[        ] W/IInputConnectionWrapper(23423): endBatchEdit on inactive InputConnection
[  +35 ms] W/IInputConnectionWrapper(23423): getCursorCapsMode on inactive InputConnection
[        ] W/IInputConnectionWrapper(23423): beginBatchEdit on inactive InputConnection
[        ] W/IInputConnectionWrapper(23423): getTextBeforeCursor on inactive InputConnection
[        ] W/IInputConnectionWrapper(23423): getTextAfterCursor on inactive InputConnection
[        ] W/IInputConnectionWrapper(23423): getSelectedText on inactive InputConnection
[        ] W/IInputConnectionWrapper(23423): endBatchEdit on inactive InputConnection
[+17637 ms] W/IInputConnectionWrapper(23423): getCursorCapsMode on inactive InputConnection
[+6977 ms] W/IInputConnectionWrapper(23423): getCursorCapsMode on inactive InputConnection
[+7686 ms] W/IInputConnectionWrapper(23423): getCursorCapsMode on inactive InputConnection
[+18498 ms] W/IInputConnectionWrapper(23423): getCursorCapsMode on inactive InputConnection
[+30263 ms] I/flutter (23423): 1973 2018-01-31 21:40:37.134404 SEVERE lookatmybaby_flutter.sentry_error_reporter: Context: building _OverlayEntry-[LabeledGlobalKey<_OverlayEntryState>#5b2d4](dirty, state: _OverlayEntryState#da995), library: widgets library
[        ] I/flutter (23423):     error: 'package:flutter/src/rendering/box.dart': Failed assertion: line 1457 pos 18: 'debugDoingThisResize || debugDoingThisLayout ||
[        ] I/flutter (23423):                  (RenderObject.debugActiveLayout == parent && _size._canBeUsedByParent)': is not true.
[ +624 ms] I/flutter (23423): #0      _AssertionError._doThrowNew (dart:core-patch/dart:core/errors_patch.dart:37)
[        ] I/flutter (23423): #1      _AssertionError._throwNew (dart:core-patch/dart:core/errors_patch.dart:33)
[        ] I/flutter (23423): #2      RenderBox.size.<anonymous closure> (package:flutter/src/rendering/box.dart:1457:18)
[        ] I/flutter (23423): #3      RenderBox.size (package:flutter/src/rendering/box.dart:1463:6)
[        ] I/flutter (23423): #4      RenderFractionalTranslation.applyPaintTransform (package:flutter/src/rendering/proxy_box.dart:2309:24)
[        ] I/flutter (23423): #5      RenderObject.getTransformTo (package:flutter/src/rendering/object.dart:2094:24)
[        ] I/flutter (23423): #6      RenderBox.localToGlobal (package:flutter/src/rendering/box.dart:1955:39)
[        ] I/flutter (23423): #7      TextSelectionOverlay._buildToolbar (package:flutter/src/widgets/text_selection.dart:365:20)
[        ] I/flutter (23423): #8      _OverlayEntryState.build (package:flutter/src/widgets/overlay.dart:170:25)
[        ] I/flutter (23423): #9      StatefulElement.build (package:flutter/src/widgets/framework.dart:3690:27)
[        ] I/flutter (23423): #10     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3602:15)
[        ] I/flutter (23423): #11     Element.rebuild (package:flutter/src/widgets/
[+3001 ms] I/flutter (23423): 1979 2018-01-31 21:40:40.763189 SEVERE lookatmybaby_flutter.sentry_error_reporter: Context: building _OverlayEntry-[LabeledGlobalKey<_OverlayEntryState>#5b2d4](dirty, state: _OverlayEntryState#da995), library: widgets library
[        ] I/flutter (23423):     error: 'package:flutter/src/rendering/box.dart': Failed assertion: line 1457 pos 18: 'debugDoingThisResize || debugDoingThisLayout ||
[        ] I/flutter (23423):                  (RenderObject.debugActiveLayout == parent && _size._canBeUsedByParent)': is not true.
[ +789 ms] I/flutter (23423): #0      _AssertionError._doThrowNew (dart:core-patch/dart:core/errors_patch.dart:37)
[        ] I/flutter (23423): #1      _AssertionError._throwNew (dart:core-patch/dart:core/errors_patch.dart:33)
[        ] I/flutter (23423): #2      RenderBox.size.<anonymous closure> (package:flutter/src/rendering/box.dart:1457:18)
[        ] I/flutter (23423): #3      RenderBox.size (package:flutter/src/rendering/box.dart:1463:6)
[        ] I/flutter (23423): #4      RenderFractionalTranslation.applyPaintTransform (package:flutter/src/rendering/proxy_box.dart:2309:24)
[        ] I/flutter (23423): #5      RenderObject.getTransformTo (package:flutter/src/rendering/object.dart:2094:24)
[        ] I/flutter (23423): #6      RenderBox.localToGlobal (package:flutter/src/rendering/box.dart:1955:39)
[        ] I/flutter (23423): #7      TextSelectionOverlay._buildToolbar (package:flutter/src/widgets/text_selection.dart:365:20)
[        ] I/flutter (23423): #8      _OverlayEntryState.build (package:flutter/src/widgets/overlay.dart:170:25)
[        ] I/flutter (23423): #9      StatefulElement.build (package:flutter/src/widgets/framework.dart:3690:27)
[        ] I/flutter (23423): #10     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3602:15)
[        ] I/flutter (23423): #11     Element.rebuild (package:flutter/src/widgets/
[ +795 ms] I/flutter (23423): 1982 2018-01-31 21:40:42.349744 SEVERE lookatmybaby_flutter.sentry_error_reporter: Context: during layout, library: rendering library
[        ] I/flutter (23423):     error: A RenderFlex overflowed by 128 pixels on the bottom.
```
## Flutter Doctor

I used the Moto5 G below

C:\Projects\lambDev\lookatmybaby_flutter>flutter doctor
[√] Flutter (on Microsoft Windows [Version 10.0.16299.192], locale en-US, channel dev)
    • Flutter version 0.0.21 at c:\sdks\flutter
    • Framework revision 2e449f06f0 (2 days ago), 2018-01-29 14:26:51 -0800
    • Engine revision 6921873c71
    • Tools Dart version 2.0.0-dev.16.0
    • Engine Dart version 2.0.0-edge.da1f52592ef73fe3afa485385cb995b9aec0181a

[√] Android toolchain - develop for Android devices (Android SDK 27.0.2)
    • Android SDK at C:\Users\ride4\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] Android Studio (version 3.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] IntelliJ IDEA Community Edition (version 2017.2)
    • Flutter plugin version 19.1
    • Dart plugin version 172.4343.25

[√] Connected devices
    • Moto G 5 Plus             • ZY224DHFWG    • android-arm • Android 7.0 (API 24)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 7.1.1 (API 25) (emulator)

**Comment by Hixie** [comment] 2018-05-29 16:41
Duplicate of https://github.com/flutter/flutter/issues/14489

**Closed by Hixie** 2018-05-29 16:41 UTC

**Comment by HanLinfeng** [comment] 2019-09-09 15:40
I have the same problem, which happens when I double-click or long-time.
My code snippet is as follows:
`
.....
ListView(
     children: <Widget>[
           Row(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: <Widget>[
            Text(
              label,
              style: TextStyle(
                fontSize: 14,
                color: Colors.black87,
              ),
            ),
            Container(
              width: 10,
            ),
            Expanded(
              child: CupertinoTextField(
                enableInteractiveSelection: true,
                controller: controller,
                keyboardType: keyboardType,
//                clearButtonMode: OverlayVisibilityMode.editing,
                cursorWidth: 1,
                inputFormatters: inputFormatters,
                maxLength: maxLength,
                maxLines: maxLines,
                placeholder: placeholder,
                padding: EdgeInsets.all(0),
                placeholderStyle: TextStyle(
                  fontSize: 14,
                  color: Colors.grey[400],
                ),
                style: TextStyle(
                  fontSize: 14,
                  color: Colors.black87,
                ),
                decoration: BoxDecoration(
                    border: Border.fromBorderSide(BorderSide.none)),
              ),
            ),
            null != right ? right : Container(),
          ],
        ),
     ],
)
...
`
The error information is as follows:
`════════ Exception Caught By rendering library ═════════════════════════════════════════════════════
The following assertion was thrown during performLayout():
'package:flutter/src/rendering/box.dart': Failed assertion: line 1694 pos 18: 'debugDoingThisResize || debugDoingThisLayout ||
                 (RenderObject.debugActiveLayout == parent && _size._canBeUsedByParent)': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

When the exception was thrown, this was the stack: 
#2      RenderBox.size.<anonymous closure> (package:flutter/src/rendering/box.dart:1694:18)
#3      RenderBox.size (package:flutter/src/rendering/box.dart:1700:6)
#4      RenderFractionalTranslation.applyPaintTransform (package:flutter/src/rendering/proxy_box.dart:2425:24)
#5      RenderObject.getTransformTo (package:flutter/src/rendering/object.dart:2167:24)
#6      RenderBox.globalToLocal (package:flutter/src/rendering/box.dart:2244:31)
...
The following RenderObject was being processed when the exception was fired: _ToolbarRenderBox#7805e NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...  needs compositing
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(w=375.0, h=812.0)
...  size: Size(375.0, 812.0)
RenderObject: _ToolbarRenderBox#7805e NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
  needs compositing
  parentData: <none> (can use size)
  constraints: BoxConstraints(w=375.0, h=812.0)
  size: Size(375.0, 812.0)
...  child: RenderDecoratedBox#d6da3 relayoutBoundary=up1 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...    parentData: offset=Offset(0.0, 0.0), arrowXOffsetFromCenter=null (can use size)
...    constraints: BoxConstraints(0.0<=w<=359.0, h=43.0)
...    size: Size(73.0, 43.0)
...    decoration: BoxDecoration
...      color: Color(0xff808080)
...    configuration: ImageConfiguration(bundle: PlatformAssetBundle#36037(), devicePixelRatio: 3.0, locale: en_US, textDirection: TextDirection.ltr, platform: iOS)
...    child: RenderFlex#91472 relayoutBoundary=up2 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...      parentData: <none> (can use size)
...      constraints: BoxConstraints(0.0<=w<=359.0, h=43.0)
...      size: Size(73.0, 43.0)
...      direction: horizontal
...      mainAxisAlignment: start
...      mainAxisSize: min
...      crossAxisAlignment: center
...      textDirection: ltr
...      verticalDirection: down
...      child 1: RenderSemanticsGestureHandler#cc688 relayoutBoundary=up3 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...        parentData: offset=Offset(0.0, 0.0); flex=null; fit=null (can use size)
...        constraints: BoxConstraints(0.0<=w<=Infinity, 0.0<=h<=43.0)
...        size: Size(73.0, 43.0)
...        gestures: tap
...        child: RenderPointerListener#a7053 relayoutBoundary=up4 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(0.0<=w<=Infinity, 0.0<=h<=43.0)
...          size: Size(73.0, 43.0)
...          behavior: opaque
...          listeners: down
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception Caught By rendering library ═════════════════════════════════════════════════════
The following NoSuchMethodError was thrown during paint():
The method 'toDouble' was called on null.
Receiver: null
Tried calling: toDouble()
When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
#1      double.+ (dart:core-patch/double.dart:17:23)
#2      _ToolbarRenderBox._clipPath (package:flutter/src/cupertino/text_selection.dart:190:51)
#3      _ToolbarRenderBox.paint (package:flutter/src/cupertino/text_selection.dart:218:7)
#4      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2089:7)
...
The following RenderObject was being processed when the exception was fired: _ToolbarRenderBox#7805e
...  needs compositing
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(w=375.0, h=812.0)
...  layer: OffsetLayer#4670f DETACHED
...    offset: Offset(0.0, 0.0)
...  size: Size(375.0, 812.0)
RenderObject: _ToolbarRenderBox#7805e
  needs compositing
  parentData: <none> (can use size)
  constraints: BoxConstraints(w=375.0, h=812.0)
  layer: OffsetLayer#4670f DETACHED
    offset: Offset(0.0, 0.0)
  size: Size(375.0, 812.0)
...  child: RenderDecoratedBox#d6da3 relayoutBoundary=up1 NEEDS-PAINT
...    parentData: offset=Offset(0.0, 0.0), arrowXOffsetFromCenter=null (can use size)
...    constraints: BoxConstraints(0.0<=w<=359.0, h=43.0)
...    size: Size(73.0, 43.0)
...    decoration: BoxDecoration
...      color: Color(0xff808080)
...    configuration: ImageConfiguration(bundle: PlatformAssetBundle#36037(), devicePixelRatio: 3.0, locale: en_US, textDirection: TextDirection.ltr, platform: iOS)
...    child: RenderFlex#91472 relayoutBoundary=up2 NEEDS-PAINT
...      parentData: <none> (can use size)
...      constraints: BoxConstraints(0.0<=w<=359.0, h=43.0)
...      size: Size(73.0, 43.0)
...      direction: horizontal
...      mainAxisAlignment: start
...      mainAxisSize: min
...      crossAxisAlignment: center
...      textDirection: ltr
...      verticalDirection: down
...      child 1: RenderSemanticsGestureHandler#cc688 relayoutBoundary=up3 NEEDS-PAINT
...        parentData: offset=Offset(0.0, 0.0); flex=null; fit=null (can use size)
...        constraints: BoxConstraints(0.0<=w<=Infinity, 0.0<=h<=43.0)
...        size: Size(73.0, 43.0)
...        gestures: tap
...        child: RenderPointerListener#a7053 relayoutBoundary=up4 NEEDS-PAINT
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(0.0<=w<=Infinity, 0.0<=h<=43.0)
...          size: Size(73.0, 43.0)
...          behavior: opaque
...          listeners: down
════════════════════════════════════════════════════════════════════════════════════════════════════`
