### ISSUE TITLE
extendBodyBehindAppBar parameter set as true in scaffold causes body of scaffold to build twice

### ISSUE THREAD

**Issue by ammarhemani** [flutter/flutter#56226] opened 2020-05-03 04:26 UTC
## Sample code to Reproduce

```
class HomeScreen extends StatefulWidget {
  @override
  _HomeScreenState createState() => _HomeScreenState();
}

class _HomeScreenState extends State<HomeScreen> {
  @override
  Widget build(BuildContext context) {
    print('home screen built');
    return Scaffold(
      extendBodyBehindAppBar: true,
      body: SampleWidget(),
    );
  }
}

class SampleWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    print('sample widget built');
    return Container();
  }
}

```

SampleWidget in the above code is being built twice when the extendBodyBehindAppBar parameter in the scaffold is set to true.

When extendBodyBehindAppBar is set to false, everything seems normal and only built once.

 • Flutter version 1.18.0-9.0.pre.38 (channel master)
• Dart version 2.9.0 (build 2.9.0-3.0.dev a69cb6d700)

**Comment by jonahwilliams** [comment] 2020-05-03 04:47
This is because `extendBodyBehindAppBar ` is implemented with a LayoutBuilder:

https://github.com/flutter/flutter/blob/fc7ce3eeb6ce7038042a711f6c32ebf5b2dfbaa5/packages/flutter/lib/src/material/scaffold.dart#L360

And this will often require two builds. I wonder if this will change when https://github.com/flutter/flutter/pull/55414 is fixed

**Comment by ammarhemani** [comment] 2020-05-03 04:51
I'm using the extendBodyBehindAppBar parameter in my entire application (20+ screens). Do you think this will affect performance?

**Comment by jonahwilliams** [comment] 2020-05-03 04:52
Rebuilding doesn't necessarily mean re-layout or re-painting. Do you notice any slowness or stuttering in release mode? If not I wouldn't worry about it too much.

**Comment by yjbanov** [comment] 2020-05-04 18:03
I'm going to assign for myself for re-triage. I'll check if the `LayoutBuilder` fix also fixes this.

**Comment by yjbanov** [comment] 2020-05-08 22:12
I'm unable to reproduce the issue with or without the `LayoutBuilder` optimization. I only see "home screen built" and "sample widget built" messages once. @ammarhemani Could you please try again on the latest master and confirm it's still an issue?

**Comment by yjbanov** [comment] 2020-05-18 21:36
Closing since I'm unable to reproduce, but feel free to reopen if this is happening again.

**Closed by yjbanov** 2020-05-18 21:36 UTC
Labels: assigned for triage, f: material design, framework, waiting for customer response

**Comment by spitfire55** [comment] 2020-09-05 16:54
Having this issue with my application. I'm using an IndexedStack w/ BottomNavBar. One of the 3 IndexedStack children uses the `extendBodyBehindAppBar` property. When I navigate to that screen, the toggling of the `extendBodyBehindAppBar` causes a rebuild of all three IndexedStack children. This breaks the desired behavior of building the IndexedStack once, and then navigating to each child w/o having to rebuild each child when the index is changed via `SetState`.

Example code below to reproduce. Notice that navigating between Screen 1 and Screen 3 does not trigger the rebuild of the IndexedStack children, while navigating between Screen 1 and 2, or 2 and 3, causes a rebuild of all 3 children in the IndexedStack. Commenting out `extendBodyBehindAppBar` fixes the issue and will have the IndexedStack work as intended.
```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: HomePage(),
    );
  }
}

class HomePage extends StatefulWidget {
  @override
  State<StatefulWidget> createState() => HomePageState();
}

class HomePageState extends State<HomePage> {
  int _currentIndex = 0;
  List<Widget> _bodyChildren;

  @override
  void initState() {
    super.initState();
    _bodyChildren = [
      ScreenOne(),
      ScreenTwo(),
      ScreenThree(),
    ];
  }

  @override
  Widget build(BuildContext context) {

    return Scaffold(
      appBar: buildAppBar(),
      body: IndexedStack(
        index: _currentIndex,
        children: _bodyChildren,
      ),
      bottomNavigationBar: BottomNavigationBar(
        currentIndex: _currentIndex,
        items: buildBottomNavBarItems(),
        onTap: (index) {
          setState(() => _currentIndex = index);
        },
      ),
      extendBodyBehindAppBar: (_currentIndex == 1) ? true : false,
    );
  }

  List<BottomNavigationBarItem> buildBottomNavBarItems() {
    return [
      BottomNavigationBarItem(
        icon: Icon(Icons.list),
        title: Text("Screen 1"),
      ),
      BottomNavigationBarItem(
        icon: Icon(Icons.map),
        title: Text("Screen 2"),
      ),
      BottomNavigationBarItem(
        icon: Icon(Icons.person),
        title: Text("Screen 3"),
      )
    ];
  }

  Widget buildAppBar() {
    return AppBar(title: Text("App Bar"));
  }
}

class ScreenOne extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    print("BUILDING SCREEN ONE");
    return Container(color: Colors.red);
  }
}

class ScreenTwo extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    print("BUILDING SCREEN TWO");
    return Container(color: Colors.blue);
  }
}

class ScreenThree extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    print("BUILDING SCREEN THREE");
    return Container(color: Colors.green);
  }
}

```
