### ISSUE TITLE
[google_maps_flutter][Android] Quickly and repeatedly switching tabs, crash with java.lang.OutOfMemoryError.

### ISSUE THREAD

**Issue by st-flower** [flutter/flutter#112528] opened 2022-09-28 07:40 UTC
Hi.

My app uses DefaultTabController to display GoogleMap on each TabView. 
I kept switching tabs quickly and repeatedly, the app crashed in java.lang.OutOfMemoryError.  
If the contents of the tabview is an empty container, it will not crash.
So GoogleMap is definitely the cause of this.
This issue can occur on any version of the Android OS.

Perhaps it has something to do with the way https://github.com/flutter/flutter/issues/105965#issuecomment-1224473127 was handled...

## Steps to Reproduce

1. Execute `flutter run` on the code sample.
2. Switching tabs quickly and repeatedly.
3. App crashed in java.lang.OutOfMemoryError.  

**Expected results:** 
No java.lang.OutOfMemoryError.

**Actual results:** 
App has crashed.

<details>
<summary>flutter doctor</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.4 21F79 darwin-x64, locale ja-JP)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.71.1)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!
```

</details>

<details>
<summary>Code sample</summary>

## Add this line to your app's build.gradle ##
```
implementation 'com.google.android.gms:play-services-maps:18.0.2'
```

## MainActivity.kt ##
```
import android.os.Bundle
import io.flutter.embedding.android.FlutterActivity
import io.flutter.embedding.engine.FlutterEngine
import io.flutter.plugin.common.MethodChannel
import io.flutter.plugins.GeneratedPluginRegistrant
import io.flutter.view.FlutterMain
import android.os.Build;
import android.view.WindowManager
import android.util.Log;
import com.google.android.gms.maps.MapsInitializer
import com.google.android.gms.maps.MapsInitializer.Renderer
import com.google.android.gms.maps.OnMapsSdkInitializedCallback

class MainActivity: FlutterActivity(), OnMapsSdkInitializedCallback{
    override 
    fun onCreate(savedInstanceState: Bundle?){
        super.onCreate(savedInstanceState);
        MapsInitializer.initialize(applicationContext, Renderer.LATEST, this)
    }

    override fun onMapsSdkInitialized(renderer: MapsInitializer.Renderer) {
      when (renderer) {
        Renderer.LATEST -> Log.d("NewRendererLog", "The latest version of the renderer is used.")
        Renderer.LEGACY -> Log.d("NewRendererLog","The legacy version of the renderer is used.")
      }
    }
}
```

## main.dart ##
```
import 'dart:async';

import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';
import 'package:google_maps_flutter_android/google_maps_flutter_android.dart';
import 'package:google_maps_flutter_platform_interface/google_maps_flutter_platform_interface.dart';

void main() {
  final GoogleMapsFlutterPlatform mapsImplementation = GoogleMapsFlutterPlatform.instance;
  if (mapsImplementation is GoogleMapsFlutterAndroid) {
    mapsImplementation.useAndroidViewSurface = false;
  }

  return runApp(const App());
}

class App extends StatelessWidget {
  const App({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(primarySwatch: Colors.grey),
      home: DefaultTabController(
        length: 3,
        child: Scaffold(
          appBar: AppBar(
            title: const Text('GoogleMapSampleApp'),
            bottom: const TabBar(
              tabs: [
                Tab(child: Text('Tokyo')),
                Tab(child: Text('London')),
                Tab(child: Text('NewYork')),
              ],
            ),
          ),
          body: const TabBarView(
            children: [
              GoogleMapView.tokyo(),
              GoogleMapView.london(),
              GoogleMapView.newYork(),
            ],
          ),
        ),
      ),
    );
  }
}

class GoogleMapView extends StatefulWidget {
  const GoogleMapView.tokyo({Key? key})
      : _kGooglePlex = const CameraPosition(target: LatLng(35.652832, 139.839478), zoom: 14.4746),
        super(key: key);

  const GoogleMapView.london({Key? key})
      : _kGooglePlex = const CameraPosition(target: LatLng(51.509865, -0.118092), zoom: 14.4746),
        super(key: key);

  const GoogleMapView.newYork({Key? key})
      : _kGooglePlex = const CameraPosition(target: LatLng(40.730610, -73.935242), zoom: 14.4746),
        super(key: key);

  final CameraPosition _kGooglePlex;

  @override
  State<GoogleMapView> createState() => GoogleMapState();
}

class GoogleMapState extends State<GoogleMapView> {
  final Completer<GoogleMapController> _controller = Completer();

  @override
  Widget build(BuildContext context) {
    return GoogleMap(
      initialCameraPosition: widget._kGooglePlex,
      myLocationButtonEnabled: false,
      mapToolbarEnabled: false,
      zoomControlsEnabled: false,
      onMapCreated: (GoogleMapController controller) {
        _controller.complete(controller);
      },
    );
  }
}
```

</details>

<details>
 <summary>Logs</summary>

```
2022-09-28 15:22:10.248 9529-10135/ I/: Waiting for a blocking GC Alloc
2022-09-28 15:22:10.432 9529-9551/ I/: Clamp target GC heap from 350MB to 256MB
2022-09-28 15:22:10.432 9529-9551/ I/: Alloc concurrent copying GC freed 5357(1301KB) AllocSpace objects, 0(0B) LOS objects, 0% free, 254MB/256MB, paused 73us,139us total 529.616ms
2022-09-28 15:22:10.432 9529-9551/ W/: Throwing OutOfMemoryError "Failed to allocate a 16 byte allocation with 1332328 free bytes and 1301KB until OOM, target footprint 268435456, growth limit 268435456; giving up on allocation because <1% of heap free after GC." (VmSize 25058592 kB)
2022-09-28 15:22:10.432 9529-9551/ E/JavaBinder: *** Uncaught remote exception!  (Exceptions are not yet supported across processes.)
    java.lang.OutOfMemoryError: Failed to allocate a 16 byte allocation with 1332328 free bytes and 1301KB until OOM, target footprint 268435456, growth limit 268435456; giving up on allocation because <1% of heap free after GC.
        at android.os.ThreadLocalWorkSource.setUid(ThreadLocalWorkSource.java:68)
        at android.os.Binder.execTransact(Binder.java:1242)
2022-09-28 15:22:10.432 9529-9919/ I/: WaitForGcToComplete blocked Alloc on Alloc for 1.188s
2022-09-28 15:22:10.432 9529-9919/ I/: Starting a blocking GC Alloc
2022-09-28 15:22:10.433 9529-9665/ I/: WaitForGcToComplete blocked Alloc on Alloc for 667.155ms
2022-09-28 15:22:10.433 9529-9665/ I/: Starting a blocking GC Alloc
2022-09-28 15:22:10.433 9529-9662/ I/: WaitForGcToComplete blocked Alloc on Alloc for 667.782ms
2022-09-28 15:22:10.433 9529-9662/ I/: Starting a blocking GC Alloc
2022-09-28 15:22:10.434 9529-9666/ I/: WaitForGcToComplete blocked Alloc on Alloc for 667.147ms
2022-09-28 15:22:10.434 9529-9666/ I/: Starting a blocking GC Alloc
2022-09-28 15:22:10.434 9529-9661/ I/: WaitForGcToComplete blocked Alloc on Alloc for 667.488ms
2022-09-28 15:22:10.434 9529-9661/ I/: Starting a blocking GC Alloc
2022-09-28 15:22:10.434 9529-9667/ I/: WaitForGcToComplete blocked Alloc on Alloc for 667.373ms
2022-09-28 15:22:10.434 9529-9667/ I/: Starting a blocking GC Alloc
2022-09-28 15:22:10.434 9529-9670/ I/: WaitForGcToComplete blocked Alloc on Alloc for 532.269ms
2022-09-28 15:22:10.435 9529-9670/ I/: Starting a blocking GC Alloc
2022-09-28 15:22:10.435 9529-9529/ I/: WaitForGcToComplete blocked Alloc on Alloc for 532.528ms
2022-09-28 15:22:10.435 9529-9529/ I/: Starting a blocking GC Alloc
2022-09-28 15:22:10.435 9529-9660/ I/: WaitForGcToComplete blocked Alloc on Alloc for 532.547ms
2022-09-28 15:22:10.435 9529-9660/ I/: Starting a blocking GC Alloc
2022-09-28 15:22:10.435 9529-10631/ I/: WaitForGcToComplete blocked Alloc on Alloc for 532.677ms
2022-09-28 15:22:10.435 9529-10631/ I/: Starting a blocking GC Alloc
2022-09-28 15:22:10.436 9529-10498/ I/: Waiting for a blocking GC Alloc
2022-09-28 15:22:10.436 9529-9529/ I/Choreographer: Skipped 166 frames!  The application may be doing too much work on its main thread.
2022-09-28 15:22:10.436 9529-9632/ I/: Waiting for a blocking GC Alloc
2022-09-28 15:22:10.436 9529-10630/ I/: Waiting for a blocking GC Alloc
2022-09-28 15:22:10.437 9529-9841/ I/: Waiting for a blocking GC Alloc
2022-09-28 15:22:10.437 9529-9550/ I/: Waiting for a blocking GC Alloc
2022-09-28 15:22:10.437 9529-10116/ I/: Waiting for a blocking GC Alloc
2022-09-28 15:22:10.437 9529-10126/ I/: Waiting for a blocking GC Alloc
2022-09-28 15:22:10.438 9529-10135/ I/: Waiting for a blocking GC Alloc
2022-09-28 15:22:10.438 2000-2795/? W/ActivityTaskManager:   Force finishing activity /.MainActivity
2022-09-28 15:22:10.438 2000-10637/? I/DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
2022-09-28 15:22:10.460 9529-9670/ I/Process: Sending signal. PID: 9529 SIG: 9
2022-09-28 15:22:10.461 2000-2342/? W/BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver
2022-09-28 15:22:10.461 2000-2342/? W/BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver
2022-09-28 15:22:10.492 3724-4458/? I/AssistantForeground: Get launcher package: com.google.android.apps.nexuslauncher
2022-09-28 15:22:10.535 2000-2795/? I/DropBoxManagerService: add tag=platform_stats_bookmark isTagEnabled=true flags=0x2
2022-09-28 15:22:10.537 2000-2342/? W/BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver
2022-09-28 15:22:10.537 2000-2342/? W/BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver
2022-09-28 15:22:10.538 1196-1196/? I/Zygote: Process 9529 exited due to signal 9 (Killed)
2022-09-28 15:22:10.538 2000-2045/? D/ConnectivityService: ConnectivityService NetworkRequestInfo binderDied(uid/pid:10293/9529, [NetworkRequest [ REQUEST id=4180, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VCN_MANAGED Uid: 10293 RequestorUid: 10293 RequestorPkg:  UnderlyingNetworks: Null] ]], android.os.BinderProxy@9dce39)
2022-09-28 15:22:10.539 2000-2597/? D/ConnectivityService: releasing NetworkRequest [ REQUEST id=4180, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VCN_MANAGED Uid: 10293 RequestorUid: 10293 RequestorPkg:  UnderlyingNetworks: Null] ] (release request)
2022-09-28 15:22:10.539 2000-4024/? I/ActivityManager: Process  (pid 9529) has died: prcp TOP 
2022-09-28 15:22:10.539 2000-3816/? I/WindowManager: WIN DEATH: Window{d28362e u0 /.MainActivity}
2022-09-28 15:22:10.539 2000-3816/? W/InputManager-JNI: Input channel object 'd28362e /.MainActivity (client)' was disposed without first being removed with the input manager!
2022-09-28 15:22:10.547 2000-2374/? I/libprocessgroup: Successfully killed process cgroup uid 10293 pid 9529 in 0ms
2022-09-28 15:22:10.556 3193-3350/? D/QuickstepModelDelegate: notifyAppTargetEvent action=1 launchLocation=
2022-09-28 15:22:10.568 3724-4464/? I/AssistantForeground: Get launcher package: com.google.android.apps.nexuslauncher
2022-09-28 15:22:10.574 5062-5062/? I/A: onApplyWindowInsets: systemWindowInsets=Insets{left=0, top=136, right=0, bottom=66}
2022-09-28 15:22:10.574 5062-5062/? I/A: onApplyWindowInsets: systemWindowInsets=Insets{left=0, top=136, right=0, bottom=66}
2022-09-28 15:22:10.584 2000-2325/? W/WindowManager: Failed to deliver inset state change to w=Window{d28362e u0 /.MainActivity EXITING}
    android.os.DeadObjectException
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(BinderProxy.java:584)
        at android.view.IWindow$Stub$Proxy.insetsControlChanged(IWindow.java:473)
        at com.android.server.wm.WindowState.notifyInsetsControlChanged(WindowState.java:3994)
        at com.android.server.wm.InsetsStateController.lambda$notifyPendingInsetsControlChanged$5(InsetsStateController.java:348)
        at com.android.server.wm.InsetsStateController.$r8$lambda$ni7v3ZO6TRbLZqXOFahDjPeXTS0(Unknown Source:0)
        at com.android.server.wm.InsetsStateController$$ExternalSyntheticLambda4.run(Unknown Source:2)
        at com.android.server.wm.WindowAnimator.executeAfterPrepareSurfacesRunnables(WindowAnimator.java:345)
        at com.android.server.wm.WindowAnimator.animate(WindowAnimator.java:226)
        at com.android.server.wm.WindowAnimator.lambda$new$1(WindowAnimator.java:106)
        at com.android.server.wm.WindowAnimator.$r8$lambda$fo2Nk5bb9hY3lvmHsTnTEwtZMbI(Unknown Source:0)
        at com.android.server.wm.WindowAnimator$$ExternalSyntheticLambda1.doFrame(Unknown Source:2)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1229)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
        at android.view.Choreographer.doCallbacks(Choreographer.java:899)
        at android.view.Choreographer.doFrame(Choreographer.java:827)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
        at android.os.Handler.handleCallback(Handler.java:942)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.os.HandlerThread.run(HandlerThread.java:67)
        at com.android.server.ServiceThread.run(ServiceThread.java:44)
2022-09-28 15:22:10.587 3724-3724/? I/GsaVoiceInteractionSrv: Handling ACTION_START_HOTWORD
2022-09-28 15:22:10.588 3724-4444/? I/GsaVoiceInteractionSrv: disregardVoiceMatch: false
2022-09-28 15:22:10.588 3724-4444/? I/GsaVoiceInteractionSrv: Cannot start hotword, hotword has been explicitly disabled.
2022-09-28 15:22:10.600 2000-2325/? W/WindowManager: Exception thrown during dispatchAppVisibility Window{d28362e u0 /.MainActivity EXITING}
    android.os.DeadObjectException
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(BinderProxy.java:584)
        at android.view.IWindow$Stub$Proxy.dispatchAppVisibility(IWindow.java:536)
        at com.android.server.wm.WindowState.sendAppVisibilityToClients(WindowState.java:3489)
        at com.android.server.wm.WindowContainer.sendAppVisibilityToClients(WindowContainer.java:1199)
        at com.android.server.wm.WindowToken.setClientVisible(WindowToken.java:398)
        at com.android.server.wm.ActivityRecord.setClientVisible(ActivityRecord.java:6564)
        at com.android.server.wm.ActivityRecord.onAnimationFinished(ActivityRecord.java:7351)
        at com.android.server.wm.ActivityRecord.postApplyAnimation(ActivityRecord.java:5263)
        at com.android.server.wm.ActivityRecord.commitVisibility(ActivityRecord.java:5235)
        at com.android.server.wm.ActivityRecord.commitVisibility(ActivityRecord.java:5239)
        at com.android.server.wm.AppTransitionController.handleClosingApps(AppTransitionController.java:1098)
        at com.android.server.wm.AppTransitionController.handleAppTransitionReady(AppTransitionController.java:286)
        at com.android.server.wm.RootWindowContainer.checkAppTransitionReady(RootWindowContainer.java:975)
        at com.android.server.wm.RootWindowContainer.performSurfacePlacementNoTrace(RootWindowContainer.java:842)
        at com.android.server.wm.RootWindowContainer.performSurfacePlacement(RootWindowContainer.java:784)
        at com.android.server.wm.WindowSurfacePlacer.performSurfacePlacementLoop(WindowSurfacePlacer.java:177)
        at com.android.server.wm.WindowSurfacePlacer.performSurfacePlacement(WindowSurfacePlacer.java:126)
        at com.android.server.wm.WindowSurfacePlacer.performSurfacePlacement(WindowSurfacePlacer.java:115)
        at com.android.server.wm.WindowSurfacePlacer$Traverser.run(WindowSurfacePlacer.java:57)
        at android.os.Handler.handleCallback(Handler.java:942)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.os.HandlerThread.run(HandlerThread.java:67)
        at com.android.server.ServiceThread.run(ServiceThread.java:44)
2022-09-28 15:22:10.605 2000-2324/? W/ActivityManager: setHasOverlayUi called on unknown pid: 9529
2022-09-28 15:22:10.607 2848-2848/? I/WallpaperService: engine resumed
2022-09-28 15:22:10.609 1241-1241/? I/sensors-hal: [hal]batch_physical_sensor:314, android.sensor.gyroscope/41, period=20000000, max_latency=0
2022-09-28 15:22:10.609 1241-1241/? I/sensors-hal: [sensor]set_config:64, sample_period_ns is adjusted to 20000000 based on min/max delay_ns
2022-09-28 15:22:10.609 1241-1241/? I/sensors-hal: [hal]batch_physical_sensor:323, android.sensor.gyroscope/41, period=20000000, max_latency=0 request completed
2022-09-28 15:22:10.610 1241-1241/? I/sensors-hal: [hal]activate_physical_sensor:251, android.sensor.gyroscope/41 en=1
2022-09-28 15:22:10.610 1241-1241/? I/sensors-hal: [ssc_utils]get_qmi_debug_flag:243, support_qmi_debug : false
2022-09-28 15:22:10.613 3704-4086/? I/AiAiEcho: Predicting[0]: 
2022-09-28 15:22:10.613 3704-4086/? I/AiAiEcho: Ranked targets strategy: WEIGHTED, count: 0, ranking metadata: 
2022-09-28 15:22:10.613 653-653/? E/ClientCache: failed to get buffer, invalid process token
2022-09-28 15:22:10.615 653-653/? E/BpTransactionCompletedListener: Failed to transact (-32)

```

</details>

**Comment by danagbemava-nc** [comment] 2022-09-28 10:38
The issue is reproducible using the code sample provided above and steps provided above.

Labeling for further investigation. 

[crash.log](https://github.com/flutter/flutter/files/9664080/crash.log)


<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.3.2, on macOS 12.6 21G115 darwin-arm, locale en-GB)
    • Flutter version 3.3.2 on channel stable at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e3c29ec00c (2 weeks ago), 2022-09-14 08:46:55 -0500
    • Engine revision a4ff2c53d8
    • Dart version 2.18.1
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/213.7172.25.2113.9014738/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A309
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] Android Studio (version 2021.3)
    • Android Studio at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/213.7172.25.2113.9014738/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] Android Studio (version 2021.2)
    • Android Studio at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/212.5712.43.2112.8815526/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.71.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.6 21G115 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 105.0.5195.125

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

```
[✓] Flutter (Channel master, 3.4.0-33.0.pre.35, on macOS 12.6 21G115 darwin-arm64, locale en-GB)
    • Flutter version 3.4.0-33.0.pre.35 on channel master at /Users/nexus/dev/sdks/flutters
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 8f066b975a (5 hours ago), 2022-09-28 01:33:06 -0400
    • Engine revision 6b314c9864
    • Dart version 2.19.0 (build 2.19.0-247.0.dev)
    • DevTools version 2.17.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/213.7172.25.2113.9014738/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A309
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] Android Studio (version 2021.3)
    • Android Studio at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/213.7172.25.2113.9014738/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] Android Studio (version 2021.2)
    • Android Studio at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/212.5712.43.2112.8815526/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.71.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.6 21G115 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 105.0.5195.125

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by st-flower** [comment] 2022-10-07 15:42
@danagbemava-nc 
@stuartmorgan 

How about after that?
Do you plan do it fix?

**Comment by stuartmorgan** [comment] 2022-10-07 15:45
Please see https://github.com/flutter/flutter/wiki/Issue-hygiene#when-will-my-bug-be-fixed

**Comment by giorgio79** [comment] 2022-11-16 17:49
Possibly dupe of https://github.com/flutter/flutter/issues/105965

**Comment by jehhxuxu** [comment] 2023-08-22 00:27
Same here 

![Screenshot 2023-08-21 at 21 26 31](https://github.com/flutter/flutter/assets/27310692/a7dadc66-47be-4d58-a08c-f1441eb41b21)

**Closed** 2023-11-30 18:13 UTC
Labels: c: crash, platform-android, p: maps, package, has reproducible steps, P2, c: fatal crash, found in release: 3.3, found in release: 3.4, team-android, triaged-android, multiteam-retriage-candidate
