### ISSUE TITLE
[go_router] Add support for ShellRoute in Type-safe Routing

### ISSUE THREAD

**Issue by Henriquedn** [flutter/flutter#117784] opened 2022-12-29 18:35 UTC
I have been trying to use Type-safe routing and it works fine with simple and nested routing.

However I have searched (including documentation and the package code itself) but haven't found a way to use **ShellRoute** with type-safe navigation.

I tried combining both type-safe and the default style as below with only the ShellRoute routes being typed but the result is not desirable.

```
late final GoRouter appGoRouter = GoRouter(
    navigatorKey: _rootNavigatorKey,
    debugLogDiagnostics: appDebug,
    initialLocation: '/landing-page',
    routes: <RouteBase>[
      GoRoute(
        path: '/',
        builder: (context, state) => const LandingView(),
      ),
      GoRoute(
        path: '/login',
        builder: (context, state) => const LoginView(),
      ),
      ShellRoute(
        navigatorKey: _shellNavigatorKey,
        builder: (BuildContext context, GoRouterState state, Widget child) {
          return ScaffoldWithNavBar(child: child);
        },
        routes: $appRoutes,
      ),
    ]);

```

It would be great if ShellRoute can be incorporated in the type-safe routing.

**Comment by huycozy** [comment] 2022-12-30 09:37
@Henriquedn As my understanding, using `Type-safe routes` will help to generate route objects and navigate between routes without using path strings. I'm just curious about how it will be used in this proposal. Can you be more specific about this?

**Comment by Henriquedn** [comment] 2023-01-05 21:08
> @Henriquedn As my understanding, using `Type-safe routes` will help to generate route objects and navigate between routes without using path strings. I'm just curious about how it will be used in this proposal. Can you be more specific about this?

The issue I am facing is that I want to use Type-safe routing and at the same time I want to use a ShellRoute. There is currently (the far that I have searched, including go_router_builder code) no way to do this. 
It there is, kindly point me towards it and see if it sorts out my issue.

**Comment by huycozy** [comment] 2023-01-06 04:22
@Henriquedn thanks for your response. I also haven't seen a Shell Route example at [go_router_builder/example](https://github.com/flutter/packages/tree/main/packages/go_router_builder/example). Labeling the issue as a new feature.

**Comment by huycozy** [comment] 2023-01-06 04:31
@Henriquedn 
I see there's an issue addressing the case you described #111888 and it's marked as a duplicate of #111909. 

So I will close this in favor of #111909. Please follow up on it for further updates. You can leave there your comment and react an upvote to the original comment will help to raise the issue. Thank you!

**Closed by huycozy** 2023-01-06 04:31 UTC
Labels: in triage
