### ISSUE TITLE
[Linux] TextField does not take text from CJK input methods

### ISSUE THREAD

**Issue by wangg** [flutter/flutter#45794] opened 2019-11-29 04:17 UTC
I am building the textfield example below as a Linux desktop application.
  https://flutter.dev/docs/cookbook/forms/retrieve-input

1. When I input CJK characters using CJK methods, the TextField cannot get anything and thus also shows nothing visually.
2. However, if I type the same characters in a text editor, and copy them into the TextField, everything works fine.

The same behavior is confirmed in both Ubuntu 16.04 and 18.04.
The same behavior is also confirmed with both ibus and fcitx input methods.

**Comment by stuartmorgan** [comment] 2019-11-29 06:26
Duplicate of #30662

**Closed by stuartmorgan** 2019-11-29 06:26 UTC
