### ISSUE TITLE
error - Cannot fit requested classes in a single dex file

### ISSUE THREAD

**Issue by BenHayat** [flutter/flutter#27682] opened 2019-02-08 13:08 UTC
If I try to put both Auth and Firestore plugins in the same project, I get the above error. But I can only put ONE plugin in the dependencies section.
What is problem?

Here, these two versions work independently but not together.
```yml
  cloud_firestore: ^0.8.2+3
  firebase_auth: ^0.6.6
```

**Comment by zoechi** [comment] 2019-02-08 13:31
Sounds like https://stackoverflow.com/questions/44653261/android-dependency-has-different-version-for-the-compile-and-runtime

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by BenHayat** [comment] 2019-02-08 13:37
@zoechi;
I don't think this is the same problem as you provided link. This problem is related to two plugins being saved in dex file.

Secondly, I was not asking or "Support question" but rather reporting this problem.
Since I have started Flutter I can not use Auth and Firestore plugins in the same project. I'm reporting this as a problem.
Please don't close this and get it ignored.

**Comment by zoechi** [comment] 2019-02-08 14:40
Please add the full error output and the output of `flutter doctor -v`

**Comment by BenHayat** [comment] 2019-02-08 15:00
Sure!
_____________
Launching lib\main.dart on Z970 in debug mode...
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
D8: Cannot fit requested classes in a single dex file (# methods: 66094 > 65536)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: C:\Flutter_WS\Test\new_test\build\app\intermediates\transforms\dexBuilder\debug\69.jar, C:\Flutter_WS\Test\new_test\build\app\intermediates\transforms\dexBuilder\debug\64.jar, C:\Flutter_WS\Test\new_test\build\app\intermediates\transforms\dexBuilder\debug\9.jar, C:\Flutter_WS\Test\new_test\build\app\intermediates\transforms\dexBuilder\debug\12.jar, C:\Flutter_WS\Test\new_test\build\app\intermediates\transforms\dexBuilder\debug\39.jar, C:\Flutter_WS\Test\new_test\build\app\intermediates\transforms\dexBuilder\debug\20.jar, C:\Flutter_WS\Test\new_test\build\app\intermediates\transforms\dexBuilder\debug\46.jar, C:\Flutter_WS\Test\new_test\build\app\intermediates\transforms\dexBuilder\debug\48.jar, C:\Flutter_WS\Test\new_test\build\app\intermediates\transforms\dexBuilder\debug\11.jar, C:\Flutter_WS\Test\new_test\build\app\intermediates\transforms\dexBuilder\debug\8.jar, C:\Flutter_WS\Test\new_test\build\app\intermediates\transforms\dexBuilder\debug\14.jar, C:\Flutter_WS\Test\new_test\build\app\intermediates\transforms\dexBuilder\debug\49.jar, C:\Flutter_WS\Test\new_test\build\app\intermediates\transforms\dexBuilder\debug\45.jar, C:\Flutter_WS\Test\new_test\build\app\intermediates\transforms\dexBuilder\debug\23.jar, C:\Flutter_WS\Test\new_test\build\app\intermediates\transforms\dexBuilder\debug\10.jar, C:\Flutter_WS\Test\new_test\build\app\intermediates\transforms\dexBuilder\debug\7.jar, C:\Flutter_WS\Test\new_test\build\app\intermediates\transforms\dexBuilder\debug\28.jar, C:\Flutter_WS\Test\new_test\build\app\intermediates\transforms\dexBuilder\debug\15.jar, C:\Flutter_WS\Test\new_test\build\app\intermediates\transforms\dexBuilder\debug\40.jar, C:\Flutter_WS\Test\new_test\build\app\intermediates\transforms\dexBuilder\debug\22.jar, C:\Flutter_WS\Test\new_test\build\app\intermediates\transforms\dexBuilder\debug\16.jar, C:\Flutter_WS\Test\new_test\build\app\intermediates\transforms\dexBuilder\debug\35.jar, C:\Flutter_WS\Test\new_test\build\app\intermediates\transforms\dexBuilder\debug\29.jar, C:\Flutter_WS\Test\new_test\build\app\intermediates\transforms\dexBuilder\debug\6.jar, C:\Flutter_WS\Test\new_test\build\app\intermediates\transforms\dexBuilder\debug\47.jar, C:\Flutter_WS\Test\new_test\build\app\intermediates\transforms\dexBuilder\debug\34.jar, C:\Flutter_WS\Test\new_test\build\app\intermediates\transforms\dexBuilder\debug\21.jar, C:\Flutter_WS\Test\new_test\build\app\intermediates\transforms\dexBuilder\debug\17.jar, C:\Flutter_WS\Test\new_test\build\app\intermediates\transforms\dexBuilder\debug\42.jar, C:\Flutter_WS\Test\new_test\build\app\intermediates\transforms\dexBuilder\debug\26.jar, C:\Flutter_WS\Test\new_test\build\app\intermediates\transforms\dexBuilder\debug\5.jar, C:\Flutter_WS\Test\new_test\build\app\intermediates\transforms\dexBuilder\debug\18.jar, C:\Flutter_WS\Test\new_test\build\app\intermediates\transforms\dexBuilder\debug\50.jar, C:\Flutter_WS\Test\new_test\build\app\intermediates\transforms\dexBuilder\debug\33.jar, C:\Flutter_WS\Test\new_test\build\app\intermediates\transforms\dexBuilder\debug\41.jar, C:\Flutter_WS\Test\new_test\build\app\intermediates\transforms\dexBuilder\debug\24.jar, C:\Flutter_WS\Test\new_test\build\app\intermediates\transforms\dexBuilder\debug\27.jar, C:\Flutter_WS\Test\new_test\build\app\intermediates\transforms\dexBuilder\debug\4.jar, C:\Flutter_WS\Test\new_test\build\app\intermediates\transforms\dexBuilder\debug\19.jar, C:\Flutter_WS\Test\new_test\build\app\intermediates\transforms\dexBuilder\debug\32.jar, C:\Flutter_WS\Test\new_test\build\app\intermediates\transforms\dexBuilder\debug\36.jar, C:\Flutter_WS\Test\new_test\build\app\intermediates\transforms\dexBuilder\debug\37.jar, C:\Flutter_WS\Test\new_test\build\app\intermediates\transforms\dexBuilder\debug\44.jar, C:\Flutter_WS\Test\new_test\build\app\intermediates\transforms\dexBuilder\debug\31.jar, C:\Flutter_WS\Test\new_test\build\app\intermediates\transforms\dexBuilder\debug\30.jar, C:\Flutter_WS\Test\new_test\build\app\intermediates\transforms\dexBuilder\debug\13.jar, C:\Flutter_WS\Test\new_test\build\app\intermediates\transforms\dexBuilder\debug\38.jar, C:\Flutter_WS\Test\new_test\build\app\intermediates\transforms\dexBuilder\debug\43.jar, C:\Flutter_WS\Test\new_test\build\app\intermediates\transforms\dexBuilder\debug\25.jar
  The number of method references in a .dex file cannot exceed 64K.
  Learn how to resolve this issue at https://developer.android.com/tools/building/multidex.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 8s
Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

_________________
Microsoft Windows [Version 10.0.17134.523]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\WINDOWS\system32>flutter doctor -v
[√] Flutter (Channel stable, v1.0.0, on Microsoft Windows [Version
    10.0.17134.523], locale en-US)
    • Flutter version 1.0.0 at C:\Flutter\flutter
    • Framework revision 5391447fae (2 months ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at C:\Users\Ben\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling      support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[√] Android Studio (version 3.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)

[√] VS Code, 64-bit edition (version 1.30.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 2.22.3

[√] Connected device (1 available)
    • Z970 • 18d84bde • android-arm • Android 4.4.4 (API 19)

• No issues found!

C:\Windows\System32>

**Comment by zoechi** [comment] 2019-02-08 15:09
See #21009

**Comment by BenHayat** [comment] 2019-02-08 15:24
But most of those messages were from 2018 before V1. We are now in V1.0 and still same problem out of the box.
I changed to:         minSdkVersion 21
And I get other errors.

**Comment by zoechi** [comment] 2019-02-08 15:35
I think you need to https://developer.android.com/studio/build/multidex

**Comment by Jeremywhiteley** [comment] 2019-02-08 16:17
I am having the same issue.  It doesn’t work and results in errors.   Is there a code lab that has Firebase Auth working with Cloud Firestore?    I can’t find any examples that shows this working.    

Can we please get a google engineer to comment on this?  The above suggestions, are just suggestions and they do not work.

**Comment by Hixie** [comment] 2019-02-08 22:46
@Jeremywhiteley: @zoechi is a valued member of the Flutter team, and indeed is a Google engineer, not that it would matter in the slightest if he were not. Please review https://github.com/flutter/flutter/blob/master/CODE_OF_CONDUCT.md before posting again.

In any case I think the answer is indeed that to use those two plugins together you need to enable multidex, as described at <https://developer.android.com/studio/build/multidex>. They together import too many large libraries, as far as I can tell.

**Comment by Jeremywhiteley** [comment] 2019-02-08 22:52
I get the error when I do an IOS build only as well.

**Comment by zoechi** [comment] 2019-02-11 08:16
@Jeremywhiteley that sounds unlikely because the error is from Android Gradle build.
Please post the full log output (add `-v` option to the build command)

**Comment by Jeremywhiteley** [comment] 2019-02-11 13:04
@zoechi   I get an error when running an iOS build. I never said it was the same error.   In fact there are numerous other open issues on this exact same topic.     What is the fix?

**Comment by zoechi** [comment] 2019-02-11 14:11
> I get the error when I do an IOS build only

> I never said it was the same error.

I'm confused. 
I'd suggest you either comment on an issue with the same error or create a new issue with properly filled issue template so that we are able to reproduce.

**Comment by zoechi** [comment] 2019-02-18 09:46
Possible duplicate of #13079

**Comment by zoechi** [comment] 2019-02-18 09:51
Somewhat related to #22021

**Comment by SunnySkss** [comment] 2019-05-15 13:57
Hello ,
I am facing this problem when i build my project..(below error)
Cannot fit requested classes in a single dex file (# methods: 66875 > 65536) |  

What should i do ..?

**Comment by zolzaya** [comment] 2019-06-16 02:31
Have you guys solved it? I have a same issue....

**Comment by zolzaya** [comment] 2019-06-22 11:55
Any updates?????

**Comment by sandeepsoni25** [comment] 2019-06-22 18:41
Yes dear i have been removed multi dex 

> Have you guys solved it? I have a same issue....

Yes dear I have been solved this problem....

just follow steps:

               In Android

If you are facing like error with your android project like :
1.  Cannot fit requested classes in a single dex file (# methods: 66875 > 65536)

	If give this type error, Please dont worry about for this.

  declare dependancy in your build.gradle file
                    implementation 'com.android.support:multidex:1.0.3'
    
    defaultConfig {   // your config code       
                     multiDexEnabled true       
    		}
    buildTypes {
        release {
                 multiDexKeepFile file('multidex-config.txt')
                }
             }
   	}
   Now,please again build your project. Error will be removed...Enjoy

**Comment by ChristBKK** [comment] 2019-07-21 01:33
@sandeepsoni25 solution worked for me. Thanks

**Comment by Jimmysonblack** [comment] 2019-08-11 12:15
Thanks very much, it worked for me!

**Comment by SunnySkss** [comment] 2019-08-11 12:32
Welcome sir

**Comment by CoreyCole** [comment] 2019-10-07 18:52
@sandeepsoni25 I believe the `android.support` libraries are deprecated, no? If you are using android X in your flutter app you can also fix the problem by adding the android x dependency:
```gradle
// android/app/build.gradle
dependencies {
  // ...
  def multidex_version = "2.0.1"
  implementation 'androidx.multidex:multidex:$multidex_version'
}
```
and in the android default config:
```gradle
// android/app/build.gradle
android {
  // ...
  defaultConfig {
    // ...
    multiDexEnabled true
  }
}
```
I **did not** have to add the multiDexKeepFile to build without errors. Can anyone explain the purpose of this file and why I might need it?

Also, read about what multidex is here: https://developer.android.com/studio/build/multidex

Has anyone found out which of the libraries (cloud_firestore or firebase_auth) is causing the limit to be reached? Depending on which library is causing the method limit to be reached, we should add to the getting started documentation that multidex is required. Either that or somehow reduce the number of methods, if that is possible.

In my project, I am using the following:
```
# firebase
firebase_auth: 0.14.0+5
cloud_firestore: 0.12.9+4
firebase_database: 3.0.7
firebase_analytics: 5.0.2
flutter_crashlytics: 1.0.0

# other
rxdart: 0.21.0
carousel_slider: 1.3.0
localstorage: 2.0.0
```

**Comment by kroikie** [comment] 2019-10-13 18:27
@BenHayat

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/457. Any further collaboration will be done there.

**Closed by kroikie** 2019-10-13 18:27 UTC
Labels: p: cloud_firestore, p: firebase, p: firebase_auth, p: first party, plugin

**Comment by YohanWadia** [comment] 2020-04-01 17:13
@CoreyCole 's solution worked for me.
But for those who just ran a Flutter upgrade in April2020... I couldnt find the dependency section in my  android/app/build.gradle... so all i did was the below, and it worked fine!

```
android {
  // ... other stuff
  defaultConfig {
    // ... other stuff
    multiDexEnabled true
  }
}

```
