### ISSUE TITLE
[iOS]  Long press space key the immediately delete text cause two vertical line to appear in the text field 

### ISSUE THREAD

**Issue by wanzc** [flutter/flutter#65440] opened 2020-09-09 02:27 UTC
When I use textfield, there is a bug：
1.activate textfield
2.input some text
3.press "space" and release immediately
4.the cursor cannot be cancelled

**Comment by softmarshmallow** [comment] 2020-09-09 06:26
that does not seems like a bug to me. what is the expected behaiviour?

**Comment by TahaTesser** [comment] 2020-09-09 08:52
Hi @wanzc 
Pressing `space` and releasing it immediately just suppose to ad extra space in the text field.  
Can you please clarify "new features" and provide actual result vs expected results

Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by wanzc** [comment] 2020-09-10 02:30
Hi!
I'm very sorry. Maybe I didn't describe it completely enough.

This happens to both IOS emulators and real machines on versions 1.17.5 and 1.20.3, respectively.

When I use "TextField", long press "space" on the keyboard, release it, and then "delete" text, two vertical lines appear.

Later, I used the UITextField of UIKit on IOS native project, and found that it was normal, but it would happen when I used the Textfield of flutter.
![WechatIMG253](https://user-images.githubusercontent.com/30285479/92674744-873bd500-f350-11ea-81e8-5289727238b9.png)

![Simulator Screen Shot - iPhone 11 - 2020-09-10 at 10 13 14](https://user-images.githubusercontent.com/30285479/92674576-388e3b00-f350-11ea-9d55-bd89001cd382.png)
![Simulator Screen Shot - iPhone 11 - 2020-09-10 at 10 13 34](https://user-images.githubusercontent.com/30285479/92674584-3d52ef00-f350-11ea-9778-ea1f3dd138a4.png)
![Simulator Screen Shot - iPhone 11 - 2020-09-10 at 10 14 07](https://user-images.githubusercontent.com/30285479/92674593-404ddf80-f350-11ea-9df8-1ae3f49b5f50.png)

![WechatIMG686](https://user-images.githubusercontent.com/30285479/92674760-90c53d00-f350-11ea-84b3-af4b314041aa.png)

**Comment by TahaTesser** [comment] 2020-09-10 07:43
Hi @wanzc 
Just reproduced it on stable but this is fixed in the `beta` to  the `master` channels 

<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel beta, 1.21.0-9.2.pre, on Mac OS X 10.15.6 19G2021, locale
    en-GB)
    • Flutter version 1.21.0-9.2.pre at /Users/tahatesser/Code/flutter_beta
    • Framework revision 81a45ec2e5 (13 days ago), 2020-08-27 14:14:33 -0700
    • Engine revision 20a9531835
    • Dart version 2.10.0 (build 2.10.0-7.3.beta)

 
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.7, Build version 11E801a
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.48.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

[✓] Connected device (3 available)
    • iPhone 11 (mobile) • 73130414-6DF8-4E37-B9AF-F81FA0F9068B • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-13-7 (simulator)
    • Web Server (web)   • web-server                           • web-javascript
      • Flutter Tools
    • Chrome (web)       • chrome                               • web-javascript
      • Google Chrome 85.0.4183.102

! Doctor found issues in 1 category.
```

</details> 

I cannot reproduce this issue on the latest `beta` channel.
Can you please upgrade to the latest  `beta` and try again
`flutter channel beta`
`flutter upgrade --force`
`flutter doctor -v`

Closing, as fixed. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2020-09-10 07:43 UTC
Labels: in triage
