### ISSUE TITLE
Flutter run fails mysteriously when lib/main.dart is empty

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#21010] opened 2018-08-24 23:19 UTC
This isn't a critical problem :-).

If you accidentally launch a flutter app with `flutter run` and lib/main.dart is empty the reported error is not "you have an empty lib/main.dart file" but: "Could not prepare to run the isolate." etc.

I can say from personal experience that this is a little confusing.

```
Launching lib/main.dart on Nexus 5 in debug mode...
Initializing gradle...                                       0.8s
Resolving dependencies...                                    1.1s
Running 'gradlew assembleDebug'...                           9.8s
Built build/app/outputs/apk/debug/app-debug.apk.
Installing build/app/outputs/apk/app.apk...                 12.1s
E/flutter ( 5140): [ERROR:flutter/shell/common/engine.cc(158)] Could not prepare to run the isolate.
E/flutter ( 5140): [ERROR:flutter/shell/common/engine.cc(117)] Engine not prepare and launch isolate.
E/flutter ( 5140): [ERROR:flutter/shell/platform/android/android_shell_holder.cc(166)] Could not launch engine in configuration.
```

**Comment by zoechi** [comment] 2018-09-07 06:58
#19167 looks similar.

**Comment by jason-simmons** [comment] 2018-09-07 22:02
The frontend server is reporting success when it tries to compile the empty input file.  However, the resulting kernel blob has no root library and can not be loaded at runtime.

@aam

**Comment by zoechi** [comment] 2018-12-11 14:50
Is this still an issue? #21221 looks similar and seems to be solved?

**Comment by zoechi** [comment] 2019-02-14 16:06
Duplicate of #22081

**Closed by zoechi** 2019-02-14 16:06 UTC
Labels: engine, severe: crash, tool
