### ISSUE TITLE
TextFormField helperText does not use multiple lines on Flutter web

### ISSUE THREAD

**Issue by paoloposo** [flutter/flutter#62907] opened 2020-08-04 21:38 UTC
When using the `helperText` on an `InputDecoration` on a `FormField` widget in conjunction with `helperMaxLines > 1`, I would expect the helper text to use multiple lines when it doesn't fit in one line, even if the text doesn't incluce newlines (`\n`).

The functionality was added with #39433.

## Steps to Reproduce

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
	return MaterialApp(
	  home: MyHomePage(),
	);
  }
}

class MyHomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
	return Scaffold(
	  body: Container(
		width: 200,
		child: Padding(
		  padding: const EdgeInsets.all(8),
		  child: TextFormField(
			decoration: InputDecoration(
			  helperText: 'one, two, three, four, five, six, seven, eight, nine, ten, eleven, twelve, thirteen, fourteen, fifteen, sixteen, seventeen, eighteen, nineteen, twenty, twenty-one, twenty-two, twenty-three, twenty-four, twenty-five, twenty-six, twenty-seven, twenty-eight, twenty-nine, thirty',
			  helperMaxLines: 3,
			),
		  ),
		),
	  ),
	);
  }
}
```

**Expected results:** 
The helper text using all three available lines, the second line therefore continuing with "seven".

**Actual results:** 
![grafik](https://user-images.githubusercontent.com/10469413/89347205-9cb34480-d6aa-11ea-81ae-57aed7ea3e31.png)

---

```
[√] Flutter (Channel beta, 1.20.0-7.3.pre, on Microsoft Windows [Version 10.0.18363.959], locale de-DE)
    • Flutter version 1.20.0-7.3.pre at C:\flutter
    • Framework revision e606910f28 (7 days ago), 2020-07-28 16:06:37 -0700
    • Engine revision ac95267aef
    • Dart version 2.9.0 (build 2.9.0-21.10.beta)

[X] Android toolchain - develop for Android devices
    X Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_SDK_ROOT to that location.
      You may also want to add it to your PATH environment variable.


[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[!] IntelliJ IDEA Ultimate Edition (version 2019.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2018.3.4
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

|Error 1 retrieving device properties for ro.product.cpu.abi:
error: closed


[√] Connected device (4 available)
    • emulator-5556 (mobile) • emulator-5556 • android-arm    • Android null (API null)
    • Web Server (web)       • web-server    • web-javascript • Flutter Tools
    • Chrome (web)           • chrome        • web-javascript • Google Chrome 84.0.4147.105
    • Edge (web)             • edge          • web-javascript • Microsoft Edge 84.0.522.52

! Doctor found issues in 3 categories.

```

**Comment by pedromassangocode** [comment] 2020-08-05 11:46
Hi @paoloposo 
I cannot reproduce this issue on latest dev channel.

![Screen Shot 2020-08-05 at 12 46 35](https://user-images.githubusercontent.com/67424416/89409269-b3dd4b00-d719-11ea-8d0b-4ec2218cfc1c.png)

Can you upgrade to dev and try again
`flutter channel dev`
`flutter upgrade --force`
`flutter doctor -v`

**Comment by paoloposo** [comment] 2020-08-06 14:36
Hello @pedromassangocode , thanks for your reply! What I forgot to mention in the original issue (but thankfully your screenshot reminded me) is that I was testing this in Flutter web (I've updated the issue accordingly).

I tried the same code on an emulated Android device and it worked there. As per your suggestion, I tried using the `dev` channel with unchanged results (=working on Android, not working on web).

<details>
  <summary>Output of `flutter doctor -v` using `dev` channel</summary>

```
[√] Flutter (Channel dev, 1.21.0-1.0.pre, on Microsoft Windows [Version 10.0.18363.959], locale de-DE)
    • Flutter version 1.21.0-1.0.pre at D:\sdk\flutter
    • Framework revision f25bd9c55c (3 weeks ago), 2020-07-14 20:26:01 -0400
    • Engine revision 99c2b3a245
    • Dart version 2.9.0 (build 2.9.0-21.0.dev 20bf2fcf56)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at D:\sdk\android-sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: D:\sdk\jdk-11\bin\java.exe
    • Java version OpenJDK Runtime Environment 18.9 (build 11+28)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[!] IntelliJ IDEA Ultimate Edition (version 2019.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2018.3.4
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[√] Connected device (4 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Web Server (web)            • web-server    • web-javascript • Flutter Tools
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 84.0.4147.105
    • Edge (web)                  • edge          • web-javascript • Microsoft Edge 84.0.522.52

! Doctor found issues in 3 categories.

```
</details>

I still believe this to be a bug (now even more so, since the result should be the same on all platforms).

**Comment by pedromassangocode** [comment] 2020-08-07 06:40
Hi @paoloposo
I cannot reproduce this issue on latest `master` channel.

<img width="460" alt="Screen Shot 2020-08-07 at 07 38 53" src="https://user-images.githubusercontent.com/67424416/89616935-27e63300-d881-11ea-8b71-5801e781edd8.png">

Can you try this on `master` and try again
`flutter channel master`
`flutter upgrade --force`
`flutter doctor -v`

<details>
<summary> flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.21.0-6.0.pre.245, on Mac OS X 10.15.6 19G73,
    locale en)
    • Flutter version 1.21.0-6.0.pre.245 at
      /Users/pedromassango/dev/SDKs/flutter_master
    • Framework revision 77b4505c80 (5 hours ago), 2020-08-06 18:51:02 -0700
    • Engine revision cd3ea1e839
    • Dart version 2.10.0 (build 2.10.0-3.0.dev fcafd43f2c)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

 
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2020.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 47.1.4
    • Dart plugin version 202.6397.47

[✓] Connected device (3 available)
    • macOS (desktop)  • macos      • darwin-x64     • Mac OS X 10.15.6 19G73
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome
      84.0.4147.105

! Doctor found issues in 2 categories.
```
</details>

**Comment by paoloposo** [comment] 2020-08-07 09:44
@pedromassangocode Using the latest master my example works on web as well. However, it not working in beta, wouldn't that mean when beta gets merged into master eventually, it will stop working again?

Also, I didn't even know Flutter for web was already in master, since the [Web FAQ](https://flutter.dev/docs/development/platform-integration/web) and [Web getting started](https://flutter.dev/docs/get-started/web) doc sites say otherwise. Is that an issue with the docs or am I missing something?

**Comment by pedromassangocode** [comment] 2020-08-07 12:14
Hi @paoloposo 
The master channel is where Flutter framework is being worked on, so it is not recommended in the Flutter docs. This issue was probably fixed now, and may be updated anytime.

given your last message I feel safe to close this issue,
if you disagree please write in the comments
and I will reopen it. 
Thank you

**Closed by pedromassangocode** 2020-08-07 12:14 UTC
Labels: in triage

**Comment by paoloposo** [comment] 2020-08-07 12:23
I did not know that at Flutter, master is less stable than dev. [This wiki page](https://github.com/flutter/flutter/wiki/Flutter-build-release-channels) cleared that up for me. Thanks for your help!
