### ISSUE TITLE
Copy and paste text of dialog with TextField for Japanese is not centered vertically in iOS

### ISSUE THREAD

**Issue by donchan922** [flutter/flutter#73681] opened 2021-01-11 01:26 UTC
## Steps to Reproduce
1. Use iOS
2. Use TextField for Japanese (using `flutter_localizations` package)
3. Display copy and paste dialog

**main.dart**
```dart
import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      localizationsDelegates: const [
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
      ],
      supportedLocales: const [
        Locale('ja', ''),
      ],
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('TextField demo'),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            TextField(),
          ],
        ),
      ),
    );
  }
}
```

**pubspec.yaml**
```yaml
name: demo
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
```

<details>
  <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 1.22.5, on macOS 11.1 20C69 darwin-x64, locale ja-JP)
    • Flutter version 1.22.5 at /Users/donchan922/flutter
    • Framework revision 7891006299 (4 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/donchan922/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.0

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (1 available)
    • iPhone SE (2nd generation) (mobile) • 345BC08D-0CD9-49CC-ABF0-8EA61B9FD588 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-5
      (simulator)

! Doctor found issues in 1 category.
```

</details>

**Expected results:**
Copy and paste text of dialog with TextField for Japanese should be centered vertically in iOS.

![demo-actual](https://user-images.githubusercontent.com/31620041/104140629-b8f3a400-53f5-11eb-92d1-28b3462f3a3e.png)

**Actual results:**
Copy and paste text of dialog with TextField for Japanese is not centered vertically (a little below the center).

![demo](https://user-images.githubusercontent.com/31620041/104140199-92346e00-53f3-11eb-9687-2b41896a9b62.png)

**Comment by YeungKC** [comment] 2021-01-11 05:34
I remember that you have dealt with similar issues. @justinmc

**Comment by kaboc** [comment] 2021-01-11 07:41
It looks similar to #58512. They may be related in some way.

**Comment by justinmc** [comment] 2021-01-11 17:36
I think this may be a regression in CupertinoButton (which is used inside the text selection menu).  @HansMuller Is this a regression or is it intended?

If I create two CupertinoButtons side-by-side, one with Japanese text and one with English, I see that they have different heights:

<img width="399" alt="Screen Shot 2021-01-11 at 9 29 55 AM" src="https://user-images.githubusercontent.com/389558/104217030-b4c48800-53ef-11eb-8b4c-dceaee38082d.png">

However, if I try this with TextButtons, there is no height difference:

<img width="163" alt="Screen Shot 2021-01-11 at 9 28 56 AM" src="https://user-images.githubusercontent.com/389558/104217028-b42bf180-53ef-11eb-8bab-71aee253c429.png">

Also, when trying the CupertinoButtons on DartPad, which is using an older version of Flutter, they have the same height:

![Screen Shot 2021-01-11 at 9 31 29 AM](https://user-images.githubusercontent.com/389558/104217400-32889380-53f0-11eb-9be7-0feb7d7c8ed0.png)

**Comment by HansMuller** [comment] 2021-01-11 18:40
This was not an intentional change per the updates to the buttons and their themes.

**Comment by pedromassangocode** [comment] 2021-01-12 13:48
![Screen Shot 2021-01-12 at 14 41 00](https://user-images.githubusercontent.com/67424416/104321687-431a3600-54e4-11eb-952d-759a9ee80e3c.png)

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel master, 1.26.0-2.0.pre.295, on Mac OS X 10.15.7 19H2 darwin-x64, locale en)
    • Flutter version 1.26.0-2.0.pre.295 at /Users/pedromassango/Code/flutter_master
    • Framework revision c19fdad097 (10 hours ago), 2021-01-11 22:19:02 -0500
    • Engine revision 0ed964d6b7
    • Dart version 2.12.0 (build 2.12.0-212.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 52.1.5
    • Dart plugin version 203.6912

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (3 available)
    • iPhone 12 Pro Max (mobile) • ECCF5C4A-8BEC-411D-B23E-85A836C3847E • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-1 (simulator)
    • macOS (desktop)            • macos                                • darwin-x64     • Mac OS X 10.15.7 19H2 darwin-x64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 87.0.4280.141

! Doctor found issues in 1 category.
```

</details>

**Comment by justinmc** [comment] 2021-01-26 22:48
Closing as a duplicate of https://github.com/flutter/flutter/issues/69847.  Let's move the discussion over there.

**Closed by justinmc** 2021-01-26 22:48 UTC
Labels: a: text input, f: material design, found in release: 1.26, framework, has reproducible steps, platform-ios, severe: regression
