### ISSUE TITLE
Scrollable containers don't make edge elements fully visible when swiping a11y focus on iOS

### ISSUE THREAD

**Issue by nscobie** [flutter/flutter#61624] opened 2020-07-16 16:35 UTC
Related: #36307 for Android `GridView` issues.

### Problem

When using an accessibility service on iOS (VoiceOver), focusing on an element (by tap or swipe) in a scrollable container (`GridView`, `ListView`, etc.) which is partially obscured does _not_ make the element fully visible. However, swiping to a fully hidden element beyond the currently visible items _does_ make the element visible by scrolling the list.

### Background

Implicit accessibility scrolling on iOS (ex: VoiceOver) is achieved by caching the next few items outside of view of the current scroll area in the semantic tree, but marking them as [isHidden](https://api.flutter.dev/flutter/semantics/SemanticsConfiguration/isHidden.html). When the accessibility focus moves from an item in the visible viewport to an `isHidden` item in the cache area (ex: swiping right with VoiceOver), the [engine will call showOnScreen](https://github.com/flutter/engine/blob/2a9fed87a7c237230f4f364a29fb3bb8e9e992fd/shell/platform/darwin/ios/framework/Source/SemanticsObject.mm#L456) on the widget.

### What needs to change

We likely need to also call `showOnScreen` for items which are partially obscured, but not marked as `isHidden`.

### Sample taken from #36307 

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatefulWidget {
  @override
  State createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  bool useSemanticsDebugger = false;

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        showSemanticsDebugger: useSemanticsDebugger,
        theme: ThemeData(primaryColor: Colors.blue),
        home: Scaffold(
          appBar: AppBar(
            title: Text('GridView Semantics Test'),
          ),
          body: GridView.count(crossAxisCount: 4,
//          body: ListView( // Try swapping the GridView for this ListView. The problem happens for both.
              children: _buildChildren(context),
          ),
        ));
  }

  List<Widget> _buildChildren(BuildContext context) {
    final widgets = List<Widget>();
    for(int i = 0; i < 100; ++i) {
      widgets.add(ListTile(
        title: Text('Cell $i'),
      ));
    }
    return widgets;
  }
}
```

**Comment by TahaTesser** [comment] 2020-07-23 14:14
<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel master, 1.21.0-2.0.pre.95, on Mac OS X 10.15.6 19G73, locale en-GB)
    • Flutter version 1.21.0-2.0.pre.95 at /Users/tahatesser/Code/flutter_master
    • Framework revision 50b87dc6c3 (19 hours ago), 2020-07-22 11:09:59 -0700
    • Engine revision dcc9a4048d
    • Dart version 2.9.0 (build 2.9.0-21.0.dev 9dca49e71e)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[✓] Connected device (5 available)
    • SM M305F (mobile)      • 32003c30dc19668f          • android-arm64  • Android 10 (API 29)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios            • iOS 13.6
    • macOS (desktop)        • macos                     • darwin-x64     • Mac OS X 10.15.6 19G73
    • Web Server (web)       • web-server                • web-javascript • Flutter Tools
    • Chrome (web)           • chrome                    • web-javascript • Google Chrome 84.0.4147.89

• No issues found!
```

</details>

**Comment by nscobie** [comment] 2020-07-29 02:58
Derailed by higher priority issues.

As seen above, I would like to add another `or` condition to where the engine [decides to call showOnScreen](https://github.com/flutter/engine/blob/13df5723883c46de2eb87896d8a51c4944c46107/shell/platform/darwin/ios/framework/Source/SemanticsObject.mm#L456) when a semantics node is focused, which would check if the node is partially hidden. My original plan was to walk the tree back from the selected node up to the root, and at each step cumulatively apply the current node's `transform` to the original node's `rect` (accumulating the transformations), and check if it fits within the bounds of the parent's `rect`. However, this would require walking the tree every time a node is selected.

Now I'm thinking it might be better to add a new `isPartiallyHidden` flag on the framework, and just do a quick flag check on the engine side. This would help solve similar problems on other platforms and promote code reuse. The current code [which calculates `isHidden`](https://github.com/flutter/flutter/blob/a317c2c06a0a11344c6cb280c9673fb7d818aa82/packages/flutter/lib/src/rendering/object.dart#L3834) could be extended to check if the `paintRect` intersection shrunk the semantics `rect`, so it would just be O(1) time per node on each tree update on the framework side rather than O(K) (where K = depth) whenever a node is focused.

I may need to write a design doc. Will post more info soon.

**Comment by goderbauer** [comment] 2020-08-06 16:45
We need to be carefully with calling `showOnScreen` for partially visible nodes. It is a common pattern for a11y users to just slide their finger over the screen to explore what is on screen. If you do that the screen content must not change while the user explores it. That means, when a11y focus lands on a partially visible node this way, we CANNOT scroll the screen. 

In other words: we can only call `showOnScreen` on a partially visible node if the a11y focus landed on it by swiping left/right on the screen (linear navigation), but not if it lands there by tapping the node or by sliding your finger over it (explore by touch). 

AFAIK, iOS doesn't have a way of telling these two navigation types apart.

**Comment by chunhtai** [comment] 2020-08-06 17:00
Do you know what is the native behavior regarding swipe left right to partially hidden node? Do they also scroll the element to be fully visible?

**Comment by nscobie** [comment] 2020-08-07 15:39
@goderbauer That makes sense in hindsight, thanks for the explanation, will put further thoughts in reply to the [design issue](https://github.com/flutter/flutter/issues/62931).

I did a little digging as well, and this [StackOverflow post](https://stackoverflow.com/a/20712889) sums up the discussions I could find. I agree there doesn't seem to be a way to tell these two navigation types apart, which seems like a pretty unfortunate platform limitation.

Should we go ahead at close this issue then, or can you think of any other approaches we could take to support this behavior?

@chunhtai for native iOS apps, swiping to a partially hidden element at the edge of any scrollable container (both `GridView` and `ListView`) **does** make the focused element visible by scrolling it to the _center_ of the visible viewport of the container. Touch exploration and tapping to focus a partially hidden element does not bring it into view, as noted by goderbauer. I'm unsure how that behavior is implemented natively, and whether or not we have access to the same functionality.

**Comment by chunhtai** [comment] 2020-08-07 16:11
@nscobie In that case we should keep this open because this is indeed a bug (at least a quality improvement). We should summarize our finding here and why we can't fix it. Hopefully in the future iOS may have new api to enable this.

**Comment by goderbauer** [comment] 2020-08-07 16:47
> Should we go ahead at close this issue then, or can you think of any other approaches we could take to support this behavior?

I would consider this one as an actual bug in our implementation because we behave differently than native would. Unfortunately, we cannot fix this one due to platform limitations. We can leave this one open to revisit in case the limitations ever change.

**Comment by huycozy** [comment] 2022-11-23 11:53
This issue is reproducible on the latest `stable` and `master` channels.

<details>
<summary>Demo video</summary>


https://user-images.githubusercontent.com/104349824/203539970-10d709e8-49a2-4deb-8415-c51765d79771.MP4


</details>

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.3.8, on macOS 13.0 22A380 darwin-x64, locale en-VN)
    • Flutter version 3.3.8 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 52b3dc25f6 (23 hours ago), 2022-11-09 12:09:26 +0800
    • Engine revision 857bd6b74c
    • Dart version 2.18.4
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Community Edition (version 2022.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 70.0.5
    • Dart plugin version 222.4167.21

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.73.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.52.0

[✓] Connected device (3 available)
    • iPhone 14 Pro Max (mobile) • 332079AF-E895-4685-910E-7B1E18B0C6B8 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-0 (simulator)
    • macOS (desktop)            • macos                                • darwin-x64     • macOS 13.0 22A380 darwin-x64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 107.0.5304.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

```bash
[!] Flutter (Channel master, 3.6.0-7.0.pre.33, on macOS 13.0 22A380 darwin-x64, locale en-VN)
    • Flutter version 3.6.0-7.0.pre.33 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b7023e843a (2 hours ago), 2022-11-22 20:47:07 -0500
    • Engine revision f75287af0b
    • Dart version 2.19.0 (build 2.19.0-416.0.dev)
    • DevTools version 2.19.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Community Edition (version 2022.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 70.0.5
    • Dart plugin version 222.4167.21

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.73.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.52.0

[✓] Connected device (4 available)
    • SM T225 (mobile)           • R9JT3004VRJ                          • android-arm64  • Android 12 (API 31)
    • iPhone 14 Pro Max (mobile) • 332079AF-E895-4685-910E-7B1E18B0C6B8 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-0 (simulator)
    • macOS (desktop)            • macos                                • darwin-x64     • macOS 13.0 22A380 darwin-x64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 107.0.5304.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```
</details>

**Comment by chunhtai** [comment] 2023-05-10 22:08
There is another report b/280593444

**Comment by chunhtai** [comment] 2023-05-12 22:37
It looks like there are two private method we can use to detect whether the voice over swipe to focus a new item

accessibilityScrollToVisible
accessibilityScrollToVisibleWithChild

These methods are only called if swipe to focus not when tocuh explore. I will attempt to make use of these method

**Closed** 2023-05-19 22:02 UTC
Labels: platform-ios, engine, waiting for PR to land (fixed), a: accessibility, f: scrolling, a: quality, customer: money (g3), has reproducible steps, P2, found in release: 3.3, found in release: 3.6
