### ISSUE TITLE
MediaQuery.of(context).padding always returns with EdgeInsets.zero in Flutter Android

### ISSUE THREAD

**Issue by Tremx389** [flutter/flutter#23421] opened 2018-10-23 18:45 UTC
Hi,
I'm totaly new in Flutter.
I've tried to get the resolution of the current device in flutter, however the `MediaQuery.of(context).size` returns with the size of the widget without other elements, like the bottom system ui elem in Android.

As far as i know, when we use
```dart
SystemChrome.setEnabledSystemUIOverlays([SystemUiOverlay.bottom]);
```

, then we should be able to get the bottom navigation bar's height with `MediaQuery.of(context).padding`, but it always returns with `EdgeInsets.zero`.

Same happens with `MediaQuery.of(context).viewInsect` and `ui.window` elems.

Please advise.

## Steps to Reproduce
```dart
  @override
  Widget build(BuildContext context) {
    SystemChrome.setEnabledSystemUIOverlays([SystemUiOverlay.bottom]);
    print(MediaQuery.of(context).padding);
  }
```
## Logs

EdgeInsets.zero

## Doctor
```
[flutter] flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v0.9.4, on Microsoft Windows [Version 10.0.17134.345], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK 28.0.2)
[√] Android Studio (version 3.1)
[√] VS Code (version 1.28.2)
[√] Connected devices (1 available)

• No issues found!
exit code 0
```

**Comment by zoechi** [comment] 2018-10-24 07:49
Do you see this on a real device or an emulator?
iOS or Android?
Can you perhaps create a screenshot that demonstrates the discrepancy?

**Comment by Tremx389** [comment] 2018-10-24 18:58
Sorry that I haven't stated these.
Android, Nexus 5X emulator.
Unfortunately I'm not allowed to share screenshots, but this issue is really confusing.. I've heard a solution that i should create a stream for both android and ios, but I believe there should be an easy way to get these values with Flutter too.

**Comment by zoechi** [comment] 2018-10-24 19:09
You don't need a screenshot from a real-world project.
I'd expect more bug reports if this wouldn't work.

**Comment by Tremx389** [comment] 2018-10-24 19:10
Well, okay, but what should I do to have the resolution?

**Comment by rmtmckenzie** [comment] 2018-10-24 19:49
@zoechi I believe this is related to a question asked on SO which gives a bit more detail - https://stackoverflow.com/questions/52954549/get-width-and-height-of-the-device-in-flutter. The issue isn't that flutter is returning the dimensions of the area it's drawing to improperly, it's that @Tremx389 was expecting that there would be a way to get the resolution of the entire phone's screen from within flutter using something like ui.window.physicalSize or MediaQuery(context).size. Instead, it's just returning the size of the area being drawn to (which _is_ what it says it does if you read the docs closely)

This part of the docs is probably the most confusing, as it makes it seem like all "system UI" might include the navigation buttons:

> This value does not take into account any on-screen keyboards or other system UI. The padding and viewInsets properties provide a view into how much of each side of the application may be obscured by system UI.

**Comment by zoechi** [comment] 2018-10-24 20:01
@rmtmckenzie thanks for the clarification!

**Comment by amen71311** [comment] 2019-02-13 12:06
In my case, 

`
  SystemChrome.setSystemUIOverlayStyle(SystemUiOverlayStyle.dark);
  double width = MediaQuery.of(context).size.width;
`
When I run in iOS simulator or Android device (debug), it is fine, but with real device (release apk or Testflight) that width will be 0 at first build then it has value later.

**Comment by zoechi** [comment] 2019-02-13 12:14
@amen71311 I think this is a different issue.
The size is provided by the native platform with a delay. When run in debug mode and perhaps also on a low emulator, then startup is usually slower and on first `build()` the size is already available.
In release mode startup is much faster and the first build often happens before the size is available and therefore `MediaQuery.of(context).size` returns `0x0`.
When the actual size becomes available the view is rebuilt again and the proper size will be reported.
You just need to ensure that a size of `0x0` does not cause an exception.

**Comment by pratikpparikh** [comment] 2019-12-03 05:31
I run into this with bottombar.   below line in 1.12.15 return 0 

`final double additionalBottomPadding = math.max(MediaQuery.of(context).padding.bottom - widget.selectedFontSize / 2.0, 0.0);`

**Comment by workerbee22** [comment] 2020-01-01 23:08
On a physical Pixel 3 XL the padding returned is always ZERO in Flutter 1.12.13+Hotfix5. So:
```
MediaQuery.of(context).padding.top
```
Returns zero.

**Comment by tvolkert** [comment] 2020-01-13 05:30
As described in the StackOverflow question above, this behavior is correct from Flutter's point of view.  Closing.

**Closed by tvolkert** 2020-01-13 05:30 UTC
Labels: d: api docs, framework, severe: new feature

**Comment by saveKenny** [comment] 2021-02-09 19:19
@tvolkert I think it's not true, since flutter consider android bottom navigation bar as part of the app's 
height but when calling:

`MediaQuery.of(context).padding.top`

It returns Zero.
