### ISSUE TITLE
`Chip.iconTheme` does not apply the icon theme

### ISSUE THREAD

**Issue by werainkhatri** [flutter/flutter#111828] opened 2022-09-18 11:59 UTC
## Steps to Reproduce

1. Execute `flutter run` on the code sample

**Expected results:** 
<img width="263" alt="Screenshot 2022-09-18 at 2 41 32 AM" src="https://user-images.githubusercontent.com/44755140/190876601-0bd40d56-f9ef-416c-8c7f-0b3fa2a73359.png">

**Actual results:** 
<img width="262" alt="Screenshot 2022-09-18 at 2 41 50 AM" src="https://user-images.githubusercontent.com/44755140/190876607-1369683a-f08e-444e-88e3-b2c8138be458.png">

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    const IconThemeData iconThemeData = IconThemeData(
      color: Colors.red,
      size: 30,
      opacity: 0.6,
    );

    return MaterialApp(
      theme: ThemeData(useMaterial3: true),
      title: 'Material App',
      home: Scaffold(
        backgroundColor: Colors.blue,
        body: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.spaceEvenly,
            children: [
              const Chip(
                iconTheme: iconThemeData,
                avatar: Icon(Icons.ac_unit),
                label: Text('Chip'),
              ),
              ActionChip(
                iconTheme: iconThemeData,
                avatar: const Icon(Icons.ac_unit),
                label: const Text('ActionChip'),
                onPressed: () {},
              ),
              ChoiceChip(
                iconTheme: iconThemeData,
                avatar: const Icon(Icons.ac_unit),
                label: const Text('ChoiceChip'),
                selected: false,
                onSelected: (_) {},
              ),
              FilterChip(
                iconTheme: iconThemeData,
                avatar: const Icon(Icons.ac_unit),
                label: const Text('FilterChip'),
                onSelected: (_) {},
              ),
              InputChip(
                iconTheme: iconThemeData,
                avatar: const Icon(Icons.ac_unit),
                label: const Text('InputChip'),
                onPressed: () {},
              ),
            ],
          ),
        ),
      ),
    );
  }
}

```

</details>

<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel stable, 3.3.2, on macOS 12.5.1 21G83 darwin-arm, locale en-IN)
    • Flutter version 3.3.2 on channel stable at /Users/werainkhatri/soft/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e3c29ec00c (3 days ago), 2022-09-14 08:46:55 -0500
    • Engine revision a4ff2c53d8
    • Dart version 2.18.1
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/werainkhatri/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13F100
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.71.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.5.1 21G83 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 105.0.5195.125

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by exaby73** [comment] 2022-09-19 09:01
## Triage report

I can reproduce this issue. Looks like `iconTheme` is not being passed to `RawChip`.

https://github.com/flutter/flutter/blob/0abb98d8aa62b57a49776f44158e3d7a986815a5/packages/flutter/lib/src/material/chip.dart#L653-L676

### Versions reproducible on

- `Stable (3.3.2)`
- `Master (3.4.0-19.0.pre.338)`

### Info

<details>
<summary>Screenshot</summary>

![issue_111828_rWQA6wIMaa](https://user-images.githubusercontent.com/50555895/190983655-2d69604b-541c-42db-b282-dc8c409084f8.png)

</details>

<details>
<summary>Code Sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    const IconThemeData iconThemeData = IconThemeData(
      color: Colors.red,
      size: 30,
      opacity: 0.6,
    );

    return MaterialApp(
      theme: ThemeData(useMaterial3: true),
      title: 'Material App',
      home: Scaffold(
        backgroundColor: Colors.blue,
        body: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.spaceEvenly,
            children: [
              const Chip(
                iconTheme: iconThemeData,
                avatar: Icon(Icons.ac_unit),
                label: Text('Chip'),
              ),
              ActionChip(
                iconTheme: iconThemeData,
                avatar: const Icon(Icons.ac_unit),
                label: const Text('ActionChip'),
                onPressed: () {},
              ),
              ChoiceChip(
                iconTheme: iconThemeData,
                avatar: const Icon(Icons.ac_unit),
                label: const Text('ChoiceChip'),
                selected: false,
                onSelected: (_) {},
              ),
              FilterChip(
                iconTheme: iconThemeData,
                avatar: const Icon(Icons.ac_unit),
                label: const Text('FilterChip'),
                onSelected: (_) {},
              ),
              InputChip(
                iconTheme: iconThemeData,
                avatar: const Icon(Icons.ac_unit),
                label: const Text('InputChip'),
                onPressed: () {},
              ),
            ],
          ),
        ),
      ),
    );
  }
}
```

</details>

### Flutter Doctor

<details><summary><code>flutter doctor -v</code> (Stable)</summary>

```
[✓] Flutter (Channel stable, 3.3.2, on Microsoft Windows [Version 10.0.22000.978], locale en-US)
    • Flutter version 3.3.2 on channel stable at C:\Users\Nabeel\fvm\versions\stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e3c29ec00c (5 days ago), 2022-09-14 08:46:55 -0500
    • Engine revision a4ff2c53d8
    • Dart version 2.18.1
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\android-sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2022 17.3.2)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.3.32819.101
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[✓] VS Code (version 1.71.0)
    • VS Code at C:\Users\Nabeel\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.46.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22000.978]
    • Chrome (web)      • chrome  • web-javascript • unknown
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 105.0.1343.27

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

<details><summary><code>flutter doctor -v</code> (Master)</summary>

```
[✓] Flutter (Channel master, 3.4.0-19.0.pre.338, on Microsoft Windows [Version 10.0.22000.978], locale en-US)
    • Flutter version 3.4.0-19.0.pre.338 on channel master at C:\Users\Nabeel\fvm\versions\master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b84bfa3526 (15 minutes ago), 2022-09-19 08:27:20 +0200
    • Engine revision b22a795011
    • Dart version 2.19.0 (build 2.19.0-214.0.dev)
    • DevTools version 2.17.0

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\android-sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2022 17.3.2)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.3.32819.101
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[✓] VS Code (version 1.71.0)
    • VS Code at C:\Users\Nabeel\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.46.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22000.978]
    • Chrome (web)      • chrome  • web-javascript • unknown
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 105.0.1343.27

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by timmaffett** [comment] 2022-09-21 14:51
https://github.com/flutter/flutter/pull/112001 fixes this bug and adds tests to verify `iconTheme` is respected for `Chip`,`ActionChip`,`ChoiceChip`,`FilterChip` and `InputChip`.

**Comment by pranavkumark13** [comment] 2022-12-28 17:08
Hello. May I know if this issue still open?

**Comment by timmaffett** [comment] 2022-12-28 17:54
I believe that #112001 still needs to be merged to complete the fix be basic bug reported by #111828
#112568 was closed with the comment by @werainkhatri to this effect.

You can see by the diffs of #112001 to current master that (without merging #112001) the bug still exists in `action_chip.dart`, `chip.dart`, `filter_chip.dart`, and `input_chip.dart` classes. 

#112001 also adds testing these classes - although @werainkhatri described some refinement of some the existing tests (if I remember correctly by adding a function to remove some replicated code in some of the tests).  I have not had the time to implement his request.

**Comment by Hixie** [comment] 2023-08-29 22:57
A partial patch for this exists in https://github.com/flutter/flutter/pull/112001.

**Comment by TahaTesser** [comment] 2023-09-29 09:01
> A partial patch for this exists in #112001.

While a newer chip issue https://github.com/flutter/flutter/issues/135595, I found this `iconTheme` issue to be fixed.

I'll land this with some improvements and updated tests. The partial patch overrides the default icon size in the chip widgets when only providing icon color.

**Closed** 2023-10-12 14:17 UTC
Labels: framework, f: material design, has reproducible steps, found in release: 3.3, has partial patch, found in release: 3.4, team-design, triaged-design, multiteam-retriage-candidate
