### ISSUE TITLE
Multi-line Text Input

### ISSUE THREAD

**Issue by dvdwasibi** [flutter/flutter#5534] opened 2016-08-22 18:33 UTC
Multi-line Text Input is a common use case (Email, Messages...).

It would also be useful to be able track "cursor location" in a "input-area" so that type-ahead UIs can be correct positioned.

**Comment by eseidelGoogle** [comment] 2016-08-22 19:02
Duplicate of https://github.com/flutter/flutter/issues/627.  Agreed, and thanks for the report!

**Closed by eseidelGoogle** 2016-08-22 19:02 UTC
