### ISSUE TITLE
[tool_crash] OutOfMemoryError: (null)

### ISSUE THREAD

**Issue by Lebanglibby** [flutter/flutter#160972] opened 2024-12-30 15:07 UTC
## Command
```sh
flutter run -t lib/get_fcm_token.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
OutOfMemoryError: (null)
```console
#0      new Uint8List (dart:typed_data-patch/typed_data_patch.dart:2307:3)
#1      _File.readAsBytesSync (dart:io/file_impl.dart:589:16)
#2      ForwardingFile.readAsBytesSync (package:file/src/forwarding/forwarding_file.dart:91:43)
#3      ForwardingFile.readAsBytesSync (package:file/src/forwarding/forwarding_file.dart:91:43)
#4      _calculateSha (package:flutter_tools/src/android/gradle.dart:926:32)
#5      AndroidGradleBuilder.buildGradleApp (package:flutter_tools/src/android/gradle.dart:588:36)
#6      _rootRunUnary (dart:async/zone.dart:1407:47)
#7      _CustomZone.runUnary (dart:async/zone.dart:1308:19)
#8      _FutureListener.handleValue (dart:async/future_impl.dart:163:18)
#9      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:861:45)
#10     Future._propagateToListeners (dart:async/future_impl.dart:890:13)
#11     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:736:7)
#12     _rootRun (dart:async/zone.dart:1399:13)
#13     _CustomZone.runGuarded (dart:async/zone.dart:1209:7)
#14     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1249:23)
#15     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
#16     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:185:5)
```
```console
[32m[✓][39m Flutter (Channel stable, 3.24.5, on Microsoft Windows [Version 10.0.22631.4602], locale en-BW)
    [32m•[39m Flutter version 3.24.5 on channel stable at C:\dev\flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision dec2ee5c1f (7 weeks ago), 2024-11-13 11:13:06 -0800
    [32m•[39m Engine revision a18df97ca5
    [32m•[39m Dart version 3.5.4
    [32m•[39m DevTools version 2.37.3

[32m[✓][39m Windows Version (Installed version of Windows is version 10 or higher)

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    [32m•[39m Android SDK at C:\Users\leban\AppData\Local\Android\sdk
    [32m•[39m Platform android-35, build-tools 35.0.0
    [32m•[39m Java binary at: C:\Program Files\Android\Android Studio1\jbr\bin\java
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.11+0--11852314)
    [32m•[39m All Android licenses accepted.

[31m[✗][39m Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    [33m![39m Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[33m[!][39m Visual Studio - develop Windows apps (Visual Studio Community 2022 17.12.3)
    [32m•[39m Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    [32m•[39m Visual Studio Community 2022 version 17.12.35527.113
    [31m✗[39m Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop development with C++" workload, and include these
      components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK

[33m[!][39m Android Studio (version 2023.3)
    [32m•[39m Android Studio at C:\Program Files\Android\Android Studio
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [31m✗[39m Unable to determine bundled Java version.
    [32m•[39m Try updating or re-installing Android Studio.

[32m[✓][39m Android Studio (version 2024.1)
    [32m•[39m Android Studio at C:\Program Files\Android\Android Studio1
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version openjdk version "17.0.11" 2024-04-16

[32m[✓][39m IntelliJ IDEA Community Edition (version 2024.2)
    [32m•[39m IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2024.2.4
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin version 242.22855.32

[32m[✓][39m VS Code (version 1.96.2)
    [32m•[39m VS Code at C:\Users\leban\AppData\Local\Programs\Microsoft VS Code
    [32m•[39m Flutter extension version 3.103.20241202

[32m[✓][39m Connected device (3 available)
    [32m•[39m 23129RN51X (mobile) • 49TOFIWOAMY5DYYD • android-arm    • Android 14 (API 34)
    [32m•[39m Windows (desktop)   • windows          • windows-x64    • Microsoft Windows [Version 10.0.22631.4602]
    [32m•[39m Edge (web)          • edge             • web-javascript • Microsoft Edge 131.0.2903.112

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[33m![39m Doctor found issues in 3 categories.

```

## Flutter Application Metadata
**Type**: malformed
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: null
**Creation framework version**: null
### Plugins
cloud_firestore-5.6.0
cloud_firestore_web-4.4.0
firebase_auth-5.3.4
firebase_auth_web-5.13.5
firebase_core-3.9.0
firebase_core_web-2.19.0
firebase_messaging-15.1.6
firebase_messaging_web-3.9.5
google_sign_in-6.2.2
google_sign_in_android-6.1.34
google_sign_in_ios-5.7.8
google_sign_in_web-0.12.4+3

**Comment by danagbemava-nc** [comment] 2024-12-31 08:11
Closing this as a duplicate of https://github.com/flutter/flutter/issues/133371

**Closed by danagbemava-nc** 2024-12-31 08:11 UTC
Labels: in triage
