### ISSUE TITLE
AttachToFlutterEngine Crashes When FlutterView is Removed

### ISSUE THREAD

**Issue by searchy2** [flutter/flutter#45347] opened 2019-11-21 17:05 UTC
## Steps to Reproduce
1. Open a Flutter Fragment.
2. Minimize the app.
3. Resume the app.
4. Close the Flutter Fragment in MainActivity onStart.
5. App crashes because flutterView is null.

```
java.lang.NullPointerException: Attempt to invoke virtual method 'void io.flutter.embedding.android.FlutterView.attachToFlutterEngine(io.flutter.embedding.engine.FlutterEngine)' on a null object reference
        at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate$2.run(FlutterActivityAndFragmentDelegate.java:294)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

**Target Platform:**
Android
**Target OS version/browser:**
Tested on Oreo to Q
**Devices:**
Simulators

## Logs
```
[√] Flutter (Channel master, v1.12.5-pre.51, on Microsoft Windows [Version 10.0.17763.864], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.3.5)
[√] Android Studio (version 3.5)
[!] VS Code (version 1.32.3)
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[√] Connected device (2 available)
```

The solution is to check if flutterView exists before attempting to attach engine.
![MaxthonSnap20191121110540](https://user-images.githubusercontent.com/19896174/69359790-dfcda480-0c4e-11ea-85bd-54ed9347c762.png)

**Comment by searchy2** [comment] 2019-12-21 18:55
Any update? This is a very unfortunate crash that can easily be fixed by a null check.

**Comment by singun-lxd** [comment] 2020-02-09 12:28
I've meet the same crash...

**Comment by qylshy** [comment] 2020-02-24 06:26
I've meet the same crash

**Comment by kmfish** [comment] 2020-03-13 14:27
I've meet the same crash

**Comment by EliuTimana** [comment] 2020-04-25 21:25
Any news? I've got this exception in production, play store is reporting the issue:
```
Huawei HUAWEI P smart 2019 (HWPOT-H), 2816MB RAM, Android 9
Report 1 of 1
java.lang.NullPointerException: 
  at io.flutter.embedding.android.FlutterView.attachToFlutterEngine (FlutterView.java:602)
  at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate$2.run (FlutterActivityAndFragmentDelegate.java:294)
  at android.os.Handler.handleCallback (Handler.java:907)
  at android.os.Handler.dispatchMessage (Handler.java:105)
  at android.os.Looper.loop (Looper.java:216)
  at android.app.ActivityThread.main (ActivityThread.java:7625)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:524)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:987)
```

**Comment by xster** [comment] 2020-10-19 20:41
I'm tentatively closing this issue since we've deprecated the old Android embedding java classes for a new embedding. See flutter.dev/go/android-project-migration. I believe this issue should no longer be present in the new embedding. Please re-open this issue if this reproduces on the new Java classes.

**Closed by xster** 2020-10-19 20:41 UTC
Labels: P4, a: existing-apps, dependency: android, e: embedder, engine, platform-android, severe: crash
