### ISSUE TITLE
Indents are wrong when there's a CheckedPopupMenuItem next to a PopupMenuItem

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#2351] opened 2016-03-02 23:21 UTC
Look at the stocks app's menu. The text doesn't line up because the item with a checkbox is hugely indented compared to the others. It looks bad.

cc @HansMuller

**Comment by HansMuller** [comment] 2016-03-02 23:44
I think it's create per the MD spec however the checked menu item should probably be separated from the ordinary ones with a divider.

https://www.google.com/design/spec/components/menus.html#menus-menu-items

**Comment by Hixie** [comment] 2016-03-02 23:51
Huh, it seems to vary. See for example the second screenshot in that file. Some of those items (especially "Mode") don't take a checkbox, and yet they're indented.

Maybe it's per-section, either indent all (if any have a checkbox) or none (if none do)? That ought to be fun to implement... (Actually it's probably relatively easy, using a custom multichild layout delegate.)

**Comment by HansMuller** [comment] 2016-03-03 00:03
I think the second screenshot's "Mode" item is an unchecked item like the screenshot with "Custom:1.2" farther down the page.

I think what's going on here is that the Check appears if you select a submenu item, and the submenu item's value shows up in the menu item's label.

We're not supporting submenus for now.

![submenu](https://cloud.githubusercontent.com/assets/1377460/13479983/a4ecb868-e08f-11e5-85f8-793f376bcabf.png)

![custom](https://cloud.githubusercontent.com/assets/1377460/13480035/f33f2c76-e08f-11e5-8691-f5a84e59ecac.png)

**Comment by Hixie** [comment] 2016-03-03 00:07
Single/1.15/Double/Custom are a variety of options you can toggle. Under Custom, you can also select specific values. That's why Custom has a check mark there.
Mode, however, is just a simple submenu. It'd never be checked.
At least, that's my understanding based on the behaviour of the app this is based on (Google Docs).

**Comment by HansMuller** [comment] 2016-03-03 00:14
You're right about the Google Docs Mode menu.  Will try and make the Stocks menu look less insane.

**Comment by zoechi** [comment] 2019-01-18 08:33
![image](https://user-images.githubusercontent.com/405837/51374675-0c330480-1b04-11e9-81cb-d560e596ee47.png)

```
[✓] Flutter (Channel dev, v1.1.9, on Mac OS X 10.14.1 18B75, locale en-AT)
```

**Comment by TahaTesser** [comment] 2020-09-04 12:35
duplicate of https://github.com/flutter/flutter/issues/3561
Keep the open issue until confirmation

![flutter_01](https://user-images.githubusercontent.com/48603081/92239732-1e300980-eed9-11ea-9826-4148d8cdaced.png)
<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Material App',
      theme: ThemeData.dark(),
      home: CheckboxInPopupMenu(),
    );
  }
}

class CheckboxInPopupMenu extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: Text("Checkbox in PopupMenuButton Example"),
        ),
        body: Center(
          child: PopupMenuButton(
            child: Text("Checkbox PopupMenuBotton"),
            itemBuilder: (context) => [
              CheckedPopupMenuItem(
                checked: true,
                child: Text("InduceSmile.com"),
              ),
              CheckedPopupMenuItem(
                child: Text("Flutter.io"),
              ),
              CheckedPopupMenuItem(
                child: Text("Google.com"),
              ),
            ],
          ),
        ));
  }
}


```

</details> 

<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel master, 1.22.0-10.0.pre.82, on Mac OS X 10.15.6 19G2021,
    locale en-GB)
    • Flutter version 1.22.0-10.0.pre.82 at
      /Users/tahatesser/Code/flutter_master
    • Framework revision 9248fda410 (11 hours ago), 2020-09-03 16:08:01 -0700
    • Engine revision 3f05b521b9
    • Dart version 2.10.0 (build 2.10.0-86.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.7, Build version 11E801a
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.48.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.0

[✓] Connected device (4 available)
    • iPhone 11 (mobile) • EDB19945-0B9F-4A6E-BAA1-425E68E3B6D6 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-13-7 (simulator)
    • macOS (desktop)    • macos                                • darwin-x64
      • Mac OS X 10.15.6 19G2021
    • Web Server (web)   • web-server                           • web-javascript
      • Flutter Tools
    • Chrome (web)       • chrome                               • web-javascript
      • Google Chrome 85.0.4183.83

• No issues found!

```

</details>

**Comment by danagbemava-nc** [comment] 2024-03-26 11:43
It doesn't seem like this reproduces on the latest versions of flutter. 
See the screenshots below

Closing this as it seems it has been fixed.

If I am wrong, kindly reopen this issue. 

Thank you

| with guidelines | without guidelines |
| -- | -- |
| <img width="400" alt="Screenshot 2024-03-26 at 11 29 28" src="https://github.com/flutter/flutter/assets/88313112/5afdf26a-005c-414e-9e9d-874481441f89"> | <img width="400" alt="Screenshot 2024-03-26 at 11 41 18" src="https://github.com/flutter/flutter/assets/88313112/23451831-91fe-46f9-962f-0a87b854b122"> |

<details>
<summary>sample used</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Material App',
      theme: ThemeData.dark(useMaterial3: false),
      home: const CheckboxInPopupMenu(),
    );
  }
}

class CheckboxInPopupMenu extends StatelessWidget {
  const CheckboxInPopupMenu({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text("Checkbox in PopupMenuButton Example"),
      ),
      body: Center(
        child: PopupMenuButton(
          child: const Text("Checkbox PopupMenuBotton"),
          itemBuilder: (context) => [
            const CheckedPopupMenuItem(
              checked: true,
              child: Text("InduceSmile.com"),
            ),
            const PopupMenuItem(child: Text('Something')),
            const CheckedPopupMenuItem(
              child: Text("Flutter.io"),
            ),
            const CheckedPopupMenuItem(
              child: Text("Google.com"),
            ),
          ],
        ),
      ),
    );
  }
}
```
</details>


<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.19.4, on macOS 14.3.1 23D60 darwin-arm64, locale en-GB)
    • Flutter version 3.19.4 on channel stable at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 68bfaea224 (6 days ago), 2024-03-20 15:36:31 -0700
    • Engine revision a5c24f538d
    • Dart version 3.3.2
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Users/nexus/Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode-15.3.0.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Users/nexus/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.2.5)
    • IntelliJ at /Users/nexus/Applications/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 77.2.2
    • Dart plugin version 232.10286

[✓] VS Code (version 1.87.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.84.0

[✓] Connected device (4 available)
    • Pixel 7 (mobile) • 28291FDH2001SA            • android-arm64  • Android 14 (API 34)
    • Nexus (mobile)   • 00008020-001875E83A38002E • ios            • iOS 17.4.1 21E236
    • macOS (desktop)  • macos                     • darwin-arm64   • macOS 14.3.1 23D60 darwin-arm64
    • Chrome (web)     • chrome                    • web-javascript • Google Chrome 123.0.6312.59
    ! Error: Browsing on the local area network for Dean’s iPad. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

```
[!] Flutter (Channel master, 3.21.0-14.0.pre.29, on macOS 14.3.1 23D60 darwin-arm64, locale en-GB)
    • Flutter version 3.21.0-14.0.pre.29 on channel master at /Users/nexus/dev/sdks/flutters
    ! Warning: `flutter` on your path resolves to /Users/nexus/dev/sdks/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/nexus/dev/sdks/flutters. Consider adding /Users/nexus/dev/sdks/flutters/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/nexus/dev/sdks/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/nexus/dev/sdks/flutters. Consider adding /Users/nexus/dev/sdks/flutters/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a8345d5399 (10 hours ago), 2024-03-25 21:07:30 -0400
    • Engine revision 3c881b75cc
    • Dart version 3.4.0 (build 3.4.0-268.0.dev)
    • DevTools version 2.34.0-dev.12
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Users/nexus/Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode-15.3.0.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Users/nexus/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.2.5)
    • IntelliJ at /Users/nexus/Applications/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 77.2.2
    • Dart plugin version 232.10286

[✓] VS Code (version 1.87.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.84.0

[✓] Connected device (5 available)
    • Pixel 7 (mobile)                • 28291FDH2001SA            • android-arm64  • Android 14 (API 34)
    • Nexus (mobile)                  • 00008020-001875E83A38002E • ios            • iOS 17.4.1 21E236
    • macOS (desktop)                 • macos                     • darwin-arm64   • macOS 14.3.1 23D60 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad     • darwin         • macOS 14.3.1 23D60 darwin-arm64
    • Chrome (web)                    • chrome                    • web-javascript • Google Chrome 123.0.6312.59
    ! Error: Browsing on the local area network for Dean’s iPad. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

```
</details>

**Closed by danagbemava-nc** 2024-03-26 11:43 UTC
Labels: framework, f: material design, has reproducible steps, P3, found in release: 1.22, team-design, triaged-design
