### ISSUE TITLE
Can't run in Xcode 10 & iOS 12

### ISSUE THREAD

**Issue by 39499740** [flutter/flutter#21968] opened 2018-09-18 02:16 UTC
Xcode's output:
↳
    error: Multiple commands produce '/Users/haoyi/TempProject/emp/build/ios/Debug-iphoneos/Runner.app/Frameworks/Flutter.framework':
    1) Target 'Runner' has copy command from '/Users/haoyi/TempProject/emp/ios/Flutter/Flutter.framework' to '/Users/haoyi/TempProject/emp/build/ios/Debug-iphoneos/Runner.app/Frameworks/Flutter.framework'
    2) That command depends on command in Target 'Runner': script phase “[CP] Embed Pods Frameworks”
    warning: The iOS deployment target is set to 4.3, but the range of supported deployment target versions for this platform is 8.0 to 12.0. (in target 'image_picker')
    warning: ignoring duplicated output file: '/Users/haoyi/TempProject/emp/build/ios/Debug-iphoneos/Runner.app/Frameworks/Flutter.framework' (in target 'Runner')
    note: Using new build systemnote: Planning buildnote: Constructing build description

Xcode Version 10.0 (10A255)

➜  ~ flutter doctor -v
[✓] Flutter (Channel beta, v0.7.3, on Mac OS X 10.13.6 17G65, locale zh-Hans-CN)
    • Flutter version 0.7.3 at /Users/haoyi/flutter
    • Framework revision 3b309bda07 (3 weeks ago), 2018-08-28 12:39:24 -0700
    • Engine revision af42b6dc95
    • Dart version 2.1.0-dev.1.0.flutter-ccb16f7282

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/haoyi/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.0, Build version 10A255
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.0

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 27.1.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 28.0.4
    • Dart plugin version 182.4323.44

[✓] VS Code (version 1.27.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.18.0

[✓] Connected devices (3 available)
    • 郝怿的 iPhone    • 6d4a90c14794752f1d56db848716a8c609b7448b • ios • iOS 12.0
    • iPhone XS     • A4E0A17F-6E4A-48C0-8AE0-B16340BFF203     • ios • iOS 12.0 (simulator)
    • iPhone XS Max • ADB38EB8-99FD-4908-BB20-8F53BA388661     • ios • iOS 12.0 (simulator)

• No issues found!

**Comment by hungrymonkey** [comment] 2018-09-18 02:39
Duplicate of https://github.com/flutter/flutter/issues/20685#issuecomment-421511890

**Comment by dnfield** [comment] 2018-09-18 03:55
Closing as duplicate of #20685.  @39499740 please let us know if you think you have something different on your hands here.

**Closed by dnfield** 2018-09-18 03:55 UTC

**Comment by asad175** [comment] 2019-06-12 09:06
One option which solved my issue is to changing build system to legacy build system. Please follow the following steps in Xcode 10+

<img width="2048" alt="Screen Shot 2019-06-12 at 1 00 42 PM" src="https://user-images.githubusercontent.com/43041540/59338128-dbea3d80-8d12-11e9-8477-81a857d09e53.png">

<img width="2048" alt="Screen Shot 2019-06-12 at 1 00 55 PM" src="https://user-images.githubusercontent.com/43041540/59338143-e278b500-8d12-11e9-9d76-4d27946b33b9.png">
