### ISSUE TITLE
flutter packages get -- failed on slow connection

### ISSUE THREAD

**Issue by stevemessick** [flutter/flutter#10581] opened 2017-06-08 15:48 UTC
```
.../flutter/bin/flutter --no-color packages get
Running "flutter packages get" in sudoku...
Connection terminated during handshake
pub get failed (1)
Process finished with exit code 1
```
I'm connected by satellite internet, so it is quite slow. It is good enough to create this issue, though. If this is strictly a pub issue let me know and I'll file it there.

**Comment by sethladd** [comment] 2017-06-08 15:52
Sorry for the troubles. "Connection terminated during handshake" sounds like a networking issue. I'm tempted to close this because `packages get` can do a lot of networking connections, and if there's a very spotty internet connection, it may fail.

**Comment by Hixie** [comment] 2017-06-08 18:14
Specifically, this is a dupe of https://github.com/flutter/flutter/issues/9898.

**Closed by Hixie** 2017-06-08 18:14 UTC
