### ISSUE TITLE
[video_player] Video not visible on [Mac | iOS] Safari when inside a ClipRRect in CanvasKit mode.

### ISSUE THREAD

**Issue by YonyElm** [flutter/flutter#80401] opened 2021-04-14 01:30 UTC
## The Problem
I want to be able to play videos on MacOS using Safari together with my Flutter application.
I had this feature working for a while until it stopped
I have noticed that by choosing different versions of flutter (without changing libraries) I get the video back.
Currently, Flutter 2.x doesn't let me enable this feature - and it prevents me from moving to flutter 2.x

Note: The application and video work as expected on mobile-web (chrome and safari) and on Desktop-web (chrome) and on mobile-IOS and mobile-Android

## Steps to Reproduce

1. Create a flutter web application that plays a video when the website loads.
    1. I used video_player plugin
    2. In my case the source of the video is a link to .mp4 file (I checked that if I copy the link and play it in the safari browser I get a working video)
    3. In my case the default video controllers are hidden, and I'm using a videoNotifier to control the video
2. Deploy the application to Firebase Hosting
3. Acess the web application using MacOS + Safari (I don't have a similar issue on Chrome/Mobile)
4. Play the video, and the bug should show up - you will hear sound, but the video won't be rendered

Flutter versions in which the bug doesn't happen: `1.25.0-8.2.pre` / `1.25.0-8.3.pre`
Flutter versions in which the bug happen: `1.26.0-17.2.pre` / `1.26.0-17.8.pre` / `1.27.0-8.0.pre` / `2.0.3` / `2.0.4` /  `2.1.0-12.2.pre`

So I guess the key difference happened in the move from `1.25.0-8.3.pre` to `1.26.0-17.2.pre`

```
Analyzing app...                                                   
No issues found! (ran in 20.4s)
```

```

[✓] Flutter (Channel stable, 2.0.4, on macOS 11.2.3 20D91 darwin-arm, locale en-US)
    • Flutter version 2.0.4 at /Users/---/programs/flutter
    • Framework revision b1395592de (12 days ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/---/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 89.0.4389.128

• No issues found!
```

**Comment by TahaTesser** [comment] 2021-04-14 08:03
Hi @YonyElm 

Can you please provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) using the `video_player` package


I just tried to reproduce using official sample and tried it locally in safari with `flutter run -d web-server` and also hosted on Netlify, app loads, video plays

<details> 
<summary>code sample</summary> 

```dart
import 'package:video_player/video_player.dart';
import 'package:flutter/material.dart';

void main() => runApp(VideoApp());

class VideoApp extends StatefulWidget {
  @override
  _VideoAppState createState() => _VideoAppState();
}

class _VideoAppState extends State<VideoApp> {
  VideoPlayerController _controller;

  @override
  void initState() {
    super.initState();
    _controller = VideoPlayerController.network(
        'https://flutter.github.io/assets-for-api-docs/assets/videos/bee.mp4')
      ..initialize().then((_) {
        // Ensure the first frame is shown after the video is initialized, even before the play button has been pressed.
        setState(() {});
      });
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Video Demo',
      home: Scaffold(
        body: Center(
          child: _controller.value.initialized
              ? AspectRatio(
                  aspectRatio: _controller.value.aspectRatio,
                  child: VideoPlayer(_controller),
                )
              : Container(),
        ),
        floatingActionButton: FloatingActionButton(
          onPressed: () {
            setState(() {
              _controller.value.isPlaying
                  ? _controller.pause()
                  : _controller.play();
            });
          },
          child: Icon(
            _controller.value.isPlaying ? Icons.pause : Icons.play_arrow,
          ),
        ),
      ),
    );
  }

  @override
  void dispose() {
    super.dispose();
    _controller.dispose();
  }
}

``` 

</details>

```yaml
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  video_player: ^1.0.1
```




Thank you

Related issues
https://github.com/flutter/flutter/issues/61705
https://github.com/flutter/flutter/issues/58527
https://github.com/flutter/flutter/issues/47030

**Comment by YonyElm** [comment] 2021-04-16 01:22
I will create a sample code and will give you an update when done.

**Comment by peerwaya** [comment] 2021-04-20 09:58
@ditman I think this issue is affected by #80524 . I have experienced this with the video player example for web. it does not work on safari until you minimize the browser and maximize it again. You can try the example to see the effect

**Comment by peerwaya** [comment] 2021-04-20 10:00
@TahaTesser you just run the video player example for web on safari on macos

**Comment by TahaTesser** [comment] 2021-04-20 11:05
@peerwaya 
Thanks, I was using older version, I can reproduce the issue using newest version and updated https://github.com/flutter/flutter/issues/80401#issuecomment-819318138

**Comment by ditman** [comment] 2021-04-20 16:57
IIRC 1.26 was the internal version for 2.0 while it wasn't announced, so the change makes sense.

Quick question @YonyElm, can you visit your deployed app with the Safari DevTools open, and see if there are any errors reported in the JS Console, or the Network panel?

**Comment by ditman** [comment] 2021-04-20 17:18
I am not sure this is a matter of the SLOT rendering, or just the video_player having some quirks in Safari (like auto-play not working because the video might have sound, or similar!)

A quick thing to test: have you tried muting the video (setting volume to `0.0`) before calling play?

**Comment by YonyElm** [comment] 2021-04-20 17:31
@ditman 
I don't see any errors in the JS console.
Can you guide me to a type of error you would think I can see on the Network panel? - I don't see something obvious
I do see few files with "An error occurred trying to reload the resource", but afterwards they are being reloaded
Is that helping?
![image](https://user-images.githubusercontent.com/34646433/115438978-e903cd80-a1c2-11eb-86e6-53fe5a2b17e3.png)

The issue happens in a muted video as well as not muted.
I am aware of auto-play rules, and my code does comply with it (and works fine for v1.25)
Also usually video won't work at all in case of auto-play rules has issues, in my case when pressing PLAY sound does play, only the video doesn't render.

Also, in my case video is not working on safari for MacOS even after minimizing and maximizing the browser - per @peerwaya suggestion
CC @TahaTesser

**Comment by YonyElm** [comment] 2021-04-20 21:58
@TahaTesser @ditman 

I took the time and investigated the issue I see deeper, and I discovered something new.
Flutter 2.0 does show videos on Safari MacOS
BUT - if you place the video widget inside `ClipRRect` the video is no longer rendering.
in case this thread is not the right place for this bug, please guide me towards the right location.

Here is a sample code to reproduce:
``` 
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:video_player/video_player.dart';

void main() {
  runApp(
    MaterialApp(
      home: _App(),
    ),
  );
}

class _App extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return DefaultTabController(
      length: 1,
      child: Scaffold(
        body:
            _BumbleBeeRemoteVideo(),
      ),
    );
  }
}

class _BumbleBeeRemoteVideo extends StatefulWidget {
  @override
  _BumbleBeeRemoteVideoState createState() => _BumbleBeeRemoteVideoState();
}

class _BumbleBeeRemoteVideoState extends State<_BumbleBeeRemoteVideo> {
  late VideoPlayerController _controller;


  @override
  void initState() {
    super.initState();
    _controller = VideoPlayerController.network(
      'https://flutter.github.io/assets-for-api-docs/assets/videos/bee.mp4',
    );

    playThis();
  }

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return SingleChildScrollView(
      child: Column(
        children: <Widget>[
          // Container(padding: const EdgeInsets.only(top: 20.0)),
          // const Text('With remote mp4'),
          Container(
            padding: const EdgeInsets.all(20),
            child: AspectRatio(
              aspectRatio: _controller.value.aspectRatio,
              // Removing ClipRRect will make video work on Safari on MacOS
              child: ClipRRect(
                borderRadius: BorderRadius.circular(10.0),
                child: VideoPlayer(_controller),
              ),
            ),
          ),
        ],
      ),
    );
  }

  Future<void> playThis() async {
    await _controller.setLooping(true);
    await _controller.setVolume(0.0);
    await _controller.initialize();
    _controller.play();
  }
}
```

Removing `ClipRRect` will present the video as expected.
Again - the bug shows up only on Safari MacOS

**Comment by ditman** [comment] 2021-04-20 22:07
@YonyElm is the video in your app inside a ClipRRect? That sounds like a legitimate bug.

What `--web-render` parameter are you using? `auto` (not specified), `html` or `canvaskit`?

**Comment by YonyElm** [comment] 2021-04-20 22:15
@ditman 
I probably use `auto`
`flutter build web -t lib/main.dart`
 +
 `autoplay=1` in order to make the video work is IOS Safari
 
 Yes, the video in my app is inside a ClipRRect - causing the issue.
 Checked it in the application and in the submitted sample - works the same
 Removing ClipRRect solved the issue

**Comment by ditman** [comment] 2021-04-20 23:01
There's something about the clip-path CSS that Safari doesn't like:

<img width="1283" alt="Screen Shot 2021-04-20 at 3 49 03 PM" src="https://user-images.githubusercontent.com/1255594/115473235-36e2fa80-a1f0-11eb-8ccf-605a84256694.png">

After removing it...

<img width="1291" alt="Screen Shot 2021-04-20 at 3 49 23 PM" src="https://user-images.githubusercontent.com/1255594/115473245-3cd8db80-a1f0-11eb-8abc-0fc5b01ba047.png">

Note that the clip-path url is valid (I'd remove the `"`, but when I do manually it doesn't work either), and the syntax is correct too, according to [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/clip-path#complete_example). Odd.

**Comment by ditman** [comment] 2021-04-20 23:02
(PS: After digging a little bit more, this doesn't seem to be related to #80524)

**Comment by TahaTesser** [comment] 2021-04-21 11:28
I was able to reproduce the issue using the official sample with `AspectRatio`, which looks like it uses the same code as ClipRRect, and yes it does look like it only reproduces on `canvaskit`,I would double-check next time) 


### Preview
| `canvaskit` | `html`  |
| --------------- | --------------- |
<img src="https://user-images.githubusercontent.com/48603081/115546363-9d7a1e00-a2ad-11eb-9762-ecb0f0bbc4ac.gif" height="200" /> | <img src="https://user-images.githubusercontent.com/48603081/115546412-ad91fd80-a2ad-11eb-99cd-dce28a56149f.gif" height="200" /> |




<details> 
<summary>code sample</summary> 

```dart
import 'package:video_player/video_player.dart';
import 'package:flutter/material.dart';

void main() => runApp(VideoApp());

class VideoApp extends StatefulWidget {
  @override
  _VideoAppState createState() => _VideoAppState();
}

class _VideoAppState extends State<VideoApp> {
  VideoPlayerController _controller;
  @override
  void initState() {
    super.initState();
    _controller = VideoPlayerController.network(
        'https://flutter.github.io/assets-for-api-docs/assets/videos/bee.mp4')
      ..initialize().then((_) {
        // Ensure the first frame is shown after the video is initialized, even before the play button has been pressed.
        setState(() {});
      });
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Video Demo',
      home: Scaffold(
        body: Center(
          child: _controller.value.isInitialized
              ? AspectRatio(
                  aspectRatio: _controller.value.aspectRatio,
                  child: VideoPlayer(_controller),
                )
              : Container(),
        ),
        floatingActionButton: FloatingActionButton(
          onPressed: () {
            setState(() {
              _controller.value.isPlaying
                  ? _controller.pause()
                  : _controller.play();
            });
          },
          child: Icon(
            _controller.value.isPlaying ? Icons.pause : Icons.play_arrow,
          ),
        ),
      ),
    );
  }

  @override
  void dispose() {
    super.dispose();
    _controller.dispose();
  }
}

``` 

</details>

**Comment by ditman** [comment] 2021-07-21 23:10
/cc @ferhatb this was the issue I brought up during our weekly meeting. This showed up right before the `slot` rendering was A Thing (probably the slot rendering made this problem worse).

Since this was a canvaskit-only issue, no shadow-dom was used whatsoever.

**Comment by viktor-ohanyan** [comment] 2021-09-11 10:04
I faced the same issue.
Is there any solution or workaround?

**Comment by ditman** [comment] 2021-09-13 16:59
@viktor-ohanyan the only workaround for now seems to be to use `--web-renderer html` when running/building your app (this change is fairly drastic on what flutter does with your app, so it might also bring other unintended consequences!)

**Comment by doppio** [comment] 2022-01-22 05:16
I'd be happy to try to fix this and submit a pull request if anyone knows where to start with this.

Unfortunately, switching back to HTML renderer is not an option for us. Lots of Flutter bugs have bounced us between the two renderers, but ultimately, CanvasKit is significantly less broken for us.

**Comment by ditman** [comment] 2022-01-31 20:24
@doppio it makes sense that this fails in any iOS browser, if it fails on iOS Safari. All iOS browsers must use the same Safari webview internally, so the same bug will be shared across all browsers.

I'll update the original issue with the iOS info. Thanks for sharing your workaround!

**Comment by Oleh-Sv** [comment] 2022-09-02 18:24
@ditman  For fix this problem we just need to add width, height to flt_clip tag. I tried to create PR for engine, but code that creates html looks like mess. If you can add height, width to flutter engine do it please.

![Uploading Screenshot 2022-09-02 at 19.24.33.png…]()

**Comment by ditman** [comment] 2022-09-02 18:47
@Oleh-Sv very good information!

I don't think we want to do `clip-path:path("...")` because of the way all paths are written into a single SVG container now, but the width/height trick is definitely doable.

Thanks for taking the time to report your findings, keep it up!

**Comment by yjbanov** [comment] 2022-09-06 22:57
This seems to be the most relevant WebKit issue: https://bugs.webkit.org/show_bug.cgi?id=200381

I can reproduce this with plain HTML/JS without Flutter Web:

- Repro: https://jsfiddle.net/yjbanov/nh9jzLba/40/
- Workaround (provided by @Oleh-Sv) : https://jsfiddle.net/yjbanov/nh9jzLba/42/

**Comment by Oleh-Sv** [comment] 2022-09-09 11:41
@yjbanov Are you going to wait fix from webkit side?

**Comment by Terranic** [comment] 2022-09-13 10:49
Is there any update? Also just stumbled on this error, video not showing in Safari with ClipRRect and web-renderer canvaskit using flutter 3.3.1.

**Comment by yjbanov** [comment] 2022-09-29 17:02
Fixed by https://github.com/flutter/engine/pull/35948

**Closed by yjbanov** 2022-09-29 17:02 UTC
Labels: plugin, p: first party, platform-web, p: video_player, e: web_canvaskit, has reproducible steps, browser: safari-macos, P3, found in release: 2.5, found in release: 2.6
