### ISSUE TITLE
[tool_crash] ProcessException: No such file or directory Command: /home/user/myapp/android/gradlew, OS error code: 2

### ISSUE THREAD

**Issue by drshravan** [flutter/flutter#144874] opened 2024-03-09 10:42 UTC
## Command
```
flutter build apk
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ProcessException: No such file or directory Command: /home/user/myapp/android/gradlew, OS error code: 2
```
#0      _ProcessImpl._start (dart:io-patch/process_patch.dart:401:33)
#1      Process.start (dart:io-patch/process_patch.dart:38:20)
#2      LocalProcessManager.start (package:process/src/interface/local_process_manager.dart:42:22)
#3      ErrorHandlingProcessManager.start.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:689:24)
#4      _run (package:flutter_tools/src/base/error_handling_io.dart:559:20)
#5      ErrorHandlingProcessManager.start (package:flutter_tools/src/base/error_handling_io.dart:688:12)
#6      _DefaultProcessUtils.start (package:flutter_tools/src/base/process.dart:428:28)
#7      _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart:448:35)
#8      AndroidGradleBuilder.buildGradleApp (package:flutter_tools/src/android/gradle.dart:493:38)
#9      AndroidGradleBuilder.buildApk (package:flutter_tools/src/android/gradle.dart:244:11)
#10     BuildApkCommand.runCommand (package:flutter_tools/src/commands/build_apk.dart:116:27)
<asynchronous suspension>
#11     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1297:27)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#13     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:333:9)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#16     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:285:5)
<asynchronous suspension>
#17     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:115:9)
```
```
[32m[✓][39m Flutter (Channel stable, 3.13.4, on Linux 5.4.0-1104-gke, locale en_US.UTF-8)
    [32m•[39m Flutter version 3.13.4 on channel stable at /opt/flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision 367f9ea16b (6 months ago), 2023-09-12 23:27:53 -0500
    [32m•[39m Engine revision 9064459a8b
    [32m•[39m Dart version 3.1.2
    [32m•[39m DevTools version 2.25.0

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    [32m•[39m Android SDK at /opt/android
    [32m•[39m Platform android-33, build-tools 30.0.3
    [32m•[39m ANDROID_SDK_ROOT = /opt/android
    [32m•[39m Java binary at: /usr/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.7+7-nixos)
    [32m•[39m All Android licenses accepted.

[31m[✗][39m Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    [33m![39m Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[32m[✓][39m Linux toolchain - develop for Linux desktop
    [32m•[39m clang version 16.0.6
    [32m•[39m cmake version 3.27.7
    [32m•[39m ninja version 1.11.1
    [32m•[39m pkg-config version 0.29.2

[33m[!][39m Android Studio (not installed)
    [32m•[39m Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[32m[✓][39m Connected device (1 available)
    [32m•[39m Linux (desktop) • linux • linux-x64 • Linux 5.4.0-1104-gke
    [33m![39m Device emulator-5554 is not authorized.
      You might need to check your device for an authorization dialog.
    [33m![39m Device localhost:5555 is not authorized.
      You might need to check your device for an authorization dialog.

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[33m![39m Doctor found issues in 2 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 367f9ea16bfae1ca451b9cc27c1366870b187ae2
### Plugins
firebase_core-2.24.2
firebase_core_web-2.10.0

**Comment by huycozy** [comment] 2024-03-11 06:22
Closing as a duplicate of https://github.com/flutter/flutter/issues/108087.

**Closed by huycozy** 2024-03-11 06:22 UTC
Labels: in triage
