### ISSUE TITLE
Bug: Line Wrapping broken when highlighting words

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [flutter/flutter#81723] opened 2021-04-11 18:55 UTC
## Bug description

When you **highlight** part of a word, _**line wrapping**_ will break for that word. That is without highlighting, the line would wrap around the word and with highlighting, it **splits the word** in half.

### Example

With highlighting, the word "color" is split in half:

https://user-images.githubusercontent.com/19204050/114316890-167eb600-9af5-11eb-8a0f-d88c3c9c97d1.mov

Without highlighting, it works just fine:

https://user-images.githubusercontent.com/19204050/114316901-20081e00-9af5-11eb-85a7-6032aec4d7f6.mov

### Use case

You might say that this is never a use case in practice, however, there is actually one case that happens **very often** and because of this bug, it makes the app using the package look somewhat ugly:

<img width="266" alt="Screen Shot 2021-04-11 at 18 34 45" src="https://user-images.githubusercontent.com/19204050/114316930-3dd58300-9af5-11eb-897a-71cf7fde2d63.png">

Whenever you have a highlighted word at the end of a sentence, it will be followed by a period that is not highlighted and this is when you will see the bug, a lot.

## Reproduction

Use the `MarkdownBody` widget with the following data:

* `Paragraph is split at the **color**.`
* `Paragraph is split at the **col**or.`

In both cases, you should be able to reproduce the behavior by wrapping the body in a `SizedBox` and altering the `width` to just the right value. The alternative is resizing the window on desktop / web :)

**Comment by TahaTesser** [comment] 2021-09-03 13:28
Hi @creativecreatorormaybenot 
I'm unable to reproduce the latest version of the package with code lines provided on the web or desktop  using `MarkdownBody`

<details> 
<summary>minimal code sample</summary> 

```dart
// Copyright 2013 The Flutter Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

import 'package:flutter/material.dart';
import 'package:flutter_markdown/flutter_markdown.dart';
import '../shared/markdown_demo_widget.dart';

// ignore_for_file: public_member_api_docs

const String _data = '''
# Minimal Markdown Test
---
This is a simple Markdown test. Provide a text string with Markdown tags
to the Markdown widget and it will display the formatted output in a scrollable
widget.

Paragraph is split at the color.

Paragraph is split at the **color**.

Paragraph is split at the **col**or.


## Section 1
Maecenas eget **arcu egestas**, mollis ex vitae, posuere magna. Nunc eget
 aliquam tortor. Vestibulum porta sodales efficitur. Mauris interdum turpis
 eget est condimentum, vitae porttitor diam ornare.

### Subsection A
Sed et massa finibus, blandit massa vel, vulputate velit. Vestibulum vitae
venenatis libero. ***Curabitur sem lectus, feugiat eu justo in, eleifend
accumsan ante.*** Sed a fermentum elit. Curabitur sodales metus id mi ornare,
in ullamcorper magna congue.
''';

const String _notes = """
# Minimal Markdown Demo
---

## Overview

The simplest use case that illustrates how to make use of the
flutter_markdown package is to include a Markdown widget in a widget tree
and supply it with a character string of text containing Markdown formatting
syntax. Here is a simple Flutter app that creates a Markdown widget that
formats and displays the text in the string _markdownData. The resulting
Flutter app demonstrates the use of headers, rules, and emphasis text from
plain text Markdown syntax.

## Usage

The code sample below demonstrates a simple Flutter app with a Markdown widget.

```
import 'package:flutter/material.dart';
import 'package:flutter_markdown/flutter_markdown.dart';

const String _markdownData = \"""
# Minimal Markdown Test
---
This is a simple Markdown test. Provide a text string with Markdown tags
to the Markdown widget and it will display the formatted output in a
scrollable widget.

## Section 1
Maecenas eget **arcu egestas**, mollis ex vitae, posuere magna. Nunc eget
aliquam tortor. Vestibulum porta sodales efficitur. Mauris interdum turpis
eget est condimentum, vitae porttitor diam ornare.

### Subsection A
Sed et massa finibus, blandit massa vel, vulputate velit. Vestibulum vitae
venenatis libero. **__Curabitur sem lectus, feugiat eu justo in, eleifend
accumsan ante.__** Sed a fermentum elit. Curabitur sodales metus id mi
ornare, in ullamcorper magna congue.
\""";

void main() {
  runApp(
    MaterialApp(
      title: "Markdown Demo",
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Simple Markdown Demo'),
        ),
        body: SafeArea(
          child: Markdown(
            data: _markdownData,
          ),
        ),
      ),
    ),
  );
}
```
""";

class MinimalMarkdownDemo extends StatelessWidget
    implements MarkdownDemoWidget {
  const MinimalMarkdownDemo({Key? key}) : super(key: key);

  static const String _title = 'Minimal Markdown Demo';

  @override
  String get title => MinimalMarkdownDemo._title;

  @override
  String get description => 'A minimal example of how to use the Markdown '
      'widget in a Flutter app.';

  @override
  Future<String> get data => Future<String>.value(_data);

  @override
  Future<String> get notes => Future<String>.value(_notes);

  @override
  Widget build(BuildContext context) {
    return const MarkdownBody(
      data: _data,
    );
  }
}

``` 
	
</details>


<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.2.3, on macOS 12.0 21A5506j darwin-x64, locale en-GB)
    • Flutter version 2.2.3 at /Users/tahatesser/Code/flutter_stable
    • Framework revision f4abaa0735 (9 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/tahatesser/Code/SDK
    • Platform android-31, build-tools 30.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/SDK
    • Java binary at: /Users/tahatesser/Code/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment Temurin-11.0.12+7 (build 11.0.12+7)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode-beta.app/Contents/Developer
    • Xcode 13.0, Build version 13A5212g
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 2020.3)
    • Android Studio at /Users/tahatesser/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7621141/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] VS Code (version 1.59.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (3 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios            • iOS 15.0
    • macOS (desktop)        • macos                     • darwin-x64     • macOS 12.0 21A5506j darwin-x64
    • Chrome (web)           • chrome                    • web-javascript • Google Chrome 93.0.4577.63

! Doctor found issues in 1 category. 
```
	
</details>

**Comment by TahaTesser** [comment] 2021-09-24 12:49
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by TahaTesser** 2021-09-24 12:49 UTC
Labels: package, p: flutter_markdown

**Comment by creativecreatorormaybenot** [comment] 2021-09-25 14:48
@TahaTesser did you try to use `flutter run -d chrome` with the two samples and rezising the window horizontally?

I am not sure how I can present a sample for this since the dimensions might not always be the same (although I could try to force it).  
Otherwise, I can also post a screen recording if that helps.

**Comment by TahaTesser** [comment] 2021-09-28 11:19
@creativecreatorormaybenot 
I tried with horizontal resize, here is the result


https://user-images.githubusercontent.com/48603081/135077184-c96c338d-46ee-4925-a0d3-59a0b7645b24.mov

**Comment by creativecreatorormaybenot** [comment] 2021-09-28 11:47
@TahaTesser thanks, that is super weird. I am wondering what we are doing differently or if an update was pushed. I will not get to it for now, but I will let you know if I know anything.
