### ISSUE TITLE
A problem bewteen build_runner and chopper

### ISSUE THREAD

**Issue by vero-jasper** [flutter/flutter#77699] opened 2021-03-09 12:03 UTC
I got a problem after  **1.25.0-8.3.pre** on branch beta, when i use **chopper(3.0.6)**, the third-party package.
I created a chopper service's abstract class, and ran build_runner to generate the implement class, there was no service code in the generated code.However, this implement class will be correct before **1.26.0**.

**And this bug is still existing in stable(2.0.1)**

<img width="662" alt="2021-03-09 19 56 27" src="https://user-images.githubusercontent.com/53299212/110467192-ac4bad80-8111-11eb-9535-177245add979.png">

<img width="662" alt="2021-03-09 19 56 41" src="https://user-images.githubusercontent.com/53299212/110467216-b4a3e880-8111-11eb-8f54-fdb4a3ac1108.png">

**Comment by darshankawar** [comment] 2021-03-09 12:54
@vero-jasper 
I believe this issue should be opened in the plugin owner's repo : https://github.com/lejard-h/chopper/issues and follow-up there for updates.
Closing this from here. If you disagree or think the issue is related to framework itself, write in comments and I'll reopen it.
Thanks.

**Closed by darshankawar** 2021-03-09 12:54 UTC
Labels: in triage

**Comment by vero-jasper** [comment] 2021-03-10 01:55
> @vero-jasper
> I believe this issue should be opened in the plugin owner's repo : https://github.com/lejard-h/chopper/issues and follow-up there for updates.
> Closing this from here. If you disagree or think the issue is related to framework itself, write in comments and I'll reopen it.
> Thanks.

Ok, I'll try it. Thanks for your answer.
