### ISSUE TITLE
[google_maps_flutter] Null check operator used on a null value

### ISSUE THREAD

**Issue by imeDevelopers** [flutter/flutter#71354] opened 2020-11-28 22:45 UTC
```
[ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception:
Null check operator used on a null value
[  +89 ms] E/flutter (26107): #0
_AndroidMotionEventConverter.toAndroidMotionEvent.<anonymous closure>
(package:flutter/src/services/platform_views.dart:601:73)
[  +85 ms] E/flutter (26107): #1      MappedListIterable.elementAt
(dart:_internal/iterable.dart:417:31)
[  +91 ms] E/flutter (26107): #2      ListIterator.moveNext
(dart:_internal/iterable.dart:343:26)
[  +14 ms] E/flutter (26107): #3      new List.from (dart:core-patch/array_patch.dart:38:29)
[   +9 ms] E/flutter (26107): #4      new List.of (dart:core-patch/array_patch.dart:68:17)
[  +85 ms] E/flutter (26107): #5      ListIterable.toList (dart:_internal/iterable.dart:211:44)
[  +10 ms] E/flutter (26107): #6      _AndroidMotionEventConverter.toAndroidMotionEvent
(package:flutter/src/services/platform_views.dart:602:12)
[  +77 ms] E/flutter (26107): #7      AndroidViewController.dispatchPointerEvent
(package:flutter/src/services/platform_views.dart:864:31)
[  +92 ms] E/flutter (26107): #8      _PlatformViewGestureRecognizer.handleEvent
(package:flutter/src/rendering/platform_view.dart:535:26)
[  +22 ms] E/flutter (26107): #9      PointerRouter._dispatch
(package:flutter/src/gestures/pointer_router.dart:77:12)
[ +151 ms] E/flutter (26107): #10     PointerRouter._dispatchEventToRoutes.<anonymous closure>
(package:flutter/src/gestures/pointer_router.dart:122:9)
[ +113 ms] E/flutter (26107): #11     _LinkedHashMapMixin.forEach
(dart:collection-patch/compact_hash.dart:377:8)
[  +85 ms] E/flutter (26107): #12     PointerRouter._dispatchEventToRoutes
(package:flutter/src/gestures/pointer_router.dart:120:18)
[  +90 ms] E/flutter (26107): #13     PointerRouter.route
(package:flutter/src/gestures/pointer_router.dart:106:7)
[  +10 ms] E/flutter (26107): #14     GestureBinding.handleEvent
(package:flutter/src/gestures/binding.dart:358:19)
[ +131 ms] E/flutter (26107): #15     GestureBinding.dispatchEvent
(package:flutter/src/gestures/binding.dart:338:22)
[ +241 ms] E/flutter (26107): #16     RendererBinding.dispatchEvent
(package:flutter/src/rendering/binding.dart:267:11)
[ +196 ms] E/flutter (26107): #17     GestureBinding._handlePointerEvent
(package:flutter/src/gestures/binding.dart:295:7)
[  +96 ms] E/flutter (26107): #18     GestureBinding._flushPointerEventQueue
(package:flutter/src/gestures/binding.dart:240:7)
[  +14 ms] E/flutter (26107): #19     GestureBinding._handlePointerDataPacket
(package:flutter/src/gestures/binding.dart:213:7)
[ +118 ms] E/flutter (26107): #20     _rootRunUnary (dart:async/zone.dart:1206:13)
[ +314 ms] E/flutter (26107): #21     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
[ +126 ms] E/flutter (26107): #22     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
[ +173 ms] E/flutter (26107): #23     _invoke1 (dart:ui/hooks.dart:265:10)
[ +251 ms] E/flutter (26107): #24     _dispatchPointerDataPacket (dart:ui/hooks.dart:174:5)
```

**Comment by iapicca** [comment] 2020-11-28 23:21
@imeDevelopers 
can you provide your `flutter doctor -v `your `pubspec.yaml` and a minimal reproducible code sample

**Comment by TahaTesser** [comment] 2020-11-30 09:04
Hi @imeDevelopers 
Can you please provide your `flutter doctor -v`, your `pubspec.yaml` your `flutter run --verbose`, and a complete reproducible minimal code sample
Thank you

**Comment by ThexXTURBOXx** [comment] 2020-12-02 10:40
Seems to me like a duplicate of #69431

**Comment by fabribit** [comment] 2020-12-11 19:02
I have the same issue, any fix to it?

**Comment by ThexXTURBOXx** [comment] 2020-12-11 19:08
There is a workaround available in the issue I linked

**Comment by ThexXTURBOXx** [comment] 2020-12-20 12:19
This issue should also get fixed by 72611

**Closed** 2020-12-21 09:56 UTC
Labels: in triage, waiting for customer response

**Comment by kjawadDeveloper** [comment] 2021-03-20 15:11
This issue is till happening

**Comment by iapicca** [comment] 2021-03-20 15:47
@kjawadDeveloper 

can you please open a new issue with providing the info listed [above](https://github.com/flutter/flutter/issues/71354#issuecomment-735653755)

**Comment by ThexXTURBOXx** [comment] 2021-03-20 16:17
No new issue is needed as it is a duplicate of the still open issue #69431
