### ISSUE TITLE
[tool_crash] String: <57 characters>

### ISSUE THREAD

**Issue by tesfayeez** [flutter/flutter#140757] opened 2023-12-30 23:50 UTC
## Command
```
flutter run --profile
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
String: <57 characters>
```

```
```
[32m[✓][39m Flutter (Channel stable, 3.16.2, on macOS 14.1 23B74 darwin-arm64, locale en-US)
    [32m•[39m Flutter version 3.16.2 on channel stable at /Users/ezanatesfaye/Desktop/Development.nosync/flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision 9e1c857886 (4 weeks ago), 2023-11-30 11:51:18 -0600
    [32m•[39m Engine revision cf7a9d0800
    [32m•[39m Dart version 3.2.2
    [32m•[39m DevTools version 2.28.3

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    [32m•[39m Android SDK at /Users/ezanatesfaye/Library/Android/sdk
    [32m•[39m Platform android-34, build-tools 34.0.0
    [32m•[39m Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Xcode - develop for iOS and macOS (Xcode 15.0)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Build 15A240d
    [32m•[39m CocoaPods version 1.14.3

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[32m[✓][39m Android Studio (version 2022.2)
    [32m•[39m Android Studio at /Applications/Android Studio.app/Contents
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[32m[✓][39m VS Code (version 1.79.2)
    [32m•[39m VS Code at /Users/ezanatesfaye/Downloads/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version 3.80.0

[32m[✓][39m VS Code (version 1.56.2)
    [32m•[39m VS Code at /Users/ezanatesfaye/Library/Mobile Documents/com~apple~CloudDocs/Documents/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version 3.80.0

[32m[✓][39m Connected device (4 available)
    [32m•[39m Ezana iPhone (mobile)      • 00008130-001C38521A88001C            • ios            • iOS 17.1.2 21B101
    [32m•[39m iPhone 15 Pro Max (mobile) • 95464DA2-735F-4808-AA7A-C2E30395F8A2 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-0 (simulator)
    [32m•[39m macOS (desktop)            • macos                                • darwin-arm64   • macOS 14.1 23B74 darwin-arm64
    [32m•[39m Chrome (web)               • chrome                               • web-javascript • Google Chrome 120.0.6099.129

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[32m•[39m No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 796c8ef79279f9c774545b3771238c3098dbefab
### Plugins
audio_service-0.18.12
audio_service_web-0.1.1
audio_session-0.1.18
audioplayers-5.2.1
audioplayers_android-4.0.3
audioplayers_darwin-5.0.2
audioplayers_linux-3.1.0
audioplayers_web-4.1.0
audioplayers_windows-3.1.0
awesome_notifications-0.8.2
awesome_notifications_core-0.8.1
cloud_firestore-4.13.1
cloud_firestore_web-3.8.5
cloud_functions-4.5.4
cloud_functions_web-4.6.7
device_info_plus-9.0.3
file_selector_linux-0.9.2
file_selector_macos-0.9.3+1
file_selector_windows-0.9.3
firebase_auth-4.14.0
firebase_auth_web-5.8.7
firebase_core-2.22.0
firebase_core_web-2.8.1
firebase_messaging-14.7.4
firebase_messaging_web-3.5.13
firebase_performance-0.9.3+4
firebase_performance_web-0.1.4+12
firebase_storage-11.5.1
firebase_storage_web-3.6.13
flutter_keyboard_visibility-5.4.1
flutter_keyboard_visibility_linux-1.0.0
flutter_keyboard_visibility_macos-1.0.0
flutter_keyboard_visibility_web-2.0.0
flutter_keyboard_visibility_windows-1.0.0
flutter_local_notifications-15.1.2
flutter_native_splash-2.3.6
flutter_plugin_android_lifecycle-2.0.15
fluttertoast-8.2.4
google_sign_in-6.1.6
google_sign_in_android-6.1.18
google_sign_in_ios-5.6.2
google_sign_in_web-0.12.0+2
image_picker-1.0.4
image_picker_android-0.8.7+4
image_picker_for_web-2.2.0
image_picker_ios-0.8.8
image_picker_linux-0.2.1
image_picker_macos-0.2.1
image_picker_windows-0.2.1
just_audio-0.9.36
just_audio_web-0.4.9
path_provider-2.1.1
path_provider_android-2.1.0
path_provider_foundation-2.3.0
path_provider_linux-2.2.0
path_provider_windows-2.2.0
permission_handler-10.4.5
permission_handler_android-10.3.6
permission_handler_apple-9.1.4
permission_handler_windows-0.1.3
share_plus-7.2.1
shared_preferences-2.2.2
shared_preferences_android-2.2.1
shared_preferences_foundation-2.3.4
shared_preferences_linux-2.3.1
shared_preferences_web-2.2.1
shared_preferences_windows-2.3.1
sqflite-2.3.0
url_launcher-6.2.1
url_launcher_android-6.2.0
url_launcher_ios-6.2.1
url_launcher_linux-3.1.0
url_launcher_macos-3.1.0
url_launcher_web-2.2.0
url_launcher_windows-3.1.0
vibration-1.8.3

**Comment by dam-ease** [comment] 2024-01-02 07:43
Closing this as a duplicate of https://github.com/flutter/flutter/issues/108812

**Closed by dam-ease** 2024-01-02 07:43 UTC
Labels: in triage
