### ISSUE TITLE
Because every version of flutter_driver from sdk depends on vm_service 9.3.0 and integration_test >=1.0.2+2 depends on vm_service >=4.2.0 <7.0.0, flutter_driver from sdk is incompatible with integration_test >=1.0.2+2.

### ISSUE THREAD

**Issue by ch930410** [flutter/flutter#115519] opened 2022-11-17 02:43 UTC
**I downloaded a flutter project on github and reported the following error during the attempt:**

Running "flutter pub get" in flutter_deer-master...             
Because every version of flutter_driver from sdk depends on vm_service 9.3.0 and integration_test >=1.0.2+2 depends on vm_service >=4.2.0 <7.0.0, flutter_driver from sdk is incompatible with integration_test >=1.0.2+2.
So, because flutter_deer depends on both flutter_driver from sdk and integration_test ^1.0.2+2, version solving failed.
pub get failed
command: "F:\flutter\flutter_windows_2.8.1-stable\flutter\bin\cache\dart-sdk\bin\dart __deprecated_pub --verbosity=warning get --no-precompile"
pub env: {
  "FLUTTER_ROOT": "F:\flutter\flutter_windows_2.8.1-stable\flutter",
  "PUB_ENVIRONMENT": "vscode.dart-code:flutter_cli:get",
  "PUB_CACHE": "C:\Users\Administrator\AppData\Local\Pub\Cache",
}
exit code: 1
last line of pub output: "So, because flutter_deer depends on both flutter_driver from sdk and integration_test ^1.0.2+2, version solving failed."

exit code 1

**Comment by huycozy** [comment] 2022-11-17 09:50
Hi @ch930410 
From what I can see, the issue is related to a 3rd party plugin (flutter_deer). Please open the issue in the [flutter_deer repository](https://github.com/simplezhli/flutter_deer).

Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments, providing your `flutter doctor -v`, your `pubspec.yaml`, a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that does not use 3rd party plugins and I will reopen it.

Thank you!

**Closed by huycozy** 2022-11-17 09:50 UTC
Labels: in triage
