### ISSUE TITLE
Webstorm Flutter plugin doesn't allow "-d all" option

### ISSUE THREAD

**Issue by smrtsmrf** [flutter/flutter#10714] opened 2017-06-15 00:49 UTC
In the command line, I can run ```flutter run -d all``` to run the app on all my connected devices. It would be great if this option was available in the Flutter plugin for Webstorm. I can edit the configuration to take additional arguments, but when I tried adding "-d all", it said it didn't support it.

**Comment by eseidelGoogle** [comment] 2017-06-15 01:43
I believe this is being worked on: https://github.com/flutter/flutter-intellij/issues/956

**Comment by eseidelGoogle** [comment] 2017-06-15 01:43
Going to close this as a dupe of that bug.  Thanks for the report!

**Closed by eseidelGoogle** 2017-06-15 01:43 UTC
