### ISSUE TITLE
[tool_crash] FileSystemException: Cannot open file, OS Error: No such file or directory, errno = 2

### ISSUE THREAD

**Issue by yash1711v** [flutter/flutter#143307] opened 2024-02-12 16:24 UTC
## Command
```
flutter --no-color run --machine --track-widget-creation --device-id=53E8B73E-1E85-4F60-B10C-F27CCA1224EF --start-paused --dart-define=flutter.inspector.structuredErrors=true lib/main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Cannot open file, OS Error: No such file or directory, errno = 2
```
#0      _File.throwIfError (dart:io/file_impl.dart:675:7)
#1      _File.openSync (dart:io/file_impl.dart:490:5)
#2      ForwardingFile.openSync (package:file/src/forwarding/forwarding_file.dart:74:16)
#3      ErrorHandlingFile.copySync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:312:22)
#4      _runSync (package:flutter_tools/src/base/error_handling_io.dart:590:14)
#5      ErrorHandlingFile.copySync (package:flutter_tools/src/base/error_handling_io.dart:311:5)
#6      CocoaPods.setupPodfile (package:flutter_tools/src/macos/cocoapods.dart:275:21)
<asynchronous suspension>
#7      injectPlugins (package:flutter_tools/src/flutter_plugins.dart:1185:9)
<asynchronous suspension>
#8      FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:378:5)
<asynchronous suspension>
#9      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1665:7)
<asynchronous suspension>
#10     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1367:27)
<asynchronous suspension>
#11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#12     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#13     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:348:9)
<asynchronous suspension>
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#15     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:294:5)
```
```
[!] Flutter (Channel stable, 3.16.9, on macOS 14.3.1 23D60 darwin-arm64, locale en-IN)
    • Flutter version 3.16.9 on channel stable at /Volumes/Yashverma/Flutter/SDK/flutter
    ! The flutter binary is not on your path. Consider adding /Volumes/Yashverma/Flutter/SDK/flutter/bin to your path.
    ! The dart binary is not on your path. Consider adding /Volumes/Yashverma/Flutter/SDK/flutter/bin to your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 41456452f2 (3 weeks ago), 2024-01-25 10:06:23 -0800
    • Engine revision f40e976bed
    • Dart version 3.2.6
    • DevTools version 2.28.5
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/yashverma/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Volumes/Yashverma/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Volumes/Yashverma/Xcode.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.15.2

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 2023.1)
    • Android Studio at /Volumes/Yashverma/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] VS Code (version 1.85.2)
    • VS Code at /Volumes/Yashverma/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • iPhone 15 (mobile) • 53E8B73E-1E85-4F60-B10C-F27CCA1224EF • ios          • com.apple.CoreSimulator.SimRuntime.iOS-17-2 (simulator)
    • macOS (desktop)    • macos                                • darwin-arm64 • macOS 14.3.1 23D60 darwin-arm64

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.1+2
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 796c8ef79279f9c774545b3771238c3098dbefab
### Plugins
file_selector_linux-0.9.2+1
file_selector_macos-0.9.3+3
file_selector_windows-0.9.3+1
firebase_analytics-10.6.2
firebase_analytics_web-0.5.5+4
firebase_auth-4.12.0
firebase_auth_web-5.8.5
firebase_core-2.21.0
firebase_core_web-2.8.1
firebase_database-10.3.2
firebase_database_web-0.2.3+10
firebase_storage-11.4.1
firebase_storage_web-3.6.12
flutter_local_notifications-16.1.0
flutter_plugin_android_lifecycle-2.0.17
google_sign_in-6.1.5
google_sign_in_android-6.1.20
google_sign_in_ios-5.6.4
google_sign_in_web-0.12.0+5
image_picker-1.0.4
image_picker_android-0.8.8+2
image_picker_for_web-3.0.1
image_picker_ios-0.8.8+4
image_picker_linux-0.2.1+1
image_picker_macos-0.2.1+1
image_picker_windows-0.2.1+1
path_provider-2.1.1
path_provider_android-2.2.1
path_provider_foundation-2.3.1
path_provider_linux-2.2.1
path_provider_windows-2.2.1
permission_handler-11.0.1
permission_handler_android-11.1.0
permission_handler_apple-9.1.4
permission_handler_windows-0.1.3
quick_actions-1.0.6
quick_actions_android-1.0.9
quick_actions_ios-1.0.8
share_plus-7.2.1
shared_preferences-2.2.2
shared_preferences_android-2.2.1
shared_preferences_foundation-2.3.4
shared_preferences_linux-2.3.2
shared_preferences_web-2.2.1
shared_preferences_windows-2.3.2
url_launcher-6.2.1
url_launcher_android-6.2.0
url_launcher_ios-6.2.0
url_launcher_linux-3.1.0
url_launcher_macos-3.1.0
url_launcher_web-2.2.0
url_launcher_windows-3.1.0

**Comment by danagbemava-nc** [comment] 2024-02-13 07:02
Closing this as a duplicate of https://github.com/flutter/flutter/issues/96167.

**Closed by danagbemava-nc** 2024-02-13 07:02 UTC
Labels: in triage
