### ISSUE TITLE
Validation error message can not be placed to center

### ISSUE THREAD

**Issue by gibbsvjy007** [flutter/flutter#21343] opened 2018-09-02 21:39 UTC
![1](https://user-images.githubusercontent.com/6039305/44960959-01872280-af09-11e8-80d1-a5a5bca24675.PNG)

I want to place this error message to center. This is not possible with currently. I tried almost every approach. 

- textAlign: TextAlign.center,

is not helping to move error message to center. It moves the input text and placeholder to center not an error message

We need this in our current design spec. It would be good if you fix it as early as possible.

Thanks.

**Comment by monmon29** [comment] 2019-03-25 06:21
Any news about this issue?

**Comment by Miloshinjo** [comment] 2019-06-20 10:44
Did anyone find a workaround for this issue?

**Comment by copmorty** [comment] 2020-02-13 11:02
Still no solution for this?

**Comment by TahaTesser** [comment] 2020-05-20 15:28
Issue still valid 

<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel dev, 1.19.0-1.0.pre, on Mac OS X 10.15.4 19E287, locale en-GB)
    • Flutter version 1.19.0-1.0.pre at /Users/tahatesser/Code/flutter_dev
    • Framework revision 456d80b9dd (9 days ago), 2020-05-11 11:45:03 -0400
    • Engine revision d96f962ca2
    • Dart version 2.9.0 (build 2.9.0-7.0.dev 092ed38a87)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/tahatesser/Code/SDK
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.2

[✓] Connected device (5 available)
    • SM M305F      • 32003c30dc19668f          • android-arm64  • Android 10 (API 29)
    • Taha’s iPhone • 00008020-001059882212002E • ios            • iOS 13.4.1
    • macOS         • macOS                     • darwin-x64     • Mac OS X 10.15.4 19E287
    • Web Server    • web-server                • web-javascript • Flutter Tools
    • Chrome        • chrome                    • web-javascript • Google Chrome 81.0.4044.138

• No issues found!

``` 

</details>

**Comment by MonkeyDrone** [comment] 2020-10-06 07:06
Still looking for a fix guys!

**Comment by kdsinghapp** [comment] 2021-08-19 08:51
any fix ?

**Comment by TahaTesser** [comment] 2021-08-23 10:49
duplicate of https://github.com/flutter/flutter/issues/11068

**Closed by TahaTesser** 2021-08-23 10:49 UTC
Labels: a: text input, severe: new feature, framework, f: material design, a: quality, has reproducible steps, found in release: 1.19
