### ISSUE TITLE
Target debug_unpack_ios failed:  Exception: Failed to codesign 

### ISSUE THREAD

**Issue by galizhan** [flutter/flutter#142128] opened 2024-01-24 11:21 UTC
### Steps to reproduce

I am not sure how we can reproduce it, but it started after installing firebase_core and firebase_messaing on my working project. Then I tried to start new project and I saw that my projects show the same error. However on simulators everything is ok. I am sure that directory is not cloud synced. Tried to delete flutter and install again. 

### Expected results

Started new project to test that it correctly will build and run

### Actual results

None of my projects are running and shows this error

```
Could not build the precompiled application for the device.
Error (Xcode): Target debug_unpack_ios failed: Exception: Failed to codesign /Users/galix/StudioProjects/untitled2/build/ios/Debug-iphoneos/Flutter.framework/Flutter with identity 57209BF0C7BCADE6F2DD50416B02ABCE081826B7.
```

### Logs

<details open><summary>Logs</summary>

```console
Waiting for iPhone (Galizhan) to connect...
Launching lib/main.dart on iPhone (Galizhan) in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: TF39AN734X
Running Xcode build...
Xcode build done.                                           11,7s
Failed to build iOS app
Could not build the precompiled application for the device.
Error (Xcode): Target debug_unpack_ios failed: Exception: Failed to codesign /Users/galix/StudioProjects/untitled2/build/ios/Debug-iphoneos/Flutter.framework/Flutter with identity 57209BF0C7BCADE6F2DD50416B02ABCE081826B7.


Error launching application on iPhone (Galizhan).
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.16.8, on macOS 14.1 23B74 darwin-arm64, locale ru-KZ)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.85.2)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!

```

</details>

**Comment by dam-ease** [comment] 2024-01-24 14:13
Hello @galizhan 
Could you confirm whether your project is located in a cloud-synced directory (like OneDrive or a similar one) or not? If so, this is similar to https://github.com/flutter/flutter/issues/123583.

Also, could you share the entire output of `flutter run -v`?

May be a duplicate of: https://github.com/flutter/flutter/issues/130639 (please also take a look at it and check if you have a such case as well)

**Closed** 2024-02-14 15:08 UTC
Labels: waiting for customer response, in triage
