### ISSUE TITLE
UI issue

### ISSUE THREAD

**Issue by g1tPush** [flutter/flutter#131133] opened 2023-07-22 18:46 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Create flutter app
2. Add Container in the center with size and color. width and height is wrapped in dp function, which is - I use this code  - import 'dart:ui';

class _Metrics {
  static final scale = setScale();

  static double setScale() {
    final pixelRatio = PlatformDispatcher.instance.views.first.devicePixelRatio;
    final screenWidth = PlatformDispatcher.instance.views.first.physicalSize.shortestSide;
    final deviceScreenWidth = screenWidth / pixelRatio;
    const designScreenWidth = 375;
    return deviceScreenWidth / designScreenWidth;
  }
}

double dp(pixels) {
  return (pixels * _Metrics.scale);
} 
designScreenWidth is the width of design screen in figma
3. Run in profile mode
4. Close the app
5. Open app again from the device

### Expected results

Color block in the center of the app on the second open

### Actual results

The block in the center does not appear. Same issue on ios. Also, wrapping runApp in Future.delayed solves the problem

### Code sample

<details><summary>Code sample</summary>

```dart

import 'dart:ui';

class _Metrics {
  static final scale = setScale();

  static double setScale() {
    final pixelRatio = PlatformDispatcher.instance.views.first.devicePixelRatio;
    final screenWidth = PlatformDispatcher.instance.views.first.physicalSize.shortestSide;
    final deviceScreenWidth = screenWidth / pixelRatio;
    const designScreenWidth = 375;
    return deviceScreenWidth / designScreenWidth;
  }
}

double dp(pixels) {
  return (pixels * _Metrics.scale);
}


import 'package:flutter/material.dart';
import 'metrics.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: Center(
        child: Container(
          width: dp(100),
          height: dp(100),
          color: Colors.blue,
        )
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details>
<summary>First video is the state of the app after building it in profile mode. Second video is the opening of the app after closing it.</summary>

[Upload media here]

</details>

https://github.com/flutter/flutter/assets/109822566/c0e6d5e1-fd5a-4642-95b2-acf782be504f

https://github.com/flutter/flutter/assets/109822566/70a52df5-8e2f-4d73-84ea-91003c0ed7ce

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.10.6, on macOS 12.5 21G72 darwin-arm64 (Rosetta), locale en-US)
    • Flutter version 3.10.6 on channel stable at /Users/user/FlutterDev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (10 days ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/user/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.80.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.68.0

[✓] Connected device (3 available)
    • 23021RAA2Y (mobile) • 47350df3 • android-arm64  • Android 13 (API 33)
    • macOS (desktop)     • macos    • darwin-arm64   • macOS 12.5 21G72 darwin-arm64 (Rosetta)
    • Chrome (web)        • chrome   • web-javascript • Google Chrome 115.0.5790.102

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by dam-ease** [comment] 2023-07-24 09:01
Hi @g1tPush. Thanks for filing this issue. I'm currently unable to reproduce this issue on the latest flutter version, Can you help provide more information about reproducing this?

https://github.com/flutter/flutter/assets/53122008/1bec269b-b92d-497b-b12f-6353e1464a18

**Comment by g1tPush** [comment] 2023-07-24 11:22
Thanks for checking the issue, in order to reproduce it, you need to run it in profile mode on real device and terminate it completely before reopening

**Comment by dam-ease** [comment] 2023-07-25 07:58
Hi @g1tPush. Thanks for your response. This seems to be specific to Android devices. Testing on a TECNO LC6a, Android 9 and the center color block doesn't appear even on the first run. Is this the case on your end? If not, can you share details on the device information you are reproducing this on?

**Comment by g1tPush** [comment] 2023-07-25 10:16
Actually, I have tried this on iphone 7 and there was the same problem with the block after restart.  android phone is Xiaomi Redmi Note 12

**Comment by dam-ease** [comment] 2023-07-26 10:03
Hi @g1tPush. Thanks for your response. This is a duplicate of https://github.com/flutter/flutter/issues/101478. `window.physicalSize` is used but its more or less the same principle as using `PlatformDispatcher`. Using the platform dispatcher api to access the window info, in profile/release mode, the data may not be available so it is not reliable. Per https://github.com/flutter/flutter/issues/101478#issuecomment-1095402681, this could help. Closing this as a duplicate, if you disagree, kindly comment and I'd reopen it. 
Thank you!

**Closed by dam-ease** 2023-07-26 10:03 UTC
Labels: in triage
