### ISSUE TITLE
Add2App passing data back and forth between Flutter view and native view is verbose

### ISSUE THREAD

**Issue by truongsinh** [flutter/flutter#31186] opened 2019-04-17 08:41 UTC
As shared in my [Hackernoon article](https://hackernoon.com/how-to-add-flutter-to-your-production-android-app-4b5150de9e44#0423) for Android, but it is similar in iOS

Right now, developers can achieve it by themselves by wiring event channel and method channel to pass data back and forth between Flutter activity/view and native activity/view, but it is verbose to make it idiomatic for native developers. I think the framework can have some support to reduce the boilerplate code.

**Comment by truongsinh** [comment] 2019-04-17 09:27
@matthew-carroll

**Comment by jmagman** [comment] 2020-01-14 21:14
Check out the ongoing work at https://github.com/flutter/flutter/issues/32930.
@xster Is this a duplicate of https://github.com/flutter/flutter/issues/24080?

**Comment by gaaclarke** [comment] 2020-04-06 17:04
You can check out the package [Pigeon](https://pub.dev/packages/pigeon).  This is a duplicate of https://github.com/flutter/flutter/issues/32930

**Closed by gaaclarke** 2020-04-06 17:04 UTC
Labels: a: existing-apps, engine, platform-ios, severe: new feature
