### ISSUE TITLE
Commit 38c33d9 ModalRoute not rendering color

### ISSUE THREAD

**Issue by unknownconstant** [flutter/flutter#59415] opened 2020-06-14 07:04 UTC
Hi, I had accidentally set my Flutter channel to master and when flutter updated I found that a ModalRoute I'm using in my app was no longer setting its color and was appearing transparent until something causes it to reload (the content is static so this only happened on hot reload).

I am quite new to Flutter and Dart so it might be that I'm using the ModalRoute incorrectly but I'm raising an issue because the change appears to have altered the rendering of the component.

In my code the getter for barrierColor is set to return from an internal variable which is set when buildPage is called so that it is able to get the color from the theme from the context passed to the buildPage function. This seems to not be getting called as it has done previously so the barrierColor gets left as null so the modal renders as transparent.

Flutter documentation states that if the barrierColor getter may change output then to call changedInternalState() but this feels counterintuitive as the state isn't changing and the color isn't known until buildPage is called. In my app the color for the ModalRoute would only change if the device enters dark mode.

In trying to resolve this before realising I was on the wrong channel I had been toying with the idea of passing the color directly to my ModalRoute through its constructor, but the ModalRoute is pushed to the navigator from a component which doesn't have context through async_redux so this would require me to handle the color or theme data through the application state and my gut feeling is that I'd be more likely to introduce bugs through doing this.

The commit to the master branch in the subject may account for the issues I've found as its comments talk about rendering routes less and coincides with my update. Switching back to Flutter stable has resolved this.

https://github.com/flutter/flutter/pull/58202

**Comment by VladyslavBondarenko** [comment] 2020-06-15 11:21
Hi @unknownconstant 
could you provide a minimal complete reproducible code sample?

**Comment by unknownconstant** [comment] 2020-06-15 11:57
Yes I will sort this shortly

**Comment by Hixie** [comment] 2020-06-15 22:55
This should be fixed for now with the revert to https://github.com/flutter/flutter/pull/58202 (revert in https://github.com/flutter/flutter/pull/59503), but I'm leaving this open to track relanding https://github.com/flutter/flutter/pull/58202 with this regression fixed and tested.

**Comment by unknownconstant** [comment] 2020-06-21 13:32
Sorry for the delay in getting something for this. I'm still unsure if this is solely me being new to the language or if there is inconsistent behaviour.

I think the optimisation work which was completed has unmasked an issue with the way I was using ModalRoute. Before the optimisation the modal route was getting rebuilt multiple times which meant that even though the color was initially null it would eventually be given the context color. Because I had a short transitionDuration I hadn't noticed that it had always been initially transparent, but slowing it down revealed that it wasn't rendering properly even in the stable release.

There is a function in async_redux which returns the current context which can be accessed from the barrierColor getter, meaning that the theme color can be accessed and it changes if the device goes into dark mode.


Given the above it feels like this is more of an issue of how I was approaching getting the color from the context as you get consistent behaviour if you can find a way to get the current context to the getter. This might be something other people have done without realising too where they have very short transitionDurations, it might be worth having the current context available to the getter directly or would that be problematic?


I've not tested this in the branch with the optimisation but I've put what I've done here: https://github.com/unknownconstant/flutter_modalroute_demo

**Comment by Hixie** [comment] 2020-06-22 23:43
Thanks for that, I'll definitely take a look at it.

**Comment by Hixie** [comment] 2020-06-22 23:57
@unknownconstant Can you elaborate on what behaviour you're seeing and what you want to see? I'm seeing the same with and without my patch with that demo.

**Comment by unknownconstant** [comment] 2020-06-23 07:08
Ah I pushed where I had sorted out the issue rather than demonstrating it.

I’ve added another button so you can see the different behaviour when you use the context from the buildpage function.

What I was seeing with this is that before the patch the modal will fade in the page content, but the background Color would snap at the point the animation ends.

After the patch the Color no longer snaps in so the modal remains transparent until something triggers a rebuild.

If the transition duration is short then the Color snapping may not be noticed especially if there are widgets being loaded which are animating in correctly.

**Comment by Hixie** [comment] 2020-06-29 23:45
Here's a simplified repro (no dependencies other than Flutter, no unnecessary arguments or widgets in build methods):

```dart
import 'package:flutter/material.dart';

void main() async {
  runApp(MaterialApp(title: 'bug59415', home: MyHomePage()));
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({Key key}) : super(key: key);

  @override
  build(BuildContext context){
    return Scaffold(
      body: Center(
        child: OutlineButton(
          child: Text('PUSH TO TEST'),
          onPressed: () { Navigator.push(context, TestRoute()); },
        ),
      ),
    );
  }
}

class TestRoute extends ModalRoute {
  TestRoute();

  Color color;

  @override
  Color get barrierColor => color;

  @override
  bool get barrierDismissible => true;

  @override
  String get barrierLabel => null;

  @override
  Widget buildPage(BuildContext context, Animation<double> animation, Animation<double> secondaryAnimation) {
    color = Theme.of(context).backgroundColor;
    return TestRoutePage();
  }

  @override
  bool get maintainState => false;

  @override
  bool get opaque => false;

  @override
  Duration get transitionDuration => Duration(milliseconds: 1000);

  @override
  Widget buildTransitions(BuildContext context, Animation<double> animation, Animation<double> secondaryAnimation, Widget child) {
    return FadeTransition(opacity: animation, child: child);
  }
}

class TestRoutePage extends StatelessWidget {
  const TestRoutePage({Key key}) : super(key: key);

  build(BuildContext context){
    return Center(
      child: Text('The background should be blue.', style: Theme.of(context).textTheme.display2),
    );
  }
}
```

**Comment by Hixie** [comment] 2020-06-29 23:51
Fundamentally the problem is that the `color` gets set during `buildPage`, which is called after the modal barrier is painted, and then nothing causes it to repaint. In the past there was a stray rebuild (the rebuild that I fixed) which would cause it to get repainted so the problem was less obvious (though still visible in the original test on master -- you see a flicker as the blue comes in later).

The solution is to set the color in the `color` getter, which is, after all, what it's for:

```diff
diff --git a/lib/main.dart b/lib/main.dart
index 0a4aa32..7fc7a9a 100644
--- a/lib/main.dart
+++ b/lib/main.dart
@@ -26,7 +26,7 @@ class TestRoute extends ModalRoute {
   Color color;

   @override
-  Color get barrierColor => color;
+  Color get barrierColor => Theme.of(navigator.context).backgroundColor;

   @override
   bool get barrierDismissible => true;
@@ -36,7 +36,6 @@ class TestRoute extends ModalRoute {

   @override
   Widget buildPage(BuildContext context, Animation<double> animation, Animation<double> secondaryAnimation) {
-    color = Theme.of(context).backgroundColor;
     return TestRoutePage();
   }
```

**Comment by unknownconstant** [comment] 2020-06-30 07:54
@Hixie Yes, this is where I got to eventually too so I’m not convinced it’s a bug as such, but due to the previous masking other people may have fallen into the same trap especially if using an external library where access to the current context isn’t immediately obvious, which is why I’d provided the repo with async_redux as it showed the context in which I was facing issues & how ultimately it was my initial misinterpretation that caused my issue.

I suppose if the context can always be accessed through some mechanism prior to the modal being loaded then no changes are necessary.

That being said, a line / example on the documentation for modalRoute to say to use navigator.context in the getter may point people in the right direction and prevent others from resubmitting this as an issue as and when the commit is pushed back into master.

**Comment by Hixie** [comment] 2020-07-01 22:45
Yeah, definitely need to document this better if I reland my patch. I'm trying to help someone at Google track down a similar regression that came up on their side when we landed this too.

**Comment by Hixie** [comment] 2020-07-08 16:59
I was provided with the following repro as well, which doesn't seem to have any problems:

```dart
import 'package:flutter/material.dart';
import 'package:flutter/widgets.dart';

class TestPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Test',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: HomePage(),
    );
  }
}

class HomePage extends StatefulWidget {
  @override
  State<StatefulWidget> createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  void _presentModalPage() {
    Navigator.of(context).push(PageRouteBuilder<void>(
      transitionDuration: const Duration(milliseconds: 300),
      barrierColor: Colors.black54,
      opaque: false,
      pageBuilder: (context, _, __) {
        return ModalPage();
      },
    ));
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: const Center(
        child: Text('Test Home'),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _presentModalPage,
        child: const Icon(Icons.add),
      ),
    );
  }
}

class ModalPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
      type: MaterialType.transparency,
      child: SafeArea(
        child: Stack(
          children: [
            InkWell(
              highlightColor: Colors.transparent,
              splashColor: Colors.transparent,
              onTap: () {
                Navigator.of(context).pop();
              },
              child: const SizedBox.expand(),
            ),
            Align(
              alignment: Alignment.bottomCenter,
              child: Container(
                height: 150,
                color: Colors.red,
              ),
            ),
          ],
        ),
      ),
    );
  }
}
```

```dart
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'test_page.dart';

void main() {
  testWidgets('Repro', (tester) async {
    final page = TestPage();
    await tester.pumpWidget(page);

    await tester.tap(find.byType(FloatingActionButton));
    await tester.pumpAndSettle();

    await expectLater(
      find.byType(TestPage),
      matchesGoldenFile('test_page_golden'),
    );
  });
}
```

**Comment by Hixie** [comment] 2020-07-29 21:03
> ```diff
> -  Color get barrierColor => color;
> +  Color get barrierColor => Theme.of(navigator.context).backgroundColor;
> ```

Turns out this doesn't work... if the theme changes, it wouldn't call changedInternalState like it needs to...

**Comment by Hixie** [comment] 2020-07-29 21:48
I'll make Navigator update the routes when didChangeDependencies fires.

**Comment by Hixie** [comment] 2020-08-18 19:26
(Original bug here is fixed but I'd like to do some further cleanup.)

**Comment by Hixie** [comment] 2020-12-01 01:43
note to self: this is on my `build-routes-even-less` branch

**Comment by Hixie** [comment] 2020-12-03 22:45
cleanup in https://github.com/flutter/flutter/pull/71689

**Closed by Hixie** 2020-12-03 22:45 UTC
Labels: P4, framework, passed first triage, perf: speed, severe: performance
