### ISSUE TITLE
[video_player_web] video doesn't load after update (2.3.0)

### ISSUE THREAD

**Issue by npateras** [flutter/flutter#146416] opened 2024-04-08 07:22 UTC
### Steps to reproduce

1. updated my video_player_web package from 2.2.0 to 2.3.0.

### Expected results

To update the dep without it breaking.

### Actual results

For some reason my video gives me a TypeError: Illegal constructor error while in version 2.2.0 it works fine.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:get/get.dart';
import 'package:video_player/video_player.dart';

import '../../logging/logger.dart';

// Sensitive url variables hidden
const videoUrl =
    'https://flutter.github.io/assets-for-api-docs/assets/videos/bee.mp4';

class VideoController extends GetxController {
  late VideoPlayerController videoPlayerController;
  final isInitialized = false.obs;

  VideoController({
    this.autoPlayVideo,
  });
  final bool? autoPlayVideo;

  @override
  void onInit() {
    super.onInit();
    videoPlayerController = VideoPlayerController.networkUrl(
      Uri.parse(videoUrl),
    )..initialize().then((_) {
        isInitialized.value = true;
        update();
      }).catchError((error) {
        logger.e('Error loading the video: $error');
      });
  }

  @override
  void onClose() {
    videoPlayerController.dispose();
    super.onClose();
  }
}
```

### Logs

<details open><summary>Logs</summary>

```console
Error loading the video: TypeError: Illegal constructor
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
    • Flutter version 3.19.5 on channel stable 
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 300451adae (11 days ago), 2024-03-27 21:54:07 -0500
    • Engine revision e76c956498
    • Dart version 3.3.3
    • DevTools version 2.31.1

```

</details>

**Comment by huycozy** [comment] 2024-04-08 11:31
Hi @npateras 
I checked this issue using [package example](https://github.com/flutter/packages/blob/bb97da8ec627466fdb45cdd36e2c0e35dee40e9e/packages/video_player/video_player/example/lib/main.dart) but couldn't see the issue.

I see you are using `chewie` which is a 3rd party package that I'm unsure if it's related or not. Could you please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code?

**Comment by npateras** [comment] 2024-04-08 11:37
> Hi @npateras I checked this issue using [package example](https://github.com/flutter/packages/blob/bb97da8ec627466fdb45cdd36e2c0e35dee40e9e/packages/video_player/video_player/example/lib/main.dart) but couldn't see the issue.
> 
> I see you are using `chewie` which is a 3rd party package that I'm unsure if it's related or not. Could you please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code?

Hello and sorry for not clarifying that, I already tested without Chewie but the issue persists, here I will share a more detailed version of my class:

import 'package:get/get.dart';
import 'package:video_player/video_player.dart';

import '../../logging/logger.dart';

const videoUrl =
    'video url hidden';

class VideoController extends GetxController {
  late VideoPlayerController videoPlayerController;
  final isInitialized = false.obs;

  VideoController({
    this.autoPlayVideo,
  });
  final bool? autoPlayVideo;

  @override
  void onInit() {
    super.onInit();
    videoPlayerController = VideoPlayerController.networkUrl(
      Uri.parse(videoUrl),
    )..initialize().then((_) {
        isInitialized.value = true;
        update();
      }).catchError((error) {
        logger.e('Error loading the video: $error');
      });
  }

  @override
  void onClose() {
    videoPlayerController.dispose();
    super.onClose();
  }
}

**Comment by npateras** [comment] 2024-04-08 11:54
The video URL I use consists of this format but it works in video_player_web version 2.2.0 and stops working in 2.3.0:
https://player.vimeo.com/progressive_redirect/playback/XXXXX/rendition/720p/file.mp4?loc=external&signature=XXXXX

**Comment by npateras** [comment] 2024-04-08 12:16
Sadly I cannot do that since the video must remain private and to get all those parameters for the url you have to be the uploader of the video on Vimeo. Also the url will not work without the signature parameter and the url basically gives me a direct native browser video.

**Comment by huycozy** [comment] 2024-04-09 03:59
I'm unsure how to create such a URL. I just tried uploading a video to Vimeo (here it is: https://vimeo.com/932320452) and then playing it using the older package version `video_player_web: 2.2.0` but it also can't be played. 

It would be helpful if you could share a public URL or steps to create such URL you shared above.

Also, does this issue only occur on Web app? Could you also confirm it on Android or iOS app?

**Comment by npateras** [comment] 2024-04-09 18:54
> I'm unsure how to create such a URL. I just tried uploading a video to Vimeo (here it is: https://vimeo.com/932320452) and then playing it using the older package version `video_player_web: 2.2.0` but it also can't be played.
> 
> It would be helpful if you could share a public URL or steps to create such URL you shared above.
> 
> Also, does this issue only occur on Web app? Could you also confirm it on Android or iOS app?

Hello @huycozy, I found a good url as an example. The issue persists even with this url:
https://flutter.github.io/assets-for-api-docs/assets/videos/bee.mp4

**Comment by huycozy** [comment] 2024-04-10 05:10
That URL is also used in the [package example](https://github.com/flutter/packages/tree/764d9974522bd8d867d34680dd33a5bb62fb1b57/packages/video_player/video_player/example). I also ran it (the current video_player_web is 2.3.0) but the video is playing well on Web:

<details>
<summary>Demo</summary>

https://github.com/flutter/flutter/assets/104349824/5730abe8-e1f3-49a4-82ae-62573d6065a4

</details>

Could you also check this example and confirm? If the issue still occurs on your end, could you please share a demo (video) and the entire error stack trace?

**Comment by npateras** [comment] 2024-04-10 06:53
I tried to run the default example on my project and this is what I got, still getting the illegal constructor error:
https://hastebin.com/share/ororeyigov.bash

  video_player: ^2.8.5
  video_player_web: 2.3.0

**Comment by npateras** [comment] 2024-04-10 09:07
So I manage to solve the issue... The reason was that I was using an override package for web on my pubspec.yml file:

`
dependency_overrides:
  web:
    git:
      url: https://github.com/dart-lang/web/
      ref: d96c01d2252372c9e0fa7ffa52d2d1df331c248b
`

**Comment by huycozy** [comment] 2024-04-11 04:35
It looks like an incompatible version issue. Since you solved it, I'm going to close the issue. If it appears with the latest version of dart-lang/web, please write in the comments and I will re-open this for further investigation.

**Closed by huycozy** 2024-04-11 04:35 UTC
Labels: in triage
