### ISSUE TITLE
Video (Vimeo) can not be played in fullscreen

### ISSUE THREAD

**Issue by lars-3107** [flutter/flutter#77746] opened 2021-03-09 22:21 UTC
Fullscreen option is missing when playing Vimeo videos for example.

**Comment by pedromassangocode** [comment] 2021-03-10 07:43
Hi @lars-3107 
Can you please provide your `flutter doctor -v` and a minimal complete reproducible code sample?
Thank you

**Comment by lars-3107** [comment] 2021-03-10 10:27
`[√] Flutter (Channel stable, 2.0.0, on Microsoft Windows [Version 10.0.19042.804], locale de-DE)
    • Flutter version 2.0.0 at C:\src\flutter
    • Framework revision 60bd88df91 (7 days ago), 2021-03-03 09:13:17 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\xxx\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\xxx\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.0)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.9.31025.194
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.54.1)
    • VS Code at C:\Users\xxx\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.20.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19042.804]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 89.0.4389.82
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 89.0.774.45

• No issues found!
`

**Comment by lars-3107** [comment] 2021-03-10 10:48
`import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Sample',
      theme: ThemeData(
        primarySwatch: Colors.teal,
      ),
      home: MyHomePage(title: 'Sample'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: WebView(
          initialUrl: 'https://vimeo.com/521802279',
          javascriptMode: JavascriptMode.unrestricted),
    );
  }
}
`

**Comment by lars-3107** [comment] 2021-03-10 10:50
If I open the link (https://vimeo.com/521802279) manually on my phone the fullscreen button on the video shows up - in the webview it doesn't.

**Comment by pedromassangocode** [comment] 2021-03-10 11:47
After reading related topics in some issues I think this is a duplicate of https://github.com/flutter/flutter/issues/27101. Please follow up on that issue for updates.
Thank you

**Closed by pedromassangocode** 2021-03-10 11:47 UTC
Labels: in triage
