### ISSUE TITLE
popModal() support for Navigator

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#16677] opened 2018-04-17 21:31 UTC
[This is coming from two teams in Google.]

If app pushes a new route from a modal route (such as full screen dialog), closing the modal starts all exit animations at the same time leading to an odd transition. Consider the following app:

```dart
import 'package:flutter/material.dart';
import 'package:flutter/scheduler.dart';

void main() {
  timeDilation = 10.0;
  runApp(new MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Flutter Demo',
      theme: new ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: new Page('First'),
    );
  }
}

class Page extends StatelessWidget {
  final String title;

  const Page(this.title);

  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: new AppBar(
        title: new Text(title),
      ),
      body: new Center(
        child: new GestureDetector(
          onTap: () => Navigator.push(
                context,
                new MaterialPageRoute(
                  builder: (context) => new ModalPage(),
                  fullscreenDialog: true,
                ),
              ),
          child: new Text('Launch Modal'),
        ),
      ),
    );
  }
}

class ModalPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: new AppBar(
        title: new Text('Modal Page'),
      ),
      body: new Center(
        child: new GestureDetector(
          onTap: () => Navigator.push(
                context,
                new MaterialPageRoute(
                  builder: (context) => new SecondaryPage(),
                ),
              ),
          child: new Text('Launch Secondary Page'),
        ),
      ),
    );
  }
}

class SecondaryPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: new AppBar(
        title: new Text('Secondary Page'),
      ),
      body: new Center(
        child: new GestureDetector(
          onTap: () {
            Navigator.popUntil(context, ModalRoute.withName('/'));
          },
          child: new Text('Clear All'),
        ),
      ),
    );
  }
}
```

which leads to:

[multi_exit_animation.zip](https://github.com/flutter/flutter/files/1921629/multi_exit_animation.zip)

Expected behavior is for the close action to execute a single modal exit animation and apply this animation only on the last route visible. In the example above, the secondary route would disappear from view revealing the entry route via the full screen dialog exit animation.

It is worth noting that if second route pushes a third route, normal `MaterialPageRoute` animations should be executed (both entry and exit). The only difference between this and current behavior is when the app wants to close the entire modal path (modal + all pages that opened from that modal).

Suggested sequence:
- Remove all routes between current route and modal route (including modal route).
- Modify the exit animation of the current route.
- Pop the current route.

**Comment by Hixie** [comment] 2018-06-26 23:18
This is working as intended. If you don't want the exit animation, use "remove" instead of "pop".

I'm working on improving this API in general.

**Comment by mehmetf** [comment] 2018-07-07 22:15
@Hixie This is more like "working as implemented". The expected effect is described in the issue and I don't believe it can be achieved by existing APIs. Please correct me if I am wrong.

**Comment by Hixie** [comment] 2018-07-16 20:44
Pretty sure you can just do it using remove instead of pop, as per my last comment.
But in any case as noted above, I'm doing a rewrite of this API which will make all this better in the long run. No ETA currently.

**Comment by Hixie** [comment] 2018-07-25 00:02
@HansMuller says he's going to write a quick demo to show this. Thanks Hans!

**Comment by HansMuller** [comment] 2018-07-30 20:00
I just talked to @Hixie about the assertion that I mentioned. It's there to prevent apps from removing a route that's partially visible, as the route below the "secondary" route would be. So reverting to `popUntil` in the unusual case where the user has managed to dimiss the modal before it's completely visible seems OK.

There is a Navigator API that handles this kind of thing in general. The `[pushAndRemoveUntil](https://github.com/flutter/flutter/issues/9989)` eagerly removes routes below the new route until a route that matches the predicate is reached.

So if the `seondaryRoute` is pushed with pushAndRemoveUntil, the current route will get removed once `secondaryRoute` is completely visible.
```
Navigator.pushAndRemoveUntil(context, secondaryRoute, ModalRoute.withName('/'));
```
Unfortunately, this approach appears to prevent the new route's animation from painting, so it might be best to stick with removing the intermediate routes just before calling Navigator.pop().

**Comment by Hixie** [comment] 2018-07-30 21:45
> Unfortunately, this approach appears to prevent the new route's animation from painting

That sounds like a bug.

**Comment by HansMuller** [comment] 2018-07-30 22:55
It looks the `pushAndRemoveUntil` animation bug was reported here: https://github.com/flutter/flutter/issues/15030. It shouldn't block resolving this issue, since removing "in the middle" routes before calling Navigator.pop() works.

**Comment by jklint-g** [comment] 2018-07-30 22:59
What can we do about the exit animation though? On iOS, that last screen needs to enter as a horizontal slide but exit as a vertical slide.

The pushAndRemoveUntil does work to remove the intermediate routes (modulo the mentioned bug), or just removing them manually. But that last screen in the dialog flow still exits horizontally.

**Comment by jklint-g** [comment] 2018-07-30 23:01
btw I made this work by nesting two navigators and intercepting didPop on the sub-navigator, but it's kinda messy.

**Comment by HansMuller** [comment] 2018-07-30 23:48
Having the dialog appear iOS-style by sliding horizontally into view but disappear by sliding downwards doesn't seem like an ideal choice vis usability. If the dialog is dismissed halfway through its transition, it might look a little odd changing its motion from horizontal to vertical. And if it was shown again in the middle of that, it would need to move along both axes.

**Comment by mehmetf** [comment] 2018-08-01 18:14
@jklint-g I know you have a workaround for this but we would like to support you if possible. 

@HansMuller, your concern about UX aside, is it possible today to change the exit animation of the last page? Does the exit animation have to be specified during route construction time or can it be delayed until the `pop()` call is made?

**Comment by alanrussian** [comment] 2018-08-01 18:39
After we discussed the specific scenario where we needed this with our designer, we decided to use a different set of transitions such that the modal transition for the last route would be the same entering as exiting. Therefore, this is no longer a mulligan blocker.

**Comment by mehmetf** [comment] 2018-08-02 15:28
Thanks. @HansMuller it seems like you did create a demo for this? If you can post a gist, we can close this bug.

**Comment by HansMuller** [comment] 2018-08-03 17:19
Here's a demo that removes an intermediate route before popping the top route: https://gist.github.com/HansMuller/f4a86fc31fdbc9699e1bd4947e9b15fd

It does not replace the topmost route's exit animation.  I suppose you could do that be creating a route class with a ProxyAnimation and a setter, so that you can change the route's animation. However, as I'd said, that sort of thing is unlikely to work well in situations where the pop animation is interrupted by a push.

**Closed** 2018-08-05 18:05 UTC
Labels: customer: cradle, f: routes, framework
