### ISSUE TITLE
barcode_scan plugin doesn't work with android_alarm_manager

### ISSUE THREAD

**Issue by Albert221** [flutter/flutter#24780] opened 2018-11-27 14:16 UTC
Here's my crash:

```
E/flutter (16834): [ERROR:flutter/shell/common/shell.cc(184)] Dart Error: Unhandled exception:
E/flutter (16834): PlatformException(error, registrar.activity() must not be null, null)
E/flutter (16834): #0      JSONMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:149:7)
E/flutter (16834): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:292:18)
E/flutter (16834): <asynchronous suspension>
E/flutter (16834): #2      AndroidAlarmManager.initialize (package:android_alarm_manager/android_alarm_manager.dart:70:10)
E/flutter (16834): <asynchronous suspension>
E/flutter (16834): #3      main (package:lek_bierz/main.dart:19:29)
E/flutter (16834): <asynchronous suspension>
E/flutter (16834): #4      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:289:19)
E/flutter (16834): #5      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

My code basically has `await AndroidAlarmManager.initialize();` (that line causes the crash) on the top of the `void main() async` function and has `<service>` registered in manifest as well as custom Application class created, implemented the `PluginRegistrantCallback` and added it to manifest. But it just doesn't work. It crashes on this line given above.

Doctor:

```
[✓] Flutter (Channel beta, v0.11.3, on Linux, locale pl_PL.UTF8)
    • Flutter version 0.11.3 at /opt/flutter
    • Framework revision 72bf075e8d (2 weeks ago), 2018-11-09 20:36:17 -0800
    • Engine revision 5646e86a6f
    • Dart version 2.1.0 (build 2.1.0-dev.9.3 9c07fb64c4)

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /home/albert221/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 27.0.3
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 3.1)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 29.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] Connected device (1 available)
    • Pixel 2 XL • 712KPED1275708 • android-arm64 • Android 9 (API 28)
```

Whole application code available [here](https://github.com/Albert221/LekBierz/tree/alarm-manager), but I don't see the relevance of any of my code with the crash.

Quick links to files in this repo:

- [pubspec.yaml](https://github.com/Albert221/LekBierz/blob/alarm-manager/pubspec.yaml)
- [main.dart](https://github.com/Albert221/LekBierz/blob/alarm-manager/lib/main.dart#L19)
- [Application.kt](https://github.com/Albert221/LekBierz/blob/alarm-manager/android/app/src/main/kotlin/me/wolszon/lekbierz/Application.kt)
- [MainActivity.kt](https://github.com/Albert221/LekBierz/blob/alarm-manager/android/app/src/main/kotlin/me/wolszon/lekbierz/MainActivity.kt)
- [AndroidManifest.xml](https://github.com/Albert221/LekBierz/blob/alarm-manager/android/app/src/main/AndroidManifest.xml)

**Comment by laoqiu** [comment] 2018-12-10 03:57
+1

**Comment by zoechi** [comment] 2018-12-10 08:13
@laoqiu 
"me too" and "+1" comments are pointless. 
Instead use ![image](https://user-images.githubusercontent.com/405837/49718793-716d1d80-fc5b-11e8-8a7a-7288f578a66d.png) on the initial comment to upvote and increase priority.
Comments cause spammy notification mails sent to all subscribers.
If you want to get notified, use ![image](https://user-images.githubusercontent.com/405837/49718838-95306380-fc5b-11e8-8900-0d9173289cc8.png)

**Comment by truongsinh** [comment] 2018-12-13 14:16
I checked out your code @Albert221 https://github.com/Albert221 and replace it in the `example` folder of the plugin, but cannot `flutter run`, see log

```
Wolfie-MBP:example truongsinh$ flutter run
Using hardware rendering with device Android SDK built for x86 64. If you get graphics artifacts, consider enabling software rendering with
"--enable-software-rendering".
Launching lib/main.dart on Android SDK built for x86 64 in debug mode...
Initializing gradle...                                       1.4s
Resolving dependencies...                                        
* Error running Gradle:
ProcessException: Process "/Users/truongsinh/Development/flutter-plugins/packages/android_alarm_manager/example/android/gradlew" exited abnormally:
Project evaluation failed including an error in afterEvaluate {}. Run with --stacktrace for details of the afterEvaluate {} error.

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/truongsinh/Development/flutter-plugins/packages/android_alarm_manager/example/android/app/build.gradle' line: 30

* What went wrong:
A problem occurred evaluating project ':app'.
> /Users/truongsinh/Development/flutter-plugins/packages/android_alarm_manager/example/android/key.properties (No such file or directory)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
  Command: /Users/truongsinh/Development/flutter-plugins/packages/android_alarm_manager/example/android/gradlew app:properties


Please review your Gradle project setup in the android/ folder.
Wolfie-MBP:example truongsinh$

**Comment by Patte1808** [comment] 2018-12-19 09:52
I debugged it quickly and this problem seems to occur once you add the barcodescanner dependency and this line to the AndroidManifest:

` <activity android:name="com.apptreesoftware.barcodescan.BarcodeScannerActivity"/>`

**Comment by tzutolin** [comment] 2018-12-22 01:39
Same here. 

`I/AlarmService(12538): Starting AlarmService...
E/MethodChannel#plugins.flutter.io/android_alarm_manager(12538): Failed to handle method call
E/MethodChannel#plugins.flutter.io/android_alarm_manager(12538): java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.PluginRegistry$PluginRegistrantCallback.registerWith(io.flutter.plugin.common.PluginRegistry)' on a null object reference
E/MethodChannel#plugins.flutter.io/android_alarm_manager(12538): 	at io.flutter.plugins.androidalarmmanager.AlarmService.startAlarmService(AlarmService.java:65)
E/MethodChannel#plugins.flutter.io/android_alarm_manager(12538): 	at io.flutter.plugins.androidalarmmanager.AndroidAlarmManagerPlugin.startService(AndroidAlarmManagerPlugin.java:75)
E/MethodChannel#plugins.flutter.io/android_alarm_manager(12538): 	at io.flutter.plugins.androidalarmmanager.AndroidAlarmManagerPlugin.onMethodCall(AndroidAlarmManagerPlugin.java:52)
E/MethodChannel#plugins.flutter.io/android_alarm_manager(12538): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:200)
E/MethodChannel#plugins.flutter.io/android_alarm_manager(12538): 	at io.flutter.view.FlutterNativeView.handlePlatformMessage(FlutterNativeView.java:163)
E/MethodChannel#plugins.flutter.io/android_alarm_manager(12538): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#plugins.flutter.io/android_alarm_manager(12538): 	at android.os.MessageQueue.next(MessageQueue.java:325)
E/MethodChannel#plugins.flutter.io/android_alarm_manager(12538): 	at android.os.Looper.loop(Looper.java:142)
E/MethodChannel#plugins.flutter.io/android_alarm_manager(12538): 	at android.app.ActivityThread.main(ActivityThread.java:6494)
E/MethodChannel#plugins.flutter.io/android_alarm_manager(12538): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.flutter.io/android_alarm_manager(12538): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
E/MethodChannel#plugins.flutter.io/android_alarm_manager(12538): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
E/MethodChannel#plugins.flutter.io/android_alarm_manager(12538): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:108)
E/flutter (12538): [ERROR:flutter/shell/common/shell.cc(184)] Dart Error: Unhandled exception:
E/flutter (12538): PlatformException(error, Attempt to invoke interface method 'void io.flutter.plugin.common.PluginRegistry$PluginRegistrantCallback.registerWith(io.flutter.plugin.common.PluginRegistry)' on a null object reference, null)
E/flutter (12538): #0      JSONMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:149:7)
E/flutter (12538): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:292:18)
E/flutter (12538): <asynchronous suspension>`

**Comment by Hixie** [comment] 2019-01-03 07:31
The issue is probably that the barcode_scan plugin is assuming there's an activity when it's registered.

I suspect there is more to the crash than described in the original comment. It would be helpful to have the entire log of the program execution.

**Comment by zubairehman** [comment] 2019-11-21 06:45
facing the same issue. any update on this?

**Comment by TahaTesser** [comment] 2020-03-17 09:28
Hi @Albert221  @zubairehman
Are you still experiencing this issue with latest stable?
if so, can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful
if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by iapicca** [comment] 2020-04-22 10:12
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.

**Closed by iapicca** 2020-04-22 10:12 UTC
Labels: p: android_alarm_manager, p: first party, platform-android, plugin, severe: crash, waiting for customer response
