### ISSUE TITLE
Devicelab tasks flaking due to insufficient storage

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#135035] opened 2023-09-19 16:53 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing infra issues](https://github.com/flutter/flutter/issues?q=is%3Aopen+is%3Aissue+label%3Ateam-infra)

### Type of Request

bug

### Infrastructure Environment

Devicelab

### What is happening?

Many Device lab tasks are flaking due to insufficient storage errors,  see: https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8769511480680570273/+/u/run_opacity_peephole_grid_of_alpha_savelayers_perf__e2e_summary/test_stdout

```
[2023-09-19 09:05:37.901796] [STDOUT] stderr: 
[2023-09-19 09:05:37.901814] [STDOUT] stderr:            adb: failed to install /opt/s/w/ir/x/w/recipe_cleanup/tmp8szcrs63/flutter sdk/dev/benchmarks/macrobenchmarks/build/app/outputs/flutter-apk/app-profile.apk: Failure [INSTALL_FAILED_INSUFFICIENT_STORAGE: Package couldn't be installed in /data/app/com.example.macrobenchmarks-1: Creating application package com.example.macrobenchmarks failed]
[2023-09-19 09:05:37.901836] [STDOUT] stdout: [        ] Warning: Failed to install APK.
[2023-09-19 09:05:37.902070] [STDOUT] stderr: [        ] Application failed to start on attempt: 2
[2023-09-19 09:05:37.902695] [STDOUT] stdout: [        ] Stopping app 'app-profile.apk' on Moto G 4.
[2023-09-19 09:05:37.902745] [STDOUT] stdout: [        ] executing: /opt/s/w/ir/cache/android/sdk/platform-tools/adb -s ZY223HK9P7 shell am force-stop com.example.macrobenchmarks
[2023-09-19 09:05:38.788481] [STDOUT] stdout: [ +885 ms] executing: /opt/s/w/ir/cache/android/sdk/platform-tools/adb -s ZY223HK9P7 shell pm list packages com.example.macrobenchmarks
[2023-09-19 09:05:39.733880] [STDOUT] stdout: [ +945 ms] Installing APK.
[2023-09-19 09:05:39.734219] [STDOUT] stdout: [        ] Installing build/app/outputs/flutter-apk/app-profile.apk...
[2023-09-19 09:05:39.734266] [STDOUT] stdout: [        ] executing: /opt/s/w/ir/cache/android/sdk/platform-tools/adb -s ZY223HK9P7 install -t -r /opt/s/w/ir/x/w/recipe_cleanup/tmp8szcrs63/flutter sdk/dev/benchmarks/macrobenchmarks/build/app/outputs/flutter-apk/app-profile.apk
[2023-09-19 09:05:54.183736] [STDOUT] stdout: [+14448 ms] Performing Streamed Install
[2023-09-19 09:05:54.183857] [STDOUT] stdout: 
[2023-09-19 09:05:54.183881] [STDOUT] stdout:             adb: failed to install /opt/s/w/ir/x/w/recipe_cleanup/tmp8szcrs63/flutter sdk/dev/benchmarks/macrobenchmarks/build/app/outputs/flutter-apk/app-profile.apk: Failure [INSTALL_FAILED_INSUFFICIENT_STORAGE: Package couldn't be installed in /data/app/com.example.macrobenchmarks-1: Creating application package com.example.macrobenchmarks failed]
[2023-09-19 09:05:54.183906] [STDOUT] stdout: [        ] Installing build/app/outputs/flutter-apk/app-profile.apk... (completed in 14.4s)
[2023-09-19 09:05:54.183982] [STDOUT] stderr: [        ] Error: ADB exited with exit code 1
[2023-09-19 09:05:54.184001] [STDOUT] stderr: [        ] Performing Streamed Install
[2023-09-19 09:05:54.184018] [STDOUT] stderr: 
[2023-09-19 09:05:54.184037] [STDOUT] stderr:            adb: failed to install /opt/s/w/ir/x/w/recipe_cleanup/tmp8szcrs63/flutter sdk/dev/benchmarks/macrobenchmarks/build/app/outputs/flutter-apk/app-profile.apk: Failure [INSTALL_FAILED_INSUFFICIENT_STORAGE: Package couldn't be installed in /data/app/com.example.macrobenchmarks-1: Creating application package com.example.macrobenchmarks failed]
[2023-09-19 09:05:54.184073] [STDOUT] stdout: [        ] Warning: Failed to install APK.
[2023-09-19 09:05:54.184351] [STDOUT] stderr: [        ] Application failed to start on 
```

**Comment by drewroengoogle** [comment] 2023-09-19 17:20
Many of them seem to be occurring on `linux-15`, @yusuf-goog Would it make sense to quarantine this bot?

**Comment by yusuf-goog** [comment] 2023-09-19 18:31
let me look at it and free up space on the attached device.

**Comment by yusuf-goog** [comment] 2023-09-19 20:10
quarantined the host. Looking at freeing up space on the device.

**Comment by yusuf-goog** [comment] 2023-09-19 20:19
Uninstalled all third party packages:
`adb shell pm list packages -3 | cut -d':' -f2 | tr '\r' ' ' | xargs -r -n1 -t adb uninstall`

Not much direct use of space. Before:

```
Filesystem                             1K-blocks    Used Available Use% Mounted on
tmpfs                                     945452     692    944760   1% /dev
tmpfs                                     945452       0    945452   0% /mnt
/dev/block/bootdevice/by-name/system     2499580 1851308    631888  75% /system
/dev/block/bootdevice/by-name/userdata  11349888 3141948   8122052  28% /data
/dev/block/bootdevice/by-name/cache       253920     296    248384   1% /cache
/dev/block/bootdevice/by-name/persist      28144     468     27024   2% /persist
/dev/block/bootdevice/by-name/dsp          12016    3740      7952  32% /dsp
/dev/block/bootdevice/by-name/modem        96688   71244     23396  76% /firmware
/dev/block/bootdevice/by-name/fsg           1968    1956         0 100% /fsg
/dev/block/bootdevice/by-name/oem         650656   97864    539360  16% /oem
/data/media                             11349888 3141948   8122052  28% /storage/emulated
```

after:

```
Filesystem                             1K-blocks    Used Available Use% Mounted on
tmpfs                                     945452     692    944760   1% /dev
tmpfs                                     945452       0    945452   0% /mnt
/dev/block/bootdevice/by-name/system     2499580 1851308    631888  75% /system
/dev/block/bootdevice/by-name/userdata  11349888 2736248   8527752  25% /data
/dev/block/bootdevice/by-name/cache       253920     296    248384   1% /cache
/dev/block/bootdevice/by-name/persist      28144     468     27024   2% /persist
/dev/block/bootdevice/by-name/dsp          12016    3740      7952  32% /dsp
/dev/block/bootdevice/by-name/modem        96688   71244     23396  76% /firmware
/dev/block/bootdevice/by-name/fsg           1968    1956         0 100% /fsg
/dev/block/bootdevice/by-name/oem         650656   97864    539360  16% /oem
/data/media                             11349888 2736248   8527752  25% /storage/emulated
```

**Comment by yusuf-goog** [comment] 2023-09-19 20:21
cc @reidbaker

**Comment by yusuf-goog** [comment] 2023-09-19 20:33
@jonahwilliams the device has ~8gb in /data, which should be enough to install any app? 

I think we might be hitting a different issue which just manifests as  `INSTALL_FAILED_INSUFFICIENT_STORAGE` : 

https://stackoverflow.com/questions/4709137/solution-to-install-failed-insufficient-storage-error-on-android

Looking into this.

**Comment by yusuf-goog** [comment] 2023-09-19 20:34
Ran:
`pm uninstall com.example.macrobenchmarks-1`
`rm -rf  /data/app/com.example.macrobenchmarks*`

Unquarantined the host, looking to see if we still get the failure.

**Comment by yusuf-goog** [comment] 2023-09-20 00:06
builds are running successfully on linux-15 now, including a few that had previously failed with out of space errors. Closing this, reopen if it happens again.

**Comment by jonahwilliams** [comment] 2023-09-20 17:04
Reopening because this is still happening: https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8769419375691054689/+/u/run_channels_integration_test/test_stdout

We used to have devicelab code that would attempt to uninstall an APK after the test completed. Is that not running anymore?

**Comment by yusuf-goog** [comment] 2023-09-20 17:11
This build failed on linux-13 device this time.

I'm looking into putting the cleanup into our device doctor script, which should automate the recovery.

**Comment by yusuf-goog** [comment] 2023-09-20 17:19
quarantined linux-13

**Comment by yusuf-goog** [comment] 2023-09-20 17:49
Device was also unresponsive. Power cycling brought it back.

Before applying any changes:

```$ adb shell df -h
Filesystem                             Size  Used Avail Use% Mounted on
tmpfs                                  923M  692K  923M   1% /dev
tmpfs                                  923M     0  923M   0% /mnt
/dev/block/bootdevice/by-name/system   2.3G  1.7G  617M  75% /system
/dev/block/bootdevice/by-name/userdata  11G  671M   10G   7% /data
/dev/block/bootdevice/by-name/cache    248M  296K  243M   1% /cache
/dev/block/bootdevice/by-name/persist   27M  440K   26M   2% /persist
/dev/block/bootdevice/by-name/dsp       12M  3.6M  7.7M  32% /dsp
/dev/block/bootdevice/by-name/modem     94M   70M   23M  76% /firmware
/dev/block/bootdevice/by-name/fsg      1.9M  1.9M     0  100% /fsg
/dev/block/bootdevice/by-name/oem      635M   96M  527M  16% /oem
tmpfs                                  923M     0  923M   0% /storage
/data/media                             11G  671M   10G   7% /storage/emulated```

Ran:

```
pm uninstall com.example.macrobenchmarks-1
rm -rf  /data/app/com.example.macrobenchmarks*
```

**Comment by yusuf-goog** [comment] 2023-09-20 17:52
Unquarantined linux-13 to test if that fixes things.

**Comment by yusuf-goog** [comment] 2023-09-20 18:26
That did not resolve the issue: https://chromium-swarm.appspot.com/task?id=64cc9ba732532b10

Trying removal of 3p packages:

`adb shell pm list packages -3 | cut -d':' -f2 | tr '\r' ' ' | xargs -r -n1 -t adb uninstall`

After:

```
$ adb shell df -h
Filesystem                             Size  Used Avail Use% Mounted on
tmpfs                                  923M  692K  923M   1% /dev
tmpfs                                  923M     0  923M   0% /mnt
/dev/block/bootdevice/by-name/system   2.3G  1.7G  617M  75% /system
/dev/block/bootdevice/by-name/userdata  11G  612M   10G   6% /data
/dev/block/bootdevice/by-name/cache    248M  296K  243M   1% /cache
/dev/block/bootdevice/by-name/persist   27M  440K   26M   2% /persist
/dev/block/bootdevice/by-name/dsp       12M  3.6M  7.7M  32% /dsp
/dev/block/bootdevice/by-name/modem     94M   70M   23M  76% /firmware
/dev/block/bootdevice/by-name/fsg      1.9M  1.9M     0  100% /fsg
/dev/block/bootdevice/by-name/oem      635M   96M  527M  16% /oem
tmpfs                                  923M     0  923M   0% /storage
/data/media                             11G  612M   10G   6% /storage/emulated
```

**Comment by yusuf-goog** [comment] 2023-09-20 20:14
One of the failures on linux-13 is:
`[INSTALL_FAILED_INSUFFICIENT_STORAGE: Package couldn't be installed in /data/app/com.yourcompany.integration_ui-1`

**Comment by yusuf-goog** [comment] 2023-09-20 21:45
Looks like device is now working, which points to `adb shell pm list packages -3 | cut -d':' -f2 | tr '\r' ' ' | xargs -r -n1 -t adb uninstall` as a possible solution. 

Please add any other devices which you see hitting this state and I'll test with this change.

**Comment by yusuf-goog** [comment] 2023-09-20 21:45
cc @christopherfujino

**Comment by keyonghan** [comment] 2023-09-25 15:53
The tree is pretty flaky due to this issue. I see issues on these bots: linux-11, linux-23 and linux-25.

@yusuf-goog After running those commands, have you tried `reboot` the device, which is necessary to release the storage?

**Comment by keyonghan** [comment] 2023-09-25 16:12
> Those bots were not cleaned up or rebooted. Only 13 and 15. These bots should be cleaned up via device doctor. Changes incoming for that.

Oh, okay. BTW: I meant the phones need a reboot. Bots will be rebooted whenever a task fails, and we need to add the device reboot to the post recovery logic.

**Comment by yusuf-goog** [comment] 2023-09-25 19:39
I recovered linux-11 and linux-23. I am waiting on our code changes to device doctor to try and automatically recover linux-25.

**Comment by sealesj** [comment] 2023-10-02 18:22
@yusuf-goog Are there any other pending changes on this before closing?

**Comment by sealesj** [comment] 2023-10-02 21:05
Closing for now since the device doctor changes have merged

**Comment by keyonghan** [comment] 2023-10-03 20:47
To unblock the tree, manually recovered linux-16. /cc @yusuf-goog I moved linux-12 to staging for your validation purpose, and created https://github.com/flutter/flutter/issues/135925 to track migrating the bot back to prod.

**Comment by keyonghan** [comment] 2023-10-09 16:16
This seems still happening very frequently. @yusuf-goog has the auto recovery logic landed? As mentioned in https://github.com/flutter/flutter/issues/135035#issuecomment-1745702091, linux-12 can be used to validate the logic.
<img width="553" alt="Screenshot 2023-10-09 at 9 14 03 AM" src="https://github.com/flutter/flutter/assets/54558023/8f315228-cb6e-4d7a-a75d-41a934f545ad">

**Comment by keyonghan** [comment] 2023-10-09 21:57
Recovered the problematic linux-10 in prod.

**Comment by yusuf-goog** [comment] 2023-10-16 17:53
Requesting debug assistance from android team on out of space issues on our android devices.

We are currently tracking https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-linux-12 for changes made to device_doctor cleanup script. It looks like the cleanup procedure listed in go/flutter-luci-playbook#android-install-failed-insufficient-storage which were implemented in https://github.com/flutter/cocoon/blob/main/cipd_packages/device_doctor/lib/src/android_device.dart#L452 does not seem to be working consistently.

1) NOTE: we currently only perform cleanup after an build errors (rather than before/after each build). So you would expect to see an out of space error build, before the clean up runs.

2) Something has changed recently, where these out of space failures have become an issue, is there some build changes that could lead to filling up the devices?

3) When looking at space usage before/after cleanup, the numbers do not seem to be that different (see https://github.com/flutter/flutter/issues/135035#issuecomment-1728187773 and https://github.com/flutter/flutter/issues/135035#issuecomment-1728234689 as examples).

cc @reidbaker @camsim99

**Comment by reidbaker** [comment] 2023-10-16 19:00
Paid with @yusuf-goog and he has a few paths forward.

**Comment by yusuf-goog** [comment] 2023-10-16 19:41
Working with @reidbaker we made some observations and paths moving forward:

* Looks like previous observations that the device is not actually running out of storage space is true (based on `df` output). Its likely the symptom for a differnt underlying issue (e.g. https://stackoverflow.com/questions/4709137/solution-to-install-failed-insufficient-storage-error-on-android)

* We ran the following to clean up 3p packages on the linux-12 device:
```
flutter@flutter-devicelab-linux-12:~$ adb shell pm list packages -u | grep com.example
package:com.example.image_list
package:com.example.app
package:com.example.activitydestroy.app
flutter@flutter-devicelab-linux-12:~$ adb shell pm list packages -f | grep com.example
package:/data/app/com.example.image_list-1/base.apk=com.example.image_list
package:/data/app/com.example.app-1/base.apk=com.example.app
package:/data/app/com.example.activitydestroy.app-1/base.apk=com.example.activitydestroy.app
flutter@flutter-devicelab-linux-12:~$ adb shell pm uninstall com.example.app
Success
flutter@flutter-devicelab-linux-12:~$ adb shell pm uninstall com.example.image_list
Success
flutter@flutter-devicelab-linux-12:~$ adb shell pm uninstall com.example.activitydestroy.app
Success
flutter@flutter-devicelab-linux-12:~$ adb shell pm list packages -u | grep com.exam
```
and brought the host back into service to see the effect of cleanup of existing packages. In case we were not complete removing all packages during the cleanup phase.

* Other thoughts on possible causes is fragmented/corrupted flash memory

If the device continues to exhibit issues we will try:

* Factory reset: which should cleanup any fragmentation, etc.
* If that fails, it could be the device memory is at end of life. Check to see if these errors happen on any of the new device (non- moto G4) devices in the lab.

**Comment by yusuf-goog** [comment] 2023-10-16 19:53
Looks like the [build](https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8767054668732704497/+/u/run_platform_views_scroll_perf_impeller__timeline_summary/test_stdout) right after our cleanup, failed with insufficient storage, but for a different package:

/data/app/dev.benchmarks.platform_views_layout-1

This is not in the cleanup path of the device_doctor recovery code either, since we look for packages containing: `'/data/app/com.example'| '/data/app/com.yourcompany' | 'flutter'`

**Comment by yusuf-goog** [comment] 2023-10-16 19:55
The package does show up in the 3p list:

```
athene:/ $ pm list packages -3
package:com.example.platform_channels_benchmarks
```

**Comment by yusuf-goog** [comment] 2023-10-17 20:59
Looks like linux-12 has not been experiencing any insufficient space errors since the last device_doctor push. 

I'm going to tag the package with `release` and start pushing it out to prod.

For reference, the currently tagged version as `release` is https://chrome-infra-packages.appspot.com/p/flutter/device_doctor/linux-amd64/+/release

**Comment by yusuf-goog** [comment] 2023-10-17 21:16
will use linux-10 as testbed for `prod` machine for new device doctor recovery procedure.

Currently on linux-10:
```
130|athene:/ $ pm list packages -3
package:io.flutter.examples.platform_channel
package:com.example.image_list
package:com.example.app
package:io.flutter.examples.flutter_view
```

**Comment by yusuf-goog** [comment] 2023-10-17 22:07
Previously deployed devicedoctor on linux-10:

`zo8N5iR6MgO4ZcEPmD1Ar37rO4yu3NE9O9kfoYZatdMC`

setting `release` tag to new version (currently tagged with `staging`):

`l5ugKqUTYj6hTVnpPpFoyNJTN12IsnT1kLoW4FcM9zkC`

**Comment by yusuf-goog** [comment] 2023-10-17 22:17
deployed to linux-22, which has seen the most recent `insufficient space` errors.

**Comment by yusuf-goog** [comment] 2023-10-17 22:28
Getting this error on linux-22:

```724 2023-10-17 22:20:12.348 I: device doctor recovery: b'Device recovery: deleting package caches...\n'
724 2023-10-17 22:20:12.349 E: device doctor recovery error: b'* daemon not running; starting now at tcp:5037\n* daemon started successfully\nUnhandled exception:\nException: Error: Could not access the Package Manager.  Is the system running?\n\n#0      AndroidDevice.deletePackageCache (package:device_doctor/src/android_device.dart:391)\n#1      AndroidDevice.cleanDevice (package:device_doctor/src/android_device.dart:458)\n<asynchronous suspension>\n#2      AndroidDevice.recover (package:device_doctor/src/android_device.dart:383)\n<asynchronous suspension>\n#3      AndroidDeviceDiscovery.recoverDevices (package:device_doctor/src/android_device.dart:182)\n<asynchronous suspension>\n#4      main (file:///b/s/w/ir/x/w/cocoon/cipd_packages/device_doctor/bin/main.dart:85)\n<asynchronous suspension>\n'```

(similar to some other machines)

**Comment by yusuf-goog** [comment] 2023-10-24 18:47
This is no longer happening across the fleet, reducing the priority to P1

**Comment by keyonghan** [comment] 2023-10-25 16:08
Just spotted that Linux-8 seems still hitting this issue:https://ci.chromium.org/ui/p/flutter/builders/prod/Linux_android%20fast_scroll_large_images__memory/10558/overview

**Comment by yusuf-goog** [comment] 2023-10-25 16:32
FYI linux-8 also has a moto G4.

**Comment by keyonghan** [comment] 2023-10-27 18:06
F.Y.I. Linux-8 is still causing flakes and tree intermittently close. I have manually quarantined the bot: https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-linux-8

**Comment by godofredoc** [comment] 2023-10-27 18:12
I'll take a look, please do not execute anything on this test bed for a few hours.

**Comment by godofredoc** [comment] 2023-10-27 18:27
Things to check:

- [ ] is cleanup logic running? which version?

**Comment by godofredoc** [comment] 2023-10-27 19:42
Cleanup logic is running on_after_task with a task failure. The following is a sample:

```
 7774 755 2023-10-27 16:41:44.485 I: device doctor recovery: b'Device recovery: deleting package caches...
Uninstalling package com.android.cts.priv.ctsshim : STDOUT(Success)
Uninstalling package com.google.android.youtube : STDOUT(Success)
Uninstalling package com.google.android.ext.services : STDOUT(Success)
Uninstalling package com.motorola.motocare : STDOUT(Success)
Uninstalling package com.android.providers.telephony : STDOUT(Success)
Uninstalling package com.google.android.gallery3d : STDOUT(Success)
Uninstalling package cci.usage : STDOUT(Success)
Uninstalling package com.android.sdm.plugins.connmo : STDOUT(Success)
Uninstalling package com.google.android.googlequicksearchbox : STDOUT(Success)
Uninstalling package com.android.providers.calendar : STDOUT(Success)
Uninstalling package com.android.providers.media : STDOUT(Success)
Uninstalling package com.qti.service.colorservice : STDOUT(Success)
Uninstalling package com.google.android.onetimeinitializer : STDOUT(Success)
Uninstalling package com.google.android.ext.shared : STDOUT(Success)
Uninstalling package com.motorola.brapps : STDOUT(Success)
Uninstalling package com.motorola.bug2go : STDOUT(Success)
Uninstalling package com.android.wallpapercropper : STDOUT(Success)
Uninstalling package com.quicinc.cne.CNEService : STDOUT(Success)
Uninstalling package com.motorola.ccc.devicemanagement : STDOUT(Success)
Uninstalling package com.motorola.android.fmradio : STDOUT(Success)
Uninstalling package com.android.documentsui : STDOUT(Success)
Uninstalling package com.motorola.android.settings.modemdebug : STDOUT(Success)
Uninstalling package com.android.externalstorage : STDOUT(Success)
Uninstalling package com.android.htmlviewer : STDOUT(Success)
Uninstalling package com.android.mms.service : STDOUT(Success)
Uninstalling package com.android.providers.downloads : STDOUT(Success)
Uninstalling package com.motorola.coresettingsext : STDOUT(Success)
Uninstalling package com.motorola.wappushsi : STDOUT(Success)
Uninstalling package com.google.android.apps.messaging : STDOUT(Success)
Uninstalling package com.motorola.android.settings.diag_mdlog : STDOUT(Success)
Uninstalling package com.motorola.entitlement : STDOUT(Success)
Uninstalling package com.motorola.att.phone.extensions : STDOUT(Success)
Uninstalling package com.motorola.ccc.checkin : STDOUT(Success)
Uninstalling package com.motorola.programmenu : STDOUT(Success)
Uninstalling package com.motorola.ccc.mainplm : STDOUT(Success)
Uninstalling package com.motorola.motgeofencesvc : STDOUT(Success)
Uninstalling package com.google.android.configupdater : STDOUT(Success)
Uninstalling package com.motorola.ccc.ota : STDOUT(Success)
Uninstalling package com.motorola.ccc.notification : STDOUT(Success)
Uninstalling package com.android.defcontainer : STDOUT(Success)
Uninstalling package com.android.providers.downloads.ui : STDOUT(Success)
Uninstalling package com.android.vending : STDOUT(Success)
Uninstalling package com.android.pacprocessor : STDOUT(Success)
Uninstalling package com.motorola.pgmsystem2 : STDOUT(Success)
Uninstalling package com.motorola.motodisplay.env : STDOUT(Success)
Uninstalling package com.motorola.ptt.prip : STDOUT(Success)
Uninstalling package com.android.certinstaller : STDOUT(Success)
Uninstalling package com.android.carrierconfig : STDOUT(Success)
Uninstalling package com.google.android.marvin.talkback : STDOUT(Success)
Uninstalling package com.motorola.digitalpersonalization : STDOUT(Success)
Uninstalling package android : STDOUT(Success)
Uninstalling package com.android.contacts : STDOUT(Success)
Uninstalling package com.motorola.android.provisioning : STDOUT(Success)
Uninstalling package com.google.android.apps.inputmethod.hindi : STDOUT(Success)
Uninstalling package com.lenovo.FileBrowser2 : STDOUT(Success)
Uninstalling package com.android.egg : STDOUT(Success)
Uninstalling package com.android.mtp : STDOUT(Success)
Uninstalling package com.android.stk : STDOUT(Success)
Uninstalling package com.android.backupconfirm : STDOUT(Success)
Uninstalling package com.google.android.launcher : STDOUT(Success)
Uninstalling package com.motorola.timeweatherwidget : STDOUT(Success)
Uninstalling package com.google.android.deskclock : STDOUT(Success)
Uninstalling package org.codeaurora.ims : STDOUT(Success)
Uninstalling package com.android.statementservice : STDOUT(Success)
Uninstalling package com.republicwireless.tel : STDOUT(Success)
Uninstalling package com.google.android.gm : STDOUT(Success)
Uninstalling package com.motorola.motocit : STDOUT(Success\n)\nUninstalling package com.android.sdm.plugins.sprintdm : STDOUT(Success)
Uninstalling package com.google.android.apps.inputmethod.zhuyin : STDOUT(Success)
Uninstalling package com.google.android.setupwizard : STDOUT(Success)
Uninstalling package com.qualcomm.qcrilmsgtunnel : STDOUT(Success)
Uninstalling package com.android.providers.settings : STDOUT(Success)
Uninstalling package com.android.sharedstoragebackup : STDOUT(Success)
Uninstalling package com.google.android.music : STDOUT(Success)
Uninstalling package com.android.printspooler : STDOUT(Success)
Uninstalling package com.motorola.android.sepolicyupdate : STDOUT(Success)
Uninstalling package com.motorola.colorprofiles : STDOUT(Success)
Uninstalling package com.android.sdm.plugins.diagmon : STDOUT(Success)
Uninstalling package com.android.dreams.basic : STDOUT(Success)
Uninstalling package com.android.inputdevices : STDOUT(Success)
Uninstalling package com.motorola.android.nativedropboxagent : STDOUT(Success)
Uninstalling package android.oem.overlay : STDOUT(Success)
Uninstalling package com.motorola.android.jvtcmd : STDOUT(Success)
Uninstalling package com.motorola.frameworks.singlehand : STDOUT(Success)
Uninstalling package com.motorola.motosignature.app : STDOUT(Success)
Uninstalling package com.google.android.apps.cloudprint : STDOUT(Success)
Uninstalling package com.google.android.apps.docs : STDOUT(Success)
Uninstalling package com.google.android.apps.maps : STDOUT(Success)
Uninstalling package com.android.cellbroadcastreceiver : STDOUT(Success)
Uninstalling package com.motorola.invisiblenet : STDOUT(Success)
Uninstalling package com.google.android.webview : STDOUT(Success)
Uninstalling package com.motorola.contacts.preloadcontacts : STDOUT(Success)
Uninstalling package com.android.server.telecom : STDOUT(Success)
Uninstalling package com.google.android.syncadapters.contacts : STDOUT(Success)
Uninstalling package com.motorola.android.providers.settings : STDOUT(Success)
Uninstalling package com.android.facelock : STDOUT(Success)
Uninstalling package com.android.keychain : STDOUT(Success)
Uninstalling package ca.bell.wt.android.tunesappswidget : STDOUT(Success)
Uninstalling package com.google.android.calculator : STDOUT(Success)
Uninstalling package com.android.chrome : STDOUT(Success)
Uninstalling package com.android.dialer : STDOUT(Success)
Uninstalling package com.google.android.packageinstaller : STDOUT(Success)
Uninstalling package com.motorola.ptt.prip.br : STDOUT(Success)
Uninstalling package com.google.android.gms : STDOUT(Success)
Uninstalling package com.google.android.gsf : STDOUT(Success)
Uninstalling package com.google.android.ims : STDOUT(Success)
Uninstalling package com.google.android.tts : STDOUT(Success)
Uninstalling package com.verizon.omadm : STDOUT(Success)
Uninstalling package com.android.calllogbackup : STDOUT(Success)
Uninstalling package com.google.android.partnersetup : STDOUT(Success)
Uninstalling package com.motorola.genie : STDOUT(Success)
Uninstalling package com.fingerprints.serviceext : STDOUT(Success)
Uninstalling package com.motorola.setup : STDOUT(Success)
Uninstalling package com.google.android.videos : STDOUT(Success)
Uninstalling package com.motorola.retailconfig : STDOUT(Success)
Uninstalling package com.motorola.lifetimedata : STDOUT(Success)
Uninstalling package com.motorola.appdirectedsmsproxy : STDOUT(Success)
Uninstalling package com.android.proxyhandler : STDOUT(Success)
Uninstalling package com.google.android.feedback : STDOUT(Success)
Uninstalling package com.google.android.printservice.recommendation : STDOUT(Success)
Uninstalling package com.google.android.apps.photos : STDOUT(Success)
Uninstalling package com.google.android.calendar : STDOUT(Success)
Uninstalling package com.motorola.onetimeinitializer : STDOUT(Success)
Uninstalling package com.android.managedprovisioning : STDOUT(Success)
Uninstalling package com.motorola.launcherconfig : STDOUT(Success)
Uninstalling package com.motorola.demo : STDOUT(Success)
Uninstalling package com.motorola.hide : STDOUT(Success)
Uninstalling package com.motorola.moto : STDOUT(Success)
Uninstalling package com.motorola.slpc : STDOUT(Success)
Uninstalling package com.android.sdm.plugins.dcmo : STDOUT(Success)
Uninstalling package com.android.providers.partnerbookmarks : STDOUT(Success)
Uninstalling package com.google.android.gsf.login : STDOUT(Success)
Uninstalling package com.android.wallpaper.livepicker : STDOUT(Success)
Uninstalling package com.motorola.carriersettingsext : STDOUT(Success)
Uninstalling package com.motorola.motocare.internal : STDOUT(Success)
Uninstalling package com.motorola.storageoptimizer : STDOUT(Success)
Uninstalling package com.google.android.inputmethod.korean : STDOUT(Success)
Uninstalling package com.motorola.fmplayer : STDOUT(Success)
Uninstalling package com.google.android.backuptransport : STDOUT(Success)
Uninstalling package com.motorola.audioeffects : STDOUT(Success)
Uninstalling package com.motorola.msimsettings : STDOUT(Success)
Uninstalling package com.android.bookmarkprovider : STDOUT(Success)
Uninstalling package com.android.settings : STDOUT(Success)
Uninstalling package com.google.android.inputmethod.pinyin : STDOUT(Success)
Uninstalling package com.android.sprint.hiddenmenuapp : STDOUT(Success)
Uninstalling package com.qualcomm.location : STDOUT(Success)
Uninstalling package com.android.omadm.service : STDOUT(Success)
Uninstalling package com.android.cts.ctsshim : STDOUT(Success)
Uninstalling package com.lmi.motorola.rescuesecurity : STDOUT(Success)
Uninstalling package com.motorola.slpc_sys : STDOUT(Success)
Uninstalling package com.qualcomm.qti.tetherservice : STDOUT(Success)
Uninstalling package com.motorola.actions : STDOUT(Success)
Uninstalling package com.android.vpndialogs : STDOUT(Success)
Uninstalling package com.google.android.talk : STDOUT(Success)
Uninstalling package com.motorola.bach.modemstats : STDOUT(Success)
Uninstalling package com.android.phone : STDOUT(Success)
Uninstalling package com.android.shell : STDOUT(Success)
Uninstalling package com.android.wallpaperbackup : STDOUT(Success)
Uninstalling package com.android.providers.blockednumber : STDOUT(Success)
Uninstalling package com.android.providers.userdictionary : STDOUT(Success)
Uninstalling package com.android.emergency : STDOUT(Success)
Uninstalling package com.motorola.cameraone : STDOUT(Success)
Uninstalling package com.google.android.inputmethod.japanese : STDOUT(Success)
Uninstalling package com.android.location.fused : STDOUT(Success)
Uninstalling package com.android.systemui : STDOUT(Success)
Uninstalling package com.motorola.motodisplay : STDOUT(Success)
Uninstalling package com.motorola.easyprefix : STDOUT(Success)
Uninstalling package com.android.bluetoothmidiservice : STDOUT(Success)
Uninstalling package com.example.platform_channels_benchmarks : STDOUT(Success)
Uninstalling package com.android.bluetooth : STDOUT(Success)
Uninstalling package com.qualcomm.timeservice : STDOUT(Success)
Uninstalling package com.qualcomm.atfwd : STDOUT(Success)
Uninstalling package com.motorola.config.wifi : STDOUT(Success)
Uninstalling package com.android.providers.contacts : STDOUT(Success)
Uninstalling package com.android.captiveportallogin : STDOUT(Success)
Uninstalling package com.google.android.inputmethod.latin : STDOUT(Success)
Uninstalling package com.motorola.android.providers.chromehomepage : STDOUT(Success)
Uninstalling package com.motorola.imagertuning_athene : STDOUT(Success)
Device recovery: deleting 3P packages...
Device recovery: rebooting...'
 7775 755 2023-10-27 16:41:44.486 E: device doctor recovery error: b'* daemon not running; starting now at tcp:5037\n* daemon started successfully'
```

**Comment by godofredoc** [comment] 2023-10-27 20:02
The problem is here https://cs.opensource.google/flutter/cocoon/+/main:cipd_packages/device_doctor/lib/src/android_device.dart;l=431?q=deleting%20package%20caches&ss=flutter%2Fcocoon

The apps are not being uninstalled because they are returning package names like `package:com.example.platform_channels_benchmarks` and the filter is using file paths. Furthermore as we are requesting only third party packages we can delete all of them without filters.

**Comment by godofredoc** [comment] 2023-10-28 03:38
Tests installing the following packages are not cleaning up the app:

* package:com.example.image_list
* package:com.yourcompany.integration_ui
* package:com.example.app
* package:com.example.platform_channels_benchmarks

**Comment by yusuf-goog** [comment] 2023-10-30 18:13
Recovery code is running and cleaning up devices. closing.

**Closed by yusuf-goog** 2023-10-30 18:13 UTC
Labels: P2, infra: device lab
