### ISSUE TITLE
Pubsec.yaml issues.

### ISSUE THREAD

**Issue by Jossyboydgenius** [flutter/flutter#143078] opened 2024-02-07 16:05 UTC
### Steps to reproduce

Command lines or steps to take to get out of these loops.

### Actual results

I upgraded my packages, and when I saved it showed me the error below:
Because every version of flutter_test from sdk depends on web 0.3.0 and myapp depends on web ^0.4.2, flutter_test from sdk is forbidden.
So, because myapp depends on flutter_test from sdk, version solving failed.
exit code 1.

It repeats the same error across the 6 packages till downgrade them all to the suggested version, but still shows the message below:

myapp] flutter pub get --no-example
Resolving dependencies...
  matcher 0.12.16 (0.12.16+1 available)
  material_color_utilities 0.5.0 (0.8.0 available)
  meta 1.10.0 (1.12.0 available)
  path 1.8.3 (1.9.0 available)
  test_api 0.6.1 (0.7.0 available)
  web 0.3.0 (0.4.2 available)
Got dependencies!
6 packages have newer versions incompatible with dependency constraints.
Try `flutter pub outdated` for more information.
exit code 0

Trust me I've done everything I could even tried a remote desktop when I called out for help but still all the same. It's frustrating.

Please help the newbie in Flutter.

### Logs

Note: web is pinned to version 0.3.0 by flutter_test from the flutter SDK.
See https://dart.dev/go/sdk-version-pinning for details.

Because every version of flutter_test from sdk depends on test_api 0.6.1 and myapp depends on test_api ^0.7.0, flutter_test from sdk is forbidden.
So, because myapp depends on flutter_test from sdk, version solving failed.

Because every version of flutter_test from sdk depends on web 0.3.0 and myapp depends on web ^0.4.2, flutter_test from sdk is forbidden.
So, because myapp depends on flutter_test from sdk, version solving failed.
exit code 1

### Flutter Doctor output

flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.9, on macOS 14.3 23D56 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[!] Xcode - develop for iOS and macOS (Xcode 15.2)
    ✗ Unable to get list of installed Simulator runtimes.
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.1)
[✓] VS Code (version 1.86.0)
[✓] Connected device (2 available)
[✓] Network resources

! Doctor found issues in 1 category.

**Comment by amrgetment** [comment] 2024-02-07 17:01
@Jossyboydgenius  use dependency_overrides like
```
dependency_overrides:
  analyzer: ^6.4.1

```

**Comment by stuartmorgan** [comment] 2024-02-07 20:58
> It repeats the same error across the 6 packages till downgrade them all to the suggested version, but still shows the message below:
> 
> ```
> myapp] flutter pub get --no-example
> Resolving dependencies...
>   matcher 0.12.16 (0.12.16+1 available)
>   material_color_utilities 0.5.0 (0.8.0 available)
>   meta 1.10.0 (1.12.0 available)
>   path 1.8.3 (1.9.0 available)
>   test_api 0.6.1 (0.7.0 available)
>   web 0.3.0 (0.4.2 available)
> Got dependencies!
> 6 packages have newer versions incompatible with dependency constraints.
> Try `flutter pub outdated` for more information.
> exit code 0
> ```

Exit code 0 is successful; the "6 packages have newer versions incompatible with dependency constraints" message is informational.

What you have described here is correct behavior, leading to a working app with the correct versions of packages based on what is compatible with the version of Flutter you are using. Flutter pins some specific dependencies, so it is expected behavior that you can't always use the newest version of every package with a given version of Flutter.

Closing as this is intended behavior.

**Closed by stuartmorgan** 2024-02-07 20:58 UTC

**Comment by stuartmorgan** [comment] 2024-02-07 20:59
@amrgetment In the future, please don't post commands in our issue tracker that are likely to break people's projects in hard-to-understand ways, especially with no context at all.

**Comment by Jossyboydgenius** [comment] 2024-02-07 21:06
Alright, like I said I'm new to newbie so I don't know much of this RN.
Thanks anyway.
