### ISSUE TITLE
Flutter build appbundle with two flavorDimensions fail with Gradle build failed to produce an .aab file

### ISSUE THREAD

**Issue by brightknight08** [flutter/flutter#65265] opened 2020-09-04 20:16 UTC
I was having trouble building a flutter app with `2 flavor dimensions` and `2 flavors` for each dimension (total of 4 variants, 
excluding the debug and release modes). 

*Please note that I can successfully build the appbundle without this error when there is only
one flavorDimension*

here's a minimal flutter app repo: https://github.com/brightknight08/flutter_build_appbundle_error to reproduce

`flutter build appbundle --release --flavor signedprod` would result in an error:
``` cli
Gradle build failed to produce an .aab file. It's likely that this file was generated under
E:\lab\flutter_build_appbundle_error\build, but the tool couldn't find it.
```

***HOWEVER***, inspecting the `\build\app\outputs\bundle\` folder, i can find the folders and .aab files there.
![image](https://user-images.githubusercontent.com/13560209/92281722-d0de8700-ef2e-11ea-9968-eea772f0ccf6.png)

---

`flutter doctor -v`
```cli
PS E:\lab\flutter_build_appbundle_error> flutter doctor -v
[✓] Flutter (Channel stable, 1.20.2, on Microsoft Windows [Version 10.0.19041.450], locale en-US)
    • Flutter version 1.20.2 at C:\flutter
    • Framework revision bbfbf1770c (3 weeks ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1


[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at E:\asdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = E:\asdk
    • Java binary at: E:\as\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 4.0)
    • Android Studio at E:\as
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.48.2)
    • VS Code at C:\Users\tim_m\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.14.0

[✓] Connected device (1 available)
    • P[redacted]...droid-arm64 • Android 10 (API 29)

• No issues found!
PS E:\lab\flutter_build_appbundle_error>
```

*I made this new issue because the other ones related to this has become a chat thread with some salty people*

**Comment by TahaTesser** [comment] 2020-09-07 14:03
Closing as duplicate of https://github.com/flutter/flutter/issues/65264

**Closed by TahaTesser** 2020-09-07 14:03 UTC
