### ISSUE TITLE
flutter crashes on flutter doctor in CMD

### ISSUE THREAD

**Issue by uttaransarkar** [flutter/flutter#38154] opened 2019-08-11 08:32 UTC
[flutter_02.log](https://github.com/flutter/flutter/files/3489703/flutter_02.log)

## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```

**Comment by jonahwilliams** [comment] 2019-08-12 02:56
Duplicate of https://github.com/flutter/flutter/issues/37223

**Closed by jonahwilliams** 2019-08-12 02:56 UTC
