### ISSUE TITLE
Flutter DropdownButtonFormField widget does not provide a way to center text vertically if constrained height is set

### ISSUE THREAD

**Issue by henry-chan-ftd** [flutter/flutter#108789] opened 2022-08-02 08:05 UTC
## Use case
There is currently no method to center the item text vertically within a bordered-style form field appropriately, contentPadding property is not sufficient for customization if the widget is wrapped with constrained upper height.

```dart
String? val;
List<String> samples = ['A', 'B', 'C'];

LimitedBox(
     maxHeight: 30,
     child: DropdownButtonFormField<String?>(
          decoration: InputDecoration(
              contentPadding: EdgeInsets.only(bottom: 10.5 * scrH),
                focusedBorder: UnderlineInputBorder(
                    borderSide:
                        BorderSide(color: Colors.transparent)),
                enabledBorder: UnderlineInputBorder(
                    borderSide:
                    BorderSide(color: Colors.transparent)),
            ),
            isExpanded: true,
            value: val,
            alignment: AlignmentDirectional.centerStart,
            items: samples
                .map((j) => DropdownMenuItem(
                    value: j,
                    child: Text(j)))
                .toList(),
            icon: Image.asset(
              'images/dropdown_arrow.png',
              scale: 2.0,
            ).padding(right: 10),
            onChanged: (newVal) => setState(() => val = newVal),
            hint: Text('Unselected'),
          )
)
```
## Proposal

```dart
DropdownButtonFormField(
        ...
        itemPosition: Alignment.centerLeft, // New property for setting item offset position, type AlignmentGeometry
)
```

**Comment by maheshmnj** [comment] 2022-08-02 11:38
Hi @henry-chan-ftd, Thanks for filing the issue. You can wrap your `DropdownMenuItem.child` in a Align widget that should allow you to align them as desired.

```dart
items: samples
    .map((j) => DropdownMenuItem(
        value: j,
        child: Align(
            alignment: Alignment.centerLeft,
            child: Text(j),
         )
     )
   ).toList(),
``` 

<details>
<summary>complete code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);
  final String title;
  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  String? val;
  List<String> samples = ['A', 'B', 'C'];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: Center(
      child: LimitedBox(
          maxHeight: 30,
          child: DropdownButtonFormField<String?>(
            decoration: InputDecoration(
              contentPadding: EdgeInsets.only(bottom: 10.5),
              focusedBorder: UnderlineInputBorder(
                  borderSide: BorderSide(color: Colors.transparent)),
              enabledBorder: UnderlineInputBorder(
                  borderSide: BorderSide(color: Colors.transparent)),
            ),
            isExpanded: true,
            value: val,
            alignment: AlignmentDirectional.centerStart,
            items: samples
                .map((j) => DropdownMenuItem(
                    value: j,
                    child: Align(
                      alignment: Alignment.centerLeft,
                      child: Text(j),
                    )))
                .toList(),
            icon: Icon(Icons.arrow_downward),
            onChanged: (newVal) => setState(() => val = newVal),
            hint: Text('Unselected'),
          )),
    ));
  }
}

```
</details>

**Comment by maheshmnj** [comment] 2022-08-02 11:39
Closing as this is not a bug and can be achieved with existing apis.

**Closed by maheshmnj** 2022-08-02 11:39 UTC
Labels: in triage

**Comment by henry-chan-ftd** [comment] 2022-08-03 01:30
Thank you for suggesting, it did sound like an accurate solution but still it incurs unexpected behavior after adopting your instruction (Align widget over child of DropdownMenuItem):
1) it does not center vertically if the dropdown box height is set less than kMinInteractiveDimension, 2) Text clipping 

**Screenshots:**
1a) ![Center not vertically, text/icon pushed to bottom when contentPadding EdgeInsets.zero](https://user-images.githubusercontent.com/105620782/182504018-90808ec3-da7c-464f-a74f-fcb98d90060e.png)

1b) ![Text clipped when no contentPadding](https://user-images.githubusercontent.com/105620782/182504353-25fc484b-39f4-4ec4-a10a-b515235a1e5d.png)

2) ![Text clipped](https://user-images.githubusercontent.com/105620782/182504021-c308c9d3-7f2f-4fc7-a86a-15b7de739bb1.png)
