### ISSUE TITLE
Setup Flutter engine environment and build engine on M1 (Apple Silicon ARM64)

### ISSUE THREAD

**Issue by eggfly** [flutter/flutter#96745] opened 2022-01-17 16:45 UTC
# Problem 😭
There are some errors if we setup flutter engine environment in standard way, including:
* `gclient sync` cannot find third_party/android_tools (including ndk and sdk) and third_party/java packages (openjdk) in arm64 on M1 chip macOS
* Cannot download prebuilt Dart SDK in arm64, and some header in Dart check 32/64 bit machine matching failed
* `tools/gn` shows `//out/android_debug/clang_x64/gen_snapshot` is not the right target, but it generates a target `//out/android_debug/clang_arm64/gen_snapshot` instead and failed
* objcopy command try to find the wrong path
* Some other errors

Related errors and failure images:
![image](https://user-images.githubusercontent.com/922837/149812884-643eec19-23b5-49a6-879c-b665ecbe5148.png)

<img width="643" alt="See BUILD ON95 oh1ch CRused PNe r1le te Be snecdeg" src="https://user-images.githubusercontent.com/922837/149812682-44e8a2c2-e43a-42e3-b702-d4b3edee1118.png">

<img width="1436" alt="Pasted Graphic 2" src="https://user-images.githubusercontent.com/922837/149812699-fb646408-297a-4d9c-8baa-e384565694b9.png">

<img width="990" alt="Pasted Graphic 5" src="https://user-images.githubusercontent.com/922837/149812789-c6601548-6d80-4c56-a0d3-79ad6f23eccc.png">

# Workaround 😊
So I dig into the var `host_cpu` and find it's maybe originally provided by `depot_tools`, and I temporarily do some modification, force cpu_arch detech logics to x64 in `depot_tools` as a workaround:
```diff
depot_tools$ git diff 
diff --git a/cipd b/cipd
index 91fbe165..d1903d77 100755
--- a/cipd
+++ b/cipd
@@ -46,13 +46,13 @@ if [ -z $ARCH ]; then
       ARCH="${UNAME}"
       ;;
     aarch64)
-      ARCH=arm64
+      ARCH=amd64
       ;;
     armv7l)
       ARCH=armv6l
       ;;
     arm*)
-      ARCH="${UNAME}"
+      ARCH="amd64"
       ;;
     *86)
       ARCH=386
diff --git a/detect_host_arch.py b/detect_host_arch.py
index cf4bfec7..6a4e8566 100755
--- a/detect_host_arch.py
+++ b/detect_host_arch.py
@@ -44,7 +44,7 @@ def HostArch():
   if host_arch == 'arm64' and platform.architecture()[0] == '32bit':
     host_arch = 'arm'
 
-  return host_arch
+  return 'x64'
 
 def DoMain(_):
   """Hook to be called from gyp without starting a separate python
diff --git a/gclient.py b/gclient.py
index 446be28d..71b087b5 100755
--- a/gclient.py
+++ b/gclient.py
@@ -1283,7 +1283,7 @@ class Dependency(gclient_utils.WorkItem, DependencySettings):
         'checkout_ppc': 'ppc' in self.target_cpu,
         'checkout_s390': 's390' in self.target_cpu,
         'checkout_x64': 'x64' in self.target_cpu,
-        'host_cpu': detect_host_arch.HostArch(),
+        'host_cpu': 'x64',
     }
```

And also we should let it download in `src/flutter/DEPS`: ( or maybe this is not a must after cheating in depot_tools):
```diff
flutter_engine/src/flutter$ git diff 
diff --git a/DEPS b/DEPS
index c72b4d7e3d..32d7b0a97a 100644
--- a/DEPS
+++ b/DEPS
@@ -66,7 +66,7 @@ vars = {
   'download_dart_sdk': True,
 
   # Checkout Android dependencies only on platforms where we build for Android targets.
-  'download_android_deps': 'host_cpu == "x64" and (host_os == "mac" or host_os == "linux")',
+  'download_android_deps': '(host_os == "mac" or host_os == "linux")',
 
   # Checkout Windows dependencies only if we are building on Windows.
   'download_windows_deps' : 'host_os == "win"',
```

Do these mods and rerun `gclient sync -D` it will prompt an arch change, and download the packages rightly.
The cipd will change from `Chrome Infra Package Deployer (cipd 2.6.2 (infra/tools/cipd/mac-arm64@PiaJs-2JM4V3hn1ffZH7wT5QV6z5Rt77aJZaCTRfspYC))` to `Chrome Infra Package Deployer (cipd 2.6.2 (infra/tools/cipd/mac-amd64@dsOLt767apUdYzHrNZ7zaQzAOZSEBHZ7ncbfUp_0zfoC))`

The cpu arch change prompt:
```
Detected CIPD client platform change to mac-amd64.
Deleting the existing client to trigger the bootstrap...
Chrome Infra Package Deployer (cipd 2.6.2 (infra/tools/cipd/mac-amd64@dsOLt767apUdYzHrNZ7zaQzAOZSEBHZ7ncbfUp_0zfoC))

Usage:  cipd [command] [arguments]
```

By forcing it from arm64 to x86, maybe it does two things:
* The macOS with M1 chip can run x86 program with Rosetta 2 translation, the toolchain, packages, android sdk, ndk, jdk and other binary in x86 will run normally
* Xcode will build the engine source files into the x86 target arch, this is a magical thing but it really does:
![image](https://user-images.githubusercontent.com/922837/149810109-eda87a0d-b9a8-4b72-887a-cf4a27ecb12e.png)

So finally it works for me to build engine from source, on MacBook Air M1 ~ 😂 

<img width="877" alt="Pasted Graphic 15" src="https://user-images.githubusercontent.com/922837/149809454-d92d3de8-2ced-40ce-98bf-293b753f2207.png">

![image](https://user-images.githubusercontent.com/922837/149811997-4eed8512-5c7b-4544-9edd-65df1aa05dd9.png)

**Comment by omarzl** [comment] 2022-03-01 02:45
Really useful! I had the same issue when compiling the iOS engine in M1
But I only applied the workaround in `depot_tools`, since there isn't a "download iOS deps" as in Android

Anyway here is a zip with the two patches in case anyone just wants apply them
[M1FlutterEnginePatchs.zip](https://github.com/flutter/flutter/files/8158378/M1FlutterEnginePatchs.zip)

**Comment by litang0908** [comment] 2022-04-05 10:23
It worked, thanks !

**Comment by spkersten** [comment] 2022-04-24 15:23
In addition to the diffs in "Workaround", I needed one more change:

```diff
--- a/cipd
+++ b/cipd
@@ -46,7 +46,7 @@ if [ -z $ARCH ]; then
       if [ $OS == 'mac' ]; then
         TRANSLATED=`/usr/sbin/sysctl -n sysctl.proc_translated 2> /dev/null || echo 0`
         if [ $TRANSLATED == "1" ]; then
-          ARCH="arm64"
+          ARCH="amd64"
         fi
       fi
       ;;
```

**Comment by kismet-** [comment] 2022-05-08 01:29
How can I build other binaries like, flutter_tester, impellerc, etc, for Apple Silicon ARM64?

**Comment by dkbast** [comment] 2022-05-09 21:49
@eggfly do you have any idea how to also build the custom embedder with this x64 workaround?

I'm trying to build the example on my M1 and could get the engine to compile so far but now I'm stuck 

https://github.com/flutter/engine/tree/main/examples/glfw

```
glfw ➤ ./run.sh                                                                                                                                                                                              git:main*
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/dkbast/src/github.com/flutter/engine/examples/glfw/debug
[ 50%] Building CXX object CMakeFiles/flutter_glfw.dir/FlutterEmbedderGLFW.cc.o
[100%] Linking CXX executable flutter_glfw
ld: warning: ignoring file /Users/dkbast/src/github.com/flutter/engine/src/out/host_debug_unopt/libflutter_engine.dylib, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
Undefined symbols for architecture arm64:
  "_FlutterEngineRun", referenced from:
      RunFlutter(GLFWwindow*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in FlutterEmbedderGLFW.cc.o
  "_FlutterEngineSendPointerEvent", referenced from:
      GLFWcursorPositionCallbackAtPhase(GLFWwindow*, FlutterPointerPhase, double, double) in FlutterEmbedderGLFW.cc.o
  "_FlutterEngineSendWindowMetricsEvent", referenced from:
      GLFWwindowSizeCallback(GLFWwindow*, int, int) in FlutterEmbedderGLFW.cc.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [flutter_glfw] Error 1
make[1]: *** [CMakeFiles/flutter_glfw.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by dkbast** [comment] 2022-05-11 19:18
@cbracken I can confirm that this now compiles on an M1 Max - as I understand we are still limited to running in "rosetta" mode (macOS-x86_64) instead of utilising apple silicon (macOS-arm64) due to some dependencies not being available for macOS-arm64 yet. 

As stated above I'm trying to compile the glfw example from the examples folder but I get an architecture miss-match - can you point me to the correct flag to specify the target architecture when building the custom embedder?

**Comment by cbracken** [comment] 2022-05-12 01:18
@dkbast that's correct.

Closing this issue as the basic issue of building on arm64 macs is resolved. I've opened https://github.com/flutter/flutter/issues/103386 to track the remaining work required to get a fully arm64 native build that doesn't rely on Rosetta.

**Closed by cbracken** 2022-05-12 01:18 UTC
Labels: engine, platform-mac, d: wiki, a: desktop, passed first triage, passed secondary triage, P5

**Comment by yx-mike** [comment] 2022-05-19 08:12
@eggfly 666666

**Comment by flar** [comment] 2022-07-17 22:10
I know that the build is only supported using Rosetta, but the android builds don't work even with Rosetta. Is that a known issue or something that broke recently?

**Comment by flar** [comment] 2022-07-17 22:11
(Basically the android tools/ndk are not downloaded at all so trying to `gn` an android build fails early.)

**Comment by ColdPaleLight** [comment] 2022-07-18 00:43
> I know that the build is only supported using Rosetta, but the android builds don't work even with Rosetta. Is that a known issue or something that broke recently?

The following workaround works for me.

```diff
flutter_engine/src/flutter$ git diff 
diff --git a/DEPS b/DEPS
index c72b4d7e3d..32d7b0a97a 100644
--- a/DEPS
+++ b/DEPS
@@ -66,7 +66,7 @@ vars = {
   'download_dart_sdk': True,
 
   # Checkout Android dependencies only on platforms where we build for Android targets.
-  'download_android_deps': 'host_cpu == "x64" and (host_os == "mac" or host_os == "linux")',
+  'download_android_deps': '(host_os == "mac" or host_os == "linux")',
```
c.f.
https://github.com/flutter/engine/blob/b438edfd1afd9a89da3e01403d41225a34a91917/DEPS#L63

**Comment by flar** [comment] 2022-07-18 03:52
> > I know that the build is only supported using Rosetta, but the android builds don't work even with Rosetta. Is that a known issue or something that broke recently?
> 
> The following workaround works for me.
> 
> ```diff
> flutter_engine/src/flutter$ git diff 
> diff --git a/DEPS b/DEPS
> index c72b4d7e3d..32d7b0a97a 100644
> --- a/DEPS
> +++ b/DEPS
> @@ -66,7 +66,7 @@ vars = {
>    'download_dart_sdk': True,
>  
>    # Checkout Android dependencies only on platforms where we build for Android targets.
> -  'download_android_deps': 'host_cpu == "x64" and (host_os == "mac" or host_os == "linux")',
> +  'download_android_deps': '(host_os == "mac" or host_os == "linux")',
> ```
> 
> c.f. https://github.com/flutter/engine/blob/b438edfd1afd9a89da3e01403d41225a34a91917/DEPS#L63

I tried that, but I then get errors trying to download various pieces:

```
Errors:
  failed to resolve perfetto/trace_to_text/mac-arm64@git_tag:v20.1 (line 29): no such tag
  failed to resolve flutter/java/openjdk/mac-arm64@version:11 (line 41): no such package: flutter/java/openjdk/mac-arm64
Error: Command 'cipd ensure -log-level error -root <My Home Dir>/Development/engine -ensure-file /var/folders/66/xlzttnjn66v9f0mgk4m6fy_w00mnw5/T/tmp7ru1kcyo.ensure' returned non-zero exit status 1
Errors:
  failed to resolve perfetto/trace_to_text/mac-arm64@git_tag:v20.1 (line 29): no such tag
  failed to resolve flutter/java/openjdk/mac-arm64@version:11 (line 41): no such package: flutter/java/openjdk/mac-arm64
```

**Comment by ColdPaleLight** [comment] 2022-07-18 04:45
> > > I know that the build is only supported using Rosetta, but the android builds don't work even with Rosetta. Is that a known issue or something that broke recently?
> > 
> > 
> > The following workaround works for me.
> > ```diff
> > flutter_engine/src/flutter$ git diff 
> > diff --git a/DEPS b/DEPS
> > index c72b4d7e3d..32d7b0a97a 100644
> > --- a/DEPS
> > +++ b/DEPS
> > @@ -66,7 +66,7 @@ vars = {
> >    'download_dart_sdk': True,
> >  
> >    # Checkout Android dependencies only on platforms where we build for Android targets.
> > -  'download_android_deps': 'host_cpu == "x64" and (host_os == "mac" or host_os == "linux")',
> > +  'download_android_deps': '(host_os == "mac" or host_os == "linux")',
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > c.f. https://github.com/flutter/engine/blob/b438edfd1afd9a89da3e01403d41225a34a91917/DEPS#L63
> 
> I tried that, but I then get errors trying to download various pieces:
> 
> ```
> Errors:
>   failed to resolve perfetto/trace_to_text/mac-arm64@git_tag:v20.1 (line 29): no such tag
>   failed to resolve flutter/java/openjdk/mac-arm64@version:11 (line 41): no such package: flutter/java/openjdk/mac-arm64
> Error: Command 'cipd ensure -log-level error -root <My Development Dir>/engine -ensure-file /var/folders/66/xlzttnjn66v9f0mgk4m6fy_w00mnw5/T/tmp7ru1kcyo.ensure' returned non-zero exit status 1
> Errors:
>   failed to resolve perfetto/trace_to_text/mac-arm64@git_tag:v20.1 (line 29): no such tag
>   failed to resolve flutter/java/openjdk/mac-arm64@version:11 (line 41): no such package: flutter/java/openjdk/mac-arm64
> ```

I had the same errors before, when I forgot to change this line of code.
https://github.com/flutter/flutter/issues/96745#issuecomment-1107862884

Here is a patch made with all the changes required by depot_tools
[depot_tools.patch.zip](https://github.com/flutter/flutter/files/9129462/depot_tools.patch.zip)

In addition to applying the patch of depot_tools, you also need to disable its updates. Good luck :)
```
# apply patch
git apply ../depot_tools.patch 
git add .
git commit -m"Apple M1 workaround"
# disable depot_tools update
./update_depot_tools_toggle.py --disable
```

**Comment by flar** [comment] 2022-07-18 05:43
> I had the same errors before, when I forgot to change this line of code. [#96745 (comment)](https://github.com/flutter/flutter/issues/96745#issuecomment-1107862884)
> 
> Here is a patch made with all the changes required by depot_tools [depot_tools.patch.zip](https://github.com/flutter/flutter/files/9129462/depot_tools.patch.zip)
> 
> In addition to applying the patch of depot_tools, you also need to disable its updates. Good luck :)

So, to answer my question, this doesn't build without workarounds installed in several files which means that the problem still exists (a workaround is not a fix). Perhaps these workarounds will go away if we get the issue to make this work without Rosetta fixed? Either way, this problem still exists.

**Comment by flar** [comment] 2022-07-18 05:44
@cbracken why was this closed when the problem still requires workarounds?

**Comment by flar** [comment] 2022-07-18 06:04
Perhaps we should have conditional variables for the path components used in DEPS that fix this so we don't have to modify depot_tools.

**Comment by flar** [comment] 2022-07-24 07:54
Filed https://github.com/flutter/flutter/issues/108241 for the remaining work to enable Android builds on Apple Silicon.

**Comment by flar** [comment] 2022-07-27 02:06
https://github.com/flutter/flutter/issues/108241 is now closed as fixed.

I verified by creating a brand new engine directory with no modifications to my depot_tools and was able to gsync, use gn to create 3 flavors of android build (debug, profile, release) and build all 3.

We should no longer require any workarounds to build host, iOS, or Android engines on Apple Silicon Macs.
