### ISSUE TITLE
Glitches on iPhone 13 Pro when UiKitView is covered by other layers

### ISSUE THREAD

**Issue by sroddy** [flutter/flutter#98756] opened 2022-02-18 17:57 UTC
## Steps to Reproduce

1. Clone https://github.com/AlessandroToschi/FlutteriPhone13ProPlatformGlitch
2. Run on iPhone 13 Pro (we don't see the bug happening on other devices nor the simulator)
3. Tap "Press me" to push the second route
4. Swipe fast the route from the left edge back and forward and observe weird glitches appearing on the whole UiKitView area.
5. Especially relevant is the fact that also the "debug" label is wrongly painted in weird positions even if it's supposed to stay in place.

**Expected results:**  No Glitches

**Actual results:**  Glitches

See also the attached video below frame by frame for reference.

https://user-images.githubusercontent.com/729934/154736641-678fb370-fc7f-4df6-9b56-6ec89bfaa895.MP4

<details>
  <summary>Logs</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.2 21D49 darwin-arm, locale it)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] IntelliJ IDEA Community Edition (version 2021.2.3)
[✓] VS Code (version 1.63.2)
[✓] Connected device (4 available)
```

</details>

**Comment by sroddy** [comment] 2022-02-18 19:46
I'm experiencing this issues since at least 2.8.0 and only on iPhone 13 Pro devices, so I'm not sure it's releated

**Comment by jmagman** [comment] 2022-02-22 18:42
Removing labels to put back in triager queue, this should be checked for duplicates, etc

**Comment by cyanglaz** [comment] 2022-02-22 20:38
I was able to reproduce it on my iphone 13 pro on flutter/master as well. 

Haven't debugged on engine yet, but I suspect it is due to a wrong frame (CGRect) of the overlay view while the platform view is animating. 

I'll add the labels back as I think it is an issue related to platform-views on iOS.

**Comment by sroddy** [comment] 2022-02-23 17:58
@cyanglaz I don't think it's just a question of a wrong frame of the overlay view, because in this example below you can see that the platform view is not animating but the textures are really behaving weirdly

https://user-images.githubusercontent.com/729934/155378723-78ecb3e5-20af-4e62-8e85-91bfdd49e287.mov

**Comment by mark8044** [comment] 2022-02-28 21:01
If we are talking about the same issue, it was for sure not in 2.8 and appeared in 2.10+, only on iOS, not in Android.  SO the problem might be localized in changes made for 2.10 from 2.8

**Comment by sroddy** [comment] 2022-03-01 15:28
@mark8044 that's why I'm saying it's not the same issue. We are running on Flutter 2.8 and we are experiencing this issue the very same way as on Flutter 2.10

**Comment by sroddy** [comment] 2022-03-08 12:23
For some reason which I can't completely understand if you set `CADisableMinimumFrameDurationOnPhone` to `true` inside the info.plist, these glitches are completely gone

**Comment by cyanglaz** [comment] 2022-03-09 00:35
Ah see: https://github.com/flutter/flutter/issues/99151#issuecomment-1062098686

cc @iskakaushik @jmagman

**Comment by jmagman** [comment] 2022-04-05 17:56
This was fixed by https://github.com/flutter/flutter/pull/100647.  The `flutter` tool will add the necessary Info.plist key when you build.

**Closed by jmagman** 2022-04-05 17:56 UTC
Labels: platform-ios, a: platform-views, P4
