### ISSUE TITLE
[tool_crash] ProcessException: Process exited abnormally:Command line invocation:    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -listxcodebuild: error: Unable to read project 'Runner.xcodeproj'.	Reason: Could not open workspace file at ~/AndroidStudioProjects/Spotlight-Flutter/ios/Runner.xcodeproj/project.xcworkspace/contents.xcworkspacedata Command: /usr/bin/xcodebuild, OS error code: 74

### ISSUE THREAD

**Issue by didierganthier** [flutter/flutter#69138] opened 2020-10-27 21:20 UTC
## Command
```
flutter create .
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ProcessException: Process exited abnormally:
Command line invocation:
    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -list

xcodebuild: error: Unable to read project 'Runner.xcodeproj'.
	Reason: Could not open workspace file at ~/AndroidStudioProjects/Spotlight-Flutter/ios/Runner.xcodeproj/project.xcworkspace/contents.xcworkspacedata Command: /usr/bin/xcodebuild, OS error code: 74
```
#0      RunResult.throwException (package:flutter_tools/src/base/process.dart:172:5)
#1      _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart:328:19)
<asynchronous suspension>
#2      XcodeProjectInterpreter.getInfo (package:flutter_tools/src/ios/xcodeproj.dart:392:50)
#3      IosProject.projectInfo (package:flutter_tools/src/project.dart:531:67)
#4      IosProject.buildSettingsForBuildInfo (package:flutter_tools/src/project.dart:513:41)
#5      IosProject._parseProductBundleIdentifier (package:flutter_tools/src/project.dart:455:56)
#6      IosProject.productBundleIdentifier (package:flutter_tools/src/project.dart:432:47)
#7      FlutterProject.organizationNames (package:flutter_tools/src/project.dart:111:19)
#8      CreateCommand.runCommand (package:flutter_tools/src/commands/create.dart:381:63)
#9      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:972:18)
#10     _rootRunUnary (dart:async/zone.dart:1198:47)
#11     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#12     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#13     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#14     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#15     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#16     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
#17     _rootRun (dart:async/zone.dart:1190:13)
#18     _CustomZone.run (dart:async/zone.dart:1093:19)
#19     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#20     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#21     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#22     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#23     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
```
```
[✓] Flutter (Channel stable, 1.22.0, on Mac OS X 10.15.6 19G2021, locale en-HT)
    • Flutter version 1.22.0 at /Users/alpha/Downloads/flutter
    • Framework revision d408d302e2 (4 weeks ago), 2020-09-29 11:49:17 -0700
    • Engine revision 5babba6c4d
    • Dart version 2.10.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/alpha/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.10.0

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.1

[✓] Connected device (1 available)
    • iPhone 12 Pro Max (mobile) • 05D5CADF-B446-45D1-A333-1AA0F3629A3F • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-1 (simulator)

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: f139b11009aeb8ed2a3a3aa8b0066e482709dde3
### Plugins
cloud_firestore-0.13.7
cloud_firestore_web-0.1.1+2
firebase_auth-0.16.1
firebase_auth_web-0.1.3+1
firebase_core-0.4.5
firebase_core_web-0.1.1+2
firebase_messaging-6.0.16
firebase_storage-3.1.6
flutter_facebook_login-3.0.0
flutter_plugin_android_lifecycle-1.0.9
geolocator-5.3.2+2
google_api_availability-2.0.4
google_sign_in-4.5.3
google_sign_in_web-0.9.2
image_picker-0.6.7+8
location_permissions-3.0.0+1
path_provider-1.6.14
path_provider_linux-0.0.1+2
path_provider_macos-0.0.4+4
sqflite-1.3.1+1
vibrate-0.0.4
video_player-0.10.12+3
video_player_web-0.1.3+2

**Comment by darshankawar** [comment] 2020-10-28 08:00
@didierganthier 
There's similar open issue describing your case, [57083](https://github.com/flutter/flutter/issues/57083).
Please follow-up there for updates. Also this if [this](https://github.com/flutter/flutter/issues/57083#issuecomment-654394040) workaround works for you.
Closing this as duplicate.

**Closed by darshankawar** 2020-10-28 08:00 UTC

**Comment by jmagman** [comment] 2021-05-13 21:07
This isn't a duplicate of #57083. Tracking instead in #63280.
