### ISSUE TITLE
Unable to run or create new project in Flutter 

### ISSUE THREAD

**Issue by Ashish-create** [flutter/flutter#60463] opened 2020-06-28 09:32 UTC
Unable to run or create new project in Flutter  -- every time I create a new project or try to run the old project in fails with this error

Oops; flutter has exited unexpectedly: "NoSuchMethodError: Closure call with mismatched arguments: function 'MutablePackageTree.allPackages'
Receiver: Closure: (_SyncIterator<Package>) => bool
Tried calling: MutablePackageTree.allPackages()
Found: MutablePackageTree.allPackages(_SyncIterator<Package>) => bool".
A crash report has been written to C:\Users\Ashish\shopapp\flutter_12.log.

**Comment by JuYeong0413** [comment] 2020-06-28 21:06
Looks like this issue is duplicate of https://github.com/flutter/flutter/issues/59245

**Comment by iapicca** [comment] 2020-06-29 11:01
Hi @Ashish-create 
As @JuYeong0413 pointed out there's an open [issue](https://github.com/flutter/flutter/issues/59245) addressing the case you described.
Please follow up on that issue, I'm closing the current one as duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by iapicca** 2020-06-29 11:01 UTC
