### ISSUE TITLE
Flutter web: Wrong icon after build

### ISSUE THREAD

**Issue by kirill-21** [flutter/flutter#83703] opened 2021-06-01 10:25 UTC
Running site from Android Studio
![image](https://user-images.githubusercontent.com/63228361/120308157-75ce9a80-c2dc-11eb-9535-6c6d794d76b1.png)

Icon preview in the Android Studio
![image](https://user-images.githubusercontent.com/63228361/120308274-9a2a7700-c2dc-11eb-9665-cb6a8707aad0.png)

Result after deploying website onto hosting: 
![image](https://user-images.githubusercontent.com/63228361/120308334-aca4b080-c2dc-11eb-8cf9-57eb9e2c34cd.png)

Building with: flutter build web --web-renderer canvaskit on Flutter 2.2.1 stable

**Comment by kirill-21** [comment] 2021-06-01 10:30
Just noticed one more change:
![image](https://user-images.githubusercontent.com/63228361/120309063-74ea3880-c2dd-11eb-8b61-a1183b107d07.png)

![image](https://user-images.githubusercontent.com/63228361/120309047-70258480-c2dd-11eb-9e05-0b665f7e8c2e.png)

**Comment by guidezpl** [comment] 2021-06-01 10:57
Likely dupe of #83208 but I'd like to investigate further. 

Could you please attach the following files to a Github reply:
* `flutter/bin/cache/material_fonts.stamp`
* `flutter/bin/cache/artifacts/material_fonts/MaterialIcons-Regular.otf`

After that, please try `flutter pub cache repair` and let me know if it works

**Comment by kirill-21** [comment] 2021-06-01 11:16
material_fonts.stamp:
```
flutter_infra_release/flutter/fonts/bd151aa3c2f7231344411a01dba4ef61b3cd56b2/fonts.zip
```

MaterialIcons-Regular.otf
https://mega.nz/file/8rokgJQC#G2QYQYA5QjzqFkjz5vkYP-5E5_uBfDl0f5s7ExpRmK0

**Comment by guidezpl** [comment] 2021-06-01 11:32
Thanks, looks good from the flutter tool's caching side, both of those are up to date. This could be browser caching. What does the icon font look like in Chrome/Firefox DevTools?

<img width="714" alt="Screenshot 2021-06-01 at 13 31 34" src="https://user-images.githubusercontent.com/6655696/120316440-b975d400-c2dd-11eb-837c-d917605615b3.png">

**Comment by kirill-21** [comment] 2021-06-01 11:37
> Thanks, looks good from the flutter tool's caching side, both of those are up to date. This could be browser caching. What does the icon font look like in Chrome/Firefox DevTools?
> 
> <img alt="Screenshot 2021-06-01 at 13 31 34" width="714" src="https://user-images.githubusercontent.com/6655696/120316440-b975d400-c2dd-11eb-837c-d917605615b3.png">

I've tested it on Edge, Cent, Yandex and Chrome. All 4 browsers show the same, wrong, icon

**Comment by guidezpl** [comment] 2021-06-01 11:40
@yjbanov Curious if you have any ideas

**Comment by kirill-21** [comment] 2021-06-01 11:42
Before today i had my website build on flutter 2.0.6, but i've decided to update it and the issue appeared

**Comment by kirill-21** [comment] 2021-06-01 11:46
> Likely dupe of #83208 but I'd like to investigate further.
> 
> Could you please attach the following files to a Github reply:
> 
> * `flutter/bin/cache/material_fonts.stamp`
> * `flutter/bin/cache/artifacts/material_fonts/MaterialIcons-Regular.otf`
> 
> After that, please try `flutter pub cache repair` and let me know if it works

I've executed "flutter pub cache repair", rebuilt and redeployed my website on server and the issue did not disappear

**Comment by guidezpl** [comment] 2021-06-02 09:35
Are you able to run on a different device, so we can isolate whether this is a web-only issue?

**Comment by kirill-21** [comment] 2021-06-02 10:09
> Are you able to run on a different device, so we can isolate whether this is a web-only issue?

Desktop(Windows), release version, the icon is normal:
![image](https://user-images.githubusercontent.com/63228361/120462547-b7764880-c3a3-11eb-8366-abb4bb27a7a6.png)

**Comment by guidezpl** [comment] 2021-06-02 10:40
Do you mind sharing a link to the hosted version?

**Comment by kirill-21** [comment] 2021-06-02 10:43
> Do you mind sharing a link to the hosted version?

https://exloader.net/#/

**Comment by guidezpl** [comment] 2021-06-02 12:21
Looks good to me, so likely a cache or service worker issue. 
<img width="1028" alt="Screenshot 2021-06-02 at 14 16 55" src="https://user-images.githubusercontent.com/6655696/120478644-5e131700-c3ad-11eb-9857-b6e5cdbd5e0a.png">

I would dig in the Network tab of DevTools.

<img width="1221" alt="Screenshot 2021-06-02 at 14 21 02" src="https://user-images.githubusercontent.com/6655696/120479043-c82bbc00-c3ad-11eb-8e02-5938daada832.png">

**Comment by kirill-21** [comment] 2021-06-02 12:27
> Looks good to me, so likely a cache or service worker issue.
> <img alt="Screenshot 2021-06-02 at 14 16 55" width="1028" src="https://user-images.githubusercontent.com/6655696/120478644-5e131700-c3ad-11eb-9857-b6e5cdbd5e0a.png">
> 
> I would dig in the Network tab of DevTools.
> 
> <img alt="Screenshot 2021-06-02 at 14 21 02" width="1221" src="https://user-images.githubusercontent.com/6655696/120479043-c82bbc00-c3ad-11eb-8e02-5938daada832.png">

Strange, even my mobile phone shows this incorrect icon
![Screenshot_20210602-152233_Browser](https://user-images.githubusercontent.com/63228361/120479730-f5309c80-c3b6-11eb-827d-6e93b4df6f25.jpg)

**Comment by ThomasWaghubinger** [comment] 2021-06-02 14:56
I noticed exactly the same issue.

**Comment by guidezpl** [comment] 2021-06-03 07:15
Without further information regarding browser caching and being unable to reproduce the bug, there's not much more I can do

**Comment by kirill-21** [comment] 2021-06-03 09:18
> Without further information regarding browser caching and being unable to reproduce the bug, there's not much more I can do

I noticed that my other projects compiled on this (2.2.1) flutter version work fine, but there's a difference in html file. 
Project with issue has such body scripts:
![image](https://user-images.githubusercontent.com/63228361/120620458-aa219280-c465-11eb-98c1-16e55d16fef4.png)
Project without, has these: 
![image](https://user-images.githubusercontent.com/63228361/120620588-c8878e00-c465-11eb-9fd9-7398fa49bad7.png)

Do not know if it's helpful

**Comment by guidezpl** [comment] 2021-06-03 11:39
Oh interesting, this might cause the service worker never to update since it's using the same version. Can you try deleting index.html and running again? It'll regenerate it using an improved loading method from https://github.com/flutter/flutter/pull/75535

**Comment by kirill-21** [comment] 2021-06-03 12:24
> running again? It'll regenerate it us

The problem is i already tried to delete index html and create a new one via flutter create . , but it created the same file

**Comment by guidezpl** [comment] 2021-06-03 14:21
Can you provide your `flutter doctor -v` and `flutter run -v` when it recreates it?

**Comment by kirill-21** [comment] 2021-06-03 16:08
![image](https://user-images.githubusercontent.com/63228361/120676334-95adbc00-c49e-11eb-8fb4-6d0333f58cb4.png)
```
[+1038 ms] executing: [C:\Install\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +663 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] 02c026b03cd31dd3f867e5faeb7e104cce174c5f
[   +2 ms] executing: [C:\Install\flutter/] git tag --points-at 02c026b03cd31dd3f867e5faeb7e104cce174c5f
[+1706 ms] Exit code 0 from: git tag --points-at 02c026b03cd31dd3f867e5faeb7e104cce174c5f
[   +1 ms] 2.2.1
[  +11 ms] executing: [C:\Install\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[+1405 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[+2374 ms] origin/stable
[+1255 ms] executing: [C:\Install\flutter/] git ls-remote --get-url origin
[+1454 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[+1066 ms] executing: [C:\Install\flutter/] git rev-parse --abbrev-ref HEAD
[ +976 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[ +818 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +7 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[  +18 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[  +59 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[  +13 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +4 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +522 ms] executing: C:\Users\karnm\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[ +656 ms] List of devices attached
[  +93 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[  +11 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +5 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +4 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +8 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[+1649 ms] Multiple devices found:
[  +89 ms] Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19042.985]
[  +16 ms] Chrome (web)      • chrome  • web-javascript • Google Chrome 91.0.4472.77
[   +1 ms] Edge (web)        • edge    • web-javascript • Microsoft Edge 91.0.864.37
[   +3 ms] [1]: Windows (windows)
[        ] [2]: Chrome (chrome)
[        ] [3]: Edge (edge)
[   +5 ms] Please choose one (To quit, press "q/Q")
[   +1 ms] : 
[+9215 ms] 2
[  +38 ms] Skipping pub get: version match.
[ +727 ms] Found plugin url_launcher at C:\Install\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher-6.0.3\
[  +21 ms] Found plugin url_launcher_linux at C:\Install\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_linux-2.0.0\
[  +24 ms] Found plugin url_launcher_macos at C:\Install\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_macos-2.0.0\
[  +35 ms] Found plugin url_launcher_web at C:\Install\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_web-2.0.0\
[  +19 ms] Found plugin url_launcher_windows at C:\Install\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_windows-2.0.0\
[ +150 ms] Found plugin integration_test at C:\Install\flutter\packages\integration_test\
[ +232 ms] Found plugin url_launcher at C:\Install\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher-6.0.3\
[   +4 ms] Found plugin url_launcher_linux at C:\Install\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_linux-2.0.0\
[   +2 ms] Found plugin url_launcher_macos at C:\Install\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_macos-2.0.0\
[   +3 ms] Found plugin url_launcher_web at C:\Install\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_web-2.0.0\
[   +3 ms] Found plugin url_launcher_windows at C:\Install\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_windows-2.0.0\
[  +35 ms] Found plugin integration_test at C:\Install\flutter\packages\integration_test\
[  +74 ms] Generating C:\Users\karnm\StudioProjects\exl_website\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[ +415 ms] Launching lib\main.dart on Chrome in debug mode...
[ +335 ms] Updating assets
[ +686 ms] Manifest contained wildcard assets. Inserting missing file into build graph to force rerun. for more information see #56466.
[   +5 ms] Waiting for connection from debug service on Chrome...
[  +47 ms] Found plugin url_launcher at C:\Install\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher-6.0.3\
[   +3 ms] Found plugin url_launcher_linux at C:\Install\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_linux-2.0.0\
[   +1 ms] Found plugin url_launcher_macos at C:\Install\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_macos-2.0.0\
[   +3 ms] Found plugin url_launcher_web at C:\Install\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_web-2.0.0\
[   +2 ms] Found plugin url_launcher_windows at C:\Install\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_windows-2.0.0\
[  +20 ms] Found plugin integration_test at C:\Install\flutter\packages\integration_test\
[  +68 ms] Found plugin url_launcher at C:\Install\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher-6.0.3\
[   +2 ms] Found plugin url_launcher_linux at C:\Install\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_linux-2.0.0\
[   +1 ms] Found plugin url_launcher_macos at C:\Install\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_macos-2.0.0\
[   +2 ms] Found plugin url_launcher_web at C:\Install\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_web-2.0.0\
[   +3 ms] Found plugin url_launcher_windows at C:\Install\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_windows-2.0.0\
[  +14 ms] Found plugin integration_test at C:\Install\flutter\packages\integration_test\
[ +936 ms] <- reset
[  +11 ms] C:\Install\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev C:\Install\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root C:\Install\flutter\bin\cache\flutter_web_sdk/
--incremental --target=dartdevc --debugger-module-names --experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true --output-dill C:\Users\karnm\AppData\Local\Temp\flutter_tools.1894734c\flutter_tool.31776e8f\app.dill
--libraries-spec file:///C:/Install/flutter/bin/cache/flutter_web_sdk/libraries.json --packages C:\Users\karnm\StudioProjects\exl_website\.dart_tool\package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false
--enable-asserts --track-widget-creation --filesystem-root C:\Users\karnm\AppData\Local\Temp\flutter_tools.1894734c\flutter_tools.b0706db8 --filesystem-scheme org-dartlang-app --initialize-from-dill
build\c7922d95bf4a2462b75c84a97c312edb.cache.dill.track.dill --platform file:///C:/Install/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk.dill --no-sound-null-safety
[  +21 ms] <- compile org-dartlang-app:/web_entrypoint.dart
```

**Comment by yjbanov** [comment] 2021-06-03 21:56
This could be due to either browser caching or a but in our font fallback. The caching could be affected by the code in `index.html`.

`flutter create` recreating the old version of the file seems suspicious. Did you delete `web/index.html` or `build/web/index.html`? You want to delete and recreates the former, not the latter. Alternatively, you can delete all of the service worker code and just keep the `<script src="main.dart.js...">`. This will remove the service worker from the equation.

Can you please try it without the service worker? This will help us categorize the issue correctly. Thanks.

**Comment by kirill-21** [comment] 2021-06-03 22:28
>  Did you delete web/index.html or build/web/index.html?
i deleted both

**Comment by ThomasWaghubinger** [comment] 2021-06-04 06:38
I removed the service worker code inside the index.html file, now it works again!
![Bildschirmfoto 2021-06-04 um 08 35 45](https://user-images.githubusercontent.com/54668289/120756916-296ba080-c510-11eb-9d5c-19c6d3065019.png)

**Comment by dmvvilela** [comment] 2021-06-16 09:58
My icons are wrong too. Tested on android device in dev mode. i don't even use web.

**Comment by hillelcoren** [comment] 2021-08-24 21:06
You can see the problem in our app using this link:

https://demo.invoiceninja.com?build=last

We compile our app using the last, current and next versions of the Flutter SDK, it's useful to isolate problems between releases. Since the icons changed between the last (v2.0) and current (v2.2) releases when viewing the last version (which uses the current fonts) the problem is always present.

For comparison here are the other versions of the app:

https://demo.invoiceninja.com (current) 
https://demo.invoiceninja.com?build=next (v2.5)
https://demo.invoiceninja.com?build=wasm

**Comment by creativecreatorormaybenot** [comment] 2021-08-24 21:33
@hillelcoren That is big! (to have the reproducible version)  
I am wondering, is there a way for you to preserve this state, so that @yjbanov e.g. will be able to reproduce it at a later point?

**Comment by hillelcoren** [comment] 2021-08-25 05:09
The state should be preserved at least until the next version of Flutter is released.

**Comment by guidezpl** [comment] 2021-12-07 09:23
Given https://github.com/flutter/flutter/issues/82947 is fixed, I'm also closing this issue. If you've run into this and the workarounds above don't work, please create a new issue and @ me.

**Closed by guidezpl** 2021-12-07 09:23 UTC
Labels: severe: regression, engine, platform-web, a: build, passed first triage, e: web_canvaskit, P3
