### ISSUE TITLE
Fonts are rendered with inconsistent anti-aliasing

### ISSUE THREAD

**Issue by larsb24** [flutter/flutter#123345] opened 2023-03-23 18:12 UTC
Linux font rendering seems to have issues with anti-aliasing, making light text appear much thicker than dark text.

**Steps to Reproduce:**

1. Write a Widget that shows light text on dark and dark text on light background
2. Compare the texts and in particular their thickness

**Expected results:** 

The font should be rendered identically in both cases.

**Actual results:**

The light text is rendered thicker with visibly more opaque anti-aliasing than the dark text.

---

I created an app showing the same text on two sides. Both with light and dark background. I also added coloured texts as reference to show that even the coloured text on the dark background has less opaque anti-aliasing. I used the Cantarell variable font because I had previously compared it to the GTK libadwaita font rendering. The same behaviour can be reproduced with any font and even icons though. On GTK apps the light text on dark background looks a lot thinner and you can see the differences in the anti-aliasing as well.

To illustrate the issue, I made a screenshot showing the app (right) and a 5x magnification of it using xzoom (left).

![image](https://user-images.githubusercontent.com/61460660/227291977-1bd27944-4b85-4435-955d-88e2a8f54357.png)

Here are screenshots of the expected behaviour, based on the adwaita demo app.
Light text on dark background:

![image](https://user-images.githubusercontent.com/61460660/227295732-441c741f-d1a7-42e4-9223-eac93821db8d.png)

Dark text on light background:

![image](https://user-images.githubusercontent.com/61460660/227295939-1a93fcc2-c1c0-47d4-9434-62621e16a8ed.png)

---

Example Code:
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    final TextStyle textStyle = TextStyle(
      fontFamily: "Canterell",
      fontSize: 15,
    );
    return MaterialApp(
      home: Material(
        child: Row(
          children: [
            Expanded(
              child: Container(
                color: Colors.grey[900],
                child: Column(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: [
                    Text('Regular', style: textStyle.copyWith(color: Colors.white)),
                    Text('Regular', style: textStyle.copyWith(color: Colors.red)),
                    Text('Regular', style: textStyle.copyWith(color: Colors.blue)),
                    Text('Regular', style: textStyle.copyWith(color: Colors.green)),
                  ],
                ),
              ),
            ),
            Expanded(
              child: Container(
                color: Colors.white,
                child: Column(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: [
                    Text('Regular', style: textStyle.copyWith(color: Colors.black)),
                    Text('Regular', style: textStyle.copyWith(color: Colors.red)),
                    Text('Regular', style: textStyle.copyWith(color: Colors.blue)),
                    Text('Regular', style: textStyle.copyWith(color: Colors.green)),
                  ],
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}

```

**Comment by larsb24** [comment] 2023-03-24 09:44
Thanks for the recognition and the examples on different environments.

Interestingly the mentioned issue seems to have a similar problem, though it seems to be going the exact opposite direction. On native Linux the light text on dark background is thinner while it seems the issue on iOS is too thin dark text on light background compared to native apps.

Looking at your screenshot from the different environments I would say that the way fonts are rendered on macOS is most consistent.

Also certainly interesting to put into context that it seems to be consistent on iOS when using Impeller. However from what I can see it doesn't look like Impeller is coming to desktop any time soon.

**Comment by gspencergoog** [comment] 2023-03-30 18:10
I don't doubt that the issue exists, but the comparison you have where it is drawn in the same app on different backgrounds isn't a useful comparison, since the starting positions of the lettering is not the same (not at the same subpixel).

In any case, since this is very similar to https://github.com/flutter/flutter/issues/67034, we're going to mark this as a duplicate of that issue. (Desktop Triage)

**Closed by gspencergoog** 2023-03-30 18:10 UTC
Labels: engine, a: typography, a: desktop, has reproducible steps, found in release: 3.7, found in release: 3.9
