### ISSUE TITLE
[Web] search results in SelectableText where displayed at the wrong position.

### ISSUE THREAD

**Issue by Wissperwind** [flutter/flutter#77888] opened 2021-03-11 08:10 UTC
Hi,

I have an alert dialog that shows some logfile. The text is displayed with the selectable text widget.
I can select it perfectly. But if I press Strg + F to search and search for some words, chrome marks the words at the wrong positions where were not in the original Text. The marked words are at random positions like an overlay. Quite annoying.
![Unbenannt](https://user-images.githubusercontent.com/20759873/110755913-cbe5f180-8249-11eb-8594-a3e555b3300a.PNG)

**Comment by darshankawar** [comment] 2021-03-11 10:05
@Wissperwind 
Can you provide `flutter doctor -v` and a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that shows this issue ?

**Comment by Wissperwind** [comment] 2021-03-11 11:00
ok
```
[√] Flutter (Channel beta, 2.0.0, on Microsoft Windows [Version 10.0.19042.746], locale de-DE)
    • Flutter version 2.0.0 at C:\Users\akilian\Flutter SDK\flutter
    • Framework revision 60bd88df91 (8 days ago), 2021-03-03 09:13:17 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\akilian\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.52.1)
    • VS Code at C:\Users\akilian\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 88.0.4324.190
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 88.0.705.74

! Doctor found issues in 1 category.
```



code example:
```
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: "Test",
      home: TestPage(),
    );
  }
}

class TestPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text("Test")),
      body: Container(
        child: Center(
          child: RaisedButton(
            color: Colors.redAccent,
            textColor: Colors.white,
            onPressed: () {
              testAlert(context);
            },
            child: Text("PressMe"),
          ),
        ),
      ),
    );
  }

  void testAlert(BuildContext context) {
    var alert = AlertDialog(
      title: Text("Test"),
      content: SelectableText("Done.. lalala you can search me if you want! \n some other line,\n and some more lines\n bla\n bla\n bla\n bla\n bla\n bla\n bla\n and some more messages",
          style: GoogleFonts.sourceCodePro()),
    );

    showDialog(
        context: context,
        builder: (BuildContext context) {
          return alert;
        });
  }
}
```
For example open the alert, select some text and than press Strg + F and search for "more".

Overall it seems to be, that I am still "on the woodway" as we would say in Germany. I would like to display some searchable text. A log file to be more specific. But in the allert attempt, the user has to first select something in the text and that he can search the text with Strg + F and than he get's shearch results that are displayed with an offset. Not the greatest user experience until now. Do you have any recommendations?

**Comment by darshankawar** [comment] 2021-03-11 13:02
@Wissperwind 
It seems to be an issue with the `google_fonts` plugin you are using. I tried with core Flutter font style, with which the search results are highlighted properly, as below:

1. `style: TextStyle(fontStyle: FontStyle.normal)` or FontStyle.italic`:

<img width="1018" alt="Screenshot 2021-03-11 at 6 27 54 PM" src="https://user-images.githubusercontent.com/67046386/110791240-fc547c80-8297-11eb-90d5-80d658a312fc.png">

2. `style: GoogleFonts.sourceCodePro()`:

<img width="1010" alt="Screenshot 2021-03-11 at 6 28 23 PM" src="https://user-images.githubusercontent.com/67046386/110791282-0b3b2f00-8298-11eb-8699-2515225d027f.png">


I suggest you to open this issue in dedicated repo: https://github.com/material-foundation/google-fonts-flutter/issues

Closing from here.

**Closed by darshankawar** 2021-03-11 13:02 UTC
Labels: in triage

**Comment by Wissperwind** [comment] 2021-03-24 10:32
Unfortunately the issue in the dedicted repo is not noticed :(

**Comment by Wissperwind** [comment] 2021-03-24 13:29
This seems to be a problem of the dynamic loading of the fint files from the google servers.
I think the text structure, where the words are in the screen is defined with the standard font. After that the fint files were loaded and the new font is applied without changing the definiton of where the words are on the screen. This leads to wrong context menus and wrong search result markers. The problem is gone if you provide the ttf files in the assets.
