### ISSUE TITLE
[tool_crash] FileSystemException: Cannot copy file to '/var/folders/d0/7s3wzhjj2z56l7t_bh5vs3480000gn/T/flutter_tools.pFZTMg/subtract_icon.svg-transformOutput0.svg', OS Error: No such file or directory, errno = 2

### ISSUE THREAD

**Issue by rohith-alphanso** [flutter/flutter#152108] opened 2024-07-22 15:42 UTC
## Command
```
flutter run --machine --start-paused --dart-define IS_LOCAL_DEBUGGING=true -d emulator-5554 --devtools-server-address http://127.0.0.1:9100/ --target /Users/rohithchittibommala/Documents/GitHub/frontend/lib/main_dev.dart --flavor dev -t lib/main_dev.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Cannot copy file to '/var/folders/d0/7s3wzhjj2z56l7t_bh5vs3480000gn/T/flutter_tools.pFZTMg/subtract_icon.svg-transformOutput0.svg', OS Error: No such file or directory, errno = 2
```
#0      _checkForErrorResponse (dart:io/common.dart:55:9)
#1      _File.copy.<anonymous closure> (dart:io/file_impl.dart:356:7)
#2      _rootRunUnary (dart:async/zone.dart:1407:47)
<asynchronous suspension>
#3      ForwardingFile.copy (package:file/src/forwarding/forwarding_file.dart:29:51)
<asynchronous suspension>
#4      ForwardingFile.copy (package:file/src/forwarding/forwarding_file.dart:29:51)
<asynchronous suspension>
#5      AssetTransformer.transformAsset (package:flutter_tools/src/build_system/tools/asset_transformer.dart:58:5)
<asynchronous suspension>
#6      DevelopmentAssetTransformer.retransformAsset (package:flutter_tools/src/build_system/tools/asset_transformer.dart:188:51)
<asynchronous suspension>
#7      DevFS.update.<anonymous closure>.<anonymous closure> (package:flutter_tools/src/devfs.dart:686:26)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 3.22.2, on macOS 13.6.1 22G313 darwin-arm64, locale en-IN)
    • Flutter version 3.22.2 on channel stable at /Users/rohithchittibommala/Downloads/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 761747bfc5 (7 weeks ago), 2024-06-05 22:15:13 +0200
    • Engine revision edd8546116
    • Dart version 3.4.3
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/rohithchittibommala/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/rohithchittibommala/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.91.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.92.0

[✓] Connected device (4 available)
    • sdk gphone64 arm64 (mobile)     • emulator-5554         • android-arm64  • Android 14 (API 34) (emulator)
    • macOS (desktop)                 • macos                 • darwin-arm64   • macOS 13.6.1 22G313 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         • macOS 13.6.1 22G313 darwin-arm64
    • Chrome (web)                    • chrome                • web-javascript • Google Chrome 126.0.6478.183
    ! Error: Browsing on the local area network for Rohith’s iPhone. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 2.17.22+2017022
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: beta
**Creation framework version**: e599f02c7af4aa8aba0e8e96f71c737f85be3c6e
### Plugins
auth0_flutter
datadog_flutter_plugin-2.6.0
device_info_plus-10.1.0
facebook_app_events-0.19.2
firebase_analytics-11.1.0
firebase_analytics_web-0.5.8
firebase_auth-5.1.1
firebase_auth_web-5.12.3
firebase_core-3.1.1
firebase_core_web-2.17.2
firebase_messaging-15.0.2
firebase_messaging_web-3.8.10
firebase_performance-0.10.0+2
firebase_performance_web-0.1.6+10
flutter_branch_sdk-8.0.3
flutter_plugin_android_lifecycle-2.0.19
flutter_secure_storage-9.2.2
flutter_secure_storage_linux-1.2.1
flutter_secure_storage_macos-3.1.2
flutter_secure_storage_web-2.0.0-beta.1
flutter_secure_storage_windows-3.1.2
fluttertoast-8.2.5
google_sign_in-6.2.1
google_sign_in_android-6.1.25
google_sign_in_ios-5.7.6
google_sign_in_web-0.12.4+1
in_app_purchase-3.2.0
in_app_purchase_android-0.3.5+1
in_app_purchase_storekit-0.3.15
local_auth-2.2.0
local_auth_android-1.0.38
local_auth_darwin-1.3.0
local_auth_windows-1.0.10
package_info_plus-8.0.0
path_provider-2.1.3
path_provider_android-2.2.4
path_provider_foundation-2.4.0
path_provider_linux-2.2.1
path_provider_windows-2.2.1
patrol-3.7.3
plaid_flutter-4.0.5-rc
rive_common-0.2.8
shared_preferences-2.2.3
shared_preferences_android-2.2.2
shared_preferences_foundation-2.4.0
shared_preferences_linux-2.3.2
shared_preferences_web-2.3.0
shared_preferences_windows-2.3.2
url_launcher-6.3.0
url_launcher_android-6.3.1
url_launcher_ios-6.3.0
url_launcher_linux-3.1.1
url_launcher_macos-3.2.0
url_launcher_web-2.3.1
url_launcher_windows-3.1.1
webview_flutter-4.7.0
webview_flutter_android-3.16.1
webview_flutter_wkwebview-3.13.0

**Comment by danagbemava-nc** [comment] 2024-07-23 07:07
Closing this as a duplicate of https://github.com/flutter/flutter/issues/100082

**Closed by danagbemava-nc** 2024-07-23 07:07 UTC
Labels: in triage
