### ISSUE TITLE
[tool_crash] _TypeError: (#0      _ProgramInfoBuilder.createInfoNodeFor (package:vm_snapshot_analysis/v8_profile.dart:419:75))

### ISSUE THREAD

**Issue by Russiarain** [flutter/flutter#129407] opened 2023-06-23 04:04 UTC
## Command
```
flutter build apk --target-platform android-arm64 --analyze-size
```

## Steps to Reproduce
1. run the above command
2. apk is built but size analyzing failed and throwing the following exceptions

## Logs
_TypeError: (#0      _ProgramInfoBuilder.createInfoNodeFor (package:vm_snapshot_analysis/v8_profile.dart:419:75))
```
#0      _ProgramInfoBuilder.createInfoNodeFor (package:vm_snapshot_analysis/v8_profile.dart:419:75)
#1      _ProgramInfoBuilder.getInfoNodeFor (package:vm_snapshot_analysis/v8_profile.dart:374:14)
#2      ListIterable.forEach (dart:_internal/iterable.dart:39:13)
#3      _ProgramInfoBuilder.build (package:vm_snapshot_analysis/v8_profile.dart:338:16)
#4      toProgramInfo (package:vm_snapshot_analysis/v8_profile.dart:282:8)
#5      _treemapFromSnapshot (package:vm_snapshot_analysis/treemap.dart:158:27)
#6      treemapFromJson (package:vm_snapshot_analysis/treemap.dart:85:5)
#7      SizeAnalyzer.analyzeZipSizeAndAotSnapshot (package:flutter_tools/src/base/analyze_size.dart:123:59)
#8      AndroidGradleBuilder._performCodeSizeAnalysis (package:flutter_tools/src/android/gradle.dart:567:60)
#9      AndroidGradleBuilder.buildGradleApp (package:flutter_tools/src/android/gradle.dart:548:15)
<asynchronous suspension>
#10     AndroidGradleBuilder.buildApk (package:flutter_tools/src/android/gradle.dart:208:5)
<asynchronous suspension>
#11     BuildApkCommand.runCommand (package:flutter_tools/src/commands/build_apk.dart:116:5)
<asynchronous suspension>
#12     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1336:27)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#14     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#15     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:296:9)
<asynchronous suspension>
#16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
```
```
[32m[✓][39m Flutter (Channel stable, 3.10.5, on Microsoft Windows [Version 10.0.22621.1848], locale zh-CN)
    [32m•[39m Flutter version 3.10.5 on channel stable at C:\Android\flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision 796c8ef792 (9 days ago), 2023-06-13 15:51:02 -0700
    [32m•[39m Engine revision 45f6e00911
    [32m•[39m Dart version 3.0.5
    [32m•[39m DevTools version 2.23.1
    [32m•[39m Pub download mirror https://pub.flutter-io.cn
    [32m•[39m Flutter download mirror https://storage.flutter-io.cn

[32m[✓][39m Windows Version (Installed version of Windows is version 10 or higher)

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    [32m•[39m Android SDK at C:\Users\Frank\AppData\Local\Android\sdk
    [32m•[39m Platform android-33, build-tools 33.0.2
    [32m•[39m Java binary at: C:\Android\Android Studio\jbr\bin\java
    [32m•[39m Java version openjdk version "17.0.6" 2023-01-17
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[31m[✗][39m Visual Studio - develop for Windows
    [31m✗[39m Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[32m[✓][39m Android Studio (version 2022.2)
    [32m•[39m Android Studio at C:\Android\Android Studio
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version openjdk version "17.0.6" 2023-01-17

[32m[✓][39m VS Code (version 1.79.2)
    [32m•[39m VS Code at C:\Users\Frank\AppData\Local\Programs\Microsoft VS Code
    [32m•[39m Flutter extension version 3.66.0

[32m[✓][39m Connected device (4 available)
    [32m•[39m Redmi Note 7 Pro (mobile) • 192.168.1.3:39611 • android-arm64  • Android 13 (API 33)
    [32m•[39m Windows (desktop)         • windows           • windows-x64    • Microsoft Windows [Version 10.0.22621.1848]
    [32m•[39m Chrome (web)              • chrome            • web-javascript • Google Chrome 114.0.5735.134
    [32m•[39m Edge (web)                • edge              • web-javascript • Microsoft Edge 114.0.1823.43

[33m[!][39m Network resources
    [31m✗[39m An HTTP error occurred while checking "https://github.com/": 信号灯超时时间已到


[33m![39m Doctor found issues in 2 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 0.1.1+2
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 682aa387cfe4fbd71ccd5418b2c2a075729a1c66
### Plugins
connectivity_plus-4.0.1
device_info_plus-9.0.2
flutter_image_compress-2.0.3
flutter_image_compress_common-1.0.1
flutter_image_compress_web-0.1.3
isar_flutter_libs-3.1.0+1
path_provider-2.0.15
path_provider_android-2.0.27
path_provider_foundation-2.2.3
path_provider_linux-2.1.11
path_provider_windows-2.1.7

**Comment by huycozy** [comment] 2023-06-23 11:21
Hi @Russiarain 
There was a similar report recently and has been fixed on Dart side (see https://github.com/flutter/flutter/issues/128402). It's available on the latest master channel now, so please switch to master and retry.

```
flutter channel master
flutter upgrade
```

Closing this issue as a duplicate of https://github.com/flutter/flutter/issues/128402. If you still experience this on master channel, please write a comment there. Thanks!

**Closed by huycozy** 2023-06-23 11:21 UTC
Labels: in triage
