### ISSUE TITLE
[animations] OpenContainer has a white background by default

### ISSUE THREAD

**Issue by JCKodel** [flutter/flutter#58264] opened 2020-05-29 19:44 UTC
## Steps to Reproduce

1. Create an Android 10 emulator (or a device with Android 10)
2. Set Dark Theme
3. Create a project with OpenContainer (animations package)

OpenContainer have always white background (why the f*** OpenContainer is opaque???). It should inherit the same rule that Card does (or, better yet: make it transparent by default, it's a container!)

## Logs

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 1.18.0-11.1.pre, on Microsoft Windows [Version 10.0.19041.208], locale pt-BR)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.45.1)
[✓] Connected device (6 available)

• No issues found!
```

**Comment by TahaTesser** [comment] 2020-06-01 10:06
Hi @JCKodel 
Can you please provide  and a minimal complete reproducible code sample.
Thank you

**Comment by JCKodel** [comment] 2020-06-01 13:30
> Hi @JCKodel
> I noticed text is black in dark mode and makes it hard to read but i wasn't able to use date picker with open container
> Can you please provide and a minimal complete reproducible code sample.
> Thank you

It's not a combination. It's two examples of misused dark theme: the calendar and the background of OpenContainer (that is hardcoded white with rounded borders).

The OpenContainer should not have styles (as Container doesn't) or, if this won't change, at least comply with the dark theme (just like Card and Scaffold do).

**Comment by HansMuller** [comment] 2020-06-01 16:18
CC @darrenaustin @shihaohong @goderbauer

**Comment by goderbauer** [comment] 2020-06-01 16:43
The OpenContainer needs to have a style (background and border) because for some transitions the open container needs to animate those from one style to another. All of this can be overridden in the `OpenContainer` constructor to your liking.

However, we could think about defaulting them to the appropriate colors from theme. That sounds useful.

**Comment by shihaohong** [comment] 2020-06-01 17:02
I think it might be worth separating this one issue into two issues, since we want to make sure we track the problems for OpenContainer and DatePicker separately.

@JCKodel A gentle reminder to adhere to the [code of conduct](https://github.com/flutter/flutter/blob/master/CODE_OF_CONDUCT.md). Please avoid profanity when addressing problems.

**Comment by gnprice** [comment] 2021-01-31 02:36
This appears to be a duplicate of #53923.

**Comment by shihaohong** [comment] 2021-02-01 01:06
Closing this in favor of tracking https://github.com/flutter/flutter/issues/53923

**Closed by shihaohong** 2021-02-01 01:06 UTC
Labels: p: animations, p: first party, package
