### ISSUE TITLE
"Unable to find bundled Java version" — Flutter doesn't support JBR bundled with Android Studio (macOS)

### ISSUE THREAD

**Issue by Khazbs** [flutter/flutter#113775] opened 2022-10-20 17:22 UTC
# Issue

**"Unable to find bundled Java version"** when using Flutter with **Android Studio Flamingo Canary 5** freshly installed on macOS via JetBrains Toolbox.

_Possibly related to: #106674_.

# Details

It looks like Android Studio Flamingo comes with JetBrains Runtime (JBR) as a bundled Java version. On my machine it is located in `"/Users/pepsiman/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/222.4345.14.2221.9178080/Android Studio Preview.app/Contents/jbr/Contents/Home"`, and it seems that Flutter doesn't currently look for Java in `jbr/Contents/Home`.

# Code

The Flutter Tools code related to digging for a bundled Java version is supposedly around this line:
https://github.com/flutter/flutter/blob/2f03dda55ebafc4dfdd7196c84a46ee2228d5576/packages/flutter_tools/lib/src/android/android_studio.dart#L450

Adding `jbr/Contents/Home` to dig in might help.

# Diagnostics

Java Version says:

```shell
~ ❯ "/Users/pepsiman/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/222.4345.14.2221.9178080/Android Studio Preview.app/Contents/jbr/Contents/Home/bin/java" --version
openjdk 17.0.4.1 2022-08-12
OpenJDK Runtime Environment (build 17.0.4.1+0-17.0.4.1b469.62-9127311)
OpenJDK 64-Bit Server VM (build 17.0.4.1+0-17.0.4.1b469.62-9127311, mixed mode)
```

Flutter Doctor says:

```shell
~ ❯ flutter doctor -v
[✓] Flutter (Channel stable, 3.3.5, on macOS 12.6 21G115 darwin-x64, locale en-RU)
    • Flutter version 3.3.5 on channel stable at /Users/pepsiman/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d9111f6402 (21 hours ago), 2022-10-19 12:27:13 -0700
    • Engine revision 3ad69d7be3
    • Dart version 2.18.2
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc2)
    • Android SDK at /Users/pepsiman/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc2
    • Java binary at: /Users/pepsiman/Library/Java/JavaVirtualMachines/corretto-1.8.0_342/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment Corretto-8.342.07.3 (build 1.8.0_342-b07)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio
    • Android Studio at /Users/pepsiman/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/222.4345.14.2221.9178080/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] VS Code (version 1.72.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.6 21G115 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 106.0.5249.119

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

**Comment by huycozy** [comment] 2022-10-21 05:27
Hi @Khazbs 
Does this issue only happen when installing new Android Studio version via JetBrains Toolbox? I mean does it happen if you install it manually?

**Comment by Khazbs** [comment] 2022-10-21 10:25
# Response

Hi @huycozy,

Just tried with the non-Toolbox setup: downloaded Flamingo from [here](https://developer.android.com/studio/preview), unzipped the app and moved it to `/Applications`. The issue remains, as that version of Android Studio uses JBR as well, and Flutter Tools still don't seem to check the `jbr/Contents/Home` directory.

# Diagnostics

Java Version says:

```shell
~ ❯ "/Applications/Android Studio Preview.app/Contents/jbr/Contents/Home/bin/java" --version
openjdk 17.0.4.1 2022-08-12
OpenJDK Runtime Environment (build 17.0.4.1+0-17.0.4.1b469.62-9127311)
OpenJDK 64-Bit Server VM (build 17.0.4.1+0-17.0.4.1b469.62-9127311, mixed mode)
```

Flutter Doctor says:

```shell
~ ❯ flutter doctor -v
[✓] Flutter (Channel stable, 3.3.5, on macOS 12.6 21G115 darwin-x64, locale
    en-RU)
    • Flutter version 3.3.5 on channel stable at
      /Users/pepsiman/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d9111f6402 (2 days ago), 2022-10-19 12:27:13 -0700
    • Engine revision 3ad69d7be3
    • Dart version 2.18.2
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version
    33.0.0-rc2)
    • Android SDK at /Users/pepsiman/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc2
    • Java binary at:
      /Users/pepsiman/Library/Java/JavaVirtualMachines/corretto-1.8.0_342/Conten
      ts/Home/bin/java
    • Java version OpenJDK Runtime Environment Corretto-8.342.07.3 (build
      1.8.0_342-b07)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio
    • Android Studio at /Applications/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] VS Code (version 1.72.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.6 21G115 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 106.0.5249.119

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

**Comment by huycozy** [comment] 2022-10-21 12:14
@Khazbs Thanks for trying that. It seems the issue isn't caused by Toolbox. So I'm going to close this issue as a duplicate of #106674. And please take a look at https://github.com/flutter/flutter/issues/106674#issuecomment-1272244801 that reported for AS Flamingo (Canary 3).

Please follow up on it for further updates. You can leave there your comment and react an upvote to the original comment will help to raise the issue. Thank you for your contribution.

**Closed by huycozy** 2022-10-21 12:14 UTC
Labels: in triage
