### ISSUE TITLE
[web] Multiline Text is Cut Off in Chrome

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [flutter/flutter#70833] opened 2020-11-19 12:21 UTC
## Multiline text widget setup

This is how the widget that you see below looks in code:

```dart
Text(
  text,
  maxLines: 3,
  overflow: TextOverflow.ellipsis,
  textAlign: TextAlign.start,
),
```

## Steps to Reproduce

0. Use `beta 1.23.0-18.1.pre`.
1. Run `flutter build web`.
2. See result.

**Expected results:** this is how it looks **on Safari**:

<a href="https://imgbb.com/"><img src="https://i.ibb.co/LvGV6H9/Screen-Shot-2020-11-19-at-12-14-49-PM.png" alt="Screen-Shot-2020-11-19-at-12-14-49-PM" border="0"></a>

**Actual results:** this is how it looks **on Chrome**:

<a href="https://imgbb.com/"><img src="https://i.ibb.co/1mQ6t7H/Screen-Shot-2020-11-19-at-12-16-33-PM.png" alt="Screen-Shot-2020-11-19-at-12-16-33-PM" border="0"></a>

---

This is similar to #63467, however, **scaling** does not matter. This is reproducible on any zoom level.

**Comment by pedromassangocode** [comment] 2020-11-19 12:31
Hi @creativecreatorormaybenot 
Can you please provide your `flutter doctor -v` and a minimal complete reproducible code sample?
Thank you

**Comment by creativecreatorormaybenot** [comment] 2020-11-20 15:27
@pedromassango I am having a really hard time to reproduce this with a minimal example - it happens all the time for the cases, where it happens, however, these cases are obviously somewhere deep within the app and it might not occur when extracting that out to a single widget `runApp` example.

I posted the Flutter version in the original comment - however, I am still trying to reproduce this properly when extracting the text widgets.

It is pretty apparent that this is a common problem looking at the latest replies in #63467.

**Comment by pedromassangocode** [comment] 2020-11-23 08:07
Hi @creativecreatorormaybenot 
Does the issue reproduces only when you scale browser? If yes, then this maybe a duplicate of #63467.

**Comment by creativecreatorormaybenot** [comment] 2020-11-23 13:11
@pedromassango No, it appears at any scale, which is why I opened this one. It also only happens for multiline and the other one cuts of words / sentences.

**Comment by lyf571321556** [comment] 2021-02-26 04:32
same issue on latest beta version;

**Comment by mdebbar** [comment] 2021-03-17 00:14
Could you please try again on latest master or on the new stable version? There've been many fixes for text rendering and I believe this issue shouldn't be happening anymore (I know it existed before, but I can't reproduce it now).

**Comment by pedromassangocode** [comment] 2021-04-07 12:56
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2021-04-07 12:56 UTC
Labels: P4, a: typography, e: web_html, passed first triage, platform-web, severe: rendering, waiting for customer response
