### ISSUE TITLE
Can't display chinese

### ISSUE THREAD

**Issue by jet10000** [flutter/flutter#7459] opened 2017-01-12 09:24 UTC
I just replace "Cloud" to "目录" in bottom_navigation_demo.dart file, then build and run in my iphone6s, the chinese "目录" can't display. How fix it?

<img width="768" alt="qq20170112-0 2x" src="https://cloud.githubusercontent.com/assets/2258120/21883756/8bb192ba-d8eb-11e6-9653-87b347546d16.png">

![img_0176](https://cloud.githubusercontent.com/assets/2258120/21883869/efc7213e-d8eb-11e6-8140-bf30795feb30.PNG)

**Comment by addobandre** [comment] 2017-01-19 16:48
This seems to be a duplicate of #6939

**Comment by xster** [comment] 2017-02-07 21:44
Going to merge this into #6939

**Closed by xster** 2017-02-07 21:44 UTC
Labels: prod: engine, ⌺‬ platform-ios
