### ISSUE TITLE
Where did the build configuration for Harfbuzz move to in the engine?

### ISSUE THREAD

**Issue by mimbrown** [flutter/flutter#122435] opened 2023-03-10 22:35 UTC
I once had a use case in which I needed to alter the build configuration for Harfbuzz in the flutter engine. It used to be that flutter maintained a [fork of Harfbuzz](https://flutter.googlesource.com/third_party/harfbuzz/) with a `BUILD.gn` file that specified how Harfbuzz was integrated into the wider project. But when I recently went to repeat this process, I discovered that something internal had changed, and that the fork no longer included the `BUILD.gn` file. Can someone point me towards where the flags/configuration for Harfbuzz are set now in the current build process? You would save me a whole lot of digging.

**Comment by exaby73** [comment] 2023-03-13 07:28
Hello @mimbrown. This looks like a duplicate of https://github.com/flutter/flutter/issues/43513. You may follow up on that issue or you can ask on Discord. You can find the Discord [here](https://github.com/flutter/flutter/wiki/Chat). Thank you

**Closed by exaby73** 2023-03-13 07:28 UTC
Labels: in triage

**Comment by mimbrown** [comment] 2023-03-13 16:18
Thanks @exaby73, I’ve moved it to discord: https://discord.com/channels/608014603317936148/1084856206427959346
