### ISSUE TITLE
[tool_crash] OutOfMemoryError: (null)

### ISSUE THREAD

**Issue by MuhammedEmad5** [flutter/flutter#145661] opened 2024-03-24 16:56 UTC
## Command
```
flutter --no-color run --machine --track-widget-creation --device-id=emulator-5554 --start-paused --dart-define=flutter.inspector.structuredErrors=true lib\main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
OutOfMemoryError: (null)
```
#0      new Uint8List (dart:typed_data-patch/typed_data_patch.dart:2236:3)
#1      Uint8Buffer._createBuffer (package:typed_data/src/typed_buffer.dart:328:40)
#2      TypedDataBuffer._createBiggerBuffer (package:typed_data/src/typed_buffer.dart:259:12)
#3      TypedDataBuffer._ensureCapacity (package:typed_data/src/typed_buffer.dart:241:21)
#4      TypedDataBuffer._insertKnownLength (package:typed_data/src/typed_buffer.dart:209:5)
#5      TypedDataBuffer._addAll (package:typed_data/src/typed_buffer.dart:186:7)
#6      TypedDataBuffer.addAll (package:typed_data/src/typed_buffer.dart:91:5)
#7      HashSink.add (package:crypto/src/hash_sink.dart:79:18)
#8      _ByteAdapterSink.add (dart:convert/byte_conversion.dart:49:11)
#9      Hash.convert (package:crypto/src/hash.dart:28:15)
#10     _calculateSha (package:flutter_tools/src/android/gradle.dart:934:20)
#11     AndroidGradleBuilder.buildGradleApp (package:flutter_tools/src/android/gradle.dart:594:36)
#12     _rootRunUnary (dart:async/zone.dart:1407:47)
#13     _CustomZone.runUnary (dart:async/zone.dart:1308:19)
#14     _FutureListener.handleValue (dart:async/future_impl.dart:162:18)
#15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:838:45)
#16     Future._propagateToListeners (dart:async/future_impl.dart:867:13)
#17     Future._completeWithValue (dart:async/future_impl.dart:643:5)
#18     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:713:7)
#19     _rootRun (dart:async/zone.dart:1399:13)
#20     _CustomZone.run (dart:async/zone.dart:1301:19)
#21     _CustomZone.runGuarded (dart:async/zone.dart:1209:7)
#22     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1249:23)
#23     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#24     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
```
```
[✓] Flutter (Channel stable, 3.19.4, on Microsoft Windows [Version 10.0.19045.4170], locale en-US)
    • Flutter version 3.19.4 on channel stable at C:\scr\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 68bfaea224 (4 days ago), 2024-03-20 15:36:31 -0700
    • Engine revision a5c24f538d
    • Dart version 3.3.2
    • DevTools version 2.31.1

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:/Users/silverlight/AppData/Local/Android/Sdk
    • Platform android-34, build-tools 33.0.0
    • ANDROID_HOME = C:/Users/silverlight/AppData/Local/Android/Sdk
    • Java binary at: C:\Program Files\Android\Android Studio1\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0--11185874)

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.3.4)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.3.32901.215
    ✗ The current Visual Studio installation is incomplete.
      Please use Visual Studio Installer to complete the installation or reinstall Visual Studio.

[!] Android Studio (version 2022.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to determine bundled Java version.
    • Try updating or re-installing Android Studio.

[!] Android Studio (version 2023.2)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to determine bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] VS Code (version 1.87.2)
    • VS Code at C:\Users\silverlight\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.84.0

[✓] Connected device (4 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Windows (desktop)                  • windows       • windows-x64    • Microsoft Windows [Version 10.0.19045.4170]
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 123.0.6312.58
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 122.0.2365.92

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 4 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 68bfaea224880b488c617afe30ab12091ea8fa4e
### Plugins
cloud_firestore-4.15.9
cloud_firestore_web-3.10.9
file_selector_linux-0.9.2+1
file_selector_macos-0.9.3+3
file_selector_windows-0.9.3+1
firebase_auth-4.17.9
firebase_auth_web-5.10.0
firebase_core-2.27.1
firebase_core_web-2.12.0
firebase_storage-11.6.10
firebase_storage_web-3.8.0
flutter_plugin_android_lifecycle-2.0.17
image_picker-1.0.7
image_picker_android-0.8.9+3
image_picker_for_web-3.0.3
image_picker_ios-0.8.9+2
image_picker_linux-0.2.1+1
image_picker_macos-0.2.1+1
image_picker_windows-0.2.1+1
path_provider_linux-2.2.1
path_provider_windows-2.2.1
shared_preferences-2.2.2
shared_preferences_android-2.2.1
shared_preferences_foundation-2.3.5
shared_preferences_linux-2.3.2
shared_preferences_web-2.3.0
shared_preferences_windows-2.3.2

**Comment by huycozy** [comment] 2024-03-25 10:43
Closing this as a duplicate of https://github.com/flutter/flutter/issues/133371.

**Closed by huycozy** 2024-03-25 10:43 UTC
Labels: in triage
