### ISSUE TITLE
[image_picker] Taking picture with adjusted exposure closes bottom sheet on iOS

### ISSUE THREAD

**Issue by leonidlist** [flutter/flutter#158377] opened 2024-11-08 13:05 UTC
### Steps to reproduce

1. Open bottom sheet
2. Click on "Camera" to pick image with `ImageSource.camera`
3. Lower exposure (you can also make exposure higher to reproduce)
4. Take a picture
5. Bottom sheet where "Camera" button is located is closed (see attached video)

### Expected results

Bottom sheet where "Camera" button is located is not closed

### Actual results

Bottom sheet where "Camera" button is located is closed when exposure in camera was changed (see attached video)

### Code sample

You can also check repository with code sample
https://github.com/leonidlist/image_picker_bottom_sheet_bug

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key});

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final _picker = ImagePicker();

  Future<void> _pickImage() async {
    final pickedFile = await _picker.pickImage(source: ImageSource.camera);
    // ignore: avoid_print
    print(pickedFile?.path);
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: const Text('Image Picker Bug'),
      ),
      body: Center(
        child: FilledButton(
          onPressed: () {
            showModalBottomSheet(
              context: context,
              builder: (context) => Container(
                color: Colors.grey.shade300,
                height: MediaQuery.sizeOf(context).height * 0.5,
                width: double.infinity,
                child: Center(
                  child: FilledButton(
                    onPressed: () {
                      _pickImage();
                    },
                    child: const Text('Camera'),
                  ),
                ),
              ),
            );
          },
          child: const Text('Open bottom sheet'),
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/user-attachments/assets/7072aa75-e147-4fa9-9f19-b29e076099cc

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.24.3, on macOS 15.0 24A335 darwin-arm64, locale en-UA)
    • Flutter version 3.24.3 on channel stable at /Users/leonidlist/dev/sdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2663184aa7 (8 weeks ago), 2024-09-11 16:27:48 -0500
    • Engine revision 36335019a8
    • Dart version 3.5.3
    • DevTools version 2.37.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/leonidlist/dev/sdk/android
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16A242d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)

[✓] VS Code (version 1.92.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.94.0

[✓] VS Code (version 1.80.0-insider)
    • VS Code at /Applications/Visual Studio Code - Insiders.app/Contents
    • Flutter extension version 3.66.0

[✓] Connected device (5 available)            
    • iPhone 16 Pro Max (mobile)      • 29640D73-0335-4644-9A83-959ABDB0C8EF • ios            • com.apple.CoreSimulator.SimRuntime.iOS-18-0 (simulator)
    • macOS (desktop)                 • macos                                • darwin-arm64   • macOS 15.0 24A335 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad                • darwin         • macOS 15.0 24A335 darwin-arm64
    • Chrome (web)                    • chrome                               • web-javascript • Google Chrome 130.0.6723.117

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by huycozy** [comment] 2024-11-11 06:04
Reproduced this on Flutter stable `3.24.4` and master `3.27.0-1.0.pre.442` using the latest package version `image_picker_ios: 0.8.12+1`. The issue doesn't occur on Android app.

**Comment by huycozy** [comment] 2024-11-11 06:05
Reproduced this on Flutter stable `3.24.4` using the latest package version `image_picker_ios: 0.8.12+1`. The issue doesn't occur on Android app.

**Comment by stuartmorgan** [comment] 2024-11-12 20:41
This is a duplicate of https://github.com/flutter/flutter/issues/14720. The exposure control taps are above the sheet, which will cause the sheet to close.

**Closed by stuartmorgan** 2024-11-12 20:41 UTC
Labels: platform-ios, p: image_picker, package, has reproducible steps, fyi-ecosystem, team-ios, found in release: 3.24
