### ISSUE TITLE
Display in debug mode is normal, but ui is not displayed in release or profile mode , both in Android and IOS.

### ISSUE THREAD

**Issue by ditclear** [flutter/flutter#32541] opened 2019-05-11 05:59 UTC
I published it in Github:<https://github.com/flutter-ui-challenges/flutter_challenge_googlemaps>

Ui display is not normal when it is inside the Stack widget.

**Comment by kangwang1988** [comment] 2019-05-12 12:19
Please provide more details including the screenshot(debug&release, normal and abnormal).
Besides, 'flutter doctor -v' please.

**Comment by ditclear** [comment] 2019-05-12 12:34
debug mode (normal):

![](https://upload-images.jianshu.io/upload_images/3722695-47573773e0dc257b.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/320)


release mode (white screen):

![](https://upload-images.jianshu.io/upload_images/3722695-f995baa0b1f1970f.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/320)

flutter doctor -v :
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.2 18C54, locale zh-Hans-CN)
    • Flutter version 1.5.4-hotfix.2 at /Users/ditclear/Desktop/flutter
    • Framework revision 7a4c33425d (13 days ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

**Comment by kangwang1988** [comment] 2019-05-26 10:45
I reproduced this issue using the latest master and believe it's a matter of timing.
It happens because that 
```dart
    screenWidth = MediaQuery.of(context).size.width;
    screenHeight = MediaQuery.of(context).size.height;
```
This code snippets works differently on debug/release because of a matter of timing. In other words, it would be zero in release in your case. A more robust way to use it would be WidgetsBindingObserver.
I've confirmed that codes below can resolve this issue:
```dart
class MyWidgetsBindingObserver extends WidgetsBindingObserver{
  VoidCallback callback;
  MyWidgetsBindingObserver(VoidCallback callback){
    this.callback = callback;
  }
  @override
  void didChangeMetrics(){
    if(callback!=null) {
      callback();
    }
  }
}

class _GoogleMapState extends State<GoogleMapPage> with TickerProviderStateMixin {
  AnimationController animationControllerExplore;
  AnimationController animationControllerSearch;
  AnimationController animationControllerMenu;
  CurvedAnimation curve;
  Animation<double> animation;
  Animation<double> animationW;
  Animation<double> animationR;
  _GoogleMapState(){
    WidgetsBinding.instance.addObserver(MyWidgetsBindingObserver((){
      setState(() {

      });
    }));
  }
```
My flutter doctor -v result:
```dart
KyleWongs-MacBook-Pro:flutter_challenge_googlemaps kylewong$ flutter doctor -v
[✓] Flutter (Channel master, v1.6.4-pre.16, on Mac OS X 10.14.4 18E226, locale en-CN)
    • Flutter version 1.6.4-pre.16 at /Users/kylewong/Codes/flutter
    • Framework revision 75d75bfaec (8 hours ago), 2019-05-25 19:47:17 -0700
    • Engine revision 8dc3a4cde2
    • Dart version 2.3.2 (build 2.3.2-dev.0.0 e3edfd36b2)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/kylewong/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • CocoaPods version 1.6.1
```
@ditclear 
I'm closing this issue now.
If you're still seeing issue, comment below and I'll reopen it if needed.

**Closed by kangwang1988** 2019-05-26 10:45 UTC

**Comment by ditclear** [comment] 2019-05-26 14:36
Thanks , you reminded me.The problem is indeed here。
I modified the code in the `home_page.dart` file , line 127-128。
```dart
screenWidth ??= MediaQuery.of(context).size.width;
    screenHeight ??= MediaQuery.of(context).size.height;
```
to 
```dart
    screenWidth = MediaQuery.of(context).size.width;
    screenHeight = MediaQuery.of(context).size.height;
```
now it works。
