### ISSUE TITLE
Cocoon/build status is not updating

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#69818] opened 2020-11-04 21:36 UTC
Though newer commits have been submitted, they are not being surfaced on the dashboard. Its unclear if devicelab is running these either.

**Comment by godofredoc** [comment] 2020-11-04 21:41
The scheduler uses chromium replicas from the github repos which update every 15 mins. Are commits from more than 15 mins ago not showing up in the dashboard?

**Comment by jonahwilliams** [comment] 2020-11-04 21:42
https://github.com/flutter/flutter/commit/7ceb20417c93553f4cbd7a5a42bb2878968f6775 was submitted over an hour ago

**Comment by godofredoc** [comment] 2020-11-04 21:45
That one is already in the replica, https://chromium.googlesource.com/external/github.com/flutter/flutter/+/refs/heads/master

Looking at the cocoon backend

**Comment by godofredoc** [comment] 2020-11-04 21:49
```
FormatException: Unexpected character (at line 139, character 7)
      },
      ^

#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1404:5)
#1      _ChunkedJsonParser.parse (dart:convert-patch/convert_patch.dart:928:13)
#2      _parseJson (dart:convert-patch/convert_patch.dart:40:10)
#3      JsonDecoder.convert (dart:convert/json.dart:505:36)
#4      JsonCodec.decode (dart:convert/json.dart:156:41)
#5      getLuciBuilders (package:cocoon_service/src/foundation/utils.dart:112:21)
<asynchronous suspension>
#6      Config.luciBuilders (package:cocoon_service/src/datastore/cocoon_config.dart:80:18)
<asynchronous suspension>
#7      LuciBuilder.getProdBuilders (package:cocoon_service/src/service/luci.dart:225:25)
#8      RefreshGithubCommits._createTasks (package:cocoon_service/src/request_handlers/refresh_github_commits.dart:210:62)
#9      RefreshGithubCommits._saveData (package:cocoon_service/src/request_handlers/refresh_github_commits.dart:120:38)
<asynchronous suspension>
#10     RefreshGithubCommits.get (package:cocoon_service/src/request_handlers/refresh_github_commits.dart:87:13)
<asynchronous suspension>
#11     RequestHandler.service.<anonymous closure> (package:cocoon_service/src/request_handling/request_handler.dart:46:28)
<asynchronous suspension>
#12     RequestHandler.service.<anonymous closure> (package:cocoon_service/src/request_handling/request_handler.dart)
#13     _rootRun (dart:async/zone.dart:1190:13)
#14     _CustomZone.run (dart:async/zone.dart:1093:19)
#15     _runZoned (dart:async/zone.dart:1630:10)
#16     runZoned (dart:async/zone.dart:1550:10)
#17     RequestHandler.service (package:cocoon_service/src/request_handling/request_handler.dart:39:12)
#18     ApiRequestHandler.service.<anonymous closure> (package:cocoon_service/src/request_handling/api_request_handler.dart:144:19)
<asynchronous suspension>
#19     ApiRequestHandler.service.<anonymous closure> (package:cocoon_service/src/request_handling/api_request_handler.dart)
#20     _rootRun (dart:async/zone.dart:1190:13)
#21     _CustomZone.run (dart:async/zone.dart:1093:19)
#22     _runZoned (dart:async/zone.dart:1630:10)
#23     runZoned (dart:async/zone.dart:1550:10)
#24     ApiRequestHandler.service (package:cocoon_service/src/request_handling/api_request_handler.dart:143:11)
<asynchronous suspension>
#25     main.<anonymous closure>.<anonymous closure> (file:///app/bin/server.dart:134:23)
<asynchronous suspension>
#26     main.<anonymous closure>.<anonymous closure> (file:///app/bin/server.dart)
#27     runAppEngine.<anonymous closure> (package:appengine/appengine.dart:80:12)
#28     runAppEngine.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:appengine/src/appengine_internal.dart:59:18)
#29     _ServiceScope._fork.<anonymous closure> (package:gcloud/service_scope.dart:209:19)
#30     _rootRun (dart:async/zone.dart:1190:13)
#31     _CustomZone.run (dart:async/zone.dart:1093:19)
#32     _runZoned (dart:async/zone.dart:1630:10)
#33     runZonedGuarded (dart:async/zone.dart:1618:12)
#34     runZoned (dart:async/zone.dart:1547:12)
#35     _ServiceScope._fork (package:gcloud/service_scope.dart:208:12)
#36     fork (package:gcloud/service_scope.dart:104:30)
#37     runAppEngine.<anonymous closure>.<anonymous closure> (package:appengine/src/appengine_internal.dart:57:9)
#38     AppEngineHttpServer.run.<anonymous closure>.<anonymous closure> (package:appengine/src/server/server.dart:83:16)
#39     _rootRunUnary (dart:async/zone.dart:1198:47)
#40     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#41     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
#42     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#43     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#44     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:808:19)
#45     _StreamController._add (dart:async/stream_controller.dart:682:7)
#46     _StreamController.add (dart:async/stream_controller.dart:624:5)
#47     _HttpServer._handleRequest (dart:_http/http_impl.dart:2977:19)
#48     new _HttpConnection.<anonymous closure> (dart:_http/http_impl.dart:2732:19)
#49     _rootRunUnary (dart:async/zone.dart:1198:47)
#50     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#51     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
#52     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#53     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#54     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:808:19)
#55     _StreamController._add (dart:async/stream_controller.dart:682:7)
#56     _StreamController.add (dart:async/stream_controller.dart:624:5)
#57     _HttpParser._headersEnd (dart:_http/http_parser.dart:394:19)
#58     _HttpParser._doParse (dart:_http/http_parser.dart:740:15)
#59     _HttpParser._parse (dart:_http/http_parser.dart:324:7)
#60     _rootRunUnary (dart:async/zone.dart:1198:47)
#61     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#62     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
#63     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#64     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#65     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:808:19)
#66     _StreamController._add (dart:async/stream_controller.dart:682:7)
#67     _StreamController.add (dart:async/stream_controller.dart:624:5)
#68     _Socket._onData (dart:io-patch/socket_patch.dart:2044:41)
#69     _rootRunUnary (dart:async/zone.dart:1206:13)
#70     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#71     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
#72     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#73     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#74     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:808:19)
#75     _StreamController._add (dart:async/stream_controller.dart:682:7)
#76     _StreamController.add (dart:async/stream_controller.dart:624:5)
#77     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1580:33)
#78     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1076:14)
#79     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#80     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#81     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#82     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

**Comment by godofredoc** [comment] 2020-11-04 21:49
\cc @CaseyHillers

**Comment by godofredoc** [comment] 2020-11-04 22:19
Fix is under review but we need to check why the presubmit tests didn't find the problem before submitting the changes.

**Comment by godofredoc** [comment] 2020-11-04 22:24
@keyonghan can you please take a look why the json validation tests didn't fail for this PR https://github.com/flutter/flutter/pull/69350/checks?

**Comment by keyonghan** [comment] 2020-11-04 23:03
The error was caught by following PRs after the change PR got submitted.
The cause is that the json validation is based on tot, rather than the json in the PR.

**Comment by godofredoc** [comment] 2020-11-04 23:08
Do we have a bug to validate the json from the PRs? should we increase the priority of that bug if exist?

**Comment by keyonghan** [comment] 2020-11-04 23:18
Actually we are validating the json from the PR, rather than tot.
json validation is based on the checkout of PR: https://github.com/flutter/flutter/pull/69803

The issue PR is not https://github.com/flutter/flutter/pull/69350, but https://github.com/flutter/flutter/pull/69803. However tests didn't get finished running before submitted.

So there is nothing left over related to this issue, closing.

**Closed by keyonghan** 2020-11-04 23:18 UTC
Labels: P1, team: infra
