### ISSUE TITLE
[tool_crash] FileSystemException: Deletion failed, OS Error: The process cannot access the file because it is being used by another process., errno = 32

### ISSUE THREAD

**Issue by dewaara** [flutter/flutter#78859] opened 2021-03-23 12:16 UTC
## Command
```
flutter run
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Deletion failed, OS Error: The process cannot access the file because it is being used by another process.
, errno = 32
```
#0      _Directory._deleteSync (dart:io/directory_impl.dart:201:7)
#1      FileSystemEntity.deleteSync (dart:io/file_system_entity.dart:408:7)
#2      ForwardingFileSystemEntity.deleteSync (package:file/src/forwarding/forwarding_file_system_entity.dart:70:16)
#3      ErrorHandlingDirectory.deleteSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:459:22)
#4      _runSync (package:flutter_tools/src/base/error_handling_io.dart:556:14)
#5      ErrorHandlingDirectory.deleteSync (package:flutter_tools/src/base/error_handling_io.dart:458:12)
#6      FlutterWebSdk.updateInner (package:flutter_tools/src/cache.dart:838:16)
#7      CachedArtifact.update (package:flutter_tools/src/cache.dart:692:11)
#8      Cache.updateAll (package:flutter_tools/src/cache.dart:562:24)
<asynchronous suspension>
#9      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1110:7)
<asynchronous suspension>
#10     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1009:27)
<asynchronous suspension>
#11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#12     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
<asynchronous suspension>
#13     CommandRunner.runCommand (package:args/command_runner.dart:197:13)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:278:9)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#16     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
```
```
[✓] Flutter (Channel stable, 2.0.3, on Microsoft Windows [Version
    10.0.18363.1016], locale en-GB)
    • Flutter version 2.0.3 at E:\AndroidStudio\FlutterSdk\flutter
    • Framework revision 4d7946a68d (5 days ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Md Halim\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: E:\AndroidStudio\New folder\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    ✗ Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 4.1.0)
    • Android Studio at E:\AndroidStudio\New folder
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 89.0.4389.90
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 89.0.774.57

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: c5a4b4029c0798f37c4a39b479d7cb75daa7b05c

**Comment by darshankawar** [comment] 2021-03-23 13:14
Closing this as duplicate of https://github.com/flutter/flutter/issues/78158

Please try below commands and see if it works for you.
```

flutter channel master
flutter upgrade
```

**Closed by darshankawar** 2021-03-23 13:14 UTC
Labels: in triage
