### ISSUE TITLE
Backbutton in Appbar with no stack

### ISSUE THREAD

**Issue by renefloor** [flutter/flutter#8080] opened 2017-02-12 11:15 UTC
## Steps to Reproduce

Make an app with two routes: e.g.:
```dart
        routes: <String, WidgetBuilder>{
          '/':         (BuildContext context) => new MyHomePage(),
          '/welcome': (BuildContext context) => new WelcomePage()
        },
```
Do a pop and push from the first screen: `Navigator.popAndPushNamed(context, "/welcome");`

The second screen will have a back button in the app bar, pressing on that will crash the app.

## Logs

```
NoSuchMethodError: The getter 'overlay' was called on null.
Receiver: null
Tried calling: overlay
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:44)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      ModalRoute.didPopNext (package:flutter/src/widgets/routes.dart:604:52)
#3      NavigatorState.pop.<anonymous closure> (package:flutter/src/widgets/navigator.dart:1009:25)
#4      State.setState (package:flutter/src/widgets/framework.dart:915:24)
#5      NavigatorState.pop (package:flutter/src/widgets/navigator.dart:999:9)
#6      NavigatorState.maybePop.<maybePop_async_body> (package:flutter/src/widgets/navigator.dart:970:7)
#7      _RootZone.runUnary (dart:async/zone.dart:1404)
#8      _FutureListener.handleValue (dart:async/future_impl.dart:131)
#9      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:637)
#10     _Future._propagateToListeners (dart:async/future_impl.dart:667)
#11     _Future._complete (dart:async/future_impl.dart:467)
#12     _SyncCompleter.complete (dart:async/future_impl.dart:52)
#13     ModalRoute.willPop.<willPop_async_body> (package:flutter/src/widgets/routes.dart:680:5)
#14     Future.Future.microtask.<anonymous closure> (dart:async/future.dart:184)
#15     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#16     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
```

## Flutter Doctor
```
[✓] Flutter (on Mac OS, channel master)
    • Flutter at /Users/rene/flutter
    • Framework revision cff7dc5444 (34 hours ago), 2017-02-10 16:54:51
    • Engine revision f306a6f701
    • Tools Dart version 1.22.0-dev.10.6

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.2)
    • Android SDK at /Users/rene/Library/Android/sdk
    • Platform android-25, build-tools 25.0.2
    • Java(TM) SE Runtime Environment (build 1.8.0_112-b16)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.2.1, Build version 8C1002
    • ios-deploy 1.9.0

[✓] IntelliJ IDEA Ultimate Edition (version 2016.3.4)
    • Dart plugin version 163.13137
    • Flutter plugin version 0.1.9.1

[✓] Connected devices
    • iPhone 7 • 27117218-088B-4305-B874-45D41FED064F • ios • iOS 10.2 (simulator)
```

**Comment by Hixie** [comment] 2017-02-12 20:09
I'm surprised the popAndPush doesn't assert itself.

**Comment by eseidelGoogle** [comment] 2017-02-23 16:57
@abarth fixed some back button regressions yesterday, may have also fixed this.

**Comment by eseidelGoogle** [comment] 2017-02-23 17:03
I've attempted to repro with this example:

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(
    new MaterialApp(
      title: 'Test',
      home: new Home(),
      routes: {
        '/': (BuildContext _) => new Home(),
        '/other': (BuildContext _) => new OtherPage(),
      },
    ),
  );
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: new AppBar(
        title: new Text('Home'),
      ),
      body: new Card(
        child: new RaisedButton(
            child: new Text('Press Me'),
            onPressed: () {
              Navigator.popAndPushNamed(context, '/other');
            }),
      ),
    );
  }
}

class OtherPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: new AppBar(
        title: new Text('Other'),
      ),
      body: new Text('Other'),
    );
  }
}

```

Here is what I see when I click the button:
```
I/flutter (24152): ══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
I/flutter (24152): The following assertion was thrown while handling a gesture:
I/flutter (24152): 'package:flutter/src/widgets/navigator.dart': Failed assertion: line 762 pos 14:
I/flutter (24152): 'config.onUnknownRoute != null': is not true.
I/flutter (24152): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (24152): more information in this error message to help you determine and fix the underlying cause.
I/flutter (24152): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (24152):   https://github.com/flutter/flutter/issues/new
I/flutter (24152): When the exception was thrown, this was the stack:
I/flutter (24152): #2      NavigatorState._routeNamed (package:flutter/src/widgets/navigator.dart:762:14)
I/flutter (24152): #3      NavigatorState.pushNamed (package:flutter/src/widgets/navigator.dart:783:17)
I/flutter (24152): #4      Navigator.popAndPushNamed (package:flutter/src/widgets/navigator.dart:631:22)
I/flutter (24152): #5      Home.build.<anonymous closure> (/data/user/0/com.yourcompany.foo/cache/foolvbfcp/foo/lib/main.dart:27:25)
I/flutter (24152): #6      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:170:14)
I/flutter (24152): #7      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:65:24)
I/flutter (24152): #8      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:148:9)
I/flutter (24152): #9      TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:94:7)
I/flutter (24152): #10     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:260:9)
I/flutter (24152): #11     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:73:12)
I/flutter (24152): #12     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:11)
I/flutter (24152): #13     BindingBase&SchedulerBinding&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:122:19)
I/flutter (24152): #14     BindingBase&SchedulerBinding&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:100:22)
I/flutter (24152): #15     BindingBase&SchedulerBinding&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:81:7)
I/flutter (24152): #16     BindingBase&SchedulerBinding&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:40:7)
I/flutter (24152): #17     BindingBase&SchedulerBinding&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:33:5)
I/flutter (24152): #18     _dispatchPointerDataPacket (file:///b/build/slave/Linux_Engine/build/src/flutter/lib/ui/hooks.dart:73)
I/flutter (24152): (elided 2 frames from class _AssertionError)
I/flutter (24152): Handler: onTap
I/flutter (24152): Recognizer:
I/flutter (24152):   Instance of 'TapGestureRecognizer'
I/flutter (24152): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

This looks like it's working correctly?  I'm using:
```
eseidel@eseidel-macbookpro /tmp/foo %flutter --version                                                                                                        [/tmp/foo]
Flutter • channel master • git@github.com:flutter/flutter.git
Framework • revision 093afe0255 (14 hours ago) • 2017-02-22 19:11:44
Engine • revision ab09530927
Tools • Dart 1.23.0-dev.0.0
```

**Comment by eseidelGoogle** [comment] 2017-02-23 17:17
Ok, here is a better repro which does reproduce the original issue:

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(
    new MaterialApp(
      title: 'Test',
      home: new Home(),
      routes: {
        '/other': (BuildContext _) => new OtherPage(),
      },
    ),
  );
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      key: new ValueKey<String>('/'),
      appBar: new AppBar(
        title: new Text('Home'),
      ),
      body: new ButtonBar(children: [
        new RaisedButton(
          child: new Text('pushNamed'),
          onPressed: () {
            Navigator.pushNamed(context, '/other');
          },
        ),
        new RaisedButton(
          child: new Text('popAndPushNamed'),
          onPressed: () {
            Navigator.popAndPushNamed(context, '/other');
          },
        ),
      ]),
    );
  }
}

class OtherPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      key: new ValueKey<String>('/other'),
      appBar: new AppBar(
        title: new Text('Other Page'),
      ),
    );
  }
}
```

**Comment by Hixie** [comment] 2017-11-29 00:41
Moving this out to beyond m3 since it doesn't currently fit our priorities, but it is something we will fix in due course. Please let us know if this is a priority for you and you can't work around it.

**Comment by zoechi** [comment] 2019-01-15 16:35
I don't get any error with Erics example from https://github.com/flutter/flutter/issues/8080#issuecomment-282058332 when clicking on `popAndPushNamed`

```
[✓] Flutter (Channel dev, v1.1.9, on Mac OS X 10.14.1 18B75, locale en-AT)
```

**Comment by goderbauer** [comment] 2019-01-16 23:02
Tentatively closing this based on the comment above. Please feel free to re-open with additional information if the issue is still present.

**Closed by goderbauer** 2019-01-16 23:02 UTC
Labels: f: routes, framework, severe: crash, severe: regression

**Comment by mleonhard** [comment] 2019-04-13 05:49
My app also gets a back button when there is only one page on the stack.  This happens if that page is not '/'.  How can I remove the back button from my app's login screen?

Code that demonstrates the problem, with screenshot:
```
import 'package:flutter/cupertino.dart'
    show CupertinoApp, CupertinoNavigationBar, CupertinoPageScaffold;
import 'package:flutter/widgets.dart' show Center, Text, runApp;

void main() {
  runApp(
    CupertinoApp(
      routes: {
        '/': (context) =>
            CupertinoPageScaffold(child: Center(child: Text('/'))),
        '/login': (context) => CupertinoPageScaffold(
              navigationBar: CupertinoNavigationBar(
                middle: Text('/login'),
              ),
              child: Center(child: Text('/login')),
            ),
      },
      initialRoute: '/login',
    ),
  );
}
```
![Screen Shot 2019-04-12 at 10 32 16 PM](https://user-images.githubusercontent.com/520739/56075181-3139bb00-5d73-11e9-9bc0-1273690d681f.png)

The workaround is to:
1. Hide the back button by passing an invisible widget as the nav bar's `leading` widget. ([source](https://stackoverflow.com/a/45918186))
1. Prevent navigating back by using `WillPopScope`. ([source](https://www.didierboelens.com/2018/04/hint-1-hide-back-arrow-and-use-close-button/))  This is important because there are many other ways to navigate back: swiping on iOS, tapping the back button on Android, pressing certain buttons on a keyboard, and invoking accessibility methods.

Workaround code and screenshot:
```
import 'package:flutter/cupertino.dart'
    show CupertinoApp, CupertinoNavigationBar, CupertinoPageScaffold;
import 'package:flutter/widgets.dart'
    show Center, Container, Text, WillPopScope, runApp;

void main() {
  runApp(
    CupertinoApp(
      routes: {
        '/': (context) =>
            CupertinoPageScaffold(child: Center(child: Text('/'))),
        '/login': (context) => WillPopScope(
              onWillPop: () async => false,
              child: CupertinoPageScaffold(
                navigationBar: CupertinoNavigationBar(
                  leading: Container(),
                  middle: Text('/login'),
                ),
                child: Center(child: Text('/login')),
              ),
            ),
      },
      initialRoute: '/login',
    ),
  );
}
```
![Screen Shot 2019-04-12 at 10 37 59 PM](https://user-images.githubusercontent.com/520739/56075295-fb95d180-5d74-11e9-9209-23e5c6bf6e64.png)

How about fixing this in Flutter?  That would save other engineers hours of time dealing with this problem.

**Comment by mkhoudary** [comment] 2020-01-13 13:14
As it seems, this happens when there's a '/' route, when I removed this route the back button disappeared without a problem.. otherwise you should implement it by hiding leading button and overriding onWillPop..

**Comment by josephessin** [comment] 2020-03-18 16:53
@mkhoudary In light of what you said, I returned `null` from my `onGenerateRoute`'s default case and that seemed to fix the erroneous back button for me as well.

```
Route<dynamic> onGenerateRoute(RouteSettings settings) {
    switch (settings.name) {
      case '/home':
        return someRoute;
      case '/login':
        return anotherRoute;
      default:
        return null;
    }
  }
```
