### ISSUE TITLE
Flutter desktop embedding example on Windows is failing to initialize at first render

### ISSUE THREAD

**Issue by Gopinathp** [flutter/flutter#41361] opened 2019-09-26 10:10 UTC
## Steps to Reproduce

git clone https://github.com/google/flutter-desktop-embedding.git
cd .\flutter-desktop-embedding\example\
flutter run

## Logs
PS E:\code\oss\flutter-desktop-embedding\example> flutter run --verbose
[  +19 ms] executing: [E:\devtools\flutter\] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +39 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +2 ms] e0247442d019516a534b66b4f5a8c47c1e2c0a3d
[   +5 ms] executing: [E:\devtools\flutter\] git describe --match v*.*.* --first-parent --long --tags
[  +37 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[   +2 ms] v1.10.6-23-ge0247442d
[  +11 ms] executing: [E:\devtools\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[  +21 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] origin/master
[   +5 ms] executing: [E:\devtools\flutter\] git ls-remote --get-url origin
[  +21 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter.git
[  +54 ms] executing: [E:\devtools\flutter\] git rev-parse --abbrev-ref HEAD
[  +20 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] master
[ +180 ms] Unable to locate an Android SDK.
[ +183 ms] Unable to locate an Android SDK.
[  +88 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +5 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +4 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +4 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +9 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +5 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +5 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +4 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[ +130 ms] Launching lib\main.dart on Windows in debug mode...
[  +28 ms] executing: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe -format json -utf8 -latest -requires Microsoft.Component.MSBuild
Microsoft.VisualStudio.Component.VC.Tools.x86.x64 Microsoft.VisualStudio.Component.Windows10SDK.17763
[  +21 ms] Exit code 0 from: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe -format json -utf8 -latest -requires Microsoft.Component.MSBuild
Microsoft.VisualStudio.Component.VC.Tools.x86.x64 Microsoft.VisualStudio.Component.Windows10SDK.17763
[   +3 ms] [
             {
               "instanceId": "b9aa9a15",
               "installDate": "2019-09-26T21:03:31Z",
               "installationName": "VisualStudio/15.9.16+28307.858",
               "installationPath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community",
               "installationVersion": "15.9.28307.858",
               "productId": "Microsoft.VisualStudio.Product.Community",
               "productPath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\Common7\\IDE\\devenv.exe",
               "state": 4294967295,
               "isComplete": true,
               "isLaunchable": true,
               "isPrerelease": false,
               "isRebootRequired": false,
               "displayName": "Visual Studio Community 2017",
               "description": "Free, fully-featured IDE for students, open-source and individual developers",
               "channelId": "VisualStudio.15.Release",
               "channelUri": "https://aka.ms/vs/15/release/channel",
               "enginePath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\Installer\\resources\\app\\ServiceHub\\Services\\Microsoft.VisualStudio.Setup.Service",
               "releaseNotes": "https://go.microsoft.com/fwlink/?LinkId=660692#15.9.16",
               "thirdPartyNotices": "https://go.microsoft.com/fwlink/?LinkId=660708",
               "updateDate": "2019-09-26T21:03:31.8736708Z",
               "catalog": {
                 "buildBranch": "d15.9",
                 "buildVersion": "15.9.28307.858",
                 "id": "VisualStudio/15.9.16+28307.858",
                 "localBuild": "build-lab",
                 "manifestName": "VisualStudio",
                 "manifestType": "installer",
                 "productDisplayVersion": "15.9.16",
                 "productLine": "Dev15",
                 "productLineVersion": "2017",
                 "productMilestone": "RTW",
                 "productMilestoneIsPreRelease": "False",
                 "productName": "Visual Studio",
                 "productPatchVersion": "16",
                 "productPreReleaseMilestoneSuffix": "1.0",
                 "productRelease": "RTW",
                 "productSemanticVersion": "15.9.16+28307.858",
                 "requiredEngineVersion": "1.18.1049.33485"
               },
               "properties": {
                 "campaignId": "1924023067.1569531026",
                 "channelManifestId": "VisualStudio.15.Release/15.9.16+28307.858",
                 "nickname": "",
                 "setupEngineFilePath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\Installer\\vs_installershell.exe"
               }
             }
           ]
[  +94 ms] Building Windows application...
[ +115 ms] **********************************************************************
[   +1 ms] ** Visual Studio 2017 Developer Command Prompt v15.9.16
[   +5 ms] ** Copyright (c) 2017 Microsoft Corporation
[   +4 ms] **********************************************************************
[ +573 ms] [vcvarsall.bat] Environment initialized for: 'x64'
[ +164 ms] Microsoft (R) Build Engine version 15.9.21+g9802d43bc3 for .NET Framework
[   +2 ms] Copyright (C) Microsoft Corporation. All rights reserved.
[   +8 ms] Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
[ +167 ms] Build started 9/26/2019 3:44:54 PM.
[ +489 ms] Project "E:\code\oss\flutter-desktop-embedding\example\windows\Runner.sln" on node 1 (default targets).
[   +2 ms] ValidateSolutionConfiguration:
[   +5 ms]   Building solution configuration "Debug|x64".
[ +293 ms] Project "E:\code\oss\flutter-desktop-embedding\example\windows\Runner.sln" (1) is building
"E:\code\oss\flutter-desktop-embedding\example\windows\Runner.vcxproj.metaproj" (2) on node 1 (default targets).
[   +3 ms] Project "E:\code\oss\flutter-desktop-embedding\example\windows\Runner.vcxproj.metaproj" (2) is building
"E:\code\oss\flutter-desktop-embedding\example\windows\FlutterBuild.vcxproj" (3) on node 1 (default targets).
[   +9 ms] InitializeBuildStatus:
[   +9 ms]   Creating "x64\Debug\Flutter Build.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
[   +3 ms] CustomBuildStep:
[   +5 ms]   Running Flutter backend build
[  +15 ms]   "E:\code\oss\flutter-desktop-embedding\example\windows\scripts\prepare_dependencies" Debug
[   +1 ms]   :VCEnd
[+2042 ms] FinalizeBuildStatus:
[   +1 ms]   Deleting file "x64\Debug\Flutter Build.tlog\unsuccessfulbuild".
[   +4 ms]   Touching "x64\Debug\Flutter Build.tlog\Flutter Build.lastbuildstate".
[   +4 ms] Done Building Project "E:\code\oss\flutter-desktop-embedding\example\windows\FlutterBuild.vcxproj" (default targets).
[  +77 ms] Project "E:\code\oss\flutter-desktop-embedding\example\windows\Runner.vcxproj.metaproj" (2) is building
"E:\code\oss\flutter-desktop-embedding\example\windows\Runner.vcxproj" (4) on node 1 (default targets).
[   +3 ms] InitializeBuildStatus:
[   +9 ms]   Creating "E:\code\oss\flutter-desktop-embedding\example\windows\..\build\windows\intermediates\x64\Debug\Runner\Runner.tlog\unsuccessfulbuild" because "AlwaysCreate"
was specified.
[  +56 ms] ClCompile:
[   +1 ms]   All outputs are up-to-date.
[  +21 ms] ResourceCompile:
[   +1 ms]   All outputs are up-to-date.
[   +5 ms] ManifestResourceCompile:
[   +2 ms]   All outputs are up-to-date.
[  +37 ms] Link:
[   +1 ms]   All outputs are up-to-date.
[   +4 ms]   Runner.vcxproj -> E:\code\oss\flutter-desktop-embedding\example\windows\..\build\windows\x64\Debug\Runner\Flutter Desktop Example.exe
[   +3 ms] CustomBuildStep:
[   +4 ms]   Bundling dependencies
[   +3 ms]   "E:\code\oss\flutter-desktop-embedding\example\windows\scripts\bundle_assets_and_deps" "E:\code\oss\flutter-desktop-embedding\example\windows\flutter\ephemeral\"
"E:\code\oss\flutter-desktop-embedding\example\windows\..\build\windows\x64\Debug\Runner\" "Flutter Desktop Example.exe"
[   +4 ms]   :VCEnd
[ +166 ms]   11 File(s) copied
[   +8 ms]   0 File(s) copied
[  +11 ms]   0 File(s) copied
[   +5 ms] FinalizeBuildStatus:
[   +1 ms]   Deleting file "E:\code\oss\flutter-desktop-embedding\example\windows\..\build\windows\intermediates\x64\Debug\Runner\Runner.tlog\unsuccessfulbuild".
[   +4 ms]   Touching "E:\code\oss\flutter-desktop-embedding\example\windows\..\build\windows\intermediates\x64\Debug\Runner\Runner.tlog\Runner.lastbuildstate".
[   +6 ms] Done Building Project "E:\code\oss\flutter-desktop-embedding\example\windows\Runner.vcxproj" (default targets).
[   +5 ms] Done Building Project "E:\code\oss\flutter-desktop-embedding\example\windows\Runner.vcxproj.metaproj" (default targets).
[   +4 ms] Done Building Project "E:\code\oss\flutter-desktop-embedding\example\windows\Runner.sln" (default targets).
[   +4 ms] Build succeeded.
[   +5 ms]     0 Warning(s)
[   +3 ms]     0 Error(s)
[   +3 ms] Time Elapsed 00:00:03.35
[  +12 ms] Building Windows application... (completed in 4.4s)
[   +3 ms] executing: build\windows\x64\Debug\Runner\Flutter Desktop Example.exe
[ +101 ms] [ERROR:c:\b\s\w\ir\cache\builder\src\flutter\shell\platform\embedder\embedder.cc(629)] Not running in AOT mode but could not resolve the kernel binary.
[  +11 ms] [ERROR:c:\b\s\w\ir\cache\builder\src\flutter\shell\platform\embedder\embedder.cc(53)] Returning error 'kInvalidArguments' (2) from Flutter Embedder API call to
'FlutterEngineRun'. Origin: c:\b\s\w\ir\cache\builder\src\flutter\shell\platform\embedder\embedder.cc:631
[   +5 ms] Failed to start Flutter engine: error 2
[  +10 ms] Failed to create view.

> Please help resolve this issue. 
> Thanks.

## Flutter Doctor Verbose

PS C:\Users\Admin> flutter doctor -v
[√] Flutter (Channel master, v1.10.7-pre.23, on Microsoft Windows [Version 10.0.10586], locale en-US)
    • Flutter version 1.10.7-pre.23 at E:\devtools\flutter
    • Framework revision e0247442d0 (16 hours ago), 2019-09-26 02:49:41 -0400
    • Engine revision 3713ecf107
    • Dart version 2.6.0 (build 2.6.0-dev.2.0 c6a14f4459)

[X] Android toolchain - develop for Android devices
    X Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_HOME to that location.
      You may also want to add it to your PATH environment variable.

[√] Visual Studio - develop for Windows (Visual Studio Community 2017 15.9.16)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2017\Community
    • Visual Studio Community 2017 version 15.9.28307.858

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).

[√] IntelliJ IDEA Community Edition (version 2019.2)
    • IntelliJ at C:\Users\Admin\AppData\Local\JetBrains\Toolbox\apps\IDEA-C\ch-0\192.6817.14
    • Flutter plugin version 39.0.5
    • Dart plugin version 192.6817.14

[√] Connected device (1 available)
    • Windows • Windows • windows-x64 • Microsoft Windows [Version 10.0.10586]

! Doctor found issues in 2 categories.
```

**Comment by stuartmorgan** [comment] 2019-09-26 14:15
Duplicate of #41352

**Closed by stuartmorgan** 2019-09-26 14:15 UTC
Labels: a: desktop, engine, tool, ❖ platform-windows
