### ISSUE TITLE
setting the userId in firebase admob rewarded video.

### ISSUE THREAD

**Issue by soofi-cheenilabs** [flutter/flutter#33033] opened 2019-05-20 09:51 UTC
I am using the firebase rewarded video and there's a method called setUserId(String userId) in the following link: 
https://developers.google.com/android/reference/com/google/android/gms/ads/reward/RewardedVideoAd.html#setUserId(java.lang.String)

I am using the flutter firebase_admob plugin available at the link: 
https://github.com/flutter/plugins/tree/master/packages/firebase_admob

How to use the method setUserId(String userId) in flutter using the flutter firebase_admob plugin? I couldn't find this in the plugin. 

Will be thankful for the reply!

**Comment by soofi-cheenilabs** [comment] 2019-05-22 18:16
This issue has been solved now as I included the following API:
```
public void setCustomData(String customData){
  // pass custom data to the server
}
```
This API is used for SSV (Server-Side Verification). 

I am currently using this API for passing custom data to the server. For those of you who are looking for an immediate solution and don't want to wait till the Google Flutter Team adds the missing APIs, can use this plugin by adding this plugin in the pubspec.yaml file in the following way:

```
dependencies:
  firebase_admob:
    git:
      url: git://github.com/soofi-cheenilabs/firebase_admob.git
  # your other dependencies
```

**Comment by ozcanfurkan** [comment] 2019-09-03 12:11
I'm waiting for setting userId in admob rewarded video. When firebase_admob plugin will update?

@soofi-cheenilabs thx for solution but not work on iOS.

**Comment by soofi-cheenilabs** [comment] 2019-09-03 16:28
> I'm waiting for setting userId in admob rewarded video. When firebase_admob plugin will update?
> 
> @soofi-cheenilabs thx for solution but not work on iOS.

You're welcome. 

I am not using the plugin now... You can tweak the code to make it to work in iOS...

**Comment by TahaTesser** [comment] 2020-03-18 15:57
Hi @soofi-cheenilabs 
Are you still experiencing this issue with latest stable? Since the mentioned PR is merged
Thank you

**Comment by Adem68** [comment] 2020-03-18 16:00
@TahaTesser i can confirm issue was fixed with pr.

**Comment by TahaTesser** [comment] 2020-03-18 16:07
@Adem68 
given your last message I feel safe to close this issue,
if you disagree please write in the comments and I will reopen it. 
Thank you

**Closed by TahaTesser** 2020-03-18 16:07 UTC
Labels: p: firebase, p: firebase_admob, plugin, waiting for customer response
