### ISSUE TITLE
Build failed with flutter run command

### ISSUE THREAD

**Issue by mehranshoqi** [flutter/flutter#74604] opened 2021-01-24 19:06 UTC
Hello every one,

i use cloud firestore and auth firebase,
when i want to run App is return Error messages like this:

<>
    
    FAILURE: Build failed with an exception.
    
    * Where:
    Script 'D:\Flutter\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 904
    
    * What went wrong:
    Execution failed for task ':app:compileFlutterBuildDebug'.
    > Process 'command 'D:\Flutter\flutter\bin\flutter.bat'' finished with non-zero exit value 1
    
    * Try:
    Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

<>

i try changing targetsdkversion and  googleservice version in build.gradle but still doesnt work.
![Screenshot (7)](https://user-images.githubusercontent.com/65711096/105640717-a6b54380-5e94-11eb-9f0f-963574946ec1.png)

**Comment by iapicca** [comment] 2021-01-24 20:03
@mehranshoqi 
[firebase](https://firebase.flutter.dev/) is a 3rd party plugin, please open an issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues)
or provide your `flutter doctor -v`, your `flutter run -d chrome -v` 
and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) without 3rd party plugins

**Comment by mehranshoqi** [comment] 2021-01-25 05:27
Hi @iapicca 

i removed Read only attribute for root folder and All work correctly.

**Comment by iapicca** [comment] 2021-01-25 08:15
@mehranshoqi 
if the problem is solved consider closing the issue

**Closed** 2021-01-25 08:18 UTC
