### ISSUE TITLE
Nested ListView scrolling behaves differently in Android build than Web build

### ISSUE THREAD

**Issue by davebound** [flutter/flutter#85312] opened 2021-06-25 12:33 UTC
The following code implements a ListView with a nested ListView as one of the children.

**Behavior for Web build**: When I scroll down to bottom of nested ListView, it causes the Parent to scroll.

**Behavior for Android build**: When I scroll down to bottom of nested ListView, it DOESN'T cause the Parent to scroll.

Why the difference? How can I make the Android build behave like the Web build?

Thanks

```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(title: Text('Demo')),
        // body: CollapsingList(),
        body: NestedLists(),
      ),
    );
  }
}

class NestedLists extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return ListView(
      children: [
        Container(color: Colors.red, height: 150.0),
        Container(color: Colors.purple, height: 150.0),
        Container(color: Colors.green, height: 150.0),
        Container(color: Colors.orange, height: 150.0),
        Padding(
          padding: const EdgeInsets.all(20.0),
          child: Container(
            height: 150,
            child: ListView(
              children: [
                Container(color: Colors.yellow, height: 50.0),
                Container(color: Colors.pink, height: 50.0),
                Container(color: Colors.cyan, height: 50.0),
                Container(color: Colors.indigo, height: 50.0),
                Container(color: Colors.blue, height: 50.0),
                Container(color: Colors.yellow, height: 50.0),
                Container(color: Colors.pink, height: 50.0),
                Container(color: Colors.cyan, height: 50.0),
                Container(color: Colors.indigo, height: 50.0),
                Container(color: Colors.blue, height: 50.0),
                Container(color: Colors.yellow, height: 50.0),
              ],
            ),
          ),
        ),
        Container(color: Colors.yellow, height: 150.0),
        Container(color: Colors.pink, height: 150.0),
        Container(color: Colors.cyan, height: 150.0),
        Container(color: Colors.indigo, height: 150.0),
        Container(color: Colors.blue, height: 150.0),
      ],
    );
  }
}

```

```
[√] Flutter (Channel beta, 2.0.2, on Microsoft Windows [Version 10.0.19042.1052], locale en-GB)
    • Flutter version 2.0.2 at c:\src\flutter
    • Framework revision 8962f6dc68 (4 months ago), 2021-03-11 13:22:20 -0800
    • Engine revision 5d8bf811b3
    • Dart version 2.12.1

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\Dave\AppData\Local\Android\sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30517.126
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 51.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.57.1)
    • VS Code at C:\Users\Dave\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.23.0

[√] Connected device (4 available)
    • ONEPLUS A3003 (mobile) • 5a78f914 • android-arm64  • Android 9 (API 28)
    • Windows (desktop)      • windows  • windows-x64    • Microsoft Windows [Version 10.0.19042.1052]
    • Chrome (web)           • chrome   • web-javascript • Google Chrome 91.0.4472.77
    • Edge (web)             • edge     • web-javascript • Microsoft Edge 91.0.864.54

• No issues found!
```

</details>

**Comment by TahaTesser** [comment] 2021-06-28 11:26
HI @davebound 
Scrolling on mobile vs desktop (web or desktop) is quite different, one is using touch gestures to scroll, and the other using a mouse or trackpad.  You can reproduce the same behavior on the desktop app.  

This is the same as https://github.com/flutter/flutter/issues/84158
The expected behavior should be the opposite of what you're expecting to do, it shouldn't scroll outer scroll when scrolling the inner scroll. Since the behaviour on desktop is not matching, this is a bug on desktop

Closing as duplicate of https://github.com/flutter/flutter/issues/84158

**Closed by TahaTesser** 2021-06-28 11:26 UTC
Labels: in triage
