### ISSUE TITLE
Issue from website page Create a horizontal list

### ISSUE THREAD

**Issue by DreaddCZ** [flutter/flutter#15127] opened 2018-03-04 11:24 UTC
From URL: https://flutter.io/cookbook/lists/horizontal-list.md

The "Complete example" does not have the horizontal scrolling inside. It is probably copied from another article.

**Comment by jordyvandomselaar** [comment] 2018-03-05 14:30
The url you've provided gives back a 404.

**Comment by brianegan** [comment] 2018-03-06 16:14
Thanks for the report! This is a dupe of https://github.com/flutter/flutter/issues/14914 and fixed by https://github.com/flutter/website/pull/822. I'm bugging some peeps for more reviews!

**Comment by brianegan** [comment] 2018-03-12 14:08
Maintainers: This is now fixed on the website. Please close!

**Closed** 2018-04-18 14:27 UTC
