### ISSUE TITLE
 The following assertion was thrown during performLayout(): 'package:flutter/src/painting/alignment.dart': Failed assertion: line 530 pos 12: 'direction !=null': is not true.

### ISSUE THREAD

**Issue by zuimozhiya** [flutter/flutter#36728] opened 2019-07-23 03:06 UTC
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```

```
```

**Comment by BondarenkoStas** [comment] 2019-09-23 13:17
@zuimozhiya In most of cases assertion errors are caused by implementation mistakes. I would advise you to post it to SO with code example to reproduce it. Closing the issue as no information available for investigation and it's not clear if it's a framework bug.

**Closed by BondarenkoStas** 2019-09-23 13:17 UTC
