### ISSUE TITLE
flutter build ipa --export-method not accepting enterprise flag

### ISSUE THREAD

**Issue by kakaru1331** [flutter/flutter#158561] opened 2024-11-13 09:04 UTC
### Steps to reproduce

1. Make sure currently using Flutter 3.24.4
2. run ```flutter create sample```
3. run ```flutter build ipa --export-method enterprise```

### Expected results

Successfully builds .xcarchive and .ipa in build/ios/ipa

### Actual results

```Runner.xrarchive``` successfully built but the message ```Encountered invalid export-method input.``` was displayed

### Code sample

Following the steps above using Flutter 3.24.4

It's a bug that was reported before.
https://github.com/flutter/flutter/issues/153000

There is even a history of bug fixes.
https://github.com/flutter/flutter/pull/153047

However it still occurs in version 3.24.4 as well

### Screenshots or Video

<img width="536" alt="image" src="https://github.com/user-attachments/assets/d208bf63-31ea-4752-93e1-62aece542859">

### Logs

<details open><summary>Logs</summary>

```console
To update the settings, please refer to https://flutter.dev/to/ios-deploy

Encountered invalid export-method input.
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.24.4, on macOS 14.6 23G80 darwin-arm64, locale ko-KR)
    • Flutter version 3.24.4 on channel stable at /Users/chihawn/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 603104015d (3 weeks ago), 2024-10-24 08:01:25 -0700
    • Engine revision db49896cf2
    • Dart version 3.5.4
    • DevTools version 2.37.3

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at /Users/chihawn/Library/Android/sdk
    • Platform android-35, build-tools 35.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16B40
    • CocoaPods version 1.16.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)

[✓] VS Code (version 1.95.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (4 available)
    • iPhone 16 Pro (mobile)          • D99BB50F-0275-476D-80F6-4429CF3304A4 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-18-1 (simulator)
    • macOS (desktop)                 • macos                                • darwin-arm64   • macOS 14.6 23G80 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad                • darwin         • macOS 14.6 23G80 darwin-arm64
    • Chrome (web)                    • chrome                               • web-javascript • Google Chrome 130.0.6723.117

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by darshankawar** [comment] 2024-11-13 11:16
@kakaru1331 
The fix most likely wasn't hot-fixed to be in stable version, as I don't see the fix in https://github.com/flutter/flutter/blob/master/CHANGELOG.md and hence you are still seeing this in latest stable version. Can you switch to latest master or beta and re-run your scenario as this must be available in those versions.

**Comment by kakaru1331** [comment] 2024-11-14 01:46
@darshankawar 
```flutter build ipa --export-method enterprise```
It works on version [3.27.0-0.1.pre](https://storage.googleapis.com/flutter_infra_release/releases/beta/macos/flutter_macos_arm64_3.27.0-0.1.pre-beta.zip).
Thank you for your help!

**Comment by huycozy** [comment] 2024-11-14 05:22
@kakaru1331 Thanks for confirming that. Closing this as a duplicate of https://github.com/flutter/flutter/issues/153000.

**Closed by huycozy** 2024-11-14 05:22 UTC
Labels: in triage
