### ISSUE TITLE
didChangeMetrics() wrongly called on iOS

### ISSUE THREAD

**Issue by PerLycke** [flutter/flutter#89824] opened 2021-09-10 06:56 UTC
## Steps to Reproduce

1. Run the code below on iOS (I tried the simulator and a physical device)

**Expected results:** didChangeMetrics() should not be called if metrics didn't change. Docs says "Called when the application's dimensions change", but it seems to be called even without dimension change.

**Actual results:** didChangeMetrics() is called when widget tree contains SingleChildScrollView, ListView or similar.

Reproducible code:

```
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      title: 'Flutter Demo',
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key}) : super(key: key);

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> with WidgetsBindingObserver {
  Size? _previousSize;
  Size? _newSize;

  @override
  void initState() {
    _previousSize = WidgetsBinding.instance!.window.physicalSize;
    WidgetsBinding.instance!.addObserver(this);
    super.initState();
  }

  @override
  void dispose() {
    WidgetsBinding.instance!.removeObserver(this);
    super.dispose();
  }

  @override
  void didChangeMetrics() {
    setState(() {
      _newSize = WidgetsBinding.instance!.window.physicalSize;
    });
    super.didChangeMetrics();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: SingleChildScrollView(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              Text(
                'Size in initState: $_previousSize',
              ),
              Text(
                'Size in didChangeMetrics: $_newSize',
              ),
            ],
          ),
        ),
      ),
    );
  }
}
```

<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel stable, 2.5.0, on macOS 11.5.2 20G95 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.60.0)
[✓] Connected device (3 available)
```

</details>

**Comment by danagbemava-nc** [comment] 2021-09-10 13:04
Hi @PerLycke, do you experience this issue on first run or you experience it after a `hot reload`/`hot restart` ?

**Comment by PerLycke** [comment] 2021-09-10 13:18
Just tried on the iOS simulator and it happens both on first run and hot restart. This is probably a regression, as I didn't notice it happen pre 2.5. Reason I discovered it is due to us handling a bug in a package in our production app by delaying painting a widget after user rotates the device. Now the delay happens even without rotation.

I dealt with this already in our code by comparing metrics reported before and after, but either way -> it shouldn't fire off didChangeMetrics if metrics didn't change (I suppose).

**Comment by danagbemava-nc** [comment] 2021-09-10 14:48
I just checked on `stable 2.2.3` and `didMetricsChange` is called on first run, with or without the `SingleChildScrollView`, so I believe this is the intended behaviour. 

It is also called on `hot restart`, however, the value of size at that point is `null`.

<details>
<summary>flutter doctor -v</summary>

```console
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.5.1 20G80 darwin-arm, locale
    en-GB)
    • Flutter version 2.2.3 at /Users/nexus/dev/sdks/flutter
    • Framework revision f4abaa0735 (2 months ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.11.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.60.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (3 available)
    • iPhone 12 (mobile) • F2592D43-5FE3-46BB-8A2B-A38BA468DCE9 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)    • macos                                • darwin-arm64
      • macOS 11.5.1 20G80 darwin-arm
    • Chrome (web)       • chrome                               • web-javascript
      • Google Chrome 93.0.4577.63

• No issues found!
```
</details>

## Screenshot

![Simulator Screen Shot - iPhone 12 - 2021-09-10 at 14 40 41](https://user-images.githubusercontent.com/88313112/132872618-436ada0c-dac3-4e0c-a5ac-264cca420f23.png)

I think you should also check on `stable 2.2.3` just so we can be certain.

**Comment by TahaTesser** [comment] 2021-10-01 09:59
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by TahaTesser** 2021-10-01 09:59 UTC
