### ISSUE TITLE
Flutter web - DB 81 DE BB instead of icon

### ISSUE THREAD

**Issue by aseremak** [flutter/flutter#140056] opened 2023-12-13 13:49 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

This is not reproducible and I can't tell you how to reproduce the problem, but I hope that with the details described below you will be able to determine what is causing the problem.

Sometimes strange images with text "DB 81" and "DE BB" are observed instead of icons:
![obraz](https://github.com/flutter/flutter/assets/50106387/38bcd94d-7faf-46be-89e0-dbee648fad87)

More details:
- it happen on the deployed web page only. I have never observed this in debug mode
- it only happens sometimes and only on some browsers, i.e. one user observed an error in Firefox, but in Chrome it was OK, and at the same time on the other computer it was also OK in Firefox
- it concerns only specific icons (Icons.signpost_outlined and Icons.calendar_month). Only these icons are sometimes displayed incorrectly. After replacing Icons.signpost_outlined with Icons.timeline, I did not observe the error on the second one.
 

### Expected results

Below is a view of how the mentioned icons are displayed correctly:

![obraz](https://github.com/flutter/flutter/assets/50106387/57102847-2b2c-465c-aa5d-d121c82d9940)
![obraz](https://github.com/flutter/flutter/assets/50106387/c54ac614-3c78-4199-94be-bf108054243c)

### Actual results

-

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[!] Flutter (Channel unknown, 3.3.8, on Ubuntu 22.04.3 LTS 6.2.0-37-generic, locale en_US.UTF-8)
    ! Flutter version 3.3.8 on channel unknown at /home/adams/flutter-stable
    ! Upstream repository unknown
    • Framework revision 52b3dc25f6 (1 year, 1 month ago), 2022-11-09 12:09:26 +0800
    • Engine revision 857bd6b74c
    • Dart version 2.18.4
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /home/adams/Android/Sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /home/adams/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 14.0.0-1ubuntu1.1
    • cmake version 3.22.1
    • ninja version 1.10.1
    • pkg-config version 0.29.2

[✓] Android Studio (version 2021.2)
    • Android Studio at /home/adams/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code
    • VS Code at /snap/code/current
    • Flutter extension version 3.78.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 22.04.3 LTS 6.2.0-37-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 120.0.6099.109

[✓] HTTP Host Availability
    • All required HTTP hosts are available
```

</details>

**Comment by huycozy** [comment] 2023-12-14 05:08
Hi @aseremak 
I also can't reproduce this issue with those two icons. 

>it only happens sometimes and only on some browsers, i.e. one user observed an error in Firefox, but in Chrome it was OK, and at the same time on the other computer it was also OK in Firefox

It could only occur on a specific browser version. Please ask your user for this information if possible. 

Also, I see you are using an old Flutter version. The latest stable is 3.16.4, please try upgrading to this version and sending a test app to your user to see if the issue persists or not.

**Comment by aseremak** [comment] 2023-12-14 07:58
Hi @huycozy

> It could only occur on a specific browser version. Please ask your user for this information if possible.

I will ask this user and others who have the same problem and I will come back with the data in a few days.
 
> Also, I see you are using an old Flutter version. The latest stable is 3.16.4, please try upgrading to this version and sending a test app to your user to see if the issue persists or not.

I have to use this version because subsequent versions have a crucial issue https://github.com/flutter/flutter/issues/129182

**Comment by huycozy** [comment] 2023-12-14 11:32
>I have to use this version because subsequent versions have a crucial issue https://github.com/flutter/flutter/issues/129182

It would be helpful if you could check this issue temporarily to see if it's fixed on a new Flutter version or not.

**Closed** 2024-01-04 12:09 UTC
Labels: waiting for customer response, in triage
