### ISSUE TITLE
When tab key is pressed on Flutter Web it does not focus to next TextFormField

### ISSUE THREAD

**Issue by abhimanyu95** [flutter/flutter#91023] opened 2021-09-30 11:54 UTC
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

 The expected result should be when the tab key is pressed then next TextFormField should be focused.

**Actual results:** 

In actual it does not focus to immediate next TextFormField.

<details>
  <summary></summary>

```
   Form(
    key: _addUserKey,
    child: Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Padding(
          padding: const EdgeInsets.symmetric(vertical: 12),
          child:
          Text(Constants.accountInfo, style: _headerStyle()),
        ),
        Row(
          children: [
            Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                /// Email
                Container(
                  width: 25.w,
                  child: TextFormField(
                    focusNode: _emailFocusNode,
                    controller:_addUserController.emailController,
                    validator: (v) => v!.trim().isEmpty
                        ? Constants.thisFieldIsRequired
                        : !EmailValidator.validate(v.trim()) ? Constants.pleaseEnterValidEmail : null,
                    decoration: InputDecoration(
                        isDense: true,
                        labelText: Constants.email,
                        hintText: Constants.email,
                        border: OutlineInputBorder()),
                  ),
                ),
                _vSpacer,

                /// Password
                Container(
                  width: 25.w,
                  child: Obx(
                        ()=> TextFormField(
                      focusNode: _passwordFocusNode,
                      controller:_addUserController.passwordController,
                      validator: (v) => v!.trim().isEmpty
                          ? Constants.thisFieldIsRequired
                          : v.trim().length < 8
                          ? Constants.enterValidPassword
                          : null,
                      obscureText: !isPasswordVisible.value,
                      obscuringCharacter: '*',
                      onTap: null,
                      decoration: InputDecoration(
                          isDense: true,
                          suffixIcon: GestureDetector(
                              onTapUp: (p){
                                isPasswordVisible.value=false;
                              },
                              onTapDown: (p){
                                isPasswordVisible.value=true;
                              },
                              child: Icon(Icons.remove_red_eye)),
                          labelText: Constants.password,
                          hintText: Constants.password,
                          border: OutlineInputBorder()),
                    ),
                  ),
                ),
                _vSpacer,

                /// Confirm Password
                Container(
                  child: Obx(()=> TextFormField(
                    focusNode: _confirmPasswordFocusNode,
                    controller: _addUserController
                        .confirmPasswordController,
                    validator: (v) => v!.trim().isEmpty
                        ? Constants.thisFieldIsRequired
                        : v.trim() != _addUserController
                        .passwordController.text
                        .trim()
                        ? Constants.passwordDoNotMatches
                        : null,
                    obscureText: !isConfirmPasswordVisible.value,
                    obscuringCharacter: '*',
                    onTap: null,
                    textInputAction: TextInputAction.next,
                    decoration: InputDecoration(
                        isDense: true,
                        suffixIcon: GestureDetector(
                            onTapUp: (p){
                              isConfirmPasswordVisible.value=false;
                            },
                            onTapDown: (p){
                              isConfirmPasswordVisible.value=true;
                            },
                            child: Icon(Icons.remove_red_eye)),
                        labelText: Constants.confirmPassword,
                        hintText: Constants.confirmPassword,
                        border: OutlineInputBorder()),
                  ),
                  ),
                  width: 25.w,
                ),
                _vSpacer,

              ],
            ),
          ],
        ),
       
        /// Some other widgets
        
      ],
    ),
  )
```

```
```

```
```

</details>

**Comment by maheshmnj** [comment] 2021-09-30 13:34
@abhimanyu95 I don't see your code sample having any code which shifts focus to the next form field. So I see this as working as intended. 

If you want to shift focus to the next field you could either use the [FocusNode](https://api.flutter.dev/flutter/widgets/FocusNode-class.html) and manually shift focus to desire fields or you could use [TextInputAction](https://api.flutter.dev/flutter/services/TextInputAction-class.html) to shift focus.


```dart
TextFormField(
    decoration: InputDecoration(hintText: 'TextField A'),
    textInputAction: TextInputAction.next, // Moves focus to next.
   ),
TextFormField(
    decoration: InputDecoration(hintText: 'TextField B'),
    textInputAction: TextInputAction.next, // Moves focus to next.
),
TextFormField(
    decoration: InputDecoration(hintText: 'TextField C'),
    textInputAction: TextInputAction.done, // Hides the keyboard.
),
```
 
Closing the issue, As this is working as intended, If you disagree feel free to write in the comments and I will reopen it.

Thank you

**Closed by maheshmnj** 2021-09-30 13:34 UTC
Labels: in triage
