### ISSUE TITLE
Build --tree-shake-icons option crashes computer

### ISSUE THREAD

**Issue by ivanjpg** [flutter/flutter#56473] opened 2020-05-06 20:40 UTC
I've been trying to build my application into production (iOS and Android) with:

```bash
--release \
--split-debug-info=./debug-info/${APP_VERSION}/${TARGET}/ \
--obfuscate \
--verbose
```

also `--shrink` for Android; this works well. But if I include `--tree-shake-icons` no matter if it is for iOS or Android, the computer hangs and then restarts (MacBook Pro, Mid 2012, 10.15.4 and 8GB of RAM). I've trying with Flutter v1.12.13+hotfix.{7,8,9} stable; Beta 1.17* and today 1.17.0 stable; all with the same results.

The last thing I saw in the log was:

```
Runnning command:
flutter/bin/cache/dart-sdk/bin/dart
flutter/bin/cache/artifacts/engine/darwin-x64/const_finder.dart.snapshot --kernel-file
/APPDIR/.dart_tool/flutter_build/HASH/app.dill --class-library-uri
package:flutter/src/widgets/icon_data.dart --class-name IconData
```

After that appears on screen the computer freezes and then shuts down. `flutter doctor -v` shows no problems at all.

Thanks in advance.

**Comment by jonahwilliams** [comment] 2020-05-06 21:05
This is unfortunately a known issue that was fixed with https://github.com/flutter/flutter/pull/55417 , but that did not make it to stable.

FYI @csells @zanderso @pcsosinski

**Comment by awhitford** [comment] 2020-05-17 18:11
I am using **Flutter 1.17.1** and when I try using `--tree-shake-icons`, it breaks:
```
    Failed to subset font; aborting.

    Target release_ios_bundle_flutter_assets failed: FontSubset error: Font subsetting failed with exit code 255.
    build failed.
    Command PhaseScriptExecution failed with a nonzero exit code
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description

Encountered error while building for device.
```

**Comment by jonahwilliams** [comment] 2020-05-17 20:08
@awhitford  tree-shake-icons is not ready in 1.17.x, the fix was to hide the option

**Comment by zanderso** [comment] 2020-05-19 21:10
The issue is fixed on master and the appropriate mitigation has been cherry-picked, so I'll close this issue.

**Closed by zanderso** 2020-05-19 21:10 UTC
Labels: cp: 1.17, cp: 1.17 completed, cp: 1.18, cp: 1.18 completed, found in release: 1.17, found in release: 1.18, hotfix: 1.17, severe: crash, tool

**Comment by suztomo** [comment] 2020-06-25 04:48
@awhitford I hit the same error as yours "FontSubset error: Font subsetting failed". Were you able to fix the error?

https://gist.github.com/suztomo/64ad27f3caaa90e38bd9ff963c3c5d9b

**Comment by awhitford** [comment] 2020-06-25 05:33
@suztomo I'm waiting for 1.18 based on:

> @awhitford tree-shake-icons is not ready in 1.17.x, the fix was to hide the option

**Comment by suztomo** [comment] 2020-06-26 04:14
Thanks. I created an issue for my problem with Flutter 1.19 (beta)

https://github.com/flutter/flutter/issues/60325
