### ISSUE TITLE
[impeller][ios][regression] Text is transformed incorrectly

### ISSUE THREAD

**Issue by delfme** [flutter/flutter#144333] opened 2024-02-28 19:19 UTC
### Steps to reproduce

This is a regression on issue https://github.com/flutter/flutter/issues/117428
It was working perfectly and regression should be caused by a very recent PR.

### Expected results

Text should transform correclty

### Actual results

See video:

https://github.com/flutter/flutter/assets/53510751/005a228d-3530-413c-a618-1a8a268485e0

### Code sample

Please run sample here. 
https://github.com/delfme/native-text-transform/tree/main

It showcases text transformation for both flutter and native text.
- Before regression, flutter text was transforming perfectly thx to a fix from @bdero https://github.com/flutter/engine/pull/39119
and you guys asked to submit https://github.com/flutter/flutter/issues/120586 to track residual issue with native text. 
- After regression, flutter text transformation is broken. 

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

This is a video from sample code:

https://github.com/flutter/flutter/assets/53510751/ab192a94-6615-4486-a25f-6d8b126038d8

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 3.20.0-13.0.pre.28, on macOS 14.2.1 23C71 darwin-arm64, locale en-IT)
[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.1)

```

</details>

**Comment by darshankawar** [comment] 2024-02-29 08:17
Thanks for the report. I cloned your repo but was getting an error while running, so copied all code below to make it runnable and was able to replicate the error on master, but not on stable.

The repo though uses third party packages.

<details>
<summary> runnable code sample </summary>

```

import 'package:cube_transition/cube_transition.dart';
import 'package:flutter/material.dart';
import 'package:flutter_native_label/flutter_native_label.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatefulWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: DemoScreen(),
      theme: ThemeData(platform: TargetPlatform.android),
    );
  }
}

class HomePage extends StatelessWidget {

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Native Text Transform issue'),
      ),
      body:  Column(
        mainAxisAlignment: MainAxisAlignment.end,
        children: <Widget>[
          Center(
            child: ElevatedButton(
                onPressed: () {
                  Navigator.of(context).push(
                      MaterialPageRoute(builder: (_) => const DemoScreen()));
                },
                child: const Text('Demo screen')),
          ),
          const SizedBox(
            height: 20,
          ),
        ],
      ),
    );
  }
}


class DemoScreen extends StatefulWidget {
  const DemoScreen({Key? key}) : super(key: key);
  @override
  State<DemoScreen> createState() => _DemoScreenState();
}

class _DemoScreenState extends State<DemoScreen> with TickerProviderStateMixin {

  @override
  void initState() {
    super.initState();
  }


  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Demo screen'),
      ),
      body: SafeArea(
        child: Column(
          children: [

            const Spacer(),
            Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  // Flutter text
                  Container(
                    padding: EdgeInsets.all(20),
                    color: Colors.grey,
                    child: const Text(
                      'Flutter Text 👍👍👍👍 👍👍👍👍 ',
                      style: TextStyle(
                          fontSize: 17
                      ),
                    ),
                  ),
                  // Native text
                  Container(
                    padding: EdgeInsets.all(20),
                    color: Colors.grey,
                    child: const NativeLabel(
                      'Native Text 👍👍👍👍 👍👍👍👍 ',
                      style: TextStyle(
                          fontSize: 17
                      ),
                    ),
                  ),

                ]),
            SizedBox(height: 200),
            Center(
              child:ElevatedButton(
                child: Text('Tap me'),
                onPressed: () {
                  FocusScope.of(context).unfocus();
                  Navigator.of(context).push(
                    CubePageRoute(
                      enterPage: DemoPage(),
                      exitPage: context.widget,
                      duration: const Duration(milliseconds: 500),
                    ),
                  );
                },
              ),
            ),
            SizedBox(height: 50),
          ],
        ),
      ),
    );
  }
}

class DemoPage extends StatelessWidget {
  const DemoPage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Demo screen'),
      ),
      body: Center(

      ),
    );
  }
}

extension StringUtils on String {
  double get va {
    final values = split('@');
    final num psValue =
        int.tryParse(values.first) ?? double.tryParse(values.first) ?? 0;
    final num fontSize =
        int.tryParse(values.last) ?? double.tryParse(values.last) ?? 0;
    return psValue * fontSize / 1000;
  }
}

```

</details>


1. Master without impeller:


https://github.com/flutter/flutter/assets/67046386/12dea62d-9309-4d8d-96fd-dc702fdeca08


2. Stable with impeller:


https://github.com/flutter/flutter/assets/67046386/ddb593db-8f75-4e69-9a8b-a5ead2ea5363

<details>
<summary> stable, master flutter doctor -v </summary>

```
[!] Flutter (Channel stable, 3.19.1, on macOS 12.2.1 21D62 darwin-x64, locale
    en-GB)
    • Flutter version 3.19.1 on channel stable at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision abb292a07e (6 days ago), 2024-02-20 14:35:05 -0800
    • Engine revision 04817c99c9
    • Dart version 3.3.0
    • DevTools version 2.31.1
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.


[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

[!] Flutter (Channel master, 3.20.0-15.0.pre.23, on macOS 12.2.1 21D62
    darwin-x64, locale en-GB)
    • Flutter version 3.20.0-15.0.pre.23 on channel master at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 96a390a9e9 (12 minutes ago), 2024-02-28 04:51:10 +0000
    • Engine revision c79117b706
    • Dart version 3.4.0 (build 3.4.0-183.0.dev)
    • DevTools version 2.33.0-dev.11
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/dhs/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13C100
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 65.1.4
    • Dart plugin version 213.7228

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (3 available)
    • Darshan's iphone (mobile) • 21150b119064aecc249dfcfe05e259197461ce23 • ios
      • iOS 15.3.1 19D52
    • macOS (desktop)           • macos                                    •
      darwin-x64     • macOS 12.2.1 21D62 darwin-x64
    • Chrome (web)              • chrome                                   •
      web-javascript • Google Chrome 109.0.5414.119

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
      
[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.



```

</details>

**Comment by delfme** [comment] 2024-02-29 09:38
@darshankawar thx for this, that project's name used "-" instead of "_" which is no longer supported by flutter. 

I think regression is recent coz we work on master and update it frequently to help discovering issues. It should be a matter of weeks.

**Comment by jason-simmons** [comment] 2024-03-09 01:32
Noticed two issues here:

* The text is being rendered at the wrong position during the animation due to a change to clip depth (https://github.com/flutter/engine/commit/c3a7f5995be8571e1b4a898fc99a1132cd6bcc6a)

The text renders correctly if I patch https://github.com/flutter/engine/blob/main/impeller/entity/shaders/glyph_atlas.vert and replace:
`  gl_Position = frame_info.mvp * vec4(position.xy, 0.0, 1.0);`
with
`  gl_Position = frame_info.mvp * position;`

* The cube animation regressed with the adoption of stencil-then-cover.
  * With `kEnableStencilThenCover = true` part of the cube renders as black instead of white while animating.

@bdero

**Comment by jonahwilliams** [comment] 2024-03-11 19:56
Thanks for looking at this @jason-simmons , I wonder if the text issue in the cupertino picker is the same?

See https://github.com/flutter/flutter/issues/144331

**Comment by bdero** [comment] 2024-03-12 00:42
Video of the newer cutoff problem with StC:


https://github.com/flutter/flutter/assets/919017/2fa0a037-4c73-40f7-bf34-3e6b2ad809b3

**Comment by delfme** [comment] 2024-03-17 10:33
Hello @bdero thx so much for this! Unfortunately we still cannot call it a fix.
I could check it only today. Just upgraded to latest master.

Please see video below, tested on iOS 17.31.1 iphone 13pro.

1) text transforms way better than before but yet not on axis, as it was before the regression.
2) https://github.com/flutter/engine/pull/51343 is causing a new issue with the images.

https://github.com/flutter/flutter/assets/53510751/f33577e5-cb41-4eef-a1f5-72e13d17e094

**Comment by delfme** [comment] 2024-03-17 10:48
Also, app crashes pointing to this Impeller issue.

#0	0x000000010c08eddc in std::_fl::shared_ptr<impeller::CaptureElement>::~shared_ptr[abi:v15000]() ()

io.flutter.1.raster (26): EXC_BAD_ACCESS (code=257, address=0x2a)

<img width="1290" alt="Screenshot 2024-03-17 at 11 46 31" src="https://github.com/flutter/flutter/assets/53510751/4cce5b07-253f-45bd-835f-5cafb60bac0c">

**Comment by delfme** [comment] 2024-03-17 13:13
Tested on beta 3.20.0-1.1.pre
We have the text transformation issue, but no issue with image transformation and that Impeller error which freezes app.
See vid

https://github.com/flutter/flutter/assets/53510751/66c5440c-f22a-45ce-a51f-d0af4b874b24

**Comment by delfme** [comment] 2024-03-17 14:39
Another thing I noticed, that might be worth a look, is that with beta 3.20.0-1.1.pre all items but text transform correctly. For example, lets focus on the text of the screen in below video: text is on top of a white rounded rect and this rect transforms correctly. But in the video shared above from master, the round rect is affected by the same transformation issue of the text.

https://github.com/flutter/flutter/assets/53510751/d7a29d14-5825-44f3-8d48-85c09ed6ce38

**Comment by bdero** [comment] 2024-03-18 06:28
@delfme Thanks for the details!

> Also, app crashes pointing to this Impeller issue. The crash doesn't quit the app, but freezes the screen in the sense that UI is unresponsive to any gesture and user is stuck on that very screen, whichever it is when the issue occurs.

This is most likely caused by another patch. The patch I submitted was shader-only and shouldn't trigger an access violation. Would you mind placing a separate issue in the tracker for that?

As for [this UV warping issue](https://github.com/flutter/flutter/issues/144333#issuecomment-2002399870), that's definitely caused by the [patch I landed](https://github.com/flutter/engine/pull/51343). I forgot about the rasterizer using z+w to perform perspective correction for attributes passed to the fragment shader...

I have some ideas about fixing this new issue and can take a closer look when I'm back in the office on March 25th. One of the challenges here is the depth ranges each draw gets are very small, so the projection will end up with huge W coordinates in order to get correct results, which may in turn cause precision issues. So we may end up needing to leave a bit more space for draws that use perspective transforms.

**Comment by delfme** [comment] 2024-03-18 13:56
@bdero I could place a separate issue but I cannot isolate the issue, so I cannot create a sample.
Can you check if issue is reproducible on other apps you use for internal tests? It seems it occurs during screen transition or animations. Maybe something is wiped out too early and cause BAD ACCESS?
Also, we didn't have the "freezing" issue on recent master (just days or a few weeks ago).

**Comment by delfme** [comment] 2024-03-22 13:04
Hello, can we re-open this issue meantime?
@bdero I will be available for testing during next 3days if you need me on that.

**Comment by bdero** [comment] 2024-03-25 17:25
Reopening this to focus on [this new issue](https://github.com/flutter/flutter/issues/144333#issuecomment-2002399870) specifically.

**Closed** 2024-03-27 17:25 UTC
Labels: c: regression, platform-ios, engine, has reproducible steps, P1, e: impeller, team-engine, triaged-engine, found in release: 3.20

**Comment by delfme** [comment] 2024-03-28 16:06
@bdero thx so much for the fix. Will test it more, but at first glance it looks perfect, see vid below.

Take this opportunity to also mention that Impeller performance on iOS are superb from our internal tests. We can call it "native". As soon as flutter team gets to fix the text/emoji thing (which is sort of flutter's Achille's heel), that would be perfection 👏🚀

https://github.com/flutter/flutter/assets/53510751/ecdc3c91-43e7-452c-925f-71f8d6a56543
