### ISSUE TITLE
Jittery deformation of text when stretching on overscroll

### ISSUE THREAD

**Issue by MaxYablochkin** [flutter/flutter#129528] opened 2023-06-25 22:41 UTC
#91605

https://github.com/flutter/flutter/assets/102767277/f324a57c-ed5c-403a-aedb-99f8fd4c5500

When there's text inside a scrollable that gets stretched to show overscroll, the text suffers from visible deformations with a jittery effect.

(To see the issue, try viewing the video full-screen.)

### Proposal

Is it possible to improve text behavior when stretched via Paragraph?

**Comment by dam-ease** [comment] 2023-06-26 11:43
Hi @MaxYablochkin. Can you please provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces this text deformation?

**Comment by MaxYablochkin** [comment] 2023-06-26 13:57
<summary>Sample Code</summary>
<details>

```
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(useMaterial3: true),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: FilledButton(
          onPressed: () {
            showDialog(
              context: context,
              builder: (context) {
                return Dialog(
                  insetPadding:
                      EdgeInsets.symmetric(horizontal: 40, vertical: 60),
                  child: Column(
                    children: [
                      Row(
                        children: [
                          Padding(
                            padding: EdgeInsets.fromLTRB(25, 20, 0, 15),
                            child: Text(
                              'Title',
                              style: Theme.of(context).textTheme.headlineSmall,
                            ),
                          ),
                        ],
                      ),
                      Divider(height: 0.0),
                      Expanded(
                        child: Scrollable(
                          viewportBuilder: (context, position) {
                            return Scrollbar(
                              child: ListView.builder(
                                itemCount: 150,
                                padding: EdgeInsets.only(left: 25.0),
                                itemBuilder: (context, index) {
                                  return Text('Line $index');
                                },
                              ),
                            );
                          },
                        ),
                      ),
                      Divider(height: 0.0),
                      Padding(
                        padding: EdgeInsets.all(15.0),
                        child: OverflowBar(
                          alignment: MainAxisAlignment.end,
                          spacing: 8,
                          children: [
                            TextButton(
                              onPressed: () {},
                              child: Text('Decline'),
                            ),
                            TextButton(
                              onPressed: () {},
                              child: Text('Accept'),
                            ),
                          ],
                        ),
                      ),
                    ],
                  ),
                );
              },
            );
          },
          child: Text('Open Dialog with Scrollable'),
        ),
      ),
    );
  }
}

```

</details>


<summary>flutter doctor</summary>
<details>

```
[✓] Flutter (Channel master, 3.12.0-10.0.pre.33, on Microsoft Windows [Version 10.0.22621.1848], locale ru-UA)
    • Flutter version 3.12.0-10.0.pre.33 on channel master at C:\Flutter-SDK\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b2e9501317 (22 hours ago), 2023-06-25 11:39:29 -0400
    • Engine revision 593e1d9a9c
    • Dart version 3.1.0 (build 3.1.0-246.0.dev)
    • DevTools version 2.24.0

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at C:\Users\yablo\AppData\Local\Android\sdk
    • Platform android-TiramisuPrivacySandbox, build-tools 32.1.0-rc1
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.5.3)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.5.33516.290
    • Windows 10 SDK version 10.0.22000.0

[✓] Android Studio (version 2022.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)

[✓] IntelliJ IDEA Community Edition (version 2023.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.2.1
    • Flutter plugin version 74.0.4
    • Dart plugin version 231.9161.14

[✓] VS Code (version 1.79.2)
    • VS Code at C:\Users\yablo\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.66.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22621.1848]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 114.0.5735.134
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 114.0.1823.41

[✓] Network resources
    • All expected network resources are available.
```    
    
</details>

**Comment by MaxYablochkin** [comment] 2023-06-26 18:46
@dam-ease 
Example with Recycler View native scrolling, which stretches the text without jitter and text deformation.  It would be very preferable to see this in Flutter.


https://github.com/flutter/flutter/assets/102767277/94e5fcd2-6c19-4261-903a-25ceca5c2c77

**Comment by chinmaygarde** [comment] 2023-08-28 17:51
I think [this is just Material behavior](https://developer.android.com/develop/ui/views/touch-and-input/gestures/scroll#implement-stretch-overscroll). The engine definitely doesn't do anything specific here.

Assigning to the framework team to confirm this is WAI.

**Comment by gnprice** [comment] 2023-08-29 02:40
The stretching itself is certainly WAI, but the bug report here is something else. If you open the original video full size (e.g. with the "full screen" icon in the player GitHub shows for it), there's a pronounced jitter that's visible and definitely isn't intended.

In the video, it's easiest to see the behavior if you focus on the top line or two of text, i.e. the text closest to the edge that's being stretched away from. I think the rest of the text has a similar jittery feeling to it, but it's harder to see there precisely what's happening, because everything not at the very top is (correctly) moving around vertically at the same time as the other effects are happening.

The second video, in a comment, provides a nice contrast of how the intended stretching effect can be done without the jitter (by showing how it's done in a native Android RecyclerView, apparently).

The jitter looks to me like the sort of thing that can be caused by a bad interaction between snapping text to physical pixels on the one hand, and an animation on the other hand. But I don't know what layer in Flutter, if any, might be responsible for snapping text to physical-pixel alignment.

**Comment by gnprice** [comment] 2023-08-29 02:44
(Edited the title and the issue description to hopefully make clearer what the reported problem is.)

**Comment by jonahwilliams** [comment] 2023-08-30 16:35
I believe the issue is that the text stretch is implemented by pushing a transform into the size/layout of the child widgets. This causes the text to be re-laid out and resize, potentially changing shape too. The fix for this should be to instead render the children to a texture and then stretch that texture instead: https://github.com/flutter/flutter/pull/133613

**Closed** 2023-08-31 01:58 UTC
Labels: platform-android, framework, a: typography, has reproducible steps, found in release: 3.10, found in release: 3.12, team-framework, multiteam-retriage-candidate
