### ISSUE TITLE
[tool_crash] FileSystemException: Deletion failed, OS Error: The system cannot find the path specified., errno = 3

### ISSUE THREAD

**Issue by shali2716** [flutter/flutter#138583] opened 2023-11-16 22:58 UTC
## Command
```
flutter pub get
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Deletion failed, OS Error: The system cannot find the path specified.
, errno = 3
```
#0      _Directory._deleteSync (dart:io/directory_impl.dart:193:7)
#1      FileSystemEntity.deleteSync (dart:io/file_system_entity.dart:414:7)
#2      ForwardingFileSystemEntity.deleteSync (package:file/src/forwarding/forwarding_file_system_entity.dart:70:16)
#3      ErrorHandlingDirectory.deleteSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:481:22)
#4      _runSync (package:flutter_tools/src/base/error_handling_io.dart:590:14)
#5      ErrorHandlingDirectory.deleteSync (package:flutter_tools/src/base/error_handling_io.dart:480:12)
#6      _createPlatformPluginSymlinks (package:flutter_tools/src/flutter_plugins.dart:1055:22)
#7      createPluginSymlinks (package:flutter_tools/src/flutter_plugins.dart:991:5)
#8      refreshPluginsList (package:flutter_tools/src/flutter_plugins.dart:1101:5)
<asynchronous suspension>
#9      FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:359:5)
<asynchronous suspension>
#10     PackagesGetCommand.runCommand (package:flutter_tools/src/commands/packages.dart:365:7)
<asynchronous suspension>
#11     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1350:27)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#13     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:348:9)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#16     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:294:5)
```
```
[32m[✓][39m Flutter (Channel stable, 3.16.0, on Microsoft Windows [Version 10.0.22000.2538], locale en-US)
    [32m•[39m Flutter version 3.16.0 on channel stable at C:\src\flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision db7ef5bf9f (27 hours ago), 2023-11-15 11:25:44 -0800
    [32m•[39m Engine revision 74d16627b9
    [32m•[39m Dart version 3.2.0
    [32m•[39m DevTools version 2.28.2

[32m[✓][39m Windows Version (Installed version of Windows is version 10 or higher)

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    [32m•[39m Android SDK at C:\Users\Jayasinghe\AppData\Local\Android\Sdk
    [32m•[39m Platform android-34, build-tools 34.0.0
    [32m•[39m Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[32m[✓][39m Visual Studio - develop Windows apps (Visual Studio Community 2022 17.7.1)
    [32m•[39m Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    [32m•[39m Visual Studio Community 2022 version 17.7.34009.444
    [32m•[39m Windows 10 SDK version 10.0.22621.0

[32m[✓][39m Android Studio (version 2022.3)
    [32m•[39m Android Studio at C:\Program Files\Android\Android Studio
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)

[32m[✓][39m VS Code (version 1.84.2)
    [32m•[39m VS Code at C:\Users\Jayasinghe\AppData\Local\Programs\Microsoft VS Code
    [32m•[39m Flutter extension version 3.76.0

[32m[✓][39m Connected device (3 available)
    [32m•[39m Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22000.2538]
    [32m•[39m Chrome (web)      • chrome  • web-javascript • Google Chrome 119.0.6045.159
    [32m•[39m Edge (web)        • edge    • web-javascript • Microsoft Edge 119.0.2151.58

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[32m•[39m No issues found!

```

## Flutter Application Metadata
**Type**: malformed
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: null
**Creation framework version**: null
### Plugins
file_picker-5.3.3
file_selector_linux-0.9.2
file_selector_macos-0.9.3+1
file_selector_windows-0.9.3
firebase_analytics-10.4.4
firebase_analytics_web-0.5.4+4
firebase_core-2.15.0
firebase_core_web-2.6.0
firebase_crashlytics-3.3.4
firebase_remote_config-4.2.4
firebase_remote_config_web-1.4.4
flutter_plugin_android_lifecycle-2.0.15
fluttertoast-8.2.2
image_picker-1.0.2
image_picker_android-0.8.7+4
image_picker_for_web-3.0.0
image_picker_ios-0.8.8
image_picker_linux-0.2.1
image_picker_macos-0.2.1
image_picker_windows-0.2.1
open_file-3.3.2
path_provider-2.0.15
path_provider_android-2.0.27
path_provider_foundation-2.2.4
path_provider_linux-2.1.11
path_provider_windows-2.1.7
printing-5.11.0
quill_html_editor-2.2.2
share_plus-7.0.2
sqflite-2.3.0
url_launcher_linux-3.0.5
url_launcher_web-2.0.18
url_launcher_windows-3.0.7
webview_flutter-4.2.2
webview_flutter_android-3.9.2
webview_flutter_wkwebview-3.7.2

**Comment by dam-ease** [comment] 2023-11-17 07:25
Closing as a duplicate of https://github.com/flutter/flutter/issues/106953

**Closed by dam-ease** 2023-11-17 07:25 UTC
Labels: in triage
