### ISSUE TITLE
Failed assertion: line 2330 pos 12: '!_debugLocked': I/flutter (18989): is not true.

### ISSUE THREAD

**Issue by amanr11314** [flutter/flutter#50465] opened 2020-02-10 12:01 UTC
```
E/flutter (18989): #0      Element.markNeedsBuild.<anonymous closure> (package:flutter/src/widgets/framework.dart:3896:11)
E/flutter (18989): #1      Element.markNeedsBuild (package:flutter/src/widgets/framework.dart:3911:6)
E/flutter (18989): #2      State.setState (package:flutter/src/widgets/framework.dart:1168:14)
E/flutter (18989): #3      OverlayState.insertAll (package:flutter/src/widgets/overlay.dart:344:5)
E/flutter (18989): #4      OverlayRoute.install (package:flutter/src/widgets/routes.dart:44:24)
E/flutter (18989): #5      TransitionRoute.install (package:flutter/src/widgets/routes.dart:181:11)
E/flutter (18989): #6      ModalRoute.install (package:flutter/src/widgets/routes.dart:959:11)
E/flutter (18989): #7      NavigatorState.push (package:flutter/src/widgets/navigator.dart:1791:11)
E/flutter (18989): #8      Navigator.push (package:flutter/src/widgets/navigator.dart:1121:34)
E/flutter (18989): #9      _LoadingScreenState.getLocationData (package:clima/screens/loading_screen.dart:26:15)
E/flutter (18989): #10     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:45:6)
E/flutter (18989): #11     _LoadingScreenState.getLocationData (package:clima/screens/loading_screen.dart:21:23)
E/flutter (18989): #12     _LoadingScreenState.initState (package:clima/screens/loading_screen.dart:17:5)
E/flutter (18989): #13     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4355:58)
E/flutter (18989): #14     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
E/flutter (18989): #15     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter (18989): #16     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter (18989): #17     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
E/flutter (18989): #18     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter (18989): #19     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter (18989): #20     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
E/flutter (18989): #21     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
E/flutter (18989): #22     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
E/flutter (18989): #23     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
E/flutter (18989): #24     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter (18989): #25     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter (18989): #26     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
E/flutter (18989): #27     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter (18989): #28     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter (18989): #29     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
E/flutter (18989): #30     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter (18989): #31     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter (18989): #32     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
E/flutter (18989): #33     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
E/flutter (18989): #34     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
E/flutter (18989): #35     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4381:11)
E/flutter (18989): #36     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
E/flutter (18989): #37     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter (18989): #38     Element.updateChild (package:flutt
I/flutter (18989): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (18989): The following assertion was thrown building Navigator-[GlobalObjectKey<NavigatorState>
I/flutter (18989): _WidgetsAppState#e88a4](dirty, state: NavigatorState#6c897(tickers: tracking 2 tickers)):
I/flutter (18989): 'package:flutter/src/widgets/navigator.dart': Failed assertion: line 2330 pos 12: '!_debugLocked':
I/flutter (18989): is not true.
I/flutter (18989): 
I/flutter (18989): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (18989): more information in this error message to help you determine and fix the underlying cause.
I/flutter (18989): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (18989):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter (18989): 
I/flutter (18989): The relevant error-causing widget was:
I/flutter (18989):   MaterialApp file:///F:/Flutter%20Bootcamp%202020/Clima/lib/main.dart:9:12
I/flutter (18989): 
I/flutter (18989): When the exception was thrown, this was the stack:
I/flutter (18989): #2      NavigatorState.build (package:flutter/src/widgets/navigator.dart:2330:12)
I/flutter (18989): #3      StatefulElement.build (package:flutter/src/widgets/framework.dart:4334:27)
I/flutter (18989): #4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4223:15)
I/flutter (18989): #5      Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (18989): #6      StatefulElement.update (package:flutter/src/widgets/framework.dart:4413:5)
I/flutter (18989): #7      Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (18989): #8      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (18989): #9      Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (18989): #10     ProxyElement.update (package:flutter/src/widgets/framework.dart:4557:5)
I/flutter (18989): #11     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (18989): #12     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (18989): #13     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (18989): #14     ProxyElement.update (package:flutter/src/widgets/framework.dart:4557:5)
I/flutter (18989): #15     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (18989): #16     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (18989): #17     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (18989): #18     ProxyElement.update (package:flutter/src/widgets/framework.dart:4557:5)
I/flutter (18989): #19     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (18989): #20     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (18989): #21     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (18989): #22     StatelessElement.update (package:flutter/src/widgets/framework.dart:4298:5)
I/flutter (18989): #23     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (18989): #24     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (18989): #25     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (18989): #26     ProxyElement.update (package:flutter/src/widgets/framework.dart:4557:5)
I/flutter (18989): #27     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (18989): #28     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (18989): #29     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (18989): #30     StatelessElement.update (package:flutter/src/widgets/framework.dart:4298:5)
I/flutter (18989): #31     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (18989): #32     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (18989): #33     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (18989): #34     StatefulElement.update (package:flutter/src/widgets/framework.dart:4413:5)
I/flutter (18989): #35     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (18989): #36     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (18989): #37     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (18989): #38     StatelessElement.update (package:flutter/src/widgets/framework.dart:4298:5)
I/flutter (18989): #39     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (18989): #40     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (18989): #41     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (18989): #42     ProxyElement.update (package:flutter/src/widgets/framework.dart:4557:5)
I/flutter (18989): #43     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (18989): #44     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (18989): #45     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (18989): #46     StatelessElement.update (package:flutter/src/widgets/framework.dart:4298:5)
I/flutter (18989): #47     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (18989): #48     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (18989): #49     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (18989): #50     ProxyElement.update (package:flutter/src/widgets/framework.dart:4557:5)
I/flutter (18989): #51     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (18989): #52     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (18989): #53     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (18989): #54     ProxyElement.update (package:flutter/src/widgets/framework.dart:4557:5)
I/flutter (18989): #55     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (18989): #56     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
I/flutter (18989): #57     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (18989): #58     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (18989): #59     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (18989): #60     StatefulElement.update (package:flutter/src/widgets/framework.dart:4413:5)
I/flutter (18989): #61     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (18989): #62     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (18989): #63     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (18989): #64     ProxyElement.update (package:flutter/src/widgets/framework.dart:4557:5)
I/flutter (18989): #65     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (18989): #66     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (18989): #67     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (18989): #68     StatefulElement.update (package:flutter/src/widgets/framework.dart:4413:5)
I/flutter (18989): #69     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (18989): #70     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (18989): #71     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (18989): #72     ProxyElement.update (package:flutter/src/widgets/framework.dart:4557:5)
I/flutter (18989): #73     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (18989): #74     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (18989): #75     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (18989): #76     ProxyElement.update (package:flutter/src/widgets/framework.dart:4557:5)
I/flutter (18989): #77     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (18989): #78     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (18989): #79     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (18989): #80     ProxyElement.update (package:flutter/src/widgets/framework.dart:4557:5)
I/flutter (18989): #81     _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:94:11)
I/flutter (18989): #82     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (18989): #83     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
I/flutter (18989): #84     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (18989): #85     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (18989): #86     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (18989): #87     ProxyElement.update (package:flutter/src/widgets/framework.dart:4557:5)
I/flutter (18989): #88     _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:94:11)
I/flutter (18989): #89     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (18989): #90     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (18989): #91     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (18989): #92     StatefulElement.update (package:flutter/src/widgets/framework.dart:4413:5)
I/flutter (18989): #93     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (18989): #94     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (18989): #95     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (18989): #96     StatefulElement.update (package:flutter/src/widgets/framework.dart:4413:5)
I/flutter (18989): #97     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (18989): #98     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (18989): #99     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (18989): #100    StatefulElement.update (package:flutter/src/widgets/framework.dart:4413:5)
I/flutter (18989): #101    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (18989): #102    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (18989): #103    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (18989): #104    ProxyElement.update (package:flutter/src/widgets/framework.dart:4557:5)
I/flutter (18989): #105    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (18989): #106    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (18989): #107    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (18989): #108    StatefulElement.update (package:flutter/src/widgets/framework.dart:4413:5)
I/flutter (18989): #109    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (18989): #110    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (18989): #111    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (18989): #112    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2432:33)
I/flutter (18989): #113    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:773:20)
I/flutter (18989): #114    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:283:5)
I/flutter (18989): #115    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1102:15)
I/flutter (18989): #116    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1041:9)
I/flutter (18989): #117    SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:850:7)
I/flutter (18989): #119    _Timer._runTimers (dart:isolate-patch/timer_impl.dart:384:19)
I/flutter (18989): #120    _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:418:5)
I/flutter (18989): #121    _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
I/flutter (18989): (elided 3 frames from class _AssertionError and package dart:async-patch)
I/flutter (18989): 
I/flutter (18989): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by amanr11314** [comment] 2020-02-10 12:03
Please help me i'm new to flutter

**Comment by TahaTesser** [comment] 2020-02-10 12:19
Hi @amanr11314 
Can you please provide your `flutter doctor -v` and `flutter run --verbose`?
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem 
Thank you

**Comment by VladyslavBondarenko** [comment] 2020-03-05 16:16
@amanr11314 
Since additional information isn't provided, closing as duplicate of https://github.com/flutter/flutter/issues/49779
if you disagree please write in the comments and I will reopen it

**Closed by VladyslavBondarenko** 2020-03-05 16:16 UTC
Labels: waiting for customer response

**Comment by irfanismaya20** [comment] 2020-03-28 18:21
I call Navigator.pop(context) and result Failed assertion: line 2113 pos 12: '!_debugLocked': is not true.

**Comment by ZubairAfzalMughal** [comment] 2020-04-12 17:11
void initState() {
    getNextPage();
    super.initState();
  }
  void getNextPage() async{
    Navigator.push(context, MaterialPageRoute(builder: (context){
      return Main();
    }));
  }
......
I am justing building my Loading page and wanted to move next page...
But I have an Error


Failed assertion: line 2330 pos 12: '!_debugLocked': is not true.

**Comment by jeanadam** [comment] 2020-05-06 01:38
I am also having this message when I call  Navigator.popUntil(context,
                                      ModalRoute.withName(MainScreen.Id)); and the result is Failed assertion: line 2113 pos 12: '!_debugLocked': is not true. This error message is just plain awful. It seems that navigator is having trouble keeping context of screens and delivering a proper message when it is out of control.

**Comment by VladyslavBondarenko** [comment] 2020-05-06 09:27
@ZubairAfzalMughal follow up on https://github.com/flutter/flutter/issues/36177

@jeanadam 
try https://github.com/flutter/flutter/issues/16602#issuecomment-407916243
