### ISSUE TITLE
Flutter Material TimePicker numeric keyboard not closing the dialog when pressing confirm.

### ISSUE THREAD

**Issue by itaiarbel** [flutter/flutter#107907] opened 2022-07-19 07:22 UTC
Hello, I have encounter a problem with the inline numeric keyboard and the TimePicker,
- when manually entering the time using the keyboard, the confirm button (check mark button) not working (it doe's nothing but vibrate, not confirming / not closing the picker).

Screenshots on how to reproduce the problem:
![timepicker-keyboard-bug](https://user-images.githubusercontent.com/4608663/179689867-5e6ffa63-85af-4c8f-ad18-e2594121bdd1.jpg)

Flutter:  3.0.5
Phone: Xiaomi Redmi Note 10 Pro

This is my code to display the picker,
>   _selectTime(BuildContext context) async {
    final TimeOfDay? timeOfDay = await showTimePicker(
      context: context,
      initialTime: selectedTime,
      initialEntryMode: TimePickerEntryMode.dial,
    );
    if (timeOfDay != null && timeOfDay != selectedTime) {
      setState(() {
        selectedTime = timeOfDay;
        updateData();
      });
    }
  }

Can someone please confirm that that bug exists all\other devices?
This is a major UX problem with the pimepicker and need to be fixed in the TimePicker code...

Thanks.

**Comment by itaiarbel** [comment] 2022-07-19 08:32
Note: Also the DatePicker keyboard confirm DO closes the keyboard,  
The problem exists only in the TimePicker Numeric keyboard....

**Comment by TahaTesser** [comment] 2022-07-19 11:30
duplicate of https://github.com/flutter/flutter/issues/68249

**Closed by TahaTesser** 2022-07-19 11:30 UTC
Labels: r: duplicate
