### ISSUE TITLE
http response does not return cookies.

### ISSUE THREAD

**Issue by chitgoks** [flutter/flutter#60281] opened 2020-06-25 13:33 UTC
this is a question in case there is something going on with http response in flutter web.

the response does not return any cookie in response header.

it works if i run it in android but when i converted it to flutter web only content length and content type are available in the response header.

is there something that needs to be done perhaps in the flutter code for web?

backend is expressjs and tried cookie  httpOnly true and false, even secure set as false but same result.

thoughts?

**Comment by TahaTesser** [comment] 2020-06-25 14:51
Hi @chitgoks 
Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by chitgoks** [comment] 2020-06-26 01:46
[√] Flutter (Channel beta, 1.19.0-4.2.pre, on Microsoft Windows [Version 10.0.18363.900], locale en-US)
    • Flutter version 1.19.0-4.2.pre at c:\flutter
    • Framework revision 9b9b543d92 (3 days ago), 2020-06-22 12:19:28 -0700
    • Engine revision 9a28c3bcf4
    • Dart version 2.9.0 (build 2.9.0-14.1.beta)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\chitg\AppData\Local\Android\Sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = C:\Users\chitg\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[!] VS Code, 64-bit edition (version 1.46.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (2 available)
    • Web Server • web-server • web-javascript • Flutter Tools
    • Chrome     • chrome     • web-javascript • Google Chrome 83.0.4103.116

! Doctor found issues in 1 category.

**Comment by chitgoks** [comment] 2020-06-26 01:51
This is the command i use flutter run -d web-server --web-port 7357 but adding --verbose to it errors out.

Here is the code to fetch the request

```
static Future<http.Response> login(Map<String, dynamic> data) async {
  http.post('$url/api/users/login', body: { 'email': 'test@test.com');
}
```

Then I do

```
http.Response res = await Web.login(user.toJson());
print(res.headers);
```

Only content-length and content-type are shown in Flutter Web. If in Mobile, the Set-Cookie response header is available. Also tried to access the same URL using Javascript AJAX code, it works fine.

**Comment by chitgoks** [comment] 2020-06-26 02:03
Thing is, i checked the network tab in dev console. the response header has set-cookie in it. but the res.headers in dart code does not show any.

**Comment by TahaTesser** [comment] 2020-06-26 05:41
Hi @chitgoks 
From what i can see it seems like http thing

From what I can see, the issue is related to a 3rd party plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/dart-lang/http/issues).
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments, possibly providing a minimal reproducible code sample that does not use 3rd party plugins, and I will reopen it.
Thank you

**Closed by TahaTesser** 2020-06-26 05:41 UTC
Labels: in triage

**Comment by chitgoks** [comment] 2020-06-26 05:59
actually its the same thing with httpclient

i tried the internal class too. ill post screenshot
