### ISSUE TITLE
flutter run -d linux fails on Flutter 1.27.0-1.0.pre

### ISSUE THREAD

**Issue by domesticmouse** [flutter/flutter#76089] opened 2021-02-16 04:49 UTC
## Steps to Reproduce

1. Run `flutter create bug`.
2. Run `flutter run -d linux` 

**Expected results:** 

Running desktop Linux app

**Actual results:** 

```
Launching lib/main.dart on Linux in debug mode...
CMake Error at cmake_install.cmake:61 (file):                           
  file INSTALL cannot copy file                                         
  "/home/brett/flutter-projects/desktop_thingey/build/linux/debug/intermediates_do_not_run/desktop_thingey"
  to "/usr/local/desktop_thingey": Permission denied.                   

Building Linux application...                                           
Exception: Build process failed
```

<details>
  <summary>Logs</summary>

```
$ flutter run -d linux --verbose
[  +98 ms] executing: [/home/brett/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +41 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 68c96f100e42ab3dbf43e61e9e2fc875a2d50cb8
[   +1 ms] executing: [/home/brett/flutter/] git tag --points-at 68c96f100e42ab3dbf43e61e9e2fc875a2d50cb8
[  +19 ms] Exit code 0 from: git tag --points-at 68c96f100e42ab3dbf43e61e9e2fc875a2d50cb8
[        ] 1.27.0-1.0.pre
[  +63 ms] executing: [/home/brett/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +7 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/dev
[        ] executing: [/home/brett/flutter/] git ls-remote --get-url origin
[   +7 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +58 ms] Unable to locate an Android SDK.
[   +7 ms] executing: [/home/brett/flutter/] git rev-parse --abbrev-ref HEAD
[   +7 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] dev
[ +101 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +5 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +103 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +97 ms] Skipping pub get: version match.
[ +221 ms] Initializing file store
[  +12 ms] Skipping target: gen_localizations
[   +9 ms] complete
[   +5 ms] Launching lib/main.dart on Linux in debug mode...
[   +6 ms] /home/brett/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev /home/brett/flutter/bin/cache/artifacts/engine/linux-x64/frontend_server.dart.snapshot
--sdk-root /home/brett/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names
--experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true --output-dill /tmp/flutter_tools.IKPOFX/flutter_tool.ALXYBF/app.dill --packages
/home/brett/flutter-projects/desktop_thingey/.dart_tool/package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation
--filesystem-scheme org-dartlang-root --initialize-from-dill build/c075001b96339384a97db4862b8ab8db.cache.dill.track.dill
[  +41 ms] Building Linux application...
[  +35 ms] <- compile package:desktop_thingey/main.dart
[   +3 ms] executing: [build/linux/debug/] cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug /home/brett/flutter-projects/desktop_thingey/linux
[ +108 ms] -- Configuring done
[   +7 ms] -- Generating done
[   +8 ms] -- Build files have been written to: /home/brett/flutter-projects/desktop_thingey/build/linux/debug
[  +15 ms] executing: ninja -C build/linux/debug install
[  +15 ms] ninja: Entering directory `build/linux/debug'
[+6193 ms] [1/5] Generating /home/brett/flutter-projects/desktop_thingey/linux/flutter/ephemeral/libflutter_linux_gtk.so,
/home/brett/flutter-projects/desktop_thingey/linux/flutter/ephemeral/flutter_linux/fl_basic_message_channel.h,
/home/brett/flutter-projects/desktop_thingey/linux/flutter/ephemeral/flutter_linux/fl_binary_codec.h,
/home/brett/flutter-projects/desktop_thingey/linux/flutter/ephemeral/flutter_linux/fl_binary_messenger.h,
/home/brett/flutter-projects/desktop_thingey/linux/flutter/ephemeral/flutter_linux/fl_dart_project.h,
/home/brett/flutter-projects/desktop_thingey/linux/flutter/ephemeral/flutter_linux/fl_engine.h,
/home/brett/flutter-projects/desktop_thingey/linux/flutter/ephemeral/flutter_linux/fl_json_message_codec.h,
/home/brett/flutter-projects/desktop_thingey/linux/flutter/ephemeral/flutter_linux/fl_json_method_codec.h,
/home/brett/flutter-projects/desktop_thingey/linux/flutter/ephemeral/flutter_linux/fl_message_codec.h,
/home/brett/flutter-projects/desktop_thingey/linux/flutter/ephemeral/flutter_linux/fl_method_call.h,
/home/brett/flutter-projects/desktop_thingey/linux/flutter/ephemeral/flutter_linux/fl_method_channel.h,
/home/brett/flutter-projects/desktop_thingey/linux/flutter/ephemeral/flutter_linux/fl_method_codec.h,
/home/brett/flutter-projects/desktop_thingey/linux/flutter/ephemeral/flutter_linux/fl_method_response.h,
/home/brett/flutter-projects/desktop_thingey/linux/flutter/ephemeral/flutter_linux/fl_plugin_registrar.h,
/home/brett/flutter-projects/desktop_thingey/linux/flutter/ephemeral/flutter_linux/fl_plugin_registry.h,
/home/brett/flutter-projects/desktop_thingey/linux/flutter/ephemeral/flutter_linux/fl_standard_message_codec.h,
/home/brett/flutter-projects/desktop_thingey/linux/flutter/ephemeral/flutter_linux/fl_standard_method_codec.h,
/home/brett/flutter-projects/desktop_thingey/linux/flutter/ephemeral/flutter_linux/fl_string_codec.h,
/home/brett/flutter-projects/desktop_thingey/linux/flutter/ephemeral/flutter_linux/fl_value.h,
/home/brett/flutter-projects/desktop_thingey/linux/flutter/ephemeral/flutter_linux/fl_view.h,
/home/brett/flutter-projects/desktop_thingey/linux/flutter/ephemeral/flutter_linux/flutter_linux.h, _phony_
[  +28 ms] [ +150 ms] executing: [/home/brett/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] [  +59 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] [        ] 68c96f100e42ab3dbf43e61e9e2fc875a2d50cb8
[        ] [        ] executing: [/home/brett/flutter/] git tag --points-at 68c96f100e42ab3dbf43e61e9e2fc875a2d50cb8
[        ] [  +18 ms] Exit code 0 from: git tag --points-at 68c96f100e42ab3dbf43e61e9e2fc875a2d50cb8
[        ] [        ] 1.27.0-1.0.pre
[        ] [  +71 ms] executing: [/home/brett/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[        ] [   +8 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] [        ] origin/dev
[        ] [        ] executing: [/home/brett/flutter/] git ls-remote --get-url origin
[        ] [   +7 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] [        ] https://github.com/flutter/flutter.git
[        ] [  +70 ms] Unable to locate an Android SDK.
[        ] [   +9 ms] executing: [/home/brett/flutter/] git rev-parse --abbrev-ref HEAD
[        ] [   +8 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] [        ] dev
[        ] [ +125 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [   +5 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [ +128 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[   +4 ms] [        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +4 ms] [        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[        ] [ +110 ms] Initializing file store
[        ] [  +13 ms] Done initializing file store
[        ] [  +66 ms] Skipping target: gen_localizations
[        ] [+2743 ms] Skipping target: unpack_linux
[        ] [ +647 ms] Skipping target: kernel_snapshot
[        ] [ +533 ms] Skipping target: debug_bundle_linux_assets
[        ] [   +1 ms] Persisting file store
[        ] [  +19 ms] Done persisting file store
[        ] [  +10 ms] build succeeded.
[        ] [  +17 ms] "flutter assemble" took 4,341ms.
[        ] [ +262 ms] ensureAnalyticsSent: 255ms
[        ] [   +2 ms] Running shutdown hooks
[        ] [        ] Shutdown hooks complete
[        ] [        ] exiting with code 0
[+1015 ms] [2/5] Building CXX object CMakeFiles/desktop_thingey.dir/flutter/generated_plugin_registrant.cc.o
[  +71 ms] [3/5] Building CXX object CMakeFiles/desktop_thingey.dir/my_application.cc.o
[ +231 ms] [4/5] Linking CXX executable intermediates_do_not_run/desktop_thingey
[        ] [4/5] Install the project...
[  +13 ms] -- Install configuration: "Debug"
[        ] -- Installing: /usr/local/desktop_thingey
[        ] CMake Error at cmake_install.cmake:61 (file):
[   +3 ms]   file INSTALL cannot copy file
[        ]   "/home/brett/flutter-projects/desktop_thingey/build/linux/debug/intermediates_do_not_run/desktop_thingey"
[        ]   to "/usr/local/desktop_thingey": Permission denied.
[   +1 ms] FAILED: CMakeFiles/install.util 
[        ] cd /home/brett/flutter-projects/desktop_thingey/build/linux/debug && /usr/bin/cmake -P cmake_install.cmake
[        ] ninja: build stopped: subcommand failed.
[  +20 ms] Building Linux application... (completed in 7.8s)
[+6440 ms] Exception: Build process failed
[   +3 ms] "flutter run" took 14,804ms.
[   +7 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:12:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:647:9)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1174:12)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1026:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:152:19)
           <asynchronous suspension>
           #5      AppContext.run (package:flutter_tools/src/base/context.dart:151:12)
           <asynchronous suspension>
           #6      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:280:9)
           <asynchronous suspension>
           #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:152:19)
           <asynchronous suspension>
           #9      AppContext.run (package:flutter_tools/src/base/context.dart:151:12)
           <asynchronous suspension>
           #10     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
           <asynchronous suspension>
           #11     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:66:9)
           <asynchronous suspension>
           #12     run.<anonymous closure> (package:flutter_tools/runner.dart:64:12)
           <asynchronous suspension>
           #13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:152:19)
           <asynchronous suspension>
           #14     AppContext.run (package:flutter_tools/src/base/context.dart:151:12)
           <asynchronous suspension>
           #15     runInContext (package:flutter_tools/src/context_runner.dart:75:10)
           <asynchronous suspension>
           #16     main (package:flutter_tools/executable.dart:92:3)
           <asynchronous suspension>
           
           
[ +105 ms] ensureAnalyticsSent: 103ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hook priority 4
[   +5 ms] Shutdown hooks complete
[        ] exiting with code 1
```

```
$ flutter analyze
Analyzing desktop_thingey...                                            
No issues found! (ran in 2.0s)
```

```
$ flutter doctor -v
[✓] Flutter (Channel dev, 1.27.0-1.0.pre, on Linux, locale en_AU.UTF-8)
    • Flutter version 1.27.0-1.0.pre at /home/brett/flutter
    • Framework revision 68c96f100e (7 days ago), 2021-02-08 16:14:15 -0800
    • Engine revision b04955656c
    • Dart version 2.13.0 (build 2.13.0-0.0.dev)

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Linux
    • Chrome (web)    • chrome • web-javascript • Google Chrome 88.0.4324.150

! Doctor found issues in 2 categories.
```

</details>

**Comment by stuartmorgan** [comment] 2021-02-16 11:49
I hate this bug :/ It's a duplicate of https://github.com/flutter/flutter/issues/59890 and some others; see my comment at https://github.com/flutter/flutter/issues/73881#issuecomment-760216098

Can you currently repro this every time you make s new project?

**Comment by domesticmouse** [comment] 2021-02-16 22:36
@stuartmorgan Nope, my just created project works fine. Argh. Closing to de-dupe

**Comment by stuartmorgan** [comment] 2021-02-17 00:04
Drat. I was hoping we finally had a case we could catch in the act of writing the wrong scripts.

**Comment by gspencergoog** [comment] 2021-02-18 19:17
Closing to de-dupe it again. :-)

**Closed by gspencergoog** 2021-02-18 19:17 UTC
Labels: a: desktop, passed first triage, platform-linux, severe: crash, tool
