### ISSUE TITLE
BoxDecoration Failed assertion

### ISSUE THREAD

**Issue by larteagar** [flutter/flutter#90761] opened 2021-09-26 14:21 UTC
```console
package:flutter/src/painting/box_decoration.dart'
: Failed assertion: line 131 pos 12: 'shape != BoxShape.circle || borderRadius == null': is not true.
```

```dart
BoxDecoration(
     shape: BoxShape.rectangle,
    color: Colors.blue,
    borderRadius: BorderRadius.circular(8)
)
```

**Comment by Vardiak** [comment] 2021-09-26 16:44
Settings the shape to rectangle with a border radius makes no sense. You should read the error more carefully: remove the shape property and everything will work fine.

**Comment by larteagar** [comment] 2021-09-26 17:55
Hi Vardiak, thank you for your reply. Look at the documentation it says otherwise,

{BorderRadiusGeometry? borderRadius}
If non-null, the corners of this box are rounded by this [BorderRadius].

Applies only to boxes with rectangular shapes; ignored if [shape] is not [BoxShape.rectangle].


How do you get a rectangular box with rounded edges like the icons in iOS?

BoxDecoration(
                    color: Colors.blue,
                    borderRadius: BorderRadius.all(Radius.circular(12))
)

This is not correct ?

Thanks

**Comment by maheshmnj** [comment] 2021-09-27 10:42
Hi @larteagar, Thanks for filing the issue, This is working as intended you cannot provide both circular shape and BorderRadius, As having borderRadius to a circle doesn't make sense, Thats why the assertion error or this is also mentioned in the [docs](https://api.flutter.dev/flutter/painting/BoxDecoration/borderRadius.html).  


> How do you get a rectangular box with rounded edges like the icons in iOS?
> 
BoxDecoration(
    color: Colors.blue,
    borderRadius: BorderRadius.all(Radius.circular(12))
)

This should be fine and give you the desired result with appropriate `BorderRadius`.

Closing this issue, Since it is working as intended. If you need further help please try asking such Questions on communities like StackOverflow.

Thanks

**Closed by maheshmnj** 2021-09-27 10:42 UTC
Labels: in triage
