### ISSUE TITLE
[google_maps_flutter] Marker/cameraPosition is not visible with smaller height

### ISSUE THREAD

**Issue by YAPPDEF** [flutter/flutter#26695] opened 2019-01-17 07:52 UTC
I have set a cameraPosition and an additional marker (same coordinates).
If the surrounding Container is "too small", they are not visible/centered.

Please fix, that the current position is always centered.
_I also tried adding ` trackCameraPosition: true` - did not work_

**Example:**
```dart
return Container(
  height: 300.0,
  width: double.infinity, // screen width
  child: GoogleMap(
    onMapCreated: (GoogleMapController controller) {
      controller.addMarker(MarkerOptions(
        position: LatLng(place.lat, place.long),
      ));
    },
    options: GoogleMapOptions(
      cameraPosition: CameraPosition(
        target: LatLng(place.lat, place.long),
        zoom: 18.0,
      ),
    ),
  ),
)
```

**Output:**
![bildschirmfoto 2019-01-17 um 08 44 31](https://user-images.githubusercontent.com/40127061/51303094-96ac3300-1a34-11e9-82eb-e65e156c91bf.png)
This is somewhere below the actual position..?

If I change the **height** of the container to **350**, then the currentPosition and marker are visible:
![bildschirmfoto 2019-01-17 um 08 45 02](https://user-images.githubusercontent.com/40127061/51303101-990e8d00-1a34-11e9-9ccc-422bd9be1b84.png)

_Version: google_maps_flutter: ^0.0.3+3_

**Comment by sindejr** [comment] 2019-01-20 17:05
Try to set trackCameraPosition: true,
`options: GoogleMapOptions(
     trackCameraPosition: true,
      cameraPosition: CameraPosition(
        target: LatLng(place.lat, place.long),
        zoom: 18.0,
      ),
    ),`

**Comment by TahaTesser** [comment] 2021-04-21 12:37
Hi @YAPPDEF 
This seems to be fixed, I cannot reproduce the issue with container 300 height or even lower

<img src="https://user-images.githubusercontent.com/48603081/115554566-44af8300-a2b7-11eb-96d3-5cf324d7c1de.png" height="450" />


<details> 
<summary>code sample</summary> 

```dart
import 'dart:async';

import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Google Maps Demo',
      home: MapSample(),
    );
  }
}

class MapSample extends StatefulWidget {
  @override
  State<MapSample> createState() => MapSampleState();
}

class MapSampleState extends State<MapSample> {
  Completer<GoogleMapController> _controller = Completer();

  static final CameraPosition _kGooglePlex = CameraPosition(
    target: LatLng(37.42796133580664, -122.085749655962),
    zoom: 14.4746,
  );

  static final CameraPosition _kLake = CameraPosition(
      bearing: 192.8334901395799,
      target: LatLng(37.43296265331129, -122.08832357078792),
      tilt: 59.440717697143555,
      zoom: 18);

  Map<MarkerId, Marker> markers =
      <MarkerId, Marker>{}; // CLASS MEMBER, MAP OF MARKS

  void _add() {
    var markerIdVal = 'marker_';
    final MarkerId markerId = MarkerId(markerIdVal);

    // creating a new MARKER
    final Marker marker = Marker(
      markerId: markerId,
      position: LatLng(37.43296265331129, -122.08832357078792),
      infoWindow: InfoWindow(title: markerIdVal, snippet: '*'),
      onTap: () {},
    );

    setState(() {
      // adding a new marker to map
      markers[markerId] = marker;
    });
  }

  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      body: Center(
        child: Container(
          height: 100,
          child: GoogleMap(
            mapType: MapType.hybrid,
            initialCameraPosition: _kGooglePlex,
            onMapCreated: (GoogleMapController controller) {
              _controller.complete(controller);
            },
            markers: Set<Marker>.of(markers.values), // YOUR MARKS IN MAP
          ),
        ),
      ),
      floatingActionButton: FloatingActionButton.extended(
        onPressed: _goToTheLake,
        label: Text('Add marker'),
        icon: Icon(Icons.directions_boat),
      ),
    );
  }

  Future<void> _goToTheLake() async {
    _add();
  }
}

``` 

</details>

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 2.0.5, on macOS 11.2.3 20D91 darwin-x64, locale
    en-GB)
    • Flutter version 2.0.5 at /Users/tahatesser/Code/flutter_stable
    • Framework revision adc687823a (5 days ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (3 available)
    • iPhone 12 (mobile) • 83060656-28E7-44CD-801E-B11EC3EC89BA • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • macOS (desktop)    • macos                                • darwin-x64
      • macOS 11.2.3 20D91 darwin-x64
    • Chrome (web)       • chrome                               • web-javascript
      • Google Chrome 89.0.4389.128

• No issues found!
```
	
</details>

Closing, as fixed. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-04-21 12:37 UTC
Labels: P4, p: first party, p: maps, plugin
