### ISSUE TITLE
[tool_crash] ProcessException: The process cannot access the file because it is being used by another process. Command: "D:\Program Files\Git\cmd\git.EXE", OS error code: 32

### ISSUE THREAD

**Issue by wilsonmutsago** [flutter/flutter#150265] opened 2024-06-14 15:35 UTC
## Command
```
flutter run --machine --start-paused -d RFCN201L7YN --devtools-server-address http://127.0.0.1:9100/ --target lib\main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ProcessException: The process cannot access the file because it is being used by another process.
 Command: "D:\Program Files\Git\cmd\git.EXE", OS error code: 32
```
#0      LocalProcessManager.runSync (package:process/src/interface/local_process_manager.dart:118:7)
#1      ErrorHandlingProcessManager.runSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:718:24)
#2      _runSync (package:flutter_tools/src/base/error_handling_io.dart:600:14)
#3      ErrorHandlingProcessManager.runSync (package:flutter_tools/src/base/error_handling_io.dart:717:12)
#4      _DefaultProcessUtils.runSync (package:flutter_tools/src/base/process.dart:376:51)
#5      _runGit (package:flutter_tools/src/version.dart:623:23)
#6      FlutterVersion.channel (package:flutter_tools/src/version.dart:122:26)
#7      FlutterVersion.checkFlutterVersionFreshness (package:flutter_tools/src/version.dart:246:37)
#8      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:255:40)
<asynchronous suspension>
#9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#10     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
<asynchronous suspension>
#11     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#13     main (package:flutter_tools/executable.dart:91:3)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 3.7.12, on Microsoft Windows [Version 10.0.19045.4291], locale en-ZW)
    • Flutter version 3.7.12 on channel stable at D:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4d9e56e694 (1 year, 2 months ago), 2023-04-17 21:47:46 -0400
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at D:\wilso\AppData\Local
    • Platform android-33, build-tools 33.0.2
    • Java binary at: D:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at D:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Build Tools 2019 16.11.26)
    • Visual Studio at D:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
    • Visual Studio Build Tools 2019 version 16.11.33529.622
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 2022.2)
    • Android Studio at D:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)

[✓] Connected device (4 available)
    • SM G981U (mobile) • RFCN201L7YN • android-arm64  • Android 13 (API 33)
    • Windows (desktop) • windows     • windows-x64    • Microsoft Windows [Version 10.0.19045.4291]
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 125.0.6422.142
    • Edge (web)        • edge        • web-javascript • Microsoft Edge 121.0.2277.106

[!] HTTP Host Availability
    ✗ HTTP host "https://cocoapods.org/" is not reachable. Reason: An error occurred while checking the HTTP host: Failed host lookup: 'cocoapods.org'
    ✗ HTTP host "https://maven.google.com/" is not reachable. Reason: An error occurred while checking the HTTP host: Failed host lookup: 'maven.google.com'
    ✗ HTTP host "https://pub.dev/" is not reachable. Reason: An error occurred while checking the HTTP host: The semaphore timeout period has expired.

    ✗ HTTP host "https://cloud.google.com/" is not reachable. Reason: An error occurred while checking the HTTP host: Failed host lookup: 'cloud.google.com'

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 2.0.0+19
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: f1875d570e39de09040c8f79aa13cc56baab8db1
### Plugins
cloud_firestore-4.12.2
cloud_firestore_web-3.8.3
firebase_analytics-10.8.0
firebase_analytics_web-0.5.5+12
firebase_auth-4.12.1
firebase_auth_web-5.8.6
firebase_core-2.24.2
firebase_core_web-2.10.0
path_provider-2.1.1
path_provider_android-2.2.1
path_provider_foundation-2.3.1
path_provider_linux-2.2.1
path_provider_windows-2.2.1
purchases_flutter-6.21.0
url_launcher-6.1.11
url_launcher_android-6.2.0
url_launcher_ios-6.2.0
url_launcher_linux-3.1.0
url_launcher_macos-3.1.0
url_launcher_web-2.0.19
url_launcher_windows-3.1.0
webview_flutter-3.0.4
webview_flutter_android-2.10.4
webview_flutter_wkwebview-2.9.5

**Comment by huycozy** [comment] 2024-06-17 06:07
This seems to happen when you execute git commands simultaneously in another terminal (there was a similar case at https://github.com/flutter/flutter/issues/58410).

I will close this as this is working as intended. If it's not your case, please write in comments and I will reopen this. Thanks!

**Closed by huycozy** 2024-06-17 06:07 UTC
Labels: in triage
