### ISSUE TITLE
Widget rebuild getting ModalMoute args when DrawerMenu is opening

### ISSUE THREAD

**Issue by alexgrek96** [flutter/flutter#35575] opened 2019-07-04 05:45 UTC
Hello, help me please. When i navigate to the route using pushNamed and send arguments, my modal route rebuilds if i call  ModalRoute.of(context).settings.arguments inside build method.

Short code example

```
class Example extends StatelessWidget {

  String type;
  static const routeName = '/';

  Example();

  @override
  Widget build(BuildContext context) {
    print("rebuild_log");

    type = ModalRoute.of(context).settings.arguments; // (1)

    return Scaffold(
        appBar: AppBar(
            title: Text("type"),
            centerTitle: true),
        drawer: Drawer(child: Container()),
        body: _Body());
  }
}
```

But if i remove line // (1) all is ok. Widget doesn't rebuild when drawer open.

Start point:

```
void main() => runApp(App());
```

And App class

```
class App extends StatelessWidget {
  @override
  Widget build(BuildContext context) => MaterialApp(
        theme: ThemeData(primaryColor: primaryThemeColor),
        initialRoute: Example.routeName,
        routes: {
          Example.routeName : (context) => Example(),
        },
      );
}
```

Log
```
I/flutter ( 8276): rebuild_log
I/flutter ( 8276): rebuild_log
I/flutter ( 8276): rebuild_log
I/flutter ( 8276): rebuild_log
```

If i use onGenerateRoute to send param into constructor and remove ModalRoute.of(context).settings.arguments all is ok 

Flutter Doctor:
```
[√] Flutter (Channel stable, v1.5.4-hotfix.2, on Microsoft Windows [Version 10.0.17134.829], locale ru-RU)
    • Flutter version 1.5.4-hotfix.2 at C:\flutter
    • Framework revision 7a4c33425d (9 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at H:\AndroidSDK
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = H:\AndroidSDK
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 36.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[!] IntelliJ IDEA Ultimate Edition (version 2019.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2019.1
    X Flutter plugin not installed; this adds Flutter specific functionality.
    • Dart plugin version 191.6183.88
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)
```

**Comment by BondarenkoStas** [comment] 2019-10-01 12:21
@alexgrek96 Is it the same while using the current flutter stable v1.9.1+hotfix.2?

**Comment by iapicca** [comment] 2019-11-08 15:53
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.

**Closed by iapicca** 2019-11-08 15:53 UTC
Labels: framework, waiting for customer response

**Comment by drriguz** [comment] 2020-07-13 11:27
Exactly the same issue here, my scenario is that I'll get an object ID from `ModalRoute.of(context).settings.arguments;`in the detail page after the user clicks an item in the list page,  and inside this detail page, there is a button to remove the data with this ID and then pop to the list page.

However because soon after the detail page is popped, it will be rebuilt, but at this moment the date with the same ID is already removed, so there might be some problem if we don't handle it.

My question is that, is this behavior intended? Otherwise, is there any workaround to avoid that?

**Comment by iapicca** [comment] 2020-07-20 06:09
Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by LuodiJackShen** [comment] 2020-08-12 02:36
Duplicate of #63364
