### ISSUE TITLE
[Camera] Can not use the camera plugin with Android API level 30

### ISSUE THREAD

**Issue by Max-Might** [flutter/flutter#69883] opened 2020-11-05 14:58 UTC
The camera plugin can not be used with Android API level 30 because it uses a deprecated method and warnings are treated as errors.

## Steps to Reproduce

1. Set compile and target API versions in your `build.gradle` file like to API level 30:
```
compileSdkVersion = 30
targetSdkVersion = 30
```

## Logs
The build fails with this error:
```
/home/user/.pub-cache/hosted/pub.dartlang.org/camera-0.5.8+11/android/src/main/java/io/flutter/plugins/camera/Camera.java:333: warning: [deprecation] createCaptureSession(List<Surface>,StateCallback,Handler) in CameraDevice has been deprecated
    cameraDevice.createCaptureSession(surfaceList, callback, null);     
                ^                                                       
error: warnings found and -Werror specified                             
1 error                                                                 
1 warning
```

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.3, on Linux, locale en_US.UTF-8)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[!] Android Studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    ✗ android-studio-dir = ~/Development/android-studio/
    ✗ Android Studio not found at ~/Development/android-studio/
[✓] Connected device (1 available)

! Doctor found issues in 1 category.
```

**Comment by darshankawar** [comment] 2020-11-06 07:36
@Max-Might 
I tried the official camera plugin [example](https://github.com/flutter/plugins/tree/master/packages/camera/example) on latest stable version (1.22.3), changed `compilesdkversion` and `targetsdkversion` to 30 and ran it on Android 11 (API 30) (emulator)and was able to compile and run the app.

<img width="1250" alt="Screenshot 2020-11-06 at 1 02 29 PM" src="https://user-images.githubusercontent.com/67046386/98338670-8792dc80-2030-11eb-920a-72b3322628f5.png">

Since I don't have a physical device targeting api 30, I am not sure if the issue you are facing is only on physical device. Can you check if on emulator too you get same error ?

**Comment by Max-Might** [comment] 2020-11-06 07:58
@darshankawar This is strange.
The error happens because this method signature is marked as deprecated in api level 30:
```java
cameraDevice.createCaptureSession(surfaceList, callback, null);
```

And in the `build.gradle` file it is configured to treat warnings as errors:
```groovy
def args = ["-Xlint:deprecation","-Xlint:unchecked","-Werror"]
```

**Comment by darshankawar** [comment] 2020-11-06 10:39
@Max-Might 
I am not facing the issue. Updated `compilesdkversion` and `targetsdkversion` to 30 and this time used [this](https://flutter.dev/docs/cookbook/plugins/picture-using-camera) example which compiled and ran properly without any issues.

Can you try running `flutter pub cache repair` or `flutter clean` and then `flutter run` ?

**Comment by kasgaormeo** [comment] 2020-11-07 04:03
I had encountered the same issue as @Max-Might 

`flutter pub cache repair` -> `flutter clean` -> `flutter run` not working.

Instead, I directly declared the Camera.java file in the camera package.

Just did pull request

**Comment by DasTobbel** [comment] 2020-11-13 15:50
Can confirm that issue. Happens to me as soon as the 'compileSdkVersion 30' is used.
Also the issue is not resolved with the suggestion of @darshankawar.
After `flutter pub cache repair` -> `flutter clean` -> `flutter run` 
build exits with:
```
[SomeDirectoryName]/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/camera-0.5.8+11/android/src/main/java/io/flutter/plugins/camera/Camera.java:333: warning: [deprecation] createCaptureSession(List<Surface>,StateCallback,Handler) in CameraDevice has been deprecated
    cameraDevice.createCaptureSession(surfaceList, callback, null);
                ^
error: warnings found and -Werror specified
1 error
1 warning
```

running on:
[✓] Flutter (Channel beta, 1.23.0-18.1.pre, on Linux, locale en_US.UTF-8) 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Chrome - develop for the web
[✓] Android Studio
[✓] Connected device (4 available)

**Comment by AmbujaAK** [comment] 2020-11-27 13:58
i too got same issue. any solution ??

**Closed** 2020-12-03 20:18 UTC
Labels: p: camera, p: first party, passed first triage, plugin
