### ISSUE TITLE
iOS compilation error - failed to emit precompiled header Runner-Bridging-Header.h

### ISSUE THREAD

**Issue by davidsx** [flutter/flutter#42498] opened 2019-10-11 05:11 UTC
## Steps to Reproduce

I have encountered some critical problems when I am developing my apps and I thought there may be some configuration violation so I start a whole new flutter and run it. 
However, I cannot successfully run my new project too.

**Target Platform: iOS**
**Target OS version/browser: iOS 13**
**Devices: iPhone XS**

## Logs

```
Launching lib/main.dart on David’s IPhone in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: XMV49G669D
Xcode build done.                                           32.0s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **
Xcode's output:
↳
    /Users/David_Lau/flutter/testing/ios/Runner/Runner-Bridging-Header.h:1:9: note: in file included from /Users/David_Lau/flutter/testing/ios/Runner/Runner-Bridging-Header.h:1:
    #import "GeneratedPluginRegistrant.h"
            ^
    /Users/David_Lau/flutter/testing/ios/Runner/GeneratedPluginRegistrant.h:8:9: error: 'Flutter/Flutter.h' file not found
    #import <Flutter/Flutter.h>
            ^
    1 error generated.
    <unknown>:0: error: failed to emit precompiled header '/Users/David_Lau/Library/Developer/Xcode/DerivedData/Runner-azesybqhtijmtfcugdshfkybgtmu/Build/Intermediates.noindex/PrecompiledHeaders/Runner-Bridging-Header-swift_XFD3EM62ZHT9-clang_3SE6OY8X33GBC.pch' for bridging header '/Users/David_Lau/flutter/testing/ios/Runner/Runner-Bridging-Header.h'
    <unknown>:0: error: generate-pch command failed with exit code 1 (use -v to see invocation)
    <unknown>:0: error: generate-pch command failed with exit code 1 (use -v to see invocation)
    /Users/David_Lau/flutter/testing/ios/Runner/Runner-Bridging-Header.h:1:9: note: in file included from /Users/David_Lau/flutter/testing/ios/Runner/Runner-Bridging-Header.h:1:
    #import "GeneratedPluginRegistrant.h"
            ^
    /Users/David_Lau/flutter/testing/ios/Runner/GeneratedPluginRegistrant.h:8:9: error: 'Flutter/Flutter.h' file not found
    #import <Flutter/Flutter.h>
            ^
    1 error generated.
    <unknown>:0: error: failed to emit precompiled header '/Users/David_Lau/Library/Developer/Xcode/DerivedData/Runner-azesybqhtijmtfcugdshfkybgtmu/Build/Intermediates.noindex/PrecompiledHeaders/Runner-Bridging-Header-swift_AE5E56KLAZ7Q-clang_29NJ7Q52SDGMJ.pch' for bridging header '/Users/David_Lau/flutter/testing/ios/Runner/Runner-Bridging-Header.h'
    note: Using new build systemnote: Planning buildnote: Constructing build description
Could not build the precompiled application for the device.

Error launching application on David’s IPhone.
Exited (sigterm)

```

```
[✓] Flutter (Channel stable, v1.9.1+hotfix.4, on Mac OS X 10.14.4 18E227, locale zh-Hant-HK)
    • Flutter version 1.9.1+hotfix.4 at /Users/David_Lau/Desktop/flutter
    • Framework revision cc949a8e8b (13 days ago), 2019-09-27 15:04:59 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/David_Lau/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    • CocoaPods version 1.7.5

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 34.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.39.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.5.1

[✓] Connected device (1 available)
    • David’s IPhone • xxxxxxxxxxxxxxxxxxxx • ios • iOS 13.1.2

• No issues found!
```

Please give advice since I cannot even start my code!!

**Comment by jmagman** [comment] 2019-10-11 18:12
Can you give us the exact reproduction steps you used to create the new app?  What are the contents of `ios/Podfile`?

**Comment by davidsx** [comment] 2019-10-13 09:21
Sorry for the late reply. 
Well, it is simply starting a new project in VS Code by the command ```Flutter: New Project```.
Then run it on either iOS simulator or a physical device. It fails to compile and gives the above error.

It does not include any Podfile inside.

**Comment by davidsx** [comment] 2019-10-13 09:30
If really need, I run ```pod init``` in ```/ios```
my Podfile has the following content:
```
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Runner' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Runner

end
```

**Comment by DanTup** [comment] 2019-10-29 11:47
I've just hit this too trying to run a test app I use for Dart-Code integration tests.

```
Launching lib/main.dart on iPhone 11 Pro Max in debug mode...
Running Xcode build...                                                  
 ├─Assembling Flutter resources...                           7.5s
 └─Compiling, linking and signing...                         0.2s
Xcode build done.                                            9.3s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    /tmp/flutter_repo/flutter_hello_world/flutter_repro_42498/ios/Runner/Runner-Bridging-Header.h:1:9: error: 'GeneratedPluginRegistrant.h' file not found
    #import "GeneratedPluginRegistrant.h"
            ^
    1 error generated.
    <unknown>:0: error: failed to emit precompiled header
    '/Users/dantup/Library/Developer/Xcode/DerivedData/Runner-fjycbzowbqgdnhcakadthzamzgvw/Build/Intermediates.noindex/PrecompiledHeaders/Runner-Bridging-He
    ader-swift_1NUF51Y4NUKU8-clang_740PO05NPUJ1.pch' for bridging header
    '/tmp/flutter_repo/flutter_hello_world/flutter_repro_42498/ios/Runner/Runner-Bridging-Header.h'
    <unknown>:0: error: generate-pch command failed with exit code 1 (use -v to see invocation)
    note: Using new build systemnote: Planning buildnote: Constructing build descriptionwarning: Capabilities for Signing & Capabilities may not function
    correctly because its entitlements use a placeholder team ID. To resolve this, select a development team in the Runner editor. (in target 'Runner' from
    project 'Runner')

Could not build the application for the simulator.
Error launching application on iPhone 11 Pro Max.
```

As far as I can tell, there is no `Podfile` file. I've committed the whole folder here if it helps:

https://github.com/DanTup/flutter_repro_42498

**Comment by DanTup** [comment] 2019-10-29 11:58
I tried deleting `build`, `ios`, `.dart_tool` and then running `flutter create .` but it's still failing with the same error.

So I tried `flutter create foo && cd foo && flutter run` and that worked fine.

So I compared the two folders, and noticed I had an `example` folder and the new project did not. Deleted that, and it built fine. I'm not sure exactly what in the `example` folder might be causing it though.

**Comment by jmagman** [comment] 2019-10-29 17:48
https://github.com/DanTup/flutter_repro_42498 looks like it's for a plugin, which is why it has an example directory?  But there's no my_package checked in.
pubspec.yaml:
```yaml
  my_package:
    path: ../my_package
```

@DanTup What exact command did you use to generate that project?  And were you inside another flutter app when you did?

**Comment by jmagman** [comment] 2019-10-29 17:51
> If really need, I run `pod init` in `/ios`

@davidsx Don't run `pod init` manually, you should delete that generated Podfile.  If you don't have any plugins you won't have a Podfile--that's expected.

**Comment by DanTup** [comment] 2019-10-29 17:56
> But there's no my_package checked in

Whoops, you should be able to just delete that - I think I removed the code for that (to simplify the repro) but must have forgotten the pubspec entry.

The reason it has an `example` folder is that I added it deliberately for testing Dart-Code supporting nested-projects (this project was just a simple hello_world that's grown a little over time for Dart-Code's integration tests).

Is it valid to have an `example` folder in an app? It did used to work (these aren't new tests/projects), but I don't know whether it was intended to be supported.

**Comment by iapicca** [comment] 2020-03-16 15:03
Hi @davidsx 
if the issue persist with the latest stable version of flutter
could you please provide your updated `flutter doctor -v` ,
your `flutter run --verbose` 
and if possible a reproducible minimal code sample.
Thank you

**Comment by jmagman** [comment] 2020-04-07 18:24
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!

Thanks for your contribution.

**Closed by jmagman** 2020-04-07 18:24 UTC
Labels: platform-ios, t: xcode, tool, waiting for customer response
