### ISSUE TITLE
[desktop] RaisedButton null onPressed crashes until resizing window

### ISSUE THREAD

**Issue by mkiisoft** [flutter/flutter#33326] opened 2019-05-24 23:29 UTC
While trying to use "null" on a RaisedButton onPressed to "disabled it" which works perfectly over Android, iOS and the equivalent of Web, is crashing on Desktop (Mac build) until I slightly resize the window which fixes everything.

```
setState() or markNeedsBuild() called during build.
This RawMaterialButtton widget cannot be marked as needing to build because the framework is already in the process of building widgets. A widget can be marked as needing to be built during the build phase only if one of its ancestors is currently building.

The widget on which setState() or markNeedsBuild() was called was:
RawMaterialButton(state:_RawMaterialButtonState#a19ee)
The widget which was currently being built when the offending call was made was:
InkWell(gesture: <none>, clipped to BoxShape.rectangle........
```
and with the following terminal info:

```
flutter: Another exception was thrown: 'package:flutter/src/material/material.dart': Failed assertion: line 585 pos 12: 'referenceBox.attached': is not true.
```

Building using the following configs:
```
Flutter (Channel master, v1.6.2-pre.29, on Mac OS X 10.14.4 18E226, locale en-US)
```

**Comment by stuartmorgan** [comment] 2019-05-25 01:28
Could you provide a simple reproducible test case of the Dart code involved?

**Comment by mkiisoft** [comment] 2019-05-25 01:48
@stuartmorgan ...sure, but is a super straight forward one:
```
RaisedButton(
child: Text(
            "some text",
           ),
color: Colors.deepPurpleAccent,
disabledColor: Colors.deepPurple,
onPressed: condition
                         ? () => logic()
                         : null,
)
```
when the condition changes to false, the "null" onPressed triggers and "breaks" the widget, but, if I resize the window to any axis, it fixes by itself.

**Comment by gspencergoog** [comment] 2019-07-26 23:06
This is a duplicate of #34930

**Closed by gspencergoog** 2019-07-26 23:06 UTC
Labels: a: desktop, ⌘‬ platform-mac
