### ISSUE TITLE
Build failed after installing package

### ISSUE THREAD

**Issue by overloadcode** [flutter/flutter#62441] opened 2020-07-28 21:00 UTC
Hello,

I'm sorry for my bad English, but I've been struggling with application development problems for several days now.

It started with a problem with the geolocator package:
`[FAILURE: Build failed with an exception. (geolocator)](https://imgur.com/vzRhve5)`

I was trying to fix it but nothing worked, so I let it go until today. I added permission_handler and I've encountered the same problem and here are the results:

```
[FAILURE: Build failed with an exception. (permission_handler](https://i.imgur.com/gkqczrR.png)
`[   +1 ms] FAILURE: Build failed with an exception.
[   +6 ms] * What went wrong:
[   +7 ms] Execution failed for task ':permission_handler:parseDebugLocalResources'.
[   +1 ms] > Could not resolve all files for configuration ':permission_handler:androidApis'.
[        ]    > Failed to transform file 'android.jar' to match attributes {artifactType=android-platform-attr,
org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}
[   +1 ms]       > Execution failed for PlatformAttrTransform: ..\AppData\Local\Android\sdk\platforms\android-29\android.jar.   
[   +1 ms]          > ..\AppData\Local\Android\sdk\platforms\android-29\android.jar (Nie mo?na odnale?? okre?lonego pliku)      
[   +1 ms] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan toget full insights.
[   +3 ms] * Get more help at https://help.gradle.org
[  +12 ms] BUILD FAILED in 17s
[ +393 ms] Running Gradle task 'assembleDebug'... (completed in 17,8s)
[   +6 ms] Exception: Gradle task assembleDebug failed with exit code 1
[   +4 ms] "flutter run" took 18 731ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
#1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:569:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:723:18)
#3      _rootRunUnary (dart:async/zone.dart:1192:38)
#4      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#5      _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#7      Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#8      Future._completeWithValue (dart:async/future_impl.dart:526:5)
#9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
#10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:298:13)
#11     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#12     _rootRunUnary (dart:async/zone.dart:1192:38)
#13     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#14     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#16     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#17     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#18     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
#19     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:298:13)
#20     AndroidDevice.isLocalEmulator (package:flutter_tools/src/android/android_device.dart)
#21     _rootRunUnary (dart:async/zone.dart:1192:38)
#22     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#23     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#24     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#25     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#26     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#27     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
#28     _rootRun (dart:async/zone.dart:1184:13)
#29     _CustomZone.run (dart:async/zone.dart:1077:19)
#30     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
#31     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
#32     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#33     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#34     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#35     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)`
```

Flutter doctor:
https://i.imgur.com/MG0buZy.png

build.gradle:
[build gradle android and defaultConfig](https://i.imgur.com/Jh3z4qR.png)

gradle.properties:
```
org.gradle.jvmargs=-Xmx1536M
android.enableR8=true
android.useAndroidX=true
android.enableJetifier=true
```

pubspec.yaml my dependencies:
[https://i.imgur.com/mXtGyiE.png](https://i.imgur.com/mXtGyiE.png)

I tried:
- clean and rerun
- default gradle plugin is set on 3.5.0 and distribution on 5.6.2, basic on [https://developer.android.com/studio/releases/gradle-plugin](https://developer.android.com/studio/releases/gradle-plugin) i change on the newest, clean, run. This didnt work, currently i have plugin 3.6.4: com.android.tools.build:gradle:3.6.4 and gradle-5.6.4-all.zip, this didnt work also, i have same error
- trying with older version packages, geolocator, permission

I'm currently working on VS Code.
Please help me

**Comment by overloadcode** [comment] 2020-07-29 07:52
> Hi @overloadcode,
> Please provide a minimal complete reproducible code sample that shows the issue you are facing.
> Thanks.


The error is unique and it's not the code problem. Build failed always occurs after installing package like geolocator or permission_handler even after the creation of a new application.

I checked it on default app - same problem and same errors.
But if i delete package, problem disappears. Location package have a problem with location_web, based on the answers from Stackoverflow i change settings.gradle and this work just fine. Geolocator gives me always same build failed with an exception. Permission_handler too.

I created a new default application, after adding geolocator to pubspec.yaml and run "flutter run" i have this error:

[Build failed geolocator](https://i.imgur.com/Hwdo36V.png)  (can't find specific file - android.jar)
If i remove geolocator from pubspec.yaml default application working without any errors.

Same thing with permission_handler
[Build failed permission_handler](https://i.imgur.com/EKQMiBW.png)

With two packages together i have error with location_permission, but rest are same.

`import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
      
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {

    return Scaffold(
      appBar: AppBar(
        
        title: Text(widget.title),
      ),
      body: Center(
      
        child: Column(
         
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
`

Permission_handler  is the second package with this build failed problem. I just need to remove them from pubspec for the application to work but then I can't use this package. I don't think the code is a problem

**Comment by darshankawar** [comment] 2020-07-29 10:30
Hi @overloadcode,

1. Are you able to build if you add any other dependency than `geolocator`, `location` and `permission_handler` ?
2. Can you try `flutter pub cache repair` and then `flutter run` to see if it works ?  Stop the app instance first, and then try the above commands.
3. Can you create a new Flutter project and then try adding these plugins again and see if it works ?

I tried adding both plugins and was able to build properly on latest master.

Also, both the plugins you mentioned are 3rd party, so if problem still persists, please consider opening this issue against their repo.

**Comment by overloadcode** [comment] 2020-07-29 11:05
>     1. Are you able to build if you add any other dependency than `geolocator`, `location` and `permission_handler` ?
> 
Yes, 2 days ago i had problem only with this `geolocator` but i wanted add some permission to my application, thats why i add `permission_handler`.
After testing some other packages for example:
`  google_maps_flutter: ^0.5.28+1
  hive: ^1.4.2
  sqflite: ^1.3.1`

Working, but with some warnings - [warnings](https://i.imgur.com/qc9ymwY.png)

I discovered that after adding `flutter_local_notifications` i have same error:
`FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flutter_local_notifications:parseDebugLibraryResources'.
> Could not resolve all files for configuration ':flutter_local_notifications:androidApis'.
   > Failed to transform file 'android.jar' to match attributes {artifactType=android-platform-attr, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}
      > Execution failed for PlatformAttrTransform: C:\Users\admin\AppData\Local\Android\sdk\platforms\android-29\android.jar.
         > C:\Users\admin\AppData\Local\Android\sdk\platforms\android-29\android.jar (Nie mo?na odnale?? okre?lonego pliku)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.`

I guess they're not the only ones who don't want to work with me, I haven't tested everything.

>     2. Can you try `flutter pub cache repair` and then `flutter run` to see if it works ?  Stop the app instance first, and then try the above commands.

I still have same errors, nothing works

> 
>     3. Can you create a new Flutter project and then try adding these plugins again and see if it works ?
> 

Same problem - this is my default project with this errors:
[Default Flutter app](https://mega.nz/file/mZgnELJY#jJZc-W3_MzlTdlV13vX0l10gyDRGGUCjpGXbKWKqUSo)

**Comment by darshankawar** [comment] 2020-07-29 12:32
@overloadcode 
Can you try [this](https://stackoverflow.com/a/54248935) solution related to android sdk 29 ?

**Comment by overloadcode** [comment] 2020-07-29 13:51
Yes!
Finally everything's working!

I checked and compared the contents of the SDK files a few files were missing, i deleted android-28, android-29 and android-30 and reinstalled. Platform-tools are fine.
Now it's work just great without any errors. Thank you for the suggestion!

**Comment by darshankawar** [comment] 2020-07-31 11:24
Hi @overloadcode,
Glad that the issue is resolved.
Given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you

**Closed by darshankawar** 2020-07-31 11:24 UTC
Labels: in triage

**Comment by bahramee** [comment] 2021-01-26 13:05
> Yes!
> Finally everything's working!
> 
> I checked and compared the contents of the SDK files a few files were missing, i deleted android-28, android-29 and android-30 and reinstalled. Platform-tools are fine.
> Now it's work just great without any errors. Thank you for the suggestion!

that was really helpful.
