### ISSUE TITLE
App doesn't get to render after didChangeAppLifecycleState event

### ISSUE THREAD

**Issue by LinusU** [flutter/flutter#32895] opened 2019-05-17 14:13 UTC
I'm building an application that shows the user some potentially confedential information, because of this the app will get locked as soon as the app is put in the background in any way. This mean that I also don't want anything but the lock-screen to show up in the task switcher or when launching from a suspended state.

The way you do this in native iOS apps is simply to switch to your lock-screen as soon as your app goes to the background.

Trying to do the same thing in Flutter though leaves the app with the previous view, and it doesn't re-render until a small delay _after you get back to the app_.

I've created a simple demo app to illustrate the problem:
https://github.com/LinusU/curtain_example

Here is also a screen recording of the Flutter app in release mode, and a screen recording on another, native, app that implements this correctly:

<img width="300" alt="flutter" src="https://user-images.githubusercontent.com/189580/57933589-95d9bf80-78b5-11e9-931d-22cc75844b21.gif" /><img width="300" alt="swift" src="https://user-images.githubusercontent.com/189580/57933594-970aec80-78b5-11e9-99d0-94c7f93a534c.gif" />

## Steps to Reproduce

1. create a simple app with this homepage

  ```dart
  class _MyHomePageState extends State<MyHomePage> with WidgetsBindingObserver {
    bool locked = false;

    @override
    void initState() {
      super.initState();
      WidgetsBinding.instance.addObserver(this);
    }

    @override
    void dispose() {
      WidgetsBinding.instance.removeObserver(this);
      super.dispose();
    }

    @override
    void didChangeAppLifecycleState(AppLifecycleState state) {
      if (state == AppLifecycleState.inactive || state == AppLifecycleState.paused || state == AppLifecycleState.suspending) {
        setState(() {
          locked = true;
        });
      }
    }

    @override
    Widget build(BuildContext context) {
      return Scaffold(
        appBar: AppBar(title: Text(widget.title)),
        body: Text(locked ? 'LOCKED' : 'UNLOCKED'),
      );
    }
  }
  ```

1. launch the app in iOS
2. drag up the control center
3. flick down the control center
4. notice the delay until the app "locks"

## Logs

```
```

```
Analyzing curtain_example...                                            
No issues found! (ran in 5.8s)
```

```
[✓] Flutter (Channel dev, v1.6.0, on Mac OS X 10.14.4 18E226, locale en-GB)
    • Flutter version 1.6.0 at /Users/linus/coding/flutter
    • Framework revision ed90d05596 (3 days ago), 2019-05-14 17:09:29 -0700
    • Engine revision 832cdacc6f
    • Dart version 2.3.1 (build 2.3.1-dev.0.0 a0290f823c)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /usr/local/share/android-sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /usr/local/share/android-sdk
    • ANDROID_SDK_ROOT = /usr/local/share/android-sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.1

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.33.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.0.0

[✓] Connected device (1 available)
    • Linus Unnebäck’s iPhone • f94aa6361e142ab9641a700b2eb487e8611738f4 • ios • iOS 12.2

• No issues found!
```

**Comment by dnfield** [comment] 2019-07-09 13:32
As mentioned in the linked bug, this would require some platform specific code.  Closing this as a duplicate of the linked bug (sorry that we missed this one, I do see it was reported earlier).

**Closed by dnfield** 2019-07-09 13:32 UTC
