### ISSUE TITLE
Upgrading to Flutter 2.0 breaks my existing web projects with FirebaseFirestore.

### ISSUE THREAD

**Issue by Nulligma** [flutter/flutter#77764] opened 2021-03-10 03:56 UTC
My projects which were working fine before updating to flutter 2.0 are now having problem in web but running perfectly fine on my android devices. Before updating they were running perfectly on web & mobile.

## Steps to Reproduce

A simple Standalone code of my projects which is getting problem is as follows: 

`Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        debugShowCheckedModeBanner: false,
        home: StreamBuilder(
          stream: FirebaseAuth.instance.idTokenChanges(),
          builder: (BuildContext context, AsyncSnapshot<User?> snapshot) {
            if (snapshot.hasError) {
              return Column(
                mainAxisAlignment: MainAxisAlignment.center,
                crossAxisAlignment: CrossAxisAlignment.center,
                children: <Widget>[
                  Icon(
                    Icons.error_outline,
                    color: Colors.red,
                    size: 60,
                  ),
                  Padding(
                    padding: const EdgeInsets.only(top: 16),
                    child: Text('Error: ${snapshot.error}'),
                  )
                ],
              );
            } else if (!snapshot.hasData)
              return _AutoLogin();
            else if (snapshot.hasData) return _AppManager();

            return Column(
              mainAxisAlignment: MainAxisAlignment.center,
              crossAxisAlignment: CrossAxisAlignment.center,
              children: <Widget>[
                SizedBox(
                  child: const CircularProgressIndicator(),
                  width: 60,
                  height: 60,
                ),
                const Padding(
                  padding: EdgeInsets.only(top: 16),
                  child: Text('Waiting for connection...'),
                )
              ],
            );
          },
        ));
  }
}

enum AppState {
  loading,
  databaseSetupPending,
  uploadingDatabase,
  databaseSetuped,
  databaseDownloading,
  ready
}

class _AppManager extends StatefulWidget {
  @override
  __AppManagerState createState() => __AppManagerState();
}

class __AppManagerState extends State<_AppManager> {
  late AppState appState;

  @override
  void initState() {
    super.initState();
    appState = AppState.loading;
    loadData();
  }

  void loadData() async {
    QuerySnapshot val =
        await FirebaseFirestore.instance.collection("AppData").get();

    setState(() {
      if (val.docs.length == 0)
        appState = AppState.databaseSetupPending;
      else
        appState = AppState.databaseDownloading;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Text(appState.toString()),
      ),
    );
  }
}

class _AutoLogin extends StatefulWidget {
  @override
  __AutoLoginState createState() => __AutoLoginState();
}

class __AutoLoginState extends State<_AutoLogin> {
  bool isLogingIn = false;
  @override
  void initState() {
    super.initState();
  }

  void login() async {
    try {
      await FirebaseAuth.instance.signInWithEmailAndPassword(
          email: "shantanu@gmail.com", password: "123456");
    } on FirebaseAuthException catch (e) {
      print(e.message);
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: isLogingIn
            ? CircularProgressIndicator()
            : TextButton(
                onPressed: () {
                  setState(() {
                    isLogingIn = true;
                  });
                  login();
                },
                child: Text("login")),
      ),
    );
  }
}`

and my index.html file is as follows: 

`https://developers.google.com/web/fundamentals/primers/service-workers -->
  <script src="https://www.gstatic.com/firebasejs/8.2.10/firebase-app.js"></script>
  <script src="https://www.gstatic.com/firebasejs/8.2.10/firebase-auth.js"></script>
  <script src="https://www.gstatic.com/firebasejs/8.2.10/firebase-firestore.js"></script>
  <script>
    // Your web app's Firebase configuration
    // For Firebase JS SDK v7.20.0 and later, measurementId is optional
    var firebaseConfig = {
      apiKey: "*******************************",
      authDomain: "*******************************",
      projectId: "*******************************",
      storageBucket: "*******************************",
      messagingSenderId: "*******************************",
      appId: "**************************************************************",
      measurementId: "*******************************"
    };
    // Initialize Firebase
    firebase.initializeApp(firebaseConfig);
  </script>
`

**Expected results:** I wanted to see the firebase - firestore's collection by name "AppData" has any document or not

**Actual results:** 
I get the following error while being on code FirebaseFirestore.instance.collection("AppData").get(); 

`Error: [cloud_firestore/unknown] Expected a value of type '((Object?) => Object)?', but got one of type '(Object) => Object?'
    at Object.throw_ [as throw] (http://localhost:62392/dart_sdk.js:5032:11)
    at collection_reference_web.CollectionReferenceWeb.new.get (http://localhost:62392/packages/cloud_firestore_web/src/write_batch_web.dart.lib.js:370:23)
    at get.next (<anonymous>)
    at http://localhost:62392/dart_sdk.js:37210:33
    at _RootZone.runUnary (http://localhost:62392/dart_sdk.js:37081:59)
    at _FutureListener.thenAwait.handleValue (http://localhost:62392/dart_sdk.js:32337:29)
    at handleValueCallback (http://localhost:62392/dart_sdk.js:32864:49)
    at Function._propagateToListeners (http://localhost:62392/dart_sdk.js:32902:17)
    at _Future.new.[_completeWithValue] (http://localhost:62392/dart_sdk.js:32750:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:62392/dart_sdk.js:32771:35)
    at Object._microtaskLoop (http://localhost:62392/dart_sdk.js:37333:13)
    at _startMicrotaskLoop (http://localhost:62392/dart_sdk.js:37339:13)
    at http://localhost:62392/dart_sdk.js:33110:9
`

```
[ +218 ms] executing: [C:\flutter/] git -c log.showSignature=false log -n 1
--pretty=format:%H
[ +238 ms] Exit code 0 from: git -c log.showSignature=false log -n 1
--pretty=format:%H
[   +2 ms] c5a4b4029c0798f37c4a39b479d7cb75daa7b05c    
[   +2 ms] executing: [C:\flutter/] git tag --points-at
c5a4b4029c0798f37c4a39b479d7cb75daa7b05c
[ +310 ms] Exit code 0 from: git tag --points-at
c5a4b4029c0798f37c4a39b479d7cb75daa7b05c        
[   +2 ms] 2.0.1
[ +159 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[ +113 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\flutter/] git ls-remote --get-url origin
[  +84 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +194 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref HEAD
[ +121 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] stable
[ +186 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required,
skipping update.
[   +5 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required,
skipping update.
[   +6 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping       
update.
[  +15 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[  +10 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping
update.
[   +5 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping     
update.
[   +9 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping
update.
[   +4 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping 
update.
[   +3 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping 
update.
[  +22 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skippingupdate.
[  +36 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skippingupdate.
[ +286 ms] executing: C:\Users\shant\AppData\Local\Android\sdk\platform-tools\adb.exedevices -l
[ +142 ms] List of devices attached
[  +15 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required,
skipping update.
[   +2 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required,     
skipping update.
[   +2 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping       
update.
[  +12 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping
update.
[   +3 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping     
update.
[   +3 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping
update.
[   +9 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping 
update.
[   +3 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping 
update.
[   +2 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skippingupdate.
[  +10 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skippingupdate.
[ +301 ms] Multiple devices found:
[  +91 ms] Chrome (web) • chrome • web-javascript • Google Chrome 88.0.4324.190
[   +8 ms] Edge (web)   • edge   • web-javascript • Microsoft Edge 89.0.774.45
[   +8 ms] [1]: Chrome (chrome)
[   +1 ms] [2]: Edge (edge)
[   +7 ms] Please choose one (To quit, press "q/Q")
[   +1 ms] : 
[+5035 ms] 1
[  +60 ms] Skipping pub get: version match.
[  +63 ms] Found plugin cloud_firestore at
C:\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore-1.0.0\
[  +28 ms] Found plugin cloud_firestore_web at
C:\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore_web-1.0.0\
[  +30 ms] Found plugin firebase_auth at
C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-1.0.0\
[  +17 ms] Found plugin firebase_auth_web at
C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth_web-1.0.0\
[  +12 ms] Found plugin firebase_core at
C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-1.0.0\
[  +10 ms] Found plugin firebase_core_web at
C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core_web-1.0.0\
[ +301 ms] Found plugin cloud_firestore at
C:\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore-1.0.0\
[  +14 ms] Found plugin cloud_firestore_web at
C:\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore_web-1.0.0\
[  +20 ms] Found plugin firebase_auth at
C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-1.0.0\
[  +18 ms] Found plugin firebase_auth_web at
C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth_web-1.0.0\
[   +6 ms] Found plugin firebase_core at
C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-1.0.0\
[  +10 ms] Found plugin firebase_core_web at
C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core_web-1.0.0\
[  +85 ms] Generating
C:\WORK\Flutter\youtube_clone\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[ +294 ms] Launching lib\main.dart on Chrome in debug mode...
[ +368 ms] Updating assets
[ +261 ms] Waiting for connection from debug service on Chrome...
[  +30 ms] Found plugin cloud_firestore at
C:\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore-1.0.0\
[  +12 ms] Found plugin cloud_firestore_web at
C:\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore_web-1.0.0\
[  +14 ms] Found plugin firebase_auth at
C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-1.0.0\
[   +7 ms] Found plugin firebase_auth_web at
C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth_web-1.0.0\
[   +6 ms] Found plugin firebase_core at
C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-1.0.0\
[  +17 ms] Found plugin firebase_core_web at
C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core_web-1.0.0\
[  +87 ms] Found plugin cloud_firestore at
C:\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore-1.0.0\
[  +15 ms] Found plugin cloud_firestore_web at
C:\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore_web-1.0.0\
[  +11 ms] Found plugin firebase_auth at
C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-1.0.0\
[   +6 ms] Found plugin firebase_auth_web at
C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth_web-1.0.0\
[   +7 ms] Found plugin firebase_core at
C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-1.0.0\
[   +6 ms] Found plugin firebase_core_web at
C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core_web-1.0.0\
[ +310 ms] <- reset
[  +18 ms] C:\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev
C:\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot      
--sdk-root C:\flutter\bin\cache\flutter_web_sdk/ --incremental --target=dartdevc     
--debugger-module-names --experimental-emit-debug-metadata
-DFLUTTER_WEB_AUTO_DETECT=true --output-dill
C:\Users\shant\AppData\Local\Temp\flutter_tools.163cc425\flutter_tool.fb86a0a2\app.dill --libraries-spec file:///C:/flutter/bin/cache/flutter_web_sdk/libraries.json      
--packages C:\WORK\Flutter\youtube_clone\.dart_tool\package_config.json
-Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts
--track-widget-creation --filesystem-root
C:\Users\shant\AppData\Local\Temp\flutter_tools.163cc425\flutter_tools.f5e09c67      
--filesystem-scheme org-dartlang-app --initialize-from-dill
build\b1b715402d823b7fd5c2b68d2edcb2ce.cache.dill.track.dill --platform
file:///C:/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk_sound.dill       
--sound-null-safety
[  +58 ms] <- compile org-dartlang-app:/web_entrypoint.dart
[+37882 ms] Waiting for connection from debug service on Chrome... (completed in     
38.5s)
[   +2 ms] Synced 30.8MB.
[   +1 ms] <- accept
[   +1 ms] Caching compiled dill
[+673565 ms] Using 
[+3933 ms] [CHROME]:
[ +690 ms] [CHROME]:DevTools listening on
ws://127.0.0.1:50527/devtools/browser/5e7d8001-eb89-4548-a966-53bbee9d0ab1
[+1672 ms] DwdsInjector: Received request for entrypoint at
http://localhost:49697/main_module.bootstrap.js
[   +8 ms] MetadataProvider: Loading debug metadata...
[  +24 ms] MetadataProvider: Loaded debug metadata
[  +19 ms] DwdsInjector: Injected debugging metadata for entrypoint at
http://localhost:49697/main_module.bootstrap.js
[+9121 ms] DevHandler: Debug service listening on
ws://127.0.0.1:50562/NqStf8QCL9o=/ws

[  +18 ms] Debug service listening on ws://127.0.0.1:50562/NqStf8QCL9o=/ws
[        ]  Running with sound null safety 
[   +5 ms]   To hot restart changes while running, press "r" or "R".       
[        ] For a more detailed help message, press "h". To quit, press "q".
[+13575 ms] Error: [cloud_firestore/unknown] Expected a value of type '((Object?) =>
Object)?',
                     but got one of type '(Object) => Object?'
                         at Object.throw_ [as throw]
(http://localhost:49697/dart_sdk.js:5032:11)
                         at collection_reference_web.CollectionReferenceWeb.new.get  

(http://localhost:49697/packages/cloud_firestore_web/src/write_batch_web.dart.lib    
                         .js:370:23)
                         at get.next (<anonymous>)
                         at http://localhost:49697/dart_sdk.js:37210:33
                         at _RootZone.runUnary
(http://localhost:49697/dart_sdk.js:37081:59)
                         at _FutureListener.thenAwait.handleValue
                         (http://localhost:49697/dart_sdk.js:32337:29)
                         at handleValueCallback
(http://localhost:49697/dart_sdk.js:32864:49)
                         at Function._propagateToListeners
(http://localhost:49697/dart_sdk.js:32902:17)
                         at _Future.new.[_completeWithValue]
(http://localhost:49697/dart_sdk.js:32750:23)
                         at async._AsyncCallbackEntry.new.callback
                         (http://localhost:49697/dart_sdk.js:32771:35)
                         at Object._microtaskLoop
(http://localhost:49697/dart_sdk.js:37333:13)
                         at _startMicrotaskLoop
(http://localhost:49697/dart_sdk.js:37339:13)
                         at http://localhost:49697/dart_sdk.js:33110:9
```

```
No issues found! (ran in 12.8s)
```

```
flutter doctor -v
[√] Flutter (Channel stable, 2.0.1, on Microsoft Windows [Version 10.0.19042.804],
    locale en-IN)
    • Flutter version 2.0.1 at C:\flutter
    • Framework revision c5a4b4029c (5 days ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.0-rc1)
    • Android SDK at C:\Users\shant\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.0-rc1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)   
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor     
      --android-licenses

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe      

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code, 64-bit edition (version 1.54.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.20.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 88.0.4324.190
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 89.0.774.45 
```

</details>

**Comment by pedromassangocode** [comment] 2021-03-10 07:40
Hi @Nulligma 
From what I can see, the issue is related to a FlutterFire plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by pedromassangocode** 2021-03-10 07:40 UTC
Labels: in triage
