### ISSUE TITLE
can not run build_runner in flutter v1.20.0

### ISSUE THREAD

**Issue by Fjnova** [flutter/flutter#65249] opened 2020-09-04 12:23 UTC
Hello team,

Thank you for making great Flutter framework.

I am trying app with Gitlab pipeline and have 1 issue with flutter v1.20.0 that I can not run this command
```
flutter pub run build_runner build
```
I got erorr message like: 
```
Error: The getter 'externalKeyword' isn't defined for the class 'FieldDeclaration'.
```

I also try some ways like [https://github.com/flutter/flutter/issues/62996](https://github.com/flutter/flutter/issues/62996) and [https://github.com/flutter/flutter/issues/56779](https://github.com/flutter/flutter/issues/56779)
But it sometime happens on my local environment, and always happens on gitlab pipepine

This is my yaml configuration file:
```image: cirrusci/flutter:1.20.0
stages:
  - z
  - t

before_script:
  - flutter clean
  - flutter pub get
  - flutter pub run build_runner build
``` 

Here is more detailed info:
<details>
  <summary>Logs</summary>

```
PS D:\xx> flutter pub run build_runner build
Precompiling executable...
Failed to precompile build_runner:build_runner:
/D:/flutter/.pub-cache/hosted/pub.dartlang.org/dart_style-1.3.7/lib/src/source_visitor.dart:1428:21: Error: The getter 'externalKeyword' isn't defined for the class 'FieldDeclaration'.
 - 'FieldDeclaration' is from 'package:analyzer/dart/ast/ast.dart' ('/D:/flutter/.pub-cache/hosted/pub.dartlang.org/analyzer-0.39.14/lib/dart/ast/ast.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'externalKeyword'.
      modifier(node.externalKeyword);
                    ^^^^^^^^^^^^^^^
/D:/flutter/.pub-cache/hosted/pub.dartlang.org/dart_style-1.3.7/lib/src/source_visitor.dart:1430:21: Error: The getter 'abstractKeyword' isn't defined for the class 'FieldDeclaration'.
 - 'FieldDeclaration' is from 'package:analyzer/dart/ast/ast.dart' ('/D:/flutter/.pub-cache/hosted/pub.dartlang.org/analyzer-0.39.14/lib/dart/ast/ast.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'abstractKeyword'.
      modifier(node.abstractKeyword);
                    ^^^^^^^^^^^^^^^
/D:/flutter/.pub-cache/hosted/pub.dartlang.org/dart_style-1.3.7/lib/src/source_visitor.dart:2618:21: Error: The getter 'externalKeyword' isn't defined for the class 'TopLevelVariableDeclaration'.
 - 'TopLevelVariableDeclaration' is from 'package:analyzer/dart/ast/ast.dart' ('/D:/flutter/.pub-cache/hosted/pub.dartlang.org/analyzer-0.39.14/lib/dart/ast/ast.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'externalKeyword'.
      modifier(node.externalKeyword);
                    ^^^^^^^^^^^^^^^
pub finished with exit code 1
```

```
```

```
PS D:\xx> flutter doctor -v                                                                         
[√] Flutter (Channel unknown, 1.20.0, on Microsoft Windows [Version 10.0.18362.720], locale en-US)
    • Flutter version 1.20.0 at D:\flutter
    • Framework revision 840c9205b3 (4 weeks ago), 2020-08-04 20:55:12 -0700
    • Engine revision c8e3b94853
    • Dart version 2.9.0


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at D:\Android\Sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = D:\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code, 64-bit edition (version 1.44.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.12.2

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```

</details>

Thank you

**Comment by pedromassangocode** [comment] 2020-09-04 12:33
Hi @Fjnova 
From what I can see, the issue is related to build_runner package rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/dart-lang/build/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by pedromassangocode** 2020-09-04 12:33 UTC

**Comment by Fjnova** [comment] 2020-09-04 13:35
thanks @pedromassangocode
