### ISSUE TITLE
Hide/Show FlutterFragment not working

### ISSUE THREAD

**Issue by zhuyonghao** [flutter/flutter#58848] opened 2020-06-06 06:08 UTC
Flutterfragment cannot hide

Android Fragment can hide，so it is error

**Comment by shadownokill** [comment] 2020-06-08 03:28
在android viewpager中使用flutterfragment, 会出现滑动页面后flutterfragment残留在屏幕上,并且变形的问题

**Comment by TahaTesser** [comment] 2020-06-08 09:14
I can reproduce this issue

Calling `fragmentManager.beginTransaction().hide(cachedFlutterFragment)`, doesn't hide
or using `android:visibility="invisible"` still shows flutterfragment at run and doesn't show hide it when android:visibility to false in kotlin

![Screenshot_1591607536](https://user-images.githubusercontent.com/48603081/84013329-656c3400-a996-11ea-81f4-58c24aaf9da6.png)

```
class CachedEngineActivity  : FragmentActivity() {

    companion object {
        private const val TAG_FLUTTER_FRAGMENT = "flutter_fragment"

    }

    private var flutterFragment: FlutterFragment? = null

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.cached_activity)

        val fragmentManager: FragmentManager = supportFragmentManager
        val showButton =  findViewById<Button>(R.id.showCachedFragment)

        flutterFragment = fragmentManager
            .findFragmentByTag(TAG_FLUTTER_FRAGMENT) as FlutterFragment?

        if (flutterFragment == null) {
            var cachedFlutterFragment = FlutterFragment.withCachedEngine(ENGINE_ID).build<FlutterFragment>()


            fragmentManager
                .beginTransaction()
                .add(
                    R.id.fragment_container_cached,
                    cachedFlutterFragment,
                    TAG_FLUTTER_FRAGMENT
                )
                .commit()

            showButton.setOnClickListener {
                fragmentManager.beginTransaction().hide(cachedFlutterFragment)
                print("test")
            }
        }

    }
```

<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel master, 1.19.0-4.0.pre.99, on Mac OS X 10.15.5 19F101,
    locale en-GB)
    • Flutter version 1.19.0-4.0.pre.99 at /Users/tahatesser/Code/flutter_master
    • Framework revision 7467492444 (3 hours ago), 2020-06-08 02:03:01 -0400
    • Engine revision dfdd88deb7
    • Dart version 2.9.0 (build 2.9.0-13.0.dev 87c5e3612b)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (4 available)
    • Android SDK built for x86 64 • emulator-5554 • android-x64    • Android 9
      (API 28) (emulator)
    • macOS                        • macOS         • darwin-x64     • Mac OS X
      10.15.5 19F101
    • Web Server                   • web-server    • web-javascript • Flutter
      Tools
    • Chrome                       • chrome        • web-javascript • Google
      Chrome 83.0.4103.97

• No issues found!

``` 

</details> 

either option don't work

**Comment by jason-simmons** [comment] 2020-06-08 23:06
This may be caused by the interaction between fragments and SurfaceViews.

Does this work if you create the fragment using `RenderMode.texture`?

**Comment by shadownokill** [comment] 2020-06-09 00:27
I&nbsp;had&nbsp;try&nbsp;it.&nbsp;But&nbsp;Texture&nbsp;mode&nbsp;will&nbsp;cause&nbsp;a&nbsp;crash&nbsp;😱.&nbsp;



---Original---

**Comment by shadownokill** [comment] 2020-06-09 08:39
I had try it. But Texture mode will cause a crash.

**Comment by TahaTesser** [comment] 2020-07-01 09:30
@zhuyonghao 
Since the issue is no longer reproducible and works based on the code sample i have provided earlier 

Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

**Closed by TahaTesser** 2020-07-01 09:30 UTC
Labels: in triage, waiting for customer response

**Comment by panda912** [comment] 2020-07-04 11:06
I'm facing the same problem, and I'm sure I called `commit()`.

**Comment by TahaTesser** [comment] 2020-07-06 09:14
@panda912 
Please upgrade to latest `master` and try again

**Comment by panda912** [comment] 2020-08-17 01:19
it still does not work.

**Comment by TahaTesser** [comment] 2020-08-18 10:53
Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
