### ISSUE TITLE
Flutter web textfield disappearing or taking so much time to transition between two textfields  

### ISSUE THREAD

**Issue by anass-naoushi** [flutter/flutter#87662] opened 2021-08-04 15:56 UTC
I have a flutter app that is running across android,ios and web. I have different pages that contain multiple textfields for the user to fill his info and signup/login. The textfields display no problems in the apk or the .app in ios. The main problem is in web when opened from an iphone (ios) . The behavior is not consistent on all iphones but the main problem is that  either the texfields flicker/disappear or the transition from a textfield to another takes about 12 seconds. A video is attached below to show the behavior  on iphone 6 safari browser (the same happens with chrome). Other iphones show a delay between the transition from a textfield to another(tested on iphone 11)

<details> 
<summary>flutter doctor -v</summary> 
	
```console

[√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.19042.1110], locale en-US)
    • Flutter version 2.2.3 at D:\flutter-src\flutter
    • Framework revision f4abaa0735 (5 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Alpha\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop for Windows (Visual Studio Community 2019 16.3.7)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.3.29424.173
    • Windows 10 SDK version 10.0.17763.0
    X Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop
      development with C++" workload, and include these components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19042.1110]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 92.0.4515.131
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 92.0.902.55

! Doctor found issues in 1 category.
```

</details>

https://user-images.githubusercontent.com/63854743/128207268-42c0b5ab-f871-453b-bd06-d807112920ff.mp4

**Comment by TahaTesser** [comment] 2021-08-05 10:06
Hi @anass-naoushi 
Can you please provide a complete reproducible minimal code sample,
Thank you

**Comment by anass-naoushi** [comment] 2021-08-05 12:43
@TahaTesser this is almost the same code being used, I tried to compile as much code as possible in one page. In order for this to work you need to use the universal html package https://pub.dev/packages/universal_html
```
import 'dart:io';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:universal_html/html.dart' as html;



class RegisterName extends StatefulWidget {
   static String route='/signup';
  @override
  _RegisterNameState createState() => _RegisterNameState();
}

class _RegisterNameState extends State<RegisterName> {
  Map userdata={};
  final formKey = GlobalKey<FormState>();
  
  @override
  Widget build(BuildContext context) {
    return CustomDisplay(
      child: Scaffold(
      body: Form(
        key: formKey,
        child: ListView(
          padding: EdgeInsets.all(0),
          children: [
           
            Container(
              height: MediaQuery.of(context).size.height,
              child:   Padding(
              padding: EdgeInsets.all(15),
              child: Column(
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                 Column(
                   children: [
                     Padding(
                       padding: const EdgeInsets.only(top:55.0),
                       child: GestureDetector(
                         child: Row(
                children: [
                  Icon(Icons.arrow_back_ios,color: Theme.of(context).primaryColor,),
                  Text("LocaleKeys.back.tr()",style:Theme.of(context).textTheme.subtitle2)
                ],
              ),
              onTap: (){
                          Navigator.pop(context);
                    },
                       ),
                     ),
                      Row(
                        mainAxisAlignment: MainAxisAlignment.start,
                        children: [
                          Text("LocaleKeys.createAccount.tr()",style: TextStyle(fontSize:34,fontWeight: FontWeight.w700,fontFamily: 'Poppins',color: Theme.of(context).textTheme.subtitle2.color),),
                        ],
                      ),
                       Divider(thickness: 1,),
               userdata['profilepicture']==null?  
                GestureDetector(
                  child: Container(
                      height: 100,
                      width: 100,
                      decoration: BoxDecoration(
                        shape: BoxShape.circle,
                        //color: Pigment.fromString('#DBDBDB')
                      ),
                      child: Padding(
                        padding: const EdgeInsets.all(25.0),
                        child: Image.asset('lib/assets/images/camera.png',scale: 2,),
                      ),
                    ),
                    onTap: ()async{
                  
                    },
                ):GestureDetector(
                  child: kIsWeb?
                    Container(
                      height: 100,
                      width: 100,
                      decoration: BoxDecoration(
                        shape: BoxShape.circle,
                        //color: Pigment.fromString('#DBDBDB'),
                        image: DecorationImage(image: MemoryImage(userdata['profilepicture']),fit: BoxFit.cover),
                      ),
                    )
                  :Container(
                      height: 100,
                      width: 100,
                      decoration: BoxDecoration(
                        shape: BoxShape.circle,
                       // color: Pigment.fromString('#DBDBDB'),
                        image: DecorationImage(image:Image.file(userdata['profilepicture']).image
                      ,fit: BoxFit.cover),
                      ),
                    ),
                    onTap: ()async{
                      
                    },
                )
                ,
                  Padding(
                    padding: const EdgeInsets.only(top:8.0),
                    child: Text("LocaleKeys.profilePicture.tr()",style: TextStyle(fontSize: 11,color: Theme.of(context).textTheme.subtitle2.color),textAlign: TextAlign.center,),
                  ),
                    Padding(
                      padding: const EdgeInsets.only(top:15.0,bottom: 15),
                      child: Container(
                        decoration: BoxDecoration(
                          border: Border.all(color:Colors.blue),
                          borderRadius: BorderRadius.circular(12)

                        ),
                        child: ClipRRect(
                          borderRadius: BorderRadius.circular(12),
                          child: TextFormField(
                              decoration: InputDecoration(
                                  contentPadding: const EdgeInsets.all(8.0),
                                  border: OutlineInputBorder(
                                    borderRadius: BorderRadius.circular(12.0),
                                  ),
                                  focusedBorder: InputBorder.none,
                                   enabledBorder: InputBorder.none,
                                   errorBorder: InputBorder.none,
                                        disabledBorder: InputBorder.none,
                                       
                                        floatingLabelBehavior:FloatingLabelBehavior.auto,
                                  labelText: "LocaleKeys.firstName.tr()",
                                  fillColor: Colors.white,
                                  filled: true
                                  ),
                                  validator: (String name){
                                    //return Validation.isNotempty(name, LocaleKeys.firstName.tr());
                                  },
                                  onChanged: (name){
                                    if(name==null||name.trim().isEmpty){
                                      userdata.remove('name');
                                    }else{
                                      userdata['name']=name.trim();
                                    }
                                    setState(() {
                                                                    
                                                                  });
                                  },
                                  ),
                        ),
                      ),
                    ),
                    Container(
                      decoration: BoxDecoration(
                        border: Border.all(color:Colors.blue),
                        borderRadius: BorderRadius.circular(12)

                      ),
                      child: ClipRRect(
                        borderRadius: BorderRadius.circular(12),
                        child: TextFormField(
                            decoration: InputDecoration(
                                contentPadding: const EdgeInsets.all(8.0),
                                border: OutlineInputBorder(
                                  borderRadius: BorderRadius.circular(12.0),
                                ),
                                focusedBorder: InputBorder.none,
                                 enabledBorder: InputBorder.none,
                                 errorBorder: InputBorder.none,
                                      disabledBorder: InputBorder.none,
                                     
                                      floatingLabelBehavior:FloatingLabelBehavior.auto,
                                labelText: "LocaleKeys.lastName.tr()",
                                fillColor: Colors.white,
                                filled: true
                                ),
                                validator: (String lastname){
                                  //return Validation.isNotempty(lastname, LocaleKeys.lastName.tr());
                                },
                                onChanged: (lastname){
                                   if(lastname==null||lastname.trim().isEmpty){
                                      userdata.remove('lastname');
                                    }else{
                                      userdata['lastname']=lastname.trim();
                                    }
                                    setState(() {
                                                                    
                                                                  });
                                },
                                ),
                      ),
                    ),
                    Padding(
                      padding: const EdgeInsets.only(bottom:15.0,top:15),
                      child: Container(
                        decoration: BoxDecoration(
                          color: Colors.white,
                          border: Border.all(color:Colors.blue),
                          borderRadius: BorderRadius.circular(12)

                        ),
                        child: ClipRRect(
                          borderRadius: BorderRadius.circular(12),
                          child: TextFormField(
                            keyboardType: TextInputType.phone,
                              decoration: InputDecoration(
                                  contentPadding: const EdgeInsets.all(8.0),
                                  border: OutlineInputBorder(
                                    borderRadius: BorderRadius.circular(12.0),
                                  ),
                                 focusedBorder: InputBorder.none,
                                   enabledBorder: InputBorder.none,
                                   errorBorder: InputBorder.none,
                                   focusedErrorBorder: InputBorder.none,
                                    disabledBorder: InputBorder.none,
                                       
                                        floatingLabelBehavior:FloatingLabelBehavior.auto,
                                  labelText: "LocaleKeys.phoneNumber.tr()",
                                  fillColor: Colors.white,
                                  filled: true
                                  ),
                                  validator: (String phonenumber){
                                      //return Validation.phonenumbervalid(phonenumber);
                                  },
                                  onChanged: (phonenumber){
                                     if(phonenumber==null||phonenumber.trim().isEmpty){
                                        userdata.remove('phonenumber');
                                      }else{
                                        userdata['phonenumber']=phonenumber.trim();
                                      }
                                      setState(() {
                                                                      
                                                                    });
                                  },
                                  ),
                        ),
                      ),
                    ),
                   ],
                 ),
                 CustomButton(text: "LocaleKeys.continueText.tr()", function:!(userdata.keys.contains('name')&&userdata.keys.contains('lastname')&&
                 userdata.keys.contains('phonenumber'))?null:(){
                    if(formKey.currentState.validate()){
    //                    Navigator.push(
    // context,
    // MaterialPageRoute(builder: (context) =>RegisterAccount(userdata: userdata)));
                    }
  
                 })
                  ],
              ),
          ),
            )
            ]
        ),
      ),
    )
    );
  }
}

class CustomButton extends StatefulWidget {
  final String text;
  final Function function;

  const CustomButton({Key key, @required this.text, @required this.function}) : super(key: key);
  @override
  _CustomButtonState createState() => _CustomButtonState();
}

class _CustomButtonState extends State<CustomButton> {
  @override
  Widget build(BuildContext context) {
    return ElevatedButton(
      style: ButtonStyle(
        shape:  MaterialStateProperty.all<RoundedRectangleBorder>(
    RoundedRectangleBorder(
      borderRadius: BorderRadius.circular(12.0),
      //side: BorderSide(color: Colors.red)
    )
  )
      ),
      child: Padding(
        padding: const EdgeInsets.all(14.0),
        child: Row(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Text(widget.text,style:TextStyle(fontSize: 17,fontFamily: 'Poppins',fontWeight: FontWeight.w600)),
          ],
        ),
      ),
      onPressed: widget.function,
    );
  }
}
class CustomDisplay extends StatefulWidget {
  final bool forceCustomWidth;
  final Widget child;
  final bool showmodal;
  final double modalheightPercentage;
  const CustomDisplay({Key key, this.forceCustomWidth, @required this.child,this.showmodal=false,this.modalheightPercentage}) : super(key: key);

  @override
  _CustomDisplayState createState() => _CustomDisplayState();
}

class _CustomDisplayState extends State<CustomDisplay> {
  @override
  Widget build(BuildContext context) {
    return Builder(
      builder: (context){
        if(normalview()){
          print('normal view');
          if(widget.modalheightPercentage!=null){
            print('display one');
            return Container(
        height: MediaQuery.of(context).size.height*widget.modalheightPercentage,
        child: widget.child,
      );
          }else{
            print('display two');
            return  widget.child;
          }
        }else{
          print('not normal view');
          if(!widget.showmodal){
            print('display three');
            return  FittedBox(
      fit: BoxFit.scaleDown,
      child:  Container(
        color: Colors.transparent,
        height: MediaQuery.of(context).size.height,
        width: detectwidth(widget.forceCustomWidth, widget.showmodal,context),
        child: widget.child,
      ),
    );
          }else{
            print('display four');
            return ClipRRect(
       borderRadius: BorderRadius.only(topLeft: Radius.circular(12),topRight: Radius.circular(12)),
      child: FittedBox(
        fit: BoxFit.scaleDown,
        child: Container(
          color: Colors.white,
            height:  MediaQuery.of(context).size.height*(widget.modalheightPercentage?? 0.75),
            width: detectwidth(widget.forceCustomWidth, widget.showmodal,context),
            child: widget.child,
          ),
      ),
    );
          }
        }
      },
    );
  }
}
 double detectwidth(bool forceCustomWidth,bool showmodal,context){
    if(forceCustomWidth==true){
      return 375.0;
    }else if(kIsWeb){
      final userAgent = html.window.navigator.userAgent.toString().toLowerCase();
      if(userAgent.contains('iphone') || userAgent.contains('ipad')||userAgent.contains('android')){
        return MediaQuery.of(context).size.width;
      }else{
        if(showmodal){
          return 375;
        }else{
           return 375;
        }
      }
    }else{
      return MediaQuery.of(context).size.width;
    }
  }
   bool normalview(){
   if(kIsWeb){
      final userAgent = html.window.navigator.userAgent.toString().toLowerCase();
      if(userAgent.contains('iphone') || userAgent.contains('ipad')||userAgent.contains('android')){
        return true;
      }else{
        return false;
      }
    }else{
      return true;
    }
  }
```

**Comment by TahaTesser** [comment] 2021-08-06 08:58
Hi @anass-naoushi 
Can you please provide a minimal reproducible code sample that does not use 3rd party plugins
Thank you

**Comment by anass-naoushi** [comment] 2021-08-06 12:22
@TahaTesser here is another code sample, it should reflect the phone UI as intended because I removed the 3rd party plugin so if you run it on desktop web you may have different results(the main purpose of the 3rd party plugin was to detect the device the site was opened on in order to maintain the phone shape irrespective of the platform)
```
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';



class RegisterName extends StatefulWidget {
   static String route='/signup';
  @override
  _RegisterNameState createState() => _RegisterNameState();
}

class _RegisterNameState extends State<RegisterName> {
  Map userdata={};
  final formKey = GlobalKey<FormState>();
  
  @override
  Widget build(BuildContext context) {
    return Scaffold(
    body: Form(
      key: formKey,
      child: ListView(
        padding: EdgeInsets.all(0),
        children: [
         
          Container(
            height: MediaQuery.of(context).size.height,
            child:   Padding(
            padding: EdgeInsets.all(15),
            child: Column(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
               Column(
                 children: [
                   Padding(
                     padding: const EdgeInsets.only(top:55.0),
                     child: GestureDetector(
                       child: Row(
              children: [
                Icon(Icons.arrow_back_ios,color: Theme.of(context).primaryColor,),
                Text("LocaleKeys.back.tr()",style:Theme.of(context).textTheme.subtitle2)
              ],
            ),
            onTap: (){
                        Navigator.pop(context);
                  },
                     ),
                   ),
                    Row(
                      mainAxisAlignment: MainAxisAlignment.start,
                      children: [
                        Text("LocaleKeys.createAccount.tr()",style: TextStyle(fontSize:34,fontWeight: FontWeight.w700,fontFamily: 'Poppins',color: Theme.of(context).textTheme.subtitle2.color),),
                      ],
                    ),
                     Divider(thickness: 1,),
             userdata['profilepicture']==null?  
              GestureDetector(
                child: Container(
                    height: 100,
                    width: 100,
                    decoration: BoxDecoration(
                      shape: BoxShape.circle,
                      //color: Pigment.fromString('#DBDBDB')
                    ),
                    child: Padding(
                      padding: const EdgeInsets.all(25.0),
                      child: Image.asset('lib/assets/images/camera.png',scale: 2,),
                    ),
                  ),
                  onTap: ()async{
                
                  },
              ):GestureDetector(
                child: kIsWeb?
                  Container(
                    height: 100,
                    width: 100,
                    decoration: BoxDecoration(
                      shape: BoxShape.circle,
                      //color: Pigment.fromString('#DBDBDB'),
                      image: DecorationImage(image: MemoryImage(userdata['profilepicture']),fit: BoxFit.cover),
                    ),
                  )
                :Container(
                    height: 100,
                    width: 100,
                    decoration: BoxDecoration(
                      shape: BoxShape.circle,
                     // color: Pigment.fromString('#DBDBDB'),
                      image: DecorationImage(image:Image.file(userdata['profilepicture']).image
                    ,fit: BoxFit.cover),
                    ),
                  ),
                  onTap: ()async{
                    
                  },
              )
              ,
                Padding(
                  padding: const EdgeInsets.only(top:8.0),
                  child: Text("LocaleKeys.profilePicture.tr()",style: TextStyle(fontSize: 11,color: Theme.of(context).textTheme.subtitle2.color),textAlign: TextAlign.center,),
                ),
                  Padding(
                    padding: const EdgeInsets.only(top:15.0,bottom: 15),
                    child: Container(
                      decoration: BoxDecoration(
                        border: Border.all(color:Colors.blue),
                        borderRadius: BorderRadius.circular(12)

                      ),
                      child: ClipRRect(
                        borderRadius: BorderRadius.circular(12),
                        child: TextFormField(
                            decoration: InputDecoration(
                                contentPadding: const EdgeInsets.all(8.0),
                                border: OutlineInputBorder(
                                  borderRadius: BorderRadius.circular(12.0),
                                ),
                                focusedBorder: InputBorder.none,
                                 enabledBorder: InputBorder.none,
                                 errorBorder: InputBorder.none,
                                      disabledBorder: InputBorder.none,
                                     
                                      floatingLabelBehavior:FloatingLabelBehavior.auto,
                                labelText: "LocaleKeys.firstName.tr()",
                                fillColor: Colors.white,
                                filled: true
                                ),
                                validator: (String name){
                                  //return Validation.isNotempty(name, LocaleKeys.firstName.tr());
                                },
                                onChanged: (name){
                                  if(name==null||name.trim().isEmpty){
                                    userdata.remove('name');
                                  }else{
                                    userdata['name']=name.trim();
                                  }
                                  setState(() {
                                                                  
                                                                });
                                },
                                ),
                      ),
                    ),
                  ),
                  Container(
                    decoration: BoxDecoration(
                      border: Border.all(color:Colors.blue),
                      borderRadius: BorderRadius.circular(12)

                    ),
                    child: ClipRRect(
                      borderRadius: BorderRadius.circular(12),
                      child: TextFormField(
                          decoration: InputDecoration(
                              contentPadding: const EdgeInsets.all(8.0),
                              border: OutlineInputBorder(
                                borderRadius: BorderRadius.circular(12.0),
                              ),
                              focusedBorder: InputBorder.none,
                               enabledBorder: InputBorder.none,
                               errorBorder: InputBorder.none,
                                    disabledBorder: InputBorder.none,
                                   
                                    floatingLabelBehavior:FloatingLabelBehavior.auto,
                              labelText: "LocaleKeys.lastName.tr()",
                              fillColor: Colors.white,
                              filled: true
                              ),
                              validator: (String lastname){
                                //return Validation.isNotempty(lastname, LocaleKeys.lastName.tr());
                              },
                              onChanged: (lastname){
                                 if(lastname==null||lastname.trim().isEmpty){
                                    userdata.remove('lastname');
                                  }else{
                                    userdata['lastname']=lastname.trim();
                                  }
                                  setState(() {
                                                                  
                                                                });
                              },
                              ),
                    ),
                  ),
                  Padding(
                    padding: const EdgeInsets.only(bottom:15.0,top:15),
                    child: Container(
                      decoration: BoxDecoration(
                        color: Colors.white,
                        border: Border.all(color:Colors.blue),
                        borderRadius: BorderRadius.circular(12)

                      ),
                      child: ClipRRect(
                        borderRadius: BorderRadius.circular(12),
                        child: TextFormField(
                          keyboardType: TextInputType.phone,
                            decoration: InputDecoration(
                                contentPadding: const EdgeInsets.all(8.0),
                                border: OutlineInputBorder(
                                  borderRadius: BorderRadius.circular(12.0),
                                ),
                               focusedBorder: InputBorder.none,
                                 enabledBorder: InputBorder.none,
                                 errorBorder: InputBorder.none,
                                 focusedErrorBorder: InputBorder.none,
                                  disabledBorder: InputBorder.none,
                                     
                                      floatingLabelBehavior:FloatingLabelBehavior.auto,
                                labelText: "LocaleKeys.phoneNumber.tr()",
                                fillColor: Colors.white,
                                filled: true
                                ),
                                validator: (String phonenumber){
                                    //return Validation.phonenumbervalid(phonenumber);
                                },
                                onChanged: (phonenumber){
                                   if(phonenumber==null||phonenumber.trim().isEmpty){
                                      userdata.remove('phonenumber');
                                    }else{
                                      userdata['phonenumber']=phonenumber.trim();
                                    }
                                    setState(() {
                                                                    
                                                                  });
                                },
                                ),
                      ),
                    ),
                  ),
                 ],
               ),
               CustomButton(text: "LocaleKeys.continueText.tr()", function:!(userdata.keys.contains('name')&&userdata.keys.contains('lastname')&&
               userdata.keys.contains('phonenumber'))?null:(){
                  if(formKey.currentState.validate()){
    //                    Navigator.push(
    // context,
    // MaterialPageRoute(builder: (context) =>RegisterAccount(userdata: userdata)));
                  }
  
               })
                ],
            ),
        ),
          )
          ]
      ),
    ),
    );
  }
}

class CustomButton extends StatefulWidget {
  final String text;
  final Function function;

  const CustomButton({Key key, @required this.text, @required this.function}) : super(key: key);
  @override
  _CustomButtonState createState() => _CustomButtonState();
}

class _CustomButtonState extends State<CustomButton> {
  @override
  Widget build(BuildContext context) {
    return ElevatedButton(
      style: ButtonStyle(
        shape:  MaterialStateProperty.all<RoundedRectangleBorder>(
    RoundedRectangleBorder(
      borderRadius: BorderRadius.circular(12.0),
      //side: BorderSide(color: Colors.red)
    )
  )
      ),
      child: Padding(
        padding: const EdgeInsets.all(14.0),
        child: Row(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Text(widget.text,style:TextStyle(fontSize: 17,fontFamily: 'Poppins',fontWeight: FontWeight.w600)),
          ],
        ),
      ),
      onPressed: widget.function,
    );
  }
}

 
```

**Comment by anass-naoushi** [comment] 2021-08-08 09:24
@TahaTesser These are also two additional videos from two iphone 11 phones displaying different behavior. One is showing the issue of taking time to go to the next textfield(about 12 seconds) and one is transitioning normally . 

https://user-images.githubusercontent.com/63854743/128627001-07dc3064-66dc-4cbc-bd9c-b58db0a45e83.MP4


https://user-images.githubusercontent.com/63854743/128627217-ccbaafd7-da9c-4e04-b3a9-c29e2df4f4b6.MP4

**Comment by TahaTesser** [comment] 2021-08-09 11:19
HI  @anass-naoushi 
Please reproduce the issue using a minimal sample instead of the existing app. I just tried your code sample on iPhone, couldn't reproduce any text field disappearing 

I am using `flutter build web` (it is on auto by default so it will be HTML renderer for mobile). Which renderer are you using?


https://user-images.githubusercontent.com/48603081/128698606-167c626d-07d6-4840-82e2-f6ece574b9db.mov




<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.22000.120], locale en-US)
    • Flutter version 2.2.3 at C:\Users\Taha\Code\flutter_stable
    • Framework revision f4abaa0735 (6 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\android-sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_SDK_ROOT = C:\Users\Taha\Code\android-sdk
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.10.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.10.31515.178
    • Windows 10 SDK version 10.0.19041.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[✓] VS Code (version 1.59.0)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.25.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22000.120]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 92.0.4515.131
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 92.0.902.67

! Doctor found issues in 1 category.
```

</details>

Please reproduce the issues from https://github.com/flutter/flutter/issues/87662#issuecomment-894768894 using the minimal code sample and to better understand all the issues,  please list the issue and their steps to reproduce along expected results and actual results

Thank you

**Comment by anass-naoushi** [comment] 2021-08-09 13:35
@TahaTesser i understand your explanation but as you have seen in my videos not all iPhones displayed the same behavior.  Some had a bug and some did not have a bug. In my last comment i uploaded two videos showing two iPhones of the same type (iPhone 11) and one had a buggy behavior and the other was perfect.  So the issue here is not clear since you may also not be able to reproduce the issue but the issue exists on other devices.

**Comment by TahaTesser** [comment] 2021-08-10 07:27
Hi @anass-naoushi 
Understandable, can you please both renderers, let me know which one causes the issue? 
`flutter build wen --web-renderer html` and `flutter build wen --web-renderer canvaskit`

**Comment by anass-naoushi** [comment] 2021-08-14 15:09
@TahaTesser  I have tested the builds and the canvaskit solved the flickering issue but the issue if 12 seconds on some iphones while switching between textfields was not solved. I think I will have to investigate on my own to see the problem with certain textfields I am using. Anyways thanks for the advice .

**Comment by TahaTesser** [comment] 2021-08-16 07:11
@anass-naoushi 
Let me know if you isolate the issue and maybe try reproducing on the simulator so I can replicate the issue too
Thank you

**Comment by TahaTesser** [comment] 2021-09-08 09:51
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by TahaTesser** 2021-09-08 09:51 UTC
