### ISSUE TITLE
I get the error "Reload already in progress, ignoring request" after the update.

### ISSUE THREAD

**Issue by rizacantufan** [flutter/flutter#56742] opened 2020-05-09 02:06 UTC
After updating Flutter, VSCode constantly gives this error. It is very tiring to stop the project and start it again.

I cleaned the memory (flutter clean). The problem still continues.

I reinstalled VScode again, the problem was not fixed. I reinstalled Flutter (beta for the web). The problem has not improved.

![Ekran Görüntüsü (1)](https://user-images.githubusercontent.com/5313560/81461080-1de56300-91b2-11ea-8e7b-726bfb7eaec0.png)

After receiving this error, the screen stops working ("Syncing files to Device Chrome ...")

What is the reason of this problem?

**in pubspec.yaml**

`environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  flutter_svg: ^0.17.4
  html: 0.14.0+3
  responsive_builder: ^0.1.5
  settings_ui: ^0.2.0
  flutter_map: ^0.9.0
  latlong: ^0.6.1
  extended_tabs: ^0.2.3
  flutter_auth: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter`

Flutter (Channel beta, v1.17.0, on Microsoft Windows [Version 10.0.18363.778], locale tr-TR)
VS Code (version 1.45.0)

**Comment by owenkealey** [comment] 2020-05-09 05:32
Im not a flutter dev but there seems to be ALOT of issues with 1.17 personally I rolled back.

**Comment by TahaTesser** [comment] 2020-05-11 07:33
Hi @rizacantufan 
Does this happen on a new project? Please a try a new project
can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by TahaTesser** [comment] 2020-06-03 11:42
Without additional information we are unfortunately not sure how to resolve this issue.
We are therefore reluctantly going to close this bug for now.
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.

**Closed by TahaTesser** 2020-06-03 11:42 UTC
