### ISSUE TITLE
Flutter Web : Expected a value of type 'SkDeletable', but got one of type 'Null'

### ISSUE THREAD

**Issue by kiaxseventh** [flutter/flutter#77258] opened 2021-03-04 16:45 UTC
hello 
I updated my filter version
but now i have problem when use Getx raw Snackbar

this issue just on the flutter web 

[this issue on Getx repository](https://github.com/jonataslaw/getx/issues/1145)

**Flutter Version:**
Flutter 2.0.0 • channel stable
Flutter 2.0.0 • channel beta
Flutter 1.26.0-17.8.pre • channel beta

**Getx Version:**
3.25.6
3.25.5
3.25.4
3.25.3
3.25.2
3.25.1
3.25.0
3.24.0
3.23.1
3.23.0

  <summary>
  
  ======== Exception caught by widgets library =======================================================
The following TypeErrorImpl was thrown building FutureBuilder(dirty, state: _FutureBuilderState#0a48a):
Expected a value of type 'SkDeletable', but got one of type 'Null'

The relevant error-causing widget was:
GetMaterialApp file:///D:/Flutter/Project/getx_snackbar_test/lib/main.dart:12:12
When the exception was thrown, this was the stack:
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/internal/js_dev_runtime/private/ddc_runtime/errors.dart 236:49 throw
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 84:3 castError
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/types.dart 266:34 as
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/canvaskit/skia_object_cache.dart 146:55 new
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/canvaskit/image_filter.dart 26:3 __
  
  </summary>

```
```

[√] Flutter (Channel stable, 2.0.0, on Microsoft Windows [Version 10.0.19041.804], locale en-US)
    • Flutter version 2.0.0 at D:\Flutter\sdk\flutter
    • Framework revision 60bd88df91 (23 hours ago), 2021-03-03 09:13:17 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at D:\Android\sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = D:\Android\sdk
    • Java binary at: D:\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at D:\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Ultimate Edition (version 2020.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2020.1.3
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code, 64-bit edition (version 1.47.3)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.13.2

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 88.0.4324.190
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 88.0.705.81

• No issues found!

```
```

</details>

**Comment by yjbanov** [comment] 2021-03-04 17:45
Something's wrong with memory management in `ImageFilter`. It's trying to garbage-collect `null`. Does this problem happen only in `--debug` mode, or also in `--release` and `--profile`?

**Comment by kiaxseventh** [comment] 2021-03-04 18:04
thank you dear @yjbanov 
can you give me command for run web build --debug or --release or --profile for fast run without upload on host for fast test ?

**Comment by yjbanov** [comment] 2021-03-04 18:05
Here you go:

`flutter run -d chrome --debug`
`flutter run -d chrome --profile`
`flutter run -d chrome --release`

**Comment by kiaxseventh** [comment] 2021-03-04 18:16
with --debug  have same issue

but with --profile and --release does not have any problem

**Comment by yjbanov** [comment] 2021-03-04 19:13
Thanks for confirming. It could be that we're a little too aggressive with assertions, but it could also indicate a memory leak. We'll have a look. Thanks for reporting!

**Comment by ArchangelXu** [comment] 2021-03-25 06:00
I engaged this error after I upgraded Flutter version to 2.1.0. seems a filter stuff...
I changed from
```
ClipRect(
      child: BackdropFilter(
        filter: ImageFilter.blur(sigmaX: blurStrength, sigmaY: blurStrength),
        child: Container(
          width: size,
          height: size,
          color: Colors.transparent,
        ),
      ),
    )
```
to
```
ImageFiltered(
          imageFilter: ImageFilter.blur(
              sigmaX: blurStrength, sigmaY: blurStrength),
          child: Image.network(
            post.getBackgroundUrl() ?? "",
            fit: BoxFit.cover,
          ) 
      )
```
and everything is fine.
Maybe this information is helpful...

**Comment by darshankawar** [comment] 2021-04-14 11:53
@kiaxseventh 
Tried the code sample mentioned [here](https://github.com/jonataslaw/getx/issues/1145#issue-821797728) using latest stable on web but didn't see the error. Tapping on the button shows `Hi` in the appbar properly.

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.0.4, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.0.4 at /Users/dhs/documents/fluttersdk/flutter
    • Framework revision b1395592de (7 days ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)    

[✓] VS Code (version 1.55.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (3 available)
	  • SM A260G (mobile)            • 5200763ebcfa861f • android-arm    • Android
      8.1.0 (API 27)
    • Darshan's iphone (mobile) • 21150b119064aecc249dfcfe05e259197461ce23 • ios
      • iOS 14.4.1
    • macOS (desktop)           • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)              • chrome                                   •
      web-javascript • Google Chrome 89.0.4389.114

! Doctor found issues in 1 category.

```

</details>

Can you upgrade to latest stable and latest getX plugin version and try again to see if issue persists at your end ?

**Comment by ziaratban** [comment] 2021-04-18 15:07
I have same issue.
I found a clue.

```dart
void main() => runApp(
  new MaterialApp(
    home: new BackdropFilter(
      filter: ImageFilter.blur(sigmaX: 0, sigmaY: 0), // >>> SkDeletable error
      child: new Container(
        color: Colors.white,
        child: new Text('test'),
      ),
    ),
  )
);
```

I get this error when I set both parameters to zero. (`sigmaX` & `sigmaY`)

**Comment by pedromassangocode** [comment] 2021-05-12 11:35
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2021-05-12 11:35 UTC
Labels: P3, e: web_canvaskit, engine, severe: crash, waiting for customer response

**Comment by arualana** [comment] 2021-06-23 02:38
This is happening again (flutter web)
[✓] Flutter (Channel master, 2.3.0-17.0.pre.416, on Linux Mint 20.1 5.4.0-58-generic, locale en_US.UTF-8)

**Comment by mauricioluz** [comment] 2021-06-25 22:02
Yes, this is happening again.
Flutter channel Master 2.3.0-17.0.pre.520

**Comment by roked** [comment] 2021-07-14 14:17
I have the same issue with the flutter_neumorphic. In --release, the error is not presented, and also if I open the --debug app in Safari the error is not presented. I assume the issue is with Chrome (again).
