### ISSUE TITLE
Text Selection Toolbar options cut off with Large Display settings

### ISSUE THREAD

**Issue by dannyvalentesonos** [flutter/flutter#44005] opened 2019-11-01 18:37 UTC
Tested on Android, but I assume this happens on iOS as well, when Large Display setting is used (in Settings -> Display), Text Selection toolbar options get cut off seeing the screen real estate is too small.

**This is a flutter app running on a phone with Large Display settings:**

![flutter_cutoff](https://user-images.githubusercontent.com/40898687/68047345-8c51e180-fcb4-11e9-8c53-ff11c064d62f.png)

**And this is a normal Android app running on the same phone with the same Large Display settings:**

![android_app_no_cutoff_1](https://user-images.githubusercontent.com/40898687/68047559-11d59180-fcb5-11e9-8b4e-d5b4fbd75907.png)

![android_app_no_cutoff_2](https://user-images.githubusercontent.com/40898687/68047563-1437eb80-fcb5-11e9-9246-8830aeac270b.png)

**Comment by dannyvalentesonos** [comment] 2019-11-01 18:38
The Android app uses the overflow menu for extra items, and it also has less spacing between items in this case.

**Comment by justinmc** [comment] 2019-11-13 17:51
I'm going to close this as a duplicate of https://github.com/flutter/flutter/issues/35826, but let me know if that issue is missing anything from here.  That issue is mainly about other locales, so I will mention the large display settings thing that you bring up.

**Closed by justinmc** 2019-11-13 17:51 UTC
Labels: a: fidelity, a: text input, f: material design, framework
