### ISSUE TITLE
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0 Cause: null pointer dereference

### ISSUE THREAD

**Issue by NaoKreuzeder** [flutter/flutter#149892] opened 2024-06-07 11:41 UTC
### Steps to reproduce

This error happens when i run my app from Android Studio on a Xiaomi Redmi 9C device. 
I could not replicate this error on my other physical devices (Google 8 pro, Huawei Mate 20 pro)

I only experience the crash in profile & release mode. 

I tried to symbolize the crash log with "dart pub global run symbolizer:symbolize" but i cannot get an output.
In the Terminal it shows:
INFO: 2024-06-07 13:27:11.325719: checking for llvm-{symbolizer,readobj,objdump} in $PATH
INFO: 2024-06-07 13:27:11.337827: checking for llvm-{symbolizer,readobj,objdump} in tools/android-ndk/toolchains/llvm/prebuilt/darwin-x86_64/bin/

and then nothing happens.

### Expected results

App runs without crash.

### Actual results

App crashes when ran from Android Studio in profile or release mode.

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
F/libc    ( 2202): Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0 in tid 2366 (1.ui), pid 2202 (anokae.shiftmob)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'Redmi/angelica_global/angelica:11/RP1A.200720.011/V12.5.3.0.RCRMIXM:user/release-keys'
Revision: '0'
ABI: 'arm'
Timestamp: 2024-06-07 12:50:56+0200
pid: 2202, tid: 2366, name: 1.ui  >>> com.pattarachanokae.shiftmob <<<
uid: 10260
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
Cause: null pointer dereference
    r0  9b6cf6e0  r1  a49d0b4c  r2  a49d0b4c  r3  00000000
    r4  20000000  r5  00000001  r6  a49d0b4c  r7  a49d0b20
    r8  a49ceecc  r9  a49cee44  r10 9b6cf70c  r11 00000fff
    ip  0000064c  sp  a49cee18  lr  a556d1c1  pc  a558c6ca
backtrace:
      #00 pc 00aae6ca  /data/app/~~UVb2K80H-3CaW1BTIdYChQ==/com.pattarachanokae.shiftmob-sI8VfbsCid9oZfMsQQ71pw==/lib/arm/libflutter.so (BuildId: 52ed653d8850a47098529674d68f80097eb36227)
      #01 pc 0036a7ff  /data/app/~~UVb2K80H-3CaW1BTIdYChQ==/com.pattarachanokae.shiftmob-sI8VfbsCid9oZfMsQQ71pw==/lib/arm/libapp.so (BuildId: 445112cfa22673e42ebd2a85d6fa15f1)
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.22.1, on macOS 14.5 23F79 darwin-arm64, locale de-AT)
    • Flutter version 3.22.1 on channel stable at /Users/naokreuzeder/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a14f74ff3a (2 weeks ago), 2024-05-22 11:08:21 -0500
    • Engine revision 55eae6864b
    • Dart version 3.4.1
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/naokreuzeder/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/naokreuzeder/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)

[✓] Connected device (5 available)
    • LYA L09 (mobile)                • F3R7N19123003087      • android-arm64  • Android 10 (API 29)
    • M2006C3MG (mobile)              • LRTCDE6THACM8H7T      • android-arm    • Android 11 (API 30)
    • macOS (desktop)                 • macos                 • darwin-arm64   • macOS 14.5 23F79 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         • macOS 14.5 23F79 darwin-arm64
    • Chrome (web)                    • chrome                • web-javascript • Google Chrome 125.0.6422.142
    ! Error: Browsing on the local area network for iPhone von Nao. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
    ! Error: Browsing on the local area network for iPad von Naorectbbegyvumkovihbybfubvhhgojkdstfjnoiouuyhkmk. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

</details>

**Comment by darshankawar** [comment] 2024-06-07 12:43
@NaoKreuzeder 
What flutter version is your app on ?
I tried symbolicating with 3.22.1 based on your flutter doctor, but it shows me build-id mismatch.

```
dhs@Dhss-MacBook-Pro ~ % dart pub global run symbolizer:symbolize https://github.com/flutter/flutter/issues/149892#issue-2340257696 "flutter#3.22.1 arm64 release force android"
Building package executable... 
Built symbolizer:symbolize.
INFO: 2024-06-07 18:11:14.702106: checking for llvm-{symbolizer,readobj,objdump} in $PATH
INFO: 2024-06-07 18:11:14.733308: checking for llvm-{symbolizer,readobj,objdump} in tools/android-ndk/toolchains/llvm/prebuilt/darwin-x86_64/bin/
INFO: 2024-06-07 18:11:14.770231: checking for llvm-{symbolizer,readobj,objdump} in /Users/dhs/Library/Android/sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/darwin-x86_64/bin/
INFO: 2024-06-07 18:11:16.220767: downloading /var/folders/w0/6j3m5z913hbd94smbfmz6y6h0000gn/T/symbols-cache/55eae6864b296dd9f43b2cc7577ec256e5c32a8d-android-arm64-release for EngineBuild(engineHash: 55eae6864b296dd9f43b2cc7577ec256e5c32a8d, variant: EngineVariant(os: android, arch: arm64, mode: release))
INFO: 2024-06-07 18:11:16.222998: gsutil cp gs://flutter_infra_release/flutter/55eae6864b296dd9f43b2cc7577ec256e5c32a8d/android-arm64-release/symbols.zip /var/folders/w0/6j3m5z913hbd94smbfmz6y6h0000gn/T/awP199/symbols.zip
INFO: 2024-06-07 18:11:29.081844: Symbolizing using /var/folders/w0/6j3m5z913hbd94smbfmz6y6h0000gn/T/symbols-cache/55eae6864b296dd9f43b2cc7577ec256e5c32a8d-android-arm64-release/libflutter.so

--------------------------------------------------------------------------------
symbolized using symbols for 55eae6864b296dd9f43b2cc7577ec256e5c32a8d android-arm64-release

  #00 0000000000aae6ca <...>/lib/arm/libflutter.so (BuildId: 52ed653d8850a47098529674d68f80097eb36227)
                                                   ??
                                                   ??:0:0
  #01 000000000036a7ff <...>/lib/arm/libapp.so (BuildId: 445112cfa22673e42ebd2a85d6fa15f1)
  
Build-ID mismatch:
  Backtrace refers to 52ed653d8850a47098529674d68f80097eb36227 but we used engine with ad074c0ef7b18624be1126cf4eb7343ec826e01c
```

Also, is that the only log you get ?

**Comment by NaoKreuzeder** [comment] 2024-06-07 13:07
@darshankawar 
I let the app crash again here is the full log from the console.

```
Launching lib/main.dart on M2006C3MG in profile mode...
Running Gradle task 'assembleProfile'...
✓ Built build/app/outputs/flutter-apk/app-profile.apk (36.0MB)
D/FlutterArchivePlugin(11536): onAttachedToEngine - IN
D/FlutterArchivePlugin(11536): doOnAttachedToEngine - IN
D/FlutterArchivePlugin(11536): doOnAttachedToEngine - OUT
D/FlutterArchivePlugin(11536): onAttachedToEngine - OUT
Debug service listening on ws://127.0.0.1:62754/-4T93PDgZJM=/ws
I/flutter (11536): [🌎 Easy Localization] [DEBUG] Localization initialized
I/flutter (11536): [🌎 Easy Localization] [DEBUG] Start
I/flutter (11536): [🌎 Easy Localization] [DEBUG] Init state
I/flutter (11536): [🌎 Easy Localization] [DEBUG] Build
I/flutter (11536): [🌎 Easy Localization] [DEBUG] Init Localization Delegate
I/flutter (11536): [🌎 Easy Localization] [DEBUG] Init provider
I/flutter (11536): [🌎 Easy Localization] [DEBUG] Load Localization Delegate
I/flutter (11536): [🌎 Easy Localization] [DEBUG] Load asset from assets/translations
I/flutter (11536): [🌎 Easy Localization] [DEBUG] Load asset from assets/translations
I/DynamiteModule(11536): Considering local module com.google.android.gms.ads.dynamite:0 and remote module com.google.android.gms.ads.dynamite:241199801
I/DynamiteModule(11536): Selected remote version of com.google.android.gms.ads.dynamite, version >= 241199801
D/DynamitePackage(11536): Instantiated singleton DynamitePackage.
D/DynamitePackage(11536): Instantiating com.google.android.gms.ads.ChimeraMobileAdsSettingManagerCreatorImpl
I/Ads     (11536): Updating ad debug logging enablement.
I/WebViewFactory(11536): Loading com.google.android.webview version 94.0.4606.85 (code 460608530)
W/anokae.shiftmo(11536): Accessing hidden method Landroid/os/Trace;->isTagEnabled(J)Z (greylist, reflection, allowed)
W/anokae.shiftmo(11536): Accessing hidden method Landroid/os/Trace;->traceBegin(JLjava/lang/String;)V (greylist, reflection, allowed)
W/anokae.shiftmo(11536): Accessing hidden method Landroid/os/Trace;->traceEnd(J)V (greylist, reflection, allowed)
W/anokae.shiftmo(11536): Accessing hidden method Landroid/os/Trace;->asyncTraceBegin(JLjava/lang/String;I)V (greylist, reflection, allowed)
W/anokae.shiftmo(11536): Accessing hidden method Landroid/os/Trace;->asyncTraceEnd(JLjava/lang/String;I)V (greylist, reflection, allowed)
I/cr_WVCFactoryProvider(11536): Loaded version=94.0.4606.85 minSdkVersion=29 isBundle=false multiprocess=true packageId=2
I/anokae.shiftmo(11536): Waiting for a blocking GC ClassLinker
I/anokae.shiftmo(11536): WaitForGcToComplete blocked ClassLinker on ClassLinker for 52.566ms
E/libc    (11536): Access denied finding property "ro.vendor.pref_scale_resolution"
I/cr_LibraryLoader(11536): Successfully loaded native library
I/cr_CachingUmaRecorder(11536): Flushed 8 samples from 8 histograms.
D/EgretLoader(11536): EgretLoader(Context context)
D/EgretLoader(11536): The context is not activity
W/Looper  (11536): PerfMonitor longMsg : seq=32 plan=14:53:55.959 late=6ms wall=1125ms running=0ms h=android.os.Handler c=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0 procState=2
I/Choreographer(11536): Skipped 68 frames!  The application may be doing too much work on its main thread.
I/anokae.shiftmo(11536): ProcessProfilingInfo new_methods=0 is saved saved_to_disk=0 resolve_classes_delay=8000
I/OpenGLRenderer(11536): Davey! duration=1170ms; Flags=0, IntendedVsync=12045958235362, Vsync=12047091568718, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=12047095015409, AnimationStart=12047095027794, PerformTraversalsStart=12047095035640, DrawStart=12047096438486, SyncQueued=12047101055409, SyncStart=12047106636102, IssueDrawCommandsStart=12047107000794, SwapBuffers=12047130985409, FrameCompleted=12047134110486, DequeueBufferDuration=0, QueueBufferDuration=2359000, GpuCompleted=0, 
W/Looper  (11536): PerfMonitor doFrame : time=41ms vsyncFrame=0 latency=1136ms procState=2 historyMsgCount=2 (msgIndex=1 wall=1125ms seq=32 late=6ms h=android.os.Handler c=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0)
W/Ads     (11536): Update ad debug logging enablement as false
D/libMEOW (11536): applied 1 plugins for [com.pattarachanokae.shiftmob]:
D/libMEOW (11536):   plugin 1: [libMEOW_gift.so]:
W/anokae.shiftmo(11536): Accessing hidden method Landroid/media/AudioManager;->getOutputLatency(I)I (greylist, reflection, allowed)
I/libMEOW_gift(11536): ctx:0xe4a5d400, ARC not Enabled.
W/cr_media(11536): Requires BLUETOOTH permission
I/GED     (11536): ged_boost_gpu_freq, level 100, eOrigin 2, final_idx 2, oppidx_max 2, oppidx_min 0
I/libMEOW_gift(11536): ctx:0xe4a5d760, ARC not Enabled.
I/System.out(11536): [okhttp]:check permission begin!
I/System.out(11536): [okhttp]:not MMS!
I/System.out(11536): [okhttp]:not Email!
I/Ads     (11536): JS: The jsLoaded GMSG has been sent (https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/production/sdk-core-v40-impl.html:810)
I/chromium(11536): [INFO:CONSOLE(810)] "The jsLoaded GMSG has been sent", source: https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/production/sdk-core-v40-impl.html (810)
I/System.out(11536): [socket]:check permission begin!
I/UserMessagingPlatform(11536): Use new ConsentDebugSettings.Builder().addTestDeviceHashedId("632FF6DA519AE67853EDF689C0AEF4E8") to set this as a debug device.
D/UserMessagingPlatform(11536): Stored info not exists: IDFA_freqCapNumViews
D/UserMessagingPlatform(11536): Stored info not exists: IABTCF_idfaFlowControl
I/System.out(11536): [okhttp]:check permission begin!
I/System.out(11536): [okhttp]:not MMS!
I/System.out(11536): [okhttp]:not Email!
I/System.out(11536): [socket]:check permission begin!
I/anokae.shiftmo(11536): Background concurrent copying GC freed 63135(3351KB) AllocSpace objects, 23(1116KB) LOS objects, 48% free, 6411KB/12MB, paused 153us total 134.592ms
I/System.out(11536): [OkHttp] sendRequest>>
I/System.out(11536): [OkHttp] sendRequest<<
I/anokae.shiftmo(11536): oneway function results will be dropped but finished with status OK and parcel size 4
I/System.out(11536): [OkHttp] sendRequest>>
I/System.out(11536): [OkHttp] sendRequest<<
I/System.out(11536): [okhttp]:check permission begin!
I/System.out(11536): [okhttp]:not MMS!
I/System.out(11536): [okhttp]:not Email!
I/System.out(11536): [OkHttp] sendRequest>>
I/System.out(11536): [OkHttp] sendRequest<<
W/BpBinder(11536): Slow Binder: BpBinder transact took 306 ms, interface=android.app.IActivityManager, code=22 oneway=false
D/UserMessagingPlatform(11536): Action[write]: {"IABTCF_gdprApplies":1}
D/UserMessagingPlatform(11536): Writing to storage: [IABTCF_gdprApplies] 1
D/EgretLoader(11536): EgretLoader(Context context)
D/EgretLoader(11536): The context is not activity
I/anokae.shiftmo(11536): Background concurrent copying GC freed 7447(1230KB) AllocSpace objects, 18(9556KB) LOS objects, 28% free, 15MB/21MB, paused 163us total 108.864ms
D/EgretLoader(11536): EgretLoader(Context context)
D/EgretLoader(11536): The context is not activity
D/UserMessagingPlatform(11536): Receive consent action: consent://consent/?action=start_transparency_status_updates
D/UserMessagingPlatform(11536): Action[start_transparency_status_updates]: {}
D/UserMessagingPlatform(11536): Receive consent action: consent://consent/?action=configure_app_assets
D/UserMessagingPlatform(11536): Action[configure_app_assets]: {}
E/libc    (11536): Access denied finding property "ro.vendor.pref_scale_resolution"
E/libc    (11536): Access denied finding property "ro.vendor.pref_scale_resolution"
D/UserMessagingPlatform(11536): Stored info not exists: IDFA_freqCapNumViews
D/UserMessagingPlatform(11536): Stored info not exists: IABTCF_idfaFlowControl
D/UserMessagingPlatform(11536): Receive consent action: consent://consent/?action=load_complete&args=%7B%22status%22%3A%22ok%22%7D
D/UserMessagingPlatform(11536): Action[load_complete]: {"status":"ok"}
D/UserMessagingPlatform(11536): Wall html loaded.
D/UserMessagingPlatform(11536): Receive consent action: consent://consent/?action=start_transparency_status_updates
D/UserMessagingPlatform(11536): Action[start_transparency_status_updates]: {}
D/UserMessagingPlatform(11536): Receive consent action: consent://consent/?action=configure_app_assets
D/UserMessagingPlatform(11536): Action[configure_app_assets]: {}
D/UserMessagingPlatform(11536): Stored info not exists: IDFA_freqCapNumViews
D/UserMessagingPlatform(11536): Stored info not exists: IABTCF_idfaFlowControl
D/UserMessagingPlatform(11536): Receive consent action: consent://consent/?action=load_complete&args=%7B%22status%22%3A%22ok%22%7D
D/UserMessagingPlatform(11536): Action[load_complete]: {"status":"ok"}
D/UserMessagingPlatform(11536): Wall html loaded.
I/anokae.shiftmo(11536): Background concurrent copying GC freed 37344(3010KB) AllocSpace objects, 18(10MB) LOS objects, 42% free, 8154KB/13MB, paused 157us total 113.039ms
D/ProfileInstaller(11536): Installing profile for com.pattarachanokae.shiftmob
F/crashpad(11802): dlopen: dlopen failed: library "libandroidicu.so" not found: needed by /system/lib/libharfbuzz_ng.so in namespace (default)
F/libc    (11536): Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0 in tid 11608 (DartWorker), pid 11536 (anokae.shiftmob)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'Redmi/angelica_global/angelica:11/RP1A.200720.011/V12.5.3.0.RCRMIXM:user/release-keys'
Revision: '0'
ABI: 'arm'
Timestamp: 2024-06-07 14:54:17+0200
pid: 11536, tid: 11608, name: DartWorker  >>> com.pattarachanokae.shiftmob <<<
uid: 10260
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
Cause: null pointer dereference
    r0  80000000  r1  a4bd4b4c  r2  a4bd4b4c  r3  a577a9e9
    r4  a4bd4b4c  r5  a4bd4b4c  r6  a4bd4b4c  r7  00000001
    r8  00000000  r9  a1cfab44  r10 00000fff  r11 a5862d60
    ip  00000734  sp  a1cfaac8  lr  a57711c1  pc  a577aa12
backtrace:
      #00 pc 00a98a12  /data/app/~~UVb2K80H-3CaW1BTIdYChQ==/com.pattarachanokae.shiftmob-sI8VfbsCid9oZfMsQQ71pw==/lib/arm/libflutter.so (BuildId: 52ed653d8850a47098529674d68f80097eb36227)
      #01 pc 00a8f1bf  /data/app/~~UVb2K80H-3CaW1BTIdYChQ==/com.pattarachanokae.shiftmob-sI8VfbsCid9oZfMsQQ71pw==/lib/arm/libflutter.so (BuildId: 52ed653d8850a47098529674d68f80097eb36227)
      #02 pc 00a9884d  /data/app/~~UVb2K80H-3CaW1BTIdYChQ==/com.pattarachanokae.shiftmob-sI8VfbsCid9oZfMsQQ71pw==/lib/arm/libflutter.so (BuildId: 52ed653d8850a47098529674d68f80097eb36227)
```

**Comment by NaoKreuzeder** [comment] 2024-06-07 13:23
@darshankawar 
Finally symbolization worked. Here is the output.

![Bildschirmfoto 2024-06-07 um 15 21 28](https://github.com/flutter/flutter/assets/152265506/2b6b2ec2-c1a2-47fa-9332-30df54dd785a)

**Comment by NaoKreuzeder** [comment] 2024-06-07 17:34
I have one more log

```
  #00 00a98a12 <...>/lib/arm/libflutter.so (BuildId: 52ed653d8850a47098529674d68f80097eb36227)
                                           unsigned int std::_fl::__cxx_atomic_load[abi:v15000]<unsigned int>(std::_fl::__cxx_atomic_base_impl<unsigned int> const*, std::_fl::memory_order)
                                           third_party/libcxx/include/atomic:958:12
                                           std::_fl::__atomic_base<unsigned int, false>::load[abi:v15000](std::_fl::memory_order) const
                                           third_party/libcxx/include/atomic:1588:17
                                           dart::UntaggedObject::ClassIdTag::Type dart::AtomicBitFieldContainer<unsigned int>::Read<dart::UntaggedObject::ClassIdTag, (std::_fl::memory_order)0>() const
                                           third_party/dart/runtime/vm/bitfield.h:48:42
                                           dart::UntaggedObject::GetClassId() const
                                           third_party/dart/runtime/vm/raw_object.h:371:46
                                           dart::ObjectPtr::GetClassId() const
                                           third_party/dart/runtime/vm/raw_object.h:865:19
                                           dart::RestoreWriteBarrierInvariantVisitor::VisitPointers(dart::ObjectPtr*, dart::ObjectPtr*)
                                           third_party/dart/runtime/vm/thread.cc:974:16
  #01 00a8f1bf <...>/lib/arm/libflutter.so (BuildId: 52ed653d8850a47098529674d68f80097eb36227)
                                           dart::ObjectPointerVisitor::VisitPointer(dart::ObjectPtr*)
                                           third_party/dart/runtime/vm/visitor.h:55:37
                                           dart::StackFrame::VisitObjectPointers(dart::ObjectPointerVisitor*)
                                           third_party/dart/runtime/vm/stack_frame.cc:274:20
  #02 00a9884d <...>/lib/arm/libflutter.so (BuildId: 52ed653d8850a47098529674d68f80097eb36227)
                                           dart::Thread::RestoreWriteBarrierInvariant(dart::Thread::RestoreWriteBarrierInvariantOp)
                                           third_party/dart/runtime/vm/thread.cc:1071:16
```

**Comment by darshankawar** [comment] 2024-06-10 05:51
> @darshankawar Finally symbolization worked. Here is the output.
> 
> ![Bildschirmfoto 2024-06-07 um 15 21 28](https://private-user-images.githubusercontent.com/152265506/337666721-2b6b2ec2-c1a2-47fa-9332-30df54dd785a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc5OTgxNzAsIm5iZiI6MTcxNzk5Nzg3MCwicGF0aCI6Ii8xNTIyNjU1MDYvMzM3NjY2NzIxLTJiNmIyZWMyLWMxYTItNDdmYS05MzMyLTMwZGY1NGRkNzg1YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMFQwNTM3NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NTM1NDE4OTc2Y2I5ZGMwZDI0YTU0MGRiZDRiZjY0MWFlYTJmODAwNTFiMTA1ZmQ2ODI2OGYyMGVmMTg2OGFlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.T33U3h20kSaY1MDDkhpQDQSf_MgIfNuMc6Lf4SANQog)

Can you provide this in properly formatted text ?

**Comment by NaoKreuzeder** [comment] 2024-06-10 08:19
@darshankawar 
```
symbolized using symbols for 55eae6864b296dd9f43b2cc7577ec256e5c32a8d android-arm-profile

  #00 00aae6ca <...>/lib/arm/libflutter.so (BuildId: 52ed653d8850a47098529674d68f80097eb36227)
                                           dart::MarkingVisitorBase<true>::MarkObject(dart::ObjectPtr)
                                           third_party/dart/runtime/vm/heap/marker.cc:510:9
                                           dart::MarkingVisitorBase<true>::VisitPointers(dart::ObjectPtr*, dart::ObjectPtr*)
                                           third_party/dart/runtime/vm/heap/marker.cc:258:7
  #01 003657a4 <...>/lib/arm/libapp.so (BuildId: 445112cfa6571b342ebd2a8519fa6979)
```

**Comment by NaoKreuzeder** [comment] 2024-06-10 08:21
@darshankawar 
This is from Logcat.
[crash minidump logcat.txt](https://github.com/user-attachments/files/15759008/crash.minidump.logcat.txt)

**Comment by mraleph** [comment] 2024-06-10 09:21
cc @rmacnak-google @mkustermann

**Comment by mkustermann** [comment] 2024-06-10 09:30
It seems incremental compaction isn't on the stable branch (which was cut before first version landed on main). @rmacnak-google Is  5918b3a4ee9e2d6240d6a97bbab56e96efdecf75 an optimization only or does it fix a bug? (this comment isn't on stable)

**Comment by rmacnak-google** [comment] 2024-06-10 16:17
@mkustermann Before incremental compaction, 5918b3a4ee9e2d6240d6a97bbab56e96efdecf75 is an optimization. (Though incremental compaction requires it for correctness.) I think there are no correctness fixes that are currently in main and not in Flutter 3.22.1.

**Comment by a-siva** [comment] 2024-06-10 19:08
//cc @rmacnak-google

**Comment by NaoKreuzeder** [comment] 2024-06-11 04:49
@a-siva 
Yes, i can do that. I need a few days.

**Comment by NaoKreuzeder** [comment] 2024-06-12 12:54
@a-siva 
I duplicated the source code that has the error and removed everything i don't want to be public.
Unfortunately the error is gone. I can't reproduce the error with the copy.

Is it enough for you if i send an APK file that has the error? Would that help you?

**Comment by a-siva** [comment] 2024-06-17 17:47
@NaoKreuzeder I don't believe sending the APK file is going to help us debug the problem.
Maybe we should first figure out if this is a regression that introduced, you indicate that the version of Flutter you are using is Channel stable, 3.22.1, Would it be possible for you to try various versions of Flutter to help us isolate the potential change that could have triggered it. Can you try and earlier Beta version of Flutter ?

**Comment by NaoKreuzeder** [comment] 2024-06-18 07:51
@a-siva 
I fixed the problem in my project. No more crashes since 1 week and also on my test device (Redmi 9C). Hope this helps you to find the problem.

Version that had the crash
```
class Testing {
  Future<void> _calculation() async {
    final List<Map<String, Duration>> listOfMaps = [];

    for (int i = 0; i < 10; i++) {
      await _subCalculation(listOfMaps);
    }
  }

  Future<void> _subCalculation(
    List<Map<String, Duration>>? listOfMaps,
  ) async {
    if (listOfMaps != null) { // here the app crashed..
      //do something..
    }
  }
}
```

I changed the upper example to this. No more crashes.
```
class Testing {
  Future<void> _calculation() async {
    final List<Map<String, Duration>> listOfMaps = [];

    for (int i = 0; i < 10; i++) {
      await _subCalculation(listOfMaps);
    }
  }

  Future<void> _subCalculation(
    List<Map<String, Duration>> listOfMaps,
  ) async {
    if (listOfMaps.isNotEmpty) {
      //do something..
    }
  }
}
```

**Comment by a-siva** [comment] 2024-06-24 17:07
@NaoKreuzeder thanks for that snippet, we will continue to investigate and see if a local reproduction is possible. Since you have found a work around for your crash, lowering the priority of this issue to P2.

**Comment by a-siva** [comment] 2024-07-10 20:45
Unable to reproduce with the snippet provided above, at this point there is not much we can do about this crash without a reproduction, closing issue.

**Closed by a-siva** 2024-07-10 20:45 UTC
Labels: c: crash, engine, dependency: dart, P3, needs repro info, team-engine, triaged-engine
