### ISSUE TITLE
Document packaging for Windows builds

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#53167] opened 2020-03-24 15:43 UTC
See https://github.com/google/flutter-desktop-embedding/issues/587 for earlier discussion.

We should very likely either:
- switch the templates for apps and plugins to use the static runtime, or
- update the app bundling script to copy in the runtime libraries into the output directory for ease of packaging.

From my initial investigation in the original bug:
> I did a quick experiment, and using the static runtime increases the size of each of the current FDE plugins from ~50-70K to ~300-500K, and Testbed.exe from ~100K to ~500K.
>
> While that's not all that much in current desktop machine size terms, it's not clear to me that the benefit of doing that vs. having a simple path to bundling the necessary runtime libraries (e.g., adding to bundle_assets_and_deps) is the right approach. We should look more into the tradeoffs in terms of potential interactions between plugins, which would be more isolated with a static runtime.

**Comment by 926** [comment] 2020-04-03 08:16
Hi,
Sorry to push on this, but testing app on windows has become key for our clients.
Have you made a choice regarding the two options ?
How about moving on with static runtime today and consider reworking the bundling script later ?
If there's anything basic, time-consuming task to do I'll be glad to help

**Comment by stuartmorgan** [comment] 2020-04-03 15:17
> Sorry to push on this, but testing app on windows has become key for our clients.

Feel free to modify the runner of the applications you build however you like for your needs.

> Have you made a choice regarding the two options ?

No, which is why this issue is still open.

**Comment by 926** [comment] 2020-04-04 09:45
Thank you for your quick reply,
Do you think this will be ok before the end of April ?
if not would could you please provide a model on how to modify the runner and not [shoot it](https://youtu.be/i5D8eZd2HLA) ?
I beg your pardon for insisting again, I know your time is scarce

**Comment by stuartmorgan** [comment] 2020-05-28 22:27
Absent any new information that leads to a re-evaluation, my current view on this is that we should use the shared runtime for the runner and plugins.

We'll need to figure out how to best support distribution, given that there are [several options](https://docs.microsoft.com/en-us/cpp/windows/redistributing-visual-cpp-files?view=vs-2019).
1. If people are using the setup packages, which seems to be the recommended solution, then it's probably just a matter of documentation (e.g., pointing to [these instructions](https://docs.microsoft.com/en-us/cpp/windows/walkthrough-deploying-a-visual-cpp-application-to-an-application-local-folder?view=vs-2019)). We might want to consider copying them to the build directory to make it easier to find them.
1. If we want to support [a fully relocatable directory with no dependencies](https://docs.microsoft.com/en-us/cpp/windows/walkthrough-deploying-a-visual-cpp-application-to-an-application-local-folder?view=vs-2019), we should likely copy the necessary libraries from `%VCToolsRedistDir%` to the build folder. Based on `depends` it looks like that's msvcp140.dll, vcruntime140.dll, and vcruntime140_1.dll (although I haven't verified that on a clean Windows install).

The problem with doing 2 is that there's the potential that if we always do it, people who are following the recommended path (1) may end up bundling all the libraries from 2 and getting the worst outcome. It might be that we instead leave that up to higher-level packaging tools, which will have the context of whether they are building an installer, or something that's just copyable.

**Comment by 926** [comment] 2020-05-30 16:28
I still cannot get my head around instructions in 1. and I don't see what is the added value of 1 instead of 2.  nor why would someone prefer to go through a tedious manual install. Are there any benefits from using bundle instead of using Flutter build windows ?
For information, the only solution we found for our clients to run our app on windows is to ask them to download Visual Studio with the required Desktop C++ modules ; so running our 20 Mo app requires a ~6 Go install.

**Comment by stuartmorgan** [comment] 2020-05-30 20:56
> I don't see what is the added value of 1 instead of 2.

The first link in my last comment discusses the reasons 1 is recommended over 2. However, how exactly to distribute the necessary libraries is always going to be up to the developer regardless of what convenience wrappers we, or other projects, may provide, so if you prefer 2 feel free to set your project up to do that.

> nor why would someone prefer to go through a tedious manual install.

I don't see how running an installer constitutes "a tedious manual install". Installers are a standard way of installing applications on Windows. But again, nothing here will force people to use an installer if they don't want to.

> For information, the only solution we found for our clients to run our app on windows is to ask them to download Visual Studio with the required Desktop C++ modules ; so running our 20 Mo app requires a ~6 Go install.

The first link in my last comment links to instructions for three different approaches, all of which are dramatically better than that, any of which you could do today. However, that's not one of the options being considered here, so it's not really relevant to the issue.

**Comment by 926** [comment] 2020-05-31 09:55
Thank you for your quick reply and for your time. 
Issue https://github.com/google/flutter-desktop-embedding/issues/723 is closed, so I assumed it was relevant to pursue the whining here about the .dll missing error. It is to avoid this error that we get users to do the full 6Go install.

The tedious instructions referred to the Visual Code you pointed to, i.e. [deploy cpp](https://docs.microsoft.com/en-us/cpp/windows/walkthrough-deploying-a-visual-cpp-application-by-using-a-setup-project?view=vs-2019). So far I failed to set-up the MFC app.  I will try again tomorrow.

Correct me again if I am wrong, but I understood that, once completed, 2. would allow developers to release the app with the required .dll libraries with a simple : 

flutter build windows

Thus preventing any Flutter developer from adventuring in the realm of Visual Studio's nails biting, doors-slamming, keyboard-slapping, step by step tutorial...

**Comment by JanezStupar** [comment] 2020-08-14 14:13
> finally nailed it \°/

@926 so what did you do?

**Comment by 926** [comment] 2020-08-16 09:49
Hi @JanezStupar 

Quick fix is to download a vcruntime140_1.dll from web and put it into the build/runner folder.
Else you can use VS to build cpp, but that is tedious.

**Comment by stuartmorgan** [comment] 2021-01-07 20:06
We've decided on using dynamic runtime, with the suggest solution being to use an installer. Generating MSIX automatically is a possibility tracked in https://github.com/flutter/flutter/issues/63672, but for now we should document how to do it manually with the right library dependencies.

**Comment by domesticmouse** [comment] 2021-01-08 06:10
@stuartmorgan the notes I have on publishing an MSIX to the MS Store are [here](https://github.com/flutter/samples/tree/master/experimental/desktop_photo_search#deploying-to-the-microsoft-store). I'm hesitant to say much more than this as it will wind up duplicating MS' documentation, and become a maintenance head ache as MS inevitably update their systems.

**Comment by stuartmorgan** [comment] 2021-01-11 15:55
Sounds like the next step is to expand on that slightly (we should separate packaging from store distribution, for instance) as a section for flutter.dev/desktop, replacing (at least mostly) the current Windows packaging discussion.

**Comment by syleishere** [comment] 2021-01-21 17:19
I think your missing the point here about exe installer. 
while(1) {
   Day 1: upload exe to your website, have friend download it and test it on desktop
   Next Day: repeat
   Other Days: repeat
   Next Days: repeat again and again
} 
Final App: Package with MSIX

So let me get this right, instead of him just clicking on a link with a single .exe and executing on the desktop, he has to manually go into programs, find the program, uninstall it, redownload the link, go for coffee and a drink already tedious, ok now maybe click on link, go through whole install process again, find the program, execute it, go for coffee, maybe a beer, now maybe report back?

No it needs to be a single .exe and the MSIX can come on very last step.

**Comment by csells** [comment] 2021-01-21 17:31
Of course you can zip up the output of the build along with the dependencies and update that as you choose.

**Comment by syleishere** [comment] 2021-01-21 17:39
Right and pyinstaller does that in a simple config file, and compiles it into a simple exe, of course have to account for things like
_MEIPASS but would be valuable to flutter community.

**Comment by stuartmorgan** [comment] 2021-01-21 18:03
> pyinstaller does that in a simple config file

If your argument here is that it would be good if someone in the broader Flutter community created a tool which makes it trivial to create a zip file (including the C++ redistributable) from the build output, I don't think anyone would disagree. We look forward to the community creating lots of ways to package and distribute Flutter applications.

> and compiles it into a simple exe

Having Flutter developers build the entire Flutter engine from scratch, which compiling to a single file would require, is a non-starter, so that's not a viable option.

I'm not clear what your issue with distributing a zip file for testing is. Your alternative scenario above does not actually compare a single exe to the zip file that I had previously explained was an option in response to your comment on the other issue.

**Comment by csells** [comment] 2021-01-26 20:09
@domesticmouse can we update the docs for Windows and macOS distribution to the stores as well as let folks know that snap is not required for Linux

**Comment by domesticmouse** [comment] 2021-02-15 03:24
Re-opening for macOS and Linux doc requirements

**Comment by domesticmouse** [comment] 2021-02-15 06:08
@csells we should probably split the macOS and Linux part of this bug out as separate bugs. I believe the Windows packaging documentation requirements were covered by https://github.com/flutter/website/pull/5268 and the macOS distribution options are covered by https://github.com/flutter/website/pull/5298.

I'm unsure what we want to say about Linux, as we don't have infrastructure in place to support binary distribution on Linux other than by snap at this point. The Flutter GDEs are asking for AppImage as an alternative https://github.com/flutter/flutter/issues/76037.

**Comment by stuartmorgan** [comment] 2021-02-15 12:03
We can say essentially the same thing we say about Windows: there's a single folder in the build output (`bundle`) which can be distributed or used to construct a distribution package of their choice (`AppImage`, `flatpak`, etc.). Ideally we could list the dependent libraries that they would need to make sure are on the system (e.g., GTK).

Currently the docs are giving a lot of people the impression that the only possible way to distribute a Linux app is via Snap, rather than that just being a way that someone had already made a script for.

**Comment by fawdlstty** [comment] 2021-02-19 09:10
> We've decided on using dynamic runtime

The `flutter_windows.dll` file that must be included is large and independent, if you continue to use dynamic runtime for Windows programs, will not solve the size problem and will make distributing software more dependence. If only because of the program size, VC-LTL can solve this problem.

> MSIX automatically is a possibility tracked in #63672

The MSIX is not easy to use, and there is no need to integrate into Flutter. Modifying the dependency options /MT, /MTd is much easier than integrating with the MSIX

**Comment by stuartmorgan** [comment] 2021-02-19 15:09
> if you continue to use dynamic runtime for Windows programs, will not solve the size problem

It avoids a roughly 10x size increase in *each* plugin used, as the original post explains.

**Comment by fawdlstty** [comment] 2021-02-19 15:32
1. The release version file `flutter_windows.dll` is 13M, it doesn't matter if you add 50K or 500K plugin dll. so:

> if you continue to use dynamic runtime for Windows programs, will not solve the size problem

2. The size increase caused by static operation is very unimportance. If the size of static runtime is 100M and changed to dynamic runtime, only 1~2M can be optimized

3. Dynamic runtime cause more trouble than their worth

**Comment by stuartmorgan** [comment] 2021-02-19 15:43
> Dynamic runtime cause more trouble than their worth

If you are aware of problems with dynamic runtime please describe them, with specifics, rather than simply asserting that they exist.

**Comment by fawdlstty** [comment] 2021-02-19 15:56
You know, for software distribution, the ideal state is copy to any environment and it usable, it easier for both green software or software installation packages

**Comment by fawdlstty** [comment] 2021-02-19 15:56
You know, for software distribution, the ideal state is copy to any environment and it usable, it easier for both green software or software installation packages

**Comment by fawdlstty** [comment] 2021-02-19 16:02
The Windows installer software has no dependencies, so after uninstalling the runtime, the dynamic runtime software will run into an exception. even though it's hard to cause

**Comment by stuartmorgan** [comment] 2021-02-19 16:25
Dynamic runtime is not incompatible with being able to make an app that can be copied. The [current documentation](https://flutter.dev/desktop#windows) already describes how to make such a thing ("Place the DLL files in a directory next to the executable and the other DLLs"). Neither of the things you listed apply if you choose to package your software that way.

**Comment by fawdlstty** [comment] 2021-02-19 16:57
The `vcruntime140.dll` on my computer is very small in size, but it relies on api set, similar to `api-ms-win-*.dll`, Win8, Win10 default support, Win7 only after SP1 with a KB00000000 (I forget which) patch, otherwise it will not run

**Comment by fawdlstty** [comment] 2021-02-20 06:16
Win8 system environment also needs to be patched. I found some document to description:
<https://www.cnblogs.com/phyking/p/5715352.html>
<https://www.cnblogs.com/ingstyle/p/12325247.html>

**Comment by leielyq** [comment] 2021-03-17 14:09
Yes!Even with the vcruntime140.dll, it's not available on win7 because it needs to be associated with a lot of the dlls that come with win10, and it's not responsible for officially releasing beta tests for flutter-Windows right now. Also test the compatibility of win7, please note that it is said to run on win7, not on win7 after the development environment to run, I believe that any mature developer will not do such a stupid thing

**Comment by GanZhiXiong** [comment] 2021-05-14 10:22
When I run exe on another computer, I get an error：

![image](https://user-images.githubusercontent.com/27394631/118256736-68de3880-b4e0-11eb-8d16-b78984f5fe0b.png)

`文件或目录损坏且无法读取`That translates to: `A file or directory is corrupted and unreadable`

I have put these files(msvcp140.dll, vcruntime140.dll,  vcruntime140_1.dll) in the same directory as the EXE files: 

![image](https://user-images.githubusercontent.com/27394631/118257523-50225280-b4e1-11eb-83f3-fc761e471976.png)

**Comment by GanZhiXiong** [comment] 2021-05-14 10:37
> When I run exe on another computer, I get an error：
> 
> ![image](https://user-images.githubusercontent.com/27394631/118256736-68de3880-b4e0-11eb-8d16-b78984f5fe0b.png)
> 
> `文件或目录损坏且无法读取`That translates to: `A file or directory is corrupted and unreadable`
> 
> I have put these files(msvcp140.dll, vcruntime140.dll, vcruntime140_1.dll) in the same directory as the EXE files:
> 
> ![image](https://user-images.githubusercontent.com/27394631/118257523-50225280-b4e1-11eb-83f3-fc761e471976.png)

I've found a problem. Copying files via Microsoft Remote Desktop seems to be corrupting. If that's the case, that's awful. 😰

**Comment by fawdlstty** [comment] 2021-05-14 10:38
Win10 system default include api-set, so you are not encountered with this problem, and may be related to other factors, you can through the system event screening

**Comment by kirill-21** [comment] 2021-06-08 21:40
> > We've decided on using dynamic runtime
> 
> The `flutter_windows.dll` file that must be included is large and independent, if you continue to use dynamic runtime for Windows programs, will not solve the size problem and will make distributing software more dependence. If only because of the program size, VC-LTL can solve this problem.
> 
> > MSIX automatically is a possibility tracked in #63672
> 
> The MSIX is not easy to use, and there is no need to integrate into Flutter. Modifying the dependency options /MT, /MTd is much easier than integrating with the MSIX

Hi. I've tried to compile the project with /MT option, but now it doesn't launch. The process is alive in a task manager, but there aren't any errors
![image](https://user-images.githubusercontent.com/63228361/121261202-16175700-c8bb-11eb-880a-3930d36af5ad.png)

I also tried to add msvcp140.dll, vcruntime140.dll, vcruntime140_1.dll dlls to the project(both with /MT and /MD options), but the result is the same

**Comment by kirill-21** [comment] 2021-06-08 22:30
Maybe you should add some option to the build command (like in web when you choose a renderer[flutter build web --web-renderer canvaskit or html]) which will switch all solutions from /md to /mt, so that you don't have to do it manually after each build

**Comment by stuartmorgan** [comment] 2021-06-08 23:19
> so that you don't have to do it manually after each build

If you have to do it after every build, you are not chasing it in the right place. The CMake files are the source of truth, and are not changed by building.

Regardless, this issue is purely about documentation at this point, as it says in the title and the comments above. Feature requests are off topic here. It would be very helpful if people could file new issues instead of trying to use this issue for anything at all related to Windows build artifacts.

**Comment by kirill-21** [comment] 2021-08-25 09:15
To ensure that your app always builds with MT, MTd flags - edit windows/CMakeLists.txt file by adding 
```
set(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>")
```
this option to it

**Comment by cbracken** [comment] 2021-09-28 22:24
Adding myself as an assignee. This has become a bit of a catch-all bug. We should summarise the remaining work and break out new bugs.

**Comment by cbracken** [comment] 2022-05-07 04:07
The strict reading of the title here was covered by https://github.com/flutter/website/pull/5268. Closing since the discussion around static vs dynamic linking was also resolved above (see discussion around size increase).

Any further tweaks to the documentation for packaging Windows builds can be filed as new bugs.

**Closed by cbracken** 2022-05-07 04:07 UTC
Labels: tool, platform-windows, a: desktop, documentation, a: build, P4
