### ISSUE TITLE
[tool_crash] NoSuchMethodError: NoSuchMethodError: The getter 'assetPathsToEvict' was called on null.Receiver: nullTried calling: assetPathsToEvict

### ISSUE THREAD

**Issue by Hmida71** [flutter/flutter#103210] opened 2022-05-06 16:30 UTC
%23%23 Command
```
flutter run -v
```

%23%23 Steps to Reproduce
1. ...
2. ...
3. ...

%23%23 Logs
NoSuchMethodError: NoSuchMethodError: The getter 'assetPathsToEvict' was called on null.
Receiver: null
Tried calling: assetPathsToEvict
```
%230      Object.noSuchMethod (dart:core-patch/object_patch.dart:38:5)
%231      HotRunner._resetDirtyAssets (package:flutter_tools/src/run_hot.dart:510:20)
%232      HotRunner._restartFromSources (package:flutter_tools/src/run_hot.dart:578:5)
<asynchronous suspension>
%233      HotRunner._fullRestartHelper (package:flutter_tools/src/run_hot.dart:760:16)
<asynchronous suspension>
%234      HotRunner.restart (package:flutter_tools/src/run_hot.dart:707:38)
<asynchronous suspension>
%235      TerminalHandler._commonTerminalInputHandler (package:flutter_tools/src/resident_runner.dart:1640:40)
<asynchronous suspension>
%236      TerminalHandler.processTerminalInput (package:flutter_tools/src/resident_runner.dart:1680:7)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 2.10.4, on Microsoft Windows [version 10.0.19043.1645], locale fr-FR)
    • Flutter version 2.10.4 at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (6 weeks ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at C:\Users\Hmida_Dz\AppData\Local\Android\Sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • ANDROID_HOME = C:\Users\Hmida_Dz\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11 9-b60-7590822)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2022 17.1.4)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.1.32407.343
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 2021.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11 9-b60-7590822)

[✓] VS Code (version 1.66.2)
    • VS Code at C:\Users\Hmida_Dz\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.40.0

[✓] Connected device (4 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)       • windows       • windows-x64    • Microsoft Windows [version 10.0.19043.1645]
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 100.0.4896.127
    • Edge (web)              • edge          • web-javascript • Microsoft Edge 100.0.1185.50

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

%23%23 Flutter Application Metadata
**Type**: app
**Version**: 1.0.0 1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: c860cba910319332564e1e9d470a17074c1f2dfd
%23%23%23 Plugins
cloud_firestore-2.5.4
cloud_firestore_web-2.6.12
connectivity-3.0.6
connectivity_for_web-0.4.0 1
connectivity_macos-0.2.1 2
file_picker-4.5.1
firebase_auth-3.3.14
firebase_auth_web-3.3.12
firebase_core-1.14.1
firebase_core_web-1.6.2
firebase_database-9.0.12
firebase_database_web-0.2.0 11
firebase_messaging-10.0.9
firebase_messaging_web-2.2.11
firebase_storage-10.2.12
firebase_storage_web-3.2.12
flutter_plugin_android_lifecycle-2.0.5
google_sign_in-5.3.0
google_sign_in_android-5.2.5
google_sign_in_ios-5.2.5
google_sign_in_web-0.10.1
image_picker-0.8.5
image_picker_android-0.8.4 11
image_picker_for_web-2.1.6
image_picker_ios-0.8.4 11
path_provider-2.0.9
path_provider_android-2.0.12
path_provider_ios-2.0.8
path_provider_linux-2.1.5
path_provider_macos-2.0.5
path_provider_windows-2.0.5
shared_preferences-2.0.13
shared_preferences_android-2.0.11
shared_preferences_ios-2.1.0
shared_preferences_linux-2.1.0
shared_preferences_macos-2.0.3
shared_preferences_web-2.0.3
shared_preferences_windows-2.1.0
sqflite-2.0.2 1
toast-0.2.9
unity_ads_plugin-0.2.4
url_launcher-6.0.20
url_launcher_android-6.0.15
url_launcher_ios-6.0.15
url_launcher_linux-3.0.0
url_launcher_macos-3.0.0
url_launcher_web-2.0.9
url_launcher_windows-3.0.0
video_player-2.4.0
video_player_android-2.3.2
video_player_avfoundation-2.3.2
video_player_web-2.0.8

**Comment by darshankawar** [comment] 2022-05-09 06:24
Closing as duplicate of https://github.com/flutter/flutter/issues/89738

**Closed by darshankawar** 2022-05-09 06:24 UTC
Labels: in triage
