### ISSUE TITLE
Flutter PlayStore Distribution APK is not loading, stuck on splash screen

### ISSUE THREAD

**Issue by saveKenny** [flutter/flutter#80143] opened 2021-04-09 19:18 UTC
flutter run -v --release works just fine, But when I upload the APK to PlayStore, and install, it stuck on the splash screen.

If I install the original APK manually from the App bundle explorer everything is just fine. But when I download the Distribution APK my app stucks on the splash screen.

I have flutter clean before building the APK, My flutter run -v --release logs are just fine and working and flutter doctor as well.

**My flutter doctor -v**

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 2.0.2, on Linux, locale en_IL)
    • Flutter version 2.0.2 at /home/daniel/projects/frontend/flutter
    • Framework revision 8962f6dc68 (4 weeks ago), 2021-03-11 13:22:20 -0800
    • Engine revision 5d8bf811b3
    • Dart version 2.12.1
                                                                                                                                                                                                   [!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/daniel/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /home/daniel/Android/Sdk
    • Java binary at: /home/daniel/projects/frontend/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 4.0)
    • Android Studio at /home/daniel/projects/frontend/android-studio
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.52.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.20.0

[✓] Connected device (1 available)
    • Mi A3 (mobile) • 5d0ddb114eaa • android-arm64 • Android 11 (API 30)

! Doctor found issues in 2 categories.
```
	
</details>

How can I read logs from my Distribution APK? What may be wrong? Thanks!

**Comment by iapicca** [comment] 2021-04-10 14:38
@saveKenny 
can you provide a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) 

does the issue occur if install manually the apk from `flutter build apk` ?

**Comment by TahaTesser** [comment] 2021-04-12 09:28
Hi @saveKenny 
You can get crash reports using sentry for flutter. To better address the issue, please provide either crash logs or reproducible steps. There could be any reason for the issue, without more information, it's hard to pinpoint the cause

**Comment by pedromassangocode** [comment] 2021-05-07 10:59
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2021-05-07 10:59 UTC
Labels: in triage, waiting for customer response
