### ISSUE TITLE
[tool_crash] ProcessException: Failed to find "/Applications/flutter/bin/cache/dart-sdk/bin/dartaotruntime" in the search path. Command: /Applications/flutter/bin/cache/dart-sdk/bin/dartaotruntime, OS error code: 0

### ISSUE THREAD

**Issue by Henrydykee** [flutter/flutter#158262] opened 2024-11-06 14:02 UTC
## Command
```sh
flutter --no-color run --machine --track-widget-creation --device-id=57624277-D4BC-4B27-B22B-019E1A996D1B --start-paused lib/main-staging.dart --flavor staging --dart-define ENV=STAGING --dart-define=flutter.inspector.structuredErrors=true lib/main-staging.dart
```

## Steps to Reproduce
1. run lib/main.dart

## Logs
ProcessException: Failed to find "/Applications/flutter/bin/cache/dart-sdk/bin/dartaotruntime" in the search path. Command: /Applications/flutter/bin/cache/dart-sdk/bin/dartaotruntime, OS error code: 0
```console
#0      LocalProcessManager.start (package:process/src/interface/local_process_manager.dart:56:7)
#1      ErrorHandlingProcessManager.start.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:699:24)
#2      _run (package:flutter_tools/src/base/error_handling_io.dart:569:20)
#3      ErrorHandlingProcessManager.start (package:flutter_tools/src/base/error_handling_io.dart:698:12)
#4      DefaultResidentCompiler._compile (package:flutter_tools/src/compile.dart:875:37)
#5      DefaultResidentCompiler._recompile (package:flutter_tools/src/compile.dart:735:14)
#6      _RecompileRequest._run (package:flutter_tools/src/compile.dart:421:16)
#7      _CompilationRequest.run (package:flutter_tools/src/compile.dart:395:30)
#8      DefaultResidentCompiler._handleCompilationRequest (package:flutter_tools/src/compile.dart:781:23)
#9      _rootRunUnary (dart:async/zone.dart:1407:47)
#10     _CustomZone.runUnary (dart:async/zone.dart:1308:19)
#11     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217:7)
#12     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:365:11)
#13     _DelayedData.perform (dart:async/stream_impl.dart:541:14)
#14     _PendingEvents.handleNext (dart:async/stream_impl.dart:646:11)
#15     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:617:7)
#16     _rootRun (dart:async/zone.dart:1391:47)
#17     _CustomZone.run (dart:async/zone.dart:1301:19)
#18     _CustomZone.runGuarded (dart:async/zone.dart:1209:7)
#19     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1249:23)
#20     _rootRun (dart:async/zone.dart:1399:13)
#21     _CustomZone.run (dart:async/zone.dart:1301:19)
#22     _CustomZone.runGuarded (dart:async/zone.dart:1209:7)
#23     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1249:23)
#24     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
```
```console
[✓] Flutter (Channel stable, 3.24.4, on macOS 15.1 24B83 darwin-arm64, locale en-US)
    • Flutter version 3.24.4 on channel stable at /Applications/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 603104015d (13 days ago), 2024-10-24 08:01:25 -0700
    • Engine revision db49896cf2
    • Dart version 3.5.4
    • DevTools version 2.37.3

[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/mac/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/to/macos-android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 16.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16B40
    • CocoaPods version 1.16.2

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 2024.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.3+-79915917-b509.11)

[✓] IntelliJ IDEA Community Edition (version 2024.2.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 82.1.3
    • Dart plugin version 242.22855.32

[✓] Connected device (3 available)
    • iPhone 11 (mobile)              • 57624277-D4BC-4B27-B22B-019E1A996D1B • ios          • com.apple.CoreSimulator.SimRuntime.iOS-18-1 (simulator)
    • macOS (desktop)                 • macos                                • darwin-arm64 • macOS 15.1 24B83 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad                • darwin       • macOS 15.1 24B83 darwin-arm64

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: f30b7f4db93ee747cd727df747941a28ead25ff5
### Plugins
firebase_core-1.13.1
firebase_core_web-1.6.1
firebase_crashlytics-2.5.3
firebase_messaging-11.2.8
firebase_messaging_web-2.2.9
firebase_remote_config-2.0.2
firebase_remote_config_web-1.0.7
flutter_pdfview-1.2.5
mixpanel_flutter-2.1.1
package_info_plus-4.1.0
path_provider-2.0.12
path_provider_android-2.0.12
path_provider_foundation-2.1.1
path_provider_linux-2.1.7
path_provider_windows-2.1.7
sentry_flutter-7.9.0
share-2.0.4
shared_preferences-2.0.13
shared_preferences_android-2.0.11
shared_preferences_ios-2.1.0
shared_preferences_linux-2.1.0
shared_preferences_macos-2.0.3
shared_preferences_web-2.0.3
shared_preferences_windows-2.1.0
sqflite-2.0.2
url_launcher-6.1.8
url_launcher_android-6.0.15
url_launcher_ios-6.0.15
url_launcher_linux-3.0.2
url_launcher_macos-3.0.0
url_launcher_web-2.0.14
url_launcher_windows-3.0.3
webview_flutter-4.5.0
webview_flutter_android-3.15.0
webview_flutter_wkwebview-3.12.0

**Comment by darshankawar** [comment] 2024-11-07 07:46
Closing this as a duplicate of https://github.com/flutter/flutter/issues/143391

**Closed by darshankawar** 2024-11-07 07:46 UTC
Labels: in triage
