### ISSUE TITLE
Flutter 2.8. Scroll Performance 

### ISSUE THREAD

**Issue by AlexSmirnov9107** [flutter/flutter#95151] opened 2021-12-13 07:21 UTC
I have noticed a huge scroll performance downgrade. Its like a jumpy

I have upgraded flutter from 2.5.3 to 2.8.

## Details

**Target Platform:iOS**
**Target OS version/browser:15.1**
**Devices:iPhone XS Max**

## Video

<details>
<summary>Flutter 2.5.3</summary>

https://streamable.com/p7tb8s
</details>

<details>
<summary>Flutter 2.8</summary>

https://streamable.com/iurz8o

</details>

## Logs

<details>
<summary>Logs</summary>

```
Analyzing mobile-flutter...                                             
No issues found! (ran in 2.8s)
```

```
[✓] Flutter (Channel stable, 2.8.0, on macOS 12.0.1 21A559 darwin-x64, locale ru-KZ)
    • Flutter version 2.8.0 at /usr/local/Caskroom/flutter/2.8.0/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cf44000065 (4 days ago), 2021-12-08 14:06:50 -0800
    • Engine revision 40a99c5951
    • Dart version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/alexandrsmirnov/Library/Android/sdk/
    • Platform android-31, build-tools 30.0.2
    • ANDROID_HOME = /Users/alexandrsmirnov/Library/Android/sdk/
    • ANDROID_SDK_ROOT = /Users/alexandrsmirnov/Library/Android/sdk/
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.63.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (3 available)
    • Alex iPhoneXsMax (mobile) • 00008020-001E5DA00E01002E            • ios            • iOS 15.1 19B74
    • iPhone 8 (mobile)         • F1CF87BA-FD56-4372-B43C-2FEAD9BE3763 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • Chrome (web)              • chrome                               • web-javascript • Google Chrome 96.0.4664.93
    ! Error: Alex iPhoneXsMax is busy: Making the device ready for development. Xcode will continue when Alex iPhoneXsMax is finished. (code -10)

• No issues found!
```

</details>

**Comment by hamberluo** [comment] 2021-12-15 06:56
same issue

**Comment by mamuseferha** [comment] 2021-12-15 10:11
Hi @AlexSmirnov9107 
Can you please provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
Thank you

**Comment by idompolo** [comment] 2021-12-21 01:37
Just make dozens of fake data into the default listview, build and launch in release mode. There is a difference in scrolling performance.

**Comment by nt4f04uNd** [comment] 2021-12-28 14:57
Duplicate of #95838

**Closed by nt4f04uNd** 2021-12-28 14:57 UTC
Labels: waiting for customer response, in triage
