### ISSUE TITLE
Different steps in a stepper are getting the same state object

### ISSUE THREAD

**Issue by tlarsen7572** [flutter/flutter#20176] opened 2018-08-03 07:48 UTC
## Steps to Reproduce

I am running into an issue where TextEditingControllers, and possibly entire State objects, are somehow getting shared between steps in a Stepper.  I have multiple steps with custom widgets containing textfields and when I move between the steps the text values persist into the next step.

This seems to only manifest when the steps, structurally, are similar (i.e. comprised of the same hierarchy of widgets).  As an example, here is a gist of a custom textfield object:

https://gist.github.com/tlarsen7572/d5ace681ab79f3f1e4797b47d6dbb8e2 (imported by the other 2 gists)

When run with this version of `main.dart`, you can experience the issue:

https://gist.github.com/tlarsen7572/92f976611b64fd2ab5398a12e8023629

But when run with this version of `main.dart`, there is no issue.  Notice that the steps are structurally different, with one step having a Column widget while the other does not:

https://gist.github.com/tlarsen7572/34f67622a289791131d7b0be3d0de6cf

## Logs

flutter analyze output:
```
Analyzing sandbox...                                             
No issues found! (ran in 2.0s)
```

flutter doctor for the beta channel:
```
[✓] Flutter (Channel beta, v0.5.1, on Mac OS X 10.13.6 17G65, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
[✓] Android Studio (version 3.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] IntelliJ IDEA Ultimate Edition (version 2018.2)
[✓] Connected devices (1 available)

• No issues found!
```

flutter doctor for the dev channel:
```
[✓] Flutter (Channel dev, v0.5.7, on Mac OS X 10.13.6 17G65, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
[✓] Android Studio (version 3.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] IntelliJ IDEA Ultimate Edition (version 2018.2)
[✓] Connected devices (1 available)

• No issues found!
```

**Comment by zoechi** [comment] 2019-01-29 13:30
I think the issue is that `Step` should allow to pass a `key`.
@HansMuller ?

**Comment by TahaTesser** [comment] 2020-04-22 13:33
Hi @tlarsen7572 
Are you still experiencing this issue with latest stable?
If yes, can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful
if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by iapicca** [comment] 2020-05-26 15:03
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by iapicca** 2020-05-26 15:03 UTC
Labels: f: material design, framework, waiting for customer response
