### ISSUE TITLE
Firestore timestamp crashed

### ISSUE THREAD

**Issue by renefloor** [flutter/flutter#12437] opened 2017-10-06 17:36 UTC
## Steps to Reproduce

I added the firebase_firestore to my app. In the firebase console I added a document with a timestamp. I tried to get that document in my app, but than it crashes. The MethodChannel doesn't accept timestamps. I use version "^0.0.1+1".

## Logs

```
java.lang.IllegalArgumentException: Unsupported value: Thu Sep 28 08:00:00 GMT+02:00 2017
	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:250)
	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:247)
	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:247)
	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:239)
	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:247)
	at io.flutter.plugin.common.StandardMethodCodec.encodeMethodCall(StandardMethodCodec.java:31)
	at io.flutter.plugin.common.MethodChannel.invokeMethod(MethodChannel.java:82)
	at io.flutter.plugin.common.MethodChannel.invokeMethod(MethodChannel.java:69)
```

**Comment by sethladd** [comment] 2017-10-06 18:10
cc @kroikie @collinjackson

**Comment by collinjackson** [comment] 2017-10-06 18:15
Are you trying to use the current server timestamp value or some other `DateTime` value?

If it's the former, we have a solution for firebase_database and should investigate whether to do the same for Firestore.

**Comment by renefloor** [comment] 2017-10-06 18:43
@collinjackson Not sure what the data type is, I was trying to figure that out. I create a document directly in the firebase console as type timestamp. Is that what you mean with "the current server timestamp"? 
![screen shot 2017-10-06 at 20 41 30](https://user-images.githubusercontent.com/15101411/31293255-e8e42bf6-aad6-11e7-826a-08450d77ff3b.png)

**Comment by pauldemarco** [comment] 2017-10-07 20:50
One approach would be to convert Dart "DateTime" objects to standard UTC milliseconds for transport over the channel, than convert into the appropriate Android/iOS date types (or whatever the firestore SDK is using).

Looking forward to this, keep up the good work :)

**Comment by collinjackson** [comment] 2017-10-09 17:14
@pauldemarco I agree, the only question is whether this should be done automatically by the plugin system or whether we should make every plugin do it manually.

**Comment by pauldemarco** [comment] 2017-10-09 17:29
IMO, since the **timestamp** is a propriety Firestore data type, it would be okay to let the conversion to and from DateTime happen automatically _within_ the plugin. That is how the web SDK for Firestore handles it, we simply send/receive Javascript Date objects to and from.

**Comment by renefloor** [comment] 2017-10-09 18:46
@collinjackson do you have any idea whether this can be fixed soon like next week or that I should make a work around for now?

**Comment by collinjackson** [comment] 2017-10-09 19:00
It looks like it should be a pretty easy fix.. I am busy for the next few days but happy to review pull requests on the flutter/plugins repo if you want a fix faster -- just make sure to tag me on them.

**Comment by renefloor** [comment] 2017-10-09 19:59
I don't have much time either. Will make a pull request when it isn't fixed before I have time.

**Comment by pauldemarco** [comment] 2017-10-12 18:01
It doesn't look like there's a hidden solution to this: https://groups.google.com/forum/#!topic/google-cloud-firestore-discuss/VKFNZhcF3qQ

**Comment by lucamtudor** [comment] 2018-02-28 15:07
any progress?

**Comment by todorescu** [comment] 2018-02-28 16:20
Wondering about the progress as well...

**Comment by outermeasure** [comment] 2018-02-28 16:21
Would anyone know what would be a good workaround?

**Comment by kenticus** [comment] 2018-02-28 16:59
@collinjackson did you guys make any headway on this one? It's currently a blocker for us.

**Comment by lucamtudor** [comment] 2018-03-01 16:22
If you need to use to unblock your project, use the following fork (it has been updated with master) in your pubspec.yaml:
```
dependencies:
  cloud_firestore:
    git:
      url: git@github.com:theshiftstudio/flutter_plugins.git
      ref: 9cabcc57e63fbc9be4fafee08e6435a1a8c71d61
      path: packages/cloud_firestore
```

**Comment by bjornbjorn** [comment] 2018-03-07 12:18
We've worked around this by making sure all dates are stored as strings in Firestore. However, we do a lot of import of data from external providers, and sometimes a timestamp will sneak itself into our dataset. That is currently a huge pain cause it will crash the app, and we'll have to find the offending timestamp (not always easy), remove it/convert to string, and then tell all beta testers to uninstall the app and reinstall it (since data is cached on the client).

So, hopefully this will be fixed soon :)

**Comment by ashtonthomas** [comment] 2018-03-07 14:19
FWIW, I'm hitting this issue with `timestamp` as well as `FIRDocumentReference` (stack trace below).

I'm going to limp along using Strings or removing the fields if I can do without for now.

## timestamp

```
Unsupported value: Thu Oct 10 00:00:00 1987 of type __NSTaggedDate
Lost connection to device.
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010aaf812b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x000000010a194f41 objc_exception_throw + 48
	2   CoreFoundation                      0x000000010aafd2f2 +[NSException raise:format:arguments:] + 98
	3   Foundation                          0x00000001082a1d69 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 193
	4   Flutter                             0x0000000108a98692 -[FlutterStandardWriter writeValue:] + 2110
	5   Flutter                             0x0000000108a985b8 -[FlutterStandardWriter writeValue:] + 1892
	6   Flutter                             0x0000000108a985b8 -[FlutterStandardWriter writeValue:] + 1892
	7   Flutter                             0x0000000108a98443 -[FlutterStandardWriter writeValue:] + 1519
	8   Flutter    <…>
```

## FIRDocumentReference

```
Unsupported value: <FIRDocumentReference: 0x60400142d2e0> of type FIRDocumentReference
SNAP: {name: half marathon}
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010f3b112b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x000000010ea45f41 objc_exception_throw + 48
	2   CoreFoundation                      0x000000010f3b62f2 +[NSException raise:format:arguments:] + 98
	3   Foundation                          0x000000010e4e6d69 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 193
	4   Flutter                             0x000000010c609692 -[FlutterStandardWriter writeValue:] + 2110
	5   Flutter                             0x000000010c609443 -[FlutterStandardWriter writeValue:] + 1519
	6   Flutter                             0x000000010c6095b8 -[FlutterStandardWriter writeValue:] + 1892
	7   Flutter                             0x000000010c6095b8 -[FlutterStandardWriter writeValue:] + 1892
	8   Flutter    <…>
Lost connection to device.
```

**Comment by Samaritan1011001** [comment] 2018-03-13 10:20
Any update on this?

**Comment by bjornbjorn** [comment] 2018-03-13 13:42
It's being worked on here: https://github.com/flutter/plugins/pull/343

Looks like we're getting close 👍

**Comment by jlouage** [comment] 2018-03-15 10:30
any update???

**Comment by Skylled** [comment] 2018-03-23 14:11
Can be closed, via flutter/plugins#429

**Closed** 2018-03-23 14:13 UTC
Labels: plugin, plugin: firebase

**Comment by AcnodeLabs** [comment] 2019-05-01 05:50
Just use Timestamp.now()  it worked for me

**Comment by shahviral9990** [comment] 2019-05-19 05:59
> Just use Timestamp.now() it worked for me

internally it's calling DateTime.now().microsecondsSinceEpoch means local time, which is not servertime

**Comment by kroikie** [comment] 2019-10-13 19:24
@renefloor

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/958. Any further collaboration will be done there.

**Comment by lvlrSajjad** [comment] 2020-07-05 11:03
Still have this crash problem
Using
```
FieldValue.serverTimestamp()
```
Causes crash in ios, I'm not sure about android ...

**Comment by masloyet** [comment] 2020-07-07 05:28
I am having the same issue with `FieldValue.serverTimestamp()`. Is this fieldvalue not implemented with the current version of flutterfire? I would prefer to use the timestamping natively supported on firestore.

**Comment by masloyet** [comment] 2020-07-10 07:21
@lvlrSajjad I switched over to `Timestamp.now()` and it seems to work in the way that `FieldValue.serverTimestamp()` was intended to.
