### ISSUE TITLE
The following assertion was thrown during a scheduler callback: 'package:flutter/src/rendering/object.dart': Failed assertion: line 1145 pos 20: 'node.isRepaintBoundary': is not true.

### ISSUE THREAD

**Issue by 2804955436xzj** [flutter/flutter#131376] opened 2023-07-27 02:27 UTC
======== Exception caught by scheduler library =====================================================
The following assertion was thrown during a scheduler callback:
'package:flutter/src/rendering/object.dart': Failed assertion: line 1145 pos 20: 'node.isRepaintBoundary': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      PipelineOwner.flushPaint (package:flutter/src/rendering/object.dart:1145:20)
#3      RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:494:19)
#4      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:905:13)
#5      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:358:5)
#6      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1284:15)
#7      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1214:9)
#8      SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1072:5)
#9      _invoke (dart:ui/hooks.dart:142:13)
#10     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:359:5)
#11     _drawFrame (dart:ui/hooks.dart:112:31)
(elided 2 frames from class _AssertionError)
这个错误怎么解决。

**Comment by 2804955436xzj** [comment] 2023-07-27 02:34
How to fix this error.

**Comment by danagbemava-nc** [comment] 2023-07-27 06:40
Closing this as a duplicate of https://github.com/flutter/flutter/issues/120874 based on the logs shared above. 

Kindly subscribe to the original issue for updates. 

Thank you

**Closed by danagbemava-nc** 2023-07-27 06:40 UTC
Labels: in triage
