### ISSUE TITLE
Image picker doesnt work on Phisical Device on Android 10 redNote pro

### ISSUE THREAD

**Issue by wytex** [flutter/flutter#75966] opened 2021-02-13 12:21 UTC
I have build my application on flutter and all is finished on emulator it working fine.
On Phisical device Android 10 RedNote pro I have some problem.
When I call function to open gallery or take a picture in first instance it work, you can take a picture or get image from gallery, but when you choose it or pick it, the Application doesnt load the image into the APP and even also the images loaded from emulator can't be loaded into the APP from Firestore.
On emulator everything work pretty good, but when I build APK and put it into my mobile Phone it doesnt.
the Steps are the followed:

Build APK and install on mobile

Run APP on Mobile and everything works fine except what I wrote above .

I part of the code where I call the function:

```
File _imageFile;
  final picker = ImagePicker();

  Future pickImage() async {
    final pickedFile = await picker.getImage(source: ImageSource.camera);

    setState(() {
      _imageFile = File(pickedFile.path);
    });
  }

  Future chooseImage() async {
    final pickedFile = await picker.getImage(source: ImageSource.gallery);

    setState(() {
      _imageFile = File(pickedFile.path);
    });
  }

  var firebaseUser =  FirebaseAuth.instance.currentUser;


  Future uploadImage(BuildContext context) async {
    String fileName = basename(_imageFile.path);
    Reference firebaseStorageRef =
    FirebaseStorage.instance.ref().child('consultantProfile/$fileName');
    UploadTask uploadTask = firebaseStorageRef.putFile(_imageFile);
    TaskSnapshot taskSnapshot = await uploadTask.whenComplete(() => null);
    final String downloadAvatar = await taskSnapshot.ref.getDownloadURL();
    await FirebaseFirestore.instance.collection('Consultant').doc(firebaseUser.uid)
        .update({"avatarImage": downloadAvatar,});
    Navigator.pop(context);
  }

  bool showSpinner = false;



  @override
  Widget build(BuildContext context) {
    return ModalProgressHUD(
      inAsyncCall: showSpinner,
      child: AlertDialog(
        elevation: 20,
        content: Column(
          mainAxisSize: MainAxisSize.min,
            mainAxisAlignment: MainAxisAlignment.center, children: <
            Widget>[
          _imageFile == null
              ? CircleAvatar(
            radius: 60,
            backgroundColor: Colors.grey[300],
            backgroundImage: AssetImage('assets/images/profileavatar.png'),
          )
              : CircleAvatar(
            radius: 66,
            backgroundImage:
            AssetImage('assets/images/background_circle.gif'),
            child: CircleAvatar(
              radius: 63,
              backgroundColor: Colors.white,
              child: CircleAvatar(
                radius: 60,
                backgroundImage: FileImage(_imageFile),
              ),
            ),
          ),
          SizedBox(
            height: 10,
          ),

```

my ``` flutter doctor -v``` and ```flutter run --verbose```

```
 Flutter (Channel stable, 1.22.6, on Linux, locale en_US.UTF-8)
    • Flutter version 1.22.6 at /home/wytex/snap/flutter/common/flutter
    • Framework revision 9b2d32b605 (3 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/wytex/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+9-Ubuntu-0ubuntu1.20.04)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/linux#android-setup for more details.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

! Doctor found issues in 2 categories.


```

 
```
[        ]            #0      KernelSnapshot.build (package:flutter_tools/src/build_system/targets/common.dart:267:7)
[        ]            <asynchronous suspension>
[        ]            #1      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:801:27)
[        ]            #2      _rootRunUnary (dart:async/zone.dart:1198:47)
[        ]            #3      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
[        ]            #4      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
[        ]            #5      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
[        ]            #6      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
[        ]            #7      Future._completeWithValue (dart:async/future_impl.dart:529:5)
[        ]            #8      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
[        ]            #9      _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
[        ]            #10     Node.computeChanges (package:flutter_tools/src/build_system/build_system.dart)
[        ]            #11     _rootRunUnary (dart:async/zone.dart:1198:47)
[        ]            #12     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
[        ]            #13     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
[        ]            #14     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
[        ]            #15     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
[        ]            #16     Future._completeWithValue (dart:async/future_impl.dart:529:5)
[        ]            #17     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
[        ]            #18     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
[        ]            #19     FileStore.diffFileList (package:flutter_tools/src/build_system/file_store.dart)
[        ]            #20     _rootRunUnary (dart:async/zone.dart:1198:47)
[        ]            #21     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
[        ]            #22     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
[        ]            #23     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
[        ]            #24     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
[        ]            #25     Future._completeWithValue (dart:async/future_impl.dart:529:5)
[        ]            #26     Future.wait.<anonymous closure> (dart:async/future.dart:414:23)
[        ]            #27     _rootRunUnary (dart:async/zone.dart:1198:47)
[        ]            #28     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
[        ]            #29     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
[        ]            #30     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
[        ]            #31     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
[        ]            #32     Future._completeWithValue (dart:async/future_impl.dart:529:5)
[        ]            #33     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
[        ]            #34     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
[        ]            #35     FileStore._hashFile (package:flutter_tools/src/build_system/file_store.dart)
[        ]            #36     _rootRunUnary (dart:async/zone.dart:1198:47)
[        ]            #37     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
[        ]            #38     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
[        ]            #39     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
[        ]            #40     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
[        ]            #41     Future._completeWithValue (dart:async/future_impl.dart:529:5)
[        ]            #42     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
[        ]            #43     _rootRun (dart:async/zone.dart:1190:13)
[        ]            #44     _CustomZone.run (dart:async/zone.dart:1093:19)
[        ]            #45     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
[        ]            #46     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
[        ]            #47     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
[        ]            #48     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
[        ]            #49     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
[        ]            #50     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
[  +96 ms] [   +5 ms] 
[        ]            #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
[        ]            #1      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:238:7)
[        ]            #2      _rootRunUnary (dart:async/zone.dart:1198:47)
[        ]            #3      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
[        ]            #4      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
[        ]            #5      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
[        ]            #6      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
[        ]            #7      Future._completeWithValue (dart:async/future_impl.dart:529:5)
[        ]            #8      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
[        ]            #9      _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
[        ]            #10     FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart)
[        ]            #11     _rootRunUnary (dart:async/zone.dart:1198:47)
[        ]            #12     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
[        ]            #13     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
[        ]            #14     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
[        ]            #15     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
[        ]            #16     Future._completeWithValue (dart:async/future_impl.dart:529:5)
[        ]            #17     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
[        ]            #18     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
[        ]            #19     _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart)
[        ]            #20     _rootRunUnary (dart:async/zone.dart:1198:47)
[        ]            #21     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
[        ]            #22     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
[        ]            #23     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
[        ]            #24     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
[        ]            #25     Future._completeWithValue (dart:async/future_impl.dart:529:5)
[        ]            #26     Future.wait.<anonymous closure> (dart:async/future.dart:414:23)
[        ]            #27     _rootRunUnary (dart:async/zone.dart:1198:47)
[        ]            #28     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
[        ]            #29     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
[        ]            #30     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
[        ]            #31     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
[        ]            #32     Future._completeWithValue (dart:async/future_impl.dart:529:5)
[        ]            #33     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
[        ]            #34     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
[        ]            #35     _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart)
[        ]            #36     _asyncErrorWrapperHelper.errorCallback (dart:async-patch/async_patch.dart:91:64)
[        ]            #37     _rootRunBinary (dart:async/zone.dart:1214:47)
[        ]            #38     _CustomZone.runBinary (dart:async/zone.dart:1107:19)
[        ]            #39     _FutureListener.handleError (dart:async/future_impl.dart:157:20)
[        ]            #40     Future._propagateToListeners.handleError (dart:async/future_impl.dart:708:47)
[        ]            #41     Future._propagateToListeners (dart:async/future_impl.dart:729:24)
[        ]            #42     Future._completeError (dart:async/future_impl.dart:537:5)
[        ]            #43     _AsyncAwaitCompleter.completeError (dart:async-patch/async_patch.dart:47:15)
[        ]            #44     KernelSnapshot.build (package:flutter_tools/src/build_system/targets/common.dart)
[        ]            #45     _rootRunUnary (dart:async/zone.dart:1198:47)
[        ]            #46     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
[        ]            #47     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
[        ]            #48     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
[        ]            #49     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
[        ]            #50     Future._completeWithValue (dart:async/future_impl.dart:529:5)
[        ]            #51     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
[        ]            #52     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
[        ]            #53     KernelCompiler.compile (package:flutter_tools/src/compile.dart)
[        ]            #54     _rootRunUnary (dart:async/zone.dart:1198:47)
[        ]            #55     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
[        ]            #56     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
[        ]            #57     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
[        ]            #58     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
[        ]            #59     Future._completeWithValue (dart:async/future_impl.dart:529:5)
[        ]            #60     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
[        ]            #61     _rootRun (dart:async/zone.dart:1190:13)
[        ]            #62     _CustomZone.run (dart:async/zone.dart:1093:19)
[        ]            #63     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
[        ]            #64     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
[        ]            #65     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
[        ]            #66     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
[        ]            #67     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
[        ]            #68     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
[        ] FAILURE: Build failed with an exception.
[        ] * Where:
[        ] Script '/home/wytex/snap/flutter/common/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 904
[        ] * What went wrong:
[        ] Execution failed for task ':app:compileFlutterBuildDebug'.
[        ] > Process 'command '/home/wytex/snap/flutter/common/flutter/bin/flutter'' finished with non-zero exit value 1
[        ] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[        ] * Get more help at https://help.gradle.org
[        ] BUILD FAILED in 29s
[        ] [   +1 ms] ensureAnalyticsSent: 0ms
[        ] [   +1 ms] Running shutdown hooks
[        ] [        ] Shutdown hooks complete
[        ] [        ] exiting with code 1
[        ] > Task :app:compileFlutterBuildDebug FAILED
[        ] Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
[        ] Use '--warning-mode all' to show the individual deprecation warnings.
[        ] See https://docs.gradle.org/6.7/userguide/command_line_interface.html#sec:command_line_warnings
[        ] 1 actionable task: 1 executed
[ +503 ms] Running Gradle task 'assembleDebug'... (completed in 29.8s)
[  +16 ms] Exception: Gradle task assembleDebug failed with exit code 1
[   +2 ms] "flutter run" took 31,044ms.
[  +15 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:607:7)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:977:18)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:836:33)
           <asynchronous suspension>
           #4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart)
           #5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
           #6      _rootRun (dart:async/zone.dart:1190:13)
           #7      _CustomZone.run (dart:async/zone.dart:1093:19)
           #8      _runZoned (dart:async/zone.dart:1630:10)
           #9      runZoned (dart:async/zone.dart:1550:10)
           #10     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
           #11     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:825:20)
           #12     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
           #13     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:335:21)
           #14     _rootRunUnary (dart:async/zone.dart:1198:47)
           #15     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #16     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #17     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #18     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #19     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #20     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #21     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #22     FlutterVersion.checkFlutterVersionFreshness (package:flutter_tools/src/version.dart)
           #23     _rootRunUnary (dart:async/zone.dart:1198:47)
           #24     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #25     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #26     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #27     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #28     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #29     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
           #30     _rootRun (dart:async/zone.dart:1190:13)
           #31     _CustomZone.run (dart:async/zone.dart:1093:19)
           #32     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #33     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
           #34     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #35     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #36     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
           #37     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
           
           
[   +8 ms] Running shutdown hooks
[        ] Shutdown hook priority 4
[   +7 ms] Shutdown hooks complete
[   +3 ms] exiting with code 1

```

**Comment by pierrethenot** [comment] 2021-02-13 13:20
same here !

**Comment by iapicca** [comment] 2021-02-13 13:53
@wytex 
you code sample includes 3rd party plugins like [firebase](https://firebase.flutter.dev/)

testing the latest version of the plugin on the latest master

<details>
<summary>code sample</summary>

```dart
import 'dart:io';
import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';

Future<Image> pickImage() async {
  final picked = await ImagePicker().getImage(
    source: ImageSource.gallery,
  );
  return Image.file(File(picked.path));
}

final image = ValueNotifier<Image>(null);

void main() => runApp(
      MaterialApp(
        home: Material(
          child: Center(
            child: ValueListenableBuilder<Image>(
              valueListenable: image,
              child: ElevatedButton(
                child: Icon(Icons.image),
                onPressed: () async => image.value = await pickImage(),
              ),
              builder: (context, image, child) => image == null
                  ? child
                  : SizedBox.fromSize(
                      size: Size.square(
                          MediaQuery.of(context).size.shortestSide * .7),
                      child: image),
            ),
          ),
        ),
      ),
    );

```

</details>
<details>
<summary>pubspec</summary> 

```yaml
name: issue
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.6.7+22

flutter:
  uses-material-design: true

```

</details>

<details>
<summary>screenshot</summary>

![Screenshot_20210213-154022](https://user-images.githubusercontent.com/45637986/107851474-e11a5c80-6e12-11eb-8ae2-aedc8977b8f7.png)

</details>

<details>
<summary>logs</summary>

```bash
[ +156 ms] Syncing files to device Pixel 3a...
[   +1 ms] <- reset
[        ] Compiling dart to kernel with 0 updated files
[   +2 ms] <- recompile package:issue/main.dart cbba1214-90a0-4745-814b-87e05381ec1f
[        ] <- cbba1214-90a0-4745-814b-87e05381ec1f
[ +112 ms] Updating files.
[        ] DevFS: Sync finished
[   +1 ms] Syncing files to device Pixel 3a... (completed in 117ms)
[   +1 ms] Synced 0.0MB.
[        ] <- accept
[  +17 ms] Connected to _flutterView/0x7633a02690.
[   +2 ms] Flutter run key commands.
[   +2 ms] r Hot reload. 🔥🔥🔥
[   +1 ms] R Hot restart.
[        ] h Repeat this help message.
[        ] d Detach (terminate "flutter run" but leave application running).
[        ] c Clear the screen
[        ] q Quit (terminate the application on the device).
[        ] Running with unsound null safety
[        ] For more information see https://dart.dev/null-safety/unsound-null-safety
[        ] An Observatory debugger and profiler on Pixel 3a is available at: http://127.0.0.1:45813/h6HJPwmaZI8=/
[ +202 ms] Activating Dart DevTools...
[+3368 ms] Activating Dart DevTools... (completed in 3.4s)
[ +853 ms] The Flutter DevTools debugger and profiler on Pixel 3a is available at: http://127.0.0.1:9101?uri=http%3A%2F%2F127.0.0.1%3A45813%2Fh6HJPwmaZI8%3D%2F
[+28948 ms] Service protocol connection closed.
[        ] Lost connection to device.
[   +2 ms] executing: /home/francesco/Android/Sdk/platform-tools/adb -s 965AY0WP5C forward --list
[  +13 ms] Exit code 0 from: /home/francesco/Android/Sdk/platform-tools/adb -s 965AY0WP5C forward --list
[        ] 965AY0WP5C tcp:44395 tcp:40873
[   +1 ms] executing: /home/francesco/Android/Sdk/platform-tools/adb -s 965AY0WP5C forward --remove tcp:44395
[   +8 ms] DevFS: Deleting filesystem on the device (file:///data/user/0/com.example.issue/code_cache/issueMBKCWE/issue/)
[ +257 ms] Ignored error while cleaning up DevFS: TimeoutException after 0:00:00.250000: Future not completed
[   +7 ms] executing: /home/francesco/Android/Sdk/platform-tools/adb -s 965AY0WP5C forward --list
[  +30 ms] Exit code 0 from: /home/francesco/Android/Sdk/platform-tools/adb -s 965AY0WP5C forward --list
[  +16 ms] "flutter run" took 147,997ms.
[ +277 ms] ensureAnalyticsSent: 258ms
[   +7 ms] Running shutdown hooks
[   +1 ms] Shutdown hook priority 4
[  +16 ms] Shutdown hooks complete
[   +5 ms] exiting with code 0

```
</details>
<details>
<summary>doctor</summary>

```console
[✓] Flutter (Channel master, 1.27.0-2.0.pre.96, on Linux, locale en_US.UTF-8)
    • Flutter version 1.27.0-2.0.pre.96 at /home/francesco/snap/flutter/common/flutter
    • Framework revision 8104c5786d (11 hours ago), 2021-02-12 21:41:03 -0500
    • Engine revision 1d537824d6
    • Dart version 2.13.0 (build 2.13.0-30.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/francesco/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_SDK_ROOT = /home/francesco/Android/Sdk
    • Java binary at: /usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_282-8u282-b08-0ubuntu1~20.04-b08)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /snap/bin/chromium

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] Connected device (3 available)
    • Pixel 3a (mobile) • 965AY0WP5C • android-arm64  • Android 11 (API 30)
    • Linux (desktop)   • linux      • linux-x64      • Linux
    • Chrome (web)      • chrome     • web-javascript • Chromium 88.0.4324.150 snap

! Doctor found issues in 1 category.
```

</details>

it seems to work as intended
if the code sample I provided doesn't represent your case
please try provide a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn't involve 3rd party plugins

**Comment by wytex** [comment] 2021-02-13 14:19
I have write another code and this work on Mobile and also on Emulator:

```
void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  File _image;
  final picker = ImagePicker();

  Future getImage() async {
    final pickedFile = await picker.getImage(source: ImageSource.camera);

    setState(() {
      if (pickedFile != null) {
        _image = File(pickedFile.path);
      } else {
        print('No image selected.');
      }
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Image Picker Example'),
      ),
      body: Center(
        child: _image == null
            ? Text('No image selected.')
            : Image.file(_image),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: getImage,
        tooltip: 'Pick Image',
        child: Icon(Icons.add_a_photo),
      ),
    );
  }
}

```

my code below instead work only on Emulator:

```
class ImageProfileAlert extends StatefulWidget {
  @override
  _ImageProfileAlertState createState() => _ImageProfileAlertState();
}

class _ImageProfileAlertState extends State<ImageProfileAlert> {
  File _imageFile;
  final picker = ImagePicker();

  Future pickImage() async {
    final pickedFile = await picker.getImage(source: ImageSource.camera);

    setState(() {
      _imageFile = File(pickedFile.path);
    });
  }

  Future chooseImage() async {
    final pickedFile = await picker.getImage(source: ImageSource.gallery);

    setState(() {
      _imageFile = File(pickedFile.path);
    });
  }

  var firebaseUser =  FirebaseAuth.instance.currentUser;


  Future uploadImage(BuildContext context) async {
    String fileName = basename(_imageFile.path);
    Reference firebaseStorageRef =
    FirebaseStorage.instance.ref().child('consultantProfile/$fileName');
    UploadTask uploadTask = firebaseStorageRef.putFile(_imageFile);
    TaskSnapshot taskSnapshot = await uploadTask.whenComplete(() => null);
    final String downloadAvatar = await taskSnapshot.ref.getDownloadURL();
    await FirebaseFirestore.instance.collection('Consultant').doc(firebaseUser.uid)
        .update({"avatarImage": downloadAvatar,});
    Navigator.pop(context);
  }

  bool showSpinner = false;



  @override
  Widget build(BuildContext context) {
    return ModalProgressHUD(
      inAsyncCall: showSpinner,
      child: AlertDialog(
        elevation: 20,
        content: Column(
          mainAxisSize: MainAxisSize.min,
            mainAxisAlignment: MainAxisAlignment.center, children: <
            Widget>[
          _imageFile == null
              ? CircleAvatar(
            radius: 60,
            backgroundColor: Colors.grey[300],
            backgroundImage: AssetImage('assets/images/profileavatar.png'),
          )
              : CircleAvatar(
            radius: 66,
            backgroundImage:
            AssetImage('assets/images/background_circle.gif'),
            child: CircleAvatar(
              radius: 63,
              backgroundColor: Colors.white,
              child: CircleAvatar(
                radius: 60,
                backgroundImage: FileImage(_imageFile),
              ),
            ),
          ),
          SizedBox(
            height: 10,
          ),
          _imageFile == null
              ? Text(
            'Aggiungi un immagine profilo',
            textAlign: TextAlign.center,
            style: TextStyle(color: Colors.black, fontSize: 14),
          )
              : Column(
            children: [
              RaisedButton(
                elevation: 10,
                color: Colors.orange,
                child: Text(
                  'CARICA IMMAGINE PROFILO',
                  textAlign: TextAlign.center,
                  style: TextStyle(color: Colors.white, fontSize: 10),
                ),
                onPressed: () {
                  setState(() {
                    uploadImage(context);
                    showSpinner = true;
                  });

                },
              ),
              SizedBox(height: 20,),
              GestureDetector(
                onTap: (){
                  chooseImage();
                },
                child: Row(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: [
                    Icon(
                      Icons.add_a_photo,
                      color: Colors.black,
                      size: 18,
                    ),
                    Text(
                      '    Cambia immagine',
                      style: TextStyle(
                          fontSize: 10, color: Colors.black),
                    ),
                  ],
                ),
              )
            ],
          ),
          SizedBox(height: 20,),
          _imageFile == null
              ? Row(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              Container(
                height: 60,
                width: 100,
                child: RaisedButton(
                  elevation: 10,
                  color: Colors.orange,
                  child: Text(
                    'SCATTA UNA FOTO',
                    textAlign: TextAlign.center,
                    style: TextStyle(color: Colors.white, fontSize: 10),
                  ),
                  onPressed: () {
                    pickImage();
                  },
                ),
              ),
              SizedBox(
                width: 15,
              ),
              Container(
                height: 60,
                width: 100,
                child: RaisedButton(
                  elevation: 10,
                  color: Colors.orange,
                  child: Text(
                    'AGGIUNGI DALLA GALLERIA',
                    textAlign: TextAlign.center,
                    style: TextStyle(color: Colors.white, fontSize: 10),
                  ),
                  onPressed: () {
                    chooseImage();
                  },
                ),
              ),
            ],
          )
              : Row(),
        ]),
      ),
    );
  }
}
```

**Comment by wytex** [comment] 2021-02-13 14:47
this is the Video on Emulator: https://youtu.be/QnLEKx9p6xI
and this one on real device: https://youtu.be/zFJ8fn_Rjbs
As you can see on Phisical device the first click on device camera it ask for permission and then stop to work... and then again on clicking on the button and nothing happen, instead into emulator all is fine.

**Comment by wytex** [comment] 2021-02-13 15:05
Another indication of this issue is when I load image on emulator it working fine even on my Chat and it retrieve correctly the image from Firestore, in the next picture, I am trying to retreive on my chat the images from firestore but nothing progress indicator run infinitely...

![WhatsApp Image 2021-02-13 at 15 58 51](https://user-images.githubusercontent.com/60034256/107853286-496a3d80-6e15-11eb-97bb-98e85222c474.jpeg)

**Comment by wytex** [comment] 2021-02-13 16:09
thansk to this post: https://stackoverflow.com/questions/65153739/flutter-cachednetworkimage-doesnt-work-for-app-downloaded-from-playstore-stuck
I have find a workaround to fix this is adding to my build.gradle :
```
buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled true // Add these lines
            shrinkResources true // Add these lines
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt') // Add these lines
        }
    }
```
It seems fixed

**Comment by iapicca** [comment] 2021-02-13 19:58
@wytex 
I'm glad you found a solution
if the problem is solved please close the issue

**Comment by wytex** [comment] 2021-02-14 10:23
This was the problem related  to APK release:
```
buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled true // Add these lines
            shrinkResources true // Add these lines
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt') // Add these lines
        }
    }
```

**Closed** 2021-02-14 10:23 UTC
