### ISSUE TITLE
Failed creating iOS build: "Could not build Objective-C module" error occurs while developing Flutter plugin

### ISSUE THREAD

**Issue by gyuri-fluttech** [flutter/flutter#94719] opened 2021-12-06 11:40 UTC
## Steps to Reproduce

I am currently developing a Flutter plugin and I stumble upon the following issue. 

## Logs

<details>
<summary>Error logs</summary>

```
    remark: Incremental compilation has been disabled: it is not compatible with whole module optimization
    <module-includes>:1:9: note: in file included from <module-includes>:1:
    #import "azure_cognitive_services-umbrella.h"
            ^
    /Users/gyuri/example_flutter/ios/Pods/Headers/Public/azure_cognitive_services/azure_cognitive_services-umbrella.h:13:9: note: in file included from
    /Users/gyuri/example_flutter/ios/Pods/Headers/Public/azure_cognitive_services/azure_cognitive_services-umbrella.h:13:
    #import "AzureCognitiveServicesPlugin.h"
            ^
    /Users/gyuri/example_flutter/ios/Pods/Headers/Public/azure_cognitive_services/AzureCognitiveServicesPlugin.h:2:9: error: 'MicrosoftCognitiveServicesSpeech/SPXSpeechAPI.h' file not found
    #import <MicrosoftCognitiveServicesSpeech/SPXSpeechAPI.h>
            ^
    <unknown>:0: error: could not build Objective-C module 'azure_cognitive_services'
    Command CompileSwiftSources failed with a nonzero exit code
    remark: Incremental compilation has been disabled: it is not compatible with whole module optimization
    Command CompileSwiftSources failed with a nonzero exit code
    remark: Incremental compilation has been disabled: it is not compatible with whole module optimization
```
</details>

The plugin I am working has a dependency: `MicrosoftCognitiveServicesSpeech-iOS` 

## Plugin `podspec` file 

<details>
<summary>azure_cognitive_services.podspec</summary>

```
#
# To learn more about a Podspec see http://guides.cocoapods.org/syntax/podspec.html.
# Run `pod lib lint azure_cognitive_services.podspec` to validate before publishing.
#
require 'yaml'

pubspec = YAML.load_file(File.join('..', 'pubspec.yaml'))
library_version = pubspec['version'].gsub('+', '-')

microsoft_cognitive_services_speech_ios_version = '1.19.0'

Pod::UI.puts "#{pubspec['name']}: Using Cognitive Services Speech SDK version '#{microsoft_cognitive_services_speech_ios_version}' defined in 'azure_cognitive_services'"

Pod::Spec.new do |s|
  s.name             = pubspec['name']
  s.version          = library_version
  s.summary          = pubspec['description']
  s.description      = pubspec['description']
  s.homepage         = pubspec['homepage']
  s.license          = { :file => '../LICENSE' }
  s.author           = { 'Author' => 'author@example.com' }
  s.source           = { :path => '.' }
  s.source_files = 'Classes/**/*'
  s.ios.deployment_target = '10'

  # Flutter dependencies
  s.dependency 'Flutter'

  # Azure Cognitive Services dependencies
  s.dependency 'MicrosoftCognitiveServicesSpeech-iOS', "#{microsoft_cognitive_services_speech_ios_version}"

  s.static_framework = true
  # Flutter.framework does not contain a i386 slice.
  s.pod_target_xcconfig = { 'DEFINES_MODULE' => 'YES', 'EXCLUDED_ARCHS[sdk=iphonesimulator*]' => 'i386' }
  s.swift_version = '5.0'
end
```

</details>

I was getting the same issue when tried to run the app on my iOS device but after applying the solution from [here](https://github.com/flutter/flutter/issues/85951#issuecomment-903801860) it started to work. 

But that wasn't sufficient. 

The same issue reappeared when I tried to create a build with `flutter build ios` or `flutter build ipa` . 

This might be related to issue #16049 but I am clueless and didn't find anything helpful.

**Comment by danagbemava-nc** [comment] 2021-12-06 14:15
Hi @gyuri-fluttech, thanks for filing the issue. 

Can you please provide the full output of `flutter build ios -v` or `flutter build ipa -v`? The output is likely to be huge, so please put it into a .txt file and attach it here. 

Thank you

**Comment by gyuri-fluttech** [comment] 2021-12-06 14:31
@danagbemava-nc , thanks for looking into this. 

You can find the logs below: 

* `flutter build ios -v` : [build_log.txt](https://github.com/flutter/flutter/files/7661341/build_log.txt)
* `flutter run -v`: [run_log.txt](https://github.com/flutter/flutter/files/7661365/run_log.txt)

**Comment by danagbemava-nc** [comment] 2021-12-07 04:59
Hi @gyuri-fluttech, can you also share the Podfile of the example app? 

And if possible, a minimal reproducible code sample.

Thank you

**Comment by gyuri-fluttech** [comment] 2021-12-07 09:45
@danagbemava-nc , sure, it should be reproducible with the following `example` app:  

[to_flutter_bug.zip](https://github.com/flutter/flutter/files/7667240/to_flutter_bug.zip)

**Comment by danagbemava-nc** [comment] 2021-12-07 14:46
@gyuri-fluttech, thanks for the sample. 

I was able to repro the build failure. 

Labelling for further insight from the team. 

I do find it odd that the example app runs just fine but building for `ios` fails. 


<details>
<summary>logs</summary>

[build_log.txt](https://github.com/flutter/flutter/files/7669141/build_log.txt)
[run_log.txt](https://github.com/flutter/flutter/files/7669142/run_log.txt)

</details>

<details>
<summary>flutter doctor -v</summary>

```console
[✓] Flutter (Channel stable, 2.5.3, on macOS 11.6 20G165 darwin-arm, locale en-GB)
    • Flutter version 2.5.3 at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (8 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.0, Build version 13A233
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[☠] IntelliJ IDEA Community Edition (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    ✗ FormatException: Unexpected extension byte (at offset 5)
    • #0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1788:7)
      #1      Utf8Decoder.convert (dart:convert/utf.dart:318:42)
      #2      InputStream.readString (package:archive/src/util/input_stream.dart:199:30)
      #3      new ZipDirectory.read (package:archive/src/zip/zip_directory.dart:40:30)
      #4      ZipDecoder.decodeBuffer (package:archive/src/zip_decoder.dart:19:30)
      #5      ZipDecoder.decodeBytes (package:archive/src/zip_decoder.dart:14:12)
      #6      IntelliJPlugins._findPluginXml (package:flutter_tools/src/intellij/intellij.dart:130:44)
      #7      IntelliJPlugins._readPackageVersion (package:flutter_tools/src/intellij/intellij.dart:141:40)
      #8      IntelliJPlugins.validatePackage (package:flutter_tools/src/intellij/intellij.dart:63:35)
      #9      IntelliJValidator.validate (package:flutter_tools/src/intellij/intellij_validator.dart:103:15)
      #10     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      #11     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:109:18)
      #12     _rootRun (dart:async/zone.dart:1428:13)
      #13     _CustomZone.run (dart:async/zone.dart:1328:19)
      #14     _runZoned (dart:async/zone.dart:1863:10)
      #15     runZonedGuarded (dart:async/zone.dart:1851:12)
      #16     runZoned (dart:async/zone.dart:1782:12)
      #17     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #18     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:200:9)
      #19     Doctor.diagnose (package:flutter_tools/src/doctor.dart:304:47)
      #20     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:50:47)
      #21     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1274:12)
      <asynchronous suspension>
      #22     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1125:27)
      <asynchronous suspension>
      #23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #24     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
      <asynchronous suspension>
      #25     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
      <asynchronous suspension>
      #26     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #27     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
      <asynchronous suspension>
      #28     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
      <asynchronous suspension>
      #29     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #30     main (package:flutter_tools/executable.dart:92:3)
      <asynchronous suspension>


[✓] VS Code (version 1.62.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (3 available)
    • iPhone 13 (mobile) • 7515F01A-C1B6-456E-8559-8D2383D3719D • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • macOS (desktop)    • macos                                • darwin-arm64   • macOS 11.6 20G165 darwin-arm
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 96.0.4664.55

! Doctor found issues in 1 category.
```

``console
[✓] Flutter (Channel master, 2.6.0-12.0.pre.935, on macOS 11.6 20G165 darwin-arm, locale en-GB)
    • Flutter version 2.6.0-12.0.pre.935 at /Users/nexus/dev/sdks/flutters
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 94385d79f2 (10 hours ago), 2021-12-06 20:46:12 -0800
    • Engine revision 66a281107b
    • Dart version 2.16.0 (build 2.16.0-80.0.dev)
    • DevTools version 2.9.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[☠] IntelliJ IDEA Community Edition (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    ✗ FormatException: Unexpected extension byte (at offset 5)
    • #0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1789:7)
      #1      Utf8Decoder.convert (dart:convert/utf.dart:351:42)
      #2      InputStream.readString (package:archive/src/util/input_stream.dart:207:30)
      #3      new ZipDirectory.read (package:archive/src/zip/zip_directory.dart:40:30)
      #4      ZipDecoder.decodeBuffer (package:archive/src/zip_decoder.dart:19:30)
      #5      ZipDecoder.decodeBytes (package:archive/src/zip_decoder.dart:14:12)
      #6      IntelliJPlugins._findPluginXml (package:flutter_tools/src/intellij/intellij.dart:130:44)
      #7      IntelliJPlugins._readPackageVersion (package:flutter_tools/src/intellij/intellij.dart:141:40)
      #8      IntelliJPlugins.validatePackage (package:flutter_tools/src/intellij/intellij.dart:63:35)
      #9      IntelliJValidator.validate (package:flutter_tools/src/intellij/intellij_validator.dart:103:15)
      #10     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      #11     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:109:18)
      #12     _rootRun (dart:async/zone.dart:1426:13)
      #13     _CustomZone.run (dart:async/zone.dart:1328:19)
      #14     _runZoned (dart:async/zone.dart:1861:10)
      #15     runZonedGuarded (dart:async/zone.dart:1849:12)
      #16     runZoned (dart:async/zone.dart:1780:12)
      #17     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #18     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:198:9)
      #19     Doctor.diagnose (package:flutter_tools/src/doctor.dart:302:47)
      #20     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:50:48)
      #21     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1320:12)
      <asynchronous suspension>
      #22     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1161:27)
      <asynchronous suspension>
      #23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #24     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
      <asynchronous suspension>
      #25     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
      <asynchronous suspension>
      #26     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #27     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
      <asynchronous suspension>
      #28     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
      <asynchronous suspension>
      #29     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #30     main (package:flutter_tools/executable.dart:94:3)
      <asynchronous suspension>


[✓] VS Code (version 1.62.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (3 available)
    • iPhone 13 (mobile) • 7515F01A-C1B6-456E-8559-8D2383D3719D • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • macOS (desktop)    • macos                                • darwin-arm64   • macOS 11.6 20G165 darwin-arm
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 96.0.4664.55

! Doctor found issues in 1 category.
```
</details>

**Comment by jmagman** [comment] 2021-12-07 18:33
This is an issue with `MicrosoftCognitiveServicesSpeech`, they haven't implemented a clang module in their xcframework so it can't be imported from Swift, you can see `to_flutter_bug/example/ios/Pods/MicrosoftCognitiveServicesSpeech-iOS/MicrosoftCognitiveServicesSpeech.xcframework/ios-arm64_x86_64-maccatalyst/MicrosoftCognitiveServicesSpeech.framework` is missing a `Module` directory. I see reports at https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/919#issuecomment-964911136.

I suggest you re-implement your plugin in Objective-C `flutter create -i obj -t plugin` until they fix the issue. This isn't related to Flutter, it would be an issue with any Swift code importing this framework.  Closing.

**Closed by jmagman** 2021-12-07 18:33 UTC
Labels: platform-ios, a: build, has reproducible steps, found in release: 2.5, found in release: 2.6

**Comment by gyuri-fluttech** [comment] 2021-12-08 07:52
I'm not very familiar with iOS development, but seems strange that it works running the app on real iOS device but doesn't work creating a build... anyway, Objective-C, here I come ...
thanks @jmagman  for your time on this !

**Comment by gyuri-fluttech** [comment] 2021-12-08 14:32
@jmagman and everyone for the future. It seems that the problem was something else and there was a workaround in the Flutter project while still using Swift for the plugin. The workaround is described here: 
https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/919#issuecomment-988835424
