### ISSUE TITLE
Jobs flaking on Windows due to adb not found?

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#127415] opened 2023-05-23 18:17 UTC
For example:

https://ci.chromium.org/ui/p/flutter/builders/prod/Windows_android%20channels_integration_test_win/8734/overview

Giving:
```
[channels_integration_test_win] Task runner system failed with exception!
ext.cocoonRunTask: (-32000) Server error
Executable "C:\opt\s\w\ir\cache\android\sdk\platform-tools/adb" failed with exit code 137.
#0      fail (package:flutter_devicelab/framework/utils.dart:102:3)
#1      _execute (package:flutter_devicelab/framework/utils.dart:371:5)
<asynchronous suspension>
#2      eval (package:flutter_devicelab/framework/utils.dart:430:3)
<asynchronous suspension>
#3      AndroidDevice.shellExec (package:flutter_devicelab/framework/devices.dart:684:5)
<asynchronous suspension>
#4      AndroidDevice.home (package:flutter_devicelab/framework/devices.dart:611:5)
<asynchronous suspension>
#5      _TaskRunner.run (package:flutter_devicelab/framework/framework.dart:156:7)
<asynchronous suspension>
#6      new _TaskRunner.<anonymous closure> (package:flutter_devicelab/framework/framework.dart:77:33)
<asynchronous suspension>

#0      new _OutstandingRequest (package:vm_service/src/vm_service.dart:1910:45)
#1      VmService._call (package:vm_service/src/vm_service.dart:2471:21)
#2      VmService.callServiceExtension (package:vm_service/src/vm_service.dart:2442:14)
#3      runTask (package:flutter_devicelab/framework/runner.dart:231:73)
<asynchronous suspension>
#4      rerunTask (package:flutter_devicelab/framework/runner.dart:113:29)
<asynchronous suspension>
#5      runTasks (package:flutter_devicelab/framework/runner.dart:51:16)
<asynchronous suspension>
#6      TestCommand.run (package:flutter_devicelab/command/test.dart:72:5)
<asynchronous suspension>
#7      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
```

Several other examples from last night and this morning.
https://ci.chromium.org/ui/p/flutter/builders/prod/Windows_android%20channels_integration_test_win/8731/overview
https://ci.chromium.org/ui/p/flutter/builders/prod/Windows_android%20basic_material_app_win__compile/10263/overview
https://ci.chromium.org/ui/p/flutter/builders/prod/Windows_android%20flavors_test_win/5705/overview
https://ci.chromium.org/ui/p/flutter/builders/prod/Windows_android%20windows_chrome_dev_mode/10290/overview
https://ci.chromium.org/ui/p/flutter/builders/prod/Windows_android%20channels_integration_test_win/8737/overview

**Comment by zanderso** [comment] 2023-05-23 18:18
cc @yusuf-goog infra gardener.

**Comment by yusuf-goog** [comment] 2023-05-23 20:21
adb exists and is callable:

`adb devices
List of devices attached
ZY22465W9K      device`

**Comment by yusuf-goog** [comment] 2023-05-23 20:27
Also, according to the logs, there were adb commands that did seem to run successfully:

```
 [2023-05-23 09:48:26.410160] [STDOUT] Executing "C:\opt\s\w\ir\cache\android\sdk\platform-tools/adb devices -l" in "C:\opt\s\w\ir\x\w\recipe_cleanup\tmp8haaaew6\flutter sdk\dev\devicelab" with environment {BOT: true, LANG: en_US.UTF-8}
 [2023-05-23 09:48:26.457024] [STDOUT] stdout: List of devices attached
 [2023-05-23 09:48:26.457024] [STDOUT] stdout: ZY22465W9K             device product:athene model:Moto_G__4_ device:athene transport_id:1
 [2023-05-23 09:48:26.457024] [STDOUT] stdout: 
 [2023-05-23 09:48:26.457024] [STDOUT] Executing "C:\opt\s\w\ir\cache\android\sdk\platform-tools/adb -s ZY22465W9K shell getprop ro.bootimage.build.fingerprint ; getprop ro.build.version.release ; getprop ro.build.version.sdk" in "C:\opt\s\w\ir\x\w\recipe_cleanup\tmp8haaaew6\flutter sdk\dev\devicelab" with environment {BOT: true, LANG: en_US.UTF-8}
 [2023-05-23 09:48:26.457024] [STDOUT] Device chosen: ZY22465W9K 
 [2023-05-23 09:48:26.457024] [STDOUT] Executing "C:\opt\s\w\ir\cache\android\sdk\platform-tools/adb -s ZY22465W9K shell input keyevent 3" in "C:\opt\s\w\ir\x\w\recipe_cleanup\tmp8haaaew6\flutter sdk\dev\devicelab" with environment {BOT: true, LANG: en_US.UTF-8}
 [2023-05-23 09:48:27.363064] [STDOUT] Checking for reboot
 [channels_integration_test_win] Task runner system failed with exception!
 ext.cocoonRunTask: (-32000) Server error
 Executable "C:\opt\s\w\ir\cache\android\sdk\platform-tools/adb" failed with exit code 137.
 #0      fail (package:flutter_devicelab/framework/utils.dart:102:3)
 #1      _execute (package:flutter_devicelab/framework/utils.dart:371:5)
 <asynchronous suspension>
 #2      eval (package:flutter_devicelab/framework/utils.dart:430:3)
 <asynchronous suspension>
 #3      AndroidDevice.shellExec (package:flutter_devicelab/framework/devices.dart:684:5)
 <asynchronous suspension>
 #4      AndroidDevice.home (package:flutter_devicelab/framework/devices.dart:611:5)
 <asynchronous suspension>
 #5      _TaskRunner.run (package:flutter_devicelab/framework/framework.dart:156:7)
 <asynchronous suspension>
 #6      new _TaskRunner.<anonymous closure> (package:flutter_devicelab/framework/framework.dart:77:33)
 <asynchronous suspension>
 #0      new _OutstandingRequest (package:vm_service/src/vm_service.dart:1910:45)
 #1      VmService._call (package:vm_service/src/vm_service.dart:2471:21)
 #2      VmService.callServiceExtension (package:vm_service/src/vm_service.dart:2442:14)
 #3      runTask (package:flutter_devicelab/framework/runner.dart:231:73)
 <asynchronous suspension>
 #4      rerunTask (package:flutter_devicelab/framework/runner.dart:113:29)
 <asynchronous suspension>
 #5      runTasks (package:flutter_devicelab/framework/runner.dart:51:16)
 <asynchronous suspension>
 #6      TestCommand.run (package:flutter_devicelab/command/test.dart:72:5)
 <asynchronous suspension>
 #7      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
 <asynchronous suspension>
 [channels_integration_test_win] Terminating process...
```

**Comment by keyonghan** [comment] 2023-05-25 00:01
The issue happened on only win2 bots, and it consistently failed tasks from 05/22 8:35pm to 05/23 11:01am. Now it resumed and is passing tests. Sounds a bot issue, and somehow has recovered. Now `powershell Get-MpThreatDetection` returns no threat. /cc @godofredoc 

![Screenshot 2023-05-24 at 4 58 36 PM](https://github.com/flutter/flutter/assets/54558023/e9f9dcd4-63fb-4199-ad22-af0d1da3d15d)

**Comment by godofredoc** [comment] 2023-05-25 17:11
Builds are not using the system's adb. It is using it from android sdk runtime dependency.

If it was windows defender it won't be persistent it will fail for a few hours and then disappear. It is also surprising that this is happening in win-2 where we have had issues with windows defender in the past.

**Comment by keyonghan** [comment] 2023-05-30 17:05
All bots are running okay now. Lowering the priority to P3 to track the root cause.

**Comment by keyonghan** [comment] 2023-11-09 19:18
Seems the test has been passing consistently and the bot has been recovered. Closing as obsolete.

**Closed by keyonghan** 2023-11-09 19:18 UTC
Labels: team-infra, P1
