### ISSUE TITLE
background color is not consistent in Web and other Platforms

### ISSUE THREAD

**Issue by deczaloth** [flutter/flutter#118612] opened 2023-01-17 11:40 UTC
## Steps to Reproduce

1. Execute `flutter run` on the code sample 

**Expected results:** To see same screen color in each platform.

**Actual results:** Windows (Desktop), Android and iOS show black screen, but (at least) Chrome and Edge show white screen.

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(Container());
}
```

</details>

<details>
  <summary>Logs</summary>

```
[√] Flutter (Channel stable, 3.3.10, on Microsoft Windows [Version 10.0.19045.2486], locale de-DE)
    • Flutter version 3.3.10 on channel stable at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (5 weeks ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at C:\Users\Julian\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Professional 2022 17.4.2)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Professional
[√] Connected device (4 available)
    • SM X200 (mobile)  • R9YT60RH43P • android-arm64  • Android 13 (API 33)
    • Windows (desktop) • windows     • windows-x64    • Microsoft Windows [Version 10.0.19045.2486]
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 109.0.5414.74
    • Edge (web)        • edge        • web-javascript • Microsoft Edge 109.0.1518.55

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by darshankawar** [comment] 2023-01-18 09:21
Closing as duplicate of https://github.com/flutter/flutter/issues/107596. Please follow-up in it for further updates.

**Closed by darshankawar** 2023-01-18 09:21 UTC
Labels: in triage
