### ISSUE TITLE
Should mention iOS janks problem on Flutter.dev page

### ISSUE THREAD

**Issue by alectogeek** [flutter/flutter#70571] opened 2020-11-15 17:00 UTC
IMHO there should be written that Flutter has huge, awful performance problems on iOS related to the shaders compilation problem. We in our company spent lots of time developing our app and came to the problem that it is not usable in production. The issues related to this problem are opened since May and there is still no solution. We thought that it will be solved in a short period of time, but it is not. If you guys can work on any other features/issues while you have such an obvious problem with performance, you should at least notify developers about the problem.

I am very disappointed as well as many other developers, sorry.

**Comment by alectogeek** [comment] 2020-11-15 17:04
Yes, I tried using a no-metal engine, but users still complain that the app is junky (and crashes sometimes because of OOM). It works well on simulators in debug mode, but janky in release mode. I tried also to rollback to v1.12.13 version, but it is barely possible in actively developing applications.

**Comment by iapicca** [comment] 2020-11-15 17:25
@alectogeek 
do you believe that the issue you are experiencing correspond to one of the issue below?
https://github.com/flutter/flutter/issues/32170
https://github.com/flutter/flutter/issues/35923
https://github.com/flutter/flutter/issues/68649

If so, it would be best to add the relevant information to the existing issue,
otherwise could you please provide more details about the issue you are experiencing
as you `flutter doctor -v` and the crash logs occurred in production

Lastly you mentioned that the issue occurs in `release` mode, but not in `debug`,
is it possible to provide a minimal reproducible code sample?

**Comment by alectogeek** [comment] 2020-11-15 17:35
@iapicca Yes, it is the same issue. 
I mentioned that it works well on simulators :) Probably because there is a virtualization layer or smth like this, but the app in the simulator is not junky (but works slowly as usual on simulators).

The main idea of my issue is to make newly coming developers aware of the problem and write about it on the flutter main web page.

**Comment by iapicca** [comment] 2020-11-15 18:02
I believe that this is not an intrinsic limitation of the framework,
but just an issue that will be solved.

I don't recall any framework "advertising" open issues on their main page
why should flutter do that? 
and why this specific issue?

**Comment by nt4f04uNd** [comment] 2020-11-15 20:29
There is already a point in official documentation https://flutter.dev/docs/perf/rendering/shader

Can be closed I guess

**Comment by TahaTesser** [comment] 2020-11-20 13:56
This issue doesn't seem to add any tangible, as @iapicca, there are a bunch of issues trying to address legit issues
Closing, If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2020-11-20 13:56 UTC

**Comment by theniceboy** [comment] 2020-11-20 14:10
I don't think we should just close it like this. The information on the homepage regarding flutter's native performance is very misleading. ￼￼￼Many people will find (and have found) themselves in a awkward position after investing bunch of their time￼. At least we should be honest. I don't think it's enough to say it somewhere hidden in the docs.

**Comment by nt4f04uNd** [comment] 2020-11-20 14:20
@theniceboy this doesn't ruin any of your time investements as it's the issue being worked on. If you find this a big problem for your application, you can try switching back over to OpenGL, check out https://github.com/flutter/flutter/issues/61045

**Comment by alectogeek** [comment] 2020-11-20 14:24
@nt4f04uNd The issue is being worked on since Spring. The warm-up problem is being worked on since last year. It is a big problem. Switching back to OpenGL courses OOM crashes, degradation of UI elements, and slowing interface during post first run usage. It was not usable for our case.

**Comment by theniceboy** [comment] 2020-11-20 14:28
@nt4f04uNd apparently image_picker won't doesn't work with OpenGL... I went there and had to come back. I know that this wouldn't make flutter look good, but it's bad to have such a big difference between advertised and reality. This issue has been present for over 6 months now. Idk which's the best solution but keeping quite is definitely not it.

**Comment by nt4f04uNd** [comment] 2020-11-20 14:31
@theniceboy fair neough, I wasn't aware of the `image_picker` problem

@alectogeek have you tried using https://github.com/acoutts/flutter-engines-no-metal , maybe the lates one will help in your case?

**Comment by alectogeek** [comment] 2020-11-20 14:32
@nt4f04uNd also usage of `flutter_svg`  is not possible with OpenGL (pictures are damaged). 
Yes, I tried to use no-metal build in production and got many negative reviews from users.

**Comment by nt4f04uNd** [comment] 2020-11-20 14:57
@TahaTesser I think the issue should be reopened. You said it's not "tangible". I can clearly say it's more than clear that @alectogeek suggests that the https://flutter.dev/ main page clearly alerted developers about this issue and the progress on it's resolution. I would also suggest adding this to some started doc pages.

**Comment by iapicca** [comment] 2020-11-20 15:49
@alectogeek @nt4f04uNd @theniceboy 
for an issue to be workable have to be reproducible
please provide 
your flutter doctor -v
and most importantly a minimal reproducible code sample (without 3rd party packages or plugins)

To disambiguate this issue from the possible, if not likely, duplicates listed [above](https://github.com/flutter/flutter/issues/70571#issuecomment-727605652)
please specify a use case not yet addressed

**Comment by nt4f04uNd** [comment] 2020-11-20 17:52
@iapicca correct me if I'm wrong, but this issue is not related to the Flutter SDK by no means, so what's the reason to provide the `flutter doctor -v`?

The main point of this issue is to make the framework huge currently unsolvable flaw to be completely clear for anyone who decides if he want to use flutter in their business, or not. Someone who didn't know about this problem may invest a couple of months on a project that will end up having that huge janks, so everyone should be clearly alerted about this thing.

> * github issues are public and a users can retrieve the specific information about the state of any issue.
>   why should this be reiterated on the website?

Becuase it's huge and unobvious, it's hard to know about it, until you actually face it.

> * if every open issue would have been `mentioned` on the website this will be incredibly crowded
>   are you suggesting that this issue in particular "deserve" to somewhat receive a spotlight? If so why?

This is an extra case. Explanation above.

> * I don't recall the suggested behavior adopted by other frameworks,
>   can you please provide a precedent, or the reasons, for your expectation?

Unfortunately I can't remember a signle precedent of such a big and unobvious issue and do you need one to actually alert people about this one?

**Comment by iapicca** [comment] 2020-11-20 18:52
@nt4f04uNd 

nobody argues about the severity of the issue
as a matter of fact flutter team itself has given to the issue a fairly high priority,
but not the highest

your statement's seem **entirely opinion based**
corroborating @TahaTesser 's point

> This issue doesn't seem to add anything tangible, as @iapicca mentioned, there are a bunch of issues trying to address legit issues
> Closing, If you disagree, please write in the comments and I will reopen it.
> Thank you

**Comment by theniceboy** [comment] 2020-11-21 00:13
@iapicca I don't think we should highlight this is issue on flutter's main page, that looks kind of weird, but I think at least we should correct the places where it false advertises for native performance or 60 fps.￼￼

**Comment by alectogeek** [comment] 2020-11-27 18:49
https://github.com/flutter/flutter/issues/32170#issuecomment-734942888
https://github.com/flutter/flutter/issues/32170#issuecomment-734945638
