### ISSUE TITLE
App fails to start on iPhone 12

### ISSUE THREAD

**Issue by duzenko** [flutter/flutter#93906] opened 2021-11-19 07:29 UTC
I recently discovered that I can't run our app on iPhone 12 Pro unless I run it from under xcode
I.e. both vscode and command line flutter run only get as far as splash screen, then timeout with error
Here's a typical output
![image](https://user-images.githubusercontent.com/1481807/142582395-c7e9f7e9-0a03-443d-8f3b-fee7bfc4501f.png)
![image](https://user-images.githubusercontent.com/1481807/142582548-99f12f95-87c4-4c86-b072-7ae1224ddf65.png)

When running from under xcode, it "just works" but I can't debug dart code or collect skia shader cache

Flutter doctor
![image](https://user-images.githubusercontent.com/1481807/142582648-d2bf2f8d-9158-46e4-88c3-385719d54274.png)

iOS version 14.8.1
xcode 13.0

**Comment by kasisnu** [comment] 2021-11-19 07:55
Hi @duzenko! Could you please share some more information?
* You mentioned that the issue started recently - Could you recall the last version that this was working as expected for you?
* Is this with an external device only? Does it work with iOS simulator for another device?
* Since the app seems to start but isn't able to get past the splash screen through the integration, would it be possible to share a minimal failing example?

Thank you

**Comment by duzenko** [comment] 2021-11-19 09:24
Well, the app is being developed extensively, and flutter upgrades often enough as well, so digging through history would not be so helpful considering flutter support policy for older versions
I don't want to spend too much time on this as flutter builds on iOS are slow enough to prevent me from trying in different configurations. However it seemed to work on a 6s running 14.8 last time I tried it
What would a minimal example achieve if it's just a hello world?

**Comment by kasisnu** [comment] 2021-11-19 11:41
Hi, I made an assumption that it might be something specific to the code in your project.

I created new app with `flutter create` on `v2.5.3` and didn't get stuck deploying to iOS on iPhone 12(sim).

Thanks

**Comment by danagbemava-nc** [comment] 2021-11-19 13:05
Hi @duzenko, this issue is known and is being tracked here https://github.com/flutter/flutter/issues/72161. 

Kindly follow up there for more information. 

Any more information you can provide over there might bring the team closer to finding a fix. 

The issue in question is quite flaky (i.e, doesn't have concrete reproducible steps and varies largely based on setup), which is why it hasn't been fixed there. 

Closing as duplicate of https://github.com/flutter/flutter/issues/72161. 

Thank you

**Closed by danagbemava-nc** 2021-11-19 13:05 UTC
Labels: in triage

**Comment by duzenko** [comment] 2021-11-19 14:26
I don't think so
Even hello world gives this error
![image](https://user-images.githubusercontent.com/1481807/142638607-4b9db447-eeba-47e0-a3ca-6080bd9a9505.png)

**Comment by duzenko** [comment] 2021-11-19 15:13
Updated to iOS 15.1, slightly different logs
![image](https://user-images.githubusercontent.com/1481807/142645830-d1633de5-1520-4042-8593-88848b9c3694.png)

**Comment by duzenko** [comment] 2021-11-19 15:17
> Hi, I made an assumption that it might be something specific to the code in your project.
> 
> I created new app with `flutter create` on `v2.5.3` and didn't get stuck deploying to iOS on iPhone 12(sim).
> 
> Thanks

oh, wow
Did you know that iPhone 12(sim) is not really an iPhone?
