### ISSUE TITLE
Flutter is broken wreck full of misbehaving widgets and HACKs, move to other platforms

### ISSUE THREAD

**Issue by jomamaigma** [flutter/flutter#143998] opened 2024-02-23 04:43 UTC
### Steps to reproduce

Steps to reproduce
1. uninstall flutter

when a simple feature as an autocomplete does not work (infinite width issue, and keyboard arrow and selection) and the bug is opened 3 years ago and still not fixed, it is time to move to another platform. this will be my last project with this dumpster fire, I said that being google and doing the rendering as it is explained, and all it might be a nice solution for multi-platform development, boy was I wrong !!

non working widgets, a lot of issues debugging strange behaviours and so on
app was rejected by apple for rendering a black screen and not doing anything on a M2, teste on an M1, intel, VM working ok on my side, this platform is a JOKE !!!
Stepper has strange highlight that overflows downwards and using a tab inside it overflows to the sides
AND MANY MANY OTHER ISSUES
it is 80% debugging strange behaviour and applying HACKS 20% coding, reminds me when I had to do css hacks back in the day of IE6,7..etc

### Expected results

working widgets and system

### Actual results

non working widgets and system

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by danagbemava-nc** [comment] 2024-02-23 08:07
If you have any issues to report, kindly file detailed issues with steps to reproduce so that they can be properly investigated. If you believe an issue needs to be re-prioritized, kindly share you thoughts on that issue with constructive feedback and upvote the issue as well. 

Filing an issue like this with no constructive/helpful feedback does not help anybody. 

I'll be closing this since this issue is not actionable. 

Thank you

**Closed by danagbemava-nc** 2024-02-23 08:07 UTC
Labels: in triage
