### ISSUE TITLE
[Impeller] Performance overlay is broken.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#126009] opened 2023-05-03 20:36 UTC
The overlay uses direct Skia calls instead of going through the display list interface. This makes the graphs not show up (though the text is visible).

The overlay must be retooled to use display list APIs instead of Skia ones.

**Comment by chinmaygarde** [comment] 2023-05-03 20:37
xref b/279222257

**Comment by chinmaygarde** [comment] 2023-05-15 19:09
I realize the team doesn't use the overlay for analyzing performance since there are better tools out there. But from the user perspective, the overlay is easy to setup to get a high level overview of the relative performance of Impeller and the legacy backend. The graphs not showing up is a rough and a poor first experience. Elevating priority for this reason.

**Comment by cbracken** [comment] 2023-06-13 22:02
Hit this today on macOS :) Agreed with @chinmaygarde that while this isn't the end of the world, it's a really nice quick-and-dirty check to see whether you're dropping frames, so would be great to support.

**Comment by lukepighetti** [comment] 2023-07-31 17:57
Having this not work feels weird since we've been able to rely on it for years. Would be nice to have an indication that this is known to not work.

**Comment by matanlurey** [comment] 2023-08-28 19:30
This sounds interesting, I'd like to work on this issue!

**Comment by matanlurey** [comment] 2023-08-28 20:38
Some notes for myself:

- [Flutter performance profiling](https://docs.flutter.dev/perf/ui-performance) is the user-facing documentation.
- It can be enabled in devtools, and I think with `P` in debug or profile mode (though profile mode is recommended).
- The code appears to be in [`performance_overlay_layer.cc`](https://github.com/flutter/engine/blob/0d5b780b16ebff2b520e90c1107ba7503a9833b4/flow/layers/performance_overlay_layer.cc) and friends. For me to figure out: it's already using `DlCanvas*`, what else needs to change to make it backend agnostic?

Here is an example with the Skia backend:

<img width="788" alt="Screenshot 2023-08-28 at 1 34 11 PM" src="https://github.com/flutter/flutter/assets/168174/f65ffa76-e4d2-455f-80bf-0c5f7330fea6">

And with Impeller enabled:

<img width="798" alt="Screenshot 2023-08-28 at 1 36 28 PM" src="https://github.com/flutter/flutter/assets/168174/482c652a-79f3-4ff4-a008-dcc30be4fde2">

**Comment by matanlurey** [comment] 2023-08-28 20:59
Ah the problem is actually not _specific_ to the performance overlay, it's the [more generic `Stopwatch` implementation](https://github.com/flutter/engine/blob/1738c1fa2642578717bbaf11faffa7f20dbdca5d/flow/instrumentation.cc):

```cc
void Stopwatch::Visualize(DlCanvas* canvas, const SkRect& rect) const {
  // Initialize visualize cache if it has not yet been initialized.
  InitVisualizeSurface(SkISize::Make(rect.width(), rect.height()));

  SkCanvas* cache_canvas = visualize_cache_surface_->getCanvas();
  SkPaint paint;

  ...
}
```

This will need to be updated.

**Comment by matanlurey** [comment] 2023-08-28 21:16
Unfortunately https://github.com/flutter/engine/pull/6225/files makes this hard[er], because a bunch of "performance" fixes were landed in such a way that has lots of knowledge of Sk-internals. For now I'm going to focus on just getting the overlay graph working at all.

**Comment by chinmaygarde** [comment] 2023-08-28 22:34
Yeah, that patch saves to a texture and such. We can back that out.

**Comment by matanlurey** [comment] 2023-08-28 22:41
Talked to @jonahwilliams offline - we'd probably want to keep the Skia-"optimized" and Dl/generic code living side by side until Impeller is shipping everywhere by default. I did end up getting the overlay working in Impeller:

![image](https://github.com/flutter/flutter/assets/168174/c11e5192-92f4-42ee-8471-22aa2e215594)

... so now I'm going to work on a bit of refactoring to make it possible to have two `Stopwatch` implementations, and select the newer one when Impeller is enabled.

**Comment by matanlurey** [comment] 2023-08-28 22:50
Draft branch, which I won't be PRing:
https://github.com/flutter/engine/compare/main...matanlurey:engine:impeller-performance-overlay-dl?expand=1

**Closed** 2023-08-30 23:15 UTC
Labels: engine, P2, e: impeller, team-engine, triaged-engine
