### ISSUE TITLE
iOS Google Maps: strange bug after reopening an app

### ISSUE THREAD

**Issue by IhorKlimov** [flutter/flutter#25653] opened 2018-12-21 11:58 UTC
I face a weird bug on iOS real devices, both in debug and release builds. Using an example project from Flutter Google maps plugin. The issue occurs after the app is reopened, without terminating it. 

video: https://www.youtube.com/watch?v=eO53HcvgtZo&feature=youtu.be

There're two cases I saw so far:

1. When you push a new route - you have a black background in the animation
2. When you show a dialog - it's not shown at all and Google map gets blocked (no gestures working). The only way to come out of this state is to double tap on a map. After double tapping, the issue is still there, however: dialog not shown, black background during animation

The strange thing is that I don't have any bug logs, both when running from Android Studio and from XCode

My modification to the example project is very simple, I added these two buttons in a list:

```dart
              FlatButton(
                child: Text('Open second page'),
                onPressed: () {
                  Navigator.of(context)
                      .push(MaterialPageRoute(builder: (b) => SecondPage()));
                },
              ),
              FlatButton(
                child: Text('Show dialog'),
                onPressed: () {
                  showDialog(
                      context: context,
                      builder: (c) => SimpleDialog(title: Text("Title")));
                },
              ),
```

Running on iOS 12.1.2, no issues on Android devices

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v1.1.4, on Mac OS X 10.14.1 18B75, locale en-UA)
[✓] Android toolchain - develop for Android devices (Android SDK version 27.0.3)
[!] iOS toolchain - develop for iOS devices (Xcode 10.1)
    ✗ Verify that all connected devices have been paired with this computer in
      Xcode.
      If all devices have been paired, libimobiledevice and ideviceinstaller may
      require updating.
      To update with Brew, run:
        brew update
        brew uninstall --ignore-dependencies libimobiledevice
        brew uninstall --ignore-dependencies usbmuxd
        brew install --HEAD usbmuxd
        brew unlink usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
[✓] Android Studio (version 3.2)
[!] IntelliJ IDEA Ultimate Edition (version 2018.2.5)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] Connected device (1 available)

! Doctor found issues in 2 categories.
```

**Comment by zoechi** [comment] 2018-12-21 12:53
Might be #24900

**Comment by amirh** [comment] 2018-12-28 00:00
Duplicate of #24900

**Closed by amirh** 2018-12-28 00:00 UTC
Labels: a: platform-views, engine, p: first party, p: maps, plugin
