### ISSUE TITLE
[impeller] Android app broken with 3.25.0-0.1.pre

### ISSUE THREAD

**Issue by jimmyff** [flutter/flutter#154778] opened 2024-09-07 14:07 UTC
After updating to  3.25.0-0.1.pre my app is unusable on android, it's all sorts of broken with visual artefacts everywhere. 

What's strange is when i do a screen recording the issues aren't present.

Video (filmed on another device):
https://photos.app.goo.gl/CCuQ4WGkbdDZaMwL9

I get these spammed to terminal:
```
E/flutter ( 9884): [ERROR:flutter/impeller/renderer/backend/vulkan/command_queue_vk.cc(68)] Break on 'ImpellerValidationBreak' to inspect point of failure: Failed to submit queue: ErrorDeviceLost
W/Adreno-GSL( 9884): <gsl_ldd_control:553>: ioctl fd 110 code 0xc040094a (IOCTL_KGSL_GPU_COMMAND) failed: errno 35 Resource deadlock would occur
W/Adreno-GSL( 9884): <log_gpu_snapshot:462>: panel.gpuSnapshotPath is not set.not generating user snapshot
```
Also saw this one:
```
════════ Exception caught by image resource service ════════════════════════════
Exception: Failed to submit blit pass command buffer.
```

The issue seems to be on screens that I interact with SVG widgets (using jovial_svg package). Example showing app working until I interact with a vector graphics widget:
https://photos.app.goo.gl/aL3FkF6a6Rjwk4DU9

Lots of errors like this:
```
W/Adreno-GSL(13637): <gsl_ldd_control:553>: ioctl fd 110 code 0xc040094a (IOCTL_KGSL_GPU_COMMAND) failed: errno 35 Resource deadlock would occur
W/Adreno-GSL(13637): <log_gpu_snapshot:462>: panel.gpuSnapshotPath is not set.not generating user snapshot
E/flutter (13637): [ERROR:flutter/impeller/renderer/backend/vulkan/swapchain/ahb/ahb_swapchain_impl_vk.cc(169)] Break on 'ImpellerValidationBreak' to inspect point of failure: Could not submit completion signal.
```

I've downgraded to `3.24.0-0.2.pre` via fvm and the issues go away:

https://photos.app.goo.gl/rSUYnrXgWwkh6S379

**Comment by jonahwilliams** [comment] 2024-09-07 14:32
We need device information to diagnose the problem. Could be device specific driver issue

**Comment by jimmyff** [comment] 2024-09-07 16:39
```
  Pixel 5 (mobile)        • android-arm64  • Android 14 (API 34)
```

- Kernel: 4.19.278-g7b....
- Build number: IP1A.231105.001.B2

I can test on more devices if need?

**Comment by jonahwilliams** [comment] 2024-09-07 16:40
Thanks! Does this repro on any of our sample apps/counter app, or only on your example app?

**Comment by jonahwilliams** [comment] 2024-09-07 16:41
Also can you please provide the entire `flutter doctor -v` so I can see your commit hash. 3.25.0-0.1.pre isn't a real version and its pretty hard to look up the commit.

**Comment by jimmyff** [comment] 2024-09-09 08:42
I can see similar issues on example app using pixel 5 when I add an SVG in. Video:
https://photos.app.goo.gl/nU5QPdhWTaKqhwbH9

If the widget is fully contained the issue doesn't seem to be there (In my quick look I can't reproduce this issue on my pixel 8 pro with this example):

<details>
<summary>main.dart</summary>

```dart
import 'package:flutter/material.dart';
import 'package:jovial_svg/jovial_svg.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          backgroundColor: Theme.of(context).colorScheme.inversePrimary,
          title: Text(widget.title),
        ),
        body: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              InkWell(
                  onTap: () {},
                  child: Container(
                      height: 400,
                      width: 400,
                      child: ScalableImageWidget(
                          si: ScalableImage.fromSvgString(
                              '<svg clip-rule="evenodd" fill-rule="evenodd" height="65.249" stroke-linejoin="round" stroke-miterlimit="2" viewBox="0 0 63.138 65.249" width="63.138" xmlns="http://www.w3.org/2000/svg"><g fill-rule="nonzero"><path d="m0 .927c.002-.154.003-.309.003-.464 0-.147-.001-.294-.003-.441-.139-19.096-9.352-29.443-30.432-29.594-.155-.002-.312-.003-.468-.003s-.312.001-.468.003c-21.08.151-30.292 10.498-30.432 29.594-.002.147-.003.294-.003.441 0 .155.001.31.004.464.157 19.073 10.055 29.411 30.419 29.571.16.002.32.004.48.004.161 0 .32-.002.481-.004 20.363-.16 30.261-10.498 30.419-29.571" fill="#ffe577" transform="translate(62.469 34.082)"/><g fill="#3b3b3b"><path d="m0-58.744c-.153 0-.306.001-.459.003-5.141.037-9.657.699-13.425 1.968-3.68 1.239-6.769 3.099-9.18 5.529-2.368 2.385-4.169 5.407-5.354 8.982-1.17 3.53-1.781 7.72-1.816 12.455-.002.147-.003.292-.003.436 0 .151.002.302.004.454.077 9.404 2.579 16.607 7.435 21.414 4.949 4.899 12.46 7.423 22.323 7.5.322.005.632.005.946 0 9.867-.077 17.378-2.601 22.328-7.5 4.855-4.807 7.357-12.01 7.434-21.41l.001-.004c.002-.152.003-.303.003-.454 0-.144-.001-.288-.003-.432-.034-4.739-.646-8.929-1.816-12.459-1.185-3.575-2.986-6.597-5.354-8.982-2.411-2.43-5.5-4.29-9.18-5.529-3.768-1.269-8.283-1.931-13.421-1.968-.156-.002-.31-.003-.463-.003m0 60.077c-.164 0-.327-.001-.49-.004-10.218-.08-18.041-2.733-23.245-7.885-5.115-5.063-7.749-12.582-7.83-22.346-.003-.154-.004-.311-.004-.469 0-.151.001-.301.003-.451.036-4.869.67-9.197 1.883-12.859 1.251-3.772 3.16-6.969 5.674-9.502 2.558-2.578 5.822-4.546 9.7-5.853 3.903-1.313 8.558-1.999 13.836-2.037.309-.004.633-.004.95 0 5.274.038 9.93.724 13.832 2.037 3.878 1.307 7.142 3.275 9.701 5.853 2.513 2.533 4.422 5.73 5.673 9.502 1.214 3.662 1.848 7.99 1.883 12.864.002.145.003.295.003.446 0 .157-.001.314-.003.472-.082 9.762-2.716 17.28-7.83 22.343-5.205 5.152-13.028 7.805-23.25 7.885-.159.003-.322.004-.486.004" transform="translate(31.569 63.916)"/><g transform="translate(52.309 57.217)"><path d="m0-22.123c-4.961-.465-12.216-.758-20.298-.758-8.288 0-15.706.308-20.673.794-1.074.105-1.844.893-2.05 1.824.033.48.081.955.143 1.427.05.111.05.111 0 0 1.468 11.06 10.935 19.594 22.397 19.594 11.479 0 20.959-8.561 22.403-19.647-.051.117-.051.117 0 0 .06-.463.106-.931.138-1.402-.205-.937-.98-1.73-2.06-1.832"/><path d="m0-22.123c-4.961-.465-12.216-.758-20.298-.758-8.288 0-15.706.308-20.673.794-1.074.105-1.844.893-2.05 1.824.033.48.081.955.143 1.427.05.111.05.111 0 0 1.468 11.06 10.935 19.594 22.397 19.594 11.479 0 20.959-8.561 22.403-19.647-.051.117-.051.117 0 0 .06-.463.106-.931.138-1.402-.205-.937-.98-1.73-2.06-1.832"/></g><path d="m0 5.724c-.238.045-.493-.023-.678-.205-1.612-1.586-3.283-2.605-4.965-3.027-1.53-.385-3.094-.304-4.779.246-.401.131-.83-.088-.961-.489-.13-.4.088-.83.488-.96 4.087-1.334 7.78-.305 11.286 3.143.3.295.304.778.008 1.078-.112.115-.253.186-.399.214" transform="translate(52.543 -.72543)"/><path d="m0 5.724c.237.045.492-.023.678-.205 1.612-1.586 3.282-2.605 4.965-3.027 1.53-.385 3.094-.304 4.779.246.4.131.83-.088.961-.489.13-.4-.089-.83-.488-.96-4.087-1.334-7.78-.305-11.286 3.143-.3.295-.304.778-.009 1.078.113.115.253.186.4.214" transform="translate(10.378 -.72543)"/></g><path d="m4.653-3.294c1.898 3.687 3.343 6.626 4.28 8.708l-4.28 1.877c-1.346-3.096-2.608-6.126-3.728-8.95z" fill="#fff" transform="matrix(.40152 .91585 .91585 -.40152 22.522 33.752)"/><path d="m-4.923-7.477c1.38 2.722 2.814 5.676 4.236 8.721l-4.236 1.968c-1.083-2.405-2.414-5.642-3.734-8.955z" fill="#fff" transform="matrix(-.42128 -.90693 -.90693 .42128 33.406 33.938)"/><path d="m0-3.917c-3.202.134-6.087.32-8.464.553-.744.072-1.213.612-1.368 1.145.032.424.076.847.13 1.261l-.419.056.419-.056c.011.081.023.164.035.249 3.571.285 6.804.521 9.667.709z" fill="#fff" transform="translate(19.876 39.24)"/><path d="m0-2.912c-2.396-.225-5.288-.404-8.479-.532v3.976c3.53-.208 7.012-.447 9.67-.639.021-.138.04-.277.059-.414.052-.401.094-.818.125-1.24-.154-.537-.625-1.081-1.375-1.151" fill="#fff" transform="translate(52.239 38.752)"/><path d="m.079-.001c4.067.067 7.866 1.207 11.132 3.143-1.89 3.806-6.183 6.425-11.132 6.343-5.011-.083-9.257-2.91-10.981-6.849 3.27-1.742 7.014-2.703 10.981-2.637" fill="#e15e5e" transform="matrix(.99986 .01655 .01655 -.99986 31.749 57.972)"/><path d="m0-15.196c.743 5.12 3.291 9.823 7.194 13.269 4.005 3.536 9.157 5.482 14.505 5.482 5.358 0 10.516-1.952 14.524-5.499 3.905-3.455 6.449-8.169 7.182-13.298-.004-.032.04-.268.049-.362.048-.38.087-.771.115-1.166-.158-.571-.654-1.152-1.451-1.226-5.121-.48-12.496-.756-20.236-.756-7.956 0-15.468.289-20.608.791-.79.078-1.284.655-1.442 1.22.029.397.069.795.119 1.186.037.087.055.176.055.265 0 .032-.002.063-.006.094m21.699 20.084c-5.674 0-11.138-2.066-15.387-5.816-4.21-3.718-6.935-8.816-7.669-14.357v-.001c-.064-.482-.114-.976-.148-1.467-.004-.064.001-.128.014-.19.282-1.275 1.341-2.217 2.636-2.343 5.181-.507 12.739-.798 20.737-.798 7.779 0 15.2.278 20.361.762 1.304.122 2.368 1.067 2.648 2.353.013.061.018.124.014.186-.033.489-.081.975-.142 1.443-.723 5.554-3.443 10.665-7.658 14.394-4.251 3.762-9.723 5.834-15.406 5.834" fill="#3b3b3b" transform="translate(10.129 53.753)"/><path d="m0-13.481c-2.583 0-4.678 2.095-4.678 4.678v8.803h9.356v-8.803c0-2.583-2.095-4.678-4.678-4.678" fill="#fff" transform="translate(18.442 27.185)"/><path d="m0-13.48c-2.583 0-4.678 2.094-4.678 4.678v8.802h9.356v-8.802c0-2.584-2.095-4.678-4.678-4.678" fill="#fff" transform="translate(45.476 27.166)"/><path d="m0-4.125c0-2.212 1.8-4.012 4.012-4.012v4.385c0 .11.055.214.148.275l1.719 1.134c.199.131.199.423 0 .554l-1.719 1.134c-.093.061-.148.164-.148.275v4.392h-4.012zm10.239 8.137h-.883v-8.137c0-2.947-2.398-5.344-5.344-5.344-2.947 0-5.344 2.397-5.344 5.344v8.137h-.783c-.367 0-.666.298-.666.666s.299.666.666.666h12.354c.368 0 .666-.298.666-.666s-.298-.666-.666-.666" fill="#3b3b3b" transform="translate(14.43 22.507)"/><path d="m0-4.143c0-2.212 1.799-4.012 4.012-4.012v4.369c0 .11.055.214.148.275l1.771 1.168c.198.132.198.423 0 .554l-1.771 1.169c-.093.061-.148.164-.148.275v4.339h-4.012zm10.188 8.155h-.833v-8.155c0-2.947-2.397-5.344-5.343-5.344-2.947 0-5.345 2.397-5.345 5.344v8.155h-.833c-.367 0-.666.299-.666.666 0 .368.299.666.666.666h12.354c.369 0 .666-.298.666-.666 0-.367-.297-.666-.666-.666" fill="#3b3b3b" transform="translate(41.464 22.507)"/><path d="m0 10.844h-2.495c-.055 0-.111-.007-.165-.021l-.116-.03c-1.682-.283-2.891-1.731-2.879-3.453.005-.68.277-2.93 3.573-3.365.29-.038.508-.288.508-.581v-2.728c0-.368.298-.666.666-.666.367 0 .666.298.666.666v2.728c0 .959-.716 1.776-1.665 1.902-1.55.204-2.408.933-2.416 2.053-.008 1.07.745 1.968 1.789 2.134.02.003.041.007.061.013l.062.016h2.411c.368 0 .666.298.666.666s-.298.666-.666.666" fill="#3b3b3b" transform="translate(34.064 19.009)"/></g></svg>')))),
              const Text(
                'You have pushed the button this many times:',
              ),
              Text(
                '$_counter',
                style: Theme.of(context).textTheme.headlineMedium,
              ),
            ],
          ),
        ),
        floatingActionButton: FloatingActionButton(
          onPressed: _incrementCounter,
          tooltip: 'Increment',
          child: const Icon(Icons.add),
        ));
  }
}

```
</details>

I've just tried my actual app using flutter 3.25 on pixel 8 pro and I don't get as many immediate visual glitches issues (maybe due to initial widget being fully contained on the larger screen), but interacting with the vector graphics on an `InteractiveViewer` widget causes a hard crash or major visual glitch & hang:
https://photos.app.goo.gl/TQnEMFYEKXqnSimy5

Something definitely not quite right with flutter 3.25 on Android.

<details>
<summary>Flutter Doctor</summary>

```
[✓] Flutter (Channel beta, 3.25.0-0.1.pre, on macOS 14.5 23F79 darwin-arm64, locale en-GB)
    • Flutter version 3.25.0-0.1.pre on channel beta at /Users/jimmyff/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d3733fcb0e (3 weeks ago), 2024-08-21 10:27:04 -0500
    • Engine revision 062b3a72fc
    • Dart version 3.6.0 (build 3.6.0-149.3.beta)
    • DevTools version 2.38.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/jimmyff/Library/Android/sdk
    • Platform android-34, build-tools 33.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)

[✓] VS Code (version 1.93.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.96.0

[✓] Connected device (5 available)
    • Pixel 5 (mobile)                • 09021FDD40027X        • android-arm64  • Android 14 (API 34)
    • Pixel 8 Pro (mobile)            • 39141FDJG00EMH        • android-arm64  • Android 15 (API 35)
    • macOS (desktop)                 • macos                 • darwin-arm64   • macOS 14.5 23F79 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         • macOS 14.5 23F79 darwin-arm64
    • Chrome (web)                    • chrome                • web-javascript • Google Chrome 128.0.6613.120

[✓] Network resources
    • All expected network resources are available.

• No issues found!
</details>

**Comment by darshankawar** [comment] 2024-09-10 07:03
We tried on Samsung and Pixel 7 devices running Android 14 but weren't able to replicate the reported behavior. 
Based on the report and behavior occured, keeping the issue open for team's tracking.

**Comment by gaaclarke** [comment] 2024-09-26 16:35
I've seen it too with a Pixel 4a.  It was much more subtle for me though.  I had to wait for the tap animation to finish then tap again and it seems to happen on the first frame of the animation.  The whole screen would glitch (notice the plus button in the bottom right).  It doesn't happen 100% of the time, maybe 33%. I can also verify that it doesn't happen when the screen recorder is engaged.

https://github.com/user-attachments/assets/3a674388-dc04-40cc-872d-ddf146cbb6df

**Comment by gaaclarke** [comment] 2024-09-26 16:47
I've updated to 7ec6083bed and I no longer see the issue.  However the logs I get seem to make it sound I'm falling back to the opengles renderer?  I'm not quite sure if those are just confusing logs or that we've fixed the impeller vulkan issue.

```
I/flutter ( 6000): [IMPORTANT:flutter/shell/platform/android/android_context_vk_impeller.cc(60)] Using the Impeller rendering backend (Vulkan).
Syncing files to device Pixel 4a...                                 54ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

A Dart VM Service on Pixel 4a is available at: http://127.0.0.1:57487/7GztIcIf7n0=/
I/mple.bug_154778( 6000): Compiler allocated 4323KB to compile void android.view.ViewRootImpl.performTraversals()
D/ProfileInstaller( 6000): Installing profile for com.example.bug_154778
The Flutter DevTools debugger and profiler on Pixel 4a is available at: http://127.0.0.1:9103?uri=http://127.0.0.1:57487/7GztIcIf7n0=/
I/AdrenoGLES-0( 6000): QUALCOMM build                   : 85da404, I46ff5fc46f
I/AdrenoGLES-0( 6000): Build Date                       : 11/30/20
I/AdrenoGLES-0( 6000): OpenGL ES Shader Compiler Version: EV031.31.04.01
I/AdrenoGLES-0( 6000): Local Branch                     : promo490_3_Google
I/AdrenoGLES-0( 6000): Remote Branch                    : 
I/AdrenoGLES-0( 6000): Remote Branch                    : 
I/AdrenoGLES-0( 6000): Reconstruct Branch               : 
I/AdrenoGLES-0( 6000): Build Config                     : S P 10.0.4 AArch64
I/AdrenoGLES-0( 6000): Driver Path                      : /vendor/lib64/egl/libGLESv2_adreno.so
I/AdrenoGLES-0( 6000): PFP: 0x016ee190, ME: 0x00000000
W/AdrenoUtils( 6000): <ReadGpuID_from_sysfs:197>: Failed to open /sys/class/kgsl/kgsl-3d0/gpu_model
W/AdrenoUtils( 6000): <ReadGpuID:221>: Failed to read chip ID from gpu_model. Fallback to use the GSL path
E/OpenGLRenderer( 6000): Unable to match the desired swap behavior.
E/OpenGLRenderer( 6000): Unable to match the desired swap behavior.
```

**Comment by gaaclarke** [comment] 2024-09-26 17:00
@jimmyff can you confirm that it works for you on https://github.com/flutter/flutter/commit/7ec6083bed3b266167f930d5930a88b32549c019 ?  Since I was able to reproduce it with the given steps and it no longer reproduces for me on `main` I'm going to close this out.  If it isn't addressed for you we can reopen it.

Since this was reproduced on a beta, do we need to try to bisect this issue to try to cherry pick into the beta branch?  Or will the fix come in eventually when we merge main into beta?

**Closed by gaaclarke** 2024-09-26 17:00 UTC
Labels: e: device-specific, platform-android, engine, P1, e: impeller, team-engine, triaged-engine, e: impeller-naughty-driver

**Comment by jonahwilliams** [comment] 2024-09-26 17:16
No we're not going to cherry pick things into beta,this beta does not go to stable AFAIK.
