### ISSUE TITLE
Regression in src/widgets/framework.dart

### ISSUE THREAD

**Issue by emlynmac** [flutter/flutter#83728] opened 2021-06-01 18:07 UTC
I migrated from 2.0.3 to 2.2.1 and had a bunch of breaks in my test code.

The root cause of this is in `src/widgets/framework.dart` 
```
Element? get _currentElement =>
      WidgetsBinding.instance!.buildOwner!._globalKeyRegistry[this];
```
In the case where these objects are nil, it crashes.
Should this not be:
```
Element? get _currentElement =>
      WidgetsBinding.instance?.buildOwner?._globalKeyRegistry[this];
```

**Comment by darshankawar** [comment] 2021-06-02 10:39
@emlynmac 
Can you provide a complete minimal reproducible code sample that shows this regression alongwith complete `flutter doctor -v` ?

Thanks.

**Comment by emlynmac** [comment] 2021-06-02 13:43
Sorry, not at the moment. I’d have thought the code inspection was enough to see the issue here

**Comment by darshankawar** [comment] 2021-06-03 06:00
@emlynmac 
Yes we do see the change as you mentioned, but I am trying to find a PR / commit which may have updated it and in order to properly address this issue, would need a minimal code sample to see how it affects or introduces breaking changes.

Thanks.

**Comment by emlynmac** [comment] 2021-06-03 15:45
To me, it looks like this change: https://github.com/flutter/flutter/commit/5584fce36e8e68505b75655fde7c42ded597d49e caused the issue.

It's not safe to force-unwrap a value if it could be nil; so simply replacing the ! with ? will maintain the API but also not cause a crash.

**Comment by darshankawar** [comment] 2021-06-04 05:44
Thanks. Keeping this open for further insights from the team.

Cc: @tvolkert

**Comment by tvolkert** [comment] 2021-06-04 06:09
Both the static `WidgetsBinding.instance` and the instance member `WidgetsBinding.buildOwner` should be non-null.  Are you running code before you call `runApp()`?  If so, you need to call `WidgetsFlutterBinding.ensureInitialized()`.

**Comment by tvolkert** [comment] 2021-06-04 06:09
A minimal repro test case is needed to investigate further.

**Comment by tvolkert** [comment] 2021-06-11 16:44
@emlynmac I'm going to close this issue as working as intended (see my [note above](https://github.com/flutter/flutter/issues/83728#issuecomment-854387714)).  If you come up with a minimal repro case that you believe argues for adding null-check operators, then please feel free to re-open.

**Comment by kuhnroyal** [comment] 2021-06-11 17:20
@tvolkert Thanks for the link to this issue.
I understand that I should call `WidgetsFlutterBinding.ensureInitialized()` and I do that in my app. But I also need to call some code (i18n setup) from an isolate where I can't call this and the library fails at that point.
What would be the correct check for the library to detect if the code is executed in an isolate?

**Comment by tvolkert** [comment] 2021-06-11 17:34
@kuhnroyal do you have a stack trace of how the code that runs in an isolate ends up trying to access the global key registry?  The fact that the code running in an isolate ends up running framework code is a [code smell](https://en.wikipedia.org/wiki/Code_smell).

**Comment by kuhnroyal** [comment] 2021-06-11 18:07
Well, it is a static call setting the locale which in turn is trying to set some translation provider settings via a `GlobalKey`. The code can probably be changed but I am not sure how to detect if a particular isolate is the flutter isolate.

**Comment by tvolkert** [comment] 2021-06-11 19:44
Interesting... if you could get a stack trace, that would be really helpful.  I'll re-open this issue for now.

**Comment by arthurpiccoli** [comment] 2021-07-07 20:27
I have a similar issue related to this using a state management package while testing, it is causing an exception when checking if the context is null: https://github.com/jonataslaw/getx/issues/1554

**Closed** 2021-07-07 20:35 UTC
Labels: framework, passed first triage, waiting for customer response

**Comment by arthurpiccoli** [comment] 2021-07-07 20:53
@tvolkert is the issue I talked about helpful for this issue? The bot closed this one right after my comment.

**Comment by tvolkert** [comment] 2021-07-08 03:46
@arthurpiccoli try calling `TestWidgetsFlutterBinding.ensureInitialized()` before your test runs.

**Comment by arthurpiccoli** [comment] 2021-07-08 16:59
> @arthurpiccoli try calling `TestWidgetsFlutterBinding.ensureInitialized()` before your test runs.

This did the trick. Working fine now.

**Comment by emlynmac** [comment] 2021-07-21 22:11
Confirmed fix for my case too.
