### ISSUE TITLE
Memory leaks on iOS when working with images

### ISSUE THREAD

**Issue by AAverin1994** [flutter/flutter#45391] opened 2019-11-22 08:58 UTC
## Description of the problem

My application works with a large number of pictures (about 1000 images). Periodically, my application crashes with OOM. 

As a test of this problem, a series of experiments was carried out. For carrying out the experiments, 2 projects were created. The first project is implemented on **flutter** and the second is native using **Xcode version 11.1**. 
The task of these projects is to load a certain number of pictures and draw them in a scrollable list. 

**ListView** is used as a scrollable list in a flutter project. 
Native implementation uses **Collection View**.

Flutter versions used for comparison (v1.9.1+hotfix.6 and v1.12.5-pre.45).

The test results are shown in the tables below. 
Description of table columns:

- **Start memory size (mb)** - amount of RAM used after the images have been downloaded and displayed.
- **Peak memory size (mb)** - high value of RAM, which was recorded during the intensive scrolling of images.

**OOM** - RAM overflow.

### Link to the test projects repository
[https://github.com/AAverin1994/flutter_image_memory_leak](https://github.com/AAverin1994/flutter_image_memory_leak)

## First experiment

The first experiment downloads pictures from the network and draws them. 

Flutter Results:

**Flutter v1.9.1+hotfix.6**

image resolution | Start memory size (mb) | Peak memory size (mb)
--  | -- | --
320x240 | 209,3 | 209,8
640x480 | 502,8 | 631,2
1024x768 | 1002 | OOM
2048x1080 | 1002,1 | OOM
4096x3072 | OOM | OOM

**Flutter v1.12.5-pre.45**

image resolution | Start memory size (mb) | Peak memory size (mb)
--  | -- | --
320x240 | 199,3 | 197,6
640x480 | 490,1 | 545,5
1024x768 | 930 | 1005
2048x1080 | 1003 | OOM
4096x3072 | OOM | OOM

Result of native implementation:

image resolution | Start memory size (mb) | Peak memory size (mb)
-- | -- | --
320x240 | 32,1 | 45,8
640x480 | 43,9 | 47,3
1024x768 | 80,3 | 81,3
2048x1080 | 89 | 98,8
4096x3072 | 116 | 137,8

## Second experiment

The next experiment is to upload and render pictures from local storage. 

Flutter Results:

**Flutter v1.9.1+hotfix.6**

image resolution | Start memory size (mb) | Peak memory size (mb)
-- | -- | --
320x240 | 1000 | 138,1 | 158
640x480 | 1000 | 228,6 | 241,3
1024x768 | 1000 | 327 | 330
2048x1080 | 1000 | 346,6 | 349
4096x3072 | 1000 | 372 | 391

**Flutter v1.12.5-pre.45**

image resolution | Start memory size (mb) | Peak memory size (mb)
-- | -- | --
320x240 | 77,9 | 91,3
640x480 | 163,4 | 179,3
1024x768 | 252,9 | 265,7
2048x1080 | 353,5 | 363,1
4096x3072 | 277,7 | 290,4

Result of native implementation:

image resolution | Start memory size (mb) | Peak memory size (mb)
-- | -- | --
320x240 | 18,6 | 19,3
640x480 | 44,4 | 45,7
1024x768 | 75,6 | 78
2048x1080 | 92 | 95,3
4096x3072 | 113,7 | 117,3

## Result
As a result, I want to note a very strong difference in the use of RAM between flutter and native. 
As far as I understand, my problem is related to problems [#13242](https://github.com/flutter/flutter/issues/13242) and [#23231](https://github.com/flutter/flutter/issues/23231)

Any ideas or suggestions for solving this problem?

Thanks!

## Used platform and device

**Target Platform: iOS**
**Target OS version/browser: iOS 12.4**
**Devices: iPhone 12.4**

## Flutter doctor

[✓] Flutter (Channel master, v1.12.5-pre.45, on Mac OS X 10.14.6 18G103, locale en-RU)
    • Flutter version 1.12.5-pre.45 at /Users/andrewaverin/Development/flutter
    • Framework revision 73c32545b7 (2 days ago), 2019-11-20 11:02:35 +0000
    • Engine revision 176f563296
    • Dart version 2.7.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at /Users/andrewaverin/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    • CocoaPods version 1.7.1

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 37.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.40.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.6.0

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

**Comment by iapicca** [comment] 2019-11-22 13:02
Hi @AAverin1994 
you certainly provided plenty of data,
and a useful comparison between version, thank you for that.

This issue appear to be a duplicate of the one you linked above
can you please underline between the two?
thanks again

**Comment by minikin** [comment] 2019-11-22 15:18
@AAverin1994  I don't think that tests are fair. 
In a Flutter project, you use [ListView](https://github.com/AAverin1994/flutter_image_memory_leak/blob/fc2026dedbdee34eebbb35345f15ed117a3de659/memory_leak_flutter_project/lib/main.dart#L82), without a builder. This type of ListView works well for small lists. However, in an iOS project, you use [UICollectionView](https://github.com/AAverin1994/flutter_image_memory_leak/blob/fc2026dedbdee34eebbb35345f15ed117a3de659/iOS_native_memory_leak_test/iOS_native_memory_leak_test/ViewController.swift#L114) which uses a different algorithm (it reuse cells).

Try to run your tests with [ListView.builder](https://flutter.dev/docs/cookbook/lists/long-lists) instead. It'll be interesting to see the results.

**Comment by ds84182** [comment] 2019-11-22 17:36
Assuming the rest of Flutter has an overhead of ~11mb, I'm assuming that for all tests in the starting state there were 100 images loaded on screen. I'm currently estimating these numbers using raw math, I admit I should really take a look at the code.

This feels like native iOS is doing image resizing, while Flutter is not. Can you try to see if [ResizeImage](https://github.com/flutter/flutter/blob/a60bf8e23a2ff683fee2c521f01cc2bb814a6749/packages/flutter/lib/src/painting/image_provider.dart#L522) fixes your problem?

Assuming that the native version is decompressing the 320x240 images to an RGBA8 texture, Native iOS has an initial overhead of ~3mb. We can use this to figure out that each image on the 2048x1080 version is using only around 1.1mb of memory, leading me to believe that the image is actually being loaded around 630x471. It could actually be smaller or larger, entirely depending on whether iOS keeps the remote image's bytes around after loading it into memory.

@AAverin1994 Please let me know if this helps, or if just adds to the confusion.

**Comment by AAverin1994** [comment] 2019-11-25 14:38
> @AAverin1994 I don't think that tests are fair.
> In a Flutter project, you use [ListView](https://github.com/AAverin1994/flutter_image_memory_leak/blob/fc2026dedbdee34eebbb35345f15ed117a3de659/memory_leak_flutter_project/lib/main.dart#L82), without a builder. This type of ListView works well for small lists. However, in an iOS project, you use [UICollectionView](https://github.com/AAverin1994/flutter_image_memory_leak/blob/fc2026dedbdee34eebbb35345f15ed117a3de659/iOS_native_memory_leak_test/iOS_native_memory_leak_test/ViewController.swift#L114) which uses a different algorithm (it reuse cells).
> 
> Try to run your tests with [ListView.builder](https://flutter.dev/docs/cookbook/lists/long-lists) instead. It'll be interesting to see the results.

Hello @minikin. 
Thanks for the answer, I tried using ListView.builder but the result was the same. 
Table with the results:

image resolution | image count | Start memory size (mb) | Peak memory size (mb)
-- | -- | -- | --
320x240 | 1000 | 248,3 | 258,2
640x480 | 1000 | 564,5 | 661,7
1024x768 | 1000 | 1008 | OOM
2048x1080 | 1000 | 1022 | OOM
4096x3072 | 1000 | OOM | OOM

**Comment by minikin** [comment] 2019-11-25 17:11
@AAverin1994 Thanks for the update! You're right. I can confirm that I also can reproduce this issue with big (4096x3072) images: https://github.com/minikin/flutter_image_memory_leak

**Comment by VytorCalixto** [comment] 2019-11-25 20:25
I'm having the same problem in android when working with network images in v1.9.1+hotfix.6

**Comment by f-martinez11-loro** [comment] 2019-11-25 22:01
I also have this problem. On iPhone 6 is easy to get an OOM error.

**Comment by VytorCalixto** [comment] 2019-11-26 01:18
I've run the test app on profile mode on a Galaxy A10 and recorded the results: https://youtu.be/LZ0cqlHgXPk

**Comment by AAverin1994** [comment] 2019-11-26 08:54
> Assuming the rest of Flutter has an overhead of ~11mb, I'm assuming that for all tests in the starting state there were 100 images loaded on screen. I'm currently estimating these numbers using raw math, I admit I should really take a look at the code.
> 
> This feels like native iOS is doing image resizing, while Flutter is not. Can you try to see if [ResizeImage](https://github.com/flutter/flutter/blob/a60bf8e23a2ff683fee2c521f01cc2bb814a6749/packages/flutter/lib/src/painting/image_provider.dart#L522) fixes your problem?
> 
> Assuming that the native version is decompressing the 320x240 images to an RGBA8 texture, Native iOS has an initial overhead of ~3mb. We can use this to figure out that each image on the 2048x1080 version is using only around 1.1mb of memory, leading me to believe that the image is actually being loaded around 630x471. It could actually be smaller or larger, entirely depending on whether iOS keeps the remote image's bytes around after loading it into memory.
> 
> @AAverin1994 Please let me know if this helps, or if just adds to the confusion.

Hello @ds84182. Thanks for the answer. 
I tried using **cacheWidth** and **cacheHeight** parameters in **Image**. I set the value to 100, which means rendering the image in a resolution 100x100. This partially reduces memory consumption, because small images are rendered, but the memory still continues to grow, but not so fast.

**Comment by ds84182** [comment] 2019-11-27 05:27
@AAverin1994 thanks for the update, you might want to follow along with #19558, which is tracking image related memory usage

**Comment by dnfield** [comment] 2020-02-07 08:55
I believe this was fixed by #48536 

If not, we can reopen.

**Closed by dnfield** 2020-02-07 08:55 UTC
Labels: a: images, engine, severe: performance

**Comment by AAverin1994** [comment] 2020-02-07 10:19
> I believe this was fixed by #48536
> 
> If not, we can reopen.

@dnfield thank you very much for the answer! Now in all places where a list view(grid view) is used, you need to use a ScrollAwareImageProvider for images to use?

**Comment by dnfield** [comment] 2020-02-07 15:19
The Image widget will do it automatically.  If you're using FadeInImage you need to add it yourself right now.

**Comment by danielgchap** [comment] 2020-02-10 06:09
@dnfield Hi there, thanks for the input. So.. how do we fix this for images over the network? Use image.network? I did that and didn't see much different using the Observatory. I'm on the flutter stable channel. Thanks boss.

**Comment by dnfield** [comment] 2020-02-10 15:30
This is not available on stable yet.  It should be on dev by now, and if not will be in the next dev r elease

**Comment by danielgchap** [comment] 2020-02-10 19:48
@dnfield you are the man. Thanks. I also found that my image caching code was gone (bad commit maybe), so the images I was downloading from firebase for my listview.builder were averaging about 5-6mb each which is a bit much to ask, even for local cache reloads. Got my code back in and seeing much better averages that are <1MB. Between this, your dev work and me working to further break down my widgets into smaller consumables, I think I'm on the right track.

Appreciate you sir. Thanks again.

**Comment by hattb-log** [comment] 2020-07-31 08:45
Hi @dnfield  Could you tell me which the version we resolved this issue. Thanks!

**Comment by dnfield** [comment] 2020-07-31 15:02
The earliest version with this was v1.15.0

**Comment by bhanuka96** [comment] 2021-02-14 18:32
> The earliest version with this was v1.15.0

@dnfield Hi, Our app use lots of images from the network. memory leak to 75% of users.it means the app crash, can't use. How do I fix this issue? btw, I use `Image.network` widget. I didn't set these two parameters. because the image is getting very low quality when set `cacheHeight` and `cacheWidth`

**Comment by cirnok** [comment] 2021-02-14 20:15
> > The earliest version with this was v1.15.0
> 
> @dnfield Hi, Our app use lots of images from the network. memory leak to 75% of users.it means the app crash, can't use. How do I fix this issue? btw, I use `Image.network` widget. I didn't set these two parameters. because the image is getting very low quality when set `cacheHeight` and `cacheWidth`

I have exactly the same problem and it's terrible. I have to sacrifice a lot of functionality to optimize this problem. I don't understand why the developers turn a blind eye to this.

**Comment by iapicca** [comment] 2021-02-14 20:39
@bhanuka96  @cirnok 
this PR was merged more than 6 months ago, 
I suggest to open a new issue providing your `flutter doctor -v`, 
your `flutter run ---release -v` and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by cirnok** [comment] 2021-02-14 20:45
> @bhanuka96 @cirnok
> this PR was merged more than 6 months ago,
> I suggest to open a new issue providing your ,
> your and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)`flutter doctor -v``flutter run ---release -v`

@iapicca https://github.com/flutter/flutter/issues/62107
There is no need, there is already an issue, but no one has been doing anything about this problem since november.

**Comment by iapicca** [comment] 2021-02-14 21:01
@cirnok 
the issue you referenced is a `documentation` request issue, it's not gonna fix any memory leak

**Comment by bhanuka96** [comment] 2021-02-15 11:21
@iapicca You are right. I am searching for a solution for so long. I find only documentation, not any solution. we lost 75% of users because of this memory leak

**Comment by iapicca** [comment] 2021-02-15 11:38
@bhanuka96 
in that issue a comment from team member says it WAI
you might want to consider a different strategy for caching

**Comment by tahaafg20** [comment] 2021-03-03 09:20
The issue still remains, a lot of other developers including myself are still experiencing the issue and it's really important not to sacrifice the quality just to prevent the app from crashing, please reopen!
