### ISSUE TITLE
[tool_crash] FileSystemException: Cannot open file, OS Error: O arquivo já está sendo usado por outro processo., errno = 32

### ISSUE THREAD

**Issue by gustabmo** [flutter/flutter#149089] opened 2024-05-25 15:06 UTC
## Command
```
flutter upgrade
```

## Steps to Reproduce
1. ... just run flutter upgrade
2. ...
3. ...

## Logs
FileSystemException: Cannot open file, OS Error: O arquivo já está sendo usado por outro processo.
, errno = 32
```
#0      _File.throwIfError (dart:io/file_impl.dart:675:7)
#1      _File.openSync (dart:io/file_impl.dart:490:5)
#2      _File.writeAsBytesSync (dart:io/file_impl.dart:644:31)
#3      _File.writeAsStringSync (dart:io/file_impl.dart:668:5)
#4      ForwardingFile.writeAsStringSync (package:file/src/forwarding/forwarding_file.dart:150:16)
#5      ErrorHandlingFile.writeAsStringSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:267:22)
#6      _runSync (package:flutter_tools/src/base/error_handling_io.dart:590:14)
#7      ErrorHandlingFile.writeAsStringSync (package:flutter_tools/src/base/error_handling_io.dart:266:5)
#8      Config._flushValues (package:flutter_tools/src/base/config.dart:185:11)
#9      Config.setValue (package:flutter_tools/src/base/config.dart:174:5)
#10     _DefaultPersistentToolState.updateLastActiveVersion (package:flutter_tools/src/persistent_tool_state.dart:116:13)
#11     UpgradeCommandRunner.recordState (package:flutter_tools/src/commands/upgrade.dart:185:34)
#12     UpgradeCommandRunner.runCommandFirstHalf (package:flutter_tools/src/commands/upgrade.dart:171:5)
<asynchronous suspension>
#13     UpgradeCommandRunner.runCommand (package:flutter_tools/src/commands/upgrade.dart:106:7)
<asynchronous suspension>
#14     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1367:27)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#16     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#17     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:348:9)
<asynchronous suspension>
#18     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
```
```
[32m[✓][39m Flutter (Channel stable, 3.16.9, on Microsoft Windows [versÆo 10.0.19045.4412], locale en-US)
    [32m•[39m Flutter version 3.16.9 on channel stable at C:\portable\flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision 41456452f2 (4 months ago), 2024-01-25 10:06:23 -0800
    [32m•[39m Engine revision f40e976bed
    [32m•[39m Dart version 3.2.6
    [32m•[39m DevTools version 2.28.5

[32m[✓][39m Windows Version (Installed version of Windows is version 10 or higher)

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    [32m•[39m Android SDK at C:\Users\gusta\AppData\Local\Android\Sdk
    [32m•[39m Platform android-34, build-tools 34.0.0
    [32m•[39m Java binary at: c:\Program Files\Android\Android Studio\jbr\bin\java
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[32m[✓][39m Visual Studio - develop Windows apps (Visual Studio Community 2022 17.8.5)
    [32m•[39m Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    [32m•[39m Visual Studio Community 2022 version 17.8.34511.84
    [32m•[39m Windows 10 SDK version 10.0.22621.0

[32m[✓][39m Android Studio (version 2023.1)
    [32m•[39m Android Studio at c:\Program Files\Android\Android Studio
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m android-studio-dir = c:\Program Files\Android\Android Studio
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)

[32m[✓][39m VS Code (version 1.88.1)
    [32m•[39m VS Code at C:\Users\gusta\AppData\Local\Programs\Microsoft VS Code
    [32m•[39m Flutter extension version 3.84.0

[32m[✓][39m Connected device (3 available)
    [32m•[39m Windows (desktop) • windows • windows-x64    • Microsoft Windows [versÆo 10.0.19045.4412]
    [32m•[39m Chrome (web)      • chrome  • web-javascript • Google Chrome 125.0.6422.60
    [32m•[39m Edge (web)        • edge    • web-javascript • Microsoft Edge 124.0.2478.67

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[32m•[39m No issues found!

```

## Flutter Application Metadata
No pubspec in working directory.

**Comment by huycozy** [comment] 2024-05-27 08:55
Closing this as a duplicate of https://github.com/flutter/flutter/issues/148583. Please check the question from the linked issue at https://github.com/flutter/flutter/issues/148583#issuecomment-2119842363.

**Closed by huycozy** 2024-05-27 08:55 UTC
Labels: in triage
