### ISSUE TITLE
Flutter Code Obfuscation - Android build issue  - classes or functions are not obfuscated

### ISSUE THREAD

**Issue by coder-kl** [flutter/flutter#48718] opened 2020-01-13 13:11 UTC
I see flutter code obfuscated properly for iOS build, however Android production build seems not working correctly . I have confirmed that Proguard or R8 modules runs when a production build is created. However, libapp.so contains classes and function names as is for the Android build.

Here are my settings to enable Proguard or R8.
build.gradle
--------------------------------------------------------------------
```
buildscript {
    repositories {
        google()
        jcenter()

        // Additional repository for fabric resources
        maven {
            url 'https://maven.fabric.io/public'
        }
    }   
    dependencies {
        classpath 'com.android.tools.build:gradle:3.5.0'
        classpath 'com.google.gms:google-services:4.2.0'  // Google Services plugin
        classpath 'io.fabric.tools:gradle:1.26.1'          // Add fabric classpath
    }
}
allprojects {
```
buildTypes detail:
------------------
```
buildTypes {
        release {
            signingConfig signingConfigs.release

            minifyEnabled true
            useProguard true

            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
```
Proguard Rules file:
---------------------------
```
#Flutter Wrapper
-optimizationpasses 5
-keep class io.flutter.app.** { *; }
-keep class io.flutter.plugin.**  { *; }
-keep class io.flutter.util.**  { *; }
-keep class io.flutter.view.**  { *; }
-keep class io.flutter.**  { *; }
-keep class com.google.android.gms.** { *; }
-keep class com.google.firebase.** { *; }
-keep class com.crashlytics.** { *; }
```

iOS mapping file example:

"RegistrationService","Zk" - RegistrationService is one of my service class, which is obfuscated as Zk. 
"_registerUser@96127098","_Bgb@96127098" - register user method changed to _Bgb.

However, `mapping.txt` under `outputs->bundle->release->mapping` does not contains any obfuscation detail for Dart classes or methods. I do see some obfuscated code details, for plugin classes not included in pro-guard rules file, but it seems Dart code is left out.

```
com.tekartik.sqflite.operation.BaseReadOperation -> com.tekartik.sqflite.operation.BaseReadOperation:
    void <init>() -> <init>
    java.lang.String getSql() -> f
    java.util.List getSqlArguments() -> g
    com.tekartik.sqflite.SqlCommand getSqlCommand() -> b
    java.lang.Boolean getInTransaction() -> c
    boolean getNoResult() -> d
    boolean getContinueOnError() -> e
    java.lang.Boolean getBoolean(java.lang.String) -> b
    com.tekartik.sqflite.operation.OperationResult getOperationResult() -> a
```

If I open `libapp.so` file from app bundle, I see all my dart code function names and classes as is. I see 

```
RegisterationService reference and _registerUser method as is.
For ex. 
get:_registerUser@95127098K§
/api/registration.service.dart8KæèúRegistrationService8KÇì
```

Is there anything I missed or do I have to add any additional rules in pro-guard.rules file? Any feedback will helpful to have obfuscated build for Android.

Thank you.

**Comment by jonahwilliams** [comment] 2020-01-13 15:18
Duplicate of https://github.com/flutter/flutter/issues/47049

**Closed by jonahwilliams** 2020-01-13 15:18 UTC
Labels: t: gradle, ▣ platform-android

**Comment by coder-kl** [comment] 2020-01-14 01:32
Thank you @jonahwilliams for feedback. 

Just to confirm, we basically need to downgrade to v1.9.1+hotfix.6 for now. The fix will available in the next release.
