### ISSUE TITLE
iOS gesture down OtherViewController to FlutterViewController

### ISSUE THREAD

**Issue by helang1991** [flutter/flutter#35784] opened 2019-07-09 03:20 UTC
## Steps to Reproduce

I wanna jump to other viewController by Plugin in Flutter, however, i met a problem: the FlutterViewController can receive gesture events from other viewController.
this is my demo link: [https://github.com/helang1991/flutter_iOS_gesture_demo](url)

screenshot: 
![image](https://github.com/helang1991/flutter_iOS_gesture_demo/blob/master/images/222.png)
## Logs

```
Reloaded 1 of 441 libraries in 502ms.
flutter: I received gesture events in FlutterViewController
flutter: I received gesture events in FlutterViewController
flutter: I received gesture events in FlutterViewController
flutter: I received gesture events in FlutterViewController
flutter: I received gesture events in FlutterViewController
flutter: I received gesture events in FlutterViewController
flutter: I received gesture events in FlutterViewController
flutter: I received gesture events in FlutterViewController
flutter: I received gesture events in FlutterViewController
```
```
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.5 18F132, locale
    en-CN)
    • Flutter version 1.5.4-hotfix.2 at /Users/helang/Flutter/flutter
    • Framework revision 7a4c33425d (2 months ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

 
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/helang/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/helang/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1343-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses

[!] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    ✗ libimobiledevice and ideviceinstaller are not installed. To install with
      Brew, run:
        brew update
        brew install --HEAD usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    ✗ ios-deploy not installed. To install:
        brew install ios-deploy
    • CocoaPods version 1.6.1

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 37.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1343-b01)

[✓] Connected device (1 available)
    • iPhone Xʀ • 72F8738C-7190-48B4-956C-50A0DE6B74BC • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)

! Doctor found issues in 3 categories.
```

**Comment by Piinks** [comment] 2019-07-09 18:39
Hi @helang1991, can you post a reproduction of the issue as well as the output of `flutter doctor`? We will need more information to help you resolve it.

**Comment by helang1991** [comment] 2019-07-10 01:48
Hi @Piinks ,I clicked screen in other viewController by plugin,  why the FlutterViewController received gesture events? Maybe other developers made similar issue.

**Comment by helang1991** [comment] 2019-07-10 01:53
flutter doctor:

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.5 18F132, locale
    en-CN)
 
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses
[!] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    ✗ libimobiledevice and ideviceinstaller are not installed. To install with
      Brew, run:
        brew update
        brew install --HEAD usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    ✗ ios-deploy not installed. To install:
        brew install ios-deploy
[✓] Android Studio (version 3.4)
[!] IntelliJ IDEA Ultimate Edition (version 2018.2.2)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] Connected device (1 available)

! Doctor found issues in 3 categories.

**Comment by crackerli** [comment] 2019-07-10 02:28
> Hi @helang1991, can you post a reproduction of the issue as well as the output of `flutter doctor`? We will need more information to help you resolve it.

I also met the problem, from the beginning, I want to develop a customized camera, a new plugin is developed to achieve this, the customized camera is a native page, when I open the camera page from flutter button, then there are two pages in app, foreground native camera page and background flutter page, something bad happened here were that when I click on the native camera page, the background futter page can receive the click event, eg. some button can react to these events.

Til now, I found the issue can be reproduced only in ios platform, android works well.

I found that image_picker have the same issue, please refer this link below:
https://github.com/flutter/flutter/issues/32896

Further more, to find the root cause, I replace the camera native page with one common native page of ios, this issue can be produced too

**Comment by crackerli** [comment] 2019-07-17 01:35
Any update on this issue? @Piinks Piinks

**Comment by maeharin** [comment] 2019-07-30 03:14
I encountered the same problem. Here is my investigation and current workaround.

## Sample application
https://github.com/maeharin/flutter_ios_present_sample

## Screenshot

![screenshot](https://user-images.githubusercontent.com/1523308/62097662-8833b380-b2c2-11e9-882f-dc6c48af1f10.gif)

## Why this occured

Looking at the implementation of FlutterViewController (ex: engine v1.5.4-hotfixes branch), we can see they are overriding 4 methods(such as the touchesBegan). From here, the iOS touch event is propagated to the Flutter side
https://github.com/flutter/engine/blob/v1.5.4-hotfixes/shell/platform/darwin/ios/framework/Source/FlutterViewController.mm#L649-L663

See the apple documentation below for how to call touchesBegan. Touch events on the iOS side are designed to run up the Responder Chain
https://developer.apple.com/documentation/uikit/touches_presses_and_gestures/using_responders_and_the_responder_chain_to_handle_events

In our case, Responder Chain is like this

- Tap the part of UI where there is no event handler
- A tap event runs up the Responder Chain on iOS and propagates to FlutterViewController's touchesBegan ()
- Flutter side event handler is called

![スクリーンショット 2019-07-30 12 13 28](https://user-images.githubusercontent.com/1523308/62097922-74d51800-b2c3-11e9-9660-47df0a206c42.png)


## Workaround

The following workarounds can be considered

### 1. Override 4 methods of UIViewController that is presented from FlutterViewController

This prevents propagating unhandled events to FlutterViewController

```swift
override func touchesBegan(_ touches: Set<UITouch>, with event: UIEvent?) {}
override func touchesMoved(_ touches: Set<UITouch>, with event: UIEvent?) {}
override func touchesEnded(_ touches: Set<UITouch>, with event: UIEvent?) {}
override func touchesCancelled(_ touches: Set<UITouch>, with event: UIEvent?) {}
```

### 2. Stop doing present from FlutterViewController

Do not present() the UIViewController directly from the FlutterViewController, for example, by making the iOS side rootViewController a NavigationController instead of a FlutterViewController.
This article will be helpful for how to change rootViewController

https://medium.com/@najeira/change-ios-rootviewcontroller-with-flutter-fc4234f37105

**Comment by helang1991** [comment] 2019-07-30 05:58
> I encountered the same problem. Here is my investigation and current workaround.
> 
> ## Sample application
> https://github.com/maeharin/flutter_ios_present_sample
> 
> ## Screenshot
> ![screenshot](https://user-images.githubusercontent.com/1523308/62097662-8833b380-b2c2-11e9-882f-dc6c48af1f10.gif)
> 
> ## Why this occured
> Looking at the implementation of FlutterViewController (ex: engine v1.5.4-hotfixes branch), we can see they are overriding 4 methods(such as the touchesBegan). From here, the iOS touch event is propagated to the Flutter side
> https://github.com/flutter/engine/blob/v1.5.4-hotfixes/shell/platform/darwin/ios/framework/Source/FlutterViewController.mm#L649-L663
> 
> See the apple documentation below for how to call touchesBegan. Touch events on the iOS side are designed to run up the Responder Chain
> https://developer.apple.com/documentation/uikit/touches_presses_and_gestures/using_responders_and_the_responder_chain_to_handle_events
> 
> In our case, Responder Chain is like this
> 
> * Tap the part of UI where there is no event handler
> * A tap event runs up the Responder Chain on iOS and propagates to FlutterViewController's touchesBegan ()
> * Flutter side event handler is called
> 
> ![スクリーンショット 2019-07-30 12 13 28](https://user-images.githubusercontent.com/1523308/62097922-74d51800-b2c3-11e9-9660-47df0a206c42.png)
> 
> ## Workaround
> The following workarounds can be considered
> 
> ### 1. Override 4 methods of UIViewController that is presented from FlutterViewController
> This prevents propagating unhandled events to FlutterViewController
> 
> ```swift
> override func touchesBegan(_ touches: Set<UITouch>, with event: UIEvent?) {}
> override func touchesMoved(_ touches: Set<UITouch>, with event: UIEvent?) {}
> override func touchesEnded(_ touches: Set<UITouch>, with event: UIEvent?) {}
> override func touchesCancelled(_ touches: Set<UITouch>, with event: UIEvent?) {}
> ```
> 
> ### 2. Stop doing present from FlutterViewController
> Do not present() the UIViewController directly from the FlutterViewController, for example, by making the iOS side rootViewController a NavigationController instead of a FlutterViewController.
> This article will be helpful for how to change rootViewController
> 
> https://medium.com/@najeira/change-ios-rootviewcontroller-with-flutter-fc4234f37105

Thanks for your advice,  I'll try your methods to fix it

**Comment by iapicca** [comment] 2020-03-16 14:51
Hi @earyzhe 
if the issue persist with the latest stable version of flutter
could you please provide your updated `flutter doctor -v` ,
your `flutter run --verbose` 
and if possible a reproducible minimal code sample.
Thank you

**Comment by iapicca** [comment] 2020-05-29 09:17
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by iapicca** 2020-05-29 09:17 UTC
Labels: f: gestures, framework, platform-ios, waiting for customer response
