### ISSUE TITLE
Enable web golden tests

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#47003] opened 2019-12-13 20:44 UTC
The tests fail with "Unknown error loading". For example:

```
02:03 +118 ~33 -1: compiling /tmp/flutter sdk/packages/flutter/test/widgets/list_view_vertical_test.dart [E]                                                                                           
  Failed to load "/tmp/flutter sdk/packages/flutter/test/widgets/list_view_vertical_test.dart": Unknown error loading http://localhost:43947/packages/flutter/material.ddc.js
```

Seen in the following, but I've seen it multiple times lately.

https://cirrus-ci.com/task/5055207964147712?command=main#L759
https://cirrus-ci.com/task/5899632894279680?command=main#L2370

/cc @jonahwilliams and @yjbanov who may know what's going on.

**Comment by dnfield** [comment] 2019-12-13 20:46
Related: https://github.com/flutter/devtools/issues/82

**Comment by dnfield** [comment] 2019-12-13 20:47
Related: https://github.com/flutter/devtools/issues/94

**Comment by tvolkert** [comment] 2019-12-13 20:53
I'm seeing this a bunch on Cirrus.  Most recently https://cirrus-ci.com/task/6533960909193216

**Comment by jonahwilliams** [comment] 2019-12-13 20:57
I think @yjbanov wrote that particular message. If the browser is failing to load the file, perhaps we could modify the require js configuration generated to retry loading files that fail?

**Comment by dnfield** [comment] 2019-12-13 21:02
Retry seems like it would help.  Where does the relevant package live? I was trying to grep this repo for it and not finding it.

**Comment by jonahwilliams** [comment] 2019-12-13 21:11
The RequireJS imports are generated by DDC (cc @nshahan ) while the actual test entrypoints are generated by build_web_compilers (cc @jakemac53  )

**Comment by jakemac53** [comment] 2019-12-13 21:38
You can set the timeout for require JS - for regular dart web we set it to never expire (the server will respond with an error if the filed doesn't exist). Not sure where to look to confirm if that is set up the same here or not.

I didn't see any compile errors in the build logs so I am not sure exactly where/how to start debugging this issue.

**Comment by dnfield** [comment] 2019-12-13 21:46
> You can set the timeout for require JS

Where? :)

**Comment by jakemac53** [comment] 2019-12-13 21:52
https://requirejs.org/docs/api.html#config-waitSeconds

https://github.com/dart-lang/build/blob/master/build_web_compilers/lib/src/dev_compiler_bootstrap.dart#L444

**Comment by dnfield** [comment] 2019-12-16 18:40
I think rather than introducing a timeout, we'd rather introduce a retry.

**Comment by dnfield** [comment] 2019-12-16 18:42
AFAICT, setting it to zero means an infinite timeout anyway.  We just want to try again say 3 or 5 times if it times out.

**Comment by dnfield** [comment] 2019-12-16 19:10
Here's an example where one shard flaked 5 times before passing: https://cirrus-ci.com/task/6026662860292096

**Comment by jakemac53** [comment] 2019-12-17 15:42
I don't think that require.js supports retry logic, at least I don't see anything.

It is also really hard to tell if we are getting a timeout or an actual failed request here. The retry would help for the latter case but likely not the former case.

**Comment by dnfield** [comment] 2019-12-17 18:04
So alternatively it seems like there may be some condition the test should be waiting for.  It seems like sometimes on CI, Chrome takes long enough to get something ready that require ends up not being able to load the file.  If we knew what condition that was we could wait for it.

**Comment by yjbanov** [comment] 2019-12-19 23:27
@chingjun at least one of the log files points to `button_theme_test.dart`:

```
00:43 +87 ~2 -1: compiling /tmp/flutter sdk/packages/flutter/test/material/button_theme_test.dart [E]                                                                                                  
  Failed to load "/tmp/flutter sdk/packages/flutter/test/material/button_theme_test.dart": Unknown error loading 
```

I recall that you started seeing this error in the PR that enabled screenshots. What was the final resolution to that problem?

One possible fix for this is to disable screenshots. I can take a look at this problem when I'm back ~Jan 6.

**Comment by chingjun** [comment] 2019-12-19 23:48
Yes that was when I first saw the failures. There were a few runs in a row when the tests passed so we decided that it was just a flake.

I do notice from all the links posted here that, of all the failures, there are at least one screenshot test that run before them, not sure if it's caused by the screenshot tests or is it because we basically have screenshot tests in every shards now.

We could try to disable all but one screenshot tests, and see if the shard containing that test still flakes.

**Comment by dnfield** [comment] 2019-12-20 00:32
I think we should try disabling screen shot tests until this can be further triaged.  I would try to look into it more but I'm not quite sure where to start.

**Comment by yjbanov** [comment] 2019-12-20 16:38
We could try a simple A/B experiment first, where we compare a no-op `matchesGoldenFile` vs a real `matchesGoldenFile`.

**Comment by yjbanov** [comment] 2020-01-07 21:23
I've been out for a few weeks. Did disabling screenshot tests fix the flakiness?

**Comment by chingjun** [comment] 2020-01-07 21:48
I believe so. I left a few screenshot tests enabled and the flakes I see now all happen after a screenshot test. Eg. https://github.com/flutter/flutter/runs/372639367

**Comment by Piinks** [comment] 2020-01-10 20:55
I think this is another case: https://cirrus-ci.com/task/6466161462214656

**Comment by Hixie** [comment] 2020-02-26 00:25
If you're seeing this unrelated to screenshot tests please update the bug, that is useful information.

**Comment by Hixie** [comment] 2020-02-26 00:26
@yjbanov @ferhatb is this on your radar?

**Comment by yjbanov** [comment] 2020-02-27 18:30
It definitely is. I'm trying to free up time to look into this. Two things that make it hard to track down:

- The log messages seem to be red herrings as all the files in question are there. The error messages are coming from our dependencies, so it will take some time to investigate.
- This never manifests locally, but only on Cirrus.

**Comment by Piinks** [comment] 2020-02-27 18:41
Looking on chat channels for mentions of this bug that may not have been reported here.
Found one so far:
https://cirrus-ci.com/task/6467030329065472

**Comment by dnfield** [comment] 2020-02-27 18:42
It seems likely to me that this is an issue of a process taking longer to run on a slower machine than it does locally.

I wonder if it'd be worth setting up a slow-ish machine somewhere to stress test these things.

**Comment by yjbanov** [comment] 2020-02-28 20:59
Here's a copy of my investigation from https://github.com/flutter/flutter/issues/49435#issuecomment-592724480:

> Ran it again 8 shards 30 times each (that's 240 shard runs total). [All green](https://github.com/flutter/flutter/pull/51642/checks?check_run_id=475669227). I also checked the last 10-ish Cirrus master build failures. None of them were from web tests.
>
> I am making the conclusion that this is fixed now. It could have been fixed by one of the Dart rolls or one of `flutter update-package --force-upgrade`s (since the error is coming from a dependency).

@Piinks 

> Looking on chat channels for mentions of this bug that may not have been reported here.
> Found one so far:
> https://cirrus-ci.com/task/6467030329065472

Given that this Cirrus build is 3 weeks old, the issue might have gone since then.

Closing based on the above, but let's reopen is this happens again.

**Comment by Piinks** [comment] 2020-02-28 22:02
Should we be able to re-enable the web golden file tests then?

**Comment by Piinks** [comment] 2020-02-29 01:01
So with multiple commits and test runs while prepping #51666, this reproduced once on one shard: https://cirrus-ci.com/task/6066690064646144?command=main#L1244

**Comment by Piinks** [comment] 2020-02-29 01:08
The flake still does not appear to be related to a golden file test, as this flake has persisted with or without golden file tests.

```
 Failed to load "/tmp/flutter sdk/packages/flutter/test/widgets/icon_data_test.dart": Unknown error loading http://localhost:41983/packages/collection/src/canonicalized_map.ddc.js
```
`icon_data_test.dart` does not contain a golden file test. 

I think this may just be a very intermittent flake. I'd still like to re-enable the golden file tests, as they all worked as intended when turned back on. We even found a bug with them back in place (https://github.com/flutter/flutter/issues/51675).

**Comment by chingjun** [comment] 2020-02-29 01:14
The flakes appear when there is a golden test that runs before the test in the same invocation. In this case, `bottom_navigation_bar_test.dart`, which contains the golden test, is executed before `icon_data_test.dart`. So it could still be the same issue, unfortunately.

▌00:22:58▐ RUNNING: cd packages/flutter; ../../bin/flutter test --concurrency=1 -v --platform=chrome test/widgets/slivers_block_test.dart test/widgets/clamp_overscrolls_test.dart test/widgets/ensure_visible_test.dart test/material/page_selector_test.dart test/widgets/physical_model_test.dart **test/material/bottom_navigation_bar_test.dart** test/widgets/implicit_animations_test.dart test/widgets/scroll_physics_test.dart **test/widgets/icon_data_test.dart** test/gestures/locking_test.dart test/widgets/scrollbar_test.dart test/material/reorderable_list_test.dart test/rendering/flex_overflow_test.dart test/widgets/intrinsic_width_test.dart test/widgets/page_view_test.dart test/foundation/diagnostics_test.dart test/widgets/performance_overlay_test.dart test/scheduler/lifecycle_test.dart test/painting/colors_test.dart test/widgets/scroll_controller_test.dart

**Comment by Piinks** [comment] 2020-02-29 01:42
> The flakes appear when there is a golden test that runs before the test in the same invocation. 

@chingjun That does not appear to be the case.  See repro in: https://cirrus-ci.com/task/5690696585707520?command=main#L1644

There are no golden file tests in this invocation.

Invocation:
▌09:35:24▐ RUNNING: cd packages/flutter; ../../bin/flutter test --concurrency=1 -v --platform=chrome test/material/tabbed_scrollview_warp_test.dart test/gestures/double_tap_test.dart test/rendering/independent_layout_test.dart test/widgets/slivers_appbar_scrolling_test.dart test/material/slider_test.dart test/widgets/sliver_prototype_item_extent_test.dart test/widgets/binding_attach_root_widget_test.dart test/widgets/pageable_list_test.dart test/cupertino/action_sheet_test.dart test/foundation/bit_field_test.dart **test/widgets/banner_test.dart [FLAKE]** test/widgets/text_formatter_test.dart test/painting/paint_image_test.dart test/widgets/flex_test.dart test/material/button_bar_theme_test.dart test/material/time_picker_test.dart test/widgets/fade_transition_test.dart test/widgets/list_view_fling_test.dart test/widgets/text_selection_test.dart test/material/stepper_test.dart

**Comment by yjbanov** [comment] 2020-03-02 18:56
We might be hitting https://github.com/dart-lang/test/issues/1104 where the test runner points at an incorrect test when it's failing.

I closed this issue because _currently_ the tests do not exhibit the issue described above. I didn't realize that this issue is a request to enable golden tests. I'll update the description.

**Closed** 2020-03-18 22:11 UTC
Labels: a: tests, team: flakes, ☸ platform-web
