### ISSUE TITLE
Small memory iOS device memory usage is too much to cause crash

### ISSUE THREAD

**Issue by xuexin** [flutter/flutter#20521] opened 2018-08-13 09:35 UTC
## Demo
https://github.com/xuexin/flutter_memory_issue

## Steps to Reproduce

1. run the demo on low memory iOS device(not simulator)
2. wait for crash

## Code

```dart
import 'package:flutter/material.dart';

void main() => runApp(new MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      theme: new ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: new Scaffold(
        appBar: new AppBar(
          title: new Text("gif"),
        ),
        body: new Center(
          child: new Image.asset('gif/plane.gif'),
        ),
      )
    );
  }
}
```
plane.gif is a big gif picture(1.7M)
airplane.gif is a small gif picture(99K)

#### small gif:
<img width="838" alt="small_me279ch a" src="https://user-images.githubusercontent.com/6419351/44023696-b7b21f2a-9f1d-11e8-910a-8cc02e06e573.png">

#### big gif:
<img width="849" alt="big_me279ch a" src="https://user-images.githubusercontent.com/6419351/44023795-fef58566-9f1d-11e8-9f94-43d8859b62a5.png">
It will crash very soonly.

#### big gif:
<img width="856" alt="big_mp2g2ch a" src="https://user-images.githubusercontent.com/6419351/44023807-0a1362ce-9f1e-11e8-94c2-0b2fb68ad540.png">

Seems that gif's data will recycle after gif playing one time.
But small memory device(like ME279CH/A) has not enough memory, and it cause crash.

## version

```
[✓] Flutter (Channel beta, v0.5.1, on Mac OS X 10.13.6 17G65, locale zh-Hans-CN)
    • Flutter version 0.5.1 at /Users/liaoyuhao/flutter
    • Framework revision c7ea3ca377 (3 months ago), 2018-05-29 21:07:33 +0200
    • Engine revision 1ed25ca7b7
    • Dart version 2.0.0-dev.58.0.flutter-f981f09760

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/liaoyuhao/sdk
    • Android NDK at /Users/liaoyuhao/sdk/ndk-bundle
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = /Users/liaoyuhao/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.0

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 27.1.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2017.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 23.2.2
    • Dart plugin version 173.4127.31

[!] VS Code (version 1.25.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

```

**Comment by xuexin** [comment] 2018-08-13 09:38
https://github.com/flutter/flutter/issues/19754
I think they are similar issues.

**Comment by zoechi** [comment] 2018-08-22 19:54
Would be good to know if this is the same in `master` channel. `beta` is unfortunately a bit outdated already.

**Comment by adriancmurray** [comment] 2018-10-22 16:54
@zoechi is this still an issue on beta vs master? Because while displaying a gif I can feel my device getting physically warm. Once the gif is removed from the tree then all is fine. I’m on mobile right now so I don’t have any actual data to present here but feel like it’s a related issue.

**Comment by zoechi** [comment] 2018-10-22 17:33
@adriancmurray the issue is still open, so it's likely not yet fixed.
Your issue looks like a different issue to me. #18787 might be somewhat related.

**Comment by xuexin** [comment] 2018-11-01 03:02
This issue still exists.
I updated the demo, so that it should be happened easier.

**Comment by NavWin** [comment] 2019-01-24 11:17
I also have a similar issue on my 16MB iPhone 6. If you open a few applications then your own application gets offloaded. If you click on it then it effectively gets restarted from scratch (not restored). This is probably the natural iPhone behaviour in that iOS. Anyway the real problem happens when at some point some flutter runtime file gets corrupted and the application will start for a brief second and then shutdown. The only way to make it work again is to reload the application from the MacBook (restarting the phone does not fix the problem). So it seems that Flutter might sometimes corrupt runtime files during a memory related shutdown. Has anyone else experienced this in iOS and Flutter? Obviously, as this is iPhone it is virtually impossible to access crash related information. The best I have come up with so far is to utilise the system Clipboard to track a startup crash. Since adding this code I am  still waiting for the app to crash permanently again!

**Comment by voyagewu** [comment] 2019-04-08 02:12
I have this issue in my App too, load dynamic **different** Image to Image Widget, and the memory will grow, and the memory becomes larger and larger. Seems like GC is not clear completely. Because after the GC, the memory will stop grows for a while, and starts grow again. This issue in V1.1.8, but available in V1.21 and V1.3.8.

**Comment by DyaryRaoof** [comment] 2019-10-12 13:50
any solution ?

**Comment by darshankawar** [comment] 2020-10-01 13:24
@xuexin 
Is this still a valid issue ?
I don't have a low memory iOS device to replicate the issue. It'll be great if you could confirm on latest Flutter and get back.
Thanks.

**Comment by pedromassangocode** [comment] 2020-10-23 10:52
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2020-10-23 10:52 UTC
Labels: P4, e: device-specific, engine, platform-ios, severe: performance
