### ISSUE TITLE
When I change the physical of Pageview in the Listener of Pageview, it will cause PageView to die.

### ISSUE THREAD

**Issue by LebenNNA** [flutter/flutter#28096] opened 2019-02-18 09:05 UTC
When I change the physical of `Pageview` in the Listener of `Pageview`, it will cause `PageView` to die.

## Codes

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: PageViewTestPage(),
    );
  }
}

class PageViewTestPage extends StatefulWidget {
  @override
  _PageViewTestPageState createState() => _PageViewTestPageState();
}

class _PageViewTestPageState extends State<PageViewTestPage> {
  PageController _controller;
  bool _locked;
  List itemLists = [
    Colors.red[100],
    Colors.red[200],
    Colors.red[300],
    Colors.red[400],
    Colors.red[500],
  ];

  void onPageChanged(int index) {}

  void scrollListener() {
    print(_controller.offset);
    double _currentOffset = _controller.offset;
    double _width = MediaQuery.of(context).size.width;
    if (_currentOffset > _controller.page * _width) {
      setState(() {
        _locked = true;
      });
    }
  }

  Widget _itemBuilder(context, int index) {
    return Container(
      color: itemLists[index],
    );
  }

  @override
  void initState() {
    _controller = PageController()..addListener(scrollListener);
    _locked = false;
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    print('---------locked:$_locked');
    return PageView.builder(
      controller: _controller,
      onPageChanged: onPageChanged,
      itemCount: 5,
      physics: _locked ? const NeverScrollableScrollPhysics() : null,
      itemBuilder: _itemBuilder,
    );
  }
}
```
```
[✓] Flutter (Channel master, v1.2.1-pre.196, on Mac OS X 10.14.2 18C54, locale
    zh-Hans-CN)
    • Flutter version 1.2.1-pre.196 at /Users/h3d-nna/Documents/flutter
    • Framework revision da5c97c3ef (4 days ago), 2019-02-14 02:47:29 -0500
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/h3d-nna/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.3.3
    • Dart plugin version 182.5124
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.31.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.23.0
```

**Comment by zoechi** [comment] 2019-02-18 09:13
Can you please make the code a complete runnable reproduction (incl `main() {...}`)?

**Comment by LebenNNA** [comment] 2019-02-18 09:44
@zoechi I have completed the code update

**Comment by zoechi** [comment] 2019-02-18 10:10
It stops rather randomly at different times when scrolling through the pages.
Once it stopped at the transition from the 1st to the 2nd page, then I could scroll to the 4th page before it stuck.

```
[✓] Flutter (Channel master, v1.2.2-pre.21, on Mac OS X 10.14.3 18D42, locale en-AT)
```

**Comment by LebenNNA** [comment] 2019-02-18 10:58
What I want to know is, what caused the page to get stuck, how should I solve it? @ @zoechi

**Comment by tango5614** [comment] 2019-06-07 12:18
I have made a PR about this issue.Would you please check it out? #34039 @zoechi

**Comment by chunhtai** [comment] 2019-07-16 22:48
Is the question why _currentOffset > _controller.page * _width ever be true before reaching to the end?
it will evaluate to true due to floating point precision error. This depends on devices and different scroll offset. 

Once the _locked set to true, the physics will be set to NeverScrollableScrollPhysics and that will prevent user or system to scroll the page. May I know what is the use case of this app?

**Comment by iapicca** [comment] 2020-07-29 10:16
Hi @LebenNNA 
testing the code below with the latest master

<details><summary>code</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(
      const MyApp(
        key: Key('app'),
      ),
    );

class MyApp extends StatelessWidget {
  const MyApp({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) => MaterialApp(
        home: const MyHomePage(
          key: Key('home'),
        ),
      );
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key key}) : super(key: key);

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  bool _never = false;

  @override
  Widget build(BuildContext context) => Scaffold(
        body: Center(
            child: //_never ?
                PageView.builder(
          itemBuilder: (BuildContext context, int index) => FlutterLogo(),
          physics: _never ? ScrollPhysics() : NeverScrollableScrollPhysics(),
        )),
        floatingActionButton: FloatingActionButton(
          onPressed: () => setState(() => _never = !_never),
        ),
      );
}

```

</details>


<details><summary>doctor</summary>

```console
[✓] Flutter (Channel master, 1.21.0-6.0.pre.90, on Mac OS X 10.15.5 19F101, locale en-GB)
    • Flutter version 1.21.0-6.0.pre.90 at /Users/nevercode/development/flutter_master
    • Framework revision 531ee9452a (4 hours ago), 2020-07-29 02:26:03 -0400
    • Engine revision 1ba310017c
    • Dart version 2.10.0 (build 2.10.0-1.0.dev 24c7666def)


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/nevercode/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[✓] Connected device (4 available)
    • Pixel 3a (mobile) • 965AY0WP5C • android-arm64  • Android 10 (API 29)
    • macOS (desktop)   • macos      • darwin-x64     • Mac OS X 10.15.5 19F101
    • Web Server (web)  • web-server • web-javascript • Flutter Tools
    • Chrome (web)      • chrome     • web-javascript • Google Chrome 84.0.4147.105

• No issues found!
```

</details>

the issue seems to be solved, I feel safe to close this issue,
if you disagree please write in the comments and I will reopen it. 
Thank you

**Closed by iapicca** 2020-07-29 10:16 UTC
Labels: P4, framework
