### ISSUE TITLE
App freeze when an overlay is displayed and iOS user do a swipe 

### ISSUE THREAD

**Issue by EArminjon** [flutter/flutter#116267] opened 2022-11-30 10:23 UTC
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. Click on the visible button to push a new route
3. Click on the visible button to push an overlay
4. Swipe from the left of the screen to the right
5. release your finger after the middle of the screen.
6. See the issue.

**Expected results:** 
I would see my overlay removed (pop) and the page too.

**Actual results:** 
The overlay is well disposed but the page freeze. User on iOS cannot swipe but can still interact with the button in the orange page.

<img width="412" alt="Capture d’écran 2022-11-30 à 11 18 17" src="https://user-images.githubusercontent.com/37028599/204770176-af79dc8a-67c8-4725-975e-2a3356891b80.png">

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const App());
}

class Home extends StatelessWidget {
  const Home({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: ElevatedButton(
          onPressed: () {
            Navigator.push(
              context,
              MaterialPageRoute<dynamic>(
                settings: const RouteSettings(name: '/page'),
                builder: (BuildContext context) => const Page(),
              ),
            );
          },
          child: const Text("Push route"),
        ),
      ),
    );
  }
}

class Page extends StatefulWidget {
  const Page({super.key});

  @override
  State<Page> createState() => _Page();
}

class _Page extends State<Page> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.orange,
      body: Builder(builder: (context) {
        return Center(
          child: ElevatedButton(
            onPressed: () {
              Navigator.of(context, rootNavigator: false).push(
                FlushbarRoute(),
              );
            },
            child: const Text("Launch flushbar"),
          ),
        );
      }),
    );
  }
}

class FlushbarRoute<T> extends OverlayRoute<T> {
  @override
  Iterable<OverlayEntry> createOverlayEntries() {
    return <OverlayEntry>[
      OverlayEntry(
        builder: (BuildContext context) => Align(
          alignment: Alignment.topCenter,
          child: Container(
            margin: const EdgeInsets.only(top: 50),
            height: 100,
            width: double.maxFinite,
            color: Colors.red,
          ),
        ),
      ),
    ];
  }
}

class App extends StatelessWidget {
  const App({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: Home(),
    );
  }
}
```

</details>

<details>
  <summary>Logs</summary>

```
No logs
```

```
No warnings
```

```
[✓] Flutter (Channel stable, 3.3.4, on macOS 12.6.1 21G217 darwin-arm, locale fr-FR)
    • Flutter version 3.3.4 on channel stable at /Users/earminjon/fvm/versions/3.3.4
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision eb6d86ee27 (7 weeks ago), 2022-10-04 22:31:45 -0700
    • Engine revision c08d7d5efc
    • Dart version 2.18.2
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/earminjon/Library/Android/Sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = /Users/earminjon/Library/Android/Sdk
    • Java binary at: /Users/earminjon/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/213.7172.25.2113.9123335/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Users/earminjon/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/213.7172.25.2113.9123335/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.2.3)
    • IntelliJ at /Users/earminjon/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 71.0.5
    • Dart plugin version 222.4345.14

[✓] IntelliJ IDEA Ultimate Edition (version 2022.2.3)
    • IntelliJ at /Users/earminjon/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/222.4345.14/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (4 available)
    • iPhone de Enguerrand (mobile) • 037a70ff3ad9e7787722c6c239f94d2aadceb764 • ios            • iOS 15.7 19H12
    • macOS (desktop)               • macos                                    • darwin-arm64   • macOS 12.6.1 21G217 darwin-arm

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

https://user-images.githubusercontent.com/37028599/204770917-8b06c064-0953-4603-8b56-cc0beb704df0.mp4

**Comment by danagbemava-nc** [comment] 2022-12-01 06:52
Closing this as a duplicate of https://github.com/flutter/flutter/issues/33875. 

Kindly follow up in the issue linked above for updates. 

Thank you

**Closed by danagbemava-nc** 2022-12-01 06:52 UTC
Labels: in triage
