### ISSUE TITLE
requestData() custom command doesn't work with gherkin in FlutterDriver

### ISSUE THREAD

**Issue by sohitEngg** [flutter/flutter#59047] opened 2020-06-09 04:24 UTC
I'm using flutter_gherkin for BDD test on my flutter Application. Recently I have a requirement in which I need to clear cache(SharePreference) for some scenarios so I have chosen to send custom command to my application. Here below is the code:

`
await world.driver.requestData("deleteChache");
`

and I am expecting the command in the main.dart in test environment as per below:

`void main() {
  enableFlutterDriverExtension(handler: (message) async {
    stdout.write('##message received $message');
    await app.deleteCache();
    return null;
  });
  app.main();
}
`

I am able to see the logs for sending part but there is no logs found for receiving part, looks like flutter driver is unable send the command to my App. Am I missing anything, is this because of gherkin environment?

**Comment by TahaTesser** [comment] 2020-06-09 14:36
Hi @sohitEngg 
From what I can see, the issue is related to a 3rd party plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/jonsamwell/flutter_gherkin/issues).
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments, possibly providing a minimal reproducible code sample that does not use 3rd party plugins, and I will reopen it.
Thank you

**Closed by TahaTesser** 2020-06-09 14:36 UTC
