### ISSUE TITLE
[web]: UI freezes and crash the iOS browser

### ISSUE THREAD

**Issue by deepak786** [flutter/flutter#109018] opened 2022-08-05 03:52 UTC
When a video file is being uploaded to Server (AWS S3), Flutter UI Freezes.
As a result the iOS Safari browser crashes. See https://cdn.discordapp.com/attachments/530797119389564939/1004659351904079882/Screen_Shot_2022-08-04_at_1.27.03_PM.png

The UI also freezes on Desktop Safari browser but desktop handles this and goes back to normal in some time.

Here is the snippet that is used to upload the video file to AWS S3 with the http package.

```
      XFile file = videoFile;
      Uint8List bytes = await file.readAsBytes();

      final uri = Uri.parse(signedUrl);
      final response = await http.put(uri, body: bytes, headers: {
        'content-type': mimeType,
      });
      debugPrint('AWS:: response: ${response.statusCode}');
```

On the iOS Safari browser, the video file size being uploaded is ~(20 - 30) MB.

I have already tried the `compute` to the upload but the result is the same.

Ref: https://stackoverflow.com/questions/64481869/flutter-uploading-a-video-through-dio-package-on-isolate

**Comment by danagbemava-nc** [comment] 2022-08-05 08:53
Hi @deepak786,

Can you please provide your `flutter doctor -v` and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?

Thank you

**Comment by deepak786** [comment] 2022-08-05 18:48
here is the sample code:
https://github.com/deepak786/file_upload_sample

1. Run the sample on web.
2. Pick a mp4 video file of size between 20 - 50 MB.
3. You will see that when the API is called to upload the file, UI freeze for some seconds depending on the size of the video you choose.

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.3.1 21E258 darwin-x64, locale
    en-US)
    • Flutter version 3.0.5 at /Library/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (3 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/appleapple/Library/Android/sdk
    • Platform android-33, build-tools 30.0.3
    • ANDROID_HOME = /Users/appleapple/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] IntelliJ IDEA Community Edition (version 2019.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.70.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.46.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.3.1 21E258 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 103.0.5060.134

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by danagbemava-nc** [comment] 2022-08-08 07:42
Hi @deepak786, what device are you experiencing this issue on? 

I tested this on my iPhone XS and it works as it does on desktop. I am not able to reproduce the browser crashing.

<details>
<summary>video</summary>

https://user-images.githubusercontent.com/88313112/183365657-d411c602-1358-479f-ba57-586f9d0274c6.MP4
</details>

**Comment by deepak786** [comment] 2022-08-08 07:52
@danagbemava-nc I experienced the crash issue on iPhone 12.

Besides the crash thing, you will see that the UI freezes for some time depending on the video size. There is a loader added when the uploading is in progress. The loader animation stops which indicates the UI is frozen.

**Comment by deepak786** [comment] 2022-08-08 07:54
In your video demo, you can see that at 00:19s the progress bar animation is stopped.

**Comment by danagbemava-nc** [comment] 2022-08-09 07:03
Hi @deepak786, the video I initially chose was 37.5mb, but it looks like there is some compression being applied, which is why the file appears to be 7mb on your end. 

> In your video demo, you can see that at 00:19s the progress bar animation is stopped.

Yes, I'm aware of this. What I meant by "it works as it does on desktop" is, as you reported in your initial post, the app recovers and resumes playing the animation, which is what I see on my mobile device as well. 

I also tried uploading a 200mb file, but I think it was compressed to about 50mb???(I'm not certain of this). From what I see in the Safari debugger, about 51mb of data is transferred when I upload the 200mb video. Can you check if you're seeing any files around that size? 

One thing I've also noticed, after the upload, the browser seems to refresh the page. Is this something you're experiencing on your end? 

Also, is your app running in release mode or debug mode?

<details>
<summary>safari screenshot</summary>

<img width="994" alt="Screenshot 2022-08-09 at 07 00 44" src="https://user-images.githubusercontent.com/88313112/183585271-a901b967-0cab-4609-aa4e-af2df189dbe3.png">

</details>

**Comment by deepak786** [comment] 2022-08-09 07:57
@danagbemava-nc I created the sample by creating an account on upload.io. But in actual I'm using S3 bucket. In the trial of the account from upload.io, there is a limit. You can upload a file with max size of 50 MB. I don't have any idea about upload.io is compressing the file.

My app is in release mode.

> One thing I've also noticed, after the upload, the browser seems to refresh the page. Is this something you're experiencing on your end?
Did the browser show a message like "The web page was reloaded because a problem occurred"?

**Comment by danagbemava-nc** [comment] 2022-08-09 13:38
> How can we avoid this animation/UI freeze?

This might probably be related to https://github.com/flutter/flutter/issues/17793

> @danagbemava-nc I created the sample by creating an account on upload.io. But in actual I'm using S3 bucket. In the trial of the account from upload.io, there is a limit. You can upload a file with max size of 50 MB. I don't have any idea about upload.io is compressing the file.

My bad, there was a bit of a miscommunication. iOS is the one compressing the videos that I select

> Did the browser show a message like "The web page was reloaded because a problem occurred"?

No, I do not see this error. Is your site hosted somewhere that I can test to see if I can repro with it?

**Comment by deepak786** [comment] 2022-08-10 04:26
> This might probably be related to https://github.com/flutter/flutter/issues/17793

So the UI Freeze is because of the CircularProgressIndicator?.

> Did the browser show a message like "The web page was reloaded because a problem occurred"?

> No, I do not see this error. Is your site hosted somewhere that I can test to see if I can repro with it?

I tested code sample on ocr-test-4f3df.web.app. I saw the browser is reloaded but there is no error "The web page was reloaded because a problem occurred".
But this is the issue actually (Browser reload) because it could not handle the large file.

**Comment by deepak786** [comment] 2022-08-10 04:38
> This might probably be related to https://github.com/flutter/flutter/issues/17793

> So the UI Freeze is because of the CircularProgressIndicator?

I tested the code sample by removing the CircularProgressIndicator but the UI is still freezing.

**Comment by danagbemava-nc** [comment] 2022-08-10 08:07
> But this is the issue actually (Browser reload) because it could not handle the large file.

That makes sense

It would appear that there are some current limitations with handling these kinds of tasks on the web at the moment(see https://github.com/flutter/flutter/issues/33577), can you check https://github.com/flutter/flutter/issues/33577#issuecomment-1196538811 to see if it helps?

**Comment by deepak786** [comment] 2022-08-15 08:32
@danagbemava-nc Thanks for this information. 
It seems that [`isolated_worker`](https://pub.dev/packages/isolated_worker) will solve the issue. 
It is working but I still have to test the changes in production.

**Closed** 2022-09-06 06:33 UTC
Labels: waiting for customer response, in triage
