### ISSUE TITLE
Pixel rounding errors in compositor

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#9276] opened 2017-04-06 23:19 UTC
## Steps to Reproduce

1. Run the following app: https://gist.github.com/tvolkert/1458377c6d4bfb582e14bb284083c1b2
2. In the drawer, select "Show Breakage" to set the `Material.debugEnablePhysicalModel` value to `true`.
3. Look closely at the text rendering within the tab contents

## Results

The rendering of the contents of the tab seem to have pixel rounding errors.  See the screenshots [without raster cache checkerboard](https://cloud.githubusercontent.com/assets/15253456/24776927/e33ed5aa-1ad7-11e7-9f08-c8d168720aec.png) and [with raster cache checkerboard](https://cloud.githubusercontent.com/assets/15253456/24776940/03295b2e-1ad8-11e7-8485-7c50bf1db682.png).

## Analysis

When you select "Checkerboard Raster Cache Images" in the drawer, the fact that the checkerboard patterns show artifacts as well indicates that this is a raster cache issue -- and that the `Material.debugEnablePhysicalModel` flag is merely tickling a code path into causing the raster cache to show this underlying issue.

**Comment by tvolkert** [comment] 2017-04-06 23:19
@chinmaygarde @jason-simmons

**Comment by tvolkert** [comment] 2017-04-07 06:21
Two extra notes:
  1. This was witnessed on a Nexus 5x physical device.
  2. FYI, the horizontal overscroll issue seen in the sample app is #8523

**Comment by eseidelGoogle** [comment] 2017-04-11 22:06
Since this is physical-model only, punting to M3, will be a blocker for turning physical model back on.

**Comment by tvolkert** [comment] 2017-04-27 22:12
Turns out it's not physical-model only, so bumping back to M2 (at least for now).  It looks like it's a bug in the compositor, and the physical-model toggle in the repro app just tickled the code path.

I just verified in an internal Google app that it happens with physical model turned off, and I can make the problem go away by turning off compositing (returning `nullptr` from `RasterCache::GetPrerolledImage`).

![flutter_no_compositing](https://cloud.githubusercontent.com/assets/15253456/25506503/d6537d2a-2b5b-11e7-8b72-8a4fba8e7370.png)

![flutter_with_compositing](https://cloud.githubusercontent.com/assets/15253456/25506507/d9f0d338-2b5b-11e7-96e9-674301267a1b.png)

**Comment by eseidelGoogle** [comment] 2017-04-28 16:30
@chinmaygarde is likely the right person to triage.

**Comment by chinmaygarde** [comment] 2017-04-28 22:31
I am not able to reproduce this issue on a Nexus 5X. I was attempting to run the reduced test case you provided.

**Comment by tvolkert** [comment] 2017-04-28 22:43
I pointed @chinmaygarde to the internal sample that exhibits this failure.

**Comment by eseidelGoogle** [comment] 2017-05-02 22:04
Any updates @chinmaygarde?

**Comment by eseidelGoogle** [comment] 2017-05-02 22:06
I don't believe this blocks the M2 event.  It's definitely very bad from those images, and we need to repro locally.  FYI @abarth

**Comment by chinmaygarde** [comment] 2017-05-02 22:48
@tvolkert pointed me to the internal sample that exhibited this behavior on Friday. Unfortunately, I was not able to get the environment setup on my workstation to access the same (and gave up halfway between trying to create a reduced test case from the code therein).

However, https://github.com/flutter/flutter/issues/8524 is caused by the same underlying issue and is easily reproducible (I am using a Pixel XL). IMO, focussing attention on that issue is a better idea.

**Comment by tvolkert** [comment] 2017-05-22 18:40
Any updates @chinmaygarde?

**Comment by chinmaygarde** [comment] 2017-05-23 19:24
The underlying issue is a duplicate of https://github.com/flutter/flutter/issues/8524. I am reworking how the raster cache handles all transforms while generating the snapshot. It is a slightly more involved change that I had initially anticipated. Will keep this ticket update with progress.

**Comment by chinmaygarde** [comment] 2017-05-23 19:51
Just so all these related tickets are linked somehow, https://github.com/flutter/flutter/issues/10144#issuecomment-303506695 is also affected by my changes.

**Comment by chinmaygarde** [comment] 2017-05-31 19:18
Update: https://github.com/flutter/engine/pull/3717 addresses this issue. Unfortunately, I am still dealing with the edge cases.

**Comment by chinmaygarde** [comment] 2017-06-05 22:57
The fix for this issue has landed in https://github.com/flutter/engine/pull/3717.

**Comment by tvolkert** [comment] 2017-06-22 18:39
It looks like this was never fixed in customer six's app (even with flutter/engine#3717) -- against Flutter version `b231006ce7efd0dcf5390e3b9e0d11c3c5174de9`, we're still seeing the following on a Nexus 5x:

![flutter_01](https://user-images.githubusercontent.com/15253456/27448280-1f1f2eec-5739-11e7-920a-bdb3015aa339.png)

**Comment by tvolkert** [comment] 2017-06-22 18:52
Reproduced in a test case app (a modification of the original test case app), located at https://gist.github.com/tvolkert/b55bfc2eebc713cea9ae324bcbfec851

![flutter_01](https://user-images.githubusercontent.com/15253456/27450667-44a513a4-5741-11e7-9922-27f82dc85bfd.png)

**Comment by Hixie** [comment] 2017-06-27 20:52
We do not expect to look at this in July. Please let us know if this becomes a higher priority.

**Comment by tvolkert** [comment] 2017-07-06 19:05
Internal change 161074170 highlights customer six's frustration with this bug, but I think our plan to address this in August still stands.

**Comment by collinjackson** [comment] 2017-07-12 02:08
I have been able to repro the issue on a non-Pixel device, which is helpful since we don't have a lot of Pixel devices around.

Here is a test case that I made:

```
    import 'package:flutter/material.dart';
    import 'package:flutter/rendering.dart';
    
    void main() {
      runApp(new MaterialApp(
        checkerboardRasterCacheImages: true,
        home: new MyHomePage(),
      ));
    }
    
    class MyHomePage extends StatefulWidget {
      @override
      _MyHomePageState createState() => new _MyHomePageState();
    }
    
    class _MyHomePageState extends State<MyHomePage> {
      @override
      Widget build(BuildContext context) {
        return new Scaffold(
          body: new Column(
            children: <Widget>[
              new Container(
                color: Colors.blue,
                height: 300.0,
                child: new GestureDetector(
                  onTap: () {
                    setState(() {});
                  },
                ),
              ),
              new Container(
                height: 0.0,
                child: new Viewport(
                  offset: new ViewportOffset.zero(),
                  axisDirection: AxisDirection.right,
                  slivers: <Widget>[],
                ),
              ),
              new Expanded(
                child: new Container(
                  child: new Material(
                    child: new Center(
                      child: new Material(
                        color: Colors.purple,
                        child: new Container(
                          width: 300.0,
                          height: 20.0,
                          child: new Text(' '),
                        ),
                      ),
                    ),
                  ),
                ),
              ),
            ],
          ),
        );
      }
    }
```

It looks like this:

![image](https://user-images.githubusercontent.com/394889/28098598-04ba18e0-666c-11e7-94e9-aeacbb30a533.png)

To trigger the bug, tap the blue area twice. You will see a checkerboard pattern appear and the edge of the purple box is jagged.

![image](https://user-images.githubusercontent.com/394889/28098605-0f6de12c-666c-11e7-8e7f-4751c25af307.png)

This test case is specific to the Nexus 5X. Devices with other screen sizes may require other values.

**Comment by eseidelGoogle** [comment] 2017-07-13 02:11
Our current understanding is we need to fix this by end of next week.  If @chinmaygarde doesn't have time, that likely means @jason-simmons or @cbracken?

**Comment by eseidelGoogle** [comment] 2017-07-17 17:11
@chinmaygarde just told me in person he worked on this Friday and will continue today.

**Closed** 2017-07-18 06:42 UTC
Labels: customer critical, customer: posse (eap), customer: six (g3), prod: engine
