### ISSUE TITLE
Camera opens in Selfie mode

### ISSUE THREAD

**Issue by abdulmanafpfassal** [flutter/flutter#97937] opened 2022-02-07 07:55 UTC
The Camera opens in Selfe mode when "preferredCameraDevice = CameraDevice.rear" is given.

**Comment by danagbemava-nc** [comment] 2022-02-07 12:55
Hi @abdulmanafpfassal 
This is intended behavior. See this from `image_picker` docs on `preferredCameraDevice`

```
  /// Use `preferredCameraDevice` to specify the camera to use when the `source` is [ImageSource.camera].
  /// The `preferredCameraDevice` is ignored when `source` is [ImageSource.gallery]. It is also ignored if the chosen camera is not supported on the device.
  /// Defaults to [CameraDevice.rear]. Note that Android has no documented parameter for an intent to specify if
  /// the front or rear camera should be opened, this function is not guaranteed
  /// to work on an Android device.
```

https://github.com/flutter/plugins/blob/a10ac2e0d8a8cd878fd0d0a54aa9a87c44c7d7c5/packages/image_picker/image_picker/lib/image_picker.dart#L49

The above change was added in the documentation as part of this PR: https://github.com/flutter/plugins/pull/3037

With this, I am closing this as not an issue with the plugin, but a limitation of Android itself.

**Closed by danagbemava-nc** 2022-02-07 12:55 UTC
Labels: in triage
