### ISSUE TITLE
firebase_admob it is possible to close ad with back button before countdown ends

### ISSUE THREAD

**Issue by lesnitsky** [flutter/flutter#27206] opened 2019-01-28 23:16 UTC
It is possible to close interstitial video ad with back button even before timer ends

**Comment by lesnitsky** [comment] 2019-01-28 23:17
this is probably easy to fix, but I'm not sure if it is _expected_ to work this way, let me know

**Comment by kroikie** [comment] 2019-10-13 19:50
@lesnitsky

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1186. Any further collaboration will be done there.

**Comment by kroikie** [comment] 2019-10-14 17:51
Since `firebase_admob` issues require work on the Flutter side as well as the plugin side these issues will remain open here as well until resolved.

**Comment by iapicca** [comment] 2019-10-24 12:09
Hi @lesnitsky
If you are still experiencing this issue 
with the latest version of Flutter and FlutterFire plugin
can you please provide your updated  `flutter doctor -v`
and your `flutter run --verbose`/`flutter build --verbose` ?
Also, to better address the issue, would be helpful
if you could post a self contained app on github
or the steps to reproduce it.
Thank you

**Comment by lesnitsky** [comment] 2019-10-24 12:13
@iapicca I'm confused.. Where should we continue this conversation? Here or FirebaseExtended/flutterfire#1186?

**Comment by iapicca** [comment] 2020-02-12 12:44
HI @lesnitsky 
for my understanding since admob
heavily relies on webview it's good practice to keep the issue on flutter as well.

Are you still experiencing this issue with the latest stable and latest version of admob?
thank you

**Comment by lesnitsky** [comment] 2020-02-12 14:00
The issue is still valid
Back button on android closes video ad before timer ends

```
[✓] Flutter (Channel master, v1.15.4-pre.22, on Mac OS X 10.14.6 18G3020, locale en-BY)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.42.0)
[✓] Connected device (4 available)

• No issues found!
```

```yaml
# pubspec.yaml
dependencies:
  flutter:
    sdk: flutter
  firebase_admob: ^0.9.0+10
```

```dart
import 'package:firebase_admob/firebase_admob.dart';
import 'package:flutter/material.dart';

class Example extends StatefulWidget {
  @override
  _ExampleState createState() => _ExampleState();
}

class _ExampleState extends State<Example> {
  @override
  void initState() {
    // interstiital test video ad id
    InterstitialAd(adUnitId: 'ca-app-pub-3940256099942544/8691691433')
      ..load()
      ..show();

    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Container();
  }
}
```

**Comment by iapicca** [comment] 2020-02-13 08:04
thank you @lesnitsky

**Comment by markus-skidrow** [comment] 2020-03-26 11:53
do anyone resolved this problem? i have the same problem

**Comment by kazyamof** [comment] 2020-05-28 00:04
> do anyone resolved this problem? i have the same problem

Same here. What is the purpose of an interstitial ad if the user can simply skip it? Sad...

**Comment by talent-apps** [comment] 2020-05-28 06:40
@kazyamof this bug is crucial for monetizing Flutter apps, yet it gets no attention.
I suggest up voting it so it will be prioritized by the flutter team.

**Comment by stuartmorgan** [comment] 2021-05-25 19:18
Closing, as `firebase_admob` is [now deprecated](https://pub.dev/packages/firebase_admob/versions/0.11.0+2).

**Closed by stuartmorgan** 2021-05-25 19:18 UTC
Labels: P4, p: firebase_admob, p: first party, plugin, severe: new feature
