### ISSUE TITLE
[in_app_purchase] buyNonConsumable failing

### ISSUE THREAD

**Issue by erf** [flutter/flutter#66147] opened 2020-09-18 22:19 UTC
## Steps to Reproduce

Running on my iPhone device in debug mode from Android Studio, i tried to call 

```dart
final result = await InAppPurchaseConnection.instance.buyNonConsumable(purchaseParam: PurchaseParam(productDetails: productDetails))
```

Where `productDetails` is a non-null object i got from calling 

```dart
InAppPurchaseConnection.instance.queryProductDetails(productIds)
```

The product is an iOS subscription.

The call to `buyNonConsumable` resulted in a crash, with no error message, even with `--verbose`.

Then i figured i should add `sandboxTesting: true` to `PurchaseParam`. Now i don't get  crash, but i got the following error:

```
flutter: error buying non consumable: PlatformException(storekit_duplicate_product_object, There is a pending transaction for the same product identifier. Please either wait for it to be finished or finish it manually using `completePurchase` to avoid edge cases., {applicationUsername: null, requestData: null, quantity: 1, productIdentifier: myProductID, simulatesAskToBuyInSandbox: true}, null)
```

I have already set up a listener to `purchaseUpdatedStream` before `runApp`, but i don't receive any events now.

UPDATE: i did receive events the next day..

**Expected results:** 

I expect the call to return with a result.

**Actual results:** 

The app either crashed with no error message or threw an expecetion with `sandboxTesting: true` set.

<details>
  <summary>Logs</summary>

See log file:

[log-iap.txt](https://github.com/flutter/flutter/files/5248474/log-iap.txt)

Nothing of relevance.

```
[✓] Flutter (Channel dev, 1.22.0-12.0.pre, on Mac OS X 10.15.6 19G2021, locale en-GB)
    • Flutter version 1.22.0-12.0.pre at /Users/erlend/flutter
    • Framework revision a27c242b0e (7 days ago), 2020-09-11 17:46:57 -0400
    • Engine revision fee6f9e533
    • Dart version 2.10.0 (build 2.10.0-110.0.dev)


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/erlend/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.7, Build version 11E801a
    • CocoaPods version 1.9.1

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.40.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.0

[✓] Connected device (2 available)
    • Erlend (mobile) • 76dfa318a18803240a229805dd90bcb18d07fef1 • ios        • iOS 13.7
    • macOS (desktop) • macos                                    • darwin-x64 • Mac OS X 10.15.6 19G2021
    ! Error: Erlend is busy: Processing cache files from device. Xcode will continue when Erlend is finished. (code -10)

• No issues found!
```

</details>

**Comment by erf** [comment] 2020-09-19 09:20
Today i did get a `purchaseUpdateStream` event with and empty purchases array.

When i tried purchase the iOS subscription today i got a new error in addition to the previous mentioned error:

```
flutter: Failed assertion: boolean expression must not be null
```

**Comment by Phorez** [comment] 2020-09-19 13:22
happening to me as well

**Comment by craigomac** [comment] 2020-09-20 13:57
In `InAppPurchasePlugin.m:182` there is:

```
payment.simulatesAskToBuyInSandbox =
        [[paymentMap objectForKey:@"simulatesAskToBuyInSandbox"] boolValue];
```

However, when the Flutter side sends `null` for this option, on the Objective-C side we get a `NSNull` instance, on which you cannot call `boolValue`—so it crashes.

I guess the fix should be to check the type of `simulatesAskToBuyInSandbox`.

**Comment by ndhbr** [comment] 2020-09-27 14:55
#60763 This is one of the plugins that simply will never work.

**Comment by erf** [comment] 2020-09-27 15:03
@ndhbr try [purchases_flutter](https://pub.dev/packages/purchases_flutter) by RevenueCat

**Comment by ndhbr** [comment] 2020-09-27 19:26
@erf I've already thought about that, but actually I don't want to make my app dependent on yet another company.

**Comment by renefloor** [comment] 2021-04-07 12:03
Duplicate of #60763

Old purchases need to be finished.

**Comment by mvanbeusekom** [comment] 2021-04-07 12:05
Closing this issue as it is a duplicate. If you don't agree leave a comment with an explanation and I will be happy to re-open the issue.

**Closed by mvanbeusekom** 2021-04-07 12:05 UTC
Labels: p: first party, p: in_app_purchase, passed first triage, platform-ios, plugin, severe: crash
