### ISSUE TITLE
What time can the flutter desktop embedding run on windows 7?

### ISSUE THREAD

**Issue by biij5698** [flutter/flutter#43897] opened 2019-10-31 10:56 UTC
@stuartmorgan What time can the flutter desktop embedding run on the windows seven system?
I have waited too long.

**Comment by stuartmorgan** [comment] 2019-10-31 14:59
You have previously been asked not to file duplicate bugs. Do not do so again. Spamming the big system, and me personally, will not affect the outcome.

Closing as a duplicate of #41418

**Comment by stuartmorgan** [comment] 2019-10-31 15:00
> I have waited too long.

You are welcome to summit patches adding Windows 7 support instead of waiting.

**Closed by stuartmorgan** 2019-10-31 14:59 UTC
