### ISSUE TITLE
flutter build ios --release. Only works if i run flutter clean first (from successful debug)

### ISSUE THREAD

**Issue by x4080** [flutter/flutter#57828] opened 2020-05-23 01:14 UTC
doctor

```
✓] Flutter (Channel master, 1.19.0-2.0.pre.142, on Mac OS X 10.14.5 18F132, locale en-ID)
 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
[!] Android Studio (version 3.5)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.45.1)
[✓] Connected device (1 available)
```

So the problem is :
- Flutter debug to ios, works fine
- When try to build release, it errors like 
```
Error output from Xcode build:
↳
    ** BUILD FAILED 

...
Command PhaseScriptExecution failed with a nonzero exit code
    note: Using new build system
    note: Planning build
    note: Constructing build description
...
Encountered error while building for device.
```
- run flutter clean
- run flutter build ios --release
- works
```
...
Xcode build done.                                           153.6s
...
```
- Now when I try to debug : error
```
...
Could not build the application for the simulator.
Error launching application on iPhone 11 Pro Max.
Exited (sigterm)
```
- run flutter clean
- debug works

**Comment by TahaTesser** [comment] 2020-05-25 11:05
Hi @x4080 
Can  you please provide `flutter build ios --release` with crash?
Thank uoi

**Comment by x4080** [comment] 2020-05-28 23:57
@TahaTesser Sorry for late reply, I try again with empty new project and it works as expected, I'll try to copy my lib to this new project and try again

**Comment by x4080** [comment] 2020-05-29 00:06
After above, I tried again in my old project release (without flutter clean after flutter debug) and here's the error
```
The domain/default pair of (/Users/zro/Documents/flutter
    projects/brix/build/ios/Release-iphoneos/Runner.app/Frameworks/App.framework/flutter_assets/ios/Flutter/App.framework/Info.plist, CFBundleExecutable) does not
    exist
    fatal error: lipo: can't map input file: /Users/zro/Documents/flutter
    projects/brix/build/ios/Release-iphoneos/Runner.app/Frameworks/App.framework/flutter_assets/ios/Flutter/App.framework/ (Invalid argument)
    fatal error: lipo: can't map input file: /Users/zro/Documents/flutter
    projects/brix/build/ios/Release-iphoneos/Runner.app/Frameworks/App.framework/flutter_assets/ios/Flutter/App.framework/ (Invalid argument)
    Failed to extract armv7 for /Users/zro/Documents/flutter
    projects/brix/build/ios/Release-iphoneos/Runner.app/Frameworks/App.framework/flutter_assets/ios/Flutter/App.framework/. Running lipo -info:
    fatal error: lipo: can't map input file: /Users/zro/Documents/flutter
    projects/brix/build/ios/Release-iphoneos/Runner.app/Frameworks/App.framework/flutter_assets/ios/Flutter/App.framework/ (Invalid argument)
    Command PhaseScriptExecution failed with a nonzero exit code
    note: Using new build system
    note: Planning build
    note: Constructing build description

Encountered error while building for device.
```

Any hints ?

**Comment by TahaTesser** [comment] 2020-05-29 07:33
Hi @x4080 
This issue related to your `plist` file 
Please check this [solution](https://github.com/flutter/flutter/issues/35256#issuecomment-526797214)
Thank you

**Comment by TahaTesser** [comment] 2020-06-01 07:02
Hi @x4080 
Did you manage to solve the issue?
Thank you

**Comment by x4080** [comment] 2020-06-01 21:41
@TahaTesser Sorry but I'm away from my computer right now, I'll let you know when I get into it, you can close it first if you like, I'll re open it if I still have problem, btw (havent tried it yet) why flutter clean seems to temporarily solve the issue if the problem is the plist ?

**Comment by jmagman** [comment] 2020-06-26 17:04
Duplicate of https://github.com/flutter/flutter/issues/57210.

**Closed by jmagman** 2020-06-26 17:04 UTC
Labels: in triage, waiting for customer response
