### ISSUE TITLE
Textfield issue: words select bar position has bug when use iPad Smart Keyboard to input Chinese

### ISSUE THREAD

**Issue by yijian166** [flutter/flutter#28411] opened 2019-02-24 04:33 UTC
## Steps to Reproduce

1. use iPad with Smart Keyboard
2. select Chinese keyboard
3. the words select bar show in top of iPad, and under the status bar

![img_e0c77dd0e10c-1](https://user-images.githubusercontent.com/710308/53295153-07aee980-3830-11e9-96ef-d65ad7ce61a5.jpeg)

## flutter doctor -v

```

[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.14.3 18D109, locale zh-Hans-CN)
    • Flutter version 1.0.0 at /Users/tyler/code/flutter
    • Framework revision 5391447fae (3 months ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/tyler/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.1.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.31.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.23.0

[✓] Connected device (3 available)

```

**Comment by fh345392977** [comment] 2019-02-24 05:30
Same issue!

**Comment by zoechi** [comment] 2019-02-25 07:35
@fh345392977 Using "add reaction" on the initial comment would increase priority while `+1`, `me too`, ... comments are rather pointless and cause lots of people to get notified for no reason.
To get notified yourself use the [Subscribe] button to the top right instead.

**Comment by LongCatIsLooong** [comment] 2020-04-17 17:40
Duplicate of https://github.com/flutter/flutter/issues/9344.

**Closed by LongCatIsLooong** 2020-04-17 17:40 UTC
Labels: a: tablet, a: text input, engine, framework, platform-ios

**Comment by jlcool** [comment] 2020-04-29 07:45
@LongCatIsLooong In the past three years, has this problem been solved or can it not be solved?
