### ISSUE TITLE
Request Feature for desktop. change form toolbar color.

### ISSUE THREAD

**Issue by P-B1101** [flutter/flutter#63472] opened 2020-08-11 10:39 UTC
## Use case
 i want to change windwos app form color.
 (the color of toolbar that has close and minimize and maximize button).
## Proposal
it would be great if there would be way to change toolbar color of windows desktop app.
it would be more great if we can change color of its icon. or event better if we could remove it at all.
as in image below, i want to change the white color or remove the white part at all.

![Annotation 2020-08-11 151147](https://user-images.githubusercontent.com/22874550/89888502-4cc20980-dbe5-11ea-9895-135641b590f9.png)

**Comment by stuartmorgan** [comment] 2020-08-11 15:34
Duplicate of https://github.com/flutter/flutter/issues/31373

**Closed by stuartmorgan** 2020-08-11 15:34 UTC
Labels: a: desktop, framework, platform-windows, severe: new feature
