### ISSUE TITLE
Placeholder order error in generated Dart file for i18n when using "price" as first parameter

### ISSUE THREAD

**Issue by gaogq3** [flutter/flutter#149463] opened 2024-05-31 06:32 UTC
## Description
I've encountered an issue with the Flutter i18n process where the order of placeholders in the generated Dart file does not match the order defined in the arb file. Specifically, when I use "price" as the first placeholder in an arb file, the generated Dart file incorrectly positions "price" as the second parameter in the getter method.

### Steps to Reproduce
1. Define a string with placeholders in an arb file, with "price" as the first placeholder.
![image](https://github.com/cfug/flutter.cn/assets/30523358/80a73233-30e1-472f-ba1d-d18ca88d07ff)

2. Run flutter pub get and flutter pub run intl_utils:generate to generate the Dart file from the arb file.
3. Observe the generated Dart file.

## Expected Behavior
The generated Dart file should have a method signature that matches the order of placeholders in the arb file:

`String specialFun(Object price, Object number){//...}`
## Actual Behavior
The generated Dart file has the "price" placeholder as the second parameter instead of the first:

`String specialFun(Object number, Object price){//...}`

![image](https://github.com/cfug/flutter.cn/assets/30523358/ae47ae8b-6b93-49df-bd35-353a137676ce)

## Environment:
![image](https://github.com/cfug/flutter.cn/assets/30523358/2dca2fd3-5851-4f43-b0bf-34aa0839fb44)

**Comment by huycozy** [comment] 2024-06-03 04:34
@gaogq3 This is a duplicate of https://github.com/flutter/flutter/issues/116308. Please see [my comment](https://github.com/flutter/flutter/issues/149394#issuecomment-2141760278) on your other duplicate issue.

**Closed by huycozy** 2024-06-03 04:34 UTC
Labels: in triage
