### ISSUE TITLE
Error connecting to the service protocol: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:65227/797xemDEehQ=/ws

### ISSUE THREAD

**Issue by BoomPowbep** [flutter/flutter#33130] opened 2019-05-21 14:08 UTC
## Steps to Reproduce
1. Lauch
2. Run 'main.dart'
3. Get the error `Error connecting to the service protocol: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:65227/797xemDEehQ=/ws` + App launching and closing immediately

## Logs

```
Launching lib/main.dart on iPhone 6s in debug mode...
Running Xcode build...
Xcode build done.                                            8,3s
Configuring the default Firebase app...
6.0.0 - [Firebase/Core][I-COR000004] App with name __FIRAPP_DEFAULT does not exist.
6.0.0 - [Firebase/Analytics][I-ACS023007] Analytics v.60000000 started
6.0.0 - [Firebase/Analytics][I-ACS023008] To enable debug logging set the following application argument: -FIRAnalyticsDebugEnabled (see http://goo.gl/RfcP7r)
Configured the default Firebase app __FIRAPP_DEFAULT.
6.0.0 - [Firebase/Core][I-COR000027] The library name (flutter-firebase_core) or version number (0.4.0+1) contain invalid characters. Only alphanumeric, dash, underscore and period characters are allowed.
*** First throw call stack:
(
	0   CoreFoundation                      0x00000001173776fb __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x000000011691bac5 objc_exception_throw + 48
	2   CoreFoundation                      0x0000000117377555 +[NSException raise:format:] + 197
	3   Runner                              0x000000010f46aa96 +[FIRApp configureWithName:options:] + 326
	4   Runner                              0x000000010f46a92f +[FIRApp configureWithOptions:] + 143
	5   Runner                              0x000000010f46a85f +[FIRApp configure] + 607
	6   Runner                              0x000000010f31eacc -[AppDelegate application:didFinishLaunchingWithOptions:] + 156
	7   UIKitCore                           0x000000011fa90311 -[UIApplication _handleDelegateCallbacksWithOptions:isSuspended:restoreState:] + 280
	8   UIKitCore                           0<…>
Error connecting to the service protocol: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:65227/797xemDEehQ=/ws

```
If, from the AppDelegate.m, I remove the `[FIRApp configure];` instruction, the app launches with the logs above, without the error...

This is my flutter doctor:
```
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.4 18E226, locale fr-FR)
    • Flutter version 1.5.4-hotfix.2 at /Users/mickaeldebalme/SDK/Flutter/flutter
    • Framework revision 7a4c33425d (3 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/mickaeldebalme/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Users/mickaeldebalme/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/182.5314842/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • ios-deploy 1.9.4
    • CocoaPods version 1.7.0.beta.3

[✓] Android Studio (version 3.3)
    • Android Studio at /Users/mickaeldebalme/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/182.5314842/Android Studio.app/Contents
    • Flutter plugin version 34.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] Connected device (1 available)
    • iPhone 6s • EB9A5D7D-C265-4C42-AAA8-790CD5AED88A • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)

• No issues found!
```

**Comment by audkar** [comment] 2019-05-21 17:45
duplicate #33050

**Comment by audkar** [comment] 2019-05-21 17:45
Maybe related #33050

**Comment by TanmaySoni** [comment] 2019-05-22 11:23
i am also having same issue

**Comment by DWYW** [comment] 2019-05-30 04:08
+1

**Comment by DanTup** [comment] 2019-06-05 13:05
For those seeing this on Android emulator using Q level API, see #33050. Try creating one using API level 28 to see if that solves the issue until there's a fix.

I don't think that covers the OP here though, as it says iPhone in the message.

**Comment by biklas7** [comment] 2019-07-05 16:59
@DanTup I'm also seeing this error on emulators with the api version 28.

**Comment by DanTup** [comment] 2019-07-08 13:22
@biklas7 do you mean the crash shown in the original message here, or just the message in the title ("Connection closed before full header...")? If the latter, please open a new issue with the full output when reproducing with `flutter run -v` (and output of `flutter doctor`) as it's probably a different issue (there are many causes for this error message).

**Comment by biklas7** [comment] 2019-07-08 14:46
@DanTup I think it was the same message like the one presented in this issue. It happened both on a real device with Android Q and then on an emulator with API 28. I did a big refactor in the app, but I will try to reproduce the error again and will post the logs here or in a new issue if that's the case.

**Comment by DanTup** [comment] 2019-07-08 15:09
@biklas7 to clarify - there are two messages in this issue - the one in the title "Connection closed before full header was received" and what looks like a crash related to Firebase:

```
*** First throw call stack:
(
	0   CoreFoundation                      0x00000001173776fb __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x000000011691bac5 objc_exception_throw + 48
	2   CoreFoundation                      0x0000000117377555 +[NSException raise:format:] + 197
	3   Runner                              0x000000010f46aa96 +[FIRApp configureWithName:options:] + 326
	4   Runner                              0x000000010f46a92f +[FIRApp configureWithOptions:] + 143
```

I think the message in the title (connection issue) is a red herring here - I think it occurred because the app crashed during startup (which means Flutter can't connect to the VM). If you're seeing that connection error message without seeing the same crash at startup, it's likely a different error (there are many reasons why Flutter might not be able to connect - for example proxy servers - so that message isn't a good indicator of issues being the same).

**Comment by biklas7** [comment] 2019-07-08 15:17
Good point! Maybe it's a different error. Either way, it seems that the error isn't happening now :man_shrugging: and I don't know why. @DanTup sorry I can't be of more help. If it happens again I will open an issue with the proper logs attached.

**Comment by thavlik** [comment] 2019-07-29 21:19
On one of the iPads I am using, I am having this issue about 50% of the time when I launch from VS Code. I have never been able to reproduce this bug launching via XCode. On the other, I get this error 100% of the time I try launching from VS Code (again, never from XCode). Launching via `flutter run` will run the app in addition to displaying the error message, but hot reloading is disabled.

**Comment by DanTup** [comment] 2019-08-05 13:04
@thavlik do you have a proxy server? Do you have the iPads set to sync over WiFi? Both of those have caused similar issues in the past. The full output of `flutter run -v` may be useful when you see this issue.

**Comment by thavlik** [comment] 2019-08-16 15:02
The device I've been using is neither logged into an Apple account nor has "iTunes Wi-Fi Sync" enabled in Settings > General.

**Comment by DanTup** [comment] 2019-08-19 09:13
@thavlik are you able to post full output from `flutter run -v` when you see the message there?

**Comment by iapicca** [comment] 2019-11-08 10:46
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.

**Closed by iapicca** 2019-11-08 10:46 UTC
Labels: waiting for customer response
