### ISSUE TITLE
BUG: DropdownButtonFormField input isn't clipped when focused/hovered.

### ISSUE THREAD

**Issue by irvine5k** [flutter/flutter#142069] opened 2024-01-23 20:55 UTC
### Steps to reproduce

When using an input decorator theme in ThemeData, the form field of the DropdownButtonFormField gets the correct themed result, but the shape is not clipped based on used radius of the input decorator for focused and hovered states.

In the supplied example, keep the custom InputDecorationTheme enabled, tap the DropDownButtonFormField and select "1", it should trig a validation error, so focus or hover the DropdownButtonFormField. The focus/hover highlights flow outside the bounds of the control.

### Expected results

The error message isn't overlayed when hovering or the field is focused

### Actual results
Focus/hover highlights flow outside the bounds of the control is expanding to the error message.

<img width="626" alt="image" src="https://github.com/flutter/flutter/assets/32758755/bf088155-3408-49c1-b5cb-1076301c1ba9">

### Code sample

<details open><summary>Code sample</summary>

https://dartpad.dev/?id=3b7483a0244597a9b0a7ea83f75abc0e

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
flutter doctor -v
[✓] Flutter (Channel stable, 3.16.1, on macOS 12.3.1 21E258 darwin-arm64, locale en-BR)
    • Flutter version 3.16.1 on channel stable at /Users/kelvengalvao/dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7f20e5d18c (8 weeks ago), 2023-11-27 09:47:30 -0800
    • Engine revision 22b600f240
    • Dart version 3.2.1
    • DevTools version 2.28.3

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS and macOS development.
      Download at: https://developer.apple.com/xcode/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on
        the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] IntelliJ IDEA Community Edition (version 2023.3.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 77.0.1
    • Dart plugin version 233.11799.172

[✓] VS Code (version 1.84.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.76.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.3.1 21E258 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 120.0.6099.234

[✓] Network resources
    • All expected network resources are available.
```

</details>

**Comment by irvine5k** [comment] 2024-01-23 20:57
Relates to #131282 which was fixed by #31481 and released on [3.16](https://docs.flutter.dev/release/release-notes/release-notes-3.16.0)

**Comment by huycozy** [comment] 2024-01-24 10:15
Hi @irvine5k 
Could you be more specific on `Actual result`? Also, your sample code hasn't applied `InputDecorationTheme` to the theme data, please update it corresponding to the description. Thanks!

**Comment by irvine5k** [comment] 2024-01-24 16:04
@huycozy I updated the sample code and I also tried to be more specific in the actual result (I don't know how can I be even more)

**Comment by huycozy** [comment] 2024-01-25 04:46
I see, it's InkWell spreads to error message area. And this is a known issue at https://github.com/flutter/flutter/issues/106659.  

Also, the issue you mentioned in the first section from description and the issue title is fixed at https://github.com/flutter/flutter/issues/131282, I don't see the issue when re-checking this. 

Closing the issue as a duplicate of https://github.com/flutter/flutter/issues/106659.

**Closed by huycozy** 2024-01-25 04:46 UTC
Labels: in triage
