### ISSUE TITLE
VersionCheckError during `flutter upgrade`

### ISSUE THREAD

**Issue by LiJiyaoisrunning** [flutter/flutter#42515] opened 2019-10-11 09:59 UTC
While I upgrade flutter sdk , throw those:
>Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Failed to send crash report due to a network error: SocketException: OS Error:
Operation timed out, errno = 60, address = clients2.google.com, port = 49705
Crash report written to /Users/XXXX/flutter_01.log;
please let us know at https://github.com/flutter/flutter/issues.

so I submit this issue.

flutter_01.log:

Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter upgrade

## exception

VersionCheckError: VersionCheckError: Command exited with code -9: git log -n 1 --pretty=format:%ad --date=iso
Standard error: 

```
#0      _runSync (package:flutter_tools/src/version.dart:506:5)
#1      FlutterVersion._latestGitCommitDate (package:flutter_tools/src/version.dart:130:12)
#2      FlutterVersion.frameworkCommitDate (package:flutter_tools/src/version.dart:121:37)
#3      FlutterVersion.toString (package:flutter_tools/src/version.dart:98:99)
#4      UpgradeCommand.runCommand (package:flutter_tools/src/commands/upgrade.dart:70:32)
<asynchronous suspension>
#5      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:545:18)
#6      _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#7      _rootRunUnary (dart:async/zone.dart:1132:38)
#8      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#9      _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#10     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#11     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#12     Future._complete (dart:async/future_impl.dart:473:7)
#13     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#14     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
#15     _rootRun (dart:async/zone.dart:1124:13)
#16     _CustomZone.run (dart:async/zone.dart:1021:19)
#17     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#18     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#19     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#20     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#21     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
```

## flutter doctor

```
encountered exception: VersionCheckError: Command exited with code -9: git log -n 1 --pretty=format:%ad --date=iso
Standard error: 

#0      _runSync (package:flutter_tools/src/version.dart:506:5)
#1      FlutterVersion._latestGitCommitDate (package:flutter_tools/src/version.dart:130:12)
#2      FlutterVersion.frameworkCommitDate (package:flutter_tools/src/version.dart:121:37)
#3      FlutterVersion.frameworkDate (package:flutter_tools/src/version.dart:83:31)
#4      FlutterValidator.validate (package:flutter_tools/src/doctor.dart:452:127)
<asynchronous suspension>
#5      Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:116:52)
#6      Doctor.diagnose (package:flutter_tools/src/doctor.dart:189:41)
<asynchronous suspension>
#7      _doctorText.<anonymous closure> (package:flutter_tools/runner.dart:188:26)
#8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#9      _rootRun (dart:async/zone.dart:1124:13)
#10     _CustomZone.run (dart:async/zone.dart:1021:19)
#11     _runZoned (dart:async/zone.dart:1516:10)
#12     runZoned (dart:async/zone.dart:1463:12)
#13     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#14     _doctorText (package:flutter_tools/runner.dart:187:19)
<asynchronous suspension>
#15     _createLocalCrashReport (package:flutter_tools/runner.dart:165:32)
<asynchronous suspension>
#16     _handleToolError (package:flutter_tools/runner.dart:120:33)
<asynchronous suspension>
#17     run.<anonymous closure> (package:flutter_tools/runner.dart:64:20)
<asynchronous suspension>
#18     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#19     _rootRun (dart:async/zone.dart:1124:13)
#20     _CustomZone.run (dart:async/zone.dart:1021:19)
#21     _runZoned (dart:async/zone.dart:1516:10)
#22     runZoned (dart:async/zone.dart:1463:12)
#23     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#24     runInContext (package:flutter_tools/src/context_runner.dart:48:24)
<asynchronous suspension>
#25     run (package:flutter_tools/runner.dart:51:10)
#26     main (package:flutter_tools/executable.dart:52:9)
<asynchronous suspension>
#27     main (file:///Users/forever/Desktop/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#28     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:298:32)
#29     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

**Comment by jmagman** [comment] 2019-10-11 18:38
Looks like a network error.  Can you ping clients2.google.com?
```
ping clients2.google.com
```

**Comment by christopherfujino** [comment] 2019-10-11 19:55
Also what OS version are you on? And it would help to know what version of flutter you are on (unfortunately the tool is crashing while trying to check). Can you do `git status; git rev-parse HEAD` and copy that here? Thank you.

**Comment by LiJiyaoisrunning** [comment] 2019-10-12 00:40
You are right, all packets loss


 
PING clients.l.google.com (216.58.200.238): 56 data bytes
 
Request timeout for icmp_seq 0
 
Request timeout for icmp_seq 1
 
Request timeout for icmp_seq 2
 
Request timeout for icmp_seq 3
 
Request timeout for icmp_seq 4
 
Request timeout for icmp_seq 5
 
Request timeout for icmp_seq 6
 
Request timeout for icmp_seq 7
 
Request timeout for icmp_seq 8
 
Request timeout for icmp_seq 9
 
Request timeout for icmp_seq 10
 
Request timeout for icmp_seq 11
 
Request timeout for icmp_seq 12
 
Request timeout for icmp_seq 13
 
Request timeout for icmp_seq 14
 
Request timeout for icmp_seq 15
 
Request timeout for icmp_seq 16
 
Request timeout for icmp_seq 17
 
^C
 
--- clients.l.google.com ping statistics ---
 
19 packets transmitted, 0 packets received, 100.0% packet loss



------------------ 原始邮件 ------------------
发件人: "Jenn Magder"<notifications@github.com>;
发送时间: 2019年10月12日(星期六) 凌晨2:40
收件人: "flutter/flutter"<flutter@noreply.github.com>;
抄送: "李纪尧"<460564954@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [flutter/flutter] flutter upgrade crash (#42515)




Looks like a network error.  Can you ping clients2.google.com?
 ping clients2.google.com

**Comment by LiJiyaoisrunning** [comment] 2019-10-12 00:41
It can not work


 
fatal: not a git repository (or any of the parent directories): .git
 
fatal: not a git repository (or any of the parent directories): .git



By the way, After I do flutter upgrade, and throw the oops words, then I do flutter doctor, show that:


 
[✓] Flutter (Channel stable, v1.9.1+hotfix.4, on Mac OS X 10.15 19A583, locale
 
    zh-Hans-CN)
 
 
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
 
[!] Xcode - develop for iOS and macOS (Xcode 10.3)
 
    ✗ CocoaPods not installed.
 
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
 
        code that responds to your plugin usage on the Dart side.
 
        Without CocoaPods, plugins will not work on iOS or macOS.
 
        For more info, see https://flutter.dev/platform-plugins
 
      To install:
 
        sudo gem install cocoapods
 
        pod setup
 
[✓] Android Studio (version 3.2)
 
[✓] Connected device (1 available)



Then I back to my project, and run, It seems work normally.


------------------ 原始邮件 ------------------
发件人: "Christopher Fujino"<notifications@github.com>;
发送时间: 2019年10月12日(星期六) 凌晨3:57
收件人: "flutter/flutter"<flutter@noreply.github.com>;
抄送: "李纪尧"<460564954@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [flutter/flutter] flutter upgrade crash (#42515)




Also what OS version are you on? And it would help to know what version of flutter you are on (unfortunately the tool is crashing while trying to check). Can you do git status; git rev-parse HEAD and copy that here? Thank you.

**Comment by jonahwilliams** [comment] 2020-02-17 02:13
If you have more context for this error message, or want to leave a 👍 to indicate that it is still affecting you please comment on the meta issue https://github.com/flutter/flutter/issues/50902

**Comment by jonahwilliams** [comment] 2020-02-17 02:13
Duplicate of

**Closed by jonahwilliams** 2020-02-17 02:13 UTC
Labels: severe: crash, t: flutter doctor, tool
