### ISSUE TITLE
[Xcode 16.0][Flutter 3.24.3] Cannot build profile mode - NPE in xcode_backend.dart during build

### ISSUE THREAD

**Issue by AlexDochioiu** [flutter/flutter#156454] opened 2024-10-09 08:04 UTC
### Steps to reproduce

<img width="906" alt="image" src="https://github.com/user-attachments/assets/10df31c3-d7bc-4fe0-a8eb-3555247c120e">

### Expected results

Should be able to build. I tried to build both directly via Xcode and through `flutter run --profile`

### Actual results

NPE error

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console

Showing Recent Messages
Unhandled exception:

Null check operator used on a null value

#0      Context.embedFlutterFrameworks (file:///Users/alexandrudochioiu/.asdf/installs/flutter/3.24.3-stable/packages/flutter_tools/bin/xcode_backend.dart:237:68)

#1      Context.run (file:///Users/alexandrudochioiu/.asdf/installs/flutter/3.24.3-stable/packages/flutter_tools/bin/xcode_backend.dart:61:9)

#2      main (file:///Users/alexandrudochioiu/.asdf/installs/flutter/3.24.3-stable/packages/flutter_tools/bin/xcode_backend.dart:17:5)

#3      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:33)

#4      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)


```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.24.3, on macOS 15.0.1 24A348 darwin-arm64, locale en-GB)
    • Flutter version 3.24.3 on channel stable at /Users/alexandrudochioiu/.asdf/installs/flutter/3.24.3-stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2663184aa7 (4 weeks ago), 2024-09-11 16:27:48 -0500
    • Engine revision 36335019a8
    • Dart version 3.5.3
    • DevTools version 2.37.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/alexandrudochioiu/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/alexandrudochioiu/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16A242d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)

[✓] IntelliJ IDEA Community Edition (version 2022.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.94.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.98.0

[✓] Connected device (3 available)
    • Alexandru’s iPhone 15 (mobile)  • redacted                  • ios            • iOS 18.0 22A5350a
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad     • darwin         • macOS 15.0.1 24A348 darwin-arm64
    • Chrome (web)                    • chrome                    • web-javascript • Google Chrome 129.0.6668.90

[✓] Network resources
    • All expected network resources are available.
```

</details>

**Comment by danagbemava-nc** [comment] 2024-10-09 10:13
Hi @AlexDochioiu, this appears to be a duplicate of https://github.com/flutter/flutter/issues/140845. 

Kindly try to see if any of the workarounds in there work for you. 

Closing from here as duplicate. 

Thank you

**Closed by danagbemava-nc** 2024-10-09 10:13 UTC
Labels: in triage

**Comment by AlexDochioiu** [comment] 2024-10-09 11:18
@danagbemava-nc Thank you for pointing this out. My profile runner was pointing to some `Pods-Runner.xcconfig` instead of the release one
