### ISSUE TITLE
[tool_crash] FormatException

### ISSUE THREAD

**Issue by murad778** [flutter/flutter#160831] opened 2024-12-24 19:14 UTC
## Command
```sh
flutter --no-color run --machine --track-widget-creation --device-id=15656ab2 --start-paused --dart-define=flutter.inspector.structuredErrors=true lib\main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FormatException
```console
#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1457:5)
#1      _ChunkedJsonParser.close (dart:convert-patch/convert_patch.dart:493:7)
#2      _JsonStringDecoderSink.close (dart:convert-patch/convert_patch.dart:1553:13)
#3      _ConverterStreamEventSink.close (dart:convert/chunked_conversion.dart:78:18)
#4      _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:132:24)
#5      _rootRun (dart:async/zone.dart:1406:47)
#6      _CustomZone.run (dart:async/zone.dart:1317:19)
#7      _CustomZone.runGuarded (dart:async/zone.dart:1225:7)
#8      _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:419:13)
#9      _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:429:7)
#10     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:318:7)
#11     _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:87:11)
#12     _EventSinkWrapper.close (dart:async/stream_transformers.dart:21:11)
#13     _StringAdapterSink.close (dart:convert/string_conversion.dart:241:11)
#14     _Utf8ConversionSink.close (dart:convert/string_conversion.dart:295:20)
#15     _ConverterStreamEventSink.close (dart:convert/chunked_conversion.dart:78:18)
#16     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:132:24)
#17     _rootRun (dart:async/zone.dart:1406:47)
#18     _CustomZone.run (dart:async/zone.dart:1317:19)
#19     _CustomZone.runGuarded (dart:async/zone.dart:1225:7)
#20     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:419:13)
#21     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:429:7)
#22     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:318:7)
#23     _SyncStreamControllerDispatch._sendDone (dart:async/stream_controller.dart:785:19)
#24     _StreamController._closeUnchecked (dart:async/stream_controller.dart:640:7)
```
```console
[!] Flutter (Channel stable, 3.27.0, on Microsoft Windows [Version 10.0.22000.2538], locale ar-SA)
    • Flutter version 3.27.0 on channel stable at C:\Users\ALFASHEL\flutter
    ! Warning: `dart` on your path resolves to C:\Users\ALFASHEL\dart-sdk\bin\dart.exe, which is not inside your current Flutter SDK checkout at C:\Users\ALFASHEL\flutter. Consider adding C:\Users\ALFASHEL\flutter\bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 8495dee1fd (2 weeks ago), 2024-12-10 14:23:39 -0800
    • Engine revision 83bacfc525
    • Dart version 3.6.0
    • DevTools version 2.40.2
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at C:/Users/ALFASHEL/AppData/Local/Android/Sdk
    • Platform android-35, build-tools 35.0.0
    • ANDROID_HOME = C:/Users/ALFASHEL/AppData/Local/Android/Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 21.0.3+-12282718-b509.11)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop Windows apps (Visual Studio Professional 2022 17.0.0)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Professional
    • Visual Studio Professional 2022 version 17.0.31903.59
    • Windows 10 SDK version 10.0.19041.0

[!] Android Studio (version 2024.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to determine bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] VS Code (version 1.93.1)
    • VS Code at C:\Users\ALFASHEL\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.98.0

[✓] Connected device (4 available)
    • SM J727VPP (mobile) • 15656ab2 • android-arm64  • Android 8.1.0 (API 27)
    • Windows (desktop)   • windows  • windows-x64    • Microsoft Windows [Version 10.0.22000.2538]
    • Chrome (web)        • chrome   • web-javascript • Google Chrome 131.0.6778.205
    • Edge (web)          • edge     • web-javascript • Microsoft Edge 131.0.2903.112

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: dec2ee5c1f98f8e84a7d5380c05eb8a3d0a81668

**Comment by danagbemava-nc** [comment] 2024-12-31 08:43
Closing this as a duplicate of https://github.com/flutter/flutter/issues/98905

**Closed by danagbemava-nc** 2024-12-31 08:43 UTC
Labels: in triage
