### ISSUE TITLE
Lamp package is not turning on flashlight on android  9(Pie) even after giving permissions .

### ISSUE THREAD

**Issue by Shavneet** [flutter/flutter#27683] opened 2019-02-08 14:03 UTC
## Steps to Reproduce
1)  In `pubspec.yaml` 
```yml
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  lamp: ^0.0.6
  permission: ^0.1.1
```
2) In `lib/main.dart` :
```dart
 getCameraPermissionStatus() async {
    var get = '';
    List<Permissions> permissions = await Permission.getPermissionsStatus([PermissionName.Camera,]);
    permissions.forEach((permission) {
      get += '${permission.permissionName}: ${permission.permissionStatus}';
      if (get != "PermissionName.Camera: PermissionStatus.allow") {
        requestCameraPermission();
      } else {
          Lamp.turnOn(intensity:1.0);
      }
    });
  }
requestCameraPermission() async {
    final res = await Permission.requestPermissions([PermissionName.Camera]);
    res.forEach((permission) {
      String a = '${permission.permissionStatus}';
      setState(() {
        if (a == 'PermissionStatus.allow') {
       Lamp.turnOn(intensity:1.0);
        }
        else {
          Permission.openSettings;
        }
      });

    });
  }
```
3) flutter run 

 

`flutter run --verbose`:
```
Navdeep-Android:flutter_app_pure_demo_shavi navdeepkaur$ flutter run --verbose
[  +38 ms] executing: [/Users/navdeepkaur/Downloads/flutter/] git rev-parse
--abbrev-ref --symbolic @{u}
[  +47 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/Users/navdeepkaur/Downloads/flutter/] git rev-parse
--abbrev-ref HEAD
[  +10 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[        ] executing: [/Users/navdeepkaur/Downloads/flutter/] git ls-remote
--get-url origin
[  +10 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[        ] executing: [/Users/navdeepkaur/Downloads/flutter/] git log -n 1
--pretty=format:%H
[  +14 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] 5391447fae6209bb21a89e6a5a6583cac1af9b4b
[        ] executing: [/Users/navdeepkaur/Downloads/flutter/] git log -n 1
--pretty=format:%ar
[  +13 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[        ] 2 months ago
[   +1 ms] executing: [/Users/navdeepkaur/Downloads/flutter/] git describe
--match v*.*.* --first-parent --long --tags
[  +14 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long
--tags
[   +1 ms] v1.0.0-0-g5391447fa
[ +309 ms] executing: /Users/navdeepkaur/Library/Android/sdk/platform-tools/adb
devices -l
[  +10 ms] Exit code 0 from:
/Users/navdeepkaur/Library/Android/sdk/platform-tools/adb devices -l
[        ] List of devices attached
[   +6 ms] executing: idevice_id -h
[  +43 ms] /usr/bin/xcrun simctl list --json devices
[ +113 ms] No connected devices.
[        ] Run 'flutter emulators' to list and start any available device
emulators.
[        ] If you expected your device to be detected, please run "flutter
doctor" to
           diagnose
[        ] potential issues, or visit https://flutter.io/setup/ for
troubleshooting tips.
[  +17 ms] "flutter run" took 422ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:26:3)
#1      RunCommand.validateCommand
(package:flutter_tools/src/commands/run.dart:249:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand
(package:flutter_tools/src/runner/flutter_command.dart:379:11)
<asynchronous suspension>
#3      FlutterCommand.run.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command.dart:335:33)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#5      _rootRun (dart:async/zone.dart:1124:13)
#6      _CustomZone.run (dart:async/zone.dart:1021:19)
#7      _runZoned (dart:async/zone.dart:1516:10)
#8      runZoned (dart:async/zone.dart:1463:12)
#9      AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#10     FlutterCommand.run
(package:flutter_tools/src/runner/flutter_command.dart:326:20)
#11     CommandRunner.runCommand (package:args/command_runner.dart:196:27)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:401:21)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#14     _rootRun (dart:async/zone.dart:1124:13)
#15     _CustomZone.run (dart:async/zone.dart:1021:19)
#16     _runZoned (dart:async/zone.dart:1516:10)
#17     runZoned (dart:async/zone.dart:1463:12)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#19     FlutterCommandRunner.runCommand
(package:flutter_tools/src/runner/flutter_command_runner.dart:361:19)
<asynchronous suspension>
#20     CommandRunner.run.<anonymous closure>
(package:args/command_runner.dart:111:29)
#21     new Future.sync (dart:async/future.dart:224:31)
#22     CommandRunner.run (package:args/command_runner.dart:111:11)
#23     FlutterCommandRunner.run
(package:flutter_tools/src/runner/flutter_command_runner.dart:241:18)
#24     run.<anonymous closure> (package:flutter_tools/runner.dart:60:20)
<asynchronous suspension>
#25     AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#26     _rootRun (dart:async/zone.dart:1124:13)
#27     _CustomZone.run (dart:async/zone.dart:1021:19)
#28     _runZoned (dart:async/zone.dart:1516:10)
#29     runZoned (dart:async/zone.dart:1463:12)
#30     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#31     runInContext (package:flutter_tools/src/context_runner.dart:43:24)
<asynchronous suspension>
#32     run (package:flutter_tools/runner.dart:51:10)
#33     main (package:flutter_tools/executable.dart:51:9)
<asynchronous suspension>
#34     main
(file:///b/build/slave/Mac_Flutter_Packaging/build/archive/flutter/packages/flut
ter_tools/bin/flutter_tools.dart:8:3)
#35     _startIsolate.<anonymous closure>
(dart:isolate/runtime/libisolate_patch.dart:287:32)
#36     _RawReceivePortImpl._handleMessage
(dart:isolate/runtime/libisolate_patch.dart:171:12)
```

`flutter analyze`:
``` 
Navdeep-Android:flutter_app_pure_demo_shavi navdeepkaur$ flutter analyze
Analyzing flutter_app_pure_demo_shavi...                         

   info • Unused import: 'package:flutter/services.dart' • lib/main.dart:2:8 •
          unused_import
   info • This class inherits from a class marked as @immutable, and therefore
          should be immutable (all instance fields must be final) •
          lib/main.dart:11:7 • must_be_immutable
   info • The value of the field '_hasFlash' isn't used • lib/main.dart:47:8 •
          unused_field
   info • Avoid using unnecessary statements • lib/main.dart:117:3 •
          unnecessary_statements
   info • Name non-constant identifiers using lowerCamelCase •
          lib/main.dart:128:8 • non_constant_identifier_names
   info • Avoid using unnecessary statements • lib/main.dart:161:11 •
          unnecessary_statements
   info • The method '_turnFlash' isn't used • lib/main.dart:167:10 •
          unused_element

7 issues found. (ran in 12.6s)
```

`flutter doctor -v`:
```
Navdeep-Android:flutter_app_pure_demo_shavi navdeepkaur$ flutter doctor -v
[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.12.6 16G29, locale en-US)
    • Flutter version 1.0.0 at /Users/navdeepkaur/Downloads/flutter
    • Framework revision 5391447fae (2 months ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/navdeepkaur/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 2.0.0
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 32.0.1
    • Dart plugin version 182.5124
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1248-b01)

[✓] Connected device (1 available)
    • XT1068 • ZX1D64H6G6 • android-arm • Android 6.0 (API 23)

• No issues found!
```

My full `main.dart` class:
```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

import 'package:lamp/lamp.dart';
import 'dart:io' show Platform;
import 'package:permission/permission.dart';


void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  bool _isOn = false;
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Simple Flashlight',
      theme: ThemeData(
        // This is the theme of your application.
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Simple Flashlight'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();

}

class _MyHomePageState extends State<MyHomePage> {
  String platform;
  bool  _isOn=false;
  double _intensity=1.0;
  bool _hasFlash=true;
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body:
      Container(
        decoration: new BoxDecoration(
            image: new DecorationImage(image:
            new AssetImage("images/blue_gradient.png"),
                fit: BoxFit.fill
            )
        ),
        child: new Center(
          //  child: new Column(
          //    children: <Widget>[
          child: ButtonTheme(
            minWidth: 160.0,
            height: 40.0,
            child: RaisedButton(
              shape: new RoundedRectangleBorder(
                  borderRadius: new BorderRadius.circular(5.0)),
              color: Colors.lightBlueAccent,
              child: Text("Flashlight", style: TextStyle(fontSize: 18),),
              elevation: 15.0,
              onPressed: () {
                if (platform == 'Android') {
                  checkAndroidCameraPermissions();
                } else
                 //checkAndroidCameraPermissions();
                  // _turnFlash();
                TurnOnflashLight();
                //Lamp.turnOff();
              },
            ),
          ),
          //    ],
          //  ),
        ),
      ),
      // This trailing comma makes auto-formatting nicer for build methods.
    );
  }

  @override
  void initState() {
    // TODO: implement initState
    super.initState();
   // Lamp.turnOn();
   // requestCameraPermission();
    initplatform();
  }

//its just for getting the platform version
  initplatform() async {
    if (Platform.isIOS) {
      platform = "IOS";
      print('is a IOS');
    } else if (Platform.isAndroid) {
      platform = "Android";
      print('is a Android');
      //requestAndroidPermissions();
    }
  }

void killAppState(){
  deactivate();
  Lamp.turnOn(intensity:1.0);
  mounted==false;
}

  void resumeAppState(){
    Lamp.turnOn(intensity:1.0);
    //mounted==true;
    Lamp.turnOn(intensity:1.0);
    //initState();
    Lamp.turnOn(intensity:1.0);
    main();
  }
  void TurnOnflashLight() {
   Lamp.turnOn(intensity:1.0);
     Navigator.push(context, MaterialPageRoute(builder: (context) => SecondScreen()));

 }

  checkAndroidCameraPermissions() {
    getCameraPermissionStatus();
  }

  getCameraPermissionStatus() async {
    var get = '';
    List<Permissions> permissions = await Permission.getPermissionsStatus([PermissionName.Camera,]);
    permissions.forEach((permission) {
      get += '${permission.permissionName}: ${permission.permissionStatus}';
      if (get != "PermissionName.Camera: PermissionStatus.allow") {
        requestCameraPermission();
      } else {
        TurnOnflashLight();
      }
    });
  }

  requestCameraPermission() async {
    final res = await Permission.requestPermissions([PermissionName.Camera]);
    res.forEach((permission) {
      String a = '${permission.permissionStatus}';
      setState(() {
        if (a == 'PermissionStatus.allow') {
          //RestartWidget.restartApp(context).
          TurnOnflashLight();
        }
        else {
          Permission.openSettings;
        }
      });

    });
  }
  Future _turnFlash() async {
    _isOn ? Lamp.turnOff() : Lamp.turnOn(intensity: _intensity);
    var f = await Lamp.hasLamp;
    setState((){
      _hasFlash = f;
      _isOn = !_isOn;
    });
  }
}
```

Issues i am facing :

1.  
```dart
requestCameraPermission() async {
    final res = await Permission.requestPermissions([PermissionName.Camera]);
    res.forEach((permission) {
      String a = '${permission.permissionStatus}';
      setState(() {
        if (a == 'PermissionStatus.allow') {
          Lamp.turnOn(intensity:1.0);
        }
        else {
          Permission.openSettings;
        }
      });

    });
  }
```   
, when i allow camera permission `Lamp.turnOn( )` runs , but it doesn't turn on flash light first time .I have to restart app to make it work .

2. In android 9 (pie)  version , it is not turning on the flashlight even after restarting the app .

Please look into these issues . If anybody has any solution or same kind of issue ,Please share .

Any help will be appreciated  . Thanks  .

**Comment by zoechi** [comment] 2019-02-08 14:48
Duplicate of https://github.com/clovisnicolas/flutter_lamp/issues/9

**Closed by zoechi** 2019-02-08 14:48 UTC

**Comment by Shavneet** [comment] 2019-02-20 09:10
> Duplicate of [clovisnicolas/flutter_lamp#9](https://github.com/clovisnicolas/flutter_lamp/issues/9)

Hello zoechi, Yes we can say say that this is duplicate of that issue, but please give a solution for that issue . Its being difficult for us to make an app without using java or swift . 
Hope a solution will be provided soon ....
