### ISSUE TITLE
Gating run success on (buildMode, emulator) tuple is incorrect

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#10248] opened 2017-05-22 16:05 UTC
We currently [fail to run](https://github.com/flutter/flutter/blob/2a140a77527e2cf6317b504c20f75242782f2b88/packages/flutter_tools/lib/src/commands/run.dart#L266) if we think the user is attempting to run a profile or release build on an emulator.

That's fundamentally the wrong check to perform.  What we mean to check is "do we have the right binary artifacts for the target platform?"  In a world where we provide profile and release x86* engine artifacts and can produce profile and release x86* apps, it's perfectly acceptable to run such things on an emulator.

The current check clashes with our heuristic-based approach for detecting whether the current device is an emulator (there's no fool-proof way to detect if something is an emulator on Android, since people can craft their own system images and report whatever they want to adb).  When the heuristic fails, causing us to think a physical device is actually an emulator (as happens in #10203), the user is prevented from running their release-mode app on their physical device.

**Comment by Hixie** [comment] 2017-05-22 16:10
The origin of this check is a belief that we should discourage people from profiling on hardware that doesn't reflect the characteristics of the actual target device. If you profile an app in an emulator where you're doing software rendering and the CPU is a quad-core beast and your GPU and CPU can run simultaneously at full power for hours, but your target hardware has a much more powerful GPU than its CPU, does GPU hardware rendering, and throttles the CPU and GPU such that only one can run at a time, and throttles everything when the battery gets hot after 50 seconds, you'll be optimising for wildly the wrong things.

**Comment by tvolkert** [comment] 2017-05-22 16:25
I figured as much.  However, there are times where users need to present (as in: project or cast) Flutter apps during talks and choose to use an emulator to do so.  Being able to produce an optimized build for that purpose would be nice.

Also, there's the fact that this issue combined with #10203 yields a horrible user experience.

**Comment by zoechi** [comment] 2018-12-31 11:30
#8824 seem related

**Comment by timsneath** [comment] 2020-01-02 23:37
This would be a nice-to-have feature (perhaps could be enabled through `flutter config`?, but in practice if performance of a Flutter app in this scenario is critical, there are other ways to get decent performance. Some examples:

- [Mirroring your Android device](https://fossbytes.com/android-screen-mirroring-apps-pc/)
- [Connecting an Android phone to a projector](https://www.lifewire.com/connect-android-phone-to-projector-4571047)
- [Mirroring your iPhone using QuickTime Player](https://medium.com/@patrickswong/how-to-mirror-your-iphone-with-a-lightning-cable-using-quicktime-in-os-x-yosemite-ace3f40ef483)
- [Projecting an iPhone through HDMI](https://www.pcmag.com/article/331956/how-to-connect-your-iphone-or-ipad-to-your-tv)

Given these viable alternatives, and the legitimate concerns from @hixie, I'm willing to close this as "by design" if you are, @tvolkert.

**Closed** 2020-01-08 18:42 UTC
Labels: tool, waiting for customer response
