### ISSUE TITLE
Generated ColorScheme using `colorSchemeSeed` is different from `ColorScheme.fromseed`

### ISSUE THREAD

**Issue by rares45** [flutter/flutter#107105] opened 2022-07-05 12:09 UTC
https://github.com/flutter/flutter/blob/d7bacf9b3fb21caf532ce2fe0dfba12518d35d4f/packages/flutter/lib/src/material/theme_data.dart#L445-L463

ThemeData gets some value defaults to the ones from a colors scheme only if it's made from a colorSchemeSeed, this creates a difference between specifying a `ColorScheme.fromSeed()` and just specifying a colorSchemeSeed.

For example:

```
theme: ThemeData(
              colorSchemeSeed: Colors.green,
              useMaterial3: true,
              brightness: Brightness.dark,
            ),
```
![image](https://user-images.githubusercontent.com/42469755/177322360-2c1cdbe8-89e2-4af7-a1eb-ad2a376f1855.png)

```
theme: ThemeData(
              colorScheme: ColorScheme.fromSeed(
                seedColor: Colors.green,
                brightness: Brightness.dark,
              ),
              useMaterial3: true,
            ),
```
![image](https://user-images.githubusercontent.com/42469755/177323120-7287f163-41cf-4e42-998d-c63ac4f124c1.png)

## Steps to Reproduce
1. Create a material app and use both options

**Expected results:**
Expected that both variants produce the same result.

**Actual results:** 
Using ColorScheme.fromSeed produces a different result not following M3 guidelines.

<details>
  <summary>flutter doctor -v</summary>

```

[✓] Flutter (Channel master, 3.1.0-0.0.pre.1502, on Linux Mint 20.3 5.4.0-121-generic, locale en_US.UTF-8)
    • Flutter version 3.1.0-0.0.pre.1502 on channel master at /home/rares/.apps/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 363b0f1050 (9 hours ago), 2022-07-04 23:14:07 -0400
    • Engine revision 69901542b7
    • Dart version 2.18.0 (build 2.18.0-254.0.dev)
    • DevTools version 2.15.0

[!] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /home/rares/.apps/android-sdk/
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/linux#android-setup for more details.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 2021.1)
    • Android Studio at /home/rares/.apps/android-studio
    • Flutter plugin version 64.1.2
    • Dart plugin version 211.7798
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] IntelliJ IDEA Community Edition (version 2022.1)
    • IntelliJ at /home/rares/.apps/idea-community
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin version 221.5591.58

[✓] VS Code (version 1.68.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.44.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Linux Mint 20.3 5.4.0-121-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 103.0.5060.114

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.


```

</details>

**Comment by maheshmnj** [comment] 2022-07-06 06:31
Hi @rares45, Thanks for filing the issue. I am able to reproduce the difference in colorScheme when the colorscheme is generated using the below theme in the counter app.

### ColorScheme.fromSeed
```dart
 theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(
          seedColor: Colors.green,
          brightness: Brightness.dark,
        ),
        useMaterial3: true,
      ),
```

### colorSchemeSeed

```dart
  theme: ThemeData(
        colorSchemeSeed: Colors.green,
        useMaterial3: true,
        brightness: Brightness.dark,
      ),
```

 ColorScheme.fromSeed  | colorSchemeSeed      
:-------------------------:|:-------------------------:
![Screenshot_1657088678](https://user-images.githubusercontent.com/31410839/177483400-b81b1535-f463-4299-8c50-d526b2db6f5e.png) | ![Screenshot_1657088642](https://user-images.githubusercontent.com/31410839/177483423-2696fcf2-cdc9-47c3-87a8-fa2cc67a61ea.png)


<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorSchemeSeed: Colors.green,
        useMaterial3: true,
        brightness: Brightness.dark,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);
  final String title;
  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;
  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}

```
</details> 



<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel stable, 3.0.4, on macOS 12.4 21F79 darwin-arm, locale en-IN)
    • Flutter version 3.0.4 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 85684f9300 (4 days ago), 2022-06-30 13:22:47 -0700
    • Engine revision 6ba2af10bb
    • Dart version 2.17.5
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-32, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.67.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.44.0

[✓] Connected device (3 available)
    • sdk gphone arm64 (mobile) • emulator-5554 • android-arm64  • Android 11 (API 30) (emulator)
    • macOS (desktop)           • macos         • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)              • chrome        • web-javascript • Google Chrome 103.0.5060.53

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

```
[✓] Flutter (Channel master, 3.1.0-0.0.pre.1494, on macOS 12.4 21F79 darwin-arm, locale en-IN)
    • Flutter version 3.1.0-0.0.pre.1494 on channel master at /Users/mahesh/Documents/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 829bddf616 (3 hours ago), 2022-07-04 03:49:08 -0400
    • Engine revision e78ed7f1c9
    • Dart version 2.18.0 (build 2.18.0-251.0.dev)
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-32, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13C100
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.67.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.44.0

[✓] Connected device (3 available)
    • sdk gphone arm64 (mobile) • emulator-5554 • android-arm64  • Android 11 (API 30) (emulator)
    • macOS (desktop)           • macos         • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)              • chrome        • web-javascript • Google Chrome 103.0.5060.53

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by rydmike** [comment] 2022-07-06 17:36
@rares45 the reasons for this difference are largely explained in this issue comment https://github.com/flutter/flutter/issues/19089#issuecomment-1106644732.

For an even longer and more detailed explanation and analysis of different `ThemeData` results when using different constructors and properties, you can refer to this blog post on the same topic https://rydmike.com/blog_roads_to_theme_data, roughly the same story can also be found here https://docs.flexcolorscheme.com/theming_roads.

One can certainly argue and wonder why `ThemeData` is so messy and produces such wildly varying results, mostly it is due to legacy reasons and never breaking with the past defaults, mixed in with many new ways of defining ThemeData. I agree, it should not be this complex and messy.

As long as the direct color properties exist in `ThemeData` and built in widgets still use them, the situation will not change. There is however a long running project that attempts to address and improve all these issues. You can read more about it here: https://github.com/flutter/flutter/issues/91772

**Comment by darrenaustin** [comment] 2022-07-25 00:56
As @rydmike alluded to above this is mostly due to backwards compatibility. We were trying to give reasonable defaults to the ThemeData.*Color properties based on the generated color scheme. As `colorSchemeSeed` was a new API, we could do it for this case without breaking existing apps. If we did the same thing for apps that passed in a ColorScheme, it could potentially break apps that used the `colorScheme` parameter before but got the usual defaults for the ThemeData.*Color properties. In hindsight this clearly leads to a confusing inconsistency that was probably not worth introducing just to have reasonable defaults in the `colorSchemeSeed` case.

The long term answer as @rydmike points out is the elimination of the ThemeData.*Color properties altogether: https://github.com/flutter/flutter/issues/91772, which we are working on.

**Comment by rydmike** [comment] 2022-07-27 13:19
@darrenaustin The `colorSchemeSeed` does indeed create a pretty good theme where it maps many important `ColorScheme` properties to still very relevant colors in `ThemeData`. However, it still also misses many of them, like `primaryColor` (in dark mode), `primaryColorDark`, `primaryColorLight`, `secondaryHeaderColor`, `toggleableActiveColor` (in dark mode), that it could have included and set to more `ColorScheme` correctly matched colors. Since it was a new API I thought it was a bit of a missed opportunity to not do that.

@rares45, if you are interested in getting all colors in your app `ColorScheme` based, then check out the examples/docs in the links I provided above. If you use those approaches you get `ThemeData` and SDK widgets that fully follows your `ColorScheme`, even for widgets not migrated to using `ColorScheme` directly yet.

Here is the TLDR of it, with your green color as example.

```dart

const ColorScheme mySchemeLight = ColorScheme.fromSeed(
  brightness: Brightness.light,
  seedColor: Colors.green,  
);

const ColorScheme mySchemeDark = ColorScheme.fromSeed(
  brightness: Brightness.dark,
  seedColor: Colors.green,  
);


ThemeData colorSchemedThemeData(Brightness mode, bool useMaterial3) =>
    mode == Brightness.light
        ? ThemeData(
            colorScheme: mySchemeLight,
            toggleableActiveColor:
                useMaterial3 ? mySchemeLight.primary : mySchemeLight.secondary,
            primaryColor: mySchemeLight.primary,
            primaryColorLight: Color.alphaBlend(
                Colors.white.withAlpha(0x66), mySchemeLight.primary),
            primaryColorDark: Color.alphaBlend(
                Colors.black.withAlpha(0x66), mySchemeLight.primary),
            secondaryHeaderColor: Color.alphaBlend(
                Colors.white.withAlpha(0xCC), mySchemeLight.primary),
            scaffoldBackgroundColor: mySchemeLight.background,
            canvasColor: mySchemeLight.background,
            backgroundColor: mySchemeLight.background,
            cardColor: mySchemeLight.surface,
            bottomAppBarColor: mySchemeLight.surface,
            dialogBackgroundColor: mySchemeLight.surface,
            indicatorColor: mySchemeLight.onPrimary,
            dividerColor: mySchemeLight.onSurface.withOpacity(0.12),
            errorColor: mySchemeLight.error,
            applyElevationOverlayColor: false,
            useMaterial3: useMaterial3,
            visualDensity: VisualDensity.standard,
          )
        : ThemeData(
            colorScheme: mySchemeDark,
            toggleableActiveColor:
                useMaterial3 ? mySchemeDark.primary : mySchemeDark.secondary,
            primaryColor: mySchemeDark.primary,
            primaryColorLight: Color.alphaBlend(
                Colors.white.withAlpha(0x59), mySchemeDark.primary),
            primaryColorDark: Color.alphaBlend(
                Colors.black.withAlpha(0x72), mySchemeDark.primary),
            secondaryHeaderColor: Color.alphaBlend(
                Colors.black.withAlpha(0x99), mySchemeDark.primary),
            scaffoldBackgroundColor: mySchemeDark.background,
            canvasColor: mySchemeDark.background,
            backgroundColor: mySchemeDark.background,
            cardColor: mySchemeDark.surface,
            bottomAppBarColor: mySchemeDark.surface,
            dialogBackgroundColor: mySchemeDark.surface,
            indicatorColor: mySchemeDark.onBackground,
            dividerColor: mySchemeDark.onSurface.withOpacity(0.12),
            errorColor: mySchemeDark.error,
            applyElevationOverlayColor: true,
            useMaterial3: useMaterial3,
            visualDensity: VisualDensity.standard,
          );
```


@darrenaustin, about `colorSchemeSeed`, it also does one perhaps controversial thing, it assigns `ColorScheme.outline` to `ThemeData.dividerColor`. This results in a very prominent looking divider color that does not looks so nice anywhere. I wonder if it is correct for M3 as its general divider color? M3 spec seems a bit "divided" on this too.

The Divider color is not yet explicitly specified in M3 as its own element (at least not as far as I could find), but e.g. in PopupMenu spec (https://m3.material.io/components/menus/specs) we can see a divider and it uses `ColorScheme.surfaceVariant` which is neutral-variant90/30 (in light/dark), this is much less prominent. `ColorScheme.outline` is typically used as outline on buttons and cards, and `outline` is is defined as neutral-variant50/60 (in light/dark). However, if you look at Navigation drawer, its spec  https://m3.material.io/components/navigation-drawer/specs) uses `outline`, so yes M3 varies on this.

Both colors are actually challenging options as a general divider color, since neither will work well on an arbitrary color. They really only work on the theme surface color, to work on any color, it kind of needs to be more like M2, totally or mostly black and white based, with opacity, but not a big problem since you can theme it that way still.

**Comment by guidezpl** [comment] 2023-02-06 08:39
This highlights one of the issues with `ThemeData.xColor` properties. For the outline, I believe the default is `outlineVariant` but some components use other colors. Since I don't believe there is further work to be done here, I'll close this issue. I'll provide an update on https://github.com/flutter/flutter/issues/91772

**Closed by guidezpl** 2023-02-06 08:39 UTC
Labels: framework, f: material design, has reproducible steps, found in release: 3.0, found in release: 3.1

**Comment by rydmike** [comment] 2023-02-06 22:44
@guidezpl the Outline color on the the DividerColor def is just plain wrong, probably an old call made before the spec was out.

Made an issue about it as well
https://github.com/flutter/flutter/issues/117755

But if you are finally killing all/most of the ThemeData colors then it won't matter after that anymore, as it will need to be fixed as a part of it anyway.

**Comment by guidezpl** [comment] 2023-02-07 10:01
I believe that's what happened. Thanks for filing an issue, will get back to it once these final `ThemeData` colors are finally gone
