### ISSUE TITLE
PlatformException(multiple_request, Cancelled by a second request, null, null)

### ISSUE THREAD

**Issue by syedmuhammadwaqas** [flutter/flutter#101806] opened 2022-04-13 06:29 UTC
![Simulator Screen Shot - iPhone 12 - 2022-04-13 at 11 27 38](https://user-images.githubusercontent.com/12509364/163113812-c7c8b572-bb31-4eb5-a0cb-3da379342db3.png)

This is example app https://pub.dev/packages/image_picker
image_picker: ^0.8.5

**Comment by syedmuhammadwaqas** [comment] 2022-04-13 06:35
![Simulator Screen Shot - iPhone 12 - 2022-04-13 at 11 34 56](https://user-images.githubusercontent.com/12509364/163114769-b8888796-45f5-483a-a5af-40151b8fcacc.png)

Not able to select first picture. (Top Left)

**Comment by danagbemava-nc** [comment] 2022-04-13 06:58
Duplicate of #82602

**Closed by danagbemava-nc** 2022-04-13 06:58 UTC
Labels: in triage
