### ISSUE TITLE
iOS tools: `install` should run `build` as necessary

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#4164] opened 2016-05-24 22:09 UTC
Running `flutter install` on a device without having run `flutter build ios` first, reports a successful install although it does nothing.  We should just run `build` on demand.

@devoncarew

**Comment by devoncarew** [comment] 2016-05-26 16:01
We'll need to split the notion of building ios apps out from the startApp() method. For the android workflow, building and running are separate tasks; for ios, it's currently all handled by the startApp() methods.

**Comment by Hixie** [comment] 2017-01-30 04:42
dupe of https://github.com/flutter/flutter/issues/4508

**Closed by Hixie** 2017-01-30 04:42 UTC
Labels: dev: tool, new feature, ⌺‬ platform-ios
