### ISSUE TITLE
Enable/Disable Copy/Paste Functionality in TextField

### ISSUE THREAD

**Issue by Harishpenta** [flutter/flutter#132191] opened 2023-08-09 06:11 UTC
### Is there an existing issue for this?

- [x] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

Security and Data Entry Control: Many applications deal with sensitive information, and there are cases where users should be allowed to input data manually but restricted from copying or pasting it. For instance, password fields, one-time code inputs, and other sensitive data forms can benefit from having the ability to selectively disable copy/paste.

Guided User Experience: In some instances, applications guide users through a step-by-step process. Preventing copy/paste during specific steps can ensure users interact with the content as intended, preventing errors and enhancing the guided experience.

Preventing Plagiarism: In educational or content creation apps, developers may want to restrict copying of content from a TextField to prevent plagiarism or unauthorized use of the entered text.

### Proposal

Introducing a parameter or property in the TextField widget that allows developers to control the copy/paste functionality can provide greater flexibility. This parameter could be a boolean value like enableCopyPaste that defaults to true, ensuring backward compatibility while enabling developers to customize this behavior. When enableCopyPaste is set to false, the copy and paste actions would be disabled, providing a secure and controlled environment for user input.

  ```
       TextField(
          enableCopyPaste: false,
          controller: myController,
          // Other properties...
        )
```
        
        
Enhanced User Experience: Developers can provide more precise control over text input interactions, improving the user experience in various scenarios.
Increased Security: Sensitive data can be entered manually without the risk of it being copied or pasted, adding an additional layer of security.
Diverse Application Use: The feature caters to a wide range of applications, from financial apps to educational platforms, where data integrity and controlled interaction matter.

**Comment by LaPyaeOo** [comment] 2023-08-09 07:27
Hello Mr @Harishpenta , this function is already include in flutter text field.

Here is the example code

```
TextField(
  toolbarOptions: ToolbarOptions(
    copy:false,
    paste: false,
    cut: false,
    selectAll: true
  ),
)
```
Is this the function that you want?
Please write in the comments for further discussion. Thanks!

**Comment by Harishpenta** [comment] 2023-08-09 09:13
I think this is deprecated :
<img width="1215" alt="Screenshot 2023-08-09 at 2 42 46 PM" src="https://github.com/flutter/flutter/assets/6199112/cb5b5952-636c-4bc9-a440-832d8e2911d9">

**Comment by LaPyaeOo** [comment] 2023-08-09 09:56
Yep, for deprecation. I found they use ```contextMenuBuilder``` instead of this.
Here is about the documentation of [contextMenuBuilder](https://api.flutter.dev/flutter/material/TextField/contextMenuBuilder.html). I suppose it should be as you want.

**Comment by dam-ease** [comment] 2023-08-09 10:49
Thanks for your input @LaPyaeOo. Hi @Harishpenta, thanks for proposing this, this already exists with flutter as mentioned with `toolbarOptions` and since it has been depreciated, you can make use of [contextMenuBuilder](https://api.flutter.dev/flutter/material/TextField/contextMenuBuilder.html) instead.
Thank you! 
Closing this as invalid, if you disagree, kindly comment and I'd reopen this.

**Closed by dam-ease** 2023-08-09 10:49 UTC
Labels: in triage

**Comment by Harishpenta** [comment] 2023-08-09 11:43
@dam-ease i have used the following code snippet using `contextMenuBuilder`

```
            contextMenuBuilder:
                (BuildContext context, EditableTextState editableTextState) {
              return AdaptiveTextSelectionToolbar.editable(
                anchors: editableTextState.contextMenuAnchors,
                clipboardStatus: ClipboardStatus.notPasteable,
                // to apply the normal behavior when click on copy (copy in clipboard close toolbar)
                // use an empty function `() {}` to hide this option from the toolbar
                onCopy: () => editableTextState
                    .copySelection(SelectionChangedCause.toolbar),
                // to apply the normal behavior when click on cut
                onCut: () => editableTextState
                    .cutSelection(SelectionChangedCause.toolbar),
                onPaste: () {
                  // HERE will be called when the paste button is clicked in the toolbar
                  // apply your own logic here

                  // to apply the normal behavior when click on paste (add in input and close toolbar)
                  editableTextState.pasteText(SelectionChangedCause.tap);
                },
                // to apply the normal behavior when click on select all
                onSelectAll: () =>
                    editableTextState.selectAll(SelectionChangedCause.toolbar),
              );
            },
```

but still i am not able to prevent copy/paste

**Comment by LaPyaeOo** [comment] 2023-08-09 18:25
Hello @Harishpenta, you may missing something in your project. I reproduced and test as code snippet from documentation. It really work and fine.
It work, although run with flutter version 3.10.5.
```flutter doctor -v```
```
[✓] Flutter (Channel stable, 3.10.5, on macOS 13.2.1 22D68 darwin-x64, locale en-US)
    • Flutter version 3.10.5 on channel stable at /Users/innolab/fvm/versions/3.10.5
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (8 weeks ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/innolab/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.81.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.70.0

[✓] Connected device (3 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • macOS (desktop)                    • macos         • darwin-x64     • macOS 13.2.1 22D68 darwin-x64
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 115.0.5790.170

[✓] Network resources
    • All expected network resources are available.

• No issues found!
````
Here is my code that run inside ```build()``` method and with working playback video.
I think so, you should check and reproduce again.

```
Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: TextField(
          decoration: InputDecoration(hintText: 'Hello World'),
          contextMenuBuilder:(BuildContext context,
              EditableTextState editableTextState){
            return AdaptiveTextSelectionToolbar(
              anchors: editableTextState.contextMenuAnchors,
              // Build the default buttons, but make them look custom.
              // In a real project you may want to build different
              // buttons depending on the platform.
              children: editableTextState.contextMenuButtonItems
                  .map((ContextMenuButtonItem buttonItem) {
                return CupertinoButton(
                  borderRadius: null,
                  color: const Color(0xffaaaa00),
                  disabledColor: const Color(0xffaaaaff),
                  onPressed: buttonItem.onPressed,
                  padding: const EdgeInsets.all(10.0),
                  pressedOpacity: 0.7,
                  child: SizedBox(
                    width: 200.0,
                    child: Text(
                      CupertinoTextSelectionToolbarButton.getButtonLabel(
                          context, buttonItem),
                    ),
                  ),
                );
              }).toList(),
            );
          }
        ),
      ),
    );
  }
```

https://github.com/flutter/flutter/assets/39775137/e0690b50-f462-4213-9fa7-99e8567ca1fc

**Comment by dam-ease** [comment] 2023-08-14 09:13
Hi @Harishpenta. Here is an example:

```dart
Scaffold(
        appBar: AppBar(
          title: const Text('Custom button appearance'),
        ),
        body: Center(
          child: Column(
            children: <Widget>[
              const SizedBox(height: 20.0),
              TextField(
                controller: _controller,
                contextMenuBuilder: (context, editableTextState) {
                  final List<ContextMenuButtonItem> buttonItems =
                      editableTextState.contextMenuButtonItems;
                  buttonItems.removeWhere((ContextMenuButtonItem buttonItem) {
                    return buttonItem.type == ContextMenuButtonType.copy;
                  });
                  return AdaptiveTextSelectionToolbar.buttonItems(
                    anchors: editableTextState.contextMenuAnchors,
                    buttonItems: buttonItems,
                  );
                },
              ),
            ],
          ),
        ),
      )
```
