### ISSUE TITLE
Sample ID is missing from comments written into samples

### ISSUE THREAD

**Issue by DanTup** [flutter/flutter#36184] opened 2019-07-15 09:32 UTC
If you run `flutter create -s material.IconButton.1 my_sample` then open up `lib/main.dart` it contains this comment at the top:

```dart
// Flutter code sample for

// This sample shows an `IconButton` that uses the Material icon "volume_up" to
// increase the volume.
```

The first line used to have the ID of the sample on the end (and still does on the website), but it's missing here. I think it's fairly recent because it caused Dart-Code test failures (we search for that text to ensure the samples were created correctly) and I only noticed them this weekend.

@gspencergoog do you have any ideas what might have caused this? I couldn't find the code that did these replacements (for ex. if I search the Flutter repo for `code-preamble` which is one of the tokens, I only find templates with it in, and not code that does replacing).

**Comment by DanTup** [comment] 2019-07-15 09:32
Also - this seems to happen on stable, but the docs on the website *do* have the ID in the comment 🤔

**Comment by DanTup** [comment] 2019-07-15 09:40
Hmmm, I'm not sure why my tests are failing on stable, as this file looks good:

https://api.flutter.dev/snippets/material.IconButton.1.dart

This file looks bad:

https://master-api.flutter.dev/snippets/material.IconButton.1.dart

Probably the issue only exists on master - I'll do more debugging of my tests.

**Comment by kf6gpe** [comment] 2020-01-06 17:37
I can't reproduce this on 1.12. I'm going to close this, and we can re-open it if I'm wrong.

**Closed by kf6gpe** 2020-01-06 17:37 UTC
Labels: tool

**Comment by DanTup** [comment] 2020-01-07 13:08
Yeah, looks fine to me too. Thanks!

**Comment by gspencergoog** [comment] 2020-01-07 17:31
Yeah, I fixed this a while ago.
