### ISSUE TITLE
When entering Chinese character,TextField the cursor is not aligned

### ISSUE THREAD

**Issue by QueryStyle** [flutter/flutter#30262] opened 2019-03-31 06:32 UTC
## Steps to Reproduce

When entering Chinese character,TextField the cursor is not aligned

![123](https://user-images.githubusercontent.com/35294630/55285592-87951a00-53c1-11e9-845b-be7aa95e9914.png)

## flutter doctor -v
```
[√] Flutter (Channel dev, v1.4.7, on Microsoft Windows [Version 10.0.17134.556], locale zh-CN)
    • Flutter version 1.4.7 at G:\Flutter\flutter
    • Framework revision 1bfa2f2311 (2 days ago), 2019-03-29 10:05:18 -0700
    • Engine revision c4d14a0071
    • Dart version 2.2.1 (build 2.2.1-dev.2.0 None)


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at E:\SDK
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = E:\SDK
    • Java binary at: D:\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.3)
    • Android Studio at D:\Android\Android Studio
    • Flutter plugin version 34.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[√] VS Code (version 1.32.3)
    • VS Code at C:\Users\21481\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 2.25.0

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!
```

**Comment by justinmc** [comment] 2019-04-01 18:12
You're right, I was just able to reproduce this using a simple TextField.

I'm going to close this because we have two similar issues currently open. You can keep track of progress over there:
https://github.com/flutter/flutter/issues/24182
https://github.com/flutter/flutter/issues/23934

I'm hoping to have some time to take a look at this soon, but PRs are always welcome :wink:

**Closed by justinmc** 2019-04-01 18:12 UTC
Labels: a: text input, f: material design, framework
