### ISSUE TITLE
flutter ugrade just nuked my uncommitted changes

### ISSUE THREAD

**Issue by ryanheise** [flutter/flutter#30234] opened 2019-03-30 04:17 UTC
(Apologies for the sensationalist headline, but this really did happen, and so I think it would benefit flutter users at large to get this issue some attention quickly.)

## Steps to Reproduce

1. Have a flutter project with uncommitted git code
2. Be on the beta channel (flutter channel beta) - edit: Actually I was on the dev channel
3. Run "flutter upgrade" from within your project directory
4. Watch as flutter upgrade checks out the master branch over the top of your hard work.

I happened to have one file still open in my editor while I ran "flutter upgrade" and the editor told me moments after running "flutter upgrade" that my file had been changed on disk and asked me if I wanted to reload it from disk. I was able to say "NO" and save a copy of the buffer somewhere safe, so I've managed to rescue ONE file, but the rest is gone. I think it's clear from the timing of it that it was "flutter upgrade" that checked out the git repository in my current directory which it shouldn't have touched.

## Logs

```
$ flutter upgrade
Upgrading Flutter from /home/ryan/opt/flutter...
From https://github.com/flutter/flutter
   8e7e43570..1bfa2f231  dev             -> origin/dev
   b5700506f..89807e68d  master          -> origin/master
 * [new branch]          v1.4.5-hotfixes -> origin/v1.4.5-hotfixes
 * [new branch]          v1.4.6-hotfixes -> origin/v1.4.6-hotfixes
 * [new tag]             v1.4.0          -> v1.4.0
 * [new tag]             v1.4.1          -> v1.4.1
 * [new tag]             v1.4.2          -> v1.4.2
 * [new tag]             v1.4.3          -> v1.4.3
 * [new tag]             v1.4.4          -> v1.4.4
 * [new tag]             v1.4.6-hotfix.1 -> v1.4.6-hotfix.1
 * [new tag]             v1.4.7          -> v1.4.7
 * [new tag]             v1.4.5          -> v1.4.5
 * [new tag]             v1.4.6          -> v1.4.6
Updating 8e7e43570..1bfa2f231
 .../bin/src/main/res/mipmap-hdpi/ic_launcher.png   |  Bin 0 -> 544 bytes
 .../bin/src/main/res/mipmap-mdpi/ic_launcher.png   |  Bin 0 -> 442 bytes
 .../bin/src/main/res/mipmap-xhdpi/ic_launcher.png  |  Bin 0 -> 721 bytes
 .../bin/src/main/res/mipmap-xxhdpi/ic_launcher.png |  Bin 0 -> 1031 bytes
 .../src/main/res/mipmap-xxxhdpi/ic_launcher.png    |  Bin 0 -> 1443 bytes
 .../app/src/main/res/mipmap-hdpi/ic_launcher.png   |  Bin 0 -> 544 bytes
 .../app/src/main/res/mipmap-mdpi/ic_launcher.png   |  Bin 0 -> 442 bytes
 .../app/src/main/res/mipmap-xhdpi/ic_launcher.png  |  Bin 0 -> 721 bytes
 .../app/src/main/res/mipmap-xxhdpi/ic_launcher.png |  Bin 0 -> 1031 bytes
 .../src/main/res/mipmap-xxxhdpi/ic_launcher.png    |  Bin 0 -> 1443 bytes
 249 files changed, 5604 insertions(+), 1705 deletions(-)
Current branch dev is up to date.

Upgrading engine...
Downloading Dart SDK from Flutter engine c4d14a00716fa616b69d51bab957aee483bdc9c2...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0  118M    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
  1  118M    1 1422k    0     0  1113k      0  0:01:48  0:00:01  0:01:47 1112k
  5  118M    5 6911k    0     0  3039k      0  0:00:39  0:00:02  0:00:37 3038k
 14  118M   14 17.2M    0     0  5396k      0  0:00:22  0:00:03  0:00:19 5395k
 23  118M   23 27.8M    0     0  6671k      0  0:00:18  0:00:04  0:00:14 6669k
 32  118M   32 38.5M    0     0  7493k      0  0:00:16  0:00:05  0:00:11 9434k
 41  118M   41 49.3M    0     0  8051k      0  0:00:15  0:00:06  0:00:09 9824k
 50  118M   50 60.0M    0     0  8453k      0  0:00:14  0:00:07  0:00:07 10.6M
 60  118M   60 70.9M    0     0  8776k      0  0:00:13  0:00:08  0:00:05 10.7M
 66  118M   66 78.9M    0     0  8716k      0  0:00:13  0:00:09  0:00:04 10.2M
 75  118M   75 89.2M    0     0  8898k      0  0:00:13  0:00:10  0:00:03 10.1M
 84  118M   84 99.6M    0     0  9049k      0  0:00:13  0:00:11  0:00:02 10.0M
 93  118M   93  110M    0     0  9196k      0  0:00:13  0:00:12  0:00:01 10.0M
100  118M  100  118M    0     0  9286k      0  0:00:13  0:00:13 --:--:--  9.9M
Building flutter tool...
```

It's been stuck at this point for more than 30 minutes, so something else also appears to be wrong.

```
$ flutter doctor -v
[✓] Flutter (Channel dev, v1.4.7, on Linux, locale en_AU.UTF-8)
    • Flutter version 1.4.7 at /home/ryan/opt/flutter
    • Framework revision 1bfa2f2311 (13 hours ago), 2019-03-29 10:05:18 -0700
    • Engine revision c4d14a0071
    • Dart version 2.2.1 (build 2.2.1-dev.2.0 None)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /home/ryan/opt/android-sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /home/ryan/opt/android-sdk
    • Java binary at: /home/ryan/opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[!] Android Studio (version 3.1)
    • Android Studio at /home/ryan/opt/android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```

I generally ignore the Android Studio warnings since I do not use it.

I can't express how devastated I am since the uncommitted code was an extremely complex algorithm that I will not be able to easily rediscover or reproduce from memory.

But there is hope.

I grepped through the various build artifacts and found that remnants of my code *may* be inside `build/app.dill.incremental.dill`. Can someone point me to more information about the format of this file so that I may recover some of what was lost?

**Comment by jonahwilliams** [comment] 2019-03-30 04:46
Hi @ryanheise, this sounds really severe - if you could help me understand what went wrong that would be great.

app.incremental.dill is a binary file, but all source code should be contained within. If you open it up with a text editor you should see something like this:

```
����KQ��``?	��������!������`"`#>J����''�4+�]/�w'	M�	�����p
`0�$�)	`1�ށނ����`3+��`1+`	?���	�5��
��
�.�K�n�/!�V�n`J�\�\I�s�y��
]6`	����`7�`?	9����Ӄ\>=��.4����`:>=��.����.�=?�����!�#���1`"`#>J�@�GC�_G�vK���{.M��Q��T��X1�`#�K'�}K$����.������\����^b�%f�N.'��j��n���*/H 3H\J99q@�V���=file:///Users/jonahwilliams/Documents/examploo2/lib/main.dart��import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'asdasad
```

**Comment by jonahwilliams** [comment] 2019-03-30 04:54
Was this project was being developed in a separate git repo location, or was it developed as part of the flutter checkout?

Have you customized the FLUTTER_ROOT env variable, or do you have an unusually setup?

Also, are you using windows/linux/mac?

**Comment by ryanheise** [comment] 2019-03-30 06:13
Thank you for the quick reply, Jonah. 

To answer your questions, it's a separate flutter project (created with flutter create) with its own separate git repo. I have not customised the FLUTTER_ROOT environment variable, and I am using Linux. Now, I also have uncommitted changes in other flutter projects on the same computer, each with their own git repo, but they were unaffected. It only affected the project directory tree that I ran the flutter upgrade command in.

Regarding the app.incremental.dill file, how often is this updated? Will it have my latest changes, or is it only updated, for example, when I do a flutter run or build?

**Comment by jonahwilliams** [comment] 2019-03-30 07:03
.dill will contain the original compile that was running, .incremental.dill will contain the latest hot reloaded diff.

Do you happen to know the exact flutter version you were on when you attempted to upgrade?

**Comment by ryanheise** [comment] 2019-03-30 08:12
Unfortunately I don't recall. My previous flutter upgrade before this one was at least within the last month. Is there any file I can inspect locally to find this out?

**Comment by DanTup** [comment] 2019-03-30 08:48
> Do you happen to know the exact flutter version you were on when you attempted to upgrade?

The logs at the top (assuming they're for the run that did this) say:

> Updating 8e7e43570..1bfa2f231

**Comment by DanTup** [comment] 2019-03-30 09:00
@ryanheise you mentioned your project had its own repository, but didn't mention where it was checked out. Was it inside the same path as the Flutter SDK (`/home/ryan/opt/flutter`)?

**Comment by ryanheise** [comment] 2019-03-30 09:50
Ah, I just checked and I am indeed on the dev channel, not beta.

My own project's git repository is not nested inside of `/home/ryan/opt/flutter`. It is in an entirely separate part of my filesystem.

**Comment by DanTup** [comment] 2019-03-30 12:08
I think I can repro this...

```
cd /Users/danny/Dev/Google/flutter

git checkout dev
git reset --hard 8e7e435
flutter doctor

mkdir -p /tmp/flutter-testing
cd /tmp/flutter-testing
flutter create foo
cd foo
git init
git add .
git commit -m "initial commit"
echo "test" > test.txt
git add .

echo ==== Status before upgrade
git status

echo ==== Upgrading....
flutter upgrade

echo ==== Status before upgrade
git status
```

Output was:

```
==== Status before upgrade
On branch master
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

	new file:   test.txt

==== Upgrading....
Upgrading Flutter from /Users/danny/Dev/Google/flutter...
Updating 8e7e43570..1bfa2f231
 .../bin/src/main/res/mipmap-hdpi/ic_launcher.png   |  Bin 0 -> 544 bytes
 .../bin/src/main/res/mipmap-mdpi/ic_launcher.png   |  Bin 0 -> 442 bytes
 .../bin/src/main/res/mipmap-xhdpi/ic_launcher.png  |  Bin 0 -> 721 bytes
 .../bin/src/main/res/mipmap-xxhdpi/ic_launcher.png |  Bin 0 -> 1031 bytes
 .../src/main/res/mipmap-xxxhdpi/ic_launcher.png    |  Bin 0 -> 1443 bytes
 .../app/src/main/res/mipmap-hdpi/ic_launcher.png   |  Bin 0 -> 544 bytes
 .../app/src/main/res/mipmap-mdpi/ic_launcher.png   |  Bin 0 -> 442 bytes
 .../app/src/main/res/mipmap-xhdpi/ic_launcher.png  |  Bin 0 -> 721 bytes
 .../app/src/main/res/mipmap-xxhdpi/ic_launcher.png |  Bin 0 -> 1031 bytes
 .../src/main/res/mipmap-xxxhdpi/ic_launcher.png    |  Bin 0 -> 1443 bytes
 249 files changed, 5604 insertions(+), 1705 deletions(-)
Current branch dev is up to date.

Upgrading engine...
Downloading Dart SDK from Flutter engine c4d14a00716fa616b69d51bab957aee483bdc9c2...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0  118M    0  560k    0     0  1282k      0  0:01:34 --:--:--  0:01:34 1281k
  6  118M    6 8238k    0     0  5764k      0  0:00:21  0:00:01  0:00:20 5761k
 13  118M   13 15.4M    0     0  6455k      0  0:00:18  0:00:02  0:00:16 6453k
 19  118M   19 23.0M    0     0  6893k      0  0:00:17  0:00:03  0:00:14 6892k
 25  118M   25 29.8M    0     0  6891k      0  0:00:17  0:00:04  0:00:13 6890k
 31  118M   31 37.8M    0     0  7138k      0  0:00:17  0:00:05  0:00:12 7648k
 38  118M   38 45.0M    0     0  7159k      0  0:00:16  0:00:06  0:00:10 7558k
 44  118M   44 52.2M    0     0  7205k      0  0:00:16  0:00:07  0:00:09 7573k
 49  118M   49 58.4M    0     0  7090k      0  0:00:17  0:00:08  0:00:09 7225k
 52  118M   52 62.4M    0     0  6784k      0  0:00:17  0:00:09  0:00:08 6690k
 55  118M   55 66.2M    0     0  6491k      0  0:00:18  0:00:10  0:00:08 5793k
 57  118M   57 68.2M    0     0  6117k      0  0:00:19  0:00:11  0:00:08 4769k
 58  118M   58 69.3M    0     0  5713k      0  0:00:21  0:00:12  0:00:09 3497k
 58  118M   58 69.6M    0     0  5311k      0  0:00:22  0:00:13  0:00:09 2305k
 58  118M   58 69.8M    0     0  4935k      0  0:00:24  0:00:14  0:00:10 1485k
 58  118M   58 69.9M    0     0  4637k      0  0:00:26  0:00:15  0:00:11  756k
 59  118M   59 70.1M    0     0  4368k      0  0:00:27  0:00:16  0:00:11  374k
 59  118M   59 70.3M    0     0  4130k      0  0:00:29  0:00:17  0:00:12  198k
 59  118M   59 70.6M    0     0  3920k      0  0:00:30  0:00:18  0:00:12  194k
 59  118M   59 71.1M    0     0  3749k      0  0:00:32  0:00:19  0:00:13  271k
 60  118M   60 71.9M    0     0  3606k      0  0:00:33  0:00:20  0:00:13  410k
 62  118M   62 73.6M    0     0  3520k      0  0:00:34  0:00:21  0:00:13  729k
 65  118M   65 78.1M    0     0  3566k      0  0:00:34  0:00:22  0:00:12 1597k
 71  118M   71 84.9M    0     0  3714k      0  0:00:32  0:00:23  0:00:09 2951k
 77  118M   77 91.9M    0     0  3853k      0  0:00:31  0:00:24  0:00:07 4259k
 83  118M   83 99.5M    0     0  4008k      0  0:00:30  0:00:25  0:00:05 5650k
 90  118M   90  107M    0     0  4157k      0  0:00:29  0:00:26  0:00:03 6886k
 96  118M   96  114M    0     0  4264k      0  0:00:28  0:00:27  0:00:01 7396k
100  118M  100  118M    0     0  4337k      0  0:00:27  0:00:27 --:--:-- 7541k
Building flutter tool...
```

At that point it also hangs for me (though I think earlier while trying to build a repro it prompted me to enter my password to "install Apple Software" and I accidentally cancelled it - I think it's getting stuck there, but it's not prompting me again).

So I just Ctrl+C'd and did this:

```
^CDannys-MacBook:tmp danny$ cd /tmp/flutter-testing/foo/
Dannys-MacBook:foo danny$ git status
On branch master
nothing to commit, working tree clean
```

It seems like is has wiped out the above change shown above.

**Comment by DanTup** [comment] 2019-03-30 13:49
Ok, I think the issue is that it's `git stash`ing before the upgrade:

```
[   +1 ms] executing: git stash push -m flutter-upgrade-from-v1.3.14
[ +318 ms] Saved working directory and index state On master: flutter-upgrade-from-v1.3.14
```

@ryanheise this means your work may still be there in your projects directory, try running `git stash list`:

```
Dannys-MacBook:foo danny$ git stash list
stash@{0}: On master: flutter-upgrade-from-v1.3.14
```

If it's there, you can apply the stash by its index number:

```
Dannys-MacBook:foo danny$ git stash apply 0
On branch master
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

	new file:   test.txt
```

**Comment by ryanheise** [comment] 2019-03-30 14:46
Yes!!! Thank you so much for finding a way to recover the code. Everything was recovered :+1:

**Comment by DanTup** [comment] 2019-03-30 15:08
Glad to hear it! Really sorry for the bother. I don't know if there's a fix to be made since the code was reverted, but if it may be re-landed then it'll need some work. I'll leave commenting/closing to someone like @jonahwilliams with more context on the change.

**Comment by dnfield** [comment] 2019-03-30 17:34
We no longer stash things on master for this command.  Removing TODAY label.

**Comment by dnfield** [comment] 2019-03-30 17:52
Errr - I take it back.  We need to validate this on master since we now do a reset...

**Comment by dnfield** [comment] 2019-03-30 18:13
Verified this is all good on master - v1.3.14 is the only build affected by this, added it to bad builds.

**Comment by jonahwilliams** [comment] 2019-03-30 18:13
@ryanheise I'm really sorry about all the trouble this caused you. It was my mistake, I forgot to mark 1.3.14 as bad after we rolled back that change

**Closed by dnfield** 2019-03-30 18:13 UTC
Labels: severe: dataloss, tool, ⚠ TODAY

**Comment by ryanheise** [comment] 2019-03-31 01:20
@jonahwilliams No damage done, thanks to both you and @DanTup for helping me to recover the files.

This reminds me of the old GHC bug where the compiler would delete your source files if it detected a type error ;-)

**Comment by dnfield** [comment] 2019-03-31 03:29
I'll just leave this here .. https://github.com/munificent/vigil

**Comment by ryanheise** [comment] 2019-03-31 09:51
Haha :-)  Given Munificent's connection to Dart, Hopefully Vigil is not a secret testing ground for new Dart ideas...

Anyway, thank you @dnfield and team for the quick response to the situation.
