### ISSUE TITLE
The following assertion was thrown building OverlaySupportTheme:

### ISSUE THREAD

**Issue by Tapankumardang** [flutter/flutter#120201] opened 2023-02-07 15:28 UTC
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following assertion was thrown building OverlaySupportTheme:
'package:flutter/src/widgets/framework.dart': Failed assertion: line 5403 pos 14:
'_dependents.isEmpty': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was:
  OverlaySupportTheme
  OverlaySupportTheme:file:///home/valor/.pub-cache/hosted/pub.dev/overlay_support-2.1.0/lib/src/overlay_state_finder.dart:75:12

When the exception was thrown, this was the stack:
#2      InheritedElement.debugDeactivated.<anonymous closure> (package:flutter/src/widgets/framework.dart:5403:14)
#3      InheritedElement.debugDeactivated (package:flutter/src/widgets/framework.dart:5405:6)
#4      _InactiveElements._deactivateRecursively.<anonymous closure> (package:flutter/src/widgets/framework.dart:1982:15)
#5      _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1984:6)
#6      ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5020:14)
#7      _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1980:13)
#8      ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5020:14)
#9      _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1980:13)
#10     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5020:14)
#11     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1980:13)
#12     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5020:14)
#13     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1980:13)
#14     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5020:14)
#15     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1980:13)
#16     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5020:14)
#17     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1980:13)
#18     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6363:14)
#19     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1980:13)
#20     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6363:14)
#21     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1980:13)
#22     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5020:14)
#23     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1980:13)
#24     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5020:14)
#25     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1980:13)
#26     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5020:14)
#27     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1980:13)
#28     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6363:14)
#29     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1980:13)
#30     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5020:14)
#31     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1980:13)
#32     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5020:14)
#33     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1980:13)
#34     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5020:14)
#35     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1980:13)
#36     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5020:14)
#37     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1980:13)
#38     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5020:14)
#39     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1980:13)
#40     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5020:14)
#41     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1980:13)
#42     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5020:14)
#43     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1980:13)
#44     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5020:14)
#45     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1980:13)
#46     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5020:14)
#47     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1980:13)
#48     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5020:14)
#49     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1980:13)
#50     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5020:14)
#51     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1980:13)
#52     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5020:14)
#53     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1980:13)
#54     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5020:14)
#55     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1980:13)
#56     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5020:14)
#57     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1980:13)
#58     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6363:14)
#59     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1980:13)
#60     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5020:14)
#61     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1980:13)
#62     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5020:14)
#63     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1980:13)
#64     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5020:14)
#65     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1980:13)
#66     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5020:14)
#67     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1980:13)
#68     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5020:14)
#69     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1980:13)
#70     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6363:14)
#71     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1980:13)
#72     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5020:14)
#73     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1980:13)
#74     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5020:14)
#75     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1980:13)
#76     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5020:14)
#77     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1980:13)
#78     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6363:14)
#79     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1980:13)
#80     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5020:14)
#81     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1980:13)
#82     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5020:14)
#83     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1980:13)
#84     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5020:14)
#85     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1980:13)
#86     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5020:14)
#87     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1980:13)
#88     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5020:14)
#89     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1980:13)
#90     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6363:14)
#91     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1980:13)
#92     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5020:14)
#93     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1980:13)
#94     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5020:14)
#95     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1980:13)
#96     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5020:14)
#97     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1980:13)
#98     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5020:14)
#99     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1980:13)
#100    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5020:14)
#101    _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1980:13)
#102    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5020:14)
#103    _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1980:13)
#104    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6363:14)
#105    _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1980:13)
#106    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5020:14)
#107    _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1980:13)
#108    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5020:14)
#109    _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1980:13)
#110    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5020:14)
#111    _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1980:13)
#112    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5020:14)
#113    _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1980:13)
#114    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6363:14)
#115    _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1980:13)
#116    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5020:14)
#117    _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1980:13)
#118    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5020:14)
#119    _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1980:13)
#120    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5020:14)
#121    _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1980:13)
#122    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5020:14)
#123    _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1980:13)
#124    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5020:14)
#125    _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1980:13)
#126    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5020:14)
#127    _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1980:13)
#128    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5020:14)
#129    _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1980:13)
#130    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5020:14)
#131    _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1980:13)
#132    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5020:14)
#133    _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1980:13)
#134    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5020:14)
#135    _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1980:13)
#136    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6363:14)
#137    _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1980:13)
#138    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5020:14)
#139    _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1980:13)
#140    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5020:14)
#141    _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1980:13)
#142    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5020:14)
#143    _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1980:13)
#144    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5020:14)
#145    _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1980:13)
#146    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5020:14)
#147    _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1980:13)
#148    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5020:14)
#149    _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1980:13)
#150    _InactiveElements.add (package:flutter/src/widgets/framework.dart:1992:7)
#151    Element.deactivateChild (package:flutter/src/widgets/framework.dart:3996:30)
#152    Element._retakeInactiveElement (package:flutter/src/widgets/framework.dart:3889:14)
...     Normal element mounting (234 frames)
#386    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953:16)
#387    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6512:36)
#388    Element.updateChild (package:flutter/src/widgets/framework.dart:3682:18)
#389    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:6041:32)
#390    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6537:17)
#391    Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#392    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
#393    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5133:11)
#394    Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#395    StatefulElement.update (package:flutter/src/widgets/framework.dart:5156:5)
#396    Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#397    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
#398    Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#399    ProxyElement.update (package:flutter/src/widgets/framework.dart:5301:5)
#400    Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#401    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
#402    Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#403    ProxyElement.update (package:flutter/src/widgets/framework.dart:5301:5)
#404    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:107:11)
#405    Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#406    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
#407    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5133:11)
#408    Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#409    StatefulElement.update (package:flutter/src/widgets/framework.dart:5156:5)
#410    Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#411    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
#412    Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#413    ProxyElement.update (package:flutter/src/widgets/framework.dart:5301:5)
#414    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:107:11)
#415    Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#416    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
#417    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5133:11)
#418    Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#419    StatefulElement.update (package:flutter/src/widgets/framework.dart:5156:5)
#420    Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#421    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
#422    Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#423    ProxyElement.update (package:flutter/src/widgets/framework.dart:5301:5)
#424    Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#425    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
#426    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5133:11)
#427    Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#428    StatefulElement.update (package:flutter/src/widgets/framework.dart:5156:5)
#429    Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#430    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6384:14)
#431    Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#432    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6384:14)
#433    Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#434    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
#435    Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#436    ProxyElement.update (package:flutter/src/widgets/framework.dart:5301:5)
#437    Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#438    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
#439    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5133:11)
#440    Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#441    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2743:19)
#442    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:863:21)
#443    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:381:5)
#444    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1289:15)
#445    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1218:9)
#446    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1076:5)
#447    _invoke (dart:ui/hooks.dart:145:13)
#448    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:338:5)
#449    _drawFrame (dart:ui/hooks.dart:112:31)
(elided 2 frames from class _AssertionError)

═════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by chrisbobbe** [comment] 2023-02-07 18:59
This looks like a duplicate of #120200.

**Comment by darshankawar** [comment] 2023-02-08 06:42
Closing as self-duplicate of https://github.com/flutter/flutter/issues/120200. Please don't file multiple issues for same error.

**Closed by darshankawar** 2023-02-08 06:42 UTC
Labels: in triage
