### ISSUE TITLE
[tool_crash] SentinelException

### ISSUE THREAD

**Issue by pulstar** [flutter/flutter#83446] opened 2021-05-26 21:56 UTC
## Command
```
flutter --no-color run --machine --track-widget-creation --device-id=1100021017146070 --start-paused --web-port=5000 --dart-define=FLUTTER_WEB_USE_SKIA=true --dart-define=flutter.inspector.structuredErrors=true --devtools-server-address=http://127.0.0.1:9103 lib\main.dart
```

## Steps to Reproduce
Crash occurred in hot restart.

## Logs
SentinelException
```

```
```
[✓] Flutter (Channel stable, 2.0.6, on Microsoft Windows [versÃ£o 10.0.19042.985], locale pt-BR)
    • Flutter version 2.0.6 at C:\src\flutter
    • Framework revision 1d9032c7e1 (4 weeks ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\pulst\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\pulst\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✗] Visual Studio - develop for Windows
    ✗ Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[✓] Connected device (5 available)
    • Grand XL LTE (mobile) • 1100021017146070 • android-arm    • Android 7.0 (API 24)
    • Vivo XI (mobile)      • PRUCHYWGG6HYSK4H • android-arm    • Android null (API null)
    • Windows (desktop)     • windows          • windows-x64    • Microsoft Windows [versÃ£o 10.0.19042.985]
    • Chrome (web)          • chrome           • web-javascript • Google Chrome 90.0.4430.212
    • Edge (web)            • edge             • web-javascript • Microsoft Edge 90.0.818.56

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 2.0.0+12
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 1d9032c7e1d867f071f2277eb1673e8f9b0274e3
### Plugins
audioplayers-0.18.3
battery-2.0.1
cloud_firestore-1.0.7
cloud_firestore_web-1.0.7
cloud_functions-1.0.7
cloud_functions_web-4.0.6
connectivity-3.0.3
connectivity_for_web-0.4.0
connectivity_macos-0.2.0
device_info-2.0.0
file_picker-3.0.1
firebase_analytics-8.0.4
firebase_analytics_web-0.3.0+1
firebase_auth-1.1.4
firebase_auth_web-1.1.2
firebase_core-1.1.1
firebase_core_web-1.0.3
firebase_dynamic_links-2.0.3
firebase_messaging-9.1.4
firebase_messaging_web-1.0.7
firebase_performance-0.7.0+2
firebase_storage-8.0.6
firebase_storage_web-1.0.6
flutter_barcode_scanner-2.0.0
flutter_country_picker-0.1.6
flutter_inappwebview-5.3.2
flutter-incall-manager-9b9bc66528e681663b685cefdcd13b23d78f39dc
flutter_isolate-2.0.0
flutter_keyboard_visibility-5.0.1
flutter_keyboard_visibility_web-2.0.0
flutter_plugin_android_lifecycle-2.0.1
flutter_ringtone_player-3.0.0
flutter_webrtc-0.6.3
flutter_webview_plugin-0.3.11
fluttertoast-8.0.6
geolocator-7.0.3
geolocator_web-2.0.3
get_ip-0.4.0
google_api_headers-1.0.0
google_maps_flutter-2.0.3
google_sign_in-5.0.2
google_sign_in_web-0.10.0
image_cropper-1.4.0
image_gallery_saver-1.6.9
image_picker-0.7.4
image_picker_for_web-2.0.0
location-4.1.1
location_web-3.0.0
package_info-2.0.0
package_info_plus-1.0.1
package_info_plus_macos-1.1.1
package_info_plus_web-1.0.1
path_provider-2.0.1
path_provider_linux-2.0.0
path_provider_macos-2.0.0
path_provider_windows-2.0.1
permission_handler-6.1.3
screen-0.0.5
share_extend-2.0.0
shared_preferences-2.0.5
shared_preferences_linux-2.0.0
shared_preferences_macos-2.0.0
shared_preferences_web-2.0.0
shared_preferences_windows-2.0.0
sqflite-2.0.0+3
system_shortcuts-1.0.0
url_launcher-6.0.3
url_launcher_linux-2.0.0
url_launcher_macos-2.0.0
url_launcher_web-2.0.0
url_launcher_windows-2.0.0
video_player-2.1.1
video_player_web-2.0.0
volume-1.0.1
wallpaper_manager-1.0.10
wifi_info_flutter-2.0.0

Flutter crash report.
Please report a bug at https://github.com/flutter/flutter/issues.

## command

flutter --no-color run --machine --track-widget-creation --device-id=1100021017146070 --start-paused --web-port=5000 --dart-define=FLUTTER_WEB_USE_SKIA=true --dart-define=flutter.inspector.structuredErrors=true --devtools-server-address=http://127.0.0.1:9103 lib\main.dart

## exception

SentinelException: [Sentinel type: Sentinel, kind: Collected, valueAsString: <collected>] from ext.flutter.activeDevToolsServerAddress()

```
```

## flutter doctor

```
[✓] Flutter (Channel stable, 2.0.6, on Microsoft Windows [versÃ£o 10.0.19042.985], locale pt-BR)
    • Flutter version 2.0.6 at C:\src\flutter
    • Framework revision 1d9032c7e1 (4 weeks ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\pulst\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\pulst\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✗] Visual Studio - develop for Windows
    ✗ Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[✓] Connected device (5 available)
    • Grand XL LTE (mobile) • 1100021017146070 • android-arm    • Android 7.0 (API 24)
    • Vivo XI (mobile)      • PRUCHYWGG6HYSK4H • android-arm    • Android null (API null)
    • Windows (desktop)     • windows          • windows-x64    • Microsoft Windows [versÃ£o 10.0.19042.985]
    • Chrome (web)          • chrome           • web-javascript • Google Chrome 90.0.4430.212
    • Edge (web)            • edge             • web-javascript • Microsoft Edge 90.0.818.56

! Doctor found issues in 1 category.
```

Flutter crash report.
Please report a bug at https://github.com/flutter/flutter/issues.

## command

flutter --no-color run --machine --track-widget-creation --device-id=1100021017146070 --start-paused --web-port=5000 --dart-define=FLUTTER_WEB_USE_SKIA=true --dart-define=flutter.inspector.structuredErrors=true --devtools-server-address=http://127.0.0.1:9103 lib\main.dart

## exception

SentinelException: [Sentinel type: Sentinel, kind: Collected, valueAsString: <collected>] from ext.flutter.activeDevToolsServerAddress()

```
```

## flutter doctor

```
[✓] Flutter (Channel stable, 2.0.6, on Microsoft Windows [versÃ£o 10.0.19042.985], locale pt-BR)
    • Flutter version 2.0.6 at C:\src\flutter
    • Framework revision 1d9032c7e1 (4 weeks ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\pulst\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\pulst\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✗] Visual Studio - develop for Windows
    ✗ Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[✓] Connected device (5 available)
    • Grand XL LTE (mobile) • 1100021017146070 • android-arm    • Android 7.0 (API 24)
    • Vivo XI (mobile)      • PRUCHYWGG6HYSK4H • android-arm64  • Android 9 (API 28)
    • Windows (desktop)     • windows          • windows-x64    • Microsoft Windows [versÃ£o 10.0.19042.985]
    • Chrome (web)          • chrome           • web-javascript • Google Chrome 90.0.4430.212
    • Edge (web)            • edge             • web-javascript • Microsoft Edge 90.0.818.56

! Doctor found issues in 1 category.
```

**Comment by darshankawar** [comment] 2021-05-27 08:16
Closing this as duplicate of https://github.com/flutter/flutter/issues/78214

**Closed by darshankawar** 2021-05-27 08:16 UTC
Labels: in triage
