### ISSUE TITLE
hot reload on save with the flutter run CLI tool

### ISSUE THREAD

**Issue by NANASHI0X74** [flutter/flutter#75512] opened 2021-02-05 15:59 UTC
## Use case
It's convenient to have hot reload on save and not have to switch back and forth between a terminal and an editor, but it seems like support for this is only provided via plugins for specific IDEs.
Why not incorporate watching input files and reloading on changes into the CLI? It seems to make more sense than to implement that separately for each "officially supported" editor/IDE or leave users to hack together their own shell scripts to the same end. While some web frameworks do this by default, why doesn't flutter have this option?
## Proposal
flutter run should watch input files for changes and automatically hot reload when a change occurs. Maybe a commond-line switch would make sense to turn this on/off and/or this could be toggled via typing in some character to a running flutter run process, like which is already being done with e.g. i for toggling the inspector

**Comment by christopherfujino** [comment] 2021-02-05 20:20
duplicate of https://github.com/flutter/flutter/issues/62679

**Closed by christopherfujino** 2021-02-05 20:20 UTC

**Comment by NANASHI0X74** [comment] 2021-02-05 22:54
thanks for pointing me there, I somehow couldn't find that issue when searching
