### ISSUE TITLE
SliverAppBar expands when TextField focused

### ISSUE THREAD

**Issue by karabaralex** [flutter/flutter#34028] opened 2019-06-07 02:41 UTC
```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: CustomScrollView(slivers: <Widget>[
          SliverAppBar(pinned: true, expandedHeight: 200,flexibleSpace: FlexibleSpaceBar(title: Container(color: Colors.white,width: 100,child: TextField()),),),
          SliverFillRemaining(child: Container(color: Color(0xffacdfdf),),)
        ],),
      ),
    );
  }
}

```

Steps:
1. start app with code above
2. scroll up so that App Bar become collapsed
3. tap on TextField

Actual: App bar expands
Expected: App bar does not expand, TextField get focus
Repros for both Android and iOS
It looks like CustomScrollView scrolls when TextField get focus. I tried resizeToAvoidBottomInset flag and I tried with of without software/hardware keyboards on simulator. 

## Logs

```
Analyzing flutter_test_app...                                           
No issues found! (ran in 1.7s)
```

```
[✓] Flutter (Channel dev, v1.7.2, on Mac OS X 10.14.5 18F132, locale en-US)
    • Flutter version 1.7.2 at /usr/local/Caskroom/flutter/1.0.0/flutter
    • Framework revision b3b6d03737 (2 days ago), 2019-06-04 19:25:55 -0400
    • Engine revision 86aa01442b
    • Dart version 2.3.2 (build 2.3.2-dev.0.0 b080e7c97a)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/asazonov/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/asazonov/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • CocoaPods version 1.5.3

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 36.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[!] IntelliJ IDEA Ultimate Edition (version 2017.2.5)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] IntelliJ IDEA Community Edition (version 2018.2.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 31.3.3
    • Dart plugin version 182.5124

[!] VS Code (version 1.34.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • Android SDK built for x86 • emulator-5558                        • android-x86 • Android 9 (API 28) (emulator)
    • iPhone Xʀ                 • A281A1AC-7003-4BA7-BE04-126B22314151 • ios         • com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)

! Doctor found issues in 2 categories.

```

**Comment by justinmc** [comment] 2019-06-07 22:36
I can reproduce this, looks like something that should be fixed to me.

**Comment by localpcguy** [comment] 2019-06-11 15:35
I think the underlying issue may be a duplicate of #25507 (just a slightly different visual effect). The key line I think is this:
> It looks like CustomScrollView scrolls when TextField get focus.

**Comment by VladyslavBondarenko** [comment] 2020-04-22 14:06
Thanks @localpcguy 

@karabaralex please follow up on https://github.com/flutter/flutter/issues/25507
I'm closing the current one as duplicate.
If you disagree please write in the comments and I will reopen it.
Thank you

**Closed by VladyslavBondarenko** 2020-04-22 14:06 UTC
Labels: f: material design, f: scrolling, framework
