### ISSUE TITLE
[tool_crash] ProcessException: Failed to find "git" in the search path. Command: git, OS error code: 0

### ISSUE THREAD

**Issue by Nabad15** [flutter/flutter#152455] opened 2024-07-28 18:23 UTC
## Command
```
flutter create --template app --overwrite .
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ProcessException: Failed to find "git" in the search path. Command: git, OS error code: 0
```
#0      LocalProcessManager.runSync (package:process/src/interface/local_process_manager.dart:118:7)
#1      ErrorHandlingProcessManager.runSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:719:24)
#2      _runSync (package:flutter_tools/src/base/error_handling_io.dart:595:14)
#3      ErrorHandlingProcessManager.runSync (package:flutter_tools/src/base/error_handling_io.dart:718:12)
#4      _runSync (package:flutter_tools/src/version.dart:852:56)
#5      _gitCommitDate (package:flutter_tools/src/version.dart:436:12)
#6      FlutterVersion.checkFlutterVersionFreshness (package:flutter_tools/src/version.dart:279:49)
#7      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:335:40)
<asynchronous suspension>
#8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#9      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:308:5)
<asynchronous suspension>
#10     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:130:9)
<asynchronous suspension>
#11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#12     main (package:flutter_tools/executable.dart:93:3)
<asynchronous suspension>
```
```
[☠] Flutter (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    ✗ ProcessException: Failed to find "git" in the search path.
        Command: git 
    • #0      LocalProcessManager.runSync (package:process/src/interface/local_process_manager.dart:118:7)
      #1      ErrorHandlingProcessManager.runSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:719:24)
      #2      _runSync (package:flutter_tools/src/base/error_handling_io.dart:595:14)
      #3      ErrorHandlingProcessManager.runSync (package:flutter_tools/src/base/error_handling_io.dart:718:12)
      #4      _DefaultProcessUtils.runSync (package:flutter_tools/src/base/process.dart:418:51)
      #5      _runGit (package:flutter_tools/src/version.dart:873:23)
      #6      FlutterVersion.frameworkAge (package:flutter_tools/src/version.dart:220:30)
      #7      FlutterValidator.validate (package:flutter_tools/src/doctor.dart:576:17)
      #8      Doctor.startValidatorTasks.<anonymous closure> (package:flutter_tools/src/doctor.dart:273:72)
      #9      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      #10     _rootRun (dart:async/zone.dart:1399:13)
      #11     _CustomZone.run (dart:async/zone.dart:1301:19)
      #12     _runZoned (dart:async/zone.dart:1826:10)
      #13     runZonedGuarded (dart:async/zone.dart:1814:12)
      #14     runZoned (dart:async/zone.dart:1760:12)
      #15     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #16     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:265:9)
      #17     DoctorText._validatorTasks (package:flutter_tools/src/doctor.dart:794:60)
      #18     DoctorText._validatorTasks (package:flutter_tools/src/doctor.dart)
      #19     DoctorText._runDiagnosis (package:flutter_tools/src/doctor.dart:798:53)
      #20     DoctorText.text (package:flutter_tools/src/doctor.dart:790:36)
      #21     DoctorText.text (package:flutter_tools/src/doctor.dart)
      #22     _createLocalCrashReport (package:flutter_tools/runner.dart:273:51)
      #23     _handleToolError (package:flutter_tools/runner.dart:235:31)
      <asynchronous suspension>
      #24     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
      <asynchronous suspension>
      #25     main (package:flutter_tools/executable.dart:93:3)
      <asynchronous suspension>


[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✗] Visual Studio - develop Windows apps
    ✗ Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[✓] VS Code (version 1.91.1)
    • VS Code at C:\Users\ayada\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.92.0

[✓] Connected device (2 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [version 10.0.19045.4651]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 127.0.6533.72

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 4 categories.

```

## Flutter Application Metadata
No pubspec in working directory.

**Comment by Nabad15** [comment] 2024-07-28 18:47
how to fix this problem

**Comment by danagbemava-nc** [comment] 2024-07-29 08:01
Closing this as a duplicate of https://github.com/flutter/flutter/issues/133585

Please make sure you have git installed on your system and it is available in your path

**Closed by danagbemava-nc** 2024-07-29 08:01 UTC
