### ISSUE TITLE
Floating SliverAppBar stops floating when center property is used on parent CustomScrollView

### ISSUE THREAD

**Issue by cyclotron3k** [flutter/flutter#132841] opened 2023-08-18 12:54 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

A floating `SliverAppBar` can be revealed by scrolling upwards, regardless of where you are in the list.

But if the `center` property of the parent `CustomScrollView` is used, then the floating property is seemingly disabled and the `SliverAppBar` only appears at the top of the list, which in the case of an infinitely long list means it's never visible.

See code sample below.

### Expected results

A floating `SliverAppBar` should be revealed by scrolling upwards.

### Actual results

It is not visible.

### Code sample

<details><summary>Code sample</summary>

```dart

import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {

  @override
  Widget build(BuildContext context) {
    
    Widget infiniteReverseList = SliverList.builder(
      itemBuilder: (BuildContext context, int index) => Text("Reverse $index"),
    );
    
    Key infiniteForwardListKey = UniqueKey();
    
    Widget infiniteForwardList = SliverList.builder(
      key: infiniteForwardListKey,
      itemBuilder: (BuildContext context, int index) => Text("Forward $index"),
    );

    return Scaffold(
      body: CustomScrollView(
        center: infiniteForwardListKey,
        slivers: [
          const SliverAppBar(
            title: Text('Sliver App Bar'),
            floating: true,
          ),
          infiniteReverseList,
          infiniteForwardList,
        ],
      ),
    );
  }
}
```
</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.13.0, on Ubuntu 22.04.3 LTS 6.2.0-26-generic, locale en_AU.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[!] Android Studio (version unknown)
    ✗ Unable to determine Android Studio version.
[✓] VS Code (version unknown)
    ✗ Unable to determine VS Code version.
[✓] Connected device (3 available)
[✓] Network resources

```

</details>

**Comment by dam-ease** [comment] 2023-08-18 14:11
Hi @cyclotron3k. Thanks for filing this issue. I see there is a currently open issue describing this issue. Closing this as a duplicate of https://github.com/flutter/flutter/issues/122169, kindly upvote, comment and follow up on the issue for updates.

**Closed by dam-ease** 2023-08-18 14:11 UTC
Labels: in triage

**Comment by cyclotron3k** [comment] 2023-08-18 15:10
Opps didn't see that one 😳

Thanks for triaging @dam-ease
