### ISSUE TITLE
Expose `clipBehavior` and `clipStrategy` (never, whenOverflowing, always) on viewports

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#27041] opened 2019-01-24 18:43 UTC
Internal: b/123345700

I see that https://github.com/flutter/flutter/issues/12618 is closed now but I see something similar with the following code:

```dart

import 'package:flutter/material.dart';
 
void main() => runApp(MyApp());
 
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}
 
class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
 
  final String title;
 
  @override
  _MyHomePageState createState() => _MyHomePageState();
}
 
class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;
 
  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }
 
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Padding(
          padding: const EdgeInsets.all(20.0),
          child: ListView(
            children: makeMany(_counter),
          ),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ),
    );
  }
}
 
List<Widget> makeMany(int count) => List.generate(
      count,
      (i) => Padding(
            padding: EdgeInsets.only(bottom: 10),
            child: Material(
              elevation: 10,
              child: Padding(
                padding: const EdgeInsets.fromLTRB(48, 8, 48, 8),
                child: Text('$i'),
              ),
            ),
          ),
    );
```

One observation is that Shadows start getting clipped when the list starts pushing items off the viewport (e.g. if there are few items on the screen, scrolling down (bounce effect) does not lead to clipping but scrolling up (which pushes the first few items off screen) clips).

[shadow-clip.mov.gz](https://github.com/flutter/flutter/files/2793090/shadow-clip.mov.gz)

Output of doctor -v
```
Thu Jan 24(10:42)|flutter$ bin/flutter doctor -v
[✓] Flutter (Channel master, v1.1.10-pre.167, on Mac OS X 10.14.2 18C54, locale en-US)
    • Flutter version 1.1.10-pre.167 at /Users/mehmetf/github/flutter
    • Framework revision cf7441983e (40 minutes ago), 2019-01-24 10:02:38 -0800
    • Engine revision 2972c71f3a
    • Dart version 2.1.1 (build 2.1.1-dev.2.0 2e5453ddb4)

[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.0, Build version 10A255
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Connected device (1 available)
    • iPhone XS Max • B0B964FF-BDE9-474A-8E6B-C22CE94D25F0 • ios • iOS 12.0 (simulator)
```

**Comment by Hixie** [comment] 2019-01-30 00:17
This is basically working as intended: the list doesn't try to clip its children unless it has overflow, IIRC.

**Comment by Hixie** [comment] 2019-01-30 00:19
@mehmetf You can work around this by wrapping the list in a ClipRect, FWIW.

It's not clear that we would want to change this. Clips are expensive so we intentionally avoid them where possible. We could make it configurable, I guess?

**Comment by mehmetf** [comment] 2019-01-30 03:15
As long as there's a workaround and a reasonable explanation, I am fine with closing this.

I do worry that the behavior is very counter-intuitive (works until overflow then breaks spectacularly). Could we somehow detect whether the overflow will result in any artifacts due to clipping (perhaps as an assert()) and warn developers?

**Comment by akireyev** [comment] 2019-01-30 09:51
From the developer's point of view, the goal is not to get more clipping, but rather better shadows. Shadows are properties of Materials, and the framework already goes to some lengths to render them nicely. The only exception are scrolling views, which decide to clip shadows in the case of an overflow.

Clipping the shadows makes the life of a developer much more complicated, because in order to preserve them, the developer has to add padding of the correct size (how does one calculate that size?), and compensate for that padding elsewhere in the layout.

Considering that shadows are an important part of the Material Design, it would be much nicer if the framework simulated the behavior of a 3D-in-3D compositor for the shadows. Namely, the clipping, if any, should apply to the materials themselves, but the shadows should not be clipped.

**Comment by Hixie** [comment] 2019-02-06 00:19
@akireyev The problem with no clipping them is... what would it mean? Consider for example a vertical list view that takes up the bottom of half the screen. The top of the list is clearly visible half-way up the screen. You scroll something with a shadow so that it's half off the list. What should it render as? If we don't clip the list contents, I don't understand what this means.

Lists are in viewports, which by definition show a window into a bigger space. Clipping (when we believe we have overflow) seems like the logical thing. The problem if anything is that we don't clip, IMHO (though that's intentional, for performance).

How would you model a viewport / scrolling list in your 3D-in-3D compositor idea?

**Comment by Hixie** [comment] 2019-02-06 00:20
@mehmetf We have no idea that there's paint overflow unfortunately (if we did, we could clip it).

Seems reasonable that we should add more documentation.

**Comment by mehmetf** [comment] 2019-02-06 01:16
@Hixie you mentioned that we could wrap the ListView in a ClipRect. I assume that clips the children even w/o overflow so the shadows are always clipped, right? It is still not what we want but it is not surprising.

If so, what is the proper solution to this? Should we be adding horizontal padding to each child so it can display its shadow?

Another confusing part here is the definition of padding.

Typical interpretation of padding is we are enlarging the child while allowing child to draw into the enlarged space (whereas you are not allowed to draw within your margin). Since the listview is enclosed in a padding, it is assumed that the children of that listview can draw into that padding without getting clipped. I think the explanation here is that ListView itself can draw into the padding but not its children.

**Comment by akireyev** [comment] 2019-02-06 13:01
@Hixie The idea is to take inspiration from the 3D world. Materials then are like paper cards in that world. That means that the shadow is defined by the material that is higher, but belongs to the one that is lower. For clipping, in particular, it means that the clipped materials are cut by the clip box, and the result is a material of a potentially different shape.

Here's an example of how this could work in 3D-in-3D:
On the image below is the "model" of the following setup:
(left, closer) A list of 3 cards (maybe in a scroll view) is clipped by a rectangle that exactly fits card width, but is shorter that the height of the list.
(right, distant) A single card is clipped by a star shape.
![cards_boxes](https://user-images.githubusercontent.com/1964638/52334858-178d9780-2a01-11e9-8032-b177566921f7.png)
Here the clip regions can be viewed as a boxes that have the corresponding projections, when viewed from the top.

The rendering then only considers the yellow parts of the cards, and the bluish ones are ignored. The white base material, however is completely unaffected, and it's the one that contains the shadows. So the actual output looks like this:
![cards](https://user-images.githubusercontent.com/1964638/52334869-1d837880-2a01-11e9-9767-97d5523428ca.png)
Notice that in this rendering, the extent of the shadows varies with the location on the screen. Imagine a developer having to add paddings to accommodate such shadows.

One may argue that in the case of a (vertically) scrolling list, the shadows of cut items at the top and the bottom look weird. The answer is that in the actual UI design it is very unlikely that such clipping occurs without another design element covering the area past the clipped one.

I understand that Flutter is unlikely to have resources to do this kind of full 3D-in-3D composition, but it could implement some approximation. For example, materials could use their clip rect to draw themselves, but draw the shadows with the parent material's clip. Even though this is more costly, the framework can make it work faster (and more reliable) than the end-developer code with overlapping widgets with hand-crafted paddings.

**Comment by Hixie** [comment] 2019-02-06 20:57
The problem isn't lack of resources, the problem is lack of generality. We need to make sure that what we implement makes sense even if there is padding all the way around the list.

Can you draw a 3D diagram that includes an actual scrolling list with items inside it that cast shadows, and shows how those shadows end up casting outside of the viewport?

**Comment by akireyev** [comment] 2019-02-07 10:41
I am not entirely sure, what can be added to the diagrams above. The set of cards on the left is essentially a list. The black box is a tightly-fitting viewport that cuts parts of the top and the bottom cards (initially all the cards are of the same size).

In this case, the current implementation renders only the things that fall inside the red border on the image below. What I'm proposing is that it renders everything.
![cards_crop](https://user-images.githubusercontent.com/1964638/52405602-ee860900-2acb-11e9-9131-8e6c965faa94.png)

Again, most actual designs for the lists, are going to have some other boundaries -- either elements or screen bounds -- that are hiding the cropped areas at the top and the bottom of the list.
![cards_bounded](https://user-images.githubusercontent.com/1964638/52405901-baf7ae80-2acc-11e9-9bf6-f927c2609dd6.png)

If there is a specific layout that concerns you, it would really help me if you could draw it.

**Comment by mehmetf** [comment] 2019-02-07 15:11
Just to consolidate the suggestions from the internal bug, @akireyev is recommending that we provide a knob to turn off clipping unconditionally. I was worried that it might become a big foot gun requiring other workarounds. To clarify what I meant:

IIUC, turning off clipping doesn't lead to artifacts only if you have the right paint order and coverage on your entire screen by other widgets. That might be simple to control for mobile screens where listview is typically the entire content and is painted over by appbar and bottombar (as you have demonstrated in the picture above). However, if that component is included in a tablet view or desktop application, you can easily find yourself in scenarios where the entire UI is too complex to avoid overflowed list items from appearing in unintended places. The clip needs to happen somewhere and it is debatable whether it is more developer friendly to allow space for each child to draw its shadows or to create a custom clip boundary for a ListView. I personally prefer the former.

It would be up to @Hixie to see whether such a functionality should be part of the framework. It could be that you need to do this in custom widget yourself where you control exactly where the widget can be placed.

**Comment by mehmetf** [comment] 2019-02-26 23:10
Let's make a decision whether we should add a parameter to all scrollables to turn off clipping or each element in a scrollable should provide enough space for its contents (including its shadow).

I am still voting for the latter. Another reason I just thought of is that the clip behavior is infectious. If you have a child element that casts a shadow but does not provide enough padding to include it, you will need to change the clipping behavior of every parent scrollable where that child element appears.

@Hixie for the final call.

**Comment by akireyev** [comment] 2019-02-27 09:37
Mehmet's observation about the infectious behavior of no-clip is correct. My experience, however, is that with any sane UI design, this rarely reaches even 3 levels of parents. Usually it's the parent and grandparent that are causing clipping problem. On Android, where you have to explicitly disable clipping on all elements, it's rarely annoying. With Flutter's default behavior of not clipping, I suspect the most common case is going to be "disable clipping on this list view, done".

The paddings, as I have mentioned before, are much more cumbersome. First of all, the developer actually needs to know how much of a padding they need in each direction. This isn't a straighforward task, because the size of the shadow isn't documented anywhere. The other set of problems comes from the fact that paddings take part in both the layout and painting. Therefore the developer has to calculate the actual spacing between the components from the spacing between the element content -- that is usually specified in the UX design -- and the padding around each component. I argue that this is much more infectious than setting a single boolean 'clip' property on a couple of parents.

The padding approach makes tight layouts overly complicated to implement. To take an extreme example, suppose a button can have a shadow extent of 10px in one of the states (e.g. pressed). With the padding approach, placing two buttons closer than 20px to each other requires a complicated manual layout. It could work, if Flutter had something like negative margins of HTML, allowing a component to define the paint bounds that are larger than layout bounds. I'm not aware of such thing, but if it exists and not deprecated, that could be another solution.

**Comment by mehmetf** [comment] 2019-02-27 15:52
I did not mean it is infectious up the widget tree (which is also true but as you observed it only affects a couple of levels, typically). It infects to all containers a reusable element is placed. Imagine your button scenario. If this button is a reusable component in your app and 20 scrollables include it, they all have to turn their clipping off. At some point, someone is going to say: "Wait a minute. Why don't we make the clipping behavior global?" which is a dangerous proposal. This is what Ian means by a generic solution does not exist.

I totally get it by the way. This is one area that Flutter falls short of its promise: "Never say no to your designer". Designers think of elements casting shadows just like in the real world; they are just a side effect of lighting. The designs are not typically done to accommodate them. However, the reality is that real shadow implementation does not exist on Android and iOS and designers do need to think about accommodating shadows. Your button example is once again very good. Putting two elements with shadows of 10px closer than 20px will create artifacts you don't expect. For instance:
- Do you expect shadows to "blend" creating a darker shade? That's not going to happen.
- Do you expect shadow of one button to be cast onto the other button? That's not going to happen either.

UX designers need to be mindful of all this, unfortunately.

While I agree that 3D-on-3D real shadows would be very nice to have, that would be a larger discussion. Feel free to file a new issue for it. This particular issue is about whether framework should allow noclip for scrollable, I believe the answer to that is no **given the current way shadows work.**

**Comment by akireyev** [comment] 2019-02-27 19:36
I am not sure I understand the problem with a reusable element. We have an example of Android, where the scenario with 20 scrollables is a real possibility since API 21 (that added the `elevation` property and shadows). Yet I haven't heard of any attempts to change the existing clipping behavior of _clip by default, and allow to disable clipping_.

In fact, in the default case, i.e. with widgets **not** clipping, the current version of Flutter is already doing great job with shadows, including the buttons example. Here are screenshots from a Flutter app on Android that has two buttons with `highlightElevation` set to 20, and each having a padding of 8.
_(The screenshots are darkened, so that the extent of the shadows is more clear)_

When a single button is pressed, its shadow extends nicely right up to the edge of the other button. It may even overlap the button, but at such low intensity, that it doesn't really matter.
![shadow_one_crop](https://user-images.githubusercontent.com/1964638/53516097-c5a1d400-3acb-11e9-8ac6-268ea9812cb5.png)

Even in a rather unlikely case of both buttons being activated at the same time, the shadows look quite reasonable:
![shadow_two_crop](https://user-images.githubusercontent.com/1964638/53516789-6ba20e00-3acd-11e9-9201-a8edea9b8853.png)
The shadows might not blend in a physically correct way, but considering the low likelihood of this event, the result is pretty good.

This example, hopefully, shows that a _no-clip_ behavior isn't likely to create that many surprises for the developers. OTOH, as I said before, it can make their lives much easier, when it comes to implementing layouts.

**Comment by mehmetf** [comment] 2019-02-27 19:47
> at such low intensity, that it doesn't really matter.

I can't count the number of times I had argued with a UX designer what matters and what doesn't matter :-)

In any case, I leave the final call to Ian.

**Comment by Hixie** [comment] 2019-02-27 23:52
@akireyev So in your diagram, the list represents a set of 3D objects that are actually getting cut off when you scroll? You're not viewing an infinite list through a viewport, you're viewing an actual physical object that is being created like in a replicator on the side that you're scrolling towards, and being destroyed like in an emancipation grid on the side that you're scrolling away from?

That's certainly a coherent model, albeit not one I've ever heard described before. It would be distinctly non-trivial to implement.

@mehmetf Turning off clipping entirely seems very dangerous. We make no guarantees about what is going on outside the visible parts of the viewport; if we don't clip what's over there, who knows what it's going to be rendering. That said, I'm all about giving people whatever rope they want. I think it would make sense to expose `clipBehavior` (with the current options exposed on many classes, but disallowing "none" in the same way ClipRect et al do) and a new `clipStrategy` with options `never`, `whenOverflowing`, and `always`.

**Comment by akireyev** [comment] 2019-03-01 10:40
@Hixie The model of replicator + emancipation grid matches really well. I understand that a fully correct implementation of such model can get really complex and expensive. I do like the coherence of the model, so if you can think of ways the framework can help developers _simulate_ that, I would welcome them.

**Comment by mehmetf** [comment] 2019-03-01 14:27
Sounds good. @akireyev as I mentioned, it would be great for you to file a new issue for what you are proposing. I am afraid the in-between messages here will get lost.

Would you say this is going to be a blocker for you for shipping soon? I want to tag this appropriately.

**Comment by akireyev** [comment] 2019-03-01 14:56
@mehmetf This is not a blocker for anything that is shipping soon.

**Comment by timsneath** [comment] 2020-01-02 20:58
Closed as 'by design' for now, per above comments.

**Closed by timsneath** 2020-01-02 20:58 UTC
Labels: customer: dream (g3), engine, framework
