### ISSUE TITLE
Keyboard input hanging on iOS Simulator

### ISSUE THREAD

**Issue by thommy66** [flutter/flutter#96277] opened 2022-01-07 10:45 UTC
Unfortunately I cannot show code to reproduce it.

It happens every day but only if I use the simulator for a couple of hours while debugging my software. I get the following error:

```
======== Exception caught by services library ======================================================
The following assertion was thrown during a platform message callback:
A KeyUpEvent is dispatched, but the state shows that the physical key is not pressed. If this occurs in real application, please report this bug to Flutter. If this occurs in unit tests, please ensure that simulated events follow Flutter's event model as documented in `HardwareKeyboard`. This was the event: KeyUpEvent#3078e(physicalKey: PhysicalKeyboardKey#7002c(usbHidUsage: "0x0007002c", debugName: "Space"), logicalKey: LogicalKeyboardKey#00020(keyId: "0x00000020", keyLabel: " ", debugName: "Space"), character: null, timeStamp: 201:09:11.739433)
'package:flutter/src/services/hardware_keyboard.dart':
Failed assertion: line 441 pos 16: '_pressedKeys.containsKey(event.physicalKey)'


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      HardwareKeyboard._assertEventIsRegular.<anonymous closure> (package:flutter/src/services/hardware_keyboard.dart:441:16)
#3      HardwareKeyboard._assertEventIsRegular (package:flutter/src/services/hardware_keyboard.dart:452:6)
#4      HardwareKeyboard.handleKeyEvent (package:flutter/src/services/hardware_keyboard.dart:544:5)
#5      KeyEventManager.handleRawKeyMessage (package:flutter/src/services/hardware_keyboard.dart:821:35)
#6      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:77:49)
#7      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:76:47)
#8      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:389:35)
#9      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:386:46)
#10     _invoke2.<anonymous closure> (dart:ui/hooks.dart:189:15)
#14     _invoke2 (dart:ui/hooks.dart:188:10)
#15     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:42:5)
#16     _Channel.push (dart:ui/channel_buffers.dart:132:31)
#17     ChannelBuffers.push (dart:ui/channel_buffers.dart:329:17)
#18     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:544:22)
#19     _dispatchPlatformMessage (dart:ui/hooks.dart:83:31)
(elided 5 frames from class _AssertionError and dart:async)
====================================================================================================
```
It happens regularly since I installed the last XCode update and XCode command line tools update (around two weeks ago) and the latest Flutter SDK update in december

I also noticed that the keyboard layout is wrong. 

I work on a MacBook Pro (Intel) and I have several keyboards connected to it. For coding I use a US keyboard, the MacBook itself has a SwissGerman layout. For some special signs like `/` or `?` I see a `ß` Sign, but only in the Simulator, e.g. when filling a Form. And then it simply freezes and I have to kill the Simulator and rebuild my flutter project.

From then on it works for a couple of hours and then freezes all of a sudden again. When I then switch to the device keyboard pressing `command+k` I can use the device keyboard on the simulated device (tapping the keys with the mouse). The hardware keyboard fires the above exception **for every keystroke** until I kill the simulator.

That's probably not very helpful but it is all I have, unfortunately.

**Comment by maheshmnj** [comment] 2022-01-07 12:52
Hi @thommy66, There have been several reports of similar issues in the past and it is very likely that it is fixed on the master channel. Could you please share the output of `flutter doctor -v`  and also try switching to the master channel and see if the issue reproduces for you by running 
```
flutter channel master
flutter upgrade
```

You may later switch back to your desired channel by running  `flutter channel <channel name>`

>  I use a US keyboard, the MacBook itself has a SwissGerman layout. For some special signs like / or ? I see a ß Sign, but only in the Simulator, e.g. when filling a Form. And then it simply freezes and I have to kill the Simulator and rebuild my flutter project.

It looks like this issue is reproducible with keys requiring the shift keys to be pressed, can you confirm this? If so, Then this looks related to https://github.com/flutter/flutter/issues/96082 (Linux)

**Comment by thommy66** [comment] 2022-01-09 08:25
Hi @maheshmnj 
Here is the output of the `doctor`

```
[flutter_riverpod1] flutter doctor -v
[✓] Flutter (Channel stable, 2.8.1, on macOS 11.6.2 20G314 darwin-x64, locale en-CH)
    • Flutter version 2.8.1 at /Users/tbednarz/Applications/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (3 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/tbednarz/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/tbednarz/Library/Android/sdk
    • Java binary at: /Users/tbednarz/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7935034/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Users/tbednarz/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7784292/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] Android Studio (version 2020.3)
    • Android Studio at /Users/tbednarz/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7935034/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.62.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (2 available)
    • iPhone 13 (mobile) • 5CB98DA3-28BD-4F88-B45C-41897847BA49 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 96.0.4664.110

• No issues found!
```

Switching to `master` is currently difficult, since I am in the middle of implementing stuff where I have a deadline...

> It looks like this issue is reproducible with keys requiring the shift keys to be pressed, can you confirm this? If so, Then this looks related to #96082 (Linux)

This may be the case... I think it happened when entering an email address. So for the `@` sign it would require the shift key and that would match the case you mentioned. But I did not pay enough attention what exactly I entered so I forgot it. If I see it again I can come back to it here.

**Comment by bernaferrari** [comment] 2022-01-09 18:03
Happening this on macOS. Just opened the app and tried to write in TextField.

```
The following assertion was thrown during a platform message callback:
A KeyUpEvent is dispatched, but the state shows that the physical key is not pressed. If this occurs in real application, please report this bug to Flutter. If this occurs in unit tests, please ensure that simulated events follow Flutter's event model as documented in `HardwareKeyboard`. This was the event: KeyUpEvent#17f3f(physicalKey: PhysicalKeyboardKey#70039(usbHidUsage: "0x00070039", debugName: "Caps Lock"), logicalKey: LogicalKeyboardKey#00104(keyId: "0x100000104", keyLabel: "Caps Lock", debugName: "Caps Lock"), character: null, timeStamp: 0:53:08.190261, synthesized)
'package:flutter/src/services/hardware_keyboard.dart':
Failed assertion: line 441 pos 16: '_pressedKeys.containsKey(event.physicalKey)'


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      HardwareKeyboard._assertEventIsRegular.<anonymous closure> (package:flutter/src/services/hardware_keyboard.dart:441:16)
#3      HardwareKeyboard._assertEventIsRegular (package:flutter/src/services/hardware_keyboard.dart:452:6)
#4      HardwareKeyboard.handleKeyEvent (package:flutter/src/services/hardware_keyboard.dart:544:5)
#5      KeyEventManager.handleRawKeyMessage (package:flutter/src/services/hardware_keyboard.dart:821:35)
#6      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:77:49)
#7      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:76:47)
#8      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:389:35)
#9      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:386:46)
#10     _invoke2.<anonymous closure> (dart:ui/hooks.dart:190:15)
#14     _invoke2 (dart:ui/hooks.dart:189:10)
#15     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:42:5)
#16     _Channel.push (dart:ui/channel_buffers.dart:132:31)
#17     ChannelBuffers.push (dart:ui/channel_buffers.dart:329:17)
#18     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:583:22)
#19     _dispatchPlatformMessage (dart:ui/hooks.dart:89:31)
(elided 5 frames from class _AssertionError and dart:async)
```

```
➜ flutter doctor -v
[✓] Flutter (Channel beta, 2.9.0-0.1.pre, on macOS 11.4 20F71 darwin-x64, locale
    en-BR)
    • Flutter version 2.9.0-0.1.pre at /usr/local/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 8f1f9c10f0 (4 weeks ago), 2021-12-14 13:41:48 -0800
    • Engine revision 234aca678a
    • Dart version 2.16.0 (build 2.16.0-80.1.beta)
    • DevTools version 2.9.1
```

**Comment by maheshmnj** [comment] 2022-01-10 07:56
Thanks for the update, But I am not able to reproduce the exception neither on stable, beta, or on master verified on both Ios Simulator and on macOS desktop. I did try with the swiss german layout on the stable channel, but could not reproduce it.

*swiss german layout*

https://user-images.githubusercontent.com/31410839/148731989-bc750b97-8fba-431b-bf32-873f6e8ec905.mov

> Switching to master is currently difficult, since I am in the middle of implementing stuff where I have a deadline...

It would be great if you can create a new sample project and try to identify the reproducible steps. 


Desktop             |  ios simulator
:-------------------------:|:-------------------------:
![image](https://user-images.githubusercontent.com/31410839/148722224-2d2c176c-f2fd-4574-b3ba-3e3bbd262d68.png) | ![Simulator Screen Shot - iPhone 12 Pro - 2022-01-10 at 11 22 32](https://user-images.githubusercontent.com/31410839/148726350-83485b50-201c-4cb4-afef-bbe5bd04137e.png)

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(primarySwatch: Colors.blue),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);
  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: const <Widget>[
            Text('Paste huge text below'),
            Expanded(
              child: TextField(maxLines: null, expands: true),
            ),
          ],
        ),
      ),
    );
  }
}

```
</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.1 21C52 darwin-arm, locale en-GB)
    • Flutter version 2.8.1 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (3 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.32.0

[✓] Connected device (4 available)
    • Redmi K20 Pro (mobile) • 192.168.1.3:5555                     • android-arm64  • Android 11 (API 30)
    • iPhone 13 Pro (mobile) • 0FA2FB93-2A89-4FDB-8293-DF66188F1E54 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-0
      (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.1 21C52 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 96.0.4664.110

• No issues found!
```

```
[✓] Flutter (Channel master, 2.9.0-1.0.pre.224, on macOS 12.1 21C52 darwin-arm, locale en-GB)
    • Flutter version 2.9.0-1.0.pre.224 at /Users/mahesh/Documents/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a0f8937b7c (7 days ago), 2022-01-03 04:15:18 -0500
    • Engine revision 8f53bbfde0
    • Dart version 2.16.0 (build 2.16.0-134.0.dev)
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.32.0

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • B622CBB7-F906-4FA7-8F49-FACEAAC905AB • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.1 21C52 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 96.0.4664.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by maheshmnj** [comment] 2022-01-10 08:00
> Happening this on macOS. Just opened the app and tried to write in TextField.

This exception could be due to different key(s) combinations, keyboard layouts, from your logs it seems like this is reproducible by pressing `Caps Lock`.

Everyone who is facing this issue, it would be great if you can identify the reproducible steps for this issue to be actionable further.

Thanks

**Comment by steeling** [comment] 2022-01-18 01:14
This is pretty debilitating when debugging. It happens to me roughly every 2 minutes, and sometimes the text input gets completely locked up to the point I need to do a full restart (~4-5 min build)

I can't seem to consistently recreate the issue. Sometimes it happens on first key pressed after restarting the app. I had autofocus on too, so there was no prior user input. Sometimes it doesn't happen. Seems to be non-deterministic.

My simulator settings have "Connect hardware keyboard" and "Use same keyboard as MacOS" enabled, and the software keyboard disabled.

**Comment by maheshmnj** [comment] 2022-01-18 08:27
@steeling  could you please share the output of `flutter doctor -v`.

**Comment by steeling** [comment] 2022-01-18 16:21
flutter doctor -v
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.0.1 21A559 darwin-x64, locale en-US)
    • Flutter version 2.8.1 at /Users/steeling/dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (5 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/steeling/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] VS Code (version 1.48.0)
    • VS Code at /Users/steeling/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] VS Code (version 1.61.2)
    • VS Code at /Users/steeling/Downloads/Visual Studio Code 2.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (2 available)
    • iPhone 13 Pro Max (mobile) • 60481563-C5F1-4593-B98E-BE7E2F78F2ED • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 97.0.4692.71

• No issues found!

**Comment by bernaferrari** [comment] 2022-01-18 16:26
Happening every day to me, but it is random. There is no way to reproduce it correctly. Maybe open the app and try pressing caps lock/other keys immediately? 

```
[✓] Flutter (Channel beta, 2.10.0-0.1.pre, on macOS 11.4 20F71 darwin-x64,
    locale en-BR)
    • Flutter version 2.10.0-0.1.pre at /usr/local/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 628f0e3f3a (7 days ago), 2022-01-11 19:50:05 -0600
    • Engine revision 63ca99584a
    • Dart version 2.16.0 (build 2.16.0-134.1.beta)
    • DevTools version 2.9.2
```

**Closed** 2022-02-01 09:09 UTC
Labels: waiting for customer response, in triage
