### ISSUE TITLE
(Only in vscode plugin on linux) - Failed to establish connection with the application instance in Chrome.

### ISSUE THREAD

**Issue by matheust3** [flutter/flutter#80219] opened 2021-04-11 14:37 UTC
## Steps to Reproduce
1. Run `flutter create bug`.
2. Try to launch debugging on vscode.

**Notes:**
1. Debugging by the web server works
2. Running `flutter run -d chrome` works but in vscode launch debug not. 

<details>
  <summary>Logs</summary>

```
❯ flutter doctor -v
[✓] Flutter (Channel stable, 2.0.4, on Linux, locale pt_BR.UTF-8)
    • Flutter version 2.0.4 at /home/matheus/flutter
    • Framework revision b1395592de (10 days ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/matheus/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /snap/android-studio/current/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio
    • Android Studio at /snap/android-studio/current/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /snap/android-studio/current/android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 89.0.4389.114

• No issues found!

```

</details>

**Comment by iapicca** [comment] 2021-04-11 16:38
@matheust3 
can you provide your `flutter run -d chrome -v`

**Comment by matheust3** [comment] 2021-04-11 16:55
@iapicca Running the command from the terminal everything works as planned, the problem is when I try to debug using vscode

<details>
  <summary>Logs - `flutter run -d chrome -v` </summary>

```
❯ flutter run -d chrome -v
[  +89 ms] executing: [/home/matheus/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +40 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] b1395592de68cc8ac4522094ae59956dd21a91db
[   +1 ms] executing: [/home/matheus/flutter/] git tag --points-at b1395592de68cc8ac4522094ae59956dd21a91db
[  +19 ms] Exit code 0 from: git tag --points-at b1395592de68cc8ac4522094ae59956dd21a91db
[        ] 2.0.4
[  +64 ms] executing: [/home/matheus/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +4 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/home/matheus/flutter/] git ls-remote --get-url origin
[   +4 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +56 ms] executing: [/home/matheus/flutter/] git rev-parse --abbrev-ref HEAD
[   +3 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +80 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +99 ms] executing: /home/matheus/Android/Sdk/platform-tools/adb devices -l
[  +26 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +152 ms] executing: /home/matheus/Android/Sdk/platform-tools/adb devices -l
[  +38 ms] Skipping pub get: version match.
[ +148 ms] Found plugin path_provider at /home/matheus/.pub-cache/hosted/pub.dartlang.org/path_provider-2.0.1/
[  +11 ms] Found plugin path_provider_linux at /home/matheus/.pub-cache/hosted/pub.dartlang.org/path_provider_linux-2.0.0/
[   +3 ms] Found plugin path_provider_macos at /home/matheus/.pub-cache/hosted/pub.dartlang.org/path_provider_macos-2.0.0/
[   +4 ms] Found plugin path_provider_windows at /home/matheus/.pub-cache/hosted/pub.dartlang.org/path_provider_windows-2.0.0/
[  +16 ms] Found plugin shared_preferences at /home/matheus/.pub-cache/hosted/pub.dartlang.org/shared_preferences-2.0.5/
[   +3 ms] Found plugin shared_preferences_linux at /home/matheus/.pub-cache/hosted/pub.dartlang.org/shared_preferences_linux-2.0.0/
[   +2 ms] Found plugin shared_preferences_macos at /home/matheus/.pub-cache/hosted/pub.dartlang.org/shared_preferences_macos-2.0.0/
[   +4 ms] Found plugin shared_preferences_web at /home/matheus/.pub-cache/hosted/pub.dartlang.org/shared_preferences_web-2.0.0/
[   +3 ms] Found plugin shared_preferences_windows at /home/matheus/.pub-cache/hosted/pub.dartlang.org/shared_preferences_windows-2.0.0/
[ +281 ms] Found plugin path_provider at /home/matheus/.pub-cache/hosted/pub.dartlang.org/path_provider-2.0.1/
[   +1 ms] Found plugin path_provider_linux at /home/matheus/.pub-cache/hosted/pub.dartlang.org/path_provider_linux-2.0.0/
[   +1 ms] Found plugin path_provider_macos at /home/matheus/.pub-cache/hosted/pub.dartlang.org/path_provider_macos-2.0.0/
[   +1 ms] Found plugin path_provider_windows at /home/matheus/.pub-cache/hosted/pub.dartlang.org/path_provider_windows-2.0.0/
[   +7 ms] Found plugin shared_preferences at /home/matheus/.pub-cache/hosted/pub.dartlang.org/shared_preferences-2.0.5/
[   +2 ms] Found plugin shared_preferences_linux at /home/matheus/.pub-cache/hosted/pub.dartlang.org/shared_preferences_linux-2.0.0/
[   +2 ms] Found plugin shared_preferences_macos at /home/matheus/.pub-cache/hosted/pub.dartlang.org/shared_preferences_macos-2.0.0/
[   +3 ms] Found plugin shared_preferences_web at /home/matheus/.pub-cache/hosted/pub.dartlang.org/shared_preferences_web-2.0.0/
[   +1 ms] Found plugin shared_preferences_windows at /home/matheus/.pub-cache/hosted/pub.dartlang.org/shared_preferences_windows-2.0.0/
[  +37 ms] Generating /media/d/Dev/Flutter/assist_agro/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[ +156 ms] List of devices attached
[   +3 ms] List of devices attached
[ +127 ms] Launching lib/main.dart on Chrome in debug mode...
[ +189 ms] Updating assets
[ +217 ms] Waiting for connection from debug service on Chrome...
[  +41 ms] Found plugin path_provider at /home/matheus/.pub-cache/hosted/pub.dartlang.org/path_provider-2.0.1/
[   +1 ms] Found plugin path_provider_linux at /home/matheus/.pub-cache/hosted/pub.dartlang.org/path_provider_linux-2.0.0/
[   +1 ms] Found plugin path_provider_macos at /home/matheus/.pub-cache/hosted/pub.dartlang.org/path_provider_macos-2.0.0/
[   +2 ms] Found plugin path_provider_windows at /home/matheus/.pub-cache/hosted/pub.dartlang.org/path_provider_windows-2.0.0/
[   +6 ms] Found plugin shared_preferences at /home/matheus/.pub-cache/hosted/pub.dartlang.org/shared_preferences-2.0.5/
[   +1 ms] Found plugin shared_preferences_linux at /home/matheus/.pub-cache/hosted/pub.dartlang.org/shared_preferences_linux-2.0.0/
[   +1 ms] Found plugin shared_preferences_macos at /home/matheus/.pub-cache/hosted/pub.dartlang.org/shared_preferences_macos-2.0.0/
[   +2 ms] Found plugin shared_preferences_web at /home/matheus/.pub-cache/hosted/pub.dartlang.org/shared_preferences_web-2.0.0/
[   +1 ms] Found plugin shared_preferences_windows at /home/matheus/.pub-cache/hosted/pub.dartlang.org/shared_preferences_windows-2.0.0/
[  +42 ms] Found plugin path_provider at /home/matheus/.pub-cache/hosted/pub.dartlang.org/path_provider-2.0.1/
[   +1 ms] Found plugin path_provider_linux at /home/matheus/.pub-cache/hosted/pub.dartlang.org/path_provider_linux-2.0.0/
[        ] Found plugin path_provider_macos at /home/matheus/.pub-cache/hosted/pub.dartlang.org/path_provider_macos-2.0.0/
[   +1 ms] Found plugin path_provider_windows at /home/matheus/.pub-cache/hosted/pub.dartlang.org/path_provider_windows-2.0.0/
[   +6 ms] Found plugin shared_preferences at /home/matheus/.pub-cache/hosted/pub.dartlang.org/shared_preferences-2.0.5/
[   +2 ms] Found plugin shared_preferences_linux at /home/matheus/.pub-cache/hosted/pub.dartlang.org/shared_preferences_linux-2.0.0/
[   +1 ms] Found plugin shared_preferences_macos at /home/matheus/.pub-cache/hosted/pub.dartlang.org/shared_preferences_macos-2.0.0/
[   +1 ms] Found plugin shared_preferences_web at /home/matheus/.pub-cache/hosted/pub.dartlang.org/shared_preferences_web-2.0.0/
[   +1 ms] Found plugin shared_preferences_windows at /home/matheus/.pub-cache/hosted/pub.dartlang.org/shared_preferences_windows-2.0.0/
[ +143 ms] <- reset
[  +10 ms] /home/matheus/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev
/home/matheus/flutter/bin/cache/artifacts/engine/linux-x64/frontend_server.dart.snapshot --sdk-root /home/matheus/flutter/bin/cache/flutter_web_sdk/
--incremental --target=dartdevc --debugger-module-names --experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true --output-dill
/tmp/flutter_tools.VIPEJQ/flutter_tool.JPMDFV/app.dill --libraries-spec file:///home/matheus/flutter/bin/cache/flutter_web_sdk/libraries.json
--packages /media/d/Dev/Flutter/assist_agro/.dart_tool/package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts
--track-widget-creation --filesystem-root /tmp/flutter_tools.VIPEJQ/flutter_tools.UAWBGG --filesystem-scheme org-dartlang-app --initialize-from-dill
build/b1b715402d823b7fd5c2b68d2edcb2ce.cache.dill.track.dill --platform
file:///home/matheus/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk_sound.dill --sound-null-safety
[  +15 ms] <- compile org-dartlang-app:/web_entrypoint.dart
[+26758 ms] Waiting for connection from debug service on Chrome... (completed in 27,0s)
[   +1 ms] Synced 35.8MB.
[        ] <- accept
[        ] Caching compiled dill
[ +435 ms] Using Google Chrome 89.0.4389.114 

[ +439 ms] [CHROME]:
[        ] [CHROME]:(google-chrome:18353): Gtk-WARNING **: 12:52:55.124: Theme parsing error: gtk.css:4069:23: Junk at end of value for color
[ +140 ms] [CHROME]:
[   +7 ms] [CHROME]:DevTools listening on ws://127.0.0.1:39819/devtools/browser/0772a2a5-7172-4ff9-a552-3250557ebe3e
[ +621 ms] DwdsInjector: Received request for entrypoint at http://localhost:37489/main_module.bootstrap.js
[  +26 ms] MetadataProvider: Loading debug metadata...
[  +50 ms] MetadataProvider: Loaded debug metadata
[  +23 ms] DwdsInjector: Injected debugging metadata for entrypoint at http://localhost:37489/main_module.bootstrap.js
[+3651 ms] DevHandler: Debug service listening on ws://127.0.0.1:39073/dOIaWHqarJo=/ws

[  +12 ms] Debug service listening on ws://127.0.0.1:39073/dOIaWHqarJo=/ws
[   +2 ms] 💪 Running with sound null safety 💪
[   +4 ms] 🔥  To hot restart changes while running, press "r" or "R".
[        ] For a more detailed help message, press "h". To quit, press "q".

```

</details>

**Comment by TahaTesser** [comment] 2021-04-12 11:59
Hi @matheust3 
Following the indication of [VS Code Flutter Extension](https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter), the correct way to address the problem is to open an issue in the dedicated [repository](https://github.com/Dart-Code/Dart-Code/issues).
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-04-12 11:59 UTC
