### ISSUE TITLE
TextField.onTap fires before winning gesture

### ISSUE THREAD

**Issue by tony123S** [flutter/flutter#45890] opened 2019-12-02 09:48 UTC
I use suffixIcon in TextField. When TextField is clicked, it will open PageC, but if suffixIcon is clicked, it will open pageB.

**PageA**
```
 StreamBuilder<List<ABC>>(
                stream: _bloc.listStream,
                builder: (context, snapshot) {
                  return TextField(
                    onTap: () {
                      if (snapshot.hasData) {
                        _goToPageC(snapshot.data);
                      } 
                    },
                          .....
                      suffixIcon: Container(
                        padding: EdgeInsets.symmetric(vertical: 10),
                        child: FloatingActionButton(
                          heroTag: "addButton",
                          child: Icon(Icons.add),
                          onPressed: () {
                            Navigator.pushNamed(context, PageB.ROUTE);
                          },
                        ),
                            .....
                },
              ),

  void _goToPageC(List list) async {
    var results = await Navigator.of(context).push(PageRouteBuilder(
        opaque: false,
        pageBuilder: (BuildContext context, _, __) {
          return PageC(list);
        }));

    if (results != null) {
             .....
        }
      });
    }
  }
```

My issue is when I click the suffixIcon, it will open pageC. When I click the back device button in pageC, only pageB will show. Why would this happened?

**Comment by iapicca** [comment] 2019-12-02 14:22
Hi @tony123S 

<details>
  <summary>sample code</summary>

```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) => MaterialApp(
    home: HomePage(),
  );
}

class HomePage extends StatefulWidget {
  @override
  _HomePageState createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  @override
  Widget build(BuildContext context) => Scaffold(
    body: Center(
      child: TextField(
        onTap: () =>  Navigator.push(
          context,
          MaterialPageRoute(builder: (context) => MyPage(title: 'C')),
        ),
        decoration: InputDecoration(
          suffixIcon: Container(
            padding: EdgeInsets.symmetric(vertical: 10),
            child: FloatingActionButton(
              child: Icon(Icons.add),
              onPressed: ()=> Navigator.push(
                context,
                MaterialPageRoute(builder: (context) => MyPage(title: 'B')),
        ),),),),
  ),),);
}

class MyPage extends StatelessWidget {
  final String title;
  MyPage({this.title});

  @override
  Widget build(BuildContext context) => Scaffold(
    body: Center(
      child: Text('page $title',
        textScaleFactor: 3,
    ),),
    floatingActionButton: FloatingActionButton(
      onPressed: ()=> Navigator.pop(context),
      child: Icon(Icons.arrow_back),
  ),);
}
```

</details>

I do see an unexpected behavior, 
but not necessarily the one described in your post:
clearly the routing to "page C" when attempting to tap on the `TextField `decoration
happens due to the overlapping of the gesture detectors area, nevertheless
I'm surprised that 2 different routing happen at the contextually.

does the code above represent the situation you are describing?
thank you

**Comment by tony123S** [comment] 2019-12-02 14:32
Hi @iapicca ,

the reason I'm using  **PageRouteBuilder** instead of **MaterialPageRoute** is to prevent stack rebuild when a new page is pushed as described here https://github.com/flutter/flutter/issues/11655

**Comment by tony123S** [comment] 2019-12-03 04:13
Anyone can help ?

**Comment by Hixie** [comment] 2020-01-06 21:56
I suspect this is because the text field's gesture detector fires onTap too eagerly (doesn't wait to have won its gesture handler).

**Comment by TahaTesser** [comment] 2020-07-03 13:55
duplicate of https://github.com/flutter/flutter/issues/39376

**Closed by TahaTesser** 2020-07-03 13:55 UTC
Labels: P4, a: text input, f: gestures, f: material design, f: routes, framework
