### ISSUE TITLE
Attribute application@name at AndroidManifest.xml:10:9-42 requires a placeholder substitution but no value for <applicationName> is provided.

### ISSUE THREAD

**Issue by aikonics** [flutter/flutter#98316] opened 2022-02-12 06:37 UTC
I cannot run my app because of this error.

<img width="1429" alt="Screen Shot 2022-02-12 at 2 33 09 PM" src="https://user-images.githubusercontent.com/30689412/153700087-d0b2f9e8-a76a-4d5b-b1d4-b3980faa03fa.png">

[✓] Flutter (Channel dev, 2.3.0-24.0.pre, on macOS 11.1 20C69 darwin-arm, locale en-PH)
    • Flutter version 2.3.0-24.0.pre at /Applications/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2b9537c783 (8 months ago), 2021-06-11 22:11:53 -0700
    • Engine revision ddbac024d1
    • Dart version 2.14.0 (build 2.14.0-188.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/aikbusmeon/Library/Android/sdk
    • Platform android-31, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] VS Code (version 1.64.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.34.0

[✓] Connected device (2 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 12 (API 31) (emulator)
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 98.0.4758.80

• No issues found!

I'm using Macbook Pro M1 and the latest Android Studio Bumblebee.

**Comment by ugyen-chophel** [comment] 2022-02-12 08:50
Can you show your AndroidManifest.xml file ?

**Comment by FaKenKoala** [comment] 2022-02-14 07:55
Removing the `android:name=${applicationName}` line works for me.

**Comment by danagbemava-nc** [comment] 2022-02-14 08:07
Hi @aikonics, please provide your `AndroidManifest.xml`.

Thank you

**Comment by aikonics** [comment] 2022-02-15 14:48
Hello guys, thanks for your response. I have fixed it by migrating my code to a new flutter project. I think my android files are outdated.  Sorry I have deleted the old version already so I cannot show you the AndroidManifest.xml. that you are asking for. Have a nice day and God bless!

**Comment by danagbemava-nc** [comment] 2022-02-16 06:24
Hi @RicardoKurashiki, kindly file a new issue a provide the relevant steps to reproduce. 

Given that the original reporter has fixed his issue, I'm going to close this as solved. 

Closing based on https://github.com/flutter/flutter/issues/98316#issuecomment-1040361210.

Thank you

**Closed by danagbemava-nc** 2022-02-16 06:24 UTC
Labels: in triage

**Comment by scana** [comment] 2022-02-20 13:53
Sorry for reviving this thread, but I see that @RicardoKurashiki did not open up a new issue for this and at the same time I have just encountered this.

If you'll get this kind of error, just change:
```groovy
defaultConfig {
        // ...
        manifestPlaceholders = [
                'appAuthRedirectScheme': 'xxxxxx'
        ]
}
```

to 
```groovy
defaultConfig {
        // ...
        manifestPlaceholders['appAuthRedirectScheme'] = "'xxxxxx"
}
```

This will ensure that Flutter-generated manifest placeholders won't be overwritten:
