### ISSUE TITLE
"flutter test" fails to start, even though everything is configured according to  https://flutter.io/testing/ 

### ISSUE THREAD

**Issue by mzimmerm** [flutter/flutter#11979] opened 2017-09-07 14:56 UTC
## My configuration and test file is as in https://flutter.io/testing/ 

pubspec.yaml
```yaml
name: flutter_charts_common
description: Package of Flutter Charts Common Libraries

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
```
The test file range_test.dart 
```dart
import 'package:test/test.dart';
void main() {

  test('my first unit test', () {
    var answer = 42;
    expect(answer, 42);
  });
}
```

### Run  flutter packages get
```
mzimmermann@home-server:~/dev/my-projects-source/public-on-github/flutter_charts_common> flutter packages get
Running "flutter packages get" in flutter_charts_common...  0.8s
m
```
above is OK

### Run  flutter test --verbose - **fails to run**

```
mzimmermann@home-server:~/dev/my-projects-source/public-on-github/flutter_charts_common> flutter test --verbose        
[      +27 ms] [/home/mzimmermann/software/flutter/gitclone/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[      +29 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[            ] origin/alpha
[            ] [/home/mzimmermann/software/flutter/gitclone/flutter/] git ls-remote --get-url origin
[       +6 ms] Exit code 0 from: git ls-remote --get-url origin
[            ] https://github.com/flutter/flutter.git
[            ] [/home/mzimmermann/software/flutter/gitclone/flutter/] git log -n 1 --pretty=format:%H
[       +6 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[            ] d36e2f6191793de66e0a132ad8c86885829bc6b2
[            ] [/home/mzimmermann/software/flutter/gitclone/flutter/] git log -n 1 --pretty=format:%ar
[       +6 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[            ] 3 months ago
[     +111 ms] switching to directory LocalDirectory: 'test' to run tests
[       +1 ms] running test package with arguments: [--, /home/mzimmermann/dev/my-projects-source/public-on-github/flutter_charts_common/test/src/util/range_test.dart]
00:00 +0: ...jects-source/public-on-github/flutter_charts_common/test/src/util/range_test.dart     [     +176 ms] test 0: starting test /home/mzimmermann/dev/my-projects-source/public-on-github/flutter_charts_common/test/src/util/range_test.dart
[      +20 ms] test 0: starting shell process
[            ] /home/mzimmermann/software/flutter/gitclone/flutter/bin/cache/artifacts/engine/linux-x64/flutter_tester --disable-observatory --disable-diagnostic --enable-dart-profiling --non-interactive --enable-checked-mode --use-test-fonts --packages=/home/mzimmermann/dev/my-projects-source/public-on-github/flutter_charts_common/.packages /tmp/dart_test_listenerhM9afE/listener.dart
[      +17 ms] test 0: awaiting initial result for pid 7170
[      +39 ms] Shell: error: Unable to read Dart source 'package:test/src/runner/plugin/remote_platform_helpers.dart'.
[            ] 
               
               Failed to load test harness. Are you missing a dependency on flutter_test?
               
[      +26 ms] test 0: process with pid 7170 crashed before connecting to test harness
[       +2 ms] test 0: waiting for controller sink to close
[       +3 ms] test 0: cleaning up...
[       +3 ms] test 0: shutting down test harness socket server
00:00 +0 -1: loading /home/mzimmermann/dev/my-projects-source/public-on-github/flutter_charts_common/test/src/util/range_test.dart [E]
  Failed to load "/home/mzimmermann/dev/my-projects-source/public-on-github/flutter_charts_common/test/src/util/range_test.dart":
  Shell subprocess cleanly reported an error before connecting to test harness. Check the logs above for an error message.
  Test: /home/mzimmermann/dev/my-projects-source/public-on-github/flutter_charts_common/test/src/util/range_test.dart
  Shell: /home/mzimmermann/software/flutter/gitclone/flutter/bin/cache/artifacts/engine/linux-x64/flutter_tester
  
  
00:00 +0 -1: Some tests failed.                                                                    
[      +24 ms] test package returned with exit code 1
[      +13 ms] "flutter test" took 382ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:29)
#1      TestCommand.runCommand (package:flutter_tools/src/commands/test.dart:205)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:210)
<asynchronous suspension>
#3      FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:156)
<asynchronous suspension>
#4      CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#5      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:277)
<asynchronous suspension>
#6      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#7      new Future.sync (dart:async/future.dart:206)
#8      CommandRunner.run (package:args/command_runner.dart:109)
#9      FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:161)
#10     run.<anonymous closure> (package:flutter_tools/executable.dart:142)
<asynchronous suspension>
#11     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#12     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#13     _rootRun (dart:async/zone.dart:1120)
#14     _CustomZone.run (dart:async/zone.dart:1001)
#15     runZoned (dart:async/zone.dart:1467)
#16     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#17     run (package:flutter_tools/executable.dart:114)
<asynchronous suspension>
#18     main (package:flutter_tools/executable.dart:67)
<asynchronous suspension>
#19     main (file:///home/mzimmermann/software/flutter/gitclone/flutter/packages/flutter_tools/bin/flutter_tools.dart:16)
#20     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)


[       +7 ms] test 0: deleting temporary directory
[       +1 ms] test 0: finished
[      +73 ms] ensureAnalyticsSent: 77ms
[       +2 ms] exiting with code 1
```

**Claims I may not have flutter_test configured but I do.**

## Logs

Run `flutter analyze` and attach any output of that command also.

```
mzimmermann@home-server:~/dev/my-projects-source/public-on-github/flutter_charts_common> flutter analyze
Analyzing /home/mzimmermann/dev/my-projects-source/public-on-github/flutter_charts_common...
  lint • Name non-constant identifiers using lowerCamelCase at lib/src/util/range.dart:186:13 • non_constant_identifier_names
  hint • The name Rect is shown, but not used at lib/src/chart/elements_layouters.dart:1:29 • unused_shown_name
  hint • The name Offset is shown, but not used at lib/src/chart/elements_layouters.dart:1:41 • unused_shown_name
  hint • The value of the field '_yLayouter' isn't used at lib/src/chart/elements_layouters.dart:301:13 • unused_field
  hint • Unused import at lib/src/chart/random_chart_data.dart:3:8 • unused_import
  hint • The value of the field '_useMonthNames' isn't used at lib/src/chart/random_chart_data.dart:14:8 • unused_field
  hint • The value of the field '_maxLabelLength' isn't used at lib/src/chart/random_chart_data.dart:15:8 • unused_field
  hint • The value of the field '_maxLabels' isn't used at lib/src/util/range.dart:16:7 • unused_field
  hint • The value of the field '_negValues' isn't used at lib/src/util/range.dart:19:13 • unused_field
  hint • The value of the field '_posValues' isn't used at lib/src/util/range.dart:20:13 • unused_field
  hint • The value of the local variable 'signDiff' isn't used at lib/src/util/range.dart:51:9 • unused_local_variable
  hint • Dead code at lib/src/util/range.dart:57:18 • dead_code
  hint • The value of the local variable 'polyMinPower' isn't used at lib/src/util/range.dart:103:9 • unused_local_variable
  hint • The value of the local variable 'polyMaxPower' isn't used at lib/src/util/range.dart:104:9 • unused_local_variable
  hint • The value of the local variable 'maxPower' isn't used at test/src/util/range_test.dart:34:9 • unused_local_variable
15 issues found.
(Ran in 7.8s)
```

## Flutter Doctor

Paste the output of running `flutter doctor` here.

```
mzimmermann@home-server:~/dev/my-projects-source/public-on-github/flutter_charts_common> flutter doctor
[✓] Flutter (on Linux, locale en_CA.UTF-8, channel alpha)
    • Flutter at /home/mzimmermann/software/flutter/gitclone/flutter
    • Framework revision d36e2f6191 (3 months ago), 2017-06-21 15:09:10 -0700
    • Engine revision b0dee695ec
    • Tools Dart version 1.24.0-dev.6.7

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at /home/mzimmermann/software/android/studio/sdk
    • Platform android-25, build-tools 25.0.3
    • ANDROID_HOME = /home/mzimmermann/software/android/studio/sdk
    • Java binary at: /home/mzimmermann/software/android/studio/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] Android Studio (version 2.3)
    • Android Studio at /home/mzimmermann/software/android/studio/android-studio
    • Gradle version 3.2
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Ultimate Edition (version 2017.2)
    • Flutter plugin version 16.0
    • Dart plugin version 172.3544.10

[✓] Connected devices
    • Z160 • WGKJYD8LQ8Z54SIV • android-arm • Android 4.2.2 (API 17)
```

**Comment by Hixie** [comment] 2017-09-22 21:06
This is suspicious:
```
[      +39 ms] Shell: error: Unable to read Dart source 'package:test/src/runner/plugin/remote_platform_helpers.dart'.
```

**Comment by JMichaelYang** [comment] 2018-02-07 05:21
Was anyone ever able to find a solution to this issue? Thanks.

**Comment by Hixie** [comment] 2018-05-29 18:12
We've never been able to reproduce this, and we use `flutter test` heavily in many different configurations.

It's not clear to me what the problem could have been. We've since changed how tests run so the failure mode would probably be different now anyway. I'm going to close this bug but if you run into this problem please please please file a new bug and include as much information as you possibly can. Thanks.

**Closed by Hixie** 2018-05-29 18:12 UTC
