### ISSUE TITLE
[Focus] Inconsistent behavior on Android and Desktop/Web

### ISSUE THREAD

**Issue by merabtenei** [flutter/flutter#110281] opened 2022-08-25 19:58 UTC
The behavior of Focus widget is different in Android and Desktop/Web.

Minimal code to reproduce the case:
```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  final String title;

  const MyHomePage({
    Key? key,
    required this.title,
  }) : super(key: key);

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            
            Focus(onFocusChange: (value) => print('FocusChanged to $value') , child: TextField()),
            ElevatedButton(onPressed: () => print('Button clicked'), child: const Text('OK')),
            
          ],
        ),
      ),
    );
  }
}
```
When you type something on the textfield and directly click / tap on the OK button we get different output as below :

**Output on Desktop and Web :**
```
FocusChanged to true
FocusChanged to false
Button clicked
```
**Output on a real Android**
```
FocusChanged to true
Button clicked
```
We are developing an app were we make updates to a rest api service when a TextField is focused out and we came across this issue. Everything works fine on Windows and Web but not on Android devices.
I guess we can use FocusScope.of(context).unfocus() on the button click event to force the onFocusChanged(false) to be called but is this the expected behavior in Flutter and is there other ways of doing this ?

**Comment by danagbemava-nc** [comment] 2022-08-26 07:40
Hi @merabtenei, I believe this is the expected behavior for mobile devices when you're entering text into a Textfield. You will have to call `FocusScope.of(context).unfocus()` to remove focus when the button is clicked.  

I created a simple SwiftUI app (I used iOS to demonstrate that it's not only on android) to show what happens when a button is clicked without explicitly removing the focus. See the recording below

Does this help clear up any confusion that you have?

<details>
<summary>video</summary>

https://user-images.githubusercontent.com/88313112/186849054-d68ec944-dbec-4a47-bfb7-219cdb303fa8.mp4
</details>

**Comment by merabtenei** [comment] 2022-08-26 10:45
Thanks for the clarification @danagbemava-nc.
In Web and Desktop we can trigger the onFocusChanged(false) by clicking on any empty place of the screen too. Is there trick to have this on Android.
We want to have the event called whenever we focus out or tap anywhere else outside the TextInput including any empty space, button or widget. What do you suggest to have this behavior similar to what we get on desktop.
Thanks again.

**Comment by danagbemava-nc** [comment] 2022-08-26 12:52
You could try wrapping the page you want to have this behavior with a `Listener` widget and then implementing `onPointerDown` to call `FocusScope.of(context).unfocus()`. 

See also https://stackoverflow.com/questions/51652897/how-to-hide-soft-input-keyboard-on-flutter-after-clicking-outside-textfield-anyw, if the onPointerDown solution doesn't work for you.

I have attached a sample below which seems to work just fine. 

I'll be closing this since this is working as intended. 

Thank you

<details>
<summary>sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  final String title;

  const MyHomePage({
    Key? key,
    required this.title,
  }) : super(key: key);

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Listener(
      onPointerDown: (_) {
        FocusScope.of(context).unfocus();
      },
      child: Scaffold(
        appBar: AppBar(
          title: Text(widget.title),
        ),
        body: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              Focus(onFocusChange: (value) => print('FocusChanged to $value'), child: TextField()),
              ElevatedButton(onPressed: () => print('Button clicked'), child: const Text('OK')),
            ],
          ),
        ),
      ),
    );
  }
}

```
</details>

**Closed by danagbemava-nc** 2022-08-26 12:52 UTC
Labels: in triage
