### ISSUE TITLE
ListTile Background Color Appears outside of ListView bounds.

### ISSUE THREAD

**Issue by hakamdev** [flutter/flutter#94261] opened 2021-11-26 19:12 UTC
When setting `tileColor` for a `ListTile` Widget, the `tileColor` appears outside the `ListView` bounds, on top of any neighboring Widget that doesn't have a `backgroundColor`.
I think this needs to be fixed. because setting a Background Color for every neighboring Widget as a workaround is not always very convenient to do!
This same issue applies to the `splashColor` of the `ListTile` when tapping it.
<img width="496" alt="Screen Shot 2021-11-26 at 8 07 15 PM" src="https://user-images.githubusercontent.com/29928577/143622381-32aa85d3-0b50-4653-9c8f-d0e809093881.png">

**Comment by hakamdev** [comment] 2021-11-26 19:13
<img width="623" alt="Screen Shot 2021-11-26 at 8 13 10 PM" src="https://user-images.githubusercontent.com/29928577/143622680-439e8dec-57b4-406a-b69c-f516e80b46e3.png">

**Comment by maheshmnj** [comment] 2021-11-29 10:24
Hi @hakamdev, Thanks for filing the issue. I verified on stable 2.5.3 and it seems to set the `tileColor` within the bounds.  Please share a minimal and complete reproducible code sample and on which platform is this issue reproducible?

<img src="https://user-images.githubusercontent.com/31410839/143850906-ed5e3e4e-dcb4-4ef2-be88-1bb2587ee011.png" width ="300">

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

/// This is the main application widget.
class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  static const String _title = 'Flutter Code Sample';

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: _title,
      home: Scaffold(
        appBar: AppBar(title: const Text(_title)),
        body: const MyStatelessWidget(),
      ),
    );
  }
}

class MyStatelessWidget extends StatelessWidget {
  const MyStatelessWidget({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return ListView.builder(itemBuilder: (context, index) {
      return Padding(
        padding: const EdgeInsets.all(8.0),
        child: ListTile(
          tileColor: Colors.red,
          leading: const Icon(Icons.star),
          title: Text('Title $index'),
          subtitle: Text('Subtitle $index'),
          trailing: Icon(Icons.more_vert),
        ),
      );
    });
  }
}
```
</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.5.3, on macOS 12.0.1 21A559 darwin-arm, locale en-GB)
    • Flutter version 2.5.3 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (6 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.1, Build version 13A1030d
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.61.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.28.0

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • B622CBB7-F906-4FA7-8F49-FACEAAC905AB • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.0.1 21A559
      darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome
      96.0.4664.55

• No issues found!
```
</details>



Thanks

**Comment by amila325** [comment] 2021-11-29 22:57
I'm also having the same issue. I'm running this code in Apple simulator iOS 15 iPhone 13. Here's a sample code I just wrote

`void main() {
  runApp(const Issue());
}
class Issue extends StatelessWidget {
  const Issue({Key? key}) : super(key: key);

  ListTile createTile(String titleText, int index) {
    return ListTile(
      title: Text(titleText),
      leading: Icon(Icons.book),
      tileColor: index.isEven ? Colors.grey : Colors.blueGrey,
    );
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: SafeArea(
        child: Scaffold(
          body: Column(
            children: [
              Text('Sample Sample Sample'),
              Text('Sample Sample Sample'),
              Text('Sample Sample Sample'),
              Text('Sample Sample Sample'),
              ListTile(
                title: Text('Some Text'),
                trailing: Icon(Icons.airplay),
              ),
              Expanded(
                child: ListView(
                  scrollDirection: Axis.vertical,
                  shrinkWrap: true,
                  children: [
                    ListTile(
                      title: Text('Tile Text'),
                      leading: Icon(Icons.book),
                      tileColor: Colors.grey,
                    ),
                    ListTile(
                      title: Text('Tile Text 2'),
                      leading: Icon(Icons.book),
                      tileColor: Colors.blueGrey,
                    ),

                  ],
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
`

**Comment by maheshmnj** [comment] 2021-11-30 10:31
@hakamdev thanks for the code sample I was able to reproduce the issue.


<img src="https://user-images.githubusercontent.com/31410839/144030994-8d6e6291-c6d6-4b7f-bc3c-676a6a5c2abd.png" width ="300">

 It looks like this is same as https://github.com/flutter/flutter/issues/86584,  Closing this issue as a duplicate , if you disagree feel free to write in the comments and I will reopen it.

Thank you.

**Closed by maheshmnj** 2021-11-30 10:31 UTC
Labels: in triage

**Comment by amila325** [comment] 2021-12-01 00:37
Can confirm according to the issue [#86584](https://github.com/flutter/flutter/issues/86584) if you wrap the ListTile with a Card widget it can be workaround to omit this issue.
