### ISSUE TITLE
[webview_flutter] Add download listener on Android webview

### ISSUE THREAD

**Issue by renefloor** [flutter/flutter#89657] opened 2021-09-08 14:30 UTC
## Use case

In the Flutter webview we have a navigationDelegate so we can do specific actions in the app based on the url that is being loaded. 

In the webview we have a button that downloads a text file. On iOS this file is received in the navigationDelegate as `data:text/plain;charset=utf-8,{text}`, but on Android nothing happens. So there my research started.

On Android the WebViewClient.shouldOverrideUrlLoading is being overriden and on iOS it is WKNavigationDelegate.decidePolicyForNavigationAction.
According to [this StackOverflow answer](https://stackoverflow.com/a/59084696) the decidePolicyForNavigationAction is also used to start a download. However, on Android this is done in setDownloadListener, for example:
```
        webview.setDownloadListener(DownloadListener { url, userAgent, contentDisposition, mimetype, contentLength ->
            val i = Intent(Intent.ACTION_VIEW)
            i.data = Uri.parse(url)
            startActivity(i)
        })
```

## Proposal

My proposal is to add `setDownloadListener` to the webview and send this url to the navigation delegate. We might want to send more information, but this way the behaviour of Android and iOS are exactly the same.

**Comment by stuartmorgan** [comment] 2021-09-09 20:14
Isn't this a duplicate of https://github.com/flutter/flutter/issues/39321?

**Closed** 2021-09-10 07:52 UTC
Labels: severe: new feature, plugin, waiting for PR to land (fixed), p: first party, p: webview, proposal, passed first triage
