### ISSUE TITLE
upgraded to flutter 3.7 and had this issue ?

### ISSUE THREAD

**Issue by harryandroiddev** [flutter/flutter#120675] opened 2023-02-14 09:34 UTC
Could not build the precompiled application for the device.
Uncategorized (Xcode): Command CompileSwift failed with a nonzero exit code

Swift Compiler Error (Xcode): Type 'WKDataDetectorTypes' has no member 'WKDataDetectorTypes'
/Users/kp/.pub-cache/hosted/pub.dev/flutter_inappwebview-5.7.2+3/ios/Classes/Util.swift:85:20

flutter doctor output:

[✓] Flutter (Channel stable, 3.7.3, on macOS 12.3.1 21E258 darwin-x64, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.75.1)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

**Comment by Xazin** [comment] 2023-02-14 09:52
Seems the error is caused by flutter_inappwebview, which is not maintained by the Flutter team, maybe it's a good idea to open this issue at their repository: https://github.com/pichillilorenzo/flutter_inappwebview

**Comment by harryandroiddev** [comment] 2023-02-14 10:13
but  i am not using this dependency but i have noticed that i used a packages that uses this dependecy internally .

**Comment by huycozy** [comment] 2023-02-14 11:05
Hi @harryandroiddev 
The issue is related to a 3rd party plugin rather than to Flutter itself. Please find the existing issues or open the issue in the dedicated [repository](https://github.com/pichillilorenzo/flutter_inappwebview/issues).

Closing, as this isn't an issue with Flutter itself.  If you disagree, please write in the comments, providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`, a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that does not use 3rd party plugins and I will reopen it.
Thank you!

**Closed by huycozy** 2023-02-14 11:05 UTC
Labels: in triage
