### ISSUE TITLE
Error when using Expanded on ListView alone inside a Column  

### ISSUE THREAD

**Issue by bogdy9912** [flutter/flutter#76734] opened 2021-02-24 22:24 UTC
Hello! I got this error, and I thought that is my duty as a Flutter developer to put it here. 

```
Performing hot reload...
Syncing files to device MAR LX1A...

======== Exception caught by widgets library =======================================================
The following assertion was thrown building AnimatedBuilder(animation: AnimationController#f2789(⏭ 1.000; paused), state: _AnimatedState#50153):
'package:flutter/src/widgets/framework.dart': Failed assertion: line 5022 pos 16: 'child is! ParentDataElement<ParentData>': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

The relevant error-causing widget was: 
  Scaffold file:///E:/GitFolder/food_delivery/lib/src/presentations/cart/cart_page.dart:12:16
When the exception was thrown, this was the stack: 
#2      ParentDataElement._applyParentData.applyParentDataToChild (package:flutter/src/widgets/framework.dart:5022:16)
#3      ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4681:14)
#4      ParentDataElement._applyParentData.applyParentDataToChild (package:flutter/src/widgets/framework.dart:5023:15)
#5      ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4681:14)
#6      ParentDataElement._applyParentData.applyParentDataToChild (package:flutter/src/widgets/framework.dart:5023:15)
...
====================================================================================================
Reloaded 12 of 1412 libraries in 1,197ms.
W/Firestore(27390): (21.7.1) [WatchStream]: (999bf6) Stream closed with status: Status{code=INTERNAL, description=Internal error
W/Firestore(27390): Rst Stream, cause=null}.

```

This is the code that generate the error:

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:food_delivery/src/containers/auth/cart_container.dart';
import 'package:food_delivery/src/models/auth/index.dart';

class CartPage extends StatelessWidget {
  const CartPage({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return CartContainer(
      builder: (BuildContext context, Cart cart) {
        return Scaffold(
          appBar: AppBar(
            title: const Text('cart'),
          ),
          body: cart == null
              ? const Center(child: Text('Nu ai produse in cos'))
              : Column(
                children: <Widget>[
                  Expanded(
                    child: ListView.builder(
                        itemCount: cart.items.length,
                        itemBuilder: (BuildContext context, int index) {
                          final CartItem item = cart.items[index];
                          return ListTile(
                            title: Text(item.name),
                            trailing: Text((item.quantity * item.price).toStringAsFixed(2)+ ' lei'),
                            subtitle: Text('${item.quantity} x ${item.price} lei'),
                          );
                        },
                      ),
                  ),
                ],
              ),
        );
      },
    );
  }
}
```
</details>

Solution: The problem is solved when I put another widget inside the column. I think that is kinda understandable to put one more widget when you use Expanded in a Column, but an error is an error.

I hope I put everything that was needed in the post.

**Comment by dubey2k** [comment] 2021-02-25 01:11
Have you tried using shrinkWrap property? Most probably it will solve this.

**Comment by pedromassangocode** [comment] 2021-02-25 07:49
Hi @bogdy9912 
Thanks for filling this. Can you provide a reproducible code sample that I can just copy/paste to reproduce the issue? the code above makes references to missing files.
Please do provide your `flutter doctor -v` as well.

Thank you

**Comment by bogdy9912** [comment] 2021-02-25 10:21
The error appears when I run those 2 codes one after another. Not only when I run directly the code that I wrote when I was filling the issue. 

```
import 'package:flutter/material.dart';

class Lala extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('lala'),
      ),
      body: Expanded(
        child: ListView.builder(
          itemCount: 10,
          itemBuilder: (BuildContext context, int index) => Container(),
        ),
      ),
    );
  }
}
```

```
import 'package:flutter/material.dart';

class Lala extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('lala'),
      ),
      body: Column(
        children: [
          Expanded(
            child: ListView.builder(
              itemCount: 10,
              itemBuilder: (BuildContext context, int index) => Container(),
            ),
          ),
        ],
      ),
    );
  }
}

```

and the doctor:
```

E:\GitFolder\food_delivery>flutter doctor -v
[√] Flutter (Channel stable, 1.22.5, on Microsoft Windows [Version 10.0.19041.804], locale en-US)
    • Flutter version 1.22.5 at C:\flutter
    • Framework revision 7891006299 (3 months ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\HP\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 29.0.2
    • ANDROID_HOME = C:\Users\HP\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\AdoptOpenJDK\jdk-11.0.6.10-hotspot\bin\java
    • Java version OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.6+10)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] Connected device (1 available)
    • MAR LX1A (mobile) • L2NDU20110012638 • android-arm64 • Android 10 (API 29)

! Doctor found issues in 2 categories.
```

**Comment by pedromassangocode** [comment] 2021-02-25 12:14
Hi @bogdy9912 
I cannot reproduce this issue on latest stable.

Please upgrade your flutter version, if the issue still happening, please provide your `flutter doctor -v`.
Thank you

**Comment by bogdy9912** [comment] 2021-02-25 19:49
the problem persist, even if I upgrade my version to the latest one. The error appear only on hot reload. If I restart everything is fine. 


```
E:\GitFolder\food_delivery>flutter doctor -v
[√] Flutter (Channel stable, 1.22.6, on Microsoft Windows [Version 10.0.19041.804],
    locale en-US)
    • Flutter version 1.22.6 at C:\flutter
    • Framework revision 9b2d32b605 (5 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\HP\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 29.0.2
    • ANDROID_HOME = C:\Users\HP\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\AdoptOpenJDK\jdk-11.0.6.10-hotspot\bin\java
    • Java version OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.6+10)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more
      details.

[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for
      detailed instructions).

[√] Connected device (1 available)
    • MAR LX1A (mobile) • L2NDU20110012638 • android-arm64 • Android 10 (API 29)

! Doctor found issues in 2 categories.

```

**Comment by pedromassangocode** [comment] 2021-02-26 08:00
Hi @bogdy9912 
I can reproduce the problem, but it is caused by the wrong usage of the `Expanded` widget. As the docs says, it must be a descendant of a `Column`, `Row` or `Flex` widget.

![Screen Shot 2021-02-26 at 08 58 44](https://user-images.githubusercontent.com/67424416/109272216-d7c8c100-7810-11eb-868b-5d5c2e6d822c.png)


 Here is a working example for your use-case, you can simply remove the Expanded widget:

```dart
class Lala extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('lala'),
      ),
      body: ListView.builder(
        itemCount: 12,
        itemBuilder: (BuildContext context, int index) => Container(
          height: 40,
          margin: EdgeInsets.symmetric(vertical: 16),
          color: Colors.blue,
        ),
      ),
    );
  }
}
```

Since the docs is clear about that, I feel safe to close this issue as working as intended.
Thank you

**Closed by pedromassangocode** 2021-02-26 08:00 UTC
Labels: in triage
