### ISSUE TITLE
Set the toolbarOptions property to the Textfield widget,and then throw an exception

### ISSUE THREAD

**Issue by zzzj1233** [flutter/flutter#45832] opened 2019-11-30 07:24 UTC
When using the TextField component, **set the toolbarOptions property to the component**, and then throw an exception。

Here is the exception prompt：
**type 'ToolbarOptions' is not a subtype of type 'bool'**

Here is my code：
```
         TextField(
                toolbarOptions: ToolbarOptions(
                copy: true, cut: true, paste: true, selectAll: true)
           )
```

When the exception was thrown, this was the stack:：
#0      new TextField (package:flutter/src/material/text_field.dart:308:40)

**Comment by iapicca** [comment] 2019-12-02 08:25
Hi @zzzj1233 
the issue is being addressed with this [PR](https://github.com/flutter/flutter/issues/40664)
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you

https://github.com/flutter/flutter/issues/45534

**Closed by iapicca** 2019-12-02 08:25 UTC
