### ISSUE TITLE
Child Button's click events failing when using StickySliver inside CustomScrollView 

### ISSUE THREAD

**Issue by Fauzdar1** [flutter/flutter#106261] opened 2022-06-19 11:09 UTC
## Synopsis
While improving UI of a production app, I tried creating a Sticky header and it works good enough (with lag though), except that no click events work on the header when it's sticky on top. This header is a Row which contains `TextButton` in one screen and in other, it's a Container containing Input layout for Search.

I had asked a question on StackOverFlow three days ago but no response on it so far. Question link - [Click Events doesn't work when sticky, using custom Sticky Sliver - Flutter](https://stackoverflow.com/questions/72652589/click-events-doesnt-work-when-sticky-using-custom-sticky-sliver-flutter)

## Steps to Reproduce

1. Implement the `StickySliver` as provided in the code sample in `CustomScrollView`.
2. Pass it a child widget containing buttons, in my case a Row with three buttons to make a custom `TabLayout`.
3. Now, any child of this `StickySliver` will be clickable until it's at the sticky position.
4. Once this StickySliver is at top as Sticky, no click-events inside the child will work, not even ripple of the buttons, nothing.
5. Scroll up again to remove the StickySliver from top and click events work again.
6. Scroll down and on top, the click events don't work, log shows nothing.

**Expected results:** 
The click events never stop working and works properly even when the child is sticking at the top like a header.

**Actual results:** 
The animation works properly, although it lags and has performance issues for some reason. But, the click events doesn't work. The OP who provided the StickyHeader code said:

> Flutter uses a hit test to fire the gesture detector. It won't fire if that fails.

<details>
<summary>Code used:</summary>

### Creating the StickySliver
```dart
class RenderStickySliver extends RenderSliverSingleBoxAdapter {
  RenderStickySliver({RenderBox? child}) : super(child: child);

  @override
  void performLayout() {
    geometry = SliverGeometry.zero;

    child?.layout(constraints.asBoxConstraints(), parentUsesSize: true);

    double childExtent = child?.size.height ?? 0;

    geometry = SliverGeometry(
        paintExtent: childExtent,
        maxPaintExtent: childExtent,
        paintOrigin: constraints.scrollOffset);

    setChildParentData(child!, constraints, geometry!);
  }
}

class StickySliver extends SingleChildRenderObjectWidget {
  const StickySliver({Widget? child, Key? key}) : super(child: child, key: key);

  @override
  RenderObject createRenderObject(BuildContext context) => RenderStickySliver();
}
```

### Using in layout
```dart
CustomScrollView(
  slivers: [
    SliverToBoxAdapter(
      child: RandomWidget()
    ),
    StickySliver(
      child: RowWithTextButtons()
    ),
    SliverToBoxAdapter(
      child: RandomWidget()
    ),
  ],
)
```

</details>

<details>
  <summary>Logs</summary>

Log shows nothing when the sticky header is clicked on one screen but it shows below lines on the other screen where Google Map is used. Also, clicking the sticky header on this map screen hides the Map markers for a second, possible layout re-render. Apart from this, no change/log/exception is there.
```
[ +562 ms] I/Counters(30707): exceeded sample count in FrameTime
[   +5 ms] D/Surface (30707): lockHardwareCanvas
[   +3 ms] E/FrameEvents(30707): updateAcquireFence: Did not find frame.
[   +9 ms] D/Surface (30707): lockHardwareCanvas
[   +4 ms] E/FrameEvents(30707): updateAcquireFence: Did not find frame.
[ +677 ms] I/Counters(30707): exceeded sample count in FrameTime
[  +10 ms] D/Surface (30707): lockHardwareCanvas
[  +10 ms] E/FrameEvents(30707): updateAcquireFence: Did not find frame.
[   +3 ms] D/Surface (30707): lockHardwareCanvas
[   +3 ms] E/FrameEvents(30707): updateAcquireFence: Did not find frame.
[  +58 ms] D/Surface (30707): lockHardwareCanvas
[   +2 ms] I/Counters(30707): exceeded sample count in FrameTime
[   +1 ms] E/FrameEvents(30707): updateAcquireFence: Did not find frame.
[  +12 ms] D/Surface (30707): lockHardwareCanvas
[   +3 ms] E/FrameEvents(30707): updateAcquireFence: Did not find frame.
[ +586 ms] I/Counters(30707): exceeded sample count in FrameTime
[   +9 ms] I/Counters(30707): exceeded sample count in FrameTime
[   +1 ms] D/Surface (30707): lockHardwareCanvas
[   +1 ms] E/FrameEvents(30707): updateAcquireFence: Did not find frame.
[  +31 ms] D/Surface (30707): lockHardwareCanvas
[   +3 ms] E/FrameEvents(30707): updateAcquireFence: Did not find frame.

```

### flutter analyze
```
Analyzing android...
No issues found! (ran in 1.0s)
```

### flutter doctor -v
```
[√] Flutter (Channel stable, 3.0.2, on Microsoft Windows [Version 10.0.19043.1766], locale en-IN)
    • Flutter version 3.0.2 at C:\Users\XXXX\Documents\FlutterSDK
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cd41fdd495 (11 days ago), 2022-06-08 09:52:13 -0700
    • Engine revision f15f824b57
    • Dart version 2.17.3
    • DevTools version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0-rc1)
    • Android SDK at C:\Users\XXXX\AppData\Local\Android\Sdk
    • Platform android-32, build-tools 32.0.0-rc1
    • ANDROID_SDK_ROOT = C:\Users\XXXX\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Build Tools 2019 16.11.11)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
    • Visual Studio Build Tools 2019 version 16.11.32228.343
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] IntelliJ IDEA Ultimate Edition (version 2021.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2021.3.2
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code (version 1.66.2)
    • VS Code at C:\Users\XXXX\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (3 available)
    • RMX3392 (mobile)  • KZZXGAXXXXXXXXXX • android-arm64  • Android 12 (API 31)
    • Windows (desktop) • windows          • windows-x64    • Microsoft Windows [Version 10.0.19043.1766]
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 102.0.5005.115

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by Fauzdar1** [comment] 2022-06-20 10:24
Wait, I'm providing a sample Flutter Repo.

**Comment by Fauzdar1** [comment] 2022-06-20 11:06
@darshankawar  Please check this repository out. It's working and it has that same problem.

https://github.com/Fauzdar1/sticky_sliver

I'm also attaching this screen recording.

https://user-images.githubusercontent.com/62703211/174588377-309a579b-c5de-4413-9023-911f55b23255.mp4

**Comment by darshankawar** [comment] 2022-06-21 05:40
Thanks for the update. Using it, I do see the same behavior, ie, when the header is at the top of the screen, the tabs aren't clickable, but when we scroll it down, they are clickable:


https://user-images.githubusercontent.com/67046386/174723869-5d9c55e8-d54a-4f56-9280-249076e74de4.mov

<details>
<summary> stable, master flutter doctor -v </summary>

```

[✓] Flutter (Channel stable, 3.0.2, on macOS 12.2.1 21D62 darwin-x64, locale
    en-GB)
    • Flutter version 3.0.2 at /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cd41fdd495 (13 days ago), 2022-06-08 09:52:13 -0700
    • Engine revision f15f824b57
    • Dart version 2.17.3
    • DevTools version 2.12.2

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

[✓] Flutter (Channel master, 3.1.0-0.0.pre.1317, on macOS 12.2.1 21D62
    darwin-x64, locale en-GB)
    • Flutter version 3.1.0-0.0.pre.1317 on channel master at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d4929bc828 (5 hours ago), 2022-06-20 20:09:05 -0400
    • Engine revision ceac23d7a9
    • Dart version 2.18.0 (build 2.18.0-190.0.dev)
    • DevTools version 2.14.0
    
[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.



```

</details>

<details>
<summary> complete runnable code sample </summary>

```

import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';
import 'package:fluttertoast/fluttertoast.dart';


void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const Home(),
    );
  }
}

class Home extends StatefulWidget {
  const Home({Key? key}) : super(key: key);

  @override
  State<Home> createState() => _HomeState();
}

class _HomeState extends State<Home> {
  bool value = false;
  TextStyle textStyle = const TextStyle(color: Colors.white);

  @override
  Widget build(BuildContext context) {
    return SafeArea(
      child: CustomScrollView(
        slivers: [
          SliverToBoxAdapter(
            child: CustomContainer(
              isOdd: value,
            ),
          ),
          StickySliver(
            child: Container(
              color: Colors.amber,
              padding: const EdgeInsets.all(10),
              child: Row(
                mainAxisAlignment: MainAxisAlignment.spaceEvenly,
                children: [
                  buildTextButton('First'),
                  buildTextButton('Second'),
                  buildTextButton('Third'),
                ],
              ),
            ),
          ),
          SliverToBoxAdapter(
            child: CustomContainer(
              isOdd: !value,
            ),
          ),
          SliverToBoxAdapter(
            child: CustomContainer(
              isOdd: value,
            ),
          ),
          SliverToBoxAdapter(
            child: CustomContainer(
              isOdd: !value,
            ),
          ),
          SliverToBoxAdapter(
            child: CustomContainer(
              isOdd: value,
            ),
          ),
        ],
      ),
    );
  }

  TextButton buildTextButton(String text) {
    return TextButton(
      onPressed: () {
        toggleBool();
        '$text Clicked'.toast;
      },
      child: Text(
        text,
        style: textStyle,
      ),
    );
  }

  toggleBool() => setState(() => value = !value);
}

class StickySliver extends SingleChildRenderObjectWidget {
  const StickySliver({Widget? child, Key? key}) : super(child: child, key: key);

  @override
  RenderObject createRenderObject(BuildContext context) =>
      _RenderStickySliver();
}

class _RenderStickySliver extends RenderSliverSingleBoxAdapter {
  _RenderStickySliver({RenderBox? child}) : super(child: child);

  @override
  void performLayout() {
    geometry = SliverGeometry.zero;

    child?.layout(constraints.asBoxConstraints(), parentUsesSize: true);

    double childExtent = child?.size.height ?? 0;

    geometry = SliverGeometry(
        paintExtent: childExtent,
        maxPaintExtent: childExtent,
        paintOrigin: constraints.scrollOffset);

    setChildParentData(child!, constraints, geometry!);
  }
}

class CustomContainer extends StatelessWidget {
  final bool isOdd;

  const CustomContainer({Key? key, required this.isOdd}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return AnimatedContainer(
      duration: const Duration(milliseconds: 300),
      height: 300,
      color: isOdd ? Colors.cyan[200] : Colors.red[200],
    );
  }
}

extension ToastUtils on String {
  void get toast => Fluttertoast.showToast(
      msg: this,
      textColor: Colors.white,
      backgroundColor: Colors.blue,
      toastLength: Toast.LENGTH_SHORT);
}

```

</details>

**Comment by darshankawar** [comment] 2022-06-22 08:30
Visiting this issue again,  I used Flutter's snackbar as below in provided code sample and using it, but seem to show same behavior. 

```
TextButton buildTextButton(String text) {
    return TextButton(
      onPressed: () {
        toggleBool();
       // '$text Clicked'.toast;
        final snackBar = SnackBar(
          content: Text('$text'),
         // action: SnackBarAction,
        );
        ScaffoldMessenger.of(context).showSnackBar(snackBar);
      },
      child: Text(
        text,
        style: textStyle,
      ),
    );
  }
```

**Comment by Fauzdar1** [comment] 2022-06-22 09:04
@Piinks  This issue is not related to any third party package and I've only used [FlutterToast](https://pub.dev/packages/fluttertoast). It is a part of Flutter framework. In fact, I don't want to use third party packages for Sticky Headers which is why I'm here trying to get this issue resolved.

Also, as I had mentioned earlier, I had already asked [this question on StackOverFlow](https://stackoverflow.com/q/72652589/8244632) but there is no response, not even a comment.

**Comment by Piinks** [comment] 2022-06-22 16:38
`SliverToBoxAdapter / RenderSliverToBoxAdaptor` also implements `SingleChildRenderObjectWidget 
 / RenderSliverSingleBoxAdapter`. Changing your `StickySliver` out for a simple `SliverToBoxAdaptor` shows no issue with tapping on buttons.

The issue is in your custom sliver.

**Comment by Fauzdar1** [comment] 2022-06-22 18:48
But, doesn't that defeat the whole purpose of creating this custom one, to make the child widget stick on top while scrolling? seems it surely does.

**Comment by Piinks** [comment] 2022-06-22 18:59
@Fauzdar1 I am not saying that you should replace your StickySliver with a SliverToBoxAdapter, it was intended to illustrate the issue is not coming from the underlying classes as you suggested in https://github.com/flutter/flutter/issues/106261#issuecomment-1162846537. 

Regrettably, the Flutter issue tracker cannot provide technical support debugging custom code. It is intended for addressing issues within the Flutter framework. Your issue lies within your custom class. It does not exist within the framework. You may not be setting your SliverGeometry correctly, or may need to handle hit testing differently for your custom sliver. Perhaps looking at the RenderSliverPersistentHeader classes can offer some guidance.

If stackoverflow was not of help, I would recommend exploring our other community channels for support and troubleshooting: https://flutter.dev/community

I am going to close this issue as it does not involve an issue with the framework from what has been reported thus far. If you can reproduce the issue using widgets from the framework, let us know and we can re-open this to take another look.

**Closed by Piinks** 2022-06-22 18:59 UTC
Labels: framework, f: scrolling, d: stackoverflow
