### ISSUE TITLE
Web Hot Restart loses current URL (worked in Stable 2.0.4)

### ISSUE THREAD

**Issue by zambetpentru** [flutter/flutter#86605] opened 2021-07-17 14:29 UTC
Greetings!

In Flutter Web Stable 2.0.4 when I do a Hot restart it resets the state as expected and keeps the same URL. Since upgrading including to beta 2.2.0-10.2.pre and the latest master today, 2.4.0-5.0.pre.79, when I do a hot restart the URL resets to the default one. This adds a lot of extra clicking when I'm doing iterative development.

This is a sample simple flutter program that demonstrates the issue
[main.dart.txt](https://github.com/flutter/flutter/files/6834819/main.dart.txt)]

Any idea what update made this change and can we revert / fix it / have it as an option?

**Comment by TahaTesser** [comment] 2021-07-19 13:54
Hi @zambetpentru 
I see there's an open issue addressing the case you described.
Please follow up on that issue, Closing as duplicate of https://github.com/flutter/flutter/issues/79241
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-07-19 13:54 UTC
Labels: in triage
