### ISSUE TITLE
Using CupertinoDatePicker with WebView will cause the component to become unresponsive

### ISSUE THREAD

**Issue by hellohejinyu** [flutter/flutter#108409] opened 2022-07-27 02:21 UTC
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. Open the date picker, then scroll up and down, there is a chance to trigger the bug, for details, see the video below

https://user-images.githubusercontent.com/8766034/181145720-0c594121-36ff-4852-8ac1-51a78a8ff508.mp4

3. And I also have this problem on my iPhone device, so I think it has nothing to do with the device, it should be a bug of Flutter or Webview.

**Expected results:** 
Time picker works fine

**Actual results:** 
The time picker freezes, can't continue scrolling, and the whole application is slow, but there isn't any error log output.

<details>
<summary>Code sample</summary>

```dart
/// you can use the code repository
/// https://github.com/hellohejinyu/webview_with_datepicker

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: const WebView(
        initialUrl: 'https://so.com',
        javascriptMode: JavascriptMode.unrestricted,
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          showCupertinoModalPopup(
            context: context,
            builder: (context) {
              return Container(
                color: Colors.white,
                height: 300,
                child: CupertinoDatePicker(
                  use24hFormat: true,
                  onDateTimeChanged: (_) {
                    //
                  },
                ),
              );
            },
          );
        },
        tooltip: 'Open DatePicker',
        child: const Icon(Icons.calendar_today),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
```

</details>

<details>
  <summary>Logs</summary>

```
[  +35 ms] D/View.DrawScrollBar(22956): mDrawScrollBar: true
[  +74 ms] D/View.DrawScrollBar(22956): mDrawScrollBar: true
[  +42 ms] D/View.DrawScrollBar(22956): mDrawScrollBar: true
[        ] I/System  (22956): Daemon delayGCRequest, sDelayGCRequest=true, delay=false, sPendingGCRequest=false
[   +4 ms] D/View.DrawScrollBar(22956): mDrawScrollBar: true
[  +17 ms] D/View.DrawScrollBar(22956): mDrawScrollBar: true
[ +189 ms] I/chatty  (22956): uid=10191(com.example.webview_with_datepicker) identical 8 lines
[   +1 ms] D/View.DrawScrollBar(22956): mDrawScrollBar: true
[  +25 ms] D/View.DrawScrollBar(22956): mDrawScrollBar: true
[ +109 ms] I/chatty  (22956): uid=10191(com.example.webview_with_datepicker) identical 5 lines
[        ] D/View.DrawScrollBar(22956): mDrawScrollBar: true
[   +7 ms] D/View.DrawScrollBar(22956): mDrawScrollBar: true
[ +996 ms] I/chatty  (22956): uid=10191(com.example.webview_with_datepicker) identical 26 lines
[        ] D/View.DrawScrollBar(22956): mDrawScrollBar: true
[ +977 ms] I/PressGestureDetector(22956): dispatchTouchEvent isWeChat = false, isMouseInPcMode = false
[+1149 ms] I/PressGestureDetector(22956): dispatchTouchEvent isWeChat = false, isMouseInPcMode = false
[+4928 ms] I/PressGestureDetector(22956): dispatchTouchEvent isWeChat = false, isMouseInPcMode = false
[+1397 ms] I/PressGestureDetector(22956): dispatchTouchEvent isWeChat = false, isMouseInPcMode = false
[+7447 ms] I/chatty  (22956): uid=10191(com.example.webview_with_datepicker) identical 15 lines
[        ] I/PressGestureDetector(22956): dispatchTouchEvent isWeChat = false, isMouseInPcMode = false
[+4381 ms] I/PressGestureDetector(22956): dispatchTouchEvent isWeChat = false, isMouseInPcMode = false
[+1207 ms] I/chatty  (22956): uid=10191(com.example.webview_with_datepicker) identical 2 lines
```

```
Analyzing webview_with_datepicker...                                    
No issues found! (ran in 1.2s)
```

```
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.5 21G72 darwin-arm, locale zh-Hans-CN)
    • Flutter version 3.0.5 at /Users/Jinyu/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (13 days ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/Jinyu/Library/Android/sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • ANDROID_HOME = /Users/Jinyu/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.69.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.44.0

[✓] Connected device (1 available)
    • DT1901A (mobile) • 1dc17a1a • android-arm64 • Android 10 (API 29)

[✓] HTTP Host Availability
    • All required HTTP hosts are available
```

</details>

**Comment by maheshmnj** [comment] 2022-07-27 08:27
Hi @hellohejinyu, Thanks for filing the issue. I am able to reproduce the issue on the latest stable channel, But not on the master channel.

master | Stable 
:-: | :-:
<video src='https://user-images.githubusercontent.com/31410839/181199009-b11891c6-3cc1-4bb7-926a-ce5bfc8c32bc.mp4' width=180/> | <video src='https://user-images.githubusercontent.com/31410839/181199120-e1284187-1834-40bb-80f1-ca739271f8a3.mp4' width=180/> 


Looks like this is fixed on the master. You may verify this by switching to the master channel by running 

```
flutter channel master
flutter upgrade
```
The fix should land on the stable in the future releases of flutter. I am going to close this issue since this works fine on the master channel.



<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.4 21F79 darwin-arm, locale en-IN)
    • Flutter version 3.0.5 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (5 days ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-32, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.67.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.44.0

[✓] Connected device (3 available)
    • sdk gphone arm64 (mobile) • emulator-5554 • android-arm64  • Android 11 (API 30) (emulator)
    • macOS (desktop)           • macos         • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)              • chrome        • web-javascript • Google Chrome 103.0.5060.114

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

```
[✓] Flutter (Channel master, 3.1.0-0.0.pre.1868, on macOS 12.4 21F79 darwin-arm, locale en-IN)
    • Flutter version 3.1.0-0.0.pre.1868 on channel master at /Users/mahesh/Documents/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 925bee92e7 (24 hours ago), 2022-07-26 04:49:06 -0400
    • Engine revision 5dcaeae656
    • Dart version 2.19.0 (build 2.19.0-34.0.dev)
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-32, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13C100
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.69.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.44.0

[✓] Connected device (3 available)
    • Redmi K20 Pro (mobile) • 192.168.1.2:5555 • android-arm64  • Android 11 (API 30)
    • macOS (desktop)        • macos            • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)           • chrome           • web-javascript • Google Chrome 103.0.5060.134

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Closed by maheshmnj** 2022-07-27 08:27 UTC
Labels: in triage
