### ISSUE TITLE
Crash during launch (SIGSEGV)

### ISSUE THREAD

**Issue by quetool** [flutter/flutter#31257] opened 2019-04-18 12:32 UTC
Sometimes my app crashes during launch on Android with device Samsung Galaxy J5 Prime
Here is the log until it crashes

```
Launching lib/main.dart on SM G570M in debug mode...
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
Built build/app/outputs/apk/debug/app-debug.apk.
I/FA      (17014): Tag Manager is not found and thus will not be used
D/OpenGLRenderer(17014): HWUI GL Pipeline
I/zygote  (17014): Do partial code cache collection, code=31KB, data=27KB
I/zygote  (17014): After code cache collection, code=29KB, data=26KB
I/zygote  (17014): Increasing code cache capacity to 128KB
D/InputTransport(17014): Input channel constructed: fd=88
D/ViewRootImpl@30c7520[MainActivity](17014): setView = DecorView@576777f[MainActivity] TM=true MM=false
V/InputMethodManager(17014): Not IME target window, ignoring
D/ViewRootImpl@30c7520[MainActivity](17014): dispatchAttachedToWindow
V/Surface (17014): sf_framedrop debug : 0x4f4c, game : false, logging : 0
D/ViewRootImpl@30c7520[MainActivity](17014): Relayout returned: old=[0,0][0,0] new=[0,0][720,1280] result=0x7 surface={valid=true 3535652864} changed=true
I/OpenGLRenderer(17014): Initialized EGL, version 1.4
D/OpenGLRenderer(17014): Swap behavior 2
D/libGLESv1(17014): STS_GLApi : DTS, ODTC are not allowed for Package : co.myapp.myappmvp
D/mali_winsys(17014): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, egl_color_buffer_format *, EGLBoolean) returns 0x3000,  [720x1280]-format:1
D/OpenGLRenderer(17014): eglCreateWindowSurface = 0xce77f6a0
D/SurfaceView(17014): BG show() Surface(name=Background for - SurfaceView - co.myapp.myappmvp/co.myapp.myappmvp.MainActivity@506e576@0) io.flutter.view.FlutterView{506e576 VFE...... .F....ID 0,0-720,1280}
V/Surface (17014): sf_framedrop debug : 0x4f4c, game : false, logging : 0
D/SurfaceView(17014): surfaceCreated 1 #8 io.flutter.view.FlutterView{506e576 VFE...... .F....ID 0,0-720,1280}
D/mali_winsys(17014): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, egl_color_buffer_format *, EGLBoolean) returns 0x3000,  [720x1280]-format:1
D/SurfaceView(17014): surfaceChanged (720,1280) 1 #8 io.flutter.view.FlutterView{506e576 VFE...... .F....ID 0,0-720,1280}
D/ViewRootImpl@30c7520[MainActivity](17014): MSG_RESIZED_REPORT: frame=Rect(0, 0 - 720, 1280) ci=Rect(0, 42 - 0, 0) vi=Rect(0, 42 - 0, 0) or=1
D/ViewRootImpl@30c7520[MainActivity](17014): MSG_WINDOW_FOCUS_CHANGED 1
V/InputMethodManager(17014): Starting input: tba=android.view.inputmethod.EditorInfo@d1dd777 nm : co.myapp.myappmvp ic=null
I/InputMethodManager(17014): startInputInner - mService.startInputOrWindowGainedFocus
I/System.out(17014): (HTTPLog)-Static: isSBSettingEnabled false
I/System.out(17014): (HTTPLog)-Static: isSBSettingEnabled false
D/InputTransport(17014): Input channel constructed: fd=93
D/ViewRootImpl@30c7520[MainActivity](17014): Relayout returned: old=[0,0][720,1280] new=[0,0][720,1280] result=0x3 surface={valid=true 3535652864} changed=false
I/System  (17014): Loaded time zone names for "es_AR" in 173ms (158ms in ICU)
V/InputMethodManager(17014): Starting input: tba=android.view.inputmethod.EditorInfo@50c4d nm : co.myapp.myappmvp ic=null
D/libGLESv2(17014): STS_GLApi : DTS, ODTC are not allowed for Package : co.myapp.myappmvp
F/libc    (17014): Fatal signal 11 (SIGSEGV), code 128, fault addr 0x0 in tid 17214 (1.ui)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'samsung/on5xelteub/on5xelte:8.0.0/R16NW/G570MUBU3CRK1:user/release-keys'
Revision: '5'
ABI: 'arm'
pid: 17014, tid: 17214, name: 1.ui  >>> co.myapp.myappmvp <<<
signal 11 (SIGSEGV), code 128 (SI_KERNEL), fault addr 0x0
    r0 d117479c  r1 d11747e8  r2 7d180ce6  r3 00000008
    r4 d1174790  r5 00000000  r6 00000000  r7 af872e26
    r8 7d180ce6  r9 ac0f4182  sl afb93716  fp afb8dc2a
    ip d29f22c0  sp ac0f4c26  lr af9de283  pc f2dbcc00  cpsr 600d0010
backtrace:
    #00 pc 00018c00  /system/lib/libc.so (sigsetjmp+136)
    #01 pc af9de281  <unknown>
Lost connection to device.
Exited (sigterm)
```

`flutter doctor -v` output

```
[✓] Flutter (Channel dev, v1.4.10, on Mac OS X 10.13.6 17G6030, locale es-AR)
    • Flutter version 1.4.10 at /Users/alfredo/Desktop/flutter
    • Framework revision 6ba720a489 (2 weeks ago), 2019-04-04 11:27:41 -0400
    • Engine revision 5944867cab
    • Dart version 2.2.1 (build 2.2.1-dev.3.0 None)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/alfredo/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 2.0.0
    • CocoaPods version 1.6.0.beta.2

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 30.0.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.31.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.25.1

[✓] Connected device (2 available)
    • SM G570M  • 42005356b2e42487                     • android-arm • Android 8.0.0 (API 26) (emulator)
    • iPhone Xʀ • 39418FB6-C582-4615-985D-77B313113DB3 • ios         • iOS 12.1 (simulator)

• No issues found!
```

**Comment by iapicca** [comment] 2020-03-09 12:47
Hi @quetool 
are you still experiencing the issue with the latest stable version of Flutter?
Thank you

**Comment by mraleph** [comment] 2020-03-23 20:23
Duplicate of #27077

**Closed by mraleph** 2020-03-23 20:23 UTC
Labels: framework, severe: crash, waiting for customer response, ▣ platform-android
