### ISSUE TITLE
IconTheme docs page has mysterious no-name properties

### ISSUE THREAD

**Issue by abarth** [flutter/flutter#9556] opened 2017-04-24 13:26 UTC
https://docs.flutter.io/flutter/material/IconTheme-class.html

![screen shot 2017-04-24 at 6 26 24 am](https://cloud.githubusercontent.com/assets/112007/25339276/fa96fe5c-28b6-11e7-8551-886eb453c01b.png)

**Comment by Hixie** [comment] 2017-04-24 14:54
Dupe of https://github.com/dart-lang/dartdoc/issues/1367

**Closed by Hixie** 2017-04-24 14:54 UTC
