### ISSUE TITLE
DecorationImage removes shadow from a container

### ISSUE THREAD

**Issue by kirill-21** [flutter/flutter#82487] opened 2021-05-13 22:54 UTC
With image:
![image](https://user-images.githubusercontent.com/63228361/118197311-5835b000-b457-11eb-9ab9-865c9aec27d1.png)

Without image:
![image](https://user-images.githubusercontent.com/63228361/118197329-61268180-b457-11eb-9408-361f2ce91e97.png)
```
child: Container(
                          width: 425.0 * AppScale.amount,
                          height: 225.0 * AppScale.amount,
                          decoration: BoxDecoration(
                            borderRadius: BorderRadius.all(
                              Radius.circular(Corners.med),
                            ),
                            color: theme.kTitleBarColor,
                            boxShadow: [
                              BoxShadow(
                                color: Colors.black.withOpacity(0.09),
                                spreadRadius: 0.0,
                                blurRadius: 8.0 * AppScale.amount,
                                offset: Offset(
                                  0.0 * AppScale.amount,
                                  2.0 * AppScale.amount,
                                ),
                              ),
                            ],
                              image: DecorationImage(
                                image: AssetImage('resources/test.jpg'),

                              )
                          ),
```

Flutter version: latest from stable channel

**Comment by pedromassangocode** [comment] 2021-05-14 10:22
Hi @kirill-21 
I cannot reproduce this issue on the latest master/stable channel using the code bellow.

![Screen Shot 2021-05-14 at 11 19 30](https://user-images.githubusercontent.com/67424416/118257269-5810d100-b4a6-11eb-9ab8-33fdd170e6af.png)

Can you please provide your `flutter doctor -v` and a code that reproduce the issue?
Thank you

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      home: Scaffold(
        body: Center(
          child: Container(
            width: 425.0,
            height: 225.0,
            decoration: BoxDecoration(
              borderRadius: BorderRadius.all(
                Radius.circular(12),
              ),
              color: Colors.white,
              boxShadow: [
                BoxShadow(
                  color: Colors.black,
                  spreadRadius: 0.0,
                  blurRadius: 16.0,
                  offset: Offset(
                    0.0,
                    2.0,
                  ),
                ),
              ],
              image: DecorationImage(
                image: AssetImage('assets/images/logo.png'),
              ),
            ),
          ),
        ),
      ),
    );
  }
}

```
</details>


<details>
<summary>flutter doctor -v</summary>

```console
/Users/pedromassango/Code/flutter_master/bin/flutter doctor --verbose
[✓] Flutter (Channel master, 2.3.0-2.0.pre.163, on macOS 11.2.3 20D91 darwin-x64, locale en-AO)
    • Flutter version 2.3.0-2.0.pre.163 at /Users/pedromassango/Code/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 298f18b592 (31 hours ago), 2021-05-12 20:50:14 -0700
    • Engine revision a339374296
    • Dart version 2.14.0 (build 2.14.0-109.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/pedromassango/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2021.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 56.0.5
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.2.3 20D91 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 90.0.4430.212

• No issues found!

```
</details>

**Comment by kirill-21** [comment] 2021-05-14 10:38
> flutter doctor -v
The code is in the first message
![image](https://user-images.githubusercontent.com/63228361/118259304-abd8e580-b4b9-11eb-9c08-ba892b687e33.png)

**Comment by pedromassangocode** [comment] 2021-05-14 11:47
Hi @kirill-21 
I've set the opacity to `.15` using the code (`Colors.red.withOpacity(0.15)`) and I'm still able to see the color. Can you please provide a code that reproduces the issue?

![Screen Shot 2021-05-14 at 12 44 14](https://user-images.githubusercontent.com/67424416/118266149-184fe680-b4b2-11eb-86a0-0722a303fccd.png)

![Screen Shot 2021-05-14 at 12 46 57](https://user-images.githubusercontent.com/67424416/118266427-7bda1400-b4b2-11eb-8189-0fa111c81402.png)

**Comment by kirill-21** [comment] 2021-05-14 12:16
> Hi @kirill-21
> I've set the opacity to `.15` using the code (`Colors.red.withOpacity(0.15)`) and I'm still able to see the color. Can you please provide a code that reproduces the issue?
```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      home: Scaffold(
        body: Center(
          child: Container(
            width: 425.0,
            height: 225.0,
            decoration: BoxDecoration(
              borderRadius: BorderRadius.all(
                Radius.circular(12),
              ),
              color: Colors.white,
              boxShadow: [
                BoxShadow(
                  color: Colors.deepPurple.withOpacity(0.15),
                  spreadRadius: 0.0,
                  blurRadius: 8.0,
                  offset: Offset(
                    0.0,
                    2.0,
                  ),
                ),
              ],
              image: DecorationImage(
                image: AssetImage('assets/test.jpg'),
              ),
            ),
          ),
        ),
      ),
    );
  }
}
```
![image](https://user-images.githubusercontent.com/63228361/118269227-265c3200-b4c7-11eb-9673-acd2af7bbd3e.png)

The image covers the shadow below itself

**Comment by pedromassangocode** [comment] 2021-05-14 13:33
Hi @kirill-21 
It doesn't, the thing is that you are not able to see the color because of the contrast of the image. If you build this on web and you zoom it, you will clearly see shadow on top and below the image.

![image](https://user-images.githubusercontent.com/67424416/118276725-dcbc1900-b4bf-11eb-80e5-0462d04d8063.png)

### Zoomed image - notice the shadow color partially visible

![Screen Shot 2021-05-14 at 14 32 29](https://user-images.githubusercontent.com/67424416/118277921-412ba800-b4c1-11eb-8281-06226e087af3.png)


To fix this, you can simply increase the opacity of your shadow's color.

**Comment by kirill-21** [comment] 2021-05-14 13:51
> Hi @kirill-21
> It doesn't, the thing is that you are not able to see the color because of the contrast of the image. If you build this on web and you zoom it, you will clearly see shadow on top and below the image.

Well, i've changed the image and opacity to .95. The shadow became visible, but it differs from an empty container, it's very light and it seems halfly cut. 
![image](https://user-images.githubusercontent.com/63228361/118279468-dcc61400-b4d3-11eb-8f06-7fca6e22ccfc.png)
![image](https://user-images.githubusercontent.com/63228361/118279516-e94a6c80-b4d3-11eb-800c-f82cc3afdafe.png)

**Comment by nt4f04uNd** [comment] 2021-05-15 19:17
This is still a contrast thing
Here I took a brush in photoshop and removed the lion

![11fqwfwqf](https://user-images.githubusercontent.com/39104740/118375607-63115180-b5cb-11eb-9ef2-a37b667da6ab.png)

**Comment by kirill-21** [comment] 2021-05-15 22:55
> This is still a contrast thing
> Here I took a brush in photoshop and removed the lion

I've created an extra slow animation to show how the image cuts the shadow, not recontrasts it
![XT6a8PDAzx](https://user-images.githubusercontent.com/63228361/118380340-b09cb700-b5e9-11eb-97a3-3e04482621cf.gif)

**Comment by chinmaygarde** [comment] 2021-05-17 18:27
From the engine perspective, this seems WAI to me [given the experiments related to making the shadow](https://github.com/flutter/flutter/issues/82487#issuecomment-841193825) be of a different color to make it more apparent. cc @goderbauer for thoughts on whether the framework does anything differently in the case of the decoration image.

**Comment by chinmaygarde** [comment] 2021-05-18 23:09
We took a closer looks at this and we don't think there is a bug here. The lack of the image makes the border more noticeable as [was confirmed by a previous comment](https://github.com/flutter/flutter/issues/82487#issuecomment-841711284). The box shadow and its arguments are independent of the image being used and an identical shadow will be rendered by the engine. If you want to make the shadow more or less noticeable, you could perhaps modify the box shadow arguments.

Since there is no action item, I am closing this as WAI.

**Closed by chinmaygarde** 2021-05-18 23:09 UTC
Labels: P4, a: images, a: quality, engine, framework, passed first triage, severe: rendering

**Comment by Hixie** [comment] 2021-05-18 23:11
This is wild. It's got to be some sort of variant of the https://en.wikipedia.org/wiki/Chubb_illusion or the https://en.wikipedia.org/wiki/Checker_shadow_illusion maybe?

Feel free to reach out on #general on the Discord channel to chat about it more if you're not convinced. :-)
