### ISSUE TITLE
[tool_crash] ArgumentError: Invalid argument(s): Cannot find executable for G:\flutter\bin\cache\dart-sdk\bin\pub.bat.

### ISSUE THREAD

**Issue by AhmedAmr11** [flutter/flutter#75166] opened 2021-02-01 20:07 UTC
## Command
```
flutter run
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ArgumentError: Invalid argument(s): Cannot find executable for G:\flutter\bin\cache\dart-sdk\bin\pub.bat.
```
#0      _getExecutable (package:process/src/interface/local_process_manager.dart:124:5)
#1      LocalProcessManager.run (package:process/src/interface/local_process_manager.dart:65:30)
#2      ErrorHandlingProcessManager.run.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:618:33)
#3      _run (package:flutter_tools/src/base/error_handling_io.dart:532:20)
#4      ErrorHandlingProcessManager.run (package:flutter_tools/src/base/error_handling_io.dart:618:12)
#5      DevtoolsServerLauncher._checkForActiveDevTools (package:flutter_tools/src/devtools_launcher.dart:120:74)
#6      DevtoolsServerLauncher.launch (package:flutter_tools/src/devtools_launcher.dart:72:43)
<asynchronous suspension>
#7      DevtoolsServerLauncher.serve (package:flutter_tools/src/devtools_launcher.dart:176:7)
<asynchronous suspension>
#8      ResidentRunner.serveDevToolsGracefully (package:flutter_tools/src/resident_runner.dart:1284:7)
<asynchronous suspension>
#9      Future.wait.<anonymous closure> (dart:async/future.dart)
<asynchronous suspension>
#10     HotRunner.attach (package:flutter_tools/src/run_hot.dart:178:7)
<asynchronous suspension>
#11     RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:620:24)
<asynchronous suspension>
#12     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1157:12)
<asynchronous suspension>
#13     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1009:27)
<asynchronous suspension>
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#15     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
```
```
[✓] Flutter (Channel dev, 1.26.0-17.1.pre, on Microsoft Windows [Version 10.0.18363.1316], locale en-US)
    • Flutter version 1.26.0-17.1.pre at G:\flutter
    • Framework revision c40e5294dd (3 days ago), 2021-01-29 08:44:18 -0800
    • Engine revision 5d3477eab4
    • Dart version 2.12.0 (build 2.12.0-259.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\20115\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\20115\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.52.1)
    • VS Code at C:\Users\20115\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.19.0

[✓] Connected device (3 available)
    • SM A207F (mobile) • R9AMB08GQ9J • android-arm64  • Android 10 (API 29)
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 88.0.4324.104
    • Edge (web)        • edge        • web-javascript • Microsoft Edge 88.0.705.50

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 8874f21e79d7ec66d0457c7ab338348e31b17f1d

**Comment by iapicca** [comment] 2021-02-02 06:38
duplicate of https://github.com/flutter/flutter/issues/60880

**Comment by pedromassangocode** [comment] 2021-02-02 06:44
Closing as duplicate of #60880

**Closed by pedromassangocode** 2021-02-02 06:44 UTC
