### ISSUE TITLE
Wrote stack traces to tombstoned on Android 13 using NFC Manager plugin in flutter app. and permission denial

### ISSUE THREAD

**Issue by Rahul123723** [flutter/flutter#135294] opened 2023-09-22 10:29 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I am trying to lock the tag using the nfcmanager facing issue while locking. once session is getting started for handling tag lock feature after that when it go to the locking function application is getting stoped and not responding.
I/abgroup.nfclabs(15408): Thread[5,tid=15413,WaitingInMainSignalCatcherLoop,Thread*=0xb400007bc1699dd0,peer=0x13780260,"Signal Catcher"]: reacting to signal 3 I/abgroup.nfclabs(15408): I/abgroup.nfclabs(15408): Wrote stack traces to tombstoned F/crash_dump64(16414): crash_dump.cpp:540] failed to attach to thread 641: Permission denied . this the stack of the exception while using the nfc manager for the andriod 13 mainly with the writelock feature. 

### Expected results

i am trying to lock the tag using the nfc manager. but it is not working with andriod 13 same with andriod 12 it is working

### Actual results

application is getting crashed and the exception is coming. not even with my code with the sanple code for nfc_manager also it getting crashed with the andriod 13 version . 

### Code sample

nfc manager for locking of the tag 

[ void _ndefWriteLock() {
    NfcManager.instance.startSession(onDiscovered: (NfcTag tag) async {
      var ndef = Ndef.from(tag);
      if (ndef == null) {
        result.value = 'Tag is not ndef';
        NfcManager.instance.stopSession(errorMessage: result.value.toString());
        return;
      }

      try {
        await ndef.writeLock();
        result.value = 'Success to "Ndef Write Lock"';
        NfcManager.instance.stopSession();
      } catch (e) {
        result.value = e;
        NfcManager.instance.stopSession(errorMessage: result.value.toString());
        return;
      }
    });
  }
}]
```

this is the sample code avilable on pub.dev and git repo of the nfc_manager this is not working with the andriod 13


### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>


### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

I/abgroup.nfclabs(15408): Thread[5,tid=15413,WaitingInMainSignalCatcherLoop,Thread*=0xb400007bc1699dd0,peer=0x13780260,"Signal Catcher"]: reacting to signal 3 I/abgroup.nfclabs(15408): I/abgroup.nfclabs(15408): Wrote stack traces to tombstoned F/crash_dump64(16414): crash_dump.cpp:540] failed to attach to thread 641: Permission denied

**Comment by huycozy** [comment] 2023-09-22 11:59
From what I can see, the issue is related to a 3rd party plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/okadan/flutter-nfc-manager/issues).

Closing, as this isn't an issue with Flutter itself. If you believe this is Flutter framework issue, please write in the comments with more information then I will reopen this.

**Closed by huycozy** 2023-09-22 11:59 UTC
Labels: in triage
