### ISSUE TITLE
ContextMenus are not dismissed when clicking outside the menu

### ISSUE THREAD

**Issue by esDotDev** [flutter/flutter#80061] opened 2021-04-08 17:04 UTC
Standard behavior on desktop/web, is that left-clicking anywhere outside a context menu will dismiss it.

In Flutter I can left-click many times around the menu, but it won't close until I click the text itself:
https://user-images.githubusercontent.com/736973/114067001-8cff8780-9859-11eb-8526-e45875946b00.mp4

cc @justinmc

**Comment by TahaTesser** [comment] 2021-04-09 11:55
Hi @esDotDev 
Thanks for filing the issue! I can only reproduce it on the desktop app (tested on macos and windows), it closes on web on both platforms

<details> 
<summary>code sample</summary> 

```dart
``` 

</details>

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 2.0.4, on macOS 11.2.3 20D91 darwin-x64, locale
    en-GB)
    • Flutter version 2.0.4 at /Users/tahatesser/Code/flutter_stable
    • Framework revision b1395592de (8 days ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.55.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.2.3 20D91 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 89.0.4389.114

• No issues found!

```

```bash
[✓] Flutter (Channel master, 2.1.0-13.0.pre.555, on macOS 11.2.3 20D91
    darwin-x64, locale en-GB)
    • Flutter version 2.1.0-13.0.pre.555 at
      /Users/tahatesser/Code/flutter_master
    • Framework revision cf27be38a9 (8 hours ago), 2021-04-08 21:04:02 -0700
    • Engine revision a9f4883dc8
    • Dart version 2.13.0 (build 2.13.0-219.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.55.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.2.3 20D91 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 89.0.4389.114

• No issues found!
```
	
</details>

**Comment by HansMuller** [comment] 2021-04-09 15:55
CC @shihaohong

**Comment by nt4f04uNd** [comment] 2021-04-10 18:35
looks related to https://github.com/flutter/flutter/issues/78909

**Comment by gspencergoog** [comment] 2021-04-15 18:15
Closing as a duplicate of #78909 (Desktop Triage)

**Closed by gspencergoog** 2021-04-15 18:15 UTC
Labels: P4, a: desktop, f: material design, found in release: 2.0, found in release: 2.1, framework, has reproducible steps
