### ISSUE TITLE
Set flutter Native window translucent

### ISSUE THREAD

**Issue by sudongg** [flutter/flutter#97088] opened 2022-01-23 07:23 UTC
## Use case
on desktop platforms, allows translucent the flutter Native window, and the translucent Native window can see the content of the main window.
(Note: Instead of making the main window transparent, the main window is opaque and the flutter Native window is transparent, which is different from #59969)

## Proposal
I want to draw video content to main window and draw UI using transparent flutter Native window as overlay.
Because most video SDK can only draw video using the window handle.

details as follows:
Video Layer = Main window => C++ call video SDK to draw video
UI Layer = flutter Native window => translucent UI overlay

**Comment by stuartmorgan** [comment] 2022-01-23 11:18
> (Note: Instead of making the main window transparent, the main window is opaque and the flutter Native window is transparent, which is different from #59969)

No, #59969 is requesting the Flutter view be transparent, which is exactly the same as what you are asking for. Many of the people commenting there *also* want to make the window transparent, but that's not controlled by Flutter, it's controlled by the runner, so there is no issue tracking making the main window transparent.

Closing as a duplicate.

**Closed by stuartmorgan** 2022-01-23 11:18 UTC

**Comment by sudongg** [comment] 2022-01-23 12:42
@stuartmorgan 
#59969, what he requires is to make a transparent application, as long as the main window is transparent.
I checked fluent_ Acrylic project. He uses SetWindowCompositionAttribute to realize the translucency of windows on windows platform. He can solve it #59969

But with this method, when I render the content to the main window, the translucent window still displays the content behind the main window rather than the content I want to render.

As far as I know, on the windows platform, there is no other way to achieve window transparency unless the updatelayeredwindow function is used after rendering.

**Comment by stuartmorgan** [comment] 2022-01-23 13:47
> #59969, what he requires is to make a transparent application

It's irrelevant what the ultimate goal is. There are two parts of making a transparent application on macOS (which is what that issue is tracking): making the window itself transparent, and making the Flutter view transparent. The former **is not in scope for the Flutter engine**, as I said above, so the only think being tracked there is the ability to make the view transparent. The fact that some people have made a variety of off-topic comments there does not change what the issue is tracking.

> As far as I know, on the windows platform

If you're interested in Windows, #71735 is the tracking bug for a transparent Flutter view. Feel free to comment there about your use case.

**Comment by sudongg** [comment] 2022-01-23 15:05
@stuartmorgan  
Although the title of #59969 is the same as my request, the content of #59969 just wants the main window to be transparent, a transparent application.

This is exactly the same request as #71735, and all the answers are about how to implement main window transparency, and someone has already given a solution.

No one in #59969 and #71735 discusses how to implement native window translucency.

Currently, on windows, I didn't find any way to set the native window transparent in the runner, only the main window can be set transparent through `SetWindowCompositionAttribute`.

I have tried creating a new win32 video window and setting the main window to be transparent (SetWindowCompositionAttribute), but when I attach the main window to the video window via SetParent, the main window becomes opaque.

My current solution is to not use SetParent , synchronize the size of the two windows, turn off the window animations, and make them look like one window, but this will affect the user experience.

I think fluent should add an `IsTransparentLayered `parameter to the native window, which when enabled will make the native window transparent and can be attached to any window as an overlay.

**Comment by stuartmorgan** [comment] 2022-01-23 15:31
> all the answers are about how to implement main window transparency

The issue tracker isn't a Q&A forum, it is tracking engineering work. That issue doesn't have "answers", it has comments from people about workarounds for various use cases. Again: "The fact that some people have made a variety of off-topic comments there does not change what the issue is tracking."

> No one in #59969 and #71735 discusses how to implement native window translucency.

The fact that the issue isn't fixed, or discussion of a temporary workaround for your use case, doesn't change what it is tracking.

> I think fluent should add an `IsTransparentLayered `parameter to the native window, which when enabled will make the native window transparent and can be attached to any window as an overlay.

That is the functionality being tracked in #71735.

**Comment by sudongg** [comment] 2022-01-23 16:19
@stuartmorgan 
Do you only read the title of the issue and not the content?
#59969 and #71735 are actually about creating transparent applications, rather than using the native window transparent as an overlay.
I'll never get an answer in #59969 or #71735.

Maybe you think that the transparent main window can be used as an overlay, but after my testing, using `SetWindowCompositionAttribute `After the window is transparent, once attached to any window using SetParent, the main window becomes opaque again. I have mentioned this in my previous reply.

Another api that can make window transparent is `UpdateLayeredWindow`, my current project is to use skiasharp to draw UI, I have implemented transparent window and can use set parent to attach to main window as overlay, after drawing transparent bitmap is done, use `UpdateLayeredWindow `to achieve The window is transparent.

I didn't see the specific implementation of the native window in the runner, so I can't understand how flutter uses skia to draw to the window. I think it's just that the runner can't achieve the transparency of the native window.

**Comment by stuartmorgan** [comment] 2022-01-23 17:09
> Do you only read the title of the issue and not the content?

No. I read the content, then I set the title to reflect what engineering work will be tracked as a result of the request that was filed.

I was the technical lead for the desktop embeddings before they were even part of the Flutter project, and wrote significant portions of them. Assuming I don't understand the issue tracker is not a productive way to engage here.

> I'll never get an answer in #59969 or #71735.

Please see my comments above. The purpose of the issue is not to provide answers, it's to track engineering work.

I'm the case of that issue, it tracks the work to make the **Flutter view** support being transparent. For any use case, whether that use case is a transparent application, or a transparent overlay working within a normal application.

I'm going to lock this, as this isn't productive to continue. I suggest following the Windows issuei referenced, and mentioning your use case there, because regardless of whether you choose to believe me or not that is the issue that is teaching the engineering work to allow your use case.
