### ISSUE TITLE
Flaky pure virtual function called in engine host tests

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#74134] opened 2021-01-17 00:34 UTC
Linux Host Engine: https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8857910757129505712/+/steps/Host_Tests_for_host_profile/0/stdout?format=raw

Mac Host Engine: https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8857963650630585808/+/steps/Host_Tests_for_host_debug_unopt/0/stdout?format=raw

Earliest instance is on https://github.com/flutter/engine/commit/d2c4de0cd483df40f3c068bbc79988e845b2da0e but that doesn't seem related.

**Comment by chinmaygarde** [comment] 2021-01-19 19:51
I originally suspected this was something to do with the mocking framework but there the failing test on Mac does not use mocking at all. There are tons of gmock warnings that I am not sure are related.

cc @chinmaygarde

**Comment by cbracken** [comment] 2021-01-25 00:28
Hit this today https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20Host%20Engine/8615/overview

**Comment by zanderso** [comment] 2021-01-25 16:41
Caused tree to be closed here https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20Host%20Engine/8641/overview.

Bumping the priority one notch to P3.

**Comment by zanderso** [comment] 2021-01-26 07:58
The message appears to be coming from here:

https://fuchsia.googlesource.com/third_party/libcxxabi/+/refs/heads/master/src/cxa_virtual.cpp#16

Which boils down to a call to `abort()` here:

https://fuchsia.googlesource.com/third_party/libcxxabi/+/refs/heads/master/src/abort_message.cpp#76

But I don't understand why `abort()` isn't causing a backtrace to be printed by the signal handlers here:

https://github.com/flutter/engine/blob/master/fml/backtrace.cc

installed by(?):

https://github.com/flutter/engine/blob/master/testing/run_all_unittests.cc#L39

**Comment by jason-simmons** [comment] 2021-01-26 22:44
Looked into this and found a few issues:
* The FML signal handler that prints backtraces may itself crash due to a null pointer dereference (see https://github.com/flutter/engine/pull/23970)
* The backtrace handler uses `dladdr` to find symbol names.  `dladdr` is unable to locate most of the relevant symbols because they have hidden visibility.  Also, `dladdr` finds symbols exported by dynamic libraries and will not find symbols within the executable unless it is linked using `--export-dynamic`.
* Dart initialization is replacing the `SIGABRT` handler set up by `fml::InstallCrashHandler`

Would it be possible for the LUCI environment to capture a core dump when a crash like this happens?

@godofredoc

**Comment by godofredoc** [comment] 2021-01-26 22:48
Yes, you'll need to modify the runner to collect a dumpstate and place it in the folder referenced by FLUTTER_LOGS_DIR  env variable and infra will automatically upload the logs to GCS.

**Comment by godofredoc** [comment] 2021-01-26 22:49
I can make the change to the recipe but will need your help on modifying the runner.

**Comment by zanderso** [comment] 2021-01-26 22:57
@jason-simmons Do you have a pointer to where Dart is doing that?

**Comment by jason-simmons** [comment] 2021-01-26 23:09
See the signal handling code in https://github.com/dart-lang/sdk/blob/master/runtime/bin/process_linux.cc

In particular, these tests will be creating and destroying Dart VM instances and going through cycles of `Dart_Initialize`/`Dart_Cleanup` (including an explicit call to `dart::bin::CleanupDartIo`).  `CleanupDartIo` calls `Process::Cleanup`, which calls `ClearAllSignalHandlers`.

**Comment by chinmaygarde** [comment] 2021-01-26 23:20
Good catch on the `dladdr` usage inaccuracy. `export-dynamic` on all Linux unit-test exectuables seems like a fine thing to do. The signal handling seems to be different Mac and Linux and the crash handler seems to work fine after I create and shutdown the VM in the process on Mac.

**Comment by zanderso** [comment] 2021-01-27 00:27
To clarify, this is happening much more frequently on the bots on Mac, so Linux-only fixes probably won't help too much.

**Comment by jason-simmons** [comment] 2021-01-27 02:59
I was able to reproduce this on a Mac using the `TypeConversionsTest.CanConvertEmptyList` test.

There is a race between Dart VM shutdown and a deferred task posted to one of the test's threads.  When the `TypeConversionsTest` deletes its `DartVMRef`, `Dart_Cleanup` will delete the `Timeline::recorder_` (which is a process-wide global).

However, there may be a pending call to `MessageLoopImpl::FlushTasks` on another thread.  `FlushTasks` logs a timeline event, and if the timeline recorder is partially deleted then this will fail with the pure virtual call error.

I think we only started seeing this recently because the timeline had been disabled during tests until https://github.com/flutter/engine/commit/f392053b1f2a10ed4022341620f341359b5f8401 landed.

@chinmaygarde What is the best way to make this safe?
The thread created by the `TypeConversionsTest` (which appears to be owned by the `ThreadTest` superclass) needs to be stopped before the `TypeConversionsTest` drops the `DartVMRef`.

**Comment by chinmaygarde** [comment] 2021-01-27 22:29
We guarantee that a `DartVMRef` can be created and destroyed on any thread. Creation, destruction and acquisition of new strong references to a VM already running in the process is done using [a single global mutex](https://github.com/flutter/engine/blob/68cd4c42b506dedd08fcd0d8f6d7fa101fe6c42d/runtime/dart_vm_lifecycle.cc#L23). I suppose [we could trace to the timeline with this mutex held](https://github.com/flutter/engine/blob/68cd4c42b506dedd08fcd0d8f6d7fa101fe6c42d/fml/trace_event.cc#L31). There is very little contention on this lock today as its done only when an engine is created and destroyed. However, I'd still use double-checked locking to access this mutex if we are using this for each timeline trace.

**Comment by jason-simmons** [comment] 2021-01-27 22:54
Would it work if `DartVM` sets a flag in the `fml/trace_event` library that controls whether `trace_event` actually calls `Dart_TimelineEvent`?

The flag would be set after calling `Dart_Initialize` and cleared before calling `Dart_Cleanup`.

**Comment by chinmaygarde** [comment] 2021-01-27 22:57
That wouldn't really work because of a TOCTOU race though. You'd need to hold a mutex while the trace is being written.

**Comment by cbracken** [comment] 2021-01-28 20:53
Another case of this: https://ci.chromium.org/p/flutter/builders/try/Linux%20Host%20Engine/18773?

**Comment by chinmaygarde** [comment] 2021-01-28 20:58
This should be fixed after https://github.com/flutter/engine/pull/24007 lands. It is going through presubmits ATM.

**Closed** 2021-02-02 17:12 UTC
Labels: P3, engine, passed first triage, team: flakes
