### ISSUE TITLE
flutter attach can't work with iOS devices

### ISSUE THREAD

**Issue by ViolyCodevB** [flutter/flutter#124005] opened 2023-04-03 10:35 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I tried to  use 'flutter attach -v' before or after run project in Xcode. The Logs show me maybe mDNs get something wrong. I also close Personal Hotspot and uncheck 'iPhone USB' in Mac.

### Actual results

Always show me 'Waiting for a connection from Flutter on Daobao777’s iPhone...' whatever i have done.

### Logs

<details>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

flutter attach -v
[  +27 ms] executing: sysctl hw.optional.arm64
[  +10 ms] Exit code 1 from: sysctl hw.optional.arm64
[        ] sysctl: unknown oid 'hw.optional.arm64'
[        ] executing: [/Users/tongjiancong/flutter/] git -c log.showSignature=false log -n 1
--pretty=format:%H
[  +26 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 62bd79521d8d007524e351747471ba66696fc2d4
[        ] executing: [/Users/tongjiancong/flutter/] git tag --points-at
62bd79521d8d007524e351747471ba66696fc2d4
[ +125 ms] Exit code 0 from: git tag --points-at 62bd79521d8d007524e351747471ba66696fc2d4
[   +1 ms] 3.7.9
[   +8 ms] executing: [/Users/tongjiancong/flutter/] git rev-parse --abbrev-ref --symbolic @{upstream}
[  +14 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{upstream}
[        ] origin/stable
[        ] executing: [/Users/tongjiancong/flutter/] git ls-remote --get-url origin
[  +15 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +30 ms] executing: [/Users/tongjiancong/flutter/] git rev-parse --abbrev-ref HEAD
[  +17 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[   +1 ms] executing: sw_vers -productName
[  +18 ms] Exit code 0 from: sw_vers -productName
[        ] macOS
[        ] executing: sw_vers -productVersion
[  +18 ms] Exit code 0 from: sw_vers -productVersion
[        ] 12.5.1
[        ] executing: sw_vers -buildVersion
[  +17 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 21G83
[        ] executing: uname -m
[   +5 ms] Exit code 0 from: uname -m
[        ] x86_64
[  +39 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +7 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +99 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[  +13 ms] executing: sysctl hw.optional.arm64
[   +3 ms] Exit code 1 from: sysctl hw.optional.arm64
[        ] sysctl: unknown oid 'hw.optional.arm64'
[        ] executing: xcrun xcodebuild -version
[ +423 ms] Exit code 0 from: xcrun xcodebuild -version
[        ] Xcode 14.2
           Build version 14C18
[  +68 ms] executing: /Users/tongjiancong/Library/Android/sdk/platform-tools/adb devices -l
[   +2 ms] executing: xcrun xcdevice list --timeout 2
[   +1 ms] xcrun simctl list devices booted iOS --json
[        ] executing: xcrun simctl list devices booted iOS --json
[   +3 ms] executing: xcrun simctl list devices booted
[ +140 ms] Exit code 0 from: xcrun simctl list devices booted
[        ] == Devices ==
           -- iOS 16.2 --
[  +22 ms] List of devices attached
           XRTNW20429011816       device usb:338886656X product:ART-AL00x model:ART_AL00x device:HWART-H
           transport_id:8
[ +113 ms] {
                      "devices" : {
                        "com.apple.CoreSimulator.SimRuntime.iOS-16-2" : [

                        ]
                      }
                    }
[+2963 ms] [
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "16.2 (20C52)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPad14,1",
                        "identifier" : "9D17CB59-33D0-48E7-9859-B86E39BECBC6",
                        "architecture" : "x86_64",
                        "modelUTI" : "com.apple.ipad-mini6-1",
                        "modelName" : "iPad mini (6th generation)",
                        "name" : "iPad mini (6th generation)"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "16.2 (20C52)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPhone14,6",
                        "identifier" : "3799B1F9-CB21-4D48-8B1C-B1EF64572324",
                        "architecture" : "x86_64",
                        "modelUTI" : "com.apple.iphone-se3-1",
                        "modelName" : "iPhone SE (3rd generation)",
                        "name" : "iPhone SE (3rd generation)"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "16.2 (20C52)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPad14,5",
                        "identifier" : "E80FEDBD-64AD-4C68-8727-CD410F17B0C7",
                        "architecture" : "x86_64",
                        "modelUTI" : "com.apple.ipad-pro-12point9-6th-1",
                        "modelName" : "iPad Pro (12.9-inch) (6th generation)",
                        "name" : "iPad Pro (12.9-inch) (6th generation)"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "16.2 (20C52)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPad14,3",
                        "identifier" : "24E4877D-EC51-4EC0-B1AD-B5E9FD887172",
                        "architecture" : "x86_64",
                        "modelUTI" : "com.apple.ipad-pro-11-4th-1",
                        "modelName" : "iPad Pro (11-inch) (4th generation)",
                        "name" : "iPad Pro (11-inch) (4th generation)"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "16.2 (20C52)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPad13,18",
                        "identifier" : "B2292C48-5523-4A5E-B2C7-1C4CF0AC9A53",
                        "architecture" : "x86_64",
                        "modelUTI" : "com.apple.ipad-10-1",
                        "modelName" : "iPad (10th generation)",
                        "name" : "iPad (10th generation)"
                      },
                      {
                        "simulator" : false,
                        "operatingSystemVersion" : "15.7 (19H12)",
                        "interface" : "usb",
                        "available" : true,
                        "platform" : "com.apple.platform.iphoneos",
                        "modelCode" : "iPhone12,1",
                        "identifier" : "00008030-001278EE3E04802E",
                        "architecture" : "arm64e",
                        "modelUTI" : "com.apple.iphone-11-1",
                        "modelName" : "iPhone 11",
                        "name" : "Daobao777’s iPhone"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "16.2 (20C52)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPhone14,8",
                        "identifier" : "86BD196C-1E44-464A-A17F-F56B5BDF92FA",
                        "architecture" : "x86_64",
                        "modelUTI" : "com.apple.iphone-14-plus-1",
                        "modelName" : "iPhone 14 Plus",
                        "name" : "iPhone 14 Plus"
                      },
                      {
                        "simulator" : false,
                        "operatingSystemVersion" : "12.5.1 (21G83)",
                        "interface" : "usb",
                        "available" : true,
                        "platform" : "com.apple.platform.macosx",
                        "modelCode" : "MacBookPro16,1",
                        "identifier" : "BD356C3E-0EDD-5A5E-B493-0509FED42910",
                        "architecture" : "x86_64h",
                        "modelUTI" : "com.apple.macbookpro-16",
                        "modelName" : "MacBook Pro",
                        "name" : "My Mac"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "16.2 (20C52)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPhone15,2",
                        "identifier" : "63FCFA36-B30B-40E4-A3DA-D3A43C5F4B41",
                        "architecture" : "x86_64",
                        "modelUTI" : "com.apple.iphone-14-pro-1",
                        "modelName" : "iPhone 14 Pro",
                        "name" : "iPhone 14 Pro"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "16.2 (20C52)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPhone15,3",
                        "identifier" : "8BF5C022-B00C-4BD6-B3E3-A1D499EF0B52",
                        "architecture" : "x86_64",
                        "modelUTI" : "com.apple.iphone-14-pro-max-1",
                        "modelName" : "iPhone 14 Pro Max",
                        "name" : "iPhone 14 Pro Max"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "16.2 (20C52)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPhone14,7",
                        "identifier" : "3C287DD0-6534-4380-8163-D3196ADFD3A0",
                        "architecture" : "x86_64",
                        "modelUTI" : "com.apple.iphone-14-1",
                        "modelName" : "iPhone 14",
                        "name" : "iPhone 14"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "16.2 (20C52)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPad13,17",
                        "identifier" : "AB8A0072-BFD5-4000-BE7A-7528A3A87ED0",
                        "architecture" : "x86_64",
                        "modelUTI" : "com.apple.ipad-air5-1",
                        "modelName" : "iPad Air (5th generation)",
                        "name" : "iPad Air (5th generation)"
                      }
                    ]
[  +15 ms] Multiple devices found:
[   +1 ms] /Users/tongjiancong/Library/Android/sdk/platform-tools/adb -s XRTNW20429011816 shell getprop
[  +94 ms] ro.hardware = kirin710
[        ] ro.build.characteristics = default
[   +4 ms] ART AL00x (mobile)          • XRTNW20429011816          • android-arm64 • Android 10 (API 29)
[   +1 ms] Daobao777’s iPhone (mobile) • 00008030-001278EE3E04802E • ios           • iOS 15.7 19H12
[        ] [1]: ART AL00x (XRTNW20429011816)
[        ] [2]: Daobao777’s iPhone (00008030-001278EE3E04802E)
[   +1 ms] Please choose one (To quit, press "q/Q")
[        ] : 
[+2426 ms] 2
[  +47 ms] Checking for advertised Dart observatories...
[+5030 ms] No pointer records found.
[   +1 ms] mDNS query failed. Checking for an interface with a ipv4 link local address.
[   +2 ms] Found interface "en0":
[        ] 	Bound address: "192.168.0.20" 
[        ] Found interface "utun3":
[        ] 	Bound address: "198.18.0.1" 
[        ] Found interface "en17":
[        ] 	Bound address: "169.254.61.89" link local
[        ] Found interface "en18":
[        ] 	Bound address: "169.254.226.102" link local
[        ] An interface with an ipv4 link local address was found.
[   +3 ms] Waiting for a connection from Flutter on Daobao777’s iPhone...

```

</details>

### Flutter Doctor output

<details>
<summary>Doctor output</summary>

```console

<!-- Paste your output here -->
[✓] Flutter (Channel stable, 3.7.9, on macOS 12.5.1 21G83 darwin-x64, locale zh-Hans-CN)
    • Flutter version 3.7.9 on channel stable at /Users/tongjiancong/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 62bd79521d (4 days ago), 2023-03-30 10:59:36 -0700
    • Engine revision ec975089ac
    • Dart version 2.19.6
    • DevTools version 2.20.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0-rc1)
    • Android SDK at /Users/tongjiancong/Library/Android/sdk
    • Platform android-33, build-tools 34.0.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.12.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] Connected device (3 available)
    • ART AL00x (mobile) • XRTNW20429011816 • android-arm64  • Android 10 (API 29)
    • macOS (desktop)    • macos            • darwin-x64     • macOS 12.5.1 21G83 darwin-x64
    • Chrome (web)       • chrome           • web-javascript • Google Chrome 111.0.5563.146

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

</details>

**Comment by bartekpacia** [comment] 2023-04-03 13:21
Hi @ViolyCodevB, thanks for reporting this issue. It looks similar to what I'm experiencing as well – I described it in #122698. This issue might be a duplicate.

**Comment by exaby73** [comment] 2023-04-03 14:03
This does indeed look like a duplicate of https://github.com/flutter/flutter/issues/122698. Thanks @bartekpacia for that catch. Closing this in favor of https://github.com/flutter/flutter/issues/122698

**Closed by exaby73** 2023-04-03 14:03 UTC
Labels: in triage
