### ISSUE TITLE
Support `-d all` for `flutter run --machine`

### ISSUE THREAD

**Issue by DanTup** [flutter/flutter#16145] opened 2018-04-02 10:08 UTC
I wanted to add support for running on all devices from VS Code. I was expecting that I probably wouldn't be able to debug (`--start-paused`) but I did think I'd be able to launch and hot-reload/restart. This seems to not be the case, however:

```text
--machine does not support -d all.
```

I'm not sure whether it's easy to support this (without debugging).. probably some of the other events may need device IDs adding to them (eg. so the IDE can track multiple apps quitting).

**Comment by DanTup** [comment] 2019-01-31 09:37
Based on previous discussions, I don't think we want to go down this route. Trying to run multiple debuggers through a single Flutter Run would need lots of changes to the protocol (for ex. if some devices terminated and others did not, it's left in a strange state).

We think a better way is for the editor to manage multiple `flutter run` instances, since the editor can then choose how to present that to the user (and allow them to switch between, etc.).

The current blocker to this is https://github.com/flutter/flutter/issues/18566.

@devoncarew should we close this one?

**Comment by zanderso** [comment] 2020-02-11 23:34
Duplicate of https://github.com/flutter/flutter/issues/29011

**Closed by zanderso** 2020-02-11 23:34 UTC
Labels: tool
