### ISSUE TITLE
Note: C:\flutter\.pub-cache\path\to\go\CloudFirestorePlugin.java uses unchecked or unsafe operations.

### ISSUE THREAD

**Issue by permanar** [flutter/flutter#47653] opened 2019-12-23 07:46 UTC
## Steps to Reproduce

1. flutter upgrade
2. flutter pub get
3. flutter run --debug

**Target Platform: Android**
**Target OS version/browser: Android**
**Devices: Emulator Pixel 3a (API 29, Android Q)**

## Logs

```
Note: C:\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore-0.13.0+1\android\src\main\java\io\flutter\plugins\firebase\cloudfirestore\CloudFirestorePlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
D8: Program type already present: io.flutter.BuildConfig
com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: 
Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
Program type already present: io.flutter.BuildConfig
	at com.android.builder.dexing.D8DexArchiveMerger.getExceptionToRethrow(D8DexArchiveMerger.java:131)
	at com.android.builder.dexing.D8DexArchiveMerger.mergeDexArchives(D8DexArchiveMerger.java:118)
	at com.android.build.gradle.internal.transforms.DexMergerTransformCallable.call(DexMergerTransformCallable.java:102)
	at com.android.build.gradle.internal.tasks.DexMergingTaskRunnable.run(DexMergingTask.kt:444)
	at com.android.build.gradle.internal.tasks.Workers$ActionFacade.run(Workers.kt:335)
	at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:39)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1.execute(NoIsolationWorkerFactory.java:61)
	at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:44)
	at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:41)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
	at org.gradle.workers.internal.AbstractWorker.executeWrappedInBuildOperation(AbstractWorker.java:41)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1.execute(NoIsolationWorkerFactory.java:55)
	at org.gradle.workers.internal.DefaultWorkerExecutor$1.call(DefaultWorkerExecutor.java:105)
	at org.gradle.workers.internal.DefaultWorkerExecutor$1.call(DefaultWorkerExecutor.java:99)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runExecution(DefaultConditionalExecutionQueue.java:215)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runBatch(DefaultConditionalExecutionQueue.java:164)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.run(DefaultConditionalExecutionQueue.java:131)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.android.tools.r8.CompilationFailedException: Compilation failed to complete
	at com.android.tools.r8.utils.t.a(:55)
	at com.android.tools.r8.D8.run(:11)
	at com.android.builder.dexing.D8DexArchiveMerger.mergeDexArchives(D8DexArchiveMerger.java:116)
	... 30 more
Caused by: com.android.tools.r8.utils.AbortException: Error: Program type already present: io.flutter.BuildConfig
	at com.android.tools.r8.utils.Reporter.a(:21)
	at com.android.tools.r8.utils.Reporter.a(:7)
	at com.android.tools.r8.utils.t.a(:36)
	... 32 more


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDexDebug'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: 
     Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
     Program type already present: io.flutter.BuildConfig
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Get more help at https://help.gradle.org

BUILD FAILED in 3m 14s
[!] The shrinker may have failed to optimize the Java bytecode.
    To disable the shrinker, pass the `--no-shrink` flag to this command.
    To learn more, see: https://developer.android.com/studio/build/shrink-code
Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

```

## Flutter analyze

```
Analyzing bisma_certification...                                        

   info - Name non-constant identifiers using lowerCamelCase -
          certification_repository\lib\src\entities\certification_entity.dart:12:16 - non_constant_identifier_names 
   info - Name non-constant identifiers using lowerCamelCase -
          certification_repository\lib\src\entities\certification_entity.dart:22:10 - non_constant_identifier_names 
   info - Name non-constant identifiers using lowerCamelCase -
          certification_repository\lib\src\models\certification.dart:13:16 - non_constant_identifier_names
   info - Name non-constant identifiers using lowerCamelCase -
          certification_repository\lib\src\models\certification.dart:23:10 - non_constant_identifier_names
   info - Name non-constant identifiers using lowerCamelCase -
          certification_repository\lib\src\models\certification.dart:34:12 - non_constant_identifier_names
   info - Unused import: 'package:flutter_spinkit/flutter_spinkit.dart' - lib\main.dart:5:8 - unused_import
   info - The declaration '_makePayment' isn't referenced - lib\src\pages\detail_page.dart:477:10 - unused_element
   info - The value of the local variable 'httpClient' isn't used - lib\src\pages\detail_page.dart:478:16 -
          unused_local_variable
   info - The value of the local variable 'datas' isn't used - lib\src\pages\detail_page.dart:511:9 -
          unused_local_variable
   info - Avoid using braces in interpolation when not needed - lib\src\pages\detail_page.dart:560:29 -
          unnecessary_brace_in_string_interps
   info - Unused import: 'package:auto_size_text/auto_size_text.dart' - lib\src\pages\home_content.dart:1:8 -
          unused_import
   info - Unused import: 'package:bisma_certification/src/pages/detail_page.dart' -
          lib\src\pages\home_content.dart:2:8 - unused_import
   info - Unused import: 'package:bisma_certification/src/utils/page_transition.dart' -
          lib\src\pages\home_content.dart:3:8 - unused_import
   info - Unused import: 'package:cached_network_image/cached_network_image.dart' -
          lib\src\pages\home_content.dart:6:8 - unused_import
   info - The value of the local variable 'device' isn't used - lib\src\pages\home_content.dart:17:9 -
          unused_local_variable
   info - The declaration '_logoutProcess' isn't referenced - lib\src\pages\home_page.dart:67:3 - unused_element    
   info - The declaration '_buildCarousel' isn't referenced - lib\src\pages\home_page.dart:154:10 - unused_element  
   info - The declaration '_initSP' isn't referenced - lib\src\pages\login_page.dart:33:3 - unused_element
   info - The declaration '_getStarted' isn't referenced - lib\src\pages\onboarding\onboarding_page.dart:27:8 -     
          unused_element
   info - Unused import: 'package:sticky_headers/sticky_headers.dart' - lib\src\pages\profile_page.dart:4:8 -       
          unused_import

20 issues found. (ran in 61.8s)
```

## Flutter doctor

```
[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.18362.10024], locale en-ID)
    • Flutter version 1.12.13+hotfix.5 at C:\flutter
    • Framework revision 27321ebbad (12 days ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\Richie\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code, 64-bit edition (version 1.41.0)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.7.1

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

• No issues found!
```

## Note

This happen when I just upgrade the flutter. Also:

1. I use the latest `cloud_firestore` version (^0.13.0+1).
2. I use `classpath 'com.google.gms:google-services:4.3.3'`.

What should I do? Oh god this is so urgent lol because this project kinda related with my bachelor thesis.

**Comment by permanar** [comment] 2019-12-23 11:08
Honestly what I've been tried is:
1. Downgrading the `cloud_firestore` multiple times as well as the flutter version.
2. Every time I downgrade the flutter version, there has to be other issues added up.
3. Changing the `minSdkVersion` from 16 to 23 in the build.gradle file android\app level.

**Comment by iapicca** [comment] 2019-12-24 15:15
Hi @permanar 
for what I can see the issue is related to a FlutterFire plugin,
please open the issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
thank you

**Closed by iapicca** 2019-12-24 15:15 UTC
Labels: p: cloud_firestore, p: first party, plugin, severe: crash, severe: regression, tool, ▣ platform-android

**Comment by permanar** [comment] 2020-01-03 04:40
Hi, 
Thanks for replying me and I am really sorry for the late reply.

Anyway thanks for the suggestion given but somehow, I managed to get out of this problem at that day just by running `flutter clean` command on my project. 

I totally forgot to try clean the build, etc.
Thank you so much. Hope this helps someone! :)
