### ISSUE TITLE
Flutter demo apps for Linux desktop don't work under Wayland

### ISSUE THREAD

**Issue by nicocarbone** [flutter/flutter#61125] opened 2020-07-08 20:09 UTC
I am trying to run the desktop samples from [https://medium.com/flutter/announcing-flutter-linux-alpha-with-canonical-19eb824590a9](https://medium.com/flutter/announcing-flutter-linux-alpha-with-canonical-19eb824590a9) and it seems none of them work under Wayland+Gnome. They do on the same machine under X11.

When running them from the terminal I get:

```
❯ flutter-gallery
/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
Gtk-Message: 17:06:46.591: Failed to load module "appmenu-gtk-module"

(build:11659): Gdk-WARNING **: 17:06:46.919: ../../../../../gdk/x11/gdkwindow-x11.c:5579 drawable is not a native X11 window

** (build:11659): WARNING **: 17:06:46.969: Failed to start Flutter engine: Failed to create EGL surface: Bad Native Window
```

**Comment by stuartmorgan** [comment] 2020-07-08 20:41
Duplicate of https://github.com/flutter/flutter/issues/57932

**Closed** 2020-07-08 20:41 UTC
