### ISSUE TITLE
[tool_crash] FileSystemException: Creation failed, OS Error: The tag present in the reparse point buffer is invalid., errno = 4393

### ISSUE THREAD

**Issue by skylife13** [flutter/flutter#92876] opened 2021-11-02 04:11 UTC
## Command
```
flutter run --machine --start-paused -d 7d3c90f90405 --dart-define=flutter.inspector.structuredErrors=true --web-allow-expose-url --devtools-server-address http://127.0.0.1:9100/ --target lib\main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Creation failed, OS Error: The tag present in the reparse point buffer is invalid.
, errno = 4393
```
#0      _Directory.createSync (dart:io/directory_impl.dart:133:7)
#1      _File.createSync (dart:io/file_impl.dart:270:14)
#2      ForwardingFile.createSync (package:file/src/forwarding/forwarding_file.dart:23:16)
#3      ErrorHandlingFile.createSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:286:22)
#4      _runSync (package:flutter_tools/src/base/error_handling_io.dart:597:14)
#5      ErrorHandlingFile.createSync (package:flutter_tools/src/base/error_handling_io.dart:285:5)
#6      _renderTemplateToFile (package:flutter_tools/src/flutter_plugins.dart:31:8)
#7      _writeAndroidPluginRegistrant (package:flutter_tools/src/flutter_plugins.dart:439:3)
#8      injectPlugins (package:flutter_tools/src/flutter_plugins.dart:1065:11)
<asynchronous suspension>
#9      FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:338:5)
<asynchronous suspension>
#10     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1260:7)
<asynchronous suspension>
#11     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1125:27)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#13     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#16     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
```
```
[✓] Flutter (Channel stable, 2.5.3, on Microsoft Windows [Version 10.0.19042.1165], locale en-ID)
    • Flutter version 2.5.3 at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (2 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Dell\AppData\Local\Android\sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.10.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.10.31515.178
    • Windows 10 SDK version 10.0.19041.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[✓] VS Code (version 1.61.2)
    • VS Code at C:\Users\Dell\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.28.0

[✓] Connected device (4 available)
    • M2003J15SC (mobile) • 7d3c90f90405 • android-arm64  • Android 11 (API 30)
    • Windows (desktop)   • windows      • windows-x64    • Microsoft Windows [Version 10.0.19042.1165]
    • Chrome (web)        • chrome       • web-javascript • Google Chrome 95.0.4638.54
    • Edge (web)          • edge         • web-javascript • Microsoft Edge 95.0.1020.40

! Doctor found issues in 2 categories.

```

## Flutter Application Metadata
**Type**: null
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: null
**Creation framework version**: null
### Plugins
cloud_firestore-0.12.11
firebase_auth-0.14.0+9
firebase_core-0.4.5
firebase_core_web-0.1.1+2

**Comment by darshankawar** [comment] 2021-11-02 11:44
Closing this as a duplicate of https://github.com/flutter/flutter/issues/56775.

As a workaround you may try or confirm, check [this](https://github.com/flutter/flutter/issues/56775#issuecomment-697044643) issue comment.

**Closed by darshankawar** 2021-11-02 11:44 UTC
Labels: in triage
