### ISSUE TITLE
`flutter run` fails horribly when licenses are not signed

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#10702] opened 2017-06-14 20:03 UTC
```
eseidel@eseidel-macbookpro2 /src/flutter/examples/flutter_gallery %flutter run -d A                [/src/flutter/examples/flutter_gallery]
Launching lib/main.dart on Android SDK built for x86 in debug mode...
FAILURE: Build failed with an exception.

* Where:
Build file '/src/flutter/examples/flutter_gallery/android/build.gradle' line: 20

* What went wrong:
A problem occurred evaluating root project 'android'.
> A problem occurred configuring project ':app'.
   > Failed to notify project evaluation listener.
      > You have not accepted the license agreements of the following SDK components:
        [Android SDK Build-Tools 25.0.3, Android SDK Platform 25].
        Before building your project, you need to accept the license agreements and complete the installation of the missing components using the Android Studio SDK Manager.
        Alternatively, to learn how to transfer the license agreements from one workstation to another, go to http://d.android.com/r/studio-ui/export-licenses.html
      > Could not get unknown property 'compileDebugJavaWithJavac' for project ':app' of type org.gradle.api.Project.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
Error running gradle: Exit code 1 from: /Applications/Android Studio.app/Contents/gradle/gradle-3.2/bin/gradle app:properties
Running 'gradle assembleDebug'...                         
Checking the license for package Android SDK Build-Tools 25.0.3 in /Users/eseidel/Library/Android/sdk/licenses
Warning: License for package Android SDK Build-Tools 25.0.3 not accepted.
Checking the license for package Android SDK Platform 25 in /Users/eseidel/Library/Android/sdk/licenses
Warning: License for package Android SDK Platform 25 not accepted.

FAILURE: Build failed with an exception.

* Where:
Build file '/src/flutter/examples/flutter_gallery/android/build.gradle' line: 20

* What went wrong:
A problem occurred evaluating root project 'android'.
> A problem occurred configuring project ':app'.
   > Failed to notify project evaluation listener.
      > You have not accepted the license agreements of the following SDK components:
        [Android SDK Build-Tools 25.0.3, Android SDK Platform 25].
        Before building your project, you need to accept the license agreements and complete the installation of the missing components using the Android Studio SDK Manager.
        Alternatively, to learn how to transfer the license agreements from one workstation to another, go to http://d.android.com/r/studio-ui/export-licenses.html
      > Could not get unknown property 'compileDebugJavaWithJavac' for project ':app' of type org.gradle.api.Project.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
Gradle build failed: 1
```

My understanding is we have a `flutter doctor --android-licenses` command to help with this.  Presumably we should suggest that to the user here?

**Comment by Hixie** [comment] 2017-06-14 20:10
Dupe of https://github.com/flutter/flutter/issues/8438.

**Closed by Hixie** 2017-06-14 20:10 UTC
Labels: dev: tool, ▣ platform-android
