### ISSUE TITLE
[Bug] Flutter Blank Screen on IOS

### ISSUE THREAD

**Issue by duongtruong12** [flutter/flutter#59754] opened 2020-06-18 10:18 UTC
Flutter Application showing **blank screen** when kept in the background about half an hour that means when I resuming the app after sometime it is showing blank screen. If anyone experienced this problem could you help me please. For normal resuming (i.e, minimize and resuming), the application was working without any problem. But after some **long time(more than 1 hour)** it was showing blank screen. After killed app and turn it on again it was fine
Here I am sharing application screenshot when I got the blank screen.

Plugin using: 
```
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.16.0
  intl_translation: ^0.17.7
  cupertino_icons: ^0.1.3
  shared_preferences: 0.5.6+1
  googleapis: ^0.55.0
  googleapis_auth: ^0.2.12
  google_sign_in: ^4.5.1
  oauth2: ^1.6.1
  io: ^0.3.4
  url_launcher: ^5.4.11
  path_provider: ^1.6.11
  background_fetch: ^0.5.5
  connectivity: ^0.4.8+6
  charts_flutter: ^0.9.0
  package_info: ^0.4.1
  flutter_circular_chart: ^0.1.0
  launch_review: ^2.0.0
  frideos: ^1.0.1
  dio: ^3.0.8
  webview_flutter: ^0.3.22+1
  oauth1: ^1.0.4
  provider: ^4.1.3
  flutter_webview_plugin: ^0.3.11
  barcode_scan: ^3.0.1
  quiver: ^2.1.3
  logger: ^0.9.1
  flutter_advanced_networkimage: ^0.6.2
  flutter_datetime_picker: ^1.3.8
  flutter_linkify: ^3.1.0
  flutter_svg: ^0.17.4
  mp_chart: ^0.2.1
  auto_size_text: ^2.1.0
  dots_indicator: ^1.1.0
  image_picker: 0.6.3+4
  sprintf: ^4.0.2
  device_apps: ^1.0.9
  timeago: ^2.0.26
  selectable_autolink_text: ^1.3.1
  table_calendar: ^2.2.3
  permission_handler: ^5.0.0+hotfix.4

  flutter_local_notifications: ^1.4.3
  firebase_messaging: ^6.0.16
  cloud_firestore: ^0.13.6

  android_alarm_manager:
    path: ../../plugin/android_alarm_manager
```

Flutter doctor -v:
```
[✓] Flutter (Channel stable, v1.17.3, on Mac OS X 10.15.5 19F101, locale en-US)
    • Flutter version 1.17.3 at /Users/macos/flutter
    • Framework revision b041144f83 (2 weeks ago), 2020-06-04 09:26:11 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/macos/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_SDK_ROOT = /Users/macos/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.2

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (2 available)
• No issues found!
```

![IMG_0913](https://user-images.githubusercontent.com/32258832/85009102-18534380-b188-11ea-8143-49aa759f5a11.PNG)

**Comment by mbdax034** [comment] 2020-06-18 13:22
I have the same problem, it works on Android but not on IOS.

**Comment by TahaTesser** [comment] 2020-06-18 14:02
Hi @duongtruong12  @mbdax034  
Does it happen with a new project? If not, please provide a minimal reproducible code sample
Thank you

**Comment by mbdax034** [comment] 2020-06-18 15:15
```dart
import 'dart:async';
import 'dart:convert';

import 'package:app/entity.dart';
import 'package:app/services/config.dart';
import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

class WebPageArguments {
  String title;
  
  String url;
  String urlSuccess;
  bool popUntile= false;

  Map<String, String> headers;

  WebPageArguments(
      {this.title,  this.url, this.urlSuccess, this.headers});
}

class WebPage extends StatefulWidget {
  static const String routeName = "webpage";
  final WebPageArguments args;

  WebPage(this.args);

   @override
  _WebPageState createState() => _WebPageState();
}

class _WebPageState extends State<WebPage> with SingleTickerProviderStateMixin {
  Configuration config = Configuration();
  AnimationController _controller;
  WebViewController _webCtrl;

  @override
  void initState() {
    super.initState();

    _controller = AnimationController(vsync: this);

  }

  onUrlSuccess(String currentUrl) {
    if (widget.args.urlSuccess.length > 4) if (currentUrl ==
            widget.args.urlSuccess ||
        currentUrl.split(widget.args.urlSuccess).length > 1) {
          if(widget.args.popUntile)
            Navigator.popUntil(context, ModalRoute.withName('/'));
          else
            Navigator.pop(context);
    }
  }

  @override
  void dispose() {
    super.dispose();
    _controller.stop();
    _controller.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: new AppBar(
          title: new Text(widget.args.url, style: TextStyle(color: Colors.white, fontSize: 14),),
          backgroundColor: Colors.pink,
        ),
        body: WebView(
          javascriptMode: JavascriptMode.unrestricted,
          navigationDelegate: (NavigationRequest delegate) {
            _webCtrl.loadUrl(delegate.url);
            onUrlSuccess(delegate.url);
          },
          onWebViewCreated: (ctrl) {
            _webCtrl = ctrl;
            print("---------  " + widget.args.url);
            print("---------  " + jsonEncode(widget.args.headers));
            ctrl.loadUrl(widget.args.url, headers: widget.args.headers);
          },
        ));
  }
}
```

**Comment by duongtruong12** [comment] 2020-06-19 10:03
I am just like @mbdax034 

Here is my main() functions

`void installDio() {
  if (dio != null &&
      dio.options != null &&
      dio.transformer != null &&
      dio.interceptors != null) {
    dio.interceptors.add(LogInterceptor(
        responseBody: false,
        request: false,
        responseHeader: false,
        requestHeader: false,
        requestBody: false));
    dio.options.contentType = DioContentType.value;
    dio.interceptors.add(InterceptorsWrapper(onRequest: (options) async {
      return options; //continue
    }, onResponse: (response) async {
      return response; // continue
    }, onError: (e) async {
      return e; //continue
    }));
    (dio.transformer as DefaultTransformer).jsonDecodeCallback = parseJson;
    dio.options.receiveTimeout = 180000;
  }
}

Future<void> main() async {
  runApp(MyApp());
  if (Platform.isAndroid) {
    const helloAlarmID = 0;
    await AndroidAlarmManager.initialize();
    await AndroidAlarmManager.periodic(
        const Duration(minutes: 15), helloAlarmID, updateLifeLogBackground,
        rescheduleOnReboot: true);
  }

  installDio();
  await BackgroundFetch.start().then((status) {
    logger.v('[wellgo] start success: $status');
  }).catchError((e) {
    logger.e('[wellgo] start FAILURE: $e');
  });
  await Firestore.instance.settings().then((_) {
    print('[Main] FireStore timestamps in snapshots set');
  }, onError: (_) => print('[Main] Error setting timestamps in snapshots'));
}`

**Comment by TahaTesser** [comment] 2020-06-19 13:29
Added `will need additional triage` since the issue reproducible by us but  looks critical

**Comment by duongtruong12** [comment] 2020-06-19 13:39
> Added `will need additional triage` since the issue reproducible by us but looks critical

Thanks you. It happened after version v1.17.0, previous version was running fine. If you need any infomation please tell

**Comment by Hixie** [comment] 2020-06-23 23:49
This might be related to #57676?

**Comment by chinmaygarde** [comment] 2020-06-30 22:44
This is a duplicate of https://github.com/flutter/flutter/issues/55969 and the current progress is mentioned [in this update](https://github.com/flutter/flutter/issues/55969#issuecomment-652023404).

**Comment by zanderso** [comment] 2020-07-06 16:09
Closing based on @chinmaygarde 's comment that this is a duplicate. Please feel free to re-open with clarifying information if I'm mistaken. Thanks!

**Closed by zanderso** 2020-07-06 16:09 UTC
Labels: a: production, engine, platform-ios
