### ISSUE TITLE
Text selection handler clips Chinese text

### ISSUE THREAD

**Issue by voiddog** [flutter/flutter#69847] opened 2020-11-05 03:11 UTC
## Screenshot
![]()
<img width="400" height="800" src="https://i.imgur.com/kihCH8p.jpg">

You can see the text will be cliping.

## Steps to Reproduce
It can be reproduce in master.

<details><summary>Code</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      supportedLocales: [
        const Locale.fromSubtags(languageCode: 'zh'),
        const Locale('en', ''),
      ],
      locale: const Locale.fromSubtags(languageCode: 'zh'),
      localizationsDelegates: [
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate
      ],
      title: 'Flutter Demo',
      theme: ThemeData(
        platform: TargetPlatform.iOS,
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Padding(
          padding: const EdgeInsets.symmetric(horizontal: 20),
          child: TextField(),
        ),
      ),
    );
  }
}
```
</details>

## Flutter doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 1.24.0-8.0.pre.87, on Mac OS X 10.15.7 19H2 darwin-x64, locale zh-Hans-CN)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2020.2.3)
[✓] VS Code (version 1.50.1)
[✓] Connected device (3 available)

! Doctor found issues in 1 category.
```

**Comment by pedromassangocode** [comment] 2020-11-05 08:14
Reproducible on stable and master channels.

![Screen Shot 2020-11-05 at 09 03 49](https://user-images.githubusercontent.com/67424416/98213896-09f2a200-1f46-11eb-8b26-4ca4b8666ba0.png)

![Screen Shot 2020-11-05 at 09 06 05](https://user-images.githubusercontent.com/67424416/98214110-61910d80-1f46-11eb-84a8-aa20f564f64b.png)

<details><summary>flutter doctor -v (master)</summary>

```
[✓] Flutter (Channel master, 1.24.0-8.0.pre.94, on Mac OS X 10.15.7 19H2 darwin-x64, locale en)
    • Flutter version 1.24.0-8.0.pre.94 at /Users/pedromassango/dev/SDKs/flutter_master
    • Framework revision 9470a7e864 (2 hours ago), 2020-11-04 21:49:59 -0800
    • Engine revision bf259226b2
    • Dart version 2.12.0 (build 2.12.0-21.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2020.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 50.0
    • Dart plugin version 202.7319.5

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (4 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • macOS (desktop)             • macos         • darwin-x64     • Mac OS X 10.15.7 19H2 darwin-x64
    • Web Server (web)            • web-server    • web-javascript • Flutter Tools
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 86.0.4240.183

• No issues found!
```
</details>

<details><summary>flutter doctor -v (stable)</summary>

```
[✓] Flutter (Channel stable, 1.22.3, on Mac OS X 10.15.7 19H2, locale en)
    • Flutter version 1.22.3 at /Users/pedromassango/dev/SDKs/flutter_stable
    • Framework revision 8874f21e79 (6 days ago), 2020-10-29 14:14:35 -0700
    • Engine revision a1440ca392
    • Dart version 2.10.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.9.3

[!] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2020.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin installed
    • Dart plugin version 202.7319.5

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (1 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86 • Android 11 (API 30) (emulator)

! Doctor found issues in 1 category.
```
</details>

**Comment by justinmc** [comment] 2020-11-05 17:39
I don't reproduce it when I run on an iPhone 11 simulator running iOS 14.  What devices are you guys seeing this on?

<img width="226" alt="Screen Shot 2020-11-05 at 9 38 18 AM" src="https://user-images.githubusercontent.com/389558/98276398-c2224980-1f4a-11eb-843b-15201583f58b.png">

**Comment by pedromassangocode** [comment] 2020-11-06 07:32
Sorry I forgot to mention that I used an Android device:
`• sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)`

Maybe it is Android specific?

**Comment by voiddog** [comment] 2020-11-06 07:39
@justinmc 
My device is android，HUAWEI P30 pro。

On your screenshot, the text is also cropped. About 1-2 pixels cropped

**Comment by voiddog** [comment] 2020-11-06 07:57
Here is the difference. 

Current:
<img width="400" src="https://i.imgur.com/bNPmP7R.png">

After remove pending:
<img width="400" src="https://i.imgur.com/ddPeGMk.png">

> There is a difference of about one pixel at the bottom

**Comment by pedromassangocode** [comment] 2020-11-06 08:02
Yes, this definitely is not Android specific.

Android on the left and iOS on the right

![Screen Shot 2020-11-06 at 09 00 09](https://user-images.githubusercontent.com/67424416/98341141-b13b0c00-200e-11eb-94ab-3c747b52a54c.png)

**Comment by voiddog** [comment] 2020-11-06 08:09
> Here is the difference.
> 
> Current:
> <img alt="" width="400" src="https://camo.githubusercontent.com/c80351e8cd45f2556f0045dd8a5d88e465775fe4bab738f0fdc1c673dbe6b640/68747470733a2f2f692e696d6775722e636f6d2f624e506d5037522e706e67">
> 
> After remove pending:
> <img alt="" width="400" src="https://camo.githubusercontent.com/ec970c650e5d48a91fc2b631cd31bfb35e69d34feff1b5ab8a9642c06d176c4c/68747470733a2f2f692e696d6775722e636f6d2f64645065474d6b2e706e67">
> 
> > There is a difference of about one pixel at the bottom

Sorry, what I said is a bit vague, I mean there is something wrong with the iOS platform too. Both image above is on iOS and The second picture is after I removed the pending in the framework. @pedromassangocode

**Comment by justinmc** [comment] 2021-01-20 22:27
Related to https://github.com/flutter/flutter/issues/73681?

**Comment by pedromassangocode** [comment] 2021-01-21 09:23
> Related to #73681?

Yes, looks like they are duplicate!?

**Comment by justinmc** [comment] 2021-01-26 22:49
Alright I'll close that one since it's newer and we can focus discussion here.

From that issue, I believe the problem is due to a change to CupertinoButton recently: https://github.com/flutter/flutter/issues/73681#issuecomment-758108087

We should try to figure out what change caused that.

**Comment by HarveyLee1228** [comment] 2021-01-28 06:00
same problem

**Comment by justinmc** [comment] 2021-02-18 21:28
This may be related to https://github.com/flutter/flutter/issues/45481, where the text is clipped in English if the accessibility text size is increased.

**Comment by maheshmnj** [comment] 2022-12-22 00:07
Reproduces on both Android and IOS

### IOS
<img width="430" alt="image" src="https://user-images.githubusercontent.com/31410839/209026037-a349fab5-7a0d-437d-90f1-2dc51136526f.png">

 ### Android
<img width="315" alt="image" src="https://user-images.githubusercontent.com/31410839/209026066-5f9c2bc3-5ca1-478e-8a6d-afad48b88086.png">

<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel master, 3.7.0-3.0.pre.33, on macOS 12.6 21G115 darwin-arm64, locale en-IN)
    • Flutter version 3.7.0-3.0.pre.33 on channel master 
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5201856805 (38 minutes ago), 2022-12-05 18:27:21 -0800
    • Engine revision a309d239c4
    • Dart version 2.19.0 (build 2.19.0-463.0.dev)
    • DevTools version 2.20.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly
      to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.70.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.55.20221129

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • 026D5789-9E78-4AD5-B1B2-3F8D4E7F65E4 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.6 21G115 darwin-arm64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 108.0.5359.94

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
```
[✓] Flutter (Channel stable, 3.3.9, on macOS 12.6 21G115 darwin-arm, locale en-IN)
    • Flutter version 3.3.9 on channel stable at /Users/mahesh/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b8f7f1f986 (24 hours ago), 2022-11-23 06:43:51 +0900
    • Engine revision 8f2221fbef
    • Dart version 2.18.5
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.70.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.53.20221101

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • 026D5789-9E78-4AD5-B1B2-3F8D4E7F65E4 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.6 21G115 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 107.0.5304.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by oke331** [comment] 2023-08-22 23:53
I'm encountering the same issue while using Flutter version 3.13.0 in a Japanese context.
Could someone guide me on how to resolve this issue?
please refer to the following comment -> https://github.com/flutter/flutter/issues/132819#issuecomment-1684831363

**Comment by tgucio** [comment] 2023-09-22 17:14
This should be fixed by https://github.com/flutter/flutter/pull/133386.

**Closed by tgucio** 2023-09-22 17:14 UTC
Labels: a: text input, c: regression, framework, a: internationalization, a: quality, has reproducible steps, P2, found in release: 3.3, found in release: 3.7, team-framework, triaged-framework
