### ISSUE TITLE
Flutter Engine Crash 

### ISSUE THREAD

**Issue by kw2019ltd** [flutter/flutter#52222] opened 2020-03-09 07:39 UTC
Fatal Exception: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/kw.ltd.twitter.facebook.youtube.twitter_facebook_youtube_app-6SFVJmS4hqvvrNOlCFDkgg==/base.apk"],nativeLibraryDirectories=[/data/app/kw.ltd.twitter.facebook.youtube.twitter_facebook_youtube_app-6SFVJmS4hqvvrNOlCFDkgg==/lib/arm64, /system/lib64, /product/lib64]]] couldn't find "libflutter.so"
       at java.lang.Runtime.loadLibrary0(Runtime.java:1067)
       at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
       at java.lang.System.loadLibrary(System.java:1667)
       at io.flutter.embedding.engine.loader.FlutterLoader.startInitialization(FlutterLoader.java:122)
       at io.flutter.embedding.engine.loader.FlutterLoader.startInitialization(FlutterLoader.java:93)
       at io.flutter.view.FlutterMain.startInitialization(FlutterMain.java:45)
       at io.flutter.app.FlutterApplication.onCreate(FlutterApplication.java:22)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1189)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6460)
       at android.app.ActivityThread.access$1300(ActivityThread.java:219)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7356)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

firebase crachlytics
![image](https://user-images.githubusercontent.com/47334522/76192066-8c756700-61e9-11ea-99a7-2f37ceeedfd6.png)

$ flutter doctor -v
09:20
[✓] Flutter (Channel unknown, v1.12.13+hotfix.8, on Linux, locale en_US.UTF-8)
    • Flutter version 1.12.13+hotfix.8 at /home/cirrus/sdks/flutter
    • Framework revision 0b8abb4724 (4 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /opt/android-sdk-linux
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /opt/android-sdk-linux
    • ANDROID_SDK_ROOT = /opt/android-sdk-linux
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_222-8u222-b10-1ubuntu1~18.04.1-b10)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).
[!] Connected device
    ! No devices available
! Doctor found issues in 3 categories.

**Comment by TahaTesser** [comment] 2020-03-09 09:13
Hi @kw2019ltd 
Please try this possible [solution](https://stackoverflow.com/a/52889813)
Thank you

**Comment by kw2019ltd** [comment] 2020-03-09 13:22
not working,, i need solution from flutter team on some devices flutter framework 32 or 64 bit works fine on other devices its not.

new issue opened as old thread closed 
https://github.com/flutter/flutter/issues/37566#issuecomment-596249746

**Comment by TahaTesser** [comment] 2020-03-09 13:27
Hi @kw2019ltd 
Please take a look at this [comment](https://github.com/flutter/flutter/issues/37566#issuecomment-517991466) from the issue you mentioned

Thank you

**Comment by TahaTesser** [comment] 2020-03-09 13:30
Closing this duplicate of [#37566](https://github.com/flutter/flutter/issues/37566), since the other one has more information

**Closed by TahaTesser** 2020-03-09 13:30 UTC
Labels: in triage, waiting for customer response
