### ISSUE TITLE
flutter analyze seems to be broken

### ISSUE THREAD

**Issue by vlidholt** [flutter/flutter#9438] opened 2017-04-18 12:57 UTC
## Steps to Reproduce

After upgrading flutter to the latest version I get a lot of erroneous warnings and errors when running `flutter analyze`. Many of the warnings are reported multiple times (the warnings seem valid though). But most disturbingly I get errors at the very start of some files:

`error • Invalid constant value at lib/page_error.dart:1:1 • invalid_constant`

All files has the same encoding (according to IntelliJ), and I've checked with a binary viewer `xxd` and there seem to be no weird invisible characters at the beginning of the affected files.

First lines of output from xxd:
```
00000000: 696d 706f 7274 2027 6461 7274 3a69 6f27  import 'dart:io'
00000010: 3b0a 696d 706f 7274 2027 6461 7274 3a6d  ;.import 'dart:m
00000020: 6174 6827 3b0a 0a69 6d70 6f72 7420 2770  ath';..import 'p
00000030: 6163 6b61 6765 3a66 6c75 7474 6572 2f6d  ackage:flutter/m
```

## Logs

Complete output from flutter analyze:
```
Viktors-MacBook-Pro:Newsvoice vik$ flutter analyze
Analyzing /Users/vik/Projects/NewsVoice/NewsvoiceApp/Newsvoice...
     hint • Unused import at lib/aspectorama_api.dart:4:8 • unused_import
     hint • Unused import at lib/aspectorama_api.dart:5:8 • unused_import
     hint • Unused import at lib/aspectorama_api.dart:13:8 • unused_import
     hint • Unused import at lib/service_universal_links.dart:1:8 • unused_import
     hint • Unused import at lib/aspectorama_api.dart:4:8 • unused_import
     hint • Unused import at lib/aspectorama_api.dart:5:8 • unused_import
     hint • Unused import at lib/aspectorama_api.dart:13:8 • unused_import
     hint • Unused import at lib/service_universal_links.dart:1:8 • unused_import
    error • Invalid constant value at lib/page_error.dart:1:1 • invalid_constant
    error • Invalid constant value at lib/page_onboarding.dart:1:1 • invalid_constant
    error • Invalid constant value at lib/widget_newsmix.dart:1:1 • invalid_constant
    error • Invalid constant value at lib/widgets_material.dart:1:1 • invalid_constant
    error • Arguments of a constant creation must be constant expressions at lib/widgets_material.dart:1:1 • const_with_non_constant_argument
    error • Invalid constant value at lib/widgets_news.dart:1:1 • invalid_constant
    error • Invalid constant value at lib/widgets_scaffold.dart:1:1 • invalid_constant
     hint • Unused import at lib/aspectorama_api.dart:4:8 • unused_import
     hint • Unused import at lib/aspectorama_api.dart:5:8 • unused_import
     hint • Unused import at lib/aspectorama_api.dart:13:8 • unused_import
     hint • Unused import at lib/page_category.dart:1:8 • unused_import
     hint • Unused import at lib/service_universal_links.dart:1:8 • unused_import
     hint • Unused import at lib/widgets_comments.dart:5:8 • unused_import
    error • Invalid constant value at lib/page_error.dart:1:1 • invalid_constant
    error • Invalid constant value at lib/page_onboarding.dart:1:1 • invalid_constant
    error • Invalid constant value at lib/widget_newsmix.dart:1:1 • invalid_constant
    error • Invalid constant value at lib/widgets_material.dart:1:1 • invalid_constant
    error • Arguments of a constant creation must be constant expressions at lib/widgets_material.dart:1:1 • const_with_non_constant_argument
    error • Invalid constant value at lib/widgets_news.dart:1:1 • invalid_constant
    error • Invalid constant value at lib/widgets_scaffold.dart:1:1 • invalid_constant
     hint • Unused import at lib/aspectorama_api.dart:4:8 • unused_import
     hint • Unused import at lib/aspectorama_api.dart:5:8 • unused_import
     hint • Unused import at lib/aspectorama_api.dart:13:8 • unused_import
     hint • Unused import at lib/page_category.dart:1:8 • unused_import
     hint • Unused import at lib/service_universal_links.dart:1:8 • unused_import
     hint • Unused import at lib/widgets_comments.dart:5:8 • unused_import
    error • Invalid constant value at lib/widgets_scaffold.dart:1:1 • invalid_constant
     hint • Unused import at lib/aspectorama_api.dart:4:8 • unused_import
     hint • Unused import at lib/aspectorama_api.dart:5:8 • unused_import
     hint • Unused import at lib/aspectorama_api.dart:13:8 • unused_import
     hint • Unused import at lib/service_universal_links.dart:1:8 • unused_import
    error • Invalid constant value at lib/widget_newsmix.dart:1:1 • invalid_constant
    error • Invalid constant value at lib/widgets_scaffold.dart:1:1 • invalid_constant
     hint • Unused import at lib/aspectorama_api.dart:4:8 • unused_import
     hint • Unused import at lib/aspectorama_api.dart:5:8 • unused_import
     hint • Unused import at lib/aspectorama_api.dart:13:8 • unused_import
     hint • Unused import at lib/service_universal_links.dart:1:8 • unused_import
    error • Invalid constant value at lib/widgets_material.dart:1:1 • invalid_constant
    error • Arguments of a constant creation must be constant expressions at lib/widgets_material.dart:1:1 • const_with_non_constant_argument
    error • Invalid constant value at lib/widgets_news.dart:1:1 • invalid_constant
    error • Invalid constant value at lib/widgets_scaffold.dart:1:1 • invalid_constant
     hint • Unused import at lib/aspectorama_api.dart:4:8 • unused_import
     hint • Unused import at lib/aspectorama_api.dart:5:8 • unused_import
     hint • Unused import at lib/aspectorama_api.dart:13:8 • unused_import
     hint • Unused import at lib/page_category.dart:1:8 • unused_import
     hint • Unused import at lib/service_universal_links.dart:1:8 • unused_import
     hint • Unused import at lib/widgets_comments.dart:5:8 • unused_import
    error • Invalid constant value at lib/page_error.dart:1:1 • invalid_constant
     hint • Unused import at lib/aspectorama_api.dart:4:8 • unused_import
     hint • Unused import at lib/aspectorama_api.dart:5:8 • unused_import
     hint • Unused import at lib/aspectorama_api.dart:13:8 • unused_import
     hint • Unused import at lib/service_universal_links.dart:1:8 • unused_import
    error • Invalid constant value at lib/widgets_scaffold.dart:1:1 • invalid_constant
     hint • Unused import at lib/aspectorama_api.dart:4:8 • unused_import
     hint • Unused import at lib/aspectorama_api.dart:5:8 • unused_import
     hint • Unused import at lib/aspectorama_api.dart:13:8 • unused_import
     hint • Unused import at lib/service_universal_links.dart:1:8 • unused_import
     hint • Unused import at lib/aspectorama_api.dart:4:8 • unused_import
     hint • Unused import at lib/aspectorama_api.dart:5:8 • unused_import
     hint • Unused import at lib/aspectorama_api.dart:13:8 • unused_import
     hint • Unused import at lib/service_universal_links.dart:1:8 • unused_import
    error • Invalid constant value at lib/widget_newsmix.dart:1:1 • invalid_constant
    error • Invalid constant value at lib/widgets_material.dart:1:1 • invalid_constant
    error • Arguments of a constant creation must be constant expressions at lib/widgets_material.dart:1:1 • const_with_non_constant_argument
    error • Invalid constant value at lib/widgets_news.dart:1:1 • invalid_constant
    error • Invalid constant value at lib/widgets_scaffold.dart:1:1 • invalid_constant
     hint • Unused import at lib/aspectorama_api.dart:4:8 • unused_import
     hint • Unused import at lib/aspectorama_api.dart:5:8 • unused_import
     hint • Unused import at lib/aspectorama_api.dart:13:8 • unused_import
     hint • Unused import at lib/page_category.dart:1:8 • unused_import
     hint • Unused import at lib/service_universal_links.dart:1:8 • unused_import
     hint • Unused import at lib/widgets_comments.dart:5:8 • unused_import
    error • Invalid constant value at lib/widgets_material.dart:1:1 • invalid_constant
    error • Arguments of a constant creation must be constant expressions at lib/widgets_material.dart:1:1 • const_with_non_constant_argument
    error • Invalid constant value at lib/widgets_news.dart:1:1 • invalid_constant
    error • Invalid constant value at lib/widgets_scaffold.dart:1:1 • invalid_constant
     hint • Unused import at lib/aspectorama_api.dart:4:8 • unused_import
     hint • Unused import at lib/aspectorama_api.dart:5:8 • unused_import
     hint • Unused import at lib/aspectorama_api.dart:13:8 • unused_import
     hint • Unused import at lib/service_universal_links.dart:1:8 • unused_import
     hint • Unused import at lib/widgets_comments.dart:5:8 • unused_import
    error • Invalid constant value at lib/widgets_material.dart:1:1 • invalid_constant
    error • Arguments of a constant creation must be constant expressions at lib/widgets_material.dart:1:1 • const_with_non_constant_argument
    error • Invalid constant value at lib/widgets_news.dart:1:1 • invalid_constant
    error • Invalid constant value at lib/widgets_scaffold.dart:1:1 • invalid_constant
     hint • Unused import at lib/aspectorama_api.dart:4:8 • unused_import
     hint • Unused import at lib/aspectorama_api.dart:5:8 • unused_import
     hint • Unused import at lib/aspectorama_api.dart:13:8 • unused_import
     hint • Unused import at lib/service_universal_links.dart:1:8 • unused_import
     hint • Unused import at lib/widgets_comments.dart:5:8 • unused_import
    error • Invalid constant value at lib/page_onboarding.dart:1:1 • invalid_constant
    error • Invalid constant value at lib/widget_newsmix.dart:1:1 • invalid_constant
     hint • Unused import at lib/aspectorama_api.dart:4:8 • unused_import
     hint • Unused import at lib/aspectorama_api.dart:5:8 • unused_import
     hint • Unused import at lib/aspectorama_api.dart:13:8 • unused_import
     hint • Unused import at lib/service_universal_links.dart:1:8 • unused_import
    error • Invalid constant value at lib/widgets_material.dart:1:1 • invalid_constant
    error • Arguments of a constant creation must be constant expressions at lib/widgets_material.dart:1:1 • const_with_non_constant_argument
    error • Invalid constant value at lib/widgets_news.dart:1:1 • invalid_constant
    error • Invalid constant value at lib/widgets_scaffold.dart:1:1 • invalid_constant
     hint • Unused import at lib/aspectorama_api.dart:4:8 • unused_import
     hint • Unused import at lib/aspectorama_api.dart:5:8 • unused_import
     hint • Unused import at lib/aspectorama_api.dart:13:8 • unused_import
     hint • Unused import at lib/service_universal_links.dart:1:8 • unused_import
     hint • Unused import at lib/widgets_comments.dart:5:8 • unused_import
     hint • Unused import at lib/aspectorama_api.dart:4:8 • unused_import
     hint • Unused import at lib/aspectorama_api.dart:5:8 • unused_import
     hint • Unused import at lib/aspectorama_api.dart:13:8 • unused_import
     hint • Unused import at lib/service_universal_links.dart:1:8 • unused_import
     hint • Unused import at lib/aspectorama_api.dart:4:8 • unused_import
     hint • Unused import at lib/aspectorama_api.dart:5:8 • unused_import
     hint • Unused import at lib/aspectorama_api.dart:13:8 • unused_import
     hint • Unused import at lib/service_universal_links.dart:1:8 • unused_import
     hint • Unused import at lib/aspectorama_api.dart:4:8 • unused_import
     hint • Unused import at lib/aspectorama_api.dart:5:8 • unused_import
     hint • Unused import at lib/aspectorama_api.dart:13:8 • unused_import
     hint • Unused import at lib/service_universal_links.dart:1:8 • unused_import
     hint • Unused import at lib/aspectorama_api.dart:4:8 • unused_import
     hint • Unused import at lib/aspectorama_api.dart:5:8 • unused_import
     hint • Unused import at lib/aspectorama_api.dart:13:8 • unused_import
     hint • Unused import at lib/service_universal_links.dart:1:8 • unused_import
    error • Invalid constant value at lib/widget_newsmix.dart:1:1 • invalid_constant
     hint • Unused import at lib/aspectorama_api.dart:4:8 • unused_import
     hint • Unused import at lib/aspectorama_api.dart:5:8 • unused_import
     hint • Unused import at lib/aspectorama_api.dart:13:8 • unused_import
     hint • Unused import at lib/service_universal_links.dart:1:8 • unused_import
    error • Invalid constant value at lib/widgets_material.dart:1:1 • invalid_constant
    error • Arguments of a constant creation must be constant expressions at lib/widgets_material.dart:1:1 • const_with_non_constant_argument
    error • Invalid constant value at lib/widgets_news.dart:1:1 • invalid_constant
    error • Invalid constant value at lib/widgets_scaffold.dart:1:1 • invalid_constant
     hint • Unused import at lib/aspectorama_api.dart:4:8 • unused_import
     hint • Unused import at lib/aspectorama_api.dart:5:8 • unused_import
     hint • Unused import at lib/aspectorama_api.dart:13:8 • unused_import
     hint • Unused import at lib/service_universal_links.dart:1:8 • unused_import
     hint • Unused import at lib/widgets_comments.dart:5:8 • unused_import
    error • Invalid constant value at lib/widgets_material.dart:1:1 • invalid_constant
    error • Arguments of a constant creation must be constant expressions at lib/widgets_material.dart:1:1 • const_with_non_constant_argument
    error • Invalid constant value at lib/widgets_material.dart:1:1 • invalid_constant
    error • Arguments of a constant creation must be constant expressions at lib/widgets_material.dart:1:1 • const_with_non_constant_argument
    error • Invalid constant value at lib/widgets_news.dart:1:1 • invalid_constant
    error • Invalid constant value at lib/widgets_scaffold.dart:1:1 • invalid_constant
     hint • Unused import at lib/aspectorama_api.dart:4:8 • unused_import
     hint • Unused import at lib/aspectorama_api.dart:5:8 • unused_import
     hint • Unused import at lib/aspectorama_api.dart:13:8 • unused_import
     hint • Unused import at lib/service_universal_links.dart:1:8 • unused_import
     hint • Unused import at lib/widgets_comments.dart:5:8 • unused_import
     hint • Unused import at lib/aspectorama_api.dart:4:8 • unused_import
     hint • Unused import at lib/aspectorama_api.dart:5:8 • unused_import
     hint • Unused import at lib/aspectorama_api.dart:13:8 • unused_import
     hint • Unused import at lib/service_universal_links.dart:1:8 • unused_import
    error • Invalid constant value at lib/widgets_scaffold.dart:1:1 • invalid_constant
     hint • Unused import at lib/aspectorama_api.dart:4:8 • unused_import
     hint • Unused import at lib/aspectorama_api.dart:5:8 • unused_import
     hint • Unused import at lib/aspectorama_api.dart:13:8 • unused_import
     hint • Unused import at lib/service_universal_links.dart:1:8 • unused_import
54 errors and 109 hints found.
(Ran in 5.9s)
```

## Flutter Doctor

[✓] Flutter (on Mac OS X 10.12.3 16D32, channel master)
    • Flutter at /Users/vik/Projects/flutter
    • Framework revision b52d659406 (14 hours ago), 2017-04-17 15:44:41 -0700
    • Engine revision c24a0e5175
    • Tools Dart version 1.23.0-dev.11.7

[✓] Host Executable Compatibility
    • Downloaded executables execute on host

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.2)
    • Android SDK at /Users/vik/Library/Android/sdk
    • Platform android-25, build-tools 25.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.3, Build version 8E162
    • ios-deploy 1.9.1
    • CocoaPods version 1.2.0

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Gradle version 3.2
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2016.3.4)
    • Dart plugin version 163.13137
    • Flutter plugin version 0.1.11.1

[✓] Connected devices
    • Nexus 5X • 01023965355db590 • android-arm • Android 6.0 (API 23)

**Comment by vlidholt** [comment] 2017-04-18 13:00
Running and compiling the app works fine, both on iOS and Android.

**Comment by eseidelGoogle** [comment] 2017-04-18 13:26
CC @pq @devoncarew @danrubel

**Comment by devoncarew** [comment] 2017-04-18 14:51
I think the issue duplication happened when we moved over to using the `dartanalyzer` command directly. I have a PR to address that. Not sure about the `error • Invalid constant value at lib/page_error.dart:1:1` invalid constant at line 1, col 1; @pq, @bwilkerson, does that sound familiar?

**Comment by pq** [comment] 2017-04-18 15:21
Yep. I was going to chime in. Very familiar.  See: https://github.com/dart-lang/sdk/issues/29281.

A quick fix should be an `.analysis_options` tweak.  Beyond that, summary deserialization should fail less catastrophically.  @bwilkerson and I have chatted about this but I don't know where we stand.

cc @scheglov

**Comment by scheglov** [comment] 2017-04-18 15:27
It's not related to deserialization from FlatBuffer.
These errors are actually reported, because of problems in constants analysis.
See https://github.com/dart-lang/sdk/issues/29358 and the comment referenced from there for details.

**Comment by pq** [comment] 2017-04-18 15:50
Ah, right.  I was conflating a few issues that happened around the same time.  Sounds like the short-term fix is the same though.  I wonder, given how often this has happened, if we couldn't detect this and produce a better error?

**Comment by scheglov** [comment] 2017-04-18 15:52
Of course we can.
I started working on the fix last Friday, but was not able to finish it yet.

**Comment by scheglov** [comment] 2017-04-18 18:03
https://codereview.chromium.org/2825813002

**Comment by pq** [comment] 2017-04-18 18:15
Awesome!

**Comment by scheglov** [comment] 2017-04-18 19:22
The issue is [fixed](https://github.com/dart-lang/sdk/commit/19353f9e633313e9b7452a51e9a80b09a16d25f0).
I tested that it works with the provided [test case](https://github.com/dart-lang/sdk/issues/29358).

**Comment by pq** [comment] 2017-04-18 19:56
Fantastic!

**Comment by devoncarew** [comment] 2017-04-18 21:03
Closing; @vlidholt, you should see the de-dups issue fixed when you update flutter, and constant locations issue fixed the next time the dart sdk is rolled into flutter.

**Comment by vlidholt** [comment] 2017-04-19 08:39
Nice! Thanks for fixing this so fast! :)

**Comment by vlidholt** [comment] 2017-04-28 14:28
This is still not fixed in the latest version of Flutter.

```
Viktors-MacBook-Pro:Newsvoice vik$ flutter analyze
Analyzing /Users/vik/Projects/NewsVoice/NewsvoiceApp/Newsvoice...
    error • Invalid constant value at lib/page_error.dart:1:1 • invalid_constant
    error • Invalid constant value at lib/page_onboarding.dart:1:1 • invalid_constant
    error • Invalid constant value at lib/widget_news_item_page_route.dart:1:1 • invalid_constant
    error • Invalid constant value at lib/widget_newsmix.dart:1:1 • invalid_constant
    error • Invalid constant value at lib/widgets_material.dart:1:1 • invalid_constant
    error • Arguments of a constant creation must be constant expressions at lib/widgets_material.dart:1:1 • const_with_non_constant_argument
    error • Invalid constant value at lib/widgets_news.dart:1:1 • invalid_constant
    error • Invalid constant value at lib/widgets_scaffold.dart:1:1 • invalid_constant
     hint • The member 'activity' can only be used within instance members of subclasses of 'ScrollPosition' at lib/page_category.dart:33:57 • invalid_use_of_protected_member
9 issues found.
(Ran in 6.4s)
```

# Flutter doctor
```
[✓] Flutter (on Mac OS X 10.12.3 16D32, channel master)
    • Flutter at /Users/vik/Projects/flutter
    • Framework revision f2e89681d9 (12 hours ago), 2017-04-27 19:55:54 -0700
    • Engine revision 7c699ce772
    • Tools Dart version 1.23.0-dev.11.11

[✓] Host Executable Compatibility
    • Downloaded executables execute on host

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.2)
    • Android SDK at /Users/vik/Library/Android/sdk
    • Platform android-25, build-tools 25.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.3, Build version 8E162
    • ios-deploy 1.9.1
    • CocoaPods version 1.2.0

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Gradle version 3.2
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2016.3.4)
    • Dart plugin version 163.13137
    • Flutter plugin version 0.1.11.1

[✓] Connected devices
    • iPhone 6 • 10BE1E9A-DA0E-42A7-8F22-2C18F58F3EE7 • ios • iOS 10.3 (simulator)
```

**Comment by eseidelGoogle** [comment] 2017-04-28 14:29
This is presumably https://github.com/dart-lang/sdk/issues/29109? @rxlabs was also reporting similarly in flutter gitter this morning.

**Comment by vlidholt** [comment] 2017-04-28 14:31
I'm not using aliased imports, so I doubt it's the same.

<img width="760" alt="screen shot 2017-04-28 at 4 29 24 pm" src="https://cloud.githubusercontent.com/assets/1539812/25533204/2695c5e8-2c30-11e7-9781-437ee4d2ef5f.png">

**Comment by eseidelGoogle** [comment] 2017-04-28 15:07
@pq do we need to roll to 1.24 to pick up this change?

**Comment by Skylled** [comment] 2017-05-03 18:51
Just want to report that I have been bypassing the minor annoyance of this issue by adding a newline to the top of my files. The analyzer instantly stops complaining.

**Comment by pq** [comment] 2017-05-05 19:47
> @pq do we need to roll to 1.24 to pick up this change?

Sorry for the slow reply...  Yep, this fix is in `1.24`.

**Comment by lukef** [comment] 2017-05-13 16:16
I know the issue says fixed in `1.24`, but i'm seeing it in `1.23.0-dev.11.11`. Does the `1.23-dev` builds contain the fix?

**Comment by devoncarew** [comment] 2017-05-13 18:26
No, the fix isn't until 1.24. I don't expect that flutter will roll to that version for at least another week. I'd look into the workaround mentioned [above](https://github.com/flutter/flutter/issues/9438#issuecomment-299001947), or manually roll your version of flutter forward by editing the `bin/internal/dart-sdk.version` file.

**Comment by lukef** [comment] 2017-05-13 19:16
That worked. Thanks and thanks for the clarification.

**Comment by raju-bitter** [comment] 2017-05-17 09:49
Another workaround is to create an .analysis_options file in the Flutter project folder and add:
```
analyzer:
  language:
    enableStrictCallChecks: true
    enableSuperMixins: true
    enableAssertInitializer: true
```

**Comment by Skylled** [comment] 2017-05-24 15:15
This should be closed with #10110, right?

**Comment by sethladd** [comment] 2017-05-24 16:00
Yeah, hopefully https://github.com/flutter/flutter/issues/9438#issuecomment-302042073 is a short-term bandaid. That should "just work" now.

**Comment by mit-mit** [comment] 2017-06-08 16:03
@vlidholt are we OK to close this?

**Closed** 2017-06-08 21:38 UTC
Labels: customer: newsvoice (eap), dependency: dart, dev: tool, dev: tool - analyze
