### ISSUE TITLE
[tool_crash] _TypeError: (#0      _ProgramInfoBuilder.createInfoNodeFor (package:vm_snapshot_analysis/v8_profile.dart:419:75))

### ISSUE THREAD

**Issue by galunecandrey** [flutter/flutter#129706] opened 2023-06-28 11:45 UTC
## Command
```
flutter build macos --build-name=23.6.28 --build-number=2068 --analyze-size --code-size-directory /Users/visionable/bitbucket-runner/temp/14ef2ece-6c36-58df-82f8-9c6873a20375/build --dart-define=ServiceHost=https://app.visionable.one --release
```

I know about:
```
flutter channel master
flutter upgrade
```
But it does not help

I believe the problems in 'records'

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
_TypeError: (#0      _ProgramInfoBuilder.createInfoNodeFor (package:vm_snapshot_analysis/v8_profile.dart:419:75))
```
#0      _ProgramInfoBuilder.createInfoNodeFor (package:vm_snapshot_analysis/v8_profile.dart:419:75)
#1      _ProgramInfoBuilder.getInfoNodeFor (package:vm_snapshot_analysis/v8_profile.dart:374:14)
#2      ListIterable.forEach (dart:_internal/iterable.dart:39:13)
#3      _ProgramInfoBuilder.build (package:vm_snapshot_analysis/v8_profile.dart:338:16)
#4      toProgramInfo (package:vm_snapshot_analysis/v8_profile.dart:282:8)
#5      _treemapFromSnapshot (package:vm_snapshot_analysis/treemap.dart:158:27)
#6      treemapFromJson (package:vm_snapshot_analysis/treemap.dart:85:5)
#7      SizeAnalyzer.analyzeAotSnapshot (package:flutter_tools/src/base/analyze_size.dart:61:59)
#8      buildMacOS (package:flutter_tools/src/macos/build_macos.dart:160:60)
<asynchronous suspension>
#9      BuildMacosCommand.runCommand (package:flutter_tools/src/commands/build_macos.dart:62:5)
<asynchronous suspension>
#10     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1297:27)
<asynchronous suspension>
#11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#12     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#13     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:339:9)
<asynchronous suspension>
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#15     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:285:5)
<asynchronous suspension>
#16     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:115:9)
```
```
[✓] Flutter (Channel master, 3.12.0-11.0.pre.52, on macOS 13.4.1 22F82 darwin-arm64 (Rosetta), locale en-US)
    • Flutter version 3.12.0-11.0.pre.52 on channel master at /Users/visionable/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 43bda355b0 (2 hours ago), 2023-06-28 05:17:25 -0400
    • Engine revision 17173994a8
    • Dart version 3.1.0 (build 3.1.0-255.0.dev)
    • DevTools version 2.24.0

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] Connected device (1 available)
    • macOS (desktop) • macos • darwin-arm64 • macOS 13.4.1 22F82 darwin-arm64 (Rosetta)

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 3 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.1.0+15
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 18116933e77adc82f80866c928266a5b4f1ed645
### Plugins
app_links-3.4.3
app_settings-4.2.0
audio_session-0.1.16
audioplayers-4.1.0
audioplayers_android-3.0.2
audioplayers_darwin-4.1.0
audioplayers_linux-2.1.0
audioplayers_web-3.1.0
audioplayers_windows-2.0.2
connectivity_plus-4.0.1
desktop_lifecycle-0.1.1
desktop_sleep
desktop_window-0.4.0
file_picker-5.3.2
firebase_core-2.14.0
firebase_core_web-2.6.0
firebase_messaging-14.6.3
firebase_messaging_web-3.5.3
flutter_app_badger-1.5.0
flutter_local_notifications-14.1.1
flutter_plugin_android_lifecycle-2.0.15
flutter_udid-2.0.1
integration_test
meeting_sdk
notification_module
package_info_plus-4.0.2
path_provider-2.0.15
path_provider_android-2.0.27
path_provider_foundation-2.2.3
path_provider_linux-2.1.11
path_provider_windows-2.1.7
permission_handler-10.3.0
permission_handler_android-10.2.3
permission_handler_apple-9.1.0
permission_handler_windows-0.1.2
realm-1.2.0
sentry_flutter-7.8.0
system_tools
system_tray-2.0.3
url_launcher-6.1.11
url_launcher_android-6.0.35
url_launcher_ios-6.1.4
url_launcher_linux-3.0.5
url_launcher_macos-3.0.5
url_launcher_web-2.0.17
url_launcher_windows-3.0.6
wakelock-0.6.2
wakelock_macos-0.4.0
wakelock_web-0.4.0
win_local_notifier

**Comment by darshankawar** [comment] 2023-06-28 13:13
Thanks for the report. I tried running the same command on a sample app using latest master version which executed properly giving analysis as below:

```
dhs@Dhss-MacBook-Pro issue_bug % flutter build macos --build-name=23.6.28 --build-number=2068 --analyze-size --code-size-directory /Users/dhs/documents/ --dart-define=ServiceHost=https://app.visionable.one --release

Building macOS application...                                           
▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  issue_bug.app                                                            48 MB
  issue_bug.app/
    Contents/
      _CodeSignature                                                        9 KB
      MacOS                                                               174 KB
      Resources                                                           189 KB
      Frameworks                                                           47 MB
      Dart AOT symbols accounted decompressed size                          5 MB
        package:flutter                                                     3 MB
        dart:core                                                         279 KB
        dart:ui                                                           270 KB
        dart:typed_data                                                   190 KB
        dart:collection                                                   111 KB
        dart:async                                                         88 KB
        dart:ffi                                                           70 KB
        dart:convert                                                       59 KB
        dart:io                                                            52 KB
        package:characters                                                 34 KB
        dart:isolate                                                       30 KB
        package:vector_math/
          vector_math_64.dart                                              29 KB
        dart:developer                                                      9 KB
        package:issue_bug/
          main.dart                                                         3 KB
        dart:math                                                           3 KB
        file:/
          /
            /
              Users/
                dhs/
                  Documents/
                    NCFlutter/
                      issue_bug/
                        .dart_tool/
                          flutter_build/
                            dart_plugin_registrant.dart                     2 KB
        dart:mirrors                                                        1 KB
        package:plugin_platform_interface/
          plugin_platform_interface.dart                                    1 KB
        dart:vmservice_io                                                 1003 B
        package:collection/
          src/
            priority_queue.dart                                            842 B
      Info.plist                                                            2 KB
▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒
A summary of your macOS bundle analysis can be found at: /Users/dhs/.flutter-devtools/macos-code-size-analysis_01.json

To analyze your app size in Dart DevTools, run the following command:
dart devtools --appSizeBase=macos-code-size-analysis_01.json
dhs@Dhss-MacBook-Pro issue_bug % 
```

Keeping this issue open based on the report and error being thrown.

/cc @mkustermann for thoughts, as the log seems related to recent fixed issue https://github.com/flutter/flutter/issues/128402

**Comment by mkustermann** [comment] 2023-06-28 13:18
@galunecandrey Could you try this with newest flutter `main` / `master` channel. If it still reproduces, we'll take a look.

**Comment by galunecandrey** [comment] 2023-06-28 13:25
@mkustermann I tried and it does not work. We have problem only on our mac mini silicone build machine. But my own macbook pro with m1 pro work fine. Also we discovered that if remove dart 3 records from code it builds fine on build machine

**Comment by mkustermann** [comment] 2023-06-28 13:28
>  Also we discovered that if remove dart 3 records from code it builds fine on build machine

@galunecandrey Could you provide a minimal reproduction? What kind of record usage triggers this?

@sstrickl Could you take a look?

**Comment by galunecandrey** [comment] 2023-06-28 13:34
@mkustermann 
```
Stream<({FullAudioDeviceSettingsModel? micSettings, bool isOn})> getMicSettingsWithEnabledStateStream(
    StateStream<CallOptionsModel> callOptionsStream,
  ) =>
      Rx.combineLatest2<FullAudioDeviceSettingsModel?, bool, ({FullAudioDeviceSettingsModel? micSettings, bool isOn})>(
        micSettingsStream,
        callOptionsStream.call(sendFirst: true).map((event) => event.micOn),
        (a, b) => (micSettings: a, isOn: b),
      ).distinct();
```

**Comment by galunecandrey** [comment] 2023-06-28 13:58
@mkustermann on x86 we don't have `--analyze-size` and thats why it works))

**Comment by galunecandrey** [comment] 2023-06-28 14:17
Without dart 3 records it works fine with `--analyze-size`

**Comment by KonstantinRr** [comment] 2023-06-29 09:07
I’m having the same issue on `master` (3.12.0-12.0.pre.52). The setup is very similar to the one mentioned above with M1 silicon and use of records. The issue only appears when running with `—analyse-size`

```
Flutter crash report.
Please report a bug at https://github.com/flutter/flutter/issues.

## command

flutter build ios --analyze-size --no-codesign

## exception

_TypeError: Null check operator used on a null value

#0      _ProgramInfoBuilder.createInfoNodeFor (package:vm_snapshot_analysis/v8_profile.dart:419:75)
#1      _ProgramInfoBuilder.getInfoNodeFor (package:vm_snapshot_analysis/v8_profile.dart:374:14)
#2      ListIterable.forEach (dart:_internal/iterable.dart:39:13)
#3      _ProgramInfoBuilder.build (package:vm_snapshot_analysis/v8_profile.dart:338:16)
#4      toProgramInfo (package:vm_snapshot_analysis/v8_profile.dart:282:8)
#5      _treemapFromSnapshot (package:vm_snapshot_analysis/treemap.dart:158:27)
#6      treemapFromJson (package:vm_snapshot_analysis/treemap.dart:85:5)
#7      SizeAnalyzer.analyzeAotSnapshot (package:flutter_tools/src/base/analyze_size.dart:61:59)
#8      _BuildIOSSubCommand.runCommand (package:flutter_tools/src/commands/build_ios.dart:699:62)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1297:27)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#11     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:339:9)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:285:5)
<asynchronous suspension>
#15     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:115:9)
<asynchronous suspension>
#16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#17     main (package:flutter_tools/executable.dart:90:3)
<asynchronous suspension>
```

## flutter doctor

```
[!] Flutter (Channel master, 3.12.0-12.0.pre.52, on macOS 13.4.1 22F82 darwin-arm64, locale en-GB)
    • Flutter version 3.12.0-12.0.pre.52 on channel master at /opt/flutter
    ! Warning: `dart` on your path resolves to /opt/homebrew/Cellar/dart/3.0.5/libexec/bin/dart, which is not inside your current Flutter
      SDK checkout at /opt/flutter. Consider adding /opt/flutter/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cd97b4391a (72 minutes ago), 2023-06-29 03:52:07 -0400
    • Engine revision eabb22900b
    • Dart version 3.1.0 (build 3.1.0-260.0.dev)
    • DevTools version 2.25.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update
      checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/konstantinrr/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] VS Code (version 1.79.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.66.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.4.1 22F82 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 114.0.5735.198

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

**Comment by sstrickl** [comment] 2023-07-04 10:58
Was OOO the end of last week, hence the delay, but taking a look at this now.

**Comment by sstrickl** [comment] 2023-07-04 11:11
So one thing I just noticed is that the new version of the package from fixing https://github.com/flutter/flutter/issues/128402 never got published to [pub.dev](https://pub.dev/packages/vm_snapshot_analysis) (it shows 0.7.2, but the in-tree package is version 0.7.4), so publishing it now.

I haven't checked whether Flutter is using the published or in-tree version, am doing so now and if the former, this should be resolved, else further debugging.

**Comment by sstrickl** [comment] 2023-07-04 11:18
Looks like `<flutter>/packages/flutter_tools/pubspec.yaml` specifically uses 0.7.2, so I'll create a PR to update it now that the new version is published.

**Comment by DaemonChoejur** [comment] 2023-07-24 12:00
`
## command

flutter build appbundle --target-platform android-arm64 --analyze-size

## exception

_TypeError: Null check operator used on a null value

```
#0      _ProgramInfoBuilder.createInfoNodeFor (package:vm_snapshot_analysis/v8_profile.dart:419:75)
#1      _ProgramInfoBuilder.getInfoNodeFor (package:vm_snapshot_analysis/v8_profile.dart:374:14)
#2      ListIterable.forEach (dart:_internal/iterable.dart:39:13)
#3      _ProgramInfoBuilder.build (package:vm_snapshot_analysis/v8_profile.dart:338:16)
#4      toProgramInfo (package:vm_snapshot_analysis/v8_profile.dart:282:8)
#5      _treemapFromSnapshot (package:vm_snapshot_analysis/treemap.dart:158:27)
#6      treemapFromJson (package:vm_snapshot_analysis/treemap.dart:85:5)
#7      SizeAnalyzer.analyzeZipSizeAndAotSnapshot (package:flutter_tools/src/base/analyze_size.dart:123:59)
#8      AndroidGradleBuilder._performCodeSizeAnalysis (package:flutter_tools/src/android/gradle.dart:567:60)
#9      AndroidGradleBuilder.buildGradleApp (package:flutter_tools/src/android/gradle.dart:508:15)
<asynchronous suspension>
#10     AndroidGradleBuilder.buildAab (package:flutter_tools/src/android/gradle.dart:228:5)
<asynchronous suspension>
#11     BuildAppBundleCommand.runCommand (package:flutter_tools/src/commands/build_appbundle.dart:153:5)
<asynchronous suspension>
#12     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1336:27)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#14     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#15     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:296:9)
<asynchronous suspension>
#16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#17     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:244:5)
<asynchronous suspension>
#18     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:91:9)
<asynchronous suspension>
#19     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#20     main (package:flutter_tools/executable.dart:91:3)
<asynchronous suspension>
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel stable, 3.10.6, on macOS 13.0.1 22A400 darwin-arm64, locale en-BT)
    [32m•[39m Flutter version 3.10.6 on channel stable at /Users/choejur/flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision f468f3366c (12 days ago), 2023-07-12 15:19:05 -0700
    [32m•[39m Engine revision cdbeda788a
    [32m•[39m Dart version 3.0.6
    [32m•[39m DevTools version 2.23.1

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    [32m•[39m Android SDK at /Users/choejur/Library/Android/sdk
    [32m•[39m Platform android-33, build-tools 30.0.3
    [32m•[39m ANDROID_HOME = /Users/choejur/Library/Android/sdk
    [32m•[39m Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Xcode - develop for iOS and macOS (Xcode 14.3)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Build 14E222b
    [32m•[39m CocoaPods version 1.12.1

[32m[✓][39m Android Studio (version 2022.1)
    [32m•[39m Android Studio at /Applications/Android Studio.app/Contents
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[32m[✓][39m VS Code (version 1.80.0)
    [32m•[39m VS Code at /Applications/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version 3.68.0

[32m[✓][39m VS Code (version 1.80.0)
    [32m•[39m VS Code at /Users/choejur/Downloads/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version 3.68.0

[32m[✓][39m Connected device (1 available)
    [32m•[39m macOS (desktop) • macos • darwin-arm64 • macOS 13.0.1 22A400 darwin-arm64

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[32m•[39m No issues found!
```
`

**Comment by mkustermann** [comment] 2023-07-24 12:25
@DaemonChoejur Could you try this on newest flutter master channel?

**Comment by ManuelFEMartinho** [comment] 2023-08-07 09:43
any news on this? I have the same

`Flutter crash report.
Please report a bug at https://github.com/flutter/flutter/issues.

## command

flutter build apk -t lib/main_dev.dart --flavor dev --dart-define-from-file=secret-config.json --analyze-size --target-platform=android-x64

## exception

_TypeError: Null check operator used on a null value

```
#0      _ProgramInfoBuilder.createInfoNodeFor (package:vm_snapshot_analysis/v8_profile.dart:419:75)
#1      _ProgramInfoBuilder.getInfoNodeFor (package:vm_snapshot_analysis/v8_profile.dart:374:14)
#2      ListIterable.forEach (dart:_internal/iterable.dart:39:13)
#3      _ProgramInfoBuilder.build (package:vm_snapshot_analysis/v8_profile.dart:338:16)
#4      toProgramInfo (package:vm_snapshot_analysis/v8_profile.dart:282:8)
#5      _treemapFromSnapshot (package:vm_snapshot_analysis/treemap.dart:158:27)
#6      treemapFromJson (package:vm_snapshot_analysis/treemap.dart:85:5)
#7      SizeAnalyzer.analyzeZipSizeAndAotSnapshot (package:flutter_tools/src/base/analyze_size.dart:123:59)
#8      AndroidGradleBuilder._performCodeSizeAnalysis (package:flutter_tools/src/android/gradle.dart:567:60)
#9      AndroidGradleBuilder.buildGradleApp (package:flutter_tools/src/android/gradle.dart:548:15)
<asynchronous suspension>
#10     AndroidGradleBuilder.buildApk (package:flutter_tools/src/android/gradle.dart:208:5)
<asynchronous suspension>
#11     BuildApkCommand.runCommand (package:flutter_tools/src/commands/build_apk.dart:116:5)
<asynchronous suspension>
#12     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1336:27)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#14     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#15     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:296:9)
<asynchronous suspension>
#16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#17     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:244:5)
<asynchronous suspension>
#18     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:91:9)
<asynchronous suspension>
#19     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#20     main (package:flutter_tools/executable.dart:91:3)
<asynchronous suspension>
```

## flutter doctor

```
[!] Flutter (Channel stable, 3.10.6, on macOS 13.1 22C65 darwin-x64, locale pt-PT)
    • Flutter version 3.10.6 on channel stable at /Users/manuelmartinho/Developer/3.10.6
    ! Warning: `flutter` on your path resolves to /Users/manuelmartinho/Developer/3.10.5/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/manuelmartinho/Developer/3.10.6. Consider adding /Users/manuelmartinho/Developer/3.10.6/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/manuelmartinho/Developer/3.10.5/bin/dart, which is not inside your current Flutter SDK checkout at /Users/manuelmartinho/Developer/3.10.6. Consider adding /Users/manuelmartinho/Developer/3.10.6/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (4 weeks ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/manuelmartinho/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.80.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.70.0

[✓] VS Code (version 1.68.1)
    • VS Code at /Users/manuelmartinho/Desktop/Visual Studio Code.app/Contents
    • Flutter extension version 3.70.0

[✓] Connected device (3 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • macOS (desktop)                    • macos         • darwin-x64     • macOS 13.1 22C65 darwin-x64
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 115.0.5790.170

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
`

Thanks

**Comment by mkustermann** [comment] 2023-08-17 11:01
@ManuelFEMartinho have you tried this on newest master or stable (3.13.0) channel?

**Comment by ManuelFEMartinho** [comment] 2023-08-17 13:24
Hi @mkustermann  I've just tried, and yes the problem persists

`Flutter crash report.
Please report a bug at https://github.com/flutter/flutter/issues.

## command

flutter build apk -t lib/main_dev.dart --flavor dev --dart-define-from-file=secret-config.json --analyze-size --target-platform=android-x64

## exception

_TypeError: Null check operator used on a null value

```
#0      _ProgramInfoBuilder.createInfoNodeFor (package:vm_snapshot_analysis/v8_profile.dart:419:75)
#1      _ProgramInfoBuilder.getInfoNodeFor (package:vm_snapshot_analysis/v8_profile.dart:374:14)
#2      ListIterable.forEach (dart:_internal/iterable.dart:39:13)
#3      _ProgramInfoBuilder.build (package:vm_snapshot_analysis/v8_profile.dart:338:16)
#4      toProgramInfo (package:vm_snapshot_analysis/v8_profile.dart:282:8)
#5      _treemapFromSnapshot (package:vm_snapshot_analysis/treemap.dart:158:27)
#6      treemapFromJson (package:vm_snapshot_analysis/treemap.dart:85:5)
#7      SizeAnalyzer.analyzeZipSizeAndAotSnapshot (package:flutter_tools/src/base/analyze_size.dart:123:59)
#8      AndroidGradleBuilder._performCodeSizeAnalysis (package:flutter_tools/src/android/gradle.dart:623:60)
#9      AndroidGradleBuilder.buildGradleApp (package:flutter_tools/src/android/gradle.dart:604:15)
<asynchronous suspension>
#10     AndroidGradleBuilder.buildApk (package:flutter_tools/src/android/gradle.dart:242:5)
<asynchronous suspension>
#11     BuildApkCommand.runCommand (package:flutter_tools/src/commands/build_apk.dart:116:5)
<asynchronous suspension>
#12     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1297:27)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#14     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#15     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:339:9)
<asynchronous suspension>
#16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#17     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:285:5)
<asynchronous suspension>
#18     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:115:9)
<asynchronous suspension>
#19     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#20     main (package:flutter_tools/executable.dart:90:3)
<asynchronous suspension>
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel stable, 3.13.0, on macOS 13.1 22C65 darwin-x64, locale pt-PT)
    [32m•[39m Flutter version 3.13.0 on channel stable at /Users/manuelmartinho/Developer/3.13.0
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision efbf63d9c6 (35 hours ago), 2023-08-15 21:05:06 -0500
    [32m•[39m Engine revision 1ac611c64e
    [32m•[39m Dart version 3.1.0
    [32m•[39m DevTools version 2.25.0

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    [32m•[39m Android SDK at /Users/manuelmartinho/Library/Android/sdk
    [32m•[39m Platform android-33, build-tools 33.0.0
    [32m•[39m Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Xcode - develop for iOS and macOS (Xcode 14.3)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Build 14E222b
    [32m•[39m CocoaPods version 1.11.3

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[32m[✓][39m Android Studio (version 2022.2)
    [32m•[39m Android Studio at /Applications/Android Studio.app/Contents
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[32m[✓][39m VS Code (version 1.81.1)
    [32m•[39m VS Code at /Applications/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version 3.70.0

[32m[✓][39m VS Code (version 1.68.1)
    [32m•[39m VS Code at /Users/manuelmartinho/Desktop/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version 3.70.0

[32m[✓][39m Connected device (4 available)
    [32m•[39m ASUS X00QD (mobile)          • J8AXB7630500CZ2 • android-arm64  • Android 9 (API 28)
    [32m•[39m sdk gphone64 x86 64 (mobile) • emulator-5554   • android-x64    • Android 13 (API 33) (emulator)
    [32m•[39m macOS (desktop)              • macos           • darwin-x64     • macOS 13.1 22C65 darwin-x64
    [32m•[39m Chrome (web)                 • chrome          • web-javascript • Google Chrome 115.0.5790.170

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[32m•[39m No issues found!
```
`

**Comment by mkustermann** [comment] 2023-08-17 14:10
@sstrickl could you investigate?

**Comment by sstrickl** [comment] 2023-08-29 14:19
Sorry, missed that there were two open bugs about this. Closing this as a duplicate of https://github.com/flutter/flutter/issues/132695, which has more information about what's going on here.

**Closed by sstrickl** 2023-08-29 14:19 UTC
Labels: c: crash, waiting for customer response, tool, platform-mac, dependency: dart, a: build, team-tool
