### ISSUE TITLE
Canvas: trying to draw too large(144000000bytes) bitmap on CarbonROM flashed phone

### ISSUE THREAD

**Issue by abalta** [flutter/flutter#52182] opened 2020-03-07 22:39 UTC
Hi, I am new to Flutter. Before I have developed many Android apps. My app crashes in some Android devices. All logs are here. I've tested in following devices.

OnePlust 7T: works
Samsung Galaxy A50: works
Emulator: works
Sony Xperia Z2: crashes. 

<details>
  <summary>Android Logcat</summary>

```
2020-03-08 01:28:32.227 15257-15257/com.mobiaxe.wasd E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.mobiaxe.wasd, PID: 15257
    java.lang.RuntimeException: Canvas: trying to draw too large(144000000bytes) bitmap.
        at android.view.DisplayListCanvas.throwIfCannotDraw(DisplayListCanvas.java:229)
        at android.view.RecordingCanvas.drawBitmap(RecordingCanvas.java:97)
        at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:529)
        at android.view.View.getDrawableRenderNode(View.java:19454)
        at android.view.View.drawBackground(View.java:19390)
        at android.view.View.draw(View.java:19187)
        at com.android.internal.policy.DecorView.draw(DecorView.java:788)
        at android.view.View.updateDisplayListIfDirty(View.java:18146)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:669)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:675)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:783)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:2992)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2806)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2359)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1392)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6752)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
        at android.view.Choreographer.doCallbacks(Choreographer.java:723)
        at android.view.Choreographer.doFrame(Choreographer.java:658)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6499)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```
</details>

<details>
  <summary>Flutter Verbose</summary

```
[  +16 ms] executing: [/home/abdullah/Flutter/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +21 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 0b8abb4724aa590dd0f429683339b1e045a1594d
[        ] executing: [/home/abdullah/Flutter/flutter/] git describe --match v*.*.* --first-parent --long --tags
[   +4 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.12.13+hotfix.8-0-g0b8abb472
[   +5 ms] executing: [/home/abdullah/Flutter/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +4 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/home/abdullah/Flutter/flutter/] git ls-remote --get-url origin
[   +4 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +33 ms] executing: [/home/abdullah/Flutter/flutter/] git rev-parse --abbrev-ref HEAD
[   +4 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +61 ms] executing: /home/abdullah/Android/Sdk/platform-tools/adb devices -l
[   +6 ms] Exit code 0 from: /home/abdullah/Android/Sdk/platform-tools/adb devices -l
[        ] List of devices attached
           BH905Q8517             device usb:3-10.1 product:D6503 model:Xperia_Z2 device:sirius transport_id:1
           emulator-5554          device product:sdk_gphone_x86 model:Android_SDK_built_for_x86 device:generic_x86 transport_id:2
[  +13 ms] /home/abdullah/Android/Sdk/platform-tools/adb -s BH905Q8517 shell getprop
[ +118 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +95 ms] Generating /home/abdullah/StudioProjects/wasd/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +17 ms] ro.hardware = qcom
[  +43 ms] Launching lib/main.dart on Xperia Z2 in debug mode...
[   +4 ms] executing: /home/abdullah/Android/Sdk/build-tools/29.0.2/aapt dump xmltree /home/abdullah/StudioProjects/wasd/build/app/outputs/apk/app.apk AndroidManifest.xml
[   +5 ms] Exit code 0 from: /home/abdullah/Android/Sdk/build-tools/29.0.2/aapt dump xmltree /home/abdullah/StudioProjects/wasd/build/app/outputs/apk/app.apk AndroidManifest.xml
[        ] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1c
               A: android:compileSdkVersionCodename(0x01010573)="9" (Raw: "9")
               A: package="com.mobiaxe.wasd" (Raw: "com.mobiaxe.wasd")
               A: platformBuildVersionCode=(type 0x10)0x1c
               A: platformBuildVersionName=(type 0x10)0x9
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1c
               E: uses-permission (line=14)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: application (line=22)
                 A: android:label(0x01010001)="wasd" (Raw: "wasd")
                 A: android:icon(0x01010002)=@0x7f080000
                 A: android:name(0x01010003)="io.flutter.app.FlutterApplication" (Raw: "io.flutter.app.FlutterApplication")
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A: android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComponentFactory" (Raw: "androidx.core.app.CoreComponentFactory")
                 E: activity (line=28)
                   A: android:theme(0x01010000)=@0x7f0a0000
                   A: android:name(0x01010003)="com.mobiaxe.wasd.MainActivity" (Raw: "com.mobiaxe.wasd.MainActivity")
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x40003fb4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: intent-filter (line=35)
                     E: action (line=36)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
                     E: category (line=38)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw: "android.intent.category.LAUNCHER")
                 E: meta-data (line=45)
                   A: android:name(0x01010003)="flutterEmbedding" (Raw: "flutterEmbedding")
                   A: android:value(0x01010024)=(type 0x10)0x2
[   +4 ms] executing: /home/abdullah/Android/Sdk/platform-tools/adb -s BH905Q8517 shell -x logcat -v time -t 1
[  +51 ms] Exit code 0 from: /home/abdullah/Android/Sdk/platform-tools/adb -s BH905Q8517 shell -x logcat -v time -t 1
[        ] --------- beginning of main
           03-08 01:28:27.541 W/logcat  (15034): type=1400 audit(0.0:2682): avc: denied { getattr } for path="/system/vendor/bin/suntrold" dev="mmcblk0p23" ino=2363 scontext=u:r:shell:s0 tcontext=u:object_r:suntrold_exec:s0 tclass=file permissive=0
[   +8 ms] executing: /home/abdullah/Android/Sdk/platform-tools/adb version
[        ] executing: /home/abdullah/Android/Sdk/platform-tools/adb -s BH905Q8517 logcat -v time -T 03-08 01:28:27.541
[  +16 ms] Android Debug Bridge version 1.0.41
           Version 29.0.6-6198805
           Installed as /home/abdullah/Android/Sdk/platform-tools/adb
[   +1 ms] executing: /home/abdullah/Android/Sdk/platform-tools/adb start-server
[  +13 ms] Building APK
Running Gradle task 'assembleDebug'...
[  +13 ms] gradle.properties already sets `android.enableR8`
[   +1 ms] Using gradle from /home/abdullah/StudioProjects/wasd/android/gradlew.
[   +4 ms] executing: /home/abdullah/android-studio/jre/bin/java -version
[  +44 ms] Exit code 0 from: /home/abdullah/android-studio/jre/bin/java -version
[        ] openjdk version "1.8.0_212-release"
           OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
           OpenJDK 64-Bit Server VM (build 25.212-b4-5784211, mixed mode)
[   +2 ms] executing: [/home/abdullah/StudioProjects/wasd/android/] /home/abdullah/StudioProjects/wasd/android/gradlew -q -Ptarget=/home/abdullah/StudioProjects/wasd/lib/main.dart -Ptrack-widget-creation=true -Pfilesystem-scheme=org-dartlang-root -Ptarget-platform=android-arm assembleDebug
[+1242 ms] calculateSha: LocalDirectory: '/home/abdullah/StudioProjects/wasd/build/app/outputs/apk'/app.apk
[  +41 ms] calculateSha: reading file took 39us
[ +478 ms] calculateSha: computing sha took 478us
[   +2 ms] ✓ Built build/app/outputs/apk/debug/app-debug.apk.
[   +2 ms] executing: /home/abdullah/Android/Sdk/build-tools/29.0.2/aapt dump xmltree /home/abdullah/StudioProjects/wasd/build/app/outputs/apk/app.apk AndroidManifest.xml
[   +7 ms] Exit code 0 from: /home/abdullah/Android/Sdk/build-tools/29.0.2/aapt dump xmltree /home/abdullah/StudioProjects/wasd/build/app/outputs/apk/app.apk AndroidManifest.xml
[        ] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1c
               A: android:compileSdkVersionCodename(0x01010573)="9" (Raw: "9")
               A: package="com.mobiaxe.wasd" (Raw: "com.mobiaxe.wasd")
               A: platformBuildVersionCode=(type 0x10)0x1c
               A: platformBuildVersionName=(type 0x10)0x9
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1c
               E: uses-permission (line=14)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: application (line=22)
                 A: android:label(0x01010001)="wasd" (Raw: "wasd")
                 A: android:icon(0x01010002)=@0x7f080000
                 A: android:name(0x01010003)="io.flutter.app.FlutterApplication" (Raw: "io.flutter.app.FlutterApplication")
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A: android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComponentFactory" (Raw: "androidx.core.app.CoreComponentFactory")
                 E: activity (line=28)
                   A: android:theme(0x01010000)=@0x7f0a0000
                   A: android:name(0x01010003)="com.mobiaxe.wasd.MainActivity" (Raw: "com.mobiaxe.wasd.MainActivity")
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x40003fb4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: intent-filter (line=35)
                     E: action (line=36)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
                     E: category (line=38)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw: "android.intent.category.LAUNCHER")
                 E: meta-data (line=45)
                   A: android:name(0x01010003)="flutterEmbedding" (Raw: "flutterEmbedding")
                   A: android:value(0x01010024)=(type 0x10)0x2
[        ] Stopping app 'app.apk' on Xperia Z2.
[        ] executing: /home/abdullah/Android/Sdk/platform-tools/adb -s BH905Q8517 shell am force-stop com.mobiaxe.wasd
[ +164 ms] executing: /home/abdullah/Android/Sdk/platform-tools/adb -s BH905Q8517 shell pm list packages com.mobiaxe.wasd
[ +846 ms] package:com.mobiaxe.wasd.debug
           package:com.mobiaxe.wasd
[   +2 ms] executing: /home/abdullah/Android/Sdk/platform-tools/adb -s BH905Q8517 shell cat /data/local/tmp/sky.com.mobiaxe.wasd.sha1
[  +55 ms] 16f25f79264a96e44800d87f76d70f40cdca2153
[        ] Latest build already installed.
[        ] Xperia Z2 startApp
[   +1 ms] executing: /home/abdullah/Android/Sdk/platform-tools/adb -s BH905Q8517 shell am start -a android.intent.action.RUN -f 0x20000000 --ez enable-background-compilation true --ez enable-dart-profiling true --ez enable-checked-mode true --ez verify-entry-points true com.mobiaxe.wasd/com.mobiaxe.wasd.MainActivity
[ +102 ms] Starting: Intent { act=android.intent.action.RUN flg=0x20000000 cmp=com.mobiaxe.wasd/.MainActivity (has extras) }
[        ] Waiting for observatory port to be available...
[ +228 ms] D/FlutterActivity(15257): Using the launch theme as normal theme.
[   +3 ms] D/FlutterActivityAndFragmentDelegate(15257): Setting up FlutterEngine.
[        ] D/FlutterActivityAndFragmentDelegate(15257): No preferred FlutterEngine was provided. Creating a new FlutterEngine for this FlutterFragment.
[ +230 ms] D/FlutterActivityAndFragmentDelegate(15257): Attaching FlutterEngine to the Activity that owns this Fragment.
[ +459 ms] Observatory URL on device: http://127.0.0.1:59357/H6q4IHLSQLg=/
[   +3 ms] executing: /home/abdullah/Android/Sdk/platform-tools/adb -s BH905Q8517 forward tcp:0 tcp:59357
[  +12 ms] 38403
[        ] Forwarded host port 38403 to device port 59357 for Observatory
[   +6 ms] Connecting to service protocol: http://127.0.0.1:38403/H6q4IHLSQLg=/
[ +139 ms] D/FlutterView(15257): Attaching to a FlutterEngine: io.flutter.embedding.engine.FlutterEngine@cc181eb
[  +47 ms] D/FlutterActivityAndFragmentDelegate(15257): Executing Dart entrypoint: main, and sending initial route: /
[ +444 ms] Successfully connected to service protocol: http://127.0.0.1:38403/H6q4IHLSQLg=/
[   +2 ms] Sending to VM service: getVM({})
[   +7 ms] Result: {type: VM, name: vm, architectureBits: 32, hostCPU: Qualcomm MSM8974PRO-AB, operatingSystem: android, targetCPU: arm, version: 2.7.0 (Fri Dec 6 16:26:51 2019 +0100) on "android_arm", _profilerMode: VM, _nativeZoneMemoryUsage: 0, pid: 15257, startT...
[   +3 ms] Sending to VM service: getIsolate({isolateId: isolates/3983678871753151})
[   +2 ms] Sending to VM service: _flutter.listViews({})
[  +69 ms] Result: {type: FlutterViewList, views: [{type: FlutterView, id: _flutterView/0x9b1c9890, isolate: {type: @Isolate, fixedId: true, id: isolates/3983678871753151, name: main.dart$main-3983678871753151, number: 3983678871753151}}]}
[   +7 ms] DevFS: Creating new filesystem on the device (null)
[        ] Sending to VM service: _createDevFS({fsName: wasd})
[  +14 ms] Result: {type: Isolate, id: isolates/3983678871753151, name: main, number: 3983678871753151, _originNumber: 3983678871753151, startTime: 1583620110955, _heaps: {new: {type: HeapSpace, name: new, vmName: Scavenger, collections: 1, avgCollectionPeriodMillis...
[  +80 ms] Result: {type: FileSystem, name: wasd, uri: file:///data/user/0/com.mobiaxe.wasd/code_cache/wasdLJJDTQ/wasd/}
[        ] DevFS: Created new filesystem on the device (file:///data/user/0/com.mobiaxe.wasd/code_cache/wasdLJJDTQ/wasd/)
[   +3 ms] Updating assets
Debug service listening on ws://127.0.0.1:38403/H6q4IHLSQLg=/ws
Syncing files to device Xperia Z2...
[  +65 ms] Scanning asset files
[   +1 ms] <- reset
[        ] Compiling dart to kernel with 0 updated files
[   +5 ms] /home/abdullah/Flutter/flutter/bin/cache/dart-sdk/bin/dart /home/abdullah/Flutter/flutter/bin/cache/artifacts/engine/linux-x64/frontend_server.dart.snapshot --sdk-root /home/abdullah/Flutter/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --incremental --target=flutter -Ddart.developer.causal_async_stacks=true --output-dill /tmp/flutter_tool.UIFTVW/app.dill --packages /home/abdullah/StudioProjects/wasd/.packages -Ddart.vm.profile=false -Ddart.vm.product=false --bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions --enable-asserts --track-widget-creation
[   +8 ms] <- compile package:wasd/main.dart
[ +544 ms] D/vndksupport(15257): Loading /vendor/lib/hw/android.hardware.graphics.mapper@2.0-impl.so from current namespace instead of sphal namespace.
[        ] D/vndksupport(15257): Loading /vendor/lib/hw/gralloc.msm8974.so from current namespace instead of sphal namespace.
```
</details>

<details>
  <summary>Flutter Doctor</summary

```
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Linux, locale en_US.UTF-8)
    • Flutter version 1.12.13+hotfix.8 at /home/abdullah/Flutter/flutter
    • Framework revision 0b8abb4724 (4 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/abdullah/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /home/abdullah/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Android Studio (version 3.6)
    • Android Studio at /home/abdullah/android-studio
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] Connected device (2 available)
    • Xperia Z2                 • BH905Q8517    • android-arm • Android 8.1.0
      (API 27)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API
      29) (emulator)

• No issues found!

```

</details>

<details>
  <summary>main.dart</summary>

```
import 'package:flutter/material.dart';
import 'package:wasd/onboarding.dart';
import 'strings.dart';

void main() => runApp(WASD());

class WASD extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: Strings.appTitle,
      theme: ThemeData(
        primaryColor: Colors.white
      ),
      initialRoute: Strings.navOnboarding,
      routes: {
        Strings.navOnboarding: (context) => Onboarding()
      },
    );
  }
}

```
</details>

<details>
  <summary>onboarding.dart</summary>

```
import 'package:flutter/material.dart';
import 'package:wasd/select_platform.dart';
import 'strings.dart';

class Onboarding extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return PageView(
      children: <Widget>[
        PagerPage(path: Strings.pathWitcherJpg, title: Strings.titlePageOne, description: Strings.subtitlePageOne),
        PagerPage(path: Strings.pathGodofwarJpg, title: Strings.titlePageTwo, description: Strings.subtitlePageTwo),
        PagerPage(path: Strings.pathRdrJpg, title: Strings.titlePageThree, description: Strings.subtitlePageThree),
        SelectPlatform()
      ],
    );
  }
}

class PagerPage extends StatelessWidget {
  final String path;
  final String title;
  final String description;

  PagerPage({Key key, this.path, this.title, this.description})
      : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Stack(
      children: <Widget>[
        Image.asset(
          path,
          height: MediaQuery.of(context).size.height,
          width: MediaQuery.of(context).size.width,
          fit: BoxFit.fill,
        ),
        Container(
          alignment: Alignment.bottomCenter,
          padding: EdgeInsets.only(bottom: 120.0),
          child: Column(
            mainAxisAlignment: MainAxisAlignment.end,
            crossAxisAlignment: CrossAxisAlignment.center,
            children: <Widget>[
              Padding(
                  child: Text(
                    title,
                    style: TextStyle(
                        color: Colors.white,
                        fontSize: 34.0,
                        decoration: TextDecoration.none),
                  ),
                  padding: EdgeInsets.only(bottom: 32.0)),
              Text(
                  description,
                  textAlign: TextAlign.center,
                  style: TextStyle(
                      color: Colors.white,
                      fontSize: 20.0,
                      decoration: TextDecoration.none)),
            ],
          ),
        )
      ],
    );
  }
}

```
</details>

This sample image is used in app.

https://i.imgur.com/n9qBj7S.jpg

**Comment by dnfield** [comment] 2020-03-09 05:33
Could you please share some sample code that reproduces this issue?

Are you just trying to render an image that's too large?  Or have you created some non-raster-image widget that is leading to this?

**Comment by dnfield** [comment] 2020-03-09 05:34
Right now, it's not clear if your app is just trying to do something it shouldn't (e.g. render a really high resolution image at full resolution), or if you've found an issue with Flutter.

**Comment by abalta** [comment] 2020-03-09 09:20
> Could you please share some sample code that reproduces this issue?
> 
> Are you just trying to render an image that's too large? Or have you created some non-raster-image widget that is leading to this?

Hi @dnfield, I updated my issue.

**Comment by TahaTesser** [comment] 2020-03-09 12:47
Tested this code sample, reproduce no issue. Could be device specific 


<details>
 <summary>Code Sample</summary>

```
import 'package:flutter/material.dart';

void main() => runApp(WASD());

class WASD extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(primaryColor: Colors.white),
      home: Onboarding(),
    );
  }
}

class Onboarding extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return PageView(
      children: <Widget>[
        PagerPage(
            path: 'https://i.imgur.com/n9qBj7S.jpg',
            title: 'Page one',
            description: 'Subtitle PageOne'),
        PagerPage(
            path: 'https://i.imgur.com/n9qBj7S.jpg',
            title: 'Page Two',
            description: 'Subtitle PageTwo'),
        PagerPage(
            path: 'https://i.imgur.com/n9qBj7S.jpg',
            title: 'Page Three',
            description: 'Subtitle PageThree'),
      ],
    );
  }
}

class PagerPage extends StatelessWidget {
  final String path;
  final String title;
  final String description;

  PagerPage({Key key, this.path, this.title, this.description})
      : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Stack(
      children: <Widget>[
        Image.network(
          path,
          height: MediaQuery.of(context).size.height,
          width: MediaQuery.of(context).size.width,
          fit: BoxFit.fill,
        ),
        Container(
          alignment: Alignment.bottomCenter,
          padding: EdgeInsets.only(bottom: 120.0),
          child: Column(
            mainAxisAlignment: MainAxisAlignment.end,
            crossAxisAlignment: CrossAxisAlignment.center,
            children: <Widget>[
              Padding(
                  child: Text(
                    title,
                    style: TextStyle(
                        color: Colors.white,
                        fontSize: 34.0,
                        decoration: TextDecoration.none),
                  ),
                  padding: EdgeInsets.only(bottom: 32.0)),
              Text(description,
                  textAlign: TextAlign.center,
                  style: TextStyle(
                      color: Colors.white,
                      fontSize: 20.0,
                      decoration: TextDecoration.none)),
            ],
          ),
        )
      ],
    );
  }
}
```

</details>


<details>
 <summary>Screenshot</summary>

![Screenshot_1583758000](https://user-images.githubusercontent.com/48603081/76214154-2a8d1f80-6232-11ea-9625-895b85edb941.png)


</details>

**Comment by abalta** [comment] 2020-03-09 13:15
> Tested this code sample, reproduce no issue. Could be device specific
> Code Sample
> Screenshot

You seem to use network image. I used this image from my assets. Please download image to assets folder and use from there.

**Comment by TahaTesser** [comment] 2020-03-09 13:20
Hi @abalta 
I have tested with asset image too found no issue in issue in emulator to confirm, this could be device specific issue and added network image for easy testing for others . 
Thank you

**Comment by dnfield** [comment] 2020-03-09 13:35
The compilation paths are different for simulator and real device.

**Comment by dnfield** [comment] 2020-03-09 13:53
You're missing Strings.dart and select_platform.dart.

**Comment by dnfield** [comment] 2020-03-09 13:58
If you run `flutter clean` and try again does the problem go away? 

Does it reproduce in a fresh project?

**Comment by abalta** [comment] 2020-03-09 14:15
> You're missing Strings.dart and select_platform.dart.

Hi, @dnfield here are string.dart and selectplatform.dart files.

<details>
  <summary>strings.dart</summary>

```
class Strings {

  static String appTitle = "WASD";

  //routes
  static String navOnboarding = '/onboarding';

  //assets path
  //jpgs
  static String pathWitcherJpg = 'assets/witcher_bg.jpg';
  static String pathGodofwarJpg = 'assets/godofwar_bg.jpg';
  static String pathRdrJpg = 'assets/rdr_bg.jpg';
  static String pathSelectPlatformBgJpg = 'assets/platform_bg.jpg';

  //svgs
  static String pathWindowsSvg = 'assets/ic_windows.svg';
  static String pathPS4Svg = 'assets/ic_ps4.svg';
  static String pathXboxSvg = 'assets/ic_xbox.svg';
  static String pathNintendoSvg = 'assets/ic_nintendo.svg';

  //onboarding
  static String titlePageOne = 'Keşfet';
  static String subtitlePageOne = 'Popüler oyunları keşfet\nÇıkacak oyunları takip et';
  static String titlePageTwo = 'Oyna';
  static String subtitlePageTwo = 'Oynadığın oyunları listene ekle\nYorum yap, beğen';
  static String titlePageThree = 'Oyuncu Ol';
  static String subtitlePageThree = 'Casual, Pro, Hardcore sen hangi oyuncusun?';

  //select platform
  static String selectYourPlatform = 'Platformunu Seç';
  static String pc = 'PC';
  static String playStation = 'Play Station';
  static String xbox = 'Xbox';
  static String nintendo = 'Nintendo';
}
```
</details>

<details>
  <summary>select_platform.dart</summary>

```
import 'package:flutter/material.dart';
import 'package:flutter_svg/flutter_svg.dart';

import 'strings.dart';

class SelectPlatform extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Stack(
      children: <Widget>[
        Image.asset(
          Strings.pathSelectPlatformBgJpg,
          height: MediaQuery.of(context).size.height,
          width: MediaQuery.of(context).size.width,
          fit: BoxFit.cover,
        ),
        Container(
          alignment: Alignment.topCenter,
          padding: EdgeInsets.all(16.0),
          child: Column(
            children: <Widget>[
              Padding(
                padding: const EdgeInsets.only(top: 64.0),
                child: Text(Strings.selectYourPlatform,
                    style: TextStyle(
                        color: Colors.white,
                        fontSize: 34.0,
                        decoration: TextDecoration.none)),
              ),
              Padding(
                padding: const EdgeInsets.only(top: 32.0),
                child: Row(
                  mainAxisAlignment: MainAxisAlignment.spaceEvenly,
                  children: <Widget>[
                    Platform(Strings.pc, Strings.pathWindowsSvg),
                    Platform(Strings.playStation, Strings.pathPS4Svg)
                  ],
                ),
              ),
              Row(
                mainAxisAlignment: MainAxisAlignment.spaceEvenly,
                children: <Widget>[
                  Platform(Strings.xbox, Strings.pathXboxSvg),
                  Platform(Strings.nintendo, Strings.pathNintendoSvg)
                ],
              )
            ],
          ),
        )
      ],
    );
  }
}

class Platform extends StatefulWidget {
  final String label;
  final String asset;

  Platform(this.label, this.asset);

  @override
  PlatformState createState() => PlatformState(label, asset);
}

class PlatformState extends State<Platform> {
  bool isSelected = false;
  String label;
  String asset;

  PlatformState(this.label, this.asset);

  @override
  Widget build(BuildContext context) {
    return _buildFlexibleCard(label, asset, isSelected);
  }

  Flexible _buildFlexibleCard(String label, String asset, bool isSelected) {
    return Flexible(
        flex: 1,
        fit: FlexFit.tight,
        child: Padding(
          padding: const EdgeInsets.all(8.0),
          child: GestureDetector(
            onTap: () {
              _selectPlatform();
            },
            child: Container(
              padding: const EdgeInsets.all(16.0),
              decoration: BoxDecoration(
                  borderRadius: BorderRadius.all(Radius.circular(8.0)),
                  color: Color(0x99222d45)),
              child: Stack(
                children: <Widget>[
                  Center(
                    child: Column(
                      children: <Widget>[
                        SvgPicture.asset(asset, width: 64, height: 64),
                        Padding(
                          padding: const EdgeInsets.only(top: 8.0),
                          child: Text(label,
                              style: TextStyle(
                                  color: Colors.white,
                                  fontSize: 16.0,
                                  decoration: TextDecoration.none)),
                        )
                      ],
                    ),
                  ),
                  Visibility(
                      visible: isSelected,
                      child: Positioned(
                          top: 0,
                          right: 0,
                          child: SvgPicture.asset('assets/ic_tick.svg',
                              width: 24, height: 24, color: Colors.white)))
                ],
              ),
            ),
          ),
        ));
  }

  void _selectPlatform() {
    setState(() {
      isSelected = !isSelected;
    });
  }
}

```

</details>

**Comment by abalta** [comment] 2020-03-09 14:23
> Hi @abalta
> I have tested with asset image too, found no issue in issue in emulator to confirm, this could be device specific issue and added network image for easy testing for others .
> Thank you

Maybe, because this device (Sony Xperia Z2) is rooted with custom rom. (https://get.carbonrom.org/device-sirius.html)

**Comment by dnfield** [comment] 2020-03-09 17:52
@abalta is the ROM you're running certified for use with the PlayStore?  If not, that could very well be why this is crashing, and I don't think we'll be able to fix this issue.

**Comment by dnfield** [comment] 2020-03-09 17:57
Looking into this a bit more - CarbonROM does not appear to be certified with the PlayStore, we do not have any devices to test with this ROM, and it's not clear whether this is a bug in CarbonROM or the engine.

Given that your app seems to be working fine on stock Android, I'm moving this over tot he `Future` milestone.  I don't expect anyone will be actively working on this, unless they're also encountering this issue on a CarbonROM flashed phone.  I am not aware of any active team members who do have access to such a device right now.

**Comment by abalta-mobven** [comment] 2020-03-09 19:07
> Looking into this a bit more - CarbonROM does not appear to be certified with the PlayStore, we do not have any devices to test with this ROM, and it's not clear whether this is a bug in CarbonROM or the engine.
> 
> Given that your app seems to be working fine on stock Android, I'm moving this over tot he `Future` milestone. I don't expect anyone will be actively working on this, unless they're also encountering this issue on a CarbonROM flashed phone. I am not aware of any active team members who do have access to such a device right now.

Thanks @dnfield and @TahaTesser. İt is good to be fine on future milestone. Maybe, future releases of CarbonRom fixed this kind of issues.

**Comment by abalta-mobven** [comment] 2020-03-09 21:26
I created new flutter default project from curiosity and then run CarbonRom flashed device, it works. Then, I remove all images on my project to run again it still crashes. I think, something else caused crashes instead of images.

**Comment by dnfield** [comment] 2020-03-09 21:55
Right - your whole stack trace is in Java code, and it is not Java code from Flutter.

**Comment by darshankawar** [comment] 2024-07-04 10:25
> Sony Xperia Z2: crashes.

This specific device model and make seems to be discontinued per https://www.gsmarena.com/sony_xperia_z2-6144.php
Also, considering the age of this issue and no activity since the last comment that was 4 years ago, I will consider this issue now as obsolete and will close as stale.
If anybody still sees the same crash using latest stable version on similar device make and model, file a new issue with relevant details.

**Closed by darshankawar** 2024-07-04 10:25 UTC
Labels: c: crash, e: device-specific, platform-android, engine, c: performance, perf: memory, P3, team-android, triaged-android
