### ISSUE TITLE
_CastError: Null check operator used on a null value

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [flutter/flutter#82423] opened 2021-05-13 07:17 UTC
I am on latest flutter and flutter doctor has no issues.

Can you guys help me to understand why i get this error: 
```
_CastError: Null check operator used on a null value
  File "auth_service.dart", line 149, in AuthService.handleSignedInUserRedirect
  File "startup_page_model.dart", line 38, in StartUpPageModel.onStartup
```

code base is:

```
class StartUpPageModel {
  final _authService = GetIt.instance<AuthService>();

  onStartup() async {
    try {
      ....

    _authService.handleSignedInUserRedirect();
  }
}

```

_authService cannot be nul because it is injected. Also i cannot reproduce it localy i see this exception only in my live app logs.

**Comment by TahaTesser** [comment] 2021-05-13 09:13
Hi @vytautas-pranskunas- 
From what I can see, the issue is related to a 3rd party plugin `get_it` rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/fluttercommunity/get_it/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`, a minimal reproducible code sample that does not use 3rd party plugins, your complete `flutter run -v` logs running the minimal code sample 
and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-05-13 09:13 UTC
Labels: in triage
