### ISSUE TITLE
removing Image widgets does not reduce Graphics memory allocation

### ISSUE THREAD

**Issue by pcsosinski** [flutter/flutter#56482] opened 2020-05-06 21:33 UTC
Internal: b/157467549

If the app was put to background and then resumed, the GPU memory went back down.

not sure what the right approach for this. Changing the widget tree and not seeing an expected memory behavior is hard to explain. Is this a bug? Is it something that should be in documentation?

/cc @cbracken @mehmetf

**Comment by liyuqian** [comment] 2020-05-08 20:24
This issue looks similar to https://github.com/flutter/flutter/issues/19558. The next steps of fixing this would also be similar:
1. Put the code of a minimal reproduction app here so we can manually reproduce the issue
2. Turn that minimal reproduction to a memory perf test similar to "Memory test on scrolling large images quickly #46033"
3. Once we can use the perf test to consistently and quickly reproduce and debug this issue, I'm confident that we'll come up with a fix like "Cleanup the IO thread GrContext #14265" soon.

**Comment by chinmaygarde** [comment] 2020-05-08 22:00
@liyuqian Isn't this WAI? Even if the images are not referenced in the widget tree, they may be referenced in the image cache in the framework. Putting the application in the background clears the cache. If the application released all ui.Image references and we did not observe a GPU memory decrease, then that would be a problem. That would be the more accurate perf test.

**Comment by mehmetf** [comment] 2020-05-09 00:07
Totally fine to close this as WAI but it is surprising from developer's point of view so we might want to think about how to expose this in tooling to guide them.

Image cache gets repeated many times in these conversations; perhaps it deserves its own metrics in the memory section of DevTools @terrylucas

**Comment by liyuqian** [comment] 2020-05-09 00:25
@chinmaygarde : if it's image cache that's retaining those images, and there's a way for developers to clear those image cache, then this is totally WAI. A reproduction app would clarify whether it's image cache WAI or some unexpected issues.

**Comment by chinmaygarde** [comment] 2020-05-09 01:16
> and there's a way for developers to clear those image cache

There are definitely ways to [manage the images in the cache and its limits](https://api.flutter.dev/flutter/painting/ImageCache-class.html).

> but it is surprising from developer's point of view so we might want to think about how to expose this in tooling to guide them.

This is true. Also, accessing the image caches can be implicit so users may not even be aware that this is whats going on. Also, the image caches are simple LRU caches with arbitrary limits that have no bearing on actual device capabilities. So it is totally possible for users to unknowingly use the image cache all the way to device memory exhaustion. From the engine's perspective, these caches are particularly frustrating because the references to the images in this cache are strong and there aren't too many opportunities to optimize textures in this cache. For example, if the images were to be speculatively evicted from device memory, rendering them again would lead to a massive increase in frame time because the host to device transfer would need to be carried out again. Also, making these images evictable from device memory means that the engine would need to maintain a host side copy of the allocation which would sharply increase heap memory usage. ui.Images were meant to be references to images that are extremely fast to render by referencing them in the widget tree. But they are also expensive in device memory. However, image caches keeps these references around for quite periods well beyond their intended use. In the past, we have done a lot of work in the engine to make it so that allocating and collecting these images is as fast/performant as possible. But till the application/framework holds a strong reference to these images, the issue of device memory usage will keep coming up. If a long term solution to the frequent discussions surrounding device memory usage of image caches is to be devised, it probably involves an alternative to image caches that maintains image references more closely tied to their use in widgets hierarchies. Till then, exposing the cost of images in the cache from tooling seems like a good idea.

To answer the question: "removing Image widgets does not reduce Graphics memory allocation, why?", The TL;DR is widgets don't own the Graphics (GPU/Device) memory allocations for the images they display, strong references to ui.Images do. So not using a widget does not imply that the graphics memory will get collected.

> A reproduction app would clarify whether it's image cache WAI or some unexpected issues.

Yes, this issue currently seems like asking a question instead of raising an issue. Lets prepare a reproduction case to ensure we aren't talking about a construction issue.

**Comment by liyuqian** [comment] 2020-05-13 18:54
@mehmetf : can you or the gPay team please provide us a reproduction case so we can figure out if it's WAI or an issue of ours?

**Comment by mehmetf** [comment] 2020-05-13 23:26
Download a large PNG to your application assets and name it `very_large.png`. Then run the following code:

```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  @override
  void initState() {
    imageCache.maximumSize = 0;
    super.initState();
  }

  void _incrementCounter() {
    if (_counter == 10) {
      imageCache.clear();
    }
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Column(
        mainAxisSize: MainAxisSize.max,
        children: [
          Text('Images will go here $_counter'),
          if (_counter > 2 && _counter <= 5)
            Image.asset('assets/very_large.png'),
        ],
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        child: Icon(Icons.ac_unit),
      ),
    );
  }
}
```

I tried to set the image cache size to 0 and also clear it when the counter hits 10 but none of that helped get the graphics size back down to "normal" levels. In my experiment, before the image is shown graphics memory reported by adb is 55M. After image is shown it is 178M and it stays there no matter what.

In fact, I misspoke earlier. After I put it the app to background and foreground again, the graphics memory goes down but not to initial levels. It stays at 140M.

**Comment by dnfield** [comment] 2020-05-18 22:27
I'm going to take a quick look at this - I have a couple ideas about things to try here.

**Comment by dnfield** [comment] 2020-05-18 23:46
Something strange here. The image cache is not holding a reference to this image for sure - it's not holding anything. Something is though. Trying to figure out what.

**Comment by dnfield** [comment] 2020-05-18 23:56
By something is, I mean the Dart VM still seems to believe it's live, even though it seems like it shouldn't be.

**Comment by dnfield** [comment] 2020-05-19 15:24
With an `Image.asset`, it does _eventually_ get GC'd once the counter increments high enough. The issue is not with image caching. I'm seeing `Image.network` get retained and not GC'd, filed separate bug for that.

I'd like to think it would get GC'd more quickly due to the size of the image I was working with (it was taking close to 200mb of memory by itself). It was taking several seconds and many many frames after it was gone before getting GC'd.  I'm not sure if that's just WAI or if that's reasonable behavior.

/cc @jason-simmons who was also looking at this

**Comment by chinmaygarde** [comment] 2020-05-19 20:45
Can you capture and attach a heap dump from the observatory for analysis here?

**Comment by dnfield** [comment] 2020-05-19 22:23
@chinmaygarde - it's not showing up in the heap snapshots, but is showing up in the old generation of the allocation profile. Here are the CSV dumps. One from app startup, (1) after the image loads, (2) after the image has been disposed by the framework but you can still see the native memory in the old generation, and (3) after I press the button 20 or 30 more times which eventually triggers a GC and the old gen is cleaned up.

Again, the main concern is that native memory is remaining resident for too long. In a real application, if I had to show that large image and then got rid of it, I need to be able to show more large images again without potentially OOMing in between because Dart has failed to GC the unreferenced memory.

[heap_profiles.zip](https://github.com/flutter/flutter/files/4653565/heap_profiles.zip)

**Comment by dnfield** [comment] 2020-05-20 00:02
And in case it's not clear, the memory showing in the old generation is also visible in Xcode - e.g. the SkImage_lazy and its backing texture are still around in memory until the GC finally grabs it.

**Comment by chinmaygarde** [comment] 2020-05-20 02:33
> With an `Image.asset`, it does eventually get GC'd ... . I'm seeing `Image.network` get retained 

Did you also disable the image cache (not sure if you are using Mehmets reduced test case)? I forget which variants consult the cache.

> And in case it's not clear, the memory showing in the old generation is also visible in Xcode.

That is to be expected. As long as there is a reference to the object in the Dart VM (even if that is a garbage reference the collector hasn't bothered collecting yet), the engine cannot collect the texture from graphics memory.

> eventually triggers a GC and the old gen is cleaned up.

Ok, this is good. It means that when a reference is finally collected, all native allocations including ones resident in graphics memory are collected.

> I need to be able to show more large images again without potentially OOMing in between because Dart has failed to GC the unreferenced memory.

Have you actually seen this happening? Before growing the old space, the VM will attempt to release garbage references. Attempting to allocate more large objects will ensure that the old garbage references are released first. Can you setup an example where one large image is loaded after another (make sure the old one is actually collectable otherwise you'll just run out of memory)?

> Again, the main concern is that native memory is remaining resident for too long.

Without manual memory management, you are never going to be in complete control of when something gets collected. Some things you can try though:
* `Shell::NotifyLowMemoryWarning` should perform more aggressive collection of unused references (in the VM and otherwise). Maybe call that before going into the background.
* We could add a new method to image (say `dispose`) that the framework can call manually that makes the engine pre-emptively get rid of the texture allocation and not wait for the garbage collector to finally come along and collect the reference. So semi-manual memory management for textures.
* Actually kill the Dart VM when going into the background. You'll incur the cost of restarting the VM when you get back which is not fast (thats why we had to add the the `Settings::leak_vm` flag).



Only the second suggestion will help when not going into the background. But then again, the collector taking a while to actually collect references seems like expected behavior.

After attempting that a reduced test case where very large images are loaded, displayed and unloaded one after another runs fine, I think we can safe say that the answer to the question "removing Image widgets does not reduce Graphics memory allocation, why?" is that the image is actually referenced in a cache or is awaiting collection by the GC, and, no actual bug has been identified.

**Comment by dnfield** [comment] 2020-05-20 05:33
In the demo app, the image cache is definitely disabled.

The ui.Image has a dispose method, that does this:

https://github.com/flutter/engine/blob/d0b69d076560ba0be6a828bf37fc9ba93722a75e/lib/ui/painting/image.cc#L39-L41

It looks like the framework never calls this. Adding a call to it also doesn't currently cause the native textures to get released (until a GC happens). It's also a little hard to be 100% sure of when that would be safe to call anyway.

> Have you actually seen this happening?

I changed the simple demo app from Mehmet so that it displays the image when the counter is at an even number. I occasionally see memory spikes in Xcode that indicate two SkImages are still resident - in fact, I managed to get it to pause at one point where that was still the case: 
![image](https://user-images.githubusercontent.com/8620741/82408531-9a810880-9a20-11ea-8064-d6e8c44005ab.png)

I'm fairly sure that one of those is in the old gen heap and one is the new incoming image - the memory drops down quickly. However, with sufficiently large images this would definitely fail, even if there was lots of wall time between the taps.

**Comment by dnfield** [comment] 2020-05-20 05:34
I would have expected a call to `NotifyIdle` to trigger the GC we want here - but I'm not entirely clear on whether that's getting called. At the very least, I'd expect it to get called when we go background if it's not already.

**Comment by dnfield** [comment] 2020-05-21 16:05
So my thought at this point is:

- We can update `dispose` on `ui.Image` to actually clear the native memory.
- We can update the framework to call `dispose` in `ImageStreamCompleter`s when they lose their last listener, and then just make sure if a new listener is added we re-create the image object.

That should resolve this issue more cleanly than trying to tune the Dart VM for this. I still wonder if there's some improvement to Dart's GC logic that could be done, but I'm not sure how much it would help since the GC may be done on one thread, the engine learns it can dispose the native memory on another thread, and yet another thread may be used by Skia to do the final freeing of resources.

**Comment by dnfield** [comment] 2020-06-01 23:08
This will be fixed by a combination of https://dart-review.googlesource.com/c/sdk/+/149521 and https://github.com/flutter/engine/pull/18706

**Comment by dnfield** [comment] 2020-06-10 03:10
Design doc discussing some options: https://docs.google.com/document/d/15zslrHsWigh9e8LeQxfieWwnXDBx5jicFPXD6l_SsH4/edit?usp=sharing

**Comment by chinmaygarde** [comment] 2020-06-15 17:55
@dnfield Do you want to adjust the milestone? The work items in the design do seemed like a stretch to cover given within the current milestone.

**Comment by dnfield** [comment] 2020-06-15 17:56
Yes.  I was initially more hopeful of a quick fix for this.  I'll update it

**Comment by jtmcdole** [comment] 2020-06-17 21:02
Is the milestone update on this suggested that this is the upper bounds of when this will be fixed, or the lower?  `customer: fun` considers this a bit higher priority as we run on embedded devices.

**Comment by dnfield** [comment] 2020-06-17 22:29
Upper.

**Comment by dnfield** [comment] 2020-06-22 19:12
https://github.com/dart-lang/sdk/issues/42078

**Comment by chinmaygarde** [comment] 2020-06-29 18:22
Triage: I am not able to tell if there is any active progress being made on the linked issue. Beyond the updated representation of external memory reported to the VM by the engine (via `Dart_UpdateExternalSize`), is there any current active line of investigation? The patch on the proposed `Dart_HintFreed` seems to be stalled. [The work around retooling GC heuristics](https://dart-review.googlesource.com/c/sdk/+/125000) was borne out of this effort but should not affect image memory specifically either as it controls how readily the heap will shrink when the image is collected, but the issue seems to be that the collection itself does not happen as fast as we would like it to.

**Comment by dnfield** [comment] 2020-06-29 19:06
I've updated the linked document to outline all that retains the SkImage. I wanted to be sure there wasn't some reasonable way for us to free the image related memory without a gc.  I'm going to sync up with Ryan and Siva again on this now that I'm convinced we need a gc to fix it.

**Comment by chinmaygarde** [comment] 2020-07-06 18:04
Triage: Are the actionable work items remaining with this issue?

**Comment by dnfield** [comment] 2020-07-06 19:23
Yes - last week was a short week and I did not get around to my last update. Anticipate moving forward on that this week.

**Comment by chinmaygarde** [comment] 2020-07-13 18:05
@dnfield: IIRC, you were working on redoing the image decoder APIs. Do you need help with any of the remaining AIs?

**Comment by dnfield** [comment] 2020-07-14 00:54
Ok. I think we can generalize this slightly.

My new idea is to track the size of the layers we retain in the layer cache. When we sweep that cache, that is a good opportunity to notify the Dart VM that it could free the heap by as many bytes as we freed there. The Dart VM could then decide to do a GC or not.

That would resolve the case of images being retained as well as any other type of object we might be retaining in the layer tree, as long as we accurately bookeep the cost of the layer.

References:

https://github.com/flutter/engine/blob/master/flow/raster_cache.cc#L265 - Adding Dart_NotifyLowMemory after this adequately frees the memory of removing image(s) from the scene

Refactoring the image decoder API is a different angle on this problem. That's to help the developer we've told "your decoded image is too big, decode it smaller" so they can actually do that and maintain aspect ratio.

**Comment by dnfield** [comment] 2020-07-15 05:41
https://github.com/flutter/engine/compare/master..dnfield:hint_freed with https://dart-review.googlesource.com/c/sdk/+/150503 patched in fixes this bug.

I'll need to come up with some tests for it.

**Comment by dnfield** [comment] 2020-08-11 23:13
Update for triage: I'm back from leave and have followed up offline with @a-siva @rmacnak-google @mkustermann about status of Dart patch.

**Comment by dnfield** [comment] 2020-08-25 16:19
Reverting the fix for this since it caused some other performance regressions.

I am actively working on an updated reland that should be safer.

**Comment by dnfield** [comment] 2020-08-31 22:01
This had to get bumped to september to accomodate relanding a new fix. Those patches are currently in progress and should land "soon".

**Comment by dnfield** [comment] 2020-09-08 23:22
Engine changes have landed. https://github.com/flutter/flutter/pull/64582 is still under review.

**Comment by dnfield** [comment] 2020-09-22 22:22
Framework side PR has been closed in favor of new engine change to create a disposable image wrapper. That is under review here: https://github.com/flutter/engine/pull/21057

It is currently blocked by https://github.com/flutter/flutter/pull/66379 and blocked by general difficulty in keeping the tree open of late.

**Comment by dnfield** [comment] 2020-09-25 22:13
engine patches have all landed, final framework patch is posted and under review.

**Comment by dnfield** [comment] 2020-09-28 17:52
Framework patch is awaiting another engine roll before it passes CI, but is still available for review. I expect to land it this week, which may mean it slips into the first week of October. Leaving it in September for now.

**Comment by dnfield** [comment] 2020-10-01 18:14
Here's a quick overview of the problem before this bug was closed:

1. dart:ui `Image` objects are backed natively by `SkImage`. `SkImage` is a C++ ref-counted pointer and it is considered immutable internally in Skia.
2. Although `Image` has a `dispose` method, that method only releases one reference on the `SkImage`. The `SkImage` will not be destroyed until the refcount is zero on the image, and potentially until we call `performDeferredCleanup` on the `GrContext`(s) related to objects referring to the image. 
2. We bump the refcount on an image any time we draw it into a picture.
2. Pictures are similarly backed by SkPicture objects, which are similarly refcounted. They get retained by Layer objects.
2. Layer objects have both a Dart and a C++ representation. Some of the C++ representations end up getting decoupled from any specific Dart object, e.g. an engine's idea of a `PictureLayer` has no direct Dart corresponding layer, but ends up being indirectly retained via various `EngineLayer` objects, which are retained by various framework `Layer` objects.
2. Framework `Layer` objects are retained by `RenderObjects`. `RenderObjects` to not have a clearly defined endpoint in their lifecycle - can get `detach`ed, but may be re-attached. 
2. At the core, we rely on the Dart GC to get rid of stale `RenderObject`s, `Layer`s, and `Picture`s. Once these things are gone, as long as the `Image` is not held in e.g. the `ImageCache`, it can also be collected and the native memory can be collected.
2. Previously, the Dart VM's GC heuristics relied on us creating new objects ("upward pressure") to know when to run a collection. There was no way to signal it that "downward pressure" existed (i.e., the program believes it has released references even if it doesn't immediately intend to create new ones). This was compounded by the fact that, as more memory gets allocated, the amount memory needed to trigger a collection increases, and so more new memory needs to get allocated.

Here's an overview of what had to happen to fix this, and some of the failed/reverted attempts.

1. Add a `HintFreed` API to the Dart VM so that we can signal it when we think memory might be freed. https://flutter.dev/go/downward-memory-pressure, https://dart-review.googlesource.com/c/sdk/+/150503
2. Use `HintFreed` at appropriate times in the engine.
  - An initial failed attempt involved trying to call this at every idle period with whatever garbage we thought we freed from the layer tree - https://github.com/flutter/engine/pull/19842. This would have had the advantage of not needing any changes to the framework or application code, at the cost of potentially doing more GCs than necessary.
  - This freed more memory, but became very CPU intensive as it triggered GCs way too frequently. Reverted here: https://github.com/flutter/engine/pull/20746
  - A second attempt was landed in https://github.com/flutter/engine/pull/20754, which focused specifically on using it when `Image.dispose` is called. This has the advantage of being more focused with GCs (although we will still see some upticks on GCs if many images are used and disposed of), but the disadvantage of requiring changes to the framework to actually dispose of images.
3. This meant that we had to get more serious about making the framework/applications dispose image objects. But the problem is, you never know if your own reference to an image is exclusive, and the framework was not built with any ownership model of image objects. This is particularly difficult as well because image objects have to be passed into canvas methods to draw, rather than calling a method on an image to draw to a canvas.
  - Initial attempt at doing this only on the framework side. https://github.com/flutter/flutter/pull/64582 Hacky, doesn't actually prevent framework or application code from disposing image objects out from under holders.
  - Rework dart:ui Image so that it can be safely cloned and disposed instead: https://github.com/flutter/engine/pull/21057
  - Rework the image stream/completer/provider/cache framework to clone handles and dispose of them when done: https://github.com/flutter/flutter/pull/66688. A key part of this is a behavioral change in `ImageStreamCompleter`s so that they are now considered disposed if they lose all listeners and no one is specifically asking to keep them alive.

This solution isn't perfect and has room for improvements:

1. LiveImage tracking can go wrong now, we can and should fix that: https://github.com/flutter/flutter/issues/67069
2. We should probably more highly prioritize excluding specific images from the cache (https://github.com/flutter/flutter/issues/47380), since customers now have very good reasons to avoid caching large images that could be disposed immediately after they're done being used (as long as that large image will not be used again).
3. The `dispose` API feels a bit clunky, especially on `ImageInfo`. `ImageInfo` is a const-creatable object that contains this stateful image which must get dispsoed.

**Comment by dnfield** [comment] 2020-10-01 23:44
This broke CanvasKit and some internal targets. Reverting and reopening while I investigate a reland.

**Closed** 2020-10-05 19:03 UTC
Labels: P2, a: images, customer: fun (g3), customer: money (g3), engine, framework, passed first triage, perf: memory, severe: performance, waiting for PR to land (fixed)

**Comment by dnfield** [comment] 2020-10-05 20:13
Fix has relanded, I think fo rreal this time :)
