### ISSUE TITLE
WebView support platform issues

### ISSUE THREAD

**Issue by sunbx** [flutter/flutter#77341] opened 2021-03-05 07:49 UTC
Fluuter after 2.0 can run in the browser, but in the app webview platform support to the android and ios only, when can you run in the browser webview  ?

**Comment by sqiao2-ford** [comment] 2021-03-05 08:17
In my mind webveiw as a small browser.

**Comment by sunbx** [comment] 2021-03-05 08:19
At present, the WebView library is not supported to run in the browser (Chrome), APP will encounter problems when doing migration, a lot of pages are done with WebView

**Comment by pedromassangocode** [comment] 2021-03-05 10:56
Hi @sunbx 
Can you please elaborate what this issue is about?

> At present, the WebView library is not supported to run in the browser (Chrome),

What library are you talking about? Do you have any link?

I don't think that it is expected for a webview plugin to run in a browser. Please elaborate more.
Thank you

**Comment by stuartmorgan** [comment] 2021-03-05 18:09
Duplicate of https://github.com/flutter/flutter/issues/45295

**Closed by stuartmorgan** 2021-03-05 18:09 UTC
Labels: in triage, waiting for customer response
