### ISSUE TITLE
Gallery: Over-scroll is the title, but it also does Refresh Indicator

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#6051] opened 2016-09-25 20:32 UTC
In the Gallery, on the homescreen, we have "Over-scroll", but the demo is also for Refresh Indicator.

We could add "& refresh indicator" to the list item title, to aid in discoverability.

**Comment by Hixie** [comment] 2017-01-31 06:51
Dupe of https://github.com/flutter/flutter/issues/5935

**Closed by Hixie** 2017-01-31 06:51 UTC
Labels: customer: gallery
