### ISSUE TITLE
Support keyboard 3d touch text selection on iOS

### ISSUE THREAD

**Issue by Eik1234** [flutter/flutter#67172] opened 2020-10-02 22:09 UTC
##  Use case
When typing in a text field on native iOS apps, you can force-press on the keyboard to move the cursor, and then force press further to select the word under the cursor. You can then drag the cursor around to extend the selection to more words, or force press again to deselect and go back to just moving the cursor. Force pressing repeatedly toggles between selecting or just moving the cursor.

In flutter applications you can move the cursor using 3d touch, but attempting to force touch further to select words does not work. Sometimes it seems to select the last word in the text field, but it does not work the same way as in native apps, where the word under the cursor is selected. This makes apps feel less native, and can be jarring as it does not do what you expect.

## Proposal
For Flutter to mimic this behaiviour as closely as possible, so it feels more like native apps.

**Comment by darshankawar** [comment] 2020-10-05 07:49
Related to [17030](https://github.com/flutter/flutter/issues/17030)

**Comment by DanielEdrisian** [comment] 2020-10-05 18:39
Since Apple is discontinuing use of 3D touch for long-press, I think we also need to opt-in for long-press instead. Is that explanation ok @Eik1234?

**Comment by pedromassangocode** [comment] 2020-11-24 10:09
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2020-11-24 10:09 UTC
Labels: a: text input, engine, f: cupertino, framework, platform-ios, proposal, waiting for customer response

**Comment by miguelSantirso** [comment] 2021-03-20 08:00
I think the original comment is quite clear: On iPhone, while dragging the cursor from the keyboard, you can "touch harder" to select a single word or a range of words. This doesn't seem to be supported on Flutter.

**Steps to reproduce:**
1. Write text with multiple words in a textfield
2. 3D touch on the keyboard to trigger the cursor mode
3. Move the cursor to any word that you want to select
4. 3D touch the screen (touch harder)

**Expected result:**

1. The word gets selected
2. You can drag the cursor to select more words

**Actual result:**

1. 3D touch while dragging the cursor has no effect

```
$ flutter doctor -v
[√] Flutter (Channel stable, 1.22.5, on Microsoft Windows [VersiÃ³n 10.0.19041.867], locale es-ES)
    • Flutter version 1.22.5 at D:\devtools\flutter-1.22
    • Framework revision 7891006299 (3 months ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4
```
