### ISSUE TITLE
MaterialButton throws unclear error when elevation is set

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#10743] opened 2017-06-15 20:27 UTC
## Steps to Reproduce

```dart
new MaterialButton(
  child: new Text('Click Me!'),
  elevation: 1.0,
  onPressed: () {},
)
```

Error message:

```
The following assertion was thrown building Material(MaterialType.button; elevation: 1.0;
textStyle.inherit: false; textStyle.color: Color(0xdd000000); textStyle.family: ".SF UI Text";
textStyle.size: 14.0; textStyle.weight: 500; textStyle.baseline: alphabetic; dirty; state:
_MaterialState#477957510()):
'package:flutter/src/material/material.dart': Failed assertion: line 215 pos 12: 'backgroundColor !=
null || widget.type == MaterialType.transparency': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new

When the exception was thrown, this was the stack:
#2      _MaterialState.build (package:flutter/src/material/material.dart:215:12)
#3      StatefulElement.build (package:flutter/src/widgets/framework.dart:3481:27)
#4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3391:15)
#5      Element.rebuild (package:flutter/src/widgets/framework.dart:3292:5)
```

The error happens in the guts of `Material` and does not correlate with the API for `MaterialButton`, which is what makes it confusing.

Workaround: use `RaisedButton` or `FlatButton` rather than `MaterialButton` directly if they work for you, or see their implementations if you are implementing a custom button based on `MaterialButton`.

## Logs

Reproducible as of f0be2fd6f0

**Comment by Hixie** [comment] 2017-06-16 07:01
You're not expected to use a MaterialButton directly usually.
What's going on here is that you neither set a background color nor told the widget to be transparent.
We should make that assert have a message explaining that, though.

**Comment by matthew-carroll** [comment] 2018-06-01 21:11
@yjbanov @Hixie - I'm unable to reproduce any error when using the provided MaterialButton configuration.  Has this issue resolved itself since June 2017?

**Comment by matthew-carroll** [comment] 2018-06-01 22:28
OK, closing.  Please re-open if the issue is seen again.

**Closed by matthew-carroll** 2018-06-01 22:28 UTC
Labels: easy fix, f: material design, framework
