### ISSUE TITLE
FlutterViewController cannot be released after flutter 3.10.1 ~ 3.10.5 and iOS mixed programming, but it can be released on flutter 3.7.6 ~ 3.7.12

### ISSUE THREAD

**Issue by AllLuckly** [flutter/flutter#128869] opened 2023-06-14 11:00 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

FlutterViewController cannot be released after flutter 3.10.1 ~ 3.10.4 and iOS mixed programming, but it can be released on flutter 3.7.11

```
- (void)didMoveToParentViewController:(UIViewController *)parent{
    [super didMoveToParentViewController:parent];
    [self.messageChannel setMessageHandler:nil];
    self.messageChannel = nil;
    [self.engine setViewController:nil];
    [self.engine destroyContext];
    [self.view removeFromSuperview];
    self.view = nil;
    [[NSNotificationCenter defaultCenter] removeObserver:self];
}
```

### Impacted Users

iOS Apps that has custom Objective-C or Swift code to manage the life cycle of the Flutter engine.

### Expected results

Call dealloc when FlutterViewController is released

### Actual results

FlutterViewController cannot be released and will not call dealloc

### Code sample

<details><summary>Code sample</summary>

```OC
FlutterEngine *flutterEngine = [[FlutterEngine alloc] initWithName:@"XXFlutter"];
    [flutterEngine runWithEntrypoint:nil initialRoute:pageName];
    XXFlutterViewController* flutterViewController = [[XXFlutterViewController alloc] initWithEngine:flutterEngine nibName:nil bundle:nil];
[self.navigationController pushViewController:flutterViewController animated:YES];
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by dam-ease** [comment] 2023-06-14 11:55
Hi @AllLuckly. Please can you provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces this issue?

**Comment by TeacherXue** [comment] 2023-06-15 02:04
The same problem, please solve it as soon as possible, the mac version also has it, and it has been solved.

**Comment by AllLuckly** [comment] 2023-06-21 17:26
> FlutterEngine *flutterEngine = [[FlutterEngine alloc] initWithName:@"XXFlutter"];
>     [flutterEngine runWithEntrypoint:nil initialRoute:pageName];
>     XXFlutterViewController* flutterViewController = [[XXFlutterViewController alloc] initWithEngine:flutterEngine nibName:nil bundle:nil];
> [self.navigationController pushViewController:flutterViewController animated:YES];

XXFlutterViewController 是继承FlutterViewController的控制器；

**Comment by AllLuckly** [comment] 2023-06-22 02:15
> Hi @AllLuckly. Please can you provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces this issue?
this is demo https://github.com/AllLuckly/flutterTestDemo

**Comment by dam-ease** [comment] 2023-06-22 07:57
Hi @AllLuckly 
Can you check [this](https://github.com/flutter/flutter/issues/94099#issuecomment-979707608) issue comment and see if it solves your issue.

**Comment by AllLuckly** [comment] 2023-06-22 10:07
> 这个

No,  I now  use  

```
FlutterEngine *flutterEngine = [[FlutterEngine alloc] init];
[flutterEngine runWithEntrypoint:nil initialRoute:initialRoute];
self = [super initWithEngine:flutterEngine nibName:nibName bundle:nibBundle];
```
but  no  dealloc

**Comment by dam-ease** [comment] 2023-06-22 11:03
Hi @AllLuckly. Unfortunately, I'm not particularly familiar with native iOS, can you provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code, logs (if any) and step-by-step process to reproduce the issue?

**Comment by AllLuckly** [comment] 2023-06-23 08:29
> 你好@AllLuckly。不幸的是，我对本机 iOS 不是特别熟悉，您能否提供一个[最小的完整可重现代码示例](https://stackoverflow.com/help/minimal-reproducible-example)，其中不包括第 3 方插件或复杂的生产代码、日志（如果有）以及重现问题的分步过程？

this is demo https://github.com/AllLuckly/flutterTestDemo

**Comment by AllLuckly** [comment] 2023-06-26 02:05
Why isn't the official going to solve the serious problem?

**Comment by dam-ease** [comment] 2023-06-26 08:40
Hi @AllLuckly. Thanks for the detailed explanation. I am able to reproduce this on the latest `master` and `stable` channels.

<details><summary>flutter doctor -v</summary>
<p>

```
[✓] Flutter (Channel stable, 3.10.5, on macOS 13.4 22F66 darwin-arm64, locale
    en-NG)
    • Flutter version 3.10.5 on channel stable at /Users/dammya/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (12 days ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version
    32.1.0-rc1)
    • Android SDK at /Users/dammya/Library/Android/sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • ANDROID_HOME = /Users/dammya/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2022.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.79.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (3 available)
    • iPhone 14 Pro (mobile) • DCF2031A-7EA9-42FF-8CD4-D4584F3E7A6D • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)        • macos                                •
      darwin-arm64   • macOS 13.4 22F66 darwin-arm64
    • Chrome (web)           • chrome                               •
      web-javascript • Google Chrome 114.0.5735.133

[✓] Network resources
    • All expected network resources are available.

• No issues found!
``` 

```
[✓] Flutter (Channel master, 3.12.0-10.0.pre.35, on macOS 13.4 22F66 darwin-arm64, locale en-NG)
    • Flutter version 3.12.0-10.0.pre.35 on channel master at /Users/dammya/fvm/versions/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c7f82a1ca2 (5 hours ago), 2023-06-25 23:44:09 -0400
    • Engine revision 88ff46e1ef
    • Dart version 3.1.0 (build 3.1.0-246.0.dev)
    • DevTools version 2.24.0

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/dammya/Library/Android/sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • ANDROID_HOME = /Users/dammya/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2022.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.79.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (3 available)
    • iPhone 14 Pro (mobile) • DCF2031A-7EA9-42FF-8CD4-D4584F3E7A6D • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 13.4 22F66 darwin-arm64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 114.0.5735.133

[✓] Network resources
    • All expected network resources are available.

• No issues found!
``` 

</p>
</details>

**Comment by cyanglaz** [comment] 2023-06-26 16:52
Similar to https://github.com/flutter/flutter/issues/126560

**Comment by chinmaygarde** [comment] 2023-06-26 17:38
Closing as duplicate of https://github.com/flutter/flutter/issues/126560.

**Closed by chinmaygarde** 2023-06-26 17:38 UTC
Labels: severe: regression, platform-ios, engine, has reproducible steps, found in release: 3.10, found in release: 3.12
