### ISSUE TITLE
[MacOS][Web] The scrolling performance degradation

### ISSUE THREAD

**Issue by Tamilarasan-Paranthaman** [flutter/flutter#123204] opened 2023-03-22 10:53 UTC
The scrolling performance on the MacOS `Web` platform was degrading.

## Steps to Reproduce

1. Run the sample in the `Web` platform on MacOS.
2. Scroll the sample in vertical direction.

**Expected results:** The scrolling performance needs to be smoother.

**Actual results:** The scrolling performance was lack of smoothness.

<details>
<summary>Code sample</summary>

```dart

import 'package:flutter/material.dart';

void main() {
  runApp(const FlutterDemo());
}

class FlutterDemo extends StatelessWidget {
  const FlutterDemo({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: _FlutteDemo(),
    );
  }
}

class _FlutteDemo extends StatefulWidget {
  const _FlutteDemo();

  @override
  State<_FlutteDemo> createState() => _FlutteDemoState();
}

class _FlutteDemoState extends State<_FlutteDemo> {
  List<Widget> widgets = [];

  @override
  void initState() {
    super.initState();
    for (int i = 0; i < 200; i++) {
      widgets.add(Container(
        height: 50,
        width: 70,
        decoration: BoxDecoration(border: Border.all(color: Colors.black)),
        child: Text(i.toString()),
      ));
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(title: const Text('Flutter Sample')),
        body: SingleChildScrollView(
          child: Row(
            children: [
              Column(children: widgets),
              Column(children: widgets),
              Column(children: widgets),
              Column(children: widgets),
              Column(children: widgets),
              Column(children: widgets),
              Column(children: widgets),
              Column(children: widgets),
              Column(children: widgets),
              Column(children: widgets),
            ],
          ),
        ));
  }
}

```

</details>

<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel stable, 3.7.7, on macOS 13.1 22C65 darwin-x64, locale en-GB)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location. [✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[!] Android Studio (not installed)
[✓] VS Code (version 1.75.1)
[✓] VS Code (version 1.76.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability 

! Doctor found issues in 2 categories.
```
</details>

**Comment by Tamilarasan-Paranthaman** [comment] 2023-03-23 08:00
Hello @iapicca,

Thank you for your response. In my application, I am using a **SingleChildScrollView** for some use cases. The sample I provided was a simplified version of my application used to replicate the issue I am facing. After testing this sample on both the **`MacOS Desktop`** and the **`Web`** on the Mac platform, I have observed a difference in scrolling performance between the two platforms. For your reference, I have attached videos demonstrating the issue.

**The output in MacOS Desktop platform:** 


https://user-images.githubusercontent.com/93904422/227139034-e93279d0-8915-4ae2-a00c-f30a24b5441a.mov


**The output in Mac Web platform:** 

https://user-images.githubusercontent.com/93904422/227139085-2db4890c-3f98-4908-b949-aa30fcf6122f.mov

**Comment by darshankawar** [comment] 2023-03-23 11:20
Thanks for the update. I am seeing same behavior as reported above, specially noticeable using canvaskit renderer. With html renderer, the scrolling is much better and smooth:


https://user-images.githubusercontent.com/67046386/227187969-24d03a88-0230-4edd-976f-210f8724da26.mov

<details>
<summary> stable, master flutter doctor -v </summary>

```
[!] Flutter (Channel stable, 3.7.7, on macOS 12.2.1 21D62 darwin-x64, locale
    en-GB)
    • Flutter version 3.7.7 on channel stable at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2ad6cd72c0 (12 days ago), 2023-03-08 09:41:59 -0800
    • Engine revision 1837b5be5f
    • Dart version 2.19.4
    • DevTools version 2.20.1
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

[!] Flutter (Channel master, 3.9.0-12.0.pre.18, on macOS 12.2.1 21D62
    darwin-x64, locale en-GB)
    • Flutter version 3.9.0-12.0.pre.18 on channel master at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 28f17d345b (39 minutes ago), 2023-03-20 21:08:41 -0700
    • Engine revision ea6ed14b4e
    • Dart version 3.0.0 (build 3.0.0-345.0.dev)
    • DevTools version 2.22.2
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/dhs/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13C100
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 65.1.4
    • Dart plugin version 213.7228

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (3 available)
    • Darshan's iphone (mobile) • 21150b119064aecc249dfcfe05e259197461ce23 • ios
      • iOS 15.3.1 19D52
    • macOS (desktop)           • macos                                    •
      darwin-x64     • macOS 12.2.1 21D62 darwin-x64
    • Chrome (web)              • chrome                                   •
      web-javascript • Google Chrome 109.0.5414.119

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
      
[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.



```

</details>

**Comment by rjcalifornia** [comment] 2023-03-23 21:12
> @Tamilarasan-Paranthaman
> 
> I suspect [SingleChildScrollView](https://api.flutter.dev/flutter/widgets/SingleChildScrollView-class.html) is the wrong tool for the job, you will have much better performances using a simple [ListView.builder ](https://api.flutter.dev/flutter/widgets/ListView/ListView.builder.html)
> 
> please try the code sample below, here is the link to a [dartpad sample](https://dartpad.dartlang.org/?id=222c792502d2a049fa957a6c9b4f5a0e)
> code sample

Well, reduce the vertical count to 50, and the SingleChildScrollView performs just like the ListView.builder. Why does it happen and what can be done to stop that from happening?

**Comment by maRci002** [comment] 2023-03-23 21:28
> Well, reduce the vertical count to 50, and the SingleChildScrollView performs just like the ListView.builder. Why does it happen and what can be done to stop that from happening?

Basicly when you are scrolling flutter triggers painting phase, so you have to break your `Row` into smaller pieces (_I would suggest to refactor `Row` -> `Column` to `Column` -> `Row` or just use the `GridView`_).

Use `ListView` or `CustomScrollView` which will use `RepaintBoundary` for it's children by default.

If you want to stick with `SingleChildScrollView` then wrap your `Container` / `Column` by `RepaintBoundary`.

**Comment by Piinks** [comment] 2023-03-24 17:09
> Well, reduce the vertical count to 50, and the SingleChildScrollView performs just like the ListView.builder. Why does it happen and what can be done to stop that from happening?

This is because a SingleChildScrollView does not lazily build children, but a ListView does. The more children you provide to a SingleChildScrollView, the more apparent the cost in performance of laying everything out is. It is called a **single child** scroll view very intentionally. It is not intended for use with many children.

> specially noticeable using canvaskit renderer. With html renderer, the scrolling is much better and smooth

This is something for the web team to weigh in on when they have their weekly triage.

**Comment by iapicca** [comment] 2023-03-24 17:13
> [...] In my application, I am using a **SingleChildScrollView** for some use cases. 
> [...] After testing this sample on both the **`MacOS Desktop`** and the **`Web`** on the Mac platform, I have observed a difference in scrolling performance between the two platforms. For your reference, I have attached videos demonstrating the issue.

@Tamilarasan-Paranthaman 
I think you are making a good point, in some cases is not possible to implement it lazily (eg. https://github.com/flutter/flutter/issues/123204)
and web performance should match or be close enough to other platforms

**Comment by rjcalifornia** [comment] 2023-03-24 17:17
> This is because a SingleChildScrollView does not lazily build children, but a ListView does. The more children you provide to a SingleChildScrollView, the more apparent the cost in performance of laying everything out is. It is called a **single child** scroll view very intentionally. It is not intended for use with many children.

Got it! That makes sense, ListView is so much better for listing items. It should not be a problem.

**Comment by rydmike** [comment] 2023-03-24 17:28
Could this performance issue partially also be related to https://github.com/flutter/flutter/issues/122189?

After 3.7 Flutter was released, performance of any SKIA web build pretty much went down the drain, compared to where it was before. The optimization points above are still valid, but should not have a big impact on the example above.

Any significant amount text rendering is horrific on a canvaskit build now. Plus it leaks and will eventually crash. The more text/icons you have the worse it gets and the faster it crashes, especially if redrawn a lot like when toggling between light/dark mode multiple times.

The only workaround at the moment is unfortunately to use the html renderer.

**Comment by iapicca** [comment] 2023-03-26 15:46
possibly related to 
- https://github.com/flutter/flutter/issues/123484

**Comment by yjbanov** [comment] 2023-03-30 03:40
https://github.com/flutter/flutter/issues/123484 is fixed now. Anyone available to test their apps at HEAD?

**Comment by yjbanov** [comment] 2023-04-05 01:03
@grahamsmith 

Thanks for checking! Can you please try again on this commit: 303d0d3e2b7131ed6177ec127f05a46f4307b519. We made another optimization with a significant improvement in some of our benchmarks. I checked the original repro as well and it improved significantly too. I'm curious if the gains are observable on other hardware/OS combinations.

**Comment by grahamsmith** [comment] 2023-04-05 01:09
It's 2am here so will check this in 12 hours or so.

Thanks for continuing to iterate on the issue.

**Comment by yjbanov** [comment] 2023-04-05 05:10
This was reverted again (https://github.com/flutter/engine/pull/40937). I'm landing it again in https://github.com/flutter/engine/pull/40938. To make sure you get the right code when verifying the fix, syncing to specifically https://github.com/flutter/flutter/commit/303d0d3e2b7131ed6177ec127f05a46f4307b519 is the safest bet.

**Comment by iapicca** [comment] 2023-04-05 19:44
it would be nice to add a test/benchmark to prevent this issue to re-emerge in the future

**Comment by yjbanov** [comment] 2023-04-05 20:00
@iapicca We have a benchmark, and it did show regressions (causing me to file https://github.com/flutter/flutter/issues/123484) and improvements. It just wasn't immediately obvious if this issue was caused by the same regression. The benchmark has been stable for a long time, since 2020, before we even launched CanvasKit in stable:

<img width="1535" alt="Screenshot 2023-04-05 at 12 53 00 PM" src="https://user-images.githubusercontent.com/211513/230191866-e99e96a9-7aeb-45b0-870e-e93c30b95cfa.png">

According to that benchmark this [latest PR](https://github.com/flutter/engine/pull/40938) will hopefully make it the fastest it's ever been (you can see the last drop in the history chart, which covers the last couple of weeks, which is 2-3x faster than the previous fastest times we've seen).

**Comment by yjbanov** [comment] 2023-04-10 18:57
I'm going to consider this as fixed. Performance optimization is never "done", but given that we're now 3x faster than pre-regression numbers I think this issue has served its purpose. We can open new issues for more specific cases.

The benchmark has been stable for almost a week now:

<img width="1395" alt="Screenshot 2023-04-10 at 11 52 51 AM" src="https://user-images.githubusercontent.com/211513/230972557-894fb98c-fac5-4448-bdce-e545ab4e4409.png">

Thanks, everyone for reporting and kicking the tires!

**Closed by yjbanov** 2023-04-10 18:57 UTC
Labels: engine, severe: performance, f: scrolling, platform-web, perf: speed, e: web_canvaskit, has reproducible steps, P3, found in release: 3.7, found in release: 3.9

**Comment by rydmike** [comment] 2023-04-10 23:21
@yjbanov can we expect the fix and https://github.com/flutter/engine/pull/40740 to land in beta channel soon? Would make them much more usable as interim solutions, while waiting for next stable (3.10?), than building with master, that can be bit too flaky sometimes.

**Comment by yjbanov** [comment] 2023-04-11 23:42
@rydmike Yes, this should make it into the beta that will eventually become 3.10.
