### ISSUE TITLE
replaceAll function does not work with letter č

### ISSUE THREAD

**Issue by ljmatan** [flutter/flutter#78751] opened 2021-03-22 00:52 UTC
I'm trying to use replaceAll function with letter č but it doesn't seem to work. It replaces other letters in Croatian alphabet however - ćžđš. 

Minimal example: 
```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: ErrorExample(),
    );
  }
}

class ErrorExample extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: ElevatedButton(
          child: Text('aaaaaaaa'),
          onPressed: () {
            String username = 'čćžđš';
            username = username.replaceAll('č', 'c');
            username = username.replaceAll('ć', 'c');
            username = username.replaceAll('š', 's');
            username = username.replaceAll('ž', 'z');
            username = username.replaceAll('đ', 'd');
            print(username);
          },
        ),
      ),
    );
  }
}

```

<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel master, 2.1.0-13.0.pre.192, on Linux, locale en_US.UTF-8)
    • Flutter version 2.1.0-13.0.pre.192 at /home/user/Development/flutter
    • Framework revision c0bcb4fc16 (2 days ago), 2021-03-19 16:34:57 -0700
    • Engine revision e6db3a275e
    • Dart version 2.13.0 (build 2.13.0-149.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/user/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /home/user/Development/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /home/user/Documents/android-studio
    • Flutter plugin version 44.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Android Studio (version 4.1)
    • Android Studio at /home/user/Development/android-studio
    • Flutter plugin version 51.0.2
    • Dart plugin version 201.9002
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.53.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.20.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 88.0.4324.182

• No issues found!
```

</details>

**Comment by pedromassangocode** [comment] 2021-03-22 11:59
Hi @ljmatan 
From what I can see, the issue is related to a 3rd party plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/dart-lang/sdk/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by pedromassangocode** 2021-03-22 11:59 UTC
Labels: in triage
