### ISSUE TITLE
TypeErrorImpl Thrown When Building CircleAvatar Widget with Unexpected Null Value

### ISSUE THREAD

**Issue by nploi** [flutter/flutter#127466] opened 2023-05-24 06:22 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Create a Flutter project.
2. Add 
    ```dart
    theme: Theme.of(context).copyWith(
            primaryTextTheme: TextTheme(),
          ),
    ```
    in `MaterialApp` widget
3. Use the `CircleAvatar` widget in your code.
4. Trigger a run.

### Expected results

The CircleAvatar widget should render without any errors and display the expected content.

### Actual results

The TypeErrorImpl exception is thrown with the error message "Unexpected null value." The error occurs in the CircleAvatar widget during the build process.

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    var title = 'Web Images';

    return MaterialApp(
      title: title,
      theme: Theme.of(context).copyWith(
        primaryTextTheme: TextTheme(),
      ),
      home: Scaffold(
          appBar: AppBar(
            title: Text(title),
          ),
          body: CircleAvatar(
            backgroundImage: NetworkImage(
              'https://picsum.photos/250?image=9',
            ),
          )),
    );
  }
}

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

<img width="612" alt="Screenshot 2023-05-24 at 13 17 03" src="https://github.com/flutter/flutter/assets/34020090/794eeb04-5ff9-4daa-b8a5-545652a33f6c">

</details>

### Logs

<details><summary>Logs</summary>

```console
═╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following TypeErrorImpl was thrown building CircleAvatar(dirty, dependencies: [_InheritedTheme,
_LocalizationsScope-[GlobalKey#2ec66]]):
Unexpected null value.
The relevant error-causing widget was:
CircleAvatar
main.dart:21
When the exception was thrown, this was the stack:
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 288:49      throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 606:63  nullCheck
packages/flutter/src/material/circle_avatar.dart 207:67                           build
packages/flutter/src/widgets/framework.dart 5156:22                               build
packages/flutter/src/widgets/framework.dart 5086:15                               performRebuild
packages/flutter/src/widgets/framework.dart 4805:7                                rebuild
packages/flutter/src/widgets/framework.dart 5162:5                                update
packages/flutter/src/widgets/framework.dart 3686:14                               updateChild
packages/flutter/src/widgets/framework.dart 5111:16                               performRebuild
packages/flutter/src/widgets/framework.dart 4805:7                                rebuild
packages/flutter/src/widgets/framework.dart 5162:5                                update
packages/flutter/src/widgets/framework.dart 3686:14                               updateChild
packages/flutter/src/widgets/framework.dart 5111:16                               performRebuild
packages/flutter/src/widgets/framework.dart 4805:7                                rebuild
packages/flutter/src/widgets/framework.dart 5162:5                                update
packages/flutter/src/widgets/framework.dart 3686:14                               updateChild
packages/flutter/src/widgets/framework.dart 5111:16                               performRebuild
packages/flutter/src/widgets/framework.dart 4805:7                                rebuild
packages/flutter/src/widgets/framework.dart 5417:5                                update
packages/flutter/src/widgets/framework.dart 3686:14                               updateChild
packages/flutter/src/widgets/framework.dart 5111:16                               performRebuild
packages/flutter/src/widgets/framework.dart 4805:7                                rebuild
packages/flutter/src/widgets/framework.dart 5417:5                                update
packages/flutter/src/widgets/framework.dart 3686:14                               updateChild
packages/flutter/src/widgets/framework.dart 6093:32                               updateChildren
packages/flutter/src/widgets/framework.dart 6595:17                               update
packages/flutter/src/widgets/framework.dart 3686:14                               updateChild
packages/flutter/src/widgets/framework.dart 5111:16                               performRebuild
packages/flutter/src/widgets/framework.dart 4805:7                                rebuild
packages/flutter/src/widgets/framework.dart 5417:5                                update
packages/flutter/src/widgets/framework.dart 3686:14                               updateChild
packages/flutter/src/widgets/framework.dart 5111:16                               performRebuild
packages/flutter/src/widgets/framework.dart 5251:11                               performRebuild
packages/flutter/src/widgets/framework.dart 4805:7                                rebuild
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Flutter 3.10.0 • channel unknown • unknown source
Framework • revision 84a1e904f4 (2 weeks ago) • 2023-05-09 07:41:44 -0700
Engine • revision d44b5a94c9
Tools • Dart 3.0.0 • DevTools 2.23.1
```

</details>

**Comment by nploi** [comment] 2023-05-24 06:28
My workaround.
```dart
return MaterialApp(
      title: title,
      theme: Theme.of(context).copyWith(
          primaryTextTheme: Theme.of(context).primaryTextTheme.copyWith(
                titleLarge: TextStyle(),
              )),
      home: Scaffold(
          appBar: AppBar(
            title: Text(title),
          ),
          body: CircleAvatar(
            backgroundImage: NetworkImage(
              'https://picsum.photos/250?image=9',
            ),
          )),
    );
```

**Comment by danagbemava-nc** [comment] 2023-05-24 10:25
Reproduces using the code sample provided above. 

<details>
<summary>logs</summary>

```
======== Exception caught by widgets library =======================================================
The following _TypeError was thrown building CircleAvatar(dirty, dependencies: [_InheritedTheme, _LocalizationsScope-[GlobalKey#81c0f]]):
Null check operator used on a null value

The relevant error-causing widget was: 
  CircleAvatar CircleAvatar:file:///Users/nexus/projects/nevercode/crash/lib/main.dart:21:15
When the exception was thrown, this was the stack: 
#0      CircleAvatar.build (package:flutter/src/material/circle_avatar.dart:207:67)
#1      StatelessElement.build (package:flutter/src/widgets/framework.dart:5156:49)
#2      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5086:15)
#3      Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#4      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5068:5)
#5      ComponentElement.mount (package:flutter/src/widgets/framework.dart:5062:5)
...     Normal element mounting (25 frames)
#30     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3971:16)
#31     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6570:36)
#32     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6582:32)
...     Normal element mounting (128 frames)
#160    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3971:16)
#161    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6570:36)
#162    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6582:32)
...     Normal element mounting (178 frames)
#340    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3971:16)
#341    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6570:36)
#342    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6582:32)
...     Normal element mounting (492 frames)
#834    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3971:16)
#835    Element.updateChild (package:flutter/src/widgets/framework.dart:3708:18)
#836    RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1253:16)
#837    RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:1222:5)
#838    RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:1169:18)
#839    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2720:19)
#840    RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:1168:13)
```
</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.10.1, on macOS 13.3.1 22E772610a darwin-arm64, locale en-GB)
    • Flutter version 3.10.1 on channel stable at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d3d8effc68 (7 days ago), 2023-05-16 17:59:05 -0700
    • Engine revision b4fb11214d
    • Dart version 3.0.1
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/222.4459.24.2221.9971841/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode-14.3.0.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/222.4459.24.2221.9971841/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] Android Studio (version 2022.2)
    • Android Studio at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/222.4459.24.2221.9862592/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.2)
    • IntelliJ at /Users/nexus/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 73.1.1
    • Dart plugin version 231.9065

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.2)
    • IntelliJ at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/231.9011.34/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.1)
    • IntelliJ at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/231.8770.65/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.78.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.64.0

[✓] Connected device (4 available)
    • Nexus (mobile)       • 00008020-001875E83A38002E • ios            • iOS 16.4.1 20E252
    • Dean’s iPad (mobile) • 00008103-000825C811E3401E • ios            • iOS 16.4.1 20E252
    • macOS (desktop)      • macos                     • darwin-arm64   • macOS 13.3.1 22E772610a darwin-arm64
    • Chrome (web)         • chrome                    • web-javascript • Google Chrome 113.0.5672.126
    ! Error: Nexus is busy: Fetching debug symbols for Nexus. Xcode will continue when Nexus is finished. (code -10)
    ! Error: Dean’s iPad is busy: Fetching debug symbols for Dean’s iPad. Xcode will continue when Dean’s iPad is finished. (code -10)

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

```
[!] Flutter (Channel master, 3.11.0-12.0.pre.28, on macOS 13.3.1 22E772610a darwin-arm64, locale en-GB)
    • Flutter version 3.11.0-12.0.pre.28 on channel master at /Users/nexus/dev/sdks/flutters
    ! Warning: `flutter` on your path resolves to /Users/nexus/dev/sdks/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/nexus/dev/sdks/flutters. Consider adding /Users/nexus/dev/sdks/flutters/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/nexus/dev/sdks/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/nexus/dev/sdks/flutters. Consider adding /Users/nexus/dev/sdks/flutters/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 216605b60f (7 hours ago), 2023-05-23 23:40:27 -0400
    • Engine revision eebcf36cd3
    • Dart version 3.1.0 (build 3.1.0-139.0.dev)
    • DevTools version 2.23.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/222.4459.24.2221.9971841/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode-14.3.0.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/222.4459.24.2221.9971841/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] Android Studio (version 2022.2)
    • Android Studio at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/222.4459.24.2221.9862592/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.2)
    • IntelliJ at /Users/nexus/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 73.1.1
    • Dart plugin version 231.9065

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.2)
    • IntelliJ at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/231.9011.34/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.1)
    • IntelliJ at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/231.8770.65/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.78.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.64.0

[✓] Connected device (3 available)
    • Dean’s iPad (mobile) • 00008103-000825C811E3401E • ios            • iOS 16.4.1 20E252
    • macOS (desktop)      • macos                     • darwin-arm64   • macOS 13.3.1 22E772610a darwin-arm64
    • Chrome (web)         • chrome                    • web-javascript • Google Chrome 113.0.5672.126
    ! Error: Dean’s iPad is busy: Fetching debug symbols for Dean’s iPad. Xcode will continue when Dean’s iPad is finished. (code -10)

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

```
</details>

**Comment by TahaTesser** [comment] 2023-05-24 12:48
Thanks for the report @nploi 

Here I simplified the code sample, I will take a look closer tomorrow to fix this. 
```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: Theme.of(context).copyWith(
        primaryTextTheme: const TextTheme(),
      ),
      home: const Scaffold(
        body: Center(
          child: CircleAvatar(),
        ),
      ),
    );
  }
}
```

**Comment by nploi** [comment] 2023-05-24 15:27
> Thanks for the report @nploi
> 
> Here I simplified the code sample, I will take a look closer tomorrow to fix this.
> 
> ```dart
> import 'package:flutter/material.dart';
> 
> void main() => runApp(const MyApp());
> 
> class MyApp extends StatelessWidget {
>   const MyApp({super.key});
> 
>   @override
>   Widget build(BuildContext context) {
>     return MaterialApp(
>       theme: Theme.of(context).copyWith(
>         primaryTextTheme: const TextTheme(),
>       ),
>       home: const Scaffold(
>         body: Center(
>           child: CircleAvatar(),
>         ),
>       ),
>     );
>   }
> }
> ```

Thank you!

**Comment by TahaTesser** [comment] 2023-05-26 08:32
Hi @nploi 
After taking a look closer, this looks like it is working as expected.  

You're using `BuildContext` to get theme  data when there is no context above  `MyApp` to provide, which returns a `null` copy of `ThemeData`, then providing an empty `TextTheme` which doesn't text color. `CircleAvatar`  looks for this color to estimate color brightness for M2. Any widget that relies on it would fail, no just `CircleAvatar`. 

To fix this, you can provide `ThemeData` without looking up in the build tree for `ThemeData` 

```dart
      theme: ThemeData(
        primaryTextTheme: const TextTheme(),
      ),
```


This can be reproduced without using `CircleAvatar`

<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      // theme: Theme.of(context).copyWith(
      //   primaryTextTheme: const TextTheme(),
      // ),
      theme: ThemeData(
        primaryTextTheme: const TextTheme(),
      ),
      home: const Scaffold(
        body: Center(
          // child: CircleAvatar(),
          child: SomeWidget(),
        ),
      ),
    );
  }
}

class SomeWidget extends StatelessWidget {
  const SomeWidget({super.key});

  @override
  Widget build(BuildContext context) {
    final ThemeData theme = Theme.of(context);

    return Text(theme.primaryTextTheme.titleMedium!.color!.toString());
  }
}
``` 
	
</details>

Closing, as this is working as expected.

**Closed by TahaTesser** 2023-05-26 08:32 UTC
Labels: severe: crash, framework, f: material design, a: error message, has reproducible steps, found in release: 3.10, found in release: 3.11

**Comment by nploi** [comment] 2023-05-26 10:48
> Hi @nploi After taking a look closer, this looks like it is working as expected.
> 
> You're using `BuildContext` to get theme data when there is no context above `MyApp` to provide, which returns a `null` copy of `ThemeData`, then providing an empty `TextTheme` which doesn't text color. `CircleAvatar` looks for this color to estimate color brightness for M2. Any widget that relies on it would fail, no just `CircleAvatar`.
> 
> To fix this, you can provide `ThemeData` without looking up in the build tree for `ThemeData`
> 
> ```dart
>       theme: ThemeData(
>         primaryTextTheme: const TextTheme(),
>       ),
> ```
> 
> This can be reproduced without using `CircleAvatar`
> 
> code sample
> ```dart
> import 'package:flutter/material.dart';
> 
> void main() => runApp(const MyApp());
> 
> class MyApp extends StatelessWidget {
>   const MyApp({super.key});
> 
>   @override
>   Widget build(BuildContext context) {
>     return MaterialApp(
>       // theme: Theme.of(context).copyWith(
>       //   primaryTextTheme: const TextTheme(),
>       // ),
>       theme: ThemeData(
>         primaryTextTheme: const TextTheme(),
>       ),
>       home: const Scaffold(
>         body: Center(
>           // child: CircleAvatar(),
>           child: SomeWidget(),
>         ),
>       ),
>     );
>   }
> }
> 
> class SomeWidget extends StatelessWidget {
>   const SomeWidget({super.key});
> 
>   @override
>   Widget build(BuildContext context) {
>     final ThemeData theme = Theme.of(context);
> 
>     return Text(theme.primaryTextTheme.titleMedium!.color!.toString());
>   }
> }
> ```
> 
> Closing, as this is working as expected.

Oh, i got it. Thank you.
