### ISSUE TITLE
Mac_android home_scroll_perf__timeline_summary timed out

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#83382] opened 2021-05-26 00:11 UTC
```
[home_scroll_perf__timeline_summary] [STDOUT] stdout:            05-25 16:29:15.033 W/System  ( 7300): ClassLoader referenced unknown path: /system/priv-app/ContactsProvider/lib/arm
[home_scroll_perf__timeline_summary] [STDOUT] stdout: [   +8 ms] executing: /opt/s/w/ir/cache/android/platform-tools/adb -s ZY223J893R shell am start -a android.intent.action.RUN -f 0x20000000 --ez enable-background-compilation true --ez enable-dart-profiling true --ez trace-startup true --ez start-paused true --ez verbose-logging true io.flutter.demo.gallery/io.flutter.demo.gallery.MainActivity
[home_scroll_perf__timeline_summary] [STDOUT] stdout: [ +970 ms] Starting: Intent { act=android.intent.action.RUN flg=0x20000000 cmp=io.flutter.demo.gallery/.MainActivity (has extras) }
[home_scroll_perf__timeline_summary] [STDOUT] stdout: [        ] Waiting for observatory port to be available...
```
https://ci.chromium.org/p/flutter/builders/prod/Mac_android%20home_scroll_perf__timeline_summary/1283

Is `flutter-devicelab-mac-21` device up and happy?

**Comment by godofredoc** [comment] 2021-06-17 22:21
@keyonghan can you please duplicate and close?

**Comment by keyonghan** [comment] 2021-06-18 18:25
Duplicate of https://github.com/flutter/flutter/issues/77193.

**Closed by keyonghan** 2021-06-18 18:25 UTC
Labels: P3, passed secondary triage, team: infra
