### ISSUE TITLE
This request has been blocked; the content must be served over HTTPS

### ISSUE THREAD

**Issue by byh000** [flutter/flutter#104820] opened 2022-05-27 11:14 UTC
I update webview_flutter version from 2.0+. to 3.0.4 .

When I set  navigationDelegate for webview, some url loaded  failed. 

Remove navigationDelegate, it will be Ok.

```

chromium(27325): [INFO:CONSOLE(0)] "Mixed Content: The page at 'https://s.click.ele.me/t_js?tu=https%3A%2F%2Fs.click.ele.me%2Ft%3Funion_lens%3DlensId%253AOPT%25401632908559%25402107df51_0832_17c30ef4622_03ee%254001%253BeventPageId%253A20150318020002597%26%26e%3D-s02ajFgIdlWj1XwWs5UIsKsrZ7QnwZZIU38EuBak7dwyz6ylggttLNb0BHx0Cfamvq7kS6q2N9P00uWAuOIi0QKKkbzG82LU780LWTlqBLgI3v55LTCxVl6AjLLb9lTANBwvt2wTOZR6ViOhOUDiFEAsIP9fSIiIuMhDs15f9WuzMYXxHfiLUFycuRJB3itu4y43vWGzZMvlAdP6D9q923BZMuzZ7UGTfEes1JAbMDXlQCa9xSVCiI2P8USLLlZu8KIi7s90hNW1w3RcOfTemRnazbNRFxMJqv8i4cF5TQNqhEoPqNSArDJO...igYgENzWrWoPDZ3ImelCkyMJ%26ref%3D%26et%3D-t021nb9PdYvdigYgENzWrWoPDZ3ImelCkyMJ%26ref%3D%26et%3D-t021nb9PdYvdigYgENzWrWoPDZ3ImelCkyMJ%26ref%3D%26et%3D-t021nb9PdYvdigYgENzWrWoPDZ3ImelCkyMJ%26ref%3D%26et%3D-t021nb9PdYvdigYgENzWrWoPDZ3ImelCkyMJ%26ref%3D%26et%3D-t021nb9PdYvdigYgENzWrWoPDZ3ImelCkyMJ%26ref%3D%26et%3D-t021nb9PdYvdigYgENzWrWoPDZ3ImelCkyMJ%26ref%3D%26et%3D-t021nb9PdYvdigYgENzWrWoPDZ3ImelCkyMJ%26ref%3D%26et%3D-t021ni97bmAGA9nlHeA8S1gGFrKwMEaDRA8T%26ref%3D%26et%3D-t021ni97bmAGA9nlHeA8S1gGFrKwMEaDRA8T' was loaded over HTTPS, but requested an insecure favicon 'http://err.taobao.com/error1.html'. This request has been blocked; the content must be served over HTTPS.

```

```

[✓] Flutter (Channel unknown, 2.8.1, on macOS 11.4 20F71 darwin-x64, locale zh-Hans-CN)
    • Flutter version 2.8.1 at /Users/byh000/dev/flutter
    • Upstream repository unknown
    • Framework revision 77d935af4d (5 months ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/byh000/Library/Android/sdk
    • Platform android-32, build-tools 30.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] Connected device (2 available)
    • M2102K1AC (mobile) • c5a9d83d • android-arm64  • Android 12 (API 31)
    • Chrome (web)       • chrome   • web-javascript • Google Chrome 102.0.5005.61

```

**Comment by darshankawar** [comment] 2022-05-27 12:07
@byh000 
Looking at the error you shared, take a look at this open issue which probably describes the same case, #43595. You may follow-up in it for further reference.

Also, check out this SO link for a workaround / solution, https://stackoverflow.com/questions/66796932/is-it-possible-to-allow-mixed-content-in-flutter-webview

Closing this as duplicate of 43595. If you disagree, write in comments and I'll reopen it.
Thanks.

**Closed by darshankawar** 2022-05-27 12:07 UTC
Labels: in triage
