### ISSUE TITLE
creating flutter application with cmd

### ISSUE THREAD

**Issue by gbbest15** [flutter/flutter#71823] opened 2020-12-07 05:43 UTC
i run flutter command to create flutter project with 

flutter create App

but it keep given me error like

Oops; flutter has exited unexpectedly: "FileSystemException: Cannot copy file to 'C:\Users\Rs
Technology\Desktop\first_flutter_porject\android\app\src\main\res\mipmap-hdpi\ic_launcher.png', path =
'C:\flutter\packages\flutter_tools\templates\app\android.tmpl\app\src\main\res\mipmap-hdpi\ic_launcher.png' (OS Error:
Access is denied.
, errno = 5)".

**Comment by iapicca** [comment] 2020-12-07 08:44
possible duplicate of https://github.com/flutter/flutter/issues/69116

**Comment by pedromassangocode** [comment] 2020-12-07 10:52
Definitely a duplicate of https://github.com/flutter/flutter/issues/69116.

**Closed by pedromassangocode** 2020-12-07 10:52 UTC
