### ISSUE TITLE
TextOverflow.ellipsis shows fading-out text behind the ellipsis

### ISSUE THREAD

**Issue by DaveShuckerow** [flutter/flutter#4641] opened 2016-06-20 22:16 UTC
```
new Text('Very long text name that extends past the bounds of the view', 
    softwrap: false, 
    overflow: TextOverflow.ellipsis);
```
will fade off the edge of the screen and put an ellipsis on the fading text, instead of blocking that text out and putting the ellipsis.

It would look much nicer if we could compute the number of characters we could render in the text's width minus the length of the ellipsis, and then only show those characters plus the ellipsis.  This would also make it possible to, instead of a postfix ellipsis, do a prefix ellipsis or an in-fix ellipsis:
`Very long text name that extends past the boun...`
`... name that extends past the bounds of the view`
`Very long text name th...t the bounds of the view`

Flutter doctor:
[✓] Flutter (on Mac OS, channel master)
    • Flutter at /Users/djshuckerow/.flutter
    • Framework revision 661740d2d6 (5 days ago), engine revision 864beb8d26

[✓] iOS toolchain - develop for iOS devices (Xcode 7.3.1)
    • XCode at /Applications/Xcode.app/Contents/Developer
    • Xcode 7.3.1, Build version 7D1014

[✓] Atom - a lightweight development environment for Flutter
    • flutter plugin version 0.2.3
    • dartlang plugin version 0.6.26

**Comment by Hixie** [comment] 2016-06-20 22:20
In theory, this is an intractable problem. (Suppose you have a font where "abcd", "abc", "ab", and "a" are all ligatures where the fewer characters you have, the wider the glyph is. Now suppose the string you're trying to show is "abcd", and it doesn't fit. What do you do?)

But we can probably do a not perfect solution that's good enough in most cases. Just keep trimming characters until appending the ellipsis fits. It'll be pretty slow, and will fail to display anything in pathological cases, but it's probably fast enough in the common case.

**Comment by Hixie** [comment] 2016-06-20 22:20
(If we add this, we should keep our existing solutions as well.)

**Comment by DaveShuckerow** [comment] 2016-06-20 22:55
That sounds reasonable.

Note: the suggestion about computing ellipsis position is somewhat unrelated to the issue I'm currently having.  I'm sending you a screencap via carrier pigeon.

**Comment by Hixie** [comment] 2016-06-21 00:46
This is a dupe of https://github.com/flutter/flutter/issues/4478 so I'm going to close it as such.

In that bug, another option is proposed: rather than truncating individual characters until it fit, we would truncate entire glyphs (ligatures) until it fit. That would have the advantage of being much more performant. It would have the disadvantage of truncating the entire word if the whole line was one ligature (e.g. if your line was the word "Zapfino" in the Zapfino font, and it overflowed at the "o", we would replace the whole thing with a "...", rather than just the "no".)

**Closed by Hixie** 2016-06-21 00:46 UTC
