### ISSUE TITLE
Stopping a debug session does not terminate the app on iOS

### ISSUE THREAD

**Issue by DanTup** [flutter/flutter#52232] opened 2020-03-09 11:33 UTC
When running an app on the iOS Simulator in debug mode (eg. `flutter run --start-paused`), the app is not terminated on the device when you stop (send an `app.stop` request). This happens even if the app is not paused at the time.

To repro:

- Open a Flutter app in Android Studio or VS Code (both have same behaviour)
- Run the app on iOS Simulator) without debugging ("Start without debugging" in VS Code, or the green triangle run button in Android Studio)
- After the app appears, click the Stop Debugging button
- Note that the app closes on the Simulator
- Re-run the app with debugging (the bug icon in Android Studio, or Start Debugging in VS Code)
- After the app appears, click the Stop Debugging button
- Note that the app remains open in the simulator

Looking at the logs in VS Code, the `--start-paused` flag is the only thing I can see that's difference in these cases, so I think something it's doing is changing the behaviour when `app.stop` is sent.

(moved from https://github.com/Dart-Code/Dart-Code/issues/2291)

**Comment by jmagman** [comment] 2020-03-09 20:07
I thought we had another issue for this but I can't find it at the moment.

**Comment by jonahwilliams** [comment] 2020-03-09 20:21
I think we have an issue for physical iOS devices filled in 2016, but not one for simulators - possibly a similar issue though

**Comment by DanTup** [comment] 2020-03-09 20:23
FWIW I don't have a physical iOS device to test, so when I put "iOS Simulator" in the subject it was mostly because it doesn't happen for Android Simulators (so it may be the same issue as for a physical device).

**Comment by mikeRozen** [comment] 2020-10-22 19:44
Confirm this issue still exists unfortunately

**Comment by jmagman** [comment] 2020-10-23 18:22
I just tried this on Flutter master in Android Studio and the stop button quit the app.  Am I missing repro steps, @DanTup?

[stop-sim-app.mov.zip](https://github.com/flutter/flutter/files/5431131/stop-sim-app.mov.zip)

```
$ flutter doctor -v 
[✓] Flutter (Channel master, 1.24.0-4.0.pre.37, on Mac OS X 10.15.7 19H2 darwin-x64, locale en-US)
    • Flutter version 1.24.0-4.0.pre.37 at /Users/magder/Projects/flutter
    • Framework revision cb67513f29 (79 minutes ago), 2020-10-23 10:00:56 -0700
    • Engine revision defa8be2b1
    • Dart version 2.11.0 (build 2.11.0-242.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/magder/Library/Android/sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Users/magder/Applications/Xcode-12-2-beta3.app/Contents/Developer
    • Xcode 12.2, Build version 12B5035g
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[✓] Connected device (1 available)
    • iPhone 12 mini (mobile) • 9A6E52CB-E5AC-4DC1-8846-9E86985E8AE2 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-2 (simulator)

• No issues found!
```

**Comment by DanTup** [comment] 2020-10-26 12:17
Same for me in VS Code - so as far as I can see, it's no longer an issue. I tested with iOS Simulator, current Flutter master (today) and latest VS Code + extensions.

@mikeRozen if you're still seeing this, can you confirm Flutter version/device and how you're testing?

**Comment by MikePendo** [comment] 2021-09-21 08:42
Sorry for the late response yes I still see it on IOS simulator. (android studio)
`Flutter 2.3.0-17.0.pre.397 • channel master • git@github.com:MikePendo/flutter.git
Framework • revision 03034e9e4a (3 months ago) • 2021-06-18 00:14:03 -0700
Engine • revision ced58ef9c1
Tools • Dart 2.14.0 (build 2.14.0-217.0.dev)
`

**Comment by DanTup** [comment] 2021-09-21 08:59
@jmagman I see the same with Flutter 2.5.0 in both VS Code and Android Studio now (using a new project created using `flutter create` from 2.5.0). The output from the `flutter run` process all seems normal with no errors and claims to have shut down cleanly.

```
[9:52:33 AM] [FlutterRun] <== [+125266 ms] DevFS: Deleting filesystem on the device (file:///Users/danny/Library/Developer/CoreSimulator/Devices/4B9D86FA-8A60-4903-A7C9-FF170548A059/data/Containers/Data/Application/9F9BC3E3-B578-4423-94A1-9A64909F1B71/tmp/flutter_application_5soa97y/flutter_application_5/)
[9:52:33 AM] [FlutterRun] <== [   +5 ms] DevFS: Deleted filesystem on the device (file:///Users/danny/Library/Developer/CoreSimulator/Devices/4B9D86FA-8A60-4903-A7C9-FF170548A059/data/Containers/Data/Application/9F9BC3E3-B578-4423-94A1-9A64909F1B71/tmp/flutter_application_5soa97y/flutter_application_5/)
[9:52:33 AM] [FlutterRun] <== [   +3 ms] Application finished.
[9:52:33 AM] [FlutterRun] <== [{"event":"app.stop","params":{"appId":"fc87f109-4a3e-47c0-be81-8c4f0e58698c"}}]
[9:52:33 AM] [FlutterRun] Process terminated! null, SIGTERM
[9:52:33 AM] [FlutterRun] <== [   +5 ms] "flutter run" took 139,111ms.
[9:52:33 AM] [FlutterRun] <== [   +4 ms] Running shutdown hooks
[9:52:33 AM] [FlutterRun] <== [        ] Shutdown hooks complete
[9:52:33 AM] [VmService] VM service connection closed: 1005 ()
[9:52:33 AM] [FlutterRun] <== [{"id":"3","result":true}]
[9:52:33 AM] [FlutterRun] <== [  +11 ms] exiting with code 0
```

**Comment by mc-jenia** [comment] 2021-09-28 15:57
did you solve this issue?

**Comment by ksilz** [comment] 2022-01-08 17:59
Same here. It used to work on my previous Intel Mac with Flutter 2.5. But on my M1 Max MacBook Pro with Flutter 2.8.1 on macOS 12.1, here's what happens if I stop the runner in IntelliJ IntelliJ IDEA 2021.3.1 (Ultimate Edition; Build #IU-213.6461.79):
- The process in IntelliJ stops.
- The app continues to run in the iPhone simulator.
- I manually kill the app in the iPhone simulator.
- macOS shows my a problem report about "Runner" (which I think is the app that I just killed).

**Comment by alotaiba** [comment] 2022-01-26 23:33
> Same here. It used to work on my previous Intel Mac with Flutter 2.5. But on my M1 Max MacBook Pro with Flutter 2.8.1 on macOS 12.1, here's what happens if I stop the runner in IntelliJ IntelliJ IDEA 2021.3.1 (Ultimate Edition; Build #IU-213.6461.79):
> 
> * The process in IntelliJ stops.
> * The app continues to run in the iPhone simulator.
> * I manually kill the app in the iPhone simulator.
> * macOS shows me a problem report about "Runner" (which I think is the app that I just killed).

I have the exact same issue on M1 MacBook Air:

```
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.1 21C52 darwin-arm, locale en-QA)
    • Flutter version 2.8.1 at /Users/abdulrahman/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (6 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/abdulrahman/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.32.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 97.0.4692.99

• No issues found!
```

**Comment by PaulRudin** [comment] 2022-04-01 09:33
I am seeing this just with "flutter run" on an M1 mac mini, without the "--start-paused" and without using an IDE to launch.

**Comment by chornbe** [comment] 2022-04-24 19:55
Still an issue.

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.4, on macOS 12.3.1 21E258 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.66.2)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

**Comment by exaby73** [comment] 2022-07-12 13:02
I can reproduce this issue in the current stable and master

<details><summary><code>flutter doctor -v</code> (Stable)</summary>

```
[✓] Flutter (Channel stable, 3.0.4, on macOS 12.4 21F79 darwin-arm, locale en-US)
    • Flutter version 3.0.4 at /Users/nabeelparkar/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 85684f9300 (12 days ago), 2022-06-30 13:22:47 -0700
    • Engine revision 6ba2af10bb
    • Dart version 2.17.5
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/nabeelparkar/Library/Android/sdk/
    • Platform android-33, build-tools 33.0.0-rc4
    • ANDROID_SDK_ROOT = /Users/nabeelparkar/Library/Android/sdk/
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /Applications/Brave Browser.app/Contents/MacOS/Brave Browser

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 69.0.4
    • Dart plugin version 221.5921.27

[✓] VS Code (version 1.68.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.42.0

[✓] Connected device (3 available)
    • iPhone 13 Pro Max (mobile) • 16B8F156-111C-489F-A6E5-2D79142036B4 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-5 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)               • chrome                               • web-javascript • Brave Browser 103.1.40.113

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

<details><summary><code>flutter doctor -v</code> (Master)</summary>

```
[✓] Flutter (Channel master, 3.1.0-0.0.pre.1616, on macOS 12.4 21F79 darwin-arm, locale en-US)
    • Flutter version 3.1.0-0.0.pre.1616 on channel master at /Users/nabeelparkar/fvm/versions/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ecfe51e652 (77 minutes ago), 2022-07-12 07:45:06 -0400
    • Engine revision 3cab418bb6
    • Dart version 2.18.0 (build 2.18.0-271.0.dev)
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/nabeelparkar/Library/Android/sdk/
    • Platform android-33, build-tools 33.0.0-rc4
    • ANDROID_SDK_ROOT = /Users/nabeelparkar/Library/Android/sdk/
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13F100
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /Applications/Brave Browser.app/Contents/MacOS/Brave Browser

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 69.0.4
    • Dart plugin version 221.5921.27

[✓] VS Code (version 1.68.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.42.0

[✓] Connected device (3 available)
    • iPhone 13 Pro Max (mobile) • 16B8F156-111C-489F-A6E5-2D79142036B4 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-5 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)               • chrome                               • web-javascript • Brave Browser 103.1.40.113

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by kika** [comment] 2022-08-10 21:37
I have the same issue as @PaulRudin above. M1MAX Macbook Pro, iOS Simulator, running `flutter run -d <iOS simulator ID>` from command line. Pressing `q` stops flutter but the app keeps going on the simulator (and it's functional). Latest stable.

<details>
  <summary>flutter doctor -v</summary>
  
  ```
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.5 21G72 darwin-arm, locale en-US)
    • Flutter version 3.0.5 at /Users/kika/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (4 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/kika/Library/Android/sdk
    • Platform android-31, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.70.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.46.0

[✓] Connected device (3 available)
    • iPad Air (5th generation) (mobile) • 9408CD29-DC69-4366-8CE3-1D44A2C2A1A5 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-5 (simulator)
    • macOS (desktop)                    • macos                                • darwin-arm64   • macOS 12.5 21G72 darwin-arm
    • Chrome (web)                       • chrome                               • web-javascript • Google Chrome 104.0.5112.79

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
  ```
</details>

**Comment by Stef-GMS** [comment] 2022-08-11 02:42
I'm seeing the same issue from terminal and Android Studio.  When I run from IntelliJ it works.

MacBook Pro M1 Max running Flutter Beta 3.3.0-0.2.pre on macOS 12.5 

flutter doctor -v
[✓] Flutter (Channel beta, 3.3.0-0.2.pre, on macOS 12.5 21G72 darwin-arm, locale en-US)
    • Flutter version 3.3.0-0.2.pre on channel beta at /Users/Stef/Apps_Dev_Space/_Google/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7ac27ac8e6 (8 days ago), 2022-08-02 14:35:08 -0700
    • Engine revision d1e7dc18bf
    • Dart version 2.18.0 (build 2.18.0-271.4.beta)
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/Stef/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13F17a
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 67.1.4
    • Dart plugin version 221.5591.58

[✓] VS Code (version 1.70.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.46.0

[✓] Connected device (3 available)
    • iPhone SE (3rd generation) (mobile) • 27109987-D82E-4F53-87E1-DA7AA0EFF70C • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-15-5 (simulator)
    • macOS (desktop)                     • macos                                • darwin-arm64   • macOS 12.5 21G72
      darwin-arm
    • Chrome (web)                        • chrome                               • web-javascript • Google Chrome
      104.0.5112.79

[✓] HTTP Host Availability
    • All required HTTP hosts are available

**Comment by ksilz** [comment] 2022-08-11 11:00
Has continued to happen for me with all Flutter versions since at least January when [I made my initial comments](https://github.com/flutter/flutter/issues/52232#issuecomment-1008080655) - M1 Max MacBook Pro, latest Flutter stable version (currently at 3.0.5), latest macOS version (currently at Monterey 12.5): When I start Flutter on an iOS simulator from IntelliJ and stop it in IntelliJ, it **always** goes on running in the simulator. And at least right now, the same is true when launching my app from the terminal.

**Comment by exaby73** [comment] 2022-10-26 12:40
I can confirm that this issue is fixed in the latest master. Closing this issue as fixed

**Comment by jmagman** [comment] 2022-10-27 00:25
@exaby73 if you were testing on a simulator, unfortunately I had to revert https://github.com/flutter/flutter/pull/114083.  Should re-land it shortly https://github.com/flutter/flutter/pull/114114

**Comment by exaby73** [comment] 2022-10-27 07:26
@jmagman Thanks for the clarification. Reopening this issue until the fix lands :)

**Closed** 2022-10-27 22:06 UTC
Labels: platform-ios, tool, a: debugging, has reproducible steps, P4, found in release: 3.0, found in release: 3.1
