### ISSUE TITLE
Screen freezes or crashes on pixel2 after upgrade to latest stable

### ISSUE THREAD

**Issue by remonh87** [flutter/flutter#36352] opened 2019-07-17 09:00 UTC
## Steps to Reproduce
When we run a screen containing our recursive_image widget the screen freezes or our app even crashes. This happens after we upgraded from flutter version v1.5.4-hotfix.2 to v1.7.8+hotfix.3

Recursive widget can be found here:
https://gist.github.com/remonh87/378fefbc89d3f160509f4b474eff7c77

1. Create a simple app containing some text and that uses the recursivewidget. e.g.

```
Center(child: RecursiveImage(
                recursionDepth: 2,
               //simple screen can be a simple screen e.g. refer to counter counter
                builder: (_, image) => SimpleScreen(
                  viewModel: viewModel,
                  image: image,
                ),
),
```

2. Run the screen and the app either crashes or freezes.

## Logs
Crash log (happens one out of 3 attempts):
`W/Adreno-GSL(15095): <gsl_ldd_control:549>: ioctl fd 60 code 0xc040094a (IOCTL_KGSL_GPU_COMMAND) failed: errno 71 Protocol error
W/Adreno-GSL(15095): <log_gpu_snapshot:458>: panel.gpuSnapshotPath is not set.not generating user snapshot
W/Adreno-GSL(15095): <gsl_ldd_control:549>: ioctl fd 60 code 0xc040094a (IOCTL_KGSL_GPU_COMMAND) failed: errno 71 Protocol error
W/Adreno-GSL(15095): <log_gpu_snapshot:458>: panel.gpuSnapshotPath is not set.not generating user snapshot
W/Adreno-GSL(15095): <gsl_ldd_control:549>: ioctl fd 60 code 0xc040094a (IOCTL_KGSL_GPU_COMMAND) failed: errno 71 Protocol error
W/Adreno-GSL(15095): <log_gpu_snapshot:458>: panel.gpuSnapshotPath is not set.not generating user snapshot
W/Adreno-GSL(15095): <gsl_ldd_control:549>: ioctl fd 60 code 0xc040094a (IOCTL_KGSL_GPU_COMMAND) failed: errno 35 Resource deadlock would occur
W/Adreno-GSL(15095): <log_gpu_snapshot:458>: panel.gpuSnapshotPath is not set.not generating user snapshot`

## Flutter doctor output
```
[✓] Flutter (Channel unknown, v1.7.8+hotfix.3, on Mac OS X 10.14.5 18F132, locale en-NL)
    • Flutter version 1.7.8+hotfix.3 at /Users/user/huedlc/hue_blue/dev/flutter
    • Framework revision b712a172f9 (8 days ago), 2019-07-09 13:14:38 -0700
    • Engine revision 54ad777fd2
    • Dart version 2.4.0


[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/user/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/user/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • CocoaPods version 1.7.2

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 36.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] Android Studio
    • Android Studio at /Applications/Android Studio 3.5 Preview.app/Contents
    • Flutter plugin version 36.1.1
    • Dart plugin version 191.7830
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Community Edition (version 2019.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 37.0.3
    • Dart plugin version 191.7830

[✓] VS Code (version 1.28.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.15.0

[✓] Connected device (4 available)
    • Pixel 2   • <123>                         • android-arm64  • Android 10 (API 29)
```

**Comment by Hixie** [comment] 2019-07-23 23:43
cc @jason-simmons if you have the time, can you see if you can track this down? sounds like it's a regression.

**Comment by jason-simmons** [comment] 2019-07-24 20:18
Do you have any more info on how to reproduce this?

I tried creating a default template app, copying the `RecursiveImage` class, and replacing the `SizedBox` with an `Image.asset`.  I then instantiated a few `RecursizeImages` in the app's layout:
```
            RecursiveImage(
                recursionDepth: 3,
                builder: (_, image) => image,
            ),
```

Ran this on a Pixel 2 XL with Android 8.0.1.  The app worked as expected, and I didn't see any logs from Skia or the GL drivers.  I tried both the current master branch of Flutter and `v1.7.8+hotfix.3`.

**Comment by remonh87** [comment] 2019-07-26 07:10
@jason-simmons  thanks for looking into this. I created an app that contains the crash: https://github.com/remonh87/recursive_image_repro

**Comment by jason-simmons** [comment] 2019-07-26 22:44
I reproduced this on a Pocophone F1.  The recursive_image_repro app results in GPU driver error logs and crashes.

Did a bisect and found that this started at this change to Skia: https://github.com/google/skia/commit/08b260c27b519ac8fb17b3ff8ddccf4a2ac0e278

**Comment by lhkbob** [comment] 2019-07-29 20:56
We have found that the issue is caused by a combination of the rotation transform and the blur backdrop filter of the in progress widget. Given this limitation, limiting transforms to just scales and translates will let still render recursive backdrop blurs without crashing the GPU.

A key part of the Skia linked above was to fix backdrop filters so that they applied the blurring and filtering in the proper, local coordinate system. In this particular case, the blurs with the same X and Y blur radii won't look any different before or after. Unfortunately, our image filtering API doesn't expose enough information to detect this case and optimize away the rotation components of the transform.

For reasons yet unknown, the new backdrop code path tickles what appears to be a driver bug on Adreno drivers but we haven't found a simple workaround. That being said, I am currently working on a much larger overhaul of the image filtering code in Skia, which will hopefully bypass this issue. I do not have a time estimate for that yet, though.

**Comment by Hixie** [comment] 2019-07-31 00:01
@jason-simmons Did you file an upstream bug or reach out to the Skia team about this? (No worries if you didn't, I just don't want to file a duplicate bug.)

**Comment by jason-simmons** [comment] 2019-07-31 00:07
We've discussed this with Skia (see the response from @lhkbob)

**Comment by Hixie** [comment] 2019-08-01 17:32
Ah, thanks missed that.

So the status here is that we are waiting for the overhaul of the related area of code in Skia.
@lhkbob do you have a bug# for the overhaul that we can follow?

**Comment by lhkbob** [comment] 2019-08-02 21:45
The overall tracker for our image filter overhaul is here: https://skbug.com/9279. The components that would address this issue hopefully are https://skbug.com/9074 and https://skbug.com/9283

**Comment by Hixie** [comment] 2019-08-13 23:49
@lhkbob Is it ok if I assign this to you? Do you have a (conservative) estimate of when this will be addressed? (Just for tracking purposes.)

**Comment by lhkbob** [comment] 2019-08-14 20:33
Yes, that is ok. I have an aggressive goal to have this addressed by the first week of September.

**Comment by lhkbob** [comment] 2019-08-29 20:07
Our working hypothesis has been that these crashes on Android devices are triggered by the same temporary image change that caused severe performance regression on iOS devices. I have landed https://skia-review.googlesource.com/c/skia/+/237904 and it has rolled into the flutter engine. This CL should bring the image allocation behavior back to more like before the regression CL landed.

However, I haven't confirmed this. If someone can test that it no longer crashes when using the ToT flutter engine, then we can close this.

**Comment by lhkbob** [comment] 2019-09-09 18:09
The other Android/iOS bugs have been fixed with my recent changes, so I would expect that this issue is resolved as well.  @remonh87, If you can test with Flutter ToT, that would be appreciated and let me know if I can close this out, or if there is something else going on in your case.

**Comment by remonh87** [comment] 2019-09-09 18:49
@lhkbob thanks for the fix. I am not familiar with the term Flutter ToT . Which version or branch do I need to grab in order to test it?

**Comment by lhkbob** [comment] 2019-09-10 17:16
ToT refers to tip of tree, so if you're able to test with the 'master' channel it will see these Skia changes. https://github.com/flutter/flutter/wiki/Flutter-build-release-channels

**Comment by remonh87** [comment] 2019-09-11 06:56
@lhkbob  Great news! I did test the issue on master branch  and it is solved now. I propose to close the issue

**Comment by cachapa** [comment] 2019-09-11 07:56
Confirm that it's working for me in the master channel.

**Comment by kf6gpe** [comment] 2019-09-16 16:59
Closing per @cachapa's comment. Feel free to reopen if I'm wrong. Thanks!

**Closed by kf6gpe** 2019-09-16 16:59 UTC
Labels: customer: solaris, dependency: skia, engine, severe: customer critical, severe: regression
