### ISSUE TITLE
Unable to generate build files for Linux

### ISSUE THREAD

**Issue by muezz** [flutter/flutter#104239] opened 2022-05-20 09:04 UTC
## Issue

My app used to compile/build without any issues on all platforms. A few weeks back, my operating system, Pop OS, upgraded from 21.10 to 22.04. Other than that, I do not remember anything else changing within my local machine where I code. Since then, I have been unable to build/run my app in linux. Keep in mind that my app still builds and runs perfectly fine on other platforms.

Below, you can find two methods. One is simple "run without debugging" and the other is the build command for the terminal. Both produce the same output but I have mentioned both of them here. I do not suspect any issue in my code as it ran flawlessly before. But if you need me to share it, I can.

Furthermore, I do a completly fresh install of my OS every couple months. I did one yesterday and installed all necessary SDKs, etc. hoping that maybe a fresh install of Flutter might fix this. I am still getting the exact same error.

### Case A
1. Press `CTRL` + `F5`

### Case B
1. Execute `flutter build linux`

</details>

<details>
  <summary>Logs</summary>

### Case A (from the debug console)

```
Launching lib/main.dart on Linux in debug mode...
lib/main.dart:1
CMake Error at /snap/flutter/111/usr/share/cmake-3.10/Modules/CMakeTestCXXCompiler.cmake:45 (message):
  The C++ compiler

    "/snap/flutter/current/usr/bin/clang++"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /home/abdulmuezz/Documents/flutter_projects/franchise_manager/build/linux/x64/debug/CMakeFiles/CMakeTmp

    Run Build Command:"/snap/flutter/current/usr/bin/ninja" "cmTC_f7ee3"
    [1/2] Building CXX object CMakeFiles/cmTC_f7ee3.dir/testCXXCompiler.cxx.o
    [2/2] Linking CXX executable cmTC_f7ee3
    FAILED: cmTC_f7ee3 
    : && /snap/flutter/current/usr/bin/clang++    -L/snap/flutter/current/usr/lib/gcc/x86_64-linux-gnu/8 -L/snap/flutter/current/usr/lib/x86_64-linux-gnu -lblkid -lgcrypt -llzma -lpthread -ldl -L/snap/flutter/current/usr/lib/ CMakeFiles/cmTC_f7ee3.dir/testCXXCompiler.cxx.o  -o cmTC_f7ee3   && :
    /snap/flutter/current/usr/bin/ld: warning: /usr/lib/gcc/x86_64-linux-gnu/11/../../../x86_64-linux-gnu/crt1.o: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0008002
    /usr/lib/gcc/x86_64-linux-gnu/11/../../../x86_64-linux-gnu/libgcc_s.so.1: undefined reference to `_dl_find_object@GLIBC_2.35'
    //lib/x86_64-linux-gnu/libgpg-error.so.0: undefined reference to `__libc_single_threaded@GLIBC_2.32'
    //lib/x86_64-linux-gnu/libgpg-error.so.0: undefined reference to `pthread_mutex_trylock@GLIBC_2.34'
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    ninja: build stopped: subcommand failed.




  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:3 (project)


Exception: Unable to generate build files
Exited (sigterm)
```

### Case B (from the terminal output)

```
abdulmuezz@pop-os:~/Documents/flutter_projects/franchise_manager$ flutter build linux

💪 Building with sound null safety 💪

CMake Error at /snap/flutter/111/usr/share/cmake-3.10/Modules/CMakeTestCXXCompiler.cmake:45 (message):
  The C++ compiler

    "/snap/flutter/current/usr/bin/clang++"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /home/abdulmuezz/Documents/flutter_projects/franchise_manager/build/linux/x64/release/CMakeFiles/CMakeTmp

    Run Build Command:"/snap/flutter/current/usr/bin/ninja" "cmTC_5628c"
    [1/2] Building CXX object CMakeFiles/cmTC_5628c.dir/testCXXCompiler.cxx.o
    [2/2] Linking CXX executable cmTC_5628c
    FAILED: cmTC_5628c 
    : && /snap/flutter/current/usr/bin/clang++    -L/snap/flutter/current/usr/lib/gcc/x86_64-linux-gnu/8 -L/snap/flutter/current/usr/lib/x86_64-linux-gnu -lblkid -lgcrypt -llzma -lpthread -ldl -L/snap/flutter/current/usr/lib/ -L/snap/flutter/current/usr/lib/gcc/x86_64-linux-gnu/8 -L/snap/flutter/current/usr/lib/x86_64-linux-gnu -lblkid -lgcrypt -llzma -lpthread -ldl -L/snap/flutter/current/usr/lib/ CMakeFiles/cmTC_5628c.dir/testCXXCompiler.cxx.o  -o cmTC_5628c   && :
    /snap/flutter/current/usr/bin/ld: warning: /usr/lib/gcc/x86_64-linux-gnu/11/../../../x86_64-linux-gnu/crt1.o: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0008002
    /usr/lib/gcc/x86_64-linux-gnu/11/../../../x86_64-linux-gnu/libgcc_s.so.1: undefined reference to `_dl_find_object@GLIBC_2.35'
    //lib/x86_64-linux-gnu/libgpg-error.so.0: undefined reference to `__libc_single_threaded@GLIBC_2.32'
    //lib/x86_64-linux-gnu/libgpg-error.so.0: undefined reference to `pthread_mutex_trylock@GLIBC_2.34'
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    ninja: build stopped: subcommand failed.




  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:3 (project)


Building Linux application...                                           
Unable to generate build files
```
### Executing `flutter run --verbose`
```
[  +66 ms] executing: uname -m
[  +33 ms] Exit code 0 from: uname -m
[        ] x86_64
[   +6 ms] executing: [/home/abdulmuezz/snap/flutter/common/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +6 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] ee4e09cce01d6f2d7f4baebd247fde02e5008851
[        ] executing: [/home/abdulmuezz/snap/flutter/common/flutter/] git tag --points-at ee4e09cce01d6f2d7f4baebd247fde02e5008851
[  +16 ms] Exit code 0 from: git tag --points-at ee4e09cce01d6f2d7f4baebd247fde02e5008851
[        ] 3.0.0
[  +12 ms] executing: [/home/abdulmuezz/snap/flutter/common/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +5 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/home/abdulmuezz/snap/flutter/common/flutter/] git ls-remote --get-url origin
[   +6 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +119 ms] executing: [/home/abdulmuezz/snap/flutter/common/flutter/] git rev-parse --abbrev-ref HEAD
[   +7 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +75 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +93 ms] executing: /home/abdulmuezz/Android/Sdk/platform-tools/adb devices -l
[  +45 ms] List of devices attached
[   +6 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +91 ms] Multiple devices found:
[ +881 ms] Linux (desktop) • linux  • linux-x64      • Pop!_OS 22.04 LTS 5.17.5-76051705-generic
[        ] Chrome (web)    • chrome • web-javascript • Chromium 101.0.4951.64 snap
[        ] [1]: Linux (linux)
[        ] [2]: Chrome (chrome)
[   +1 ms] Please choose one (To quit, press "q/Q")
[        ] : 
[+8560 ms] 1
[  +37 ms] Skipping pub get: version match.
[  +89 ms] Found plugin move_to_background at /home/abdulmuezz/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/move_to_background-1.0.2/
[  +12 ms] Found plugin path_provider at /home/abdulmuezz/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider-2.0.10/
[   +3 ms] Found plugin path_provider_android at /home/abdulmuezz/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_android-2.0.14/
[   +2 ms] Found plugin path_provider_ios at /home/abdulmuezz/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_ios-2.0.9/
[   +2 ms] Found plugin path_provider_linux at /home/abdulmuezz/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_linux-2.1.6/
[   +4 ms] Found plugin path_provider_macos at /home/abdulmuezz/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_macos-2.0.6/
[   +4 ms] Found plugin path_provider_windows at /home/abdulmuezz/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_windows-2.0.6/
[  +29 ms] Found plugin uni_links at /home/abdulmuezz/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/uni_links-0.5.1/
[   +4 ms] Found plugin uni_links_web at /home/abdulmuezz/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/uni_links_web-0.1.0/
[   +5 ms] Found plugin url_launcher at /home/abdulmuezz/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher-6.1.2/
[   +2 ms] Found plugin url_launcher_android at /home/abdulmuezz/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_android-6.0.17/
[   +2 ms] Found plugin url_launcher_ios at /home/abdulmuezz/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_ios-6.0.16/
[   +4 ms] Found plugin url_launcher_linux at /home/abdulmuezz/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_linux-3.0.1/
[   +4 ms] Found plugin url_launcher_macos at /home/abdulmuezz/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_macos-3.0.1/
[   +5 ms] Found plugin url_launcher_web at /home/abdulmuezz/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_web-2.0.11/
[   +2 ms] Found plugin url_launcher_windows at /home/abdulmuezz/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_windows-3.0.1/
[  +99 ms] Found plugin move_to_background at /home/abdulmuezz/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/move_to_background-1.0.2/
[   +3 ms] Found plugin path_provider at /home/abdulmuezz/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider-2.0.10/
[   +1 ms] Found plugin path_provider_android at /home/abdulmuezz/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_android-2.0.14/
[        ] Found plugin path_provider_ios at /home/abdulmuezz/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_ios-2.0.9/
[        ] Found plugin path_provider_linux at /home/abdulmuezz/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_linux-2.1.6/
[        ] Found plugin path_provider_macos at /home/abdulmuezz/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_macos-2.0.6/
[   +1 ms] Found plugin path_provider_windows at /home/abdulmuezz/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_windows-2.0.6/
[  +10 ms] Found plugin uni_links at /home/abdulmuezz/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/uni_links-0.5.1/
[   +1 ms] Found plugin uni_links_web at /home/abdulmuezz/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/uni_links_web-0.1.0/
[   +1 ms] Found plugin url_launcher at /home/abdulmuezz/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher-6.1.2/
[   +1 ms] Found plugin url_launcher_android at /home/abdulmuezz/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_android-6.0.17/
[   +1 ms] Found plugin url_launcher_ios at /home/abdulmuezz/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_ios-6.0.16/
[        ] Found plugin url_launcher_linux at /home/abdulmuezz/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_linux-3.0.1/
[   +2 ms] Found plugin url_launcher_macos at /home/abdulmuezz/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_macos-3.0.1/
[   +3 ms] Found plugin url_launcher_web at /home/abdulmuezz/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_web-2.0.11/
[   +1 ms] Found plugin url_launcher_windows at /home/abdulmuezz/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_windows-3.0.1/
[  +85 ms] Generating /home/abdulmuezz/Documents/flutter_projects/franchise_manager/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[ +133 ms] Initializing file store
[  +12 ms] Skipping target: gen_localizations
[   +4 ms] gen_dart_plugin_registrant: Starting due to {InvalidatedReasonKind.inputChanged: The following inputs have updated contents:
/home/abdulmuezz/Documents/flutter_projects/franchise_manager/.dart_tool/package_config_subset,/home/abdulmuezz/Documents/flutter_projects/franchise_manager/.dart_tool/flutter_build/dart_plug
in_registrant.dart}
[  +43 ms] Found plugin move_to_background at /home/abdulmuezz/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/move_to_background-1.0.2/
[   +2 ms] Found plugin path_provider at /home/abdulmuezz/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider-2.0.10/
[   +1 ms] Found plugin path_provider_android at /home/abdulmuezz/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_android-2.0.14/
[   +1 ms] Found plugin path_provider_ios at /home/abdulmuezz/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_ios-2.0.9/
[   +1 ms] Found plugin path_provider_linux at /home/abdulmuezz/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_linux-2.1.6/
[   +1 ms] Found plugin path_provider_macos at /home/abdulmuezz/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_macos-2.0.6/
[   +1 ms] Found plugin path_provider_windows at /home/abdulmuezz/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_windows-2.0.6/
[  +19 ms] Found plugin uni_links at /home/abdulmuezz/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/uni_links-0.5.1/
[   +2 ms] Found plugin uni_links_web at /home/abdulmuezz/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/uni_links_web-0.1.0/
[   +2 ms] Found plugin url_launcher at /home/abdulmuezz/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher-6.1.2/
[   +1 ms] Found plugin url_launcher_android at /home/abdulmuezz/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_android-6.0.17/
[   +1 ms] Found plugin url_launcher_ios at /home/abdulmuezz/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_ios-6.0.16/
[   +3 ms] Found plugin url_launcher_linux at /home/abdulmuezz/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_linux-3.0.1/
[   +4 ms] Found plugin url_launcher_macos at /home/abdulmuezz/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_macos-3.0.1/
[   +4 ms] Found plugin url_launcher_web at /home/abdulmuezz/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_web-2.0.11/
[   +1 ms] Found plugin url_launcher_windows at /home/abdulmuezz/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_windows-3.0.1/
[  +31 ms] gen_dart_plugin_registrant: Complete
[   +2 ms] Skipping target: _composite
[   +6 ms] complete
[  +11 ms] Launching lib/main.dart on Linux in debug mode...
[  +11 ms] /home/abdulmuezz/snap/flutter/common/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev
/home/abdulmuezz/snap/flutter/common/flutter/bin/cache/dart-sdk/bin/snapshots/frontend_server.dart.snapshot --sdk-root
/home/abdulmuezz/snap/flutter/common/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names --experimental-emit-debug-metadata
-DFLUTTER_WEB_AUTO_DETECT=true --output-dill /tmp/flutter_tools.PVCZLC/flutter_tool.NGNQRP/app.dill --packages
/home/abdulmuezz/Documents/flutter_projects/franchise_manager/.dart_tool/package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation
--filesystem-scheme org-dartlang-root --initialize-from-dill build/c075001b96339384a97db4862b8ab8db.cache.dill.track.dill --source
/home/abdulmuezz/Documents/flutter_projects/franchise_manager/.dart_tool/flutter_build/dart_plugin_registrant.dart --source package:flutter/src/dart_plugin_registrant.dart
-Dflutter.dart_plugin_registrant=file:///home/abdulmuezz/Documents/flutter_projects/franchise_manager/.dart_tool/flutter_build/dart_plugin_registrant.dart
--enable-experiment=alternative-invalidation-strategy
[  +48 ms] Building Linux application...
[  +32 ms] <- compile package:franchise_manager/main.dart
[   +3 ms] executing: [build/linux/x64/debug/] cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug -DFLUTTER_TARGET_PLATFORM=linux-x64 /home/abdulmuezz/Documents/flutter_projects/franchise_manager/linux
[ +209 ms] -- The CXX compiler identification is Clang 6.0.0
[   +5 ms] -- Check for working CXX compiler: /snap/flutter/current/usr/bin/clang++
[ +149 ms] -- Check for working CXX compiler: /snap/flutter/current/usr/bin/clang++ -- broken
[   +1 ms] CMake Error at /snap/flutter/111/usr/share/cmake-3.10/Modules/CMakeTestCXXCompiler.cmake:45 (message):
[   +2 ms]   The C++ compiler
[        ]     "/snap/flutter/current/usr/bin/clang++"
[        ]   is not able to compile a simple test program.
[        ]   It fails with the following output:
[        ]     Change Dir: /home/abdulmuezz/Documents/flutter_projects/franchise_manager/build/linux/x64/debug/CMakeFiles/CMakeTmp
[        ]     Run Build Command:"/snap/flutter/current/usr/bin/ninja" "cmTC_e9d5e"
[        ]     [1/2] Building CXX object CMakeFiles/cmTC_e9d5e.dir/testCXXCompiler.cxx.o
[        ]     [2/2] Linking CXX executable cmTC_e9d5e
[        ]     FAILED: cmTC_e9d5e 
[        ]     : && /snap/flutter/current/usr/bin/clang++    -L/snap/flutter/current/usr/lib/gcc/x86_64-linux-gnu/8 -L/snap/flutter/current/usr/lib/x86_64-linux-gnu -lblkid -lgcrypt -llzma
-lpthread -ldl -L/snap/flutter/current/usr/lib/ CMakeFiles/cmTC_e9d5e.dir/testCXXCompiler.cxx.o  -o cmTC_e9d5e   && :
[        ]     /snap/flutter/current/usr/bin/ld: warning: /usr/lib/gcc/x86_64-linux-gnu/11/../../../x86_64-linux-gnu/crt1.o: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0008002
[        ]     /usr/lib/gcc/x86_64-linux-gnu/11/../../../x86_64-linux-gnu/libgcc_s.so.1: undefined reference to `_dl_find_object@GLIBC_2.35'
[        ]     //lib/x86_64-linux-gnu/libgpg-error.so.0: undefined reference to `__libc_single_threaded@GLIBC_2.32'
[        ]     //lib/x86_64-linux-gnu/libgpg-error.so.0: undefined reference to `pthread_mutex_trylock@GLIBC_2.34'
[        ]     clang: error: linker command failed with exit code 1 (use -v to see invocation)
[        ]     ninja: build stopped: subcommand failed.
[        ]   CMake will not be able to correctly generate this project.
[        ] Call Stack (most recent call first):
[        ]   CMakeLists.txt:3 (project)
[        ] -- Configuring incomplete, errors occurred!
[        ] See also "/home/abdulmuezz/Documents/flutter_projects/franchise_manager/build/linux/x64/debug/CMakeFiles/CMakeOutput.log".
[        ] See also "/home/abdulmuezz/Documents/flutter_projects/franchise_manager/build/linux/x64/debug/CMakeFiles/CMakeError.log".
[  +23 ms] Building Linux application... (completed in 418ms)
[+13966 ms] Exception: Unable to generate build files
[        ] "flutter run" took 24,928ms.
[   +6 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:699:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1183:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:94:3)
           <asynchronous suspension>
           
           
[ +247 ms] ensureAnalyticsSent: 245ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1
```

### Executing `flutter analyze`

```
Analyzing franchise_manager...                                          

   info • Depend on referenced packages • lib/pages/page_add/widgets/fields/field_date.dart:4:8 • depend_on_referenced_packages
   info • Depend on referenced packages • lib/pages/page_add/widgets/fields/field_date_range.dart:4:8 • depend_on_referenced_packages

2 issues found. (ran in 1.9s)
```

### Executing `flutter doctor -v`

```
[✓] Flutter (Channel stable, 3.0.0, on Pop!_OS 22.04 LTS 5.17.5-76051705-generic, locale en_US.UTF-8)
    • Flutter version 3.0.0 at /home/abdulmuezz/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ee4e09cce0 (10 days ago), 2022-05-09 16:45:18 -0700
    • Engine revision d1b9a6938a
    • Dart version 2.17.0
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /home/abdulmuezz/Android/Sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: /snap/android-studio/121/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /snap/bin/chromium

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[✓] Android Studio (version 2021.2)
    • Android Studio at /snap/android-studio/121/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.67.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.40.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Pop!_OS 22.04 LTS 5.17.5-76051705-generic
    • Chrome (web)    • chrome • web-javascript • Chromium 101.0.4951.64 snap

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by maheshmnj** [comment] 2022-05-20 11:54
Hi @muezz, Did you install flutter via snap? if yes this is very likely an issue with `flutter_snap`. This is a duplicate of https://github.com/flutter/flutter/issues/102678 (closed)
Closing as per the response here https://github.com/flutter/flutter/issues/102678#issuecomment-1114103944

**Closed** 2022-05-20 11:55 UTC
Labels: in triage

**Comment by muezz** [comment] 2022-05-20 12:21
@maheshmnj  Thanks for the response. I came from discord where a couple other people were also having this issue. At least now its clear that it isnt a flutter issue and its only because of the snap packaging system. Hopefully they fix it soon (I went to their repo and saw that someone else has already opened this issue).
