### ISSUE TITLE
FloatingActionButton child widget state lost on mouse cursor hover outside of app

### ISSUE THREAD

**Issue by tgucio** [flutter/flutter#117390] opened 2022-12-20 12:45 UTC
## Steps to Reproduce

1. Execute `flutter run` on the code sample
2. Tap on the FAB a few times
3. Hover the mouse cursor in an out of the app window when the color overlay is shown

**Expected results:** color overlay stays when mouse cursor is hovered

**Actual results:** color overlay disappears, FooBar widget state is created anew (see app logs)

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(primarySwatch: Colors.blue),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;
  final ValueNotifier<Color> _color = ValueNotifier<Color>(Colors.green);

  void _incrementCounter() {
    setState(() {
      _counter++;
    });

    _color.value = _color.value == Colors.green ? Colors.purple : Colors.green;
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text(widget.title)),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text('You have pushed the button this many times:'),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headlineMedium,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: FooBar(color: _color, child: const Icon(Icons.add)),
      ),
    );
  }
}


class FooBar extends StatefulWidget {
  const FooBar({super.key, required this.color, required this.child});

  final ValueNotifier<Color> color;
  final Widget child;

  @override
  State<FooBar> createState() => FooBarState();
}

class FooBarState extends State<FooBar> {
  OverlayEntry? _overlayEntry;

  @override
  void initState() {
    super.initState();
    print('FooBarState $this initState');

    widget.color.addListener(_handleColorUpdated);
  }

  @override
  void didUpdateWidget(FooBar oldWidget) {
    print('FooBarState $this didUpdate');
    super.didUpdateWidget(oldWidget);
    oldWidget.color.removeListener(_handleColorUpdated);
    widget.color.addListener(_handleColorUpdated);
  }

  @override
  void dispose() {
    print('FooBarState $this dispose');
    _overlayEntry?.remove();
    _overlayEntry?.dispose();
    widget.color.removeListener(_handleColorUpdated);
    super.dispose();
  }

  void _handleColorUpdated() {

    if (_overlayEntry == null) {
      _overlayEntry = OverlayEntry(
        builder: (BuildContext context) {
          return Align(
            alignment: Alignment.bottomLeft,
            child: SizedBox(
              width: 200,
              height: 50,
              child: Material(
                color: widget.color.value,
                child: Text(
                  'Color: ${widget.color.value}',
                  style: const TextStyle(color: Colors.black, fontSize: 10),
                ),
              ),
            ),
          );
        }
      );
      Overlay.of(context).insert(_overlayEntry!);
    } else {
      _overlayEntry?.remove();
      _overlayEntry = null;
    }

    setState(() { });
  }

  @override
  Widget build(BuildContext context) {
    print('FooBarState $this build');
    return Container(
      padding: const EdgeInsets.all(4.0),
      color: widget.color.value,
      child: widget.child,
    );
  }
}
```

</details>

<details>
  <summary>Logs</summary>

```
flutter --version
Flutter 3.7.0-10.0.pre.34 • channel master • https://github.com/flutter/flutter.git
Framework • revision 7b850ef375 (3 days ago) • 2022-12-17 07:05:35 -0500
Engine • revision f74dd53318
Tools • Dart 3.0.0 (build 3.0.0-35.0.dev) • DevTools 2.20.0
```

</details>

**Comment by huycozy** [comment] 2022-12-21 06:04
@tgucio thanks for filing the issue. This issue is reproducible on the latest `master` channels. Verified on `macOS` app.

<details>
<summary>Demo video</summary>


https://user-images.githubusercontent.com/104349824/208832833-f448df49-f98a-4a72-af84-3479946c3209.mp4


</details>

<details>
<summary>flutter doctor -v (master)</summary>

```bash
[!] Flutter (Channel master, 3.7.0-13.0.pre.18, on macOS 13.0.1 22A400 darwin-x64, locale en-VN)
    • Flutter version 3.7.0-13.0.pre.18 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e8e26b6840 (34 minutes ago), 2022-12-20 21:05:23 -0500
    • Engine revision c7eae29010
    • Dart version 3.0.0 (build 3.0.0-39.0.dev)
    • DevTools version 2.20.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.74.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.54.0

[✓] Connected device (3 available)
    • SM T225 (mobile) • R9JT3004VRJ • android-arm64  • Android 12 (API 31)
    • macOS (desktop)  • macos       • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)     • chrome      • web-javascript • Google Chrome 108.0.5359.124

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```
</details>

**Comment by huycozy** [comment] 2022-12-21 06:18
@tgucio thanks for filing the issue. This issue is reproducible on the latest `master` channels. It seems only to happen on desktop app as below since I can't see the issue on Web app.

| MacOS | Windows | Linux | Web |
| --------------- | --------------- |  --------------- |   --------------- | 
❌ | ❌ | ❌ | ✅ | 

✅: No Issue ❌: Issue reproduced

<details>
<summary>Demo video</summary>


https://user-images.githubusercontent.com/104349824/208832833-f448df49-f98a-4a72-af84-3479946c3209.mp4


</details>

<details>
<summary>flutter doctor -v (master)</summary>

```bash
[!] Flutter (Channel master, 3.7.0-13.0.pre.18, on macOS 13.0.1 22A400 darwin-x64, locale en-VN)
    • Flutter version 3.7.0-13.0.pre.18 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e8e26b6840 (34 minutes ago), 2022-12-20 21:05:23 -0500
    • Engine revision c7eae29010
    • Dart version 3.0.0 (build 3.0.0-39.0.dev)
    • DevTools version 2.20.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.74.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.54.0

[✓] Connected device (3 available)
    • SM T225 (mobile) • R9JT3004VRJ • android-arm64  • Android 12 (API 31)
    • macOS (desktop)  • macos       • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)     • chrome      • web-javascript • Google Chrome 108.0.5359.124

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```
</details>

**Comment by huycozy** [comment] 2022-12-26 07:25
@tgucio It seems the issue is caused by `Tooltip` inside `FloatingActionButton` as the issue does not happen anymore when removing `tooltip` attribute. 

Please retry testing this. In case you are also having a similar result, please take a look at new issue #117627 which filing a root issue of this. And please feel free to close this issue as a duplicate. Thanks!

**Comment by gspencergoog** [comment] 2023-01-05 19:14
Closing as a duplicate of https://github.com/flutter/flutter/issues/117627 (Desktop Triage)

**Closed by gspencergoog** 2023-01-05 19:14 UTC
Labels: framework, f: material design, a: desktop, a: mouse, has reproducible steps, found in release: 3.7
