### ISSUE TITLE
Material Icon 'add_card' is missing!

### ISSUE THREAD

**Issue by echonox** [flutter/flutter#98398] opened 2022-02-14 11:44 UTC
The material icon 'add_card' including rounded, sharp and etc versions of the same icon is missing I've tried both stable and beta channel.

https://api.flutter.dev/flutter/material/Icons/add_card-constant.html

Running the app on Android or Windows it shows nothing, and running it on Web it shows wrong icon (Bed icon):

![image](https://user-images.githubusercontent.com/9529847/153859123-1d638052-f984-4233-a2e7-75402c9d38cf.png)

![image](https://user-images.githubusercontent.com/9529847/153859150-1185623d-73ad-4546-87a7-ee33b62abd1f.png)

[✓] Flutter (Channel stable, 2.10.1, on Microsoft Windows [Version 10.0.22000.493], locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc1)
[✓] Chrome - develop for the web
[✓] Visual Studio - develop for Windows (Visual Studio Community 2022 17.0.4)
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.64.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!

Also the preview icon doesn't show in VSCode or Android Studio:

![image](https://user-images.githubusercontent.com/9529847/153858056-2e6da248-9921-4049-8b01-2e7b757defd0.png)

**Comment by danagbemava-nc** [comment] 2022-02-14 12:45
Duplicate of #97767

**Closed by danagbemava-nc** 2022-02-14 12:45 UTC
Labels: in triage
