### ISSUE TITLE
'package:flutter/src/rendering/stack.dart': Failed assertion: line 599 pos 12: 'size.isFinite': is not true.

### ISSUE THREAD

**Issue by flodaniel** [flutter/flutter#143360] opened 2024-02-13 08:28 UTC
### Steps to reproduce

Try to render this widget:
```dart
Stack(
      children: [
        Positioned(
          left: 0,
          top: 0,
          child: Container(
            width: 28,
            height: 25.83,
          ),
        ),
      ],
    )
```

### Expected results

Not sure what i would expect, but flutter tells me to file a bug either way. 

### Actual results

Flutter throws this assertion:

```console
════════ Exception caught by rendering library ═════════════════════════════════
The following assertion was thrown during performLayout():
'package:flutter/src/rendering/stack.dart': Failed assertion: line 599 pos 12: 'size.isFinite': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.yml
.
.
.

(elided 12 frames from class _AssertionError, class _Timer, dart:async, and dart:async-patch)

The following RenderObject was being processed when the exception was fired: RenderStack#91654 relayoutBoundary=up17
    parentData: offset=Offset(0.0, 0.0); flex=null; fit=null (can use size)
    constraints: BoxConstraints(0.0<=w<=393.0, 0.0<=h<=Infinity)
    size: MISSING
    alignment: AlignmentDirectional.topStart
    textDirection: ltr
    fit: loose
    child 1: RenderConstrainedBox#9e7b7 NEEDS-LAYOUT NEEDS-PAINT
        parentData: top=0.0; left=0.0; offset=Offset(0.0, 0.0)
        constraints: MISSING
        size: MISSING
        additionalConstraints: BoxConstraints(w=28.0, h=25.8)
RenderObject: RenderStack#91654 relayoutBoundary=up17
    parentData: offset=Offset(0.0, 0.0); flex=null; fit=null (can use size)
    constraints: BoxConstraints(0.0<=w<=393.0, 0.0<=h<=Infinity)
    size: MISSING
    alignment: AlignmentDirectional.topStart
    textDirection: ltr
    fit: loose
    child 1: RenderConstrainedBox#9e7b7 NEEDS-LAYOUT NEEDS-PAINT
        parentData: top=0.0; left=0.0; offset=Offset(0.0, 0.0)
        constraints: MISSING
        size: MISSING
        additionalConstraints: BoxConstraints(w=28.0, h=25.8)
════════ Exception caught by rendering library ═════════════════════════════════
RenderBox was not laid out: RenderStack#91654 relayoutBoundary=up17 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1972 pos 12: 'hasSize'
The relevant error-causing widget was:
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════
RenderBox was not laid out: RenderFlex#4a4f2 relayoutBoundary=up16 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1972 pos 12: 'hasSize'
The relevant error-causing widget was:
```

### Code sample

<details open><summary>Code sample</summary>

```dart
Stack(
      children: [
        Positioned(
          left: 0,
          top: 0,
          child: Container(
            width: 28,
            height: 25.83,
          ),
        ),
      ],
    )
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
════════ Exception caught by rendering library ═════════════════════════════════
The following assertion was thrown during performLayout():
'package:flutter/src/rendering/stack.dart': Failed assertion: line 599 pos 12: 'size.isFinite': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.yml
.
.
.

(elided 12 frames from class _AssertionError, class _Timer, dart:async, and dart:async-patch)

The following RenderObject was being processed when the exception was fired: RenderStack#91654 relayoutBoundary=up17
    parentData: offset=Offset(0.0, 0.0); flex=null; fit=null (can use size)
    constraints: BoxConstraints(0.0<=w<=393.0, 0.0<=h<=Infinity)
    size: MISSING
    alignment: AlignmentDirectional.topStart
    textDirection: ltr
    fit: loose
    child 1: RenderConstrainedBox#9e7b7 NEEDS-LAYOUT NEEDS-PAINT
        parentData: top=0.0; left=0.0; offset=Offset(0.0, 0.0)
        constraints: MISSING
        size: MISSING
        additionalConstraints: BoxConstraints(w=28.0, h=25.8)
RenderObject: RenderStack#91654 relayoutBoundary=up17
    parentData: offset=Offset(0.0, 0.0); flex=null; fit=null (can use size)
    constraints: BoxConstraints(0.0<=w<=393.0, 0.0<=h<=Infinity)
    size: MISSING
    alignment: AlignmentDirectional.topStart
    textDirection: ltr
    fit: loose
    child 1: RenderConstrainedBox#9e7b7 NEEDS-LAYOUT NEEDS-PAINT
        parentData: top=0.0; left=0.0; offset=Offset(0.0, 0.0)
        constraints: MISSING
        size: MISSING
        additionalConstraints: BoxConstraints(w=28.0, h=25.8)
════════ Exception caught by rendering library ═════════════════════════════════
RenderBox was not laid out: RenderStack#91654 relayoutBoundary=up17 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1972 pos 12: 'hasSize'
The relevant error-causing widget was:
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════
RenderBox was not laid out: RenderFlex#4a4f2 relayoutBoundary=up16 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1972 pos 12: 'hasSize'
The relevant error-causing widget was:
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.16.9, on macOS 14.1.2 23B92 darwin-arm64, locale
    en-AT)
    • Flutter version 3.16.9 on channel stable at
      /Users/floriandaniel/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 41456452f2 (3 weeks ago), 2024-01-25 10:06:23 -0800
    • Engine revision f40e976bed
    • Dart version 3.2.6
    • DevTools version 2.28.5

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/floriandaniel/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/floriandaniel/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] IntelliJ IDEA Community Edition (version 2023.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.86.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.82.0```

</details>

**Comment by dam-ease** [comment] 2024-02-13 09:42
Hello @flodaniel.
Is the code snippet all you ran to reproduce this? I'm unable to reproduce on my end with the snippet (full minimal code sample below). This seems to me like an issue with you code layout seeing you are using the `Stack` Widget as well. Please try with the sample below to see if it still reproduces on your end.
<details><summary>Code Sample</summary>
<p>

```dart
import 'package:flutter/material.dart';


void main() => runApp(const AppBarApp());

class AppBarApp extends StatelessWidget {
  const AppBarApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(
          colorSchemeSeed: const Color(0xff6750a4), useMaterial3: true),
      home: SafeArea(
        child: Scaffold(
          body: Stack(
            children: [
              Positioned(
                left: 0,
                top: 0,
                child: Container(
                  width: 28,
                  height: 25.83,
                  child: Text("Hey"),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
``` 

</p>
</details>

**Comment by flodaniel** [comment] 2024-02-13 09:54
Hello @dam-ease,

thanks for the quick reply! You are correct, overall I was using a more complex layout, I have managed to reproduce it now with this minimal sample:

```dart

import 'package:flutter/material.dart';

void main() => runApp(const AppBarApp());

class AppBarApp extends StatelessWidget {
  const AppBarApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(
          colorSchemeSeed: const Color(0xff6750a4), useMaterial3: true),
      home: SafeArea(
        child: Scaffold(
          body: Column(
            mainAxisAlignment: MainAxisAlignment.end,
            children: [
              Stack(
                children: [
                  Positioned(
                    left: 0,
                    top: 0,
                    child: Container(
                      width: 28,
                      height: 25.83,
                    ),
                  ),
                ],
              ),
            ],
          ),
        ),
      ),
    );
  }
}


```

**Comment by dam-ease** [comment] 2024-02-13 11:11
Thanks for your response @flodaniel.
From your code sample, you are wrapping the `Stack` widget with a `column`. Since `column` and `stack` will take up the screen size, to be able to use both together, you need to give the contents a certain height using a Container or a SizedBox or need to be wrapped with expanded (see sample below)

<details><summary>Code Sample</summary>
<p>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const AppBarApp());

class AppBarApp extends StatelessWidget {
  const AppBarApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(
          colorSchemeSeed: const Color(0xff6750a4), useMaterial3: true),
      home: SafeArea(
        child: Scaffold(
          body: Column(
            mainAxisAlignment: MainAxisAlignment.end,
            children: [
              Expanded(
                child: Stack(
                  children: [
                    Positioned(
                      left: 0,
                      top: 0,
                      child: Container(
                        width: 28,
                        height: 25.83,
                      ),
                    ),
                  ],
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}

``` 

</p>
</details> 

Please see support channels like Stackoverflow or [flutterhelp](https://www.reddit.com/r/flutterhelp/) for resources and ask 
 more questions like this.
Closing this from here as this seems to be WAI.

**Closed by dam-ease** 2024-02-13 11:11 UTC
Labels: in triage

**Comment by flodaniel** [comment] 2024-02-13 13:26
Hi @dam-ease,

I was not asking for help about this specific layout, but the flutter SDK logs in the console that one should absolutely open a ticket. If the report is not actionable, the flutter SDK should not log a "request to open ticket".
