### ISSUE TITLE
TextField Line break problem in Chinese input on the web page

### ISSUE THREAD

**Issue by mingxin-yang** [flutter/flutter#140728] opened 2023-12-29 08:38 UTC
### Steps to reproduce

When inputting Chinese into the TextField on the web page, display problems will occur when wrapping lines. 

### Expected results

Can input Chinese normally

### Actual results

When inputting Chinese into the TextField on the web page, display problems will occur when wrapping lines. 

### Code sample

<details open><summary>Code sample</summary>

```dart
TextField(
                      enabled: widget.options.enabled,
                      autocorrect: widget.options.autocorrect,
                      autofocus: widget.options.autofocus,
                      enableSuggestions: widget.options.enableSuggestions,
                      controller: _textController,
                      cursorColor: InheritedChatTheme.of(context)
                          .theme
                          .inputTextCursorColor,
                      decoration: InheritedChatTheme.of(context)
                          .theme
                          .inputTextDecoration
                          .copyWith(
                            hintStyle: InheritedChatTheme.of(context)
                                .theme
                                .inputTextStyle
                                .copyWith(
                                  color: InheritedChatTheme.of(context)
                                      .theme
                                      .inputTextColor
                                      .withOpacity(0.5),
                                ),
                            hintText:
                                InheritedL10n.of(context).l10n.inputPlaceholder,
                          ),
                      focusNode: _inputFocusNode,
                      keyboardType: widget.options.keyboardType,
                      maxLines: 5,
                      minLines: 1,
                      onChanged: widget.options.onTextChanged,
                      onTap: widget.options.onTextFieldTap,
                      style: InheritedChatTheme.of(context)
                          .theme
                          .inputTextStyle
                          .copyWith(
                            color: InheritedChatTheme.of(context)
                                .theme
                                .inputTextColor,
                          ),
                      textCapitalization: TextCapitalization.sentences,
                    )
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/flutter/flutter/assets/23076937/57a577f4-7f13-4dc8-a70b-31048865ec76

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
$ flutter doctor                                                    
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.2, on macOS 11.7.6 20G1231 darwin-x64, locale zh-Hans-CN)
[!] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[!] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    ✗ Flutter requires Xcode 14 or higher.
      Download the latest version or update via the Mac App Store.
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] VS Code (version 1.85.1)
[!] Proxy Configuration
    ! NO_PROXY is not set
[✓] Connected device (2 available)
[✓] Network resources

! Doctor found issues in 3 categories.
```

</details>

**Comment by mingxin-yang** [comment] 2024-01-02 02:06
> Try to add a key to Textfield.

Trying this approach also didn't resolve the issue

**Comment by darshankawar** [comment] 2024-01-02 06:43
> display problems will occur when wrapping lines.

@mingxin-yang 
Can you provide short video showing what exactly the issue are you facing ? The video you shared didn't seem to have rendered properly as I can't play it.



> ```dart
> TextField(
>                       enabled: widget.options.enabled,
>                       autocorrect: widget.options.autocorrect,
> ```

Can you also provide us complete but minimal reproducible code sample without any third party implementation that we can directly copy paste and run to see the reported behavior ?

**Comment by mingxin-yang** [comment] 2024-01-02 07:01
https://github.com/flutter/flutter/assets/23076937/2e5816e6-402b-4cb3-b9ae-766c5c725650

@darshankawar Hello, I have uploaded a new video, but the Chinese cannot be displayed correctly when changing lines.
I tried a simple code, and this problem will occur as long as it is a multi-line input box.
```
TextField(
          maxLines: 5,
          minLines: 1,
        ),
```

**Comment by darshankawar** [comment] 2024-01-03 05:21
Thanks for the update. So, if I understand correctly, in multline textfield with chinese input, when you enter text, the suggestions don't show in chinese or whether the english text doesn't get converted into Chinese ?

Can you also confirm if the behavior persists on latest master ?

`flutter channel master`
`flutter upgrade`

**Comment by mingxin-yang** [comment] 2024-01-03 06:02
> Can you also confirm if the behavior persists on latest master ?
> 
> `flutter channel master` `flutter upgrade`

Yes, I am sure that this problem occurs in the latest version. During the line break period, the English text to be converted does not become Chinese normally. You can use the Chinese input method to input, and this problem will occur. @darshankawar

**Comment by darshankawar** [comment] 2024-01-04 05:55
Thanks for the update @mingxin-yang 
I tried the code sample running on latest master and on web and observed below as shown:


https://github.com/flutter/flutter/assets/67046386/f4214790-3bb6-46f0-aaee-f67de9fbdddc


It seems that it works as expected ? If not, can you describe / elaborate if it isn't ?

I used pinyin-simplified keyboard.

**Comment by mingxin-yang** [comment] 2024-01-04 06:02
@darshankawar  Thank you for your try. You can reduce the width of the window, and then a bug will appear during automatic line wrapping. You should not hit the enter key to wrap the line.

**Comment by darshankawar** [comment] 2024-01-05 06:20
Thanks for the update and your patience while we figure this out @mingxin-yang 
I tried as you suggested, but don't seem to be getting the issue.


https://github.com/flutter/flutter/assets/67046386/43e74769-042f-4ca1-8106-bf1df48eb81c

When I type in and intellisense is shown, using the keyboard if I select the chinese text, it shows up in the textfield properly, but sometimes, if I don't use the keyboard to select the chinese text selection and just try to hit enter, then it doesn't show the Chinese text, but I think this is not the issue you are highlighting.

**Comment by mingxin-yang** [comment] 2024-01-05 07:14
<img width="441" alt="image" src="https://github.com/flutter/flutter/assets/23076937/03575574-8353-4ac3-920d-81f75473f65d">
<img width="482" alt="image" src="https://github.com/flutter/flutter/assets/23076937/e7f623a1-4578-40c6-baef-0a6575b188b8">   

---
I think the problem has been reproduced in your attempt. If you press the space bar on the keyboard after the first picture, the Chinese on IntelliSense should appear, but the result is a combination of English and Chinese. This is the problem. When typing in Chinese, there is no need to hit enter, otherwise English will be entered. This is normal.  

In order to better make you aware of the problem, I re-recorded the video. In the video, the left side is the mac side and the right side is the web side, and my keyboard operations are displayed in the lower left corner of the video. @darshankawar 
https://github.com/flutter/flutter/assets/23076937/62088c54-0412-4c4a-8b5f-37d776f52725

**Comment by darshankawar** [comment] 2024-01-05 13:09
Thanks for the feedback. I tried to replicate again, but unknowningly might have reproduced it. Tried same set of input on macos desktop and web and below is the comparison:

1. desktop:

<img width="356" alt="Screenshot 2024-01-05 at 6 35 32 PM" src="https://github.com/flutter/flutter/assets/67046386/190d667d-6ba3-47fb-a44c-e6ae8175cdbd">

2. web:

<img width="499" alt="Screenshot 2024-01-05 at 6 36 59 PM" src="https://github.com/flutter/flutter/assets/67046386/b383c15b-2ae1-4d94-b5ed-57f44cb0c503">


I see that once, while on web, it didn't translate the text to Chinese and kept it in English, so I think this might be the issue being reported.

Keeping the issue open for team's tracking.

**Comment by htoor3** [comment] 2024-01-05 20:55
This might be related to https://github.com/flutter/flutter/issues/134797.  The issue is that IME composition gets interrupted on newlines.  We've seen this kind of problem get resolved in the POC for the [native text editing proposal](https://github.com/flutter/flutter/issues/120613)

I'll try to verify that this is the same issue as the one above and dedupe.

**Comment by mingxin-yang** [comment] 2024-01-08 08:22
Thank you, this should be the IME problem you mentioned, but I don’t understand what it means to use Platform views to solve it. Do you need to set up the TextField differently when it is judged to be web? Can you provide an example for input? box becomes normal.
```
TextField(
          maxLines: 5,
          minLines: 1,
        ),
```
@htoor3  @darshankawar

**Comment by htoor3** [comment] 2024-01-11 17:37
@mingxin-yang it's something we will fix on our end that should hopefully resolve IME issues like this. 

In the meantime, I will work to find a solution to this for the current system. I believe the root cause the same as this issue: https://github.com/flutter/flutter/issues/134797, so I will deduplicate this.  Once a fix is made on that issue, we can verify that it also fixes the line break issue here as well.

**Closed by htoor3** 2024-01-11 17:37 UTC
Labels: a: text input, a: internationalization, platform-web, has reproducible steps, team-web, found in release: 3.16, found in release: 3.18
