### ISSUE TITLE
flutter build ios failing: ld: framework not found App

### ISSUE THREAD

**Issue by kentcb** [flutter/flutter#32454] opened 2019-05-10 01:57 UTC
## Steps to Reproduce

I am running:

```
flutter build ios --release
```

Until recently, this worked. However, something is now broken and I'm having trouble identifying what. I have been trying to get Crashlytics working and I suspect it is related but it's unclear how.

## Logs

I have run a build with `--verbose` and have uploaded as a zip [here](https://github.com/flutter/flutter/files/3164674/build_log.zip) (output was too much for gist). I have redacted only the application name from the log.

This appears at several points in the log:
```
ld: framework not found App
```

But I suspect there is an underlying problem causing that.

`flutter doctor -v` output:
```
[✓] Flutter (Channel master, v1.5.9-pre.196, on Mac OS X 10.14.4 18E226, locale en-AU)
    • Flutter version 1.5.9-pre.196 at /Users/kent/Repository/flutter
    • Framework revision 9c77e8e8a0 (6 hours ago), 2019-05-09 12:43:51 -0700
    • Engine revision 644db5a49c
    • Dart version 2.3.1 (build 2.3.1-dev.0.0 a0290f823c)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/kent/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[!] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.33.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.0.0

[✓] Connected device (1 available)
    • iPad • e9621f25ae14a6b0a4ad7d3eb0600bd2454564c0 • ios • iOS 12.1.4

! Doctor found issues in 1 category.
```
If you're wondering why I'm on `master`, it's because I've been going through hell trying to get an iOS build to actually complete without hanging/timeouts. That is now fixed on `master` so I'm there reluctantly until it makes its way into `dev` and beyond.

**Comment by kentcb** [comment] 2019-05-10 03:00
I tried going back to `dev` channel and got same result.

**Comment by FlorinMihalache** [comment] 2019-05-11 08:16
I think I had the same issue, also getting this error:  `ld: framework not found App`

This is how I fixed it:
I noticed that in the `project/ios/Flutter` folder, `App.framework` was missing. Not sure what caused this, but I'm sure I did't delete it on purpose. I copied it from a new Flutter project and it works fine now.

**Comment by kangwang1988** [comment] 2019-05-12 12:47
@FlorinMihalache 
Can you run `flutter build ios --release --verbose` and paste the result here?

**Comment by FlorinMihalache** [comment] 2019-05-12 12:59
@kangwang1988 
Sure: https://gist.github.com/FlorinMihalache/a2ce7065d24cf261fcf1aad9fbef77ac

**Comment by suesitran** [comment] 2019-05-18 12:25
found this when i run "flutter build ios --release --verbose"

Encountered error while building for device.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:24:3)
#1      BuildIOSCommand.runCommand (package:flutter_tools/src/commands/build_ios.dart:94:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:559:18)
#3      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#4      _rootRunUnary (dart:async/zone.dart:1132:38)
#5      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#6      _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#8      Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#9      Future._complete (dart:async/future_impl.dart:473:7)
#10     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#11     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async-patch/async_patch.dart:33:20)
#12     _rootRun (dart:async/zone.dart:1124:13)
#13     _CustomZone.run (dart:async/zone.dart:1021:19)
#14     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#15     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#16     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#17     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:115:13)
#18     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:5)

**Comment by kangwang1988** [comment] 2019-05-26 11:08
@FlorinMihalache 
I can't find anything wrong based on your gist log.
Where is the `ld: framework not found App`?

**Comment by kangwang1988** [comment] 2019-05-26 11:16
Let me make the flutter build logic more clear.
1.flutter tools would generate a Generated.xcconfig containing the flutter environment:
![image](https://user-images.githubusercontent.com/817851/58380904-18672b00-7fea-11e9-8698-a2166b4ffe68.png)
2.There is a xcode_backend.sh specified in Xcode project's build phases. It would do two things, copy Flutter.framework and compile App.framework based on environment variables specified in Generated.xcconfig
![image](https://user-images.githubusercontent.com/817851/58380921-477d9c80-7fea-11e9-8eed-25d934bd6b30.png)
3.App.framework and flutter.framework are added to the project by default.
![image](https://user-images.githubusercontent.com/817851/58380930-70059680-7fea-11e9-9f9c-3a276501bb56.png)
4.After adding to the project, it's linked and embeded.
![image](https://user-images.githubusercontent.com/817851/58380947-93304600-7fea-11e9-806d-0d7e48268338.png)
This issue probably could be fixed by comparing your project setting and logic given below.

@kentcb

**Comment by IvanBean** [comment] 2019-05-26 14:32
In my case, implementing Crashlytics 0.0.4+3 cause the `Flutter.framwork` and `App.framework` not be generated on `flutter build ios`, the build will fail and after that `flutter run` resulting in `ld: framework not found App`. Checkout to earlier commit which not implement Crashlytics yet then build works again, 
 hope this information helps, thanks.

**Comment by harsha973** [comment] 2019-06-23 22:52
I faced the same issue. For me it's because of **wrong crashlytics configuration** in Build scripts.

⛔️ **Wrong configuration - Having Fabric and `xcode_backend.sh` in the same build script.** 

<img width="821" alt="Screen Shot 2019-06-24 at 10 25 41 AM" src="https://user-images.githubusercontent.com/1115535/59982878-c1965500-966c-11e9-8251-5ee7c27570e6.png">

To fix this, as mentioned in firebase_crashlytics documentation, you need to create separate config for crashlytics separate from Flutter build script.

✔️ 1) **Separate config for `xcode_backend.sh`**. Good explanation [above](https://github.com/flutter/flutter/issues/32454#issuecomment-495990912). Basically this is responsible to copy Flutter.framework and compile App.framework based on environment variables.

<img width="836" alt="Screen Shot 2019-06-24 at 10 30 29 AM" src="https://user-images.githubusercontent.com/1115535/59982930-79c3fd80-966d-11e9-8118-7e369a89ab7a.png">


✔️ 2) **Separate config for Pods/Fabric** 

<img width="824" alt="Screen Shot 2019-06-24 at 10 30 37 AM" src="https://user-images.githubusercontent.com/1115535/59982939-a24bf780-966d-11e9-937a-37d6e46e6f8c.png">

In my case the reason for the problem is, xcode_backend.sh is adding input files as arguments and this script fails to copy Flutter.framework

Hope this helps to move you in right direction.

**Comment by tudor07** [comment] 2019-09-02 12:22
Still having this issue on Flutter `1.7.8+hotfix.4`

**Comment by Gioxxy** [comment] 2019-10-27 14:10
I am having the same problem on flutter `1.9.1+hotfix.6`. The files in the .ios folder are not copied to the ios/Flutter folder when I run `flutter build ios`

**Comment by kazuooooo** [comment] 2019-10-28 05:41
I also having same error and It looks xcode_backend.sh script not executed,
cuz echo "xcode_backend.sh executed! :)" not found, but I couldn't find why.

<img width="1228" alt="Runner_xcodeproj" src="https://user-images.githubusercontent.com/6919381/67654158-f3f3ee00-f98f-11e9-88dc-2da379c49867.png">

Like @FlorinMihalache say above, I create sample project

```
flutter create sample_app
```

and copied App.framework and Flutter.framework to developing app which causing error.

<img width="1579" alt="Flutter_と_Flutter_と_github_com_と_最近使った項目_と_Flutter_と_最近使った項目_と_App_framework_と_ios_と_Runner_xcodeproj" src="https://user-images.githubusercontent.com/6919381/67654423-e0955280-f990-11e9-9ddf-e957240a7c58.png">


It works fine. (but little bit dirty way 👿 )

**Comment by Gioxxy** [comment] 2019-10-28 17:24
> I also having same error and It looks xcode_backend.sh script not executed,
> cuz echo "xcode_backend.sh executed! :)" not found, but I couldn't find why.
> 
> <img alt="Runner_xcodeproj" width="1228" src="https://user-images.githubusercontent.com/6919381/67654158-f3f3ee00-f98f-11e9-88dc-2da379c49867.png">
> 
> Like @FlorinMihalache say above, I create sample project
> 
> ```
> flutter create sample_app
> ```
> 
> and copied App.framework and Flutter.framework to developing app which causing error.
> 
> <img alt="Flutter_と_Flutter_と_github_com_と_最近使った項目_と_Flutter_と_最近使った項目_と_App_framework_と_ios_と_Runner_xcodeproj" width="1579" src="https://user-images.githubusercontent.com/6919381/67654423-e0955280-f990-11e9-9ddf-e957240a7c58.png">
> 
> It works fine. (but little bit dirty way 👿 )

By copying App.framework and Flutter.framework it happens that they are not updated in the following compilations, except in hot reload

**Comment by jmagman** [comment] 2019-10-28 17:59
> I am having the same problem on flutter `1.9.1+hotfix.6`. The files in the .ios folder are not copied to the ios/Flutter folder when I run `flutter build ios`

If you are trying the experimental add-to-app feature (the only case there should be an `.ios` directory) you [must be on the master channel](https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps#intro).  `flutter build ios` will not copy anything from `.ios` to `ios`.  In fact, with add-to-app you should not have an `ios` directory unless you ran `make-host-app-editable` at some point.
@Gioxxy can you file a new issue?  App.framework is injected differently with add-to-app and requires separate triage.

**Comment by Gioxxy** [comment] 2019-10-28 18:36
> > I am having the same problem on flutter `1.9.1+hotfix.6`. The files in the .ios folder are not copied to the ios/Flutter folder when I run `flutter build ios`
> 
> If you are trying the experimental add-to-app feature (the only case there should be an `.ios` directory) you [must be on the master channel](https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps#intro). `flutter build ios` will not copy anything from `.ios` to `ios`. In fact, with add-to-app you should not have an `ios` directory unless you ran `make-host-app-editable` at some point.
> @Gioxxy can you file a new issue? App.framework is injected differently with add-to-app and requires separate triage.



No, I'm not using the add-to-app. I'm sorry, doing some tests I noticed that copying the App.framework of the .ios folder in the ios/Flutter folder allows me to compile "correctly", 
but it didn't seem like a great solution.

**Comment by Gioxxy** [comment] 2019-11-02 15:09
I opened a new issue here https://github.com/flutter/flutter/issues/44050

**Comment by Xingefb** [comment] 2019-11-21 10:14
flutter channel other origin

**Comment by u2633** [comment] 2019-12-16 16:21
After experiencing many times of failure, I at last solved this issue by a dirty way. First, I created a new project from Android Studio. Next, I copied my source code into the new project including third party Libs. Last, run the command "flutter build ios --release" and launched archive under XCode. This time..., I eventually got the build success message. Hope this helps.

**Comment by VikasJilla** [comment] 2020-01-06 05:30
As @harsha973 mentioned I had to separate the Crashlytics script. But itself did not solve the issue.
Moving the run script to the top of the build phases(I think, mainly to step above embed frameworks) and also keeping the Crashlytics script as the last phase(as mentioned in Crashlytics integration), solved the issue.

Please check the below image
![Screen Shot 2020-01-06 at 10 38 12 AM](https://user-images.githubusercontent.com/11890238/71797345-a4a6f980-3073-11ea-8c92-c03a84e92096.png)

**Comment by simphiwehlabisa** [comment] 2020-02-25 10:12
Create a new flutter project and go to ios folder flutter and copy app.framework to your project

**Comment by gianalmada** [comment] 2020-03-03 09:11
> 
> 
> I think I had the same issue, also getting this error: `ld: framework not found App`
> 
> This is how I fixed it:
> I noticed that in the `project/ios/Flutter` folder, `App.framework` was missing. Not sure what caused this, but I'm sure I did't delete it on purpose. I copied it from a new Flutter project and it works fine now.



> 
> 
> Let me make the flutter build logic more clear.
> 1.flutter tools would generate a Generated.xcconfig containing the flutter environment:
> ![image](https://user-images.githubusercontent.com/817851/58380904-18672b00-7fea-11e9-8698-a2166b4ffe68.png)
> 2.There is a xcode_backend.sh specified in Xcode project's build phases. It would do two things, copy Flutter.framework and compile App.framework based on environment variables specified in Generated.xcconfig
> ![image](https://user-images.githubusercontent.com/817851/58380921-477d9c80-7fea-11e9-8eed-25d934bd6b30.png)
> 3.App.framework and flutter.framework are added to the project by default.
> ![image](https://user-images.githubusercontent.com/817851/58380930-70059680-7fea-11e9-9f9c-3a276501bb56.png)
> 4.After adding to the project, it's linked and embeded.
> ![image](https://user-images.githubusercontent.com/817851/58380947-93304600-7fea-11e9-806d-0d7e48268338.png)
> This issue probably could be fixed by comparing your project setting and logic given below.
> 
> @kentcb

Step 3 App.framework not added to my ios/flutter, i dont why, i tried to make another new project but stil not found App.framework, is my flutter crash ??

**Closed** 2020-03-03 20:11 UTC
Labels: customer: crowd, tool, ⌺‬ platform-ios

**Comment by softmarshmallow** [comment] 2020-03-30 14:51
app, flutter .framework does not exists in newly created dummy project via `flutter create sample`... wierd..?

**Comment by jmagman** [comment] 2020-03-30 18:07
> app, flutter .framework does not exists in newly created dummy project via `flutter create sample`... wierd..?

It won't exist until you run `flutter run` or `flutter build ios`

**Comment by palexs** [comment] 2020-04-12 10:45
My app was missing `App.framework` and `Flutter.framework` and as a result failing to start, because `Thin Binary` build step contained a mistake. According to https://flutter.dev/docs/development/ios-project-migration it should be:
```
/bin/sh "$FLUTTER_ROOT/packages/flutter_tools/bin/xcode_backend.sh" embed
/bin/sh "$FLUTTER_ROOT/packages/flutter_tools/bin/xcode_backend.sh" thin
```
but in my case it was:
```
/bin/sh "$FLUTTER_ROOT/packages/flutter_tools/bin/xcode_backend.sh" embed_and_thin
```
Apparently, `xcode_backend.sh` on `channel stable` as of the time of writing this is missing `embed_and_thin`. Other channels have it, so I was able to run the app on `channel beta`, for example.

**Comment by jmagman** [comment] 2020-04-13 17:33
> My app was missing `App.framework` and `Flutter.framework` and as a result failing to start, because `Thin Binary` build step contained a mistake. According to https://flutter.dev/docs/development/ios-project-migration it should be:
> 
> ```
> /bin/sh "$FLUTTER_ROOT/packages/flutter_tools/bin/xcode_backend.sh" embed
> /bin/sh "$FLUTTER_ROOT/packages/flutter_tools/bin/xcode_backend.sh" thin
> ```
> 
> but in my case it was:
> 
> ```
> /bin/sh "$FLUTTER_ROOT/packages/flutter_tools/bin/xcode_backend.sh" embed_and_thin
> ```
> 
> Apparently, `xcode_backend.sh` on `channel stable` as of the time of writing this is missing `embed_and_thin` command. Other channels have it, so I was able to run the app on `channel beta`, for example.

That's exactly right, good investigation.  In order to backport from beta/dev/master back to stable, you must have `embed` and `thin` separately because `embed_and_thin` isn't present in stable yet.  Most users stay on stable or at least on a particular channel, so we optimize for their use cases, and try to document workarounds for the channel-hoppers.

**Comment by palexs** [comment] 2020-04-13 17:50
@jmagman Thanks, Jenn! I'm afraid many people experiencing the problem land in https://github.com/flutter/flutter/issues/49504, but I couldn't post this solution there, as the conversation was closed there.

**Comment by jmagman** [comment] 2020-04-13 18:21
@palexs I was hoping "If you are seeing a similar crash on iOS 13.4 or greater, please file a new Flutter GitHub issue so we can take a look." would cover it since there are about a thousand ways for code signing to fail or for the App.framework to be missing, so I don't want to point out https://github.com/flutter/flutter/issues/52084#issuecomment-600768772 specifically.

**Comment by srjmalla** [comment] 2020-06-27 15:28
This fixed the issue for me

flutter channel stable

flutter upgrade

**Comment by Sauraus** [comment] 2020-08-06 02:10
We just upgrade to 1.20.0 and since then this issue has cropped up. tried all options so far and nothing.

**Comment by rubensdemelo** [comment] 2020-08-06 12:19
> We just upgrade to 1.20.0 and since then this issue has cropped up. Tried all options so far and nothing.
> 
> Another fun fact, downgrading to 1.19.0-4.3.pre resolves the issue, no more framework not found App... got a love software that makes breaking changes on a minor release.... Semantic versioning anyone? :D https://semver.org/

try to delete `ios/Flutter/Flutter.framework/` and run again

**Comment by Sauraus** [comment] 2020-08-06 15:32
> > We just upgrade to 1.20.0 and since then this issue has cropped up. Tried all options so far and nothing.
> > Another fun fact, downgrading to 1.19.0-4.3.pre resolves the issue, no more framework not found App... got a love software that makes breaking changes on a minor release.... Semantic versioning anyone? :D https://semver.org/
> 
> try to delete `ios/Flutter/Flutter.framework/` and run again

Our build process runs a `flutter clean` which wipes all intermediate directories so that's already being done.

BTW. I can also build the app with 1.17.5 except for some `svg` issues which is why I need the 1.19.0-4.3.pre version.

**Comment by jmagman** [comment] 2020-08-06 16:28
`flutter clean` does not delete `ios/Flutter/Flutter.framework`.

If you are seeing this problem, please file a new GitHub issue and completely fill out the template, and include the output of your `flutter run` with the `-v` verbose command.  `ld: framework not found App` is an extremely generic error (it means your compiled dart framework cannot be found), and I'd like to track down why you are individually seeing it.

If you think this is related to https://flutter.dev/docs/development/ios-project-migration (did the migration not automatically happen for you?) that's helpful.

**Comment by Sauraus** [comment] 2020-08-06 16:34
> `flutter clean` does not delete `ios/Flutter/Flutter.framework`.
> 
> If you are seeing this problem, please file a new GitHub issue and completely fill out the template, and include the output of your `flutter run` with the `-v` verbose command. `ld: framework not found App` is an extremely generic error (it means your compiled dart framework cannot be found), and I'd like to track down why you are individually seeing it.
> 
> If you think this is related to https://flutter.dev/docs/development/ios-project-migration (did the migration not automatically happen for you?) that's helpful.

I will create a new issue, because my `.ios/Flutter` directory contains no `Flutter.Framework` but an `App.Framework`

```
➜  vid_flutter_plugin git:(release/2.3.4) ls -asl .ios/Flutter/
total 64
 0 drwxr-xr-x  13 antoni  staff   416 Aug  6 08:31 .
 0 drwxr-xr-x  10 antoni  staff   320 Aug  5 21:15 ..
 8 -rw-r--r--   1 antoni  staff    32 Aug  5 21:26 .last_build_id
 0 drwxr-xr-x  22 antoni  staff   704 Aug  5 21:15 .symlinks
 0 drwxr-xr-x   5 antoni  staff   160 Aug  5 21:17 App.framework
 8 -rw-r--r--   1 antoni  staff   794 Aug  5 15:15 AppFrameworkInfo.plist
 0 drwxr-xr-x   4 antoni  staff   128 Aug  5 21:13 FlutterPluginRegistrant
 8 -rw-r--r--   1 antoni  staff   432 Aug  5 21:15 Generated.xcconfig
 8 -rw-r--r--   1 antoni  staff   125 Aug  5 15:15 README.md
 0 drwxr-xr-x   4 antoni  staff   128 Aug  6 08:31 engine
 8 -rwxr-xr-x   1 antoni  staff   540 Aug  5 21:15 flutter_export_environment.sh
16 -rw-r--r--   1 antoni  staff  6344 Aug  5 21:13 podhelper.rb
 8 -rw-r--r--   1 antoni  staff   537 Aug  5 21:13 vid_flutter.podspec
➜  vid_flutter_plugin git:(release/2.3.4) flutter clean
Cleaning Xcode workspace...                                         3.1s
Deleting build...                                                  103ms
Deleting .dart_tool...                                              10ms
Deleting .android...                                                 4ms
Deleting .ios...                                                    88ms
➜  vid_flutter_plugin git:(release/2.3.4) ls -asl .ios/Flutter/
ls: .ios/Flutter/: No such file or directory
```

**Comment by jmagman** [comment] 2020-08-06 16:36
@Sauraus That's not a bug, add-to-app `.ios` directories are deleted on `flutter clean`.
