### ISSUE TITLE
Regression in draw_rect_variable_paint.skwasm.drawFrameDuration.average

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#135275] opened 2023-09-22 02:40 UTC
https://flutter-flutter-perf.skia.org/e/?begin=1683910573&end=1695345623&keys=Xed2eff54443a26af4263ce51cdfc1509&requestType=0&selected=commit%3D36940%26name%3D%252Carch%253Dintel%252Cbranch%253Dmaster%252Cconfig%253Ddefault%252Cdevice_type%253Dnone%252Cdevice_version%253Dnone%252Chost_type%253Dlinux%252Csub_result%253Ddraw_rect_variable_paint.skwasm.drawFrameDuration.average%252Ctest%253Dweb_benchmarks_skwasm%252C&xbaroffset=36940

On the engine roll at https://github.com/flutter/flutter/commit/07e70a40867ca9abb276c832e362a7e051d45576

Containing https://github.com/flutter/engine/pull/46061, which is the only one I'm seeing that looks related cc @eyebrowsoffire

**Comment by eyebrowsoffire** [comment] 2023-09-22 02:44
This is a duplicate of https://github.com/flutter/flutter/issues/135167. It's an expected measurement change.

**Closed** 2023-09-22 02:44 UTC
Labels: team-web
