### ISSUE TITLE
Issue with camera plugin

### ISSUE THREAD

**Issue by eliaweiss** [flutter/flutter#76585] opened 2021-02-23 07:53 UTC
I'm using the camera plugin, with https://github.com/rushio-consulting/flutter_camera_ml_vision/blob/master/lib/flutter_camera_ml_vision.dart

But the flutter_camera_ml_vision doesn't work on IOS, so on IOS I just use the camera as is.

But flutter_camera_ml_vision uses camera version 0.5.8+7 which has a bug that if you hold the iphone vertical to the ground + than the image is flipped.

luckily this was fixed with v 0.7.0+2

but I had to copy the code from flutter_camera_ml_vision in order to upgrade it to camera 0.7.0+2,
it was straight forward process, the only issue that i had is that I had to change the following code (line 293):

     child: SizedBox(
          width: _cameraController.value.previewSize.height *
              _cameraController.value.aspectRatio,
          height: _cameraController.value.previewSize.height,
          child: cameraPreview,
        ),

to

      child: SizedBox(
          width: widget.cameraController.value.previewSize.height,
          height: widget.cameraController.value.previewSize.width,
          child: cameraPreview,
        ),

My question is why, why does the width and height get flipped?
Is it a bug?
If not than, can you please explain this?

Thanks

## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by TahaTesser** [comment] 2021-02-23 09:07
Hi @eliaweiss 
From what I can see, the issue is related to a 3rd party plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/rushio-consulting/flutter_camera_ml_vision/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-02-23 09:07 UTC
Labels: in triage

**Comment by eliaweiss** [comment] 2021-02-23 09:13
> Hi @eliaweiss
> From what I can see, the issue is related to a 3rd party plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/rushio-consulting/flutter_camera_ml_vision/issues).
> Closing, as this isn't an issue with Flutter itself.
> If you disagree, please write in the comments,
> providing your `flutter doctor -v`, your `flutter run -v`, your `pubspec.yaml`
> a minimal reproducible code sample that does not use 3rd party plugins,
> and I will reopen it.
> Thank you

It has nothing to do with a third party plugin:
1. flutter_camera_ml_vision  is a google plugin
2. the problem started to happen when upgrading the camera plugin
3. the problem is that in order to display the camera preview one has to flip the width and height
4. the reason I mentioned the flutter_camera_ml_vision  plugin is for how-t-repeat purpose

**Comment by TahaTesser** [comment] 2021-02-23 10:26
@eliaweiss 
1. it is not, check out their GitHub
2.  third party plugin depends on `camera`, they need to upgrade their dependency in their package.

3 & 4
Please provide your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Comment by eliaweiss** [comment] 2021-02-23 10:43
here is the code I use in my app:

`
import 'dart:async';
import 'dart:io';
import 'dart:typed_data';
import 'dart:ui';

import 'package:camera/camera.dart';
import 'package:device_info/device_info.dart';
import 'package:firebase_ml_vision/firebase_ml_vision.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_widgets/flutter_widgets.dart';
import 'package:native_device_orientation/native_device_orientation.dart';
import 'package:path_provider/path_provider.dart';
import 'package:zapit/camerascreen/ImageDetectionTuple.dart';

part 'utils.dart';

typedef HandleDetection<T> = Future<T> Function(FirebaseVisionImage image);
typedef Widget ErrorWidgetBuilder(BuildContext context, CameraError error);

enum CameraError {
  unknown,
  cantInitializeCamera,
  androidVersionNotSupported,
  noCameraAvailable,
}

enum _CameraState {
  loading,
  error,
  ready,
}



class ZCameraMlVision<T> extends StatefulWidget {
  final HandleDetection<T> detector;
  final Function(ImageDetectionTuple<T>) onResult;
  final WidgetBuilder loadingBuilder;
  final ErrorWidgetBuilder errorBuilder;
  final WidgetBuilder overlayBuilder;
  final CameraLensDirection cameraLensDirection;
  final BoundingBoxExtractor<T> boundingBoxExtractor;
//  final ResolutionPreset resolution;
  final Function onDispose;
  CameraController cameraController;
  ZCameraMlVision({
    Key key,
    @required this.onResult,
    @required this.detector,
    @required this.boundingBoxExtractor,
    this.cameraController,
    this.loadingBuilder,
    this.errorBuilder,
    this.overlayBuilder,
    this.cameraLensDirection = CameraLensDirection.back,
//    this.resolution,
    this.onDispose,
  }) : super(key: key);

  @override
  ZCameraMlVisionState createState() => ZCameraMlVisionState<T>();
}

class ZCameraMlVisionState<T> extends State<ZCameraMlVision<T>> {
  String _lastImage;
  Key _visibilityKey = UniqueKey();

  ImageRotation _rotation;
  _CameraState _cameraMlVisionState = _CameraState.loading;
  CameraError _cameraError = CameraError.unknown;
  bool _alreadyCheckingImage = false;
  bool _isStreaming = false;
  bool _isDeactivate = false;

 // int _ts = DateTime.now().millisecondsSinceEpoch;

  NativeDeviceOrientation _nativeDeviceOrientation = NativeDeviceOrientation.portraitUp;
  NativeDeviceOrientationCommunicator _orientationCommunicator = new NativeDeviceOrientationCommunicator();



  @override
  void initState() {
    super.initState();
    _initialize();

    var stream = _orientationCommunicator.onOrientationChanged(useSensor : true);
    stream.listen((x) {
      _nativeDeviceOrientation = x;
      //print(x);
    });
  }

  Future<void> stop() async {
    if (widget.cameraController != null) {
      if (_lastImage != null && File(_lastImage).existsSync()) {
        await File(_lastImage).delete();
      }

      // Directory tempDir = await getTemporaryDirectory();
      // _lastImage = '${tempDir.path}/${DateTime.now().millisecondsSinceEpoch}';
      try {
        XFile file = await widget.cameraController.takePicture();
        _lastImage = file.path;
      } on PlatformException catch (e) {
        debugPrint('$e');
      }

      _stop(false);
    }
  }

  void _stop(bool silently) {
    Future.microtask(() async {
      if (widget.cameraController?.value?.isStreamingImages == true && mounted) {
        await widget.cameraController.stopImageStream();
      }
    });

    _orientationCommunicator.pause();

    if (silently) {
      _isStreaming = false;
    } else {
      setState(() {
        _isStreaming = false;
      });
    }
  }

  void start() {
    if (widget.cameraController != null) {
      _start();
    }
  }

  void _start() {
    widget.cameraController.startImageStream(_processImage);
    _orientationCommunicator.resume();
    setState(() {
      _isStreaming = true;
    });
  }

  CameraValue get cameraValue => widget.cameraController?.value;
  ImageRotation get imageRotation => _rotation;

  Future<void> Function() get prepareForVideoRecording =>
      widget.cameraController.prepareForVideoRecording;

  Future<void> startVideoRecording(String path) async {
    await widget.cameraController.stopImageStream();
    return widget.cameraController.startVideoRecording();
  }

  Future<void> stopVideoRecording() async {
    await widget.cameraController.stopVideoRecording();
    await widget.cameraController.startImageStream(_processImage);
  }

//  Future<void> Function(String path) get takePicture =>
//      widget.cameraController.takePicture;

  Future<void> _initialize() async {
    if (Platform.isAndroid) {
      final deviceInfo = DeviceInfoPlugin();
      final androidInfo = await deviceInfo.androidInfo;
      if (androidInfo.version.sdkInt < 21) {
        debugPrint('Camera plugin doesn\'t support android under version 21');
        if (mounted) {
          setState(() {
            _cameraMlVisionState = _CameraState.error;
            _cameraError = CameraError.androidVersionNotSupported;
          });
        }
        return;
      }
    }

    CameraDescription description =
        await _getCamera(widget.cameraLensDirection);
    if (description == null) {
      _cameraMlVisionState = _CameraState.error;
      _cameraError = CameraError.noCameraAvailable;

      return;
    }
//    widget.cameraController = CameraController(
//      description,
//      widget.resolution ??
//          ResolutionPreset
//              .low, // As the doc says, better to set low when streaming images to avoid drop frames on older devices
//      enableAudio: false,
//    );
    if (!mounted) {
      return;
    }

    try {
      await widget.cameraController.initialize();
    } catch (ex, stack) {
      debugPrint('Can\'t initialize camera');
      debugPrint('$ex, $stack');
      if (mounted) {
        setState(() {
          _cameraMlVisionState = _CameraState.error;
          _cameraError = CameraError.cantInitializeCamera;
        });
      }
      return;
    }

    if (!mounted) {
      return;
    }

    setState(() {
      _cameraMlVisionState = _CameraState.ready;
    });
    _rotation = _rotationIntToImageRotation(
      description.sensorOrientation,
    );

    //FIXME hacky technique to avoid having black screen on some android devices
    await Future.delayed(Duration(milliseconds: 200));
    start();
  }

  @override
  void dispose() {
    if (widget.onDispose != null) {
      widget.onDispose();
    }

    _orientationCommunicator.pause();
    if (_lastImage != null && File(_lastImage).existsSync()) {
      File(_lastImage).delete();
    }
    if (widget.cameraController != null) {
      widget.cameraController.dispose();
    }
    widget.cameraController = null;
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    if (_cameraMlVisionState == _CameraState.loading) {
      return widget.loadingBuilder == null
          ? Center(child: CircularProgressIndicator())
          : widget.loadingBuilder(context);
    }
    if (_cameraMlVisionState == _CameraState.error) {
      return widget.errorBuilder == null
          ? Center(child: Text('$_cameraMlVisionState $_cameraError'))
          : widget.errorBuilder(context, _cameraError);
    }

    Widget cameraPreview = AspectRatio(
      aspectRatio: widget.cameraController.value.aspectRatio,
      child: _isStreaming
          ? CameraPreview(
              widget.cameraController,
            )
          : _getPicture(),
    );
    if (widget.overlayBuilder != null) {
      cameraPreview = Stack(
        fit: StackFit.passthrough,
        children: [
          cameraPreview,
          widget.overlayBuilder(context),
        ],
      );
    }
    return VisibilityDetector(
      child: FittedBox(
        alignment: Alignment.center,
        fit: BoxFit.cover,
        child: SizedBox(
          width:widget.cameraController.value.previewSize.height,
          // widget.cameraController.value.previewSize.height *
          //     widget.cameraController.value.aspectRatio,
          height: widget.cameraController.value.previewSize.width,
          child: cameraPreview,
        ),
      ),
      onVisibilityChanged: (VisibilityInfo info) {
        if (info.visibleFraction == 0) {
          //invisible stop the streaming
          _isDeactivate = true;
          _stop(true);
        } else if (_isDeactivate) {
          //visible restart streaming if needed
          _isDeactivate = false;
          _start();
        }
      },
      key: _visibilityKey,
    );
  }

  void _processImage(CameraImage cameraImage) async {
    if (!_alreadyCheckingImage && mounted) {
      _alreadyCheckingImage = true;
      try {


        final T results =
            await _detect<T>(cameraImage, widget.detector, _rotation);
//        print("cameraImage width"+cameraImage.width.toString());
//        print("cameraImage height"+cameraImage.height.toString());
//        print("widget.cameraController.value.aspectRatio"+widget.cameraController.value.aspectRatio.toString());
//        print("widget.cameraController.value.previewSize width"+widget.cameraController.value.previewSize.width.toString());
//        print("widget.cameraController.value.previewSize height"+widget.cameraController.value.previewSize.height.toString());


     /*   var t = DateTime.now().millisecondsSinceEpoch;
        print("dt = " +(t-_ts).toString());
        _ts= t;*/
        widget.onResult(new ImageDetectionTuple(cameraImage,results,
            _rotation, widget.boundingBoxExtractor, _nativeDeviceOrientation));
      } catch (ex, stack) {
        debugPrint('$ex, $stack');
      }
      _alreadyCheckingImage = false;
    }
  }

  void toggle() {
    if (_isStreaming && widget.cameraController.value.isStreamingImages) {
      stop();
    } else {
      start();
    }
  }

  Widget _getPicture() {
    if (_lastImage != null) {
      final file = File(_lastImage);
      if (file.existsSync()) {
        return Image.file(file);
      }
    }

    return Container();
  }
}`

it is based on flutter_camera_ml_vision with minor improvments

when I upgrade the camera plugin I had to change the lines:

  child: SizedBox(
      width: widget.cameraController.value.previewSize.height,
      height: widget.cameraController.value.previewSize.width,
      child: cameraPreview,
    ),

NOTE that the width and height are flipped.

I want to know if it's a bug or if theres a logical reason to it

Thanks for your help

**Comment by TahaTesser** [comment] 2021-03-01 11:44
Hi @eliaweiss 
Your code has third-party packages
Please provide your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you
