### ISSUE TITLE
A KeyRepeatEvent is dispatched, but the state shows that the physical key is not pressed

### ISSUE THREAD

**Issue by Ali-Kheiri** [flutter/flutter#133744] opened 2023-08-31 08:08 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

```
A KeyRepeatEvent is dispatched, but the state shows that the physical key is not pressed. If this occurs in real application, please report this bug to Flutter. If this occurs in unit tests, please ensure that simulated events follow Flutter's event model as documented in `HardwareKeyboard`. This was the event: KeyRepeatEvent#7d0f6(physicalKey: PhysicalKeyboardKey#52951(usbHidUsage: "0x00070050", debugName: "Arrow Left"), logicalKey: LogicalKeyboardKey#860f3(keyId: "0x100000302", keyLabel: "Arrow Left", debugName: "Arrow Left"), character: null, timeStamp: 0:00:06.970337)
'package:flutter/src/services/hardware_keyboard.dart':
hardware_keyboard.dart:1
Failed assertion: line 434 pos 16: '_pressedKeys.containsKey(event.physicalKey)'

``` 

### Expected results

using bloc state management, emit same state via different values .

### Actual results

I had defined two events. I also defined another event that, when creating it, received some values ​​from a block defined as mutlibloc and immediately passed it to the event. I encountered this error

### Code sample

`if (event is SetHotLeadEvent) {
        emit(const ClientsInitialLoading(
            message: 'Custom loading message'));
        final response = await getIt
            .get<IAddClientRepo>()
            .setHotLead(selectedLeadId: event.clientModel.id);
        response.fold(
          (l) => emit(
            ClientsLoaded(
              clientListModel:
                  ClientListModel(currentPage: 1, clients: [], reachMax: true),
              error: LoadMoreError(
                  message: 'Custom error msg'),
            ),
          ),
          (r) async {
            final response =
                await responseBuilder(event.filterDataModel, page: 1);
            response.fold(
                (l) => emit(
                      ClientsLoaded(
                        clientListModel: ClientListModel(
                            currentPage: 1, clients: [], reachMax: true),
                        error: LoadMoreError(
                            message: 'error msg'),
                      ),
                    ), (r) {
              final clientList = ClientListModel(
                  clients: r.clientListModel.clients,
                  currentPage: r.clientListModel.currentPage + 1,
                  reachMax: r.clientListModel.reachMax);

              if (clientList.clients.isEmpty) {
                emit(ClientsEmpty());
              } else {
                //Adding  to existing list
                clientList.clients =
                    clientList.clients + r.clientListModel.clients;
                clientList.currentPage = r.clientListModel.currentPage + 1;
                clientList.reachMax = r.clientListModel.reachMax;

                emit(ClientsLoaded(clientListModel: clientList));
              }
            });
          },
        );
      }`
      
      
      and my other events : 

-       ClientsLoadEvent

-       ClientsLoadMoreEvent
      
  

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by dam-ease** [comment] 2023-08-31 11:18
Hi @Ali-Kheiri. Thanks for filing this. From the logs, not sure its related to the code sample provided. It seems similar/related to https://github.com/flutter/flutter/issues/107972.
Closing this as a duplicate of an already open issue, kindly comment, upvote and follow up on that issue for updates. If you disagree, kindly comment here and I'd reopen this.
Thank you!

**Closed** 2023-08-31 11:18 UTC
Labels: in triage
