### ISSUE TITLE
[tool_crash] ArgumentError: Invalid argument(s): Invalid type for "path": null

### ISSUE THREAD

**Issue by pontipd** [flutter/flutter#101271] opened 2022-04-04 01:40 UTC
## Command
```
flutter create --template app --overwrite .
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ArgumentError: Invalid argument(s): Invalid type for "path": null
```
#0      FileSystem.getPath (package:file/src/interface/file_system.dart:160:7)
#1      LocalFileSystem.directory (package:file/src/backends/local/local_file_system.dart:23:41)
#2      ErrorHandlingFileSystem.directory (package:flutter_tools/src/base/error_handling_io.dart:130:24)
#3      _templateImageDirectory (package:flutter_tools/src/template.dart:369:21)
<asynchronous suspension>
#4      Template.merged (package:flutter_tools/src/template.dart:129:16)
<asynchronous suspension>
#5      CreateBase.renderMerged (package:flutter_tools/src/commands/create_base.dart:428:31)
<asynchronous suspension>
#6      CreateBase.generateApp (package:flutter_tools/src/commands/create_base.dart:447:23)
<asynchronous suspension>
#7      CreateCommand.runCommand (package:flutter_tools/src/commands/create.dart:292:31)
<asynchronous suspension>
#8      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1140:27)
<asynchronous suspension>
#9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#10     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#11     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#13     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.2.1 21D62 darwin-x64, locale en-TH)
    • Flutter version 2.8.1 at /Users/staff/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (4 months ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/staff/Library/Android/sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code (version 1.66.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.36.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 100.0.4896.60

• No issues found!

```

## Flutter Application Metadata
No pubspec in working directory.

**Comment by danagbemava-nc** [comment] 2022-04-04 10:21
Duplicate of #56811

**Closed by danagbemava-nc** 2022-04-04 10:21 UTC
Labels: in triage
