### ISSUE TITLE
[Web] `ListView` scrollbar does not work when `SemanticsBinding.instance.ensureSemantics()` is called

### ISSUE THREAD

**Issue by MatteoAntolini** [flutter/flutter#152322] opened 2024-07-25 16:33 UTC
### Steps to reproduce

1. Create a new Flutter project.
2. Add `SemanticsBinding.instance.ensureSemantics()` in the `main` function.
3. Create a `ListView` with a scrollbar.
4. Run the application on web.
5. Try to scroll the `ListView` with the scrollbar.

### Expected results

The scrollbar should work properly, allowing the user to scroll through the `ListView` when interacting with the scrollbar.

### Actual results

The scrollbar does not function, and the user is unable to scroll through the `ListView` by interacting with the scrollbar.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter/semantics.dart';

void main() {
  runApp(const TestApp());
  SemanticsBinding.instance.ensureSemantics();
}

class TestApp extends StatelessWidget {
  const TestApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: Scaffold(
        body: TestPage(),
      ),
    );
  }
}

class TestPage extends StatelessWidget {
  const TestPage({super.key});

  @override
  Widget build(BuildContext context) {
    return Center(
      child: SizedBox(
        height: 500,
        width: 300,
        child: Container(
            decoration: BoxDecoration(
              boxShadow: kElevationToShadow[2],
              color: Colors.white,
              borderRadius: BorderRadius.circular(4),
            ),
            child: ListView.builder(
              padding: EdgeInsets.zero,
              itemBuilder: (context, index) =>
                  ListTile(title: const Text("TEST"), onTap: () {}),
              itemCount: 20,
            )),
      ),
    );
  }
}

```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.22.2, on Microsoft Windows [Versione 10.0.19045.4651], locale it-IT)
[☠] Windows Version (the doctor check crashed)
    X Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know
      about this issue at https://github.com/flutter/flutter/issues.
    X ProcessException: Failed to find "powershell" in the search path.
        Command: powershell
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2023.2)
[√] VS Code (version 1.91.1)
[√] Connected device (3 available)
[√] Network resources

! Doctor found issues in 2 categories.
```

</details>

**Comment by danagbemava-nc** [comment] 2024-07-26 08:58
Hi @MatteoAntolini, I just tested the code sample on `stable 3.22.3` and it seems to work as expected. Can you upgrade to this version to see if this issue still reproduces for you? See the recording below. 

https://github.com/user-attachments/assets/90696f37-aa1c-41fa-83d3-fbad42c40f8f

**Comment by MatteoAntolini** [comment] 2024-07-26 16:15
I upgraded flutter to `3.22.3` 
Still not working as expected


https://github.com/user-attachments/assets/9ba30969-f6ba-46c6-93d5-8488f737b80b

**Comment by danagbemava-nc** [comment] 2024-07-29 06:43
Hi @MatteoAntolini, can you check on the `master/main` branch to see if you're consistently able to interact with the `scrollbar`. I re-tested on stable and I wasn't able to always interact with the scrollbar, but it seemed to have improved on the master channel.

**Comment by MatteoAntolini** [comment] 2024-07-31 08:56
Hi @danagbemava-nc, I switched to the Flutter master channel. Now it seems that the scrollbar is working properly. Unfortunately, there is now a shadow of an invisible element extending beyond the boundaries of the ListView.



https://github.com/user-attachments/assets/8e3ba3f9-aff3-4b14-9416-a9b009779506



<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, 3.24.0-1.0.pre.364, on Microsoft Windows [Versione 10.0.19045.4651], locale it-IT)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components        
[√] Android Studio (version 2023.2)
[√] VS Code (version 1.91.1)
[√] Connected device (3 available)
[√] Network resources

! Doctor found issues in 1 category.
```

</details>

**Comment by danagbemava-nc** [comment] 2024-08-01 06:28
Hi @MatteoAntolini, thanks for confirming that the scrollbar issue has indeed been fixed on the master channel. 

Regarding the unexpected shadow, kindly file a new issue so that it can be properly tracked. Please feel free to ping me on that issue. 

Per our triage policy, I'll be closing this issue since it has been fixed on the master channel. 

Thank you

**Closed by danagbemava-nc** 2024-08-01 06:28 UTC
Labels: in triage

**Comment by MatteoAntolini** [comment] 2024-08-07 07:46
Tested on Flutter 3.24

The shadow is not visible and the widget works as expected
