### ISSUE TITLE
Catalina tests have closed the tree due to missing device

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#70248] opened 2020-11-11 00:39 UTC
```
2020-11-10T16:36:30.848888: "/Users/flutter/.cocoon/flutter/bin/flutter" exit code: 0
2020-11-10T16:36:30.861078: Task failed: DeviceException: No connected iOS devices found.2020-11-10T16:36:30.861333: 

Stack trace:
2020-11-10T16:36:30.883336: package:flutter_devicelab/framework/adb.dart 683:7         IosDeviceDiscovery.discoverDevices
===== asynchronous gap ===========================
dart:async                                                 _asyncErrorWrapperHelper
package:flutter_devicelab/framework/framework.dart         _TaskRunner._performTask.<fn>
package:stack_trace                                        Chain.capture
package:flutter_devicelab/framework/framework.dart 216:11  _TaskRunner._performTask
package:flutter_devicelab/framework/framework.dart 119:41  _TaskRunner.run
```

**Comment by keyonghan** [comment] 2020-11-11 00:59
marked as a duplicate of https://github.com/flutter/flutter/issues/70244.

**Closed by keyonghan** 2020-11-11 00:59 UTC
Labels: P0, team: infra
