### ISSUE TITLE
Bad state: Future already completed

### ISSUE THREAD

**Issue by bartektartanus** [flutter/flutter#16602] opened 2018-04-15 10:53 UTC
## Steps to Reproduce

I'm calling:
```dart
Navigator.popUntil(context, (r)=>false);
```

and getting this error:
## Logs

```
I/flutter ( 4464): ══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
I/flutter ( 4464): The following StateError was thrown while handling a gesture:
I/flutter ( 4464): Bad state: Future already completed
I/flutter ( 4464): When the exception was thrown, this was the stack:
I/flutter ( 4464): #1      Route.didComplete (package:flutter/src/widgets/navigator.dart:185:19)
I/flutter ( 4464): #2      Route.didPop (package:flutter/src/widgets/navigator.dart:173:5)
I/flutter ( 4464): #3      OverlayRoute.didPop (package:flutter/src/widgets/routes.dart:58:36)
I/flutter ( 4464): #4      TransitionRoute.didPop (package:flutter/src/widgets/routes.dart:209:18)
I/flutter ( 4464): #5      _ModalRoute&TransitionRoute&LocalHistoryRoute.didPop (package:flutter/src/widgets/routes.dart:369:18)
I/flutter ( 4464): #6      NavigatorState.pop (package:flutter/src/widgets/navigator.dart:1683:15)
I/flutter ( 4464): #7      NavigatorState.popUntil (package:flutter/src/widgets/navigator.dart:1722:7)
I/flutter ( 4464): #8      Navigator.popUntil (package:flutter/src/widgets/navigator.dart:1101:27)
I/flutter ( 4464): #9      PresentationWidgetState.header.<anonymous closure> (package:conference_app/presentation.dart:214:27)
I/flutter ( 4464): #10     _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:490:14)
I/flutter ( 4464): #11     _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:545:30)
I/flutter ( 4464): #12     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
I/flutter ( 4464): #13     TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:161:9)
I/flutter ( 4464): #14     TapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:123:7)
I/flutter ( 4464): #15     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
I/flutter ( 4464): #16     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:147:20)
I/flutter ( 4464): #17     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:121:22)
I/flutter ( 4464): #18     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:101:7)
I/flutter ( 4464): #19     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:64:7)
I/flutter ( 4464): #20     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:48:7)
I/flutter ( 4464): #21     _invoke1 (dart:ui/hooks.dart:134:13)
I/flutter ( 4464): #22     _dispatchPointerDataPacket (dart:ui/hooks.dart:91:5)
I/flutter ( 4464): (elided one frame from package dart:async)
I/flutter ( 4464): Handler: onTap
I/flutter ( 4464): Recognizer:
I/flutter ( 4464):   TapGestureRecognizer#b584e(debugOwner: GestureDetector, state: ready, won arena, finalPosition:
I/flutter ( 4464):   Offset(20.7, 49.4), sent tap down)
I/flutter ( 4464): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter ( 4464): Another exception was thrown: 'package:flutter/src/widgets/navigator.dart': Failed assertion: line 1846 pos 12: '!_debugLocked': is not true.
```
## Flutter Doctor
```
[✓] Flutter (Channel dev, v0.2.10, on Mac OS X 10.13.4 17E199, locale pl-PL)
    • Flutter version 0.2.10 at ...
    • Framework revision d6d874474b (9 days ago), 2018-04-06 13:23:16 -0700
    • Engine revision d2b69fec75
    • Dart version 2.0.0-dev.46.0.flutter-09e1766e6c

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at ...
    • Android NDK at ...
    • Platform android-27, build-tools 27.0.3
    • Java binary at: ...
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.3)
    • Xcode at ...
    • Xcode 9.3, Build version 9E145
    • ios-deploy 1.9.2
    • CocoaPods version 1.4.0

[✓] Android Studio (version 3.0)
    • Android Studio at ...
    • Flutter plugin version 23.1.1
    • Dart plugin version 171.4424
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] Android Studio (version 3.1)
    • Android Studio at ...
    • Flutter plugin version 23.2.2
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] Connected devices (2 available)
    • Android SDK built for x86 • emulator-5554                        • android-x86 • Android 6.0 (API 23) (emulator)
    • iPhone X                  • 74D25CBC-32DB-40A9-A12D-A3F61936B347 • ios         • iOS 11.3 (simulator)
```

**Comment by SoaresGabriel** [comment] 2018-07-14 18:01
Same error with
`Navigator.popUntil(context, ModalRoute.withName('/'));`

**Comment by zoechi** [comment] 2018-07-16 11:23
@SoaresGabriel can you please add the output of `flutter doctor -v`?

**Comment by zoechi** [comment] 2018-07-17 07:11
@SoaresGabriel can you create a minimal reproduction?
Create a new project with `flutter create` and add the code to `lib/main.dart` that is required to reproduce the issue?

**Comment by SoaresGabriel** [comment] 2018-07-17 13:57
@zoechi yes, there it is:
https://gist.github.com/SoaresGabriel/75f3df8fa5c4d18b6d097a1b62b3cd1b

Go to page b, and click pop until, and the exception is thrown:

```
I/flutter (11670): ══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
I/flutter (11670): The following StateError was thrown while handling a gesture:
I/flutter (11670): Bad state: Future already completed
I/flutter (11670): 
I/flutter (11670): When the exception was thrown, this was the stack:
I/flutter (11670): #1      Route.didComplete (package:flutter/src/widgets/navigator.dart:184:19)
I/flutter (11670): #2      Route.didPop (package:flutter/src/widgets/navigator.dart:172:5)
I/flutter (11670): #3      OverlayRoute.didPop (package:flutter/src/widgets/routes.dart:58:36)
I/flutter (11670): #4      TransitionRoute.didPop (package:flutter/src/widgets/routes.dart:209:18)
I/flutter (11670): #5      _ModalRoute&TransitionRoute&LocalHistoryRoute.didPop (package:flutter/src/widgets/routes.dart:369:18)
I/flutter (11670): #6      NavigatorState.pop (package:flutter/src/widgets/navigator.dart:1682:15)
I/flutter (11670): #7      NavigatorState.popUntil (package:flutter/src/widgets/navigator.dart:1721:7)
I/flutter (11670): #8      Navigator.popUntil (package:flutter/src/widgets/navigator.dart:1100:27)
I/flutter (11670): #9      PageB.build.<anonymous closure> (file:///mnt/Data/Developer/IdeaProjects/flutter_navigation_test/lib/main.dart:50:23)
I/flutter (11670): #10     _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:494:14)
I/flutter (11670): #11     _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:549:30)
I/flutter (11670): #12     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
I/flutter (11670): #13     TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:161:9)
I/flutter (11670): #14     TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:94:7)
I/flutter (11670): #15     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:315:9)
I/flutter (11670): #16     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:73:12)
I/flutter (11670): #17     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:11)
I/flutter (11670): #18     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:143:19)
I/flutter (11670): #19     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:121:22)
I/flutter (11670): #20     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:101:7)
I/flutter (11670): #21     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:64:7)
I/flutter (11670): #22     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:48:7)
I/flutter (11670): #23     _invoke1 (dart:ui/hooks.dart:134:13)
I/flutter (11670): #24     _dispatchPointerDataPacket (dart:ui/hooks.dart:91:5)
I/flutter (11670): (elided one frame from package dart:async)
I/flutter (11670): 
I/flutter (11670): Handler: onTap
I/flutter (11670): Recognizer:
I/flutter (11670):   TapGestureRecognizer#86893(debugOwner: GestureDetector, state: possible, won arena, finalPosition:
I/flutter (11670):   Offset(203.5, 361.5), sent tap down)
I/flutter (11670): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (11670): Another exception was thrown: 'package:flutter/src/widgets/navigator.dart': Failed assertion: line 1845 pos 12: '!_debugLocked': is not true.
I/flutter (11670): Another exception was thrown: 'package:flutter/src/widgets/navigator.dart': Failed assertion: line 1845 pos 12: '!_debugLocked': is not true.
```

**Comment by SoaresGabriel** [comment] 2018-07-17 14:02
I just found the error, i was creating the PageRoutes, but was not giving a name to it. I fix the above example by change the pages in MyApp:
```
static final pages = {
  '/': (settings) => MaterialPageRoute(builder: (context) => PageA(), settings: settings),
  PageB.routeName: (settings) => MaterialPageRoute(builder: (context) => PageB(), settings: settings),
};
```
And onGenerateRoute in the MaterialApp widget:
```
onGenerateRoute: (settings) {
  return pages[settings.name](settings);
},
```

I think the error message should be clearer.

**Comment by zoechi** [comment] 2018-07-17 14:04
Great! I guess we leave this open as a reminder to improve the error output.

**Comment by luigifaticoso** [comment] 2018-07-18 12:55
I gave them a name this way:
```
var routes = <String, WidgetBuilder>{
      EventList.routeName: (BuildContext context) =>
          new EventList(title: "EventList")
};
```
and in the MaterialApp:
`routes: routes`
how should i fix the popUntil?

**Comment by SoaresGabriel** [comment] 2018-07-18 13:20
@luigifaticoso I think it should work that way with routes. A similar example worked here.
Maybe the problem is something else. @zoechi

**Comment by goderbauer** [comment] 2019-01-08 21:04
Any change somebody can post a self-contained minimal example that reproduces this error? Ideally, I should be able to just copy & paste the code and run it to be able to see the failure. That will make it much easier for me to understand how we can improve the error message here.

**Comment by Philip-Wu** [comment] 2019-01-14 12:10
In my case, I get the error if I do the following:

1. Navigator.pushNamed()
2. Navigator.pushNamedAndRemoveUntil()
3. Navigator.popUntil()

The issue is resolved, then i change step 2 to be as follows:
1. Navigator.pushNamed()
2. Navigator.pushNamed()
3. Navigator.popUntil()

**Comment by goderbauer** [comment] 2019-01-14 18:13
@Philip-Wu Any chance you can post a complete code example that I can copy and paste to run? That will make debugging this a lot easier.

**Comment by Philip-Wu** [comment] 2019-01-14 23:10
I Just realized my mistake was the same as the others, in that I had the wrong route name.
The error message should say something like 'route does not exist'.

Here's an example piece of code that recreates the error (on my part) but could use a better error description. When you run the app, from the menu choose 'Screen1', then 'popUntilNotOnStack'

`import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
      ),
      routes: {
        '/': (context) => MyHomePage(title: 'Root'),
        '/screen1': (context) => MyHomePage(title: 'Screen 1'),
        '/popUntil': (context) => MyHomePage(title: 'popUntilNotOnStack'),
      },
      initialRoute: '/',
      //home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      // This call to setState tells the Flutter framework that something has
      // changed in this State, which causes it to rerun the build method below
      // so that the display can reflect the updated values. If we changed
      // _counter without calling setState(), then the build method would not be
      // called again, and so nothing would appear to happen.
      _counter++;
    });
  }

  void _menuSelection( String menuSelection) {
    print('menuSelection: '+menuSelection);
    switch (menuSelection) {
      case 'Screen1':
        Navigator.pushNamed(context, '/screen1');
        //Navigator.popUntil(context, ModalRoute.withName('/'));
        return;
      case 'popUntil':
      /**
       *
       *
       * THIS LINE FAILS DUE TO WRONG ROUTE NAME
       *
       *
       */
        Navigator.popUntil(context, ModalRoute.withName('/notOnStack'));
        return;
    }
  }


  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
        actions: <Widget>[PopupMenuButton<String>(
          onSelected: _menuSelection,
          itemBuilder: (BuildContext context) =>
          [
            PopupMenuItem<String>(
                value: 'Screen1',
                child: Text('Screen1')),
            PopupMenuItem<String>(
                value: 'popUntil',
                child: Text('popUntil')),
          ],
        )
        ],
      ),
      body: Center(
        // Center is a layout widget. It takes a single child and positions it
        // in the middle of the parent.
        child: Column(
          // Column is also layout widget. It takes a list of children and
          // arranges them vertically. By default, it sizes itself to fit its
          // children horizontally, and tries to be as tall as its parent.
          //
          // Invoke "debug painting" (press "p" in the console, choose the
          // "Toggle Debug Paint" action from the Flutter Inspector in Android
          // Studio, or the "Toggle Debug Paint" command in Visual Studio Code)
          // to see the wireframe for each widget.
          //
          // Column has various properties to control how it sizes itself and
          // how it positions its children. Here we use mainAxisAlignment to
          // center the children vertically; the main axis here is the vertical
          // axis because Columns are vertical (the cross axis would be
          // horizontal).
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.display1,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
`

**Comment by GianfrancoMS** [comment] 2019-01-22 22:07
If I don't use named routers because I need to pass parameters to other pages, how can I use popUntil then?

**Comment by DevarshRanpara** [comment] 2019-03-01 08:15
I have different kind of situation on this error..!
I used sign in dialogue in my login page, but when signin process completes my home page opens and dialogue is keep running,
my 
dialogue class is in different file,

My dialogue calling is as above,
 
`  
  void _submit() async {
    final form = formKey.currentState;
    if (form.validate()) {
      form.save();
      Dialogs dialogs=Dialogs(context);
      dialogs.setMessage(Strings.signInMessage);
      dialogs.show();
      String res = await loginModel.auth(_userId, _password);
      dialogs.hide();        
      _gotoHome(res);
    }
  }
`

and my dialogue class is as above

`
class Dialogs {
  BuildContext buildContext;
  String message = Strings.loading;

  Dialogs(this.buildContext);

  void setMessage(String mess) {
    this.message = mess;
  }

  void show() {
    _showDialog();
  }

  void hide() {
    Navigator.pop(buildContext);
  }

  _showDialog() {
    showDialog(
      context: buildContext,
      barrierDismissible: false,
      builder: (BuildContext context) {
        // return object of type Dialog
        return AlertDialog(
          content: SizedBox(
            height: 45.0,
            child: Center(
              child: Row(
                children: <Widget>[
                  SizedBox(width: 10.0),
                  CircularProgressIndicator(),
                  SizedBox(width: 20.0),
                  Text(
                    message,
                    style: TextStyle(color: Colors.white, fontSize: 20.0),
                  )
                ],
              ),
            ),
          ),
        );
      },
    );
  }
}

`

**Comment by DevarshRanpara** [comment] 2019-03-01 13:04
Hi,
I have same issue,

i am calling my loading dialogue,
but when i close it,
it keeps running,

my dialogue is in different class

my code is as follows,

`
Dialogs dialogs=Dialogs(context);
dialogs.setMessage(Strings.signInMessage);
dialogs.show();
String res = await loginModel.auth(_userId, _password);
dialogs.hide();

dialogue hide method is as follows

void hide() {
Navigator.pop(buildContext);
}

`

it shows this error


E/flutter ( 5356): [ERROR:flutter/shell/common/shell.cc(184)] Dart Error: Unhandled exception:
E/flutter ( 5356): Bad state: Future already completed

**Comment by rajeshzmoke** [comment] 2019-03-06 09:21
@ViniciusSossela dude u deserve a medal or something..

```
MaterialApp(
            title: 'Flutter Demo',
            debugShowCheckedModeBanner: false,
            theme: snapshot.hasData ? snapshot.data : null,
            // theme: _themeData,
            // onGenerateRoute: ,
            routes: <String, WidgetBuilder>{
              WelcomeScreen.routeName: (BuildContext context) =>
                  WelcomeScreen(),
              LoginScreen.routeName: (BuildContext context) => LoginScreen(),
              AuthConfirmScreen.routeName: (BuildContext context) =>
                  AuthConfirmScreen(),
              SupportScreen.routeName: (BuildContext context) => SupportScreen(),
              SupportTeamScreen.routeName: (BuildContext context) =>
                  SupportTeamScreen(),
              SupportPermissionScreen.routeName: (BuildContext context) =>
                  SupportPermissionScreen(),
              SpecialtiesScreen.routeName: (BuildContext context) =>
                  SpecialtiesScreen(),
            },
            home: WelcomeScreen(),
          );
```
This is the flow
`Welcome -> Login ->Auth ->Support -> SupportTeam -> SupportPermission`  then i want to go back to `Support`

```
Navigator.popUntil(
                  context, ModalRoute.withName(SupportScreen.routeName));
```
throws me the error posted by OP

following @ViniciusSossela  advice solves it... but why is the Documentation not clear on this implementation?..

**Comment by ChallenAi** [comment] 2019-04-06 10:20
> I had the same issue... The problem was the same that @soaresgabriel said, but I was not navigating directly from routes. I did navigate with the code below and I wasn't setting the name of it, like in the @soaresgabriel case.
> 
> ```dart
> Navigator.of(context).push(
>             MaterialPageRoute(
>               builder: (context) => MyFuckingPage(),
>             ),
>           );
> ```
> 
> Then I solved with:
> 
> ```dart
> Navigator.of(context).push(
>             MaterialPageRoute(
>               settings: RouteSettings(name: MyFuckingPage.routeName), <----------
>               builder: (context) => MyFuckingPage(),
>             ),
>           );
> ```
> 
> and then the popUntil worked:
> 
> ```dart
> Navigator.of(context).popUntil(
>                           ModalRoute.withName(MyFuckingPage.routeName));
> ```
> 
> @zoechi To me the error was also not clear... I just realized that the name was missing because I found this issu on flutter github.

awesome solution, I just solved this problem according to your answer.
`
        page =  new PageRouteBuilder(
          settings: RouteSettings(name: "/"),
          pageBuilder: ...
        )

`

**Comment by vanlooverenkoen** [comment] 2019-05-31 14:23
I had a problem where I had 2 Navigators. the root navigator is used. https://stackoverflow.com/a/50683571/5115254

```Navigator.of(context, rootNavigator: true).pop(result)```

**Comment by waqasraz** [comment] 2019-06-24 20:37
When I remove the homepage from the route popUntill worked. Because I was setting a home property in MaterialApp Widget as well as the same route in the routes.

**Comment by HappyGhostz** [comment] 2019-09-27 02:33
The Same problem :when I use the ' return await Navigator.of(context).pushReplacement(route);'

E/flutter (21450): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: Bad state: Future already completed
E/flutter (21450): #0      _AsyncCompleter.complete (dart:async/future_impl.dart:39:31)
E/flutter (21450): #1      Route.didComplete (package:flutter/src/widgets/navigator.dart:189:19)
E/flutter (21450): #2      NavigatorState.pushReplacement.<anonymous closure> (package:flutter/src/widgets/navigator.dart:1846:13)
E/flutter (21450): #3      TickerFuture.whenCompleteOrCancel.thunk (package:flutter/src/scheduler/ticker.dart:389:15)
E/flutter (21450): #4      _rootRunUnary (dart:async/zone.dart:1132:38)
E/flutter (21450): #5      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter (21450): #6      _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
E/flutter (21450): #7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
E/flutter (21450): #8      Future._propagateToListeners (dart:async/future_impl.dart:668:32)
E/flutter (21450): #9      Future._completeWithValue (dart:async/future_impl.dart:483:5)
E/flutter (21450): #10     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:513:7)
E/flutter (21450): #11     _rootRun (dart:async/zone.dart:1124:13)
E/flutter (21450): #12     _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter (21450): #13     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
E/flutter (21450): #14     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
E/flutter (21450): #15     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
E/flutter (21450): #16     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)

**Comment by Harag** [comment] 2019-10-01 18:57
Doing a pop before a pushRepacementNamed will also give you the error.

Navigator.pop(context);
Navigator.pushReplacementNamed(context, "/");


E/flutter ( 6044): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: Bad state: Future already completed
E/flutter ( 6044): #0      _AsyncCompleter.complete (dart:async/future_impl.dart:39:31)
E/flutter ( 6044): #1      Route.didComplete (package:flutter/src/widgets/navigator.dart:203:19)
E/flutter ( 6044): #2      NavigatorState.pushReplacement.<anonymous closure> (package:flutter/src/widgets/navigator.dart:1861:13)
E/flutter ( 6044): #3      TickerFuture.whenCompleteOrCancel.thunk (package:flutter/src/scheduler/ticker.dart:389:15)
E/flutter ( 6044): #4      _rootRunUnary (dart:async/zone.dart:1132:38)
E/flutter ( 6044): #5      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter ( 6044): #6      _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
E/flutter ( 6044): #7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
E/flutter ( 6044): #8      Future._propagateToListeners (dart:async/future_impl.dart:707:32)
E/flutter ( 6044): #9      Future._completeWithValue (dart:async/future_impl.dart:522:5)
E/flutter ( 6044): #10     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552:7)
E/flutter ( 6044): #11     _rootRun (dart:async/zone.dart:1124:13)
E/flutter ( 6044): #12     _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter ( 6044): #13     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
E/flutter ( 6044): #14     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
E/flutter ( 6044): #15     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
E/flutter ( 6044): #16     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)

**Comment by yuefeishao** [comment] 2019-10-30 10:13
Error thrown on navigator pop until : “!_debugLocked': is not true.”

    Navigator.of(context).popUntil( ModalRoute.withName('/setting'));

    原因：栈内没有对应路由的信息

    解决办法：对应路由跳转进栈，路由跳转出栈

**Comment by joaowd** [comment] 2019-11-01 19:35
I'm having the same issue

**Comment by uzumaki258** [comment] 2019-11-04 08:15
I still have same issue when use popuntil

**Comment by suryapermana92** [comment] 2019-11-17 11:17
> I had the same issue... The problem was the same that @soaresgabriel said, but I was not navigating directly from routes. I did navigate with the code below and I wasn't setting the name of it, like in the @soaresgabriel case.
> 
> ```dart
> Navigator.of(context).push(
>             MaterialPageRoute(
>               builder: (context) => MyFuckingPage(),
>             ),
>           );
> ```
> 
> Then I solved with:
> 
> ```dart
> Navigator.of(context).push(
>             MaterialPageRoute(
>               settings: RouteSettings(name: MyFuckingPage.routeName), <----------
>               builder: (context) => MyFuckingPage(),
>             ),
>           );
> ```
> 
> and then the popUntil worked:
> 
> ```dart
> Navigator.of(context).popUntil(
>                           ModalRoute.withName(MyFuckingPage.routeName));
> ```
> 
> @zoechi To me the error was also not clear... I just realized that the name was missing because I found this issu on flutter github.

I just had the same problem, I'm using named Routes but previously haven't give names to respective routes. This answer made my day! Thanks @ViniciusSossela

**Comment by julianbraasch** [comment] 2019-11-19 06:45
@suryapermana92 could you provide a small code snippet on how you fixed the problem with named routes? Mine are still broken...

**Comment by suryapermana92** [comment] 2019-11-19 11:04
sorry just saw this. @julianbraasch sure.

this is my route_generator.dart for my RouteGenerator class.

```
class RouteGenerator {
  static Route<dynamic> generateRoute(RouteSettings settings) {
    switch (settings.name) {
      case indexRoute:
        return MaterialPageRoute(builder: (_) => SplashScreen());
      case navigationRoute:
        return MaterialPageRoute(
            builder: (_) => NavigationScreen(),
          settings: RouteSettings(name: navigationRoute) // <----- here is where you give the name
        );
      case homeRoute:
        return MaterialPageRoute(builder: (_) => HomeScreen());
      case tutorialRoute:
        return MaterialPageRoute(builder: (_) => TutorialScreen());
      case loginRoute:
        return MaterialPageRoute(builder: (_) => LoginScreen());
   
      default:
        return _errorRoute();
    }
  }

  static Route<dynamic> _errorRoute() {
    return MaterialPageRoute(builder: (_) {
      return Scaffold(
        appBar: AppBar(
          title: Text('Error'),
        ),
        body: Center(child: Text('ERROR 404')),
      );
    });
  }
}
```

**Comment by julianbraasch** [comment] 2019-11-19 15:19
@suryapermana92 thank you. But I think we are still talking about different things. In my app, I am not using ```MaterialPageRoute``` explicitly. I give each route a name like this

```dart
class X extends StatefulWidget {
    static const String routeName = "/X";
    ...
}
```
and then navigate to that route by calling
```dart
Navigator.pushNamed(context, X.routeName);
```
so there is no way I can pass ```RouteSettings```.

**Comment by suryapermana92** [comment] 2019-11-19 15:36
@julianbraasch I am navigating with quite similar syntax:

```
Navigator.of(context).pushNamed(routeName, arguments: args);
```

 the settings also important for us later to pass arguments to the destination screen.

I suggest you check this article on medium https://medium.com/flutter-community/clean-navigation-in-flutter-using-generated-routes-891bd6e000df

maybe you can few hours fix your navigation and you can continue from there

**Comment by julianbraasch** [comment] 2019-11-19 15:45
@suryapermana92 I use the ```arguments``` parameter of ```pushNamed```:
```dart
@optionalTypeArgs
static Future<T> pushNamed<T extends Object>(
  BuildContext context,
  String routeName, {
  Object arguments,
 }) {
  return Navigator.of(context).pushNamed<T>(routeName, arguments: arguments);
}
```
Thanks for the article link, I will check it out.

**Comment by saravananmnm** [comment] 2019-12-10 11:13
[ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: Bad state: Future already completed
E/flutter ( 7601): #0      _AsyncCompleter.complete (dart:async/future_impl.dart:39:31)
E/flutter ( 7601): #1      Route.didComplete (package:flutter/src/widgets/navigator.dart:203:19)
E/flutter ( 7601): #2      NavigatorState.pushReplacement.<anonymous closure> (package:flutter/src/widgets/navigator.dart:1861:13)
E/flutter ( 7601): #3      TickerFuture.whenCompleteOrCancel.thunk (package:flutter/src/scheduler/ticker.dart:389:15)
E/flutter ( 7601): #4      _rootRunUnary (dart:async/zone.dart:1132:38)
E/flutter ( 7601): #5      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter ( 7601): #6      _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
E/flutter ( 7601): #7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
E/flutter ( 7601): #8      Future._propagateToListeners (dart:async/future_impl.dart:707:32)
E/flutter ( 7601): #9      Future._completeWithValue (dart:async/future_impl.dart:522:5)
E/flutter ( 7601): #10     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552:7)
E/flutter ( 7601): #11     _rootRun (dart:async/zone.dart:1124:13)
E/flutter ( 7601): #12     _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter ( 7601): #13     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
E/flutter ( 7601): #14     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
E/flutter ( 7601): #15     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
E/flutter ( 7601): #16     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
E/flutter ( 7601):

**Comment by saravananmnm** [comment] 2019-12-10 11:18
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.9.1+hotfix.6, on Microsoft Windows [Version 10.0.18362.476], locale en-IN)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Android Studio (version 3.5)
[√] Connected device (1 available)

• No issues found!

**Comment by saravananmnm** [comment] 2019-12-10 11:20
` Navigator.pushReplacement(
      context,
      new CupertinoPageRoute(builder: (context) => data),
    );`

**Comment by tony123S** [comment] 2020-02-07 04:07
It works in my case !  So this is how I solve.

I using `popUntil` to back from pageC to pageA

PageC

 `Navigator.of(context).popUntil(ModalRoute.withName(PageA.ROUTE));`

router.dart

```
case PageA.ROUTE:
        return MaterialPageRoute(
          settings: RouteSettings(name: PageA.ROUTE), <--- Important
          builder: (_) => ProxyProvider<ABCRepository,ABCBloc>(
            builder: (context, abcRepository, abcBloc) =>
                ABCBloc(repository: repository),
            dispose: (context, abcBloc) => abcBloc.dispose(),
            child: PageA(),
          ),
        );
```

**Comment by pixnbit** [comment] 2020-03-05 23:31
If you tried everything from above, i.e. all your routes are named. You might be in the same situation as me, I needed to popUntil to the first screen, which was launched by specifying `home:  `, the default name for that screen is not what you defined, it's '/', and you can override it with initialRoute. My builder is like this:

```
        builder: (context, darkThemeProvider, sessionProvider, child) {
          return MaterialApp(
            title: 'Abc',
            home:
                sessionProvider.loggedIn() ? DashboardScreen() : LoginScreen(),
            routes: <String, WidgetBuilder>{
              DashboardScreen.route: (context) => DashboardScreen(),
              LoginScreen.route: (context) => LoginScreen(),
            },
            initialRoute: sessionProvider.loggedIn() ? DashboardScreen.route : LoginScreen.route,
            onGenerateRoute: _generateRoute,
          );
        }
```

Both routes name mapping and the initialRoute overriding are needed.

**Closed** 2020-05-27 17:02 UTC
Labels: customer: crowd, f: routes, framework, severe: crash
