### ISSUE TITLE
Flutter run -d chrome HttpException

### ISSUE THREAD

**Issue by f-tepel** [flutter/flutter#75073] opened 2021-01-30 21:11 UTC
I am trying to run the flutter web version on Manjaro Linux. As you can see down below, my flutter doctor looks fine. When I try to start the sample (flutter create myapp) app I get a HttpException.

## Command
```
flutter run -d chrome
```

## Logs
HttpException
```
Oops; flutter has exited unexpectedly: "HttpException: , uri = http://localhost:43233/json".
A crash report has been written to /home/felix/Code/digitale-praxis/app/flutter_05.log.
```
```
[✓] Flutter (Channel master, 1.26.0-18.0.pre.90, on Linux, locale en_US.utf8)
    • Flutter version 1.26.0-18.0.pre.90 at /home/felix/snap/flutter/common/flutter
    • Framework revision 25134a16d1 (13 hours ago), 2021-01-29 23:52:30 -0800
    • Engine revision ce14c8a841
    • Dart version 2.12.0 (build 2.12.0-276.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/felix/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /snap/android-studio/current/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /opt/google/chrome/chrome

[✓] Android Studio
    • Android Studio at /snap/android-studio/current/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /snap/android-studio/current/android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 88.0.4324.96 unknown

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: beta
**Creation framework version**: 5d36f2e7f5387b6c751449258ade8e4e6edf99be
### Plugins
integration_test

**Comment by iapicca** [comment] 2021-01-31 13:47
@f-tepel 
can you attach the file mentioned in your logs `/home/felix/Code/digitale-praxis/app/flutter_05.log`

possible duplicate of https://github.com/flutter/flutter/issues/72522

**Comment by f-tepel** [comment] 2021-01-31 15:39
Its basically the same from what I posted plus:

## exception

HttpException: HttpException: , uri = http://localhost:43233/json

**Comment by f-tepel** [comment] 2021-01-31 19:09
This might be a problem with the snap.
I uninstalled flutter with:

`sudo snap remove flutter`

Then follow the manual install instructions [here](https://flutter.dev/docs/get-started/install/linux#install-flutter-manually)

In a nutshell you do: 

```
git clone https://github.com/flutter/flutter.git
export PATH="$PATH:`pwd`/flutter/bin"
flutter channel beta
flutter upgrade
flutter config --enable-web
cd /your_app
flutter run -d chrome
```

Still it is weird that the snap install did not work. But maybe it is just a problem on my local setup.

**Comment by TahaTesser** [comment] 2021-02-01 09:03
Hi @f-tepel 
This indeed seems to be an issue Flutter snap 
https://github.com/flutter/flutter/issues/73976
https://github.com/flutter/flutter/issues/74985
closing as duplicate
Glad to resolved with manual installation
Thank you

**Closed by TahaTesser** 2021-02-01 09:03 UTC

**Comment by iapicca** [comment] 2021-02-06 18:32
this is a snap installation issue, follow up [here](https://github.com/canonical/flutter-snap/issues/23)
