### ISSUE TITLE
Flutter Web Application Not Loading Offline Due to External Font Dependency

### ISSUE THREAD

**Issue by AtifShahzed** [flutter/flutter#135868] opened 2023-10-02 17:53 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Deploy the Flutter web application to an IIS server.
2. Disconnect the client machine from the internet.
3. Access the deployed app.

### Expected results

The app should load and function correctly even when the client machine is not connected to the internet.

### Actual results

I am currently working on a Flutter web application that needs to be deployed to a client's IIS server. The deployment process was straightforward, similar to deploying a normal website. However, we have encountered an issue where the app does not load when the client's machine is not connected to the internet. 

Upon investigation, I noticed that Flutter is fetching fonts from the internet by default, specifically from the URL: https://fonts.gstatic.com/s/roboto/v20/KFOmCnqEu92Fr1Me5WZLCzYlKw.ttf. This external font dependency is causing the app to fail to load on the client's machine when there is no internet connection.

The app fails to load due to the external font dependency.

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]
![image](https://github.com/flutter/flutter/assets/54445953/5a35e728-82df-44d2-95b9-aa76a2786204)

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by danagbemava-nc** [comment] 2023-10-03 08:19
Hi @AtifShahzed, the root cause of this issue is https://github.com/flutter/flutter/issues/60069. 

Kindly subscribe to the original issue for updates. 

Closing from here as duplicate. 

Thank youj

**Closed by danagbemava-nc** 2023-10-03 08:19 UTC
Labels: in triage
