### ISSUE TITLE
Flutter web 3.27 debug - TextFormField - DartError event_position_helper.dart:70:10 - The targeted input element must be the active input element

### ISSUE THREAD

**Issue by pbeccegato** [flutter/flutter#160155] opened 2024-12-12 10:45 UTC
### Steps to reproduce

1 Launch the app in Chrome from VSCode
2 Click on textformfield
3 Insert some chars
4 Click outside of the textformfield
5 Click inside the textformfield

### Expected results

Write into the textformfield without any errors

### Actual results

The debug pause; playing again, into the debug console I've got this error:

```
DartError: Assertion failed: org-dartlang-sdk:///lib/_engine/engine/pointer_binding/event_position_helper.dart:70:10
targetElement == domElement
"The targeted input element must be the active input element"
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 288:3     throw_
errors.dart:288
dart-sdk/lib/_internal/js_dev_runtime/private/profile.dart 110:39               assertFailed
profile.dart:110
dart-sdk/lib/_internal/js_dev_runtime/private/profile.dart 110:39               _computeOffsetForInputs
profile.dart:110
lib/_engine/engine/pointer_binding/event_position_helper.dart 38:14             computeEventOffsetToTarget
event_position_helper.dart:38
lib/_engine/engine/pointer_binding.dart 1088:30                                 [_convertEventsToPointerData]
pointer_binding.dart:1088
lib/_engine/engine/pointer_binding.dart 1016:9                                  <fn>
pointer_binding.dart:1016
lib/_engine/engine/pointer_binding.dart 948:7                                   <fn>
pointer_binding.dart:948
lib/_engine/engine/pointer_binding.dart 541:9                                   loggedHandler
pointer_binding.dart:541
dart-sdk/lib/_internal/js_dev_runtime/patch/js_allow_interop_patch.dart 212:27  _callDartFunctionFast1
```

Building the app and test it on webserver, the app works fine.

### Code sample

```
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            TextFormField(),
            const Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headlineMedium,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ), 
    );
  }
}
```

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs
various log parts

```
[   +6 ms] DevHandler: VmService proxy responded with an error:
           {jsonrpc: 2.0, id: 10, error: {code: -32601, message: Method not found, data: {jsonrpc: 2.0, method: _setStreamIncludePrivateMembers, id: 10, params: {streamId: Stdout, includePrivateMembers: false}}}}
[   +2 ms] This app is linked to the debug service: ws://127.0.0.1:49287/m32uQVXqjlM=/ws
[        ] DevHandler: VmService proxy responded with an error:
           {jsonrpc: 2.0, id: 11, error: {code: -32601, message: Method not found, data: {jsonrpc: 2.0, method: _setStreamIncludePrivateMembers, id: 11, params: {streamId: Stderr, includePrivateMembers: false}}}}
[   +3 ms] DevHandler: VmService proxy responded with an error:
           {jsonrpc: 2.0, id: 13, error: {code: -32601, message: Method not found, data: {jsonrpc: 2.0, method: _setStreamIncludePrivateMembers, id: 13, params: {streamId: Isolate, includePrivateMembers: false}}}}
[   +1 ms] DevHandler: VmService proxy responded with an error:
           {jsonrpc: 2.0, id: 14, error: {code: -32601, message: Method not found, data: {jsonrpc: 2.0, method: _setStreamIncludePrivateMembers, id: 14, params: {streamId: Extension, includePrivateMembers: false}}}}
[        ] Debug service listening on ws://127.0.0.1:49287/m32uQVXqjlM=/ws
Connecting to VM Service at ws://127.0.0.1:49287/m32uQVXqjlM=/ws
Connected to the VM Service.
[  +19 ms] DevHandler: VmService proxy responded with an error:
           {jsonrpc: 2.0, id: 18, error: {code: -32601, message: Method not found, data: {jsonrpc: 2.0, method: _setStreamIncludePrivateMembers, id: 18, params: {streamId: Isolate, includePrivateMembers: false}}}}
.....
           {jsonrpc: 2.0, id: 23, error: {code: -32602, message: The stream `ToolEvent` is not supported on web devices}}
[  +42 ms] DevHandler: VmService proxy responded with an error:
           {jsonrpc: 2.0, id: 29, error: {code: -32601, message: setLibraryDebuggable: Not supported on web devices}}
[        ] DevHandler: VmService proxy responded with an error:
           {jsonrpc: 2.0, id: 30, error: {code: -32601, message: setLibraryDebuggable: Not supported on web devices}}
.....
[        ] DevHandler: VmService proxy responded with an error:
           {jsonrpc: 2.0, id: 722, error: {code: -32601, message: setLibraryDebuggable: Not supported on web devices}}
[   +2 ms] ExpressionEvaluator: Evaluating "() { return true; }" at packages/flutter/src/widgets/unique_widget.dart
[   +6 ms] ExpressionEvaluator: Evaluating JS: "function () {
             try {
               return   (function() {
                   const dart_sdk = require('dart_sdk');
                   const dart_rti = dart_sdk.dart_rti;
                   const dart = dart_sdk.dart;
                   return dart.fn(() => true, dart_rti._Universe.eval(dart_rti._theUniverse(), "core|bool()", true));
                 }(

                 ))();
             } catch (error) {
               return error.name + ": " + error.message;
             }
           }" with scope: {}
[   +1 ms] ExpressionEvaluator: Evaluated "() { return true; }" to "{type: boolean, value: true}"
[+5262 ms] DartError: Assertion failed: org-dartlang-sdk:///lib/_engine/engine/pointer_binding/event_position_helper.dart:70:10
           targetElement == domElement
           "The targeted input element must be the active input element"
           dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 288:3     throw_
           dart-sdk/lib/_internal/js_dev_runtime/private/profile.dart 110:39               assertFailed
           dart-sdk/lib/_internal/js_dev_runtime/private/profile.dart 110:39               _computeOffsetForInputs
           lib/_engine/engine/pointer_binding/event_position_helper.dart 38:14             computeEventOffsetToTarget
           lib/_engine/engine/pointer_binding.dart 1088:30                                 [_convertEventsToPointerData]
           lib/_engine/engine/pointer_binding.dart 1016:9                                  <fn>
           lib/_engine/engine/pointer_binding.dart 948:7                                   <fn>
           lib/_engine/engine/pointer_binding.dart 541:9                                   loggedHandler
           dart-sdk/lib/_internal/js_dev_runtime/patch/js_allow_interop_patch.dart 212:27  _callDartFunctionFast1
```

### Flutter Doctor output

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.27.0, on macOS 15.1.1 24B2091 darwin-arm64, locale it-IT)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[!] Xcode - develop for iOS and macOS (Xcode 16.1)
    ✗ Unable to get list of installed Simulator runtimes.
    ✗ CocoaPods not installed.
        CocoaPods is a package manager for iOS or macOS platform code.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/to/platform-plugins
      For installation instructions, see https://guides.cocoapods.org/using/getting-started.html#installation
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.2)
[✓] VS Code (version 1.95.3)
[✓] Connected device (4 available)
[✓] Network resources

! Doctor found issues in 1 category.
```

**Comment by pbeccegato** [comment] 2024-12-12 13:18
> Thanks for the report @pbeccegato I was able to replicate this on latest stable wherein just hovering over the textfield throws the reported error. Although this doesn't occur on latest master which probably is fixed as part of #159804. Can you switch to latest master and re-run your scenario to check and confirm ?

You're wrigth. Switching on the latest master "Flutter 3.28.0-1.0.pre.87 • channel master", the issue is gone.

Many thanks.

**Comment by csells** [comment] 2024-12-13 05:03
This crashes my web based app using the latest stable (Flutter 3.27 from yesterday) when hovering over a `TextField`. Seems like this should be a candidate for a hotfix; lots of apps use `TextField`.

fyi: @kevmoo

**Comment by darshankawar** [comment] 2024-12-13 05:16
Yes, I agree, that on latest stable, just hovering over the textfield throws triggers the reported error. I will keep the issue open for team's attention and if this needs to be hot-fixed.

**Comment by Cocotus** [comment] 2024-12-15 17:08
Going to watch this issue, because its really annoying right now in latest stable while debugging flutter web apps.^^ Meanwhile I switched to master branch for flutter (terminal: flutter channel master), the problem is gone there.^^So here's hoping for a quick fix for the stable branch.

**Comment by drrnbrns** [comment] 2024-12-16 16:06
If anyone is severely impacted while we wait for a new stable version, you can uncheck "All Exceptions" and "Uncaught Exceptions" in the debugger breakpoints section so that the debugger doesn't stop.  Apart from that it's just a lot of console output you can ignore for now.

The alternative is to switch to master as mentioned above (`flutter channel master`).

**Comment by Reprevise** [comment] 2024-12-17 00:19
@yjbanov Is flutter/engine#56949 eligible for a CP to stable?

**Comment by acsweets** [comment] 2024-12-17 06:33
I also encountered the same problem

**Comment by Ssiswent** [comment] 2024-12-17 07:26
The same.

**Comment by Erekushin** [comment] 2024-12-17 08:54
so anyone has temporary solution for this error?

**Comment by heinrichmarais** [comment] 2024-12-17 11:25
> so anyone has temporary solution for this error?

Running `flutter channel master` then `flutter upgrade` fixed it for me.

**Comment by CellCS** [comment] 2024-12-17 13:14
Bug is also existing in 3.27.1, but not in 3.28-pre.

**Comment by FetFrumos** [comment] 2024-12-17 14:45
Have same issue in  3.27.1

**Comment by bennajah0** [comment] 2024-12-17 14:54
Same in 3.27.1

**Comment by mdebbar** [comment] 2024-12-17 18:17
This was fixed in https://github.com/flutter/engine/pull/56949.

A cherry-pick request was made in https://github.com/flutter/engine/pull/57246.

Duplicate of https://github.com/flutter/flutter/issues/159804

**Closed by mdebbar** 2024-12-17 18:17 UTC
Labels: a: text input, c: regression, c: crash, platform-web, has reproducible steps, team-web, fyi-text-input, found in release: 3.27

**Comment by CellCS** [comment] 2024-12-19 14:39
> > If anyone is severely impacted while we wait for a new stable version, you can uncheck "All Exceptions" and "Uncaught Exceptions" in the debugger breakpoints section so that the debugger doesn't stop. Apart from that it's just a lot of console output you can ignore for now.
> 
> Just an FYI, this doesn't fix the issue for me, on 3.27.1.

now using 3.28-pre by "flutter channel master" in development, hope 3.28 will be released soon.

**Comment by eduardofcr** [comment] 2024-12-20 13:11
after upgrade Chrome to 131.0.6778.204 and flutter to 3.27.1, the issue was solved.
It looks like it was a double bug...
the issue does not happens in Edge 131.0.2903.99, but I did not tried in Safari...

**Comment by j-fbriere** [comment] 2024-12-20 14:20
Just made the test of upgrading Chrome with Flutter stable.
Upgrading to Chrome 131.0.6778.204 (in my case 131.0.6778.205) and Flutter stable to 3.27.1 does **NOT** solve the problem.
The error: "The targeted input element must be the active input element" still appears.
The test was made on Windows 10 Pro.

**Comment by Errechydy** [comment] 2024-12-20 14:26
Same issue in 3.27.1

**Comment by MarceloRab** [comment] 2024-12-21 19:03
Same issue in 3.27.1

**Comment by MarceloRab** [comment] 2024-12-21 19:04
Same issue in 3.27.1

**Comment by tha022** [comment] 2024-12-21 23:00
Same issue here too
I have the same versions as j-fbriere
"Upgrading to Chrome 131.0.6778.204 (in my case 131.0.6778.205) and Flutter stable to 3.27.1 does NOT solve the problem."

**Comment by Abolfazl-MI** [comment] 2024-12-23 03:43
### have same bug on master with 3.27.0 :

### flutter doctor:
```
$ flutter doctor -v
[√] Flutter (Channel stable, 3.27.0, on Microsoft Windows [Version 10.0.19045.5247], locale en-US)
    • Flutter version 3.27.0 on channel stable at C:\Users\Abolfazl\Documents\dev\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 8495dee1fd (12 days ago), 2024-12-10 14:23:39 -0800
    • Engine revision 83bacfc525
    • Dart version 3.6.0
    • DevTools version 2.40.2
    ```

 the code 
 ```
 import 'package:coffeebar_shop_panel/utils/extensions/context.ext.dart';
import 'package:flutter/material.dart';
import 'package:iconsax_plus/iconsax_plus.dart';

class LoginScreen extends StatelessWidget {
  const LoginScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Container(
        color: context.theme.colorScheme.primary,
        width: context.mediaQueryData.size.width,
        height: context.mediaQueryData.size.height,
        child: Center(
          child: Card(
            child: Container(
              width: 300,
              height: 300,
              child: Column(
                spacing: 5,
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  Icon(
                    IconsaxPlusBold.coffee,
                    size: 40,
                  ),
                  Text('Coffee Bar'),
                  SizedBox(
                    height: 10,
                  ),
                  //login form
                  Form(
                    child: Padding(
                      padding: const EdgeInsets.all(8.0),
                      child: Column(
                        spacing: 10,
                        children: [
                          TextFormField(
                            decoration: InputDecoration(
                              labelText: 'Username',
                              // outline input border for all states
                              border: OutlineInputBorder(
                                borderRadius: BorderRadius.circular(10),
                              ),
                            ),
                          ),
                          TextFormField(
                            decoration: InputDecoration(
                              labelText: 'Password',
                              border: OutlineInputBorder(
                                borderRadius: BorderRadius.circular(10),
                              ),
                              prefixIcon: Icon(IconsaxPlusBold.eye),
                            ),
                            obscureText: true,
                          ),
                          ElevatedButton(
                            onPressed: () {
                              // context.navigator.pushReplacementNamed(AppRouteNames.mainWrapper);
                            },
                            child: Text('Login'),
                          )
                        ],
                      ),
                    ),
                  )
                ],
              ),
            ),
          ),
        ),
      ),
    );
  }
}
```

**Comment by Guillaume-Fortin** [comment] 2024-12-27 09:05
Same bug in 3.27.1 chrome 131.0.6778.205

**Comment by Dararii** [comment] 2024-12-27 15:55
So, what is the current workaround? Should I wait until Flutter v3.28 is released?

**Comment by Cocotus** [comment] 2024-12-27 15:59
> So, what is the current workaround? Should I wait until Flutter v3.28 is released?

Meanwhile I switched to master channel (typing: flutter channel master) branch from stable. With that development works fine at moment and the annoying error is gone. When 3.28 is released I while switch back to stable through terminal again :)

**Comment by torres-semernin** [comment] 2024-12-27 16:06
The current workaround is using flutter master channel. A fix is in the master channel but awaiting for a stable release.

-------- Original Message --------

**Comment by Reprevise** [comment] 2025-01-08 17:45
I think it's a combination of the holidays (people are on vacation) and the fact that flutter/engine was merged into flutter/flutter (the main repo) so I think the cherry picks have to be redone in flutter/flutter.

**Comment by Charlie-le4sp** [comment] 2025-01-11 23:20
Hello, the same thing happened to me...I thought it was a problem in my environment but no, from the beginning since I updated I started to have that problem, a problem that did not appear in version 3.22 which I used...while I will change from channel to flutter master, waiting for an official flutter solution 😓😓

**Comment by darshankawar** [comment] 2025-01-13 05:26
Everyone facing this issue, this has been fixed as hot-fix as part of https://github.com/flutter/engine/pull/57246.
Current status is https://github.com/flutter/engine/pull/57246#issuecomment-2581190108, so please have some patience until this is resolve.

**Comment by kevmoo** [comment] 2025-01-13 19:04
FYI: Flutter 3.27.2 has been tagged an the fix here is included.

**Comment by j-fbriere** [comment] 2025-01-13 20:21
> FYI: Flutter 3.27.2 has been tagged an the fix here is included.

What do you mean? There is no tag 3.27.2 in flutter git repository right now.

**Comment by kevmoo** [comment] 2025-01-13 20:23
@j-fbriere sorry. https://github.com/flutter/flutter/commit/68415ad1d920f6fe5ec284f5c2febf7c4dd5b0b3

This is in line to be the next stable "dot" release once verified.

**Comment by Reprevise** [comment] 2025-01-13 21:18
@kevmoo https://github.com/flutter/flutter/pull/161524 doesn't have any info regarding _what_ fixes are included, and neither does the engine PR (https://github.com/flutter/engine/pull/57271). It only mentions a new Dart version, and some infrastructure updates.

**Comment by kevmoo** [comment] 2025-01-13 21:31
@Reprevise – gotta read through the history. Digging into other engine commits, the fix is included. https://github.com/flutter/engine/commit/9c0d3222c068ebdcff16c16c71787e281a33a6e0

**Comment by Reprevise** [comment] 2025-01-13 21:33
> [@Reprevise](https://github.com/Reprevise) – gotta read through the history. Digging into other engine commits, the fix is included. [flutter/engine@9c0d322](https://github.com/flutter/engine/commit/9c0d3222c068ebdcff16c16c71787e281a33a6e0)

So all these commits are in the new hotfix?

![Image](https://github.com/user-attachments/assets/07245156-5d82-48e2-a413-0e2bc5722fc2)

**Comment by kevmoo** [comment] 2025-01-13 22:34
@Reprevise – yep! This is one of those things that'll be MUCH easier once we have a stable release out of the "merged" engine/flutter repo.

**Comment by j-fbriere** [comment] 2025-01-13 22:41
Flutter 3.27.2 now has been tagged in the stable branch of the Flutter git repository. I'll start my testing...

**Comment by kevmoo** [comment] 2025-01-14 02:18
Thanks for letting us know, @j-fbriere !
