### ISSUE TITLE
[Write Your First Flutter App] In Part 2, Part 4, Part 5 link to source code are broken

### ISSUE THREAD

**Issue by cesarodriguez4** [flutter/flutter#86258] opened 2021-07-11 23:05 UTC
![CleanShot 2021-07-11 at 19 02 53@2x](https://user-images.githubusercontent.com/11139209/125212349-cc83a880-e27a-11eb-8aa2-8564c0037fc1.png)
This url points [here](https://github.com/flutter/codelabs/blob/master/startup_namer_null_safety/step5_add_icons/lib/main.dart) but the link is broken.

**Comment by TahaTesser** [comment] 2021-07-23 14:22
In Part 2, Part 4, Part 5 link to source code are broken

**Comment by domesticmouse** [comment] 2021-08-03 11:43
This was caused by me collapsing the `startup_namer_null_safety` code into `startup_namer`. Fix is in flight. Thanks!

**Closed by domesticmouse** 2021-08-03 11:43 UTC
Labels: d: codelabs, documentation, passed first triage

**Comment by TahaTesser** [comment] 2021-08-03 12:19
Hi @domesticmouse 
Can you please confirm link step 6 and 7 are all fixed? 
see https://github.com/flutter/website/issues/6090

**Comment by domesticmouse** [comment] 2021-08-03 22:46
It is now =)
