### ISSUE TITLE
[flutter_image] Image.loadingBuilder returns null loadingProgress while using NetworkImageWithRetry

### ISSUE THREAD

**Issue by benyamin218118** [flutter/flutter#75579] opened 2021-02-07 10:08 UTC
https://github.com/flutter/flutter_image

<details>
<summary>code sample</summary>

```dart
                            new Image(
                                    image: new NetworkImageWithRetry(image,
                                        fetchStrategy: FetchStrategyBuilder(
                                            maxAttempts: 5,
                                            initialPauseBetweenRetries:
                                                const Duration(seconds: 1),
                                            totalFetchTimeout:
                                                const Duration(seconds: 45),
                                            transientHttpStatusCodePredicate:
                                                (sc) {
                                              return <int>[
                                                0, // Network error
                                                408, // Request timeout
                                                500, // Internal server error
                                                502, // Bad gateway
                                                503, // Service unavailable
                                                504, // Gateway timeout
                                                423, // Resource Locked
                                              ].contains(sc);
                                            }).build()),
                                    loadingBuilder: (BuildContext context,
                                        Widget child,
                                        ImageChunkEvent loadingProgress) {
                                      if (loadingProgress == null)
                                        return child;
                                      return Center(
                                        child: CircularProgressIndicator(
                                          value: loadingProgress
                                                      .expectedTotalBytes !=
                                                  null
                                              ? loadingProgress
                                                      .cumulativeBytesLoaded /
                                                  loadingProgress
                                                      .expectedTotalBytes
                                              : null,
                                        ),
                                      );
                                    },
                                  )
```
</details>

here i have the loadingBuilder which is working correctly on Image.network(url);
but it is not working ( loadingProgress is Always null ) when i am using NetworkImageWithRetry and Image here.
whats wrong?

**Comment by pedromassangocode** [comment] 2021-02-08 07:28
Hi @benyamin218118 
Can you please provide your `flutter doctor -v` and a minimal complete reproducible code sample?
Thank you

**Comment by benyamin218118** [comment] 2021-02-08 09:52
my flutter is up2date with stable channel, 
Flutter 1.22.6 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 9b2d32b605 (2 weeks ago) • 2021-01-22 14:36:39 -0800
Engine • revision 2f0af37152
Tools • Dart 2.10.5

you can test my example in my first comment.

**Comment by pedromassangocode** [comment] 2021-02-08 11:50
Hi @benyamin218118 
I need a code that does not uses any third-party package/plugin as they may be the root cause of the issue.

**Comment by benyamin218118** [comment] 2021-02-09 07:03
@pedromassangocode my problem is using NetworkImageWithRetry with Image class dude :/

**Comment by pedromassangocode** [comment] 2021-02-09 11:41
I was able to reproduce the issue.

<details>
<summary>logs</summary>

```bash
Performing hot restart...
[  +21 ms] Scanned through 494 files in 7ms
Syncing files to device sdk gphone x86 64...
[   +1 ms] Scanning asset files
[   +1 ms] <- reset
[        ] Compiling dart to kernel with 1 updated files
[        ] <- recompile package:flutter_example/main.dart 75582575-29b4-426d-a7ad-37c4004417e8
[        ] package:flutter_example/main.dart
[        ] <- 75582575-29b4-426d-a7ad-37c4004417e8
[ +292 ms] Updating files
[ +935 ms] DevFS: Sync finished
[        ] Synced 24.4MB.
[        ] <- accept
[ +457 ms] Hot restart performed in 1,677ms.
[   +5 ms] Restarted application in 1,725ms.
[+2180 ms] I/flutter ( 5609): Progress: null
[+2559 ms] I/chatty  ( 5609): uid=10167(com.example.flutter_example) 1.ui identical 1 line
[        ] I/flutter ( 5609): Progress: null
[+57543 ms] org-dartlang-debug:synthetic_debug_expression:1:6: Error: Can't find ']' to match '['.
[        ] <int>[
[        ]      ^
[+11046 ms] org-dartlang-debug:synthetic_debug_expression:1:6: Error: Can't find ']' to match '['.
[        ] <int>[
[        ]      ^
[+3643 ms] org-dartlang-debug:synthetic_debug_expression:1:6: Error: Can't find ']' to match '['.
[        ] <int>[
[        ]      ^
```
</details>

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 1.22.6, on macOS 11.2 20D64 darwin-x64, locale en-AO)
    • Flutter version 1.22.6 at /Users/pedromassango/Code/flutter_stable
    • Framework revision 9b2d32b605 (2 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.9.3

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin installed
    • Dart plugin version 203.6912

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```

</details>

**Comment by pedromassangocode** [comment] 2021-02-10 08:37
@Hixie I saw a thread in https://github.com/flutter/flutter_image/pull/18#issuecomment-775721675 about this package being deprecated, so I would like to know if the triage team should accept issues related to that package here. As a example, I'm thinking to close this issue since the package i being deprecated (assuming that based on your comment mentioned above).

**Comment by Hixie** [comment] 2021-02-10 20:44
The package itself isn't deprecated, it's just that right now we have nobody working on it and if anyone wants to work on it within the Flutter team the first step will be moving it to the flutter/packages repo. We should still accept issues on this package for now. If we decide to end-of-life the package (e.g. because someone has a better one) then we would then close those issues, but we haven't decided to do that yet.

**Comment by Abhishek01039** [comment] 2021-02-13 12:00
hello @Hixie
I have published the plugin https://pub.dev/packages/hf_retry
now you can deprecate this repo.
Thanks

**Comment by Abhishek01039** [comment] 2021-02-13 12:09
> @Hixie I saw a thread in [flutter/flutter_image#18 (comment)](https://github.com/flutter/flutter_image/pull/18#issuecomment-775721675) about this package being deprecated, so I would like to know if the triage team should accept issues related to that package here. As a example, I'm thinking to close this issue since the package i being deprecated (assuming that based on your comment mentioned above).

@pedromassangocode Please transfer this issue to https://github.com/hireflutter-dev/hf-retry repo.
Thanks

**Comment by Abhishek01039** [comment] 2021-02-13 12:10
@benyamin218118 Please free to open this issue to https://github.com/hireflutter-dev/hf-retry here.
Thanks

**Closed** 2021-06-08 14:08 UTC
Labels: a: images, found in release: 1.22, has reproducible steps, p: first party, package
