### ISSUE TITLE
Flutter Flavours for macOS

### ISSUE THREAD

**Issue by domesticmouse** [flutter/flutter#96489] opened 2022-01-11 23:02 UTC
We should support [flavors](https://docs.flutter.dev/deployment/flavors) for Flutter macOS.

/cc @craiglabenz

**Comment by stuartmorgan** [comment] 2022-01-12 01:26
Duplicate of https://github.com/flutter/flutter/issues/64088

**Closed by stuartmorgan** 2022-01-12 01:26 UTC
Labels: platform-mac, a: desktop
