### ISSUE TITLE
Flutter Web with CanvasKit renders FontWeight not correct

### ISSUE THREAD

**Issue by AndroidNils** [flutter/flutter#60125] opened 2020-06-23 20:09 UTC
## Steps to Reproduce

1. Copy this code:
```
import 'package:flutter/material.dart';

void main() {
  runApp(
    MaterialApp(
      home: Scaffold(
        body: Text(
          "Weigth",
          style: TextStyle(
            fontWeight: FontWeight.w800,
            fontSize: 50,
          ),
        ),
      ),
    ),
  );
}

```
2. Run `flutter build web --release --dart-define=FLUTTER_WEB_USE_SKIA=true`

**Expected results (normal render):** 
![image](https://user-images.githubusercontent.com/24459435/85454837-97d47e80-b59d-11ea-96d8-ff0badea948f.png)

**Actual results (CanvasKit):** 
![image](https://user-images.githubusercontent.com/24459435/85454722-7d9aa080-b59d-11ea-82b6-49d0217f4043.png)

<details>
  <summary>Flutter doctor</summary>

```
[✓] Flutter (Channel beta, 1.19.0-4.1.pre, on Mac OS X 10.15.5 19F96, locale
    de-DE)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.46.1)
[✓] Connected device (2 available)
```
</details>

**Comment by iapicca** [comment] 2020-06-24 09:09
HI @AndroidNils 
testing 
<details><summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(
    MaterialApp(
      home: Scaffold(
        body: Text(
          "Weigth",
          style: TextStyle(
            fontWeight: FontWeight.w800,
            fontSize: 50,
          ),
        ),
      ),
    ),
  );
```

</details>


with the latest master

<details><summary>screenshot</summary>

**FontWeight.w800**
`flutter run -d chrome --dart-define=FLUTTER_WEB_USE_SKIA=true -v`
![Screenshot from 2020-06-24 11-35-41](https://user-images.githubusercontent.com/45637986/85522871-e1a97d00-b60e-11ea-9380-cc6f9bc7b891.png)

`flutter run -d chrome -v`
![Screenshot from 2020-06-24 11-37-47](https://user-images.githubusercontent.com/45637986/85523074-2b926300-b60f-11ea-9730-bf75f7595a16.png)

**FontWeight.w100**
`flutter run -d chrome --dart-define=FLUTTER_WEB_USE_SKIA=true -v`
![Screenshot from 2020-06-24 12-05-48](https://user-images.githubusercontent.com/45637986/85526927-13244780-b613-11ea-83fe-970328dcb17a.png)

`flutter run -d chrome -v`
![Screenshot from 2020-06-24 12-07-01](https://user-images.githubusercontent.com/45637986/85527129-436be600-b613-11ea-9e19-e935c2a85b6a.png)



</details>

<details><summary>doctor</summary>

```console
[✓] Flutter (Channel master, 1.20.0-1.0.pre.184, on Linux, locale en_US.UTF-8)
    • Flutter version 1.20.0-1.0.pre.184 at /home/francesco/development/flutter_master
    • Framework revision 61b93d25bb (3 hours ago), 2020-06-24 01:53:01 -0400
    • Engine revision 2a9fed87a7
    • Dart version 2.9.0 (build 2.9.0-18.0.dev 6b630c3719)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /usr/lib/Android
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /usr/lib/Android
    • ANDROID_SDK_ROOT = /usr/lib/Android
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_252-8u252-b09-1~18.04-b09)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✗] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1
    ✗ GTK 3.0 development libraries are required for Linux development.
      They are likely available from your distribution (e.g.: apt install libgtk-3-dev)

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] VS Code (version 1.46.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.11.0

[✓] Connected device (3 available)
    • Linux desktop • linux      • linux-x64      • Linux
    • Web Server    • web-server • web-javascript • Flutter Tools
    • Chrome        • chrome     • web-javascript • Google Chrome 83.0.4103.106

! Doctor found issues in 2 categories.

```

</details>

testing on the latest beta

<details><summary>screenshot</summary>

**FontWeight.w800**
`flutter run -d chrome -v`
![Screenshot from 2020-06-24 11-46-20](https://user-images.githubusercontent.com/45637986/85524096-795b9b00-b610-11ea-8b37-67a910fa6cbc.png)

`flutter run -d chrome --dart-define=FLUTTER_WEB_USE_SKIA=true -v`
![Screenshot from 2020-06-24 12-00-51](https://user-images.githubusercontent.com/45637986/85526104-61851680-b612-11ea-8da4-95bd6549dacc.png)

**FontWeight.w100**
`flutter run -d chrome -v`
![Screenshot from 2020-06-24 11-49-40](https://user-images.githubusercontent.com/45637986/85525650-f1769080-b611-11ea-9771-b592650eb616.png)

`flutter run -d chrome --dart-define=FLUTTER_WEB_USE_SKIA=true -v`
![Screenshot from 2020-06-24 11-59-10](https://user-images.githubusercontent.com/45637986/85525905-326ea500-b612-11ea-9030-c390be1fcdf2.png)

</details>

<details><summary>doctor</summary>

```console
[✓] Flutter (Channel beta, 1.19.0-4.1.pre, on Linux, locale en_US.UTF-8)
    • Flutter version 1.19.0-4.1.pre at /home/francesco/development/flutter_beta
    • Framework revision f994b76974 (2 weeks ago), 2020-06-09 15:53:13 -0700
    • Engine revision 9a28c3bcf4
    • Dart version 2.9.0 (build 2.9.0-14.1.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /usr/lib/Android
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /usr/lib/Android
    • ANDROID_SDK_ROOT = /usr/lib/Android
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_252-8u252-b09-1~18.04-b09)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] VS Code (version 1.46.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.11.0

[✓] Connected device (2 available)
    • Web Server • web-server • web-javascript • Flutter Tools
    • Chrome     • chrome     • web-javascript • Google Chrome 83.0.4103.106

! Doctor found issues in 1 category.

```

</details>

I do not experience the issue you are encountering,
I don't have access to a mac at the moment, I'll proceed with further testing asap
Thank you

**Comment by AndroidNils** [comment] 2020-06-24 09:33
Hmm, I tested it again and I still experience this issue :/ 

I noticed also that the title "Flutter Web with CanvasKit ignores FontWeight" isn't correct. The parameter is applied, but the FontWeight is still too thin with CanvasKit (you see it in my screenshots).

**Comment by iapicca** [comment] 2020-06-26 13:21
Hi @AndroidNils 
I cannot reproduce the issue on mac as well
<details><summary>screenshots</summary>

flutter run -d chrome
![image](https://user-images.githubusercontent.com/45637986/85861046-5ffd4f00-b7c8-11ea-9a9d-268aab3e3583.png)

flutter run -d chrome --dart-define=FLUTTER_WEB_USE_SKIA=true
![image](https://user-images.githubusercontent.com/45637986/85861277-c08c8c00-b7c8-11ea-81ab-483d1744da86.png)

</details>

<details><summary>doctor</summary>

```console
[✓] Flutter (Channel master, 1.20.0-1.0.pre.219, on Mac OS X 10.15.5 19F101, locale en-GB)
    • Flutter version 1.20.0-1.0.pre.219 at /Users/nevercode/development/flutter_master
    • Framework revision 98d66de888 (10 hours ago), 2020-06-25 23:38:02 -0400
    • Engine revision 22b099bc63
    • Dart version 2.9.0 (build 2.9.0-19.0.dev ea87c9b01a)


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/nevercode/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (4 available)
    • Pixel 3a      • 965AY0WP5C • android-arm64  • Android 10 (API 29)
    • macOS desktop • macos      • darwin-x64     • Mac OS X 10.15.5 19F101
    • Web Server    • web-server • web-javascript • Flutter Tools
    • Chrome        • chrome     • web-javascript • Google Chrome 83.0.4103.116

• No issues found!
```

</details>

are you experiencing this with the latest master?
Thank you

**Comment by AndroidNils** [comment] 2020-06-26 14:13
@iapicca Yes, I tested it also with the latest master. But as mentioned in #60120 this issue doesn't accord every time:

> I tested again a little. So it's a little bit tricky. I either have this issue (but not #60125) or I haven't this issue (but #60125) 🤨 From my feeling, it's completely random, which option happens 😅

From: https://github.com/flutter/flutter/issues/60120#issuecomment-649484838

**Comment by ekasetiawans** [comment] 2020-07-05 21:07
same issue

<details>
<summary>main.dart</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(
    MaterialApp(
      home: Scaffold(
        body: Column(
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: [
            Text(
              "w100",
              style: TextStyle(
                fontWeight: FontWeight.w100,
                fontSize: 50,
              ),
            ),
            Text(
              "w200",
              style: TextStyle(
                fontWeight: FontWeight.w200,
                fontSize: 50,
              ),
            ),
            Text(
              "w300",
              style: TextStyle(
                fontWeight: FontWeight.w300,
                fontSize: 50,
              ),
            ),
            Text(
              "w400",
              style: TextStyle(
                fontWeight: FontWeight.w400,
                fontSize: 50,
              ),
            ),
            Text(
              "w500",
              style: TextStyle(
                fontWeight: FontWeight.w500,
                fontSize: 50,
              ),
            ),
            Text(
              "w600",
              style: TextStyle(
                fontWeight: FontWeight.w600,
                fontSize: 50,
              ),
            ),
            Text(
              "w700",
              style: TextStyle(
                fontWeight: FontWeight.w700,
                fontSize: 50,
              ),
            ),
            Text(
              "w800",
              style: TextStyle(
                fontWeight: FontWeight.w800,
                fontSize: 50,
              ),
            ),
            Text(
              "w900",
              style: TextStyle(
                fontWeight: FontWeight.w900,
                fontSize: 50,
              ),
            ),
          ],
        ),
      ),
    ),
  );
}
```

</details>

<details>
<summary>screenshot: flutter build web --release</summary>
<img width="1312" alt="Screen Shot 2020-07-06 at 03 44 40" src="https://user-images.githubusercontent.com/20693888/86542207-d246ff80-bf3d-11ea-8cc7-95cc6fa8fe01.png">
</details>

<details>
<summary>screenshot: flutter build web --release --dart-define=FLUTTER_WEB_USE_SKIA=true</summary>
<img width="1312" alt="Screen Shot 2020-07-06 at 03 45 00" src="https://user-images.githubusercontent.com/20693888/86542220-edb20a80-bf3d-11ea-992e-7faceca87cb5.png">


</details>


<details>
<summary>flutter doctor</summary>

```
ekasetiawans@MacBookPro text_weight % flutter doctor -v
[✓] Flutter (Channel master, 1.20.0-3.0.pre.130, on Mac OS X 10.15.5 19F101, locale en-ID)
    • Flutter version 1.20.0-3.0.pre.130 at /Users/ekasetiawans/Development/flutter
    • Framework revision a74310242e (2 hours ago), 2020-07-05 14:58:01 -0400
    • Engine revision f8bbcc396b
    • Dart version 2.9.0 (build 2.9.0-20.0.dev c190fc3a31)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/ekasetiawans/Development/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • ANDROID_HOME = /Users/ekasetiawans/Development/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.1

 
[✓] Connected device (5 available)            
    • iPhone 7 (mobile)          • 00444a65613e7dbfec251d2cef80b8ddc15fa3cf • ios            • iOS 13.5.1
    • iPhone 11 Pro Max (mobile) • 957D2B29-9078-4F52-BD06-DE11D5FFEE4E     • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-5 (simulator)
    • macOS (desktop)            • macos                                    • darwin-x64     • Mac OS X 10.15.5 19F101
    • Web Server (web)           • web-server                               • web-javascript • Flutter Tools
    • Chrome (web)               • chrome                                   • web-javascript • Google Chrome 83.0.4103.116

• No issues found!
```

</details>

**Comment by markusaksli-nc** [comment] 2020-08-14 07:05
Closing since this was fixed by https://github.com/flutter/engine/pull/20272 and is no longer reproducible on the latest master `1.21.0-10.0.pre.94`.
<details>
 <summary>flutter doctor -v</summary>

```
[√] Flutter (Channel master, 1.21.0-10.0.pre.94, on Microsoft Windows [Version 10.0.19041.450], locale en-US)
    • Flutter version 1.21.0-10.0.pre.94 at C:\Development\flutter_master
    • Framework revision 58feba8edd (65 minutes ago), 2020-08-13 21:16:04 -0700
    • Engine revision 7571e7c380
    • Dart version 2.10.0 (build 2.10.0-11.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Users\marku\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.6.5)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.6.30320.27
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.0)
    • Android Studio at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (5 available)
    • SM G950F (mobile)           • ce12171c51cc001c03 • android-arm64  • Android 9 (API 28)
    • sdk gphone x86 arm (mobile) • emulator-5554      • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)           • windows            • windows-x64    • Microsoft Windows [Version 10.0.19041.450]
    • Web Server (web)            • web-server         • web-javascript • Flutter Tools
    • Chrome (web)                • chrome             • web-javascript • Google Chrome 84.0.4147.125

• No issues found!
```
</details>

**Closed by markusaksli-nc** 2020-08-14 07:05 UTC
Labels: P4, a: typography, dependency: skia, e: web_canvaskit, engine, framework, platform-web, severe: rendering
