### ISSUE TITLE
Is it possible for the flutter doctor command to ignore certain IDEs?

### ISSUE THREAD

**Issue by ShiraazMoollatjie** [flutter/flutter#25719] opened 2018-12-23 20:04 UTC
I use flutter mainly in conjunction with Android Studio. But I get warnings for IntelliJ Community Edition (which I use mainly for java work) and Visual Studio Code (which I use for other languages).

So I get output like:

```
[√] Flutter (Channel beta, v1.0.0, on Microsoft Windows [Version 10.0.16299.785], locale en-US)
[√] Android Studio (version 3.2)
[!] IntelliJ IDEA Community Edition (version 2018.2)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] VS Code, 64-bit edition (version 1.28.2)
[!] Connected device
    ! No devices available
```

So is there a way to remove IntelliJ IDEA from that output?

**Comment by Sh1d0w** [comment] 2018-12-24 03:45
IMO I don't see why flutter doctor should check for installed plugins in the editor. It should be concerned only for runtime setup, e.g. OS version, flutter version, libs needed for deploy and debug etc.

What editor I chose and if I have a plugin should be not of its concern. I may like to write code with vim, and not use those IDEs at all. Those warning are also annoying in that case.

**Comment by zoechi** [comment] 2018-12-24 11:45
@Sh1d0w how does it hurt?
What is your use case?
What information is relevant depends on what issues are raised. 
If someone raises an issue about the IDE not behaving as expected different information is required then when the issue is about `flutter build ...` causing errors.

**Comment by Sh1d0w** [comment] 2018-12-24 12:38
@zoechi What you say makes sense, but again the command can output the IDE versions as it currently does, but not give you errors that you don't have the plugin installed for this IDE.

This way you still will have the info you need in the issue, and we won't have those annoying errors when we run the command.

The only problem is the annoyance. This error gives nothing meaningful to me:

```
[!] IntelliJ IDEA Community Edition (version 2018.2)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
```

I may have the CE edition installed and using it for other purposes than writing Dart or Flutter code, but in order to get rid of that error I have to install the plugin.

This is more like OCD problem than a real issue, but still :P

**Comment by zoechi** [comment] 2018-12-24 12:44
The hint should be easy to ignore. 
`flutter doctor` is usually only used to diagnose a problem.
What's your use cae where xou find it anmoying?

**Comment by Sh1d0w** [comment] 2018-12-24 14:44
This is exactly the case where it gets annoying.

You run this command to diagnose a problem, then you get some errors, that are not actually errors, rather than suggestions regarding missing IDE plugins. And the only way to make them go away is to force install the plugins on all 3 IDEs, even if you use only one of them for developing Flutter apps.

**Comment by ShiraazMoollatjie** [comment] 2018-12-26 08:43
I suppose that if `flutter doctor` can detect your primary IDE (via prompt/config or even another command) then it can work.

It's easy to ignore the messages, it's what I'm doing right now. Although one can ask the question that if the `flutter doctor` command outputs ignorable messages, doesn't that dilute the value of the command?

**Comment by zoechi** [comment] 2018-12-27 07:51
@ShiraazMoollatjie I don't see a way to derive what your primary IDE is, and when you post the output here I wouldn't want the output have anything suppressed just because you're not actively using an IDE `flutter doctor` found. For diagnosis the whole picture is more important.

**Comment by zoechi** [comment] 2019-01-09 14:39
Somewhat related #12768

**Comment by kangwang1988** [comment] 2019-01-09 14:43
`flutter doctor` as suggested is mainly for diagnosing.
The more information related provided, the better, i guess.

**Comment by luolong** [comment] 2019-03-21 09:45
> `flutter doctor` as suggested is mainly for diagnosing.
> The more information related provided, the better, i guess.

True, it is mostly for diagnosing but as it is currently, the diagnosis contains a certain amount of false positives and those are noise.

It would be nice to be able to explicitly exclude some IDE's (paths?) from the diagnostics (an ignore list somewhere in the configuration perhaps)

This is a low priority issue to be certain, but valuable for at least some developers...

**Comment by iapicca** [comment] 2019-11-01 12:53
Hi @ShiraazMoollatjie 
I see there's an open [issue ](https://github.com/flutter/flutter/issues/10352)addressing the case you described.
Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you

**Closed by iapicca** 2019-11-01 12:53 UTC
Labels: t: flutter doctor, tool

**Comment by luolong** [comment] 2019-11-04 07:35
It is unfortunate that this issue was closed. This is definitely *not* a duplicate of #10352 and should not be closed based on that argument.
