### ISSUE TITLE
FocusNode's parent widget (TextField) processes a KeyEvent before the FocusNode's onKey() property returns, making the KeyEventResult.handled useless as it's too late to take it into account.

### ISSUE THREAD

**Issue by jeremynac** [flutter/flutter#96516] opened 2022-01-12 09:44 UTC
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. Use flutter web.
3. Type "This is a message" in the textfield, and when done, press the "Enter" key.

**Expected results:** 

1. The onKey function of the focusNode is called successfully, and it detects that the enter key has been pressed.
2. Inside the onKey function, we print the text that is contained in the TextField controller, and it contains "This is a message".
3. We call widget.onSubmit() with "This is a message" as parameter.
4. We return KeyEventResult.handled in the end of the onKey function.
5. The "Enter" key is not processed by the TextField.

**Actual results:** 

1. The onKey function of the focusNode is called successfully, and it detects that the enter key has been pressed.
2. Inside the onKey function, we print the text that is contained in the TextField controller, and it contains "This is a message\n", with an extra "\n"
3. That means that the "Enter" key was processed by the textfield before its focusNode finished processing it.
4. We return KeyEventResult.handled in the end of the onKey function.
5. The "Enter" key has already been processed as "newline" by the TextField before we even returned.

FocusNode onKey property does not stop the keyEvent from propagating to the parent widgets, even before the onKey function returns.

We want to have a TextField that works like most messaging apps, where you can press "Enter" to submit, and "Shift" + "Enter" to add a newline.
To do this, the only way we found (after trying with onSubmitted and TextInputType.text) was to add a focusNode in the TextField with an onKey() property.
In the onKey, we detect if "Enter" without "Shift" was pressed and it was, we call onSubmit and return KeyEventResult.handled so that the TextField does not process it.
But the TextField processed the "Enter" key (and adds a newline) even before we return from the onKey() function.

<details>
<summary>code sample</summary>

```dart
class ActionBarCommentField extends StatefulWidget {
  final Function(String) onSubmit;
  ActionBarCommentField({required this.onSubmit});
  @override
  _ActionBarCommentFieldState createState() => _ActionBarCommentFieldState();
}

class _ActionBarCommentFieldState extends State<ActionBarCommentField> {
  final TextEditingController commentTextController = TextEditingController();
  late final FocusNode focusNode = FocusNode(onKey: onKey);

  @override
  initState() {
    super.initState();
  }

  onSubmit() {
    final text = commentTextController.text;
    Navigator.of(context).pop();
    widget.onSubmit(text);
  }

  KeyEventResult onKey(FocusNode _, RawKeyEvent event) {
    // Check if the key event is on web.
    if (event is RawKeyUpEvent && event.data is RawKeyEventDataWeb) {
      var data = event.data as RawKeyEventDataWeb;
      // Check if enter was pressed without shift/
      if (data.key == "Enter" && !data.isShiftPressed) {
        debugPrint("Submit ${commentTextController.text}");
        // This prints the "Submit text + \n" at the end, meaning the textfield handled the "Enter" key event before this.
        widget.onSubmit(commentTextController.text);
        return KeyEventResult.handled;
      }
    }
    return KeyEventResult.ignored;
  }

  @override
  Widget build(BuildContext context) {
    return Container(
        decoration: BoxDecoration(color: Colors.white),
        margin:
            EdgeInsets.only(bottom: MediaQuery.of(context).viewInsets.bottom),
        child: ListTile(
            title: TextField(
              autofocus: true,
              controller: commentTextController,
              style: Theme.of(context).textTheme.headline6,
              maxLines: null,
              focusNode: focusNode,
            ),
            trailing: IconButton(onPressed: onSubmit, icon: Icon(Icons.send))));
  }
}
```

</details>

<details>
  <summary>Logs</summary>

```
[        ] Restarted application in 1,243ms.
[  +63 ms] [🌎 Easy Localization] [DEBUG] Localization initialized
[  +32 ms] Initializing flutter web google sign in
[   +4 ms] [🌎 Easy Localization] [DEBUG] Start
[        ] [🌎 Easy Localization] [DEBUG] Init state
[        ] [🌎 Easy Localization] [DEBUG] Build
[        ] [🌎 Easy Localization] [DEBUG] Init Localization Delegate
[        ] [🌎 Easy Localization] [DEBUG] Init provider
[   +5 ms] [🌎 Easy Localization] [DEBUG] Load Localization Delegate
[        ] [🌎 Easy Localization] [DEBUG] Load asset from assets/translations
[ +255 ms] Retreived user
[   +4 ms] User granted notifications permission: AuthorizationStatus.authorized
[  +38 ms] listening
[  +19 ms] Listen to notifications
[+4304 ms] Submit this is a message
```

```
Analyzing zentime...                                                    
No issues found! (ran in 7.5s)
```

```
[✓] Flutter (Channel stable, 2.5.2, on macOS 12.1 21C52 darwin-x64, locale en-FR)
    • Flutter version 2.5.2 at /Users/jeremynaccache/AppFiles/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3595343e20 (3 months ago), 2021-09-30 12:58:18 -0700
    • Engine revision 6ac856380f
    • Dart version 2.14.3

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/jeremynaccache/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.2.1, Build version 13C100
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Code/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.32.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 97.0.4692.71

! Doctor found issues in 1 category.
```

</details>

**Comment by maheshmnj** [comment] 2022-01-12 12:15
Hi @jeremynac, Thanks for filing the issue. It seems you are using an older version of flutter, Could you please try updating to the latest `stable 2.8.1` and see if the issue persists.


Thank you.

**Comment by maheshmnj** [comment] 2022-01-13 06:31
Thanks for the code sample @jeremynac, I don't see a newline character (\n) added on pressing the enter Key, Please check the below code sample with a slight modification in print statement to make sure if `\n` was added to text input on pressing enter.

>     debugPrint("Submit ${commentTextController.text} and some text");

To verify this run the code sample press enter and see the result text would be in a single line.
Now, press shift enter (add a line break) and press enter. You will see multiline text.

<details>
<summary>complete code sample</summary>

```dart
import 'dart:ui';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
// import 'package:flutter_inappwebview/flutter_inappwebview.dart';
import 'package:webview_flutter/webview_flutter.dart';
import 'package:yaml/yaml.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        title: 'Flutter Demo',
        theme: ThemeData(
          primarySwatch: Colors.blue,
        ),
        home: ActionBarCommentField(
          onSubmit: (x) {
            print('submitted');
          },
        )
        // const MyHomePage(title: 'Flutter Demo Home Page'),
        );
  }
}
class ActionBarCommentField extends StatefulWidget {
  final Function(String) onSubmit;
  const ActionBarCommentField({required this.onSubmit});
  @override
  _ActionBarCommentFieldState createState() => _ActionBarCommentFieldState();
}

class _ActionBarCommentFieldState extends State<ActionBarCommentField> {
  final TextEditingController commentTextController = TextEditingController();
  late final FocusNode focusNode = FocusNode(onKey: onKey);

  @override
  initState() {
    super.initState();
  }

  onSubmit() {
    final text = commentTextController.text;
    Navigator.of(context).pop();
    widget.onSubmit(text);
  }

  KeyEventResult onKey(FocusNode _, RawKeyEvent event) {
    // Check if the key event is on web.
    if (event is RawKeyUpEvent && event.data is RawKeyEventDataWeb) {
      var data = event.data as RawKeyEventDataWeb;
      // Check if enter was pressed without shift/
      if (data.key == "Enter" && !data.isShiftPressed) {
        debugPrint("Submit ${commentTextController.text} and some text");
        // This prints the "Submit text + \n" at the end, meaning the textfield handled the "Enter" key event before this.
        widget.onSubmit(commentTextController.text);
        return KeyEventResult.handled;
      }
    }
    return KeyEventResult.ignored;
  }

  @override
  Widget build(BuildContext context) {
    return Material(
      child: Center(
          child: ListTile(
              title: TextField(
                autofocus: true,
                controller: commentTextController,
                style: Theme.of(context).textTheme.headline6,
                maxLines: null,
                focusNode: focusNode,
              ),
              trailing:
                  IconButton(onPressed: onSubmit, icon: Icon(Icons.send)))),
    );
  }
}

```
</details>
  
  
<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.1 21C52 darwin-arm, locale en-GB)
    • Flutter version 2.8.1 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (3 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.32.0

[✓] Connected device (4 available)
    • Redmi K20 Pro (mobile) • 192.168.1.3:5555                     • android-arm64  • Android 11 (API 30)
    • iPhone 13 Pro (mobile) • 0FA2FB93-2A89-4FDB-8293-DF66188F1E54 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-0
      (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.1 21C52 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 96.0.4664.110

• No issues found!
```

</details>

**Comment by jeremynac** [comment] 2022-01-14 11:55
Thank you for this answer.
I tested your code by creating a new Flutter project and putting it inside, and it worked as intended.
It's still not working right in my project's code though (it's printing a "\n" between the text and the " and some text").
There must be something wrong in my project, I'll keep investigating.
Would you have any idea of what could cause the widgets to behave differently in my project ?
I am using Mobx.dart with Provider if that changes anything.
Again, thank you for your time

**Comment by maheshmnj** [comment] 2022-01-14 12:51
thanks for the update @jeremynac, May be you can share a minimal sample project and I can have a look.

**Comment by jeremynac** [comment] 2022-01-21 11:34
I finally found the cause of the issue:
In my MaterialApp I had:
```
MaterialApp(
// ...
  shortcuts: {
     ...(kIsWeb
         ? {LogicalKeySet(LogicalKeyboardKey.space): ActivateIntent()}
         : {}),
   },
  // ...
)
```
I used this because the space bar was not working in production without adding this shortcut.

So now, the problem is that if I add the shortcut above in MaterialApp, I can't submit on Enter.
But if I remove the shortcut, I cannot type a space.
The code is exactly the same as above only with this shortcut.
Also, I am using Firebase hosting for production

**Comment by maheshmnj** [comment] 2022-01-24 05:34
> I used this because the space bar was not working in production without adding this shortcut.

That sounds like a different issue. Please file that as a separate issue.  Since you found the cause of the issue I believe this is safe to close this issue.
Closing as solved, if you disagree feel free to write in the comments and I will reopen it.

Thank you.

**Closed by maheshmnj** 2022-01-24 05:34 UTC
Labels: in triage
