### ISSUE TITLE
[tool_crash] SocketException: Failed to create datagram socket (OS Error: Address already in use, errno = 48), address = , port = 5353

### ISSUE THREAD

**Issue by oncealong** [flutter/flutter#78871] opened 2021-03-23 14:50 UTC
## Command
```
flutter --no-color attach --machine --device-id=00008030-000E24320AE3802E lib/main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
SocketException: SocketException: Failed to create datagram socket (OS Error: Address already in use, errno = 48), address = , port = 5353
```
#0      _NativeSocket.bindDatagram (dart:io-patch/socket_patch.dart:760:7)
<asynchronous suspension>
#1      _RawDatagramSocket.bind (dart:io-patch/socket_patch.dart:2095:26)
#2      RawDatagramSocket.bind (dart:io-patch/socket_patch.dart:2053:31)
#3      MDnsClient.start (package:multicast_dns/multicast_dns.dart:127:71)
<asynchronous suspension>
#4      MDnsObservatoryDiscovery.query (package:flutter_tools/src/mdns_discovery.dart:59:20)
#5      MDnsObservatoryDiscovery.getObservatoryUri (package:flutter_tools/src/mdns_discovery.dart:151:57)
#6      AttachCommand._attachToDevice (package:flutter_tools/src/commands/attach.dart:235:51)
#7      _rootRunUnary (dart:async/zone.dart:1192:38)
#8      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#9      _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#10     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#11     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#12     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#13     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
#14     _rootRun (dart:async/zone.dart:1184:13)
#15     _CustomZone.run (dart:async/zone.dart:1077:19)
#16     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
#17     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
```
```
[✓] Flutter (Channel unknown, v1.17.5, on Mac OS X 10.15.7 19H114, locale en-CN)
    • Flutter version 1.17.5 at /Users/along/flutter/flutter_1.17
    • Framework revision 8af6b2f038 (9 months ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/along/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/along/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio
    • Android Studio at /Applications/Android Studio 4.2 Preview.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio3.5.app/Contents
    • Flutter plugin version 44.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[!] Android Studio
    • Android Studio at /Applications/Android Studio Canary.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[!] IntelliJ IDEA Ultimate Edition (version 2020.3.2)
    • IntelliJ at /Users/along/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.54.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (4 available)
    • Along的iPhone • 00008030-000E24320AE3802E • ios            • iOS 14.3
    • macOS        • macOS                     • darwin-x64     • Mac OS X 10.15.7 19H114
    • Chrome       • chrome                    • web-javascript • Google Chrome 89.0.4389.90
    • Web Server   • web-server                • web-javascript • Flutter Tools

! Doctor found issues in 4 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: unknown
**Creation framework version**: 8af6b2f038c1172e61d418869363a28dffec3cb4

when I lsof 5353 port, it shows:
```
(py2) ➜  flutter git:(8af6b2f038) ✗ lsof -i:5353
COMMAND   PID  USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
dart    80598 along    8u  IPv4 0xeee444a50978dd0d      0t0  UDP *:mdns
dart    80598 along   14u  IPv4 0xeee444a50978c2e5      0t0  UDP localhost:mdns
```

**Comment by TahaTesser** [comment] 2021-03-23 15:23
Hi @oncealong 
You seem to be using  a nine-months old of Flutter setup 
Can you please upgrade to the latest  `stable` and try again
`flutter channel stable`
`flutter upgrade --force`
`flutter doctor -v`

Closing as this is an outdated Flutter version, the issue is most likely fixed by now
Thank you

**Closed by TahaTesser** 2021-03-23 15:23 UTC
Labels: in triage

**Comment by oncealong** [comment] 2021-03-24 06:09
@TahaTesser 
same with flutter 2.0 stable, https://github.com/flutter/flutter/issues/78937
