### ISSUE TITLE
[go_router] PopScope not working on Android

### ISSUE THREAD

**Issue by minhnguyenandpad** [flutter/flutter#138525] opened 2023-11-16 05:45 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I have update to Flutter stable 3.16.0 and Dart 3.2.0
And migrate from `WillPopScope` to `PopScope`
Refer to: https://docs.flutter.dev/release/breaking-changes/android-predictive-back

### Expected results

The `_doSomethingWhenPressPhysicButton` should be called when user press the physic back button on `android`.

### Actual results

Nothing happen when I press the physic button.

### Code sample

<details><summary>Code sample</summary>

Before:
```dart
WillPopScope(
  onWillPop: () async {
    _doSomethingWhenPressPhysicButton(); /// This is working
    return true;
  },
  child: ...
),

```
After:
```dart
PopScope(
  canPop: true,
  onPopInvoked (bool didPop) {
    _doSomethingWhenPressPhysicButton(); /// Nothing happen
  },
  child: ...
),
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>
</details>

### Logs

<details><summary>Logs</summary>

```console
I/ViewRootImpl@e6d6173[MainActivity](31551): ViewPostIme pointer 0
I/ViewRootImpl@e6d6173[MainActivity](31551): ViewPostIme pointer 1
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.16.0, on macOS 12.6.1 21G217 darwin-arm64, locale en-JP)
    • Flutter version 3.16.0 on channel stable at /Users/minh.nguyen/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db7ef5bf9f (10 hours ago), 2023-11-15 11:25:44 -0800
    • Engine revision 74d16627b9
    • Dart version 3.2.0
    • DevTools version 2.28.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/minh.nguyen/Library/Android/sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • ANDROID_HOME = /Users/minh.nguyen/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.13.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.66.2)
    • VS Code at /Users/minh.nguyen/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.40.0

[✓] Connected device (4 available)
    • SM G991B (mobile) • R5CR41JCJCD                          • android-arm64  • Android 13 (API 33)
    • macOS (desktop)   • macos                                • darwin-arm64   • macOS 12.6.1 21G217 darwin-arm64
    • Chrome (web)      • chrome                               • web-javascript • Google Chrome 119.0.6045.123

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

</details>

**Comment by danagbemava-nc** [comment] 2023-11-16 08:41
Hi @minhnguyenandpad, can you please provide a complete minimal reproducible code sample so that we can investigate this? 

I tested the PopScope example from https://api.flutter.dev/flutter/widgets/PopScope-class.html and the back button worked for me. Can you also try that example to see if it works for you as well? 

Thank you

**Comment by andretofa** [comment] 2023-11-16 09:29
I also experience a problem with PopScope, but for flutter web on the mobile browsers Chrome, Firefox & Safari. My experience is, that the swipe gesture to navigate the browser to a previous page will go through, even though you have set canpop to false. Example code:

```
class MyWidget extends StatelessWidget {
  const MyWidget({super.key});

  @override
  Widget build(BuildContext context) {
    return PopScope(
      canPop: false,
      child: Scaffold(
        body: Center(
          child: Text('Please don\'t pop me!'),
        ),
      ),
    );
  }
}
```

**Comment by btrautmann** [comment] 2023-11-16 20:50
I'm not sure if this should be posted here or in its own issue, but our team was investigating `PopScope` and found some interesting behavior that can be reproduced using [this repo](https://github.com/btrautmann/pop_scope_repro). I don't believe this component is behaving as described in the docs.

**Using Navigator 1.0 APIs on iOS 17:**
1. When `canPop` is set to `true`, user can go back via app bar or back button and `onPopInvoked` is invoked with `didPop` set to `true` in both cases.
2. When `canPop` is set to `false`, user cannot go back via app bar or back button, but `onPopInvoked` is only invoked with `didPop` set to `false` when pressing app bar back button. It is _not_ invoked at all for the back gesture, which is _unexpected_ per the docs (which read _The [onPopInvoked] parameter reports when system back gestures occur, regardless of whether or not they were successful_).

**Using GoRouter APIs on iOS 17:**
1. When `canPop` is set to `true`, user can go back via app bar or back button _but_ `onPopInvoked` is never invoked.
2. When `canPop` is set to `false`, user cannot go back via app bar or back button but again `onPopInvoked` is only invoked with `didPop` set to `false` when pressing app bar back button. It is not invoked for the back gesture.

**Using Navigator 1.0 APIs on Android 14:**
1. When `canPop` is set to `true`, user can go back via app bar or back button and `onPopInvoked` is invoked with `didPop` set to `true` in both cases.
2. When `canPop` is set to `false`, user cannot go back via app bar or back button, and `onPopInvoked` is `invoked` in both cases with `didPop` set to `false`

**Using GoRouter APIs on Android 14:**
1. When `canPop` is set to `true`, user can go back via app bar or back button _but_ `onPopInvoked` is never invoked.
2. When `canPop` is set to `false`, user cannot go back via app bar or back button. `onPopInvoked` is invoked in both cases with `didPop` set to `false`.

**Summary Table:**

Platform | Nav API      | `canPop` value |  `onPopInvoked` via `appBar` | `onPopInvoked` on back swipe | Expected |
| ----------- | ----------- | ----------- | ----------- | ----------- | ----------- |
| iOS     | 1.0 | true | true | true | true
| iOS     | 1.0 | false | true | false | **false**
| iOS     | GoRouter | true | false | false | **false**
| iOS     | GoRouter | false | true | false | **false**
| Android     | 1.0 | true | true | true | true
| Android     | 1.0 | false | true | true | true
| Android     | GoRouter | true | false | false | **false**
| Android     | GoRouter | false | true | true | true

**Comment by btrautmann** [comment] 2023-11-16 21:00
@minhnguyenandpad my results table above seems to corroborate your report if you're using `GoRouter` in your application. Is that the case, or are you using Navigator 1.0?

**Comment by minhnguyenandpad** [comment] 2023-11-17 03:49
> @minhnguyenandpad my results table above seems to corroborate your report if you're using `GoRouter` in your application. Is that the case, or are you using Navigator 1.0?

Yes we currently use `GoRouter`

**Comment by minhnguyenandpad** [comment] 2023-11-17 06:42
> Hi @minhnguyenandpad, can you please provide a complete minimal reproducible code sample so that we can investigate this?
> 
> I tested the PopScope example from https://api.flutter.dev/flutter/widgets/PopScope-class.html and the back button worked for me. Can you also try that example to see if it works for you as well?
> 
> Thank you

We are currently using `Go Router` and this behavior happen. It's working fine with default navigator.

**Comment by danagbemava-nc** [comment] 2023-11-17 07:24
@andretofa, kindly file a new issue and provide detailed info so that we can investigate. 

@btrautmann thanks for the detailed investigation. I believe it would be best to file separate issues for each inconsistency in the behaviour of the widget and what is expressed in the docs. This way it is easier to know when any/all of them have been fixed. 
Also, the table isn't quite clear to me😅, what value/state is the `expected` column corresponding to? 

@minhnguyenandpad can you provide the minimal sample for your case? I would like to compare results with the sample provided by @btrautmann

**Comment by btrautmann** [comment] 2023-11-17 10:53
> Also, the table isn't quite clear to me😅, what value/state is the `expected` column corresponding to?

Sorry about that. The `Expected` column is intended to communicate whether the behavior in the preceding columns was expected based on the documentation of `PopScope`.

**Comment by btrautmann** [comment] 2023-11-17 10:56
> I believe it would be best to file separate issues for each inconsistency in the behaviour of the widget and what is expressed in the docs

Just to be clear before I go forward, are you saying you want an issue for _each_ failing  row in the table, or just for the entire table itself? My thinking is one issue for the whole table may be fine, but wanted to double check based on your wording.

**Comment by AndreiMisiukevich** [comment] 2023-11-17 13:05
@danagbemava-nc 

Is there any chance the decision about deprecating `WillPopScope` will be revisited?

My team finds `PopScope` inconvenient in comparison to `WillPopScope`.

While `WillPopScope` allows to intercept the pop-action intent, the `PopScope` doesn't. Instead, `PopScope` proposes to handle the result of this action.

In our case, we want to present confirmation dialogs when the user wants to close the page and `WillPopScope` works like a charm in this scenario.

Yes, we can set `canPop: false` and write dialogue prompting logic inside `onPopInvoked`, but it doesn't solve the problem because the result of `NavigatorState.maybePop` will be returned before the user answers to dialog.

**Comment by btrautmann** [comment] 2023-11-17 15:51
> As [btrautmann](https://github.com/btrautmann)'s comment, we are currently using `GoRouter` and this behavior happen. It's working fine with default navigator when I create an example app.
> 
> Could you help me add `p: go_router` label for this issue?

Just to be clear, there are definitely some issues with compat with 1.0 APIs. I'l open an issue that highlights that per my above comment.

**Comment by matt-hall-zory** [comment] 2023-11-18 01:31
I'm using auto_route which has the same issues as go router. onPopInvoked is not being called.
WillPopScope was deprecated far too soon.

**Comment by danagbemava-nc** [comment] 2023-11-20 07:45
> Just to be clear before I go forward, are you saying you want an issue for each failing row in the table, or just for the entire table itself? My thinking is one issue for the whole table may be fine, but wanted to double check based on your wording.

Hi @btrautmann, sorry for the late reply. I meant more in the sense of grouping the issues based on whether they happen when you're using go_router or when you're using the navigator apis. The reason behind filing multiple issues as I stated [above](https://github.com/flutter/flutter/issues/138525#issuecomment-1815861499) is to make it so it's easier for the teams involved to investigate each individual case effectively. Sometimes having multiple items within a single issues makes it a bit tedious to investigate

**Comment by btrautmann** [comment] 2023-11-20 17:40
> > Just to be clear before I go forward, are you saying you want an issue for each failing row in the table, or just for the entire table itself? My thinking is one issue for the whole table may be fine, but wanted to double check based on your wording.
> 
> Hi @btrautmann, sorry for the late reply. I meant more in the sense of grouping the issues based on whether they happen when you're using go_router or when you're using the navigator apis. The reason behind filing multiple issues as I stated [above](https://github.com/flutter/flutter/issues/138525#issuecomment-1815861499) is to make it so it's easier for the teams involved to investigate each individual case effectively. Sometimes having multiple items within a single issues makes it a bit tedious to investigate

Cool, the same was requested on the new issue, so I'll break that new issue out into one for 1.0 and one for GoRouter.

**Comment by btrautmann** [comment] 2023-11-20 17:46
Just a heads up that I've opened https://github.com/flutter/flutter/issues/138737 and I believe it's a superset of this issue, so it's possible this can be closed in favor of that one unless somebody disagrees! @minhnguyenandpad LMK if you don't think the new issue covers your case.

**Comment by WebSchw** [comment] 2023-12-04 20:49
Are there some workarounds until this issue (see #138737) is fixed?

**Comment by subzero911** [comment] 2023-12-05 12:06
Same here.
WillPopScope is marked as deprecated, but it works.
<img width="804" alt="image" src="https://github.com/flutter/flutter/assets/12999702/1ced0f79-90a6-4ac1-8ac1-1cca6a12f3d4">

`PopScope` just doesn't work.

**Closed** 2023-12-06 06:23 UTC
Labels: waiting for customer response, in triage
