### ISSUE TITLE
[iOS] Sign in with Apple requirement

### ISSUE THREAD

**Issue by MarkOSullivan94** [flutter/flutter#34387] opened 2019-06-13 08:22 UTC
As announced at WWDC this year it looks like Apple will be requiring iOS apps to have a "Sign in with Apple" button if they offer a 3rd-party sign in option (like Facebook or Google).

> It will be required as an option for users in apps that support third-party sign-in when it is commercially available later this year.

https://developer.apple.com/news/?id=06032019j

# Use case

This is more a precaution than an issue I am having currently. 

It should help avoid any issues with iOS Flutter apps in the future being rejected from the Apple store with some planning and preparation around this issue.

## Proposal

I guess one of these two approaches could be used to help tackle any potential issue in the future: 

- Updating all of the sign in packages READMEs on how to add this button and create a new package using the "Sign in with Apple" button

or

- Possibly add it automatically with existing sign in packages if the Flutter app is being run on an iOS device

I've listed the two most popular packages for sign in functionality below however there might be others with pub.dev which would also have to be updated.

https://pub.dev/packages/google_sign_in
https://pub.dev/packages/firebase_auth

**Comment by collinjackson** [comment] 2019-06-13 18:27
If someone would like to submit a PR for option #1 to flutter/plugins, we would consider hosting it in the first-party plugins repository.

I don't know if it makes sense to add this functionality automatically since there are many cases where you might not need it.

**Comment by omarkamal** [comment] 2019-06-18 07:25
This is **certainly** a required package, as Flutter is predominantly used for service apps and a signing in via OAuth is a regular affair in such applications.

**Comment by tomgilder** [comment] 2019-06-20 03:49
I started work on a plugin this week. Should have an initial prototype by the weekend.

**Comment by omarkamal** [comment] 2019-06-20 06:29
Thanks, Tom! That's great news for everyone.

**Comment by tomgilder** [comment] 2019-06-23 21:27
Very early days and half-implemented but you can see an example here: https://github.com/tomgilder/flutter_sign_in_with_apple/blob/master/example/lib/main.dart

API is still evolving and package not ready to be published yet.

**Comment by deadsoul44** [comment] 2019-07-10 16:38
Is there any progress for this item? This is very important for developers who do not have mac but still wants to publish apps for ios.

**Comment by tomgilder** [comment] 2019-07-14 15:56
Published the initial version of the package, 0.0.1: https://pub.dev/packages/apple_sign_in

Tested with iOS 13 beta 3, logs in successfully and gets credentials. Still a few things to implement, see the readme.

Still need to decide if there's any value in adding support for Apple's JavaScript framework for other platforms to that package.

**Comment by deadsoul44** [comment] 2019-07-14 16:12
Great work. Starred and watching the repo. Thank you.

**Comment by json469** [comment] 2019-08-08 10:02
Will there be any UI elements for this? Apple has set out a good guideline for the button UI (https://developer.apple.com/design/human-interface-guidelines/sign-in-with-apple/overview/)

**Comment by sceee** [comment] 2019-09-15 13:09
Should this issue be moved to the https://github.com/FirebaseExtended/flutterfire Repo now since it affects firebase_auth?

I think for the UI elements @json469 took care in https://github.com/dmjones/flutter_auth_buttons/pull/13 so they should soon be in the `flutter_auth_buttons` package. What's missing is the implementation in Firebase ( https://github.com/firebase/firebase-ios-sdk/issues/3145 ) and following up the implementation in `firebase_auth` (which is now in the flutterfire Repo) is missing.

**Comment by tomgilder** [comment] 2019-09-29 17:36
Sorry for the lack of updates, have been a busy bee.

Just published 0.1.0 of [apple_sign_in](https://pub.dev/packages/apple_sign_in), the API should now be stable. It includes a Flutter "Sign In with Apple" or "Continue with Apple" button (only in English, for now).

Would love to get the package battle-tested, _please_ let me know if anyone's used it successfully (or unsuccessfully) in production.

**Comment by chrispypatt** [comment] 2019-10-02 12:25
> Sorry for the lack of updates, have been a busy bee.
> 
> Just published 0.1.0 of [apple_sign_in](https://pub.dev/packages/apple_sign_in), the API should now be stable. It includes a Flutter "Sign In with Apple" or "Continue with Apple" button (only in English, for now).
> 
> Would love to get the package battle-tested, _please_ let me know if anyone's used it successfully (or unsuccessfully) in production.

Awesome! Thanks, I am going to try using this with custom firebase tokens this week/weekend and and get back to you!

**Comment by epiphanatic** [comment] 2019-10-15 01:37
> Sorry for the lack of updates, have been a busy bee.
> 
> Just published 0.1.0 of [apple_sign_in](https://pub.dev/packages/apple_sign_in), the API should now be stable. It includes a Flutter "Sign In with Apple" or "Continue with Apple" button (only in English, for now).
> 
> Would love to get the package battle-tested, _please_ let me know if anyone's used it successfully (or unsuccessfully) in production.

Thank you! I've successfully used it in combination with firebase custom auth token using cloud function. Works beautifully. Production looks good on Android. Can't confirm Apple yet but will let you know if any problems there.

**Comment by deadsoul44** [comment] 2019-10-15 08:09
How did you use it on Android? This package is only for iOS?

**Comment by joserocha3** [comment] 2019-11-07 05:21
Hi @epiphanatic what steps are you taking to do this? Is it:

1. Get credentials using `apple_sign_in`
2. Send credentials to cloud function
3. Call `admin.auth().createCustomToken(uid)`
4. Return token to mobile device
5. Call `signInWithCustomToken(token)`

If that is what you are doing what did you use for `uid` and does `signInWithCustomToken` exist in flutter's `firebase_auth`?

**Comment by epiphanatic** [comment] 2019-11-07 05:41
@joserocha3 yep, that's exactly what I'm doing. For uid: when I get the apple credentials from
`final AuthorizationResult result = await AppleSignIn.performRequests([
      AppleIdRequest(requestedScopes: [Scope.email, Scope.fullName])
]);`
I then use `result.credential.user`. 
I printed the entire result and best I can tell that is Apple's form of uid (I have no experience with ios). It has the format of number.hash.number. 
However, as of ios 13.2 this plugin may not work. I was trying to get something into production with it, which was fine during 13.1, but it was rejected just as 13.2 became a requirement and they said the button didn't do anything. I haven't tested since then (I just pulled the plugin out to get it through) as I've not gotten around to it. But then again, I've had so many problems with Apple it could be just them...

**Comment by joserocha3** [comment] 2019-11-07 05:56
@epiphanatic I'll give it a go this coming week and test with 13.2. Maybe we can pinpoint an issue and @tomgilder can provide a fix. Thanks!

**Comment by tomgilder** [comment] 2019-11-07 07:42
Haven't tested with 13.2 - will take a look asap

**Comment by epiphanatic** [comment] 2019-11-07 08:24
@tomgilder @joserocha3 I just tested with 13.2, it's fine. As suspected, it is/was just Apple...

**Comment by erizakaria** [comment] 2019-11-27 10:38
hai, anyone can help me to findout how to regist to firebase using apple id sign in, sorry for my bad english. thanks

**Comment by dacxjo** [comment] 2019-11-27 17:32
Hi , im need a Sign in with apple to deploy my app, im using this plugin and realy works, im using firebase cloud function to generate the token and use _auth.signInWithCustomToken but the firebase user that returns is empty, why this happen or is there another way to use firebase?

**Comment by erizakaria** [comment] 2019-11-28 03:49
hi @dacxjo, can you tell me how to use firebase cloud function to generate the token, im still newbie by the way. thanks

**Comment by dacxjo** [comment] 2019-11-29 11:54
@erizakaria Hi, i dont now if my approach is the best but to my situation it works.

What i did, is create a "callable" cloud function , you can create one on the [cloud console](https://console.cloud.google.com/) , make sure that you select the right project , and enable for the project the [Identity and Access Management (IAM) API](https://console.developers.google.com/apis/library/iam.googleapis.com?q=IAM&id=7af3ed42-ced4-4dcb-a8e0-6c823c9c40b9&project=arpen-249810&authuser=1&hl=ES), which is required to generate custom tokens.

This is what i have in my cloud function:

```
const admin = require("firebase-admin");
const functions = require("firebase-functions");
admin.initializeApp();

exports.appleToken = functions.https.onCall(async (data, context) => {
  let uuid = data.uuid;
  let token = "";

  if (uuid != "") {
    await admin
      .auth()
      .getUserByEmail(data.email)
      .then(async user => {
        await admin
          .auth()
          .createCustomToken(user.uid)
          .then(tkn => {
            token = tkn;
          });
      })
      .catch(async err => {
        if (err.code === "auth/user-not-found") {
          await admin
            .auth()
            .createUser({
              uid: uuid,
              email: data.email,
              displayName: data.name
            })
            .then(async userRecord => {
              await admin
                .auth()
                .createCustomToken(userRecord.uid)
                .then(tkn => {
                  token = tkn;
                });
            });
        }
      });

    return {
      token: token
    };
  } else {
    return null;
  }
});

```

and my package.json

```
{
  "name": "sample-http",
  "version": "0.0.1",
  "engines": {
    "node": "8"
  },
  "dependencies": {
    "firebase-admin": "^8.0.0",
    "firebase-functions": "^3.2.0"
  }
}
```
as you can see , first check if the user already exist to generate a token with his uid but if not the user is created and after the token is generated and returned.

Back in your flutter app , you'll have to install the [cloud_functions plugin](https://pub.dev/packages/cloud_functions) .

Create an instance of a callable function:

```
 final HttpsCallable callable = CloudFunctions.instance.getHttpsCallable(
    functionName: 'your_cloud_function_name',
  );
```

And when the apple_signin plugin returns your user data (email,uuid,name) , then you call the cloud function that should return the token , in which you will call the _firebaseAuth.signInWithCustomToken:
```
 try {
          await callable.call(<String, dynamic>{
            'uuid': result.credential.user,
            'name': result.credential.fullName.givenName,
            'email': result.credential.email 
          }).then((HttpsCallableResult res) async {
            await _auth
                .signInWithCustomToken(token: res.data['token'])
                .then((authRes) {
              print(authRes);
            });
            Navigator.of(context, rootNavigator: true).pop();
            notifyListeners();
          }).catchError((err) {
            print(err);
          });

```

This is what i did, i don't know if this is going to help you but is what works to me. And sorry if i don't explain well, english is not my first language.

**Comment by dacxjo** [comment] 2019-11-29 12:14
@erizakaria i forgot to say that you can monitor the cloud functions behavior from the firebase console , in the left menu "Functions"

**Comment by ssbaval** [comment] 2019-11-29 13:00
@epiphanatic @joserocha3 I've also used the apple_sign_in and can confirm it works but created a custom auth solution using backend Node.js code to generate the token and then using signInWithCustomToken to complete the firebase side.  My observations and maybe you guys can comment : 

1- Email is blank in **identifier** field in Firebase authentication tab (Can be resolved by adding this inside callable function)

2- **Provider** field in Firebase authentication tab is blank

3- Provider field in FirebaseUser after call from **signInWithCustomToken**   is **Firebase** and not **Apple** - I'm guessing this is because we have opted for a custom auth solution and not provided an equivalent  **AuthCredential**

4- Since FirebaseUser provider field is now **Firebase** it means your Node function will fail if there is another Firebase user with the same email address. This is incorrect since if there is a Facebook, Twitter, Google, Github user with the same email address - your node function will pass because the provider is different.

Do you guys get the same observation and more importantly - is there a way to change the Provider ID/Description so its not 'Firebase' (In Firebase User)  and 'BLANK' in Authentication console (Ultimately I'm guessing google needs to Update **Firebase Auth** to provide an **AppleAuthProvider**

**Comment by therealjohnsummer** [comment] 2019-11-29 16:31
@dacxjo The approach you are using in your cloud function is somewhat flawed. The issue you have is that you assume that the email address is unique. In Firebase as you know, there is the ability to allow **multiple accounts per email address**. If this is enabled, based on your current logic , two users with the same email address and different providers will have access to the same data ...

i.e 

Assume you have a firebase user called : myFirebaseUser@gmail.com - and this user is authenticated already on Firebase and has the provider set to Firebase.

Now assume you also enable apple sign in, and a new user also called myFirebaseUser@gmail.com wants to sign in via apple sign in. Note - these two users are completely different. They just share the same email address but have different conceptual providers : 

myFirebaseUser@gmail.com  Provider==> Firebase
myFirebaseUser@gmail.com  provider==> Apple

Based on your logic of checking for a valid email user -> your code will confirm that **myFirebaseUser@gmail.com ** already exists and will then return the custom token for that user and then allow that user to be authenticated and be allowed to log in.

The issue is that the myFirebaseUser@gmail.com  user is the apple user (And should have a completely different user area) compared to myFirebaseUser@gmail.com  (which is the Firebase user). In your example , user data areas (assuming you set this up based on email/uid) would be shared across two or more entirely different users.

The issue is compounded because a **Custom Auth** solution will not have valid Provider information for **Apple Sign in**

**Comment by AirborneEagle** [comment] 2019-11-30 01:40
@therealjohnsummer 
This is the firebase default auth behavior
`Prevent users from creating multiple accounts using the same email address with different authentication providers`

Are you suggesting that it should not be that way?

**Comment by therealjohnsummer** [comment] 2019-11-30 10:19
@AirborneEagle Not sure how you deduced I was suggesting this should not be the case by my last post. I tried to be specific by stating : 

> In Firebase as you know, there is the ability to allow multiple accounts per email address.

I was simply trying to illustrate that the solution presented by @dacxjo **is only** suitable in the **default firebase auth** set up. If one changes the default to : 

![image](https://user-images.githubusercontent.com/54981654/69899075-4478b580-1359-11ea-8bcc-6d524f579461.png)
 
Which provides added flexibility for social provider login and allows logons such as : 

user@gmail.com   -> using facebook provider
user@gmail.com   -> using google provider
user@gmail.com   -> using twitter provider
user@gmail.com   -> using firebase provider


which then allows a custom logon solution to allow more flexibility when creating user accounts which share the same email address such as : 

![image](https://user-images.githubusercontent.com/54981654/69899166-8eae6680-135a-11ea-9afc-c0589d8a96df.png)

etc

**Comment by dacxjo** [comment] 2019-11-30 17:58
@therealjohnsummer In my firebase console i have enabled **Allow creation of multiple account with the same email address** to share the account data when the email is exactly the same. I know that this is not the best behavior but , this is a workaround because I didn't find a reasonable way or tutorial to link accounts providers with firebase auth using the linkWithCredentials method.

**Comment by therealjohnsummer** [comment] 2019-11-30 19:01
@dacxjo There is no need to use LinkWithCredentials. As can be seen with my last post - 4 distinct users with same email log in and each have separate user folders. Your approach and more importantly your Node.js cloud function would not facilitate this.

**Comment by i6x86** [comment] 2019-12-01 20:28
> @dacxjo There is no need to use LinkWithCredentials. As can be seen with my last post - 4 distinct users with same email log in and each have separate user folders. Your approach and more importantly your Node.js cloud function would not facilitate this.

Not sure if I understand correctly, but why do someone should create separate user folders if they want to link the existing one with the newly "created". In my use case I need to save the user folder with all faves, stuff and all... so I need this functionality, two different users (well they are really one with different signin methods) to share one account folder.

**Comment by therealjohnsummer** [comment] 2019-12-01 21:03
@i6x86  Firestore authentication allows social provider logon as well as Firebase logon. The latter allows one to enter ANY email address whatsoever. That email address could be the same email address as a valid user on your system who say uses gmail. If I then use a known gmail address of a user on your system and attempt to create a user account using this email, if you follow the approach @dacxjo uses - you will end up piggy backing of the other users account - assuming you allow the creation of multiple email accounts and also do not require that an email address has been checked (User taps on the email link to verify their email address via the email sent from Firebase).

**Comment by i6x86** [comment] 2019-12-02 01:39
@therealjohnsummer ok I think I get it. I didn't saw it because I use only Facebook and Gmail and they both are prompt for password so if you don't have access to the user device you can not log in with their account. I think it would be the same with Apple. Am I right or there's something I miss?

**Comment by batbileg289** [comment] 2019-12-03 12:39
Is it working now? Is there anyone who have successfully implemented Apple Sign-In in Flutter iOS App using Firebase Authentication?

**Comment by lgArlequin** [comment] 2019-12-03 13:26
@batbileg289 I am using the method proposed by @dacxjo  and it works fairly well.

**Comment by batbileg289** [comment] 2019-12-03 15:31
Why do we need to use cloud functions? 
Is there any known bug in library? If so, is there anyone who can fix that bug? :)

**Comment by TheJulianJES** [comment] 2019-12-03 15:33
For iOS there's currently a PR in the FlutterFire Repo: https://github.com/FirebaseExtended/flutterfire/pull/1526

**Comment by lgArlequin** [comment] 2019-12-03 15:35
Because the method does not yet exist in the firebase_auth plugin.
https://github.com/FirebaseExtended/flutterfire/issues/1434

**Comment by batbileg289** [comment] 2019-12-03 15:40
@TheJulianJES @lgArlequin Thanks

**Comment by i6x86** [comment] 2019-12-04 14:38
Does anyone get done the Android side? I think we'll appreciate some good example.

**Comment by rinusaha** [comment] 2019-12-15 16:46
> For iOS there's currently a PR in the FlutterFire Repo: [FirebaseExtended/flutterfire#1526](https://github.com/FirebaseExtended/flutterfire/pull/1526)

Any idea, when it will be available in Flutter pub store? As of now, I can see it is 0.15.2, which does not have the changes.

**Comment by lannes** [comment] 2019-12-17 02:43
> Sorry for the lack of updates, have been a busy bee.
> 
> Just published 0.1.0 of [apple_sign_in](https://pub.dev/packages/apple_sign_in), the API should now be stable. It includes a Flutter "Sign In with Apple" or "Continue with Apple" button (only in English, for now).
> 
> Would love to get the package battle-tested, _please_ let me know if anyone's used it successfully (or unsuccessfully) in production.

@tomgilder 

Hi Tom, I submit success with apple_sign_in plugin, however I must fix button text for Vietnamese language.

https://apps.apple.com/us/app/lsicheck/id1471614412?ls=1

Thank you very much!

**Comment by collinjackson** [comment] 2019-12-17 23:32
> > For iOS there's currently a PR in the FlutterFire Repo: [FirebaseExtended/flutterfire#1526](https://github.com/FirebaseExtended/flutterfire/pull/1526)
> 
> Any idea, when it will be available in Flutter pub store? As of now, I can see it is 0.15.2, which does not have the changes.

You can update to 0.15.3 to get Apple sign-in support.

**Comment by collinjackson** [comment] 2019-12-17 23:36
Marking this closed since I don't think there's anything more for the Flutter team to do here, but please let me know if I'm mistaken and I'll reopen.

**Closed by collinjackson** 2019-12-17 23:36 UTC
Labels: plugin, severe: new feature, would be a good package

**Comment by rinusaha** [comment] 2019-12-18 16:49
> Marking this closed since I don't think there's anything more for the Flutter team to do here, but please let me know if I'm mistaken and I'll reopen.

Thanks a lot @collinjackson 
I am getting this error after upgrading to version 0.15.3. Can you please help, if anything I am missing here?
_______________________________________________________________________________________________________________
Xcode's output:
↳
    /Users/soumensaha/Softwares/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.15.3/ios/Classes/FLTFirebaseAuthPlugin.m:493:38: error: no known class method for selector
    'credentialWithProviderID:IDToken:rawNonce:accessToken:'
          credential = [FIROAuthProvider credentialWithProviderID:provider
                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Users/soumensaha/Softwares/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.15.3/ios/Classes/FLTFirebaseAuthPlugin.m:502:38: error: no known class method for selector 'credentialWithProviderID:IDToken:rawNonce:'
          credential = [FIROAuthProvider credentialWithProviderID:provider
                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    2 errors generated.
_______________________________________________________________________________________________________________

**Comment by enzobonggio** [comment] 2019-12-20 03:25
> > Marking this closed since I don't think there's anything more for the Flutter team to do here, but please let me know if I'm mistaken and I'll reopen.
> 
> Thanks a lot @collinjackson
> I am getting this error after upgrading to version 0.15.3. Can you please help, if anything I am missing here?
> 
> Xcode's output:
> ↳
> /Users/soumensaha/Softwares/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.15.3/ios/Classes/FLTFirebaseAuthPlugin.m:493:38: error: no known class method for selector
> 'credentialWithProviderID:IDToken:rawNonce:accessToken:'
> credential = [FIROAuthProvider credentialWithProviderID:provider
> ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> /Users/soumensaha/Softwares/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.15.3/ios/Classes/FLTFirebaseAuthPlugin.m:502:38: error: no known class method for selector 'credentialWithProviderID:IDToken:rawNonce:'
> credential = [FIROAuthProvider credentialWithProviderID:provider
> ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 2 errors generated.

I have the same problem 0.15.3 also

**Comment by dacxjo** [comment] 2019-12-20 13:01
Same error here, after update to the last version

**Comment by lgArlequin** [comment] 2019-12-20 15:38
I solved this error as most of the time I do it ...

Run **pod update** in the IOS folder

**Comment by rinusaha** [comment] 2020-01-22 17:16
Made this work by replacing this code in  FLTFirebaseAuthPlugin.m file.


    // if (accessToken != (id)[NSNull null] && rawNonce != (id)[NSNull null] &&
    //     [accessToken length] != 0 && [rawNonce length] != 0) {
    //   credential = [FIROAuthProvider credentialWithProviderID:provider
    //                                                   IDToken:idToken
    //                                                  rawNonce:rawNonce
    //                                               accessToken:accessToken];
    // } else if (accessToken != (id)[NSNull null] && [accessToken length] != 0) {
    //   credential = [FIROAuthProvider credentialWithProviderID:provider
    //                                                   IDToken:idToken
    //                                               accessToken:accessToken];
    // } else if (rawNonce != (id)[NSNull null] && [rawNonce length] != 0) {
    //   credential = [FIROAuthProvider credentialWithProviderID:provider
    //                                                   IDToken:idToken
    //                                                  rawNonce:rawNonce];
    // } else {
    //   NSLog(@"To use OAuthProvider you need to provide at least one of the following 'accessToken' "
    //         @"or 'rawNonce'.");
    // }
    credential = [FIROAuthProvider credentialWithProviderID:provider
                                                      IDToken:idToken
                                                  accessToken:accessToken];

**Comment by xster** [comment] 2020-04-17 17:02
@collinjackson could you also update the firebase_auth documentation to describe how to use or add the option for apple sign in?
