### ISSUE TITLE
Debug broken on new iPad Mini / Process exited with status = -1 (0xffffffff) lost connection

### ISSUE THREAD

**Issue by stx** [flutter/flutter#90704] opened 2021-09-25 03:40 UTC
## Steps to Reproduce

1. flutter create .
2. flutter run

USB-C to USB-C cable on 2019 16" MacBook Pro.

<details>
  <summary>Logs</summary>

```

[ +117 ms]  └─Compiling, linking and signing... (completed in 4.4s)
[        ] Xcode build done.                                            8.5s
[   +1 ms] executing: rsync -av --delete /Users/james/Development/test/build/ios/Debug-iphoneos/Runner.app
/Users/james/Development/test/build/ios/iphoneos
[  +16 ms] building file list ... done
           Runner.app/
           Runner.app/Info.plist
           Runner.app/PkgInfo
           Runner.app/Runner
           Runner.app/embedded.mobileprovision
           Runner.app/Frameworks/
           Runner.app/_CodeSignature/CodeResources

           sent 148281 bytes  received 142 bytes  296846.00 bytes/sec
           total size is 121936479  speedup is 821.55
[   +3 ms] Installing and launching...
[        ] Debugging is enabled, connecting to observatory
[   +6 ms] executing: script -t 0 /dev/null /Users/james/Development/flutter/bin/cache/artifacts/ios-deploy/ios-deploy --id
00008110-000A58163E98801E --bundle build/ios/iphoneos/Runner.app --app_deltas build/ios/app-delta --debug --no-wifi --args
--enable-dart-profiling --disable-service-auth-codes --enable-checked-mode --verify-entry-points
[  +25 ms] [....] Waiting for iOS device to be connected
[   +8 ms] [....] Using 00008110-000A58163E98801E (J310AP, J310AP, uknownos, unkarch) a.k.a. 'iPad mini'.
[        ] ------ Install phase ------
[        ] [  0%] Found 00008110-000A58163E98801E (J310AP, J310AP, uknownos, unkarch) a.k.a. 'iPad mini' connected through USB,
beginning install
[ +173 ms] [  5%] TransferringPackage
[        ] [  5%] Copying /Users/james/Development/test/build/ios/iphoneos/Runner.app/META-INF/ to device
[        ] [  5%] Copying /Users/james/Development/test/build/ios/iphoneos/Runner.app/META-INF/com.apple.ZipMetadata.plist to device
[        ] [  5%] Copying /Users/james/Development/test/build/ios/iphoneos/Runner.app/_CodeSignature/ to device
[        ] [  5%] Copying /Users/james/Development/test/build/ios/iphoneos/Runner.app/_CodeSignature/CodeResources to device
[        ] [  5%] Copying /Users/james/Development/test/build/ios/iphoneos/Runner.app/AppIcon20x20@2x.png to device
[        ] [  6%] Copying /Users/james/Development/test/build/ios/iphoneos/Runner.app/AppIcon20x20@3x.png to device
[        ] [  6%] Copying /Users/james/Development/test/build/ios/iphoneos/Runner.app/AppIcon29x29.png to device
[        ] [  6%] Copying /Users/james/Development/test/build/ios/iphoneos/Runner.app/AppIcon60x60@2x.png to device
[        ] [  6%] Copying /Users/james/Development/test/build/ios/iphoneos/Runner.app/Runner to device
[   +1 ms] [  7%] Copying /Users/james/Development/test/build/ios/iphoneos/Runner.app/AppIcon29x29@2x.png to device
[        ] [  7%] Copying /Users/james/Development/test/build/ios/iphoneos/Runner.app/AppIcon40x40@3x.png to device
[        ] [  7%] Copying /Users/james/Development/test/build/ios/iphoneos/Runner.app/AppIcon29x29~ipad.png to device
[        ] [  7%] Copying /Users/james/Development/test/build/ios/iphoneos/Runner.app/AppIcon40x40@2x.png to device
[        ] [  8%] Copying /Users/james/Development/test/build/ios/iphoneos/Runner.app/AppIcon29x29@3x.png to device
[        ] [  8%] Copying /Users/james/Development/test/build/ios/iphoneos/Runner.app/AppIcon60x60@3x.png to device
[        ] [  8%] Copying /Users/james/Development/test/build/ios/iphoneos/Runner.app/Base.lproj/ to device
[        ] [  8%] Copying /Users/james/Development/test/build/ios/iphoneos/Runner.app/Base.lproj/Main.storyboardc/ to device
[        ] [  9%] Copying
/Users/james/Development/test/build/ios/iphoneos/Runner.app/Base.lproj/Main.storyboardc/UIViewController-BYZ-38-t0r.nib to device
[        ] [  9%] Copying
/Users/james/Development/test/build/ios/iphoneos/Runner.app/Base.lproj/Main.storyboardc/BYZ-38-t0r-view-8bC-Xf-vdC.nib to device
[        ] [  9%] Copying /Users/james/Development/test/build/ios/iphoneos/Runner.app/Base.lproj/Main.storyboardc/Info.plist to device
[        ] [  9%] Copying /Users/james/Development/test/build/ios/iphoneos/Runner.app/Base.lproj/LaunchScreen.storyboardc/ to device
[        ] [ 10%] Copying
/Users/james/Development/test/build/ios/iphoneos/Runner.app/Base.lproj/LaunchScreen.storyboardc/01J-lp-oVM-view-Ze5-6b-2t3.nib to device
[        ] [ 10%] Copying
/Users/james/Development/test/build/ios/iphoneos/Runner.app/Base.lproj/LaunchScreen.storyboardc/UIViewController-01J-lp-oVM.nib to
device
[        ] [ 10%] Copying /Users/james/Development/test/build/ios/iphoneos/Runner.app/Base.lproj/LaunchScreen.storyboardc/Info.plist to
device
[        ] [ 10%] Copying /Users/james/Development/test/build/ios/iphoneos/Runner.app/Assets.car to device
[        ] [ 10%] Copying /Users/james/Development/test/build/ios/iphoneos/Runner.app/AppFrameworkInfo.plist to device
[        ] [ 11%] Copying /Users/james/Development/test/build/ios/iphoneos/Runner.app/AppIcon40x40@2x~ipad.png to device
[        ] [ 11%] Copying /Users/james/Development/test/build/ios/iphoneos/Runner.app/AppIcon76x76@2x~ipad.png to device
[        ] [ 11%] Copying /Users/james/Development/test/build/ios/iphoneos/Runner.app/AppIcon83.5x83.5@2x~ipad.png to device
[        ] [ 11%] Copying /Users/james/Development/test/build/ios/iphoneos/Runner.app/AppIcon29x29@2x~ipad.png to device
[        ] [ 12%] Copying /Users/james/Development/test/build/ios/iphoneos/Runner.app/AppIcon40x40~ipad.png to device
[        ] [ 12%] Copying /Users/james/Development/test/build/ios/iphoneos/Runner.app/Frameworks/ to device
[        ] [ 12%] Copying /Users/james/Development/test/build/ios/iphoneos/Runner.app/Frameworks/libswiftCoreImage.dylib to device
[   +5 ms] [ 12%] Copying /Users/james/Development/test/build/ios/iphoneos/Runner.app/Frameworks/libswiftObjectiveC.dylib to device
[  +64 ms] [ 13%] Copying /Users/james/Development/test/build/ios/iphoneos/Runner.app/Frameworks/libswiftCore.dylib to device
[+1121 ms] [ 17%] Copying /Users/james/Development/test/build/ios/iphoneos/Runner.app/Frameworks/libswiftCoreGraphics.dylib to device
[  +40 ms] [ 18%] Copying /Users/james/Development/test/build/ios/iphoneos/Runner.app/Frameworks/libswiftUIKit.dylib to device
[  +29 ms] [ 18%] Copying /Users/james/Development/test/build/ios/iphoneos/Runner.app/Frameworks/libswiftMetal.dylib to device
[  +21 ms] [ 18%] Copying /Users/james/Development/test/build/ios/iphoneos/Runner.app/Frameworks/libswiftDispatch.dylib to device
[  +79 ms] [ 19%] Copying /Users/james/Development/test/build/ios/iphoneos/Runner.app/Frameworks/libswiftos.dylib to device
[  +15 ms] [ 19%] Copying /Users/james/Development/test/build/ios/iphoneos/Runner.app/Frameworks/libswiftCoreFoundation.dylib to device
[  +14 ms] [ 19%] Copying /Users/james/Development/test/build/ios/iphoneos/Runner.app/Frameworks/Flutter.framework/ to device
[        ] [ 20%] Copying /Users/james/Development/test/build/ios/iphoneos/Runner.app/Frameworks/Flutter.framework/_CodeSignature/ to
device
[        ] [ 20%] Copying
/Users/james/Development/test/build/ios/iphoneos/Runner.app/Frameworks/Flutter.framework/_CodeSignature/CodeResources to device
[        ] [ 20%] Copying /Users/james/Development/test/build/ios/iphoneos/Runner.app/Frameworks/Flutter.framework/icudtl.dat to device
[  +51 ms] [ 21%] Copying /Users/james/Development/test/build/ios/iphoneos/Runner.app/Frameworks/Flutter.framework/Flutter to device
[+1654 ms] [ 27%] Copying /Users/james/Development/test/build/ios/iphoneos/Runner.app/Frameworks/Flutter.framework/Headers/ to device
[        ] [ 28%] Copying
/Users/james/Development/test/build/ios/iphoneos/Runner.app/Frameworks/Flutter.framework/Headers/FlutterEngine.h to device
[        ] [ 28%] Copying
/Users/james/Development/test/build/ios/iphoneos/Runner.app/Frameworks/Flutter.framework/Headers/FlutterChannels.h to device
[        ] [ 28%] Copying
/Users/james/Development/test/build/ios/iphoneos/Runner.app/Frameworks/Flutter.framework/Headers/FlutterPlugin.h to device
[        ] [ 28%] Copying
/Users/james/Development/test/build/ios/iphoneos/Runner.app/Frameworks/Flutter.framework/Headers/FlutterAppDelegate.h to device
[        ] [ 29%] Copying
/Users/james/Development/test/build/ios/iphoneos/Runner.app/Frameworks/Flutter.framework/Headers/FlutterTexture.h to device
[        ] [ 29%] Copying
/Users/james/Development/test/build/ios/iphoneos/Runner.app/Frameworks/Flutter.framework/Headers/FlutterEngineGroup.h to device
[        ] [ 29%] Copying
/Users/james/Development/test/build/ios/iphoneos/Runner.app/Frameworks/Flutter.framework/Headers/FlutterPlatformViews.h to device
[        ] [ 29%] Copying
/Users/james/Development/test/build/ios/iphoneos/Runner.app/Frameworks/Flutter.framework/Headers/FlutterHeadlessDartRunner.h to device
[        ] [ 30%] Copying
/Users/james/Development/test/build/ios/iphoneos/Runner.app/Frameworks/Flutter.framework/Headers/FlutterCodecs.h to device
[        ] [ 30%] Copying /Users/james/Development/test/build/ios/iphoneos/Runner.app/Frameworks/Flutter.framework/Headers/Flutter.h to
device
[        ] [ 30%] Copying
/Users/james/Development/test/build/ios/iphoneos/Runner.app/Frameworks/Flutter.framework/Headers/FlutterViewController.h to device
[        ] [ 30%] Copying
/Users/james/Development/test/build/ios/iphoneos/Runner.app/Frameworks/Flutter.framework/Headers/FlutterMacros.h to device
[        ] [ 31%] Copying
/Users/james/Development/test/build/ios/iphoneos/Runner.app/Frameworks/Flutter.framework/Headers/FlutterDartProject.h to device
[        ] [ 31%] Copying
/Users/james/Development/test/build/ios/iphoneos/Runner.app/Frameworks/Flutter.framework/Headers/FlutterPluginAppLifeCycleDelegate.h to
device
[        ] [ 31%] Copying
/Users/james/Development/test/build/ios/iphoneos/Runner.app/Frameworks/Flutter.framework/Headers/FlutterBinaryMessenger.h to device
[        ] [ 31%] Copying
/Users/james/Development/test/build/ios/iphoneos/Runner.app/Frameworks/Flutter.framework/Headers/FlutterCallbackCache.h to device
[        ] [ 31%] Copying /Users/james/Development/test/build/ios/iphoneos/Runner.app/Frameworks/Flutter.framework/Modules/ to device
[        ] [ 32%] Copying
/Users/james/Development/test/build/ios/iphoneos/Runner.app/Frameworks/Flutter.framework/Modules/module.modulemap to device
[        ] [ 32%] Copying /Users/james/Development/test/build/ios/iphoneos/Runner.app/Frameworks/Flutter.framework/Info.plist to device
[        ] [ 32%] Copying /Users/james/Development/test/build/ios/iphoneos/Runner.app/Frameworks/App.framework/ to device
[        ] [ 32%] Copying /Users/james/Development/test/build/ios/iphoneos/Runner.app/Frameworks/App.framework/_CodeSignature/ to device
[        ] [ 33%] Copying
/Users/james/Development/test/build/ios/iphoneos/Runner.app/Frameworks/App.framework/_CodeSignature/CodeResources to device
[        ] [ 33%] Copying /Users/james/Development/test/build/ios/iphoneos/Runner.app/Frameworks/App.framework/App to device
[        ] [ 33%] Copying /Users/james/Development/test/build/ios/iphoneos/Runner.app/Frameworks/App.framework/flutter_assets/ to device
[        ] [ 33%] Copying /Users/james/Development/test/build/ios/iphoneos/Runner.app/Frameworks/App.framework/flutter_assets/NOTICES.Z
to device
[        ] [ 34%] Copying
/Users/james/Development/test/build/ios/iphoneos/Runner.app/Frameworks/App.framework/flutter_assets/vm_snapshot_data to device
[        ] [ 34%] Copying
/Users/james/Development/test/build/ios/iphoneos/Runner.app/Frameworks/App.framework/flutter_assets/isolate_snapshot_data to device
[ +283 ms] [ 35%] Copying
/Users/james/Development/test/build/ios/iphoneos/Runner.app/Frameworks/App.framework/flutter_assets/AssetManifest.json to device
[        ] [ 35%] Copying
/Users/james/Development/test/build/ios/iphoneos/Runner.app/Frameworks/App.framework/flutter_assets/kernel_blob.bin to device
[+1692 ms] [ 42%] Copying
/Users/james/Development/test/build/ios/iphoneos/Runner.app/Frameworks/App.framework/flutter_assets/FontManifest.json to device
[        ] [ 43%] Copying /Users/james/Development/test/build/ios/iphoneos/Runner.app/Frameworks/App.framework/flutter_assets/packages/
to device
[        ] [ 43%] Copying
/Users/james/Development/test/build/ios/iphoneos/Runner.app/Frameworks/App.framework/flutter_assets/packages/cupertino_icons/ to device
[        ] [ 43%] Copying
/Users/james/Development/test/build/ios/iphoneos/Runner.app/Frameworks/App.framework/flutter_assets/packages/cupertino_icons/assets/ to
device
[        ] [ 43%] Copying
/Users/james/Development/test/build/ios/iphoneos/Runner.app/Frameworks/App.framework/flutter_assets/packages/cupertino_icons/assets/Cupe
rtinoIcons.ttf to device
[   +7 ms] [ 44%] Copying /Users/james/Development/test/build/ios/iphoneos/Runner.app/Frameworks/App.framework/flutter_assets/fonts/ to
device
[        ] [ 44%] Copying
/Users/james/Development/test/build/ios/iphoneos/Runner.app/Frameworks/App.framework/flutter_assets/fonts/MaterialIcons-Regular.otf to
device
[  +79 ms] [ 44%] Copying /Users/james/Development/test/build/ios/iphoneos/Runner.app/Frameworks/App.framework/Info.plist to device
[        ] [ 44%] Copying /Users/james/Development/test/build/ios/iphoneos/Runner.app/Frameworks/libswiftDarwin.dylib to device
[  +26 ms] [ 45%] Copying /Users/james/Development/test/build/ios/iphoneos/Runner.app/Frameworks/libswiftQuartzCore.dylib to device
[  +18 ms] [ 45%] Copying /Users/james/Development/test/build/ios/iphoneos/Runner.app/Frameworks/libswiftCoreAudio.dylib to device
[  +16 ms] [ 45%] Copying /Users/james/Development/test/build/ios/iphoneos/Runner.app/Frameworks/libswiftFoundation.dylib to device
[ +570 ms] [ 48%] Copying /Users/james/Development/test/build/ios/iphoneos/Runner.app/Frameworks/libswiftCoreMedia.dylib to device
[  +20 ms] [ 48%] Copying /Users/james/Development/test/build/ios/iphoneos/Runner.app/AppIcon20x20~ipad.png to device
[        ] [ 48%] Copying /Users/james/Development/test/build/ios/iphoneos/Runner.app/embedded.mobileprovision to device
[   +1 ms] [ 49%] Copying /Users/james/Development/test/build/ios/iphoneos/Runner.app/AppIcon20x20@2x~ipad.png to device
[        ] [ 49%] Copying /Users/james/Development/test/build/ios/iphoneos/Runner.app/Info.plist to device
[        ] [ 49%] Copying /Users/james/Development/test/build/ios/iphoneos/Runner.app/PkgInfo to device
[        ] [ 49%] Copying /Users/james/Development/test/build/ios/iphoneos/Runner.app/AppIcon76x76~ipad.png to device
[  +91 ms] [ 52%] CreatingStagingDirectory
[        ] [ 57%] ExtractingPackage
[        ] [ 60%] InspectingPackage
[  +25 ms] [ 60%] TakingInstallLock
[  +22 ms] [ 65%] PreflightingApplication
[  +36 ms] [ 65%] InstallingEmbeddedProfile
[  +61 ms] [ 70%] VerifyingApplication
[ +133 ms] [ 75%] CreatingContainer
[   +4 ms] [ 80%] InstallingApplication
[   +9 ms] [ 85%] PostflightingApplication
[  +12 ms] [ 90%] SandboxingApplication
[  +15 ms] [ 95%] GeneratingApplicationMap
[ +242 ms] [100%] Installed package build/ios/iphoneos/Runner.app
[  +80 ms] ------ Debug phase ------
[        ] Starting debug of 00008110-000A58163E98801E (J310AP, J310AP, uknownos, unkarch) a.k.a. 'iPad mini' connected through USB...
[  +79 ms] [  0%] Looking up developer disk image
[   +6 ms] [ 95%] Developer disk image mounted successfully
[+3748 ms] [100%] Connecting to remote debug server
[        ] -------------------------
[ +838 ms] (lldb) command source -s 0 '/tmp/BF633B82-A2C6-4928-830F-2D65CBFA23BA/fruitstrap-lldb-prep-cmds-00008110_000A58163E98801E'
[        ] Executing commands in '/tmp/BF633B82-A2C6-4928-830F-2D65CBFA23BA/fruitstrap-lldb-prep-cmds-00008110_000A58163E98801E'.
[        ] (lldb)     platform select remote-ios --sysroot '/Users/james/Library/Developer/Xcode/iOS DeviceSupport/15.0
(19A5340a)/Symbols'
[        ]   Platform: remote-ios
[        ]  Connected: no
[        ]   SDK Path: "/Users/james/Library/Developer/Xcode/iOS DeviceSupport/15.0 (19A5340a)/Symbols"
[        ] (lldb)     target create "/Users/james/Development/test/build/ios/iphoneos/Runner.app"
[ +548 ms] Current executable set to '/Users/james/Development/test/build/ios/iphoneos/Runner.app' (arm64).
[        ] (lldb)     script
fruitstrap_device_app="/private/var/containers/Bundle/Application/520B3396-B7E8-4C6F-9815-EA151411477D/Runner.app"
[ +371 ms] (lldb)     script fruitstrap_connect_url="connect://127.0.0.1:51513"
[        ] (lldb)     script fruitstrap_output_path=""
[        ] (lldb)     script fruitstrap_error_path=""
[        ] (lldb)     target modules search-paths add /usr "/Users/james/Library/Developer/Xcode/iOS DeviceSupport/15.0
(19A5340a)/Symbols/usr" /System "/Users/james/Library/Developer/Xcode/iOS DeviceSupport/15.0 (19A5340a)/Symbols/System"
"/private/var/containers/Bundle/Application/520B3396-B7E8-4C6F-9815-EA151411477D" "/Users/james/Development/test/build/ios/iphoneos"
"/var/containers/Bundle/Application/520B3396-B7E8-4C6F-9815-EA151411477D" "/Users/james/Development/test/build/ios/iphoneos" /Developer
"/Users/james/Library/Developer/Xcode/iOS DeviceSupport/15.0 (19A5340a)/Symbols/Developer"
[   +5 ms] (lldb)     command script import "/tmp/BF633B82-A2C6-4928-830F-2D65CBFA23BA/fruitstrap_00008110_000A58163E98801E.py"
[   +3 ms] (lldb)     command script add -f fruitstrap_00008110_000A58163E98801E.connect_command connect
[        ] (lldb)     command script add -s asynchronous -f fruitstrap_00008110_000A58163E98801E.run_command run
[        ] (lldb)     command script add -s asynchronous -f fruitstrap_00008110_000A58163E98801E.autoexit_command autoexit
[        ] (lldb)     command script add -s asynchronous -f fruitstrap_00008110_000A58163E98801E.safequit_command safequit
[        ] (lldb)     connect
[  +29 ms] (lldb)     run
[ +409 ms] success
[        ] Application launched on the device. Waiting for observatory url.
[+30004 ms] iOS Observatory not discovered after 30 seconds. This is taking much longer than expected...
[+12282 ms] (lldb) Process 368 exited with status = -1 (0xffffffff) lost connection
[   +2 ms] ios-deploy exited with code 0
[   +6 ms] Installing and launching... (completed in 55.1s)
[        ] Error launching application on iPad mini.
[   +2 ms] "flutter run" took 71,373ms.
[   +3 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:669:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1125:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:92:3)
           <asynchronous suspension>
           
           
[   +5 ms] ensureAnalyticsSent: 3ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1

```

```

[✓] Flutter (Channel stable, 2.5.1, on macOS 11.5.2 20G95 darwin-x64, locale en-US)
    • Flutter version 2.5.1 at /Users/james/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffb2ecea52 (7 days ago), 2021-09-17 15:26:33 -0400
    • Engine revision b3af521a05
    • Dart version 2.14.2

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/james/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.0, Build version 13A233
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.60.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (3 available)
    • iPad mini (mobile) • 00008110-000A58163E98801E • ios            • iOS 15.0 19A342
    • macOS (desktop)    • macos                     • darwin-x64     • macOS 11.5.2 20G95 darwin-x64
    • Chrome (web)       • chrome                    • web-javascript • Google Chrome 93.0.4577.82

! Doctor found issues in 1 category.
```

</details>

**Comment by TahaTesser** [comment] 2021-09-27 12:36
Hi @stx 
Is this a new iPad mini 2021? Can you please try running the app from Xcode? 
Thank you

**Comment by stx** [comment] 2021-09-27 18:04
@TahaTesser Yep, the new one. Xcode works.

**Comment by jmagman** [comment] 2021-09-28 17:05
ios-deploy added these devices in https://github.com/ios-control/ios-deploy/commit/089734fb5f1ccb2d273ba7880525e6dd9c7ad8dd.

**Comment by jmagman** [comment] 2021-09-28 20:43
Hm I'm actually not able to reproduce this on an iPhone 13 mini, which also isn't added.

What's the device showing while the `Application launched on the device. Waiting for observatory url.` message is showing? Is the app loaded, is it a white screen, etc?

**Comment by danagbemava-nc** [comment] 2021-11-17 12:26
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by danagbemava-nc** 2021-11-17 12:26 UTC
Labels: e: device-specific, platform-ios, waiting for customer response, tool, a: tablet, passed first triage, P3
