### ISSUE TITLE
[tool_crash] String: <57 characters>

### ISSUE THREAD

**Issue by yaowei103** [flutter/flutter#132379] opened 2023-08-11 09:03 UTC
## Command
```
flutter --no-color run --machine --device-id=3QV8WQA7UA --start-paused --profile --disable-dds --dart-define=flutter.inspector.structuredErrors=true lib\main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
String: <57 characters>
```

```
```
[✓] Flutter (Channel stable, 3.10.4, on Microsoft Windows [版本 10.0.17763.4645], locale zh-CN)
    • Flutter version 3.10.4 on channel stable at D:\programs\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 682aa387cf (9 weeks ago), 2023-06-05 18:04:56 -0500
    • Engine revision 2a3401c9bb
    • Dart version 3.0.3
    • DevTools version 2.23.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at C:\Users\ActionPower\AppData\Local\Android\sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio 生成工具 2019 16.11.26)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
    • Visual Studio 生成工具 2019 version 16.11.33529.622
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 2022.2)
    • Android Studio at D:\programs\androidStudio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)

[✓] Connected device (4 available)
    • DMG12800T070 33WTC (mobile) • 3QV8WQA7UA    • android-arm    • Android 8.1.0 (API 27)
    • sdk gphone x86 64 (mobile)  • emulator-5554 • android-x64    • Android 13 (API 33) (emulator)
    • Windows (desktop)           • windows       • windows-x64    • Microsoft Windows [版本 10.0.17763.4645]
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 115.0.5790.171

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 4d9e56e694b656610ab87fcf2efbcd226e0ed8cf
### Plugins
disk_space-0.2.1
flutter_isolate-2.0.4
flutter_native_splash-2.3.1
flutter_udisk_plugin-0.0.1
leak_detector-1.0.1+4
path_provider-2.0.15
path_provider_android-2.0.27
path_provider_foundation-2.2.3
path_provider_linux-2.1.11
path_provider_windows-2.1.7
permission_handler-10.4.0
permission_handler_android-10.3.0
permission_handler_apple-9.1.1
permission_handler_windows-0.1.3
screen_brightness-0.2.2
screen_brightness_android-0.1.0+2
screen_brightness_ios-0.1.0
screen_brightness_macos-0.1.0+1
screen_brightness_windows-0.1.1
shared_preferences-2.1.2
shared_preferences_android-2.2.0
shared_preferences_foundation-2.3.0
shared_preferences_linux-2.3.0
shared_preferences_web-2.2.0
shared_preferences_windows-2.3.0
sqflite-2.2.8+4
url_launcher-6.1.11
url_launcher_android-6.0.36
url_launcher_ios-6.1.4
url_launcher_linux-3.0.5
url_launcher_macos-3.0.5
url_launcher_web-2.0.17
url_launcher_windows-3.0.6

**Comment by danagbemava-nc** [comment] 2023-08-11 09:31
Closing this as a duplicate of https://github.com/flutter/flutter/issues/108812

**Closed by danagbemava-nc** 2023-08-11 09:31 UTC
Labels: in triage
