### ISSUE TITLE
[local_auth][ios] NSInternalInconsistencyException

### ISSUE THREAD

**Issue by severance88** [flutter/flutter#57129] opened 2020-05-13 16:32 UTC
```
2020-05-13 16:55:50.635621+0100 Runner[658:102822] [Animation] +[UIView setAnimationsEnabled:] being called from a background thread. Performing any operation from a background thread on UIView or a subclass is not supported and may result in unexpected and insidious behavior. trace=(
	0   UIKitCore                           0x000000019c19dfa4 A96D079A-405F-3E74-8B4F-39ADE0CC4FE3 + 15241124
	1   libdispatch.dylib                   0x0000000102b26bd8 _dispatch_client_callout + 16
	2   libdispatch.dylib                   0x0000000102b284c8 _dispatch_once_callout + 84
	3   UIKitCore                           0x000000019c19df08 A96D079A-405F-3E74-8B4F-39ADE0CC4FE3 + 15240968
	4   UIKitCore                           0x000000019c19e090 A96D079A-405F-3E74-8B4F-39ADE0CC4FE3 + 15241360
	5   UIKitCore                           0x000000019c0c4934 A96D079A-405F-3E74-8B4F-39ADE0CC4FE3 + 14350644
	6   UIKitCore                           0x000000019c0c4888 A96D079A-405F-3E74-8B4F-39ADE0CC4FE3 + 14350472
	7   UIKitCore                           0x000000019b34af0c A96D079A-405F-3E74-8B4F-39ADE0CC4FE3 + 220940
	8   UIKitCore                           0x000000019b34a36c A96D079A-405F-3E74-8B4F-39ADE0CC4FE3 + 217964
	9   UIKitCore                           0x000000019b339224 A96D079A-405F-3E74-8B4F-39ADE0CC4FE3 + 148004
	10  UIKitCore                           0x000000019b33690c A96D079A-405F-3E74-8B4F-39ADE0CC4FE3 + 137484
	11  UIKitCore                           0x000000019b3369e0 A96D079A-405F-3E74-8B4F-39ADE0CC4FE3 + 137696
	12  UIKitCore                           0x000000019b3605b8 A96D079A-405F-3E74-8B4F-39ADE0CC4FE3 + 308664
	13  UIKitCore                           0x000000019b37ffec A96D079A-405F-3E74-8B4F-39ADE0CC4FE3 + 438252
	14  UIKitCore                           0x000000019b37f208 A96D079A-405F-3E74-8B4F-39ADE0CC4FE3 + 434696
	15  UIKitCore                           0x000000019b37f194 A96D079A-405F-3E74-8B4F-39ADE0CC4FE3 + 434580
	16  UIKitCore                           0x000000019b3691f4 A96D079A-405F-3E74-8B4F-39ADE0CC4FE3 + 344564
	17  UIKitCore                           0x000000019b6fd600 A96D079A-405F-3E74-8B4F-39ADE0CC4FE3 + 4097536
	18  UIKitCore                           0x000000019b6fdd04 A96D079A-405F-3E74-8B4F-39ADE0CC4FE3 + 4099332
	19  UIKitCore                           0x000000019b713454 A96D079A-405F-3E74-8B4F-39ADE0CC4FE3 + 4187220
	20  UIKitCore                           0x000000019b70c260 A96D079A-405F-3E74-8B4F-39ADE0CC4FE3 + 4158048
	21  UIKitCore                           0x000000019b70dc74 A96D079A-405F-3E74-8B4F-39ADE0CC4FE3 + 4164724
	22  UIKitCore                           0x000000019b710150 A96D079A-405F-3E74-8B4F-39ADE0CC4FE3 + 4174160
	23  UIKitCore                           0x000000019b71064c A96D079A-405F-3E74-8B4F-39ADE0CC4FE3 + 4175436
	24  UIKitCore                           0x000000019b7100a0 A96D079A-405F-3E74-8B4F-39ADE0CC4FE3 + 4173984
	25  UIKitCore                           0x000000019b710308 A96D079A-405F-3E74-8B4F-39ADE0CC4FE3 + 4174600
	26  Runner                              0x0000000102a6aff4 -[FLTLocalAuthPlugin alertMessage:firstButton:flutterResult:additionalButton:] + 788
	27  Runner                              0x0000000102a6bee8 -[FLTLocalAuthPlugin handleErrors:flutterArguments:withFlutterResult:] + 804
	28  Runner                              0x0000000102a6b960 __67-[FLTLocalAuthPlugin authenticateWithBiometrics:withFlutterResult:]_block_invoke + 272
	29  LocalAuthentication                 0x00000001b0539238 7C8C06D3-220B-324B-9473-FCFBB9F62338 + 45624
	30  LocalAuthentication                 0x00000001b0538878 7C8C06D3-220B-324B-9473-FCFBB9F62338 + 43128
	31  LocalAuthentication                 0x00000001b0532ddc 7C8C06D3-220B-324B-9473-FCFBB9F62338 + 19932
	32  libdispatch.dylib                   0x0000000102b257fc _dispatch_call_block_and_release + 24
	33  libdispatch.dylib                   0x0000000102b26bd8 _dispatch_client_callout + 16
	34  libdispatch.dylib                   0x0000000102b292d4 _dispatch_queue_override_invoke + 872
	35  libdispatch.dylib                   0x0000000102b38160 _dispatch_root_queue_drain + 376
	36  libdispatch.dylib                   0x0000000102b38a88 _dispatch_worker_thread2 + 156
	37  libsystem_pthread.dylib             0x00000001979caf48 _pthread_wqthread + 212
	38  libsystem_pthread.dylib             0x00000001979cdad4 start_wqthread + 8
)
2020-05-13 16:55:50.648373+0100 Runner[658:102822] [Assert] Unsupported use of UIKit view-customization API off the main thread. -setHasDimmingView: sent to <_UIAlertControllerView: 0x15de7d410; frame = (0 0; 375 667); layer = <CALayer: 0x2818dbae0>>
2020-05-13 16:55:50.648631+0100 Runner[658:102822] [Assert] Unsupported use of UIKit view-customization API off the main thread. -setShouldHaveBackdropView: sent to <_UIAlertControllerView: 0x15de7d410; frame = (0 0; 375 667); layer = <CALayer: 0x2818dbae0>>
2020-05-13 16:55:50.648712+0100 Runner[658:102822] [Assert] Cannot be called with asCopy = NO on non-main thread.
2020-05-13 16:55:50.648829+0100 Runner[658:102822] [Assert] Unsupported use of UIKit view-customization API off the main thread. -setAlignsToKeyboard: sent to <_UIAlertControllerView: 0x15de7d410; frame = (0 0; 375 667); layer = <CALayer: 0x2818dbae0>>
2020-05-13 16:55:50.656170+0100 Runner[658:102822] This application is modifying the autolayout engine from a background thread after the engine was accessed from the main thread. This can lead to engine corruption and weird crashes.
 Stack:(
	0   Foundation                          0x0000000198183e8c 3C682044-3249-3938-8111-F2F12D066D2B + 2252428
	1   Foundation                          0x0000000197f8506c 3C682044-3249-3938-8111-F2F12D066D2B + 159852
	2   UIKitCore                           0x000000019c0d71e0 A96D079A-405F-3E74-8B4F-39ADE0CC4FE3 + 14426592
	3   UIKitCore                           0x000000019c0d8594 A96D079A-405F-3E74-8B4F-39ADE0CC4FE3 + 14431636
	4   UIKitCore                           0x000000019b386f80 A96D079A-405F-3E74-8B4F-39ADE0CC4FE3 + 466816
	5   UIKitCore                           0x000000019b3827ec A96D079A-405F-3E74-8B4F-39ADE0CC4FE3 + 448492
	6   UIKitCore                           0x000000019b382a58 A96D079A-405F-3E74-8B4F-39ADE0CC4FE3 + 449112
	7   UIKitCore                           0x000000019b382d78 A96D079A-405F-3E74-8B4F-39ADE0CC4FE3 + 449912
	8   UIKitCore                           0x000000019b387800 A96D079A-405F-3E74-8B4F-39ADE0CC4FE3 + 468992
	9   UIKitCore                           0x000000019b38764c A96D079A-405F-3E74-8B4F-39ADE0CC4FE3 + 468556
	10  UIKitCore                           0x000000019b369328 A96D079A-405F-3E74-8B4F-39ADE0CC4FE3 + 344872
	11  UIKitCore                           0x000000019b6fd600 A96D079A-405F-3E74-8B4F-39ADE0CC4FE3 + 4097536
	12  UIKitCore                           0x000000019b6fdd04 A96D079A-405F-3E74-8B4F-39ADE0CC4FE3 + 4099332
	13  UIKitCore                           0x000000019b713454 A96D079A-405F-3E74-8B4F-39ADE0CC4FE3 + 4187220
	14  UIKitCore                           0x000000019b70c260 A96D079A-405F-3E74-8B4F-39ADE0CC4FE3 + 4158048
	15  UIKitCore                           0x000000019b70dc74 A96D079A-405F-3E74-8B4F-39ADE0CC4FE3 + 4164724
	16  UIKitCore                           0x000000019b710150 A96D079A-405F-3E74-8B4F-39ADE0CC4FE3 + 4174160
	17  UIKitCore                           0x000000019b71064c A96D079A-405F-3E74-8B4F-39ADE0CC4FE3 + 4175436
	18  UIKitCore                           0x000000019b7100a0 A96D079A-405F-3E74-8B4F-39ADE0CC4FE3 + 4173984
	19  UIKitCore                           0x000000019b710308 A96D079A-405F-3E74-8B4F-39ADE0CC4FE3 + 4174600
	20  Runner                              0x0000000102a6aff4 -[FLTLocalAuthPlugin alertMessage:firstButton:flutterResult:additionalButton:] + 788
	21  Runner                              0x0000000102a6bee8 -[FLTLocalAuthPlugin handleErrors:flutterArguments:withFlutterResult:] + 804
	22  Runner                              0x0000000102a6b960 __67-[FLTLocalAuthPlugin authenticateWithBiometrics:withFlutterResult:]_block_invoke + 272
	23  LocalAuthentication                 0x00000001b0539238 7C8C06D3-220B-324B-9473-FCFBB9F62338 + 45624
	24  LocalAuthentication                 0x00000001b0538878 7C8C06D3-220B-324B-9473-FCFBB9F62338 + 43128
	25  LocalAuthentication                 0x00000001b0532ddc 7C8C06D3-220B-324B-9473-FCFBB9F62338 + 19932
	26  libdispatch.dylib                   0x0000000102b257fc _dispatch_call_block_and_release + 24
	27  libdispatch.dylib                   0x0000000102b26bd8 _dispatch_client_callout + 16
	28  libdispatch.dylib                   0x0000000102b292d4 _dispatch_queue_override_invoke + 872
	29  libdispatch.dylib                   0x0000000102b38160 _dispatch_root_queue_drain + 376
	30  libdispatch.dylib                   0x0000000102b38a88 _dispatch_worker_thread2 + 156
	31  libsystem_pthread.dylib             0x00000001979caf48 _pthread_wqthread + 212
	32  libsystem_pthread.dylib             0x00000001979cdad4 start_wqthread + 8
)
2020-05-13 16:55:50.659340+0100 Runner[658:102822] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Modifications to the layout engine must not be performed from a background thread after it has been accessed from the main thread.'
*** First throw call stack:
(0x197cad80c 0x1979d5fa4 0x198183f1c 0x197f8506c 0x19c0d71e0 0x19c0d8594 0x19b386f80 0x19b3827ec 0x19b382a58 0x19b382d78 0x19b387800 0x19b38764c 0x19b369328 0x19b6fd600 0x19b6fdd04 0x19b713454 0x19b70c260 0x19b70dc74 0x19b710150 0x19b71064c 0x19b7100a0 0x19b710308 0x102a6aff4 0x102a6bee8 0x102a6b960 0x1b0539238 0x1b0538878 0x1b0532ddc 0x102b257fc 0x102b26bd8 0x102b292d4 0x102b38160 0x102b38a88 0x1979caf48 0x1979cdad4)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

This error shows and the app crashes after failing to authenticate with fingerprint 5 times.

Fail 3 times and the pop-up goes away. Bring the pop-up back again, fail times 2 and the app crashes.

`local_auth v0.6.2+2`

```
[✓] Flutter (Channel stable, v1.17.0, on Mac OS X 10.15.4 19E287, locale en-PT)
    • Flutter version 1.17.0 at /Users/simaogarcia/Library/flutter
    • Framework revision e6b34c2b5c (11 days ago), 2020-05-02 11:39:18 -0700
    • Engine revision 540786dd51
    • Dart version 2.8.1

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/simaogarcia/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.9.0

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.45.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.1
[✓] Connected device (1 available)
    • Inspire Iphone • 3b70acd7f8c351d668e8624334a222e7ff62b05c • ios • iOS 13.2

• No issues found!
```

**Comment by TahaTesser** [comment] 2020-05-14 09:35
Hi @severance88 
can you please provide your `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by severance88** [comment] 2020-05-14 10:33
Hi @TahaTesser 
Im having trouble getting the `flutter run --verbose`
It's so much output, that some of it gets cut and at the very end I get this

```
Application launched on the device. Waiting for observatory port.
[   +8 ms] Attempting to forward device port 55246 to host port 1024
[        ] executing: /Users/simaogarcia/Library/flutter/bin/cache/artifacts/usbmuxd/iproxy 1024 55246 3b70acd7f8c351d668e8624334a222e7ff62b05c
[  +15 ms] Attempting to forward device port 55246 to host port 1025
[        ] executing: /Users/simaogarcia/Library/flutter/bin/cache/artifacts/usbmuxd/iproxy 1025 55246 3b70acd7f8c351d668e8624334a222e7ff62b05c
[+1008 ms] Forwarded port ForwardedPort HOST:1025 to DEVICE:55246
[  +17 ms] HttpException: Connection closed before full header was received, uri = http://localhost:1025/ws
```

Regarding the minimal code sample, you can reproduce the issue in the example project as is.
Thanks

**Comment by TahaTesser** [comment] 2020-05-15 08:17
Hi @severance88 
Not able to reproduce this issue using example using iOS 13.4.1 

Can you please provide complete logs using official example
You can get full logs in https://gist.github.com/

<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel stable, v1.17.1, on Mac OS X 10.15.4 19E287, locale en-GB)
    • Flutter version 1.17.1 at /Users/tahatesser/Code/flutter_stable
    • Framework revision f7a6a7906b (2 days ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/tahatesser/Code/SDK
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.1

[✓] Connected device (1 available)
    • iPhone 8 • 7A1DEA5A-1E0D-4355-BE91-38ADC811AF4E • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-13-4 (simulator)

• No issues found!

``` 

</details> 

Can you please name the device you noticed the issue?
Thank you

**Comment by severance88** [comment] 2020-05-15 08:44
Hi @TahaTesser 

Below are the logs. All taken using the official example. iPhone 6s running iOS 13.2

flutter doctor -v
```
[✓] Flutter (Channel stable, v1.17.0, on Mac OS X 10.15.4 19E287, locale en-PT)
    • Flutter version 1.17.0 at /Users/simaogarcia/Library/flutter
    • Framework revision e6b34c2b5c (13 days ago), 2020-05-02 11:39:18 -0700
    • Engine revision 540786dd51
    • Dart version 2.8.1
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/simaogarcia/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.9.0
[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
[✓] VS Code (version 1.45.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.1
[✓] Connected device (1 available)
    • Inspire Iphone • 3b70acd7f8c351d668e8624334a222e7ff62b05c • ios • iOS 13.2
• No issues found!
```
[flutter run --verbose](https://gist.github.com/severance88/e287f710682114b7705a1fcd989bb98c)

**Comment by TahaTesser** [comment] 2020-05-15 09:00
Hi @severance88 
Thank you for providing logs
Probably not reproducible on simulator touch id
Closing as duplicate of https://github.com/flutter/flutter/issues/47465

**Closed by TahaTesser** 2020-05-15 09:00 UTC
Labels: in triage

**Comment by severance88** [comment] 2020-05-15 09:47
Hi @TahaTesser 

Should this issue be closed? I know it's a duplicate, but the other issue is waiting for customer response for almost 2 months.

I'm here, and I'm willing to follow up.
Thanks

**Comment by TahaTesser** [comment] 2020-05-15 13:44
@severance88 
Mentioned issue is already 
We don't need to have duplicate tracking 
Removing waiting to other, didn't notice it
Thank you
