### ISSUE TITLE
MissingPluginException(No implementation found for method init on channel plugins.flutter.io/google_sign_in)

### ISSUE THREAD

**Issue by vskr** [flutter/flutter#14096] opened 2018-01-13 23:13 UTC
Using Flutter's google sign_in

But seeing the following message when I use this statement to sign in a user

_googleSignIn.signIn();

E/flutter ( 6491): MissingPluginException(No implementation found for method init on channel plugins.flutter.io/google_sign_in)

Any help would be appreciated.

**Comment by vskr** [comment] 2018-01-17 05:37
Bump. 

Could it be because of the error in plugin (unlikely cos other would have noticed it too)

Or is it a user error on my part on how to use the plugin?

**Comment by mravn-google** [comment] 2018-01-17 09:16
Duplicate of https://github.com/flutter/flutter/issues/14137

**Closed by mravn-google** 2018-01-17 09:16 UTC

**Comment by pulstar** [comment] 2020-09-17 18:48
Check if you are using any of these packages and remove them:

```
flutter_facebook_auth
flutter_twitter_login
github_sign_in
```

**Comment by pulstar** [comment] 2020-09-17 18:59
Check if you are using any of these packages and remove it:

```
flutter_facebook_auth
flutter_twitter_login
github_sign_in
```
