### ISSUE TITLE
Tree closed on iOS symbol doctor failure

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#119213] opened 2023-01-26 04:21 UTC
https://ci.chromium.org/p/flutter/builders/prod/Mac_ios%20macos_chrome_dev_mode

**Comment by zanderso** [comment] 2023-01-26 15:57
This is widespread and affecting every test for the past ~day or so.

<img width="1281" alt="Screenshot 2023-01-26 at 7 56 43 AM" src="https://user-images.githubusercontent.com/6343103/214884317-6929008c-88a4-4e78-a8b7-fb49317f595b.png">

**Comment by zanderso** [comment] 2023-01-26 15:58
cc @yusuf-goog @jmagman @christopherfujino

**Comment by ricardoamador** [comment] 2023-01-26 16:24
@zanderso we have a tracking bug for this already in the infra queue.
https://github.com/flutter/flutter/issues/118924
I will look into this now.

**Comment by ricardoamador** [comment] 2023-01-26 16:26
Closing this as duplicate of the linked issue in my previous comment and elevating the priority of that issue.

**Comment by yusuf-goog** [comment] 2023-01-26 17:53
https://github.com/flutter/cocoon/pull/2421 should fix this.

**Closed** 2023-01-26 18:32 UTC
Labels: team: infra, P0
