### ISSUE TITLE
FlutterFragment could not be hidden on some Android versions

### ISSUE THREAD

**Issue by CruorVult** [flutter/flutter#59968] opened 2020-06-22 08:54 UTC
I need to hide and show fragment without removing it. I have used method `hide` of `FragmentTransaction`
```
FragmentManager fragmentManager = getSupportFragmentManager();
FlutterFragment flutterFragment = (FlutterFragment) fragmentManager.findFragmentByTag(TAG_FLUTTER_FRAGMENT);
if (flutterFragment != null) {
	fragmentManager
			.beginTransaction()
			.hide(flutterFragment)
			.commitNow();
}
```
It works on Android 10, but does not work on 8 and 9.

Code to add fragment:

```
FragmentManager fragmentManager = getSupportFragmentManager();
FlutterFragment flutterFragment = (FlutterFragment) fragmentManager
		.findFragmentByTag(TAG_FLUTTER_FRAGMENT);
if (flutterFragment == null) {
	flutterFragment = FlutterFragment.withCachedEngine(FLUTTER_ENGINE_ID).build();
	FragmentTransaction transaction = fragmentManager.beginTransaction();
	transaction.add(
			R.id.flutter_container,
			flutterFragment,
			TAG_FLUTTER_FRAGMENT
	).commitNow();
}
```
Full example in attach
[flutter_fragment.zip](https://github.com/flutter/flutter/files/4812236/flutter_fragment.zip)

**Comment by TahaTesser** [comment] 2020-06-22 14:27
Hi @CruorVult 
Tried your code sample on latest `master` channel, it hides the flutter fragment on Android 10 but not Android 8 

### Android 8 not working
![ezgif com-resize (2)](https://user-images.githubusercontent.com/48603081/85299069-7357a400-b4c2-11ea-8c73-a417732bb63a.gif)


### Android 10 not working
![ezgif com-resize (1)](https://user-images.githubusercontent.com/48603081/85299063-72bf0d80-b4c2-11ea-8fee-fbdbce32c262.gif)


<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel master, 1.20.0-1.0.pre.132, on Mac OS X 10.15.5 19F101,
    locale en-GB)
    • Flutter version 1.20.0-1.0.pre.132 at
      /Users/tahatesser/Code/flutter_master
    • Framework revision 5995661777 (3 days ago), 2020-06-19 16:15:58 -0700
    • Engine revision 676cd566f7
    • Dart version 2.9.0 (build 2.9.0-17.0.dev 7e72c9ae7e)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (6 available)
    • SM M305F                  • 32003c30dc19668f          • android-arm64  •
      Android 10 (API 29)
    • Android SDK built for x86 • emulator-5554             • android-x86    •
      Android 8.0.0 (API 26) (emulator)
    • Taha’s iPhone             • 00008020-001059882212002E • ios            •
      iOS 13.5.1
    • macOS desktop             • macos                     • darwin-x64     •
      Mac OS X 10.15.5 19F101
    • Web Server                • web-server                • web-javascript •
      Flutter Tools
    • Chrome                    • chrome                    • web-javascript •
      Google Chrome 83.0.4103.106

• No issues found!
``` 

</details>

**Comment by panda912** [comment] 2020-07-04 09:39
Hi, I'm facing FlutterFragment could not be hidden on Android7.1.2

**Comment by zhaiyunbin** [comment] 2020-08-07 08:59
same isue

**Comment by panda912** [comment] 2020-08-17 02:19
Hi, I hava a solution, but I don't know if there will be unexpected side effects. extends FlutterFragment and override `FlutterFragment#onFlutterSurfaceViewCreated(FlutterSurfaceView)` to get the `flutterSurfaceView` instance,  and set `flutterSurfaceView`'s visibility on `Fragment#onHiddenChanged(boolean)`.

```kotlin
class MyFlutterFragment : FlutterFragment() {

    private var flutterSurfaceView: FlutterSurfaceView? = null

    override fun onFlutterSurfaceViewCreated(flutterSurfaceView: FlutterSurfaceView) {
        super.onFlutterSurfaceViewCreated(flutterSurfaceView)
        this.flutterSurfaceView = flutterSurfaceView
    }

    override fun onHiddenChanged(hidden: Boolean) {
        super.onHiddenChanged(hidden)
        flutterSurfaceView?.visibility = if (hidden) View.GONE else View.VISIBLE
    }
}
```

**Comment by wangyujian** [comment] 2021-06-17 20:12
> Hi, I hava a solution, but I don't know if there will be unexpected side effects. extends FlutterFragment and override `FlutterFragment#onFlutterSurfaceViewCreated(FlutterSurfaceView)` to get the `flutterSurfaceView` instance, and set `flutterSurfaceView`'s visibility on `Fragment#onHiddenChanged(boolean)`.
> 
> ```kotlin
> class MyFlutterFragment : FlutterFragment() {
> 
>     private var flutterSurfaceView: FlutterSurfaceView? = null
> 
>     override fun onFlutterSurfaceViewCreated(flutterSurfaceView: FlutterSurfaceView) {
>         super.onFlutterSurfaceViewCreated(flutterSurfaceView)
>         this.flutterSurfaceView = flutterSurfaceView
>     }
> 
>     override fun onHiddenChanged(hidden: Boolean) {
>         super.onHiddenChanged(hidden)
>         flutterSurfaceView?.visibility = if (hidden) View.GONE else View.VISIBLE
>     }
> }
> ```

Thank you~

**Comment by chdo002** [comment] 2022-08-24 07:01
this problem still exits in flutter 3.0.5

**Comment by chdo002** [comment] 2022-08-24 07:54
> this problem still exits in flutter 3.0.5
I post a question
https://stackoverflow.com/questions/73454694/flutter-reuse-fragment-float-above-other-views

**Comment by huycozy** [comment] 2023-04-21 10:59
This issue seems to have been fixed on the latest stable channel as I cannot reproduce it there on some below Android versions. 

| Android 8.0 | Android 9.0 |
| --------------- | --------------- |
<video src="https://user-images.githubusercontent.com/104349824/233618502-d727b4b7-9e4b-4f95-90e9-fd45c1a0233a.mov"/> | <video src="https://user-images.githubusercontent.com/104349824/233619351-f1b80e7f-4b56-400e-a1e5-14326a7ea761.mov"/>

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.7.12, on macOS 13.0.1 22A400 darwin-x64, locale en-VN)
    • Flutter version 3.7.12 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4d9e56e694 (2 days ago), 2023-04-17 21:47:46 -0400
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.77.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.62.0

[✓] Connected device (3 available)
    • SM T225 (mobile) • R9JT3004VRJ • android-arm64  • Android 13 (API 33)
    • macOS (desktop)  • macos       • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)     • chrome      • web-javascript • Google Chrome 112.0.5615.137

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

```bash
[!] Flutter (Channel master, 3.10.0-10.0.pre.38, on macOS 13.0.1 22A400 darwin-x64, locale en-VN)
    • Flutter version 3.10.0-10.0.pre.38 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7aa01f53f8 (38 minutes ago), 2023-04-20 22:31:11 -0400
    • Engine revision 122c3b3820
    • Dart version 3.1.0 (build 3.1.0-26.0.dev)
    • DevTools version 2.23.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio Flamingo.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio Flamingo.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.77.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.62.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 112.0.5615.137

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>

I will close this issue since it has already been fixed on the stable channel. If you still experience this issue on the stable channel, kindly leave a comment below and I will reopen this. Thank you!

**Closed by huycozy** 2023-04-21 10:59 UTC
Labels: platform-android, engine, a: existing-apps, e: OS Version specific, has reproducible steps, P4, found in release: 1.20
