### ISSUE TITLE
iOS Textfield caret handles do not appear when text is selected in latest beta release (1.4.9)

### ISSUE THREAD

**Issue by dannyvalentesonos** [flutter/flutter#31287] opened 2019-04-18 21:58 UTC
The latest Beta version (1.4.9-hotfix.1) has an issue where the iOS TextField's caret handles do not appear when text is selected.

This can be reproduced with a simple app that just has a TextField widget.

This is because the FadeTransition widgets around the handles never have the controllers run forward, because of some check failing to determine that the position is in the selection.

**Comment by dannyvalentesonos** [comment] 2019-04-18 21:59
<img width="266" alt="sample_app_missing_handles" src="https://user-images.githubusercontent.com/40898687/56393897-af7adf00-6203-11e9-9c6b-51db302b7a22.png">
![sample_app_missing_handles_inspector](https://user-images.githubusercontent.com/40898687/56393907-b4d82980-6203-11e9-9210-a6c39191fadd.png)

**Comment by dannyvalentesonos** [comment] 2019-04-18 22:00
![sample_app_missing_handles_inspector](https://user-images.githubusercontent.com/40898687/56393949-d20cf800-6203-11e9-9108-6cfeceef6968.png)

**Comment by justinmc** [comment] 2019-04-19 17:50
Thanks for catching this!  I was able to reproduce it too.  I think you're right about the FadeTransition being the culprit.  I'm digging into this.

**Comment by xster** [comment] 2019-04-23 21:12
Adding today tag since we shouldn't release with this issue.

**Comment by xster** [comment] 2019-04-23 21:44
@justinmc can you reference the commit that caused it (you seem to allude to one in #31332) for breadcrumb following posterity?

**Comment by justinmc** [comment] 2019-04-23 22:08
The commit is https://github.com/flutter/flutter/commit/88a477cacead093d18be0dcb4ea72e9976aeb0a7 from when https://github.com/flutter/flutter/pull/24476 was merged.

**Comment by Hixie** [comment] 2019-04-24 00:11
We've already released many dev releases and one beta with this, so it's probably fine to remove the TODAY label.

**Comment by justinmc** [comment] 2019-04-24 15:35
I removed the Today label, but I'm working through the code reviews on the PR and should land it soon.

**Comment by xster** [comment] 2019-04-24 18:25
What are the implications? Are we shipping 1.5.4 with this bug?

**Comment by justinmc** [comment] 2019-04-24 22:21
For the record it seems like it was decided that 1.5.4 would be hot fixed with this after the fact.

**Comment by justinmc** [comment] 2019-04-25 20:20
Fixed with https://github.com/flutter/flutter/pull/31332

**Closed by justinmc** 2019-04-25 20:20 UTC
Labels: a: text input, customer: amplify, f: cupertino, severe: regression, waiting for PR to land (fixed)
