### ISSUE TITLE
Gtk theme does not comply with selected one

### ISSUE THREAD

**Issue by MalcolmMielle** [flutter/flutter#82620] opened 2021-05-15 17:35 UTC
On Linux, the gtk theme selected with light or dark is always Adwaitalight or dark, regardless of the actual theme selected (through gnome tweak tools or other). My guess is that this happens because flutter only has access to the default theme included with GTK.

Tested with Yaru, Arc, and Nordic.

**Comment by TahaTesser** [comment] 2021-05-17 10:42
Hi @MalcolmMielle 
This has been recently fixed by https://github.com/flutter/engine/pull/25535

Can you please upgrade to the latest  `master` and try again
Execute the following commands to upgrade
`flutter channel master`
`flutter upgrade --force`
`flutter doctor -v`

duplicate of https://github.com/flutter/flutter/issues/80199
Thank you

**Comment by MalcolmMielle** [comment] 2021-05-17 11:56
Thanks a lot, I have updated to the lastest master and it's indeed working much better!
One limitation still is that the theme does not follow the current installed theme but instead use Adwaita colors. I'm adding a picture to illustrate the problem (my app is on the left and on the right is gnome tweak tools with the selected theme).
However, it now correctly switches between dark and light theme.

![Screenshot from 2021-05-17 13-43-22](https://user-images.githubusercontent.com/4457840/118483298-22721f00-b716-11eb-9b78-08aa9f2a6692.png)

I'm adding some of my digging here to help if someone tries to fix this.
______

I sadly have no experience using GTK and I can't really put out a fix but, to give an idea for the direction, the theme css has certain values that could be used to create a FlutterTheme:

```
/* GTK NAMED COLORS
   ----------------
   use responsibly! */
/* widget text/foreground color */
@define-color theme_fg_color #a8a8a8;
/* text color for entries, views and content in general */
@define-color theme_text_color #a8a8a8;
/* widget base background color */
@define-color theme_bg_color #171a1f;
/* text widgets and the like base background color */
@define-color theme_base_color #131519;
/* base background color of selections */
@define-color theme_selected_bg_color #9bbfbf;
/* text/foreground color of selections */
@define-color theme_selected_fg_color #000;
/* base background color of disabled widgets */
@define-color insensitive_bg_color #1a1c22;
/* text foreground color of disabled widgets */
@define-color insensitive_fg_color #606163;
/* disabled text widgets and the like base background color */
@define-color insensitive_base_color #131519;
/* widget text/foreground color on backdrop windows */
@define-color theme_unfocused_fg_color #606163;
/* text color for entries, views and content in general on backdrop windows */
@define-color theme_unfocused_text_color #a8a8a8;
/* widget base background color on backdrop windows */
@define-color theme_unfocused_bg_color #171a1f;
/* text widgets and the like base background color on backdrop windows */
@define-color theme_unfocused_base_color #15171c;
/* base background color of selections on backdrop windows */
@define-color theme_unfocused_selected_bg_color #9bbfbf;
/* text/foreground color of selections on backdrop windows */
@define-color theme_unfocused_selected_fg_color #000;
/* widgets main borders color */
@define-color borders #08090b;
/* widgets main borders color on backdrop windows */
@define-color unfocused_borders #0a0b0d;
/* these are pretty self explicative */
@define-color warning_color #aa4b1a;
@define-color error_color #b72f1d;
@define-color success_color #70af5a;
@define-color fg_color #a8a8a8;
@define-color text_color #a8a8a8;
@define-color bg_color #171a1f;
@define-color base_color #131519;
@define-color selected_bg_color #9bbfbf;
@define-color selected_fg_color #000;
@define-color unfocused_fg_color #606163;
@define-color unfocused_text_color #a8a8a8;
@define-color unfocused_bg_color #171a1f;
@define-color unfocused_base_color #15171c;
@define-color unfocused_selected_bg_color #9bbfbf;
@define-color unfocused_selected_fg_color #000;
```

By reading those one and adding theme to a ThemeData structure like 

```
import 'dart:io';
import 'dart:ui';
import 'package:flutter/material.dart';
import 'package:from_css_color/from_css_color.dart';
import 'package:gsettings/gsettings.dart';

class GnomeTheme {
  String contents = "";

  Color? themeBgColor;
  Color? textColor;
  Color? buttonFg;
  Color? themeBaseColor;
  Color? insensitiveBgColor;
  // Border of widgets not text inputs fields
  Color? unfocusedBorder;
  Color? border;
  Color? themeSelectedBG;
  Color? textSelectedFG;

  void loadFromFile() {
    final settings = GSettings(schemaId: 'org.gnome.desktop.interface');
    final theme = settings.stringValue('gtk-theme');
    String fileName = "/usr/share/themes/" + theme + "/gtk-3.0/gtk.css";
    File file = File(fileName);
    if (file.existsSync()) {
      contents = File(fileName).readAsStringSync();
    }
  }

  ThemeData data(context) {
    ThemeData themedata = ThemeData(
        iconTheme: IconThemeData(color: textColor),
        brightness: Brightness.dark,
        canvasColor: themeBgColor,
        textSelectionTheme: TextSelectionThemeData(cursorColor: textColor),
        textButtonTheme: TextButtonThemeData(
            style: TextButton.styleFrom(
                side: BorderSide(
                    color: border != null ? border! : const Color(4278190080)),
                primary: textColor,
                backgroundColor: buttonFg)),
        elevatedButtonTheme: ElevatedButtonThemeData(
            style: ElevatedButton.styleFrom(
                primary: buttonFg, onPrimary: textColor)),
        textTheme: TextTheme(
            bodyText2: TextStyle(color: textColor),
            bodyText1: TextStyle(color: textColor)),
        inputDecorationTheme: InputDecorationTheme(
            isDense: true,
            labelStyle: TextStyle(color: textColor),
            disabledBorder: OutlineInputBorder(
              borderSide: BorderSide(
                  width: 1.0,
                  style: BorderStyle.solid,
                  color: insensitiveBgColor != null
                      ? insensitiveBgColor!
                      : Colors.blue),
            ),
            enabledBorder: OutlineInputBorder(
              borderSide: BorderSide(
                  width: 1.0,
                  style: BorderStyle.solid,
                  color: textColor != null ? textColor! : Colors.blue),
            ),
            focusedBorder: OutlineInputBorder(
              borderSide: BorderSide(
                  width: 2.0,
                  style: BorderStyle.solid,
                  color: textColor != null ? textColor! : Colors.blue),
            )),
        primaryColor: themeBaseColor);
    return themedata.copyWith(
        colorScheme: themedata.colorScheme.copyWith(secondary: textColor));
  }

  /// Get standard gtk color define
  Color? getBaseColor(String colorName) {
    String demand = "(@define-color " + colorName + " )(.*);";
    RegExp exp = new RegExp(demand);

    RegExpMatch? matches = exp.firstMatch(contents);
    String? color = matches?.group(2).toString();
    if (color != null) {
      return fromCssColor(color);
    }
    return null;
  }

  void parse() {
    themeBgColor = getBaseColor("theme_base_color");
    textColor = getBaseColor("theme_text_color");
    buttonFg = getBaseColor("button_fg_color");
    themeBaseColor = getBaseColor("theme_base_color");
    insensitiveBgColor = getBaseColor("insensitive_bg_color");
    unfocusedBorder = getBaseColor("unfocused_borders");
    border = getBaseColor("borders");
    themeSelectedBG = getBaseColor("theme_selected_bg_color");
    textSelectedFG = getBaseColor("theme_selected_fg_color");

    if (buttonFg == null) {
      buttonFg = themeBgColor;
    }
  }
}
```

I'm adding theme.data to the MaterialApp theme, I can get something that looks more like the theme I have 


![Screenshot from 2021-05-17 13-53-38](https://user-images.githubusercontent.com/4457840/118484271-5437b580-b717-11eb-9356-d26cdad36ed2.png)

Wish is closer to the theme I have at the moment.

Maybe this can be generalize in GTK and someone with more experience than me can do it :).

**Comment by TahaTesser** [comment] 2021-05-18 06:47
Hi @MalcolmMielle 
The theme you're referring to on the left (in the Flutter window) is a default dark theme in Flutter, which is the same on all platforms, it has nothing to do with Linux. If you can exactly replicate the adwaita theme, you need to do it in the code itself. 
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-05-18 06:47 UTC
Labels: in triage

**Comment by MalcolmMielle** [comment] 2021-05-18 07:25
Thanks for the clarification. It makes more sense now. 

I believe it makes sense to follow the full gtk theme instead of the default flutter one so that flutter apps do not look out of place in the eco-system. That sounds more like a feature than a bug in the end. If you think it's useful to track it feel free to reopen.

**Comment by TahaTesser** [comment] 2021-05-18 12:54
@MalcolmMielle 
Since Flutter is cross-platform, I don't think it is reasonable to customize the theme just a Linux app to match the native theme, even if it is possible. This would involve reading native theme and updating framework at runtime, which is unreasonable for such for simply for asthetic reason while you can fancy your app with greater control from app theme. 

If you disagree, you can file a new  issue for request, this is closed for duplicate bug
