### ISSUE TITLE
Android PlatformViews page back to non-platformview page, still glitch for one frame after this fix: https://github.com/flutter/engine/pull/30724/

### ISSUE THREAD

**Issue by eggfly** [flutter/flutter#102508] opened 2022-04-25 14:03 UTC
## Steps to Reproduce

Friendly cc @blasten  😄

0. Use the commits after this fix: https://github.com/flutter/engine/pull/30724
1. Use the stable 2.10.3 engine version, or use the github.com/flutter/flutter master branch commit(a1a305c9fa428846dc143bb7bdba68e62204fea4), it's exactly before "Roll Engine" commit before the new android platform view architecture merged into main engine branch(the new arch is ok without bug😄): https://github.com/flutter/engine/commit/5f0271a38988732c48f55c1244717430816391d3:
* https://github.com/flutter/engine/pull/31468

2. Use the demo Dart code below: 
3. Click any of the button in the list, navigate to webview and go back, you can see one frame glitch (about 30% probability), which position is around the clicked button's gray background.

Screenrecord
By camera:

https://user-images.githubusercontent.com/922837/165108746-ca4e4b8b-9834-43f1-b6de-fefb066426a4.MOV

By `adb screen record`:

https://user-images.githubusercontent.com/922837/165112326-5d6749ca-698d-4d75-b9a9-d2c3ebf898bf.mp4

Screenshot:
<img width="348" alt="image" src="https://user-images.githubusercontent.com/922837/165108679-4d329a79-d0fa-450b-b94d-34376bcded8a.png">

## Demo code:

<details>
<summary>CupertinoPageRoute Demo</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter/cupertino.dart';

import 'package:webview_flutter/webview_flutter.dart';


void main() {
  WebView.platform = SurfaceAndroidWebView();
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(home: HomeScreen());
  }
}

class HomeScreen extends StatefulWidget {
  const HomeScreen({Key? key}) : super(key: key);

  @override
  _HomeScreenState createState() => _HomeScreenState();
}

class _HomeScreenState extends State<HomeScreen> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SafeArea(
        child: Column(
          children: [
            ListTile(
              title: Text('Red'),
              onTap: () {
                Navigator.push(context, CupertinoPageRoute(builder: (context) {
                  return const ProducDetailPage();
                }));
              },
            ),
            ListTile(
              title: Text('Green'),
              onTap: () {
                Navigator.push(context, CupertinoPageRoute(builder: (context) {
                  return const ProducDetailPage();
                }));
              },
            ),
            ListTile(
              title: Text('Green 1'),
              onTap: () {
                Navigator.push(context, CupertinoPageRoute(builder: (context) {
                  return const ProducDetailPage();
                }));
              },
            ),
            ListTile(
              title: Text('Green 2'),
              onTap: () {
                Navigator.push(context, CupertinoPageRoute(builder: (context) {
                  return const ProducDetailPage();
                }));
              },
            ),
            ListTile(
              title: Text('Green 3'),
              onTap: () {
                Navigator.push(context, CupertinoPageRoute(builder: (context) {
                  return const ProducDetailPage();
                }));
              },
            ),
            ListTile(
              title: Text('Green 2'),
              onTap: () {
                Navigator.push(context, CupertinoPageRoute(builder: (context) {
                  return const ProducDetailPage();
                }));
              },
            ),
            ListTile(
              title: Text('Green 2'),
              onTap: () {
                Navigator.push(context, CupertinoPageRoute(builder: (context) {
                  return const ProducDetailPage();
                }));
              },
            ),
            ListTile(
              title: Text('Green 2'),
              onTap: () {
                Navigator.push(context, CupertinoPageRoute(builder: (context) {
                  return const ProducDetailPage();
                }));
              },
            ),
            ListTile(
              title: Text('Green 2'),
              onTap: () {
                Navigator.push(context, CupertinoPageRoute(builder: (context) {
                  return const ProducDetailPage();
                }));
              },
            ),
            ListTile(
              title: Text('Green 2'),
              onTap: () {
                Navigator.push(context, CupertinoPageRoute(builder: (context) {
                  return const ProducDetailPage();
                }));
              },
            ),
            ListTile(
              title: Text('Green 2'),
              onTap: () {
                Navigator.push(context, CupertinoPageRoute(builder: (context) {
                  return const ProducDetailPage();
                }));
              },
            ),
            CircularProgressIndicator(
              semanticsLabel: 'Linear progress indicator',
            ),
            CircularProgressIndicator(
              semanticsLabel: 'Linear progress indicator',
            ),
            CircularProgressIndicator(
              semanticsLabel: 'Linear progress indicator',
            ),
            CircularProgressIndicator(
              semanticsLabel: 'Linear progress indicator',
            ),
            CircularProgressIndicator(
              semanticsLabel: 'Linear progress indicator',
            ),
            ListTile(
              title: Text('Green 2'),
              onTap: () {
                Navigator.push(context, MaterialPageRoute(builder: (context) {
                  return const ProducDetailPage();
                }));
              },
            ),
            ListTile(
              title: Text('Green 2'),
              onTap: () {
                Navigator.push(context, MaterialPageRoute(builder: (context) {
                  return const ProducDetailPage();
                }));
              },
            ),
            ListTile(
              title: Text('Green 2'),
              onTap: () {
                Navigator.push(context, MaterialPageRoute(builder: (context) {
                  return const ProducDetailPage();
                }));
              },
            ),
            ListTile(
              title: Text('Green 2'),
              onTap: () {
                Navigator.push(context, MaterialPageRoute(builder: (context) {
                  return const ProducDetailPage();
                }));
              },
            ),
            ListTile(
              title: Text('Green 2'),
              onTap: () {
                Navigator.push(context, MaterialPageRoute(builder: (context) {
                  return const ProducDetailPage();
                }));
              },
            ),
            ListTile(
              title: Text('Green 2'),
              onTap: () {
                Navigator.push(context, MaterialPageRoute(builder: (context) {
                  return const ProducDetailPage();
                }));
              },
            ),
            ListTile(
              title: Text('Green 2'),
              onTap: () {
                Navigator.push(context, MaterialPageRoute(builder: (context) {
                  return const ProducDetailPage();
                }));
              },
            ),
            // CircularProgressIndicator(
            //   semanticsLabel: 'Linear progress indicator',
            // ),
            // SizedBox(
            //   height: 150,
            //   child: WebView(
            //     initialUrl: 'https://flutter.dev',
            //   ),
            // ),
          ],
        ),
      ),
    );
  }
}

class ProducDetailPage extends StatelessWidget {
  const ProducDetailPage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: const Text('Produc Detail'),
        ),
        body: Column(children: const [
          Padding(
            padding: EdgeInsets.all(8.0),
            child: SizedBox(
              height: 150,
              child: Placeholder(
                color: Colors.red,
              ),
            ),
          ),
          SizedBox(
            height: 150,
            child: WebView(
              initialUrl: 'https://flutter.dev',
            ),
          ),
            CircularProgressIndicator(
              semanticsLabel: 'Linear progress indicator',
            ),
        ]));
  }
}

class ProductDetailPage2 extends StatelessWidget {
  const ProductDetailPage2({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: const Text('Produc Detail'),
        ),
        body: Column(children: const [
          SizedBox(
            height: 150,
            child: Placeholder(
              color: Colors.green,
            ),
          ),
        ]));
  }
}


```

```
```

</details>

Here's my diagnosis: 

Firstly, the commit https://github.com/flutter/engine/pull/30724/files#diff-87fa95e503a7a95a32aee115dded76fc6f8ec76fc29c2d2c071b413df0c3a096R265
introduced the `isPaused` member, when isPaused is set to true, then the `stopRenderingToSurface()` is not called any more:
https://github.com/flutter/engine/pull/30724/files#diff-d3ae30246a95a9e78606b57b860941c4d74d5dfba9ecc394f202c9a62002531bR242

<img width="617" alt="image" src="https://user-images.githubusercontent.com/922837/165109035-d6162ed5-ba4f-498e-9772-790b76d93e1d.png">

Let's see there's a variable named `isDisplayingFlutterUi`  in FlutterRenderer.java :

https://github.com/flutter/engine/blob/f6dd681d4ec88b86a80bd367e6e050ae4ef7ffc7/shell/platform/android/io/flutter/embedding/engine/renderer/FlutterRenderer.java#L44

It controls the logic in `addIsDisplayingFlutterUiListener()`

<img width="877" alt="image" src="https://user-images.githubusercontent.com/922837/165109129-a54b6837-f19e-4e8c-9028-e9bf8f35c6de.png">

https://github.com/flutter/engine/blob/f6dd681d4ec88b86a80bd367e6e050ae4ef7ffc7/shell/platform/android/io/flutter/embedding/engine/renderer/FlutterRenderer.java#L78

when `isDisplayingFlutterUi` is true, the `addIsDisplayingFlutterUiListener` will directly calls the `listener` on current java call stack.

But in this issue's scenario, the code in `RevertImageView()`:
* firstly calls `renderSurface.attachToRenderer(renderer);` but not set `isDisplayingFlutterUi` to false;
* secondly calls `addIsDisplayingFlutterUiListener` and run `onDone.run()` directly on current stack.
It will
`onDone.run()` will call finishFrame() and will set `overlayView.setVisibility(View.GONE);`:

<img width="784" alt="image" src="https://user-images.githubusercontent.com/922837/165109971-bbaf7a9b-6511-4099-8dbc-b1ee6fac3675.png">

<img width="695" alt="image" src="https://user-images.githubusercontent.com/922837/165110051-1a6ffddd-e1f3-4b1f-9f79-f2e60e93745e.png">

But the gone of `FlutterImageView` is too early! And I think the first new frame rendering on SurfaceView is not ready yet. The previous image of SurfaceView shows the click state (with a gray shadow) of the button..

I think the wrong stack is here:
<img width="1309" alt="image" src="https://user-images.githubusercontent.com/922837/165111366-b4c04b0c-067c-4ea0-beb6-9e16c309615a.png">

After revert this commit, the original right stack is below:

![image](https://user-images.githubusercontent.com/922837/165109703-ac654d54-08bc-4356-8da5-07f254b14a05.png)

**Comment by blasten** [comment] 2022-04-25 17:50
@eggfly have you tried to run this on the master channel?
The code that you are referencing isn't used anymore. We now render WebView as a texture unless you use a new API called `initExpensiveAndroidView`, so there's no "hybrid" composition.

**Comment by eggfly** [comment] 2022-04-26 01:19
> @eggfly have you tried to run this on the master channel?
> The code that you are referencing isn't used anymore. We now render WebView as a texture unless you use a new API called `initExpensiveAndroidView`, so there's no "hybrid" composition by default.

Yes the master branch has no bug. But our apps' min.sdk level is below 23(most of them are 20 or 21).

**Comment by blasten** [comment] 2022-04-27 18:31
> But our apps' min.sdk level is below 23(most of them are 20 or 21).

That's a limitation unfortunately. Contributions are welcome though.
This issue is relatively low priority since there's a solution for API level >=23.

**Comment by chinmaygarde** [comment] 2022-05-02 18:02
This seems to be working as intended. Closing.

**Closed by chinmaygarde** 2022-05-02 18:02 UTC
Labels: platform-android, engine, a: platform-views, passed first triage
