### ISSUE TITLE
Problem managing InkWells at nested levels.

### ISSUE THREAD

**Issue by manujbahl** [flutter/flutter#18861] opened 2018-06-27 05:40 UTC
It looks like the way to define `InkWell` is to put it at the top of the stack so that we can see the ripple effect and the taps are captured by the `InkWell` widget. 

Im my case I have nested levels of containers each with their own `InkWells`. Now because of the way `InkWells` are designed, I can't have the inner container `InkWell` respond to taps because the Outer container `InkWell` is always on top of everything and prevents the tap being received by the Inner Container. 

Does anyone have a solution to this problem ? Below is a piece of code demonstrating this issue

[https://gist.github.com/manujbahl/d0ffaa1607f3b4ae8758bbae7378e469](https://gist.github.com/manujbahl/d0ffaa1607f3b4ae8758bbae7378e469)

```dart
import 'package:flutter/material.dart';

main() {    
    runApp(new TestSample());
}

class TestSample extends StatelessWidget{
    @override
    Widget build(BuildContext context) {
         var widget = new MaterialApp(
                home: new Scaffold(
                    body: new Center( 
                        child: new OuterContainerStack(),
                    )
                ),
            );
            return widget;
        }
}

class OuterContainerStack extends StatelessWidget {
    @override
    Widget build(BuildContext context) {
        return new Stack(
            children: <Widget>[
                new OuterContainer(),
                new Positioned.fill(
                    child: new Material(
                        color: Colors.transparent,
                        child:new InkWell(
                            onTap: () {
                                print("Outer Container");
                            }
                        )
                    )
                )
            ],
        );

    }
}

class OuterContainer extends StatelessWidget {
    @override
    Widget build(BuildContext context) {
        return new Container(
            width: 300.0,
            height: 300.0,
            color: Colors.blueAccent,
            child: new Column(
                mainAxisAlignment: MainAxisAlignment.center,
                crossAxisAlignment: CrossAxisAlignment.center,
                children: <Widget>[
                    new InnerContainerStack()
                ],
            ),
        );

    }
}

class InnerContainerStack extends StatelessWidget {
    @override
    Widget build(BuildContext context) {
        return new Stack(
            children: <Widget>[
                new InnerContainer(),
                new Positioned.fill(
                    child: new Material(
                        color: Colors.transparent,
                        child:new InkWell(
                            onTap: () {
                                print("Inner Container");
                            }
                        )
                    )
                )
            ],
        );

    }
}

class InnerContainer extends StatelessWidget {
    @override
    Widget build(BuildContext context) {
        return new Container(
            width: 200.0,
            height: 200.0,
            color: Colors.redAccent
        );

    }
}
```

**Comment by manujbahl** [comment] 2018-06-27 15:46
this is the output from flutter doctor.  

> [✓] Flutter (Channel master, v0.5.5-pre.14, on Mac OS X 10.13.5 17F77, locale en-US)
>     • Flutter version 0.5.5-pre.14 at /Users/MBahl/flutter/flutter
>     • Framework revision b401e76554 (2 weeks ago), 2018-06-13 09:20:19 -0700
>     • Engine revision c3976b3c71
>     • Dart version 2.0.0-dev.61.0.flutter-c95617b19c
> 
> [✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
>     • Android SDK at /Users/MBahl/Library/Android/sdk
>     • Android NDK at /Users/MBahl/Library/Android/sdk/ndk-bundle
>     • Platform android-28, build-tools 27.0.3
>     • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
>     • All Android licenses accepted.
> 
> [✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • Xcode 9.4.1, Build version 9F2000
>     • ios-deploy 1.9.2
>     • CocoaPods version 1.5.3
> 
> [✓] Android Studio (version 3.1)
>     • Android Studio at /Applications/Android Studio.app/Contents
>     • Flutter plugin version 20.0.1
>     • Dart plugin version 171.4424
>     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
> 
> [!] VS Code (version 1.24.1)
>     • VS Code at /Applications/Visual Studio Code.app/Contents
>     • Flutter extension not installed; install from
>       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
> 
> [✓] Connected devices (1 available)
>     • iPhone X • 1B5D88F3-6FD1-4154-95F9-711950D6049A • ios • iOS 11.4 (simulator)
> 
> ! Doctor found issues in 1 category.

I do have dart and flutter plugins installed and those are working just fine. Not sure why flutter doctor is complaining about that

**Comment by manujbahl** [comment] 2018-06-27 15:46
![image](https://user-images.githubusercontent.com/5688107/41984878-9fc77dda-79e6-11e8-8348-0fbdaecaded5.png)

**Comment by manujbahl** [comment] 2018-06-29 15:08
anything ?

**Comment by zoechi** [comment] 2018-06-29 15:46
Have you considered asking on SO?

**Comment by zoechi** [comment] 2019-01-28 18:48
https://stackoverflow.com/questions/54408064/how-do-deal-with-nested-inkwell-with-flutter

**Comment by Hixie** [comment] 2019-05-30 17:22
Duplicate of https://github.com/flutter/flutter/issues/14417, which has a workaround for now.

**Closed by Hixie** 2019-05-30 17:22 UTC
Labels: f: material design, framework
