### ISSUE TITLE
Invalid luci-engine check prevents roll cls from landing

### ISSUE THREAD

**Issue by aam** [flutter/flutter#91098] opened 2021-10-01 16:51 UTC
dart roll https://github.com/flutter/engine/pull/28984 has been sitting for 5 hours with "luci-engine — Tree is currently broken...." despite tree being seemingly green.

Might be related to https://github.com/flutter/flutter/issues/90997

cc @godofredoc

**Comment by godofredoc** [comment] 2021-10-04 17:55
This was a problem with the way we query the builds to validate status. Builds triggered with bb don't have all the required tags anymore which causes that successful bb builds to get ignored.

**Comment by godofredoc** [comment] 2021-10-04 17:57
duplicate of https://github.com/flutter/flutter/issues/90569

**Closed by godofredoc** 2021-10-04 17:57 UTC
Labels: team: infra
