### ISSUE TITLE
ThemeData.primaryColor not working in flutter 3.0.0

### ISSUE THREAD

**Issue by SchweitzerGAO** [flutter/flutter#104311] opened 2022-05-21 05:50 UTC
## Steps to Reproduce

Hi there, I am a novice user of flutter 3.0.0 and I just finished following the official Chinese tutorial of building a application: 
[https://codelabs.flutter-io.cn/codelabs/first-flutter-app-pt2-cn/index.html#0](https://codelabs.flutter-io.cn/codelabs/first-flutter-app-pt2-cn/index.html#0)
When I proceeded to step 7, I followed the steps and modified the code:

```dart
@override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Startup Name Generator',
      theme: ThemeData(
        primaryColor: Colors.red,
      ),
      home: const RandomWords(),
    );
  }
```
But it doesn't work for me and it remains blue in the emulator:
![image](https://user-images.githubusercontent.com/64410968/169637300-3892f304-3a90-4605-9b0a-45e814919500.png)
<details>
<summary>Code sample</summary>

```dart
@override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Startup Name Generator',
      theme: ThemeData(
        primaryColor: Colors.red,
      ),
      home: const RandomWords(),
    );
  }
```

</details>

<details>
  <summary>Logs</summary>

log for `flutter run --verbose`
```
[  +95 ms] executing: [D:\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +134 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +2 ms] ee4e09cce01d6f2d7f4baebd247fde02e5008851
[        ] executing: [D:\flutter/] git tag --points-at ee4e09cce01d6f2d7f4baebd247fde02e5008851
[  +75 ms] Exit code 0 from: git tag --points-at ee4e09cce01d6f2d7f4baebd247fde02e5008851
[   +1 ms] 3.0.0
[  +15 ms] executing: [D:\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +63 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] origin/stable
[        ] executing: [D:\flutter/] git ls-remote --get-url origin
[  +55 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter.git
[ +153 ms] executing: [D:\flutter/] git rev-parse --abbrev-ref HEAD
[  +65 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] stable
[  +97 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +72 ms] executing: D:\Android-SDK\platform-tools\adb.exe devices -l
[  +84 ms] List of devices attached
           emulator-5554          device product:sdk_gphone_x86 model:sdk_gphone_x86 device:generic_x86_arm transport_id:2
[  +17 ms] D:\Android-SDK\platform-tools\adb.exe -s emulator-5554 shell getprop
[  +83 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +4 ms] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +196 ms] Skipping pub get: version match.
[  +94 ms] Generating D:\COURSE_WORK_Bachelor\CV2022Spring\project\palm_mobile\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +63 ms] ro.hardware = ranchu
[  +20 ms] Using hardware rendering with device sdk gphone x86. If you notice graphics artifacts, consider enabling software rendering with "--enable-software-rendering".
[  +34 ms] Initializing file store
[  +23 ms] Skipping target: gen_localizations
[  +11 ms] gen_dart_plugin_registrant: Starting due to {InvalidatedReasonKind.inputChanged: The following inputs have updated contents:
D:\COURSE_WORK_Bachelor\CV2022Spring\project\palm_mobile\.dart_tool\package_config_subset}
[  +37 ms] gen_dart_plugin_registrant: Complete
[   +3 ms] Skipping target: _composite
[   +3 ms] complete
[   +7 ms] Launching lib\main.dart on sdk gphone x86 in debug mode...
[   +7 ms] D:\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev D:\flutter\bin\cache\dart-sdk\bin\snapshots\frontend_server.dart.snapshot --sdk-root
D:\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names --experimental-emit-debug-metadata
-DFLUTTER_WEB_AUTO_DETECT=true --output-dill C:\Users\CHARLE~1\AppData\Local\Temp\flutter_tools.2efe6514\flutter_tool.655eae54\app.dill --packages
D:\COURSE_WORK_Bachelor\CV2022Spring\project\palm_mobile\.dart_tool\package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation
--filesystem-scheme org-dartlang-root --initialize-from-dill build\c075001b96339384a97db4862b8ab8db.cache.dill.track.dill --enable-experiment=alternative-invalidation-strategy
[  +10 ms] executing: D:\Android-SDK\build-tools\32.1.0-rc1\aapt dump xmltree D:\COURSE_WORK_Bachelor\CV2022Spring\project\palm_mobile\build\app\outputs\flutter-apk\app.apk
AndroidManifest.xml
[  +34 ms] Exit code 0 from: D:\Android-SDK\build-tools\32.1.0-rc1\aapt dump xmltree D:\COURSE_WORK_Bachelor\CV2022Spring\project\palm_mobile\build\app\outputs\flutter-apk\app.apk
AndroidManifest.xml
[   +1 ms] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1f
               A: android:compileSdkVersionCodename(0x01010573)="12" (Raw: "12")
               A: package="cv.palm.palm_mobile" (Raw: "cv.palm.palm_mobile")
               A: platformBuildVersionCode=(type 0x10)0x1f
               A: platformBuildVersionName=(type 0x10)0xc
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1f
               E: uses-permission (line=15)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: application (line=17)
                 A: android:label(0x01010001)="palm_mobile" (Raw: "palm_mobile")
                 A: android:icon(0x01010002)=@0x7f080000
                 A: android:name(0x01010003)="android.app.Application" (Raw: "android.app.Application")
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A: android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComponentFactory" (Raw: "androidx.core.app.CoreComponentFactory")
                 E: activity (line=23)
                   A: android:theme(0x01010000)=@0x7f0a0000
                   A: android:name(0x01010003)="cv.palm.palm_mobile.MainActivity" (Raw: "cv.palm.palm_mobile.MainActivity")
                   A: android:exported(0x01010010)=(type 0x12)0xffffffff
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x40003fb4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: meta-data (line=38)
                     A: android:name(0x01010003)="io.flutter.embedding.android.NormalTheme" (Raw: "io.flutter.embedding.android.NormalTheme")
                     A: android:resource(0x01010025)=@0x7f0a0001
                   E: intent-filter (line=42)
                     E: action (line=43)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
                     E: category (line=45)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw: "android.intent.category.LAUNCHER")
                 E: meta-data (line=52)
                   A: android:name(0x01010003)="flutterEmbedding" (Raw: "flutterEmbedding")
                   A: android:value(0x01010024)=(type 0x10)0x2
                 E: uses-library (line=56)
                   A: android:name(0x01010003)="androidx.window.extensions" (Raw: "androidx.window.extensions")
                   A: android:required(0x0101028e)=(type 0x12)0x0
                 E: uses-library (line=59)
                   A: android:name(0x01010003)="androidx.window.sidecar" (Raw: "androidx.window.sidecar")
                   A: android:required(0x0101028e)=(type 0x12)0x0
[   +9 ms] executing: D:\Android-SDK\platform-tools\adb.exe -s emulator-5554 shell -x logcat -v time -t 1
[  +18 ms] <- compile package:palm_mobile/main.dart
[  +92 ms] --------- beginning of main
           05-21 05:45:15.343 W/adbd    ( 1865): timeout expired while flushing socket, closing
[  +18 ms] executing: D:\Android-SDK\platform-tools\adb.exe version
[ +130 ms] Android Debug Bridge version 1.0.41
                    Version 33.0.1-8253317
                    Installed as D:\Android-SDK\platform-tools\adb.exe
[  +11 ms] executing: D:\Android-SDK\platform-tools\adb.exe start-server
[ +111 ms] Building APK
[  +64 ms] Running Gradle task 'assembleDebug'...
[   +4 ms] Using gradle from D:\COURSE_WORK_Bachelor\CV2022Spring\project\palm_mobile\android\gradlew.bat.
[  +23 ms] executing: [D:\COURSE_WORK_Bachelor\CV2022Spring\project\palm_mobile\android/] D:\COURSE_WORK_Bachelor\CV2022Spring\project\palm_mobile\android\gradlew.bat
-Pverbose=true -Ptarget-platform=android-x86 -Ptarget=D:\COURSE_WORK_Bachelor\CV2022Spring\project\palm_mobile\lib\main.dart -Pbase-application-name=android.app.Application
-Pdart-defines=RkxVVFRFUl9XRUJfQVVUT19ERVRFQ1Q9dHJ1ZQ== -Pdart-obfuscation=false -Ptrack-widget-creation=true -Ptree-shake-icons=false -Pfilesystem-scheme=org-dartlang-root
assembleDebug
[+2289 ms] > Task :app:preBuild UP-TO-DATE
[   +1 ms] > Task :app:preDebugBuild UP-TO-DATE
[        ] > Task :app:mergeDebugNativeDebugMetadata NO-SOURCE
[  +88 ms] > Task :app:compileFlutterBuildDebug UP-TO-DATE
[   +1 ms] > Task :app:packLibsflutterBuildDebug UP-TO-DATE
[        ] > Task :app:compileDebugAidl NO-SOURCE
[        ] > Task :app:compileDebugRenderscript NO-SOURCE
[        ] > Task :app:generateDebugBuildConfig UP-TO-DATE
[  +96 ms] > Task :app:checkDebugAarMetadata UP-TO-DATE
[   +1 ms] > Task :app:cleanMergeDebugAssets
[        ] > Task :app:mergeDebugShaders UP-TO-DATE
[        ] > Task :app:compileDebugShaders NO-SOURCE
[        ] > Task :app:generateDebugAssets UP-TO-DATE
[        ] > Task :app:mergeDebugAssets
[ +697 ms] > Task :app:copyFlutterAssetsDebug
[   +3 ms] > Task :app:generateDebugResValues UP-TO-DATE
[        ] > Task :app:generateDebugResources UP-TO-DATE
[   +1 ms] > Task :app:mergeDebugResources UP-TO-DATE
[        ] > Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
[        ] > Task :app:extractDeepLinksDebug UP-TO-DATE
[        ] > Task :app:processDebugMainManifest UP-TO-DATE
[        ] > Task :app:processDebugManifest UP-TO-DATE
[   +1 ms] > Task :app:processDebugManifestForPackage UP-TO-DATE
[  +90 ms] > Task :app:processDebugResources UP-TO-DATE
[   +2 ms] > Task :app:compileDebugKotlin UP-TO-DATE
[        ] > Task :app:javaPreCompileDebug UP-TO-DATE
[ +247 ms] > Task :app:compileDebugJavaWithJavac UP-TO-DATE
[ +209 ms] > Task :app:processDebugJavaRes NO-SOURCE
[  +13 ms] > Task :app:mergeDebugJavaResource UP-TO-DATE
[   +1 ms] > Task :app:checkDebugDuplicateClasses UP-TO-DATE
[   +2 ms] > Task :app:dexBuilderDebug UP-TO-DATE
[   +1 ms] > Task :app:desugarDebugFileDependencies UP-TO-DATE
[   +1 ms] > Task :app:mergeExtDexDebug UP-TO-DATE
[   +1 ms] > Task :app:mergeDexDebug UP-TO-DATE
[   +2 ms] > Task :app:mergeDebugJniLibFolders UP-TO-DATE
[  +16 ms] > Task :app:mergeDebugNativeLibs UP-TO-DATE
[   +7 ms] > Task :app:stripDebugDebugSymbols UP-TO-DATE
[   +1 ms] > Task :app:validateSigningDebug UP-TO-DATE
[   +5 ms] > Task :app:writeDebugAppMetadata UP-TO-DATE
[   +1 ms] > Task :app:writeDebugSigningConfigVersions UP-TO-DATE
[+1583 ms] > Task :app:compressDebugAssets
[   +3 ms] Execution optimizations have been disabled for task ':app:compressDebugAssets' to ensure correctness due to the following reasons:
[   +4 ms]   - Gradle detected a problem with the following location:
'D:\COURSE_WORK_Bachelor\CV2022Spring\project\palm_mobile\build\app\intermediates\assets\debug\mergeDebugAssets'. Reason: Task ':app:compressDebugAssets' uses this output of task
':app:copyFlutterAssetsDebug' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are
executed. Please refer to https://docs.gradle.org/7.4/userguide/validation_problems.html#implicit_dependency for more details about this problem.
[ +390 ms] > Task :app:packageDebug UP-TO-DATE
[   +3 ms] > Task :app:createDebugApkListingFileRedirect UP-TO-DATE
[ +195 ms] > Task :app:assembleDebug
[  +42 ms] Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
[   +1 ms] You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
[   +1 ms] See https://docs.gradle.org/7.4/userguide/command_line_interface.html#sec:command_line_warnings
[        ] Execution optimizations have been disabled for 1 invalid unit(s) of work during this build to ensure correctness.
[   +1 ms] Please consult deprecation warnings for more details.
[        ] BUILD SUCCESSFUL in 5s
[   +1 ms] 35 actionable tasks: 5 executed, 30 up-to-date
[ +386 ms] Running Gradle task 'assembleDebug'... (completed in 6.4s)
[  +39 ms] calculateSha: LocalDirectory: 'D:\COURSE_WORK_Bachelor\CV2022Spring\project\palm_mobile\build\app\outputs\flutter-apk'/app.apk
[ +646 ms] √  Built build\app\outputs\flutter-apk\app-debug.apk.
[   +4 ms] executing: D:\Android-SDK\build-tools\32.1.0-rc1\aapt dump xmltree D:\COURSE_WORK_Bachelor\CV2022Spring\project\palm_mobile\build\app\outputs\flutter-apk\app.apk
AndroidManifest.xml
[  +52 ms] Exit code 0 from: D:\Android-SDK\build-tools\32.1.0-rc1\aapt dump xmltree D:\COURSE_WORK_Bachelor\CV2022Spring\project\palm_mobile\build\app\outputs\flutter-apk\app.apk
AndroidManifest.xml
[   +2 ms] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1f
               A: android:compileSdkVersionCodename(0x01010573)="12" (Raw: "12")
               A: package="cv.palm.palm_mobile" (Raw: "cv.palm.palm_mobile")
               A: platformBuildVersionCode=(type 0x10)0x1f
               A: platformBuildVersionName=(type 0x10)0xc
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1f
               E: uses-permission (line=15)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: application (line=17)
                 A: android:label(0x01010001)="palm_mobile" (Raw: "palm_mobile")
                 A: android:icon(0x01010002)=@0x7f080000
                 A: android:name(0x01010003)="android.app.Application" (Raw: "android.app.Application")
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A: android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComponentFactory" (Raw: "androidx.core.app.CoreComponentFactory")
                 E: activity (line=23)
                   A: android:theme(0x01010000)=@0x7f0a0000
                   A: android:name(0x01010003)="cv.palm.palm_mobile.MainActivity" (Raw: "cv.palm.palm_mobile.MainActivity")
                   A: android:exported(0x01010010)=(type 0x12)0xffffffff
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x40003fb4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: meta-data (line=38)
                     A: android:name(0x01010003)="io.flutter.embedding.android.NormalTheme" (Raw: "io.flutter.embedding.android.NormalTheme")
                     A: android:resource(0x01010025)=@0x7f0a0001
                   E: intent-filter (line=42)
                     E: action (line=43)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
                     E: category (line=45)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw: "android.intent.category.LAUNCHER")
                 E: meta-data (line=52)
                   A: android:name(0x01010003)="flutterEmbedding" (Raw: "flutterEmbedding")
                   A: android:value(0x01010024)=(type 0x10)0x2
                 E: uses-library (line=56)
                   A: android:name(0x01010003)="androidx.window.extensions" (Raw: "androidx.window.extensions")
                   A: android:required(0x0101028e)=(type 0x12)0x0
                 E: uses-library (line=59)
                   A: android:name(0x01010003)="androidx.window.sidecar" (Raw: "androidx.window.sidecar")
                   A: android:required(0x0101028e)=(type 0x12)0x0
[   +5 ms] Stopping app 'app.apk' on sdk gphone x86.
[   +1 ms] executing: D:\Android-SDK\platform-tools\adb.exe -s emulator-5554 shell am force-stop cv.palm.palm_mobile
[ +119 ms] executing: D:\Android-SDK\platform-tools\adb.exe -s emulator-5554 shell pm list packages cv.palm.palm_mobile
[ +160 ms] package:cv.palm.palm_mobile
[   +5 ms] executing: D:\Android-SDK\platform-tools\adb.exe -s emulator-5554 shell cat /data/local/tmp/sky.cv.palm.palm_mobile.sha1
[ +173 ms] 6ee477e634e7a2ad2a5f052bb68e326463727314
[   +2 ms] Latest build already installed.
[        ] executing: D:\Android-SDK\platform-tools\adb.exe -s emulator-5554 shell -x logcat -v time -t 1
[  +98 ms] --------- beginning of main
           05-21 05:45:28.168 I/TngMinusOneSync( 2199): Syncing TNG:-1
[   +9 ms] executing: D:\Android-SDK\platform-tools\adb.exe -s emulator-5554 shell am start -a android.intent.action.RUN -f 0x20000000 --ez enable-dart-profiling true --ez
enable-checked-mode true --ez verify-entry-points true cv.palm.palm_mobile/cv.palm.palm_mobile.MainActivity
[  +99 ms] Starting: Intent { act=android.intent.action.RUN flg=0x20000000 cmp=cv.palm.palm_mobile/.MainActivity (has extras) }
[   +1 ms] Waiting for observatory port to be available...
[ +783 ms] Observatory URL on device: http://127.0.0.1:39733/urXFAi1fPps=/
[   +1 ms] executing: D:\Android-SDK\platform-tools\adb.exe -s emulator-5554 forward tcp:0 tcp:39733
[  +45 ms] 55249
[   +1 ms] Forwarded host port 55249 to device port 39733 for Observatory
[   +7 ms] Caching compiled dill
[  +37 ms] Connecting to service protocol: http://127.0.0.1:55249/urXFAi1fPps=/
[ +329 ms] Launching a Dart Developer Service (DDS) instance at http://127.0.0.1:0, connecting to VM service at http://127.0.0.1:55249/urXFAi1fPps=/.
[ +173 ms] DDS is listening at http://127.0.0.1:55252/YZ9qGPoR4hs=/.
[  +74 ms] Successfully connected to service protocol: http://127.0.0.1:55249/urXFAi1fPps=/
[  +94 ms] DevFS: Creating new filesystem on the device (null)
[  +35 ms] DevFS: Created new filesystem on the device (file:///data/user/0/cv.palm.palm_mobile/code_cache/palm_mobileEAIJBV/palm_mobile/)
[   +4 ms] Updating assets
[ +138 ms] Syncing files to device sdk gphone x86...
[   +3 ms] <- reset
[   +2 ms] Compiling dart to kernel with 0 updated files
[   +1 ms] Processing bundle.
[   +2 ms] <- recompile package:palm_mobile/main.dart cda39142-ed99-43e1-b89b-b15eeb3cd94d
[        ] <- cda39142-ed99-43e1-b89b-b15eeb3cd94d
[   +2 ms] Bundle processing done.
[ +117 ms] Updating files.
[        ] DevFS: Sync finished
[   +2 ms] Syncing files to device sdk gphone x86... (completed in 132ms)
[   +1 ms] Synced 0.0MB.
[   +2 ms] <- accept
[   +8 ms] Connected to _flutterView/0xf0204580.
[   +3 ms] Flutter run key commands.
[   +2 ms] r Hot reload.
[        ] R Hot restart.
[        ] h List all available interactive commands.
[        ] d Detach (terminate "flutter run" but leave application running).
[   +1 ms] c Clear the screen
[        ] q Quit (terminate the application on the device).
[        ]  Running with sound null safety
[   +1 ms] An Observatory debugger and profiler on sdk gphone x86 is available at: http://127.0.0.1:55252/YZ9qGPoR4hs=/
[+1599 ms] The Flutter DevTools debugger and profiler on sdk gphone x86 is available at: http://127.0.0.1:9101?uri=http://127.0.0.1:55252/YZ9qGPoR4hs=/

```

log for `flutter analyze`
```
Analyzing palm_mobile...
No issues found! (ran in 3.0s)

```

log for `flutter doctor -v`
```
[√] Flutter (Channel stable, 3.0.0, on Microsoft Windows [版本 10.0.19044.1645], locale zh-CN)
    • Flutter version 3.0.0 at D:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ee4e09cce0 (11 days ago), 2022-05-09 16:45:18 -0700
    • Engine revision d1b9a6938a
    • Dart version 2.17.0
    • DevTools version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at D:\Android-SDK\
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: D:\Java\bin\java
    • Java version Java(TM) SE Runtime Environment (build 17.0.2+8-LTS-86)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.10.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.10.31515.178
    • Windows 10 SDK version 10.0.19041.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] IntelliJ IDEA Ultimate Edition (version 2021.2)
    • IntelliJ at D:\JetBrains\IntelliJ IDEA 2021.2.1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code (version 1.67.1)
    • VS Code at C:\Users\CharlesGao\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (4 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)       • windows       • windows-x64    • Microsoft Windows [版本 10.0.19044.1645]
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 101.0.4951.67
    • Edge (web)              • edge          • web-javascript • Microsoft Edge 101.0.1210.32

HTTP Host availability check is taking a long time...[!] HTTP Host Availability
    X HTTP host "https://maven.google.com/" is not reachable. Reason: An error occurred while checking the HTTP host: 信号灯超时时间已到

    X HTTP host "https://cloud.google.com/" is not reachable. Reason: An error occurred while checking the HTTP host: 信号灯超时时间已到


! Doctor found issues in 2 categories.

```
I think the issues is caused by the internet environment in China but I used VPN 
</details>

**Comment by naveenlearner38** [comment] 2022-05-21 20:15
Instead of primaryColor. Try primarySwatch in ThemeData

**Comment by SchweitzerGAO** [comment] 2022-05-23 02:02
OK thanks and I will try it

**Comment by SchweitzerGAO** [comment] 2022-05-23 03:27
Thanks @naveenlearner38 it works! but it worked wrongly only with the color white and black, when I set the color to white or black, it failed to run and it throws an exception:
![image](https://user-images.githubusercontent.com/64410968/169737370-eb125e05-cc7e-4949-a44b-67cab83e5b8f.png)
I searched for solutions, some people said that I have to create my own `MaterialColor`. Do I really need to do this? 
By the way, I set the color by this code:
```Dart
Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Startup Name Generator',
      theme: ThemeData(
        primarySwatch: Colors.white
      ),
      home: const RandomWords(),
    );
  }
```

**Comment by naveenlearner38** [comment] 2022-05-23 05:42
> Thanks @naveenlearner38 it works! but it worked wrongly only with the color white and black, when I set the color to white or black, it failed to run and it throws an exception: ![image](https://user-images.githubusercontent.com/64410968/169737370-eb125e05-cc7e-4949-a44b-67cab83e5b8f.png) I searched for solutions, some people said that I have to create my own `MaterialColor`. Do I really need to do this? By the way, I set the color by this code:
> 
> ```dart
> Widget build(BuildContext context) {
>     return MaterialApp(
>       title: 'Startup Name Generator',
>       theme: ThemeData(
>         primarySwatch: Colors.white
>       ),
>       home: const RandomWords(),
>     );
>   }
> ```

https://github.com/flutter/flutter/issues/23239 Look this

**Comment by maheshmnj** [comment] 2022-05-23 09:21
Hi @SchweitzerGAO, Thanks for filing the issue this is working as intended due to the [on going work on Theme System](https://docs.google.com/document/d/1kzIOQN4QYfVsc5lMZgy_A-FWGXBAJBMySGqZqsJytcE/edit#heading=h.pub7jnop54q0) 
see https://github.com/flutter/flutter/issues/89839#issuecomment-919437144. to apply `primaryColor`  you may use `colorScheme` as below 

```dart
theme: ThemeData(
     colorScheme: ColorScheme.light().copyWith(primary: Colorss.white),
  );
```

Closing as working as intended

**Closed by maheshmnj** 2022-05-23 09:21 UTC
Labels: in triage

**Comment by SchweitzerGAO** [comment] 2022-05-23 11:11
Sure and many thanks

**Comment by SchweitzerGAO** [comment] 2022-05-23 11:52
Thanks @naveenlearner38 #23239 worked for me!
