### ISSUE TITLE
[local_auth] Returns false without checking biometrics at all

### ISSUE THREAD

**Issue by YAPPDEF** [flutter/flutter#53826] opened 2020-04-02 14:36 UTC
We have a very strange issue which is currently not reproducible (most of the time it works just fine and suddenly stops working).

There is no error output at all. When calling `authenticateWithBiometrics`, it just returns false (as if the user was not able to log in successfully). But the popup of the biometrics was never displayed to the user. So when triggering it again, it immediately returns false.

This is a very annoying bug. Both on Android and iOS
Currently using Flutter (Channel stable, v1.12.13+hotfix.8)

**Comment by darshankawar** [comment] 2021-03-03 13:08
@YAPPDEF 
Is this still a valid issue ? The plugin has gone through [updates](https://pub.dev/packages/local_auth/changelog) since this issue was logged. I recommend you to upgrade to [latest](https://pub.dev/packages/local_auth/install) plugin version and stable version and try again to see if issue persists or not.

If so, can you provide a reproducible code sample that shows the issue ?

**Comment by YAPPDEF** [comment] 2021-03-03 15:05
@darshankawar sadly yes.. We did change the logic of the screen which triggers it. This also did not work..

It's very hard to reproduce and test as it only happens very rarely and out of nothing. There is no pattern yet.

It could have something to do with app flavors (which we use).
I once saw in the device logs (with that problem) that local_auth logged another flavor we were just using. 
We're currently on `0.6.2+3`

**Comment by darshankawar** [comment] 2021-03-04 06:13
@YAPPDEF 
Thanks for getting back.
Is there a way to provide a reproducible use case involving app flavors that we can try and verify ?

**Comment by YAPPDEF** [comment] 2021-03-04 07:13
@darshankawar 
As mentioned sadly not. It mostly works fine and then all of a sudden biometrics is not possible anymore. So always returning false from that moment on.

If we find a pattern we can put in an example to reproduce the issue, I'll update it here

**Comment by pedromassangocode** [comment] 2021-04-23 09:15
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2021-04-23 09:15 UTC
Labels: p: first party, p: local_auth, plugin, waiting for customer response
