### ISSUE TITLE
Regression in moke_catalina_hot_mode_dev_cycle_ios__benchmark_hotRestartMillisecondsToFrame & related benchmarks

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#45993] opened 2019-12-03 15:40 UTC
Looks like it started in https://github.com/flutter/flutter/pull/45817. May be related to https://github.com/flutter/flutter/issues/45992.

**Comment by jonahwilliams** [comment] 2019-12-03 22:39
Looking at the rest of the integration tests for hot reload performance, only Catalina benchmarks regressed. This could be caused by an infra issue, such as a system dialog opening on the device or something else running on the machine

**Comment by Hixie** [comment] 2019-12-03 22:53
Given that four benchmarks regressed at roughly the same time but on different commits all on the same bot, I suspect the bot.

**Comment by Hixie** [comment] 2019-12-03 22:55
Hm, actually, they didn't all happen at the same time. Weird. There's a few hours difference.

**Comment by Piinks** [comment] 2019-12-04 00:16
Its hard to tell from the dashboard, but it actually looks to me like it happened at https://github.com/flutter/flutter/commit/02bca1342d2025e0d3bf3c115957950c9b1ea749 , which would not make much sense as it is a revert.

**Comment by Piinks** [comment] 2019-12-04 00:18
Actually, disregard, I mean that comment for the other Today bug, #45992.

**Comment by godofredoc** [comment] 2019-12-04 06:28
Metrics are back to the expected values:

I had to kill "/Users/flutter/.cocoon/flutter/bin/cache/artifacts/libimobiledevice/idevicesyslog" because it was keeping ~2000 files open.

I also had to kill "/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/Resources/usbmuxd -launchd" for the metrics to go to expected values

**Comment by godofredoc** [comment] 2019-12-04 06:32
This is actually related to https://github.com/flutter/flutter/issues/45112. Will close this one and add context to #45112

**Closed by godofredoc** 2019-12-04 06:32 UTC
Labels: autoroller: commit, severe: performance, severe: regression, t: hot reload
