### ISSUE TITLE
[Impeller] Canvas.drawVertices() does not work on iOS simulator/device

### ISSUE THREAD

**Issue by badlogic** [flutter/flutter#127486] opened 2023-05-24 11:32 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Clone this minimal reproduction project: https://github.com/badlogic/flutter-mali-crash
2. Compile it with Flutter SDK 3.10.1 and run it on an iOS simulator or device via `flutter run`

### Expected results

<img width="453" alt="Screenshot 2023-05-24 at 13 21 15" src="https://github.com/flutter/flutter/assets/514052/ac18281f-4870-4f7c-a6d7-b00dfc0ef0c5">

The expected results shows up when running the app without Impeller via `flutter run --no-enable-impeller`

### Actual results

<img width="453" alt="Screenshot 2023-05-24 at 13 20 26" src="https://github.com/flutter/flutter/assets/514052/11a2a7c6-53c8-47aa-a5e5-0489ca37a34e">

The result shown when running the app on the iOS simulator or device with Impeller enabled, i.e. `flutter run`

### Code sample

<details><summary>Code sample</summary>

A minimal reproduction sample can be found here: https://github.com/badlogic/flutter-mali-crash
The sample loads mesh data from a text file and converts it to a Vertices instance. It also loads an image and constructs an ImageShader based Paint from it. It then proceeds to render the vertices instance 12 times at random locations on the screen via Canvas.drawVertices() using the `modulate` blend mode together with a trivial `ImageShader`. Other blend modes also fail.

The app uses Flame to minimize the LOC count. Flame itself does not interfere with the rendering in any meaningful way other than setting a transform on the Canvas instance used for rendering.

```dart
import 'dart:convert';
import 'dart:math';
import 'dart:typed_data';
import 'dart:ui' as ui;

import 'package:flame/game.dart';
import 'package:flutter/services.dart';
import 'package:flutter/material.dart';
import 'package:flutter/painting.dart' as painting;

void main() {
  runApp(const MyApp());
}

class MaliCrash extends FlameGame {
  late ui.Image _texture;
  late Paint _paint;
  late ui.Vertices _vertices;
  late List<Vector2> _positions = [];

  Future<void> _loadPaint() async {
    final imageData = (await rootBundle.load("assets/spineboy.png")).buffer.asUint8List();
    final codec = await ui.instantiateImageCodec(imageData);
    final frameInfo = await codec.getNextFrame();
    _texture = frameInfo.image;
    _paint = Paint()
      ..shader = ImageShader(_texture, TileMode.clamp, TileMode.clamp, Matrix4.identity().storage, filterQuality: FilterQuality.high)
      ..isAntiAlias = true;
  }

  Future<void> _loadVertices() async {
    final lines = LineSplitter().convert(await rootBundle.loadString("assets/spineboy.mesh"));
    final numVertices = int.parse(lines[0]);
    final numIndices = int.parse(lines[1]);
    final positions = Float32List(numVertices * 2);
    final uvs = Float32List(numVertices * 2);
    final colors = Int32List(numVertices);
    final indices = Uint16List(numIndices);
    int idx = 2;
    for (int i = 0; i < numVertices * 2; i++) {
      positions[i] = double.parse(lines[idx++]) * 0.2;
    }
    for (int i = 0; i < numVertices * 2; i++) {
      uvs[i] = double.parse(lines[idx++]) * (i % 2 == 0 ? _texture.width : _texture.height);
    }
    for (int i = 0; i < numVertices; i++) {
      colors[i] = int.parse(lines[idx++]);
    }
    for (int i = 0; i < numIndices; i++) {
      indices[i] = int.parse(lines[idx++]);
    }

    _vertices = ui.Vertices.raw(VertexMode.triangles, positions, textureCoordinates: uvs, colors: colors, indices: indices);
  }

  @override
  Color backgroundColor() => const Color(0xffcccccc);

  @override
  Future<void> onLoad() async {
    await _loadPaint();
    await _loadVertices();
    final rng = Random();
    for (int i = 0; i < 12; i++) {
      _positions.add(Vector2(rng.nextDouble() * size.x, rng.nextDouble() * size.y));
    }
  }

  @override
  void render(Canvas canvas) {
    for (var position in _positions) {
      canvas.save();
      canvas.translate(position.x, position.y);
      canvas.drawVertices(_vertices, painting.BlendMode.modulate, _paint);
      canvas.restore();
    }
  }
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Mali Crash',
      home: GameWidget(game: MaliCrash())
    );
  }
}

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>
See expected and actual results sections above.
</details>

### Logs

<details><summary>Logs</summary>

```console
➜  flutter-mali-crash git:(main) ✗ flutter run
Launching lib/main.dart on iPhone 14 Pro in debug mode...
Running Xcode build...
 └─Compiling, linking and signing...                      1,853ms
Xcode build done.                                            9.4s
[VERBOSE-2:FlutterDarwinContextMetalImpeller.mm(35)] Using the Impeller rendering backend.
Syncing files to device iPhone 14 Pro...                            39ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

A Dart VM Service on iPhone 14 Pro is available at: http://127.0.0.1:63740/ECaaw6ByFgw=/
The Flutter DevTools debugger and profiler on iPhone 14 Pro is available at: http://127.0.0.1:9103?uri=http://127.0.0.1:63740/ECaaw6ByFgw=/
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
➜  flutter-mali-crash git:(main) ✗ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.1, on macOS 13.0 22A380 darwin-arm64, locale en-AT)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] IntelliJ IDEA Community Edition (version 2022.3.3)
[✓] VS Code (version 1.78.2)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by jonahwilliams** [comment] 2023-05-24 20:00
The problem here is specifc to the extra blending step (it works fine if the colors are removed). We're first piecing together the texture and vertices, but then we don't correctly apply the right transforms to blend this back into the surface.

As an aside, using blend modes with drawVertices is going to be extremely expensive in general, and would be best avoided. Not that we won't fix this case, of course.

**Comment by badlogic** [comment] 2023-05-24 20:34
Thank you for the quick response to this.

Are there any docs on such performance gotchas with Impeller? Or can you suggest a less expensive path for rendering blended, textured, vertex colored triangle soups?

**Comment by badlogic** [comment] 2023-05-24 20:53
Apologies for the follow up: according to the [Impeller docs](https://github.com/flutter/engine/blob/main/impeller/docs/blending.md#pipeline-blends) the blend mode used in the repro (and other blend modes used by the "actual" code) are all "pipeline blend modes".

Are you saying that pipeline blend modes are extremely expensive as well?

**Comment by jonahwilliams** [comment] 2023-05-24 21:14
Pipeline blend modes are hardware supported in both Skia and impeller and are perfectly cromulent. The problem is specific to drawAtlas and drawVertices. By definition blending is done between a src and destination surface, however drawAtlas/drawVertices defines the colors from the paint parameter as source, and the colors from the vertices are considered the destination. Therefore, in order to perform the blend we have to first draw the colors to an offscreen texture and then blend the destination source onto that. That also requires us to take that offscreen texture and fill it back onto the surface. That's significantly more work per frame than if the textures are tinted offline into an atlas, as drawAtlas or drawVertices with no blending does not require any offscreen surfaces.

Technically this could be supported without an offscreen surface using specialized shaders, but with 29 blend modes its not something we'd like to do.

Happy to disucss more how you're specifically using color blending, I'd love to figure out if there is a better API we could offer here.

**Comment by jonahwilliams** [comment] 2023-05-24 22:00
Its hard for me to suggest an alternative, because I'm not sure exactly what all of the use cases are. Are you intentionally picing which blend mode to use? Have you used other sprite rendering APIs that worked differently? Any pointers would be great.

**Closed** 2023-05-24 22:57 UTC
Labels: a: gamedev

**Comment by badlogic** [comment] 2023-05-25 08:35
@jonahwilliams thank you for the explanation. It must have eluded me when I implemented rendering, that the `BlendMode` parameter actually governs blending of the vertex colors with the color from the `Paint` instead of the surface onto which the mesh is rendered. If I understand correctly, then the cost is similarly big with both the Skia and Impeller renderers, as both have to do offscreen rendering. If that's the case, then based on my micro-benchmarks for Skia, performance should be OK for pretty much all use cases on all platforms.

That said, it'd be great to have a less expensive way to render blended, textured, vertex colored triangle soups. I'll try to explain what we do in as short a way as possible.

I've written a [Spine](http://esotericsoftware.com/) runtime for [Flutter](https://github.com/EsotericSoftware/spine-runtimes/tree/4.1/spine-flutter), that can load and render Spine skeletons.

A Spine skeleton consists of one or more arbitrary meshes that are connected to a skeleton made of hierarchical bones. The bone transforms are animated, the meshes follow accordingly. Basic 2D skeletal animation + skinning. E.g. here's the skeleton from the repro with each mesh offset on the z-axis for visualization purposes.

![image](https://github.com/flutter/flutter/assets/514052/26ab8fb7-8efc-47fb-a3b7-322e07eca51e)

Each mesh of a skeleton has:
* A tint color, which is the same across all vertices of the mesh. The color includes an alpha component. In most of the APIs/engines/frameworks we support, we specifiy this color as a per vertex color. We also do this in our Flutter runtime for lack of an alternative.
* A texture, which provides additional per pixel color information. The texels also include an alpha component. The texel color is "modulated" with the tint color, usually in a shader, or by default by the API/engine/framework used for rendering.
* A blend mode, specifying how the source color (tint color * texel color) should be blended with the destination pixel color in the (usually onscreen) render target color buffer. Here are the blend modes we support:

```dart
enum BlendMode {
  normal(0, rendering.BlendMode.srcOver),
  additive(1, rendering.BlendMode.plus),
  multiply(2, rendering.BlendMode.modulate),
  screen(3, rendering.BlendMode.screen);
```

A mesh's tint color, texture, and blend mode is user definable in the Spine Editor. Most meshes of a skeleton will have a tint of `0xffffffff` and a `BlendMode.srcOver` blend mode. A subset of meshes will have tint colors that vary over time, e.g. to create a color change effect. Another subset will use the other 3 supported blend modes, most commonly the additive `BlendMode.plus` for special effects like particles.

For rendering, we first transform the bones according to the animation(s) that are being played back, compute vertex positions and tint colors of meshes, batch meshes based on blend mode and texture, and finally submit batched meshes to the rendering API.

We support a wide range of gaming frameworks and engines, which all offer more or less simple APIs to perform rendering as described above. The basic gist for most of them when rendering a (batched) mesh is:

* (Optionally) set a fragment shader that will combine the incoming vertex color (== mesh tint color, same for all vertices of a mesh) with the texel color for the fragment's UV coordinates. The output is RGB + alpha. Here's an example shader from our WebGL runtime. It's literally just `vertex color * texel color`:
```glsl
varying LOWP vec4 v_color;
varying vec2 v_texCoords;
uniform sampler2D u_texture;

void main () {
	gl_FragColor = v_color * texture2D(u_texture, v_texCoords);
}
```
* Set the blend mode, which defines how to blend the fragment output color with the render target's color buffer.
* Set the texture on a texture unit.
* Submit the (batched) mesh for rendering, with a vertex layout something like `{ vec2 position, vec2 uv, vec4 color }`

In the Flutter case, we use `Canvas.drawVertices()` with a `Vertices` instance containing one batched mesh with positions, per vertex colors and UV coordinates. The `Paint` is an `ImageShader` so texels get sourced from the texture image associated with the mesh. The blend mode we specify as a parameter to `drawVertices()` which I now realize is wrong, as it doesn't govern blending between the combined tint color + texel color with the rendering target pixel.

To boil it down, what we'd need is a `drawVertices()` method, where the `BlendMode` parameter governs blending between the fragment output color (vertex color * `Paint` color) with the rendering target color buffer.  That would imply that the vertex color and `Paint` color for a fragment are always multiplied like in the `WebGL` shader above. Alternatively, a second `BlendMode` parameter could be added that would work like in the current `drawVertices()` implementation, with `BlendMode.multiply` being a fast path that doesn't need a round trip through an offscreen texture.

**Comment by chinmaygarde** [comment] 2023-05-26 19:53
@jonahwilliams You mentioned during the weekly sync that the fix for this needs to be cherry-picked into 3.10-candidate.2. Is this still the case?

**Comment by jonahwilliams** [comment] 2023-05-27 00:45
@chinmaygarde yes

**Comment by jonahwilliams** [comment] 2023-05-27 00:49
@badlogic Thanks for the additional details on this. Since it sounds like Spine itself describes the per-vertex color blending with a BlendMode enum, we're likely going to need to improve the performance of this API by eliding the offscreen pass. If you only needed to blend one specific way, I was going to suggest an alternative API using the fragment shaders - but it occurs to me that we can't actually support UV mapping in user authored fragment shaders yet.

As for blending onto the canvas, this is described by the blend mode parameter of the Paint passed to drawVertices. So you should be able to do this today, but I think that its quite confusing how these methods have two!

**Comment by jonahwilliams** [comment] 2023-05-27 00:50
Though I would suggest that you should elide the colors array if possible. Anything we do here will still be marginally more expensive than not providing the colors at all

**Comment by badlogic** [comment] 2023-06-02 12:03
@jonahwilliams thanks a lot for your answer. I'll play around with improving the default case of meshes with vertex color 0xffffffff based on your suggestion.
