### ISSUE TITLE
IOS can not be built. error: 'FirebaseCore/FIRLogger.h' file not found

### ISSUE THREAD

**Issue by miamee** [flutter/flutter#75620] opened 2021-02-08 10:45 UTC
<img width="1289" alt="Screen Shot 2021-02-08 at 5 42 27 AM" src="https://user-images.githubusercontent.com/76895083/107209263-92af2d00-69d0-11eb-8c57-548f1e5bd098.png">
error: 'FirebaseCore/FIRLogger.h' file not found. IOS can not be built. How to solve this error?

**Comment by TahaTesser** [comment] 2021-02-08 10:53
Hi @miamee 
Please try the following [solution](https://github.com/flutter/flutter/issues/70895#issuecomment-748331277)
If the problem persists,  From what I can see, the issue is related to a FlutterFire plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-02-08 10:53 UTC
