### ISSUE TITLE
[tool_crash] Invalid argument(s): Cannot find executable for C:\Users\Giulianna\AndroidStudioProjects\vamos\android\gradlew.bat.

### ISSUE THREAD

**Issue by hanzen310579** [flutter/flutter#61547] opened 2020-07-15 15:02 UTC
## Command
```
flutter --no-color run --machine --track-widget-creation --device-id=emulator-5554 --dart-define=flutter.inspector.structuredErrors=true lib\main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ArgumentError: Invalid argument(s): Cannot find executable for C:\Users\Giulianna\AndroidStudioProjects\vamos\android\gradlew.bat.
```
#0      _getExecutable (package:process/src/interface/local_process_manager.dart:127:5)
#1      LocalProcessManager.start (package:process/src/interface/local_process_manager.dart:43:30)
#2      _DefaultProcessUtils.start (package:flutter_tools/src/base/process.dart:462:28)
#3      _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart:480:35)
#4      buildGradleApp (package:flutter_tools/src/android/gradle.dart:384:35)
#5      buildGradleApp (package:flutter_tools/src/android/gradle.dart:423:19)
#6      _rootRunUnary (dart:async/zone.dart:1192:38)
#7      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#8      _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#9      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#10     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#11     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#12     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
#13     _rootRun (dart:async/zone.dart:1184:13)
#14     _CustomZone.run (dart:async/zone.dart:1077:19)
#15     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
#16     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
#17     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#18     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#19     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
```
```
[✓] Flutter (Channel stable, v1.17.5, on Microsoft Windows [versÃ£o 10.0.18362.900], locale pt-BR)
    • Flutter version 1.17.5 at C:\src\flutter
    • Framework revision 8af6b2f038 (2 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Users\Giulianna\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = C:\Program Files\Android\Android Studio\jre
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions.

[✓] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code, 64-bit edition (version 1.47.0)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.12.2

[✓] Connected device (1 available)
    • sdk gphone x86 arm • emulator-5554 • android-x86 • Android 11 (API 30) (emulator)

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 8af6b2f038c1172e61d418869363a28dffec3cb4

**Comment by VladyslavBondarenko** [comment] 2020-07-15 15:29
Duplicate of https://github.com/flutter/flutter/issues/56975

**Closed by VladyslavBondarenko** 2020-07-15 15:29 UTC
