### ISSUE TITLE
flutter run --route=/signup doesn't work

### ISSUE THREAD

**Issue by jerryzhoujw** [flutter/flutter#46065] opened 2019-12-04 09:18 UTC
## Steps to Reproduce

I have read the document of `class Navigator extends StatefulWidget`.

In it's comment there's a demo about how to use `flutter run --route=/signup`.

1. Bellow is the code, and I include a `NavigatorObserver` to log the route change.

2. Run it with `flutter run --route=/signup` in terminal, but it go to route `/`, not to `signup`.

PS: by the way, I don't know how to debug this issue beside `NavigatorObserver`, any document mentioned on this ?

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Code Sample for Navigator',
      // MaterialApp contains our top-level Navigator
      // initialRoute: '/',
      routes: {
        '/': (BuildContext context) => HomePage(),
        '/signup': (BuildContext context) => SignUpPage(),
      },
      navigatorObservers: [MyNavigatorObserver()],
    );
  }
}

class HomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return DefaultTextStyle(
      style: Theme.of(context).textTheme.display1,
      child: Container(
        color: Colors.white,
        alignment: Alignment.center,
        child: Text('Home Page'),
      ),
    );
  }
}

class CollectPersonalInfoPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return DefaultTextStyle(
      style: Theme.of(context).textTheme.display1,
      child: GestureDetector(
        onTap: () {
          // This moves from the personal info page to the credentials page,
          // replacing this page with that one.
          Navigator.of(context)
              .pushReplacementNamed('signup/choose_credentials');
        },
        child: Container(
          color: Colors.lightBlue,
          alignment: Alignment.center,
          child: Text('Collect Personal Info Page'),
        ),
      ),
    );
  }
}

class ChooseCredentialsPage extends StatelessWidget {
  const ChooseCredentialsPage({
    this.onSignupComplete,
  });

  final VoidCallback onSignupComplete;

  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      onTap: onSignupComplete,
      child: DefaultTextStyle(
        style: Theme.of(context).textTheme.display1,
        child: Container(
          color: Colors.pinkAccent,
          alignment: Alignment.center,
          child: Text('Choose Credentials Page'),
        ),
      ),
    );
  }
}

class SignUpPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    // SignUpPage builds its own Navigator which ends up being a nested
    // Navigator in our app.
    return Navigator(
      initialRoute: 'signup/personal_info',
      onGenerateRoute: (RouteSettings settings) {
        WidgetBuilder builder;
        switch (settings.name) {
          case 'signup/personal_info':
            // Assume CollectPersonalInfoPage collects personal info and then
            // navigates to 'signup/choose_credentials'.
            builder = (BuildContext _) => CollectPersonalInfoPage();
            break;
          case 'signup/choose_credentials':
            // Assume ChooseCredentialsPage collects new credentials and then
            // invokes 'onSignupComplete()'.
            builder = (BuildContext _) => ChooseCredentialsPage(
                  onSignupComplete: () {
                    // Referencing Navigator.of(context) from here refers to the
                    // top level Navigator because SignUpPage is above the
                    // nested Navigator that it created. Therefore, this pop()
                    // will pop the entire "sign up" journey and return to the
                    // "/" route, AKA HomePage.
                    Navigator.of(context).pop();
                  },
                );
            break;
          default:
            throw Exception('Invalid route: ${settings.name}');
        }
        return MaterialPageRoute(builder: builder, settings: settings);
      },
    );
  } 
}

class MyNavigatorObserver extends NavigatorObserver {
  List<String> routeStack = List();

  void didPush(Route<dynamic> route, Route<dynamic> previousRoute) {
    final _route = route.settings.name;
    final _previousRoute =
        previousRoute != null ? previousRoute.settings.name : 'null';
    routeStack.add(_route);
    debugPrint('============= didPush start ===========================');
    debugPrint('previousRoute: $_previousRoute, route:$_route');
    debugPrint('----------------------------------------');
    debugPrint('routeStack:$routeStack');
    debugPrint('============= didPush end ===========================');
  }

  void didPop(Route<dynamic> route, Route<dynamic> previousRoute) {
    final _route = route.settings.name;
    final _previousRoute = previousRoute.settings.name;
    routeStack.removeLast();
    debugPrint('============= didPop start ===========================');
    debugPrint('previousRoute: $_previousRoute, route:$_route');
    debugPrint('----------------------------------------');
    debugPrint('routeStack:$routeStack');
    debugPrint('============= didPop end ===========================');
  }

  @override
  void didRemove(Route route, Route previousRoute) {
    final _route = route.settings.name;
    // NOTE(jerry): don't make sense, previousROute should not be null,
    //       but it's null here. To check this later.
    final _previousRoute = previousRoute?.settings?.name ?? 'null';
    routeStack.removeLast();
    debugPrint('================ didRemove start ========================');
    debugPrint('previousRoute: $_previousRoute, route:$_route');
    debugPrint('----------------------------------------');
    debugPrint('routeStack:$routeStack');
    debugPrint('================ didRemove end ========================');
  }

  @override
  void didReplace({Route newRoute, Route oldRoute}) {
    final _newRoute = newRoute.settings.name;
    final _oldRoute = oldRoute.settings.name;
    routeStack.removeLast();
    routeStack.add(_newRoute);
    debugPrint('================ didReplace start ========================');
    debugPrint('oldRoute: $_oldRoute, newRoute:$_newRoute');
    debugPrint('----------------------------------------');
    debugPrint('routeStack:$routeStack');
    debugPrint('================ didReplace end ========================');
  }
}
```

**Target Platform:**  Mac
**Target OS version/browser:** iOS 13.2.2
**Devices:** iOS 13.2.2 Simulator

## Logs

```
flutter: ============= didPush start ===========================
flutter: previousRoute: null, route:/
flutter: ----------------------------------------
flutter: routeStack:[/]
flutter: ============= didPush end ===========================
```

```
Analyzing route_navigation_example...
No issues found! (ran in 2.3s)
```

```
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.15.1 19B88, locale en-CN)
    • Flutter version 1.9.1+hotfix.6 at /Users/jerryzhou/Documents/code/flutter/sdk/flutter
    • Framework revision 68587a0916 (3 months ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0


[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/jerryzhou/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 34.0.2
    • Dart plugin version 183.5901
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✗] Cannot determine if IntelliJ is installed
    ✗ Directory listing failed

[✓] VS Code (version 1.40.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.6.0

[✓] Connected device (1 available)
    • iPhone 11 Pro Max • 1363D0C3-E3A1-41AF-A2DB-B8E1D82DBABF • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-2
      (simulator)

! Doctor found issues in 2 categories.
```

**Comment by jerryzhoujw** [comment] 2019-12-05 10:57
https://github.com/flutter/flutter/issues/10813

**Comment by ahan** [comment] 2020-03-20 11:46
Same issue, `--route=/signup` not working.
Is this bug fixed? @Hixie

**Comment by awhitford** [comment] 2020-07-03 19:31
I can't seem to get this to work either.  (And maybe this is why my Dynamic Links are pulling up the home screen instead of the screen I want.) 😭

**Comment by awhitford** [comment] 2020-07-03 20:54
Is the CLI usage supposed to be `--route=/page` or `--route /page`?

**Comment by pedromassangocode** [comment] 2020-09-16 12:59
Hi @jerryzhoujw 
I noticed that you were testing on a iOS device but this feature is currently supported on Android devices only.

I'm closing this as a duplicate of https://github.com/flutter/flutter/issues/4703. Please follow up on that issue for updates.

**Closed by pedromassangocode** 2020-09-16 12:59 UTC
Labels: f: routes, framework

**Comment by awhitford** [comment] 2020-09-18 03:30
"Android devices only"?  Where is that documented?  What about web, macos, linux, windows, etc.?

**Comment by pedromassangocode** [comment] 2020-09-18 06:47
There is an open issue to add support for web https://github.com/flutter/flutter/issues/58980. It is not documented and it should be. I'm not sure for other platforms.
