### ISSUE TITLE
SliverPersistentHeaderDelegate impossible to have dynamic min/max extent bug

### ISSUE THREAD

**Issue by BerndWessels** [flutter/flutter#19843] opened 2018-07-26 22:36 UTC
The problem:

It seems that it is impossible for the `SliverPersistentHeaderDelegate` to return a `minExtent` or `maxExtent` based on its content.

The scenario:

Imagine you have a `SliverPersistentHeaderDelegate` that contains a `Text Widget` or something else that might vary in height based on the applications state.

Now you want the `minExtent` to make sure that there is just enough space for this dynamic content.

This is not possible because the `minExtent getter` is called before the `SliverPersistentHeaderDelegate` builds, so there is no way to know what the correct `minExtent` will be.

The solution proposal:

There should be a way to measure the height of the dynamic content that gets rendered in the `SliverPersistentHeaderDelegate` and then add that into the calculation of `minExtent`.

**Comment by jmihelcic** [comment] 2019-08-07 08:55
Any progress on this issue?

**Comment by Cliffus** [comment] 2020-02-24 13:37
I came up with a dirty solution for this issue, feel free to use it in your project:
https://stackoverflow.com/a/60377088/1128053

**Comment by darshankawar** [comment] 2020-08-26 12:51
Hi @BerndWessels,
Can you please confirm if you still experience the issue on latest stable or master version ? Would be great if you reply with latest behavior.
Thanks.

**Comment by darshankawar** [comment] 2020-09-16 09:57
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by darshankawar** 2020-09-16 09:57 UTC
Labels: customer: crowd, f: scrolling, framework, waiting for customer response

**Comment by chris-rutkowski** [comment] 2020-09-16 11:01
@darshankawar please don't close this issue.  
The issue is not a problem but rather an inconvenience.

As @BerndWessels said we cannot simply just return a Widget and make the framework do all the heavy work. Instead, we need to provide some height values. 
This is very difficult if the Widget contains text - text can be completely different in many circumstances:
- dynamic text
- translated text
- user changed the font size in accessibility settings of phone

**Comment by lukaspili** [comment] 2020-09-16 16:21
At this point, we have to manually layout dynamic text in order to measure the height and provide it to `SliverPersistentHeaderDelegate`. It's cumbersome, error prone and could be automatically done by the widget or a helper.
