### ISSUE TITLE
Lots of errors from flutter run + android emulator

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#9864] opened 2017-05-06 15:54 UTC
Not sure if this is normal, but using `flutter run` and an android emulator, I see a never-ending repeat of the following, anytime something interacts with the emulator screen:

```
E/libGLESv2_swiftshader( 3117): badness: unimplemented: IsColorRenderable vendor/transgaming/swiftshader_source/src/OpenGL/libGLESv2/utilities.cpp:1059
E/swiftshader( 3117): AndroidEnterDebugger
E/libGLESv2_swiftshader( 3117): badness: unimplemented: IsColorRenderable vendor/transgaming/swiftshader_source/src/OpenGL/libGLESv2/utilities.cpp:1059
```

and, after I type 'r' in the console, I see:

```
Initializing hot reload...
E/libGLESv2_swiftshader( 3117): badness: unimplemented: IsColorRenderable vendor/transgaming/swiftshader_source/src/OpenGL/libGLESv2/utilities.cpp:1059
E/swiftshader( 3117): AndroidEnterDebugger
E/libGLESv2_swiftshader( 3117): badness: unimplemented: IsColorRenderable vendor/transgaming/swiftshader_source/src/OpenGL/libGLESv2/utilities.cpp:1059
E/swiftshader( 3117): AndroidEnterDebugger
E/libGLESv2_swiftshader( 3117): badness: unimplemented: IsColorRenderable vendor/transgaming/swiftshader_source/src/OpenGL/libGLESv2/utilities.cpp:1059
E/swiftshader( 3117): AndroidEnterDebugger
Reloaded 412 of 427 libraries in 1,177ms.
E/libGLESv2_swiftshader( 3117): badness: unimplemented: IsColorRenderable vendor/transgaming/swiftshader_source/src/OpenGL/libGLESv2/utilities.cpp:1059
E/swiftshader( 3117): AndroidEnterDebugger
E/libGLESv2_swiftshader( 3117): badness: unimplemented: IsColorRenderable vendor/transgaming/swiftshader_source/src/OpenGL/libGLESv2/utilities.cpp:1059
E/swiftshader( 3117): AndroidEnterDebugger
E/libGLESv2_swiftshader( 3117): badness: unimplemented: IsColorRenderable vendor/transgaming/swiftshader_source/src/OpenGL/libGLESv2/utilities.cpp:1059
E/swiftshader( 3117): AndroidEnterDebugger
```

Is this normal, or is this from the combo of android emulator and Flutter?

Impact on the developer: if anything else is ever printed to the console, it will be lost :) Also, it's not clear I can type 'r' because there's no "prompt" and it looks like a stream of log/error messages.

FWIW, this may or may not be useful. This is the output from running the emulator:

```
C:\Users\sethladd\AppData\Local\Android\Sdk\tools>emulator -skin 1080x1920 -avd Foo1
emulator: WARNING: encryption is off
Hax is enabled
Hax ram_size 0x40000000
HAX is working and emulator runs in fast virt mode.
```

**Comment by eseidelGoogle** [comment] 2017-05-08 19:46
@chinmaygarde or @jason-simmons would know.

**Comment by chinmaygarde** [comment] 2017-05-08 19:49
That emulator seems to be implementing OpenGL ES support using SwiftShader which is complaining about unimplemented features. The logs don't originate from the engine.

**Comment by sethladd** [comment] 2017-05-08 21:41
Are these errors benign ? Should we hide them?

Or, did I do something wrong when I setup my AVD?

**Comment by chinmaygarde** [comment] 2017-05-08 21:45
Yes, those errors should be benign. Its just that some other library is logging to logcat.

**Comment by Hixie** [comment] 2017-05-08 23:04
Is 3117 our pid, in these logs?

**Comment by zoechi** [comment] 2018-12-18 14:22
Is this issue still relevant?

**Comment by jeanpoelie** [comment] 2018-12-21 10:59
I have encountered this issue today.
Steps to reproduce:
Start Visual Studio 2017
Create a Xamarin Forms project
Start emulator.

**Comment by Hixie** [comment] 2019-01-16 00:34
We're just going to close this because it's not clear what exactly the issue here is.

@jeanpoelie If you do see this, please file a new bug with exact steps to reproduce -- when you file the bug, it'll prompt you for information we need (like your flutter version). Thanks!

**Comment by Hixie** [comment] 2019-01-16 00:34
We're just going to close this because it's not clear what exactly the issue here is.

@jeanpoelie If you do see this, please file a new bug with exact steps to reproduce -- when you file the bug, it'll prompt you for information we need (like your flutter version). Thanks!

**Closed by Hixie** 2019-01-16 00:34 UTC
Labels: e: device-specific, will need additional triage, ▣ platform-android
