### ISSUE TITLE
[tool_crash] FileSystemException: writeFrom failed, OS Error: No space left on device, errno = 28

### ISSUE THREAD

**Issue by 1510844487** [flutter/flutter#102195] opened 2022-04-20 06:55 UTC
## Command
```
flutter --no-color pub get
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: writeFrom failed, OS Error: No space left on device, errno = 28
```
#0      _RandomAccessFile.writeFromSync (dart:io/file_impl.dart:873:7)
#1      _File.writeAsBytesSync (dart:io/file_impl.dart:606:14)
#2      ForwardingFile.writeAsBytesSync (package:file/src/forwarding/forwarding_file.dart:124:16)
#3      copyDirectory (package:flutter_tools/src/base/file_system.dart:136:15)
#4      copyDirectory (package:flutter_tools/src/base/file_system.dart:142:7)
#5      copyDirectory (package:flutter_tools/src/base/file_system.dart:142:7)
#6      IosProject._copyEngineArtifactToProject (package:flutter_tools/src/xcode_project.dart:415:7)
#7      IosProject._regenerateFromTemplateIfNeeded (package:flutter_tools/src/xcode_project.dart:397:7)
<asynchronous suspension>
#8      IosProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/xcode_project.dart:315:5)
<asynchronous suspension>
#9      FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:321:7)
<asynchronous suspension>
#10     PackagesGetCommand.runCommand (package:flutter_tools/src/commands/packages.dart:177:5)
<asynchronous suspension>
#11     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1161:27)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#13     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 2.10.4, on Mac OS X 10.15.5 19F101 darwin-x64, locale zh-Hans-CN)
    • Flutter version 2.10.4 at /Users/wuguofa/flutter/sdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (4 weeks ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/wuguofa/Library/Android/sdk
    • Platform android-31, build-tools 30.0.3
    • ANDROID_HOME = /Users/wuguofa/Library/Android/sdk
    • Java binary at: /Users/wuguofa/Downloads/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ✗ Flutter requires a minimum Xcode version of 12.3.
      Download the latest version or update via the Mac App Store.
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Users/wuguofa/Downloads/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] IntelliJ IDEA Community Edition (version 2021.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.65.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.32.0

[✓] Connected device (2 available)
    • Redmi Note 8 (mobile) • 881390e4 • android-arm64  • Android 9 (API 28)
    • Chrome (web)          • chrome   • web-javascript • Google Chrome 100.0.4896.127

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: module
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: true
**Plugin**: false
**Android package**: com.shuidi.flutteragent
**iOS bundle identifier**: com.shuidi.flutteragent
**Creation channel**: stable
**Creation framework version**: 0b8abb4724aa590dd0f429683339b1e045a1594d
### Plugins
audioplayers-0.20.1
flutter_boost-03628114fc150dc1ffdbe4fd8ad01639aa1eebe8
package_info-2.0.2
package_info_plus-09c7aea0cf4e2cd1edd1ae9f8dff282b895babb2
package_info_plus_linux-1.0.5
package_info_plus_macos-1.3.0
package_info_plus_web-1.0.5
package_info_plus_windows-1.0.5
path_provider-2.0.9
path_provider_android-2.0.12
path_provider_ios-2.0.8
path_provider_linux-2.1.5
path_provider_macos-2.0.5
path_provider_windows-2.0.5
flutter
shared_preferences-2.0.13
shared_preferences_android-2.0.11
shared_preferences_ios-2.1.0
shared_preferences_linux-2.1.0
shared_preferences_macos-2.0.3
shared_preferences_web-2.0.3
shared_preferences_windows-2.1.0
sqflite-2.0.2+1
url_launcher-6.0.20
url_launcher_android-6.0.15
url_launcher_ios-6.0.15
url_launcher_linux-3.0.0
url_launcher_macos-3.0.0
url_launcher_web-2.0.9
url_launcher_windows-3.0.0

**Comment by darshankawar** [comment] 2022-04-20 07:51
Closing this as a duplicate of https://github.com/flutter/flutter/issues/54213

**Closed by darshankawar** 2022-04-20 07:51 UTC
Labels: in triage
