### ISSUE TITLE
Draggables should have onDragUpdate returning currrent drag offset

### ISSUE THREAD

**Issue by emvaized** [flutter/flutter#56818] opened 2020-05-10 07:33 UTC
## Use case

Currently `Draggable` and `LongPressDraggable` widgets can provide `onDragStarted`, `onDragEnd`, `onDragComplete` and `onDragCancel` callbacks, which can trigger some actions on start or end of drag movement. 
Those are very great, but there's no option to track current `feedback`'s offset during drag, before the release of finger.

## Proposal
`Draggable` and `LongPressDraggable` widgets should provide the ability to set `onDragUpdate` callback, which will receive `details` with `globalPosition` and `delta` included -- the same as GestureDetector's `onPanUpdate` callback.

Desired behavior:
```
LongPressDraggable(
   feedback: Icon(Icons.add),
    onDragEnd: (details) => print(details.offset.dx),
    onDragUpdate: (details) => print(details.offset.dy)  // <-- this is impossible now
);
```

**Comment by TahaTesser** [comment] 2020-05-11 12:18
duplicate of [#39490](https://github.com/flutter/flutter/issues/39490)

**Closed by TahaTesser** 2020-05-11 12:18 UTC
