### ISSUE TITLE
MultiDragGestureRecognizer forces to provide debugOwner param which should be optional and only for debuggin purposes

### ISSUE THREAD

**Issue by ethael** [flutter/flutter#67119] opened 2020-10-02 08:33 UTC
Attribute debugOwner was not required In previous flutter versions, but it is required in 1.22 (not sure when it become required)
MultiDragGestureRecognizer does not use it internally, it only uses it to fill the super constructor
GestureRecognizer which is a super class of the MultiDragGestureRecognizer does not require debugOwner param
Therefore it should be an optional parameter in MultiDragGestureRecognizer too

**Comment by pedromassangocode** [comment] 2020-10-02 10:04
Hi @ethael 
`MultiDragGestureRecognizer` is an abstract class and its descendants may or may not provide it.

Does it broke anything in your code? Can you provide a sample code that worked before and does not works now?
I'm trying to understand if this was really a breaking change for customer's code.
Thank you

**Comment by ethael** [comment] 2020-10-02 10:32
Hi there. I have been implementing this class in several projects. My implementations had no constructor, as it was not needed. After flutter upgrade I had to add those constructors only to call super constructor providing a debugOwner parameter set to null.

From my point of view it really doesn't matter if descendant can do it like I did to protect the rest of application code. That param is internally (in MultiDragGestureRecognizer) not used and its super class GestureRecognizer does not force it as required, so it clearly a mistake. Either it should be optional, or there should at least be comment about why it is required (maybe for some future plans... duno)

**Comment by pedromassangocode** [comment] 2020-10-02 11:07
Hi @ethael 
Can you please provide a sample code that worked before and does not works now?
Thank you

**Comment by ethael** [comment] 2020-10-02 12:41
```
class Recognizer extends MultiDragGestureRecognizer<VerticalPointerState> {
  @override
  VerticalPointerState createNewPointerState(PointerDownEvent event) {
    return VerticalPointerState(event.position);
  }

  @override
  String get debugDescription => 'Vertical recognizer';
}

class VerticalPointerState extends MultiDragPointerState {
  VerticalPointerState(Offset initialPosition) : super(initialPosition);
}

```

**Comment by pedromassangocode** [comment] 2020-10-02 13:51
Thanks, this seems to be valid however, this is currently solved in the latest master channel as you can see in the images bellow.

| Stable channel |
| ------------------- |
![Screen Shot 2020-10-02 at 14 45 59](https://user-images.githubusercontent.com/67424416/94930257-0d65ba00-04be-11eb-9cf8-cfdfc006ee15.png)

| Master channel |
| ------------------- |
| ![Screen Shot 2020-10-02 at 14 42 21](https://user-images.githubusercontent.com/67424416/94930365-338b5a00-04be-11eb-857c-67b9d77f6840.png) |

Closing as the issue is already fixed on latest master channel.

<details><summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.23.0-8.0.pre.105, on Mac OS X 10.15.6 19G2021 x86_64, locale en)
    • Flutter version 1.23.0-8.0.pre.105 at /Users/pedromassango/dev/SDKs/flutter_master
    • Framework revision f1013e6873 (12 hours ago), 2020-10-02 09:50:33 +0800
    • Engine revision 0522ff22cc
    • Dart version 2.11.0 (build 2.11.0-181.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0, Build version 12A7209
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2020.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin installed
    • Dart plugin version 202.7319.5

[✓] VS Code (version 1.48.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

[✓] Connected device (4 available)
    • Android SDK built for x86 64 (mobile) • emulator-5554 • android-x64    • Android 9 (API 28)
      (emulator)
    • macOS (desktop)                       • macos         • darwin-x64     • Mac OS X 10.15.6 19G2021
      x86_64
    • Web Server (web)                      • web-server    • web-javascript • Flutter Tools
    • Chrome (web)                          • chrome        • web-javascript • Google Chrome 85.0.4183.121

• No issues found!

```
</details>

**Closed by pedromassangocode** 2020-10-02 13:51 UTC
Labels: in triage
