### ISSUE TITLE
[Impeller][Android] Font is bolder/thicker after upgrading to stable 3.24.0

### ISSUE THREAD

**Issue by liuzehnhang** [flutter/flutter#153677] opened 2024-08-19 07:34 UTC
### Steps to reproduce

After upgrading Flutter 3.24.0, the font size of FontWeighta.w400 on Android has become thicker

### Expected results

After upgrading Flutter 3.24.0, the font size of FontWeighta.w400 on Android has become thicker

### Actual results

After upgrading Flutter 3.24.0, the font size of FontWeighta.w400 on Android has become thicker

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by danagbemava-nc** [comment] 2024-08-19 13:38
Hi @liuzehnhang, please provide a complete minimal reproducible code sample so that we can properly investigate this. 

Are you using impeller on android?

What version of flutter were you using prior to 3.24.0? 

Please also include some screenshots and the output of `flutter doctor -v`

In the future, please do not file an issue without the information requested in the template. 

Thank you

**Comment by liuzehnhang** [comment] 2024-08-20 08:16
My previous version was 3.22.3
![WeChat1ddd7f71ef87d31d6600b02f7722300b](https://github.com/user-attachments/assets/455f8131-08bc-439e-9aeb-e6a6f6432d4b)

![WechatIMG304](https://github.com/user-attachments/assets/d272e551-da59-4c0a-b69f-ed2b7e40af04)
![WechatIMG305](https://github.com/user-attachments/assets/372a402b-bc24-4a1e-91b8-16b06eec03d7)

**Comment by liuzehnhang** [comment] 2024-08-20 09:34
@danagbemava-nc

**Comment by tihimsm** [comment] 2024-08-21 06:19
same issue on Japanese Hiragana ,Katakana and Kanji.

**Comment by danagbemava-nc** [comment] 2024-08-21 06:34
Hi @liuzehnhang, @tihimsm, are you seeing this with specific fonts or are all fonts affected? Can either of you provide a complete minimal reproducible code sample so that we can properly investigate this? 

Thank you

**Comment by liuzehnhang** [comment] 2024-08-21 07:29
The issue has been temporarily resolved，MaterialApp   add " textTheme:  GoogleFonts.poppinsTextTheme() " , change font

**Comment by danagbemava-nc** [comment] 2024-08-22 06:24
Hi @liuzehnhang, what font were you using initially?

**Comment by liuzehnhang** [comment] 2024-08-22 08:11
@danagbemava-nc    Initially not set, it should be the default font

**Comment by liuzehnhang** [comment] 2024-08-22 08:21
My phone is Xiaomi 13

**Comment by naivetoby** [comment] 2024-08-22 22:42
### Bug Report: Flutter Default Font (Roboto) Not Applied on Xiaomi Hyper OS and Color OS after Upgrading to Flutter 3.24.0

#### Issue Description:
After upgrading to Flutter 3.24.0, the default font (Roboto) is not applied correctly on certain Android systems, specifically:

- **Xiaomi Hyper OS**: The font weight is incorrectly displayed as bold.
- **Color OS**: The font weight appears lighter than expected.

When the Roboto font is not applied, the system default font is used instead.

#### Steps to Fix:
1. In your `MaterialApp`, specify the following `fontFamilyFallback`:

   ```dart
   fontFamilyFallback: Platform.isIOS
       ? ['.AppleSystemUIFont', 'PingFang SC']
       : ['Roboto'],
   ```

2. Add the Roboto font in `pubspec.yaml`:

   ```yaml
   flutter:
     uses-material-design: true
     fonts:
       - family: Roboto
         fonts:
           - asset: fonts/Roboto-Black.ttf
           - asset: fonts/Roboto-BlackItalic.ttf
           - asset: fonts/Roboto-Bold.ttf
           - asset: fonts/Roboto-BoldItalic.ttf
           - asset: fonts/Roboto-Italic.ttf
           - asset: fonts/Roboto-Light.ttf
           - asset: fonts/Roboto-LightItalic.ttf
           - asset: fonts/Roboto-Medium.ttf
           - asset: fonts/Roboto-MediumItalic.ttf
           - asset: fonts/Roboto-Regular.ttf
           - asset: fonts/Roboto-Thin.ttf
           - asset: fonts/Roboto-ThinItalic.ttf
   ```

3. Run the app on devices with Xiaomi Hyper OS or Color OS.

#### Observed Behavior:
- **Xiaomi Hyper OS**: The issue is resolved by manually importing the Roboto font.
- **Color OS**: The app still uses the system default font, and the issue persists despite the manual font import.

Additionally, if the system default font is changed in the device settings, the app's font also changes accordingly on these systems.

#### Expected Behavior:
- The default Roboto font should be applied consistently across all Android systems.
- Changes to the system default font in the device settings should not affect the app's font when the Roboto font is specified.

#### Flutter Version:
- Flutter 3.24.0

**Comment by danagbemava-nc** [comment] 2024-08-23 07:22
Hi @liuzehnhang, @naivetoby, what versions of android are your devices running?

**Comment by liuzehnhang** [comment] 2024-08-23 08:43
![WechatIMG308](https://github.com/user-attachments/assets/3347bb27-7ccc-42d2-9d7f-6109c89bc477)

**Comment by liuzehnhang** [comment] 2024-08-23 08:43
@danagbemava-nc

**Comment by danagbemava-nc** [comment] 2024-08-26 07:44
Hi @liuzehnhang, one more thing, did you have impeller enabled on android or were you using SKIA?

**Comment by naivetoby** [comment] 2024-08-26 08:11
> Hi @liuzehnhang, @naivetoby, what versions of android are your devices running?

Android 14
impeller enabled

**Comment by liuzehnhang** [comment] 2024-08-27 01:37
> Hi @liuzehnhang, one more thing, did you have impeller enabled on android or were you using SKIA?

impeller enabled

**Comment by danagbemava-nc** [comment] 2024-08-27 07:23
Hi @naivetoby, @liuzehnhang 1 more thing, can you check on the master channel to see if you still experience this issue?

**Comment by naivetoby** [comment] 2024-08-27 08:44
I confirm the problem has been fixed on Flutter master channel.

- **Xiaomi Hyper OS with Android 14**
- **Color OS with Android 14**

flutter doctor -v
```shell
[✓] Flutter (Channel master, 3.25.0-1.0.pre.147, on macOS 14.6.1 23G93 darwin-x64, locale zh-Hans-CN)
    • Flutter version 3.25.0-1.0.pre.147 on channel master at /Users/toby/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 99dc3beaf4 (6 hours ago), 2024-08-26 22:10:32 -0400
    • Engine revision b41ca79092
    • Dart version 3.6.0 (build 3.6.0-175.0.dev)
    • DevTools version 2.39.0-dev.15

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/toby/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Users/toby/Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Android Studio (version 2024.1)
    • Android Studio at /Users/toby/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)

[✓] IntelliJ IDEA Ultimate Edition (version 2024.2.0.2)
    • IntelliJ at /Users/toby/Applications/IntelliJ IDEA Ultimate.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin version 242.20629

[✓] VS Code (version 1.92.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.94.0

[✓] Connected device (1 available)
    • Toby 的 iPhone (mobile) • 00008110-00042D36116B801E • ios • iOS 17.6.1 21G93

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

**Comment by liuzehnhang** [comment] 2024-08-27 09:00
> I confirm the problem has been fixed on Flutter master channel.我确认 Flutter 主通道上的问题已修复。
> 
> * **Xiaomi Hyper OS with Android 14搭载 Android 14 的小米 Hyper OS**
> * **Color OS with Android 14带有 Android 14 的 Color OS**
> 
> flutter doctor -v 颤振医生 -V
> 
> ```shell
> [✓] Flutter (Channel master, 3.25.0-1.0.pre.147, on macOS 14.6.1 23G93 darwin-x64, locale zh-Hans-CN)
>     • Flutter version 3.25.0-1.0.pre.147 on channel master at /Users/toby/flutter
>     • Upstream repository https://github.com/flutter/flutter.git
>     • Framework revision 99dc3beaf4 (6 hours ago), 2024-08-26 22:10:32 -0400
>     • Engine revision b41ca79092
>     • Dart version 3.6.0 (build 3.6.0-175.0.dev)
>     • DevTools version 2.39.0-dev.15
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
>     • Android SDK at /Users/toby/Library/Android/sdk
>     • Platform android-34, build-tools 34.0.0
>     • Java binary at: /Users/toby/Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
>     • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)
>     • All Android licenses accepted.
> 
> [✓] Xcode - develop for iOS and macOS (Xcode 15.4)
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • Build 15F31d
>     • CocoaPods version 1.15.2
> 
> [✓] Android Studio (version 2024.1)
>     • Android Studio at /Users/toby/Applications/Android Studio.app/Contents
>     • Flutter plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/9212-flutter
>     • Dart plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/6351-dart
>     • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)
> 
> [✓] IntelliJ IDEA Ultimate Edition (version 2024.2.0.2)
>     • IntelliJ at /Users/toby/Applications/IntelliJ IDEA Ultimate.app
>     • Flutter plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/9212-flutter
>     • Dart plugin version 242.20629
> 
> [✓] VS Code (version 1.92.2)
>     • VS Code at /Applications/Visual Studio Code.app/Contents
>     • Flutter extension version 3.94.0
> 
> [✓] Connected device (1 available)
>     • Toby 的 iPhone (mobile) • 00008110-00042D36116B801E • ios • iOS 17.6.1 21G93
> 
> [✓] Network resources
>     • All expected network resources are available.
> 
> • No issues found!
> ```
Not completely fixed, there are still issues with displaying bold fonts   （FontWeight-w600 has thicker Chinese characters

）
![WechatIMG319](https://github.com/user-attachments/assets/619594c3-4424-4908-baeb-2de25975c0e3)
`/Users/wyy/developer/android/sdk/flutter/bin/flutter doctor --verbose
[✓] Flutter (Channel master, 3.25.0-1.0.pre.147, on macOS 14.4.1 23E224 darwin-arm64, locale zh-Hans-CN)
    • Flutter version 3.25.0-1.0.pre.147 on channel master at /Users/wyy/developer/android/sdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 99dc3beaf4 (7 小时前), 2024-08-26 22:10:32 -0400
    • Engine revision b41ca79092
    • Dart version 3.6.0 (build 3.6.0-175.0.dev)
    • DevTools version 2.39.0-dev.15
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/wyy/Library/Android/sdk
    • Platform android-35, build-tools 34.0.0
    • ANDROID_HOME = /Users/wyy/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)
    • All Android licenses accepted.`

**Comment by liuzehnhang** [comment] 2024-08-27 09:06
The Chinese characters'囊' overlap together

**Comment by danagbemava-nc** [comment] 2024-08-28 07:04
Hi @liuzehnhang, kindly file a new issue for https://github.com/flutter/flutter/issues/153677#issuecomment-2311970420

**Comment by naivetoby** [comment] 2024-08-29 06:53
@liuzehnhang @danagbemava-nc Possible issues I found https://github.com/flutter/flutter/issues/154166#issuecomment-2316838349

**Closed** 2024-08-29 09:06 UTC
Labels: waiting for customer response, in triage
