### ISSUE TITLE
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_web-2.0.7/lib/url_launcher_web.dart:50:61: Error: No named parameter with the name 'isVisible'.         .registerViewFactory(linkViewType, linkViewFactory, isVisible: false);                                                             ^^^^^^^^^ Failed to compile application.

### ISSUE THREAD

**Issue by RaddN** [flutter/flutter#99589] opened 2022-03-05 07:38 UTC
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_web-2.0.7/lib/url_launcher_web.dart:50:61: Error: No named parameter with the name 'isVisible'.
        .registerViewFactory(linkViewType, linkViewFactory, isVisible: false);
                                                            ^^^^^^^^^
Failed to compile application.

**Comment by darshankawar** [comment] 2022-03-07 07:10
@RaddN 
Check [this](https://github.com/flutter/flutter/issues/97796#issuecomment-1030150455) issue comment.
In order to use `url_launcher_web-2.0.7`, you'll need to use Flutter 2.10 version. So you can probably upgrade the plugin version to latest 2.0.9 which should resolve this issue. 
Closing this as duplicate of https://github.com/flutter/flutter/issues/97796

**Closed by darshankawar** 2022-03-07 07:10 UTC
Labels: in triage
