### ISSUE TITLE
Windows app crashing on keyboard or mouse inputs

### ISSUE THREAD

**Issue by yahu1031** [flutter/flutter#90054] opened 2021-09-14 14:24 UTC
## Steps to Reproduce

1. Run `flutter create --patforms=windows bug`.

Run the application as it is. In my case, I have used [bitsdojo_window](https://pub.dev/packages/bitsdojo_windows) for frame less window. Not sure if it was because of this(mostly nope). Then when I left/right click on mouse or any ctrl, Fn, Alt, Shift keys will be throwing this error.
**Expected results:** 
Show work fine.
**Actual results:** 
Closes the app with the error mentioned below.
<details>
  <summary>Logs</summary>

`flutter run` (no verbose)
```log
Launching lib\main.dart on Windows in debug mode...
lib\main.dart:1
Connecting to VM Service at ws://127.0.0.1:51149/nHDy7Wu63E0=/ws
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: 'package:flutter/src/services/hardware_keyboard.dart': Failed assertion: line 787 pos 16: 'false': Should never encounter KeyData when transitMode is rawKeyData.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
#2      KeyEventManager.handleKeyData
package:flutter/…/services/hardware_keyboard.dart:787
#3      PlatformDispatcher._dispatchKeyData.<anonymous closure> (dart:ui/platform_dispatcher.dart:375:61)
#4      _invoke2.<anonymous closure> (dart:ui/hooks.dart:205:15)
#5      _rootRun (dart:async/zone.dart:1428:13)
#6      _CustomZone.run (dart:async/zone.dart:1328:19)
#7      _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
#8      _invoke2 (dart:ui/hooks.dart:204:10)
#9      PlatformDispatcher._dispatchKeyData (dart:ui/platform_dispatcher.dart:373:5)
#10     _dispatchKeyData (dart:ui/hooks.dart:104:31)
Unable to parse JSON message:
The document is empty.

════════ Exception caught by services library ══════════════════════════════════
The following _CastError was thrown during a platform message callback:
Null check operator used on a null value

When the exception was thrown, this was the stack
#0      KeyEventManager._convertRawEventAndStore
package:flutter/…/services/hardware_keyboard.dart:884
#1      RawKeyboard.handleRawKeyEvent
package:flutter/…/services/raw_keyboard.dart:677
#2      KeyEventManager.handleRawKeyMessage
package:flutter/…/services/hardware_keyboard.dart:818
#3      BasicMessageChannel.setMessageHandler.<anonymous closure>
package:flutter/…/services/platform_channel.dart:73
#4      BasicMessageChannel.setMessageHandler.<anonymous closure>
package:flutter/…/services/platform_channel.dart:72
Launching lib\main.dart on Windows in debug mode...
lib\main.dart:1
Connecting to VM Service at ws://127.0.0.1:51149/nHDy7Wu63E0=/ws
#5      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure>
package:flutter/…/services/binding.dart:379
#6      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure>
package:flutter/…/services/binding.dart:376
#7      _invoke2.<anonymous closure> (dart:ui/hooks.dart:205:15)
#11     _invoke2 (dart:ui/hooks.dart:204:10)
#12     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:42:5)
#13     _Channel.push (dart:ui/channel_buffers.dart:132:31)
#14     ChannelBuffers.push (dart:ui/channel_buffers.dart:329:17)
#15     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:544:22)
#16     _dispatchPlatformMessage (dart:ui/hooks.dart:92:31)
(elided 3 frames from dart:async)
════════════════════════════════════════════════════════════════════════════════
Lost connection to device.
```

```
PS C:\Users\yaswa> flutter doctor -v
[✓] Flutter (Channel stable, 2.5.0, on Microsoft Windows [Version 10.0.22454.1000], locale en-IN)
    • Flutter version 2.5.0 at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cc385b4b8 (6 days ago), 2021-09-07 23:01:49 -0700
    • Engine revision f0826da7ef
    • Dart version 2.14.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\yaswa\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Users\yaswa\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\203.7678000\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.2)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31624.102
    • Windows 10 SDK version 10.0.20348.0

[✓] Android Studio (version 2020.3)
    • Android Studio at C:\Users\yaswa\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\203.7678000
    • Flutter plugin version 60.0.2
    • Dart plugin version 203.8292
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.60.0)
    • VS Code at C:\Users\yaswa\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.26.0

[✓] Connected device (4 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)                  • windows       • windows-x64    • Microsoft Windows [Version 10.0.22454.1000]
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 93.0.4577.63
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 93.0.961.47

• No issues found!
```
</details>

Note: I will update the verbose run once I get back on it.

Device details:
![image](https://user-images.githubusercontent.com/35523357/133275690-4cf2d8fe-40ea-41ee-9c5a-e449ff84561d.png)

**Comment by yahu1031** [comment] 2021-09-14 21:05
Few more logs
```
Reloaded 1 of 932 libraries in 297ms.
Unable to parse JSON message:
The document is empty.

════════ Exception caught by services library ══════════════════════════════════
The following assertion was thrown during a platform message callback:
A KeyUpEvent is dispatched, but the state shows that the physical key is not pressed. If this occurs in real application, please report this bug to Flutter. If this occurs in unit tests, please ensure that simulated events follow Flutter's event model as documented in `HardwareKeyboard`. This was the event: KeyUpEvent#44bb2(physicalKey: PhysicalKeyboardKey#700e2(usbHidUsage: "0x000700e2", debugName: "Alt Left"), logicalKey: LogicalKeyboardKey#00104(keyId: "0x200000104", keyLabel: "Alt Left", debugName: "Alt Left"), character: null, timeStamp: 14:25:21.749924)
'package:flutter/src/services/hardware_keyboard.dart':
Failed assertion: line 441 pos 16: '_pressedKeys.containsKey(event.physicalKey)'

2

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack
#2      HardwareKeyboard._assertEventIsRegular.<anonymous closure>
package:flutter/…/services/hardware_keyboard.dart:441
#3      HardwareKeyboard._assertEventIsRegular
package:flutter/…/services/hardware_keyboard.dart:452
#4      HardwareKeyboard.handleKeyEvent
package:flutter/…/services/hardware_keyboard.dart:543
#5      KeyEventManager.handleRawKeyMessage
package:flutter/…/services/hardware_keyboard.dart:821
#6      BasicMessageChannel.setMessageHandler.<anonymous closure>
package:flutter/…/services/platform_channel.dart:73
#7      BasicMessageChannel.setMessageHandler.<anonymous closure>
package:flutter/…/services/platform_channel.dart:72
#8      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure>
package:flutter/…/services/binding.dart:379
#9      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure>
package:flutter/…/services/binding.dart:376
#10     _invoke2.<anonymous closure> (dart:ui/hooks.dart:205:15)
#14     _invoke2 (dart:ui/hooks.dart:204:10)
#15     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:42:5)
#16     _Channel.push (dart:ui/channel_buffers.dart:132:31)
#17     ChannelBuffers.push (dart:ui/channel_buffers.dart:329:17)
#18     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:544:22)
#19     _dispatchPlatformMessage (dart:ui/hooks.dart:92:31)
(elided 5 frames from class _AssertionError and dart:async)
════════════════════════════════════════════════════════════════════════════════
Lost connection to device.
Exited (sigterm)
```

**Comment by darshankawar** [comment] 2021-09-15 08:16
@yahu1031 
There's a similar open issue describing your case, https://github.com/flutter/flutter/issues/89982
Please follow-up there for updates.
Closing this as a duplicate.

**Closed by darshankawar** 2021-09-15 08:16 UTC
Labels: in triage

**Comment by dkwingsmt** [comment] 2021-11-08 20:15
@yahu1031 Are you still encountering this issue on the latest master?

**Comment by yahu1031** [comment] 2021-11-08 20:16
@dkwingsmt sometimes yes.

**Comment by dkwingsmt** [comment] 2021-11-08 20:19
I mean, it would be best if you can describe a reproduction step and verify it on latest master, since there have been some fixes since when you first wrote this issue and we've been playing around for a bit as well.

**Comment by yahu1031** [comment] 2021-11-11 15:20
@dkwingsmt Sorry to make you wait. I couldn't face it now on the latest changes. Please don't lock this convo. If I get any issues I will write a comment.
