### ISSUE TITLE
The introduction of image resources in Flutter project cannot automatically prompt, and the development efficiency is very low.

### ISSUE THREAD

**Issue by gionchat** [flutter/flutter#53545] opened 2020-03-30 01:14 UTC
The introduction of image resources in Flutter project cannot automatically prompt, and the development efficiency is very low
Here's the Android project:
![图片](https://user-images.githubusercontent.com/58280808/77866709-b52bd200-7266-11ea-848e-dd4b161ee430.png)

**Comment by TahaTesser** [comment] 2020-03-30 09:59
Hi @gionchat 

Duplicate of [#2580](https://github.com/flutter/flutter-intellij/issues/2580)

following the indication of [jetbrains' Flutter plugin](https://plugins.jetbrains.com/plugin/9212-flutter)
the correct way to address the problem
is to open an issue on the dedicated [github](https://github.com/flutter/flutter-intellij/issues)
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it. 
Thank you for your understanding

**Closed by TahaTesser** 2020-03-30 09:59 UTC
