### ISSUE TITLE
textField losing focus

### ISSUE THREAD

**Issue by HJMengx** [flutter/flutter#36515] opened 2019-07-19 04:28 UTC
### Steps to Reproduce

Hello there.
When I use TextField for input, the focus is automatically lost when I click on it the first time, and it can be executed when I click on it again the second time.

This problem will only occur if the page using the TextField is navigator.push.

If directly as the home page, it can be work.

#### Push Page

<img  src="http://ww3.sinaimg.cn/large/006tNc79gy1g55026r1gmg30nw1144mj.gif" width=50% />

#### Home Page

<img  src="http://ww2.sinaimg.cn/large/006tNc79gy1g551am5wp1g30nu14qkcl.gif" width=50% />

**Comment by rvhamed** [comment] 2019-08-13 07:05
Hi, I have the same issues, when I set the "focusNode".

**Comment by kf6gpe** [comment] 2020-01-07 21:23
Closing due to lack of reproducible case & `flutter doctor -v` output. If you'd like us to look into it, please reopen with these.

**Closed by kf6gpe** 2020-01-07 21:23 UTC
Labels: a: text input, f: material design, framework
