### ISSUE TITLE
Regression in Linux Android Debug Engine times

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#96124] opened 2022-01-04 16:54 UTC
Over the past couple of months, these builds have regressed from typically taking around 30 minutes to regularly taking upwards of 40+ minutes. Eyeballing the build timelines, the delays I'm seeing come from the `bot_update` step more regularly taking 7+ minutes.

<img width="1565" alt="Screen Shot 2022-01-04 at 8 50 23 AM" src="https://user-images.githubusercontent.com/6343103/148094437-31901206-cf9c-4d11-b61b-87dd1543aa01.png">

/cc @godofredoc @blasten

**Comment by godofredoc** [comment] 2022-01-05 20:37
@keyonghan can you please take a look?

**Comment by keyonghan** [comment] 2022-01-05 22:22
> @keyonghan can you please take a look?

Scanned through infra changes around 11/26, but don't see suspicious changes.

After taking a further look at this builder, some findings comparing before (~25min) and after (~35min)
1) step checkout source code (bot_update) exec time jumps high (>5 min) occasionally, for both cases
2) step `build android_jit_release_x86` consistently takes longer (~6min) than before (~1.2min) => 5min longer
3) step `test: Host Tests for android_debug` consistently takes longer (~4.3 min) than before (~2.7min) => 1.5 min longer

Also checked other builders, and all execute normally without hitting regressions (except Mac iOS Engine, see attached). This sounds like code changes affecting specific build/test execution time. @blasten to confirm.

As for `Mac iOS Engine`, regression happened around 11/28. 
![Screen Shot 2022-01-05 at 2 18 13 PM](https://user-images.githubusercontent.com/54558023/148297576-f11a85bb-b1c5-460b-b393-92e92e93f5da.png)

Some finding comparing before (~17min) and after (~30min):
Example build: [before](https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20iOS%20Engine/13003/overview) v.s. [after](https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20iOS%20Engine/13202/overview).
1) Step `build ios_debug` consistently takes longer (~8 min) than before (~1.5min) =>6.5min longer
2) Step `build ios_debug_arm` consistently takes longer (~7 min) than before (~1.3min) => 5.7 min longer
@zanderso shall we open a separate bug for `Mac iOS engine`?

**Comment by godofredoc** [comment] 2022-01-05 22:43
This could be related to the android sdk bundle change. If the dependency in the engine was changed to use the monolithic SDK+NDK around the time this started happening we may need to take a look at the caching configurations for android sdk.

**Comment by zanderso** [comment] 2022-01-05 23:37
The `Mac iOS Engine` change may be related to running additional `clang-tidy` checks. That is consistent with the increase in build times in the graph if the checks were enabled by a single CL. If the times there are mostly around/under 30 minutes, then that is still within our objective, and so we don't need an issue filed for that. /cc @jmagman to confirm.

My concern with the Android builder was the gradual increase in build times. OTOH, @keyonghan if you can identify changes or dates where the increases in cost of `build android_jit_release_x86` and `test: Host Tests for android_debug` happened, that would be very helpful. That is, if the change is consistent, did you see where/when it happened?

**Comment by blasten** [comment] 2022-01-05 23:52
In regard to Linux Android Debug Engine, I found something suspicious. See  "Checkout source code". It took 6.1 min to download the source in [[1]](https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20Android%20Debug%20Engine/12918/overview), vs 20 sec in [[2]](https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20Android%20Debug%20Engine/13323/overview)

The main difference (from the logs) seems to come from "https://github.com/google/angle", which seems to be downloading every single branch of Chromium?

Logs:  https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8829336819991588561/+/u/Checkout_source_code/bot_update/stdout?format=raw

**Comment by keyonghan** [comment] 2022-01-05 23:56
> This could be related to the android sdk bundle change. If the dependency in the engine was changed to use the monolithic SDK+NDK around the time this started happening we may need to take a look at the caching configurations for android sdk.

Doesn't seem related to android sdk, as we didn't have any dependency changes in engine repo for recent 3 months.

**Comment by keyonghan** [comment] 2022-01-05 23:56
> My concern with the Android builder was the gradual increase in build times. OTOH, @keyonghan if you can identify changes or dates where the increases in cost of `build android_jit_release_x86` and `test: Host Tests for android_debug` happened, that would be very helpful. That is, if the change is consistent, did you see where/when it happened?

Step `build android_jit_release_x86` jumped since [build 12938](https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20Android%20Debug%20Engine/12938/overview) with commit https://github.com/flutter/engine/commit/2614113fd9c92b1b777b4efda9ae81f34cde1b48 /cc @mdebbar 
Step  `test: Host Tests for android_debug` jumped since [build 13086](https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20Android%20Debug%20Engine/13086/overview) with commit https://github.com/flutter/engine/commit/2eca05e1b6f1c8e971e2f337e336eda66789cf89 /cc @blasten

**Comment by zanderso** [comment] 2022-01-06 00:12
I don't think https://github.com/flutter/engine/commit/2614113fd9c92b1b777b4efda9ae81f34cde1b48 could have affected `build android_jit_release_x86`. The build targets built in that step wouldn't touch the files that were changed. Maybe there was a recipe change around the same time.

**Comment by blasten** [comment] 2022-01-06 00:25
> Step test: Host Tests for android_debug jumped since build 13086 with commit flutter/engine@2eca05e

I will experiment with some flags, but based on [this thread](https://github.com/robolectric/robolectric/issues/3351) I don't have much hope.

**Comment by keyonghan** [comment] 2022-01-06 00:35
> I don't think [flutter/engine@2614113](https://github.com/flutter/engine/commit/2614113fd9c92b1b777b4efda9ae81f34cde1b48) could have affected `build android_jit_release_x86`. The build targets built in that step wouldn't touch the files that were changed. Maybe there was a recipe change around the same time.

Focused on infra changes around 11/26.. but we do have three `recipes` rolls on 11/29:
https://flutter-review.googlesource.com/c/recipes/+/23620
https://flutter-review.googlesource.com/c/recipes/+/23640
https://flutter-review.googlesource.com/c/recipes/+/23641
/cc @godofredoc @zanderso there were quite some changes inside, do you recognize any that may cause our build time increasing, especially the step `build android_jit_release_x86`?

**Comment by jmagman** [comment] 2022-01-06 00:51
Clang tidy is being run in `Linux Android Debug Engine` in the `test: lint android_debug` step, changed on 11/22 https://flutter-review.googlesource.com/c/recipes/+/22160 from.  It added ~3:00 to the build, for ~25 minutes total.

**Comment by blasten** [comment] 2022-01-06 03:47
I didn't see any improvements after enabling the flag to parallelize the tests (probably due to the issue linked above).
There are 118 steps in `Linux Android Debug Engine`, do we need all of that in a single task?

**Comment by zanderso** [comment] 2022-01-06 16:29
@blasten Do we need a newer version of Robolectric? There's a PR to upgrade here: https://github.com/flutter/engine/pull/30437.

**Comment by utzcoz** [comment] 2022-01-06 16:42
> @blasten Do we need a newer version of Robolectric? There's a PR to upgrade here: [flutter/engine#30437](https://github.com/flutter/engine/pull/30437).

Hi @zanderso @blasten  , I'm the author of this mentioned PR. In my opinion, it's recommended to upgrade Robolectric version to gain support for latest Android SDK, for example this PR will bring support for SDK 31, and https://github.com/flutter/engine/pull/28886 brings support for SDK 30. When upgrading Robolectric version, I have found existing problems at higher SDK, including testing code and real logic code. For example, https://github.com/flutter/engine/pull/30437 shows that current Flutter's Android IMM workaround doesn't work on SDK 31 because Android S changed logic that breaks tests(this problem should be confirmed).  With latest Robolectric, testing code can provide more broader compatibility guarantee.

**Comment by keyonghan** [comment] 2022-01-06 17:10
Tried a couple of `led` runs, but all hit the increased execution time: 
1) [build](https://luci-milo.appspot.com/raw/build/logs.chromium.org/flutter/led/keyonghan_google.com/f9b28a0f4403413c8a8f02216d43d1b90847f0f0dec926c8e2cbcde0a78e8cf0/+/build.proto): cl https://flutter-review.googlesource.com/c/recipes/+/23620 with engine TOT commit
2) [build](https://luci-milo.appspot.com/raw/build/logs.chromium.org/flutter/led/keyonghan_google.com/c3e5cc5532cda7a5f00323fc4024b72cf5f3df18d1b5f9fc3576fc6068955d68/+/build.proto): cl https://flutter-review.googlesource.com/c/recipes/+/23640 with engine TOT commit
3) [build](https://luci-milo.appspot.com/raw/build/logs.chromium.org/flutter/led/keyonghan_google.com/21644d4d01a3b59bf0423ff7cd66e2afac5854b3bebfb5c3b1653e7c1db5f03c/+/build.proto): cl https://flutter-review.googlesource.com/c/recipes/+/23641 with engine TOT commit

Then I tried one more recipes cl earlier on [11/23](cl https://flutter-review.googlesource.com/c/recipes/+/23426) with engine TOT commit, it's still the same - [build](https://luci-milo.appspot.com/raw/build/logs.chromium.org/flutter/led/keyonghan_google.com/a58d37dcf829ae76a04a1ac32115a53bd3efaa1a7a04bf935655b7838dc6a020/+/build.proto)

Lastly I tried the recipes cl earlier on [11/23](cl https://flutter-review.googlesource.com/c/recipes/+/23426), but using the `good` engine commit https://github.com/flutter/engine/commit/d877faa2a639df9bb7beea62e033aea4869f6894 (the commit before https://github.com/flutter/engine/commit/2614113fd9c92b1b777b4efda9ae81f34cde1b48, where the build step started taking longer), however, the `build android_jit_release_x86` step still took 5min 53 sec.

This makes me feel the culprit is something else. Will take a look if any dependencies have been promoted to some newer version quietly that may affect this build step.

**Comment by blasten** [comment] 2022-01-07 02:26
I was able to reduce the execution time locally. https://github.com/flutter/engine/pull/30728

**Comment by keyonghan** [comment] 2022-01-10 19:25
> I was able to reduce the execution time locally. [flutter/engine#30728](https://github.com/flutter/engine/pull/30728)

Thanks @blasten ! 
Seems the step `build android_jit_release_x86` dropped back to 1.4min, but step `test: Host Tests for android_debug` still took 4.2min.

**Comment by blasten** [comment] 2022-01-10 19:39
Yes, unfortunately the way Gradle parallelizes tests won't help to reduce the time.

4.2min doesn't seem like a lot to some standards, but if this needs to be reduced, the alternative requires manual sharding, which is more expensive to maintain than the current set up.

**Comment by zanderso** [comment] 2022-01-19 17:18
What's the status of this? Dropping `build android_jit_release_x86` back down to 1.4 minutes from 6 minutes is a good improvement.

**Comment by ricardoamador** [comment] 2023-02-02 23:23
This has not had activity in over a year. Closing as not an issue.

**Closed by ricardoamador** 2023-02-02 23:23 UTC
Labels: severe: regression, passed first triage, team: infra, passed secondary triage, P3
