### ISSUE TITLE
Rendering Bug on iOS

### ISSUE THREAD

**Issue by JPyke3** [flutter/flutter#29478] opened 2019-03-16 06:51 UTC
Hi all! I have encountered a strange renderer error when i load my flutter app on my iDevice for the first time. It happens consistently without fail every single time across multiple devices. As soon as i tap the screen or perform any interaction with the screen the issue resolves itself and the UI must rebuild. But any advice as to whats causing this bug would be greatly appreciated.

## Steps to Reproduce

1. Open the app for the first time on an iphone

## Screenshot

![IMG_1283](https://user-images.githubusercontent.com/13283054/54471805-907dcd00-47bf-11e9-97bd-183d640bea2e.PNG)

## Logs

```
Able to post logs when informed which logs to post
```

```
Jacobs-MacBook-Pro:~ jacobpyke$ flutter doctor -v
[✓] Flutter (Channel master, v1.3.11-pre.12, on Mac OS X 10.14.3 18D109, locale en-DE)
    • Flutter version 1.3.11-pre.12 at /Users/jacobpyke/Development/Flutter/v1/flutter
    • Framework revision 439fbbe69e (16 hours ago), 2019-03-15 07:53:27 -0700
    • Engine revision b36068c377
    • Dart version 2.2.1 (build 2.2.1-dev.1.0 None)

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/jacobpyke/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Library/Java/JavaVirtualMachines/jdk-10.0.2.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment 18.3 (build 10.0.2+13)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.io/setup/#android-setup for detailed instructions.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[✓] Connected device (1 available)
    • iPhone von Jacob • 00008020-001318C22130003A • ios • iOS 12.1.2

! Doctor found issues in 2 categories.
```

**Comment by Babelfisch** [comment] 2019-03-16 18:03
Same problem:

![IMG_4187](https://user-images.githubusercontent.com/1218405/54479549-221c2780-481e-11e9-80a2-04cb608f2dab.jpg)

**Comment by jonahwilliams** [comment] 2019-03-16 18:10
Duplicate of https://github.com/flutter/flutter/issues/28484

**Closed by jonahwilliams** 2019-03-16 18:10 UTC
