### ISSUE TITLE
Voiceover crash when navigating between screens when the content of an underlying view changes

### ISSUE THREAD

**Issue by shihaohong** [flutter/flutter#47684] opened 2019-12-23 17:38 UTC
Internal bug: b/145575783

## Reproduction steps

1) Switch on VoiceOver
2) Tap on the '+' button using VoiceOver
3) Tap on the back button using VoiceOver

## Sample app
Tested on an iPhone XS running iOS 13.2.3. The following app is built with the latest SDK on https://flutter.dev/docs/get-started/install/macos.

```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(primarySwatch: Colors.blue),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;
  void _incrementCounter() {
    Navigator.push(
      context,
      MaterialPageRoute(builder: (context) => MyHomePage(title: 'Second Page')),
    );
    Future.delayed(const Duration(milliseconds: 1000), () {
      setState(() {
        _counter = 50;
      });
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text(widget.title)),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text('You have pushed the button this many times:'),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.display1,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ),
    );
  }
}
```

**Comment by mehmetf** [comment] 2020-01-09 04:27
Dupe of 46457

**Closed by mehmetf** 2020-01-09 04:27 UTC
Labels: a: accessibility, customer: money (g3), customer: quill (g3), severe: crash
