### ISSUE TITLE
got Issue while connecting to firebase

### ISSUE THREAD

**Issue by syedasadullah** [flutter/flutter#45484] opened 2019-11-24 08:22 UTC
I have used authentication feature of firebase in my android apps. It is wrorking good on android but when i converted it to web app and configured it with firebase then each time when i run app it gives
"Cannot found collection"

**Comment by iapicca** [comment] 2019-11-25 10:48
Hi @syedasadullah 
for what I can see the issue is related to a FlutterFire plugin,
please open the issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
thank you

**Closed by iapicca** 2019-11-25 10:48 UTC
