### ISSUE TITLE
 Why is he banned from speaking Chinese?

### ISSUE THREAD

**Issue by cshijiel** [flutter/flutter#48697] opened 2020-01-13 06:28 UTC
> 原issue：https://github.com/flutter/flutter/issues/48617
> 
> 另有人去v2ex找认同感嘲讽说中文的，图啥呢？
> 他只是英语不好，至于到处批判嘛，您的素养呢？说了蛮语素养都没了？

Original issue: https://github.com/flutter/flutter/issues/48617

Others go to v2ex to find a sense of ridicule and speak Chinese.
He just doesn't speak English well. As for criticism everywhere, what about your quality? After speaking the brutal literacy?

```console
We've translated this issue's description into English using Google Translate. If you're comfortable writing in English, please check the translation and update it if necessary. Thanks for the report!

```

**Comment by cshijiel** [comment] 2020-01-13 06:37
v2ex link: https://www.v2ex.com/t/637051

**Comment by iapicca** [comment] 2020-01-13 07:40
Hi @cshijiel 
the issue you linked was closed because isn't addressing any issue itself,
but instead referring to the closed issue https://github.com/flutter/flutter/issues/48552
which was  itself closed as `duplicate` of https://github.com/flutter/flutter/issues/47582
and not because the language that was used.

Does this answer your question?
Thank you

**Comment by cshijiel** [comment] 2020-01-13 09:15
OK, fine. Thanks for your reply. You can close this issue now.

**Comment by iapicca** [comment] 2020-01-13 09:17
I'm glad that you find my answer satisfactory @cshijiel 
thank you for letting me know

**Closed by iapicca** 2020-01-13 09:17 UTC
Labels: from: china

**Comment by dnfield** [comment] 2020-01-13 17:54
My recent reply on the linked bug was not meant to indicate that Chinese is banned - I'm truly sorry if that's how it was understood.

It does make it very hard for us non-Chinese speakers though if there are screenshots of Chinese text in a bug.  I can't use translation services to understand it, and if it's a bug about text rendering or something I can't copy and paste the text to reproduce it locally.  Of course, if you want to include a screenshot of a rendering issue that is fine - but please also include the actual text that's causing the issue (https://github.com/flutter/flutter/issues/48549 this bug does a good job of that).

As @iapicca stated, the linked bug was actually closed because it was a meta-question about why another bug was closed, which isn't really what this issue tracker is for.

**Comment by sky126** [comment] 2020-01-14 04:01
这是英文不好问题吗？这是典型不自己尝试搜索学习直接伸手让别人帮他解决问题。我到感觉你圣母了，这种伸手党不说说自己还感觉良好。

**Comment by MuZiLee** [comment] 2020-01-15 10:47
@sky
I am the one who published myself in Chinese, yes, my English is not good, please don't use language to attack others, this reflects your quality and family education. Again, I am not a shenshou party, and this brother is not the Madonna.
But I have a feeling you like to spray people around. It's true
