### ISSUE TITLE
Items in SliverList lose state when they are out of the viewport

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#9512] opened 2017-04-21 00:04 UTC
I don't have a simple case to reproduce this but it seems like the cards I put into SliverList are going through `initState()` when they go off screen and get back on again.

```Dart
    return new SliverPadding(
        padding: const EdgeInsets.only(top: 8.0, left: 8.0, right: 8.0),
        sliver: new SliverList(delegate: new SliverChildListDelegate(cards)));
```

**Comment by Hixie** [comment] 2017-04-21 17:04
Yes, lists are entirely lazy now (by design).

**Comment by mehmetf** [comment] 2017-04-21 17:11
Is there a way to make them not lazy? Or use a different construct instead of SliverList? These cards need to maintain their state even when off screen.

**Comment by Hixie** [comment] 2017-04-21 17:36
It's certainly possible (for example you could just have one SliverToBoxAdapter for each card and list them all in the viewport) but performance will suffer dramatically. I would strongly recommend not keeping app state within the widgets.

**Comment by mehmetf** [comment] 2017-04-21 17:49
We have a bar chart widget that stores which bar the user has selected. This is not something that I would keep anywhere other than the state of the widget and I don't want it to be lost when the card is off screen.

We are using this now:
```Dart
return new SingleChildScrollView(
        child: new Padding(
            padding: const EdgeInsets.only(top: 8.0, left: 8.0, right: 8.0),
            child: new ListBody(children: children)));
```

and we don't see this behavior. I am guessing ListBody simply keeps everything?

**Comment by Hixie** [comment] 2017-04-21 17:54
Yeah, ListBody is basically just a Column.

That will work ok assuming `children` is bounded and small (not much more than what's on the screen). It will not scale.

**Comment by Hixie** [comment] 2017-04-21 17:55
https://github.com/flutter/flutter/issues/8418 is about making it possible to have individual widgets remain even when off-screen in a lazy list, which may address this specific use case. It will only be reasonable if you have a small number of such special widgets, though. If you end up with a million charts maintaining state, performance will be terrible.

**Comment by mehmetf** [comment] 2017-04-21 17:57
Of course.

We are talking UX here. I dare any human to remember which bar they clicked on a million charts.

In our case the maximum number of cards in a page is 6. On average we have 3.

**Comment by Hixie** [comment] 2018-05-18 21:40
#8418 is fixed now. I'm going to close this. Let me know if you still need something.

**Closed by Hixie** 2018-05-18 21:40 UTC
