### ISSUE TITLE
Problem with TextFormField

### ISSUE THREAD

**Issue by HamzaAyada** [flutter/flutter#60898] opened 2020-07-06 12:18 UTC
I create a simple TextFormField,
When I start typing the input, the screen becomes vibrating and the keyboard disappear as you find in screens shot.

![image](https://user-images.githubusercontent.com/49845208/86552255-5483f380-bf3f-11ea-932f-ee4b4cf40a3d.png)

 
- Flutter version : 1.17.5
- Android SDK version: 30.0.0
- Android Studio version: 4.0
- Device SM A750F: Android 10 (API 29)

![Screenshot_20200706-035203_Gallery](https://user-images.githubusercontent.com/49845208/86551137-29e46b80-bf3c-11ea-87cf-f24d54acd38f.jpg)
![Screenshot_20200706-035210_Gallery](https://user-images.githubusercontent.com/49845208/86551141-2cdf5c00-bf3c-11ea-8b2b-9fd4958a836d.jpg)

**Comment by VladyslavBondarenko** [comment] 2020-07-06 12:50
Hi @HamzaAyada 
Please complete minimal reproducible code sample in the text form.
Avoid using screenshots of text when is not necessarily, screenshots are not searchable and it's not possible to copy-past text out of it

**Comment by HamzaAyada** [comment] 2020-07-06 12:52
`import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';


class LoginPage extends StatefulWidget {
  @override
  _LoginPageState createState() => _LoginPageState();
}

class _LoginPageState extends State<LoginPage> {
  @override
  Widget build(BuildContext context) {
    ScreenUtil.init(context, width: 374, height: 812);
    Size size = MediaQuery.of(context).size;
    TextEditingController _login;
    TextEditingController _password;
    void initState() {
      super.initState();
      _login = TextEditingController();
      _password = TextEditingController();
    }

    void dispose() {
      _login.dispose();
      _password.dispose();
      super.dispose();
    }

    return Scaffold(
      body:Container(
        height: size.height,
        decoration: BoxDecoration(
          image: DecorationImage(
            image: AssetImage('assets/bg_2.png'),
            fit: BoxFit.cover
          )
        ),
        child: SingleChildScrollView(
          child: Column(
            children: <Widget>[
              Container(
                margin: EdgeInsets.all(30),
                child: Image(
                  alignment: Alignment.bottomCenter,
                  image: AssetImage('assets/walkwin.png'),
                ),
              ),
              Row(
                mainAxisAlignment: MainAxisAlignment.spaceAround,
                crossAxisAlignment: CrossAxisAlignment.center,
                children: <Widget>[
                  FlatButton(
                    child: Container(
                      child: Center(
                        child: Text(
                          'CONNEXION',
                          style: TextStyle(
                            fontFamily: 'NeoSansStd',
                            fontSize: 18.sp,
                            color: const Color(0xfffefefe),
                          ),
                          textAlign: TextAlign.center,
                        ),
                      ),
                      width: 140.w,
                      height: 36.h,
                      decoration: BoxDecoration(
                        border: Border.all(
                            width: 2.w, color: const Color(0xff505aa2)),
                        borderRadius: BorderRadius.circular(10.0),
                        color: const Color(0xff505aa2),
                      ),
                    ),
                  ),
                  FlatButton(
                    onPressed: () =>
                        Navigator.pushNamed(context, '/inscription'),
                    child: Container(
                      child: Center(
                        child: Text(
                          'INSCRIPTION',
                          style: TextStyle(
                            fontFamily: 'NeoSansStd',
                            fontSize: 18.sp,
                            color: const Color(0xff505aa2),
                          ),
                          textAlign: TextAlign.center,
                        ),
                      ),
                      width: 140.w,
                      height: 36.h,
                      decoration: BoxDecoration(
                        borderRadius: BorderRadius.circular(10.0),
                        color: const Color(0xfffefefe),
                        border: Border.all(
                            width: 2.w, color: const Color(0xff505aa2)),
                      ),
                    ),
                  ),
                ],
              ),
              Container(
                height: 360,
                width: 380,
                child: Card(
                  child: Padding(
                    padding: EdgeInsets.all(15),
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: <Widget>[
                        Text(
                          'Numéro de téléphone',
                          style: TextStyle(
                            fontWeight: FontWeight.w500,
                            fontFamily: 'NeoSansStd',
                            fontSize: 20.sp,
                            color: const Color(0xff454545),
                          ),
                          textAlign: TextAlign.start,
                        ),
                        SizedBox(height: 10,),
                        TextFormField(
                          controller: _login,
                          textInputAction: TextInputAction.next,
                          keyboardType: TextInputType.number,
                          maxLength: 8,
                          style: TextStyle(
                            fontSize: 25.sp,
                            fontFamily: 'NeoSansStd',
                            color: const Color(0xff505aa2),
                          ),
                          decoration: const InputDecoration(
                            errorStyle: TextStyle(
                              color: Colors.red,
                              wordSpacing: 5.0,
                            ),
                            icon: ImageIcon(
                              AssetImage('assets/ic_phone.png'),
                              color: const Color(0xff48c2c5),
                              size: 40,
                            ),
                            hintText: '9X XX XX XX',
                            border:  InputBorder.none,
                            counter: Text(''),
                          ),
                        ),
                         Text(
                            'Mot de passe',
                            style: TextStyle(
                              fontWeight: FontWeight.w500,
                              fontFamily: 'NeoSansStd',
                              fontSize: 20.sp,
                              color: const Color(0xff454545),
                            ),
                            textAlign: TextAlign.left,
                        ),
                        SizedBox(height: 10,),
                        TextFormField(
                          controller: _password,
                          textInputAction: TextInputAction.done,
                          keyboardType: TextInputType.number,
                          maxLength: 4,
                          style: TextStyle(
                            fontSize: 25.sp,
                            fontFamily: 'NeoSansStd',
                            color: const Color(0xff505aa2),
                          ),
                          obscureText: true,
                          decoration: const InputDecoration(
                            errorStyle: TextStyle(
                              color: Colors.red,
                              wordSpacing: 5.0,
                            ),
                            icon: ImageIcon(
                              AssetImage('assets/ic_lock.png'),
                              color: const Color(0xff48c2c5),
                              size: 40,
                            ),
                            hintText: 'X-X-X-X',
                            border:  InputBorder.none,
                            counter: Text(''),
                          ),
                        ),
                        FlatButton(
                          onPressed: () => Navigator.pushNamed(context, '/home'),
                          child: Container(
                            margin: EdgeInsets.only(left: 120),
                            width: 50.w,
                            height: 50.h,
                            decoration: BoxDecoration(
                              borderRadius: BorderRadius.all(Radius.circular(100)),
                              color: const Color(0xff48c2c5),
                              image: DecorationImage(
                                image: const AssetImage('assets/arrow.png'),
                                fit: BoxFit.fitWidth,
                              ),
                            ),
                          ),)
                      ],
                    ),
                  ),
                  shape: RoundedRectangleBorder(
                    borderRadius: BorderRadius.circular(15.0),
                  ),
                  shadowColor: const Color(0xff505aa2),
                  elevation: 10,
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}`

**Comment by VladyslavBondarenko** [comment] 2020-07-06 14:22
@HamzaAyada 
note that I can't copy and simply run the code,

<details>
 <summary>I tried with this and of course I can't reproduce</summary>

```
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

void main() => runApp(MaterialApp(home: LoginPage()));

class LoginPage extends StatefulWidget {
  @override
  _LoginPageState createState() => _LoginPageState();
}

class _LoginPageState extends State<LoginPage> {
  @override
  Widget build(BuildContext context) {
    Size size = MediaQuery.of(context).size;
    TextEditingController _login;
    TextEditingController _password;
    void initState() {
      super.initState();
      _login = TextEditingController();
      _password = TextEditingController();
    }

    void dispose() {
      _login.dispose();
      _password.dispose();
      super.dispose();
    }

    return Scaffold(
      body:Container(
        height: size.height,
        decoration: BoxDecoration(
            image: DecorationImage(
                image: NetworkImage('https://images.pexels.com/photos/281260/pexels-photo-281260.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500'),
                fit: BoxFit.cover
            )
        ),
        child: SingleChildScrollView(
          child: Column(
            children: <Widget>[
              Container(
                margin: EdgeInsets.all(30),
                child: Image(
                  alignment: Alignment.bottomCenter,
                  image: NetworkImage('https://images.pexels.com/photos/281260/pexels-photo-281260.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500'),
                ),
              ),
              Row(
                mainAxisAlignment: MainAxisAlignment.spaceAround,
                crossAxisAlignment: CrossAxisAlignment.center,
                children: <Widget>[
                  FlatButton(
                    child: Container(
                      child: Center(
                        child: Text(
                          'CONNEXION',
                          style: TextStyle(
                            fontFamily: 'NeoSansStd',
                            fontSize: 18,
                            color: const Color(0xfffefefe),
                          ),
                          textAlign: TextAlign.center,
                        ),
                      ),
                      width: 140,
                      height: 36,
                      decoration: BoxDecoration(
                        border: Border.all(
                            width: 2, color: const Color(0xff505aa2)),
                        borderRadius: BorderRadius.circular(10.0),
                        color: const Color(0xff505aa2),
                      ),
                    ),
                  ),
                  FlatButton(
                    onPressed: () =>
                        Navigator.pushNamed(context, '/inscription'),
                    child: Container(
                      child: Center(
                        child: Text(
                          'INSCRIPTION',
                          style: TextStyle(
                            fontFamily: 'NeoSansStd',
                            fontSize: 18,
                            color: const Color(0xff505aa2),
                          ),
                          textAlign: TextAlign.center,
                        ),
                      ),
                      width: 140,
                      height: 36,
                      decoration: BoxDecoration(
                        borderRadius: BorderRadius.circular(10.0),
                        color: const Color(0xfffefefe),
                        border: Border.all(
                            width: 2, color: const Color(0xff505aa2)),
                      ),
                    ),
                  ),
                ],
              ),
              Container(
                height: 360,
                width: 380,
                child: Card(
                  child: Padding(
                    padding: EdgeInsets.all(15),
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: <Widget>[
                        Text(
                          'Numéro de téléphone',
                          style: TextStyle(
                            fontWeight: FontWeight.w500,
                            fontFamily: 'NeoSansStd',
                            fontSize: 20,
                            color: const Color(0xff454545),
                          ),
                          textAlign: TextAlign.start,
                        ),
                        SizedBox(height: 10,),
                        TextFormField(
                          controller: _login,
                          textInputAction: TextInputAction.next,
                          keyboardType: TextInputType.number,
                          maxLength: 8,
                          style: TextStyle(
                            fontSize: 25,
                            fontFamily: 'NeoSansStd',
                            color: const Color(0xff505aa2),
                          ),
                          decoration: const InputDecoration(
                            errorStyle: TextStyle(
                              color: Colors.red,
                              wordSpacing: 5.0,
                            ),
                            icon: Icon(Icons.email),
                            hintText: '9X XX XX XX',
                            border:  InputBorder.none,
                            counter: Text(''),
                          ),
                        ),
                        Text(
                          'Mot de passe',
                          style: TextStyle(
                            fontWeight: FontWeight.w500,
                            fontFamily: 'NeoSansStd',
                            fontSize: 20,
                            color: const Color(0xff454545),
                          ),
                          textAlign: TextAlign.left,
                        ),
                        SizedBox(height: 10,),
                        TextFormField(
                          controller: _password,
                          textInputAction: TextInputAction.done,
                          keyboardType: TextInputType.number,
                          maxLength: 4,
                          style: TextStyle(
                            fontSize: 25,
                            fontFamily: 'NeoSansStd',
                            color: const Color(0xff505aa2),
                          ),
                          obscureText: true,
                          decoration: const InputDecoration(
                            errorStyle: TextStyle(
                              color: Colors.red,
                              wordSpacing: 5.0,
                            ),
                            icon: Icon(Icons.email),
                            hintText: 'X-X-X-X',
                            border:  InputBorder.none,
                            counter: Text(''),
                          ),
                        ),
                        FlatButton(
                          onPressed: () => Navigator.pushNamed(context, '/home'),
                          child: Container(
                            margin: EdgeInsets.only(left: 120),
                            width: 50,
                            height: 50,
                            decoration: BoxDecoration(
                              borderRadius: BorderRadius.all(Radius.circular(100)),
                              color: const Color(0xff48c2c5),
                              image: DecorationImage(
                                image: NetworkImage('https://images.pexels.com/photos/281260/pexels-photo-281260.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500'),
                                fit: BoxFit.fitWidth,
                              ),
                            ),
                          ),)
                      ],
                    ),
                  ),
                  shape: RoundedRectangleBorder(
                    borderRadius: BorderRadius.circular(15.0),
                  ),
                  shadowColor: const Color(0xff505aa2),
                  elevation: 10,
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
```

</details>

Try to make a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by iapicca** [comment] 2020-07-29 10:39
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by iapicca** 2020-07-29 10:39 UTC
Labels: a: text input, f: material design, framework, in triage, waiting for customer response

**Comment by HamzaAyada** [comment] 2020-09-21 01:32
@iapicca @VladyslavBondarenko @HansMuller 



```flutter doctor -v```

```console
[√] Flutter (Channel stable, 1.20.4, on Microsoft Windows [version 10.0.19041.508], locale fr-FR)
    • Flutter version 1.20.4 at C:\flutter
    • Framework revision fba99f6cf9 (6 days ago), 2020-09-14 15:32:52 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2


[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at C:\Users\HAMZA TEK'NOLOGY IT\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Ultimate Edition (version 2019.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2019.2.3
    • Flutter plugin version 43.0.2
    • Dart plugin version 192.8052

[√] VS Code (version 1.47.3)
    • VS Code at C:\Users\HAMZA TEK'NOLOGY IT\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.13.1

[√] Connected device (1 available)
    • JAT L29 (mobile) • 9EHNW20303000604 • android-arm • Android 9 (API 28)

• No issues found!

```





the problem is that when I put a form for example directly in the ```main.dart``` it works correctly
but when I use the routers to navigate from page to another I cannot use the ```TextFormFields```





- main.dart (the TextFormField Work)
```dart
void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    SystemChrome.setPreferredOrientations([
      DeviceOrientation.portraitUp,
    ]);
    return MaterialApp(
      title: 'YourCab Client',
      debugShowCheckedModeBanner: false,
      home: RegisterPage(),
      // ignore: missing_return

    );
  }
}
```

- main.dart (the TextFormField dosn't Work)
``` dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:yourcab_client/routes/routes.dart';
import 'package:yourcab_client/ui/register.dart';


void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    SystemChrome.setPreferredOrientations([
      DeviceOrientation.portraitUp,
    ]);
    return MaterialApp(
      title: 'YourCab Client',
      debugShowCheckedModeBanner: false,
      routes: routes,
      // ignore: missing_return

    );
  }
}
```

- routes.dart
```dart

import 'package:flutter/cupertino.dart';
import 'package:yourcab_client/ui/about.dart';
import 'package:yourcab_client/ui/historique.dart';
import 'package:yourcab_client/ui/home.dart';
import 'package:yourcab_client/ui/login.dart';
import 'package:yourcab_client/ui/packs.dart';
import 'package:yourcab_client/ui/promotion.dart';
import 'package:yourcab_client/ui/register.dart';
import 'package:yourcab_client/ui/resetePassword.dart';
import 'package:yourcab_client/ui/setting.dart';
import 'package:yourcab_client/ui/splashScreen.dart';
import 'package:yourcab_client/ui/support.dart';


final routes = {
  '/register': (BuildContext context) => RegisterPage(),
};
```

- Form

```dart
class RegisterPage extends StatefulWidget {
  @override
  _RegisterPageState createState() => _RegisterPageState();
}

class _RegisterPageState extends State<RegisterPage> {
  final _formRegisterKey = GlobalKey<FormState>();
  String _firstName, _lastName, _email, _telephone, _sexe, _password = "";
  @override
  Widget build(BuildContext context) {
    SizeConfig().init(context);
    return Scaffold(
      body: Container(
        height: SizeConfig.safeBlockVertical * 110,
        width: SizeConfig.safeBlockVertical * 100,
        child: ListView(
          padding: EdgeInsets.only(left: 20, right: 20),
          children: [
            Container(
              height: SizeConfig.safeBlockVertical * 15, //10 for example
              width: SizeConfig.safeBlockHorizontal * 20,
              margin: EdgeInsets.fromLTRB(50, 5, 50, 5),
              child: Image(
                alignment: Alignment.bottomCenter,
                image: AssetImage('assets/logo_bleu.png'),
              ),
            ),
            Form(
                key: _formRegisterKey,
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(
                      'Nom',
                      style: TextStyle(
                        textBaseline: TextBaseline.alphabetic,
                        fontWeight: FontWeight.w500,
                        fontSize: 20,
                        color: const Color(0xff454545),
                      ),
                      textAlign: TextAlign.start,
                    ),
                    SizedBox(
                      height: SizeConfig.blockSizeVertical * 1,
                    ),
                    TextFormField(
                      textInputAction: TextInputAction.next,
                      keyboardType: TextInputType.text,
                      onSaved: (login) => _firstName = login,
                      validator: (value) =>
                      value.isEmpty ? "Nom est obligatoire!" : null,
                      decoration: InputDecoration(
                        errorStyle: TextStyle(
                          color: Colors.red,
                          wordSpacing: 5.0,
                        ),
                        hintText: 'Nom',
                        border: OutlineInputBorder(
                          borderRadius: BorderRadius.circular(20),
                        ),
                        counter: Text(''),
                      ),
                      style: TextStyle(
                        fontSize: 20,
                        color: const Color(0xff454545),
                      ),
                    ),
                    Text(
                      'Prènom',
                      style: TextStyle(
                        textBaseline: TextBaseline.alphabetic,
                        fontWeight: FontWeight.w500,
                        fontSize: 20,
                        color: const Color(0xff454545),
                      ),
                      textAlign: TextAlign.start,
                    ),
                    SizedBox(
                      height: SizeConfig.blockSizeVertical * 1,
                    ),
                    TextFormField(
                      textInputAction: TextInputAction.next,
                      keyboardType: TextInputType.text,
                      onSaved: (login) => _lastName = login,
                      validator: (value) =>
                      value.isEmpty ? "Prènom est obligatoire!" : null,
                      decoration: InputDecoration(
                        errorStyle: TextStyle(
                          color: Colors.red,
                          wordSpacing: 5.0,
                        ),
                        hintText: 'Prènom',
                        border: OutlineInputBorder(
                          borderRadius: BorderRadius.circular(20),
                        ),
                        counter: Text(''),
                      ),
                      style: TextStyle(
                        fontSize: 20,
                        color: const Color(0xff454545),
                      ),
                    ),
                    Text(
                      'E-mail',
                      style: TextStyle(
                        textBaseline: TextBaseline.alphabetic,
                        fontWeight: FontWeight.w500,
                        fontSize: 20,
                        color: const Color(0xff454545),
                      ),
                      textAlign: TextAlign.start,
                    ),
                    SizedBox(
                      height: SizeConfig.blockSizeVertical * 1,
                    ),
                    TextFormField(
                      textInputAction: TextInputAction.next,
                      keyboardType: TextInputType.emailAddress,
                      onSaved: (email) => _email = email,
                      validator: (value) =>
                      value.isEmpty ? "E-mail est obligatoire!" : null,
                      decoration: InputDecoration(
                        errorStyle: TextStyle(
                          color: Colors.red,
                          wordSpacing: 5.0,
                        ),
                        hintText: 'nom-prénom@yourcab.fr',
                        border: OutlineInputBorder(
                          borderRadius: BorderRadius.circular(20),
                        ),
                        counter: Text(''),
                      ),
                      style: TextStyle(
                        fontSize: 20,
                        color: const Color(0xff454545),
                      ),
                    ),
                    Text(
                      'Mobile',
                      style: TextStyle(
                        textBaseline: TextBaseline.alphabetic,
                        fontWeight: FontWeight.w500,
                        fontSize: 20,
                        color: const Color(0xff454545),
                      ),
                      textAlign: TextAlign.start,
                    ),
                    SizedBox(
                      height: SizeConfig.blockSizeVertical * 1,
                    ),
                    TextFormField(
                      textInputAction: TextInputAction.next,
                      keyboardType: TextInputType.emailAddress,
                      onSaved: (login) => _telephone = login,
                      validator: (value) =>
                      value.isEmpty ? "Mobile est obligatoire!" : null,
                      decoration: InputDecoration(
                        errorStyle: TextStyle(
                          color: Colors.red,
                          wordSpacing: 5.0,
                        ),
                        hintText: 'Numéro de Mobile'
                            '',
                        border: OutlineInputBorder(
                          borderRadius: BorderRadius.circular(20),
                        ),
                        counter: Text(''),
                      ),
                      style: TextStyle(
                        fontSize: 20,
                        color: const Color(0xff454545),
                      ),
                    ),
                    Text(
                      'Mot de Passe',
                      style: TextStyle(
                        textBaseline: TextBaseline.alphabetic,
                        fontWeight: FontWeight.w500,
                        fontSize: 20,
                        color: const Color(0xff454545),
                      ),
                      textAlign: TextAlign.start,
                    ),
                    SizedBox(
                      height: SizeConfig.blockSizeVertical * 1,
                    ),
                    TextFormField(
                      textInputAction: TextInputAction.done,
                      keyboardType: TextInputType.text,
                      obscureText: true,
                      onSaved: (password) => _password = password,
                      validator: (value) => value.isEmpty
                          ? "Mot de Passe est obligatoire!"
                          : null,
                      decoration: InputDecoration(
                        errorStyle: TextStyle(
                          color: Colors.red,
                          wordSpacing: 5.0,
                        ),
                        hintText: 'xxxxxxxxx',
                        border: OutlineInputBorder(
                          borderRadius: BorderRadius.circular(20),
                        ),
                        counter: Text(''),
                      ),
                      style: TextStyle(
                        fontSize: 20,
                        color: const Color(0xff454545),
                      ),
                    ),
                    Center(
                      child: RaisedButton(
                        shape: RoundedRectangleBorder(
                            borderRadius: BorderRadius.circular(38.0),
                            side:
                            BorderSide(color: const Color(0xff203B7A))),
                        onPressed: () {
                          MaterialPageRoute(builder: (context)=>HomePage());
                          //print(_identifier);
                          if (_formRegisterKey.currentState.validate()) {
                            _formRegisterKey.currentState.save();
                            //signIn(_login, _password);
                            //saveUser(_login, _identifier);
                          }
                        },
                        color: const Color(0xff203B7A),
                        //padding: EdgeInsets.fromLTRB(135, 10, 100, 20),
                        child: Image(
                          height: 20,
                          image: const AssetImage('assets/arrow.png'),
                          fit: BoxFit.fitWidth,
                        ),
                      ),
                    ),
                  ],
                ))
            /*Padding(
                child: ,
                padding: EdgeInsets.all(10))*/
          ],
        ),
      ),
    );
  }
}
```

**Comment by iapicca** [comment] 2020-09-21 06:41
@HamzaAyada 
the code you provided seems to be a snippet from production,
please provide a **_minimal_** reproducible code sample as mentioned [above](https://github.com/flutter/flutter/issues/60898#issuecomment-654269856)

tagging @TahaTesser for visibility
