### ISSUE TITLE
[tool_crash] ProcessException: The system cannot find the file specified. Command: C:\Users\91848\flutter\bin\cache\dart-sdk\bin\pub.BAT, OS error code: 2

### ISSUE THREAD

**Issue by soumitrakand7** [flutter/flutter#90059] opened 2021-09-14 15:09 UTC
## Command
```
flutter doctor
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ProcessException: The system cannot find the file specified.
 Command: C:\Users\91848\flutter\bin\cache\dart-sdk\bin\pub.BAT, OS error code: 2
```
#0      _ProcessImpl._start (dart:io-patch/process_patch.dart:390:33)
#1      Process.start (dart:io-patch/process_patch.dart:36:20)
#2      LocalProcessManager.start (package:process/src/interface/local_process_manager.dart:44:22)
#3      ErrorHandlingProcessManager.start.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:691:24)
#4      _run (package:flutter_tools/src/base/error_handling_io.dart:567:20)
#5      ErrorHandlingProcessManager.start (package:flutter_tools/src/base/error_handling_io.dart:690:12)
#6      _DefaultProcessUtils.start (package:flutter_tools/src/base/process.dart:425:28)
#7      _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart:444:35)
#8      _DefaultPub.batch (package:flutter_tools/src/dart/pub.dart:308:34)
<asynchronous suspension>
#9      _DefaultPub.get (package:flutter_tools/src/dart/pub.dart:248:7)
<asynchronous suspension>
#10     PubDependencies.update (package:flutter_tools/src/flutter_cache.dart:119:5)
<asynchronous suspension>
#11     Cache.updateAll (package:flutter_tools/src/cache.dart:557:9)
<asynchronous suspension>
#12     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1227:7)
<asynchronous suspension>
#13     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1125:27)
<asynchronous suspension>
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#15     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#16     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
```
```
[✓] Flutter (Channel stable, 2.5.0, on Microsoft Windows [Version 10.0.19043.1202], locale en-IN)
    • Flutter version 2.5.0 at C:\Users\91848\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cc385b4b8 (6 days ago), 2021-09-07 23:01:49 -0700
    • Engine revision f0826da7ef
    • Dart version 2.14.0

[✗] Android toolchain - develop for Android devices
    • Android SDK at C:\Users\91848\AppData\Local\Android\sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[✓] VS Code (version 1.60.0)
    • VS Code at C:\Users\91848\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.26.0

[✓] VS Code (version 1.58.0-insider)
    • VS Code at C:\Users\91848\AppData\Local\Programs\Microsoft VS Code Insiders
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 93.0.4577.63
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 93.0.961.38

! Doctor found issues in 2 categories.

```

## Flutter Application Metadata
No pubspec in working directory.

**Comment by soumitrakand7** [comment] 2021-09-14 15:11
Getting the error: 'Oops; flutter has exited unexpectedly: "ProcessException: The system cannot find the file specified.' when I type flutter doctor in the command prompt

**Comment by maheshmnj** [comment] 2021-09-15 07:16
Hi @soumitrakand7, Thanks for filing the issue. 

>   ✗ cmdline-tools component is missing

I believe this is causing the issue.
You have to make sure you have installed android SDK command line tools. The simplest way of doing this is 

- Install android studio 
- then go to Preferences > Appearance & Behavior > System Settings > Android SDK > SDK Tools > Android SDK Command-line Tools (latest)


<img width="1094" alt="Screenshot 2021-09-15 at 12 44 55 PM" src="https://user-images.githubusercontent.com/31410839/133388092-d4b4b37c-2a88-46c7-b4d6-4047789fc28e.png">

**Comment by soumitrakand7** [comment] 2021-09-15 15:21
Thank you @maheshmnj 
This worked. But now i am facing an issue with android licenses.

[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\91848\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    **✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.**
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
      
And I can't run "flutter doctor --android-licenses" as the same error pops up:
Oops; flutter has exited unexpectedly: "ProcessException: The system cannot find the file specified.

**Comment by maheshmnj** [comment] 2021-09-16 06:08
@soumitrakand7  please share the updated `flutter doctor -v` and the complete output of  
`flutter doctor --android-licenses`

**Comment by soumitrakand7** [comment] 2021-09-16 06:22
This is the error I face when I run `flutter doctor --android-licenses` :

![image](https://user-images.githubusercontent.com/90708604/133559357-44746eab-60b6-4779-8b58-a836c25fdfcd.png)

And a similar error when I run `flutter doctor -v` :

![image](https://user-images.githubusercontent.com/90708604/133560012-c5ebbbf7-ae82-4b9c-bf1d-29250f615ff0.png)



The `flutter doctor` command also doesn't work.
Hope this gives a clear idea.

**Comment by maheshmnj** [comment] 2021-09-16 06:28
@soumitrakand7, can share the crash log written  at `C:\Windows\System32\Flutter_04.log`. And in the future when 
sharing logs or errrors please share it as a text instead of relying on screenshots.

Thanks

**Comment by soumitrakand7** [comment] 2021-09-16 06:37
## Command
```
flutter doctor
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ProcessException: The system cannot find the file specified.
 Command: C:\Users\91848\flutter\bin\cache\dart-sdk\bin\pub.BAT, OS error code: 2
```
#0      _ProcessImpl._start (dart:io-patch/process_patch.dart:390:33)
#1      Process.start (dart:io-patch/process_patch.dart:36:20)
#2      LocalProcessManager.start (package:process/src/interface/local_process_manager.dart:44:22)
#3      ErrorHandlingProcessManager.start.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:691:24)
#4      _run (package:flutter_tools/src/base/error_handling_io.dart:567:20)
#5      ErrorHandlingProcessManager.start (package:flutter_tools/src/base/error_handling_io.dart:690:12)
#6      _DefaultProcessUtils.start (package:flutter_tools/src/base/process.dart:425:28)
#7      _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart:444:35)
#8      _DefaultPub.batch (package:flutter_tools/src/dart/pub.dart:308:34)
<asynchronous suspension>
#9      _DefaultPub.get (package:flutter_tools/src/dart/pub.dart:248:7)
<asynchronous suspension>
#10     PubDependencies.update (package:flutter_tools/src/flutter_cache.dart:119:5)
<asynchronous suspension>
#11     Cache.updateAll (package:flutter_tools/src/cache.dart:557:9)
<asynchronous suspension>
#12     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1227:7)
<asynchronous suspension>
#13     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1125:27)
<asynchronous suspension>
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#15     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#16     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
```
```
[✓] Flutter (Channel stable, 2.5.0, on Microsoft Windows [Version 10.0.19043.1202], locale en-IN)
    • Flutter version 2.5.0 at C:\Users\91848\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cc385b4b8 (8 days ago), 2021-09-07 23:01:49 -0700
    • Engine revision f0826da7ef
    • Dart version 2.14.0

[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\91848\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    ✗ Android SDK file not found: adb.
    • Try re-installing or updating your Android SDK,
      visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.3)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31702.278
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.60.1)
    • VS Code at C:\Users\91848\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.26.0

[✓] VS Code (version 1.58.0-insider)
    • VS Code at C:\Users\91848\AppData\Local\Programs\Microsoft VS Code Insiders
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19043.1202]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 93.0.4577.82
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 93.0.961.38

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
No pubspec in working directory.

**Comment by soumitrakand7** [comment] 2021-09-16 07:54
## Command
```
flutter doctor
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ProcessException: The system cannot find the file specified.
 Command: C:\Users\91848\flutter\bin\cache\dart-sdk\bin\pub.BAT, OS error code: 2
```
#0      _ProcessImpl._start (dart:io-patch/process_patch.dart:390:33)
#1      Process.start (dart:io-patch/process_patch.dart:36:20)
#2      LocalProcessManager.start (package:process/src/interface/local_process_manager.dart:44:22)
#3      ErrorHandlingProcessManager.start.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:691:24)
#4      _run (package:flutter_tools/src/base/error_handling_io.dart:567:20)
#5      ErrorHandlingProcessManager.start (package:flutter_tools/src/base/error_handling_io.dart:690:12)
#6      _DefaultProcessUtils.start (package:flutter_tools/src/base/process.dart:425:28)
#7      _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart:444:35)
#8      _DefaultPub.batch (package:flutter_tools/src/dart/pub.dart:308:34)
<asynchronous suspension>
#9      _DefaultPub.get (package:flutter_tools/src/dart/pub.dart:248:7)
<asynchronous suspension>
#10     PubDependencies.update (package:flutter_tools/src/flutter_cache.dart:119:5)
<asynchronous suspension>
#11     Cache.updateAll (package:flutter_tools/src/cache.dart:557:9)
<asynchronous suspension>
#12     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1227:7)
<asynchronous suspension>
#13     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1125:27)
<asynchronous suspension>
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#15     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#16     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
```
```
[✓] Flutter (Channel stable, 2.5.0, on Microsoft Windows [Version 10.0.19043.1202], locale en-IN)
    • Flutter version 2.5.0 at C:\Users\91848\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cc385b4b8 (8 days ago), 2021-09-07 23:01:49 -0700
    • Engine revision f0826da7ef
    • Dart version 2.14.0

[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\91848\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.3)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31702.278
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.60.1)
    • VS Code at C:\Users\91848\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.26.0

[✓] VS Code (version 1.58.0-insider)
    • VS Code at C:\Users\91848\AppData\Local\Programs\Microsoft VS Code Insiders
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19043.1202]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 93.0.4577.82
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 93.0.961.38

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
No pubspec in working directory.

**Comment by soumitrakand7** [comment] 2021-09-16 08:01
Error for `flutter doctor --android-licenses` :

Microsoft Windows [Version _10.0.19043.1202]
(c) Microsoft Corporation. All rights reserved.

C:\Windows\system32>flutter doctor --android-licenses
Running "flutter pub get" in flutter_tools...

Oops; flutter has exited unexpectedly: "ProcessException: The system cannot find the file specified.

  Command: C:\Users\91848\flutter\bin\cache\dart-sdk\bin\pub.BAT --verbosity=warning get --no-precompile".
A crash report has been written to C:\Windows\System32\flutter_14.log.
This crash may already be reported. Check GitHub for similar crashes.
https://github.com/flutter/flutter/issues?q=is%3Aissue+ProcessException%3A+The+system+cannot+find+the+file+specified.%0D%0A%0A++Command%3A+C%3A%5CUsers%5C91848%5Cflutter%5Cbin%5Ccache%5Cdart-sdk%5Cbin%5Cpub.BAT+--verbosity%3Dwarning+get+--no-precompile

To report your crash to the Flutter team, first read the guide to filing a bug.
https://flutter.dev/docs/resources/bug-reports

Create a new GitHub issue by pasting this link into your browser and completing the issue template. Thank you!
https://git.io/Jupur

**Comment by soumitrakand7** [comment] 2021-09-16 08:03
Error for `flutter doctor --android-licenses` :

Microsoft Windows [Version _10.0.19043.1202]
(c) Microsoft Corporation. All rights reserved.

C:\Windows\system32>flutter doctor --android-licenses
Running "flutter pub get" in flutter_tools...

Oops; flutter has exited unexpectedly: "ProcessException: The system cannot find the file specified.

Command: C:\Users\91848\flutter\bin\cache\dart-sdk\bin\pub.BAT --verbosity=warning get --no-precompile".
A crash report has been written to C:\Windows\System32\flutter_14.log.
This crash may already be reported. Check GitHub for similar crashes.
https://github.com/flutter/flutter/issues?q=is%3Aissue+ProcessException%3A+The+system+cannot+find+the+file+specified.%0D%0A%0A++Command%3A+C%3A%5CUsers%5C91848%5Cflutter%5Cbin%5Ccache%5Cdart-sdk%5Cbin%5Cpub.BAT+--verbosity%3Dwarning+get+--no-precompile

To report your crash to the Flutter team, first read the guide to filing a bug.
https://flutter.dev/docs/resources/bug-reports

Create a new GitHub issue by pasting this link into your browser and completing the issue template. Thank you!
https://git.io/Jupur

Thank You and sorry for the inconvenience.

**Comment by maheshmnj** [comment] 2021-09-16 12:08
@soumitrakand7 Thanks for the details.

Closing this issue as a duplicate of https://github.com/flutter/flutter/issues/90059
if you disagree feel free to write in the comments and I will reopen it.

Thank you.

**Closed by maheshmnj** 2021-09-16 12:08 UTC
Labels: in triage
