### ISSUE TITLE
Shadow animation using Impeller causing rendering issues

### ISSUE THREAD

**Issue by gabrielgarciagava** [flutter/flutter#140653] opened 2023-12-27 11:22 UTC
### Steps to reproduce

1. Run the code sample with Impeller enabled.
2. Press on the cards a couple of times to activate the shadow animation

### Expected results

No UI issues

### Actual results

Some vertical black lines will appear on random cards.

Note that this issue only happens when running on iOS with Impeller enabled.

### Code sample

<details open><summary>Code sample</summary>

```dart
// Copyright 2014 The Flutter Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

import 'package:flutter/material.dart';

void main() => runApp(const AnimatedShadowIssueExampleApp());

class AnimatedShadowIssueExampleApp extends StatelessWidget {
  const AnimatedShadowIssueExampleApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(title: const Text('Bug example')),
        backgroundColor: const Color(0xff222222),
        body: const SizedBox(height: 180, child: AnimatedShadowIssue()),
      ),
    );
  }
}

class AnimatedShadowIssue extends StatelessWidget {
  const AnimatedShadowIssue({super.key});

  @override
  Widget build(BuildContext context) {
    return const CustomScrollView(
      scrollDirection: Axis.horizontal,
      slivers: [
        SliverToBoxAdapter(child: Square()),
        SliverToBoxAdapter(child: Square()),
        SliverToBoxAdapter(child: Square()),
        SliverToBoxAdapter(child: Square()),
        SliverToBoxAdapter(child: Square()),
      ],
    );
  }
}

class Square extends StatefulWidget {
  const Square({super.key});

  @override
  State<Square> createState() => _SquareState();
}

class _SquareState extends State<Square> with TickerProviderStateMixin<Square> {
  late AnimationController _pressAnimationController;
  late Animation<List<BoxShadow>> _shadowAnimation;

  @override
  void initState() {
    super.initState();

    _pressAnimationController = AnimationController(vsync: this)..addListener(() => setState(() {}));
    _shadowAnimation = BoxShadowListTween(begin: normalShadows, end: pressedShadows).animate(_pressAnimationController);
  }

  @override
  void dispose() {
    _pressAnimationController.dispose();

    super.dispose();
  }

  Future<void> animateDown() async {
    try {
      await _pressAnimationController
          .animateTo(1, duration: const Duration(milliseconds: 100), curve: Curves.easeOutQuart)
          .orCancel;
    } on Exception {
      // Will throw is onTapUp happens too fast. Ignore the exception
    }
  }

  Future<void> animateUp() async {
    try {
      await _pressAnimationController
          .animateTo(0, duration: const Duration(milliseconds: 100), curve: Curves.easeOutQuart)
          .orCancel;
    } on Exception {
      // Will throw is onTapDown happens too fast. Ignore the exception
    }
  }

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.all(4.0),
      child: Opacity(
        opacity: 0.8,
        child: DecoratedBox(
          decoration: BoxDecoration(
            boxShadow: _shadowAnimation.value,
          ),
          child: Stack(
            children: [
              const Positioned.fill(
                child: ColoredBox(
                  color: Color(0xff20c0a0),
                ),
              ),
              GestureDetector(
                behavior: HitTestBehavior.opaque,
                onTapDown: (details) => animateDown(),
                onTapUp: (details) => animateUp(),
                onTapCancel: () => animateUp(),
                child: const Center(
                  child: Padding(
                    padding: EdgeInsets.all(12.0),
                    child: Text("Wide card"),
                  ),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}

class BoxShadowListTween extends Tween<List<BoxShadow>> {
  BoxShadowListTween({required List<BoxShadow> begin, required List<BoxShadow> end}) : super(begin: begin, end: end);

  @override
  List<BoxShadow> lerp(double t) => BoxShadow.lerpList(begin, end, t)!;
}

const normalShadows = [
  BoxShadow(
    color: Color(0x39000000),
    offset: Offset(0.0, 1.5),
    blurRadius: 3.0,
    spreadRadius: 0.0,
    blurStyle: BlurStyle.normal,
  ),
  BoxShadow(
    color: Color(0x6c000000),
    offset: Offset(0.0, 6.0),
    blurRadius: 12.0,
    spreadRadius: 0.0,
    blurStyle: BlurStyle.normal,
  )
];

const pressedShadows = [
  BoxShadow(
    color: Color(0x40000000),
    offset: Offset(0.0, 1.0),
    blurRadius: 2.0,
    spreadRadius: 0.0,
    blurStyle: BlurStyle.normal,
  ),
  BoxShadow(
    color: Color(0x73000000),
    offset: Offset(0.0, 4.0),
    blurRadius: 8.0,
    spreadRadius: 0.0,
    blurStyle: BlurStyle.normal,
  )
];
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/flutter/flutter/assets/1520279/e33d5d3b-9530-46a7-95b2-a94157dbd39e

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

I'm not sure why it reports an issue with CocoaPods. There is no problem in practice. I can run the app with flutter commands and through XCode as well. We have some special environment configurations because of our CI, so maybe that is the reason. Anyway, the issue is not related to that.

<details open><summary>Doctor output</summary>

```console
[!] Flutter (Channel [user-branch], 3.16.5, on macOS 14.1.2 23B92 darwin-arm64, locale en-NL)
    ! Flutter version 3.16.5 on channel [user-branch] at /Users/gabrielgava/signify/repos/hue_blue_2/dev/flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at https://flutter.dev/docs/get-started/install.
    ! Upstream repository unknown source is not a standard remote.
      Set environment variable "FLUTTER_GIT_URL" to unknown source to dismiss this error.
    • Framework revision 78666c8dc5 (7 days ago), 2023-12-19 16:14:14 -0800
    • Engine revision 3f3e560236
    • Dart version 3.2.3
    • DevTools version 2.28.4
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and
      upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/gabrielgava/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode-15.0.1.app/Contents/Developer
    • Build 15A507
    ✗ CocoaPods installed but not working.
        You appear to have CocoaPods installed but it is not working.
        This can happen if the version of Ruby that CocoaPods was installed with is different from the one being used to invoke it.
        This can usually be fixed by re-installing CocoaPods.
      To re-install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] IntelliJ IDEA Community Edition (version 2023.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 76.2.4
    • Dart plugin version 232.9559.10

[✓] VS Code (version 1.84.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.74.0

[✓] Connected device (3 available)
    • iPhone 15 Pro (mobile) • FB4703C2-F962-4F30-8518-37A5A42CB9D0 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-0 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 14.1.2 23B92 darwin-arm64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 120.0.6099.129

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
```

</details>

**Comment by gabrielgarciagava** [comment] 2023-12-27 12:56
I was able to remove a little bit more code. Now removing the Animation or the Opacity makes the problem go away.

```dart
// Copyright 2014 The Flutter Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

import 'package:flutter/material.dart';

void main() => runApp(const AnimatedShadowIssueExampleApp());

class AnimatedShadowIssueExampleApp extends StatelessWidget {
  const AnimatedShadowIssueExampleApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(title: const Text('Bug example')),
        backgroundColor: const Color(0xff42ff42),
        body: const SizedBox(height: 180, child: AnimatedShadowIssue()),
      ),
    );
  }
}

class AnimatedShadowIssue extends StatelessWidget {
  const AnimatedShadowIssue({super.key});

  @override
  Widget build(BuildContext context) {
    return const CustomScrollView(
      scrollDirection: Axis.horizontal,
      slivers: [
        SliverToBoxAdapter(child: Square()),
        SliverToBoxAdapter(child: Square()),
        SliverToBoxAdapter(child: Square()),
        SliverToBoxAdapter(child: Square()),
        SliverToBoxAdapter(child: Square()),
      ],
    );
  }
}

class Square extends StatefulWidget {
  const Square({super.key});

  @override
  State<Square> createState() => _SquareState();
}

class _SquareState extends State<Square> with TickerProviderStateMixin<Square> {
  late AnimationController _pressAnimationController;
  late Animation<List<BoxShadow>> _shadowAnimation;

  @override
  void initState() {
    super.initState();

    _pressAnimationController = AnimationController(vsync: this)..addListener(() => setState(() {}));
    _shadowAnimation = BoxShadowListTween(begin: normalShadows, end: pressedShadows).animate(_pressAnimationController);
  }

  @override
  void dispose() {
    _pressAnimationController.dispose();

    super.dispose();
  }

  Future<void> animateDown() async {
    try {
      await _pressAnimationController
          .animateTo(1, duration: const Duration(milliseconds: 100), curve: Curves.easeOutQuart)
          .orCancel;
    } on Exception {
      // Will throw is onTapUp happens too fast. Ignore the exception
    }
  }

  Future<void> animateUp() async {
    try {
      await _pressAnimationController
          .animateTo(0, duration: const Duration(milliseconds: 100), curve: Curves.easeOutQuart)
          .orCancel;
    } on Exception {
      // Will throw is onTapDown happens too fast. Ignore the exception
    }
  }

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.symmetric(horizontal: 6.0, vertical: 18.0),
      child: Opacity(
        opacity: 0.8,
        child: DecoratedBox(
          decoration: BoxDecoration(
            boxShadow: _shadowAnimation.value,
          ),
          child: GestureDetector(
            behavior: HitTestBehavior.opaque,
            onTapDown: (details) => animateDown(),
            onTapUp: (details) => animateUp(),
            onTapCancel: () => animateUp(),
            child: const Center(
              child: Padding(
                padding: EdgeInsets.all(12.0),
                child: Text("Wide card"),
              ),
            ),
          ),
        ),
      ),
    );
  }
}

class BoxShadowListTween extends Tween<List<BoxShadow>> {
  BoxShadowListTween({required List<BoxShadow> begin, required List<BoxShadow> end}) : super(begin: begin, end: end);

  @override
  List<BoxShadow> lerp(double t) => BoxShadow.lerpList(begin, end, t)!;
}

const normalShadows = [
  BoxShadow(
    color: Color(0x3900ff00),
    offset: Offset(0.0, 1.5),
    blurRadius: 3.0,
    spreadRadius: 0.0,
    blurStyle: BlurStyle.normal,
  ),
  BoxShadow(
    color: Color(0x6c000000),
    offset: Offset(0.0, 6.0),
    blurRadius: 12.0,
    spreadRadius: 0.0,
    blurStyle: BlurStyle.normal,
  )
];

const pressedShadows = [
  BoxShadow(
    color: Color(0x4000ff00),
    offset: Offset(0.0, 1.0),
    blurRadius: 2.0,
    spreadRadius: 0.0,
    blurStyle: BlurStyle.normal,
  ),
  BoxShadow(
    color: Color(0x73000000),
    offset: Offset(0.0, 4.0),
    blurRadius: 8.0,
    spreadRadius: 0.0,
    blurStyle: BlurStyle.normal,
  )
];
```

This code makes me believe the issue is a combination of Opacity and Shadow rendering.

**Comment by danagbemava-nc** [comment] 2023-12-28 11:09
Hi @gabrielgarciagava, it would appear that this has been fixed on the master channel, can you check with the code sample on the master channel as well to see if this reproduces over there?

**Comment by Taym95** [comment] 2023-12-28 12:09
@danagbemava-nc how do you know it is fixed in master did you test it?

**Comment by gabrielgarciagava** [comment] 2023-12-28 12:41
@danagbemava-nc @Taym95 I tested the sample app in the master branch and it indeed looks like it is fixed. I also tested it in our main project and it looks to be good there also.

@danagbemava-nc Is there any chance to see this fix cherry-picked to current stable channel? Also, do you have any idea which pull request has fixed this problem? Thank you.

**Comment by danagbemava-nc** [comment] 2023-12-29 06:57
Hi @gabrielgarciagava, thanks for confirming that it has been fixed on the master channel. 

It appears that this has also been fixed on the beta channel, this means that it will most likely be in the next stable version. 

Unfortunately, I don't know the particular pr/commit that fixed it.

However, per our triage policy I'll be closing this since it has been fixed on the master/beta channels. 

Thank you

**Closed by danagbemava-nc** 2023-12-29 06:57 UTC
Labels: in triage
