### ISSUE TITLE
[tool_crash] TemplateException: Value was missing for variable tag: androidFlutterJar. (4:24)

### ISSUE THREAD

**Issue by Maximuss-cmyk** [flutter/flutter#60358] opened 2020-06-26 13:44 UTC
I have flutter and dart already installed and I have been able to work on flutter projects in the past, but now when I create a new project none of the conventional folders appear.

I expected to see something like this:

![2020-06-26 15_29_54-](https://user-images.githubusercontent.com/67269178/85862386-fbd78c80-b7c1-11ea-8b9d-ef82916d6fef.png)

But currently this is what I see when entering a new project:
![image](https://user-images.githubusercontent.com/67269178/85862494-21649600-b7c2-11ea-825b-9e80333c58fa.png)

To me it looks like even though I created a new flutter project Android Studio looks at it as simply a blank new project, as the flutter icon is not in the top left where it usually is with the project folder.

When running flutter doctor I get the following:

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, 1.19.0-4.1.pre, on Microsoft Windows [Version 10.0.18362.175], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[√] Android Studio (version 3.6)
[√] Connected device (1 available)
```

Furthermore there are Flutter logs that are automatically created when I create a new flutter project with crash reports. Here are the details of the reports:

Flutter crash report.
Please report a bug at https://github.com/flutter/flutter/issues.

## command

flutter --no-color create --template app --description Displaying the time all around the world --org com.example --project-name thetimeoftheworld the_time_of_the_world

## exception

TemplateException: Value was missing for variable tag: androidFlutterJar. (4:24)
      <root url="jar://{{{androidFlutterJar}}}!/" />
                       ^

```
#0      Renderer.visitVariable (package:mustache_template/src/renderer.dart:97:9)
#1      VariableNode.accept (package:mustache_template/src/node.dart:46:43)
#2      Renderer.render.<anonymous closure> (package:mustache_template/src/renderer.dart:52:30)
#3      List.forEach (dart:core-patch/growable_array.dart:289:8)
#4      Renderer.render (package:mustache_template/src/renderer.dart:52:13)
#5      Template.render (package:mustache_template/src/template.dart:42:14)
#6      Template.renderString (package:mustache_template/src/template.dart:34:5)
#7      MustacheTemplateRenderer.renderString (package:flutter_tools/src/build_runner/mustache_template.dart:15:67)
#8      Template.render.<anonymous closure> (package:flutter_tools/src/template.dart:219:66)
#9      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
#10     Template.render (package:flutter_tools/src/template.dart:155:24)
#11     CreateCommand._renderTemplate (package:flutter_tools/src/commands/create.dart:628:21)
#12     _rootRunUnary (dart:async/zone.dart:1198:47)
#13     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#14     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#16     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#17     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#18     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#19     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#20     Template.fromName (package:flutter_tools/src/template.dart)
#21     _rootRunUnary (dart:async/zone.dart:1198:47)
#22     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#23     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#24     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#25     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#26     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#27     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#28     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#29     _templateImageDirectory (package:flutter_tools/src/template.dart)
#30     _rootRunUnary (dart:async/zone.dart:1198:47)
#31     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#32     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#33     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#34     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#35     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#36     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#37     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#38     readAnyConfigFileUri (package:package_config/src/package_config_io.dart)
#39     _rootRunUnary (dart:async/zone.dart:1198:47)
#40     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#41     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#42     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#43     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#44     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#45     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
#46     _rootRun (dart:async/zone.dart:1190:13)
#47     _CustomZone.run (dart:async/zone.dart:1093:19)
#48     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#49     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#50     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#51     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#52     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#53     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

## flutter doctor

```
[✓] Flutter (Channel beta, 1.19.0-4.1.pre, on Microsoft Windows [Version 10.0.18362.175], locale en-US)
    • Flutter version 1.19.0-4.1.pre at C:\src\flutter
    • Framework revision f994b76974 (2 weeks ago), 2020-06-09 15:53:13 -0700
    • Engine revision 9a28c3bcf4
    • Dart version 2.9.0 (build 2.9.0-14.1.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\Ryan.Aidan\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[✓] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 46.0.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[✓] Connected device (1 available)
    • sdk gphone x86 • emulator-5554 • android-x86 • Android 11 (API 30) (emulator)

• No issues found!
```

**Comment by VladyslavBondarenko** [comment] 2020-06-26 14:58
I'm not experiencing this when creating app with Android studio on Mac

**Comment by jonahwilliams** [comment] 2020-06-26 16:56
Duplicate of https://github.com/flutter/flutter/issues/57985

> Workaround is to delete the following files from your Flutter install location:

packages/flutter_tools/templates/app/.idea/libraries/Flutter_for_Android.xml.tmpl
packages/flutter_tools/templates/module/common/.idea/libraries/Flutter_for_Android.xml.tmpl
packages/flutter_tools/templates/plugin/.idea/libraries/Flutter_for_Android.xml.tmpl


Fixed via https://github.com/flutter/flutter/pull/59706

**Closed by jonahwilliams** 2020-06-26 16:56 UTC
Labels: severe: fatal crash, tool
