### ISSUE TITLE
i got this error

### ISSUE THREAD

**Issue by Sreejith93** [flutter/flutter#61725] opened 2020-07-17 13:35 UTC
\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher-5.5.0\android\src\main\java\io\flutter\plugins\urllauncher\WebViewActivity.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

**Comment by TSCSOftware** [comment] 2020-07-17 14:05
not wrong.it is your first build??
now worring some plugins {admob, firebase}like that!!

**Comment by Abhishek01039** [comment] 2020-07-17 15:12
@Sreejith93  This is just a warning. You can ignore it

**Comment by VladyslavBondarenko** [comment] 2020-07-17 15:34
Duplicate of https://github.com/flutter/flutter/issues/60986

**Closed by VladyslavBondarenko** 2020-07-17 15:34 UTC
