### ISSUE TITLE
Hot reload / Hot restart don't work in Android Studio 3.6.3 - Windows 10

### ISSUE THREAD

**Issue by OliverCulleyDeLange** [flutter/flutter#57937] opened 2020-05-25 10:59 UTC
Given the most simple app, seen below, when i change the text, and hot reload - nothing changes. 
```
import 'package:flutter/material.dart';

void main() {
  runApp(
    MaterialApp(
      title: 'Test App',
      home: Scaffold(
        body: Center(child: Text("Test1")),
      ),
    ),
  );
}
```

Alot of people seem to be complaining of the same at the bottom of [this issue](https://github.com/flutter/flutter/issues/40352)

On my normal sized app, the issue is slightly different, when i hot reload, the file change doesn't seem to be detected as i get the following output:
```
Performing hot reload...
Syncing files to device Moto G 5S Plus...  
Reloaded 0 of 866 libraries in 547ms.
````

Also, when i hot restart, the app restarts but changes don't appear:
```
Performing hot restart...
Syncing files to device Moto G 5S Plus...
Restarted application in 4,114ms.
```

#### Flutter doctor
```
C:\Users\olly_>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.17.1, on Microsoft Windows [Version 10.0.18363.836], locale en-GB)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[√] Android Studio (version 3.6)
[!] IntelliJ IDEA Community Edition (version 2019.3)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] VS Code (version 1.45.1)
[√] Connected device (1 available)

! Doctor found issues in 1 category.
```

I was on beta channel, but switched back to stable to see if that fixed anything, which it didn't. 

#### Possibly related
I did notice that flutter doctor was failing to get android licenses statuses as Android Studio seems to have deprecated the old 'build' folder in favor of 'cmdline-tools' - see my comment on this [SO Answer](https://stackoverflow.com/a/61040516/3014299) - So i had to install the 'Android SDK Tools (Obsolete)' from Android Studio Sdk Manager. 

Apologies if there's a duplicate ticket somewhere in issues already, I had a quick scan but couldn't find anything that seemed to be the same thing.

**Comment by TahaTesser** [comment] 2020-05-25 13:24
duplicate of https://github.com/flutter/flutter/issues/57796

**Closed by TahaTesser** 2020-05-25 13:24 UTC
