### ISSUE TITLE
onGenerateRoute called multiple times for /home/1/2/3/4/5

### ISSUE THREAD

**Issue by stuz5000** [flutter/flutter#71786] opened 2020-12-06 01:12 UTC
I request an initial route of `/home/1/2/3/4/5`, but  onGenerateRoute is called 7 times, 7 states are allocated and 7 widgets are built

One is expected for each.

## Steps to Reproduce

Run the following with Chrome (web) as the build target.

```
[1] Building widget /
initState /
[1] Building widget /home
initState /home
[1] Building widget /home/1
initState /home/1
[1] Building widget /home/1/2
initState /home/1/2
[1] Building widget /home/1/2/3
initState /home/1/2/3
[1] Building widget /home/1/2/3/4
initState /home/1/2/3/4
[1] Building widget /home/1/2/3/4/5
initState /home/1/2/3/4/5
```

This can have dire perform consequences (because excessive web requests and drawing may result) and generate errors in the application (e.g. `/home/1/2/3` may have no meaning -- I requested `/home/1/2/3/4/5`).

Furthermore, is appears that although `/home/1/2/3/4/5`
is correctly (finally) displayed, the other 6 states are not disposed, and it is therefore difficult to detect that these pages are not needed or wanted, and cancel asynchronous workers from loading their dynamic content.

I see the same problems in the Android emulator (Nexus 7)

```
import 'package:flutter/material.dart';

Route onGenerateRoute(RouteSettings settings) {
  int ncalls = 0;
  Widget builder_(BuildContext context) {
    ncalls++;
    print("[$ncalls] Building widget ${settings.name}");
    return Home(Uri.parse(settings.name));
  }

  return MaterialPageRoute<void>(
    builder: builder_, //(context) => path.builder(context, match),
    settings: settings,
  );

  // Route(settings: settings);
}

class Home extends StatefulWidget {
  Uri uri;  /// Determines content of page
  Home(this.uri, {Key key}) : super(key: key);

  @override
  _HomeState createState() => _HomeState();
}

class _HomeState extends State<Home> {
  @override
  void initState(){
    print("initState ${widget.uri}");
    super.initState();
  }

  @override
  void dispose(){
    super.dispose();
    print("dispose ${widget.uri}");
  }

  @override
  Widget build(BuildContext context) {
    Widget child = Text("home\n${widget.uri}");
    child = Center(child: child);
    child = Container(color: Colors.white, child: child);
    child = Scaffold(body: child);
    return child;
  }
}

//
//////////////////////////////////////////
//

void main() {
  runApp(MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Consultation Tagger',
      initialRoute: "/home/1/2/3/4/5",
      onGenerateRoute: onGenerateRoute)
  );
}
```

<details>

```
/home/sir/development/flutter/bin/flutter doctor --verbose
[✓] Flutter (Channel unknown, 1.22.0-12.2.pre, on Linux, locale en_US.UTF-8)
    • Flutter version 1.22.0-12.2.pre at /home/sir/development/flutter
    • Framework revision 2bafdc8226 (2 months ago), 2020-09-25 12:48:22 -0700
    • Engine revision f763b5b9b9
    • Dart version 2.10.0 (build 2.10.0-110.5.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/sir/Android/Sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /usr/lib/jvm/java-8-oracle/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] Connected device (2 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 86.0.4240.193

! Doctor found issues in 1 category.
Process finished with exit code 0
```

</details>

**Comment by Plegizplegiz** [comment] 2020-12-06 09:33
su 6.12.2020 klo 3.14 Stuart Reynolds <notifications@github.com> kirjoitti:

**Comment by Plegizplegiz** [comment] 2020-12-07 08:40
su 6.12.2020 klo 11.32 Ismo Lehtinen <lehtinenismo1@gmail.com> kirjoitti:

**Comment by darshankawar** [comment] 2020-12-07 09:40
@stuz5000 
Your `flutter doctor` says `Channel unknown, 1.22.0-12.2.pre`, but not sure if it represents dev, master or beta ?
Also, can you switch to latest version from the branch you are on and try again to see if you see similar behavior ?

**Comment by stuz5000** [comment] 2020-12-07 19:14
Yes -- the message seems to result with following the flutter install and upgrade instructions.

Anyhow... refresh install of beta gives the same problem.
```
/home/sir/development/flutter/bin/flutter doctor --verbose
[✓] Flutter (Channel beta, 1.24.0-10.2.pre, on Linux, locale en_US.UTF-8)
    • Flutter version 1.24.0-10.2.pre at /home/sir/development/flutter
    • Framework revision 022b333a08 (3 weeks ago), 2020-11-18 11:35:09 -0800
    • Engine revision 07c1eed46b
    • Dart version 2.12.0 (build 2.12.0-29.10.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/sir/Android/Sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /usr/lib/jvm/java-8-oracle/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] IntelliJ IDEA Ultimate Edition (version 2020.3)
    • IntelliJ at /snap/intellij-idea-ultimate/263
    • Flutter plugin version 51.0.4
    • Dart plugin version 203.5981.152

[✓] IntelliJ IDEA Ultimate Edition (version 2020.2)
    • IntelliJ at /snap/intellij-idea-ultimate/261
    • Flutter plugin version 50.0
    • Dart plugin version 202.7319.5

[✓] Connected device (3 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Web Server (web)                   • web-server    • web-javascript • Flutter Tools
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 86.0.4240.193

! Doctor found issues in 1 category.
Process finished with exit code 0
```

**Comment by darshankawar** [comment] 2020-12-08 06:10
@stuz5000 
Please see [this](https://github.com/flutter/flutter/issues/61351#issuecomment-657789756) issue comment and see if it answers your question.

**Comment by stuz5000** [comment] 2020-12-08 17:06
Thanks. I left a comment here:
  https://github.com/flutter/flutter/issues/61351#issuecomment-740763322

It helps, although onGenerateRoute still gets called twice for the same route. It doesn't not called initState multiple times, so, thankful for that.

**Comment by darshankawar** [comment] 2020-12-09 06:24
@stuz5000 
I see below in console after running your code sample from https://github.com/flutter/flutter/issues/61351#issuecomment-740763322:

```
[1] Building widget /home/1/2/3/4/5
initState /home/1/2/3/4/5
[1] Building widget /home/1/2/3
initState /home/1/2/3
[1] Building widget /home/1/2/3
initState /home/1/2/3
[1] Building widget /home/1/2/3/4
initState /home/1/2/3/4

```
What's the expected behavior you are looking for ?

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel beta, 1.24.0-10.2.pre, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-IN)
    • Flutter version 1.24.0-10.2.pre at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 022b333a08 (3 weeks ago), 2020-11-18 11:35:09 -0800
    • Engine revision 07c1eed46b
    • Dart version 2.12.0 (build 2.12.0-29.10.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (2 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome
      87.0.4280.88

• No issues found!


```

</details>

**Comment by stuz5000** [comment] 2020-12-09 18:58
What's the reason for 4x builds of the widget (I didn't see multiple initState calls upon updating the browser bar, but that behavior is worse).

I would expect to be able to enter a route in the browser bar, which would be followed by:
 - a single call onGenerateRoute with that URI as the route name, followed by:
 - a single call to build function returned by onGenerateRoute, followed by
 - a single call to the initState function of the widget of the build function

Why should we see multiples of any of the above?

**Comment by darshankawar** [comment] 2020-12-10 05:43
Keeping this issue open for further analysis. https://github.com/flutter/flutter/issues/71786#issuecomment-741560622

**Comment by mdebbar** [comment] 2021-01-14 19:49
@stuz5000 is this an issue only on web? Could you verify other platforms (native iOS/Android)? My understanding is this is the expected behavior.

**Comment by stuz5000** [comment] 2021-01-14 19:52
Its the same also for Android.

If means 'expected behavior' is 'by design'. Sure I believe you.

If 'expected behavior' mean sensible, expected, clearly understood behavior for API users, I do not.

**Comment by mdebbar** [comment] 2021-01-14 22:27
> If means 'expected behavior' is 'by design'.

Yes, it's by design. I think what you want is `onGenerateInitialRoutes` as suggested in the other issue. But I see you commented saying it's called twice on app load. Is that expected, @chunhtai ?

**Comment by stuz5000** [comment] 2021-01-14 22:44
Overriding onGenerateInitialRoutes does let me work around the confusing default behavior. 
The only other minor problem is that build is being called 4 times (for the desired single initial route).

initState and onGenerateRoute is called just once, so that's a big win.
(web and Android).

**Comment by ronytesler** [comment] 2021-05-16 17:28
Any update? using onGenerateInitialRoutes and returning a list of one MaterialPageRoute is fine?

**Comment by chunhtai** [comment] 2021-05-17 17:08
@ronytesler If that meets your use case, I can't see a reason not to do that. @stuz5000 In general we don't guarantee how many times the build will be called, so it is encouraged to keep the build method simple and fast. My guess for why it is called 4 times is probably the platform flushes platform settings to the app which causes rebuild in the first couple of frames.

**Comment by adrian-moisa** [comment] 2021-11-11 10:57
I faced the same issue. I'm going to share what I've learned out of my own research. 

- When opening a deep link, the flutter router recreates all the prior router/history states of the app.
- This means that the back button can return the user trough all the screens needed to get there even if it got there via deep linking.
- This behavior makes sense for mobile devices. However, on the web, this behavior is not wanted.
- If we load a deep link such as: http://domain/s/lorem-ipsum/all/posts we end up initialising each route level if it has it's own screen defined
- If you happen to have the same component on all levels this in turn leads to 5 sets of duplicated API calls which is completely unacceptable
- Therefore we can use `onGenerateInitialRoutes` to prevent this behavior from occurring.
- The default history stack is overridden with a router/history stack with just one state


**main.dart**

    ...
    return MaterialApp(
      ...
      initialRoute: user != null ? '/' : '/login',
      
      // The default history stack is overridden with a router/history stack with just one state
      // In this case I used fluro but any other onGenerateRoute method will do the trick
      onGenerateInitialRoutes: (initialRoute) =>
          [appRouter.generator(RouteSettings(name: initialRoute))!],
      onGenerateRoute: appRouter.generator,
    );



**router.dart**

    final appRouter = FluroRouter();
    
    void defineAppRoutes() {
      final routes = {
        // Auth
        '/login': LoginPage(),
        '/register': RegisterPage(),
    
        // Pages
        '/': MainFeed(),
        '/s': MainFeed(),
        '/s/:spaceId': MainFeed(),
        '/s/:spaceId/:activityId': MainFeed(),
        '/s/:spaceId/:activityId/posts': MainFeed(),
        ... many more such routes
      };

      routes.forEach((route, page) {
        appRouter.define(route, handler: Handler(
          handlerFunc: (BuildContext? context, Map<String, List<String>> params) =>
          page,
        ));
      });
    
      // Not found
      appRouter.notFoundHandler = Handler(
          handlerFunc: (BuildContext? context, Map<String, dynamic> params) {
            return NotFoundPage();
          });
    }

**Performance/Billing concerns**

Some of you might be using Firebase and possibly planning to run an app with high volumes of traffic. Therefore it is quite important to pay attention to what your router does. You might be sending requests for more data than what you actually need to load for your first view of the app. Especially for sharing links on the web this might be costly if you don't optimize your API calls. Since Firebase does everything via websockets make sure you either place print statements in all your API calls or you can also switch to json-server during development to get a better view of the HTTP calls in the developer tools. There are many ways to handle this optimisation. What matters first of all is to be aware of your API calls and how many. I was able to generate 15K api calls with 3-4 work hours using an unoptimised version of my app.

I'm still learning some of this stuff so please excuse me if I used some wrong terms. Let me know how can I improve this answer. Hopefully it helps you.

@stuz5000 
-`initState` will be called as many route segments as you have unless you override `onGenerateInitialRoutes`
- `build` is called as many times as flutter thinks there's a change event. As long as you don't do any complex logic or any API calls during the build stage it's not that bad. Similar to React or Angular the change detection algo makes sure that if duplicate builds happen only the relevant changes are computed.

**Comment by karomancer** [comment] 2022-02-17 03:06
Having the same issue; I see it called 4 times on Android. iOS is ok.

The 3rd and 4th time the provided method for `onGenerateRoute` is called, the `routeName` is wrong despite `pushNamed` providing the right one. It appears that `pushNamed` is being called elsewhere internally with a different `RouteSettings` parameter rather than from my own code.

**Comment by Piinks** [comment] 2022-06-16 23:13
It sounds like we got to the bottom of this based on the comments above, @stuz5000 is this still an issue you are experiencing?

**Comment by stuz5000** [comment] 2022-06-20 02:35
Honestly ... this happened more than one and a half years ago. I haven't touched flutter for quite some time and don't have a dev environment set up to re-test. But everyone else it happy, sounds great to me.

**Comment by Piinks** [comment] 2022-06-22 22:20
Ok thanks for getting back to us! Since this issue has not been seen for a while, it sounds like it was resolved. I am going to close this, but if you see the issue again let us know and we can take another look! Thanks!

**Closed by Piinks** 2022-06-22 22:20 UTC
Labels: framework, f: routes, passed first triage, has reproducible steps, found in release: 1.24
