### ISSUE TITLE
Many of our flutter widget tests are failing, when the widget under test is not wrapped in MaterialApp

### ISSUE THREAD

**Issue by yyoon** [flutter/flutter#11859] opened 2017-08-31 00:12 UTC
## Steps to Reproduce

I discovered that many of our flutter widget tests are broken, with a lot of exceptions generated like below:
https://gist.github.com/yyoon/cdb7fd3dc7f408866c123bd1f25f754f

The above exceptions were generated by running the test file here:
https://github.com/fuchsia-mirror/modules-email/blob/1296d9d0005092e3287c4afe350f306acefcefe9/modules/composer/test/message_text_input_test.dart

I haven't tried this everywhere, wrapping the widget inside the `pumpWidget` call with a `MaterialApp` widget seems to resolve this issue.

Since we can't run these tests in our CI yet, I don't know when this started to happen exactly.

Another related issue:
The [example test code](https://flutter.io/testing/#widget-testing) shown in the official webpage is also broken in a similar way. Wrapping the widget with a `Directionality` or a `MaterialApp` fixes the problem there.

## Flutter Doctor

```
[✓] Flutter (on Linux, locale en_US.UTF-8, channel unknown)
    • Flutter at /usr/local/google/home/youngseokyoon/Programming/fuchsia/lib/flutter
    • Framework revision f0bf7b5c8c (2 hours ago), 2017-08-30 15:37:35 -0700
    • Engine revision f9e00a7c72
    • Tools Dart version 1.25.0-dev.11.0

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at /usr/local/google/home/youngseokyoon/Android/Sdk
    • Platform android-25, build-tools 25.0.3
    • Java binary at: /opt/android-studio-2.3/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] Android Studio (version 2.3)
    • Android Studio at /opt/android-studio-2.3
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[-] IntelliJ IDEA Community Edition (version 2017.1)
    ✗ Flutter plugin version 13.1 - the recommended minimum version is 16.0.0
    • Dart plugin version 171.4424
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[✓] Connected devices
    • None
```

**Comment by Hixie** [comment] 2017-08-31 00:17
Yeah, you need a Directionality around any widget that depends on text direction (such as Row). This is part of our implementing RTL. MaterialApp takes care of this for you. @apwilson worked on adding Directionality widgets in the appropriate places for Fuchsia, so he can probably help you.

**Comment by yyoon** [comment] 2017-08-31 00:26
Yes, @apwilson included the `Directionality` widget to the top-level widget that every module uses, so that part is fine. I was referring to the individual widget tests though. Is it expected that everyone who writes widget tests should wrap their widgets with `Directionality`? If that's the case, I think that should be documented/communicated better somehow. Also, as I mentioned in the original post, the example test code on the official website is broken the same way, so this should probably be fixed.

**Comment by Hixie** [comment] 2017-08-31 03:23
Yeah we're still rolling this stuff out. If you find any particular part of the Web site or API docs that need updating please do file a bug listing those places.

As far as tests go, I expect we'll be introducing a method that automatically wraps the widgets under test in things like Directionality. The problem is, there's a lot of them. Most material widgets need a Material ancestor, many widgets need a MediaQuery and a Directionality, widgets with text are all going to need a Localization widget, many widgets (e.g. any with tooltips) need an Overlay, etc. But then it's worse than that because you have to actually test the widgets. So for example, with Directionality, you need to test each widget in LTR mode and in RTL mode, to make sure it works right in both modes, so we can't exactly make a simple wrap method that just wraps the widget in a single set of things.

**Comment by yyoon** [comment] 2017-09-01 23:08
For the example test on the website, I could send a PR for adding a `Directionality` widget there to fix that specific test, if that's how you would fix it. Or would you prefer me to just file an issue?

Having a test-specific utility that automatically wraps things would be really nice. But I understand the point that the widgets should be tested under different configurations of those wrapping widgets.

I originally thought this was a regression of some sort because our tests were working fine until very recently. But it sounds like it's not really a bug. I fixed our tests by adding appropriate wrappers. Feel free to close this issue.

**Comment by Hixie** [comment] 2017-09-01 23:16
Can you point me to the specific thing on the web site?

**Comment by Hixie** [comment] 2017-09-01 23:17
For what it's worth, I've been starting to create per-test-file functions called "boilerplate" that introduce the relevant widgets for specific tests, since they seem to vary so much. (Widgets that are sometimes needed include: Overlay, Directionality, Material, Localizations, Navigator, Center...)

**Comment by Hixie** [comment] 2017-09-01 23:18
Also, be aware that I will shortly be landing a patch (https://github.com/flutter/flutter/pull/11888) that requires a Directionality for every subtree containing a Text widget, which may affect even more tests.

**Comment by yyoon** [comment] 2017-09-01 23:19
The example test I'm referring to is here:
https://flutter.io/testing/#widget-testing

It uses `Slider` widget, but doesn't have a `Directionality` widget around it.

**Comment by Hixie** [comment] 2017-09-02 06:12
We should just wrap that one in a `new MaterialApp(home: ...)`

**Comment by yyoon** [comment] 2017-09-05 18:48
Created a PR for that. Please take a look.
https://github.com/flutter/website/pull/661

**Comment by Hixie** [comment] 2018-05-18 20:43
Going to close this issue as obsolete.

**Closed by Hixie** 2018-05-18 20:43 UTC
