### ISSUE TITLE
[tool_crash] FileSystemException: Failed to decode data using encoding 'utf-8', null

### ISSUE THREAD

**Issue by thearaks** [flutter/flutter#154607] opened 2024-09-04 09:02 UTC
## Command
```sh
flutter --no-color run --machine --track-widget-creation --device-id=ee43c9d8 --start-paused --flavor=staging --dart-define=flutter.inspector.structuredErrors=true lib/main.dart
```

## Steps to Reproduce
1. Add the character `ç` to `andorid/local.properties` file, i.e.:
```
sdk.dir=/Users/user/Library/Android/sdk
flutter.sdk=/Users/user/Library/flutter
flutter.buildMode=debug
flutter.versionName=1.0.0
flutter.versionCode=1
#ç
```
2. Run the app

The build process will crash, even if it shouldn't since `ç` [is a valid UTF-8 character](https://www.fileformat.info/info/unicode/char/00e7/index.htm).

## Logs
FileSystemException: Failed to decode data using encoding 'utf-8', null
```console
#0      _File._tryDecode (dart:io/file_impl.dart:615:7)
#1      _File.readAsStringSync (dart:io/file_impl.dart:624:7)
#2      ForwardingFile.readAsStringSync (package:file/src/forwarding/forwarding_file.dart:99:16)
#3      ErrorHandlingFile.readAsStringSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:230:22)
#4      _runSync (package:flutter_tools/src/base/error_handling_io.dart:600:14)
#5      ErrorHandlingFile.readAsStringSync (package:flutter_tools/src/base/error_handling_io.dart:229:12)
#6      new SettingsFile.parseFromFile (package:flutter_tools/src/base/utils.dart:173:59)
#7      updateLocalProperties (package:flutter_tools/src/android/gradle_utils.dart:732:29)
#8      AndroidProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:754:12)
#9      FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:381:21)
<asynchronous suspension>
#10     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1750:7)
<asynchronous suspension>
#11     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1408:27)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#13     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:420:9)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#16     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:5)
<asynchronous suspension>
```
```console
[✓] Flutter (Channel stable, 3.24.1, on macOS 14.5 23F79 darwin-x64, locale it-IT)
    • Flutter version 3.24.1 on channel stable at /Users/user/Library/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5874a72aa4 (2 settimane fa), 2024-08-20 16:46:00 -0500
    • Engine revision c9b9d5780d
    • Dart version 3.5.1
    • DevTools version 2.37.2

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/user/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/user/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)

[✓] VS Code (version 1.92.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.94.0

[✓] Connected device (5 available)
    • Pixel 7 (mobile)                         • 32021FDH2000SH            • android-arm64  • Android 14 (API 34)
    • MI 6 (mobile)                            • ee43c9d8                  • android-arm64  • Android 13 (API 33)
    • iPhone SE 3rd gen di Code Atlas (mobile) • 00008110-0008654122E8401E • ios            • iOS 17.6.1 21G93
    • macOS (desktop)                          • macos                     • darwin-x64     • macOS 14.5 23F79 darwin-x64
    • Chrome (web)                             • chrome                    • web-javascript • Google Chrome 128.0.6613.114

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 54e66469a933b60ddf175f858f82eaeb97e48c8d
### Plugins
cloud_firestore-5.3.0
cloud_firestore_web-4.1.2
cloud_functions-5.1.0
cloud_functions_web-4.9.12
firebase_analytics-11.3.0
firebase_analytics_web-0.5.9+2
firebase_auth-5.2.0
firebase_auth_web-5.12.6
firebase_core-3.4.0
firebase_core_web-2.17.5
firebase_crashlytics-4.1.0
path_provider-2.1.4
path_provider_android-2.2.10
path_provider_foundation-2.4.0
path_provider_linux-2.2.1
path_provider_windows-2.3.0
shared_preferences-2.3.2
shared_preferences_android-2.3.2
shared_preferences_foundation-2.5.2
shared_preferences_linux-2.4.1
shared_preferences_web-2.4.2
shared_preferences_windows-2.4.1

**Comment by danagbemava-nc** [comment] 2024-09-04 09:19
Closing this as a duplicate of https://github.com/flutter/flutter/issues/50723

**Closed by danagbemava-nc** 2024-09-04 09:19 UTC
Labels: in triage
