### ISSUE TITLE
iOS release error: Module 'firebase_admob' not found

### ISSUE THREAD

**Issue by jimmyff** [flutter/flutter#52406] opened 2020-03-11 14:00 UTC
All my debug builds of my app on iOS work (and the admob plugin worked with visible ads on my app). When I ran the simulator via Xcode my app would always have the red debug banner even if I'd done a `--release` build ([see my original issue](https://github.com/flutter/flutter/issues/52242#issuecomment-597376827)). I've now figured out how to get a real release build following the instructions here:
https://github.com/flutter/flutter/issues/51673#issuecomment-597215128
 

However when I change the Xcode schemes 'Build Configuration' to `Release` (or Profile) I now get an error when I try to run it:

**Module 'firebase_admob' not found**
This is in GeneratedPluginRegistrant.m on line 10 (source included below).

I've tried this using the flutter dev & master channel and have the same issue. I'm currently using master. I've tried removing my Pods folder and re-running `pod install`.

### GeneratedPluginRegistrant.m
```m
//
//  Generated file. Do not edit.
//

#import "GeneratedPluginRegistrant.h"

#if __has_include(<firebase_admob/FLTFirebaseAdMobPlugin.h>)
#import <firebase_admob/FLTFirebaseAdMobPlugin.h>
#else
@import firebase_admob;
#endif

#if __has_include(<firebase_analytics/FLTFirebaseAnalyticsPlugin.h>)
#import <firebase_analytics/FLTFirebaseAnalyticsPlugin.h>
#else
@import firebase_analytics;
#endif

#if __has_include(<firebase_core/FLTFirebaseCorePlugin.h>)
#import <firebase_core/FLTFirebaseCorePlugin.h>
#else
@import firebase_core;
#endif

#if __has_include(<url_launcher/FLTURLLauncherPlugin.h>)
#import <url_launcher/FLTURLLauncherPlugin.h>
#else
@import url_launcher;
#endif

#if __has_include(<webview_media/FLTWebViewFlutterPlugin.h>)
#import <webview_media/FLTWebViewFlutterPlugin.h>
#else
@import webview_media;
#endif

@implementation GeneratedPluginRegistrant

+ (void)registerWithRegistry:(NSObject<FlutterPluginRegistry>*)registry {
  [FLTFirebaseAdMobPlugin registerWithRegistrar:[registry registrarForPlugin:@"FLTFirebaseAdMobPlugin"]];
  [FLTFirebaseAnalyticsPlugin registerWithRegistrar:[registry registrarForPlugin:@"FLTFirebaseAnalyticsPlugin"]];
  [FLTFirebaseCorePlugin registerWithRegistrar:[registry registrarForPlugin:@"FLTFirebaseCorePlugin"]];
  [FLTURLLauncherPlugin registerWithRegistrar:[registry registrarForPlugin:@"FLTURLLauncherPlugin"]];
  [FLTWebViewFlutterPlugin registerWithRegistrar:[registry registrarForPlugin:@"FLTWebViewFlutterPlugin"]];
}

@end
```

### Pod version
```
jimmypro-7:eurovision jimmyff$ pod   --version 
1.9.0
```

### Podfile
```podfile
# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def parse_KV_file(file, separator='=')
  file_abs_path = File.expand_path(file)
  if !File.exists? file_abs_path
    return [];
  end
  generated_key_values = {}
  skip_line_start_symbols = ["#", "/"]
  File.foreach(file_abs_path) do |line|
    next if skip_line_start_symbols.any? { |symbol| line =~ /^\s*#{symbol}/ }
    plugin = line.split(pattern=separator)
    if plugin.length == 2
      podname = plugin[0].strip()
      path = plugin[1].strip()
      podpath = File.expand_path("#{path}", file_abs_path)
      generated_key_values[podname] = podpath
    else
      puts "Invalid plugin specification: #{line}"
    end
  end
  generated_key_values
end

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  # Flutter Pod

  copied_flutter_dir = File.join(__dir__, 'Flutter')
  copied_framework_path = File.join(copied_flutter_dir, 'Flutter.framework')
  copied_podspec_path = File.join(copied_flutter_dir, 'Flutter.podspec')
  unless File.exist?(copied_framework_path) && File.exist?(copied_podspec_path)
    # Copy Flutter.framework and Flutter.podspec to Flutter/ to have something to link against if the xcode backend script has not run yet.
    # That script will copy the correct debug/profile/release version of the framework based on the currently selected Xcode configuration.
    # CocoaPods will not embed the framework on pod install (before any build phases can generate) if the dylib does not exist.

    generated_xcode_build_settings_path = File.join(copied_flutter_dir, 'Generated.xcconfig')
    unless File.exist?(generated_xcode_build_settings_path)
      raise "Generated.xcconfig must exist. If you're running pod install manually, make sure flutter pub get is executed first"
    end
    generated_xcode_build_settings = parse_KV_file(generated_xcode_build_settings_path)
    cached_framework_dir = generated_xcode_build_settings['FLUTTER_FRAMEWORK_DIR'];

    unless File.exist?(copied_framework_path)
      FileUtils.cp_r(File.join(cached_framework_dir, 'Flutter.framework'), copied_flutter_dir)
    end
    unless File.exist?(copied_podspec_path)
      FileUtils.cp(File.join(cached_framework_dir, 'Flutter.podspec'), copied_flutter_dir)
    end
  end

  # Added by jimmy
  # add the Firebase pod for Google Analytics && admob 
  pod 'Firebase/Analytics'
  pod 'Firebase/AdMob'

  # Keep pod path relative so it can be checked into Podfile.lock.
  pod 'Flutter', :path => 'Flutter'

  # Plugin Pods

  # Prepare symlinks folder. We use symlinks to avoid having Podfile.lock
  # referring to absolute paths on developers' machines.
  system('rm -rf .symlinks')
  system('mkdir -p .symlinks/plugins')
  plugin_pods = parse_KV_file('../.flutter-plugins')
  plugin_pods.each do |name, path|
    symlink = File.join('.symlinks', 'plugins', name)
    File.symlink(path, symlink)
    pod name, :path => File.join(symlink, 'ios')
  end
end

# Prevent Cocoapods from embedding a second Flutter framework and causing an error with the new Xcode build system.
install! 'cocoapods', :disable_input_output_paths => true

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end

```

### Flutter doctor
```
[✓] Flutter (Channel master, v1.15.20-pre.20, on Mac OS X 10.14.6 18G1012, locale en-GB)
    • Flutter version 1.15.20-pre.20 at /Users/jimmyff/flutter-sdk
    • Framework revision 4049889d9e (11 hours ago), 2020-03-10 20:05:41 -0700
    • Engine revision 0e2c8feeeb
    • Dart version 2.8.0 (build 2.8.0-dev.12.0 9983424a3c)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/jimmyff/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Development/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.9.0

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Development/Android Studio.app/Contents
    • Flutter plugin version 40.2.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] IntelliJ IDEA Ultimate Edition (version 2017.2)
    • IntelliJ at /Applications/Development/IntelliJ IDEA.app
    ✗ Flutter plugin version 15.1 - the recommended minimum version is 16.0.0
    • Dart plugin version 172.3317.48
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```

**Comment by jimmyff** [comment] 2020-03-12 13:22
I've been hunting around trying to resolve this as I really need to release this app. 

I found a discrepency between debug vs profile & release: In Runner -> Build Settings -> Supported platforms:

Both Profile & Release were both set to `iphoneos` whereas Debug was set to `iOS` - I tried to set them all to `iOS` and it rebuilds however fails with error: 

```
Target aot_assembly_release failed: Exception: Unsupported iOS arch name "i386"
build failed.
Command PhaseScriptExecution failed with a nonzero exit code
```

I now think that it was supposed to be set that way, however I don't seem to be able to revert the settings? I get a pop up with the options iOS, macOs, tvOs, watchOs or Other - I can select those, but then if I select other a popup appears with iphonesimulator and iphoneos - I can't select either, selecting, tapping, hitting Enter just lets me eddit the label!

**Comment by jimmyff** [comment] 2020-03-12 13:31
Just to clarify that the debug scheme does still work and admob works correctly for that scheme -it's only when I set the scheme to `Release` that I get the problems.

**Comment by jmagman** [comment] 2020-03-12 20:39
Release and Profile are not supported on the simulator.  That's why Profile and Release support `iphoneos` and not `iphonesimulator`.
Duplicate of https://github.com/flutter/flutter/issues/11754

**Closed by jmagman** 2020-03-12 20:39 UTC
Labels: a: build, a: release, tool, ⌺‬ platform-ios
