### ISSUE TITLE
Pixel and performance problems in Flutter ios

### ISSUE THREAD

**Issue by volkanustekidag** [flutter/flutter#135422] opened 2023-09-25 13:20 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I generally experience performance and resolution problems in Flutter iOS. I am experiencing many problems such as flickering or bad quality in an svg file, bad quality in a lottie file, and flickering in listings in scroll situations.What is the reason for this and why does it occur?

These never happen on Android, what am I doing wrong?

### Expected results

-

### Actual results

-

### Code sample

<details><summary>

SvgPicture.asset(
       AssetConstants.birthdayImage,
),
</summary>

```dart
[Paste your code here]
```

</details>

### Assets
<details><summary>Svg assets</summary>

```console
<svg width="178" height="123" viewBox="0 0 178 123" fill="none" xmlns="http://www.w3.org/2000/svg">
<g id="Group">
<g id="Group_2">
<g id="Group_3">
<g id="Group_4">
<path id="Vector" d="M179.781 36.668H117.008V123.767H179.781V36.668Z" fill="#2D4E9E"/>
<path id="Vector_2" d="M179.781 75.5332H117.008V84.5992H179.781V75.5332Z" fill="#3A5DBD"/>
<path id="Vector_3" d="M152.927 36.668H143.861V123.46H152.927V36.668Z" fill="#253460"/>
</g>
<g id="Vector_4" style="mix-blend-mode:overlay" opacity="0.1">
<path d="M179.781 36.668V123.767H172.285V43.4962H117.008V36.668H179.781Z" fill="black"/>
</g>
<g id="Vector_5" style="mix-blend-mode:overlay" opacity="0.1">
<path d="M158.051 60.6396H123.536V116.773H158.051V60.6396Z" fill="white"/>
</g>
</g>
<g id="Group_5">
<g id="Group_6">
<path id="Vector_6" d="M153.71 36.6683H143.614L158.175 7.22515C159.883 3.76845 163.017 1.26761 166.766 0.363603C170.512 -0.540401 174.443 0.25987 177.54 2.55693C181.105 5.20226 183.057 9.42219 182.757 13.8533C182.457 18.2807 179.96 22.2042 176.073 24.3457L153.71 36.6683ZM169.816 6.82872C169.334 6.82872 168.849 6.8843 168.367 7.00286C166.592 7.43263 165.107 8.6145 164.295 10.2558L155.603 27.832L172.776 18.3696C174.643 17.3396 175.799 15.5279 175.944 13.3976C176.088 11.2672 175.188 9.31844 173.472 8.04394C172.402 7.24738 171.12 6.83243 169.816 6.83243V6.82872Z" fill="#253460"/>
<g id="Group_7" style="mix-blend-mode:overlay" opacity="0.1">
<path id="Vector_7" d="M177.541 2.55623C177.048 2.18574 176.537 1.8597 176.003 1.57812C178.878 4.4124 180.394 8.36557 180.12 12.4743C179.797 17.2685 177.096 21.507 172.887 23.83L149.591 36.6676H153.707L176.066 24.345C179.956 22.1998 182.45 18.2837 182.75 13.8526C183.05 9.4289 181.098 5.20156 177.533 2.55994L177.541 2.55623Z" fill="black"/>
</g>
<g id="Group_8" style="mix-blend-mode:overlay" opacity="0.2">
<path id="Vector_8" d="M157.172 17.0949C156.961 17.0949 156.746 17.0467 156.542 16.9393C155.871 16.591 155.612 15.7648 155.96 15.0979L159.532 8.23638C161.399 4.85378 166.782 -0.699919 173.911 2.28997C174.607 2.58266 174.933 3.38292 174.641 4.07575C174.348 4.77228 173.548 5.09831 172.855 4.80562C166.182 2.00839 162.111 9.21449 161.94 9.52571L158.387 16.3576C158.143 16.8244 157.668 17.0912 157.176 17.0912L157.172 17.0949Z" fill="white"/>
</g>
<g id="Group_9" style="mix-blend-mode:overlay" opacity="0.2">
<path id="Vector_9" d="M149.591 31.6706C149.38 31.6706 149.165 31.6224 148.961 31.515C148.29 31.1667 148.031 30.3442 148.379 29.6736L152.292 22.1563C152.64 21.4857 153.462 21.2263 154.133 21.5746C154.804 21.9229 155.063 22.7454 154.715 23.416L150.802 30.9333C150.558 31.4001 150.084 31.6706 149.591 31.6706Z" fill="white"/>
</g>
<g id="Vector_10" style="mix-blend-mode:overlay" opacity="0.2">
<path d="M176.733 7.59618C177.584 7.59618 178.274 6.90614 178.274 6.05493C178.274 5.20372 177.584 4.51367 176.733 4.51367C175.881 4.51367 175.191 5.20372 175.191 6.05493C175.191 6.90614 175.881 7.59618 176.733 7.59618Z" fill="white"/>
</g>
</g>
<g id="Group_10">
<path id="Vector_11" d="M120.721 24.3457C116.835 22.2042 114.334 18.2807 114.037 13.8533C113.741 9.42589 115.69 5.20226 119.254 2.55693C122.351 0.25987 126.278 -0.540401 130.028 0.363603C133.777 1.26761 136.908 3.76845 138.62 7.22515L153.18 36.6683H143.084L120.721 24.3457ZM123.322 8.04023C121.607 9.31103 120.706 11.2635 120.851 13.3939C120.995 15.5242 122.147 17.3359 124.018 18.3659L141.191 27.8283L132.499 10.2521C131.688 8.6145 130.206 7.42892 128.427 6.99915C127.949 6.88429 127.464 6.82501 126.979 6.82501C125.675 6.82501 124.393 7.23997 123.322 8.03654V8.04023Z" fill="#253460"/>
<g id="Group_11" style="mix-blend-mode:overlay" opacity="0.1">
<path id="Vector_12" d="M114.038 13.8497C114.338 18.2808 116.831 22.2006 120.721 24.342L143.081 36.6647H147.197L123.9 23.827C119.695 21.5041 116.99 17.2656 116.668 12.4714C116.394 8.36264 117.909 4.40947 120.784 1.5752C120.251 1.85677 119.739 2.1828 119.247 2.55329C115.683 5.19491 113.73 9.42225 114.03 13.8459L114.038 13.8497Z" fill="black"/>
</g>
<g id="Group_12" style="mix-blend-mode:overlay" opacity="0.2">
<path id="Vector_13" d="M139.62 17.0949C139.831 17.0949 140.046 17.0467 140.25 16.9393C140.921 16.591 141.18 15.7648 140.832 15.0979L137.26 8.23638C135.393 4.85378 130.009 -0.699919 122.881 2.28997C122.185 2.58266 121.859 3.38292 122.151 4.07575C122.444 4.77228 123.244 5.09831 123.937 4.80562C130.61 2.00839 134.681 9.21449 134.852 9.52571L138.405 16.3576C138.649 16.8244 139.124 17.0912 139.616 17.0912L139.62 17.0949Z" fill="white"/>
</g>
<g id="Group_13" style="mix-blend-mode:overlay" opacity="0.2">
<path id="Vector_14" d="M147.2 31.6706C147.411 31.6706 147.626 31.6224 147.829 31.515C148.496 31.1667 148.759 30.3442 148.411 29.6736L144.499 22.1563C144.15 21.4857 143.328 21.2263 142.657 21.5746C141.987 21.9229 141.727 22.7454 142.076 23.416L145.988 30.9333C146.233 31.4001 146.707 31.6706 147.2 31.6706Z" fill="white"/>
</g>
<g id="Vector_15" style="mix-blend-mode:overlay" opacity="0.2">
<path d="M118.517 6.05493C118.517 6.90706 119.206 7.59618 120.058 7.59618C120.91 7.59618 121.599 6.90706 121.599 6.05493C121.599 5.20279 120.91 4.51367 120.058 4.51367C119.206 4.51367 118.517 5.20279 118.517 6.05493Z" fill="white"/>
</g>
</g>
</g>
</g>
<g id="Group_14">
<g id="Group_15">
<g id="Group_16">
<path id="Vector_16" d="M57.9045 123.373H0L1.40045 118.683L2.68237 114.396L3.09361 113.029L6.6022 101.273L8.29534 95.6195L11.8039 83.8675L13.4971 78.21L17.0094 66.4505L18.7025 60.7968L22.2111 49.041L23.9042 43.3873L28.9504 26.5039L33.0517 40.2418L34.4337 44.836L37.2865 54.3947L38.6647 58.9962L41.5175 68.5549L42.8995 73.1565L45.7523 82.7152L47.1231 87.3168L49.987 96.8755L51.3578 101.477L54.218 111.036L55.5926 115.637L57.9045 123.373Z" fill="#00DF59"/>
<g id="Group_17">
<path id="Vector_17" d="M34.4335 44.8363L32.3143 45.5662L22.2109 49.0414L23.9041 43.3877L31.4696 40.7868L33.0516 40.2422L34.4335 44.8363Z" fill="#212F56"/>
<path id="Vector_18" d="M38.6651 58.9961L34.9157 60.2854L17.0098 66.4504L18.7029 60.7967L34.071 55.4986L37.2869 54.3945L38.6651 58.9961Z" fill="#212F56"/>
<path id="Vector_19" d="M42.9002 73.1562L37.5133 75.0124L11.8047 83.8672L13.4978 78.2098L36.6722 70.2256L41.5183 68.5547L42.9002 73.1562Z" fill="#212F56"/>
<path id="Vector_20" d="M47.1234 87.3164L40.1137 89.732L6.60254 101.273L8.29568 95.6191L39.2653 84.9489L45.7526 82.7148L47.1234 87.3164Z" fill="#212F56"/>
<path id="Vector_21" d="M51.3578 101.477L42.7141 104.455L13.8453 114.396L1.40039 118.682L2.68231 114.396L3.09355 113.029L41.8657 99.6759L49.9869 96.875L51.3578 101.477Z" fill="#212F56"/>
<path id="Vector_22" d="M55.5923 115.637L33.1293 123.373H18.3984L44.4701 114.396L54.2178 111.035L55.5923 115.637Z" fill="#212F56"/>
</g>
</g>
<g id="Vector_23" style="mix-blend-mode:overlay" opacity="0.2">
<path d="M57.9045 123.373H0L1.40045 118.683L2.68237 114.396H44.4704L42.7142 104.456L41.8658 99.6764L40.1133 89.7324L39.2649 84.9493L37.5125 75.0126L36.6715 70.2259L34.9153 60.2855L34.0706 55.4988L32.3145 45.5658L31.4697 40.7864L28.9504 26.5039L33.0517 40.2418L34.4337 44.836L37.2865 54.3947L38.6647 58.9962L41.5175 68.5549L42.8995 73.1565L45.7523 82.7152L47.1231 87.3168L49.987 96.8755L51.3578 101.477L54.218 111.036L55.5926 115.637L57.9045 123.373Z" fill="black"/>
</g>
</g>
<path id="Vector_24" d="M52.5655 14.9339L52.0728 17.809C42.6289 16.1899 32.1846 28.3977 30.3729 30.6095C30.2951 31.7877 28.802 32.2434 28.0759 31.3098L27.798 30.9504C27.6831 30.7985 16.1349 16.038 5.82772 17.8053L5.33496 14.9302C12.9004 13.6335 20.54 19.3354 25.2935 23.9036C22.5555 18.524 17.6465 11.0549 11.0924 10.036L11.537 7.15357C19.1618 8.34285 24.6117 16.2492 27.6572 22.1067C27.5942 13.1296 26.9681 2.31492 26.9533 2.17042L29.8691 2C29.9024 2.58168 30.4989 12.9258 30.573 21.7992C33.6444 15.975 39.0388 8.32062 46.5302 7.15357L46.9822 10.036C40.5578 11.0326 35.7043 18.2424 32.9367 23.5887C37.7161 19.0761 45.1705 13.6668 52.5655 14.9302V14.9339Z" fill="#212F56"/>
</g>
<g id="Group_18">
<g id="Group_19">
<g id="Group_20">
<path id="Vector_25" d="M81.7719 33.2002H78.1484V69.7976H81.7719V33.2002Z" fill="#FFEDC7"/>
<g id="Group_21">
<path id="Vector_26" d="M82.9905 31.6417C83.1906 35.0318 79.9599 34.891 79.9599 34.891C79.9599 34.891 78.4075 34.9614 77.5257 33.8684C77.1293 33.3868 76.8662 32.6828 76.9292 31.6417C77.1219 28.2443 79.9599 24.8506 79.9599 24.8506L79.9673 24.858C80.1377 25.0655 82.7978 28.3481 82.9905 31.6417Z" fill="#F25629"/>
<g id="Vector_27" style="mix-blend-mode:overlay" opacity="0.2">
<path d="M82.9902 31.6421C83.1902 35.0322 79.9595 34.8914 79.9595 34.8914C79.9595 34.8914 78.4072 34.9618 77.5254 33.8688C83.331 34.08 80.0744 25.1622 79.967 24.8584C80.1374 25.0659 82.7975 28.3484 82.9902 31.6421Z" fill="black"/>
</g>
</g>
</g>
<g id="Group_22">
<path id="Vector_28" d="M95.1732 26.9189H91.5498V63.5163H95.1732V26.9189Z" fill="#FFEDC7"/>
<g id="Group_23">
<path id="Vector_29" d="M96.3958 25.3615C96.5959 28.7515 93.3651 28.6107 93.3651 28.6107C93.3651 28.6107 91.8128 28.6811 90.931 27.5881C90.5346 27.1065 90.2715 26.4025 90.3345 25.3615C90.5272 21.964 93.3651 18.5703 93.3651 18.5703L93.3726 18.5777C93.543 18.7852 96.2031 22.0678 96.3958 25.3615Z" fill="#F25629"/>
<g id="Vector_30" style="mix-blend-mode:overlay" opacity="0.2">
<path d="M96.3954 25.3619C96.5955 28.7519 93.3648 28.6111 93.3648 28.6111C93.3648 28.6111 91.8124 28.6815 90.9307 27.5885C96.7363 27.7997 93.4796 18.8819 93.3722 18.5781C93.5426 18.7856 96.2028 22.0682 96.3954 25.3619Z" fill="black"/>
</g>
</g>
</g>
<g id="Group_24">
<path id="Vector_31" d="M108.579 33.1992H104.955V69.7966H108.579V33.1992Z" fill="#FFEDC7"/>
<g id="Group_25">
<path id="Vector_32" d="M109.8 31.6417C110 35.0318 106.769 34.891 106.769 34.891C106.769 34.891 105.217 34.9614 104.335 33.8684C103.939 33.3868 103.676 32.6828 103.739 31.6417C103.931 28.2443 106.769 24.8506 106.769 24.8506L106.777 24.858C106.947 25.0655 109.607 28.3481 109.8 31.6417Z" fill="#F25629"/>
<g id="Vector_33" style="mix-blend-mode:overlay" opacity="0.2">
<path d="M109.801 31.6421C110.001 35.0322 106.77 34.8914 106.77 34.8914C106.77 34.8914 105.218 34.9618 104.336 33.8688C110.142 34.08 106.885 25.1622 106.777 24.8584C106.948 25.0659 109.608 28.3484 109.801 31.6421Z" fill="black"/>
</g>
</g>
</g>
</g>
<g id="Group_26">
<g id="Group_27">
<g id="Group_28">
<path id="Vector_34" d="M129.332 94.7419V123.059H53.751V94.7419C53.751 93.6267 53.7991 92.5227 53.8992 91.4297C55.5738 72.1159 71.7866 56.959 91.5413 56.959C101.971 56.959 111.422 61.1863 118.261 68.0293C120.981 70.7451 123.285 73.8683 125.075 77.3102C126.068 79.2182 126.905 81.2189 127.564 83.2974C128.713 86.9097 129.332 90.7554 129.332 94.7419Z" fill="#FFBC2B"/>
<g id="Group_29">
<g id="Vector_35" style="mix-blend-mode:overlay" opacity="0.2">
<path d="M127.565 83.2974L123.386 81.0559C122.682 80.678 121.889 80.489 121.085 80.489H121C118.318 80.489 116.132 82.6675 116.132 85.3499V99.3694L116.095 99.6399C115.165 106.742 109.063 112.1 101.89 112.1C93.9874 112.1 87.5482 105.671 87.5482 97.7726V81.1559C87.5482 78.4958 85.3919 76.3395 82.7392 76.3395C80.0864 76.3395 77.9228 78.4958 77.9228 81.1559V87.7396C77.9228 95.6385 71.4947 102.067 63.5884 102.067C59.8278 102.067 56.3452 100.633 53.748 98.1764V94.7419C53.748 93.6267 53.7962 92.5227 53.8963 91.4297C55.5709 72.1159 71.7837 56.959 91.5384 56.959C101.968 56.959 111.419 61.1863 118.258 68.0293C120.978 70.7451 123.282 73.8683 125.072 77.3102C126.065 79.2182 126.902 81.2189 127.562 83.2974H127.565Z" fill="black"/>
</g>
<g id="Group_30">
<g id="Vector_36" style="mix-blend-mode:overlay" opacity="0.2">
<path d="M63.6886 116.712C64.5214 116.712 65.1965 116.037 65.1965 115.204C65.1965 114.371 64.5214 113.696 63.6886 113.696C62.8558 113.696 62.1807 114.371 62.1807 115.204C62.1807 116.037 62.8558 116.712 63.6886 116.712Z" fill="black"/>
</g>
<g id="Vector_37" style="mix-blend-mode:overlay" opacity="0.2">
<path d="M120.271 97.1174C121.103 97.1174 121.778 96.4423 121.778 95.6095C121.778 94.7767 121.103 94.1016 120.271 94.1016C119.438 94.1016 118.763 94.7767 118.763 95.6095C118.763 96.4423 119.438 97.1174 120.271 97.1174Z" fill="black"/>
</g>
<g id="Vector_38" style="mix-blend-mode:overlay" opacity="0.2">
<path d="M77.2755 114.838C78.1083 114.838 78.7834 114.163 78.7834 113.33C78.7834 112.497 78.1083 111.822 77.2755 111.822C76.4427 111.822 75.7676 112.497 75.7676 113.33C75.7676 114.163 76.4427 114.838 77.2755 114.838Z" fill="black"/>
</g>
<g id="Vector_39" style="mix-blend-mode:overlay" opacity="0.2">
<path d="M115.481 116.35C116.313 116.35 116.988 115.675 116.988 114.842C116.988 114.009 116.313 113.334 115.481 113.334C114.648 113.334 113.973 114.009 113.973 114.842C113.973 115.675 114.648 116.35 115.481 116.35Z" fill="black"/>
</g>
<g id="Vector_40" style="mix-blend-mode:overlay" opacity="0.2">
<path d="M74.3151 106.384C74.8144 106.384 75.2191 105.979 75.2191 105.48C75.2191 104.981 74.8144 104.576 74.3151 104.576C73.8159 104.576 73.4111 104.981 73.4111 105.48C73.4111 105.979 73.8159 106.384 74.3151 106.384Z" fill="black"/>
</g>
<g id="Vector_41" style="mix-blend-mode:overlay" opacity="0.2">
<path d="M120.575 112.726C120.575 113.226 120.171 113.63 119.671 113.63C119.17 113.63 118.767 113.226 118.767 112.726C118.767 112.226 119.17 111.822 119.671 111.822C120.171 111.822 120.575 112.226 120.575 112.726Z" fill="black"/>
</g>
<g id="Vector_42" style="mix-blend-mode:overlay" opacity="0.2">
<path d="M122.687 118.48C122.687 118.98 122.283 119.384 121.783 119.384C121.283 119.384 120.879 118.98 120.879 118.48C120.879 117.98 121.283 117.576 121.783 117.576C122.283 117.576 122.687 117.98 122.687 118.48Z" fill="black"/>
</g>
</g>
</g>
</g>
<g id="Group_31">
<path id="Vector_43" d="M125.075 77.3063C123.789 76.6172 122.322 76.2282 120.77 76.2282H120.685C115.638 76.2282 111.559 80.3073 111.559 85.346V99.0913C110.915 104.03 106.691 107.839 101.575 107.839C96.006 107.839 91.4934 103.333 91.4934 97.7687V81.152C91.4934 76.1429 87.4365 72.0786 82.4237 72.0786C77.4109 72.0786 73.3503 76.1429 73.3503 81.152V87.7357C73.3503 93.2968 68.8377 97.8057 63.2729 97.8057C59.0159 97.8057 55.3703 95.1678 53.8994 91.4258C55.574 72.112 71.7868 56.9551 91.5416 56.9551C101.971 56.9551 111.422 61.1824 118.262 68.0254C120.981 70.7449 123.285 73.8644 125.075 77.3063Z" fill="#EF4822"/>
<g id="Group_32" style="mix-blend-mode:overlay" opacity="0.2">
<path id="Vector_44" d="M63.2657 95.608C60.9353 95.608 58.7086 94.6114 57.1562 92.8701C56.6338 92.2847 56.6857 91.3881 57.2711 90.8657C57.8565 90.347 58.7531 90.3952 59.2755 90.9806C60.2906 92.118 61.7467 92.77 63.2694 92.77C65.8554 92.77 68.0673 90.925 68.5304 88.3871C68.6712 87.6165 69.4122 87.1089 70.1791 87.246C70.9497 87.3868 71.461 88.1241 71.3202 88.8947C70.6126 92.7849 67.2263 95.608 63.2694 95.608H63.2657Z" fill="white"/>
</g>
<g id="Group_33" style="mix-blend-mode:overlay" opacity="0.2">
<path id="Vector_45" d="M102.035 105.146C97.2554 105.146 93.3652 101.259 93.3652 96.4835C93.3652 95.95 93.4134 95.4313 93.5023 94.9497C93.6505 94.179 94.3878 93.6715 95.1621 93.8197C95.9328 93.9642 96.4366 94.7088 96.2921 95.4795C96.2329 95.787 96.2032 96.1278 96.2032 96.4835C96.2032 99.6957 98.8189 102.308 102.035 102.308C104.417 102.308 106.536 100.881 107.433 98.6731C107.726 97.947 108.552 97.595 109.282 97.8914C110.008 98.1841 110.356 99.014 110.063 99.7401C108.73 103.023 105.58 105.146 102.035 105.146Z" fill="white"/>
</g>
<g id="Vector_46" style="mix-blend-mode:overlay" opacity="0.2">
<path d="M72.2791 84.5272C72.2791 85.3052 71.6492 85.9314 70.8749 85.9314C70.1006 85.9314 69.4707 85.3015 69.4707 84.5272C69.4707 83.7529 70.1006 83.123 70.8749 83.123C71.6492 83.123 72.2791 83.7529 72.2791 84.5272Z" fill="white"/>
</g>
<g id="Vector_47" style="mix-blend-mode:overlay" opacity="0.2">
<path d="M96.1765 90.87C96.1765 91.648 95.5467 92.2742 94.7723 92.2742C93.998 92.2742 93.3682 91.6443 93.3682 90.87C93.3682 90.0957 93.998 89.4658 94.7723 89.4658C95.5467 89.4658 96.1765 90.0957 96.1765 90.87Z" fill="white"/>
</g>
<g id="Vector_48" style="mix-blend-mode:overlay" opacity="0.2">
<path d="M120.27 73.1161C120.27 73.8941 119.64 74.5202 118.866 74.5202C118.092 74.5202 117.462 73.8904 117.462 73.1161C117.462 72.3417 118.092 71.7119 118.866 71.7119C119.64 71.7119 120.27 72.3417 120.27 73.1161Z" fill="white"/>
</g>
<g id="Vector_49" style="mix-blend-mode:overlay" opacity="0.2">
<path d="M82.7693 68.3885C82.7693 69.1666 82.1395 69.7927 81.3651 69.7927C80.5908 69.7927 79.9609 69.1629 79.9609 68.3885C79.9609 67.6142 80.5908 66.9844 81.3651 66.9844C82.1395 66.9844 82.7693 67.6142 82.7693 68.3885Z" fill="white"/>
</g>
<g id="Group_34" style="mix-blend-mode:overlay" opacity="0.2">
<path id="Vector_50" d="M95.3127 81.2347C94.5829 81.2347 93.9641 80.6789 93.9012 79.9379C93.1342 71.1795 85.5539 69.8123 85.4798 69.8012C84.7055 69.6715 84.1868 68.9417 84.3128 68.1673C84.4425 67.393 85.176 66.8743 85.9467 67.0003C86.043 67.0151 95.7685 68.7675 96.728 79.6897C96.7984 80.4714 96.2205 81.1606 95.4387 81.2273C95.398 81.231 95.3535 81.231 95.3127 81.231V81.2347Z" fill="white"/>
</g>
<g id="Group_35" style="mix-blend-mode:overlay" opacity="0.2">
<path id="Vector_51" d="M108.629 84.1749C108.592 84.1749 108.555 84.1749 108.518 84.1712C107.74 84.1082 107.158 83.4339 107.214 82.6559C107.236 82.3743 107.803 75.7091 114.253 72.8156C114.968 72.4932 115.809 72.8156 116.128 73.5306C116.45 74.2457 116.128 75.0867 115.413 75.4053C110.537 77.5949 110.059 82.6596 110.041 82.8745C109.978 83.6155 109.359 84.1786 108.625 84.1786L108.629 84.1749Z" fill="white"/>
</g>
</g>
<g id="Vector_52" style="mix-blend-mode:overlay" opacity="0.15">
<path d="M117.199 66.8734C110.864 62.0681 102.965 59.2227 94.4102 59.2227C74.6554 59.2227 58.4426 74.3796 56.768 93.6934C56.668 94.7864 56.6198 95.8942 56.6198 97.0056V123.059H53.9004V94.7419C53.9004 93.6267 53.9485 92.5227 54.0486 91.4297C55.7232 72.1159 71.936 56.959 91.6908 56.959C101.516 56.959 110.471 60.7121 117.199 66.8697V66.8734Z" fill="white"/>
</g>
</g>
</g>
</g>
</g>
</svg>

```
</details>

-

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

https://github.com/flutter/flutter/assets/56761000/76aa87cf-6711-4c4a-8561-f04b201cac46

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.13.5, on macOS 13.6 22G120 darwin-arm64, locale en-TR)
    • Flutter version 3.13.5 on channel stable at /Users/ogoo/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 12fccda598 (7 days ago), 2023-09-19 13:56:11 -0700
    • Engine revision bd986c5ed2
    • Dart version 3.1.2
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/ogoo/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.13.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.82.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.72.0

[✓] Connected device (3 available)
    • iPhone 15 Pro (mobile) • 09A36E5E-48AF-455E-8124-DE6F23BF1889 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-17-0 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 13.6 22G120
      darwin-arm64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome
      117.0.5938.92

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by darshankawar** [comment] 2023-09-26 06:46
@volkanustekidag 
In order to properly address the issue, please provide us a runnable reproducible code sample that we can use to verify it further.

**Comment by volkanustekidag** [comment] 2023-09-26 06:57
> @volkanustekidag In order to properly address the issue, please provide us a runnable reproducible code sample that we can use to verify it further.

This is not due to a code snippet, I am experiencing poor performance in photos and animations in general on IOS.

**Comment by darshankawar** [comment] 2023-09-27 05:18
> SvgPicture.asset( AssetConstants.birthdayImage, ),

Please provide us the asset you are using and also provide flutter doctor -v to know which version are you facing the issue on.

**Comment by volkanustekidag** [comment] 2023-09-27 07:19
> > SvgPicture.asset( AssetConstants.birthdayImage, ),
> 
> Please provide us the asset you are using and also provide flutter doctor -v to know which version are you facing the issue on.
I added the things you wanted.

**Comment by volkanustekidag** [comment] 2023-09-27 07:19
> > SvgPicture.asset( AssetConstants.birthdayImage, ),
> 
> Please provide us the asset you are using and also provide flutter doctor -v to know which version are you facing the issue on.

I added the things you wanted.

**Comment by darshankawar** [comment] 2023-09-28 06:35
@volkanustekidag 
Thanks for the update. Using the details you provided, I came up with below runnable code sample, ran it using latest master version on iPhone 13 pro max simulator (OS 15.2) with which I didn't observe the jank or shaky svg image. 


https://github.com/flutter/flutter/assets/67046386/d670d285-001f-48b9-968f-afe7e730524d


<details>
<summary> runnable code sample </summary>

```

import 'package:flutter/material.dart';
import 'package:flutter_svg/flutter_svg.dart';

void main() {
  runApp(MaterialApp(
    home: Scaffold(
      body: ListView(
        padding: const EdgeInsets.all(8),
        children: [
          SvgPicture.asset(
              'assets/test.svg'
          ),
          Container(
            height: 50,
            color: Colors.amber[600],
            child: const Center(child: Text('Entry A')),
          ),
          Container(
            height: 50,
            color: Colors.amber[500],
            child: const Center(child: Text('Entry B')),
          ),
          Container(
            height: 50,
            color: Colors.amber[100],
            child: const Center(child: Text('Entry C')),
          ),
          Container(
            height: 50,
            color: Colors.amber[600],
            child: const Center(child: Text('Entry A')),
          ),
          Container(
            height: 50,
            color: Colors.amber[500],
            child: const Center(child: Text('Entry B')),
          ),
          Container(
            height: 50,
            color: Colors.amber[100],
            child: const Center(child: Text('Entry C')),
          ),
          Container(
            height: 50,
            color: Colors.amber[600],
            child: const Center(child: Text('Entry A')),
          ),
          Container(
            height: 50,
            color: Colors.amber[500],
            child: const Center(child: Text('Entry B')),
          ),
          Container(
            height: 50,
            color: Colors.amber[100],
            child: const Center(child: Text('Entry C')),
          ),
          Container(
            height: 50,
            color: Colors.amber[600],
            child: const Center(child: Text('Entry A')),
          ),
          Container(
            height: 50,
            color: Colors.amber[500],
            child: const Center(child: Text('Entry B')),
          ),
          Container(
            height: 50,
            color: Colors.amber[100],
            child: const Center(child: Text('Entry C')),
          ),
        ],
      )
    ),
  ));
}

```

</details>

I verified on `Channel master, 3.15.0-10.0.pre`

Can you try the same on the device / simulator you are seeing the reported behavior and check if it still persists ?

**Comment by volkanustekidag** [comment] 2023-09-28 06:57
> void main() {
>   runApp(MaterialApp(
>     home: Scaffold(
>       body: ListView(
>         padding: const EdgeInsets.all(8),
>         children: [
>           SvgPicture.asset(
>               'assets/test.svg'
>           ),
>           Container(
>             height: 50,
>             color: Colors.amber[600],
>             child: const Center(child: Text('Entry A')),
>           ),
>           Container(
>             height: 50,
>             color: Colors.amber[500],
>             child: const Center(child: Text('Entry B')),
>           ),
>           Container(
>             height: 50,
>             color: Colors.amber[100],
>             child: const Center(child: Text('Entry C')),
>           ),
>           Container(
>             height: 50,
>             color: Colors.amber[600],
>             child: const Center(child: Text('Entry A')),
>           ),
>           Container(
>             height: 50,
>             color: Colors.amber[500],
>             child: const Center(child: Text('Entry B')),
>           ),
>           Container(
>             height: 50,
>             color: Colors.amber[100],
>             child: const Center(child: Text('Entry C')),
>           ),
>           Container(
>             height: 50,
>             color: Colors.amber[600],
>             child: const Center(child: Text('Entry A')),
>           ),
>           Container(
>             height: 50,
>             color: Colors.amber[500],
>             child: const Center(child: Text('Entry B')),
>           ),
>           Container(
>             height: 50,
>             color: Colors.amber[100],
>             child: const Center(child: Text('Entry C')),
>           ),
>           Container(
>             height: 50,
>             color: Colors.amber[600],
>             child: const Center(child: Text('Entry A')),
>           ),
>           Container(
>             height: 50,
>             color: Colors.amber[500],
>             child: const Center(child: Text('Entry B')),
>           ),
>           Container(
>             height: 50,
>             color: Colors.amber[100],
>             child: const Center(child: Text('Entry C')),
>           ),
>         ],
>       )
>     ),
>   ));
> }
Thank you very much for your help. But as you can see, the problem still persists. Could the problem be caused by the channel? I am using the stable channel.

https://github.com/flutter/flutter/assets/56761000/d4dfd871-449c-42e2-9450-123e3a92aa44

**Comment by darshankawar** [comment] 2023-09-28 08:52
Yes, it seems the reported behavior persists on latest stable, but not on master, as it seems to have fixed in it per my verification earlier.
Per our triage policy, since the behavior works as expected on latest master, I'll close this as fixed. It'll roll out in stable version per Flutter team's release policy you can read in wiki [here](https://github.com/flutter/flutter/wiki/Release-process).

**Closed by darshankawar** 2023-09-28 08:52 UTC
Labels: in triage
