### ISSUE TITLE
Installing build failing

### ISSUE THREAD

**Issue by MStanoevich** [flutter/flutter#21396] opened 2018-09-04 19:43 UTC
I took a 1 month break from this project and I am back at it but when I try running flutter run, this is what happens:

```
Built build\app\outputs\apk\debug\app-debug.apk.
Installing build\app\outputs\apk\app.apk...

Oops; flutter has exited unexpectedly: "Exit code -1 from: C:\Users\A296791\AppData\Local\Android\sdk\platform-tools\adb -s emulator-5554 shell am start -a android.intent.action.RUN -f 0x20000000 --ez enable-background-compilation true --ez enable-dart-profiling true --ez enable-checked-mode true com.example.lnotes/com.apptreesoftware.mapview.MapActivity:
Starting: Intent { act=android.intent.action.RUN flg=0x20000000 cmp=com.example.lnotes/com.apptreesoftware.mapview.MapActivity (has extras) }

Security exception: Permission Denial: starting Intent { act=android.intent.action.RUN flg=0x30000000 cmp=com.example.lnotes/com.apptreesoftware.mapview.MapActivity (has extras) } from null (pid=14660, uid=2000) not exported from uid 10085

java.lang.SecurityException: Permission Denial: starting Intent { act=android.intent.action.RUN flg=0x30000000 cmp=com.example.lnotes/com.apptreesoftware.mapview.MapActivity (has extras) } from null (pid=14660, uid=2000) not exported from uid 10085
        at com.android.server.am.ActivityStackSupervisor.checkStartAnyActivityPermission(ActivityStackSupervisor.java:1788)
        at com.android.server.am.ActivityStarter.startActivity(ActivityStarter.java:717)
        at com.android.server.am.ActivityStarter.startActivity(ActivityStarter.java:544)
        at com.android.server.am.ActivityStarter.startActivityMayWait(ActivityStarter.java:1099)
        at com.android.server.am.ActivityStarter.execute(ActivityStarter.java:486)
        at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:5120)
        at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:5094)        at com.android.server.am.ActivityManagerShellCommand.runStartActivity(ActivityManagerShellCommand.java:479)        at com.android.server.am.ActivityManagerShellCommand.onCommand(ActivityManagerShellCommand.java:161)        at android.os.ShellCommand.exec(ShellCommand.java:103)
        at com.android.server.am.ActivityManagerService.onShellCommand(ActivityManagerService.java:16005)        at android.os.Binder.shellCommand(Binder.java:634)
        at android.os.Binder.onTransact(Binder.java:532)
        at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:3592)
        at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3291)        at android.os.Binder.execTransact(Binder.java:731)".
```

Here is flutter doctor:

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v0.6.0, on Microsoft Windows [Version 6.1.7601], locale sv-SE)
[√] Android toolchain - develop for Android devices (Android SDK 28.0.2)
[√] Android Studio (version 3.1)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] IntelliJ IDEA Community Edition (version 2018.2)
[√] Connected devices (1 available)

• No issues found!
```

**Comment by zoechi** [comment] 2018-09-05 07:19
Is this with the emulator, a real device or both?

**Comment by MStanoevich** [comment] 2018-09-05 17:35
It is with emulator, android API 28

**Comment by dark-chocolate** [comment] 2018-09-13 17:38
Upgrading to the latest flutter version caused this issue for me. I was running v0.5.1 couple of days ago and now I am using v 0.7.3. 

PS: I think @zoechi remembers my case. Once again a big thanks to him for helping me out in upgrading flutter. He is very helpful guy among all.

**Comment by leorachit** [comment] 2018-09-14 11:41
What is the solution for this?

**Comment by dark-chocolate** [comment] 2018-09-17 09:58
I found the solution (at least it worked for me), I moved 
`<activity android:name="com.apptreesoftware.mapview.MapActivity" .../>` below
` <activity android:name=".MainActivity" .../>` in the `AndroidManifest.xml` file

**Comment by dlutton** [comment] 2018-10-24 05:07
Thanks @dark-chocolate, that solution worked for me as well for a different API configuration.

**Comment by rcourivaud** [comment] 2018-12-23 20:08
You can add ` android:exported="true"` to `com.apptreesoftware.mapview.MapActivity` XML tag
 
Something like that

```
<activity android:name="com.apptreesoftware.mapview.MapActivity"
          android:exported="true"/>
```

**Comment by jonahwilliams** [comment] 2019-04-22 00:50
This issue is caused by errors in the AndroidManifest file. We might have changed something or otherwise altered some process around 0.6.0 that caused the previous configuration to no longer work.

New projects created do not have this issue, and the fix seems fairly straightforward. Closing for now, but please file a new issue if this starts happening again.

**Closed by jonahwilliams** 2019-04-22 00:50 UTC
Labels: severe: crash, severe: regression, tool
