### ISSUE TITLE
[webview_flutter] Rendering issue on Android with Flutter 3 and setting backgroundTransparent to true.

### ISSUE THREAD

**Issue by sezer-healthlogix** [flutter/flutter#104686] opened 2022-05-26 04:33 UTC
Plugin version: 3.0.2

I'm running into an issue where on some Android devices the web view isn't rendering properly when the backgroundColor parameter is set to Colors.transparent. It seems to cause a blurry/faded out affect when the page changes as it doesn't fully remove the previous pages from the view.

This issue only started occurring when we upgraded to flutter v3.0.1. We were previously using v2.10.5.

**Step to reproduce**

1. Run the following emulator: Nexus 4 API 28 - Android 9.0 Google APIs | arm64
2. Then create a WebView with the intialUrl pointing to https://www.google.com/ and with backgroundColor set to Colors.transparent.
3. Interact with the web view by searching then scrolling up and down and you should be able to see the issue.4. 

<img width="569" alt="Screen Shot 2022-05-26 at 2 20 15 pm" src="https://user-images.githubusercontent.com/62915393/170416342-b8813c3b-4441-4ab1-9e03-7f9cd61d7ab9.png">

**Comment by danagbemava-nc** [comment] 2022-05-26 08:40
Issue is reproducible on flutter 3+ but not stable 2.10.5. 

I tested on the following devices
 - Poco X3 NFC      • Android 11 (API 30)
 - Pixel 4 Emulator  • Android 9 (API 28) (emulator)
 - Pixel 4a Emulator    • Android 12 (API 32) (emulator)
 - Pixel 2 Emulator • Android 5.1.1 (API 22) (emulator)
 -  Nexus 6 Emulator   • Android 6.0 (API 23) (emulator)

But I was only able to reproduce this on the following devices
- Pixel 4 Emulator running android 9 (api 28)
- Nexus 6 Emulator running android 6


<details>
<summary>recordings</summary>

### flutter 2.10.5

https://user-images.githubusercontent.com/88313112/170451756-042c755f-a90a-4b57-aeb9-3447040ef819.mp4

### flutter 3+

https://user-images.githubusercontent.com/88313112/170451805-1b73d894-165d-4864-bb73-523bfc9e896f.mp4


</details>

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      title: 'Flutter Google Maps Demo',
      home: WebviewSample(),
    );
  }
}

class WebviewSample extends StatefulWidget {
  const WebviewSample({Key? key}) : super(key: key);

  @override
  State<WebviewSample> createState() => WebviewSampleState();
}

class WebviewSampleState extends State<WebviewSample> {

  @override
  Widget build(BuildContext context) {
    return const Scaffold(
      body: WebView(
       initialUrl: 'https://google.com',
       backgroundColor: Colors.transparent,
      ),
    );
  }
}
```
</details>


<details>
<summary>flutter doctor -v</summary>

```
[√] Flutter (Channel unknown, 2.10.5, on Microsoft Windows [Version 10.0.19043.1706], locale en-GH)
    • Flutter version 2.10.5 at c:\src\sdks\rc\flutter
    • Upstream repository unknown
    • Framework revision 5464c5bac7 (5 weeks ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[!] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at C:\Users\Deana\AppData\Local\Android\sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.1.4)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.1.32407.343
    • Windows 10 SDK version 10.0.22000.0

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] VS Code (version 1.67.2)
    • VS Code at C:\Users\Deana\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.40.0

[√] Connected device (8 available)
    • M2007J20CG (mobile)                • 5dd3be00      • android-arm64  • Android 11 (API 30)
    • AOSP on IA Emulator (mobile)       • emulator-5554 • android-x86    • Android 9 (API 28) (emulator)
    • sdk gphone64 x86 64 (mobile)       • emulator-5556 • android-x64    • Android 12 (API 32) (emulator)
    • Android SDK built for x86 (mobile) • emulator-5558 • android-x86    • Android 5.1.1 (API 22) (emulator)
    • Android SDK built for x86 (mobile) • emulator-5560 • android-x86    • Android 6.0 (API 23) (emulator)
    • Windows (desktop)                  • windows       • windows-x64    • Microsoft Windows [Version 10.0.19043.1706]      
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 101.0.4951.67
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 101.0.1210.53

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

```
[√] Flutter (Channel stable, 3.0.1, on Microsoft Windows [Version 10.0.19043.1706], locale en-GH)
    • Flutter version 3.0.1 at C:\src\sdks\stable\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (6 days ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

[!] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at C:\Users\Deana\AppData\Local\Android\sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.1.4)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.1.32407.343
    • Windows 10 SDK version 10.0.22000.0

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] VS Code (version 1.67.2)
    • VS Code at C:\Users\Deana\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.40.0

[√] Connected device (8 available)
    • M2007J20CG (mobile)                • 5dd3be00      • android-arm64  • Android 11 (API 30)
    • AOSP on IA Emulator (mobile)       • emulator-5554 • android-x86    • Android 9 (API 28) (emulator)
    • sdk gphone64 x86 64 (mobile)       • emulator-5556 • android-x64    • Android 12 (API 32) (emulator)
    • Android SDK built for x86 (mobile) • emulator-5558 • android-x86    • Android 5.1.1 (API 22) (emulator)
    • Android SDK built for x86 (mobile) • emulator-5560 • android-x86    • Android 6.0 (API 23) (emulator)
    • Windows (desktop)                  • windows       • windows-x64    • Microsoft Windows [Version 10.0.19043.1706]      
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 101.0.4951.67
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 101.0.1210.53

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

```
[√] Flutter (Channel master, 3.1.0-0.0.pre.935, on Microsoft Windows [Version 10.0.19043.1706], locale en-GH)
    • Flutter version 3.1.0-0.0.pre.935 at c:\src\sdks\master\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f22c203394 (48 minutes ago), 2022-05-26 03:20:09 -0400
    • Engine revision 22b1214189
    • Dart version 2.18.0 (build 2.18.0-149.0.dev)
    • DevTools version 2.13.1

[!] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at C:\Users\Deana\AppData\Local\Android\sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.1.4)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.1.32407.343
    • Windows 10 SDK version 10.0.22000.0

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] VS Code (version 1.67.2)
    • VS Code at C:\Users\Deana\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.40.0

[√] Connected device (8 available)
    • M2007J20CG (mobile)                • 5dd3be00      • android-arm64  • Android 11 (API 30)
    • AOSP on IA Emulator (mobile)       • emulator-5554 • android-x86    • Android 9 (API 28) (emulator)
    • sdk gphone64 x86 64 (mobile)       • emulator-5556 • android-x64    • Android 12 (API 32) (emulator)
    • Android SDK built for x86 (mobile) • emulator-5558 • android-x86    • Android 5.1.1 (API 22) (emulator)
    • Android SDK built for x86 (mobile) • emulator-5560 • android-x86    • Android 6.0 (API 23) (emulator)
    • Windows (desktop)                  • windows       • windows-x64    • Microsoft Windows [Version 10.0.19043.1706]      
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 101.0.4951.67
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 101.0.1210.53

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

</details>

**Comment by stuartmorgan** [comment] 2022-05-26 20:02
@blasten This looks likely to be another regression from platform view changes.

**Comment by bailyzheng** [comment] 2022-06-14 13:35
@stuartmorgan When will this problem be solved? Also #104886. It should be p0 as the problem must happen on lower android version. It make our app for commercial use impossible.

**Comment by blasten** [comment] 2022-06-15 17:50
This is due to this limitation https://github.com/flutter/engine/blob/119ea35cfdefd530641ccef92216f40e48ceffc9/shell/platform/android/io/flutter/plugin/platform/PlatformViewWrapper.java#L308.  

Unfortunately, this feature works above API level 29 by default after recent changes. We still have support for this if `initExpensiveAndroidView` is used in the WebView plugin, instead of `initSurfaceAndroidView` https://api.flutter.dev/flutter/services/PlatformViewsService/initExpensiveAndroidView.html

**Comment by stuartmorgan** [comment] 2022-06-27 19:00
@bparrishMines Could you take this one? I think we have three options:
1. Switch the plugin unconditionally to `initExpensiveAndroidView` (which IIRC means we switch back to Hybrid Composition, so pre-3.0 behavior/performance).
2. Just document the limitation that transparent web views doesn't work before API 29.
3. Add the ability to control (maybe via global switch in the Android implementation package?) which of the two is used, and document that in the README.

3 is probably the best option. We can default to the current version for performance in the common case, but it would give an escape hatch to get the pre-Flutter-3.0 behavior back.

**Comment by bparrishMines** [comment] 2022-06-30 02:43
@stuartmorgan Yea, I can take it. I'll create a PR.

**Comment by bparrishMines** [comment] 2022-07-20 17:37
Fixed by: https://github.com/flutter/plugins/pull/6063.

**Closed by bparrishMines** 2022-07-20 17:37 UTC
Labels: severe: regression, platform-android, engine, plugin, p: first party, p: webview, severe: rendering, e: OS Version specific, has reproducible steps, P3, found in release: 3.0, found in release: 3.1
