### ISSUE TITLE
The flickering color of buttons with icons when the Impeller is turned on on iOS

### ISSUE THREAD

**Issue by 0niel** [flutter/flutter#134934] opened 2023-09-18 13:22 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Run on an iOS device in debug mode and with Impeller enabled
2. Play the scroll animation

### Expected results

The widget should not change its display without changing the state

### Actual results

A widget with icons or an image is flickering

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      themeMode: ThemeMode.dark,
      darkTheme: ThemeData.dark().copyWith(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepOrange),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: SingleChildScrollView(
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.center,
          children: [
            SizedBox(height: MediaQuery.of(context).size.height / 3),
            SettingsButton(
              // <-- flickering widget
              text: 'Преподаватели',
              icon: Icons.people_alt_rounded,
              onClick: () {},
            ),
            const SizedBox(height: 8),
            SettingsButton(
              // <-- flickering widget
              text: 'Посещения',
              icon: Icons.access_time_rounded,
              onClick: () {},
            ),
            const SizedBox(height: 8),
            SettingsButton(
                // <-- flickering widget
                text: 'Зачетная книжка',
                icon: Icons.menu_book_rounded,
                onClick: () {}),
            const SizedBox(height: 8),
            SettingsButton(
              // <-- flickering widget
              text: 'О приложении',
              icon: Icons.apps_rounded,
              onClick: () {},
            ),
            const SizedBox(height: 8),
            SettingsButton(
                // <-- flickering widget
                text: 'Настройки',
                icon: Icons.settings_rounded,
                onClick: () {}),
            SizedBox(height: MediaQuery.of(context).size.height / 2),
          ],
        ),
      ),
    );
  }
}

class SettingsButton extends StatelessWidget {
  const SettingsButton(
      {Key? key, required this.text, required this.icon, required this.onClick})
      : super(key: key);
  final String text;
  final IconData icon;
  final Function onClick;

  @override
  Widget build(BuildContext context) {
    return SizedBox(
      height: 50,
      child: Card(
        margin: const EdgeInsets.all(0),
        shape: RoundedRectangleBorder(
          borderRadius: BorderRadius.circular(12.0),
        ),
        color: Theme.of(context).colorScheme.onSurface,
        shadowColor: Colors.transparent,
        child: InkWell(
          borderRadius: BorderRadius.circular(12),
          child: Row(
            crossAxisAlignment: CrossAxisAlignment.center,
            children: [
              Padding(
                padding: const EdgeInsets.symmetric(horizontal: 16),
                child: Icon(
                  icon,
                  color: Theme.of(context).textTheme.bodyLarge?.color,
                ),
              ),
              Text(
                text,
                style: Theme.of(context).textTheme.bodyLarge,
              ),
            ],
          ),
          onTap: () {
            onClick();
          },
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

https://github.com/flutter/flutter/assets/51058739/f9614ba5-20b6-45a1-9b3d-e1625293bb52

</details>

### Logs

<details><summary>Logs</summary>

https://pastebin.com/raw/gcyvFq6x

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.13.4, on macOS 13.5.2 22G91 darwin-arm64, locale ru-RU)
    • Flutter version 3.13.4 on channel stable at /Users/dragonprod/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 367f9ea16b (5 days ago), 2023-09-12 23:27:53 -0500
    • Engine revision 9064459a8b
    • Dart version 3.1.2
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/dragonprod/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /Users/dragonprod/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/222.4459.24.2221.9971841/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] Android Studio (version 2022.2)
    • Android Studio at /Users/dragonprod/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/222.4459.24.2221.9971841/Android
      Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] Android Studio (version 2022.2)
    • Android Studio at /Users/dragonprod/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/222.4459.24.2221.10121639/Android
      Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.4)
    • IntelliJ at /Users/dragonprod/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.2)
    • IntelliJ at /Users/dragonprod/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/231.9011.34/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.4)
    • IntelliJ at /Users/dragonprod/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/231.9225.16/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.82.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.72.0

[✓] Connected device (3 available)
    • iPhone 14 Pro Max (mobile) • 8A309035-0EF2-4307-A649-E2BA17A684E6 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-2 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 13.5.2 22G91 darwin-arm64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 116.0.5845.187

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

</details>

**Comment by darshankawar** [comment] 2023-09-19 07:43
Thanks for the report @0niel 
Can you simplify the code sample provided and just share a runnable but minimal reproducible code that we can directly copy paste and run to verify the reported behavior ?

**Comment by Benzt2h** [comment] 2023-09-19 10:34
i have same problem

**Comment by 0niel** [comment] 2023-09-19 11:20
> Thanks for the report @0niel Can you simplify the code sample provided and just share a runnable but minimal reproducible code that we can directly copy paste and run to verify the reported behavior ?

Hello!

<details><summary>Code sample</summary>

```dart

import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      themeMode: ThemeMode.dark,
      darkTheme: ThemeData.dark().copyWith(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepOrange),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: SingleChildScrollView(
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.center,
          children: [
            SizedBox(height: MediaQuery.of(context).size.height / 3),
            SettingsButton(
              // <-- flickering widget
              text: 'Преподаватели',
              icon: Icons.people_alt_rounded,
              onClick: () {},
            ),
            const SizedBox(height: 8),
            SettingsButton(
              // <-- flickering widget
              text: 'Посещения',
              icon: Icons.access_time_rounded,
              onClick: () {},
            ),
            const SizedBox(height: 8),
            SettingsButton(
                // <-- flickering widget
                text: 'Зачетная книжка',
                icon: Icons.menu_book_rounded,
                onClick: () {}),
            const SizedBox(height: 8),
            SettingsButton(
              // <-- flickering widget
              text: 'О приложении',
              icon: Icons.apps_rounded,
              onClick: () {},
            ),
            const SizedBox(height: 8),
            SettingsButton(
                // <-- flickering widget
                text: 'Настройки',
                icon: Icons.settings_rounded,
                onClick: () {}),
            SizedBox(height: MediaQuery.of(context).size.height / 2),
          ],
        ),
      ),
    );
  }
}

class SettingsButton extends StatelessWidget {
  const SettingsButton(
      {Key? key, required this.text, required this.icon, required this.onClick})
      : super(key: key);
  final String text;
  final IconData icon;
  final Function onClick;

  @override
  Widget build(BuildContext context) {
    return SizedBox(
      height: 50,
      child: Card(
        margin: const EdgeInsets.all(0),
        shape: RoundedRectangleBorder(
          borderRadius: BorderRadius.circular(12.0),
        ),
        color: Theme.of(context).colorScheme.onSurface,
        shadowColor: Colors.transparent,
        child: InkWell(
          borderRadius: BorderRadius.circular(12),
          child: Row(
            crossAxisAlignment: CrossAxisAlignment.center,
            children: [
              Padding(
                padding: const EdgeInsets.symmetric(horizontal: 16),
                child: Icon(
                  icon,
                  color: Theme.of(context).textTheme.bodyLarge?.color,
                ),
              ),
              Text(
                text,
                style: Theme.of(context).textTheme.bodyLarge,
              ),
            ],
          ),
          onTap: () {
            onClick();
          },
        ),
      ),
    );
  }
}

```

</details>



https://github.com/flutter/flutter/assets/51058739/a804dec9-ff01-45dd-a274-020f9ae97807

**Comment by darshankawar** [comment] 2023-09-19 12:19
Thanks for the update. Although I see the reported behavior on latest stable, but not on latest master, as shown below:


https://github.com/flutter/flutter/assets/67046386/e05f8587-49e5-4bf2-a062-8e99032bad21

This indicates, it works as expected on latest master, but the fix is not in stable yet. Per our triage policy, since it is fixed in master and works as expected, I am going ahead and closing as fixed.

**Closed by darshankawar** 2023-09-19 12:19 UTC
Labels: in triage
