### ISSUE TITLE
Code Signing Flutter.framework Permission Denied

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#45915] opened 2019-12-02 18:47 UTC
I'm unable to "flutter run" on a project to execute on the simulator.  A "flutter clean" doesn't fix the issue.  Here is the output:
```
mkdir -p /Users/aaclarke/dev/native_images/example/build/ios/Debug-iphonesimulator/Runner.app/Frameworks
    rsync --delete -av --filter P .*.?????? --filter "- CVS/" --filter "- .svn/" --filter "- .git/" --filter "- .hg/" --filter "-
    Headers" --filter "- PrivateHeaders" --filter "- Modules"
    "/Users/aaclarke/dev/native_images/example/ios/Pods/../Flutter/Flutter.framework"
    "/Users/aaclarke/dev/native_images/example/build/ios/Debug-iphonesimulator/Runner.app/Frameworks"
    building file list ... done
    Flutter.framework/
    Flutter.framework/Flutter
    Flutter.framework/Info.plist
    Flutter.framework/icudtl.dat
    Flutter.framework/_CodeSignature/
    Flutter.framework/_CodeSignature/CodeResources

    sent 94440048 bytes  received 120 bytes  62960112.00 bytes/sec
    total size is 94428117  speedup is 1.00
    Stripped /Users/aaclarke/dev/native_images/example/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/Flutter.framework/Flutter
    of architectures: armv7 arm64
    Code Signing /Users/aaclarke/dev/native_images/example/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/Flutter.framework with
    Identity -
    /usr/bin/codesign --force --sign -  --preserve-metadata=identifier,entitlements
    '/Users/aaclarke/dev/native_images/example/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/Flutter.framework'
    /Users/aaclarke/dev/native_images/example/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/Flutter.framework: replacing
    existing signature
    /Users/aaclarke/dev/native_images/example/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/Flutter.framework: Permission
    denied
    Command PhaseScriptExecution failed with a nonzero exit code
    note: Using new build systemnote: Planning buildnote: Constructing build description
```

It appears that the permissions for `/Users/aaclarke/dev/native_images/example/ios/Pods/../Flutter/Flutter.framework` are restrictive and the rsync is just copying them over, creating the problem.  Here is the `ls -thor` for that directory:
```
aaclarke-macbookpro2:example aaclarke$ ls -thor "/Users/aaclarke/dev/native_images/example/ios/Pods/../Flutter/Flutter.framework"
total 184432
drwxr-xr-x   3 aaclarke    96B Dec  2 10:40 _CodeSignature/
-r--r--r--   1 aaclarke   863K Dec  2 10:40 icudtl.dat
-r-xr-xr-x   1 aaclarke    89M Dec  2 10:40 Flutter*
drwxr-xr-x  17 aaclarke   544B Dec  2 10:40 Headers/
drwxr-xr-x   3 aaclarke    96B Dec  2 10:40 Modules/
-r--r--r--   1 aaclarke   963B Dec  2 10:40 Info.plist
```

I'm not sure of the steps that lead the pods permissions to be read only, but maybe it's best to fix this by tweaking our rsync script to so that the copied Flutter.framework has the permissions we need.

cc @jmagman

**Comment by gaaclarke** [comment] 2019-12-02 18:54
```
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.14.6 18G103, locale en-US)
    • Flutter version 1.9.1+hotfix.6 at /Users/aaclarke/dev/flutter
    • Framework revision 68587a0916 (3 months ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0
```

**Comment by gaaclarke** [comment] 2019-12-02 18:59
Also to note, this project is the example project for a plugin.  It can be found here: https://github.com/gaaclarke/native_images

It looks like the problem might be in the plugin template.

**Comment by jmagman** [comment] 2019-12-02 19:07
Duplicate of https://github.com/flutter/flutter/issues/40146.

**Closed by jmagman** 2019-12-02 19:07 UTC
Labels: ⌺‬ platform-ios

**Comment by ZQ1297089376** [comment] 2020-05-19 07:48
You can try to change configuration item，Build Phases->Thin Binary
/bin/sh "$FLUTTER_ROOT/packages/flutter_tools/bin/xcode_backend.sh" thin

**Comment by jmagman** [comment] 2020-05-19 18:48
@ZQ1297089376 Depending on what version you are on, if you remove the `embed` part Flutter and your compiled dart code will not actually be embedded in your app.  You are likely hitting some different problem than this issue, please file a new GitHub issue and completely fill out the template.

**Comment by TahaAli07** [comment] 2020-07-01 14:24
Moved from v1.9.1+hotfix.6 to v1.11.0 .

To change flutter version to 1.11.0 just run

`flutter version v1.11.0`

This fixed this issue for me , tried all other other highly voted solutions but none worked.
