### ISSUE TITLE
Ensure that flutter apps can be navigated with a physical keyboard

### ISSUE THREAD

**Issue by gmoraja** [flutter/flutter#47479] opened 2019-12-19 21:20 UTC
@goderbauer

Mobile apps do not seem to work with an external keyboard connected via Bluetooth: on the keyboard, the tab or arrow keys fail to change the point of focus. In the layout, it should be possible to define the focus order for each of the focusable elements, with or without Assistive Technology (Voiceover/TalkBack).

This seems to work correctly on iOS now, but not on Android.

Here is an example of a project where it's currently not working:
https://vertical.is/apps/vetchange-flutter

**Comment by goderbauer** [comment] 2019-12-19 21:36
/cc @gspencergoog 

@gmoraja Unfortunately, for security reasons I can't run this app on my phone. Can you post some runnable code that reproduces the problem that we can copy and paste to run?

Also can you post the output of `flutter doctor -v` so we can see what version of Flutter you are using?

**Comment by gmoraja** [comment] 2019-12-19 21:40
@lorenzOliveto can you help with this?

**Comment by gmoraja** [comment] 2019-12-19 21:52
In the meantime, here is the comment we received from the auditor when testing accessibility:

> To enable tab navigation: In the layout,  explicitly define the focus order for each of the focusable elements with the android:nextFocusForward attribute. | For Arrow key navigation use attributes: android:nextFocusUp / android:nextFocusDown / android:nextFocusLeft / android:nextFocusRight. (Refer to Android 10 API: https://developer.android.com/about/versions/10/features#a11y-apis | and Android 9 API: https://developer.android.com/about/versions/pie/android-9.0)

**Comment by lorenzOliveto** [comment] 2019-12-20 08:10
Here's the output of Flutter doctor:

```
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.2 19C57,
    locale it-IT)
    • Flutter version 1.12.13+hotfix.5 at /Users/lorenzooliveto/Flutter/flutter
    • Framework revision 27321ebbad (9 days ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/lorenzooliveto/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

```

We're testing on a Pixel 3A with a keyboard attached with USB, attached 2 videos:
the first (PTSD Coach) is a native app that shows the focus changes on the layout, the second (mPro) is the flutter app (https://play.google.com/store/apps/details?id=com.pavir.mpro&hl=it); we only see a green border but the focus doesn't move pressing the arrow keys.

[apps.zip](https://github.com/flutter/flutter/files/3987314/apps.zip)

**Comment by gspencergoog** [comment] 2020-01-08 00:44
I believe that this is an issue with the Flutter app in question, and not with Flutter itself: we do support navigation via the keyboard, both with TAB/Shift-TAB, and the arrow keys (and the d-pad on a game controller).

Is there a simple source code example you can give me where it doesn't work?
What widgets are being used on the pages in question?

If they are custom widgets, then they may need to add support for keyboard traversal (e.g. take a look at the [FocusableActionDetector](https://api.flutter.dev/flutter/widgets/FocusableActionDetector-class.html) widget, which handles most of the required setup).

**Comment by lorenzOliveto** [comment] 2020-01-08 09:03
Here's a simple source code with a ListView and Text Widget:

```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: ListView.builder(
        itemBuilder: (context, index) => ListTile(
          title: FocusableActionDetector(
            child: Text(
              index.toString(),
            ),
          ),
        ),
        itemCount: 50,
      ),
    );
  }
}
```

In the demo video the EULA screen uses only material or cupertino widgets: a Column with an Expanded containing a ListView, a CupertinoButton, and Text and Image widgets inside the ListView.

So you are suggesting to wrap every focusable widget on the screen within a `FocusableActionDetector` and change the appearance of the widget once it gains and loses focus?

I was expecting to function ootb as we haven't made any code change to make it work on a
the native app you're seeing in the video.

**Comment by gmoraja** [comment] 2020-01-08 16:50
@gspencergoog could you please also point us to a Flutter open-source mobile app available on the Play Store that currently supports the keyboard navigation? I tried a few but so far I haven't found one that does that.

**Comment by gspencergoog** [comment] 2020-01-08 18:00
No, you would only have to add `FocusableActionDetector` if you developed your own custom widget (your own kind of button, for instance). The standard Material widgets support keyboard traversal out of the box.

However, if you take out the `FocusableActionDetector` you added, the code snippet you have above doesn't have any focusable widgets in it. `Text` widgets aren't focusable: they don't have any meaningful user interaction when focused, in the same way that an image or padding doesn't have any useful interaction. They are focusable in accessibility modes (i.e. when TalkBack is enabled) through screen readers, but not through regular keyboard traversal.

Your code, as is, is actually handling focus because you added the `FocusableActionDetector` (which adds a `Focus` widget implicitly): notice that if you hit the "down" arrow enough times, the list will actually scroll.

Here's a modified version of your code with a small wrapper around the `Text` widget that would allow the text widget to visually show when it has focus.  It just uses the `Focus` widget and not the `FocusableActionDetector`, because that's overkill for this case (`FocusableActionDetector` handles things like keyboard activation and hover notification as well as focus).

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: ListView.builder(
        itemBuilder: (context, index) => ListTile(
          title: FocusableText(
            index.toString(),
            autofocus: index == 0,
          ),
        ),
        itemCount: 50,
      ),
    );
  }
}

class FocusableText extends StatelessWidget {
  const FocusableText(this.data, {Key key, this.autofocus}) : super(key: key);

  final String data;
  final bool autofocus;

  @override
  Widget build(BuildContext context) {
    return Focus(
      autofocus: autofocus,
      child: Builder(builder: (BuildContext context) {
        return Container(
          color: Focus.of(context).hasPrimaryFocus ? Colors.black12 : null,
          child: Text(data),
        );
      }),
    );
  }
}
```

**Comment by gspencergoog** [comment] 2020-01-08 18:32
The keyboard traversal is a fairly new feature, and is only in the latest stable build, so many apps on the app store may not have rebuilt with it yet.

Here's one [open source example](https://play.google.com/store/apps/details?id=io.github.x_wei.flutter_catalog&hl=en_US) that has support.

**Comment by gmoraja** [comment] 2020-01-09 00:33
Got it. I just tried the app you shared and it works indeed. The focus on the elements doesn't follow a precise order but hopefully, that's something that can be manually set up. @lorenzOliveto what do you think?

**Comment by gspencergoog** [comment] 2020-01-09 00:44
That example actually has a bug in the way it is implemented: it has a Stack widget used to implement the sliding preferences pane behind the main page, and those widgets are still active and participating in focus traversal: it's an easy fix to add a `FocusScope` to prevent that.

**Comment by Hixie** [comment] 2020-01-15 00:26
Sounds like this is working as intended, so I'm going to close the issue. Please don't hesitate to file a new bug if you find something that doesn't work. Thanks!

**Closed by Hixie** 2020-01-15 00:26 UTC
Labels: a: desktop, customer: soldier, framework, severe: customer critical

**Comment by gmoraja** [comment] 2020-01-15 00:38
@Hixie we're currently testing the behavior of the app following @gspencergoog's suggestions. We encountered multiple issues but I was waiting to complete the round of testing to provide consolidated feedback. Could you please reopen the issue? We will be able to complete our update in one or two days.

**Comment by goderbauer** [comment] 2020-01-15 00:44
@gmoraja Can you please file new issues for each bug you encounter? For our workflow it would be best to have separate issues for each bug you encounter.

**Comment by gmoraja** [comment] 2020-01-15 18:40
ok @goderbauer I opened the following issues:
https://github.com/flutter/flutter/issues/48903
https://github.com/flutter/flutter/issues/48904
https://github.com/flutter/flutter/issues/48905

and found two existing issues describing what we're also experiencing:
https://github.com/flutter/flutter/issues/47156
https://github.com/flutter/flutter/issues/19027

Would it be possible to label them as "severe: customer critical", as Chris Sells originally did for this one?

**Comment by hkwinslow** [comment] 2021-02-19 17:44
I cannot navigate my iOS Flutter app using a bluetooth keyboard. When I click tab to go to the next input field, it just adds a tab character (or space) in the text field. Any ideas?
