### ISSUE TITLE
TextField background color changes to dark grey unexpectedly when it gets focused at flutter v1.6.1-pre.47

### ISSUE THREAD

**Issue by sgon00** [flutter/flutter#33109] opened 2019-05-21 06:26 UTC
Flutter doctor

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.6.1-pre.47, on Mac OS X 10.13.6 17G4015, locale en-CN)
```

After upgrading flutter master to v1.6.1-pre.47, I find out when I click on a TextField, the background color of the TextField becomes dark grey (when I have a filled white color decoration). This is unexpected. The previous behavior is the background color remains the same as white. 

Whether this is a new feature or a bug, how can I make the background color unchanged as before? 

Thanks a lot. 

**Edited:** 

* I just figured out the problem only happens when TextField has a decoration with a filled color, such as:

```dart
          TextField(
            decoration: InputDecoration(
              filled: true,
              fillColor: Colors.white,
              border: InputBorder.none,
            ),
            minLines: 1,
            maxLines: 5,
          ),
```

The above code will have this issue and this never happens before the flutter upgrade.

* If I comment out the filled color arguments, the problem is gone. For example:

```dart
          TextField(
            decoration: InputDecoration(
              border: InputBorder.none,
            ),
            minLines: 1,
            maxLines: 5,
          ),
```

The above code will not have this issue when there is no filled color.

**Edited:** adding a screenshot:

![flutter_07](https://user-images.githubusercontent.com/1555508/58079633-051c2000-7be4-11e9-8bf1-4033e980395f.png)

**Comment by 643063150** [comment] 2019-05-28 07:02
me  to，i  use  this  [https://blog.csdn.net/weixin_44893898/article/details/89184101](url)

**Comment by atul-chaudhary** [comment] 2020-01-15 08:53
Is there any way to set the background color to white because i am having a different background color

**Comment by VladyslavBondarenko** [comment] 2020-07-29 13:19
@sgon00 
I can't reproduce it with current master `1.21.0-6.0.pre.90` running with Android 9 device and iOS 13.6 simulator.

<details>
 <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.21.0-6.0.pre.90, on Mac OS X 10.15.6 19G73, locale en-GB)
    • Flutter version 1.21.0-6.0.pre.90 at /Users/nevercode/dev/flutter
    • Framework revision 531ee9452a (85 minutes ago), 2020-07-29 02:26:03 -0400
    • Engine revision 1ba310017c
    • Dart version 2.10.0 (build 2.10.0-1.0.dev 24c7666def)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/nevercode/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[✓] Connected device (6 available)
    • Redmi Note 7 (mobile)       • 6345c469                                 • android-arm64  • Android 9 (API 28)
    • Nevercode’s iPhone (mobile) • b668e524315069f3db3661ac11ff1f66afafebdb • ios            • iOS 13.6
    • iPhone 11 Pro Max (mobile)  • 55C8466B-5367-492B-8EFE-EC45D980571F     • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-6 (simulator)
    • macOS (desktop)             • macos                                    • darwin-x64     • Mac OS X 10.15.6 19G73
    • Web Server (web)            • web-server                               • web-javascript • Flutter Tools
    • Chrome (web)                • chrome                                   • web-javascript • Google Chrome 84.0.4147.105

• No issues found!
```

</details>

Seems to be fixed, closing

**Closed by VladyslavBondarenko** 2020-07-29 13:19 UTC
Labels: a: text input, framework

**Comment by flutterq** [comment] 2021-01-15 15:48
Step By Step Guide to [flutter textfield background color on focus](https://flutterq.com/wp-admin/post.php?post=247&action=edit)
