### ISSUE TITLE
AppBar brightness: Brightness.light won't change status bar's color on iOS dark mode

### ISSUE THREAD

**Issue by edgarfroes** [flutter/flutter#41236] opened 2019-09-24 23:49 UTC
My app's AppBar has a white background. When on Dark Theme in iOS, after settings `brightness: Brightness.light`, the status bar's text won't change color and will stand white.

The print below shows the white text over the white AppBar

![IMG_9BCF9BF94CA3-1](https://user-images.githubusercontent.com/4291391/65557270-1b771700-df09-11e9-801d-c3d1903a8645.jpeg)

Should I change the app's color scheme to fit iOS' Dark Theme or is this a legit bug?

<details>
<summary>flutter doctor -v</summary>

```

[✓] Flutter (Channel master, v1.10.6-pre.49, on Mac OS X 10.14.6 18G95, locale pt-BR)
    • Flutter version 1.10.6-pre.49 at /Volumes/Repos/flutter
    • Framework revision 81e693a7fe (4 hours ago), 2019-09-24 12:38:45 -0700
    • Engine revision b875c7a5ff
    • Dart version 2.6.0 (build 2.6.0-dev.0.0 7c1821c4aa)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/edgar/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.0, Build version 11A420a
    • CocoaPods version 1.7.5

[!] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.38.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.4.1

[✓] Connected device (1 available)
    • iPhone de Edgar • 00008020-000D54182E90003A • ios • iOS 13.1

! Doctor found issues in 1 category.

```

</details>

**Comment by edgarfroes** [comment] 2019-09-24 23:50
Duplicate of #41067

**Comment by jonahwilliams** [comment] 2019-09-25 00:30
Thanks! - Closing as duplicate of #41067

**Closed by jonahwilliams** 2019-09-25 00:30 UTC
