### ISSUE TITLE
[web]: Clipboard support on Flutter Web

### ISSUE THREAD

**Issue by blockspacer** [flutter/flutter#40124] opened 2019-09-10 04:40 UTC
Clipboard support should be implemented in Flutter Web. It needs to be wired with Flutter's Clipboard Service.

reopen of https://github.com/flutter/flutter/issues/33470

**Comment by pennzht** [comment] 2019-12-03 15:21
`Clipboard` support still doesn't work on Web.

## Steps to reproduce
1. Create a Flutter project and use the following code as `main.dart`.
2. Run the project.
3. Click on the "COPY TEXT" button.
4. Try to paste elsewhere.

The two buttons correctly copy the texts 'Text ONE (1) copied.' and 'Text TWO (2) copied.' to clipboard on mobile devices.
When run in Chrome, the two buttons **do not** copy the texts to the clipboard.

```
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(body: MyHomePage()),
    );
  }
}

class MyHomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    void _handleSuccess(dynamic result) {
      Scaffold.of(context).showSnackBar(
        SnackBar(
          content: Text('_handleSuccess called with result $result.'),
        ),
      );
    }

    void _handleError(Object exception) {
      Scaffold.of(context).showSnackBar(
        SnackBar(
          content: Text('_handleError called with exception $exception.'),
        ),
      );
    }

    return Center(
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          RaisedButton(
            child: Text('COPY TEXT ONE (1)'),
            onPressed: () async {
              await Clipboard.setData(
                ClipboardData(text: 'Text ONE (1) copied.'),
              ).then(_handleSuccess, onError: _handleError);
            },
          ),
          RaisedButton(
            child: Text('COPY TEXT TWO (2)'),
            onPressed: () async {
              await Clipboard.setData(
                ClipboardData(text: 'Text TWO (2) copied.'),
              ).then(_handleSuccess, onError: _handleError);
            },
          ),
        ],
      ),
    );
  }
}
```

**Comment by nturgut** [comment] 2019-12-03 21:44
Thanks for filing the issue. This will be tracked in 2 parts:

- For browsers who support clipboard API: https://github.com/flutter/flutter/issues/46020
- For other browsers: https://github.com/flutter/flutter/issues/46022

**Comment by nturgut** [comment] 2019-12-03 21:45
marking as duplicate since we created 2 follow up issues. thanks again for the feedback.

**Closed by nturgut** 2019-12-03 21:45 UTC
Labels: severe: new feature, ☸ platform-web
