### ISSUE TITLE
Firebase storage App check error - No App Check token for request. 

### ISSUE THREAD

**Issue by randomizedlife01** [flutter/flutter#88564] opened 2021-08-20 06:06 UTC
Hello, I am using Firebase storage. And when I log in from multiple devices, I'm testing the output of the data that the user has saved. The Android emulator and iOS simulator are now logged in as one id to proceed with the test.

The problem occurs here. Firebase firestore loads data without problems, while attempting to import a saved image results in the following error:

W/NetworkRequest(13036): No App Check token for request.

After searching for a long time, I concluded that this happens in App check plugin. But I'm...

https://firebase.flutter.dev/docs/app-check/overview

I've written everything that this official document requires, but the problem hasn't been solved. The biggest problem is that the local debug token is not output. Since then, I have removed the App check plugin and deleted the contents created from all files, but still the same error is still output.

Is there a way to solve this problem? Please help me.

here is my code...

ios/appdelegate.swift

```
import UIKit
import Flutter

@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {
  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
  ) -> Bool {
    GeneratedPluginRegistrant.register(with: self)
    FirebaseApp.initializeApp(/*context=*/ this);
    FirebaseAppCheck firebaseAppCheck = FirebaseAppCheck.getInstance();
    firebaseAppCheck.installAppCheckProviderFactory(
    DebugAppCheckProviderFactory.getInstance());
    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }
}
```

android/app/bundle.gradle

```
dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation platform('com.google.firebase:firebase-bom:28.3.0')
    implementation 'com.google.firebase:firebase-analytics'
    implementation 'com.android.support:multidex:1.0.3'
    implementation 'com.google.firebase:firebase-appcheck-safetynet:16.0.0-beta02'
}

```

android/MainActivity.java

```
package com.artboypark.oharu_app;

import android.os.Bundle;
import android.util.Log;

import io.flutter.embedding.android.FlutterActivity;

import com.google.firebase.FirebaseApp;
import com.google.firebase.appcheck.FirebaseAppCheck;
import com.google.firebase.appcheck.safetynet.GeneratedPluginRegistrant;
import com.google.firebase.appcheck.safetynet.SafetyNetAppCheckProviderFactory;

public class MainActivity extends FlutterActivity {
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        FirebaseApp.initializeApp(/*context=*/ this);
        FirebaseAppCheck firebaseAppCheck = FirebaseAppCheck.getInstance();
        firebaseAppCheck.installAppCheckProviderFactory(SafetyNetAppCheckProviderFactory.getInstance());
        GeneratedPluginRegistrant.registerWith(this);
    }
}
```

lib/main.dart

```
Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();
  await FirebaseAppCheck.instance.activate(webRecaptchaSiteKey: 'Your reCAPTCHA v3 site key...');
  SystemChrome.setPreferredOrientations([DeviceOrientation.portraitUp, DeviceOrientation.portraitDown]).then((_) {
    runApp(const OharuApp());
  });
}

```

please help!

**Comment by TahaTesser** [comment] 2021-08-23 08:40
Hi @randomizedlife01 
From what I can see, the issue is related to a FlutterFire plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  providing your `flutter doctor -v`, your `pubspec.yaml`, a minimal reproducible code sample that does not use 3rd party plugins, your complete `flutter run -v` logs running the minimal code sample 
and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-08-23 08:40 UTC
Labels: in triage
