### ISSUE TITLE
Dialog Widget Click event is translucent to lower layer

### ISSUE THREAD

**Issue by ShuoShen-Susan** [flutter/flutter#81617] opened 2021-05-01 16:07 UTC
Hello~everyone,
I have an app, which has Google Maps on the bottom.
Sometimes, some widgets overlay the Map, like alterDialog, Drawers.
However, the click event on the screen is translucent. When I interact on the upper widget, the gesture will also affect the lower widget(the Google Map). I don't want users to interact with the lower layer widgets.
Is there some method to block the gestures?
I try the GestureDetector and RawGestureDetector, it works not very well.

My code:

<details> 
<summary>code sample</summary> 

```dart
Class HomePage  extends StatefulWidget {
Widget build(BuildContext context) {
return Scaffold(
      key: _scaffoldKey,
      endDrawer: Drawer(
        child: OrderList(),
      ),
      body: Stack(
        children: [
          GoogleMap(
              mapType: MapType.normal,
              myLocationButtonEnabled: true,
              myLocationEnabled: true,
              zoomControlsEnabled: false,
              initialCameraPosition: _currentPositionCamera == null
                  ? _cityCenter
                  : _currentPositionCamera!,
              markers: Set.from(markers),
              polylines: polylines,
              onMapCreated: (GoogleMapController controller) {
                if (!_controller.isCompleted) {
                  _controller.complete(controller);
                }
              },
              onCameraMove: _onGeoChanged),
          Align(
            alignment: Alignment.bottomLeft,
            child: Padding(
              padding: const EdgeInsets.fromLTRB(10.0, 0.0, 0.0, 138.0),
              child: FloatingActionButton(
                heroTag: 'Inner',
                backgroundColor: themeColor,
                child: Icon(
                  Icons.edit_location_rounded,
                  color: defaultBlack,
                ),
                onPressed: () {
                  setState(() {
                    ridersDialog(context);
                    editMode = true;
                  });
                },
              ),
            ),
          ),
        ],
      ),
    );
}
}
```

Overlay widget Dialog
``
```
Future<dynamic> ridersDialog(BuildContext context) {
  return showAnimatedDialog(
      context: context,
      barrierDismissible: true,
      animationType: DialogTransitionType.slideFromLeft,
      duration: Duration(milliseconds: 500),
      builder: (BuildContext context) {
        return GestureDetector(
          behavior: HitTestBehavior.deferToChild,
          child: Container(
              child: AlertDialog(
                titlePadding: EdgeInsets.fromLTRB(16.0, 13.0, 16.0, 0.0),
                contentPadding: EdgeInsets.fromLTRB(16.0, 7.0, 16.0, 16.0),
                backgroundColor: Theme.of(context).backgroundColor,
                title: Center(
                  child: Text(tr("selectLanguage"),
                      style: Theme.of(context)
                          .textTheme
                          .headline2!
                          .copyWith(fontWeight: FontWeight.bold)),
                ),
                content: Text(
                              rider.alias!,
                              style: Theme.of(context).textTheme.headline4,
                            ),
              )),
        );
      });
}
``` 

</details>

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[√] Flutter (Channel stable, 2.0.4, on Microsoft Windows [Version 10.0.19041.1], locale en-US)
    • Flutter version 2.0.4 at D:\internship\flutter
    • Framework revision b1395592de (4 weeks ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at D:\internship\Android
    • Platform android-30, build-tools 30.0.3
    • Java binary at: D:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at D:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 89.0.4389.90
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 89.0.774.76

! Doctor found issues in 1 category.
```
		
</details>

**Comment by TahaTesser** [comment] 2021-05-03 09:23
Hi @Lyiyian 
Are you experiencing this issue on the web https://github.com/flutter/flutter/issues/80655
Check out my minimal reproducible code sample in https://github.com/flutter/flutter/issues/80655#issuecomment-822273717
I can't reproduce it on the iOS simulator, are you experiencing it on mobile?

**Comment by TahaTesser** [comment] 2021-05-27 12:43
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by TahaTesser** 2021-05-27 12:43 UTC
