### ISSUE TITLE
Web surface rendering failure when resizing and scrolling views in DevTools

### ISSUE THREAD

**Issue by DaveShuckerow** [flutter/flutter#45122] opened 2019-11-18 21:18 UTC
Scrolling around in the inspector page of the app and resizing the app too much leads to this stack trace:

```
══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
The following NoSuchMethodError was thrown during a scheduler callback:
'<Unexpected Null Value>'
method not found
Receiver: null
Arguments: []

When the exception was thrown, this was the stack:
package:dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 194:49      throw_
package:dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 35:3        throwNullValueError
package:dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 462:39  _notNull
package:build_web_compilers/lib/_engine/engine/dom_canvas.dart 95:39                      drawRect
package:build_web_compilers/lib/_engine/engine/recording_canvas.dart 775:11               apply
package:build_web_compilers/lib/_engine/engine/recording_canvas.dart 77:22                apply
package:build_web_compilers/lib/_engine/engine/surface/picture.dart 223:29                [_applyDomPaint]
package:build_web_compilers/lib/_engine/engine/surface/picture.dart 213:7                 applyPaint
package:build_web_compilers/lib/_engine/engine/surface/picture.dart 525:5                 [_applyPaint]
package:build_web_compilers/lib/_engine/engine/surface/picture.dart 538:5                 apply
package:build_web_compilers/lib/_engine/engine/surface/surface.dart 644:5                 build
package:build_web_compilers/lib/_engine/engine/surface/picture.dart 544:11                build
package:build_web_compilers/lib/_engine/engine/surface/surface.dart 959:14                build
package:build_web_compilers/lib/_engine/engine/surface/surface.dart 959:14                build
package:build_web_compilers/lib/_engine/engine/surface/surface.dart 959:14                build
package:build_web_compilers/lib/_engine/engine/surface/surface.dart 959:14                build
package:build_web_compilers/lib/_engine/engine/surface/surface.dart 1142:15               [_updateManyToOne]
package:build_web_compilers/lib/_engine/engine/surface/surface.dart 989:7                 update
package:build_web_compilers/lib/_engine/engine/surface/offset.dart 45:11                  update
package:build_web_compilers/lib/_engine/engine/surface/surface.dart 1108:15               [_updateManyToOne]
package:build_web_compilers/lib/_engine/engine/surface/surface.dart 989:7                 update
package:build_web_compilers/lib/_engine/engine/surface/offset.dart 45:11                  update
package:build_web_compilers/lib/_engine/engine/surface/surface.dart 1204:17               [_updateManyToMany]
package:build_web_compilers/lib/_engine/engine/surface/surface.dart 993:7                 update
package:build_web_compilers/lib/_engine/engine/surface/offset.dart 45:11                  update
package:build_web_compilers/lib/_engine/engine/surface/surface.dart 1108:15               [_updateManyToOne]
package:build_web_compilers/lib/_engine/engine/surface/surface.dart 989:7                 update
package:build_web_compilers/lib/_engine/engine/surface/offset.dart 45:11                  update
package:build_web_compilers/lib/_engine/engine/surface/surface.dart 1204:17               [_updateManyToMany]
package:build_web_compilers/lib/_engine/engine/surface/surface.dart 993:7                 update
package:build_web_compilers/lib/_engine/engine/surface/offset.dart 45:11                  update
package:build_web_compilers/lib/_engine/engine/surface/surface.dart 1108:15               [_updateManyToOne]
package:build_web_compilers/lib/_engine/engine/surface/surface.dart 989:7                 update
package:build_web_compilers/lib/_engine/engine/surface/clip.dart 99:11                    update
package:build_web_compilers/lib/_engine/engine/surface/surface.dart 1133:15               [_updateManyToOne]
package:build_web_compilers/lib/_engine/engine/surface/surface.dart 989:7                 update
package:build_web_compilers/lib/_engine/engine/surface/offset.dart 45:11                  update
package:build_web_compilers/lib/_engine/engine/surface/surface.dart 1108:15               [_updateManyToOne]
package:build_web_compilers/lib/_engine/engine/surface/surface.dart 989:7                 update
package:build_web_compilers/lib/_engine/engine/surface/offset.dart 45:11                  update
package:build_web_compilers/lib/_engine/engine/surface/surface.dart 1204:17               [_updateManyToMany]
package:build_web_compilers/lib/_engine/engine/surface/surface.dart 993:7                 update
package:build_web_compilers/lib/_engine/engine/surface/offset.dart 45:11                  update
package:build_web_compilers/lib/_engine/engine/surface/surface.dart 1108:15               [_updateManyToOne]
package:build_web_compilers/lib/_engine/engine/surface/surface.dart 989:7                 update
package:build_web_compilers/lib/_engine/engine/surface/offset.dart 45:11                  update
package:build_web_compilers/lib/_engine/engine/surface/surface.dart 1204:17               [_updateManyToMany]
package:build_web_compilers/lib/_engine/engine/surface/surface.dart 993:7                 update
package:build_web_compilers/lib/_engine/engine/surface/offset.dart 45:11                  update
package:build_web_compilers/lib/_engine/engine/surface/surface.dart 1108:15               [_updateManyToOne]
package:build_web_compilers/lib/_engine/engine/surface/surface.dart 989:7                 update
package:build_web_compilers/lib/_engine/engine/surface/offset.dart 45:11                  update
package:build_web_compilers/lib/_engine/engine/surface/surface.dart 1108:15               [_updateManyToOne]
package:build_web_compilers/lib/_engine/engine/surface/surface.dart 989:7                 update
package:build_web_compilers/lib/_engine/engine/surface/clip.dart 99:11                    update
package:build_web_compilers/lib/_engine/engine/surface/surface.dart 1108:15               [_updateManyToOne]
package:build_web_compilers/lib/_engine/engine/surface/surface.dart 989:7                 update
package:build_web_compilers/lib/_engine/engine/surface/offset.dart 45:11                  update
package:build_web_compilers/lib/_engine/engine/surface/surface.dart 1108:15               [_updateManyToOne]
package:build_web_compilers/lib/_engine/engine/surface/surface.dart 989:7                 update
package:build_web_compilers/lib/_engine/engine/surface/offset.dart 45:11                  update
package:build_web_compilers/lib/_engine/engine/surface/surface.dart 1204:17               [_updateManyToMany]
package:build_web_compilers/lib/_engine/engine/surface/surface.dart 993:7                 update
package:build_web_compilers/lib/_engine/engine/surface/offset.dart 45:11                  update
package:build_web_compilers/lib/_engine/engine/surface/surface.dart 1204:17               [_updateManyToMany]
package:build_web_compilers/lib/_engine/engine/surface/surface.dart 993:7                 update
package:build_web_compilers/lib/_engine/engine/surface/offset.dart 45:11                  update
package:build_web_compilers/lib/_engine/engine/surface/surface.dart 1108:15               [_updateManyToOne]
package:build_web_compilers/lib/_engine/engine/surface/surface.dart 989:7                 update
package:build_web_compilers/lib/_engine/engine/surface/clip.dart 99:11                    update
package:build_web_compilers/lib/_engine/engine/surface/surface.dart 1108:15               [_updateManyToOne]
package:build_web_compilers/lib/_engine/engine/surface/surface.dart 989:7                 update
package:build_web_compilers/lib/_engine/engine/surface/offset.dart 45:11                  update
package:build_web_compilers/lib/_engine/engine/surface/surface.dart 1108:15               [_updateManyToOne]
package:build_web_compilers/lib/_engine/engine/surface/surface.dart 989:7                 update
package:build_web_compilers/lib/_engine/engine/surface/offset.dart 45:11                  update
package:build_web_compilers/lib/_engine/engine/surface/surface.dart 1204:17               [_updateManyToMany]
package:build_web_compilers/lib/_engine/engine/surface/surface.dart 993:7                 update
package:build_web_compilers/lib/_engine/engine/surface/offset.dart 45:11                  update
package:build_web_compilers/lib/_engine/engine/surface/surface.dart 1204:17               [_updateManyToMany]
package:build_web_compilers/lib/_engine/engine/surface/surface.dart 993:7                 update
package:build_web_compilers/lib/_engine/engine/surface/clip.dart 306:11                   update
package:build_web_compilers/lib/_engine/engine/surface/surface.dart 1204:17               [_updateManyToMany]
package:build_web_compilers/lib/_engine/engine/surface/surface.dart 993:7                 update
package:build_web_compilers/lib/_engine/engine/surface/offset.dart 45:11                  update
package:build_web_compilers/lib/_engine/engine/surface/surface.dart 1108:15               [_updateManyToOne]
package:build_web_compilers/lib/_engine/engine/surface/surface.dart 989:7                 update
package:build_web_compilers/lib/_engine/engine/surface/offset.dart 45:11                  update
package:build_web_compilers/lib/_engine/engine/surface/surface.dart 1108:15               [_updateManyToOne]
package:build_web_compilers/lib/_engine/engine/surface/surface.dart 989:7                 update
package:build_web_compilers/lib/_engine/engine/surface/transform.dart 42:11               update
package:build_web_compilers/lib/_engine/engine/surface/surface.dart 1108:15               [_updateManyToOne]
package:build_web_compilers/lib/_engine/engine/surface/surface.dart 989:7                 update
package:build_web_compilers/lib/_engine/engine/surface/scene_builder.dart 468:23          build
package:flutter/src/rendering/layer.dart 767:35                                           buildScene
package:flutter/src/rendering/view.dart 227:36                                            compositeFrame
package:flutter/src/rendering/binding.dart 347:16                                         drawFrame
package:flutter/src/widgets/binding.dart 774:13                                           drawFrame
package:flutter/src/rendering/binding.dart 283:5                                          [_handlePersistentFrameCallback]
package:flutter/src/scheduler/binding.dart 1100:15                                        [_invokeFrameCallback]
package:flutter/src/scheduler/binding.dart 1039:9                                         handleDrawFrame
package:flutter/src/scheduler/binding.dart 955:5                                          [_handleDrawFrame]
package:build_web_compilers/lib/_engine/engine.dart 176:21                                <fn>
════════════════════════════════════════════════════════════════════════════════════════════════════
Another exception was thrown: Assertion failed:
org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/surface/scene_builder.dart:227:12
```

```
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.10.16-pre.70, on Mac OS X 10.14.6 18G87, locale en-US)
[✓] Chrome - develop for the web
[✓] Android Studio
[✓] IntelliJ IDEA Community Edition (version 2019.1.3)
[✓] Connected device (3 available)
```

**Comment by yjbanov** [comment] 2020-01-30 23:17
This looks like a duplicate of https://github.com/flutter/flutter/issues/43931 (the exception is exactly the same)

**Closed by yjbanov** 2020-01-30 23:17 UTC
Labels: customer: webeap, framework, severe: crash, t: devtools, ☸ platform-web
