### ISSUE TITLE
[in_app_purchase] users don't get the trial period offer after upgrading to a new version

### ISSUE THREAD

**Issue by mikron123** [flutter/flutter#148672] opened 2024-05-20 11:40 UTC
### Steps to reproduce

On Android, the subscription process is charging the users instead of offering the only offer (3 days free trial) like it used to be.

I didn't find any documentation or a hint in the change logs, is it a bug or a syntax change?

### Expected results

Subscription offer has to be offered immediately

### Actual results

on purchase, the user is being charged without suggesting the offer.

**Comment by top2429** [comment] 2024-05-21 06:56
> ### Steps to reproduce
> * Use a phone in landscape orientation (I use pixel 3a, simulator)
> * Focus the first TextField
> * Go to the next TextField with keyboard or click on the next TextField.
> * Keyboard disappears, while in flutter 3.19.2 or before it worked fine.
> 
> ### Expected results
> It is expected that the keyboard also stays visible if the focus goes to the next TextField when the phone is in in landscape orientation.
> 
> * Flutter 3.22.0: Keyboard disappears
> * Flutter 3.19.2 Keyboard stays visible like expected (like the versions before)
> 
> ### Actual results
> * In landscape orientation the keyboard disappears when the next TextField gets focus.
> * You need to click the TextField again to show the keyboard.
> 
> ### Code sample
> Code sample
> ```dart
> void main() {
>   runApp(const MyApp());
> }
> 
> class MyApp extends StatelessWidget {
>   const MyApp({super.key});
> 
>   // This widget is the root of your application.
>   @override
>   Widget build(BuildContext context) {
>     return MaterialApp(
>       title: 'Flutter Demo',
>       theme: ThemeData(
>         colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
>         useMaterial3: true,
>       ),
>       home: const MyHomePage(title: 'Flutter Demo Home Page'),
>     );
>   }
> }
> 
> class MyHomePage extends StatefulWidget {
>   const MyHomePage({super.key, required this.title});
> 
>   final String title;
> 
>   @override
>   _MyHomePageState createState() => _MyHomePageState();
> }
> 
> class _MyHomePageState extends State<MyHomePage> {
>   @override
>   void initState() {
>     super.initState();
>   }
> 
>   @override
>   Widget build(BuildContext context) {
>     return Scaffold(
>         appBar: AppBar(
>           title: Text(widget.title),
>         ),
>         body: CustomScrollView(slivers: [
>           SliverToBoxAdapter(
>               child: Container(
>             height: 500,
>             color: Colors.amber,
>           )),
>           SliverToBoxAdapter(child: Builder(builder: (context) {
>             return const Column(
>               children: [
>                 SizedBox(
>                   height: 72.0,
>                   child: Row(children: [
>                     Expanded(
>                         child:
>                             TextField(textInputAction: TextInputAction.next)),
>                     SizedBox(
>                       width: 8.0,
>                     ),
>                     Expanded(child: TextField()),
>                   ]),
>                 ),
>               ],
>             );
>           })),
>           SliverToBoxAdapter(
>               child: Container(
>             height: 500,
>             color: Colors.amber,
>           )),
>         ]));
>   }
> }
> ```
> 
> ### Screenshots or Video
> Difference flutter 3.19.2 vs 3.22.0
> 
> Flutter 3.22.0, No Keyboard
> ![image](https://private-user-images.githubusercontent.com/32017307/332047086-cc0d2a79-d4a5-4b3e-a7b3-2417e6dd2284.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyNzQ4NjIsIm5iZiI6MTcxNjI3NDU2MiwicGF0aCI6Ii8zMjAxNzMwNy8zMzIwNDcwODYtY2MwZDJhNzktZDRhNS00YjNlLWE3YjMtMjQxN2U2ZGQyMjg0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIxVDA2NTYwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4YzdlYWRlMWE3YjMxMmY1MGI4ODQ1NWExMDE5YzY4ZjNmNGEyZTZkMmE1YzJmNWQ3ZGJlOWExYTAwMmI4ZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.l1h7nqpXlfHkrBZClQmGG7bFGboEW_sfYcoQ03cAtFU)
> 
> Flutter 3.19.2, Keyboard stays visible
> ![image](https://github.com/flutter/flutter/assets/32017307/d2465e52-4151-4e34-ba9e-df35ebff6a3a)
> ### Logs
> Logs
> ```
> No log at moment.
> 
> </details>
> 
> 
> ### Flutter Doctor output
> 
> <details open><summary>Doctor output Flutter 3.22.0</summary>
> 
> ```console
> Doctor summary (to see all details, run flutter doctor -v):
> [√] Flutter (Channel stable, 3.22.0, on Microsoft Windows [Version
>     10.0.22631.3593], locale en-NL)
> [√] Windows Version (Installed version of Windows is version 10 or higher)
> [!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
>     X cmdline-tools component is missing
>       Run `path/to/sdkmanager --install "cmdline-tools;latest"`
>       See https://developer.android.com/studio/command-line for more details.
>     X Android license status unknown.
>       Run `flutter doctor --android-licenses` to accept the SDK licenses.
>       See https://flutter.dev/docs/get-started/install/windows#android-setup for
>       more details.
> [√] Chrome - develop for the web
> [X] Visual Studio - develop Windows apps
>     X Visual Studio not installed; this is necessary to develop Windows apps.
>       Download at https://visualstudio.microsoft.com/downloads/.
>       Please install the "Desktop development with C++" workload, including all of
>       its default components
> [√] Android Studio (version 2023.3)
> [√] VS Code (version 1.89.1)
> [√] Connected device (5 available)
> [√] Network resources
> ```
> 
> Doctor output Flutter 3.19.2
> ```
> Success
> PS C:\Repositories\flutter\test\keyboard_bug> flutter doctor   
> Doctor summary (to see all details, run flutter doctor -v):
> [√] Flutter (Channel stable, 3.19.2, on Microsoft Windows [Version
>     10.0.22631.3593], locale en-NL)
> [√] Windows Version (Installed version of Windows is version 10 or higher)
> [!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
>     X cmdline-tools component is missing
>       Run `path/to/sdkmanager --install "cmdline-tools;latest"`
>       See https://developer.android.com/studio/command-line for more details.      
>     X Android license status unknown.
>       Run `flutter doctor --android-licenses` to accept the SDK licenses.
>       See https://flutter.dev/docs/get-started/install/windows#android-setup for   
>       more details.
> [√] Chrome - develop for the web
> [X] Visual Studio - develop Windows apps
>     X Visual Studio not installed; this is necessary to develop Windows apps.      
>       Download at https://visualstudio.microsoft.com/downloads/.
>       Please install the "Desktop development with C++" workload, including all of 
>       its default components
> [√] Android Studio (version 2023.3)
> [√] VS Code (version 1.89.1)
> [√] Connected device (5 available)
> [√] Network resources
> ```

**Comment by darshankawar** [comment] 2024-05-21 07:59
@mikron123 
Can you provide `flutter doctor -v`, previous plugin in which it worked as usual and the version you upgraded to in which you are seeing the reported error ? Also, please provide us reproducible code sample.

**Comment by mikron123** [comment] 2024-05-21 08:06
> @mikron123 Can you provide `flutter doctor -v`, previous plugin in which it worked as usual and the version you upgraded to in which you are seeing the reported error ? Also, please provide us reproducible code sample.

I do not see any error, that's the thing. It just doesn't offer the 3 days trial, and the subscription on the Google Play Console hasn't been changed at all. As well as the purchase code on my end: `_connection.buyNonConsumable(purchaseParam: purchaseParam);`

I upgraded from version 3.0.8 to 3.1.13

**Comment by mikron123** [comment] 2024-05-21 11:19
To narrow it down - version 3.1.5 offers the trial, >= 3.1.6 ignores the trial offer. Is there an API to choose the offer alongside the purchase?

**Comment by darshankawar** [comment] 2024-05-22 06:25
Can you upgrade to latest version and re-run your scenario to check if it persists still or not ? There have been few updates for Android as I see from changelog.

**Comment by mikron123** [comment] 2024-05-22 07:03
> Can you upgrade to latest version and re-run your scenario to check if it persists still or not ? There have been few updates for Android as I see from changelog.

Version 3.2.0 - Same result. As said, I went over all the versions in between, simply changing the version and then running - it started on 3.1.6

**Comment by darshankawar** [comment] 2024-05-23 05:26
This seems to be similar to https://github.com/flutter/flutter/issues/143514 in which you have already commented, so I suggest you to follow-up in it for further updates. Closing this as a duplicate. If you disagree, write in comments and I'll reopen it.

**Closed by darshankawar** 2024-05-23 05:26 UTC
Labels: in triage
