### ISSUE TITLE
Scrollable body inside `NestedScrollView` does not scroll when there are a few items and `SliverAppBar` is pinned

### ISSUE THREAD

**Issue by raulmabe** [flutter/flutter#82546] opened 2021-05-14 15:15 UTC
I have implemented a combination of `NestedScrollView` with the `OverlapAbsorber/OverlapInjector`, and `TabBarView` where every tab has an infinite list. I have encountered a bug where when there isn't enough items on a list to cover the height of the screen the scrollable body of the corresponding tab stops being scrollable. This happens only when the `SliverAppBar` has `pinned` to `true`. Moreover, if you change tabs, the same scrollable body that stopped being scrollable now becomes scrollable. 

## Steps to Reproduce
[Minimum Code on DartPad](https://dartpad.dev/5e8421981a88e27735cdf6f706e2cba1)

I recommend on playing with the height of the container and the pinned property to see how it changes the behaviour.

**Expected results:** I expected the CustomScrollView on first page to be always scrollable

**Actual results:** The CustomScrollView on first page does not scroll before changing tabs, but do afterwards

<details>
  <summary>Flutter doctor</summary>

```
[✓] Flutter (Channel stable, 2.0.4, on macOS 11.1 20C69 darwin-x64, locale es-ES)
    • Flutter version 2.0.4 at /Users/mabe/development/flutter
    • Framework revision b1395592de (6 weeks ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/mabe/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.56.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.22.0

[✓] Connected device (2 available)
    • MySim (mobile) • 17E8835A-AA8C-47E7-ADDF-8063A0966EA3 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • Chrome (web)   • chrome                               • web-javascript • Google Chrome 90.0.4430.212

• No issues found!
```

</details>

**Comment by nt4f04uNd** [comment] 2021-05-14 15:32
> Expected results:  I expected the CustomScrollView on first page to be always scrollable

Why?

All SliverOverlapInjector does is that it adds additional extent to the view received from SliverOverlapAbsorber, i.e. just adds additional height to the view

I believe you are looking for setting `AppBar.floating = true` and `NestedScollView.floatHeaderSlivers = true` for your use case

**Comment by raulmabe** [comment] 2021-05-14 16:44
> Why?

Because I need to let the user overscroll to fetch more data. Anyway, what I expected doesn't really matter as I my intention is to inform about this behaviour not being consistent as it changes when the user changes between tabs _-i don't think this is expected-_.

> if you change tabs, the same scrollable body that stopped being scrollable now becomes scrollable.

**Comment by darshankawar** [comment] 2021-05-17 07:53
Below behavior is seen. The First tab isn't scrollable at first, but after coming from second tab, it starts scrolling.


https://user-images.githubusercontent.com/67046386/118451583-0a4cd080-b713-11eb-8ec2-ffba2ff2f7c7.mov


Keeping this open for further investigation.

<details>
<summary> code sample </summary>

```
[✓] Flutter (Channel stable, 2.0.6, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.0.6 at /Users/dhs/documents/fluttersdk/flutter
    • Framework revision 1d9032c7e1 (2 weeks ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (3 available)
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 90.0.4430.212

! Doctor found issues in 1 category.



```

</details>

**Comment by Piinks** [comment] 2021-06-04 18:30
Hi @raulmabe it looks like there is a lot of custom code here that may be causing your issue, are you able to reduce it down to a minimal reproduction of just the widgets causing the problem?

**Comment by darshankawar** [comment] 2021-07-09 12:16
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by darshankawar** 2021-07-09 12:16 UTC
Labels: f: scrolling, found in release: 2.0, framework, has reproducible steps, waiting for customer response
