### ISSUE TITLE
Content within a webview can appear to be outside of the flutter view when changing device orientation

### ISSUE THREAD

**Issue by robertjobin** [flutter/flutter#47471] opened 2019-12-19 18:28 UTC
## Steps to Reproduce
Launch a web view, preferably of a web page that has pictures or a solid color background that differs from the color palate of your app
Change device orientation from portrait to landscape
Observe the content of the web page appears outside of the container using flutter

**Target Platform:  iOS, Android**
**Target OS version/browser: iOS 13.3, Android 8.1.0**
**Devices: iPad Pro, Samsung Galaxy Tab A (2017)**

**Comment by iapicca** [comment] 2019-12-20 12:02
Hi @phoelapyae69 
can you please provide your updated  `flutter doctor -v`?
Thank you

**Comment by robertjobin** [comment] 2019-12-20 18:09
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.14.6 18G2022, locale en-US)
    • Flutter version 1.12.13+hotfix.5 at /Users/<username>/Library/flutter/1.12.13+hotfix.5-stable
    • Framework revision 27321ebbad (10 days ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/<username>/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.
[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.0, Build version 11A420a
    • CocoaPods version 1.7.5
[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

**Comment by darshankawar** [comment] 2020-07-02 09:48
Hi @robertjobin,
I tried to replicate this issue on an Android Tablet emulator (Pixel C, api 27) and opened [unsplash](https://unsplash.com/) website using `webview`. I was able to see the screen render properly after changing rotation from portrait to landscape and vice versa.

I am on latest Flutter dev channel (1.20.0-0.0.pre) and latest `webview_flutter` plugin.

Can you please confirm if you still experience this issue after upgrading Flutter and `webview` plugin ?

**Comment by TahaTesser** [comment] 2020-07-24 14:50
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

**Closed by TahaTesser** 2020-07-24 14:50 UTC
Labels: a: tablet, customer: amplify, p: first party, p: webview, plugin

**Comment by dannyvalentesonos** [comment] 2020-07-26 17:10
@TahaTesser This still occurs on iOS (testing with an iPad 7th gen) using Flutter 1.20. Can we please get it reopened?

I'm also attaching a video to show the issue. On Android, it does not occur, though I see other issues. I am attaching a video of that too. For Android, the issue is that it seems like sometimes the entire Flultter view is drawn twice while rotating. Doesn't happen on every rotate. The video captures just one rotate where this issue occurs.

Thanks

[bad_rotate_webview.zip](https://github.com/flutter/flutter/files/4977988/bad_rotate_webview.zip)


[✓] Flutter (Channel beta, 1.20.0-7.2.pre, on Mac OS X 10.15.5 19F101, locale en-US)
    • Flutter version 1.20.0-7.2.pre at /Users/danny.valente/Library/flutter/1.20.0-7.2.pre-beta
    • Framework revision a2bde82fbd (8 days ago), 2020-07-18 15:16:35 -0700
    • Engine revision 60b269d898
    • Dart version 2.9.0 (build 2.9.0-21.2.beta)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/danny.valente/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

**Comment by iapicca** [comment] 2020-07-27 06:18
Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by dannyvalentesonos** [comment] 2020-07-27 13:27
@iapicca Why do we need to open a new issue? The video I attached shows exactly this issue that the title describes perfectly. Maybe we can change this title to call out iOS specifically, but this bug's behavior, as described, is still present on iOS.
Thanks

**Comment by iapicca** [comment] 2020-07-27 14:15
Hi @dannyvalentesonos 
for once the issue is related to an obsolete flutter version and it appears to be inactive
moreover as you described your case seems to be specific to `ios` and `device specifivc`;

opening a new issue please provide 
your `flutter doctor -v`,
your `pubspec.yaml` and a minimal reproducible code sample.
Thank you

**Comment by dannyvalentesonos** [comment] 2020-07-30 02:03
I've created #62537
