### ISSUE TITLE
[Web] ListView freezes only on iOS.

### ISSUE THREAD

**Issue by ghost** [flutter/flutter#47825] opened 2019-12-26 15:50 UTC
I haven't tested on `macOS `so I'm not sure if it works on `macOS`.
I launched website and works fine on `Android `and `Windows `but on iOS, `ListView` freezes when scrolling normally/slowly.  
However, if I scrolling very fast to the end and go back to the top, I can scroll whole page without freeze. 
I think it happens because of `Image.asset` because it works without image.
How can I fix this?

**Flutter Doctor**

```
[√] Flutter (Channel beta, v1.12.13+hotfix.6, on Microsoft Windows [Version 10.0.17763.914], locale ja-JP)
    • Flutter version 1.12.13+hotfix.6 at C:\Users\yusak\Desktop\flutter
    • Framework revision 18cd7a3601 (2 weeks ago), 2019-12-11 06:35:39 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\yusak\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.41.1)
    • VS Code at C:\Users\yusak\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.7.1

[√] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 79.0.3945.88
    • Web Server • web-server • web-javascript • Flutter Tools
```

**Comment by iapicca** [comment] 2019-12-27 12:23
Hi @KodaiTakata 
can you please provide a minimal code sample to reproduce the problem?
Thank you

**Comment by KodaiTakata** [comment] 2019-12-28 13:05
`class DefaultText extends StatelessWidget {
  final String text;
  final double fontSize;
  final Color color;
  final FontWeight weight;
  final String font;
  DefaultText({@required this.text, @required this.fontSize, this.color, this.weight, this.font});
  @override
  Widget build(BuildContext context) {
    return Text(
      text,
      style: TextStyle(
        fontFamily: font,
        color: color ?? Colors.white,
        fontSize: fontSize,
        fontWeight: weight ?? FontWeight.normal,
      ),
    );
  }
}`

`class ImaegParagraph extends StatelessWidget {
  final double width;
  final double height;
  final EdgeInsetsGeometry padding;
  final String title;
  final double titleFontSize;
  final String imagePath;
  final String imageCaption;
  final VoidCallback onZoom;
  final VoidCallback onTap;
  final String description;
  final double descFontSize;
  ImaegParagraph(
      {@required this.width,
      @required this.height,
      @required this.padding,
      @required this.title,
      @required this.titleFontSize,
      @required this.imagePath,
      @required this.imageCaption,
      @required this.onZoom,
      @required this.onTap,
      @required this.description,
      @required this.descFontSize});
  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: padding,
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: <Widget>[
          DefaultText(
            color: Colors.black,
            text: title,
            fontSize: titleFontSize,
            weight: FontWeight.bold,
          ),
          const SizedBox(height: 25.0),
          Padding(
              padding: EdgeInsets.symmetric(horizontal: width * 0.1),
              child: Container(
                    width: double.infinity,
                    height: height / 3,
                  child: Image.asset(imagePath,
                      fit: BoxFit.cover))),
          Align(
            alignment: Alignment.bottomCenter,
            child: FlatButton(
              child: Text('Zoom an image',
                  style: const TextStyle(decoration: TextDecoration.underline)),
              onPressed: onZoom,
            ),
          ),
            Align(
              alignment: Alignment.bottomRight,
              child: Padding(
                padding: const EdgeInsets.only(top: 8.0, right: 8.0),
                child: FlatButton(
                  textColor: Colors.blue,
                  child: Text(
                    imageCaption ?? '',
                    style:
                        const TextStyle(decoration: TextDecoration.underline),
                  ),
                  onPressed: onTap,
                ),
              ),
            ),
          Padding(
            padding:
                const EdgeInsets.symmetric(horizontal: 16.0, vertical: 10.0),
            child: DefaultText(
              color: Colors.black,
              text: description,
              fontSize: descFontSize,
              weight: FontWeight.normal,
            ),
          ),
          const SizedBox(height: 20.0)
        ],
      ),
    );
  }
}`

`class TextParagraph extends StatelessWidget {
  final EdgeInsetsGeometry padding;
  final String title;
  final double titleFontSize;
  final String description;
  final double descFontSize;
  TextParagraph({
    @required this.padding, 
    @required this.title,
    @required this.titleFontSize,
    @required this.description,
    @required this.descFontSize
  });
  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: padding,
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: <Widget>[
          DefaultText(
            text: title,
            color: Colors.black,
            fontSize: titleFontSize,
            weight: FontWeight.bold,
          ),
          Padding(
            padding:  const EdgeInsets.symmetric(horizontal: 16.0, vertical: 20.0),
            child: DefaultText(
              text: description,
              color: Colors.black,
              fontSize: descFontSize,
              weight: FontWeight.normal,
            ),
          ),
        ],
      ),
    );
  }
}`

`class Freeze extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
return Scaffold(
     body: ListView(
       children: <Widget>[
          ImaegParagraph(
            width: width,
            height: height,
            padding: const EdgeInsets.symmetric(horizontal: 20.0, vertical: 20.0),
            title: 'Some title',
            titleFontSize: 25.0,
            imagePath: 'imagePath',
            imageCaption: 'Some caption',
            onZoom: () {},
            onTap: () {},
            description: 'long text here',
            descFontSize: 20.0,        
          ),
          ImaegParagraph(
            width: width,
            height: height,
            padding: const EdgeInsets.symmetric(horizontal: 20.0, vertical: 20.0),
            title: 'Some title',
            titleFontSize: 25.0,
            imagePath: 'imagePath',
            imageCaption: 'Some caption',
            onZoom: () {},
            onTap: () {},
            description: 'long text here',
            descFontSize: 20.0,        
          ),
          ImaegParagraph(
            width: width,
            height: height,
            padding: const EdgeInsets.symmetric(horizontal: 20.0, vertical: 20.0),
            title: 'Some title',
            titleFontSize: 25.0,
            imagePath: 'imagePath',
            imageCaption: 'Some caption',
            onZoom: () {},
            onTap: () {},
            description: 'long text here',
            descFontSize: 20.0,        
          ),
          TextParagraph(
            padding: const EdgeInsets.symmetric(horizontal: 20.0, vertical: 40.0),
            title: 'Some title',
            titleFontSize: 25.0,
            description: 'long text here',
            descFontSize: 20.0,
          )
       ],
     )
   );
  }
} `

**Comment by KodaiTakata** [comment] 2019-12-28 13:07
Sorry for late response.
Thank you for your help.

**Code** 

`class DefaultText extends StatelessWidget {
  final String text;
  final double fontSize;
  final Color color;
  final FontWeight weight;
  final String font;
  DefaultText(
      {@required this.text,
      @required this.fontSize,
      this.color,
      this.weight,
      this.font});
  @override
  Widget build(BuildContext context) {
    return Text(
      text,
      style: TextStyle(
        fontFamily: font,
        color: color ?? Colors.white,
        fontSize: fontSize,
        fontWeight: weight ?? FontWeight.normal,
      ),
    );
  }
}

class ImaegParagraph extends StatelessWidget {
  final double width;
  final double height;
  final EdgeInsetsGeometry padding;
  final String title;
  final double titleFontSize;
  final String imagePath;
  final String imageCaption;
  final VoidCallback onZoom;
  final VoidCallback onTap;
  final String description;
  final double descFontSize;
  ImaegParagraph(
      {@required this.width,
      @required this.height,
      @required this.padding,
      @required this.title,
      @required this.titleFontSize,
      @required this.imagePath,
      @required this.imageCaption,
      @required this.onZoom,
      @required this.onTap,
      @required this.description,
      @required this.descFontSize});
  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: padding,
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: <Widget>[
          DefaultText(
            color: Colors.black,
            text: title,
            fontSize: titleFontSize,
            weight: FontWeight.bold,
          ),
          const SizedBox(height: 25.0),
          Padding(
              padding: EdgeInsets.symmetric(horizontal: width * 0.1),
              child: Container(
                  width: double.infinity,
                  height: height / 3,
                  child: Image.asset(imagePath, fit: BoxFit.cover))),
          Align(
            alignment: Alignment.bottomCenter,
            child: FlatButton(
              child: Text('Zoom an image',
                  style: const TextStyle(decoration: TextDecoration.underline)),
              onPressed: onZoom,
            ),
          ),
          Align(
            alignment: Alignment.bottomRight,
            child: Padding(
              padding: const EdgeInsets.only(top: 8.0, right: 8.0),
              child: FlatButton(
                textColor: Colors.blue,
                child: Text(
                  imageCaption ?? '',
                  style: const TextStyle(decoration: TextDecoration.underline),
                ),
                onPressed: onTap,
              ),
            ),
          ),
          Padding(
            padding:
                const EdgeInsets.symmetric(horizontal: 16.0, vertical: 10.0),
            child: DefaultText(
              color: Colors.black,
              text: description,
              fontSize: descFontSize,
              weight: FontWeight.normal,
            ),
          ),
          const SizedBox(height: 20.0)
        ],
      ),
    );
  }
}

class TextParagraph extends StatelessWidget {
  final EdgeInsetsGeometry padding;
  final String title;
  final double titleFontSize;
  final String description;
  final double descFontSize;
  TextParagraph(
      {@required this.padding,
      @required this.title,
      @required this.titleFontSize,
      @required this.description,
      @required this.descFontSize});
  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: padding,
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: <Widget>[
          DefaultText(
            text: title,
            color: Colors.black,
            fontSize: titleFontSize,
            weight: FontWeight.bold,
          ),
          Padding(
            padding:
                const EdgeInsets.symmetric(horizontal: 16.0, vertical: 20.0),
            child: DefaultText(
              text: description,
              color: Colors.black,
              fontSize: descFontSize,
              weight: FontWeight.normal,
            ),
          ),
        ],
      ),
    );
  }
}

class Freeze extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: ListView(
      children: <Widget>[
        ImaegParagraph(
          width: width,
          height: height,
          padding: const EdgeInsets.symmetric(horizontal: 20.0, vertical: 20.0),
          title: 'Some title',
          titleFontSize: 25.0,
          imagePath: 'imagePath',
          imageCaption: 'Some caption',
          onZoom: () {},
          onTap: () {},
          description: 'long text here',
          descFontSize: 20.0,
        ),
        ImaegParagraph(
          width: width,
          height: height,
          padding: const EdgeInsets.symmetric(horizontal: 20.0, vertical: 20.0),
          title: 'Some title',
          titleFontSize: 25.0,
          imagePath: 'imagePath',
          imageCaption: 'Some caption',
          onZoom: () {},
          onTap: () {},
          description: 'long text here',
          descFontSize: 20.0,
        ),
        ImaegParagraph(
          width: width,
          height: height,
          padding: const EdgeInsets.symmetric(horizontal: 20.0, vertical: 20.0),
          title: 'Some title',
          titleFontSize: 25.0,
          imagePath: 'imagePath',
          imageCaption: 'Some caption',
          onZoom: () {},
          onTap: () {},
          description: 'long text here',
          descFontSize: 20.0,
        ),
        TextParagraph(
          padding: const EdgeInsets.symmetric(horizontal: 20.0, vertical: 40.0),
          title: 'Some title',
          titleFontSize: 25.0,
          description: 'long text here',
          descFontSize: 20.0,
        )
      ],
    ));
  }
}`

**Comment by yjbanov** [comment] 2020-01-03 22:46
Can you please try on the latest master channel? https://github.com/flutter/engine/pull/14378 was just submitted that probably fixes this.

/cc @dkwingsmt

**Comment by KodaiTakata** [comment] 2020-01-07 08:17
Sorry for late response. 
I just tried that on the master channel but still freeze:(

**Comment by KodaiTakata** [comment] 2020-01-07 13:40
Here is the [URL](https://daibaku-98319.firebaseapp.com/#/)
As you read through, view will freeze and you won't be able to scroll if you use iOS.

**Comment by yjbanov** [comment] 2020-01-09 23:10
Thanks for confirming. We'll take a look.

**Comment by yjbanov** [comment] 2020-01-09 23:11
Can you please keep that link alive so we can reproduce this? (or provide another stable link)

**Comment by KodaiTakata** [comment] 2020-01-14 10:35
Sorry again for late response.
I will keep that link, it's just demo site.
Thank you:)

**Comment by ferhatb** [comment] 2020-03-31 22:40
@ghost , can you please retry on latest master. We have fixed several issues that caused iOS crash due to images rendered in canvas elements.

**Comment by iapicca** [comment] 2020-05-29 13:52
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by iapicca** 2020-05-29 13:52 UTC
Labels: a: assets, a: images, e: web_html, f: scrolling, framework, platform-web, waiting for customer response
