### ISSUE TITLE
[Web] The Flutter Web fails to build the correct MaterialIcon.

### ISSUE THREAD

**Issue by YeomDongUk** [flutter/flutter#79020] opened 2021-03-25 05:26 UTC
I'm using Flutter 2.0.3 and dart 2.12.2 for web site.
the Icon data in Icon WIdget is different from web release build.

![스크린샷 2021-03-25 오후 2 23 59](https://user-images.githubusercontent.com/40842475/112423333-c2927400-8d75-11eb-9fa8-221e67e81f6d.png)

Icon Data

<img width="140" alt="스크린샷 2021-03-25 오후 2 25 55" src="https://user-images.githubusercontent.com/40842475/112423459-06857900-8d76-11eb-83e9-89176ddecdb3.png">

result

![스크린샷 2021-03-25 오후 2 23 12](https://user-images.githubusercontent.com/40842475/112423269-a5f63c00-8d75-11eb-913a-7e78704f4954.png)

result flutter doctor -v

**Comment by darshankawar** [comment] 2021-03-25 10:47
@YeomDongUk 
Tried a sample app with the said Icons and ran `flutter build web` and opened it in the browser, which showed the icons correctly, as below:

<img width="503" alt="Screenshot 2021-03-25 at 4 15 19 PM" src="https://user-images.githubusercontent.com/67046386/112460932-6f282200-8d85-11eb-81ec-010c62a2c08e.png">

```
return MaterialApp(
      home: Scaffold(
        body: Center(
          child: Column(
            children: [
              Icon(Icons.home),
              Icon(Icons.person),
              Icon(Icons.event),
              Icon(Icons.article)
            ],
          ),
        ),
      ),
    );
```

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.0.3, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.0.3 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 4d7946a68d (6 days ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.54.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (4 available)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 89.0.4389.90

! Doctor found issues in 1 category.

```

</details>

If above doesn't represent your case, provide a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that shows the issue you are facing.

**Comment by HansMuller** [comment] 2021-03-25 15:59
CC @guidezpl

**Comment by guidezpl** [comment] 2021-03-25 16:12
I wonder if there's an issue with the updating mechanism for artifacts.

Could you please provide the contents of the file `<path to flutter>/bin/cache/material_fonts.stamp`?

**Comment by YeomDongUk** [comment] 2021-03-26 05:11
`import 'package:flutter/material.dart';
import 'package:the_cal_flutter_web/style/custom_color.dart';

class CommonDrawer extends StatefulWidget {
  final void Function(int index) onButtonTap;
  final int initalPageIndex;
  CommonDrawer({
    Key? key,
    required this.onButtonTap,
    required this.initalPageIndex,
  }) : super(key: key);

  @override
  _CommonDrawerState createState() => _CommonDrawerState();
}

class _CommonDrawerState extends State<CommonDrawer> {
  late int _pageIndex;
  final datas = <Map<String, dynamic>>[
    {
      "icon": Icons.home,
      "text": "홈",
    },
    {
      "icon": Icons.person,
      "text": "회원관리",
    },
    {
      "icon": Icons.event,
      "text": "행사관리",
    },
    {
      "icon": Icons.article,
      "text": "자유게시판 관리",
    },
  ];

  @override
  void initState() {
    _pageIndex = widget.initalPageIndex;
    super.initState();
  }

  void onTap(int index) {
    if (index != _pageIndex) {
      widget.onButtonTap(index);
      setState(() => _pageIndex = index);
    }
  }

  @override
  Widget build(BuildContext context) {
    return Card(
      elevation: 6,
      child: Container(
        width: 150,
        child: ListView.separated(
          physics: ClampingScrollPhysics(),
          padding: EdgeInsets.all(12),
          separatorBuilder: (BuildContext context, int index) =>
              SizedBox(height: 12),
          itemCount: datas.length,
          itemBuilder: (context, index) => InkWell(
            borderRadius: BorderRadius.circular(20),
            onTap: () => onTap(index),
            child: Container(
              height: (MediaQuery.of(context).size.height - 174) / 8,
              child: AnimatedContainer(
                duration: Duration(milliseconds: 300),
                decoration: BoxDecoration(
                  color: index == _pageIndex
                      ? CustomColor.logo
                      : Colors.transparent,
                  borderRadius: BorderRadius.circular(20),
                ),
                child: Column(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: [
                    Icon(
                      datas[index]['icon'],
                      color: index == _pageIndex ? Colors.white : Colors.grey,
                      size: 40,
                    ),
                    SizedBox(height: 6),
                    Text(
                      datas[index]['text'],
                      style: TextStyle(
                        fontSize: 14,
                        color: index == _pageIndex ? Colors.white : Colors.grey,
                        fontWeight: FontWeight.bold,
                        fontFamily: 'HelveticaNeue',
                      ),
                    ),
                  ],
                ),
              ),
            ),
          ),
        ),
      ),
    );
  }
}
`

**Comment by YeomDongUk** [comment] 2021-03-26 05:12
<pre>
<code>
import 'package:flutter/material.dart';
import 'package:the_cal_flutter_web/style/custom_color.dart';

class CommonDrawer extends StatefulWidget {
  final void Function(int index) onButtonTap;
  final int initalPageIndex;
  CommonDrawer({
    Key? key,
    required this.onButtonTap,
    required this.initalPageIndex,
  }) : super(key: key);

  @override
  _CommonDrawerState createState() => _CommonDrawerState();
}

class _CommonDrawerState extends State<CommonDrawer> {
  late int _pageIndex;
  final datas = <Map<String, dynamic>>[
    {
      "icon": Icons.home,
      "text": "홈",
    },
    {
      "icon": Icons.person,
      "text": "회원관리",
    },
    {
      "icon": Icons.event,
      "text": "행사관리",
    },
    {
      "icon": Icons.article,
      "text": "자유게시판 관리",
    },
  ];

  @override
  void initState() {
    _pageIndex = widget.initalPageIndex;
    super.initState();
  }

  void onTap(int index) {
    if (index != _pageIndex) {
      widget.onButtonTap(index);
      setState(() => _pageIndex = index);
    }
  }

  @override
  Widget build(BuildContext context) {
    return Card(
      elevation: 6,
      child: Container(
        width: 150,
        child: ListView.separated(
          physics: ClampingScrollPhysics(),
          padding: EdgeInsets.all(12),
          separatorBuilder: (BuildContext context, int index) =>
              SizedBox(height: 12),
          itemCount: datas.length,
          itemBuilder: (context, index) => InkWell(
            borderRadius: BorderRadius.circular(20),
            onTap: () => onTap(index),
            child: Container(
              height: (MediaQuery.of(context).size.height - 174) / 8,
              child: AnimatedContainer(
                duration: Duration(milliseconds: 300),
                decoration: BoxDecoration(
                  color: index == _pageIndex
                      ? CustomColor.logo
                      : Colors.transparent,
                  borderRadius: BorderRadius.circular(20),
                ),
                child: Column(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: [
                    Icon(
                      datas[index]['icon'],
                      color: index == _pageIndex ? Colors.white : Colors.grey,
                      size: 40,
                    ),
                    SizedBox(height: 6),
                    Text(
                      datas[index]['text'],
                      style: TextStyle(
                        fontSize: 14,
                        color: index == _pageIndex ? Colors.white : Colors.grey,
                        fontWeight: FontWeight.bold,
                        fontFamily: 'HelveticaNeue',
                      ),
                    ),
                  ],
                ),
              ),
            ),
          ),
        ),
      ),
    );
  }
}

</code>
</pre>

this is my source
when i build release, i can't see result from web on desktop

**Comment by darshankawar** [comment] 2021-03-26 05:56
@YeomDongUk 
The code you provided seem to have custom widgets, so we can't directly use it and run to verify the issue. Please provide a complete reproducible code sample that we can directly copy paste and run to verify.

Also,  provide the requested details as below.


> I wonder if there's an issue with the updating mechanism for artifacts.
> 
> Could you please provide the contents of the file `<path to flutter>/bin/cache/material_fonts.stamp`?

**Comment by pedromassangocode** [comment] 2021-04-16 08:52
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by YeomDongUk** [comment] 2021-05-17 11:21
@guidezpl
Sorry too late. 
it is the content of file.
flutter_infra/flutter/fonts/1363603dd17dd609018e53cdbd5fef6791814337/fonts.zip

**Comment by guidezpl** [comment] 2021-05-17 11:39
Np. That is expected. I modified the sample slightly and was unable to reproduce the error


```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: CommonDrawer(),
    );
  }
}

class CommonDrawer extends StatefulWidget {

  final int initalPageIndex;
  CommonDrawer({
    Key? key,
     this.initalPageIndex = 1,
  }) : super(key: key);

  @override
  _CommonDrawerState createState() => _CommonDrawerState();
}

class _CommonDrawerState extends State {
  late int _pageIndex;
  final datas = [
    {
      "icon": Icons.home,
      "text": "홈",
    },
    {
      "icon": Icons.person,
      "text": "회원관리",
    },
    {
      "icon": Icons.event,
      "text": "행사관리",
    },
    {
      "icon": Icons.article,
      "text": "자유게시판 관리",
    },
  ];

  @override
  void initState() {
    _pageIndex = 1;
    super.initState();
  }

  void onTap(int index) {
    if (index != _pageIndex) {
      //widget.onButtonTap(index);
      setState(() => _pageIndex = index);
    }
  }

  @override
  Widget build(BuildContext context) {
    return Card(
      elevation: 6,
      child: Container(
        width: 150,
        child: ListView.separated(
          physics: ClampingScrollPhysics(),
          padding: EdgeInsets.all(12),
          separatorBuilder: (BuildContext context, int index) =>
              SizedBox(height: 12),
          itemCount: datas.length,
          itemBuilder: (context, index) => InkWell(
            borderRadius: BorderRadius.circular(20),
            onTap: () => onTap(index),
            child: Container(
              height: (MediaQuery.of(context).size.height - 174) / 8,
              child: AnimatedContainer(
                duration: Duration(milliseconds: 300),
                decoration: BoxDecoration(
                  color: index == _pageIndex
                      ? Colors.red
                      : Colors.transparent,
                  borderRadius: BorderRadius.circular(20),
                ),
                child: Column(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: [
                    Icon(
                      datas[index]['icon'] as IconData,
                      color: index == _pageIndex ? Colors.white : Colors.grey,
                      size: 40,
                    ),
                    SizedBox(height: 6),
                    Text(
                      datas[index]['text'] as String,
                      style: TextStyle(
                        fontSize: 14,
                        color: index == _pageIndex ? Colors.white : Colors.grey,
                        fontWeight: FontWeight.bold,
                        fontFamily: 'HelveticaNeue',
                      ),
                    ),
                  ],
                ),
              ),
            ),
          ),
        ),
      ),
    );
  }
}
```

<img width="863" alt="Screenshot 2021-05-17 at 13 38 07" src="https://user-images.githubusercontent.com/6655696/118482605-3ec18c00-b715-11eb-98e4-8787ac55f3ad.png">

**Comment by YeomDongUk** [comment] 2021-05-18 08:03
after pub cache repair, it is done. 
thx guys.

**Comment by guidezpl** [comment] 2021-05-18 11:39
Great!

**Closed by guidezpl** 2021-05-18 11:39 UTC
Labels: f: material design, framework, in triage
