### ISSUE TITLE
Android native view renders outside bounds

### ISSUE THREAD

**Issue by wanoghoco** [flutter/flutter#107332] opened 2022-07-08 23:57 UTC
Rendering CameraX API With AndroidView in flutter cause the app to render the native widget ontop of the flutter app, the new widget covers the flutter debug banner, even in a stack, column, expanded widget, no other widget is shown on the UI because it will be covered by the native native widget. this issue occurs when CameraX is loaded fully

Flutter team please look to this issue. I thought it would have been fixed with the current update but it wasn't. Please help me with this issue 

The project: https://github.com/wanoghoco/camerapreview

**Comment by Tom3652** [comment] 2022-07-10 08:36
I have made the same issue #106798 using CameraX, this is a serious bug with `PlatformViews`.

**Comment by maheshmnj** [comment] 2022-07-11 07:01
Hi @wanoghoco, Thanks for filing the issue. There has been a major change in platform views in flutter 3 which broke many plugins which depend on Platformviews.
A recent fix was made  https://github.com/flutter/flutter/issues/103630 but looks like it doesn't seem to address all the nuts and bolts a new bug has been raised to track this https://github.com/flutter/flutter/issues/107313 which I believe will resolve the issue.

Closing as duplicate of the above-linked issue.

**Closed by maheshmnj** 2022-07-11 07:01 UTC
Labels: in triage
