### ISSUE TITLE
NullPointerException crashes under RenderMode of rendermode.texture

### ISSUE THREAD

**Issue by louyaming** [flutter/flutter#56962] opened 2020-05-12 02:29 UTC
From URL: https://www.flutterchina.club/faq.md

Crashes occur with the latest stable version  1.17.0，the log is :
java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.embedding.engine.renderer.RenderSurface.attachToRenderer(io.flutter.embedding.engine.renderer.FlutterRenderer)' on a null object reference.

tips:
RenderMode.surface is normal,and  rendermode.texture is bad

**Comment by TahaTesser** [comment] 2020-05-12 12:09
Hi @louyaming 
can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by louyaming** [comment] 2020-05-13 01:27
> Hi @louyaming
> can you please provide your `flutter doctor -v` and `flutter run --verbose`?
> Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
> Thank you
1.The result of executing the command  `flutter doctor -v` as bellow:
 `[√] Flutter (Channel stable, v1.17.0, on Microsoft Windows [Version 10.0.18363.778], locale zh-CN)
    • Flutter version 1.17.0 at E:\software\work\flutter
    • Framework revision e6b34c2b5c (10 days ago), 2020-05-02 11:39:18 -0700
    • Engine revision 540786dd51
    • Dart version 2.8.1


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at E:\AppData\Local\Android\Sdk
    • Platform android-R, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] Connected device (1 available)
    • NX531J • a753faff • android-arm64 • Android 6.0.1 (API 23)

• No issues found!`. 
In addition, my code is good at 1.12.3, but upgrading to 1.17.0 is problematic。
2.My code as ：
`FlutterFragment flutterFragment = FlutterFragment.withCachedEngine("my_engine_id")
    .renderMode(FlutterView.RenderMode.texture)
    .build();`

3. The crash log is:
`Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.embedding.engine.renderer.RenderSurface.attachToRenderer(io.flutter.embedding.engine.renderer.FlutterRenderer)' on a null object reference
        at io.flutter.embedding.android.FlutterView.attachToFlutterEngine(FlutterView.java:699)
        at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onCreateView(FlutterActivityAndFragmentDelegate.java:290)
        at io.flutter.embedding.android.FlutterFragment.onCreateView(FlutterFragment.java:585)
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2698)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:320)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1187)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1356)
        at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1434)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1497)
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:447)
        at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2169)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1992)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1947)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1849)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2629)
        at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2577)
        at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:247)
        at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:541)
        at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:201)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1330)
        at android.app.Activity.performStart(Activity.java:6367)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2579)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2676) 
        at android.app.ActivityThread.access$900(ActivityThread.java:173) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1436) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:171) 
        at android.app.ActivityThread.main(ActivityThread.java:5760) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:622) `

**Comment by TahaTesser** [comment] 2020-05-13 09:49
Not able to reproduce this issue due to other issues complications in the code
but i see there is PR so i am gonna label it

**Comment by LiGe888** [comment] 2020-06-16 06:49
1.19 is fine,1.17  class FlutterView  line 275 is wrong
 this.flutterTextureView = flutterTextureView;
    this.renderSurface = flutterTextureView;  (1.19 is ok)

**Comment by jmagman** [comment] 2020-06-23 18:17
Duplicate of https://github.com/flutter/flutter/issues/56125.  Fixed in 1.18.0-dev.0.0, which is available on the beta channel.

**Closed by jmagman** 2020-06-23 18:17 UTC
Labels: a: existing-apps, engine, platform-android

**Comment by HappyGhostz** [comment] 2020-07-31 09:51
available on the Stable(v1.17.5) channel?

**Comment by jmagman** [comment] 2020-07-31 17:14
@HappyGhostz No, it's available on the [beta channel](https://flutter.dev/docs/development/tools/sdk/releases?tab=macos) in 1.18.0-dev.0.0.
