### ISSUE TITLE
Camera no longer builds for Android release using Flutter Master channel

### ISSUE THREAD

**Issue by snevetssirk** [flutter/flutter#44368] opened 2019-11-07 20:20 UTC
Using the most recent camera widget, I can build debug and profile binaries for Android but trying to build for release produces this error:

A problem occurred configuring root project 'camera'.
         This warning prints for all Android build failures. The real root cause of the error may be unrelated.
> SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.

If I downgrade flutter to the DEV channel, or to STABLE, I can build release binaries.

However, we're testing memory improvements that come with the MASTER channel and I just can't make that build work.

Seems probable it's related to Android X but can't be sure.

**Comment by snevetssirk** [comment] 2019-11-07 21:13
Further to my report, it does build if you have the ANDROID_HOME environment variable set, but it never needed it before. So while this is by no means a blocker, it's going to generate reports, I suspect.

**Comment by iapicca** [comment] 2019-11-11 08:01
Hi @snevetssirk 
could you please provide a self contained app on github
or the steps to reproduce the issue?
Thank you

**Comment by iapicca** [comment] 2019-12-04 14:14
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.

**Closed by iapicca** 2019-12-04 14:14 UTC
Labels: p: camera, p: first party, plugin, severe: crash, waiting for customer response

**Comment by chaochaox1990** [comment] 2020-04-01 05:50
Hi I have the same issue 
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'camera'.
> SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s


The plugin camera could not be built due to the issue above.
admindeMacBook-Pro-3:install_master limi$ flutter doctor -v
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.14.6 18G103, locale zh-Hans-CN)
    • Flutter version 1.12.13+hotfix.5 at /Users/limi/Downloads/flutter
    • Framework revision 27321ebbad (4 months ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/limi/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.7.5

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] Connected device (1 available)
    • LLD AL30 • 6SJNW18530001994 • android-arm64 • Android 9 (API 28)

this happened when I run flutter run --release 

Could u pls help me check about this.
