### ISSUE TITLE
Flutter app getting stucked on blank screen when a new activity is launched from lock screen automatically.

### ISSUE THREAD

**Issue by deensquare** [flutter/flutter#48676] opened 2020-01-12 13:56 UTC
I am trying to respond to an fcm data message in onmessagereceived of the firebasemessagingservice class by launching a new activity. the application works perfectly in foreground and even background when the phone is unlocked but gets stuck on blank screen when the activity is launched from lock screen. any suggestions will be appreciated.

**Comment by iapicca** [comment] 2020-01-13 08:30
Hi @deensquare 
for what I can see the issue is related to a FlutterFire plugin,
please open the issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
thank you

**Closed by iapicca** 2020-01-13 08:30 UTC

**Comment by priezz** [comment] 2020-01-30 13:41
Could be related to #43373. If it is, here is the fix #48983 (not merged though).
