### ISSUE TITLE
 The application works in debug mode but in relese mode it has firabse_core errors

### ISSUE THREAD

**Issue by foxnabla** [flutter/flutter#68707] opened 2020-10-21 13:03 UTC
I have an application that works in debug mode, but it doesn't work in relese mode. After updating flutter and gadle I got errors associated with firabase_core. I have changed the firebase versions in the pubspec_yaml file but it still doesn't work. Does anyone know what could happen?

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':generateReleaseRFile'.
> Could not resolve all files for configuration ':releaseRuntimeClasspath'.
   > Could not find com.google.firebase:firebase-bom:25.3.1.
     Searched in the following locations:
       - https://storage.googleapis.com/download.flutter.io/com/google/firebase/firebase-bom/25.3.1/firebase-bom-25.3.1.pom
       - https://storage.googleapis.com/download.flutter.io/com/google/firebase/firebase-bom/25.3.1/firebase-bom-25.3.1.jar
     Required by:
         project :
   > Could not find com.google.firebase:firebase-core:.
     Required by:
         project :
   > Could not find androidx.annotation:annotation:1.1.0.
     Searched in the following locations:
       - https://storage.googleapis.com/download.flutter.io/androidx/annotation/annotation/1.1.0/annotation-1.1.0.pom
       - https://storage.googleapis.com/download.flutter.io/androidx/annotation/annotation/1.1.0/annotation-1.1.0.jar
     Required by:
         project :

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':javaPreCompileRelease'.
> Could not resolve all files for configuration ':releaseCompileClasspath'.
   > Could not find com.google.firebase:firebase-bom:25.3.1.
     Required by:
         project :
   > Could not find com.google.firebase:firebase-core:.
     Required by:
         project :
   > Could not find androidx.annotation:annotation:1.1.0.
     Required by:
         project :

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 4s

------------------------------------------------------------------------------------------

pubspec.yaml

cupertino_icons: ^0.1.2
  firebase_dynamic_links:
  firebase_analytics: ^5.0.15
  firebase_messaging: 
  image: 
  http: 
  rxdart: 
  shared_preferences: 
  url_launcher: ^5.5.0
  image_picker: 
  mime_type: 
  http_parser: 
  random_color: 
  compressimage: 
  flutter_html: 
  soundpool: ^1.1.1   
  badges:  
  sqflite: 
  flutter_swiper: 
  curved_navigation_bar: 
  exif: 
  path_provider: 
  cached_network_image:
  animate_do: 
  font_awesome_flutter: ^8.8.1
  no_context_navigation: ^1.0.2
  liquid_swipe: ^1.5.0
  flutter_svg: ^0.18.1
  share: ^0.6.5+3
  provider: ^4.0.4
  toast: ^0.1.5
  webview_flutter: ^1.0.3
  fl_chart: ^0.12.0

FLUTTER DOCTOR

$ flutter doctor -v
[√] Flutter (Channel stable, 1.22.0, on Microsoft Windows [Version 10.0.19041.572], locale es-419)
    • Flutter version 1.22.0 at C:\src\flutter
    • Framework revision d408d302e2 (3 weeks ago), 2020-09-29 11:49:17 -0700
    • Engine revision 5babba6c4d
    • Dart version 2.10.0

 
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0-rc1)
    • Android SDK at C:\Users\Matias\Android\sdk
    • Platform android-29, build-tools 30.0.0-rc1
    • ANDROID_HOME = C:\Users\Matias\Android\sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 44.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.50.1)
    • VS Code at C:\Users\Matias\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.15.1

[√] Connected device (1 available)
    • Mi A2 (mobile) • 30a0ded • android-arm64 • Android 10 (API 29)

• No issues found!

**Comment by pedromassangocode** [comment] 2020-10-21 13:58
Hi @foxnabla 
From what I can see, the issue is related to a FlutterFire plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by pedromassangocode** 2020-10-21 13:58 UTC
Labels: team: infra
