### ISSUE TITLE
Linux Host Engine is 15% flaky on step `test: Host Tests for host_release`

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#106590] opened 2022-06-25 00:14 UTC
There are [15 post-submit flakes](https://data.corp.google.com/sites/dash_infra_metrics_datasite/flutter_check_test_flakiness_status_dashboard/?p=BUILDER_NAME:%22Linux%20Host%20Engine%22&p=LIMIT:100) in recent 100 runs. (Seems same as https://github.com/flutter/flutter/issues/106589, but just in case any new issues exist. Feel free to dup.)

Example flaky builds:
https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20Host%20Engine/16512/overview
https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20Host%20Engine/16510/overview
https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20Host%20Engine/16507/overview

Error logs:
```
[206/208] EmbedderTestGlVk/EmbedderTestMultiBackend.CompositorMustBeAbleToRenderKnownScenePixelRatioOnSurface/0 (412 ms)
[207/208] EmbedderTestGlVk/EmbedderTestMultiBackend.PlatformViewMutatorsAreValid/1 (148 ms)
[208/208] EmbedderA11yTest.A11yTreeIsConsistent (120073 ms)
[INFO:test_timeout_listener.cc(76)] Test timeout of 120 seconds per test case will be enforced.
[0;33mNote: Google Test filter = EmbedderA11yTest.A11yTreeIsConsistent
[m[0;32m[==========] [mRunning 1 test from 1 test suite.
[0;32m[----------] [mGlobal test environment set-up.
[0;32m[----------] [m1 test from EmbedderA11yTest
[0;32m[ RUN      ] [mEmbedderA11yTest.A11yTreeIsConsistent
[FATAL:flutter/testing/test_timeout_listener.cc(45)] Check failed: delay < timeout_. Test EmbedderA11yTest.A11yTreeIsConsistent did not complete in 120 seconds and is assumed to be hung. Killing the test harness.
[ERROR:flutter/fml/backtrace.cc(116)] Caught signal SIGABRT during program execution.
Frame 0: 0x7fe5c823c7f1 abort
Frame 1: 0x56108f6f1806 Unknown
Frame 2: 0x56108f6f17fc Unknown
Frame 3: 0x56108f501160 flutter::testing::PendingTests::CheckTimedOutTests()
Frame 4: 0x56108f50100b std::__1::__function::__func<>::operator()()
Frame 5: 0x56108f6f2a5d fml::MessageLoopImpl::FlushTasks()
Frame 6: 0x56108f6f9df6 fml::MessageLoopLinux::Run()
Frame 7: 0x56108f6f2911 fml::MessageLoopImpl::DoRun()
Frame 8: 0x56108f6f8bb7 std::__1::__thread_proxy<>()
Frame 9: 0x7fe5c89926db start_thread
Frame 10: 0x7fe5c831d61f __clone

[208/208] EmbedderA11yTest.A11yTreeIsConsistent returned/aborted with exit code -6 (120073 ms)
FAILED TESTS (1/208):
  120073 ms: /b/s/w/ir/cache/builder/src/out/host_release/exe.unstripped/embedder_unittests EmbedderA11yTest.A11yTreeIsConsistent (try #2)
SUMMARY:
  /b/s/w/ir/cache/builder/src/out/host_release/exe.unstripped/embedder_unittests EmbedderA11yTest.A11yTreeIsConsistent passed 1 / 2 times.


!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!


Failed Command:

python3 /b/s/w/ir/cache/builder/src/third_party/gtest-parallel/gtest-parallel /b/s/w/ir/cache/builder/src/out/host_release/exe.unstripped/embedder_unittests --repeat=2

Exit Code: 250



!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!


Traceback (most recent call last):
  File "/b/s/w/ir/cache/builder/src/flutter/testing/run_tests.py", line 1071, in <module>
    sys.exit(main())
  File "/b/s/w/ir/cache/builder/src/flutter/testing/run_tests.py", line 1021, in main
    build_dir, engine_filter, args.coverage, args.engine_capture_core_dump
  File "/b/s/w/ir/cache/builder/src/flutter/testing/run_tests.py", line 397, in RunCCTests
    gtest=True
  File "/b/s/w/ir/cache/builder/src/flutter/testing/run_tests.py", line 225, in RunEngineExecutable
    env=env
  File "/b/s/w/ir/cache/builder/src/flutter/testing/run_tests.py", line 80, in RunCmd
    (command_string, process.returncode)
Exception: Command "python3 /b/s/w/ir/cache/builder/src/third_party/gtest-parallel/gtest-parallel /b/s/w/ir/cache/builder/src/out/host_release/exe.unstripped/embedder_unittests --repeat=2" exited with code 250.
```

**Comment by zanderso** [comment] 2022-06-25 01:05
Same question. About what commit did these start happening, and please confirm that test failures notify the sheriff.

**Comment by chinmaygarde** [comment] 2022-06-27 17:32
Marking this as a duplicate of https://github.com/flutter/flutter/issues/106589

**Closed by chinmaygarde** 2022-06-27 17:32 UTC
Labels: engine, P1, severe: flake
