### ISSUE TITLE
run  flutter build ios-framework is  FAILED

### ISSUE THREAD

**Issue by L-X-J** [flutter/flutter#106476] opened 2022-06-23 09:58 UTC
## flutter --version
```log
Flutter 3.0.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision cd41fdd495 (2 weeks ago) • 2022-06-08 09:52:13 -0700
Engine • revision f15f824b57
Tools • Dart 2.17.3 • DevTools 2.12.2
```

## Steps to Reproduce

run command ` flutter build ios-framework  --output=framework-out`

## Logs
<details>
<summary>
Unable to build plugin frameworks for simulator: 2022-06-23 17:23:40.446 xcodebuild[74220:13798814] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionSentinelHostApplications for extension
Xcode.DebuggerFoundation.AppExtensionHosts.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
2022-06-23 17:23:40.449 xcodebuild[74220:13798814] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionPointIdentifierToBundleIdentifier for extension
Xcode.DebuggerFoundation.AppExtensionToBundleIdentifierMap.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
</summary>

```log
💪 Building with sound null safety 💪

Building frameworks for ph.xwifi.flutter.plugin in debug mode...
 ├─Copying Flutter.xcframework...                                  228ms
 ├─Building App.xcframework...                                      5.2s
 ├─Building plugins...                                              9.7s
Unable to build plugin frameworks for simulator: 2022-06-23 17:23:40.446 xcodebuild[74220:13798814] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionSentinelHostApplications for extension
Xcode.DebuggerFoundation.AppExtensionHosts.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
2022-06-23 17:23:40.449 xcodebuild[74220:13798814] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionPointIdentifierToBundleIdentifier for extension
Xcode.DebuggerFoundation.AppExtensionToBundleIdentifierMap.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
** BUILD FAILED **


The following build commands failed:
        Ld /Users/chenxinlei/BehemothCloud-Projects/x_wifi_flutter/xwifi-ios-framework/Debug/iphonesimulator/Debug-iphonesimulator/flutter_scankit/flutter_scankit.framework/flutter_scankit normal (in target 'flutter_scankit' from project
        'Pods')
(1 failure)
```

```
[✓] Flutter (Channel stable, 3.0.2, on macOS 12.4 21F79 darwin-arm, locale
    zh-Hans-CN)
    • Flutter version 3.0.2 at /Users/chenxinlei/flutter-home
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cd41fdd495 (2 weeks ago), 2022-06-08 09:52:13 -0700
    • Engine revision f15f824b57
    • Dart version 2.17.3
    • DevTools version 2.12.2

[!] Android toolchain - develop for Android devices (Android SDK version
    33.0.0-rc2)
    • Android SDK at /Users/chenxinlei/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc2
    • ANDROID_HOME = /Users/chenxinlei/Library/Android/sdk
    ✗ Android SDK file not found:
      /Users/chenxinlei/Library/Android/sdk/build-tools/33.0.0-rc2/aapt.
    • Try re-installing or updating your Android SDK,
      visit https://flutter.dev/docs/get-started/install/macos#android-setup for
      detailed instructions.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.2)
    • IntelliJ at /Users/chenxinlei/Applications/JetBrains Toolbox/IntelliJ IDEA
      Ultimate.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.2)
    • IntelliJ at /Users/chenxinlei/Library/Application
      Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/213.6777.52/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.68.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (4 available)
    • Redmi K30 (mobile) • adb-ff24b668-azqupx._adb-tls-connect._tcp. •
      android-arm64  • Android 11 (API 30)
    • iPhone (mobile)    • bf303b4ca45b70ed917a3e355a3f079113786da0   • ios
      • iOS 14.8.1 18H107
    • macOS (desktop)    • macos                                      •
      darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)       • chrome                                     •
      web-javascript • Google Chrome 102.0.5005.115

[✓] HTTP Host Availability
    • All required HTTP hosts are available
```

</details>

`flutter_scankit` is only run in arm64 ,I don't know if it has any effect. I run command ` flutter run ` to iOS device a success,but run command `flutter build ios-framework  --output=framework-out` is failed

**Comment by huycozy** [comment] 2022-06-23 11:48
Hi @L-X-J 
From what I can see, the issue is related to a 3rd party plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/arcticfox1919/flutter-scankit).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments, providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`, a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that does not use 3rd party plugins and I will reopen it.
Thank you!

**Closed by huycozy** 2022-06-23 11:48 UTC
Labels: in triage

**Comment by L-X-J** [comment] 2022-06-24 01:47
Hi @huycozy 
My current projects  is flutter module project. I hava a question.  I run a  command `flutter run ` can success, but i run `flutter build ios-framework --output=framework-out ` is failed,I want to know the difference between the two commands.
<details>
<summary>
flutter doctor -v
</summary>

```
[✓] Flutter (Channel stable, 3.0.2, on macOS 12.4 21F79 darwin-arm, locale
    zh-Hans-CN)
    • Flutter version 3.0.2 at /Users/chenxinlei/flutter-home
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cd41fdd495 (2 weeks ago), 2022-06-08 09:52:13 -0700
    • Engine revision f15f824b57
    • Dart version 2.17.3
    • DevTools version 2.12.2

[!] Android toolchain - develop for Android devices (Android SDK version
    33.0.0-rc2)
    • Android SDK at /Users/chenxinlei/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc2
    • ANDROID_HOME = /Users/chenxinlei/Library/Android/sdk
    ✗ Android SDK file not found:
      /Users/chenxinlei/Library/Android/sdk/build-tools/33.0.0-rc2/aapt.
    • Try re-installing or updating your Android SDK,
      visit https://flutter.dev/docs/get-started/install/macos#android-setup for
      detailed instructions.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.2)
    • IntelliJ at /Users/chenxinlei/Applications/JetBrains Toolbox/IntelliJ IDEA
      Ultimate.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.2)
    • IntelliJ at /Users/chenxinlei/Library/Application
      Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/213.6777.52/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.68.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (4 available)
    • rk3288 (mobile) • LYAX3Z7F6BROXZQ5H5G1743                  • android-arm
      • Android 7.1.2 (API 25)
    • iPhone (mobile) • bf303b4ca45b70ed917a3e355a3f079113786da0 • ios
      • iOS 14.8.1 18H107
    • macOS (desktop) • macos                                    • darwin-arm64
      • macOS 12.4 21F79 darwin-arm
    • Chrome (web)    • chrome                                   •
      web-javascript • Google Chrome 102.0.5005.115

[✓] HTTP Host Availability
    • All required HTTP hosts are available
! Doctor found issues in 1 category.
```
</details>

##  `flutter run -v` 
Because there are too many output contents, I uploaded the output contents to AWS S3
[flutter run -v out.log](https://xpower-bucket-open.s3.ap-southeast-1.amazonaws.com/public/test/flutter+run+-v+out.log)

<details>
<summary>
my pubspec.yaml
</summary>

```log
name: flutter_module
description: X-Wifi.Flutter 模块

version: 0.0.3+1

environment:
  sdk: ">=2.16.2 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # GetX
  # https://github.com/jonataslaw/getx/blob/master/README.zh-cn.md
  get: ^4.6.1
  # 屏幕适配
  # https://github.com/OpenFlutter/flutter_screenutil/blob/master/README_CN.md
  flutter_screenutil: ^5.5.2
  # 轮播图
  # https://pub.dev/packages/card_swiper
  card_swiper : ^2.0.1
  # 组件库
  # https://pub.flutter-io.cn/packages/bruno/versions
  bruno : ^2.2.0
  # 网络请求
  # https://pub.dev/packages/retrofit
  retrofit: '>=3.0.0 <4.0.0'

  # 拍照 选取相册
  #https://pub.dev/packages/image_picker
  image_picker: ^0.8.5+3
  # 二维码扫描
  # https://pub.dev/packages/flutter_barcode_scanner
  #  flutter_barcode_scanner: ^2.0.0
  # 日志
  # https://pub.dev/packages/logger
  logger: any
  # 下拉刷新上拉加载
  # https://pub.dev/packages/flutter_easyrefresh
  flutter_easyrefresh: 2.2.1

  #华为二维码
  #https://pub.dev/packages/huawei_scan
#  huawei_scan: ^2.1.0+300
  # 华为统一扫码 魔改自https://pub.dev/packages/huawei_scan
  flutter_scankit:
    git:
      url: https://github.com/arcticfox1919/flutter-scankit

  #判断权限
  #https://pub.dev/packages/permission_handler/install
  permission_handler: ^10.0.0

  # app设置
  # https://pub.dev/packages/app_settings
  app_settings: 4.1.6

  decimal: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  # 网络请求
  # https://pub.dev/packages/retrofit
  retrofit_generator: '>=4.0.0 <5.0.0'
  build_runner: ^2.1.10
  json_serializable: '>4.4.0'
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - lib/res/images/

  # To add Flutter specific custom fonts to your application, add a fonts
  # section here, in this "flutter" section. Each entry in this list should
  # have a "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

  module:
    androidX: true
    androidPackage: ph.xwifi.flutter.plugin
    iosBundleIdentifier: ph.xwifi.flutter.plugin

```
</details>
