### ISSUE TITLE
Firebase crash on permission

### ISSUE THREAD

**Issue by NikosTsesmelis** [flutter/flutter#110766] opened 2022-09-01 08:23 UTC
I am using permission_handler: 10.0.0 to request a location permission like this.

`PermissionStatus status = await Permission.location.status;`

And somehow the firebase plugin crashes the app when I accept.

Working versions:
cloud_firestore: 3.3.0
firebase_core: 1.19.2
firebase_messaging: 12.0.0

Crashing versions:
cloud_firestore: 3.4.6
firebase_core: 1.21.1
firebase_messaging: 13.0.0

Error message

```
E/AndroidRuntime( 8410): java.lang.AssertionError
E/AndroidRuntime( 8410): 	at io.flutter.plugins.firebase.messaging.FlutterFirebasePermissionManager.onRequestPermissionsResult(FlutterFirebasePermissionManager.java:33)
E/AndroidRuntime( 8410): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onRequestPermissionsResult(FlutterEngineConnectionRegistry.java:777)
E/AndroidRuntime( 8410): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onRequestPermissionsResult(FlutterEngineConnectionRegistry.java:409)
E/AndroidRuntime( 8410): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onRequestPermissionsResult(FlutterActivityAndFragmentDelegate.java:757)
E/AndroidRuntime( 8410): 	at io.flutter.embedding.android.FlutterActivity.onRequestPermissionsResult(FlutterActivity.java:748)
E/AndroidRuntime( 8410): 	at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:8264)
E/AndroidRuntime( 8410): 	at android.app.Activity.dispatchActivityResult(Activity.java:8114)
E/AndroidRuntime( 8410): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4866)
E/AndroidRuntime( 8410): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4914)
E/AndroidRuntime( 8410): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
```

**Comment by darshankawar** [comment] 2022-09-01 08:34
Closing this as duplicate of https://github.com/firebase/flutterfire/issues/9430

**Closed by darshankawar** 2022-09-01 08:34 UTC
Labels: in triage
