### ISSUE TITLE
[cloud_firestore] Add MetadataChanges to documentReference.snapshot()

### ISSUE THREAD

**Issue by basketball-ico** [flutter/flutter#37007] opened 2019-07-26 10:47 UTC
I want to use MetadataChanges like in [Android](https://firebase.google.com/docs/reference/android/com/google/firebase/firestore/DocumentReference)

**Comment by collinjackson** [comment] 2019-08-01 18:34
I believe that this is a duplicate of flutter/flutter#16432 and it was fixed in https://github.com/flutter/plugins/pull/1918. Please let me know if I'm mistaken

**Closed by collinjackson** 2019-08-01 18:34 UTC
Labels: p: cloud_firestore, plugin, severe: new feature

**Comment by kroikie** [comment] 2019-10-13 19:53
@basketball-ico

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1210. Any further collaboration will be done there.
