### ISSUE TITLE
`flutter run` process doesn't terminate after closing app when run in release mode on Windows

### ISSUE THREAD

**Issue by DanTup** [flutter/flutter#135019] opened 2023-09-19 13:18 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

- use `flutter create` to create an app
- run the app with `flutter run --release -d windows`
- close the application window after it launches

### Expected results

The `flutter` process in the terminal should exit when the app was closed.

### Actual results

The `flutter` process remains active in the terminal.

### Code sample

Any project works, including the `flutter create` sample.

### Screenshots or Video

https://github.com/flutter/flutter/assets/1078012/ef066fb3-3a67-4bf9-98f8-c8e2d24719f6

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
PS C:\Dev\Test Projects\flutter_counter> flutter doctor -v
[!] Flutter (Channel master, 3.14.0-14.0.pre.341, on Microsoft Windows [Version 10.0.22621.2283], locale en-GB)
    • Flutter version 3.14.0-14.0.pre.341 on channel master at C:\Dev\Google\flutter
    ! Warning: `dart` on your path resolves to C:\Dev\Tools\Dart\Stable\bin\dart.exe, which is not inside your current Flutter SDK checkout at
      C:\Dev\Google\flutter. Consider adding C:\Dev\Google\flutter\bin to the front of your path.
    • Upstream repository git@github.com:DanTup/flutter.git
    • FLUTTER_GIT_URL = git@github.com:DanTup/flutter.git
    • Framework revision 2337c64d0c (26 hours ago), 2023-09-18 13:13:37 +0200
    • Engine revision 4107ee0dc8
    • Dart version 3.2.0 (build 3.2.0-173.0.dev)
    • DevTools version 2.28.0-dev.8
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and
      upgrades.

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\danny\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.6.5)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.6.33829.357
    • Windows 10 SDK version 10.0.22000.0

[✓] Android Studio (version 2022.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)

[✓] VS Code (version 1.82.2)
    • VS Code at C:\Users\danny\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.73.20230904

[✓] VS Code (version 1.83.0-insider)
    • VS Code at C:\Users\danny\AppData\Local\Programs\Microsoft VS Code Insiders
    • Flutter extension version 3.73.20230904

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22621.2283]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 116.0.5845.188
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 116.0.1938.62

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

**Comment by stuartmorgan** [comment] 2023-09-19 18:36
Duplicate of https://github.com/flutter/flutter/issues/58459

**Closed by stuartmorgan** 2023-09-19 18:36 UTC
