### ISSUE TITLE
On Android after opening and closing virtual keyboard once, the RawKeyboard stops sending RawKeyDownEvent for listeners

### ISSUE THREAD

**Issue by megamonster21099** [flutter/flutter#71894] opened 2020-12-08 05:49 UTC
Issue happens when developing apps for using the remote controller (Android TV or Tv Box).
When the virtual keyboard is opened once in the app, the sysctem stops sending Down events for RawKeyboard listeners. Only Up events trigger.
Tested on tv boxes with API25, API29, Android emulator API30.
![image](https://user-images.githubusercontent.com/31510777/101443654-a41f7e80-3926-11eb-9cc2-6c297bb8dea7.png)

### **Steps to reproduce:**
_Note! For somebody who do not have remote controller - you can generate key press by adb command` adb shell input keyevent <code>`, where UP=19, DOWN=20, ENTER=23. 
If you're using emulator - just use the PC keyboard UP and Down arrows.
We tested with real remote controllers._

1. Run the code below. See that "Button Top" has a focus.

2. Press "Down". See that "Button Middle" has a focus.
   Output:
```
   Handle key Down event 20
   Handle key Up event 20
```
   Result: _handleRawKeyEvent receives both events. Works as expected

3. Press "Down" again. See that "Button Bottom" has a focus.
   Output:
```
   Handle key Down event 20
   Handle key Up event 20
```
   Result: _handleRawKeyEvent receives both events. Still works as expected

3. Press "Down" again. See that Textfield has a focus, virtual keyboard opened.
   Output:
```
   Handle key Down event 20
   Handle key Up event 20
```
   Result: _handleRawKeyEvent receives both events. Still works as expected

4. Close keyboard with "Back" button. Keyboard closed, but textfield still has a focus.

5. Press button "Request focus to Button Top". See that "Button Top" has a focus.

6. Press "Down" again. See that nothing happens
   Output:
```
   Handle key Up event 20
```
   Result: _handleRawKeyEvent receives only Up events.

7. Try to click with mouse different buttons, try to press Left, Right or any other buttons, nothing helps. The RawKeyboard listener  will never receive the Down event. Even if you navigate to another screens - all the buttons will be impossible to navigate.

### **Conclusion:**
1) The problem is that after opening keyboard, the navigation between widgets with a remote controller becomes impossible.
2) All of the  RawKeyboard listeners stops receiving "Down" events. It is critical to our app, as it uses its own focus navigation solution, based on the listening of RawKeyboard events.
3) Seems that Android does not generate key down, because the virtual keyboard is not "terminated". The problem found in AndroidKeyProcessor.java. It always return true even if the keyboard closed:
```
 public boolean onKeyDown(@NonNull KeyEvent keyEvent) {
    if (eventResponder.dispatchingKeyEvent) {
      return false;
    }
    //Seems, here is the problem, as it always return true even if the keyboard closed:
    if (textInputPlugin.getLastInputConnection() != null
        && textInputPlugin.getInputMethodManager().isAcceptingText()) {
      if (textInputPlugin.getLastInputConnection().sendKeyEvent(keyEvent)) {
        return true;
      }
    }

    Character complexCharacter = applyCombiningCharacterToBaseCharacter(keyEvent.getUnicodeChar());
    KeyEventChannel.FlutterKeyEvent flutterEvent =
        new KeyEventChannel.FlutterKeyEvent(keyEvent, complexCharacter, eventIdSerial++);
    keyEventChannel.keyDown(flutterEvent);
    eventResponder.addEvent(flutterEvent.eventId, keyEvent);
    return true;
  }
```

<details><summary>Sample code</summary>

```
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Focus Example',
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  FocusNode _focusNodeButtonTop;

  @override
  void initState() {
    RawKeyboard.instance.addListener(_handleRawKeyEvent);
    _focusNodeButtonTop = FocusNode();
    _focusNodeButtonTop.requestFocus();
    super.initState();
  }

  @override
  void dispose() {
    _focusNodeButtonTop.dispose();
    RawKeyboard.instance.removeListener(_handleRawKeyEvent);
    super.dispose();
  }

  void _handleRawKeyEvent(event) {
    if (event is RawKeyDownEvent) {
      print(
          "Handle key Down event ${(event.data as RawKeyEventDataAndroid).keyCode}");
    } else if (event is RawKeyUpEvent) {
      print(
          "Handle key Up event ${(event.data as RawKeyEventDataAndroid).keyCode}");
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            RaisedButton(
                autofocus: true,
                focusNode: _focusNodeButtonTop,
                child: Text("Button Top"),
                onPressed: () {
                  print("pressed Button Top");
                }),
            RaisedButton(
                autofocus: true,
                child: Text("Button Bottom"),
                onPressed: () {
                  print("pressed Button Bottom");
                }),
            TextField(),
            RaisedButton(
                autofocus: true,
                child: Text("Unfocus everything"),
                onPressed: () {
                  WidgetsBinding.instance.focusManager.primaryFocus?.unfocus();
                  print("Unfocused everything");
                }),
            RaisedButton(
                autofocus: true,
                child: Text("Request focus to Button Top"),
                onPressed: () {
                  _focusNodeButtonTop.requestFocus();
                  print("Requested focus to Button Top");
                }),
          ],
        ),
      ),
    );
  }
}
```
</details>

### **Flutter doctor:**
```
[√] Flutter (Channel stable, 1.22.4, on Microsoft Windows [Version 10.0.19041.630], locale uk-UA)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[!] Android Studio (version 4.1.0)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] Connected device (1 available)
```
_Note: Do not know why it shows an error, all plugins are installed and working well._

**Comment by pedromassangocode** [comment] 2020-12-08 08:10
I can confirm that the the steps above works fine on `beta` and `master` channel but I found some stranger behavior on `stable` channel.

This is what get while following the steps above on `stable` channel:

```
Performing hot restart...
Syncing files to device sdk gphone x86 arm...
Restarted application in 1,757ms.
I/flutter ( 2051): Handle key Up event 20
I/flutter ( 2051): Handle key Up event 20
I/flutter ( 2051): Handle key Up event 20
I/flutter ( 2051): Handle key Up event 19
I/flutter ( 2051): Handle key Up event 19
I/flutter ( 2051): Handle key Up event 20
I/flutter ( 2051): Handle key Up event 20
```

@megamonster21099 please provide your `flutter doctor -v`.


<details><summary>flutter doctor -v (stable)</summary>

```
[✓] Flutter (Channel stable, 1.22.4, on Mac OS X 10.15.7 19H2 darwin-x64, locale en)
    • Flutter version 1.22.4 at /Users/pedromassango/dev/SDKs/flutter_stable
    • Framework revision 1aafb3a8b9 (4 weeks ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.9.3

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.2.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin installed
    • Dart plugin version 202.8070

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (1 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86 • Android 11 (API 30) (emulator)

! Doctor found issues in 1 category.
Process finished with exit code 0
```
</details>

<details><summary>flutter doctor -v (master)</summary>

```
[✓] Flutter (Channel master, 1.25.0-5.0.pre.108, on Mac OS X 10.15.7 19H2 darwin-x64, locale en)
    • Flutter version 1.25.0-5.0.pre.108 at /Users/pedromassango/dev/SDKs/flutter_master
    • Framework revision 995aa138cd (4 hours ago), 2020-12-08 09:18:02 +0530
    • Engine revision b0d31ae166
    • Dart version 2.12.0 (build 2.12.0-125.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.2.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 52.0.4
    • Dart plugin version 202.8070

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (3 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • macOS (desktop)             • macos         • darwin-x64     • Mac OS X 10.15.7 19H2 darwin-x64
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 87.0.4280.88

• No issues found!
Process finished with exit code 0
```
</details>

**Comment by megamonster21099** [comment] 2020-12-08 08:48
@pedromassangocode , tried again with master and stable. You're right - on master works as expected. Issue happens on stable.
Here is the flutter doctor:
flutter doctor -v (stable):
```
[√] Flutter (Channel stable, 1.22.4, on Microsoft Windows [Version 10.0.19041.630], locale uk-UA)
    • Flutter version 1.22.4 at C:\Android\flutter
    • Framework revision 1aafb3a8b9 (4 weeks ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Android\sdk\
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = C:\Android\sdk\
    • Java binary at: C:\Android\AndroidStudio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Android\AndroidStudio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (1 available)
    • Quad Core Enjoy TV Box (mobile) • 192.168.1.110:5555 • android-arm • Android 7.1.2 (API 25)

! Doctor found issues in 1 category.
```
flutter doctor -v (master):
```
[√] Flutter (Channel master, 1.25.0-5.0.pre.108, on Microsoft Windows [Version 10.0.19041.630], locale uk-UA)
    • Flutter version 1.25.0-5.0.pre.108 at C:\Android\flutter
    • Framework revision 995aa138cd (5 hours ago), 2020-12-08 09:18:02 +0530
    • Engine revision b0d31ae166
    • Dart version 2.12.0 (build 2.12.0-125.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Android\sdk\
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = C:\Android\sdk\
    • Java binary at: C:\Android\AndroidStudio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Android\AndroidStudio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (3 available)
    • Quad Core Enjoy TV Box (mobile) • 192.168.1.110:5555 • android-arm    • Android 7.1.2 (API 25)
    • Chrome (web)                    • chrome             • web-javascript • Google Chrome 87.0.4280.88
    • Edge (web)                      • edge               • web-javascript • Microsoft Edge 85.0.564.67

• No issues found!
```

**Comment by gspencergoog** [comment] 2020-12-11 18:20
Since this appears to be working on beta, I'm going to close this bug, since the code in beta will be making its way to stable in the next release.

**Closed by gspencergoog** 2020-12-11 18:20 UTC
Labels: a: text input, f: focus, found in release: 1.24, framework, has reproducible steps, platform-android
