### ISSUE TITLE
Release build not opening beyond splash screen after upgrading to flutter 2.0

### ISSUE THREAD

**Issue by harshapulikollu** [flutter/flutter#77594] opened 2021-03-08 12:59 UTC
## Steps to Reproduce

Upgraded to `flutter 2.0` and created a appbundle using `flutter build appbundle`

**Expected results:**  App should launch and run as it does on debug builds

**Actual results:** App not moving past splash screen

<details>
  <summary>Logs</summary>
`flutter doctor -v` 

```
[✓] Flutter (Channel stable, 2.0.0, on macOS 11.2.2 20D80 darwin-x64, locale en-GB)
    • Flutter version 2.0.0 at /Users/harshapulikollu/Documents/development/flutter
    • Framework revision 60bd88df91 (5 days ago), 2021-03-03 09:13:17 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/harshapulikollu/Library/Android/sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.53.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0

[✓] Connected device (3 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android R (API 29) (emulator)
    • macOS (desktop)         • macos         • darwin-x64     • macOS 11.2.2 20D80 darwin-x64
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 89.0.4389.82

• No issues found!

```

</details>

**Comment by pedromassangocode** [comment] 2021-03-08 13:33
Hi @harshapulikollu 
Does the issue reproduces with the default Flutter counter app? If not, can you please provide a minimal reproducible code sample?

Can you please provide the steps to install the `appbundle` into the device?
Thank you

**Comment by harshapulikollu** [comment] 2021-03-08 14:20
Hi @pedromassangocode,
The issue is not reproducing with default Flutter counter app.
I uploaded the `appbundle` to Google Play and on the device, I updated the app through Google play.

This is the log when I connected device and run `flutter run --release `
```
E/flutter (14256): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: MissingPluginException(No implementation found for method Firebase#initializeCore on channel plugins.flutter.io/firebase_core)
E/flutter (14256): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156)
E/flutter (14256): <asynchronous suspension>
E/flutter (14256): #1      MethodChannel.invokeListMethod (package:flutter/src/services/platform_channel.dart:344)
E/flutter (14256): <asynchronous suspension>
E/flutter (14256): #2      MethodChannelFirebase._initializeCore (package:firebase_core_platform_interface/src/method_channel/method_channel_firebase.dart:30)
E/flutter (14256): <asynchronous suspension>
E/flutter (14256): #3      MethodChannelFirebase.initializeApp (package:firebase_core_platform_interface/src/method_channel/method_channel_firebase.dart:77)
E/flutter (14256): <asynchronous suspension>
E/flutter (14256): #4      Firebase.initializeApp (package:firebase_core/src/firebase.dart:41)
E/flutter (14256): <asynchronous suspension>
E/flutter (14256): #5      main (package:kara/main.dart:56)
E/flutter (14256): <asynchronous suspension>
E/flutter (14256): 

```
This is my `firebase_core: ^1.0.0` version in my `pubspec.yaml` file

I have initialized firebase in my `main` method before `runApp`

```
void main() async {
  /// Makes sure dart able to talk with native code to avoid runtime errors
  WidgetsFlutterBinding.ensureInitialized();

  ///Here initializing firebase
  await Firebase.initializeApp();

runApp(MyApp());
```

**Comment by pedromassangocode** [comment] 2021-03-09 06:20
Hi @harshapulikollu 
From what I can see, the issue is related to a FlutterFire plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Comment by pedromassangocode** [comment] 2021-03-09 06:25
Hi @harshapulikollu 
From what I can see, the issue is related to a FlutterFire plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by pedromassangocode** 2021-03-09 06:25 UTC
Labels: in triage
