### ISSUE TITLE
[Skia for Web] Unable to use NetworkImage while Image.memory is fine

### ISSUE THREAD

**Issue by MTRNord** [flutter/flutter#54010] opened 2020-04-04 19:35 UTC
## Steps to Reproduce

1. Run `flutter create bug`.
2. Add a `Image.network()` widget
3. Open the web app using the `--release --dart-define=FLUTTER_WEB_USE_SKIA=true` arguments

**Expected results:** Images being displayed

**Actual results:** Images are downloaded but not displayed

<details>
  <summary>Logs</summary>

Taken from the chrome dev tools. Unfortunly this is release mode (required by the flag) and therefor the issue is obfuscated :(
```
"Cannot pass "[object HTMLImageElement]" as a sk_sp<SkImage>"
```

```
C:\Users\marce\StudioProjects\fluffychat-flutter>flutter analyze
Analyzing fluffychat-flutter...

   info - The value of the field 'httpClient' isn't used - lib\components\audio_player.dart:35:14 - unused_field
   info - 'body1' is deprecated and shouldn't be used. This is the term used in the 2014 version of material design. The modern term is bodyText2. This feature was deprecated after v1.13.8. - lib\components\dialogs\recording_dialog.dart:83:50 -
          deprecated_member_use
   info - 'body1' is deprecated and shouldn't be used. This is the term used in the 2014 version of material design. The modern term is bodyText2. This feature was deprecated after v1.13.8. - lib\components\list_items\message.dart:59:47 - deprecated_member_use
   info - 'body1' is deprecated and shouldn't be used. This is the term used in the 2014 version of material design. The modern term is bodyText2. This feature was deprecated after v1.13.8. - lib\components\list_items\state_message.dart:27:48 -
          deprecated_member_use
   info - 'body1' is deprecated and shouldn't be used. This is the term used in the 2014 version of material design. The modern term is bodyText2. This feature was deprecated after v1.13.8. - lib\components\reply_content.dart:46:55 - deprecated_member_use
   info - 'title' is deprecated and shouldn't be used. This is the term used in the 2014 version of material design. The modern term is headline6. This feature was deprecated after v1.13.8. - lib\components\theme_switcher.dart:36:7 - deprecated_member_use
   info - 'title' is deprecated and shouldn't be used. This is the term used in the 2014 version of material design. The modern term is headline6. This feature was deprecated after v1.13.8. - lib\components\theme_switcher.dart:70:7 - deprecated_member_use
   info - 'title' is deprecated and shouldn't be used. This is the term used in the 2014 version of material design. The modern term is headline6. This feature was deprecated after v1.13.8. - lib\components\theme_switcher.dart:104:7 - deprecated_member_use
   info - 'body1' is deprecated and shouldn't be used. This is the term used in the 2014 version of material design. The modern term is bodyText2. This feature was deprecated after v1.13.8. - lib\views\chat.dart:426:62 - deprecated_member_use
   info - 'title' is deprecated and shouldn't be used. This is the term used in the 2014 version of material design. The modern term is headline6. This feature was deprecated after v1.13.8. - lib\views\chat_details.dart:218:67 - deprecated_member_use
   info - 'body1' is deprecated and shouldn't be used. This is the term used in the 2014 version of material design. The modern term is bodyText2. This feature was deprecated after v1.13.8. - lib\views\chat_details.dart:254:64 - deprecated_member_use
   info - 'body1' is deprecated and shouldn't be used. This is the term used in the 2014 version of material design. The modern term is bodyText2. This feature was deprecated after v1.13.8. - lib\views\chat_encryption_settings.dart:115:66 - deprecated_member_use
   info - 'title' is deprecated and shouldn't be used. This is the term used in the 2014 version of material design. The modern term is headline6. This feature was deprecated after v1.13.8. - lib\views\settings.dart:136:68 - deprecated_member_use

13 issues found. (ran in 8.1s)
```

```
C:\Users\marce\StudioProjects\fluffychat-flutter>flutter doctor -v
[√] Flutter (Channel beta, v1.15.17, on Microsoft Windows [Version 10.0.18362.719], locale de-DE)
    • Flutter version 1.15.17 at C:\flutter
    • Framework revision 2294d75bfa (4 weeks ago), 2020-03-07 00:28:38 +0900
    • Engine revision 5aff311948
    • Dart version 2.8.0 (build 2.8.0-dev.12.0 9983424a3c)


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\marce\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Users\marce\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\192.6308749\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.6)
    • Android Studio at C:\Users\marce\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\192.6308749
    • Flutter plugin version 37.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 80.0.3987.149
    • Web Server • web-server • web-javascript • Flutter Tools

• No issues found!

```

</details>

If you want to check against the real Code I am using you will be able to find the code here (PS: this issue is only happening to the Avatars): https://gitlab.com/ChristianPauly/fluffychat-flutter/-/tree/251b5f26afd49313d14b0934971d77c4432dd519

Be aware that this requires a account from the https://matrix.org network as that is a chat application.

If any further information is required feel free to ping me and I will try to provide that information as best as possible.

**Comment by mkiisoft** [comment] 2020-04-09 20:13
I'm using Channel dev with same experience. The problem with Image.memory are images with CORS blocking getting it from get(url) bodyBytes. My doctor:

`[✓] Flutter (Channel dev, v1.16.3, on Mac OS X 10.14.5 18F132, locale en-US)
    • Flutter version 1.16.3 at /Users/username/Documents/flutter
    • Framework revision be3a4b37b3 (2 weeks ago), 2020-03-26 18:08:05 -0700
    • Engine revision b2bdeb3f0f
    • Dart version 2.8.0 (build 2.8.0-dev.17.0 1402e8e1a4)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/username/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    ! CocoaPods 1.6.1 out of date (1.8.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade:
        sudo gem install cocoapods

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio
    • Android Studio at /Applications/Android Studio 4.1 Preview.app/Contents
    • Flutter plugin version 45.0.2
    • Dart plugin version 193.6494.35
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.0.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] IntelliJ IDEA Community Edition (version 2019.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 36.1.4
    • Dart plugin version 191.7830

[✓] VS Code (version 1.43.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.0
`

**Comment by Pitazzo** [comment] 2020-04-21 19:54
Exactly same problem here; when not using Skia, everything is fine. Here is my doctor output:
```
[✓] Flutter (Channel beta, v1.17.0, on Linux, locale es_ES.UTF-8)
    • Flutter version 1.17.0 at /home/pitazzo/SDKs/flutter
    • Framework revision d3ed9ec945 (hace 2 semanas), 2020-04-06 14:07:34 -0700
    • Engine revision c9506cb8e9
    • Dart version 2.8.0 (build 2.8.0-dev.18.0 eea9717938)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/pitazzo/SDKs/android
    • Platform android-29, build-tools 29.0.2
    • ANDROID_SDK_ROOT = /home/pitazzo/SDKs/android
    • Java binary at: /home/pitazzo/SDKs/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[!] Android Studio (version 3.5)
    • Android Studio at /home/pitazzo/SDKs/android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.44.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.9.1

```

Did you find any workaround?

**Comment by rhelenagh** [comment] 2020-05-08 10:50
Is there any progress with this error?
Thank you

**Comment by ChristianPauly** [comment] 2020-05-10 07:49
I've found out that https://pub.dev/packages/flutter_advanced_networkimage is working fine with Skia on one app but not on the other app. We have searched differences for hours but had no idea why...

**Comment by rhelenagh** [comment] 2020-05-13 08:23
Just for information, with the package that mentions https://pub.dev/packages/flutter_advanced_networkimage (which is very interesting) the Skia option active unfortunately doesn't work.

**Comment by m-j-g** [comment] 2020-06-11 14:56
Seems like this should be top priority as every application uses network images.

**Comment by cbenhagen** [comment] 2020-06-28 08:23
Duplicate of https://github.com/flutter/flutter/issues/49725

**Comment by iapicca** [comment] 2020-07-06 13:15
Hi @MTRNord 
as @cbenhagen pointed out there's an open [issue](https://github.com/flutter/flutter/issues/49725) addressing the case you described.
Please follow up on that issue, I'm closing the current one as duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by iapicca** 2020-07-06 13:15 UTC
Labels: P4, a: images, customer: crowd, e: web_canvaskit, platform-web, severe: crash
