### ISSUE TITLE
`Mac module_test_ios` and `Linux_android linux_chrome_dev_mode` framework tests are not running

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#137761] opened 2023-11-02 14:11 UTC
It looks like jobs triggered yesterday are stuck on yellow, and preventing newer jobs from starting. cc @sealesj 

<img width="192" alt="Screenshot 2023-11-02 at 07 09 48" src="https://github.com/flutter/flutter/assets/6343103/c59dcc24-32cc-420b-96aa-a349058eb1a7">

**Comment by sealesj** [comment] 2023-11-02 14:34
Seeing success with retrying the Linux_android linux_chrome_dev_mode job, still looking into the issue with Mac module_test_ios: https://ci.chromium.org/ui/p/flutter/builders/prod/Linux_android%20linux_chrome_dev_mode/11957/overview

**Comment by sealesj** [comment] 2023-11-02 16:32
Now seeing `Linux_android linux_chrome_dev_mode` triggered automatically with the newer job: https://ci.chromium.org/ui/p/flutter/builders/prod/Linux_android%20linux_chrome_dev_mode/11967/overview

**Comment by sealesj** [comment] 2023-11-02 18:13
Issue seems to be resolved and new tests running as normal, closing for now since manual retry of stalled tasks seemed to fix the issue

**Comment by zanderso** [comment] 2023-11-02 19:54
Is there any hint about what the root cause was? I'm not sure anything was really fixed here.

**Comment by sealesj** [comment] 2023-11-02 20:17
@ricardoamador Could you help me understand when I can see `Linux_android linux_chrome_dev_mode` in log output for "Available builder list", but then that build doesn't seem to be scheduled? 
![Screenshot 2023-11-02 at 12 26 10 PM](https://github.com/flutter/flutter/assets/103135467/aa585ca8-9907-4eba-84fe-95f41ce3654b)

**Comment by ricardoamador** [comment] 2023-11-02 21:04
Not sure. I would need to see what was going on around that time. Where all of the bots that can run that target busy? I think the available builders list is just all the builders that are supported.

**Comment by ricardoamador** [comment] 2023-11-02 22:52
That task can run on 18 bots in our prod pool so perhaps there were not enough builders at the time. This could also be an issue with the change over from the deployment of the new services since this happened around that time. Let me see if I can find anything.

**Comment by ricardoamador** [comment] 2023-11-02 23:56
Okay I was able to find this message in the logs which admittedly I had not seen before now:
![image](https://github.com/flutter/flutter/assets/32242716/da8d6848-ffa1-4237-b462-c9f8e33c3b24)

Not saying that is the cause but it is odd.

**Comment by sealesj** [comment] 2023-11-06 14:55
@ricardoamador Thank you for that investigation. I wonder if there was a flakiness issue that contributed to this. 
The issue has not returned but it could be helpful to understand especially if this happens again

**Comment by ricardoamador** [comment] 2023-11-06 17:28
Yeah sorry. I was not finished looking into this. Several other things came up and I was sidetracked. I will take another look today as I am oncall.

**Comment by keyonghan** [comment] 2023-11-08 22:28
Marking as dup of https://github.com/flutter/flutter/issues/122117

**Closed by keyonghan** 2023-11-08 22:28 UTC
Labels: team-infra
