### ISSUE TITLE
Android license status unknown

### ISSUE THREAD

**Issue by prakashdey46** [flutter/flutter#53037] opened 2020-03-22 06:00 UTC
Please kindly help me to resolve this error. 

C:\Users\Lenovo Ideapad>flutter doctor -v
[√] Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [Version 10.0.16299.98], locale en-IN)
    • Flutter version 1.12.13+hotfix.8 at D:\files_prakash\Flutter
    • Framework revision 0b8abb4724 (6 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\Lenovo Ideapad\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed      instructions.

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 29.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[√] VS Code (version 1.43.1)
    • VS Code at C:\Users\Lenovo Ideapad\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.8.1

[√] Connected device (1 available)
    • Z70 • Z70417KA023148 • android-arm64 • Android 7.0 (API 24)

! Doctor found issues in 1 category.

**Comment by Abhishek01039** [comment] 2020-03-22 10:57
flutter doctor --android-licenses
Run this command

**Comment by unreadablename** [comment] 2020-03-22 11:46
flutter doctor tries to find `sdkmanager` in `$ANDROID_HOME/tools/bin/`
but now tools are located in `$ANDROID_HOME/cmdline-tools/latest/bin/`

@Abhishek01039 that's why `flutter doctor --android-licenses` won't work

**Comment by richikchanda1999** [comment] 2020-03-23 04:58
Here is how I had fixed it:
1. Open Android Studio
2. Goto File > Settings
3. Select Appearance & Behaviour > System Settings > Android Sdk
4. Select the 'Sdk tools' tab and uncheck the checkbox below which says 'Hide the obsolete packages'
5. This will update the list and find 'Android SDK Tools (Obsolete)'.
6. Select it, click on apply and follow the steps to install it. 
7. Restart Android Studio and run flutter doctor

**Comment by TahaTesser** [comment] 2020-03-23 11:27
Duplicate of [#51712](https://github.com/flutter/flutter/issues/51712)

**Closed by TahaTesser** 2020-03-23 11:27 UTC
