### ISSUE TITLE
[NavigationRail] NavigationRail does not scroll when NavigationRailDestinations are more than the screen could contain

### ISSUE THREAD

**Issue by DattatreyaReddy** [flutter/flutter#121236] opened 2023-02-22 16:11 UTC
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. The NavigationRail widget throws an overflow exception

**Expected results:** 
* The navigation rail should be scrollable.

**Actual results:** 
* The navigation rail throws an overflow exception

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) => const MaterialApp(home: MyHomePage());
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text("Hello"),
      ),
      body: Row(
        children: [
          NavigationRail(destinations: [
            for (int _ in List.filled(10, 0))
              const NavigationRailDestination(
                icon: Icon(Icons.home),
                label: Text("home"),
              ),
          ], selectedIndex: 0),
          const Expanded(child: Center(child: Text(' Navigation Rail'))),
        ],
      ),
    );
  }
}

```

</details>

<details>
  <summary>Logs</summary>

```
[   +3 ms] Flutter run key commands.
[        ] r Hot reload. 🔥🔥🔥
[        ] R Hot restart.
[        ] h List all available interactive commands.
[        ] d Detach (terminate "flutter run" but leave application running).
[        ] c Clear the screen
[        ] q Quit (terminate the application on the device).
[        ] 💪 Running with sound null safety 💪
[        ] An Observatory debugger and profiler on macOS is available at: http://127.0.0.1:53963/czhm8cCoh-0=/
[ +274 ms] 
           ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
           The following assertion was thrown during layout:
           A RenderFlex overflowed by 184 pixels on the bottom.

           The relevant error-causing widget was:
             NavigationRail NavigationRail:file:///Users/padya/MySpace/flutter-project/bug/lib/main.dart:23:11

           The overflowing RenderFlex has an orientation of Axis.vertical.
           The edge of the RenderFlex that is overflowing has been marked in the rendering with a yellow and
           black striped pattern. This is usually caused by the contents being too big for the RenderFlex.
           Consider applying a flex factor (e.g. using an Expanded widget) to force the children of the
           RenderFlex to fit within the available space instead of being sized to their natural size.
           This is considered an error condition because it indicates that there is content that cannot be
           seen. If the content is legitimately bigger than the available space, consider clipping it with a
           ClipRect widget before putting it in the flex, or using a scrollable container rather than a Flex,
           like a ListView.
           The specific RenderFlex in question is: RenderFlex#44364 relayoutBoundary=up8 OVERFLOWING:
             creator: Column ← Align ← Expanded ← Column ← MediaQuery ← Padding ← SafeArea ← DefaultTextStyle ←
               AnimatedDefaultTextStyle ← _InkFeatures-[GlobalKey#15411 ink renderer] ←
               NotificationListener<LayoutChangedNotification> ← PhysicalModel ← ⋯
             parentData: offset=Offset(0.0, 0.0) (can use size)
             constraints: BoxConstraints(0.0<=w<=Infinity, 0.0<=h<=536.0)
             size: Size(72.0, 536.0)
             direction: vertical
             mainAxisAlignment: start
             mainAxisSize: min
             crossAxisAlignment: center
             verticalDirection: down
           ◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤
           ════════════════════════════════════════════════════════════════════════════════════════════════════
[  +14 ms] The Flutter DevTools debugger and profiler on macOS is available at: http://127.0.0.1:9103?uri=http://127.0.0.1:53963/czhm8cCoh-0=/
[+18275 ms] Application finished.

```

```
Analyzing bug...                                                
No issues found! (ran in 1.3s)
```

```
[✓] Flutter (Channel stable, 3.7.3, on macOS 13.0.1 22A400 darwin-arm64, locale en-IN)
    • Flutter version 3.7.3 on channel stable at /Users/padya/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9944297138 (2 weeks ago), 2023-02-08 15:46:04 -0800
    • Engine revision 248290d6d5
    • Dart version 2.19.2
    • DevTools version 2.20.1

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/padya/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] IntelliJ IDEA Community Edition (version 2022.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.76.0-insider)
    • VS Code at /Applications/Visual Studio Code - Insiders.app/Contents
    • Flutter extension version 3.58.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.0.1 22A400 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 110.0.5481.100

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```

</details>

<img width="912" alt="Screenshot 2023-02-22 at 9 39 18 PM" src="https://user-images.githubusercontent.com/58727124/220685517-d3d6e4da-925c-4e14-97b2-d42634b1872b.png">

**Comment by danagbemava-nc** [comment] 2023-02-23 07:06
Hi @DattatreyaReddy, this is a duplicate of https://github.com/flutter/flutter/issues/89167. 

Kindly update your PR to point to the original issue. 

Closing from here as duplicate.

Thank you

**Closed by danagbemava-nc** 2023-02-23 07:06 UTC
Labels: in triage
