### ISSUE TITLE
TextPainter line metrics test flake

### ISSUE THREAD

**Issue by Piinks** [flutter/flutter#44375] opened 2019-11-07 21:44 UTC
This test failed a post-submit test on a single Linux shard, but passed after re-running.
This link is the line of the failed expectation: https://github.com/flutter/flutter/blob/b10a5d6898532d0dd7298aceb95efd3627b7c3b2/packages/flutter/test/painting/text_painter_test.dart#L749

There was no other output to indicate why the test failed.

**Comment by Piinks** [comment] 2019-11-07 21:50
cc/ @GaryQian

**Comment by godofredoc** [comment] 2019-11-07 23:16
@Piinks by any chance do you a link to the logs?

**Comment by Piinks** [comment] 2019-11-08 00:09
Sure thing!

https://api.cirrus-ci.com/v1/task/5376047603777536/logs/main.log

**Comment by goderbauer** [comment] 2019-11-14 00:57
Dupe of https://github.com/flutter/flutter/issues/43763.

**Closed by goderbauer** 2019-11-14 00:57 UTC
Labels: a: tests, framework, team, team: flakes, team: infra
