### ISSUE TITLE
flutter create fails with pub get -4 error

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#9727] opened 2017-05-02 18:18 UTC
_From @mit-mit on May 2, 2017 17:58_

I have been seeing this sporadically (on MacOS, flutter is up-to-date on master:

```
$ flutter create test82
Creating project test82...
Wrote 64 files.

Running 'flutter packages get' in test82...
1
pub get failed (-4)
$
```

To test things a bit, I just tried this 25 times in a row, and I got the failure three times.

_Copied from original issue: flutter/flutter-intellij#974_

**Comment by mit-mit** [comment] 2017-05-02 18:18
_From @devoncarew on May 2, 2017 17:59_

Is this a pub error? Does this mean that the pub hosted service is overloaded or failing?

**Comment by mit-mit** [comment] 2017-05-02 18:18
_From @devoncarew on May 2, 2017 18:2_

Where is that `1` coming from above?

**Comment by mit-mit** [comment] 2017-05-02 18:18
cc @kevmoo

**Comment by mit-mit** [comment] 2017-05-02 18:18
Managed to get a repro with `-v`:

```
mit-macbookpro2:tmp mit$ flutter create -v test99
[  +19 ms] [/Users/mit/dev/github/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +12 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] [/Users/mit/dev/github/flutter/] git ls-remote --get-url origin
[   +4 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] git@github.com:flutter/flutter.git
[        ] [/Users/mit/dev/github/flutter/] git log -n 1 --pretty=format:%H
[   +4 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] ff8609f27396c91f9ead5a560a19ec3d34d5f7b8
[        ] [/Users/mit/dev/github/flutter/] git log -n 1 --pretty=format:%ar
[   +5 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[        ] 16 hours ago
[ +113 ms] Creating project test99...
[  +15 ms]   test99/.gitignore
[   +8 ms]   test99/.idea/libraries/Dart_SDK.xml
[   +7 ms]   test99/.idea/libraries/Flutter_for_Android.xml
[        ]   test99/.idea/modules.xml
[        ]   test99/.idea/runConfigurations/main_dart.xml
[        ]   test99/.idea/workspace.xml
[   +3 ms]   test99/android.iml
[   +1 ms]   test99/android/.gitignore
[   +1 ms]   test99/android/app/build.gradle
[   +1 ms]   test99/android/app/src/main/AndroidManifest.xml
[   +1 ms]   test99/android/app/src/main/java/com/yourcompany/test99/MainActivity.java
[   +1 ms]   test99/android/app/src/main/res/mipmap-hdpi/ic_launcher.png
[        ]   test99/android/app/src/main/res/mipmap-mdpi/ic_launcher.png
[        ]   test99/android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
[        ]   test99/android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
[        ]   test99/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
[        ]   test99/android/build.gradle
[        ]   test99/android/gradle.properties
[        ]   test99/android/settings.gradle
[   +1 ms]   test99/ios/.gitignore
[        ]   test99/ios/Flutter/AppFrameworkInfo.plist
[        ]   test99/ios/Flutter/Debug.xcconfig
[        ]   test99/ios/Flutter/Release.xcconfig
[        ]   test99/ios/Podfile
[        ]   test99/ios/Podfile.lock
[        ]   test99/ios/Pods/Manifest.lock
[        ]   test99/ios/Pods/Pods.xcodeproj/project.pbxproj
[   +1 ms]   test99/ios/Pods/Pods.xcodeproj/xcshareddata/xcschemes/Pods-Runner.xcscheme
[        ]   test99/ios/Pods/Target Support Files/Pods-Runner/Pods-Runner-acknowledgements.markdown
[   +1 ms]   test99/ios/Pods/Target Support Files/Pods-Runner/Pods-Runner-acknowledgements.plist
[        ]   test99/ios/Pods/Target Support Files/Pods-Runner/Pods-Runner-dummy.m
[        ]   test99/ios/Pods/Target Support Files/Pods-Runner/Pods-Runner-frameworks.sh
[        ]   test99/ios/Pods/Target Support Files/Pods-Runner/Pods-Runner-resources.sh
[        ]   test99/ios/Pods/Target Support Files/Pods-Runner/Pods-Runner.debug.xcconfig
[        ]   test99/ios/Pods/Target Support Files/Pods-Runner/Pods-Runner.release.xcconfig
[        ]   test99/ios/Runner/AppDelegate.h
[        ]   test99/ios/Runner/AppDelegate.m
[        ]   test99/ios/Runner/Assets.xcassets/AppIcon.appiconset/Contents.json
[        ]   test99/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@1x.png
[        ]   test99/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@2x.png
[        ]   test99/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@3x.png
[        ]   test99/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@1x.png
[        ]   test99/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@2x.png
[        ]   test99/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@3x.png
[        ]   test99/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@1x.png
[        ]   test99/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@2x.png
[        ]   test99/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@3x.png
[        ]   test99/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@2x.png
[        ]   test99/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@3x.png
[        ]   test99/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@1x.png
[        ]   test99/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@2x.png
[        ]   test99/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-83.5x83.5@2x.png
[        ]   test99/ios/Runner/Base.lproj/LaunchScreen.storyboard
[        ]   test99/ios/Runner/Base.lproj/Main.storyboard
[        ]   test99/ios/Runner/Info.plist
[        ]   test99/ios/Runner/main.m
[        ]   test99/ios/Runner.xcodeproj/project.pbxproj
[  +12 ms]   test99/ios/Runner.xcodeproj/project.xcworkspace/contents.xcworkspacedata
[        ]   test99/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
[   +1 ms]   test99/ios/Runner.xcworkspace/contents.xcworkspacedata
[        ]   test99/lib/main.dart
[   +2 ms]   test99/test99.iml
[        ]   test99/pubspec.yaml
[   +1 ms]   test99/README.md
[        ] Wrote 64 files.
[   +4 ms] Running 'flutter packages get' in test99...
[   +2 ms] [/Users/mit/tmp/test99/] /Users/mit/dev/github/flutter/bin/cache/dart-sdk/bin/pub --verbosity=warning get --no-precompile
[  +18 ms] 1
pub get failed (-4)

#0      throwToolExit (package:flutter_tools/src/base/common.dart:29)
#1      pubGet (package:flutter_tools/src/dart/pub.dart:62)
<asynchronous suspension>
#2      CreateCommand.runCommand (package:flutter_tools/src/commands/create.dart:147)
<asynchronous suspension>
#3      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:205)
<asynchronous suspension>
#4      FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:156)
<asynchronous suspension>
#5      CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#6      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:262)
<asynchronous suspension>
#7      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#8      Future.Future.sync (dart:async/future.dart:208)
#9      CommandRunner.run (package:args/command_runner.dart:109)
#10     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:157)
#11     run.<anonymous closure> (package:flutter_tools/executable.dart:140)
<asynchronous suspension>
#12     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#13     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#14     _rootRun (dart:async/zone.dart:1120)
#15     _CustomZone.run (dart:async/zone.dart:1001)
#16     runZoned (dart:async/zone.dart:1465)
#17     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#18     run (package:flutter_tools/executable.dart:113)
<asynchronous suspension>
#19     main (package:flutter_tools/executable.dart:66)
<asynchronous suspension>
#20     main (file:///Users/mit/dev/github/flutter/packages/flutter_tools/bin/flutter_tools.dart:8)
#21     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#22     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)


[  +95 ms] ensureAnalyticsSent: 86ms
[   +4 ms] exiting with code -4
mit-macbookpro2:tmp mit$
```

**Comment by mit-mit** [comment] 2017-05-02 18:18
@kevmoo looks like this is the pub command failing. Do we have server-side logs that can help us understand what is going on?

**Comment by kevmoo** [comment] 2017-05-03 01:16
@mit-mit If you could get me a rough time (UTC) when you see this – and your IP address, I could dig in the logs.

I just ran this 25 times (some across my mobile phone tether) to try to reproduce and got nothing.

I'm not sure if it's a server issue or the client – the client should certainly be telling us more in the error case.

**Comment by mit-mit** [comment] 2017-05-03 05:52
Just use the github comment timestamps above; I added those within minutes of seeing the failures.

**Comment by mit-mit** [comment] 2017-05-03 06:17
Also, what is the average duration you are seeing for the `flutter create` command? I'm seeing roughly 5-6 seconds.

**Comment by mit-mit** [comment] 2017-05-03 06:21
Just tried 20 attempts at home, i.e. different machine, different network, same country :-). Got two -4 failures.

**Comment by jakobr-google** [comment] 2017-05-03 08:42
The `1` is coming from pub's stdout.

I tried running `while true; do rm .packages; flutter packages get; done` on my machines. I did not get any errors on my goobuntu machine, but on my macOS laptop, I got these failures intermittently - on both wired and wifi.

Local IP address: 100.104.15.179
Public IP address: 2.109.66.195

Start timestamp: Wed May  3 10:37:13 CEST 2017
End timestamp: Wed May  3 10:38:34 CEST 2017

Output:
```
jakobr-macbookpro:fisk jakobr$ while true; do rm .packages; f packages get; done
rm: .packages: No such file or directory
Running 'flutter packages get' in fisk...             0.3s
Running 'flutter packages get' in fisk...             0.3s
Running 'flutter packages get' in fisk...             0.3s
Running 'flutter packages get' in fisk...             0.3s
Running 'flutter packages get' in fisk...             0.3s
Running 'flutter packages get' in fisk...             0.3s
Running 'flutter packages get' in fisk...             0.3s
Running 'flutter packages get' in fisk...             0.3s
Running 'flutter packages get' in fisk...             0.3s
Running 'flutter packages get' in fisk...             0.3s
Running 'flutter packages get' in fisk...             0.3s
Running 'flutter packages get' in fisk...                 
1
pub get failed (-4)
rm: .packages: No such file or directory
Running 'flutter packages get' in fisk...             0.3s
Running 'flutter packages get' in fisk...             0.3s
Running 'flutter packages get' in fisk...             0.3s
Running 'flutter packages get' in fisk...             0.3s
Running 'flutter packages get' in fisk...             0.3s
Running 'flutter packages get' in fisk...             0.3s
Running 'flutter packages get' in fisk...             0.3s
Running 'flutter packages get' in fisk...             0.3s
Running 'flutter packages get' in fisk...             0.3s
Running 'flutter packages get' in fisk...             0.3s
Running 'flutter packages get' in fisk...             0.3s
Running 'flutter packages get' in fisk...             0.3s
Running 'flutter packages get' in fisk...             0.3s
Running 'flutter packages get' in fisk...                 
1
pub get failed (-4)
rm: .packages: No such file or directory
Running 'flutter packages get' in fisk...             0.3s
Running 'flutter packages get' in fisk...             0.3s
Running 'flutter packages get' in fisk...             0.3s
Running 'flutter packages get' in fisk...                 
1
pub get failed (-4)
rm: .packages: No such file or directory
Running 'flutter packages get' in fisk...             0.3s
Running 'flutter packages get' in fisk...             0.3s
```

The `1` comes from pub, and `pub get failed (-4)` from Flutter Tools. `-4` is the exit code returned from pub.

**Comment by jakobr-google** [comment] 2017-05-03 09:18
Looks like it might be a Dart VM issue. With help from @mkustermann we got a core dump from pub.

Uploaded to `gs://dart-temp-crash-archive/jakob-pub-get-crash-core`, and uploaded copy of the Dart SDK used to `gs://dart-temp-crash-archive/jakob-pub-get-crash-dart-sdk.tar.bz2`.

**Comment by a-siva** [comment] 2017-05-04 01:50
https://github.com/dart-lang/sdk/commit/9b1412031b66f86d2739595d115107def42b736d was landed in the dart repo to fix this

**Closed by a-siva** 2017-05-04 01:50 UTC
Labels: bug, dev: tool

**Comment by jakobr-google** [comment] 2017-05-04 08:49
@mit-mit we can apply @mraleph's workaround to Flutter Tools, if we don't want to roll Dart SDK:
```
diff --git a/packages/flutter_tools/bin/flutter_tools.dart b/packages/flutter_tools/bin/flutter_tools.dart
index 762e6a5e9..bf762394a 100644
--- a/packages/flutter_tools/bin/flutter_tools.dart
+++ b/packages/flutter_tools/bin/flutter_tools.dart
@@ -4,6 +4,13 @@
 
 import 'package:flutter_tools/executable.dart' as executable;
 
+// Temporary workaround for https://github.com/flutter/flutter/issues/9727
+bool get initializeLibNotify {
+  final DateTime date = new DateTime.now();
+  return date.month == 1;
+}
+
 void main(List<String> args) {
+  final bool x = initializeLibNotify;
   executable.main(args);
 }
```

**Comment by mit-mit** [comment] 2017-05-04 08:53
Interesting. @eseidel @abarth I'll let you guys make the call on what fix route to pursue.

**Comment by eseidelGoogle** [comment] 2017-05-04 14:17
@jakobr-google changing flutter_tools sounds lower risk.  I recommend we do that.  I'm not aware of anything else which would cause us to roll dart between now and next Tues (our planned branch point).
