### ISSUE TITLE
[tool_crash] OSError: OS Error: Can't assign requested address, errno = 49

### ISSUE THREAD

**Issue by laity1991** [flutter/flutter#98913] opened 2022-02-22 09:57 UTC
## Command
```
flutter --no-color attach --machine --device-id=F920DEF7-B325-4EA5-8A4C-0A7D74000827 lib/main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
OSError: OS Error: Can't assign requested address, errno = 49
```
#0      _NativeSocket.nativeSetRawOption (dart:io-patch/socket_patch.dart:1564:35)
#1      _NativeSocket.setRawOption (dart:io-patch/socket_patch.dart:1485:5)
#2      _RawDatagramSocket.setRawOption (dart:io-patch/socket_patch.dart:2379:56)
#3      MDnsClient.start (package:multicast_dns/multicast_dns.dart:138:16)
<asynchronous suspension>
#4      MDnsObservatoryDiscovery.query (package:flutter_tools/src/mdns_discovery.dart:66:7)
<asynchronous suspension>
#5      MDnsObservatoryDiscovery.getObservatoryUri (package:flutter_tools/src/mdns_discovery.dart:153:51)
<asynchronous suspension>
#6      AttachCommand._attachToDevice (package:flutter_tools/src/commands/attach.dart:271:11)
<asynchronous suspension>
#7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#8      AttachCommand.runCommand (package:flutter_tools/src/commands/attach.dart:220:5)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1125:27)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#11     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 2.5.3, on macOS 11.6 20G165 darwin-x64, locale zh-Hans-CN)
    • Flutter version 2.5.3 at /Users/liuwenkai1/Library/Developer/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (4 months ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/liuwenkai1/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.2.1, Build version 13C100
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.19.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.34.0

[✓] VS Code (version 1.64.2)
    • VS Code at /Users/liuwenkai1/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.34.0

[✓] Connected device (2 available)
    • iPhone 8 Plus (mobile) • F920DEF7-B325-4EA5-8A4C-0A7D74000827 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 98.0.4758.102

• No issues found!

```

## Flutter Application Metadata
**Type**: module
**Version**: 1.0.0+1
**Material**: true
**Android X**: true
**Module**: true
**Plugin**: false
**Android package**: com.jd.oa.flutter.login.jdme_flutter_login
**iOS bundle identifier**: com.jd.oa.flutter.login.jdmeFlutterLogin
**Creation channel**: stable
**Creation framework version**: 20e59316b8b8474554b38493b8ca888794b0234a
### Plugins
connectivity-3.0.2
connectivity_macos-0.2.1+2
flutter_downloader
jdme_file_transfer
jdme_network
path_provider-2.0.1
path_provider_linux-2.1.0
path_provider_macos-2.0.2
path_provider_windows-2.0.3
shared_preferences-2.0.3
shared_preferences_linux-2.0.2
shared_preferences_macos-2.0.2
shared_preferences_web-2.0.2
shared_preferences_windows-2.0.2
sqflite-2.0.0+4
video_player-2.2.3
video_player_web-2.0.4
wakelock-0.4.0
wakelock_macos-0.1.0+3
wakelock_web-0.2.0+3
webview_flutter-2.0.13

**Comment by maheshmnj** [comment] 2022-02-22 11:31
Hi @laity1991, Thanks for filing the issue. You seem to be using a older version of flutter could you please try upgrading to `stable 2.10.2` and see if that helps fix the issue.

**Comment by laity1991** [comment] 2022-02-23 08:46
But my colleagues are using 2.5.3 without any problems

**Comment by maheshmnj** [comment] 2022-02-23 11:25
They may have a different system setup, Does this issue occur often for you, Probably upgrading might help.

Closing as a duplicate of https://github.com/flutter/flutter/issues/97489

**Closed by maheshmnj** 2022-02-23 11:25 UTC
Labels: in triage
