### ISSUE TITLE
Detecting iOS back swipe

### ISSUE THREAD

**Issue by AndreHaueisen** [flutter/flutter#28237] opened 2019-02-21 00:53 UTC
I have a Flutter package that pushes a new route to show something similar to a Snackbar. The problem is that, on iOS, when the user swipes to go back, my route gets popped without a warning and ends up throwing an exception. Is there any way I can detect that back swipe on iOS?

This is the [package](https://pub.dartlang.org/packages/flushbar) btw.
Thanks for your time.

**Comment by zoechi** [comment] 2019-02-21 07:02
Perhaps https://stackoverflow.com/questions/49161644/flutter-disable-swipe-to-navigate-back-in-ios

To investigate we would need a minimal runnable reproduction
as a single file so that we can just copy your code into `lib/main.dart` of a new project and run to reproduce.

**Comment by zoechi** [comment] 2019-02-21 07:02
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by AndreHaueisen** [comment] 2019-02-21 23:57
Code to reproduce it is really simple. Would appreciate if you could give me some insights. Thanks for your time.

0 - Install `flushbar: ^1.2.1`
1 - Click in the `New Screen` button
2 - In the new screen, click the button to show Fluhsbar
3 - While it is showing, make a swipe to go back on IOS

```
import 'package:flutter/material.dart';
import 'package:flushbar/flushbar.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  void _showFlushbar() {
    Flushbar(
      message: "My first flushbar",
      flushbarPosition: FlushbarPosition.TOP,
    )
      ..borderRadius = 4
      ..aroundPadding = EdgeInsets.all(8)
      ..show(context);
  }



  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            RaisedButton(
              onPressed: () {
                _showFlushbar();
              },
              child: Text("Show flushbar"),
            ),
            RaisedButton(
              child: Text("New screen"),
              onPressed: () {
                Navigator.of(context).push(
                  MaterialPageRoute(builder: (context) {
                    return NewScreen();
                  }),
                );
              },
            )
          ],
        ),
      ),
      // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}

class NewScreen extends StatelessWidget {

  void _showFlushbar(BuildContext context) {
    Flushbar(
      message: "My first flushbar",
    )
      ..borderRadius = 4
      ..aroundPadding = EdgeInsets.all(8)
      ..show(context);
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Container(
        child: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              RaisedButton(
                onPressed: () {
                  _showFlushbar(context);
                },
                child: Text("Show flushbar"),
              ),
            ],
          ),
        ),
      ),
    );
  }
}

```

**Comment by xster** [comment] 2019-02-26 22:41
The answer is maybe, but before I say much, I think this is a create opportunity to improve something in our docs as well. Can I ask what form of docs did you search for in trying to find a solution? Was it the website, or the API docs? If so, which classes did you look at?

**Comment by AndreHaueisen** [comment] 2019-02-28 20:52
I went deep into the file ../flutter/packages/flutter/lib/src/widgets/routes.dart to see if the development team had the answer in one of the lines. No success there.
Actually, I do not understand what happens when IOS back swipe happens. Is `popUntil()` called?

**Comment by AndreHaueisen** [comment] 2019-02-28 21:35
The error happens in the line 1833 of the ..flutter/packages/flutter/lib/src/widgets/navigator.dart file
`_history.last.didPopNext(route);`

**Comment by xster** [comment] 2019-03-01 06:12
I didn't look too deeply into what the flushbar package does. What is the exception thrown exactly?

You can control when the back swipe can be used by looking at https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/cupertino/route.dart#L219. 

From your description, I can't quite tell if the snackbar is being popped and you don't want it to (you can add a WillPopScope to override) or if the route behind the snackbar is being popped (in which case you'd want to top most route to block gestures going to the route behind it or properly handle the top route being disposed).

**Comment by AndreHaueisen** [comment] 2019-03-02 14:03
Flushbar pushes a new route to show a notification. The back swipe dismisses it and the swiped screen but throws an error in the process that I do not understand why.
Preferebly, I don't block the swipe behaviour, just properly handle it.
If I can't find a solution for that I will be forced to block the swipe while Flushbar is showing.

```
══╡ EXCEPTION CAUGHT BY ANIMATION LIBRARY ╞═════════════════════════════════════════════════════════
flutter: The following assertion was thrown while notifying status listeners for AnimationController:
flutter: Cannot reuse a MaterialPageRoute<dynamic> after disposing it.
flutter: 'package:flutter/src/widgets/routes.dart': Failed assertion: line 218 pos 12:
flutter: '!_transitionCompleter.isCompleted'
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new?template=BUG.md
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #2      TransitionRoute.didPopNext (package:flutter/src/widgets/routes.dart:218:12)
flutter: #3      NavigatorState.pop (package:flutter/src/widgets/navigator.dart:1833:23)
flutter: #4      _CupertinoBackGestureController._handleStatusChanged (package:flutter/src/cupertino/route.dart:617:17)
flutter: #5      _AnimationController&Animation&AnimationEagerListenerMixin&AnimationLocalListenersMixin&AnimationLocalStatusListenersMixin.notifyStatusListeners (package:flutter/src/animation/listener_helpers.dart:188:19)
flutter: #6      AnimationController._checkStatusChanged (package:flutter/src/animation/animation_controller.dart:682:7)
flutter: #7      AnimationController._tick (package:flutter/src/animation/animation_controller.dart:698:5)
flutter: #8      Ticker._tick (package:flutter/src/scheduler/ticker.dart:228:5)
flutter: #9      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
flutter: #10     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleBeginFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:906:11)
flutter: #11     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection/runtime/libcompact_hash.dart:367:8)
flutter: #12     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:904:17)
flutter: #13     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleBeginFrame (package:flutter/src/scheduler/binding.dart:834:5)
flutter: #14     _invoke1 (dart:ui/hooks.dart:173:13)
flutter: #15     _beginFrame (dart:ui/hooks.dart:143:3)
flutter: (elided 2 frames from class _AssertionError)
flutter:
flutter: The AnimationController notifying status listeners was:
flutter:   AnimationController#4fedf(⏮ 0.000; paused; DISPOSED; for MaterialPageRoute<dynamic>(null))
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by xster** [comment] 2019-03-06 04:40
Is the preferred behavior that the notification moves with the route that's above it and being swiped or for it to stay anchored as the page behind it gets swiped? 

Is the preferred behavior that the notification stays above the before last route after the last route is swiped away or for it to somehow be gone along with the last route? 

The specific assert failure you pointed out above is fixed on master head via https://github.com/flutter/flutter/pull/28756. Though I'm not sure if the new behavior is what you desire. Worth testing it out.

**Comment by AndreHaueisen** [comment] 2019-03-06 17:16
I think the behavior itself is fine. I mean, the notification should be dismissed if the route bellow it gets popped (as we have now). The problem is just that it throws an error.
I will test it on the master and get back to you.

While we are at the subject, would it be possible to implement something like a `popNamed('routeName')`?
For example, we have routes A, B and C pushed. A was the first, C the last.
Supose I want to pop B without disrupting C. So I go `popNamed(B)`.
Is that reasonable?

**Comment by AndreHaueisen** [comment] 2019-03-06 23:15
Just tested it. It fixes the problem. Although it does not dismiss the notification too (I'm curious to see how you did that), the user can dismiss it manually.
This issue is closed for me if you don't need more information.
I appreciate the time and attention.
Cheers

**Comment by xster** [comment] 2019-03-07 22:48
That was my expected behavior and should be the right behavior too. Since this flushbar package implements the notification via a separate route. it should conceptually not be affected by routes below it being dismissed either. 

Now that I understand your initial question a bit better, it wasn't a documentation issue. It was just a bug in the framework.

**Closed by xster** 2019-03-07 22:48 UTC
Labels: f: cupertino, f: gestures, framework, ⌺‬ platform-ios

**Comment by ThinkDigitalRepair** [comment] 2019-04-30 22:55
One of his questions wasn't answered though. What happens when the route is popped? My issues is that I'm looking to return information to the precious screen, which works with the back arrow, but it returns null when swiped to go back. We should have a way to capture this input.

**Comment by AndreHaueisen** [comment] 2019-05-31 13:07
@xster hello again
Were that any changes to your fix? I'm the beta channel now and the iOS back swipe is causing some weird behavior. It causes Flusbar to be dismissed instead of the screen and the screen animation stops in the middle.
This is not the behavior I experienced [here](https://github.com/flutter/flutter/issues/28237#issuecomment-470315889)

```
[✓] Flutter (Channel beta, v1.6.3, on Mac OS X 10.14.5 18F132, locale en-BR)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
[✓] Android Studio (version 3.4)
[✓] Connected device (2 available)

• No issues found!

```

**Comment by AndreHaueisen** [comment] 2019-06-03 12:09
@zoechi Can you give me a hand here? [#28756](https://github.com/flutter/flutter/pull/28756) fixed the problem, but [#30422](https://github.com/flutter/flutter/pull/30422) appears to have broken it again.

To be clear, the problem I have is that when I show a notification through a route, IOS back gesture pops the notification's route instead of the screen where gesture originated. This causes the back gesture animation to be stuck in the middle of the screen.

A possible solution would be to do what I described [here](https://stackoverflow.com/questions/56419236/conserve-current-route-and-pop-previous-one-in-flutter/56420178#56420178) but it looks like it is not possible. Is that true?

**Comment by jeneena-jose** [comment] 2019-12-31 11:06
Do we get an event when we land on the previous screen on back-swipe from current screen ? @AndreHaueisen

**Comment by shinriyo** [comment] 2020-04-22 00:08
@jeneena-jose Why don't you use it?
https://pub.dev/packages/cupertino_back_gesture
