### ISSUE TITLE
Flutter Image list Crashing 

### ISSUE THREAD

**Issue by rsaf** [flutter/flutter#32820] opened 2019-05-16 17:02 UTC
We built a Page that displays a list of images. The images are rendered on scroll, but yet they consume too much memory. Repeatedly navigating to the page leads to an Immediate crash. This is happening on production and we can't find any working solution.

The code needed to reproduce the issue can be found here at this git repository: 

[source code](https://github.com/rsaf/flutterImageList)

## Steps to Reproduce

1. Navigate to the image list by clicking 'go to test page'

2. scroll to the bottom of the list

3. Press any image (this should navigate to this same page gain)

4. repeat step 2 and 3 several times (about 10-20 times on Iphone 6, or other low memory devices). You can see an obvious memory increase while navigating to the page

![Uploading image.png…]()

## Logs

```
flutter analyze
Analyzing flutterImageList...                                           

   info • Set literals were not supported until version 2.2, but this code is required to be able to run on earlier versions • ImageList/lib/main.dart:12:16 •
          sdk_version_set_literal
   info • The class 'Future' was not exported from 'dart:core' until version 2.1, but this code is required to be able to run on earlier versions •
          ImageList/lib/pages/test_pages/image_list_performance.dart:29:3 • sdk_version_async_exported_from_core
   info • The value of the local variable 'hashTagName' isn't used • ImageList/lib/pages/test_pages/list_item.dart:26:12 • unused_local_variable
   info • The value of the local variable 'likeStatus' isn't used • ImageList/lib/pages/test_pages/list_item.dart:27:10 • unused_local_variable
   info • Unused import: 'package:xiang_flutter/services/storage/god_storage.dart' • ImageList/lib/services/api/api.dart:2:8 • unused_import
   info • Unused import: 'package:flutter/material.dart' • ImageList/lib/services/progress_loading/progress_loading.dart:2:8 • unused_import
   info • Unused import: 'dart:async' • ImageList/lib/services/service_center.dart:6:8 • unused_import
   info • The class 'Future' was not exported from 'dart:core' until version 2.1, but this code is required to be able to run on earlier versions •
          ImageList/lib/utils/utils.dart:24:10 • sdk_version_async_exported_from_core
   info • This class (or a class which this class inherits from) is marked as '@immutable', but one or more of its instance fields are not final: NoData._imageWidth,
          NoData._imageHeight • ImageList/lib/widgets/no_data.dart:3:7 • must_be_immutable
   info • Set literals were not supported until version 2.2, but this code is required to be able to run on earlier versions • lib/main.dart:12:16 • sdk_version_set_literal
   info • The class 'Future' was not exported from 'dart:core' until version 2.1, but this code is required to be able to run on earlier versions •
          lib/pages/test_pages/image_list_performance.dart:29:3 • sdk_version_async_exported_from_core
   info • The value of the local variable 'hashTagName' isn't used • lib/pages/test_pages/list_item.dart:26:12 • unused_local_variable
   info • The value of the local variable 'likeStatus' isn't used • lib/pages/test_pages/list_item.dart:27:10 • unused_local_variable
   info • Unused import: 'package:xiang_flutter/services/storage/god_storage.dart' • lib/services/api/api.dart:2:8 • unused_import
   info • Unused import: 'package:flutter/material.dart' • lib/services/progress_loading/progress_loading.dart:2:8 • unused_import
   info • Unused import: 'dart:async' • lib/services/service_center.dart:6:8 • unused_import
   info • The class 'Future' was not exported from 'dart:core' until version 2.1, but this code is required to be able to run on earlier versions •
          lib/utils/utils.dart:24:10 • sdk_version_async_exported_from_core
   info • This class (or a class which this class inherits from) is marked as '@immutable', but one or more of its instance fields are not final: NoData._imageWidth,
          NoData._imageHeight • lib/widgets/no_data.dart:3:7 • must_be_immutable

18 issues found. (ran in 7.0s)
```

```
flutter doctor -v
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.13.6 17G5019, locale en-CN)
    • Flutter version 1.5.4-hotfix.2 at /Users/rolland/dev/flutter
    • Framework revision 7a4c33425d (2 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/rolland/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.1

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 35.3.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.33.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.0.2

[✓] Connected device (1 available)
    • 测试姬-粉 • e22543eeafdb74d8aaf7a2efc8b29cc1ea95702e • ios • iOS 11.4.1

• No issues found!
```

**Comment by dnfield** [comment] 2019-05-17 14:50
This seems to be a duplicate of https://github.com/flutter/flutter/issues/32143 - please feel free to reopen if you think there's something else here!

**Closed by dnfield** 2019-05-17 14:50 UTC

**Comment by DyaryRaoof** [comment] 2019-10-12 14:01
Any solutions please ?

**Comment by dnfield** [comment] 2020-01-10 00:00
See https://github.com/flutter/flutter/pull/48536
