### ISSUE TITLE
ConcurrentCopy GC cause Native Crash happens on Android 13 and Android 12  and above devices increase rapidly since 12th Sep.

### ISSUE THREAD

**Issue by mukkumukesh** [flutter/flutter#137328] opened 2023-10-26 08:25 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

We tried to reproduce it on our end but failed so we don't have reproduce steps.

### Expected results

The application should not crash.

### Actual results

On Android 12 & 13 devices, our app received a GC-related native crash from 25th Aug and spike from 12th Sept onwards. We tried to reproduce it on our end but failed. I see those crashes on the Google Play console not even on Firebase crashlytics so it indicates the crash happened on app startup like before Firebase was initiated somehow. I am sharing the crash details that I got from the play console.

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

<img width="1040" alt="OnePlus OP515BL1 (OnePlus Nord2 5G)" src="https://github.com/flutter/flutter/assets/12988908/8e8e1383-a68d-4c54-8e47-df71f0f8cc8a">
<img width="1418" alt="Android_12" src="https://github.com/flutter/flutter/assets/12988908/a618085d-0ac2-47d7-a18f-f8bb97324df4">
<img width="1412" alt="Screenshot 2023-10-21 at 12 43 01 PM" src="https://github.com/flutter/flutter/assets/12988908/8e7c9314-4068-48f4-86dd-90af6d24b5dd">
<img width="1405" alt="Screenshot 2023-10-21 at 12 42 43 PM" src="https://github.com/flutter/flutter/assets/12988908/12f1fa2c-3415-4e0c-a5ce-329074db5c01">
<img width="1405" alt="Screenshot 2023-10-21 at 12 42 18 PM" src="https://github.com/flutter/flutter/assets/12988908/7547ec3b-01b1-4718-a615-591d3cf591a0">
<img width="1408" alt="Screenshot 2023-10-21 at 12 42 02 PM" src="https://github.com/flutter/flutter/assets/12988908/06d2c120-f49c-4e03-b164-1fad0f730f70">

</details>

### Logs

<details><summary>Logs</summary>

```console
Carsh 1:

backtrace:
  #00  pc 0x000000000024b03c  /apex/com.android.art/lib64/libart.so (art::gc::collector::ConcurrentCopying::ProcessMarkStackForMarkingAndComputeLiveBytes()+1720)
  #01  pc 0x0000000000247c7c  /apex/com.android.art/lib64/libart.so (art::gc::collector::ConcurrentCopying::MarkingPhase()+1128)
  #02  pc 0x0000000000244640  /apex/com.android.art/lib64/libart.so (art::gc::collector::ConcurrentCopying::RunPhases()+184)
  #03  pc 0x00000000003bde5c  /apex/com.android.art/lib64/libart.so (art::gc::collector::GarbageCollector::Run(art::gc::GcCause, bool)+320)
  #04  pc 0x00000000003bb8c0  /apex/com.android.art/lib64/libart.so (art::gc::Heap::CollectGarbageInternal(art::gc::collector::GcType, art::gc::GcCause, bool, unsigned int)+508)
  #05  pc 0x00000000003bb114  /apex/com.android.art/lib64/libart.so (art::gc::Heap::ConcurrentGC(art::Thread*, art::gc::GcCause, bool, unsigned int)+188)
  #06  pc 0x00000000003baf98  /apex/com.android.art/lib64/libart.so (art::gc::Heap::ConcurrentGCTask::Run(art::Thread*)+72)
  #07  pc 0x0000000000393830  /apex/com.android.art/lib64/libart.so (art::gc::TaskProcessor::RunAllTasks(art::Thread*)+76)
  #08  pc 0x000000000037b514  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (art_jni_trampoline+116)
  #09  pc 0x00000000006d8768  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (java.lang.Daemons$HeapTaskDaemon.runInternal+200)
  #10  pc 0x00000000006ab49c  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (java.lang.Daemons$Daemon.run+172)
  #11  pc 0x00000000004ee2f8  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (java.lang.Thread.run+72)
  #12  pc 0x00000000003605a4  /apex/com.android.art/lib64/libart.so (art_quick_invoke_stub+612)
  #13  pc 0x000000000034b930  /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+144)
  #14  pc 0x00000000004f3e38  /apex/com.android.art/lib64/libart.so (art::Thread::CreateCallback(void*)+1888)
  #15  pc 0x00000000000c1b40  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+224)
  #16  pc 0x0000000000054f20  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64)

Crash 2

backtrace:
  #00  pc 0x000000000007caa4  /apex/com.android.runtime/lib64/bionic/libc.so (abort+180)
  #01  pc 0x00000000007910cc  /apex/com.android.art/lib64/libart.so (art::Runtime::Abort(char const*)+1380)
  #02  pc 0x00000000000357d0  /apex/com.google.mainline.primary.libs@340817060/lib64/[libbase.so/5cbcb48dc4a1ceb71422e6e07e9f12bb952b969b1d4789234c07c3b6241482a6f3a09733800aa23496f3dcd787dd1ded12735fe6dc5b3049d050d96b769bc049/libbase.so](https://www.google.com/url?q=http://libbase.so/5cbcb48dc4a1ceb71422e6e07e9f12bb952b969b1d4789234c07c3b6241482a6f3a09733800aa23496f3dcd787dd1ded12735fe6dc5b3049d050d96b769bc049/libbase.so&sa=D&source=buganizer&usg=AOvVaw1Xm8k2MynsKCWjDUbw5aUB) (android::base::SetAborter(std::__1::function<void (char const*)>&&)::$_0::__invoke(char const*)+80)
  #03  pc 0x0000000000034d58  /apex/com.google.mainline.primary.libs@340817060/lib64/[libbase.so/5cbcb48dc4a1ceb71422e6e07e9f12bb952b969b1d4789234c07c3b6241482a6f3a09733800aa23496f3dcd787dd1ded12735fe6dc5b3049d050d96b769bc049/libbase.so](https://www.google.com/url?q=http://libbase.so/5cbcb48dc4a1ceb71422e6e07e9f12bb952b969b1d4789234c07c3b6241482a6f3a09733800aa23496f3dcd787dd1ded12735fe6dc5b3049d050d96b769bc049/libbase.so&sa=D&source=buganizer&usg=AOvVaw1Xm8k2MynsKCWjDUbw5aUB) (android::base::LogMessage::~LogMessage()+352)
  #04  pc 0x0000000000207724  /apex/com.android.art/lib64/libart.so (art::gc::Verification::LogHeapCorruption(art::ObjPtr<art::mirror::Object>, art::MemberOffset, art::mirror::Object*, bool) const+1976)
  #05  pc 0x000000000024b740  /apex/com.android.art/lib64/libart.so (void art::mirror::Object::VisitReferences<true, (art::VerifyObjectFlags)0, (art::ReadBarrierOption)1, art::gc::collector::ConcurrentCopying::ComputeLiveBytesAndMarkRefFieldsVisitor<true>, art::gc::collector::ConcurrentCopying::ComputeLiveBytesAndMarkRefFieldsVisitor<true> >(art::gc::collector::ConcurrentCopying::ComputeLiveBytesAndMarkRefFieldsVisitor<true> const&, art::gc::collector::ConcurrentCopying::ComputeLiveBytesAndMarkRefFieldsVisitor<true> const&)+1452)
  #06  pc 0x000000000024b0a0  /apex/com.android.art/lib64/libart.so (art::gc::collector::ConcurrentCopying::ProcessMarkStackForMarkingAndComputeLiveBytes()+1820)
  #07  pc 0x0000000000247c7c  /apex/com.android.art/lib64/libart.so (art::gc::collector::ConcurrentCopying::MarkingPhase()+1128)
  #08  pc 0x0000000000244640  /apex/com.android.art/lib64/libart.so (art::gc::collector::ConcurrentCopying::RunPhases()+184)
  #09  pc 0x00000000003bde5c  /apex/com.android.art/lib64/libart.so (art::gc::collector::GarbageCollector::Run(art::gc::GcCause, bool)+320)
  #10  pc 0x00000000003bb8c0  /apex/com.android.art/lib64/libart.so (art::gc::Heap::CollectGarbageInternal(art::gc::collector::GcType, art::gc::GcCause, bool, unsigned int)+508)
  #11  pc 0x00000000003bb114  /apex/com.android.art/lib64/libart.so (art::gc::Heap::ConcurrentGC(art::Thread*, art::gc::GcCause, bool, unsigned int)+188)
  #12  pc 0x00000000003baf98  /apex/com.android.art/lib64/libart.so (art::gc::Heap::ConcurrentGCTask::Run(art::Thread*)+72)
  #13  pc 0x0000000000393830  /apex/com.android.art/lib64/libart.so (art::gc::TaskProcessor::RunAllTasks(art::Thread*)+76)
  #14  pc 0x000000000041d514  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (art_jni_trampoline+116)
  #15  pc 0x00000000006f9c18  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (java.lang.Daemons$HeapTaskDaemon.runInternal+200)
  #16  pc 0x00000000006ccb4c  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (java.lang.Daemons$Daemon.run+172)
  #17  pc 0x000000000050f628  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (java.lang.Thread.run+72)
  #18  pc 0x00000000003605a4  /apex/com.android.art/lib64/libart.so (art_quick_invoke_stub+612)
  #19  pc 0x000000000034b930  /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+144)
  #20  pc 0x00000000004f3e38  /apex/com.android.art/lib64/libart.so (art::Thread::CreateCallback(void*)+1888)
  #21  pc 0x00000000000eb720  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+208)
  #22  pc 0x000000000007e2d0  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64)

```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
flutter doctor

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.8, on macOS 13.6 22G120 darwin-arm64, locale en-IN)
[!] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] Android Studio (version 2022.1)
[✓] Connected device (3 available)
[✓] Network resources

! Doctor found issues in 1 category.

```

</details>

**Comment by dam-ease** [comment] 2023-10-26 12:58
Hi @mukkumukesh. Thanks for filing this. Looking through the logs, I see this doesn't seem peculiar to flutter apps only and can see reported crashes https://issuetracker.google.com/issues/250515266. Can you follow up on that issue to see if its similar to yours?

**Comment by mukkumukesh** [comment] 2023-10-26 16:28
Hello @dam-ease,

I appreciate your quick response. I'd like to clarify that the issue you referred to at https://issuetracker.google.com/issues/250515266 is not the same as our current problem. The issue you mentioned specifically pertains to crashes occurring in Android 11, while our problem is related to crashes happening on Android 12 and newer app versions like 13 and 14.

I've taken the initiative to report this issue to Google's native team at https://issuetracker.google.com/issues/301833859. They have also suggested that log this issue with the Flutter team, as it might be associated with Flutter. You can find their comments on the matter here: [https://issuetracker.google.com/issues/301833859#comment24, https://issuetracker.google.com/issues/301833859#comment37], among others.

At the moment, I'm unable to reproduce the issue on my end, which makes it challenging to pinpoint the exact cause. However, it's crucial that we address this problem promptly since it is negatively impacting our app's performance, and the crash rate is below 99%.

I'm eagerly awaiting your response, as this issue requires urgent attention.  Let me know for any information related to this.

**Comment by dam-ease** [comment] 2023-10-27 07:28
Thanks for your response and taking time to do these. I'll label this for more insights from the team. Thanks!

**Comment by mukkumukesh** [comment] 2023-10-31 04:50
Hi @dam-ease We are eagerly waiting. Any update on this?

**Comment by ltpanda** [comment] 2023-11-01 04:25
+1，our app have the same issue

**Comment by YannZhao** [comment] 2023-11-07 12:26
+1, same issue, affected since 12th Sept.

**Comment by vishnuprajapati** [comment] 2023-11-09 10:50
+1, same issue, affected since September.

**Comment by camsim99** [comment] 2023-11-09 19:43
@mukkumukesh You mentioned that this started happening around September 12th. Did you publish a new version of your app around that time or did you notice an increase in crashes unrelated to such an app update?

**Comment by camsim99** [comment] 2023-11-09 19:45
@vishnuprajapati @YannZhao @ltpanda We've noticed that a couple of folks are running into this issue. Just FYI that the Flutter team sometimes sorts bugs by the amount of 👍  they have. If you want to bring a bug to our attention, using 👍 works more effectively than commenting +1 on a bug

**Comment by reidbaker** [comment] 2023-11-10 15:03
I am reaching out to the engineers working on the android bug, at this time we believe that this is unrelated to flutter usage but are struggling to reliably reproduce. If you can reproduce this issue constantly please comment on this bug.

**Comment by reidbaker** [comment] 2023-11-10 15:39
Dropping to a p2 to reflect that the flutter team is not actively working on this but we are actively seeking reproductions.

**Comment by mukkumukesh** [comment] 2023-11-24 08:23
@camsim99 We did not roll out any release during that period of time. It happens only on the listed device as I said earlier like about and including 12 only.

I am unable to reproduce at my end. Crash is reported on the play console only with limited logs as I shared above. The same issue is also reported on Google's team issue tracker well they also tried to reproduce this but were not able to yet. Google issue tracker link [https://issuetracker.google.com/issues/301833859](url)

**Comment by reidbaker** [comment] 2023-11-27 14:19
We understand and believe this issue will have to be resolved by the android team that is already working on this. If I hear of an update I will try to reflect it here.

**Comment by mukkumukesh** [comment] 2024-02-19 05:47
Hi Everyone, The Issue is resolved by the Google team as the issue at their end. Please find the issue status here [Google Fixes](https://issuetracker.google.com/issues/301833859#comment204).

Thanks @dam-ease @reidbaker For your great effort toward finding and making ticket P2 at your end. We can close the issue now

**Closed** 2024-02-19 17:17 UTC
Labels: platform-android, engine, e: OS-version specific, a: production, P2, needs repro info, team-android, triaged-android
