### ISSUE TITLE
Allow shared-preference instance to be unset

### ISSUE THREAD

**Issue by SEGVeenstra** [flutter/flutter#80495] opened 2021-04-15 07:33 UTC
## Use case

While unit-testing my code I sometimes need an instance of SharedPreferences, but to also test failures I need `SharedPreferences.getInstance()` to crash.

To do so, I can make the MethodChannel throw a platform exception:
```dart
 MethodChannel('plugins.flutter.io/shared_preferences')
        .setMockMethodCallHandler((MethodCall methodCall) async {
      throw genericPlatformException;
    });
```

This works fine, UNLESS, an earlier test has created an instance with `SharedPreferences.getInstance()`.
EDIT:
To be more precise, after using: `SharedPreferences.setMockInitialValues(data)`. Which will use the memoryStore and therefor bypasses the MethodChannel call.

After that the same instance is used and I'm not able to crash the application.

## Proposal

Allow the `SharedPreference.getInstance()` and values set with `setMockInitialValues` to be reset so that each test can start with a clean slate.

**Comment by pedromassangocode** [comment] 2021-04-15 08:28
Does the clear method solved the issue?

```dart
final instance = await SharedPreferences.getInstance();
  await instance.clear();
```

Alternatively calling `SharedPreferences.setMockInitialValues({})` (with a empty map) may clear the state (I haven't tried yet).

**Comment by SEGVeenstra** [comment] 2021-04-15 12:08
That will only clear the data, but I want to replicate the first initialisation where it sets the instance.

I worked around it by just mocking SharedPreferences, but that also renders the `setMockInitialValues`-method pointless because I might as well mock that too...

**Comment by pedromassangocode** [comment] 2021-04-15 12:51
Ok. I found a duplicate of this issue https://github.com/flutter/flutter/issues/25407. Please follow up on that issue as we don't track same issue on different places.
Thank you

**Closed by pedromassangocode** 2021-04-15 12:51 UTC
Labels: in triage
