### ISSUE TITLE
Flutter web shows just blank screen (no error)

### ISSUE THREAD

**Issue by tomasbaran** [flutter/flutter#58432] opened 2020-06-01 20:06 UTC
This is horrible!!! I've lost more than a day on this and still haven't found any solution. Everything works great on iOS and on Android. Once I run it on the web: blank screen & no error! 

- flutter run -d chrome

It's hard to reproduce. What's even more confusing that out of maybe 100 times that I tried it, 4 times it worked without changing anything on my side. Very frustrating, since I'm developing it mainly for the web.

<details>
  <summary>Logs</summary>

```
```

```
```

```
[✓] Flutter (Channel master, 1.19.0-3.0.pre.5, on Mac OS X 10.15.4 19E287, locale es-ES)
    • Flutter version 1.19.0-3.0.pre.5 at /Users/tomas/Development/flutter
    • Framework revision f4d26a3b85 (19 minutes ago), 2020-06-01 12:33:01 -0700
    • Engine revision 923687f0e7
    • Dart version 2.9.0 (build 2.9.0-11.0.dev 6489a0c68d)


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/tomas/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (2 available)
    • Web Server • web-server • web-javascript • Flutter Tools
    • Chrome     • chrome     • web-javascript • Google Chrome 83.0.4103.61

• No issues found!
```

</details>

**Comment by tomasbaran** [comment] 2020-06-01 20:23
I think I'm getting to the core problem: Firestore cloud!!! I need it very urgently to work RIGHT NOW! :( 

I just add `cloud_firestore_web: ^0.1.1+2` or `  cloud_firestore: ^0.13.6` in the pubspec.yaml and bang the website just wouldn't work at all!

**Comment by tomasbaran** [comment] 2020-06-01 20:26
Might be related to: https://github.com/flutter/flutter/issues/50704

**Comment by TahaTesser** [comment] 2020-06-02 11:04
Hi @tomasbaran 
From what I can see, the issue is related to a FlutterFire plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments, possibly providing a minimal reproducible code sample that does not use flutter fire or other 3rd party plugins, and I will reopen it.
Thank you

**Closed by TahaTesser** 2020-06-02 11:04 UTC
