### ISSUE TITLE
[tool_crash] FileSystemException: Cannot resolve symbolic links, OS Error: The system cannot find the path specified., errno = 3

### ISSUE THREAD

**Issue by harshit2608** [flutter/flutter#85002] opened 2021-06-21 20:34 UTC
Flutter Crash Report

## Command
```
flutter doctor
```

## Logs
FileSystemException: Cannot resolve symbolic links, OS Error: The system cannot find the path specified.
, errno = 3
```
#0      FileSystemEntity._throwIfError (dart:io/file_system_entity.dart:818:7)
#1      FileSystemEntity.resolveSymbolicLinksSync (dart:io/file_system_entity.dart:348:5)
#2      ForwardingFileSystemEntity.resolveSymbolicLinksSync (package:file/src/forwarding/forwarding_file_system_entity.dart:56:49)
#3      ForwardingFileSystemEntity.resolveSymbolicLinksSync (package:file/src/forwarding/forwarding_file_system_entity.dart:56:49)
#4      AndroidSdk.locateAndroidSdk.findAndroidHomeDir (package:flutter_tools/src/android/android_sdk.dart:119:43)
#5      AndroidSdk.locateAndroidSdk (package:flutter_tools/src/android/android_sdk.dart:140:54)
#6      AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:104:42)
#7      _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:311:23)
#8      AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:92:20)
#9      AppContext.get (package:flutter_tools/src/base/context.dart:121:32)
#10     AppContext.get (package:flutter_tools/src/base/context.dart:119:24)
#11     androidSdk (package:flutter_tools/src/globals_null_migrated.dart:34:39)
#12     runInContext.<anonymous closure> (package:flutter_tools/src/context_runner.dart:184:29)
#13     AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:104:42)
#14     _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:311:23)
#15     AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:92:20)
#16     AppContext.get (package:flutter_tools/src/base/context.dart:121:32)
#17     AppContext.get (package:flutter_tools/src/base/context.dart:119:24)
#18     deviceManager (package:flutter_tools/src/globals.dart:38:44)
#19     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:262:17)
<asynchronous suspension>
#20     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#21     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:232:5)
<asynchronous suspension>
```
```
encountered exception: FileSystemException: Cannot resolve symbolic links, path = '' (OS Error: The system cannot find the path specified.
, errno = 3)

#0      FileSystemEntity._throwIfError (dart:io/file_system_entity.dart:818:7)
#1      FileSystemEntity.resolveSymbolicLinksSync (dart:io/file_system_entity.dart:348:5)
#2      ForwardingFileSystemEntity.resolveSymbolicLinksSync (package:file/src/forwarding/forwarding_file_system_entity.dart:56:49)
#3      ForwardingFileSystemEntity.resolveSymbolicLinksSync (package:file/src/forwarding/forwarding_file_system_entity.dart:56:49)
#4      AndroidSdk.locateAndroidSdk.findAndroidHomeDir (package:flutter_tools/src/android/android_sdk.dart:119:43)
#5      AndroidSdk.locateAndroidSdk (package:flutter_tools/src/android/android_sdk.dart:140:54)
#6      AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:104:42)
#7      _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:311:23)
#8      AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:92:20)
#9      AppContext.get (package:flutter_tools/src/base/context.dart:121:32)
#10     androidSdk (package:flutter_tools/src/globals_null_migrated.dart:34:39)
#11     runInContext.<anonymous closure> (package:flutter_tools/src/context_runner.dart:120:29)
#12     AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:104:42)
#13     _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:311:23)
#14     AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:92:20)
#15     AppContext.get (package:flutter_tools/src/base/context.dart:121:32)
#16     androidWorkflow (package:flutter_tools/src/android/android_workflow.dart:26:49)
#17     _DefaultDoctorValidatorsProvider.validators (package:flutter_tools/src/doctor.dart:80:11)
#18     Doctor.validators (package:flutter_tools/src/doctor.dart:186:46)
#19     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:192:45)
#20     Doctor.diagnose (package:flutter_tools/src/doctor.dart:303:47)
#21     _doctorText (package:flutter_tools/runner.dart:232:18)
#22     _handleToolError (package:flutter_tools/runner.dart:157:27)
<asynchronous suspension>
#23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#24     main (package:flutter_tools/executable.dart:91:3)
<asynchronous suspension>

```

## Flutter Application Metadata
No pubspec in working directory.

**Comment by harshit2608** [comment] 2021-06-21 20:44
I have followed all the steps that are mentioned in the issue #79548 but still i am getting the same errors.

Flutter Location: ``C:\Users\<user-name>\flutter``
OS: Windows 10 
Git Version: 2.30.2.windows.1

Also when using cmd without admin permission it gives following error on command : ``flutter``
![Screenshot 2021-06-22 021156](https://user-images.githubusercontent.com/42277796/122825191-3c97b200-d2ff-11eb-979a-a27f8d70d79c.png)

**Comment by darshankawar** [comment] 2021-06-22 07:33
Closing this as duplicate of https://github.com/flutter/flutter/issues/59770

**Closed by darshankawar** 2021-06-22 07:33 UTC
Labels: in triage
