### ISSUE TITLE
Flutter build with Xcode 15 failed

### ISSUE THREAD

**Issue by Mauro27Y** [flutter/flutter#135237] opened 2023-09-21 17:11 UTC
Yesterday I have installed Mac OS Sonoma RC and Xcode 15 released version. From that moment I wasn't able anymore to build with flutter. For existing project the error is:

```console
Launching lib/main.dart on iPad (10th generation) in debug mode...
Running Xcode build...
Xcode build done.                                            5.4s
Failed to build iOS app
Uncategorized (Xcode): Command CodeSign failed with a nonzero exit code

Could not build the application for the simulator.
Error launching application on iPad (10th generation).
```

So I tried to create a new project but also have an error:

```console
Launching lib/main.dart on iPad (10th generation) in debug mode...
Running Xcode build...
Xcode build done.                                            3.7s
Failed to build iOS app
Error (Xcode): Target debug_unpack_ios failed: Exception: Failed to codesign /Users/nicolarigoni/Documents/Fiverr/test/build/ios/Debug-iphonesimulator/Flutter.framework/Flutter with identity -.

Could not build the application for the simulator.
Error launching application on iPad (10th generation).
```

I have tried the permission in keychain and flutter doctor but all seams okay. Someone can help me? thanks

**Comment by nikb7** [comment] 2023-09-21 20:27
The fix for this has been committed in master channel already.
Hopefully will get live in stable release soon.

**Comment by huycozy** [comment] 2023-09-22 09:20
Could you confirm your project is located in a cloud-synced directory (like OneDrive or a similar one) or not? If so, this is similar to https://github.com/flutter/flutter/issues/123583.

Also, could you share the entire output of `flutter run -v` and `flutter doctor -v`?

May be a duplicate of: https://github.com/flutter/flutter/issues/130639 (please also take a look on it and check if you have a such case as well)

**Comment by Mauro27Y** [comment] 2023-09-23 18:07
yes it was on iCloud directory, but few days ago it was working

**Comment by huycozy** [comment] 2023-09-25 05:34
Can you share what your previous XCode version was? I suspect your case is the same as #130639 described at https://github.com/flutter/flutter/issues/130639#issuecomment-1641036450:

> it was working perfectly until I upgraded to macOS 14 Beta and Xcode 15 Beta

Also, as reported at https://github.com/flutter/flutter/issues/130639#issuecomment-1640995451, the workaround is `to not put Flutter repos in a cloud-synced directory and use source control instead.` and the issue should be followed at https://github.com/flutter/flutter/issues/123583. Let me know if this information is relevant to you.

**Comment by shovelmn** [comment] 2023-09-25 08:46
I got the same error, added details.

```
[   +2 ms] Uncategorized (Xcode): Command CodeSign failed with a nonzero exit code

[   +3 ms] Could not build the application for the simulator.
[        ] Error launching application on iPhone 15.
```

<details>
```
[✓] Flutter (Channel stable, 3.13.5, on macOS 13.5.2 22G91 darwin-x64, locale en-NO)
    • Flutter version 3.13.5 on channel stable at /Users/shovelmn12/fvm/versions/3.13.5
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 12fccda598 (6 days ago), 2023-09-19 13:56:11 -0700
    • Engine revision bd986c5ed2
    • Dart version 3.1.2
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/shovelmn12/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.13.0

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Community Edition (version 2023.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.82.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.72.0

[✓] Connected device (1 available)
    • iPhone 15 (mobile) • 35555E5C-8DC3-456F-8557-78F73A476B3F • ios • com.apple.CoreSimulator.SimRuntime.iOS-17-0 (simulator)

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```
</details>

**Comment by shovelmn12** [comment] 2023-09-25 08:47
I got the same error, added details.

```
[   +2 ms] Uncategorized (Xcode): Command CodeSign failed with a nonzero exit code

[   +3 ms] Could not build the application for the simulator.
[        ] Error launching application on iPhone 15.
```

<details>
```
[✓] Flutter (Channel stable, 3.13.5, on macOS 13.5.2 22G91 darwin-x64, locale en-NO)
    • Flutter version 3.13.5 on channel stable at /Users/shovelmn12/fvm/versions/3.13.5
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 12fccda598 (6 days ago), 2023-09-19 13:56:11 -0700
    • Engine revision bd986c5ed2
    • Dart version 3.1.2
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/shovelmn12/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.13.0

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Community Edition (version 2023.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.82.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.72.0

[✓] Connected device (1 available)
    • iPhone 15 (mobile) • 35555E5C-8DC3-456F-8557-78F73A476B3F • ios • com.apple.CoreSimulator.SimRuntime.iOS-17-0 (simulator)

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```
</details>

**Comment by hugesilver** [comment] 2023-09-29 10:38
Same issue

```
Launching lib/main.dart on iPhone 15 Pro in debug mode...
main.dart:1
Xcode build done.                                           10.3s
Failed to build iOS app
Uncategorized (Xcode): Command CodeSign failed with a nonzero exit code

Could not build the application for the simulator.
Error launching application on iPhone 15 Pro.
Exited
```

**Comment by huycozy** [comment] 2023-09-29 11:05
@shovelmn12 @hugesilver Are you also having this issue with project located in a cloud-synced directory as we discussed above? If so, please take a look at https://github.com/flutter/flutter/issues/135237#issuecomment-1732948641 and share more information if any.

**Comment by perepechin** [comment] 2023-09-29 11:34
I have the same issue, and to debug my app I am currently using this workaround: https://github.com/flutter/flutter/issues/128531#issuecomment-1587984546

In my case, it works just fine for me if I run it via Xcode, but it doesn't work if I run it via "flutter run," so now I run the app via Xcode and then use "flutter attach" in VS Code to attach the debugger.

**Comment by perepechin** [comment] 2023-09-29 11:47
> I have the same issue, and to debug my app I am currently using this workaround: [#128531 (comment)](https://github.com/flutter/flutter/issues/128531#issuecomment-1587984546)
> 
> In my case, it works just fine for me if I run it via Xcode, but it doesn't work if I run it via "flutter run," so now I run the app via Xcode and then use "flutter attach" in VS Code to attach the debugger.

Update. I found that the app folder was located in my Documents folder that is synced with iCloud. 
I moved the sources outside of this Documents folder, and now I don't have this issue anymore, and I can build the app without any issues in VS Code code as well.

**Comment by hugesilver** [comment] 2023-09-30 04:44
> @shovelmn12 @hugesilver Are you also having this issue with project located in a cloud-synced directory as we discussed above? If so, please take a look at [#135237 (comment)](https://github.com/flutter/flutter/issues/135237#issuecomment-1732948641) and share more information if any.

I moved iCloud Storage to Local, It working! thanks!

**Comment by shovelmn12** [comment] 2023-10-01 03:47
I solved the issue by changing a folder I created inside Runner folder.

I named it Resources and seems like xcode did not like it. Once I renamed to to anything else it worked

**Comment by GuerreiroLeonardo** [comment] 2023-10-03 15:14
> Can you share what your previous XCode version was? I suspect your case is the same as #130639 described at [#130639 (comment)](https://github.com/flutter/flutter/issues/130639#issuecomment-1641036450):
> 
> > it was working perfectly until I upgraded to macOS 14 Beta and Xcode 15 Beta
> 
> Also, as reported at [#130639 (comment)](https://github.com/flutter/flutter/issues/130639#issuecomment-1640995451), the workaround is `to not put Flutter repos in a cloud-synced directory and use source control instead.` and the issue should be followed at #123583. Let me know if this information is relevant to you.


Been 4 days on this shit. Finally found why I was having this problem.

**Comment by ArslanYousaf12** [comment] 2023-10-04 19:15
thanks guys finally found the issue

**Comment by amine-zergan** [comment] 2023-10-08 09:15
i have same issue but i can't the solution for it ?????

Xcode build done.                                           19,9s
Failed to build iOS app
Uncategorized (Xcode): Command CodeSign failed with a nonzero exit code

Could not build the application for the simulator.
Error launching application on iPhone 15 Pro.

**Closed** 2023-10-18 09:08 UTC
Labels: waiting for customer response, in triage

**Comment by mars000** [comment] 2023-10-22 09:44
the fix for me:
- move entrie project out of directory that is syncing or associated iwth iCloud and onto a local directory on your HD.
- then it compiled fine.
don't know why, but iCloud is stuffing it up in some way.
Hope this helps and help there is solution to this proble soon, as this started happening as soon as I upgraded OS to Sonoma 14.0
