### ISSUE TITLE
[camera] Mi 6 mobile phone photo after the picture rotation problem

### ISSUE THREAD

**Issue by HyggeBo7** [flutter/flutter#45227] opened 2019-11-20 03:17 UTC
camera: ^0.5.6+3
device: MI6
version:Android 9.0
If the height of the shot is greater than the width, the picture will rotate.

**Comment by iapicca** [comment] 2019-11-20 16:31
Hi @DearBo7 
Can you describe the issue more in details?
Also could you please provide your `flutter doctor -v`
and a minimal code sample to reproduce the problem
Thank you

**Comment by DearBo7** [comment] 2019-11-21 02:05
> Hi @DearBo7
> Can you describe the issue more in details?
> Also could you please provide your `flutter doctor -v`
> and a minimal code sample to reproduce the problem
> Thank you

[√] Flutter (Channel beta, v1.10.7, on Microsoft Windows [Version 10.0.18362.418], locale zh-CN)
    • Flutter version 1.10.7 at D:\android\sdk\flutter
    • Framework revision e70236e36c (7 weeks ago), 2019-10-02 09:32:30 -0700
    • Engine revision 9e6314d348
    • Dart version 2.6.0 (build 2.6.0-dev.4.0 1103600280)

Sometimes the picture that appears will be rotated 90 degrees.

**Comment by iapicca** [comment] 2019-11-21 08:04
Hi @DearBo7
Can you please provide a minimal code sample or the steps to reproduce the problem?
Thank you

**Comment by DearBo7** [comment] 2019-11-25 09:05
CameraResult cameraResult = await Navigator.push(context, MaterialPageRoute(builder: (context) => TakePictureCamera(cameras: cameras)));
      //cameraResult.path;

```dart
class TakePictureCamera extends StatefulWidget {
  final List<CameraDescription> cameras;
  final ResolutionPreset resolutionPreset;
  final bool isEnableVideo;
  final String fileDirectory;

  const TakePictureCamera({
    Key key,
    @required this.cameras,
    this.isEnableVideo: false,
    this.resolutionPreset: ResolutionPreset.max,
    this.fileDirectory,
  })  : assert(isEnableVideo != null),
        assert(cameras != null && cameras.length > 0),
        assert(resolutionPreset != null),
        super(key: key);

  @override
  _TakePictureCameraState createState() => _TakePictureCameraState();
}

class _TakePictureCameraState extends State<TakePictureCamera>
    with WidgetsBindingObserver, TickerProviderStateMixin {
  CameraController _controller;
  String _videoPath;

  bool isFrand = false; //Is it a front camera

  AnimationController percentageAnimationController;
  bool isShowAnimationView = false;
 // File path configuration information stored in this file
  //BlocCamera _blocCamera;

  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addObserver(this);
    //Initialize the rear camera camera
    onNewCameraSelected(widget.cameras.first);

    percentageAnimationController = AnimationController(
        vsync: this, duration: Duration(milliseconds: 15000))
      ..addListener(() {
        setState(() {
          if (percentageAnimationController.isCompleted) {
            onStopButtonPressed();
          }
        });
      });
  }

  @override
  void dispose() {
    _controller?.dispose();
    WidgetsBinding.instance.removeObserver(this);
    percentageAnimationController.dispose();
    super.dispose();
  }

  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    // TODO: implement didChangeAppLifecycleState
    super.didChangeAppLifecycleState(state);
    if (_controller == null || !_controller.value.isInitialized) {
      return;
    }
    if (state == AppLifecycleState.inactive) {
      _controller?.dispose();
    } else if (state == AppLifecycleState.resumed) {
      if (_controller != null) {
        onNewCameraSelected(_controller.description);
      }
    }
  }

  final GlobalKey<ScaffoldState> _scaffoldKey = GlobalKey<ScaffoldState>();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        backgroundColor: Colors.black,
        key: _scaffoldKey,
        body: Container(
          margin: EdgeInsets.only(top: Utils.topSafeHeight),
          width: Utils.width,
          child: ConstrainedBox(
            constraints: BoxConstraints(
              maxWidth: Utils.width,
              maxHeight: Utils.height - Utils.topSafeHeight,
            ),
            child: _cameraPreviewWidget(),
          ),
        ),
        bottomNavigationBar: BottomAppBar(
          color: Colors.transparent,
          child: Container(
            height: 100,
            padding: EdgeInsets.symmetric(vertical: 10),
            child: Row(
              mainAxisAlignment: MainAxisAlignment.spaceAround,
              children: <Widget>[
                //Select album
                Container(
                  child: CircleAvatar(
                    radius: 30,
                    backgroundColor: Colors.transparent,
                    child: IconButton(
                      iconSize: 30,
                      onPressed: () async {
                        File image = await ImagePicker.pickImage(
                            source: ImageSource.gallery);
                        if (image != null) {
                          backResult(image.path,
                              isImage: true, isGallery: true);
                        }
                      },
                      icon: Icon(Icons.photo_size_select_actual,
                          color: Colors.white),
                    ),
                  ),
                ),
                //Camera button
                Container(
                  child: CircleAvatar(
                    backgroundColor: Color(0x7fffffff),
                    radius: 36,
                    child: GestureDetector(
                      onTap: () {
                        if (_controller != null &&
                            _controller.value.isInitialized &&
                            !_controller.value.isRecordingVideo) {
                          onTakePictureButtonPressed();
                        }
                      },
                      onLongPressStart: (longStartDetail) {},
                      onLongPressEnd: (longEndDetail) {},
                      onLongPress: () {
                        ///If you are not allowed to record a video, long press gestures have no effect
                        if (!widget.isEnableVideo) {
                          return;
                        }
                        if (_controller != null &&
                            _controller.value.isInitialized &&
                            !_controller.value.isRecordingVideo) {
                          onVideoRecordButtonPressed();
                        }
                      },
                      onLongPressUp: () {
                        ///If you are not allowed to record a video, long press gestures have no effect
                        if (!widget.isEnableVideo) {
                          return;
                        }
                        if (_controller != null &&
                            _controller.value.isInitialized &&
                            _controller.value.isRecordingVideo) {
                          onStopButtonPressed();
                        }
                      },
                      child: CircleAvatar(
                          backgroundColor: Color(0xffffffff), radius: 30),
                    ),
                  ),
                ),
                //Front and rear camera change buttons
                Container(
                  child: CircleAvatar(
                    radius: 30,
                    backgroundColor: Colors.transparent,
                    child: IconButton(
                      iconSize: 30,
                      onPressed: () {
                        isFrand = !isFrand;
                        if (isFrand) {
                          if (widget.cameras.length > 1) {
                            onNewCameraSelected(widget.cameras[1]);
                          } else {
                            return;
                          }
                        } else {
                          onNewCameraSelected(widget.cameras[0]);
                        }
                      },
                      icon: Icon(Icons.cached, color: Colors.white),
                    ),
                  ),
                ),
              ],
            ),
          ),
        ));
  }

  void onNewCameraSelected(CameraDescription cameraDescription) async {
    if (_controller != null) {
      await _controller.dispose();
    }
    _controller = CameraController(
      cameraDescription,
      widget.resolutionPreset,
      enableAudio: widget.isEnableVideo,
    );

    _controller.addListener(() {
      if (mounted) setState(() {});
      if (_controller.value.hasError) {
        print('Camera error ${_controller.value.errorDescription}');
      }
    });

    try {
      await _controller.initialize();
    } on CameraException catch (e) {
      print(e);
    }

    if (mounted) {
      setState(() {});
    }
  }

  Widget _cameraPreviewWidget() {
    if (_controller == null || !_controller.value.isInitialized) {
      return Container();
    } else {
      return AspectRatio(
        aspectRatio: _controller.value.aspectRatio,
        child: CameraPreview(_controller),
      );
    }
  }

  void onTakePictureButtonPressed() {
    takePicture().then((String imagePath) {
      if (imagePath == null) {
        return;
      }
      if (mounted) {
        backResult(imagePath, isImage: true);
      }
    });
  }

  /// Take a photo and return
  void backResult(String path, {bool isImage: true, bool isGallery: false}) {
    CameraResult cameraResult = CameraResult(path,
        isVideo: !isImage, isImage: isImage, isGallery: isGallery);
    Navigator.pop(context, cameraResult);
  }

  Future<String> takePicture() async {
    if (!_controller.value.isInitialized) {
      return null;
    }
    String filePath = await _blocCamera.getImagesPath();

    if (_controller.value.isTakingPicture) {
      // A capture is already pending, do nothing.
      return null;
    }

    try {
      await _controller.takePicture(filePath);
    } on CameraException catch (e) {
      print(e);
      return null;
    }
    return filePath;
  }

  void onVideoRecordButtonPressed() {
    startVideoRecording().then((String filePath) {
      if (mounted)
        setState(() {
          percentageAnimationController.forward();
        });
      if (filePath != null) print('Saving video to $filePath');
    });
  }

  Future<String> startVideoRecording() async {
    if (!_controller.value.isInitialized) {
      return null;
    }

    String filePath = await _blocCamera.getVideoPath();

    if (_controller.value.isRecordingVideo) {
      // A recording is already started, do nothing.
      return null;
    }

    try {
      _videoPath = filePath;
      await _controller.startVideoRecording(filePath);
    } on CameraException catch (e) {
      print(e);
      return null;
    }
    return filePath;
  }

  void onStopButtonPressed() {
    stopVideoRecording().then((_) {
      if (mounted)
        setState(() {
          percentageAnimationController.reset();
        });
      backResult(_videoPath, isImage: false);
      print('Video recorded to: $_videoPath');
    });
  }

  Future<void> stopVideoRecording() async {
    if (!_controller.value.isRecordingVideo) {
      return null;
    }

    try {
      await _controller.stopVideoRecording();
    } on CameraException catch (e) {
      print(e);
      return null;
    }

//    await _startVideoPlayer();
  }
}

class CameraResult {
  bool isVideo;
  bool isImage;
  bool isGallery;
  String path;

  CameraResult(this.path,
      {this.isVideo: false, this.isImage: true, this.isGallery: false});
}

```

**Comment by DearBo7** [comment] 2019-11-25 09:10
```dart
var cameras = await _getCameras();
CameraResult cameraResult = await Navigator.push(context, MaterialPageRoute(builder: (context) => TakePictureCamera(cameras: cameras)));
//cameraResult.path;
```

**Comment by iapicca** [comment] 2019-11-25 09:10
Thank you @DearBo7 
issue possibly related to https://github.com/flutter/flutter/issues/35334

**Comment by lifenautjoe** [comment] 2020-02-15 12:38
While it can be a  duplicate of  #35334, that issue was never solved nor was given any continuation despite the large amount of people experiencing it. Can we reopen  #35334 perhaps?

**Comment by lifenautjoe** [comment] 2020-02-17 16:27
@DearBo7 I've found a temporal work-around for this.

Please see https://github.com/flutter/flutter/issues/35334#issuecomment-586694182

**Comment by darshankawar** [comment] 2024-07-03 11:28
Revisting this issue, @HyggeBo7 Can you re-run your scenario using latest camera package version and stable version on same device to see if the reported behavior persists or not ? 
I tried to run the code sample you provided but it seems to be outdated. This will help us to properly update status of this issue.

**Closed** 2024-07-24 12:10 UTC
Labels: e: device-specific, platform-android, waiting for customer response, p: camera, package, P2, team-android, triaged-android
