### ISSUE TITLE
Can't Retrieve SHA-1 Certificate for Flutter App

### ISSUE THREAD

**Issue by Adifyr** [flutter/flutter#24776] opened 2018-11-27 11:35 UTC
Hi. I'm trying to integrate Firebase Auth with Flutter. For that I need to register my Android App with Firebase. For Google Sign-In, I require the SHA-1 Certificate of my Android App.

On a regular app, this used to be possible by going to the **Gradle Panel** on the right hand side and executing the **`signingReport` Gradle Task**. However on the flutter app, there is no such Panel, and I can't find any way to show it.

I've also posted a [StackOverflow Question](https://stackoverflow.com/questions/53481094/flutter-get-sha-1-certificate-android-studio-3-2-1), which has been there for 2 days but has no response. Please allow for a way to get a flutter app's SHA-1 certificate conveniently. If a solution to this already exists, please let me know.

**Comment by Adifyr** [comment] 2018-11-27 12:16
Any other way to get the SHA-1 certificate for now?

**Comment by zoechi** [comment] 2018-11-27 12:36
Something like https://www.youtube.com/watch?v=P-IbtOeQld4 worked for me

**Comment by kyleDEVV** [comment] 2018-11-28 09:20
This worked for me a while ago https://www.youtube.com/watch?v=nGvPNG-f1-o&t

**Comment by robert-claypool** [comment] 2019-02-12 08:05
[Authenticating Your Client](https://developers.google.com/android/guides/client-auth) documents how to obtain your SHA-1 with `keytool`.

**Comment by zoechi** [comment] 2019-02-12 08:44
Closing as duplicate of https://github.com/flutter/flutter-intellij/issues/3042

See also https://flutter.io/docs/development/tools/android-studio#editing-android-code-in-android-studio-with-full-ide-support for how to open like an Android project with the related features available until the issue is fixed.

**Closed by zoechi** 2019-02-12 08:44 UTC
Labels: severe: new feature, tool, ▣ platform-android

**Comment by Nik4u22** [comment] 2020-06-24 04:51
You will need to right click on gradlew.bat and go to terminal
<img width="323" alt="Annotation 2020-06-24 100601" src="https://user-images.githubusercontent.com/64134540/85501999-195ef780-b604-11ea-99a9-cf0913e35d9f.png">

In terminal you will need to write command as gradlew signingReport
<img width="551" alt="3" src="https://user-images.githubusercontent.com/64134540/85502052-309de500-b604-11ea-9321-4ba04544a552.png">

Then you will be able to see your key details

<img width="708" alt="4" src="https://user-images.githubusercontent.com/64134540/85502101-457a7880-b604-11ea-8a5b-51fb501afaa6.png">
