### ISSUE TITLE
"One or more plugins require a higher Android SDK/NDK version" – tell me what these plugins are

### ISSUE THREAD

**Issue by bartekpacia** [flutter/flutter#147806] opened 2024-05-03 21:34 UTC
### Steps to reproduce

This error message could've been more helpful, i.e. mention specifically _which_ plugins require higher NDK version:

```
$ flutter build apk --debug

One or more plugins require a higher Android NDK version.
Fix this issue by adding the following to /Users/bartek/projects/example/android/app/build.gradle:
android {
  ndkVersion "25.1.8937393"
  ...
}

Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
```

### Expected results

```
$ flutter build apk --debug

Your project is configured with Android NDK 23.1.7779620, but the following plugin(s) require a higher Android NDK version:
- firebase_core requires 25.1.8937393
- location requires 25.1.8937393
Fix this issue by adding the following to /Users/bartek/projects/example/android/app/build.gradle:
android {
  ndkVersion "25.1.8937393"
  ...
}

Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
```

### Reproduction

I'm using Flutter from master branch (~May 3rd, 2024):

1. `flutter create --platforms=android example`
2. Add some plugins to `pubspec.yaml`:

    ```yaml
    dependencies:
      firebase_core: ^2.30.1
      location: ^6.0.1
    ```
3. `flutter build apk --debug`

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 3.22.0-23.0.pre.30, on macOS 14.4.1 23E224 darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[!] Xcode - develop for iOS and macOS (Xcode 15.3)
    ✗ Unable to get list of installed Simulator runtimes.
[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Android Studio (version 2023.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2024.1.1)
[✓] VS Code (version 1.89.0)
[✓] Connected device (2 available)
[✓] Network resources

! Doctor found issues in 2 categories.
```

</details>

**Comment by huycozy** [comment] 2024-05-06 07:46
Hi @bartekpacia, this change makes sense but I couldn't reproduce the issue. 

In the first build, I faced `incompatible version of Kotlin` issue with `location-6.0.1` plugin, I had to change it from 1.7.10 to 1.9.0.
```console
...
e: /Users/huynq/.pub-cache/hosted/pub.dev/location-6.0.1/android/src/main/java/com/lyokone/location/FlutterLocationService.kt: (294, 17): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
...
```

Then when I built the project again, it was successful without NDK version issue. I wonder if there is any more step to reproduce this?

**Comment by bartekpacia** [comment] 2024-05-06 15:04
@huycozy You're right, sorry. I must've missed something.

But for sure [this test](https://github.com/flutter/flutter/blob/6c7df7968a633b7f71210580f74136b9866d8fa9/packages/flutter_tools/test/integration.shard/android_plugin_ndkversion_mismatch_test.dart) reproduces this problem.

**Comment by huycozy** [comment] 2024-05-07 04:31
Yes, it's obvious through that test. Marking this as a proposal for this improvement.

**Closed** 2024-05-07 15:11 UTC
Labels: platform-android, tool, t: gradle, c: proposal, team-android
