### ISSUE TITLE
Gradle build failed to produce an Android package. but still able to generate working release apk

### ISSUE THREAD

**Issue by newbieflutter** [flutter/flutter#39883] opened 2019-09-05 07:50 UTC
I have a flutter application so I wanted to test the proguard into it. What I did is as follows

1. In build.gradle(Module.app) I have added this
```
buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
            minifyEnabled true
            useProguard true

            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
```
2. Next in the gradle script I have one file named as proguard-rules.pro and contents is as follows.
```
#Flutter Wrapper
-ignorewarnings
-keep class io.flutter.app.** { *; }
-keep class io.flutter.plugin.**  { *; }
-keep class io.flutter.util.**  { *; }
-keep class io.flutter.view.**  { *; }
-keep class io.flutter.**  { *; }
-keep class io.flutter.plugins.**  { *; }
```
3. I go into flutter terminal I ran this command ```flutter build apk``` and after some time it gives me this error 
```
Running Gradle task 'assembleRelease'...                                
Running Gradle task 'assembleRelease'... Done                      90.3s
Gradle build failed to produce an Android package.
```
4. At the very top I have this in red
```
Note: Some input files use unchecked or unsafe operations.              
Note: Recompile with -Xlint:unchecked for details.                      
Note: Some input files use unchecked or unsafe operations.              
Note: Recompile with -Xlint:unchecked for details.                      
Note: /usr/local/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher-5.1.2/android/src/main/java/io/flutter/plugins/urllauncher/WebViewActivity.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details. 
```
Then below some where in red is this 
```
Warning: com.baseflow.geolocator.tasks.LocationUpdatesUsingLocationManagerTask: can't find referenced class com.google.android.gms.common.util.Strings
Warning: com.baseflow.geolocator.tasks.LocationUpdatesUsingLocationManagerTask: can't find referenced class com.google.android.gms.common.util.Strings
Warning: io.flutter.embedding.android.FlutterView: can't find referenced method 'android.graphics.Insets getSystemGestureInsets()' in library class android.view.WindowInsets
Warning: io.flutter.embedding.android.FlutterView: can't find referenced class android.graphics.Insets
Warning: io.flutter.embedding.android.FlutterView: can't find referenced class android.graphics.Insets
Warning: io.flutter.embedding.android.FlutterView: can't find referenced class android.graphics.Insets
Warning: io.flutter.embedding.android.FlutterView: can't find referenced class android.graphics.Insets
Warning: io.flutter.embedding.android.FlutterView: can't find referenced class android.graphics.Insets
Warning: io.flutter.embedding.android.FlutterView: can't find referenced class android.graphics.Insets
Warning: io.flutter.view.FlutterView: can't find referenced method 'android.graphics.Insets getSystemGestureInsets()' in library class android.view.WindowInsets
Warning: io.flutter.view.FlutterView: can't find referenced class android.graphics.Insets
Warning: io.flutter.view.FlutterView: can't find referenced class android.graphics.Insets
Warning: io.flutter.view.FlutterView: can't find referenced class android.graphics.Insets
Warning: io.flutter.view.FlutterView: can't find referenced class android.graphics.Insets
Warning: io.flutter.view.FlutterView: can't find referenced class android.graphics.Insets
Warning: io.flutter.view.FlutterView: can't find referenced class android.graphics.Insets

Warning: there were 14 unresolved references to classes or interfaces.  
         You may need to add missing library jars or update their versions.
         If your code works fine without the missing classes, you can suppress
         the warnings with '-dontwarn' options.                         
         (http://proguard.sourceforge.net/manual/troubleshooting.html#unresolvedclass)
Warning: there were 2 unresolved references to library class members.   
         You probably need to update the library versions.              
         (http://proguard.sourceforge.net/manual/troubleshooting.html#unresolvedlibraryclassmember)
```
But the weird part it still generated the release apk and I can run it well. So how to resolve this issue is it a bug or not ? How to know if the obfuscation is done or not ?

**Comment by BondarenkoStas** [comment] 2019-09-05 08:43
@newbieflutter Can you please provide your ```flutter doctor -v``` output?

**Comment by newbieflutter** [comment] 2019-09-05 10:19
Hi BondarenkoStas, 
Below is the results you requested.

✓] Flutter (Channel dev, v1.9.5, on Mac OS X 10.14.6 18G87, locale en-GB)
    • Flutter version 1.9.5 at /usr/local/flutter
    • Framework revision 365f577c70 (13 days ago), 2019-08-23 14:08:04 -0700
    • Engine revision 72283b6419
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/shaisingh/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    ! CocoaPods out of date (1.6.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade:
        sudo gem install cocoapods
        pod setup

[!] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[!] Connected device
    ! No devices available

**Comment by RenanDelfanti** [comment] 2019-09-10 19:02
Same error for me.

**Comment by kecson** [comment] 2019-09-16 12:21
Same error for me. I has add this in the Proguard-rules.pro:
-keep class io.flutter.app.** { *; }
-keep class io.flutter.plugin.**  { *; }
-keep class io.flutter.util.**  { *; }
-keep class io.flutter.view.**  { *; }
-keep class io.flutter.**  { *; }
-keep class io.flutter.plugins.**  { *; }


Flutter (Channel stable, v1.9.1+hotfix.2)

**Comment by DenisBogatirov** [comment] 2019-09-17 10:21
Same for me

**Comment by newbieflutter** [comment] 2019-09-17 15:57
Hi All,
         Any one found any solution to this issue ?

**Comment by blasten** [comment] 2019-09-17 17:15
Duplicate of https://github.com/flutter/flutter/issues/40218

The solution is posted here: https://github.com/flutter/flutter/issues/40218#issuecomment-531047713

**Closed by blasten** 2019-09-17 17:15 UTC
Labels: customer: crowd, t: gradle, tool
