### ISSUE TITLE
Search Functionality on WEB (CTRL + F) breaks Textfield

### ISSUE THREAD

**Issue by yescorp** [flutter/flutter#124000] opened 2023-04-03 09:22 UTC
## Steps to Reproduce

1. Execute `flutter run` on the code sample on WEB platform 
2. Click on the Textfield 
3. Press `CTRL + F` to open the search field
4. Search for 'a'
5. Click down arrow on the search field to advance the current search match
6. Click on the TextField
7. Try to type any text

**Expected results:** 
The typed text appears in TextField

**Actual results:** 
Typing functionality stops working

https://user-images.githubusercontent.com/79095619/229467749-850aee35-3227-4f25-947f-9a289213c358.mov

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatefulWidget {
  const MyApp({super.key});

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  TextEditingController controller = TextEditingController();

  @override
  void initState() {
    controller.text = '''
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur pharetra nec risus id sodales. Nulla eu faucibus purus. Aliquam sed velit mattis lectus tempus aliquam non ac nisl. Quisque convallis pretium libero non imperdiet. Curabitur et pharetra ipsum, a tincidunt erat. Etiam mattis quis massa id dapibus. Mauris sagittis dui quis ex ultrices fermentum. Etiam at feugiat nunc, et tempus eros. Quisque consectetur lorem a facilisis feugiat. Nunc eget lorem non est rutrum maximus. Aenean iaculis lectus eget dui dapibus tincidunt. Aliquam et sapien erat. Mauris aliquam dignissim sagittis. Morbi aliquam ante et dui mattis, id sagittis sem semper. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.

Maecenas suscipit orci ut tincidunt vehicula. Cras at sodales dui. Ut posuere leo ac finibus finibus. Suspendisse potenti. Maecenas ac semper lectus, non molestie erat. Sed interdum, lorem egestas tincidunt ornare, nibh ex blandit arcu, eu ultricies nulla lorem in lacus. Curabitur ac leo eget turpis malesuada scelerisque eu et arcu. Morbi et eleifend nibh.

Curabitur auctor diam a sollicitudin iaculis. Fusce auctor non justo sit amet lobortis. Etiam vitae pharetra mi. Duis efficitur commodo eros, sed facilisis neque blandit quis. Vivamus ut purus tristique, auctor massa quis, laoreet libero. Phasellus felis mauris, tristique ut aliquet non, varius ac erat. Suspendisse potenti. Sed risus ligula, hendrerit posuere efficitur a, pellentesque a mauris. In hac habitasse platea dictumst.

Donec aliquet quam quis iaculis hendrerit. Donec viverra eget purus sit amet gravida. Donec vulputate massa a nisl commodo aliquet. Suspendisse sem leo, ullamcorper at auctor sed, varius eu odio. Mauris ac imperdiet tortor. Integer elementum accumsan molestie. Donec sed mattis mauris. Aenean vitae feugiat justo. Maecenas fringilla vitae felis vitae laoreet.

Etiam porttitor nunc erat, lobortis cursus purus dictum eget. Phasellus dictum tincidunt tincidunt. Quisque at mollis est, quis sollicitudin nisi. Duis tincidunt est ac enim dictum, ut volutpat nisi blandit. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Mauris consequat ex eget arcu vehicula pharetra. In sit amet mauris vel sem rutrum fermentum. Aliquam non mattis magna.
''';
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: TextField(
          controller: controller,
          maxLines: null,
        ),
      ),
    );
  }
}

```

</details>

<details>
  <summary>Logs</summary>

```
Analyzing flutter-code-editor...                                        
No issues found! (ran in 2.0s)
```

```
[✓] Flutter (Channel stable, 3.7.3, on macOS 12.3 21E230 darwin-x64, locale en-KZ)
    • Flutter version 3.7.3 on channel stable at /Users/yestay/fvm/versions/2.10.2
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9944297138 (8 weeks ago), 2023-02-08 15:46:04 -0800
    • Engine revision 248290d6d5
    • Dart version 2.19.2
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/yestay/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13F100
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.76.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.60.0

[✓] VS Code (version 1.71.0)
    • VS Code at /Users/yestay/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.60.0

[✓] Connected device (3 available)
    • iPhone 12 (mobile) • B9A1DB3D-AAD1-4339-BF60-5B7DD66E4504 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-5 (simulator)
    • macOS (desktop)    • macos                                • darwin-x64     • macOS 12.3 21E230 darwin-x64
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 111.0.5563.146

[✓] HTTP Host Availability
    • All required HTTP hosts are available
```

</details>

**Comment by danagbemava-nc** [comment] 2023-04-03 14:16
Related to https://github.com/flutter/flutter/issues/65504

Reproducible using the code sample provided above. This happens with the normal hardware keyboard as well (not just the onscreen keyboard). We can type into the TextField after unfocusing and refocusing on the TextField but typing breaks after searching again. See the recording below.

<details>
<summary>recording</summary>

https://user-images.githubusercontent.com/88313112/229534849-8cace839-b3ff-498a-b13e-0703be6ccd97.mov
</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.7.9, on macOS 13.3 22E252 darwin-arm64, locale en-GB)
    • Flutter version 3.7.9 on channel stable at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 62bd79521d (4 days ago), 2023-03-30 10:59:36 -0700
    • Engine revision ec975089ac
    • Dart version 2.19.6
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/221.6008.13.2211.9619390/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode-14.3.0.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/221.6008.13.2211.9619390/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] Android Studio (version 2022.1)
    • Android Studio at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/221.6008.13.2211.9477386/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1)
    • IntelliJ at /Users/nexus/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 72.1.5
    • Dart plugin version 231.8109.91

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1)
    • IntelliJ at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/231.8109.175/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.77.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.60.0

[✓] Connected device (3 available)
    • Nexus (mobile)  • 00008020-001875E83A38002E • ios            • iOS 16.4 20E247
    • macOS (desktop) • macos                     • darwin-arm64   • macOS 13.3 22E252 darwin-arm64
    • Chrome (web)    • chrome                    • web-javascript • Google Chrome 111.0.5563.146

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

```
[!] Flutter (Channel master, 3.9.0-20.0.pre.91, on macOS 13.3 22E252 darwin-arm64, locale en-GB)
    • Flutter version 3.9.0-20.0.pre.91 on channel master at /Users/nexus/dev/sdks/flutters
    ! Warning: `flutter` on your path resolves to /Users/nexus/dev/sdks/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/nexus/dev/sdks/flutters. Consider adding /Users/nexus/dev/sdks/flutters/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/nexus/dev/sdks/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/nexus/dev/sdks/flutters. Consider adding /Users/nexus/dev/sdks/flutters/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3a1a47c243 (4 hours ago), 2023-04-03 05:51:18 -0400
    • Engine revision 0ed4b5ecbc
    • Dart version 3.0.0 (build 3.0.0-401.0.dev)
    • DevTools version 2.22.2
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/221.6008.13.2211.9619390/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode-14.3.0.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/221.6008.13.2211.9619390/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] Android Studio (version 2022.1)
    • Android Studio at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/221.6008.13.2211.9477386/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1)
    • IntelliJ at /Users/nexus/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 72.1.5
    • Dart plugin version 231.8109.91

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1)
    • IntelliJ at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/231.8109.175/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.77.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.60.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.3 22E252 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 111.0.5563.146

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

```
</details>

**Comment by mdebbar** [comment] 2023-04-06 20:34
Duplicate of https://github.com/flutter/flutter/issues/82708

**Closed by mdebbar** 2023-04-06 20:34 UTC
Labels: a: text input, platform-web, has reproducible steps, assigned for triage, found in release: 3.7, found in release: 3.9
