### ISSUE TITLE
C# and .NET Library Support

### ISSUE THREAD

**Issue by robloo** [flutter/flutter#62078] opened 2020-07-23 00:32 UTC
Add the ability to use C# and .NET libraries from Dart. Full object-based interop.

## Use case

A lot of existing applications are written using C# and .NET. This is all coming together with .NET 5/6. However, the story about the UI-layer is quite difficult right now. Tech like Flutter is clearly a better design than where MAUI is going. 

I can almost justify re-writing the UI layer in Dart; however, a lot of existing code and business logic is in C#/.NET and needs to be maintained. It's not always ideal to just have a backend running on a server with gRPC sending over data to a Flutter frontend. I would like to use C# logic and data models directly in Flutter apps.

## Proposal

Add support for consuming C#/.NET libraries in a Dart/Flutter app. I'm not asking to be able to write a Flutter UI using C#. This is still a big ask, but it's doable using modifications of the existing .NET 5 AOT compiler and tooling.

**Comment by TahaTesser** [comment] 2020-07-23 10:23
Hi @robloo 
Is this proposal for just consuming C# and .Net logic using platform channel?  Something like https://api.dart.dev/dev/2.10.0-0.0.dev/dart-ffi/dart-ffi-library.html? for C# and .Net.
Please give use some use cases as well
Thank you

**Comment by robloo** [comment] 2020-07-23 15:14
> Is this proposal for just consuming C# and .Net logic using platform channel? OR Something like dart:ffi library for C# and .Net.

I would classify both of these as the same thing. On Desktop OSs it would be useful to have this functionality where the .NET VM can be running in parallel then calling into code running on top of it. However, it's not the main point I'm going for.

The goal would be to support C# and .NET source compiling for the Dart VM and AOT for Android/iOS just like Dart. I'm concerned this may not be doable looking more into it as the Dart VM was never designed for multiple languages.... Perhaps a different architecture with AOT C#/.NET compilation linking with Dart/Flutter is possible but it would need to work on iOS too which is probably the most restrictive.

**Comment by TahaTesser** [comment] 2020-07-24 09:12
Hi @robloo 
From what I can see, the issue is related to a Dart rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/dart-lang/sdk/issuess).
Closing, If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2020-07-24 09:12 UTC
Labels: in triage
