### ISSUE TITLE
App crashes when focusing AutoCompleteGroup TextField

### ISSUE THREAD

**Issue by netgfx** [flutter/flutter#77715] opened 2021-03-09 16:08 UTC
## Steps to Reproduce

1. Run `flutter run --no-sound-null-safety -v`
2. App runs and installs on iPhone SE
3. Focus TextFormField inside an AutoCompleteGroup
4. 
```
AutofillGroup(
        key: UniqueKey(),
        child: TextFormField(
                   autofillHints: [AutofillHints.email],
                   keyboardType: TextInputType.emailAddress,
                   controller: _emailTextController,
                   maxLines: null,
                   onChanged: (value) {},
                   onFieldSubmitted: (value) => {TextInput.finishAutofillContext(shouldSave: true)},
                   decoration: InputDecoration(
                   border: OutlineInputBorder(),
                   labelText: 'Email',
        ),
   ))
```
5. Crashes with:
```
[+4684 ms] Process 82774 stopped
[        ] * thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1,
address=0x3fda9027bf8)
[        ]     frame #0: 0x00000001b2540230 libobjc.A.dylib`lookUpImpOrForward + 92
[        ] libobjc.A.dylib`lookUpImpOrForward:
[        ] ->  0x1b2540230 <+92>:  ldr    w9, [x8]
[        ]     0x1b2540234 <+96>:  mov    w8, #0x8
[        ]     0x1b2540238 <+100>: bic    w8, w8, w9, lsr #26
[        ]     0x1b254023c <+104>: orr    w28, w8, w19
[        ] Target 0: (Runner) stopped.
[        ] ios-deploy exited with code 0
[ +111 ms] Service protocol connection closed.
[        ] Lost connection to device.
[   +2 ms] DevFS: Deleting filesystem on the device

```

**Expected results:**  Not crash

**Actual results:** Crash

<details>
  <summary>Logs</summary>

```
[+4684 ms] Process 82774 stopped
[        ] * thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1,
address=0x3fda9027bf8)
[        ]     frame #0: 0x00000001b2540230 libobjc.A.dylib`lookUpImpOrForward + 92
[        ] libobjc.A.dylib`lookUpImpOrForward:
[        ] ->  0x1b2540230 <+92>:  ldr    w9, [x8]
[        ]     0x1b2540234 <+96>:  mov    w8, #0x8
[        ]     0x1b2540238 <+100>: bic    w8, w8, w9, lsr #26
[        ]     0x1b254023c <+104>: orr    w28, w8, w19
[        ] Target 0: (Runner) stopped.
[        ] ios-deploy exited with code 0
[ +111 ms] Service protocol connection closed.
[        ] Lost connection to device.
[   +2 ms] DevFS: Deleting filesystem on the device
```

```
  info • Unused import: 'dart:io' • lib/AuthData.dart:1:8 • unused_import
   info • Unused import: 'dart:io' • lib/JWTConstructor.dart:1:8 • unused_import
   info • Duplicate import • lib/JWTConstructor.dart:3:8 • duplicate_import
   info • Unused import: 'dart:io' • lib/JWTConstructor.dart:3:8 • unused_import
   info • Unused import: 'package:flutter/scheduler.dart' • lib/JWTConstructor.dart:4:8 • unused_import
   info • Unused import: 'package:flutter/services.dart' • lib/JWTConstructor.dart:5:8 • unused_import
   info • Unused import: 'package:local_auth/local_auth.dart' • lib/JWTConstructor.dart:6:8 • unused_import
   info • The library 'package:key_gen/key_gen.dart' is legacy, and should not be imported into a null safe
          library • lib/JWTConstructor.dart:7:8 • import_of_legacy_library_into_null_safe
   info • Unused import: 'dart:convert' • lib/JWTConstructor.dart:8:8 • unused_import
   info • The library 'package:flutter_secure_storage/flutter_secure_storage.dart' is legacy, and should not
          be imported into a null safe library • lib/JWTConstructor.dart:9:8 •
          import_of_legacy_library_into_null_safe
   info • Unused import: 'package:flutter_secure_storage/flutter_secure_storage.dart' •
          lib/JWTConstructor.dart:9:8 • unused_import
   info • Unused import: 'package:local_auth/local_auth.dart' • lib/Login.dart:5:8 • unused_import
   info • Unused import: 'package:flutter_screen_lock/lock_screen.dart' • lib/Login.dart:6:8 • unused_import
   info • Unused import: 'package:flutter_screen_lock/dot_secret_ui.dart' • lib/Login.dart:7:8 •
          unused_import
   info • The library 'package:flutter_secure_storage/flutter_secure_storage.dart' is legacy, and should not
          be imported into a null safe library • lib/Login.dart:8:8 • import_of_legacy_library_into_null_safe
   info • Unused import: 'dart:convert' • lib/Login.dart:9:8 • unused_import
   info • The library 'package:crypto/crypto.dart' is legacy, and should not be imported into a null safe
          library • lib/Login.dart:10:8 • import_of_legacy_library_into_null_safe
   info • Unused import: 'package:crypto/crypto.dart' • lib/Login.dart:10:8 • unused_import
   info • The library 'package:rflutter_alert/rflutter_alert.dart' is legacy, and should not be imported into
          a null safe library • lib/Login.dart:11:8 • import_of_legacy_library_into_null_safe
   info • The library 'package:key_gen/key_gen.dart' is legacy, and should not be imported into a null safe
          library • lib/Login.dart:19:8 • import_of_legacy_library_into_null_safe
   info • Duplicate import • lib/Login.dart:20:8 • duplicate_import
   info • Unused import: 'dart:convert' • lib/Login.dart:20:8 • unused_import
   info • The field doesn't override an inherited getter or setter • lib/Login.dart:31:31 •
          override_on_non_overriding_member
   info • Name non-constant identifiers using lowerCamelCase • lib/Login.dart:73:16 •
          non_constant_identifier_names
   info • Unused import: 'package:flutter_screen_lock/dot_secret_ui.dart' • lib/Registration.dart:6:8 •
          unused_import
   info • The library 'package:flutter_secure_storage/flutter_secure_storage.dart' is legacy, and should not
          be imported into a null safe library • lib/Registration.dart:7:8 •
          import_of_legacy_library_into_null_safe
   info • The library 'package:crypto/crypto.dart' is legacy, and should not be imported into a null safe
          library • lib/Registration.dart:9:8 • import_of_legacy_library_into_null_safe
   info • Unused import: 'package:crypto/crypto.dart' • lib/Registration.dart:9:8 • unused_import
   info • The library 'package:rflutter_alert/rflutter_alert.dart' is legacy, and should not be imported into
          a null safe library • lib/Registration.dart:10:8 • import_of_legacy_library_into_null_safe
   info • The library 'package:key_gen/key_gen.dart' is legacy, and should not be imported into a null safe
          library • lib/Registration.dart:18:8 • import_of_legacy_library_into_null_safe
   info • Duplicate import • lib/Registration.dart:19:8 • duplicate_import
   info • The field doesn't override an inherited getter or setter • lib/Registration.dart:36:9 •
          override_on_non_overriding_member
   info • The operand can't be null, so the condition is always true • lib/Registration.dart:101:15 •
          unnecessary_null_comparison
   info • Unused import: 'package:flutter/material.dart' • lib/gRPC.dart:3:8 • unused_import
   info • The library 'package:grpc/grpc.dart' is legacy, and should not be imported into a null safe library
          • lib/gRPC.dart:5:8 • import_of_legacy_library_into_null_safe
   info • Unused import: './lib/generated/mtls.pbjson.dart' • lib/gRPC.dart:7:8 • unused_import
   info • Unused import: './lib/generated/mtls.pbenum.dart' • lib/gRPC.dart:8:8 • unused_import
   info • Unused import: './lib/generated/greeter.pbjson.dart' • lib/gRPC.dart:12:8 • unused_import
   info • Unused import: './lib/generated/greeter.pbenum.dart' • lib/gRPC.dart:13:8 • unused_import
   info • Name types using UpperCamelCase • lib/gRPC.dart:22:7 • camel_case_types
   info • The operand can't be null, so the condition is always true • lib/gRPC.dart:101:26 •
          unnecessary_null_comparison
   info • The operand can't be null, so the condition is always true • lib/gRPC.dart:124:26 •
          unnecessary_null_comparison
   info • The operand can't be null, so the condition is always true • lib/gRPC.dart:146:26 •
          unnecessary_null_comparison
   info • The library 'package:protobuf/protobuf.dart' is legacy, and should not be imported into a null safe
          library • lib/lib/generated/common.pb.dart:10:8 • import_of_legacy_library_into_null_safe
   info • The library 'package:protobuf/protobuf.dart' is legacy, and should not be imported into a null safe
          library • lib/lib/generated/greeter.pb.dart:10:8 • import_of_legacy_library_into_null_safe
   info • The library 'package:grpc/service_api.dart' is legacy, and should not be imported into a null safe
          library • lib/lib/generated/greeter.pbgrpc.dart:12:8 • import_of_legacy_library_into_null_safe
   info • The library 'package:protobuf/protobuf.dart' is legacy, and should not be imported into a null safe
          library • lib/lib/generated/mtls.pb.dart:10:8 • import_of_legacy_library_into_null_safe
   info • The library 'package:grpc/service_api.dart' is legacy, and should not be imported into a null safe
          library • lib/lib/generated/mtls.pbgrpc.dart:12:8 • import_of_legacy_library_into_null_safe
   info • The library 'package:key_gen/key_gen.dart' is legacy, and should not be imported into a null safe
          library • lib/main.dart:7:8 • import_of_legacy_library_into_null_safe
   info • The library 'package:flutter_secure_storage/flutter_secure_storage.dart' is legacy, and should not
          be imported into a null safe library • lib/main.dart:9:8 • import_of_legacy_library_into_null_safe
   info • Unused import: 'Authenticate.dart' • lib/main.dart:15:8 • unused_import
   info • Unused import: './JWTConstructor.dart' • lib/main.dart:17:8 • unused_import
   info • The value of the field '_supportState' isn't used • lib/main.dart:86:17 • unused_field
   info • The value of the field '_canCheckBiometrics' isn't used • lib/main.dart:87:9 • unused_field
   info • The value of the field '_availableBiometrics' isn't used • lib/main.dart:88:24 • unused_field
   info • The value of the field '_isAuthenticating' isn't used • lib/main.dart:90:8 • unused_field
   info • Name non-constant identifiers using lowerCamelCase • lib/main.dart:143:16 •
          non_constant_identifier_names
   info • The declaration '_navigateToRegistration' isn't referenced • lib/main.dart:150:3 • unused_element
   info • The declaration '_checkBiometrics' isn't referenced • lib/main.dart:288:16 • unused_element
   info • The declaration '_getAvailableBiometrics' isn't referenced • lib/main.dart:303:16 • unused_element
   info • The library 'package:crypto/crypto.dart' is legacy, and should not be imported into a null safe
          library • lib/utils.dart:3:8 • import_of_legacy_library_into_null_safe
   info • The library 'package:flutter_secure_storage/flutter_secure_storage.dart' is legacy, and should not
          be imported into a null safe library • lib/utils.dart:5:8 • import_of_legacy_library_into_null_safe
   info • The library 'package:key_gen/key_gen.dart' is legacy, and should not be imported into a null safe
          library • lib/utils.dart:6:8 • import_of_legacy_library_into_null_safe
   info • Unused import: 'AuthData.dart' • lib/utils.dart:7:8 • unused_import
```

```
[✓] Flutter (Channel dev, 2.1.0-10.0.pre, on macOS 11.2.1 20D74 darwin-x64, locale en-GR)
    • Flutter version 2.1.0-10.0.pre at /Users/mixalisdobekidis/SDK/flutter
    • Framework revision cc9b78fc5c (12 days ago), 2021-02-25 13:26:03 -0800
    • Engine revision a252ec09b7
    • Dart version 2.13.0 (build 2.13.0-77.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/NO_NAME_SSD/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.54.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (3 available)
    • Redmi Note 5 (mobile) • 3a68a8b3                                 • android-arm64  • Android 9 (API 28)
    • 7L's iPhone (mobile)  • 21a54e701c409f46af355cc927962aa6002a8798 • ios            • iOS 14.4
    • Chrome (web)          • chrome                                   • web-javascript • Google Chrome
      88.0.4324.192

• No issues found!
```

</details>

**Comment by HansMuller** [comment] 2021-03-09 16:48
CC @LongCatIsLooong

**Comment by LongCatIsLooong** [comment] 2021-03-20 23:53
I'm not able to reproduce this on a SE simulator with the repro, either on master or on cc9b78fc5c. @netgfx is this still happening on the latest master?

**Comment by netgfx** [comment] 2021-03-21 08:34
@LongCatIsLooong some notes:
- I have used real iPhone SE and iPhone X devices to replicate this.
- using:
```
Flutter 2.1.0-12.1.pre • channel dev • https://github.com/flutter/flutter.git
Framework • revision 8264cb3e8a (11 days ago) • 2021-03-10 12:37:57 -0800
Engine • revision 711ab3fda0
Tools • Dart 2.13.0 (build 2.13.0-116.0.dev)
```
I haven't tested on master.

**Comment by LongCatIsLooong** [comment] 2021-03-22 19:14
Unfortunately I still can't reproduce this on my XR. I created a new project and replaced the body of the scaffold with the provided code sample, but still no luck.

**Comment by netgfx** [comment] 2021-03-23 10:08
I have tested again on a new project and it doesn't reproduce, however when focusing it the keyboard slightly opens and re-closes (which I understand is a different issue altogether, just mentioning it). But no it doesn't crash anymore. @LongCatIsLooong

**Comment by LongCatIsLooong** [comment] 2021-03-23 21:50
It would be difficult to investigate without a repro since I don't know off the top of my head what went wrong from the stack trace. I think it would be helpful to know if this has to do with the project setup or widget configurations. Does it still repro if you repace your main.dart with something like:

```dart
void main() {
  runApp(
    MaterialApp(
      home: AutofillGroup(
          key: UniqueKey(),
          child: TextFormField(
            autofillHints: [AutofillHints.email],
            keyboardType: TextInputType.emailAddress,
            maxLines: null,
            onChanged: (value) {},
            onFieldSubmitted: (value) { TextInput.finishAutofillContext(shouldSave: true) },
            decoration: InputDecoration(
              border: OutlineInputBorder(),
              labelText: 'Email',
            ),
          )),
    ),
  );
```

**Comment by pedromassangocode** [comment] 2021-04-21 09:13
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2021-04-21 09:13 UTC
Labels: a: text input, f: material design, framework, waiting for customer response
