### ISSUE TITLE
[shared_preferences] pub get failed / exit code 66 / shared_preferences_linux_example

### ISSUE THREAD

**Issue by awhitford** [flutter/flutter#61376] opened 2020-07-13 19:05 UTC
Ever since upgrading `shared_preferences` to **0.5.8**, I am now seeing this:
```
[ios/.symlinks/plugins/shared_preferences_linux/example] flutter pub get
Running "flutter pub get" in example...                         
Because shared_preferences_linux_example depends on shared_preferences from path which doesn't exist (could not find package shared_preferences at "../../shared_preferences"), version solving failed.
pub get failed (66; Because shared_preferences_linux_example depends on shared_preferences from path which doesn't exist (could not find package shared_preferences at "../../shared_preferences"), version solving failed.)
exit code 66
```
Why would an _example_ impact my build?

Luckily, it seems harmless, but it is annoying.

<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.5 19F101, locale en-US)
    • Flutter version 1.17.5 at /Users/anthony/flutter
    • Framework revision 8af6b2f038 (13 days ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0-rc4)
    • Android SDK at /Users/anthony/Library/Android/sdk
    • Platform android-R, build-tools 30.0.0-rc4
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[✓] Connected device (2 available)
    • iPhone 11 Pro Max     • 24F5F921-BD98-497F-9DEF-7F99FEDA41E1 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-5 (simulator)
    • iPad (7th generation) • 9A327E6C-836E-497B-B174-86AD0B20D40E • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-5 (simulator)

• No issues found!
```

</details>

**Comment by TahaTesser** [comment] 2020-07-14 08:21
Hi @awhitford 
Looks like you're trying to run  `shared_preferences_linux_example` on stable channel, in order to use linux example you need to be on either `dev` or `master` [Linux setup](https://flutter.dev/desktop#set-up), linux isn't available on `stable` channel yet

I just ran on latest [example](https://github.com/flutter/plugins/tree/master/packages/shared_preferences/shared_preferences_linux/example) on latest `master`

<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel master, 1.20.0-8.0.pre.75, on Linux, locale en_US.UTF-8)
    • Flutter version 1.20.0-8.0.pre.75 at /home/taha/Code/flutter_master
    • Framework revision bb3280885c (9 hours ago), 2020-07-13 16:28:27 -0700
    • Engine revision f10f172573
    • Dart version 2.9.0 (build 2.9.0-21.0.dev 06cb010247)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /home/taha/Code/sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = /home/taha/Code/sdk
    • Java binary at: /home/taha/Code/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.
[✓] Chrome - develop for the web
    • Chrome at google-chrome
[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1
[✓] Android Studio (version 4.0)
    • Android Studio at /home/taha/Code/android-studio
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
[✓] VS Code (version 1.47.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.12.2
[✓] Connected device (3 available)
    • Linux (desktop)  • linux      • linux-x64      • Linux
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome
      83.0.4103.116
• No issues found!
```

</details> 

Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2020-07-14 08:21 UTC

**Comment by awhitford** [comment] 2020-07-17 06:39
@TahaTesser Just to clarify, I'm not trying to do anything with Linux -- I just upgraded my dependency, and now my build has this warning.  It makes me think that it is trying to do something that it should not be doing.

If my app is not targeting Linux, should I be building Linux code?

But even more disturbing:  Why am I getting a warning message about _example_ code for a dependency?

Also, I only see this in VSCode -- not the command line builds.

**Comment by TahaTesser** [comment] 2020-07-17 13:34
Hi @awhitford 
Example code has only linux folder, i am not sure how you targeting another platform from that example code on `stable ` channel  [example](https://github.com/flutter/plugins/tree/master/packages/shared_preferences/shared_preferences_linux/example)

Can you please provide your `flutter run --verbose`, your `pubspec.yaml` and a complete reproducible minimal code sample
Thank you

**Comment by sumitra19jha** [comment] 2020-08-07 04:06
I am also getting the same error and I am not using linux
