### ISSUE TITLE
[FEATURE] ExpansionTile title height and space between title and leading widgets

### ISSUE THREAD

**Issue by ramioooz** [flutter/flutter#57577] opened 2020-05-19 14:08 UTC
## Use case
ExpansionTile is a very powerful and important widget in many applications, however it has very limited customization. we want to be able to change expansionTile height and spaces as indicated in the image : 

Before : 
![expansionTile-issue-2](https://user-images.githubusercontent.com/27827640/82430568-c5ee0c80-9a8d-11ea-8d8f-c8910b98c67d.png)

After (smaller heights and spaces between `leading` and `title` widgets) 👍
![expansionTile-issue_compact](https://user-images.githubusercontent.com/27827640/82379660-96a4b480-9a27-11ea-9fd8-7e3580888a72.png)

this is simply a column containing 3 expansionTiles and one ListTile like so: 
```
Column(
      children: <Widget>[
        ExpansionTile(
          leading: Icon(Icons.laptop),
          title: Text('Company management',
              style: TextStyle(
                height: 1,
                // color: Colors.white,
              )),
        ),
        Divider(
          thickness: 1,
          height: 0,
          indent: 20,
          endIndent: 0,
          // color: Colors.white30,
        ),
        ExpansionTile(
          title: Text('Service management',
              style: TextStyle(
                height: 1,
                // color: Colors.white,
              )),
          leading: Icon(Icons.settings),
        ),
        Divider(
          thickness: 1,
          height: 0,
          indent: 20,
          endIndent: 0,
          // color: Colors.white30,
        ),
        ExpansionTile(
          title: Text('Clients management',
              style: TextStyle(
                height: 1,
                // color: Colors.white,
              )),
          leading: Icon(Icons.move_to_inbox),
        ),
        Divider(
          thickness: 1,
          height: 0,
          indent: 20,
          endIndent: 0,
          // color: Colors.white30,
        ),
        ListTile(
          leading: Icon(Icons.computer),
          title: Text('Dispatch system',
              style: TextStyle(
                height: 1,
                // color: Colors.white,
              )),
        ),
      ],
    )
```

## Proposal
We understand that you want the overall view of expansionTile widget to comply with Material Design standards, which is amazing 👌 but still, we need to have the freedom to customize the widget as we see suitable for our application.

My regards,
Rami

**Comment by HansMuller** [comment] 2020-05-19 14:25
CC @shihaohong

**Comment by shihaohong** [comment] 2020-05-19 15:15
@AyushBherwani1998 do you have time to take a look at this proposal since you experience with ExpansionTile? I'll happily review a PR if you want to take a look into this :)

**Comment by AyushBherwani1998** [comment] 2020-05-19 15:25
Sure @shihaohong . I'm happy to look into this :)

**Comment by AyushBherwani1998** [comment] 2020-05-19 18:19
@shihaohong Regarding the proposal, we have already a [`tilePadding`](https://github.com/flutter/flutter/blob/1cfd792a380034e1cbd0a4c067b00165222b1f35/packages/flutter/lib/src/material/expansion_tile.dart#L108) property in the master branch which can be used to increase the height of the `ExpansionTile`.

For having the padding between the `leading` and `title` of the `ExpansionTile` we will need to add a new property in the `ListTile` and then expose that property in `ExpansionTile` since internally it uses `ListTile`. 

Also, instead of adding a new property and exposing it later for adding the padding between `leading` and `title` users can simply wrap the leading widget inside the `Padding` widget to get the desired output.

For Example:

```dart
ExpansionTile(
  leading: Padding(
    padding: EdgeInsets.only(right: 24),
    child: Icon(Icons.add),
  ),
  title: Text("Hello"),
)
```

###### Output

![Screenshot_1589911864](https://user-images.githubusercontent.com/34301187/82362975-d28d4900-9a2a-11ea-8803-a2b437922bee.png)


WDYT of making the changes in the `ListTile` for having a new property? Should I proceed to have a look at the `ListTile` implementation and first land a PR for that?

**Comment by shihaohong** [comment] 2020-05-19 18:36
Based on your analysis, it seems like everything that's being asked in the proposal seems possible. @ramioooz, Is there a particular use case that you're not able to achieve with the current API?

**Comment by ramioooz** [comment] 2020-05-19 18:53
Hello @shihaohong and @AyushBherwani1998 

Thank you so much for your reply,
We actually need to explicitly **reduce** (not increase) the height of expansionTile. We tried to place it inside a `SizedBox` and give that a height of something like 30. but it turns out to miss some pixels from the render.

We also want to **reduce** (not increase) the space between `leading` widget and `title` widget of expansionTile

Thank you

**Comment by AyushBherwani1998** [comment] 2020-05-19 19:47
Hey @ramioooz, Thank you for clarifying that.

@shihaohong having a look at the implementation of `ListTile` we can expose the [`visualDensity`](https://github.com/flutter/flutter/blob/602d8baf34ec9d875fd6e74e99699bf62885d9f3/packages/flutter/lib/src/material/list_tile.dart#L711) property to control the compactness of the `ExpansionTile`. WDYT?

**Comment by shihaohong** [comment] 2020-05-19 20:51
It might not be as simple as that, since visual density controls the padding of a few different sections of `ListTile`, while not granting fine-grained control over reducing the tile's padding.

@ramioooz Could you take a look into using visual density in ListTile and see if that allows you to achieve the configuration you want? If not, maybe some specifics on what kind of look you are hoping to go for.

Based on a cursory glance at the ListTile code, it doesn't look like it will be a clean API to simply expose the hard-coded padding values such as [this one](https://github.com/flutter/flutter/blob/602d8baf34ec9d875fd6e74e99699bf62885d9f3/packages/flutter/lib/src/material/list_tile.dart#L1144). From a user's point of view, you will suddenly have to grapple with multiple types of padding properties to get what you want, so we will need to think about this carefully.

**Comment by shihaohong** [comment] 2020-05-19 20:54
@ramioooz It might even be a possibility to just fork the code for ListTile and manually update the hard-coded padding values to get the reduction you want. I know that this poses its own problems, such as keeping the rest of the code updated with new changes to `ListTile`, but that's an option to consider in the short run.

**Comment by ramioooz** [comment] 2020-05-19 21:55
Hey @shihaohong ,
I updated my first comment, added another picture to give you more specifics about the look we desire.
I took a quick look over [expansion_tile.dart](https://github.com/flutter/flutter/blob/602d8baf34ec9d875fd6e74e99699bf62885d9f3/packages/flutter/lib/src/material/expansion_tile.dart) and [list_tile.dart](https://github.com/flutter/flutter/blob/602d8baf34ec9d875fd6e74e99699bf62885d9f3/packages/flutter/lib/src/material/list_tile.dart). I found out that the widgets are so **rigid** and need a serious re-construction from the ground up in order to make it customizable and flexy. 

Yes, I can fork the code and do my own alternations, and maybe make a package out of it and publish it so that anyone can use it, but I'de rather have you guys consider doing it and maybe include it in the SDK upcoming update.

Thanks

**Comment by shihaohong** [comment] 2020-05-20 22:05
@ramioooz I took another look at the code for `ListTile` and I'm starting to feel like it wouldn't be possible without introducing a pretty big breaking change. A lot of the preexisting parameters for ListTile and its subclasses are already depended on by users, and the only reasonable way to alter ListTile to be as flexible as you want would be to introduce massive breaking changes to these implementations (for example, defaulting the ListTiles to have absolutely no padding, and introducing padding through a default padding size that adheres to the material spec).

Based on your screenshot, it looks different enough from a ListTile (or ExpansionTile) that I would simply recommend just creating a custom widget for your use case (which you could do by forking the ExpansionTile code like I mentioned before). 

I explicitly wrote a [section on the API docs for ListTile](https://master-api.flutter.dev/flutter/material/ListTile-class.html#material.ListTile.4) a while ago to demonstrate different ways to construct a variety of widgets because a `ListTile` can only be _so_ flexible before it devolves into a `Row` with multiple items in them, at which point, creating a unique Material library becomes less useful for users.

I will close this issue for now, since I do not think there is a reasonable way forward. I hope my explanation made sense!

**Closed by shihaohong** 2020-05-20 22:05 UTC
Labels: f: material design, framework, proposal

**Comment by degloff** [comment] 2020-06-15 17:11
@ramioooz you may want to give [this package](https://pub.dev/packages/configurable_expansion_tile#-readme-tab-) a try. Not perfect but it allows you to create more compact expansion tiles.

**Comment by jinfagang** [comment] 2020-09-24 05:05
@shihaohong `tilePadding` only shrink down the left and right not top and bottom:

![image](https://user-images.githubusercontent.com/21303438/94103185-8cc40f80-fe66-11ea-909a-22e023773f1f.png)
```
 ExpansionTile(
                  tilePadding: EdgeInsets.symmetric(vertical: 0),
                  childrenPadding: EdgeInsets.all(0),
```

**Comment by shihaohong** [comment] 2020-09-24 05:25
@jinfagang Could you file a new issue with a reproducible sample? Also, the output of `flutter doctor -v` would be helpful as well. cc/ @AyushBherwani1998

**Comment by AyushBherwani1998** [comment] 2020-09-24 05:43
Hey @jinfagang,
The `tilePadding` is working as intended. ExpansionTile internally uses a ListTile whose height is defined as per Material Guidelines. The extra space that you have when applying 0 padding is the normal height of ListTile. In general you can't use `tilePadding` to reduce the height but only increase it.

**Comment by jinfagang** [comment] 2020-09-24 09:36
@AyushBherwani1998 what should I do if I want make it less?

**Comment by jinfagang** [comment] 2020-09-24 09:36
I think thisss issue is also intend to be less the height not more

**Comment by AyushBherwani1998** [comment] 2020-09-24 09:42
The only I can suggest now is to make a custom widget. You can fork the code, and instead of ListTile use a Row inside ExpansionTile for more controls.

**Comment by jinfagang** [comment] 2020-09-25 06:32
@shihaohong  Any ideas? This definitely can be easily done inside flutter...

**Comment by horiaciu** [comment] 2024-04-29 19:09
For anyone still struggling with this, here's how I managed to eliminate all padding:

```
ListTileTheme(
    minVerticalPadding: 0,
    child: ExpansionTile(
        tilePadding: EdgeInsets.zero,
        minTileHeight: 0,
        ...
    ),
),
```

To remove the horizontal padding, setting the `tilePadding` in the `ExpansionTile` to zero is enough.

To remove the vertical padding, you have to set both the `minVerticalPadding` in the `ListTileTheme` and the `minTileHeight` in the `ExpansionTile` to zero.

This is pretty hopeless, but it works.
