### ISSUE TITLE
Issue from website page Flutter Tutorials

### ISSUE THREAD

**Issue by joshuawill** [flutter/flutter#21262] opened 2018-08-31 05:35 UTC
From URL: https://flutter.io/tutorials/

**Comment by zoechi** [comment] 2018-08-31 08:19
Can you please elaborate on what the issue is about?

**Comment by zoechi** [comment] 2018-09-04 11:06
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.

**Closed by zoechi** 2018-09-04 11:06 UTC
