### ISSUE TITLE
[tool_crash] FileSystemException: Error en la creación, Error del sistema operativo: El sistema no puede encontrar la ruta especifica. , errno 3

### ISSUE THREAD

**Issue by Luisgarmendia** [flutter/flutter#67248] opened 2020-10-04 05:34 UTC
## Command
```
flutter build apk --release
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Creation failed, OS Error: El sistema no puede encontrar la ruta especificada.
, errno = 3
```
#0      _Directory.createSync (dart:io/directory_impl.dart:133:7)
#1      ForwardingDirectory.createSync (package:file/src/forwarding/forwarding_directory.dart:22:16)
#2      ForwardingDirectory.createSync (package:file/src/forwarding/forwarding_directory.dart:22:16)
#3      _ensureExists (package:flutter_tools/src/cache.dart:1413:15)
#4      Cache.downloadFile (package:flutter_tools/src/cache.dart:491:5)
#5      CachedArtifact._downloadArchive.<anonymous closure> (package:flutter_tools/src/cache.dart:640:23)
#6      CachedArtifact._downloadArchive.<anonymous closure> (package:flutter_tools/src/cache.dart:636:55)
#7      CachedArtifact._withDownloadFile (package:flutter_tools/src/cache.dart:670:26)
#8      CachedArtifact._downloadArchive (package:flutter_tools/src/cache.dart:636:12)
#9      CachedArtifact._downloadZipArchive (package:flutter_tools/src/cache.dart:657:12)
#10     EngineCachedArtifact.updateInner (package:flutter_tools/src/cache.dart:785:13)
#11     CachedArtifact.update (package:flutter_tools/src/cache.dart:592:11)
#12     Cache.updateAll (package:flutter_tools/src/cache.dart:458:24)
#13     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:831:27)
#14     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:741:33)
#15     _rootRunUnary (dart:async/zone.dart:1198:47)
#16     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#17     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#18     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#19     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#20     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#21     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#22     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#23     FlutterCommand.usagePath (package:flutter_tools/src/runner/flutter_command.dart)
#24     _rootRunUnary (dart:async/zone.dart:1198:47)
```
```
[✓] Flutter (Channel stable, 1.20.4, on Microsoft Windows [VersiÃ³n 10.0.19041.508], locale es-HN)
    • Flutter version 1.20.4 at D:\flutter
    • Framework revision fba99f6cf9 (3 weeks ago), 2020-09-14 15:32:52 -0700
    • Engine revision <<<<<<< HE
    • Dart version 2.9.2

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\LGARM\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: D:\Software\X64\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions.

[✓] Android Studio (version 4.0)
    • Android Studio at D:\Software\X64\Android\Android Studio
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code, 32-bit edition (version 1.49.3)
    • VS Code at D:\Software\X86\Microsoft VS Code
    • Flutter extension version 3.15.0

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.

```

## Flutter Application Metadata
**Type**: null
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: null
**Creation framework version**: null
### Plugins
connectivity-0.4.9+2
connectivity_for_web-0.3.1
connectivity_macos-0.1.0+3
firebase_core-0.5.0
firebase_core_web-0.2.0
firebase_messaging-7.0.0
flutter_secure_storage-3.3.3
geolocator-5.3.2+2
google_api_availability-2.0.4
location-3.0.2
location_permissions-3.0.0+1
location_web-1.0.0
path_provider-1.6.11
path_provider_linux-0.0.1+2
path_provider_macos-0.0.4+3
shared_preferences-0.5.8
shared_preferences_linux-0.0.2+1
shared_preferences_macos-0.0.1+10
shared_preferences_web-0.1.2+7
sqflite-1.3.1
url_launcher-5.5.0
url_launcher_linux-0.0.1+1
url_launcher_macos-0.0.1+7
url_launcher_web-0.1.2+1

**Comment by iapicca** [comment] 2020-10-04 07:13
duplicate of https://github.com/flutter/flutter/issues/60272

according to this [comment](https://github.com/flutter/flutter/issues/66415#issuecomment-701003004)
this issue might have been fixed in the master channel

**Comment by iapicca** [comment] 2020-10-04 08:42
duplicate of https://github.com/flutter/flutter/issues/60272

**Comment by darshankawar** [comment] 2020-10-05 10:47
Close as duplicate of [60272](https://github.com/flutter/flutter/issues/60272)

**Closed by darshankawar** 2020-10-05 10:47 UTC
