### ISSUE TITLE
Warning logged for deprecated `accentIconTheme`

### ISSUE THREAD

**Issue by AlexV525** [flutter/flutter#56639] opened 2020-05-08 06:26 UTC
## Steps to Reproduce

1. Run a flutter project.
2. Using inspector to select a widget.
3. When the scope floating action button of the inspector displayed, the warning logged.

![image](https://user-images.githubusercontent.com/15884415/81377211-93f8b400-9137-11ea-8e1c-62434d861f30.png)

Logs:
```
I/flutter (12802): Warning: The support for configuring the foreground color of FloatingActionButtons using ThemeData.accentIconTheme has been deprecated. Please use ThemeData.floatingActionButtonTheme instead. See https://flutter.dev/go/remove-fab-accent-theme-dependency. This feature was deprecated after v1.13.2.
```

flutter doctor:
```
[✓] Flutter (Channel stable, v1.17.0, on Mac OS X 10.15.3 19D76, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
[✓] Android Studio (version 3.6)
```

**Comment by VladyslavBondarenko** [comment] 2020-05-08 09:25
Hi @AlexVincent525 
please see https://github.com/flutter/flutter/pull/48435,
Closing, as this isn't an issue with Flutter,
if you disagree please write in the comments and I will reopen it

**Comment by AlexVincent525** [comment] 2020-05-08 09:56
Hi, actually I've already check this tips before I open it,  but I can't figure out which repo should it belong. Can you guide me to the correct one?

**Comment by VladyslavBondarenko** [comment] 2020-05-08 14:53
@AlexVincent525 
can you see warning after changing

from 
```
MaterialApp(
  theme: ThemeData(
    accentIconTheme: IconThemeData(color: Colors.red),
  ),
)
```
to
```
MaterialApp(
  theme: ThemeData(
    floatingActionButtonTheme: FloatingActionButtonThemeData(
      foregroundColor: Colors.red,
    ),
  ),
)
```
?
(as said in the "Migration guide" part of the linked PR)

**Comment by AlexVincent525** [comment] 2020-05-08 15:58
> @AlexVincent525
> can you see warning after changing
> 
> from
> 
> ```
> MaterialApp(
>   theme: ThemeData(
>     accentIconTheme: IconThemeData(color: Colors.red),
>   ),
> )
> ```
> 
> to
> 
> ```
> MaterialApp(
>   theme: ThemeData(
>     floatingActionButtonTheme: FloatingActionButtonThemeData(
>       foregroundColor: Colors.red,
>     ),
>   ),
> )
> ```
> 
> ?
> (as said in the "Migration guide" part of the linked PR)

I didn't use the `accentIconTheme` in my theme definition, but I'll try it tomorrow. Thanks.

**Comment by AlexVincent525** [comment] 2020-05-09 05:12
@VladyslavBondarenko This was solved after I defined `floatingActionButtonTheme` as the #48435 told. But my question is which one of my code affect this while I didn't use `accentIconTheme`? I think some docs might require an update.

**Comment by VladyslavBondarenko** [comment] 2020-05-11 06:43
@AlexVincent525 
it's hard for me to say, it would be easier if you check what values you do you have here https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/floating_action_button.dart#L432 and investigate where they came from

**Comment by AlexVincent525** [comment] 2020-05-11 06:48
> it would be easier if you check what values you do you have here https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/floating_action_button.dart#L432 and investigate where they came from

I think we should bring this open again though there's no obvious API usage in my case.

**Comment by AlexVincent525** [comment] 2020-05-12 04:06
For the record, the `ThemeData` with this issue occurred is:
```dart
final Color currentColor = Colors.red;

ThemeData get lightTheme => ThemeData.light().copyWith(
  brightness: Brightness.light,
  primaryColor: Colors.white,
  primaryColorBrightness: Brightness.light,
  primaryColorLight: Colors.white,
  primaryColorDark: Colors.white,
  accentColor: currentColor,
  accentColorBrightness: Brightness.light,
  canvasColor: Colors.grey[200],
  scaffoldBackgroundColor: Colors.white,
  bottomAppBarColor: Colors.white,
  cardColor: Colors.white,
  highlightColor: Colors.transparent,
  splashFactory: const NoSplashFactory(),
  toggleableActiveColor: currentColor,
  cursorColor: currentColor,
  textSelectionColor: currentColor.withAlpha(100),
  textSelectionHandleColor: currentColor,
  indicatorColor: currentColor,
  appBarTheme: AppBarTheme(brightness: Brightness.light, elevation: 1),
  iconTheme: IconThemeData(color: Colors.black),
  primaryIconTheme: IconThemeData(color: Colors.black),
  tabBarTheme: TabBarTheme(
    indicatorSize: TabBarIndicatorSize.tab,
    labelColor: Colors.black,
    unselectedLabelColor: Colors.black,
  ),
  buttonColor: currentColor,
);
```

**Comment by VladyslavBondarenko** [comment] 2020-05-12 08:57
Thanks @AlexVincent525,
I see that using `accentColorBrightness: Brightness.light` triggers the warning, because it changes `defaultAccentIconThemeColor` in [the used condition](https://github.com/flutter/flutter/pull/48435/commits/e6313de5d77483518f6b30dcf8a2789b08d8d146#diff-53c54164f747ccc01d275c01330d0fb2R420). 
This way this combination:

```
accentColorBrightness: Brightness.light,
accentIconTheme: IconThemeData(color: Colors.black),
```

doesn't trigger the warning, although `accentIconTheme` is used

@HansMuller

**Comment by AlexVincent525** [comment] 2020-05-12 09:08
> I see that using `accentColorBrightness: Brightness.light` triggers the warning, because it changes `defaultAccentIconThemeColor` in [the used condition](https://github.com/flutter/flutter/pull/48435/commits/e6313de5d77483518f6b30dcf8a2789b08d8d146#diff-53c54164f747ccc01d275c01330d0fb2R420).

Nice catch! So this might be much easier to solve.

**Comment by Hixie** [comment] 2020-06-12 19:06
Well this should under no circumstances be logging a warning, since that's against our style guide. Deprecations should be caught by the analyzer or not at all.

**Comment by markusaksli-nc** [comment] 2020-07-20 09:04
Reproducible on the latest master `1.21.0-2.0.pre.66`.

<details>
 <summary>Minimal reproducible sample</summary>

 ```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  static const String _title = 'Flutter Code Sample';

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(
        accentIconTheme: IconThemeData(color: Colors.red),
      ),
      title: _title,
      home: MyStatelessWidget(),
    );
  }
}

class MyStatelessWidget extends StatelessWidget {
  MyStatelessWidget({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Floating Action Button'),
      ),
      body: Center(child: const Text('Press the button below!')),
      floatingActionButton: FloatingActionButton(
        onPressed: () {},
        child: Icon(Icons.navigation),
      ),
    );
  }
}
```
</details>
<details>
 <summary>flutter doctor -v</summary>

 ```
[√] Flutter (Channel master, 1.21.0-2.0.pre.66, on Microsoft Windows [Version 10.0.18362.900], locale et-EE)
    • Flutter version 1.21.0-2.0.pre.66 at C:\Development\flutter_master
    • Framework revision 54c9441723 (2 days ago), 2020-07-17 18:56:12 -0400
    • Engine revision d327828632
    • Dart version 2.9.0 (build 2.9.0-21.0.dev 9dca49e71e)


[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at C:\Users\Isa\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: C:\Users\Isa\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.6.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.6.30309.148
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.0)
    • Android Studio at C:\Users\Isa\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.47.2)
    • VS Code at C:\Users\Isa\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.12.2

[√] Connected device (5 available)
    • SM G950F (mobile)       • ce12171c51cc001c03 • android-arm64  • Android 9 (API 28)
    • sdk gphone x86 (mobile) • emulator-5554      • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)       • windows            • windows-x64    • Microsoft Windows [Version 10.0.18362.900]
    • Web Server (web)        • web-server         • web-javascript • Flutter Tools
    • Chrome (web)            • chrome             • web-javascript • Google Chrome 84.0.4147.89

• No issues found!
```
</details>

**Comment by wujek-srujek** [comment] 2021-03-08 09:10
Im getting this warning even though I'm not doing any ThemeData customization, I'm using the default light `ThemeData` and additionally create a dark theme with `ThemeData.dark()`. The warning is logged whenever I switch theme modes in the app.

**Comment by maxzod** [comment] 2021-03-25 23:51
@wujek-srujek  same as you , also iam using only one fixed light theme 
```dart 
static final light = ThemeData.light().copyWith(
     pageTransitionsTheme: NoTransitionsOnWeb(),
    textTheme: GoogleFonts.tajawalTextTheme().copyWith(bodyText1: GoogleFonts.tajawal(color: Colors.black)),
    primaryTextTheme: GoogleFonts.tajawalTextTheme().copyWith(headline6: TextStyle(color: Colors.black)),
    brightness: Brightness.light,
    primaryColor: AppColors.zeroBlue,
    primaryColorBrightness: Brightness.dark,
    accentColor: Colors.white,
    secondaryHeaderColor: const Color(0xffC4822D),
    accentColorBrightness: Brightness.light,
    floatingActionButtonTheme: FloatingActionButtonThemeData(backgroundColor: AppColors.darkBlue),
    dividerColor: Colors.black,
  );
```

**Comment by oravecz** [comment] 2021-04-18 22:28
Still happens in stable 2.0.4 FWIW. Use the standard `flutter create myapp` sample. Add a dark theme, and toggle the `MaterialApp.themeMode`.

**Comment by HansMuller** [comment] 2021-06-23 19:01
@oravecz sorry about the persistent unnecessary warning. It was removed in https://github.com/flutter/flutter/pull/78296 which landed on March 15th. It's making its way into the next stable release.

**Comment by HansMuller** [comment] 2021-06-23 19:07
@markusaksli-nc - The ThemeData accentIconTheme constructor parameter and the accent parameters in ThemeData.copyWith() should have been deprecated in #81336 but were inadvertently left out. PR #85144  is intended to fix that.

**Closed** 2021-06-23 23:51 UTC
Labels: P4, a: quality, f: material design, found in release: 1.21, framework, has reproducible steps
